### ISSUE TITLE
Segregate Legacy Roles from currently used System Roles

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#10013]
Currently, all System roles are lumped together under the "System" top-level role in a very confusing way.  Legacy/Deprecated roles are mixed in with the currently active System Roles, and the list isn't even sorted (see https://github.com/dotCMS/core/issues/7949).
## Possible Solution

A few suggestions:
1. **Probably Best** (_but probably the most work and most potential to break things_): Create a new "Legacy Roles" top-level role and put all the Legacy roles under that.
   - So new users only have to see and think about the currently active roles under the "System" top level role.
2. **Probably Next Best** (_but unknown customer impact_): Hide all the legacy roles from the Roles & Tabs screen completely.
   - I'm not sure if these roles are ever actually changed by legacy customers, so I'm not sure if this would remove some necessary functionality for long-time customers upgrading to new releases.
3. **Consolation Prize** (_but definitely the easiest_): Change the Starter site so all Legacy Roles are Locked in the starter.
   - Then we can make a note on the doc pages about it, making it easier for new customers to recognize and ignore legacy roles.
#### Also:

We really need to either sort **_all_** roles (not just System roles) alphabetically (again, see https://github.com/dotCMS/core/issues/7949), or allow users to manually change the order the roles are displayed.
## Known Workarounds

I now regularly recommend to new customers in Content Architect training that they lock those roles, so they're visually distinguished from active system roles.  _(Option #3 above is really just automating this workaround by doing it in the starter site)_.
## Context
1. I've gotten questions about it during multiple Content Architect trainings.
2. A customer came up to me during the user conference specifically saying some of our documentation is really bad, and specifically mentioning the System Roles documentation.  It turns out he hasn't looked at that document since we recently upgraded it (so the docs are alot better than they were), but one of his specific complaints was how to tell the difference between active and legacy system roles.
## Your Environment
- dotCMS version used: 3.6.0
## See Also
- https://github.com/dotCMS/core/issues/7949
- https://github.com/dotCMS/core/issues/9204 (Look at item #2 - it's possible to add new roles under the top-level **System** role, and probably shouldn't be).

**Comment by jkshapiro** [comment]
See also #8349

**Comment by oarrietadotcms** [comment]
There is another client asking for this one, it would be great if we can give some kind of priority to this ticket.

Thanks!
