### ISSUE TITLE
Notify Login As changes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10019]
- [x] When you "login as", the system is refreshing the menu, but we need refresh the host selector too, this because you can see all the host that you don't have permissions as limited user.  
- [ ] When you login as, we need to refresh the username and profile pic to the person who is being logged in as

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10086

**Comment by jcastro-dotcms** [comment]
Regarding bullet #2, our NG component is not ready for displaying the user's profile pic, and back-end functionality has not been developed for that either. So, that will be handled either later on or in another ticket.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
