### ISSUE TITLE
Notify Site Browser changes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10018]
When user A changes or updates a file in the file browser, user B using the file browser should see the new files or file changes without a browser refresh.

**Comment by freddyucv** [comment]
We will generate an Event when:

- A Folder is added, deleted or updated
- A Link is added, deleted or archived
- A Page is added, deleted or archived
- A File is added, deleted or archived

**Comment by freddyucv** [comment]
we will generate an Event when  a File,Page or Link is moved too

**Comment by freddyucv** [comment]
When the Page and File are Unarchived too

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10158
https://github.com/dotCMS/core-web/pull/231

**Comment by jgambarios** [comment]
Missing work will be done in: https://github.com/dotCMS/core/issues/10302
