### ISSUE TITLE
Material design Dijit theme

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10028]
In order to match our new NG shell we need to create a new Material Design Dijit theme based on the progress we already made in 3.6.

First we need to migrate the theme changes we made in 3.6 to 3.7, make it fully working and based on those changes create a the new theme.

Related to: https://github.com/dotCMS/core/issues/9019

------
**Important Note:** We want the new Material Design dijit theme to work just with the Angular shell, without it we need to use our regular theme.

**Comment by wezell** [comment]
Started this branch:

issue-10028-materialze-dojo
