### ISSUE TITLE
Notify Layout changes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10021]
When a new portlet or tab is added or removed, people's sidebars will need to be refreshed.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10095 and https://github.com/dotCMS/core-web/pull/226

**Comment by oswaldogallango** [comment]
P.R #10095 and dotCMS/core-web#226

**Comment by bryanboza** [comment]
Some enhancements reported in the #10117
