### ISSUE TITLE
Fix Recent Content/Widgets to use ES

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10022]
## Expected Behavior
The recent contents/widgets for the NG UI needs to be calculated using elastic search

## Current Behavior
Right now we are calculating the recent contents/widgets reading from the DB and using the mod_user column (We implemented cache on top of this in order to reduce the db hits)

## Possible Solution
Remove the logic that reads from the DB and the cache logic around it and calculate using ES.

**Comment by wezell** [comment]
This is in branch #9272 I believe
