### ISSUE TITLE
Spike: Running tests in jenkins

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10033]
It is needed to figure out how to run integration and unit tests in Jenkins.

Proposed frequency
- Integration tests: nightly
- Unit tests: on each merge if possible, if not, every half or one hour
- E2E: keep the infrastructure for the servlet test runner? so e2e can run?

Thoughts from our call:
0. clone source, ./gradlew
1. Run Unit tests   <----- every merge
2. Run Integration tests in all 4 dbs   <----- every 4 hours (or once a day)

Start current process   <----- every day
3. Build Distro
4. Run end to end tests	

Time: 3d

**Comment by nollymar** [comment]
Useful links to configure Jenkins-GitHub to run unit-tests with each merge:
http://jakubstas.com/github-and-jenkins-pull-request-checking/#.WBnhk-ErL-Z
http://jakubstas.com/github-and-jenkins-integration/#.WBnhkeErL-Z
https://www.theguild.nl/building-github-pull-requests-with-jenkins/
https://github.com/jenkinsci/ghprb-plugin
https://github.com/janinko/ghprb
https://thepracticalsysadmin.com/setting-up-a-github-webhook-in-jenkins/
https://www.cloudbees.com/blog/better-integration-between-jenkins-and-github-github-jenkins-plugin

**Comment by nollymar** [comment]
Useful links to configure Gradle Plugin in Jenkins:
https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin
https://guides.codepath.com/android/building-gradle-projects-with-jenkins-ci
