### ISSUE TITLE
Remove necessity to have ant installed to execute gradle tasks

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10030]
Some tasks require to install ant for their execution. They should use the bin/ant-launcher.jar instead:
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/build.gradle#L500
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/build.gradle#L521

## Expected Behavior

Run successfully any build.gradle task in an environment without ant

## Current Behavior

The task deployWarTomcatDev requires to have installed ant to be executed

## Possible Solution

Replace the exec ant call by a javaexec call using ant-launcher.jar

## Steps to Reproduce (for bugs)

1. Execute ./gradlew deployWarTomcatDev in an environment without ant
2. The task will not be executed successfully

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10031

**Comment by dsilvam** [comment]
Note to QA: test the deployWarTomcatDev on both unix and windows. Windows without ant.

**Comment by erickgonzalez** [comment]
Tested on Ubuntu and Windows 7.
