### ISSUE TITLE
Fix current failing unit tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10035]
After running `./gradlew test` we are getting:

Unit-Tests (“./gradlew  test”): 914 tests completed, 5 failed

We need to be green :)

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/10047

**Comment by maurizo** [comment]
Cleaning up PR: https://github.com/dotCMS/core/pull/10072

**Comment by maurizo** [comment]
New PR for failing test: https://github.com/dotCMS/core/pull/10079
