### ISSUE TITLE
Being able to indicate the db properties via parameters/properties-file in the Init for ITests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10034]
We need to be able to indicate the db properties via parameters/properties-file in the Init for ITests.

Look at the work already done here:  
https://github.com/dotCMS/core/tree/issue-9272-new-content-types/dotCMS/src/integration-test/java/com/dotmarketing/util

https://github.com/dotCMS/core/blob/issue-9272-new-content-types/dotCMS/src/integration-test/java/com/dotmarketing/util/TestInitialContextFactory.java

## Expected Behavior
Being able to specify dbms from properties

## Current Behavior
Hardcoded value inside the class

## Context
Running integration tests in jenkins for every db

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10110

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/10159
