### ISSUE TITLE
Test static plugin deployment with new distro

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10039]
It is needed to verify the correct behavior of static plugin deployment using the new gradle task for generating the distribution : `./gradlew createDist`

Please test on Windows and Unix envs. 

## Expected Behavior
Static plugins deploying correctly.

**Comment by shaydotcms** [comment]
Passed QA. 
Tested issue in latest master-3.7, MySQL 5.6.23, Postgres 9.3, Firefox
Started dotCMS instance, uploaded files to root and other folders, created pages, content types, etc. Everything worked as expected
