### ISSUE TITLE
Simple Enhancement: Add Download option for OSGI Plugins

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10048]
Right now to move an OSGI plugin to another server requires access to the command line on the server to grab the plugin so that it can be deployed on another server.  We should add a download option (see photo attached), so that you can download an OSGI plugin on one server and deploy it on another, without needing command line access.

I would assume that this is a pretty easy enhancement.

![osgi download](https://cloud.githubusercontent.com/assets/1569167/19932403/aed1b03e-a0d5-11e6-844d-c8fdcd544de1.jpg)

**Comment by wezell** [comment]
Not a bad idea but osgi plugins can have config and passwords in them that could be de-compiled (for example, our oauth plugin on demo).  I think they should not be downloadable.

**Comment by DeanGonzalez** [comment]
Good point, I did not think about that.  However we could add a method for making an OSGI Plugin downloadable and then allow each plugin the ability to set a property to allow the plugin to be downloadable - set to false by default, no property set to true in the plugin, no download option.  Just a thought.

**Comment by dotcmsCodeReview** [comment]
yea i don't think we need it.  U can PP them. and if you don't have access
to a plugin then you probably shouldn't be able to download
