### ISSUE TITLE
Document how to run tests 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10045]
Documentation for instructing how to run tests is needed.

It needs to include how to:
- [ ] Run unit tests via gradle. 

- [ ] Run integration tests via gradle. 

- [ ] Run unit tests via Eclipse and IntelliJ Idea

- [ ] Run integration tests via Eclipse and IntelliJ Idea

For gradle, also include the different options available for running packages, single test class, etc.
We can include a couple and link to the [official doc ]
(https://docs.gradle.org/current/userguide/java_plugin.html#test_filtering)

**Comment by maurizo** [comment]
Integration test
==========
Properties to change and possible values.  Please replace <tomcat8> for the correct path to deployed instance.

it-dotcms-config-custer.properties
------------------------------
```
es.cluster.name=testDotCMSIndex
es.path.data=<tomcat8>/webapps/ROOT/dotsecure/esdata
es.path.work=<tomcat8>/webapps/ROOT/dotsecure/esdata/work
es.path.repo=<tomcat8>/webapps/ROOT/dotsecure/esdata/essnapshot/snaphosts
es.path.logs=<tomcat8>/webapps/ROOT/dotsecure/logs
```
it-dotmarketing-config.properties
------------------------------
```
ASSET_REAL_PATH=<tomcat8>/webapps/ROOT/assets
DYNAMIC_CONTENT_PATH=<tomcat8>/webapps/ROOT/dotsecure
VELOCITY_ROOT=<tomcat8>/webapps/ROOT/WEB-INF/velocity
GEOIP2_CITY_DATABASE_PATH_OVERRIDE=<tomcat8>/webapps/ROOT/WEB-INF/geoip2/GeoLite2-City.mmdb
TOOLBOX_MANAGER_PATH=<tomcat8>/webapps/ROOT/WEB-INF/toolbox.xml

// this one is new
context.path.felix=<tomcat8>/webapps/ROOT/WEB-INF/felix
```

**Comment by dsilvam** [comment]
https://docs.google.com/document/d/1VXKX6OoHYge1WmzLYLVMkmS0_fEkClV6-PZ4JNlcyW8/edit?userstoinvite=dean@dotcms.com&ts=583335d4#

**Comment by DeanGonzalez** [comment]
Documented:
http://auth.dotcms.com/docs/latest/testing
http://auth.dotcms.com/docs/latest/functional-tests
http://auth.dotcms.com/docs/latest/integration-tests
http://auth.dotcms.com/docs/latest/unit-tests
