### ISSUE TITLE
More Routing and URL Cleanup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10059]
I am open to discussion here but I believe we need our URLs to look like this:
```
/dotAdmin/#/login
/dotAdmin/#/browser        (where ext_browser is driven by the portlet id and not hard coded if possible, which I want to change)
/dotAdmin/#/content  <---- content search screen
/dotAdmin/#/content/asdfadsfads-asdfadsfadsf-asdfdasfadsf   <--- content edit id or inode
/dotAdmin/#/logout

```

- [ ] Move /html/ng to /dotAdmin
- [ ] Move Routing to use #

**Comment by freddyucv** [comment]
why use the '#' character? is not better just: 

/dotAdmin/login
/dotAdmin/browser      
/dotAdmin/content 
/dotAdmin/content/asdfadsfads-asdfadsfadsf-asdfdasfadsf 
/dotAdmin/logout

**Comment by dotcmsCodeReview** [comment]
It's better because it supports the back button easier when moving from a
non angular 2 app and things like this.

**Comment by jgambarios** [comment]
Check https://docs.angularjs.org/guide/$location -angular has a way to do hashbang navigation.

**Comment by wezell** [comment]
- pattern for Angular tools - `http://localhost:8080/dotAdmin/#/rules` 
- For legacy tools - `http://localhost:8080/dotAdmin/#/c/site-browser`

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/243 and https://github.com/dotCMS/core/pull/10390

**Comment by oswaldogallango** [comment]
still need to reduce the path for angular component like the rules engine one for the moment still works like this http://localhost:8080/dotAdmin/#/c/a/rules

**Comment by oswaldogallango** [comment]
Second pull request with final changes https://github.com/dotCMS/core/pull/10489 and https://github.com/dotCMS/core-web/pull/250

**Comment by bryanboza** [comment]
The new changes looks good, also we need some work in the last two points: 

/dotAdmin/#/content/**asdfadsfads-asdfadsfadsf-asdfdasfadsf**   <--- **content edit id or inode**
/dotAdmin/#/logout

**Comment by oswaldogallango** [comment]
updating some links references to portlet ids using the new portletId enum P.R https://github.com/dotCMS/core/pull/10611

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/261

**Comment by bryanboza** [comment]
Fixed, just pending the ```/dotAdmin/#/content/asdfadsfads-asdfadsfadsf-asdfdasfadsf   <--- content edit id or inode``` but seems is ok for now
