### ISSUE TITLE
Test OAuth Plugin with JWT/UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10058]
This needs to work.  Acceptance criteria will be it running on demo.dotcms.com

For frontend, we need to check if the user is on the front end login page configured in dotcms.  For the back end, we should intercept calls to /dotAdmin/* and/or /html/* and if the user does not have a JWT token, we redirect them to the oauth login first

**Comment by jdotcms** [comment]
The plugin should be able to work on BE and FE on 4.1

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11394

**Comment by jgambarios** [comment]
**Note to QA:** This is the version of the plugin we need to test https://github.com/dotCMS/plugin-dotcms-oauth/tree/master-4.1

**Comment by bryanboza** [comment]
Fixed, now we are able to deploy that plugin and upload without problems... Some new enhancements here: https://github.com/dotCMS/core/issues/11439

**Comment by bryanboza** [comment]
Need update the readme and the documentation of this plugin

**Comment by john-thomas-dotcms** [comment]
Doc completed, please review: https://auth.dotcms.com/docs/latest/oauth-authentication-plugin
