### ISSUE TITLE
Personas not displaying in tag fields on new Content Types

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10060]
Tested on dotCMS 3.6 Amazon instance and on demo.dotcms.com running 3.6

Persona tags do not appear in the suggested tag list after creating a NEW content type with a tag field.  Make sure to clear browser cache and maybe even clear dotCMS cache from maintenance portlet before testing this to avoid false positives.

The personas on tag fields appear just fine on content types that download with the starter, but not on new content types.

screencast: http://screencast.com/t/ttakdb8b

![nofirsttimeinvester](https://cloud.githubusercontent.com/assets/1569167/19970610/1ed17316-a1a2-11e6-8f82-60a6baa87d1d.jpg)
![nowealthyprospect](https://cloud.githubusercontent.com/assets/1569167/19970611/1ed192c4-a1a2-11e6-8d43-632dc0b8b624.jpg)

**Comment by shaydotcms** [comment]
I was able to replicate it locally in master-3.7 using MySQL 5.6.23 and Postgres 9.3.5 DBs
