### ISSUE TITLE
Migrate tests that make real requests to the functional-tests folder

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10078]
Some tests listed [here](https://github.com/dotCMS/core/issues/9785) should be moved to the functional-tests folder. Currently, these tests are under the integration-tests folder. However, they can not be run with right click/server down

## Expected Behavior

Tests that make real requests must be under functional-tests folder

## Current Behavior

Tests that make real requests are under integration-tests folder

**Comment by dsilvam** [comment]
CurrentSessionLanguageConditionletFTest
NumberOfTimesPreviouslyVisitedConditionletFTest
PagesViewedConditionletFTest
UsersBrowserLanguageConditionletFTest
UsersSiteVisitsConditionletFTest
VisitedUrlConditionletFTest
VisitorOperatingSystemConditionletFTest
VisitorsCurrentUrlConditionletFTest

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10096

**Comment by nollymar** [comment]
Tests still failing:
1) case01(com.dotcms.csspreproc.LessCompilerTest)
2) case01(com.dotcms.csspreproc.SassCompilerTest)
3) testCanGetResource(com.dotcms.rest.api.v1.system.i18n.I8NResourceFTest)
4) testGreaterThanComparison(com.dotmarketing.portlets.rules.conditionlet.PagesViewedConditionletFTest)
5) testNotEqualsComparison(com.dotmarketing.portlets.rules.conditionlet.PagesViewedConditionletFTest)
6) testEqualsComparison(com.dotmarketing.portlets.rules.conditionlet.PagesViewedConditionletFTest)
7) testFireOnOncePerVisitor(com.dotmarketing.portlets.rules.actionlet.SetSessionAttributeActionletFTest)
8) testSaveDeleteNotification(com.dotcms.notification.business.NotificationAPITest)
9) test(com.dotcms.publisher.endpoint.business.PublishingEndPointAPITest)
10) serializeTest(org.apache.velocity.runtime.parser.node.SimpleNodeTest)
11) uploadSnapshotTest(com.dotcms.content.elasticsearch.business.ESIndexAPITest)
12) uploadSnapshotTest_noSnapshotFound(com.dotcms.content.elasticsearch.business.ESIndexAPITest)
13) shouldWorkVirtualLinkCMSHomePage(com.dotmarketing.filters.CMSFilterTest)
14) shouldWorkVirtualLink(com.dotmarketing.filters.CMSFilterTest)
15) shouldRedirectToFolderIndex(com.dotmarketing.filters.CMSFilterTest)
16) shouldReturnStrutsPage(com.dotmarketing.filters.CMSFilterTest)
17) widgetInvalidateAllLang(com.dotmarketing.portlets.contentlet.business.ContentletAPITest)
18) findContentletsByHost(com.dotmarketing.portlets.contentlet.business.ContentletAPITest)
19) testAboutUs(com.dotmarketing.viewtools.navigation.NavToolTest)
