### ISSUE TITLE
Notify Reindex changes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10073]
When a reindex is executed a notification should be created.

The creation of the notification for the reindex process is already implemented, the problem is the notification is created for the **SYSTEM_USER** and the socket will not find a **SYSTEM_USER** to deliver the notification. 

We have to approaches here:

1. Create the notification just for the user that executed the reindex.
2. Change the notification to work with roles (we already support this mechanism), we could deliver this notification to all the admin roles.
3. We can create a global notification.

I prefer option two, @wezell @jtesser any thoughts here?.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core-web/pull/228
https://github.com/dotCMS/core/pull/10128

**Comment by bryanboza** [comment]
Some improvements needed in the cards: #10133, #10134
