### ISSUE TITLE
Jenkins job for running unit tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10085]
This job will:

- Checkout the source code from master branch (Source Code Management in Project window on Jenkins)
- Execute unit tests (gradle test) 
- Hook up the test results (xml) so jenkins can display them

Frequency will be once an hour

**Comment by oarrietadotcms** [comment]
Link: https://cb.dotcms.com/job/Git_Master_UnitTest_Runner_3.7/
Documentation: https://docs.google.com/a/dotcms.com/document/d/1T3tQSEXLPk_r8Kfsfnqva-Uf-_7TqTSzvb70lfZbtgg/edit?usp=sharing
