### ISSUE TITLE
Gradle script for managing lifecycle of remote instances and execution of integration/functional tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10087]
The gradle task will do the following:

- [ ] Interact with AWS EC2 instance (Amazon Linux): launch, setup and terminate instances (https://github.com/classmethod/gradle-aws-plugin)
- [ ] Interact with AWS RDS instance (All Supported Databases): create, setup and delete server (https://github.com/classmethod/gradle-aws-plugin)
- [ ] Execute Integration and Functional Tests by running remote commands on AWS EC2 instance via SSH: execute bash script with console output log (https://gradle-ssh-plugin.github.io/)
- [ ] Copy xml reports back for reporting

#### Important Points :

- Make sure every step logs to the console
- Make sure when we run remote commands we do so getting the output over ssh to the local gradle console so we can monitor and debug jobs 
- Gradle task can read properties like AWS Key, db, AMI to use 
- All tests should run on 1 AMI we build.  The AMI should already have the following installed:
     - Java
     - Gradle
     - Anything else we need.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10151

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10156

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10160
