### ISSUE TITLE
Restore existing snapshots create failed copies inside dotsecure/essnapshot

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10080]
When you upload a same existing snapshot, the system will continue creating failed copies inside /dotsecure/essnapshot

## Expected Behavior 
The system should avoid creating failed copies of the existing snapshot

## Steps to Reproduce 
1-Login to dotcms
2-Navigate to System> Maintenance> Index tab. Right click over any index and select "Download Index Snapshot"
3-After the index has downloaded, click "Restore Index Snapshot" button. 
4-Upload the index you have just downloaded. The first time the system creates essnapshot folder. See image below:
![image](https://cloud.githubusercontent.com/assets/8741846/20062158/3b20dc5e-a4c8-11e6-9b8f-0ceee0a45bb1.png)

5-Once the index has uploaded, repeat the process and upload the same existing snapshot again.
6-You will get notified by UI that an unexpected error occurred and a copy of the failed snapshot will be placed inside /dotsecure/essnapshot. In addition, the path /dotsecure/essnapshot/snapshot is created. 
7-If you keep uploading the same existing snapshot over and over, the system will continue creating failed copies. Image below shows **5 attempts** of uploading the same snapshot 5 times:
![image](https://cloud.githubusercontent.com/assets/8741846/20062595/f212df88-a4c9-11e6-9ded-17c5e8707031.png)

## Your Environment
- dotCMS version used: master-3.7
- Browser Name and version: Firefox v45.0.1
- Operating System and version: Ubuntu 14.04.1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8
- Database and version: Postgres 9.3.5

**Comment by dsilvam** [comment]
Nice catch @shaydotcms

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/10172

**Comment by shaydotcms** [comment]
Passed QA.
No failed copies are created when you upload a same existing snapshot.
Tested on dotcms 3.7 distro / Ubuntu 14.04.1 / Postgres 9.3.5
