### ISSUE TITLE
Optimize permissions queries for other RDBMS

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10084]
As a follow-up on https://github.com/dotCMS/core/issues/8692 and https://github.com/dotCMS/core/issues/8819 Queries related to add/update/drop/retrieve permissions on our Permissions API would require optimization for:

- Postgres.
- Oracle.
- SQL Server

Given the problems surfaced on permission individually a large site, which brought down a customer's clustered environment running 3.5.1 (See [this ticket](htps://my.dotcms.com/tickets/detail.dot?id=6d588f76-1ac9-4b8b-9274-d47530e4f6ec) for more details), a bottleneck was caused when:

1. New permissions were applied.
2. Old permissions were wiped out from the DB and Cache, leaving the cache in a cold state.
3. New permissions were requested from Frontend pages, just in the moment the new Permissions set was being applied to this new site. 

Optimization for Queries on MySQL database has reduced the time wait for new permissions to be applied, so it's advised to make similar updates to the rest of the queries, in order to:

1. Apply permissions in a timely manner, in both DB and cache.
2. Reduce unnecessary DB load from frontend requests. that could lead to a system/DB shutdown in the middle point between clearing cache and getting new permissions applied.

**Comment by joseorsini** [comment]
Update: the following EXPLAIN plan was performed over one of the queries that attempts to insert new permission references for Contents. These permissions were set at Site Level . There's a comparison in the Gist 

https://gist.github.com/joseorsini/b68109690e32b6b99524d002d4080ccf 

Between the old query and new one, and also it has an EXPLAIN plan for each one of them. This was performed with client's data on 3.5.1 (where initial issues with Permissions being applied at Site Level was reported). 

Despite the overall execution time has decreased a lot, this is one of the queries that may require further optimization, along with queries for Files, HTMLPages and Links, which basically it's data stored on folders and have those "merge joins" as query's sub-condition. 

There is more visibility of queries being executed after enabling hibernate.show_sql property on the system.properties file. This will log all queries executed by our DotConnect class.

**Comment by maurizo** [comment]
The idea on https://github.com/dotCMS/core/commit/9e021475ecac099e2d7672c88119d5de71e3e0cb was to evaluate and migrate the changes on https://github.com/dotCMS/core/issues/8692 to the supported DBs.  With that commit the work is done on Postgresql and Oracle.  There is work still pending on MSSQL.  The changes suggested on #8692 have little impact on the starter data but increasing performance on larger datasets.

**Comment by wezell** [comment]
this should be tested against large customer datasets, but in truth, it is going to be hard to do without front end load. @brentgriffin @chrismccracken any ideas?

**Comment by brentgriffin** [comment]
We have provided a large postgres dataset - relating to client who helped escalate this issue - https://my.dotcms.com/tickets/detail.dot?id=6d588f76-1ac9-4b8b-9274-d47530e4f6ec

If improves postgres, we would like to deploy as a hotfix for client running 3.5.1

**Comment by brentgriffin** [comment]
Let us know if you need us to locate clients with larger datasets that are willing to share them for Oracle and MSSQL

**Comment by agomez-dotcms** [comment]
Hi Guys,

After finishing the performance analysis previously done by @maurizo but this time against MS-SQL Server ([Documentation Here](https://drive.google.com/drive/folders/0B18_9Hxpugx8QS1JejMxMkVzUlk)), I was able to measure and implement fixes in most of the MS-SQL -specific permissions -related queries this ticket focuses on.

The analysis consisted of measuring the performance of three different (but funcionally equivalent) queries against (1) a database containing starter data and (2) a database containing starter data and 50 copies of the default host. Subtle adjustments were done on the actual MS-SQL queries after measuring the performance.

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10652

**Comment by agomez-dotcms** [comment]
Hey @dsilvam,

I just committed the refactorings to permission-reference -specific queries per your request.
I am now moving this ticket to In Review since PR is already submitted.

Thanks,
Anibal
