### ISSUE TITLE
Error is showing when you try to upload file via WebDav Finder

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10091]
When you try to upload a non empty file (png, txt, pdf, etc) **_to the root_** of dotcms using the new path (/webdav/live or working/1, 2, 3, etc), the first time you will get this error:
<img width="399" alt="ed69e50e-3b1b-473a-a325-e55e4f1ef5ce" src="https://cloud.githubusercontent.com/assets/8741846/16658114/5a646f06-4422-11e6-8e3e-eafa52ef2d25.png">
The second time that you try again, it gets successfully uploaded
This error is not present when you upload the file inside a folder
There's no error in the logs
This issue happens also with multi-lingual files and is not happening with Cyberduck

## Expected Behavior
The system should upload the file via WebDav the first time.

## Current Behavior
Currently, you have to upload the file via WebDav twice before you can see it in demo.dotcms.com

## Steps to Reproduce
1- Connect to dotcms using Webdav(Finder). Follow this documentation to set up the connection property: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav#MacOS
2- Upload a non-empty file (png, txt, pdf, etc) **_to the root_** of dotcms. The first time you do it, you will get the error code -36

## Your Environment
- dotCMS version used: Latest master-3.7
- Browser Name and version: Firefox v45.0.1 & Chrome
- Operating System and version: Ubuntu 14.04.1 & Mac OS 10.10.5
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8
- Database and version: Postgres 9.3.5 & MySQL 5.6.23

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10121

**Comment by DeanGonzalez** [comment]
Tested, working on uploading files at the host level in multiple languages, creating folders at host level, and uploading multilingual files to those new folders.
