### ISSUE TITLE
Undeployed Dynamic Plugin returns after OSGi Framework Restart

### ISSUE THREAD

**Issue by pmooneyarchitech** [dotCMS/core#10103]
A dynamic plugin which has been uploaded to DotCMS through the admin console and then later undeployed, will return when the OSGi framework is restarted via the 'Restart Framework' button in the admin console.

## Expected Behavior

When a dynamic plugin is undeployed, it is expected that it remains undeployed through framework restarts or DotCMS restarts. 

## Current Behavior

When restarting the OSGi framework or DotCMS, any undeployed plugins should not return. They should remain undeployed.

## Possible Solution

The dynamic plugin jar remains in the `felix/load` folder. When the plugin is undeployed, perhaps it's jar should be removed from this folder.

## Known Workarounds

The plugin jar can be manually removed from the felix/load folder. However this is not an option without admin access to the machine hosting DotCMS.

Another alternative is to deploy a replacement plugin with the same name but an empty Activator in order to achieve the effect of removing that dynamic plugin's code from DotCMS.

## Steps to Reproduce (for bugs)

1. In the DotCMS admin console, navigate to the Dynamic Plugins section.
2. Upload a jar for a dynamic plugin.
3. Undeploy the dynamic plugin by clicking the 'undeploy' link
4. Click the 'Restart Framework' button. Alternatively, restart DotCMS.
5. Observe the dynamic plugin has returned to the 'Dynamic Plugins' section.

## Context

I'm developing with a DotCMS environment where I do not have admin access to DotCMS' host machine (eg, this is the case with DotCMS cloud). In my case I need to retire and remove a plugin which is no longer being used, and is detrimental to leave in place.

## Your Environment

* dotCMS version used: 3.5
* Browser Name and version:
* Operating System and version: 
* Application Server and version:
* Java Brand and version: 
* Database and version:
* Application module (if apply):

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10584

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/10586

**Comment by erickgonzalez** [comment]
If the OSGI plugin is undeployed and you restart the framework or dotcms, it stays undeployed.
