### ISSUE TITLE
Error deploying static plugins in Unix and Windows

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10105]
There's an error when you try to run deploy-plugins command either on Unix or Windows:
https://gist.github.com/shaydotcms/65c94d40cfeff75f60e588db5964d770

## Expected Behavior
Deploy-plugins should build successfully

## Current Behavior
There's an error that don't allow to run successfully deploy-plugins.sh or deploy-plugins.bat
https://gist.github.com/shaydotcms/65c94d40cfeff75f60e588db5964d770

## Steps to Reproduce
1- Generate a distribution of dotcms-3.7 directly from core master-3.7
2- Configure your dotCMS so you'll be able to deploy your plugins successfully. Follow this doc if you need help http://dotcms.com/docs/latest/root-folder-in-plugins
3- Deploy your plugins by running the following commands inside your distribution of dotCMS:
* deploy-plugins.sh (Linux, Unix-based)
* deploy-plugins.bat (Windows)
4- The system will generate the error mentioned before and the plugins won't be deployed.

## Your Environment
- dotCMS version used: Latest master-3.7
- Browser Name and version: Firefox v45.0.1 & Chrome
- Operating System and version: Ubuntu 14.04.1 / Win7 Pro SP1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8
- Database and version: Postgres 9.3.5 / SQLServer 2012

**Comment by nollymar** [comment]
ant-contrib.jar was deleted with the ant upgrade. Included again in PR: https://github.com/dotCMS/core/pull/10106

**Comment by shaydotcms** [comment]
Passed QA. 
Tested issue in latest master-3.7, MySQL 5.6.23, Postgres 9.3, Firefox
Started dotCMS instance, uploaded files to root and other folders, created pages, content types, etc. Everything worked as expected
