### ISSUE TITLE
JWT Rememberme isn't working with ldap authentication 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10109]
Related to #10083 

We are having problems with the rememberme functionality using ldap to authenticate, the JWT is not making the reauthentication process ...

We are having this error on log: https://gist.github.com/bryanboza/89efd04d32a5f5b2269725e70bf9b991

## Steps to Reproduce (for bugs)
- Login in to the new UI using an ldap user (Check the remember-me option )
- Delete the JSESSIONID cookie
- Reload the page

## Your Environment
Tested on master-3.7
Windows Server 2012
Database: H2
Browser: Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/395

**Comment by bryanboza** [comment]
After the last changes, now we don't have the NPE, but isn't auto-login
```INFO enterprise.LDAPImpl: No password supplied for username: bryan```

**Comment by bryanboza** [comment]
Tested disabling the property ```auth.impl.ldap.syncPassword``` in the ```portal.properties``` file, and neither works... We have a bug here

**Comment by wezell** [comment]
We should never Sync passwords from an IDP.

**Comment by jdotcms** [comment]
Got it!

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10356

**Comment by bryanboza** [comment]
Ok, after this fix now we can auto login, but maybe we need document that if you change something in the ldap or active directory, we still login normally, because we are not synchronizing with the external system ... @john-thomas-dotcms
