### ISSUE TITLE
JWT inconsistencies    

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10108]
We are having authentication problems with the JWT process, this becacuse when you don't have the json.web.token.allowhttp property enabled, and you delete the JSESSIONID coockie, the system is redirecting to the login page, but if you refresh this page, we are login  into the backend without credentials 

FYI: After test the same process in the old UI, this works fine, the problem is only the NG2 UI.

## Steps to Reproduce (for bugs)
1. Login in to the new UI (Check the remember-me option ) 
2. Delete the JSESSIONID cookie 
3. Reload the page 
4. Reload again without credentials 

## Your Environment
Tested on master-3.7 
Windows Server 2012
Database: H2 
Browser: Chrome

**Comment by jdotcms** [comment]
Basically the parameter is not restricting the autologin!

**Comment by jdotcms** [comment]
On it

**Comment by jdotcms** [comment]
Currently the login.jsp is taking the user id from the JWT cookie and do the autologin in the jsp.
We are ok to keep this hack functionality since it will be remove in the future in favor of the Angular login.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10228

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
