### ISSUE TITLE
Viewtools: ContentMap is not respecting language for pulling Images/Fields

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10119]
For Content Types with Image/File fields, a FileAssetMap object is returned once a content is pulled via Velocity code (using the $dotcontent tool), however we're getting inconsistent results if the image and the content were created with a non-default language.

## Expected Behavior
The right file should be pulled, regardless of its language.

## Current Behavior
The system is trying to pull the default language version of the file by default (see [here](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/viewtools/content/ContentMap.java#L203)) which ends up calling the cached version of the file with the default language (see [here](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/cache/LiveCache.java#L211))

## Possible Solution
Fix was tested on 3.6.0

## Known Workarounds
no workarounds are available for this

## Steps to Reproduce (for bugs)
1. Create an Event content in a non-default language.
2. Upload an image to the portal and save it with the same language the Event was created.
3. Pull the content in frontend using $dotcontent.find("content_identifier").
4. Then, pull the image by calling $content.image or whatever its velocity var name is. It returns nothing. 

The dotcms-velocity.log file returns this 
```
[15/11/16 10:01:14:269 EST] ERROR content.ContentMap: Unable to retrive Field or Content: Can't find contentlet: a6048d7c-344d-4ea9-b572-9a3c4b3551ea lang:1 live:true
```

Which means it's trying to pull the image/field by the default language (langId = 1) when the actual language of the content and the image is different (in our tests, the langId = 3)

## Context
Reported by cloud customer: https://my.dotcms.com/tickets/detail.dot?id=b178c604-7cb4-4ca9-8fb4-274867cf28df

## Your Environment

* dotCMS 3.6.0
* Any Browser.
* CentOS 6.5, MacOS Sierra.
* Tomcat 8.0.18.
* Oracle Java 8, OpenJDK 8.
* Postgres 9.3.5.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10120

**Comment by oarrietadotcms** [comment]
Working just fine.
