### ISSUE TITLE
Add Icons for Bulgarian and Romanian Languages

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#10112]
The Icons for Bulgarian and Romanian Languages

## Expected Behavior

We are missing the Icons for Bulgarian and Romanian Languages
https://github.com/dotCMS/core/tree/master-3.7/dotCMS/src/main/webapp/html/images/languages

## Current Behavior

The icons missing.

## Possible Solution

Add the icons here: https://github.com/dotCMS/core/tree/master-3.7/dotCMS/src/main/webapp/html/images/languages

**Comment by jdotcms** [comment]
The changes has been committed on 3.7, in addition there is a hotfix for 3.6:
https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-10112_v3.6

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10115

**Comment by jgambarios** [comment]
@jdotcms there is something else to do here or we can send this to QA?

**Comment by jdotcms** [comment]
yeah, I already marked it as "need qa"
thx

**Comment by oarrietadotcms** [comment]
![screen shot 2017-03-08 at 10 43 09 am](https://cloud.githubusercontent.com/assets/8225685/23713580/03be4c50-03ec-11e7-865d-7302842ffe00.png)

bg and ro languages icons are displayed just fine
