### ISSUE TITLE
AWS Setup for running of Integration and E2E tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10116]
Setup of the following items need to be done in AWS:

- [ ] IAM User Access Key credentials
- [ ] Security Policy with corresponding access permissions
- [ ] EC2 Key Pair with corresponding public/private keys
- [ ] Default Virtual Private Cloud (VPC)
- [ ] Security Group with Inbound Rules for SSH and Database Ports 
- [ ] Creation of AMI (JDK 1.8, Gradle, GIT and Ant)

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10151

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10156

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10160
