### ISSUE TITLE
Adjustments to build-tests.xml to run functional tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10129]
Some adjustments need to be done to this ant script to be able to run the functional tests with the new process. Also some of the work used to be done here is now done at other places, so it needs to be cleaned up as well.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10151

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10156

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10160
