### ISSUE TITLE
Jenkins jobs to run integration/functional tests in different db's 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10123]
One Jenkins job per dbms. Each will trigger integration/functional tests once a day by:
- Setting up AWS credentials and execution environment
- Running gradle script for remote tests against AWS EC2/RDS instances
- Publish/Show tests result report
- Generate output expected by the nightly job

**Comment by oarrietadotcms** [comment]
https://cb.dotcms.com/view/master-3.7/
