### ISSUE TITLE
Bash Script for Running Tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10124]
Write a bash script that will run the tests against all supported databases. This one is to be executed on the remote instances.

- Clone code from Github
- Configure and Run E2E tests
- Configure and Run Integration tests
- Zip and Transfer tests output files

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10151

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10156

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10160
