### ISSUE TITLE
We are deleting the notifications in the logout 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10135]
## Expected Behavior
If you have some notifications read, and you logout, after login again, you should have the same notifications  

## Current Behavior
When you logout, the system is deleting all the notifications from the database 

SC: http://screencast.com/t/fOIY6pqSn

## Steps to Reproduce (for bugs)
- Login 
- Generate some notifications 
- Mark as read 
- Logout 
- Login again and open the notification window 

## Your Environment
Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
Same problem as: https://github.com/dotCMS/core/issues/10133

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10252

**Comment by bryanboza** [comment]
Fixed, tested in the last master-3.7 // H2 // Chrome
