### ISSUE TITLE
Login as is not cleaning notifications 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10134]
## Expected Behavior
We need clear the notification every time you login as 

## Current Behavior
If you generate any notification just for admin users, and you login as any limited user, the system are showing the notification 

## Possible Solution
Need clear this window every time you login as 

## Steps to Reproduce (for bugs)
- Login as admin
- Generate a reindex notification  (this should be only for admin users)
- Read this 
- Login as Chris Publisher (limited user)
- Try to read the notifications 

## Your Environment
Tested on master-3.7 // MySQL // FF

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10176
https://github.com/dotCMS/core-web/pull/232

**Comment by jgambarios** [comment]
The **WebResourceTest** test started to fail after the changes on this ticket and is going to be fix it in https://github.com/dotCMS/core/issues/10191
