### ISSUE TITLE
New UI - No way to apply license

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10130]
Looks like we are missing the icon class "downloadIcon"

![screen shot 2016-11-17 at 11 25 05 am](https://cloud.githubusercontent.com/assets/934364/20397680/a5336218-acb8-11e6-9d3c-439b8ad8cd4c.png)

**Comment by dotcmsCodeReview** [comment]
maybe there is a business model here.  Try to buy another and maybe it will
work
