### ISSUE TITLE
Mark notifications as read should be individual by user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10133]
We are having problems with the notification, this because when you have a new notification we are showing a notification alert in the UI, but if you read that, the notification disappear.

This because we are setting a field in the database, and this is for all the users, then when you login as different user, the system shows the notification read. This notifications should be individual for every user. 

SC: http://screencast.com/t/rrmgniE9

Steps: 
- Login as admin user
- Generate a reindex notification 
- Login as other admin user 
- Check the notifications 

## Your Environment
Tested in the last master-3.7 
Database: MySQL
Browser: Chrome and FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10252

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
