### ISSUE TITLE
Fix HostAPITest DeleteHost IT

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10144]
It has issues when running on jenkins: https://cb.dotcms.com/job/Git_Master_Int_Funct_Test_Runner_3.7_MySQL/8/testReport/junit/com.dotmarketing.portlets.contentlet.business/HostAPITest/testDeleteHost/

The problem is that the copy host is taking more than the max time established by the test. So the idea we have is not fire a quartz job with the copy host but instead call the HostAssetsJobImpl.run passing the JobExecutionContext with the map of parameters, so the host copying is sync and we don't need to completion checking.

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/10192
