### ISSUE TITLE
When finding a contentlet by identifier, if the live content is requested by it does not exists, then return null

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#10150]
When an user calls the ESContentAPIImpl, findContentletByIdentifier with the live flag in true but the content is not live, null should be returned.

Currently is throwing an exception to the higher layers.

## Expected Behavior

If the content is not live, should return null.

should return null.

## Current Behavior

currently if the user ask for a content live, and it is not actually live will thrown an exception.

check if the content is not live, and return null instead.

## Possible Solution

Check if the content is live, otherwise return null.

## Known Workarounds

No any workaround

## Steps to Reproduce (for bugs)

1. See ticket: https://my.dotcms.com/tickets/detail.dot?id=8cc40eb2-0737-4ab2-8f68-676c16a03997
2.

## Your Environment

* dotCMS version used: 3.5
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by dsilvam** [comment]
@jdotcms what about Optional?

**Comment by jdotcms** [comment]
not sure, the rest of the code are expecting a null.

**Comment by joseorsini** [comment]
Steps to reproduce: 

1. On a demo site, clone demo.dotcms.com site. Let's call this new site "todelete.dotcms.com".
2. Once the site is cloned, stop todelete.dotcms.com site. 
3. Then, right click on this stopped site and add it to a bundle. 
4. Go to Publishing Queue -> Bundles and look for the Bundle you created with the site you stopped.
5. Click on "Download for UnPublish".

Stacktrace: 
https://gist.github.com/joseorsini/59558844377d63865091e22bb54bfec7

Backend returns error 500.
