### ISSUE TITLE
Modify PublishingEndPointAPITest not to rely on number of endpoints

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10152]
This test assumes there are no endpoints created as a precondition, which might not be always the case. 

See here: https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/integration-test/java/com/dotcms/publisher/endpoint/business/PublishingEndPointAPITest.java#L93-L97

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/10185
