### ISSUE TITLE
PersonaActionletFTest.addPersona failing on remote server

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10155]
This seems to be due to a functional test calling the integration service init

com.dotmarketing.portlets.contentlet.business.FileAssetTest extends ContentletBaseTest and it doesn't need / shouldn't to. 

This might be the cause of the failure. 

https://cb.dotcms.com/view/master-3.7/job/Git_Master_Int_Funct_Test_Runner_3.7_Postgres/31/testReport/junit/com.dotmarketing.portlets.rules.actionlet/PersonaActionletFTest/addPersona/

**Comment by agomez-dotcms** [comment]
Hey Daniel, you may ignore the PR. In interest of having the tests running successfully for this Monday, I already committed these changes directly on master-3.7. I did tests over these changes and they actually fixed the problem. Apologies for not waiting but I wanted to have it working on Jenkins in advance so we don't compromise the demo. The commit is e1fc634
