### ISSUE TITLE
Insure PP works with the new ContentTypes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10169]
Description by @erickgonzalez :
Test in All DB's (Postgres, MySQL, MSSQL, Oracle) and also test fresh install of 3.8.0 and upgrade from 3.6.0 as well.

- [x] Create a new Content (Page, File, Content Generic) and PP.

- [x] Create a new Content Type and PP.

- [x] Create a new Content of the Content Type just created and PP.

- [x] Update an existing Content Type and PP.

- [x] Update an existing Content (Page, File, Content Generic) and PP.

- [x] Create a new Content Type, create a Content and PP. The ContentType should be pushed as a dependency of the content. 

- [x] Create a Page and PP, move the Page and PP, the move of the Page is successful.

- [x] Create a new Content (Page, File, Content Generic) in Spanish and PP.

- [x] Create a new version of an existing Content (Page, File, Content Generic) in Spanish and PP.

- [x] Create a bundle with different kinds of Contents and PP.

- [x] Create a new Relationship and PP.

- [x] Modifiy an existing Relationship and PP.

- [x] Perform all steps above with upgrade from 3.6.0

**Comment by dsilvam** [comment]
We need to test all dbs here

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10287

**Comment by dsilvam** [comment]
Note to QA: Tested in MySQL. Please test the remaining.

**Comment by wezell** [comment]
One thing we need to do and maybe this is another card is to remove the Structure and Field entries in the hibernate.hbm files and ensure that everything still works with the new APIs

**Comment by shaydotcms** [comment]
Failed QA. Unable to push new content types. Waiting for fix on #10324

**Comment by shaydotcms** [comment]
Still needs work. 
- [x] Push publish working successfully with fresh install of dotcms_4.1
- [x] Push publish working successfully after upgrade using starter data
- [ ] Reindex is failing after upgrading from dotcms_3.6.0 to dotcms_4.1 using client's db. Reindex gets stuck at some point, therefore it's not possible to ensure whether PP is working with client's db.

Reindex is successfully executed when the upgrade is to dotcms_4.0

Tested on latest master_4.1
Postgres 9.3.5
Ubuntu 14.04.1 / Mac OS 10.10.5
Firefox v45.0.1

**Comment by nollymar** [comment]
Reindex also fails on this environment:
Master 4.1
MySQL (client DB)
Mac OS
Google Chrome

Log details: https://gist.github.com/nollymar/85e1299db343b40cf31b661a993988fb

**Comment by shaydotcms** [comment]
Passed QA.
Content types were pushed successfully after upgrade from 3.6 to 4.1 using starter and client data
Tested on latest master-4.1
Postgres 9.3.5
Ubuntu 14.04.1 / Mac OS 10.10.5
Firefox v45.0.1
