### ISSUE TITLE
Regression tests for Content Types in MySQL

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10179]
Desc by Shay:
Using a MySQL DB, confirm that you are able to accomplish below tasks through the UI:
- [x] You can navigate to Content Types portlet
- [x] Content types dropdown is functional
- [x] "Search" and "Reset" buttons are functional
- [x] "Show System" checkbox is functional
- [x] Sort by columns works
- [x] You can create/modify a new content type
- [x] You can view Entries and Relationships
- [ ] You can relate content to the new content type (i.e.: if you have a new content type which type is "page", make sure that you can create a page and use this new content type)

**Comment by shaydotcms** [comment]
Pending tasks are waiting for merge on 3.8 (#10255)

**Comment by shaydotcms** [comment]
Failed QA.
Error is showing up in the logs once you create/edit a content type
https://gist.github.com/shaydotcms/a6d984ce610105ac1339ac74677aa7ca

**Comment by dsilvam** [comment]
Pending for https://github.com/dotCMS/core/issues/10246

**Comment by shaydotcms** [comment]
Passed QA.
All tasks were accomplished successfully.
