### ISSUE TITLE
Move current password in the Login As modal

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10187]
The **Current Password** in the **Login As** modal is a required field and needs to be move in top of the **Change Password** checkbox.

As it is right now looks like it is only required when the user wants to change his password when it is actually required for any operation on that modal.

![loginas](https://cloud.githubusercontent.com/assets/923947/20573886/96f45fa4-b177-11e6-9c04-034f3ce30b6d.png)

**Comment by jgambarios** [comment]
Also we need to replace all the Angular Material components in order to use Prime NG components.

**Comment by oswaldogallango** [comment]
this is the new look and feel with primeng 
<img width="1328" alt="screen shot 2016-11-28 at 4 41 56 pm" src="https://cloud.githubusercontent.com/assets/1569280/20687623/30c178d0-b58b-11e6-8718-278d7c7ba66e.png">

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/237

**Comment by jgambarios** [comment]
Also we need to replace the dialog to use: http://www.primefaces.org/primeng/#/dialog

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/239. this is the look and field using the prime ng dialogs for the My Account and Login As. Need some styling improvement.

My Account
<img width="1205" alt="screen shot 2016-11-30 at 2 03 36 pm" src="https://cloud.githubusercontent.com/assets/1569280/20766803/d90382a6-b705-11e6-8c66-ac76d361e254.png">

Login As
<img width="1207" alt="screen shot 2016-11-30 at 1 58 05 pm" src="https://cloud.githubusercontent.com/assets/1569280/20766764/b2233258-b705-11e6-8205-c2b530b032de.png">

<img width="1208" alt="screen shot 2016-11-30 at 1 58 26 pm" src="https://cloud.githubusercontent.com/assets/1569280/20766769/b80edc1c-b705-11e6-9a9f-6fb3c810a51d.png">

<img width="1205" alt="screen shot 2016-11-30 at 1 59 11 pm" src="https://cloud.githubusercontent.com/assets/1569280/20766774/bc2f2824-b705-11e6-960a-4798b040d715.png">

**Comment by bryanboza** [comment]
Fixed, tested on master 3.7 // H2 // FF
