### ISSUE TITLE
Verify that Integrity Checker works with the new ContentTypes Impl

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10182]
Confirm that whole Integrity Checker functionality is working when the actions below are executed:
- [x] You can create the same content type in the sender and the receiver
- [x] Through the UI, "View Conflicts" button appears after you hit "Check Integrity" and the system finds the conflicts with the same content type in the sender and the receiver
- [x] When you click "Discard Conflicts" button and run "Check Integrity" again, the system finds again the conflicts
- [x] When you click "Close" button, the system still shows the conflicts
- [x] Content Types tab is showing the current conflicts between the local and remote node
- [x] You can fix the conflicts at Local Node
- [x] Fix the conflicts at the Remote Node
- [x] Try the same with File, Folder, Page

**Comment by erickgonzalez** [comment]
All works! But found an issue when trying to create a folder.
