### ISSUE TITLE
Notify Site Browser changes is generating double notification 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10198]
Related to #10018 

## Expected Behavior
After you change any thing in the site browser, the system should send a notification  to all the users with access to the edited content or folder .

## Current Behavior
If you add a new page in to the folder, the system is sending double notification to all the users

## Steps to Reproduce (for bugs)
- Login
- Create a new folder
- Add permissions to any limited user 
- In other browser login as the limited user 
- Add a new page as admin into the folder 

## Your Environment
Tested in the last master-3.7 // h2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10250

**Comment by bryanboza** [comment]
We are unable to receive this notifications, needs work

**Comment by bryanboza** [comment]
We still having double notifications when you add menu links...

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10514
https://github.com/dotCMS/core-web/pull/254

**Comment by bryanboza** [comment]
All the changes was reverted, for now we don't have actions...
