### ISSUE TITLE
Unable to publish bundle that contains special characters

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10195]
A new bundle was created using accents in one of its folders. When trying to upload and publish it, the process fails.

Ticket details: https://my.dotcms.com/tickets/detail.dot?id=e6f44ad8-446a-4ccd-aed7-6839eb2e0681

## Expected Behavior

Bundles folders must support special characters in general

## Current Behavior

If a new bundle is created with special characters in any of its folder, the publishing process fails

## Known Workarounds

Folders in the bundle file need to be renamed without special characters

## Steps to Reproduce (for bugs)

1. Create a bundle with a folder that contains special characters
2. Upload bundle
3. Verify bundle status: Failed to Publish

## Context

This bug was reported by a client. The fix was included as part of the pull request

## Your Environment

* dotCMS version used: 3.7.0
* Browser Name and version: Google Chrome
* Operating System and version: MacOS Capitan
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres
* Application module (if apply): Push Publishing

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10196

**Comment by erickgonzalez** [comment]
Tested with a folder named: "crédito" and a bundle "Èéêë", working as it should.

**Comment by fitzciaran** [comment]
We have had publishing blocked due to this issue, so glad this being looked at. While the fix is not released we managed to get it working by using an osgi dynamic plugin to override some of the dotcms bundling code.
