### ISSUE TITLE
An invalid character in Cookie value

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#10190]
An invalid character [44] was present in the Cookie value

## Expected Behavior

com.liferay.portal.auth.BasicAutoLogin.login is storing a query string but it is not encoded, and some cases is throwing an error. Shouldn't be throwing it.

Decode the query string pass to the cookie

## Current Behavior

Some actions throws a 500 b/c the issue

Decode the query string on the cookie

## Possible Solution

For 3.6 decode on the BasicAutoLogin, on 3.7 it is not needed

## Known Workarounds

No any

## Steps to Reproduce (for bugs)

For instance if you go to any struts action with a query string with an invalid character will throw the 500

1. Get log in
2. Got to any content type
3. Export
4. If the query string has an invalid character will throw an 500

## Context
javax.servlet.error.exception=java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value
java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:160) at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:109) at org.apache.catalina.connector.Response.generateCookieString(Response.java:989) at org.apache.catalina.connector.Response.addCookie(Response.java:937) at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:386) at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58) at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58) at com.liferay.portal.auth.BasicAutoLogin.login(BasicAutoLogin.java:73) at com.liferay.portal.struts.PortalRequestProcessor.processPath(PortalRequestProcessor.java:303) at com.dotmarketing.struts.PortalRequestProcessor.processPath(PortalRequestProcessor.java:29) at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:168) at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:160) at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277) at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:185) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)

## Your Environment

* dotCMS version used: 3.6
* Browser Name and version: any
* Operating System and version: any
* Application Server and version: tomcat
* Java Brand and version:
* Database and version: mysql
* Application module (if apply):

**Comment by DannyGloudemans** [comment]
We experience the same behavior in dotCMS 3.7.1. The problem has something to do with the comma's in the query parameter expFieldsValues:

`/c/portal/layout?p_l_id=71b8a1ca-37b6-4b6e-a43b-c7482f28db6c&p_p_id=EXT_11&p_p_action=1&p_p_state=maximized&p_p_mode=view&_EXT_11_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_EXT_11_cmd=export&_EXT_11_referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3D71b8a1ca-37b6-4b6e-a43b-c7482f28db6c%26p_p_id%3DEXT_11%26p_p_action%3D1%26p_p_state%3Dmaximized%26_EXT_11_struts_action%3D%2Fext%2Fcontentlet%2Fview_contentlets&expStructureInode=57644521-4494-472b-8e29-b27421ae40b8&expFieldsValues=Faq.brand1,,Faq.code,,Faq.question,,Faq.answer,,languageId,1&expCategoriesValues=&showDeleted=false&expCurrentSortBy=modDate%20desc&filterSystemHost=false&filterLocked=false&filterUnpublish=false`

**Comment by vermastuti** [comment]
CookieProcessor is a new configuration element, introduced in Tomcat 8.0.15. The CookieProcessor element allows different cookie parsing configuration in each web application, or globally in the default conf/context.xml file.

According to official docs at [Apache Tomcat 8 Configuration Reference Version 8.0.47](https://tomcat.apache.org/tomcat-8.0-doc/config/cookie-processor.html) :

**The standard implementation of CookieProcessor is: org.apache.tomcat.util.http.LegacyCookieProcessor. Note that it is anticipated that this will change to org.apache.tomcat.util.http.Rfc6265CookieProcessor in a future Tomcat 8 release.**

Later..

According to official docs at [Apache Tomcat 8 Configuration Reference Version 8.5.23](https://tomcat.apache.org/tomcat-8.5-doc/config/cookie-processor.html)

**The standard implementation of CookieProcessor is org.apache.tomcat.util.http.Rfc6265CookieProcessor**

To resolve this issue: add this line in conf/context.xml at location %CATALINA_HOME% (i.e. C:\apache-tomcat-8.5.20\conf\context.xml in my case):

`<CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" />`

This is how it looks like after adding:

```
<?xml version="1.0" encoding="UTF-8"?>

<Context reloadable="true">
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>
    <Transaction factory="bitronix.tm.BitronixUserTransactionObjectFactory"/>
    <CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" />    
</Context>
```
