### ISSUE TITLE
Error: Notify Delete Folder in Site Browser

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#10199]
After solve this issue:

https://github.com/dotCMS/core/issues/10018

Any change in the site browser is notify, so If we have two users A and B for example, both of them working into the Site Browser portlet and the A user change any contentlet then the B user should see the change.

## Expected Behavior
When the user A deletes a folder then user B should see the change, of course only if B has permission on the folder.

## Current Behavior
If user B is not a Admin user is not notify when the folder is deleted

## Possible Solution
After user A deletes the folder a Event is created, after that this event is sent to all the users who has permissions on the deleted folder, when the user B permissions are checked the folder does not exists anymore and that is why the event notification is not sent to user B. 
If user B is an admin user then a specific permission is not checked as you can see here:

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java#L341

## Steps to Reproduce (for bugs)
1. Login with user A, and navigate to the Site Browser
2. Login with user B (not Admin), and navigate to the Site Browser
3. A delete a Folder, B have to have permission to see the deleted folder
4. B don't get refresh of the Site Browser

Maybe the error occur with DELETE_LINK and DELETE_BASE_CONTENT_TYPE events too

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10294

**Comment by bryanboza** [comment]
Fixed, some enhancements reported on #10320
