### ISSUE TITLE
We are sending notification to reload the page, when you are editing//adding content via site browser 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10200]
Related to #10018 

## Expected Behavior
The site browser notification should be showed O/NLY if you are in the site browser. 

## Current Behavior
But if you via site browser open any page in editing mode, and try to add content, when  the system detect some change in the folder/content, shows a notification to reload the page and you lost the info... 

This because the Angular Routing, is located in the site browser, and when you try to add the content change the window via iframe. 

## Steps to Reproduce (for bugs)
- Login
- Add a new folder 
- Add a new page and add individual permissions to a limited user 
- Login in another browser as limited user and try to add a new content to the page 
- As admin add another page or edit the existing  one

## Your Environment
Tested in the last master-3.7 // h2 // FF

**Comment by jgambarios** [comment]
This won't happen anymore after https://github.com/dotCMS/core/issues/10302
