### ISSUE TITLE
Fix startup and db-related issues with ContentTypes

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10203]
Fix queries with "like" conditions for dbs with case sensitive like. (Postgres, Oracle, ?)

https://github.com/dotCMS/core/blob/master-3.8/dotCMS/src/main/java/com/dotcms/contenttype/business/sql/ContentTypeSql.java#L18

https://github.com/dotCMS/core/blob/master-3.8/dotCMS/src/main/java/com/dotcms/contenttype/business/sql/ContentTypeSql.java#L48-L59

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10230

**Comment by oarrietadotcms** [comment]
Note for QA: We need to test in every instance from a clean start and also from an upgrade.

**Comment by oarrietadotcms** [comment]
[MySQL upgrade log 3.6.0-3.8.0](https://gist.github.com/oarrietadotcms/b982aa9dd1aa802ec69f8fcab9f680fb)

**Comment by erickgonzalez** [comment]
Postgres no issues found https://gist.github.com/erickgonzalez/f485d7adb4ea7e23205d95704c22aeda

**Comment by erickgonzalez** [comment]
MSSQL having issues https://github.com/dotCMS/core/issues/10336

**Comment by erickgonzalez** [comment]
ORACLE: After Applying this fix https://github.com/dotCMS/core/pull/10345 the upgrade went good https://gist.github.com/erickgonzalez/7772669827590d066f069d8c4f1b91cd

**Comment by erickgonzalez** [comment]
MSSQL: after some fixes https://github.com/dotCMS/core/pull/10380 https://github.com/dotCMS/core/pull/10383 https://github.com/dotCMS/core/pull/10377 the upgrade to 3.8 went good 

https://gist.github.com/erickgonzalez/1b5477184acc690fcdca0be3e94fb58e

**Comment by wezell** [comment]
We need to test this against client dbs

**Comment by dsilvam** [comment]
Note to QA: Please test against client dbs

**Comment by nollymar** [comment]
Tested successfully on client dbs: Postgres and MySQL
