### ISSUE TITLE
Confirm permissions functionality with the new ContentTypes Impl

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10202]
- [x] Test # 1
1) Create a new structure with a text field and edit the host or folder field on the structure and assign it to demo.dotcms.com
2) Create a new role and assign the role to the demo host with publish on child structures on the host and edit on the host itself... publish on all the rest of the child objects on the host
3) Assign that role to a new user, login as that user, and make sure the limited user can use and contribute content on that new structure.

------------------------------

- [x] Test # 2
1) Create a new Role
2) Assign that New role to demo host (individually permission), with ability to add/edit on host and Publish on Child Content and Child Structures under the host
3) Create a new structure and in the Host or Folder system field, choose demo.dotcms.com, and add a text field to the structure and save
4) Create a user with that role, login as that user, and make sure the user can contribute content with that new structure.

-----------------------------

- [x] Test # 3
1) Create a new structure and in the ""host or folder"" field assign it to a specific folder on the website browser tree (from which it will inherit permissions). Add a text field to the structure
2) Create a new role and assign the Home, Site Browser, and Content tabs
3) Assign it to the same folder with publish permissions on child structures and ""view"" on parent host
4) Edit the structure again and make sure the new role appears with publish rights on the structures permissions which are being inherited from the folder.
5) Create a new user, assign it to the new Role, login as that user and make sure the user can successfully publish content using that structure from the content tab.

-----------------------------

- [x] Test # 4
1- Login  
2- Add a user role with only view permissions on host
3- Edit permissions to all child objects in a folder and ""add to"" on the folder. 
4- Give the role edit permission on the GC structure and the content &  WB tab, and view permissions to a template.  
5- Now create an html page in that folder and try to save content to a container. 
-----------------------------

- [x] Test # 5
1- Login 
2- Go to CMS Admin- Users
3- Create limited publisher who has VIEW only to the host and to a parent folder, and FULL Publish on all child objects and publish permissions on the generic content structure.
4- Try to edit and publish one of the child objects as that limited user
5- Then try to add a new generic content to the folder (using host field), and make sure the limited user CAN'T do this

**Comment by erickgonzalez** [comment]
Test # 3 can't be tested successfully because of this issue https://github.com/dotCMS/core/issues/10679

**Comment by erickgonzalez** [comment]
After the fix on #10679 all tests works.
