### ISSUE TITLE
Not sanitizing inputs

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#10208]
When a content is submit from a form the values are not been sanitizing

## Possible Solution

Create a HttpServletRequestWrapper and OverWrite methods like getParameterValues to apply sanization.
A new SanizationAPI could be create for this, this have to allow create a configurable chain of SanizationChecker class each of them would apply a different checking.
If a client want to apply a new checking just have to create a new SanizationChecker subclass and add it to the chain.
This would work almost the same that the current WebInterceptors

**Comment by jdotcms** [comment]
It could be also applied to getParts method!

**Comment by jdotcms** [comment]
Just in case, the SanizationAPI will have a default chain of SanizationChecker's, but the client can add more by configuration in case they need more validations for form values.
