### ISSUE TITLE
Need a confirmation before reload the page to notify permissions changes

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10205]
Related to #10020 

## Expected Behavior
As the Add//Remove files from any folder we need be consistence in all the system, then we need a confirmation message before reload the page when you made some permissions changes on sites

## Current Behavior
The system is refreshing the page without confirmation 

## Steps to Reproduce (for bugs)
1. Login as user A
2. Login as user B
3. Go to site browser 
4. As user A made some change in the site permissions 

## Your Environment
Tested on the last master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
This won't be a problem after https://github.com/dotCMS/core/issues/10302

**Comment by jgambarios** [comment]
Closed as we are not refreshing the Site Browser window anymore https://github.com/dotCMS/core/issues/10302
