### ISSUE TITLE
 Check that proper messages are returned to the user when content types are created/modified in the UI

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10217]
We need to verify actions below and generate proper response messaging when the following actions take place:
- [x] Successful message is returned when content type is created
- [x] Message is returned if content type is not created
- [x] Message is displayed if there's an invalid input from the user
- [x] Message is displayed if required fields are not filled in
- [x] Message is displayed if content is created successfully

This one needs to be part of this as well: https://github.com/dotCMS/core/issues/10209

**Comment by dsilvam** [comment]
These need to be automated test
