### ISSUE TITLE
Fix contentType unit tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10227]
There are three unit tests failing related to the contentType changes:

 com.dotcms.notifications.BaseContentTypeSystemEventProcessorTest.testProcess	
 com.dotcms.rest.api.v1.content.ContentTypeResourceTest.testNoContentLetTypes	
 com.dotcms.rest.api.v1.content.ContentTypeResourceTest.testFileContentLetTypes

They need to be fixed or if they are failing because of real bugs let's capture them in separate issues.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10231

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10232

**Comment by dsilvam** [comment]
PR for 3.7: https://github.com/dotCMS/core/pull/10232

**Comment by agomez-dotcms** [comment]
PR (for 3.7 and 3.8): https://github.com/dotCMS/core/pull/10234
