### ISSUE TITLE
We are deleting the notifications when you login as 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10226]
After the fix #10134, the system is deleting completely the notifications every time you login as. 

## Expected Behavior
The system should hide the notifications when you login as, but when you come back to the original user should show again 

## Current Behavior
When you login as the system is deleting the notifications, and you can't see those again 

![r1](https://cloud.githubusercontent.com/assets/2641437/20731085/57140ac0-b64e-11e6-8a95-50547801822c.gif)

## Your Environment
- Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10252

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
