### ISSUE TITLE
Multiple File Upload does not allow Publishing without `Edit` permissions on the upload folder

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#10236]
Users with `Publish` permissions for `Content/Files` within a folder can **not** publish files into that folder using the `Multiple Files` upload feature unless the user _also_ has `Edit` permission on the folder where the files will be uploaded.  (The same users _can_ publish files if they upload only 1 file at a time - so this is a permissions problem with the multiple file upload feature).

## Expected Behavior

The permissions for Multiple File Upload should work exactly the same as the permissions for uploading a single file (adding a single File Asset).  That is, if the user has `Publish` permission for `Content/Files` inside the upload folder, and `Add Children` permissions on the upload folder itself, they should be able to upload and publish multiple files.

## Current Behavior

Users can't publish multiple files unless the users are granted all the above permissions _plus_ `Edit` permission on the upload folder itself.

## Possible Solution

In an ideal world, both the regular File Asset upload and the Multiple Files upload should go through the same permissions code (both to prevent duplication of code and to ensure there aren't discrepancies in how the permissions are handled).  So ideally, change Multiple File uploads to go through the same permissions check code that uploading a File Asset goes through now.

## Known Workarounds

1. Grant users `Edit` permission on the folder.
    * But this isn't an acceptable workaround for some customers, since it gives users the ability to edit files they didn't upload.
2. Give each user their own separate upload folder (so you can give each user `Edit` permissions for the folder without impacting other users' uploads).
    * Again, probably not an acceptable workaround for customers with many users.

## Steps to Reproduce (for bugs)

1. Create a new top-level folder.
2. Create a new Role and grant it the following permissions on the newly created folder:
    ![image](https://cloud.githubusercontent.com/assets/13456955/20802351/a4503950-b7a0-11e6-8a49-da0b96ab00f2.png)
3. Add the `Home` and `Site Editor` tabs to the Role.
4. Create a new user and assign the user to the new Role.
5. `Login As` the new user.
6. Open the `Site Editor` tab and select the newly created folder.
7. Select `+ Add New` -> `Image or File`, and select the `File Asset` content type.
    * Result: The `Save / Publish` workflow action is available (and correctly publishes the file if you select it).
8. In the Site Editor, select `+Add New` -> `Multiple Files` and select the `File Asset` content type.
    * **RESULT**: There is no `Save and Publish` button available (either before or after you select files to upload).

Note: If you add the `Edit` permission to the upload folder (as in the following image), and perform the same steps above, then the final result is that the user can correctly `Save and Publish` the files when uploading multiple files.

![image](https://cloud.githubusercontent.com/assets/13456955/20802730/da9302bc-b7a1-11e6-9b87-27c8fb0b4865.png)

## Context

Affecting a customer who is attempting to upgrade from 2.5.7 to 3.5 or 3.6.0; this issue is a deal-breaker for them, as their current workflow depends on users being able to publish files using Multiple Files upload *without* the users having `Edit` permission on the upload folder (so the users can't edit other users' uploads).

## Related Issues

* https://github.com/dotCMS/core/issues/4793

## Your Environment

* dotCMS version used: 3.6.0 (demo)
* Browser Name and version: Chrome
* Operating System and version: Win7
* Application Server and version: (demo)
* Java Brand and version: (demo)
* Database and version: (demo)

**Comment by john-thomas-dotcms** [comment]
Support Ticket: https://my.dotcms.com/ticket/UTHSC-80

**Comment by mattyarbrough** [comment]
This is an issue currently affecting customers on 4.x
