### ISSUE TITLE
XMLSitemap Exclusions do not appear to work

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#10233]
In working on a customer site I attempted to exclude certain paths from the sitemap and was unable to get them to exclude.  On a clean demo site locally I was also unable to do so, trying multiple content types in an attempt to achieve the correct functionality.  If this is not the correct way to do these exclusions then the documentation should be updated.

All of these failed to have any effect:

org.dotcms.XMLSitemap.content.IGNORE_UrlText=/bearmountain
org.dotcms.XMLSitemap.folder.IGNORE_UrlText=/bearmountain
org.dotcms.XMLSitemap.Content.IGNORE_UrlText=/bearmountain
org.dotcms.XMLSitemap.Folder.IGNORE_UrlText=/bearmountain
org.dotcms.XMLSitemap.content.IGNORE_UrlText=/intranet/news/
org.dotcms.XMLSitemap.News.IGNORE_UrlText=/intranet/news/
org.dotcms.XMLSitemap.calendarEvent.IGNORE_UrlText=/news-events/events
org.dotcms.XMLSitemap.Event.IGNORE_UrlText=/news-events/events
org.dotcms.XMLSitemap.calendarEvent.IGNORE_UrlText=/events
org.dotcms.XMLSitemap.Event.IGNORE_UrlText=/events
org.dotcms.XMLSitemap.Location.IGNORE_UrlText=/about-us/locations
org.dotcms.XMLSitemap.Location.IGNORE_UrlText=/locations
org.dotcms.XMLSitemap.Location.IGNORE_UrlText=/about-us/locations/
org.dotcms.XMLSitemap.Location.IGNORE_UrlText=/locations/

## Your Environment

* dotCMS version used: 3.6.0
* Browser Name and version: n/a
* Operating System and version: AWS linux, Centos 6.8 
* Application Server and version: bundled tomcat
* Java Brand and version: oracle 1.8, openjdk 1.8
* Database and version: postgres 9.3
* Application module (if apply):

**Comment by gabbydotCMS** [comment]
Reported by client:
https://my.dotcms.com/tickets/detail.dot?id=062ee6ec-7e51-4311-853d-ee21b98be1fe

**Comment by DeanGonzalez** [comment]
Yeah, I tested in 4.0 with this config and results: https://gist.github.com/DeanGonzalez/8b908180c108b2ed4ff001b726fc01c2

**Comment by jgambarios** [comment]
We found the **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText** is working as long as you have this property set: **org.dotcms.XMLSitemap.USE_STRUCTURE_URL_MAP = true**, so at this point we need to update our doc as it does not explain we need to use those two properties together.

Now, this is how it works the **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText** property, lets assume we have this URL map: **/new-event/test/{title}** and you have a **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText=/test**, what the code does is that is going to replace the **/test** String in the URL map replacing it with an empty String resulting in something like: **/new-event/my-event-title** as the code first resolve the URL map before to apply the **IGNORE_UrlText** properties.

If we want to replace the whole URL map you will need something like: **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText=/new-event/test/my-event-title**

**Comment by jgambarios** [comment]
@john-thomas-dotcms I think we are missing a couple of pieces in the doc here:
1. In the property **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText** the **ContentTypeVar** refers to the Structure var name, I think is not very clear in the doc, so you can have multiple **IGNORE_UrlText** properties as you can use it per structure var name.
2. The **IGNORE_UrlText** properties will work only if you have the **org.dotcms.XMLSitemap.USE_STRUCTURE_URL_MAP** enabled.
3. The **org.dotcms.XMLSitemap.ContentTypeVar.IGNORE_UrlText** properties support regex.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11462

**Comment by john-thomas-dotcms** [comment]
Doc updated: https://auth.dotcms.com/docs/latest/xml-sitemap

**Comment by bryanboza** [comment]
No changes here, just update the work, tested and woks fine

**Comment by nollymar** [comment]
The last commit does not clean the stringbuf var on each iteration, thus, the previous stringbuf value is written to the xml file each time the uri is empty.

I have created a new PR: https://github.com/dotCMS/core/pull/11618

Please, verify and test in order to provide a hotfix for a client

**Comment by bryanboza** [comment]
Tested after the last commit and work as expected...
