### ISSUE TITLE
Adding a new Field to a Content Type fails

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10246]
Logs:

https://gist.github.com/oarrietadotcms/d7affd927aca96b746f895b537f1754f
https://gist.github.com/oarrietadotcms/d7affd927aca96b746f895b537f1754f

## Steps to Reproduce (for bugs)
1. Go to Content Type Portlet
2. Select Content Generic
3. Add new Text field
4. See error after a couple of seconds in dotcms.log

## Context
Conflicts with new Immutable lib and Gson.

## Your Environment
* dotCMS version used: 3.8.0
* Browser Name and version: Any
* Operating System and version: Any
* Application Server and version: Any
* Java Brand and version: Java 8
* Database and version: Any

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10257

**Comment by dsilvam** [comment]
Getting a different error when trying same steps: https://gist.github.com/dsilvam/e37d8685bad73de734d777d251363b62.
Tested on Postgres

**Comment by dsilvam** [comment]
When Adding, Editing Content Types and Fields, this error is happening:
https://gist.github.com/shaydotcms/a6d984ce610105ac1339ac74677aa7ca

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10317

**Comment by shaydotcms** [comment]
Passed QA. System is now adding fields to content types.
No errors showing.
Tested in Postgres DB
