### ISSUE TITLE
Materialize Dojo Portlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10242]
This is a placeholder task for work on the portlet jsps.

#### Workflow tasks 
- [x] Workflow tasks
  - [x] Edit Workflow tasks
- [x] Dashboard
  - [x] Dashboard Detail
  - [x] Workstream

#### Site Browser
- [ ] Site browser
- [x] Links
  - [x] Edit Links
- [x] Templates
  - [x] Advanced Templates
  - [ ] Template  #Designer
- [x] Containers
  - [x] Edit Containers
- [x] Time Machine
- [x] Publishing Queue

#### Content
- [x] Contentlet search
  - [x] Edit contentlet
- [x] Calendar
  - [x] Month View
  - [x] Week View
  - [x] Day View
  - [ ] Edit Event
  - [ ] New Event
  - [ ] Event Pop Window
- [x] Link Checker

#### Marketing
- [x] Rules
- [x] Vanity Url
  - [x] Add Vanity Url
- [x] Forms

#### Content Type
- [x] Content types
  - [x] Create/Edit Fields
    - [x] Field variables
  - [x] View Relationships
    - [x] Add/Edit Relationships
  - [x] Properties
  - [x] File tree dialog
  - [x] Push history
- [x] Categories
- [x] Tag Manger
- [x] Workflow Schemes
  - [x] Workflow Edit/Add
    - [x] Workflow Action
    - [x] Workflow Sub Action

#### System
- [x] Users
- [x] Roles & Tabs
- [x] Sites
  - [x] Copy Site
- [x] Maintenance
- [x] Configuration
  - [x] Basic Info Tab
  - [x] License Manager Tab
  - [x] Network Tab
  - [x] Publishing Environments Tab
- [x] Languages
  - [x] List Languages
  - [x] Add Language
  - [x] Add/edit Variables 
- [x] Query Tool
- [x] ES Search
- [x] Site Search
  - [x] Indices
  - [x] Search Test
  - [x] View Jobs
  - [x] Job Scheduler
  - [x] Audit Data
- [x] Dynamic Plugins

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10278

**Comment by bryanboza** [comment]
**Workflow Tasks**

We are unable to upload files... You can't see the tree SC: http://screencast.com/t/xZQrriH4w

**Comment by bryanboza** [comment]
**Dashboard**

- [ ] The work stream window need adjust the top margin: http://screencast.com/t/loGFx8ro

- [ ] The properties portlet looks more ordered with the left aligned, as in the old UI http://screencast.com/t/JTTysZqT70y

**Comment by bryanboza** [comment]
**Links**

- [ ] Unable to see the folder tree adding new links: http://screencast.com/t/2jQlVIurO

- [ ] Unable to order by title or mod date 

- [ ] UI: need adjust the top margin: http://screencast.com/t/KQoekF1ljWY

**Comment by bryanboza** [comment]
**Templates**

- [ ] If you un-publish some template, then right click and publish, the system is not refreshing the status

- [ ] Unable to select the file in the image fields editing templates: http://screencast.com/t/ojbgqPe7a5E2

- [ ] Unable to add js/css in the template field, the button does not working http://screencast.com/t/YwoUdHMr5si5

**Comment by bryanboza** [comment]
**Containers**

- [ ] When you publish any container with the right click menu, the status field is not refreshing 

- [ ] UI: Need adjust the top margin http://screencast.com/t/caxlHDC4J0F

- [ ] Need remove the empty field that are after content type/code field http://screencast.com/t/P8eh0QG8wYR

**Comment by fmontes** [comment]
**Categories**

- [ ] Action button not working correctly

- [ ] When you open add new category dialog and scroll, the dialog just broke

**Comment by fmontes** [comment]
**Content type**

- [ ] Portlet toolbar it's broke

**Comment by bryanboza** [comment]
New issues related to the UI changes: #10318 and #10319

**Comment by bryanboza** [comment]
**Site Browser**

- [ ] Unable to add page rules, we are showing the pattern library instead the rules portlet http://screencast.com/t/Xk241BucRVM

**Comment by bryanboza** [comment]
**Time Machine**

- [ ] Unable to see the snapshots... http://screencast.com/t/Qas7dzZdT

**Comment by bryanboza** [comment]
**Vanity URL**

- [ ] The files tree isn't working for the URL to redirect field
- [ ] Unable to order fields by the column names: URL and title http://screencast.com/t/oNKadV2Qmzd

**Comment by bryanboza** [comment]
**Users**

- [ ] JS error trying to add tags, the system isn't showing the suggested tags in the marketing tab http://screencast.com/t/uciEquxP

- [ ] Unable to delete tags, after add some one

**Comment by fmontes** [comment]
**Roles and Tabs**

- [ ]  Permission box cut off: https://cloudup.com/c0UiJDm6-Ya

**Comment by bryanboza** [comment]
**Sites:**
- [ ]  The error messages need styling help http://screencast.com/t/yVLfN7MmyH

**Comment by bryanboza** [comment]
New issue created #10457
