### ISSUE TITLE
Fix failures in Integration Tests in 3.8

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10245]
After creating master-3.8 branch with the changes for content types, there are a large number of integration tests failing on jenkins: 

Results on postgres: https://cb.dotcms.com/view/master-3.8/job/Git_Master_Int_Funct_Test_Runner_3.8_Postgres/12/testReport/

We need to have these tests passing again.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10300

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10305
