### ISSUE TITLE
Browser console errors when loading Content Types portlet 

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10254]
Browser is throwing console errors when loading Content Types portlet. In addition once you access the portlet, you are unable to click on it again in order to reload it.

## Expected Behavior
Content Types portlet should load with a clean console. In addition, as in previous dotcms releases, you should be able to click the Content Type portlet as many times as you want to reload the content.

## Current Behavior
Browser is throwing console errors when loading Content Types portlet. In addition, once you access the Content Type portlet, you are unable to click on it again in order to reload.

## Known Workarounds
Reload the Content Type portlet page by hitting Refresh button in the browser

## Steps to Reproduce (for bugs)
1- Login to dotcms
2- Open the browser console (Inspect Element) to see the logs
3- Navigate to Content Type portlet
4- Click again the Content Type portlet to reload it
5- You will see an error in the browser console

**Chrome error**
![image](https://cloud.githubusercontent.com/assets/8741846/20844066/b2bea8f8-b883-11e6-833a-5b77bf564b90.png)

**Firefox error**
![image](https://cloud.githubusercontent.com/assets/8741846/20844193/524ba4c0-b884-11e6-803f-3f5a434e28ab.png)

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: Postgres 9.3.5 
- Operating System and version: Ubuntu 14.04.1
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
I don't see this error with the latest code in master-3.8. But I know that new layout are currently changing so I would like to test this one before the iteration ends.

**Comment by shaydotcms** [comment]
Error is not showing any more, however second issue still happen: once you click on Content Types portlet, you cannot reload it by clicking again on it, you will need to navigate away and come back in order to reload it. This was not happening in 3.7
![reload content type portlet](https://cloud.githubusercontent.com/assets/8741846/21107907/f174b61e-c058-11e6-9030-e17e980d358e.gif)

**Comment by erickgonzalez** [comment]
Related to https://github.com/dotCMS/core/issues/10382
