### ISSUE TITLE
Dot site selector is not refreshing when you add new sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10256]
## Expected Behavior
We need auto refresh the site selector every time you add//delete any site 

## Current Behavior
After the last changes we broke this functionality, then we are not refreshing this component 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to sites portlet and add a new site 
3. Validate the site selector auto refresh

## Your Environment
Tested in the last master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
Related to changes in https://github.com/dotCMS/core/issues/10198

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10514
https://github.com/dotCMS/core-web/pull/254

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF... We are unable to see the site list after close once, but reported on card #10457
