### ISSUE TITLE
Error in logs after creating/updating a content type

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10255]
System successfully creates/updates a content type, however there's an error in the logs:
https://gist.github.com/shaydotcms/84175c68fa84d6b9f9a8019a4e6c426f

## Expected Behavior
There shouldn't be any errors in the logs after creating/updating a content type

## Current Behavior
System successfully creates/updates a content type, however there's an error in the logs
https://gist.github.com/shaydotcms/84175c68fa84d6b9f9a8019a4e6c426f

## Steps to Reproduce (for bugs)
1- Login to dotcms
2- Navigate to Content Types portlet
3- Click "Add New Content Type" button
4- Fill in the blanks and hit Save button
5- Check the logs
6- Issue can be reproduced when you edit an existing content type

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: Postgres 9.3.5 
- Operating System and version: Ubuntu 14.04.1
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10288

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
