### ISSUE TITLE
FilterWebInterceptorProvider forces session creation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10258]
The FilterWebInterceptorProvider forces session creation for every request.  This is a dotCMS antipattern.

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotcms/filters/interceptor/FilterWebInterceptorProvider.java#L29

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10259

**Comment by bryanboza** [comment]
Waiting for the fix #10242 in the Site Browser section

**Comment by wezell** [comment]
here is the test:

`curl -head http://localhost:8080/images/404.jpg`

and 

`curl -head http://demo.dotcms.com/contentAsset/raw-data/4d7daefa-6adb-4b76-896d-c2d9f95b2280/fileAsset`

and make sure they do not leave any cookies or JSESSIONIDs

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
