### ISSUE TITLE
Document Content Type REST API

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10277]
We need documentation for the new Content Type REST API:

Available operations:

- [ ] Get 
```GET /v1/contenttype/id/{typeId}```
```
curl -v -u admin@dotcms.com:admin -XGET http://localhost:8080/api/v1/contenttype/id/4c441ada-944a-43af-a653-9bb4f3f0cb2b
```

- [ ] Create 
```POST /v1/contenttype``` (need to define JSON object)
```
curl -v -u admin@dotcms.com:admin -XPOST http://localhost:8080/api/v1/contenttype -H "Content-Type: application/json" --data @bodyCreate.json
```
Contents of file bodyCreate.json:
```
[{
  "clazz": "com.dotcms.contenttype.model.type.ImmutableSimpleContentType", 
  "defaultType": false, 

  "name": "The Content Type 1", 
  "description": "THE DESCRIPTION", 

  "host": "48190c8c-42c4-46af-8d1a-0cd5db894797", 
  "owner": "dotcms.org.1", 

  "variable": "TheContentType1",

  "fixed": false, 
  "system": false, 
  "folder": "SYSTEM_FOLDER"
}]
```

- [ ] Delete
```DELETE /v1/contenttype/id/{typeId}```
```
curl -v -u admin@dotcms.com:admin -XDELETE http://localhost:8080/api/v1/contenttype/id/05c64f1d-2d39-4b93-95c4-99d72ebe869a
```

Operations not yet implemented:
Update. See #10173

**Comment by DeanGonzalez** [comment]
https://auth.dotcms.com/docs/latest/content-type-api

**Comment by agomez-dotcms** [comment]
**To be documented**: Following are the possible values for the "clazz" attribute in JSON payload for Content Type REST API:

"com.dotcms.contenttype.model.type.ImmutableFileAssetContentType"
"com.dotcms.contenttype.model.type.ImmutableFormContentType"
"com.dotcms.contenttype.model.type.ImmutablePageContentType"
"com.dotcms.contenttype.model.type.ImmutablePersonaContentType"
"com.dotcms.contenttype.model.type.ImmutableSimpleContentType"
"com.dotcms.contenttype.model.type.ImmutableWidgetContentType"

Thanks,
Anibal

**Comment by wezell** [comment]
@agomez-dotcms In the doc I want to use the non-immutable (which shouldn't be exposed to visitors) forms for the clazz names, e.g.
```
"com.dotcms.contenttype.model.type.FileAssetContentType"
"com.dotcms.contenttype.model.type.FormContentType"
"com.dotcms.contenttype.model.type.PageContentType"
"com.dotcms.contenttype.model.type.PersonaContentType"
"com.dotcms.contenttype.model.type.SimpleContentType"
"com.dotcms.contenttype.model.type.WidgetContentType"
```

**Comment by DeanGonzalez** [comment]
Added this doc: https://authoring.dotcms.com/docs/latest/create-content-types-of-each-base-type
