### ISSUE TITLE
Mark fields as required in a Content Type

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10285]
## Expected Behavior
System should let the user know beforehand what fields are required to complete the Content Type form.

## Current Behavior
When the user doesn't fill out some required fields, the system is not letting the user know beforehand that they are required. It is until the user clicks "Save" button that a message comes up, i.e.: Content Type name
![image](https://cloud.githubusercontent.com/assets/8741846/20936738/4d18a3a4-bba9-11e6-9adb-7f3132cbb5ee.png)

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Types portlet
3. Click "Add New Content Type" button
4. Do not fill out any information in the form, just click "Save" button
5. System should let the user know beforehand what fields are required to complete the Content Type form. It is until the user clicks "Save" button that a message comes up.

## Your Environment
- dotCMS version used: demo.dotcms.com & latest master_3.8
- Database and version: Postgres 9.3.5 
- Operating System and version: Ubuntu 14.04.1
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by dsilvam** [comment]
This is the current behavior in 3.6, so I don't think this is going to change until we redo the portlet in angular
