### ISSUE TITLE
Unable to create new content type in MS SQLServer db

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10282]
System is throwing this error in the logs when you click Save button
https://gist.github.com/shaydotcms/3ea2a6ca42787463dc6b141250de1e30

## Expected Behavior
System should create a the new content type

## Current Behavior
System never leaves the Content Type form therefore it's never created

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Type portlet
3. Click "Add New Content Type" button:
4. Fill in all the required fields and hit Save button
5. System never leaves the Content Type form therefore it's never created

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: SQLServer 2012
- Operating System and version: Win7 Pro SP1
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
Code change on https://github.com/dotCMS/core/issues/10281 also fixed this one.

**Comment by shaydotcms** [comment]
A new error with a jsp file came up:
https://gist.github.com/shaydotcms/d330d3b4cf809d308de9673de3b022e4

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10301

**Comment by shaydotcms** [comment]
New error is showing up in the logs:
https://gist.github.com/shaydotcms/a6d984ce610105ac1339ac74677aa7ca

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/10317

**Comment by shaydotcms** [comment]
Passed QA.
No errors are showing in the logs and content types are created/edited successfully.
Tested on same environment described in "Steps to Reproduce"
