### ISSUE TITLE
Content Search portlet is not working using MS SQLServer db

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10281]
System is throwing this error in the logs:
https://gist.github.com/shaydotcms/fb5c3263f54d33ba84502eecc7c1b43b

## Expected Behavior
Content Search portlet should display all available contents

## Current Behavior
Content Search portlet is displaying "Ooops, sorry. This has caused a problem"

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Search portlet and click to open it
3. Content Search portlet is displaying "Ooops, sorry. This has caused a problem"

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: SQLServer 2012
- Operating System and version: Win7 Pro SP1
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10295

**Comment by shaydotcms** [comment]
Passed QA.
Content Search portlet is working appropriately
Tested in same environment
