### ISSUE TITLE
ESContentletIndexAPITest.createContentIndexAndDelete failing in Jenkins

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10296]
ESContentletIndexAPITest.createContentIndexAndDelete is failing in Jenkins sporadically, 
and it seems like it makes a couple more tests to fail:

com.dotcms.content.elasticsearch.business.ESIndexAPITest.uploadSnapshotTest_fromCurrentLive
com.dotcms.content.elasticsearch.business.ESIndexAPITest.createSnapshotTest

Jenkins failures: 
- MSSQL: https://cb.dotcms.com/view/master-4.0/job/Git_Master_Int_Funct_Test_Runner_3.7_MSSQL/39/

- MySQL: https://cb.dotcms.com/view/master-4.0/job/Git_Master_Int_Funct_Test_Runner_3.7_MySQL/16/

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10459

**Comment by dsilvam** [comment]
There is feedback here we need to wait for, basically the results of the integration tests on Jenkins
