### ISSUE TITLE
Fix Functional Tests in Jenkins for 3.8

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10304]
There are some functional tests failing in Jenkins for master-3.8 branch

See: https://cb.dotcms.com/view/master-3.8/job/Git_Master_Int_Funct_Test_Runner_3.8_MySQL/lastCompletedBuild/testReport/

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10315
