### ISSUE TITLE
Define metadata for pagination in REST JSON responses 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10309]
We need to define a standard for this. 
This goes in the lines of including a "previous", "next" pre-built links and also total count. 

Here are a few interesting approaches : 

Github: https://developer.github.com/v3/#pagination, https://developer.github.com/guides/traversing-with-pagination/
Confluence: https://developer.atlassian.com/confdev/confluence-server-rest-api/pagination-in-the-rest-api
Twillio: https://www.twilio.com/docs/api/rest/response#response-formats-list-paging-information
Google: https://developers.google.com/custom-search/json-api/v1/using_rest
Good article: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination

Agreed outcome needs to go to the "Standards" Document. Please ask @jgambarios for more

### @fmontes: https://github.com/dotCMS/core/issues/11818

1. By default should use: dotcms.paginator.rows
2. If the FE ask for "20" with a param in the first request the backend should response with 20 and the paginations urls will have that limit

**Comment by dsilvam** [comment]
Whatever decided, we need a card to incorporate this in the pagination of Sites, see https://github.com/dotCMS/core/pull/10275

**Comment by wezell** [comment]
@fmontes I believe this is done, correct?  We are going with a ? parameter?  Please comment.

**Comment by wezell** [comment]
Closing - I believe we are using the github pattern

**Comment by dsilvam** [comment]
Did we use the 'Link' header as github does?

**Comment by dsilvam** [comment]
https://developer.github.com/v3/#link-header

**Comment by dsilvam** [comment]
And also, where is this pattern we now use documented? or what would be the example code to check when writing new endpoints or adding pagination to them?

**Comment by wezell** [comment]
@dsilvam I would ask Freddy?

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/11818

**Comment by wezell** [comment]
Are we done with this issue and if so, what is our choice?

**Comment by dsilvam** [comment]
not yet @wezell

**Comment by dsilvam** [comment]
@freddyucv went with the github approach, but with some mods I think
