### ISSUE TITLE
Don't refresh site browser on events generated by Site Browser changes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10302]
Related to: https://github.com/dotCMS/core/issues/10018

Currently on certain operations on the Site Browser like add, delete or update folders, links, pages and files we are creating system events, those events when handle by the client side generate a refresh on the site browser portlet.

## Expected Behavior
We don't want the refresh of the Site Browser

## Current Behavior
The client side captures the generated event and displays a javascript confirm asking if you want or not to refresh the Site Browser portlet.

## Possible Solution
Do nothing on the client site with the generated events.

## Context
The creation of the events is correct but on the client they will be handle when we implement the Site Browser with angular.

**Comment by jgambarios** [comment]
**Note:** When changing permissions on files an Event is generated and it is reloading the site browser, we need to avoid the refresh also in that case.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10514
https://github.com/dotCMS/core-web/pull/254

**Comment by bryanboza** [comment]
All the changes was reverted, for now we are not refreshing...
