### ISSUE TITLE
Need validate the null values from UI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10319]
## Expected Behavior
After the new theme changes, we need validate some values before call the methods, this to avoid some errors 

## Current Behavior
When you try to upload some single fields as limited user, and don't have permissions over the default structure, the file asset type window appears in blank, you need select some value, but if you don't select some value, this cause an error... 

## Steps to Reproduce (for bugs)
1. Login as limited user
2. Try to upload some single file 
3. Don't select the content type and click to upload 

This generate a NPE:  ```ERROR portlet.StrutsPortlet: java.lang.NullPointerException```

## Your Environment
Tested on master-3.7 // H2 // FF

**Comment by jdotcms** [comment]
A new message has been added to the Language.properties, needs translation

edit-contentlet-content-type-null=The content type is null on adding new content with the inode: {0}

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10449

**Comment by bryanboza** [comment]
Passed, some new inconsistencies reported on #10461
