### ISSUE TITLE
Unable to upload multiple files from limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10318]
## Expected Behavior
When you have permission over any folder, you should be able to upload individual or multiple files without problems 

## Current Behavior
We are having an error when you as limited user try to upload some multiple files, we are having an error in the ```/html/portal/layout_portal.jsp``` file... 
<img width="1152" alt="2016-12-09_0818" src="https://cloud.githubusercontent.com/assets/2641437/21051925/ff7dee38-bde7-11e6-98e7-c699406aad2e.png">

Here the log error: https://gist.github.com/bryanboza/1e185afc3e12b5685d1638e35ee22a86

## Steps to Reproduce (for bugs)
1. Login as admin and create a new folder 
2. Add full permissions to some limited user over this folder
3. Login as the limited user 
4. Try to upload multiple files

## Your Environment
Tested in the last master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10364
