### ISSUE TITLE
Need to scroll down to be able to view Configuration portlet

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10311]
When you navigate to the Configuration portlet, it seems that it's all blank but actually you have to scroll down because it's a the bottom of the page.

![image](https://cloud.githubusercontent.com/assets/8741846/21018909/56456eb2-bd34-11e6-8547-6b1afb470138.png)

## Expected Behavior
Configuration portlet should show as soon as you access it without having to scroll down.

## Current Behavior
You need to scroll down to be able to view the Configuration portlet

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to System> Configuration portlet
3. It seems that it's all blank but actually you have to scroll down because it's a the bottom of the page.
![image](https://cloud.githubusercontent.com/assets/8741846/21018932/64cc888a-bd34-11e6-9c97-976822acfb87.png)

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: Postgres 9.3.5 / SQLServer 2012 / MySQL 5.6.23
- Operating System and version: Ubuntu 14.04.1 / Win7 Pro SP1 / Mac OS 10.10.5
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by wezell** [comment]
This is being fixed by Freddy
