### ISSUE TITLE
Error when creating a folder

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#10316]
## Expected Behavior
Creation of the folder should be successful.

## Current Behavior
When you try to create a folder and error is thrown.

## Steps to Reproduce (for bugs)
1. Create a new folder
2. An error is thrown https://gist.github.com/erickgonzalez/cdd01a7882a932591df7be2b376f7bea

## Your Environment
* dotCMS version used: 3.8
* Browser Name and version: chrome
* Operating System and version: OS
* Database and version: mysql and postgres

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10407

**Comment by agomez-dotcms** [comment]
Issue was been moved to "Done" after being tested by successfully creating both root and non-root level folders from Site-Browser.
