### ISSUE TITLE
Content Management: Cannot Delete/Move assets via WebDAV

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10327]
## Expected Behavior
The logged in user, with the right amount of permissions, should be able to move or delete resources from any site, via WebDAV.

## Current Behavior
Move/Delete Methods on WebDAV return [Error 500, for any asset type (file, folder, page)](https://gist.github.com/joseorsini/1c3b7c3d9ea844d7746a26e151f65aed). This is happening because the isResource Method, which verifies the path that comes from WebDAV (and where Site and Folder are verified), [is attempting to strip the WebDAV headers from the request](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L1156), however, these values are already stripped [on move](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L1137-L1138) and [delete](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L1336) methods, so it returns a IOException complaining about the URI in question.

## Possible Solution
Remove the stripMapping call inside isResource Method, because it is not needed at all.

## Known Workarounds
Deleting the asset via Website Browser.

## Steps to Reproduce (for bugs)
1. Start up 3.6.0 and apply an Enterprise License
2. Bind dotCMS to a 3rd party WebDAV app, like BitKinex or CyberDuck
3. Go to /resources/res-images/ folder and add an image. See confirmation in logs and Website Browser that the file was added. Refresh the 3rd party app if file is not yet listed.
4. Delete the file that was recently added.  Error is thrown.
5. Drag and Drop  /resources/res-documents/dotCMSCheatSheet.pdf to the root context of Site (inside demo.dotcms.com site). Error is thrown 

Stacktrace: https://gist.github.com/joseorsini/1c3b7c3d9ea844d7746a26e151f65aed

## Context
Reproduced and reported by client: https://my.dotcms.com/tickets/detail.dot?id=c3230b35-afe6-47a6-a759-baba36bbf6ca

## Your Environment

* dotCMS 3.6.0
* Google Chrome.
* CyberDuck 4.7.3 (18402).
* macOS Sierra 10.12.1.
* Tomcat 8.0.18.
* Java 8
* Postgres 9.4.1.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10330

**Comment by dsilvam** [comment]
Note to QA: Please re-test basic webdav flow on Finder with this one

**Comment by DeanGonzalez** [comment]
Tested uploading files and creating folders in finder via webdav.  Tested uploading files at the host level.  Tested folder and file creation in multiple languages via webdav. Passed.

**Comment by dsilvam** [comment]
Thanks for checking it out @DeanGonzalez
