### ISSUE TITLE
Site Browser events problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10320]
After the card #10018, now we are sending some events every time you make some changes on site browser, but we still having some inconsistencies...

## Expected Behavior
We should fire an event every time you made some change

## Context
- [ ] The publish event on pages is not sending notifications... 
- [ ] We are not firing  events when you add multiple files.
- [ ] If you create some page, and try to un-publish from some user different to admin, the system is sending the notification to user that generate the event.
The same thing in the follow cases:
                                     _- Un-publish // Archive // Un-archive // Delete files 
                                     - Un-publish // Archive pages_
- [ ] The admin is not receiving notifications when you delete some folder from other user 
- [ ] Un-Archive links is not generating event 

## Your Environment
Tested on the last master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/10256 https://github.com/dotCMS/core/issues/10198 https://github.com/dotCMS/core/issues/10302

**Comment by bryanboza** [comment]
All the changes was reverted, for now we don't have actions...
