### ISSUE TITLE
Fix upgrades tasks Oracle

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#10328]
## Expected Behavior
When upgrading from a previous dotcms version, the upgrade must be successful.

## Current Behavior
When upgrading from Oracle is throwing a Fatal Error. Upgrade Tasks we need to review:

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03710AddFKForIntegrityCheckerTables.java

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03715AddFKForPublishingBundleTable.java

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03720AddRolesIntegrityCheckerTable.java

LOG: https://gist.github.com/erickgonzalez/71ec9c36a4d16778c12a755f232f0345

## Possible Solution
Remove " ; " of each statement, when using dotconnect the " ; " is not needed.

## Steps to Reproduce (for bugs)
1. Start an instance of dotcms 3.6.0
2. Stop the instance.
3. Upgrade the instance to 3.8.0 (or 3.7.0)
4. Check the logs.

## Your Environment
* Browser Name and version: FF
* Operating System and version: Windows 7
* Database and version: Oracle 11g

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10345

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // Oracle 11g // Chrome
