### ISSUE TITLE
Error in logs when you push a new content type

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10324]
There's an error in the logs when you try to push content types. I did the test with all the content types (Content, Widget, File, Page, Persona) and was able to push successfully only the Content content type, the other types of content failed.
The system is showing different errors depending on the content type being pushed:
https://gist.github.com/shaydotcms/cbc7d4a0c7e91a31a74942b552388352

The sender and receiver used MySQL as DB. Also tested with different DBs on the sender and receiver (sender: Postgres / receiver: MSSQL) and got the same errors.

## Expected Behavior
All content types should be pushed with no problems.

## Current Behavior
Only the Content content type was pushed successfully, the other types of content failed.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Types portlet
3. Click "Add New Content Type" button 
4. Create a new content type with all the different types of content (Content, Widget, File, Page, Persona)
5. Push each new content type
6. Check the logs

## Your Environment
Sender:
- dotCMS version used: Latest master_3.8
- Database and version: MySQL 5.6.23 / Postgres 9.3.5
- Operating System and version: Ubuntu 14.04.1
- Browser Name and version: Firefox v45.0.1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

Receiver:
- dotCMS version used: Latest master_3.8
- Database and version: MySQL 5.6.23 / SQLServer 2012
- Operating System and version: Mac OS 10.10.5 / Win7 Pro SP1
- Browser Name and version: Firefox v45.0.1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by wezell** [comment]
Talk to me about this one.

**Comment by agomez-dotcms** [comment]
PR (Core): https://github.com/dotCMS/core/pull/10374
PR (Enterprise): https://github.com/dotCMS/enterprise-2.x/pull/402

**Comment by shaydotcms** [comment]
Passed QA
All content types were pushed successfully
Tried also pushing the content types inside bundles and it worked
Tested in latest master_4.1
Sender: MySQL 5.6.23
Receiver: SQLServer 2012
