### ISSUE TITLE
Errors trying to publish/un-publish menu links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10321]
## Current Behavior
We are having some problems every time you made some change over the menu links, we are having an error on log 

```ERROR: business.VersionableFactoryImpl: Versionable null when finding working version com.dotmarketing.portlets.links.model.Link Trying old method.```

## Steps to Reproduce (for bugs)
1. Login 
2. Create a menu link
3. Save and publish (check the logs)
4. Un-publish (check the logs) 
5. Try to publish again (check the logs)

## Your Environment
Tested on master-3.7 // H2 // FF

**Comment by jdotcms** [comment]
I couldn't reproduce it on my local

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10392

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // Postgres // FF
