### ISSUE TITLE
Update License Plugin for 500 level 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10339]
* https://github.com/dotCMS/plugin-dotcms-license/blob/master-3.x/src/main/java/com/dotcms/license/servlet/GenerateLicenseServlet.java
* Plugin runs on dotcms.com

This is the plugin that the support portal and other things use to actually generate the license

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/10384
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/403
PR License: https://github.com/dotCMS/license/pull/33

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/plugin-dotcms-license/pull/10

**Comment by agomez-dotcms** [comment]
Attention Guys!

As introduced in comments on #10340, after Support Portal's deployment to Production, there is one action remaining to be completed:

1. Log into "http://my.dotcms.com/c"
2. Add "Platform" value on select field at "Content-Types -> Enterprise Contract -> License Level" ("Platform|Platform")

Thanks,
Anibal
