### ISSUE TITLE
Cancel button on csv import does not actually cancel update

### ISSUE THREAD

**Issue by maxkahn** [dotCMS/core#10333]
## Expected Behavior
The cancel button should not execute the update. The existing content should be completely unchanged.

## Current Behavior
Instead, the fields that would be updated on the previewed csv import are actually updated.

## Known Workarounds
Update content through the dotCMS UI instead of by csv import.

## Steps to Reproduce (for bugs)
1. Create a new content type with 2 text fields, say Field1 and Field2, where each field has 'required', 'user searchable', 'show in listing', and 'indexed' checked, 'unique' is not checked.
2. Create a new piece of content with that type on the 'content' tab , filling in those two fields. (Say Field1 is "ABAB" and Field2 is "CDCD".)
3. Click through to 'import content' on the 'add new content' drop-down. Select the new content type from the 'content type to import' menu.
4. Download a csv sample file. Add one row under the headers, with values "ABAB" in the Field1 column and "EFEF" in the Field2 column. Save the csv file.
5. Choose that csv file using the 'choose file' button and check Field1 as a key field. Click 'Go to preview'.
6. On the next page, click cancel, and return to content search.

(Note: this bug also appears on csv updates using an 'identifier' column instead of a key field. I have not observed it with inserts by csv import.)

## Context
We regularly use the csv import feature to let non-technical coworkers update content in bulk. The workflow should be intelligible to non-technical coworkers and minimize the time spent updating or deleting each piece of content individually.

## Your Environment
Reproduced on demo.dotcms.com/admin, as well as our installation, running version 3.5.

**Comment by mingfu** [comment]
This is biting us quite often. Would be great if we can get some visibility in terms of whether this can be looked at. Appreciate it!

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12133

**Comment by DeanGonzalez** [comment]
Passed QA, tested with two field keyfield and with identifier field... now acts as expected
