### ISSUE TITLE
Failed to edit comments thru Content Search

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10332]
When you try to edit a comment, the system will throw an error in the logs:
https://gist.github.com/shaydotcms/4af31288fd59d32dd5c6738d9474c857

It looks like there's a error through different lines of code in edit_contentlet.jsp 

## Expected Behavior
You should be able to edit comments with no problems

## Current Behavior
When you try to edit a comment, the system will throw an error in the logs and give a UI message:
![image](https://cloud.githubusercontent.com/assets/8741846/21113972/2beca99c-c071-11e6-81ae-935ff539926c.png)

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Go to Content Search portlet
3. Click on Type dropdown and select Comments 
4. Click on any comment in order to edit it
5. You will see the error showing in the logs

## Your Environment
- dotCMS version used: Latest master_3.8
- Database and version: Postgres 9.3.5 / MySQL 5.6.23 / Oracle 12c
- Operating System and version: Ubuntu 14.04.1 / Mac OS 10.10.5
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by erickgonzalez** [comment]
Dup of https://github.com/dotCMS/core/issues/10501
