### ISSUE TITLE
Add new license level 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10338]
* Add code to License Jar https://github.com/dotCMS/license 
* Alter dotCMS code that reads license to be aware of new level. Enterprise Code 

NOTES 
* ensure 400 level stuff still works.  we should be checking level or under 
* new level is 500. Called Platform

**Comment by nollymar** [comment]
PR Core: #10384
PR Enterprise: dotCMS/enterprise-2.x#403
PR License: dotCMS/license#33
