### ISSUE TITLE
Document Static Publishing 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10347]
* we need to document how static pushing works with S3. 
* We need to stress the importance of Bucket Names on AWS. For example If you use a bucketID pattern see the notes here https://github.com/dotCMS/core/issues/10343 THEN you need to ensure you use a pattern that will be unique. AWS uses bucket names that are globally unique across their infrastructure.
In addition to this you can currently only have 100 buckets.  you can request more from AWS but this is between AWS and the client and had nothing to do with dotCMS. 
* We need to stress permissions.  If you use a pattern for the buckets you will need to have a use that can create the buckets UNLESS you create the required buckets manually. We ONLY create IF the bucket doesn't already exist 

See https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

https://www.flowdock.com/app/dotcms/static-push/threads/Jwn942FrPk_hn6424yUd-UEhVfC

**Comment by chrismccracken** [comment]
Need to doc IAM Policy permissions needed for the following cases: 

* Auto-create bucket
* Sync website


These are *probably* as follows (untested):

**Auto-create bucket:**
```
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Sid":"statement1",
         "Effect":"Allow",
         "Action":[
            "s3:CreateBucket", "s3:ListAllMyBuckets", "s3:GetBucketLocation"  
         ],
         "Resource":[
            "arn:aws:s3:::*"
         ]
       }
    ]
}
```
**Sync website:**

```
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Sid":"statement2",
         "Effect":"Allow",
         "Action":[
            "s3:ListBucket", "s3:ListAllMyBuckets", "s3:GetObject", "s3:PutObject", "s3:DeleteObject"
         ],
         "Resource":[
            "arn:aws:s3:::examplebucket"
         ]
       }
    ]
}
```
(maybe no DeleteObject, depends if we handle unpublish/deletes)

In this example, policy limits access to specified bucket. This is **strongly** recommended if you are not using a dedicated AWS account for dotCMS Static Publish buckets.

**Comment by chrismccracken** [comment]
**If create bucket feature is enabled**, a dedicated AWS account should be used for the Static Push target. Allowing access to an existing AWS account that contains or may contain other S3 resources is strongly discouraged due to security concerns.
