### ISSUE TITLE
Update Support Portal for new 500 level 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10340]
* Need to update the VTL that posts to the LicenseUtil of the Support Portal https://github.com/dotCMS/SupportPortal/blob/master-3.x/src/main/java/com/dotcms/support/util/LicenseUtil.java#L71
* this is the VTL /global/vtl/contractListing.vtl
* Update the Contract Level in the Content Type Field. Field is License Level

**Comment by joseorsini** [comment]
this one needs to be edited as well, so once a Contract is created, the new License Level is available for selecting /global/vtl/contractForm.vtl

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/SupportPortal/pull/252

**Comment by agomez-dotcms** [comment]
Attention Guys!

As introduced in comments above, after Support Portal's deployment to Production, there is one action remaining to be completed:

1. Log into "http://my.dotcms.com/c"
2. Add "Platform" value on select field at "Content-Types -> Enterprise Contract -> License Level" ("Platform|Platform")

Thanks,
Anibal
