### ISSUE TITLE
Update the Environment UI 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10342]
* Update the add/edit Push Environment screen 
* Alter the naming for Protocol 
* Make the text Area for password be config options when the AWS S3 protocol is selected 

MORE TO COME

**Comment by jdotcms** [comment]
![awss3](https://cloud.githubusercontent.com/assets/19578350/21359762/de8138d4-c6a2-11e6-984c-89d31507e1f4.png)

**Comment by jdotcms** [comment]
The next step will be to validate and save the information into the db.

**Comment by jdotcms** [comment]
after the review yesterday, some changes were reverted. 
I have just keep the aws s3 protocol in the select box and the a little help in the text area to add the properties when this is empty.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10412

**Comment by agomez-dotcms** [comment]
Passed QA. UI performs validations on Static Publishing connection parameters. Also, both single and mixed endpoint push publishing are working as expected by using the parameters provided from the UI.
