### ISSUE TITLE
Create AWSS3EndPointPublisher

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10343]
* needs to use the static bundlers https://github.com/dotCMS/enterprise-2.x/blob/master-3.6/src/com/dotcms/enterprise/publishing/timemachine/TimeMachinePublisher.java#L42-L49
* When creating languages we wanna use language code for folder name and not languageID on S3 side 
* Uses Publishing Framework iPublisher Interface as in TimeMachinePublisher.java
* 500 level - Platform 
* Uses CMS Anon permissions
* Will not handle deletes automatically or renames.  The client needs to do a manual Push Delete to remove. Ensure when we delete we delete recursive 
* We will not Poll AWS. 
* use this for the transport code https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html

Notes on how buckets, hosts and languages will work 
* The idea is to allow one or multiple buckets to work allowing our clients flexibility moving forward 
* We will accomplish this by providing variables that can be used to setup a pattern. Of course the pattern can be hardcoded without the variables allowing for any configuration 
* The variables will will respect will be {hostId} {hostname} {languageIso} {languageId}
* We will allow 2 patterns to be set. The first one is required and the second one is not 
* The required pattern is the bucketID pattern . ie.. bucketId={hostId}-{languageIso} If there is no variable used ie... bucketId=mybucketAWSID then the system will use a single bucket.  If the variable is used then it will use multiple buckets 
* The second pattern is the bucketRootPrefix.  ie... bucketRootPrefix={hostId}-{languageId}. This pattern is optional. If you had a single bucket config then you could say bucketRootPrefix={hostId}-{languageId}. which on S3 would look something like this //s3bucketID/dotcms.com/1
* If the bucketRootPrefix is not provided we will just store our top level assets as the root of the bucket 
* We should only create the bucket IF it doesn't exist. So check and if it doesn't exist try to create. So clients should be able to run with create buckets privs or without them

**Comment by chrismccracken** [comment]
Recommended:
`RESOLVE_BUCKET_NAME_CONFLICT=true|false`
If enabled, this will append a integer to the bucket name auto-pattern in the case that the required bucket name is not available (ex. `bucketId={hostId}-{languageIso}` becomes `bucketId={hostId}-{languageIso}-1`. This will also require state tracking for the env for the host/lang:bucketname map. This is an AWS-documented best practice to handle bucket namespace conflicts.

If not enabled, creation or use of an auto-pattern bucket that is unavailable due to namespace conflict will simply fail and we will not Static Push that dotCMS host/language.

**Comment by wezell** [comment]
One other variable - {languageCountry}

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/416

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10487

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10487
