### ISSUE TITLE
Create an NG2 Portlet for NGSite Browser 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10352]
* need to add dotJS into NG project now in core
* The config for the portlet.xml should be something like
<portlet>
	<portlet-name>NG2SITE_BROWSER_PORTLET</portlet-name>
	<display-name>Super Cool Site Browser</display-name>
	<portlet-class>com.dotcms.spring.portlet.PortletController</portlet-class>
</portlet>
* Add a route to NG router https://github.com/dotCMS/core-web/blob/master-3.7/src/view/components/app.routing.ts#L20 the ID maps directly to the portletID 
* Bring in dotDesktop Components

**Comment by wezell** [comment]
I believe the initial work has been done.
