### ISSUE TITLE
deploy.gradle for dotcms JAR is broken

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10363]
After the gradle layout swith, trying to upload dotcms.jar to artifactory is failing: The pom is not including the dependencies.

Steps to reproduce:
1. Compile a new dotcms.jar using gradle task deployWarTomcat.
2. [Run this command](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/deploy.gradle#L36).
3. Go to Artifactory and look under libs-release-local, com->dotcms->dotcms->3.7.0->dotcms-3.7.0.pom and click on "View" action
4. Compare with same file from 3.6.0. Dependencies are missing.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10670
