### ISSUE TITLE
Error when trying to import a bundle with messages.properties

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10361]
If a user tries to import a bundle that contains a **Language.properties** or a **Language-ext.properties**, this error is thrown:

~~~
ERROR business.PublisherAPIImpl: Error Publishing Bundle: 2 java.lang.ArrayIndexOutOfBoundsException: 2 
at com.dotcms.enterprise.publishing.remote.handler.LanguageVariablesHandler.b(SourceFile:102) ~[ee-g0951ce8.jar:?] 
at com.dotcms.enterprise.publishing.remote.handler.LanguageVariablesHandler.a(SourceFile:63) ~[ee-g0951ce8.jar:?] 
at com.dotcms.enterprise.publishing.remote.handler.LanguageVariablesHandler.handle(SourceFile:49) ~[ee-g0951ce8.jar:?] 
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5.1_3.5-8-g8506266.jar:?] 
at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5.1_3.5-8-g8506266.jar:?] 
at java.lang.Thread.run(Thread.java:745) 
ERROR lang.String: Error Publishing: java.lang.ArrayIndexOutOfBoundsException: 2 
INFO rest.PublishThread: Finished bundle publish process
~~~

## Expected Behavior

The bundle should be imported successfully

## Current Behavior

Importing a bundle that contains a **Language.properties** or a **Language-ext.properties** fails and throw an exception in **dotcms.log**.
Support ticket: https://my.dotcms.com/tickets/detail.dot?id=8cc40eb2-0737-4ab2-8f68-676c16a03997

## Possible Solution

View PR attached for 3.7. A hotfix was provided to the client

## Your Environment

* dotCMS version used: dotCMS 3.5.1
* Browser Name and version: Chrome
* Operating System and version: Linux
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8
* Database and version: Postgres
* Application module (if apply): Push Publishing

**Comment by nollymar** [comment]
PR (Enterprise): https://github.com/dotCMS/enterprise-2.x/pull/401

**Comment by shaydotcms** [comment]
Still getting the same error in the logs:
https://gist.github.com/shaydotcms/1f0c9cd0fdc797909a185d8a020110d9

**Comment by nollymar** [comment]
PR Enterprise (master): https://github.com/dotCMS/enterprise-2.x/pull/480

**Comment by shaydotcms** [comment]
Passed QA.
Successfully uploaded and downloaded bundle containing language.properties files.
Verified that other types of contents were successfully uploaded/downloaded
No errors in the logs
No errors in Status/History tab

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit 5ac4cd233500833d67b4b9d44773293bb3596af5
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
