### ISSUE TITLE
Elastic Search 1.7.X EOL 2017-01-16

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#10373]
Hi,

We see that the EOL date is near for Elastic Search 1.7.X, which is used in dotCMS.

In which version will this be updated?

https://www.elastic.co/support/eol

Thanks

**Comment by wezell** [comment]
When dotCMS last upgraded ES in 3.6,  we selected the latest version that would not cause us to change major things in dotCMS.  This was done with an eye towards backward compatibility and not forcing larger customers to reindex on upgrade or rewrite implementations.

While we are looking to upgrade ES in a future release, we do not have a target dotCMS version where we will be upgrading ES.  Our concern is specifically towards dotCMS performance, backward compatibility, stability and security.
