### ISSUE TITLE
dotcms vulnerabilities

### ISSUE THREAD

**Issue by tdr130** [dotCMS/core#10371]
Hi

Can you send me your security contact / email?
i have found some vulnerabilities in dotcms
i will email u the details or you can contact me
--
Regards,
todaro
email:tongdr@safedog.cn or root@itodaro.pw

**Comment by wezell** [comment]
Please email security@dotcms.com with any security related report. Thanks and we appreciate you reaching out to us.

**Comment by tdr130** [comment]
ok  get it
