### ISSUE TITLE
License lost on app server and db server shutdown/restart combination

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10375]
Steps to reproduce:

1. License a server
2. Shut it down 
3. Shut down the db
4. Start the server again (with no db).  

The license will get wiped out.  If you then start the db and restart dotCMS, it will have been reverted to Community

**Comment by freddyucv** [comment]
Really the error also happened without restart dotCMS but we don't have the steps to reproduce it 

support ticket:

https://my.dotcms.com/tickets/detail.dot?id=1978a6e5-e124-4cfb-bc0c-828a725b8591

**Comment by dsilvam** [comment]
dup of #9849
