### ISSUE TITLE
License error by deleting inative cluster server 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#10388]
If a user work with the follow configuration:

ENABLE_REMOVE_INACTIVE_CLUSTER_SERVER: true (default value)
ENABLE_SERVER_HEARTBEAT: false

then after 2 weeks every server become a inactive server so they are delete from the cluster_server table.

## Expected Behavior
If the heartbeat is off then deleting inactive server has to be off too

## Current Behavior

All the servers lose the license after two weeks

## Possible Solution

check the ENABLE_SERVER_HEARTBEAT properties's value before book the DeleteInactiveClusterServersJob.

**Comment by freddyucv** [comment]
PRs:

https://github.com/dotCMS/license/pull/36
https://github.com/dotCMS/enterprise-2.x/pull/406
https://github.com/dotCMS/core/pull/10413

**Comment by dsilvam** [comment]
Merge into 3.7:
https://github.com/dotCMS/license/pull/38
https://github.com/dotCMS/enterprise-2.x/pull/408
https://github.com/dotCMS/core/pull/10425

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
