### ISSUE TITLE
Click in navigation item to reload same page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#10382]
## Expected Behavior
If you are in a portlet (or iframe portlet) and you click the navigation item for the same portlet it should reload the portlet.

## Current Behavior
When you click the "active" portlet link in the main nav nothing happen.

## Possible Solution
Check if there is anything that could help us in the angular routing.

## Steps to Reproduce (for bugs)

1. Go to any portlet, ex: Content Type > Content Type
2. Click again in the nav: Content Type > Content Type
3. Nothing happens

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/255

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // h2 // Chrome
