### ISSUE TITLE
Merge License Fixes into 3.7

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10395]
We need to get the license fixes into 3.7 branch

**Comment by dsilvam** [comment]
PRs:
https://github.com/dotCMS/license/pull/40
https://github.com/dotCMS/enterprise-2.x/pull/408
https://github.com/dotCMS/core/pull/10441

**Comment by nollymar** [comment]
Changes in https://github.com/dotCMS/core/issues/10388 were merged
Changes in https://github.com/dotCMS/core/issues/9849 were already in 3.7
