### ISSUE TITLE
Unable to upgrade from 2.5 to 4.0

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10391]
## Expected Behavior
We should be able to upgrade from any version to the last one

## Current Behavior
We are having some problems in the task ```Task03140AddFileAssetsIntegrityResultTable```, then the system isn't starting  

## Steps to Reproduce (for bugs)
1. Start dotCMS-2.5 
2. Shutdown
3. Copy the assets file 
4. Start dotCMS-3.7 

## Your Environment
Tested on OSX // MySQL // dotCMS-2.5 ==> dotCMS-3.7

**Comment by bryanboza** [comment]
The same problem with Postgres and MySQL, and with the versions 2.5 and 3.2.1

**Comment by dsilvam** [comment]
Tasks Task03510CreateDefaultPersona and Task03140AddFileAssetsIntegrityResultTable need to be altered to avoid doing API calls and only have static sql.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/10446
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/410

**Comment by shaydotcms** [comment]
Passed QA
Tested with started data and cliente data
Successfully upgraded from dotcms_2.5.7 to 4.0
Tested with MySQL and Postgres db

**Comment by dsilvam** [comment]
Note to QA: Let's also test a migration from Oracle and MSSQL to 4.0 using client's db

**Comment by erickgonzalez** [comment]
MSSQL: Successfully upgrade from 3.7 to 4.0, using client's DB (originally came from 3.3) https://gist.github.com/erickgonzalez/dd41852683bc930ff4709f63b728480b

**Comment by erickgonzalez** [comment]
Issue with Oracle: https://github.com/dotCMS/core/issues/10654
