### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10400]
- [x] Remove the resize of the **Login As** window and the problems described in the screenshot http://www.screencast.com/t/uFmIX3Vwe
^ Fixed
https://github.com/dotCMS/core-web/pull/246

- [x] **Workflow tasks:** Fix the checkboxes styles http://www.screencast.com/t/i46Ju2JLAd
- [x] Problems with the table paddings http://www.screencast.com/t/U4QhdO8KVs
^ Fixed
https://github.com/dotCMS/core/pull/10437
https://github.com/dotCMS/dotcms-dojo-theme/pull/6
- [ ] **Folder/Site selector** should use the same styles as the **Site Browser** http://www.screencast.com/t/imAdrlQcaf
- [x] **Edit Page Asset:** **Language Variables** should be next to the text areas and the **Select Link** button does not work http://www.screencast.com/t/xDTaTTf8gq
^fixed
https://github.com/dotCMS/core/pull/10460

- [x] **Page Asset history:** Both tables have different margins, **Push History** should be lower, divided by a line and the Identifier should be in bold maybe?: http://www.screencast.com/t/nCMJ0wDH
^Fixed
https://github.com/dotCMS/core/pull/10494
https://github.com/dotCMS/dotcms-dojo-theme/pull/8

- [x] **Links:** Pagination should have a bigger top padding/margin  http://www.screencast.com/t/fMDUgszsIGh
- [x] **Links:** Wrong form styles http://www.screencast.com/t/kRrNexXS
- [x] **Templates:** Pagination should have a bigger top padding/margin http://www.screencast.com/t/a4arefAD
- [x] **Templates:** Fix header, right form and action buttons http://www.screencast.com/t/6eUKt6Fetc
- [x] **Templates:** Wrong form styles http://www.screencast.com/t/z3ZXA1IeA
- [x] **Templates:** History tab is not using the same styles as other history tabs http://www.screencast.com/t/HiqlgMECI
^^^Fixed
https://github.com/dotCMS/dotcms-dojo-theme/pull/11
https://github.com/dotCMS/core/pull/10494

- [ ] **Advance template:** **Select a File** should use the same style as the **Site Browser** http://www.screencast.com/t/MMui1XMeTI
--- Create new ticket ---

- [x] Fix the **Select a Container** modal http://www.screencast.com/t/0AOOw32m
--- Create new ticket ---

- [x] **Add js/css** does **NOT** work http://www.screencast.com/t/pzKTmUXmRp
- [x] Styling the Popup Menus in the **Site Browser**: http://www.screencast.com/t/4fR5FSn5kiNE
^ fixed
https://github.com/dotCMS/core/pull/10460
https://github.com/dotCMS/dotcms-dojo-theme/pull/7
- [x] Action buttons should have some padding at the bottom http://www.screencast.com/t/apTMfYEyM9
- [x] Wrong form styles http://www.screencast.com/t/y6xa24qD
- [x] Action buttons should have some padding at the bottom http://www.screencast.com/t/hsg3Uwyu7a
- [x] **Select Sites** --> **Add Site** --> Does not looks good http://www.screencast.com/t/fwQNCxmYDpq
^^^Fixed
dotCMS/dotcms-dojo-theme#11
#10494
- [ ] Improve Warning and Error messages http://www.screencast.com/t/78Zqg0U0H
--- Create new ticket --- @fmontes 

- [x] Remove empty space when there is no header http://www.screencast.com/t/strAescDAit
- [ ] Buttons should be side by side http://www.screencast.com/t/ZfAqzjhtB
--- Create new ticket ---

- [x] **Content Search** —> **Import** —>Wrong form styles http://www.screencast.com/t/ApY9zkg80b
- [ ] **NOT Priority** but his modal could look better http://www.screencast.com/t/Gj7Cv2SdGmL we already have a version of that modal in Angular, **we need both?**
- [x] Work on the for inside the modal, bottom buttons have a wrong margin, the scroll in the modal affects the window http://www.screencast.com/t/0oa8UZAgMcVg
- [x] Add new **Event**: **Image and File fields** does **NOT** work http://www.screencast.com/t/d8XO0CgoKS
- [x] **Date time fields** are transparent on hover http://www.screencast.com/t/y2agtRafE
- [x] Spaces in the pagination http://www.screencast.com/t/Cdhn2bR7
^^^ Fixed
https://github.com/dotCMS/core/pull/10645
https://github.com/dotCMS/dotcms-dojo-theme/pull/13

- [x] Apply the proper horizontal form styles http://www.screencast.com/t/zn7Ctx57mqFj
^ Was fixed in previews updates

- [x] Edit **Content Type** --> **URL Map Pattern** --> Style question mark http://www.screencast.com/t/HHUdh6Ia
- [x] Edit **Content Type** --> **Detail Page** --> **Info** --> Remove extra space http://www.screencast.com/t/efZD4gaagP
- [x] **Workflow:** Style the modal and the **Edit Workflow Scheme** button does **NOT** work http://www.screencast.com/t/0uNmJQZs
--- JS error comented ---
- [x] **Who can Use** adds multiple users even with only one selected on the dropdown and form styles http://www.screencast.com/t/fDW1pAJmpK7
- [x] Wrong form styles **Workflow > edit step** https://www.screencast.com/t/wDwnFkgxqB
- [x] **Workflow > Edit Schema** When the checkbox is checked the buttons disappear https://www.screencast.com/t/TG4Du3NRzSi
^^^Fixed
https://github.com/dotCMS/core/pull/10685
https://github.com/dotCMS/dotcms-dojo-theme/pull/16

- [x] **content types > tag manager** Delete button should be red https://www.screencast.com/t/VtVwjkevLz
- [x] Wrong styles on **Users portlet** tables and the roles tree does not respect his parent container http://www.screencast.com/t/lVFBQW4A
- [x] Wrong styles on **Roles and Tabs** tables and also the Edit Tab modal needs work http://www.screencast.com/t/ykF1Suxu , https://www.screencast.com/t/Dx38IPfH4
- [x] We are numbering the error of required fields https://screencast.com/t/glFTVuoB7J
- [x] **Maintenance** --> **Tools** --> Needs small tweaks http://www.screencast.com/t/P8hoSdXO
- [ ] The cancel button need the flat style... this on push related content window https://screencast.com/t/EORbEi38i
can't reproduce it https://www.screencast.com/t/ZY73fOaYfQS
- [x] The structure field looks too long adding structure relationships https://screencast.com/t/rNE1yrkp
- [x] Relationships error need style https://screencast.com/t/6Xf6QB9xRr, also the unique value error https://screencast.com/t/b9kTXcOBPrA
- [x] As in the old UI, the relationship tab needs some required icon https://screencast.com/t/tHh6GBwG
- [x] **Roles and tabs** > unnecessary scroll on data table https://www.screencast.com/t/MVOlGvD2e
- [x] Relate content window needs style https://screencast.com/t/NPT5Qo18Jr5 (https://github.com/dotCMS/core/commit/7a1ac8e9f0ded40c7cb58bd8b69c3d174b0e4e65)
- [x] Remove extra spaces and general layout style: http://www.screencast.com/t/XRveosPe (https://github.com/dotCMS/core/commit/6c07b27e4a1988a5e672d7bc0fe3a82689810db8)
- [x] Add proper padding http://www.screencast.com/t/X31D4KFi (https://github.com/dotCMS/core/commit/b64446aca58324557e20253a97d4e2edbd448da4)
- [ ] ~~Add properties in lang needs styling: https://cloudup.com/cBOup8aIxHo~~ (@fmontes fixed in https://github.com/dotCMS/core/issues/10457)
- [x] Site Browser, add multiple files with the same name... https://www.screencast.com/t/YKXfK6HExSpr (https://github.com/dotCMS/core/commit/d85080ee95ea2008ac9cf180c1ea3ff4b0fb02c9)
- [x]  Site browser, add page with an invalid URL... this name(!@#$%^&*&()_+") 
https://screencast.com/t/70kGhSJY4 (https://github.com/dotCMS/core/commit/d85080ee95ea2008ac9cf180c1ea3ff4b0fb02c9)
- [x] Site browser, validation message it's not showing correctly in some cases: https://cloudup.com/ckx2Oj0eVjn (https://github.com/dotCMS/core/commit/588d207d53be4413c696a71e756381023752ca43)
- [ ] ~~Site browser, try to upload files window, this on single and multiple files...~~ https://screencast.com/t/LopDspLCsK (@fmontes fixed in https://github.com/dotCMS/core/issues/10457)
- [x] Needs form styles http://www.screencast.com/t/x9DGnWRz9 (https://github.com/dotCMS/core/commit/aac5f60ba993c6f9dd02e531f6e4ba122aa9f6cb)
- [x] Remove the _ http://www.screencast.com/t/DniTvRoua0Hh (https://github.com/dotCMS/core/commit/9d27c3f4869389d12883e5f5459fba6761c99bb1)
- [x] The Popup Menu needs work http://www.screencast.com/t/rTBvXg5w (https://github.com/dotCMS/core/commit/64b9ea27fad9e2ea931a36d85d135d76731fe253)
- [x] The delete icon needs to be on the center of the table column and there is a scroll even when the window have space http://www.screencast.com/t/yvkzqMHqMghr also the form doesn't have the correct html markup (https://github.com/dotCMS/core/commit/7edcb112a7d7f29b25ef0f09bb4e980503b03dc9)

**Comment by bryanboza** [comment]
Fixed, some new tickets opened here:
https://github.com/dotCMS/core/issues/10805
https://github.com/dotCMS/core/issues/10806
