### ISSUE TITLE
Publish issues in Templates and Containers

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10405]
Publish Templates and Containers using right click is not working.

**Comment by jdotcms** [comment]
When you get login into the new UI; go to SiteBrowser, then templates, then select an element and right click on unpublish, it worked, then right click on publish and it is not working, it seems to work at the second time, but should work the first time.

Similar scenario for Containers.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10435

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // Chrome
