### ISSUE TITLE
Clean out old/deprecated macros and ViewTools

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10402]
We have a number of Macros and viewtools that have been deprecated.  We should remove these before 4.0.0

**Comment by jgambarios** [comment]
This is the branch https://github.com/dotCMS/core/tree/issue-10402-remove-deprecated-stuff
We need to make sure to run all the tests and functionality before to merge this branch.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10742

**Comment by bryanboza** [comment]
Fixed, some new issues reported related to this changes...
