### ISSUE TITLE
Make insert of permissions references in PermissionsFactory to be eager by configuration

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10409]
We have code that deletes the permission references and then eagerly inserts them. 

See all the inserts of references in these methods:

- [ ] com.dotmarketing.business.PermissionBitFactoryImpl#updatePermissionReferencesOnAdd

- [ ] com.dotmarketing.business.PermissionBitFactoryImpl#resetPermissionsUnder

This needs to be changed to depend on a config property PERMISSIONS_REFERENCES_INSERT_LAZILY, which defaults to 'true'. If Property equals to false then we do the inserts, if not, we simply let them load lazily.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10420

**Comment by agomez-dotcms** [comment]
Please notice the name of the property was finally named as "PERMISSIONS_REFERENCES_INSERT_LAZILY" (defaulting to 'true')

**Comment by john-thomas-dotcms** [comment]
Added to Permission Inheritance Doc: http://auth.dotcms.com/docs/latest/permission-inheritance#PerformanceCompatibility
Added to Release Notes.

**Comment by erickgonzalez** [comment]
QA Passed with the steps provided by Anibal. Also talked with Mauricio and he tried the changes on an AWS machine with client's data and time reduces by 50%.
