### ISSUE TITLE
Unable to see the drop down options on Safari and FF

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10414]
## Expected Behavior
We need support the basic functionality in all the supported browsers 

## Current Behavior
Right now, we are unable to see the drop down options in Safari, this when you try to see the user list in the LoginAs. 

## Steps to Reproduce (for bugs)
1. Login as Admin user 
2. Try  the LoginAs 
3. Try to expand the users drop down 

## Your Environment
Tested on master-4.0 // Postgres // Safari

**Comment by bryanboza** [comment]
FYI: This is working fine on Chrome

**Comment by woontsoudev** [comment]
This is a Primeng issue and is posted on github:
https://github.com/primefaces/primeng/issues/745

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/252

**Comment by bryanboza** [comment]
We still having problems with this case... Now we can see the drop-down, but if you open it and close, and then try to open again you are unable to see... 

FYI: No errors on console and the same behavior on FF and Safari

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/256

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // Chrome
