### ISSUE TITLE
Rename Task03730UpdateMssqlVarcharTextColumns and adapt 4.0 upgrade tasks

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10428]
Since we are backporting this to 3.7, this task needs to be renamed to avoid it running twice

Rename to Task03600UpdateMssqlVarcharTextColumns

Also, upgrade tasks in the range 3700 <= and < 3730 need to be modified to change de varchar to nvarchar for mssql

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10448

**Comment by shaydotcms** [comment]
Passed QA
Tested on latest master_4.
SQLServer 2012 
Win7 Pro SP1
