### ISSUE TITLE
Workflow improvements for lock management

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#1042]
For history read https://github.com/dotCMS/dotCMS/issues/950

1) Show actionlets that have "Requires Lock" = false even if the piece of content is locked. This needs to be done on the Workflow Portlet detail page and on the edit contentlet screen

2) develop workflow actionlet called "SuperUserUnlockContentlet" that uses the System User to unlock the piece of content. This will allow Workflow admins to create a workflow action that will release a lock, regardless of who has the lock on it

**Comment by wezell** [comment]
#1 is part of the new workflow process, #2 is a good idea.  We can reopen if needed.
