### ISSUE TITLE
Fix corrupted source files

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10433]
There are a couple of files with problems with ^M chars at the end of each line.
They cannot be properly diff'ed in git thus making code reviews impossible. 

- DBConnectionFactory: https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotmarketing/db/DbConnectionFactory.java

- DBConnectionFactoryTest: https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/integration-test/java/com/dotmarketing/db/DbConnectionFactoryTest.java

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10621

**Comment by oarrietadotcms** [comment]
FWIW I used this tool on Mac:
`mac2unix -n src/main/java/com/dotmarketing/db/DbConnectionFactory.java src/main/java/com/dotmarketing/db/DbConnectionFactory.java`

**Comment by oarrietadotcms** [comment]
PR for master 4.0: https://github.com/dotCMS/core/pull/10625

**Comment by oarrietadotcms** [comment]
PR for 4.1, class: src/main/java/com/dotmarketing/db/LocalTransaction.java . https://github.com/dotCMS/core/pull/10943
