### ISSUE TITLE
Unable to create new content from some content types

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10436]
The system is throwing errors when you create new content from existing content types such as Widget and Personas

## Expected Behavior
You should be able to create new content out from Widget and Personas without issues

## Current Behavior
The system is throwing errors when you create new content from existing content types such as Widget and Personas

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Search
3. For a Widget content type: 
-Select News Listing from the dropdown
-Click "Add New Content"
-You will get the error in the logs
https://gist.github.com/shaydotcms/6d77d5b09b8695fc1f79b7836cf87b60#file-error-with-widget-content-type

4. For a Persona content type:
-Select Persona from the dropdown
-Click "Add New Content"
-You will get the error in the logs
https://gist.github.com/shaydotcms/6d77d5b09b8695fc1f79b7836cf87b60#file-error-with-persona-content-type

## Your Environment
- dotCMS version used: Latest master_4.1
- Database and version: MySQL 5.6.23
- Operating System and version: Mac OS 10.10.5
- Browser Name and version: Firefox v45.0.1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10450

**Comment by erickgonzalez** [comment]
Passed QA. Now able to create Widget and Persona successfully.
