### ISSUE TITLE
Fix asset create UUID collisions based on MINIMUM_SHORTY_ID_LENGTH

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#10444]
When using shorty ID's for /contentAsset/... -> /dA/..., it is possible to get shorty id collisions. For example, 
`1a190d07-3834-4bed-aad7-27cfa942c7b1` and `1a190d07-1233-7bad-def7-27cfa932c7b4`
will both resolve to `1a190d07` if `MINIMUM_SHORTY_ID_LENGTH=8`.

One way to avoid this collision would be to check for the collision at the time of asset creation. When the UUID is generated, we could check if the MINIMUM_SHORTY_ID_LENGTH prefix of that UUID already exists before we use it. If it DOES exist, then we simply generate a new UUID and check for collision again before use. The prefix we check for would vary based on MINIMUM_SHORTY_ID_LENGTH. We should not need to check all identifiers, only those for file content assets that are exported via shorty IDs.

**Comment by wezell** [comment]
`MINIMUM_SHORTY_ID_LENGTH` is 10
