### ISSUE TITLE
On session destroy Event delay after logout

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10447]
## Expected Behavior
When you logout, we need just killing the local session 

## Current Behavior
We are having problems after you logout and login again, this because the on session destroy event is delaying, then if you logout and login immediately, the system is killing the session 

## Steps to Reproduce (for bugs)
- Login as admin 
- Logout 
- Try to login again but immediately 

## Your Environment
Tested on master-4.0 // Postgres // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/248

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // Chrome
