### ISSUE TITLE
Styling Dojo Portlets

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10457]
Related to #10242 

## Portlets

- [x]  The properties portlet looks more ordered with the left aligned, as in the old UI http://screencast.com/t/JTTysZqT70y (https://github.com/dotCMS/core/commit/a5e9c62f580978ac2bc0e2f0569f0dae17d979af)

**Links**
- [x] Create and edit link form need styling. (https://github.com/dotCMS/core/commit/27e455cdd9830d596b17a2d2f69fe67be8cda22c)
- [x] Need show a complete path in the folder field  after add any link (https://github.com/dotCMS/core/commit/27e455cdd9830d596b17a2d2f69fe67be8cda22c)
- [ ] ~~Unable to order by title or mod date, clicking the column header (neither works on demo)~~

**Templates**
- [x] Unable to add js/css in the template field, the button does not working (https://github.com/dotCMS/core/commit/050dd0227a6f066be059aad7f1e683dc0ed673b0)

**Categories** 
- [x] Need center the text in the permissions tab … https://screencast.com/t/yxuwZQ2lN (https://github.com/dotCMS/core/commit/08c439c915111f03addf08be696a008aa6f95e9a)

**Vanity URL**
- [ ] ~~The vanity URL need styling help https://screencast.com/t/LgNqcaE41~~ (**This forms in big screens needs to be fixed globally**)
- [ ] ~~Unable to order fields by the column names: URL and title http://screencast.com/t/oNKadV2Qmzd~~

**Users**
- [ ] ~~JS error trying to add tags, the system isn't showing the suggested tags in the marketing tab http://screencast.com/t/uciEquxP~~
- [ ] ~~Unable to delete tags, after add some one~~
- [x] Remove "Marketing" tab (https://github.com/dotCMS/core/commit/ded3c0fe8bcbbb2e077f5a80688deee6212e4e79)
- [x] Permission box cut off: https://cloudup.com/c0UiJDm6-Ya (https://github.com/dotCMS/core/commit/d233cb55c9fcea0b1cda4a53663e09e07ee21031)
- [x] When create a user there is a empty button: https://cloudup.com/cwtJm9THiCZ (https://github.com/dotCMS/core/commit/0aaa8761529c8f0b712a6bc6f1b0f316c75937bc)

**Roles and Tabs**
- [x]  Permission box cut off: https://cloudup.com/c0UiJDm6-Ya (https://github.com/dotCMS/core/commit/d233cb55c9fcea0b1cda4a53663e09e07ee21031)
- [x]  After add some tabs we need create an scroll to avoid override the some components https://screencast.com/t/Riti75zIRJ (https://github.com/dotCMS/core/commit/5d11b4346f912d58ba94721f9382f4a157bf0657)

**Content Type**
- [x]  Make sure all icons shows: https://cloudup.com/clu6mLRZGlQ (https://github.com/dotCMS/core/commit/f57e0e91cd2a9c1971cdeba67afa6c854e3a9073)

**Site Browser**
- [x]  Make sure all icons shows: https://cloudup.com/cOUWNjvqxK5 (https://github.com/dotCMS/core/commit/f57e0e91cd2a9c1971cdeba67afa6c854e3a9073)
- [x] Fix this icons: https://cloudup.com/cWH5nQKd9YV (https://github.com/dotCMS/core/commit/5745bb32fcbda5c6f574921092fb9548abbf778a)
- [x] Remove extra icon in context menu
- [x] Fix dialog for "add page": https://cloudup.com/cPXGw4FRucB (https://github.com/dotCMS/core/commit/b9cd69e2beb05a47abe16a81c1d9bf34d092c53d)

**Configutation**
- [x] *Network Tab:* Need add icons to show the status of every one of the nodes (https://github.com/dotCMS/core/commit/76894312cb8ce46e763a5b311f03652b64e38496)
- [x] *Publishing Environment:* The push environment needs styling help https://screencast.com/t/2ujvPYzMqCp (https://github.com/dotCMS/core/commit/10ae76ecf521598d5b62bc835d402462fbd5c7cb)
- [x] *All tabs:* needs to fix height. (https://github.com/dotCMS/core/commit/10ae76ecf521598d5b62bc835d402462fbd5c7cb)

**Sites**
- [x] Needs to fix checkbox: https://cloudup.com/ci8u3UIQi0D (https://github.com/dotCMS/core/commit/d74286c44ce57791d786e8f495ab57fc1358d6ab)
- [x] Unable to see the site status, if the site is active or stoped you don't know (https://github.com/dotCMS/core/commit/2608bba8cdd911d54297b7d59c154e67367ad99a)

## Components
- [x] Permission component styling (https://github.com/dotCMS/core/commit/08c439c915111f03addf08be696a008aa6f95e9a)
- [x] Site selector width it's too big make it fit content: https://cloudup.com/cAnDB5tELGb (https://github.com/dotCMS/core-web/pull/257)

Tested on master-4.0 // H2 // Chrome

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/10532
https://github.com/dotCMS/dotcms-dojo-theme/pull/9

**Comment by bryanboza** [comment]
**Categories:**
- [ ]  Need change the permissions icons https://www.screencast.com/t/sCA4ba5aL

Users
- [ ] The permissions tab needs styling help: https://screencast.com/t/rR89k7KSwp

Roles & Tabs:
- [ ] The permissions tab needs styling help: https://screencast.com/t/2kNLfzraU

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0
