### ISSUE TITLE
Add timestamp variables to AWSS3Publisher

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#10465]
to our current list of variables which can be used in the bucket name and folder prefix we need to add 2 more. 

{date} which will default to yyyyMMdd-HHmmss if no pattern is supplied
and 
{date-yyyyMMdd-HHmmss} to change the pattern.

**Comment by agomez-dotcms** [comment]
Hi Guys, this has been implemented already and the new variable may be used in two different ways:

1. "{date}" which defaults to "yyyyMMdd-HHmmss" format

2. "{date-yyyyMMdd-HHmmss}" which formats the date using the provided custom format. Please notice the custom format only supports alphanumeric and hyphen characters. Custom format also assumes the pattern letters supported by Java's Simple Date Format: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html.

Thanks,
Anibal

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10497

**Comment by agomez-dotcms** [comment]
Passed QA. Both default and custom date format placeholder are working as expected when used as part of bucket-name and folder-prefix. Moving to Done
