### ISSUE TITLE
Error creating/deleting any content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10469]
## Expected Behavior
We should be able to create or delete any content type without problems 

## Current Behavior
We are having an error on logs every time you delete or create some structure 
Here the SC: https://gist.github.com/bryanboza/d590a9265258b0aac7a959a73fd98d27

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types and create a new one 
3. Check the logs 

**FYI:** The same case if you delete some one 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10472

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
