### ISSUE TITLE
BinaryExporterBundler not supporting all patterns 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10474]
So we had an issue in 2013 https://github.com/dotCMS/core/issues/4258 where we altered the pattern 
https://github.com/dotCMS/enterprise-2.x/blob/b600c97398a0c2680fd98e6344ba1c8d40801c1c/src/com/dotcms/enterprise/publishing/bundlers/BinaryExporterBundler.java#L59

Basically this pattern doesn't work
http://localhost:8080/contentAsset/resize-image/97e2e928-8f6c-4253-a07e-2eb1d5d10e3f/image/h/125

but this does 
http://localhost:8080/contentAsset/image/97e2e928-8f6c-4253-a07e-2eb1d5d10e3f/image/filter/Resize/resize_h/125

You can see this doing a static push and looking at the home page you will have images returning 404

We need to update the pattern and test including testing the original issue from 2013

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10487
