### ISSUE TITLE
Reindex failing on an upgrade to 4.1

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10473]
Reindex is failing after upgrading from dotcms_3.6.0 to dotcms_4.1 using client's db on both postgres and MySQL. 

Log (MySQL): https://gist.github.com/nollymar/85e1299db343b40cf31b661a993988fb

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10498

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10509

**Comment by nollymar** [comment]
Tested on client dbs (Postgres/ MySQL)

**Comment by shaydotcms** [comment]
Passed QA.
Tested on latest master-4.1.0 / Win7 Pro SP1 / SQLServer 2012
