### ISSUE TITLE
Web-Socket connection is broken after refresh the browser page  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10471]
## Expected Behavior
We need keep this connection after refresh the browser page, this to allow the user receive notifications 

## Current Behavior
After you login and refresh the browser page, the web socket connection is broken, and you are unable to receive notifications automatically of any event, you need refresh the page manually to see the new notifications 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types and delete some content field 
3. Make sure you are receiving notifications automatically 
4. Refresh the browser page 
5. Make the same process again and you can't receive the notification 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/249

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // Chrome & FF
