### ISSUE TITLE
Error deleting content types with associated content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10485]
## Expected Behavior
We should be able to delete any content type with associated content, this without problem 

## Current Behavior
We are having an error in the log every time you try to delete some content type and this have associated content 

Here the log:  https://gist.github.com/bryanboza/12681c0c973ce857f17279b17e966798

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content type 
3. Add some content to this structure 
4. Try to delete the created content type 

## Your Environment
Tested on master-4.0 // MySQL // Chrome

**Comment by jgambarios** [comment]
Same error was reported by jenkins: https://cb.dotcms.com/view/master-4.0/job/Git_Master_Int_Funct_Test_Runner_4.0_Postgres/149/testReport/

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10545

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
