### ISSUE TITLE
Problems with the notifications in cluster 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10484]
We are having some inconsistencies with the notifications, this when you are in cluster 

## Expected Behavior

- [ ] The notifications should work by role and not by user, then if you reindex, this notifications should be sent to all the admin roles 

- [ ]  You should be able to delete notifications from any node 

## Current Behavior

- [ ] If you reindex from any node, and you are login as different admin users (every node), both users should be notified, but the system is sending the notification just to one of those. 

## Steps to Reproduce (for bugs)
1. Configure your cluster
2. Login as different admin users in both instances 
3. Reindex in one 
4. Check the notification 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10536

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
