### ISSUE TITLE
Create PDF Thumbnailer

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10499]
I thought the 12 Monkeys lib would give us the ability to thumbnail PDFs but that it not the case.  Having the ability to thumbnail PDFs like any other image based asset would be a nice new feature.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10506

**Comment by DeanGonzalez** [comment]
http://auth.dotcms.com/docs/latest/image-resizing-and-processing
