### ISSUE TITLE
Error when clicking on "View Entries" (Content Types)

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10503]
Similar to #10502 .

Click on View in the "Entries" column of any content type. Redirection to the Content Search screen will take place with the proper type selected, but no content will be listed.

**Comment by erickgonzalez** [comment]
Browser Console Error: doSearch is not defined

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10543

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
