### ISSUE TITLE
Static Publishing problems with Links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10508]
As all the other not supported elements, if you try to push any link to some amazon S3 server the system have a different behavior 

## Expected Behavior
We have two options here: 
- Like all the not supported elements, the system should show an error message before try to push 
or
- We should support push links, this because you can see the menu links from front-end because is a static link 

## Current Behavior
The system is pushing the entire site. 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your static publishing environment 
3. Create a new link from site browser 
4. Try to push 

## Your Environment
Tested on master-3.7 // MySQL // Chrome

**Comment by dsilvam** [comment]
Related to: https://github.com/dotCMS/core/issues/10504

**Comment by dsilvam** [comment]
This is not supported

**Comment by dsilvam** [comment]
Handled in https://github.com/dotCMS/core/issues/10504
