### ISSUE TITLE
Error when clicking on "View Entries" (Content Types)

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10502]
This error is displayed when trying to view entries for **Tour RSVP**:
An unexpected system error occurred.
limit param must be more than 0.

No more details in dotcms.log.

## Expected Behavior

If a user clicks on View Entries for any content type, the application should display all entries for that content type.

## Steps to Reproduce (for bugs)

1. Go to Content Types
2. Search for Tour RSVP content type
3. Click on "View Entries"
4. An error is displayed: "An unexpected system error occurred. limit param must be more than 0"

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (Client DB). Shared on dotCMS' Google Drive: dotcms_postgres_ticket_10501_10502.sql.zip
* Application module (if apply): Content Types

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10607

**Comment by shaydotcms** [comment]
Passed QA.
I was able to view Entries for Tour RSVP and the other content types
Tested on upgrade using 3.6 client db to latest master-4.1
Mac OS 10.10 / Postgres 9.3.5
