### ISSUE TITLE
Static Publishing inconsistencies 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10504]
We are having some problems trying to push some objects to the amazon S3 servers, this because the s3 servers just support push images, pages and files, and from the system level we allow push multiple things, then we need catch this exception to avoid failures when you try to push multiple things in bundles 

## Expected Behavior
We need try to catch this exception 

## Current Behavior
We are showing an error with the StaticDependencyBundler in logs every time you try to push a not supported element... This like: categories, templates, containers, etc... 

## Your Environment
Tested from master-3.7 // MySQL // Chrome, this pushing to a S3 server

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/421

**Comment by agomez-dotcms** [comment]
Hey Guys,

After changes merged above following is a summary of the elements supported / not-supported for static publishing functionality:

- Supported Elements: pages, files, images, folders and hosts
- Not Supported Elements: links, templates, containers, rule, content-types and categories

For the elements **not** supported, static publishing functionality is ignored for each of the elements involved.

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
Passed QA. After trying to push any of the **not** supported elements, errors are not appearing anymore and instead an **empty** bundle is pushed (with no side effects). Moving ticket to Done
