### ISSUE TITLE
Unable to include a File to a content whose type has "File" field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10500]
Steps to reproduce:

1. Add new type with a "File" field
2. Go to Content Search and add new content of that type
3. Hit the "Browse" button next to the "File" field.

No file dialog will open and the following error is thrown in the browser's console:

https://gist.github.com/dsilvam/289833cf06ab862919ce138559bb6568

Reproduced in master- 4.1. Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10548

**Comment by bryanboza** [comment]
We still having problems in that case... We have a struts error on log here:
```ERROR portlet.StrutsPortlet: java.lang.ClassCastException: org.apache.catalina.connector.RequestFacade cannot be cast to com.liferay.util.servlet.UploadServletRequest```
To recreate: 
1. Add new type with a "File" field
2. Go to Content Search and add new content of that type
3. Hit the "Browse" button next to the "File" field.
4. Select any folder and upload a new file 
5. Save the content 

![1](https://cloud.githubusercontent.com/assets/2641437/22386576/56e46cac-e49d-11e6-8993-a678fc4f7c05.png)

**Comment by jdotcms** [comment]
Unable to reproduce on latest 4.0 code

**Comment by bryanboza** [comment]
Tested in the last master-4.0 // H2 // FF
