### ISSUE TITLE
Error adding/editing content with relationships

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10501]
When trying to add or edit a content with relationships a message is displayed (Ooops, sorry. This has caused a problem. Try again) and an exception is thrown (https://gist.github.com/nollymar/0e4f827c12b74f4701d962c560717337)

## Steps to Reproduce (for bugs)

1. Add or Edit content of type: Comment or Blog 
2. After clicking Add or Edit Content this message is displayed "Ooops, sorry. This has caused a problem. Try again."
3. In **dotcms.log**,  this exception is thrown: https://gist.github.com/nollymar/0e4f827c12b74f4701d962c560717337

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: Google Chrome
* Operating System and version: MacOS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (Client DB). Shared on dotCMS' Google Drive: dotcms_postgres_ticket_10501_10502.sql.zip
* Application module (if apply): Content

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10510
