### ISSUE TITLE
NavTool: Cannot render menu if Page is forwarded from Vanity URL

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10513]
Starting 3.3, NavTool allows to build a Menu by taking only a level. By default, the request.getAttribute(“javax.servlet.forward.request_uri”) value is pulled from the request and then a lookup in the current Site is made, trying to find the folder and then pull all Show On Menu items.

## Expected Behavior
Regardless of how a page is accessed (regular visit vs redirect vs forward), the menu should be built.

## Current Behavior
After visiting a Vanity URL and the forward to the mapped page is made, the request.getAttribute(“javax.servlet.forward.request_uri”) lookup on a page returns the Vanity URL uri. Lookup on data fails because the Vanity URL might not match with an existing folder, or it could return different values in case the URI matches a folder (which might be different than the mapped value on the Vanity URL definition).

## Possible Solution
Make a lookup and ask if the Path is a Folder or a Vanity URL

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Create a page under /about/locations. Mark "Show On Menu" Box. For testing purposes, page name is /about-us/locations/our-locations
2. On this page, create a SimpleWidget and use the NavTool.getNav(2) as Velocity Code:

```
#set($list = $navtool.getNav(2))
$list
```

3. Create a Vanity URL
    - URI: locate-me
    - Site: demo.dotcms.com
    - Page: /about-us/locations/our-locations

4. Visit the page in live mode, after clearing all caches:

    - /about-us/locations/our-locations: Menu is displayed, only one link is shown
    - /locate-me: Menu is not displayed. It only shows $list variable.

## Context
Lookup here should be transparent to client, regardless of how a page was accessed. 
Reported by client: https://my.dotcms.com/tickets/detail.dot?id=8e6f14ff-d4f1-40ec-81ef-968b95ae3243

## Your Environment

* dotCMS 3.5.1, 3.6.2.
* Google Chrome Browser.
* macOS Sierra.
* Tomcat 8.0.18.
* openJDK 8.
* Postgres 9.4.1, SQL Server 2012-2014.

**Comment by wezell** [comment]
Guys, we do have a way to do this, I believe.  I am pretty sure this example will work if you pass the right path to the $navtoo, e.g. do a `$navtool.getNav( path )` call with the $dotPageContent object like this 
`$navtool.getNav( $dotPageContent.path )` or `$navtool.getNav( $dotPageContent.parentPath )`

**Comment by joseorsini** [comment]
@wezell passing in the path always works. The problem is we pass i only a Level, which defaults to the request.getAttribute(“javax.servlet.forward.request_uri”). This value is different than $VTLSERVLET_URI property in case the page in question is the result of a forward made by a Vanity URL. 

See the screenshots: 

<img width="634" alt="screen shot 2017-01-23 at 4 57 11 pm" src="https://cloud.githubusercontent.com/assets/1717110/22224556/10795a24-e18d-11e6-916c-c0898e74ea67.png">

<img width="483" alt="screen shot 2017-01-23 at 4 57 13 pm" src="https://cloud.githubusercontent.com/assets/1717110/22224561/134ddbc6-e18d-11e6-8d50-8f7674c28d09.png">

Again,  passing in the path works. This particular scenario with Vanity URLs and passing in only a level is not working.

**Comment by wezell** [comment]
I might be missing something but I think this is good and expected default behavior.  When using URL Mapped content or Vanity URLS, the customer should make a determination as to which "path" they want to build their nav from and pass that in.


If they want the Vanity URL to map property every time, they should have the Vanity do a redirect to the desired page rather than a forward (you do this by setting the target as a whole url,  locate-me => http://customer.com/about-us/locations/our-location

**Comment by joseorsini** [comment]
Got it. Workaround was presented to the client and waiting for their feedback. Thanks, @wezell!

**Comment by nkeiter** [comment]
Unfortunately Wezell's “solution” doesn't work on our version. The ($dotPageContent.path & $dotPageContent.parentPath) properties either do not exist or are not visible to us in 3.5.1. Also, Wezell's solution isn't valid for the case study, in that we needed it to work for depth level numbers when the path was variable or not intuitive.

However, we were able to build a different workaround in our macro to get vanity URLs working.

**Comment by john-thomas-dotcms** [comment]
@wezell the Vanity URL solution is a good one, but I don't think there's a similar way to get this working well for URL Maps.  So unless I'm missing something, I think that means that any general navigation (such as side bar navigation, header and footer navigation, etc.) will need to use paths instead of levels with $navtool.

Is that how we want it to work?  (If so I'll update the docs with that recommendation).
