### ISSUE TITLE
Test Upgrade to 3.7 on MSSQL

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10516]
Using client's db and starter. 

- [x] Create/Modify/Delete Content-Type

- [x] Create/Modify/Delete Field

- [x] Create/Modify/Delete Contentlets

- [x] Create/Modify/Delete Folder

- [x] Create/Modify/Delete Pages

- [x] Upload File Asset

- [x] Reindex

- [x] Push assets

**Comment by erickgonzalez** [comment]
dotcms.log upgrade from 3.3 to 3.7 https://gist.github.com/erickgonzalez/847a1c27ac64a32919d6cada5395a602

Also, smoke tested the items above and worked successfully.
