### ISSUE TITLE
Unable to create a past time machine snapshot

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10511]
## Expected Behavior
We should be able to create a past time machine snapshot without problems 

## Current Behavior
We are showing an error on logs every time you try to create a past time machine snapshot 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to time machine portlet 
3. Try to create a past snapshot
4. Check the logs 

## Your Environment
Tested on master-3.7 // MySQL // Chrome

**Comment by nollymar** [comment]
The root cause was an attempt to copy a directory with empty files. A new validation was included.

PR (Enterprise): https://github.com/dotCMS/enterprise-2.x/pull/420

**Comment by shaydotcms** [comment]
Failed QA. Still unable to create a past TM after upgrade from 3.6 using client data
https://gist.github.com/shaydotcms/f760215035d75a6496e35952dfb7c8bd

![image](https://cloud.githubusercontent.com/assets/8741846/22308865/63923398-e30e-11e6-9f5c-215a0f523363.png)

Tested in latest master-3.7
Ubuntu / Postgres / FF
