### ISSUE TITLE
Static publishing problems pushing complete sites

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10527]
We are having problems when you try to push some site different to demo.dotcms.com, this because we are including in all the demo site in the bundle. 

## Expected Behavior
We should include just the site you are pushing and some dependencies from demo if is necessary

## Current Behavior
We include all the site 

## Steps to Reproduce (for bugs)
1. Login 
2. Configure your push environment 
3. Create a new site and add a new page  
4. Try to push the new site 

## Your Environment
Tested on master-3.7 // MySQL // Chrome

**Comment by bryanboza** [comment]
FYI: Also we have this error when you try the same but with force push...

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/425

**Comment by nollymar** [comment]
Tested both scenarios: push/force push. Result: Successful
