### ISSUE TITLE
Disable AWS endpoint in UI if license != platform

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10523]
We need to disable the selection of AWS in the UI and in the API if the license level does not permit it.  We will need a new language key as well - `publisher_Endpoint_type_awss3_requires_platform_license`

**Comment by wezell** [comment]
![screen shot 2017-01-25 at 9 16 02 am](https://cloud.githubusercontent.com/assets/934364/22293788/f45966f6-e2de-11e6-8e27-0f69192a7fcd.png)

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10525
