### ISSUE TITLE
Add new Endpoints properties to language file

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10528]
A couple of changes are needed in the Language.properties file:

1. Include a new property "publisher_Endpoints=Endpoints" and reference it here: https://github.com/dotCMS/core/blob/master-3.7/dotCMS/html/portlet/ext/cmsconfig/remotePublishing.jsp#L877 instead of "Servers"

2. Include a new property "publisher_Add_Server=Add Server" and change the value of property "publisher_Add_Endpoint" to be "Add Endpoint". Use "publisher_Add_Endpoint" property here https://github.com/dotCMS/core/blob/master-3.7/dotCMS/html/portlet/ext/cmsconfig/remotePublishing.jsp#L1006, and "publisher_Add_Server" property here https://github.com/dotCMS/core/blob/master-3.7/dotCMS/html/portlet/ext/cmsconfig/remotePublishing.jsp#L1044

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10530
