### ISSUE TITLE
Save and publish content is not redirecting to the referer

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#10539]
## Expected Behavior
After you save and publish a content you should be redirected to the listing. 

## Current Behavior
When you add or edit a content, after saving you are not redirected to the referrer as before. You stay in the add/edit window without value. If you click cancel you are redirected to the listing and the new or edited contentlet is saved. There is an issue that the referrer is not being set or is not being redirected to the listing

## Steps to Reproduce (for bugs)

1. Go to content search or site
2. Add or edit a content
3. click save and publish button
4. The content is saved but you are not redirected to the content search view. you stay in the add/edit content window empty

## Your Environment
* dotCMS version used: 4.0
* Browser Name and version: any browser
* Java Brand and version: 8
* Database and version: all

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10570

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10595

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
