### ISSUE TITLE
Issue editing text file when it’s created as multilingual file 

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10537]
When you have a text file and want to create a multilingual version of it, you cannot edit it until you save it and reopen it again. Refer to #4849 

## Expected Behavior
You should be able to edit the file without having to save it first.

## Current Behavior
When you have a text file and want to create a multilingual version of it, you cannot edit it until you save it and reopen it again.

## Steps to Reproduce (for bugs)
1. Go to Site Browser> Add New button> Image or File
2. Select File Asset and add a text file in default language (English)
3. Save the file
4. Right click over the file to edit it
5. Save the file in another language (Espanol)
6. Hit "Edit text" button next to Resource Link
7. You will see that you cannot edit it 
Browser console error:
Contentlet : is null Object {javaClassName: "com.dotmarketing.business.DotStateException", message: "Contentlet : is null"}
8. You have to save it and reopen it again so you can edit the file

![resource link](https://cloud.githubusercontent.com/assets/8741846/22314551/cb726f3c-e327-11e6-8fb5-83913c0343fe.gif)

##Your Environment
- dotCMS version used: demo.dotcms.com / latest master-3.7
- Database and version: All DBs
- Operating System and version: Ubuntu 14.04.1 / Win7 Pro SP1 / Mac OS 10.10.5
- Browser Name and version: Firefox v45.0.1
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by wezell** [comment]
New ui
