### ISSUE TITLE
Unable to see new pages in the static environment if you don't push the entire site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10534]
We are having problems to see the new pages in the FE of the static environment. This because 
If you create a new page and enable the show on menu property, and you try to push that to an static environment that you previously pushed some content, the system push the new page, but the html of the site was generated previously, then you can't see this page from FE... 

To see that changes you need push the entire host again. 

## Expected Behavior
We need some way to check this property and generate again the html of the site, too see the new changes, this because don't make sense the individual push if you can't see the changes in the site... 

## Current Behavior
The system just push the page, but you can't see it from the site 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure the static pushing environment 
3. Push the entire site 
4. Create a new folder with a new page that have the show on menu property 
5. Push this folder or site
6. Try to see it from the front-end site 

## Your Environment
Tested on master-3.7 // MySQL // FF

**Comment by jtesser** [comment]
As discussed just a doc issue
