### ISSUE TITLE
Unable to push pages to static publish environment after edit some content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10533]
We are having some problems when you push some page and after this you edit the page and try to push it again, this because when you edit the page you modify some content, but the page have the same **mod_date**... Then when you try to push the system compare the mod_date column and send the bundle empty, this because isn't detecting changes in the page. 

## Expected Behavior
After edit the page we should be able to push again and update the content in the Amazon S3 server 

## Current Behavior
The system is comparing the mod_date field and no detect changes 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your static publishing environment 
3. Create a new page and add some content 
4. Push this page 
5.  Edit some of the contents of the page and save and publish 
6. Try to push again 

## Your Environment
Tested on the last master-3.7 // MySQL // FF

**Comment by dsilvam** [comment]
Handled here : ee PR: dotCMS/enterprise-2.x#427
