### ISSUE TITLE
Import Contents: Multilingual contents cannot be added if selected Key field is Unique

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10541]
Currently, Import Contents tool allows us to create/update multiple versions (on different languages) of the same content, as long as the language-related columns are added to the CSV file you import. In some cases, it's expected that a content editor creates multiple versions at the same time for the same content, being the Language the only difference between each version. 

## Expected Behavior
In the same way the Content Search portlet works, the Import Tool should allow you to create multiple versions of a content, on different languages, regardless of the Content Type fields' attributes. Currently, we can duplicate an existing content in one Language, leave the content as is (but with a different language) and save/publish, even if we have unique fields on the Content Type.

## Current Behavior
We cannot import two contents with the same value under a Unique Field, marked as Key field once the CSV file is imported, even if each CSV row has a different value. This should not prevent the content from being created because it differs from the scenario described on the "Expected Behavior" section of this ticket.

## Possible Solution
Fix the ImportUtil.java class and allow contents with same values on unique fields (selected as key field) AND different languages to be created.

## Known Workarounds
Setiing a different value for each Unique field on every version of the same content, because if it's not selected as Key field once imported, then it will create separate contents (with different identifiers), instead of a single content with different versions. Even if we add a identifier column to the CSV file, not all contents are properly imported. 

## Steps to Reproduce (for bugs)

1. Make the "title" field on Event Content type as Unique. Since this is a system content type, you can do this by running the following Query in the DB and then flushing all caches 

```
update field set unique_ = 't'  where structure_inode = 'f6259cc9-5d78-453e-8167-efd7b72b2e96' and field_name = 'Title';
```
2. Go to Import Contents portlet. Select "Multilingual File" on the "language to import" dropdown and select "Title" as Key field.
3. Import the following CSV file to dotCMS, via Import Contents tool 
```
languageCode,countryCode,host1,title,urlTitle,startDate,endDate,description,link,tags,categories
en,US,48190c8c-42c4-46af-8d1a-0cd5db894797,Event Test 005,event-test-us,01/26/2017 12:00 AM,01/26/2017 11:59 PM,english description,,,
es,ES,48190c8c-42c4-46af-8d1a-0cd5db894797,Event Test 005,Event-test-es,01/26/2017 02:00 AM,01/26/2017 12:00 PM,spanish description,,,  
```
4. Preview page will show this. As you can see, the page indicates that the Line 3 (the one in Spanish Language) is not going to be imported because there is another content with the same title. As stated before, this doesn't prevent the Content Search manager to create multiple versions of the same content and have the same value under an Unique field.

<img width="1478" alt="screen shot 2017-01-26 at 1 11 28 pm" src="https://cloud.githubusercontent.com/assets/1717110/22344155/0cb3b072-e3c9-11e6-9830-7aa1fafe0f56.png">

5. Import the file. Only one version will be created. 
<img width="1493" alt="screen shot 2017-01-26 at 1 15 22 pm" src="https://cloud.githubusercontent.com/assets/1717110/22344276/8d401898-e3c9-11e6-9e6d-d6bbb085ce14.png">

## Context
This also happens if you desire to update existing contents. Only one version will be imported from the CSV file. 
Reported by customer:	https://my.dotcms.com/tickets/detail.dot?id=9b578165-236a-4be6-a094-495741508a67

## Your Environment

* dotCMS version 3.6.0.
* Google Chrome Browser.
* macOS Sierra, centOS 6.
* Tomcat 8.0.18.
* Oracle Java JDK 8, openJDK 8.
* Postgres 9.4.1.

**Comment by wezell** [comment]
We need to change this line to use the `field.getVelocityVar()` method:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/quartz/job/ContentImportThread.java#L661

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12028

**Comment by DeanGonzalez** [comment]
Tested in Postgres.  Had to alter both the sql statement and the .csv file to make them work, but both language versions of the content upload successfully.  I also tried updating existing content the same way and this was also successful.
