### ISSUE TITLE
Unable to add custom tabs 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10542]
We are breaking the system when you add a new custom tab, we are having an error on log 

## Expected Behavior
We need support add custom tabs and add some portlets into it 

## Current Behavior
The system throws an error on log 

LOG: https://gist.github.com/bryanboza/6cdcdde57c2bcb29a15755dd35b4392a

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to System --> Roles & Tabs 
3. Select CMS Administrator and go to tabs 
4.  Create some custom tab
5. Add some portlets 
6. Click to save 

## Your Environment
Tested on mater-4.0 // H2 // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10544

**Comment by fabrizzio-dotCMS** [comment]
tested in master. Portlets can be added.
