### ISSUE TITLE
Unable to push some page to static environment if you rename the page folder 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10547]
We are having problems when you rename the folder that contain any page that you already pushed, this because if you try to push again the page after rename the folder, the system is sending the bundle empty. 

FYI: If you try to push the folder have the same behavior.

## Expected Behavior
Since the pages bundles always are sending forced, we should push again the page and rename the folder 

## Current Behavior
We are sending an empty bundle 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Configure your static publishing environment 
3. Create a new folder and a new page into it 
4. Push the page 
5. In your dotCMS instance rename the folder
6. Try to push the page again 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10551
