### ISSUE TITLE
Missing tags on event content on calendar view

### ISSUE THREAD

**Issue by maurizo** [dotCMS/core#10555]
This is from a [ticket](https://my.dotcms.com/tickets/detail.dot?id=674c6c20-5ac6-47a7-92f0-77a019832767). The event tags are not being displayed on the calendar view or using the view tool unless the content is loaded first using the content management portlet.

## Expected Behavior
Tags should always show on the event view and using the view tool without extra steps.

## Current Behavior
The contentlet management portlet uses the `EditContentletAction._editWebAsset()` [here](https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/action/EditContentletAction.java#L1239) to load the tags and this "puts" tags into the cache.
The calendar portlet and view tool does not have such code.
  
## Possible Solution
The hotfix solution was to add the `setTags()` calls where needed.  A more elegant and probably easier to maintain solution is to have this code called during the final "find" method  on the contentlet API so every contentlet would load it tags upon being retrieved.

## Known Workarounds
As described in the ticket the cache needs to be updated by loading the content on the management portlet.

## Steps to Reproduce (for bugs)
As described on the ticket.

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/10566

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11332

**Comment by shaydotcms** [comment]
Passed QA. Tags are showing in the event view and view tool:

**Event view and view tool**
![image](https://cloud.githubusercontent.com/assets/8741846/25109998/2dd9bb56-239e-11e7-94f7-e866f9a0e0c5.png)

**Front end**:
![image](https://cloud.githubusercontent.com/assets/8741846/25109993/22d1ff5c-239e-11e7-86ee-e69f9995d3a0.png)

Tested on master-4.1 / commit 6caf33e8f8ba46cdf1db336e500969febdee9ee0
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
