### ISSUE TITLE
Static Publishing: Can not resend bundle

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10556]
After a failed or successful push to AWS S3, it is not possible to resend the same bundle when clicking on "Retry Bundle". This error is shown: "No Bundle with id: b83eb109-de83-4fc1-bbea-b1e0139f6156 found".
View attached video.

## Expected Behavior

An user should be able to resend a static push 

## Steps to Reproduce (for bugs)

1. Create a new site
2. Configure a static publishing environment 
3. Try to push the site into the configured enviroment. 
4. Go to Publishing Queue and click on "Retry Bundle". This message is displayed: "No Bundle with id: b83eb109-de83-4fc1-bbea-b1e0139f6156 found"

## Your Environment

* dotCMS version used: 3.7.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (starter)
* Application module (if apply): Publishing Queue

![retry_static_push](https://cloud.githubusercontent.com/assets/8741395/22379796/d57bc78c-e488-11e6-94ba-d38179aa9118.gif)

**Comment by jtesser** [comment]
Yea as @dsilvam pointed out this is mostly because of the change to the bundle name for static. ie... -static

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10568

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/430

**Comment by nollymar** [comment]
Working as expected
