### ISSUE TITLE
Static Publish: Fail to push multilingual content

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10565]
Currently, it is not possible to push static content in an alternative language. The application just considers the default language.

Log details: https://gist.github.com/nollymar/87c796e3f42859dc971c958fd484bbdb

## Expected Behavior

The user should be able to publish in AWS S3 any content with all its languages versions

## Steps to Reproduce (for bugs)

1. Create a new language
2. Create a Page Asset or File Asset for the new language
3. Try to publish in a static environment. 
4. Check dotcms.log. Error details: https://gist.github.com/nollymar/87c796e3f42859dc971c958fd484bbdb

**Note:** when a new content is created in two languages: the default language and an alternative one, the content is pushed, but just one file is saved in the S3 instance

## Your Environment

* dotCMS version used: 3.7.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (starter)
* Application module (if apply): Push Publishing

**Comment by wezell** [comment]
@nollymar what is your bucket/folder pattern?

**Comment by nollymar** [comment]
Firstly, I wasn't considering the hostname/language pattern. But in a second attempt, I considered the suggested one: **dotcms-nolly-bucket-{hostname}-{languageIso}** and it didn't work either.

**Comment by jtesser** [comment]
I think u need to have the page in another language.  Not just content on
it.  This might not be right but test that also

**Comment by dotcmsCodeReview** [comment]
Ahh wait this is urlmap content right

**Comment by jtesser** [comment]
This was working.  Need to debug and see what is up

**Comment by nollymar** [comment]
@jtesser , I created a page version for two languages: English and French. But the logic seems to be considering the default one: https://github.com/dotCMS/enterprise-2.x/blob/42953239dcd3d36673dbb614fb6f51f3a60298a7/src/com/dotcms/enterprise/publishing/staticpublishing/StaticDependencyBundler.java#L119-L119

**Comment by jtesser** [comment]
Yea talking to Daniel about it now

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/431

**Comment by nollymar** [comment]
Now, this error is solved: https://gist.github.com/nollymar/87c796e3f42859dc971c958fd484bbdb. However, after publishing demo site in multiple languages, the site has some problems with css styles.
In the JS Console this message is displayed: Failed to load resource: the server responded with a status of 404 (Not Found) http://nolly-bucket-demo.dotcms.com-en-us.s3-website-us-west-2.amazonaws.com/DOTLESS/application/themes/quest/less/main.css
