### ISSUE TITLE
Static Push: Failed to load css files when publishing multiligual sites

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10573]
After publishing demo site in multiple languages, the site has some problems with css styles.
In the JS Console this message is displayed: Failed to load resource: the server responded with a status of 404 (Not Found) http://nolly-bucket-demo.dotcms.com-en-us.s3-website-us-west-2.amazonaws.com/DOTLESS/application/themes/quest/less/main.css

Looking at the path /DOTLESS/application/themes/quest/less, the main.css file exists only in the French bucket. For Spanish and English's buckets, this path does not exist.

## Current Behavior

demo site is loading without css

## Steps to Reproduce (for bugs)

1. Create content for demo site in Spanish, French and English
2. Configure Static Push environment
3. Create buckets for each language and assign the correct security policy
4. Publish demo site

## Your Environment

* dotCMS version used: 3.7.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (starter)
* Application module (if apply): Push Publishing

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/433

**Comment by nollymar** [comment]
Now, it is working for css, but it is failing for js files

**Comment by agomez-dotcms** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/435

**Comment by agomez-dotcms** [comment]
Hi Guys,

The last issue reported (JS files -related) has been fixed by replicating all file-assets from default-language into all languages configured. This has been discussed and decided as the solution to go for now. A further refinement, might incorporate include/exclude -like configuration properties to filter (by extension) what files are to be replicated.

Thanks,
Anibal

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10587

**Comment by bryanboza** [comment]
Fixed, tested in the last master-3.7 // h2 // Chrome
