### ISSUE TITLE
Merge master-3.7 changes into master-4.0

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10577]
Once 3.7 is released, we need to merge the changes from it and the enterprise repos

**Comment by dsilvam** [comment]
Include this commit as well: https://github.com/dotCMS/core/commit/32fb6741967f6f5e391fb64616cbb4fa83a47906

**Comment by dsilvam** [comment]
Changelog: include the removal of the mapping of SpeedyAssetsServlet2. Please check with @nollymar

**Comment by nollymar** [comment]
SpeedyAssetsServlet2 was removed from the repository. No changelog was needed because this file had not been part of a final release.

**Comment by nollymar** [comment]
Doc that describes the rename/merge process (which is useful for future merges): 
https://docs.google.com/document/d/1w6tXyEiQjm94SM9XEYR2L0dIRg_0XG8vcut4g7lvrYo/edit

Attaching script used for rename in a zip file:

[rename_gradle_layout.zip](https://github.com/dotCMS/core/files/767948/rename_gradle_layout.zip)

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/10715
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/442
PR License: https://github.com/dotCMS/license/pull/42
