### ISSUE TITLE
QA round for devs

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10572]
This ticket will contain the parts of the system we are testing or we need to test in our QA round, and remember the idea is to find issues related with the new UI:

- [ ] Push publish
- [ ] Inline editing
- [ ] Forgot password
- [ ] Time Machine
- [ ] Containers
- [ ] Templates
- [ ] Site Browser
- [ ] HTML Page Edit Mode
- [ ] Rules
- [ ] Dashboard
- [ ] Workflow Tasks
- [ ] Content Types
- [ ] Relationships
- [ ] Tag Manager
- [ ] Workflow Schemes
- [ ] Content Search
- [ ] Calendar
- [ ] Link Checker
- [ ] Link
- [ ] Categories
- [ ] Users
- [ ] Roles & Tabs
- [ ] Sites
- [ ] Maintenance
- [ ] Configuration
- [ ] Languages
- [ ] Query Tool
- [ ] ES Search
- [ ] Site Search
- [ ] Dynamic plugins

**Comment by oswaldogallango** [comment]
In the **Category portlet** is missing a way to go back to the parent when you go down and see the children categories.

In the **Content Search** is missing the button option to export contents.
<img width="1323" alt="screen shot 2017-02-03 at 9 39 06 am" src="https://cloud.githubusercontent.com/assets/1569280/22603225/83294f0e-ea14-11e6-96b1-da8d62b1aee8.png">

Also in the **Content Search** the contents name needs to be separated from the checkboxes
<img width="1325" alt="screen shot 2017-02-03 at 9 34 17 am" src="https://cloud.githubusercontent.com/assets/1569280/22603263/ac13b44a-ea14-11e6-8753-37e4b84525f1.png">

**Comment by oswaldogallango** [comment]
In the **Calendar portlet** when you add an event and tries to add a category the seach box  in the popup is to small for the text size

<img width="1322" alt="screen shot 2017-02-03 at 1 38 37 pm" src="https://cloud.githubusercontent.com/assets/1569280/22603691/590a9a64-ea16-11e6-9207-48296eed8afe.png">

In the user **Users portlet ** on the roles tab. If you click the + to expand the roles under the system. the list of roles is displayed but outside of the textarea

<img width="1325" alt="screen shot 2017-02-03 at 1 44 50 pm" src="https://cloud.githubusercontent.com/assets/1569280/22603964/6f776d3a-ea17-11e6-9982-088f732ec45e.png">

Then under the permission tabs the checkboxes are not under the correspondent value in the next to the site name
<img width="1322" alt="screen shot 2017-02-03 at 1 48 52 pm" src="https://cloud.githubusercontent.com/assets/1569280/22604092/f48ec5fe-ea17-11e6-852f-4e89a721f326.png">

And under the additional info tab. if you click to add an address the inputs are too big for the message area
<img width="1324" alt="screen shot 2017-02-03 at 1 53 47 pm" src="https://cloud.githubusercontent.com/assets/1569280/22604305/e829f602-ea18-11e6-9a0b-fa06256a1965.png">

**Comment by oswaldogallango** [comment]
In the **Roles & Tabs portlet** in the CMS Tabs, the name of portlets that have a dash are cut for some reason. when you add the portlet the names are fine
<img width="1326" alt="screen shot 2017-02-03 at 4 17 10 pm" src="https://cloud.githubusercontent.com/assets/1569280/22608869/ba1c90ee-ea2c-11e6-8e75-747ac039dc06.png">
But after your save and reopen  to edit that tab, those names are being displayed like this
<img width="1326" alt="screen shot 2017-02-03 at 4 21 57 pm" src="https://cloud.githubusercontent.com/assets/1569280/22608977/24732a20-ea2d-11e6-8dcc-b6d244005df7.png">
Seems that something is cutting the name from this "com.dotcms.repackage.javax.portlet.title.site-browser" to this "com.dotcms.repackage.javax.portlet.title.site"

**Comment by oswaldogallango** [comment]
In the **Sites portlet** if you do right click on a site and click the "Edit Site Variable" button. The input for search is too small
<img width="1188" alt="screen shot 2017-02-06 at 8 17 31 am" src="https://cloud.githubusercontent.com/assets/1569280/22648610/7ff049b8-ec45-11e6-8ce2-dc37d932f6c9.png">

and if you click the "Add New Site Variable" button the dialog title is too close to the first input box
<img width="1182" alt="screen shot 2017-02-06 at 8 18 58 am" src="https://cloud.githubusercontent.com/assets/1569280/22648651/ab9656fc-ec45-11e6-927d-b7a6ee614acf.png">

**Comment by oswaldogallango** [comment]
In the **Maintenance portlet** on the Index tab right now only the current working index is showed in green before both the live and working active indexes were displayed in green
<img width="1184" alt="screen shot 2017-02-06 at 9 05 47 am" src="https://cloud.githubusercontent.com/assets/1569280/22650158/ecfdb5d0-ec4b-11e6-8116-7a122a81ca5e.png">

In the log files, if you click the popup button to watch any lg for example the dotcms log the popup is empty. doesn't show anything
<img width="1185" alt="screen shot 2017-02-06 at 9 16 24 am" src="https://cloud.githubusercontent.com/assets/1569280/22650418/2f3cd39e-ec4d-11e6-80db-ef627ba11d61.png">

**Comment by oswaldogallango** [comment]
In the **Configuration portlet** in the license tab. when you add a licence using the zip. the table displaying the licenses values doesn't look fine, all the text is showed to close should be more space between the rows and some color to differentiate each one. Maybe with a similar styling to the one used to display the current license info.
<img width="1184" alt="screen shot 2017-02-06 at 9 27 03 am" src="https://cloud.githubusercontent.com/assets/1569280/22650929/25d9cd96-ec4f-11e6-915b-fd5d7e29fb49.png">

In the "Publishing environment" tab add a publishing environment add a server and click the edit option for that environment. the box is too little and doesn't allow to edit the environment
<img width="1184" alt="screen shot 2017-02-06 at 9 34 24 am" src="https://cloud.githubusercontent.com/assets/1569280/22651118/e7feb0c6-ec4f-11e6-81cf-ae1741dd323d.png">

**Comment by oswaldogallango** [comment]
In the ** Workflow Scheme portlet** if you add a workflow a then you try to edit the workflow clicking the Edit workflow scheme button. the dialog to edit the workflow is not displayed

<img width="1182" alt="screen shot 2017-02-06 at 11 20 50 am" src="https://cloud.githubusercontent.com/assets/1569280/22655728/09b39074-ec5f-11e6-8243-181473f5fd1d.png">
 
Also when in a workflow step, you add some subactions. They are displayed
<img width="1178" alt="screen shot 2017-02-06 at 11 29 01 am" src="https://cloud.githubusercontent.com/assets/1569280/22655926/bc3e7240-ec5f-11e6-9d90-d02d01c936d3.png">

then you click save. The subactions are not displayed. If you cancel and go back to the step the subactions are not displayed.
<img width="1184" alt="screen shot 2017-02-06 at 11 28 40 am" src="https://cloud.githubusercontent.com/assets/1569280/22655991/e530268a-ec5f-11e6-95f4-f446a075c111.png">

but if you add another subaction then the previous ones are displayed
<img width="1183" alt="screen shot 2017-02-06 at 11 28 16 am" src="https://cloud.githubusercontent.com/assets/1569280/22656016/f7ffad9e-ec5f-11e6-965f-3e912ab6cced.png">

**Comment by oswaldogallango** [comment]
In the **Content Type portlet** click the menu button option to check all the relationships. 
<img width="1180" alt="screen shot 2017-02-06 at 11 52 19 am" src="https://cloud.githubusercontent.com/assets/1569280/22656938/cc834e5c-ec62-11e6-8739-b71c3ca1ac48.png">
You are redirected to the view relationships page but the option to return to the view content types is is not there any more
<img width="1187" alt="screen shot 2017-02-06 at 11 47 05 am" src="https://cloud.githubusercontent.com/assets/1569280/22656962/d3b8c684-ec62-11e6-867b-6ee50b1332eb.png">
and if you add a new relationship the inputs fields are too bigs
<img width="1189" alt="screen shot 2017-02-06 at 11 46 18 am" src="https://cloud.githubusercontent.com/assets/1569280/22656991/eaddd750-ec62-11e6-8343-89fb506cf0bd.png">

**Comment by oswaldogallango** [comment]
In the **Workflow Task portlet** in the listing, there are checkboxes but not actions. not sure if the button were deleted by mistake or if we have a reason to have them.
<img width="1185" alt="screen shot 2017-02-06 at 2 47 14 pm" src="https://cloud.githubusercontent.com/assets/1569280/22663726/bc803308-ec7b-11e6-82c5-e1305d1a5c6c.png">

**Comment by oswaldogallango** [comment]
The **Inline editing** is not saving the changes in the content

In the **Site Browser portlet** in the edit mode when you try to add or reuse a content the menu is displayed in the wrong place

<img width="1183" alt="screen shot 2017-02-06 at 3 07 15 pm" src="https://cloud.githubusercontent.com/assets/1569280/22664368/6265f3c8-ec7e-11e6-9420-b88607541653.png">

In the site-browser portlet when you add multiple files the window is hidding part of the buttons
<img width="1181" alt="screen shot 2017-02-06 at 3 18 56 pm" src="https://cloud.githubusercontent.com/assets/1569280/22664727/e8c16960-ec7f-11e6-9be3-b34cc6a4d19e.png">

**Comment by oswaldogallango** [comment]
In the **In the rules portlet** some rules conditionlets and actionlet are not displaying the right option get blanks and freeze the code. If you click other menu portlet is not responding. For example visitor location. Also the portlet is not working in browser like FF and safari

<img width="1184" alt="screen shot 2017-02-06 at 3 28 15 pm" src="https://cloud.githubusercontent.com/assets/1569280/22664973/e9561910-ec80-11e6-8007-4156f73eebb8.png">

**Comment by oswaldogallango** [comment]
In the **Containers portlet** when you add in a container the capability to include  content the teare and the ace editor size change in different sizes
<img width="1183" alt="screen shot 2017-02-06 at 3 58 21 pm" src="https://cloud.githubusercontent.com/assets/1569280/22666175/9c5c4788-ec85-11e6-9ad1-3f2be6a0ed60.png">

**Comment by oswaldogallango** [comment]
In the **Dashboard portlet** if you click any of the view links are the viewing x of x section is displayed cut
<img width="1181" alt="screen shot 2017-02-07 at 10 18 35 am" src="https://cloud.githubusercontent.com/assets/1569280/22697462/81cf2aa8-ed1f-11e6-8c56-ce4d5ba2b1be.png">

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10682

For the following fix:
1) fixed issue displaying maintence> tail log popup
2) Roles and tabs issue with portlet names with dashes
3) Issue displaying subactions in the workflow scheme portlet

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10692

Fixes error trying to show the rules tab. When someone goes to a page and click the edit page properties

**Comment by bryanboza** [comment]
The publish queue needs styling help:

- [ ] We need remove the vertical scroll bar 

- [ ] The delete button need the the style of the delete buttons 

SC: https://screencast.com/t/QX5VLlbPi9w

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10758

Fixes: 
The Inline editing is not saving the changes in the content

**Comment by fmontes** [comment]
- [ ] Main navigation doesn't scroll on small screens: https://cloudup.com/cy8qLdf7DbK

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10765

**Comment by bryanboza** [comment]
Fixed, some new improvements opened in the card #10777
