### ISSUE TITLE
Adding Configurable component to switch between dev or prod mode in Angular

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#10579]
Adding Configurable component to switch between dev or prod mode in Angular

## Expected Behavior

Passing a devMode query string parameter with a value "on", we should be able to switch the app to dev mode. "off" viceversa

## Current Behavior

Current the environment is set at the begin and there is not any chance to change it.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/258

**Comment by bryanboza** [comment]
Passed...
