### ISSUE TITLE
We need to Respect Page Fall Thru when Static Publishing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10583]
Right now we are not getting directories in spanish (secondary language) when a page has spanish content exists, but the page does not have a spanish version.  

This is not correct if this property is set to true:
1) DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true
If this is set to true, then we should be checking to see if there is spanish (secondary language), on the page, if so, then push the spanish version of the page, but if NOT, then still push the page in the DEFAULT LANGUAGE VERSION, - this will create the page and the folder directory.

2) IF THE PAGE IS PUSHED, we should then be checking this property (every time):
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=TRUE
If that property is set to true, then if the spanish (secondary language) of the content on the page exists, push the spanish content, and if it does NOT exist, then we push the DEFAULT LANGUAGE version of the content.

Of course, french, german, whatever language, should work the same way.  I was only using spanish as an example of a secondary language.

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/436
core PR: https://github.com/dotCMS/core/pull/10587

**Comment by oarrietadotcms** [comment]
Friendly reminder to test URL Maps you need to keep an eye on property: DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE. By default is false

**Comment by DeanGonzalez** [comment]
http://auth.dotcms.com/docs/latest/multilingual-static-endpoints

**Comment by erickgonzalez** [comment]
Passed QA.
Created a Spanish version of the 404-error page without any content, and saw this 2 scenarios:

- DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=FALSE and pushed the page--> shows the page blank.
- DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=TRUE and pushed the page--> shows the page with the English content.
