### ISSUE TITLE
Static publishing  error when you try to push some page that no have version in the default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10589]
We are having an error if you try to push some page, and this one does not have version in the default system language

## Expected Behavior
We should be able to support that case 

## Current Behavior
We stop the pushing and fire this exception https://gist.github.com/bryanboza/4c4666bfac5e6a72f4687c89f220768b

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Configure your static pushing environment 
3. Push the entire site
4. Create a new page, but this only in a different language that default 
5. Try to push this page 

## Your Environment
Tested on master-3.7 with the last changes // H2 // Chrome

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/437

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // Chrome
