### ISSUE TITLE
Shorty unneeded collision warning

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10592]
When writing shorties, we were trying to find the right pattern to make sure there were no collisions and one way to test was to see if there was another exact shorty in the cache already.  Turns out, this causes unnecessary logging that can be triggered by a race condition.  And regardless, the real anti-collision code was moved to the db lookup anyway.

Another recommendation would be to put shorties on disk by default as well as they are called for every hard asset lookup

**Comment by dsilvam** [comment]
Pr: https://github.com/dotCMS/core/pull/10593
