### ISSUE TITLE
JGroups repackage is missing repackaged things

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10597]
## Expected Behavior
Be able to add a new JGroups jar to dotCMS

## Current Behavior
When you add it makes the cluster fail

## Steps to Reproduce (for bugs)
1. add a new Jgroups jar to dotcms in a plugin
2. run dotcms in a cluster with step 1 on both servers
3. the cluster will fail to come up (jgroups xml files are failing.  Dups :-( )

**Comment by wezell** [comment]
Hazelcast
