### ISSUE TITLE
Need validate the fields are not null when  you try to import content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10598]
We need validate from UI, this to avoid some errors 

SC: https://www.screencast.com/t/qR8eUrMz7ZO

## Expected Behavior
Need show some message and validate the field is not null

## Current Behavior
We try to import the content and shows an error 

Here the log: https://gist.github.com/bryanboza/8f6241d70bcd09c4bfe9fb021e75d730

## Steps to Reproduce (for bugs)
1. Login
2. Go to content search 
3. Try to import content 
4. Click to "Go to preview" button 

## Your Environment
Tested on master-4.0 // H2 // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10606

**Comment by bryanboza** [comment]
Ok , now we are showing the error if you leave the field in blank, that's the main problem.

But maybe the UI should be more intelligent, we should validate the field before call the servlet, because right now we call the servlet and show the message with the servlet error... Then we have this exception on log https://gist.github.com/bryanboza/e7ffa11c73cbcb914aee9e1c2b250746
