### ISSUE TITLE
"Force Push" option does not work with Bundles

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#10601]
If you create a Bundle, and push it from the `Bundles` tab (in the `Publishing Queue`) with the `Force Push` option selected, the bundle is not actually force pushed.

## Expected Behavior
When you push publish a bundle and select `Force Push`, each item in the bundle should be force pushed.

## Current Behavior
When you push a bundle and check the `Force Push` option, it doesn't actually force push any items in the bundle.

## Known Workarounds
Force Push each content item individually.

## Steps to Reproduce (for bugs)
1. Push 2 individual content items to a push Environment, and wait for the push to finish.
2. On the receiving server, archive both items that were pushed in step 1.
3. Create a bundle by adding both items from step 1 to the same bundle (e.g. select `Add to Bundle` for both items, putting them in the same bundle).
4. Open the `Publishing Queue`.
5. Select the `Bundles` tab.
6. Click the `Push Publish` button for the bundle created in step 1.
7. In the `Remote Publish Bundle` popup, check the `Force Push` option.
8. Click the `Push` button to push the bundle.
9. View the bundle in the `Pending` tab.
    * **Result:** The bundle shows `Force Push: false`.
10. Wait for the bundle to push to the Endpoint, and then check both content items on the Endpoint.
    * **Result:** Both items are still archived (meaning neither item was actually force pushed).

## Context
This is a significant bug, but the workaround is reasonable in most cases.

## Your Environment
* dotCMS version used: 3.7.0
    * Note: JT reported that this also exists on 3.6.2, but I wasn't able to try it (because I was unable to create a bundle with the individual content items on 3.6.2 - possibly a problem with the 3.6.2 starter for the content items I was working with).
* Browser Name and version: Chrome
* Operating System and version: Win7
* Application Server and version: distro
* Java Brand and version: 8.0 (111)
* Database and version: distro
* Application module (if apply):

**Comment by shaydotcms** [comment]
Unable to reproduce issue.
Bundle is sent successfully when "Force Push" option is checked
<img width="300" alt="4d4a0497-db85-4f6f-82c7-7a3d2f1830c6" src="https://user-images.githubusercontent.com/8741846/26851895-8ee08f04-4ac9-11e7-908a-06f027efcab0.png">



Tested with upgrade from dotcms_3.3 with client dataset (db and assets) to master branch / commit 7187688c9a1f58906abdc6d76ddc57dd9c90d705
Both sender and receiver were upgrade and configured using:
Ubuntu 14.04.1 / Postgres 9.3.5 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
Logs for both sender and receiver: https://gist.github.com/shaydotcms/c562dd74c47433796bd016b42b393b31
