### ISSUE TITLE
Multiple AWSS3 Endpoints will not transfer concurrently

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#10603]
See the loop here. https://github.com/dotCMS/enterprise-2.x/blob/8ebc3c2bc3f65fe482b5468be24fe8d227ae16de/src/com/dotcms/enterprise/publishing/staticpublishing/AWSS3Publisher.java#L156

We push to one endpoint then the next etc... 

I think we want to add a thread here to fire the logic in the loop of the endpoint so we can transfer currently to all S3 Endpoints

**Comment by wezell** [comment]
Let's hold on this
