### ISSUE TITLE
Links: External link is updated if its URL value matches a Site that was recently updated.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10609]
Once a Site gets its name updated, it makes a batch update  of Menu Links, so if there's a Menu Link pointing to a URL from this recently updated site, it will be automatically updated and it will include the updated site name on its URL.

## Expected Behavior
The update must be executed for Internal Links only. An internal link is just a resource that will point to an existing asset on the same or a different site. 

## Current Behavior
The update process makes a batch update of ALL Menu Links and their versions where an occurrence of Site Names is found. This will overwrite data for External links, which might match this rule under specific scenarios, breaking its functionality and requiring additional human intervention for restoring original values. 

## Possible Solution
Update only Internal Links if the Site name has been changed. 

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Clone demo.dotcms.com site. For testing purposes, let's call it "cloned.dotcms.com".
2. On demo.dotcms.com/about-us/ folder, create a Link called "Site B". This one must be:
    - An internal link.
    - Point anything from the cloned.dotcms.com site.
3. Open the recently created link and change it to "external". Don't change anything else from the Link object and Save/Publish it.
4. Go to Sites portlet and open cloned.dotcms.com site. Edit its name to "old-cloned.dotcms.com" site. Save/Publish it.
5. Go back to demo.dotcms.com/about-us/ folder and open the Link. The URL value now points to old-clone.dotcms.com, despite it's an external resource according to the Link definition. 

Data: 

- Link was created, pointing to Internal Page from a different Site: 

```
dotcms361=# select * from links where title = 'Site B';
                inode                 | show_on_menu | title  |        mod_date         |   mod_user   | sort_order | friendly_name |              identifier              | protocal |               url                | target |       internal_link_identifier       | link_type | link_code
--------------------------------------+--------------+--------+-------------------------+--------------+------------+---------------+--------------------------------------+----------+----------------------------------+--------+--------------------------------------+-----------+-----------
 8058eda5-4cb5-475c-a01a-a0eb1cb69365 | t            | Site B | 2017-02-01 14:39:25.219 | dotcms.org.1 |          0 |               | 0e031718-5322-42bb-911c-f1df7cd4b058 | http://  | cloned.dotcms.com/about-us/index | _self  | 497eb4c4-d537-4890-9647-515e66057c72 | INTERNAL  |
(1 row)
```

- Link was updated, now pointing to an External resource (Live version is the EXTERNAL one): 

```
dotcms361=# select * from links where title = 'Site B';
                inode                 | show_on_menu | title  |        mod_date         |   mod_user   | sort_order | friendly_name |              identifier              | protocal |               url                | target |       internal_link_identifier       | link_type | link_code
--------------------------------------+--------------+--------+-------------------------+--------------+------------+---------------+--------------------------------------+----------+----------------------------------+--------+--------------------------------------+-----------+-----------
 8058eda5-4cb5-475c-a01a-a0eb1cb69365 | t            | Site B | 2017-02-01 14:39:25.219 | dotcms.org.1 |          0 |               | 0e031718-5322-42bb-911c-f1df7cd4b058 | http://  | cloned.dotcms.com/about-us/index | _self  | 497eb4c4-d537-4890-9647-515e66057c72 | INTERNAL  |
 b0093e7a-0065-43d8-9e38-21fd07b4696b | t            | Site B | 2017-02-01 14:40:35.352 | dotcms.org.1 |          0 |               | 0e031718-5322-42bb-911c-f1df7cd4b058 | http://  | cloned.dotcms.com/about-us/index | _self  |                                      | EXTERNAL  |
```

- Link and all of its versions are updated once the Site name has been changed. Live version is the EXTERNAL one: 

```
dotcms361=# select * from links where title = 'Site B';
                inode                 | show_on_menu | title  |        mod_date         | mod_user | sort_order | friendly_name |              identifier              | protocal |                 url                  | target |       internal_link_identifier       | link_type | link_code
--------------------------------------+--------------+--------+-------------------------+----------+------------+---------------+--------------------------------------+----------+--------------------------------------+--------+--------------------------------------+-----------+-----------
 8058eda5-4cb5-475c-a01a-a0eb1cb69365 | t            | Site B | 2017-02-01 14:42:42.575 | system   |          0 |               | 0e031718-5322-42bb-911c-f1df7cd4b058 | http://  | old-cloned.dotcms.com/about-us/index | _self  | 497eb4c4-d537-4890-9647-515e66057c72 | INTERNAL  |
 b0093e7a-0065-43d8-9e38-21fd07b4696b | t            | Site B | 2017-02-01 14:42:42.578 | system   |          0 |               | 0e031718-5322-42bb-911c-f1df7cd4b058 | http://  | old-cloned.dotcms.com/about-us/index | _self  |                                      | EXTERNAL  |
```

## Screenshot of Add/Edit Link after the Site Name was updated: 
<img width="1372" alt="screen shot 2017-02-01 at 2 42 57 pm" src="https://cloud.githubusercontent.com/assets/1717110/22523430/6c9ccd84-e88d-11e6-9423-3d7ea9aa9517.png">

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=dfafb89e-d03d-455d-9a52-8aa889329613 

As stated before, the automatic process of updating Menu Links should update Internal Links only, and apply the fix only for the current live/working version of these Links. It's SHOULD not  overwrite old versions' data.

## Your Environment
* dotCMS 3.6.1, 3.7.0.
* Google Chrome Browser.
* macOS Sierra 10.12.3.
* Tomcat 8.0.18.
* Java 8.
* Postgres 9.4.1

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10910

**Comment by nollymar** [comment]
After some tests, the feature is working as expected. However, there is a specific case where the URL of an internal link is not being updated:
- Create an internal link
- Edit it and change it to External
- Modify the site name
- Edit the link again and bring back the original version (the internal link)
- Modify the site name again
- The restored internal link is not updated with the new site URL

According to a conversation with @oarrietadotcms , this case is not being considered in the implementation, so in case we want to fix it, the logic should be modified.
