### ISSUE TITLE
Website Browser: Show full page/file name when mouse hovers the asset title

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10604]
On Website Browser, depending on the file/page name's length, this piece of string may be shorten to 30 characters, including 3 dots at the end of the shortened string. For environments where multiple files have been uploaded to a site/folder, we could have a scenario where the shortened string may look the same for all files, so it's difficult so see which asset an user needs access to unless the user:

- Right click -> edit the asset.
- Double click -> see the whole file name on a field he/she can edit.

## Expected Behavior
Hovering the mouse on the actual file/page name should have the same behavior that the "alt" attrib on an IMG html tag has: show the file name for an easy read of the asset in question.

## Current Behavior
There is no way to see the whole file/page name unless the file is opened.

## Steps to Reproduce (for bugs)

1. Login to demo.dotcms.com
2. On Website Browser, go to /resources/res-documents folder.
3. Download the photoshop-keyboard-shortcuts.pdf file and make several copies of it.
    - photoshop-keyboard-shortcuts-001.pdf
    - photoshop-keyboard-shortcuts-002.pdf
    - photoshop-keyboard-shortcuts-003.pdf
4. Upload all new files under the same folder. 

Screenshot: 
<img width="1372" alt="screen shot 2017-02-01 at 12 15 59 pm" src="https://cloud.githubusercontent.com/assets/1717110/22518199/c49c532e-e879-11e6-8116-87f2653f2b4e.png">

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=f2fbfb96-b3ec-42a0-b49a-02be555c4de0

## Your Environment

* dotCMS 3.6.2, master-4.0
* Google Chrome Browser
* macOS Sierra 10.12.3
* Tomcat 8.0.18.
* Java 8.
* Postgres 9.4.1.

**Comment by mattyarbrough** [comment]
This continues to be an issue for customers in current release.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/13490
