### ISSUE TITLE
Core 4.0 not building in Eclipse 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10612]
Might be my setup but regardless these UPS shipping helper classes/imports are antique and are not required.

**Comment by jdotcms** [comment]
Not sure about eclipse, but I guess it is similar to idea and you have to active a plugin to support gradle auto dependency.

**Comment by wezell** [comment]
That wasn't the issue - the issue was that my JDK didn't provide `javafx` or `com.sun.net.ssl.internal.ssl.Provider()`

Neither of which we need
