### ISSUE TITLE
Edit mode nests when browsing the site

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10616]
Open a page in edit mode and try to browse around.

![screen shot 2017-02-02 at 9 30 05 am](https://cloud.githubusercontent.com/assets/934364/22553310/40f6eb54-e92a-11e6-8fc4-16f8ed5877b9.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10624

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // Chrome
