### ISSUE TITLE
websocket issues

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10617]
Websockets need to fall back if the protocol is not supported.

This will require work on the client and the server.

![screen shot 2017-02-02 at 10 07 46 am](https://cloud.githubusercontent.com/assets/934364/22554809/8415e700-e92f-11e6-8ca8-ba40aa1bb82e.png)

**Comment by dotcmsCodeReview** [comment]
Didn't we just have a commit or issue on this

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10663

**Comment by bryanboza** [comment]
Error after refresh the browser https://screencast.com/t/sKmlP53v

**Comment by bryanboza** [comment]
This fix is breaking the events, now we have problems receiving notifications...

**Comment by bryanboza** [comment]
We are modifying this code with the card: #10807

**Comment by DeanGonzalez** [comment]
documented: http://auth.dotcms.com/docs/latest/system-events#Websockets (see long polling config)
