### ISSUE TITLE
UI Punchlist vol. 1

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10629]
- [x] Site Browser - make font bigger

- [x] System> Maintenance 
All active indexes need to be green and building indexes orange - it looks like only alternating rows are colored (https://github.com/dotCMS/core/commit/96905ca0e21bee04726b1f9eb41a465b798a44ef)
![screen shot 2017-02-03 at 12 16 35 pm](https://cloud.githubusercontent.com/assets/934364/22601004/05b425b6-ea0b-11e6-8204-479413a3fcd5.png)

- [x] Edit Content Screen (https://github.com/dotCMS/core/commit/1eee676d8a36c2f0cb433ce0860ebbbfe2f40127)
1. WYSIWYG (max-width of 900px or 100% whichever is less) X (650px)  
2. Text boxes should have max-width of 900px or 100% whichever is less
3. switching to plain text and then back to wysiwyg is broken
4. ~~Image editor not visible, you have to scroll up and it does weird things - try editing an image on a "News" item~~ (There is an issue for this: https://github.com/dotCMS/core/issues/10640)
5. Category picker messed up.  make font/dialog bigger if possible
- [x] Marketing > Rules Screen still change the default style (https://github.com/dotCMS/core-web/pull/266/commits/ba07640cc5d7e6f9a8d0affc594bfabb2d1df74e)

- [ ] ~~System > Configuration > License~~ (fixed on https://github.com/dotCMS/core/issues/10457)
1. Request a license/current custome buttons need to be updated
2. hit current customers - the Cluster Licenses table is wonky
![screen shot 2017-02-03 at 12 24 42 pm](https://cloud.githubusercontent.com/assets/934364/22601183/c464611a-ea0b-11e6-8419-145166080219.png)

- [x] User Roles look funky and don't load until you resize your browser - same with the roles screen **(fixed on another task image editor dialog issue)**
![screen shot 2017-02-09 at 3 58 45 pm](https://cloud.githubusercontent.com/assets/934364/22802951/d9d2a35c-eee0-11e6-946f-2d25d023541a.png)

- [x] Content Search Screen wraps text under the checkbox (https://github.com/dotCMS/core/commit/f6b0ddfa86c5bc13c1eb8b2fa5769ebe4c3ff5c0)
![screen shot 2017-02-09 at 4 03 37 pm](https://cloud.githubusercontent.com/assets/934364/22803065/65093198-eee1-11e6-89cb-2ca662c34c49.png)

**Push publish**
- [x] The view conflicts button need styling help: https://screencast.com/t/20DQynT2 (https://github.com/dotCMS/core/pull/10713/commits/8ad42aaddd1c6ef2f7bb6a3d3486dc6370e83c50)
- [x] The close button of the conflicts windows need flat style: https://screencast.com/t/5k9Om7Gzx4j (https://github.com/dotCMS/core/pull/10713/commits/8ad42aaddd1c6ef2f7bb6a3d3486dc6370e83c50)

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // Edge

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10987
