### ISSUE TITLE
Push Publish "Receive From" dialog broken

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10628]
When you are not using a Platform level license the dialog is broken.

![brokendialognotplatform](https://cloud.githubusercontent.com/assets/8225685/22600024/770c013c-e9fe-11e6-8966-708a9920295f.png)

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10637

**Comment by shaydotcms** [comment]
Passed QA.
"Receive From" dialog is showing the usual fields using non-platform license

![image](https://cloud.githubusercontent.com/assets/8741846/22609515/1e4c7f76-ea27-11e6-80d2-a89097a1e6e1.png)
Tested on upgrade using 3.6 client db to latest master-4.1
Mac OS 10.10 / Postgres 9.3.5

**Comment by shaydotcms** [comment]
Passed QA.
When license is not Platform, "Receive from" dialog now is showing the right options to configure push publish
![image](https://cloud.githubusercontent.com/assets/8741846/22654884/da11481c-ec53-11e6-9188-7a940474bfd0.png)

![image](https://cloud.githubusercontent.com/assets/8741846/22655798/e5b95828-ec56-11e6-8123-3b8671f52df4.png)

Tested in latest master-3.7 // MySQL 5.6.23, Postgres 9.3
