### ISSUE TITLE
Image editor needs to work

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#10640]
```image_tool.jsp``` it's a completely different file that we need to style:

- try the new dojo theme - if it looks bad or will need a lot of work, forget it and roll back to the old one.
- Make sure everything works.

**Comment by wezell** [comment]
Guys, let not spend too much time here.  Try the new look and if it works, great.  If not, I don't want to spend more than a few hours and we can leave this one and work on others.  I don't want to spend a week styling this and am ok launching with it with the old look.

**Comment by wezell** [comment]
That said, it is broken if you have to scroll down to the image, which we need to fix - it is on my punchlist

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10722

**Comment by bryanboza** [comment]
Fixed, now is usable
