### ISSUE TITLE
Unable to delete some fields in content types

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10641]
You cannot delete some fields (such as text, textarea, image or file) in new or existing content types. UI states that "The file is being deleted..." however it's not happening and there are errors in logs:
https://gist.github.com/shaydotcms/a37d82ff11747569ee3e7ec5d9f94b4a

## Expected Behavior
You should be able to delete fields on new or existing content types

## Current Behavior
Some fields such as text, textarea, image or file cannot be deleted from new or existing content types.

## Steps to Reproduce (for bugs)
1. Login to dotcms.com
2. Navigate to Content Types
3. Add a new field (such as text, textarea, image or file) to an existing or a new content type 
4. Try to delete that field
5. You will see the error described above

## Your Environment
- dotCMS version used: Latest master_4.1
- Database and version: Postgres 9.3.5
- Operating System and version: Mac OS 10.10.5
- Browser Name and version: Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by wezell** [comment]
We need to talk about this one.

**Comment by oarrietadotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/10728

Note that I also renamed several APIs, to avoid using "2" as part of the name, also Api -> API as standard.

**Comment by nollymar** [comment]
Test results: Successful
