### ISSUE TITLE
Improve bucket region logic

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10642]
- [x] If user provides bucket region property we use that one, unless is us-east-1.
- [x] If user does not provide bucket region property (or value is us-east-1) we need to create bucket without region.

**Comment by oarrietadotcms** [comment]
ee branch: issue-10642-region

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/441

**Comment by john-thomas-dotcms** [comment]
http://auth.dotcms.com/docs/latest/connecting-remote-servers#AWSS3Region

**Comment by oarrietadotcms** [comment]
@shaydotcms I just realized that I didn't generate the ee jar with the latest code. It is ready now.

**Comment by shaydotcms** [comment]
Passed QA.
- [x] "US Standard" region is created when the site is pushed without bucket region
- [x] "US Standard" region is created when region is us-east-1
- [x] Successfully pushed the same shit using different bucket regions, i.e.: us-west-2 / ap-northeast-2 / ap-southeast-1 / eu-central-1
- [x] Successfully pushed 2 individual sites using different bucket regions, i.e.:
demo.dotcms.com —> eu-central-1
copy of demo —> ap-southeast-1
- [x] Successfully pushed site through bundle
