### ISSUE TITLE
Receive notification problems  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10650]
We still having some problems with the notifications, this when you have multiple notifications or more that one at the same time 

## Expected Behavior
We should receive all the notifications without problems 

## Current Behavior
When you have more that one notification at the same time, the system some times receive just one, and then after you logout and login again receive all the other ones 

SC: https://screencast.com/t/iJiajOSw2

## Steps to Reproduce (for bugs)
1. Login 
2. Go to content types 
3. Delete multiple fields at the same time (you should receive 2 notification by field)
4. Delete all the notifications 
5. Logout and login again 

## Your Environment
Tested on master-4.0 // H2 // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10671

**Comment by bryanboza** [comment]
Unable to reproduce in the last master-4.0
