### ISSUE TITLE
Unable to upgrade to 4.0 in Oracle

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#10654]
Expected Behavior

When upgrading from a previous dotcms version, the upgrade must be successful.

Current Behavior

When upgrading from Oracle is throwing a Fatal Error. Upgrade Tasks we need to review:

https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03735UpdatePortletsIds.java#L40

Possible Solution

Remove "; " of each statement, when using dotconnect the "; " is not needed.

Steps to Reproduce (for bugs)

Start an instance of dotcms 3.6.0 (was able to reproduce with starter and client's data)
Stop the instance.
Upgrade the instance to 4.0
Check the logs.
Your Environment

Browser Name and version: FF
Operating System and version: Windows 7
Database and version: Oracle 11g

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10655

**Comment by nollymar** [comment]
Test results: OK
