### ISSUE TITLE
Need change the related content flags to use the same ones that in content search 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10667]
We use this flags when you are adding related content, this to know the language content and if is published or not. 
SC: https://cloudup.com/cKUJwUEpzcK

## Expected Behavior
By consistency we need use the same ones that we use in content search and add the status column

## Current Behavior
We use the flag with some border in different color 

## Your Environment
Tested on master-4.0 // H2 // Chrome

**Comment by wezell** [comment]
New UI can address
