### ISSUE TITLE
ElasticSearch exceptions in dotcms.log file when Log4J is set in DEBUG mode

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#10665]
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=a54e2bf2-f2c4-474a-8961-4a5748464823

When starting up dotCMS and setting the ElasticSearch logging level to DEBUG, some Java exceptions are thrown in the dotcms.log file. Even though the system continues to work as expected, those stack traces shouldn't be displayed and should be investigated.

One of the stack traces is caused by a missing .JAR file. This is not making ES fail in any way. More details provided in this document: https://drive.google.com/open?id=1UG8lXI5gpiL1F6nDCnQIMlqafJg7oxs5-hjpqT-ggDI

## Expected Behavior
The system should not report the Java exceptions when enabling the DEBUG level.

## Current Behavior
Stack traces show up when the logging level is set to DEBUG.

## Possible Solution
For the second stack trace, a solution is explained in this document (adding and repackaging the .JAR file): https://drive.google.com/open?id=1UG8lXI5gpiL1F6nDCnQIMlqafJg7oxs5-hjpqT-ggDI

## Known Workarounds
N/A

## Steps to Reproduce
1. Set the logging level of ES classes to DEBUG.
2. Start your dotCMS instance and check the dotcms.log file.

## Your Environment
* dotCMS version used: 3.3.2
* Browser Name and version: Any
* Operating System and version: Any
* Application Server and version: WebLogic
* Java Brand and version: Java 8
* Database and version: Any

**Comment by joseorsini** [comment]
Related to: https://github.com/dotCMS/core/issues/8436
