### ISSUE TITLE
Main navigation needs selected portlet highlight

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10660]
We need highlight the selected portlet in the menu, this to know in where you are located. 

## Expected Behavior
As in the old UI we need some thing different from the others portlets in the menu  
SC: https://screencast.com/t/kSXjYP7t2ggL

## Current Behavior
You don't know in which portlet you are, the menu just show the list and nothing different when you select some one 

## Your Environment
Tested on master-4.0

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/272

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
