### ISSUE TITLE
Rules: Conditions are not fired for URL Mapped Contents

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10672]
We currently allow rules to be assigned directly to pages, and in Rules portlet, we allow creating rules for specific frontend behavior, like current URL or visited pages. 

## Expected Behavior
Since URL-Mapped contents are not exactly pages, rules could be triggered for specific URL-Map Patterns/Contents so the visitor can have a custom behavior in frontend pages once one of these contents are visited, in the same way it would work for regular pages. 

## Current Behavior
Rules are not triggered if the Visited URL or the current URL is a URL Mapped Content. nothing on the URLMapFilter class handles potential rules applied to these contents.

## Possible Solution
Validate potential rules for the current URL Mapped content in case there is a match with actual contents.

## Known Workarounds
Use the Request Attribute and `javax.servlet.forward.request_uri` in your condition - see below

## Steps to Reproduce
1. On demo.dotcms.com site, Go to Content Type -> Blogs.
2. Make sure that the Detail Page is /blogs/blog-detail page. Save the Content Type.
3. On Website Browser, edit the /blogs/blog-detail page. Add the following rule: 
    - Fire on Every page.
    - Set Condition: Current URL contains `/blogs/blog-detail`
    - Action: Set "Wealthy Prospector" Persona.
4. Go to Rules Portlet. Add two rules.
    - Rule 1 Condition: Current URL contains `/blogs/index`
    - Rule 1 Action: Set "Retiree" Persona.
    - Rule 2 Condition:  Current URL contains `/blogs/bill-ackman-s-top-stock-picks`
    - Rule 2 Action: Set "First Time Investor" Persona.
5. On a different Browser, go to the following pages: 
    - /blogs/index: Rule is fired. Retiree is set as persona.
    - /blogs/bill-ackman-s-top-stock-picks: Rule is not fired. Retiree is still set as persona.
    - /blogs/blog-detail: Rule is not fired. Retiree is still set as persona.

## Screenshots: 

- Rule set on /blogs/blog-detail page: 

<img width="1448" alt="screen shot 2017-02-09 at 10 07 47 am" src="https://cloud.githubusercontent.com/assets/1717110/22789707/e4035a1c-eeb1-11e6-8473-61f092f7746c.png">

- Rules set on Rules portlet:

<img width="1468" alt="screen shot 2017-02-09 at 9 50 51 am" src="https://cloud.githubusercontent.com/assets/1717110/22789721/f1803412-eeb1-11e6-92ae-d150d4b4788a.png">

- /blogs/index page, with right Persona after the rule is fired: 

<img width="1441" alt="screen shot 2017-02-09 at 10 06 41 am" src="https://cloud.githubusercontent.com/assets/1717110/22789724/f94f38a0-eeb1-11e6-84e1-05bc939b159e.png">

- /blogs/blog-detail page, with wrong Persona because rule is not fired:

<img width="1439" alt="screen shot 2017-02-09 at 10 21 21 am" src="https://cloud.githubusercontent.com/assets/1717110/22789764/141f57be-eeb2-11e6-9f46-19c84800ee63.png">

- /blogs/bill-ackman-s-top-stock-picks page, with wrong persona because rule is not fired:

<img width="1445" alt="screen shot 2017-02-09 at 10 06 55 am" src="https://cloud.githubusercontent.com/assets/1717110/22789778/22221f2c-eeb2-11e6-9ef0-f88168217c74.png">

## Context
Since most contents delivered on a Frontend page could be the result of a URL-Mapped Pattern tied to a Content type, it would be good to support this case and allow specific frontend behavior once these contents are visited. 

Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=50ae4079-4ce6-4956-a480-84a0a62431d4

## Your Environment
* dotCMS 3.5.1, 3.7.0.
* Google Chrome Browser.
* macOS Sierra 10.12.3.
* Tomcat 8.0.18.
* Java 8.
* Postgres 9.4.1.

**Comment by wezell** [comment]
There is a workaround:

`javax.servlet.forward.request_uri`

![screen shot 2017-02-09 at 12 28 52 pm](https://cloud.githubusercontent.com/assets/934364/22795098/6783ddba-eec3-11e6-9f0b-07acc068b191.png)

**Comment by joseorsini** [comment]
Thanks, @wezell !

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16316

**Comment by dsilvam** [comment]
Passed Internal QA: URL Mapped Contents firing rules.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
