### ISSUE TITLE
Categories UI problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10676]
Here some problems the we have in categories portlet 

- [x] When you select multiple categories the dialog looks cut: https://screencast.com/t/7uOBXVWIF
- [ ] ~~We are loosing the add to bundle button on this portlet: https://screencast.com/t/7uOBXVWIF~~ (it's an enterprise feature and it's there: https://cloudup.com/cdpR6VQfELh)
- [x] Need add the crum trail on this portlet: https://screencast.com/t/phYs5GJjlQoY
- [x] Need limit the keywords to avoid break the UI: https://screencast.com/t/w8RRaKad
- [x] The variable id need styling: https://screencast.com/t/7SFsGpYEx
- [ ] ~~When you add a category field in any structure, this window need styling help: https://screencast.com/t/NAURv97fJh5~~ (fixed on: https://github.com/dotCMS/core/issues/10629)

- [x] Problems when you click in any column: https://screencast.com/t/KuFNpjTk
- [x] Problems when you try to use the reorder button
**This 2 problems are backend related: 
Request blank: http://localhost:8080/categoriesServlet?start=0&count=10&sort=category_name
Request good: http://localhost:8080/categoriesServlet?start=0&count=10&**

Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10694

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // Chrome.... Some new enhancements reported on #10707
