### ISSUE TITLE
Improvement to Shorty ID for associated files

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10675]
In dotCMS 3.7 if you add an IMAGE field called "screenshot" to the news content, then add the following code to the news detail page, the shorty URL works just fine for both the Binary and the Image field:
Screenshot Image field shortyURL: $!{news.screenshot.shortyUrl} - works<br>
Binary field shortyURL: $!{news.image.shortyUrl} -works <br>

However, it would also be very useful is we could just get the shorty ID of the associated file in the following way:

Screenshot shorty: $!{news.screenshot.shorty}<br>
Binary shorty: $!{news.image.shorty}<br>

These two statements should return only the shortyID of the associated files.

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10686

To reproduce I added this code to: /application/vtl/pages/news/news-detail.vtl

Screenshot: $!{URLMapContent.screenshot.shortyUrl} <br>
Image: $!{URLMapContent.image.shortyUrl} <br>
Screenshot: $!{URLMapContent.screenshot.shorty} <br>
Image: $!{URLMapContent.image.shorty} <br>

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/displaying-content-with-binary-image-fields
