### ISSUE TITLE
Site or Folder is not kept when Creating a Content Type

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#10679]
## Expected Behavior
When you create a content type and replace the field Site or Folder, the new value should be saved.

## Current Behavior
If you create a Content Type and you change the Site or Folder field, it's saved as "System Host" regardless the value you selected.

## Steps to Reproduce (for bugs)
1. Create a Content Type
2. In the field Site or Folder select a folder (e.g demos)
3. Save the Content Type
4. Click over Content Type portlet
5. Click over the created Content Type
6. Go to Properties Tab
7. The value of the Site or Folder field is now System Host

## Your Environment
* dotCMS version used: master-4.1
* Browser Name and version: FF
* Operating System and version: MacOS
* Database and version: Postgres

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10689

**Comment by nollymar** [comment]
Tests results: Successful
