### ISSUE TITLE
Reports portlet need styling help 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10688]
Whgen you add a new tab and add the report portlet, this need styling help with the new NG2 UI

## Expected Behavior
We should fix some details 

## Current Behavior

- [ ] The top tab looks different to the other portlets: https://screencast.com/t/nZ3iyCnmiev
- [ ] After create a new report we are missing some icons: https://screencast.com/t/cv1RaKGW
- [ ] When you edit the report the cancel button needs flat style: https://screencast.com/t/0yyRByWy
- [ ] When you try to open the report we are having problems: https://screencast.com/t/1DTRTrjh

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to Roles && Tabs
3. Add a new tab
4. Add the Report portlet 
5. Open this portlet and add a new report

## Your Environment
Tested on master-4.0 // H2 // Chrome

**Comment by wezell** [comment]
Very low priority.
