### ISSUE TITLE
Unable to open logs in the pop-up

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10681]
We are having errors when you try to open any log in a pop-up window 

## Expected Behavior
We should be able to see the log on this window 

## Current Behavior
We are having a exception in log: https://gist.github.com/bryanboza/c687c67aa75b208d6ada5097ee8a7d2d

## Steps to Reproduce (for bugs)
1. Login 
2. Go to System >> Maintenance >> Log Files 
3. Select the dotcms.log 
4. Click in the pop-up button 

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/10572
PR: https://github.com/dotCMS/core/pull/10682

**Comment by bryanboza** [comment]
Fixed...
