### ISSUE TITLE
Microsoft Edge UI problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10693]
We are having some UI problems in Microsoft Edge 

## Expected Behavior
We should support Microsoft Edge without problems 

## Current Behavior

- [ ] ~~Problems open some event to edit~~ 
- [ ] When you click to any portlet the loading indicator isn't closing automatically, you need click the iframe to close **(Waiting for Gamba because it's not happening to Montes)**
- [x] Loading indicator it's showing vertical and horizontal scroll. (https://github.com/dotCMS/core-web/commit/5cea8a3d88da73826e1e75a764d435d6c85a9a7e)
- [x] Null message in the login window, after logout (https://github.com/dotCMS/core-web/commit/4f3b706a96a6d9eece2b1391f7c1aacc12c5bccb)

## Your Environment
Tested on master-4.0 // H2 // Edge

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/271

**Comment by bryanboza** [comment]
Still having the loading indicator problem

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/280

**Comment by bryanboza** [comment]
Fixed, new problems on #10778
