### ISSUE TITLE
Unable to see past time machine snapshot in Edge

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10691]
We are having problems trying to open a past time machine snapshot

## Expected Behavior
We should open the snapshot without problems

## Current Behavior
When you try  to open, the browser is trying to download some file. 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Time Machine 
3. Crete a past time machine snapshot 
4. Try to open the snapshot 

## Your Environment
Tested on master-4.0 // H2 // Edge

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10803

**Comment by bryanboza** [comment]
Still having the same problem when you try to navigate in the snapshot https://www.screencast.com/t/iC7le9M8

**Comment by jcastro-dotcms** [comment]
Fixed.

PR: https://github.com/dotCMS/core/pull/10931

**Comment by bryanboza** [comment]
Fixed, now we can see the snapshots without problems in Edge
