### ISSUE TITLE
Multiple notifications when you delete some user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10695]
We are generating 20 notifications every time you delete some user.

We should generate just one notification to avoid noise... 

## Your Environment
Tested on master-4.0 // H2 // Chrome

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10751

**Comment by bryanboza** [comment]
Need the fix #10617

**Comment by bryanboza** [comment]
Fixed
