### ISSUE TITLE
Unify add publish endpoint and license jsp with 3.7 changes into 4.0

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10696]
These JSP's changed a lot in each version and the merge requires decision probably with @fmontes , @oarrietadotcms and @agomez-dotcms. 

JSPs:
1. license.jsp
2. add_publish_endpoint.jsp

Branch: 3.7-merge-to-4.0

**Comment by nollymar** [comment]
After a discussion with @dsilvam , @oarrietadotcms and @jgambarios , we agreed to merge *license.jsp* as suggested in https://github.com/dotCMS/core/pull/10715.

However, *add_publish_endpoint.jsp* will be merged only with those changes in 3.7. Cody will re apply  styles and design changes from 4.0
