### ISSUE TITLE
Rules Engine can fill logs with InvalidLicenseException errors 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10697]
If you have a site with rules that is getting traffic and you relicense or the license expires, the rules engine will fill your log with InvalidLicenseException and stacktraces.

- create a whole site rule
- `ab -n 10000 -c 3 http://localhost:8080/`
- login to the backend and reset your license
 - your log is filling up

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10698

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
