### ISSUE TITLE
We need to frame bust on login screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10709]
How to reproduce:
1. Login and browse to any portlet
2. kill all your browser cookies for the site
3. Click a link in the old portlet or click to browse to another portlet
4. this:
![screen shot 2017-02-14 at 8 34 32 am](https://cloud.githubusercontent.com/assets/934364/22930969/bae50ad0-f290-11e6-8e27-5bff64391097.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10729

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // Chrome
