### ISSUE TITLE
Error changing the site thumbnail 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10708]
We are having problems when you try to change the site thumbnail from any host 

## Expected Behavior
We should be able to change it without problems 

## Current Behavior
We have an error exception on logs: https://gist.github.com/bryanboza/c801c467168d42ece0a9dc2548a55b38

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to sites portlet 
3. Edit the site 
4. Change the host thumbnail and save it 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by bryanboza** [comment]
Also we are having problems if the host have thumbnail and you add a new site https://screencast.com/t/eWjpNP8A4ufS

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10786

About the thumbnail: I talked with Cody and it is not used right now on the new UI but they plan to add it in future releases.

Also @jgambarios is going to report an issue with removing the binary field image (host thumbnail).

**Comment by bryanboza** [comment]
We still having problems with this card: #10906

**Comment by nollymar** [comment]
The error commented on #10906 could not be recreated
