### ISSUE TITLE
Get rid of inline help link

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10701]
We need to remove this button/link from the old jsps

![screen shot 2017-02-13 at 1 35 21 pm](https://cloud.githubusercontent.com/assets/934364/22897376/6fe2aa8c-f1f1-11e6-989c-0c920f5cb0d8.png)

**Comment by john-thomas-dotcms** [comment]
@wezell, cleaning up the inline help is on my backburner list, and I've been slowly merging the inline help docs into the regular docs (so inline help pulls up the regular doc sections).

Do you want to just remove the button in 4.0, or take the time to update the inline help so it's always pointing to regular (and regularly updated) docs?

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10745

**Comment by bryanboza** [comment]
Fixed, now we don't have this window
