### ISSUE TITLE
Re-apply styles to the add_publish_endpoint.jsp

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10719]
After the migration of the 3.7 code to 4.0 and the addition of the Static Publish UI we need to re-apply the UI changes on this file: **add_publish_endpoint.jsp**

- https://www.screencast.com/t/pq7E5xoUYH45
- https://cloudup.com/cNmBK9yonOv

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10736

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
