### ISSUE TITLE
Revisit ContentTypeImportExportUtil for new ContentTypes

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10711]
Code here needs to change:
https://github.com/dotCMS/core/commit/09c0d311da5c0fcbe8cc17314f8666717fb11710#diff-6f5be13b3de23ad695770ff9f6acd009

- Don't use FieldsCache
- contentType.fields() should get all the fields
- use contentType to json functionality (ask @wezell )

**Comment by agomez-dotcms** [comment]
PR Core: https://github.com/dotCMS/core/pull/11503

**Comment by dsilvam** [comment]
Note to QA: please generate a new starter with new content types included and then load the new starter from an empty db

**Comment by dsilvam** [comment]
PR for 4.1: https://github.com/dotCMS/core/pull/11520

**Comment by shaydotcms** [comment]
Passed QA.
- Generated new content types and added new content to those content types.
- Then generated a new starter with new content types (and contents) included and then loaded the new starter from an empty db: The new content types are showing successfully
- New contents were also created in different language than default and they are showing with new starter.

Tested locally in  master-4.1 / commit 6b3ae069404821f907d4ff7bd8e663d810693ea7
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8

**Comment by wezell** [comment]
Use field.variables() instead of reloading variables

**Comment by wezell** [comment]
In fact - @agomez-dotcms we might want to make this method private or protected to prevent it from being used outside the ContentType's instantiation/hydration.  Thoughts?

APILocator.getContentTypeFieldAPI().loadVariables(ff)

**Comment by agomez-dotcms** [comment]
PR Core: https://github.com/dotCMS/core/pull/11557
