### ISSUE TITLE
Legacy Files clean up

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10716]
We need to remove all the code related to **legacy Files**, it is important to remove all the related code, tests, APIs, Factories, Cache, Portles, JSPs, etc...

Also remove hibernate mappings

**Comment by wezell** [comment]
All of these need to be deleted and then we fix the red:

- src/main/java/com/dotmarketing/portlets/htmlpages/*
- src/main/java/com/dotmarketing/portlets/files/*

One caveat or file we should leave - the MultiFileUpload form the browser uses a struts action in the 
- src/main/java/com/dotmarketing/portlets/files/*

**Comment by dsilvam** [comment]
Change log: scripting package is being removed as well. Contact @nollymar for more info

**Comment by dsilvam** [comment]
Note to QA: QA should be covered by https://github.com/dotCMS/core/issues/10725

**Comment by nollymar** [comment]
Huge refactoring to remove everything related to legacy files. Changes from @erickgonzalez (legacy html) are included as part of the PRs:

PR Core: https://github.com/dotCMS/core/pull/10802
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/448
PR License: https://github.com/dotCMS/license/pull/43
