### ISSUE TITLE
Change AWS lib dependency to only require S3

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10721]
Like this:

`compile group: 'com.amazonaws', name: 'aws-java-sdk-s3', version:'1.11.66'`

Not this:

`compile group: 'com.amazonaws', name: 'aws-java-sdk', version:'1.11.66'`

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10733

WEB-INF folder was reduced from 364 to 282 jars and Static Publish is still working just fine.
