### ISSUE TITLE
Legacy HTML Pages clean up

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10723]
We need to remove all the code related to legacy HTML pages, it is important to remove all the related code, tests, APIs, Factories, Cache, Portles, JSPs, etc...

All of these need to be deleted and then we fix the red:

src/main/java/com/dotmarketing/portlets/htmlpages/*

Also remove hibernate mappings

- [x] Create a page
- [x] Add New Content to the page
- [x] Add Existing Content to the page
- [x] Publish Page
- [x] Edit Page
- [x] Cut Page
- [x] Copy Page
- [x] Remove Page
- [x] Create page version in Spanish
- [x] Push Publish page
- [x] Site Search

**Comment by erickgonzalez** [comment]
Remember to remove from the UI the tool of Migrate Legacy HTML Pages

**Comment by dsilvam** [comment]
Note to QA: QA will be done here https://github.com/dotCMS/core/issues/10725

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/443
