### ISSUE TITLE
Allow text files to be edited inline

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10727]
Content Editors should be able to edit text files inline on the edit content screen

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10735

**Comment by wezell** [comment]
This got overwritten when we removed the legacy Files

**Comment by nollymar** [comment]
Thanks for the observation @wezell . I'll working on it.

**Comment by nollymar** [comment]
Fix for overwritten files: https://github.com/dotCMS/core/pull/10848
