### ISSUE TITLE
Failing tests in jenkins 4.0

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10730]
The following two tests are failing in Jenkins for all DBs:

https://cb.dotcms.com/job/Git_Master_Int_Funct_Test_Runner_4.0_Postgres/191/testReport/

As expected, they also fail in 4.1.

We need to fix 'em

**Comment by oarrietadotcms** [comment]
branch: issue-10730-fix-test

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10747
