### ISSUE TITLE
Reset License issues

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10738]
When you click "Reset License Identity" button, the browser console throws an error. In addition the UI states "ERROR HTTP code status: 200"
You will notice also that you have to click twice the "Reset License Identity" button to get the license rest

![license](https://cloud.githubusercontent.com/assets/8741846/22985817/4589a54a-f36f-11e6-8b41-265758a8be16.gif)

## Expected Behavior
1. No browser console errors when you hit "Reset License Identity" button
2. UI should not display "ERROR HTTP code status: 200"
3. You should not have to click twice the "Reset License Identity" button to get the license removed

## Current Behavior
1. When you click "Reset License Identity" button, the browser console throws an error
2. UI states "ERROR HTTP code status: 200"
3. You will notice also that you have to click twice the "Reset License Identity" button to get the license reset

## Steps to Reproduce (for bugs)
1. Startup a dotcms instance and apply a license (trial.jsp)
2. Navigate to System> Configuration. Click License Manager tab; you should see the License information. If you inspect the browser console, you will not see any errors at this point
3. Now click "Reset License Identity" button and you will see in the UI the message "ERROR HTTP code status: 200"
In addition, the browser console you show an error: "TypeError: dojo.byId(...) is null"
4. Notice that the License has not been reset, until you click "Reset License Identity" button again

## Your Environment
- dotCMS version used: Latest master_4.0
- Database and version: Postgres 9.3.5
- Operating System and version: Mac OS 10.10.5
- Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10773
