### ISSUE TITLE
Java Null Pointer error in Edit mode when using "shortyUrl" param

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10734]
Getting a Java Null Pointer error in Edit mode when adding this code to the news listing.vtl on demo:

Shorty of binary URL: $!{newsItem.image.shortyUrl}<br/>

The tool works on live mode but in edit mode, the error appears on the screen.  When originally tested, this parameter worked fine, but we made some changes right before the release that might have affected the shorty tool

![nullpointer](https://cloud.githubusercontent.com/assets/1569167/22983341/69256028-f367-11e6-93e8-f32a908b08eb.png)

**Comment by DeanGonzalez** [comment]
After the fix, we need to make sure that all the ways you can use the shorty tool still work: http://dotcms.com/docs/latest/displaying-content-with-binary-image-fields

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10737

**Comment by DeanGonzalez** [comment]
Tested in 4.0 - working in Edit mode
