### ISSUE TITLE
Error 500 trying to download a bundle pushed to a static environment 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10740]
## Expected Behavior
As the normal pushed bundles we should be able to download the bundle, this from the publish queue portlet... 
https://screencast.com/t/B34nhn7Er

## Current Behavior
We are having an error 500 when  you try to download 
https://screencast.com/t/7JEivGLIM

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your static pushing environment 
3. Try to push some bundle
4. Go to publish queue and try to download the bundle

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/446

**Comment by bryanboza** [comment]
Still having the same problem

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
