### ISSUE TITLE
Unable to add pushing environment using the system in spanish

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10749]
We should be able to use the system normally in any of the languages

## Expected Behavior
We should be able to push normally in any language

## Current Behavior
We are unable to add environments, this if you use the system in spanish

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to system --> Configuration --> Pushing Environments
3. Try to add a new environment

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10754

**Comment by bryanboza** [comment]
Fixed, tested in master-4.0
