### ISSUE TITLE
Unable to open the icon list adding a new tab

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10743]
## Expected Behavior
We need allow click in the icon list link that we have when you are adding a new tab 

## Current Behavior
We are unable to open this link, this because this is a mouse over event, then when you move the mouse, the dialog is disappearing 

SC: https://screencast.com/t/qYsJgYfSXD

## Your Environment
Tested on master-4.0 // MySQL // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10956

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0
