### ISSUE TITLE
Edit mode errors

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10753]
## Current Behavior

1. Clear cache
2. Go to http://localhost:8080/dotAdmin
3. Logging in
4. Copy in the address bar and go to: http://localhost:8080/about-us/index
5. Edit a Content --> Fails

![2017-02-17_11-05-47](https://cloud.githubusercontent.com/assets/923947/23075361/c4e76ff0-f501-11e6-9bca-afe497e5757c.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10775

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 and now i am unable to recreate
