### ISSUE TITLE
Push Publish modal shows wrong options

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10759]
1. Add content to a Push Publish Bundle
2. Site Browser --> Publishing Queue --> Bundles --> Push Publish

The Push Publish modal starts with the **Push** option selected but shows the **Expire** date inputs that belongs to the **Push and Expire** option.

![2017-02-17_14-38-38](https://cloud.githubusercontent.com/assets/923947/23082664/f30efce0-f51f-11e6-9e35-44d1cd41a1d0.gif)

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10762

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
