### ISSUE TITLE
Typo in warning message

### ISSUE THREAD

**Issue by edwingustafson** [dotCMS/core#10761]
Typo in warning message.

https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/viewtools/content/util/ContentUtils.java#L114

## Expected Behavior

Should read "More than one"

## Current Behavior

Currently reads "More then one"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by john-thomas-dotcms** [comment]
Thanks for the heads up.  We are currently reviewing _all_ the messages in the application for the upcoming 4.0 release.  We'll make sure this correction is included.

**Comment by edwingustafson** [comment]
Closing, fixed long ago.
