### ISSUE TITLE
Unable to publish pages with associated content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10763]
## Expected Behavior
When you push some page and have associated content that isn't published, the system should publish this content by dependency. 

## Current Behavior
We are having a problems when you try to push the page and have associated content 

SC: https://www.screencast.com/t/AgzGJlTXyv2

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new page 
3. Add some contents to this page, but just save that ones(not publish)
4. Go to the page properties and try to publish the page 

## Your Environment
Tested in the last master-4.0 // H2 // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10767

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
