### ISSUE TITLE
Cron job not being reset when servers miss a job in a clustered environment

### ISSUE THREAD

**Issue by roysilveira-hca** [dotCMS/core#10760]
## Expected Behavior
In a clustered environment, when all the servers are down, and a cron job is missed, when the servers are restarted, the cron job should go to the next scheduled execution of the job. 

## Current Behavior
When a cron job is missed in a clustered environment, due to the server being down, the cron job is stuck at the old schedule. Since that time is passed, the servers never pick that job up again.
Example: If there is a cron job that is scheduled to run every 5 minutes, and the next run is at 10:00 am Feb 20 2017. and the servers are brought down at 9:58 am Feb 20 2017, and then brought back up at 10:02 am Feb 20 2017, the "Next Run" in dotCMS is stuck at 10:00 am Feb 20 2017. 

## Known Workarounds
Create a user job to run on the schedule.

**Comment by gabbydotCMS** [comment]
Reported by client: https://my.dotcms.com/tickets/detail.dot?id=b27ffc4e-81f6-4e57-8cdd-151cea0f5c70
