### ISSUE TITLE
We need publish the menu links when you click save & publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10779]
## Expected Behavior
When you are adding a new menu link and click save & publish we need publish it 

## Current Behavior
When you are adding a new menu link and click save & publish we are just saving the link, but appears as unpublished

**FYI: This works in the old UI**

## Steps to Reproduce (for bugs)
1. Login 
2. Go to any folder 
3. Try to add a new menu link
4. Save and publish 

## Your Environment
Tested on master-4.0 // Chrome & Edge

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10792

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
