### ISSUE TITLE
[UI] : Top-right option menu in Content Search page is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#10771]
The top-right option menu used to publish, un-publish, archive, delete, etc. is not working. Users need to go directly to the content in the list, right-click it, and then select the appropriate option.

<img width="331" alt="top-right-option-menu" src="https://cloud.githubusercontent.com/assets/8779585/23221397/9407d964-f8ea-11e6-898a-45a146caf3ff.png">

## Expected Behavior
The options in the top-right option menu should work the same as right-clicking a content in the list.

## Current Behavior
The options in the top-right option menu is NOT working.

## Possible Solution
N/A

## Known Workarounds
Right-click the specific content in the list to perform those actions.

## Steps to Reproduce (for bugs)
1. Log into the dotCMS back-end and go to the Content Search page.
2. Select the "Content (Generic)" option in the "Type" drop-down.
3. Click the checkbox next to the title of any content in the list.
4. Click any of the options in the the top-right option menu. They don't work.

## Context
Users not being aware of the right-click capability in dotCMS can have difficulties publishing, un-publishing, archiving, etc. a content. Also, this cripples the ability for users to select several contents and perform the same action on them, which diminishes productivity.

## Your Environment
* dotCMS version used: 4.0
* Browser Name and version: Chrome 56.0.2924.87 (64-bit)
* Operating System and version: Mac OS X 10.9.5
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8
* Database and version: MySQL 5.6.20
* Application module (if apply): Content Search

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10788

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
