### ISSUE TITLE
Unable to reuse content in editing mode

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10776]
## Expected Behavior
We should be able to reuse different contents in multiple pages without problems 

## Current Behavior
We are having a empty form and you can't see the contents 

SC: https://screencast.com/t/PE44SyG2d

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new page 
3. Try to reuse some content 

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10787

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
