### ISSUE TITLE
Create new loading screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10774]
We need to add brand to this loading screen.  

![screen shot 2017-02-22 at 10 18 49 am](https://cloud.githubusercontent.com/assets/934364/23220975/a5c8562c-f8f1-11e6-85d6-3b70558ea677.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/279

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF... Nice loading
