### ISSUE TITLE
Style improving part #2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10777]
Here some new sections that needs styling help:

- [x] Pages Statics: https://screencast.com/t/mC0TlbQ20 

- [ ] The show archived is different in the sites portlet and in the site browser, we need consistence

- [ ] After add a new content  type we need center the no fields text: https://screencast.com/t/1FvFW6OFBZ 

- [ ] The cancel button in the text editor need the flat style: https://www.screencast.com/t/1NIlSuAJrt23

- [ ] Workflow Task  > edit content / change language dialog box need more space
https://www.screencast.com/t/mngXapGE

- [ ] Workflow Task  > Attached files tab
https://www.screencast.com/t/zEZrKas46

**Comment by wezell** [comment]
known issues
