### ISSUE TITLE
What's changed feature isn't working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10772]
We are having problems when you try to see the changes from the editing mode 

## Expected Behavior
We should be able to see what's changed in the pages 

## Current Behavior
We are showing an error because we are unable to find the jsp file 

SC: https://screencast.com/t/dakv0WEGP9a

## Steps to Reproduce (for bugs)
1. Login
2. Apply the license 
3. Add a new page 
4. Add content to the page and save & publish
5. Add more content and just save 
6. Go to preview tab and click in the what's changed link 

## Your Environment
Tested in the last master-4.0 // MySQL // FF

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10855

**Comment by erickgonzalez** [comment]
Working as it should. Showing red when content is deleted and green when content is added.
