### ISSUE TITLE
On logging in, make default screen the first portlet in the first layout

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10770]
When you login now, you are taken to the pattern library by default. We need to mirror the old behavior and take the user to their first portlet if no specific path is specified.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/283

**Comment by bryanboza** [comment]
We are having problems on FF, the system have the correct URL, but isn't loading the portlet...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/288

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/289

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF

**Comment by bryanboza** [comment]
We still having problems with this card, after login the system is showing a blank page... https://screencast.com/t/yuIXh5xa

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/307

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
