### ISSUE TITLE
Microsoft Edge problems part #2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10778]
Here some new findings that we have on Microsoft Edge: 

- [ ] The login as windows looks bad https://www.screencast.com/t/bNEnGXHp (**can't reproduce**)

- [x]  We are showing a "X" in the dot_site_selector component when you change the site, and this allow leave the component without selection 

- [x] Unable to see the icons in the host tree: https://www.screencast.com/t/KfQYCUp4JJhZ

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/10795
https://github.com/dotCMS/core-web/pull/281

**Comment by bryanboza** [comment]
Fixed, tested on Microsoft Edge // dotCMS 4.0
