### ISSUE TITLE
Edit mode controls wrapping

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10782]
The "Add Content" dropdown is not wide enough making "reuse content" wrap.

![screen shot 2017-02-22 at 8 01 32 pm](https://cloud.githubusercontent.com/assets/934364/23240177/db92cf74-f939-11e6-964f-0387e1affd0a.png)

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/pull/10787

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
