### ISSUE TITLE
Still seeing nested iframes in edit mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10781]
Try different editing on url-mapped content.  This happens when you edit a url mapped content from edit mode, eg. hit the edit button from this page:

http://demo.dotcms.com/news/u-s-labor-department-moves-forward-on-retirement-advice-proposal 

and not 
 
http://demo.dotcms.com/news/

 ---

![url-maps](https://cloud.githubusercontent.com/assets/934364/23240387/40ab95a2-f93b-11e6-8c09-e7a24f8cca27.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10800

**Comment by bryanboza** [comment]
Unable to recreate in master-4.0 after the fix...
