### ISSUE TITLE
Editing a container from edit mode results in an "oops"

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10783]
See below.  I was trying to hit save and publish

![container](https://cloud.githubusercontent.com/assets/934364/23240306/c89b9f6c-f93a-11e6-80e9-f070fcf6edbf.gif)

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10837

**Comment by nollymar** [comment]
Tested on 4.0. Working correctly.
