### ISSUE TITLE
Image Editor calculating wrong Y on crop

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10780]
When you use the crop function in the image editor, the resultant crop is 

1. Too short, the crop_h value is too small and 
2. Too high, the crop_y value is wrong

![cropping](https://cloud.githubusercontent.com/assets/934364/23237930/9e84fd70-f92d-11e6-8da6-e2e392d9a4bf.gif)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/11098

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // MySQL // FF
