### ISSUE TITLE
Remove button does not clear the image in a File Asset content type

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10793]
When you click on "Remove" button to delete the image, the image doesn't go away. If you keep adding and removing images, they stay there.

## Expected Behavior
Images should go away when you click "Remove" button

## Current Behavior
When you click on "Remove" button to delete the image, the image doesn't go away. If you keep adding and removing images, they stay there.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Site Browser
3. Click the ellipsis to add "Image or File" 
4. Add any image, then click Remove button.
5. You will see it doesn't clear the image.
6. If you keep adding images and hitting Remove button, the images stay there

![clear image](https://cloud.githubusercontent.com/assets/8741846/23305989/e54e6180-fa66-11e6-971e-0edd8d036478.gif)

## Your Environment
* dotCMS version used: Master_4.0
* Last commit b5df569bc378a8cd14d2dbf85fbfdc9ab03630b4
* Database and version: Postgres 9.3.5 / SQLServer 2012 / MySQL 5.6.23
* Operating System and version: Win7 Pro SP1 / Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by dsilvam** [comment]
Note to QA: This seems to be fixed. We need to double check

**Comment by erickgonzalez** [comment]
Work as expected
