### ISSUE TITLE
Top-right option menu in Content Search remains enabled 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#10790]
When you click any of the menu option the menu remains enabled, this menu Should be disabled after that.

## Expected Behavior
The Top-right option menu in Content Search should come back to disable because there aren't content selected 

## Steps to Reproduce (for bugs)
1. Log into the dotCMS back-end and go to the Content Search page (The menu is disabled).
3. Click the checkbox next to the title of any content in the list (The menu is enabled).
4. Click any of the options in the the top-right option menu. The menu is still enabled but not content is selected.

**Comment by fmontes** [comment]
Turns out the issue was related with the way we are including forms to submit because the new error of google chrome.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10934

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
