### ISSUE TITLE
Delete db tables for legacy pages and legacy files 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10799]
Need to include in both:
- Startup task
- .sql files

Related to https://github.com/dotCMS/core/issues/10723 and 
https://github.com/dotCMS/core/issues/10716

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10847

**Comment by erickgonzalez** [comment]
PR for failing tests https://github.com/dotCMS/core/pull/10851

**Comment by dsilvam** [comment]
Note to QA: we need to test both upgrades and clean starts

**Comment by oarrietadotcms** [comment]
Working just fine, I tested on clean instance and also from 3.6.0 (with starter data). No errors at all.

Upgrade log: https://gist.github.com/oarrietadotcms/3e1a502396b2ec73d2a4e3d12e551d4a
