### ISSUE TITLE
Svg image is diplaying xml code below Resource Link

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10796]
## Expected Behavior
Xml code should not be displayed when the .svg image is being edited. 
This is the normal behavior in demo2.dotcms.com

## Current Behavior
When you edit a .svg image, its xml code is displayed below 

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Site Browser
3. Click the ellipsis to add "Image or File" in the root or inside a folder
4. Click to browse and add a .svg image, then click Save/Publish.
5. Reopen .svg image in Edit mode
6. You will see the xml code underneath the Resource Link

![svg image](https://cloud.githubusercontent.com/assets/8741846/23280152/b90f83ee-f9dd-11e6-9814-955e9b9dd53a.gif)

## Your Environment
* dotCMS version used: Latest master_4.0
* Last commit b5df569bc378a8cd14d2dbf85fbfdc9ab03630b4
* Database and version: SQLServer 2012 / MySQL 5.6.23
* Operating System and version: Win7 Pro SP1 / Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10964

**Comment by erickgonzalez** [comment]
Working as expected. Tested with .jpg, .svg, .xml, .log and it's showing only the image with the first 2 and the text editor with the others.
