### ISSUE TITLE
Need remove the references to the legacy classes when you publish some page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10808]
## Expected Behavior
We should be able to publish pages without problems 

## Current Behavior
We are having an error when you try to publish some page that have related content, this because we are using references to the deleted code...
ST: https://gist.github.com/bryanboza/e0f1a482b35580a46d434318904a9872

## Steps to Reproduce (for bugs)
1. Login
2. Create a new page
3. Add some contents to this page, but just save that ones(not publish)
4. Go to the page properties and try to publish the page

## Your Environment
Tested on master-4.0 // MySQL // FF

**Comment by jcastro-dotcms** [comment]
This was fixed by the latest merged changes related to removing legacy HTML code.

**Comment by bryanboza** [comment]
Fixed, tested in the last master-4.0 // MySQL // FF
