### ISSUE TITLE
We are duplicating notifications on FF

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10807]
Related to #10664 

## Expected Behavior
We should receive the same notifications as all the others browsers 

## Current Behavior
We are duplicating the notifications, then you need double notifications on every event 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to content types 
3. Select some content type 
4. Delete some field 

![r1](https://cloud.githubusercontent.com/assets/2641437/23320611/1bc02c14-faa1-11e6-8df3-b260a35a5872.gif)

## Your Environment
Tested on master-4.0 // H2 // FF (51.0.1)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/285

**Comment by bryanboza** [comment]
Now some times we are not receiving notifications in all the browsers... needs work here
SC: https://screencast.com/t/pJo5mcMob

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/287

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF

**Comment by bryanboza** [comment]
We still duplicating notifications https://www.screencast.com/t/MwvxgYWa

**Comment by bryanboza** [comment]
FYI: We still duplicating all the notifications not only the reindex
