### ISSUE TITLE
Edit text when editing file is not working

### ISSUE THREAD

**Issue by woontsoudev** [dotCMS/core#10809]
1. /application/vtl/custom-fields/color-picker.vtl
2. clicking on edit text brn fail

![error](https://content.screencast.com/users/woontsou/folders/Jing/media/b8730a11-1882-4e8f-9612-5995719cd43f/00000025.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10835

**Comment by bryanboza** [comment]
Fixed, now the system open the modal without problems... Style improvements reported on #10777
