### ISSUE TITLE
Microsoft Edge part #3

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10804]
Here more UI tweaks 

- [x] Double scroll bar editing workflows: https://www.screencast.com/t/0IyU3GLLt5s7

- [x] Maintenance tools: https://www.screencast.com/t/L9MrRqyvIPKB

- [x] Required fields message isn't showing properly https://www.screencast.com/t/EdLFxxnZN

- [x] The cancel button need the flat style... this on push related content window https://screencast.com/t/EORbEi38i

**Comment by fmontes** [comment]
Marked issues are done, unmarked is a backend stuff, errors are not coming: https://github.com/dotCMS/core/tree/issue-10804-gen-ui

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10889

**Comment by bryanboza** [comment]
Fixed, tested on Microsoft Edge // H2 // master-4.0
