### ISSUE TITLE
Categories RT

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10818]

**Comment by shaydotcms** [comment]
Tested in master-3.7 / commit 27b79769c267715637e7dfe2a219c66114485fb7
SQLServer 2012 / MySQL 5.6.23
Mac OS 10.10
Firefox v45.0.1 / Chrome v54.0.2840.98
Tomcat 8
Java 8

**Comment by shaydotcms** [comment]
Tested in master-4.0 / commit 60df59fea84c921c870df185470524d89fc5d9bd
MySQL 5.6.35
Mac OS 10.10
Firefox v45.0.1 / Chrome v54.0.2840.98
Tomcat 8
Java 8
