### ISSUE TITLE
Permissions Tab on objects is broken - shows no roles

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10831]
After today's commits, the permissions tab is broken:

To reproduce, just start up and look at the permissions tab on any folder on the site browser
![permissions](https://cloud.githubusercontent.com/assets/1569167/23374223/eca1e1bc-fce8-11e6-800e-abc5d07e82c2.png)

**Comment by nollymar** [comment]
Old references to legacy files were removed.

PR: https://github.com/dotCMS/core/pull/10832

**Comment by oarrietadotcms** [comment]
Working as expected.
