### ISSUE TITLE
Unable to upgrade from dotcms-3.7 to 4.0 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10844]
We are having some problems trying to upgrade from the last 3.7 to 4.0 

## Expected Behavior
We should be able to upgrade without problems

## Current Behavior
We are having problems with the portlet id, this because in 4.0 those was changes and when you try to login on backend the system is trying to find with the old id... 
SC: https://screencast.com/t/tM3iXBrhvSN
ST: https://gist.github.com/bryanboza/168867633775f2bf096d72e68677d849

## Possible Solution
Maybe we need clear the roles cache 

**FYI:** If you shutdown and start again the app, you are able to navigate through portlets 

## Your Environment
Tested on masOSX
From: dotCMS 3.7 // MySQL (5.6)
To: dotCMS 4.0 // MySQL  (5.6)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10864

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
