### ISSUE TITLE
Integrity checker is not working in 4.0

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10840]
## Current Behavior

An exception is thrown when Integrity Checker is run. See trace log: https://gist.github.com/nollymar/2a84fbd704dbc4867b5d8f13d29e5e83

## Steps to Reproduce (for bugs)

1. Set up a Dynamic Push Publishing environment with one server and one receiver, using independent Oracle databases
2. In the sender environment run Integrity Checker

## Your Environment

* dotCMS version used: 4.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Oracle DB
* Application module (if apply): Push Publishing

**Comment by nollymar** [comment]
Fixed. The fix includes:
- A not null constraint was removed from a temp table used during integrity checker validation
- dotcms.org.default role_key was excluded from csv generation

PR: https://github.com/dotCMS/core/pull/10843

**Comment by oarrietadotcms** [comment]
Working as expected.
