### ISSUE TITLE
Removing a File Asset does not remove image icon

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10841]
Found in dotCMS 4.0

Easy to reproduce bug: Add a new file asset image to a folder and save/publish.  Then edit the image again and click the remove button to replace it with a new image.  The image icon is not removed.  If you add a new image, it stacks the new image on top of the old image:

![removing file asset](https://cloud.githubusercontent.com/assets/1569167/23416572/fba0390a-fda8-11e6-953f-eda255fb49b6.png)

**Comment by oarrietadotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/10846
