### ISSUE TITLE
CookieFilter throws An attempt was made to write more data to the response headers than there was room available in the buffer. Increase maxHttpHeaderSize on the connector or write less data into the response headers. error

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#10857]
When the client  uses third parties application that uses cookies, The CookiesFilter is causing the system to throw the following exception 

```
2017-02-23T11:11:14,150 ERROR c.l.p.s.MainServlet [url:GET//...] An attempt was made to write more data to the response headers than there was room available in the buffer. Increase maxHttpHeaderSize on the connector or write less data into the response headers. 
``` 

As the client describes: The CookiesFilter ServletFilter is configured in web.xml for all URLs. The com.dotmarketing.filters.CookiesFilter.doFilter() method calls com.liferay.util.CookieUtil.setCookiesSecurityHeaders which in turns calls a 3 parameter variant of the same method name, setCookiesSecurityHeaders(HttpServletRequest req, HttpServletResponse res, Set cookies). This method then loops through all cookies in the request (except JSESSIONID from Tomcat and dotCMS' one ID cookie) and performs the following:

Resets the path attribute to /;
Sets the httpOnly and secure flags to true (which we have configured because we believe in securing our users' data and really feel should be the default);
Resets the cookie to expire on browser exit overriding any external cookies that have either long lives or sessions in higher level domains.
This is really bad form, there is even a large comment in this method saying so. 

It breaks the following:

If the client have 3rd party integrations that use tracking cookies with short lifespans and unique names where a single user can get multiple cookies but the browser will continually discard older cookies. This code converts each of these into session cookies meaning the browser never discards them so the cookie list grows until the Cookie HTTP request header exceeds our current limit (8kb) and results in an error for the user.

We use cookies for marketing and tracking purposes that require long lives, these are broken in your product.
There are certain marketing cookies that require the httpOnly flag not be set so JavaScript can interact with them, this is not possible in this scenario.
Our infrastructure for distributing traffic in a highly available fashion requires cookie lengths that are short and domain name assignments that are reconfigured based on global availability.
The fix for this is simple, remove the CookiesFilter from web.xml since it only modifies request-side cookies, something a web application really should never do.

## Possible Solution
We should remove or modify the filter to only alter dotcms related cookies

## Known Workarounds

Some clients have disable the filter to avoid this issue

## Context
the issue was originally reported on https://my.dotcms.com/tickets/detail.dot?id=9106e246-04a8-4cf5-966e-ff2df936e2de

## Your Environment

* dotCMS version used: 3.6.0

**Comment by gabbydotCMS** [comment]
Dup https://github.com/dotCMS/core/issues/10856
