### ISSUE TITLE
Htmlpage table error when doing push publish

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10854]
An error in the receiver is showing when you click "Check Integrity" button:
https://gist.github.com/shaydotcms/46811774066c489af07c1b1e21ef8ee5

## Expected Behavior
"Check Integrity" button should run and verify PP configuration

## Current Behavior
An error in the receiver is showing when you click "Check Integrity" button:
https://gist.github.com/shaydotcms/46811774066c489af07c1b1e21ef8ee5

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Apply dotcms license
3. Go to System > Configuration> Publishing Environments tab
4. Setup Push Publish configuration
5. Hit "Check Integrity" button
6. You will see the error in the logs
https://gist.github.com/shaydotcms/46811774066c489af07c1b1e21ef8ee5

## Your Environment
* dotCMS version used: Master_4.0
* Last commit 657d56a396b8c5585f11200e2c540e6c8a419ace
* Database and version: Sender and Receiver MySQL 5.6.35
* Operating System and version: Sender Win7 Pro SP1 / Receiver Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by jcastro-dotcms** [comment]
This seems to be related to removing the legacy HTML pages code. It'll probably be the same for the legacy File checker.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10890
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/449

**Comment by nollymar** [comment]
This ticket was tested creating conflicts for folders, page assets and file assets.
Test result: Successful
