### ISSUE TITLE
Right-click on Site Browser folders and host disabled on page load

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10852]
Tested on today's dotCMS master-4.0

Right click is disabled on folders and hosts on Site Browser load.

Screencast: https://screencast.com/t/m8mLGo8IEF

You have to left click or hover over a + sign next to a folder to get the edit options.

Since rignt-click has been the only option on all previous versions to edit a folder or host, we should make sure that on page load, the folder or host can be right-clicked to show options on that folder or host.

**Comment by DeanGonzalez** [comment]
If you aren't seeing it - Command - R and then try to right-click a host or folder - it's a real bug

**Comment by DeanGonzalez** [comment]
Also, with clean browser cache, even left clicking requires two clicks just to open a folder: https://screencast.com/t/zgf8y9vg

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/290

**Comment by bryanboza** [comment]
Fixed
