### ISSUE TITLE
Code view seems broken

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10871]
I am running the core-web and it seems like code view of wysiwyg fields is broken.  It should show the Ace editor

![screen shot 2017-03-02 at 10 08 01 am](https://cloud.githubusercontent.com/assets/934364/23514039/0a536814-ff34-11e6-8a75-47b66b855c85.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10924

**Comment by bryanboza** [comment]
Fixed, related to #10916
