### ISSUE TITLE
Login Screen styling tweaks

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#10874]
Make CSS changes based on attached image

![screen shot 2017-03-01 at 4 12 29 pm](https://cloud.githubusercontent.com/assets/1561349/23516590/a4ea724e-ff3b-11e6-8ce6-44fb5356595d.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/293

**Comment by bryanboza** [comment]
Fixed, new improvements coming....
