### ISSUE TITLE
Suggested tags isn't working on 4.0 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10885]
## Expected Behavior
We should be able to show suggested tags without problems 

## Current Behavior
We have a JS problem not show the tags 
https://www.screencast.com/t/R260NLJzsY

## Steps to Reproduce (for bugs)
1. Login 
2. Go to content and try to add a new content  to the banner structure
3. Add a new tag 

## Your Environment
Tested on master-4.0 // MySQL// FF

**Comment by jdotcms** [comment]
fixed 
![screen shot 2017-03-03 at 4 07 43 pm](https://cloud.githubusercontent.com/assets/19578350/23570816/a4812d84-002b-11e7-8fec-686171ef8861.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10918

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0
