### ISSUE TITLE
Problems after upgrade from dotcms_3.7 to 4.0

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10883]
We are having some problems after upgrade 

## Expected Behavior
The dotSite Selector should work normally after upgrade

## Current Behavior
The dotSite selector isn't refreshing if you are in the site browser and change the site 
SC: https://screencast.com/t/9CNNE4V7Qq8

## Steps to Reproduce (for bugs)
1. Upgrade from 3.7 
2. Login 
3. Add a new site  
4. Go to site browser and try to change the site in the dotSite Selector 

## Your Environment
Tested on master-4.0 // MySQL // FF & Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/295

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/296

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
