### ISSUE TITLE
Unable to see the system tab in the angular menu if you expand all the menu items 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10895]
We are having all problems with the scroll bar if you expand all the tabs

## Expected Behavior
If you don't expand any of the tabs and don't have space we need a scroll bar 

## Current Behavior
If you expand all the tabs you are unable to see the system content: SC https://screencast.com/t/5o2jbRm4h6kM

## Steps to Reproduce (for bugs)
1. Login
2. Expand all the tabs 
3. Try to see the system content 

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/292

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // Postgres // FF & Chrome
