### ISSUE TITLE
Consistent identity mapping via immutable values

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10898]
- (Subject:userid vs email:emailaddress)
- Map SAML assertion subject name to "saml:<subject>" dotCMS userId

**Comment by dsilvam** [comment]
From conversation with @wezell @chrismccracken @jtesser @jcastro-dotcms :
- userid needs to be obtained from the subject (single value), instead of the attributes (separate from the subject) 
- No need to generate uuid anymore. Use the one provided
- No "saml:" prefix.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/plugin-dotcms-openSAML3/pull/7

**Comment by shaydotcms** [comment]
Passed QA.
Tested locally using dotcms_3.7.1 release
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
