### ISSUE TITLE
UI Tweaks fro 4.0 release

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#10896]
List of UI tweaks fro 4.0 release.

**Login page:**
- [ ] ~~Make background image size cover (background-size: cover;)~~ **(done in another task)**

**Content Search Screen**
- [x] Enlarge font on the "Add New Content" select content type pop-up table

**Edit Template**
- [ ] ~~Advanced template code field needs to be bigger.~~ **(not happening for me)**

![screen shot 2017-03-03 at 4 45 21 pm](https://cloud.githubusercontent.com/assets/1561349/23570125/d6caadc4-0030-11e7-9f0d-4cf858bda3a6.png)

More to come . . .

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10961

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0
