### ISSUE TITLE
Lucene Pull for BlogEntry Does not Include Last Day Specified

### ISSUE THREAD

**Issue by jweedenwright** [dotCMS/core#10892]
## Expected Behavior
As a developer, If I'm writing code to search for a blog entry between the 1st and 31st of March regardless of time of day of when it was published, I will only pass 20170301 and 20170331 and expect that blog entries created on ANY of those days will show up (again regardless of time of day).

The expected results would be to see all articles from 3/1 THROUGH 3/31.

## Current Behavior
The way that the dotCMS/lucene code appears to be working is that it appends 00:00:00 to both dates if a time is not passed. As such, the query will return blog entries from March 1st to March 30th, ignoring all articles created AFTER 00:00:00 on the 31st.

## Possible Solution
If a time is not passed for a datetime, add "00:00:00" to the start date and "23:59:59" to the end date, to ensure all blog entries are pulled through the end of the last day specified.

## Known Workarounds
A time could be passed as a workaround, but that's extra logic, extra code and unnecessary in some cases.

## Steps to Reproduce (for bugs)
1. Setup blog and blog entry content with relationships, ensure that one of the blog entries' posting date is on the last day of our query that we'll be building below.
2. Attempt a pull using a similar query in velocity:
set ($related_blog = $dotcontent.pullRelated("Blog-BlogEntry","8a1b4ea8-44b6-4d65-961e-57612065dd9e", "+blogEntry.postingDate:[20120302 TO 20170301]  ",false,100,"blogEntry.postingDate desc"))
3. Note that the blog entry that is on the last day is not included in the results.

## Your Environment
* dotCMS version used: 3.5.1
* Browser Name and version: Chrome
* Operating System and version: Mac OS

**Comment by gabbydotCMS** [comment]
Requested by client:
https://my.dotcms.com/tickets/detail.dot?id=8195415b-23f3-4aad-818a-e8183157f2ab

**Comment by wezell** [comment]
This should be handled in client code
