### ISSUE TITLE
JS error trying to see the site search jobs

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10907]
## Expected Behavior
We should be able to see the site search jobs without problems 

## Current Behavior
We are having a JS error calling the function and isn't showing jobs 
SC: https://screencast.com/t/fPT0bMss

## Steps to Reproduce (for bugs) 
1. Login 
2. Apply an enterprise license 
3. Go to system --> site search --> View all jobs

## Your Environment
Tested on master-4.0 // Postgres // Chrome

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // Postgres // Chrome  & FF

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10918

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
