### ISSUE TITLE
Better exception handling on NoSuchUser

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10901]

**Comment by wezell** [comment]
https://gist.github.com/chrismccracken/e0d568551066dca5e0e473d7788e7602

**Comment by oarrietadotcms** [comment]
This is working after Chris commit, tested on my local against Okta test server. Log: https://gist.github.com/oarrietadotcms/fceff08cf1affab5effc51b842d7b23c#file-gistfile1-txt-L2
