### ISSUE TITLE
JS problems trying to select the host thumbnail

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10906]
## Expected Behavior
We should support select the site thumbnail without problems 

## Current Behavior
We are having problems to select the host thumbnail field in the site properties, we are having a JS error here and the image never is uploaded.

Here the error: https://gist.github.com/bryanboza/9bb20561721a38086c52280c7083adb5

## Steps to Reproduce (for bugs)
1. Login 
2. Go to system --> Sites
3. Create a new site and try to select the thumbnail field 

## Your Environment
Tested on master-4.0 // Postgres // Chrome

**Comment by nollymar** [comment]
I was not able to reproduce it. It may have been related to a cache issue. Now, it is working as expected.
