### ISSUE TITLE
Editing Template from Edit mode doesn't save

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#10919]
Editing Template from Edit mode doesn't save>

## Expected Behavior
templates should save

## Current Behavior
doesn't save

## Possible Solution
fix it

## Known Workarounds
edit template from the admin screen not edit mode

## Steps to Reproduce (for bugs)
1. Click Edit template from Edit Mode
2.Try to save changes
3. Doesn't save

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/issues/10919

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
