### ISSUE TITLE
Error trying to edit contentlet

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10916]
1. Open the Content Search screen.
2. Search for "youtube remote".
3. Click on the "YouTube Remote Widget Call" content.

**Result:** The main frame is blank (it doesn't take you to the content editing screen for that content - or anywhere else).

![error](https://cloud.githubusercontent.com/assets/923947/23569914/7ac5c0da-0027-11e7-9027-7af4f0564db4.png)

**Comment by jgambarios** [comment]
Note from John regarding this issue:

> But the Link Checker finds a broken link in this piece of content, and the content is still showing (and found by the link checker) after a full reindex...so it seems like the content must exist somewhere.

**Comment by DeanGonzalez** [comment]
Jonathan and I looked at this together and isolated to the code option on WYSYWIG fields is broken: 
![codefielderror](https://cloud.githubusercontent.com/assets/1569167/23620689/74f9472a-025d-11e7-85ba-923f418a4661.png)

**Comment by DeanGonzalez** [comment]
We should also make sure that when we fix this that the ACE editor is still working: https://github.com/dotCMS/core/issues/10871

**Comment by jdotcms** [comment]
Fixed
![screen shot 2017-03-06 at 12 37 28 pm](https://cloud.githubusercontent.com/assets/19578350/23624012/cc412410-0269-11e7-947a-f04eddd15b33.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10929

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
