### ISSUE TITLE
Minor UI tweaks 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10927]
- [ ] Workflow Task > Preview-tab  https://screencast.com/t/N1BSTojSh
Demo is working in the same way

- [x] Workflow Task  > edit content / change language dialog box need more space
https://www.screencast.com/t/mngXapGE

- [x] Workflow Task > Edit content > info btn / empty header needs to be removed
https://www.screencast.com/t/N5PKFZoanJBK

- [x] Site Browser > Edit site > Permissions tab / more space between  Apply Changes btn and checkbox, Scroll https://www.screencast.com/t/Y5v9DpwXubx9

- [x] Site Browser > Edit page > Advanced Properties / btn icon space
https://www.screencast.com/t/6NdT2qMX32oM

- [x] Site Browser > Templates > Edit Template > Versions tab / Actions sidebar is overlapping the content tabs https://www.screencast.com/t/aRGYL0pJ

- [x] Site Browser > Time machine > action settings / Bottom space is too big
https://www.screencast.com/t/3t0tS5z1PDK0

- [x] Site Browser / unespected underline
https://www.screencast.com/t/zbgBThmyRyF

- [x] Content Search / checkbox alignment  https://www.screencast.com/t/KbxLxJjseb

- [x] Content Search > edit Banner > info button / the header without title needs to be removed
https://www.screencast.com/t/qOKCDiWAKTt

- [x] Content Search > Add new content > tags input / when you write a tag, the suggestions dropdown is not working https://www.screencast.com/t/R260NLJzsY

- [ ] Workflow Task  > Attached files tab https://www.screencast.com/t/zEZrKas46
Demo is working in the same way
- [x] Content Types > Categories > action delete categories / dialog space between buttons
https://www.screencast.com/t/dw53REPC

- [ ] System > Roles and tabs > users tab > action edit role / the checkbox needs more space
https://www.screencast.com/t/Cz8NaGtg
^^^ The delete action is not working

- [x] System > sites > action add site / remove header https://www.screencast.com/t/oqQxIYMky

- [x] System > site search > view all jobs tab / js error https://www.screencast.com/t/qveN8bijo39

- [x] System > site search > indices tab / btn icon space
https://www.screencast.com/t/VUux4iN6PRl

- [x] Adding new checkbox field https://screencast.com/t/zQWcMp6ij

- [x] The number is behind the bell icon https://www.screencast.com/t/gzAjHuinTWhA

- [x] Content Search > Content type dropdown / https://www.screencast.com/t/I06ODdpFsmN

- [x] Site Browser > Containers / overlaping https://www.screencast.com/t/hT5Bk8jn

- [x] System > Configuration / Get licence step boxes needs the same height https://www.screencast.com/t/cyKPkIUf4AE

- [x] Content > Edit Content / news content scroll unexpected https://www.screencast.com/t/69923s57QE

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10940

**Comment by bryanboza** [comment]
Fixed, some new improvements related on #11029
