### ISSUE TITLE
Blocking Race Condition on Startup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10921]
Running dotCMS locally - I have seen a few cases where the server does not come up and just sit locked up.  Normally, I just restart but it happened to me yesterday and I got threaddumps - one from yesterday and one this morning from the same jvm.

This happens if you don't have valid license - in the 

`CacheLocator.init`, it calls the 
`LicenseManager.getLicense`
which calls the 
`ClusterFactory.RemoveNodeFromClusterThread`
which calls `CacheLocator.init`

https://gist.github.com/wezell/2a5e33056d882aaf9ab5d266f763a949

https://gist.github.com/wezell/600648360aeba27ac69b7745e6452271

Here is the same thing from another startup on another day (3/8/17)
https://gist.github.com/wezell/17fe9bed8df304a3406bc9241992fbb9

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11268

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/466
