### ISSUE TITLE
Remove the WebKeys.CMS_USER_ID_COOKIE

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10923]
We should not still have this with our JWT work - we need to delete it from /com/dotmarketing/util/WebKeys.java and delete all references to and instead rely on JWT
---

![screen shot 2017-03-05 at 3 20 23 pm](https://cloud.githubusercontent.com/assets/934364/23590985/4aa5ea6a-01b7-11e7-9d8f-2704b451aa25.png)

**Comment by wezell** [comment]
might be related to #10922 as I had this cookie set

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10973

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF
