### ISSUE TITLE
Error trying to add more that one site field to any structure 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10932]
We are having some problems compiling the JSP file when you try to add two or more times a site / folder field in any structure.

## Expected Behavior
We should show an exception but not the JSP error on log 

## Current Behavior
We have an error compiling the JSP file 

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new structure
3. Try to add more that on Site / Folder field 

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jdotcms** [comment]
![screen shot 2017-03-07 at 10 44 44 am](https://cloud.githubusercontent.com/assets/19578350/23667344/23836e0e-0323-11e7-9ae7-968c5c22bf1b.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10946

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
