### ISSUE TITLE
Update fields and action button across the site.

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#10930]
- For the fields update hover and active color in form fields use blue instead of red
- For the action button make more prominent action button across the site use blue and make it a little bigger

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core-web/pull/294
https://github.com/dotCMS/core/pull/10942

**Comment by bryanboza** [comment]
Fixed, looks better now... Nice change
