### ISSUE TITLE
Integrity Checker is not detecting conflicts between roles

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10936]
Currently Integrity Checker is not detecting conflicts between roles. All other conflicts are being detected.

## Expected Behavior
Integrity Checker should detect conflicts between roles as of now

## Current Behavior
Integrity Checker is not detecting conflicts between roles. All other conflicts are being detected

## Steps to Reproduce (for bugs)
1. Startup a dotcms instance
2. Apply a dotcms license
3. Login to dotcms 
4. Navigate to Configuration> Publishing Environment 
5. Configure a push publish environment (Sender and Receiver)
6. Go to System> Roles & Tabs. Create a new role in the sender and receiver with the same name
7. On the sender, go back to Configuration> Publishing Environment and click the Check Integrity button
8. System will tell you "No Integrity Conflicts found", however there's a role with the same name in the sender and receiver.
9. No errors found in logs.

## Your Environment
* dotCMS version used: master_4.0
* Commit: d70d622f3dc4927bec7b12f680753556748bd83c
* Database and version: Sender MySQL 5.6.35 / Receiver MySQL 5.6.35
* Operating System and version: Sender Win7 / Receiver Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by shaydotcms** [comment]
It seems that the issue is when role Key is blank, Integrity Checker is not detecting the conflict between roles.

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/integrity-checker#IntegrityChecker
