### ISSUE TITLE
NavTool Reorder of Navitation items is missing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10941]
only exists in dotCMS 4.0 - probably as a result of cleanup task

Easy to reproduce, just edit any demo page, look at top navigation - the nav re-order arrows are missing:

This is dotCMS 4.0 missing the up and down arrows:

![navtool](https://cloud.githubusercontent.com/assets/1569167/23665539/5a2468a0-031e-11e7-87d2-c86583f2a2ac.png)

This is 3.7.1 with the re-order arrows functioning properly

![navtoolre-order](https://cloud.githubusercontent.com/assets/1569167/23665553/69d96ae8-031e-11e7-84d9-b448faabbfaf.png)

When we fix we need to make sure that top nav and side nav functions properly and at least down to the tertiary level on nested items

**Comment by dsilvam** [comment]
@fishsmith will fix in starter

**Comment by dsilvam** [comment]
Note to QA: need to test when new starter is ready

**Comment by wezell** [comment]
This needs new documentation
```
	#if ($EDIT_MODE && $PUBLISH_HTMLPAGE_PERMISSION)
	<div style="height:20px;">
      #set($_formId="dot_form_menu_$date.date.time") 
	  <form class="navbar-form navbar-right" action="${directorURL}" method="post" target="_parent" name="${_formId}" id="${_formId}">
		<input type="hidden" name="cmd" value="orderMenu" />
		<input type="hidden" name="hostId" value="${host.identifier}" />
		<input type="hidden" name="referer" value="${VTLSERVLET_URI}" />
		<input type="hidden" name="pagePath" value="${VTLSERVLET_URI}" />
		<input type="hidden" name="startLevel" value="1" />
		<input type="hidden" name="depth" value="2" />
			<a href="javascript:document.getElementById('${_formId}').submit();" class="btn btn-primary btn-xs normaltip" data-original-title="Reorder Menu">
				<i class="fa fa-arrow-up"></i> 
				<i class="fa fa-arrow-down"></i> 
			</a>
	  </form>
	</div>
    #end

```

**Comment by DeanGonzalez** [comment]
Updated doc: http://authoring.dotcms.com/docs/latest/navtool#ExampleAddReorderButton

**Comment by erickgonzalez** [comment]
Tested with the new starter generated today and working as expected.
