### ISSUE TITLE
Test and doc CSRF filter plugin

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10949]
We need to test and document the CSRF Filter so support can feel ok about suggesting that a customer use it.

**Comment by dsilvam** [comment]
https://github.com/dotCMS/com.dotcms.csrffilter

**Comment by wezell** [comment]
We might need to update plugin and add an allow config pattern that takes a list of allowed ips

**Comment by wezell** [comment]
Updated with this commit dotCMS/com.dotcms.csrffilter#1

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/csrf-filter-plugin
