### ISSUE TITLE
Test upgrades from old datasets

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10950]
This is part of the testing for 4.0 

We need to test in all dbs with dataset from customers

**Comment by oarrietadotcms** [comment]
Postgres log: https://gist.github.com/oarrietadotcms/3136f686036894e9d68db0517cb5dd25

**Comment by erickgonzalez** [comment]
MSSQL Log https://gist.github.com/erickgonzalez/2c12114513bde97034c61e26839b0f99

**Comment by oarrietadotcms** [comment]
MySQL log: https://gist.github.com/oarrietadotcms/f555525b20fe1177d1e82a669865ded6

**Comment by erickgonzalez** [comment]
Oracle Log: https://gist.github.com/erickgonzalez/7e2e41545bfe8dc9940b7968d254d90a
