### ISSUE TITLE
Containers never publish

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10957]
When you edit a container, it does not flush the caches properly and the front end does not reflect the change.

See attached - specifically try to edit the sub_nav container.

![containers never publish](https://cloud.githubusercontent.com/assets/934364/23684251/99229084-036b-11e7-8639-ff77d3857d2b.gif)

**Comment by jgambarios** [comment]
I was able to reproduce with the **Subnav Menu** container which has not Container Structures associated to it, the other containers works as expected, and looks like the problem is related with the changes made in https://github.com/dotCMS/core/issues/9209

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10962

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
