### ISSUE TITLE
Add the base content type icons back to the content selection list 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10952]
On the content search screen list, we need to add the base content type icons back.  I don't love the icons, but from a usability perspective they make sense when trying to find your content type.

We have the correct icons on the screen where you manage "Content Types".

![screen shot 2017-03-07 at 3 05 23 pm](https://cloud.githubusercontent.com/assets/934364/23675518/9f701d4a-0347-11e7-8fab-8ee1af9011ad.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10977

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
