### ISSUE TITLE
Tuckey Rules: Forward-type rules not working consistently for multilingual pages

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10953]
## Expected Behavior
Since it's possible to set a Tuckey rule that acts a forward rule, we expect that given a RegEx pattern, we should be able to be "forwarded" to a language-specific page/asset, according to the Tuckey Rule we have set.

## Current Behavior
For a multilingual page lookup, if the trailing slash is missing on the current request (for a non-default language asset), it always falls back (making a redirect) to the page with the default language, despite the rule actually matches with the defined Tuckey Rule.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Create a /test/ folder under demo.dotcms.com site.
2. Under /test/ folder, create a Multilingual page (in english and spanish). Use the blank template for this page. This page's URI is `index`.
2. Add a multilingual content to the page (in english and spanish).
3. Based on the com.dotcms.tuckey's OSGi plugin, add the following rule (see this [Activator.java](https://gist.github.com/joseorsini/a58cff9924d2e5f816d64e503ab77949) class for more reference). This rule indicates that for every request to `/es_la/(.*)` URI, it will set the CMS_FILTER_URLMAP_OVERRIDE property with the rest of the URI and set the languageId in session to "2" (Español - España language).
4. On different browsers, make the following requests:

- /test -> Goes to /test/, shows content on english.
- /test/ -> shows content on English/
- /es_la/test/ -> shows content on Spanish, URI does not change on browser.
- /es_la/test -> goes to /test/, shows content with the last language set on session (depending on tests, it could be English or Spanish).

## Context
So far, regardless of the missing trailing slash on the request's URIs that falls under the definition of our Tuckey Rule, we're not getting consistent results, so the expected behavior is that `/es_la/test` works the same way that a request to `/es_la/test/` works, which leads the request to the Spanish version of the page.

Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=05046ad1-a2da-4700-90b6-809a2b810abd

## Your Environment

* dotCMS 3.6.0, 3.7.1.
* Google Chrome, Firefox browsers.
* macOS Sierra.
* Tomcat 8.0.18.
* Java JDK 8u60.
* Postgres DB.

**Comment by wezell** [comment]
Unless I am missing something, this is not an issue - I think you ought to adjust your tuckey rule and set the user's language in session before the redirect.

**Comment by joseorsini** [comment]
The tuckey rule already does that, but it only works if the trailing slash is present in the UI.
