### ISSUE TITLE
Several Minor Issues

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#10959]
1. **Dynamic Plugins**: When you upload an invalid OSGI plugin file, or restart the OSGI framework, the popup shows a blank rectangle (mabte it's supposed to be a progress bar?).
    * To reproduce:
        1. Open `Dynamic Plugins` (System -> Dynamic Plugins).
        2. Click the `Restart Framework` button.
        3. Click `OK` to continue.

2. **Menu Links**: If you attempt to save a Menu Link without a Title, it wipes out the parent folder you selected.
    * To reproduce:
        1. Open the Links screen (Site Browser -> Links).
        2. Select `Add Link` from the pull-down menu (...).
        3. Enter information for all fields (parent folder, link, Target, Sort Order, and Show on Menu).
        4. Click `Save`.
            * Result: The screen refreshes, an error message appears (very briefly) in a hover popup, and the value you entered for the parent folder is wiped out.
            * Note that the other information entered is not wiped out.  Only the parent folder value is cleared.

3. **Blurry Icons**: When in the file selection popup, if you view files by icons, the icons are very blurry (and kind of ugly).
    * To reproduce:
        1. Open a File Asset.
        2. Browse for a file.
        3. Select a dotCMS folder with pages in it.
        4. Click the icon to view icons.

4. **Templates**: When you open the screen for the first time, you have to click on a template in the list twice to open it.
    * The first click seems to change focus from the search box to the list, and the second click actually opens the template.
    * This only happens the first time you show the screen; after you've opened a Template once, any time you show the list it works normally (with a single click).

5. **Template Designer**: "Remove Container" string (in the layout grid) is always wrapped to the next line.
    * This seems like it might have to do with the width of that page element (since the "Add Container" string, which appears to be styled the same, doesn't wrap).
    * Note: If I put `&nbsp;` in the string place of a space it prevents the wrapping, but does it even in places where it needs to wrap (when the columns are narrow).

6. **Permissions Tab (Templates)**: `Add User` shows the field is required, but shouldn't.
    * This field isn't really required (since you could select a Role instead).
    * In addition, `Add Role` doesn't show as required.
         * So the behavior is inconsistent, and the "Add User" behavior is (arguably) incorrect.

7. **Bundles screen**: The Push Publish popup opens even if no Environments are configured.
    * To reproduce:
        1. Make sure no publishing Environments are configured.
        2. Create a bundle.
        3. Open the Bundles list (Site Browser -> Publishing Queue -> Bundles tab).
        4. Select `Push Publish` for the bundle.

8. **Hard to see Links**: Some links in the backend UI text aren't visually distinguishable as links (they're not blue or styled differently from the non-link text).
    * Example: Publishing Environments: With no environments configured, open the Publishing Environments tool (System -> Configuration -> Publishing Environments).  The `Add One Now` links are in black text that's barely distinguishable from the non-link text.

9. **Content Types screen**: There are no icons for the Form or Contact Us content types (that come in the starter site).
    * To reproduce: Just open the Content Types screen and look at the `Form` and `Contact Us` content types in the list.

10. **Content Search screen**: The `Show Query` popup (Content Search -> Search button -> Show Query) appears to be sized incorrectly
    * The popup always shows a vertical scroll bar.
    * Note: The vertical scrollbar still shows up (with the same amount of empty space at the bottom) even if I reduce the amount of vertical space taken by the strings displayed in the popup.

11. **Roles & Tabs**: When adding or editing a tab, the link to the FontAwesome web site can't be clicked.
    * The link is in a hover popup which only shows up while the mouse is over the callout icon.
    * The hover popup goes away as soon as you try to move the mouse into it.
    * To reproduce:
        1. Open the `Roles & Tabs` screen (System -> Roles & Tabs).
        2. Select a Role.
        3. Click the `Tabs` tab.
        4. Click the `Create Custom Tab` button.
        5. Place the mouse over the callout icon next to the `Icon` field label.
        6. Try to click the link.

12. The tool names (along the left nav bar) often end up wrapping.
    * I'm not sure if this is intended, but I think it makes the left nav look a little messy, and makes it take up a little too much vertical space.
    * Note: The nav bar don't recognize HTML characters like `&nbsp;` in the tool names, so this can't be changed in the language props.

## Your Environment

* dotCMS version used: 03/06/17 nightly.
* Browser Name and version: Chrome
* Operating System and version: W7
* Application Server and version: Distro
* Java Brand and version: 1.8
* Database and version: Distro (H2)

**Comment by fmontes** [comment]
1. Didn’t do it.
2. Didn’t do it.
3. Didn’t do it.
4. Can’t reproduce.
5. Didn’t do it.
6. Didn’t do it.
7. Didn’t do it.
8. Done.
9. Done.
10. Didn’t do it.
11. Done.
12. Didn’t do it.
