### ISSUE TITLE
Each menu click loads portlet twice

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10960]
When trying to debug an issue with containers, I saw each request get loaded twice.  Let's make sure we are only loading the iframe once.  See gif:

---
![loading-twice](https://cloud.githubusercontent.com/assets/934364/23684755/af0cba5c-036e-11e7-984e-d027bcd4e17b.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10963

**Comment by bryanboza** [comment]
Fixed, now i have just one call each request... Tested on master-4.0
