### ISSUE TITLE
Licensing: Trial licenses cannot be requested

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10967]
## Steps to Reproduce (for bugs)

1. Start up 3.7.1 or 4.0 with starter data.
2. Once it's up and running, go to Configuration -> License Manager tab.
3. Click on "request a trial license" button.
4. Fill out the form for requesting a Trial License.
5. Error is thrown.

The application, despite it's generating the request Code, is not sending it properly to the trial request form because it cannot retrieve it from the actual payload we got from the LicenseResource class.

## Possible Solution
force-parse the string coming from LicenseResource to JSON and then pull the request code from it.

## Context
Reproduced consistently on 3.7.1 and 4.0 only. This is a follow-up of latest changes in LicenseResource class https://github.com/dotCMS/core/issues/10626

## Your Environment
* dotCMS 3.7.1, 4.0.
* Google Chrome, Firefox.
* macOS Sierra.
* Tomcat 8.0.18.
* Java JDK 6u80.
* Postgres 9.4.1.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10969

**Comment by bryanboza** [comment]
Seems, we still having problems here: https://www.screencast.com/t/2nXIwZqDT5

**Comment by bryanboza** [comment]
Fixed, tested in the last master-4.0 // H2 // FF
