### ISSUE TITLE
Prevent Directory Traversal in bundle uploader

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10974]
When we untar a bundle, we untar all the files in that bundle to the file system.  This potentially allows for a bundle to be uploaded that contains a file in a folder outside the bundle path.  This needs to be prevented in code.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10975

**Comment by bryanboza** [comment]
Fixed, tested after the fix #11002 and now works fine... Some minor improvement opened in a new card...
