### ISSUE TITLE
Need disable the actions button in site browser if you don't have permissions in the host 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10972]
The actions button in the site browser should respect permissions, then if you don't have this. this must appear as disabled to avoid confusions 

## Expected Behavior
If you don't have permissions in the host, the button should appear disabled

## Current Behavior
You are able to click the button but don't have actions, then looks like broken 
SC: https://screencast.com/t/hQF51T1o

## Steps to Reproduce (for bugs)
1. Login as limited user 
2. Go to site browser 
3. Try to click the action button (...)

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10980

**Comment by bryanboza** [comment]
Fixed, some improvements on #10985, #10984
