### ISSUE TITLE
Permission exception is broken the system when you are as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10984]
## Expected Behavior
We need a better handle of the permissions exceptions to avoid this kind of errors 

## Current Behavior
We are unable to catch the exception in the JSP file then this is generating a NPE in the logs... 
SC: https://screencast.com/t/khJLDZeu
ST: https://gist.github.com/bryanboza/f78ba2a8e7d33ee5a770ea88c9b9ef63

## Steps to Reproduce (for bugs)
1. Login as admin
2. Use the login as and login as Chris Publisher
3. Try to add a new folder 

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11001

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
