### ISSUE TITLE
Static Publishing can't be enabled even with Platform and Site License

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10983]
Just tested after latest commits on dotCMS 4.0

First I created an enteprise contract with Platform and Site license checked

![license](https://cloud.githubusercontent.com/assets/1569167/23760538/ac9ad072-04b5-11e7-8ccd-2fbf917f770f.png)

then I tried to use the license generator as a current client, but there is no platform option when requesting a license as a current customer:

![noplatformoption](https://cloud.githubusercontent.com/assets/1569167/23760641/f7d0fe9a-04b5-11e7-99b2-79212be9dc36.png)

So there is no way to configure static publishing, even after applying a prime license.

![config](https://cloud.githubusercontent.com/assets/1569167/23760664/1034ba4e-04b6-11e7-8f44-08558df37aa8.png)

**Comment by nollymar** [comment]
Platform license level was included. PR:  https://github.com/dotCMS/core/pull/10986

**Comment by DeanGonzalez** [comment]
Working now - tested both static and dynamic publishing - working for both
