### ISSUE TITLE
Hybrid push with Folder and Files not pushing files to dynamic environment

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10994]
Reproduced on lated dotcms 4.0 build

Easy to reproduce:

1) Set up a push publishing connection with Platform license
2) Set up a push publishing environment on both sending and receiving and on the sending server, make sure that the "Push to All Endpoints" property is set up.
3) On sending server, first set up two different dynamic endpoints (maybe an amazon instance and demo.dotcms.com)
4) Create a new folder and upload two images to the folder
5) Push publish the folder to the environment

Bug:  The first endpoint will receive folder and files, but the second will only receive the folder, but the files do not get sent.  Solution is that when we set up an endpoint with the "Push to All Endpoints" Push Mode, we need to dependency check all push objects for each ENDPOINT rather than the environment.

Work arounds
Putting the endpoints into two different environments OR Using Force Push delivers all assets to all endpoints - so there is a current way to get around the issue, but we should get "Push to All Endpoints" to work properly

**Comment by DeanGonzalez** [comment]
I imagine that this also exists in 3.7x since individual environments work fine, but I will verify tomorrow morning that this bug also exists on 3.7.2

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11334 and https://github.com/dotCMS/enterprise-2.x/pull/461

**Comment by DeanGonzalez** [comment]
Passed QA - good fix

**Comment by DeanGonzalez** [comment]
I tested QA today again, with two dynamic servers and one static server - folders and files made it to all three just fine, and quickly.
