### ISSUE TITLE
Updating Nav won't stop closing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10995]
So, I was looking at the starter with JasonS and he updated a Nav item name and WOW, it closed and updated on my screen too.  That is all good.  Once that happened, the nav would not stop closing, again and again.

See screencast:

![nav-wont-stop-closing](https://cloud.githubusercontent.com/assets/934364/23800394/3cd3d8a4-057a-11e7-86f3-816bae3e22f3.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/300

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
