### ISSUE TITLE
More frame busting!

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10996]
So, we catch people who are not logged in and go to the /c path.  We don't do well with people who have already logged in or have remember me checked.  You can end up at screens like this:

---

![screen shot 2017-03-10 at 11 17 52 am](https://cloud.githubusercontent.com/assets/934364/23803165/a73363dc-0583-11e7-8710-69529352b679.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10997

**Comment by jgambarios** [comment]
@bryanboza please make sure the edit mode works properly after this change.

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MSSQL // FF
