### ISSUE TITLE
Fixing UserAPITest

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11003]
Fixing UserAPITest

## Expected Behavior
New changes on Containers should not break the replacement user on the UserAPITest

## Current Behavior
The replacement on the containers live version is not working, it seems the cache is having a old one user version.

## Possible Solution
Invalidate the container live node associated to the original container.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11004
