### ISSUE TITLE
Pushing Bundles "for Unpublish" failing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11002]
tested in dotcms 4.0

I created a bundle and downloaded for publishing and unpublishing.  I tried to make sure there were many objects in the bundle so I included:

- A New Content Type
- Categories (new content type has a new category field)
- A new Container
- A new template that uses the new container
- a new page that uses the new template
- A piece of content on the page

Here is the bundle that uploads for publish just fine:
[0c377a4a-7255-4c53-a719-b605d35bb2ac.tar.gz](https://github.com/dotCMS/core/files/835037/0c377a4a-7255-4c53-a719-b605d35bb2ac.tar.gz)

Here is same bundle that fails on upload for unpublish:

[7910d2ec-6b29-4941-9517-5e5a79f4fd40.tar.gz](https://github.com/dotCMS/core/files/835038/7910d2ec-6b29-4941-9517-5e5a79f4fd40.tar.gz)

**Comment by oarrietadotcms** [comment]
error in the log: https://gist.github.com/oarrietadotcms/bc7397875a0ba796d3d7d6881c81d8fa

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11023

The error below is displayed in the dotcms.log when you upload the first bundle, but I double checked and the page is created and published without any problems. If necessary we can create a new issue with this weird error message.

ERROR business.ESContentletAPIImpl: Cannot publish related HTML Pages.  Fail

**Comment by bryanboza** [comment]
Fixed, Tested on master-4.0 // Sender: MySQL // Receiver: Postgres and now works fine.... A minor issue reported here: #11044
