### ISSUE TITLE
Vertical scrollbar in dojo portlets is hidden under the fixed div

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11007]
See this video for an example:

http://www.screencast.com/t/Wy9ki7oodUT

Edit a content -> news item to see for yourself.  If you move the sidebar over 10 or so pixels, then you can see it (but this is a hack)
```
.content-edit__sidebar {
  background-color: #FAFAFA;
  border-left: solid 1px #ECEDEE;
  height: 100%;
  padding: 16px;
  position: fixed;
  right: 10px;
  top: 0;
  width: 220px;
} 
```

reference:
http://stackoverflow.com/questions/13028584/browsers-scrollbar-is-under-my-fixed-div

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11020

**Comment by bryanboza** [comment]
Unable to reproduce with the last changes... Fixed
