### ISSUE TITLE
Resize iframe when windows resize

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11017]

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/301

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // W10

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/304

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // W10
