### ISSUE TITLE
Add new content styling issues

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11016]
We are having styling problems using the Add New Content in the Angular shell

![](https://content.screencast.com/users/jgambarios/folders/Snagit/media/bc5e4ac8-cfc3-44ac-9b7d-733a680ea7ac/2017-03-13_10-58-06.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/299

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
