### ISSUE TITLE
Style user toolbar dropdown component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11019]
Make it look like this one.

<img width="288" alt="screen shot 2017-03-13 at 11 56 16 am" src="https://cloud.githubusercontent.com/assets/751424/23919797/e52d72d0-08bd-11e7-91df-2e9bf099c8f7.png">

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/302

**Comment by bryanboza** [comment]
Hey @fmontes can you add more info here to make sure what are we testing please??? And to see  which areas could be affected by this change...

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MSSQL // FF
