### ISSUE TITLE
Initial Host Selector is ALPHA and does not resolve host properly

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11022]
In the new host selector, for a first time user, we are returning the resolved host - instead, we are just sending back hosts in alpha order.  We should work like this - if no default host is selected, we should follow our normal host resolution procedure and set the initial default host.

---
![screen shot 2017-03-13 at 3 37 06 pm](https://cloud.githubusercontent.com/assets/934364/23872159/9a6a6f38-0803-11e7-88a7-01c03f5759d7.png)

**Comment by jgambarios** [comment]
On first load we need to use https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPIImpl.java#L124 in order to identify what would be the selected site.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11037

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // postgres // FF
