### ISSUE TITLE
UI is displaying more than 5 notifications

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11024]
Related to #9397

When you execute certain processes many times such as a reindex or delete a user, the UI is trying to list all the notifications generated after the execution, however it should only list 5 notifications as per #9397.
When resolution doesn't allow to display the whole list, the notifications' list gets cut at the bottom.

(In this example, I executed the reindex 11 times)
![image](https://cloud.githubusercontent.com/assets/8741846/23873005/23118aaa-07f6-11e7-8665-7c09b0585ca8.png)

## Expected Behavior
UI should only load 5 notifications as per #9397

## Current Behavior
UI is trying to list all the notifications after a reindex or delete a user

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to System> Maintenance> Index
3. Run the reindex more that 5 times 
4. You will see the UI is trying to list all the notifications
5. If you create several users and try to delete them, you will see the same behavior with the notifications

## Your Environment
* dotCMS version used: Master-4.0
* Commit a8b16650fe907cedf24b8d477ec6a42d930f8b00
* Browser Name and version: Firefox v45.0.1
* Operating System and version: Mac OS 10.10
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8
* Database and version: MySQL 5.6.35

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/305

**Comment by bryanboza** [comment]
Still having problems here: https://screencast.com/t/PWHES0sRWsXd

**Comment by bryanboza** [comment]
The same problem: https://screencast.com/t/rVCAb9LmxE

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/306

**Comment by bryanboza** [comment]
After the last changes we are having a lot of problems with notifications... 

- [ ] If you have one notification and mark as read, when you generate a new notification the system shows two new notification, the old one and the new one 

- [ ] The notifications count never is more than 5, we should show only the last 5 notifications, but the count should continue

- [ ] If you mark the notifications as read and then logout, when you login again you have all ones as new notifications 

Here the SC: https://www.screencast.com/t/Wdw47K3WPQp

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/308

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // H2 // FF
