### ISSUE TITLE
Minor UI tweaks part2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11029]
#11024 

- [x] Need resolve the icon problems in the TASK portlet: https://screencast.com/t/XZD31K8IGW // https://www.screencast.com/t/zEZrKas46
^^^ Fixed
https://github.com/dotCMS/core/pull/11036

- [x] Workflow task --> Attached files  need styling help: https://screencast.com/t/ADpA6ewngk

- [x]  Site Browser > Edit site > Permissions tab / more space between Apply Changes btn and checkbox, Scroll https://screencast.com/t/rpu1HWgmj1T

- [ ] System > Roles and tabs > users tab > action edit role  isn't working https://screencast.com/t/Wd8t8gLR4

- [x] License portlet components need styling help, also need a static size : https://screencast.com/t/tdeAjnJFkfsc

- [x] Delete confirmation button need appear in red: https://screencast.com/t/1X0Z7tx10

- [ ] Delete button in the Status/History on publish queue need be in red: https://www.screencast.com/t/RS56U2dPOYdL

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11036

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11053

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11096

**Comment by bryanboza** [comment]
Still having problems with the point #5 on FF... https://screencast.com/t/63r4ckbCy

**Comment by woontsoudev** [comment]
Was fixed on PR https://github.com/dotCMS/core/pull/11258
