### ISSUE TITLE
Permissions: Avoid unnecessary flush of Cache regions when permissions are applied

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11021]
Once permissions are applied to permissionable objects (sites, folders, contents, etc), the application tracks down all assets where permissions were updated and remove them from cache, however, depending on the amount of assets being processed at a specific permissioning task, all permission cache is flushed, even for other assets which permissions were never changed.

## Current Behavior
If a large set (more than 200 assets) require their permissions to be updated in cache after they were updated on the DB, all the Permissions Cache is flushed

- https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java#L1515-L1523
- https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java#L2801-L2810

This behavior is the same for several permission-related operations in the background, like cascading permissions, where multiple flushes are requested even if they're not needed.

- https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java#L2801-L2810

For example, cascading permissions trigger a flushCache at the end of the job's execution. All items that are handled on the savePermission method already cleans the cache for each item, so there's no need to flush all caches.

- https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java#L1805

## Possible Solution
The MAX_IDS_CLEAR property sets that permissions on cache should be removed if the amount of assets being processed are less than 200 assets. Other than that, a flush of all caches is requested. The ideal solution is to delete permissions on cache for assets that are being processed by the Permission API/Factory, instead of forcing a flush of an entire region that will end up consuming all server resources once new permissions (whether they were edited or not) are requested on frontend requests/

## Steps to Reproduce (for bugs)

1. Have 2 sites with more than 1000 contents under each site.
2. Go to one of the sites and reset/apply new permissions.
3. Permissions-related cache regions are flushed for all sites, even if the other site never got its permissions updated.

## Context
Follow-up to https://github.com/dotCMS/core/issues/10084
Related to https://my.dotcms.com/tickets/detail.dot?id=6d588f76-1ac9-4b8b-9274-d47530e4f6ec

## Your Environment

* dotCMS 3.5.1, master-4.0.
* Any browser
* Any OS.
* Tomcat 8.0.18.
* Oracle Java JDK 8.
* Postgres DB.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11034

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11155

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // MySQL // FF, tested applying cascade permissions in a host with 100 files assets, works as expected.
