### ISSUE TITLE
Permissions: Glitches in UI don't allow user to successfully cascade permissions

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11033]
If we're assigning permissions to a Site, folder or any other permissionable object, we should be able to add as many roles/users as possible in order to allow granular access and privileges to roles/users for specific assets and potential operations over them. 

## Expected Behavior
Regardless of the amount of roles assigned to the Permissions Tab, applying and cascading permissions to a Site should reset permissions for all children assets so they inherit permissions directly from the Site.

## Current Behavior
It seems there is a bug in the UI that only allows the user to cascade permissions for the current active role/user. Other collapsed roles/users on this view are not taken into account, so permissions are not set and therefore not inherited to children assets. 

## Possible Solution
Inspect if checkboxes are checked for every single role/user added to it and then apply permissions as expected.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. After starting up master-4.0, go to Sites and edit demo.dotcms.com site.
2. On Permissions Tab, check all "View" boxes for CMS Anonymous role.
<img width="1544" alt="screen shot 2017-03-14 at 1 02 57 pm" src="https://cloud.githubusercontent.com/assets/1717110/23912898/a28cbb8a-08b7-11e7-89e6-79a1481befe1.png">

3. Add "Contributor" role to it and then check "View" boxes for Folders, Containers and Templates. Leave this item open/active, so CMS Anonymous role looks "collapsed"
<img width="1542" alt="screen shot 2017-03-14 at 1 03 08 pm" src="https://cloud.githubusercontent.com/assets/1717110/23912906/a69c6bee-08b7-11e7-8ffa-e1404db1d330.png">

4. Check on "reset all children permissions to match the above" box., so all children assets will inherit these permissions set.
5. Save permissions. Once permissions are applied, frame is refreshed. Go back to Site's Permissions tab.

This is how each role's permissions look after permissions are applied to Site: 

CMS Anonymous role:
<img width="1537" alt="screen shot 2017-03-14 at 1 03 41 pm" src="https://cloud.githubusercontent.com/assets/1717110/23912941/c8decad0-08b7-11e7-87b8-b8122c8edbd4.png">

Contributor Role: 
<img width="1541" alt="screen shot 2017-03-14 at 1 03 43 pm" src="https://cloud.githubusercontent.com/assets/1717110/23912950/cf0406e6-08b7-11e7-884a-89cd0ecdfabe.png">

If we look at permissions for /about-us/ folder, we see two issues: 

1. CMS Anonymous role is not inherited.
2. Contributor role is there, but there's no indication of which permission level is set to it, unless we click on "Reset Permissions" button: 

<img width="1535" alt="screen shot 2017-03-14 at 1 13 41 pm" src="https://cloud.githubusercontent.com/assets/1717110/23913102/46672808-08b8-11e7-8e4b-51124f26a774.png">

## Context
As a follow up of #11021, this issue surfaced during local tests, however they're unrelated to the WIP on this ticket, since it can be reproduced on demo4 site. This bug will basically make the permissions inheritance useless for sites with multiple access levels set through roles.

## Your Environment

* dotCMS 4.0 
* Google Chrome Browser.
* macOS Sierra (app and db).
* Tomcat 8.0.18.
* Java JDK 8.
* Postgres, H2 databases.

**Comment by wezell** [comment]
This might be on purpose because it was such a heavy op.   Try this.  Set
all your permissions on your content object without cascading.  Then once
you have it set, hit the cascade button.  That should make them all cascade
at once.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11043

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // Postgres // FF
