### ISSUE TITLE
Clean up unused stuff

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#11038]
- [x]  Remove src/com/dotcms/plugin/saml/v3/interceptor/*.java.txt
- [x]  Remove custom web.xml deployer in OpenSaml3PluginDeployer.java
- [x]  Remove src/test/com/dotcms/plugin/saml/v3/*.txt if they are not or will not be used
- [x]  Remove SOAP bindings and dependencies

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/plugin-dotcms-openSAML3/pull/9
