### ISSUE TITLE
Rename Integrity Checker tab from "roles" to "User Roles"

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11031]
This is for having a better understanding of what we are really solving with the integrity checker.

**Comment by dsilvam** [comment]
@DeanGonzalez suggests relabeling to "Roles/User Roles"

**Comment by DeanGonzalez** [comment]
I suggest "Roles/User Roles"

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/11048
