### ISSUE TITLE
Unable to load sites in the dotSiteSelector after upgrade 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11040]
When you upgrade dotCMS from any version, by default you don't have indices, the the system isn't loading the sites

## Expected Behavior
After upgrade and then reindex we should reload the dotSiteSelector component to see all the sites 

## Current Behavior
After the reindex finish the system isn't adding the sites to the web component 

## Steps to Reproduce (for bugs)
1. Add new sites from the old version 
2. Upgrade from any version
3. Reindex
4. Try to select different hosts 

## Your Environment
Tested upgrading on macOSX

From: dotcms_3.7 // MSSQL 
To: dotcms_4.0 // MSSQL

**Comment by bryanboza** [comment]
FYI: You need refresh the browser window to see the sites

**Comment by jgambarios** [comment]
This is because we don't fire an event to refresh the Site Selector on reindex.
