### ISSUE TITLE
Invalid portlet name after upgrade from 2.5 version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11045]
We are having an invalid portlet that don't have key after upgrade from 2.5 version 

## Expected Behavior
We should add a new key for this portlet or delete this one 

## Current Behavior
We don't have key to this portlet 

<img width="1440" alt="img1" src="https://cloud.githubusercontent.com/assets/2641437/23936811/bdbe7a08-0919-11e7-8cb7-d722711e234e.png">

## Steps to Reproduce (for bugs)
1. Start dotcms_2.5
2. Create some pages and add content to it 
3. Upgrade to dotcms_3.7 
4. Migrate all the pages to content 
5. Upgrade to dotcms_4.0 
6. Login and look the portlet list in the menu 

## Your Environment
Tested upgrading from 2.5 to 3.7 and then 4.0 // Postgres // FF

**Comment by wezell** [comment]
You need to delete it from your layouts.
