### ISSUE TITLE
Better default SAML settings

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#11052]
Set per-Site SAML config defaults as follows if not specifically configured:

* assertion.customer.endpoint.url: service.provider.issuer + "/dotsaml3sp"
* protocol.binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
* assertion.resolver.handler.classname: "com.dotcms.plugin.saml.v3.handler.HttpPostAssertionResolverHandlerImpl"
* keyentryid: "dotsaml3sp"
* keystore.entry.password: keystore.password
* want.assertions.signed: "true"
* authn.requests.signed: "true"
* verify.assertion.signature:"true"
* isassertion.encrypted: "false"
* clock.skew: "10000"
* message.life.time: "20000"
* roles.attribute: "authorizations"

Re: #10903 #11038

**Comment by oarrietadotcms** [comment]
commits: 

1. https://github.com/dotCMS/plugin-dotcms-openSAML3/commit/2231951a6a04e518cbcbdfe10dcddd33b2d21295
2. https://github.com/dotCMS/plugin-dotcms-openSAML3/commit/7f3cfa64f68f7ecd98a66512dcac009a399752fa
