### ISSUE TITLE
Problem with the portlet URL when the first portlet is rules

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11051]
When you define your first portlet is rules engine, when you login, the system is trying to find a weird URL and shows a 404 error

## Expected Behavior
We should load our first portlet without problems 

## Current Behavior
The system shows a 404 error and isn't finding the portlet... 

SC:  https://screencast.com/t/dsAhN6WsIfX

## Steps to Reproduce (for bugs)
1. Login 
2. Go to roles and tabs and define the sort order to the marketing portlet to "0"
3. Logout 
4. Login again 

## Your Environment
Tested in the last master-4.0 // H2 // FF & Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/309

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // MySQL // FF
