### ISSUE TITLE
Get the immutables lib building in Intellij

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11069]
Apparently the Immutables lib we are using for 4.1 does not play well with Intellij. We need to figure out the process of how we can use it or perhaps explore other options like getting rid of the annotations and having the generated src in our code base.

**Comment by jgambarios** [comment]
As reference: https://immutables.github.io/apt.html

**Comment by wezell** [comment]
Here is another reference:

https://github.com/immutables/immutables/issues/404

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/11148
https://github.com/dotCMS/enterprise-2.x/pull/455
https://github.com/dotCMS/license/pull/45

**Comment by jgambarios** [comment]
This thicket was just the initial work for https://github.com/dotCMS/core/issues/11120
