### ISSUE TITLE
Further validations on SAML config field on Site

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11067]
Desired validations when saving the SAML config on the site field:

idp.metadata.path: Does it exist? Can we open it? Is it valid xml?
keystore.path: Does it exist? Can we open the file? Does the keystore password work for it? Does it contain the keyentryid? Can we open the key with the key entry password?

From comment: https://github.com/dotCMS/core/issues/10903#issuecomment-286817223
when we re-init the SAML filter on the Site save post-hook we need to catch if there is some SAML config but there is missing critical SAML config and log the init failure appropriately

The critical config elements that are always needed are:
service.provider.issuer
idp.metadata.path
keystore.path
keystore.password
keystore.entry.password (maybe default to keystore.password if !defined)

Everything else we should be able to have usable defaults

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/plugin-dotcms-openSAML3/pull/11

**Comment by oarrietadotcms** [comment]
PR after QA: https://github.com/dotCMS/plugin-dotcms-openSAML3/pull/13

**Comment by nollymar** [comment]
Passed QA
