### ISSUE TITLE
Can't display back-end after upgrade to 3.7.1

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#11063]
After we upgraded dotCMS from 3.3.2 to 3.7.1 (windows, MSSQL) we couldn't open the back-end anymore after logging in. DotCMS was working, it was just the back-end that didn't work.

After some investigating we noticed that the page rendering stopped while rendering the menu and we could see a NullpointerException in the wrapper log. The problem was layout_005fportal_jsp.java line 1340. It is the last line of this code:

```java
boolean isSelectedTab = (layout != null && layouts !=null && layout.getId().equals(layouts[l].getId()));
PortletURLImpl portletURLImpl = new PortletURLImpl(request, portletIDs.get(0), layouts[l].getId(), false);
String tabHREF = portletURLImpl.toString() + "&dm_rlout=1&r=" + System.currentTimeMillis();

Portlet portlet = (Portlet) APILocator.getPortletAPI().findPortlet(portletIDs.get(0));
Object object = Class.forName(portlet.getPortletClass()).newInstance();
```
(The source is in the categories/sub_nav.jsp)

It seems that the custom plugins that we had before the upgrade caused an issue after the upgrade. DotCMS couldn't render the menu (and thus the page) because of a missing plugin/portlet.

## Expected Behavior
We would expect that the menu would render correctly but that (maybe) the detail page of a menu item would return an error. That is how dotCMS used to work.

## Current Behavior
The entire back-end does not render. It is possible to open a page in the edit mode though.

## Known Workarounds
Remove the portlet references from the cms_layouts_portlets table.

## Steps to Reproduce (for bugs)
We were not able to reproduce this on the demo site since we can't upload plugins with portlets there (not allowed), and locally with a clean dotCMS with H2DB in Windows we didn't have this issue. Therefore we think it has something to do with upgrading or MSSQL. 

## Context
This problem caused our upgrade to take much more time (over 20 hours more) than what would normally be the case. Also we don't understand why the dotCMS back-end would not render when it is just missing a plugin. The menu should just render HTML and not check for any existing classes/logic.

## Your Environment
* dotCMS: 3.3.2 -> 3.7.1
* Browser Name and version: all browsers
* Operating System and version: Windows Web Server 2008 R2
* Java Brand and version: 1.8 v121
* Database and version: MSSQL 11.0.6248.0

**Comment by wezell** [comment]
Xander - sorry this took so long, but this is a dying problem with the upcoming 4.0 release.  The subnav.jsp is no longer used

**Comment by wezell** [comment]
And when I say the upcoming 4.0 release, I mean within the week :)
