### ISSUE TITLE
DateTime and Time fields are forcing the seconds to be always 00

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#11071]
If you have a content type with a Time or DateTime fields, then the seconds are always set to 0, those fields are only taking in count the hour and minutes when they are changed.  
## Expected Behavior

Some clients need to be able to see the difference of seconds on those fields
## Current Behavior

If you have a content type Test with a time and date time field and you call the content rest api 
If /api/content/render/false/query/+contentType:test

You will see that always for any value you put in those fields always the seconds are set to 00.0 the only exception is the mode date
"modDate":"2017-03-16 10:20:02.068","mytime":"1970-01-01 17:15:00.0", "myDatetime":"2017-03-16 23:58:00.0"
## Possible Solution

Remove the inputs condition where the seconds are set always to 0

## Steps to Reproduce (for bugs)

1. Create a content type with some fields including a date time and time fields
2. Create some contents for that content type
3. Validate if the date time and time fields are setting different values for the seconds
4. The seconds shouldn't be alway equals to 0

## Context
This issue was reported here https://my.dotcms.com/tickets/detail.dot?id=f5d7842b-4395-4451-b40b-bae8e077e722

## Your Environment
Originally tested on dotCMS 3.6.2

* dotCMS version used: 3.6.2, 3.7.X, 4.0

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11564

**Comment by jgambarios** [comment]
We found an issue on the REST api where the seconds were not saved for Datetime fields and the problem was fixed.
For the save of content from the UI we made NO changes as the datetime/time fields components does not have seconds.

**Comment by jgambarios** [comment]
**Note to QA:** Please check the above comment https://github.com/dotCMS/core/issues/11071#issuecomment-301155642

**Comment by nollymar** [comment]
A good improvement would be to include seconds for the others date/time formats defined in the class, for example: MM/dd/yyyy hh:mm aa

**Comment by nollymar** [comment]
The doc needs to be updated as well: https://dotcms.com/docs/latest/save-content-using-rest-api#headerFormats

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11612/files

This is the updated list of allowed date and date/time formats for values sent via REST:

* "yyyy-MM-dd HH:mm:ss"
* "yyyy-MM-dd HH:mm"
* "d-MMM-yy"
* "MMM-yy"
* "MMMM-yy"
* "d-MMM"
* "dd-MMM-yyyy"
* "MM/dd/yyyy hh:mm:ss aa"
* "MM/dd/yyyy hh:mm aa"
* "MM/dd/yy HH:mm:ss"
* "MM/dd/yy HH:mm:ss"
* "MM/dd/yy HH:mm"
* "MM/dd/yy hh:mm:ss aa"
* "MM/dd/yy hh:mm:ss"
* "MM/dd/yyyy HH:mm:ss"
* "MM/dd/yyyy HH:mm"
* "MMMM dd, yyyy"
* "M/d/y"
* "M/d"
* "EEEE, MMMM dd, yyyy"
* "MM/dd/yyyy"
* "hh:mm:ss aa"
* "hh:mm aa"
* "HH:mm:ss"
* "HH:mm"
* "yyyy-MM-dd"

**Comment by bryanboza** [comment]
Tested every one of those formats... Here some improvements 

- [ ] In cases when you don't specify the year, we should get the current year ("d-MMM" //  "M/d"), right now we use 1970 by default 

- [ ] With this specific case ("MMMM dd, yyyy"), we have an error if you don't leave a blank space after the coma (","), log: https://gist.github.com/bryanboza/2dd364be16b17e09eadf49d549d061da

- [ ] Cases when you don't send the date, just the hour, we should take the current date (hh:mm:ss aa // hh:mm aa // HH:mm:ss //  HH:mm // hh:mm:ss aa)

- [ ] Finally we need add something in logs when you add a new content via REST API

**Comment by bryanboza** [comment]
Fixed, now we save seconds when use the REST, some improvements related to the date/time formats here #11661
