### ISSUE TITLE
Add javadoc to gradle core

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11089]
Add javadoc

We need to add to core.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11091

**Comment by bryanboza** [comment]
Unable to generate the javadoc in master-4.1 
Here the stacktrace: https://gist.github.com/bryanboza/07f5ba3a1486bfe0a06c8fd0c9da2fc6

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11480

**Comment by bryanboza** [comment]
Fixed, tested on release-4.1 and now we can generate the javadoc without problems
