### ISSUE TITLE
Performance Improvement to DotTemplateTool and liveMode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11084]
After the velocity caching work, running some benchmarks:
---
Before these changes:
https://gist.github.com/wezell/90741793113f270586a22365473d668c

After these fixes:
https://gist.github.com/wezell/708b41230289b3a657b4547185c80f28

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11183

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // postgres // Chrome... Tested with some workaround templates and everything looks ok
