### ISSUE TITLE
Unable to start master-4.1 in H2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11095]
We are having some problems when you try to start master-4.1 using H2 as database 

## Expected Behavior
We should be able to start in any of the supported databases without problems 

## Current Behavior
We are having an error and the system isn't starting 
Here the SC: https://gist.github.com/bryanboza/6a8ffc0fd869e9fe024c88af4426884f

**FYI:** Works fine in other DB

## Your Environment
Tested on master-4.1 // H2

**Comment by jtesser** [comment]
@nollymar @dsilvam @wezell this was one of my errors from last week

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11203

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2
