### ISSUE TITLE
NPE trying to upload single image/file

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11102]
We are having a NPE error when you try to upload a single image in master-4.1, this is breaking the system and we are showing an error at UI level 

## Expected Behavior
We should be able to upload images without problems

## Current Behavior
We are having a NPE and this breaks the system 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to site browser 
3. Try to upload some single image or file 
![r1](https://cloud.githubusercontent.com/assets/2641437/24224510/1bfc6db6-0f21-11e7-98fd-ad2a42dd6aba.gif)

Here the log: https://gist.github.com/bryanboza/ce124ba6b471d3aca0f7171fdb11b48e

## Your Environment
Tested on master-4.1 // MySQL // FF

**Comment by jgambarios** [comment]
Closed as is a dup of https://github.com/dotCMS/core/issues/11097
