### ISSUE TITLE
100% CPU usage when disconnect network with dotCMS tabs open in browser

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#11119]
When I shut off my network with dotCMS tabs open in my browser, the browser process(es) with the dotCMS tab(s) sometimes goes to 100% CPU usage.

## Expected Behavior

The browser should, in the worst case, log you out of the dotCMS backend (this is what happened in 3.7.x).

I think that may also be the ideal case, since it provides the best security.  However another consideration is that if a user has unsaved content in a screen (like the content editing screen) and loses connection, they'll lose their changes if they're logged out of the backend automatically - and in an ideal world, this wouldn't happen (otherwise loss of network connection for unpredictable reasons could cause loss of work).  Not sure there's an easy way to deal with this, but it's something to consider.

## Current Behavior

When the network is disconnected sometimes the browser process goes to 100% CPU usage on 1 core.  Note that in FF I've seen this every time (so far), but in Chrome it's been intermittent.

## Possible Solution

Not a possible solution, but I'm wondering if this might have something to do with the JWT authentication, since in 3.7.x you would be automatically logged out, but now it can cause high CPU load (is the thrashing from the JWT code trying to maintain a connection or reconnect?).

## Known Workarounds

Close the browser tabs with dotCMS screens open.

**Note:**

* The high CPU usage stops as soon as the dotCMS tabs are closed, even if the other browser tabs (displaying sites other than the dotCMS backend) remain open.
* Closing the non-dotCMS tabs does not solve the CPU usage problem; only closing the dotCMS tabs does.

## Steps to Reproduce (for bugs)

1. Open one or more dotCMS backend screens in the browser.
    * At this point, it doesn't seem to matter which dotCMS screen is open in the browser, since it's happened with a number of different tools.
2. Shut off your network connection.
Result: The browser process goes to >= 100% cpu on 1 core (~13% CPU usage on a quad-core with hyperthreading).

## Context

Although this isn't a show-stopper, it's obviously undesired behavior.

## Your Environment
* dotCMS version used: 4.1.0 release (authoring.dotcms.com)
* Browser Name and version:
    * Chrome v51.0.2704.79
    * Firefox v42.0
    * **Note:** So far, this has been 100% reproducible on FF, but only intermittent on Chrome.  I'll try to update FF and see if a newer version behaves any different.
* Operating System and version: Win 7 Enterprise
* Application Server and version: Tomcat (distro on auth)
* Java Brand and version: 1.8 (auth)
* Database and version: Postgresql (auth)

**Comment by john-thomas-dotcms** [comment]
A few on this:

1. Retries should not happen in an un-delayed loop (pretty much ever I think, though I might be missing some use cases).
2. It might make sense to try relatively quickly for some initial period of time, then back off to a slower retry interval.
    * Basically assume the connection went down and slow down to a reconnect interval.
3. Regardless of the retry interval, for security reasons, the connection should probably be automatically logged out (and stop trying completely) after some period of time.
    * Ideally this would be configurable, but for now at least this would probably be on the order of several minutes.
4. It seems like we should have a standard pattern for this, if we don't already.
5. It might make sense to implement some kind of an API call wrapper to implement whatever pattern we decide on for this.
    * I'm guessing that right now we're handling this different in many different places where we're making calls.
    * A wrapper that implements a standard pattern would allow us to lazily update all API calls to ensure we have consistent behavior, and would give us a single point to be able to either adjust the timeouts and retries or insert user-configurable parameters for these.

**Comment by wezell** [comment]
@john-thomas-dotcms I agree with all that but I am hesitant to add too much complexity at this point around all our apis.  I think this is limited to our websocket (can you or @brentgriffin confirm) impl.  I am ok with it timing out and going to login for 5.0

**Comment by brentgriffin** [comment]
I too observed this behavior but seems to be 100% reproducible (at least 4 of the 4 times I have tried) - In addition to the excessive CPU being used by the browser tab (in my case 70%) there is also 40K per second network traffic being sent to the machine that was hosting dotCMS.

My steps to recreate:
1.  Login to dotCMS backend
2. Leave backend page open and stop dotCMS server
3. Observe cpu usage and network traffic

It appears to be requesting system events via the /api/ws/v1/system/events API
e.g. - in less than a minute the following request was sent over 1800 times:
![image](https://user-images.githubusercontent.com/3208956/41854259-5e06580e-7855-11e8-82bc-e977d9170ba1.png)

**Comment by wezell** [comment]
I believe we are using socket.io - see our options here:
https://socket.io/docs/client-api/#manager
