### ISSUE TITLE
Make dojo widgets works on IE11

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11111]
This is the first step to support IE11 on 4.0

## Expected Behavior
- Make sure all the widgets in the dojo theme looks and work correctly on IE11

## Current Behavior
- Some widgets have cut text, like: textfields, some selects etc..

## Possible Solution
- Style, style, style

**Comment by woontsoudev** [comment]
https://github.com/dotCMS/dotcms-dojo-theme/pull/27
