### ISSUE TITLE
Improve error message when failing to write the ServerID

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#11121]
There are two places were the server id is written: inside the DYNAMIC_CONTENT_PATH and the hearbeat information inside the ASSETS. When there's a problem writing this file, the same error is shown:

_ERROR... Could not write Server ID to file system java.io.FileNotFoundException_

## Expected Behavior
A different error message should be shown for each particular case

## Current Behavior
The same error is shown for both cases

## Your Environment
* dotCMS version used: 3.3.1, current
* Related: https://my.dotcms.com/tickets/detail.dot?id=b7eca9b9-4c26-478f-be53-0f523cef7208

**Comment by wezell** [comment]
dupe #9257
