### ISSUE TITLE
Error thrown when Adding a HostFolderField

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#11128]
## Expected Behavior
If a Content-type doesn't have a HostFolderField you should be able to add one without any issues.

## Current Behavior
If you try to add a HostFolderField to a Content-type without checking the User Searchable option error is thrown. This is because is expected that field is Indexed and without that option the field is not indexed. We need to decide if we want this field always be indexed or to remove the precondition regarding if the field needs to be indexed.

Log: https://gist.github.com/erickgonzalez/1b7eb51311c1f43d6df7b94092920bd1

Precondition: https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotcms/contenttype/model/field/HostFolderField.java#L22

## Steps to Reproduce (for bugs)
1. Go To Types & Tools
2. Create a new Content-Type
3. Add a new Host or Folder Field
4. Do not check any of the options (Required and User Searchable)

## Your Environment
* dotCMS version used: master-4.1
* Browser Name and version: Chrome and FF
* Operating System and version: MacOs
* Database and version: Postgres

**Comment by erickgonzalez** [comment]
We are experiencing the same behavior with the Tag Field.

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/11150

**Comment by bryanboza** [comment]
Fixed... tested on master-4.1 now the field appear as indexed by default
