### ISSUE TITLE
Support IE11

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11133]
### core-web:
- [x] After login the dashboard appears in blank: (https://github.com/dotCMS/core-web/commit/938c10456eeab49025a4e00f4523f49a3a6ec9ab)
    - https://www.screencast.com/t/Ue5XAnOOlq
- [ ] All routes > if you refresh the browser page doesn't load correctly, an js errors appears:     
    - https://www.screencast.com/t/evhK5PoRBWUF
    - https://www.screencast.com/t/gwYd5J14WV
    - https://www.screencast.com/t/xrNVEA7VLWy
- [x] We are loosing the session after refresh the browser
- [x] Notifications needs styling help (https://github.com/dotCMS/core-web/commit/d4d7b0dea6e5a22670779aed1aa80ef96e84d1b8)
    - https://www.screencast.com/t/GtyttvHHiN5
- [x] Unable to reproduce the dotCMS logo animation loading the login portlet  (https://github.com/dotCMS/core-web/commit/328ffe89e8ce6874e7a8788bfefa370802cfa24a) https://www.screencast.com/t/kurRdT4Dn33

## core:
- [x] Task > Edit content - action btn / its not working: (https://github.com/dotCMS/core/pull/11177)
    - https://www.screencast.com/t/yQaarrenpee
- [x] Site browser > Save content error and js errors: (https://github.com/dotCMS/core/pull/11177)
    - https://www.screencast.com/t/ZLM98pC8
- [x] Content search > Edit content / js errors: (https://github.com/dotCMS/core/pull/11177)
    - https://www.screencast.com/t/vXGyuG9h0IG
- [ ] ~~Types and tags > Categories / js error~~: (*happening in all browsers in 4.1*)
    - https://www.screencast.com/t/nyGAGlJfwqnN
- [x] Unable to upload a license pack:(**already fixed**)
    - https://www.screencast.com/t/IUfUdLuxJSHl
- [ ] Need remove the horizontal scroll on calendar iframe: (https://github.com/dotCMS/core/pull/11177 - https://github.com/dotCMS/dotcms-dojo-theme/pull/28)
   - https://screencast.com/t/hfESTGFQTZZV
- [x] Unable to see the bad links in the link checker portlet: (**already fixed**)
https://screencast.com/t/XXAqOrPMHTph... **FYI: Works in other browsers** 

## Could be both:

- [ ] ~~Unable to receive the time machine notification automatically after finish, you need click to any other portlet in the angular menu to receive the notification **(need to check the long pooling thing)**~~ (*happening in all browsers in 4.1*)

**Comment by bryanboza** [comment]
More UI problems on EI11:

- [ ] Unable to upload a license pack: https://www.screencast.com/t/IUfUdLuxJSHl
