### ISSUE TITLE
Refactor Reorder-Menu-Items portlet to not POST reordered menu-items over query-string

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11135]
Reorder-Menu-Items portlet is relying on query-string for sending reordered menu-items. **This may cause error "HTTP code 414 Request-URI Too Large" from NGINX (on dotCMS Cloud servers) at the moment the reordered menu-items are saved and when the menu-items tree is quite big**. Instead, the POST request should send the reordered menu-items over request-body.

## Expected Behavior
Reorder-Menu-Items portlet should be able to save reordered menu-items when the menu-items tree is big. That can be achieved by having Reorder-Menu-Items portlet should sending the reordered menu-items tree over POST request body

## Current Behavior
Reorder-Menu-Items portlet is not able to save a big tree of reordered menu-items. When NGINX is configured in front of dotCMS's tomcat and upon clicking on the "Save Changes" button on Reorder-Menu-Items portlet, the POST request fails with error "HTTP code 414 Request-URI Too Large" from NGINX. This is caused by the fact that the reordered menu-items tree is submitted over POST request query-string

<img width="1440" alt="screen shot 2017-03-24 at 4 05 07 pm" src="https://cloud.githubusercontent.com/assets/22307536/24315692/307c243c-10ae-11e7-8bbc-b61af4be0d6c.png">

## Steps to Reproduce (for bugs)
The behavior with which Reorder-Menu-Items portlet sends reordered menu-items over query-string can be reproduced on latest dotCMS 4.0 demo site (https://demo.dotcms.com) with following steps:
1. Log into https://demo.dotcms.com
2. Go to Site Browser and click on folder "services"
3. Double click on page "first-time-investors"
4. Click on button "Lock for editing" at top-right side
5. Click on "Reorder Menu" icon on menu at left-hand-side
6. On Reorder-Menu-Items portlet, click on button "Save Changes"
7. Inspect query-string generated for previous POST request and confirm that big menu-item trees would generate error "HTTP code 414 Request-URI Too Large" from NGINX

<img width="1440" alt="screen shot 2017-03-24 at 3 39 50 pm" src="https://cloud.githubusercontent.com/assets/22307536/24315803/0e340dc6-10af-11e7-9fca-920040c6b668.png">

<img width="1440" alt="screen shot 2017-03-24 at 3 40 17 pm" src="https://cloud.githubusercontent.com/assets/22307536/24315809/174251f2-10af-11e7-98f4-164cae76aaf7.png">

<img width="1440" alt="screen shot 2017-03-24 at 3 38 54 pm" src="https://cloud.githubusercontent.com/assets/22307536/24315829/293f44b4-10af-11e7-8e14-b33e3255a3d3.png">

## Context
The error documented on this issue (ie. "HTTP code 414 Request-URI Too Large" from NGINX) can only be reproduced over big menu-items trees. This has been the case for one of dotCMS's Cloud clients on dotCMS 3.7.1 version, which reported the issue that is currently tracked at https://my.dotcms.com/tickets/detail.dot?id=59edb35c-9b40-4186-a526-40b5417487ee. It has been analyzed that this requires refactorings on both Client-Side and Server-Side code and that is potentially affecting latest dotCMS versions (3.7.1 and 4.0)

## Your Environment
* dotCMS version used: 3.7.1 and 4.0
* Browser Name and version: Firefox
* Operating System and version: Mac OSX
* Application Server and version: Tomcat
* Database and version: Postgres

**Comment by wezell** [comment]
@gabbydotCMS did we try my suggestion on the ticket?

**Comment by gabbydotCMS** [comment]
@wezell not yet, I'll give you an update today

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/11669

**Comment by oarrietadotcms** [comment]
PR Core release 4.1.0: https://github.com/dotCMS/core/pull/11694

**Comment by gabbydotCMS** [comment]
Hotfix was successful on client's dEC environment
https://my.dotcms.com/tickets/detail.dot?id=59edb35c-9b40-4186-a526-40b5417487ee

**Comment by shaydotcms** [comment]
Thanks for the confirmation @gabbydotCMS
