### ISSUE TITLE
Fix Cache Stats

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11147]
We need to fix the hazelcast / guava / H22 cache stat numbers

**Comment by wezell** [comment]
Guava looks like this:

![screen shot 2017-03-28 at 1 02 53 pm](https://cloud.githubusercontent.com/assets/934364/24417585/ee18fe60-13b6-11e7-851c-32fc501437db.png)

**Comment by jtesser** [comment]
Ahh yes I made a late change that did that :-)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/11284

**Comment by jtesser** [comment]
I am closing this as it should be done
