### ISSUE TITLE
DotParse from Custom Code Field does not display properly on content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11146]
Reproduced on 4.0.1 on training server and demo.dotcms.com

When placing this code inside a custom code field on a NEW content type

#dotParse('/application/vtl/custom-fields/url-title.vtl')

Then editing content, the URL title always appears as $structure.urlMapPattern, instead of displaying the url title properly.

![displayurltitlebroken](https://cloud.githubusercontent.com/assets/1569167/24411286/bbd54770-1392-11e7-9740-d593291067db.png)

The url title saves successfully but can't be viewed while adding content.

**Comment by wezell** [comment]
This needs to be fixed in the starter code.
