### ISSUE TITLE
Hazelcast Performance 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11151]
We need to insure that Hazelcast is properly reading and writing for all regions.  Currently I am aware that the ContentType (fields) cache and the Indices caches are not working properly.

**Comment by jtesser** [comment]
So I fixed the indicies cache and all small regions here https://github.com/dotCMS/core/commit/c57e48ad5d11c8cfc3050b0eb2772e443f943bb7#diff-30165178aef8182deba8f6366383edb7
for details see my bug report here https://github.com/hazelcast/hazelcast/issues/10179

**Comment by jtesser** [comment]
we have decided that Hazelcast has too much overhead for just one server.  Once you set up a cluster it gets faster and is the cache to consider.
