### ISSUE TITLE
Embed DTD in hibernate's xml

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11158]
Please take a look at this PR:

https://github.com/dotCMS/core/pull/11130

**Comment by jtesser** [comment]
In addition to the other PR and issue this issue is related to the work here https://github.com/dotCMS/core/issues/11120

**Comment by dsilvam** [comment]
Dup of https://github.com/dotCMS/core/issues/11129

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/11160
