### ISSUE TITLE
The add event form needs UI help 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11154]
We are some problems at the UI level adding a new event on the calendar iframe 

## Expected Behavior
We need show the add event form normally without problems 

## Current Behavior
This form has some UI problems https://screencast.com/t/SjcNTjyA

## Steps to Reproduce (for bugs)
1. Login 
2. Go to calendar and try to add some event  
3. Looks the form 

## Your Environment
Tested on master-4.1 // Postgres

**Comment by wezell** [comment]
New UI
