### ISSUE TITLE
Unable to create containers 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11153]
We are having problems when you try to create a new container, this because the system is unable to compile the layout_portal.jsp in the line 19... 

## Expected Behavior
We should be able to add containers without problems 

## Current Behavior
The system breaks and shows an error 
ST: https://gist.github.com/bryanboza/1eea0371310d4d997a905f6c0c4d4b80

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Site --> Containers 
3. Try to add a new one 

## Your Environment
Tested on master-4.1 // Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11166

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // MySQL // FF
