### ISSUE TITLE
Add new event error

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11164]
If you try to add a new event you get a ```null``` error.

## Steps To Reproduce:
1. Go to:  Content > Calendar > Add new event

## Expected Behavior
Add new event should load a form and be able to save the event

## Current Behavior
https://www.screencast.com/t/jf0tDRHh

**Comment by jdotcms** [comment]
<img width="1375" alt="save1" src="https://cloud.githubusercontent.com/assets/19578350/24595770/b97f3428-17f6-11e7-8211-b7571331491c.png">
<img width="1421" alt="save2" src="https://cloud.githubusercontent.com/assets/19578350/24595790/e2312336-17f6-11e7-83d3-5b4a6c148c47.png">

**Comment by jdotcms** [comment]
I was able to save the event. However I am getting this error:
https://gist.github.com/jdotcms/3233313924fd5932003901157436bb71

Will double check it.

**Comment by jdotcms** [comment]
At the end, it wasn't an issue; it is just debugging messages. Will send to QA for double checking!

**Comment by bryanboza** [comment]
Fixed, I am able to add new events, some UI improvements here https://github.com/dotCMS/core/issues/11223
