### ISSUE TITLE
Inherited Permissions Display Error

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11175]
Reproduced on dotCMS 4.0.1

1) Edit a role, add demo.dotcms.com, and view permissions on all folders on the host.
2) Edit one of the folders on the site browser that is inheriting permissions from the host.  It displays that the role has full permissions on folders instead of just view (bug)

![inheritedpermissionserror](https://cloud.githubusercontent.com/assets/1569167/24476893/4e184718-1492-11e7-8a63-d9c9e4a69b90.png)

screencast: https://screencast.com/t/yCyB7x0r

**Comment by john-thomas-dotcms** [comment]
This one is still an issue.  Just want to refresh it and see if we can get it looked at.

**Comment by wezell** [comment]
Fixed here

https://github.com/dotCMS/core/commit/fe02328483095d9d02d3103652a291260fbfe7d0
