### ISSUE TITLE
Nested Roles are not passing permissions to Parent Roles

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11173]
tested on latest dotCMS 4.0.1

Easy to reproduce:
Create a parent role and then a nested Child role.  Give the child role access to a site browser folder or a Content type, etc.

Create a new user and assign the PARENT role to the user.  Then login as that user.  The bug is that none of the child objects were passed to the parent role/user (which is purpose of nesting roles)

screencast: https://screencast.com/t/7NoUsH5woJ

**Comment by agomez-dotcms** [comment]
After fixing issues referenced above (which were preventing exercising required functionality) on actual 4.1 branch, **this issue could not be reproduced according provided steps. It was also tested on live 3.7 and 4.0 sites with same results** (ie. https://demo3.dotcms.com and https://demo.dotcms.com).

After using following steps, I confirmed that a Limited User was able to see Folders and Content-Types with permissions granted through a Child Role (from "Site->Browser" and "Content->Search" portlets, respectively):

**[AS ADMIN USER]**
1. Created Parent and Child roles. Granted access to "Home", "Site" and "Content" tabs (on both)
2. Granted Child role with "View access" to corresponding Host from "System->Roles" portlet
3. Created Limited User from "System->Users" portlet. **Added it into Parent role** from "System->Roles" portlet
<img width="1440" alt="screen shot 2017-04-05 at 5 12 05 pm" src="https://cloud.githubusercontent.com/assets/22307536/24731382/e69ca2e2-1a26-11e7-87eb-9accb9376298.png">

4. Created new Content-Type from "Content-Types" portlet. Individually permissioned **Child role** with "Publish access" to the new content-type
5. Created new Folder from "Site->Browser" portlet. Individually permissioned **Child role** with "Publish access" to the new folder
<img width="1440" alt="screen shot 2017-04-05 at 5 11 44 pm" src="https://cloud.githubusercontent.com/assets/22307536/24731363/c696e110-1a26-11e7-94fa-0a2de7423158.png">

**[AS LIMITED USER]**
1. Went to "Site->Browser" portlet. Limited user was able to see the new folder, which was permissioned through reverse-inherited Child role
<img width="1440" alt="screen shot 2017-04-05 at 5 13 18 pm" src="https://cloud.githubusercontent.com/assets/22307536/24731339/a2334d36-1a26-11e7-81c4-5cb64fe816fe.png">

2. Went to "Content->Search" portlet. Limited user was able to see the new content-type, which was permissioned through reverse-inherited Child role
<img width="1439" alt="screen shot 2017-04-05 at 5 13 41 pm" src="https://cloud.githubusercontent.com/assets/22307536/24731348/b01322aa-1a26-11e7-9cf5-6b1effbdf736.png">

Hence, moving this ticket to "In Review"

**Comment by DeanGonzalez** [comment]
I just tested and this appears to be fixed now after the other fixes on the associated issues. Closing this one out.

**Comment by DeanGonzalez** [comment]
Fixed in 4.1
