### ISSUE TITLE
Cannot add/delete some fields in a Content/Content Type

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#11170]
The Category and Hidden fields cannot be deleted from the Content Type and data can't be added to a Category Field to a contentlet.

## Expected Behavior
Content should be added to a contentlet and fields should be deleted from a Content Type without issues.

## Current Behavior
The system is failing to perform the actions described above.

## Possible Solution
Investigate if this is related to the new Content Type and Field classes.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Create a Content Type and add a Category field and a Hidden field.
2. Delete both fields. Check the logs and an exception will be displayed.
3. Also, create a contentlet based on the Content Type you created above.
4. Try to add content to the Category field. The link to add content is not showing up.

## Your Environment
* dotCMS version used: 4.1.0
* Browser Name and version: Any
* Operating System and version: Any
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8
* Database and version: Any
* Application module (if apply): Content Search and Content Type pages.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11209

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF
