### ISSUE TITLE
Unable to see the live version of some page multi language pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11179]
We are having problems with the multi-language pages, this because if you try to see the live version of some page that  is in any language different to the default this never loads and shows a blank page. 

## Expected Behavior
As in previous versions we should be able to see the live versions of the pages in any language 

## Current Behavior
The page never loads, and leave a blank page 
SC: https://screencast.com/t/iSCeqENsM

**FYI:** Also the same problem on FE

## Steps to Reproduce (for bugs)
1. Login  
2. Add a new page 
3. Create a page version in Spanish 
4. Add content to both languages 
5. From edit mode, change the language to Spanish and go to the live tab. 

**FYI:** No errors on log

## Your Environment
Tested on master-4.1 // Postgres // FF & Chrome

**Comment by jcastro-dotcms** [comment]
Cannot reproduce the issue anymore. Verified with @bryanboza personally, and the problem is not present now.

**Comment by bryanboza** [comment]
Tested again and we are unable to reproduce on master-4.1 // H2 // FF
