### ISSUE TITLE
Unable to delete push environments 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11187]
After add some push environment, we are unable to delete it... 

## Expected Behavior
We need be able to delete the environments without problems 

## Current Behavior
We are having an error when you try to delete the environment 

SC: https://gist.github.com/bryanboza/044822192b4014b39332e9b57f6b8b21

## Steps to Reproduce (for bugs)
1. Login 
2. Apply the license 
3. Add a new push environment 
4. Add a new endpoint to this environment 
5. Try to delete it 

## Your Environment
Tested on master-4.1 // MySQL // Chrome

**Comment by jcastro-dotcms** [comment]
Note to QA: Cannot reproduce the issue. Please re-test.

**Comment by bryanboza** [comment]
Now we are able to delete the push environment, but still having problems deleting the endpoints, **FYI:** steps updated

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11229

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF... New improvement on #11232

**Comment by jcastro-dotcms** [comment]
PR containing changes requested by Will: https://github.com/dotCMS/core/pull/11289

**Comment by bryanboza** [comment]
Fixed, retested with the last changes and works as expected...
