### ISSUE TITLE
Publish angular app as a node module

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11181]
We need to publish the angular app as a node module so we can npm install it into core and run the app from there.

1. Publish only what's on ```/dist/```
2. Make sure not to carry source dependencies
3. Add an ```npm``` script for automate this.

**Comment by fmontes** [comment]
So after all this, what we need to do inside core is:

```shell
$ npm install ~/dev/core-web/dist/dotcms-ui-1.0.0.tgz
$ rm node_modules/dotcms-ui/package.json
$ cp -a node_modules/dotcms-ui/ ~/dev/dotcms/tomcat8/webapps/ROOT/dotAdmin
$ rm -rf node_modules
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11208
