### ISSUE TITLE
Fixing unit tests

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11188]
We still have some failing unit tests:

https://cb.dotcms.com/view/master-4.1/job/Git_Master_Int_Funct_Test_Runner_4.1_Postgres/158/testReport/

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/11190 for https://cb.dotcms.com/view/master-4.1/job/Git_Master_Int_Funct_Test_Runner_4.1_MSSQL/lastSuccessfulBuild/testReport/junit/com.dotmarketing.portlets.structure.factories/StructureFactoryTest/findStructuresUserCanUse/

**Comment by erickgonzalez** [comment]
This PR https://github.com/dotCMS/core/pull/11210 is for showing the Permissions Tab on the Content Type Portlet, it was throwing an issue in browser console related to Structure Mapping in hibernate.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11227

**Comment by erickgonzalez** [comment]
This PR https://github.com/dotCMS/core/pull/11237 is for https://cb.dotcms.com/view/master-4.1/job/Git_Master_Int_Funct_Test_Runner_4.1_Postgres/151/testReport/junit/com.dotmarketing.portlets.contentlet.business/ContentletAPITest/widgetInvalidateAllLang/

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/11263 is for https://cb.dotcms.com/view/master-4.1/job/Git_Master_Int_Funct_Test_Runner_4.1_Postgres/lastSuccessfulBuild/testReport/junit/com.dotmarketing.business.cache.provider.h22/H22CacheTest/testInit/
