### ISSUE TITLE
Support Progressive Jpegs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11184]
We need a way for our image filters to be able to create and deliver progressive jpegs
Non-progressive:
`http://localhost:8080/dA/4d7daefa-6adb/2000w/jpegp/404.jpg`

progressive
`http://localhost:8080/dA/4d7daefa-6adb/2000w/jpegp/404.jpg`

Why it matters:
https://www.wired.com/2013/01/the-return-of-the-progressive-jpeg

**Comment by wezell** [comment]
![venice-carnival-2012-9-behind-the-scenes-ipad-progressive](https://cloud.githubusercontent.com/assets/934364/24551909/79e2afda-15f2-11e7-9606-ddeb4575f9c9.jpg)

Test image

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11255

**Comment by bryanboza** [comment]
Fixed, tested with the attached image and now is progressive...

**Comment by john-thomas-dotcms** [comment]
Forgot to add the doc link: https://auth.dotcms.com/docs/latest/image-resizing-and-processing

(Just a couple touches)
