### ISSUE TITLE
Unable to edit push publish environments 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11186]
After add some push environment, we are unable to edit 

## Expected Behavior
When you click the environment you need open the edit window 

## Current Behavior

- [ ] When you click it, just open the environment edit window, but not the endpoint configuration
SC: https://screencast.com/t/W2XT7HCTR

- [ ] Also when you try to edit the receiver environments, the system open the window but without the values... 
SC: https://screencast.com/t/PU5cJFPr

## Your Environment
Tested on master-4.1 // MySQL // FF

**Comment by wezell** [comment]
Cannot reproduce in the latest code.
