### ISSUE TITLE
Integrity checker isn't working on master-4.1

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11189]
Unable to run the integrity checker, we have a NPE in the log and the job never starts 

## Expected Behavior
Need support the integrity checker 

## Current Behavior
NPE in the log... 
SC: https://gist.github.com/bryanboza/c46a91c9330a69056ef6c7b66952477b

## Steps to Reproduce (for bugs)
1. Login  
2. Add a new push environment on sender
3. Configure your push environment on the receiver side 
4. Try to run the integrity checker 

## Your Environment
Tested on master-4.1 // MySQL // FF 
This on both environments

**Comment by jcastro-dotcms** [comment]
The fix implemented for https://github.com/dotCMS/core/issues/11187 will take care of this issue.

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, now this is working on master-4.1 // some new enhancements related to be case sensitive here #11466
