### ISSUE TITLE
Need remove the Next/Previous buttons in content types portlet when you don't have access to all the content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11192]
When you have more that 40 structures, the system is showing Next/Previous buttons, this to paginate... 

## Expected Behavior
If you don't have access to all these content types, the system should hide those buttons 

## Current Behavior
If you have more that 40 content types, and login as some limited user, the system continue showing these buttons
SC: https://screencast.com/t/BQocc69jgy

## Steps to Reproduce (for bugs)
1. Login as admin
2. Make sure you have more that 40 content types 
3. Login as some limited user (Daniel Publisher)
4. Go to content types portlet

## Your Environment
Tested on master-4.1 // MySQL // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11224

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF
