### ISSUE TITLE
[Improvement] Fix Task: Delete Relations with no existing Content Types

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11191]
Improvement requested by @gabbydotCMS 

Client had a NPE when downloading a bundle for publish. The bundle had a single template, the bundle process goes like this: 

Template -> Container -> Content Type -> Relations

There was a relationship on the Database that had a child Content Type that no longer existed. (maybe old bug? o bad data?). It would be cool to have a Fix Task that takes care of these cases.

[Client Ticket](https://my.dotcms.com/tickets/detail.dot?id=7c1d09b0-30bc-4918-b31f-6b0b89cad29a)

## Possible Solution
1. Run query: `delete from relationship where inode in (select inode from relationship where child_structure_inode not in (select inode from structure) OR parent_structure_inode not in (select inode from structure));`
2. Flush Caches

## Your Environment
* dotCMS version used: 3.7.1
* Database and version: Postgres (Cloud Client)

**Comment by wezell** [comment]
Hopefully 4.1 will address issues like where data gets out of sync.  Additionally #11194
