### ISSUE TITLE
Run Unit tests on every commit

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11201]
Please see https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by agomez-dotcms** [comment]
Hi Guys,

It looks this task is now done via Jenkins job at https://cb.dotcms.com/view/builds%20-%20pull%20requests/job/Build_PullRequests_Tester_All/

In interest of saving time, please notice UNIT tests are the ones that run upon Pull Requests (not Integration nor Functional tests) as documented on Google Doc at https://docs.google.com/document/d/1UyufwSs93LnQSDCJlsZM0uavbePx-lWGI0qT3vVQAkA

Thanks,
Anibal

**Comment by dsilvam** [comment]
@agomez-dotcms I updated the title accordingly to reflect this.

**Comment by agomez-dotcms** [comment]
Thanks!
