### ISSUE TITLE
Minifiy Dojo

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11218]
Very much like we did with the angular ui load, we need to minify our dojo load so that a user downloads 1 file instead of 240.  The difference is that this minification process does not need to be part of a build process and we can use a 1 time tool to do it - as we are not updating our use of dojo or its components at this time.

**Comment by freddyucv** [comment]
We have some style errors in the edit content screen

<img width="1308" alt="screen shot 2017-04-07 at 09 49 37" src="https://cloud.githubusercontent.com/assets/10408015/24808676/f4cedc14-1b79-11e7-916b-a7f861164249.png">

<img width="501" alt="screen shot 2017-04-07 at 09 49 59" src="https://cloud.githubusercontent.com/assets/10408015/24808679/f9bbc408-1b79-11e7-93eb-4639c88df537.png">
