### ISSUE TITLE
Mailer Viewtool does not pick up all context.xml settings

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#11217]
## Expected Behavior
Any configuration set in the configuration static plugin's context.xml would pass through to the Mailer Viewtool.  

## Current Behavior
Currently when trying to configure to use some third party mail services (gmail, for example) if the services requires StartTLS and dotcms is configured with 

mail.smtp.starttls.enable="true"

triggering the viewtool still results in

Unable to Send Message: 530 5.7.0 Must issue a STARTTLS command first.

**Comment by gabbydotCMS** [comment]
Reported on 	https://my.dotcms.com/tickets/detail.dot?id=69bec382-0345-4067-b9ac-7088ca00db7c

**Comment by JustinKubicek** [comment]
I'm curious if anyone has put any work into this issue. I'm going to be using dotCMS for another project. It would be great if the Mailer Viewtool supported this. I'm checking out the dotCMS project code to familiarize myself with it...

**Comment by vianneychacon** [comment]
A similar problem was experienced in a 3.7.1 installation. The SES settings are working correctly, the forgot password feature is working for example, but not the mail tool. The error is: `Unable to Send Message: 530 Authentication required`. Reference: https://dotcms.zendesk.com/agent/tickets/90373

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
