### ISSUE TITLE
Calendar add event form needs styling

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11223]
The add/edit content for events it's not working correctly: https://www.screencast.com/t/fFvpswHaDh

## Expected Behavior
1. Remove all extra white space
2. Scroll on top when the page loads.

## Current Behavior
1. Description filed have a big white space
2. When the page load scroll it's at the middle of the page.

## Steps to Reproduce (for bugs)

1. Go to calendar
2. Click "Add new"

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: All
* Operating System and version: All

**Comment by gabbydotCMS** [comment]
Reported by client: https://my.dotcms.com/tickets/detail.dot?id=3b0d1b8b-2862-4d44-a21b-b0e8b05f38f4
