### ISSUE TITLE
Breadcrumps categories are hidden

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11221]
There was a fixed for the categories portlet and added the breadcrumps,
however the style is hidden them, we have to show them when they exists.

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/11140 and https://github.com/dotCMS/core/pull/11220

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11324

**Comment by bryanboza** [comment]
Fixed, now we can see the breadcrumbs without problems
