### ISSUE TITLE
Login As RestAPI uses parameters 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11230]
Login As API expects the username/password as URL parameters, which can be traced on access logs and also on browser’s network tab.

We need to use POST parameters to pass this information.

Steps:

1.  Login to 4.0.1 as admin@dotcms.com/admin user.
2. Go to Users portlet and select 'admin2@dotcms.com'. Change its password to 'admin/1234' (including the slash).
3. On the top right corner, click on the user icon and select "Login as".
Select "Dave Smith" user and, once it prompts for password, place the admin@dotcms.com password.
4. dotCMS access logs show password in REST API call, in clear text.
```
0:0:0:0:0:0:0:1 - - [04/Apr/2017:13:56:55 -0400] PUT /api/v1/users/loginas/userid/dotcms.org.2802/pwd/admin HTTP/1.1 HTTP/1.1 localhost/api/v1/users/loginas/userid/dotcms.org.2802/pwd/admin 200 74 http://localhost:8080/dotAdmin/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

**Comment by jgambarios** [comment]
We need to change the method here https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java#L301

And here I guess https://github.com/dotCMS/core-web/blob/master-4.1/src/app/api/services/login-service.ts#L183

**Comment by joseorsini** [comment]
for your consideration: 

https://github.com/dotCMS/core/issues/11238
https://github.com/dotCMS/core/issues/11235

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/11252
https://github.com/dotCMS/core-web/pull/316

**Comment by bryanboza** [comment]
Fixed, the rest has been changed to  http://localhost:8080/api/v1/users/loginas/ and you need sent the userId by parameter...  Works as expected
