### ISSUE TITLE
Incorporate Velocity Memory Improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11236]
There have been a few memory improvements made in velocity 2.0 that we can lift and bring into our own velocity code.  These are:

https://issues.apache.org/jira/browse/VELOCITY-801
https://issues.apache.org/jira/browse/VELOCITY-833
https://issues.apache.org/jira/browse/VELOCITY-841

I believe JT and Jorge have already incorporated 833 but we should also incorporate the other two patches as well.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11254

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // postgres // FF
