### ISSUE TITLE
Add new site form don't have translation 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11234]
## Expected Behavior
Every portlet should have translation 

## Current Behavior
If you change the system language to Spanish and then try to add a new site, the system is showing the form in English

SC: https://screencast.com/t/b6AKDksZHWds

## Steps to Reproduce (for bugs)
1. Change the dotcms language to Spanish
2. Login 
3. Try to add a new site 

## Your Environment
Tested on master-4.1 // H2 // FF

**Comment by wezell** [comment]
This is set by the Host content type labels
