### ISSUE TITLE
Content types endpoint it's requiring license

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11231]
In the UI we use the endpoint ```v1/contenttype/basetypes``` to build the "add content" component, recently it was modified (url) and now it's trowing error 500 requiring license. 

## Expected Behavior
Should response without license

## Current Behavior
Is asking for license

**Comment by jgambarios** [comment]
For 4.1 the flow is:

https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotcms/rest/api/v1/content/ContentTypeHelper.java#L110
Which calls:
https://github.com/dotCMS/enterprise-2.x/blob/master-4.1/src/main/java/com/dotcms/enterprise/priv/ESSearchProxy.java#L106

The ESSearchProxy.java can be use only with a license so the "Add content" component won't work for community users.

This is how used to work in 4.0:
https://github.com/dotCMS/core/blob/4.0.1/dotCMS/src/main/java/com/dotmarketing/portlets/structure/business/StructureAPIImpl.java#L200-L234

**Comment by jcastro-dotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/11276
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/457

**Comment by jcastro-dotcms** [comment]
Additional PR: https://github.com/dotCMS/core/pull/11280

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF

**Comment by jcastro-dotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/11292
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/459
Lic PR: https://github.com/dotCMS/license/pull/47

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // postgres // FF
