### ISSUE TITLE
Make Jenkins build for all release branches 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11239]
We are moving to more of a git-flow model which we use now but modified. We will be more traditional git-flow. 

This means we will have a single master and SOMETIMES have release branches when more then one release is being worked on ie... a release will be coming out soon with less functionality then the master currently has 

Jenkins will be always testing master.  

In addition we need Jenkins to have a second tab which runs tests for all release branches.  A release branch will have the convention of starting with the name release-xxx

This will clean up Jenkins

**Comment by nollymar** [comment]
Now, the dotCMS project can be configured easily in Eclipse following these steps: https://docs.google.com/document/d/1GAwk3fgSDVZXF7hdKQnHmoO_8Gklyo1FuPrsa93EMrA/edit?pli=1#

**Comment by nollymar** [comment]
A new Jenkins task called **Git_Releases_Seed** was included to create and launch a builder for each release branch. For more details, please take a look at this documentation (Section **Continuous Integration for Releases**): https://docs.google.com/document/d/1kaC5rpQospPFR5TZTBCn8sPlnwUCsyhHq-c_d3jRtt8/edit#
