### ISSUE TITLE
Hydrate contenttype.fields when loading 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11244]
When loading a content type, we need to hydrate the contenttype's fields before storing it into cache so the whole representation is available in cache.  Without this change, every time you request a content type's fields, it hits the db.

**Comment by wezell** [comment]
I also wrapped the db lookup methods in the local transaction which will close the db connection after using it.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11253

**Comment by bryanboza** [comment]
Fixed, I made some sanity test over content types and everything works as expected
