### ISSUE TITLE
[Improvement] See full page url on edit mode

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11240]
Client Ticket: https://my.dotcms.com/tickets/detail.dot?id=d4bfdb97-dd00-4f4a-85c6-4c61658865e5

The new UI provides no easy way to find the page's full URL of a given page you are editing. (And the site tree is hidden in edit mode. But even if it wasn't you'd have to manually type out that path, given you can't copy the site tree.)

It would be nice to have a “Resource Link” provided for users like you do for Files Assets and images.

Since the URL is obfuscated in the new UI, users can no longer easily copy it from the address bar to view in another browser or send to us for support.

## Your Environment

* dotCMS version used: 4.0.1

**Comment by john-thomas-dotcms** [comment]
+1
