### ISSUE TITLE
Admin User unable to access Folder->Permissions for any folder on Site->Browser-> tab

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11251]
While addressing issue #11173, it was found that Admin Users are currently not able to access Folder->Permissions for any folder on Site->Browser tab. System does not break neither on Server-Side nor Client-Side. This actually seems to be an issue at Client-Side as Folder->Permissions screen remains blank

## Expected Behavior
Folder->Permissions should be available to Admin Users for any folder on Site->Browser-> tab

## Current Behavior
Folder->Permissions is not available to Admin Users. Folder->Permissions screen remains blank
<img width="1440" alt="screen shot 2017-04-05 at 11 48 49 am" src="https://cloud.githubusercontent.com/assets/22307536/24719198/15dacd62-19f6-11e7-8123-22af64fdf134.png">

## Steps to Reproduce (for bugs)
1. Login as Admin User
2. Go to Site->Browser tab
3. Right-Click on any Folder and Select Edit Folder
4. Switch to Permissions tab
5. Look at blank screen

## Your Environment
* dotCMS version used: 4.1.0 (master-4.1)
* Browser Name and version: Any
* Operating System and version: Mac OSX
* Application Server and version: Apache Tomcat
* Java Brand and version: Oracle Java 1.8.0_102
* Database and version: MySQL

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11259

**Comment by wezell** [comment]
Can we get a integration test on this?

**Comment by shaydotcms** [comment]
Passed QA. Followed steps to reproduce. Admin user now has access to Site->Browser tab.
Tested in master-4.1 / commit 4b045577a008bd9838608f6849a1870ccd5677ee
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
