### ISSUE TITLE
Force all vanity urls to lowercase

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11264]
- [x] We need to remove the lower(?) from the VanityUrlFactory SQL and lowercase the string before the query
- [x] write a startuptask that lowercases all vanity urls

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11345

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11358

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11367

**Comment by bryanboza** [comment]
Fixed, now all the new vanity url, are saved in lowercase and after upgrade we made the update without problems
