### ISSUE TITLE
Create "4 Eyes" Principle Workflow Actionlet 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11265]
Customer would like content to be published if at least 2 people (4 eyes) approve the content.  They are not particular as to which users, they just need 2 people to approve before the content goes live.

We need to develop an actionlet that enforces this principle.  We already have a multi-approver actionlet, but in that one you need to specify the list of approvers.  What we should do is allow a user to select which role has "4 Eye" publishing permissions and then all it would take is 2 of those users to approve and the content would be published.

**Comment by joseorsini** [comment]
Requested by another customer: https://my.dotcms.com/tickets/detail.dot?id=e69f4f52-0f9b-4f7a-ac6f-84224ee37d41

**Comment by john-thomas-dotcms** [comment]
I think this could be useful as long as it's an option on the workflow step (not a general change in how assignment is handled).

I regularly assign content to myself with a workflow action so it will show up in my task queue; but in some kinds of workflow actions (like a Review step) it may make sense not to allow this, so an option in the workflow action to exclude the current user from the assignment would make sense.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/13366

**Comment by bryanboza** [comment]
Tested on 4.3.0 and works as expected.

**Comment by bryanboza** [comment]
Fixed, tested on master and works as expected too

**Comment by jgambarios** [comment]
Documented in here: https://dotcms.com/docs/latest/multiple-approval-sub-actions
