### ISSUE TITLE
Session language is affecting when you upload new files 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11267]
After implement the multi-language files, we are having some problems with the session language variables, this because we are not intuitive... Because after set that variable all the system still working with that... 

## Expected Behavior
We need find the way to continue working normally with the default session language after set this variable to see some preview... 

## Current Behavior
When you login and upload some file, the system is uploading this in the default language, but if you create a new page, and then create this page in Spanish or any other language and go to the preview, the system set the session language, and after that, if you upload some file, this is uploaded on the same language..
SC: https://www.screencast.com/t/bnerdG6q

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new folder and upload some field (make sure is uploaded in the default language )
3. Create a new page 
4. Create a new version of this page, but now in Spanish
6. Go to the preview and add a piece of content... 
5. Bring back to the Browser and try to upload a new file 

## Your Environment
* dotCMS version used: The last code of master-4.1 
* Browser Name and version: Chrome 
* Operating System and version: MacOSX
* Application Server and version: Tomcat
* Java Brand and version: Java8
* Database and version: H2

**Comment by wezell** [comment]
should work in the new UI
