### ISSUE TITLE
Lock Role is not working

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11274]
Locking a Role is not working from the **Roles & Tools** portlet

## Expected Behavior
Right click and **Lock Role** should lock the selected role

## Current Behavior
No lock is being applied to the role

## Steps to Reproduce (for bugs)
1. Roles & Tools
2. Select a Role
3. Right click and select **Lock Role**
4. The Role is not getting any lock

## Your Environment
* dotCMS version used: 4.1
* Database and version: Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11275

**Comment by erickgonzalez** [comment]
Working as it should, Role is being locked and unlocked successfully.
