### ISSUE TITLE
Update /icon servlet calls on Report-related jsp files

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11286]
Despite the Reports portlet is deprecated, it's still used by Enterprise customers, who have noticed that the "Export" buttons for different formats (Excel spreadsheet or PDF file) are broken. 

## Expected Behavior
It should use the new icons, in the same way Site Browser does, for these buttons.

## Current Behavior
It shows an error 404 on access logs and on browser's console. Users cannot figure out easily how to export reports to PDF or XLS files.

## Possible Solution
Build a similar logic [we have for Site Browser](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/browser/view_browser_js_inc.jsp#L855-L870) and apply it [here](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/report/view_reports.jsp#L159-L175)

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Go to https://demo.dotcms.com/icon?i=.pdf. It should resolve to https://demo.dotcms.com/html/images/icons/pdf.png according to logic in the IconServlet class (this is for 3.x releases). For 4.x, the same original URL should resolve to its respective mapping on the dot_admin.css file.
2. An error 404 message is thrown.

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=e8255e02-29bc-4af4-876b-3ba2e762db0c

## Your Environment

* dotCMS 4.0.1, 3.7.1.
* Any OS/DB/Browser.
* Java 8u121

**Comment by wezell** [comment]
IconServlet has been deprecated for years.  If it is needed by a client, it can be provided by a static plugin.
