### ISSUE TITLE
Clean up of removed (deprecated) code

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11295]
After this issue: https://github.com/dotCMS/core/issues/10402 we are having FATAL errors on clients environments, because there are references to some of the classes removed. For example this client had problems with DeliverCampaign job. Doing a quick search I could find some of the places where we still use the logic removed [Example 1](https://github.com/dotCMS/core/blob/549b621398ae5d253b6a894a10b015ac3c1a4c67/dotCMS/src/main/java/com/dotmarketing/init/DotInitScheduler.java#L100-L100), [Example 2](https://github.com/dotCMS/core/blob/7f5a06e84b78371f8600e7fd072d9ba657ab8298/dotCMS/src/main/java/com/dotmarketing/servlets/RunScheduledJobServlet.java#L31-L31). 

Also, we need to make sure clients coming from previous versions (using those jobs removed) don't have the jobs in the quartz tables, etc. (Upgrade Task)

Client ticket: https://my.dotcms.com/tickets/detail.dot?id=7e6c49a1-93f0-43e2-b1f7-185d6897f499

## Known Workarounds
in this case (DeliverCampaignJob):
```
DELETE FROM qrtz_excl_cron_triggers WHERE trigger_name IN (SELECT trigger_name FROM qrtz_excl_triggers WHERE job_name = 'DeliverCampaignJob');
DELETE FROM qrtz_excl_triggers WHERE job_name = 'DeliverCampaignJob';
DELETE FROM qrtz_excl_job_details WHERE job_name = 'DeliverCampaignJob';
```

**Comment by wezell** [comment]
I believe we need an upgrade task that deletes all old jobs and triggers.  The ones that matter get rebuilt on startup anyway

**Comment by dsilvam** [comment]
Yeah @oarrietadotcms suggested doing so in the description

**Comment by shaydotcms** [comment]
Passed QA. Tested with started data and doing upgrade from 3.6.0 to 4.1.0 using clients' data
No errors are showing in regards to old classes.
Tested on master-4.1 / commit 6caf33e
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
