### ISSUE TITLE
Rest API for managing Field Variables

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11291]
We need a crud RESTEndpoint for Adding, Editing and Deleting Field Variables

-- Additional description by @agomez-dotcms -- -

- [ ] List all field variables of given content type and field (id)
```GET /v1/contenttype/{typeId}/fields/id/{fieldId}/variables ```

- [ ] List all field variables of given content type and field (var)
```GET /v1/contenttype/{typeId}/fields/var/{fieldVar}/variables ```

- [ ] Get field variable by id (and field-id) 
```GET /v1/contenttype/{typeId}/fields/id/{fieldId}/variables/id/{fieldVarId}```
 
- [ ] Get field by id (and field-var)
```GET /v1/contenttype/{typeId}/fields/var/{fieldVar}/variables/id/{fieldVarId}```

- [ ] Create field variable in content type and field (and field-id)
  ```POST /v1/contenttype/{typeId}/fields/id/{fieldId}/variables``` (need to define JSON object)

- [ ] Create field variable in content type and field (and field-var)
  ```POST /v1/contenttype/{typeId}/fields/var/{fieldVar}/variables``` (need to define JSON object)

- [ ] Update existing field variable by id (and field-id)
 ```PUT /v1/contenttype/{typeId}/fields/id/{fieldId}/variables/id/{fieldVarId}```

- [ ] Update existing field variable by id (and field-var)
 ```PUT /v1/contenttype/{typeId}/fields/var/{fieldVar}/variables/id/{fieldVarId}```

- [ ] Delete by id (and field-id)
```DELETE /v1/contenttype/{typeId}/fields/id/{fieldId}/variables/id/{fieldVarId}```

- [ ] Delete by id (and field-var)
 ```DELETE /v1/contenttype/{typeId}/fields/var/{fieldVar}/variables/id/{fieldVarId}```

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11306

**Comment by shaydotcms** [comment]
Passed QA
Tested on master-4.1 / commit f0bc140
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
