### ISSUE TITLE
Undefined message when you use the viewing as feature 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11296]
We are having a Undefined message when you try to use this feature to preview some page in editing mode

## Expected Behavior
This message should disappear 

## Current Behavior
We are showing an undefined message 
SC: https://screencast.com/t/MnWrMgozkzh

## Steps to Reproduce (for bugs)
1. Apply an enterprise license
2. Add a new page  
3. Go to editing mode and try to see as some device 

SC: https://screencast.com/t/MnWrMgozkzh

## Your Environment
Tested on master-4.1 // H2 // FF

**Comment by jgambarios** [comment]
The fix made on this ticket was reverted in order to fix this tickets https://github.com/dotCMS/core/issues/11531 https://github.com/dotCMS/core/issues/11529 so we will see this problem again, we need to find an alternative solution for this problem.

**Comment by bryanboza** [comment]
Passed, tested after the changes in #11529 and works as expected

**Comment by bryanboza** [comment]
Still having problems here: https://screencast.com/t/Cnbba51abrl

**Comment by jgambarios** [comment]
I marked this ticket as Release: 4.1.0 as the revert applied here (https://github.com/dotCMS/core/issues/11529) was done also in 4.1

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11538

**Comment by jgambarios** [comment]
**Note to QA:** @bryanboza please re test https://github.com/dotCMS/core/issues/11529
