### ISSUE TITLE
IE issues after regression testing

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11294]
Here some of the issues that QA found running the regression testing

## Do These
- [x] Consistences window filtering events on calendar needs styling: https://screencast.com/t/fV8ntDOr
#### Theme (https://github.com/dotCMS/dotcms-dojo-theme/pull/31/commits/6e68c3b017f01bd942c422b9b664769265cbb306)
- [ ] In the "Browser" portlet: The cut and paste option isn't refreshing after finish
- [x] Unable to see the dynamic plugins on IE: https://screencast.com/t/DYlZ4N2IWHc (https://github.com/dotCMS/core/pull/11436/commits/31b86958eb5e1c316dd1956a8ce16510772fcfe7)

## core-web

- [x] Unable to see the loading animation when you refresh the page: https://screencast.com/t/NBso2JpcU (https://github.com/dotCMS/core-web/commit/846062b717d3a4305302817521b379c4cbbfb2f2)

- [x] We aren't refreshing the angular menu when you login as: https://screencast.com/t/KzSOD8XXFG

- [x] ~~Need delete the scroll bar in the notifications window: https://screencast.com/t/XAE18Iz9UWg~~ (this is normal IE11 behavior, scrollbars show even when no need to scroll, Windows old school type)

- [x] ~~The form link under the "+" button don't have icon: https://screencast.com/t/aRw8dL6X3J~~ (fixed in other issue)

- [x] ~~We are auto-login after delete the browser history, cache, cookies, etc... : https://screencast.com/t/PLKgfFM2P6E2~~ (On IE11 cookies needs to be cleared different [like this](http://stackoverflow.com/questions/20601097/clear-session-cookies-in-ie11))

- [x] ~~Notifications needs styling help: https://screencast.com/t/sPsuQstyVk~~ (fixed in other task: https://cloudup.com/cQumQRft-XB)

- [x] ~~User info window have a unnecessary scroll bar: https://screencast.com/t/V2YwbhcspaJh //  https://screencast.com/t/tiAPX75BCG~~ (not happening to me, tested on Windows WIN 8 and 10 and Surface with Windows 10, maybe it was fixed on other task but don't know where)

- [x]  ~~The notifications are disappearing after mark as read and login again: https://screencast.com/t/lJV2ht9fpr, also if you refresh the browser the notification is disappearing~~ **this is not happening, on the contrary:**
    - [x] When you clear all or remove a notification, logout/login the notifications are still there.
    - [x] Load more button it's showing on load unnecessarily.

## core

- [x] We are unable to edit a site from site browser portlet (https://github.com/dotCMS/core/commit/be19452a181961416d21a39e63a3155dd9e6e27d): https://screencast.com/t/rdkRFk6atoA

- [x] ~~Unable to see the site tree adding new content to file // image fields : https://screencast.com/t/5fTwayCoi~~ (It was already fixed)

- [x] Show global tags in the tags portlet needs help (unable to see the checkbox): https://screencast.com/t/xrAaalO5Z1Qd
Theme(https://github.com/dotCMS/dotcms-dojo-theme/pull/30/commits/655665327dae1be58dc281387505c8a09696d909)
core(https://github.com/dotCMS/core/commit/934c900469a3cf291c0a8ee9dd63a2e81caec76e), (https://github.com/dotCMS/core/commit/cc959a632200a4eb223e24ca7e1cadf455ca4ca0)

- [x] ~~Variable ID field needs styling help: https://screencast.com/t/jQVWTkrZ, also the role in the permissions tab: https://screencast.com/t/YiUSIAQ9F~~ (It was already fixed)

- [ ] ~~Unable to cut and paste folders with pages, the system just paste the folder without pages~~ (works for me @fmontes)

- [ ] ~~Unable to view past Time Machine snapshot. Pop up asks to open or save file and this is not the right behavior in other browsers~~ (logs: https://gist.github.com/shaydotcms/9579f3218d10b872f68af5eecfc9552d)
![image](https://cloud.githubusercontent.com/assets/8741846/25348857/db7013c6-28dc-11e7-805c-4685a55338fa.png)

## Do not fix for now

- [ ] Add new report button in the reports portlet needs button style: https://screencast.com/t/NzPqqGlV
- [ ] Document content types needs an icon instead the checkbox as in previous releases: https://screencast.com/t/RAnS7SIFbM
- [ ] The progress bar in the sites portlet looks misaligned: https://screencast.com/t/0N28hurhAjb

FYI: All those issues are running master-4.1 // Internet Explorer 11

**Comment by freddyucv** [comment]
this PR: https://github.com/dotCMS/core-web/pull/336 
fix the "We aren't refreshing the angular menu when you login as: " error

**Comment by freddyucv** [comment]
this PR:  https://github.com/dotCMS/core-web/pull/339

fix:  "Load more button it's showing on load unnecessarily."
