### ISSUE TITLE
Allow all dotcms property files to be read from envronment

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11302]
Related to #10658, we need to use the same logic to allow an admin to config almost any property file in the system using the same logic via the environment rather than by editing the files.  Currently, this includes:

`system.properties`
`portal.properties`

**Comment by wezell** [comment]
@jtesser @chrismccracken Can either of you think of any other property files that would need to be configured via envrionment vars?

**Comment by jdotcms** [comment]
For the system.properties file, if the property on the already exists on the System props, shouldn't be override.

**Comment by jdotcms** [comment]
Interpolation ({env:} & {sys:}) will be needed only on portal.properties, does not make sense on system.properties

**Comment by jdotcms** [comment]
portal.properties supports things such as portal.authentication={env:var}

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11396

**Comment by bryanboza** [comment]
Fixed, tested in the last master-4.1 and now you can read in the portal.properties too
