### ISSUE TITLE
Respect Velocity Folder config property

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11303]
Description by @wezell : 

There is another requirement - we need to respect theVELOCITY_FOLDER config property everywhere within the dotCMS system. Currently, our ActivatorUtil has this value hard coded. Here is a search of where we need to change this property to use what is configured in the config properties:

![af6ad926-1f92-11e7-9fe2-fd537afbf399](https://cloud.githubusercontent.com/assets/1576794/24977605/36d028a8-1f93-11e7-8df4-58e197d2cbe1.png)

**Comment by dsilvam** [comment]
@danlaguna we probably need to also get the usages of https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/util/ConfigUtils.java#L54-L54 and change as well

**Comment by shaydotcms** [comment]
Passed QA

* Verified that velocity default folder location is created when velocity property **is not defined** in dotmarketing-config.properties. Uploaded successfully osgi plugin.
* Verified that velocity custom folder is created when velocity property **is defined** (VELOCITY_ROOT) in dotmarketing-config.properties. Uploaded successfully osgi plugin.
* Verified that velocity custom folder is created when defining an **environment variable** and velocity property (VELOCITY_ROOT) is defined in dotmarketing-config.properties (e.g.: VELOCITY_ROOT = {env:velocityPath). Uploaded successfully osgi plugin.
* Uploaded a few osgi plugins and worked fine.

Tested in dotcms 4.1.0 distribution
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/distributed-velocity-files
