### ISSUE TITLE
Fix loading indicator creating scroll in some browsers

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11310]
Go to sec 48: https://drive.google.com/file/d/0B4eH8CZ7LTcqZmlubmFzcFJYM2c/view

The overflow of the loading animation it's doing this, ```overflow: hidden``` should fix it.

**Loading indicator have to two modes: inline (in login) and fullscreen (iframe) make sure it works on both**

## Expected Behavior
- Loading indicator shouldn't crate scroll bars in any browser.

## Current Behavior
- Scroll bars show when loading indicator appear on the screen.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to login page
2. Enter user and password
3. Scroll bars appear when loading indicator show

## Context
N/A

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: All
* Operating System and version: All
* Application Server and version: N/A
* Java Brand and version: N/A
* Database and version: N/A
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=90e33528-89ed-45b0-97b8-b9b6af0805cb
