### ISSUE TITLE
Move ContentHookAbstract methods to the interfaces

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11320]
When changing or adding a method signature to the content api, it is painful because one needs to add it to  6, no 7, places, the 

1. ContentletAPI
2. ContentletAPIInterceptor
3. ESContentletAPIImpl
4. ContentletAPIPreHook
5. ContentletAPIPostHook
6. ContentletAPIPreHookAbstract
7. ContentletAPIPostHookAbstract

Moving the hook methods from the Abstracts to the interfaces would remove at least 2 of these changes

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11393

**Comment by jgambarios** [comment]
**Note to QA:** For this ticket we need to test the content hooks OSGI plugins

**Comment by oswaldogallango** [comment]
The OSGI com.dotcms.hook work fine with these changes, also the BinaryExporterServler and ContentletAPI are working fine
