### ISSUE TITLE
Content with long names not fitting in the drop down

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11323]
We have content that has long names and it isn't fitting in the drop down view when trying to relate it to other content

<img width="1680" alt="screen shot 2017-04-17 at 8 26 48 am" src="https://cloud.githubusercontent.com/assets/8225685/25091684/a44cf8ea-2347-11e7-9be6-e489e21428e6.png">

Client Ticket: https://my.dotcms.com/tickets/detail.dot?id=b3de284c-3c89-45ae-9b93-ecc3303bf6b4

dotCMS version: 3.6.0

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/11614

**Comment by shaydotcms** [comment]
Passed QA.
Now long names are fitting in the drop down.
Tested creating different children folders and sublevels, they worked.
![image](https://user-images.githubusercontent.com/8741846/27053188-ba2590b0-4f79-11e7-9883-c0ddd799b10c.png)

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit df7ff50790f273ac67afb31fe1a376c9feecbd0c
Ubuntu 14.04.1 / Postgres 9.3.5 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
