### ISSUE TITLE
PermissionAjax.retrievePermissionable refactor

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11326]
We need to improve the code inside https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/ajax/PermissionAjax.java#L322-L410

We need to find and implement a better way to resolve the passed permissionable id.

As reference:
https://github.com/dotCMS/core/pull/11283
https://github.com/dotCMS/core/compare/issue-11221-proposal?expand=1
https://github.com/dotCMS/core/compare/issue-11221-proposal-2?expand=1

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/11221

**Comment by wezell** [comment]
Can come back to this
