### ISSUE TITLE
Unable to see the themes in the template designer 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11329]
## Expected Behavior
We should have the theme list on the theme drop-down in the template designer 

## Current Behavior
The field is in blank 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Site --> Templates 
3. Try to add a new template with the template designer 
4. Select the theme

## Your Environment
Tested on master-4.1 // H2 // FF & Chrome

**Comment by wezell** [comment]
![screen shot 2017-04-17 at 1 33 35 pm](https://cloud.githubusercontent.com/assets/934364/25097432/848abdfa-2372-11e7-953d-2f316d397418.png)

This worked for me.

**Comment by bryanboza** [comment]
Yes, sorry something wrong in with my local index or cache, after update to the last code and start with a fresh environment that woks for me too...
