### ISSUE TITLE
Make sure we respect VELOCITY_ROOT everywhere

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11338]
We have a config variable called `VELOCITY_ROOT` that currently points to our velocity folder under our web-inf - `/WEB-INF/velocity`

1. There are places in our code where we do not respect this variable.  We need to use the `VELOCITY_ROOT` folder everywhere in the codebase 
2. We need to be able to configure this `VELOCITY_ROOT` folder to be outside of the .war path
3. Like all our config, we need to allow this to use env variables.
4. We need to make sure that an osgi based velocity portlet can be deployed without writing to `/WEB-INF/velocity`

**Comment by dsilvam** [comment]
This is dup of https://github.com/dotCMS/core/issues/11303
