### ISSUE TITLE
SAML plugin and ADFS 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11349]
- [x] entityId is wrong- it should default to the main hostname of the Site that SAML is configured on, not of the global default Site. If your default host does not have SAML configured and you are only using it for 1+n non-default hosts, SAML will not work at all with the way it is now.

- [x] The nameIdFormat is critical. When we are mapping to userId, we cannot use the transient nameIdFormat because that will send a new value and create a new dotCMS user on every login. Our default should be persistent, and we should not offer transient at all

- [x] We are sending an encryption cert to the IdP. In prior testing, encryption does not work and is not a feature we are focused on. Assertion encryption is completely different from assertion signing.  Remove encryption from the assertion signing.

**Comment by jdotcms** [comment]
The second one looks easy
https://github.com/dotCMS/plugin-dotcms-openSAML3/blob/master/src/com/dotcms/plugin/saml/v3/meta/DefaultMetaDescriptorServiceImpl.java#L186

Just remove the Transient format from the array.

**Comment by jdotcms** [comment]
More docu, about the #1 
![saml_config](https://cloud.githubusercontent.com/assets/19578350/25246689/a7d6b6a6-25c5-11e7-8865-e0e485d6504f.png)

**Comment by jdotcms** [comment]
```
Here’s what we need...
If dotcms.saml.service.provider.issuer ($issuer) is set on the Site config, then:
in metadata.xml:
- entityID = “$issuer"
- AssertionConsumerService Location = "$issuer/dotsaml3sp"
in the AuthnRequest:
- AssertionConsumerServiceURL = "$issuer/dotsaml3sp"
- saml2:Issuer = “$issuer"
If dotcms.saml.service.provider.issuer ($issuer) is NOT set on the Site config, then:
in metadata.xml:
- entityID = "https://$sitebasehostname"
- AssertionConsumerService Location = "https://$sitebasehostname/dotsaml3sp"
in the AuthnRequest:
- AssertionConsumerServiceURL = "https://$sitebasehostname/dotsaml3sp"
- saml2:Issuer = "https://$sitebasehostname"
```

**Comment by bryanboza** [comment]
This is for 3.7 and was tested by Chris in the development process

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/plugin-dotcms-openSAML3/pull/15
