### ISSUE TITLE
Unable to run structure reindex from the content search tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11347]
Since previous versions we have the option to run a structure reindex in any structures from this tab, but right not we are trying to run a reindex but we are trying to run a reindex with a null inode... 

## Expected Behavior
We should be able to catch the correct structure inode and run the reindex without problems 

## Current Behavior
The system is sending a null inode and send a WARN in the log, the the reindex isn't running 

Here the log: 
```
 WARN cache.LegacyContentTypeCacheImpl: Structure with inode: '' not found in db
```
**FYI:** Works as expected if you go to the maintenance tab, select the structure and run an individual reindex 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Content // Search 
3. Select any structure in the type drop-down
4. Click the "..." button and try to reindex 
5. Check your logs 

## Your Environment
Tested on master-4.1 // H2 // Chrome

**Comment by oswaldogallango** [comment]
The reindex was running but there wasn't any log or notification showing that was running. Now some notification and logs are included. P.R https://github.com/dotCMS/core/pull/11400

**Comment by bryanboza** [comment]
Fixed, now we have info in the log and notification... Nice work!!!
