### ISSUE TITLE
Upgrade Gradle version in enterprise, license and OSGI plugins

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11346]
This is in the wrapper

**Comment by danlaguna** [comment]
The upgrade has been completed. Here are the Pull Request URLs where this was modified: 
- EE: https://github.com/dotCMS/enterprise-2.x/pull/465
- License: https://github.com/dotCMS/license/pull/48
- Plugin Seeds (against master-4.1): https://github.com/dotCMS/plugin-seeds/pull/6
