### ISSUE TITLE
Full reindex does not properly set index replica count w/ autowire

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#11351]
When you run a full reindex, at the completion of the reindex ESIndexAPI.moveIndexBackToCluster() does not correctly set the index replica count when you are using autowire clustering (sets to zero replicas).

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11352

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
