### ISSUE TITLE
Unable to load the permissions tab on widgets 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11359]
We still having problems loading the permissions tab with some content types

## Expected Behavior
We need be able to set permissions to some widget 

## Current Behavior
The permissions tab isn't loading and leave a blank page 
SC: https://screencast.com/t/LNSB4Wpxtk

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new page 
3. Add a new widget to that page 
4.  Try to set permissions to this widget 

## Your Environment
Tested on master-4.1 // H2 // IE11 & FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11361

**Comment by bryanboza** [comment]
Fixed, tested in the last master-4.1 // postgres // FF
