### ISSUE TITLE
Unable to remplace files under the resources folder with plugins 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11350]
We are having problems using  the ROOT folder in plugins replacing some files via static plugin, the system isn't replacing the original file 

**FYI :** If you try with some other file in a different location or any other folder into the resources, this works without problems, the error is just on the resources path... 

## Expected Behavior
All the files inside the project should be replace by the content inside the  ROOT folder without problems 

## Current Behavior
After deploy plugins, the original files don't have changes 

## Steps to Reproduce (for bugs)
1. Create a copy of the hazelcast-embedded.xml file in to the plugins ==> com.dotcms.config ==> ROOT ==> dotCMS ==> src ==> main ==> resources
2. Do some configuration in this property 
3. Try to deployWarTomcat
4. Check the file in ROOT ==> WEB-INF ==> classes ,  to make sure have the changes 

## Your Environment
Tested on master-4.1

**Comment by wezell** [comment]
This is because you are trying to use a static plugin to against the ./src code which has a different directory structure than.  I think we need to do our tests against only distro  builds.

**Comment by bryanboza** [comment]
Yes, I know we should test with the nightly builds, but some days ago we was having some problems in Jenkins and we are not building over release-4.1, then I am compiling the code in a dev environment. Also some times we need test on that way to avoid wait to the next build... For me is more like a dev issue...
