### ISSUE TITLE
Permissions problems adding content as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11365]
We are having a "Content locked" message when you add permissions over some content type to a limited user

## Expected Behavior
After you add permissions over the content type to some limited user you don't need any other permissions to allow create new pieces of content 

## Current Behavior
After you add permissions we still having a permissions error message 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types edit the "**Simple Widget**" permissions
 3. Add permissions to "**Chris Publisher**" 
<img width="1236" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25257125/01beed64-25f3-11e7-9c63-07a6b1630690.png">

4. Logout 
5. Login as "**Chris Publisher**"
6. Go to Content ==> Search
7. Try to add a new simple widget 
<img width="1248" alt="bug2" src="https://cloud.githubusercontent.com/assets/2641437/25257179/6983418e-25f3-11e7-8d94-9b765ac9b5cd.png">

Here the log: https://gist.github.com/bryanboza/f23a459e1dff795738b75ad185468deb

## Your Environment
* dotCMS version used: Master-4.1
* Browser Name and version: Firefox
* Operating System and version: Mac_OSX
* Application Server and version: Tomcat8
* Java Brand and version: Java8
* Database and version: Postgres

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11433

**Comment by bryanboza** [comment]
After the last changes we still having problems, by default anonymous user  should have permissions over the site, if you add permissions to some structure, you should be able to add content to this structure, now if you add permissions to any structure and try to navigate to content search tab we have this error: https://gist.github.com/bryanboza/8d61610eea39cda409e11e05337c3354

**Comment by oswaldogallango** [comment]
@bryanboza the error that you are mentioning is different to the one reported in this issue. The error you are putting there is not related to the content locked, but this one seems that is related with the host permission on the sub_nav.jsp

28/04/17 17:49:06:411 CST] ERROR business.HostAPIImpl: User : dotcms.org.2795 does not have permission to a host
com.dotmarketing.exception.DotSecurityException: User : dotcms.org.2795 does not have permission to a host
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findDefaultHost(HostAPIImpl.java:118) [dotcms_4.1.0_ad062aa.jar:?]
	at org.apache.jsp.html.portlet.ext.contentlet.sub_005fnav_jsp._jspService(sub_005fnav_jsp.java:740) e.

**Comment by bryanboza** [comment]
Unable to recreate after the last changes... Fixed...
