### ISSUE TITLE
Need improve messages when you don't have permissions to edit some content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11366]
Need improve the way to show permissions error when you can't edit some piece of content 

## Expected Behavior
As in the other maybe we should show a black pop-up with the permissions message and continue normally 

## Current Behavior
When you try to edit some content and you don't have permissions, the system shows this message "Unfortunately this has caused a problem. Please try again. ", maybe we can improve that to avoid look broken 

## Steps to Reproduce (for bugs)
1. Enable the property ALLOW_VELOCITY_SQL_ACCESS_TO_DOTCMS_DB in the dotmarketing-config. properties file 
2. Start dotCMS
3. Login as admin
4. Create a new page and add a pice of content with some query 
```
$sql.getSQLResults("default","select * from inode limit 10",0,0))
```
5. Make sure as admin the system is resolving the query 
<img width="1240" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25284210/8ead8f34-2673-11e7-9ced-de4fe260ab25.png">
6. Give edit permissions of this page to some limited user **(Chris Publisher)**
<img width="1259" alt="bug2" src="https://cloud.githubusercontent.com/assets/2641437/25284226/988260d4-2673-11e7-8b11-24f3f5ed5024.png">
7. Login as **(Chris Publisher)**
8. Try to edit the piece of content 
<img width="1255" alt="bug3" src="https://cloud.githubusercontent.com/assets/2641437/25284289/ce447b44-2673-11e7-883d-68a69fd383de.png">

LOG: https://gist.github.com/bryanboza/23705adcda5d11922b033f4abf70823d

## Your Environment
Tested on master-4.1 // H2 // FF

**Comment by wezell** [comment]
Can be addressed to a new ui
