### ISSUE TITLE
Fix integration tests failing in Jenkins

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#11363]
The following tests are failing in Jenkins for any DB and need to be fixed:
 

- com.dotmarketing.filters.CMSFilterTest.shouldWorkVirtualLinkCMSHomePage
-  com.dotmarketing.filters.CMSFilterTest.shouldWorkVirtualLink
-  com.dotmarketing.portlets.virtuallinks.business.VirtualLinkAPITest.getVirtualLinksByTitleAndSiteList
-  com.dotmarketing.portlets.virtuallinks.business.VirtualLinkAPITest.getIncomingVirtualLinks
-  com.dotmarketing.portlets.virtuallinks.business.VirtualLinkAPITest.getActiveVirtualLinks
-  com.dotmarketing.portlets.virtuallinks.business.VirtualLinkAPITest.getVirtualLinksByURI
-  com.dotmarketing.portlets.virtuallinks.business.VirtualLinkAPITest.getVirtualLinksByTitleAndUrl

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11367
