### ISSUE TITLE
Errors generating a past time machine snapshot

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11373]
We are having some errors on log creating past time machine snapshots

## Expected Behavior
The snapshot should be created without problems, and allow see this in all the supported browsers 

## Current Behavior
The system is showing some errors on log 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Site ==> Time Machine 
3. Generate a new snapshot with the default options 
<img width="534" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25291248/7fd1e4e0-268e-11e7-8dfd-22bdf4805e13.png">
4. Check the logs 

Log error: https://gist.github.com/bryanboza/46ec2ec3f15973919e4bf1efb500753d

## Your Environment
Tested on master-4.1 // H2 // IE11 and FF

**Comment by jcastro-dotcms** [comment]
Note to QA: This issue is not reproducible with the latest pull form Git. No errors are displayed in the ``dotcms.log`` file after kicking off a Time Machine using the input data specified in this ticket. Used DBs are H2, PostgreSQL, and MySQL.

**Comment by bryanboza** [comment]
Unable to reproduce after retest, something wrong on my local
