### ISSUE TITLE
Error creating reports in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11375]
We are having a hibernate issue trying to create a new report in dotCMS

## Expected Behavior
Need allow create new reports without problems 

## Current Behavior
The system is showing the follow error and the report never is created 
```
ERROR action.EditReportAction: Unable to save Report: com.dotmarketing.exception.DotHibernateException: Unable to save Object to Hibernate Session 
```

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to roles and Tabs and add the report portlet 
3. Try to create a new report with  the attached file 

**FYI:**  This file has been tested in previous versions  

Here the file: https://drive.google.com/a/dotcms.com/file/d/0B0jytRKu5p1KTkRPZVM5UGsxVmc/view?usp=sharing

## Your Environment
Tested on master-4.1 // H2 // FF

**Comment by wezell** [comment]
Report functionality should be removed.
