### ISSUE TITLE
Can't emulate devices in edit mode and small screens

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11372]
When you are in *edit mode* and your screen is small (I'm in a MBP 15") you don't have access to select the devices to simulate: 

<img width="770" alt="screen shot 2017-04-21 at 12 04 25 pm" src="https://cloud.githubusercontent.com/assets/751424/25290392/1bdc5d06-268b-11e7-8b92-397ed129759f.png">

## Expected Behavior
Edit mode sidebar should scroll.

## Current Behavior
Edit mode sidebar doesn't scroll.

## Possible Solution
Add some ```overflow: scroll``` to the sidebar should do the trick

## Steps to Reproduce (for bugs)

1. Apply entreprise license
2. Go to edit mode (resize your Browser Windows if necessary)
3. Try to access the "On" device section on the right sidebar.

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: All
* Operating System and version: All
* Application Server and version: All
* Java Brand and version: All
* Database and version: All

**Comment by wezell** [comment]
Edit mode will be addressed in a future iteration
