### ISSUE TITLE
Unable to see the image of the events from FE 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11388]
Problems with the events if you add some image to any envent, then go to front-end and try to see the event.... 

## Expected Behavior
The system should show the event with the associated image without problems 

## Current Behavior
The system isn't showing the image 
![bug1](https://cloud.githubusercontent.com/assets/2641437/25352470/5bb2264e-28e9-11e7-8be8-f56cdfa97744.png)

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to calendar portlet 
3. Add a new event and assign some image to the image field (anyone)
4.Save the event 

## Your Environment
Tested on master-4.1 // postgres // FF

**Comment by wezell** [comment]
Moved to starter work:

https://docs.google.com/document/d/127dCwikrz_YAokQRamvjp0ehzEAIDhBnBQd0bBRk64A/edit
