### ISSUE TITLE
Error resolving invalid pages if you remove the 404 vanity URL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11395]
We are having a NPE if you try to resolve some invalid URL and you was removed the 404 vanity URL, maybe is not a major bug, but we should have a better fail here 

## Expected Behavior
WE should handle this exception and show a better error 

## Current Behavior
The system show this error on log and error on browser too 

Here the log: https://gist.github.com/bryanboza/0bc8f94a7da9eb6b06007ac1f0d1c075

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to the vanity URL page and delete the 404 vanity 
3. Try to resolve an invalid URL 

## Your Environment
Tested on master-4.1 // postgres // FF

**Comment by jcastro-dotcms** [comment]
Unable to reproduce. The 404 page is not being displayed, only the default dotCMS 404 message. Working as expected.

**Comment by bryanboza** [comment]
That's an old issue, unable to reproduce in the last master
