### ISSUE TITLE
Problems deleting multiple fields from content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11401]
We are having an error when you try to delete more that one field from any structure 

## Expected Behavior
We should be able to delete multiple fields without problems 

## Current Behavior
If you delete just one field everything works ok, but after delete another one, the system shows an error 

Here the log: https://gist.github.com/bryanboza/01f55ba3030f51bf75af2bfdd3cb71f0

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types and select the youtube structure
3. Try to delete 2 or 3  fields continuously 
4. Check your dotcms.log file  

## Your Environment
Tested on master-4.1 // postgres // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11429

**Comment by bryanboza** [comment]
We need auto refresh after finish to load the filed... Right now we are getting the success notification but the system isn't refreshing ... SC: https://screencast.com/t/QEHhHoYqBg

**Comment by jgambarios** [comment]
@bryanboza please create a different ticket for that improvement.

**Comment by bryanboza** [comment]
Fixed, some new improvement here: #11447
