### ISSUE TITLE
[Improvement] Dynamic/OSGI plugins Tool

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11404]
Client has a lot of experience on the OSGi development and support. He created the list below with really nice improvements that we should implement on dotCMS. I tried to find if we had some of this issues reported but then I thought we could use this ticket as an EPIC.

1. Sort list by column headers.
2. Filter list by filter text.
3. Show file date of jar. (Helps determine version if not part of name.)
4. Show upload date of jar. (Helps determine history/audit trail.)
5. Show upload user of jar. (Helps determine history/audit trail.)
6. Add "Restart" option to stop/start plugin in one click.
7. Add "Redeploy" option to undeploy/deploy plugin in one click.
8. Add new State "Error" for plugins which encountered errors starting. (Currently plugins show as "Resolved" but not "Active" if an error occurred on start. This makes it hard to identify whether a plugin was intentionally stopped for a time or if it is having issues starting up.)
9. Color coded indicators (Like the one's for content publishing status.) Orange dot for "Resolved", Green checked dot for "Active", Red dot for "Error".
10. If "Error" state, add a link to view the errors thrown by the plugin.
11. Make the jar file a clickable link to download the jar in your browser.
12. Make a link to download all jar files as compressed ZIP or TAR file.
13. Provide historical audit trail for plugins, i.e. who, when, what.
14. Allow plugins to be added to a Push Publishing bundle.
15. Allow plugins to be loaded from a Push Publishing bundle.
16. Add plugin profiling tools.  (How often the plugin's code is executed in the JVM, average cpu footprint, average memory footprint etc.) (Make an option to turn on profiling for a given plugin or all plugins.)
17. Add a system report to reveal all active Tuckey filters and their origin if possible (System Value/static plugin/osgi plugin etc. Identify plugins by name if possible?). (Perhaps on a different maintenance page, but this is directly related to plugins.)
18. Add compression support, bulk upload support. I.e. upload a ZIP or TAR of plugin jars. (Server would then decompress/unzip/untar and deploy.)
19. Add Bulk Action options. I.e. stop/start/restart, undeploy/deploy/redeploy, all plugins in one click. (Restarting the framework kind of does this, but only in one direction.)
20. "Tag" plugins by GenericBundleActivator class methods used by plugin, then display the tags in the list. (ViewTool, Servlet, Tuckey, Post-Hook, Pre-Hook, Portlet, Struts, Rule, Actionlet, Quartz Job, etc.) (This will help identify what services the plugin added at a glance.)
21. Provide an on-demand report overview of "Objects" added by a given plugin. (Kind of like the "Tag" concept, but more detail here.) Report would show either object class names or text values added by the various GenericBundleActivator class methods used by plugin. I.e. "ViewTool added, class: MyViewTool.class, key: $mVT", "Servlet added, class: MyServlet.class, path: /app/myServlet", "Tuckey Filter added, filter:^/asdf?/$ , forward:/xyz/", "Post-Hook added, class: MyHook.class" (Display the most useful and relevant meta-data per type.)  (Some of this information is printed to the log on start, but not easily retrievable later in the life cycle.)

Support ticket: https://my.dotcms.com/tickets/detail.dot?id=b9e24803-5f07-4633-bc96-1928aef4a47f

**Comment by nkeiter** [comment]
Perhaps an “OSGI plugins as content” approach could be used. Similar to FileAsset, there could be a special content type called PluginAsset. This would allow those “Tags” I suggested to be easily added by the system to the contentlet. This would also allow for an audit trail, and even permissioning. There could be a field to hold “meta-data” about the plugin and what objects were added, a field to hold start errors, etc. Obviously there would also be a field to hold the binary of the jar file itself. The jar name could be the unique id of the contentlet (or at least a field marked required and unique.) Published plugins would be loaded and deployed, unpublished plugins would be undeployed, but still “exist” as content. (All that would be needed would be a special post-hook to do the file system part.) All the power of the existing content engine could be leveraged against the plugins, including push publishing.

One downside to this approach would be that plugins could no longer be “dropped” into the file system's /felix/load folder. Maybe not a bad thing though? Perhaps the directory listener could add/update the contentlet automatically if it detects a plugin that is dropped in? And if a plugin is deleted from the file system it could automatically unpublish the contentlet? This would also expose plugins to the REST API, but if properly permissioned, that wouldn't be an issue.

Just some ideas for the development team. I remember the goal once was “everything is content.” :)
