### ISSUE TITLE
Documentation for Hook up AutoCluster to Hazelcast 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11416]
Documentation for https://github.com/dotCMS/core/issues/11124

Please read: https://github.com/dotCMS/core/issues/11124#issuecomment-297594115

**Comment by DeanGonzalez** [comment]
Documented: https://dotcms.com/docs/latest/hazelcast-cluster-transport-configuration

**Comment by DeanGonzalez** [comment]
done
