### ISSUE TITLE
Mobile preview on templates isn't simulating devices

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11413]
As in the content editing, when you are in the templates portlet and go to the preview, we have the option to see the preview on some mobile devices, but when you select this option the system just reload the preview in a new tab, but isn't simulating the device 

## Expected Behavior
As in the content editing we need show the template in a device 

## Current Behavior
Just load the template in a new tab, but you can't look the device 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Site => Templates
3. Try to edit any template
4. Go to Preview tab
5. On Mobile Preview drop-down select some device 
6. Make sure you see the template in the device 

## Your Environment
Tested on master-4.1 // Postgres // Chrome

**Comment by wezell** [comment]
The preview button has always popped open a new window the size of the device.  It does not do it inline.  Maybe it should but it seems that this functionality has been superseded by the page level preview anyway.
