### ISSUE TITLE
Error when trying to deploy OSGI com.dotcms.portlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11417]
When the [Portlet OSGI plugin ](https://github.com/dotCMS/plugin-seeds/tree/master-4.0/OSGi/com.dotcms.portlet) is tried to be deployed, it ends in "Resolved" state. 

After taking a look, the problem is a ClassNotFoundException in this line:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/osgi/GenericBundleActivator.java#L353

After debugging and comparing to the previous code, the problem is that the wrong classloader is being used (dotcms). We need to specify the proper classloader.

**Comment by jgambarios** [comment]
**Note to QA:** This ticket is related to: https://github.com/dotCMS/core/issues/11420

**Comment by bryanboza** [comment]
Fixed, after this changes, now you can deploy and upload the plugin without problems
