### ISSUE TITLE
Reformat Workflow Actions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11423]
When a user clicks on a workflow action, we need to make the edit action page look like this - this work needs to be done in dojo

![workflow](https://cloud.githubusercontent.com/assets/934364/25500819/71a13f90-2b5e-11e7-9dba-31b076651226.png)

### Page to redesign:
1. Types & Tags
2. Workflow
3. Select a Workflow
4. Add Workflow Action button or click in one of the created actions

**Comment by woontsoudev** [comment]
Completed...
Core: (https://github.com/dotCMS/core/pull/11504/commits/6fa7f820d05794c7ac1bfbda7b8eccdb2684b8ae)
Dojo-theme: (https://github.com/dotCMS/dotcms-dojo-theme/pull/32/commits/33373782360828136650ff28be094a8964d4331a)
