### ISSUE TITLE
Design Content Type Listing Page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11424]
This listing page is generic enough to serve as a template for our other listing pages.  Speak with @fishsmith on look and feel

Column names:
- Name	
- Variable	
- Base Type 
- Entries (count of the entries)

**Comment by fmontes** [comment]
![content type listing](https://cloud.githubusercontent.com/assets/751424/25855919/ba91c2ce-3491-11e7-8979-7992c5b12a3f.png)
![content type listing selected](https://cloud.githubusercontent.com/assets/751424/25855917/ba59197e-3491-11e7-8c54-ea4cd186a6c9.png)
