### ISSUE TITLE
Unable to upload content to the binary fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11431]
We are having a js error trying to upload some file to the binary fields 

## Expected Behavior
Need be able to upload content to any field without problems 

## Current Behavior
We have a JS error and isn't uploading the file 

ERROR: ReferenceError: FileAjax is not defined 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type
3. Add a new binary field 
4. Go to Content Search tab and try to add some content to the new structure 
5. Select some file to upload to the binary field 

## Your Environment
Tested on master-4.1 // Postgres // FF

**Comment by wezell** [comment]
Please make sure you can reproduce
