### ISSUE TITLE
Things to test with the #dotParse and #parseContainer changes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11437]
In 4.1 we've moved what used to be macros to be velocity directives, which is better for memory and parsing performance.  This includes:

#dotParse(path)
and 
#parseContainer (container_id)

So the big thing we need to test is whether anything has changed with regards to how we handle .vtl includes vs. what our existing behavior is.  These changes will allow us to really tweak how we handle multi-lingual capabilities because we can change our behavior in code rather than in velocity.
This change might break existing functionality or fix functionality that has been long broken.

1. Live/working rendering
- does this work with #dotParsed VTLs?
- does this work with Containers?
- what happens in edit mode if a dotParsed VTL only has a working version?
- what happens in live mode  if a dotParsed VTL only has a working version?
- is this different than what happens currently?

2. Multi-lingual pages
- Has anything changed with how we render .vtls and containers on multi-lingual pages?
We need to test all these dotmarketing-config switches and make sure we behave at least as well as we do in 4.0
```
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=false
DEFAULT_WIDGET_TO_DEFAULT_LANGUAGE=true
DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true
```
- what happens in edit mode if a dotParsed VTL only has a version in the default language?
- what happens in live mode  if a dotParsed VTL only has a working version?

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/11362

**Comment by oswaldogallango** [comment]
These are the results of the tests https://docs.google.com/document/d/1gU_7sDf57jw_dTUDJ_ZPGIJIMjutWaVUxfZ_7j9VWYU/edit?ts=590b509c

**Comment by bryanboza** [comment]
Tested every one of the cases and here are the results https://docs.google.com/document/d/1gU_7sDf57jw_dTUDJ_ZPGIJIMjutWaVUxfZ_7j9VWYU/edit# , new issue detected here #11542 ... In general now 4.1 works better than 4.0...
