### ISSUE TITLE
When you remove the asset of a Binary field the asset is still related

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#11430]
## Expected Behavior
If you remove the asset of a binary field and make the REST API call to that content, the binary field should be empty.

## Current Behavior
If you remove the asset of a binary field and make the REST API call to that content, the binary field still shows the path of the asset.

## Possible Solution
Check in the filesystem if the asset on that path exists, if don't exists the binary field value should be empty.

## Steps to Reproduce (for bugs)
1. Create a content-type with a Binary Field and a Text Field.
2. Create a content of the previous content-type, fill both fields.
3. Click on the Search button
4. Copy the REST API Call
5. Paste it in a browser tab
6. Both fields (the binary one and the text one) should have values
7. Edit the content created in step 2
8. Remove the asset on the binary field
9. Save and Publish
10. Repeat steps 3-5
11. The Binary field still shows the value regardless we removed the asset.

## Context
Client's Ticket https://my.dotcms.com/tickets/detail.dot?id=a7d7314a-d666-4321-9f47-15e71911f532

## Your Environment
* dotCMS version used: v3.5.1 and demo.dotcms.com (v4.0.1)

**Comment by gabbydotCMS** [comment]
Also reported on https://my.dotcms.com/tickets/detail.dot?id=49808174-52b6-4b48-a028-a28c2f3f0967

**Comment by brentgriffin** [comment]
Another client has run into this problem:  https://dotcms.zendesk.com/agent/tickets/94657

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12978

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now works as expected
