### ISSUE TITLE
Concurrent PP can send bundle again and again

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11432]
Note: this is impacting our ability to launch on the product.

While a push publish of a bundle in running, it is possible for the PublisherQueueJob to be triggered again (up to PUBLISHER_QUEUE_MAX_TRIES times) by Quartz (per the cron-style schedule) even if a previous run is still in flight on the destination server. 

What we are seeing:
- A single new bundle is created and added to the publish queue
- The PublisherQueueJob is triggered by Quartz and picks up the bundle
- The bundle is transmitted to the server and the status is updated to PublishAuditStatus.Status.BUNDLE_SENT_SUCCESSFULLY.getCode() by PushPublisher.process line 197 (we see the corresponding log output confirming this is occurring)
- The EndpointDetail status is updated to Status.PUBLISHING_BUNDLE at this point.
- At this point, the remote endpoint is unpacking the tarball and processing the contents. Assume this will take more than 1 minute meaning it will still be running when the next step occurs.
- At the next trigger instance for the PublisherQueueJob (top of the next minute), the job checks for bundles in BUNDLE_SENT_SUCCESSFULLY and endpoints in PUBLISHING_BUNDLE statuses in the updateAuditStatus() method. If we're on the second try (assuming PUBLISHER_QUEUE_MAX_TRIES is the default of 3), it allow the execute() method to proceed at which point the PublisherAPIImpl.getQueueBundleIdsToProcess() method selects the same bundle we've been talking about because it's status is still BUNDLE_SENT_SUCCESSFULLY.
- The PublisherQueueJob resends the bundle tarball which is received by the endpoint still processing the tarball from earlier.
- The REST endpoint on the push publish target immediately tries to delete the working directory for the bundle but, because there is an existing job running, there are file locks. This is exasperated in a clustered situation because the bundles are stored on NFS (as a subdirectory of the ASSETS directory which is required to be on shared storage) which results in open hard links, per the NFS spec.
- This means the delete operation does not complete because you can't delete non-empty directories. Since the criteria for the publish to proceed is that the directory exists, it proceeds with the partially deleted content which causes this second job to fail since most of the files from the tarball were deleted during the FileUtils.deleteDirectory() operation and the contents of the new tarball were never extracted.
- This looping of the PublisherQueueJob continues each minute until PUBLISHER_QUEUE_MAX_TRIES is encountered when the entire job fails even though a good chunk of the content from the very first bundle sent by PublisherQueueJob may have been processed before subsequent bundles were received causing the source work directory to be partially deleted.

This is all a long winded way of saying, you need to remove the status BUNDLE_SENT_SUCCESSFULLY as a criteria for PublisherAPIImpl.getQueueBundleIdsToProcess(). You also need to modify the PublisherQueueJob.updateAuditStatus() method to exclude the status BUNDLE_SENT_SUCCESSFULLY and PUBLISHING_BUNDLE when determining if the publish attempt should be incremented when comparing against PUBLISHER_QUEUE_MAX_TRIES. This may need to be done directly in PublishAuditAPIImpl.getPendingPublishAuditStatus() though that may have side effects.

Edit from Oscar: Notice that this behavior is dotCMS 3.6.0, we need to be careful with any change because all of this logic changed heavily for Static Publish.

**Comment by brentgriffin** [comment]
https://my.dotcms.com/tickets/detail.dot?id=c0166c45-3627-406e-9abd-89088cb64ce3

**Comment by wezell** [comment]
```
I just performed an additional publish with a large bundle and monitored both the log output and changes to the publishing_queue_audit.status column for the bundle and I think I have a better idea of what is going on.

Here is the actual flow as best I can tell:

Publishing kicks off and begins bundling (status = 2)
Publishing begins sending the bundle to endpoints (status = 3)
Bundle sent to all endpoints with HTTP response code 200 (status = 10)
At this point, the remote endpoints are processing the bundle. On the next activation of the PublisherQueueJob, the following happens:

The bundle is still in status of 10 (BUNDLE_SENT_SUCCESSFULLY)
The PublisherQueueJob.execute() method calls the private updateAuditStatus() method which picks up bundles including those in status 10
The endpoints are contacted for status on the bundle. Assume:
At least 1 endpoint returns SUCCESS (countGroupOk > 0)
At least one endpoint returns PUBLISHING_BUNDLE (countGroupPublishing > 0)
No endpoints return FAILED_TO_PUBLISH (countGroupFailed == 0)
The resulting if/elsif/else logic will fall through to the final else ( commented: “Otherwise, just keep trying to publish the bundle”) which sets the bundle status to 13
The execute() method continues processing and picks up the same bundle that was just processed because it is currently in status 13.
The bundle is resent to the publishing endpoints which triggers the untar method and the FileUtils.deleteDirectory described above resulting in corruption of the working directory of those publishing endpoints still in the PUBLISHING_BUNDLE status and causing the entire publish operation to fail
```

**Comment by oarrietadotcms** [comment]
From Client:

I attached a git-style patch that fixes this issue. Essentially, this patch recognizes when some of the targets in the environment are still in progress if one or more of the targets in that environment return an error status, allowing the in-progress nodes to proceed to a complete state of either success or error. It also modifies the logic that selects bundles for publishing and auditing to recognize the WAITING_FOR_PUBLISHING status which is a bit of an orphan in the code.

There is a side effect I was able to reproduce but I believe the same side effect would have triggered the issue this fixes. For publishing target clusters where the assets directory is backed by NFS (which is the required architecture) and the NFS mount uses the “hard” option and the connection to the NFS server is lost, the local publish thread on the target machine will hang and fail to update the bundle status. This patch will leave the bundle status on the publishing source in “Waiting for publishing” unless the publishing target database is manually updated to change the publishing_queue_audit table status and pojo_status values indicating a failed state and the publishing target JVM is restarted.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11498

The solution proposed by the customer is correct. Bundles are not being re-sent **unless they are associated to a failure status** now. Local developer tests were performed by placing a breakpoint on the publishing process of a receiver environment in order to simulate a big-sized bundle. An external environment and a real big bundle are ideal for official testing.

**Comment by jgambarios** [comment]
**Note to QA:** @bryanboza please coordinate with me to see what is the best way to test this issue, probably we will need help from Chris in order to set up a test environment.

**Comment by bryanboza** [comment]
Tested with the client environment... Passed QA
