### ISSUE TITLE
Need auto-refresh after delete some field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11447]
Related to #11401 

When you delete some field, the system is firing 2 notifications, one when the system start to delete, and the other one after finish... In previous versions we have the refresh after the system start to delete, then in structures with a los of data this does not work.... But right now we are not refreshing at all, we need move this refresh after the success notification 

## Expected Behavior
We should refresh the structure after finish to delete to see the changes 

## Current Behavior
The system is deleting the field, but isn't refreshing to see the changes, you need refresh manually 

## Steps to Reproduce (for bugs)

1. Login as Admin 
2. Go to "Types & Tags" => Content types 
3. Select some content type and delete some field 
4. Wait the system refresh 

## Your Environment
Tested on master-4.1 // Postgres // FF & Chrome

**Comment by wezell** [comment]
We will address with new ui
