### ISSUE TITLE
Externalize Tomcat Configuration

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11446]
In the quest to allow a dotcms installation be completely externalized, we are missing one piece -  the tomcat server itself.

We need to allow the tomcat to be able to read its config (if needed) from environmental or system properties just as we now do with dotcms config.

This change requires a change to our tomcat dependency - we need to add a class to the ./lib folder and add a line to the catalina.properties file

For more information on this, see:

http://stackoverflow.com/questions/11468881/externalize-tomcat-configuration

1. Test https://github.com/dotCMS/dotcms-context-property-decoder and make sure it compiles to a .jar
2. Add .jar to our tomcat that we use in the distro under the /lib directory
3. Add property to the tomcat we ship with our ./conf/catalina.properties to call our jar `org.apache.tomcat.util.digester.PROPERTY_SOURCE=com.dotcms.tomcat.context.TomcatPropertyDecoder`

**Comment by jtesser** [comment]
We actually use to do this with our tomcat years ago before 1.9 :-)

**Comment by wezell** [comment]
You can install this to add environmental variables to your osx:

https://github.com/hschmidt/EnvPane
