### ISSUE TITLE
Unable to open past time machine snapshots 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11442]
We are having problems to open past time machine snapshots, we are having different behavior in every browser 

## Expected Behavior
We need be able to open the snapshot in all the supported browsers 

## Current Behavior
We are unable to open on FF, the system try to open but leave a blank page
SC: https://screencast.com/t/7CfGTpO1V
If you use chrome the system is opening another backend in the iframe
SC: https://screencast.com/t/MXHKCi81B9N1

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Site => Time Machine 
3. Create a past time machine with the follow configuration 
<img width="600" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25551103/3a056cde-2c3d-11e7-8a48-6740f3c426cc.png">
4. Save and Run
5. Try to open the generated snapshot 

## Your Environment
Tested on master-4.1 // Postgres // FF & Chrome

**Comment by jcastro-dotcms** [comment]
Note to QA: This issue is not reproducible with the latest changes anymore. Creating snapshots in both Firefox and Chrome is working correctly. Please re-test.

**Comment by oswaldogallango** [comment]
I did the test on FF, Chrome, and Safari. On all the browsers I was able to generate the past time machine and open it. No error on logs or backend. I couldn't  reproduce this issue.

**Comment by bryanboza** [comment]
Unable to reproduce with the last code
