### ISSUE TITLE
Subtle host issue in #dotParse

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11457]
After playing with my hostnames last night testing an issue, I came in this morning and saw that some widgets were not rendering:

![screen shot 2017-05-02 at 11 02 56 am](https://cloud.githubusercontent.com/assets/934364/25624328/01d2f740-2f27-11e7-971c-4a392ecd0c12.png)

After debugging, turns out that this is because of how we were resolving the host in the new dotParse directive.  We were looking up by exact name and not falling back to default host if the name had changed, like we did in the macro.

This changes the hostname resolution to how we did it in the macro.

**Comment by wezell** [comment]
Better!

![screen shot 2017-05-02 at 11 16 03 am](https://cloud.githubusercontent.com/assets/934364/25624865/bf335388-2f28-11e7-9b66-7e3ca2753362.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11458

**Comment by bryanboza** [comment]
Fixed, tested on release -4.1 and works fine...
