### ISSUE TITLE
Wrong number of nodes on Hazelcast cluster with two members

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11463]
After adjustments made for Hazelcast implementation as part of #11124,  **Number of Node(s) in System->Configuration->Network** is still reporting a wrong number which is not reflecting the actual/real number of members in the cluster.

On a Hazelcast cluster with two nodes, it is reporting three nodes. This needs to be fixed. Please look at screen-shoot below:

<img width="1440" alt="screen shot 2017-05-02 at 11 45 27 am" src="https://cloud.githubusercontent.com/assets/22307536/25632630/987c6bf4-2f31-11e7-82b9-3a994598c752.png">

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464

**Comment by shaydotcms** [comment]
Passed QA.
Number of nodes in Network tab matches with number of nodes available after Hazelcast configuration.
Tested on dotcms 4.1.0 distribution generated from master on commit 6b1238a802537d5cc3b2ed56c0b130e52195e6a0
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
