### ISSUE TITLE
Remove CLUSTER_AUTOWIRE property and replace it with two (es, transport)

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11468]
After adjustments made for Hazelcast implementation as part of #11124, related to: https://github.com/dotCMS/core/issues/10001

CLUSTER_AUTOWIRE will be replaced with:

- AUTOWIRE_CLUSTER_TRANSPORT
- AUTOWIRE_CLUSTER_ES

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/auto-clustering-configuration

**Comment by shaydotcms** [comment]
Passed QA. File dotcms-config-cluster.properties in fact contains these two properties. 
Both AutoCluster and ManualCluster are working well with these properties
Tested on master-4.1 / dotcms_4.1.0 distribution
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
