### ISSUE TITLE
Invalid Cache Stats when using Hazelcast Client cache provider

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11464]
After adjustments made for Hazelcast implementation as part of #11124, Cache Stats in **System->Maintenance->Cache->Refresh Stats** is still reporting "0" for all stats when using Hazelcast **Client** cache provider.

This needs to be fixed. Small investigation needs to take place to determine the right stats to use for the Hazelcast Client case. Please look at screen-shoot below:

<img width="1440" alt="screen shot 2017-05-02 at 12 12 12 pm" src="https://cloud.githubusercontent.com/assets/22307536/25632888/88b262ea-2f32-11e7-80e1-b75835516e88.png">

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464

**Comment by shaydotcms** [comment]
Passed QA.
System is now showing the right stats available when using Hazelcast Client cache provider
![image](https://cloud.githubusercontent.com/assets/8741846/26378803/60175a82-3fd3-11e7-944e-bedea501dabb.png)


Tested on dotcms 4.1.0 distribution generated from master on commit 6b1238a
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
