### ISSUE TITLE
$visitor.referrer is null on front-end, but filled properly on back-end

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#11473]
When the `$visitor.referrer` property is accessed in the page editor on the back-end, it contains a valid URL.  When the exact same property is accessed from the same page on the front-end, it shows as null.

## Expected Behavior

The `$visitor` properties should all work on both the front-end and back-end.

## Current Behavior

`$visitor.referrer` is null when it's accessed from a page being displayed on the front-end.

## Steps to Reproduce (for bugs)

1. Create a new Page Asset.
2. Add a simple widget to the page, with the following Velocity code in it to just dump the visitor object: `$visitor`.
3. View the page in the back-end page editor.
    * Result: The `referrer` property shows a valid URL.
4. View the page from the front-end.
    * Result: The `referrer` property shows as `null`.

## Context

This is an important property.  Jason S is trying to use it for the dotCMS production web site.

## Your Environment

* dotCMS version used: 4.0.1 (demo) and 4.1.0 (nightly 05/02/17)
* Browser Name and version: Chrome
* Operating System and version: Win7
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8.0_111
* Database and version: Postgres and H2

**Comment by jcastro-dotcms** [comment]
Note to QA: This issue is not reproducible with the latest code anymore as per the comment in ticket  #11494

**Comment by bryanboza** [comment]
Tested on release-4.1 and here we need resolve the velocity code from edit mode when you are using a simple content, like when you are using widgets...
https://screencast.com/t/xtMPYyNK7X

**Comment by bryanboza** [comment]
This is expected, the just the widget should resolve velocity code in edit mode

**Comment by wezell** [comment]
shoud use `$visitor.referer`
