### ISSUE TITLE
Support Hazelcast Embedded and Client Transports/Caches

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11487]
- The HazelCastCacheTransport needs to be renamed to HazelCastCacheTransportEmbedded. Add a Protected String to it for the xmlFilePath and create a second class that extends this class named HazelCastCacheTransportClient and just override the xmlFilePath. When loading a client for the transport layer we should never try to autowire only do this in the Embedded. So we need to also override the init() in the HazelCastCacheTransportClient but other then the String and init() all code should be the same

- Need to make the HazelCastCacheProvidr follow the same pattern as the HazelCastCacheTransportClient above with the protected String and extending the Embedded Provider

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464

**Comment by shaydotcms** [comment]
Passed QA.
Both Hazelcast Embedded and Client Transports/Caches are able to be configured on AutoWire and Manual cluster.
Tested on dotcms 4.1.0 distribution generated from master on commit 6b1238a
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
