### ISSUE TITLE
Performance Optimizations for Distributed Caches such as Hazelcast

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11488]
- In the CacheProvider interface we need to provide a new boolean called isDistributed which both Hazel and Redis provider would return true. If true then we should NOT use the CacheTransport meaning we would removeLocalOnly because in distributed cache we expect the cache to handle cacheInvalidation (Look at call to Transport in ChainableCacheAdministratorImpl.remove(), implement cacheProviderAPI.isAllDistributed(region))

- On cache-invalidation-message receive, add a "ignoreDistributed" flag over CacheLocator.getCacheAdministrator().removeLocalOnly(key, group) at ChainableCacheAdministratorImpl.invalidateCacheMesageFromCluster. This must apply with the same pattern to flushAll and flushGroup cases as well.

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464
