### ISSUE TITLE
Style primeng DataTable component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11507]
## PrimeNg Component:
https://www.primefaces.org/primeng/#/datatable

## Design:
![data table](https://cloud.githubusercontent.com/assets/751424/25784409/81239436-3329-11e7-938a-21b29628cdda.png)

## Acceptance Criteria
1. Match the design
2. Works in all the supported browsers (don't forget IE11)
3. Include [pagination](https://www.primefaces.org/primeng/#/datatable/paginator) styling
4. Include [sorting](https://www.primefaces.org/primeng/#/datatable/sort) icons
5. Include [selection](https://www.primefaces.org/primeng/#/datatable/selection) styling 
5. Doesn't break others styled components (see Pattern library)
6. Add an example to the pattern library

**Comment by woontsoudev** [comment]
Completed...
Core-web: https://github.com/dotCMS/core-web/pull/349/commits/c5e8230cc771553405ba2fa7f652294834d4b6bd
