### ISSUE TITLE
Style/create floating action button

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11508]
We already have an icon button, we need to following the [same logic](https://github.com/dotCMS/core-web/blob/master/src/styles/primeng-theme/components/_button.scss#L46:L69) create a floating action button.

## Design:
<img width="133" alt="screen shot 2017-05-07 at 1 42 09 pm" src="https://cloud.githubusercontent.com/assets/751424/25784520/a5c0b4b6-332b-11e7-878c-b82081732bb3.png">

## Acceptance Criteria:
1. Mesure: 56 x 56 px.
2. Should behave like a normal button (check Pattern Library), that means that hover, active and other state works the same but with this color (disabled remains gray)
3. Works in all the supported browsers (don't forget IE11)
4. Add it to the Pattern Library

**Comment by woontsoudev** [comment]
Completed...
coreWeb: https://github.com/dotCMS/core-web/pull/346/commits/cc2a1791bad71fa428689964b6e2f8a57ce59c43
