### ISSUE TITLE
Load content types in listing page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11510]
This is only to print out the data, not actions at all in this one.

This one goes after: https://github.com/dotCMS/core/issues/11507

## Design:
![data table](https://cloud.githubusercontent.com/assets/751424/25784409/81239436-3329-11e7-938a-21b29628cdda.png)

## Acceptance criteria:
1. Match the design (it should already match from https://github.com/dotCMS/core/issues/11507)
2. Works in all the supported browsers (don't forget IE11)
3. Pagination
4. Unit test in components and services

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11615
