### ISSUE TITLE
Loading users takes several seconds

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#11519]
For a customer with hundreds of contents, loading users assigned to a selected role takes several seconds to perform and it locks other tabs from the Roles/Tabs portlet

## Expected Behavior
Loading users assigned doesn't take several seconds

## Current Behavior

https://drive.google.com/file/d/0B4eH8CZ7LTcqUWxYSGdfek1oWTQ/view

## Possible Solution

Currently is made a sql query for each user assigned to the selected roles.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/RoleAPIImpl.java#L288

We can do just one sql request to get all users

**Comment by joseorsini** [comment]
Please see 
https://github.com/dotCMS/core/issues/11518

**Comment by joseorsini** [comment]
This also affects once you open the Users tool and click on any current User. If the list of Roles to assign is a big one, then it takes a considerable amount of time to load them all.
