### ISSUE TITLE
Custom Fields Showing the edit pencil

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11524]
It should be hidden from the backend. This is a result of the dotParse directive

![screen shot 2017-05-08 at 3 39 28 pm](https://cloud.githubusercontent.com/assets/934364/25821814/8b205e3e-3404-11e7-8d9b-02a34b81ddff.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11526

**Comment by bryanboza** [comment]
Fixed, now we don't have the pen icon... Tested on release-4.1 // FF
