### ISSUE TITLE
edit mode - container controls not working if multiple containers on a page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11529]
It gives you a js error on all but the last one when trying to edit the container from edit mode:

https://dotcms.slack.com/archives/C028Z3R2D/p1494280334129094

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11530

**Comment by jgambarios** [comment]
Related to the changes made here https://github.com/dotCMS/core/issues/11296

**Comment by jgambarios** [comment]
**Note to QA:** @bryanboza as part of this ticket please re-test https://github.com/dotCMS/core/issues/11296

**Comment by bryanboza** [comment]
Fixed, tested on release-4.1 // FF // Now you can add content to any container without problems
