### ISSUE TITLE
JS error trying to add content to pages with templates that have multiple containers 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11531]
We are having problems when you create a new template with more that one container, this because when you try to add content to the page, the system just allow add content to the last one.... 

## Expected Behavior
We should be able to add content to any container in a template 

## Current Behavior
You can only add content to the last one 

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new template and add 3 containers 
<img width="1411" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25827595/36f3b96e-3409-11e7-9368-527bbdd8d962.png">
3. Create a new page and use the created container  
4. Go to edit mode and try to add content to the first container of the page 
<img width="1440" alt="bug2" src="https://cloud.githubusercontent.com/assets/2641437/25827669/a3ad2e8c-3409-11e7-932d-66cd287ca8fe.png">
5. Repeat the step #4 with the second container

## Your Environment
Tested with the last code of the release-4.1 // MySQL // FF

**Comment by wezell** [comment]
dupe #11529
