### ISSUE TITLE
Unable to push from http to https session 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11547]
We are having problems when you try to push publish (PP) or run the Integrity checker (IC) when the sender is using a http and the receiver https. 

## Expected Behavior
We should be able to support push publish between this different instances 

## Current Behavior
After you configure the PP environment, when you try to run the IC and/or PP we have errors on the sender:

Log after trying to use the IC:
https://gist.github.com/jcastro-dotcms/95b5f8ebbfeb23b44090fbaaacf0b4f7
Log after trying to use the PP:
https://gist.github.com/jcastro-dotcms/4b773cc7e453d354ec28f062c3edb874

## Steps to Reproduce (for bugs)
1. With a https session on sender configure your PP environment
2. Configure your receiver in a single (http) server
3. Try to run the integrity checker
4. Check your logs 
5. Try to push some file 

## Your Environment
* dotCMS version used: Tested with both servers with the last code of release-4.1
* Browser Name and version: Chrome 
* Operating System and version: MacOSX
* Application Server and version: Tomcat
* Java Brand and version: 
```
java version “1.8.0_65”
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
* Database and version: Postgres
* Application module (if apply): Push Publish // Integrity Checker

**Comment by erickgonzalez** [comment]
Clients ticket https://my.dotcms.com/tickets/detail.dot?id=9124a6ee-0b4e-4deb-8b1d-48aee3ab785f

**Comment by wezell** [comment]
I cannot reproduce this with real certificates, e.g. pushing to demo.dotcms.com
