### ISSUE TITLE
Roles/Tabs: Non-Top level roles are sorted randomly

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11545]
Roles and Tabs tool allows searching user-assignable users according to the logged-in user's permissions, however, the behavior of Roles listed on the Roles tree doesn't seem to be consistent.

## Expected Behavior
 Top Level roles are ordered by Role Name (asc), so we would expect children roles should have the same order/sort.

## Current Behavior
There is no consistent sort for roles once we expand one of the Top Level Roles.

## Possible Solution
Set a consistent way to sort children Roles. Currently, We pull these roles using the RoleResource class and, once any Top Level Role is selected, this code

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/RoleFactoryImpl.java#L61 

is called. Then, this code 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/RoleFactoryImpl.java#L695 

populates the current role's list of children roles. No sort is detailed here on the query that pulls the children roles for the selected one. 

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Login to demo site.
2. Go to Roles/Tabs tool.
3. Click on "System" role. Roles are not sorted by their name.

## Context
Reported by customer: 	https://my.dotcms.com/tickets/detail.dot?id=f2f2d1e2-e969-4319-b0e1-1d108925128b

## Your Environment

* all versions of dotCMS.
* Any browser/OS.
* Any App/DB Server.
* Java 8u121.

**Comment by gabbydotCMS** [comment]
Also reported by https://my.dotcms.com/tickets/detail.dot?id=1b28a08b-966a-40bd-870a-2dffcd05154f

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11798

**Comment by bryanboza** [comment]
Fixed, now we have the list ordered asc by name... Tested on master // Chrome

**Comment by bryanboza** [comment]
Still having problems when you add new roles in lowercase, the system put in the last position those ones, and is not ordering ... Just order the new roles if start with uppercase.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11909

**Comment by bryanboza** [comment]
Fixed, tested on postgres // master
