### ISSUE TITLE
Problems when you call from live mode a VTL file that no have live version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11542]
Related to #11437 

After the last velocity changes we are having errors parsing VTL files when the asset does not have a live version. 
The error can be reproduce using normal content and widgets, but we have some differences on how they fail.

## Expected Behavior
If you **don't have a live version** of the VTL and the **#dotParse** is use on it we should handle the error and don't show nothing 

## With normal contents:
The system broke the entire page, you are unable to see others contents in the page

**Error**:  $render.eval($column.draw())                     
**Log**: https://gist.github.com/bryanboza/568f5718fc3c0171bfe51d92c9160b2f

<img width="1307" alt="bug1" src="https://cloud.githubusercontent.com/assets/2641437/25874163/9e642226-34ce-11e7-9e2d-4044a8ecdee3.png">

## With widgets
The system shows a **$code** message, but you are able to see the other contents in the page

**Error**: $code

**Log**:  https://gist.github.com/bryanboza/25e7c70418db2ab8473d0043044edf16 

<img width="1462" alt="bug2" src="https://cloud.githubusercontent.com/assets/2641437/25874413/b94693a2-34cf-11e7-8fa9-ab16773bf866.png">

## Steps to Reproduce (for bugs)
1. Upload a VTL file that ONLY have a working version
2. Create a new page 
3. Add a content to the page with this code ```#dotParse('/folder/file1.vtl')```
4. Finally just try to see that page from front end or live mode.

5. Test the steps 1-4 but instead add a content use a widget

## Your Environment
Tested on release-4.1 // Postgres // FF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11573

**Comment by bryanboza** [comment]
Still having problems in that case.... 

Tested with this 3 VTL files: 
File1 = Jut Working version
File2 = Working and Live Version 
File3 = Just live version

**Case #1:**  
- In a new page add a generic content, in the wysiwyg field, change this to code mode and paste that piece of code:   **#dotParse("/folder/file1.vtl")**
- Add another content with the file2.vtl 
- Add another content witht the file3.vtl 
- If you go to preview mode everything looks ok
- Go to live mode
**We are not showing nothing here....**
![case1](https://cloud.githubusercontent.com/assets/2641437/26167881/5e0bb46e-3af5-11e7-8288-8310306b6ce6.gif)
**Case #2:**  
- In a new page add a generic content, in the wysiwyg field, change this to code mode and paste that piece of code:   **#dotParse("/folder/file3.vtl")**
- Add another content with the file2.vtl 
- Add another content witht the file1.vtl 
- If you go to preview mode everything looks ok
- Go to live mode
**The system shows the content #3 and this is ok, but also shows the content #2 twice** 
![case2](https://cloud.githubusercontent.com/assets/2641437/26167886/65abad14-3af5-11e7-9d7b-c80d978b631f.gif)
**Case #3:**  
- In a new page add a simple widget, and paste that piece of code:  **#dotParse("/folder/file1.vtl")**  
- Add another widget with the file2.vtl 
- Add another widget with the file3.vtl 
- If you go to preview mode everything looks ok
- Go to live mode
**The system shows a $code message with the content #1.**
![case3](https://cloud.githubusercontent.com/assets/2641437/26167889/6e520a6c-3af5-11e7-8bcb-bcac90b8098a.gif)

**Comment by oswaldogallango** [comment]
This resolve the $code and $render.eval($column.draw()) error message when the reource doesnt exist in live mode P.R https://github.com/dotCMS/core/pull/11666

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11677

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11677

**Comment by oswaldogallango** [comment]
there is an issue when we create a page and the lock button is not displayed properly reported on this ticket https://github.com/dotCMS/core/issues/11679

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11706

**Comment by bryanboza** [comment]
Still having problems with the velocity exceptions when you have a bad velocity code...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11741

**Comment by bryanboza** [comment]
Fixed, tested with the last relese-4.1 code and now works as expected...

**Comment by DeanGonzalez** [comment]
Retested: passed
