### ISSUE TITLE
Expiring Content and PP

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11559]
We have some cases where auth-expiring content does not play well with our Push Publishing framework and users on the remote system.  There are multiple cases here. Sometimes it causes the bundle to fail and other times the content will just not expire.  Here are a few scenarios.

- [ ] Content set set to expire (or set to expire in 5 m) and last mod_user of the content does not exist on remote file system.  

- [ ] Content is expired (or set to expire in 5 m) and last mod_user exists on remote file system but does not have any Roles/rights on remote system

finally

- [ ] In the above scenarios, each different base type of content treats the expiring date differently.  HTMLPages, Content, FileAssets, etc.. If you try to push a piece of content, say a page, that is expired (or set to expire), without the mod_user, it work but content does not.

Here is what we need.  We need a boolean config property called `HEADLESS_CONTENT_DELIVERY` (default false) that if set to true, will automatically set a non-existing mod_user to system user and use the system user for all save, publish/unpublish operations.

**Comment by wezell** [comment]
See @joseorsini's issue #11575 above.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/enterprise-2.x/pull/467 and https://github.com/dotCMS/core/pull/11712

**Comment by oswaldogallango** [comment]
This new property HEADLESS_USER_CONTENT_DELIVERYwas included in the dotmarketing-config.properties. By default is set to false. If the property is set to true, the PublishDateUpdater class will use the System user to publish or expire content instead of the mod user

**Comment by john-thomas-dotcms** [comment]
Doc link: https://auth.dotcms.com/docs/latest/push-publishing-permissions#headless

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres and works as requested...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/482

I modified the logic in order to use the **HEADLESS_USER_CONTENT_DELIVERY** property inside the ContentHandler, the problem with the old place where the property was is that could be used outside the Push Publish context allowing the app to avoid some permissions restrictions we have.

**Comment by bryanboza** [comment]
Fixed, tested on master // MSSQL...
