### ISSUE TITLE
Multi-tenanted external ElasticSearch

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#11552]
In order to efficiently use resources with an external ElasticSearch cluster, we need the ability for multiple dotCMS clusters to share an ElasticSearch cluster with private per-cluster namespacing. This should be hidden to the dotCMS Administrator, ie they should not have visibility that the Elastic cluster is shared and access should be isolated so that a given dotCMS cluster can only access and manage its own indexes.

A suggested pattern for enabling this would be to intercept all index API calls and inject a prefix into the index name, and stripping that prefix out when displaying in the dotCMS application (transparent to the app admins and developers). This prefix could use the existed unique CLUSTERID, which can also be set as a configuration parameter.

Example architecture:
![image](https://cloud.githubusercontent.com/assets/3977301/25961856/94afffd0-3630-11e7-926b-fc4ec11f2e11.png)

**Comment by chrismccracken** [comment]
Also re: https://github.com/dotCMS/enterprise-2.x/pull/314

**Comment by chrismccracken** [comment]
Also need to take into consideration any non-obvious tools that access ElasticSearch:
- Site Search
- Viewtools (Site Search and ES tool)

Anything that grants access to an ES index should control visibility to only the ES namespace for it's own cluster

**Comment by wezell** [comment]
We should use the shorty value of the cluster id to prefix the index names.
This needs to be fully hidden from dotCMS users - meaning, they should not be able to call elasticsearch with those prefixes being applied.
We should pay attention to importing and exporting index snapshots as well - it is ok if the clusterId is prefixed when downloading or creating a snapshot, as long as we insure that it is always prefixed on any attempts to import a snapshot.

**Comment by freddyucv** [comment]
For QA: Bug in Site Search.
Steps: 
1. Have two dotCMS running in different port with different DB
2. Go to "Dev Tools/Site Search" in Node 1, and . create a new "Site Search Index"
3._ Go to  "Dev Tools/Site Search" in Node 1 and you can see the Serach Index created in the first node.

![bug_1](https://user-images.githubusercontent.com/10408015/70073336-4abb9b80-15be-11ea-9bc7-7ee27a686898.gif)

**Comment by freddyucv** [comment]
For QA: Bug in Index tab in Maintanence
Steps:
1. Have two dotCMS running in different port with different DB
2. Go to "Maintenence" and Index tab in Node 1, yo here can see the Node 2's Index.
3. Go to "Maintenence" and Index tab in Node 2, yo here can see the Node 3's Index.

![bug_2](https://user-images.githubusercontent.com/10408015/70074004-89058a80-15bf-11ea-93bb-73a4c9cc5bb6.gif)

**Comment by wezell** [comment]
Let's read the links in this convo:
https://stackoverflow.com/questions/41868056/multi-tenancy-in-elastic-search

**Comment by wezell** [comment]
All indexes will now be prefixed with the value of the dotCMS Cluster Id.  This value will be autogenerated, though it can be set in the dotmarketing-config.properties 
 as `DOTCMS_CLUSTER_ID=xxxxx`
It can also be specified at runtime as an environmental property `export DOTCMS_CLUSTER_ID=xxxxx` . or a system.property, e.g. `-DDOTCMS_CLUSTER_ID=xxxxx`

**Comment by nollymar** [comment]
PRs to merge into `issue-15942`
Core: https://github.com/dotCMS/core/pull/17746
EE: https://github.com/dotCMS/enterprise-2.x/pull/696

**Comment by dsilvam** [comment]
Tests are covered in this issue: https://github.com/dotcms/core/issues/18046

**Comment by dsilvam** [comment]
Passed QA. Tested here: https://github.com/dotCMS/core/issues/18046
