### ISSUE TITLE
Can't Uncheck the "Never" Checkbox on the Expire field on starter News Content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11569]
Reproduced on latest 4.1 build

Easy to reproduce.  Add a new piece of News Content - bug is that you can't uncheck the "Never" option under the Expire field.

![expirebug](https://cloud.githubusercontent.com/assets/1569167/26014157/aa7d2ec6-3718-11e7-8210-e2db78b67028.jpg)

screencast: https://screencast.com/t/n0N9x4Lz5

**Comment by danlaguna** [comment]
Tested on both master and release4.1 branches and this does not happen anymore.

Steps to reproduce:

1. Login to dotCMS/admin
2. Click on the Content menu item (left pane) and hit search
3. Click on the Add New Content button and then click Add New Content option
4. Select the News option
5. Scroll down until you see the Never checkbox.
6. Click the checkbox to verify behavior

Environment:
OS: macOS Sierra version: 10.12.5 (16F73) 
Browser: Chrome Version 58.0.3029.110 (64-bit)
DB: Postgres


<img width="1440" alt="never - checked" src="https://cloud.githubusercontent.com/assets/26439824/26253889/0d14cfd6-3c72-11e7-8c17-f4e423e09d83.png">
<img width="1440" alt="never - unchecked" src="https://cloud.githubusercontent.com/assets/26439824/26253906/15f7402a-3c72-11e7-9b2e-3be205f19ca0.png">

**Comment by DeanGonzalez** [comment]
After an update, I can no longer produce this either... seems to be working... closing the issue

**Comment by DeanGonzalez** [comment]
Bug must have been produced between commits... closing
