### ISSUE TITLE
What's Changed is Broken after a save from inline  editing tool

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11566]
Found on latest 4.1 build

Easy to reproduce

1) Bring up new licensed instance, and go to the "about us" - locations index page (which uses the inline editing tool).
2) Add a new piece of Generic content and save/publish.  Then use the inline editing tool to edit the generic content and make a change.  Do not make changes by editing the content, save changes using the inline editing tool only.
3) Then click on the Preview tab, and on What's changed.  Bugs are that the preview page does not display the changes, nor do the changes get highlighted by what's changed feature.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11641

After this [commit](https://github.com/dotCMS/core/commit/fccff5a543ab078495fe04d8e5fc76b3e6b85d3e) we no longer read the "PREVIEW_MODE" value in the context, so we need to set WebKeys.PREVIEW_MODE_SESSION in the session and request. Also we need to pass the user and userID as part of the session/request.

**Comment by oarrietadotcms** [comment]
PR release 4.1.0: https://github.com/dotCMS/core/pull/11657

**Comment by shaydotcms** [comment]
Passed QA.
System is successfully displaying the changes, and the changes get highlighted by what's changed feature.
![image](https://cloud.githubusercontent.com/assets/8741846/26451805/c7f0dc4e-411a-11e7-900e-e9732dfac85e.png)

Tested on dotcms 4.1.0 distribution generated from Release-4.1 on commit b2682bce459687e928267ff941ae2de83504e3a7
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
