### ISSUE TITLE
Unable to disable the "never" checkbox when you use date time fields to expire content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11563]
When you use date time fields, we are unable to disable the never option, this because when you click the checkbox this don't have action 

## Expected Behavior
We should be able to enable and disable this option 

## Current Behavior
We are unable to un-check the never option 
SC: https://screencast.com/t/LzwJCznvi5N

## Steps to Reproduce (for bugs)
1. Create a new content type 
2. Add two indexed date time fields 
3. Go to the content type properties and select those fields in the publish and expire fields 
4. Save it 
5. Try to add a new content to this content type and make sure you can disable the "never" option 

## Your Environment
Tester on master-4.1 // Postgres // Chrome and FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11595

**Comment by bryanboza** [comment]
Fixed, tested in the latest release-4.1 // oracle // Chrome

**Comment by bryanboza** [comment]
Still having problems here, if you set this field mandatory and you check the never checkbox, the system shows a required error... 
Here the SC: 
![case1](https://cloud.githubusercontent.com/assets/2641437/26178284/974c3cc4-3b1a-11e7-82d3-791596225d23.gif)

**Comment by bryanboza** [comment]
Fixed...
