### ISSUE TITLE
Make jenkins push master builds to dotcms.com

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11577]
We did the Master build and testing but we missed the last step. We need a place where the last good build can be downloaded.  The shortest path to this is to hook up the nightly to any release builds to deliver those to dotcms.com

**Comment by wezell** [comment]
@agomez-dotcms this is what you were working on?

**Comment by agomez-dotcms** [comment]
Hi @wezell,

Yes, it looks so. I have been working these days on providing nightly builds for release branches too. At this moment, the process is succeeding when manually trigerred from Jenkins but it is failing with an strange error/exception when the Jobs are automatically trigerred by Jenkins on scheduled.

I have planned to review this issue with automated nightly builds as my next priority. I am afraid that my highest priority at this moment is to review failing tests that appeared after enabling Functional Tests back on Jenkins.

Hope that helps!

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
Hi Guys,

After a first "micro" iteration (done last week) over parent epic (Enhancements to Testing Infrastructure), it seems this task is now solved. More details -on what was accomplished- last week may be found at parent epic's comment (https://github.com/dotCMS/core/issues/11196#issuecomment-302859170).

Thanks,
Anibal
