### ISSUE TITLE
Push Publishing: Publish/Expire Feature should always run as System User

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11575]
This feature, as stated in our [documentation](https://dotcms.com/docs/latest/setting-publish-and-expire-dates-for-content), allows automatic Publish and Expire dates for contents, according to two Date/Time fields with different values. 

Under specific scenarios, this feature may not work as expected. There's a chance that a Pushed content between environments has a last mod user that either:

- does not exist on the target environment, although there is a "fallback" feature that sets the System User to do this automatically.
- does not have enough permissions to publish/unpublish this content automatically given a specific date and time. 

In any case, we should not ask for the content's last mod user: in case it does not exist, an exception is thrown and existing code in PublishDateUpdater class falls back to looking up the System User. 

In case the user exists, but for security reasons all roles and permissions were removed (this is a common practice on Push Publishing environments, where access to Prod is removed to users or users don't even exist there), the process fails and affects everything in the PublisherQueueJob, affecting all contents to be pushed in the Queue and retrieving bundles' status from other environments where these ones were originally pushed.

## Possible Solution
Set System user (which is a CMS Admin user by default) to publish/expire contents, regardless of the content's last mod user.

## Known Workarounds
Push users and sync roles between environments. 

## Context
Reported on tickets: 
- https://my.dotcms.com/tickets/detail.dot?id=ffdf2e6e-a818-4eec-8f0b-22afbf8e35ed
- https://my.dotcms.com/tickets/detail.dot?id=d7a95d85-422b-429b-af9e-4089d385fa94

## Your Environment

* dotCMS v4.0.1
* Any OS/Browser.
* Any App/DB server. 
* Java 8u121.

**Comment by wezell** [comment]
Dupe #11559 even though this is a better report.
