### ISSUE TITLE
URL Title field is not auto filled

### ISSUE THREAD

**Issue by gsollazzo** [dotCMS/core#11576]
The URL Title filed does not work in the default state.

## Expected Behavior
The URL Title should call the .vtl and fill the field.

## Current Behavior
Nothing happens.

## Steps to Reproduce (for bugs)
1. Install DotCMS 4.0.1
2. Create a new Blog post (or any content with a URL Title field)
3. Write something in the Title field
4.

## Your Environment
* dotCMS version used: 4.0.1
* Browser Name and version: Chrome on OSX, Firefox on OSX
* Operating System and version: FreeBSD 11.0
* Application Server and version: Default Tomcat 8.0.18
* Java Brand and version: OpenJDK Runtime Environment (build 1.8.0_121-b13)
* Database and version: PostgreSQL 9.6
* Application module (if apply):

<img width="1059" alt="screen shot 2017-05-15 at 13 58 03" src="https://cloud.githubusercontent.com/assets/12738685/26056657/8f471198-3976-11e7-8e6d-e1cd070dea72.png">

**Comment by wezell** [comment]
@gsollazzo This works on the current demo - see https://demo.dotcms.com/dotAdmin .  If you can reproduce your error there, we can reopen this.

![screen shot 2017-05-15 at 9 13 35 am](https://cloud.githubusercontent.com/assets/934364/26059181/ccd32e5c-394e-11e7-9a27-e876e4186e96.png)
