### ISSUE TITLE
Large amount of White Space added on Events

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11571]
Found on latest 4.1 Build

Large amount of white space between the Description title on the WYSIWYG field and the field itself.  Something wrong with backend CSS here I think. (see screenshot below)  Re-arranging field order does not solve the issue.

![crazyspace](https://cloud.githubusercontent.com/assets/1569167/26014666/d41c0232-371a-11e7-8558-05e26e511bc4.jpg)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11643

**Comment by bryanboza** [comment]
Fixed, now we don't have the white space, but when you try to add a new event the form appears with the scroll down, you need scroll up to see the first field
