### ISSUE TITLE
Contents: Search Box does not work on FileBrowserDialog box

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11574]
Image/File fields allow you to attach existing images to these fields, or in case they don't exist, it allows the user to upload them under a selected site and/or folder. 

## Expected Behavior
If a logged in user would like to search for an image or file under a selected folder, the FileBrowserDialog box should respect the search criteria and pull any occurrence to the user.

## Current Behavior
Search box does not work on this view, regardless of the selected "View" mode (List, Details, Thumbnails).

## Possible Solution
Check if any JS event was removed from it and restore it, so search of files/images can work as expected.

## Known Workarounds
None. User has to scroll until he/she finds the file/image they'd like to store under the field.

## Steps to Reproduce (for bugs)

1. Login to demo site.
2. Go to Content search portlet.
3. Add a new Event.
4. For "Image" field, click on "Browse" button.
5. Go to demo.dotcms.com/images/icons folder.
6. Once all images are listed, type on the search box "loader". Nothing is filtered according to user input.

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=fb9d0152-5670-4fe8-8b88-279e142efdad

## Your Environment

* dotCMS v4.0.1
* Any OS/Browser.
* Tomcat 8.0.18.
* Java 8u121.
* Any DB server.

**Comment by oswaldogallango** [comment]
related to #12353
