### ISSUE TITLE
3.7.2

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11597]
Placeholder for issues

1. H22Cache
2. Rules Cache Ping-pong
3. ContainerServices 
4. doc_values
5. ???

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/issues/10967 
https://github.com/dotCMS/core/issues/10869
https://github.com/dotCMS/core/issues/10828
https://github.com/dotCMS/core/issues/10825

**Comment by wezell** [comment]
Good - #10869 is the ContainerServices

**Comment by brentgriffin** [comment]
https://github.com/dotCMS/core/issues/11835

**Comment by brentgriffin** [comment]
https://github.com/dotCMS/core/issues/11811 - CategoryAPI unescaped SQL
https://github.com/dotCMS/core/issues/11813 - SQL injection vector

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/issues/10515 - Image/File fields printed on containers are not working for non-default language version of pages

**Comment by brentgriffin** [comment]
https://github.com/dotCMS/core/issues/10974 - Prevent Directory Traversal in bundle uploader

**Comment by brentgriffin** [comment]
# To be included in 3.7.2
https://github.com/dotCMS/core/issues/11315 - RuleCache.getRulesByParentFireOn uses cache anti-pattern
https://github.com/dotCMS/core/issues/10869 - Containers: Boolean-type Radio fields are not parsed properly on container code
https://github.com/dotCMS/core/issues/11330 - Move ES to use doc_values by default
https://github.com/dotCMS/core/issues/10967 - Licensing: Trial licenses cannot be requested
https://github.com/dotCMS/core/issues/10828 - Push Publishing: Cannot push empty template if DB is Oracle
https://github.com/dotCMS/core/issues/10825 - Push Publishing: Cannot configure "receive from" endpoint if DB is Oracle
https://github.com/dotCMS/core/issues/11835 - When Sending Bundles we read the whole file into memory
https://github.com/dotCMS/core/issues/11811 - CategoryAPI unescaped SQL
https://github.com/dotCMS/core/issues/11813 - SQL injection vector
https://github.com/dotCMS/core/issues/10974 - Prevent Directory Traversal in bundle uploader
https://github.com/dotCMS/core/issues/11592 - h22 (change concurrency setting)



# Not included (perhaps in a 3.7.3):
https://github.com/dotCMS/core/issues/10515 - Viewtools: FileTool does not respect DEFAULT_FILE_TO_DEFAULT_LANGUAGE property

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/commit/64226f899eb3236731de552bdacbb4a820b66a86 related to H22 (Change concurrency setting)

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/commit/c385f2a8e68ebbc987dbd9a40a189fb00269f5df related to: Prevent Directory Traversal in bundle uploader

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/issues/12627 this one should be included as well on this release.

**Comment by joseorsini** [comment]
#11622 and #8552 were added to the build as well.

**Comment by joseorsini** [comment]
Adding this one as well, as per a use-case reported by customer 

https://github.com/dotCMS/core/issues/10515

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/commit/80ee268510783cef77379f5a6edf521360f62e41 

Added build name and improvements for avoiding zero-byte file issues
