### ISSUE TITLE
Test upgrades with customer's data

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11594]
At least one for each db

Please include the log when completed and create gibhub issues if needed for the errors. 

Upgrade and then reindex through the UI

**Comment by danlaguna** [comment]
Tested with the following dumps:
https://drive.google.com/drive/u/1/folders/0B48uh-u7fegRemVodzZlUDRMUzA

Postgres log: https://gist.github.com/danlaguna/733fb7924cbc3a03c22a8b3f111d7ffb
MySQL log: https://gist.github.com/danlaguna/57e9fde1389e35df37c21ddae9da3486
Oracle: TBD
MSSQL: TBD

**Comment by bryanboza** [comment]
Tested upgrade in oracle with real data, and the upgrade works fine...

**Comment by danlaguna** [comment]
MSSQL: data is so big there are memory performance issues. Check logs for additional details.

**Comment by dsilvam** [comment]
MSSQL upgrade from 3.3 was successfully tested by @shaydotcms
