### ISSUE TITLE
[Reindex] Errors when reindex BD after upgrade

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11596]
We have several errors related to bad data and new Content Type logic that we need to fix.

[dotcms.log](https://gist.github.com/oarrietadotcms/4348dfa06adb93b6695780f8465c0f49)

**Comment by oarrietadotcms** [comment]
[dotcms.log](https://gist.github.com/oarrietadotcms/4f11e0379788ae830ba89c633e5b59b3) during reindex after commits.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11602

**Comment by oarrietadotcms** [comment]
PR release 4.1.0: https://github.com/dotCMS/core/pull/11603

**Comment by shaydotcms** [comment]
Passed QA.
Tested on upgraded from dotcms 3.6 to 4.1.0 against client's DB in postgres. No isssues in the logs with reindex
Tests were also performed with dotcms DB and user was able to reindex after upgrade
