### ISSUE TITLE
DB: Workflow Actions should have a many-to-many relationship with workflow steps 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11609]
Currently, workflow actions can only belong to a single workflow step in the workflow scheme. We need to allow a workflow action to belong to multiple workflow steps (in the same scheme).  This will require a startup task and a db schema change.

**Comment by jdotcms** [comment]
The following messages have been added to the Language.properties, and could be good to check:
```
+Workflow-does-not-exists-action=The action does not exists
+Workflow-does-not-exists-step=The steps does not exists
+Workflow-could-not-save-action=Could not save the action
+Workflow-action-already-exists=The action could not be saved, it already exists
+Workflow-permission-issue-save-action=The current user does not have the required permissions to save this action
```

**Comment by bryanboza** [comment]
After testing the integration of this changes, we have some issues: 

- [ ] Unable to delete workflow steps once you has been added some action 
Log: https://gist.github.com/bryanboza/db137e28b8628281aaca3536e78e838a
_We need be able to delete steps without problems, also if the step contais actions we should delete it_ 

- [ ] We need a better handle of the error at log level when you try to add some action twice in the same step 
Log: https://gist.github.com/bryanboza/e657192dc493e00d27a9fb1a442e1450
_We need hide all the stacktrace and show just one line error on log._ 

- [ ] Problems to update a workflow action 
SC: https://screencast.com/t/LUfAMbe5qr
_After you edit some action, the system is just updating in the main list, not in every step that this is associated_ 

- [ ] We are duplicating the notify assignee sub-action every time you update the action 
SC: https://screencast.com/t/vVUvvoAG
_Every time you made some change in the workflow action, we are adding a new "notify assignee" sub-action_

**Comment by jdotcms** [comment]
All DONE

**Comment by bryanboza** [comment]
Unable to start master on MSSQL 
Here the complete log: 
https://gist.github.com/bryanboza/31da27210baf55a23c13ee2814611b58

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13216

**Comment by jdotcms** [comment]
Fixes for the MSSQL are done!

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13239

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13259

**Comment by bryanboza** [comment]
The main changes of this card are only at UI level...

**Comment by bryanboza** [comment]
Fixed, after the last changes, now we are able to handle multiple workflows without problems, some pending changes here, but was reported on separate cards
