### ISSUE TITLE
Category Relationships View

### ISSUE THREAD

**Issue by asifanoor** [dotCMS/core#11601]
Expected Behavior

We would like to view all category relationships in the admin to check where these categories are being used.

Current Behavior
Before deleting a category, users have no way to check where this category is being used. The only message displays is: this category has dependencies.

Possible Solution
Admins will be able to view all relationships a category has before deleting / replacing / updating.

How would you use it?
For a multi tenant instance where various teams will be working on different projects, it will be helpful for CMS admins to view all category relationships for house keeping e.g. off-boarding a host etc.

**Comment by gabbydotCMS** [comment]
Related support ticket: https://my.dotcms.com/tickets/detail.dot?id=a1f0b639-ecf8-4bb7-af8a-04fc46361e25
