### ISSUE TITLE
DotCMS Installation / Upgrade Process

### ISSUE THREAD

**Issue by asifanoor** [dotCMS/core#11610]
Expected Behavior
Confirm from user if they want to go ahead with installation / upgrade before running the actual installation / upgrade process.

Current Behavior
DotCMS installation / upgrade process automatically starts without confirming from user if they really want to go ahead with installation / upgrade.

Possible Solution
May be displaying some environment information for user to review. Display a dialogue or a button e.g. start upgrade / installation or cancel.

Context
Different teams perform different actions e.g. upgrades will be scheduled & completed by operations team and it will help for auditing purposes.
 
 Your Environment
* dotCMS version used: 4.0
* Browser Name and version: IE 11
* Operating System and version:
* Application Server and version: tomcat 8
* Java Brand and version: jdk 1.8
* Database and version: MSSQL 2012

**Comment by gabbydotCMS** [comment]
Related support ticket: https://my.dotcms.com/tickets/detail.dot?id=9e6c0365-fca2-440b-98a2-81d562d82cf0
