### ISSUE TITLE
Content REST allow for managing multiple binary files

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11613]
The case is documented here https://dotcms.com/docs/latest/save-content-using-rest-api#binaryOrder

You have to provide binaries in the right order and provide them allow.  The issue is when they should be optional and because this is the RESTAPI what if an order changes or more are added. 

It's too brittle and integration pieces are easily broken in the dotCMS UI

**Comment by wezell** [comment]
We should additionally allow the second binary to be changed and leave the first and the third unchanged without having to resend them.

Also have the second binary removed (voided) and the first and the third be unchanged - without having to resend them.

**Comment by jtesser** [comment]
@DeanGonzalez need to update the doc here

You can now provide an OPTIONAL parameter named binary_fields. binary_fields is a comma separated list of velocityVariable names for fields on a Content Type which are of the Type Binary. If you do NOT provide the binary_fields parameter you must provide all the binaries in the proper order as already documented here https://dotcms.com/docs/latest/save-content-using-rest-api#binaryOrder
So @DeanGonzalez to be clear what this addresses is now you can send only the binary fields you want and you can specify your own order in case they get out of order or moved in the Content Type. 

An example is 
curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -F "json={stName:'fileAsset',hostFolder:'demo.dotcms.com:/images',title:'test7',binary_fields:'fileAsset,bin2'fileName:'test9.png'};type=application/json" -F "file=@test.png;type=application/png"  -F "file=@test.png;type=application/png"

**Comment by jtesser** [comment]
@wezell I am going to close this issue.  It doesn't address your comment but this issue should https://github.com/dotCMS/core/issues/11625

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=49808174-52b6-4b48-a028-a28c2f3f0967

**Comment by dsilvam** [comment]
we need a PR with the commit in here

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/13472

**Comment by DeanGonzalez** [comment]
There is a syntax problem with the example.  Working case is actually:

curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -F "json={stName:'fileAsset',hostFolder:'demo.dotcms.com:/images',title:'deanTest',binary_fields:'fileAsset',bin1'fileName:'pool.jpg'};type=application/json" -F "file=@pool.jpg;type=application/jpg" -F "file=@pool.jpg;type=application/jpg"

Was just some single quotes out of place.  Will test this again after I can add another binary field.

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/save-content-using-the-rest-api#multipleBinaryExample

**Comment by wezell** [comment]
Does this need to be in a code block?

**Comment by dsilvam** [comment]
@wezell @DeanGonzalez the sentence does not
