### ISSUE TITLE
Should Vanity URLs as Content be Multilingual?

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11629]
In moving to the idea that ALL THINGS ARE CONTENT, we always need to be mindful of how we deal with new types of content and multilingual installations.  

We are beginning the process of moving Vanity URLs to be content and in doing so, are looking for feedback from our customers and community.  We feel like we need to ask:

1. Would it be helpful if Vanity URLs were multi-lingual? Meaning an "English" vanity url that matched the url would not run on the "Dutch" site (if the session/request language variable is set to dutch).

2. If Vanity URLs are multi-lingual, do we support a configurable fallback mechanism that would fall back to the vanity urls in the default language?

3. Or is that just too confusing and would it be better just to manage a big list of vanity urls (even with multilingual urls) for your web site/property that would run if they matched?

**Comment by cmaessen** [comment]
One thing to take into consideration is that both the Vanity URL and the target URL can be different based on the language. This means that it could be that there's a Vanity URL with the same name for different languages but which goes to a different page/document.

So my take is:
1) Should be an option you can turn on or off
2) If it runs for all languages you want this as a fall back
3) Could capture the above use cases

**Comment by monzonj** [comment]
Hi!
We are a dotcms customer and really looking forward to have Vanity URL as content! Yay!

We would defo have 3 implemented. Much easier to maintain

**Comment by monzonj** [comment]
And they should be pushable! :)

**Comment by wezell** [comment]
So the decision is #2 - add the variable to allow allow fallback, default to fallback=true so they work for all languages otb
