### ISSUE TITLE
Create Vanity Url BaseType

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11627]

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11951

**Comment by bryanboza** [comment]
- [ ] Problems modifying some vanity URL, we need clear the cache after modify the content, this because we are unable to see the changes after refresh...

**Comment by oswaldogallango** [comment]
@bryanboza I included some code modifications to solve the error you mentioned before (cache and uri syntax). Now, if you put a regex uri with bad regex syntax, the error is displayed in the log and the system is not going to get block as before. So you can modify the uri

**Comment by jgambarios** [comment]
PRs: 
https://github.com/dotCMS/core/pull/11951
https://github.com/dotCMS/enterprise-2.x/pull/483

**Comment by bryanboza** [comment]
Fixed, now we have this base type working, now we need add the default structure to the new starter, also some improvements are pending in new cards
