### ISSUE TITLE
When Saving content allow it to function as an update or patch 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11625]
The main focus here is the REST API but might be applicable elsewhere.  When updating Content via REST you have to provide the entire Content and Relationships from previous versions.  

If I want to just update a specific field for example I cannot do this.

At least for the REST case we need to add a parameter to the JSON being passed in that will handle this case.  We can checkout the content and then update with the passed in fields. Obviously the identifier will need to be passed in. Ensure we handle Relationships in addition to the fields.

**Comment by jtesser** [comment]
So it looks to me like this works for content fields now. 

Basically we do this

```
Contentlet existing=APILocator.getContentletAPI().findContentletByIdentifier((String)map.get("identifier"), false,
								contentlet.getLanguageId(), APILocator.getUserAPI().getSystemUser(), false);
						APILocator.getContentletAPI().copyProperties(contentlet, existing.getMap());
						contentlet.setInode("");
```
And then we set what is passed in. 

For Categories and Relationships we do not respect existing. This is what needs to change.

**Comment by wezell** [comment]
We need to test this with all content base types.  Also, I believe our simplest contentletAPI.checkin() might have an issue here

**Comment by wezell** [comment]
Dupe: #12761
