### ISSUE TITLE
Fix compilation of static plugins on Windows due to long string on classpath

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11622]
## Current Behavior
Static plugins cannot be compiled because classpath argument on javac call exceeds max amount of chars on Windows environments.

## Possible Solution
Implement http://vvratha.blogspot.com/2012/04/avoiding-long-classpath-issue-in-ant.html

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Try to compile any static plugin on Windows environment.

## Context
Reproduced on local 3.7.1 environment and reported by customer 	https://my.dotcms.com/tickets/detail.dot?id=36dfd22c-4167-44be-8891-d46f2e0be067

## Your Environment

* dotCMS 3.7.1, current master.
* Any Browser.
* Any Windows-flavored OS.
* Tomcat 8.0.18
* Java 8u131.
* Any DB.

**Comment by gabbydotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/11624

**Comment by jgambarios** [comment]
**Note to QA:** Please make sure it is working using the source code and the distribution

**Comment by bryanboza** [comment]
Fixed, tested with a static plugin on Windows and works as expected
