### ISSUE TITLE
Future Time Machine Not displaying content waiting to publish

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11638]
Future Time Machine not displaying content waiting to be published

1) Create a new content type, and establish mandatory publish and expire fields on the content type
2) Create a new container and place the new content type on the container exposing the title field, then create a template that uses the container, then a page that uses that template
3) Place one piece of content that is published already and expires on a future date, then create another piece of content that will publish and expire in the future.
4) Go to the future time machine and examine the page - bug is that the "future publish" content does not display on the page.

screencast: https://screencast.com/t/FGCJY1nqCdGo

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11692

**Comment by oarrietadotcms** [comment]
PR release 4.1.0: https://github.com/dotCMS/core/pull/11701

**Comment by DeanGonzalez** [comment]
Passed QA - good fix
