### ISSUE TITLE
Message improvements trying to publish scheduler content with future dates

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11637]
When you have a content type, and set the publish and expire fields to schedule auto publish/expire content, if you try to publish some content that have a future publish date, the system isn't showing an error as in the 3.x versions. 

## Expected Behavior
We should show a notification at the UI level, and improve the log error 

## Current Behavior
The system isn't publishing the content, and shows an error on log, but we never notify the user about the error in the UI, also we unable to resolve the **message.contentlet.publish.future.date** property...

**FYI**: Tested on 4.0 and we have the same behavior 
Here the log: https://gist.github.com/bryanboza/41f14af5ea4b3fef618b38e02d760d2b

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type with 2 date time fields (make sure are indexed )
3. Go to the content type properties and set this fields to the publish and expire values... 
4. Try to publish some piece of content with a future publish date 

## Your Environment
Tested on the last release-4.1 // Oracle // Chrome

**Comment by erickgonzalez** [comment]
PR to fix log https://github.com/dotCMS/core/pull/12004 tested on 3.x and there isn't anything showing at UI level. Bryan's gonna check it again, but if he is not able to reproduce we can add the UI as an enhancement.

**Comment by bryanboza** [comment]
After test this, seems we have the same behavior at the UI level in the 3.x versions, just works in 2.x https://screencast.com/t/XshLGO9uT

**Comment by jgambarios** [comment]
**Note to QA:** This is an old ticket, It is still a problem?

**Comment by bryanboza** [comment]
Yes, tested in the last master and we are able to reproduce. We need work on this improvement

**Comment by wezell** [comment]
this works as of 5.1.6
