### ISSUE TITLE
remove legacy vanity url logic

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11632]
1. Remove the package
2. Unmap virtual links from the hibernate.xml
3. Delete the old table

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/12143
https://github.com/dotCMS/enterprise-2.x/pull/485

**Comment by bryanboza** [comment]
Having some errors on log when you start dotCMS, waiting for the new starter to make sure this disappear
