### ISSUE TITLE
Order cache stats

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11646]
We should order the cache stats list ALPHA

**Comment by wezell** [comment]
![screen shot 2017-05-18 at 8 20 17 pm](https://cloud.githubusercontent.com/assets/934364/26228409/7770fc8a-3c07-11e7-830b-84d2517edd3c.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11647

**Comment by bryanboza** [comment]
Fixed, ordered alphabetically by region
