### ISSUE TITLE
Cut off button on dialog popup

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11656]
## Steps to Reproduce (for bugs)

1. Edit a generic content 
2. In the WYSIWYG click on "insert image"
3. In the dialog select any folder
4. Click on the button: "Upload new file"
5. Buttons are cut off: https://www.screencast.com/t/4klPgJWk

**Comment by woontsoudev** [comment]
Completed, https://github.com/dotCMS/core/pull/11775
