### ISSUE TITLE
We are not respecting the DEFAULT_PAGE_TO_DEFAULT_LANGUAGE property

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11654]
Related to #11640 

We are having a strange behavior when you turn off, this because if you turn off that property, we should see a 404 error if you try to see another language version of the page, and right now if you turn off this.

But the system continue working according that other properties
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=false
DEFAULT_WIDGET_TO_DEFAULT_LANGUAGE=true

At the end, turn off the DEFAULT_PAGE_TO_DEFAULT_LANGUAGE should invalidate this other properties. 

## Steps to Reproduce (for bugs)
1. Turn off this property DEFAULT_PAGE_TO_DEFAULT_LANGUAGE (in the dotmarketing file)
2. Try to see the Spanish version of any page, that ONLY exist in english 

## Your Environment
Tested in the last master-4.1 // Postgres // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14805

**Comment by bryanboza** [comment]
Ok after the last test we need a couple of fixes here: 

- [ ] We need to validate the error of those cases from FE

- [ ] We are having a 500 error when you have a page in any language and ask for a page in the default language and this does not exist. 

- [ ] The DEFAULT_PAGE_TO_DEFAULT_LANGUAGE property isn't changing dynamically, you need restart the server to apply the change

**Comment by jdotcms** [comment]
As a recommendation, when the user creates a new language, it would be a good idea to create also the error page and vanity url for that language.
@wezell

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14840

**Comment by bryanboza** [comment]
Fixed, tested with the last changes and now this is working
