### ISSUE TITLE
Text Area fields isn't saving the content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11652]
When you add some content in a text area field, the system isn't saving this data when you try to edit the piece of content 

## Expected Behavior
We should be able to see the data when you try to edit the content 

## Current Behavior
Isn't saving the content 

SC: https://screencast.com/t/n0lqRjWlRMQ

## Steps to Reproduce (for bugs)
1. Create a new content type
2. Add Just a text and a text area field
3. Try to add a new content 
4. Type some data and save it 
 
## Your Environment
Tested on master-4.1

**Comment by wezell** [comment]
The issue is that the data_type is not being passed in from the struts action - they are being set to "system_fields"

![screen shot 2017-05-19 at 12 38 44 pm](https://cloud.githubusercontent.com/assets/934364/26257855/306537f0-3c90-11e7-908a-94aa92b6ca5d.png)

**Comment by jdotcms** [comment]
Confirmed, the text are is saved with a fieldContentlet as a system_field and the saveContent is filtering it by that reason

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11667

**Comment by bryanboza** [comment]
We are having problems getting the value property,  and we are unable to save the content 
SC: https://screencast.com/t/pyGYVw1TnbF 
Log: https://gist.github.com/bryanboza/704ad4dbcc6a9af28293ed574b1e77fd

**Comment by wezell** [comment]
fixed here:

https://github.com/dotCMS/core/commit/f0053dac5e2ed3243adddaea085e648b446055df

**Comment by bryanboza** [comment]
Fixed, tested on the last release-4.1 // Oracle // Chrome
