### ISSUE TITLE
An empty list is a valid value to be stored in the Cache for Roles

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11650]
On Roles we are checking if Layouts are empty or null, consequently we are making a db hit if the layout is null or empty. We shouldn't check empty since it is a valid value, just be null the only one checked.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11658

**Comment by bryanboza** [comment]
Fixed, tested on release-4.1
