### ISSUE TITLE
Cluster issue: 2nd node’s status is showing red in Network tab even though it’s sharing successfully with 1st node

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11663]
When you set up a cluster with 2 or more nodes in a VM, 1st (local) node’s status is showing green in Network tab but 2nd (remote) node’s status is red even though it’s sharing successfully assets and db with 1st (local) node.
This issue is not stopping nodes to share data/assets/etc. between them.
This issue is happening when using either autocluster or manual cluster configuration.
This is happening with 2 or more nodes set up in a VM.
Issue may not be reproducible when all nodes are set up in the same computer.

## Expected Behavior
Node's status should be green in Network tab when there are no issue between nodes

## Current Behavior
1st (local) node’s status is showing green but 2nd (remote) node’s status is showing red in Network tab even though it’s sharing successfully assets and db with 1st (local) node.

![image](https://cloud.githubusercontent.com/assets/8741846/26314360/fc9426ec-3eca-11e7-827b-26548ee9ce49.png)

## Steps to Reproduce (for bugs)
1. Set up 2 (or more) nodes in a autocluster or manual configuration using VMs. 
2. Start up 1st node/dotcms instance and apply license pack to use cluster nodes.
3. Check Network tab and make sure node's status is green 
4. Start up 2nd node/dotcms instance. 
4. Check Network tab. You will see 2nd (remote) node’s status is showing red even though it’s sharing successfully assets and db with 1st (local) node.

## Your Environment
* dotCMS version used: Dotcms 4.1.0 distribution generated from master on commit  6b1238a802537d5cc3b2ed56c0b130e52195e6a0
* Database and version: MySQL 5.6.35 (remote node) / MySQL 5.6.35 (local node)
* Operating System and version: Ubuntu 14.04.1/ Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
I believe this has been fixed, please retest

**Comment by dsilvam** [comment]
Note to QA: There is no direct PR for this one, but it might be fixed when changes from p8 were brought back.
