### ISSUE TITLE
Constraint violation when executing Task04115LowercaseIdentifierUrls

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11664]
This is because of duplicated records after applying the lower. 

Error in the log:
java.sql.BatchUpdateException: Batch entry 28 UPDATE identifier SET parent_path = ‘/design/images/template/‘, asset_name = ‘logo(old).png’ WHERE id = ‘e18e86db-060d-4480-80f2-aa1ec6857155’ was aborted.  Call getNextException to see the cause.

Real error: 
[2017-05-18 17:27:20] [23505] ERROR: duplicate key value violates unique constraint “identifier_unique_key”
[2017-05-18 17:27:20] Detail: Key (parent_path, asset_name, host_inode)=(/design/images/template/, logo(old).png, c355915b-94cb-4fb2-8ffb-a0a0576fadb1) already exists.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11670

**Comment by oarrietadotcms** [comment]
Records on identifer: 1.771.853 
Records to lower/update: 246.074
Failed records: 1.803
Time: 10:46:42.422 -> 10:50:15:961

**Comment by oarrietadotcms** [comment]
PR release 4.1.0: https://github.com/dotCMS/core/pull/11676

**Comment by oarrietadotcms** [comment]
Note to QA: test against Postgres DB dump.

**Comment by shaydotcms** [comment]
Passed QA.
Tested on upgraded from dotcms 3.6 to 4.1.0 against client's DB in postgres. No isssues with task04115 registered on logs:
https://gist.github.com/shaydotcms/932742096246aa18c7e58add170464b8

(Dotcms 4.1.0 distribution generated from realease-4.1 after commit 7bfb5dc5c7c460fcd0628978cb4468aaf7283d67
Ubuntu 14.04.1 / Postgres 9.3.5 / Tomcat 8 / Java 8)
