### ISSUE TITLE
Aleatory error creating pages

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#11679]
Sometimes when you create a page, you will see that the lock button is not shown properly. 

<img width="1151" alt="screen shot 2017-05-22 at 10 06 28 am" src="https://cloud.githubusercontent.com/assets/1569280/26359701/29656bc0-3fa4-11e7-977a-b1820a7c30eb.png">
When that happens the live mode of the page sometimes doesn't work, meaning that doesn't show anything on the live mode tab, even if you have contents with live versions. The error is aleatory and if you try to clean the cache or reindex the error continue

## Steps to Reproduce (for bugs)

1. Create a page
2. When you see the error that the lock button is not displayed
3. reload the page, add some contents with live versions
4. check if the  live mode display the contents

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: All
* Operating System and version: Mac OSX
* Java Brand and version: 1.8

**Comment by wezell** [comment]
wow, nice use of the word aleatory Ozzy!

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11693

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes....
