### ISSUE TITLE
Unable to edit the text fields data type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11681]
NPE when you try to edit the data type from a existing text field 

## Expected Behavior
We should be able to edit any kind of file without problems 

## Current Behavior
We are having a NPE every time you try to change the datatype of a text field and the change isn't saved 

SC: https://www.screencast.com/t/HExli4oDa
Here the log: https://gist.github.com/bryanboza/001c87d67439a9ad6310d3371a12e7fc

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content  type 
3. Add a new text field and save it 
4. Try to edit the text field and set the data type to decimal 
5. Try to save it 

## Your Environment
Tested in the last release-4.1 // Oracle 11g // Chrome

**Comment by wezell** [comment]
Users should not be able to change the data type of a field.  The good news is we a preventing this from at the API/factory level.  We need to prevent it at the UI level (change the jsp to not allow for changes once the field has been saved.)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11700

**Comment by bryanboza** [comment]
Fixed, tested on release-4.1 // postgres // FF
