### ISSUE TITLE
When server is bounced, the admin does not load

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11705]
If you are logged into the admin and the server is bounced (no remember me) and you refresh your browser, the menus throw a 500 error and the admin never loads. You need to wipe your cookies to re-login

**Comment by wezell** [comment]
![screen shot 2017-05-24 at 6 36 26 pm](https://cloud.githubusercontent.com/assets/934364/26428481/edbca054-40af-11e7-9988-c72b9d0b4382.png)

**Comment by wezell** [comment]
also, shouldn't we be in prod mode?

**Comment by fmontes** [comment]
Closed "but expect to see it again"
