### ISSUE TITLE
Starting dotCMS with Mysql connection

### ISSUE THREAD

**Issue by youngstone89** [dotCMS/core#11708]
## Current Behavior

There are serveral errors occuring in starting up the dotCMS application with mysql connection
1. First Error-NameNotFoundException
![image](https://cloud.githubusercontent.com/assets/19413355/26432271/7f5256c8-4135-11e7-8b42-abb96f3eae13.png)

2. Second Error- Error cluster.ClusterFactory: Could not save Server to DB
![image](https://cloud.githubusercontent.com/assets/19413355/26432318/e7deaf70-4135-11e7-95a1-dffb530cab12.png)

3. Third Error- license.LicenseManager: Server not found
![image](https://cloud.githubusercontent.com/assets/19413355/26432367/4bee0592-4136-11e7-9721-4586984a62e7.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Because of those errors, dotCMS application isn't initiated properly. 
The only thing I want is to connect Mysql with dotCMS. 
It works with H2 default database for starting up the dotCMS but not with Mysql. 

## Your Environment

* dotCMS version used: dotCMS 4.0.1
* Operating System and version: Amazon EC2
* Application Server and version: Tomcat inside dotCMS archive 
* Java Brand and version: openJDK 1.8+
* Database and version:  Mysql 5.6.36
* Application module (if apply):

**Comment by jgambarios** [comment]
Closed as looks like a configuration error, if the problem persist please use our community group https://groups.google.com/forum/#!forum/dotcms
