### ISSUE TITLE
Failed bundle wipes index entry of modified content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11716]
If you import a bundle and some of the content objects fail, this throws a bundler exception which is good.  The problem arises when content is been successfully imported and then something a subsequent handler is doing fails.  This rolls back all the commit listeners and the content index gets out of whack.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/publisher/receiver/BundlePublisher.java#L201-L209

**Comment by wezell** [comment]
[ea4fa05f-67f2-434f-8a86-a0a8c9519bb9.tar.gz](https://github.com/dotCMS/core/files/1029825/ea4fa05f-67f2-434f-8a86-a0a8c9519bb9.tar.gz)

Try to import this bundle first and then checkout the hosts list

**Comment by wezell** [comment]
![screen shot 2017-05-25 at 2 12 52 pm](https://cloud.githubusercontent.com/assets/934364/26464019/539e3e06-4154-11e7-9ac7-5b61349d8624.png)

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/11988

**Comment by shaydotcms** [comment]
Passed QA.
Successfully uploaded different bundles, including bundle provided by Will in this issue.
Bundler exception is still thrown when some of the content objects fail, which is good.
Hosts are not missing from the Content Search, as they were before the fix
![image](https://user-images.githubusercontent.com/8741846/27697047-6e933e74-5cb0-11e7-9d86-86e468370bbe.png)
Created/deleted different hosts and changes are being shown appropriately

Tested locally using the following environments:
Fresh starter and also using upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit 46d9818107ca6938e4b0fa30364d707ac1ddb423
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
