### ISSUE TITLE
Bad response in Content Type REST API when trying to save content type with already used velVar

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11722]
curl -v -u admin@dotcms.com:admin -XPOST http://localhost:8080/api/v1/contenttype -H "Content-Type: application/json" --data @bodyCreate.json

**Notice field "variable" has value "Products" which is already used for a different content type in starter**
```
{
  "clazz": "com.dotcms.contenttype.model.type.ImmutableSimpleContentType", 
  "defaultType": false, 

  "name": "validName", 
  "description": "THE DESCRIPTION", 

  "host": "48190c8c-42c4-46af-8d1a-0cd5db894797", 
  "owner": "dotcms.org.1", 

  "variable": "Products",

  "fixed": false, 
  "system": false, 
  "folder": "SYSTEM_FOLDER"
}
```

Problem is the REST api should return 400 bad request and specifying the error to the user. 
Instead is returning a 200 ok with the HTML code used to response for errors in the UI (The HTML code includes a 500 code in the output). 

Error is logged properly though it should not be that verbose, should be only a one line log.  
Error in log:  https://gist.github.com/dsilvam/687c4c133fcd69ed7fc28dc301407d93

**Comment by agomez-dotcms** [comment]
PR Master: https://github.com/dotCMS/core/pull/11740
