### ISSUE TITLE
Company background image doesn't show in pop-up menu

### ISSUE THREAD

**Issue by jcanup** [dotCMS/core#1172]
We uploaded a modified version of the bg-1.jpg background image to the /html/images/backgrounds/ folder.  When logging back into the application and clicking on the backgrounds button, the pop-up window does not show the new file in the pop-up window.

<i have screenshots of this issue, if someone wants them>

**Comment by wezell** [comment]
This is a good idea but 4.x will draw the pages differently and this will be a moot point.
