### ISSUE TITLE
Content Type Rest API: NPE error when content type misses one of the required fields

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11720]
When you create a content type through REST API and it misses one of the requried fields, for instance "name", the system returns a 200 OK status, however if you navigate in UI to portlet Types & Tags > Content Types, you will see a NPE error in the logs.
This issue is happening also when you update a content type through REST. 
In addition, different required fields like "variable" are triggering this error.

## Expected Behavior
System should not allow to create a content types without missing a required field, i.e.: name 

## Current Behavior
System allows you to create a content types without a required field, i.e.: name; then it throws NPE error

## Steps to Reproduce (for bugs)
1. Startup a dotcms instance
2. Create a new Content Type through REST API leaving a required filed in blank, i.e.: name

REST endpoint: ``` POST /v1/contenttype ```

curl command: ``` curl -v -u admin@dotcms.com:admin -XPOST http://localhost:8080/api/v1/contenttype -H "Content-Type: application/json" --data @bodyCreate.json ```

bodyCreate.json file: (notice that required field ***name is blank*** for testing purposes)
```
{
  "clazz": "com.dotcms.contenttype.model.type.ImmutableSimpleContentType", 
  "defaultType": false, 

  "name": "", 
  "description": "THE DESCRIPTION", 

  "host": "48190c8c-42c4-46af-8d1a-0cd5db894797", 
  "owner": "dotcms.org.1", 

  "variable": "TheContentType1",

  "fixed": false, 
  "system": false, 
  "folder": "SYSTEM_FOLDER"
}
```
See the doc https://auth.dotcms.com/docs/latest/content-type-api#createContentType for more info about creating a content type using REST APIs

3. Check the status response. You will get a 200 OK, however it should not allow to create a content types without missing a required field 
4. In the UI, navigate to portlet Types & Tags > Content Types
5. Check the logs, you will see a NPE error:
https://gist.github.com/shaydotcms/5ebd97b30539a20f2eb05aa887254c4a

## Your Environment
* dotCMS version used: Dotcms 4.1.0 distribution generated from release-4.1 with commit b2682bce459687e928267ff941ae2de83504e3a7
* Database and version: MySQL 5.6.35 
* Operating System and version: Mac OS 10.10.5 
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by dsilvam** [comment]
PR master: https://github.com/dotCMS/core/pull/11729#pullrequestreview-40418672
