### ISSUE TITLE
NPE error on Content Type Fields Rest API

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11727]
Similar to #11720 the system throws an NPE error when a content type field misses one of the required fields, i.e.: name
This happens when we use the REST endpoints to create content type fields.

## Expected Behavior
System should not allow to create a content type fields without missing a required field, i.e.: name

## Current Behavior
Using the REST endpoints, when there's a blank required field, the system throws an NPE error in the logs, however the status returned is 200 OK 

## Steps to Reproduce (for bugs)
1. Startup a dotcms instance
2. Create a new Content Type through REST API or through the UI 
3. Now create a content type field (in this case text field) using the REST endpoints and leave blank a required filed, i.e.: name

REST endpoint: ``` POST /v1/contenttype/{typeId}/fields ```

curl command: ``` curl -v -u admin@dotcms.com:admin -XPOST http://localhost:8080/api/v1/contenttype/ddf29c1e-babd-40a8-bfed-920fc9b8c77f/fields -H "Content-Type: application/json" --data @bodyCreate.json  ```

bodyCreate.json file: (notice that required field ***name is blank*** for testing purposes)
```
{
    "clazz" : "com.dotcms.contenttype.model.field.ImmutableTextField",
    "contentTypeId" : "ddf29c1e-babd-40a8-bfed-920fc9b8c77f",
    "dataType" : "TEXT",
    "name" : "",

    "defaultValue" : "THE DEFAULT VALUE",
    "regexCheck" : "THE VALIDATION REGEX",
    "hint" : "THE HINT",

    "sortOrder" : 11,
    "readOnly" : "false",
    "fixed" : "false",

    "required" : "true",
    "searchable" : "true",
    "indexed" : "true",
    "listed" : "true",
    "unique" : "false"
}
```
See the doc https://auth.dotcms.com/docs/latest/fields-content-type-api#createField for more info about creating a content type field using REST APIs

4. Check the status response. You will get a 200 OK, however it should not allow to create a content types field without missing a required field 
4. In the UI, navigate to portlet Types & Tags > Content Types
5. Check the logs, you will see a NPE error:
https://gist.github.com/shaydotcms/1c93115a3de1528a3d8fa69eee28e936

## Your Environment
* dotCMS version used: Dotcms 4.1.0 distribution generated from Release-4.1 on commit b2682bce459687e928267ff941ae2de83504e3a7
* Database and version: MySQL 5.6.35 
* Operating System and version: Mac OS 10.10.5 
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by agomez-dotcms** [comment]
PR Master: https://github.com/dotCMS/core/pull/11743
