### ISSUE TITLE
System allows to save blank key/value fields thru REST in Content Type Fiel Variables 

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11730]
UI doesn't allow to create a content type field variable with blank key/value fields, which is the right behavior, however this is possible thru REST.

## Expected Behavior
System should not allow to save key/value fileds in blank.

## Current Behavior
You are allowed to create a content type field variable with blank key/value fields. This is wrong.

## Steps to Reproduce (for bugs)
1. Startup a dotcms instance
2. Create a new Content Type and a new field through REST API or UI
3. Now create a content type field variable thru REST leaving in blank the key/value fields

REST endpoint: ``` POST /v1/contenttype/{typeId}/fields/id/{fieldId}/variables ```

curl command: ``` curl -v -u admin@dotcms.com:admin -XPOST http://localhost:8080/api/v1/contenttype/ddf29c1e-babd-40a8-bfed-920fc9b8c77f/fields/id/0dbb0e2e-679f-420b-94a6-10d114288c0b/variables -H "Content-Type: application/json" --data @bodyCreate.json ```

bodyCreate.json file: (notice that required ***key/value fields are left in blank*** for testing purposes)
```
{
  "clazz": "com.dotcms.contenttype.model.field.ImmutableFieldVariable", 
  "fieldId": "0dbb0e2e-679f-420b-94a6-10d114288c0b", 

  "key": "",
  "value": ""
}
```
See the doc https://auth.dotcms.com/docs/latest/field-variables-content-type-api#createFieldVariableFieldID for more info about creating a content type field variable using REST APIs

3. Check the status response. You will get a 200 OK, however it should not allow to create a content type field with blank key/value fields. 
4. In the UI, navigate to portlet Types & Tags > Content Types
5. Click to open the Content Type you just created. Now open/edit the content type field you just created.
6. Finally go to Field Variables tab. You should see an entry with no key/value data, for example:
![image](https://cloud.githubusercontent.com/assets/8741846/26474987/dccfde56-4171-11e7-9504-e8fea2817a28.png)

7. There are no errors in the logs. System return 200 OK status

## Your Environment
* dotCMS version used: Dotcms 4.1.0 distribution generated from release-4.1 with commit b2682bce459687e928267ff941ae2de83504e3a7
* Database and version: MySQL 5.6.35 
* Operating System and version: Mac OS 10.10.5 
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
@shaydotcms my question for you to test is if you is if you can add two FieldVariables with no keys.  Or two that have the same key.  Those should def fail.

**Comment by agomez-dotcms** [comment]
PR Master: https://github.com/dotCMS/core/pull/11745
