### ISSUE TITLE
Contentlets are not associated to the content types by dependency when you push an entire site

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11748]
When you push an entire site we should send all the content of this site, including pages, files, content types and their contentlets. 

## Expected Behavior
We should send the content type and their contents by dependency

## Current Behavior
After the fix #11723, now we are sending the content type, but not their contents 

No errors on logs...

## Steps to Reproduce (for bugs)
1. Crete a new site  
2. Add a new structure to this site  
3. Add some contents to the created structure 
4. Push the entire site 

5. Check on receiver, you have the contents associated to the structure 

## Your Environment
Tested on release-4.1 // postgres... This on both sides

**Comment by wezell** [comment]
@bryanboza did you add a host / folder field to the content type?

and when you added the content to that type, did you select the new site

**Comment by bryanboza** [comment]
I just set the content type to the host, after add the site/folder field works as expected...
