### ISSUE TITLE
We need to check individual permissions on contenttype update

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11754]
We are checking inherited permissions on a content type when we save/update it, but we should check if it has been permissioned individually on update.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14891

**Comment by erickgonzalez** [comment]
If permissions are assigned individually on a content type to a limited user they're respected.

- View Permission -> Not able to create or update content, only view it.
- Edit Permission -> Able to create or edit content but only Save it, not publish it.
- Publish Permission -> Able to create or edit content and publish it.

**Comment by erickgonzalez** [comment]
Also tested edit the content-type with diff type of permissions:
- View and Edit Permissions -> Not able to edit the Content-Type but we should show an error in the UI e.g **You do not have enough permissions to perform the action**, we only show the error on the log.

- Publish Permission -> Can edit the Content-Type unless you try to edit permissions.

- Edit Permissions Permission -> Can edit the whole Content-Type even permissions.

**Comment by bryanboza** [comment]
Fixed tested as the last comment and works fine

**Comment by dsilvam** [comment]
Note to QA: required individual permission to edit a content type or its fields or field variables now is EDIT_PERMISSIONS

**Comment by dsilvam** [comment]
new PR: https://github.com/dotCMS/core/pull/15000

**Comment by DeanGonzalez** [comment]
Needs work.  I only gave the Contributor Role - Publish on the Content Type.  No Edit Permissions, and I was able to delete all the non-system fields from the Documentation content type, completely destroying all the content for those fields... we need to lock that down too.

**Comment by dsilvam** [comment]
new PR: https://github.com/dotCMS/core/pull/15048

**Comment by nollymar** [comment]
During tests I was able to update content types and fields successfully. However, deleting Filckr content type was not possible. This issue was registered on this card: https://github.com/dotCMS/core/issues/15070

**Comment by bryanboza** [comment]
Ok guys, after test with the last version of release 5.0, we have the following errors: 

When you set publish permissions. 
- [ ] We are able to delete fields of the content type

- [ ] We are able to add/remove relationships of this content type

- [ ] We are able to delete the entire content type

**Comment by nollymar** [comment]
* [ ] Additionally, when Edit Permissions is set, it is not possible to delete **Contact Us** content type

**Comment by dsilvam** [comment]
@bryanboza point 1 is behaving correctly in master. The field disappear but if you reload the portlet, it is there again. Got this error in the log: 
```
Caused by: com.dotmarketing.exception.DotSecurityException: User:Joe Contributor : dotcms.org.2789 does not have permissions EDIT_PERMISSIONS for object SimpleContentType{name=testType 1, id=3cff796c-aa61-4e12-a0bf-a5f6cbea7948, description=null, defaultType=false, detailPage=null, fixed=false, iDate=Thu Aug 09 20:48:38 MSK 2018, system=false, versionable=true, multilingualable=false, variable=Testtype1, urlMapPattern=null, publishDateVar=null, expireDateVar=null, owner=null, modDate=Thu Aug 09 20:48:52 MSK 2018, host=48190c8c-42c4-46af-8d1a-0cd5db894797, folder=SYSTEM_FOLDER, requiredFields=[]} of type com.dotmarketing.portlets.structure.model.Structure
	at com.dotmarketing.business.PermissionBitAPIImpl.checkPermission(PermissionBitAPIImpl.java:281) ~[dotcms_5.0.0_d7b6b4f.jar:?]
```

**Comment by dsilvam** [comment]
@bryanboza @DeanGonzalez not working on point 2 since we are redoing rels on a new issue #14298

**Comment by dsilvam** [comment]
@bryanboza not able to delete content type with limited user as stated in point 3. Getting this in the log: 
```Caused by: com.dotmarketing.exception.DotSecurityException: User:Joe Contributor : dotcms.org.2789 does not have permissions EDIT_PERMISSIONS for object SimpleContentType{name=testType 1, id=3cff796c-aa61-4e12-a0bf-a5f6cbea7948, description=null, defaultType=false, detailPage=null, fixed=false, iDate=Thu Aug 09 20:48:38 MSK 2018, system=false, versionable=true, multilingualable=false, variable=Testtype1, urlMapPattern=null, publishDateVar=null, expireDateVar=null, owner=null, modDate=Thu Aug 09 20:48:52 MSK 2018, host=48190c8c-42c4-46af-8d1a-0cd5db894797, folder=SYSTEM_FOLDER, requiredFields=[]} of type com.dotmarketing.portlets.structure.model.Structure
	at com.dotmarketing.business.PermissionBitAPIImpl.checkPermission(PermissionBitAPIImpl.java:281) ~[dotcms_5.0.0_d7b6b4f.jar:?]
```

**Comment by dsilvam** [comment]
Please check latests comments. Moving to Done

**Comment by bryanboza** [comment]
nothing to check here, the case was moved to a new card
