### ISSUE TITLE
Fix sites enpoint pagination

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11753]
The parameter for results it's harcoded to: ```1```

### The solution:
1. Remove the ```currentSite``` endpoint
2. Update the ```sites``` to receive a parameter to receive the current site.

### Acceptante Criteria
1. Update unit tests
2. Update the Frontend: https://github.com/dotCMS/core/issues/11698
3. JavaDoc

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11888
