### ISSUE TITLE
Categories for a content are not been filtering correctly

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11751]
Categories for a content are not been filtering correctly

## Expected Behavior

Based on https://my.dotcms.com/tickets/detail.dot?id=ae389c95-db31-43f0-a874-1443f9d60c6d 
the categories on the content rest are not retrieving the right subcategories, for the content categories.

Have to fix the code in order to retrieve the right parent categories filtered by the current category field

## Current Behavior

The current rest get content does not return the right parent categories filtered, instead of it returned all parent categories even if it is not a child of the category field.

## Steps to Reproduce (for bugs)

Check the steps on the ticket

## Your Environment

* dotCMS version used: 4.0.1
* Browser Name and version: Chrome, FF
* Operating System and version: Mac
* Application Server and version: Tomcat
* Java Brand and version: 1.8
* Database and version: MySQL
* Application module (if apply):

**Comment by gabbydotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/11755

**Comment by dsilvam** [comment]
We need a test reproducing this behavior before the fix and passing it after

**Comment by oarrietadotcms** [comment]
Integration test added to the PR: https://github.com/dotCMS/core/pull/11755

[Log from master (without fix merged)](https://gist.github.com/oarrietadotcms/fec92325812f6ce5ca8fdc6860403e4b)
[Log from the branch](https://gist.github.com/oarrietadotcms/365e5a96e566d1c884106013c6dcd8f6)
