### ISSUE TITLE
Only run Func/Full tests if there has been a commit since the last run

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11752]
As our testing requirements grow with the number of releases and supported releases we should only run the long expensive ($$$) tests if there has been a change in the codebase.  For example, I saw this running monday night after a long weekend where monday was a holiday and no commits had been made:

![9 25 pm monday night](https://cloud.githubusercontent.com/assets/934364/26593105/fa6a6b1c-4530-11e7-8fef-2e09c4445336.gif)

**Comment by agomez-dotcms** [comment]
I just added changes to support this. This should now be done. I will leave it under "In Review" to make sure it behaves as promised.
