### ISSUE TITLE
Uppercase on Identifier table when updating a folder name

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#11762]
## Expected Behavior
The asset name column on the identifier table should be lower case when updating a folder name.

## Current Behavior
If you update a folder name the asset_name saves with the case you typed.

## Steps to Reproduce (for bugs)
1. Create a folder
2. Edit the folder created but only the Name field and only use Uppercase.
3. Check the identifier table, the asset_name is on Uppercase.

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by wezell** [comment]
I do not believe this will cause issues as the identifier lookup is still case insensitive

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11802

**Comment by bryanboza** [comment]
Fixed, tested on the last master code and now we are saving all the folders in lowercase... Also the integrity checker is detecting conflicts

**Comment by bryanboza** [comment]
Test case added here: http://qa.dotcms.com/index.php?/cases/view/62070
