### ISSUE TITLE
Delete field from content types isn't updating the mod_date field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11776]
We are having some problems when you try to delete some field from any content type, this because we are not updating the mod_date field in the DB, and this is affecting the system when you try to push publish twice the same structure, because we are not detecting changes and send an empty bundle... 

**FYI: Also we have the same problems editing the field variables** 

## Expected Behavior
When you delete some field from any content type we need update the mod_date field

## Current Behavior
We are not updating this field 

## Steps to Reproduce (for bugs)
1. Configure the push publish environment 
2. Create a new content type 
3. Add two fields to this content (any type)
4. Push this content type 
5. From sender delete one of the content type fields 
6. Try to push again 

## Your Environment
Tested on the last release-4.1 // Postgres

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11781

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11781

**Comment by oswaldogallango** [comment]
There is a case that needs to be fixed and it's when you eliminate a FieldVariable and you do a push. The bundle is sending the new Content Type without the eliminated FieldVariable  (which is good) but the save logic of the ContentTypeAPI is not managing the removal of those extra FieldVariables. Meaning that can add and edit FieldVariables, but isn't removing the eliminated ones (the field variables removed from the authoring server) on the receiver server.

**Comment by bryanboza** [comment]
Fixed, pending delete field variables but was reported here: #11819
