### ISSUE TITLE
Need update/delete content types relationships via push publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11779]
We are having some problems related to the relationships: 

### Case 1

- [ ] If you push the content type with a relationship, and delete the relation and push again, neither is deleting the relation on receiver... (also if you force push)

### Case 2

- [ ] If you push the content type with a relationship, and delete the relation, and create a new one to the same content type, and push again, the system is not deleting the old relation on receiver, but is creating the new one

## Expected Behavior
We should edit the mod date when you made any change in the relationships
Also we need implement the way to delete relationships by dependency 

## Current Behavior
We never delete relationships, you can force push and neither works 

## Your Environment
Tested in the last release-4.1 // Postgres (this on both nodes)

**Comment by bryanboza** [comment]
Tested on dotCMS_3.7 and we have the follow behavior: 

- If you update any relationship and push the content type again, the system is modifying the mod_date and made the change on receiver without problems 

- The delete cases isn't working, if you delete the relationship and force push, the system isn't deleting this on receiver (bug)

**Comment by wezell** [comment]
This would be a new feature - what we need is a relationship push delete
