### ISSUE TITLE
Update of a content type needs to alter its mod_update at API level

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11787]
We have this correct in case of deleting the fields or fields var of a content type, but we are missing some cases or those are badly placed

- Content Type updated. Include Test case
- Field created. Include Test case
- Field updated. Include Test case
- Field deleted. (Done already). Include Test case
- Field var created. Include Test case
- Field var deleted. (Done already). Include Test case

**Comment by oswaldogallango** [comment]
this test where done on https://github.com/dotCMS/core/issues/11776

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/11781

**Comment by bryanboza** [comment]
Fixed, tested on the last release-4.1 and now works as expected
