### ISSUE TITLE
Problems trying to show content types relations into the relationship field

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11782]
We are having a JS problems when the system try to show the content type relation into a relationship field...

## Expected Behavior
As in previous versions, when you add the relationship filed, we should delete the relation tab and show this info into the field. 

## Current Behavior
We are having this error in the JS console, and the content never loads 
```
VM21170 dojo.js?b=4.1.0:2 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at _38c (VM21170 dojo.js?b=4.1.0:2)
    at Object.empty (VM21170 dojo.js?b=4.1.0:2)
    at Object.advice (VM21170 dojo.js?b=4.1.0:2)
    at Object._25a [as empty] (VM21170 dojo.js?b=4.1.0:2)
    at Object.html._setNodeContent (VM21175 build.js?b=4.1.0:4)
    at Object.html.set (VM21175 build.js?b=4.1.0:4)
    at VM51850 layout?p_l_id=71b8a1ca-37b6-4b6e-a43b-c7482f28db6c&p_p_id=content&p_p_action=1&p_p_state=ma…:1447
    at _181 (VM21170 dojo.js?b=4.1.0:2)
    at _17d (VM21170 dojo.js?b=4.1.0:2)
    at _179 (VM21170 dojo.js?b=4.1.0:2) 
```

**FYI:** Tested on 3.7 and works fine 

## Known Workarounds
We tested this and the problem is when you add this field to the content type and this have a relation. 

## Steps to Reproduce (for bugs)
1. Add 2 new structures 
2. Add one text content to every content type
3. Add a new piece of content to every content type 
4. Add a new relationship between those content types 
5. Try to edit the added content of any of the content types 

## Your Environment
Tested on release-4.1 // Postgres // Chrome

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=c9be55a7-5c88-4d4c-994b-81f65797c1e0

**Comment by gabbydotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/11783

**Comment by jgambarios** [comment]
**Note to QA:** @bryanboza please make sure that when the **Parent or Child is required** the required style is properly display in the UI (Red **\***), looking the pull request that could be broken.

**Comment by bryanboza** [comment]
Fixed, now we are able to see contentlets when you add the relationship field, also some improvements reported here: #11906
