### ISSUE TITLE
Allow Receive From to take a netmask

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11789]
When setting up a PP environment, we need to allow a the "Receive From" endpoint take a netmask of valid senders.

We already have the netmask parseing logic, so we just need to use when validating the receiveing server

```
import com.dotcms.repackage.org.apache.commons.net.util.SubnetUtils;



      String ipOrNetMask = instance.netmask;
      Comparison comparison = instance.comparison;

      if (ipOrNetMask.contains("/")) {
        compare = new SubnetUtils(instance.netmask).getInfo().isInRange(ipAddress);
      } else {
        compare = ipAddress.equals(ipOrNetMask);
      }
```

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/11973

**Comment by john-thomas-dotcms** [comment]
https://auth.dotcms.com/docs/latest/connecting-remote-servers#ReceiveFromServers
