### ISSUE TITLE
Deprecate and shut down legacy front end struts actions by default

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11784]
We need to shut down legacy front end struts actions by default.  They are deprecated and provide surface area for potential vulnerabilities.

It will be possible to enable them if needed but they should be disabled by default.

**Comment by wezell** [comment]
This @Deprecates every java class under com.dotmarketing.cms EXCEPT the URLMapFilter

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12412

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres
