### ISSUE TITLE
Develop content type edit/update

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11786]
We already have a component for "create" a content type. We need to update the same component to be able to "edit" a content type. **DOESN'T INCLUDE THE FIELDS DRAG&DROP FUNCIONALITY**

### How should work
1. Link from content type listing when user click a listing row
2. The component will receive the id of the content type and request the object to the crud service
3. With that object will update the form object
4. Populate the form
5. Allow editing
6. "Save" button should said: "Update" instead
7. Update button should be disabled by default and only enable if the form it's changed
8. Form validation remains the same
9. Update the request to be a PUT with the id and the new content (update the ```crud-service.ts``` to do this)
10. Url should be ```/edit/``` instead of ```/create/``` update the routing.

### Acceptance Criteria
1. Work in all the supported browsers (don't forget IE11)
2. Multilanguage
3. Unit test

**Comment by woontsoudev** [comment]
Please check the point seven:
Update button should be disabled by default and only enable if the form it's changed.
