### ISSUE TITLE
Unable to push entire sites before the last content types changes

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11793]
We are having some problems trying to push a entire site copy of demo.dorcm.com 

## Expected Behavior
We should be able to push sites without problems 

## Current Behavior
We are having an error and we are unable to push the site 

Log: https://gist.github.com/bryanboza/d057f119f87d4621fe786b4f1e537795

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Configure the push environment 
3. Create a new site copy of demo.dotcms.com
4. Try to push 

## Your Environment
Tested with two instances in postgres // Chrome

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11806

**Comment by dsilvam** [comment]
PR 4.1: https://github.com/dotCMS/core/pull/11807
