### ISSUE TITLE
Recommendations for English language variable values

### ISSUE THREAD

**Issue by jcanup** [dotCMS/core#1179]
Running through the US-specific country values, I found a few of them could use some tightening up or re-writing for clarification.  Here are the edits I recommend:

[Language Key] contents_not_enough_permissions
[current] Your permissions are not enough to submit this kind of content
[update] You do not have the correct permissions to submit this kind of content
# 

[Language Key] contents_edited_piece_of_content

[current] This is just a note from the dotCMS system to inform you that a piece of content you are using on a page you manage has been edited.

[update] This is just a note from the dotCMS system to inform you an edit has been made on a piece of content used on a page you manage.
# 

[Language Key]error_user_not_found
[current]The e-mail address or password is incorrect.
[update] The email address or password is incorrect.
# 

[Language Key]error_webregistration_location
[current]You need to select a location
[update] Select a location
# 

[Language Key]product_order_your_email
[current]Your E-mail:
[update]Your Email:
# 

[Language Key]product_order_thank_you_message_body
[current]Here is a summary of your order. You will be able to view the status and order history on 'Your Profile' information.<br>You will also get an email with tracking information once the order is been shipped.
[update]Here is a summary of your order. You will be able to view the status and order history on 'Your Profile' information.<br>You will also get an email with tracking information once the order has shipped.

**Comment by wezell** [comment]
@john-thomas-dotcms please review these suggestions and incorporate what you feel makes sense.  Thanks

**Comment by john-thomas-dotcms** [comment]
Turns out none of these keys exist any more.  In any case, the keys were all reviewed and grammar and language updated for 4.0.  (Every. Single. Key. :-p)
