### ISSUE TITLE
Should be able to use Default Credential Provider Chain for AWS authentication

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#11797]
Public version of https://github.com/dotCMS/enterprise-2.x/issues/469.

## Expected Behavior
The default credential provider chain should be used to create an S3 client if credentials are not provided in the Publishing Configuration setup. 

## Current Behavior
When setting up a static endpoint, a token and secret are expected to be provided. These credentials are stored in the database and then used to create an S3 Client.

## Possible Solution
See https://github.com/dotCMS/core/pull/11764 and https://github.com/dotCMS/enterprise-2.x/pull/470.

## Context
This is particularly useful when running dotCMS on ec2 instances that have an IAM policy attached to them that gives them access to s3. In that case, no other credentials are required for using the s3 Client. But even if not using ec2, this would be useful. Moving the credentials out of the UI and into a credentials file on the server would keep users from being able to view the keys and allow rotating of credentials without having to implement some sort of credentials API.

## Your Environment
* dotCMS version used: 3.7.1 (looks like it is the same on master)

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/connecting-remote-servers#AWSS3Properties
