### ISSUE TITLE
We are not validating the first line of the value field creating radio fields on content types

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11804]
We are not validating the first line of the editor, then this is allowing wrong data in the specific formats. We just are validating the rest of the lines and not the first one 

Also when you try to add not allowed values, we have an error on log, but not showing nothing at UI level

### Case 1
We need validate all the lines to respect the specific formats 

### Case 2
Need show an error alert on the UI

### Case 1
We are allowing wrong values in the first line of the value field

SC: https://screencast.com/t/oOdlJPYmq

### Case 2
We are just showing an  error on log, but not to the end user in the UI
Log: https://gist.github.com/bryanboza/db0de7a28428f3265a73a0e1e70ce98d 
 
## Steps to Reproduce (for bugs)
1. Login 
2. Create a new structure 
3. Add a new radio field (select any specific format and add wrong values in the first line of the value field)
4. Save it 

## Your Environment
Tested on release-4.1 // Postgres // Chrome

**Comment by john-thomas-dotcms** [comment]
For select fields, the first line can be blank (e.g. a pipe with nothing on either side), so this might be related to that?  If it is, please make sure the fix for radio buttons doesn't prevent you from adding a blank first entry for select fields.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12917

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // Chrome

**Comment by jgambarios** [comment]
Fixing this issue we added logic to a Struts action which is something we should avoid, we need to move that logic to a lower layer like an API.
