### ISSUE TITLE
CategoryAPI unescaped SQL

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11811]
The categoryAPI has methods that build inline sql and don't used PreparedStatements.

**From the other issue:** 
For security purposes, details located here:
https://drive.google.com/drive/folders/0BwenB5wlEw5manZXM1R3NlZneWs?ths=true
and here:
https://docs.google.com/document/d/1xyin5LoTipC9MaTeyO8vaei-AubPf9Nc0vw7b8Lx0jg/edit

**Comment by oarrietadotcms** [comment]
I am putting this one _on hold_ until @bgriffin69 can get us a payload to reproduce this vulnerability. 

Note: We already sanitize the inode param here: [Source Code](https://github.com/dotCMS/core/blob/872d716ccd00ed8a3f1ae7007ba8ee37c5e80eaa/dotCMS/src/main/java/com/dotmarketing/portlets/categories/business/CategoryFactoryImpl.java#L623-L623)

**Comment by brentgriffin** [comment]
@oarrietadotcms -  I have been able to verify problem - Document has been updated with example payload - note, example is specific to DB as noted noted

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11860

**Comment by agomez-dotcms** [comment]
PR Release-4.1.1: https://github.com/dotCMS/core/pull/11874

**Comment by oarrietadotcms** [comment]
PR to fix Oracle bug after introducing the PreparedStatement: https://github.com/dotCMS/core/pull/11880

[Test Failing](https://cb.dotcms.com/view/builds%20-%20full%20-%20master/job/Build_Full_Tester_Func_Int_master_Oracle/6/)

**Comment by DeanGonzalez** [comment]
Tested several times - could not bring server down as in original case.
