### ISSUE TITLE
SQL injection vector

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#11813]
For security purposes, details located here:  
https://drive.google.com/drive/folders/0BwenB5wlEw5manZXM1R3NlZneWs?ths=true
and here:
https://docs.google.com/document/d/1xyin5LoTipC9MaTeyO8vaei-AubPf9Nc0vw7b8Lx0jg/edit

**Comment by wezell** [comment]
Connected with #11811

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11832

**Comment by oarrietadotcms** [comment]
PR with fixes for Integration Test: https://github.com/dotCMS/core/pull/11838

Failed Jenkins job: https://cb.dotcms.com/view/builds%20-%20continuous/job/Build_Continuous_Tester_Func_Int_master/4/

**Comment by agomez-dotcms** [comment]
PR Release-4.1.1: https://github.com/dotCMS/core/pull/11875
