### ISSUE TITLE
Take a new starter

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#11823]
Persona details are not shown when loading frontend pages on dotCMS starter site
## Expected Behavior

Details must be shown as on [demo3](https://demo3.dotcms.com/)
![demo3 persona details](https://cloud.githubusercontent.com/assets/8353755/26830541/780ba052-4ac9-11e7-8685-b0c8a91f8371.png)

## Current Behavior

Persona details are not shown, see [demo4](https://demo.dotcms.com/)
![demo4 persona details](https://cloud.githubusercontent.com/assets/8353755/26830596/a54451ea-4ac9-11e7-9e86-2680d7dee5de.png)

## Steps to Reproduce (for bugs)

1. Install dotCMS starter site
2. Apply Enteprise License
3. Go to the home page
4. Check on persona details

## Your Environment

* dotCMS version used: 4.1.0
* Browser Name and version: Chrome/Firefox (latest)
* Operating System and version: Amazon Linux/CentOS
* Application Server and version: Embedded Tomcat
* Java Brand and version: OpenJDK 1.8.0_131
* Database and version: Postgresql

**Comment by wezell** [comment]
@vianneychacon do you have an enterprise license?

**Comment by vianneychacon** [comment]
Yes, I've tested this with an enterprise license installed

**Comment by brentgriffin** [comment]
locally on 4.0.1 with enterprise license, I am seeing the same broken behavior

**Comment by wezell** [comment]
Uggh.  I had an updated starter on my local.  We need to take a new starter, where it has been fixed already.

**Comment by jgambarios** [comment]
**Note to QA:** New starter created
