### ISSUE TITLE
Cache chain properties are being reverted to default values

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#11824]
Cache chain properties are being reverted to default values when changing them via the *configuration plugin*. The properties are:
```
cache.default.chain                     =com.dotmarketing.business.cache.provider.caffine.CaffineCache
cache.contentletcache.chain =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
cache.velocitycache.chain   =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
```
Notice the tabs/white spaces on the properties. They get duplicated on the merged file after deploying plugins.
## Expected Behavior

Cache chain properties should be correctly overwritten by the configuration plugin
## Current Behavior

Properties are loaded but the default values are not commented out. In fact, I tried to erase those blank spaces and tabs and after deploying plugins the spaces and tabs are added again
## Known Workarounds

Manually comment out those properties on the merged file
## Steps to Reproduce (for bugs)

1. Edit the properties on the configuration plugins ``dotmarketing-config.properties``, for example:
```
cache.default.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient
cache.velocitymemoryonlycache.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient
cache.contentletcache.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient
cache.velocitycache.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient
```
2. Deploy plugins
3. Check out the merged ``dotmarketing-config.properties``

## Your Environment

* dotCMS version used: 4.1.0
* Operating System and version: Amazon Linux/CentOS
* Application Server and version: Embedded tomcat
* Java Brand and version: OpenJDK 1.8.0_131
* Database and version: Postgresql

**Comment by brentgriffin** [comment]
Could be related to the extra spaces we shipped with here: 
 https://github.com/dotCMS/core/blob/4.1.0/dotCMS/src/main/resources/dotmarketing-config.properties#L511-L514

**Comment by wezell** [comment]
look the the issue I just referenced. We need to make the plugin merger smarter. I believe, because it would be very nice to be able to format our property files into something nicer.

**Comment by dsilvam** [comment]
PR ant-tooling: https://github.com/dotCMS/ant-tooling/pull/7
