### ISSUE TITLE
Replace current Vanity URLs url resolver to use content

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#11825]
We need to replace in our current Vanity URLs code the logic in order to start to resolve the URLs using the new Vanity URL content type. 

For that, we need to search and modify the filters (CMSFIlter, URLMapFilter, etc ), cache, utils and factories that set and get the current Vanity URLs and change it to use the new Content Type

**Comment by oswaldogallango** [comment]
P.R to Vanity Url base branch https://github.com/dotCMS/core/pull/11907

**Comment by oswaldogallango** [comment]
This issue is related to https://github.com/dotCMS/core/issues/11627

**Comment by bryanboza** [comment]
Fixed, now we are able to resolve the vanity URL as content without problems.... Tested on mater // postgres // Chrome
