### ISSUE TITLE
When you switching between contenttype on the reuse content pop, host field is breaking

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11828]
When you switching between contenttype on the reuse content pop, host field is breaking

## Expected Behavior
Host field should not break and must shows the folders.

## Current Behavior
An error on 3.7 is happening, on 4.1 is showing an empty box.

## Possible Solution
Fix the dojo code

## Known Workarounds
Refresh the page.

## Steps to Reproduce (for bugs)

see https://my.dotcms.com/tickets/detail.dot?id=2ba9aa27-c60e-4c1f-b0f4-72eab5e9838a 

## Your Environment

* dotCMS version used:3.7.1, 4.1

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/11830

**Comment by shaydotcms** [comment]
Passed QA.
Switched between different contents (Location, Content Generic, Docuements, Banner) and clicked on Host/Site dropdown on every switch. Verified that every time the host/site is showing:

<img width="180" alt="e65a6895-ec85-41f2-b8c1-183c7c5f941c" src="https://user-images.githubusercontent.com/8741846/26888742-3233c744-4b69-11e7-97de-74163bc2d28b.png">

Upgrade from dotcms_3.3 with client dataset (db and assets) to master branch / commit d651055925d5736ccee127b5827172cfaa4c784f
Ubuntu 14.04.1 / Postgres 9.3.5 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
