### ISSUE TITLE
Problems after fix folder conflicts with the integrity checker 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11829]
We are having problems after fix some folder conflict, then the system shows all the content pages of the system into the folder. 

## Expected Behavior
We should fix the conflict and see their content without problems

## Current Behavior
The system is fixing the conflict, but when you try to open the folder this contains a list of pages of all the system. Also we are having a NPE on log 

Log: https://gist.github.com/bryanboza/b5f2276f106854311d390fdc28c6d225

SC: https://screencast.com/t/7bZA3ZHxXqkv

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your push environment 
3. Create a new folder in both environments with the same name
4. Run the Integrity checker 
5. Fix the folder conflicts 

6. Without update the portlet, navigate to the fixed folder on receiver

****FYI:** This is fixed when you refresh the portlet** 
 
## Your Environment
Sender:  Master // MySQL
Receiver: Master // H2

**Comment by bryanboza** [comment]
FYI: The same behavior on dotCMS_4.1

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11848

**Comment by shaydotcms** [comment]
Passed QA.
System assets/pages are not showing in the folder after the conflict is fixed.

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit f448026f377ce4f738cfd29e305107934141042e
Ubuntu 14.04.1 / Postgres 9.3.5 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
