### ISSUE TITLE
Warning message in dotcms.log after adding/updating any field in a Content Type

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#11839]
Every time a field is added or updated in a Content Type, a warning message in the ``dotcms.log`` file is displayed explaining a problem with the DB column property of the new ``Field`` class. However, the field is successfully added or updated.

## Expected Behavior
No warning message should be displayed, specially because the field is added/updated correctly.

## Current Behavior
The field is added/updated correctly, but the following warning message is displayed:
```
[07/06/17 10:16:56:022 CST]  WARN business.FieldFactoryImpl: field db column being updated:Unable to save field with DB Column bool - must match (system_field|(text|float|bool|date|text_area|integer)[0-9]+) Radio 1 radio1
```

## Possible Solution
Check the error in code.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Go to **Types & Tags > Content Types** portlet and create a new Content Type with any base type. Content Type details are irrelevant to this issue.
2. Add any type of field (e.g., a Radio field) to the Content Type.
3. Check the dotcms.log and you'll see the warning message posted above.

## Context
Warning messages upon a successful field creation/update is confusing to users and Sys Admins.

## Your Environment
* dotCMS version used: 4.1.0
* Browser Name and version: Any
* Operating System and version: Any
* Application Server and version: Any
* Java Brand and version: Java 8
* Database and version: Any
* Application module (if apply): Content Types

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11840

**Comment by jgambarios** [comment]
Basically the fix was to change the log level from Warn to Debug.
