### ISSUE TITLE
On copy page the content will stay related to both pages

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#11834]
When you copy an existing dotCMS page and you want to edit the content of this page the content will be changed on both pages as it's the same content which is related to both pages.

## Expected Behavior
We expect that when you copy a page that you will get content on both pages but that the content has an unique identifier on both pages, so when you change the content on page A that the content on page B will stay the same.

## Current Behavior
When you copy a page the content on both pages will be the same with the same identifier. So when you change content on page A it will also be changed on page B.

## Possible Solution
When you copy a page the content should be duplicated, so both contents have an unique identifier.

## Known Workarounds
There aren't workarounds at the moment.

## Steps to Reproduce (for bugs)
1. Login on https://demo.dotcms.com/dotAdmin/#/public/login
2. Site -> Browser -> right mouseclick on index -> Copy
3. Right mouse click on demo.dotcms.com -> Paste
4. Now you have two pages in the same folder called index and index_copy. When you open both pages you will see that the content on both pages is the same, which is fine:
- https://demo.dotcms.com/index
- https://demo.dotcms.com/index_copy
5. However when you change the content 'Global Investing' on page index_copy,  you will see that the content is changed on both pages, while I would expected that this would only be changed on the page 'index_copy'

## Context
For our customer we have pages called 'landing pages' which they use to inform customers. Sometimes they would like to create a new pages which is more or less the same as another one. So what they do is copy that page and edit some of the content on that page. However then it will be changed on both pages which isn't what they want.

## Your Environment

* dotCMS version: 3.7.1 (but it doesn't also work on the demo website which is 4.1.0)

**Comment by DannyGloudemans** [comment]
Hi,

Could you please give an update about this ticket, if this will be solved or that this functions how it's designed?

Thank you

**Comment by nkeiter** [comment]
I’m thinking this isn’t necessarily a bug, but rather a feature request to have a “Copy Page & Content” button.

As is, the system is copying the “Page Contentlet” and duplicating it properly will all properties and relationships of the original, including the content assignments.  In many cases this is the desired behavior.  I do see your point about wanting it to function differently, but I think that functionality would be a completely different feature.

**Comment by DannyGloudemans** [comment]
To be honest I cannot think of an use case where you would like copy a page and use the same content on both pages, but I can imagine that you would like to copy a page and change some of the content on it.

So it would be great to hear something from dotCMS what their opinion is.

**Comment by john-thomas-dotcms** [comment]
Although it may seem counter-intuitive at first glance, this is actually the intended behavior (to keep the same content linked to both pages).  It works this way because pages don't actually "contain" content - instead, all content on a page is merely linked to the page.  This is what allows you to display the same content on multiple pages without making a copy of that content (and then having to maintain multiple copies of the same content).

So when you copy a page, all you're copying are the page properties and the "links" to the content on the page.

**Comment by john-thomas-dotcms** [comment]
We have had requests for a "deep copy" function (separate from the normal copy function) to create separate copies of the content linked to by a page, but we don't currently have this functionality.

And although it doesn't address your current need, the use case for where you want to copy a page and not copy the content is the situation I mentioned above - when you have the same content linked from multiple pages, if copying the page creates a copy of the content, then you now have un-linked that content from the other pages it's linked to, so it becomes unclear which version of the content you want to be linked to from each page.

**Comment by john-thomas-dotcms** [comment]
Although this isn't a bug (since it's the intended behavior), I filed a separate feature request to address your use case (wanting to copy all the content on a page when it's copied): https://github.com/dotCMS/core/issues/14379
