### ISSUE TITLE
Relationship errors on Push Publish

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#11842]
We are losing relationships when Pushing content.

After pushing content with PP on the Receiver server we are wiping out the Tree records for the Relationships related to the sent content before to save the relationships sent in the bundle, that means we are removing all the relationships before to save just the ones on the bundle losing all the relationships that were not sent in the bundle.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/11846
https://github.com/dotCMS/enterprise-2.x/pull/471

**Comment by bryanboza** [comment]
Tested in the release 4.1.1 ninthly build, and we still having problems at the data validation level, this because we are not validating  dependencies in the relationships, the the system is sending the content id of some contentlets that are not in the bundle...

**Comment by wezell** [comment]
@bryanboza does this kill the push or just show in the logs

**Comment by bryanboza** [comment]
No, the push is finishing without problems, neither have errors on log, to see that is just with db queries directly... But as we talk in the meeting this is a separate improvement, i will move that to a new card..

**Comment by bryanboza** [comment]
Fixed, now we are just deleting the related contentlets of the tree table and then creating again with the new ones...

**Comment by bryanboza** [comment]
Test case created here: http://qa.dotcms.com/index.php?/cases/view/62071
