### ISSUE TITLE
Allow portal.properties to be reload without restarting the server on 4.1

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11847]
Allow portal.properties to be reload without restarting the server

## Expected Behavior
When you make a change on portal.properties configuration will be load without restart the server

## Current Behavior
If you change portal, need to restart the server to get the changes.

## Possible Solution
Integrate a file watcher over the portal.properties file

## Known Workarounds
N/A

**Comment by gabbydotCMS** [comment]
Related support ticket: https://my.dotcms.com/tickets/detail.dot?id=9e937e53-81f4-4f94-b66a-6220f248e797
