### ISSUE TITLE
field variables should allow empty values on instantiation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11849]
There is no reason field variables should not allow a key with an empty or null value when instantiated.  Maybe we prevent the save, but not on instantiation.

**Comment by dsilvam** [comment]
PR master:  https://github.com/dotCMS/core/pull/11851

**Comment by shaydotcms** [comment]
Passed QA.
Verified that field variables cannot be saved with empty/null values.
Message on logs when attempted to save field variable with empty value : 
ERROR factories.FieldFactory: FieldVariable.value cannot be empty

Response from REST when attempted to save field variable with empty value: 
{
 "message":"FieldVariable.value cannot be empty"
}

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit df7ff50790f273ac67afb31fe1a376c9feecbd0c
Ubuntu 14.04.1 / Postgres 9.3.5 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
