### ISSUE TITLE
Query param in the content type endpoint shouldn't be case sentitive

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11855]
1. http://localhost:8080/api/v1/contenttype?limit=10&offset=0 **&query=Ba** --> returns "Banner"
2. http://localhost:8080/api/v1/contenttype?limit=10&offset=0 **&query=ba** --> returns _nothing_

**Comment by dsilvam** [comment]
Note to QA: Would be good to test the performance of this with a large set of content types

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12066
