### ISSUE TITLE
Unique property isn't respecting with text fields type whole number 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11857]
If you create a new unique field type text in a content type, we are able to add multiple contents with the same value 

## Expected Behavior
We should respect that property and show an error message if the value already exist 

## Current Behavior
We allow multiple contents with the same value in the unique field 

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new content type
3. Add a new field type text (select whole number)
4. Go to content search and try to add multiple pieces of content with the same value

## Your Environment
Tested on the pre-release-4.1.1 / h2 / Chrome

**Comment by oswaldogallango** [comment]
Unable to reproduce

**Comment by bryanboza** [comment]
That's an old issue, unable to reproduce with the last code
