### ISSUE TITLE
Content Types not inheriting permissions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11850]
Inherited permissions are not respected in Content Types because of an inconsistency between the permission type in db and the permission type expected in code. 

To see the error, edit the Host content type and go to the permissions tab and no permissions will show. In 4.0, you were able to see the inherited permissions from the host. 

More Details here: https://my.dotcms.com/tickets/detail.dot?id=94168a06-0312-4900-849e-642a76fc4a50

**Comment by agomez-dotcms** [comment]
PR Master: https://github.com/dotCMS/core/pull/11852

**Comment by bryanboza** [comment]
Fixed, tested in the starter and with the real database and now the structures are inheriting permissions from host as expected

**Comment by agomez-dotcms** [comment]
PR Master (Integration Test): https://github.com/dotCMS/core/pull/11863

**Comment by bryanboza** [comment]
Testcase created here: http://qa.dotcms.com/index.php?/cases/view/62068
