### ISSUE TITLE
The contentlet resource is not returning the url field

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11878]
The contentlet resource is not returning the url field

The url field is separated from the content itself, so do we need to return it as part of the contentlet get resource.

## Expected Behavior

The url should be included, for instance
http://localhost:8080/api/content/inode/35d2008f-725c-4860-846b-859fdaa247b

{
"contentlets": [
{
"template": "afeeae75-a4ed-4cac-83e1-9d13513510c9",
"owner": "1.dotcms",
"identifier": "c740631b-baca-4f64-b822-720ea6b70515",
"friendlyname": "FriendlyName",
"modDate": "2017-05-10 11:53:52.298",
"cachettl": "15",
"languageId": 1,
"description": "add summary",
"title": "Title",
"showOnMenu": "true",
"inode": "35d2008f-725c-4860-846b-859fdaa247b",
"folder": "6bf611b1-38e9-40c1-b9c2-784eecd88259",
"sortOrder": 0,
"modUser": "1.dotcms",
"host": "70d672bc-46c3-4924-a043-47c63c43cb5b",
"lastReview": "2017-05-10 11:53:51.773",
"stInode": "b53770e7-5b84-44dd-ba64-c1ec9a6bdcec"
}
]
}

Does not return the url, but the content edit portlet does.

## Current Behavior
THe url field is not being included as part of the response

## Possible Solution
Add the url to the response

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/11882

**Comment by bryanboza** [comment]
Fixed, now we have the URL field in that resource

**Comment by bryanboza** [comment]
We are having problems with this rest, this because when you try to get any content and you don't have permissions the json comes empty, by the rest send a 200 status code, and here we need send a 401 code, that is unauthorized.... SC: https://screencast.com/t/YWdC8vY1

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12357

**Comment by bryanboza** [comment]
Still having problems with this issue, now when you don't have permissions we have a 500 error and have this error on log: 
```
User:anonymous does not have permissions to Contentlet:6915b00e-0050-488e-b8cf-70166afe4d17

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12387

**Comment by bryanboza** [comment]
Fixed, tested on master // MySQL and now is working as expected
