### ISSUE TITLE
Research messages keys json

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11871]
We have the idea of bringing all the messages keys in one request, we need to know how much kbs that will be

**Comment by freddyucv** [comment]
This the languages.properties as a json file.
the size is just 254kb.

[Language.json.zip](https://github.com/dotCMS/core/files/1075311/Language.json.zip)

..And here is that code who take the Language.properties file and create the new Language.json file.

```
        ResourceBundle language = ResourceBundle.getBundle("Language");

        Enumeration<String> keys = language.getKeys();
        Map<String, String> jsonContentMap = new HashMap();

        while( keys.hasMoreElements() ){
            String key = keys.nextElement();
            String value = language.getString(key);
            jsonContentMap.put(key, value);
        }

        Gson gson = new Gson();
        gson.toJson(jsonContentMap, new FileWriter("Language.json"));
```

**Comment by jdotcms** [comment]
Why don't use a web service: Resource to return it. You can use a Streaming
response to do lazy outpout

On Wed, Jun 14, 2017 at 10:56 AM, Freddy Rodriguez <notifications@github.com

**Comment by freddyucv** [comment]
Yes that is the idea is use a web service, but I dont sure if we need a Streaming response here

**Comment by fmontes** [comment]
Sounds good... but you think that for 200kb request is worth to do that work?

**Comment by wezell** [comment]
Can we hold on this until we talk?
