### ISSUE TITLE
Licenses being lost/not allocated properly in clusters

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#11881]
In a number of instances we have seen cluster instances lose their licenses in shorter times than the heartbeat settings, as well as instances where a license displays as assigned to a cluster node on the license page but in the listing of cluster licenses it shows as available.  In addition we've seen instances where the server id/license id on a node do not match the server id/license id on the list of cluster licenses.

One example of this happening is here: https://my.dotcms.com/tickets/detail.dot?id=2952d003-6fc6-4ccd-b684-9d2b6b8d5854

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/495
PR Core: https://github.com/dotCMS/core/pull/12268
