### ISSUE TITLE
Hazelcast client mode scaling breaking network status

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11889]
2 issues here

1. The status is red in client mode
2. When setting up the following config we get this NPE 
https://gist.github.com/vianneychacon/53a1433313dcf75eee977e0178d02b35
CONFIG is for https://github.com/hazelcast/hazelcast-tomcat-sessionmanager
https://gist.github.com/vianneychacon/c9fb3ea1960c5eed76fe4267e6f647fd#file-server-xml-L35
https://gist.github.com/vianneychacon/c9fb3ea1960c5eed76fe4267e6f647fd#file-server-xml-L126

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11910
