### ISSUE TITLE
Allow same email address to be associated with multiple dotCMS accounts when authentication type is set to UserID

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#11895]
When using external authentication methods (like LDAP and SAML), it's not rare to find multiple accounts associated to the same email account. This represents a problem for dotCMS, for even when the authentication is being done with the userID, the email addresses associated to dotCMS accounts need to be unique.

## Expected Behavior
When authentication type is set to be done by UserID, dotCMS should allow an email address to be used in multiple accounts.

## Current Behavior
Even when authentication is set to be done by UserID, dotCMS returns a duplicated email address message when trying to create a new account with an email address that is already associated to another account.

## Your Environment
* dotCMS version used: 3.7.1

**Comment by wezell** [comment]
can't you just create a unique one for each user?

fake-{uuid}@dotcms.com

**Comment by jdotcms** [comment]
@wezell it is the idea, you can include something like

{prefix}NameId{postfix)

NameId will be the unique user id from SAML
prefix could be fake-
and postfix could be @dotcms.com (by default is @noemail.com)

Thanks,
J
