### ISSUE TITLE
Add REST Endpoint for looking up backend language variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11901]
We need the ability to look up language variables via rest.  This commit allows you to do a REST lookup against system language variables:

`/api/v1/languages/{languageId}/{searchPrefix}`

- This does not require auth

```
curl http://localhost:8080/api/v1/languages/2/com.dotcms.repackage.javax
```

**Comment by dsilvam** [comment]
Integration tests for different search cases (including no filter) would be nice

**Comment by wezell** [comment]
@dsilvam I thought we had this and I finally found it - Geoff did it a while back but it will only pull a "bundle" of messages, which I guess is ok:

```
curl -uadmin@dotcms.com:admin http://localhost:8080/api/v1/system/i18n/en/com.dotcms.repackage.javax.portlet.title
```

**Comment by wezell** [comment]
@fmontes @freddyucv please take note of the above.
