### ISSUE TITLE
Setting COOKIES_HTTP_ONLY=true does not apply to all cookies

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#11912]
When setting the COOKIES_HTTP_ONLY=true in dotmarketing-config.properties it only sets JSESSIONID cookie to HttpOnly, not the dmid, opvc or sitevisitscookie.

* dotCMS version used: 4.1

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=53d0cdda-a7f1-407e-b920-34bbf736df26

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12290

**Comment by shaydotcms** [comment]
Passed QA. 
Running curl command successfully verified that when COOKIES_HTTP_ONLY=true in dotmarketing-config.properties, JSESSIONID, dmid, opvc and sitevisitscookie are showing HttpOnly enabled. 

Tested locally on master branch.
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by oarrietadotcms** [comment]
commit with the hotfix: https://github.com/dotCMS/support/commit/fdc39381475eb8af1d0294f8b4ee9a31b5284a9c

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12400
Test via Curl:
```
erickgonzalez@~/Documents/master/tomcat8$ curl --HEAD http://localhost:8080/
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=5FE1A0B33206481E17CC78B38CBD6054; Path=/; HttpOnly
Set-Cookie: opvc=120e3725-a982-4287-acff-077abc52323e; Path=/; HttpOnly
Set-Cookie: sitevisitscookie=1; Expires=Thu, 07-Jul-2022 22:09:33 GMT; Path=/; HttpOnly
Set-Cookie: dmid=d0f86537-d22f-44f2-bb8d-ba7db41019b7; Expires=Thu, 07-Jul-2022 22:09:33 GMT; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 22 Aug 2017 22:09:34 GMT
```

**Comment by shaydotcms** [comment]
Passed QA
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Firefox 47 / Tomcat 8 / Java 8
```
ShayNg@RetMBP14~ $ curl --HEAD http://localhost:8080/index
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=362F9BC76BAB06D58083E09F85C6BD55; Path=/; HttpOnly
Set-Cookie: opvc=840868b4-859b-4200-a04c-ad03bdda1fd9; Path=/; HttpOnly
Set-Cookie: sitevisitscookie=1; Expires=Sun, 10-Jul-2022 14:23:10 GMT; Path=/; HttpOnly
Set-Cookie: dmid=5b31d2cf-3eac-4455-b5fe-a62ef5d095cc; Expires=Sun, 10-Jul-2022 14:23:10 GMT; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 25 Aug 2017 14:23:10 GMT

```
