### ISSUE TITLE
Files: Improvements on BinaryExporterServlet if force_download is present on URI

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11913]
We currently set a specific behavior on our BinaryExporterServlet class so once a file is called sing `force_download=1` as part of its URI, whether the call is made through its resource link or any REST API-based URL. This forces the file to be downloaded and depending on browser settings, a "save as" dialog pops up. 

However, there are a few things that changes on the response once this happens 

<img width="1373" alt="screen shot 2017-06-16 at 7 54 21 am" src="https://user-images.githubusercontent.com/1717110/27230486-a8dda39c-526c-11e7-88f4-7fe0dfbab476.png">

The content type is set to `application/force-download`, which is a hack and not a standard when it comes to handling files to be donwloaded. Nothing the response, except for the Content-Disposition header, might indicate what kind of file we're downloading, but again, this information might not be accurate. 

Additionally, the Content-Length is dropped so the response package can't tell the actual length of the content about to be delivered, affecting the download process. 

This is how a regular response looks if `force_download` is not present.

<img width="1055" alt="screen shot 2017-06-16 at 7 49 01 am" src="https://user-images.githubusercontent.com/1717110/27230588-00379850-526d-11e7-9062-af8a6def6e98.png">

## Expected Behavior
We should get more details about the download on the response headers and avoid using `application/force-download` as HTTP response header.

## Possible Solution
Use `application/octet-stream` instead of `application/force-download`, set the Content-Length if force_download is present on the request Query String.

## Known Workarounds
Remove force_download from the query string and once the file is delivered, right-click and "save as".
 
## Steps to Reproduce (for bugs)

1. Upload a file to any folder. e.g., /test/image-0001.jpg
2. Go to localhost/test/image-0001.jpg and inspect the response headers on browser
3. Go to localhost/test/image-0001.jpg?force_download=1 and inspect the response headers on browser. They are slightly different from the first request.

## Context
Reproduced during some tests requested by customer: 	https://my.dotcms.com/tickets/detail.dot?id=0e975cb1-76d2-4d33-ae3a-7bff9bf5bcd4

## Your Environment

* dotCMS 4.1.1.
* Google Chrome Browser.
* Windows 10, Mac OS Sierra.
* Tomcat 8.0.18.
* Java 8u121.
* Oracle 12C, Postgres 9.3.5.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11932

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres and everything works as expected
