### ISSUE TITLE
License should apply from bundle always

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11927]
Currently dotCMS only applies a license from a bundle if autoscale transport is set to true. In the past meaning previous to 4.1 it was tied to autoscale but this was never the intention. 

Our intention is that a dotCMS server on start will be greedy and always take a license IF it is available in the DB

To test this we need to test the following scenarios. 

1. Make sure in a single dotCMS you can apply a license as normal. 
2. Set up a server with a license bundle applied. Then point a second dotCMS at the same DB and make sure it picks up a free license from the bundle. We should test with autoscale props set to true and also set to false. 
3. Make sure autoscale still works for transport and ES both internal and external setup

**Comment by jtesser** [comment]
PR https://github.com/dotCMS/enterprise-2.x/pull/474

**Comment by agomez-dotcms** [comment]
Passed QA. Tested all the scenarios suggested above and confirmed proper functioning.
