### ISSUE TITLE
Create new KeyValue BaseType

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11921]
Will come with 2 fields:

- key (text)
- value (long text)

**Comment by jdotcms** [comment]
Done, KeyValue and DefaultKeyValue have been added

**Comment by jgambarios** [comment]
PR: PR: https://github.com/dotCMS/core/pull/12082

**Comment by bryanboza** [comment]
Fixed, now we have the base content as expected.  Some new improvements reported in new cards like: #12168 , #12155. Also we need add a default structure in the new starter
