### ISSUE TITLE
File Asset shows via Query Tool but not in Site Browser or Content Search

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#11943]
We have an issue on our authoring server with a image file asset which is referenced by the documentation.  There are 2 basic issues:

* The file asset appears when you search for it in the Query Tool (and you can click through to the content editing screen and edit it), but can't be found via the Content Search screen or Site Browser. 
* Even though this file asset was pushed to production, trying to access the image by identifier returns a 404.  (Accessing the same image with the same URL on auth displays the image properly).

## Expected Behavior

1. An image that is findable (and then editable) via the Query Tool should be visible in Content Search and Site Browser.
2. Pushing the file asset to production should make the images visible on production.

## Current Behavior

There is an image file asset on authoring with the following field values:
* Title: Example Image for Documentation
* File Name: The-Gherkin-London-England.jpg
* Identifier: f0b0a192-3337-4c18-b8e4-dbad8c802046
* Folder: Should be in /documentation/images (that is the original location, and the content editing screen of the file asset shows the folder as "images"; the content editing screen doesn't provide a way to verify that the full path matches the original path, but I'm assuming for the moment that it hasn't been moved from the original path).

If you open the Query Tool and enter the query `+identifier:f0b0*`, this file asset is displayed in the results, and you can click through to it (opening the content editing screen).  On the content editing screen, you can take all normal actions for a published file asset, including lock, save, publish, and push.  But the file asset can't be found in Content Search or the Site Browser.

## Known Workarounds

Recreate the image file asset and change all links to point to the new one instead.

## Steps to Reproduce (for bugs)

1. Login to authoring.
2. Open the Query Tool.
3. Type in the query `+identifier:f0b0*` and press `Submit`.
    * Result: There is a single result, "Example Image for Documentation".
4. Click on the result link to open the content editing screen and view the file asset.
5. Open the Content Search screen.
6. Set `Type` to `File Asset`.
7. Type part of the Title or File Name into the appropriate search fields.
    * Result: The file asset does not appear in the list.
    * Note: I also manually looked through every page on the content screen (without entering a search term) just to make sure this wasn't a problem with the search feature - the file does not appear anywhere in the file asset listing.
8. Open the Site Browser and attempt to browse to the file asset.
    * Result: The file asset does not appear in the site browser.

## Context

Things tried:
* Save, Save and Publish, and Save Publish and Push of the file asset.
* Full reindex of auth.

Right now, the only way we know of to solve this problem is to recreate the file asset and reference the new one.  But since this image used to work fine (it used to display in the Site Browser and etc., and used to display properly on prod), we need to understand what is causing the problem to make sure customers won't see the same issue.

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Chrome 58.0.3029.110
* Operating System and version: Win7
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8 (auth/prod)
* Database and version: postgres (auth/prod)

**Comment by dsilvam** [comment]
@john-thomas-dotcms I gave it a try to find the piece of content and I was able to do it by changing the "host or folder" field in the Content Search to "old.dotcms.com"
