### ISSUE TITLE
Saving Binary files of same name to different fields breaks upload

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11950]
Easy to reproduce on latest dotCMS 4.1.1 version  (reproduced local and on demo.dotcms.com)

Steps to reproduce:
1) Add two required binary fields to the Generic Content Type
2) Add a new piece of Generic Content and add the same image for both binary fields and Save/Publish
3) Bug: Re-open the piece of Generic Content.  The second field has no image attached to it.  Saving the same file to multiple Binary fields is unsuccessful on the first try with a new piece of content.

**Comment by DeanGonzalez** [comment]
When testing, it might be a good idea to upload the same file to two different language versions of the same piece of content, with the same file uploads to both fields on both language versions.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11975

**Comment by DeanGonzalez** [comment]
Really great fix. Never seen upload work so quickly or so reliably... very responsive... tested multilingual... no need to wait... just keep clicking and uploading... even files close to a gig in size... really nice fix.

**Comment by agomez-dotcms** [comment]
A hotfix for this issue may also be found at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-11950_v3.7.1. Also, a Support ticket might be related at https://my.dotcms.com/tickets/detail.dot?id=53760016-0200-4bd6-af82-d04dbf997066.
