### ISSUE TITLE
VelVarName is not consistent on Content Types

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#11957]
In UI, depending on what you set as Content Type name, VelVarName could contain uppercase letters, lowercase letters or a mix of both. However, VelVarName should be consistent independently of which the Content Type name be.

## Expected Behavior
VelVarName should be consistent independently of which the Content Type name be.

## Current Behavior
In UI, depending on what you set as Content Type name, VelVarName could contain uppercase letters, lowercase letters or a mix of both.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Types and create a new Content Type (use whatever content type you want, in this case I used Content)
3. Create some Content Types using uppercase, lowercase and a few words as the name. i.e.: 
a) all lowercase: "abcd content type"
b) first letter uppercase: "Abcd content type"
c) first letter of each word uppercase: "Abcd Content Type" 
d) all words together and using some letters in uppercase: "ABCDcontenttype"

![image](https://user-images.githubusercontent.com/8741846/27391153-6570a6f2-5660-11e7-99d5-cc58451ada67.png)

4. Check the Content Types list and you will see the Variable name is not consistent

## Your Environment
* dotCMS version used: master branch / commit 57f2b72b0ef988db5ae8bc877db0c448df17149d
* Database and version: Postgres 9.3.7
* Operating System and version: Ubuntu 14.04.1
* Browser Name and version: Firefox v45.0.1 
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by joseorsini** [comment]
please ignore last commit. typo on the message sent with the commit
