### ISSUE TITLE
JWT API Tokens

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11969]
Currently we have a challenge - our JWT tokens are really User tokens and are tied directly to users, which is ok.  The issue is when you try to use them as API tokens - this causes a number of challenges. 

1. we do not have any view into what JWT tokens we have issued for a given user, 
2. We do not have any way to invalidate a particular token without invalidating them all. In dotCMS, if you create an API USER and then request multiple tokens for that user to be used by different clients, the only way to invalidate one particular token is to update the API USER, which updates the user mod_date, which instantly invalidates all tokens for that particular user.
3. Editing any property on the user invalidates all tokens for that user
4. All token use forces a new login session to be created - a token that is used to call an API should not force a session to be created.

We need to provide another level of separation from a token and a user that will allow us to

- Report on tokens that have been issued to a user
- revoke a token on a token by token basis
- Limit the ip scope in which a token can be used
- capture security info on the issuance of the token
- Issue tokens from the UI

All JWT validation needs to be cached and in doing this, we need to make sure that a JWT authentication does not call the database for every request.

## Create a `api_tokens_issued` DB table
create a new db table that allows us to store metadata around the issuance of a JWT (NOT THE TOKEN ITSELF)  that are issued for longer than a session.  The table could look something like:

`tokens_issued`

- `    token_id varchar(255)`  - a random UUID
- `    token_userid varchar(255)` - the userId that the token maps to
- `    issue_date  timestamp`
- `    expire_date timestamp`
- `    requested_by_userId varchar(255)` - the userId who requested the token
- `    requested_from varchar(255)` - store the ip address of who the request cam from
- `    revoke_date timestamp`  - the date a token has been revoked
- `    revoked_by_userId varchar(255)` - who revoked the token
- `    allowed_from	varchar(255)`  - the networkAddr for who can use this token
- `    cluster_id varchar(255)`  - the clusterId of the installation- 
- `    metaData bigtext` - a field that we can use to store meta/json without updating the model
- `    mod_date timestamp` - last mod date for the record

## Issuing a new Token
When issuing a new token that is not session based, we write an entry into the `tokens_issued` table with a random UUID as the `token_id`.   We add this `token_id` as the JWT `sub` and we remove the `user_id` from the JWT.  We will also add the `clusterId` to the token.  Additionally, we need to remove the `updated_at`property from our tokens.

### TokenCache
Create a new Cache that implements our Cachable that can cache the JWT tokens by  `token_id`

### Authorization Flow
When presented with a JWT to use as authorization, dotCMS will read the `token_id` out of the JWT and use it to lookup the tokens validity.  Our API needs to
first do a cache lookup by token_id, and if a record is not found in cache, do a db lookup against the `tokens_issued` table.  If nothing is found in the `tokens_issued` table, we need to insert a 404_TOKEN record into the cache to prevent future lookups.

Once we have our `tokens_issued` data for the `token_id`, dotCMS will validate it to see if:
- It has not expired
- It has not been revoked
- The cluster_id matches our cluster (make this configurable)
- The IP matches the allowed_from ip value (ignore if allowed_from value is null)

If all of these are true, we take the user_id from the `tokens_issued` record and return that user as the authenticated user.

## API
- Add an API endpoint that returns a list of all the tokens_issued for userId.  This should only be accessible if the user has access to the user portlet (check portlet permissions)
- Add an API endpoint that can revoke/invalidate an api token
- Add an API endpoint to create api tokens
- Add an API endpoint to create JWTs from an api token

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16229

**Comment by jgambarios** [comment]
**Note to QA:** As part of the Internal QA process we need to test this functionality and the upgrade tasks in all 4 databases, also we need to verify if extra integration tests could be or are required to be add.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16239

**Comment by jdotcms** [comment]
Code review and unit test done: has ran related unit tests to make sure is running ok. Minor changes has been made.

**Comment by jdotcms** [comment]
Remember me has been tested, by removing the session cookies except the access_token, the user was successfully re-login

**Comment by jdotcms** [comment]
We have created a json:

POST http://localhost:8080/api/v1/authentication/api-token
```{
	"user":"admin@dotcms.com",
	"password":"admin",
	"label":"test"
}```

Output
```
200
{
    "errors": [],
    "entity": {
        "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGk3ODM1ODlhMC0wYzY1LTRlOTctYjQ1Zi1lYzEzMTNkZWI5NzAiLCJ4bW9kIjoxNTU0NzQxMzQ5MDAwLCJuYmYiOjE1NTQ3NDEzNDksImlzcyI6IjVmZWVlYWM3LWM4MmYtNDYyZi1hZDFiLWMxZDU2NWUxOTdmZSIsImxhYmVsIjoidGVzdCIsImV4cCI6MTU1NTk1MDk0OSwiaWF0IjoxNTU0NzQxMzQ5LCJqdGkiOiI1ODI4ZTQ5Ny03ZjgwLTQyNTEtOWZjZC0wNzYxM2Y1YmNlZDYifQ.QXSLKEZXkW4jjLPSPgSZnHmbTsWRh9v5P2R-_YUHJJo"
    },
    "messages": [],
    "i18nMessagesMap": {},
    "permissions": []
}
```

```

  "sub": "api783589a0-0c65-4e97-b45f-ec1313deb970",
  "xmod": 1554741349000,
  "nbf": 1554741349,
  "iss": "5feeeac7-c82f-462f-ad1b-c1d565e197fe",
  "label": "test",
  "exp": 1555950949,
  "iat": 1554741349,
  "jti": "5828e497-7f80-4251-9fcd-07613f5bced6"
```

**Comment by jdotcms** [comment]
Note:
Apitokens are for use in headers, e.g. Authorization: Bearer
User tokens are for the cookies

That said, if an user is modified the autologin won't work (b/c it is a validation for it). However the api token does not matter that validation.

**Comment by jdotcms** [comment]
When creating an jwt,
if expirationSeconds is not sent or less than 0, returns 400
if the user does not exists, returns 404 (note: the user only by userid)

**Comment by jdotcms** [comment]
I have created a new user, then I have done as an admin user a token for the new user such as
```
POST http://localhost:8080/api/v1/apitoken
{
	"userId":"user-58a9d126-bbbb-432f-a583-856a251e706c",
	"expirationSeconds":600
}
```

Then I have used the token and worked

**Comment by jdotcms** [comment]
After 5 minutes the token is expired and not longer worked the access.

**Comment by jdotcms** [comment]
If the user associated to the token is inactivated, the login not longer work

**Comment by jdotcms** [comment]
After calling the
PUT http://localhost:8080/api/v1/apitoken/api11039fb3-ef38-45e1-82e7-943575858f89/revoke
the JWT not longer work

**Comment by jdotcms** [comment]
The remove was successfully deleted

**Comment by jdotcms** [comment]
Have created a token on the users portlet, do an api request with it, then revoked, then do the same api request: the token not longer work

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16348

**Comment by wezell** [comment]
# Token Doc




## Set an API token as an env var
export TOK=`curl -H "Content-Type:application/json" -s  -X POST -d  '{ "user":"admin@dotcms.com", "password":"admin", "expirationDays": 1000 }' http://localhost:8080/api/v1/authentication/api-token | python -c 'import json,sys;print json.load(sys.stdin)["entity"]["token"]'`



## Get all non revoked tokens
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XGET  http://localhost:8080/api/v1/apitoken/dotcms.org.1/tokens | python -m json.tool

## Get all tokens
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XGET  http://localhost:8080/api/v1/apitoken/dotcms.org.1/tokens?showRevoked=true | python -m json.tool


## Revoke a token
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPUT  http://localhost:8080/api/v1/apitoken/api9dccf2f4-9eb6-4e63-8cf1-7b818844d947/revoke 


## Delete a token
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XDELETE http://localhost:8080/api/v1/apitoken/api3e504d68-ce39-4df8-875d-3a0c370dfe3b


## Generate a new API Token Request AS admin@dotcms.com FOR joe@dotcms.com
curl -s -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST http://localhost:8080/api/v1/apitoken -d'{
    "userId":"dotcms.org.2789",
    "network":"192.168.1.0/24",
    "expirationSeconds":600
}' | python -m json.tool

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle... Tested with each one of the commands and it is working as expected
