### ISSUE TITLE
Need update the license request image in the network tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11965]
We need update this image because have some UI problems 

<img width="1440" alt="img2" src="https://user-images.githubusercontent.com/2641437/27408614-ca75536a-569a-11e7-8303-7568f2b7c16c.png">

## Your Environment
Tested on maste-4.1 //

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12005

**Comment by bryanboza** [comment]
Fixed, now looks better, tested in the last master  // chrome
