### ISSUE TITLE
Add license information to the configuration endpoint

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11966]
Add license information to the configuration endpoint

## Expected Behavior
Add the license information on the configuration resource

/api/v1/configuration

**Comment by jdotcms** [comment]
for http://localhost:8080/api/v1/configuration

Will got:

{
  "errors": [],
  "entity": {
    "dotcms.websocket.disable": false,
    "dotcms.paginator.rows": 10,
    "license": {
      "displayServerId": "077cf077",
      "levelName": "COMMUNITY EDITION",
      "isCommunity": true
    },
    "dotcms.paginator.links": 5,
    "releaseInfo": {
      "buildDate": "June 13, 2017",
      "version": "4.2.0"
    },
    "dotcms.websocket.baseurl": "localhost:8080",
    "dotcms.websocket.protocol": "ws",
    "dotcms.websocket.endpoints": {
      "websocket.systemevents.endpoint": "/api/ws/v1/system/events"
    },
    "EDIT_CONTENT_STRUCTURES_PER_COLUMN": 15,
    "dotcms.websocket.reconnect.time": 1000,
    "i18nMessagesMap": {
      "relativeTime": {
        "mm": "%d minutos",
        "hh": "%d horas",
        "dd": "%d días",
        "MM": "%d meses",
        "yy": "%d años",
        "d": "un día,",
        "past": "hace %s",
        "h": "una hora",
        "m": "un minuto",
        "M": "un mes",
        "s": "segundos",
        "future": "en %s",
        "y": "un año"
      },
      "notifications_dismissall": "Descartar todo",
      "notifications_dismiss": "Descartar",
      "notifications_title": "Notificaciones"
    }
  },
  "messages": [],
  "i18nMessagesMap": {}
}

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11967

**Comment by bryanboza** [comment]
Fixed, after the last change, now we have all this info in  the rest... Tested in the last master // Postgres
