### ISSUE TITLE
Parent Roles are Passing Permissions to Child Roles

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11962]
Reproduced in 3.7, 4.1.1, and master

Bug: Parent role is passing folder permissions to a child role.

Parent roles should never pass permissions down to a child role.  Child role pass permissions UP to parent roles.  Reverse role inheritance is the rule on nested roles.

To reproduce:

1) Create a parent role called Webmaster with key and "can grant" on all
2) Create a CHILD role of Webmaster called Product Publisher with key and "can grant" on all
3) Create a CHILD role of Product Publisher called Product Contributor with key and "can grant" on all
4) From the Product Contributor role, permission the role to view and add children on demo.dotcm.com and give access to view and add/edit child objects on the "Go Quest" directory
5) Edit the Product Publisher role and give the role full publish permissions to the applications directory.
6) Go back to the Product Contributor role and look at the role permissions.  This role now has acces to the applications directory - that is the bug.  Permissioning a parent role should never pass ANYTHING down to a child-nested role

Screencast: https://screencast.com/t/YKC1NlLqPP

**Comment by oarrietadotcms** [comment]
FYI, roles have a "Reverse" Permission Inheritance 

> When Roles are set up in a hierarchy, all permissions granted to a “child” Role are inherited (upward) by the “parent” Role, so the parent Role automatically receives all permissions granted to the child Role. If a parent Role has multiple child Roles (or grand-child Roles), the parent Role receives all the permissions of all its descendant Roles.

> Role inheritance allows you to create a logical hierarchy of roles where users with greater rights (such as administrators or managers) automatically have all the permissions of any Roles lower in the hierarchy, without you having to explicitly assign the same rights to the parent Roles. For example, you might create a top-level “Manager” role, a second-level (child) “Supervisor” Role, and a third-level (grand-child) “Employee” Role. In this example, Supervisors would always have all the rights assigned to Employees plus any additional rights appropriate for Supervisors; and Managers would always have all the rights assigned to both Supervisors and Employees plus any additional rights assigned to Managers. You can thus easily create Role hierarchies which mirror real-world operational or organizational hierarchies, without having to duplicate permissions assignments for multiple different Roles.

https://dotcms.com/docs/latest/role-permissions#Inheritance

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12030

**Comment by oarrietadotcms** [comment]
PR to fix failing integration test: https://github.com/dotCMS/core/pull/12054

https://cb.dotcms.com/view/builds%20-%20continuous/job/Build_Continuous_Tester_Func_Int_master/71/

**Comment by DeanGonzalez** [comment]
Both Parent and Child Roles seem to be applied and functioning normally now - good fix
