### ISSUE TITLE
Unable to set expire date on content types

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11978]
We are having problem when you try to use date/time fields to  expire contents in content type 

This when you just have one of those to expire (not publish)

## Expected Behavior
We should be able to set the publish and expire values individually  and save the piece of content to automatically publish/expire the content 

## Current Behavior
After you set that values and save, the system set the expire date to never expire, and isn't saving the value 

## Steps to Reproduce (for bugs)
1. Login as admin
2.  Create a new content type with a date/time fields, and set this values to expire in the content type properties
3. Create a new page into that content type 
4. Set the "expire" value and save and publish 
5. Try to edit the page, make sure you have the same values in the field 

![img4](https://user-images.githubusercontent.com/2641437/27458215-2be7a858-5765-11e7-9a29-125a1b85dccf.png)

SC: https://screencast.com/t/xASA6WxdAi

## Your Environment
Tested on master // Postgres // Chrome

**Comment by bryanboza** [comment]
FYI: Seems this is an old issue, because I am able to reproduce on 3.7

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/11994

**Comment by bryanboza** [comment]
After test this, seems we have the same behavior at the UI level in the 3.x versions, just works in 2.x https://screencast.com/t/XshLGO9uT

**Comment by bryanboza** [comment]
Fixed, now we are able to see the date when you are editing the content... Tested on master// postgres // Chrome
