### ISSUE TITLE
Make sure the system properties has been read before the MainServlet

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11974]
Make sure the system properties has been read before the MainServlet

## Expected Behavior

The system properties from system.properties must be read before the MainServlet

## Current Behavior
There are some weird case where it is not, and it is just depending in a call from CollectionFactory in my case

## Possible Solution
Call the SystemProperties before the init MainServlet

## Known Workarounds
Edit the hibernate.properties, the issue is related with hibernate that is not getting the new configuration

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11976

**Comment by bryanboza** [comment]
Tested in the specific environment, just mark as passed QA
