### ISSUE TITLE
Binary Formatting displaying as optional on Binary Fields

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11982]
Seen on master and 4.1.1

Binary fields need to be saved as Data Type=binary.  This is not optional.  In 3.x versions we had the Data Type Binary shown, but it was selected by default and could not be de-selected... which is proper behavior.

![binary37](https://user-images.githubusercontent.com/1569167/27492387-4a393e90-5803-11e7-97b3-a46730382df3.jpg)

In 4.x however, we mistakenly display the formatting as de-selected, as if the formatting was optional.

![binaryformat](https://user-images.githubusercontent.com/1569167/27492492-a06bf99c-5803-11e7-9e84-c8da8998662a.jpg)

We should change the radio button back to being selected and unchangeable.

**Comment by wezell** [comment]
as we are redeveloping the content type screen, this is a dying problem.  Also, if you save with it not selected, it will still get the binary data type
