### ISSUE TITLE
Single Click "Add New Content" from "Content -> Search" Portlet

### ISSUE THREAD

**Issue by nkeiter** [dotCMS/core#11986]
You should be able to "Add New Content", "Import Content", and "Export" in a single click from the "Content -> Search" portlet.

## Expected Behavior
Each operation should be done with a single click.

## Current Behavior
It currently takes at least two clicks to perform any of these operations.  That might not sound like much, but when you are adding 20 or 30 contentlets in a row it adds up and starts getting annoying.

## Possible Solution
I think everyone would be better served if this was displayed as three horizontally aligned buttons rather than a drop-down menu. Then adding new content could be done in a single click.

## Known Workarounds
None, keep clicking.

## Steps to Reproduce (for bugs)
1. Navigate to "Content -> Search" portlet.
2. Try to "Add New Content".
3. Add several pieces of new content in a row.
4. Count how many clicks it takes to get to your desired page.

## Context
Adding multiple contentlets in a row.

## Your Environment
* dotCMS version used: 4.0.1
* Browser Name and version: Chrome Version 56.0.2924.87 (64-bit)
* Operating System and version: Mac OS X El Capitan 10.11.6
* Application Server and version: Windows Server 2008 R2 Standard Service Pack 1
* Java Brand and version: Oracle, 1.8.0_121
* Database and version: Oracle, 11g
* Application module (if apply): Backend Content Search Portlet

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=2847c1e4-8b1a-468c-868f-1e2815af4f7e
