### ISSUE TITLE
Hazelcast client mode breaks if the hazelcast hiccups

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11998]
If a connected to external hazelcast the client gets blocks. This happens if connected to a cluster and the second node goes down OR connected to a single hazel and it goes away for whatever reason.  

One return of hazel the dotCMS doesn't recover

**Comment by jtesser** [comment]
Hazel has a feature request in on this one https://github.com/hazelcast/hazelcast/issues/9692

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12022

**Comment by jtesser** [comment]
So the test case here is Run an external Hazelcast meaning dotCMS in client mode and kill the external hazel.  Ensure when you start again the cache is working and when the cache is down threads are not blocked meaning page hits. Might be slow cause hitting the DB 

Can do a config setup like this to test in dotmarketing-config
-cache.default.chain                    =com.dotmarketing.business.cache.provider.caffine.CaffineCache
-cache.contentletcache.chain =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
-cache.velocitycache.chain   =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
+#cache.default.chain                   =com.dotmarketing.business.cache.provider.caffine.CaffineCache
+#cache.contentletcache.chain =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
+#cache.velocitycache.chain   =com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotmarketing.business.cache.provider.h22.H22Cache
 #cache.default.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderEmbedded
-#cache.default.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient
+cache.default.chain=com.dotmarketing.business.cache.provider.hazelcast.HazelcastCacheProviderClient

-CACHE_INVALIDATION_TRANSPORT_CLASS=com.dotcms.cache.transport.HazelcastCacheTransportEmbedded
+CACHE_INVALIDATION_TRANSPORT_CLASS=com.dotmarketing.business.jgroups.NullTransport

**Comment by shaydotcms** [comment]
Passed QA.

Tested using Hazelcast as client with cluster and using single dotcms instance. When shutting down Hazelcast client I was still able to navigate thru the page, which is good.
When Hazelcast is down, Refresh Stats doesn't show Hazelcast cache data, however when Hazelcast is back, Refresh Stats does show Hazelcast cache data, which is good.

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit 46d9818107ca6938e4b0fa30364d707ac1ddb423
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
