### ISSUE TITLE
Save Custom Tool Group will redirect to admin homepage

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#12006]
## Expected Behavior
When you save a Custom Tool Group you should be redirected to the Tool Group overview page for that role. (Location: Roles & Tools page -> Tools tab)

## Current Behavior
When you Click on save Custom Tool Group you will be redirected to the admin homepage, this doesn't make sense as I didn't finish the role configuration yet.

## Steps to Reproduce (for bugs)
1. Go to Roles & Tools page
2. Click on a role
3. Go to Tools tab
4. Click on Create Custom Tool Group
5. Click on Save

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Firefox
* Operating System and version: Windows 10.1
* Java Brand and version: Java 8

**Comment by DannyGloudemans** [comment]
The same is when you add an existing tool group to a existing role, very annoying.

**Comment by john-thomas-dotcms** [comment]
+1 on this - disorienting to redirect to the Tasks screen when you save a custom tool group.
