### ISSUE TITLE
Condition isn't working in the tuckey OSGI plugin 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12002]
We are having problems testing the condition when you are using the tuckey plugin... 

## Expected Behavior
If you call this url from google chrome, we should display the message "from google Chrome" if not, will do nothing (404 error).

## Current Behavior
If you call this url from chrome we still displaying the 404 error and we are unable to resolve the condition 

## Steps to Reproduce (for bugs)
1. Download the plugin-seeds-master folder from github
2. Compile the **com.dotcms.tuckey** plugin (./gradlew jar)
3. Upload the generated lib in to the plugins portlet
4. Try to resolve this url from google **http://localhost:8080/example/condition**

**FYI: All the other URL works as expected** 

## Your Environment
Tested in the last master // postgres

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/plugin-seeds/pull/9

**Comment by erickgonzalez** [comment]
With the refactor of the plugin now it redirects to "about us" page when it comes from Google Chrome, and "404 error" page when from another. Also in the Readme, it was missing a "/" at the end of the URL: http://localhost:8080/example/condition/

**Comment by bryanboza** [comment]
Fixed, tested on master // chrome... Now works as expected
