### ISSUE TITLE
[Feature Request] Bind language ID to host/alias/TLD

### ISSUE THREAD

**Issue by thequicksilver** [dotCMS/core#12008]
## Current Behavior
At the moment, dotCMS prefers to handle language switching on the front end of sites via a URL parameter (usually set by something like a dropdown) absent a third party technology that manipulates the request headers to include language properties or doing something custom in Velocity as pages load.

## Possible Solution
Would love to see some options on hosts and host aliases to define a default language ID to display if the site is requested via a specific hostname/TLD. So we could say site1.com serves language ID `1`, while site1.co.jp would serve language ID `4` without any additional settings or configuration. This should work if hosts are entirely standalone, or if all the sites are served via one host with several aliases.

Alternatively, it could be done the opposite way. When you configure a language, you could specific TLDs it applies to, so you set up language ID `4` as ja_JP, and tell it that language ID should apply by default to hostnames ending in .co.jp. 

Either of these options would resolve a lot of need, I think, and could still be overridden by a specific value passed in the URL.

**Comment by rediris** [comment]
I second this.

**Comment by wezell** [comment]
You can do this type of logic with the rules engine, at least at the host level.  For the more general pattern matching that sets a language, you can use tuckey.

**Comment by cfalzone** [comment]
Will, the issue for us here is that, while this works, it leads to a lot of custom code that makes upgrading dotCMS more involved than we like.  We are looking for a fully-supported, configuration-based solution to this issue.  Allow us to set the language per alias in config and have the CMS Support it completely.  Every Upgrade using tuckey rules breaks things.  Case in point, the upgrade to 3.6 for us completely broke Tuckey Forwards.  This has become a pain point for our organization and we would like to see it fully supported in dotCMS without custom plugin work or the need for a proxy in front of dotCMS.

**Comment by wezell** [comment]
Chris, I hear you regarding tuckey, but we accidently moved the tuckey filter below (Filter Order) the CMSFilter in the 2.x series (which broke redirects) and only in the late 3 series did that problem get rectified.  I am sorry you all got caught up in that.  You can forward now, you just need to use something like this:

https://github.com/dotCMS/plugin-seeds/blob/master/OSGi/com.dotcms.tuckey/src/main/java/com/dotcms/tuckey/Activator.java#L59-L65

I don't see our moving tuckey again anytime soon, so I would def suggest that route for pattern matching or rules for more specific behaviors.
