### ISSUE TITLE
Create get content related endpoint on the ContentResource

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#12009]
Create get content related endpoint on the ContentResource

## Expected Behavior
Provide an endpoint to get related content.

## Current Behavior
Does not exists

It would work something like this:

http://localhost:8080/api/content/related/relation/LandingPage-Products/id/7b22b477-b444-4d4b-b2e4-14ac4f9378e9/parents/true/limit/10

and will return the contents related.

**Comment by wezell** [comment]
You can get this using the ContentResource and a query.

**Comment by jdotcms** [comment]
yeah, the team decided to do something more high level such as the toolview does.
Let us know if that approach is ok for the Biz.

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=2c3560f8-094d-4fbe-9724-0a3c6face114

**Comment by gabbydotCMS** [comment]
PR: #12021

**Comment by jgambarios** [comment]
@wezell based on your comment https://github.com/dotCMS/core/issues/12009#issuecomment-311749928 and the pull request https://github.com/dotCMS/core/pull/12021 do you think this is something we want into de master?
