### ISSUE TITLE
On edit multiselect field, if the double Quotes the value is wrong

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#12015]
On edit multiselect field, if value has double quotes the value stored in the system is cut and breaking the logic to select it consequently.

## Expected Behavior
The form should remember the option selected in a multi field, even if the value has "

## Current Behavior
The value is cut and storing wrong things, not selected is highlighted

## Possible Solution
Escape in a javascript var the value.

## Known Workarounds
Use a diff quotes, not "

## Steps to Reproduce (for bugs)
https://my.dotcms.com/tickets/detail.dot?id=2cf42209-f287-4b8c-b223-f468207f6d2e

**Comment by gabbydotCMS** [comment]
PR #12020

**Comment by bryanboza** [comment]
We still having problems with this field this because when you add a new piece of content and then try to edit, we lost the selected value in the field 
SC: https://screencast.com/t/hnnMeAg1Ln

**Comment by dsilvam** [comment]
New PR: https://github.com/dotCMS/core/pull/12360
