### ISSUE TITLE
Autocomplete not working with Login As feature

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12024]
Tested on master

Autocomplete when typing the name of an existing user is not working when searcing for users via the Login As feature.

Not finding "Joe Contributor" as a backend user in the image below:

![loginas](https://user-images.githubusercontent.com/1569167/27697130-a3adac20-5cb0-11e7-99f8-433feb2a9d62.jpg)

**Comment by dsilvam** [comment]
@john-thomas-dotcms @DeanGonzalez. 
We have a new version of UserResource REST API. This https://dotcms.com/docs/latest/rest-api-end-points#UserResource needs to be updated. 

Also, as part of this ticket, method com.dotcms.rest.api.v1.user.UserResource#loginAsData was deprecated in favor of com.dotcms.rest.api.v2.user.UserResource#loginAsData

**Comment by DeanGonzalez** [comment]
I will doc this one and paste the link.

**Comment by john-thomas-dotcms** [comment]
So just to be clear, the v1 version of the API is still supported for now, but deprecated (e.g. may be removed in a later release), correct?

**Comment by dsilvam** [comment]
@john-thomas-dotcms Three things here:
1. UserResource currently documented in code (no version) is fully deprecated (at class level). 
2. UserResource under v1 package, has only one method deprecated (loginAsData). The rest of the methods are current and they are the recommended version to use. 
3. UserResource under v2 package **only** has the new version of the method mentioned above (loginAsData)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12198

**Comment by fmontes** [comment]
Pagination it's not working.

**Comment by bryanboza** [comment]
Also we have this problems: https://screencast.com/t/ZGHiEp4AIh

**Comment by bryanboza** [comment]
As in the last comment, we stil, having problems in  this feature: 
https://screencast.com/t/DyIGWBnqj2de
https://screencast.com/t/vkoab2Xd1CI

**Comment by bryanboza** [comment]
Now we have a new component to this feature....
