### ISSUE TITLE
Vertical scroll bar doesn't display in content edit screen, cut off in file edit screen

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#12034]
In the content editing screen, there is no vertical scroll bar displayed, even though the fields don't all fit on the screen.  In the file edit screen, the scroll bars on the file editing control are cut off.  Both appear to be due to a styling issue with the () file.

## Expected Behavior

The scroll bars should be fully visible in all edit windows, on all platforms and browsers.

## Current Behavior

The following screen shot shows how the content editing screen displays in my browser:

![image](https://user-images.githubusercontent.com/13456955/27702342-94d0f722-5cb8-11e7-904a-85aa4c3dfea2.png)

The following screen shot shows how the file editing screen displays:

![image](https://user-images.githubusercontent.com/13456955/27702358-aa404e00-5cb8-11e7-96d8-12b2b6f58621.png)

Note, however, that for some files the file editing field isn't fully cut off:

![image](https://user-images.githubusercontent.com/13456955/27702404-d053ff7e-5cb8-11e7-9345-0b99c9feccc4.png)

## Possible Solution

We identified this issue before the 4.0 release, and I believe it was supposed to be fixed, but it appears the fix didn't make it into the release.  At the time, Will suggested I make a change to the dotcms.css file to increase the spacing on the right side, which solved the problem for me then (though a hard-coded change to the spacing might not be the best or most appropriate change to make things display well for all platforms and browsers).

## Known Workarounds

1. Manually edit the dotcms.css file to increase the spacing.
2. Click on the page or control and use the page up/page down/arrow keys to scroll.

#### Content editing screen:

1. Log into the demo site.
2. Open the Content Search screen.
3. Click on any "Content (Generic)" content item (e.g. "About Quest").

#### File editing screen:

1. Log into the demo site.
2. Open the Site Browser.
3. Navigate to the folder /application/vtl/widgets/location.
4. Open the properties for the "location-listing.vtl" file.

## Context

This is just an annoyance, but doesn't look good.

## Your Environment

* dotCMS version used: 4.0.0 - 4.1.1
* Browser Name and version: Chrome (Multiple versions of 58 through Version 59.0.3071.86)
* Operating System and version: Win 7 Enterprise
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8 (local and on demo)
* Database and version: H2 (local) and postgres (local and demo)

**Comment by john-thomas-dotcms** [comment]
OK, so I just found out this is a little worse than I thought.  If the action side bar is too long to fit on the page vertically, then there's no way to scroll down to the items below the page break.  Here's an example, on demo:

![image](https://user-images.githubusercontent.com/13456955/27743265-3c9f0ba8-5d70-11e7-8598-6bc2a4225be6.png)

**Comment by john-thomas-dotcms** [comment]
This is still an issue.  It doesn't look good (and it's annoying :smile: ).  And I'm guessing it's not alot of work to fix.  Can we please consider this for the next release?

**Comment by joseorsini** [comment]
This also affects how browsers handle PDF exports of pages. For example, this test page is generated from an Event in demo.dotcms.com site

[test.pdf](https://github.com/dotCMS/core/files/1549568/test.pdf)

And as you can see, the output is truncated.
