### ISSUE TITLE
DeployWarTomcat not using artifactory jars when compiling

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12031]
The **DeployWarTomcat** is compiling using the submodules code when they are present.

## Expected Behavior
We should compile using the **ee** and **license** jar living in artifactory and use the submodules code only when running the **DeployWarTomcatDev** task.

## Current Behavior
We are compiling using the source of the submodules and not using the **ee** and **license** jars

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12032

**Comment by bryanboza** [comment]
Fixed, after test the deployWarTomcat still working normally....
