### ISSUE TITLE
Create endpoint to get sites by id

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12035]
### Acceptance Criteria

1. Create the endpoint ```/sites-urls/id/{id}```
2. After this update the method: ```getSiteyBId``` in the ```SiteService``` of core-web to use this endpoint.
3. Work in all the supported browsers (don't forget IE11)
4. Multilanguage
5. Unit test (also in core-web)

**Comment by wezell** [comment]
Wait, don't we have this?

/api/content/id/{id}

**Comment by fmontes** [comment]
Yup @wezell that's right... closing this one. Forgot that site are just content :)
