### ISSUE TITLE
Upgrade to current master fails because of wrong sql

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12047]
Introduced by this task Task04120IncreaseHostColumnOnClusterServerTable

SQL here is missing keyword "TYPE" after column name : https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04120IncreaseHostColumnOnClusterServerTable.java#L43

This is only for postgres.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12048
