### ISSUE TITLE
Images on WYSIWYG are not localized to different languages while on Preview

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#12059]
After reproducing an [issue for a client](https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a), it was discovered that Images on WYSIWYG are not localized to different languages while on Preview. After investigation, this problem -that is not present on latest master branch- needs to be hotfixed for old versions of dotCMS (in our case, 3.7.1). This ticket was only added for hotfix tracking purposes (it will be closed) since problem could not be reproduced on our latest versions.

## Steps to Reproduce (for bugs)
1. Log into Back-End as Administrator user and go to "Site Browser"
2. Add New Folder "test"
3. Under "test" folder, Create New File Asset "Flag.png" and Upload US's "Flag.png", Save and Publish
4. Open "Flag.png" file asset, Change Language to "Español (ES)" and Upload Spain's "Flag.png", Save and Publish
5. Under "test" folder, Create New Page Asset [title: "my-page", template: "demo.dotcms.com Quest - 1 Column"], Save and Publish

6. Open "my-page" page asset, Lock for Editing
7. Add Content (Generic) [title: "UNITED STATES FLAG"] and Insert Image on WYSIWYG field from "/test/Flag.png", Save and Publish
8. Edit Content (Generic), Lock for Editing, Change Language to "Español (ES)" and Insert Image on WYSIWYG field from "/test/Flag.png" [title: "SPAIN FLAG"], Save and Publish

9. Open "my-page" page asset, Preview, Change Language to "Español (ES)" and Look at WRONG Image from WYSIWYG content

## Expected Behavior
SPAIN image should be displayed while previewing WYSIWYG content when having Language changed to "Español (ES)"

## Current Behavior
UNITED STATES image is actually/wrongly displayed while previewing WYSIWYG content when having Language changed to "Español (ES)"

## Screen Shoots
<img width="1440" alt="screen shot 2017-07-05 at 3 19 25 pm" src="https://user-images.githubusercontent.com/22307536/27885464-5f993948-6195-11e7-8109-de14dd326386.png">

<img width="1440" alt="screen shot 2017-07-05 at 3 03 20 pm" src="https://user-images.githubusercontent.com/22307536/27885429-41d9d85e-6195-11e7-9f36-8be33d414c76.png">

## Context
Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a (3.7.1)

## Your Environment
* dotCMS version used: 3.7.1.
* Browser Name and version: FF
* Operating System and version: MacOSX
* Application Server and version: Tomcat
* Database and version: MySQL

## RESOURCES
![flag](https://user-images.githubusercontent.com/22307536/27885540-982b3130-6195-11e7-9e31-006ec7bba7f4.png)
![flag](https://user-images.githubusercontent.com/22307536/27885550-a0b5935e-6195-11e7-8495-068cec1b6d50.png)
![flag](https://user-images.githubusercontent.com/22307536/27885577-afa4248e-6195-11e7-927f-d2e429c35555.png)

**Comment by agomez-dotcms** [comment]
The fix for this issue may be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12059_v3.7.1. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a

**Comment by brentgriffin** [comment]
@wezell believes this https://github.com/dotCMS/core/issues/8229 fixes this issue.

**Comment by wezell** [comment]
@agomez-dotcms I think you can just take the .jsp file to solve the customer issue on 3.7 - the java code does not need to be backported - it is optional if you want to use the whole hostname.

**Comment by agomez-dotcms** [comment]
Hey Guys, as documented on previous comment (above). This client-issue was already solved via hotfix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12059_v3.7.1. Hotfix worked for me and client still is on his way to testing it.

On the other hand, issue could not be reproduced on latest dotCMS version. That's why I left it Closed.
