### ISSUE TITLE
The authentication required action on Vanity URL need redirect to the vanity after login

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12069]
Related to #11627 

As part of the new vanity URLs, now we have some actions to the vanity, but in the case of authentication required, it should be just an intermediate step, we should resolve the forward after login. 

## Expected Behavior
When the system redirect to the login page on FE, after you login we should redirect to the forward url... 

If you already logged in, the system should resolve the vanity without problems 

## Current Behavior
When you use this action, actually we only redirects to the login page on FE, and after this, we lost the action... 

## Steps to Reproduce (for bugs)
1. Add a new structure of type Vanity URL
2. Add a new vanity using the 401 authentication required action
3. Go to FE, and try to hit this vanity 
4. Login and make sure the system continue resolving the vanity 

## Your Environment
Tested on master // Postgres // Chrome

**Comment by jgambarios** [comment]
**Note:** As part of this ticket we want to remove from the **Action** field select the **401**,**403**,**404** and **500** actions.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12358

**Comment by jgambarios** [comment]
**Note to QA:** Now the only allowed status for the Action field are: **200**, **301**, **302**

**Comment by bryanboza** [comment]
Fixed, now we just have the mentioned codes... Tested on the last master
