### ISSUE TITLE
Back End Users logging in with no layouts should not be able to login to console.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#12062]
Reported by customer.  https://my.dotcms.com/tickets/detail.dot?id=fe9c30d2-7ed2-40f3-a5ba-7eb580e81d11

Users logging in with no roles assigned will see the spinning processing graphic but the page will never refresh to the dotAdmin console.  Refreshing the page results in a blank page.

We need to add a `User.hasConsole()` method that returns whether the user has any layouts assigned to them.  We will use this in the authentication process to prevent any user without layouts from logging in to the BACK END

**Rule:** If a user is a backend user validating a USER TOKEN and the `user.hasConsole()== false` e.g. (does not have any layouts), then we will reject the login and will NOT issue a user token.  Login will fail.

We need to do this work in the `JsonWebTokenFactory.validateToken` method.

**Comment by john-thomas-dotcms** [comment]
FWIW, I saw this same behavior after upgrading a 3.7.0 instance to 4.1.0 locally.  I assume I must have done something wrong with the upgrade, but saw the exact same behavior.  The 3.7.0 instance was just a slightly modified starter site, and I was logging in with the default admin@dotcms.com role.

**Comment by wezell** [comment]
Users with no roles should get a failed login in the back end

**Comment by wezell** [comment]
This is fixed in 5.2.0
