### ISSUE TITLE
Images on WYSIWYG are not localized to different languages when Content is Edited

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#12060]
After reproducing [second issue for a client](https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a), it was discovered that Images on WYSIWYG are not localized to different languages while Content is Edited. After investigation, it seems this problem can not be solved without having side-effects at other parts of the system. So, this ticket is left for analysis, documentation and tracking purposes. Further discussion needs to happen to decide the right approach/solution (see section below)

## Steps to Reproduce (for bugs)
1. Log into Back-End as Administrator user and go to "Site Browser"
2. Add New Folder "test"
3. Under "test" folder, Create New File Asset "Flag.png" and Upload US's "Flag.png", Save and Publish
4. Open "Flag.png" file asset, Change Language to "Español (ES)" and Upload Spain's "Flag.png", Save and Publish
5. Under "test" folder, Create New Page Asset [title: "my-page", template: "demo.dotcms.com Quest - 1 Column"], Save and Publish

6. Open "my-page" page asset, Lock for Editing
7. Add Content (Generic) [title: "UNITED STATES FLAG"] and Insert Image on WYSIWYG field from "/test/Flag.png", Save and Publish
8. Edit Content (Generic), Lock for Editing, Change Language to "Español (ES)" and Insert Image on WYSIWYG field from "/test/Flag.png" [title: "SPAIN FLAG"], Save and Publish

9. Open "my-page" page asset, Edit Content, Change Language to "Español (ES)" and Look at WRONG Image from WYSIWYG field: UNITED STATES image is displayed but SPAIN image should be displayed

## Expected Behavior
SPAIN image should be displayed while editing WYSIWYG content when having Language changed to "Español (ES)"

## Current Behavior
UNITED STATES image is actually/wrongly displayed while editing WYSIWYG content when having Language changed to "Español (ES)"

## Screen Shoots
<img width="721" alt="screen shot 2017-07-05 at 3 58 29 pm" src="https://user-images.githubusercontent.com/22307536/27887150-695a90a6-619c-11e7-97ea-c44fcf2049d0.png">

<img width="1439" alt="screen shot 2017-07-05 at 3 58 48 pm" src="https://user-images.githubusercontent.com/22307536/27887163-70b39d84-619c-11e7-9d68-7f3d57ab1a43.png">

## Context
Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a (3.7.1). Reason why image on WYSIWYG content is NOT displayed according selected Language (in our case, Español (ES)) is because (1) WYSIWYG component references it without any language-parameter and (2) language-attribute in session is not changed as part of the Content's Language drop-down
```
<p>SPAIN FLAG</p>
<p><img src="/test/Flag.png" alt="Flag" width="320" height="213" /></p>
```

## Possible Approaches/Solutions 
1. Do Nothing (Fix by Design). Leave WYSIWYG displaying images in locale-agnostic way
2. Switching Language-Id in Session upon Change on Language drop-down (Content edit screen). This have global impact on the language user is currently browsing site with
3. Remove Language drop-down (in Content edit screen) so user will only able to edit language-specific content by relying on what is in session
4. Add "languageId" parameter to URL that does not impact the language set in session
5. Others?

## Your Environment
* dotCMS version used: 3.7.1 and 4.1.1.
* Browser Name and version: FF
* Operating System and version: MacOSX
* Application Server and version: Tomcat
* Database and version: MySQL

## Resources
![flag](https://user-images.githubusercontent.com/22307536/27885540-982b3130-6195-11e7-9e31-006ec7bba7f4.png)
![flag](https://user-images.githubusercontent.com/22307536/27885550-a0b5935e-6195-11e7-8495-068cec1b6d50.png)
![flag](https://user-images.githubusercontent.com/22307536/27885577-afa4248e-6195-11e7-927f-d2e429c35555.png)

**Comment by wezell** [comment]
fixed in master with #8229

**Comment by agomez-dotcms** [comment]
After tests against master and backport/hotfix, I was able to confirm that this problem gets fixed by issue https://github.com/dotCMS/core/issues/8229 and PR https://github.com/dotCMS/core/pull/12075. Hence, moving to In-Review pipeline

**Comment by agomez-dotcms** [comment]
The fix for this issue may also be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12060_v3.7.1. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=b0a6e664-a9e6-4a0f-a3cf-9de25245ae1a

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres and now works as expected
