### ISSUE TITLE
Login Screen too wide

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12068]
A regression in master.  It should look like it does on demo.dotcms.com/dotAdmin

This is what it looks like now
![screen shot 2017-07-07 at 1 01 59 pm](https://user-images.githubusercontent.com/934364/27968399-d9e277fc-6314-11e7-8c3d-2a6a4cd0e72e.png)

**Comment by fmontes** [comment]
This need to be tested in a bigger screen.
