### ISSUE TITLE
Vanity URLs performance tests

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12081]
We need to run performance tests on the new Vanity URLs:

1. Using Apache Benchmark execute multiple performance tests on latest master and on a 4.1.1 dotCMS version in order to compare the results.
2. Make sure the cache is working properly checking that we are not executing unnecessary SQL queries, tools like https://glowroot.org can help us to accomplish that.

**Comment by oswaldogallango** [comment]
Here, are the results from the apache benchmark for Virtual link on dotcms 4.1.1 and Vanity URL on dotcms 4.2.0. The tests used 1000 requests with 50 concurrent requests on all the cases

https://gist.github.com/oswaldogallango/cd1a2211650fcf5adf031d1808457c82
