### ISSUE TITLE
Test Vanity URLs upgrade task

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12084]
Make sure the upgrade tasks of Vanity URLs are working properly, we need to test those upgrade tasks with large data sets.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12119

**Comment by jgambarios** [comment]
**NOTE:** We tested this upgrade task using a large data set, we found some issues during the tests but those issues are now fixed.

**Comment by bryanboza** [comment]
We are having some problems after test with a real DB in MySQL: https://gist.github.com/bryanboza/76b5b74e3cec8a1edf9fadfe6d0f2ef4

**Comment by oswaldogallango** [comment]
p.R https://github.com/dotCMS/core/pull/12295

**Comment by bryanboza** [comment]
Fixed, after this fix now we are creating the content type and migrating all the vanities to content, tested in the 4 databases with real data and works as expected.
