### ISSUE TITLE
Replace boolean casting by Boolean in jsp files

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#12086]
This files need to be modified:
* src/main/webapp/html/portal/layout_portal.jsp
* src/main/webapp/html/portlet/ext/browser/view_browser_js_inc.jsp
* src/main/webapp/html/portlet/ext/common/sub_nav_inc.jsp
* src/main/webapp/html/portlet/ext/containers/view_containers.jsp
* src/main/webapp/html/portlet/ext/folders/context_menus_js.jsp
* src/main/webapp/html/portlet/ext/folders/menu_actions_js.jsp
* src/main/webapp/html/portlet/ext/templates/view_templates.jsp

It is causing a runtime exception when the application is deployed on JBoss EAP 6.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12087

**Comment by wezell** [comment]
This fix is required to run on jboss

**Comment by wezell** [comment]
@DeanGonzalez This change required to run 4.1.1 on Jboss, correct?  It should be noted in jboss  doc or on the changelog?

**Comment by john-thomas-dotcms** [comment]
Updated the 4.1.1 change log: https://dotcms.com/docs/latest/changelogs#ImportantNotes4.1.1

I left this out of the JBoss doc itself, since it only applies to the 4.1.1 release (and won't apply once 4.2.0 is released).

**Comment by DeanGonzalez** [comment]
I also placed a note in the 4.2 changelog under fixed tasks: https://auth.dotcms.com/docs/latest/changelogs#Fixes4.2.0
