### ISSUE TITLE
synchronize VanityUrlServices.initializeVanityUrlCache

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12099]
This is building all vanity urls by host - I think we should synchronize this method on the host+languageId interned because on a cold system, this method would get called ... a lot

**Comment by wezell** [comment]
maybe the initializeVanityUrlCache() too

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/12089

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12180
