### ISSUE TITLE
vanity urls - 301 redirect results in a 302 redirect

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12098]
I have this Vanity URL

![screen shot 2017-07-11 at 7 23 56 pm](https://user-images.githubusercontent.com/934364/28095090-871336ee-666e-11e7-903a-1256a6bb909f.png)

and I am getting this response from the server:

```
hot-fries:dotcms_3.7.0 will$ curl --head http://127.0.0.1:8080/test
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Location: http://127.0.0.1:8080/about-us/index
Connection: close
Content-Length: 0
Date: Tue, 11 Jul 2017 23:23:24 GMT
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12120

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres
