### ISSUE TITLE
Site Search: Results for URL Mapped contents are not displayed properly.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12102]
## Expected Behavior
For URL Mapped contents, the Result.Title attribute should be populated with the content title and not the Detail page's title

## Current Behavior
For Site Search, any search on a frontend implementation will return the detail page for URL Mapped contents if the search term is the actual Detail Page title. This happens also for every content of the same content type, overriding every content's title with the detail page one,

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Go to demo (4.1.1) or demo3 (3.7.1) site.
2. On the homepage, go to the top right corner of your screen and type "News Detail". Click on search button.
3. Results list looks like this: 

<img width="1218" alt="screen shot 2017-07-12 at 6 39 00 am" src="https://user-images.githubusercontent.com/1717110/28118038-da88d3d4-66cc-11e7-8b3f-44ad74f4dc9d.png">

As you can see on the first result, the title should be `Blackberry goes cross-platform as it unveils devices`, but instead it displays the Page Detail title for these URL-Mapped contents. The URL displayed here is the right one though. 

The Velocity code that shows these results is this one 

```
            #foreach($result in $searchresults.results)
            ##PRINTING EACH SEARCH RESULT
            <li>
                <h4><a href="$result.uri">$result.title</a></h4>
                <p class="url">http://$result.url</p>
                ##<p>$UtilMethods.shortenString("$result.description", 160)</p>
                #foreach($highlight in $result.highlights)
                    <p class="resultSummary">$highlight...</p>
                    #break
                #end
                <p class="resultsNum">modified: $result.modified</p>
                <p class="resultsNum">${result.highlights.size()} match(es) in document</p>

                #set($i =$math.add($i, 1))
                #if($i==$show)
                    #break
                #end
            </li>
            #end
```
 
and if we print  `Result: $result` on this code, we get this: 

```
Result: News Detail:demo.dotcms.com/news/blackberry-goes-cross-platform-as-it-unveils-devices
```

## Context
Reported by customer https://my.dotcms.com/tickets/detail.dot?id=77996538-5bcb-48c8-be9e-282dd80db087

## Your Environment

* dotCMS 3.7.1, 4.1.1.
* Any OS and Browser.
* Any app server. 
* Java 8u121.
* Any DB.

**Comment by wezell** [comment]
This is an implementation issue not a dotcms issue per se.  Site Search reads this value from what's printed in the <html><head><title></title> value.  On a detail page, this should be coded to print out the URL mapped title value.  We just need to adjust the starter site.

**Comment by joseorsini** [comment]
Thanks, @wezell. We'll get back to customer with this suggestion.

**Comment by brentgriffin** [comment]
Seems like nobody updated the starter site - i just added the necessary changes to the html_head.vtl file on starter so this should work properly in future releases.
