### ISSUE TITLE
VirtualLink Cache invalidations need work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12101]
Sorry for the attached gif - and ignore the contentlet that won't publish - that was in an old screen I hadn't refreshed.  But 

1. Create + Publish a vanityurl
2. test it, forward works!
3. unpublish the vanityurl
4. test it again - it doesn't forward!
5. publish the same vanityurl
6. test it, it's broken! 

![cache-invalidation](https://user-images.githubusercontent.com/934364/28096621-398c9ad2-6678-11e7-9477-9b46bc3778a5.gif)

**Comment by wezell** [comment]
also, feel free to send me to some good free screencap software that does not use flash and whose hosting won't go away after a year

**Comment by oswaldogallango** [comment]
show action in listing P.R. https://github.com/dotCMS/core/pull/12137

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12180

**Comment by bryanboza** [comment]
Fixed, now we are unable to reproduce that case on master, new case opened here: #12222
