### ISSUE TITLE
Breadcrumbs are not cleared when using browser's back button 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12112]
Go to categories portlet and start navigating to parent->children categories, and go back using the browser's back button. Breadcrumbs are not cleared 

<img width="1104" alt="2017-07-13_0949" src="https://user-images.githubusercontent.com/1576794/28172246-b3f6368c-67b0-11e7-8a11-cc69cbe9c186.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12130

**Comment by DeanGonzalez** [comment]
The crumbtrails work, even though there is a different issue we still have to fix with applying categories and making sure the cat-search crumbtrails work when adding content with nested categories.... but separate task (#12127), so passing this one.

**Comment by danlaguna** [comment]
After revision of the issue I found a weird behavior.

Steps to reproduce:
1) Create a new category: Test
2) Go into Test and create a new Category: Test2
3) Go into Test2 and create a new Category: Test3
4) Use the breadcrums to go to the Top Level
5) Click on Test, then Test2 and finally Test3
6) Use breadcrums to go to the Top Level again
7) Hit Back on the Browser. The breadcrums lose the reference (see image)

Expected result:
The breadcrums should show:
Top Level > Test > Test2 > Test3
<img width="1440" alt="screen shot 2017-07-18 at 2 30 19 pm" src="https://user-images.githubusercontent.com/26439824/28338308-c4d51b26-6bc5-11e7-84c5-09b610d659de.png">

**Comment by shaydotcms** [comment]
Passed QA.
Followed steps to reproduce with new categories and old categories and it's working
Tested again original issue and it's working

Tested locally using the following environments:
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit f49bdf82745833681f4d0a5e4a554dcd33d5f130
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
