### ISSUE TITLE
Adding HTTP Headers through Tuckey Plugin

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#12114]
Currently it's not possible to set headers such as Cache-Control through the tuckey plugin, this configuration must be done either through static plugin or at the LB level.

In our binaryexporterservlet, we need to check if the Cache Control headers are already set before setting them again:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/servlets/BinaryExporterServlet.java#L427-L445

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=72c84d4f-4511-45a2-98de-5be68a43e3c3

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12340

**Comment by nollymar** [comment]
An example of how to configure tuckey rules:

~~~
        //Defines a rule to set Cache-Control for images
        NormalRule rule = new NormalRule();
        rule.setFrom("([^\\s]+(\\.(?i)(jpg|jpeg|png|gif|ico))$)");
        SetAttribute attr = new SetAttribute();
        attr.setType("response-header");
        attr.setName("Cache-Control");
        attr.setValue("max-age=31536000, public");
        rule.addSetAttribute(attr);
        addRewriteRule(rule);

        //Defines a rule to set Cache-Control for other resources
        NormalRule rule2 = new NormalRule();
        rule2.setFrom("([^\\s]+(\\.(?i)(css|js|pdf|fvl|swf))$)");
        SetAttribute attr2 = new SetAttribute();
        attr2.setType("response-header");
        attr2.setName("Cache-Control");
        attr2.setValue("max-age=2628000, public");
        rule2.addSetAttribute(attr2);
        addRewriteRule(rule2);
~~~

**Note**: Delete browser cache once the plugin is deployed to force a full file reloading and see the new response header policy (browser development tools can help to show the Cache-Control properties for each resource)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12340
