### ISSUE TITLE
Change color of add-new-cat message 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12113]
When you just added a new category, dialog displays a message asking if the user wants to add another one, although the message is in red, which tends to think it is an error. Message should be green if picking a color

**Comment by shaydotcms** [comment]
Passed QA.

Message color was successfully changed 
![image](https://user-images.githubusercontent.com/8741846/28272386-92f4386a-6ac8-11e7-9051-e25c6e1e5c1b.png)

MacOS 10.10 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
