### ISSUE TITLE
Forms: Remove validation of potential page extension in referrer

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12123]
Since pages do not require a page extension, this code 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/cms/content/submit/action/SubmitContentAction.java#L110-L113 

will break pages as contents and, in case of failure upon submitting a new form content via frontend page, redirect to original referrer breaks and ends up in error 404.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12124

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=e9c42b63-b5c7-4d69-b2b1-244c6ec9e5ed

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Postgres // FF
