### ISSUE TITLE
Need a friendly json for Field

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#12126]
Currently a field json is somethin like:

{
   "modDate":1498753593000,
   "indexed":true,
   "dataType":"TEXT",
   "contentTypeId":"28039964-5615-4ccfbb96ded62adbcc6a" , 
   "readOnly":false, 
   "searchable":true, "required":true, 
   "clazz":"com.dotcms.contenttype.model.field.ImmutableTextField"
}

Then only way to know the type is with the 'clazz' property (the dataType property is the database type used by the field), the class property is not friendly.

## Expected Behavior

We need a new friendly property to know the field's type.

## Possible Solution

We have to modify the json mapping in the com.dotcms.contenttype.model.field.Field class, here some examples:

https://stackoverflow.com/questions/30362446/deserialize-json-with-jackson-into-polymorphic-types-a-complete-example-is-giv

http://www.studytrails.com/java/json/java-jackson-serialization-polymorphism/

## Steps to Reproduce (for bugs)

Currently we have at least two End point who work with Fields.
- https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResource.java#L214

- 
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/FieldResource.java#L59

**Comment by wezell** [comment]
This is an improvement and not critical.
