### ISSUE TITLE
Error showing categories in categories dialog when creating/editing contentlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12127]
Either create a new content type with a field of type 'category' or edit an existing contentlet of any of the types with cat fields (e.g. Blog), and try to open the cat field dialog. 

'Sorry, an error occurred' will be displayed and not cats will show. 

Error is because the jsp is not sending (need to figure out why) param 'count' in the url when making the request to the categoriesServlet:

Request in 4.1: /categoriesServlet?inode=3b8c53ec-f6ba-4b81-adef-6b7ed38a8490&q=&start=0&**count=10**

Request in master: /categoriesServlet?inode=375341a2-0912-422f-b903-2602b6105c70&q=&start=0

Code expects both (start, count) params to be set: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/servlets/JSONCategoriesServlet.java#L92

Need to figure out why jsp stopped sending the count param

**Comment by nollymar** [comment]
It was fixed with a rollback of the last upgraded dojo version. PR: https://github.com/dotCMS/core/pull/12147
