### ISSUE TITLE
[core] The "Save and Publish" button of the Upload Multiple Files dialog is only showing up for Admin users

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12122]
- Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=aa8b5874-80ab-478d-8634-6b9158c07a9b
- dotCMS 4.1.1

## Expected Behavior
The Upload Multiple Files dialog should allow permissioned non-admin users to click the **Save and Publish** button when uploading files through the UI.

## Current Behavior
Non-admin users are seeing the **Cancel** and **Save** buttons, but NOT the **Save and Publish** button.

## Possible Solution
Compare previous versions of the code in order to figure out why the code changed regarding the display of the **Save and Publish** button for non-admin users. As it is right now, such a button IS displayed if the following two conditions apply:

1. The logged-in user has the CMS Owner or the CMS Administrator role.
2. The workflow scheme associated to the File Asset Content Type (.i.e, the type of content associated to files) is not mandatory.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Log into the dotCMS back-end with a limited user.
2. Go to the Site Browser and click any of the folders you have access to.
3. Click the ellipsis and then the "Multiple Files" option.
4. Select the "File Asset" content type and click the "Select file(s) to upload" button. Select any file(s) you want.
5. The "Save and Publish" button does not show up.

## Context
This is imperative for customers who want to assigned limited permissions to their users, instead of granting admin roles to them.

## Your Environment
* dotCMS version used: 4.1.1
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Content Edition.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12138

**Comment by bryanboza** [comment]
Fixed, tested on master // Chrome

**Comment by bryanboza** [comment]
Fixed, tested on master // chrome
