### ISSUE TITLE
Improve Category Bundler/Handler process

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#12125]
Currently we are Push Publishing all the Categories from the Category Portlet, we need to improve this process by setting the categories as dependencies of the contentlets that we are pushing.

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/486
PR core: https://github.com/dotCMS/core/pull/12178

**Comment by oarrietadotcms** [comment]
We decided to modify to xml file extensions for categories, _.category.xml_ for the old one (full) and for the new _.category.dpc.xml_

PR ee: https://github.com/dotCMS/enterprise-2.x/pull/492

**Comment by dsilvam** [comment]
Issue created from doing QA of this one: https://github.com/dotCMS/core/issues/12248

**Comment by DeanGonzalez** [comment]
Added doc to change log and also here: 
https://auth.dotcms.com/docs/latest/push-publishing-dependencies#Categories
https://auth.dotcms.com/docs/latest/what-to-know-before-push-publishing
https://auth.dotcms.com/docs/latest/pushing-categories

**Comment by john-thomas-dotcms** [comment]
Updated the doc on push delete to be clear that you can not push to delete categories: https://auth.dotcms.com/docs/latest/push-publishing-content#PushDelete
