### ISSUE TITLE
Forms cannot be submitted

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12128]
Once the fix for this issue is in place: https://github.com/dotCMS/core/issues/12123, we're able to see that Forms stopped working in 4.x. 

This is a deprecated issue, however, upgraded clients would like to keep them in place until a replacement as content (REST API calls) is in place. The problem here is that, for some reason, the application cannot find the Content Type of this form, despite it exists on data. 

## Expected Behavior
Forms should be submitted without problems.

## Current Behavior
Forms cannot be submitted. Without the fix for #12123, it returns a 404 Error page because it cannot go back to the original referrer upon failure in verifying the content type. After applying this fix, we're able to see a message called "Content Type with id:'' not found" on the form page. 

Debugging the code from SubmitContentAction class, 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/cms/content/submit/action/SubmitContentAction.java#L128

We're able to see that the content Type Inode is pulled from the form's info (it's rendered as a hidden field in the form code), however, lookup on ContentTypeAPI returns a null object and verification is made by the content type's name (unsupported, only Variable and Inode columns are used for search purposes).

```
[17/07/17 12:24:47:717 EDT]  INFO action.SubmitContentAction: Creating form for Content Type with inode 013be3ab-b6da-45c2-9c21-95eb11a33322
[17/07/17 12:24:47:724 EDT]  WARN cache.LegacyContentTypeCacheImpl: Structure with inode: 'Proposal Request Form' not found in db
[17/07/17 12:24:47:726 EDT] ERROR action.SubmitContentAction: Content Type with id:'' not found
```

## Steps to Reproduce (for bugs)

1. Apply fix from #12123, in order to avoid error 404 page upon failure in submitting a form.
2. Go to https://demo.dotcms.com/contact-us page. 
3. Submit a form. It will fail. 

## Context
Reproduced on demo site, running dotCMS 4.1.1. 
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=e9c42b63-b5c7-4d69-b2b1-244c6ec9e5ed

## Your Environment

* dotCMS 4.1.1.
* Any OS/Browser.
* Any application server.
* Java 8u121.
* Any DB.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12135
