### ISSUE TITLE
Push Publish button does not work in user portlet

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#12121]
In the User portly if you select a user and hit the Push Publish button in the upper right section of the portlet the Push Publish dialog appears and is able to be filled out and submitted.  At hitting Push to submit the job the dialog goes away and no job appears in the publishing queue, nor is anything written to the logs.  Right clicking the user and selecting Push Publishing pops up the Push Publish dialog and when the Push button is hit to submit the job the dialog goes away and a job does appear in the publishing queue and the user is subsequently pushed to the target environment.

## Your Environment

* dotCMS version used: 3.7.1, 4.1.1
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=6b1c8882-bbcd-499c-9dc7-42e2d92314e6
