### ISSUE TITLE
[Improvement] [UI] Summarize a Folder's children before deletion

### ISSUE THREAD

**Issue by lucidmachine** [dotCMS/core#12139]
When a user attempts to delete a Folder in the Site Browser portlet the system opens a confirmation dialog which warns that the Folder's children will also be deleted. Expand this dialog to also provide a summary of the Folder's children which will be deleted with the target Folder.

## Expected Behavior
The confirmation dialog's message should include summary statistics. For example, "Are you sure you want to delete this folder? All 10 files, 2 folders, and 37 contentlets in and beneath this folder will be deleted.  (This operation cannot be undone)." These statistics would aid the user in determining whether they want to delete all of the target Folder's children.

## Current Behavior
Currently the confirmation dialog's string is static and contains no summary data. It simply reads contents of the language property with key "Are-you-sure-you-want-to-delete-this-folder-this-action-cant-be-undone". In English, this is "Are you sure you want to delete this folder? All files, folders, and content in and beneath this folder will be deleted.  (This operation cannot be undone)".

For the user to determine whether they want to delete the target Folder's children as well as the target Folder they must find all of the Folder's children manually using multiple different Portlets. To determine how many child File Assets or Page Assets or Folders may be deleted the user must use the Site Browser portlet to expand all Folders beneath the target Folder. To determine how many Contentlets may be deleted the user must use the Content Search portlet to run one search for each Content Type for each Folder under and including the target Folder. Performing all of this navigation and these searches can be time-consuming and error-prone.

## Possible Solution
Utilize internal API calls such as FolderAPI.findSubFolders(), FileAssetAPI.findFileAssetsByFolder(), and ContentletAPI.findContentletsByFolder() in order to collect all objects which are children of the target Folder. Compute summary data, which may include figures such as the total number of children, number of child Folders, number of child File Assets, number of child Contentlets,  etc. Inject that summary data into the function deleteFolder() in view_browser_js_inc.jsp. Interpolate the data into the internationalized string and pass the resulting string into the confirm() call.

## Known Workarounds
Manually locate all child Files, Folders, and Contentlets. See section Current Behavior.

## Context
Our clients often accidentally delete important File Assets or Contentlets they didn't realize existed in or beneath the target folder. Contentlets are especially problematic because they are not visible from the Site Browser portlet where the user is attempting to delete a Folder.

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=ddcf173a-06c7-468a-ae18-95941be50173

**Comment by brentgriffin** [comment]
workaround is twofold:
1.  Site browser visually shows all folders and files beneath a given folder
2. On the content site search portlet, you can search for a folder and see all of the content in that folder

**Comment by brentgriffin** [comment]
Per discussion with will and client, https://dotcms.zendesk.com/agent/tickets/90585 - this will be addressed when the site browser is refactored.
