### ISSUE TITLE
Need fix the redirect after add the new language variables using the "+" button 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12146]
We have problems with the redirect when you add a new piece of content type language or vanity URL

## Expected Behavior
After you add the piece of content, the system should redirect to the content search add show all the contents of this content type 

## Current Behavior
We are redirecting to add a new generic content 

SC: https://screencast.com/t/vbKhA8xc

## Steps to Reproduce (for bugs)
1. Add a new Key/Value content type 
2. Using the "+" button in the angular menu add a new piece of content  
3. Save & Publish and look the redirect 

## Your Environment
Tested on master // Chrome

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12595

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by bryanboza** [comment]
After test the last changes, now we are unable to reuse the same link to add more that one content, after you add a piece of content and you try to add other one with the same link, this doesn't work 
SC: https://screencast.com/t/h2k5p8sUIhda

**Comment by jgambarios** [comment]
**Note to QA:** This is a reported problem in Fox where an url can not be reused/refresh when was already resolved https://github.com/dotCMS/core/issues/12661

**Comment by bryanboza** [comment]
Fixed, now the redirect is working as expected, need validate we fix the problem when you try to reuse this link... Reported here  #12661
