### ISSUE TITLE
Category Select Broken when creating New Content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12145]
Tested on latest Master

I was testing the fix to: https://github.com/dotCMS/core/issues/12112

I created a new content type, and imported the .csv category list (see attached), that I always use for training, and applied it on a category field on a content type.

Then when I tried to create content and apply the new category, the select category field was broken and unusable (Sorry, an error ocurred):
![caterror](https://user-images.githubusercontent.com/1569167/28343074-be68ce64-6bd8-11e7-9674-34cd52d5deb3.jpg)

There were also JavaScript Errors on the page:

![javascripterrors](https://user-images.githubusercontent.com/1569167/28343090-cf1d34c0-6bd8-11e7-8e64-2fe77147c02e.jpg)

**Comment by dsilvam** [comment]
Already reported here https://github.com/dotCMS/core/issues/12127. Closing as dup
