### ISSUE TITLE
Pushing Language Variables as content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12142]
## Expected Behavior
- As the old variables when you push some language,  we need push it by dependency.
- In pushing the new language variables,  need to respect their last_push dates and only push if they need it.

## Current Behavior
We just are sending the old language variables, but not including the content ones.

## Your Environment
Tested on master // postgres // FF

**Comment by wezell** [comment]
We need to maintain our current behavior

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12200

**Comment by bryanboza** [comment]
We still having problems on this specific case: 
1- Create a new language 
2- Create a new piece of content in this language (Generic, page, anything)
3- Create a new language variable in this language 
4- Push the piece of content

By dependency the system is pushing the language to create the content on the receiver, but isn't sending the language variable

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12238

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

FYI: We have the follow behavior, maybe we can improve the performance in the future 

1. We are including ALL the language variables the first time you push some content related to some language 
2. After this, we are sending the edited language variables and the new ones, this in every push, but just in the language that you are sending content (this is happening in every push, we are ignoring if the pushed content is related to the language variable or not)

**Comment by wezell** [comment]
We are going to need to fix the case where a language variable already exists on the receiver and you push another variable with the same key and a different identifier

**Comment by jcastro-dotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/12426
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/515

**Comment by jcastro-dotcms** [comment]
Code review PRs:

Core PR: https://github.com/dotCMS/core/pull/12436

**Comment by bryanboza** [comment]
We still having problems here: 

- [ ] When you are sending some unique content and already exist on receiver, the system is just creating the new version of the content, but not deleting the old one... 
To recreate: 
1. Create a new content manually on both sides, on sender unpublished and in sender published
2. Push the created content from sender to receiver
3. The system is replacing the existing one, but we still having live and working versions

- [ ] As we remplace by key when you push , we should support the remove, right now we just are validating if exist the identifier and if not we are not deleting... 

FYI: I tested the case #1 with generic content and works as expected, this is an issue related to unique fields changes...

**Comment by jcastro-dotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/12571
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/530

**Comment by bryanboza** [comment]
- [ ] After test we solve the first problem, but still having the problems with the delete, also found a new issue following this steps: 
- Create a new language variable on sender 
- Push it 
- Unpublish this variable on sender 
- Push again (we should remove the live and just leave the working version) 
- Publish the variable one more time 
- Try to push

**Comment by jcastro-dotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/12604
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/536

**Comment by bryanboza** [comment]
Tested after the last PR, and we still having problems with the follow case: 

- Create a new language variable on sender
- Push it
- Unpublish this variable on sender
- Push again (we should remove the live and just leave the working version)
- Publish the variable one more time
- Try to push again

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/539

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
