### ISSUE TITLE
Push Publishing Event Listeners

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12141]
dotCMS will create events that are fired when the a PP job is completed.  dotCMS users can create listeners that can be called which can then perform any action the user would like, from kicking off an rsync process to sending a notification.  These user created listeners will be able to be deployed/registered via OSGI.

Events that will fire:

- PP ADDED TO QUEUE
- PP Process Start
- PP Process End
- PP ALL Endpoints Success
- PP ALL Endpoints Failure
- PP SINGLE Endpoint Failure

**Comment by dsilvam** [comment]
PR for event-listeners https://github.com/dotCMS/core/pull/12192

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12196
Plugin Example: https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.pushpublish.listener

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12202
PR plugin-seeds: https://github.com/dotCMS/plugin-seeds/pull/11

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/push-publish-listeners-configuration
