### ISSUE TITLE
Unable to see the Wysiwyg editor the first time you try to add content after start the server

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12152]
We are having problems trying loading the wysiwyg field the fist time you try to add content after start the server 

## Expected Behavior
We should be able to add content and load this field without problems 

## Current Behavior
We ara unable to see the editor: https://screencast.com/t/g08PVGUG9we

## Steps to Reproduce (for bugs)
1. Start the server 
2. Login 
3. Try to add a new piece of generic content 

## Your Environment
Tested on master // chrome

**Comment by woontsoudev** [comment]
When the browser tries to load "tinymce", it has a delay when read the plugins list.

File: "core/dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field_js.jsp"
line 44

NOTE: Using the setTimeOut function to wrap the function initialisation it's a possible quick solution to fix this problem.

**Comment by erickgonzalez** [comment]
Unable to reproduce with the latest code.

**Comment by bryanboza** [comment]
Tested in the latest master and neither can reproduce... Moved to passed QA
