### ISSUE TITLE
Add properties form to create or edit fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12156]
**ADD ALL/SAME FIELDS TO ALL THE TYPES WE HAVE ANOTHER STORY FOR CUSTOM DATA: https://github.com/dotCMS/core/issues/12193**

----

### Design
https://github.com/dotCMS/core/issues/12172

### How this work
1. You drag and drop from sidebar  to the drop zone.
2. On drop you get a dialog
2. Dialog include form with the properties fields for "that" type of field **(mark required fields)**
3. User should fill the form and hit "Add" button
4. Do a request to save the field
5. Close the dialog
6. If the user hit "cancel" close the dialog and remove the field from the drop zone

### Edit field
1. When you click a field, dialog open again to "edit" properties of the field
2. Action button should read "Save"

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
Merged https://github.com/dotCMS/core/pull/12257
