### ISSUE TITLE
Key field in the key/value content types must be unique 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12155]
Related to #11924 

As in the old language variables, we need verify if the key already exist in other piece of content to avoid language variables with the same key in the same content type 

## Expected Behavior
We need show a WARN that already exist other content with the same key 

## Current Behavior
We are allowing add multiple contentlets with the same key in the same key/value content type 

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new content type key/value 
3. Try to add more that one content to this content type (this with the same key value)

## Your Environment
Tested on master // postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12204

**Comment by bryanboza** [comment]
Fixed, tested on master // MySQL // FF
