### ISSUE TITLE
Language variables as content should use locale when the language_id don't have associated country 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12168]
As part of the new language variables improvements, when you use a generic language, and this one don't have associated country, the system should use the locale to define the priority

## Expected Behavior
If you request some page in some language that don't have associated country, we need use some rules to define the priority: 

1. The system need try to get the language in your specific location
2. If don't exist that language in your with your country code, should use the generic one

**FYI:** This case is ONLY when you try to use the generic languages (without associated country), if the language have associated country the fallback is working fine 

Example: 
You have this languages: 
1. EN-(US)
2. ES-(ES)
3. EN ()
 
If you try to get some language variable with the ?language_id=3, the system should try to get, EN with your country code (**EN-(US)**), this before the the generic (**EN ()**)

## Current Behavior
If you request some language variable in a generic language and this exist, we are using this, and never check if exist in the language with your locale. 

## Steps to Reproduce (for bugs)
1. Login  
2. Create a new English generic language (**without associated country**)
3. Create a new language variable ("**Variable1**") in both languages (**EN-US // EN**) but with different value  
4. Add a new page with a widget that try to get this language variable (**$text.get("Variable1")**)
5. Try to see the page with the **language_id = EN** (generic, without country)

FYI: **We are getting this without priority, we need use the locale first if exist...**

## Your Environment
Tested on master // Postgres // Chrome

**Comment by jdotcms** [comment]
On it

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12263

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF... Basically we are taking the browser language to set the location
