### ISSUE TITLE
Need add/remove flags to the pages in languages without country 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12161]
As part of the new language variables as content now we can add languages without country, then when you add a new page in that language we are having problems at UI level with the flag 

## Expected Behavior
We should define/remove some flag  or remove it 

## Current Behavior
We are having a square without image 

SC https://screencast.com/t/gaf3VSDqr

## Steps to Reproduce (for bugs)
1. Login 
2. Add a new language without country
3. Add a new page on this language 
4. Make sure you have the correct flag in the page info 

## Your Environment
Tested on master // Chrome

**Comment by bryanboza** [comment]
Also the languages without associated country: https://screencast.com/t/ybkiVnfz

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12255

**Comment by bryanboza** [comment]
Fixed, now you can configure this on the dotmarketing file with the follow properties....
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/dotmarketing-config.properties#L865

Tested on master // Oracle // Chrome

**Comment by jgambarios** [comment]
@erickgonzalez during the product owner meeting we decided we don't want to handle the default flag using properties but instead we just want to add the default flag gif files for each language, so please remove the new properties and the logic related to it and change it to the default image solution.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12373

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now we don't have the properties on the dotmarketing file, now we hace defined the flags...
