### ISSUE TITLE
[UI] The "Site or Folder" field is not working correctly when expanding sites at the bottom.

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12163]
Reported via Suport: https://my.dotcms.com/tickets/detail.dot?id=2d9e66f9-6e00-4326-86bf-94310f100c31
dotCMS version: 4.1.1, 4.2.0

When adding existing content to a page container, a dotCMS instance with a high number of Sites is causing the **Site or Folder** field of a Content Type to behave incorrectly when expanding a Site located near the bottom of the drop-down.

## Expected Behavior
The **Site or Folder** filtering when adding an existing content to a page container must allow users to expand any Site they need - either at the top or the bottom of the field.

## Current Behavior
When filtering existing content, the small pane in the **Site or Folder** field is closing and setting the value as "Root" when expanding a Site near the bottom of the widget.

## Possible Solution
Check the Dojo widget that expands the Sites.

## Known Workarounds
First expand the Sites that are not completely at the bottom of the widget, keep expanding the next ones until you're close to the Site you want to select.

## Steps to Reproduce (for bugs)
1. Log into http://demo.dotcms.com/c
2. Go to the **Sites** page and create around 13 empty Sites, e.g., "com.demo.test1" to "com.demo.test13". Make sure they're active.
3. Now, go to the **Site Browser**.
4. Open up the "index" located at the root of the "demo.dotcms.com" Site.
5. Lock for editing and, in the first container, click **Add Content > Reuse Content**.
6. Select the **Event** Content Type.
7. Click the **Site** drop-down, try to expand one of the Sites at the bottom of the widget, e.g., "demo.dotcms.com". The dialog closes and the selected value is set to "Root".

## Context
Customers need several more clicks to filter contents by Site or Folder.

## Your Environment
* dotCMS version used: 4.1.1, 4.2.0
* Browser Name and version: Chrome
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Page Edition.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/12794

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // Chrome
