### ISSUE TITLE
Add param to site-selector to show archived/stopped sites

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12166]
### What to do:
1. By default, the ```site-selector-component``` will get archive and stopped sites
2. Add a ```boolean``` attribute to load **only** published and live sites
3. Update the ```site-selector-component``` in the ```toolbar-component``` and set this new attribute to ```true```

### How to do it:
1. Update the ```site-selector``` component to add the required filter to the ```pagination-service```
2. Not sure if the current endpoint supports this

### In the backend:
1. Update the ```/site/``` backend to be able to receive params for archive or live host.
2. If possible, make sure urls for pagination doesn't return empty params

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11)
3. Multilanguage
4. Unit test

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12237
