### ISSUE TITLE
File Select Dialog Filter Field Doesn't Filter Files 

### ISSUE THREAD

**Issue by manuel-miranda** [dotCMS/core#12167]
Reported via Suport: https://my.dotcms.com/tickets/detail.dot?id=ede0e045-6d8b-4fbd-8808-4ade87c3dc49

File Select Dialog Filter Field Doesn't Filter Files 

## Expected Behavior
Filter files/images by name and avoid scroll down for searching in a big list.

## Known Workarounds
Scroll down to select file in a big list.

## Steps to Reproduce (for bugs)
1. Log in to the portal.
2. Create a new Contentlet whose Content Type contains a File Field. For example, create a new Contentlet of type “Blog”.
3. Click the “Browse…” button next to the Source Field.
4. In the file tree pane on the left side of the window, navigate to a host or folder which contains images.
5. In the “Filter” field, type a text string which should match the contents of some - but not all - of the names of the File Assets listed.
6. Press the Enter key to submit the form.

## Context
Customer cannot filter images they have to scroll down the list to select the image they want to add.

## Your Environment
* dotCMS version used: 4.1.1
* Browser Name and version: Opera, Google Chrome.
* Operating System and version: Not relevant.
* Application Server and version: Tomcat 8.0.18
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Not relevant.

**Comment by oswaldogallango** [comment]
related to #12353
