### ISSUE TITLE
Filtering File Asset Metadata returns no results

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12176]
Tested on latest Master

Searching for types of files via metadata appears to be broken in latest master.  Using the example in the documentation:
https://auth.dotcms.com/docs/latest/file-metadata#SearchFields

The current master version returns no results when filtering metadata

![metadatafilterbug](https://user-images.githubusercontent.com/1569167/28473980-01af0d6e-6e04-11e7-8432-25c0480298e8.jpg)

**Comment by joseorsini** [comment]
Dup of https://github.com/dotCMS/core/issues/8156

**Comment by dsilvam** [comment]
Closing as dup
