### ISSUE TITLE
Problems editing languages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12174]
We are having some problems trying to edit the languages, this because we are loosing the values in the edit form 

## Expected Behavior
When you try to edit we should show the edit form with the values

## Current Behavior
We are loosing the value, all the fields appear empty 

SC: https://screencast.com/t/DyGodQj0Dy

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Types & Tags --> Languages
3. Try to edit some of the languages

## Your Environment
Tested on master // postgres // FF

**Comment by oswaldogallango** [comment]
Checking the code, I noticed that is the same code we have since 3.x, the only difference are these extra lines
```
dojo.ready(function() {
	var fieldWidth = "300px";
	new dijit.form.TextBox({
		name: "languageCode",
		style: "width: " + fieldWidth
	}, "languageCode");

	new dijit.form.TextBox({
		name: "countryCode",
		style: "width: " + fieldWidth
	}, "countryCode");

	new dijit.form.TextBox({
		name: "language",
		style: "width: " + fieldWidth
	}, "language");

	new dijit.form.TextBox({
		name: "country",
		style: "width: " + fieldWidth
	}, "country");
})
```
and if you comment those lines then the form fields properties are displayed but the styles will be broken.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12179

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // Chrome
