### ISSUE TITLE
Integration of the Content Search listing into VanityURLs portlet

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12181]
Currently the VanityURL portlet is not working as we migrated the VanityURLs to content, we need to modify the current portlet in order to display the listing of all the contents of type Vanity URL.

This portlet needs to work as the Form portlet works (Except for the landing page) where we reuse our Content Search listing but displaying/allowing only a group of specific content types, in this case content types where the Base Type is Vanity URL.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12230

**Comment by bryanboza** [comment]
We need set the referral after add/edit some vanity, this because we have all the content types in the drop-dow after add or edit some content.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12245

**Comment by bryanboza** [comment]
Fixed, tested on master // Chrome
