### ISSUE TITLE
Implement VanityURLs blacklist

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12184]
We need the ability to ignore a list of specified URL patterns when evaluating Vanity URLs.
Ignoring back end URL requests by the Vanity URLs process is going to help with the back end performance and will reduce the Vanity URLs cache footprint.

Initial list of URLs to ignore:
* /html
* /api
* /dotAdmin
* /dwr
* /webdav
* /dA
* /contentAsset
* /c
* /DOTSASS
* /DOTLESS

**Comment by wezell** [comment]
Adding:

/webdav
/dA
/contentAsset
/c
/DOTSASS
/DOTLESS

**Comment by john-thomas-dotcms** [comment]
Doc: https://auth.dotcms.com/docs/latest/vanity-urls#Blacklist

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12253

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // Chrome
