### ISSUE TITLE
Unable to organize Categories in descending order

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12188]
Categories are not being organized in descending order. This is happening for parent and child categories.

Notice on the images below that Sort Order does not change the order of the items:
![image](https://user-images.githubusercontent.com/8741846/28529606-399cfb90-704e-11e7-8844-88e45a60da6d.png)

![image](https://user-images.githubusercontent.com/8741846/28529618-4416409a-704e-11e7-97fa-7c63c6c183c8.png)

## Expected Behavior
Top level and sublevel categories should be organized in ascending or descending order

## Current Behavior
Categories are not being organized in descending order. This is happening for parent and child categories.

## Steps to Reproduce (for bugs)
1. Loging to dotcms
2. Navigate to Types & Tags/Categories
3. With existing Categories, click on Sort Order and try to organize in descending order
4. You will see it's not working 

## Your Environment
* dotCMS version used: Master branch
* Database and version: Postgres 9.3.5 
* Operating System and version: Ubuntu 14.04.1
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by shaydotcms** [comment]
I was able to reproduce this issue in demo.dotcms.com

**Comment by dsilvam** [comment]
This was broke in this commit: https://github.com/dotCMS/core/commit/cec760af830fd32d728d213e331a16018bfaffd4#diff-c913c32b993f74e63e0543442f02a1fe 

Following commit after that one made the one above not needed
