### ISSUE TITLE
Widgets: Image/File fields from Multilingual fields are not respected properly in Live Mode

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12185]
Under specific scenarios, we're not getting consistent results of how Widget contents are printed on pages, specifically if these ones have Image/File fields and their values are printed on the Widget Code of this content type. 

## Expected Behavior
Printing widget code, which in most situations will attempt to print fields' values of the same content, should respect language in session and act as regular multilingual contents.

## Current Behavior
For multilingual widgets, we're not able to get printed Image/File fields, even if these referenced assets are multilingual. We always get a different Image/File printed via REST API, however other fields from the same content it's printed honor the language in session.

## Known Workarounds
None

## Steps to Reproduce (for bugs)

1. Create a Test Widget Content Type.
- on Widget Code, add 

```
<img src ="/contentAsset/raw-data/${image}/fileAsset" alt="$widgetTitle">
```
- Add an Image field called "Image".

2. Create a multilingual file under /home folder. NOTE: It's important that the actual file has the same name in all languages, but it has to be a different asset for each language version. Let's use these: 

hydrangea.jpg (in English)
![hydrangea](https://user-images.githubusercontent.com/1717110/28491888-d18040a6-6eb5-11e7-80c1-040d924dcd10.jpg)

hydrangea.jpg (In Spanish)
![hydrangea](https://user-images.githubusercontent.com/1717110/28491892-e3607660-6eb5-11e7-9449-713905a80399.jpg)

3. Create a multilingual page under /home folder. Let's call it "test-hydrangea"
4. Create a Multilingual Test Widget Content: 
    - Widget Title (for English version): Test English.
    - Image: select /home/hydrangea.jpg file.

    - Widget Title (for Spanish Version): Test Spanish.
    - Image: /home/hydrangea.jpg file.
5. Open /home/test-hydrangea page in Edit Mode. 
6. In English version of the page, add the "Test English" widget you created. 
7. On Edit/Preview mode, Switch between English and Spanish version of the page.

English: Works OK. 
<img width="1680" alt="screen shot 2017-07-22 at 8 18 07 am" src="https://user-images.githubusercontent.com/1717110/28491908-5fab814c-6eb6-11e7-8c1a-c96cda2e1a92.png">

Spanish: Works OK.
<img width="1680" alt="screen shot 2017-07-22 at 8 18 12 am" src="https://user-images.githubusercontent.com/1717110/28491912-67dd035e-6eb6-11e7-8284-25d77cf71c6d.png">

8. On Live Mode, make the same test of /home/test-hydrangea page 

English: Works OK.
<img width="1373" alt="screen shot 2017-07-22 at 8 20 09 am" src="https://user-images.githubusercontent.com/1717110/28491937-ae91af5c-6eb6-11e7-83de-9250bd10e3f7.png">

Spanish: It shows English image. 
<img width="1372" alt="screen shot 2017-07-22 at 8 20 14 am" src="https://user-images.githubusercontent.com/1717110/28491940-b3709f88-6eb6-11e7-8e11-2e862fb316ad.png">

If we inspect the image, we see "Test Spanish", meaning that the image version we're pulling is the English one, however the other objects from the current content/Widget is from its Spanish version. 
<img width="1680" alt="screen shot 2017-07-22 at 8 21 17 am" src="https://user-images.githubusercontent.com/1717110/28491948-dfccd61e-6eb6-11e7-8813-f5c9a9c056c7.png">

## Context
Reported by customer: 
https://my.dotcms.com/tickets/detail.dot?id=487b49a4-dad7-4a59-859a-d293149dbddf

## Your Environment

* dotCMS 3.7.1, 4.1.1.
* Any OS/Browser.
* Any App Server.
* Java 8u121.
* Postgres, Oracle DBs.

**Comment by wezell** [comment]
Is this true if you clear your browsers cache?

**Comment by brentgriffin** [comment]
Personally, I am unable to recreate in the backend in edit, preview, or live mode in 3.7.1.  

I am able to recreate problems on the frontend and that is a browser cache issue.
