### ISSUE TITLE
Copy host: incorrect template on copied pages

### ISSUE THREAD

**Issue by jorith88** [dotCMS/core#12186]
We run into issues with the copy host functionality. Due to this issue we have to relink all (copied) content to all pages manually, which takes a lot of time.

## Expected Behavior

Copied pages are linked to the copied templates on the new host

## Current Behavior

Copied pages are linked to the original templates on the source host

## Possible Solution

Relink all copied pages to the copied templates. This could be provided as an option in the copy dialog.

## Known Workarounds

Manually linking the new pages to the correct templates. After this all content needs to be placed on the pages again.

## Steps to Reproduce (for bugs)

On demo.dotcms.com:

1. Navigate to System -> Sites
2. Click 'Add Site'
3. Choose 'Copy an existing Site'
4. Site to copy: demo.dotcms.com
5. Check 'All' to copy everything and click 'Next'
6. Fill in 'www.example.com' as host name and click 'Save / Activate'
7. Open the Site Browser
8. Click on the about-us folder, and right-click on index -> 'Page properties'
9. The template is 'demo.dotcms.com Quest - 2 Column (Right Bar)'. I would expect 'www.example.com Quest - 2 Column (Right Bar)'

## Context

Copying an entire site takes a lot of time when we have to switch templates for all pages. This does also mean that we have to relink all content on those pages.

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Chrome 59.0.3071.115
* Operating System and version: Windows 10
* Application Server and version: Bundled Tomcat
* Java Brand and version: Java 8u131
* Database and version: PostgreSQL 9.6
* Application module (if apply):

**Comment by wezell** [comment]
While not ideal, this has been dotCMS behavior since the beginning, I believe (I know it was in the three series).  This is working as designed.
