### ISSUE TITLE
Need indicate the required values adding new languages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12189]
After the last  changes in languages, now jut need the language code to add a new language, but we need show a required indicator in the field

 ## Expected Behavior
Need indicate witch fields are required 

## Current Behavior
We don't have indicators 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Types & Tags -> Languages 
3. Try to add a new language

## Your Environment
Tested on master // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12303

**Comment by bryanboza** [comment]
Need some styling help

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12313

**Comment by bryanboza** [comment]
Fixed, tested on master // chrome
