### ISSUE TITLE
Error starting up in H2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12203]
We are having an error when you are trying to startup the last dotcms in H2 

## Expected Behavior
We need be able to start without problems 

## Current Behavior
We have the follow exception: https://gist.github.com/bryanboza/6dfb99758ceba9395fca52aa8f04bb6d

**FYI: The server is starting normally**  

## Your Environment
Tested on master // H2

**Comment by erickgonzalez** [comment]
Unable to reproduce this with latest master https://gist.github.com/erickgonzalez/ca1bb85f441496009da412f2af841224

**Comment by bryanboza** [comment]
Tested with the last code and I am unable to reproduce
