### ISSUE TITLE
Image in WYSIWYG uses relative URL instead of /contentAsset URL

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#12214]
When adding an image in a WYSIWYG field in dotCMS I noticed that the URL that was used was a relative URL, for instance /images/myimage.png, and not /contentAsset/image/{identifier}/xxx. This is fine when all images used are located on the host, but not if there is another host from which the image is retrieved. The image will be displayed as 'missing', both in the WYSIWYG editor and on the site.

## Expected Behavior
I would expect that dotCMS would use a /contentAsset URL always or at least when the image is not located on the host.

## Known Workarounds
Do not use the 'add image' functionality? Or copy all your files to all the hosts that use the files.

## Steps to Reproduce (for bugs)
1. Edit a piece of content, for instance "About Quest" on demo.dotcms.com
2. Click on the 'insert/edit image' button in the WYSIWYG field
3. Find an image, for instance /images/photos/app-promo.jpg
4. Click OK
5. Look at the source of the WYSIWYG field. It will display an image tag with a relative URL, not a /contentAsset URL.

The best would be to test it with 2 hosts, but the demo site only has one.

## Context
We have a shared host which contains all the templates, containers and (a lot of) images. But now we can't reuse these images since the relative URL of the image can't be found on other hosts. We now need to copy all images to all hosts. I believe that in the past the URL was always a /contentAsset URL... It doesn't look as nice as a relative URL but at least it always works.

**Comment by wezell** [comment]
This will be configurable:

https://github.com/dotCMS/core/issues/8229#issuecomment-313817233
