### ISSUE TITLE
Back button sends user to Top Level instead of immediate parent category

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12216]
When you create nested categories and then clicks the back button in the browser, the user is sent to the top level category instead of the immediate parent category.
Correct behavior:
https://screencast.com/t/UNiGhhlu1LF6

Current wrong behavior:
https://screencast.com/t/0bueS851y

## Expected Behavior
Hitting back button should send user to immediate parent category

## Current Behavior
When you create nested categories and then clicks the back button in the browser, the user is sent to the top level category instead of the immediate parent category

## Steps to Reproduce (for bugs)
1. Log in to dotcms
2. Navigate to Types & Tags/Categories
3. Create a new category in Top Level: Test1
4. Click Test1 and create a new category inside it: Test2
5. Click Test2 and create a new category inside it: Test3
6. Click the back button in the browser
4. You will see the user is sent to the Top Level instead of the immediate parent category

## Your Environment

* dotCMS version used: Master branch / commit aa086af6fa8155c2e979eda2ab1e87f9d140c565
* Database and version: Postgres 9.3.5
* Operating System and version: Ubuntu 14.04.1
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by danlaguna** [comment]
Tested it again and found no issues.

Created the following structure:\
Test
-Test2
--Test3

Proceed to go to parent Test, then Test2 and finally Test3. Then use the browser back option, works as expected.
