### ISSUE TITLE
Create new VanityURLFilter 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12224]
In order to clean up the CMSFilter and separate responsibilities we need to move the current VanityURLs logic into a new filter.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/12229
https://github.com/dotCMS/enterprise-2.x/pull/491

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // Chrome, all the vanity stuff still working as expected

**Comment by wezell** [comment]
This currently fails to redirect to a urlmapped page

**Comment by jgambarios** [comment]
**Note to QA:** Please make sure to test redirects to URL Mapped pages

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12332

**Comment by jgambarios** [comment]
**Note:** Missing Integration test in order to test the redirect to URL Mapped pages

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12396

**Comment by jgambarios** [comment]
**Note to QA:** Please make sure to test redirects to URL Mapped pages

**Comment by bryanboza** [comment]
Fixed, tested with url mapped pages and works as expected...
