### ISSUE TITLE
[Push-Publishing / Bundle Handler] Performance enhancement for publishing a big bundle of Categories

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#12225]
As part of a [client request](https://my.dotcms.com/tickets/detail.dot?id=7b5f6383-6016-44b6-b349-538793fb82bf), dotCMS 3.7.1 was performing slowly when uploading a **big** bundle of Categories (around 18000 [sub-]categories in total). After analysis, it was noticed that CategoryHandler, by relying on PushCategoryUtil, was repeteadly reading same category file from bundle (concretely, with O(n^2) algorithmic complexity). **Each and every method call to "pushCategoryUtil.getCategoryWrapperFromInode(inode)" is potentially traversing all category files (repeteadly)**. This is very computationally expensive/unnecessary if taking into account that an initial single pass over category files can be used to map category-inodes to category-files. Hence, this ticket has been added to fix/track this performance enhancement in latest versions of the product and as documentation of hotfix provided to client (in dotCMS 3.7.1).

## Expected Behavior
CategoryHandler should have at least **linear-time** algorithmic complexity (**O(n)**) when reading category files from bundle

## Current Behavior
CategoryHandler is currently having **quadratic-time** algorithmic complexity (**O(n^2)**) when reading category files from bundle

## Context
Reproduced during client tests on dotCMS 3.7.1. Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=7b5f6383-6016-44b6-b349-538793fb82bf. This ticket may be addressed by refactoring "com.dotcms.publisher.util.PushCategoryUtil" in a way that provides **linear-time** algorithmic complexity (**O(n)**) to "com.dotcms.enterprise.publishing.remote.handler.CategoryHandler" (when traversing all category files contained into bundle).

## Steps to Reproduce
1. Log into dotCMS as CMS Administrator
2. Go to "Site -> Publishing Queue -> Bundles"
3. Upload a big bundle of Categories

## Your Environment
* dotCMS version used: 3.7.1.
* Browser Name and version: Any Browser
* Operating System and version: Any OS
* Application Server and version: Apache Tomcat
* Database and version: Any

**Comment by agomez-dotcms** [comment]
PR Core (Master): https://github.com/dotCMS/core/pull/12227

**Comment by agomez-dotcms** [comment]
A hotfix for this issue (targeting dotCMS 3.7.1) may be found on https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12225_v3.7.1. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=7b5f6383-6016-44b6-b349-538793fb82bf

**Comment by dsilvam** [comment]
Had to increased the heap size to 1.5gb in order to have the process completed.
In addition, when ```select count(1) from categories``` is run, count is 13677, but the count of categories inside the bundle is 17970.

**Comment by dsilvam** [comment]
Note to QA: Please test a static push and make sure the status of the push (UI) is correct

**Comment by agomez-dotcms** [comment]
Issues reported by @dsilvam on previous message are now solved by followings PRs:
- PR Core (Master): https://github.com/dotCMS/core/pull/12261
- PR Enterprise (Master): https://github.com/dotCMS/enterprise-2.x/pull/494

**Comment by dsilvam** [comment]
PR core (p8): https://github.com/dotCMS/core/pull/12327
