### ISSUE TITLE
We are not respecting the  order field in the vanities as content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12221]
As the new changes in the vanity URL we have a "order" by default in the vanity content types. Then we need respect this property  

## Expected Behavior
We need respect this property in order to resolve the vanity 

## Current Behavior
We are ignoring this property and just resolve with the first one 

## Steps to Reproduce (for bugs)
1. Login 
2. Create a new vanity content type 
3. Add two new vanities with the same URI field but select a different order 
4. Try to hit this vanity from FE 

## Your Environment
Tested on master // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12329

**Comment by bryanboza** [comment]
After do some testing here we have this enhancements: 

- We should not allow values < 0 in this field: https://screencast.com/t/u4SpWCg5ip8

- We need validate just allow numeric values on this field and improve the message... (rigth now we are not validating the first value, also if you type a number and then other character this is allowed, but if you type a number and then some other character this is allowed): https://screencast.com/t/9eDxaXKlRsI

**Comment by jgambarios** [comment]
We need to validate the use of just numeric values from the UI, agreed with that, but I don't mind to allow negative values in the order field, I don't see it as a bug.

**Comment by bryanboza** [comment]
Fixed, tested on master and now we can ser the resolve order... New enhancement reported here: #12397
