### ISSUE TITLE
[Push-Publishing / Bundle Handler] Wrong Status on Publishing Queue after Upload Bundle

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#12226]
As part of a [client request](https://my.dotcms.com/tickets/detail.dot?id=7b5f6383-6016-44b6-b349-538793fb82bf), dotCMS 3.7.1 was displaying wrong status "Failed to send to all environments" on Publishing Queue just after Upload Bundle functionality was exercised. This misled the user to "Retry Bundle" which was still running in background, which caused another concurrency errors when accessing same bundle files from different threads. Instead, Publishing Queue should display "Publishing Bundle" status upon Uploading Bundle; Success or Failure messages should be displayed after upload-bundle process is done. Hence, this ticket has been added to fix/track this enhancement in latest versions of the product and as documentation of hotfix provided to client (in dotCMS 3.7.1).

## Expected Behavior
Publishing Queue should display "Publishing Bundle" status just after Upload Bundle functionality is exercised

## Current Behavior
Publishing Queue is currently displaying "Failed to send to all environments" status just after Upload Bundle functionality is exercised

## Context
Reproduced during client tests on dotCMS 3.7.1. Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=7b5f6383-6016-44b6-b349-538793fb82bf. This ticket may be addressed by tweaking [code of "PublisherQueueJob" that is in charge of determining publishing status on Upload Bundle use-case](https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotcms/publisher/business/PublisherQueueJob.java#L349-L362).

## Steps to Reproduce
1. Log into dotCMS as CMS Administrator
2. Go to "Site -> Publishing Queue -> Bundles"
3. Upload a big bundle of Categories

## Your Environment
* dotCMS version used: 3.7.1.
* Browser Name and version: Any Browser
* Operating System and version: Any OS
* Application Server and version: Apache Tomcat
* Database and version: Any

**Comment by agomez-dotcms** [comment]
PR Core (Master): https://github.com/dotCMS/core/pull/12228

**Comment by agomez-dotcms** [comment]
A hotfix for this issue (targeting dotCMS 3.7.1) may be found on https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12225_v3.7.1. Also, the original Support ticket may be accessed at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12226_v3.7.1

**Comment by agomez-dotcms** [comment]
PR Core (Master): https://github.com/dotCMS/core/pull/12262

**Comment by dsilvam** [comment]
PR core (P8): https://github.com/dotCMS/core/pull/12326
