### ISSUE TITLE
Problems invalidating Vanity URLs with the same URI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12222]
The cache invalidation is not working properly when we have multiple Vanity URLs **with the same URL**.

## Expected Behavior
We need refresh the cache when you un-publish some vanity 

## Current Behavior
We are having some cache invalidation problems 

SC: https://screencast.com/t/yEKF1wVM

## Steps to Reproduce (for bugs)
1. Create a vanity URL content type 
2. Create 2 vanities with the **same URI** (one with 200 action, and another with 404)
3. Edit the 404 and publish again (this to make sure is the last one edited, then should resolve this one)
4. Hit this vanity from FE
5. Now un-publish the 404 vanity
6. Hit again from FE this vanity 

Still having the 404 and should resolve the one that is published (200) 

FYI: In you try the same process but with the 200 vanity works as expected 

## Your Environment
Tested on master // chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12246

**Comment by bryanboza** [comment]
Fixed, tested on the last master // MySQL... 

FYI: If you try via curl works as expected, but we are having some problems testing via browser because we have problems with the browser cache...
