### ISSUE TITLE
Testing framework: include the ability to run PR-fired unit tests using ee code in issue branch

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12235]
This is useful when you have changes in both core and ee and the unit tests are run in the issue branch. 

It would need to check if a branch with the same name of the branch in core exists in ee and if so, use it instead of the ee jar.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13313
PR cb-tooling: https://github.com/dotCMS/cb-tooling/pull/4
