### ISSUE TITLE
Contents: URL Mapped Content with limited permissions return error 404

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12241]
Despite we allow limited users to log in to frontend pages and get access to specific contents, given a limited set of permissions over contents, assets or pages, this is not true for Url-Mapped contents, which in all cases return error 404 page in case permissions over these contents are set in order to request a frontend login.

## Expected Behavior
In the same way pages or any other contents work on frontend pages, hitting a URL Mapped Content (which ends up hitting the Content type detail page) should prompt you to a login page and, afger logging in, proper redirection is made depending on the logged in user's permissions/roles.

## Current Behavior
System returns Error 404 for URL Mapped Contents if the parent Content Type has permissions for limited users (Requesting frontend login). The system doesn't even redirect to the login page as it does for limited pages or other assets.

## Possible Solution
Make proper permissions validations on the URLMapFilter and then redirect to Login page if a match is found on data and requires that user logs in to the frontend. 

## Known Workarounds
- Set CMS Anonymous -> View for these contents, which it's not advised sometimes because users would like to restrict access to contents.
- Change the way URL Mapped contents are pulled. Instead of using the Url Map Pattern as defined on the content type, they can use a regular detail page with limited access and pass in the content identifier. This way, the page will prompt user to log in and then redirect to the content.

## Steps to Reproduce (for bugs)

1. Login to demo.dotcms.com site.
2. Go to Content Types and open News content type.
3. Go to Permissions and remove all permissions. Assign Intranet -> View and Cascade to all contents.
4. On a different browser, go to https://demo.dotcms.com/news/find-the-401k-investing-strategy-for-you (this is an existing content). An Error 404 is thrown, instead of indicating the user to log in to the frontend.
5. Go to https://demo.dotcms.com/intranet/news. since this is a page, the redirect to a login page is done without problems. Login using bill@dotcms.com account, and page will be displayed.
6. After logging in, go to https://demo.dotcms.com/news/find-the-401k-investing-strategy-for-you. Content is now available for the logged in user.

## Context
Reported by customer:  
https://my.dotcms.com/tickets/detail.dot?id=1a36e976-ce69-47ff-95cc-3e65856aef36

## Your Environment

* dotCMS 4.1.1.
* Any supported Browser.
* Any Operating System.
* Any Application Server.
* Java 8u121.
* Any Database.

**Comment by wezell** [comment]
To Reproduce:

```
hot-fries:core will$ curl --head https://demo.dotcms.com/news/intranet-news-rethinking-budget-6-counterintuitive-tips
HTTP/1.1 404 Not Found
Date: Thu, 10 Aug 2017 15:05:36 GMT
Content-Type: text/html;charset=UTF-8
Connection: keep-alive
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=57CBFEC72B2E9730662A52DD416B4E65; Path=/; Secure; HttpOnly
Set-Cookie: dmid=108325ed-b59f-460e-8215-0c28a6df7d7c; Expires=Sat, 25-Jun-2022 15:05:36 GMT; Path=/

```

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12322

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now works as expected
