### ISSUE TITLE
Category Push Improvement on Error Handling

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12249]
We should log errors in push publishing when we can't create categories on the receiver side because the category key is already used by another category parent.  Right now, if you try to push a piece of content that has a cat key on the sender that is a dupe of an cat key on the receiver, but belongs to a different parent, we simple push the content, without the category, but we do not log that the dupe category could not be created, nor added to the piece of content that was pushed.

Here is how to recreate the issue:
1) Create a Parent category with children on the sender (make sure they have category keys)
2) Add the category to a piece of content, label the content with a few categories
3) Push the content and make sure the categories push as a dependency
4) On the sender, delete the category field from the content type, and delete the child and Parent Category you had created
5) Edit the existing Topic category and add as a child, one of the categories and keys that was used by the prior category
6) Push a piece of news with the dupe Topic child category
7) Problem is that we do not error in the log.  We push the content, but we do not create the category, nor do we add the category to the content, we just push the content without the category since the category keys already exist, under a different parent on the sender.

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/541
Now we log something like this:
```
[26/09/17 15:30:02:382 CST]  WARN handler.CategoryHandler: Category found in Server with same key: 'child' but different inode; bundle: d07a2090-6a4a-431e-b580-3a6a3985befd, local: 9f7b33aa-628b-408c-9f5d-4d9b661a8091. Updating local Category to match the one from bundle.

```
