### ISSUE TITLE
Pushing Cat with already existing key in receiver does not get associated to Content

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12248]
Related to #12125 

Steps to reproduce:

1. Create cat on sender (Cat Name: mySenderCat, **Cat Key: sameKey**, Cat Keywords: myCatKeywords) under AZ-Index (Parent cat)
2. Create cat on receiver (Cat Name: myReceiverCat, **Cat Key: sameKey**, Cat keywords myReceiverCarKeywords)  under AZ-Index (Parent cat)
3. In the sender, create a new content type with a field of type 'Category' and choose AZ-Index as value.
4. In the sender, Create (Save&Publish) a new piece of content of previously created type and choose 'mySenderCat' in the field of type 'Category'
5. Push Publish the content created above.

Expected result: 
1. Since there is a cat with same key in the receiver, the properties of sender's cat (name, keywords) should be copied to receiver's cat. This is correctly happening. 
2. Pushed piece of content should have the category assigned to it. **This is not happening.**

Actual result:
Content is being pushed but there is no value for the field of type 'Category'

**Comment by agomez-dotcms** [comment]
PR (Core): https://github.com/dotCMS/core/pull/12282
PR (Enterprise): https://github.com/dotCMS/enterprise-2.x/pull/496
