### ISSUE TITLE
QA for removing cats from content and PP

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12251]
We need qa test for the following case:

1. Create a piece of content with two or more cats
2. PP content (make sure content, cats, and content-cat rels are pushed)
3. Remove one cat from content created in 1 and push again
4. Make sure content in the receiver has the proper cats related (same as sender)

**Comment by shaydotcms** [comment]
Passed QA.
Tested with existing and new categories
Also tested with default and non default language generic contents
Verified that content in the receiver has the proper cats related as in the sender

Tested locally with master branch / commit b128f4b52bceb4904f5ed258b84e2753435ed4cb
Sender: Mac 10.10 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
Receiver: Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
