### ISSUE TITLE
PP Event Listeners Included Info in Event

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12250]
We need to include some PP information in the events sent to the Listeners.

This can/might vary depending on the type of event

Things that should be included to all events:
- What's being pushed
- Dates 

AllEndpointsSuccessEvent:
- Bundle config

We also need to update the OSGI plugin example in the seeds to print this new info received

- In Addition, we need to create events for the Static Publisher as well.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13121
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/561
PR Plugin-Seeds: https://github.com/dotCMS/plugin-seeds/pull/22/files
