### ISSUE TITLE
Problem with Vanity URL cache on cluster environments

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#12258]
On cluster environments, we are getting some 404 errors only in one of the servers with some vanity URLs. Here is the error displayed in the catalina.out https://gist.github.com/oswaldogallango/daed5bf0f0faafd06b17b2ad95fdd4fd

## How to  Reproduce
To reproduce it, you need to generate a cluster environment with two servers on the same machine, then add a vanity URL on the first server, then test on the front end of the second server if the vanity work, and after test in the first server.

Then add two vanity URLs in the first server and again test that both vanities works on the second server (front end) and then in the first server. Generally on the first server, only one of the two vanities work and the second throws a 404 error on that server.

## Your Environment

* dotCMS version used: 4.2.0
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version: 8
* Database and version: postgres
* Application module (if apply):

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12289

**Comment by bryanboza** [comment]
Fixed, tested with a cluster in the last master // MySQL
