### ISSUE TITLE
Static Push can not push to some regions

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#12267]
Static configuration as follows:

```ini
aws_access_key=<REDACTED>
aws_secret_access_key=<REDACTED>
aws_bucket_name=prod-ohio-static.<REDACTED>.dotcmscloud.com
aws_bucket_region=us-east-2
```

https://gist.github.com/chrismccracken/cde1973cf86af04d920d6096dd7420ba

**Comment by chrismccracken** [comment]
Also, in this case the Static Published kept aggressively trying to republish even though it was never going to success. Error handling behavior is tough to get perfect, but is this case where we get a 400 from the AWS S3 API it should just fail.

**Comment by oarrietadotcms** [comment]
I think the problem could be that we are [creating a AmazonS3Client](https://github.com/dotCMS/enterprise-2.x/blob/master/src/main/java/com/dotcms/enterprise/publishing/storage/AWSS3Storage.java#L47-L56) without specifying the Region and then the [headBucket method](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#headBucket-com.amazonaws.services.s3.model.HeadBucketRequest-) says that:

> ... if the bucket is in a different region than the client is configured with 

We can use this method: [setRegion(Region region)](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#setRegion-com.amazonaws.regions.Region-)

**Comment by brentgriffin** [comment]
might be related to https://github.com/dotCMS/core/issues/12187

**Comment by nollymar** [comment]
**PR Core:** https://github.com/dotCMS/core/pull/12320
**PR Enterprise:** https://github.com/dotCMS/enterprise-2.x/pull/502
**PR dotcms-libs:** https://github.com/dotCMS/dotcms-libs/pull/31

**Comment by nollymar** [comment]
**Important for testing:** Different static push scenarios where content is pushed to:
* Several endpoints in different regions, including us-east-2
* Endpoints with non-existing/existing buckets

Also, please consider to push more than one host and multilingual content

**Comment by dsilvam** [comment]
PR Enterprise (master): https://github.com/dotCMS/enterprise-2.x/pull/503

**Comment by shaydotcms** [comment]
Passed QA. Successfully pushed content to different regions such as us-east-2 / us-west-2 / ca-central-1 / sa-east-1

**Comment by nollymar** [comment]
A new change was required to solve this problem:
https://github.com/elastic/elasticsearch-cloud-aws/issues/242

PR Core: https://github.com/dotCMS/core/pull/12446
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/522

It also fixes these issues:
https://github.com/dotCMS/core/issues/12429
https://github.com/dotCMS/core/issues/12430

**Comment by dsilvam** [comment]
PR ee (master): https://github.com/dotCMS/enterprise-2.x/pull/523

**Comment by dsilvam** [comment]
Retest this after upgrade of Hazelcast

**Comment by shaydotcms** [comment]
Passed QA. Successfully pushed after Hazelcast upgrade to different regions such as us-east-2 / us-west-2 / ca-central-1 / sa-east-1
