### ISSUE TITLE
Need remove some characters from the content properties tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12271]
We are having some extra characters when you try to see the content type properties

## Expected Behavior
When you try to edit some content type, in the type field, we need show just the content type, and remove the **"%>"**

## Current Behavior
We have this extra characters **"%>"**
SC: https://www.screencast.com/t/IjGV3wpvxID0

## Steps to Reproduce (for bugs)
1. Login 
2. Go to content types 
3. Try to edit some content type 
4. Go to the properties tab 

## Your Environment
Tested on master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12288

**Comment by bryanboza** [comment]
Fixed, tested in the last master
