### ISSUE TITLE
Timestamp inconsistency 

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#12276]
https://my.dotcms.com/tickets/detail.dot?id=79cb9c1e-d7e1-45b7-9c49-bd4dd026fcea

Setting the timezone of dotcms through the admin console doesn't consistently change  (new Date gets altered but preparedStatement.setObject(timestamp) ends up saving in previous timezone).

In a cluster environment this can lead to failure of nodes to recognize each other and to sync ES/Cache.

Daniel Silva is working on a hot fix for this. 

* dotCMS version used: 4.1.1
* Database and version: PostGRE, MySQL

**Comment by dsilvam** [comment]
PR core: https://github.com/dotCMS/core/pull/12308
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/499

**Comment by DeanGonzalez** [comment]
Added to fixes in changelog: https://auth.dotcms.com/docs/latest/changelogs#release-4.2.0
