### ISSUE TITLE
Can not edit hidden fields of a Form

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#12285]
## Expected Behavior
From the Content Type portlet, you should be able to edit the value of a hidden field.

## Current Behavior
If you create a new Form you can not edit the values of the fields created by default (form title, form email, form return page)

## Steps to Reproduce (for bugs)
1. Create a new Form
2. Set a value for the form title field. (click over the edit field)
3. Check the field value (clicking again over the edit field).

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12331

**Comment by bryanboza** [comment]
Fixed, tested on master // FF
