### ISSUE TITLE
[core] : Link Checker feature incorrectly flagging internal links when contentlet and link live under different Site

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12298]
Reported via Support: https://my.dotcms.com/tickets/detail.dot?id=8151135f-11d2-44cb-969a-d224a4a15cfc
Reproducible in https://demo.dotcms.com/c
Reproducible in dotCMS 4.1.1

The Link Checker process is incorrectly flagging **internal links** as invalid when both the contentlet containing the link and the link itself live in different sites.

## Expected Behavior
The Link Checker tool should report internal and external links that are indeed broken.

## Current Behavior
The Link Checker tool is correctly handling external links. However, some internal links might be incorrectly flagged as invalid under specific circumstances.

## Possible Solution
N/A

## Known Workarounds
There are two workarounds at the moment:
1. Have the contentlet and the internal link in its WYSIWYG live under the same site.
2. Use a third-party link checker tool.

## Steps to Reproduce (for bugs)
1. Log into https://demo.dotcms.com/c
2. Create a new Content Type called "My New CT" which has **ONLY 1 FIELD**: a WYSIWYG field.
3. Create a new content based on the new Content Type created before. In the WYSIWYG field, add a link that points to ``/resources/res-documents/dotCMSCheatSheet.pdf``. Note that this file lives inside the "demo.dotcms.com" site.
4. Go to the **Content > Link Checker** page, select the "My New CT" content type in the drop-down and make sure the page is not displaying any results.
5. Click the **Run Check Now** button and wait for the process to finish. You can tail the ``dotcms.log`` file and wait until you see a message similar to this one:
```
INFO linkchecker.LinkCheckerJob: Finished checking for broken links. Processed 115 contentlets. Found 12 broken links
```
6. Make sure the "My New CT" content type is selected, and click the **Refresh** button in the **Link Checker** page. You will see that the link is being flagged as invalid, although it's not.

## Context
It is confusing for customers using the Link Checker tool to see contentlets flagged with invalid links when they are not. This is the current behavior:

The contentlet is created under the "SYSTEM_HOST" site because there's no "Site or Folder" field in the Content Type definition. The PDF file referenced in the internal link lives under the "demo.dotcms.com" site. In order to check for invalid links in a WYSIWYG, the Link Checker API uses the site ID **that the contentlet lives in** to determine whether the referenced file exists or not. However, in this case, both the contentlet and the file live in different sites.

The Link Checker API will query the ``identifier`` table to determine if the file referenced by the internal link exists or not. For example, for this link: ``/resources/res-documents/dotCMSCheatSheet.pdf``, the query will be:
```sql
SELECT * FROM identifier WHERE parent_path = "/resources/res-documents/" AND asset_name = "dotCMSCheatSheet.pdf" AND host_inode = "SYSTEM_HOST"
```
However, this query **will not return any data as the value of the host_inode is incorrect**. Remember that the contentlet does live under "SYSTEM_HOST"; but, the referenced file in the URL lives under "demo.dotcms.com". For the query to work correctly, the host_inode must be changed:
```sql
SELECT * FROM identifier WHERE parent_path = "/resources/res-documents/" AND asset_name = "dotCMSCheatSheet.pdf" AND host_inode = "48190c8c-42c4-46af-8d1a-0cd5db894797"
```
A new approach must be defined that will allow the API to have access to the site that the file lives in when the site of the contentlet is "SYSTEM_HOST".

## Your Environment
* dotCMS version used: dotCMS 3.6.0, 3.7.1, and 4.1.1
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Link Checker.

**Comment by jgambarios** [comment]
If the Contentlet lives on the SYSTEM_HOST we need to try to resolve the relative file asset path using the Default Site as File Assets can **NOT** live under the SYSTEM_HOST

**Comment by bryanboza** [comment]
Fixed, now we are trying to resolve the relative paths ONLY in the default host. If now will added as invalid link in the link checker...
