### ISSUE TITLE
Quartz job error setting permissions to content types

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12305]
We are having a quartz error, when you set individual permissions to content types

## Expected Behavior
We should validate this,  and catch the error, also be able to set the permissions without problems 

## Current Behavior
We are having this error setting the permissions
ST: https://gist.github.com/bryanboza/d27c311491ad9b22afce64719f646094

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types and try to edit some one 
3. Go to the permissions tab 
4. Try to set individual permissions
5. Select the reset cascade permissions and apply changes  

## Your Environment
Tested on master // postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12307

**Comment by bryanboza** [comment]
Fixed, now i am unable to reproduce thi case in the latest master
