### ISSUE TITLE
Upgrade jasper reports lib version

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#12301]
From client:

> I see that dotCMS version 4.1.0 comes now with a repackaged version of jasper reports (dot.jasperreports-3.5.0_1.jar), when I look into the jar file, I don't see any of the classes repackaged and we have a requirement to use jasperreports-4.5.0.jar.
> 
> Would it be possible to upgrade this jar?

Client ticket: https://my.dotcms.com/tickets/detail.dot?id=0e39a0eb-decf-42da-a359-46609e487915

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/issues/7836
https://github.com/dotCMS/core/issues/1738
