### ISSUE TITLE
Permissions error with content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12306]
Unable to see the contents after set different permissions to limited users.

## Current Behavior
By default if you set permissions to some limited user in the content type, this user should be able to see the content type and their contents. 
SC: https://screencast.com/t/dTUCJDZ6ElC

Also we don't have assigned permissions to the users by default in the starter. But if you apply again the same permissions to some limited user, you see the content type, but not their contents 
SC: https://screencast.com/t/i2YT5wL3I

## Steps to Reproduce (for bugs)
1. Create a new content type and set individually permissions to some limited user (chris publisher)
SC: https://screencast.com/t/dTUCJDZ6ElC
2. Login as Chris Publisher and try to add a new content to this content type (you must have an error, **you need add children permissions over the host**)
3. Come back as admin, go to users, set the selected limited user (chris publisher) and check the permissions... https://screencast.com/t/AiSW4tIeqim5
4. Set the permissions to publish content over demo site... https://screencast.com/t/ahap2sCh9I
5. Login as Chris Publisher again and try to add a new piece of content (now you should be able to add without problems)
6. Back to admin, remove the added permissions and leave as default again... https://screencast.com/t/AiSW4tIeqim5
7. Login as Chris again and try to see the content type in the content search 

## Your Environment
Tested on master // Postgres // Chrome

**Comment by wezell** [comment]
@DeanGonzalez Please get with Bryan and see if this is a real issue.

**Comment by bryanboza** [comment]
Here the SC: https://screencast.com/t/CqttTwD5p

**Comment by DeanGonzalez** [comment]
To reproduce:

Create a new content type with a host or folder field

Permission a USER to the content type and to demo.dotcms.com with:

1) Add Children
2) Add Content/Files as children of the host

Now login as the limited user and add a piece of content and save with host/folder value set to demo.dotcms.com

Now as admin user, edit the user again and take all USER permissions off demo.dotcms.com, but leave the Content Type permissions set to Publish.

Now login as the limited user again and go to the content search manager.  Not only can the user not see the content (which is expected) but no "Add New Content" button displays at all.  The content Search manager is broken and there are errors in the log.  The limited user should still be able to attempt to add new content, but the host/folder field should no longer have a setable value.  But the content search view should not be broken - that is the bug - we are not catching/handling something properly.

**Comment by erickgonzalez** [comment]
Unable to reproduce because we are hitting a new issue before this:
When you go to the Users Portlet (or the Roles/Tab Portlet), select any and navigate to the Permissions Tab, nothing is showed just the loading icon (5 yellow points). Nothing in the dotcms.log but on the browser console appears **Session is closed** could be related to the new annotations with AOP?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12447

**Comment by bryanboza** [comment]
We still having problems here, now after remove the add children permissions in the site, I should be able to see the contents of the content type(CT) because I have permissions over the CT.
Then I just should have an error when I try to add some content.... But right now I am able to see the contents created by the limited user but we lost the titles value and shows Unknown: 
<img width="1612" alt="title" src="https://user-images.githubusercontent.com/2641437/29946783-e5f48844-8e63-11e7-9f69-2e9f5f604d84.png">

**Comment by bryanboza** [comment]
Also if you try to create a new content via REST, and you don't have permissions to add in the content type, we are sending the follow error to the log:

```User: anonymous doesn't have write permissions to Contentlet: Unknown```

Instead this **"Unknown"** we should show the name of the content type

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12504

**Comment by bryanboza** [comment]
Fixed the original problem, we have new cards related to permissions, need retest after this fixes

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgres // Chrome

**Comment by bryanboza** [comment]
Unable to retest the original problem, the login as feature isn't working

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
