### ISSUE TITLE
Create the .required style 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12311]
We need add some style to the .required, this to be consistent with the required signals through the system.

![image](https://user-images.githubusercontent.com/2641437/29181836-ddd078a4-7db9-11e7-8635-e3cb57c37b79.png)
Also we need apply some styling to the existing required dialog: https://www.screencast.com/t/JyhjFL3Lj

## Expected Behavior
We need use the same style in all the cases 

## Current Behavior
We are using different styles in all the system 

https://www.screencast.com/t/JyhjFL3Lj
https://www.screencast.com/t/F9r9Qb6sIG
https://www.screencast.com/t/93OhRbGKlQt
https://www.screencast.com/t/ccv2qAxioz

## Your Environment
Tested on master // postgres

**Comment by fmontes** [comment]
### What to do:

1. Create a ```.require``` class in [this file](https://github.com/dotCMS/dotcms-dojo-theme/blob/master/scss/backend/dot-admin/forms/_base.scss) style to be as close to this icon (use font-awesome for the icon

<img width="175" alt="screen shot 2017-08-21 at 4 43 31 pm" src="https://user-images.githubusercontent.com/751424/29541224-f741e2bc-868f-11e7-900a-d363111277b9.png">

2. Style the tooltip to be as close as this: https://www.screencast.com/t/F9r9Qb6sIG but keep it "flat", so fix the height and add the arrow on the left. (Check if there is a class for the position of the arrow"

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now looks better
