### ISSUE TITLE
We are showing the forms hidden fields in FE

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12312]
Related to #12285, #12019 

We have problems when you add a new form to some page and then try to add a piece of content from FE, this because by default we have some hidden fields in the forms, and we are showing this ones in  FE

SC: https://screencast.com/t/Az0yGiPY

**FYI: I tested on 3.x versions and works as expected, also tested adding a hidden field to some content type and then add to the page and works fine** 

## Expected Behavior
The hidden fields should now showed in FE

## Current Behavior
We shows those fields 

## Steps to Reproduce (for bugs)
1. Create a new form 
2. Add this form to a content page
3. Try to add a piece of content from FE to this page 

## Your Environment
Tested on master // Postgres // Chrome

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12354

**Comment by bryanboza** [comment]
Fixed, tested on master // FF // MySQL
