### ISSUE TITLE
Add Regex Matcher to new vanity urls

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12315]
We need to be able to support URL rewrites, e.g.

We need to support url rewriting with our new Vanity URLs.  basically, we should use regex matchers to do the find and replace on the matching $ variables

```
    <rule>
        <from>^/some/olddir/(.*)$</from>
        <to type="redirect">/very/newdir/$1</to>
    </rule>
```
Means `/some/olddir/testing/here.html ---> /very/newdir/testing/here.html`

```
<rule>
        <from>^/products/([0-9]+)$</from>
        <to>/products/index.jsp?product_id=$1</to>
    </rule>
```

```
/en/(.*)$
/$1?language_id=1
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12349

**Comment by bryanboza** [comment]
Fixed, tested in the last master using this regex "/am/([a-e]+)/([1-6]+)" and works as expected, now we are matching without problems

**Comment by wezell** [comment]
We need to be sure that we are not just matching, that we are replacing.  The mailinglist had a good example of why we need this to work this morning:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dotcms/sss7kkw9Vgw/QgyKnRvXDAAJ

We need to make sure Chris's example works

**Comment by wezell** [comment]
@bryanboza I just tested this and it works as expected.  Good job.

**Comment by wezell** [comment]
![screen shot 2017-08-21 at 1 27 05 pm](https://user-images.githubusercontent.com/934364/29531086-fb581f58-8674-11e7-9e44-43f3052b9eae.png)
