### ISSUE TITLE
Backend users should not 500 error on pages whose templates parse a CMS Anonymous .vtl file

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12317]
We introduced this 500 error when we made dotParse restrictions tighter on backend roles.  This needs an adjustment to avoid major upgrade issues.  These are the following adjustments that we can make to avoid backend pages becoming unreachable.

![500error](https://user-images.githubusercontent.com/1569167/29191607-8e6eac1e-7ddb-11e7-9d4d-3f1794f2e1c0.jpg)

1) If a file being dotParsed is permissioned with CMS Anonymous, then render the file (like a header or footer.vtl that is marked with CMS Anonymous - which is pretty standard)

2) Even if the file being parsed does not have CMS Anonymous, nor the user's role, instead of 500 on the whole page, merely do not render that file, but allow the rest of the page to load, so that the areas of a page that the DO HAVE PERMISSIONS TO, can still be reached (containers, etc.), and modified.

If we make pages unreachable suddenly by backend users after upgrade, just because they do not have permissions to a .vtl file that is called in a header or footer, this will greatly hinder the upgrade process, especially for large clients.

**Comment by wezell** [comment]
To test - from the backend try to edit a page with a limited user who has access to that page and the theme .vtls only have CMS_ANON=read.  In 4.1.1, this will fail as a 500 in EDIT_MODE.  With the attached fix, the page will render in EDIT_MODE

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12318

**Comment by jgambarios** [comment]
**Note to QA:** As part of this ticket we need to re-test https://github.com/dotCMS/core/issues/11542

**Comment by DeanGonzalez** [comment]
I tested this case and also #11542 - both now working as expected
