### ISSUE TITLE
No way to view version number on backend (without logging out)

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#12335]
Since release 4.0, the only place the dotCMS version number is displayed is on the login screen.  So there is no way to find out what version you're running once you're logged into the back-end.

## Expected Behavior

There should be some way to view the dotCMS version number after you login to the back-end.

## Current Behavior

The dotCMS version is only displayed on the login page.  Once you login to the back-end there is no way to view the version number.

## Possible Solutions

* Ideal: Add an About popup, accessible from one of the following:
    * The logged in user menu (top right of every screen).
    * The "+" menu (top right of every screen).
    * The Maintenance tool (as a new tab).
* Alternate: Set the version number in an environment or system variable, so it can be viewed in the System Info tab (in the Maintenance tool).
    * This is a little more convoluted, but might be alot faster to implement.

## Known Workarounds

1. Logout and view the version number on the login screen.
2. Launch an incognito window to display the login screen.

## Context

In versions prior to 4.0, the version number was visible from the user menu.  This functionality was removed in 4.0, and has been asked about by multiple customers, both in training and in support calls.

## Your Environment

* dotCMS version used: 4.x
* Browser Name and version: All
* Operating System and version: All
* Application Server and version: All
* Java Brand and version: All
* Database and version: All

**Comment by john-thomas-dotcms** [comment]
@brentgriffin pointed out that if a client customizes the login page, then the version number won't even show there - which means in that case the version number isn't shown anywhere.  So we may want to consider addressing this before we run into that case from a customer.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12345

**Comment by dsilvam** [comment]
PR core (master): https://github.com/dotCMS/core/pull/12346
