### ISSUE TITLE
Categories are removed on Page as Content when using a workflow

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#12333]
Client ticket:
https://my.dotcms.com/tickets/detail.dot?id=ea211e53-7345-4860-996a-028e8a529561

## Possible Solution
See commit below.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Go to Types & Tags -> Workflow -> Add Workflow Scheme.
2. Name: 'Automated Save & Publish' -> Save -> Click on New scheme.
3. Add Workflow Step -> Name : Published - > Add
4. Add Workflow Action for Published
4.1 Name: Save & Publish, Save Content: True (check), Who can use: Admin, Assign To: Current User, Next Step: Published -> Save.
4.2 Add "Unlock Content" Sub-action.
4.3 Add "Publish Content" Sub-action.
4.4 Save.
5. Edit Workflow Scheme: Mandatory: True, Default Action: Save & Publish -> Save
6. Go to Types & Tags -> Content Types -> Add New Content Type.
6.1 Type: Page, Name: Page with Categories, Workflow: Automated Save & Publish -> Save.
6.2 Add New Field -> Display Type: Category, Label -> Topic, Category: Event Types -> Save
7. Go to Content -> Search -> Type: Page With Categories -> Add New Content.
7.1 Title: Test Page, Template: Blank, Cache TTL: 0
7.2 Go to Advanced Properties -> Add 2 Categories to Topic.
7.3 Save and Publish.
8. Go to Page Properties and check that Categories(Topic) are still there -> Cancel.
9. Lock for Editing -> Save & Publish.
10. Go to Page Properties: Categories are NOT there.

## Context
We use this [checkin from the WorkflowResource](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/WorkflowResource.java#L163) and inside the method we [send the categories as a new ArrayList](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L2571).

## Your Environment

* dotCMS version used: 3.6.2 (client), master

**Comment by oarrietadotcms** [comment]
By sending the null as an extra param, we use this [checkin implementation that find the Categories from DB](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L2590-L2592) and save them again.

**Comment by dsilvam** [comment]
This is only for 4.3.0 cause it all checkin methods were refactored in 5.0

**Comment by shaydotcms** [comment]
Passed QA.
Categories are showing on Page as Content when using a workflow
![image](https://user-images.githubusercontent.com/8741846/36228710-95515506-119a-11e8-8666-8fb567fd9d8f.png)

Tested on release-4.3.0 branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8.6

**Comment by shaydotcms** [comment]
Not required for 5.0
