### ISSUE TITLE
ES re-inits on CMS cluster topology change when AUTOWIRE_CLUSTER_ES=false

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#12347]
When we have configured for autowire to NOT manage ES cluster membership (for external ES), it seems that when a CMS server joins/leaves the cluster we are still re-init'ing ES, which we should not need to do and could cause or contribute to an outage or degraded cluster performance.

https://gist.github.com/chrismccracken/7ff20120365298eb5019a1b9a7fb5843

**Comment by dsilvam** [comment]
PR core (master): https://github.com/dotCMS/core/pull/12348

**Comment by shaydotcms** [comment]
Passed QA.
Error reported is not showing anymore. Tested using following steps:

- Configured 3 nodes in a cluster environment using manual cluster configuration + hazelcast embedded for cluster and cache.
- Set up heartbeat on each node = 3mins
- Started up all 3 nodes 
- Confirmed that information was being replicated
- Shut down 2 nodes
- Checked logs but no relevant errors
- Started up those 2 nodes again and verified that information was being replicated among the 3 nodes.

All 3 nodes were using an upgrade dotcms instance from 3.6 to master
Mac 10.10 / Win7 / Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
