### ISSUE TITLE
OSGI Example of the new annotations

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12343]
We need to create an OSGI example in the Plugin Seeds repository showing the use of the new three annotations: https://github.com/dotCMS/core/issues/12100#issuecomment-321083547

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/plugin-seeds/pull/12

**Comment by bryanboza** [comment]
Fixed, tested with the new plugin added to the plugin-seeds folder called "aop" and is compiling and upload as expected...
