### ISSUE TITLE
Search Box does not work on FileBrowserDialog box

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#12353]
There is an issue with the FileBrowserDialog that is not allowing to use the filter functionality.
When you try to insert an image in a WYSIWYG field the select file windows is not filtering the results displayed when you put some value in the filter box. Same thing happens when you use an Image or File field. The filter for some reason is not being called when you write some text

![image-plugin-filter](https://user-images.githubusercontent.com/1569280/29422780-47ca97f2-8347-11e7-9b86-b12446fd7ec5.png)

## Expected Behavior
When you insert an image in a WYSIWYG field and try to filter the results in the select file windows, the values displayed should be those that have a match with the string put it on the filter window.

## Current Behavior
When you insert an image in a WYSIWYG field the select file windows is not filtering the results displayed, when you put some value in the filter box. Is displaying the results available

## Steps to Reproduce (for bugs)

1. Login into the back end
2. go to the content search tab
3. add a new Content Generic contentlet
4. In the WYSIWYG field click on insert image option
5. click on the source button 
6. select on demo site the resources/res-images folder
7. write in the filter box: rome
8.  the values displayed are the same. no filter is applied

## Context
This issue was reported by the client in this ticket https://my.dotcms.com/tickets/detail.dot?id=e39fd65d-8945-4137-8d4e-2ceeb3518592

These other two issues are related to the same problem
https://github.com/dotCMS/core/issues/12167 and https://github.com/dotCMS/core/issues/11574
## Your Environment

* dotCMS version used: 3.7, 4.1.1, 4.2.0

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12356

**Comment by bryanboza** [comment]
Fixed, tested on the last master // MySQL // Chrome
