### ISSUE TITLE
Network tab showing all nodes in red 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12361]
If you start a server up with a license.dat, it will assign a server_id and its status in the Network tab will be green. Then, if you shutdown the server, remove the server_id.dat and start the server up again, the tab has two entries for the same ip (one green and one red), this is correct, however, if you do the same a third time (shutdown the server and delete the server_id.dat), the tab shows three rows in red for the same server

In addition we need to include the license id per node 

Another issue solved: when a platform license is used and some nodes are in red, the fields in the table show "undefined"

**Comment by nollymar** [comment]
These PRs: https://github.com/dotCMS/core/pull/12384 (Core) https://github.com/dotCMS/enterprise-2.x/pull/510 (License) solve two problems:

- Include the license id per node

- When a platform license is used and some nodes are in red, the fields in the table show "undefined"
