### ISSUE TITLE
Push publish log entries do not contain enough details when pushing to multiple endpoints

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12376]
I am pushing to an environment with three different endpoints.  In all of the log entries, the level of detail seems limited to only the environment - no log entries for specific endpoints.

## Expected Behavior

I should be able to see some logging for specific endpoints.  In my case, I had three endpoints.  One succeeded, one failed, and one is still "Waiting for Publishing".  There are no log entries for success or failure, only that the status is "Waiting for Publishing" - which I understand is the status of the environment but visibility into the specific endpoint events are worth logging.

![image](https://user-images.githubusercontent.com/3208956/29488188-5b4f65de-84cb-11e7-8186-1e86610acd6d.png)

At the very least, I would expect to see:
* log entries when we begin sending a bundle to a specific endpoint
* log entries when we detect success or failure for each endpoint

Ideally, I would see:
* log entries for each endpoint when in "PUBLISHING_BUNDLE" status
* log entries for each endpoint when in "WAITING_FOR_PUBLISHING" status

Here are examples of logs:  https://gist.github.com/brentgriffin/a92d9534831c14f71df96de034d9644f

**Comment by dsilvam** [comment]
Noisy log:

![pasted image at 2017_08_22 11_47 am](https://user-images.githubusercontent.com/1576794/29577551-74bf099e-8731-11e7-972c-3f0bb1820ff1.png)

Info can be presented in one line

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12409
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/511
