### ISSUE TITLE
Relationships: Cannot sort contents to be related with new/existing one

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12381]
We're able to relate contents, however, the dialog box that opens the contents a logged-in user does not allow sorting according to the searchable fields on the list headers. 

## Expected Behavior
A logged in user should be able to sort contents according to its searchable fields, as per the list headers suggest it can be done.

## Current Behavior
Clicking on a list header wipes out the entire dialog box, and even if you close/re-open it, contents are never going to be listed unless you entirely exit the Contents portlet and go back again.

## Possible Solution
Implement the fix as per this ticket: https://my.dotcms.com/tickets/detail.dot?id=5082497f-0da5-4f20-94d7-8aa36703638f

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Go to Content Search portlet and Add a new Blog entry.
2. Go to Relationships tab and click on Relate, for the Blog-Comments relationship.
3. Once the dialog box opens, you should be able to search all Comments under the selected Language.

![screen shot 2017-08-21 at 10 12 25 am 2](https://user-images.githubusercontent.com/1717110/29528471-62ad4e88-8659-11e7-95ad-f2e364aa07e4.png)

4. On the list headers, click on "Title" so you can sort contents by title. All contents disappear. 

![screen shot 2017-08-21 at 10 12 29 am 2](https://user-images.githubusercontent.com/1717110/29528481-72b611ca-8659-11e7-8719-0fcfa602681f.png)

## Context
Despite this was reported on this ticket https://my.dotcms.com/tickets/detail.dot?id=5082497f-0da5-4f20-94d7-8aa36703638f the proposed fix was never committed and merged to master. 

## Your Environment

* dotCMS version used: 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App Server.
* Java Brand and version: Java 8u121.
* Database and version: Postgres, SQL Server
* Application module (if apply): N/A.

**Comment by bryanboza** [comment]
Fixed, now we are able to sort, but we need some styling help here, new issue created here: #12440

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12382 

Thanks for following up, @bryanboza
