### ISSUE TITLE
Date / Time Issues - was Bundle appears to be stuck in "Starting" state

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12393]
Context:  Dynamic pushing to an environment with three endpoints.

While waiting for a small bundle to finish publishing, force pushed an entire site to the environment - initiated this action at 22:21PDT.  Since the other bundle was in the "WAITING_FOR_PUBLISHING" state, the full site bundle entered the "Starting" state at 22:24PDT.

At 22:36PDT, the initial small bundle is logged as having successfully published.  7 hours later, the full site bundle is still in the "Starting" state and does appear to have started any of the bundlers.  It seems to be stuck in "Starting" state.

dotcms.log and dotcms-pushpublish.log files will be made available.

**Comment by brentgriffin** [comment]
Secure links for log files:
[dotcms.log.gz](https://drive.google.com/open?id=0BwenB5wlEw5mZlhLRzRDVTAzbzA)
[dotcms-pushpublish.log.gz](https://drive.google.com/open?id=0BwenB5wlEw5ma3BfdURLNG4ybDA)

**Comment by wezell** [comment]
brent.griffin
think I just figured out our bundles wanting to wait for 24 hours to publish


[4d] 
brent.griffin the right click push publish dialog prepopulates with the current date and time - will need to wait till tonight to verify but I think the browser must be populating the date based on the local browser date but the time seems to be based on the server time - i.e. right now it populates 9/8/2017 11:54AM


[4d] 
chris.mccracken I don’t see the problem, that’s what time it is :stuck_out_tongue:


[4d] 
brent.griffin
so, my guess is that last night after midnight, it grabbed my date 9/8 and grabbed the server time which was 22:xx and that became the publish date


[4d] 
chris.mccracken Yeah, all the servers are set to Pacific time except the DB which is UTC


[4d] 
brent.griffin
right, so it did what I must have told it - think the default in the UI is wrong / messed up in this case - will test this weekend to find out


[4d] 
brent.griffin
i think the moral of the story is that nobody should be push publishing through the UI after midnight local time :slightly_smiling_face:


[4d] 
chris.mccracken Lol


[4d] 
john.thomas Let's just say this is a corner case that only devs will ever stay up late enough to find :stuck_out_tongue_closed_eyes:


[<1m] 
daniel.silva
@will
