### ISSUE TITLE
Make sure only the creator of the connection is the one that close it on LocalTransactions and CloseDb

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#12402]
Currently we have an issue with the connection handling, basically the connection could be share between calls since it is place in the thread local, some of the new patterns introduced such as the CloseDB are intensive closing connections as we want, but they have to be smart enough to close just connections that were created by the current callback. The same for LocalTransactions

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12403
