### ISSUE TITLE
Cancelling changes to a Template makes content disappear on the page

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12410]
Tested on Master.  This is what the page looks like after editing a template, adding a row, and clicking cancel (which should mean that nothing has changed)

Steps to reproduce:

1) Open any starter page
2) Edit Template and add a row, assign a 50/50 split or whatever
3) Click cancel (which means no change should have been made at all)
4) **Bug:** when you return to the page all content disappears.  To get the content back, you have to go to the site browser and re-open the page from there.

screencast: https://screencast.com/t/B7ktPP74T2D

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12425

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes on master... Fixed

**Comment by DeanGonzalez** [comment]
Passed QA for me too
