### ISSUE TITLE
"What's Changed" Highlighting is not cleared after publishing the page

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12413]
Tested on latest master
Problem: "What's Changed" Highlighting is not cleared after publishing the page AND all unpublished content on the page.

Steps to reproduce:
1) On a clean starter, go the About US->Our Team page
2) Add a new piece of generic content and publish it
3) Using the inline editing tool (NOT clicking on edit button), just click into the body text of the generic content and add a change
4) Click on the Preview tab and "What's Changed"
5) Click on Publish Page and publish the assets on the page
6) Bug: Click on "What's changed" again, and it willl still show the highlighted change, even though the content has already been published.  Something is not getting cleared when the page (and all content on the page) is being published

Screencast: https://screencast.com/t/TbSxSEkDu

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12442

**Comment by DeanGonzalez** [comment]
Passed QA, tested with single content, multiple contentlets.  Working as expected now.
