### ISSUE TITLE
Make the language variables works by site

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12417]
Since now the language variable are content, maybe we can handle the this values by site, this to allow have multiple values depending the site 

Here if you use system host, this will be reflected in all the sites 

## Expected Behavior
We should be able to use different languages variables depending the site 

## Current Behavior
This works just by language, not by site 

## Steps to Reproduce (for bugs)
1. Create a new key/value content type "Language Variable"
2. Add a site/folder field to the same content type 
3. Try to add the same key/value but in different sites 

## Your Environment
Tested in the last master // MySQL // FF

**Comment by wezell** [comment]
For now, we will stick with the current behavior, but this could change future forward.
