### ISSUE TITLE
Unable to add content to Vanity URL content types via REST api

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12415]
We are having an exception trying to set a string value as long in the order field 

## Expected Behavior
We need be able to add content to this content types without problems

## Current Behavior
We are having an error and we are unable to save the content 

ST: https://gist.github.com/bryanboza/7789571a70397724e8685d181450e4cb

## Steps to Reproduce (for bugs)
1. Create a new vanity content type  "Vanity URL"
2. Using this REST ``` http://localhost:8080/api/content/publish/1```
3. Try to send this values 
```
{"stName":"Vanityurl", "title":"Vanity Test", "site":"All Sites", "uri":"/vanitytest", "action":"200", "fordwardTo":"/about-us", "order":"0"}
```
4.  Check if the content is saved 

## Your Environment
Tested on master // MySQL // FF

**Comment by jdotcms** [comment]
The example has a typo, this is the right one:
```
{"stName":"Vanityurl", "title":"Vanity Test", "site":"All Sites", "uri":"/vanitytest", "action":"200", "forwardTo":"/about-us", "order":"0"}
```

However even with it still getting errors

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12432

**Comment by bryanboza** [comment]
Fixed, tested on master // and now we are able to add vanities via REST without problems...
