### ISSUE TITLE
Import license pack on startup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12420]
When dotcms starts up, it should look for a license_pack.zip under the /assets directory.  If that exists, we should import that into the db for use by the cluster.

**Comment by jgambarios** [comment]
PRs: 
https://github.com/dotCMS/enterprise-2.x/pull/517
https://github.com/dotCMS/core/pull/12428

**Comment by wezell** [comment]
Two ways to import licenses in dotcms on startup.
1. put a license file (text file of a trial license for example) here on startup `/dotsecure/license/license.dat`
2. Drop a license pack (a file that matches license*.zip) in the `/assets/` folder. 

Both of these should be picked up and imported into the license repo

**Comment by bryanboza** [comment]
This isn't working in the last master

**Comment by wezell** [comment]
This works with the caveat that you cannot load a license pack with a fresh starter.  For a license pack to be picked up, the starter and /assets directory needs to be already loaded (importing a starter deletes any /assets already there).  If we want it loaded from the starter, you will need to have the license pack in the assets folder in the starter.zip
