### ISSUE TITLE
Static Push to Multiple Endpoints Seems to Get Stuck in "PUBLISHING_BUNDLE" Status

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12430]
Doing a static push to an environment with two different S3 Endpoints seems to get forever stuck in Publishing status.

Tested push of a single folder to environment with two S3 endpoints.  This is the same small folder that was used tested in https://github.com/dotCMS/core/issues/12429  and pushes in under a minute when pushing to a single S3 endpoint.

## Expected Behavior
I expected this folder to push in less than two minutes.  

## Current Behavior

I started the push around 13:23 PDT and at 19:46 PDT the log files were still logging that the bundle had a status of "PUBLISHING_BUNDLE".  The bundle still showed up on the pending tab and every minute it was logging that it was in this "PUBLISHING_BUNDLE" status.

Had to delete the bundle to get it to stop appearing on the "Pending" tab and to stop logging the status in the log files.

Will attempt again to see if I can recreate but wanted to capture this behavior first.

**Comment by brentgriffin** [comment]
So, I cleaned up S3 and the push history and retried the process two more times.  Both times worked just fine.  So this seems to be a sporadic issue.

**Comment by nollymar** [comment]
Solved on https://github.com/dotCMS/core/issues/12267
