### ISSUE TITLE
Delete Push History Appears To Only Work Once Per Page Refresh

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12431]
On System->Configuration->Publishing Environments, when the "Delete Push History" link is clicked it normally displays this dialog:
![image](https://user-images.githubusercontent.com/3208956/29738471-c50d3a38-89e8-11e7-8534-f9742a51bb3a.png)

This works fine the first time I click on the link; however, when I click on another link to delete the push history for another environment, no dialog appears.  It is unclear whether or not it is actually deleting the history or not.

If I refresh the page, the first click on a "Delete Push History" link works but no other ones after that work (without refreshing page first)

I believe the functionality and UI displayed should be the same no matter how many of those links I click on in one visit to the page.

**Comment by bryanboza** [comment]
We continue having problems, now we are unable to resolve the message key, then shows an "undefined" message,  and we are not auto hiding the message.

**Comment by bryanboza** [comment]
Fixed, some new improvements reported here: #12492

**Comment by bryanboza** [comment]
Need retest after the fix #12492
