### ISSUE TITLE
Make the dotCMS color in the angular menu configurable... 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12439]
As part of the new dotCMS enhancements, maybe we can do the dotCMS BE color configurable, this to allow the client change the preferrer color in the  angular menu etc
<img width="1612" alt="menu" src="https://user-images.githubusercontent.com/2641437/29785626-8b90ac78-8be5-11e7-903a-a4f2ded566e8.png">
... 

Tested in the last master...

**Comment by gabbydotCMS** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=35ee656f-5a7d-48e8-95c4-1a7ab8fafb91
