### ISSUE TITLE
Relationships: Sort titles need looks as clickable content

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12440]
Related to #12381 

We're able to relate contents, however, the dialog box that opens the contents a logged-in user does not look as clickable content on the list headers. We need add some styling help

<img width="1612" alt="clickable" src="https://user-images.githubusercontent.com/2641437/29786056-f2a6c4d2-8be6-11e7-8254-dc2950b7fad0.png">

Tested in the last master // chrome

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12623

**Comment by bryanboza** [comment]
Fixed, tested in the last master // chrome & FF
