### ISSUE TITLE
Push Publish is not pushing some assets by dependency

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12449]
I created a brand new page and added a new generic content type. This generic content contains an image.
When I push the page it got successfully pushed and also the content type was pushed, **however the image inside was not pushed** by dependency.

You can see here that in the receiver, the image inside the content type is broken
![image](https://user-images.githubusercontent.com/8741846/29832729-56f87484-8ca6-11e7-8c90-5bd9ea533f85.png)

So when I opened the new page in the receiver, the content type is not showing the image. 

## Expected Behavior
All files should be pushed by dependency

## Current Behavior
Images inserted inside generic content are not being pushed by dependency when the generic content is pushed

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Setup a sender and receiver server to configure push publish environment 
3. In the sender, create a new page(e.g.: "index"). Inside the page, add a new generic content(e.g.: "test generic content"). Inside the new generic content, add an image. 
4. Push the new page to the receiver.
5. Open in Preview the page, you will see that it's missing the image because it was not pushed by dependency.

## Your Environment
* dotCMS version used: 
Upgrade from dotcms_3.6 with client dataset (db and assets) to master branch / commit 1a0ba9d0e9effc6fd3489817eb7f115db1c04df0
Also tested using fresh install of master banch / commit 1a0ba9d0e9effc6fd3489817eb7f115db1c04df0
* Database and version: Sender and receiver using Postgres 9.3.5
* Operating System and version: Receiver: Mac OS 10.10.5 / Sender: Ubuntu 14.04.1
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by jgambarios** [comment]
@shaydotcms this is not a bug, we do not parse the WYSIWYG content in order search for dependencies.

**Comment by shaydotcms** [comment]
Not an actual issue, seems to be ok as we don't push assets by dependency when they are inside the ace editor

**Comment by john-thomas-dotcms** [comment]
Note: The way to make this work as a dependency is to create an image field on the content type, and include the image in the WYSIWYG by referencing the URL of the image field (rather than inserting it using the WYSIWYG editor).  Images or files inserted using the WYSIWYG field directly won't be pushed by dependency, but images and files in image/file fields will.
