### ISSUE TITLE
WebDAV: Files created with spaces return Error 404 when they're downloaded

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12459]
If files were uploaded with spaces on its name, dotCMS will preserve these attributes for the file name and title, however, its resource link and how it's mapped on data will have these spaces removed.

- File uploaded: '/about-us/test pdf.pdf'
- Resource link:  '/about-us/test+pdf.pdf'

However, for WebDAV-based operations, files are listed with their file names/titles including spaces, and once the user tries to export/download them, it returns Error 404. 

## Expected Behavior
Pulling assets via WebDAV should have the same behavior Site Browser has. Any pulled resource would attempt to make the right pull of files and make them available for content editors using WebDAV clients like WinSCP and Cyberduck.

## Known Workarounds
Update files and remove spaces.

## Steps to Reproduce (for bugs)

1. Create a file called 'pdf & test.pdf' file, and upload it to /about-us/ folder.
2. Once it's created, open the content in the backend for editing and see its resource link. Should point to `/about-us/pdf+&+test.pdf`. Once it's opened, the ampersand should resolve to `%26`, but file is going to be displayed anyway.
3. Open WinSCP or CyberDuck and connect to dotCMS via WebDAV.
4. Once authentication is successful, go to demo.dotcms.com/about-us/ folder. You'll see the `pdf &amp; test` file listed under this folder. Download it.
5. Error 404 is thrown. URL generated on WebDAV is `https://demo.dotcms.com/about-us/pdf%20%26amp%3B%20test.pdf` (spaces are replaced with %20 and &amp; is encoded as %26amp%3B).

## Context
Reported by customer 
https://my.dotcms.com/tickets/detail.dot?id=caf730ee-acc0-48a7-9a93-37da469d7791 

Reproduced on dotCMS 4.1.1

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: 8u121.
* Database and version: Any DB.
* WebDAV Client: WinSCP, CyberDuck.

**Comment by brentgriffin** [comment]
I have been unable to reproduce on 3.7.1, 4.1.1, or 4.2.2 using Cyberduck version 6.3.2 or Mac Finder for OSX 10.13.2

**Comment by brentgriffin** [comment]
based on client ticket, this problem seems to be related to WinSCP and the default encoding being 1252 (ANSI - Latin I)

**Comment by john-thomas-dotcms** [comment]
@brentgriffin it may be a WinSCP issue but I'm not sure it's the encoding.  I downloaded WinSCP and looked through the settings, and the only thing that uses the 1252 encoding is the internal editor (to display and edit the file after it's downloaded), so it seems like that shouldn't have an effect on the file name.  But they do have a setting to replace characters in the file names in the transfer settings presets:

![image](https://user-images.githubusercontent.com/13456955/33946793-89ce8f7c-dfd7-11e7-954f-92d152955280.png)

However I tried the transfer of a file with a space in WinSCP and it worked fine for me (with the default settings, including the 1252 encoding and the default setting to replace characters in the file name).

Also note that when I uploaded the file `pdf & test.pdf` to a File Asset, the `&` was removed in the file name (but retained in the file title) so the file showed as just `pdf test.pdf` in the back-end (and when WinSCP listed the files in that folder):

![image](https://user-images.githubusercontent.com/13456955/33947383-1b0f0d08-dfd9-11e7-9caf-fe27de7bd43f.png)

So it seems like maybe the example is missing a step, or maybe dotCMS allows the `&` in the file name if it's uploaded from a Linux machine or using a specific browser, but not from a Windows machine using Chrome (which is what I'm doing).

**Comment by brentgriffin** [comment]
ok from what I can tell this problem seems to be related to the ampersand and not the spaces.  I am able to recreate this issue with the latest cyberduck on demo3 and demo with a filename that has no spaces in it - i.e. "test&pdf.pdf"
