### ISSUE TITLE
Language Variables improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12451]
Reviewing the Language Variables unit tests I found some potential issues that I will address on this ticket.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12452

**Comment by bryanboza** [comment]
We still working on some language variables improvements. Waiting the final version to test

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres //  FF... We still waiting for new unique improvements, but has been reported in a separate ticket
