### ISSUE TITLE
Unnecessary re-permissioning when pushing a content type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12460]
When we push a Content type that includes a Host/folder field, it forces all the content of that type to be re-permissioned, which is an very heavy issue:

**Comment by wezell** [comment]
![screen shot 2017-08-30 at 11 23 49 am](https://user-images.githubusercontent.com/934364/29880430-bb6bb71c-8d75-11e7-9441-cd5a9519f218.png)

**Comment by dsilvam** [comment]
Note to QA: Please test doing a force push of a content, with a very large dataset, that includes a large number of contents of the same type as the content being pushed.

**Comment by DeanGonzalez** [comment]
Tested that contentlet permissions are not over-ridden when adding a host-folder field to a content type.  Now testing the push with large data set.
