### ISSUE TITLE
Contents: Having 2 or more Tab Divider fields break the Add/Edit Content form

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12471]
Tab Divider fields help us group content type fields into smaller sets of data we can organize from a UI perspective. However, there's a problem on how these objects are created and then rendered once a logged in user tries to add a content for these content types. 

## Expected Behavior
We should be able to see the Add/Edit Content without issues, and tabs should be working just fine.

## Current Behavior
There is a JS issue caused by the way Tab Dividers are created. Its field_contentlet value, set to `system_field` by default, causes a Dojo issue by the time more than one Tab Divider is present on the Content Type and then they're rendered on the backend. This makes the whole Add/Edit Content view unusable and content editors cannot create/edit contents at all.

## Possible Solution
Change the logic Tab Dividers are created and avoid reusing the same field_contentlet value on every Tab Divider field under the same content type.

## Known Workarounds
- Update the field_contentlet value to system_field + an integer value, in the same way we handle multiple occurrences of Velocity Var Names. However, this values are overwritten once the Content Type gets updated via Push Publishing tasks. 
- Delete Tab Divider fields and keep only one. 

## Steps to Reproduce (for bugs)

1. Go to Content Types.
2. For Event Content Type, add two Tab divider fields.
    - 1st Tab Divider field, called "Assets". Place it between "Link" and "Image" fields.
    - 2nd Tab Divider, called "Old Data". Place it between "File" and "Tags" fields.

![screen shot 2017-08-30 at 1 50 44 pm](https://user-images.githubusercontent.com/1717110/29892012-4285f1e0-8d8a-11e7-9868-c0bb57d07b46.png)

3. Go to Calendar tool and add a new Event content.
4. Screen goes blank and this is thrown on the browser's console.

<img width="1673" alt="screen shot 2017-08-30 at 1 41 49 pm" src="https://user-images.githubusercontent.com/1717110/29892247-2e2453ee-8d8b-11e7-8fba-82c152278451.png">

## Context
Reproduced on demo site and reported by customer: https://my.dotcms.com/tickets/detail.dot?id=77cd2b7d-4308-4af0-8d14-5bcaba053d2e

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: 8u121.
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12481

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes, tested on master // MySQL // Chrome
