### ISSUE TITLE
Extremely Slow Dynamic Push Publishing of Content with Many Relationships

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12480]
Dynamically Pushing a single piece of content with many relationships is taking way too long.

I believe that this is a combination of environmental configuration (cache) and code changes needed to address this significant problem.

Details are available here:  https://docs.google.com/a/dotcms.com/document/d/1mATRn_wYrVz87R_TnPdXT4PGVWh3kjJSUkh8NzJGx5A/edit?usp=sharing

**Comment by dsilvam** [comment]
Note to QA: This is with same dataset as reported.

**Comment by shaydotcms** [comment]
Passed QA.
Tested locally with upgrade from client dataset on dotcms_3.6 to master branch
Commit 98c13c5 on Sep 28, 2017
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
