### ISSUE TITLE
Binary field upload does not display thumbnail

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12490]
Tested on latest Master with Chrome

Adding a Binary field to a piece of content or uploading a file asset to a folder no longer displays thumbnail preview on successful upload. All previous versions did this and also displayed the edit image button so the image coud be edited before publishing the content.  See screenshots.

File Asset
![fileasset](https://user-images.githubusercontent.com/1569167/29947004-e0198752-8e64-11e7-8a60-62617a43d139.jpg)

Binary
![binary](https://user-images.githubusercontent.com/1569167/29947010-e474d162-8e64-11e7-9d24-04c6264e4bf1.jpg)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12498

**Comment by DeanGonzalez** [comment]
The original case passes, but multiple file upload is broken. https://github.com/dotCMS/core/issues/12510 I think this is result of permission changes and not necessarily changes here.. so passing this one
