### ISSUE TITLE
Delete push history enhancements  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12492]
Related to #12431 

## Expected Behavior

- [ ] As part of the UX standard all the delete transactions should have confirmation. Maybe here we need shows a confirmation dialog before delete all this data 

- [ ] By security we need log this transactions, we need include this in the user_activity.log, also in the push publish log. 

## Current Behavior
We are not requesting for a confirmation, and we are not logging nothing in our logs

## Steps to Reproduce (for bugs)
1. Login 
2. Configure the push environment 
3. Go to configuration --> publishing environments  
4. Delete the push history 

## Your Environment
Tested on master // MySQL // Chrome

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12505
