### ISSUE TITLE
Page in non default language is not showing image in content type after PP

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12494]
On a fresh dotcms instance with starter code. In the browser, I create a folder. Then I created a page which has a generic content and an image in the wysiwyg of that generic content.
Then I created the same content for a page in a **non default language**
When I push publish the folder that contains the pages and the images, everything is push successfully (pages + generic content + images), however the generic content is not showing the image on the non-default page. This issue is not happening for pages on default language.
Logs in receiver serer: https://gist.github.com/shaydotcms/e3560b9849b5ad2f949591cde75f2352

## Expected Behavior
The page in non default language should display the image included in the wysiwyg as the image and the content was pushed successfully.

## Current Behavior
Page in non default language is not showing image in content type after PP

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Setup a sender and receiver server to configure push publish environment
3. In the sender, create a new folder ("Test folder"). Inside that folder, create a page(e.g.: "index"). Inside the page, add a new generic content(e.g.: "test generic content"). Inside the new generic content, add an image.
4. Inside the same folder, create the same index page in another language (i.e.: Spanish, Italian, etc). You should also create the same generic content in that language so it can be displayed in this page. Finally add an image.
5. Push the new test folder to the receiver.
6. You should see that the folder, page, generic content and image were pushed successfully
7. Now open in Preview the page in non default language, you will see that it's missing the image, although the image was successfully pushed

## Your Environment
* dotCMS version used: 
fresh dotcms instance with starter code / commit 1a0ba9d0e9effc6fd3489817eb7f115db1c04df0
* Database and version: Sender and receiver using Postgres 9.3.5
* Operating System and version: Receiver: Mac OS 10.10.5 / Sender: Ubuntu 14.04.1
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by erickgonzalez** [comment]
Followed the steps above and the content with the images shows correctly on both lang but the error on the log still shows up, taking a look.

**Comment by bryanboza** [comment]
Fixed
