### ISSUE TITLE
Error when trying to upload Multiple Files to a folder

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12510]
Tested on latest master

Uploading multiple files to a folder is unsuccessful and throws this error in the log: 

[05/09/17 13:57:10:542 CST] ERROR business.ESContentletAPIImpl: User: system cannot read Contentlet: 

https://screencast.com/t/QtSKSn8ZEe

**Comment by erickgonzalez** [comment]
Looked at this with @DeanGonzalez and neither of us was able to reproduce.
