### ISSUE TITLE
Create New StaticBundler to publish statically to a local folder

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12521]
What will be included when the static publisher fires: - should be exactly like our TimeMachine

- Pages
- Folders
- Files/Images/Assets
- URLMapped Content
- Shorties `/dA/asdasdasdasd`
- ContentAssets
- Saas/Less

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/548
PR core: https://github.com/dotCMS/core/pull/12914

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/static-push-publishing-plugin

**Comment by DeanGonzalez** [comment]
Added the UI doc here: https://auth.dotcms.com/docs/latest/connecting-remote-servers#CustomStaticEndpoints

**Comment by DeanGonzalez** [comment]
This doc was mostly done... I think old doc got pasted over it... luckily I had a local copy: https://auth.dotcms.com/docs/latest/connecting-remote-servers#CustomStaticEndpoints
