### ISSUE TITLE
Create Listener fired after static bundling to push via SCP/sFTP

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12522]

**Comment by oarrietadotcms** [comment]
Work done here: https://github.com/dotCMS/core/issues/12250

**Comment by dsilvam** [comment]
We need a README.md for this OSGI plugin

**Comment by DeanGonzalez** [comment]
Documentated: https://authoring.dotcms.com/docs/latest/push-publish-listeners-configuration

**Comment by DeanGonzalez** [comment]
Done, and I marked that parent doc with 4.3 as well so that it would also push and retain order.
