### ISSUE TITLE
Simultaneous Logouts

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12520]
When multiple people are logged in as the same user and one of them logs out, they all logout.

**Comment by john-thomas-dotcms** [comment]
I see this one regularly when I'm logged into the demo site - I get logged out at random times.  I know what this is, but someone evaluating dotCMS won't know why so it doesn't look very good.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14028

**Comment by bryanboza** [comment]
Fixed, now we are able to navigate normally after some of the users logout
