### ISSUE TITLE
Permissions: Need validate the permissions of content before show the right click menu

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12534]
We are not validating permissions when you try to see the right click menu, then the system shows the options with the permissions that you have when you save the content and this can be changed 

## Expected Behavior
Before show the right click menu, we need validate the permissions that you have in this moment, to avoid not allowed action in case the permissions was changed 

## Current Behavior
We show some action in the right click menu, but if you change the permissions we still showing the same actions, but if you open the content, the system is showing the new actions

SC: https://screencast.com/t/1DFGFrP86

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type and just add a text
3. Add permissions to the content type for limited user to publish content (chris publisher)
4. As limited user add a new piece of content 
5. Now back to admin edit the content type, and add a new site or folder field 
6. As limited again do right click to the created content, (try to publish / unpublish) you will have some not allowed actions
7. If you try opening the piece of content you will no have permissions to do this actions 

## Context
The problem is that we still showing the options in the right click menu, based on the permissions that you have in the moment you save the content.

## Your Environment
Tested in the last master // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
See also this comment for a related issue: https://github.com/dotCMS/core/issues/12401#event-1218045374
