### ISSUE TITLE
Content API isn't respecting permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12536]
We have problems validating permissions in the content API when you try to get content via REST, this because an anonymous user can get private content. 

## Expected Behavior
We should validate if the requesting user have permissions to get the requested content 

## Current Behavior
An anonymous user is able to get content from any content type, without validate if have permissions or not 

## Steps to Reproduce (for bugs)
1. Create a new content type 
2. Add some contents to this content type 
3. Edit the content type permissions, and set permissions just to admin 
<img width="1372" alt="per1" src="https://user-images.githubusercontent.com/2641437/30180690-f8d7e14e-93cd-11e7-9e9e-37e48966fba4.png">
4. Apply cascade changes 
5.  Make sure every piece of content have the same permissions 
<img width="1372" alt="per2" src="https://user-images.githubusercontent.com/2641437/30180696-ff2602e2-93cd-11e7-9017-7842b7d958ec.png">
5. Try to get content from this content type via REST
<img width="2964" alt="per3" src="https://user-images.githubusercontent.com/2641437/30180718-11280c56-93ce-11e7-903e-547472b1c04a.png">

## Your Environment
Tested on master // Postgres // Postman

**Comment by jdotcms** [comment]
trying to reproduce it

**Comment by bryanboza** [comment]
Tested after the last changes and we still having the same problem, but to reproduce you should add some pieces of content to the content type before change the permissions... Seems the problems can be with the reset all permissions process.
To recreate: 
- Create a new content type 
- Add a piece of content 
- Go to the content type permissions and remove the anonymous permissions and add ONLY to admin user
- Reset all children permissions and apply changes
- Try to get the content via REST

**Comment by bryanboza** [comment]
Ok, after test the last changes, now the original problem has been fixed, but now we are having another  problem with permissions: 

- [ ] When you add permissions to content types, this should apply this permissions just  to the new contentlets, not to existing ones, just in case that you apply cascade changes. But right now when you add some permissions to any content type, this is applying cascade changes automatically 

SC: https://screencast.com/t/BU2JpjveWR

**Comment by wezell** [comment]
@bryanboza actually, permissions are loaded lazily.  This means that if you change permissions without first loading the content, it will get the new permissions.  A bug would be:

1. Load the content check the permissions
2. Change the permissions on a subfolder and don't cascade them
3. Check the permissions on the content again and see that they have not been changed.
4. cascade the folder permissions, let it finish and then check the content permissions again - they should be changed.

**Comment by bryanboza** [comment]
Ok @wezell, actually your case works as expected, but if you try to reproduce my case on demo.dotcms.com, we have a totally different behavior. 
**Steps:**
- Create a new content type 
- Add a new contentlet to this content type, and check the permissions 
- Now add some role, to the content type permissions. Apply the changes but don't cascade
- Check again the existing contentlet permissions. You should  only the CMS Anonymous role (by default)

However we have two roles, the default and the new one.
SC: https://screencast.com/t/10RVNQko

**Comment by jgambarios** [comment]
**Note to QA:** After a meeting with Will we realize the issue reported in this https://github.com/dotCMS/core/issues/12536#issuecomment-333656959 is an expected behaviour.

**Comment by bryanboza** [comment]
Fixed...
