### ISSUE TITLE
We are unable to sort the relationships 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12533]
We are having some problems when you try to sort the relationships by their columns 

## Expected Behavior
As the other portlets we should be able sort the content when you click in the column header 

## Current Behavior
As all the other portlets we should be able to order the contents by the column header, by in this case isn't working 

SC: https://screencast.com/t/AKc5VHPjHcg1
Log: https://gist.github.com/bryanboza/93e21ea443815565759c55ce4a79039e 

## Steps to Reproduce (for bugs)
1. Login
2. Go to content types portlet 
3. In the ":" button click to view all the relationships 
4. Try to sort the relationships  by any of the columns headers 

## Your Environment
Tested in the last master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12605

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
