### ISSUE TITLE
Clustering Cleanup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12548]
Remove `DIST_INDEXATION_ENABLED` and `CACHE_CLUSTER_THROUGH_DB` properties.

Cleaned up some method names and args. 

The only properties needed to cluster are:

```
AUTOWIRE_CLUSTER_ES=true
AUTOWIRE_MANAGE_ES_REPLICAS=true
AUTOWIRE_CLUSTER_TRANSPORT=true
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12552
