### ISSUE TITLE
Error in logs doing a single push 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12553]
We have an error doing a single push 

## Expected Behavior
We should push without errors in the log 

## Current Behavior
We are having this error in log, but the page is pushed without problems 

ST: https://gist.github.com/bryanboza/6e268aaebdee06c47c525756a7d5c238

## Steps to Reproduce (for bugs)
1. Create a new folder  
2. Add a single page in to the folder 
3. Add a new generic content to this page 
4. Configure your push environment 
5. Right click in the page and push publish 

**FYI: Tested after the integration of p8 in master... We have this error but the page is pushed**

## Your Environment
Tested on master // Postgres // FF (this on both environments)

**Comment by jcastro-dotcms** [comment]
**PROGRESS UPDATE:** This error is also reproducible in dotCMS 4.1. The only difference is that the error logged in the ``dotcms.log`` file is shorter:
```
[18/09/17 10:07:29:139 CST] ERROR business.ESContentletAPIImpl: Cannot publish related HTML Pages.  Fail
```
The error message was updated with more information in 4.2

**Comment by jcastro-dotcms** [comment]
As per meeting with @wezell and @jgambarios , the following solution has been approved:
* Change the message logging from ERROR to WARN.
* Do not include the exception's stack trace.
* Add a clarification note mentioning that this can happen when importing content in batch.

In the end, the push of the folder, the page, and its contents is successful. The new message will look like this:
```
[25/09/17 14:34:10:225 CST] WARN business.ESContentletAPIImpl:  Cannot publish related HTML Pages: htmlPageIdentifier.getId() = [61015872-e18f-43c8-a08f-367adf4d4957], languageId = [1], pageInode = [0c193e1a-2654-4965-a42d-7a9596152512]. This might happen if contents are being imported in batch.
```

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12662

**Comment by bryanboza** [comment]
After test the last changes, now we have a different error with the same steps

Here the log: https://gist.github.com/bryanboza/09637e48ab3523711f41a5ed79239f08

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12753

**Comment by bryanboza** [comment]
Fixed, now we are unable to reproduce this error... Tested in the last master // postgres
