### ISSUE TITLE
License not being picked on clean start

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12562]
This is correctly happening in project-8, but in master the cms is unable to grab a license when starting fresh.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12564

**Comment by shaydotcms** [comment]
Passed QA. Sever is grabbing a license when starting fresh.
![image](https://user-images.githubusercontent.com/8741846/30765760-7ee77e34-9fae-11e7-814e-2b788a55b973.png)

Tested on master branch
Commit a53b74cd96fcdbc3501a6dc329d97709f7a769e3 on Sep 22, 2017
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
