### ISSUE TITLE
Click on related content does not redirect

### ISSUE THREAD

**Issue by manuel-miranda** [dotCMS/core#12563]
When click on related content of a custom content, it does not redirect to the related content
Reported via https://my.dotcms.com/tickets/detail.dot?id=16ac9ee8-de83-4516-a524-b85efbe2d507

## Expected Behavior
Clicking ob content related on the relationship tab should redirect to the related content

## Current Behavior
After adding a relationship between with a custom content, when click  the related content (on the relationships tab of the content)  it does not redirect.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Create a new **Content Type**
2. Add new **Content** of the new **Content Type** just created 
3. Add a **Relationship** between the new **Content Type** and Employee (as example)
4. View **Relationships Tab** of a **Employee** content.
5. Click on the **Relationship** created on step 3, notice that nothing happens.

![image](https://user-images.githubusercontent.com/29102758/30286046-79532b00-96dd-11e7-86ac-ac09f1708b10.png)

## Context
This is affecting the default behavior of dotCMS, reverse way works, going to new Content created and find relationships clicking on it it will redirect to the Content (on this case Employee).
Reproduced on demo site and reported by customer: https://my.dotcms.com/tickets/detail.dot?id=16ac9ee8-de83-4516-a524-b85efbe2d507

## Your Environment
* dotCMS version used: 4.1.1, 3.6.2
* Browser Name and version: Opera
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Not relevant.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12566

**Comment by bryanboza** [comment]
Fixed, tested on master // MySQL // FF
