### ISSUE TITLE
Request a Trial License link is broken

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12574]
Tested on latest master

Configuration -> Licensing -> Request a Trial License link is broken

![request](https://user-images.githubusercontent.com/1569167/30335666-34d9a6a2-97a0-11e7-90af-50a614d68b19.jpg)

Link Path: http://localhost:8080/html/blank.jsp

**Comment by wezell** [comment]
This worked in Project-8, I'll look into it.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/core/pull/12580

**Comment by DeanGonzalez** [comment]
Tested: Working now

**Comment by shaydotcms** [comment]
Passed QA.
Trial license link is working. System is generating trial license and sending by email.
Tested on master branch
Commit effde18af8b02087cecc26b092f9dab8596e1ae7 on Sep 19, 2017
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
