### ISSUE TITLE
Move logic from DeleteInactiveClusterServersJob to FreeServerFromClusterJob

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12573]
Please remove property REMOVE_INACTIVE_CLUSTER_SERVER_PERIOD

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/534

**Comment by dsilvam** [comment]
Note to QA: Inactive servers in a cluster (ones not active for more than HEARTBEAT_TIMEOUT) should now be removed from cluster tables and not shown in the Network Tab. For testing purposes HEARTBEAT_TIMEOUT can be reduced to something like three minutes or less.

**Comment by DeanGonzalez** [comment]
Added to Changelog, documentation did not appear to need an adjustment.

**Comment by shaydotcms** [comment]
Passed QA. Followed steps on Notes to QA.
After HEARTBEAT_TIMEOUT, inactive servers in a cluster were removed from cluster tables. They are not showing in Network Tab either.

Tested on master branch 
Commit 41ae1ddef8f40a7f8e6c095b1ff123cace84897c on Sep 8, 2017
Mac OS 10.10 / Postgres 9.3.7
Ubuntu 14.04.1 / Postgres 9.3.7
Win7 Pro SP1 / Postgres 9.3.7
Chrome v54.0.2840.98 / Tomcat 8 / Java 8
