### ISSUE TITLE
"lock for editing" taking a very long time for content with thousands of relationships

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12585]
Locking a piece of content with thousands of relationships takes over 50 seconds.

The interesting thing is that the Call to ContentletAjax.lockContent.dwr returns in about 800ms.  Based on the chrome developer profiler, it looks like more than 50 seconds is spent in an anonymous javascript function.

## Expected Behavior

Clearly, do not expect locking content to take this long.  Locking should be a very quick thing.

**Comment by dsilvam** [comment]
Neither @oarrietadotcms or me were able to reproduce this behavior
