### ISSUE TITLE
Replace FileInputStreams with Files.newInputStream()

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12583]
See this blog:

https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful

We need to replace our FileInputStreams with Files.newInputStream() e.g.
```
try(InputStream in = Files.newInputStream(file.toPath)){

}
```

**Comment by oarrietadotcms** [comment]
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/537
core PR: https://github.com/dotCMS/core/pull/12628
