### ISSUE TITLE
PP: Make Publish Start and End date being global

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12590]
For Dynamic push, Publish Start and End dates in the Publish Detail Dialog currently reflect the actual publish start and end date of only one of the endpoints. We need these to reflect the dates for the global (all endpoints) publish process. 

Related to: https://github.com/dotCMS/core/issues/12429

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12601
