### ISSUE TITLE
Login with wrong password spins - does not throw error

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12593]
Tested on latest Master

Recent changes to login removed our password fail notification, we are not catching bad passwords and returning anything in the log or in the UI - it just spins.

![spins](https://user-images.githubusercontent.com/1569167/30439854-24067dbc-9932-11e7-9230-3b187e90a598.jpg)

**Comment by bryanboza** [comment]
Hey @DeanGonzalez check your dotcms-security.log, we log here and not in the dotcms.log. I think the problems is that we need restart  the invalid attempts number, because we penalize some seconds after a failed intent....

**Comment by erickgonzalez** [comment]
Not able to reproduce with the latest master, as Bryan mentions after every invalid attempt the timing increases to try again, but every time the notification shows up. Tested with FF and Chrome.

![image](https://user-images.githubusercontent.com/5278970/30756681-ed3433c6-9f88-11e7-987d-207390d075a1.png)
