### ISSUE TITLE
Content Search Portlet: Portlet breaks if Content Type has double quotes on it.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12598]
## Steps to Reproduce (for bugs)

1) Create Content Type with Name 'test “content” type' . It has to be with double quotes like here. 2) Add at least one field 
3) Create content with this type
4) Try to load Content -> Search page

Portlet is broken and nothing is displayed.

## Context
Reported by customer https://my.dotcms.com/tickets/detail.dot?id=7a5e853f-30be-4a6a-9582-9167421263ee

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Chrome, Firefox.
* Operating System and version: macOS 10.12.6.
* Application Server and version: Tomcat 8.0.18.
* Java Brand and version: JDK 8u121.
* Database and version: Postgres DB.
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12599

**Comment by bryanboza** [comment]
With this changes we are not fixing the bug, now we just are replacing all after the quotation marks... Then when you try to load the content search this name does not exist. 
<img width="1593" alt="quotation marks" src="https://user-images.githubusercontent.com/2641437/32123749-98bcf5e8-bb22-11e7-80da-5f7f106b7436.png">

**Comment by joseorsini** [comment]
@bryanboza this is a separate issue and it can be reproduce on demo. Fixes submitted under this ticket are not related to this one reported during the QA evaluation. 

I'll be uploading a follow-up fix for this one, though. 

<img width="1563" alt="screen shot 2017-10-30 at 8 35 51 am" src="https://user-images.githubusercontent.com/1717110/32177087-f67fefa4-bd4e-11e7-93aa-cdeb8144bf19.png">

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12949

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now works as expected
