### ISSUE TITLE
Workflow action icons can no longer be selected, but display in workflow scheme window

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#12617]
As of 4.0, you can no longer assign an icon to each workflow actions (as you could in 3.x).  However there are still some workflow icons displaying in the workflow scheme window for some actions.

## Expected Behavior

Either:

* The workflow schemes window should _not_ show any icons for workflow actions, or
* Workflow action icons should be selectable in workflow actions **_and_** should be displayed on the action buttons in the content editing screen.

## Current Behavior

In some workflows (presumably those created in 3.x and migrated to 4.x), some (but not all) workflow actions display icons in the workflow scheme window.  For example, the following shows the workflow scheme window for the `Documentation Management` workflow scheme on the starter site:

![image](https://user-images.githubusercontent.com/13456955/30548101-09b244c0-9c46-11e7-84f9-c3fdb7b438fb.png)

The red circles highlight two workflow actions that are still displaying icons.  However there is no way to select an icon for any workflow action in the action editing screen:

![image](https://user-images.githubusercontent.com/13456955/30548273-8f47b674-9c46-11e7-858c-81a8068632d8.png)

_Note also_ that there's a gap between the `Assign To` and `Next Step` fields, where the icon selection drop-down used to be - this gap should probably be removed.

Finally, note that these workflow action icons do **_not_** display on the action buttons in the content editing screen for the same workflow actions:

![image](https://user-images.githubusercontent.com/13456955/30548502-2dd80078-9c47-11e7-8425-737b536077a4.png)

## Possible Solution

1. Clean up the starter DB to remove those icons from the Document Management workflow.
2. Update to the workflow scheme window to no longer display the icons (even if they're assigned).

Note: I think we'll need to make sure to do #2 instead of (or in addition to) #1, since if we don't then any customers with existing workflows will likely have the problem when upgrading to 4.x.

## Steps to Reproduce (for bugs)

Just open the `Documentation Management` workflow on demo (please see screen shots above).

## Context

Since I assume the workflow action icons were intentionally removed in 4.0, I also assume this is merely cosmetic, and will only affect 3.x customers with workflows who upgrade to 4.x.

If it was not intentional for workflow action icons to be removed, then that's another story...

## Your Environment

* dotCMS version used: 4.0.1, 4.1.1 (local and demo)
* Browser Name and version: Chrome 59.0.3071.86
* Operating System and version: Win 7 Enterprise
* Application Server and version: distro
* Java Brand and version: 1.8 (local and demo)

**Comment by wezell** [comment]
I believe this is removed.
