### ISSUE TITLE
Wrong credentials crashing the app

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12614]
As a stakeholder I want to show a message to the user when try to login with the wrong credentials.

## Expected Behavior
1. When login is unsuccessful we should show a nice message.

## Current Behavior
1. When login is unsuccessful app crash:

<img width="604" alt="screen shot 2017-09-16 at 7 10 41 pm" src="https://user-images.githubusercontent.com/751424/30517140-c0cf554c-9b12-11e7-9d10-04291a0c641e.png">

## Possible Solution
This used to work, so we broke it at some point.

We can start looking into here: https://github.com/dotCMS/core-web/blob/master/src/app/view/components/login/login-component/login-container.ts#L61

## Known Workarounds
N/A

**Comment by bryanboza** [comment]
Fixed tested in multiple browsers and works as expected. Need validate this behavior in IE11...

**Comment by bryanboza** [comment]
Fixed, tested in all the browsers and works as expected
