### ISSUE TITLE
[Blocked] Add some styling to DotCMS Browser portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12612]
#### Here are the instructions:

<img width="1439" alt="screen shot 2017-09-16 at 6 40 41 pm" src="https://user-images.githubusercontent.com/751424/30517043-9d80f72a-9b0e-11e7-8a8e-a2ed7cf39750.png">

### Acceptance Criteria

1. Match the design
2. Use DataList from primeng to the right table
3. Work in all the supported browsers (don't forget IE11)

**Comment by wezell** [comment]
Will be addressed in the new Browser
