### ISSUE TITLE
Fix margin in rules engine on page properties

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12616]
As a stakeholder I want overall design of the app to be as consistent as possible

## Expected Behavior
1. 24px in the margin of the rules engine inside a tab on page properties

## Current Behavior
1. Way more that 24px in the margin of the rules engine inside a tab on page properties

## Steps to Reproduce (for bugs)

1. Login
2. Go to Browser
3. Right click a page and click properties
4. Go to "Rules" tab

**Comment by bryanboza** [comment]
Fixed, now we have padding 0px... Tested on the last master // Chrome
