### ISSUE TITLE
Enhancement: Suggested Field Type List Re-order

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12615]
Since the field type lists on Content Types are only alphabetically listed, then the most useful one (Text) is toward the bottom of the list.  There is also no logical grouping of the fields.  So I re-grouped based on what fields I thought were most often used, and then grouped by similarity.  I also added a visual separator between the groupings.  Thought this might help webmasters more than an alpha list.

We should also remove the word "field" at the end of the title to each field type since it is understood when you are adding fields to the content type.  We should also be consistent.

![fieldlistreorder](https://user-images.githubusercontent.com/1569167/30551985-aed92fbe-9c59-11e7-8c9b-37186435a469.jpg)

**Comment by john-thomas-dotcms** [comment]
+1, this would help.

Only changes I'd suggest:

* Put `Hidden` and `Constant` in same grouping.
* Put `Custom Field` at the bottom.

**Comment by DeanGonzalez** [comment]
I redid the image to reflect input from John Thomas and Jason Smith.

**Comment by bryanboza** [comment]
Since this list is ordered by usage, this will be different to every client, then we should make this order dynamically , and not set this by code.

**Comment by DeanGonzalez** [comment]
I talked to Jay, we can alpha sort within each group if we add another separator line after WYSIWYG, and move Key/Value to the same group as "Custom, Hidden, Constant, Permissions"  - Then we can alpha sort each subgrouping and it still works from a usability standard on most used fields being listed first.
