### ISSUE TITLE
OSGI plugins don't work on master

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12622]
We have problems trying to use the follow OSGI plugins 

- [x] com.dotcms.custom.spring
- [x] com.dotcms.job
- [x] com.dotcms.spring
- [x] com.dotcms.tuckey

## Expected Behavior
We should be able to use this examples without problems with the latest version of master 

## Current Behavior
We have problems trying to compile that ones 

## Your Environment
Tested in the last master // Postgres // FF

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/12827
https://github.com/dotCMS/plugin-seeds/pull/16

**Comment by bryanboza** [comment]
After test all the plugins again now we are having problems with: 

- [ ] com.dotcms.ruleengine.conditionlet
- [ ] com.dotcms.ruleengine.actionlet

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/plugin-seeds/pull/19

**Comment by jgambarios** [comment]
**Note to QA:** We removed the **com.dotcms.ruleengine.conditionlet** and **com.dotcms.ruleengine.actionlet** plugins as they already exist in core. 
The correct example plugins are **com.dotcms.ruleengine.velocityscriptingactionlet** and **com.dotcms.ruleengine.visitoripconditionlet**

**Comment by bryanboza** [comment]
Fixed, that plugins has been removed from the repo
