### ISSUE TITLE
[Binary Files] ShortyId Feature breaks REST API calls for files with non-uuid identifiers

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12627]
Once [this OSGi plugin is deployed](https://github.com/joseorsini/LegacyFilesMigrator), all Legacy Files are migrated as contents, by reusing the same File/Data attributes and take advantage of File Asset content type at the same time. Reusing the following values: 

- Site.
- Folder.
- Inode.
- Identifier

is expected in order to avoid breaking relationships with other Contents:

- Links.
- Image/File Fields.
- Static pulls on HTML/JS/Velocity Code, etc.
- CSS Stylesheets for Templates/Containers.

however there is a problem with the ShortyId feature introduced in 3.x. A lookup of an asset using
[REST API calls](https://dotcms.com/docs/latest/image-resizing-and-processing) ends up in Error 404 because the ShortyId validation on BinaryExporterServlet:

- Interprets the passed Id as a potential Shorty Id.
- It fails upon validating [if this is a valid ShortyId](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/uuid/shorty/ShortyIdAPIImpl.java#L146). Since Legacy Files had an auto-incremental numeric value as identifier before UUIDs were implemente, we can have any potential numeric value here.
- If we change the `MINIMUM_SHORTY_ID_LENGTH` value to `1`, [then a lookup of a ShortyID in the DB](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/uuid/shorty/ShortyIdAPIImpl.java#L100) may return inaccurate values here, breaking the entire BinaryExporterServlet and throwing Error 404.

## Expected Behavior
Regardless of the current format of the file identifier, the BinaryExporterServlet should handle this identifier format instead of a hardcoded reference to UUIDs length. IF no shortyId can be found, then the actual Identifier needs to be pulled from the actual request and then render the image/file if a match is found.

## Known Workarounds
Use the resource link, which it's an inconvenient. For example, Containers allow you to add programmatically links for Image/File/Binary fields, and links inserted are REST API calls. Same for getUri() methods from BinaryMap class, for those cases where images were pulled using Velocity code.

## Steps to Reproduce (for bugs)

1. Get a 1.9.x set of data and assets where Legacy Files were created with numeric values as identifiers.
2. Upgrade to 3.7.1.
3. Deploy [this OSGi plugin](https://github.com/joseorsini/LegacyFilesMigrator) and migrate all Legacy Files to contents.
4. Upgrade to 4.1.1 (optional, these same tests can be made on 3.7.1, behavior is the same).

On tests performed, this http://localhost:8080/contentAsset/raw-data/639df909-f6a2-44d2-9fd1-5957c908315b/fileAsset returned a valid asset:

```
mysql> select * from identifier where id = '639df909-f6a2-44d2-9fd1-5957c908315b';
+--------------------------------------+--------------------------------------+-------------------------+------------------------+------------+-----------------+----------------+
| id                                   | host_inode                           | parent_path             | asset_name             | asset_type | syspublish_date | sysexpire_date |
+--------------------------------------+--------------------------------------+-------------------------+------------------------+------------+-----------------+----------------+
| 639df909-f6a2-44d2-9fd1-5957c908315b | 2b268629-379c-4168-8f1b-741cc2d43ea8 | /resources/docs/pq/bic/ | bic_guide_visiteur.pdf | contentlet | NULL            | NULL           |
+--------------------------------------+--------------------------------------+-------------------------+------------------------+------------+-----------------+----------------+
1 row in set (0.00 sec)
```

Whereas this one http://localhost:8080/contentAsset/raw-data/7285/fileAsset returns error 404

```
mysql> select * from identifier where id = '7285';
+------+--------------------------------------+-------------------------+-------------------------------+------------+-----------------+----------------+
| id   | host_inode                           | parent_path             | asset_name                    | asset_type | syspublish_date | sysexpire_date |
+------+--------------------------------------+-------------------------+-------------------------------+------------+-----------------+----------------+
| 7285 | 2b268629-379c-4168-8f1b-741cc2d43ea8 | /resources/docs/pq/bic/ | BICPlanActionPhoqueCommun.pdf | contentlet | NULL            | NULL           |
+------+--------------------------------------+-------------------------+-------------------------------+------------+-----------------+----------------+
1 row in set (0.00 sec)
```

If `MINIMUM_SHORTY_ID_LENGTH` is set to its default value (10 chars), then this exception is thrown:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/uuid/shorty/ShortyIdAPIImpl.java#L149

If `MINIMUM_SHORTY_ID_LENGTH` is set to `1`, then we have this on log files:

```
If [19/09/17 15:59:43:635 CST]  WARN shorty.ShortyIdAPIImpl: Shorty ID collision:7285
```

and DB lookup on the ShortyIdAPIImpl throws this

```
mysql> select inode as id, 'inode' as type, type as subtype from inode where inode like '7285%' union select id,'identifier', asset_type from identifier where id like '7285%';
+--------------------------------------+------------+------------+
| id                                   | type       | subtype    |
+--------------------------------------+------------+------------+
| 7285024a-885e-4679-9719-6d69528e9289 | inode      | contentlet |
| 72850ea6-7d36-4a04-94e8-e51e8fc6c7ac | inode      | contentlet |
| 72858842-4557-4b26-a5cf-f80d6d7ecc22 | inode      | contentlet |
| 7285                                 | identifier | contentlet |
+--------------------------------------+------------+------------+
4 rows in set (0.24 sec)
```

Hitting `/resources/docs/pq/bic/BICPlanActionPhoqueCommun.pdf` link shows the asset.

## Context
For customers who are expecting to get this plugin working and have all their Legacy Files migrated to contents, this is cumbersome and not all Legacy Files may be supported. 

Reported under this ticket: https://my.dotcms.com/tickets/detail.dot?id=36cab880-b0ed-4c49-b94f-f2cea8d96451

## Your Environment

* dotCMS version used: 3.7.1, 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App Server.
* Java Brand and version: 8u121.
* Database and version: MySQL 5.6.29
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12629

**Comment by joseorsini** [comment]
3rd time is the charm https://github.com/dotCMS/core/pull/12638

**Comment by wezell** [comment]
This breaks serving images/files that are not file assets.  For example, the first page of our demo site is broken.  Please roll out these commits.

**Comment by wezell** [comment]
Also, @joseorsini make sure to use google java formatting when coding - it calls for spaces rather than tabs.   Not sure if you have the style sheet.

**Comment by bryanboza** [comment]
Yes, this is breaking the images on front-end: https://screencast.com/t/kcbHfD7fYL

**Comment by jgambarios** [comment]
Reverting changes: https://github.com/dotCMS/core/pull/12975

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/12972

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now this is working
