### ISSUE TITLE
Nav it's closing when first clicked portlet it's loaded

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12631]
As a stakeholder I want the navigation state to work as expected

## Expected Behavior
1. When a portlet loads the navigation state (expanded and collapsed options) should remain the same.

## Current Behavior
1. When user login, expand an option and click in the first portlet the nav collapse.

## Possible Solution
Check what navigation it's subscribe to and check it's something it's triggering there.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Login (only happen with fresh login)
2. Expand options in the navigation
3. Click any portlet
4. The nav closed

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Chrome
