### ISSUE TITLE
Unable to use dotCMS in IE11

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12637]
We are having problems to load the login window if you try to use IE11 

## Expected Behavior
As part of the supported browser we need be compatible with IE11

## Current Behavior
The system shows the loading logo and never load

SC: https://screencast.com/t/QCdEGeMu

FYI: We are having a console error 
```
Object doesn't support property or method 'assign'
```

## Your Environment
Tested in the last master // IE11

**Comment by bryanboza** [comment]
Now we are able to login but we still having problems trying to navigate in our backend 

- [ ] Rules isn't loading https://screencast.com/t/QayiQus1l8q

- [ ] "+" button in the angular menu isn't working https://screencast.com/t/VOwRuwPoxdK

- [ ] Scrollbar in the notification window https://screencast.com/t/7f2gI0sgFfPP

- [ ] Unable to add fields in the new content types angular portlet  (please retest the basic functionality in IE11) https://screencast.com/t/lD35315o0VMp

**Comment by bryanboza** [comment]
We still having problems here trying to add new fields in the new content types portlet and also continue with the scroll bar in the notification window... Needs work in both cases

**Comment by fmontes** [comment]
@bryanboza the fixes are merged now.

**Comment by bryanboza** [comment]
Fixed, tested in the last master // IE11
