### ISSUE TITLE
Can not add a portlet to a new Tool Group after it's added to any other Tool Group

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#12635]
If you add any portlet to any Tool Group, and then try to create a new Tool Group and add the same portlet to the new Tool Group, it can't be added.

## Expected Behavior

A portlet should be able to be added to every new tool group created, regardless of whether it was added to another tool group previously or not.

## Current Behavior

After you've added a portlet to a tool group, you can not add the same portlet to any _new_ tool group (though you _can_ add it to an existing tool group).

## Possible Solution

It looks like we're not clearing some kind of internal state indicating what portlets have been selected when we save a tool group.

## Known Workarounds

1. Save the tool group then re-open it for editing
    A. Add the portlet to the first tool group.
    B. Create and save the 2nd tool group _without_ the desired portlet.
    C. Re-open the 2nd tool group for editing, and add the desired portlet.
2. Change portlets and return
    A. Add the portlet to the first tool group.
    B. Click on any other portlet in the navigation side pane (e.g. `System` -> `Users`).
    C. Return to the Tools tab (e.g. `System` -> `Roles & Tabs` -> select a Role -> `Tools`).
    D. Create the 2nd tool group, and the portlet can now be added without problems.

## Steps to Reproduce (for bugs)

1. Open `System` -> `Roles & Tools`.
2. Select a Role (e.g. `Intranet`).
3. Select the `Tools` tab.
4. Create a new tool group with 1 portlet in it:
    A. Click `Create Custom Tool Group`.
    B. Give the tool group a name (e.g. `Group 1`)
    C. Select a portlet from the `Tools` menu (e.g. `Categories`) and click `Add`.
    D. Press `Save`.
5. Create a new tool group and attempt to add the same portlet to it:
    A. Click `Create Custom Tool Group`.
    B. Give the tool group a name (e.g. `Group 2`)
    C. Select the same portlet as above (e.g. `Categories`) and click `Add`.
**RESULT:** Nothing happens.  The portlet is not added to the list, and no error message is displayed in the logs.

## Your Environment

* dotCMS version used: 4.1.0 (demo)
* Browser Name and version: Chrome 61.0.3163.79
* Operating System and version: Win 7 Enterprise
* Application Server and version: Tomcat 1.8 (demo)
* Java Brand and version: 1.8 (demo)

## Possibly Related

Freddy saw an issue where he wasn't able to add a new tool group because he received an error saying a tool group with that name already existed (even though it didn't).  That could potentially be caused by a similar failure to properly clear status somewhere in this code.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12767

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgres // chrome
