### ISSUE TITLE
Content types angular portlet issues 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12640]
Related to #11506 

- [x] Need reload the save button after you add a new content type, this because we are leaving the save button and every time you click on it, the system is creating a new content type, if you close and open the created content type, this button disappear and we have an update button
SC: https://screencast.com/t/RtQEeF4T065

- [x] Need remove the colapse button, isn't necesary 
SC: https://screencast.com/t/B1ViO5OnW

- [x] We are unable to resolve some keys
SC: https://screencast.com/t/Uw3tr00xwP3D

- [x] Need enable the date time fields in the "Publish/Expire date fields" when you add those fields to the content types
SC: https://screencast.com/t/j145Xi2WPw5

- [ ]  ~~The workflow field isn't working (know issue)~~

- [x] Need add a redirect to the **Variable** and **Identifier** links
SC: https://screencast.com/t/4KDWQfTP

- [x] The Wysiwyg properties window need styling help
SC: https://screencast.com/t/sejTZIUnR

- [ ] ~~To be consistent with the system, the delete confirmation button should be in red color
SC: https://screencast.com/t/uYyu1J9O~~
@fmontes: we are moving away from red buttons for "negative" actions

- [x] We are unable to delete content types from this portlet 
SC: https://screencast.com/t/bdGCbaR1CLTP

- [ ] ~~By user experience maybe we need handle a save/cancel button. This to avoid cancel changes doing in the fields in case of error 
SC: https://screencast.com/t/978xNG5oy~~
@fmontes: we're doing a little bit of redesign that will include something of this.

- [x] Need add a confirmation message when you try to delete some component with fields
SC: https://screencast.com/t/IOv1D8AGj (Luis)

- [ ] ~~As part of the new changes maybe we need support custom layouts (**enhancement**)
SC: https://screencast.com/t/jOGOw7v0u~~
@fmontes we're redesign it how we create rows/cols

- [ ] ~~Need auto collapse the edit content type window when you click in a component~~
SC: https://screencast.com/t/JkAn5ZeLE
@fmontes we have another idea for this.

- [x] Need add log activity in the user_activity.log when add/delete components and fields from any content type

- [x] Since now we are unable to see what kind of fields is every one, we need a distinct icon to binary and file fields 
SC: https://screencast.com/t/gJqMntKk

- [x] We need add a red signal to the field when you set as required

- [x] Need add the .required style when you are creating new fields
SC: https://screencast.com/t/L05bb3O3RPL

- [x] Wrong window to create site or folder field 
SC: https://screencast.com/t/iFhRYM5ZK

- [x] Need show more content types per page
SC: https://screencast.com/t/DllQhliC

- [x] Regex validation field needs styling help (Luis)
SC: https://screencast.com/t/QL8rOmPHwI

- [x] Need validate if the descriptive text is important (Humberto)
SC: https://screencast.com/t/vgWDkXKx

- [x] We are unable to see the fields when you are adding some base type with default fields (widget, pages, key/value)
SC: https://screencast.com/t/aijkRYY9YhPo

- [x] We are able to delete the default fields
SC: https://screencast.com/t/W5UyS0fpTvg

- [x] Need refresh the iframe when you delete some permissions in content types
SC: https://screencast.com/t/Q1bxHfKp

- [ ] ~~Unable to add/view relationships from the new portlet~~ (#12665)

- [x] SQL query problems in the global search field
SC: https://screencast.com/t/t3QKSPHv4t
SC: https://screencast.com/t/Xj2PfrUfJKFY

- [x] Unable to add tag fields

- [x] Variable and description order isn't working 
SC: https://screencast.com/t/nwhK37dn

- [ ] ~~Unable to filter the system content types, also filter by type (as in the old portlet)
SC: https://screencast.com/t/jyVUW9D8TMbs~~ (#12666)

- [ ] ~~Unable to add Vanity URL and key/value base types 
SC: https://screencast.com/t/dKTXJnVC~~

- [x] We are loosing some properties of the default field 
SC: https://screencast.com/t/zlnzqJCurlyG

- [ ] ~~We are unable to add field variables 
SC: https://screencast.com/t/xkrL3prQ~~ (https://github.com/dotCMS/core/issues/12667)

**Comment by jgambarios** [comment]
PR:
Master: https://github.com/dotCMS/core/pull/12710
4.2: https://github.com/dotCMS/core/pull/12732
