### ISSUE TITLE
Content types angular portlet functional issues

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12654]
Related to #11506 

- [ ] We are unable to see the fields when you are adding some base type with default fields (widget, pages, key/value)
SC: https://screencast.com/t/aijkRYY9YhPo

- [ ] We are able to delete the default fields
SC: https://screencast.com/t/W5UyS0fpTvg

- [ ] Need refresh the iframe when you delete some permissions in content types 
SC: https://screencast.com/t/Q1bxHfKp

- [ ] Unable to add/view relationships from the new portlet 

- [ ] SQL query problems in the global search field  
SC: https://screencast.com/t/t3QKSPHv4t
SC: https://screencast.com/t/Xj2PfrUfJKFY

- [ ] Unable to add tag fields 

- [ ] Variable and description order isn't working 
SC: https://screencast.com/t/nwhK37dn

- [ ] Unable to filter the system content types, also filter by type (as in the old portlet)
SC: https://screencast.com/t/jyVUW9D8TMbs

- [ ] Unable to add Vanity URL and key/value base types 
SC: https://screencast.com/t/dKTXJnVC

- [ ] We are loosing some properties of the default field 
SC: https://screencast.com/t/zlnzqJCurlyG

- [ ] We are unable to add field variables 
SC: https://screencast.com/t/xkrL3prQ

**Comment by freddyucv** [comment]
Duplicate #12640
