### ISSUE TITLE
Some characters breaks sql queries from Content Search and Host selector

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12653]
We have a SQL error when you type some special characters in some of the components like site selector

## Expected Behavior
We should scape this characters before send the query 

## Current Behavior
We are sending this and crashing the query

## Steps to Reproduce (for bugs)
1. Login
2. Add a new site
3. In the site selector component add a `'` character 
4. Check the dotcms.log file

## Your Environment
Tested on master // postgres

**Comment by jgambarios** [comment]
Closed as same issue was reported in https://github.com/dotCMS/core/issues/12640
