### ISSUE TITLE
Unique value should not be validated when language is different

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#12658]
## Expected Behavior
Creating new content with a unique field value should not care about uniqueness if languages are different.

## Steps to Reproduce (for bugs)
1- Create a content type with 2 text fields
*Title: Datatype-> Text
*Number: Datatype-> Whole Number and Unique
2- Create a new content in English with the values (title: test, number: 1)
3- Create a new content in Spanish with the values (title: test2, number: 1)

Pop up will show up saying that field value must be unique

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF and Chrome

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12659

**Comment by dsilvam** [comment]
Adapt ITest for the new behavior https://github.com/dotCMS/core/pull/12674

**Comment by shaydotcms** [comment]
Successfully created new content with same unique value in different languages and did not receive popup saying I'm unable to use the same unique value for different languages 
![image](https://user-images.githubusercontent.com/8741846/30940137-3ba94c9a-a39d-11e7-8f80-7aa8e008d26b.png)

Tested on master branch
Commit cc8fce62c56211d717848ace1ee6022a19320f79 on Sep 27, 2017
Mac OS 10.10 / Postgres 9.3.7 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
