### ISSUE TITLE
On Sql Injections attempts we should log in the security.log file

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12652]
We are login this kind of error in the global log, we need move this to the security log 

## Expected Behavior
When Sql Injections attempts we should log in the secutiry.log file instead the global log 

## Current Behavior
We are logging the complete error in our global log 

## Steps to Reproduce (for bugs)

1. Login
2. Add a new site
3. In the site selector component add a SQL reserved word "select, delete, insert"
4. Check the dotcms.log file

## Your Environment
Tested on master // Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12657

**Comment by bryanboza** [comment]
Fixed, tested in the last code and now we have the this logged in the security.log file, also have the complete stack trace in the dotcms.log
