### ISSUE TITLE
We are allowing SQL injection in the site selector component 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12651]
We are crashing the SQL query if you add some special character or a SQL command 

## Expected Behavior
We should validate this before made the query and scape this characters 

## Current Behavior
We are crashing the query and showing and error in log 
SC: https://screencast.com/t/ylOrJ6gPlfQ

## Steps to Reproduce (for bugs)
1. Login
2. Add a new site 
3. In the site selector component add a "; or ' " or some SQL reserved word "select, delete, insert"
4. Check the dotcms.log file 

## Your Environment
Tested on the last master // Postgres // FF

**Comment by jgambarios** [comment]
The system is not allowing or crashing with SQL Injections, the system shows in the logs the attempt for  the sql injection.
