### ISSUE TITLE
 Unable to add/view relationships from the new Content Types portlet 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#12665]
1. Add a tab inside the content types edit for relationships
2. Relationships listing should filter by the content type we are coming from
3. Dropdown by default should select as parent or child one of the content types we are coming from and update in case user change it.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12750

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12966
