### ISSUE TITLE
Create Static Endpoint

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12669]
Create a new endpoint type - static endpoint - that allows a user to specify a local folder to publish statically to.

Upon saving, the system will test if the system has write access to the folder and report an error if it does not.

The idea is to allow the “Publish To” folder path to accept variables to work allowing our clients flexibility moving forward.

By default, all static publishing will push under the folder $ASSET_PATH/static_publishing

Or can be specified independently by the config variable:
STATIC_PUBLISHING_ROOT_PATH

All files that are published will be published under this path

We will strip out any .. (dot dot) or filesystem characters from the “Publish To” path entered 

The “Publish To” path will accept variables that can be used to setup a folder pattern. The variables we will respect will be 

- {hostId} 
- {hostname} 
- {languageIso} 
- {languageCountry}
- {languageId}
- {date}
- {date-FFFFFFFF}

**Comment by DeanGonzalez** [comment]
Documented: These are the same properties as in the AWS bucket. I placed link inside the custom static plugin doc: https://auth.dotcms.com/docs/latest/connecting-remote-servers#CustomStatic
