### ISSUE TITLE
[angular] Links in the "+" component are not refreshing when clicking a link equal to the browser's URL

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12661]
When adding new content of a given Content Type via the "+" component, the Angular app is not re-routing correctly when the link clicked by the user is the same as the URL in the browser.

## Expected Behavior
After adding content with a specific Content Type, users should be able to add more content of the same Content Type by using the "+" component.

## Current Behavior
After the first time, trying to add more content of the same Content Type through the "+" component is not working.

## Possible Solution
Review the angular routing mechanism.

## Known Workarounds
Use the **Add New Content > Add New Content** button.

## Steps to Reproduce
1. Log into the dotCMS back-end.
2. Click the **"+" component > Content > Content (Generic)**. Notice that the URL in the browser will look like this: http://localhost:8080/dotAdmin/#/c/Content_(Generic)
3. Add any new content, and click **Save/Publish**. Notice that the URL in the browser still looks like this: http://localhost:8080/dotAdmin/#/c/Content_(Generic)
4. One more time, click the **"+" component > Content > Content (Generic)**.
5. Nothing happens. The user should be redirected to the Add Content page.

## Context
The problem seems to be caused by Angular not re-routing because the URL in the link and the URL in the browser are the same. Clicking any other Content Type in the "+" component will work.

## Your Environment
* dotCMS version used: Not relevant.
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Angular.

**Comment by jgambarios** [comment]
**NOTE:** We have the same behaviour on the left menu (this used to work) when a menu element is resolved clicking on the same menu element does nothing.

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgres // Chrome
