### ISSUE TITLE
Add fields variables tab to the create/edit fields

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#12667]
As a stakeholder I need that user can add fields variables to fields in the new content types

## Mocks
<img width="932" alt="screen shot 2018-10-06 at 7 43 44 am" src="https://user-images.githubusercontent.com/751424/46571975-9ed7db00-c93b-11e8-9950-17fd0ac2edf3.png">

<img width="960" alt="screen shot 2018-10-06 at 7 42 45 am" src="https://user-images.githubusercontent.com/751424/46571968-794ad180-c93b-11e8-9bb6-47c3c54d0825.png">

### NOTE
See that we replace the "Data Type" radio buttons with a checkbox.

### Interface example: 
```
{  
   name:“1507132008926”,
   lastModifierFullName:“system user system user”,
   lastModifierId:“system”,
   lastModDate:new Date(1507132009000),
   id:“4d40d61a-0395-4861-bdfb-e89b3f1afa0b”,
   value:“44”,
   key:“tet”,
   fieldId:“86fabb34-01be-486c-95e6-741df13bacc4”
}
```

### Acceptance Criteria

1. Match the design
2. Add the [tabview](https://www.primefaces.org/primeng/#/tabview) to the dialog.
3. When creating a content type "Field Variables" tabs will be disabled
4. User should be able to add an entry by keyboard, by focusing the name type, tab, type, enter.
5. When user click on "edit" a field it should focus on the name field
6. When the table grows bigger that the dialog we start scrolling, cancel stick remain at the bottom
7. Work in all the supported browsers (don't forget IE11 and iPad)
8. Multilanguage
9. Unit test

**Comment by freddyucv** [comment]
end points:
GET: /v1/contenttype/{typeId}/fields/id/{fieldId}/variables

POST: /v1/contenttype/{typeId}/fields/id/{fieldId}/variables
   data example:                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 {
	"key": "k1",
	"value":"v1",
	"clazz": "com.dotcms.contenttype.model.field.FieldVariable",
	"fieldId": "0c2c306e-de92-4b3b-b1a5-46d5f7007b24"
}

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15266

**Comment by fmontes** [comment]
<img width="846" alt="screen shot on 2018-09-20 at 09_39_46" src="https://user-images.githubusercontent.com/751424/45829967-4f49ac00-bcb9-11e8-84e3-0b4302c44c65.png">

**Comment by fmontes** [comment]
QA results:

1. Design is not match, icons are wrong
2. Can't edit a field
3. If the user add too much entries the dialog doesn't grow

**Comment by fmontes** [comment]
This tests is failing: https://github.com/dotCMS/core-web/blob/master/src/app/portlets/content-types/fields/content-type-fields-variables/content-type-fields-variables.component.spec.ts#L77

**Comment by bryanboza** [comment]
We need some styling help with long values 
SC: https://screencast.com/t/oPOWB4C9cb

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
