### ISSUE TITLE
Create Workflow Action Roles

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12678]
Create 4 new special roles (Action Roles?) that will be included in the Workflow Action > “Who Can Use” selector.  This these will be 

- Anyone who can View Content
- Anyone who can Edit Content
- Anyone who can Publish Content
- Anyone who can Edit Permissions Content

Granting a workflow workflow action one of these special roles will allow for workflow actions to be permissioned based on the permissions of the underlying content object vs a hardcoded list of users/roles.

**Comment by wezell** [comment]
We will need to write an integration test

**Comment by wezell** [comment]
We need a db upgrade task to automatically create these roles - and  want to have a hardcoded list of role_ids as well - do not use random UUIds

**Comment by wezell** [comment]
```
0f995057-5c35-4ae7-998a-774dda146c63
0d98c223-f542-4676-9b9e-c2142ae249eb
617f7300-5c7b-463f-9554-380b918520bc
3acfbed2-9909-43b0-b871-2eaa3d56456c
c3eb4526-6d96-48d8-9540-e5fa560cfc0f
4b53bfa4-846b-4886-9eb0-bda6888e5f27
52181fb6-65c8-4221-8d17-1da8b0e20784
a1cfb7ed-c478-4cfb-a98e-62acd8b3a5fd
38dc1da4-f4a2-483d-a468-6e9653acb213
4def098c-21f4-4860-afaf-19fda064b709
```

**Comment by jdotcms** [comment]
These roles should exists on the db.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13258

**Comment by bryanboza** [comment]
This works with specific steps, Waiting for the new starter to test

**Comment by bryanboza** [comment]
We have permissions problems here, If you use "Anyone who can view the content" and give permissions to some limited user, we have this error when you try to execute this action.
ST: https://gist.github.com/bryanboza/a815c362fc979e2199dfa6520d2763bc

**To recreate:**
- Create a new worflow 
- Add a new step
- Add a new action to this step (Pub1) add the publish sub-action
- Create new content type and add this workflow
- Give full permissions to some limited user over this content type 
- Add a new content, and execute the WF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13526

**Comment by oswaldogallango** [comment]
included integration tests P.R https://github.com/dotCMS/core/pull/13526

**Comment by bryanboza** [comment]
Tested in the last master code, and we have a problems with the "Anyone who can view the contnet" role here, this because right now our logic needs do a checkout of the content to execute any action, and you can't do that if don't have permissions to edit... 

Then does not make sense have this role, if you can't execute actions with it...

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/13174

**Comment by bryanboza** [comment]
Fixed, now we are able to execute actions without problems, but this only if the action does not require special permissions
