### ISSUE TITLE
Webdav not working to upload files with capital letters

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12671]
Tested on latest master using finder

No images or files can upload:

screenshot: 
![webdavissue](https://user-images.githubusercontent.com/1569167/30882402-087c17ee-a2c6-11e7-99cc-7e6f88602578.jpg)

Here is the error in the log: https://gist.github.com/DeanGonzalez/8b3c3e3598573d90ad6e20c12f901378

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12711

**Comment by erickgonzalez** [comment]
Tested on Cyberduck and finder. Uploads the files successfully but we have some logs regarding Broken pipe when using Finder (same behavior on the previous version).

**Comment by DeanGonzalez** [comment]
Hey Guys, webdav is not working for me on this mornings master.  I just updated.  Try dragging over 4 files, or folders with files.  It's not working and this is definitely issues first seen in 4.2.  In 4.1.1 I think we got the null error, but the files still made it.  The files are failing in current master: https://screencast.com/t/9inTIIJzMG

**Comment by bryanboza** [comment]
After test in the last master we still having problems but just if you use Finder to upload files, I do the same test with Cyberduck and works fine. Seems the problem is just with Finder: 

Here the ST: https://gist.github.com/bryanboza/cbff72887eae6fdebbd82f3853f6e593

**Comment by bryanboza** [comment]
Also I have this other error trying to upload multiple files: https://gist.github.com/bryanboza/8913588bc8591a49180dd2d7ba0c1945

**Comment by shaydotcms** [comment]
Cyberduck is working fine, issue is happening with Finder.
New ticket has bee created for this https://github.com/dotCMS/core/issues/12873
