### ISSUE TITLE
Allow multiple workflows schemes to be associated to a content type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12675]
dotCMS workflows will be modified so that a single content type can be associated with 1 or more workflow schemes. 

When editing a piece of content that is not in a current workflow state, a content editor will be presented with a list of the workflow schemes & underlying workflow actions.  This list will be show the workflow action to which they have permissions for the content type they are viewing.  

If the content is already in a current workflow scheme/step, the content editor will only see the actions in that scheme/step to which they have permissions (current behavior).

**Comment by oswaldogallango** [comment]
P.R enterprise https://github.com/dotCMS/enterprise-2.x/pull/560 and core https://github.com/dotCMS/core/pull/13119

**Comment by jgambarios** [comment]
**Note to QA:** We need please to test the regular behaviour of the Workflows, but also make sure it is working webdav, multiple uploads and push publish with the new changes.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13137

**Comment by bryanboza** [comment]
Fixed, some pending changes reported in a separated cards..
