### ISSUE TITLE
set default action from the content type screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12676]
From the content type screen an admin will be able to select an optional “default action” for the content type based on the workflow schemes it is part of.  This will be used to force new content of that type, which does not specify a workflow action (e.g. webdav, rest), into a default workflow process and action. 

I think we might need to add a db field.

**Comment by oswaldogallango** [comment]
first PR https://github.com/dotCMS/core/pull/13643 and EE PR https://github.com/dotCMS/enterprise-2.x/pull/586

**Comment by oswaldogallango** [comment]
Pull with UI changes for import contentlet and upload multiple files P.R https://github.com/dotCMS/core/pull/13689

**Comment by oswaldogallango** [comment]
ui workflow action changes on site browser and contentlet search P.R https://github.com/dotCMS/core/pull/13738

**Comment by bryanboza** [comment]
Now we have the changes on master... New issues created here in a separated cards...
