### ISSUE TITLE
 push static sites, pages and content to a remote server via scp /r sftp

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12670]
develop an OSGI “listener“ that will fire when a Static Push Publishing job has completed

The listener will transfer locally published files to a remote server via scp.

Via a config, will be able to specify the file path to a .pem identity file that will be used to authorize the remote connection and transfer. 

This listener will report back push publishing status to the UI to allow a dotCMS admin to monitor the success or failure of the remote publishing process within the dotCMS system.

The listener can be configured to push publish to one or multiple endpoints for each site and host.

**Comment by oarrietadotcms** [comment]
Work done here: https://github.com/dotCMS/core/issues/12250

**Comment by shaydotcms** [comment]
Needs work. Issue described in #13176
