### ISSUE TITLE
"Login As" feature does not allow changing to another user

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12672]
Tested on latest master

The "Change" button does not do anything after choosing the "Login As" and a user.

Screenshot: 
![loginas](https://user-images.githubusercontent.com/1569167/30882541-831bc968-a2c6-11e7-9602-9cee1585552a.jpg)

**Comment by erickgonzalez** [comment]
https://gist.github.com/erickgonzalez/373c133199a015f1015c25891eab38a3
