### ISSUE TITLE
[CMIS] : DotCMSObject.java is not making any reference to the new ContentType.java class

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12680]
We need to decide whether the ``DotCMSObject.java`` class should take both ``Structure`` and ``ContentType`` classes into consideration in its code:
* https://github.com/dotCMS/enterprise-2.x/blob/master/src/main/java/com/dotcms/enterprise/cmis/utils/DotCMSObject.java#L163
* https://github.com/dotCMS/enterprise-2.x/blob/master/src/main/java/com/dotcms/enterprise/cmis/utils/DotCMSObject.java#L261

## Expected Behavior
If necessary, both classes should be supported for now.

## Current Behavior
Only ``Structure`` is evaluated in the code.

## Possible Solution
Handle the ``ContentType`` class or leave it as it is.

## Known Workarounds
N/A

**Comment by wezell** [comment]
No, CMIS is deprecated and slated for removal.
