### ISSUE TITLE
Error on saving Form system filed on version 4.1 

### ISSUE THREAD

**Issue by ekelvin** [dotCMS/core#12684]
Error on saving Form system filed on version 4.1 like Title or the return page. 

## Expected Behavior
When creating a new form and editing a system filed like `Title` should be able to save the value

## Current Behavior
Seems like it is saved but if you return back the value is not there 
in console I found this error `Error: dwr.engine.incompleteReply, Incomplete reply from server`
I noticed the system fields in the created form are different from a sample Form. In the new one are type `hidden` in the sample form are type display.
## Steps to Reproduce (for bugs)

1. Create a new Form
2. Edit the Title field
3. return and check the value
4. the form can't be added in a container

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: chrome 64 bit Version 61.0.3163.91
* Operating System and version: Windows 10
* Application Server and version: 
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by wezell** [comment]
Fixed in the upcoming release.
