### ISSUE TITLE
Edit Content: In a select field, if double quotes are used in the value, the selected option is not kept

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#12689]
It is a similar case to the one reported on this issue: https://github.com/dotCMS/core/issues/12015. However, at the moment it was solved only for multiselect fields.

It was reported by a client: https://my.dotcms.com/tickets/detail.dot?id=594b6098-51a8-45e8-bc11-af273cb66575

## Steps to Reproduce (for bugs)

1. Create a content type that contains a single select field. Values in the select must contain double quotes
2. Create a new content for the single select content type, save and publish
3. Click on the created content for edition
4. Notice the select field, it did not keep the value saved previously on step 2

## Your Environment

* dotCMS version used: dotCMS 4.1.1/4.2.0
* Browser Name and version: Google Chrome

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/12690

**Comment by shaydotcms** [comment]
Passed QA.
Verified that single value is properly saved.
Tested locally on master branch / commit 0c7239bd6995aebdc178608665083a2875fbeda4
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
