### ISSUE TITLE
Push Publishing should update content with matching unique fields

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12686]
Tested on latest master
Follow up task associated with: https://github.com/dotCMS/core/issues/9886

**Case:**  A Content Type has **2 or more different unique fields**.  Currently we are checking all three values and only updating a piece of content on the receiver if EVERY one of the three unique fields is a match.  This means that we can create violation duplicates, because we are not updating the content bases on ANY matching unique field.  The should not be considered together, but independently when looking for a contentlet to update.

**Fix:**  IF **ANY** unique field content finds a match on the receiving server, FOR ANY unique field, then we should update the contentlet, and match the identifiers.  This will ensure that push publishing does not fail, that no unique key violations can be created on the same content type via push publishing, and that identifiers match on both sides.

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/enterprise-2.x/pull/543

**Comment by oarrietadotcms** [comment]
Passed QA, tested with Sender upgrade 3.7.1 -> 4.2, Receiver clean 4.2. Both Mac OS.
