### ISSUE TITLE
In a multi-select field, a comma is added at the end of the field when it is saved

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#12705]
For contents with multi-select fields, when one or more values are selected, a comma is added at the end when the field is saved. 

Reported by a client: https://my.dotcms.com/tickets/detail.dot?id=594b6098-51a8-45e8-bc11-af273cb66575

## Steps to Reproduce (for bugs)

1. Create a content type with a multi-select field
2. Add a new content for the content type
3. Verify the value saved for the field in ES Search

**Note:** A screencast was included

## Your Environment

* dotCMS version used: dotCMS 4.1.1
* Browser Name and version: Google Chrome

![edit-multiselect-field](https://user-images.githubusercontent.com/8741395/30996596-94f715a8-a487-11e7-8958-ed0439350b3a.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/12706

**Comment by shaydotcms** [comment]
Passed QA.
Verified that comma is not added at the end of the field when it is saved
![image](https://user-images.githubusercontent.com/8741846/31108733-4bf84096-a7b8-11e7-9f50-a94d5db11289.png)

Tested locally on master branch / commit 24394afa1602edf4bf975e3f6ef8013d337663f6
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
