### ISSUE TITLE
Unable to add portlet to existing tool

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12717]
Seeing this on upgraded authoring - I am unable to add a portlet to a tab

![screen shot 2017-10-02 at 12 32 25 pm](https://user-images.githubusercontent.com/934364/31088214-d97903a6-a76d-11e7-870a-8a6062eca018.png)

**Comment by fmontes** [comment]
Dups: https://github.com/dotCMS/core/issues/12635
