### ISSUE TITLE
Rules blows up UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12718]
This is on authoring which was upgraded to the release-4.2 nightly

1. Click Rules
2. Click another portlet
3. Click Rules Again

![screen shot 2017-10-02 at 12 38 01 pm](https://user-images.githubusercontent.com/934364/31088441-a9bca888-a76e-11e7-8d63-4a898548fc1e.png)

### Steps to reproduce

1. Add environments
2. Go to rules
3. Go to other portles
4. Go back to rules <-- crash.

**Comment by bryanboza** [comment]
Fixed, tested in the last master // chrome
