### ISSUE TITLE
Pagination UI is broken

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#12719]
Pagination UI is broken in the modal window dialog.

next, previous and results details are scrolling with the list.

Video
https://www.dropbox.com/s/r8phjj46pi2g0ow/modal-pagination-issue.mp4?dl=0

**Comment by jgambarios** [comment]
PR:
**Master:** https://github.com/dotCMS/core/pull/12729
**4.2:** https://github.com/dotCMS/core/pull/12733

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now works as expected
