### ISSUE TITLE
Trim url "to home" while in first portlet doesn't work

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12727]
As a stakeholder I want the routing to work as the user expect

## Expected Behavior
If the user is in any portlet and trim the url to be like: ```# || #/ || #/c || #/c/``` the app should go to the first portlet

## Current Behavior
If the user is in the **first portlet** and trim the url, the page goes blank.

## Possible Solution
[Here](https://github.com/dotCMS/core-web/blob/427a46ade8f15befff4c36a7a2dd7c69b6e8ff58/src/app/view/components/dot-navigation/dot-navigation.service.ts#L31) is where we listed to the change of the hash or the popstate event.

## Known Workarounds
Click in the first portlet does go there.

## Steps to Reproduce (for bugs)
1. Login
2. Wait for the first porlet to load
3. Trim the url to be like ```localhost/dotAdmin/#```
4. See how the pages goes blank.

**Comment by bryanboza** [comment]
Fixed, now we are redirecting to the first portlet
