### ISSUE TITLE
Routing QA to freeze 4.2

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12726]
### Issues to QA

https://github.com/dotCMS/core/issues/11979
https://github.com/dotCMS/core/issues/12661
https://github.com/dotCMS/core/issues/12673
https://github.com/dotCMS/core/issues/12688
https://github.com/dotCMS/core/issues/12660

### Known issues:
1. When you are in the first portlet and trim the url to go to home it’ doesn’t work (https://github.com/dotCMS/core/issues/12727)
2. Back button not updating the address bar: https://github.com/dotCMS/core/issues/12728
3. Confirmation messages keys not merged in core yet
4. User can't add content for "Media" content type
<img width="542" alt="screen shot 2017-10-03 at 6 55 38 am" src="https://user-images.githubusercontent.com/751424/31126173-16668c1c-a808-11e7-90e9-ccb85e3fb65d.png">

### Also working on
- [x] Iframe overlay error in the console
- [x] CanActivate || CanActivateChild not working with nested routes like /content-types-angular/add/xxx
- [x] Botton + disabled in IE11
- [x] Rules loading on IE11
- [x] Bring back loading indicator to login
- [ ] Content search not working FF with specific user: daniel@dotcms.com

**Comment by fmontes** [comment]
### Working on
- [ ] Iframe overlay error in the console
- [ ] Content search not working FF with specific user: daniel@dotcms.com
- [ ] Button + > Content > Media not working
- [ ] CanActivate || CanActivateChild not working with nested routes like /content-types-angular/add/xxx
- [ ] Botton + disabled in IE11
- [ ] Rules loading on IE11

### Known issues:
1. When you are in the first portlet and trim the url to go to home it’ doesn’t work (https://github.com/dotCMS/core/issues/12727)
2. Back button not updating the address bar: https://github.com/dotCMS/core/issues/12728
3. Confirmation messages keys not merged in core yet

**Comment by fmontes** [comment]
Another known issue: Messages keys for confirmation box are in PR not merge in core.

**Comment by fmontes** [comment]
** Not sure why but can't edit previous comments **

### Working on

- [ ] Bring back loading indicator to login

**Comment by bryanboza** [comment]
After the last testing we still having problems with the #12661

**Comment by bryanboza** [comment]
Waiting for this issue #12728

**Comment by bryanboza** [comment]
Fixed, after the fix #12728 now this is completed
