### ISSUE TITLE
Uploading file assets in IE11 does not work

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#12722]
This error has been reported by a client. When dotCMS is running on Linux and the browser client is IE11, the AjaxServletUpload may receive a Windows absolute path, it does not happen with all IE11 versions. When it happens, the file assets upload breaks because this condition fails https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotmarketing/servlets/AjaxFileUploadServlet.java#L157. **Note:** File.separator refers to the server filepath separator

This issue may be related to: https://github.com/dotCMS/core/issues/6214
Support Ticket: https://dotcms.zendesk.com/agent/tickets/91168

## Expected Behavior

Uploading file assets should work no matter the platform where the browser is running

## Your Environment

* dotCMS version used: dotCMS 4.1.1
* Browser Name and version: IE 11
* Operating System and version: Linux/Windows
* Application Server and version: Tomcat8
* Java Brand and version: JDK 8

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/12723

**Comment by bryanboza** [comment]
Fixed, tested on master // IE 11
