### ISSUE TITLE
We are unable to find the images in static sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12738]
We are unable to found resources when you do a static push and then try to use it

## Expected Behavior
We should be able to navigate and see normally the static site

## Current Behavior
We are unable to get the images 
SC: https://screencast.com/t/ItDkBHjljw

**FYI: Tested with a single push publish and works as expected** 

Also the images has been pushed to the S3 instance. And I'm able to see the image without problems if take the individual URL

## Steps to Reproduce (for bugs)
1. Login in BE
2. Create a new folder and upload some images
3. Crete a new page with a photo gallery widget and set the resources field to the same folder 
4. Try to navigate to this site in the static environment 

## Your Environment
Testing in the last master // postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/544

**Comment by bryanboza** [comment]
After the last changes we are unable to see the HTML pages in static sites.. 
https://screencast.com/t/UXazhM6RVuYC

**Comment by oarrietadotcms** [comment]
False alarm, it was a configuration problem with the static hosting from AWS S3. Also as important note the thumbnails of the photo gallery needs to remove the last "/" in order to work in AWS S3

**Comment by bryanboza** [comment]
Fixed, now we are able to see the images in the static site, we have pending the problem with the thumbnails, but will be moved to a new card...
