### ISSUE TITLE
Save portlet url when user tried to go but it's not login and then redirect on login

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12735]
As a stakeholder I want users to be able to go where they want as fast as possible

## Expected Behavior
If user tries to go to a portlet but it's not logged in, we should redirect to that portlet after user login.

## Current Behavior
If user tries to go to a portlet but it's not logged in, when he is login we are redirecting to the first portlet.

## Possible Solution
Maybe in the [dot-menu.service.ts](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-menu.service.ts#L36) we can save the portlet where the user it's trying to go and if then when we redirect after login we can check in the service if the prop exist then redirect to that portlet.

**Comment by bryanboza** [comment]
Fixed, now we are saving the portlet url... Nice fix
