### ISSUE TITLE
Content types angular portlet issues on iPad

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12736]
Here some issues we are having using the new portlet in the iPad 

- [ ] Unable to scroll the components list 
![img_0018](https://user-images.githubusercontent.com/2641437/31139901-2f6b0b16-a830-11e7-8124-06f35f6a68f2.jpg)

- [x] Unable to delete fields 
![img_0019](https://user-images.githubusercontent.com/2641437/31140022-7bd62e54-a830-11e7-9ede-e25baac76106.jpg)

- [x] The hide field isn't working 
![img_0020](https://user-images.githubusercontent.com/2641437/31140052-90d3dac2-a830-11e7-9d31-1fa24fb21340.jpg)

- [x] The update button is duplicating the content types 
![img_0021](https://user-images.githubusercontent.com/2641437/31140084-a9faffd0-a830-11e7-8b26-b3b9f1179f25.jpg)

- [ ] Problems when you scroll the portlet 
https://screencast.com/t/gZfwdM9jXiwn

**Comment by wezell** [comment]
Not targeting iPad for site builders.
