### ISSUE TITLE
[NC] Create add rows component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12748]
### Mocks

Disabled:

![disabled](https://user-images.githubusercontent.com/751424/31179964-92026cc4-a8da-11e7-847e-7e7e0416a9ba.png)

Enabled:

![enabled](https://user-images.githubusercontent.com/751424/31180055-d4d350e0-a8da-11e7-9c57-167b7784349d.png)

When click in add row:

![step 1](https://user-images.githubusercontent.com/751424/31180266-6b56628c-a8db-11e7-87a4-01b70118890e.png)

When hover or left-right in the keyboard:

![step 2](https://user-images.githubusercontent.com/751424/31180324-92cee686-a8db-11e7-9ef1-46fa3dd1d0aa.png)

### How it works
1. User click on add row
2. Animates slide up from "Add" button to "Select columns" state
3. After user select an amount of columns trigger event and go back to "step one"

### Keyboard
1. Left or right to highlight columns
2. Enter to select a column
3. Esc to to back to previous step.

### Events:
1. When user select the amount of columns it should be trigger an event with the number of columns.

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12875
