### ISSUE TITLE
[NC] Update the content type create/edit form

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12747]
![form2](https://user-images.githubusercontent.com/751424/31179413-27435d22-a8d9-11e7-9b17-3cc33363eb80.png)

**NOTE:** remove action will be moved to the listing.

### Create mode:
1. By default expanded with no edit button.
2. "Save" button should be disabled until the form is valid
3. Required fields should be mark with an * next to the label
4. When the user fill the form, submitted and the content type is saved, we should collapsed and show the edit button

### Edit mode
1. By default collapsed with edit button.
2. It will expand when: User click on edit button or user type something in the name field
3. When expanded edit button should be disabled
4. Update button should be disabled until user edit any of the form fields (that's include the name field)
5. Cancel will collapsed the form
6. If user change something in any field and the hit cancel, we should collapsed the form and left the form in the original state

### Keyboard shortcuts:
1. Enter should submit the form (if can be send)
2. Esc should cancel/collapsed the form
3. Tab should allow to move between fields

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Minor: Cancel and update buttons should be included in the tab order... You can access this buttons with the tab key

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Postgres // Chrome
