### ISSUE TITLE
[code] Remaining HibernateUtil.closeSessionSilently() call in PermissionBitFactoryImpl.java

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#12751]
Now that we have the DB annotations for connection handling, we should look into the ``PermissionBitFactoryImpl`` class, for example, this line: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java?utf8=%E2%9C%93#L2307

## Expected Behavior
All DB interactions need to be handled via the new dotCMS annotations.

## Current Behavior
There are places in code that are explicitly closing connections. This can cause problems with large transactions.

**Comment by wezell** [comment]
known issue
