### ISSUE TITLE
Unable to start up dotcms in mssql server due to issues with some tasks

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12759]
When using a fresh starter I'm unable to start up dotcms in mssql server due to issues with some tasks 
https://gist.github.com/shaydotcms/6e92539e6e36bbf0757a12edb1aad52b

## Expected Behavior
Dotcms should start up without issues in mssql server

## Current Behavior
Dotcms is not starting up in mssql server

## Steps to Reproduce (for bugs)
1. Set up a dotcms instance using mssql server
2. Check the logs to see the errors

## Your Environment
* dotCMS version used: dotcms 4.2 master branch / commit 0adf5b61643cab4558264e7fb0af544d12333397
* Database and version: SQLServer 2012
* Operating System and version: Win7 Pro SP1
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by jgambarios** [comment]
Closed as it is a dup of https://github.com/dotCMS/core/issues/12805
