### ISSUE TITLE
Update listing-data-table.component and add action to delete content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12758]
![listing table](https://user-images.githubusercontent.com/751424/31195532-e1435078-a907-11e7-9a6f-f86fdcd3f88e.png)

### About listing page 

So we can have 2 options of listing table:

1. User can't select rows
2. User can select more than one row using the checkbox

### So rows without checkboxes we need to add actions

We need to update the [listing-data-table.component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/listing-data-table/listing-data-table.component.ts)

1. Add a array param to pass actions for rows, (we can use the interface for [MenuItem](https://www.primefaces.org/primeng/#/menumodel) of primeng)
2. If the user pass an array with just one action we show directly the [icon with a tooltip](https://github.com/dotCMS/core-web/blob/da59b361aea32d57afd1f3e7ac39031a4b64bbaa/src/app/view/components/_common/icon-button-tooltip/icon-button-tooltip.component.ts) button
2. If the user pass an array of actions that have more than one options we use the ... [icon button](https://github.com/dotCMS/core-web/blob/master/src/styles/primeng-theme/components/_button.scss#L37) with the [menu](https://www.primefaces.org/primeng/#/menu) of options.

### Components
1. One action component: Update the [icon with a tooltip](https://github.com/dotCMS/core-web/blob/da59b361aea32d57afd1f3e7ac39031a4b64bbaa/src/app/view/components/_common/icon-button-tooltip/icon-button-tooltip.component.ts) component to be accesible and use the [icon button](https://github.com/dotCMS/core-web/blob/master/src/styles/primeng-theme/components/_button.scss#L37) under the hood.
2. More than one action component: Create a new button action component that is a combination of [icon button](https://github.com/dotCMS/core-web/blob/master/src/styles/primeng-theme/components/_button.scss#L37) with the [menu](https://www.primefaces.org/primeng/#/menu) of options.

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test
5. Implement the delete content type action on the content type listing.

**Comment by bryanboza** [comment]
For QA: The description of this card is about the listing-data-table.component, not related to content types portlet, this is a global component that can be reused in multiple portlets.

**Comment by bryanboza** [comment]
New related card reported here  #12991 

Now @wezell, @fishsmith since we don't have right click action on this new angular portlets, not sure if by default we should include the edit action on this table or not. We can edit just clicking the content type, but we also have this option in the old one.

**FYI: Right now we just have the delete action by default**

**Comment by bryanboza** [comment]
After test that, when you configure the push environment we have just the Push Publish option on this menu, we lost the "Add to bundle" option. 

SC: https://screencast.com/t/tdYFZHWC
