### ISSUE TITLE
VanityURL Services error deleting content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12757]
We are having an error when you try to delete some content type and this contains contentlets 

## Expected Behavior
We should be able to delete contents without problems 

## Current Behavior
We are having a VanityURL Services error in log 
SC: https://gist.github.com/bryanboza/083345f265d13c4ad7b19255c4e4a0ea 

## Steps to Reproduce (for bugs)
1. Create a new content type 
2. Add some pieces of content to this content type 
3. Try to delete the content type and all the content

## Your Environment
Tested in the last master // Postgres / FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12787

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now we have a WARN message...
