### ISSUE TITLE
File Content Types are not respecting Permissions set on the Content Type

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12764]
Observed on latest master

For some reason, limited users are always allowed to "Save/Publish" on File Content Types only, even if the content contributor role only has save on the File Content type.  This aberrant behavior is only on File Content types.  I tested regular content types and page content types and this does not happen.

To duplicate, edit the File Asset Content Type Permissions and give the Contributor role edit permissions but not publish.  Log in as Joe Contributor, he will be able to publish new files that he adds to directories even though he does not have publish permissions on the File Asset Content Type.  This is also true for new File Content Types that you add to the system as well.

screencast: https://screencast.com/t/GCn8cs3sA6Q

**Comment by dsilvam** [comment]
We were able to reproduce on demo (4.1.1) and even demo3 (3.7.1)

**Comment by DeanGonzalez** [comment]
Yeah, this apparently has been broken for a while, probably tied to something hard-coded in the default workflow scheme that is tied specifically to File Content Types.  We need to remove the "Save/Publish" option if the File Content Type is INDIVIDUALLY PERMISSIONED and does not have Publish rights on the File content type.  That is the way ALL other content types behave.  It appears to be a mistake that has been around for a while, and just now got caught by a client.

**Comment by dsilvam** [comment]
PR release-4.2: https://github.com/dotCMS/core/pull/12789

**Comment by DeanGonzalez** [comment]
Needs Work.  If I give a limited user Edit on a file content type, and only add children on a folder and view on child content/files - the limited user should NOT be allowed to save to that folder.  This should require edit or save/publish permissions for content/files as children of that folder.  However, the save is currently being allowed, which is incorrect. screencast: https://screencast.com/t/kB8DxARqegh

**Comment by DeanGonzalez** [comment]
These permissions on a folder should NOT be allowing save of files to that folder: https://screencast.com/t/H5nrQd2ajg

**Comment by DeanGonzalez** [comment]
Needs work: Limited user should not be able to save to a folder with these permissions:
![permissions](https://user-images.githubusercontent.com/1569167/31451778-384217c6-ae6a-11e7-9481-ab320fb1d97a.png)

**Comment by dsilvam** [comment]
Issue reported here was caught in a different ticket. Passing this one as it solved issue in the description.
