### ISSUE TITLE
[REST API] Contents that were already related are dropped if REST call does not include Relationships

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12761]
Our current REST API documentation states that, for a content being updated, existing relationships need to be passed in under the same call, by placing:

- The relationship name.
- Lucene Query.

However, REST API endpoints for our latest release: 

- Do not include related contents (if any) as part of the contents set/list being pulled using these Endpoints. 
- Any user-friendly method that helps users to pull related contents given a Query or Content identifier, along with information about relationships involved for this content.

So, for update tasks, it's a bit counter-intuituve to explicitly specify which contents we should relate to the one we're updating:

- Not all relationships may be required under this scenario.
- A content creator/editor wouldn't know if this is a required thing to do, of if it requires human intervention to do so.
- Other ways to update contents (backend, Imports via CSV file) don't require any human intervention, and existing relationships are retained if they're not modified by the content editor.

## Expected Behavior
If NO relationships are specified during a XPUT request (for updating contents) and existing content already has relationships, these ones must be retained.

## Current Behavior
Contents being updated via REST API calls get their related contents dropped if no relationships info is specified on the actual call.

## Known Workarounds
Follow the guidelines here https://dotcms.com/docs/latest/save-content-using-rest-api#relationships

## Steps to Reproduce (for bugs)

1. Login to the Backend. 
2. Create a Blog Content and relate two Comments to it.

Content Tab:
<img width="1663" alt="screen shot 2017-10-04 at 2 57 14 pm" src="https://user-images.githubusercontent.com/1717110/31199350-5bd2a74c-a914-11e7-9ee5-c5ab110f0240.png">

Relationships Tab:
<img width="1666" alt="screen shot 2017-10-04 at 2 55 34 pm" src="https://user-images.githubusercontent.com/1717110/31199379-6acd4892-a914-11e7-8479-9ea0fc5e10d5.png">

3. Pull the content you created via REST API call: 

```
$ curl -v -u "admin@dotcms.com:admin" -XGET http://localhost:8080/api/content/query/+identifier:fc537e87-af8c-426d-b0d2-e4ac188bbb8e
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* Server auth using Basic with user 'admin@dotcms.com'
> GET /api/content/query/+identifier:fc537e87-af8c-426d-b0d2-e4ac188bbb8e HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=27D830E23242D1C4121FDB0ACEFF1FD4; Path=/; HttpOnly
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Headers: Authorization, Accept, Content-Type, Cookies
< Content-Type: text/plain
< Content-Length: 581
< Date: Wed, 04 Oct 2017 20:56:05 GMT
< 
* Connection #0 to host localhost left intact
{"contentlets":[{"owner":"dotcms.org.1","identifier":"fc537e87-af8c-426d-b0d2-e4ac188bbb8e","modDate":"2017-10-04 14:55:42.0","urlTitle":"test-content-001","author":"Jose Orsini","languageId":1,"commentscount":0,"title":"Test Content 001","sysPublishDate":"2017-10-04 14:15:00.0","body":"<p>TEST BODY<\/p>","inode":"c33ee847-1f6f-41d2-9536-aee3745f2ea5","folder":"SYSTEM_FOLDER","__DOTNAME__":"Test Content 001","sortOrder":0,"modUser":"dotcms.org.1","host":"SYSTEM_HOST","lastReview":"2017-10-04 14:55:42.0","topic":"Retirement","stInode":"799f176a-d32e-4844-a07c-1b5fcd107578"}]}
```

As you can see, there is no additional info about the related contents here.

4. Update the content you created via REST API call, without specifying the Relationship involved there and a query to pull contents already related to the Blog entry.

```
$ curl -v -u "admin@dotcms.com:admin" -XPUT http://localhost:8080/api/content/publish/1 -F 'json={"stName":"Blog","identifier":"fc537e87-af8c-426d-b0d2-e4ac188bbb8e","title":"Test Blog 001","urlTitle":"test-blog-001","author":"Jose Orsini Updated through curl","body":"<p>Test content 001, updated again<\/p>","topic":"Retirement","sysPublishDate":"2017-10-04 14:15:00.0"};type=application/json'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* Server auth using Basic with user 'admin@dotcms.com'
> PUT /api/content/publish/1 HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 446
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------92d045a6003d539e
> 
< HTTP/1.1 100 Continue

< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=87EFB001983C2580A1C9017744AB7662; Path=/; HttpOnly
< Location: http://localhost:8080/api/content/inode/5114ff26-af9d-4468-9292-02216cc2b286
< inode: 5114ff26-af9d-4468-9292-02216cc2b286
< identifier: fc537e87-af8c-426d-b0d2-e4ac188bbb8e
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Headers: Authorization, Accept, Content-Type, Cookies
< Content-Length: 0
< Date: Wed, 04 Oct 2017 21:01:03 GMT
< 
* Connection #0 to host localhost left intact
```

Content tab of new version:
<img width="1391" alt="screen shot 2017-10-04 at 3 01 25 pm" src="https://user-images.githubusercontent.com/1717110/31199543-f5c0cdf2-a914-11e7-91d2-0aefc11be595.png">

Relationships Tab:
<img width="1391" alt="screen shot 2017-10-04 at 3 01 33 pm" src="https://user-images.githubusercontent.com/1717110/31199547-fc847864-a914-11e7-9340-80494335a79f.png">

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94432

## Your Environment

* dotCMS version used: 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App Server.
* Java Brand and version: Java 8u121.
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by wezell** [comment]
We need to create an integration test that creates content with categories and relationships and then calls the simplest ContentletAPI.checkin(contentlet, user, bool) method and make sure that the checked in content MAINTAINS the relationships and categories.

We should test multiple relationships 1-n and n-n (non-required) and 1-n and n-n (required)

**Comment by joseorsini** [comment]
Closed original PR since new changes introduced by @dsilvam are more efficient and updated. https://github.com/dotCMS/core/pull/12762

**Comment by DeanGonzalez** [comment]
Added a special note about Relationships being preserved on update here: https://auth.dotcms.com/docs/latest/save-content-using-the-rest-api#jsonCreateUpdate

**Comment by DeanGonzalez** [comment]
Updated both child and parent doc, and checked that same relationship / other related contentlets were maintained after the update. - passed QA
