### ISSUE TITLE
JSP error fixing content types integrity conflicts with relationships 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12760]
We have an error when you try to open some of the containers of the related content type

## Expected Behavior
We should update the changed identifier in the relationship to avoid this kind of errors 

## Current Behavior
When the system try to find the related content of this content types, the system is unable to get the related parent structure, this because is trying to get this with the old identifier 
SC: https://gist.github.com/bryanboza/2ae6a013d05611301ebbda9d3197eae3

## Steps to Reproduce (for bugs)
1. On receiver side create 2 new pages content types with this names  (CT1 and CT2)
2. Add a new relationship (CT1 - CT2) parent required 
3. Add related pieces of content to both content types
4. On sender create a new content types called (CT1)
5. Run the integrity checker 
6. Fix the content type conflicts 
7. Go to receiver side and try to open some of the containers of CT2

## Your Environment
Tested on master // postgres // FF this on both sides

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12785

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
