### ISSUE TITLE
Retry event is sending again to all the endpoints if the bundle fail in some one 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12777]
Since the changes in the retry event, now we are able to send the bundle just to the failed endpoints or to all endpoints if you want. 

But if the bundle fail, we automatically are sending to all the endpoints. 

## Expected Behavior
To decrease the response time, and increase the performance, if the bundle fail in one of the endpoints, the system should resend this just to the failed one, not to all. 

## Current Behavior
We are resending to all the endpoints 3 times 

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Add two endpoints to this environments (one valid and other invalid)
3. Try to send some bundle  
4. Make sure after fail sending to the invalid endpoint, we are resending just to this one 

## Your Environment
Tested on master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12837

**Comment by bryanboza** [comment]
Fixed, tested on the last release-4.2 and now we are just sending to the failed endpoints.
