### ISSUE TITLE
Loading indicator not showing in login

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12782]
As a stakeholder I want to users have visual information while wait for actions in the app.

## Expected Behavior
When user click in the login button we should hide the button and show the loading indicator in it place.

## Current Behavior
When user click the login button it hides but is not showing the loading indicator.

## Possible Solution
1. We have a [new loading-indicator.service](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/iframe/dot-loading-indicator/dot-loading-indicator.service.ts) with show and hide method.
2. Loading indicator in the [login.component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/login/login-component/login.component.html#L53) is using a class property for but needs to be update it to use the service.

### Aceptance Criteria
1. Update unit tests
2. Multilanguage
3. Make sure it works in all the supportted browsers (iPad and IE11)

**Comment by bryanboza** [comment]
We are having problems here because now, the penalization with the wrong attempts isn't working, you can try multiple times with wrong credentials and we are not penalizing

**Comment by fmontes** [comment]
This delay it's being done in the backend, the request it's been delay in the backend BUT only when the user is valid, we should do this for any user, valid or invalid, but it's a backend work.
