### ISSUE TITLE
Archived File Versions showing Saved Icon

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12784]
Tested on latest master, even re-indexed and cleared dotCMS cache, browser cache

An archived document should never also show a saved icon.  Only status light should be archived.  Right now unpublishing and archiving a file shows both.

Screenshot:
![savedarchived](https://user-images.githubusercontent.com/1569167/31258149-623d889a-a9fa-11e7-9a34-d97a79bf0559.png)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12888

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
