### ISSUE TITLE
Can't add Key/Values or Vainity Url conten types angular

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12781]
As a stakeholder I want users to be able to add ALL TYPES of content types.

## Expected Behavior
Users should be able to add: **Key/Values** and **Vainity Url from** ```angular-content-types```.

## Current Behavior
Users are only able to add: Content, Widget, File, Page and Persona.

## Possible Solution
1. We are hardcoding the options [here](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/content-types/main/content-types.component.ts#L61)
2. We should be using the basetypes endpoint (```/api/v1/contenttype/basetypes```) to populate this options.
3. We have a [service](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-contentlet.service.ts) to handle the request to basetypes endpoint.
4. Here is the [service](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/content-types-info/content-types-info.service.ts) to get icons and other base type info.

**Comment by fmontes** [comment]
Doing it in: https://github.com/dotCMS/core/issues/12667

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres
