### ISSUE TITLE
Jenkins might not run on release branches if more than 100 branches

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12788]
We are getting only one page of branches from github api, with page_size=100, which the maximum page size. If we have more than one hundred branches, we might run into the scenario that release branches don't get it in the first page, thus, not running at all. 

Need to find a way to either search, or iterate through and process all the pages.

**Comment by nollymar** [comment]
A change was applied on task **Build_Full_Seed** to iterate over pages (default page size=100)
