### ISSUE TITLE
Unable to push html pages after push remove the parent folder and try to push again 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12780]
We have an error when you try to push  html pages, and you has been deleted their parent folder via push remove

## Expected Behavior
We should push an the page without problems 

## Current Behavior
The system is showing an error and the page isn't pushed 

Log: https://gist.github.com/bryanboza/adb23e7db16d4cfbb0a57bae2f6ad75a

**FYI: If you try force push this works normally**

## Steps to Reproduce (for bugs)
1. Login 
2. Configure your push environment 
3. Crete a new folder
4. Add a new page in to the folder  
4. Push the page
5. Push remove the folder 
6. Unpublish the page
7. Try to push again the page 

## Your Environment
Tested on master // Postgres // Chrome

**Comment by oswaldogallango** [comment]
I could reproduce the error. the unpublish page is being pushed to the receiver server.

**Comment by jgambarios** [comment]
Not a bug, this is the expected behaviour.
