### ISSUE TITLE
Cache velocitymacros to disk by default

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12796]
If you cache the velocity templates `cache.velocitycache.chain` to anything not in memory (H22, Redis, Hazelcast) you should also cache the `cache.velocitymacrocache.chain` to the same chain because if the you call an uncached velocity macro defined on a velocity template that is in cache, the macro will return null.

We just need to change our defaults and doc.

**Comment by dsilvam** [comment]
PR 4.2: https://github.com/dotCMS/core/pull/12798

**Comment by wezell** [comment]
@joseorsini @nollymar  This is the right answer for this issue:

https://my.dotcms.com/tickets/detail.dot?id=1e84356a-af5a-4bf1-9995-95d6331d319c

**Comment by joseorsini** [comment]
@wezell So we should send that recommendation for customers on 4.1.1 dealing with issues related to velocitycache, along with this one? https://github.com/dotCMS/core/issues/12523

**Comment by wezell** [comment]
Yeah, as long as they have nollymar's hotfix
