### ISSUE TITLE
Upgrade Hazelcast to 3.9+

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12790]
Master is currently in 3.8.4. Let's upgrade to 3.9.+ Lot's of fixes.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/13371

**Comment by shaydotcms** [comment]
Passed QA.
Tested with 2 nodes and data/assets are replicating successfully. Network tab is showing green status for both.
Tested on master branch / Mac OS 10.10 / Postgres 9.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
