### ISSUE TITLE
Vanity URLs upgrade to 301s, should be forwards

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12809]
When the automated upgrade task runs to upgrade vanity urls, it seems that it makes them all into 301/redirects.  This can break some implementations that rely on the transparent forwarding - for example, it broke our "Request a license" link on dotCMS.

Looking at our upgraded dotcms.com it seems that all the converted vanity urls are 301/redirects.

I think vanity urls that start with / need to be converted to 200/forwards and vanity urls that `.contain("//")` should be converted to 301/redirects.

Either way we do this, there are going to be cases where we get it wrong. We will need to message this in the change log.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12838

**Comment by bryanboza** [comment]
Fixed, tested in the last master // Win10 // MSSQL and now we migrate the vanities with the respecting codes https://screencast.com/t/n6gCvySj
