### ISSUE TITLE
Add system status REST endpoint

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#12804]
We need an endpoint that reports system status outside of actual dotCMS content for monitoring purposes. 

Proposed URL: `/api/vX/system-status` (X as current api version)

It should monitor the following components:
- db connectivity
- assets availability
- index availability
- cache availability

Basic status reported by HTTP status code:
- 200: All components working as intended, frontend and backend requests should work as intended
- 507 (Insufficient storage): One or more components needed to store changes have failed and backend access should be considered failed. All components needed for frontend page requests are operating as intended and the system should be servicing frontend requests correctly
- 503 (Service Unavailable): One or more components needed for core functionality has failed, and the system is not expected to service frontend or backend requests correctly.

Extended status should be output in json array, example as follows:
```
{
  "StatusCheckResults": {
    "dbSelect": true,
    "cacheGet": false,
    "contentindexGet": true,
    "fileassetsRead": true,
    "fileassetsWrite": false
  }
}
```

Endpoint should have a builtin timer/killswitch for failfast logic, this API should **_never_** hang on any upstream API call.

(Preferred) Access to API should be restricted (403 on ACL denial) to specified CIDR ranges using config property (dotmarketing-config.properties):
`STATUS_API_IP_ACL="127.0.0.1,10.1.0.0/16"` (no mask = /32)

**Comment by wezell** [comment]
resolved by the system monitor plugin:

https://github.com/dotCMS/plugin-system-monitor
