### ISSUE TITLE
Unable to access to the pages/folder properties with right click as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12806]
We are having problems to access to the page/folder or element properties using the right click, this when you try to use the right click and you are as limited user 

## Expected Behavior
We should be able to see the element options when you right click something in the site browser 

## Current Behavior
We are unable to see the element menu, when you are as limited user 
SC: https://www.screencast.com/t/QIHUimihd5

## Steps to Reproduce (for bugs)
1. Create a new folder 
2. Create a new page in to the folder 
3. Grant full permissions to some limited user over this folder 
4. Login as the limited user 
5. Try to see the properties menu 

## Your Environment
Tested on master // Chrome

**Comment by wezell** [comment]
@fmontes  Is this merged with the 4.2.0 branch?

**Comment by bryanboza** [comment]
Fixed, tested on the last master, and now works fine
