### ISSUE TITLE
Race condition leaves host selector with no host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12803]
Many times when first logging into dotCMS, the host selector comes up empty.  If you refresh, it loads.  

I think we need a timer or something that will make sure that the host selector is properly filled.

![screen shot 2017-10-09 at 11 39 38 am](https://user-images.githubusercontent.com/934364/31348240-f68fe9e4-acec-11e7-9d93-30ab2133eb4c.png)

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/12807 (master)
https://github.com/dotCMS/core/pull/12854 (4.2)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the original case in the last master
