### ISSUE TITLE
Unable to import tags when you change some site to use their own tag storage 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12819]
We are unable to import tags, when you change some site to use their own tag storage and then try to import some tags, the system is showing a console error and we are unable to import 

## Expected Behavior
We need be able to import tags without problems 

## Current Behavior
We have a console error and you are unable to import
SC: https://www.screencast.com/t/LAfeU27z

![console](https://user-images.githubusercontent.com/2641437/31408757-ddc379be-adc6-11e7-8978-cc4ac7fad45d.png)

## Steps to Reproduce (for bugs)
1. Login 
2. Add a new site 
3. Change the tag storage to your own 
4. Go to the tag portlet and try to import tags 

## Your Environment
Tested on master // Chrome // MSSQL

**Comment by oswaldogallango** [comment]
I can't reproduce this error. the import tags box is displayed without problems

**Comment by bryanboza** [comment]
Unable to recreate in the last master...
