### ISSUE TITLE
We are losing the category level name after reorder

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12818]
We have lost this value after use the reorder features in the category portlet 

## Expected Behavior
This reorder should work normally without lose values 

## Current Behavior
We lose the level name, and show undefined 
SC: https://screencast.com/t/2wwbJ0WL

FYI: For now is a minor issue, just this value. 

## Steps to Reproduce (for bugs)
1. Login 
2. Navigate to types & tags --> categories 
3. On this portlet click to reorder button
4. Check the navigation tree 

## Your Environment
Tested on master // chrome

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12849

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
