### ISSUE TITLE
Need validate you have a pages content type selected before try to create a new page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12814]
We need validate if you have a page  content type selected in the drop down, this before to try to create a new page, to avoid errors because the system don't found the content type 

## Expected Behavior
We should validate you have some content type selected before advance 
<img width="1372" alt="limited" src="https://user-images.githubusercontent.com/2641437/31403428-4a1bff48-adb6-11e7-8bc1-d2ea9d0fcf4f.png">

## Current Behavior
When you try to create a new page as limited user and you don't have permissions over some pages content type, the system allow try to create a new page and we are having an error. 

SC: https://screencast.com/t/5qtg9sRh
Log: https://gist.github.com/bryanboza/7fae57d7b38a89c67bad5e7acae768a5

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Create a new folder and grant full permissions to some limited user 
3. Login as the limited user and try to create a new page into this folder
4. Without a content type selected click to the select button 

## Your Environment
Tested on master // Chrome

**Comment by wezell** [comment]
old browser will be going away.
