### ISSUE TITLE
Error when adding a new user in the receiver after pushing users bundle

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#12810]
After pushing a bundle of users, it is not possible to add a new user in the receiver using the UI

dotcms.log error: https://gist.github.com/nollymar/403c1c42070466835aef8510329c120a

Reported by a client: https://dotcms.zendesk.com/agent/tickets/94460

Probably currentId column in counter table is outdated 

## Steps to Reproduce (for bugs)

1. Using a fresh starter configure one server and one receiver 
2. Remove all default users except admin, admin2 from the receiver
3. Create a two users in the sender
4. In the sender, add the new users to a bundle, as well as an existing one (except admin, admin2)
5. Push the bundle
6. Try to create a new user in the receiver after pushing. This error is thrown: https://gist.github.com/nollymar/403c1c42070466835aef8510329c120a

## Your Environment

* dotCMS version used: dotCMS 4.1.1
* Browser Name and version: Google Chrome
* Operating System and version: Windows 10
* Application Server and version: Tomcat8
* Java Brand and version: JDK 8
* Database and version: MSSQL Server 2012/ Postgres

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/12831

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master...
