### ISSUE TITLE
Minor: Need use site instead host word in all the system 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12812]
We need use the same word in all the system to refer to the same thing, right now we are using sites, but we have some places that we are using host

## Expected Behavior
To be consistent we need use the same word in all the system, this to avoid confusions 

## Current Behavior
We are using Sites and Host 
<img width="1372" alt="site" src="https://user-images.githubusercontent.com/2641437/31402510-6c8c7218-adb3-11e7-86d2-e6fb56858f89.png">

## Your Environment
Tested on master // Chrome

**Comment by john-thomas-dotcms** [comment]
Note: The word "host" doesn't even appear in any of the strings in the Language.properties file any more (except where it's part of "System Host"), so any cases of this we have left are likely strings that need to be extracted into the Language.properties file anyway so they can be properly translated.
