### ISSUE TITLE
Avoid checking connection per each file when Static Publishing

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12825]
When static publishing, there is a validation to check if the connection is successful, but this is done per each file being transferred. This can be done only once per endpoint.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/546

**Comment by dsilvam** [comment]
Note to QA: Please test normal static push and also try to disconnect in the middle of the publishing and the how it behaves.

**Comment by shaydotcms** [comment]
Passed QA.
Static push continues sending the files where they left off when the connection was lost
