### ISSUE TITLE
[Contents] ContentMap cannot return Image/File info if language of asset and parent content are different.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12820]
Expecting content re-usability, it's possible to create contents on non-default languages and re-use existing assets for Image/File fields. However, when these contents are pulled in frontend pages, nothing can be returned for these assets because the original lookup is made using the parent content language.

So for example, we have this scenario

1. Create a Spanish Event in Starter site.
2. For Image field, add /images/404.jpg as value (this image is originally stored in English).
3. Create a Test Page in Spanish, and a Widget in Spanish that pulls this image. 

```
#set($content = $dotcontent.find("73b57f23-f066-4919-9d61-8bf58185b7c1"))

Content image is: $!{content.image}

<img src="/contentAsset/image/$!{content.image.identifier}/fileAsset">
```

This returns an empty string. It falls in this code 

https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotmarketing/viewtools/content/ContentMap.java#L169 

and it doesn't take into account the DEFAULT_FILE_TO_DEFAULT_LANGUAGE property (set to true by default).

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94495

## Your Environment

* dotCMS version used: 4.1.1
* Browser Name and version: Any Browser
* Operating System and version: Any OS.
* Application Server and version: Any app server.
* Java Brand and version: Java 8u121.
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
PR https://github.com/dotCMS/core/pull/12822

**Comment by bryanboza** [comment]
Fixed, tested on the last master
