### ISSUE TITLE
Push publish action need be added to the options button in the new UI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12821]
As part of the changes now we have a new button with some properties, in order to be compatible with touch devices, but we are losing some properties.

## Expected Behavior
We need all the available properties on this button when you select some element 

## Current Behavior
We are losing the push publish and add to bundle options on templates - containers - links 
<img width="1372" alt="options 1" src="https://user-images.githubusercontent.com/2641437/31411641-7236a23a-adcf-11e7-8f95-d806fc68ed07.png">

<img width="1372" alt="options 2" src="https://user-images.githubusercontent.com/2641437/31411644-74a9c542-adcf-11e7-8318-0e3317cb1d17.png">

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your push environment 
3. Go to Templates / Conteiners / Links portlet
4. Select some element 
5. Click on the "..." button
6. Make sure you have the same properties of the right click

## Your Environment
Tested on master // Chrome

**Comment by wezell** [comment]
known issue
