### ISSUE TITLE
NPE error importing tags with blank name/host

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12833]
Logs are displaying NPE error when there's an attempt to import tags with empty name/host Id, however UI says "Tags successfully imported "
https://gist.github.com/shaydotcms/d61c9ef412b2968b218e3914c6fd4d30

## Expected Behavior
System should validate when tag name/host id is blank.
UI should not display successful message.

## Current Behavior
System is not validating blank tag name/host id

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Type> Tags
3. To better visualize that tags are actually not being imported, delete the existing tags, however this happens also when there are existing tags.
4. Click button to Import Tags
5. Upload a .csv file containing tags with empty name but actual site identifier. You can import the .csv files attach here: 
[Tags empty name.zip](https://github.com/dotCMS/core/files/1376957/Tags.empty.name.zip)
[Tags empty host.zip](https://github.com/dotCMS/core/files/1377008/Tags.empty.host.zip)

6. You will see successful message in UI however tags were not imported. Check logs for errors
![image](https://user-images.githubusercontent.com/8741846/31462573-739cf0dc-ae8a-11e7-9af1-f17588a8f902.png)

## Your Environment
* dotCMS version used: dotcms 4.2 master / commit  cbee90a3c962b315fed01bfb96e68c677157ff24
* Database and version: Postgres 9.3.5
* Operating System and version: Mac OS 10.10.5 
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by dsilvam** [comment]
PR master: https://github.com/dotCMS/core/pull/12869

**Comment by bryanboza** [comment]
We still having problems with tags... New related issue open here #12903

**Comment by bryanboza** [comment]
Fixed
