### ISSUE TITLE
UI should notify when user tries to save a category with a long name

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12848]
When category name is too long, UI should let user know what is going on. Currently after you hit Save button, nothing happens.

## Expected Behavior
After you hit Save button, UI should let user know when category name is too long

## Current Behavior
System appropriately logs the restriction but UI not. Currently after you hit Save button, nothing happens.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Content Types> Categories
3. Create a new category
4. For the Name and/or Key, use a very long name, i.e.: Test with a Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Really Long Name
5. Hit Save button. You will see nothing happens.
6. System appropriately logs the restriction but UI not.

## Your Environment
* dotCMS version used: dotcms 4.2 master / commit cbee90a3c962b315fed01bfb96e68c677157ff24
* Database and version: Postgres 9.3.5
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
Add max length to category name fields

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/12864

**Comment by bryanboza** [comment]
Fixed.  Now we have limit on this field, then we are unable to exceed the max limit...
