### ISSUE TITLE
Categories' breadcrumbs are showing "undefined" after doing sort order

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12845]
After you do sort order, the breadcrumbs are changing from **Categories>Top Level** to **Categories>undefined**

## Expected Behavior
Categories breadcrumbs should not change from **Categories>Top Level** to **Categories>undefined**

## Current Behavior
Doing a sort order in Categories breadcrumbs are changing from **Categories>Top Level** to **Categories>undefined**

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Types & Tags> Categories
3. Click on Reorder button
4. Check the breadcrums

Before sort order:
![image](https://user-images.githubusercontent.com/8741846/31509078-6645a24a-af3d-11e7-8c4b-e23b0172076d.png)

After sort order:
![image](https://user-images.githubusercontent.com/8741846/31508923-dae58620-af3c-11e7-9729-fd61cb1cad85.png)

## Your Environment
* dotCMS version used: dotcms 4.2 master / commit cbee90a3c962b315fed01bfb96e68c677157ff24
* Database and version: Postgres 9.3.5
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/12818
