### ISSUE TITLE
Update FixTask00080DeleteOrphanedContentTypeFields

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12852]
This upgrade task does a IN scan that takes too much time to perform and transaction might be dropped for large databases.

In addition to that, making a DELETE query on field table does not cascade a deletion of the inode entries on inode table.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12853/files

**Comment by shaydotcms** [comment]
Passed QA.

Upgrade from dotcms_3.6 with client dataset to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

Upgrade from dotcms_2.5.7 with client dataset to master branch
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8

Upgrade from dotcms_3.3 with client dataset to master branch
Win7 Pro SP1 / SQLServer 2012 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8 /
