### ISSUE TITLE
Upgrades - Task03065AddHtmlPageIR not dropping old definition of table

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#12862]
We've ran into a few clients coming from 2.5.7 whose table htmlpages_ir is not properly defined. Moreover, running into the following exception when upgrading to latest 3.x or 4.x version is a common place for clients running on MS SQL Server:

```
FATAL runonce.Task03600UpdateMssqlVarcharTextColumns: Unable to execute SQL upgrade
com.microsoft.sqlserver.jdbc.SQLServerException: ALTER TABLE ALTER COLUMN failed because column 'local_working_inode' does not exist in table 'htmlpages_ir'.
```

This table appears for first time in our db creation scripts on dotCMS 2.5.7: https://github.com/dotCMS/core-2.x/blob/2.5.7/sql/cms/dotcms_extra_mssql.sql#L793 (example is from our MS SQL Server script, but the same applies to the other db scripts), and then it disappears from the scripts on 3.0 and 3.0.1. A new definition is introduced on 3.1: https://github.com/dotCMS/core/blob/3.1/src-conf/mssql.sql#L3460 , and an upgrade task takes care of creating it for clients coming from older versions: https://github.com/dotCMS/core/blob/3.1/src/com/dotmarketing/startup/runonce/Task03065AddHtmlPageIR.java .

The problem is that the upgrade task creates the table only if it doesn't exists. For clients who started on 2.5.7 with a different definition of the table, the upgrade task does nothing: https://github.com/dotCMS/core/blob/3.1/src/com/dotmarketing/startup/runonce/Task03065AddHtmlPageIR.java#L44-L54

## Expected Behavior

Task03065AddHtmlPageIR should take into account that the table may exist in the database and then either make the necessary alterations or drop/recreate the table.

## Current Behavior
The upgrade task does nothing and the table remains in the database with the wrong definition.

## Possible Solution
Drop the table and create it again.

## Known Workarounds
Run scripts to drop the table and create it again.

## Steps to Reproduce (for bugs)
1. Start up a brand new 2.5.7 instance
2. Upgrade to anything between 3.1 and 3.7.1
3. Check the table definition after upgrading
4. If using MS SQL Server, upgrade to 3.7.1 should fail on Task03600UpdateMssqlVarcharTextColumns

## Context
Reported by several supported clients:
https://dotcms.zendesk.com/agent/tickets/93459
https://dotcms.zendesk.com/agent/tickets/94470
https://dotcms.zendesk.com/agent/tickets/91882

## Your Environment
* dotCMS version used: 2.5.7 - 3.7.1
* Database and version: MS SQL Server 2016

**Comment by bryanboza** [comment]
Fixed, tested with a real dataset and now we are able to upgrade from 2.5.7 to 4.2.1 .
