### ISSUE TITLE
Content type edit with unknown id breaks the app

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12876]
As a stakeholder I want users that the app respond to all the posible scenarios in the routing.

### Expected behavior
If the users goes to the route ```/content-types-angular/edit/unknown-id``` we should redirect to ```/content-types-angular/```

### Current behavior
If the users goes to the route ```/content-types-angular/edit/unknown-id``` the app crashed.

### Possible Solutions
Not sure, we can discuss.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
