### ISSUE TITLE
Webdav failing in Finder for Folder names with Capital Letters

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#12873]
Tested on latest master

Easy to reproduce, but this behavior seems to be only in Finder and only with folder names that have capital letters.

To Reproduce:
1) Create a few directories on your local host whose names are InitCapped and place a few files in each folder
2) Establish a webdav connection thru Finder on a Mac and drag the folders over to create them on the dotCMS server.  BUG: Webdav fails to move the files over to the server after creating the lower cased folder names.

![webdaverror](https://user-images.githubusercontent.com/1569167/31633336-4570f270-b27d-11e7-8435-3367aefe791b.png)

Dragging folders works if you lower-case the folders before you drag.

**Comment by wezell** [comment]
And Capital letters works with cyberduck?

**Comment by dsilvam** [comment]
They do @wezell

**Comment by wezell** [comment]
dupe issue
