### ISSUE TITLE
System is not showing accurate number of existing comments for News

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12874]
System is not showing accurately how many comments exist for News. It shows "0 Comments" or "No Comments" when there are existing comments.

## Expected Behavior
Number of comments should match

## Current Behavior
System is not displaying accurately the number of existing comments.

## Steps to Reproduce (for bugs)
1. Start up a dotcms instance and access this link in the browser: localhost:8080/news/the-gas-price-rollercoaster
2. Notice that this news say **No Comments** but when you scroll down, you will see there are actually **4 comments**
![image](https://user-images.githubusercontent.com/8741846/31635923-cf388272-b285-11e7-97dc-43ee0bb6bade.png)
![image](https://user-images.githubusercontent.com/8741846/31635928-d97386b0-b285-11e7-8c65-24789458ca48.png)
3. Login to the backend and navigate to Content> Search
4. Filter by News and click on "The Gas Price Rollercoaster"
5. Click on "Relationship" tab. You will see the relationships do exist
![image](https://user-images.githubusercontent.com/8741846/31636038-3e5dfae2-b286-11e7-9f8e-36ce2a14263b.png)

## Your Environment
* dotCMS version used: dotcms 4.2 master / commit 0749f1057e0019dd5c94aa31a9f007d3194ee5aa
* Database and version: Postgres 9.3.5
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
Need to update our starter impl
