### ISSUE TITLE
Pushing System Folder fails because of validations in FolderAPIImpl

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12878]
See more details https://dotcms.zendesk.com/agent/tickets/94548

Since System Folder is added as a dependency once contents are pushed, the current validations on FolderAPIImpl.save may return an unexpected exception in dotCMS 4.1.1. The way we're retrieving the parent permissionable for System Folder is not properly validated, since it should be inheriting permissions from System Host. However, the code states that

- Parent folder is pulled dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java In this case, System Folder does not have a parent folder, so it brings itself back from the API.
- It asks for permissions over its parent folder, so it falls into a bad state here https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java#L558 should be assigning the parent Site, in this case, System Host.

The default behavior here is that:

- For Push Publishing scenarios, this folder will ALWAYS be edited/modified by System User.
- System User has CMS Administrator role, and permissions validations here are skipped for this particular user.
- We should ask for the right permissionable parent here, which is System Host.
- Send a more detailed exception in case the parent permissionable is a Site, not a folder. Therefore, the exception will throw a NPE, breaking more things in the process.

**Comment by joseorsini** [comment]
New PR: https://github.com/dotCMS/core/pull/13124

**Comment by jgambarios** [comment]
Closed as after talking with @joseorsini we realized is not a longer valid case.

**Comment by cfalzone** [comment]
Interested why this was closed as no longer a valid case?  

We have a hotfix for this issue running in our production on 4.1.1 and it was necessary. 

See our helpdesk ticket on this:  https://helpdesk.dotcms.com/hc/en-us/requests/94548

**Comment by oarrietadotcms** [comment]
@joseorsini @jgambarios Could you please explain why this one is not a valid case? Chris Falzone is waiting for an answer here. Thanks.

**Comment by joseorsini** [comment]
@cfalzone @oarrietadotcms @jgambarios hi guys. By the time the potential fix here was tested, we weren't able to get it reproduced. Even after reviewing and building unit tests that could have led this issue to be reproduced, it was not possible, therefore the fix was not necessary anymore for 4.2.x/4.3.x releases.
