### ISSUE TITLE
Missing User mod_date column on migration

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12887]
We have errors migrating directly to latest 4.2 from old dotCMS versions (2.x), and the reason is because at some point in 4.x we added a **mod_date** column to the **user** table, with that column we modified the hibernate mappings for the user table and added an upgrade task, the problem with the migration is that we have the hibernate mapping with the new **mod_date** column but the **InitServlet** tries to get the System User before to run the upgrade task that is going to add the new **mod_date** column and hibernate fails because the mapping have a column the table does not have.

## Expected Behavior
A direct migration to 4.2 should work

## Possible Solution
Change the failing method that load the user using hibernate to use **dotConnect** instead.

**Comment by john-thomas-dotcms** [comment]
Note: I'm not sure if this is related, but in the 4.1 release notes we say that to migrate to 4.1 from an earlier release you first need to migrate to 4.0.  Does it work to migrate first from 2.x to 4.0, and then from 4.0 to 4.2?

**Comment by jgambarios** [comment]
**Note to QA:** Please make sure that direct migrations to latest master is working maybe from a 2.x distribution.

**Comment by bryanboza** [comment]
Fixed, tested upgrading from 2.5.7 to master // postgres... New card updated here: #12916
