### ISSUE TITLE
Workflows: Exception occurred processing JSP page file

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12886]
We are having an exception processing a JSP file when you are using workflows 

## Expected Behavior
We need validate this exception and be able to resolve the workflow or send an specific error if is necessary 

## Current Behavior
We are showing an unexpected error and have an error on logs 
Log: https://gist.github.com/bryanboza/7b3399f8b07f11118584a9ef9d6048f7
SC: https://screencast.com/t/HQZ56s0i

## Steps to Reproduce (for bugs)
1. Login as limited user and upload a new document (Joe/Joe)
2. Send for Review 
3. As admin go to the tasks portlet and open this document 
4. Add a new file located in some restricted folder (root of the site)
5. Login as published user and try to open this document 

Here the video: https://screencast.com/t/V6RrsYOe

## Your Environment
Tested in the last master // postgres // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12892

**Comment by bryanboza** [comment]
After test in the last master, we still having problems with the same JSP file, but now when you try to access to the content portlet... 

LOG: https://gist.github.com/bryanboza/deb440c82fdad0db5e676189f9ddec57

Also maybe we need remove all the stack trace of the dotSecurityException in the dotcms.log file, just with a small error is ok.

**Comment by oswaldogallango** [comment]
@bryanboza I was Unable to reproduce this issue in my local environment. I tried with differents Db's, also with a new clean tomcat download and nothing. I can't get the error you have.

**Comment by bryanboza** [comment]
Fixed, after compile again all the jsp files this works as expected
