### ISSUE TITLE
Reindex error after delete users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12881]
We have an error when you try to delete some user, this because the relation does not exist

## Expected Behavior
After you delete some user we need be able to auto-reindex without problems 

## Current Behavior
We have an error with the relation and the system is unable to reindex
SC: https://gist.github.com/bryanboza/f6fc8d16f1e2c560cacda7a811ad125b

## Steps to Reproduce (for bugs)
1. Login 
2. Go to system --> users 
3. Select some user and goto user detail tab
4. Delete the user 
5. Select other user to replace 
6. Delete

## Your Environment
Tested on release-4.2 // postgres // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12912

**Comment by jcastro-dotcms** [comment]
New PR: https://github.com/dotCMS/core/pull/12953

**Comment by bryanboza** [comment]
Fixes, tested in the last master // Oracle, MySQL and Postgres // Chrome
