### ISSUE TITLE
Notification need translation if you use italian as default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12880]
If you use Italian as language, the notification stuff continue showing in English 

## Expected Behavior
We should have translation in every supported language 

## Current Behavior
If you use italian all this stuff still showing in English

<img width="1372" alt="italiano" src="https://user-images.githubusercontent.com/2641437/31682307-e1f4633e-b336-11e7-80a2-668145186763.png">

## Your Environment
Tested on release-4.2 // Postgres // Chrome

**Comment by jgambarios** [comment]
**Note to QA:** Unable to reproduce.

**Comment by fabrizzio-dotCMS** [comment]
Unable to reproduce the issue. 
I tried generating notification items on different instances of the application using a different locale and the notifications generated on the fly are displayed correctly. 
Tested using Italian, Spanish and English
