### ISSUE TITLE
NPE importing tags

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12903]
Related to #12833 

We have an error when you try to import some tags from a CSV file and this contains a bad host_id 

## Expected Behavior
We should be able to catch this error and continue with the other tags of the CSV

## Current Behavior
We are having a NPE error and we are unable to import the tags 

Log: https://gist.github.com/bryanboza/dd35a02152d86aa850ad4e835ba1bf31

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to types and tags  --> Tags
3. Try to import some tags from a CSV file (this should have a wrong site_id in the host column)
4. Check the dotcms.log file 

## Your Environment
Tested on the last master // postgres // FF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12906

**Comment by bryanboza** [comment]
Fixed, now we have a small message error in the logs... Tested on master // H2 // FF
