### ISSUE TITLE
Fixed global value for SYSTEM_FOLDER identifier

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12904]
We also need an upgrade task to update the existing SYSTEM_FOLDER record with fixed id

**Comment by shaydotcms** [comment]
Passed QA.
Upgrade task is showing in logs and db.
Tested locally on master branch / commit 7edc777c8362408af192f57d7e0d7c464ca06185
Win7 Pro SP1 / SQLServer 2012 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by dsilvam** [comment]
Note to QA: Please test with large datasets

**Comment by shaydotcms** [comment]
Needs work. Waiting for card #12971

**Comment by shaydotcms** [comment]
Passed QA.
Upgrade task is showing in logs and db.
Tested after upgrade from dotcms_3.x and 2.x with client dataset to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
