### ISSUE TITLE
Take identifiers out of hibernate

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12905]
We need to use straight sql when working with the identifiers and the db.   inserting, updating deleting.

- [x] write tests for identifierfactory (https://github.com/dotCMS/core/issues/13045)
- [x] remove identifier from hibernate.xml
- [x] copy identifierFactoryImpl to a new impl and remove hibernateutil and hibernateexception
- [x] make sure new tests pass
- [x] make sure old tests pass (https://github.com/dotCMS/core/issues/13046)
- [x] insure import/export (starter) tooling still works.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13070
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/558
