### ISSUE TITLE
Replace String.replace with Pattern

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12907]
This call will compile the regular expression each time 
https://github.com/dotCMS/core/blob/87adf51dc8cfb13deab9f1a1f752ddcc3a325e07/dotCMS/src/main/java/com/dotcms/contenttype/model/field/LegacyFieldTypes.java#L146

This can be replaced by explicitly using a Pattern object

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12908
