### ISSUE TITLE
[REST] Include URL attribute for File/Page contents being pulled via REST API calls

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12910]
We should include URL attributes for files and pages being pulled through our REST API endpoints. 

For example this one 

https://demo.dotcms.com/api/content/query/+contentType:htmlpageasset 

pulls all Pages in demo site, however, URL field (which is a system field, indexed and user searchable) is not added to the results list.

The only way we have for pulling something close to an URL is this one 

https://demo.dotcms.com/api/content/id/bb7ca6fc-5025-4268-aca5-c077ed1e532a

However there's a bug in the system. We're pulling only the asset name, rather than the whole URI of the page/file 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/ContentHelper.java#L86  

## Context
Reported by customer https://dotcms.zendesk.com/agent/tickets/94579. Despite customer is running dotCMS 3.7.1, the information requested on REST API calls is no available on current release.

## Your Environment

* dotCMS version used: 4.2.0.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: Java 8u121
* Database and version: Any DB
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
PR https://github.com/dotCMS/core/pull/12913

**Comment by bryanboza** [comment]
Fixed, tested in the last master // Postgres // Chrome
