### ISSUE TITLE
Re-order Language.properties file and create standard for key names

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#12919]
The Language.properties file is currently difficult to deal with because of inconsistent naming of the keys and inconsistent ordering of the file.

## Expected Behavior

Suggestion discussed with Will is to do a one-time re-order of the strings file into alphabetical order, and implement a standard naming convention for the keys.

## Current Behavior

The Language.properties file is currently difficult to deal with because:

1. It's ordered in "historical" fashion, with some strings alphebatized, some in sections of related strings, some in the order they were added to the file, and some sections split in multiple places.
2. The naming of the keys is inconsistent, including differences in the case of keys, multiple keys referencing the same string, and some keys including the class where they're used while others are generic.
3. There are multiple duplicate keys for many of the strings.

## Possible Solution

1. Use a standard convention for naming string keys.
2. Sort the file into alphabetical order (and maintain it in that order).

Note: If a standard naming convention includes the class name where the string is used, the keys will automatically be grouped together when the file is sorted.

## Context

The inconsistencies cause a number of challenges:

* Make it difficult for developers to determine whether a string already exists (resulting in duplicates).
* Make it difficult to manage the translations with each new release (comparing the changes in the Language.properties file and identifying which strings have been translated in each of the other language files).
* Cause second order bugs and clutter (strings which are no longer used anywhere in code) when a string is changed, since existing keys may not be re-used, and duplicate keys with the same string may be missed and not changed.

## Your Environment

* dotCMS version used: 4.2.0

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14981
