### ISSUE TITLE
Edit Mode Reimagined

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#12928]
We are hoping to redo Edit Mode starting Nov 2017 with a release in March 2018. 

The primary functionality and features we to address are

- Overall modernization of Edit Mode
- We aim to make it easy for Content Contributors to be able to solely live on this screen
- Provide the ability to create a page with easy to use tooling such as DND, easy content placement, editing layouts all in a non technical way (no code)
- replace code in `APILocator.getTemplateAPI().getContainersInTemplate(` to only call the multi-tree

**Comment by wezell** [comment]
Completed in 5.0.0
