### ISSUE TITLE
Allow multiple of the same container to be used on a page

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#12931]
Also, containers need to be able to be nested and included at any level of page parsing

- [ ] Add an optional param to the parseContainer directive that specifies a unique (to a page) id for the container, e.g. #parseContainer("0812412-23423432-234234", "uuid (unique id of the container on the page)")
- [ ] #parseContainer("0812412-23423432-234234") still needs to work
- [ ] allow the multi_tree table to support multiple of the same containers on any page.  this means repurposing the relation_type field to store the unique id of the container on the page 
- [ ] delete the template_containers from hibernate and the db
- [ ] depreciate APILocator.getTemplateAPI().getContainersInTemplate. remove any use of that. Create a `APILocator.getContainerAPI().getContainersOnPage(HTMLPage)` that does a 
```
select unique(parent2) from multi_tree where parent1=?
```
and iterates over the ids to build a list of container.
- [ ] Multi-tree has to take the relation_type into account when multi-trees get deleted
- [ ] Startup task: add index on multi_tree.parent1

**Comment by jtesser** [comment]
![2017-10-27_1430](https://user-images.githubusercontent.com/1486445/32119482-649a4364-bb23-11e7-9e2a-d3f6cd7ddc76.png)

**Comment by dsilvam** [comment]
Being worked by Fox in other tickets
