### ISSUE TITLE
Oracle problem on startup

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#12937]
With the recent changes, and an oracle DB. dotCMS is not starting up. Is throwing and exception trying to import the users 

here is the log https://gist.github.com/oswaldogallango/41d2b3a4b3ce3b50bc95c8d160328274

## Steps to Reproduce (for bugs)

1. Set an oracle DB
2. startup dotCMS

## Your Environment

* dotCMS version used: master
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Related to** https://github.com/dotCMS/core/issues/12887

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12938

**Comment by bryanboza** [comment]
Fixed, now i am able to start normally using oracle
