### ISSUE TITLE
Create workflow task endpoint for new Content Type designer

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12935]
The new content type designer needs an endpoint that will 
1. display a list of workflows.  
2. send back workflow detail data if passed an id.

On the content type screen, we need to be able to support a multiple select.  I am a fan of the primeNG multi-select:

https://www.primefaces.org/avalon-ng/#/forms

**Comment by bryanboza** [comment]
Fixed, now this is working, new related enhancements reported on new cards

**Comment by bryanboza** [comment]
Fixed, now we are able to see the complete list of workflows, and set which one you want to use without problems
