### ISSUE TITLE
[Push Publishing] Force Push value is not accurate between environments

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12947]
Force Push attribute is not saved properly once a bundle is received on the Receiver environment.

## Steps to Reproduce (for bugs)

1. Star tup 2 dotCMS instances and configure Push Publishing for them.
2. On Server A, create a /test folder
3. On Server B, manually create a /test folder.
4. Don't run the integrity checker. For testing purposes, it's important to make it fail, so we can see the Force Push attribute different between environments.
5. Add the /test folder to a bundle called "test-bundle-001". Up to this point, the bundle is stored this way

```
mysql> select * from publishing_bundle where name = 'test-bundle-001';
+--------------------------------------+-----------------+--------------+-------------+--------------+------------+
| id                                   | name            | publish_date | expire_date | owner        | force_push |
+--------------------------------------+-----------------+--------------+-------------+--------------+------------+
| e1c41c50-0db9-430f-bbc2-d0f000590af8 | test-bundle-001 | NULL         | NULL        | dotcms.org.1 |          0 |
+--------------------------------------+-----------------+--------------+-------------+--------------+------------+
1 row in set (0.00 sec)
```

6. Go to Publishing Queue -> Bundles and Push this bundle. Make sure Force Push is checked.

```
mysql> select * from publishing_bundle where name = 'test-bundle-001';
+--------------------------------------+-----------------+---------------------+-------------+--------------+------------+
| id                                   | name            | publish_date        | expire_date | owner        | force_push |
+--------------------------------------+-----------------+---------------------+-------------+--------------+------------+
| e1c41c50-0db9-430f-bbc2-d0f000590af8 | test-bundle-001 | 2017-10-27 14:19:00 | NULL        | dotcms.org.1 |          1 |
+--------------------------------------+-----------------+---------------------+-------------+--------------+------------+
1 row in set (0.00 sec)
```

7. Wait for bundle to fail to publish and inspect data on Receiver environment:

```
mysql> select * from publishing_bundle where name = 'test-bundle-001';
+--------------------------------------+-----------------+---------------------+-------------+--------+------------+
| id                                   | name            | publish_date        | expire_date | owner  | force_push |
+--------------------------------------+-----------------+---------------------+-------------+--------+------------+
| e1c41c50-0db9-430f-bbc2-d0f000590af8 | test-bundle-001 | 2017-10-27 14:20:02 | NULL        | system |          0 |
+--------------------------------------+-----------------+---------------------+-------------+--------+------------+
1 row in set (0.00 sec)
```

Screenshots:

Sender environment:
<img width="702" alt="screen shot 2017-10-27 at 2 20 42 pm" src="https://user-images.githubusercontent.com/1717110/32123593-2383a48e-bb22-11e7-95b1-351c00e27197.png">

Receiver Environment:
<img src="https://user-images.githubusercontent.com/1717110/32123601-275cfd44-bb22-11e7-8ed0-3e50e71e2e66.png">

## Context
Reported by Customer: https://dotcms.zendesk.com/agent/tickets/94600

## Your Environment

* dotCMS version used: 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any app server.
* Java Brand and version: 8u121.
* Database and version: Postgres, MySQL.
* Application module (if apply): N/A.

**Comment by shaydotcms** [comment]
Waiting for fix on #13018 to complete testing
