### ISSUE TITLE
Allow Containers on the Filesystem

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12943]
![2017-10-27_1430](https://user-images.githubusercontent.com/1486445/32119482-649a4364-bb23-11e7-9e2a-d3f6cd7ddc76.png)

We need to be able to completely define containers in .vtls without having to click and paste code in a UI.

- We will still support the current `#parseContainer({containerId}, {unique})` syntax

- We will add the ability to call a`#parseContainer({[host]/application/containers/mycontainer/container.vtl}, {unique})` 

- This means that a container for a structure should live under the `/application/containers/{CONTAINER_NAME}/{structureVar}.vtl`

- We will also need special containers 
`/application/containers/{CONTAINER_NAME}/preloop.vtl` 
and 
`/application/containers/{CONTAINER_NAME}/postloop.vtl` 

- We will need to update the `#parseContainer` code in order to handle these containers

- containers will need to be parse-abile across hosts, like `#dotParse` and the example on the board

- like themes, we will need to be able to search for them from the layout manager when adding a container to a row.

- Question: do we need a separate `/application/containers/{CONTAINER_NAME}/container.vtl` that defines the number of content objects allowed or can this info go into the preloop?
`#set($dotMaxContainerContents = 10)`

- I guess we support multi-lingual containers?  If the files have multi-lingual versions, why not?

**Comment by jdotcms** [comment]
The ContainerResource must retrieve the db containers and file containers

**Comment by jdotcms** [comment]
on the content search for a container, should filter only by the content type supported by the container

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15558
