### ISSUE TITLE
Password strength indicator needs styling

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12958]
As a stakeholder I want all the app components looks good and work correctly.

<img width="1372" alt="00001250" src="https://user-images.githubusercontent.com/751424/32226286-cc54fba6-be0d-11e7-900f-b61cdee1ce96.png">

## Expected Behavior
It needs to be a background so it doesn't confuse with the content of the page.

## Current Behavior
It's doesn't have a background and it looks broken.

## Possible Solution
Need to style the primeng password component

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Go to my account
3. Try to change the password

**Comment by bryanboza** [comment]
Fixed, now looks better... Tested in the last master
