### ISSUE TITLE
Host selector in form not getting the current site

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12955]
As a stakeholder I want the site-selector field to have selected by default the current site.

## Expected Behavior
In the content type form the site-selector default value should match the current site.

## Current Behavior
If you change the current site the change it's not reflecting in the field.

## Possible Solution
N/A

## Known Workarounds
N/A

**Comment by bryanboza** [comment]
Fixed, tested on the last master // H2 // Chrome 

**For QA purpose: Now when you try to add a new content type from the angular portlet, the site or folder field value should change automatically when you change the siteSelector... But if you select some site manually, the system should keep your value.**
