### ISSUE TITLE
Click all block to edit a field in the drop zone

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12957]
As a stakeholder I want to make easy to user to edit field

## Expected Behavior
Click in the "block" of a field should trigger the edit of the field (show the dialog)

## Current Behavior
Click on the "block" of a field does nothing, only clicking in the "edit" icon show the dialog.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to content-types-angular
2. Edit a content type
3. Click on the block of the field
4. Nothing happens

**Comment by bryanboza** [comment]
Fixed, now we are able to edit the field just clicking the field
