### ISSUE TITLE
Widen create/update field dialog box

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12956]
As a stakeholder I would like user have enough space to fill form and create fields in content types.

## Expected Behavior
Create/edit fields dialog form should be have more width.

## Current Behavior
Create/edit fields dialog form have just 300px of witdh.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to content types angular
2. Create or edit a content type
3. Create or edit a field
4. Check the width of the dialog bo

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
