### ISSUE TITLE
We are allowing add new persona content types from the angular portlet without license 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12962]
Since the personas is a enterprise feature, we need hide this option in the community version, and allow that just in case you have license , as work in the old portlet.

## Do this in the backend
Response of ```basetypes``` should not have Persona type.

## Expected Behavior
We should hide **personas, key value and vanity url** content types if you don't have license 

## Current Behavior
We are allowing add persona content types from the new angular content types portlet 

## Steps to Reproduce (for bugs)
1. Login . 
2. Add the new content types portlet 
3. Make sure you are in the community edition 
4. Try to add a new persona content type 

## Your Environment
Tested on master // postgres // FF 

## Acceptance Criteria

1. When click + in create content type the listing of the options should include what license allow.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
This needs to be enforced in the content type api / factory, not at the ui level.

**Comment by bryanboza** [comment]
The same behavior with forms

**Comment by fmontes** [comment]
1. Content types, personas and forms

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14754

**Comment by dsilvam** [comment]
After applying or removing ee license, you need to do CMD+R (refresh) in the browser to see the refreshed list of base types. Will be solved here: https://github.com/dotCMS/core/issues/14787
