### ISSUE TITLE
Page Preview Sidebar Doesn't Scroll

### ISSUE THREAD

**Issue by lucidmachine** [dotCMS/core#12967]
If your computer's screen is too small for the right-hand sidebar (iframe#frameMenu) to fit, you will be unable to scroll the sidebar. To replicate this, resize your browser to a smaller vertical size and then load a Preview screen. The controls on the right below the Workflow buttons will not be reachable if they fall below the bottom of the screen. This is especially an issue on smaller laptops, and in particular with the Persona and Mobile preview controls on the right.

## Expected Behavior
User should be able to scroll contents of sidebar in order to view and access controls in bottom of sidebar.

## Current Behavior
User is completely unable to view or interact with controls in the bottom of the sidebar.

## Possible Solution
s/scrolling="no"/scrolling="yes"/

## Known Workarounds
Utilize your web browser's developer tools or a custom CSS override to disable or remove the inline style 'scrolling="no"', or set 'scrolling="yes"', on the element iframe#frameMenu.

## Steps to Reproduce
1. Log in to the app's portal. (/dotAdmin)
2. Open the Browser portlet (Site > Browser).
3. Open any page for editing. For example, open "//demo.dotcms.com/index".
3. Resize your browser's window so that it has <= 500px vertically.

## Context
Users whose devices have particularly small screens, who use screen magnifiers, who change their browsers' zoom levels, who resize browser windows, or who have browser developer tools open may be unable to see or access core features in the sidebar (iframe#frameMenu) including Language, Viewing As, or Personas.

## Your Environment
* dotCMS version used: 4.1.1

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres // chrome
