### ISSUE TITLE
Allow a single workflow action to be available for locked and/or unlocked content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12960]
We need a workflow action to be able to be shown on content that is locked, on unlocked or in both cases.

![screen shot 2017-10-31 at 12 21 53 pm](https://user-images.githubusercontent.com/934364/32235698-935f1ae2-be36-11e7-9c5e-5c7575ce81b0.png)

**Comment by jdotcms** [comment]
default must both

**Comment by jdotcms** [comment]
as part of this task we are only going to include a new field called "show_on", a dropdown on the add/edit workflow action with the choices "locked, unlocked, both" and the corresponding migration of the information (based on the boolean value of the require_lock, the show_on will have LOCK or UNLOCK, keep in mind the show_on will be a comma separated list on the db, which the values are the names of an enum that will encapsulate all show on status')

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13286

**Comment by bryanboza** [comment]
We have problems here because when you lock for editing the content, we are not refreshing the list of actions in the window, now this works if you test with different users, but if you try that with the same user, we are not refreshing this list and we still showing the same actions 
Here the video: https://screencast.com/t/Kyr0tZws9

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/13320

**Comment by bryanboza** [comment]
Fixed, now it works, but we still depending of this issue #13287 , we need test again after remove this functionality.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now this works as expected
