### ISSUE TITLE
Unable to scroll in the field list on the new angular content types portlet on iPad

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12969]
We have problems to see the complete list of the fields on the new angular content types portlet and we are unable to scroll in that list 

## Expected Behavior
We need be able to scroll and see all the field list without problems 

## Current Behavior
We are unable to scroll and we can't see the last fields in the list 
![img_0061](https://user-images.githubusercontent.com/2641437/32295818-01a6aeaa-bf10-11e7-9c43-c117bbbe4f09.jpg)

## Steps to Reproduce (for bugs)
1. Login 
2. Go to the new content types on angular 
3. Add a new content type 
4. Try to add a new text field 

## Your Environment
Tested on the last master // iPad Air2

**Comment by wezell** [comment]
ipad low priority
