### ISSUE TITLE
Incompatibility between content types portlets

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12964]
As part of the new changes, now we have two content types portlets. But we are having Incompatibility problems between those ones

## Expected Behavior
We should be able to see any content type from the new angular content types portlet  

## Current Behavior
We are having multiple problems here: 

- [ ] If you create a new content type in the old portlet, the system is unable to open//edit from the new one. This because don't have line and tab dividers to order

- [ ] If you create a new content type from the angular portlet, and then try to add a new content, we have problems to see the fields, this because we are showing the fields in multiple tabs, also we are unable to rename this tabs 
SC: https://www.screencast.com/t/XxjQRJjEAdHu

- [ ] We are unable to rename the tab dividers... This because this are added automatically and the name is auto generated by the system 

**FYI: Also we need take in consideration the content types of the clients databases, if we deprecate the old content types portlet, we are unable to edit the existing ones...**

## Steps to Reproduce (for bugs)
1. Login as admin
2. Add the new angular content types portlet 
3. Create a new content type 
4. Add a new layout with 4 columns 
5. Add a new filed to every column 
6. Try to add a new piece of content 

## Your Environment
Tested on the last master // postgres // FF

**Comment by wezell** [comment]
Please retest.  This is a blocker if it is still true.

**Comment by jgambarios** [comment]
**Note to QA:** @bryanboza please help us to validate if this is still an issue.

**Comment by bryanboza** [comment]
Tested and now I'm unable to reproduce those cases, the only inconsistency is in the new portlet because we don't have tab and line dividers fields... Not sure if is expected but this is functionality that we are removing to the system @

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14859

**Comment by fmontes** [comment]
We bring back tab and line dividers fields, you can add and edit them now in any content type.

**Comment by wezell** [comment]
@bryanboza is this different behavior than 4.x?

**Comment by bryanboza** [comment]
Yes @wezell , this works in the old portlet but not in the new one.
Here the difference: https://www.screencast.com/t/AaNziSSmZ0

**Comment by bryanboza** [comment]
Fixed, now we are able to add/edit/delete those fields from the new portlet
