### ISSUE TITLE
Make shorties faster

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12972]
If we are matching an exact uuid (36 chars) against the database, we should not do a `like uuid%` with a wildcard.  This causes a seq_scan rather than using the index and is much slower.

See: 
https://gist.github.com/jtesser/5b5288afbe66ef59ce4876fed84500f6

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12974

**Comment by bryanboza** [comment]
Hey @wezell, can you help me to see what I should test here?

**Comment by wezell** [comment]
We just need to make sure that shorties still work.

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and works as expected.
