### ISSUE TITLE
Task04225 is missing after upgrade on MySQL and MSSQL

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#12971]
Task04225UpdateSystemFolderIdentifier is missing when an upgrade is performed. Task is present in different DBs with starter data.

Upgrade was done on:  
MySQL from dotcms_2.5.7 to dotcms_4.3.0 
and 
MSSQL server from dotcms_3.3 to dotcms_4.3.0

## Expected Behavior
Task04225UpdateSystemFolderIdentifier should be present after upgrade.

## Current Behavior
Task04225UpdateSystemFolderIdentifier is currently missing when an upgrade is done.

## Steps to Reproduce (for bugs)
1. Perform an upgrade (assets and DB) using clients' data (in this case, you can upgrade using MySQL from dotcms_2.5.7 to dotcms_4.3.0)
2. Go to the DB and run Select * From db_version
3. You will see that Task04225UpdateSystemFolderIdentifier is not listed
[MySQL_tasks_upgrade_2.5_4.3.zip](https://github.com/dotCMS/core/files/1435772/MySQL_tasks_upgrade_2.5_4.3.zip)
4. Repeat steps above with a different client data set (MSSQL/upgrade from dotcms_3.3 to dotcms_4.3.0)
5. You will see that Task04225UpdateSystemFolderIdentifier is not listed
[MSSQL_tasks_upgrade_3.3_4.3.zip](https://github.com/dotCMS/core/files/1435774/MSSQL_tasks_upgrade_3.3_4.3.zip)

## Your Environment
* dotCMS version used: upgrade from client dataset MySQL dotcms 2.5.7 to dotcms 4.3 master and MSSQL dotcms 3.3 to dotcms 4.3 master
* Operating System and version: Mac OS 10.10.5 / Win7 Pro SP1
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by acurionedotcms** [comment]
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/554

**Comment by shaydotcms** [comment]
Passed QA.

Upgrade successfully performed from dotcms_3.6 with client dataset to master branch using MySQL and MSSQL
