### ISSUE TITLE
Login As link should only appear to users with a role that provides that functionality.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#12973]
The Login As link in the admin console displays for all users, which can cause confusion and when users without the Login As role attempt to login as another user it can sometimes result in an error message of [object Object] rather than "You have not been assigned the role Login As".  This link should only display for users who have that role assigned.

* dotCMS version used: 4.1.1, 4.2.0

**Comment by wezell** [comment]
Not a priority
