### ISSUE TITLE
NPE creating push environment 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12977]
We have a NPE error trying to create a new push publishing environment, this because we are having error when you try to create the receiver node 

## Expected Behavior
We should be able to add the sender and receiver node without problems 

## Current Behavior
We have a NPE error and we are unable to create the receiver node 

Log: https://gist.github.com/bryanboza/7335deb5ec4c3168a58ba144b7762e74

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Apply the license 
3. Try to add a receiver node in the push environments configuration 

## Your Environment
Tested in the last master // postgres // FF

**Comment by oarrietadotcms** [comment]
@acurionedotcms is working on this one right now. @dsilvam is this a duplicate?

**Comment by dsilvam** [comment]
yeah this is let me link it

**Comment by dsilvam** [comment]
Fixed in this https://github.com/dotCMS/core/pull/12976

**Comment by bryanboza** [comment]
Fixed, tested with the last changes on master // H2 // FF
