### ISSUE TITLE
New content types portlet need be compatible with the iPad resolution 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12970]
We have some errors in the UI when you try to open this portlet from an iPad 

## Expected Behavior
We should support the navigation in the iPad resolution 

![img_0062](https://user-images.githubusercontent.com/2641437/32296672-79226170-bf12-11e7-8b56-3dce9bfee8f8.jpg)
![img_0064](https://user-images.githubusercontent.com/2641437/32296673-793b0c2a-bf12-11e7-9321-96e804a48d62.jpg)

## Your Environment
Tested on master // iPad Air2

**Comment by wezell** [comment]
ipad = low priority.  Please test ie11 instead.
