### ISSUE TITLE
Hide delete button in undeleteable content types (like Content Generic)

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12983]
As a stakeholder I don't want user have the option to delete content types that can't be deleted.

### Possible solution
If the content type have ```defaultType: true``` or ```fixed: true``` it can't be removed.

### Acceptance Criteria

1. Remove the delete action button from all the content types rows that can't be deleted
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Seems we are including Content (Generic) here and we are able to delete this content type from the old UI
As you can see in the follow SC: 
https://screencast.com/t/l7gHhHBo3dQ
https://screencast.com/t/oPpQtWWspHrH

**Comment by fmontes** [comment]
The condition should be only: ```fixed: true```

**Comment by bryanboza** [comment]
Now we have the delete button, bu as is expected if you try that we should show an error message by the dependencies, right now if you try from the new portlet, we just have the error on logs, but we are not showing nothing at UI level 
Here the log error: https://gist.github.com/bryanboza/450af80797cc16cdb7b8b8d3b65ff333

**Comment by bryanboza** [comment]
Not sure why we close this card if we still having the problem. Here the log when you try to delete the Content (generic): https://gist.github.com/bryanboza/413e4dd7e2fcc784dc67ac9dc87f011b

**Comment by fmontes** [comment]
@bryanboza as per @wezell (a few months ago) we're not building the popup like the old portlet, the fix we did was NOT allow the content type to be removed.

**Comment by bryanboza** [comment]
Ok, guys like in the previous version Generic Content is a content type that you can delete, but we can't do this by a dependency of their contents.  And this is what we show in the pop up when you try to delete it. After this fix, we just hide the delete button on this content type.

**Comment by freddyucv** [comment]
we hide the delete button because Generic Content is the defaultType, if you try to delete a content type with content then the content are deleted too, but for now it not show the confirmation dialog.

If we want to show the dialog again, I think it should be another issue

**Comment by bryanboza** [comment]
Seems that is good for now. Passed
