### ISSUE TITLE
Make preview resolutions configurable

### ISSUE THREAD

**Issue by ekelvin** [dotCMS/core#12988]
## Expected Behavior
Make preview resolutions configurable so that can you can add the target resolutions of the project

## Current Behavior

The list of resolutions is fixed you can't modify it.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by wezell** [comment]
I believe they are - it is just a content type within the system.  You can add, deleted or edit them.

![screen shot 2017-11-04 at 9 52 29 am](https://user-images.githubusercontent.com/934364/32405972-e5ba87ba-c145-11e7-9f7b-46d3517bc538.png)
