### ISSUE TITLE
Cannot Delete Content types in current master.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12999]
As a follow up for https://github.com/dotCMS/core/issues/12716, additional tests made:

- Created a Test Content 001 Content Type, with only a Title Field.
- Under Large-1 Container on demo site, add this content type and print $!{title} value.
- Create a page using Quest - 1 Column.
- On Edit Mode, add a Test Content 001 content under the main container of this page. You should see printed the Content Title on this page.
- Attempt to delete the content type, which calls the destroy() method on ContentletAPI and then destroyContentlets() (the one that fails in regression tests). This shows on backend view:

<img width="1488" alt="screen shot 2017-11-07 at 8 47 30 am" src="https://user-images.githubusercontent.com/1717110/32499808-36174fb8-c399-11e7-8cc5-9500c29e20c0.png">

- Go ahead and remove the Test Content 001 content from Large-1 container.
- Open again the page in Edit Mode. Content is still there, despite the container should not print contents from this content type. Nothing is printed from this content, though.

<img width="1487" alt="screen shot 2017-11-07 at 8 55 33 am" src="https://user-images.githubusercontent.com/1717110/32499882-6ff1051c-c399-11e7-90c6-fbbb69647526.png">

this is the current definition of container. See that Test Content 001 content type is not part of the code definition anymore:

<img width="1462" alt="screen shot 2017-11-07 at 9 01 04 am" src="https://user-images.githubusercontent.com/1717110/32500207-48a0a1c4-c39a-11e7-88cd-25ebebe324f4.png">

- Try again to delete the content type. Same error as above 

---

If we try to delete a content type like Call to Action, or the same content type above without following the steps for adding contents to pages/containers, we get this error

```
An unexpected system error occurred. 
com.dotmarketing.exception.DotDataException: An error occurred when  saving a system event with ID: [null]: Cannot find type adapter for  class 
com.dotcms.contenttype.model.type.ImmutableSimpleContentType

```

Stacktrace: https://gist.github.com/joseorsini/17f2fc375da89f52a503e9a4461817af

**Comment by joseorsini** [comment]
It makes sense that a content type deletion complains about an old container-contenttype relationship, however, it exists on an old version of the container itself (these relationships are versionable). Still, current live/working version of container does not reference this content type, so we should be able to delete the content type instead of going to each old version of the container and inspect which one refers to this content type.

Additionally, multi-tree relationships are not versionable, so if a current version of a container drops support for a content type, we shouldn't keep those records on this tree IMHO.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13242

**Comment by jgambarios** [comment]
By Wills request we reverted https://github.com/dotCMS/core/pull/13242 with this pull request https://github.com/dotCMS/core/pull/13255
After the changes on this pull request https://github.com/dotCMS/core/pull/13193 are merge it we need to reapply the changes made on https://github.com/dotCMS/core/pull/13242

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we are able to delete content types without problems

**Comment by DeanGonzalez** [comment]
Passed, had trouble dropping fields on a new content type, but will report that on separate issue.
