### ISSUE TITLE
[Licensing] Customers using Prime Licenses on Oracle installs cannot see pages

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13007]
This commit which introduces improvements for Licensing across different places in our codebase

https://github.com/dotCMS/core/commit/28e07ba10133137bdfd2c8320fec7a232999db0d#diff-921461c352ce37381ddb902efdb4f781

Made the VelocityServlet to consistently forward all page requests to the /portal/no_license.jsp file, even for those who have applied a valid license to the server. 

For specific scenario of customers with Prime Licenses and Oracle DBs, this code 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/velocity/VelocityServlet.java#L176 

is always true, despite Prime is the right license level.

**Comment by wezell** [comment]
That commit is an aggregate commit. The commit we should put eyes on is this one:

https://github.com/dotCMS/core/commit/daab6aea03143642c39bbbba154cf7bd0c510231 
and this one:
https://github.com/dotCMS/enterprise-2.x/commit/6e6dca71392e91a9c12e6ad5a220c1235e5cfb8b

**Comment by joseorsini** [comment]
@wezell agreed. However, I haven't seen anything on other commits that would require an update. The only place there License Validation is actually broken is on VelocityServlet.

PR: https://github.com/dotCMS/core/pull/13008

**Comment by dsilvam** [comment]
PR master: https://github.com/dotCMS/core/pull/13008

**Comment by bryanboza** [comment]
Fixed, tested on release-4.2.1 // Oracle 12c
