### ISSUE TITLE
Update hamburger button

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13003]
As a user I want to know when the navigation is expanded and collapsed.

## Expected Behavior
When menu (sidebar) is expanded the icon should be left arrow and collapsed hamburger icon.

## Current Behavior
Menu expanded/collapsed icon is hamburger icon.

### Acceptance Criteria
1. When navigation is expanded the icon should be left arrow and collapsed hamburger icon.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in the last master // Postgres // Chrome
