### ISSUE TITLE
[Vanity Urls] Lookup of migrated Vanity URLs is still case sensitive

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13017]
During the upgrade between 3.x and 4.x releases, there are a few Upgrade tasks that deal with Vanity URLs:

- Make them all lowercase: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04105LowercaseVanityUrls.java
- Create new Vanity URL Content Type: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04200CreateDefaultVanityURL.java
- Migrate Vanity URLs to contents: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04205MigrateVanityURLToContent.java

Despite migration goes well and all Vanity URLs are stored as lowercase objects, lookup at API level is still case sensitive.

## Workaround: 

Set the proper case for cases like /cms404Page so the Vanity URL works and redirects to custom error page goes without any issues.

## Steps to Reproduce (for bugs)

1. Upgrade a dotCMS instance from 3.x to 4.2.0.
2. Make sure the Vanity URL pointing to a custom Error 404 page is created. After the upgrade, it should be labeled as `/cms404page`.
3. Hit any page that doesn't exist, like '/test-index/index'
4. System does not redirect to custom 404 page. It falls back to the 404 page specified on web.xml (https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/error/custom-error-page.jsp)

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94682 
Tested on upgrades from 3.3.1 to 4.2.0 using Postgres, Oracle and MSSQL databases.

## Your Environment

* dotCMS version used: 4.2.0.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Tomcat 8.0.18, Tomcat 8.0.36.
* Java Brand and version: Java 8u121
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by bryanboza** [comment]
Fixed, tested on 4.2.1 and now it is working as expected
