### ISSUE TITLE
Unable to upload license pack

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13018]
System is not uploading license from license pack. This is happening with starter data and client dataset
https://gist.github.com/shaydotcms/17818d68f7bd4eb0911b7c864c227bf9

## Expected Behavior
System should allow to upload license from license pack.

## Current Behavior
Systems throws an error when uploading the license. UI says license was successfully uploaded.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to System> Configuration. Click Licensing tab
3. Click Upload button and browse for the a license pack
4. Click Upload button
5. You will see the error in the logs: https://gist.github.com/shaydotcms/17818d68f7bd4eb0911b7c864c227bf9
6. UI will say "Your Licenses have been uploaded" but this is not true.
![image](https://user-images.githubusercontent.com/8741846/32571652-cbfa8dde-c48d-11e7-9e37-2fcc42e6f8e8.png)

## Your Environment
* dotCMS version used: master branch / commit a3ac2710e2109ecc27206f68044454d97061f803
* Database and version: Postgres 9.3.5 / SQLServer 2012
* Operating System and version: Mac OS 10.10.5 / Win7 Pro SP1
* Browser Name and version: Firefox v45.0.1 & Chrome v54.0.2840.98
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/555

**Comment by shaydotcms** [comment]
Passed QA.
I was able to successfully apply the license
