### ISSUE TITLE
Binary fields info window needs styling help

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13016]
We are having problems to see the complete path of the binary fields on this window 
<img width="1438" alt="file" src="https://user-images.githubusercontent.com/2641437/32519961-013604f2-c3d4-11e7-854b-cf264bae2ffc.png">

We need a UI improvement here via JSP 
## Your Environment
Tested on master // Chrome

**Comment by wezell** [comment]
will address later.
