### ISSUE TITLE
/edit does not deliver the logged in user to the last page browsed on front end

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13026]
Tested on latest 4.2

Easy to reproduce, visit a page on the front end of demo site like this one:

https://demo.dotcms.com/about-us/our-team/

Then add the /edit at the end of the domain and log in.

Expected behavior is that it should deliver you to the "our team" page in edit mode, but instead, it is acting like a /admin login and brings the user to the workflow tasks screen.

**Comment by bryanboza** [comment]
After update the last code in release-4.2.3, we still having problems in with the redirect, we always redirect to the edit of the index page

**Comment by wezell** [comment]
@fmontes  Work off 4.2.2 so we can deliver a hotfix

**Comment by bryanboza** [comment]
Still having problems here, sometimes we don't redirect to the correct page, also when redirect we are unable to edit the page.
SC: https://www.screencast.com/t/Y0FPUX9u

**Comment by bryanboza** [comment]
Also tested on 4.3.0 and neither works SC: https://screencast.com/t/BvaxXrorU

**Comment by bryanboza** [comment]
Tested on rease-4.3.0 // postgres // chrome. Now this is working as expected

**Comment by bryanboza** [comment]
Note to doc: We have an special case here, if you turn off this the ENABLE_CLICKSTREAM_TRACKING property this feature isn't working. Maybe we need doc this case

**Comment by fmontes** [comment]
@bryanboza please test this in master.

**Comment by bryanboza** [comment]
Fixed, we have the same behavior, this works but depends of the property ENABLE_CLICKSTREAM_TRACKING
