### ISSUE TITLE
Non-CMS Anonymous pages are not requiring login, they just 500

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13025]
Tested on latest dotCMS 4.2 instance

I think we accidentally changed this property to "false" when it should be set to true by default:

**allow.legacy.com.dotmarketing.cms.login.action.loginaction=true**

I asked Will and he said, the default value should be **true**.

When set to false, any intranet page causes a 500 error instead of going to the login page with referrer.

For instance, this page on demo is not causing a 500 error:

https://demo.dotcms.com/intranet/

Expected behavior is that hitting that page should automatically lead you here, since the page has no CMS Anonymous permissions:

https://demo.dotcms.com/application/login/login.html?referrer=/intranet/&native=true

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgres // FF , also tested on release 4.2.1
