### ISSUE TITLE
Site Search indexes Sites other than selected.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#13038]
Currently a production issue for a client, https://dotcms.zendesk.com/agent/tickets/94695, replicated on demo3

## Expected Behavior
Site Search selected to run on a specific Site/Folder only indexes content for that Site/Folder

## Current Behavior/Steps to Reproduce
1 - Create new blank site
2 - Create new Site Search index
3 - Run new Site Search index against that Site
4 - Results include all matching content from default site as well

## Your Environment
* dotCMS version used: 3.7.1

**Comment by wezell** [comment]
@mattyarbrough , exactly what content did you see on the wrong host?  Are you sure  it was not System Host content?

**Comment by mattyarbrough** [comment]
It was content from the System Host.

**Comment by mattyarbrough** [comment]
Dean explained this to me, this is not a bug.
