### ISSUE TITLE
We are not respecting the DEFAULT_VANITY_URL_TO_DEFAULT_LANGUAGE property after change the session language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13039]
We are unable to apply the fallback after change change the session language, we have a 404 error and we are unable to resolve the vanity URL.

## Expected Behavior
After you change the session language, the system should resolve the vanities normally with the new language and if does not exist respect the **DEFAULT_VANITY_URL_TO_DEFAULT_LANGUAGE** property

## Current Behavior
After you change the language, the system is unable to resolve if the vanity don't have version in the new language 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new page with versions in English and Spanish 
3. Create a new Spanish version of the 404 Error page 
4. Create a 3 new vanities (all those ones redirect to the page you has been created)
- The first (test1) with versions in English and Spanish
- The second one (test2) just in English
- The last one (test3) just in Spanish
 5. From incognito mode hit every one of those ones

**FYI**: 
- By default is all is ok 
- After you change the session language (hit http://localhost:8080/index?language_id=2), we are unable to resolve vanities if ONLY have english version then we are not respecting the DEFAULT_VANITY_URL_TO_DEFAULT_LANGUAGE which is in true by default 

## Your Environment
Tested on release-4.2.1 // postgres // Chrome

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13040 (master)
https://github.com/dotCMS/core/pull/13043 (4.2.1)

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now works as expected
