### ISSUE TITLE
Migrated virtual links live on system host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13055]
We are storing the virtual link host in two places - the identifier.host and the "site" field on the content type.

We are going to fix this sooner rather than later.
- [x] Create an upgrade task that runs after the one we have that changes the host on the identifier to the value of the site field
- [ ] Remove the site field from the basecontenttype vanityurl - it is redundant.
- [ ] Add a host/folder field to the basecontenttype vanityurl
- [ ] Use the identifier.host field to do the lookups 
- [ ] Make sure we migrate the data stored in the vanityurl contentlet to the identifier  host

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13056 (master)
https://github.com/dotCMS/core/pull/13057 (4.2.2)

**Comment by jgambarios** [comment]
Upgrade task:
https://github.com/dotCMS/core/pull/13060 (master)
https://github.com/dotCMS/core/pull/13061 (4.2.2)
