### ISSUE TITLE
Error running a fresh installation in Oracle

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13066]
This error is thrown during a fresh installation using Oracle 12c: https://gist.github.com/nollymar/97025c70ef23eaa2352cbb17219d3dc9

## Your Environment

* dotCMS version used: master
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 8
* Database and version: Oracle 12c

**Comment by acurionedotcms** [comment]
Enterprise PR: https://github.com/dotCMS/enterprise-2.x/pull/559
