### ISSUE TITLE
Page does not disappear from Site Search if delete folder

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#13065]
## Expected Behavior
If you delete a folder with a published page, that page should disappear from Site Search.

## Current Behavior
If you delete a folder with a published page, that page still appears from Site Search.

## Known Workarounds
Create a new Site Search Job.

## Steps to Reproduce (for bugs)
1. Create a content (e.g Content-Type: Content Generic, Title: Erick, Body: Erick)
2. Create a page (e.g under blogs) and relate the content created above
3. Create a folder(e.g under contact us), under that folder a page, and also relate the content to that page.
4. Create a Site Search Index (e.g SS)
5. Create a Site Search Job with the following settings:
![image](https://user-images.githubusercontent.com/5278970/32844924-2a2254e0-c9e9-11e7-85da-01bbca7c1acc.png)
6. Wait to the Site Search Job runs
7. Go to Search Tab (on the Site Search Portlet) and search for the title of the content created (in this case Erick), you should get 2 results.
![image](https://user-images.githubusercontent.com/5278970/32844983-47407264-c9e9-11e7-8af4-a539ce9a1eb3.png)
8. Go to Site > Browser and delete the folder without unpublish the page.
9. Wait until the Site Search Job runs again (with the config provided it runs every 5 min)
10. Do the same search for step 7, you should get 1 result but you still get 2.

## Your Environment
* dotCMS version used: demo and master
* Browser Name and version: FF
* Operating System and version: MacOs
* Database and version: Postgres
* Application module (if apply): Site Search

**Comment by erickgonzalez** [comment]
Client's issue: https://dotcms.zendesk.com/agent/tickets/94690

**Comment by wezell** [comment]
this works the same as PP - you delete a folder locally, you lose the ability to push delete that folder. we do not store deletes anywhere to be able to replay them into a site search or a remote server.  The workaround is to use uncheck incremental and do a full reindex.

**Comment by john-thomas-dotcms** [comment]
So yeah, the issue here is that the site search job is incremental.  Incremental site searches do _not_ remove anything from the index - they just add new items and update any changed items.

**Comment by john-thomas-dotcms** [comment]
Hmmm...actually the doc already states this.  I do need to reformat the doc a little, but you can point the customer to the doc (https://dotcms.com/docs/latest/site-search under the "Include changes from" heading about mid-way down the page)

**Comment by bdestefanis** [comment]
In my tests the issue occurred whether the job was Incremental or not. I had to delete the index, recreate it, and re-index to remove the pages. There is no way to automate deleting the index and re-creating it so our nightly re-indexes are not removing these deleted pages.

**Comment by brentgriffin** [comment]
Based on recent interaction about this issue also being a problem with the non-incremental indexing, and interaction with Will - reopening
