### ISSUE TITLE
Integrity Checker problems after fix conflicts on MSSQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13074]
We have problems using the integrity checker when you are using MSSQL as database, this because after you run the integrity checker (IC), detect conflict and fix or discard, and then try to run again.  We have an error because the table temporal table already exist.

## Expected Behavior
Since is a temporal table, this should be deleted after fix//discard conflicts 

## Current Behavior
We are leaving this table and we are unable to run again the IC
Log: https://gist.github.com/bryanboza/f73dafb99e27c05354b0725b0f5aade4 

## Steps to Reproduce (for bugs)
1. Configure the push env
2. Create some conflict 
3. Run the IC
4. Fix the conflicts
5. Run again

## Your Environment
Tested on master // MSSQL 2014

**Comment by wezell** [comment]
Have not seen again.
