### ISSUE TITLE
Language Variables Search under WYSIWYG Should search New LV Content for match

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13077]
Under our WYSIWYG, we have a Language Variable Search feature to include the variable in the WYSYWYG.  We are still searching the old text file version... we should give this guy a little upgrade since he is using the deprecated terms.

![languagevariables](https://user-images.githubusercontent.com/1569167/32927229-0e0eea60-cb11-11e7-84b3-aa29a4b593d8.png)

**Comment by jgambarios** [comment]
@DeanGonzalez is not looking for the Language Variables as content at all?

**Comment by john-thomas-dotcms** [comment]
Note that this also applies to Textarea fields

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14726

**Comment by dsilvam** [comment]
needs work: div not scrollable and not able to see the results: 
https://www.screencast.com/t/A63hfnegc
