### ISSUE TITLE
NavTool does not filter contents by language.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13087]
As of 4.2.x, we do allow NavTool calls and, by passing in a Language Id to the call, we should only get showOnMenu items for the specified path, and with the same Language Id we passed in. 

However, this attribute is not being respected and we're getting contents from all languages under the folder we passed in to this Viewtool

## Expected Behavior
Whether we pass in the language or not, we should respect the language in session and pull objects that match this language.

## Current Behavior
All contents under a folder are passed in.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Create a folder. For this test, let's call it `multipass`.
2. Create a multilingual page call navtool-test under this folder (in English and Spanish.
3. Add two different files to `/multipass/` folder. One of them is in English, the other one is in Spanish.

File in English.
<img width="1675" alt="screen shot 2017-11-20 at 11 17 52 am" src="https://user-images.githubusercontent.com/1717110/33031883-2540ca88-cde5-11e7-861d-a7c93a6d98d5.png">

File in  Spanish .
<img width="1660" alt="screen shot 2017-11-20 at 11 17 40 am" src="https://user-images.githubusercontent.com/1717110/33031884-2557e1fa-cde5-11e7-9722-2dd6a41a860b.png">

Contents of /multipass folder
<img width="1666" alt="screen shot 2017-11-20 at 11 16 17 am" src="https://user-images.githubusercontent.com/1717110/33031850-1259a39a-cde5-11e7-88c9-fc1a93d7e75b.png">

3. Under /multipass folder, add a Multilingual Simple widget with this NavTool call: 

```
#set($selectedLanguage = $request.getParameter("com.dotmarketing.htmlpage.language"))
#set($lang = $UtilMethods.parseLong($selectedLanguage,1))
<h2>Menu</h2>
<div>Language is: $lang and class is $lang.class</div>
#set($firstLevelItems = $navtool.getNav("/multipass", $lang))
<ul>
#foreach ($firstLevelItem in $firstLevelItems)
<li>
#if ($UtilMethods.isSet($firstLevelItem.codeLink))
$!{firstLevelItem.codeLink}
#else
<a #if($firstLevelItem.active)class="active"#end href="$!{firstLevelItem.href}" title="$!{firstLevelItem.title}"#if($firstLevelItem.target) target="$!{firstLevelItem.target}"#end>
<span>$!{firstLevelItem.title}</span>
</a>
#end
</li>
#end
</ul>
```

4. Show the page in Edit Mode

<img width="1674" alt="screen shot 2017-11-20 at 11 17 01 am" src="https://user-images.githubusercontent.com/1717110/33032069-cacb261a-cde5-11e7-9165-30b48355d32f.png">

Same behavior is displayed if we switch the page version to Spanish:

<img width="1663" alt="screen shot 2017-11-20 at 11 17 22 am" src="https://user-images.githubusercontent.com/1717110/33032093-d5772f64-cde5-11e7-8e0d-be9b1773b70e.png">

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94763

## Your Environment

* dotCMS version used: 4.2.x.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any app server.
* Java Brand and version: Any supported Java 8 JDK
* Database and version: Any DB.
* Application module (if apply): N/A.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by bryanboza** [comment]
Tested again and this isn't filtering by different languages in the last master code, we need a rework on this one. 

Also, we have the same case in the NavResource. https://github.com/dotCMS/core/issues/14449

**Comment by erickgonzalez** [comment]
Since we have the property **DEFAULT_PAGE_TO_DEFAULT_LANGUAGE** default to `true`, we show all the items regardless the language, to avoid this you can change the property (but this will affect other parts of the system) or you can filter the navresult via velocity (calling the LanguageId, e.g $!{firstLevelItem.LanguageId})

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14558

**Comment by bryanboza** [comment]
Ok, after discussing with @erickgonzalez and @dsilvam we have problems in the validation here because if you have the property is true, the navtool always is including all the files. 

We need some work here.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14567
