### ISSUE TITLE
Multiple issues with Templates

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13097]
Currently, we do not allow the following tasks related to Templates:

- Full Delete. We cannot delete templates from system. Nothing is logged in the dotcms.log file, and Template remains as an archived asset. It seems like the action in the UI doesn't trigger the struts action for a full delete, as detailed on the EditTemplateAction class.
- Even if we're able to delete Templates, we should prevent this from happening in case the Template is being used by Pages (in the same way we do it for Content Types being used on Containers).
- Make sure that both delete processes (from Delete Button at the bottom of the list, and via right-click) behave the same, meaning that they should display the same dialog and the list of htmlpages that use the template (if any) 

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94771

## Your Environment

* dotCMS version used: 4.2.2.
* Browser Name and version: any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: Any supported Java 8 version.
* Database and version: any DB.
* Application module (if apply): N/A.

**Comment by dsilvam** [comment]
Note to QA: Try to delete a template that is used by a lot of htmlpages (should not let delete it) and see if the Dialog with the list of dependencies makes sense and displays good, and the message is clear to the user.

**Comment by shaydotcms** [comment]
Passed QA.

Verified that:
Templates with no page/container dependencies can be deleted
Templates with page dependencies cannot be deleted 
Update on template name is reflected on its dependencies (i.e.: pages)
Template is deleted thru UI by right click
![image](https://user-images.githubusercontent.com/8741846/33507193-fc9f5c84-d6b8-11e7-9007-038f9fcf4c28.png)

Template is deleted thru UI by clicking the 3 ellipsis
![image](https://user-images.githubusercontent.com/8741846/33507199-08cd261c-d6b9-11e7-8646-6aeebcbcf7b0.png)

Template is deleted in DB
Confirmation message is consistent with the different ways the system has to delete it

Tested with upgrade from dotcms_3.x with client dataset to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by dsilvam** [comment]
Page title is not enough info. We need to show: host + path

**Comment by shaydotcms** [comment]
Passed QA. Now popup is showing host + path

![image](https://user-images.githubusercontent.com/8741846/34837292-f75b2c22-f6bf-11e7-88c8-db27db509928.png)

Tested with upgrade from dotcms_3.x with client dataset to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
