### ISSUE TITLE
Add a delay to network cache flushing to avoid race conditions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13100]
In a clustered environment, nodes can get out of sync and one server shows the correct content while the other shows a 404.  This might be happening when :

1. Server A is in a DB transaction editing content
2. Server B is getting load on read of page or file
3. Server A still within the DB transaction clears the cache
5. Server B sees an empty cache BUT Transaction from A is not yet commited
6. So Server B pulls old object from DB BUT doesn’t add to cache yet
7. Server A commits. and commit cache invalidation happens after the commit
8. Server B receives cache inval and removes THEN the inserts from the DB which is stale is put into cache

**Comment by bryanboza** [comment]
Fixed
