### ISSUE TITLE
Conditions for current URL in Rules Engine should support urlmapped Content URLs

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13109]
Tested on dotcms 4.2.2

Our "current URL" condition is currently not supporting URL Mapped page URL's.  If I set up a condition on a personalization rule to:

Condition: Current URL - "Contains" - "how-wall-street-may-threaten-your-pension"
Action: Set Persona = Wealthy Prospect
and then I hit this page: https://demo.dotcms.com/news/how-wall-street-may-threaten-your-pension
...no action is triggered.  However, if I set the condition to "contains" - "products"
and then I hit this page: https://demo.dotcms.com/products/
Then the action is triggered and the persona is set.

https://screencast.com/t/AadW9Cyd

We should support URL mapped requests when examining if a URL request contains a text string.

**Comment by wezell** [comment]
Most probably, the conditionlet should check against the request.getAttribute("javax.servlet.forward.request_uri") and not request.getRequestURI or whatever
