### ISSUE TITLE
Bad asset / host information preventing from bundling content

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#13115]
Client getting NullPointerException when trying to BUNDLE content - it does even get to the push stage.  Here is log message:  https://gist.github.com/brentgriffin/3764101454bf76b0140323f7a7ab20a7

Can get relevant details and data here:  https://dotcms.zendesk.com/agent/tickets/94811

## Known Workarounds

Manually flush the cache - this allows the bundling to complete successfully.

## Your Environment

* dotCMS version used: 4.2.1
* Browser Name and version: N/A
* Operating System and version:  CentOS (our standard cloud deployment)
* Application Server and version: embedded tomcat
* Java Brand and version: 
* Database and version:  postgres
* Application module (if apply):

**Comment by brentgriffin** [comment]
So far, I have not been able to reproduce.

The log file shows a NullPointerException here:  https://github.com/dotCMS/enterprise-2.x/blob/4.2.0/src/main/java/com/dotcms/enterprise/publishing/remote/bundler/HostBundler.java#L299 which seems to indicate that "APILocator.getHostAPI().find" is returning null:  https://github.com/dotCMS/enterprise-2.x/blob/4.2.0/src/main/java/com/dotcms/enterprise/publishing/remote/bundler/HostBundler.java#L246

**Comment by oarrietadotcms** [comment]
PR for ee: https://github.com/dotCMS/enterprise-2.x/pull/564

I tried to work Java 8 Optional in Host API find but it has 265 usages.

**Comment by shaydotcms** [comment]
Passed QA.
Tested with Upgrade from dotcms_3.6 to master branch
Ubuntu 14.04.1 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by shaydotcms** [comment]
Passed QA.
I was able to successfully push content inside/outside a bundle
Tested on release-4.3.0 branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8.6
