### ISSUE TITLE
Forgot password function sends wrong message

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13116]
We need to send the same message regardless.

https://docs.google.com/document/d/1d4TvfQ8tCPQ5gLOq-2IcqxBnUiOf5wLbyZ0PjPsj3kg/edit

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13132

**Comment by bryanboza** [comment]
Fixed, tested in the las master and now we have the same response in both cases...
