### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13117]
https://docs.google.com/document/d/1LwJgxjMSld72syHDMp_Q_67gQB3-utVExCxhuudti3g/edit

**Comment by wezell** [comment]
We should review the RoleAjax too

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13136

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgress // Chrome

**Comment by wezell** [comment]
Call the webUserApi getLoggedinUser(request);

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13356

**Comment by bryanboza** [comment]
Fixed, tested again after the last improvements and works fine

**Comment by bryanboza** [comment]
Fixed, tested with the last code of release-4.3.0 and it is working as expected
