### ISSUE TITLE
IE11 - Cannot select new times from dojo TimePicker in back-end. 

### ISSUE THREAD

**Issue by RobertBicknell** [dotCMS/core#13113]
In IE11 the time picker can be opened, but on click, no selection / change event takes place and so updateDate() is never fired. For example, login in demo.dotcms.com as admin and try to change the publish time for a News or Blog item.

## Expected Behavior

The TimePicker should work as normal and in other browsers by allowing the selection of any time displayed in the pop-up.

## Possible Solution

* Check for missing es7 polyfills for array and object
* The selection is actually converted to a datetime object and experiences and validation error because the date part is not filled (can be seen debugging updateDate() when onchange does fire). Perhaps IE11 somehow detects the validation error and cancel the change event.

## Known Workarounds

Typing the new time allow the update to be made.

## Steps to Reproduce (for bugs)

Can be reproduced on demo.dotcms.com - open a News or Blog item in IE11 and try to change the publish tie.  (as of Nov 27 2017) 

1.
2.
3.
4.

## Context

Generated by Zendesk ticket: https://dotcms.zendesk.com/agent/tickets/94779

## Your Environment

* dotCMS version used:
IE11
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by fmontes** [comment]
It happen to me on Windows 10 and IE 11.125.XXX
And Robert on Windows 10 and IE 11.674

**Comment by hmoreras** [comment]
We are currently running Dojo.js verison 1.8.3 and that version do not support IE 11. we are making the update to 1.8.6 that add the support.

Reference: http://dojotoolkit.org/reference-guide/1.10/releasenotes/1.8.html#releasenotes-1-8

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13226

**Comment by bryanboza** [comment]
Fixed, tested on master // IE11 // W10
