### ISSUE TITLE
[Upgrade] Problem with creating FK in SQL Server due to mismatch of data/length of columns involved.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13129]
A customer running dotCMS 3.6.2 with SQL Server database attempted to upgrade to 3.7.x releases, and found this issue during the upgrade process:

```
[27/11/17 11:37:35:476 CST] ERROR runonce.Task03600UpdateMssqlVarcharTextColumns: Can't create foreign key on table 'cms_role' in columns [id]. Message: Column 'cms_role.id' is not the same length or scale as referencing column 'workflow_task.assigned_to' in foreign key 'FK_workflow_assign'. Columns participating in a foreign key relationship must be defined with the same length and scale.
com.microsoft.sqlserver.jdbc.SQLServerException: Column 'cms_role.id' is not the same length or scale as referencing column 'workflow_task.assigned_to' in foreign key 'FK_workflow_assign'. Columns participating in a foreign key relationship must be defined with the same length and scale. 
```

As per this upgrade task 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03600UpdateMssqlVarcharTextColumns.java#L418 

We're setting the cms_role.id column as a NVARCHAR(36) one, and 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task03600UpdateMssqlVarcharTextColumns.java#L582

sets the workflow_task.assigned_to column as a NVARCHAR(255) one.

According to SQL Server documentation (https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-foreign-key-relationships) 

> A FOREIGN KEY constraint specified at the table level must have the same number of reference columns as the number of columns in the constraint column list. The data type of each reference column must also be the same as the corresponding column in the column list. 

So by the time Foreign Keys are re-added to the current schema, it fails with the error above. 

## Expected Behavior
We should either set the same data type and length on both columns, and make sure this doesn't break any other relationship with other tables.

## Current Behavior
Upgrade task fails and cannot move forward with the upgrade process.

## Possible Solution
Since assigned_to column always points to a Role/UserRole on cms_role, it should have its NVARCHAR value set to 36. 

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/94824

This logic remains in place for 4.2.x releases, so any customer running 3.6.2 or older releases may deal with this problem.

## Your Environment

* dotCMS version used: 3.7.x, 4.2.x.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App Server.
* Java Brand and version: Any supported Java 8 version
* Database and version: SQL Server database only.
* Application module (if apply): N/A/

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13227

**Comment by bryanboza** [comment]
Fixed, tested in the last master code // MSSQL 2017 // FF
