### ISSUE TITLE
Upgrade Elastic Search

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13127]
Currently on 1.7. Let's see how far we can get. 

Branches:

ee: https://github.com/dotCMS/enterprise-2.x/tree/issue-13127
core: https://github.com/dotCMS/core/tree/issue-13127

**Comment by wezell** [comment]
Let's target the highest AWS offers and no more.

![screen shot 2017-11-28 at 2 27 53 pm](https://user-images.githubusercontent.com/934364/33339841-65206a46-d448-11e7-8a22-7401455bcd4e.png)

**Comment by nollymar** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/587
PR Core: https://github.com/dotCMS/core/pull/13648
