### ISSUE TITLE
NPE error in Webdav with languages other than 1

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13134]
System is throwing NPE errors on a clean install with languages other than 1 on Webdav

## Expected Behavior
System should allow to create/update data using a different language than 1 with Webdav

## Current Behavior
We' getting NPE errors using a different language than 1 with Webdav

## Steps to Reproduce (for bugs)
1) Extract a base 4.2.2 installation downloaded from https://dotcms.com/download/
2) Start up with default H2 database
3) Set up Webdav to localhost on port 8080 with path /webdav/live/2
4) Click a folder to try to expand it
5) You will get a NPE error 
https://gist.github.com/shaydotcms/45678f86c470ce3fe187ab266f3533c2

## Your Environment
* dotCMS version used: master branch
* Database and version: H2 db
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox 
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by bryanboza** [comment]
Also we have this other error https://gist.github.com/bryanboza/f13a26b1a008ec165577609c7b8846f8 , you can reproduce trying to connect with the same steps via finder, or using cyberduck trying to create a new folder

**Comment by aDNers** [comment]
Bryanboza: I have seen the same error in my logs, maybe they are related issues.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/13188

**Comment by bryanboza** [comment]
Tested in the last master branch; Now we are able to upload files in different languages, but are having this permissions exception on logs: https://gist.github.com/bryanboza/ee507b64ad46ce75460e5540a707540f

We need take look of this. 

Tested in the latest master // Cyberduck 6.3.1 // postgres

**Comment by erickgonzalez** [comment]
Able to reproduce with the following steps:

1- Create a new folder
2- Upload several files to that new folder (if you upload only one file, doesn't show any error)

**Comment by erickgonzalez** [comment]
Main issue fixed, new issue Bryan and I described above is gonna be fixed here https://github.com/dotCMS/core/issues/13309
