### ISSUE TITLE
REST API: unauthenticated users should only see live content.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#13131]
Reference ticket: https://dotcms.zendesk.com/agent/tickets/94830

Reproducible on demo, if you add "+working:true" to a REST query, dotCMS will deliver the working version of content even to unauthenticated users. 

e.g.
This link will correctly show no information, as this piece of content is not published: 
https://demo.dotcms.com/api/content/id/2fba86cb-ce57-49eb-bb6d-199a4094f5be

If you add +working:true to some query, you get the content in the working state. In this case you can see the content of the unpublished identifier 2fba86cb-ce57-49eb-bb6d-199a4094f5be. 
https://demo.dotcms.com/api/content/render/false/type/json/query/+contentType:RequestProspectus%20+working:true

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
