### ISSUE TITLE
asset_name on identifier gets mixed case on move

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#13147]
Basically if you upload a file with mixed case and move it. I changed via host/folder field though happens also with cut paste it will save to identifier with mixed case on asset_name. 

This is ONLY happening on 4.1.1 NOT on 4.2

**Comment by cfalzone** [comment]
Just subscribing to updates. This is affecting us right now.

**Comment by jcastro-dotcms** [comment]
A hotfix has been created to address this issue for dotCMS 4.1.1, and has been uploaded to our Hotfix Repo.
