### ISSUE TITLE
Unable to see the workflow steps from edit mode on pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13165]
Related to #12675 

We are unable to see the workflow action steps, this from edit mode on pages 

## Expected Behavior
As in the previous version, when you create a new page and you assign to a workflow step, we should be able to see the next steps of the workflow from edit mode on pages.

This is on demo: https://screencast.com/t/IIWw4BRYYM

This in the last master: https://screencast.com/t/FJDZ8kTnOAQ

## Current Behavior
We are unable to see the worflow steps from edit mode, you need go to the content portlet and search for this page.

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Create a new page 
3. Assign this page to a workflow 

## Your Environment
Tested on the last master // Postgres // Chrome

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13173

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we can see the steps without problems, new problem with the default scheme reported here #11609
