### ISSUE TITLE
Mislead message thrown when trying to create a new language with wrong values

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13168]
An incorrect message and an exception are thrown if a user types unexpected values for fields when a new language is created, ie. type a language name in the Language Code field.

![create_language](https://user-images.githubusercontent.com/8741395/33579565-4a424aa8-d918-11e7-9024-796236b2cb06.gif)

**Log error:** https://gist.github.com/nollymar/dbb8ea4857a3945291b91cebda722f6b
**Wrong message:** "Language Not Saved. There is already another Language with the same Language code and Country code."

## Your Environment

* dotCMS version used: dotCMS 4.2.x
* Browser Name and version: Google Chrome
* Operating System and version: MacOS
* Application Server and version: Tomcat8
* Java Brand and version: JDK 8
* Database and version: Postgres
* Application module (if apply): Languages

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15082
