### ISSUE TITLE
Change Host Delete strategy

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13179]
Host delete actually happens inside a transaction, which, depending on the amount of data, can be a very long operation. 

Let's remove the annotation for the hostAPI.delete method and also look for methods that it calls internally that can be time consuming (like conAPI.deleteContentByHost)

**Comment by shaydotcms** [comment]
Waiting for https://github.com/dotCMS/core/issues/13375

**Comment by shaydotcms** [comment]
Same NPE error when trying to access backend after upgrade in Mysql
