### ISSUE TITLE
Unable to push images on static push

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13176]
When you push a folder containing other type of files different than pages (i.e.: images, videos, etc), the folder is not pushed and the logs show "WARN staticpublishing.StaticPublisher: Bundle is EMPTY"
If you click force push, the folder of images do get pushed.

## Expected Behavior
Pushing a folder containing other type of files different than pages for the first time, should work successfully without having to do a force push.

## Current Behavior
You have to force push to be able to send the folder with images.

## Possible Solution
Do a force push will send the folder of images.

## Steps to Reproduce (for bugs)
1. Generate Key Pair and PEM file.
2. Upload certificate to your remote node in command line using SSH.
3. Test connection client to server.
4. Generate the file "com.dotcms.staticpublish.listener-0.1.jar" with the appropriate values for key.file.path, ssh.user, hosts and remote.path. Then upload the jar to dotcms instance.
5. Setup a publish environment using appropriate license.
6. Create a folder and upload a few images to it.
7. Push the folder to the remote node without using force push.
8. You will see that nothing was pushed and logs say "WARN staticpublishing.StaticPublisher: Bundle is EMPTY"
9. If you do a force push, the folder is pushed.

## Your Environment
* dotCMS version used: master branch
* Database and version: Sender Postgres 9.3.5
* Operating System and version: Sender Ubuntu 14.04.1 / receiver Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/565

**Comment by bryanboza** [comment]
Fixed, tested in the last release-4.2.3 branch // Postgres // Tomcat and now works as expected, also tested the fallback properties and works as expected too.
