### ISSUE TITLE
Stopped sites need to be available in the site selector

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13178]
When you stop a site in dotCMS we (sometimes) do not allow it to be selected in the site selector.

We need to show live and stopped sites in the site selector.  Only archived sites should be excluded.

1. Create a new site
2. Stop it
3. Refresh the page

![screen shot 2017-12-06 at 10 42 41 am](https://user-images.githubusercontent.com/934364/33670120-4d6fa224-da72-11e7-9700-0a08e52d5a66.png)

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/13167

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we are able to see the stopped sites in the dotSiteSelector, tested with FF & Chrome
