### ISSUE TITLE
Add "System Workflow" scheme to include all default workflow actions

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#13174]
In version 4.2.x and earlier, if you do not assign a mandatory workflow to a content type, dotCMS automatically includes a number of default actions (e.g. "Save", "Save / Publish", "Assign Workflow", etc.) which are available based on the user's permissions on the content.

With the new workflows, we need to put all of these default actions into a "System Workflow" scheme that can be added to a content type like any other workflow scheme.  Note that this also means:

* This System Workflow scheme is the scheme that should be assigned by default to any new content type.
    * It can be removed from the content type as long as another workflow scheme has been assigned to the content type.
* The upgrade task will need to add the System Workflow scheme to any existing content types which do _not_ have a mandatory workflow scheme assigned.

**Comment by wezell** [comment]
Is this what the SYSTEM_WORKFLOW looks like?

- Archived
	- Unarchive
	- Delete
- Unpublished
	- Archive
	- Publish
	- Copy
- Published
	- Republish
	- Unpublish
	- Copy

**Comment by john-thomas-dotcms** [comment]
Semi-full spec for the system workflow (initial pass):

#### Step: Unpublished

* Resolved: No
* Action: Archive
    * Show When: Locked, Unlocked
    * Subactions:
        *Archive Content
        * Unlock Content
    * Assign To: Current User
    * Next Step: Archived
* Action: Publish
    * Show When: Locked, Unlocked
    * Subactions:
        * Save Content
        * Publish Content
        * Unlock Content
    * Assign To: Current User
    * Next Step: Published
* Action: Copy
    * Show When: Locked, Unlocked
    * Subactions:
        * Copy Content
    * Assign To: Current User
    * Next Step: Unpublished (e.g. no change)
* Action: Save
    * Show When: Locked
    * Subactions:
        * Save Content
    * Assign To: Current User
    * Next Step: Unpublished (e.g. no change)

#### Step: Published

* Resolved: Yes
* Action: Republish
    * Show When: Unlocked
    * Subactions:
        * Publish Content
    * Assign To: Current User
    * Next Step: Published (e.g. no change)
* Action: Unpublish
    * Show When: Locked, Unlocked
    * Subactions:
        * Unpublish Content
    * Assign To: Current User
    * Next Step: Unpublished
* Action: Copy
    * Show When: Locked, Unlocked
    * Subactions:
        * Copy Actionlet
    * Assign To: Current User
    * Next Step: Published (e.g. no change)
* Action: Save
    * Show When: Locked
    * Subactions:
        * Save Content
    * Assign To: Current User
    * Next Step: Unpublished
* Action: Save / Publish
    * Show When: Locked
    * Subactions:
        * Save Content
        * Publish Content
    * Assign To: Current User
    * Next Step: Published (e.g. no change)

#### Step: Archived

* Resolved: Yes
* Action: Unarchive
    * Show When: Unlocked
    * Subactions:
        * Unarchive Content
    * Assign To: Current User
    * Next Step: Unpublished
* Action: Delete
    * Show When: Unlocked
    * Subactions:
        * Delete Content
    * Assign To: Current User
    * Next Step: Archived (e.g. no change)

**Important Note:**

* By changing the default actions to an actual workflow, we're actually changing it so that **_all_** unpublished content in the system will show up in someone's workflow queue.
    * This is different because in previous versions items only showed up in a user's workflow queue if the workflow assigned to the content type was _not_ the Default Workflow (or the "Assign Workflow" action was explicitly executed).
    * I think this is a good thing, but it needs to be understood (and documented in the changelogs).

**Comment by wezell** [comment]
Great work @john-thomas-dotcms 

One other thing is that we are also going to have to insert permissions, e.g. 
**Action: Save / Publish** 
(Permission: Anyone who can Publish)
- Show When: Locked
- Subactions:
  - Save Content
  - Publish Content
- Assign To: Current User
- Next Step: Published (e.g. no change)

**Comment by jgambarios** [comment]
@jdotcms The `Save & Publish` action have the actionlets in the wrong order, we need to change the order in the starter site, generar a new starter zip and modify the upgrade task of the System Workflow.
Please make sure the order in the other actions is correct.

**Comment by bryanboza** [comment]
Fixed, to many cards reported around that...
