### ISSUE TITLE
Image selection dialogue should be resizable

### ISSUE THREAD

**Issue by jbjornson** [dotCMS/core#13177]
The select image dialog is not resizable and is difficult to use, especially with many levels of directories and/or many files the selected directory.

## Expected Behavior
The user should be able to resize the dialog as well as the file tree on the left hand side of the dialog.

## Current Behavior
The dialog and file tree are fixed size.

## Your Environment
* dotCMS version used: 4.1.1

**Comment by jbjornson** [comment]
![image_selection_dialogue](https://user-images.githubusercontent.com/881278/33658805-3f69dd78-da7e-11e7-9f17-65722dffb8eb.png)

**Comment by levosgien** [comment]
https://dotcms.zendesk.com/agent/tickets/94894
