### ISSUE TITLE
Unable to do an static push on entire site

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13185]
System fails to static push an entire site: https://gist.github.com/shaydotcms/a6a57c362fb291d6d55f1451a51538e9

## Expected Behavior
System should successfully push an entire site.

## Current Behavior
Errors are showing when you push an entire site.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to System> Configuration> Licensing tab. Upload a Platform license so you can configure static push.
3. After that, switch to Publishing Environments tab and configure an static push environment
4. Navigate to Site> Browser.
5. Right click over the root (demo.dotcms.com) and select Push Publish
6. Check the logs, you will see the error described: https://gist.github.com/shaydotcms/a6a57c362fb291d6d55f1451a51538e9

## Your Environment
* dotCMS version used: master branch
* Database and version: Sender Postgres 9.3.5
* Operating System and version: Sender Ubuntu 14.04.1 / receiver Mac OS 10.10.5
* Browser Name and version: Firefox v45.0.1
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
Please add logging to the IOException that says what asset failed to push

**Comment by shaydotcms** [comment]
In fact, the error does show up but the site is successfully pushed.

**Comment by bryanboza** [comment]
We still having issues here, now we are unable to send a single host, if you from the site browser  portlet try to push the site, we are including all the other sites in the bundle

**Comment by bryanboza** [comment]
After check again seems the problem is because we have dependencies in the data set that we are using to test, Not an issue

**Comment by bryanboza** [comment]
Now we are able to push entire sites without problems
