### ISSUE TITLE
Unable to delete the notify assignee sub-action from workflow actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13183]
We have an error when you try to delete this sub action from a workflow action 

## Expected Behavior
Since we show the delete button we should be able to delete without problems 

Or this is a mandatory sub-action, then we should hide the delete button 
SC: https://screencast.com/t/G9QXhkOb

## Current Behavior
Right now when you delete it, the system is hiding the sub-action, but we are having an error in the log, after you save the changes, this appears again 
```
ERROR business.PermissionBitAPIImpl: Permissionable object is null
```

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Add a new workflow 
3. Add a new step to this workflow 
4. Try to delete the notify assignee sub-action 
5. Save it 

## Your Environment
Tested on the last master // mysql // FF

**Comment by jgambarios** [comment]
Unable to reproduce

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master
