### ISSUE TITLE
[Permissions] Content Types do not show Permissions if Site/Folder value is a Folder

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13180]
If we create/update a content type and set its Site/Folder value to a Folder, the system doesn't show the permissions this content type is inheriting. It should show it's inheriting from its parent folder.

Now, if we create assets under this Folder, we can see that new files are inheriting permissions from it.

## Expected Behavior
If a folder is set on Site/Folder attribute of a Content Type, then permissions should reflect it's inheriting permissions from this parent object, in the same way it does if a Site was selected.

## Current Behavior
An empty permissions list is displayed.

## Possible Solution
Check permissions inheritance for content type if a Site or Folder is selected. By switching values here, we should:

- Show consistently where it's inheriting permissions from.
- Update permissions once the value is updated.
- Question: If a content type has individual permissions and this Site/Folder attribute is changed, should we reset permissions here?

## Steps to Reproduce (for bugs)

1. Create a folder called /uploads on demo.dotcms.com site.
2. Create a File-type Content Type called "User Upload". Select "demo.dotcms.com/uploads" folder as its Site/Folder value: 
<img width="1521" alt="screen shot 2017-12-06 at 1 47 26 pm" src="https://user-images.githubusercontent.com/1717110/33682710-fd33e4c0-da8d-11e7-9c8f-a3281d8c622c.png">

3. Check its permissions tab. Shows empty, and should show permissions are inherited from this folder. 

<img width="1521" alt="screen shot 2017-12-06 at 1 47 37 pm" src="https://user-images.githubusercontent.com/1717110/33682733-142d46e4-da8e-11e7-90e3-7471dde95cad.png">
4. Go to Site Browser and upload a User Upload file to it.
5. Once it's uploaded, check its permissions. It's inheriting permissions from demo.dotcms.com site 

<img width="1414" alt="screen shot 2017-12-06 at 2 03 20 pm" src="https://user-images.githubusercontent.com/1717110/33682794-480e195c-da8e-11e7-8e81-a171b884f464.png">

## Context
Reported by customer: 
https://dotcms.zendesk.com/agent/tickets/94881

## Your Environment

* dotCMS version used: 4.2.x.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any Application Server.
* Java Brand and version: Any Supported Java 8 Server.
* Database and version: Any DB.
* Application module (if apply): N/A.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/13528

**Comment by shaydotcms** [comment]
Passed QA
After creating a File type Content Type called "User Upload" and selecting "demo.dotcms.com/uploads" folder as its Site/Folder value, permissions tab is actually showing that permissions are inherited from this folder.
![image](https://user-images.githubusercontent.com/8741846/35646951-9fbe8478-0696-11e8-98ab-7ad5cf390bbf.png)

Then I uploaded file to "User Upload" and checked its permissions. It's inheriting permissions from demo.dotcms.com site
![image](https://user-images.githubusercontent.com/8741846/35647018-dbe4f8c4-0696-11e8-8242-de35df04584b.png)

Mac OS 10.10 / Postgres 9.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by dsilvam** [comment]
Note to QA: please test the following scenarios:

- Create content type that lives under demo.dotcms.com. Make sure content type's permissions are inherited from demo.
- Create content type that lives  under folder, which inherits permissions from demo.dotcms.com. Make sure content type's permissions are inherited from demo.
- Create content type that lives under folder, which has individual permissions (you need to check everything under 'Contributor' Role). Make sure content type's permissions are inherited from folder with individual perms.

**Comment by shaydotcms** [comment]
Passed QA
Mac OS 10.10 / Postgres 9.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
