### ISSUE TITLE
Create PageResource Response for Edit Mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13192]
We need to create methods in the page resource to return the page in EDIT_MODE, complete with proper markup

**Comment by wezell** [comment]
Tested these cases:

Edit mode
1. Edit Mode content shows live = live, preview=working and edit=working 
2. Containers respect live/working
3. Template respects live/working
4. Widgets respect live/working
5. Shorty Serves live or working depending on the last mode

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13193
https://github.com/dotCMS/enterprise-2.x/pull/572
