### ISSUE TITLE
Unable to upload files to the document content type

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13208]
Related to #11609 

We are experiencing some issues when you try to upload a some file to the document content type,  this because we violates the foreign key constraint "fk_workflow_step"

## Expected Behavior
We should be able to upload documents to this structure without problems 

## Current Behavior
Since the workflow changes now we have problems uploading files to this content types
Here the log: 
https://gist.github.com/bryanboza/2073b675aa3aeefb71bce12b24d7cc71

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to the content portlet 
3. Select the document content type
4. Try to upload some file here 
5 .Check the dotcms.log file 

## Your Environment
Tested in the last master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13224

**Comment by bryanboza** [comment]
We still having problems on this card, because now after upload the file we don't have actions on this workflow, just the "Cancel" and don't do nothing 
Here the video:  https://screencast.com/t/9lyN91eg

**Comment by bryanboza** [comment]
Fixed, we have no action because the document management is a mandatory workflow, and also we create a new ticket for the actions here #13307. Those are separated things... The main problem was fixed on the PR...
