### ISSUE TITLE
[REST] Return 200 OK instead of 404 if data requested returns empty list

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13205]
Currently, our ContentResource (and maybe other REST endpoints) return a response status of 404 in case the requested data returns an empty list. 

For example this request 

https://demo.dotcms.com/api/content/query/+contentType:test/limit/1 

deals with pulling 1 content from a content type called "Test" which does not exist on our demo site. Despite we're getting an empty contentlets list, the response status is 404, which is deceiving and confusing. 404 should be reserved for missing endpoints.

<img width="1516" alt="screen shot 2017-12-12 at 10 55 53 am" src="https://user-images.githubusercontent.com/1717110/33898104-07b216b2-df2d-11e7-84be-e152c80c0e6e.png">

--

From: https://tools.ietf.org/html/rfc7231#section-6.3
6.3. Successful 2xx

The 2xx (Successful) class of status code indicates that the client's
request was successfully received, understood, and accepted.

From: https://tools.ietf.org/html/rfc7231#section-6.5.4
6.5. Client Error 4xx

The 4xx (Client Error) class of status code indicates that the client seems to have erred. Except when responding to a HEAD request, the server SHOULD send a representation containing an explanation of the error situation, and whether it is a temporary or permanent condition. These status codes are applicable to any request method. User agents SHOULD display any included representation to the user.

## Context: 
Reported by customer. https://dotcms.zendesk.com/agent/tickets/94911

## Your Environment

* dotCMS version used: 4.2.x
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: Any supported Java 8 version.
* Database and version: Any supported DB.
* Application module (if apply): N/A

**Comment by oarrietadotcms** [comment]
We have another client that just reported this one again. Using 4.2.1

**Comment by gabbydotCMS** [comment]
One more client having troubles with this after upgrading to 4.2.1.

**Comment by bryanboza** [comment]
Fixed, tested on the master branch and now we return an empty list 
https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/3431e2d8-dd03-4af3-a03b-a965b25920c6/00000134.png

**Comment by oarrietadotcms** [comment]
PR for 4.3.4: https://github.com/dotCMS/core/pull/16205
