### ISSUE TITLE
Status inconsistencies when you try to push to some static environment with multiple endpoints 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13204]
In the new static push the result message is handled by the OSGI plugin. Then if you are sending to an environment that have multiple endpoints, the plugin is updating the global status of the bundle and isn't adding a separated status to this one 

## Expected Behavior
As in the single push publish, if some environment have multiple endpoints associated, and some of those ones fails, we need show a message "failed sending to some environments " and have individual information of the endpoints in the bundle detail window

## Current Behavior
Every endpoint add their individual status in the bundle info, but this is not the case of the new static endpoints, the OSGI plugin just update the global status
SC: https://screencast.com/t/4MaUXxscn

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Apply the platform license 
3. Add a new push environment with multiple endpoints (mixed mode) 
4. Make sure you don't have the publish listener plugin uploaded or stop it 
5. Try to push something 
6. Check the bundle status 

## Your Environment
Tested in the last release-4.3.2 // postgres

**Comment by wezell** [comment]
will be fixed by #13211
