### ISSUE TITLE
Static bundle still in pending after finish the creation if you stop the publisher plugin.  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13201]
If you top the OSGI publisher  plugin and try to push something, we need just create the bundle, save in file system and the bundle should be deleted from pending. 

## Expected Behavior
After finish the bundle creation we should delete it from pending 

To the system should be ok if you have a listener plugin for push it, but if you don't have it, this shouldn't affect. 

## Current Behavior
We keep this task in pending waiting for the plugin 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Upload and stop the "com.dotcms.staticpublish.listener" plugin
3. Configure your static push environment 
4. Try to push some folder 

## Your Environment
Tested on the last release-4.2.3 code // postgres

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/569

**Comment by bryanboza** [comment]
Foxed, tested in the last code of release-4.2.3 // postgres and now we delete it from pending and leave as "Bundle saved successfully in filesystem"
