### ISSUE TITLE
Update sidenav for iPad and tablets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13215]
We have some [issues](https://user-images.githubusercontent.com/2641437/31140084-a9faffd0-a830-11e7-8b26-b3b9f1179f25.jpg) with the space we have in an iPad or tablet.

I think we can fix some of the issues by giving more space to the portlet so the idea is to make the sidenav overlay the content / porlet.

### Mocks

By default should sidenav should be collapsed:

![normal](https://user-images.githubusercontent.com/751424/34005084-688e4472-e0bf-11e7-83fc-a853e998ee3b.png)

When the user clicks the hamburger button it should expand BUT overlaying the content:

![expanded](https://user-images.githubusercontent.com/751424/34005114-7adb1cc2-e0bf-11e7-9dd4-191a26a0b39e.png)

### Acceptance Criteria

1. Match the design
2. By default in iPad the menu should be collapsed
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Use media queries for the css
5. Is you need to check the size of the screen in the typescript side we can use [ng2-responsive](https://github.com/ManuCutillas/ngx-responsive) only if it's really necessary.
6. Transparent overlay should fadein and fadeout
7. Click outside the sidenav should hide it
8. Click in an item in the sidenav to change portlet should hide it
9. Scroll when necessary remains
10. We have mixins for the media queries, use them if possible event if we have to update them: https://github.com/dotCMS/core-web/blob/f5fe7e59ac5f29786edaa855b071151ff293827a/src/styles/primeng-theme/utils/_mixins.scss#L50

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Postgres // iPadAir2
