### ISSUE TITLE
Error when starting with empty DB 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13213]
Reproduced in Postgres:

https://gist.github.com/jgambarios/8e0fec71db4b4ab068d5faf2fc23b31f#file-error-L28

Related to this changes: https://github.com/dotCMS/core/commit/6b17f56d44556ee77db5168f17e031d903a38cad

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13260

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
