### ISSUE TITLE
Fix repackaging of specific class in Tika Library.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13212]
An exception reported by a customer https://dotcms.zendesk.com/agent/tickets/94812

Indicates that a class is missing in Tika Library. For this line of code in Tika jar's DocumentDocument.java class

```
public static final SchemaType type = (SchemaType)XmlBeans.typeSystemForClassLoader(DocumentDocument.class.getClassLoader(), "schemaorg_apache_xmlbeans.system.sE130CAA0A01A7CDE5A2B4FEB8B311707").resolveHandle("document2bd9doctype");
```

 and given the exception in log files

```
Caused by: java.lang.RuntimeException: Cannot load SchemaTypeSystem.  Unable to load class with name  schemaorg_apache_xmlbeans.system.sE130CAA0A01A7CDE5A2B4FEB8B311707.TypeSystemHolder.  Make sure the generated binary files are on the classpath.
```

It looks like a class reference needs to be repackaged in Tika library. This jar shows that

`com.dotcms.repackage.schemaorg_apache_xmlbeans.system.sE130CAA0A01A7CDE5A2B4FEB8B311707.TypeSystemHolder
`

class exists, so it would make sense to update the DocumentDocument.java class and repackage a new version of this jar. Any other occurrence of these xmlbeans classes' call on the jar would require a similar update in code

Exception: https://gist.github.com/joseorsini/848f1f706bb104f6e04337269dc0e37e

This is triggered once a .docx or any Word Document is uploaded to the application.

## Your Environment

* dotCMS version used: 4.2.x.
* Browser Name and version: Any Browser.
* Operating System and version: any OS.
* Application Server and version: Any App Server.
* Java Brand and version: Any supported Java8 version.
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13243
https://github.com/dotCMS/dotcms-libs/pull/32

**Comment by jgambarios** [comment]
Waiting for the client feedback before to mark it as done.

**Comment by wezell** [comment]
being done in #13482
