### ISSUE TITLE
Generate separate bundles per push type

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13211]
Currently, a bundle can be sent to an environment that can be comprised of different types of endpoints (dynamic, static aws3, static file system). Each handle statuses in different ways, so having them sharing a global status for the bundle makes it hard and can lead to confusion. One possibility is to generate a different bundle per push/endpoint type, so they can have their own separate statuses.

**Comment by wezell** [comment]
dupe: #13204
