### ISSUE TITLE
Unable to go to the backend after login in frontend 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13223]
If you are navigating on Frontend (FE) and you login on it, if you try to see admin console (BE) **"/dotAdmin"** , we just shows a blank page and never loads the BE console

## Expected Behavior
We should be able to see FE and BE in the same window without problems 

## Current Behavior
We just show a blank page and we are having an error in console 
![image](https://user-images.githubusercontent.com/2641437/34057517-e0e6d118-e19c-11e7-95ef-5ced73e024c6.png)

Here the video: https://www.screencast.com/t/TrZdufeib

## Steps to Reproduce (for bugs)
1. Start the dotcms instance 
2. Go to the FE, and then login in any page 
3. Try to see the admin console "/dotAdmin"
4. Check the JS console 

## Your Environment
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
The fix for this will be done here: https://github.com/dotCMS/core/issues/2252
