### ISSUE TITLE
Save page model

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13235]
As a User I want to be able to save all the changes I do in the pages.

### Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

#### core-web
1. Get the model correctly
2. Send the model to the server when user click save button
3. Save button should only be enable when model is updated

#### core
1. Create the endpoint that get the model and update/save the whole page

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13358
