### ISSUE TITLE
Stop eating exceptions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13241]
We need to do a code search for exceptions that are being caught and rethrown that do not include the original exception as the root cause, e.g.

```
	catch(Exception e){
		throw new DotDataException(e.getMessage());
	}
```
should be:

```
	catch(Exception e){
		throw new DotDataException(e.getMessage(),e);
	}
```

**Comment by wezell** [comment]
We need to to this for DotHibernateExceptions, DotDataExceptions, DotSecurityExceptions, DotValidationExceptions  Any others?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13251

**Comment by wezell** [comment]
Do a text search for `Exception(e.getMessage())` and put eyes on where ever that is called.

**Comment by erickgonzalez** [comment]
PR's https://github.com/dotCMS/core/pull/13416 and https://github.com/dotCMS/enterprise-2.x/pull/576
