### ISSUE TITLE
Add dialog to choose edit template or layout

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13270]
As a User I want to be able to edit a template to affect all the pages that use it or just the layout for a particular page.

### Mock
![edit page - content 3](https://user-images.githubusercontent.com/751424/34470875-b3bb1c28-ef00-11e7-8ea0-63d60e679cbc.png)

### How to do this?
1. Maybe we can use a guard called [CanDeactivate](https://angular.io/api/router/CanDeactivate) to achieve this.
2. To save a template as a layout we just need to do the request without template name.

### Acceptance Criteria

1. When user goes from "Content" to "Layout" and the page have a template applied we show the dialog
2. If user select "Edit Template" we just edit the template as usual
3. If user select "Edit Layout" we need to clone the template, save it as a layout and applied to the page, then the user just edit that cloned template as usual
4. Match the design
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13335

**Comment by luisrojascr** [comment]
It presents some layout issues in iPad.

Tested in iPad version 1.

![ipad-screenshot](https://user-images.githubusercontent.com/1789179/34735470-32496c2c-f535-11e7-9f0f-12aa5b0f2b25.jpg)

**Comment by fmontes** [comment]
I didn't found that issue in a recent iOS version I do found an issue with the iframe overlaying the toolbar in iPad, I fix it here: https://github.com/dotCMS/core-web/pull/510
