### ISSUE TITLE
Stay in Edit Mode when browsing around

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13276]
If you are in edit mode, (EDIT, PREVIEW) and you browse around the site, we should maintain that mode where possible.

**Comment by fmontes** [comment]
1. This is kind of working, but we don't know why dotcms it's rendering EDIT_MODE html in the page
2. Because we're browsing inside the iframe the url (queryParams) doesn't change, that means that if we go to layout and go back to content we'll render the "old" page.
