### ISSUE TITLE
Remove Requires Lock from the workflow UI and the logic around it

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13287]
After the changes on https://github.com/dotcms/core/issues/12960 we need to remove from the Workflow Action window the `Requires Lock` field along with the logic related to it, meaning the **requiresCheckout** validations.

We need to:

1. Remove from the UI the **Requires Lock** field
2. Remove all the required **requiresCheckout** logic
3. Create a new Save Content sub-action (checkout, checkin)
4. If a client already calls directly the checkin method is going to work because the `DISABLE_WORKFLOW` is null
5. If the checkin is called from a sub-action we need a new method that calls the **fireWorkflowPreCheckin**, then we disable the `DISABLE_WORKFLOW` property and then we call the **fireWorkflowPostCheckin** which is going to call the **executeAction** of the actionlet, meaning, will execute the actionlet.
With the `DISABLE_WORKFLOW` if the sub-action calls a checkin no extra workflows will be executed.

Before to work on this ticket we need to finish first https://github.com/dotCMS/core/issues/12676 and https://github.com/dotCMS/core/issues/13174

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13775

**Comment by bryanboza** [comment]
Fixed, now it is working ok, @wezell we need define how should be the upgrade process with the custom workflows from previous versions
