### ISSUE TITLE
Allow the "Next Step" of a Workflow Action to be set to "Current Step"

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#13294]
Currently when a workflow action is executed, the action always takes the content into a specific workflow step.  If you want an action to not change the workflow step of the content, then the action must specify the step it's in as the "Next Step".

However with the new workflow changes, the same action can be shared among multiple workflow steps, so if an action which is not supposed to change the workflow step always takes the content to a specific workflow step it can't easily be used from different workflow steps.

## Current Behavior

Currently for any action, you have to specify the "Next Step", which is a specific step.  So for example if the content is in "Published" step and you have a "Copy" action in that step which should keep the content in the "Published" step, then in the "Copy" action you must specify the "Next Step" as "Published" (so the step won't change).

But with the new workflows, you can share the same action among multiple workflow steps.  And if the "Copy" action can only go to "Published" as the "Next Step", then it can't easily be shared among multiple workflow steps.

## Possible Solution

Add a "Current Step" option to the "Next Step" selection drop-down.  If "Current Step" is selected, then when the action is executed the content just does not change steps (no matter what step it's in).

Similar to how the "Current User" allows an action to keep the current user the same, without specifying a specific user.

## Known Workarounds

Create multiple actions - one for each step of the content it's needed in.

## Context

This is important to implement with the new feature of sharing workflow actions among multiple steps.  Otherwise the "Next Step" assignment significantly limits how much actions can be shared among different workflow steps.

**Comment by jdotcms** [comment]
so - here is the rule - if a workflow action is being processed that specifies a next step that does not exist (lets say from a push publish or whatever), it stays on the current step

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13317

**Comment by bryanboza** [comment]
Unable to save actions with the current step. We have this error on log and we are unable to save the action.
Log: https://gist.github.com/bryanboza/eafd23e42f77e12db482df15db3b794a

**Comment by bryanboza** [comment]
Fixed, tested on the last master // postgres // FF
