### ISSUE TITLE
Remove the Mandatory option from Workflows

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13303]
Now as a Content Type can have multiple Workflows the concept of **Mandatory** does not apply anymore, we need to remove that field from the UI and code.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13560

**Comment by oswaldogallango** [comment]
Core P.R https://github.com/dotCMS/core/pull/13580 and EE P.R https://github.com/dotCMS/enterprise-2.x/pull/584

**Comment by oswaldogallango** [comment]
codacybot changes P.R https://github.com/dotCMS/core/pull/13583

**Comment by bryanboza** [comment]
For now we don't have more this option at UI level. Everything still working normally for now

**Comment by bryanboza** [comment]
As part of the changes we need remove the workflow default action login, right now after apply the license we are unable to upload contentlets in the document content type, or any one with the document management workflow assigned

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13607
https://github.com/dotCMS/enterprise-2.x/pull/585

**Comment by bryanboza** [comment]
Not sure if this is related, but i am unable to reproduce because when you try to upload some file to the document content type  and try to save & publish, the process is taking a lot of time and we have a time out that is killing the process and we are not uploading the file

**Comment by bryanboza** [comment]
Fixed, now I am unable to reproduce with the last workflow changes
