### ISSUE TITLE
Unable to set icons to workflow actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13302]
Since we have changes in the UI, now we are unable to set icons to the workflow actions

## Expected Behavior
We should allow set icons to the different actions 
SC: https://screencast.com/t/6Wo4gRIFMGe2

## Current Behavior
We are unable to set icons to the actions, also we are not showing this ones in the list of actions 
SC: https://screencast.com/t/X1uD4Qojov

## Steps to Reproduce (for bugs)
1. Login 
2. Apply the license 
3. Go to workflows and try to create a new action 

## Your Environment
Tested in the last master // MySQL // FF

**Comment by bryanboza** [comment]
If this is on purpose... Then we need delete the icon of the "full delete" action in the starter https://screencast.com/t/uIbXIumX6R

**Comment by john-thomas-dotcms** [comment]
I'm pretty sure this was intentional.

See also https://github.com/dotCMS/core/issues/12617
