### ISSUE TITLE
After creating content it does not redirect

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#13322]
## Expected Behavior
After you create some content it should redirect you to the previous screen and a message "Content Saved" should be shown.

## Current Behavior
After you create some content, does not do anything (no redirect or message is shown).

## Steps to Reproduce (for bugs)
1. Go to Content Tab
2. Create New Content
3. Save/Publish

**Comment by bryanboza** [comment]
Fixed, tested in the last master code // postgres // FF
