### ISSUE TITLE
Create endpoint to get themes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13323]
As a stakeholder I want users to be able to get the themes.

**Comment by fmontes** [comment]
Per @wezell 

We need to use elasticsearch to populate the theme list - which is really a list of folders.  As you cannot get folders from Elasticsearch, use a query like this:

```
+parentpath:\\/application\\/themes\\/* +title:template.vtl host:{host id the user is on}

```
to get a list of theme templates.vtl and then use the folder id to populate the list of folders.  Notice that in the query above, there is no + in front of host.  This means that the results will show the themes of the current site first, but the results won't be limited to the current site (based on user permissions) The reason for this is we need to allow a user access to themes that might be on different sites.  


Also, the theme selector should show the theme folder name then the hostname that the theme is on, e.g.:
```
Quest - demo.dotcms.com
Intranet - demo.dotcms.com
Other theme - www.testing.com
```
![screen shot 2018-01-08 at 8 47 57 am](https://user-images.githubusercontent.com/934364/34673811-94a38338-f451-11e7-91f6-dd7aeef70657.png)

**Comment by wezell** [comment]
Also, no need to use a fancy ES query.  Just do a normal content query and make sure to sort by score.
