### ISSUE TITLE
Implemente theme selector in layout editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13325]
As a user I want to be able to select a theme for the template or layout.

### Possible Solution
The url to get the themes ```/api/v1/themes```

### Mock
1. When click here:
<img width="1161" alt="screen shot 2018-05-21 at 2 32 25 pm" src="https://user-images.githubusercontent.com/751424/40328502-d5e4a4ec-5d03-11e8-986d-fe6d9fc7668f.png">

2. We open this:
<img width="1230" alt="screen shot 2018-05-21 at 2 33 30 pm" src="https://user-images.githubusercontent.com/751424/40328557-024f86be-5d04-11e8-9df2-7fe5539bf3ea.png">

### Components
1. Create a dot-theme-selector component
2. We have a site selector, we can reuse
3. For the listing we can use the data list from primeng it have filter and pagination
4. For the dialog we use the dialog from primeng or we can create a wrapper dialog component where we add the buttons cancel/apply because we'll be using this a lot.

### Acceptance Criteria

1. Match the design
2. Update the toolbar button when the theme is selected
3. Make sure the save of the layout (form value) have the selected theme
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test
8. Add dropdown to select theme
9. Save theme identifier to the layout

**Comment by wezell** [comment]
We need to use elasticsearch to populate the theme list - which is really a list of folders.  As you cannot get folders from Elasticsearch, use a query like this:

```
{
   “query”: {
       “query_string”: {
           “query”: “+parentpath:\\/application\\/themes\\/* +title:template.vtl host:{host id the user is on}”
       }
   },
   “size”: 100
}
```
to get a list of theme templates.vtl and then use the folder id to populate the list of folders.  Notice that in the query above, there is no + in front of host.  This means that the results will show the themes of the current site first, but the results won't be limited to the current site (based on user permissions) The reason for this is we need to allow a user access to themes that might be on different sites.  


Also, the theme selector should show the theme folder name then the hostname that the theme is on, e.g.:

Quest - demo.dotcms.com
Intranet - demo.dotcms.com
Other theme - www.testing.com

**Comment by hmoreras** [comment]
waiting more info to implement themes

**Comment by hmoreras** [comment]
on hold, while endpoints are ready

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14647

**Comment by fmontes** [comment]
<img width="1135" alt="screen shot 2018-06-21 at 6 56 36 am" src="https://user-images.githubusercontent.com/751424/41720454-4fbfb6b0-7520-11e8-952d-a7b97d5df735.png">

<img width="1135" alt="screen shot 2018-06-21 at 6 56 36 am" src="https://user-images.githubusercontent.com/751424/41720488-6caf8a3e-7520-11e8-8f79-f4035007993c.png">

**Comment by hmoreras** [comment]
the side margins of the dialog I will respect the common variable `$dialog-padding` to be consistent.

**Comment by bryanboza** [comment]
Passed, new cards to work on this created.
