### ISSUE TITLE
Content types form re-styling

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13330]
As a stakeholder I want the content types form to be easiest to access.

### Mock
<img width="951" alt="screen shot 2018-01-19 at 8 05 09 am" src="https://user-images.githubusercontent.com/751424/35154335-86db1800-fcef-11e7-86ff-cde1c995fcf0.png">

<img width="430" alt="dialog 1" src="https://user-images.githubusercontent.com/751424/35154203-f8333060-fcee-11e7-9fe8-c4107a4bdaad.png">

### Acceptance Criteria

1. Update content type title according to the mock:
    - Name is now just text
    - Identifier and variable name is shown after the content type is created or in edfitm ode
2. On **create** content type we show the dialog box with the form
    - User should not be able to close the dialog
    - Dialog title: "Create content type"
    - Dialog action: "Create" (disable until the form is valid)
    - Cancel: will return to listing
3. On **edit**, content type we show the dialog box with the form populated
    - User should be able to close the dialog in the x, esc key or clicking outside the dialog
    - Dialog title: "Edit content type"
    - Dialog action: "Update" (disable until form is valid or the model change)
4. If the screen it's not big enough form should scroll in the dialog
5. Match the design
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
8. Unit test

**Comment by john-thomas-dotcms** [comment]
Doc Note: Screen shots for appropriate docs will need to be updated
