### ISSUE TITLE
NPE creating content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13338]
We are unable to create content types

## Expected Behavior
We should be able to create new content types without problems 

## Current Behavior
When you try to create a new content type, we have a NPE and you are unable to create a new one 
Here the logs: 
https://gist.github.com/bryanboza/4144e169590b96af30061f87f9badc9f

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to content types 
3. Try to create a new one 
4. Check the dotcms.log file 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13348

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres // FF
