### ISSUE TITLE
When create/save layout to a page, page it's not updated

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13334]
If you edit a page and make it template a layout and edit the layout, the changes are not reflected on the page content but you can see it in the layout of that page.

## Expected Behavior
When add a layout to a template and edit it, should see those changes in the page content and containers.

## Current Behavior
Changes to an assigned layout to a page doesn't reflect the changes in the content of the page.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Edit a page with a template
2. Go to "Layout"
3. Select edit page in the dialog
4. Do changes in the layout and save
5. Go to the content, see the changes in the layout are not reflected there.

**Comment by freddyucv** [comment]
Fix with this commit:  

https://github.com/dotCMS/core/commit/2cf3c6d99fe58acc60835119b47f8674f5a8da68
