### ISSUE TITLE
Make Relationships case insensitive

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13340]
This find relationship call where a Relationship is named "relationshipName" in the db and you pass in all lowercase `relationshipname` with an empty cache, it comes back null.

Once the relationship cache is loaded, `relationshipname` returns the actual relationships.
```
Relationship rel = FactoryLocator.getRelationshipFactory().byTypeValue(relationshipname);
```

We should force relationship keys to be lowercase on save.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13617
