### ISSUE TITLE
Allow drag and drop steps to reorder in the workflow portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13352]
Since we are able to reorder actions just drag and drop, maybe we need be able to reorder the steps with the same way. 

## Expected Behavior
We need allow reorder steps just drag and drop in the workflow portlet 

## Current Behavior
We allow reorder steps, but this changing the order value in the steps detail window, we need do this with minor clicks as posible. 

<img width="361" alt="steps" src="https://user-images.githubusercontent.com/2641437/34730936-6f018ce4-f526-11e7-97f6-f3a9f2cfb4ff.png">

## Steps to Reproduce (for bugs)
1. Login on backend 
2. Go to workflows portlet 
3. Add a new WF 
4. Add multiple steps 
5. Try to reorder 

## Your Environment
Tested in the last master // FF // PP

**Comment by wezell** [comment]
Please hold on this task until we get the new workflow step .jsp

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13382

**Comment by bryanboza** [comment]
Fixed now this is working better after the last UI changes, but now we have the follow problem.

- [ ]  Need ignore the add Workflow step column in the order
SC: https://screencast.com/t/XB3mWs9LHg3e

**Comment by bryanboza** [comment]
After test again, now we have this cases: 
- In new workflows we are not changing the order filed, but we still allowing move this un-existing column. From my prospective I think we should lock this column as all.

- In the workflow that comes in the starter, we still changing the order when you move this column

SC: https://screencast.com/t/sydv7eiaTT

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13595

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now it works as expected. Also tested with cross browser testing
