### ISSUE TITLE
WorkflowProcessor.setNextStep not respected

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13351]
This stopped working.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/MultipleApproverActionlet.java#L121

**Comment by jgambarios** [comment]
Unable to reproduce with the latest code.

**Comment by bryanboza** [comment]
Tested in the latest master // postgres // FF, and I am unable to reproduce too.... Maybe something related to this issue #13322  because we are not refreshing the actions after save. But right now is fixed.
