### ISSUE TITLE
Blank page shown when a language is edited

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13368]
## Current Behavior

When a language is selected to be edited a blank page is loaded. View attached video.
More log details (taken from JS Console): https://gist.github.com/dsilvam/6e44577d41ad03c1ac73c01234c0f99e
No error found in dotcms.log
![edit_language](https://user-images.githubusercontent.com/8741395/34787669-1485bc32-f606-11e7-9715-b7a49be2d2bb.gif)

## Your Environment

* dotCMS version used: current master (dotCMS 5.x)
* Browser Name and version: Google Chrome
* Operating System and version: MacOSx
* Application Server and version: Tomcat 8.5
* Java Brand and version: JDK 8
* Database and version: postgres
* Application module (if apply): Languages

**Comment by fmontes** [comment]
Mistery fixed.
