### ISSUE TITLE
Use native elasticsearch field types when mapping dotCMS fields to elasticsearch

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13363]
Currently, we convert all dotCMS field types into Strings when we index them into elasticsearch except for the geopoint fields.   What we need to do instead is store our fields nativily in elasticsearch, by either forcing conversion based on DBStorageType or allowing ES to dynamically assign the field type.

Any field that gets converted into a non-string (like an int, float, date, etc) we will need to index the string version of the field by appending `_text` to the field var name to allow legacy customer to easily change their working queries to work with the new mappings

**Comment by wezell** [comment]
we need to maintain the _dotraw mapping

**Comment by nollymar** [comment]
This is an example of how fields will be mapped after upgrading to ES6: https://gist.github.com/nollymar/5745d982108d1ffeba2bc525d51fe5a6

**Comment by DeanGonzalez** [comment]
Documented: 
https://auth.dotcms.com/docs/latest/elasticsearch-examples
https://auth.dotcms.com/docs/latest/search-within-all-content-type-fields-using-catchall
https://auth.dotcms.com/docs/latest/aggregated-site-search (John Michael)
