### ISSUE TITLE
Unable to upgrade with MySQL

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13375]
Currently there's a 500 error when you upgrade from dotcms_2.5.7 or dotcms_3.x to latest master. 
Tried to upgrade directly from 2.5.7 to master: failed.
Tried to upgrade directly from 2.5.7 to 3.x(which worked fine), then from 3.x to master: failed.

I did another test upgrading from dotcms_3.x to master and Postgres and it did work.

## Expected Behavior
You should be able to upgrade without problem to latest master on MySQL.

## Current Behavior
500 error after upgrade.
https://gist.github.com/shaydotcms/f24a422d99e277c58728ff5c0e184353

## Steps to Reproduce (for bugs)
1. Follow standard steps to upgrade directly from dotcms_2.5.7 to master using a real dataset
2. Check the logs and you'll see NPE errors 
3. If you wish, you could try to upgrade from dotcms_2.5.7 to dotcms_3.x. If you try to login you will be able to do so
4. Now follow standard steps to upgrade from dotcms_3.x to master using the same dataset.
5. You will see the error described in the link:
https://gist.github.com/shaydotcms/f24a422d99e277c58728ff5c0e184353

## Your Environment
* dotCMS version used: upgrade from dotcms_2.5.7 to dotcms master branch / commit b5df569bc378a8cd14d2dbf85fbfdc9ab03630b4
* Database and version: MySQL 5.6.35
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by erickgonzalez** [comment]
Tried with starter data from 3.7.1 to the latest master and the upgrade was just fine. Gonna try with client dataset.

**Comment by erickgonzalez** [comment]
With client dataset, the upgrade went smooth. Here is a portion of the dotcms.log, https://gist.github.com/erickgonzalez/b1425ed6e6d623e76e9a04b0452bd6f7 as you can see the 
**Database upgraded to version: 4325**.

**Comment by bryanboza** [comment]
Tested with the client dataset, and the upgrade was success, no errors in the upgrade process, but when you go to the backend I've the same error.
ST: https://gist.github.com/bryanboza/caf0d673854db083e458f65c05565936

_**FYI: Tested with starter site and I am unable to recreate the same problem.**_

**Comment by shaydotcms** [comment]
Passed QA.
I was able to successfully upgrade from 2.5.7 to master branch. No issues logging into the backend.
MySQL 5.6.35 / Mac OS 10.10.5 / Firefox v57.0.4 / Tomcat 8 / Java 8
