### ISSUE TITLE
Unable to expand folders on backend using Safari browser

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13374]
Unable to expand folders on the backend using Safari, it does work ok on Chrome and Firefox.
 
## Expected Behavior
There should not be any issues expanding folders on the backend using Safari browser.

## Current Behavior
There are issues on the backend navigating with Safari browser.

## Steps to Reproduce (for bugs)
1. Login to dotcms using Safari browser(use incognito mode)
2. Navigate to Site->Browser
3. Click the "+" sign to expand a folder, i.e: images, resources, services, etc. This will not work
Error showing in console:
[Error] ReferenceError: Can't find variable: isRightClick
	treeFolderSignRefMouseUp (layout, line 571)
![image](https://user-images.githubusercontent.com/8741846/34800532-d5a59b08-f629-11e7-9f52-523de8d010ed.png)

## Your Environment
* dotCMS version used: master branch with starter data
* Database and version: MySQL 5.6.35
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Safari 8.0.8
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by erickgonzalez** [comment]
Unable to reproduce with the latest master.

**Comment by wezell** [comment]
This is on an old version of safari
