### ISSUE TITLE
Detect changes on content field values to determine showing warning

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13372]
For content with relationships when you are going to add a new relationships, because you are redirected to another screen, you are warned about potencial missing changes. 

This used to be shown based on whether there were changes or not in the field values, but in a very inefficient way, even leading to server freezes ([see here](https://github.com/dotCMS/core/issues/13206))

We need to make this in a more efficient way (maybe a flag set to true on the onChange on any field?).

**Comment by wezell** [comment]
dupe #14472
