### ISSUE TITLE
Unable to add workflow actions after upgrade from 3.x version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13379]
We have problems after upgrade instances from 3.x version to the last master, this because we are unable to add workflow actions into the steps.

## Expected Behavior
We need be able to work with the new workflow login without problems 

## Current Behavior
When you try to add a new action we have this database exception: 
https://gist.github.com/bryanboza/c2309a83599dce3623dc652294fdbd94

## Steps to Reproduce (for bugs)
1. Start a dotcms 3.x instance 
2. Create a new WF with steps and actions  
3. Upgrade to the last master 
4. Start and reindex
5. Try to add a new action to some step

## Your Environment
Tested in the last master // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13385

**Comment by bryanboza** [comment]
Fixed, tested upgrading from 3.x version to the last master code // MySQL
