### ISSUE TITLE
Edit page does not respect hosts selected

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13389]
As a user, I want to be able to edit any page from any host in my DotCMS instance.

## Context

When you open a page in the browser to preview and edit, it does not respect the host - meaning if you have a multisite implemented, it will only show you pages from the default site.

## Expected Behavior
User should be able to edit any page from the current site selected.

## Current Behavior
User only can edit pages in the default site.

## Possible Solution
Backend: endpoints should return the pages the FE is asking for the current site selected, BE already know which site is selected by the logged user.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Create a new site
2. Change the current site to your new site.
3. Add a page ```/about-us/index``` (with different template and content as the one in the default site)
4. Try to edit that page in the new site
5. It's loading the page from the default site.

## Screencast
![hosts-no-respected](https://user-images.githubusercontent.com/934364/34884851-065a56a4-f78c-11e7-8997-5ef7625aa31c.gif)

## Acceptance Criteria

1. Should load the page of the current site (from site-browser)
2. If we are in a edit page and we change the site in the toolbar we should try to reload the same page in edit mode:
    - If the page doesn't exist catch the 404 and redirect to site-browser
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by freddyucv** [comment]
It is working for me
![it_is_working](https://user-images.githubusercontent.com/10408015/37974332-e5b56996-3199-11e8-844e-e4c611a6de74.gif)

**Comment by freddyucv** [comment]
What should we do in this case?

![what_do_here](https://user-images.githubusercontent.com/10408015/37974394-137c67bc-319a-11e8-94aa-81faa8fd2550.gif)

we should reload de page with the new site or we should back to the site-browser?, in this case we have a page with the same url in both site but i'll not  happend every time

**Comment by bryanboza** [comment]
Fixed, now this is working and if you are editing any page and change the site, the sytem shows an Opss error and redirect to the site browser of the new site

**Comment by bryanboza** [comment]
New improvements added here #14075...
