### ISSUE TITLE
PPHandler not seeing commited change in previous Handler

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13381]
Related to https://github.com/dotCMS/core/issues/13373

To reproduce, the FK removal done in the Upgrade task in the task mentioned above needs to be removed. 

ContentWorkflowHandler is not seeing a commit that should have been made by ContentHandler even though they are in the same transaction. 

This can be reproduced on MSSQL.

**Comment by jtesser** [comment]
So @dsilvam is the plan to merge the FK removal in 4 then address better in 5?

**Comment by dsilvam** [comment]
@jtesser exactly, the FK removal is already merged

**Comment by dsilvam** [comment]
Note to QA: add the FK back by executing:
`alter table workflow_task add constraint FK_workflow_task_asset foreign key (webasset) references identifier(id);`
