### ISSUE TITLE
Edit button on any content is always redirecting to same content

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13386]
When you hit edit button to change the content of a page, it always brings up the same content ("The Gas Price Rollercoaster"), instead of the actual content that needs to be edited.

## Expected Behavior
Edit button should edit the correct content. 

## Current Behavior
When you hit edit button it always brings up the same content ("The Gas Price Rollercoaster")

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Site> Browser> about-us
3. Right click over "index" to Open(Preview)
4. Click edit button on any of the contents available
5. You will see "The Gas Price Rollercoaster" content is always showing up, independently of the content you want to edit.

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.3.5
* Operating System and version: Mac OS 10.10.5 
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by fmontes** [comment]
This was fix long time ago.
