### ISSUE TITLE
Unable to send mails from workflows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13390]
We have an error when you have any action that needs send an email from a workflow action, this because we are unable to find the **"static/workflow/workflow_email_template.html"**

## Expected Behavior
We should be able to send email notifications without problems 

## Current Behavior
We are having an error, when you try to send the notification and this stop the process 

## Steps to Reproduce (for bugs)
1. Login 
2. Go to the workflows portlet 
3. Create a new workflow
4. Add a new step and add a new action, this shoud have the "Notify Assignee" sub-action
5. Create a new content type and set this workflow 
6. Add a new piece of content and execute the workflow

## Your Environment
Tested in the last master code // MySQL  // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13484

**Comment by bryanboza** [comment]
Fixed, now we are able to notify users without problems, we still having the error #12945 but is reported in the separated issue...

**Comment by wezell** [comment]
This changes the file used by the default workflow email that is sent by velocity from `static/workflow/workflow_email_template.html` to `static/workflow/workflow_email_template.vtl`
