### ISSUE TITLE
Create Copy Contentlet Workflow Actionlet

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13395]
Create a new Copy Contentlet Workflow Actionlet.

## Expected Behavior
Creates a Copy of the current contentlet

## Current Behavior
Do not exists

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13415

**Comment by bryanboza** [comment]
We have an error when you use this action in a page assets content type, this is the error: https://gist.github.com/bryanboza/c77cfe997473fab8170a6cf4d71a1ab7

We need rename the page, as we do in FileAssets, because we are unable to add pages with the same URL.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13524

**Comment by bryanboza** [comment]
The same problem with the document content type: https://gist.github.com/bryanboza/76dd3aba885003dd9589b565ccc192b5

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13533

**Comment by bryanboza** [comment]
Still having the same issue... This happens when the WF have just one step 
Here the WF: https://screencast.com/t/6oSTzFDau

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13556

**Comment by bryanboza** [comment]
This action is allowing create duplicated keys in language variables 
https://www.screencast.com/t/EEHQIeAS

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13585

**Comment by bryanboza** [comment]
Fixed, now this works as expected, have a different behavior when you enable the requires checkout... After remove this functionality we need retest
