### ISSUE TITLE
Rendered contentlet in container endpoint not returning correctly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13399]
If you edit the container HTML for certain content type the response for the contentlet of that content types remains the same.

### Endpoint:
http://localhost:3000/api/v1/containers/56bd55ea-b04b-480d-9e37-5d6f9217dcc3/uuid/LEGACY_RELATION_TYPE/content/5aef0c62-b7d6-4805-9e7c-77a67f4822f3

**Comment by wezell** [comment]
fixed in #13425
