### ISSUE TITLE
We need a 404 cache for WorkflowAPI.findSchemesForStruct and WorkflowAPI.findStepsByContentle

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13407]
I was seeing slowness in the Content Search screen and took a thread dump:

https://gist.github.com/wezell/fa306dd66228d2be44f5e530781fc373#file-threaddump-dmp-L1112

Both the WorkflowAPI.findSchemesForStruct and WorkflowAPI.findStepsByContentlet need to cache the db result if there is a empty return to prevent tons of database hits.

You can see here that we are not caching the steps if the incoming list is empty:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowCacheImpl.java#L210-L211

**Comment by wezell** [comment]
As an example:
https://github.com/dotCMS/core/compare/issue-13407-404-cache-for-workflow?expand=1

**Comment by jgambarios** [comment]
We need to create an integration test for this change.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/14026
