### ISSUE TITLE
Unable to push entire site

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13419]
System is throwing an error when you copy an entire site and try to push it. I successfully pushed a single file but failed with entire site.

## Expected Behavior
System should be able to push entire site.

## Current Behavior
System is throwing an error when you copy an entire site and try to push it.

## Steps to Reproduce (for bugs)
1. Set up a push publish environment in the sender and receiver server
2. In the sender, navigate to System>Sites. Hit Add Site button> Copy an existing site> Next
3. Choose demo.dotcms.com and hit next
4. Type in host name and hit Save/Activate
5. Once it's been create, do right click over the new site you've just created and Push Publish
6. Check the logs for the error
https://gist.github.com/shaydotcms/855a5a1e826a4c40874c1b85ce4af2bc
7. Publishing Queue portlet is showing the following:
![image](https://user-images.githubusercontent.com/8741846/35063029-7f56f4a6-fb8b-11e7-9083-c51a15515d02.png)

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6 
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
Found this issue when working on this fix: https://github.com/dotCMS/core/issues/13457

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/13458

**Comment by shaydotcms** [comment]
Passed QA. I was able to push entire site using starter data and upgrade
Mac OS 10.10 / Postgres 9.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
