### ISSUE TITLE
TikaUtils doesn't respect Categories or Tags

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#13429]
when we made the change to catgeories and tags around 3.5 some functionality that use to work in TikaUtils was lost.  Most clients do not use it but some do.

**Comment by jtesser** [comment]
@jgambarios @dsilvam @wezell if we can get this merged would help moving forward.  Make it work as it did in 2.5 or at least closer.  Still need an ES Mapping depending on how you use it 

I actually think at some point in code we can solve this with dynamic analyzers

**Comment by bryanboza** [comment]
Fixed, this was tested with the client plugin...

**Comment by wezell** [comment]
Please retest after we merge branch release-nocode-alpha

**Comment by bryanboza** [comment]
Fixed, tested in the last release-4.3.0 and still working normally...

**Comment by wezell** [comment]
I am not sure this code is right or is what was ever done before.   Was this implemented for Boar's Head site search thingy?
