### ISSUE TITLE
New workflow portlet enhancements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13420]
Here a list of some problems that we have in the new workflow portlet 

- [ ] We save the action after type the name, after this we are unable to delete
_The delete button isn't working after you type the action name. If you click this button we need delete the action and bring back to the step list._
SC: https://screencast.com/t/yrgApRCjK

- [ ] Need styling help we you have multiple steps 
SC: https://screencast.com/t/orBUA8lKF5r4

- [x] The delete step button looks like disabled (it's ok - WE)
SC: https://screencast.com/t/qLS5a5oubOi

- [x] We need a list of global actions in order to reuse actions  (no, we are doing it like this - WE)

- [x] We need delete the action if you cancel before save the action  (it is fine as is - WE)
SC: https://screencast.com/t/SgVv4tscrrgm

- [x] We are creating a copy of the action  if you try to move to a different step
_Maybe we need just move, the global list is in case of you need use the same action in a different step (this is expected - WE)
SC: https://screencast.com/t/Go5MpxEEO

- [ ] Need styling help in case of you have a lot of actions in the same step
SC: https://screencast.com/t/1FGQBUo4AFyx

- [ ] Need set the Max length limit in the action name 
SC: https://screencast.com/t/JfLtOJBrJ

- [ ] Need styling help in case you have multiple workflows 
SC: https://screencast.com/t/46ogyUyR

- [ ] Unable to delete steps from the iPad resolution 
SC: https://drive.google.com/file/d/1gSuJrIrN4gX2KiP5lFyxSNSoqF5Wdtwf/view?usp=sharing

- [ ] Need ignore the add Workflow step column in the order 
SC: https://screencast.com/t/XB3mWs9LHg3e

**Comment by wezell** [comment]
The ones I checked above are how it is supposed to work.
