### ISSUE TITLE
Some Functionality doesn't work in Platform

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#13430]
we have some functionality that doesn't work with a platform license.  The reason is because we return an int[] for allowed versions in all classes that extend the ParentProxy.  

Then the LiceneManager checks if they match.  Our level are hierarchal and while maybe at some point we thought Pro would do something Prime doesn't there is no need for this IMO 

So the SOLUTION is in the LiceneManager we should just check if the level >= rather then equal to

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/577

**Comment by bryanboza** [comment]
Fixed, simple change here, just tested everything works normally with the platform license
