### ISSUE TITLE
Response time problems executing workflows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13445]
We have problems with the response time when you execute some workflow, this because the system shows the saving modal window, but this takes a lot of time 

## Expected Behavior
We should be able to save contents and execute workflows without problems just in seconds 

## Current Behavior
We shows the saving modal window and this still here a lot of time, At the end is closed by the ajax timeout 
SC: https://github.com/dotCMS/core/issues/13196

## Steps to Reproduce (for bugs)
1. Login 
2. Go to Workflows portlet and create a new one 
3. Create a new content type and use the created WF 
4. Add a piece of content and try to execute the WF

## Your Environment
Tested in the last master code // Postgres // FF

**Comment by wezell** [comment]
This happens when there is a js error or content fails to save.
