### ISSUE TITLE
Several NPEs when copying Demo Site

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#13457]
System is throwing an error when you copy an entire site 

## Expected Behavior

System should be able to copy entire site.

## Current Behavior

System is throwing an several errors when you copy an entire site.

## Steps to Reproduce (for bugs)

1. Navigate to System>Sites. Hit Add Site button> Copy an existing site> Next
2. Choose demo.dotcms.com and hit next
3. Type in host name and hit Save/Activate

Log errors: https://gist.github.com/oarrietadotcms/b38aa15310f67dde29f45d2e1605b40e

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6 
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/13465

**Comment by shaydotcms** [comment]
Passed QA.
No NPEs when copying demo site.
Ubuntu 14.04.1 / Postgres 9.6 / v57.0.4 / Tomcat 8 / Java 8
