### ISSUE TITLE
Make Workflow tasks to work by language

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13469]
The **workflow_task** table needs to use the language id as part of the table key in order to allow to execute steps/actions not just by identifier but also by language.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13509

**Comment by bryanboza** [comment]
Fixed, tested in the last master code, and upgrading from 2.5 and in both cases works as expected....

**Comment by bryanboza** [comment]
After test the task portlet we have problems here, this because after you assign some content to a user in a specific language and after that you create a new version of this content, we show the assigned content in spanish 

Here the SC: https://screencast.com/t/czpWtoCFk

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13569

**Comment by bryanboza** [comment]
After test this again, now we have one line by language, but we need add the flag to this portlet, this because don't make sense open the content to see what language is it. 
SC: https://content.screencast.com/users/bryan--azuy/folders/Snagit/media/0bb42381-2f01-4908-a991-5654e4db6b62/2018-02-06_16-14-34.png

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13589

**Comment by bryanboza** [comment]
We are unable to show the flags in the task portlet when the language is a generic one (don't have the country code)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13601

**Comment by bryanboza** [comment]
Fixed, tested in with the last master code // Postgres // FF. Also tested in a upgrade instance and works as expected.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13681

**Comment by bryanboza** [comment]
Unable to upgrade from previous versions to master 
Here the log: https://gist.github.com/bryanboza/953495a0d74bbed87fb5359da762dbb6

Tested with a starter site from 3.7 to master

**Comment by bryanboza** [comment]
Fixed, tested after upgrade and now it is working as expected
