### ISSUE TITLE
Unable to add fields to content types

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13471]
After the last changes in the angular content types portlet, now we have problems adding fields to content types 

## Expected Behavior
We need be able to create content types, add fields and content without problems 

## Current Behavior
We have an error doing the PUT 
SC: https://screencast.com/t/GOj0HYocR

## Steps to Reproduce (for bugs)
1. Login as admin
2. From the content types portlet try to create a new one
3. Add any layout and add some field to this layout 
4. Try to save it 

## Your Environment
Tested in the last master code // postgres // FF

**Comment by fmontes** [comment]
Fixed in another issue.
