### ISSUE TITLE
If an instance has Platform License, the LDAP validation is not working

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#13478]
If you have a dotCMS instance with Platform License, and you use LDAP for authentication. The code is not authorizing the LDAP validation because the Platform license level is not included in these lines https://github.com/dotCMS/enterprise-2.x/blob/4.2.2/src/main/java/com/dotcms/enterprise/AuthPipeProxy.java#L61-L64

when these methods are called https://github.com/dotCMS/enterprise-2.x/blob/4.2.2/src/main/java/com/dotcms/enterprise/AuthPipeProxy.java#L11-L20
## Expected Behavior
Platform License should be allowed to do LDAP authentications

## Current Behavior
If you try to login using LDAP, the authentication fails

## Possible Solution
Add the PLATFORM licence level on the getStaticAllowedVersions method
## Steps to Reproduce (for bugs)

1. Configure a DotCMS instance with LDAP
2. Add a PlatForm license to the instance
3. try to login to the backend

## Context

This ticket was reported by a client here https://dotcms.zendesk.com/agent/tickets/95090
## Your Environment

* dotCMS version used: 4.2.X

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/enterprise-2.x/pull/580

**Comment by bryanboza** [comment]
Fixed, tested on the release-4.3.0 code // MSSQL // Windows, now we are able to use the ldap users using the platform license

Here the backend: https://screencast.com/t/bA3PUe8tN5
Here the active directory config: https://screencast.com/t/QZ70JMrWg
