### ISSUE TITLE
Vanity URL Forward broken for cross-site request

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#13485]
When attempting to add a global regex vanity URL that rewrite the request to a specific Site, the interface and rewrite is broken in a couple ways. This uses the "200 - Forward" Action type, which should perform an internal URL rewrite

First, when attempting to select the URL in the "Forward To:" the Site is stripped from the destination after selecting a specific Site's URL in the "click here to browse" interface. (ie, selecting `mysite.dotcms.com/products/some-page` is altered to `/products/some-page`)

Secondly, when attempting to manually specify the destination site in the "Forward To:" the request is then handled via a 302 Redirect rather than a rewrite. The two following syntaxes for the "Forward To:" were tested with identical behaviour: `//mysite.dotcms.com/products/$1` and `http://mysite.dotcms.com/products/$1`.

![image](https://user-images.githubusercontent.com/3977301/35289261-a2c33046-001b-11e8-95ac-672d6efe6373.png)

```
⚡ ~ ► curl -vL https://demo.dotcms.com/test/consumer-discretionary-from-my-site
*   Trying 54.165.137.45...
* TCP_NODELAY set
* Connected to demo.dotcms.com (54.165.137.45) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=demo.dotcms.com
*  start date: Jan 12 04:15:42 2018 GMT
*  expire date: Apr 12 04:15:42 2018 GMT
*  subjectAltName: host "demo.dotcms.com" matched cert's "demo.dotcms.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /test/consumer-discretionary-from-my-site HTTP/1.1
> Host: demo.dotcms.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Tue, 23 Jan 2018 16:52:51 GMT
< Content-Length: 0
< Connection: keep-alive
< Server: Apache-Coyote/1.1
< Location: http://mysite.dotcms.com/products/consumer-discretionary-from-my-site
<
* Connection #0 to host demo.dotcms.com left intact
* Issue another request to this URL: 'http://mysite.dotcms.com/products/consumer-discretionary-from-my-site'
* Could not resolve host: mysite.dotcms.com
* Closing connection 1
curl: (6) Could not resolve host: mysite.dotcms.com
```

**Comment by wezell** [comment]
I might be missing something but I don't think we should support anything but full redirects to other sites.  If we were to implement a 200 "forward" to other sites, it would be a proxy - we actually have unmerged code that does this, but it is not in the core product.

**Comment by wezell** [comment]
https://github.com/dotCMS/core/commit/eb4b8985bc1080a760ddbe854e7668652006f6e4

**Comment by jdotcms** [comment]
The commit looks great

**Comment by joseorsini** [comment]
this new implementation may help fixing this issue related to LinkChecker https://github.com/dotCMS/core/issues/13310
