### ISSUE TITLE
Remove Tika jar from Tomcat classpath

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13482]
We need to remove the tika jar dependency we have in our project and added it as a OSGI plugin.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13605

**Comment by bryanboza** [comment]
After this changes we have some problems trying to get the metadata from the XML file, also when the file have 0 bytes, this is failing...

New related issue here #13874

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13981
https://github.com/dotCMS/enterprise-2.x/pull/602

Tika plugin:
https://github.com/dotCMS/plugin-com.dotcms.tika

**Comment by bryanboza** [comment]
Fixed, now the related cards was fixed and this change works as expected
