### ISSUE TITLE
We need to update the host picker when you archive a site

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13483]
1. Add a site
2. change to it
3. delete it

![screen shot 2018-01-23 at 9 41 44 am](https://user-images.githubusercontent.com/934364/35281739-b40878e2-0021-11e8-8402-4f2ca34c9001.png)

### Posible fix:
1. Here is the [site-selector.component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/site-selector/site-selector.component.ts)
2. Check if the websocket event when a site it's remove it is working.

### Acceptance Criteria
1. Add unit tests in the site selector component
2. When a site gets archived it and is selected we should:
    - Remove the site from the list
    - Select the default site on the list

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13997

**Comment by bryanboza** [comment]
We need the fix #14020 to test

**Comment by bryanboza** [comment]
Right now we are not capturing the webSocket event and we have the follow behavior: 

- [ ] We are not refreshing the dotSiteSelector when you add a new site 

- [ ] We are not refreshing the dotSiteSelector when you archive some site 

- [ ] Neither when you delete some site

**Comment by fmontes** [comment]
There's an issue for that: https://github.com/dotCMS/core/issues/14030

**Comment by fmontes** [comment]
@jgambarios told me they were working on this error on this issue: https://github.com/dotCMS/core/issues/14161

**Comment by bryanboza** [comment]
Fixed, that's working fine
