### ISSUE TITLE
Inconsistent Content Indexing

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#13508]
## Expected Behavior

When there are no content changes, each ES reindex should result in the same number of live and working counts.

## Current Behavior

![image](https://user-images.githubusercontent.com/3208956/35451140-cebe31fa-0287-11e8-94f2-0fab36add51a.png)
As you can see from the above screenshot, index counts are varying wildly even though no content has changed.

## Steps to Reproduce (for bugs)

1.  Download nightly build - https://dotcms.com/contentAsset/raw-data/27fb0082-dd9d-4d13-b276-8ba65568eff7/zip/dotcms-2018-01-25_22-13.zip
2.  Unzip nightly build
3.  Start dotcms
4.  Reindex content multiple times and compare index counts and sizes

## Your Environment

* dotCMS version used: 20180125 nightly build
* Browser Name and version: N/A
* Operating System and version: OSX and Alpine linux (via docker)
* Application Server and version: embedded tomcat 8.5.24
* Java Brand and version: Oracle 1.8.0_141 and OpenJDK 1.8.0_151
* Database and version: Postgres 9.6.6
* Application module (if apply): N/A

**Comment by brentgriffin** [comment]
BTW - tested on demo.dotcms.com which is running 4.2.2 and demo did NOT demonstrate this problem

**Comment by brentgriffin** [comment]
Seems like this may be DB specific - 

FWIW - after interacting with Will and his inability to recreate this on his system which is using MariaDB, I attempted to create on MySQL 5.7.20 and was not able to recreate - I reindexed 5 times and consistently got the same counts (880 working and 872 live)

So, could reproduce in Postgres 9.6.6, 10.1, and 9.5.10 
Could NOT reproduce in MySQL 5.7.20

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/13604
