### ISSUE TITLE
Missing text in popup when deleting user in another languages

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13507]
When you attempt to delete a user, there's some missing text ("This operation cannot be undone") when the popup is showing in a different language.

English
![image](https://user-images.githubusercontent.com/8741846/35412133-d1d9a3d0-01e0-11e8-9205-8d878231917f.png)

Spanish
![image](https://user-images.githubusercontent.com/8741846/35412027-7ab19cfc-01e0-11e8-80a5-6ce9c0b0274e.png)

Deutsch
![image](https://user-images.githubusercontent.com/8741846/35412035-82848a2a-01e0-11e8-943a-1a7e9c237048.png)

## Expected Behavior
Translation should be the same for all languages.

## Current Behavior
Text "This operation cannot be undone" is missing for different languages.

## Possible Solution
Text "This operation cannot be undone" should not show up even when language is English or it should be translated to all other languages.

## Steps to Reproduce (for bugs)
1. Startup up dotcms instance and login in to backend using English language
2. Navigate to Users portlet. Pick a user from the list or create a new user
3. On the tab User Details, click Delete button 
4. Select a user to replace the current user you are about to delete
5. Hit Delete
6. You will get the message "Are you sure you want to delete this user?  (This operation cannot be undone)"
7. Hit Cancel button
8. Shutdown dotcms instance then start up again. This is to make sure you are switch to the correct language when you login to the backend.
9. Login using another language, i.e: Spanish, Deutsch, etc
10. Follow steps 2 - 6
11. You will see text "This operation cannot be undone" is not showing in this language

## Your Environment
* dotCMS version used: dotcms master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v58.0
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
known issue
