### ISSUE TITLE
Delete Workflow Schema

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13521]
A user should be able to delete a workflow scheme that is no longer being used
- The system workflow should never be deleted or delete-able
- Content types that use the workflow scheme being deleted (basically any content types with 0 workflows) will be automatically associated with the system workflow
- Audit/security log the deletion of the workflow
  - workflow_steps
  - workflow_tasks 
  - workflow_comments
  - workflow_history
  - workflow_actions
  - workflow_actionletclasses
  - workflow_actionclasses_properties

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13936

**Comment by bryanboza** [comment]
We need add the audit/security part in our logs

**Comment by oswaldogallango** [comment]
this P.R includes the security logs https://github.com/dotCMS/core/pull/14001

**Comment by bryanboza** [comment]
Fixed, now we have the log section working as expected, and we are able to delete schemes without problems
