### ISSUE TITLE
Delete button in the edit workflow actions window does not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13523]
We have a JS console error when you click on this button, and this isn't working at all

## Expected Behavior
We should delete the action when you click on it 

## Current Behavior
We have a JS error and the button does not work 
<img width="847" alt="img1" src="https://user-images.githubusercontent.com/2641437/35579497-6852f306-05ac-11e8-99d7-787170f0f27a.png">

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to workflows portlet 
3. Edit some workflow 
4. Try to add a new action 
5 . After add click in the delete button 

## Your Environment
Tested in the last master // Postgres // FF

**Comment by jgambarios** [comment]
@wezell now that we have those deletes

![Delete 1](https://content.screencast.com/users/jgambarios/folders/Snagit/media/0612eda9-4d18-47d7-97b0-7b349eea5ea6/2018-02-28_12-22-13.png)

Do you think that we need this one?:
![Delete 2](https://content.screencast.com/users/jgambarios/folders/Snagit/media/174314e2-5cc3-427f-a0c9-bd9b17a1a7eb/2018-02-28_12-21-34.png)

If the answer is yes, should I remove completely the Action?, meaning, from all the steps where the action is used and the action itself? or can we remove that delete button?

**Comment by wezell** [comment]
We need that button and the way it should work is like this:
1. if the action is on more than one step, it deletes the relationship from the action to the step with no confirmation
2. if the action is only on 1 step, then the user gets a confirmation that they want to delete the action and and if they say yes, you delete the action and the action_step relation altogether.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13914

**Comment by bryanboza** [comment]
Fixed, now we don't have this button editing the step. Tested in the last master code // postgres // FF
