### ISSUE TITLE
Hide template layouts from listings

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13522]
Template layouts are being displayed in a few listings in the UI. 
There's no current way to distinguish them from global templates. 
Let's use the "show_on_menu" db column in the templates table (currently unused) for this purpose and filter accordingly

**Comment by fmontes** [comment]
We have identified two places:

1. Template listing (the table)
2. In page properties template field (dropdown)

**Comment by DeanGonzalez** [comment]
Passed QA - Layouts do not appear on on Template listing or on template select for new pages.  New layouts saved as templates DO appear properly.
