### ISSUE TITLE
Replace "facets" usage in queries in VTLs on starter site

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13538]

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14065/files
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/609

**Comment by nollymar** [comment]
Additionally, these files were modified in starter:
* /application/vtl/pages/site-search/site-search.vtl
* /application/vtl/widgets/news/news-location-listing.vtl
* /application/vtl/pages/news/news-detail-right-column.vtl

**Comment by dsilvam** [comment]
Note to QA: Make sure that:
* sitesearch works and the search criteria is highlighted 
* this page works correctly https://demo.dotcms.com/demos/content-geolocation
