### ISSUE TITLE
Unable to see the content types permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13531]
We have an error when you try to see the permissions tab of any content type

## Expected Behavior
We should be able to see, and modify permissions 

## Current Behavior
We can't see the permissions 
SC: https://screencast.com/t/q0EZt6M3

## Steps to Reproduce (for bugs)
1. Login  
2. Go to content types 
3. Select some content type
4. Try to modify the permissions 

## Your Environment
Tested in the last master // postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/13557

**Comment by bryanboza** [comment]
Still having problems on FF: https://www.screencast.com/t/i2v22Byc

**Comment by fmontes** [comment]
Will be fixed here: https://github.com/dotCMS/core/issues/13774

**Comment by bryanboza** [comment]
Fixed, now we are able to see this tab from the new content type portlet
