### ISSUE TITLE
Add same contentlet to different instances of the same container in a page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13542]
As a user I want to be able to add same contentlet to different instances of the same container in a page.

## Expected Behavior
Template have the same container more that once, user should be able to add the same contentlet to both of those containers.

## Current Behavior
If user try to add a second contentlet to the same intance of a container in a page, backend "save" endpoint trows error 400.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a page template
2. Add a second instance of an existing container
3. Add the same contentlet to both instances of that container
4. It breaks

**Comment by wezell** [comment]
done
