### ISSUE TITLE
Prevent to D&D a second contentlet to the same container

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13541]
We can't have the same contentlet twice in the same **container**, you can have it in the same page BUT NOT in the same container.

## Expected Behavior
If you try to D&D a contentlet in a container where the same contentlet exist we should prevent it.

## Current Behavior
User can D&D any contentlet, app is only checking by type and max-length

## Possible Solution
We need to update [this function](https://github.com/dotCMS/core-web/blob/1f840f6301b15a5d74e960d950e711cea2b8718f/src/app/portlets/dot-edit-content/services/html/iframe-edit-mode.js.ts#L37).

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a page
2. Add the same contentlet twice in different containers
3. Drag and drop one of the contentlet to the container where the other (same) is.
4. Is drops and it shouldn't

### Acceptance Criteria

1. Try to move this code to a .ts file and import it then use .toString()
2. Unit tests the functions
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by freddyucv** [comment]
We already check this when a content is added into the container here (maybe this code could help):

https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-content/services/dot-edit-content-html.service.ts#L164

**Comment by luisrojascr** [comment]
I added some initial code.

Check the branch [](https://github.com/dotCMS/core-web/tree/issue-13541-prevent-DnD-a-second-contentlet-in-the-same-container)
