### ISSUE TITLE
Edit pages with advance template

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13548]
As a expert user I want to be able to edit the template code within the edit content page

### Backend
We need a flag from the renderHTML endpoint that tell us:
1. Page have an advanced template
2. User have permission to edit that template

```
{
    template: {
        drawed: boolean,
        canEdit: boolean
    }
}
```

### Acceptance Criteria

1. Make sure that when you open a template edited by the new edit mode with the old the template designer it works, right now it showing [TemplateLayout json data](https://www.screencast.com/t/B3xiXmNCIS), we need here set the drawed porp to true when a template is create by the edit-page.
2. With the both BE flag in true we show the "Layout" button with the text: "Template" and the icon of "code"
3. If the flag 1 is true and 2 is false we show the button with the same text and icon but disabled
4. If button is enabled and the user click it we should load the JSP for edit that template (we might need some other things from the backend to do this)
5. Match the design
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
8. Unit test

**Comment by fmontes** [comment]
@freddyucv started this and all the BE work is done:

https://github.com/dotCMS/core-web/tree/issue-13548-Edit-pages-with-advance-template
https://github.com/dotCMS/core/tree/issue-13548-Edit-pages-with-advance-template

**Comment by fmontes** [comment]
@hmoreras report a couple of bugs that will be fix when we merge: https://github.com/dotCMS/core-web/pull/555/

**Comment by wezell** [comment]
When you edit an advanced template and return to the page, the content is not being updated.
