### ISSUE TITLE
Push Publish. Unable push entire site

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13552]
System is throwing an error when you copy an entire site and try to push it. I successfully pushed a single file but failed with entire site.

## Expected Behavior
System should be able to push entire site.

## Current Behavior
System is throwing an error when you copy an entire site and try to push it.

## Possible Solution
1. Set up a push publish environment in the sender and receiver server
2. In the sender, navigate to System>Sites. Hit Add Site button> Copy an existing site> Next
3. Choose demo.dotcms.com and hit next
4. Type in host name and hit Save/Activate
5. Once it's been create, do right click over the new site you've just created and Push Publish
6. Check the logs for the error
https://gist.github.com/shaydotcms/32de395b09a592127bdb335739b110ec

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by acurionedotcms** [comment]
The error was being caused by problems handling some specific Workflows.
These errors have been fixed already in the latest enterprise version, with PR:  https://github.com/dotCMS/enterprise-2.x/pull/586

**Comment by acurionedotcms** [comment]
Cannot be tested until https://github.com/dotCMS/core/issues/13684 gets fixed.

**Comment by shaydotcms** [comment]
Passed QA.
Successfully pushed entire site 
Tested on master branch 
Mac OS 10.10 / Postgres 9.6.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8.6
