### ISSUE TITLE
Unable to upload files via webdav using finder 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13553]
We have an error uploading files using finder to connect via webdav this because we are having the files with 0 length exception. 

## Expected Behavior
We should be able to upload files via webdav with any of the supported clients 

## Current Behavior
We are unable to upload the file because have the follow exception, and this with any file
ST: https://gist.github.com/bryanboza/3e14dfc217405994eb4a5abf59e22e20

**FYI: Tested with cyber duck and works fine** \

## Steps to Reproduce (for bugs)
1. Connect as admin via finder using this URL: http://localhost:8080/webdav/live/1
2. Go to any folder 
3. Try to upload some file 
4. Check the dotcms.log file 

## Your Environment
Tested on master // postgres // FF

**Comment by wezell** [comment]
I believe this is resolved

**Comment by bryanboza** [comment]
Now this specific error has been fixed, New error with the same case reported here: #13824
