### ISSUE TITLE
UI to handle permission for edit page, layout and templates

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13554]
## User can have permission to:
1. Page (and hence to the layout)
2. Page and template

### Page
User can edit the page and the layout

#### Edit layout from button
1. Don't show the template/layout selector dialog
2. If the page have a layout all good we just let the user edit it
3. If the page have a template we create a assign a layout to the page if the user update it

#### Edit layout by url
1. Don't show the template/layout selector dialog
2. If the page have a layout all good we just let the user edit it
3. If the page have a template we create a assign a layout to the page if the user update it

### Page and template
User can edit the page, layout and template

#### Edit layout from button
1. Show the template/layout selector dialog
2. Everything keeps the same as it is right now

#### Edit layout by url
1. Show the template/layout selector dialog
2. Everything keeps the same as it is right now

### To a page
1. It won't show in the site browser (already happen)
2. If try to edit the page by url we show a dialog "You don't have permission" and when accept redirect to Site Browser or first portlet

### To a template or layout
1. It won't show in the template listing (already happen)
2. If try to edit the template or layoutby url we show a dialog "You don't have permission" and when accept redirect to Site Browser or first portlet

**Comment by wezell** [comment]
We need to test the cases here (except for edit template permission):

https://docs.google.com/spreadsheets/d/1YRwB3WX9JNizXZimQ6yYHL-2LmYPITURqcJCyInEWEs/edit#gid=1705859077

**Comment by wezell** [comment]
Templates are not going to be editable from the page now - only layouts.
