### ISSUE TITLE
Update container/contentlet endpoint to return widget and forms correctly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13550]
As a stakeholder I want the container/contentlet to also return correctly html for Widgets and FORM  

## Expected Behavior
If I hit the endpoint with a widget or form identifier it should return correctly the rendered HTML for those assets.

this is the end point:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java#L149

## Current Behavior
If I hit the endpoint with a widget or form identifier some cases just return partial HTML or nothing

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Goes to edit a page
2. Add or D&D a widget or form
3. See the result.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13570

**Comment by fmontes** [comment]
1. Is not returning correctle the HTML for forms
2. https://github.com/dotCMS/core/issues/13577
