### ISSUE TITLE
Handle another user locking a page in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13567]
### Acceptance Criteria
1. If the page is locked by another user and the current user can steal the lock:
    - Page should load in preview
    - Paint the switch to a "warning" color
    - If the user try to steal the lock (by clicking in edit button or the switch), show a confirmation dialog
2. If the page is locked by another user and the current user can't steal the lock:
    - Show a message that reads: "Page is locked by XXX"
    - Make the switch disabled
    - Disable the EDIT option
    - If clicks on the switch blink the lock message

**Comment by freddyucv** [comment]
It should show a message to notify who has the page block (when it is blocked of course)
