### ISSUE TITLE
Allow for missing release.properties

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13561]
some dev environments do not update the release.properties file when building dotCMS and the current defaults broke on the latest Chrome.  We need to allow better defaults.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13562

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13576

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now it works...
