### ISSUE TITLE
Unable to save Object to Hibernate Session exception creating contents

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13563]
We have a hibernate session problem, when you try to execute the publish content sub-action in a content that's has not been saved 

## Expected Behavior
We need catch this problem, or save the content first but not show this error 

## Current Behavior
We have a this error window
SC: https://screencast.com/t/mcl2mY0y

## Steps to Reproduce (for bugs)
1. Add a new workflow and just one step to this action 
2. Add a sub-action to this step (publish content) https://screencast.com/t/wPWAxtQwxN
3. Create a new content types and add just a text field 
4. Assign the created workflow to this content type
5. Try to create a new piece of content and execute the workflow

## Your Environment
Tested in the last master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13579

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13582

**Comment by bryanboza** [comment]
Fixed, this case, now we have a new improvement in #13578
