### ISSUE TITLE
Cannot edit Designed templates using Chrome 64

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13571]
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95244 

Once a content editor updates its Chrome browser to version 64, it fails to edit templates (Themes) created via Template Designer feature, and a JS error is thrown on browser's console. 

## Possible Solution
Remove https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/templates/design/design_templates.jsp#L345 since this call is not necessary.

## Known Workarounds
Downgrade Chrome version, or use another Browser.

## Steps to Reproduce (for bugs)

1. Upgrade Google Chrome browser to Version 64.
2. Login to demo.dotcms.com/dotAdmin 
3. Go to Templates Tool.
4. Open "Quest - 3 Column" template 

Screenshot:
<img width="1409" alt="screen shot 2018-02-06 at 9 04 11 am" src="https://user-images.githubusercontent.com/1717110/35866536-13adfffa-0b1d-11e8-8485-52574c02f0fd.png">

## Your Environment

* dotCMS version used: 4.2.2.
* Browser Name and version: Chrome, Version 64.
* Operating System and version: Any OS.
* Application Server and version: Any supported application server.
* Java Brand and version: Any supported Java version.
* Database and version: Any DB version.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/13573

**Comment by bryanboza** [comment]
Fixed, tested in the last master and in 4.3.1 and works as expected
