### ISSUE TITLE
Need improve some exception with workflows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13578]
We need improve the exception handler in some specific cases managing workflows

## Expected Behavior
We need show a better errors, and more clear exceptions 

## Current Behavior
Right now we have 2 exceptions caused by the same problem 

As part of the happy path, you need know about how the workflows works to create new ones, but in other case if you are exploring dotcms and cause exeptions like this ones, maybe we need work on this cases

**Case 1:**

- Create a new workflow and add a new step, in the action leave just the "copy contenttlet" sub-action
https://www.screencast.com/t/XK1bvixF
- Add a new content type and then set this workflow to the content type
- Try to add a new content, without save the contentlet, try to execute the workflow step
We have this exception on logs: https://gist.github.com/anonymous/3e1825c4b70a4d6ab59224c6846d5d8f
And this error at UI level: https://content.screencast.com/users/bryan--azuy/folders/Snagit/media/480f3e41-7083-44e8-aa46-28a2b2ca49fe/2018-02-06_12-20-21.png

**Case 2:**
- Do the same steps, but now with the **"publish content"** sub-action
This is the error on logs: https://gist.github.com/anonymous/29790f9dccb57a029619a25dc8b41920
And this is at UI level: https://www.screencast.com/t/8sdN9C7VEx

## Possible Solution
We need take a desition here, 

- Be smarter and save the piece of contents before excecute the action
- Improve the error messages, to be more clear about the error 

## Your Environment
Tested in the last master core // H2 // FF

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/14110

**Comment by wezell** [comment]
will be fixed in other issue
