### ISSUE TITLE
Site selector is not refreshing after Edit a Site in the backend.

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#13586]
There are two areas that will show you what site you are currently viewing. One is at the top of the screen in the blue bar and the other is when you are viewing the "Site Browser." When in the later section, you are able to see both at the same time.  However, using the following steps, it is able to have that section display two different sites, making it confusing to know which site I was actually making changes to.

Steps to recreate

1. Select a site using the upper blue menu
2. Click on Site Browser - > Browser
3. Platform correctly shows the same site name 
4. Click System -> Sites
5. Select a new site from this list (Click name)
6. Click Site Browser -> Browser
7. Platform incorrectly shows two different site names

![screen shot 2018-02-07 at 2 28 15 pm](https://user-images.githubusercontent.com/8225685/35939921-2f7c1bf8-0c13-11e8-88d1-8d121e506b6e.png)

**Comment by jdotcms** [comment]
on 4.x this could be handle by system events/web sockets
