### ISSUE TITLE
Copy contentlet sub-action need copy the references on pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13581]
Related to #13395 

As part of the changes on workflows, now we have the copy contentlet as a sub-action. But when you create a copy of any page,  need copy the entire page, this with all the references to their contentlets.

**FYI: We have the same behavior on demo** 

## Expected Behavior
Need create a exact copy of the page

## Current Behavior  
We create a copy of the page, but lost the contents associated to this one.

## Steps to Reproduce (for bugs)
1. Create a new Workflow
2. Add a new Step
3. Add a new action that execute the "copy contentlet " sub-action
3. Associate this workflow to the page asset content type
4. Create a new page and add some contents 
5. From content search open the page and execute the workflow 
6. Make sure the contents are in the copy of the page 

## Your Environment
Tested in the last master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13811

**Comment by bryanboza** [comment]
We need keep the order of the contents after copy any page 
SC: https://screencast.com/t/oits9zot

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13930

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now it works as expected
