### ISSUE TITLE
Need a forbidden exception if you don't have permissions to create content types in the new portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13590]
In the new portlet, When you try to create a new content type, and you don't have permissions, the REST service is giving back a 403 Forbidden exception, but we are not doing nothing with this at UI level 

## Expected Behavior
We need catch this exception, and show a forbidden error at UI level 

## Current Behavior
WE have just the exception on logs but we aren't doing anything in the FE 
SC: https://screencast.com/t/i7Q2KMXq

## Steps to Reproduce (for bugs)
1. Login as Chris Publisher 
2. Go to the new content types portlet 
3. Try to create a new content type 
4. Make sure you have the exception in the dotcms.log file 

## Your Environment
Tested on the last master // Postgres // FF

**Comment by fmontes** [comment]
User should not be able to get to the content type creation screen, will be fixed when this is done: https://github.com/dotCMS/core/issues/13726
