### ISSUE TITLE
Comment on workflow actionlet need a default comment 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13606]
As part of the new actionlets improvements, we need add a default comment to this sub-action

This to avoid errors in the log, If you add this sub-action to some action, and save it, by default the comment is null, then if you execute this workflow action, we have an error on log, and we have no errors at UI level 

## Expected Behavior
We need add a default comment to avoid this error 

## Current Behavior
We don't have a default comment, and if you execute this workflow we have this error on log 
ST: https://gist.github.com/bryanboza/04f445b3c04840359cdecef45e478f9f

## Steps to Reproduce (for bugs)
1. Add a new action to some WF 
2. Add a sub-action comment on workflow to this action and save it as default 
3. Assign this workflow to some content type
4. Add a new pice of content to this content type 
5. Execute the WF action 

## Your Environment
Tested in the last master // postgres // FF

**Comment by wezell** [comment]
Long standing issue
