### ISSUE TITLE
Upgrade Log4j2 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13613]
To what ES needs to function properly and minimum 2.6. 

This would mean have log4j2 unrepackaged and change all the references in our classes and other repackaged jars that use it (unrepackage them as well)

**Comment by nollymar** [comment]
PR ant-tooling: 
https://github.com/dotCMS/ant-tooling/pull/9 
https://github.com/dotCMS/ant-tooling/pull/10

PR core: https://github.com/dotCMS/core/pull/13688

PR ee: https://github.com/dotCMS/enterprise-2.x/pull/588
