### ISSUE TITLE
Delete actionlet isn't working on workflows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13618]
We have a NPE trying to use the delete actionlet on workflows. 

## Expected Behavior
This actionlet should delete the content  without problems 

## Current Behavior
WE have a NPE and the content is not deleted 

## Steps to Reproduce (for bugs)
1. Add a new workflow 
2. Add an action to this WF, with this sub-actions https://www.screencast.com/t/08s62H0b
3. Assign this workflow to any content type 
4. Create a piece of content 
5. Execute the action 

## Your Environment
Tested in the last master code // Postgres // FF

**Comment by jgambarios** [comment]
Unable to reproduce

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13791

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now it works, new improvements reported here: #13804
