### ISSUE TITLE
Sub-actions order isn't working in the workflow actionlets 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13615]
We have problems when you try to reorder the sub-actions list and then save the changes, we are not respecting this order 

## Expected Behavior
We need be able to reorder the sub-action list, this to execute the task in order. 

## Current Behavior
After you reorder the list and save the changes, we come back to the original order 

SC: https://www.screencast.com/t/zVk4LpvI

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to workflows (wf)
3. Add a new WF
4. Add a new step with an action 
5. Add multiple sub-actions to this action
6. Try to reorder and save the changes
7. Make sure we keep the order 

## Your Environment
Tested in the last master code // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13707

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now it is working as expected
