### ISSUE TITLE
ES: Number of replicas not defaulting to property value

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13614]
Even though we ship with `es.index.number_of_replicas=0`, the number of replicas are defaulting to '1' after the upgrade of Elasticsearch to 6.1

`AUTOWIRE_MANAGE_ES_REPLICAS=true` 
- should use the ClusterUtil to set the # of replicas
- user should not be able to update # of replicas in the UI

if 

`AUTOWIRE_MANAGE_ES_REPLICAS=false`
- should use whatever the default replicas are set to
- user should be able to update # of replicas in the UI
- system should respect this property `es.index.number_of_replicas=0`

**Comment by shaydotcms** [comment]
Passed QA.

Tested on master branch.
Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
