### ISSUE TITLE
remove hadoop 0.20.3-dev

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13625]

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14266

**Comment by erickgonzalez** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/613

**Comment by erickgonzalez** [comment]
PR dotcms-libs: https://github.com/dotCMS/dotcms-libs/pull/38
