### ISSUE TITLE
remove jboss jars

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13634]
dot.jboss-common-core', version:'2.2.3.GA_2'
dot.jbosscache-core', version:'3.2.5.GA_2'

**Comment by wezell** [comment]
This will remove the jboss cache classes

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14254

**Comment by erickgonzalez** [comment]
PR for dotcms-libs https://github.com/dotCMS/dotcms-libs/pull/35
