### ISSUE TITLE
/edit it's making the page go 404

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13646]
When you try to ```/edit``` any page the page get lost and goes 404 (cache maybe?)

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to any page (logged out) like: http://localhost:8080/about-us/index
2. Go to http://localhost:8080/edit
3. Try to go again to http://localhost:8080/about-us/index
4. It show 404

## Your Environment

* dotCMS version used: master
* Browser Name and version: Chrome
* Operating System and version: OSX Latest
* Application Server and version: 8
* Database and version: H2
* Application module (if apply):

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/13680

**Comment by erickgonzalez** [comment]
Please also check that this is working too https://github.com/dotCMS/core/issues/12170

**Comment by erickgonzalez** [comment]
New PR https://github.com/dotCMS/core/pull/13786 , the previous PR is closed.

**Comment by shaydotcms** [comment]
Passed QA
After login, user is redirected to the last visited page in Edit Mode.
No 404 error page

Tested master branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
