### ISSUE TITLE
JSP error trying to see the site dashboard 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13658]
We have an error in the JSP file when you try to see the site dashboard. And we are unable to see this  

## Expected Behavior
We should be able to see the sites dashboard without problems 

## Current Behavior
We have an unexpected error, and we are unable to see the dashboard 

Here the ST: https://gist.github.com/bryanboza/26ac4f38f52a1257bb25935b75f0a6af

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to Sites
3.  Select one site and enable the dashboard property
4. Go to Dashboard portlet and try to see the site dashboard 

## Your Environment
Tested on release 4.3.0 code and in the last master and I'm able to reproduce in both cases

**Comment by erickgonzalez** [comment]
PR for 4.3.0 https://github.com/dotCMS/core/pull/13660

**Comment by erickgonzalez** [comment]
PR for master https://github.com/dotCMS/core/pull/13662
