### ISSUE TITLE
Unrepackaging com/dotcms/repackage/org/apache/commons/lang/SystemUtils.class broke ant-tooling

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#13659]
Somewhere between 4.2.3 and the current 5.x nightlies, the `com/dotcms/repackage/org/apache/commons/lang/SystemUtils.class` library (dot.commons-lang-2.4_2.jar) was unrepackaged to `org/apache/commons/lang/SystemUtils.class` (commons-lang-2.6.jar). This has broken the plugins deployer due to a dependency in https://github.com/dotCMS/ant-tooling/blob/master/src/main/java/com/dotmarketing/plugin/util/PluginRoot.java. The library is called when deploy-plugins attempts to change permissions on executable files contained within a plugin.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13669
https://github.com/dotCMS/ant-tooling/pull/8
