### ISSUE TITLE
NotFoundInDbException in JS console 

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#13651]
Exception in Javascript Console when hitting backend Content -> Search

dotCMS Version: 4.2.2
Browser: Google Chrome
```
Content Type with id:'_all' not found 
{javaClassName: "com.dotcms.contenttype.exception.NotFoundInDbException", message: "Content Type with id:'_all' not found"}
javaClassName
:
"com.dotcms.contenttype.exception.NotFoundInDbException"
message
:
"Content Type with id:'_all' not found"
__proto__
:
Object
```
[Client Ticket.](https://dotcms.basecamphq.com/mobile/#/projects/14059395/todo_lists/29655057/todo_items/224944272)

**Comment by jcastro-dotcms** [comment]
Closing ticket, as https://github.com/dotCMS/core/issues/13753 will reference all the console errors in portlets.
