### ISSUE TITLE
[SiteSearch] Search by meta keywords is not working

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13667]
## Expected Behavior
If all page's html code is indexed, then keywords meta field should be indexed as well, and taken into account for searching purposes.

## Current Behavior
No matter which value we can set to a page's keywords meta field, these results are not retrieved by Site Search upon lookup of a potential match with existing pages. Even if we try to set a specific Site-Search behaviour, using code from our documentation 

https://dotcms.com/docs/latest/site-search 

or a similar approach like: 

```
#if ($request.getHeader("User-Agent") != "DOTCMS-SITESEARCH")
...
#end
```

Keywords are not indexed, and don't seem to be relevant for searching purposes.

## Known Workarounds
N/A.

## Steps to Reproduce (for bugs)

1. Make sure your dotCMS instance has an Enterprise License.
2. Edit this file: /application/themes/quest/html_head.vtl

and change this line
```
<meta name="keywords" content="$dotPageContent.seokeywords" />
```

with this
```
#if ($request.getHeader("User-Agent") != "DOTCMS-SITESEARCH")
<meta name="keywords" content="$dotPageContent.seokeywords" />
#else
<meta name="keywords" content="User Agent is spoofed. Neat.">
#end
```
Then, save and publish it.

3. Edit /about-us/index page and add this under SEO Keywords field: `Hello, is it me you are looking for`

4. Edit /about-us/locations/index page and make sure it's marked as Show on Menu, its Cache TTL is set to 0 seconds, and add `Sheeps say bah` under SEO Keywords field.

5. Run a Site search Job over demo.dotcms.com site. Let the system create a new index for it and make it default.

6. On a different browser, visit /about-us/index page in Live View (not logged in to the backend) and inspect its head tags:

If User Agent is browser's default (e.g., Safari), we will see the page's SEO Keywords field on the keywords meta tag.
<img width="1562" alt="screen shot 2018-02-20 at 10 04 10 am" src="https://user-images.githubusercontent.com/1717110/36434910-ca9eabde-1625-11e8-8fac-c45116d15509.png">

If we spoof the User Agent and set it to DOTCMS-SITESEARCH, we see the keywords value is changed to the static message we placed on the html_head.vtl file: 

<img width="1571" alt="screen shot 2018-02-20 at 10 04 51 am" src="https://user-images.githubusercontent.com/1717110/36434948-e58f3648-1625-11e8-8755-adf2a312bdb7.png">

However, if we continue spoofing the user agent, we cannot pull those pages which keywords are set to the static value

<img width="1569" alt="screen shot 2018-02-20 at 10 05 22 am" src="https://user-images.githubusercontent.com/1717110/36434994-023044f4-1626-11e8-91f2-af249caec7ec.png">

Reverting back the user agent to its default value, we see that the original SEO Keywords values are not taken into account: 

We should see all pages here with "Hello..." on their keywords meta tag
<img width="1158" alt="screen shot 2018-02-20 at 10 08 52 am" src="https://user-images.githubusercontent.com/1717110/36435052-2bb975b6-1626-11e8-8b49-a557d37ee4f2.png">

And here, we should be seeing the /about-us/locations/index page, which SEO keywords value starts with "Sheep". It's not listed.

<img width="1288" alt="screen shot 2018-02-20 at 10 09 06 am" src="https://user-images.githubusercontent.com/1717110/36435092-53a1d596-1626-11e8-9205-140aa180e2ba.png">

## Context
Knowing that we can modify the way pages are indexed in Site Search, this doesn't seem to work specifically with meta tags. Other parts of the code seem to work just fine, as demonstrated on this support ticket: 

https://dotcms.zendesk.com/agent/tickets/95314

## Your Environment

* dotCMS version used: 4.2.2.
* Browser Name and version: Latests versions of Chrome, Safari and Firefox Quantum.
* Operating System and version: Any OS.
* Application Server and version: Any supported Application Server.
* Java Brand and version: Any Java 8 version.
* Database and version: Any DB.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
From customer: 

> We've just confirmed that the User-Agent is null or empty when site search index is running. For example, this works:
> 
>` #if (!$UtilMethods.isSet($request.getHeader("User-Agent")) || $request.getHeader("User-Agent") == "DOTCMS-SITESEARCH")`

**Comment by acurionedotcms** [comment]
Enterprise PR: https://github.com/dotCMS/enterprise-2.x/pull/593

**Comment by wezell** [comment]
You can search keywords by adding +keywords:{searchTerm} - they are just not searched by default.

**Comment by iljaskevicarchitech** [comment]
Keywords are not the issue.

The issue is that the value set to keywords meta tag depends on the User-Agent and **User-Agent is blank or null when ES index job is running**. This means that the meta tag gets indexed with the wrong value and the search results are wrong.

That's why changing this:
`#if ($request.getHeader("User-Agent") == "DOTCMS-SITESEARCH")`
into this:
`#if (!$UtilMethods.isSet($request.getHeader("User-Agent")) || $request.getHeader("User-Agent") == "DOTCMS-SITESEARCH")`
makes it return correct results.

**Comment by dsilvam** [comment]
`$request.getHeader("User-Agent")` returns no value, but `$request.getAttribute("User-Agent")`, [as indicated in the documentation ](https://dotcms.com/docs/latest/site-search), properly returns `DOTCMS-SITESEARCH` value when Site Search job is running.

**Comment by iljaskevicarchitech** [comment]
Ok. Can you then please tell me where in your Changelog or somewhere else you document changing `$request.getHeader("User-Agent")` into `$request.getAttribute("User-Agent")` because I can't find it?

I've been trying to figure out why someone would use one when the documentation clearly specified the other (I didn't write this code). Fortunately, the WayBack Machine helped me figure out that your documentation actually said `$request.getHeader("User-Agent")` as late as Feb. 2017 and this code was implemented in 2015. You can see it [here](https://web.archive.org/web/20170212024902/http://dotcms.com:80/docs/latest/site-search).

Site-Search is one of your enterprise features, I would image that you'd make sure there is some transition, documentation, or (at least) backwards compatibility when changing something that impacts its core behaviour on dotCMS.

**Comment by joseorsini** [comment]
@iljaskevicarchitech 

As stated in the related Zendesk Ticket: 

Our documentation has reflected the right usage of this Velocity code since it was updated for the last time on 12/13/2017. Our suggestion form our comment in the Zendesk ticket from Feb 16th points to the right usage of this code:

```
#if($request.getAttribute("User-Agent")!="DOTCMS-SITESEARCH") 
      ##Custom code... 
#end
```

however your implementation was verifying the request headers instead.

```
#if ($request.getHeader("User-Agent") != "DOTCMS-SITESEARCH") 
    <meta name="keywords" content="$metaKeywords" /> 
#end 
##... other code here 
#set($pageCategories = ... 
#if ($request.getHeader("User-Agent") == "DOTCMS-SITESEARCH") 
    <meta name="keywords" content="$!pageCategories"> 
#end
```

Regardless, this Github ticket was raised anyways so it could validate meta keywords upon a SiteSearch lookup.

Let us know how it goes after applying the fix submitted to this Github ticket and applying the right code on your VTL files.
