### ISSUE TITLE
Error when push publishing in Oracle

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13663]
This is due to this query: 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/publisher/assets/business/PushedAssetsFactory.java#L18.

That query gets executed when push publishing with an empty dotCMS cache. 

Error is the following:
```
com.dotmarketing.exception.DotDataException: ORA-00932: inconsistent datatypes: expected - got NCLOB
{
  "SQL": ["SELECT * FROM publishing_pushed_assets WHERE asset_id = ? AND environment_id = ? AND endpoint_ids = ? ORDER BY push_date DESC"],
  "maxRows": [1],
  "offest": [0],
  "params": [
    "767509b1-2392-4661-a16b-e0e31ce27719",
    "598f20a8-4aa7-4665-9356-e5abe8d53466",
    "6d9e55b8-dad4-412d-b325-f2861b363a5f"
  ]
}
```

This is related to the changes introduced here: https://github.com/dotCMS/core/pull/11334/files#diff-2881d5e777e9114f694544c6ff4a3478R18.

Related to issue https://github.com/dotCMS/core/issues/10994

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13672
