### ISSUE TITLE
Unable to use twice the add new content tool in the angular menu 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13671]
We have a console error and we are unable to use twice the add content tool, this from the angular menu 

## Expected Behavior
We should be able to use this tool multiple times without problems 

## Current Behavior
We have a console error and the system is breaking with the loading element 
SC: https://screencast.com/t/WJkPWiyRw

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Click on  the "+" logo in the angular menu and select any content type
3. Add a new piece of content 
4. Click to the "+" button and select the same content type again 

## Your Environment
Tested with the last code of release 4.3.0  // postres // FF

**Comment by bryanboza** [comment]
Fixed, tested in the last code and works as expected.

**Comment by fmontes** [comment]
This was fixed in 4.3.0 here: https://github.com/dotCMS/core-web/commit/c28e9a4c1718fdbf6ddab09c0c69b7c20f59e8f9

But we need to make it in master, but we need a better fix.

**Comment by bryanboza** [comment]
Fixed, tested in master and works as expected. 

New issue reported here: #14200
