### ISSUE TITLE
Update ES examples to be compliant with ES6

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13676]
We have some examples of ES/lucene queries in our Documentation site that need to be updated considering:
* Filtering by date changed to support native date datatype fields
* "filtered" keyword was removed. "bool" must be used instead: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html

This notes can help as a guide for documentation updates: https://docs.google.com/document/d/1TN7P_CoXcMX6Vtgmg5S00Wwv3_mlUVfrhm8qGyWhRzY/edit?usp=sharing

**Comment by DeanGonzalez** [comment]
Documented: 
https://auth.dotcms.com/docs/latest/elasticsearch-examples
https://auth.dotcms.com/docs/latest/search-within-all-content-type-fields-using-catchall
https://auth.dotcms.com/docs/latest/aggregated-site-search (John Michael)
