### ISSUE TITLE
Can not create a SiteSearch Index

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#13691]
## Expected Behavior
You should be able to create a Site Search Index without issues.

## Steps to Reproduce (for bugs)
1. Go To Dev Tools Portlet
2. Clic over SiteSearch.
3. Create a new SiteSearch Index.

## Context
Seems to be related to the new upgrade of ES.

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13730
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/590
