### ISSUE TITLE
Unable to see events from the calendar portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13695]
When you add a new event we are unable to see this on the calendar view in the events portlet 

## Expected Behavior
We need be able to see the events from any of the views (day, week, month)

## Current Behavior
We are unable to see the events on those views, but we have the events in the "Event" content type

FYI: We save the piece of content, but isn't shown on the calendar portlet

## Steps to Reproduce (for bugs)
1.  Login as admin 
2. Go to the calendar portlet 
3. Add a new event 
4. Change between the views and try to see the added event 

## Your Environment
Tested in the last master code // postgres // FF

**Comment by acurionedotcms** [comment]
I was able to reproduce this issue. While debugging the code, realized that there's nothing wrong with the Calendar portlet.
It generates a Lucene query that filters by date, which is currently not working , related to the Elastic Search Upgrade. https://github.com/dotCMS/core/issues/13127

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13741

**Comment by shaydotcms** [comment]
Passed QA.
Event is showing appropriately in the calendar portlet by day, week and month.
Event is showing also in front end 
Images are showing well in backend and front end.

Tested in master branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8.6
