### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#13699]
Sporadic appearance of error message in log saying: "Failed to obtain DB connection from data source 'NonTxDataSource.DotMarketingQuartzExclusiveScheduler': org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction."

Excerpt from dotcms.log:  https://gist.github.com/brentgriffin/568b3d0ff7fba8f26e9acd336911967b 
 
Originally saw this issue while testing our docker containerization, but then verified it was a problem with a normal install from the .tar.gz nightly build file on my linux server.

## Steps to Reproduce (for bugs)

1.  Start up dotCMS and wait for scheduled jobs to fire

## Your Environment

* dotCMS version used: master-nightly-20180220
* Browser Name and version: NA
* Operating System and version: Linux
* Application Server and version: Embedded Tomcat
* Java Brand and version: Oracle JDK 8
Database and version: Postgres
Application module (if apply):

**Comment by mattyarbrough** [comment]
This is being experienced by clients in the field on 4.3.3
