### ISSUE TITLE
Unable to Modify Workflow Step "Enabled Schedule" once created

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13709]
Found in dotCMS version 4.2.2 and master.  Not sure where it first got introduced.

To recreate, create a workflow step and click the "Enabled Schedule" option and set a time limit.  Works as expected, and save the change.

Re-edit the workflow step.  The time for the scheduled action and the name of the action that was scheduled no longer displays (bug), and if you uncheck the "Enable Schedule" button, the box collapses (bug), making the bottom half of the step un-editable.

![enabledschedule](https://user-images.githubusercontent.com/1569167/36618993-d0650b50-18b2-11e8-9365-08595edb905a.png)

Screencast: https://screencast.com/t/M3zUiTKNyAS

**Comment by bryanboza** [comment]
dupe #13859
