### ISSUE TITLE
Make all loggers Async by default and add disruptor.jar

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13700]
We need to set all loggers to be async by default and add the distruptor.jar to our classpath:

@jtesser is the issue owner

From: https://logging.apache.org/log4j/2.x/manual/async.html

> Set System property log4j2.contextSelector to org.apache.logging.log4j.core.async.AsyncLoggerContextSelector

> Log4j-2.9 and higher require disruptor-3.3.4.jar or higher on the classpath. Prior to Log4j-2.9, disruptor-3.0.0.jar or higher was required.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14496
