### ISSUE TITLE
Auto select recently created content type in search portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13719]
As a User I want to be able to add content asap to a recently created content type.

## Expected Behavior
After user creates a content types and goes to ```Content > Search``` the new content type should be selected.

## Current Behavior
After user creates a content types and goes to ```Content > Search``` the new content type it's not selected.

## Possible Solution
This is a JSP thing, I think.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
https://www.screencast.com/t/QvdDvXHFc5

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15088

**Comment by bryanboza** [comment]
As in the old portlet, we need auto select the content type that you recently edited, after this change now it works just with created content types, but not in case you edit someone. We need some work here.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15112

**Comment by bryanboza** [comment]
Fixed, now it is working on release-5.0 // Postgres // FF

**Comment by bryanboza** [comment]
We have a special case here, in 5.x series we are excluding the host content type from the content search portlet, then If you recently modify this structure, when you move to the content search we need to clean the variable from the session and show the **"All"** option. 
Right now we show like an error in the field: 
https://screencast.com/t/ONWDaiDiB5h

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15188

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
