### ISSUE TITLE
Expire date fields it's not being saved

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13717]
As a User I want to be able to set expire date fields in my content type

## Expected Behavior
When user select a expire date field options and save it.

## Current Behavior
Users can't save a expire date field

## Screencast
https://www.screencast.com/t/LE4VpxKndC7 (it happen in the new dialog form too)

## Possible Solution
Check the model we're sending to the server.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a content type (for example News)
2. Set a expire field option
3. Save
4. Edit the form again, see that the expire date is not set.

**Comment by wezell** [comment]
Also, you are unable to set "now()" as a default value for date and time fields

**Comment by wezell** [comment]
![screen shot 2018-03-13 at 12 32 50 pm](https://user-images.githubusercontent.com/934364/37355706-bc90270c-26ba-11e8-87e0-3423d93ff623.png)

**Comment by alfredo-dotcms** [comment]
From the QA I did:

- When user select a expire date field options and save it. --> Works
- you are unable to set "now()" as a default value for date and time fields --> Failed (prob a new issue will be created for this) @fmontes

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now we save the expire field, new card to the date stuff in the #13915
