### ISSUE TITLE
PDF files with umlaut got corrupt (404 not found) after upgrade to dotCMS 4

### ISSUE THREAD

**Issue by yasindilekci** [dotCMS/core#13712]
After upgrading our dotCMS instance from version 3.7.1 to 4.2.2 we noticed existing PDF files with a diaeresis/umlaut character in the file name got corrupt.

When we tried to open the PDF files we were redirected to a 404 Not Found page.

## Expected Behavior
PDF files that we can still open and view, instead of them getting corrupt after an upgrade.

## Current Behavior
Existing PDF files got corrupt, redirected to 404 Not Found page when trying to open. The PDF files were working in the previous dotCMS version.

## Known Workarounds
None

## Steps to Reproduce (for bugs)
1. dotCMS 3.7.1 instance with a couple of PDF File Assets with an umlaut character in the title
2. Upgrade the dotCMS 3.7.1 instance to dotCMS 4.2.2
3. Try to open the PDF File Assets with the umlaut in the title (see step 1), these are corrupt after the upgrade

## Context
An example of one of the many PDF files which got corrupt as listed in the File Assets view:
![image](https://user-images.githubusercontent.com/10976988/36659826-10f0329c-1ad6-11e8-943c-7c136fed7c33.png)

Note the umlaut character is replaced by a diamond shape character with the question mark.

The 404 Not Found page we got redirected to when trying to open a corrupted PDF file:
![image](https://user-images.githubusercontent.com/10976988/36659892-598999f8-1ad6-11e8-82e2-939cd3efd937.png)

In WebDAV the file was shown as follows:
![image](https://user-images.githubusercontent.com/10976988/36659921-779e56c2-1ad6-11e8-84f6-227b25544e05.png)

And when we try to open the PDF file in WebDAV:
![image](https://user-images.githubusercontent.com/10976988/36659961-8e4ff1f0-1ad6-11e8-9e7a-463f4b9c0671.png)

This issue was solved by finding the file in the assets folder by inode and reuploading (without touching the umlaut).

## Your Environment
dotCMS 4.2.2

**Comment by DannyGloudemans** [comment]
Still an issue in dotCMS 5.1.1
