### ISSUE TITLE
Unable to upload file using Finder

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13716]
We're getting error code -36 with Finder when trying to upload a file.
Cyberduck uploads does upload files correctly.

## Expected Behavior
Finder should be able to upload file successfully to dotcms

## Current Behavior
Error code -36 with Finder when trying to upload a file, for example:
The Finder can’t complete the operation because some data in “Lead1.jpg” can’t be read or written.
(Error code -36)

## Known Workarounds
Use Cyberduck

## Steps to Reproduce (for bugs)
1. Open a Finder window and navigate to Go> Connect to Server
2. Use server address http://localhost:8080/webdav/live/1 then sign in with dotcms credentials
3. Upload a file to the backend using Finder 
4. You will get an error message:
https://gist.github.com/shaydotcms/7abe18a326e75064353c6706d75bf5d7

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Chrome v64
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/13817

**Comment by shaydotcms** [comment]
Passed QA. Files are successfully uploaded using Finder.

Tested on master branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6*
