### ISSUE TITLE
Filter the content types you can create based on instance license 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13714]
As a stakeholder I don't want users to be able to add content types that are not allowed to because of license level.

https://screencast.com/t/uil9tllzgK0k

## Expected Behavior
Show only the content types that user can add based on the license level.

## Current Behavior
Is showing all the content types no matter which license user have.

## Possible Solution
Edit the array of items we pass to the button base on the license

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to content types
2. Click in the + button
3. See the options in the sub menu

### Acceptance Criteria

1. Show only the base types users can create base on the license level
    - Need to ask what base types go with which license
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
We need to make sure this happens at the java API level too.

**Comment by dsilvam** [comment]
Related to: https://github.com/dotCMS/core/issues/13726

**Comment by fmontes** [comment]
Closing because https://github.com/dotCMS/core/issues/13726
