### ISSUE TITLE
Send notification when a content type or a content type field is deleted

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13718]
As a User I want to know when someone deletes a content type or that a content field DELETE JOB has finished and I want a meaningful message when this occurs

Right now we send stuff about the inode - no user cares.  We need to show something like:

Field **content.expireDate** (id:123213-12321321-123213) was deleted.

or Content Type **content** (id:123213-12321321-123213) was deleted.

## Expected Behavior
When an user deletes a content type or a content type field the system should send a websocket notification.

## Current Behavior
System is not sending notifications when any users delete a content type or a content types field.

## Possible Solution
Not sure, but is a backend thing.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to content types
2. Delete a content type
3. Nothing happens
4. Also, deletes a field
5. Nothing happens

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by wezell** [comment]
This needs to be done in the API

**Comment by erickgonzalez** [comment]
PR for notification of deleting Content Type: https://github.com/dotCMS/core/pull/16940
for the notification of the delete of a field is on hold because of this issue https://github.com/dotCMS/core/issues/16939

**Comment by wezell** [comment]
We don't need notification here, all we need to do is run the field "cleaning" in the background
