### ISSUE TITLE
Enhancement: Add a File Size Limit Parameter to Binary, Image, and File Fields

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13711]
It would be a nice enhancement to allow Webmasters to place a file size limit on Binary, Image, and File fields so that they could limit file size on uploads.  

Since File Asset Content types use these fields, that would also, by default, affect all other types of uploading to the Site Browser as well.

Small Mockup:

![filesizelimit](https://user-images.githubusercontent.com/1569167/36621387-6f928072-18bd-11e8-8ff1-28f2b46f4c50.png)

**Comment by bdestefanis** [comment]
This would be nice. We have content editors who routinely upload 30MB profile pictures.
