### ISSUE TITLE
Content types UI issues

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13723]
- [x] Hint information modal not showing in the right place: https://screencast.com/t/tXBYlOEX
    - PS: ```appendTo="body"``` should fix it
- [x] JS error when you select the User searchable checkbox: https://screencast.com/t/HdmrD6ySPn
- [x] if the row is empty we should not show the confirmation when try to delete.
- [x] Can't edit "Host or folder field" is related with the checkboxes
- [x] Some css tweaks

------------
### March, 15th

- [x] When click in the + to create a content type we got a error in the console
- [x] When user creates a content type the "System Workflow" should be checked by default (user can unchecked tho) **(event is the license is community)**
- [x] When create a content type basetype of page the contenttypes.content.page is missing.
- [x] Date fields selector updates are broken

**Comment by hmoreras** [comment]
The following are not working: 

- [ ] When user creates a content type the "System Workflow" should be checked by default (user can unchecked tho) (event is the license is community).  **Is not selected by default** https://screencast.com/t/70AQyqUbl2E

- [ ] if there are a few containers empty, and delete one, all get deleted. https://screencast.com/t/Jp3vKLIc.
