### ISSUE TITLE
[Push Publish] Pushing categories is not consistent

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#13722]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/95132

The `CategoryHandler` class is using a deprecated method to correctly update Categories. This is causing the push process to intermittently retrieve the incorrect Category in the receiver environment, causing the push to fail.

## Expected Behavior
Pushing contents with Categories should be consistent.

## Current Behavior
Using the incorrect method is making the push of Categories to fail.

## Possible Solution
Update the code to handle this issue.

**NOTE: A hotfix has been sent to the customer testing the fix, and it worked. Jose Castro will provide the fix for master.**

## Known Workarounds
N/A

## Steps to Reproduce
1. Ask the Support Dev for the steps.

## Context
Using the incorrect lookup method for Categories causes unpredictable behavior when pushing contents with Categories.

## Your Environment
* dotCMS version used: dotCMS 4.2.2
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Push Publishing

**Comment by jcastro-dotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/589

**Comment by oarrietadotcms** [comment]
@jgambarios there is a commit missing from the PR that @jcastro-dotcms did: see https://github.com/dotCMS/support/commit/582898d1cdb74a1f72cec19e94db5d832288a5bb

**Comment by splotzky** [comment]
That would explain the bug in #14403. Please include the missing commit in 4.3.4 and release it ASAP.

**Comment by jgambarios** [comment]
Missing commit: https://github.com/dotCMS/enterprise-2.x/pull/619
