### ISSUE TITLE
Content Type Permissions Not Respected by + Options Palette

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13726]
Tested on demo.dotcms.com running 4.3.1

The + actions palette lists all content types when the user has access to none of them.  These lists should pull based on a users permissions - no permissions, no items should appear in the list.

![respectobjectpermissions](https://user-images.githubusercontent.com/1569167/36684938-77739674-1ae7-11e8-9f1b-07cc646b8052.png)

This behavior is inconsistent with how we work elsewhere in the system

**Comment by DeanGonzalez** [comment]
This was reported by DB

**Comment by wezell** [comment]
Non issue with new ui
