### ISSUE TITLE
Users should not be able to edit system fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13720]
As a stakeholder I want to make sure users don't break some content types by editing system fields

## Expected Behavior
"System fields" should not be editable in some content types.

## Current Behavior
All fields are editable in all content types.

## Possible Solution
1. Check in demo.dotcms.com old content type to see the pattern here
2. Ask other developers, could be QA, Gamba or maybe even Dean can have the info about the patterns

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a "Persona" type
2. See you can edit all the fields
3. https://www.screencast.com/t/CmLAxIm5i

### Acceptance Criteria
1. We need to apply the same pattern as in demo.dotcms.com
2. Match the design
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by freddyucv** [comment]
we are already doing this for the delete button right here: 

https://github.com/dotCMS/core-web/blob/master/src/app/portlets/content-types/fields/content-type-field-dragabble-item/content-type-field-dragabble-item.component.html#L10

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now we are unable to edit this fields
