### ISSUE TITLE
Add a dropdown to filter content type listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13725]
As a User I want to be able to search for content types of a particular base type

## Expected Behavior
Listing table should a dropdown with the base types to user can filter and search base on that selection
![Screen Shot 2018-02-26 at 10.49.49 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/359bfa8d-b2e2-4d29-954a-aff458a9d119)

## Current Behavior
Users can only search for all the base types

## Possible Solution
Just build it.

## Known Workarounds
N/A

### Acceptance Criteria
1. Dropdown options should come from the base type endppint
2. Add the dropdown before the current search textfield
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14752

**Comment by wezell** [comment]
This is solved with #14560

**Comment by fmontes** [comment]
When you select "Any content type" show no results

**Comment by bryanboza** [comment]
We have two options at the end of the list Recent content and Recent widgets, these options are not working, also we need show the scrollbar here. 
<img width="1680" alt="list" src="https://user-images.githubusercontent.com/2641437/42783184-67c30ce8-8908-11e8-958f-a3213cc18be3.png">

Log: https://gist.github.com/bryanboza/13800fe88f8b4d36bcc000fdbe5a95ce

**Comment by hmoreras** [comment]
@bryanboza , `Recent` types are not longer part of the list

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Also show the correct data with and without license
