### ISSUE TITLE
Can't add multiples options to radio, selects or checkboxes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13721]
As a user I want to be able to add multiple options to fields

## Expected Behavior
When user add a new line in the value of a radio, selects or checkboxes it means is a new option.

## Current Behavior
Users can't add more than one option to those fields.

## Possible Solution
Not sure, we need to look what we send to the endpoint and how that handle it, the fix could be FE or BE.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
https://www.screencast.com/t/oq2Bbh4QUpCK

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now we are able to add multiple options to this fields
