### ISSUE TITLE
Image/File Field uploads should not display "Save and Publish" option if user does not have Publish rights to site/folder

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13727]
Tested on latest 4.3.1

If a content type has and image or file field, the user has to select the site/folder that they are going to upload the file to.  Right now we are not checking permissions on the selected object when we display the "Save and Publish" button.  That button should only display if the user has rights to publish files to the default file object type set on the folder.

For example, the user below only has "Edit" permissions on the file asset content type, but the "Save & Publish" button displays anyway.

![imagefileuploadstofolder](https://user-images.githubusercontent.com/1569167/36685920-719eec8c-1aea-11e8-94a1-f5690a245b21.png)

When the user clicks the "Save & Publish" button, the content is merely saved, but we should not be displaying the action which the user can not actually take.

**Comment by DeanGonzalez** [comment]
This was reported by Deutschebank

**Comment by wezell** [comment]
not an issue in 5.x
