### ISSUE TITLE
Inconsistencies on vanity URLs when you import and when you create it manually 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13736]
We have different behaviors when you try to import content and when you create new vanities manually. 

We need have the same value in "host_inode" in the identifier table  and the "Site field"  in the contentlet table 

## Expected Behavior
We need be consistent whit this behavior in both cases 

## Current Behavior
- When you import vanities, the column "host_inode" is saved as "SYSTEM_HOST". 
<img width="1173" alt="t4 1" src="https://user-images.githubusercontent.com/2641437/36744086-86b73152-1bb1-11e8-9623-f3eb86834d6c.png">
<img width="1333" alt="t1 1" src="https://user-images.githubusercontent.com/2641437/36743943-29687ace-1bb1-11e8-8560-52354a11b57f.png">

- But when you create the vanity manually from backend, the "host_inode" and the Site field have the same value. 
<img width="1193" alt="t3 1" src="https://user-images.githubusercontent.com/2641437/36743960-31bfeda6-1bb1-11e8-9c67-f1db83898620.png">
<img width="1203" alt="t3 2" src="https://user-images.githubusercontent.com/2641437/36743964-33ac134c-1bb1-11e8-9c4a-008982216273.png">

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to the vanity URL portlet and create a new vanity from backend 
3. Now try to import some vanity from a CSV file 
4. Check at the data base level in both cases you have the same value in "host_inode" in the identifier table  and the "Site field"  in the contentlet table 

## Your Environment
Tested in the last master code // postgres // FF

**Comment by levosgien** [comment]
Customer Ref: https://dotcms.zendesk.com/agent/tickets/95445
