### ISSUE TITLE
Create new rest endpoint to the execution of a given action on a given content

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13747]
Right now we have a **com.dotcms.rest.WorkflowResource** with just a **fireWorkflow** method, the idea of that method is to allow the execution of a given action to a given content, we need to **deprecate** that resource and create a similar method in the new **com.dotcms.rest.api.v1.workflow.WorkflowResource** adjusted to the new Workflows logic.

Related to https://github.com/dotCMS/core/issues/13640

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13775

**Comment by bryanboza** [comment]
After test this REST service we have some improvements:

- [ ] In case of fail (401), we need log this transaction in the dotcms.security.log

- [ ] We are able to execute any action from this rest, without validate if the workflow is associated to the content or not

- [ ] We are not respecting permissions, if you add the user in the "**how can use**" field, this user can save content without validate if have permissions to save in the content type or not

- [ ] We have a 500 error (Internal server error), in case you don't have permissions to read the action, we need a 401 (unauthorized) error here

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13873

**Comment by bryanboza** [comment]
We have new problems with this REST... A new card created here #13905

**Comment by bryanboza** [comment]
Note to QA: We need this fix to test again this REST

**Comment by bryanboza** [comment]
Fixed, new improvements created in a separate tickket
