### ISSUE TITLE
Allow the System workflow with a community license

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13744]
The *System workflow* should be available with the community edition.

## Expected Behavior
Even without license the basic operations provided by the *System Workflow* should be available.

## Current Behavior
As workflows is an enterprise feature without license is not possible to use the *System Workflow*.

## Possible Solution
Add an special case in order to allow the use of the *System Workflow* without license just like the *Default Scheme*

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13775

**Comment by bryanboza** [comment]
Now we have this issue after apply the license #13903

**Comment by bryanboza** [comment]
Fixed.
