### ISSUE TITLE
Cascading Permissions from Host not respected by "All Sites" Template list

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13749]
Tested on latest 4.3.1 version

It is easiest to watch the video to replicate this because there are a few steps, but here is how to reproduce:

1) Create a new blank site and call it "Site B"
2) Create a new Role Called "**Test**" and give it the Home, Site Editor, Content Tools - then under permissions, give the following permissions on the demo.dotcms.com host click the **Cascade Permissions** checkbox and apply the permissions:

![demo permissions](https://user-images.githubusercontent.com/1569167/36812634-6063b4f8-1c97-11e8-9268-2edc7261ac8a.png)

Now give the role these permissions on the Site B Host:

![sitebpermissions](https://user-images.githubusercontent.com/1569167/36812639-66422184-1c97-11e8-8d09-171e0c6028e1.png)

4) Edit the **Page Asset** Content Type and assign it to inherit permissions from the **demo host** instead of system host under the properties of the Page Asset Content Type.

5) Create a new user and assign the user to the **test role**, then Login As the user

6) Try to create a new Page on the on Site B, and after selecting page asset, click on the template selector, then click on the "All Sites" option.  Click on the template select again and it is blank - This is the bug. All the templates from demo.dotcms.com should be available to the user, but none are.

Unlisted Video on how to reproduce: https://youtu.be/MfuZjnloetI (Not listed on our youTube channel, no panic)

Interesting Footnote, to get the templates to show up on the list for the limited user, all you have to do is edit any template, click cancel, then login as the limited user, and it shows up on the list.

**Comment by DeanGonzalez** [comment]
Since this list is used by some larger clients we should import maybe 2000+ hosts and make sure that the field is still very performant with the autocomplete search functionality

**Comment by levosgien** [comment]
https://dotcms.zendesk.com/agent/tickets/95850
