### ISSUE TITLE
FileAsset not publishing after executing Save&Publish action

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13740]
Trying to upload and publish a file via Site browser is not doing so. 

**Steps to reproduce**:
1. Go to Site Browser
2. Chose a folder or site level
3. Click on the menu (three dots) button at the top right corner and chose MultipleFiles 
4. Select "FileAsset"
5. Click on "Select Files to Upload"
6. Choose your file
7. Select "Save and Publish" from the dropdown next to "Execute" button.
8. Click "Execute" button 

**Result**: The file is only _saved_ instead of _saved and published_
**Expected Result**: The file should be _saved and published_

Screencast: 
https://www.screencast.com/t/J1HCbnqW

**Comment by jgambarios** [comment]
This ticket will be fix in https://github.com/dotCMS/core/issues/13789
