### ISSUE TITLE
json link not working under Marketing->Forms->Add New Form

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#13751]
## Steps to Reproduce (for bugs)

1. Go to Marketing->Forms->Add New Form
2. Click on "Type: Form json" link

## Context
Missing content type: url looks like this /id/api/v1/contenttype/id/
[Source code related.](https://github.com/dotCMS/core/blob/99c826953483e221e1f8c9dce28fbcc9b6ae6774/dotCMS/src/main/webapp/html/portlet/ext/structure/edit_structure.jsp#L595)

## Your Environment

* dotCMS version used: 4.3.1

**Comment by jcastro-dotcms** [comment]
Just a clarification:

The link **does not work** when you are creating a new Form only. If you create it, go back to it, and then click the JSON link, it will work as expected.
