### ISSUE TITLE
Filtering by date in the Contentlet Portlet is not showing results

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13755]
With the ES upgrade, this functionality is broken. Probably, dates are not being formatted properly. 

![filter_by_dates.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/e1e2380a-3d7d-4b77-a458-001df2ebefae)

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13790

**Comment by shaydotcms** [comment]
Passed QA.
Ran Lucene queries using correct and incorrect date formats such as:
- Correct: 2018-03-05 || 03/05/2018 || 3/5/2018
- Incorrect: 2018/03/05 || 20180305 || 03052018

Verified that results are as expected

Tested in master branch
Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
