### ISSUE TITLE
remove old jars (was: Change log4j imports in jars)

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13754]
We have three jars that need the log4j import to be changed to the non-repackaged version.

Find out the usages of these libraries and if not used, remove.

- Binary file dot.bsf-ukv_2.jar matches
- Binary file dot.cargo-core-uberjar-0.9_2.jar matches
- Binary file dot.hadoop-dev-core-0.20.3_2.jar matches (this one should be  #removed)
- Batik ?
- jasperreports
- Abdera
- Jetty
- Jboss Core and cache
- Drools

**Comment by wezell** [comment]
The fix is to remove these jars.

**Comment by wezell** [comment]
Dupe #13622
