### ISSUE TITLE
Templates portlet is showing archived templates even when "Show Archived" option is not checked

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13768]
You create a new template and then archive it. When you create a 2nd template, you can see that the archived template is being shown even if "Show Archived" option is not checked.

## Expected Behavior
System should not show archived templates if "Show Archived" option is not checked.

## Current Behavior
Templates are being shown even if "Show Archived" option is not checked.
![image](https://user-images.githubusercontent.com/8741846/36908091-e9f1ca3e-1dff-11e8-9608-2fd105514511.png)

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Site> Templates
3. Create a new template. Select either Designer or Advanced template. Hit Save or Save/Publish
4. Right click over the new template > Unpublish. Then right click again and Archive
5. Hit "Show Archived" option.
6. Now again create a new template. Select either Designer or Advanced template. Hit Save or Save/Publish
7. You will see now that "Show Archived" option is unchecked and previous archived template is showing in the list of templates even when "Show Archived" option is now unchecked.

## Your Environment
* dotCMS version used: http://demo.dotcms.com
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version:Chrome 64
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by wezell** [comment]
known issue
