### ISSUE TITLE
Advanced template should not delete text in "Description" if template Title is missing

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13769]
When you create an advanced template and fill in "Description" field but miss the template Title and hit save or save/publish, the template description gets deletes.
https://screencast.com/t/LNaRh8vFQcMO

System should not delete the text in the description field.

## Expected Behavior
System should keep the text in the description field.

## Current Behavior
Text in "Description" field is deleted if you miss the template Title and hit save or save/publish.

## Steps to Reproduce (for bugs)
1. Login to dotcms
2. Navigate to Site> Templates
3. Hit the ellipsis to create new template. Choose Advanced Template
4. Type in some text in Description field. Do not put any data in Title field.
5. Hit Save or Save/Publish
6. You will see the text in the Description field is deleted.

## Your Environment
dotCMS version used: master branch
Database and version: Postgres 9.6.6
Operating System and version: Mac OS 10.10.5
Browser Name and version:Chrome 64
Application Server and version: Tomcat 8
Java Brand and version: Java 8

**Comment by wezell** [comment]
known issue
