### ISSUE TITLE
ES Search: Sort results by modDate in case a sortBy field is not specified in the query

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13760]

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13805
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/595

**Comment by nollymar** [comment]
This doc needs to be updated: https://auth.dotcms.com/docs/latest/sorting-content-pulls-by-score#Sorting

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/sorting-content-pulls-by-score#Sorting
