### ISSUE TITLE
Incorrect behavior when you are setting permissions and use the login-as functionality 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13774]
We have a weird behavior when you are in setting permissions to some content type and try to use the login-as functionality 

## Expected Behavior
We need refresh the portlet and show the correct permissions 

## Current Behavior

- [ ] When you login-as, the system isn't refreshing the tab and seems you have permissions to edit. (if you try to edit we have an error)
SC: https://screencast.com/t/bKwqCf5F

- [ ] After you refresh manually we are showing the incorrect permissions, this will cause confusions 
SC: https://screencast.com/t/RqcISotkcJw8

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to the content types portlet 
3. Select some conte type and add permissions to view to some limited user 
4. Using the login-as, try to login as the selected limited user 
5. Edit some permissions and save changes 

6. Repeat the steps 1-4, but now refresh the page and go to the permissions tab as the limited user 
7. Make sure this are the correct permissions

## Your Environment
Tested in the last master // Postgres // FF

**Comment by fmontes** [comment]
### Solution
1. Create a service that is one-one the [iframe-component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/iframe/iframe-component/iframe.component.ts)
2. Create a method "reload" in the service
3. When that method is called the iframe reload whatever page it have loaded

**Comment by bryanboza** [comment]
We need refresh the entire portlet here and redirect to the content types list that you have permissions to see...

**Comment by fmontes** [comment]
@bryanboza I create another issue because this functionality is completely out of the scope of this user story: https://github.com/dotCMS/core/issues/14037
