### ISSUE TITLE
Ship with a osgi-extra-generated.conf

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13778]
Having the system build it is error prone and can produce unexpected results, depending on how tomcat is started.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13803

**Comment by bryanboza** [comment]
Fixed, tested the follow cases: 
- Edit the file, and start dotCMS... The system leave the same file with the changes
- Remove the file... The system is auto-generating a new file 
- Rename the file to "osgi-extra.conf" and edit the file... The system leave the same file 

Tested in the last master code // postgres // tomcat
