### ISSUE TITLE
Need add the content types to the angular menu when you create a new one from the new portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13771]
We need be able to add new pieces of content selecting the content type in the "+" button in the angular menu

## Expected Behavior
When you add a new content type from the new portlet, we fire an event to add this to the content types list in the "+" button on the angular menu

## Current Behavior
After you save the new content types, the system isn't adding it to the list 
SC: https://screencast.com/t/5eDlL2Xv0ZS

## Possible Solution
Create a listener and we send the new content type when is created.

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to the new content types portlet 
3. Add a new content type 
4. Try to add a new piece of content using the "+" button in the angular menu

## Your Environment
Tested on master // postgres // FF

## Acceptance Criteria

1. Update Add (+) button content in the toolbar when new content type is added to the system
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
###We need
1. BE work: dispatch a websocket event.
2. FE work: listen to that event and update the list.

**Comment by fmontes** [comment]
We're getting rid of that button here: https://github.com/dotCMS/core/issues/14495
