### ISSUE TITLE
Improve Workflows Actionlets by handling special cases

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13783]
Analyzing the operations we have when right click on the Site Browser and Content Search we found special cases we need to handle depending on the selected content type.

Actionlets to modify:

1. Copy actionlet adding special cases for Pages and Files
2. Publish actionlet adding special cases for Pages and Events
3. Delete actionlet adding special cases for Pages and Files

**Comment by wezell** [comment]
We can fix this in the contentlet API, right?

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13811

the delete and publish actionlets works in the same way for pages, events and files contents

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now I am unable to reproduce the errors...
