### ISSUE TITLE
Permissions error executing worflows actions as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13782]
We have a permissions exception if you try execute a workflow action as a limited user and we are unable to fire the action 

## Expected Behavior
If you have the required permissions we need be able to fire actions as any limited user 

## Current Behavior
We have a permissions exception and we are unable to execute the action 
LOG: https://gist.github.com/bryanboza/223611969bc52f28cd98d75b861179b1

## Steps to Reproduce (for bugs) 
1. Login as admin 
2. Edit the Save&Publish action for new contnets in the system workflow, add permissions to any who can publish (https://screencast.com/t/CZn30Xc7)
3. Add a new content type and add full permissions to any limited user 
4. Login as this limited user and try to execute the Save&Publish action 

## Your Environment
Tested in the last master code // Postrges // FF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13828

**Comment by bryanboza** [comment]
Fixe now this is working properly...
