### ISSUE TITLE
System Workflow improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13789]
We need to improve our current System Workflow fixing some known issues and changing the current steps.

### Known issues to fix (related to https://github.com/dotCMS/core/issues/13740):
1. The `Save & Publish` action have the actionlets in the wrong order, we need to change the order in the starter site, generar a new starter zip and modify the upgrade task of the System Workflow.
Please make sure the order in the other actions is correct.
2. Also the `Who can Use` is missing from all the actions on the _System Workflow_

### Improve the initial step (related to https://github.com/dotCMS/core/issues/13780)
After finishing the changes in https://github.com/dotCMS/core/issues/13780 we need to improve _System Workflow_ first step in order to allow existing contents to interact correctly with the _System Workflow_

**Comment by jgambarios** [comment]
**Note:** Should we add a _Reset_ action?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14014

**Comment by bryanboza** [comment]
Note to QA: We need test the upgrades here, make sure the system workflow works as expected

**Comment by bryanboza** [comment]
Tested after upgrade from 3.x version en each database engine and looks as expected, more improvements reported in new cards .
