### ISSUE TITLE
compileAspect faild with Syntax error

### ISSUE THREAD

**Issue by Anhong2008** [dotCMS/core#13787]
I'm a beginner of learning to use dotCMS. I have checked out master code from github(Without Enterprise Module). 
After i imported the project into my intellij idea, when execute the gradle jar task, it failed as bellow:
`
:compileAspect
[ant:iajc] .\DotCms\core\dotCMS\src\main\java\com\dotcms\csspreproc\CSSPreProcessServlet.java:37 [error] The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files
[ant:iajc] public class CSSPreProcessServlet extends HttpServlet {
[ant:iajc]                                           ^^^^^^^^^^
[ant:iajc] .\DotCms\core\dotCMS\src\main\java\com\dotcms\csspreproc\CSSPreProcessServlet.java:40 [error] Syntax error, annotations are only available if source level is 1.5 or greater
[ant:iajc] @Override
[ant:iajc] ^^^^
[ant:iajc] 
[ant:iajc] 2 errors
:compileAspect FAILED
`
## Expected Behavior
Could someone please tell me what's the problem? Thanks.
I thinks maybe threre is something wrong with my configuration about aspjectj.

## Your Environment
* dotCMS version used:master
* Browser Name and version:chrome 
* Operating System and version:windows7
* Application Server and version:tomcat8
* Java Brand and version:jdk 9
* Database and version:
* Application module (if apply):

**Comment by jgambarios** [comment]
Hi @Anhong2008 please submit this kind of questions in the google group community https://groups.google.com/forum/#!forum/dotcms
Please remember the master branch is not an stable branch and you can always refer to the dotCMS documentation https://dotcms.com/docs/latest/developing-from-source
