### ISSUE TITLE
Extend Workflows Action Show When capabilities with more statuses

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13780]
We need to extend the workflows actions adding more display statuses, right now we have only three display statuses:

* Lock
* Unlock
* Both

We need to add the following statuses in two different fields:

1. (Lock || Unlock)
   * Lock
   * Unlock
2.  (New || Unpublished || Published || Archived)
    * New
    * Unpublished
    * Published
    * Archived

In code we will use an **AND** condition between them resulting is something like:
```
(Lock || Unlock) && (New || Unpublished || Published || Archived)
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13808

**Comment by bryanboza** [comment]
Fixed, now we have multiple options in master, more changes pending here (UI) but we can close this card.
