### ISSUE TITLE
Cache problems navigating on front end 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13788]
We are getting a cache error when you try to navigate on any of the pages in our FE

## Expected Behavior
We need be able to navigate without errors 

## Current Behavior 
Every time you try to navigate to any page that you don't have in cache we are getting this error: 
ST: https://gist.github.com/e27879cd2ee10f36619543db828e785d

## Steps to Reproduce (for bugs)
1. Make sure you have the latest master running
2. Go to your FE
3. Navigate to any page 
4. Check your dotcms.log file 

## Your Environment
Tested on master // postgres // FF

**Comment by wezell** [comment]
I looked into this and could not quickly find what velocity object/bean we were trying to persist that included the UserApiImpl.  Maybe the PageResource somehow?  Regardless, this needs to be found and fixed before 5.0

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13863

**Comment by shaydotcms** [comment]
Passed QA.
Navigated through most of the pages in FE, no errors where thrown in the logs.
Tested on master branch / Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
