### ISSUE TITLE
Content history is not keeping order when a content is edited

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#13796]
When contentlet versions are not loaded from cache, a DB query is used to return these results, but records are not being ordered by modDate (Descending)

**Code hint:** https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L900-L901

**Screenshot:** https://www.screencast.com/t/jti3uLkzMMx5

## Expected Behavior

Contentlet versions must be displayed and sorted by modDate (descending order)

## Steps to Reproduce (for bugs)

1. Open a News content to edit
2. Modify any field, click on Save and immediately go to the History Tab 

## Your Environment

* dotCMS version used: dotCMS 5.x
* Browser Name and version: Google Chrome
* Database and version: Postgres
* Application module (if apply): Contentlet portlet

**Comment by nollymar** [comment]
Fixed in https://github.com/dotcms/core/issues/13760

**Comment by DeanGonzalez** [comment]
Clicking on save ends up with erratic ordering and the published status is changing on the versions even though there was no publish action: https://screencast.com/t/ErNsUnnphc - needs some more work

**Comment by DeanGonzalez** [comment]
Hi Nolly, as we discussed together in our share screen, there are still two issues.  All Save actions are ordering properly, but when a publish action is made via the workflow, the content in the history 1) shows saved, not published (first bug), and secondly, when the content is saved again, after a published version 2) the newly saved content does not appear at the top of the list, but at the bottom:

![order](https://user-images.githubusercontent.com/1569167/37310804-bfc25162-260a-11e8-9177-1b47f2eb6094.png)

**Comment by DeanGonzalez** [comment]
passed qa
