### ISSUE TITLE
Problems executing the Save as Draft action of the Document Management workflow 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13799]
We have an error trying to get the Save as draft action, this because we are getting an error and the content isn't saved 

## Expected Behavior
We should be able to execute this action without problems 

## Current Behavior
We have this error and the content isn't saved 
<img width="315" alt="err1" src="https://user-images.githubusercontent.com/2641437/37053492-ed8f2836-2141-11e8-8562-1942a9694d6f.png">

Log: https://gist.github.com/bryanboza/a41488e9b0b7e7b06544ad3b975ae14b

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content search 
3. In the document content type, try to upload a new file  
4. Execute the save as draft action 

## Your Environment
Tested in the last master // postgres // FF

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/13783

**Comment by bryanboza** [comment]
Fixed, tested in master and now I am unable to reproduce
