### ISSUE TITLE
Delete sub-action improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13804]
As part of our typical workflow to delete some content you need pass throw some specific steps, 
Unpublish // Archive // Delete,  but right now this sub_action is able to delete published content directly. 

Also we should be able to delete content individually by language 

## Expected Behavior
We need respect this rules and allow delete just in case of the piece of content is archived 

Also if you have a multi language content, you should be able to delete any of the languages individually

## Current Behavior
We have two interesting cases here: 

- [ ] We regulate this just from the UI, but if you create a custom workflow, we allow delete published content directly or also you can call this action via REST

- [ ] If you have a published multilingual content, and you try to delete directly this works, but if you unpublish, then delete, this is failing deleting 
Here the error 
```
[07/03/18 11:35:02:844 CST] ERROR ajax.ContentletAjax: null
java.lang.NullPointerException: null
```

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a custom workflow 
3. Add a new action and add the delete sub-action on it 
4. Associate this to the Generic conte type 
5. Try to execute that from a published piece of content 

## Your Environment
Tested on the last master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13932

**Comment by bryanboza** [comment]
Fixed, after this validation we are unable to see the error...
