### ISSUE TITLE
Error when running Lucene query containing some datetime format 

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13806]
System is currently throwing an error in the Query tool when running a query containing the following datetime format: yyyy-MM-dd’T’HH:mm:ss
Example of query:
```
+contentType:News +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +News.sysPublishDate:03/05/2018T23:00:00 +languageId:1 +deleted:false +working:true
```
Result:
![image](https://user-images.githubusercontent.com/8741846/37111440-4b24e710-2205-11e8-8ffe-f16b6ce24cfd.png)

## Expected Behavior
System should process appropriate valid/invalid query
Query Error should not be displayed in UI

## Current Behavior
System is currently throwing an error in the Query tool when running a query containing the following datetime format: yyyy-MM-dd’T’HH:mm:ss

## Steps to Reproduce (for bugs)
1. Login to Dotcms
2. Navigate to Dev Tools> Query Tool
3. Run following query:
```
+contentType:News +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +News.sysPublishDate:03/05/2018T23:00:00 +languageId:1 +deleted:false +working:true
```
4. You will get an error in the UI

## Your Environment
 * dotCMS version used: master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v58.0
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13818

**Comment by nollymar** [comment]
The supported datetime format is: **MM/dd/yyyy HH:mm:ss**
Internally, dates are converted according to the lucene pattern: **yyyy-MM-dd'T'HH:mm:ss**

**Comment by shaydotcms** [comment]
Passed QA. Supported datetime formats **MM/dd/yyyy HH:mm:ss** and **yyyyMMddHHmmss** show results as expected.

Tested on master branch.
Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
