### ISSUE TITLE
Add Save and Update Scheme to the WorkflowResource

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#13819]
Add Save and Update Scheme to the WorkflowResource

Add the POST and PUT for the Workflow with diff methods and forms.
Keep the back-compatibility with the current ajax and reuse the current code to do the resource by using the helper.

**Comment by jgambarios** [comment]
Also we need to verify all the operations we have here: https://github.com/dotCMS/core/tree/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/ajax and try to map those operations to rest endpoints.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13829

**Comment by jgambarios** [comment]
**Note to QA:** Please make sure that not only the new rest endpoints but also the operations from the portlet are working properly

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13847

**Comment by bryanboza** [comment]
Fixed, now we have this methods in the workflow resource, we reported a new improvements here: #13964
