### ISSUE TITLE
Improve Websocket Notifications

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13812]
We need to use the websocket/Notification API to send more Events to give richer feedback to the user when actions/errors happen within dotCMS. These include

1. SimpleTextEvent 
Shows a simple text message

2. SimpleErrorTextEvent
Shows a simple error message

3. HtmlNotificationEvent - 
Shows a pre-formated html message

4. ConfirmNotificationEvent - 
- message
- confim callback funtion

shows a message with a cancel button and an ok button - when the ok button is hit, it fires a RestAPI call

**Comment by john-thomas-dotcms** [comment]
Would it also make sense to add a workflow sub-action that generates a system event (or at least a notification)?

There is at least one customer issue asking for something like this, which could be solved if we had a sub-action to do this.

**Comment by jgambarios** [comment]
@john-thomas-dotcms I like the idea of having a Workflow sub-actions that generates al least for now a System notification

**Comment by wezell** [comment]
it isn't a system notification. it is a one off message.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14004

**Comment by bryanboza** [comment]
Unable to see the notifications after set the action, we need some work here

**Comment by jgambarios** [comment]
This ticket is it just the first part of the new websockets notifications which is done, the second part consist in integrate these new notifications into core-web https://github.com/dotCMS/core/issues/14023

**Comment by jgambarios** [comment]
Improvements made in https://github.com/dotcms/core/issues/14161
