### ISSUE TITLE
Ship with minimal log4j2.xml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13813]
We need to ship (when you download dotCMS) with a minimal log4j2 config that spits everything out to the console for 2 reasons:

1. Our current log4j2 setup is confusing and can obfuscate errors from our developers, testers and users.
2. As we move towards containerization, spitting everything out to STDOUT is the expected behavior.

We can still include our bigger log4j config as the production example.

**Comment by wezell** [comment]
This also only shows the parent package and class name of the log writer - which makes for smaller logs.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13815

**Comment by shaydotcms** [comment]
Passed QA.
Performed several actions on the system such as push publish, integrity checker, cluster configuration, create/update/delete content types, create/clone existing sites, workflow actions, licensing, categories, tags, ES search, time machine, etc.
System seems to displaying every log in console appropriately.
Tested on master branch / Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6

**Comment by john-thomas-dotcms** [comment]
The following documentation also needs to be updated:

* "Logs" tab in the "Maintenance" screen: Explain why the default config shows no logs.
* Log4j documentation: Point to the production example log4j.xml file.
