### ISSUE TITLE
Unable to clone site

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13820]
We're currently getting errors when trying to copy an entire site. The site seems to be cloned but in fact it's missing content.

## Expected Behavior
System should be able to clone a site successfully.

## Current Behavior
Site is not being cloned.

## Steps to Reproduce (for bugs)
1-Set up a push publish environment in the sender and receiver server
2-To verify if the site is cloned successfully, in the sender add a few file assets inside any folder or in the root
3-Now in the sender, navigate to System>Sites. Hit Add Site button> Copy an existing site> Next. Choose demo.dotcms.com and hit next
4- Check the logs for the error. 
https://gist.github.com/shaydotcms/67cb812a35f8b246b7df2241496e3bd0
5- The site name is showing in the UI but it's not properly cloned, the file assets you added in the original site(demo) are missing.

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Firefox v57.0.4
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by nollymar** [comment]
The initial trace is not showing anymore. Now, it's failing with this error: https://gist.github.com/nollymar/8ecae5846c378f80aae4874dde643f51

**Comment by jgambarios** [comment]
Tika parse error fixed in https://github.com/dotCMS/core/issues/13482#issuecomment-377741879

**Comment by bryanboza** [comment]
Fixed, now we are able to clone sites without this error, tested in the last master code
