### ISSUE TITLE
Does dotCMS project support jdk 9 ?

### ISSUE THREAD

**Issue by Anhong2008** [dotCMS/core#13832]
Does dotCMS prject support jdk 9 ? I tried jdk 9 to run gradle build task with gradle 4.5, it failed with errors. But when i use jdk 8 instead, it build successfully.
The failed information as below:

:compileAspect [ant:iajc] .\DotCms\core\dotCMS\src\main\java\com\dotcms\csspreproc\CSSPreProcessServlet.java:37 [error] The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files [ant:iajc] public class CSSPreProcessServlet extends HttpServlet { [ant:iajc] ^^^^^^^^^^ [ant:iajc] .\DotCms\core\dotCMS\src\main\java\com\dotcms\csspreproc\CSSPreProcessServlet.java:40 [error] Syntax error, annotations are only available if source level is 1.5 or greater [ant:iajc] @Override [ant:iajc] ^^^^ [ant:iajc] [ant:iajc] 2 errors :compileAspect FAILED

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by jdotcms** [comment]
Hi @Anhong2008 
We are currently using Java8 and we have tested our build process on that version.
However it should work on Java9, I would recommend to check the AspectJ version and see if there is an upgrade for java9
Thanks,
J
