### ISSUE TITLE
Add CRUD operations for Workflow actions in the WorkflowResource

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13839]
Add the missing CRUD operations for the Workflow actions into the `com.dotcms.rest.api.v1.workflow.WorkflowResource`
Keep the back-compatibility with the current ajax and reuse the current code to do the resource by using the helper.

---
The place where the current ajax operations to be reuse/migrate are in this folder:
https://github.com/dotCMS/core/tree/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/ajax

--
Please remember that all the operations that change some how a workflow, steps and actions needs to meet these conditions:

1. The user have access to the Workflow portlet
2. The user have the proper license level for workflows
Without those two conditions modifications should not be allowed.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13908

**Comment by bryanboza** [comment]
Fixed, some new improvements reported here: #13964
