### ISSUE TITLE
Hide workflow scheme names in actions if content already in a scheme

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13834]
We are showing the 

> action.name (scheme.name)

everywhere.  We should only show the scheme.name if 
1. the action is not in a workflow AND
2. the action has multiple schemes.

**Comment by wezell** [comment]
We need to do more and hide the scheme on the right click menus too.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14268

**Comment by bryanboza** [comment]
Fixed, tested on master and now looks better, nice improvement
