### ISSUE TITLE
Workflow action fails and causes content to become unindexed

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#13844]
On our authoring server, when you take a workflow action on a Documentation content item, and the workflow action includes any sub-action to push publish the content, the push fails and the content is un-indexed (no longer showing in the Tasks or Content Search screens, and requiring multiple re-indexes for the content to re-appear).

Note that a direct push publish using the default actions (by right-clicking the content in the Content Search screen and selecting "Push Publish") works, so this is only a problem with pushing from the workflow.

## Expected Behavior

Since the default push works, the push from the workflow should also work.  Even if the push from the workflow fails for some reason, it should **NOT** un-index the content when it fails.

## Current Behavior

Taking any workflow action which includes the "Push Publish" or "Push Now" sub-actions both:

* Fails to successfully push the item.
* Causes the content item to be un-indexed.

## Known Workarounds

Push content using the default action (e.g. right-click on the content item in the Content Search screen and select "Push Publish").

## Steps to Reproduce (for bugs)

1. Log on to the dotCMS authoring server.
2. Go to the Content Search screen.
3. Create a new content item of the Documentation content type.
    * Enter value for all required fields, and copy the "URL Title" value to the "Wiki Title" field.
    * Select "Save Draft" to save the content.
4. From the Content Search screen, click the new content item to re-open it in the content editing screen.
5. Select the "Publish & Push" action.
    * Leave all fields in the push publish popup at the default - just add the "dotcms.com" push environment and press the "Push" button.

**Result:** The new content item disappears from the Content Search screen.

## Context

Currently the only way we can successfully push documentation content from auth to prod is by using the default "Push Publish" action (e.g. right-click on the item in the Content Search screen).  So our workflow is broken.

Will believes this may be a bug in the API, which means it's potentially urgent.

## Notes

* Workflow sub-actions which come *before* the push sub-action work correctly.
    * I don't know if any workflow sub-actions which come *after* the push action work or not - I haven't tried adding any after the push sub-action yet.
* I haven't yet tried to recreate this on a server other than our authoring server.
* This doesn't appear to be a problem with a corrupted workflow.
    * I re-created the workflow from scratch, but the problem still happens.
* This might potentially be an issue with a corrupted push env (I didn't try recreating the push env yet).
    * But the push env works fine with a default action push (right-click "Push Publish").
    * And the push env worked fine before the 4.3.x release.
    * And finally even if the push env got corrupted somehow, it still obviously shouldn't cause the content to be un-indexed.
* This is a new problem.
    * I believe it just started happening with the 4.3.x upgrade, but can't be 100% sure of the timing.
* There is a potentially related issue that, after a content item is un-indexed, it takes **at least** two re-indexes to get the item to show up again in the back-end.
    * Most of the time a full re-index followed by a re-index of only the Documentation content type makes the content come back.
    * However at least once it has required a full re-index, followed by a re-index of the content type, followed by another full re-index before the content appeared in the Content Search screen again.

## Your Environment

* dotCMS version used: 4.3.2
* Operating System and version: AWS Linux (auth)
* Application Server and version: Tomcat 1.8 (distro)
* Java Brand and version: 1.8 (auth)
* Database and version: Postgres (auth)

**Comment by dsilvam** [comment]
Note to QA: Replicate the scheme of 'Document' content type, make sure you have a Push now actionlet, and after executing the workflow, make sure the content is searchable via content search screen

**Comment by shaydotcms** [comment]
Passed QA
Tested on master branch / Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
