### ISSUE TITLE
Elasticsearch: index replicas set incorrectly and index health broken with no license

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#13849]
On a clean startup with no license (community edition), the index replicas are set incorrectly to "1" (should be zero for a single cms node), and the index health does not work (returns error when you click on it).

https://imgur.com/a/QWBBg

**Comment by dsilvam** [comment]
@chrismccracken did you check that `AUTOWIRE_CLUSTER_ES=true` ? and `AUTOWIRE_MANAGE_ES_REPLICAS` is either _true_ or commented out (defaults to _true)?

**Comment by dsilvam** [comment]
Will be solved in: https://github.com/dotCMS/core/issues/13900

**Comment by nollymar** [comment]
This PR fixes the error when clicking on the index health: https://github.com/dotCMS/core/compare/issue-13849-index-replicas-set-incorrectly-and-index-health-broken-with-no-license?expand=1

**Comment by shaydotcms** [comment]
Passed QA
Using community edition(no license) index replicas are set to "0" for a single cms node and index health shows appropriate data when clicking on it.
![image](https://user-images.githubusercontent.com/8741846/37860561-382384a6-2eed-11e8-9757-750144055934.png)

Tested on Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
