### ISSUE TITLE
Add more that one container into a box makes the edit page renders incorrectly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13840]
As a User I want to be able to add more than one container in a box of a page and add content that renders as expected.

## Expected Behavior
It should align all the containers inside the box correctly.

## Current Behavior
1. https://cloudup.com/c0ua5qtQCWj

## Possible Solution
This should be fixed in plain css.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Create or edit a page
2. Edit the layout or template
3. Add more containers in the same box
4. Go to the edit page

## Acceptance Criteria

1. Make sure that all containers in the box are correctly aligned in the rendered page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we are able to add multiple containers per box, new card created here: #13977

**Comment by fmontes** [comment]
Needs to double check this with the new bootstrap in the theme
