### ISSUE TITLE
Research to create templates portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13843]
So we need to build the template portlet, listing and edit a template.

1. Do we have an endpoint or api with pagination support to get the templates?
    - To build the template listing
2. Do we need an endpoint to get the ```template``` by id?
3. Do we need an endpoint to update the template?
4. Do we need something else?

**Comment by freddyucv** [comment]
We need create a new end point to listing templates with pagination, using the new response's format like this one:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResource.java#L311

... and a new component using the 'dot-listing-data-table' to listing these templates, like this:

https://github.com/dotCMS/core-web/blob/master/src/app/portlets/content-types/main/content-types.component.html

currently the templates listing allow filter by archived but the 'dot-listing-data-table' componente don't allow something like 'custom filters', so maybe we should extends this component.

**Comment by freddyucv** [comment]
"Do we need an endpoint to get the template by id?"

Yes, we need one.
It could return almost the same response that the renderHTML end point but without the render and viewAs attributes (we don't need them for the edit the template).

We need do a refactoring and move some method from the PageResourceHelper class to a API, each Helper has a one to one relationship with a end point and we'll need reuse some method define into de PageResourceHelper into the TemplateResource.

We need add a new routing for the DotEditLayoutComponent In Angular  and create a new resolver.

**Comment by freddyucv** [comment]
Do we need an endpoint to update the template?

Yes, we need create a new end point almost like this one:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java#L339

but without use the page uri, the new end point has to use the template inode (or identifier), the url should be something like:

POST: /v1/template/:id

the body must content the layout and template object attributes:

{
    template: ...,
    layout: ...
}

(Maybe we could have two end point one to template and another one to layout.)

We need a place to set the template properties values:

<img width="1145" alt="screen shot 2018-03-13 at 07 55 29" src="https://user-images.githubusercontent.com/10408015/37345029-953926dc-2691-11e8-99b6-e93140d2e66f.png">

After we choose where set the template's properties then we can know if we need one or two end points to update the template by id.

Al so we need switch if save the template with the current pageViewService or if save it with the new end point, here:

https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/layout/dot-edit-layout-designer/dot-edit-layout-designer.component.ts#L119

maybe we just need to do something like:

`
if (this.pageState.page.identifier) {
    this.pageViewService.save(this.pageState.page.identifier, dotLayout).subscribe(...);
} else {
   this.templateService.save(..., dotLayout).subscribe(...);
}
`

**Comment by freddyucv** [comment]
We should move all the dot-edit-layout.module, because it is into dot-edit-page it have to be more independent. I dont know if maybe we have to rename all the dot-edit-layout.module.

**Comment by fmontes** [comment]
@freddyucv that's why I created this one: https://github.com/dotCMS/core-web/tree/master/src/app/portlets/dot-edit-page/layout/dot-edit-layout-designer/components/dot-layout-designer
