### ISSUE TITLE
[WebDAV] Error in logs using Finder when you upload a file containing "+" sign in its name 

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#13842]
When you upload a file through Finder containing "+" sign in its name, the file is successfully uploaded but it throws errors in the logs.
https://gist.github.com/shaydotcms/8a4b279fc529b256784e18732a78e0b4

Finder says: "The Finder can’t complete the operation because some data in “Postgres+copy.xml” can’t be read or written.
(Error code -36) "

When the file name contains another character such as "$", "&", " ", etc..., it does upload the file without errors.

## Expected Behavior
Uploading files whose name contains "+" signs to dotCMS from Finder should not through errors in the logs.

## Current Behavior
There are error in logs using Finder when you upload a file containing "+" sign in its name. 
"The Finder can’t complete the operation because some data in “Postgres+copy.xml” can’t be read or written.
(Error code -36) "

## Steps to Reproduce (for bugs)
1. Open a Finder window and navigate to Go> Connect to Server
2. Use server address http://localhost:8080/webdav/live/1 then sign in with dotcms credentials
3. Upload a file containing "+" sign in its name using Finder
4. You will get an error message:
https://gist.github.com/shaydotcms/8a4b279fc529b256784e18732a78e0b4

## Your Environment
* dotCMS version used: master branch
* Database and version: Postgres 9.6.6
* Operating System and version: Mac OS 10.10.5
* Browser Name and version: Chrome v64
* Application Server and version: Tomcat 8
* Java Brand and version: Java 8

**Comment by jcastro-dotcms** [comment]
Related to https://github.com/dotCMS/core/issues/13603

**Comment by shaydotcms** [comment]
Duplicate of https://github.com/dotCMS/core/issues/13824
