### ISSUE TITLE
Changes to Save actions should be independent between Workflow Steps

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13851]
Changes to Save actions should be independent between Workflow Steps.

Regardless of whether the save action was copied or created new, changes to one save action should not be changing save actions in other worklow steps.  Right now, the bug is that changing the New, Published, Unpublished, Archived, All for an action changes all of the save actions in all of the steps of the System Workflow.

![saveerror](https://user-images.githubusercontent.com/1569167/37311494-0a477e9a-260d-11e8-88b3-43e41722513f.png)

This is incorrect behavior.

Video: https://www.screencast.com/t/TzkSePnE

**Comment by jgambarios** [comment]
@DeanGonzalez Now we have the ability to re-use actions between steps (global actions) so this is not as bug as you are actually re-using the same action, if you need an action that behaves differently between steps a new action should be created on each step.

**Comment by DeanGonzalez** [comment]
Just Discussed with Jonathan and Jason, - we need something in the UI that shows that all the actions are linked together, so that accidental permissions, changes are not made in sweeping ways without the user understanding them... but that will be another different ticket to follow up this

**Comment by wezell** [comment]
This is expected behavior.  I believe once you understand this, it will be more natural
