### ISSUE TITLE
add mime types for fonts

### ISSUE THREAD

**Issue by dotjorgeu** [dotCMS/core#1385]
saw this in chrome

Resource interpreted as Font but transferred with MIME type application/octet-stream: "http://localhost:8080/css/fonts/JosefinSlab-SemiBold-webfont.woff".

make sure update in the upcoming tomcat7 branch issue-1088-upgrade-tomcat

**Comment by oarrietadotcms** [comment]
Here are my findings:

- Right now we are using tomcat's default mime-mapping for woff. ([dotcms](https://github.com/dotCMS/tomcat/blob/8.0.18/conf/web.xml#L4242-L4245) and [tomcat](https://github.com/apache/tomcat/blob/trunk/conf/web.xml#L4316-L4319))
- The [standard mime-mapping for woff](https://www.w3.org/TR/WOFF/#appendix-b) is different than the one tomcat has. 
- [Chrome right now supports both mime-mappings](http://zduck.com/2013/google-chrome-and-woff-font-mime-type-warnings/). No error is displayed on the browser or server logs.

@brentgriffin @wezell Please let me know if you want to update tomcat's default with the standard from w3 but I don't think is necessary.

**Comment by brentgriffin** [comment]
@oarrietadotcms how do the other browsers handle it?  Firefox, Safari, Edge, IE, and Opera

**Comment by oarrietadotcms** [comment]
I tested our demo site in Chrome, Safari and Firefox: No problem at all. But I focused on the error message in Chrome, as reported.

**Comment by jgambarios** [comment]
Closed as nothing to do here.
