### ISSUE TITLE
Edit step errors on Workflows

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13859]
We are having two errors after the new redesign of workflows 

- [ ] When you enable the "**enable schedule**" box, the system shows two more additional fields, if you enable and save it,  when you try to open this box again we are not showing this fields, then if you try to disable this property, the system is cutting off the Save button 

SC: https://screencast.com/t/SGhoiFqzd

- [ ] If you try to "enable schedule", and you don't have steps in the workflow, the system is showing a DB failure error, we need better handle of this error 

SC: https://screencast.com/t/Ioq3hbHq

## Steps to Reproduce (for bugs) 
1. Login as admin
2. Create a new workflow 
3. Add a new action to this WF
4. Now try to edit the workflow and select the "enable schedule" field
5. Save and close the edit window
6. Try to edit again, and disable this property

## Your Environment
Tested on the last master code  // FF

**Comment by jgambarios** [comment]
Unable to reproduce

**Comment by bryanboza** [comment]
Fixed, after the last changes we are unable to reproduce
