### ISSUE TITLE
Elastic Search error upgrading from 2.x instance 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13866]
When you try to upgrade your instance coming from a 2.x version we are having a ES error 

## Expected Behavior
We need be able to upgrade without problems 

## Current Behavior
We have this error in the dotcms.log file 
SC: https://gist.github.com/bryanboza/4481cbab6dca0acc378a11867fb1ac5c

## Steps to Reproduce (for bugs)
1. Start a dotcms 2.x instance 
2. Configure your master instance to use the same database and assets 
3. Star the last master instance 
4. Check your dotcms.log file 

## Your Environment
Tested upgrading from 2.5 instance to master // postgres

**Comment by wezell** [comment]
A reindex is required when moving to 5.0
