### ISSUE TITLE
[Content Management] Updating a content messes up existing M-N relationships

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13862]
## Expected Behavior
M-N relationships and related contents should be respected on any programmatic update of contents.

## Current Behavior
Related contents given a content we're updating are not save dproperly once this content is being updated programmatically using this Checkin call 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/ContentletAPI.java#L1087 

This is true for M-N relationships where Parent and Child content types are the same content type.

## Possible Solution
N/A.

## Known Workarounds
Edit the content using a different checkin call or through the UI.

## Steps to Reproduce (for bugs)

1. Create a Test Content Type with only Two fields: Title (Text) and Description (Text area)
2. Create a M-N relationship with this same Content Type as Parent and Child content types.
3. Create at least 5 contents under this content type.
4. For one of the contents you create, relate 2 different contents as parent contents, and 2 other contents as children contents. The relationships tab should look like this.

<img width="1237" alt="screen shot 2018-03-14 at 8 55 52 am" src="https://user-images.githubusercontent.com/1717110/37407010-ad06b95c-2766-11e8-8ed3-ef52c63f4b77.png">

5. Once it's saved and published, deploy this OSGi plugin. https://github.com/dotCMS/com.dotcms.plugin.content.update 

6. Send a curl command like the following, indicating you're updating the content with multiple related contents (parent AND child).

```
$ curl -u admin@dotcms.com:admin -v -XPUT -H "Content-Type: application/json" -d '{"field":"title","value":"Title 0003 Updated","query":"+identifier:1d709690-8e15-4533-9246-62f66948e979  +languageId:1"}' http://localhost:8080/api/contentUpdate/update/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* Server auth using Basic with user 'admin@dotcms.com'
> PUT /api/contentUpdate/update/ HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 120
> 
* upload completely sent off: 120 out of 120 bytes
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=DE29B5F29D0A906A4E9D805DA23F01EB; Path=/; HttpOnly
< Access-Control-Expose-Headers: Authorization
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< Access-Control-Allow-Headers: Authorization, Accept, Content-Type, Cookies
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
< Content-Type: application/json
< Content-Length: 120
< Date: Wed, 14 Mar 2018 13:57:37 GMT
< 
* Connection #0 to host localhost left intact
{"failures":[],"success":[{"inode":"65d7f691-8268-4425-ac18-763e32230f7b","id":"1d709690-8e15-4533-9246-62f66948e979"}]}
```

Once you open the content, relationships look like this: 

<img width="1231" alt="screen shot 2018-03-14 at 8 57 50 am" src="https://user-images.githubusercontent.com/1717110/37407086-db484b5a-2766-11e8-9f5e-e58cf2d023c6.png">

## Context
In spite the plugin helps to reproduce this issue, the problem here is not related to plugin's inner logic, but it's more related to this Checkin call 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/ContentletAPI.java#L1087 

The relationships are not a mandatory param, and should be retrieved automatically once this call is made, however, for M-N relationships, the system does not have a smart way to check if related contents are parent OR child. Therefore, the relationships tree for the content we updated gets broken after the content is programmatically updated using ths checkin call. 

Reproduced by customer:

https://dotcms.zendesk.com/agent/tickets/95437

## Your Environment

* dotCMS version used: 4.2.0, 4.3.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any supported application version.
* Java Brand and version: Any Java 8 Version.
* Database and version: Any supported DB engine.
* Application module (if apply): See related plugin, which makes the process of reproducing this issue easier.

# Acceptance

- [ ] Insure behavior is still broken in 5.0
- [ ] Insure that this behavior only happens with relationships of a content type to itself
- [ ] Find out if there are api based issues that need to be fixed - not based on the plugin
- [ ] Integration test

**Comment by levosgien** [comment]
https://dotcms.zendesk.com/agent/tickets/95437
https://dotcms.zendesk.com/agent/tickets/95591
