### ISSUE TITLE
Tika error pushing an entire site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13874]
We have a tika error trying to read data from the XML file 

## Expected Behavior
We need be able to push sites without problems 

## Current Behavior
We have a tika error in the process 
LOG: https://gist.github.com/bryanboza/d5c86e0010bdf673523135bb8bc3e8f0

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your push environment 
3. Create a copy of demo site
4. Try to push this site 

## Your Environment
Tested in the last master code // postgres // FF

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/13482

**Comment by bryanboza** [comment]
Fixed, unable to reproduce with the last changes of master
