### ISSUE TITLE
Tags not saving when editing content

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13872]
When editing a piece of content that has a tag field, the tags are not being saved. This only happens on editing an existing piece of content. It works only the first time.

## Expected Behavior
Editing content should preserve its tags

## Current Behavior
Editing content makes tags to go away

## Steps to Reproduce (for bugs)
1. Create content type with tag field
2. Create piece of content of that type, assigning a tag or more (Tags should be persisted)
3. Edit the piece of content and click Save&Publish again. Tags will be gone after this.

**Comment by shaydotcms** [comment]
Passed QA. 
After modify the content, the tags were persistent.
Tested on master branch / Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
