### ISSUE TITLE
Unable to execute any workflow action importing content if don't have the save as sub action

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13889]
Part of the new changes in the card #12676, is now we are able to execute actions directly when you are importing content. but we are unable to execute any nothing if the selected action don't have the save as sub-action. 

## Expected Behavior
If you are importing content that does not exist yet, we should try to execute the action and fail, but if the content exist, we need make sure we apply this action and update existing the contents. 

## Current Behavior
We detect the contents already exist and say that will update, but if the action don't do the (save) we are not updating the existing ones

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content types with 2 text fields (ID: https://screencast.com/t/yNr3O36IxL ,  and Name: https://screencast.com/t/lIxPFThdimO )
3. Add some pieces of content 
4. Export the all the content of the content type 
5. Now edit the csv file and make some changes to the name field 
6. Try to import the content but execute some action without save 

With unpublish: https://gist.github.com/bryanboza/9b697746cc6e4b387b1c5eba877bc4fe
With archive: https://gist.github.com/bryanboza/3d7bc85e838f2e17a2dc9d3e27951a98

## Your Environment
Tested in the last master code // postgres // FF

**Comment by oswaldogallango** [comment]
Now the import contents accept workflow actions on the CSV, files those actions ids could be regular ids or shortyIds. Here is an example of how the csv file with workflow actions Ids should look like: https://gist.github.com/oswaldogallango/93216fbeb6d6f787ba4c5cab8280f9e2

Also the logic works like this:

Import Content validations on import content

1. Check if the wfActionId header is included in the CSV headers.
1.a If it's set wfActionId do a findActionRespectingPermissions to validate that the user have permission.
1.b.1 If the user can get the action then fire the workflowAction for that content.
1.b.2 If the user can't get the action then go to 2.

2. If the wfActionId isn't set in the CSV, then check if it's set on the workflowForm dropdown.
2.a If it's set wfActionId on the dropdown do a findActionRespectingPermissions to validate that the user have permission.
2.b.1 If the user can get the action then fire the workflowAction for that content.
2.b.2 If the user can't get the action then go to 3.

3. If the wfActionIf isn't set or the user doesn't have permission to get it then execute the old checking

**Comment by oswaldogallango** [comment]
P. R https://github.com/dotCMS/core/pull/14094

**Comment by wezell** [comment]
Does this work with Shorties?

**Comment by wezell** [comment]
We need to remove the required from the dojo field - if there is no actionId then it will just save

![screen shot 2018-04-17 at 4 42 28 pm](https://user-images.githubusercontent.com/934364/38895639-91ff96c0-425e-11e8-974f-d85981ce1d73.png)

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/14159

**Comment by oswaldogallango** [comment]
Yes, this accept actions using shorties and/or regular UUID's

**Comment by bryanboza** [comment]
After retest this stuff, I am able to reproduce some unexpected errors trying to use some of the available actions: 
Here the logs: 
https://gist.github.com/bryanboza/c9eab8b99940e16b5475c2ace43cefef
https://gist.github.com/bryanboza/1f523a1ff15c414e7b0322e6ceeea081

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14319

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14319

**Comment by bryanboza** [comment]
New related enhacement here: #14373

**Comment by bryanboza** [comment]
We still showing the success message also when the process is failing

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14376

**Comment by jdotcms** [comment]
I have created a new content type with two text fields.
Then created 4 of them.
Then did an edit to all of them adding prefix 'xxx' and 'yyy'
Then import the new file with a non-save action
Checked the log: it is ok
Checked the content: it is ok

**Comment by jdotcms** [comment]
![Screen Shot 2018-05-11 at 4.45.58 PM.png](https://images.zenhubusercontent.com/577bcb78bf93871ccd9d9591/e4ecc8f3-5b7f-469a-9e8a-0ad7e787cd34)

![Screen Shot 2018-05-11 at 4.46.07 PM.png](https://images.zenhubusercontent.com/577bcb78bf93871ccd9d9591/a48ec01f-b1fe-4e34-88a4-8e0865390c03)

![Screen Shot 2018-05-11 at 4.46.14 PM.png](https://images.zenhubusercontent.com/577bcb78bf93871ccd9d9591/e9451aa0-74ea-4a10-8875-e2e9470d5b35)

**Comment by bryanboza** [comment]
Fixed, now we have a better import process.. We create new enhancements in a new card
