### ISSUE TITLE
Content types: [Violation] 'click' handler took XXXms and auto focus add to bundle dropdown

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13880]
As a user I want clicks happen immediately.

## Expected Behavior
When something is clicked, action should happen immediately.

## Current Behavior
When something is clicked it took +300ms to emit the action and there is a warning in the console.

## Possible Solution
This is happening because we have [menu component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/action-menu-button/action-menu-button.component.html#L2) for each row in the listing.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Apply license
3. Go to content type and open console
4. Click on something like the ... in any row, see the warning and how long it takes to exec the click

## Acceptance Criteria

1. Get rid of the warning in the browser
2. Make sure clicks happen immediately
3. In add to bundle dialog make the focus to be in the dropdown when it loads
    - @fmontes: I think thet autofocus attr is not working because of this slowness.
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by fmontes** [comment]
I worked on this and I think the only solution will be create our own custom menu component for this.

**Comment by alfredo-dotcms** [comment]
QA: the AC #3 is not implemented, and the options menu is always openned

**Comment by bryanboza** [comment]
Fixed, this is working better now, tested on master // Postgres // FF
