### ISSUE TITLE
Remove leftover usages of CLUSTER_AUTOWIRE

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13890]
This property was replaced by the more granular ones `AUTOWIRE_CLUSTER_ES` and `AUTOWIRE_CLUSTER_TRANSPORT`, but it is still referenced (default to _true_) in a couple of JSPs and a doc. 

JPSs:
index_stats.jsp
site_search_index_stats.jsp

Doc:
https://dotcms.com/docs/latest/configuring-an-external-elasticsearch-server#Both9
https://dotcms.com/docs/latest/configuring-an-external-elasticsearch-server#ExternalOnly9

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13904

**Comment by DeanGonzalez** [comment]
Documented and pushed
