### ISSUE TITLE
Need refresh the complete page to use workflows in content types portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13903]
To allow use workflows in your instance we need have a EE license, but after apply this, we need refresh the complete changes to enable this feature

## Expected Behavior
After apply the license we need be able to use any EE feature 

## Current Behavior
We need refresh the browser to enable the workflow field in content types
SC: https://screencast.com/t/clg7SkbpnkOv

## Possible Solution
We need to update [this service](https://github.com/dotCMS/dotcms-js/blob/7d6c0864b4d026cecbb98cbd364785559edbbacd/src/core/dotcms-config.service.ts) **in dotcms-js** when a license is applied, we might required a websocket event that tells us that the license was applied.

## Acceptance Criteria

1. Create a license service:
    - Url: v1/appconfiguration
    - Get only license object
2. Use the license service to check options in the content type listing
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by fmontes** [comment]
AC 2 needs to be done.
