### ISSUE TITLE
When deleting the last Action/Step relationship delete the global action

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13917]
Right now the delete button for actions on each step is deleting just the relationship between actions and steps but the action itself is never deleted.

![Actions](https://camo.githubusercontent.com/16e8bddefb94f886ec6f604f75a7c822c70e3420/68747470733a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f6a67616d626172696f732f666f6c646572732f536e616769742f6d656469612f30363132656461392d346431382d343764372d393762302d3762333439656561356561362f323031382d30322d32385f31322d32322d31332e706e67)

## Expected Behavior
When deleting the last action relationship we need to also delete the action itself.

## Current Behavior
The global action is never deleted.

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres // FF
