### ISSUE TITLE
We need improve the messages to required fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13916]
After test the card #13721 , we have a weird message when you try to save a new piece of content without select any of the values in a required filed 

## Expected Behavior
We need validate the required fields and send an error with the name of the field. This to indicate the end user which of the fields is having problems 

## Current Behavior
We just send a message that you has an invalid field, and we have the error on log, this because the error comes from BE
SC: https://screencast.com/t/6q79e9OHh

## Possible Solution
We need define if we need validate this from front-end, or if we need catch the error from backend to show an error message 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content types with 2 fields (Text: Name, Checkbox: Test1) make sure the checkbox is required
3. Try to add a new piece of content 
4. Leaving the Test1 field without selection try to save 

## Your Environment
Tested in the last master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14100

**Comment by bryanboza** [comment]
Fixed, now we are able to see the name of the fields in the message
