### ISSUE TITLE
Reload workflow actions when user lock or unlock the page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13926]
As a User I want to be able to fire all the workflows actions I have available.

## Context
Workflows actions available for a user can be different if the contentlet is locked or unlocked.

## Expected Behavior
When a user toogle the page lock, the workflow actions should be refreshed.

## Current Behavior
When a user toggle the page lock nothing happen in the workflow actions dropdown.

## Possible Solution
Implement ```ngOnChanges``` in the workflow action selector component and make the request there? Maybe, but if the inode didn't change will the ```ngOnChanges``` trigger?

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Lock or unlock the page
4. The workflow actions selector have the same options

### Acceptance Criteria
1. Workflow action lists should update when the lock/unclock the page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed now we are reloading the action list

**Comment by bryanboza** [comment]
Fixed, tested on master // MySQL // FF
