### ISSUE TITLE
Import/Export workflow UI

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13920]
As a continuation of the work made in https://github.com/dotCMS/core/issues/13875 we need to add to the UI in the Workflows listing portlet an option to Import a Workflow and to the edit Workflow portlet an option to Export it.

![import](https://user-images.githubusercontent.com/923947/37716054-2f8a830a-2ce3-11e8-8d89-7fc5cf3c72b0.png)
---
![export](https://user-images.githubusercontent.com/923947/37716052-2f32d3bc-2ce3-11e8-8b9e-e79ceff3dece.png)

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/14157

**Comment by jdotcms** [comment]
For this errors you can get the header error-message

**Comment by jdotcms** [comment]
@bryanboza 
I have tried to import a scheme with shorties and it is working
<img width="526" alt="screen shot 2018-04-22 at 11 52 05 pm" src="https://user-images.githubusercontent.com/19578350/39109049-706f959a-4688-11e8-9dc0-f9ff31a23e99.png">
<img width="1112" alt="screen shot 2018-04-22 at 11 51 58 pm" src="https://user-images.githubusercontent.com/19578350/39109050-708cac0c-4688-11e8-80d2-320b75b5db28.png">

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/14184

**Comment by bryanboza** [comment]
We need some style improvements in case of some errors, 
Example: If you try to import some file that does not have the json format: 
![case1](https://user-images.githubusercontent.com/2641437/39215296-934d5a5a-47d4-11e8-9520-75016e9e3152.gif)

**Comment by jgambarios** [comment]
I'm having errors importing a Workflow https://gist.github.com/jgambarios/52f742af5ac5bd291afe6c218186343c

1. Select a Workflow and exported
2. Import the exported file
3. Fails

Multiple problems here:
1. The import fails
2. The error handling and display to the user

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14369

**Comment by bryanboza** [comment]
Fixed, now this is working as expected. New security enhancement here #14380
