### ISSUE TITLE
Include ability for clustered implementations to specify whether a reinit is needed or not

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13923]
Currently,  when a scaling down/up, a reinit of the transport happens no matter what. 
The idea is to allow each implementation to tell whether a reinit is needed or not.

I would like to scale mu cluster without forcing a reinit of my transport layer.

The same is true for elasticsearch.  We should not reinit if autowire is off

Story Owner: @chrismccracken

**Comment by wezell** [comment]
@chrismccracken is this still true?  With the changes here #14304 , is this still needed?

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14620

**Comment by wezell** [comment]
@chrismccracken @brentgriffin can you all please let us know if this works ?

**Comment by wezell** [comment]
Passing without feedback from @chrismccracken
