### ISSUE TITLE
dotCMS Cache problems editing workflows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13929]
We have a cache error when you are editing some workflow scheme, this because we are not deleting the previous version from cache. 

## Expected Behavior
We need update this content in the cache when you save the changes 

## Current Behavior
We are not deleting the content from cache and for example: 

If you archive some content and then you try to get the schemes of the content type via REST, we are getting the scheme with the archived property in false 

## Steps to Reproduce (for bugs)
1. Create a new Workflow 
2. Associate this workflow to some content type  
3. Via REST try to get all the schemes of this content type using this rest:  ` http://localhost:8080/api/v1/workflow/schemes/schemescontenttypes/{contentTypeId}`
4.  Go via backend and archive this scheme
5.  Made again the same call to the rest 

## Your Environment
Tested in the last master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13930

**Comment by bryanboza** [comment]
Fixed, tested on master and now we invalidate the cache when you save changes in the schema
