### ISSUE TITLE
Update ES replica management for ES 6.x

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#13927]
Elasticsearch replica configuration is no longer possible at the ES cluster or node level, and must be set on the index itself at create time or after creation. This requires altering some replica mgmt patterns in autowire and index management classes.

**Comment by dsilvam** [comment]
After meeting with @chrismccracken and @nollymar, agreed changes are:

Introduce new property called `ES_INDEX_REPLICAS` which will replace `AUTOWIRE_MANAGE_ES_REPLICAS` and any other replica properties currently used.
Possible values for `ES_INDEX_REPLICAS` will be:
* “autowire”
* integer value (e.g. "2") (fixed value, this one sets auto_expand_replicas=false)
* “0-all” (or any other boundary) ( this one sets auto_expand_replicas=true, and sets this boundary)

A combination of AUTOWIRE_CLUSTER_ES=false && ES_INDEX_REPLICAS=autowire does not make sense and won't work. 

if `ES_INDEX_REPLICAS` is not specified, the default value would depend on whether `AUTOWIRE_CLUSTER_ES` is `true|false` like the following:
Default to `autowire` if `AUTOWIRE_CLUSTER_ES=true`
Default to `1` if `AUTOWIRE_CLUSTER_ES=false`

**Comment by nollymar** [comment]
Doc to be updated:
https://dotcms.com/docs/latest/auto-clustering-configuration#ReplicaManagement
https://dotcms.com/docs/latest/managing-site-indexes-with-elasticsearch#Replicas
https://dotcms.com/docs/latest/manual-cluster-configuration#step-3-index-elasticsearch-cluster
https://dotcms.com/docs/latest/manual-cluster-configuration#number-of-replicas-for-the-content-index
https://dotcms.com/docs/latest/restful-api-to-manage-indexes#UpdateReplica
https://dotcms.com/docs/latest/configuring-an-external-elasticsearch-server

**Comment by DeanGonzalez** [comment]
https://auth.dotcms.com/docs/latest/auto-clustering-configuration#ReplicaManagement - Done
https://auth.dotcms.com/docs/latest/managing-site-indexes-with-elasticsearch#Replicas - Done
https://auth.dotcms.com/docs/latest/manual-cluster-configuration#step-3-index-elasticsearch-cluster - Done
https://auth.dotcms.com/docs/latest/manual-cluster-configuration#number-of-replicas-for-the-content-index - Done
https://auth.dotcms.com/docs/latest/restful-api-to-manage-indexes#UpdateReplica - Done
https://dotcms.com/docs/latest/configuring-an-external-elasticsearch-server - Done
