### ISSUE TITLE
FE: Edit Layout feature is EE only

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13938]
As a stakeholder I want to make sure that only EE DotCMS instance can't edit layouts of the page

## Expected Behavior
When DotCMS instance is not EE we should disabled the "Layout" button from the right sidebar in edit page.

## Current Behavior
Edit page UI is not checking if a DotCMS instance is EE or not.

## Possible Solution
Need to update the model of the toolbar with the EE information and add the primeng tooltip component to the toolbar as well.

We can use ```levelName``` from the license property when we do: ```this.dotcmsConfig.getConfig()```

## Known Workarounds
N/A

## Zeplin
https://zpl.io/VxBq6JE

#### Disable button
![menu](https://user-images.githubusercontent.com/751424/37782135-c91e015c-2db7-11e8-8f85-08c8ad8510e6.png)

#### Disable button hover
![menu 2](https://user-images.githubusercontent.com/751424/37782148-d1d049ae-2db7-11e8-859c-9b9e3e69e8a1.png)

## Acceptance Criteria

1. Match the design
2. Show disable layout button with tool when no EE license is in the instance.
3. Check in the resolver so user can't access to the ```/layout``` if no EE license is set.
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by alfredo-dotcms** [comment]
According to Will, this is enabled starting on `Standard` level 200.
```
COMMUNITY("COMMUNITY EDITION", 100),
  STANDARD("STANDARD EDITION", 200),
  PROFESSIONAL("PROFESSIONAL EDITION", 300),
  PRIME("PRIME EDITION", 400),
  PLATFORM("PLATFORM EDITION", 500);
```

**Comment by bryanboza** [comment]
After test, we need refresh the complete browser to see the changes after apply the license, the same thing if you remove the license this still available until you refresh the browser
