### ISSUE TITLE
Need show the complete Id in the workflow actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13940]
If you are editing a workflow action, right now we are showing a shorty id, this is generating problems trying to use the resources because you need do the query directly in the database to get the real identifier. 

## Expected Behavior
We have two options here, 

- [ ] Show the complete id in the edit action window 

- [ ] Make the REST works with shorty Id 

## Current Behavior
From the UI we have just the shorty id, then to use the resource you need make the query directly in the DB
SC: https://screencast.com/t/Th5mbWQ8V

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to the workflow portlet 
3. Edit some action and copy the id 
4. Using the follow resource try to get this action 
 http://localhost:8080/api/v1/workflow/actions/{actionID}

## Your Environment
Tested in the last master code // postgres // FF

**Comment by wezell** [comment]
We need to actually change the resources to use shorties.  And as a rule, we should always use the shorty code to resolve almost any uuid we pass in.

**Comment by bryanboza** [comment]
Fixed, right now the REST end points are supporting shortly id's
