### ISSUE TITLE
Unable to edit workflow steps 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13948]
We have a 404 error message when you edit ay workflow step and try to save the changes 

## Expected Behavior
We should be able to edit workflow steps without problems 

## Current Behavior
We have a FAILURE http 400 bad request pop up and we are unable to save the changes
Also we have this error on logs: https://gist.github.com/bryanboza/dd088e4eca8f0587a17911575596a5eb

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to the workflow portlet 
3. Edito some scheme 
4. Try to edit some workflow step
5. Save it 

## Your Environment
Tested on master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13943

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres //  FF
