### ISSUE TITLE
Edit page content search should show results without filtering

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13946]
As a user I want to see results for content search as soon as possible.

## Expected Behavior
When you open the add/edit dialog in edit page we should show results of the search as soon as load, and refresh results when user manually filter.

Additionally, the results should incorporate the _all idea of the content search - where the list of content that comes back is not from a single content type but from all content types.

## Current Behavior
The search results only show when we click on the "search" button of the form.

## Possible Solution
Start here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/ng-contentlet-selector.jsp

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Open the add/edit dialog
4. See there is no results of the search on load.

## Acceptance Criteria

1. Add "All" to the content types dropdown
    - It should be selected by default
    - It should show results for all the contenttypes
2. Update the results when another content type is selected in the dropdown
3. It should work as the content search in the portlet: ```Content > Search``` (without the all option)
4. Match the design
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14006

**Comment by alfredo-dotcms** [comment]
this does not met AC #3, so when changed the dropdown the list should be updated without doing click on the button, as is in `Content -> Search`

**Comment by fmontes** [comment]
Needs backend change in the ```ContentletAjax.searchContentlets``` method. Branch: https://github.com/dotCMS/core/tree/issue-13946-fix-all-by-basetype

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now this is working
