### ISSUE TITLE
Unable to navigate and to any other page from edit mode and try to edit

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13949]
As a user I want to be able to be editing one page, click in any link in the page and keep editing that linked page

## Expected Behavior
When user is editing a page and navigate to another, he should be able to also edit that new page.

## Current Behavior
User can't edit a page he get by navigating from the edit mode of another page.

## Screencast:
https://screencast.com/t/OrHwZL4N

## Possible Solution
[Here](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/content/dot-edit-content.component.ts#L116) is where we listen when the page loads, everytime a user navigate to a internal link here this is the event that triggers, so we need to add the toolbars and bind events there.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Within that page navigate to any links there
4. Toolbars and stuff are missing

## Acceptance Criteria
1. User should be able to keep editing a page when internal nav happen
2. Match the design
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by fmontes** [comment]
Locker is not working as expected.

**Comment by wezell** [comment]
Preview mode needs to work the same way.

**Comment by bryanboza** [comment]
We have problems here if you try to navigate to the same page that you're editing 
SC: https://screencast.com/t/32Twn34G

**Comment by bryanboza** [comment]
Fixed, now this is working as expected... Tested on master // MySQL // FF

**Comment by fmontes** [comment]
When you navigate from page to page the nav bar in the right is not keeping selected "content"

**Comment by fmontes** [comment]
### Page content is getting cached in the resolver and is wrong

1. Edit a content of the page
2. Go to layout
3. Go back to content
4. The content is not updated any more, need to refresh the page.

**Comment by fmontes** [comment]
## Error in the internal navigation
1. Edit a page
2. Go to layout
4. Go back to content
5. Try any internal page link, see the error in the console

**Comment by bryanboza** [comment]
Fixed tested in the last master and now I don't have the error
