### ISSUE TITLE
Fix cancel button in add/edit content to a page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13947]
As a user I want to be able to go back to the process of edit or create a contentlet from the edit page.

## Expected Behavior
1. When user is editing a contentlet and click "Cancel" we close the dialog
2. When user is creating a content and click "Cancel" we should go back to the search results

## Current Behavior
Click in cancel do nothing.

## Possible Solution
This needs to be done at jsp level and also in angular level.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Try to add or edit a piece of content
4. Click in cancel

## Acceptance Criteria
1. When user is editing a contentlet and click "Cancel" we close the dialog
2. When user is creating a content and click "Cancel" we should go back to the search results
3. Match the design
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now is working according the acceptance criteria
