### ISSUE TITLE
Fix add/edit contentlet dialog issues

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13945]
The dialog we use to add or edit a contentlet needs a few improvements / fixes:

## Steps to reproduce
1. Login
2. Edit page
3. Click con + > content or click on the pencil icon
4. That dialog we need to fix

## Acceptance Criteria
1. Update the title message key, is broken in core
2. Dialog should not be draggable (check doc in primeng)
3. Hit ```esc``` key should close the dialog
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by hmoreras** [comment]
Close in scape is active, however this works when the focus in on the current window, once the user interacts with the iframe, the current window lost focus and the scape do not work.

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to close this window using the Esc key.
