### ISSUE TITLE
Language Variables not pulling content value before default language variables

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13954]
Tested on latest 4.3.2 release

We have some default language variables that auto-translate certain terms.  Our global language variables used to have priority and over-ride them if set, however, our new content-based language variables do not (bug)

For instance, consider the following code:  
```  
First Name: $text.get("firstName") - working<br/>
Last Name: $text.get("lastName") - working<br/>
Email: $text.get("email") - Not pulling Value from Content<br/>
Submit: $text.get("submit") - Not pulling Value from Content<br/>  
```  
Now here are the content settings for each language variable:

![content](https://user-images.githubusercontent.com/1569167/37798546-b25bf084-2de2-11e8-9a04-993f6d3b0d42.png)

Even if we set the "email" and "submit" values in the language variable content, they do not pull using the velocity above.  This disables the ability for webmasters to over-ride the default language translation files we have in the system.

Front end in English:

![english](https://user-images.githubusercontent.com/1569167/37798947-dac76412-2de3-11e8-9fce-aa254ba8a81f.png)

Front end in Spanish

![spanish](https://user-images.githubusercontent.com/1569167/37798981-f1fcdea0-2de3-11e8-9919-b399fb03e121.png)

Front end in French

![french](https://user-images.githubusercontent.com/1569167/37798988-f757d148-2de3-11e8-9c48-1474fee047e1.png)

**Comment by wezell** [comment]
This needs a branch and to be merged

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16586 now first looks up for the lang variables as content, if not found search in the properties file.

**Comment by nollymar** [comment]
Tests results: OK

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
