### ISSUE TITLE
Double click Edit button duplicate edit controls

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13952]
As a stakeholder I want to make sure that the system work as expected under any circumstance.

## Expected Behavior
If the user doubleclick in the Edit button it should still load the edit page with one set of toolbar buttons.

## Current Behavior
If the user doubleclick in the Edit button it load the page with TWO set of toolbar buttons.

## Possible Solution
The component doesn't have a doubleclick event we can listen to, so the solution could be... debounce maybe?

## Known Workarounds
N/A

## Screencast:
- https://screencast.com/t/ibB7l7gFkqE
- https://www.screencast.com/t/TEThHcA9xkO

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Click in preview
4. Double click in edit

## Acceptance Criteria

1. When user doubleclick the edit button should still load the edit page with one set of toolbar 
2. When user click on a selected "mode" click should not do anything.
3. Match the design
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and multiple browser, now i am unable to recreate
