### ISSUE TITLE
Can't move from Preview to Live when only have permission to view the page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13951]
As a user I want to be able to move between preview and live mode in a page I have permissions to view for the page editor

## Expected Behavior
User should be able to move between preview/live when have permission to view the page

## Current Behavior
User can't move and the UI is showing a error dialog message.

## Possible Solution
The problem is we're doing the lock/unlock request when the user don't have permission to edit or lock the page and that's returning a 403.

We might no need to lock/unlock all the time for every page state update.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login as Bill
2. Go to edit ```intranet/index``` (Bill only have view permissions here)
3. Try to move from Preview to live
4. Boom

## Screencast
https://www.screencast.com/t/xX032tiL

## Acceptance Criteria
1. User should be able to move from Preview to Live without seeing any dialog errors when it have permissions to view the page
2. Match the design
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14005

**Comment by fmontes** [comment]
When move from Live <> Edit it show and the page is locked by another user, it shows the dialog: "Are you sure you want to steal the lock?"

**Comment by fmontes** [comment]
When the page is locked by an user and you see it as an admin (it means you can steal the lock), the lock needs to be orange (which is working) but algo needs to be "off" so the user can turn it on and steal.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected in the acceptance criteria
