### ISSUE TITLE
Remove the conditions that forces a content type to always have associated a workflow

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#13953]
We need to remove the condition that forces a Content Type to always have related a workflow when we have a license applied. We should remove the references to the findDefaultScheme method when a content type doesn't have a workflow assigned.

Now should be possible to have a content type without any workflow associated. We need to remove the setting of the default Workflow when you don't have associated a workflow on a content type.

## Expected Behavior
We should be able to save a content type without any workflow associated

## Current Behavior
Currently if you edit a workflow and un-select all the workflows from the angular edit content type portlet and saves when you go back to the content type the default workflow is selected.

same thing happens from the old content type portlet, but in this case you are not allowed to save with a workflow selected.

## Steps to Reproduce (for bugs)
1. Edit a content type
2. Unmark all the selected workflows associated to that content type and save
3. Edit again the Content-type and validate that the content type doesn't have any workflow seleted

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13986

**Comment by bryanboza** [comment]
If any content type have just one workflow, and you delete this one, since now we allow content types without workflows, we need remove the functionality to auto associate this content type to the system workflow.

**Comment by oswaldogallango** [comment]
@bryanboza the only case that force you to have associated the system workflow is if you have a community license. if you have any license type except community and remove the workflow associated to the content type, you will see that not actions are availables if  you try to add or edit a contentlet and in both portlets that handle content types, the option is not marked as default as before.

**Comment by bryanboza** [comment]
Unable to reproduce after update, tested in the last master conde // Postgres // FF
