### ISSUE TITLE
window.dotNgModel is undefined in Firefox

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13957]
As a stakeholder I want the app as error free as possible

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Login in Firefox
2. Edit a page
3. Lock the page
4. Check the console for the error

## Acceptance Criteria

1. Make sure the error don't show
2. Double check that page model it's being saved
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
Not happening anymore, tested on Chrome, FF & IE

**Comment by fmontes** [comment]
Fixed in another issue
