### ISSUE TITLE
Live Mode is Broken for all non-default languages

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#13958]
tested on demo.dotcms.com and on 4.3.2 local

Easy to reproduce, go to any page, new or a starter page, switch to secondary language, then look at the page in live mode (Page Breaks in that mode and goes blank)

![blanklive](https://user-images.githubusercontent.com/1569167/37801526-935d2cf2-2dec-11e8-87a2-802202e6f76d.png)

Tested with multiple pages and with spanish and french.

FYI this does not appear to happen on master with the new page editing features.

**Comment by wezell** [comment]
Fixed in 5.x
