### ISSUE TITLE
Fix editing page and login as an another user

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13950]
As a user I want to be able to see and edit a page as a login as user.

## Expected Behavior
When user login as another user it should go to first portlet.

## Current Behavior
When user login as, nothing happen.

## Possible Solution
1. We need to look into this [subscribe](https://github.com/dotCMS/core-web/blob/issue-13299-Implement-workflows-in-the-edit-page-v2/src/app/view/components/dot-navigation/dot-navigation.service.ts#L41)
2. Some routing issues here.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Login as another user
4. Nothing happen

## Acceptance Criteria

1. When an user is editing a page and login as another user go to first portlet
2. When user is editing a page logged as any user and logout as should go to first portlet
3. When user is logged in the page being edited should reflect all the permissions for the logged as user
2. If the login as user doesn't have permission to view the page, we redirect to site-browser
3. Match the design
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, now this is working fine on master
