### ISSUE TITLE
Prevent that user can add contentlet to a content type in a container with no permission

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13955]
As a stakeholder I want users to be able to add content only to the containers and content types where I have permissions to.

## Expected Behavior
When user should be able to add content to the containers that hold content types where the user have permission to create content to.

## Current Behavior
The UI Is not checking anything and the jsp breaks.

## Possible Solution
Probably BE and FE

## Known Workarounds
N/A

## Acceptance Criteria
1. Disable the + when user doesn't have permission to add content on a container, it could be:
    - User doesn't have permission to any content type that the container holds
    - User doesn't have permission to add content
2. Disable the edit button in  a contentlet when user doesn't have permission to edit it, it could be:
    - User doesn't have permission to view/edit the contentlet content type
    - User doesn't have permission to edit the contentlet it self
3. In the content search, user should only see in the dropdown the content type he have access to
4. Match the design
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by freddyucv** [comment]
branch in core:

https://github.com/dotCMS/core/tree/issue-13955-Prevent-that-user-can-add-contentlet-to-a-content-type-in-a-container-with-no-permission

**Comment by bryanboza** [comment]
Fixed, now we validate every kind of content before disable the button, after this if you don't have permissions then we disable it.
