### ISSUE TITLE
Remove support of ES Facets from documentation

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13969]
ES Facets were previously deprecated, but are now not supported in ES 6.1. 
They need to be removed from the documentation and also include this in the changelogs.

Documents to watch:

https://dotcms.com/docs/latest/faceted-site-search
https://dotcms.com/docs/latest/faceted-site-search#Migration (in here keep the migration part but change "deprecated" to "not supported" or something equivalent)

**Comment by DeanGonzalez** [comment]
Faceted now marked as defunct instead of deprecated: https://auth.dotcms.com/docs/latest/aggregated-site-search#Migration
