### ISSUE TITLE
Enforced 4-Eyes Labeling is unclear

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#13971]
The enforced 4 Eyes action requires a button e.g. 'approve' to be clicked twice by two different users. Users get confused and keep clicking to on the button as it doesn't change status.  The button should no longer be available to the same user or should indicate that there is an additional approval needed.

**Comment by wezell** [comment]
This is a function of how our workflows work -we might be able to modify it future forward but there are no current plans to do so.
