### ISSUE TITLE
Add loading indicator when edit a page from site browse

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13974]
As a stakeholder I want user to always have visible feedback when an action is executed.

## Expected Behavior
It should show a loading indicator when user doubleclick or right click to edit a page.

## Current Behavior
Not showing loading indicator and take a few seconds so it looks kinda broken.

## Possible Solution
Maybe emit a custom event from the site browser jsp that we listing in angular.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Go to site browser
3. Double click or right click to open page
4. Seconds... the edit page.

## Acceptance Criteria

1. Show loading indicator as soon user double click file or right click > open in Site Browser
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we have the load indicator here
