### ISSUE TITLE
/v1/workflow/schemes is not returning archive schemes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13970]
## Expected Behavior
Should return all the workflows schemas, including archive ones with the property archive in true

## Current Behavior
It's not returning archive ones.

## Possible Solution
N/A

## Known Workarounds
N/A

## Acceptance Criteria

1. Endpoint should return archive workflow schemes with the archive property in true
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres and now we have the archived sites on the list...
