### ISSUE TITLE
Allow container selector to add the same container more than one

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13977]
As a user I want to be able to add any container anywhere in the page as much as I want.

## Expected Behavior
Container selector should allow user to add the same container more than one.

## Current Behavior
Container selector prevent the same container to be selected more than once.

## Possible Solution
Add a attr to the container selector to define this behavior like: ```[multiple]="true"``` here is the validation: https://github.com/dotCMS/core-web/blob/master/src/app/view/components/dot-container-selector/dot-container-selector.component.ts#L35

## Acceptance Criteria

1. User should be able to add the same container more than once in the same block
2. Container selector component should have an attribute to set that
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need multiple clicks in the container selector to see the list fo containers

**Comment by bryanboza** [comment]
This is just the UI part, now it's working, but now we have an issue when you try to use it SC: https://gist.github.com/bryanboza/faaa687786f33b10089527219331e289

**Comment by bryanboza** [comment]
We still waiting for the ticket #13566

**Comment by bryanboza** [comment]
Fixed, after the fix #13566 now I am unable to reproduce the error
