### ISSUE TITLE
User can delete a folder that is being used as a theme for a template

### ISSUE THREAD

**Issue by mwoodland** [dotCMS/core#13989]
A user can delete a folder even if it's being used as a theme in a (template designer) template. Once this has happened the user can no longer change the theme for the template and is instead shown the advanced template view for the template which doesn't have the theme field on it.

## Expected Behavior
Either the user should be prevented from deleting the folder if it's in use by a template and should be told which templates are using it or once the folder has been deleted the user should continue to be able to update the template so they can correct the template to use a theme that still exists.

## Current Behavior
Currently the folder can be deleted and then the template ends up being broken and left in a state where you can't repair it because the field for specifying the theme is no longer displayed when viewing the template.

## Known Workarounds
- Delete the affected templates and recreate them
- Or update the templates in the dotCMS database to update the theme to reference a folder that exists and then flush caches and re-index the site

## Steps to Reproduce (for bugs)

1. Log into https://demo.dotcms.com/admin
2. In the site browser add a new folder under /application/themes
3. Under site templates add a new template designer template
4. Set a title and set the theme to the folder you just created
5. Save and publish the template
6. Back in the site browser delete the folder you added
7. Back under site templates view the template again you will no longer be shown the design template tab and you will not be able to set a theme for the template

## Context
We've managed to end up in a situation where some of our templates have been corrupted by this issue.  This prevents some of the tooling we use for the dotCMS sites from working. We'd either like to be able to fix the affected templates from the dotCMS administration site or be prevented from getting in this situation in the first place.

## Your Environment

* dotCMS version used:
We're currently using dotCMS 4.1.1 and are in the process of upgrading to 4.2.0, this affects both versions. However I've also reproduced this in the demo site https://demo.dotcms.com/dotAdmin/#/c/templates

**Comment by levosgien** [comment]
https://dotcms.zendesk.com/agent/tickets/95519
