### ISSUE TITLE
Removing step when saving Workflows to a Content Type

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#13980]
When saving Workflows to a Content Type we are removing the Contentlets of that Content Type from their current steps even if the Workflow of that step is not removed from the Content Type workflows, meaning, when saving the Content Type we are ALWAYS cleaning the steps of the contentlets.

Also the cache of the modified Workflow tasks is never updated.

Method where the wrong clean up is made:
``` java
    @Override
    public void saveSchemeIdsForContentType(String contentTypeInode, List<String> schemesIds) throws DotDataException {
        if (LicenseUtil.getLevel() < LicenseLevel.STANDARD.level) {
            return;
        }
        try {

            final DotConnect db = new DotConnect();
            db.setSQL(sql.DELETE_SCHEME_FOR_STRUCT);
            db.addParam(contentTypeInode);
            db.loadResult();

            for(String id : schemesIds) {
                db.setSQL(sql.INSERT_SCHEME_FOR_STRUCT);
                db.addParam(UUIDGenerator.generateUuid());
                db.addParam(id);
                db.addParam(contentTypeInode);
                db.loadResult();
            }
            // update all tasks for the content type and reset their step to
            // null
            db.setSQL(sql.UPDATE_STEPS_BY_STRUCT);
            db.addParam((Object) null);
            db.addParam(contentTypeInode);
            db.loadResult();

            // we have to clear the saved steps/tasks for all contentlets using
            // this workflow

            cache.removeStructure(contentTypeInode);

            cache.clearStepsCache();
        } catch (final Exception e) {
            Logger.error(this.getClass(), e.getMessage(), e);
            throw new DotDataException(e.getMessage(),e);
        }
    }
```

## Expected Behavior
We should alter the workflow tasks of the contentlets of a modified Content Type only if the task belong to a removed Workflow from the Content Type.

Also the cache should be cleaned up for the modified workflow tasks.

## Current Behavior
We are removing from the current step all the Contentlets when we adding a new workflow to a Content Type and also the cache for workflow tasks is never updated.

## Steps to Reproduce (for bugs)
1. Document used to had a mandatory workflow and for that reason all the Documents are in an step (workflow_task)
2. Add a second workflow to the Document Content Type

After doing that I found two issues:
1. To all the Documents workflows tasks we changed the status to null, meaning, is not longer in a step which is wrong as we never removed the workflow of the task from the Content Type.
2. Also the cache of the task was not clean, we still have in memory the task with the status set.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/13992

**Comment by bryanboza** [comment]
Fixed, tested in the last master code // postgres
