### ISSUE TITLE
Research: Add detail page field to content types

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13988]
When building a URL mapped content type - you have to specify a detail page.  Normally, this looks something like this, with a browse button:

![screen shot 2018-03-26 at 10 12 02 pm](https://user-images.githubusercontent.com/934364/37942780-d72e07ae-3142-11e8-82eb-fde3d6a15df1.png)
   
in 5.0 it looks like this, with no way to select a detail page except by entering in the identifier.  Has anyone tried to make a content type with a detail page in 5.0?

![screen shot 2018-03-26 at 10 12 35 pm](https://user-images.githubusercontent.com/934364/37942824-fff65592-3142-11e8-96f1-f0557dcd7d2d.png)

**Comment by wezell** [comment]
@bryanboza is there an issue for this already?

**Comment by fmontes** [comment]
No there is no issue for that, we need to build this.

**Comment by fmontes** [comment]
I don't think is worthy to make this into a field

1. Too many services that are duplicated in the library and core-web
2. Code is not tested, too risky to bring in
3. Implement control value accessor will require refactor
