### ISSUE TITLE
Double content search call trying to execute the delete action 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13987]
When you try to execute a delete action, the system is doing a double call to the `ContentAjax.searchContentlets` .

## Expected Behavior
We should call this just one time 

## Current Behavior
We call this twice, then we have some strange behavior with the search button if you are in the content search portlet 
SC: https://screencast.com/t/m59um1E6

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a custom workflow
3. Add a new action and add the delete sub-action on it
4. Associate this to the Generic conte type
5. Try to execute that from a published piece of content

## Your Environment
Tested on the last master code // postgres // chrome

**Comment by wezell** [comment]
This is done to give elasticsearch reindexing to catch up and will be taken care of when we redo the search screen
