### ISSUE TITLE
Unable to add push environment after upgrade from 3.x version in postgres 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13996]
We have an 500 error and get a exception when you try to add a push environment and we are unable save. 

## Expected Behavior
We should be able to add push environments without problems 

## Current Behavior
We have this exception: https://gist.github.com/bryanboza/26f284529fa2871df2e3ca571b7be116

## Steps to Reproduce (for bugs)
1. Upgrade a new instance from 3.x to master   
2. Apply the license 
3. Reindex
4. Go to the push environments tab in the configuration and try to add a new environment 

## Your Environment
Tested in the last master code, upgrading from 3.x version // Postgres

**Comment by fabrizzio-dotCMS** [comment]
I tried several times to reproduce this error with no luck. It's working fine for me.

**Comment by bryanboza** [comment]
Unable to reproduce in the last master...
