### ISSUE TITLE
Unable to upgrade from 3.x version in MySQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13995]
We have problems trying to upgrade from 3.x version to master 

## Expected Behavior
We should be able to upgrade without problems 

## Current Behavior
We have this exeption and we are unable to upgrade 
Log: https://gist.github.com/bryanboza/1cd3b1b0fb7ca52155fc8ab41ea44ba9

## Your Environment
Tested upgrading from 3.x version to the last master // MySQL

**Comment by acurionedotcms** [comment]
Seems to be working as expected..
I created a new startup using dotcms v 3.7.2 on MySQL and it started correctly
Then started a latest version of master to that MySQL database
It properly upgraded up to db_version 4355

![image](https://user-images.githubusercontent.com/32649325/38820655-b443bf58-415b-11e8-87a7-919877849437.png)

**Comment by shaydotcms** [comment]
Passed QA.
No issues after upgrade from 3.7.1version(starter data)  to master(starter data) 
Ran db_version and last task showing is 4355, which is the right task

Tested upgrading from 3.x version to the last master // MySQL
