### ISSUE TITLE
Problems showing the available actions to some content type if one of the schemas don't have steps 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13998]
We are having problems to show the available options to some content type, if you associate to some schema that don't have steps.

## Expected Behavior
We need be able to show the actions of the other associated schemas if some schema don't have steps 

## Current Behavior
We have no actions, if some of the associated schemas don't have steps  

We assume in code all the schemas have steps. 

## Steps to Reproduce (for bugs)
1. Create 2 workflows schemas 
2. Add steps and actions just to one of this ones 
3. Associate some content type to 3 workflows (2 new ones and the system workflow)
4. Try to add a new piece of content to this content  type 

SC: https://screencast.com/t/OLYunrX6B

## Your Environment
Tested in the last master code // postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14061

**Comment by bryanboza** [comment]
Fixed, tested in the last master code and now I am unable to reproduce
