### ISSUE TITLE
Copying a host adds _copy to assets in the root folder

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14000]
Make a copy of a default host with assets/pages in the root folder and they add _copy to them.

![Screen Shot 2018-03-29 at 8.27.35 AM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/c37ce349-d3fc-4444-ad32-eeec40ea15c7)

**Comment by bryanboza** [comment]
Fixed, I'm unable to reproduce after the last changes, tested on master // MySQL
