### ISSUE TITLE
Not possible to get live version of content with Page REST API

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14002]
If the live and working versions of a content are not the same, and you place the content on a page, you can **not** get the live version of content using the `/api/v1/page/json` endpoint.

## Expected Behavior

The page REST API `/api/v1/page/json` endpoint is, according to the javadocs, supposed to accept a `/live/{true|false}` URL parameter, **_and_** the default value of this parameter is supposed to be **true** (meaning that, by default, only the live version of the content should be returned).

Both of these behaviors (the default showing only the live content, and the ability to use the `/live/{true|false}` parameter) should work as document in the javadocs.

## Current Behavior

Currently both of the following incorrect behaviors happen:

1. By default the working version of the content is returned instead of the live version of the content.
2. The `/live/true` parameter is not working.

As a result, it's not even possible to return the live version of the content with this endpoint if the live and working versions of the content are different.

## Possible Solution

It appears that this is caused by the following line of code:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResourceHelper.java#L179

This line passes a hard-coded `false` value, rather than passing the value of the `live` argument.

## Known Workarounds

None that I've found so far without altering the content itself.

(In other words, you could make the live and working versions of the content the same by either publishing the current working version of the content or doing a "Bring back" on the live version - both of which would require editing every content which has a different live and working version).

## Steps to Reproduce (for bugs)

1. Login to the demo site.
2. Open the "About Quest" contentlet (of type "Content (Generic)") and make sure there are different live and working versions of the content.  Note the inode of both the live and working versions of the content.
3. Type in the following URL: https://demo.dotcms.com/api/v1/page/json/about-us/index
4. Search for the inodes of both the live and working versions of the content within the results.
    * **Result:** Only the inode of the working version of the content is included.
    * In other words, the default is to return the working, not the live version of the content.
5. Type in the following URL: https://demo.dotcms.com/api/v1/page/json/live/true/about-us/index
6. Search for the inodes of both the live and working versions of the content within the results.
    * **Result:** Only the inode of the working version of the content is included.
    * In other words, the `/live/true` URL param is ignored.

## Context

This makes the page REST API impractical for customers with content in both live and working states at the same time (which I assume is probably most customers).

## Your Environment

* dotCMS version used: 4.3.2 (demo)
* Browser Name and version: Chrome
* Operating System and version: Win10 Pro
* Application Server and version: Tomcat (demo)
* Java Brand and version: 1.8 (demo)

**Comment by fmontes** [comment]
The url should use a queryParam like ```?live={true|false}```

**Comment by john-thomas-dotcms** [comment]
That was tried @fmontes and it still didn't work (the working version was still returned, even with that parameter).  I couldn't find any way to get a live version of the content, even with help from @wezell.

It's been a while, but if I remember correctly, a look into the source code showed that we do read the live=true parameter, but instead of passing the value of that parameter into the method where the content is retrieved we just pass a hard-coded 0.

**Comment by john-thomas-dotcms** [comment]
The other issue @fmontes is that the default should be to return the live content, not the working content.  So in addition to fixing the code to read that parameter, the default for that parameter (if it's not passed in explicitly) should be true instead of false.

**Comment by dsilvam** [comment]
This is not happening on 5.0. 

Equivalent endpoint for doing this operation in 5.0 is: 
http://localhost:8080/api/v1/page/render/about-us/index?mode=LIVE_MODE
and it is properly returning the live version of the content when `mode=LIVE_MODE`, and when no `mode=LIVE_MODE` is returning the working version. Passing this one. @john-thomas-dotcms please let me know if I need to do something else
