### ISSUE TITLE
Keep changes in the page when move toggle from edit to preview

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14018]
As a user I want to be able to see how the changes I did in a page will looks like once is published.

## Expected Behavior
If an user do changes to a page (add or move content) should be able to preview those changes when click in "Preview" button and the changes should remain if goes back to "Edit".

## Current Behavior
If an user do changes to a page (add or move content) and click in "Preview" the changes are gone and if goes back to "Edit" gone too.

## Possible Solution
1. If the model is updated and user moves to preview, add a class to the body of the iframe html to hide the toolbars with css and not make the request to get preview.
2. Is the model is updated allow user to save the page from the preview state (right now save button is hidden).

## Known Workarounds
Right now user needs to save the page in order to see it in preview and that's so no cool.

## Steps to Reproduce (for bugs)

1. Edit a page
2. Add or move content
3. Click on "Preview"
4. Changes are gone

## Acceptance Criteria

1. User should be able to add or move content to a page a preview the changes without saving the page
2. User should be able to save the page from preview state when the model changed.
3. If the model is updated and user try to go to live we should a confirmation dialog to let the user know that it will lose the changes
4. Match the design
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by alfredo-dotcms** [comment]
some progress was done in this `core-web` branch: `issue-14018-keep-changes-in-the-page-when-move-toggle-from-edit-to-preview`

**Comment by fmontes** [comment]
No longer necessary because: https://github.com/dotCMS/core/issues/14326
