### ISSUE TITLE
Unable to archive sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14020]
We are unable to archive sites, this because the system detect the site as archived an is only stoped 

## Expected Behavior
We need be able to archive and unarchive sites without problems 

## Current Behavior
When you try to archive we have an error on log and the site is not archived 

Log: https://gist.github.com/bryanboza/db757162eeaee0dc425d4e7f7a04e28d

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to system --> sites
3. Create a new copy of demo  
4. Stop the site
5. Try to archive the copy 

## Your Environment
Tested in the last master code // postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14072

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we are able to archive without problems

**Comment by oarrietadotcms** [comment]
Hotfix for 3.7.1: https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-14020_v3.7.1
