### ISSUE TITLE
ERROR: column "server_id" does not exist

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14029]
Getting this error repeatedly from the 20180402 nightly build on both H2 and Postgres DBs
https://gist.github.com/brentgriffin/601284fc7783f09aa430a70c915da9ab
## Expected Behavior
This error should not be occurring.

## Current Behavior

 Just start dotcms up and access the frontend - this error will appear many times.

**Comment by jgambarios** [comment]
Unable to reproduce, @bryanboza can you please help us to verify this problem?

**Comment by bryanboza** [comment]
Unable to reproduce in the last master, tested navigating in FE and BE with and without license and I am unable to see the error

**Comment by jdotcms** [comment]
It is kind odd, if you are not upgrading you should get the table definition from it, are you running a clean install or upgrade?

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/postgres.sql#L2459

**Comment by wezell** [comment]
@brentgriffin Are you still seeing this?  If so, lets reopen
