### ISSUE TITLE
Can't save a page with no contentlets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14025]
As a user I want to be able to empty a page and save it.

## Expected Behavior
User should be able to save an emptied page.

## Current Behavior
If user try to save and empty page it crash the request.

## Possible Solution
1. Need to update the backend
2. We need to catch the error in the FE just in case.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a page
2. Remove all the contentlets
3. Try to save it
4. Crash

## Acceptance Criteria

1. Fix the backend to accept empty pages to save
2. Update the FE to catch and handle the error if trying to save a page fail
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, now we are able to save without problems
