### ISSUE TITLE
[Contents] When copying a contentlet of any type, it should only clone the live / working version and not all versions

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14024]
Once a content or even a site is copied over, we carry over its old versions. No matter how many old versions it has, this is always true. However, for other assets like containers, we do not carry over these old versions.

Whenever an existing site is copied, we should have a consistent way to carry over assets and associated info. Knowing that users would like to get only live/working versions of contents/assets from the original site they've copied everything from, having old versions copied:

- might not be necessary.
- does not apply for all asset types (it doesn't happen for containers or templates).

## Expected Behavior
We should either exclude old versions and copy only live/working versions of contents and other assets, or copy everything. Behavior of versionable assets should be consistent.

## Current Behavior
Once we copy a site, we're able to see contents copied including all of their old versions. Even with a regular copy of a content this is true. However, for other copy processes, like Containers, templates or links, old versions are not copied.

## Possible Solution
Make the ContentletAPI.copyContentlet to accept an additional param and ask if all versions (including old ones) should be copied over. 

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Login to the backend and create multiple versions of at least 1 container, 1 link and 1 content .
2. Copy the demo site to a new one, including all assets from it.
3. Compare the list of assets and versions you created versions for, between demo and newly created site.
- New container on the cloned site has nothing on the history tab, only its live/working version.
- New link on the cloned site has nothing on the history tab, only its live/working version.
- New contentlet on the cloned site has the same amount of versions it had on the original demo site.

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95424

## Your Environment

* dotCMS version used: 4.2.2, 4.3.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any supperted application server.
* Java Brand and version: Any supported Java 8 version
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

**Comment by wezell** [comment]
This is definitely a problem

**Comment by joseorsini** [comment]
Commit here https://github.com/dotCMS/core/commit/07603a38ae9552110bf5b8498c03fc9470b6a069

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14069

**Comment by joseorsini** [comment]
This issue avoids copying old versions that might be potentially broken, as stated on this ticket  https://github.com/dotCMS/core/issues/13682

**Comment by joseorsini** [comment]
Disregard commits 3272add and d4b7bd2 , which are unrelated to this issue.
