### ISSUE TITLE
UI: Improve Websocket Notifications

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14023]
As a continuation to the ticket https://github.com/dotCMS/core/issues/13812 we need to integrate in core-web the new websocket notifications.
Right now the backend is generating the new notification events and sending them throw the websocket and in core-web we need to capture and handle those messages properly in the form of UI messages.

## Possible solution
1. Global message component should listen to the websocket events

## Acceptance Criteria

1. Update the global component and service to use growl component and message service from primeng
2. We need to somehow make growl work with "loading" message, it means loading animated icon (this is pure css overwrite original)
3. Show messages from the workflows actions triggered
4. Remove the **default** global message when trigger an workflow action (clean up the message key please)
5. Show the messages top right corner
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
8. Unit test

**Comment by fmontes** [comment]
This was done by the toast.
