### ISSUE TITLE
Unable to upgrade to the last master in MSSQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14038]
We have problems tying to upgrade from a previous version to the last master 

## Expected Behavior
We need be able to upgrade from previous version to the last master without problems 

## Current Behavior
We are having a SQL problem adding the system workflow 
LOG: https://gist.github.com/bryanboza/e6083efd43218ede69b113ffd09c53f7

## Your Environment
Tested in the last master // postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14040

**Comment by bryanboza** [comment]
Fixed, now we are able to upgrade from previous versions to the last master without problems
