### ISSUE TITLE
Websocket events happening before asset is created or published

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14030]
With the update of the websocket to make them faster (pretty cool tho) we run into some other issues, the websocket event is happening before the transaction is complete, for example, events like: SAVE_SITE and PUBLISH_SITE are happening before the site is saved or published.

For example, in the site selector component we liste for those events to refresh the site list, the refresh is not happening because when we trigger the refresh of the site to the endpoint the new site is not coming in the list.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14095

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/14161

**Comment by bryanboza** [comment]
We need the FOX implementation to test this events...
