### ISSUE TITLE
Unable to reorder workflow sub-actions in upgraded instances

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14043]
If you upgrade your instance from a previous version to the last master, you are unable to reorder workflow sub-actions into a step. 

## Expected Behavior
We should be able to reorder and save without problems 

## Current Behavior
After you try to save we alter the order again and don't save the changes
SC: https://screencast.com/t/3sLy97Gcba4

## Steps to Reproduce (for bugs)
1. Start a dotCMS instance with a previous version 
2. Create a new workflow scheme with steps and actions 
3. Upgrade to master
4. Try to add a new sub-action to one of the actions, change the execution order and save 
5. Make sure the changes was applied 

## Your Environment
Tested after upgrade from 3.x to master in mssql

**Comment by jgambarios** [comment]
Unable to reproduce

**Comment by bryanboza** [comment]
Able to reproduce after upgrade https://screencast.com/t/ryJP2TY1sn

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14484

**Comment by bryanboza** [comment]
Fixed, tested after upgrade and now I'm unable to reproduce the problem
