### ISSUE TITLE
[REST] Return proper status for ES API REST endpoint if no query is passed in

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14052]
We're returning Error 500 if we hit the ES API REST endpoint if the request doesn't have a JSONObject as ES Query. Even passing in an empty string, or no data at all, it throws error 500. 

## Possible Solution
Return Error 400 Bad Request response if no query is passed in.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. On a browser, hit https://demo.dotcms.com/api/es/search.
2. An error 500 is thrown in log files and on browser.

Stacktrace: https://gist.github.com/joseorsini/d4eab540b159e10a564e5fa9ee705380

## Your Environment

* dotCMS version used: 4.3.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any supported application server.
* Java Brand and version: Any supported Java 8 version.
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14054

**Comment by erickgonzalez** [comment]
400 error is thrown if no JSON is passed in rest call `/api/es/search`

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
