### ISSUE TITLE
Missing and edit .vtl file icon in Edit Mode for parsed vtl files in dynamic listings

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14056]
This is only in the 5.0 version

When we dotParse a .vtl file and place that widget on a page, webmasters need to see an icon in Edit Mode on the page so that they can directly edit the file that is being parsed on the page.

This is how it looks in 4.3.2:

![editwidgeticon](https://user-images.githubusercontent.com/1569167/38433359-c14f4dc4-3987-11e8-9283-be5dd011e183.png)

## Posible Solution
1. Send from the backend to the HTML a ```data-dot-vtl="url to the vtl"```
2. In the FE we read that data attr and if exist we add the button to edit the vtl
3. Use the iframe to show the JSP to edit the vtl file code 

## Acceptance Criteria

1. Add button so user can edit the VTL of a widget and on click should open an iframe to edit the vtl code.
    - The button icon should be https://material.io/icons/#ic_code
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by freddyucv** [comment]
BE: https://github.com/dotCMS/core/tree/issue-14056-Missing-and-edit-.vtl-file-icon-in-Edit-Mode-for-parsed-vtl-files-in-dynamic-listings

**Comment by fmontes** [comment]
Edit button is broken.

**Comment by fmontes** [comment]
Changes in the vtl are not getting in to the UI.

**Comment by fmontes** [comment]
Not refreshing the contantlet after `vtl` file updated

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
