### ISSUE TITLE
Add to bundle field should remember last one

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14066]
As a user I want the last bundle I added to be selected as default

## Expected Behavior
When user try to add to bundle the bundle field value should be the last bundle user added to.

## Current Behavior
No value selected never.

## Possible Solution
Localstorage, we need to create a service with set and get for localstorate, make it work as close as the original API as possible.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Go to content type
3. Add to bundle any
4. Add to bundle another one, no bundle value selected.

## Acceptance Criteria

1. Bundle value should be the last one user added to.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Tested with the last changes, and now we are remembering the bundle, but when you try to add something to a bundle from content types portlet or sites portlet, we lost this value

**Comment by erickgonzalez** [comment]
Tested now from the **Content Types Portlet** the value of the bundle field is the last bundle the user added to.

**Comment by fmontes** [comment]
This works in the Angular side but not in the jsp

**Comment by freddyucv** [comment]
PRs:

core: https://github.com/dotCMS/core/pull/17920
core-web: https://github.com/dotCMS/core-web/pull/1269

**Comment by dsilvam** [comment]
Passed Internal QA: _Add to Bundle_ functionality properly remembers last selection on both type of  Dialogs,  the one launched from _Content type_  portlet and the one launched from the other portlets (Content search, categories, Site-Browser, etc)

**Comment by bryanboza** [comment]
Fixed, tested after the in with the last changes and now we are remembering the from all the portlets. Tested on release-5.2.6 // Postgres // FF
