### ISSUE TITLE
[Relationships] Add more room for related contents' titles (or other listed fields)

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14060]
## Expected Behavior
For related contents in the Relationships tab, we should be able to see its full text (title, or any other listed fields) or at least a better formatted way to show listed fields with large amounts of characters.

## Current Behavior
Listed fields of related contents are cut off and readability is lost.

## Known Workarounds
None. 

## Steps to Reproduce (for bugs)

1. Edit the `Tiffany &amp; Co: Still Shining With Substantial Earnings Beat And Guidance Increase` content:
- Edit its title to `Tiffany &amp; Co: Still Shining With Substantial Earnings Beat And Guidance Increase Tiffany &amp; Co: Still Shining With Substantial Earnings Beat And Guidance Increase`.
- Relate 1 comment to this blog article.
- Save/Publish it.
2. open the comment content you related to this Blog article and look at the relationships tab. The blog title is being cut off.

<img width="1290" alt="screen shot 2018-04-06 at 3 00 49 pm" src="https://user-images.githubusercontent.com/1717110/38441834-b04c6376-39ab-11e8-9afc-5ec69249321a.png">

## Context
As reported by customer https://dotcms.zendesk.com/agent/tickets/95569 this placeholder of related contents allowed at least two lines of text in 3.3.x releases, and same test on demo3.dotcms.com site (runnung 3.7.1), the styling is different, and full text of this field can be displayed if the browser is resized horizontally.

## Your Environment

* dotCMS version used: 4.3.2.
* Browser Name and version: Any Browser.
* Operating System and version: any OS.
* Application Server and version: Any application server.
* Java Brand and version: Any Java8 version.
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

**Comment by iljaskevicarchitech** [comment]
This issue seems to be caused by an inline CSS `height` property on a div element in the table.

This is with the `height` property:
<img width="710" alt="withcssheightproperty" src="https://user-images.githubusercontent.com/11724459/38518455-e51a1e70-3c0a-11e8-957d-a572e125c8fa.png">

This is without the `height` property:
<img width="700" alt="withoutcssheightproperty" src="https://user-images.githubusercontent.com/11724459/38518454-e4f91126-3c0a-11e8-822a-1a00144c15b6.png">

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14074

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by dsolistorres** [comment]
Hotfix for 4.3.2
[hotfix-GIT-14060_v4.3.2.zip](https://github.com/dotCMS/core/files/2984566/hotfix-GIT-14060_v4.3.2.zip)
