### ISSUE TITLE
Content Type should allow the text string 'Null'

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#14098]
In a Content Type (in this instance, a Person) with a field of Last Name defined:

Variable: familyName
Label: Last Name
Data Type: text
Validation regex:  [^(<[.\\n]+>)]*
required, user searchable, system indexed, show in list

If a user enters the valid last name of Null the system throws an error.  In the browser it's
The field Last Name is mandatory

In the log it is:

ERROR business.ESContentletAPIImpl: Contentlet [Unknown/New] has an invalid field.
com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Contentlet [Unknown/New] has an invalid field.

This should not be doing a string value comparison to null but for actual null values.

Reproduced on Demo 4.3.1:

1. Open the Content Search screen.
2. Select the "Content (Generic)" content type.
3. Select "Add New Content" -> "Add New Content".
4. Set the Title field to "Null" (without quotes)
5. Put any text in the Body field.
6. Press the "Save / Publish" action button.

**Comment by john-thomas-dotcms** [comment]
Note that we should double check how the fields are being compared with the value "null", and make sure the field values are escaped properly everywhere they're referenced.
