### ISSUE TITLE
Error trying to edit pages as limited users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14091]
As limited user If I have permissions need be able to edit pages without problems, this in order to respect the permissions stuff 

## Expected Behavior
If you set permissions to edit an specific page, you need be able to edit it without problems 

## Current Behavior
We have an error in the log when you try to edit and every time you try to modify something in the page 
Log: https://gist.github.com/bryanboza/8af2062c5e6d9d0c9729f93ea423778e

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to /about-us and set full permissions to chris publisher 
3. Now set full permissions to the same user in the page /about-us/index
4. Logout
5. Login as Chris Publishe 
6. Try to edit the page 

## Your Environment
Tested on master // postgres

**Comment by jgambarios** [comment]
Not longer an issue but we made some small improvements to the logging of errors: https://github.com/dotCMS/core/pull/14903

**Comment by bryanboza** [comment]
Not an issue for now, tested again and now looks better after the improvements
