### ISSUE TITLE
Standardize error codes in the new WorkflowResource

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14109]
We need to make sure we are using the proper response code on all the _WorkflowResource_ endpoints when a license is required, the user is not authenticated and when the user does not have the proper permissions to execute an operation.

We need to make sure we are using these codes:

* **403** If the user does not have a license
* **403** If does not have permissions
* **401** If the user does not exist
* **401** If the user credentials are incorrect

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14180

**Comment by bryanboza** [comment]
Fixed, now we have this standard in all the endpoints of the workflow resource
