### ISSUE TITLE
Relate content improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14118]
Related to #14022 

As user, relating content should be easier in the new ui.

## Expected Behavior
[ ] - We need to make the language not required
[ ] - We need the relate content window to be bigger and render correctly
[ ] - When you try to relate some content, we need  show the window and auto search to populate the content list. 

## Current Behavior
The window is too small and it does not populate 

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create two new content types  (CT1,CT2) 
3. Add just one text field to every one and create a new relationship between those ones 
4. Add a new piece of contnent to CT1
5. Try to add a new piece of content to CT2 and relate with the previously created in CT1

6. also try relating a news article to its different relation types.

## Your Environment
Tested on master // postgres // FF 

## Acceptance Criteria  
1. Allow add a related content with just one click
    - [ ] Make language selection optional
    - [ ] render the list of available contents 
2. Make the dialog bigger
2. Work in all the supported browsers
3. Multilanguage

**Comment by wezell** [comment]
This branch has 1/2 of the changes needs to be completed.  Please start from here:

https://github.com/dotCMS/core/compare/issue-14118-relate-content-improvements

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14887

**Comment by wezell** [comment]
Possibly causing the "Reuse content window" to get squished:

![screen shot 2018-07-23 at 1 43 22 pm](https://user-images.githubusercontent.com/934364/43100146-6b6eeca6-8e92-11e8-98a4-2458492b6d63.png)

**Comment by fmontes** [comment]
<img width="1239" alt="screen shot 2018-07-25 at 7 00 07 am" src="https://user-images.githubusercontent.com/751424/43202363-8d56f592-8fd8-11e8-8480-82ab4072eeb0.png">
<img width="1243" alt="screen shot 2018-07-25 at 7 01 05 am" src="https://user-images.githubusercontent.com/751424/43202365-8d6cdb3c-8fd8-11e8-8e22-b514414843d4.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.0 // Postgres // FF
