### ISSUE TITLE
Delete Host process improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14112]
We need to do some improvements on the Delete Host process:

1. Instead to be a regular thread convert it to be a **DotSubmitter**
2. In order to make it testable needs to return a **Future**
3. Needs to use a `WrapInTrasaction` annotation
4. The unit test needs to be updated in toder to avoid the `Thread.sleep` and make use of the `future.get`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14139

**Comment by bryanboza** [comment]
Testing deleting multiple sites in master // MySQL,  and this still working as expected..
