### ISSUE TITLE
Site selector needs to update on login as

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14116]
As a user I want to see the see the right site list according the user I'm logged or logged as

## Expected Behavior
When user login as we need to refresh the list of sites in the site selector

## Current Behavior
When user login as nothing happen in the site selector

## Possible Solution
Listen for the changes un Auth

## Known Workarounds
Refresh the whole page

## Steps to Reproduce (for bugs)

1. Login
2. Create sites
3. Assign sites to diff user
4. Login as an user and see the list of sites in the site selector doesn't update

## Acceptance Criteria

1. When user login as update the list of the sites in the site selector
2. If the current site is not available in the new list set the default site and if not set the first site as current site
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by wezell** [comment]
Again, login as should refresh the whole page which should short circuit all the issues like this.

**Comment by bryanboza** [comment]
We continue with problems here, now after you try to log in as we are updating the site selector component, but we try to the default user and if you don't have permissions we have an error on log and we are unable to show the component 
LOG: https://gist.github.com/bryanboza/46057e0fe873ff43e2ec41143b7b89bb
To reproduce: 
1. Create a new site 
2. Create a new role and give full permissions just to the new site 
3. Create a new user and set the new role 
4. Login as using the new user

Here we need to update the site selector just with the new user, and in this case, we have an error on the log and we load all the UI without the site selector

**Comment by bryanboza** [comment]
We continue with problems here, we are unable to display the site selector when you login as a limited user.
SC: https://screencast.com/t/PfXHrn1gD

**Comment by fmontes** [comment]
Waiting for this: https://github.com/dotCMS/core/pull/15524/files

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15524

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Oracle and now it is working as expected
