### ISSUE TITLE
Add New Content button in dialog content search not working as expected

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14125]
As a user I want to be able to add content of the content type I'm searching for.

![Screen Shot 2018-04-13 at 3.18.48 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/44e48f68-e5ed-4337-8e33-6a766f6413f7)

## Expected Behavior
Add New Content button should be hidden until one content type is selected in the dropdown.

## Current Behavior
Add New Content button shows all the time.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Click on + > Content
4. The button is there and if you click it it will add content of the first content type after the "All"

## Acceptance Criteria

1. Add New Content button should show only after a content type is selected 
2. Add New Content button should hide when "All" option is selected
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, now we don't have this button if the "All" option is in the drop down
