### ISSUE TITLE
Some UI improvements in the workflow portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14126]
We need do some improvements on this portlet because have a UI issues 
 
- [ ] Problems when you create a new Scheme with a really log name, or just made a copy of some copy without rename: https://screencast.com/t/6XeppJ4bA4z

- [ ]  We have different background color when you have more that one line of steps into some scheme: https://screencast.com/t/ajnRcEZpHU

- [x] On Firefox, when you try to edit some schema, this is redirecting to the steps window, and in the others browsers we just shows the edit window: https://screencast.com/t/1KX9NLzS3x, also we need show this window centered.

**Comment by wezell** [comment]
We should fix the 2 css issues.
