### ISSUE TITLE
Login as admin user not handling wrong password

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14129]
As a admin user I want to be able to login as another admin user if I have the password.

## Expected Behavior
When admin user try to login as admin2 it should work.

## Current Behavior
When admin user try to login as admin2 an alert with an error is shown.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login as admin 
2. Try to login as admin2
3. Alert thrown.

## Acceptance Criteria

1. Add a hint to the password field: "Please reenter your user password"
2. If auth is unsuccessful:
    - Add a message on the top of the form: "Your password is wrong, please try again"
    - Don't show the alert
    - Focus in the password to user can type the password again
3. User should be able to hit enter to send the form.
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now this is working

**Comment by bryanboza** [comment]
Fixed, tested on master and now I am able to login as any admin user.
