### ISSUE TITLE
[Templates] Limited user cannot get list of Containers it has access to.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14134]
## Expected Behavior
Limited users, even if they have full permissions, should have access to all Templates/Containers once a Page is created, or a Template is edited and wants to add a new container to it.

## Current Behavior
Any non-admin user with full grants over a Site (including Publish permissions for all assets) cannot retrieve the list of Containers it has access to because of a bug in the system.

## Steps to Reproduce (for bugs)

1. Go to Roles portlet. Select Contributor Role
2. Assign Add To/Edit/Publish permissions to all assets.
3. Assign Templates and Containers as available layouts/portlets for this user. This can be made on Role's "Tabs" section.
4. Login As Joe Contributor.
5. Go to Templates portlet.
6. Select and template and edit it.
7. Click on "Add Container" button. Dropdown shows as empty.

Stacktrace:

https://gist.github.com/joseorsini/ef4d83d65afd679ae9e74d046cc3aefa 

## Context
Reported by customer: 
https://dotcms.zendesk.com/agent/tickets/95579

## Your Environment

* dotCMS version used: 4.3.2, master.
* Browser Name and version: Any Browser.
* Operating System and version: Any supported OS.
* Application Server and version: Any supported application server.
* Java Brand and version: Any supported Java version.
* Database and version: Microsoft SQL Server 2016.
* Application module (if apply): N/A.

Acceptance Criteria: 
- Need to be tested in 4 DBs

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14138

**Comment by DeanGonzalez** [comment]
I just tested and got the original reported behavior running on Postgres with latest master.

**Comment by joseorsini** [comment]
@DeanGonzalez I had the same behavior too while I was doing some tests. Thought it was something related to my local, but indeed seems to be a performance related issue.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14315

**Comment by nollymar** [comment]
PermissionedWebAssetUtil.java has been removed here: https://github.com/dotCMS/core/pull/14344

**Comment by bryanboza** [comment]
Fixed, tested on master and now I am able to add/edit/remove templates and containers without problems
