### ISSUE TITLE
Update Tomcat to at least 8.5 for HTTP/2 support

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#14140]
Currently dotCMS does not work with HTTP/2. In order to enable HTTP/2 support an update to Tomcat 8.5 or higher is required.

## Expected Behavior
The dotCMS admin interface should work with HTTP/2.

## Current Behavior
The dotCMS admin interface does not work with HTTP/2 because the embedded Tomcat 8.0 does not support it.

## Possible Solution
Update the embedded Tomcat to Version 8.5 or higher for HTTP/2 support, see:
https://stackoverflow.com/questions/30855281/tomcat-support-for-http-2-0

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Activate HTTP/2
2. Try to use the dotCMS admin interface

## Context
We would like to enable HTTP/2 for our entire website, including the dotCMS admin interface.

## Your Environment
* dotCMS version used: 4.3.2
* Browser Name and version: any
* Operating System and version: Linux (Debian 9)
* Application Server and version: embedded Tomcat 8.0
* Java Brand and version: Java 8
* Database and version: MySQL 5.7
* Application module (if apply):

**Comment by wezell** [comment]
This is part of the 5.0 release

**Comment by wezell** [comment]
So, to be clear, the 5.x series has Tomcat 8.5.  We are not planing on shipping or testing with Http/2.0 enabled in the upcoming release, though that will change as we move further down the release 5.x cycle
