### ISSUE TITLE
Sporadic problems on starting from clean starter

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14145]
On a few occasions on 3 different machines, I have had problems with dotCMS not starting up cleanly from a clean starter.  It is getting stuck indexing the content.
## Expected Behavior

Expect it to start up cleanly and to index all of the data from the starter.

## Current Behavior

On this specific situation, 2 pieces of content refused to index.  The log shows this
```
16:54:53.135  INFO  util.ImportExportUtil - Records left to index : 2
16:55:53.295  INFO  util.ImportExportUtil - Records left to index : 2
16:56:53.456  INFO  util.ImportExportUtil - Records left to index : 2
16:57:53.618  INFO  util.ImportExportUtil - Records left to index : 2
16:58:53.779  INFO  util.ImportExportUtil - Records left to index : 2
16:59:53.939  INFO  util.ImportExportUtil - Records left to index : 2
17:00:54.101  INFO  util.ImportExportUtil - Records left to index : 2
17:01:54.263  INFO  util.ImportExportUtil - Records left to index : 2
17:02:54.424  INFO  util.ImportExportUtil - Records left to index : 2
17:03:54.581  INFO  util.ImportExportUtil - Records left to index : 2
17:04:54.741  INFO  util.ImportExportUtil - Records left to index : 2
17:05:54.900  INFO  util.ImportExportUtil - Records left to index : 2
17:06:55.059  INFO  util.ImportExportUtil - Records left to index : 2
17:07:55.218  INFO  util.ImportExportUtil - Records left to index : 2
17:08:55.376  INFO  util.ImportExportUtil - Records left to index : 2
17:09:55.533  INFO  util.ImportExportUtil - Records left to index : 2
17:10:55.697  INFO  util.ImportExportUtil - Records left to index : 2
17:11:55.858  INFO  util.ImportExportUtil - Records left to index : 2
17:12:56.019  INFO  util.ImportExportUtil - Records left to index : 2
17:13:56.179  INFO  util.ImportExportUtil - Records left to index : 2
```

[Full logs here](https://gist.github.com/brentgriffin/14615323e23a4eaae25b1918f0fb6b07)

## Possible Solution

N/A
## Known Workarounds

Stop dotcms, blow away database and dotcms installation and try again.  Does not usually happen twice in a row.

## Steps to Reproduce (for bugs)

1.  Untar dotcms build tar
2.  Config db
3.  Start db 
4.  Monitor catalina.out
5.  Repeat as necessary till happens

## Context

Just trying to do some testing in docker but have seen problem in and out of docker.

## Your Environment

* dotCMS version used:  master/latest
* Browser Name and version: N/A
* Operating System and version:  Ubuntu linux, Alpine Linux, OSX
* Application Server and version:  embedded Tomcat
* Java Brand and version: 8
* Database and version: 9.5, 9,5, 10.1
* Application module (if apply):

**Comment by wezell** [comment]
See if setting `REINDEX_ON_SAVE_IN_SEPARATE_THREAD=false` improves your results

**Comment by brentgriffin** [comment]
Definitely sporadic but does NOT seem to be related to this setting.  So did some additional testing with REINDEX_ON_SAVE_IN_SEPARATE_THREAD set.

With this set to false:  1 out of 10 clean starts failed
With this set to true (the default)  1 out of 10 clean starts failed

**Comment by brentgriffin** [comment]
Had this problem happen twice this morning.  Here is DB info from the most recent occurrence:

```
dotcms=> select * from dist_reindex_journal;
  id  |            inode_to_index            |            ident_to_index            | serverid | priority |        time_entered        | index_val | dist_action
------+--------------------------------------+--------------------------------------+----------+----------+----------------------------+-----------+-------------
 1026 | ea01b0cb-8c3c-437c-bde8-19440b582851 | ea01b0cb-8c3c-437c-bde8-19440b582851 |          |       40 | 2018-05-10 15:36:31.241664 |           |           1
(1 row)
```
**Strange that inode and ident match**

When I tried to query that inode in contentlet table, there are no matching records.
```
dotcms=> select inode, identifier from contentlet where inode = 'ea01b0cb-8c3c-437c-bde8-19440b582851';
 inode | identifier
-------+------------
(0 rows)
```
contentlet table does have a record with that identifer:
```
dotcms=> select inode, identifier, structure_inode from contentlet where identifier = 'ea01b0cb-8c3c-437c-bde8-19440b582851';
                inode                 |              identifier              |           structure_inode
--------------------------------------+--------------------------------------+--------------------------------------
 d3ba9fd8-e4cf-41d4-a812-2039d1a01541 | ea01b0cb-8c3c-437c-bde8-19440b582851 | f6259cc9-5d78-453e-8167-efd7b72b2e96
(1 row)
```

Content is of "Calendar and events" type:
```
dotcms=> select inode, name, description from structure where inode = 'f6259cc9-5d78-453e-8167-efd7b72b2e96';
                inode                 | name  |     description
--------------------------------------+-------+---------------------
 f6259cc9-5d78-453e-8167-efd7b72b2e96 | Event | Calendar and events
(1 row)
```

dotcms log from this occurance:  https://gist.github.com/brentgriffin/764bf3f170c944b4f792b7c4c5f27671

**Comment by wezell** [comment]
The second query - contentlet table - should be:
```
select inode, identifier from contentlet where identifier = 'ea01b0cb-8c3c-437c-bde8-19440b582851';
```

**Comment by brentgriffin** [comment]
Should the inode and identifier values be the same in the dist_reindex_journal table?

**Comment by wezell** [comment]
oh, I see what you are saying.  Yes, both columns in the dist_reindex_journal are the identifiers.

**Comment by wezell** [comment]
Be mindful of these changes: #14145

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14450

**Comment by brentgriffin** [comment]
I have been running with this code and have restarted more than 12 times today so far on two of the environments where I have seen this problem before.  Normally, I would have seen this problem 2 or 3 times by now but have not seen it at all today.  Best I can tell at this time, this issue has been resolved.

**Comment by brentgriffin** [comment]
HOWEVER, I am concerned that I did see any code added to log index failures.  It seems that the cause for this failure was addressed; however, if another problem occurs in the future, the indexing will fail without any information providing insight into the failure.

**Comment by nollymar** [comment]
@brentgriffin where did you see that code? If any problem arises during indexing process we should be able to see it in our logs. Indeed, with this PR we removed the flag to ignore malformed dates

**Comment by brentgriffin** [comment]
Right - what I am saying is that I did not see that code.  Every minute it was logging how many items were left to index but was not logging any thing about why those records would not index.  And I did not see that we added any code to do that going forward.

**Comment by nollymar** [comment]
We do log this info, indeed, it helped me to solved this issue. When there is something wrong during the indexing process, an error like this will be logged: 

`12:19:41.062  ERROR reindex.ReindexThread$1 - Error indexing content [failure in bulk execution:
[68]: index [working_20180507121910], type [content], id [9f303322-a908-4df0-8194-e1323f11b008_1], message [java.lang.IllegalArgumentException: mapper [calendarevent.originalstartdate] of different type, current_type [date], merged_type [text]]
[69]: index [live_20180507121910], type [content], id [9f303322-a908-4df0-8194-e1323f11b008_1], message [java.lang.IllegalArgumentException: mapper [calendarevent.originalstartdate] of different type, current_type [date], merged_type [text]]]`
