### ISSUE TITLE
System error trying to add a new content to pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14147]
We have a  system error when you are tying to add a new content to some page, and select multiple content types in the drop down and at the end leave the "All" option. 

## Expected Behavior
If the **"All"** option is selected, the system should show another window to select the content type that you want to add content 

## Current Behavior
We shows an error because we send a null parameter 
SC: https://screencast.com/t/ucGdtuIbp 

Also if you since the first time leave the all option and click to add new content, the system is trying to add the first in the list, as in previous versions we need show a new window with the list of the available contents to select what content type do you want to add a new piece. 

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Add a new page  
3. Try to add a new content 
4.  In the add content window select some specific content type, and then bring back to "All" 
5. Click in the add new content button 

## Your Environment
Tested on the last master // MySQL // FF

**Comment by fmontes** [comment]
Dupe: https://github.com/dotCMS/core/issues/13955
