### ISSUE TITLE
Esc key should back to listing from content type create

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14165]
As a user I want to be able to go back to the listing if I don't want to create a content type

## Expected Behavior
If user hits + to create a content type it should go back to the listing if hit esc key

## Current Behavior
esc key does nothing

## Possible Solution
N/A

## Known Workarounds
Click back in the browser button.

## Steps to Reproduce (for bugs)

1. Login
2. Go to content types
3. Click in create
4. Hit esc key, nothing

## Acceptance Criteria

1. In create content type screen if user hit esc it should go back to listing (same if it gets there by url)
2. In edit content type if hit esc just close the dialog (this is working, just make sure not to break it)
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is closing the angular dialog. Tested on master // postgres // FF
