### ISSUE TITLE
Improve the Commit Listener in order to execute listener at the very end

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#14161]
Currently we do no have a way to run listener at the very end, for instance when the index is done.
We need a way to add listener at the very end of the finalize listener executions

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/13812

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14162

**Comment by bryanboza** [comment]
This changes breaks the auto refresh of the dotSiteSelector field, this when you add//remove sites

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14228

**Comment by bryanboza** [comment]
Now is working the event when you create a new site, but isn't working with the delete

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14267

**Comment by bryanboza** [comment]
Hey guys, after test again now we capture the add/remove events. But also we have more cases here: 
e.g. : When you archive some site we remove this from the siteSelector, but if you unarchive, we need refresh the component again and this isn't working.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14320

**Comment by bryanboza** [comment]
Fixed, now this events are working properly
