### ISSUE TITLE
Adding Related Content with REST API adds relationship in wrong order

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14179]
Tested on latest 4.3.2

When using a self-join relationship, and submitting a relationship via rest api, the submitted content ends up becoming the parent instead of the child of the content who was queried for in the relationship.

![bug](https://user-images.githubusercontent.com/1569167/39070787-ebb45152-44a1-11e8-953c-f9e0cd5ef104.png)

Here is how to reproduce:

- Set up regular content, content type called Standard and give it a single text field called title
- Next, add a self-join relationship from Parent_Standard to Child_Standard

![relationship](https://user-images.githubusercontent.com/1569167/39071976-34286d7a-44a6-11e8-80f4-4b62489441fa.png)

- Now add a new piece of content called "Table of Contents" and save/publish
- Re-edit the contentlet and copy the id of the contentlet.  In this example, "3c4fc6c8-ce12-4775-91ee-cee7fae6ac21"
- Next place create a new page in dotcms and drop a simple widget on the page with the following form code: https://gist.github.com/DeanGonzalez/ab133af540813448acd82908ba23c296
- Change line 59 of the code and insert the identifier of your table of contents content into that line:
'Parent_Standard-Child_Standard': '+structureName:Standard +identifier:3c4fc6c8-ce12-4775-91ee-cee7fae6ac21'
- Save and Publish the form, and then in a new browser or new session, view the form page and submit a new content title using the form.
- Now look at the content on the backend - the bug is that the relationship is reverse.  The content submitted should have become the child of "Table of Contents" but instead, the "Table of Contents" is now the child of the submitted content.

**Comment by DeanGonzalez** [comment]
I tested with a relationship to a different content type as well, and it is also broken.  So it does not seem to matter how you create the relationship, whether self-join or not, the submitted content becomes the parent of the content submitted, which is reverse behavior to what we have documented and does not seem to match the normative use case either. https://dotcms.com/docs/latest/save-content-using-the-rest-api#relationships

**Comment by oarrietadotcms** [comment]
I think the problem could be around [this line](https://github.com/dotCMS/core/blob/5e54ce99dce21c0f31aadfc999ecd0f94e596c75/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L2794). The [isParent method](https://github.com/dotCMS/core/blob/8ed28fc8b7bd3ff9f1cccf9b488511283e02ff9a/dotCMS/src/main/java/com/dotcms/contenttype/business/RelationshipFactoryImpl.java#L314-L319) (by the way, I hate that name and the getter method name also: isHasParent()) could be ignoring the fact that the relation is between same Content Types and setting the value as hasParent = false.

Just my two cents...
