### ISSUE TITLE
Make #dotedit works in new edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14183]
As a user I want to be able to use the ```#editContentlet(inode)``` in my vtls

## Expected Behavior
When user add ```#editContentlet(inode)``` in edit mode should show an icon to edit the contentlet

## Current Behavior
Not showing anything.

## Acceptance Criteria
1. Add icon to edit the contentlet in the list
2. Click on the icon should the contentlet dialog editor
3. When user update a contentlet it should show the changes in the page
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by alfredo-dotcms** [comment]
Bug found when navigating and going through the pages, then when you click on a specific news it shows 2 times. And when you try to edit it, after you save it, it crash and the news dissapears
https://monosnap.com/file/AeiRUxUW0OAQyjsbUdh3BeRonfGxwN

**Comment by fmontes** [comment]
What @alfredo-dotcms is reporting we might have to leave it as a known issue, because our endpoint doesn't support custom urls, issue created: https://github.com/dotCMS/core/issues/14483

**Comment by fmontes** [comment]
Edit mode page DOM is not getting refreshed after a VTL is updated.

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected
