### ISSUE TITLE
Save & Publish sub-action should release the content in case is locked 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14198]
After execute the save & publish or the publish action, we need release the content and unlock

## Expected Behavior
As in previous version, when you execute the save & publish or a publish action in workflows, we need unlock the piece of content

## Current Behavior
We execute this actions but the piece of content still locked 

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Add a new page (save & publish)
3. Try to edit this page and lock for editing 
4. Execute the save & publish again 

## Your Environment
Tested on master  // MySQL // FF

**Comment by jgambarios** [comment]
We need to add the **Lock** and **Unlock** actionlets to the *System Workflow* and generate a new starter zip.

**Comment by wezell** [comment]
moved to #14323
