### ISSUE TITLE
Login as should redirect to first portlet

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14199]
As a stakeholder I need that when an user login/logout as the system redirects to the first portlet.

## Expected Behavior
Login/logout as should redirect to first portlet.

## Current Behavior
Login/logout as reloads the current portlet.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Login as another user
3. No redirection happening

## Acceptance Criteria

1. Login/logout as should redirect to first portlet, this should happen no matter which page or portlet we're in.
2. Clean up subscribe for auth in other parts of the app where we don't need it anymore.
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by fmontes** [comment]
If you are in the first portlet and you login/logout as... the page (iframe o angular component) is not being refresh.

**Comment by fmontes** [comment]
While QAing this I found an issue with the menu and create this: https://github.com/dotCMS/core/issues/14295

**Comment by bryanboza** [comment]
Hey guys @wezell @fmontes I have a doubt here.

Ok when I login as we should redirect to the first portlet, but when I logout as, I should bring back to the last portlet or redirect to the first again. 

Asking because right now we redirect to the first on the logout-as too, but one of the principal functions of the login-as feature is to see how are the permissions, preview of documets, content etc, this as limited users, then I think the system will be more usable if we are able to bring back to the last portlet after logout-as.

**Comment by wezell** [comment]
I think the first portlet is ok for now.

**Comment by bryanboza** [comment]
Ok then fixed, tested on master // postgres // FF
