### ISSUE TITLE
Update Template selector in page properties

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14204]
As a user I want to know when a page have a layout or template and be able to change it from the page.

## Expected Behavior
Template dropdown field page properties should handle when a page have a layout selected.

## Current Behavior
Template dropdown field page properties does nothing.

## Possible Solution
Need work in the backend that saves layout, in case we have a layout created, then we change it for a template and then we try to save a layout again.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page layout
3. Go to the page property

## Acceptance Criteria

1. If the page have a layout created
    - The value of the dropdown should say: Custom Page Layout
    - The dropdown should allow user to select a template
2. If the user change the layout for a template and save the page we should remove the layout from the DB.
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
