### ISSUE TITLE
We need filter according the permissions the conte types list on the add new content tool in the angular menu

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14200]
As stakeholder, We need filter the list of the content types on the add new content tool of the angulat menu (+ button), because don't make sense the limited user be able to see all the private content types that I have and they don't have permissions to see. 

Also if you login directly, not using the login as feature, we are unable to use it because the ("+") button is disabled, also if you have permissions to add content to content types. 

 
## Expected Behavior
We need just show the exact list of content types that we show in the content search portlet

And if you login directly as limited we need enable this button and show the same list 

## Current Behavior
We are showing the complete list of the existing conte types to the limited user when try to use this tool
**_SC Using the login as:_**
![case1](https://user-images.githubusercontent.com/2641437/39162902-18d80710-4735-11e8-8bed-fe0eaf154eee.gif)

**_SC login directly:_**
![case2](https://user-images.githubusercontent.com/2641437/39163158-77f3657c-4736-11e8-9610-8427f25232d4.gif)

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Using the login as try to login as any limited user (chris publisher)
3. Try to use the add new content tool in the angular menu (the "+" button) 

## Your Environment
Tested on master // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14284

**Comment by bryanboza** [comment]
After test now we already have the backend part, the endpoint now is filtering the contents, now we need refresh this component from angular every time you login and login-as... 

## Aceptance Criteria

- [ ] Refresh the component every time you login 

- [ ] Refresh the component every time you login-as

- [ ] Refresh the component every time you logout-as

- [ ] Test in all the browsers 

- [ ] Unit test

**Comment by fmontes** [comment]
We're getting rid of the + button in here: https://github.com/dotCMS/core/issues/14495
