### ISSUE TITLE
Update content search toolbar

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14223]
As a stakeholder I want to be consisten with all the add asset functionality in the system

## Expected Behavior
1. Add and import content should be to the right
2. Actions should be to the left.

## Current Behavior
Is the other way around

## Possible Solution
JSP level.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. GO to Content > Search

## Acceptance Criteria

1. The ... buttons should be a dropdown on the left with the label: "Actions"
2. The "Add new content" dropdown should be a blue button on the right with the + sign
3. They should keep acting as they are right now:
    - Actions will be disable until checkboxes in the list are checked.
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14287

**Comment by bryanboza** [comment]
Fixed, here we just change the order, we still pending change the actions by conte type in #14237
