### ISSUE TITLE
Workflows export, add a version to the response

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#14230]
on the rest workflow, add a version to the response on export

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14235

**Comment by bryanboza** [comment]
Fixed now we have version in the export
https://github.com/dotCMS/core/blob/fc04ee3a993a0198b12f0f703511b31949b8f30b/dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java#L78
