### ISSUE TITLE
Avoid breaking copyContentlet process because of permission reference not being inserted.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14232]
Whenever a content is copied between folders, it is possible that due to permission errors like this happen: 

https://gist.github.com/joseorsini/726a5eb838684edc35c916147e776762

Although the process of copying permissions from the old to the new content executed here 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L5225 

may return an unexpected error here 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitFactoryImpl.java#L2292 

the process should continue, knowing that the permission reference is inserted anyways whenever the content is requested either on frontend or backend requests.

## Current Behavior

If the permission reference is not immediately inserted, the process of copying the content is affected and multi-tree relationships are lost. Content is not automatically published (in case the original version is).

## Possible Solution
Capture potential permission-related issues that should not prevent contents from being copied.

## Known Workarounds
None

## Context
Reported by customer
https://dotcms.zendesk.com/agent/tickets/95727

## Your Environment

* dotCMS version used: 4.2.2, 4.3.3.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any application server.
* Java Brand and version: Any Java 8 version.
* Database and version: Any supported DB.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14233

**Comment by dsilvam** [comment]
Not an issue anymore - Fixed in master
