### ISSUE TITLE
Make Content Search Screen workflow aware

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14237]
We have this issue.  Thoughts on how to solve?  We will not be able to release 5.0 like this.

![screen shot 2018-04-27 at 6 36 10 am](https://user-images.githubusercontent.com/934364/39358976-100bb3a8-49e6-11e8-98de-4e00850338b1.png)

**Comment by bryanboza** [comment]
That happens with license, and those aren't the system workflow actions, those are the old coded actions that we had before create the system workflow

**Comment by jdotcms** [comment]
these actions seems to be hardcoded
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/view_contentlets.jsp#L549
