### ISSUE TITLE
Update stater quest theme template.vtl

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14244]
As a users I want to be able to add sidebars, gaps and every type of columns to my page

## Expected Behavior
When user add a sidebar or a gap to the layout it should be able to use it in the page

## Current Behavior
Sidebar and gaps are not working in the page

## Possible Solution
Need to update the ```template.vtl```

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. Edit a layout and add a sidebar and containers
4. Try to add content to that sidebar...

## Acceptance Criteria

1. Homepage
1. Sidebar should render left and right correctly
2. User should be able to add content to the sidebar in the page
3. Users should be able to add columns any sizes and any gap
4. Make [news listing pagination](https://www.screencast.com/t/KF82QeAvtr1) looks correctly
5. [Search result page](https://dotcms.slack.com/files/U5B1SC4KG/FAHHDM45S/site_search_error.gif) looks correctly
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
8. Unit test

**Comment by hmoreras** [comment]
Changes ready at https://gist.github.com/hmoreras/f729747589314b5770c5446d0f77ed03
