### ISSUE TITLE
500 Error after clicking "Download Index Snapshot"

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#14243]
Log details: https://gist.github.com/nollymar/e1a58f62a51d2e3155ef52886901ce02

## Steps to Reproduce (for bugs)

1. Go to Maintenance -> Index Tab
2. Right click on an index and select "Download Index Snapshot"

## Your Environment

* dotCMS version used: master (dotCMS 5.0)
* Browser Name and version: Google Chrome
* Application module (if apply): Maintenance -> Index

## Acceptance

- [x] Download snapshot successful against a large dataset, e.g. dotcms.com
- [x] Upload/restore snapshot works successfully.
- [x] Integration test for both download an upload/restore

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14280/files

This feature was working only when an absolute `path.repo` was defined. With this PR, both absolute and relative paths are supported. It was not possible to implement an IT for this particular case because restoring the ESClient in our IT environment would have been needed, however, ITs already exist for download/restore snapshots implementations.

Download/Restore Snapshot functionalities have been tested after this change.

**Comment by dsilvam** [comment]
Note to QA: let's do first check mark in the acceptance criteria

**Comment by dsilvam** [comment]
Tested with dotcms.com data. Downloaded and restored snapshot. Download took ~20s, and restore ~5s.

**Comment by bryanboza** [comment]
After test, now it is working from UI, but via REST we need standardise the endpoint 

- [ ] We have a 500 error in case of no credentials, we need a 401 here 

- [ ] The same thing with limited user or invalid credentials

- [ ] In case you send a wrong file, we need return a 400 error 

- [ ] We have a 500 error in case you try to restore the same index twice

**Comment by bryanboza** [comment]
New related issue on #14318

**Comment by bryanboza** [comment]
Need retest with snapshots of real database...

**Comment by dsilvam** [comment]
Note to changelog: the entire resource `/api/esindex` has been deprecated in favor of `api/v1/esindex`.

**Comment by dsilvam** [comment]
Note to Doc: all endpoints' paths in this page https://dotcms.com/docs/latest/restful-api-to-manage-indexes, need to be updated from ~`api/esindex`~  to `api/v1/esindex`

**Comment by bryanboza** [comment]
Fixed, tested with a real snapshot of 8 gb, and now I'm able to restore snapshots without problems

**Comment by DeanGonzalez** [comment]
Documented here: https://auth.dotcms.com/docs/latest/restful-api-to-manage-indexes
and in change log

**Comment by DeanGonzalez** [comment]
Added to changelog: https://auth.dotcms.com/docs/latest/changelogs#RestApiChanges5.0.0
