### ISSUE TITLE
Self-join relationship not saving as child, only parent

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#14253]
Steps to reproduce
1. Create a Test Content Type with only Two fields: Title (Text) and Description (Text area)
2. Create a M-N relationship with this same Content Type as Parent and Child content types.
3. Create at least 5 contents under this content type.
4. For one of the contents you create, relate 2 different contents as parent contents, and 2 other contents as children contents. The relationships tab should look like this.

<img width="1237" alt="screen shot 2018-03-14 at 8 55 52 am" src="https://user-images.githubusercontent.com/1717110/37407010-ad06b95c-2766-11e8-8ed3-ef52c63f4b77.png">

Issue is after saving the content, only the parent relationships are shown (Title 0002, Title 0001), with the child ones showing nothing (Title 0005, Title 0004 not listed)

Acceptance:
- [ ] Above case working  
- [x] Integration test if possible

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
