### ISSUE TITLE
Test sitesearch keywords

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#14258]
Let's make sure searching by keywords is working ok in sitesearch

1. Edit or create a new page and fill the SEO Keywords with some value.
2. Run sitesearch job at least on the host and lang of the page in 1. 
3. Make sure you get results in the sitesearch screen when searching by your value used in 1.

**Comment by nollymar** [comment]
Working fine.

- Site search was tested in front end, the most relevant keywords were listed as expected with some styling details 

- Filtering by keywords on a site search index in backend returns the expected records.

Both tests were done using several keywords and pages.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and this is working as expected
