### ISSUE TITLE
Workflow filter needs some styling help 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14274]
Related to #14185 

Now we can filter actions by role and content type, but we need some UI help here 

## Expected Behavior
We need organize both drop downs fields and be able to see without problems in all the supported browsers 

## Current Behavior

- [ ] This fields looks misaligned 
<img width="741" alt="img1" src="https://user-images.githubusercontent.com/2641437/39536508-07d33f32-4df4-11e8-9632-d3cdf6370e40.png">

- [ ] We need remember the selection after click in the field and then click out of the field 
SC: https://screencast.com/t/8JGo8O8qFj

## Steps
1. Login as admin
2. Go to Types & Tags --> Workflows
3. Select any of the workflows 
4. Look the filter 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
fixed
