### ISSUE TITLE
Unify render and renderHTML endpoints

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14288]
As a stakeholder I don't want duplicated endpoints.

## Expected Behavior
Only one endpoint

## Current Behavior
Right now we have render and renderHTML endpoint

## Possible Solution
N/A

## Acceptance Criteria

1. Keep only /render endpoint
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14292
