### ISSUE TITLE
Workflow Link Broken in Workflow Emails

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14283]
This has probably been broken for a while, tested in latest release:

When emails are generated thru the workflows and a "notify assignee" sub-action is present, then the email template (/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/velocity/static/workflow/workflow_email_template.html) sends an email:

![worflowwithnulllink](https://user-images.githubusercontent.com/1569167/39547411-c1c4a3b6-4e14-11e8-9c3f-7975df2e8658.png)

This email template expects that a `${workflowLink}` is being set:

```
	 <tr bgcolor="white">
		 <td align="right" valign="top">
			<font color="gray"><b>$structureName:</b></font>
		</td>
		<td>
			<a href="${workflowLink}">$!{workflowTaskTitle}</a><br>
		</td>
	</tr>
```  
However, this workflow link ends up being sent with some `Null` values for id's at the beginning of the pathing, thus resulting in a 404, as shown in this example:

```  
https://demo.dotcms.com/c/portal/layout?p_l_id=&p_p_id=workflow&p_p_action=1&p_p_state=maximized&p_p_mode=view&_workflow_struts_action=/ext/workflows/edit_workflow_task&_workflow_cmd=view&_workflow_taskId=9dcb1888-2ce3-482a-8675-44464ef5bce0  
```  

We should fix the way this workflow link is built, so that after login, the user is brought to the detail of the specific task (permissions permitting)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14521

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14637

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
