### ISSUE TITLE
Being able to resize code editor when editing content 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#14289]
The code editor should be resizable to ease the editing.
See: 
<img width="1682" alt="00000178" src="https://user-images.githubusercontent.com/1576794/39586356-7ba54932-4ebc-11e8-802d-17d40971a509.png">

## Possible Solution
https://ace.c9.io/#nav=api&api=editor

## Acceptance Criteria
1. Make resizable code editor 
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
Content --> Search --> Simple Widget

On widgets the modal renders a `textarea` which is resizable on all browsers except IE. To make it resizable on IE the textarea component needs to be changed for the ACE Editor component

**Comment by wezell** [comment]
I believe this is taken care of in another catch all ui task.
