### ISSUE TITLE
For Relating Content via REST API - Add Parent and Child Parameter

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14294]
Right now the only way to add related content via a REST API form is something like this:
```  
 //Relates the standard to the parent doc but - child doc relationships are not maintained
			  'Parent_Standard-Child_Standard': '+structureName:StandardsChangeRequestForm1 +identifier:' + parentId 
```  
Where `parentId` is the id of the parent content, and therefore, the content being submitted becomes the child of that parent content.  Ths works just fine.    

However, if we are updating a piece of content we need a way to relate both parent and child doc to a content object that we have loaded in a form, otherwise we can't load and maintain existing relationships when updating content.  Therefore we need to emulate the dotCMS backend GUI behavior that passes a -C (Child) or a -P (Parent) so that the direction of the relationship can be indicated by the code submitting the content.

So we need add a relationship parameter to the content API that can control direction, and we need to make sure this can be called multiple times, and also works with Content Types that are related to themselves (self-join):

```  
 //Relates the standard to the parent doc but - child doc relationships are not maintained
			  'Parent_Standard-Child_Standard -P': '+structureName:StandardsChangeRequestForm1 +identifier:' + parentId, 
 'Parent_Standard-Child_Standard -C': '+structureName:StandardsChangeRequestForm1 +identifier:' + childId
```  
I place `-P` and `-C` in the code above to represent, as a place holder only, a parameter after the relationship name, but I have no idea what that parameter should really look like or where it should be placed.

**Comment by DeanGonzalez** [comment]
Note to QA on what should be tested with this issue:  

- Submit content with self join relationship using one Content Type, and submit multiple related parents, multiple related children.
- Make sure that existing relationships on the Parent or Child content do not get erased
- Submit parent and child relationships using more than one relationship
- Order of multiple related content should reflect the order of the multiple parents or multiple child contentlets using the same order as reflected in the form (REST API call)

**Comment by wezell** [comment]
This will be taken care of #14298
