### ISSUE TITLE
Relationships by api should use the contenttype's fieldVar rather than the  relation_type_value

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14301]
Meaning, if comments has a relationship field called Related Blog `relatedBlog`, then this example from our docsite 
```
curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -H "Content-Type:application/json" -d '{
   contentType:"Comments",
   languageId:1,
   title:"test comment",
   email:"myemail@mydomain.com",
   comment:"this is my cool comment",
   Blog-Comments:"+contentType:Blog +title:picks"
}'
```

would become:
```
curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -H "Content-Type:application/json" -d '{
   contentType:"Comments",
   languageId:1,
   title:"test comment",
   email:"myemail@mydomain.com",
   comment:"this is my cool comment",
   relatedBlog:"+contentType:Blog +title:picks"
}'
```

**Comment by wezell** [comment]
Just like in the importer, should take either a lucene query OR a comma separated list of identifiers.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15625

**Comment by nollymar** [comment]
With these changes now it's possible to add relationships via REST API in two ways: 
* Using the relation_type_value (as always) 
* Using the velocityVarName of the RelationshipField (if exists)

Both cases support filtering by lucene queries and/or contentlet identifiers. Filtering criteria must be sent as a comma separated list. 

For instance: 
```
//relatedBlog in this case is the velocityVarName of the field
relatedBlog:"+contentType:Blog +title:picks, ea768b68-497c-45a4-88b1-f245232282ba"


//Blog-Comments is the relationship name (relation_type_value)
Blog-Comments:"+contentType:Blog +title:picks, ea768b68-497c-45a4-88b1-f245232282ba"
```

**Comment by nollymar** [comment]
This doc needs to be updated: https://doc.dotcms.com/docs/latest/save-content-using-the-rest-api#relationships

**Comment by dsilvam** [comment]
Passed Internal QA: Created a field comments->blog via rest and then submitted a new Comments content using the curl in the description. Worked as expected: the Comments content was successfully created with the related Blog content
