### ISSUE TITLE
Broken cluster components when autowire disabled

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#14304]
Version: 5.0-nightly-2018-04-30_22-12

With these settings:

`AUTOWIRE_CLUSTER_ES=false`
`AUTOWIRE_CLUSTER_TRANSPORT=false`

`CACHE_INVALIDATION_TRANSPORT_CLASS=com.dotcms.cache.transport.HazelcastCacheTransportClient`

The cache transport is unable to connect consistently (hz client initializes one-way) and network tab shows red on cache.

Also, this error is generated on every heartbeat interval defined by `HEARTBEAT_CRON_EXPRESSION` ("Expecting servers" stays empty despite "Found servers" accurate):

```
19:29:20.003  INFO  cluster.ClusterFactory - Cluster topography has changed. This might force a rewire
19:29:20.003  INFO  cluster.ClusterFactory - Expecting Servers:[]
19:29:20.003  INFO  cluster.ClusterFactory - Found Servers:[{serverId=831c6319-5254-4e87-9b73-cbdad646dddd, clusterId=04606b56-ab45-478b-b634-db1c5909ad5a, ipAddress=10.0.3.7, host=null, name=d7431262f4ee, esTransportTcpPort=9300, esNetworkPort=null, esHttpPort=9200, cachePort=5701, lastHeartBeat=1525462160001, key=null, licenseSerial=1ff7a6fa-f7e8-4214-a95d-48098ee06629}, {serverId=f1864d50-6787-41af-a778-b0d85d95c1cb, clusterId=04606b56-ab45-478b-b634-db1c5909ad5a, ipAddress=10.0.2.9, host=null, name=01b9c911c29f, esTransportTcpPort=9300, esNetworkPort=null, esHttpPort=9200, cachePort=5701, lastHeartBeat=1525462160000, key=null, licenseSerial=d36eb74f-0136-4b3d-a33b-eb88321c58ca}]
```

Change `AUTOWIRE_CLUSTER_TRANSPORT=true` fixes the issues, but we do not want autowire with the hz client transport due to re-initing on every dotCMS topology change.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pulls
