### ISSUE TITLE
Index relationships under contentType:fieldVar, e.g. +blog.comment:123123-123123123-12312312

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14300]
After change: #14298

We need to be able to support the legacy mappings AND this new mapping.

**Comment by nollymar** [comment]
Find PR on this card: https://github.com/dotCMS/core/issues/14298

**Comment by dsilvam** [comment]
Passed internal qa: Field created and able to search by it. 

Tested case: Added a new relationship field to News type, relating to Youtube type (news->youtube) , and associated two news contents to the same youtube content and was able to get them by running: `news.youtubes:1040556d-ce25-4ec5-bae6-39c571813808`

**Comment by bryanboza** [comment]
Related to #15163, we need to wait for this fix

**Comment by nollymar** [comment]
This ticket #15163 is already fixed

**Comment by bryanboza** [comment]
Fixed, tested on master // oracle // FF
