### ISSUE TITLE
Reset Workflow actionlet isn't working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14307]
We have problems with the reset workflow actionlet, this because after execute this action the content still in the same step 

## Expected Behavior
This action should reset the current workflow 

## Current Behavior
We execute the action but isn't reseting the WF

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new piece of content and save and publish 
3. Go to the workflow portlet and add a new action to the published step with the reset sub-action
4. Edit the piece of content and execute this action 
5. Make sure the WF was reseted  

## Your Environment
Tested on master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14375

**Comment by bryanboza** [comment]
Fixed, now this works as expected
