### ISSUE TITLE
Performance issue: Listing templates takes a lot of time 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#14316]
Listing templates from either the Templates Portlet or the Page Asset Edition *when logged in with a limited user* takes a lot of time 

## Steps to Reproduce (for bugs)

There are two paths to recreate this issue:
**First path**
1. Go to the Templates Portlet

**Second Path**
1. Edit or create a new Page Asset
2. Click on the Templates dropdown list

## Your Environment

* dotCMS version used: 5.0
* Browser Name and version: Google Chrome
* Database and version: Postgres
* Application module (if apply): Templates and Create/Edit Page Asset

**Comment by DeanGonzalez** [comment]
This one needs work, the auto-complete on the template listing is broken: https://screencast.com/t/AKyGSPJqL5 - FYI I tested with mysql database, not sure if that made any difference.

**Comment by dsilvam** [comment]
@DeanGonzalez the filtering was fixed and merged into master
