### ISSUE TITLE
dojo js error prevents button rendering on select contentlet screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14311]
Sometimes when you hit the reuse content button from edit mode, the "select" buttons in the content list don't render in dojo - seems there is a dojo id conflict.  

## Screncast

![dojo-error](https://user-images.githubusercontent.com/934364/39708670-ca031948-51e5-11e8-83cf-a6a80503f168.gif)

## Acceptance Criteria

1. Fix JS error on add/select content screen
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master and now we have the correct style of buttons and don't have the js error on console.
