### ISSUE TITLE
Personas and View as in edit mode are enterprise feature

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14327]
As a stakeholder I only want users  to use Personas and View As dropdowns in Edit Page when have enterprise license.

## Expected Behavior
When no enterprise license dropdowns should be disabled.

## Current Behavior
When no enterprise license dropdowns works normally.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit page
3. See gray bar dropdowns

## Acceptance Criteria

1. When no enterprise license dropdowns should be ~~disabled~~ hidden.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Hey guys, I need we need more coverage here. As in previous versions we need hide the personas functionality from the content search and also from the content types portlet if you don't have a EE license. Right now we are allowing add personas content types and also add contentlets to this content types. And both cases should be EE features.

**Comment by bryanboza** [comment]
Ok, seems this is just a edit mode change, the main issue will be fixed here #12962
