### ISSUE TITLE
Make dropdown "fit" width so don't jump when an option is selected

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14328]
As a stakeholder I want to make sure that dropdowns didn't change the width based on the option selected.

## Expected Behavior
Prevent dropdown width jumps

## Possible Solution
Create a util that receive an array of string and give us the width of the dropdown

## Acceptance Criteria

1. Get the longest string option in a dropdown to set the with with a max width of 140px
2. Implement in View As toolbar, content types edit y any dropdown field in content type properties
3. Add ```text-overflow: ellipsis``` to the dropdown selected label
4. Match the design
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by bryanboza** [comment]
Fixed, now looks ok. New functionality enhancement reported here #14328
