### ISSUE TITLE
Implement auto save in edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14326]
As a stakeholder I want users to be able to save the content automatically as they work on the page

## Expected Behavior
When user update the model of the page should save page automatically.

## Current Behavior
User should save the page every time update the page.

## Possible Solution
Listen for the model change and save.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit page
3. Add, move, remove contentlets

## Acceptance Criteria

1. Page should save automatically when model update:
    - Add
    - Move (drag and drop)
    - Remove
2. Remove the "Save" button
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Make sure that autosave don't break when drag and drop happen a quickly
5. Multilanguage
6. Unit test

**Comment by fmontes** [comment]
1. Open a page
2. With no changes navigate in the internal links
3. See the "Saving..." message in toolbar get stuck.

**Comment by bryanboza** [comment]
Fixed, now we are autosaving after doing any change in the edit page.
