### ISSUE TITLE
Make the workflow step associated to a Content into the index

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14337]
We need to include to the indexed content of the Contentlet the step of the Contentlet.

## Expected Behavior
We should be able to filter by step with lucene.

## Notes
Make sure to modify the existing indexes when for example:
* The Contentlet moves to another step
* A change that affects the Step is executed like:
  * Remove a Workflow or step
  * Remove the association between the Workflow and Content Type

---

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java#L219-L226

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/14364

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
