### ISSUE TITLE
Workflow step filter in Content Search

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14338]
We need to add a Workflow Scheme and Workflow Step filter in the Content Search portlet just like in the Workflow Tasks portlet.

## Expected Behavior
We should be able to filter by Workflow step in the Content Search portlet.
We will need to also have the ability to filter content that is in NO workflow or step

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14446

**Comment by bryanboza** [comment]
According to the discussion in Cody, we need to  hide the archived WF from this filter

**Comment by bryanboza** [comment]
Let close this card, we continue working on this on #14538
