### ISSUE TITLE
Add/edit contentlets in angular dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14334]
As a stakeholder I want that users have the same experience to edit a contentlet across the system.

## Expected Behavior
When user try to edit a contentlet it should open the dialog as in edit page

## Current Behavior
In content search when edit a content it open a new page within the iframe

## Possible Solution
Fire an event from the content search iframe and angular catch it.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Search content
3. Open any content

## Acceptance Criteria

1. From content search 
    - Create/edit a contentlet from the angular **dialog** (same as in edit content from a page)
    - Create a contentlet should not close the dialog UNLESS is a page in that case redirect to edit the page
2. From edit page
    - Dialog should not close when user add or edit a contentlet
    - Dialog should close when user reuse a contentlet
3. From site browser:
    - Add a page should open in the dialog and redirect to edit page after save and publish
3. Dialog only close when the user hits "Cancel", ESC key or click outside the dialog
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by fmontes** [comment]
NO redirect after content created is save and published

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14409

**Comment by bryanboza** [comment]
Ok we have a couple of things we need improve here: 

**_From content search:_** 

- [ ] We need refresh the iframe after you close the angular dialog, maybe need verify if have changes before it. Right now if you modify some content and save & publish, then close the dialog, you have the contentlet without changes, and you are able to reopen without see the changes. 
SC:  https://screencast.com/t/GKTt6iYw 

**_From edit page_** 

- [ ] We have a js error when you try to edit some pice of content 
SC: https://screencast.com/t/GKTt6iYw

- [ ] Also we need some styling help here 
SC: https://screencast.com/t/2lpA4scCn

**Comment by bryanboza** [comment]
Ok, after test this again, we need refresh this dialog after executing any action, for example after save and publish we need to refresh the content detail information because now this content step and the actions should be changed 
SC: https://screencast.com/t/XBgtrrNnHn

**Comment by fmontes** [comment]
We're not doing this UX feedback for 5.0, we'll take note for when we redesign the edit contentlet.

**Comment by fmontes** [comment]
@wezell fix this here: https://github.com/dotCMS/core/commit/6300c82bf33435cbe902dd197a3025cd20032ca7#diff-1fb5611e54b3b5bcaddbdc73cacf8e1bR571

**Comment by bryanboza** [comment]
Hey guys, now we are refreshing the actions, but not the step of the content type

**Comment by fmontes** [comment]
@wezell will work on that.

**Comment by wezell** [comment]
done in #14682

**Comment by bryanboza** [comment]
Fixed, now we refresh the dialog window
