### ISSUE TITLE
Calculate workflow batch actions based on the selected Workflow Step

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14339]
We need to calculate what batch actions based on the selected Workflow Step.

![screen shot 2018-04-27 at 6 36 10 am](https://user-images.githubusercontent.com/934364/39358976-100bb3a8-49e6-11e8-98de-4e00850338b1.png)

## Expected Behavior
When an user selects multiple Contentlets on the Content Search portlet we need to calculate the available options based on the selected Workflow Step.

## Current Behavior
We are displaying hardcoded operations.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14575

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14664

**Comment by bryanboza** [comment]
We are able to apply the **Unpublish** action to Unpublished contents from bulk actions. If you try this from the edit of the content this action isn't available. 

FYI: If you call the endpoint this isn't an available action.

**Comment by jgambarios** [comment]
As we discussed the comment above is not a bug.

**Comment by jdotcms** [comment]
When testing: "If the user does not have an ee liceense, we need to hide the "Actions" button."
The button is displayed but the actions available are just unlock and reindex
![Screen Shot 2018-07-05 at 3.59.58 PM.png](https://images.zenhubusercontent.com/577bcb78bf93871ccd9d9591/9a9e5c0a-9593-479f-b218-8f16be8dc5db)
![Screen Shot 2018-07-05 at 3.59.54 PM.png](https://images.zenhubusercontent.com/577bcb78bf93871ccd9d9591/d365782c-b16c-4de5-bb93-8cbc0f39394d)

**Comment by jdotcms** [comment]
These comments:
"
if the calculation returns a single step, the "Actions" button will show the available actions in the dropdown as it does now
if the calculation returns actions from multiple step, the "Actions" button will pop up a modal "Bulk Actions" window that shows the available steps/actions. Something like this:
"

not longer applies, since the pop is always rendered not matter the quantity of options you get

**Comment by jdotcms** [comment]
Testing this:
"We need to wrap the REST call in a debounce function to prevent multiple overlapping calls, a la https://gist.github.com/nmsdvid/8807205#gistcomment-2595895"

I have tried several clicks over the button and just one action is triggered based on the logs in the network tab in the dev tools

**Comment by jdotcms** [comment]
pased internal QA, it looks very well!

**Comment by bryanboza** [comment]
Fixed, tested with multiple databases, and works as expected...
