### ISSUE TITLE
Error message saving layout changes 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14346]
As user we need a success message to now all the changes was saved without problems 

## Expected Behavior
We need show the correct message every time you save changes in the edit mode 

## Current Behavior
If you try to edit something in the layout, and then you try to save, we show an error message here, but the changes was saved. 
SC: https://screencast.com/t/GRWJ35JV2v

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Apply a valid license 
3. Try to edit some page 
4. Edit something in the layout 
5. Try to save the changes 

## Your Environment
Tested on master // postgres // FF

**Comment by freddyucv** [comment]
Fix here: https://github.com/dotCMS/core/pull/14313
