### ISSUE TITLE
Need to import cluster licenses sooner in bootup process

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14349]
Right now when we first startup dotCMS, we do not import the license.zip file until Task00020 which is after the data has been imported and indexed.  The ramification of the issue is that the index is created with only a community license which means that the replica count is 0.  

I have not tested it yet but based on the log files, it looks like we try to load license.dat files way earlier in the startup process.

The current startup process looks like this:
Task00001 creates DB schema
Task00003 creates system roles
Task00004 loads the starter
...
...
Task00020LoadClusterLicenses

If possible, it seems ideal to load the cluster licenses as task 2 instead of task 20 and that ES would be properly configured for an enterprise licensed server rather than for a community licensed server. 
 https://github.com/dotCMS/core/blob/4d1ecbe1573c9875c77e92d44c943d0b9628ff54/dotCMS/src/main/java/com/dotmarketing/startup/runalways/Task00020LoadClusterLicenses.java

## Expected Behavior

When the server starts up for the first time, I would expect for the indexes to have the proper number of replicas based on my environment rather than the limit of 0 for community license.
## Known Workarounds

*  Use a license.dat file for specific starting server.  The license.dat file is imported early in the booting process and allow the ES index to be created with the correct number of replicas based on the ES cluster size.
*  Reindex content after the license has been properly applied.

## Steps to Reproduce (for bugs)

1.  Install dotCMS cluster (or configure for external ES - i.e. docker-compose)
2. Place valid license.zip file in assets directory
3. Startup dotCMS
4. Notice in log that index is created before license is imported
5. Notice that index has replica of 0 instead of 1

## Context

This is causing an issue with ES persistence in Docker.  Since there are zero replicas, the static ES node (that would ensure the indexes are persisted between restarts) may not host a replica of the data and therefore when the system is restarted the index is lost and has to be recreated.

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/622

**Comment by brentgriffin** [comment]
this looks good based on 20180611 nightly build!
