### ISSUE TITLE
Login as should refresh the siteSelector according to permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14347]
As stakeholder I need the system filter the sites acording to permissions when I use the login-as feature

## Expected Behavior
The system should hide the sites from the list if the logged user don't have permissions over this siite

## Current Behavior
We include all the site in the siteSelector list, but if you don't have read permissions over some of the sites and you select this one in the component, we shows an error 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Add a new site 
3. Remove all the permissions to this site and add permissions ONLY to the admin user 
4. Using the login-as login as some limited user (chris publisher)
5. Select the new site in the siteSelector 
6. Check your log file 

## Your Environment
Tested on master // postgres // FF

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/14116
