### ISSUE TITLE
Workflow Copying a page with an extension, e.g. .html appends _copy after the extension

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14345]
Files work correctly, pages are broken:

![screen shot 2018-05-08 at 6 07 25 pm](https://user-images.githubusercontent.com/934364/39785591-b9e4f724-52ea-11e8-8ea6-65e2587d80ac.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14392

**Comment by jgambarios** [comment]
There is a case we are not handling:

1. On a page right click and Copy
   * A copy is made
2. On the same page right click and Copy
   * Fails as already exist a copied page with the same name

We are handling this case with file assets, we need to implement the same fix we applied for files in pages.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14480

**Comment by bryanboza** [comment]
Fixed, now we take the last dot symbol and add the "_copy" before it.
