### ISSUE TITLE
[Contents] Pages that are copied do not retain their multi-tree information.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14359]
## Expected Behavior
When a page is copied from one folder to another, the sort order of all containers added to their containers should be retained.

## Current Behavior
Multi-Tree relationships get their sort_order attribute ignored and defaults to zero. This means the page lose all order of contents added under each container.

## Known Workarounds
Re-order contents manually.

## Steps to Reproduce (for bugs)

1. Create a test page under any folder. Use the blank template for it.
2. Add few contents under this page. 
3. List the contents under this page's unique container with a query like this (you need to grab the page identifier):

```

SELECT mt.child, mt.tree_order, c.title from multi_tree mt, contentlet c where mt.parent1 = '506877ac-a4c0-49b8-855e-49ad009726af' and mt.child = c.identifier order by mt.tree_order asc;
                child                 | tree_order |      title       
--------------------------------------+------------+------------------
 371297d5-615b-4b44-af2c-a59950b1ff72 |          0 | Test 001
 8aa3b048-8921-445c-84ac-c451900cabb4 |          1 | Test 002 Content
 9ec5ef24-2a45-4377-8a45-900c3b724c43 |          2 | Test 003 Content
 48537f6a-1ca4-4148-bc40-fcdb81c0106d |          3 | Test 004 Content
 087998f9-9db5-4008-8f0b-fb36488cc38d |          4 | Test 005 Content
 446a8d06-f3ab-4c57-b731-02ab7dcd0d80 |          5 | Test 006 Content
(6 rows)
```

4. On Site Browser portlet, right click on this page and select "Copy".
5. Select a different folder, right click on it and select "Paste".
6. Grab the newly created page's identifier and re-run the same query from above 

```
SELECT mt.child, mt.tree_order, c.title from multi_tree mt, contentlet c where mt.parent1 = 'd044bd5a-5202-4984-ab4c-bbc8d954f9b3' and mt.child = c.identifier order by mt.tree_
                child                 | tree_order |      title       
--------------------------------------+------------+------------------
 48537f6a-1ca4-4148-bc40-fcdb81c0106d |          0 | Test 004 Content
 087998f9-9db5-4008-8f0b-fb36488cc38d |          0 | Test 005 Content
 446a8d06-f3ab-4c57-b731-02ab7dcd0d80 |          0 | Test 006 Content
 371297d5-615b-4b44-af2c-a59950b1ff72 |          0 | Test 001
 8aa3b048-8921-445c-84ac-c451900cabb4 |          0 | Test 002 Content
 9ec5ef24-2a45-4377-8a45-900c3b724c43 |          0 | Test 003 Content
```

Sort order in the multi tree is never saved, and contents have a different sort order.

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95822

## Your Environment

* dotCMS version used: 4.2.2, latest master.
* Browser Name and version: Any Browser.
* Operating System and version: Any supported OS.
* Application Server and version: Any application server.
* Java Brand and version: Any Java 8 version. 
* Database and version: Any DB version.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/14360

**Comment by wezell** [comment]
Merged and fixed

**Comment by oarrietadotcms** [comment]
PR for 4.3.4: https://github.com/dotCMS/core/pull/16207
