### ISSUE TITLE
Incorrect document count in ES index when replica is greater than 0

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14353]
When replica is greater than zero, we seem to be counting every occurrence of documents rather than the number of documents actually in the ES index.

![image](https://user-images.githubusercontent.com/3208956/39827101-8173987c-537c-11e8-9296-9fbafee36d13.png)

![image](https://user-images.githubusercontent.com/3208956/39827112-87ba8ca4-537c-11e8-9926-08a5391e0005.png)

You can see from the above images that we are essentially doubling the document count because of the replica.  The index actually only has half the number of documents we are reporting.

## Expected Behavior

I expect the document count in the backend of dotCMS to match the number of documents that ES reports the index to have.  e.g. Above I have an index with 1,055 documents and I have one replica of that index. (not 2,110 documents)

## Steps to Reproduce (for bugs)

1.  Startup dotCMS cluster (or external ES via docker)
2. Verify the replica count on your index is greater than 0 (if not, reindex)
3. Compare document count on System->Maintenance->Index page with document count from ES

## Context

Noticed this issue while testing ES functionality in our docker environment.

**Comment by chrismccracken** [comment]
It looks like we are using`live_20180508192230.total.docs.count`(count of docs on primary shard + all replica shards) instead of the more expected `live_20180508192230.primaries.docs.count`(count just from primary shard) from the index stats API. The latter is the real number of dotCMS records in the index.
