### ISSUE TITLE
Logout resource endpoint is executed twice on logout

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14358]
When requesting a Logout from the admin site we are calling twice the `/api/v1/logout`, I was able to verify that using Chrome and with breakpoints in my IDE.

## Expected Behavior
Only one request to the `/api/v1/logout` should be executed.

## Current Behavior
We are requesting twice the `/api/v1/logout` endpoint.

## Steps to Reproduce (for bugs)
1. Login to dotCMS
2. Logout
3. Check in the browser the executed requests

![Twice](https://content.screencast.com/users/jgambarios/folders/Snagit/media/12da3ca2-10c0-4c2c-959d-5646e5b7f79d/2018-05-09_12-49-57.png)

**Comment by wezell** [comment]
Does not hurt anything.
