### ISSUE TITLE
Workflow schemes UI tweaks 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14365]
- [ ] Spend little or no time on the ui "beauty" of these changes.  We will take care of that after they are done.
- [x] Show the Content Types related to the Workflow Scheme in the Edit Workflow modal, and for each Content Type add a link to the edit Content Type portlet
- [x] Remove the identifier under the Workflow names on the Workflow list portlet
- [x] Remove Initial step from the Workflow Scheme in the Edit Workflow modal
- [x] Move the JSON link to the edit modal of Workflows Scheme and to the edit modal of Workflows Steps

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14382

**Comment by bryanboza** [comment]
Fixed, the portlet looks better after those improvements.
