### ISSUE TITLE
We are not respecting the unique validations via REST

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14361]
We are able to add two contents with the same value also when the key is unique if you t ry this via REST. 

## Expected Behavior
We need be able to validate it, as we do if you try from the admin 

## Current Behavior
We allow create contents with the same value also when have the unique property 
<img width="1215" alt="rest validation" src="https://user-images.githubusercontent.com/2641437/39843582-f3303a52-53a8-11e8-99d2-975c11b58be4.png">

## Steps to Reproduce (for bugs)
1. Using this endpoint 
```
http://localhost:8080/api/v1/workflow/actions/b9d89c80-3d88-4311-8365-187323c96436/fire
Body: 
{ "contentletFormData" : {
	"stInode" : "f4d7c1b8-2c88-4071-abf1-a5328977b07d",
	"languageId" : 1,
	"key": "postman",
	"value": "postman"
}
}
```
2. Execute twice with the same body 
3. Go to the admin console 
4. Check the contents of the language variables content type 

## Your Environment
Tested on master // postgres

**Comment by jgambarios** [comment]
I think this behaviour is expected, if you post immediately the second request the index has not been updated yet and thats why does not notice that exist another content with the same key.
