### ISSUE TITLE
UI format fields should not be use on the import and/or export process

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14373]
As part of the changes to the new content types portlet, now we need two extra fields to be able to display in the new portlet. But when you try to import/export content, we need hide this buttons because does not make sense look this here and cause confusion. 

## Expected Behavior
We need hide this field from the import/export process

## Current Behavior
When you try to import in any content type, we have this fields auto selected here: https://screencast.com/t/dH5clr5b

When you export content, we include this fields in the csv file 
https://screencast.com/t/heFKcDvzg

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type 
3. Add a piece of content of this conte type 
4. Try to import/export content 

## Your Environment
Tested on master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14417

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to see this fields in the import/export process
