### ISSUE TITLE
[Contents] Once you copy a site, pages in destination site do not retain their original multi-tree information.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#14378]
Follow up of #14359 

This fix needs to be applied on classes related to Copy Site functionality.

**Comment by joseorsini** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/614

**Comment by erickgonzalez** [comment]
Now when you copy a site the pages are copied with all its content.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
