### ISSUE TITLE
Move to programatic HikariCP

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14385]
I would like to select a non-tomcat connection pool for dotCMS to use moving forward for dotCMS.  This would

1. Allow dotCMS to use docker and Kub secrets in order to prevent configuration errors and allow us great control in the configuration of the pool.
2. Allow for the application to own the datasource rather than the app server, making us more portable  as a .war
3. Provide customers with proper specific extension points - max connections, timeouts, what have you, while choosing sane defaults for dotCMS.
4. Allow us to tie into a "secrets" mechanism for config options - see this article as an example:

https://medium.com/lucjuggery/from-env-variables-to-docker-secrets-bc8802cacdfd

1. Allow customers to override the JNDI default \(if they want to\) by specifying the `jdbc/dotCMS` datasource in the app-server.

## Steps to Hikari

- \[x\] Unrepackage and update our Hikari lib
- \[x\] Migrate the tests to use hikari
- \[x\] Migrate Tomcat to use hikari \(jndi\)
- \[x\] Programatic Pool Config \(like we do for our integration tests but smarter

  - If `jdbc/dotCMSPool` exists in the App server, use it,
  - if `db.properties` exists in the `WEB-INF/classes` folder, use it
  - otherwise we check for secrets and use them,
  - otherwise we check for env variables.

### Worth Reading

https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22

https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

**Comment by brentgriffin** [comment]
background information:  http://www.trustiv.co.uk/2014/06/battle-connection-pools

**Comment by jgambarios** [comment]
**NOTE:** As part of this ticket we need to move the changes made in here https://github.com/dotCMS/core/pull/17505 where we upgrade the db drivers to the **5.3.0** release branch when available.

**Comment by wezell** [comment]
@nollymar Here is a quote from a customer and describes a problem this ticket needs to solve:

> we are currently trying to connect dotCMS to an AWS RDS. For compliance reason we are not allowed to store the RDS credentials in plaintext. According to Amazon the Secrets Manager would be a solution to this. Unfortunately we would have to replace the default JDBC driver provided by dotCMS. Do you have any experience or examples on this?

**Comment by nollymar** [comment]
@wezell I read a bit about https://aws.amazon.com/secrets-manager/ and I saw that they provide an API. Have you visualized how we will support Amazon Secrets Manager or what will be the scope from our end?

**Comment by nollymar** [comment]
> @nollymar Here is a quote from a customer and describes a problem this ticket needs to solve:
> 
> > we are currently trying to connect dotCMS to an AWS RDS. For compliance reason we are not allowed to store the RDS credentials in plaintext. According to Amazon the Secrets Manager would be a solution to this. Unfortunately we would have to replace the default JDBC driver provided by dotCMS. Do you have any experience or examples on this?

We added support for custom implementations. In case you want to use your own implementation, the fully qualified name of the class that implements the logic to initialize the datasource has to be set with this property `DATASOURCE_PROVIDER_STRATEGY_CLASS`

**Comment by wezell** [comment]
We need to update the DBPropertiesDataSourceStrategy to just read in the Hikari properties file and use any values it finds there for its connection pool, rather than translating our custom properties to Hikari values.

**Comment by wezell** [comment]
We will need to update the values in the `db.properties` and the `db-config.properties` as well as revisit the docker image database configuration values.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18493

**Comment by nollymar** [comment]
**Note to QA:** The following scenarios need to be tested: 
- [ ] Deploy a dotcms instance using docker
- [ ] Deploy a dotcms instance in your local environment after setting values in `db.properties`

Please read this comment for further information: https://github.com/dotcms/core/issues/17843#issue-549828629

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.0 // MySQL // FF
