### ISSUE TITLE
Make integration test for PageResource

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#14386]
Make integration test for:

- PageResource#loadJson
- PageResource#render
- PageResource#saveLayout
- PageResource#addContent
- PageResource#renderHTMLOnly

Also make integration or unit test for any API use in the Resource or Helper.

**Comment by bryanboza** [comment]
Also we need add javadoc for each endpoint, we have some ones like "**render**" without this...

**Comment by freddyucv** [comment]
Take off HttpServletRequest and HttpServletResponse parameters from all the methods of HTMLPageAssetRenderedAPI

**Comment by bryanboza** [comment]
Also, we need to add the corresponding test to the "Page API " in order to test the changes that we made on card #18158

**Comment by wezell** [comment]
We did this on another card.
