### ISSUE TITLE
Record in the security logger important workflow transactions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14380]
We need use the security logger in order to have a register of the most important workflow transactions.

## Expected Behavior
We need record the most important workflow transactions in a security log. Specially when you create, remove, import and export 

## Current Behavior
We are not logging nothing on this transactions 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to workflows 
3. Made some important transaction here (create or delete some scheme) 
4. Make sure you have this transaction on logs 

## Your Environment
Tested on the last master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15259

**Comment by bryanboza** [comment]
Fixed, now we log the WF transactions
