### ISSUE TITLE
More workflow styling

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14387]
* Move description field
* Order Content types by name
* Align top bar

**Comment by wezell** [comment]
![screen shot 2018-05-14 at 2 25 39 pm](https://user-images.githubusercontent.com/934364/40015894-b6f8b950-5782-11e8-948e-76ac0efba4e9.png)

**Comment by bryanboza** [comment]
According to the first mockup we need some styling on this window, the scheme id should be the first field, the buttons need be aligned. 
SC: https://screencast.com/t/ymgs2pqmz

**Comment by bryanboza** [comment]
Also, we need to fix that: https://screencast.com/t/l9yOEdOIM

**Comment by fmontes** [comment]
Please fix the dropdown focus and active state colors.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14997

**Comment by fmontes** [comment]
This is not fixed:

1. https://www.screencast.com/t/l9yOEdOIM

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15015

**Comment by bryanboza** [comment]
Unable to scroll when you have multiple workflows 

![scroll](https://user-images.githubusercontent.com/2641437/43549993-77f11102-959f-11e8-853a-a553d9817470.png)

**Comment by hmoreras** [comment]
scroll in multiple workflows and steps, is working.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now it is working as expected
