### ISSUE TITLE
Forms base type should not allow to create a contentlet from

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14399]
As a user I should not be able to create a contentlet of base type "Form".

## Expected Behavior
User should be able to add a form created from the Form portlet but no contentlet of the form type

## Current Behavior
User can create contentlets from form type

## Solution
* When user click in `+ > Form` we open a dialog listing the form content types and the button "Select", we need a component for this.
    - We need a new component for this
    - We should be able to use the same endpoint as the content types but filtered
    - Not sure what we need to do with the "select" button to render the form in the iframe, but is already being rendered, check that code.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page
3. In the container click + > Form
4. List results should be Form base type

## Acceptance Criteria

1. Users should be able to add forms to their pages
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
https://github.com/dotCMS/core-web/tree/issue-Forms-base-type-should-not-allow-to-create-a-contentlet-from

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14631

**Comment by jgambarios** [comment]
Reverting changes: https://github.com/dotCMS/core/pull/14662

**Comment by bryanboza** [comment]
Now we are able to add the form to the page, and we have the base type in the page, but you can't see the form from FE as in the previous version. We have a permissions message here
SC: https://screencast.com/t/Sl0tn14Y

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14748

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14795

**Comment by bryanboza** [comment]
Fixed, now we are able to see forms in FE, new card created here: #14822
