### ISSUE TITLE
Add page properties button to the edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14408]
As a user I want to be able to edit the page properties from the edit page.

## Expected Behavior
When click the "properties" button in the right nav open the contentlet editor for the page.

## Current Behavior
No button .

## Possible Solution
1. Add a button to the right nav in edit page with icon + "Properties"
2. On click call the edit contentlet service.

## Acceptance Criteria

1. When user click the button open the contentlet editor.
2. When the user close the dialog we need to refresh the edit page.
    - User can change anything even the url
    - Need to reload the page correctly
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we have this button
