### ISSUE TITLE
Edit page: Inline editing backend

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14402]
As a stakeholder I want users to be able to edit text fields in contentlets while edit a page.

## Expected Behavior
render endpoint should return HTML ready for editable fields in contentlets.

## Current Behavior
HTML is coming but not in the right format.

## Possible Solution
N/A

## Acceptance Criteria

1. When content is editable HTML should bring a ```<span>``` with:
    - ```dot-data-object="editableField"```
    - ```data-dot-field="fieldName"```
    - ```data-dot-inode="contentletInode"```
2. Make sure respect permissions
3. Multilanguage
4. Unit test

**Comment by dotcmsCodeReview** [comment]
I think dot-data-object=editable is too broad. It need to be
dot-data-object=editableField or something

sent from my mobile

**Comment by wezell** [comment]
done
