### ISSUE TITLE
Add field variable name to edit field dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14400]
As a user I want to have access to the variable name of a field from the edit field form.

## Expected Behavior
Should see the var name in the field form

## Current Behavior
No var name in the field form.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a content type
3. Edit a field
4. No var name in the dialog

## Acceptance Criteria

1. Add field variable to the edit field form bottom right of the name field
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we have this on the edit field window
