### ISSUE TITLE
400 Error if the required form is not sent to the Resource endpoint

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14406]
If you make a request and don't send the parameters at all, we are getting a 500 error.

## Expected Behavior
We need a way to validate the error and send the correct code in all the resources endpoints.

## Current Behavior
We are getting a NPE because we are not validating if the form was sent.

## Steps to Reproduce (for bugs)
1. Start an instance with EE license 
2. From REST call this endpoint http://localhost:8080/api/v1/workflow/schemes but without parameters 
3. Make sure you have a 400 error (bad request) instead 500 

## Your Environment
Tested on master // postgres // FF

**Comment by wezell** [comment]
low priority.  I would rather see this type of testing / fixes on our contentlet apis and new apis for edit mode.

**Comment by bryanboza** [comment]
yes, just caught after run the automated tests

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14434

**Comment by bryanboza** [comment]
Fixed, now we have the correct error codes on this resource
