### ISSUE TITLE
[Push Publish] Categories are not included anymore in push published contentlets

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#14403]
When push publishing a contentlet that contains a category field, this field is always empty on the receiving server.

## Expected Behavior
All categories that were previously added to the contentlet on the source server should appear on the receiving server.

## Current Behavior
All categories that were previously added to the contentlet on the source server disappear on the receiving server.

## Possible Solution
This bug might have been introduced by another category related bugfix: #13722

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Add some categories to a contentlet that contains a categories field
2. Push publish this contentlet to another server
3. Check the categories field on the receiving server
4. It's empty

## Context
All existing categories in contentlets get lost on our staging and production server after push publishing them from our authoring server.

## Your Environment
* dotCMS version used: 4.3.3
* Browser Name and version: any
* Operating System and version: Linux (Debian 8)
* Application Server and version: bundled Tomcat 8.0
* Java Brand and version: Java 8
* Database and version: MySQL 5.7

**Comment by splotzky** [comment]
The parent-child-relationship between category and contentlet is missing in the database table 'tree' on the receiving server.

**Comment by splotzky** [comment]
It turns out that this issue is a duplicate of #13722. I close this one.

**Comment by joseorsini** [comment]
Reopening and adding missing commit that was not fully merged to EE repo.

**Comment by joseorsini** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/618
