### ISSUE TITLE
PageResource improvements

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14415]
As part of standardize our REST we need improve the error codes and other things

## LoadJson

- [ ] Need a bad request code (404) in case of invalid URL.. Now we have a 500

## Render

- [ ] Needs generate the javadoc

- [ ] Need include a valid message in the response in case you send an invalid URL

## Layout

- [ ] We need a 404 in case you send an invalid **$pageId**. right now we have a 500 error

- [ ] We need a bad request error (400) in case you don't send parameters at all

## AddContent

- [ ] Need a 404 error in case you send an invalid **$pageId**

- [ ] We need a bad request error (400) in case you don't send parameters at all

- [ ] Need a bad request error in case of invalid parameter

## renderHTMLOnly

- [ ] We have a (Unexpected '<') error en case of success request 

- [ ] Need generate the javadoc

- [ ] Need a 404 in case of invalid uri 

- [ ] We need return a 403 in case you don't have read permissions. (we are returning a 401)

**Comment by dsilvam** [comment]
After talking with @wezell: No need to validate if sending a non existing page, container or content

**Comment by bryanboza** [comment]
Hey @wezell. 
Sorry but not sure if I'm misunderstanding...

The idea is to standardize our resources and use the same response codes in specific cases, almost in the new ones. We fix the same cases in the workflow resource.  Now, if we don't validate that cases, we will return 500 (internal server error) in a lot of requests. Also with the **AddContent** endpoint, not only return 200, we are adding this to the database, and we are not continuing rendering the page. For me is an API error.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14455

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now all the test are working
