### ISSUE TITLE
DeleteScheme endpoint in the workflow resource needs some improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14422]
After test the new endpoint in the workflow resource, we need improve some codes and handle some cases: 

- [ ] We have a 500 error in case the scheme isn't archived\

- [ ] We have a 500 error in case you try to delete the SystemWorkflow, since you can't delete this scheme we nee a 403 here.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14488

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now works as expected, also the automated tests for this resource are ready. #14518
