### ISSUE TITLE
Error upgrading dotCMS in postgres 9.6 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14429]
We are having a postgres error when you try to upgrade an instance to the last master and you are using the 9.6  version.

## Expected Behavior
Since in this page https://dotcms.com/docs/latest/dotcms-technology-requirements we support all the 9+ versions, we need be able to support this version without errors 

## Current Behavior
We are having a postgres specific error in the upgrade process 
SC: https://gist.github.com/bryanboza/70c2db29096d8740f2b591ed079d5223

FYI: For now is just noise in the log, because the process continues 

## Known Workarounds
https://stackoverflow.com/questions/38427585/postgresql-error-column-am-amcanorder-doesnt-exist?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

## Steps to Reproduce (for bugs)
1. Take a dotCMS 3.x version 
2. Upgrade this to the last master version  
3. Check the process in the catalina.out file 

## Your Environment
Tested trying to upgrade from 3.7 instance to the last master 
postgres version: psql (PostgreSQL) 9.6.8
OS: macOS High Sierra 10.13.4

**Comment by wezell** [comment]
dupe #14465
