### ISSUE TITLE
We need clear the filter in the add new content dialog after change the content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14438]
We need reset/clear the filter after you change the content type, this because we still tying to filter by the same parameters after change it. 

## Expected Behavior
We need clear all the values after change the content type 

## Current Behavior
When you are adding a new content, and you try to order by some field, and then change the conte type, the system is still trying to order by the same value and isn't finding results 
SC: https://screencast.com/t/de4Ib1Jfq

## Possible Solution
Reset values 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Try to add a new pice of content to some page 
3. With the content type field in all, try to order by some of the displayed fileds 
4. Now change the content type and try to see other content 

## Your Environment
Tested on master // postgres // FF

**Comment by bryanboza** [comment]
Related to #14334

**Comment by wezell** [comment]
dojo / javascript issue

**Comment by bryanboza** [comment]
The **" Add New"** (+) button shouldn't change position when you change the content type. 

SC: https://screencast.com/t/70mOPF6SOM

**Comment by erickgonzalez** [comment]
@bryanboza @hmoreras is working on this dialog fixing UI on this ticket https://github.com/dotCMS/core/issues/14118

**Comment by bryanboza** [comment]
Fixed
