### ISSUE TITLE
Add title to the contentlet dialog editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14433]
As a user I want more information about what I'm doing in the contentlet editor.

## Mock
![contentlet editor](https://user-images.githubusercontent.com/751424/40327481-5becf156-5d00-11e8-8829-b6374eab7fd5.png)

## Acceptance Criteria

1. NG:
    - [ ] Add the dialog with the title
        - Content Search when user is in "add" mode
        - Content type name when user is creating or editing the name of the content type (the same you have to remove in the JSP sidebar)
    - [ ] Add the close button on the right
2. JSP:
    - [ ] Remove the close button in the sidebar
    - [ ] Remove the content type title in the sidebar
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
- [ ] Need to add the close button when you are adding a new content type, right now we are displaying this button when you edit but not when you add. 
SC: https://screencast.com/t/5yaAjaA6U

- [ ] Need be consistent with the styling of both windows 
1. https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/4a212e3c-ec8a-44fd-9319-ac9fa83b7974/00000059.png
2. https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/aca92b7d-06ee-47ed-a52e-394097c2a926/00000060.png
