### ISSUE TITLE
Unable to add templates from site browser 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14436]
As user I need be able to add templates from the site browser portlet. Right now we have a jsp error. 

## Expected Behavior
We need be able to add templates from site browser without problems 

## Current Behavior
We have a jsp error and this is breaking the backend UI 
SC: https://screencast.com/t/pbVCcCrNa
Error: https://gist.github.com/bryanboza/c801b030b8247748e2d2aba6d7f61246

## Steps to Reproduce (for bugs)
1. Clear the browser cache
2. Login as admin 
3. Go to site browser portlet 
4. From the angular options menu try to add a new template 

## Your Environment
Tested on master // postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14498

**Comment by bryanboza** [comment]
Fixed, now we don't have that options in the drop-down
