### ISSUE TITLE
Merge my NavResource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14449]
We need to review and vet the NavResource pull request here #14220 

We need Postman tests for this new resource

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14507

**Comment by bryanboza** [comment]
Postman test created: 
**Here the doc: https://goo.gl/xfSfRA**

- [ ] Need returns a 404 error in case of invalid URL. Right now returns a 200 with an empty JSON. 

- [ ] Need a 400 error (bad request) in case you send an invalid "depth" parameter... We are returning 404, and this is just a bad the parameter 

- [ ] This rest is not validating permissions, e.g. If you have a folder with some pages into it. But just the admin has permissions to see this folder. If you call this REST as a limited user, we are returning the complete tree of the folder.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14547

**Comment by bryanboza** [comment]
We don't have a way to filter here by language, and we need be able to do it...

**Comment by wezell** [comment]
What is the correct behavior here?  Do we respect the langauge fall back?  Also, folders are not multi-lingual so they will behave differently than pages or files.  Before we "fix" this for the specific use case, I'd like to know why the customer cannot work around the particular issue themselves in the implementation.

**Comment by john-thomas-dotcms** [comment]
It seems like the most appropriate way to handle it with our existing config is to use the language fallback for content, but like Will said, folders kind of break that model already.  I'm not sure if it would make sense to have a separate language fallback just for navigation, but it might be worth thinking about.

Is there a way to use language variables to accomplish the same thing, particularly with respect to folders?

**Comment by jgambarios** [comment]
**Note:** @erickgonzalez as we discussed we need to:

1. Allow the end point to accept an optional language id parameter
2. If a language id parameter is sent we need to use it but if the parameter IS NOT sent we need to calculate the language to use calling `WebAPILocator.getLanguageWebAPI().getLanguage(req)`

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14618

**Comment by bryanboza** [comment]
We need do some improvements here: 

- [ ] When you send a request with an invalid parameter, the server returns 400(bad request) but we need be more specific in the response body. Right now we return this: 
```"message": "For input string: \"asd\"" '```
In this case I'm sending  ```depth=asd```, the same thing with the **languageId**

- [ ] Now the **languageId** si an optional parameter, but if we have this parameter we need to use and validate. Then if you send an languageId and this does not exist, we need validate this case, and return a 400 (bad request)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14679

**Comment by wezell** [comment]
For whatever reason, all these changes have broken the velocity nav tool in starter.  You can see that no navigation is being printed out

**Comment by wezell** [comment]
![screen shot 2018-06-22 at 9 20 46 am](https://user-images.githubusercontent.com/934364/41778774-bfe7fd48-75fd-11e8-8575-1761ca9b3667.png)

**Comment by erickgonzalez** [comment]
Actually I think this could be the one that broke it, let me take a look https://github.com/dotCMS/core/issues/14655

**Comment by bryanboza** [comment]
Need to return a 400 error when you send an invalid language id and not a 404, this because the param is part of the request and this is a bad request. 
SC: https://screencast.com/t/BaJbaW5xT
