### ISSUE TITLE
Update edit page layout toolbar

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14442]
As a stakeholder I want to make sure toolbars are consistent across the app

## Mock
![Toolbar.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/ffa5df0f-7541-4bde-8255-45e8c2270ff1)

<img width="1230" alt="edit page - layout" src="https://user-images.githubusercontent.com/751424/40364825-73e2135a-5d90-11e8-9851-4fe9d73443c7.png">

## Acceptance Criteria

1. Match the design
2. Cancel button redirect to "Edit content"
3. Theme selector, there is another issue for that
4. Everything else works the same
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
