### ISSUE TITLE
Allow users to select two other colors on company portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14454]
In the company portlet, we need to save two more colors (Primary color, Secondary color) in the company for use by the UI.  We will also need to return these values rest call 

http://localhost:8080/api/v1/appconfiguration

![screen shot 2018-05-22 at 3 40 37 pm](https://user-images.githubusercontent.com/934364/40386663-571e2806-5dd8-11e8-8681-c3f0f1f70baf.png)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14520

**Comment by erickgonzalez** [comment]
We need a startup task to modify the current values (business and 3059 grand ave.)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14539

**Comment by DeanGonzalez** [comment]
documented: https://auth.dotcms.com/docs/latest/branding-basic-information
