### ISSUE TITLE
Fix the shipping context.xml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14451]
In adding back the datasourceFactory param, this changed our connection pooling to use different config values: 

We need to change our shipping defaults in the `context.xml` back to the params found on this page:

https://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html

This moves us back to using `maxActive` rather than `maxTotal`

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14494
