### ISSUE TITLE
Integrity Checker error trying to fix content types conflicts with relationships

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14457]
As a user, I need be able to fix the integrity checker conflicts without problems in any of the sides and any supported databases. 

## Expected Behavior
We need be able to fix conflicts in any of the sides without problems. 

## Current Behavior
If you have content types conflicts and these ones have  relationships, we are unable to fix conflicts because you will get this error: 
ST: https://gist.github.com/bryanboza/4beb65718acc4ad028d4787845168a59

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Set up your push environment 
3. Create two new content types (CT1 and CT2) this manually on both sides  
4. Create a new relationship (CT1-CT2) this on both sides two
5. Run the integrity checker 
6. Try to fix conflicts on remote 

## Your Environment
**Sender:** 
Master // Postgres // FF 
**Receiver:** 
Master // MSSQL // FF
Master // H2 // FF

**Comment by wezell** [comment]
we assume the two relationships have the same inode.
