### ISSUE TITLE
Make a copy of dotCMS.com and upgrade it to 5.0

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14453]
Let's get a db/assets dump of dotCMS.com and upgrade it to 5.0 and test the index size/performance

**Comment by dsilvam** [comment]
Compare Reindex performance between 4.x or version being upgrading and 5.0

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14656

**Comment by erickgonzalez** [comment]
Upgrade to 5.0 using dotcms.com DB went fine without issues. Need to talk about how to test the performance of the reindex between 4.0 and 5.0.

**Comment by wezell** [comment]
1. Spin up an AWS instance
2. make copy of DB / assets for dotCMS
3. upgrade to 5.x

**Comment by erickgonzalez** [comment]
An AWS instance has been created with the DB and assets of dotcms.com, has been upgraded to 5.0 with June 29th nightly build.
