### ISSUE TITLE
More theme endpoint work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14456]
This is a follow on to the theme work already done here: #13323

- [x] Endpoint needs to take a searchParam query param that it adds to the lucene search `+catchall:searchParam*` to allow a search by name or other properties
- [x] Endpoint needs to return the inode, name, title  of the selected folder (not the contentlet)
- [x] Endpoint needs to return the identifier of the file $theme/theme.png if that exists, else null
- [x] Endpoint needs to paginate - see/modify current ThemeResource

**Comment by fmontes** [comment]
We also need an endpoint where we sent the identifier and get one theme.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14554/files

**Comment by erickgonzalez** [comment]
- [ ] When passing an id that does not exist should return 404 not found, right now is returning a 200 with an empty json.

- [ ] When passing a hostId that does not exist should return a 400, right now is returning a 200 with an empty JSON.

**Comment by nollymar** [comment]
New validations were implemented here: https://github.com/dotCMS/core/pull/14665

**Comment by wezell** [comment]
It does not look like the 3rd bullet was done?
Endpoint needs to return the identifier of the file $theme/theme.png if that exists, else null

**Comment by wezell** [comment]
Oh, I see it. nm

**Comment by bryanboza** [comment]
Ok, after test the endpoint we have the follow errors: 

- [ ] The **${hostId}** parameter should be optional, if you don't send that we need take the default site. 
_Right now this work if you made the request via browser, because the site is in session, but if you try directly from postman or via curl this returns a 400 (bad request)_

- [ ] The response of this endpoint is a page (html content) and by standard we need return all the errors in JSON format. 
SC: https://screencast.com/t/WJtJ0mrpsx

- [ ] We need validate if the **$hostId** is valid or not and indicate in the response if the host does not exist.

**Comment by wezell** [comment]
This is actually wrong:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/util/pagination/ThemePaginator.java#L102

We don't want to set the folder's identifier to the `$theme/theme.png` identifier.  We just need to include it in the results. Additionally, we are mutating the folder ID which is causing the issue here: #14691

**Comment by nollymar** [comment]
@bryanboza @wezell your suggestions have been implemented here: https://github.com/dotCMS/core/pull/14705

**Comment by bryanboza** [comment]
After test again, we are not validating the asset status here, If you have the image unpublished or archived, we always are returning the thumbnail in the endpoint.

**Comment by nollymar** [comment]
According to the priorities, some enhancements suggested by @bryanboza were applied on this PR: https://github.com/dotCMS/core/pull/14790

**Comment by bryanboza** [comment]
We still having problems here, after the last changes now the {hostId} is a required parameter. If you don't send it, we need to return a 400 error. Right now we have a 404 as when we send an invalid parameter. 
<img width="1640" alt="themesresource" src="https://user-images.githubusercontent.com/2641437/42772534-f978d8a0-88e7-11e8-81de-fb8238e8ecba.png">

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/14852

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected. Good job here @nollymar 
<img width="1280" alt="theme" src="https://user-images.githubusercontent.com/2641437/43095209-4bb5418c-8e72-11e8-8ba3-251f76cb17c0.png">
