### ISSUE TITLE
render endpoint in live is returning working contentlets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14462]
As a user I want to get live page with JUST live contentlets.

## Expected Behavior
Endpoint should returned only published contentlets of the page when ask for live

## Current Behavior
Endpoint is returning working versions of contentles inside a page

## Possible Solution
Endpoint: ```/api/v1/page/render/about-us/index```

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Edit a contentlet contained in a page and just save it
3. See the page that contain that contentlet in live
4. Contentlet is updated even when it wasn't published.

## Acceptance Criteria

1. Live version of a page should only show the page with the published contentlets
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We have a 500 error if you try to render a page that has been edited from the layout tab on edit mode 
SC: https://gist.github.com/bryanboza/9236fc256fd21101d3b0abdeeed3e44e

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/15060

**Comment by bryanboza** [comment]
After the changes, I'm able to reproduce the second case of the last comment...

- [ ] We have a 500 error if you don't specify the mode in the parameter ?live=true, also in the log we have a permissions error. https://gist.github.com/bryanboza/0744962bf1b76a5832cb03da632e945a
If this is needed we need a 400 here (bad request), but don't know if we should use a fallback here and if you don't specify return the working version

**Comment by dsilvam** [comment]
new PR: https://github.com/dotCMS/core/pull/15130

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
