### ISSUE TITLE
Multiple Files upload not working

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14466]
When trying to use the Multiple Files functionality in the Site Browser we are getting an error:

https://gist.github.com/jgambarios/073a412bd1761892be85bbd4efa0c188

![Error](https://content.screencast.com/users/jgambarios/folders/Snagit/media/1cd27ae0-5524-4043-96b8-73299ebecf18/2018-05-23_13-54-48.png)

## Expected Behavior
The System should allow to upload multiple File Assets

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14503

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
