### ISSUE TITLE
Add Workflow Step column to the Content Search listing

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14473]
We want to include to the Content Search listing a new column for the Workflow Step where we display in what Step the Contentlet is.

![New Column](https://content.screencast.com/users/jgambarios/folders/Snagit/media/f6a52a8d-aaf3-4a64-ac31-7e9fadd41eb2/2018-05-24_10-06-11.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14749

**Comment by bryanboza** [comment]
Fixed, now we have this column
