### ISSUE TITLE
Render endpoint crash when ask for live version after save layout

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14475]
As a user I want to be able to view a live version of a page when layout is saved.

## Expected Behavior
User should be able to see the live version of the page with the recently updated layout.

## Current Behavior
When user save a layout and try to go to live, endpoint returns 500.

## Acceptance Criteria

1. User should be able to see the live version of the page with the recently updated layout.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14477

**Comment by fmontes** [comment]
When you remove the sidebar with a content already existing in the page, the content from the container in the sidebar render in the container left in the page.

**Comment by bryanboza** [comment]
Fixed, now we are returning a 404 if don't have a live version
