### ISSUE TITLE
Clicking any other Main menu option should close Time Machine Snapshot

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14489]
Right now if you examine a past time machine snapshot using the Time Machine and then click any item in the main left nav, then it is impossible to edit content on pages, because the snapshot does not close automatically.  Clicking on any main menu item should close any open snapshot mode before loading the new page.

Screencast: https://screencast.com/t/zfijir24

The way it is now, someone opens a time machine snapshot, then they click on a main menu item, and the bug is that there is no way to edit content on any page, until you either clear browser session, or open snapshot again and close snapshot.

**Comment by DeanGonzalez** [comment]
If we are going for "one page app" then clicking main menu item should not leave user stuck in a place where they can't edit content on any page.  It's too much to ask from an understanding perspective on how to resolve it as well.

**Comment by wezell** [comment]
I believe this was fixed by @erickgonzalez in #14803
