### ISSUE TITLE
When user close the contentlet editor dialog in Content > Search refresh the search not the page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14485]
As a stakeholder I want user to have the best experience when editing contentlets

## Expected Behavior
When user close the contentlet editor dialog trigger the search in the form.

## Current Behavior
When user close the contentlet editor dialog the iframe reloads

## Possible Solution
[Here](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/main-legacy/main-legacy.component.ts#L64) we're doing the reload, we have do something like:

```iframe.contentWindow.reloadSearch()``` or whatever the name of the function in the jsp.

## Acceptance Criteria

1. When user close the dialog editor in the content search just redo the search
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, nice improvement
