### ISSUE TITLE
Trying to Edit the System Host from the Content Search portlet fails

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14481]
In the *Content Search* portlet we can filter by the **Host** Content Type, when you filter by **Host** and if you try to edit the **System Host** an error is displayed in the Screen. 

![System Host](https://content.screencast.com/users/jgambarios/folders/Snagit/media/739fb194-3884-412c-8a3e-ce6726bb4144/2018-05-24_15-02-39.png)
![Error](https://content.screencast.com/users/jgambarios/folders/Snagit/media/efb58ae8-e414-4250-8f6f-1d9c89ffd889/2018-05-24_15-03-08.png)

## Possible Solution
I see two possible solutions:
1. Exclude **Host** Content Type from the Content Search portlet and only allow to edit a Host from the **Sites** portlet.
2. Exclude the **System Host** from the listing

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14690

**Comment by bryanboza** [comment]
Fixed, now we can't see the sites content types from the content search portlet, also is excluding from the list of the site portlet
