### ISSUE TITLE
Allow Admin to flush elasticsearch's cache 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14486]
We had an incident last night where a server entered into Full GC from which it could not recover.  When taking a heap dump, it became apparent that Elasticsearch's cache was using all the instance memory.  We need a way to allow an admin to flush Elasticsearch's field and filter cache in order to reclaim the memory from older indexes.

Perhaps this should also occur after a full reindex.

**Comment by wezell** [comment]
![screen shot 2018-05-25 at 10 53 54 am](https://user-images.githubusercontent.com/934364/40551073-f2c264ce-6009-11e8-9140-6571e9a21a23.png)

**Comment by john-thomas-dotcms** [comment]
This has potential privacy implications in the use case where a site operator receives a request to remove user information; ability to flush the ES cache may be necessary to ensure user data is fully removed from the system.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14497

**Comment by bryanboza** [comment]
Fixed, now we have this button and we are flushing the caches without problems
