### ISSUE TITLE
Chrome redesign and user picking colors

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14495]
As a user I want to be able to custom the colors of the admin in `Site > Configuration`

## Acceptance Criteria

1. Make sure everything works with the chrome redesign
2. User should be able to pick colors from `Site > Configuration`
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14649

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14660

**Comment by bryanboza** [comment]
Fixed, now this is working as expected
