### ISSUE TITLE
Old template designer not rendering containers correctly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14493]
Looks like is a css problem.

![mira](https://user-images.githubusercontent.com/751424/40733571-31aa81f2-63f3-11e8-8a7e-d961b4e12bb9.gif)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* dotCMS version used:
* Browser Name and version:
* Operating System and version:
* Application Server and version:
* Java Brand and version:
* Database and version:
* Application module (if apply):

**Comment by freddyucv** [comment]
Branch to see the bug:

https://github.com/dotCMS/core/tree/issue-14493-Old-template-designer-not-rendering-containers-correctly

**Comment by hmoreras** [comment]
![image](https://user-images.githubusercontent.com/31667212/40811740-af01e5d0-64ef-11e8-85c0-7b0da01d3e53.png)

html looks the same, except the name of the containers, id looks correct

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14650

**Comment by bryanboza** [comment]
Fixed, tested on master and I'm unable to reproduce
