### ISSUE TITLE
Container selector not showing the first page of results

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14504]
As a user I want to be able to select containers.

![image](https://user-images.githubusercontent.com/751424/40733832-e55265bc-63f3-11e8-95e9-30275b0967f7.png)

## Expected Behavior
Users should be able to select containers

## Current Behavior
Container selector is not showing results in the listing.

## Possible Solution
N/A

## Known Workarounds
Search for the container

## Steps to Reproduce (for bugs)

1. Login
2. Edit a layout
3. Try to add a container

## Acceptance Criteria

1. Container selector should show the listing of the first page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
Seems like a BE issue, when doing a curl on http://localhost:8080/api/v1/containers, this returns empty containers

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14551

**Comment by bryanboza** [comment]
Fixed, now we are showing the list
