### ISSUE TITLE
Starter: News detail shows duplicated info

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14501]
The detail of a News Content Type shows duplicated data in the starter.

![Duplicated](https://content.screencast.com/users/jgambarios/folders/Snagit/media/c2de5164-9b4d-407a-aac2-282f381efe22/2018-05-25_14-47-21.png)

After a quick research I saw the duplicated data comes from the `news-detail-ng-comments.vtl` file.

**Comment by jgambarios** [comment]
Fixed on the starter

**Comment by bryanboza** [comment]
Fixed, tested with the last starter
