### ISSUE TITLE
Implements crumbtrails in the new chrome

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14513]
As a stakeholder I want user to have a sense of which portlet are they in

## Mocks
<img width="621" alt="screen shot 2018-10-06 at 7 29 16 am" src="https://user-images.githubusercontent.com/751424/46571850-9a122780-c939-11e8-8eeb-c25862b4aa34.png">

## Expected Behavior
User should get the crumbtrails in the top bar

## Current Behavior
N/A

## Possible Solution
Use the router information to get the data

## Acceptance Criteria

1. When user is in a jsp legacy portlet it should only get `First level > Porlet name`
2. When user is in an angular portlet we should show the whole path `First level > Porlet Name > Title`, for example: 
    - In content types listing: `Types & Tags > Content Types`
    - In content types item: `Types & Tags > Content Types > News Item`
4. First section link should open the first portlet of that section
5. Second section link should open THAT portlet
6. Last section of the crumbtrail should NOT be a link
7. Match the design
8. Work in all the supported browsers (don't forget IE11 and iPad)
9. Multilanguage
10. Unit test

**Comment by alfredo-dotcms** [comment]
Notes:
![image](https://user-images.githubusercontent.com/37185433/47239892-ce5afe80-d3a3-11e8-80eb-5f77bde12583.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/47239948-fc404300-d3a3-11e8-9495-048978dbb7ee.png)

**Comment by bryanboza** [comment]
Fixed, for now, this is ok with double breadcrumbs. Tested on the last master

**Comment by bryanboza** [comment]
Ok, according to the @fishsmith comments:
- We need to remove the workflow crumb trail. It doesn't carry over to the workflow action or sub-action. So it's only on the first screen. I think I would remove it for the JSP

- On the categories just remove the first link called Categories the "Categories" and "Top Level" goto the same level so in the top, you would have "Types & Tags | Categories" then keep the local crumb trail but start with "Top Level > A-Z Index > ...."

**Comment by fmontes** [comment]
![47239948-fc404300-d3a3-11e8-9495-048978dbb7ee](https://user-images.githubusercontent.com/751424/48647889-fe052280-e9b2-11e8-9bd9-3b0295f8b44a.png)
![47239892-ce5afe80-d3a3-11e8-80eb-5f77bde12583](https://user-images.githubusercontent.com/751424/48647890-fe052280-e9b2-11e8-9b0d-fc9026fe74c6.png)

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/15597/files
