### ISSUE TITLE
Unable to copy workflow schemes 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14511]
We have an error and we are unable to copy the WF schemes. The endpoint returns a 415 error. 

## Expected Behavior
We need be able to copy workflows without problems 

## Current Behavior
We show an "unable to copy" message and the workflow isn't copied 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to the workflow portlet 
3. select any of the workflows 
4. Try to copy
 
_**FYI:  For now we have no errors in the logs, also this is working from REST but no via UI**_

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
Needs integration test as well

**Comment by jgambarios** [comment]
We already have a `CopyActionletTest` the problem was in the javascript ajax call.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
