### ISSUE TITLE
Create a new contentlet should update the tabs once is saved

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14514]
![save_news.gif](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d9e43dd5-9a7a-4316-952a-11464762b199)

**Comment by fmontes** [comment]
@wezell told me he'll work on this.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14611

**Comment by bryanboza** [comment]
Now we are updating the tabs, but we need to update the step information too. 
SC: https://screencast.com/t/icsPPv4fTK

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14682

**Comment by bryanboza** [comment]
We have problems with this card after you delete any content, we need close this window after you try to delete some piece of content. Right now we delete the piece of content but the window continues opened, and the content does not exist. This is causing the error. 

SC: https://gist.github.com/bryanboza/349d3bf0e3eaa3aa0094d1c07fda590b

**Comment by fmontes** [comment]
I created an issue to handle the delete error: https://github.com/dotCMS/core/issues/14809

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected
