### ISSUE TITLE
Catch/no-crash JS errors in the edit page iframe

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14526]
As a stakeholder I want to make sure that "customers" JS errors don't break edit mode.

## Expected Behavior
Is there is an error in the customer page edit mode didn't crash.

## Current Behavior
Edit mode is crashing on iframe/page throws an error.

## Possible Solution
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

## Acceptance Criteria

1. Log the error but don't crash the app
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
### My finds so far
1. Branch: issue-14526-catch-errors
2. We don't need to catch errors in JS from the iframe, is no different
3. The only JS error that crash the app is related with dojo in pages that have form
4. Pages with forms are broken in public too
5. Is not the dojo version, I downgrade to 1.8.3 (the one that have demo.dotcms.com) and same error

**Comment by alfredo-dotcms** [comment]
partial fix: `bootstrap.min.js` and `popper.min.js` should load before dojo, so an option could be to move it from `/application/themes/quest/footer.vtl` to /application/themes/quest/header.vtl

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14942
