### ISSUE TITLE
Update Encryption Key algorithm

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14523]
dotCMS encryptor / unencryptor uses an old and broken algos to encrypt userIds in the jwt token.  We need to use a more modern algorithm to regenerate the default encryption key

**Comment by wezell** [comment]
To test, null the key from the company, e.g.:

`update company set key_=null;`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14533

**Comment by bryanboza** [comment]
Fixed, now we are regenerating the key every time the server starts
