### ISSUE TITLE
Create deeplinking for contentlets and tasks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14522]
As a user I want to be able to get a contentlet and a workflow by url

## Expected Behavior
When user hits ```c/content/inode``` or ```c/task/id``` we should open the dialog with the respective iframe.

## Current Behavior
N/A

## Possible Solution
1. Update the `app-routing.module.ts`
2. The contentlet is easy with the contentlet editor
3. The other one we have to create a component like the dialog editor

## Acceptance Criteria

1. When user hits ```c/content/inode```, ```c/calendar/inode``` ```c/workflow/id``` we should open the dialog with the respective iframe and in the background the current portlet (content, calendar, workflow, etc...)
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
1. Open URL's in a new tab (without the app loaded) doesn't show the dialog, only redirect to the first portlet
2. `task` always shows me: `Unfortunately this has caused a problem. Please try again` in the jsp, it might be the url needs something else.

**Comment by fmontes** [comment]
1. Dialog is not loading correctly the header

**Comment by fmontes** [comment]
As per @wezell request:

We need to change the urls

```/c/workflow/:id```

and 

```/c/content/:inode```

**Comment by alfredo-dotcms** [comment]
This works, but the calendar url is: `/c/calendar/INODE`
