### ISSUE TITLE
Make sure edit page toolbar and control css are not overwrite

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14527]
As a user I want to make sure all my edit content control are visible

## Acceptance Criteria

1. Make sure edit page toolbar and control don't get lost in the z-index of the page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
Also, don't let the page CSS to override the control css

![screen shot 2018-06-15 at 10 01 23 am](https://user-images.githubusercontent.com/934364/41472022-37290a6c-7083-11e8-829e-0acabb3f98ab.png)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes
