### ISSUE TITLE
Show what's changed on EE only.

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14525]
As a stakeholder I want to show what's change only for EE instances.

## Expected Behavior
Show what's changed on EE only.

## Current Behavior
Showing WC all the time.

## Possible Solution
Use the license service.

## Known Workarounds
N/A

## Acceptance Criteria

1. Show what's changed on EE only
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed tested on the last master and now this works just with license
