### ISSUE TITLE
Filter device and persona selector

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14524]
As a stakeholder I want to make sure options in personas and device selector are the right ones.

## Expected Behavior
If user add personas or devices without all the fields we need, filter out those options

## Current Behavior
If user add personas or devices without all the fields we need it breaks.

## Possible Solution
Simple `.filter` in the rxjs stream where we get the data,

## Steps to Reproduce (for bugs)

1. Create a device without size
2. Try to use the device in the edit page
3. Broken...

## Acceptance Criteria

1. Personas and device selector should only show usable options
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
This issue only applies for `devices` since `persona` don't have an attribute where we can check in the FE to be filtered

**Comment by bryanboza** [comment]
I think this isn't the correct fix, we need set this fields as required in our starter because right now if you add a new device and don't appear in the list seems like a bug.

**Comment by fmontes** [comment]
I make the fields required in the starter

**Comment by bryanboza** [comment]
We need wait for a new starter

**Comment by bryanboza** [comment]
After the last changes now we don't have this specific problem, but we need to exclude the unpublished and archived devices from the list. Right now we just add the device to the list but ignore the status.

**Comment by bryanboza** [comment]
Also, we are unable to change back to the default view
https://files.slack.com/files-pri/T028R2630-FBRDC4DDY/changing-view-as.gif

**Comment by bryanboza** [comment]
Fixed, tested with the last code and now I'm unable to recreate those errors
