### ISSUE TITLE
Unable to republish menu links after create a new one and un-publish  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14532]
We are unable to publish menu links after you create a new one, unpublish and then try to republish again. The same case if you just save a new one and then try to publish 

## Expected Behavior
Since I'm logged as admin I should be able to publish this menu links without problems 

## Current Behavior
We have a permissions error and the menu link isn't published 

Also, we are unable to add menu links to pages in different languages
ST: https://gist.github.com/bryanboza/3258cf97f07dba9bdd7df07718184d33

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to site browser
3. Create a new menu link and just save it  
4. Try to publish 
5. Make sure the menu link was published 

Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15134

**Comment by nollymar** [comment]
Test results: Success. It's working as expected
