### ISSUE TITLE
Workflow filter need respect the content type permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14534]
The new filter in the workflow portlet isn't respecting the content type permissions, and the idea of this filter is to know which actions I can execute as a specific user in a specific content type, but then we are showing multiple actions and maybe we the user don't have permissions to see this content type. 

## Expected Behavior
This filter should validate if the selected user has permissions to read or publish before display the action in the list. 

## Current Behavior
We display multiple actions to execute as a limited user in some content types that the user can't see 
SC: 
<img width="1459" alt="img1" src="https://user-images.githubusercontent.com/2641437/40807770-77a30324-64e2-11e8-8d1e-d8fbd3a03678.png">

## Possible Solution
Validate the content type permissions before display in the list 

## Known Workarounds
1. Login as admin 
2. Go to the WF portlet 
3. Select the system WF
4. Now using the filter select a limited user and the **_"Event"_** content type

Using the login-as, make sure you can execute this actions in this content type as the selected user. 

## Your Environment
Tested on the last master // Postgres // FF

**Comment by jdotcms** [comment]
After an analysis over the code we have figured out that the current behavior is right, the permission are applying by using respect front end roles in true, which means that the filter is running on FE mode rather than BE.

The solution proposed is going more in terms of the UI, I would suggest to add a checkbox (third filter) with:

[ ] respect front end roles

**Comment by wezell** [comment]
I would force it to backend mode by default and not add another control.  I
think front end mode permissions on workflows and their content is not
correct.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14772

**Comment by bryanboza** [comment]
Fixed, now we filter according to backend mode
