### ISSUE TITLE
We are able to execute actions from archived workflows

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14538]
We are showing and allowing execute actions from archived schemes 

## Expected Behavior
We need to remove the available workflow action from contents if the scheme is archived. 

## Current Behavior
We are allowing continue executing WF actions on contentlets when the scheme is archived 
SC: https://screencast.com/t/5leRZlin4dr

## Known Workarounds

1. Actions in archived workflows should not work (or be visible anywhere but in the workflows portlet, really).
2. Contents in an archived workflow should be reset to being in no workflow state.
3. Archived workflows should not show in the content filter.
4. We need a confirmation message before archiving the site since this is a destructive operation 

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to the WF portlet and create a new workflow
3. Create a new content type and set this WF
4. Now archive the WF
5. Finally, go to content search and try to add a new piece of content to the created content type
6. Make sure you don't have the actions of the archived scheme

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14663

**Comment by jgambarios** [comment]
We need to exclude the Archived Workflows from the Content Search portlet.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14802

**Comment by bryanboza** [comment]
After this fix, we need to remove the archived WF from the edit content too.

**Comment by bryanboza** [comment]
After the test of the last changes we have this case: 

When you have a piece of content in a workflow and this workflow is archived, the content should be locked. This because don't have available actions to execute, but when you delete the workflow from the content type, we need to delete all the relationships and reset the workflow of the content associated with it. 

And leave the pieces of content like new, you should be able to see the actions from all the associated workflows. Right now after doing this process, we are able to see just the actions from the "New" step in the system workflow.

**To reproduce:** 
1- Create 2 workflows (WF-A, WF-B)
2- Create a new content type and associate to (System Workflow, WF-A, WF-B)
3- Add a piece of content to this content types using the WF-A
4- Archive the WF-A 
5- Delete the WF-A from the list of associated WF to the content type 
6- Try to edit the piece of content, you should be able to see the actions of the system workflow and WF-B
