### ISSUE TITLE
ShortyIdCache still returning 404 after PP  

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#14546]
This is kind of difficult to describe, please see the Steps to Reproduce. 

**Support ticket**: https://dotcms.zendesk.com/agent/tickets/95797
## Possible Solution

See hotfix.

## Known Workarounds

Flush caches.

## Steps to Reproduce (for bugs)

1. Set up a PP environment.
2. Add this property to your dotmarketing config file: 
`WYSIWYG_IMAGE_URL_PATTERN=/dA/{shortyId}/{name}?language_id={languageId}&p={path}{name}&I={inode}`
3. Create a Test Content with a title and a WYSIWYG.
4. Create a new content under the WYSIWYG, upload an image from the file system. 
5. PP the content.
6. Open the content in the receiver, you will see a broken link image because the image in WYSIWYG was not sent as dependency (no error here, this is by design).
7. PP the image missing in the receiver.
8. Open the content again, you will see the same broken link image even when the image is already in the instance.

## Your Environment

* dotCMS version used: 4.2.2

**Comment by wezell** [comment]
fixed in #16310
