### ISSUE TITLE
Reorder Step endpoint in the workflow resource should return a 400 error in case of invalid parameter 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14545]
We need to return a 400 (bad request) in case you send an invalid parameter in case of the string order value 

## Expected Behavior
We need to send a 400 bad request error in that case 

## Current Behavior
We return a 404 in this case which is wrong 

## Steps to Reproduce (for bugs)
1. Start a dotcms instance with an EE license 
2. Using this endpoint send an invalid to reorder value (any value not int)
`http://localhost:8080/api/v1/workflow/reorder/step/94178d17-96a0-4e08-b9aa-94214a7fb31e/order/0` 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14756

**Comment by bryanboza** [comment]
Fixed, now this is working as expected 
<img width="1680" alt="reorder" src="https://user-images.githubusercontent.com/2641437/42527282-6d288bfe-8435-11e8-98f0-b77380f3b938.png">
