### ISSUE TITLE
Edit files in contentlet dialog editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14543]
As a stakeholder I want to make sure all the contentlets in the system are edited in the contentlet dialog editor

## Expected Behavior
Files are contentlet, should be edit in the dialog

## Current Behavior
Files are being edited in a new page

## Possible Solution
Same ad we did with pages

## Acceptance Criteria

1. From site browser and content search, edit a file should open in the dialog
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working
