### ISSUE TITLE
Unable to upload files from the wysiwyg editor 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14549]
We are unable to upload files when you are in a WYSIWYG editor, then try to insert a new image in the editor and here you try to upload a new one. We are showing an unexpected error.
 
## Expected Behavior
We should be able to upload files from this window, and then use it without problems 

## Current Behavior
When you try to upload some file from this window the system shows an unexpected error and the system crashes. 

SC: https://screencast.com/t/Sd5hrPYpW6T
ST: https://gist.github.com/bryanboza/bbe7bbeb4de1d5eff37e3b70db964b20

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new page 
3. Try to add a new piece of content type Generic
4. From when WYSIWYG editor try to insert a new image, here try to upload a new one 
5. Execute the save and publish action 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
Closed as dup: https://github.com/dotCMS/core/issues/14628
