### ISSUE TITLE
[dotCMS Upgrade] categories_tab field prevents Full Reindex

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#14553]
After upgrading a couple of clients last week, we are unable to do a full reindex. The error is the same, _**categories_tab**_ field returns a NPE because is not found by LegacyFieldTransformer. The log below doesn't describe the error so we needed to debug locally in order to find out the error.

Log: https://gist.github.com/oarrietadotcms/4c622a992e836edc78580fedcb8a8834

## Expected Behavior

1. Source code is hiding the real error, it should be logged to help client track this error.
2. idk if categories_tab should be included in our list of fields, or we should have an upgrade task to remove that field from DB. 
## Current Behavior

Reindex gets stuck.

## Known Workarounds

Deleting fields from DB:
```
delete from field where inode = '78484' and structure_inode = '78440';
delete from field where inode = '79040' and structure_inode = '79028';
delete from field where inode = '78693' and structure_inode = '78521';
```
## Steps to Reproduce (for bugs)

1. Ask @manuel-miranda for a upgraded DB dump to reproduce locally.
2. Reindex.

## Context

```
select * from structure where inode = '78440'; -- News Widget
select * from structure where inode = '79028'; -- Employee Widget
select * from structure where inode = '78521'; -- Events Widget
```
## Your Environment

* dotCMS version used: 4.3.3

**Comment by wezell** [comment]
This can be handled in our "things to know" doc on upgrading from <2.x
