### ISSUE TITLE
Error in Eclipse please help me!

### ISSUE THREAD

**Issue by galgalo1** [dotCMS/core#14564]
java.lang.ClassCastException: org.apache.catalina.connector.RequestFacade cannot be cast to javax.servlet.ServletResponse
	Com.dineshkrish.bo.RegisterSrv.doPost(RegisterSrv.java:29)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

**Comment by wezell** [comment]
Not the right place for a support request.
