### ISSUE TITLE
Allow content types to be searched by their base type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14560]
In 4.x you can filter the result of content types by their base type.  In 5.x, you can't, we've lost that dropdown.  We need to allow a user to filter the result set by the baseType name as well as the content type name, e.g.

- CONTENT
- WIDGET
- FORM
- FILEASSET
- HTMLPAGE
- PERSONA
- VANITY_URL
- KEY_VALUE

**Comment by wezell** [comment]
![base-type-filter](https://user-images.githubusercontent.com/934364/41059396-729b53d8-699a-11e8-8d07-8218cb43d844.gif)

**Comment by dsilvam** [comment]
Let's automate test this. Use @wezell's branch

**Comment by nollymar** [comment]
A new ContentTypesPaginatorTest was created
PR Core: https://github.com/dotCMS/core/pull/14561

**Comment by bryanboza** [comment]
Fixed now the filter is working

**Comment by bryanboza** [comment]
Something happens with this fix, now this isn't working. We need fix this again

**Comment by fmontes** [comment]
Close, UI done here: https://github.com/dotCMS/core/issues/13725
