### ISSUE TITLE
Dear experts,   I am getting this new error and then I googled and found out that with Java Eclipse  and web servlet annotation you won't need deployment descriptor..   What do I do to keep the container happy ?  

### ISSUE THREAD

**Issue by galgalo1** [dotCMS/core#14565]
Here's the error :

HTTP Status 500 - Error instantiating servlet class Com.candidjava.RegistrationTeacher

type Exception report

message Error instantiating servlet class Com.candidjava.RegistrationTeacher

description The server encountered an internal error that prevented it from fulfilling this request.

exception 
javax.servlet.ServletException: Error instantiating servlet class Com.candidjava.RegistrationTeacher
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	java.lang.Thread.run(Unknown Source)

**Comment by jgambarios** [comment]
Closed as this is not the right place to post this kind of questions, please use our community group https://groups.google.com/forum/#!forum/dotcms
