### ISSUE TITLE
What's changed isn't working if you are using the view as feature 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14579]
We have problems if you use the view-as feature and in any device try to use the what's changed 

## Expected Behavior
We need be able to show what's changed in any device 

## Current Behavior
The UI of the device is crashing 
SC: https://screencast.com/t/UlR5uusKa

## Steps to Reproduce (for bugs)
1. Login as admin
2. Try to edit any page 
3.  View as any device 
4. Try to see what's changed 

## Your Environment
Tested on master // postgres // FF

**Comment by wezell** [comment]
Known issue
