### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14572]
- [x] Clean up container edit styling , this makes the preloop/postloop bigger and allows them to auto expand with text
- [x] Same thing on the textarea field on the content type (widgets too)
- [x] add uuid when adding a container (#parseContainer) to an advanced template
- [x] Puts comments front and center on the workflow task list display.  We need to show comments first, before anything.

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/14656

**Comment by bryanboza** [comment]
Fixed, those are just UI enhancements
