### ISSUE TITLE
Update context.xml and catalina.properties for faster dotCMS startups

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14570]
While messing around with embedded tomcat, I found a number of switches that speed up tomcat's start up performance by preventing package scanning on startup.  On a local machine with SSDs, this translates to a substantial performance increase and I would guess that on machines with slower drives, like some cloud boxen, the difference could be greater.

Current context.xml:
`INFO: Server startup in 38040 ms`

context.xml with disabled jar scanning:
`INFO: Server startup in 23670 ms`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14571
