### ISSUE TITLE
Make sure all contentlets are create and edit from the dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14573]
## Acceptance Criteria

1. New > Image or File
2. Talk detail should open in new url
3. Edit contentlet from content search should open with new url: `/c/content/{inode}`
4. Content > Calendar event
5. Sites > edit site
6. Site browser > edit site

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14635

**Comment by bryanboza** [comment]
Fixed, now all those cases are working properly
