### ISSUE TITLE
The script into a content should run when it is added into the page

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#14582]
If you add a content with script code into it, the script code is not run when the content is add into the page

## Expected Behavior
The script should run when the content is added

## Current Behavior
The script code into the content is not running

## Steps to Reproduce (for bugs)
1. Crete a new widget with the follow code
```
<script>
  alert('AAAAAAAAAA');
</script>
```
2. Go to about-us/index page (or whatever other page)
3. Add the content into the page

![not_running](https://user-images.githubusercontent.com/10408015/41300215-6875483c-6e22-11e8-89f6-ae9c9417d61f.gif)

**Comment by bryanboza** [comment]
Fixed, tested with the attached example and now this works
