### ISSUE TITLE
ES problem when starting in Docker without a License

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14583]
When starting up in Docker without a license file, this message logs over and over:
zen.ZenDiscovery - failed to send join request to master

Basically, dotCMS is running without a master ES node which causes the ES index init to fail.

Full log is here:  https://gist.github.com/brentgriffin/a64c81cf6caa9c586f290c76a40c3787#file-docker-output-L6818

When starting up with a license file everything seems to initialize properly.

To recreate, follow steps here:  https://authoring.dotcms.com/docs/latest/docker-examples#full-container-stack-on-single-node

**Comment by dsilvam** [comment]
@chrismccracken will this one be solved by https://github.com/dotCMS/core/issues/14550?

**Comment by wezell** [comment]
Seems like it.  We will test #14550 and if that works, then this one will pass as well.
