### ISSUE TITLE
Search and return the full url for fileAssets and pages in our content resource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14580]
We need to be able to search by URL the full path of files and pages using elasticsearch in order to allow for quick searching and filtering of url based content ,  e.g. like githubs file search.

This might mean we need to index the`contentlet identifier.getPath()`  - we might even need a custom stemmer on it and we need to add the path to the `ContentletUtil.getContentPrintableMap ` that the `ContentletResource` and the `ESContentResourcePortlet` return with their restful results.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/14636

**Comment by bryanboza** [comment]
Fixed, tested from the ES_Search tab using this query:
```
{
        "query" : { "query_string" : {"query" : "+Identifier:$PageId"} }
    } 
```
Now every page and asset should have a **"path"** parameter.
