### ISSUE TITLE
Can't Drag Text Fields to Content Type Layout

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14616]
Tested on latest Master

Easy to reproduce:  Create a new Content Type, add a layout, and try to add a Text or Wysiwyg field.  If you are on a standard laptop screen, there is no way to drag the fields at the bottom to the Content Type layout.  The only way is to change the zoom in the browser.  

![nodrag](https://user-images.githubusercontent.com/1569167/41315226-1be10810-6e4c-11e8-853a-c16e2d0e54d0.png)

Bug: Users can't be expected to zoom-out in their browsers just to be able to drag-and-drop text fields to the Content Type Layout.

Screencast: https://www.screencast.com/t/qyuwniiJ4WJ

In my opinion, we need to fix this or we should not use this view as default for the 5.0 release.

**Comment by DeanGonzalez** [comment]
Hey Freddy, I just tested this and seems to be working - good fix!

**Comment by bryanboza** [comment]
Fixed, now the scroll is in the field list
