### ISSUE TITLE
Add missing options to "Push Now" workflow action

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14613]
Currently there is no way to do a push delete automatically from a workflow action, or to do other types of push automation (for example publishing and/or unpublishing at some specified time in the future).  This is because the "Push Now" workflow action just doesn't have options for these.

## Expected Behavior

* Needed: It should be possible to create a workflow action which automatically performs a Push Delete on the content.
* Ideal: It would be ideal to be able to create a workflow action which automatically pushes content (either to publish or to delete or both) at a time in the future.

## Current Behavior

If you want content to be removed from the receiving server, you must do it manually.  There is no way to do this with workflows.

## Possible Solution

Right now the "Push Now" workflow action simply doesn't provide the options for what type of push you want to do, so it's passing default values for all options which can't be selected.

So it's likely that allowing a push delete in a workflow action would just require adding a radio button to the Push Now workflow fields to allow the user to specify whether to "Push" or "Remove".

Adding the ability to push and push delete in the future would also require adding a date/time field of some kind.  This would require slightly more work than allowing selection of Push/Remove (since users would need to be able to specify how far in the future the time should be set), but a simple field specifying how many seconds in the future to perform the push would be a simple way to do this (and would be consistent with how the time period for scheduled workflow actions works).

Final note: In an ideal world, the workflow fields popup would look alot like the Push Publish popup (including the ability to select "Push", "Remove", or "Push Remove" and then showing or hiding the "Publish" and "Expire" fields to set those times).  But this could still work if it simply allowed "Push" or "Remove" and then a single time field, since the user could add two "Push Now" sub-actions to accomplish the same results (one to push and one to remove).

## Known Workarounds

Remember to push delete content manually.

## Context

We get bitten by this regularly in our own Documentation workflow.  This happens since, without the ability to do a "Push Now" that specifies a Push Delete instead of a normal push, there's no way to create an "Unpublish" action that will ensure the documentation is removed from the production server.  This means that we semi-regularly have documents which someone unpublishes on auth, but forgets to take off prod by doing a push delete (since the push delete must be done manually).  So it's a semi-regular occurrence that a user finds an old doc on prod that needs to be manually cleaned up.

And we're not alone - customers have basically asked for this before: https://github.com/dotCMS/core/issues/8127

## Your Environment

* dotCMS version used: 4.3 (demo/auth)

**Comment by mattyarbrough** [comment]
Customers are experiencing problems in the field with this.

**Comment by john-thomas-dotcms** [comment]
Update: This is even a little more of a problem than I thought, since the "Push Publish" sub-action also does not allow you to do a push delete.  The popup that the "Push Publish" sub-action brings up will only do a push, and does not have any options to do a Push Remove.

So as of right now, there's no way at all to do a push remove with Workflows - you can only do a push remove using the "default" push publish actions on the Content Search screen.

**Comment by jgambarios** [comment]
@mattyarbrough @john-thomas-dotcms We integrated the Push Publish modals in https://github.com/dotCMS/core/issues/15074 the Workflow Push Publish Action modal now have (as it is the same now) the same options the "old" Push Publish modal used to have.

**Comment by john-thomas-dotcms** [comment]
Can we please consider adding these options to the "Push Now" actionlet?

This has been a hole for a while, but the most glaring case is that, when content is archived on the sender, the user has to remember to perform a separate push delete of that content for it to be removed from the receiver.  Since this requires a manual process, it often doesn't happen (even on our own doc site, I see this often).  All that would be needed to automate and simplify this for users would be the ability to add a "Push Now" actionlet which specifically does a push delete of the content before archiving it.

Note: @jgambarios 's comment above does not actually apply here - he's talking about the "Push Publish" actionlet, but this issue is about the "Push Now" actionlet.
