### ISSUE TITLE
Capture the first 1000 failure error messages for build action

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14615]
We need to capture a list of the first 1000 error messages when executing bulk actions.  This will be a List<String> of strings, e.g.
```
Field with string regex [phone] does not match Contentlet [69aaa4e9-a45a-453b-a29d-c518d64fef66] has an invalid field.
Contentlet [69aaa4e9-a45a-453b-a29d-c518d64fef66] has an invalid field.
```
We need to return this to the bulk action results so the user can see what is happening under the covers.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14696

**Comment by bryanboza** [comment]
Fixed
