### ISSUE TITLE
Reorder Menu button fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14612]
Starter site -> Edit Mode -> About Us Page

Click on the "reorder menu"

![screen shot 2018-06-12 at 3 12 31 pm](https://user-images.githubusercontent.com/934364/41311807-69d4084a-6e53-11e8-8952-c26d37503fce.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14707

**Comment by bryanboza** [comment]
Now when you trying to reorder this menu, the system is refreshing completely the page and redirect to the first portlet, we need some work here...

**Comment by wezell** [comment]
Note that in form code and in the starter, you need to remove the 

`target="_parent"` from the form here:
 
https://dotcms.com/docs/latest/navtool#ExampleAddReorderButton

it is in :
`//demo.dotcms.com/application/vtl/containers/second-level-nav.vtl`

and 

`//demo.dotcms.com/application/themes/quest/header.vtl`

**Comment by nollymar** [comment]
Doc updates: `target="_parent"` should be removed from the code example here: https://dotcms.com/docs/latest/navtool#ExampleAddReorderButton

**Comment by bryanboza** [comment]
Fixed, tested on master and now it's working

**Comment by DeanGonzalez** [comment]
Removed target code from documentation: https://auth.dotcms.com/docs/latest/navtool#ExampleAddReorderButton
