### ISSUE TITLE
Empty Keys on Categories cause PP to fail 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#14619]
The solution here is an upgrade task that updates the key column as follows 

UPDATE category SET category_key = SOMEUUID WHERE category_key is NULL OR category_key = '';

We want to use a UUID to ensure no dup keys and no logic trying to deal. People can update IF they do not like it.  They are editable 

The problem came about here https://github.com/dotCMS/enterprise-2.x/commit/eeb49482eef6e63b3b9abae548f5376ad34894a0#diff-e93c8eed88d5c9fe87012487ea7aeb01

The commit above is good as it fixes 2 categories Pushing with the same name which we DO allow. 

In addition in 4.x you can NOT save a category through import OR directly without a key.  It will auto add a key

**Comment by jcastro-dotcms** [comment]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/95960

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14641
