### ISSUE TITLE
Allow more granularity on where a workflow action is shown

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14639]
There are a number of places where the some of the workflow options for content that are shown do no make sense.  For example, from the content listing page, you can right click and perform a "Save".  What does that do?  Similarly, we have actions that are shown in the bulk action screen that should not be available there.

We have the inverse problem as well, on the edit content screen, when you lock a content for editing, make changes to it and hit an action that does not include a “save” sub-action - we don’t save your content change, we just perform the action, even though it looks like your changes are saved they are not.

In reviewing this and comparing this to how we performed pre-5.0, we really just hacked around this with the "Requires Lock" field and used that not only as a "save" indicator, but a "show on listing/editing" screen as well.  I think adding the option to show or hide actions on the Editing / Listing screens fixes this and really allows us have a system workflow that mirrors almost exactly how we did it pre-5.0.

![screen shot 2018-06-14 at 4 46 04 pm](https://user-images.githubusercontent.com/934364/41439363-7aae37fc-6ff8-11e8-872b-815be674ccdd.png)

**Comment by wezell** [comment]
This will necessitate a new system workflow definition and starter.

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/14694 and https://github.com/dotCMS/core/issues/14692

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14681

**Comment by bryanboza** [comment]
Fixed, now we have implemented this functionality... Some new improvements reported
