### ISSUE TITLE
Unable to edit pages in languages different the default one 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14643]
We have an error when you try to create/edit some page that is in a different language that the default 

## Expected Behavior
We need be able to edit pages in any language without problems 

## Current Behavior
When you create any page we are redirecting to the edit mode of the page and here we have an error and we are unable to edit 
<img width="435" alt="img1" src="https://user-images.githubusercontent.com/2641437/41443665-8acb596e-6ffb-11e8-8368-00d3c9880597.png">
ST: https://gist.github.com/bryanboza/775442ecd41d3c07173fb5d25d2e26b5

## Steps to Reproduce (for bugs)
1. Login as admin 
2. From site browser add a new page in Spanish 
3. Try to edit

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14737

**Comment by hmoreras** [comment]
When adding content in Spanish the request gives an error https://screencast.com/t/ZuxSQdofp1 , and gives an error when trying to save. Beside that when adding english content gives an error: https://screencast.com/t/Qacibh2aXVYW

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14769

**Comment by hmoreras** [comment]
not working when creating a new page, and then new content, content do not get saved.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14792

**Comment by fmontes** [comment]
`Right click > Open (preview)` crash.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14813

**Comment by bryanboza** [comment]
The add page works just the first time, after you added a new page and you try to add another one, we have a JS error and you can't do it. 
SC: https://screencast.com/t/LyNNsMODbB

To reproduce: 
1. Go to Site browser 
2. Create a new folder 
3. Add a new page 
4. Try to add another page 

**FYI: you need refresh all the browser to this works again**

**Comment by bryanboza** [comment]
Fixed, now we can edit pages in different languages without problems
