### ISSUE TITLE
Edit Content leaves cache dirty

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14652]
When you are on the edit content screen and make changes to the content object and then perform a workflow action that does not "save" or "save as draft" the content, the content is changed in cache but not in the db.  We need to make sure that one of these is true 

1) When editing content, we are editing a copy of the content and not the content object stored in cache.

2) we flush the content cache after any workflow actions or editing of the content to ensure the content is properly refreshed

![dirty-content](https://user-images.githubusercontent.com/934364/41550102-c873f6ca-72f5-11e8-834d-1eaa4d3a233c.gif)

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/issues/14652

**Comment by erickgonzalez** [comment]
Still able to reproduce it.

**Comment by nollymar** [comment]
Fixed here https://github.com/dotCMS/core/pull/14807
