### ISSUE TITLE
copy whole url to clipboard

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14651]
When we do a url copy, we only copy the uri, not the whole url.  This makes it pretty hard to use - we need to copy the whole url, e.g.

https://demo.dotcms.com/about-us/index

![copy-whole-url](https://user-images.githubusercontent.com/934364/41545364-03a9c92a-72e9-11e8-8b30-641f5b6146ba.gif)

**Comment by fmontes** [comment]
Here we do the copy: https://github.com/dotCMS/core-web/blob/d2f9496088a531b29b640fec70d95d83f14448d1/src/app/portlets/dot-edit-page/components/dot-edit-page-info/dot-edit-page-info.component.ts#L60

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
