### ISSUE TITLE
Custom Fields don't work

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#14658]
Trying to add a custom field for URL Title and nothing is being printed out on the content screen.

**Reproduce.**

1. add a custom field to a content type
2. Try to add a new piece of content of that type

**Results.**
The divs are empty.

![screen shot 2018-06-18 at 3 48 09 pm](https://user-images.githubusercontent.com/1561349/41558713-b85201e6-730f-11e8-9a9c-0eecaba47216.png)

**Notes**
I tried both writing the code directly into the custom filed and trying a dotParse. Same results

**Comment by wezell** [comment]
Turns out you were using a constant field.
