### ISSUE TITLE
NavTool should include Show on Menu Pages at Root level

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14655]
NavTool should support pages, menu-links that have show on menu at the root of a host.  Right now the nav tool is only pulling directories at the root level.

To test, use the attached vtl file to pull all show on menu items from the root level (place in a simple widget on a page)

[navTool.txt](https://github.com/dotCMS/core/files/2112569/navTool.txt)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14689

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/14699

**Comment by bryanboza** [comment]
Fixed, tested on master and now is working as expected
