### ISSUE TITLE
Exclude Host Base Type from Bulk Actions execution 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14672]
In the Content Search portlet we exclude the Host Content Type as we decided that we should be able to modify Sites only from the Sites portlet and without the use of Workflows.

Now with the new Bulk Actions there are some scenarios where the ES query is returning also Sites which is wrong, we need to exclude the Host Base Type from those queries and also validate the fire action method won't execute actions over a Site.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14680

**Comment by jgambarios** [comment]
Also related to https://github.com/dotCMS/core/issues/14481

**Comment by jdotcms** [comment]
first thing: the host is not reachable from the content search now

**Comment by jdotcms** [comment]
I have made several testing (black and white box), also I have ran a few on rest without including the host, such as:

```
PUT http://localhost:8080/api/v1/workflow/contentlet/actions/bulk/fire
{
	"query":"-baseType:3 +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +(wfscheme:d61a59e1-a49c-46f2-a929-db2b4bfa88b2*) +languageId:1 +deleted:false +working:true",
	"workflowActionId":"000ec468-0a63-4283-beb7-fcb36c107b2f"
}
```

The code adds the -contentType:Host to the query if it is not there to avoid host types, good!

**Comment by bryanboza** [comment]
Fixed, now we are unable to see the host content type in the list and also we are ignoring the contents.
