### ISSUE TITLE
Time machine is showing the admin console instead the FE

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14670]
When you try to see your site in the future using the time machine tool, we are showing the admin console instead show the FE of the snapshot as we do with the past snapshots. 

## Expected Behavior
We need show the FE and not the BE (admin console)

## Current Behavior
We are displaying the admin console of the admin page, and you can navigate as in the backend 
SC: https://screencast.com/t/2nxa3OXDe

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to Site --> Time Machine  
3. Generate a future time machine snapshot 

## Your Environment
Tested on the last master // Postgres // Safari

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14804

**Comment by erickgonzalez** [comment]
Found this https://github.com/dotCMS/core/issues/14803 after fixed this one.

**Comment by nollymar** [comment]
It's working correctly. Passed internal QA
