### ISSUE TITLE
Can't rename tools

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#14685]
Under the Roles and Tools section, you can't edit the display name of the tools.

Reproduce:
1. Open the tool dialog
2. rename the tool
3. save
4. refresh the page
Result: tool name didn't update

![screen shot 2018-06-21 at 9 38 26 am](https://user-images.githubusercontent.com/1561349/41722641-21192dca-7537-11e8-817d-b4345722499a.png)

**Comment by erickgonzalez** [comment]
Note to QA: please also test that this is working https://github.com/dotCMS/core/issues/12635

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14739

**Comment by dsilvam** [comment]
Passed Internal QA. #12635 also tested and working.
