### ISSUE TITLE
Unable to see the new dashboard portlet as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14683]
We have problems when you try to access this portlet as a limited user, since now this portlet is the first in the list, when you use the login-as feature we redirect to the first portlet and have this error 

## Expected Behavior
We need to be able to see this data as any user that have permissions to access the portlet. 

## Current Behavior
We show an error on log and leave a blank page 
Log:
```
14:34:32.598  ERROR embedded_002ddashboard.render_jsp - Invalid user accessing JSP - is user 'Chris Publisher : dotcms.org.2795' logged in?
```
SC: https://screencast.com/t/WFDXy4O3GfFx

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Using the logi as feature, login as chris publisher 
3. try to see the new dashboard 

## Your Environment
Tested in the last master code // Postgres // FF

**Comment by erickgonzalez** [comment]
New Dashboard shows without issues as limited users.
