### ISSUE TITLE
Upgrade tasks from new Show On options

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14694]
We need to handle the inclusion of the new `Show On` options for existing clients.

1. Modify the System Workflow in the starter site in order to use the new `Show On` options. 
2. Modify the existing upgrade task that creates the System Workflow in order to include the new `Show On` options.
3. Create a new upgrade task that modifies any existing Workflow (except for the System Workflow) in order to add them the new `Show On` options using these rules:
   * Show On Listing if the action does NOT have a Requires Lock
   * Show On Editing if the action HAVE a Requires Lock

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14728

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14785

**Comment by bryanboza** [comment]
Fixed, tested with a real database and this is working as expected
