### ISSUE TITLE
Actions popup windows needs to work on batch actions

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14693]
Some Workflow actions allow to display popup windows with different options, those popup windows are not working with the new batch actions.

We need to make sure that works with:

* Assign To
* Comments
* Push Publish
* Custom Code

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14727

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14753

**Comment by jdotcms** [comment]
I have tested an action with assign (EDIT, LISTING, BULK) - PASSED
I have tested an action with comment (EDIT, LISTING, BULK) - PASSED
I have tested an action with assign and comment (EDIT, LISTING, BULK) - PASSED

**Comment by jdotcms** [comment]
PP and Custom code are also working on LISTING AND BULK

**Comment by bryanboza** [comment]
Fixed, now this is working as expected
