### ISSUE TITLE
Navigation problems in edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14706]
We have an error when you try to use the nav-tool navigation in the new edit mode. 

## Expected Behavior
We need to be able to use the nav-tool in edit mode without problems 

## Current Behavior
Once you try to navigate to the same page that you are, we show another admin window here 
SC: https://www.screencast.com/t/hNi13ARra

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Try to edit the about-us --> index page
3. Once you are on edit mode using the nav-tool navigate to the same page 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14828

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
