### ISSUE TITLE
Unable to see the content search portlet on FF 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14716]
We are having problems to see the content search portlet on FF, we are just showing a blank page and the portlet isn't loading 

## Expected Behavior
We need be able to work normally in any of the supported portlets 

## Current Behavior
The portlet isn't loading 

## Steps to Reproduce (for bugs)
1. Using FF login as admin 
2. Go to content --> search 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
I'm able to reproduce the issue in FF `57.0 (64-bit)` and FF `60.0.2 (64-bit)` also I see errors in console:
```
ReferenceError: event is not defined[Learn More] layout:4360:1
```
![Error](https://content.screencast.com/users/jgambarios/folders/Snagit/media/0d103180-58bb-40fc-aa51-1e752359fc67/2018-06-26_09-26-12.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14738

**Comment by bryanboza** [comment]
Fixed, tested on the last master code // Postgres // FF
