### ISSUE TITLE
Browser always sending EDIT_MODE

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14711]
If you click on a page from the CMS browser, it ALWAYS tries to send you to EDIT_MODE, even if you do not have a lock on the page.  This is incorrect.  If the page is locked by you, it should send you to EDIT_MODE, else it should send you to PREVIEW_MODE.  

1. Page is not locked
2. Taken to page passing in EDIT_MODE but the page is not locked and says PREVIEW_MODE
3. EDIT_MODE gets set in the page context which adds the reorder menu and the edit banner code BUT the page is mostly rendered in PREVIEW_MODE
4. Switch to EDIT_MODE via the tabs, then switch back to PREVIEW_MODE.  Looks like it should.

![edit_mode_oddness2](https://user-images.githubusercontent.com/934364/41873718-cc85eaa4-7893-11e8-81fa-28746949ac36.gif)

![edit_mode_oddness](https://user-images.githubusercontent.com/934364/41873409-ea4e2ac0-7892-11e8-8df2-b26c8809fc3a.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14757

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
