### ISSUE TITLE
We lost lock/unlock right click options

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14713]
Here is the browser - no unlock
![screen shot 2018-06-25 at 4 22 50 pm](https://user-images.githubusercontent.com/934364/41874054-c1cbf77e-7894-11e8-9274-b661c234e6d1.png)

Here is the content search .... Ahh, unlock
![screen shot 2018-06-25 at 4 25 48 pm](https://user-images.githubusercontent.com/934364/41874095-e3167300-7894-11e8-9195-16ebdafcb6b5.png)

**Comment by jgambarios** [comment]
Closed as we have the same behavior in previous versions.
