### ISSUE TITLE
Page properties dialog should not request for confirmation if you don't made changes  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14715]
As part of the new changes, when you open page properties we show this in an angular dialog, but we need be smarter before closing this window. 

We need to detect if you have changes in some of the fields, then we need ask for confirmation to close, but if you don't have changes just close. 

## Expected Behavior
Detect if you have changes request for a confirmation if not close without it. 

## Current Behavior
We always are asking for confirmation
 
## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content search 
3. Select some page and go to the page properties 
4. Close the angular dialog 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
I believe this is fixed.
