### ISSUE TITLE
Radio Button Search Filter on Content Not Working

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14714]
Tested on latest 5.0 release

Radio Button search is not working and does not list all the options of the field.  Here is how I have the radio button configured with two options on the Content Type:

![radiobutton](https://user-images.githubusercontent.com/1569167/41874122-2d41f370-7884-11e8-9a9e-b0f37597385d.jpg)

Here is the broken search filter on the Content Search Screen:

![bug on search](https://user-images.githubusercontent.com/1569167/41874144-3d67c7a2-7884-11e8-8053-8f8c2964a4e5.jpg)

**Comment by bryanboza** [comment]
Fixed, now this is working as expected. Tested in the last master // Postgres // FF
