### ISSUE TITLE
Clear should clear all filters in Content Search EXCEPT the Content Type

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14710]
Tested on latest 5.0

After searching for a title of a WIdget Content Type, I clicked clear and it clears out all the filters, but also clears out the Content Type.  We should not clear out the content type.

**Comment by erickgonzalez** [comment]
Not able to reproduce it with the latest master.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14794

**Comment by DeanGonzalez** [comment]
passed QA
