### ISSUE TITLE
Select box breaks content screen

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#14725]
Add a select box to a content type seems to break the content search screen. 

Steps to recreate:

I added a select field to a content type with the following option in the select:

Analytics|analytics
CDN|cdn
Cloud|cloud
CRM|crm
DAM|dam
eCommerce|ecommerce
Marketing Automation|marketing
Search|search
Plugins|plugins

I then went to the content search screen and tried to filter. 

Only the first option was displayed in the dropdown

Searching by the only option available broke the backend. I needed to close my browser to get it working again.

See Video: https://www.dropbox.com/s/svr4u1wp4q36ni8/select-box-issue.mp4?dl=0

**Comment by bryanboza** [comment]
fixed, tested on master and now this is working as expected
