### ISSUE TITLE
Unable to add/edit events 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14720]
We have an error trying to compile the JSP file and we are unable to add new events in the calendar portlet 

## Expected Behavior
We need to be able to add events to the calendar without problems 

## Current Behavior
We have an error in the JSP file and we are unable to add new ones
Here the error: https://gist.github.com/bryanboza/91a54ed3130718150be606cb6e9e2252

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to the calendar portlet 
3. Try to add a new event 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14735

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
