### ISSUE TITLE
Download and resource link isn't working for assets 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14731]
We have problems when you try to download any asset or try to use the resource link, this because the system isn't finding the link and shows a 404 

## Expected Behavior
Both links should work 

## Current Behavior
We show a 404 error and you can't download or open the asset

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to application --> Vtl and try to edit any file 
3. Try to download the file or see the resource link

## Your Environment
Tested on master // Postgres // FF

**Comment by jdotcms** [comment]
after a research, the restriction to download a file vtl or vm is intentional.
more info here: https://github.com/dotCMS/core/issues/12855

**Comment by wezell** [comment]
we should hide the link for .vtl and .vm

**Comment by wezell** [comment]
Take a look at this which allows you to config the resource link for images

https://dotcms.com/docs/latest/the-wysiwyg-field#ImageURLFormat

**Comment by bryanboza** [comment]
We need to remove the redirect functionality when you click in the FileLink field in the info modal...
https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/17c89d28-5b40-4c0e-abda-2eef69ea6c60/00000252.png

**Comment by bryanboza** [comment]
Sorry guys, but after the change, I think don't make sense continue showing the info just for the file name, I think we need to remove the info button here.  Almost when is a file asset, but we need to take care because this is used in other types of files and works as expected 
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/a4797f96-a3f4-4141-8825-f8f043d1f3ff/00000268.png

**Comment by DeanGonzalez** [comment]
After a meeting with Will, the new directives on this ticket are:

Front End Client Website behavior
1) Make .vtl and .vm files completely inaccessible from a front-end website (even with front-end login).

Logged in dotCMS Backend Behavior

2) Before displaying the Info button for .vtl and .vm files, we will check backend user permissions (No special logic, just permission check where useFrontendRoles=false).  If the user has at least view permissions to the file, the info button will display.  If the user does not have permissions to the file, the info button will not appear at all

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15138

**Comment by bryanboza** [comment]
We need some work here. After the fix now we are validating the session but not permissions.
e.g: If you log in as any limited user, and then go try to download the asset with the link, we allow download the file, but you don't have permissions.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15218

**Comment by bryanboza** [comment]
We continue with a wrong behavior here, now we validate the permissions, but if you don't have session, we are allowing see/download the file

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15244

**Comment by bryanboza** [comment]
We continue with permissions problems here, we are able to download//see the file without session

**Comment by bryanboza** [comment]
Tested after the last changes and now we have the correct validations to this kind of files
