### ISSUE TITLE
Content type > category field loses selection

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14733]
add a category field to a content type

edit it again and the category you selected is not selected

**Comment by wezell** [comment]
![category-field](https://user-images.githubusercontent.com/934364/41995972-6dc9caf0-7a21-11e8-9bd0-ccdf4c9237e2.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14780

**Comment by bryanboza** [comment]
Fixed, now we are saving the selection. New card created here: https://github.com/dotCMS/core/issues/14797
