### ISSUE TITLE
Cascade of Permissions from Content Type not working

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14736]
Reproduced in latest Master

Cascade of permissions from host is not applying permissions to content that was previously created before the new role was added.

![permissions bug](https://user-images.githubusercontent.com/1569167/42000948-a2286998-7a1f-11e8-9582-9ec97055be93.png)

To reproduce:
1) Create a new content type
2) Add content using the new content type
3) Add a new role
4) Edit the content Type again, and on the permissions tab, add the new role with publish rights on the content, then click the checkbox to cascade permissions to the existing content.
5) *Bug - edit one of the previously created contentlets... the role does not get applied and is not visible on the permissions tab

Screencast: https://www.screencast.com/t/DhJXRebQo

**Comment by wezell** [comment]
fixed in #20504
