### ISSUE TITLE
JS errors in the new content types portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14742]
We have some javascript errors when you are navigating in the new content types portlet

Here more details: 

- [ ] We have a filter on this portlet, and if you try to search by some word and the system isn't finding consistencies. We have a JS error and the portlet never finish to load
SC: https://screencast.com/t/Xmlwju2bAR

- [ ] If you are on the detail window of some content type and click in the content types portlet link in the angular menu. We have a JS error after refreshing the page 
SC: https://screencast.com/t/wZ0fBASPpfv7

## Your Environment
Both cases tested on master instance // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14791

**Comment by bryanboza** [comment]
I'm able to reproduce the second case in the last master code 
SC: https://screencast.com/t/1kArDwXkiRwF

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
