### ISSUE TITLE
Range requests reading file in memory

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14744]
I might be mistaken here, but this it looking pretty bad and it can easily be replaced with a file.length call.  Affects large vids, what have you:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/servlets/BinaryExporterServlet.java#L457

ref:
https://isc.sans.edu/diary/The+HTTP+Range+Header/15541

**Comment by wezell** [comment]
Yup, brings my local to its knees.  Good news is that our bin exporter does not advertise the capability
<img width="1304" alt="screen shot 2018-06-28 at 8 34 16 pm" src="https://user-images.githubusercontent.com/934364/42067161-d2fd1f70-7b12-11e8-92cc-fa14e458ae8e.png">
<img width="1584" alt="screen shot 2018-06-28 at 8 35 50 pm" src="https://user-images.githubusercontent.com/934364/42067175-e5c2e59a-7b12-11e8-8bb3-6f5e70549fe2.png">

.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14745

**Comment by bryanboza** [comment]
Fixed, testing with multiple calls to really large videos (2 GB) and works perfect
