### ISSUE TITLE
Duplicated OSGi classes on classpath

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14746]
While looking into some OSGi issues, I noticed that we have multiple copies of some OSGi classes on our classpath.  

A specific example is BundleContext.  Here are the occurances found on an installation of the 20180626 nightly build:
```
    |♦ findclass.sh . /BundleContext.class
    ./dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/felix/bundle/org.osgi.core-5.0.0.jar:org/osgi/framework/BundleContext.class
    ./dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/lib/org.apache.felix.framework-5.6.2.jar:org/osgi/framework/BundleContext.class
    ./dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/lib/org.apache.felix.main-5.6.2.jar:org/osgi/framework/BundleContext.class

```

I did some investigating and found that org.apache.felix.main-5.6.2.jar and org.apache.felix.framework-5.6.2.jar have 345 classes that are exactly the same same.  The main jar has 3 additional classes that the framework jar does not have.  The framework jar does not have any classes that are not contained in the main jar.  It would be totally safe to remove org.apache.felix.framework-5.6.2.jar from our build and distribution.  One duplicate down.

org.osgi.core-5.0.0.jar is a little trickier.  It has duplicate classes but it is from a different source, older, and does not have all of the same classes as the felix libraries.  It is from 2012 - not sure why it is needed but as you can see above, it is in the .../ROOT/WEB-INF/felix/bundle directory rather than the normal lib folder which makes me think it may serve some special purpose.  In my local testing, things seemed to work the same without the jar as they did with the jar but there may be some special case that I did not trigger.

**Comment by wezell** [comment]
I believe we can/should remove `org.osgi.core-5.0.0.jar`

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/14832
https://github.com/dotCMS/enterprise-2.x/pull/624

**Comment by jdotcms** [comment]
After checking latest deployment, the jar is not longer there
```
$ pwd
../tomcat8/webapps/ROOT/WEB-INF/lib
$ find . -name "org.*"
./org.apache.felix.framework-5.6.10.jar
./org.apache.felix.http.api-3.0.0.jar
./org.apache.felix.http.base-3.0.18.jar
./org.apache.felix.http.bridge-3.0.18.jar
./org.apache.felix.http.bundle-3.0.0.jar
./org.apache.felix.http.cometd-2.3.2.jar
./org.apache.felix.http.jetty-3.0.0.jar
./org.apache.felix.http.proxy-3.0.2.jar
./org.apache.felix.http.servlet-api-1.1.2.jar
./org.apache.felix.http.whiteboard-3.0.0.jar
./org.apache.felix.main-5.6.10.jar

```

**Comment by bryanboza** [comment]
Fixed, now we don;t have this file
