### ISSUE TITLE
Problems editing pages as limited user in the new edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14743]
Related to #13325 

We have some problems when you try to edit pages as a limited user in the new edit mode 

## Expected Behavior
As in previous versions if a user has full permissions over some page we need be able to edit anything related to the page without problems 

## Current Behavior
When you try to edit the page we have an error in the log, and we have more problems when you try to make some change in the layout tab. 
SC: https://screencast.com/t/7dc1l38T
Log: https://gist.github.com/bryanboza/4c3b4e520720dec7f4d2f03c7a277438

**Note: I think the problem here is because the limited user doesn't have read permissions to folder "application/themes"**
 
## Steps to Reproduce (for bugs)
1. Login as admin user  
2. Edit the "about-us" permissions and add full permissions to Chris Publisher 
 https://screencast.com/t/fb5FW0Pj
3. Login as Chris publisher 
4. Try to edit the page "/about-us/index" 
5. Go to the layout tab in the edit mode 

## Your Environment
Tested in master // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14812

**Comment by bryanboza** [comment]
Not sure, but maybe this is related or can be affected with the card #14850, we need test both after the fix

**Comment by bryanboza** [comment]
Fixed
