### ISSUE TITLE
Unable to navigate to folders in the Site/Folder fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14750]
After the UI changes, now we are unable to select folder when you are adding content and have a site/folder field 

## Expected Behavior
We need be able to navigate through the folders of the sites

## Current Behavior
We can select just the site 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types 
3. Create a new content type with site/folder field 
4. Try to add a new piece of content and try to select an specific folder in the site/folder field 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryanboza What is the bug here?  That the content type itself cannot be assigned to a site or folder? or that the content of the content type cannot have a site/folder field?

**Comment by wezell** [comment]
@bryanboza please retest

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
