### ISSUE TITLE
Hide workflow options if content is not current version

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14758]
In the edit content screen, we need to hide workflow options if the content is not the latest version.  Additionally, we should show a link back to the "See latest version" in addition to the "Bring back this version"  option. 

Current Behavior - we show workflow options based on the current state of the content, even though we are looking at an old version

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14856

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14930
