### ISSUE TITLE
UI: Unable to execute bulk actions on FF

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14762]
We have problems trying to execute the bulk actions on FF.

## Expected Behavior
We need to be able to execute those actions from any supported browser 

## Current Behavior
We have a dojo error on the console every time you click on the action 
<img width="1677" alt="console1" src="https://user-images.githubusercontent.com/2641437/42187791-8cd515e4-7e0e-11e8-8b02-717349be1d62.png">

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to content search 
3. Select multiple actions 
4. Try to execute the available actions 

## Your Environment
Tested on master // FF 60.2

**Comment by jgambarios** [comment]
Fixed with https://github.com/dotCMS/core/pull/14766

**Comment by bryanboza** [comment]
Fixed, tested on master // FF
