### ISSUE TITLE
findAvailableActions endpoint enhancements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14771]
As part of the new changes, we need to improve the experience using every one of the new endpoints, after the last changes we need to update some things on that one.  

- [x] We need to update the JavaDoc and indicate the "renderMode" is an optional parameter and how to use. 

- [x] Since this is an optional parameter, we need to make sure if you send this we are using it, in order to avoid confusions. If you send this parameter and send something different to "listing" or "editing" we need to return a 404 (not found) instead use the default. The default is ok if you don't send anything, but if you send something we need to use. 

- [x] Also if you send an invalid parameter or something different to "renderMode" we need return 400(bad request), this because in this case, the error is in the URL. 

### Testing Info
Tested in the last master // Postgres

**Comment by jdotcms** [comment]
For the third one, it is pretty much than the second one. Now if an user sends anything else as a query string we not used to check if it is ok or not, or even expected or not, the users can pass whatever they want it could be for filters, servlet etc.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14786

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
