### ISSUE TITLE
Unable to edit the page/asset permissions if does not exits in the default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14779]
We are unable to see the asset or page permissions if this does not exist in the default language 

## Expected Behavior
We need to be able to edit the permissions without problems 

## Current Behavior
We have an error in the JSP file and the permissions tab never loads
Log: https://gist.github.com/bryanboza/ab26211c1b67cb867b2840d87e45b6e5

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to site browser 
3. Add a new page or asset in Spanish (without English version )
4. Try to edit the permissions 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14806

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
