### ISSUE TITLE
Broken pipe error navigating on Firefox 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14782]
We are having an error processing cookies when you navigate through portlets using firefox

## Expected Behavior
We need take look of this error and avoid that behavior 

## Current Behavior
We have the following error just trying to navigate through portlets
Log: https://gist.github.com/bryanboza/2ea9e214924d7f47d9a01a65b27ac255

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Site browser 
3. Navigate to content search and click in other portlets too 

**FYI: Seems sporadic but it's easy to reproduce** 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
This is a known issue with tomcat, not with dotCMS.
