### ISSUE TITLE
Content by Id not utf-8

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14783]
When you call the rest api for a content, e.g. `/api/content/id/123123012312-123213-213213`, it does not return`utf-8`, it returns `TEXT/PLAIN`.   We need to change the     `@Produces(MediaType.TEXT)` to     `@Produces(MediaType.APPLICATION_JSON)`

## To test 

1. Add content in chinese
2. call it direct by the api (inode or identifier) and see it broken
3. Inspect the headers and see that we are sending the wrong mime type

Additionally, do we need to explicitly add charset=utf-8 to all our endoints?  See the proper way to do this system wide - with a filter:

https://stackoverflow.com/questions/5514087/jersey-rest-default-character-encoding/20569571
```
@Produces(MediaType.APPLICATION_JSON)
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14870

**Comment by bryanboza** [comment]
Fixed, tested on the last master code
