### ISSUE TITLE
OSGi exported packages getting corrupted when edited through backend UI

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14799]
When a package is added to the list of Exported Packages, the osgi-extra.conf file seems to be saved correctly with the changes.  However, if you open the Exported Packages popup a second time, it seems that the contents of the osgi-extra-generated.conf file are being appended to the line of your package.  

![image](https://user-images.githubusercontent.com/3208956/42400960-1da3b404-8139-11e8-8742-5b3e91621cfe.png)

So now if you unwittingly save this popup, your package name is corrupted and you osgi-extra.conf is twice as long as it was because all of the original packages are included twice.

Details of contents are recorded here for your review:  https://gist.github.com/brentgriffin/0417c9ad099d57ad8e95d85fedeef8fa

## Known Workarounds

Manually edit the osgi-extra.conf or the data in the popup

## Steps to Reproduce (for bugs)

1.  Startup dotcms
2. On plugins page, click "Exported Packages"
3. At the end of the list add a ",", hit <RETURN>
4. Add packages you want to add to list - i.e. com.dotcms.osgi.oauth
5. Click on "Exported Packages" again and notice two things.  the package that you added has been merged together with another package and all of the original packages are in there twice.

## Your Environment

* dotCMS version used:  master nightly from 20180703

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/14832
https://github.com/dotCMS/enterprise-2.x/pull/624

**Comment by bryanboza** [comment]
Fixed, now we are not duplicating the packages, tested on master // Postgres // FF
