### ISSUE TITLE
NPE trying to find consistencies in the categoryResource 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14797]
We have an error every time you try to find some consistency and this does not exist 

## Expected Behavior
If you try this and don't exist consistencies we need to handle that case and avoid this NPE

## Current Behavior
We have an NPE in the resource 
log: https://gist.github.com/bryanboza/90e76439025d3aad5a1ebd50a203247a

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content type and add a category field 
3. Try to add a new piece of content 
4. Using the search in the category field try to fina consistencies for "aaa"

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14808

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
