### ISSUE TITLE
We need exclude the Host cotnent type from the list of conten types to import

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14800]
Since the Host content type is a restricted to apply workflow actions, we need to remove this content types from the list. 

## Expected Behavior
By rule, we are unable to apply workflow actions to contentlets of the Host content type, but we have a fallback in the import process and this is ignoring the rule, then you are able to import sites. 

## Current Behavior
If you try to import some contents to the Host content type and don't select one of the available actions in the drop-down we are applying the fallback, and this is doing a check-in. Then we save the sites 
<img width="539" alt="img_host" src="https://user-images.githubusercontent.com/2641437/42402583-f8f2cba4-8138-11e8-97e6-25131e48abd1.png">

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content search --> Import Content
3. Select the host content type and leave the action drop-down empty 
4. Select the correct CSV file
5. Try to import 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14801

**Comment by bryanboza** [comment]
Fixed, tested on master and now we don't have this structure on the list
