### ISSUE TITLE
Delete a contentlet from the actions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14809]
As a user I want to be able to delete a contentlet form the edit contentlet page.

## Expected Behavior
User should delete a contentlet and the dialog should close with no errors.

## Current Behavior
User deletes de content but the dialog remain and there is an [error](https://gist.github.com/bryanboza/349d3bf0e3eaa3aa0094d1c07fda590b) in the log.

## Possible Solution
Check for the workflow that is being trigger and emit a close if it's a delete.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
https://screencast.com/t/nYby734007k6
 **In order to do that:** edit the System Worflow and in the step:
1. New: edit "Unpublished" and check "editing"
2. Same goes with "Archive" in Unpublished step

## Acceptance Criteria

1. Close the dialog after a contentlet is removed
2. Refresh the content search list
3. If edit mode: refresh the page and save the without the deleted content
4. If edit mode and delete the page itself (from page props) redirect to the site browser
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14827

**Comment by bryanboza** [comment]
Fixed, tested on master and now we close the dialog and delete the content
