### ISSUE TITLE
Put Back the set of Content Type in Session after edit

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#14818]
Tested on latest master

This is helpful UI behavior that has accidentally been removed while making the 5.0 version.  For a very long time, after editing a Content Type, if you went to the Content Search manager, the Content Search manager was smart and was already set to filter by the Content Type you had just made edits to.  All versions have worked this way back to the 3.x series.  

We should not remove this behavior.

![bug](https://user-images.githubusercontent.com/1569167/42585641-736a7086-84f3-11e8-911d-d9c734be5230.jpg)

**Comment by DeanGonzalez** [comment]
Working correctly now.

**Comment by wezell** [comment]
dupe #14818
