### ISSUE TITLE
When initializing with a new DB (even unintentionally), existing assets are wiped out

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14819]
If you start dotCMS and no database is found the starter.zip is used to create a new database.  However if you have any assets in the assets folder when this is done, the existing assets are wiped out.  This means that a very small error (forgetting to copy the context.xml file, or even misconfiguring it by a single character) can cause a very destructive operation (wiping out all assets).

Bottom line, the default behavior is destructive when it doesn't need to be, and that can cause significant issues including data loss.  In most cases, destructive operations should require explicit choices, rather than being implicit/default behavior.

## Expected Behavior

If there are existing assets in the assets folder but no database is found, the existing assets should be backup up (moved to a different folder) instead of being wiped out.

## Possible Solution

Check to see if there are existing assets in the assets folder (via the existence of expected subfolders) and if so, rename the existing assets folder and create a new one.

## Known Workarounds

If customers have followed the upgrade procedures fully and made a backup of their assets folder, then they can restore the assets folder from backup.

If they haven't followed the upgrade procedures then there is no workaround, and they either will have to revert to an old backup (losing some changes) or in the worst case lose all their assets.

## Steps to Reproduce (for bugs)

1. Upgrade an existing dotCMS instance to a new version.
    * Make sure to set the assets path correctly to point to the existing assets.
    * But don't copy the context.xml file to the new dotCMS distribution.
2. Start dotCMS
    * Result: The contents of the assets folder are wiped out and replaced with the assets from the starter.zip file.

## Context

This is potentially highly destructive, and although customers who follow the proper upgrade procedures will only lose time (to find and solve this problem), those that don't follow the upgrade procedures will irrevocably (and unnecessarily) lose data.

Although failing to backup the assets and failing to properly follow the upgrade procedures can both be classified as user errors, people do make mistakes so errors will happen.  And having the potential for a relatively simple user error to cause potentially critical data loss is not a good approach (especially when it wouldn't be difficult for us to prevent the loss).

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14998

**Comment by erickgonzalez** [comment]
Working as it should, now if you forget to change the context.xml the assets are not wiped out.
