### ISSUE TITLE
Sorting in Content Search is incorrect

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14821]
When you sort the Content Search screen by selecting a column header, in at least some cases the results are not sorted correctly.

## Expected Behavior

All content items should sort correctly in the Content Search screen.

## Current Behavior

On our authoring server, when you sort by Last Edit Date descending, there are seven content items of the "Simple Widget" content type that appear at the top of the list, with Last Edit Date values from 03/23/2018 to 06/05/2018 - even though there are other content items with Last Edit Date values of 07/10/2018 which sort below the Simple Widget content items.

On the starter site, there is one Simple Widget content item that sorts out of order in the same way (at the top of the list when sorting by "Last Edit Date" descending).

**Notes:**

* This happened after authoring was fully reindexed, so this does not appear to be correctable with a reindex.
* There all other content items of the same Simple Widget content type seem to sort correctly by the Last Edit date - it is only these few that are sorting differently.
* When you do a "Show Query" on the Content Search screen, the queries show that the content is being sorted by "modDate desc" - which is correct.  So the error appears to be in either some content fields that aren't showing, or in how the index is being created.
* Both authoring and starter were upgraded at some point from 4.x to 5.x, so there's a possibility this could be an artifact of the upgrade (unknown how likely this is).

## Known Workarounds

None.

## Steps to Reproduce (for bugs)

1. Log onto the starter site.
2. Open the Content Search screen.
3. Click the "Last Edit Date" column header to sort by this field.
4. Click the "Last Edit Date" column to reverse the sort order by this field.
**Result:** There is one Simple Widget content item which displays at the top of the list, even though its "Last Edit Date" field has a value that should sort lower in the list.

## Context

This is a basic feature that needs to work.  But hints that there might be a deeper problem with indexing or the new ES changes which could cause more serious problems.

## Your Environment

* dotCMS version used:
    * Authoring: Nightly from 07/06.
    * Starter: unknown 5.0 build.
* Browser Name and version: Chrome 67.0.3396.62
* Operating System and version: Win 10 Pro
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8 (auth & starter)
* Database and version: Postgres (auth)

**Comment by john-thomas-dotcms** [comment]
Image from starter showing the issue:

![image](https://user-images.githubusercontent.com/13456955/42589438-cef0f572-84f5-11e8-97d2-afa1e39932b8.png)

**Comment by john-thomas-dotcms** [comment]
Image from starter showing the issue:

![image](https://user-images.githubusercontent.com/13456955/42589464-e4718830-84f5-11e8-8c1d-a12461e34e65.png)

**Comment by nollymar** [comment]
Fixed. We were adding the *_dotraw* suffix to the sortBy criteria.
PR Core: https://github.com/dotCMS/core/pull/14824

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected
