### ISSUE TITLE
We are losing the radio field values after add contents in forms

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14822]
We have problems adding content to forms, this because we lost the selection in radio fields after saving the content. The same behavior with check boxes 

## Expected Behavior
We need to remember this selection when  you save the content 

## Current Behavior
When you are adding a new piece of content to any form, you select some value and save it. After you try to open this content from the backend, we lost the selected value 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Add a new form, add a radio field with 2 options 
3. Create a new page and add this form to the page 
4. From FE, navigate to the page and add a new piece of content using the form 
5. Try to see the saved content from BE 

## Your Environment
Tested on master // Postgres // FF

**Comment by bryanboza** [comment]
We still having the same problem with checkboxes

**Comment by fmontes** [comment]
@bryanboza Is working for me
