### ISSUE TITLE
Calendar portlet isn't showing the workflow actions properly 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14833]
In the calendar portlet, when you try to edit any event, here we always have the same options regardless of the workflow

## Expected Behavior
We need to show the corresponding actions according findAvailableActions. 

## Current Behavior
Always have the same actions 
https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/6053556a-96e6-4f6e-848d-cb62126ef113/00000156.png

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new workflow (WF)
3. Assign this WF to the event content type 
4. Add a new event and save it using the new WF
5. Go to calendar portlet and try to edit the event, make sure you have the available actions of the WF

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14872

**Comment by bryanboza** [comment]
Fixed, tested on master and now we have just one option here
