### ISSUE TITLE
Error adding a new template

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14834]
We have an error trying to add a new template 

## Expected Behavior
We need to be able to add templates without problems 

## Current Behavior
We have an error every time you try to add a new template using the template designer, seems we are calling an unexisting method 

Here the log: https://gist.github.com/bryanboza/77217e9420f0d7812b172f727da03c0a

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content --> templates 
3. Try to add a new template using the template designer 

## Your Environment
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14944

**Comment by erickgonzalez** [comment]
I tested Will's commit and the error no longer shows up.

**Comment by bryanboza** [comment]
Fixed, now I'm able to add templates without the error
