### ISSUE TITLE
Uploading an Image from the Image browser gets a 404 Error

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#14836]
When you edit a piece of content that has an Image Field and then you try to upload a new image from the Image Fields browser you get a 404 error when you try to upload.

## Expected Behavior
The new image should be uploaded and not return a 404 error

## Current Behavior
Returns a 404 error when you try to upload an image

## Steps to Reproduce (for bugs)
1. Edit an event or any piece of content that has an "Image" field
2. Click the "Browse Button"
3. Navigate to a folder
4. Click "Upload New File"
5. Select a file/image to be uploaded from your desktop
6. Select a workflow action to be executed
7. Click "Execute Button"
8. Returns a 404

See Video: https://www.dropbox.com/s/zpjybiji2lqxooe/file-upload-404-error.mp4?dl=0

**Comment by DeanGonzalez** [comment]
I tested this with existing events and with new events and I was able to upload without issue.  What environment?

<img width="1227" alt="screen shot 2018-07-13 at 5 59 38 pm" src="https://user-images.githubusercontent.com/1569167/42718482-8a731f38-86c6-11e8-934b-e032333e150d.png">

**Comment by fishsmith** [comment]
Was that a binary field or an Image field. Binary works fine.

Jason Smith
dotCMS Inc
www.dotcms.com
786.594.5283
