### ISSUE TITLE
[Calendar Events] : FE Calendar is failing to display events in List View

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#14837]
Reported by customer via Support: https://dotcms.zendesk.com/agent/tickets/96159
Reproducible in dotCMS 4.3.3, code also missing in master 5.0

## Expected Behavior
Users should be able to select the List View of the calendar and see the events in list format without issue.

## Current Behavior
Users CANNOT view any events in the List View. Only days without any events are displaying correctly.

## Possible Solution
Inspect code and find the bug.

## Known Workarounds
DO NOT select the List View option, and use the Week and Month View options instead.

## Steps to Reproduce (for bugs)
1. Get the DB and assets from the support team.
2. Go to the page where the Events Calendar is being displayed.
3. Select one of the options in the `List View` dropdown.
4. The loading indicator shows up. However, it just keeps spinning and never displays any information related to events.

## Context
This feature was working on their previous 3.7.2 environment. After the upgrade, it stopped working.

## Your Environment
* dotCMS version used: 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: FE Calendar.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/14838

**Comment by bryanboza** [comment]
This was tested with the client and works as expected
