### ISSUE TITLE
Edit twice a contentlet is crashing the app in the jsp side

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14844]
## Steps to reproduce
1. Login
2. Go to content search
3. Edit a contentlet (close the dialog)
4. Edit the same contentlet
5. See the console

** same thing happen when you edit a contentlet from the edit page **

## Acceptance Criteria

1. User should be able to edit the same contentlet as many time as he want with no errors
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Unable to reproduce in the last master
