### ISSUE TITLE
Send host id to the theme selector endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14846]
Theme selector not showing results when first load

## Expected Behavior
Theme selector should show results of the current site

## Current Behavior
Not showing results until you select a site if you only have one site you can't do nothing.

## Steps to Reproduce (for bugs)

1. Login
2. Edit a page layout
3. Click in the theme button
4. NO RESULTS...

## Acceptance Criteria

1. Theme selector should show items for the current site
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected... 

Postman test updated.
