### ISSUE TITLE
com.dotcms.util.HttpRequestDataUtil.isIpMatchingNetmask does not support IPv6

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#14845]
com.dotcms.util.HttpRequestDataUtil.isIpMatchingNetmask() does not support IPv6 IP addresses or CIDRs

If it does not need to support old netmasks, it could just be changed to use the soon to be added com.dotcms.util.network.IPUtils.isIpInCIDR() method.  Of course the rules engine UI that utilizes this functionality would also need to be updated.

I did add changes to keep the code from throwing exceptions if IPv6 address or CIDRs are used but adding full support for IPv6 and changing the rules UI is beyond the scope of my current work.

## Expected Behavior

Should be able to handle IP addresses like:  0:0:0:0:0:0:0:1 and CIDRs like 0:0:0:0:0:0:0:1/128

## Known Workarounds

Exact matches of IPv6 IPs should work with the changes I made.

**Comment by swicken-dotcms** [comment]
Reopening as we have a customer requesting this: https://dotcms.zendesk.com/agent/tickets/115555
