### ISSUE TITLE
Navigate from certain pages doesn't work in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14857]
When you navigate from our-team or location the page state seems not to be updated it.

This happens when you switch from edit mode to layout mode and back again, then navigate to the homepage.  You will see that the url does not update.

**Comment by alfredo-dotcms** [comment]
looking at this, it only happens when the page is locked(padlock icon), if the pages are unlocked, then the state is updated

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
