### ISSUE TITLE
Unable to see the changes after edit the page theme using the new theme selector in the new edit mode  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14850]
We are having problems to see the changes after edit the theme using the theme selector in the new edit mode when you come back to the content tab we need be able to see the changes and we still showing the old theme. 
 
## Expected Behavior
After changing the theme and come back to the content tab we need to display the page with the new theme here 

## Current Behavior
We are not refreshing the new changes
SC: https://www.screencast.com/t/WGkBxBFfz

FYI: This is working just the first time  

## Steps to Reproduce (for bugs)
1. Create a new page using the quest theme 
2. Try to edit and go to the layout tab
3. Change the theme to one-pager 
4. Go back to the content tab 
5. Repeat the steps 3 and 4 but now with intranet
6. Make sure you're able to see the changes 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
I cannot reproduce this

**Comment by bryanboza** [comment]
Hey @wezell, this is working the first time, after you try again this doesn't work 
SC: https://screencast.com/t/w1KYmzAkvj

**Comment by alfredo-dotcms** [comment]
this seems to be BE, the layout that comes to be rendered from the endpoint is not the latest.

After you do a Flush manually in the app, now you get the latest theme applied

**Comment by freddyucv** [comment]
we need clean this cache when we save a new layout

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/factories/MultiTreeFactory.java#L424

the layout is saved in this end point

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java#L217

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14906

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now it looks better, unable to reproduce the error
