### ISSUE TITLE
Unable to open the edit page from content search portlet

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14851]
As in previous versions when you double click to some page in the content search portlet, we display the page properties, and after you save changes, we need redirect to the edit mode of this page

## Expected Behavior
We need be able to go directly to edit some page from content search portlet, right now we are just able to see the page properties dialog, and we don't have the preview option in right click 

## Current Behavior
If you double-click just open the page properties dialog 

## Steps to Reproduce (for bugs)
1. Create a new page
2. Go to content search and search for this page 
3. Double-click to edit 
4. Make sure the system redirect to edit mode 

## Your Environment
Tested on master // Postgres // FF

**Comment by petedegraw** [comment]
I'd also suggest adding "open to Page Preview" since, after all, many people have thousands of pages and may use content search to find their pages but dotCMS doesn't currently provide access to Page Preview from the Edit mode.
