### ISSUE TITLE
test pushing a rule that does not have a conditionlet and/or an actionlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14863]
Test this from the rules portlet and test this from a page with a rule on it.

**Comment by erickgonzalez** [comment]
Tested the following scenarios and all worked without issues:
- From Rules Portlet
    - Created Empty Rule and PP.
    - Created Rule with Empty Actionlet and PP.
    - Created Rule with Empty Conditionlet and PP.

- From Rule Tab (when Editing a Page)
    - Created a Page with 3 Rules (one empty, one with empty actionlet and one with empty conditionlet) and PP.
    - Created a Page with an Empty Rule and PP.
    - Created a Page with a Rule with Empty Actionlet and PP.
    - Created a Page with a Rule with Empty Conditionlet and PP.
