### ISSUE TITLE
Respect color scheme in workflow steps view

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14862]
I believe this is the only place in the system that the colors are not respected:

![Screen Shot 2018-07-17 at 3.33.28 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/0d56eb03-fbc0-46a2-aaab-958d7716349f)

**Comment by fmontes** [comment]
`html/portlet/ext/workflows/schemes/workflow.css`

**Comment by bryanboza** [comment]
Fixed, now this is working
