### ISSUE TITLE
URLMaps do not work on auth.dotcms.com

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14861]
Most probably due to index upgrade, but urlmaps are no longer working.  You can see them broken systemically:

https://authoring.dotcms.com/plugins/export-to-word

https://authoring.dotcms.com/codeshare/quick-and-easy-star-ratings

https://authoring.dotcms.com/company/news/dotcms-reveals-new-content-as-infrastructure-philosophy-for-api-era

**Comment by dsilvam** [comment]
fixed on https://github.com/dotCMS/core/issues/14882
