### ISSUE TITLE
Unable to manage content in non-default language (where page is in default language)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14867]
When you edit an english page and change your "view as" language to spanish and then add a piece of spanish content to the page, the content does not get added and you get an error in the js console:

![Screen Shot 2018-07-17 at 5.18.45 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/166e41bb-63ec-4ca1-a1b0-2b5226993dfe)

Additionally, if you have a piece of content that is translated on a page in the default language, it will appear properly on both languages but you cannot delete the content from the page while viewing in the non-default language

Here is Bryan's screencast
https://screencast.com/t/slM3E5HbuUSg

**Comment by wezell** [comment]
![multi-lingual-fails](https://user-images.githubusercontent.com/934364/42846065-cf19a658-89e5-11e8-8db7-126b3fa60ac9.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14879

**Comment by bryanboza** [comment]
Here another video how to reproduce, also in this case we need to return a 400 error in the endpoint and show some type of WARN to the end user to let know about the error.
SC: https://screencast.com/t/slM3E5HbuUSg
