### ISSUE TITLE
Rename LanguageWebAPI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14878]
We have two LanguageWebAPIs - one is a real one that you get by the WebAPILocator and one is a fake one that is really just a viewtool:
`com.dotcms.rendering.velocity.viewtools.LanguageWebAPI`

The problem is we are putting backend/system important methods in the viewtool LanguageWebAPI without realizing it.

**Comment by wezell** [comment]
This fixes #14867

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14879

**Comment by wezell** [comment]
EE PR: dotCMS/enterprise-2.x/pull/625

**Comment by dsilvam** [comment]
Let's write a test for the new API method `HTMLPageAssetAPI.findByIdLanguageFallback`

**Comment by bryanboza** [comment]
Fixed, I tested the following viewtools here: 
- text
- globalvars
- glossary
- utilHtml
- languagewebapi
- langbackendwebapi
- pluginapitool
- xsstool

Also tested again the language fallbacks here.
