### ISSUE TITLE
Allow sass compilation via file extension, not just prefix

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14874]
Right now, we allow SASS files to be compiled by prefixing the call with DOTSASS, e.g.
`<link rel="stylesheet" href="/DOTSASS/application/themes/one-pager/sass/main.css">`

We need to also allow for a SASS file to be compiled by changing the file extension (not forcing a prefix), e.g.
`<link rel="stylesheet" href="/application/themes/one-pager/sass/main.dotsass">`

## Reasoning 
The reason for this is that by requiring the `/DOTSASS/` prefix, you lose the ability to reference images and other assets via a relative url, which makes the entire theme less portable.  In 5.x and beyond, themes are taking on a much bigger role making this a more important issue.

## Example 
In our current starter we have the "one-pager" theme that requires images as backgrounds.  To reference them in css, we currently need to fully path to them, like so:

```
body {
...
  background-image: url("/application/themes/one-pager/img/background-body.jpg");
  background-attachment: fixed;
  background-position: 50% -20px;
  background-repeat: no-repeat;
  background-size: 100% auto; }
```

If you want to copy this theme to a new folder or change the theme name, you need to update all the css files that reference images under `/application/themes/one-pager/img` for the new theme to work. 

If we enable SASS compilation based on a file extension:
`<link rel="stylesheet" href="/application/themes/one-pager/sass/main.dotsass">`

We can now reference images in our css using a relative path which makes the whole theme completely portable as a unit

```
body {
...
  background-image: url("../img/background-body.jpg");
  background-attachment: fixed;
  background-position: 50% -20px;
  background-repeat: no-repeat;
  background-size: 100% auto; }
```

## Testing
These two urls should return the same file:
`http://127.0.0.1:8080/DOTSASS/application/themes/quest/sass/main.css`
`http://127.0.0.1:8080/application/themes/quest/sass/main.dotsass`

**Comment by dsilvam** [comment]
TestCase: http://qa.dotcms.com/index.php?/cases/view/62073

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/server-side-compiling-of-sass-files#TemplateReference

**Comment by erickgonzalez** [comment]
Both links return the same file.

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now we are compiling the file with both options
