### ISSUE TITLE
Elasticsearch not respecting DYNAMIC_CONTENT_PATH

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14880]
If you set the `DYNAMIC_CONTENT_PATH` in the dotmarketing-config.properties, it should be respected by anything that uses that property.  Currently, dotCMS ignores that property when creating indexes and sticks them into `./webapps/ROOT/dotsecure` no matter what is set.

`DYNAMIC_CONTENT_PATH=/opt/dotcms/data/dotsecure`
```
[root@authoring5 current]# pwd

/opt/dotcms/wwwroot/current
[root@authoring5 current]# ls -la ./dotserver/tomcat-8.5.24/webapps/ROOT/dotsecure/
total 0
drwxr-x--- 3 root root  20 Jul 18 17:35 .
drwxr-xr-x 8 root root 115 Jul 18 17:35 ..
drwxr-x--- 3 root root  19 Jul 18 17:35 esdata

[root@authoring5 current]# ls -la /opt/dotcms/data/dotsecure/
total 0
drwxr-x--- 4 dotcms dotcms 37 Jul 18 17:35 .
drwxr-xr-x 6 dotcms dotcms 62 Jun 19 12:42 ..
drwxr-x--- 2 root   root   46 Jul 18 17:39 license
drwxr-x--- 3 root   root   21 Jul 18 17:35 velocity
```

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/14895

**Comment by bryanboza** [comment]
Fixed tested on master // postgres

**Comment by DeanGonzalez** [comment]
Already documented here: https://dotcms.com/docs/latest/dynamic-content-path
