### ISSUE TITLE
Allow URLMaps to work without preprocess.vl

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14882]
In the 4.x series, we auto-included the `preprocess.vl` file on the top of every template.  This file is what what populates urlmaps
In 5, we do not auto include the preprocess.vl, we say we expect it to be included manually in the templates.

Our starter site code, both 4 and 5, includes the preprocess.vl file in the top of every template (which means that in 4.x, it was run twice) but it this is why urlmaps work on starter and not on some sites. 
if you add the `parse('preprocess.vl')` to the top of a template on auth, then URLMaps will work as expected.

We should remove the dependance of URLMaps on the preprocess.vl and handle them in code, where they will be more performant, cleaner, testable, etc.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14883

**Comment by bryanboza** [comment]
Fixed
