### ISSUE TITLE
Wrong CamelCase creating content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14881]
We have an error converting the content type name to set the VarName if you use a specific format. 

If you are adding a new content type and use this format or combination (AA#) we ignore all the characters after the number and set the VarNames with spaces or special characters 

Here the video of how to reproduce: https://screencast.com/t/JWnVOEFGqS2E

**FYI: We have the same problem on previous versions**

This is causing errors trying to get content from this content type. 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new ContentType with this name (MP3 ., test)
3. Make sure you have the correct CamelCase in the varName variable 

## Your Environment
Tested on master // Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16162

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
