### ISSUE TITLE
Need refresh the page in edit mode after edit some content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14892]
As a user, I want to be able to see my changes immediately after editing a piece of content added to my page. 

## Expected Behavior
We need to refresh the page in order to display the changes 

## Current Behavior
After you have a piece of content into a page and from edit mode try to edit this content. After you save the changes you are unable to see this in the edit tab, you need change the tab and then bring back. 
SC: https://screencast.com/t/pH5UAJ8u

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new page 
3. Edit this page and add a piece of content
4. Now from edit mode edit the piece of content added to the page and save & publish
5. Make sure after close the edit dialog you are able to see the changes 

## Your Environment
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
Not an issue.
