### ISSUE TITLE
Make Popup Browser bigger

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14893]
The popup/modal is too small when browsing for a file or image to attach to another contentlet, We need it to be bigger:

![screen shot 2018-07-20 at 10 03 59 am](https://user-images.githubusercontent.com/934364/43006716-68bc2522-8c04-11e8-91e1-78148ec3a15c.png)

**Comment by fmontes** [comment]
@alfredo-dotcms please make it 90% width

**Comment by bryanboza** [comment]
Fixed
