### ISSUE TITLE
small save css fix

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14905]
When editing content, users will want to know if the action they press actually saves the content. 
 This change removes the word (saves) and adds a small save icon in its place.
![screen shot 2018-07-23 at 2 56 05 pm](https://user-images.githubusercontent.com/934364/43097004-bcf33028-8e88-11e8-9a05-6081ba2d2e0d.png)

**Comment by dsilvam** [comment]
PR https://github.com/dotCMS/core/pull/14908#pullrequestreview-139871363

**Comment by bryanboza** [comment]
Fixed
