### ISSUE TITLE
Allow api jwt tokens to be issued for longer term

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14914]
We have a config property that is not exposed that sets an upper limit on how long a token can bee issued for.  Because it is not set by defualt, we fall back to 30 days.  We need to ship with a longer default.

`json.web.token.max.allowed.expiration.days`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14915

**Comment by fabrizzio-dotCMS** [comment]
Tested using CURL 
The functionality works as expected. The value in the property file json.web.token.max.allowed.expiration.days is always respected. Changes on the property are picked almost immediately. 
And the default value of 14 days is used when no value is sent or when zero or a negative number is entered.

Even though I think the default value of 3560 days that is intended as the upper valid limit is extremely high. We're talking 2028.

**Comment by bryanboza** [comment]
Fixed tested with the last comment and works as expected
