### ISSUE TITLE
Error when deleting a content type that has a workflow association

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#14917]
It is not possible to delete a content type that is linked to a workflow. This exception is thrown in the log: https://gist.github.com/nollymar/887cd50f46e2cf0d7ab501b121529fbe and nothing is showed up in the UI

## Possible Solution

1. Display a warning message to notify the user that the content type has to be unlinked from the workflow first.
or 
2. Remove the workflow relationship in cascade

## Known Workarounds

The workflow association needs to be removed before deleting the content type

## Steps to Reproduce (for bugs)

1. Log in into the backend
2. Go to the Content Types portlet
3. Try to delete News content type

## Your Environment

* dotCMS version used: 5.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OSx
* Database and version: postgres
* Application module (if apply): Content Types

**Comment by jdotcms** [comment]
We are going to implement the solution #2

**Comment by jdotcms** [comment]
neither me nor Nolly were able to reproduce the issue, however we are going to do some minor fixes for the vanity urls in order to be less noisy on error when deleting the content from the index.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14934

**Comment by bryanboza** [comment]
Unable to reproduce the original issue, after the improvements here, now I'm able to delete the content type without noise in the log
