### ISSUE TITLE
Update no license image in workflows portlet

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14926]
We need to change the image we use in workflows when there is no license.

### Current image
![No license](https://images.zenhubusercontent.com/570baf67bf93871ccd993571/5320200a-ec00-417e-ad9d-3add19d1f7d1)

**Comment by wezell** [comment]
![workflows_png](https://user-images.githubusercontent.com/934364/43204595-529b4392-8fef-11e8-85a1-4839bf13c516.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14931

**Comment by bryanboza** [comment]
As the other portlets, we need to apply the grayscale filter

**Comment by jgambarios** [comment]
Image changed with a grayscale.

**Comment by bryanboza** [comment]
Fixed
