### ISSUE TITLE
Need remove the sort by step from the content dialog 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14939]
We have an error when you try to reorder the contents by step in the content dialog 

## Expected Behavior
For now, as in the content search portlet, we need to remove the option to order by step 

## Current Behavior
We show the following error in the log and hide all the contentlets 
ST: https://gist.github.com/bryanboza/c5086736c7651fa066188aacaf3f2ae8
<img width="1182" alt="sort" src="https://user-images.githubusercontent.com/2641437/43220671-d7263230-9007-11e8-893d-b55c0fa0a227.png">

**FYI: The problem here is because we have contentlets not assigned and this isn't a step** 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Edit some page 

3. Try to add a piece of content 
4. Select any content type in the content dialog 
5. Try to order by step

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14958

**Comment by jdotcms** [comment]
issue has been found and fix has been sent. Need QA from another developer is needed

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14969

**Comment by bryanboza** [comment]
**Minor**: We need set the same style of the other not sortable columns 
SC: https://screencast.com/t/dSvBTXnU4mIs

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14980

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
