### ISSUE TITLE
'Assets Search and Replace' corrupts File Assets

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#14932]
## Expected Behavior
It should replace the text in the File Assets.

## Current Behavior
Replaces the text in the File Assets but user will get 404 from all File Assets replaced.

## Possible Solution
See hotfix.

## Known Workarounds
Edit the File Asset content, unlock, Save & Publish.

## Steps to Reproduce (for bugs)
1. Upload a .txt file (let's say it's called: MyTextFile.txt) with this text "Lorem ipsum dolor sit amet"
2. Access the file in the Front End using the file name (i.e. https://demo.dotcms.com/MyTextFile.txt), it will show up without any errors.
3. Run the 'Assets Search and Replace' tool: Check both "Generate New Asset Version" and "Automatically Publish New Asset Version". Replace "Lorem ipsum" with "Replaced text".
4. Confirm that it says Assets modified: 1 (or more)
5. Try to hit the same file from the Front End again (i.e. https://demo.dotcms.com/MyTextFile.txt). You will get a 404 error.

## Your Environment

* dotCMS version used: 4.3.3

**Comment by wezell** [comment]
@jtesser  We are going to remove this functionality from the codebase

**Comment by jdotcms** [comment]
needs doc, since the search and replace is gone from the tool tab

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15251
