### ISSUE TITLE
What's changed feature isn't rendering the page correctly 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14941]
When you use the what's changed feature in a page, we have a JS error and we are unable to render the page correctly 

## Expected Behavior
We need to be able to render the page correctly and see the changes without problems 

## Current Behavior
We lost the page styles and have a JS error 
SC: https://screencast.com/t/zQhpPQGjYLu

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Edit some page 
3. Add a piece of content but just save 
4. Go to the preview tab and enable the what's changed 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/628

**Comment by wezell** [comment]
working
