### ISSUE TITLE
Invalid message trying to archive the system workflow 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14948]
We have an invalid message when you try to archive the system workflow, we are showing the unable to delete exceptions and have an error in the log. 

We need a better handle of this case. 

ST: https://gist.github.com/bryanboza/807509fb9ea7a43387f8a7b323eb8b87

## Environment 
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14949

**Comment by bryanboza** [comment]
Fixed, tested and now looks better
