### ISSUE TITLE
Unable to cancel the copy workflow 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14950]
Once you try to copy some workflow, you can't cancel. 

## Expected Behavior
When you try to copy some workflow, we are asking for the name of the new WF, but if you cancel this we need to cancel the copy 

## Current Behavior
Once you cancel the copy we are creating the workflow copy with auto-generated name. 
SC: https://screencast.com/t/W7WMslY2SI

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to Types & Tags --> Workflow
3.  Try to copy any WF
4. Cancel the copy 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14951

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now this is working as expected
