### ISSUE TITLE
Gradle copies src/main/resources to ./bin/system/src-conf

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14961]
Look in our distributions and you will see that the files in `src/main/resources` are getting added to the folder `./bin/system/src-conf`

I think the files used to live there and now do not and should not.  These files should end up in the WEB-INF folder under `dotserver/tomcat-8.xx/webapps/ROOT/WEB-INF/classes`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/14962

**Comment by bryanboza** [comment]
Fixed tested on master and now neither have the system directory under /bin/.

**Comment by wezell** [comment]
@bryanboza with this change, we are unable to deploy plugins in a new build.  Let us revert this change for now.

**Comment by wezell** [comment]
Turns out we need this folder for plugin builds
