### ISSUE TITLE
We lost the page contents after add content in to the same page in other language

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14965]
We lost the related content to the page after you add a piece of content to the page but in others language.  

## Expected Behavior
We need be able to handle the page in multiple languages individually without problems  

## Current Behavior
If you have a page in a default language and this with pieces of content. When you create a version of the page in another language, when you add a piece of content to the page in the new language, we lose the  relations of the default language 
SC: https://screencast.com/t/mZ34i6kI

## Steps to Reproduce (for bugs)
1. Login as admin
2. Add a new page in English 
3. Add some pieces of content 
4. Save and Publish 
5. Create the Spanish version of the page 
6. Add a piece of content to the Spanish page
7. Go back to the English version and make sure you can see the content  

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
What happens in 4.3?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14978

**Comment by bryanboza** [comment]
Fixed, now this is working as expected

**Comment by dsolistorres** [comment]
Attached hotfix backport for 4.3.3
[hotfix-GIT-14965_v4.3.3.zip](https://github.com/dotCMS/core/files/2797707/hotfix-GIT-14965_v4.3.3.zip)
