### ISSUE TITLE
Unable to add NEW content in second language

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14966]
From the content search screen:

1. Add a piece of content in english - saved/published a piece of content (english)  
2. stay  on the same dialog, and select “Spanish” on the dropdown at right
3. The system does not ask to fill the info with english info (suspicious)
4.  Enter content in spanish again and click saved/publish. 
5. You get two different content objects (different identifiers)

**Comment by jdotcms** [comment]
I have seen that yesterday.
If you close the edit content windows and click on again on the content to edit and create the new content on another language works, but you have to close and reopen, not sure what is going on.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14973

**Comment by bryanboza** [comment]
Need some work here, now we are able to add the Spanish content, but if you try to come back to the English one, we have an error processing the JSP file, here the log: https://gist.github.com/bryanboza/df1a1928741ee3ae8720f159936cc783

**Comment by freddyucv** [comment]
I found three more errors:

![error_1](https://user-images.githubusercontent.com/10408015/45500663-6aa63b80-b73c-11e8-89f3-070ad24b04a7.gif)
![error_2](https://user-images.githubusercontent.com/10408015/45500682-6f6aef80-b73c-11e8-933d-fd62620cab4e.gif)
![error_3](https://user-images.githubusercontent.com/10408015/45500687-72fe7680-b73c-11e8-8f7b-206bf54bdb8b.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15303

**Comment by bryanboza** [comment]
Tested on the last master and we continue with problems here: 
SC: https://www.screencast.com/t/pZ6tUF7oa

**Case 1:** 
1- Add a new content in English 
2- Now change the language drop down to Spanish 
3- Click in NO, to the populate content dialog 
4- Add a content and save the Spanish version 
**In this case, the EN and SP contents have different identifier** 

**Case 2**
1- Add a new content in English 
2- Now change the language drop down to Spanish 
3- Click in NO, to the populate content dialog 
4- Try to come back to the English content again 
**We need to be able to come back to the English content without problems**

**Comment by wezell** [comment]
The code that needs the fix is `/html/portlet/ext/contentlet/edit_contentlet.jsp` line ~559

**Comment by wezell** [comment]
Only case #2 needs to be fixed

Case 2
1- Add a new content in English
2- Now change the language drop down to Spanish
3- Click in NO, to the populate content dialog
4- Try to come back to the English content again
We need to be able to come back to the English content without problems

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15404

**Comment by jgambarios** [comment]
Please apply the changes requested in https://github.com/dotCMS/core/pull/15404#discussion_r223860267

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15407

**Comment by bryanboza** [comment]
We continue having the same problem here, need some work 
SC: https://screencast.com/t/RtGbE1e3

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15440

**Comment by bryanboza** [comment]
Fixed, tested on master // oracle // FF
