### ISSUE TITLE
"Archive" button should not be visible when creating a new Workflow Scheme

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14979]
When you add a new workflow scheme, the "Edit Scheme" modal displays `Archive`, `Save` and `Cancel` buttons, but the `Archive` button shouldn't be displayed since the scheme doesn't even exist yet.

## Expected Behavior

Only show the buttons and options that are appropriate for a new scheme which hasn't been saved yet.

## Current Behavior

1. The `Archive` button displays when it doesn't make any sense.

![image](https://user-images.githubusercontent.com/13456955/43370365-9a2dbdac-9332-11e8-8e94-ee14b7e6ba7c.png)

2. If you add the Workflow Scheme name and then select "Archive", it creates the scheme, saves it, and archives it, creating a non-visible scheme with no steps in it.

## Possible Solution

Hide the Archive button when the Edit Scheme modal is opened for new schemes.

## Steps to Reproduce (for bugs)

1. Open the Workflows portlet (Types & Tags -> Workflows).
2. Press the `Add Workflow Scheme` button.
3. In the "Edit Scheme" modal, type in a scheme name.
4. Press the `Archive` button.
    * **Result:** A message appears saying the scheme was saved and the view returns to the main Workflows screen.
5. Check the "Show Archived" checkbox.
    * **Result:** The newly created scheme is displayed, showing that the scheme has no steps.

## Context

* This is junk which clutters up the system with no valid use case.
* This will be confusing if a user accidentally moves the mouse slightly and clicks the `Archive` button instead of the `Save` button.
    * The message when clicking the `Archive` button is identical to the one that comes up when clicking the `Save` button, so they may not realize they clicked the wrong button.
    * When they go to look for their new scheme it won't be displayed (since it's archived).

## Your Environment

* dotCMS version used: Nightly master 7/23 (authoring)
* Browser Name and version: Chrome

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by dsilvam** [comment]
Fixed for 5.0.0. Closing
