### ISSUE TITLE
Now property in date time fields isn't working for multi-language content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14975]
As a new feature, we need to support add **(now)** in the date time fields, and this should set the current date, but if you change to add a new content and change the language to a different one, we lost the value in the content dialog

SC: https://screencast.com/t/1zaq6F4qpeHh

## To reproduce 
- Login as admin 
- Create a  new content type 
- Add a date time field and set **now** in the default value field 
- Try to add a new piece of content 
- Change the language of the content that you are adding 

## Environment 
Tested on master // Postgres // FF

**Comment by freddyucv** [comment]
Fix in this branch

https://github.com/dotCMS/core/tree/issue-14975-Now-property-in-date-time-fields-isnt-working-for-multi-language-content

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0 and now this is working as expected

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0 // Postgres // FF
