### ISSUE TITLE
Allow ContentResource to take a WorkflowAction.id

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14985]
Our current ContentResource does an odd thing - it expects a workflow action to be passed in by name.  We need to add the ability to pass in the workflow action by id without breaking the legacy pattern.

**Comment by fabrizzio-dotCMS** [comment]
As far as I can tell these endpoint are only capable to perform a 'hard coded' save or publish.  
```
/api/content/save/1
/api/content/publish/1
/api/content/[Workflow Action Name][/wfActionComments/{COMMENT}][/wfActionAssign/{USER ID}]
```
The operation findAvailableActions is only executed to perform an assignment or to set a comment.
But that's it. 
If let's say we had an operation named  `archive` which happens to be available for the specified content it would never get invoked even if we passed that name in the URL.

An example like (taken from https://dotcms.com/docs/latest/save-content-using-the-rest-api):
`/api/content/Assign for Review/1/wfActionComments/Hey, take a look/wfActionAssign/dotCMS.org.7575
`
Would only take effect if we had an Assignable Commentable  action named `Assign for Review` 
But outside of those two examples, anything else would get invoked.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15009

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15050

**Comment by john-thomas-dotcms** [comment]
Documented: latest/save-content-using-the-rest-api#workflows
