### ISSUE TITLE
A Page - in any language version - can only have 1 template

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14982]
When updating the template for any page, we need to update all language versions to use the same template (exactly as we do for the url)

**Comment by wezell** [comment]
We need to do this work in the db in order to make it performant.

**Comment by nollymar** [comment]
Please consider this info for documentation: 

1. Page assets with different language versions will always share a template 
2. Rolling a page back will not roll back the template selection

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/15023

**Comment by bryanboza** [comment]
Fixed, now when you change the theme in one language this change automatically in all the versions

**Comment by bryanboza** [comment]
We continue having problems with this card. 

After the last changes, now when you change the theme in some version, this change for all the versions, but after change this, if you bring back to the old version of some specific language, this change just for it. Then you have a page with different themes in the different languages. 

Maybe on this case, when you bring back we affect just the content, we need to discard the theme changes. (not sure)
@wezell  

SC: https://screencast.com/t/jM0FTvZaOW

**Comment by wezell** [comment]
This is an acceptable after effect of munging with the template

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/pages-multilingual#changing-templates-layouts-on-multilingual-pages
