### ISSUE TITLE
NPE executing  workflows with publish/expire fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14988]
When you have a content type with date/time fields and use the publish/expire functionality. When you try to do a Save or Save&Publish we have an NPE here and you are unable to execute the workflow

## Expected Behavior
We need be able to execute the WF without problems 

## Current Behavior
We have an error seems that is when you use the never expire 
SC: https://gist.github.com/bryanboza/f5428446ea86affb9a973959887428ac

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content type 
3. Add the date/time field and set as publish and expire
4. Try to save a new piece of content using the never expire 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14989
