### ISSUE TITLE
Add more fields properties to listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14987]
As a User I want to be able to tell if a field is required or indexed from the list of fields.

## Mock
![localhost_8080_dotAdmin_.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/6eeb6741-b279-4d7b-ad66-9432d6fa8bd5)

## Acceptance Criteria

1. Move the variable name next to the title
2. Add the properties below the field name
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
