### ISSUE TITLE
Add more fields properties to listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14986]
As a User I want to be able to tell if a field is required or indexed from the list of fields.

## Mock
![localhost_8080_dotAdmin_.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/6eeb6741-b279-4d7b-ad66-9432d6fa8bd5)

**Comment by wezell** [comment]
don't lose the variable name

**Comment by wezell** [comment]
Oh, I see, it is in the (xx)

**Comment by fmontes** [comment]
Dupe
