### ISSUE TITLE
Unexpected system error trying to create a multi-language version if you don't have permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14990]
We have an unexpected error when you are as a limited user, just have permissions to view the content and you try to create a new version of the content in a different language 

## Expected Behavior
We need to capture the error and show a type of message that you don't have permissions to do this action 

## Current Behavior
We have an error and breaks the system 
SC: https://screencast.com/t/3TmPj4zB

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content type, set View permissions to Chris Publisher 
3. Add a text field 
4. Crete a piece of content on this content type 
5. Login as Chris Publisher 
6. Open the created content and try to create the Spanish version of this piece of content 

## Your Environment
Tested on mater // Postgres // FF

**Comment by fmontes** [comment]
Should we disable the lang dropdown?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15220

**Comment by bryanboza** [comment]
We have a JSP error trying to lock the content for editing with the limited user 
Error: https://gist.github.com/bryanboza/ff624b878757efd099a3f8f1fbd3e5e2

**Comment by bryanboza** [comment]
We still having the JSP error SC: https://gist.github.com/bryanboza/e23a081662111d0546a2f442412a9da3

**To reproduce:** 
- Add a new content type 
- Edit the content type permissions, remove all the permissions and add edit permissions just to Chris Published 
- As admin add a new piece of content
- Login as Chris Publisher and edit this piece of content, try to lock

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master
