### ISSUE TITLE
The "Who Can Send to this Environment" field is broken in multiple ways

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#14992]
The "Who Can Send to This Environment" field in the Push Config "Edit Environment" modal does not allow selection of all users/Roles by browsing the list, and causes users/Roles to be added automatically and unintentionally when you type into the field to search for a user/Role.

## Expected Behavior

* Administrators should be able to add any user or Role to the Environment by browsing through the list.
* You should be able to find any Role by typing.
* Roles should not be added unintentionally when users perform normal actions (like typing to search).

## Current Behavior

1. When you page on the second page only have the entries are new; the other half are ones that were also shown on the first page.  So it only half-pages.
2. When paging through the list by selecting "More Choices" at the bottom, it only shows 2 pages of results. After that the pages are empty.  So, combined with issue 1, this means you only can see 1 and 1/2 pages of users/Roles (so browsing this list is pretty much broken on any system with a normal number of users and Roles).
3. When you type into the box to find a user/Role, it automatically adds the first user to match what you've typed, for **each key** you type.
    * For example, if on the starter site you type "Joh" to find the "John Doe" user, all of the following users will also be added to the list automatically, just from your typing (without you ever selecting any of these users from the drop-down):
        * "Jane Reviewer" (since that's the first user that matches "J")
        * "Joe Contributor" (since that's the first user that matches "Jo")
        * "John Doe" (which at least is what we're looking for - but it was still added automatically without actually selecting it).
4. The "CMS Administrator" Role (and a number of other Roles, though I can't figure out which ones/why) are not displayed in the browsing list and can not be found by typing into the text portion of the field.

## Known Workarounds

For each issue, by number:
1. Type to find the user/Role name.
2. Type to find the user/Role name.
3. Delete the users/Roles which were incorrectly added (you have to do this after every time you type).
4. None that I know of.

## Steps to Reproduce (for bugs)

1. On the starter site, open the System -> Users tool.
2. Add 50 users with names like "Aa", "Ao", "Ba", "Bo", etc. to "Yo".
3. Open the System -> Configuration tool.
4. Select the `Publishing Environments` tab.
5. Press the "ADD ENVIRONMENT" button.
6. Open the user/Role drop-down and view the last 11 users/Roles listed.
7. Select `More Choices` to view the second page.
    * **Result:** The 11 users/Roles at the end of the last page are duplicated in the middle of this page.
    * This is issue #1, above.
8. Select `More Choices` again to move to the third page.
    * **Result:** The third (and all subsequent) pages are blank.
    * This is issue #2, above.
9. Click in the text portion of the "Who Can Send to This Environment" field.
10. Type in "Joh" to find the user "John Doe", then click outside the modal without selecting any users/Roles.
    * **Result:** The following users are added:
        * Jj
        * Jo
        * John Doe
11. Use `More Choices` to browse through the list for the "CMS Administrator" Role.
    * **Result:** The role is not displayed in the list where it should be (or at all, really).
12. Type in "CMS" to try and find the Role "CMS Administrator", then click outside the modal without selecting any users/Roles.
    * **Result:**
        * The "CMS" you type is **replaced** with "Cur".
            * This, by itself, is wrong.  If the text doesn't match anything, then simply nothing should be displayed - what you typed should not be changed.
        * The "CMS Administrator" role is never displayed.
        * The "Current User" role is found, even when the text typed is "CMS" (and so the "Current User" role should not still be displayed, since it no longer matches what was typed).
        * The "Current User" role is added (even though it was never selected).

## Context

I literally can't set up an environment properly right now on authoring because of these issues.

More specifically, the combination of these 4 issues causes a few types of problems:

* **Critical Functionality Fails:** I can't find any way to select the "CMS Administrator" role, which is obviously an issue.
* **"Soft" Security Issue:** On a system with normal numbers of users and Roles, it's fairly likely that users who should not have permission to push will accidentally get assigned it.
    * The admin **must** type to be able to find the users/Roles they need to assign (since the browse doesn't work).
    * And the wrong users will be assigned automatically when the admins type like this.
    * And there is no indication that a user was added, so the admins will only see this if they double-check the list afterward (and note that there is very little vertical space in the list of assigned users/Roles, so it's very easy for accidentally assigned user/Roles to not be visible by the time the admin is finished typing).
* **Bad Impression:** The inability to browse past the second page of users/Roles looks bad.
* **Poor Ease of Use:** It's difficult to do the simple operation of assigning users and Roles permission to push to an environment.

## Your Environment

* dotCMS version used: Nightly 7/23 (authoring and starter)
* Browser Name and version: Chrome 67.0.3396.62
* Operating System and version: Win 10 Pro
* Application Server and version: Tomcat (distro)

**Comment by john-thomas-dotcms** [comment]
A couple additional pieces if information:

1. These bugs exist in 4.3.3, but do **not** exist in 4.3.2 or earlier versions.
    * So this is a recent change without much exposure yet to be able to determine how much impact it has on customers.
2. There are two types of Roles that can not be selected here:
    * Any system Roles
    * Any Role which does not have a user assigned.  Note that this is true even if the Role has `Can Grant` `Users` checked, and even if the Role permissions are inherited by some users (with the Role as a sub-role within a Role hierarchy, and users assigned to the higher-level Roles).

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15010

**Comment by bryanboza** [comment]
Fixed, after those improvements now works better
