### ISSUE TITLE
No feedback to user in UI when no permissions to edit field of content type

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#14999]
If a limited user does not have the required permissions (see [here](https://github.com/dotCMS/core/issues/11754#issuecomment-409214348)) to edit a field of a content type, the REST resource is properly returning Forbidden response code (403) but the UI is not doing anything with it, even reflecting the change in the UI, but after leaving the portlet and coming back the change is not there, misleading the user.

**Comment by erickgonzalez** [comment]
Working on this here https://github.com/dotCMS/core/issues/11754

**Comment by dsilvam** [comment]
@bryanboza your first point about permissions for deleting fields was done already in https://github.com/dotCMS/core/issues/11754. Please check

**Comment by bryanboza** [comment]
After test this with the last core-web version, now we show the error in the UI, but the field still disappearing, and you need to reload to see the field again. We need to leave the field in the list. 
SC: https://screencast.com/t/suQdrOOasQ2

**Comment by fmontes** [comment]
DOne

**Comment by bryanboza** [comment]
Fixed. tested on the last release-5.0.1 // Postgres // FF

**Comment by bryanboza** [comment]
Tested on master and we have pending improvements, moved to a the card #15180
