### ISSUE TITLE
dotSecurity exception when you go to Site Browser as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14993]
When you are navigating as a limited user and go to Site Browser portlet, we are having this exception just clicking on the portlet.
 
If you don't have permissions to some folder we need just hide this and not show the exception 
Log: https://gist.github.com/bryanboza/f2c8fa3c48e512d71c2958747b68f14f

**FYI: Unable to reproduce on 4.x**

## To recreate: 
- Login as Chris publisher 
- Go to site browser 
- Check the log 

## Environment 
Tested on master // postgres

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15207
