### ISSUE TITLE
Resize in Image Editor Not setting Fixed Width Properly

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#150]
I was also able to reproduce this on 1.9.5 and in both Firefox and Safari

When editing a file asset image and typing a fixed resize width, when clicking the resize button, the width set is being changed to another number... even after changing again and saving... the final resize number is off on the fixed width.

See screencast:  http://screencast.com/t/ctGdbpJe

**Comment by wezell** [comment]
this has been fixed
