### ISSUE TITLE
Custom field in Widget CT definition is causing problems when adding content for it

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15002]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/96259
Reproducible in dotCMS 4.2.0, and Demo running 4.3.3.

Adding a custom field containing JavaScript code (jQuery) when creating a custom Widget Content Type is causing problems in the back-end. So, when adding this custom Widget to a page, the **Cancel** and **Save / Publish** buttons do not work, and a JS error is printed in the browser's console.

## Expected Behavior
Adding JS code to a custom field should not interfere with the dotCMS internal source code.

## Current Behavior
The **Cancel** and **Save / Publish** buttons do not work with the JS code in the custom field.

## Possible Solution
Find the problem and fix it.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Create a new Content Type of type **Widget**.
2. Add a custom field to the new Widget, and add the following code in it:
```
<script> 
document.addEventListener('DOMContentLoaded', function() { 
console.log('hi'); 
}); 

</script> 
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
```
3. Go to the Site Browser and create a test page (you can use the blank template).
4. Open up the browser's console and try to add the custom Widget that you created in the first step.
5. You'll see the word "hi" in the console, which is expected. Now, click the **Cancel** or the **Save / Publish** button.
6. You'll see the following error in the console:
```
{…}
​javaClassName: "java.lang.NullPointerException"
message: ""
<prototype>: Object { … }
```

## Your Environment
* dotCMS version used: 4.2.0, 4.3.3
* Browser Name and version: Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Management.

**Comment by jtesser** [comment]
The issue here is we use Dojo on the edit content screen. Custom Fields HTML/JS gets rendered in our edit content screen.  When writing a Custom Field you need to use HTML/JS that is compatible with our screen. 

Our recommendation is to use DOJO. You can find examples here https://dotcms.com/docs/latest/custom-field

While we do not restrict JQuery persay you would be responsible when writing the JS to make sure it works on our Edit Content Screen.
