### ISSUE TITLE
Site Search Returning URLMap Patterns as Title instead of Actual Title

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15006]
Tested on latest 5.0 Master

After looking at the Elastic Search Index using Kibana with Nolly, we determined that the index is somehow getting the URL Title confused with the Title of the content.  

The **content itself** is fine as you can see below:

<img width="1936" alt="querytool" src="https://user-images.githubusercontent.com/1569167/43482967-716b34da-94c7-11e8-8ed0-f2d48ac58dd9.png">

But the **Site Search Index confuses the Two**.  Here are the results using the site search query tool:

![dotcmssitesearchquery](https://user-images.githubusercontent.com/1569167/43483071-c55dea92-94c7-11e8-9fee-1706b75d50cc.png)

And here is the Query of the **ES Index directly** using Kibana:

![kibana-esquery](https://user-images.githubusercontent.com/1569167/43483088-d32d3df8-94c7-11e8-86c4-1c599121b28e.png)

This is the way it is supposed to look and **currently works in 4.3.3** on the backend of demo:

![demoessearch](https://user-images.githubusercontent.com/1569167/43487179-1a4934ac-94d3-11e8-9067-1775cbd37216.png)

and here on the front end of **4.3.3 demo**:

![demofrontsearch](https://user-images.githubusercontent.com/1569167/43487210-2fbd8784-94d3-11e8-9e36-593cb690b6dc.png)

**Comment by wezell** [comment]
This might not be an elasticsearch thing, though it might be.  When indexing the a page, regardless if it is urlmapped or a normal page, for the site search we should be reading the titles from the tika parser, which has also changed in 5.x.

**Comment by nollymar** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/629/files

**Comment by erickgonzalez** [comment]
Working as it should, now is shown the Title instead of the URL. Tested on release-5.0.0.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0
