### ISSUE TITLE
Unable to fix html pages conflicts from Integrity checker 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15008]
We have a conflict when you try to fix html pages conflict using the integrity checker 

## Expected Behavior
We need to be able to fix this kind of conflicts without problems 

## Current Behavior
We have a sql error trying to do the update or delete on the table "identifier" and we are unable to fix the conflict 
ST: https://gist.github.com/bryanboza/18e02328ed753896e78d83e7e926ec8f

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Apply the EE license on both servers and configure your push environment 
3. Create a new page in the same path and with the same name in both servers 
4. Run the IC (integrity checker) and try to fix the conflicts on remote 

## Your Environment
Tested on master //

Sender:  Postgres  v9.6 // FF
Receiver:  Postgres v10 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15040

**Comment by bryanboza** [comment]
Fixed, tested on master and now all those cases are working, a new case reported here #15047
