### ISSUE TITLE
Index snapshot is stored locally on master node when using restful api

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#15016]
When creating a [index snapshot](https://dotcms.com/docs/latest/restful-api-to-manage-indexes#Snapshot) using restful api, the snapshot is stored locally on the master node, causing an error if the api call is made to any non-master node.

## Expected Behavior

Creating the snapshot via restful api should be available from any node

## Current Behavior

An error is thrown when calling the api from a non-master node:
`org.elasticsearch.repositories.RepositoryVerificationException: [backup] a file written by master to the store [../dotCMS-4.2.2/dotserver/tomcat-8.0.18/webapps/ROOT/dotsecure/essnapshot/snapshots] cannot be accessed on the node [[xxx-xxx-xxx-xxx-xxxxx][xxxx][temp.dotcms.com][inet[/10.0.0.4:9309]]]. This might indicate that the store [../dotCMS-4.2.2/dotserver/tomcat-8.0.18/webapps/ROOT/dotsecure/essnapshot/snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node`

## Known Workarounds

Point the api call to the master node

## Steps to Reproduce (for bugs)

1. Create a cluster
2. Attempt to create a index snapshot using restful api, point to a non-master node

## Your Environment

* dotCMS version used: 4.2.2, 4.3.2
* Browser Name and version: curl
* Operating System and version: Linux
* Application Server and version: Embedded tomcat
* Java Brand and version: OpenJDK 1.8.0_121
* Database and version: Postgresql

**Comment by jtesser** [comment]
OK so @wezell and @vianneychacon the snapshot module in ES is meant to be shared.  SO the snapshots directory needs to be on a shared volume 
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/modules-snapshots.html
