### ISSUE TITLE
Change Dates in Time Machine is not Clearing Cache to load new Page Content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15014]
Tested on the latest Master version.

Switching dates in the future time machine does not change the page view of the content.

To recreate: Add Time sensitive News content that has a future publish and a future expire date.

Open the Time machine and travel to the news page, choose a date BEFORE the publish date on your content.  Let the page load without your content.

Then choose a future date after which your content should be appearing.  The content does not show up.  To get the page to change at all, you need to close the snapshot, then travel to the future date.  Apparently we made some changes and now we are not clearing the cache when new dates are selected in the time machine.

**Comment by erickgonzalez** [comment]
This is because of the **TTL** property of the page if the property is set to 0 the change of a date works just fine. According to our doc: ```Changes to the Template, Containers, and content on the Page will not be reflected until after this timeout has expired, so if a Page has a large Cache TTL you may see an old version of the Page when displaying it in Live mode or on the dotCMS front-end.``` The reason why when you close the snapshot and open a new future date works, it's because it takes more than 15 sec to go through the whole process. So my thoughts here are that this is not an issue.

**Comment by wezell** [comment]
@erickgonzalez we need the page cache to return a miss if we are in a time machine situation.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15067

**Comment by nollymar** [comment]
Test results: Success
