### ISSUE TITLE
Unable to open pages after change the layout and push publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15012]
We are having problems when you have been pushed a page in multiple languages and change the layout in one of those, and then push publish again 

## Expected Behavior
We need be able to see the page in edit mode without problems 

## Current Behavior
We are unable to edit the page after change the layout and push again 
Log: https://gist.github.com/bryanboza/9d669cb4850ee916e4b845cfd2ee8a5e

FYI: I tested refreshing the browser, reloading the portlet, also force pushing again and I'm unable to edit. 

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Login as admin
3. Create a new page in two or more environments 
4. Push publish this page 
5. Make sure you can open and edit both versions on the receiver side
6. Change the layout just to one of the versions of the page
7. Push it again 
8. On receiver try to open this page 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
Please test again after nolly's changes here #14982

**Comment by bryanboza** [comment]
Fixed with the last changes
