### ISSUE TITLE
Unlock container could display more accurate date

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#15018]
[This logic](https://github.com/dotCMS/core/blob/7f5a06e84b78371f8600e7fd072d9ba657ab8298/dotCMS/src/main/webapp/html/portlet/ext/director/unlock_container.jsp#L59-L72) leaves a big gap between 2 days and 1 year. 

## Expected Behavior
It could display the amount of exact days since unlocked.

## Current Behavior
Displays '2 days ago' in the container if the modified data is between 2 days and 1 year.

## Known Workarounds
None

## Context
Client ticket: https://dotcms.zendesk.com/agent/tickets/96280

## Your Environment

* dotCMS version used: 4.x and master

**Comment by wezell** [comment]
Needs to be changed to use 
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/util/DateUtil.java#L234
