### ISSUE TITLE
Unable to push remove entire sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15013]
We have problems when you try to push/remove an entire site on 5.0, this because the system is trying to delete content that isn't archived 

## Expected Behavior
We need be able to delete sites and their content via push publish 

## Current Behavior
We have this error and the site isn't deleted 
Log: https://gist.github.com/bryanboza/14ce01bb8d3b3d922707ab8ef2cd9368

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Create a copy of demo site
3. Push publish the new site  
4. Now try to push remove this site 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
Pretty sure this is fixed here: #14913

**Comment by bryanboza** [comment]
Able to reproduce after the last changes

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/632

**Comment by erickgonzalez** [comment]
PR for the IT  https://github.com/dotCMS/core/pull/15189

**Comment by nollymar** [comment]
After several tests, it is working as expected.

**Comment by nollymar** [comment]
Tested on release 5.0.2 successfully

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and works fine
