### ISSUE TITLE
Error trying to re-push some file after push remove 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15022]
When you push some folder, then push remove the same one, and after this, you try to push some file into this folder, we have an error and the system never increase the attempts, then we still retrying. 

## Expected Behavior
We need to handle this case and avoid this error, also if we fail we need to increase the number of attempts, and not still retrying more than 3 times 

**FYI: Unable to reproduce on 4.x versions, we just are unable to see the page on the receiver side, but the bundle doesn't fail. And if you force push this works fine, I think is ok don't see the changes on the receiver, but the major problem here is the system continue retrying**  
 
## Current Behavior
We have this the following error on the log, and the system never finishes to retry send this again. 
ST: https://gist.github.com/bryanboza/197e39bb2baf94d30ebcecb664778de5

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Login as admin 
3. Create a new folder with a page on it 
4. Push this page 
5. Push, remove the folder 
6. Crete a new page into the same folder and try to push the page 

## Your Environment
Tested on master //  Postgres // FF

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/15254
https://github.com/dotCMS/enterprise-2.x/pull/636

**Comment by bryanboza** [comment]
Ok after test again, now we are killing the process after 3 attempts, but we need to handle the principal case and avoid the error. 

I think we need to register the remove in the pushed objects cache because if you try to force push, it is working fine. 

The problem is that dotCMS don't send the folder as a dependency because has been already pushed.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15436

**Comment by bryanboza** [comment]
Fixed, tested on master // Postres // FF. Now we are unable to reproduce the error

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
