### ISSUE TITLE
Language drop down isn't working when you enable the whats changed feature 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15024]
We are unable to change the language version of the page when you have the what's changes checkbox enabled. 

## Expected Behavior
We need to be able to change the language when you have enabled this feature. This to avoid confusions because seems the system doesn't respond.

## Current Behavior
When you have enabled this checkbox, and you change the language this isn't refreshing the page 
![gift1](https://user-images.githubusercontent.com/2641437/43551455-4bf15a08-95a4-11e8-96e6-8f8b03a37797.gif)

FYI: Tested on 4.x and this works 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new page and version in different languages 
3. On edit mode enable the what's changed feature 
4. Change the language of the page

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
@fmontes  - What's changed should not be a checkbox -  it is not a state.  It is a one-off view.  I mentioned this in the design phase but was overruled.

**Comment by wezell** [comment]
The fix is that changing any of the other properties / dropdowns or buttons unchecks what's changed.

**Comment by bryanboza** [comment]
We need some work here according to the @wezell comments

**Comment by bryanboza** [comment]
Also, we have a JSP error here when you change the language and the page does not exist in the selected language. 
SC: https://gist.github.com/bryanboza/d5d0e2514f31d8480892234ae8ffca24

To reproduce: 
- Login as admin
- Create a new page just in English
- Go to preview and enable the what's changed
- Change the language to Spanish

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/15263
https://github.com/dotCMS/enterprise-2.x/pull/637

**Comment by bryanboza** [comment]
Fixed tested on master // Postgres // FF
