### ISSUE TITLE
Use the standard workflow dialog for workflow action with PP

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15028]
When we add a workflow action that includes PP, we have somehow included the wrong dialog.  We need to include the standard dialog. This is true on the content listing screen AND the browser.

this is the wrong dialog that comes with a workflow action:
![screen shot 2018-08-02 at 11 00 27 am](https://user-images.githubusercontent.com/934364/43592356-5c778b5a-9643-11e8-87c2-4461b6d79404.png)

This is the right dialog - you get this when you use the default PP action:
![screen shot 2018-08-02 at 11 01 26 am](https://user-images.githubusercontent.com/934364/43592418-810044ee-9643-11e8-8e22-4c881b5e0065.png)

**Comment by wezell** [comment]
Also, before the dialog is opened, we need to call the dojo.destroy methods correctly to make sure there aren't other dialogs sitting around in dojo memory.  Otherwise you get a j/s error of dojo failing and dojo dijit do not render properly:

![screen shot 2018-08-02 at 11 06 22 am](https://user-images.githubusercontent.com/934364/43592686-20a75ed8-9644-11e8-852f-e4235d89bc9e.png)

![screen shot 2018-08-02 at 11 05 44 am](https://user-images.githubusercontent.com/934364/43592651-07a610f0-9644-11e8-8396-c0610d7c57d6.png)

**Comment by wezell** [comment]
1. If comments are disallowed, hide that field
2. we need to add the pp environment when it is selected (remove the add button)
3. intelligent defaults - if only one environment, have it selected, if there is one stored in session, select it.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15049

**Comment by bryanboza** [comment]
We have double scroll when you try to execute a PP action from bulk action window
SC: https://screencast.com/t/L5HHBcs4E6

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15066

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0 and now this works fine
