### ISSUE TITLE
Page properties button in edit page should edit the current language

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15029]
As user I want to be able to edit the page properties of the language I have selected

## Expected Behavior
When user click `+ Properties` in the edit page it should edit the current language

## Current Behavior
Always edit the lang that is loaded the first time or it last save

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Login
2. Open a page (in english)
3. Click in properties, all good
4. Change the page to spanish
5. Click in properties, we're editing the "english" version of this page

## Acceptance Criteria

1. Edit the page lang contentlet we're currently editing
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
I would hold on this as the logic is tricky - you could be editing a content on a page in Spanish where the page does not have a language version in Spanish.  I don't know if the producivity gain merits the additional complexity.

**Comment by bryanboza** [comment]
Fixed, now we are redirecting to the current language properties
