### ISSUE TITLE
Survivability - allow default host to be created even if host content type has issues 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15020]
If in the course of operations, you lose your default host, your system can be rendered inaccessible.  Our fallback was failing because there was already a fallback default host created and the unique key on hostname was throwing up.

To get to a no default host state:
1. Sender and Receiver running starter
2. Sender - add a required field to your host structure and add a value for demo.dotcms.com
3. Sender - create new host - test.dotcms.com and set as default
3. Sender -  edit a piece of content that lives on demo.dotcms.com - say a page title
4. Push the edited page -  this should push all the dependencies as well, including the now NOT default host demo.dotcms.com

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15021

**Comment by nollymar** [comment]
During tests found two potential issues: 
1) when the modified page is pushed to the receiver, the content type is not updated with the new required field. Also, both sites are pushed with their corresponding inode but the new field is not pushed
2) testing another case, I noticed that once the new site is created with the required field, if I set this as default (before adding a value to the required field for demo.dotcms.com), both hosts are set to default. I didn’t find a way rollback this behavior.

**Comment by bryanboza** [comment]
Ok, after test the case, I think now the bundle is pushed without problems, we send all the dependencies and remove the default host, that's ok.

But in this specific case, we are leaving the receiver without default host, and this is not possible to do manually, we always need a default site. I think we need some work here to validate if we don't have a default site, select the only one as default. 
SC: 
<img width="1676" alt="2018-08-16_1334" src="https://user-images.githubusercontent.com/2641437/44230846-917f4b00-a159-11e8-88aa-c7806305c5f1.png">

**Comment by bryanboza** [comment]
Tested again with the last changes of release-5.0.1 and as @nollymar says in his comment, now after you add a new required field to the host structure, we are able to add default sites as you want 
<img width="1432" alt="sites" src="https://user-images.githubusercontent.com/2641437/44377082-865d4f80-a4b8-11e8-8c74-a974b53ff8ea.png">
Also after you have more than one default host we are unable to push anything

**Comment by bryanboza** [comment]
Moved to #15173

**Comment by nollymar** [comment]
Tested again on master and it's working as expected
