### ISSUE TITLE
Make sure theme selector match mock 100%

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15035]
As a developer we need to make sure the styles of the new components we develop match exactly the mocks and works as the UX team expects.

## Mocks
https://projects.invisionapp.com/d/main#/console/14206936/297253502/preview

## What to do
1. We have to modify global styles for the dialog in this case
2. Make sure all the dialog look the same
3. We might have to update the colors variables for this one

## Acceptance Criteria

1. Match the design 100%
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
![screen shot on 2018-08-16 at 07 28 28](https://user-images.githubusercontent.com/751424/44211374-0df83680-a126-11e8-9572-ca16765e9308.png)

--------------------------------

![screen shot on 2018-08-16 at 07 29 18](https://user-images.githubusercontent.com/751424/44211572-84953400-a126-11e8-987f-f216c45a39fe.png)

There is 2 ways I think we can do this:

1. Ovewriting with css the icon
2. Using:

```
<p-header>
    Header content here
</p-header>
```

**Comment by alfredo-dotcms** [comment]
according to Jason Fallas, the dialog design of https://projects.invisionapp.com/d/main#/console/14206936/315111645/preview

should be the design for all dialogs in general

**Comment by fmontes** [comment]
![screen shot on 2018-08-20 at 07 31 04](https://user-images.githubusercontent.com/751424/44343474-40b66d80-a44b-11e8-88b0-e8808aec33d7.png)

**Comment by fmontes** [comment]
![screen shot on 2018-08-20 at 11 44 50](https://user-images.githubusercontent.com/751424/44357190-9ea87c80-a46e-11e8-9273-3c44ae753795.png)

--------------------------------

**Comment by wezell** [comment]
accepted
