### ISSUE TITLE
Change Reindex to Refresh

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15033]
When I click the reindex button here, we need to 1. flush the contents from cache, and 2. then reindex.

![Screen Shot 2018-08-02 at 12.02.11 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/c2f2c585-4b24-4f4d-8309-f745ac15d60f)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15213

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected
