### ISSUE TITLE
PageContextBuilder and VelocityLiveMode Integration tests

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15032]
We need integration tests on the PageContextBuilder and the Velocity Modes to 
1. Insure we are getting the right values in the pageContext
2. Insure we are rendering the correct content based on the parameters coming in.

Testing matrix:
https://docs.google.com/spreadsheets/d/17HzQ2XJ5rFTFG2ZyFypmXC3mtPeKfqhOMbO6A-p_6N8/edit#gid=0

**Comment by wezell** [comment]
My initial stab at the PageContextBuilderTest

https://gist.github.com/wezell/a3b10275957131b3fb1915975829188e_

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15292
