### ISSUE TITLE
If there is a template called "Default Template" on your host when creating a page, use it

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15031]
1. Add a config setting called like `DEFAULT_TEMPLATE_NAME=Default Template`
2. When adding a new page in the system, if there is a template that matches the DEFAULT_TEMPLATE_NAME name on the site where the page is being added, select it by default.  If there are 2 templates that match, select the first one.

**Comment by bryanboza** [comment]
Fixed, now it is working as expected, also this property is case insensitive. 

Note to doc:
By default the property does not exist, we need to add in the dotmarkenting.config.properties file
(property name: DEFAULT_TEMPLATE_NAME )

**Comment by nollymar** [comment]
Working fine on 5.0.2

**Comment by bryanboza** [comment]
Fixed, works on release-5.0.2

**Comment by john-thomas-dotcms** [comment]
This was partially documented, via documentation for the config property.  Now fully documented: https://dotcms.com/docs/latest/adding-a-page#DefaultTemplate
