### ISSUE TITLE
Error adding containers to sites different to the default 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15045]
We have an error trying to add containers to some site different to the default, we have an NPE, and this is causing an error processing the JSP file `[/html/portlet/ext/containers/edit_container.jsp]`

## Expected Behavior
We need to be able to add containers to any site without problems 

## Current Behavior
We have an NPE, this is causing an error in the JSP and in the UI we show an unexpected error 
SC: https://screencast.com/t/BzPjdUjdp

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new site (site1)
3. Create 2 new content types (test1, test2), Everyone just one field Text, both in the new site 
4. Go to containers and try to add a new one 
5. Select Max. Contents=2 and add the 2 new content types
6. Add the variables with the fields of the content types 
7. Try to save it 

## Your Environment
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
@bryanboza remember to include the error in log when possibly! thanks

**Comment by fabrizzio-dotCMS** [comment]
I am not able to reproduce this issue. After several attempts, I am able to add containers with no problem.

**Comment by bryanboza** [comment]
Tested again in the last version of release-5.0.0 and I'm unable to reproduce, something wrong in my local can cause the error. Not a bug
