### ISSUE TITLE
Error re-pushing content after made some changes in the workflow 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15047]
We have an error when you push some content, then you do some changes in the workflow (delete a step) and then try to re-push again

## Expected Behavior
The content handler should reset all the pieces of content that are referenced to this step and the try to push the changes 

## Current Behavior
We have an error by the dependencies and we fail to push the bundle 
ST: https://gist.github.com/bryanboza/95cedd6e16f8b7a00c0fb67a4f1ccc1e

## Possible Solution
Maybe we need to reset the workflow on the contents that are on this step 

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Login as admin
3. Create a new WF with three steps
4. Create a new content type and set to use this workflow 
5. Add two new pieces of content and set both in the second step  
6. Push it
7. Now on sender move both contents to the step3 
8. Try to push again one of those 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/15059
https://github.com/dotCMS/enterprise-2.x/pull/630

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0 and now we are skipping the validation from the PP process,  now works as expected.
