### ISSUE TITLE
JSP error trying to use the what's changed after  change the theme on pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15043]
Error when you have a page and you change anything in the layout tab on edit mode, and then try to use the what's changes feature, this is breaking the UI 

## Expected Behavior
We need be able to continue using this feature normally 

## Current Behavior
We have a JSP error and the page leaves blank
Error: https://gist.github.com/bryanboza/1061b55e96d48e98a3a6d95752b8ddd8

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new page 
3. Add a piece of content 
4. Change the page theme 
5. Try to use the what's changed 
 
## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
This should be retested after nolly's change of 1 layout per template.  Bryan's stack is trying to find a spanish page.

**Comment by bryanboza** [comment]
I tested after the change, with the last master and we have this error. I think maybe we need to take in consideration for 5.0

**Comment by nollymar** [comment]
PR Core https://github.com/dotCMS/core/pull/15060

**Comment by bryanboza** [comment]
Fixed, tested on master  // Postgres // FF
