### ISSUE TITLE
Need indicate the name of the WF in the step column

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15042]
We need indicate the name of the workflow in the step column, this to avoid confusions when the content type is associated to multiple workflows 

## Expected Behavior
We should display the name of the workflow in cases **when the content type have multiple workflows associated**, this to avoid confusions in case of one of the WF have steps with the same name 

## Current Behavior
We can have multiple workflows with the same step name, and this can cause confusions. Like in this case, the content type is associated to 2 WF, and both have the step 2
SC: https://www.screencast.com/t/smHmoUbV

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
We cannot display everything in the show on listing screen.  I think being able to filter is enough.
