### ISSUE TITLE
Need auto hide the mouse over info from content types portlet on Safari and Edge 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15044]
When you are navigating in the new content types portlet and you see the mouse over info of some button, we still having this info once you change the portlet 

## Expected Behavior
As in the other browsers, we need auto hide this after moving the mouse 

## Current Behavior
We still having this info after click in a different button or move to another portlet 
SC: https://screencast.com/t/X3HHm4VQ05

## Your Environment
Tested on master // Safari

**Comment by wezell** [comment]
This might take an upgrade of primeng?

**Comment by fmontes** [comment]
![1651---base_image_4 1424268494](https://user-images.githubusercontent.com/751424/44241628-5e04e680-a182-11e8-8fd6-dab734aa00a0.jpg)

**Comment by bryanboza** [comment]
Fixes, tested on master // Safari
