### ISSUE TITLE
Content Types styling

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15056]
**DON'T DO ANYTHING TO ADD THE ROWS IN COLUMNS YET, THIS ISSUE IS JUST FOR THE LOOK AND FEEL, NO BEHAVIOUR SHOULD BE CHANGED HERE**

We need to make sure that the content types portlet match exactly UX requirements

## Mocks:
1. [Listing](https://projects.invisionapp.com/d/main#/console/14206936/298130096/preview)
2. [Detail](https://projects.invisionapp.com/d/main#/console/14206936/295974731/preview)
    - Check in invision app there is more screens for each state of this.

## To consider:
1. If you have any doubts on how any part should work, please ask Jason Fallas
2. We might need to defined some variables changes in our CSS, please meet with Freddy M to check this

## Acceptance Criteria

1. Match the design 100%
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
<img width="124" alt="screen shot 2018-08-13 at 7 49 12 pm" src="https://user-images.githubusercontent.com/751424/44067276-fb4d12f8-9f31-11e8-8350-ed5542bef68f.png">
Use the `dot-icon` component.

The row height doesn't match the mock (57px)

**Comment by fmontes** [comment]
![screen shot on 2018-08-17 at 11 48 09](https://user-images.githubusercontent.com/751424/44280941-783ad500-a213-11e8-86ce-8ed31c8d5572.png)

---------------------------

**Comment by fmontes** [comment]
![screen shot on 2018-08-21 at 11 53 59](https://user-images.githubusercontent.com/751424/44419911-b8fb5c80-a539-11e8-85ae-bb37b3566eeb.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/45110038-6b1c5200-b0fe-11e8-9a7b-f28bcff6042c.png)

things to be fixed, according: https://projects.invisionapp.com/d/main#/console/14206936/298130096/preview

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/45110747-5fca2600-b100-11e8-938a-d3191fdc3859.png)

things to be fixed, according: https://projects.invisionapp.com/d/main#/console/14206936/295974725/preview

**Comment by dotcmsCodeReview** [comment]
We just added the margin, right?  it should be there.
