### ISSUE TITLE
Folder permissions are not reloading iframe

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#15055]
when you try to change the permissions on a folder we are not refreshing the frame. This is preventing you from seeing the controls.

## Expected Behavior
Clicking permission individually should show the permission controls.

## Current Behavior
You need to reload the iframe to see the controls after you click the "permission individually" button.

## Known Workarounds
Rick click "reload frame"

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15154

**Comment by bryanboza** [comment]
Fixed, now we are reloading the iframe with the corresponding permissions

**Comment by dsilvam** [comment]
All as expected in 5.0.2

**Comment by bryanboza** [comment]
Works fine on 5.0.2 too.
