### ISSUE TITLE
We are not updating the WF step on receiver when you push a content in without WF 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15062]
We have problems updating the step in a piece of content after push, then reset the workflow and push it again 
 
## Expected Behavior
We need to remove the WF step from the receiver side when you push the content without WF 

## Current Behavior
We are not updating and the step leave in the with the old status 

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Create a new piece of content and assign to some WF step
3. Push this piece of content 
4. Now reset the workflow and leave this in [Not Assigned]
5. Push this piece again 
6. Make sure we are updating content in the receiver 

## Your Environment
Tested on master // Postgres // FF

**Comment by bryanboza** [comment]
After test, we have the same behavior, seems we lost some changes here

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/15338
https://github.com/dotCMS/enterprise-2.x/pull/639

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
