### ISSUE TITLE
Can't scroll in permissions tab

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15068]
When the res is low, user can scroll to the "hidden" accordion item

![edit_permission_scroll.gif](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d62abff8-4ba1-436e-94fb-2364ba5b8eda)

## Acceptance Criteria

1. Make sure user can click in the accordion items scrolling to it
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
Normal.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle and MS Edge and now it works as expected
