### ISSUE TITLE
Editing a contentlet resets the content listing page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15064]
If you page 2, 3, 4 pages into the content list and click on a contentlet, and then close the contentlet, the underneath content listing page resets to 0.

![content-paging](https://user-images.githubusercontent.com/934364/43746745-1ebebfe4-99b4-11e8-92cf-f7a0c9130ea6.gif)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master

**Comment by dsilvam** [comment]
@bryanboza let's please test this one on release-5.0.1

**Comment by erickgonzalez** [comment]
I tested on release-5.0.1 and it's working
