### ISSUE TITLE
Stop checking permissions of each content of a type when deleting the type

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15070]
We only need to check the permissions of the type, not every contentlet of that type. 

[This code](https://github.com/dotCMS/core/blob/64da8f20dbf422b9b902144c9f0df33f0e8f4133/dotCMS/src/main/java/com/dotcms/contenttype/business/ContentTypeAPIImpl.java#L80-L94) can go away.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15071

**Comment by nollymar** [comment]
Tests Results: Failed. It was not possible to delete Flickr content type.

Log details: https://gist.github.com/nollymar/478806c00fa3503ac0a4b6be6aea2b9b

**Comment by nollymar** [comment]
New issue registered here: https://github.com/dotCMS/core/issues/15090
