### ISSUE TITLE
Improve Delete ContentType --> ESContentFactoryImpl.delete(List contentlets)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15076]
When deleting content type We are doing huge batch sql calls with 1000 or 1500 clauses in the sql.  We should just loop over the content list, delete the trees and multi-trees inline and every x deletes call a db savepoint in order to keep the progress so far.

https://gist.github.com/wezell/d08f10e52efe2b4274c5528e84b6923a

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15205

**Comment by dsilvam** [comment]
Current contentTypeAPI.delete method does tons of things and all wrapped in transaction, which is a very long one. Let's follow the same strategy used when deleting a host.

**Comment by nollymar** [comment]
**Tests results:** The delete process is working fine, however a notification is never shown, neither via the NotificationAPI or the UI considering that the process takes a while when many contentlets (more than 1000) are involved.

Suggestion: Show a notification just for the delete thread

**Comment by dsilvam** [comment]
Creating new issue out of Nolly's input
