### ISSUE TITLE
We need the license expire advertisement on 5.x series 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15080]
As in the 4.x series, when your license expires soon, we need to show a type of advertisement about it, as a reminder;

## Expected Behavior
We need the same message that we have in 4.x series or integrate that in the new notification window 

1. Only Admins (has CMS_Admin role) get the notification
2. Happens on every login once license is 30 days from expiration

## Current Behavior
We don't have this message, then we don't remind that 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Apply a license that expires in less than 10 days 
3. Logout 
4. Login again and make sure you have the reminder 

## Your Environment
Tested on release-5.0.0 // Postgres // FF

**Comment by wezell** [comment]
Once we are within 30 days of license expiration, we need to pop a modal window (once per day max) to show how many days you have until your license expires.

**Comment by wezell** [comment]
This should push a notification via the notification API to CMS_Admins on the following days before the expiration:

30
15
8
4
2
1

**Comment by wezell** [comment]
@fmontes this one is waiting on our toast impl.  We should add a toast warning when a user logs into the system if the license is going to expire.

**Comment by erickgonzalez** [comment]
PR core: https://github.com/dotCMS/core/pull/16242
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/659

**Comment by nollymar** [comment]
After several tests, I have some suggestions: 
1. The notification should remain open until the user decides to close it
2. Sometimes, the notification doesn't appear or takes from 3 to 20 secs to display. So, I suggest to add logging info that helps to make sure the validation is executed and the notification sent

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF . Now we have a toast notification for this case

**Comment by erickgonzalez** [comment]
Message when license is going to expire:
<img width="1792" alt="Screen Shot 2019-04-03 at 9 55 47 AM" src="https://user-images.githubusercontent.com/5278970/55493922-0921bd80-55f7-11e9-86c6-e747f82c1edd.png">

Message when license already expired:
<img width="1792" alt="Screen Shot 2019-04-18 at 9 56 46 AM" src="https://user-images.githubusercontent.com/5278970/55494083-5b62de80-55f7-11e9-9234-7c6f3c137ff9.png">

**Comment by wezell** [comment]
@john-thomas-dotcms -  needs translation and I would say that we should change "Your dotCMS license already expired" to just "Your dotCMS license has expired"
