### ISSUE TITLE
Fix init servlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15083]
The init servlet was splitting the hostnames properly.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15084

**Comment by erickgonzalez** [comment]
To Test:
1. update your site hostname to be something like `ericktest.com`
2. add a bunch of site aliases on separate lines
3. restart dotcms and let it run for a couple of minutes
4. login to dotcms.com and look at the content > pingbacks and make the content record looks ok

**Comment by bryanboza** [comment]
Fixed, tested with the last comment and everything works normally
