### ISSUE TITLE
Community users are not able to delete content types 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15090]
It is not possible to delete content types when a community license is set. 

Log: https://gist.github.com/nollymar/478806c00fa3503ac0a4b6be6aea2b9b

Root cause: This condition restricts the delete process: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowFactoryImpl.java#L1368

## Your Environment

* dotCMS version used: dotCMS 5.0.0

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15098

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Tested on release-5.0.1 and works as expected
