### ISSUE TITLE
Update FA icons to Material Design in the tools portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15092]
As a stakeholder a I want users to be able to use Material Design icons in the system menu.

## Expected Behavior
Users should be able to add icons names for Material Design icons

## Current Behavior
User can use Font Awesome.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. `System > Roles & Tabs`
2. Select any role and click tab: "Tools"
3. Edit any of the menu items
4. See the icon field

![screen shot on 2018-08-13 at 10 50 31](https://user-images.githubusercontent.com/751424/44046316-55996c38-9ee8-11e8-90e5-a182fe911e95.png)

## Acceptance Criteria

1. Use MD icons in the navigation (but it should support fa too)
2. Update starter site to match the icons to the new design
3. Update the jsp form message from:
    - From: ~You can view the list of available icons at the FontAwesome web site.~
    - To: You can view the list of available icons at the Material Design Icons web site.
4. Update the link in the message
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by fmontes** [comment]
Needs works, needs to support FA icons too.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres
