### ISSUE TITLE
Unable to see the added content to pages in the new edit mode when the server is running on Windows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15097]
We have problems when you use windows server to run your dotCMS instance 

## Expected Behavior
We need be able to start a dotCMS server in any SO without problems. This was deprecated to prod servers, but for testing purpose, we need to support 

## Current Behavior
When you start a dotCMS instance in a windows server, we are unable to see the content of the pages in the new edit mode 

**FYI: Tested with multiple databases and we have the same problem, also tested with the same databases but on Linux environments and works as expected** 

## Steps to Reproduce (for bugs)
1. On a Windows machine start a dotCMS instance 
2. Login as admin 
3. Create a new page 
4. Add a piece of content to the page, and make sure you can see that on the edit mode 

## Your Environment
Tested on release-5.0 and master 
Windows Server 2016

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15103

**Comment by bryanboza** [comment]
Fixed, tested with the last release 5.0.1 // Windows Server 2016 // H2 and now it is working as expected
