### ISSUE TITLE
Unable to add files to new  file asset content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15105]
We have a JSP error in the ```[/html/portlet/ext/contentlet/edit_contentlet.jsp] ``` file when you try to add a new piece of content to a custom file asset content types 

## Current Behavior
We have an unexpected error when you try to add a new piece of content to a custom file asset structure
SC: https://screencast.com/t/nCm1PICLtY7
Log:  https://gist.github.com/bryanboza/92d4970df07adc393d9df8cf6f8c9055

**FYI: Unable to reproduce on release-5.0.0**

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types and create a new one type FIle
3. Go to content search portlet and try to create a new piece of content 

## Your Environment
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15112

**Comment by bryanboza** [comment]
Tested on release-5.0.1 and works fine
