### ISSUE TITLE
Parse of Login Static Files broken

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15111]
In previous versions we have supported parsing files on the server using the following call to a static html file:

```  
#parse('/static/user_account/reset_password.html')  
```  
http://demo.dotcms.com/application/login/forgot_password.html

In 5.0 it looks like this static file was removed and the starter site login/reset password functionality is broken:

<img width="1390" alt="screen shot 2018-08-14 at 4 27 33 pm" src="https://user-images.githubusercontent.com/1569167/44121961-011cfb00-9fdf-11e8-90a5-bd3ec88d89dd.png">

Screencast: https://www.screencast.com/t/NhrsVUKstVQ

**Comment by wezell** [comment]
This needs to be removed from the starter.

**Comment by erickgonzalez** [comment]
Nothing to do here, since those files are already removed.
