### ISSUE TITLE
Make edit contentlet dialog bigger and better

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15116]
As a User I want to use as much space as possible to edit contentlets

## Expected Behavior
Take as much room as possible in the edit contentlet dialog

## Current Behavior
Contentlet editor dialog have a max with of 1200px

## Possible Solution
N/A

## Acceptance Criteria

1. Make contentlet editor dialog as wider as possible
2. Center the forms (edit contentlet and advanced properties)
3. Add fullscreen button to WYSIWYG field
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master and looks fine
