### ISSUE TITLE
Upgrade EE link in the metadata field should open in a new browser tab

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15119]
The link to upgrade to EE link that appears in the metadata field when you are in a community version should redirect to a new tab and now open in the content dialog 
 
## Expected Behavior
We need open this link in a new window or tab, and not load in the same content dialog 
SC: https://screencast.com/t/zOFxgPk6nu

## Current Behavior
We are loading the page in the content dialog 

## Steps to Reproduce (for bugs)
1. Start a community versions 
2. Login as admin 
3. Add a new file asset 
4. Go to the metadata tab
5. Click in the upgrade to EE link 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
know issue
