### ISSUE TITLE
Edit workflow window needs styling help when you change the default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15110]
When you use another language as default the edit workflow window needs some styling help with the buttons 

SC: 
<img width="565" alt="2018-08-14_1610" src="https://user-images.githubusercontent.com/2641437/44121494-7d164380-9fdd-11e8-8877-c01f6cc39915.png">
## Aceptance criteria: 

- [ ] We should keep the same other in all the languages

- [ ] Test in all the supported browsers

Tested on master // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15133

**Comment by bryanboza** [comment]
Fixed, tested on the last release-5.0.1 // Postgres // FF
