### ISSUE TITLE
Unable to add entries on content types with category fields using the SaveDraft sub-action

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15129]
We have problems trying to use the save-draft subaction, this when you have category fields in the content type 

## Expected Behavior
We need to be able to save it without problems 

## Current Behavior

- [x] If the category field is required we are unable to save the draft, this because the system shows an error that the field is mandatory. Seems we are unable to get the categories  

- [x] We have the same case with relationships after you relate the content we get the required field error

**FYI: Works as expected with the save and save & publish actions**
 
## Steps to Reproduce (for bugs)
1. Login as admin
2. Add a new action to the system WF, this on the first step and add the SaveDraft sub action for new contents 
3. Go to content search and try to add a new entry to the blog content type 

## Your Environment
Tested on release-5.0.1 // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15137

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.1 // Postgres // Chrome and now works as expected

**Comment by bryanboza** [comment]
Fixed, tested on master and now this works as expected
