### ISSUE TITLE
Save as Draft workflow action does nothing

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#15126]
The workflow action "Save as Draft" doesn't seem to do anything. 

**Steps to reproduce:**
- edit a piece of content that has a relationship field (blogs on our site)
- relate to a piece of content (author)
- Use a workflow action that has a "Save as Draft"
- Results nothing happens and when you close the content then open it again the relationship did not save

**Comment:**
Since the dialog stays open regardless I'm not sure we even need this action.

**Workaround:**
Use/replace with the "Save Content" action

**Comment by wezell** [comment]
Sanchez, can you get with Jason Smith on this one?  @jdotcms get with @fishsmith

**Comment by jdotcms** [comment]
For sure Will

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/15129
