### ISSUE TITLE
Created collapsed version of the main nav

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15135]
As a user I want to be able to collapse the menu to take advantage of more space in the window.

#### Expanded
![Screen Shot 2018-08-16 at 2.18.18 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/ebc8c9eb-0d12-404a-844e-4034a5280021)

#### Collapsed
![Screen Shot 2018-08-16 at 2.18.54 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/f173bf28-e21c-46dd-8d70-c276378374b2)

#### Interaction
https://projects.invisionapp.com/share/T9I5RWESGYP#/screens/314900360

## Acceptance Criteria

1. Match the design
2. When the user collapse the menu it should set the active color to the icon
3. When user expand the menu it should also expand the active section and mark the active item
4. When the menu is collapsed and the user click in a non-active icon it should navigate to the first portlet within that section and expand the menu, the section and select the first portlet
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by fmontes** [comment]
1. If you reload the app in edit page the menu doesn't load
2. If you go to a edit page from `Site > Browser > ...` the menu close itself

**Comment by bryanboza** [comment]
After the last changes, if you collapse the menu and reload the page from edit mode, we lost the selection icon and don't show the selected portlet.

**Comment by fmontes** [comment]
That's expected, becase we are "saving" the active section of the menu when you use the menu, edit page have no representation in the menu, it doesn't belong to any section (not site browser) because of that, we don't have any section or active live to mark to.

**Comment by fmontes** [comment]
As per @wezell now `edit-page` will be always open in `Site > Browser`

**Comment by wezell** [comment]
I think this needs work.  I'll say it again, I don't think that if you manually close the nav, the nav should automatically open when you click - or it should open and close again..  Which is why I thought that clicking the icons on the collapsed nav should take you to the top portlet of that section.

![nav-wonky](https://user-images.githubusercontent.com/934364/45428130-8fcc7880-b66e-11e8-86d7-b6e073c39e68.gif)

**Comment by hmoreras** [comment]
- Left menu items do not get updated after doing `login as` so a limited user still have all the menu items that don't have access . https://screencast.com/t/QxxOmj4R1

**Comment by bryanboza** [comment]
Fixed, tested  on master // Postgres // FF
