### ISSUE TITLE
Need a license validation on FE using database engines that requires EE

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15131]
As in previous versions (4.x) we need to apply a license to be able to use the front end of the application using MSSQL and Oracle, and right now we are not validating this.

## Expected Behavior
We need to lock this functionality when you use these databases 

## Current Behavior
The site is fully usable with that DB engines 

## Your Environment
Tested on release-5.0.1 // MSSQL // FF

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/15155

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are validating the license here, new improvement created on #15160
