### ISSUE TITLE
Select box not filtering in content search

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#15139]
If a content type has a "Select box" field and the value is two words, the content search will not filter by it.

Video: https://www.dropbox.com/s/vdcbw6v1h50ogtp/select-box-not-filtering.mp4?dl=0

## Expected Behavior
That the content would filter by the selected value.

## Current Behavior
Only filters if the selected value has no spaces

## Known Workarounds
make all values single word

## Steps to Reproduce (for bugs)
1. add a select box to a content type
2. add an option ---  Two Word|two word
3. Try to filter content by that select box

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15375

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master

**Comment by bryanboza** [comment]
Fixed, now it is working as expected
