### ISSUE TITLE
dotCMS version 5 - very hard to click on buttons on layout design mode

### ISSUE THREAD

**Issue by hcmuafnvt** [dotCMS/core#15146]
The buttons on layout design mode is very hard to click. Please have a look at the attached file.

<img width="1524" alt="4 - button hard to click" src="https://user-images.githubusercontent.com/9898243/44349163-9714c200-a4c6-11e8-977c-d995622ed376.png">

**Comment by wezell** [comment]
@fmontes the way to reproduce this is to run with your screen magnified
