### ISSUE TITLE
Can't add servlets via OSGi in 5.0.0

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#15145]
It is not possible to add a servlet in 5.0.0 using OSGi in the way that is described in the example plugin com.dotcms.servlet (https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.servlet). The code looks for an ExtHttpService but that service is not available in 5.0.0, or at least not by default. 
 I've compared the bundles and services in dotCMS 4.2.2 to 5.0.0, and the ExtHttpService is missing in 5.0.0. 

## DotCMS 4.2
org.apache.felix.framework 
-- [org.osgi.service.resolver.Resolver]
-- [org.osgi.service.packageadmin.PackageAdmin]
-- [org.osgi.service.startlevel.StartLevel]
-- [org.apache.velocity.tools.view.PrimitiveToolboxManager]
-- [com.dotmarketing.portlets.workflows.business.WorkflowAPIOsgiService]
-- [com.dotmarketing.portlets.rules.conditionlet.ConditionletOSGIService]
-- [com.dotmarketing.portlets.rules.actionlet.RuleActionletOSGIService]
org.easymock 
org.objenesis 
org.apache.felix.bundlerepository 
-- [org.apache.felix.bundlerepository.RepositoryAdmin]
-- [org.osgi.service.repository.Repository]
-- [org.osgi.service.url.URLStreamHandlerService]
org.apache.felix.fileinstall 
-- [org.osgi.service.url.URLStreamHandlerService]
org.apache.felix.gogo.command 
-- [org.apache.felix.gogo.command.Basic]
-- [org.apache.felix.gogo.command.Inspect]
-- [org.apache.felix.gogo.command.Files]
org.apache.felix.gogo.runtime 
-- [org.apache.felix.service.threadio.ThreadIO]
-- [org.apache.felix.service.command.CommandProcessor]
org.apache.felix.gogo.shell 
-- [org.apache.felix.service.command.Converter]
-- [org.apache.felix.gogo.shell.Builtin]
-- [org.apache.felix.gogo.shell.Procedural]
-- [org.apache.felix.gogo.shell.Posix]
-- [org.apache.felix.gogo.shell.Telnet]
-- [org.apache.felix.gogo.shell.Shell]
**org.apache.felix.http.bundle 
-- [javax.servlet.http.HttpServlet]
-- [java.util.EventListener]
-- [javax.servlet.Servlet]
-- [org.osgi.service.http.HttpService, org.apache.felix.http.api.ExtHttpService]**
osgi.cmpn 
osgi.core 

## DotCMS 5.0:
org.apache.felix.framework 
-- [org.osgi.service.resolver.Resolver]
-- [org.osgi.service.packageadmin.PackageAdmin]
-- [org.osgi.service.startlevel.StartLevel]
-- [org.apache.velocity.tools.view.PrimitiveToolboxManager]
-- [com.dotmarketing.portlets.workflows.business.WorkflowAPIOsgiService]
-- [com.dotmarketing.portlets.rules.conditionlet.ConditionletOSGIService]
-- [com.dotmarketing.portlets.rules.actionlet.RuleActionletOSGIService]
com.dotcms.tika 
-- [com.dotcms.tika.TikaServiceBuilder]
jcl.over.slf4j 
org.apache.felix.configadmin 
-- [org.apache.felix.cm.PersistenceManager]
-- [org.osgi.service.cm.ConfigurationAdmin]
org.apache.felix.fileinstall 
-- [org.osgi.service.url.URLStreamHandlerService]
-- [org.osgi.service.cm.ManagedServiceFactory]
-- [org.osgi.service.cm.ConfigurationListener, org.apache.felix.fileinstall.ArtifactListener, org.apache.felix.fileinstall.ArtifactInstaller]
org.apache.felix.http.api 
slf4j.api 
slf4j.simple 4
org.apache.tika.bundle 
-- [org.apache.tika.detect.Detector]
-- [org.apache.tika.parser.Parser]
org.apache.tika.core 

## Possible Solution
The ExtHttpService should be added to the possible services or the plugin should be changed to the correct way to add a servlet.

## Steps to Reproduce (for bugs)
1. Build the com.dotcms.servlet plugin
2. Build the com.dotcms.service plugin (there's a dependency)
3. Deploy the plugins
4. Open /app/helloworld

## Context
We want to update our Advanced Search plugin, so people have an easier way to search for a particular String in content, containers, structures etc. The plugin uses a Servlet to retrieve all the results and we can't add the servlet right now. It would be nice if we knew how it could be added or that the OSGi is 'fixed' so we can add it. On the forum (https://groups.google.com/forum/#!topic/dotcms/QRj-vhu8Ws4) I've added the code that I used; a slightly modified com.dotcms.servlet plugin that can log what is going on and is not dependent on the service plugin.

**Comment by Xander-Steinmann** [comment]
The code that I used to create the list above is the following:
`            for(Bundle bundle: context.getBundles()) {
                Logger.info(this.getClass(), bundle.getSymbolicName() + " " + bundle.getState());
                if(bundle.getRegisteredServices() != null) {
                    for (ServiceReference<?> serviceReference : bundle.getRegisteredServices()) {
                        Logger.info(this, "-- " + serviceReference);
                    }
                }
            }
`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15152

**Comment by bryanboza** [comment]
Fixed, tested with the last version of the plugin seeds using release-5.0.1 and now the example is working as expected
