### ISSUE TITLE
Error trying to add a new content type that ends with ";"

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15147]
We have an error every time that you try to add a new content type and use this character in the name. This because this is breaking the code 

## Expected Behavior
We need to escape this and all the other special characters that can affect the code 

## Current Behavior
We have this error on the log and shows an error in the UI
ST: https://gist.github.com/bryanboza/208f3d7029420e7467785b76048ab712

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to content types 
3. Try to add a new one with this character in the name (;)

## Your Environment
Tested on release-5.0.1 // Postgres // FF

**Comment by nollymar** [comment]
Apparently it was already fixed. Please test again.

**Comment by erickgonzalez** [comment]
Working as it should, no error in the logs and we're stripping out the `;` from the variable.

**Comment by bryanboza** [comment]
Fixed, now we are excluding this character
