### ISSUE TITLE
URL in intranet login page is incorrect

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15156]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/96160
Reproducible in Demo running dotCMS 5.0.0, and 4.3.3

Starting dotCMS 4.1.0, some code changes were implemented and the original behavior of the login feature for secured pages was changed. Specifically, the URL in the browser was not longer in the form of `/dotCMS/login?referrer=/url/to/secured-page` but just `/url/to/secured-page`. This is breaking the custom code for customers that use this feature as the way to obtain the referrer has changed.

## Expected Behavior
The URL in the browser should look like it always has been: `/dotCMS/login?referrer=/url/to/secured-page`.

## Current Behavior
The URL in the browser is `/url/to/secured-page`.

## Possible Solution
Bring back the code that displays the correct URL.

## Known Workarounds
Change the code to redirect to the current URL on the page, which is not feasible for most customers.

## Steps to Reproduce (for bugs)
1. Log into the back-end, and create a new HTML Page.
2. View the page in an incognito window, make sure it displays correctly.
3. Now, go the properties of the page you just created, go to the **Permissions** tab, click the **Permission Individually** button, add the "Intranet" role, check the **View** checkbox, and remove the same checkbox from the **CMS Anonymous** role. This will make the page ask for front-end authentication.
4. Go back to the incognito window, refresh the page, and you will be redirected to the login page. However, the URL in the browser is not `/dotCMS/login?referrer=/the/page/you/created`

## Your Environment
* dotCMS version used: 5.0.0, 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Intranet Login pages.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by oarrietadotcms** [comment]
PR for 4.3.4: https://github.com/dotCMS/core/pull/16204
