### ISSUE TITLE
We lost the bin field value after have a relationship required error 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15157]
If you try to add a new piece of content and you have a required bin field in the content type. If you have an error because the relationship is required, after relating the content, we lost the value of the filed, but in the UI looks like you already have a file selected. 

## Expected Behavior
We need keep value and allow save the piece of content without problems 

## Current Behavior
After relating the content to solve the problem, when you try to save it again,  now we have a new error because the bin field lost the value. 
SC: https://screencast.com/t/uwrgu6E2

## Steps to Reproduce (for bugs) 
1. Login as admin 
2. Create a new content type with a bin field 
3. Create a new relationship with this content type (required)
4. Now try to save a new content without relationship
5. Try to save it
6. After getting the required error, relate the content and try to save it again 

## Your Environment
Tested on release-5.0.1 // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15240

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes

**Comment by dsilvam** [comment]
Passing in 5.0.2

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.0.2
