### ISSUE TITLE
Add new field on content types to support relationships

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15163]

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/issues/14298

**Comment by dsilvam** [comment]
Passed Internal QA: Added a new relationship field to an existing content-type via REST API and used it to create new relationships.

**Comment by bryanboza** [comment]
I'm unable to add the new relationship fields, we have a java.lang.NumberFormatException and you can't create the field.
ST: https://gist.github.com/bryanboza/a407eba6df250fe84388f0e7a854490e

**Comment by dsilvam** [comment]
This is working for us. Please retest @bryanboza
