### ISSUE TITLE
Import/Export content using relationship fields

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15167]
**Export Relationships:** there must be a column with the velocityVarName of the relationship field. It must contain a comma-separated list of related identifiers

**Import Relationships:**
Relationships must be imported using the velocityVarName of the field and related content must be specified as comma-separated values.
Possible values can be: 
* identifiers
* lucene query
* both separated by comma

**Comment by nollymar** [comment]
Implemented as part of https://github.com/dotcms/core/issues/14298

**Comment by dsilvam** [comment]
Passed Internal QA
* **Export**: New relationship field and its value were included in the resulting csv file after exporting a couple of contentlets each with a couple of related contentlets

* **Import**: Contentlets with the new relationship field and its related content were able to be imported by using the file generated above and  removing the identifier column. (Contenlets were be removed prior to restoring/importing)

**Comment by nollymar** [comment]
**Note to QA:** 
* Importing related content using legacy relationships should work as documented here https://dotcms.com/docs/latest/importing-related-content. Please, test self related content as well.

* Importing related content using a comma separated list of lucene queries and/or identifiers should work for both legacy and new relationships.

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now both cases are working as expected
