### ISSUE TITLE
Steps to migrate legacy relationships to the new approach

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15169]
Migrating a legacy relationship to the new relationship field approach requires the execution of a manual process described below: 

1) Edit the Content Type --> Add a new RelationshipField.
For example: if I want to migrate an existing relationship between **News** Content Type and **Media**, then I should add a new relationship field on **News** that points to **Media**
<img width="1437" alt="add_a_new_relationship_field" src="https://user-images.githubusercontent.com/8741395/50457151-80c0bc00-0927-11e9-8d57-727630084fc4.png">

Note: In case the other side of the relationship is required, you should also add a Relationship Field on **Media** that points to the **News**' field we have just created.

2) Find in database the `relation_type` of both, the legacy relationship and the new relationship record created on Step 1

``` 
select * from relationship;
```

<img width="1439" alt="find_relationships" src="https://user-images.githubusercontent.com/8741395/50457176-a4840200-0927-11e9-9a3f-1ea0b80d19db.png">

3) Manually, update in database the existing entries in the `tree` table that point to the legacy relationship

```
update tree set relation_type='News.media' where relation_type='Parent_News-Child_Media'

```

4) Delete from database the legacy relationship record. **Be careful to delete the right relationship record**

```
delete from relationship where relation_type_value='Parent_News-Child_Media'
```

5) Run a full reindex

6) Verify all changes have been applied correctly (all existing related contentlets must be listed on the new relationship field)

**Important note for push publishing environments:**

In order to see these changes on a receiver server, you have to:

1) Push the edited content type(s) and its contentlets
2) Manually delete the legacy relationship from the receiver database. **Be careful to delete the right relationship record**
```
delete from relationship where relation_type_value='Parent_News-Child_Media'
```
3) Run a full reindex

**Comment by bryanboza** [comment]
Need to test upgrades in all the supported databases

**Comment by nollymar** [comment]
These manual steps are not needed anymore. Now, legacy relationships can be easily migrated using a button implemented on this card: https://github.com/dotCMS/core/issues/15752

**Comment by bryanboza** [comment]
After you migrate some legacy relationship to a field, If you open the relationship, edit something and save, this from the relationships tab, we are saving it as a new legacy relationship, this because if you try to edit the relationship, you are able to convert again... and we create a new one every time you save
![2019-01-10_14-59-46 1](https://user-images.githubusercontent.com/2641437/51000405-a4bcf980-14f2-11e9-8b88-4aa029a62dbd.gif)
