### ISSUE TITLE
Define how the relationship field will be displayed in the UI

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15165]
This is the mockup of the new relationship field 

- we need to test a system that has 10 languages defined and show only the first 5 flags/states.  
- on mouse over, we will show all the flags/states

![screen shot 2018-12-11 at 12 09 04 pm](https://user-images.githubusercontent.com/934364/49817270-c4b79c80-fd3d-11e8-8005-90bf5d93e570.png)

**Comment by fmontes** [comment]
FULL MOCK: https://projects.invisionapp.com/share/T9I5RWESGYP#/335950128_Edit_Contentlet_-_Relationships_Field

**Comment by fishsmith** [comment]
![relationship-mockup](https://user-images.githubusercontent.com/1561349/49956670-c74bfa80-fed3-11e8-8e42-930fa2b4412b.png)
![relationship-mockup-2](https://user-images.githubusercontent.com/1561349/49956671-c9ae5480-fed3-11e8-8665-0e18cb2304b0.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15729

**Comment by bryanboza** [comment]
Unable to add the new relationships field, when you add a new relationship field, and you click on save, we are not adding the field and just disable the save button.
SC: https://screencast.com/t/FkK5IG3enc5A

**Comment by alfredo-dotcms** [comment]
@hmoreras the error bryan reported looks to be related with the validation of the form, the `Save` button needs to be disabled until the form is valid (`name` and `content type` fields required)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
