### ISSUE TITLE
Submenu changes when clicking "edit"

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#15162]
When a submenu is rendered on a page and you want to edit the page the submenu changes. In our case the submenu even disappears completely. This can be reproduced on the demo site.

I guess this has to do with the URL that changes from /services/first-time-investors to /api/v1/page/render/services/first-time-investors.

## Expected Behavior
When you click "edit" the menu should display the same items as in "preview"

## Current Behavior
The menu changes to the main menu (on the demo site), and in my case the menu disappears completely because I use $navtool.getNav(1)

## Steps to Reproduce (for bugs)
1. Open demo.dotcms.com
2. Open Site > Browser
3. Open the page Services > First time investors
The menu on the left displays 4 items: First time investors, Retirees etc.
4. Click on "EDIT" (top left), even when it is already selected
The menu on the left now displays the main menu (The same as the header menu). When you click the arrows you can modify the correct 4-item menu.

## Context
Now when we edit a page our entire submenu (and breadcrumb) disappear and/or break, which does not look very professional. Only the main menu remains fine.

## Your Environment
* dotCMS version used: 5.0.0 (same as the current demo site)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15253

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 // FF

**Comment by nollymar** [comment]
Working fine on master. However the reorder functionality is not working. Neither "Save Changes" or "Cancel" buttons are working. Tested with Chrome
