### ISSUE TITLE
Remove double dirty checking

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15177]
In the contentlet editing screen, if you lock the contentlet and edit a text field and then go to unlock the content, you get a javascript confirm  - this needs to go away.

We have an angular dialog that will trigger if you try to close the dirty piece of content.

**Comment by bryanboza** [comment]
Fixed, now we don't have the confirmation dialog

**Comment by bryanboza** [comment]
Tested on release-5.0.2 and works fine
