### ISSUE TITLE
Static push to S3 is broken in 5.0.0

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#15176]
Static push to S3 creates zero length files
## Expected Behavior

Files should be published to the S3 bucket 
## Current Behavior

The files are created but they have no content, all of them are zero length files.
![s3-bucket static push](https://user-images.githubusercontent.com/8353755/44426919-3bd9e280-a54d-11e8-8df6-3ac80ce8d954.png)
## Steps to Reproduce (for bugs)

1. Setup a vanilla dotCMS 5.0.0
2. Install PLATFORM license
3. Create an S3 bucket and an IAM user with full permissions on that bucket
4. Configure this bucket as a dotCMS static push endpoint 
5. Attempt to push any content
6. Check the files in the S3 buckets, the structure and the files are there but they are zero length files

## Your Environment

* dotCMS version used:
* Browser Name and version: Firefox 61.0.2
* Operating System and version: MacOS High Sierra 10.13.6
* Application Server and version: Embedded tomcat
* Java Brand and version: OpenJDK 1.8.171
* Database and version: default embedded H2DB

**Comment by oarrietadotcms** [comment]
Client ticket: https://dotcms.zendesk.com/agent/tickets/96444

**Comment by wezell** [comment]
@oarrietadotcms @vianneychacon this is almost a non-issue.  What is happening is that no language-id is specified in the endpoint config and the english page versions get written with content and then are overwritten by the 0 length spanish page versions.  The "fix" is to use one of the language variables in your bucket name or bucket prefix to separate out the english from the spanish sites.  From an R&D perspective, we can check to see if there is any language set and if not and the site has multiple languages, only publish the default language.

**Comment by wezell** [comment]
Make sure to check like this pseudo code 
(`aws_bucket_folder_prefix` or `aws_bucket_name`) contains ( `{languageIso}` or `{languageId}` or `{languageCountry}`)

**Comment by jtesser** [comment]
FWIW we saw this config working in 4.x 
aws keys/secret
aws_bucket_name=aws-s3-xxxxxx
aws_bucket_folder_prefix=sandbox-{hostname}-{hostId}
aws_bucket_region=us-east-1

**Comment by dotcmsCodeReview** [comment]
Did they have multiple langauges in their installation?

**Comment by jtesser** [comment]
Looking at some things and asking what is happening on AWS side.  Give me a bit to get some answers

**Comment by hcmuafnvt** [comment]
@wezell and @jtesser 
My config works well on dotCMS 4.x but don't work on version 5. When push to Aws s3, all static files are pushed correctly but only html files are empty content (zero byte).

**Comment by wezell** [comment]
@hcmuafnvt we are looking into it as I type.  As a work around right now, you could add the {languageId} variable to your bucket name, e.g.
`aws_bucket_name=aws-s3-{languageId}-xxxxxx`

**Comment by bryanboza** [comment]
Fixed, tested in the last release-5.0.2 code and now we are sending the page in all the language versions, also his contents. But we have a new issue here: #15310. 

Waiting for this fix.

**Comment by bryanboza** [comment]
**Note to doc:** Maybe we need to add in the documentation as a best practice always try to use the "{hostname}-{languageIso}" parameters in order to configure the environment. @john-thomas-dotcms
