### ISSUE TITLE
Bring columns back to edit content and content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15179]
As a user I want to be able to add columns to my content types forms

## Expected Behavior
Be able to create row and columns of fields in content types and the create contentlets with the form organized in rows and columns

## Current Behavior
No rows and columns actions.

## Possible Solution
Some code is commented for 5.0.

## Acceptance Criteria

1. Match the design
2. Be able to drag and drop rows
3. Be able to drag and drop fields between columns
4. In the edit contentlet form see the form organize in rows and colums as it was designed in the content tpes
5. Multilanguage
6. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15190

**Comment by hmoreras** [comment]
![image](https://user-images.githubusercontent.com/31667212/45047059-37c1c080-b035-11e8-91a1-4c8c17a382d2.png)

row deleted icon and field icons are overlapped

**Comment by hmoreras** [comment]
delete button don't go away after drag & drop https://screencast.com/t/ApjbuFbTNd

**Comment by fmontes** [comment]
@wezell we need to come up with a solution for the tabs inside columns

**Comment by fmontes** [comment]
The approach will be update the "Add row" to a dropdown with:

1. Add row
2. Add tab
3. Add line divider

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15379

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
