### ISSUE TITLE
content types tweaks

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15178]
The content types are looking great @hmoreras and I know we are not done with them but these are my initial impressions.  Keep up the good work!

### 1. Indent second line of field information  (see image below)
![Screen Shot 2018-08-21 at 9.11.28 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/09a66d01-050a-461e-814f-b6ffccae1976)

### 3. Tabs needs to look the same in content types and edit page
<img width="640" alt="screen shot 2018-08-22 at 10 58 07 am" src="https://user-images.githubusercontent.com/751424/44478238-4c946200-a5fa-11e8-9e83-41c7329f5290.png">

### 4. Content type "card" look missing background shadow
![screen shot 2018-08-21 at 9 25 09 pm](https://user-images.githubusercontent.com/934364/44437579-cf7cd480-a588-11e8-8b74-f6fcfe20142f.png)

### 5. make content type variable more prominent and cut and pasteable in listing/editing.  (something like but not exactly this)
![screen shot 2018-08-21 at 9 26 36 pm](https://user-images.githubusercontent.com/934364/44437693-56ca4800-a589-11e8-92cd-42ea87a5ff10.png)

**Comment by fmontes** [comment]
![screen shot on 2018-08-23 at 09 27 21](https://user-images.githubusercontent.com/751424/44535245-cc800200-a6b6-11e8-9d01-237c71ab1f89.png)

**Comment by fmontes** [comment]
Delete content type button is missing. (reported by @bryanboza )

**Comment by fmontes** [comment]
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/751424/44282150-56dbe800-a217-11e8-84b5-340159e8cace.png" data-skip-pjax=""><img src="https://user-images.githubusercontent.com/751424/44282150-56dbe800-a217-11e8-84b5-340159e8cace.png" alt="screen shot on 2018-08-17 at 12 14 43" style="max-width:100%;"></a>

**Comment by fmontes** [comment]
![screen shot on 2018-08-27 at 16 35 17](https://user-images.githubusercontent.com/751424/44690238-51508000-aa17-11e8-92d7-ef471a82a91b.png)

**Comment by fmontes** [comment]
![screen shot on 2018-08-27 at 16 37 05](https://user-images.githubusercontent.com/751424/44690299-88bf2c80-aa17-11e8-9c85-601ca8a26537.png)

**Comment by fmontes** [comment]
<img width="1509" alt="screen shot on 2018-08-31 at 10_37_46" src="https://user-images.githubusercontent.com/751424/44924920-05008b00-ad0a-11e8-8059-7fc296610e0c.png">

**Comment by bryanboza** [comment]
We need a bigger icons for the edit and remove buttons, right now those are too small 
SC: https://screencast.com/t/VL5yf8lw

**Comment by fmontes** [comment]
That's the size of the UX mock: https://projects.invisionapp.com/d/#/console/14206936/295974727/preview 12px.

**Comment by bryanboza** [comment]
@wezell what do you think here?

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now we have all those improvements
