### ISSUE TITLE
Categories portlet enhancements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15174]
We have multiple problems with this portlet, we need some work here: 

- [ ] Need add full support to special characters. Rigth now we are removing it to set the key and variable values
<img width="1691" alt="test1" src="https://user-images.githubusercontent.com/2641437/44370614-3bcbdb00-a498-11e8-95e0-ae160add7dd8.png">
I think we need to have the normal behavior like in the single tags.

- [ ] Also we have problems on this portlet with the double byte characters, we allow add this kind of categories, but set a weird value to key and variable
<img width="1678" alt="test2" src="https://user-images.githubusercontent.com/2641437/44370739-bdbc0400-a498-11e8-98d4-eb31233172f5.png">
 
Both cases can cause problems trying to get categories doing queries 

### Import // Export 
- [ ] We have this error trying to export categories with this characters:
ST: https://gist.github.com/bryanboza/9306b06786ebf66f57f60689fc097ee9

- [ ] The import categories aren't respecting the replace//add option, also we import when you select the file. We need to wait for you click the import button to start the transaction, right now when you click on the import button seems this isn't doing anything

**Comment by dsilvam** [comment]
@bryanboza after reviewing with @wezell, we are not working on cases 1 and 2. We do our best effort to generate the keys for and vars for the user based on the input name, but they can always edit them.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15182

**Comment by nollymar** [comment]
Tests results: Success.
Tests included:
- Adding/Deleting categories and subcategories with non latin characters
- Importing/Exporting categories and subcategories with non latin characters

**Comment by nollymar** [comment]
Working fine on 5.0.2

**Comment by bryanboza** [comment]
Fixed, now we are able to import/export categories with this characters without problems
