### ISSUE TITLE
Content type without categories after push publish

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15172]
We don't have much details but after a push publish process (related to this thicket https://github.com/dotCMS/core/issues/15124 ) we have in the receiver server a Content Type without categories.

We need to try to reproduce the issue and make sure the categories are always sent as part of the Content Type.

**Note:** We have two ways to fire a Push Publish process, using the regular action and with workflows, we need to make sure to test both ways, both ways should be using the same endpoint but we need to make sure both are sending the proper information.

1. Create new top level cat with some children
2. Create a new content type that has a category field that uses this category
3. push it, and make sure if receiver is has it.

**Comment by fabrizzio-dotCMS** [comment]
I haven't been able to reproduce this error. 
I tried a number of scenarios involving categories and they're always synchronized accurately on the target server.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15325

**Comment by bryanboza** [comment]
Fixed, now it is working better and we are pushing the categories by dependency

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 // Postgres // FF and now it is working as expected.
