### ISSUE TITLE
JSP error trying to display all the assigned contents in the task portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15186]
When you try to see all the assigned content on this portlet we have an error on this JSP file `[/html/portlet/ext/workflows/view_tasks_list.jsp] at line [183]` and you are unable to see the list of tasks 

## Expected Behavior
We need to be able to use the filter without problems 

## Current Behavior
We show a blank list and show this JSP error on logs 
Here the complete ST: https://gist.github.com/bryanboza/ee85bb03124898cf97b701fd79aeff52

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to the Tasks portlet 
3. Using the filter try to see the task assigned to All 

## Your Environment
tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15241

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and now it is working
