### ISSUE TITLE
Action window pops if Push Publishing workflow action is above other actions in browser

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15184]
Only happens in the Browser
### To reproduce
1. Have a PP environment faked up
2. On system workflow > published, add a Push Publishing Action with the push publishing actionlet
3. Put the PP action at the top of the action list
4. Go to the Browser and publish a file.  then try to unpublish it, you will get the action window popped up.

### Workaround
Move your PP action to the bottom of the list.

![pp-popup](https://user-images.githubusercontent.com/934364/44529256-a27c0f00-a6b9-11e8-803d-d8634d9ce832.gif)

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes

**Comment by dsilvam** [comment]
Unable to reproduce in 5.0.2. Passing QA
