### ISSUE TITLE
Index or cache improperly updated when attempt to save content without Required field value

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#15199]
If you attempt to update a content item without filling in a Required field for that content, any changes you have made to other fields in the content look as though they have been saved, until the content is re-indexed.  After a re-index the content display is reverted to show that no changes were made.

## Expected Behavior

The values displayed for a content should not be changed if the content is not actually modified.

## Current Behavior

If a required field of a content item has not been filled in, and you save the content item, a modal pops up telling you that the field is required, but all other changes you've made to the content are displayed as if they were actually saved.  However if you re-index the content (or make another change to the content type which forces the content to be reindexed - such as deleting the Required field), the content display reverts to what it was before the (failed) attempt to update the content.

## Known Workarounds

Force a re-index of the content after the failed save of the content.

## Steps to Reproduce (for bugs)

1. Open the front-end of the demo site or dotCMS starter site.
2. Select `News & Events` -> `News`, and note which News item is first in the list.
3. Open the `Content Types` tool in the back-end.
4. Edit the 'News' Content Type.
5. Add a new Text field named 'Test', and check the `Required` box.
6. Save the Content Type.
7. Open the `Content Search` screen.
8. Find and edit the News content that showed first in the News list on the front-end (from step 2).
9. Change the Title of the News content to add `XYZ` to the end of the Title.
    * _Note:_ Do **_not_** enter any value for the 'Test' field.
10. Save/Publish the content.
    * _Result:_ (Correct) A modal window pops up telling you that the 'Test' field is required.
11. Close the content editing window, and look at the content in the `Content Search` screen.
    * **Result:** (Incorrect) The title of the News item you attempted to save shows the title with 'XYZ' added to the end.
12. Open the front end, return to the home page, and then select `News & Events` -> `News` again.
    * **Result:** (Incorrect) The title of the News item you attempted to save shows the title with `XYZ` added to the end.
13. Open the `Content Types` tool.
14. Open the 'News' Content Type.
15. Delete the 'Test' field.
16. Return to the `Content Search` screen and look at the content item you saved in step 8.
    * **Result:** (Correct) The title of the content has reverted so the 'XYZ' no longer shows in the content title.

## Context

This allows content editors to ignore Required fields when making changes to content, because the change to the title actually shows up on the front end, even though the save failed.

## Your Environment

* dotCMS version used: 5.0.1
* Browser Name and version: Chrome 68.0.3440.75
* Operating System and version: Win 10 Pro
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8.0_162
* Database and version: Postgres (demo), H2 (training)

**Comment by john-thomas-dotcms** [comment]
See related: https://github.com/dotCMS/core/issues/14652

**Comment by john-thomas-dotcms** [comment]
Note that this appears to be a cache issue, not an indexing issue, since the problem can be resolved by clearing the cache.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15215

**Comment by dsilvam** [comment]
Passed QA in 5.0.2: Content is not left dirty after changing field values and failing to save because of missing required field value.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce with the last changes

**Comment by nollymar** [comment]
Failing on this case: 
1. Edit a news and set a value for the new field, save/publish, close the popup
2. Edit the same news and now leave the new field empty and save. No error is shown even when the field is required. (wrong behavior)
3. Close the popup and try to edit the same contentlet. The old value set for the required field is shown. So, it seems that the contentlet was not saved on step 2 and the validation was not shown either.
