### ISSUE TITLE
Implement the new experience to "Add Rows" in content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15194]
As a User I want to be able to add rows to content types easily.

## Expected Behavior
Add rows with clicks and no drag and drop.

## Current Behavior
You can only add rows by drag and drop.

## Possible Solution
N/A

## Mocks
https://projects.invisionapp.com/d/#/console/14206936/295974726/preview (more in the project)

## Add row component:
`/src/app/portlets/content-types/fields/content-type-fields-add-row`

## Acceptance Criteria

1. User should be able to add rows from 
    - Add row button on the top right
    - Add row button in the empty row at the very end of all the rows
2. Users should be able to select how many rows to add by:
    - Click
    - Left and right + enter in the keyboard
3. If there are many rows and the row selection in below the fold when the user click the top add row button we need to scroll into row selection, see the interaction [here](https://projects.invisionapp.com/d/#/console/14206936/297882253/preview)
3. Remove the ability to drag and drop rows from the right sidebar (remove all code related also)
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15224

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
