### ISSUE TITLE
Workflow Rest is losing form on existing contentlet

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#15192]
when you call an action with an existing contentlet, the form is being lost

1) create a contenttype with two text fields
2) call the save and publish from the new steps in the system workflow
```
http://localhost:8080/api/v1/workflow/actions/b9d89c80-3d88-4311-8365-187323c96436/fire
{ 
	"contentletFormData" : {
  		"stInode" : "a666dece-d010-4e3d-b8f2-02e0e750b337",
  		"title" : "test5",
		 "name": "test5"
	}
}
```
3) then call the same but include the inode previously created and the save publish from the publish step
```
http://localhost:8080/api/v1/workflow/actions/ceca71a0de/fire?inode=55ff2c2e-82d0-4765-ba33-a66b384f2397
{ 
	"contentletFormData" : {
  		"stInode" : "a666dece-d010-4e3d-b8f2-02e0e750b337",
  		"title" : "test_x_3",
		 "name": "test612"
	}
}
```

The changes are being missed

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15322

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15324

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now I'm unable to reproduce

**Comment by jgambarios** [comment]
Integration test will be created in https://github.com/dotCMS/core/issues/15326

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
