### ISSUE TITLE
Clear up dialog title in add contentlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15198]
As a user I want to know correctly which contentlet I'm about to edit

## Expected Behavior
When user open a dialog to edit a content the dialog title should show blank until the title is loaded

## Current Behavior
Is showing the previous contentlet title

## Possible Solution
Is the `header` attr [here](https://github.com/dotCMS/core/issues/15198#issue-353811399)

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Go to Content > Search
2. Click ... > add content
3. Close the dialog
4. Try to create another content but a different type

## Acceptance Criteria

1. When user open the dialog to create a content it should always show blank until right dialog title loads.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on release 5.0.2 and works as expected
