### ISSUE TITLE
Allow Detail Pages in Community

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15195]
We are blocking the query that is required for detail pages to be auto-completed.

**Comment by dsilvam** [comment]
PR core: #15196 
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/634

**Comment by erickgonzalez** [comment]
We have an issue showing the value with Community License https://github.com/dotCMS/core/issues/15217

**Comment by bryanboza** [comment]
Fixed, now we have the auto-complete and you are able to save the detail and works, but we have the problem when you are in the community edition and edit the content type, we are not showing this value. This was already reported on #15217

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/638 and https://github.com/dotCMS/core/pull/15306

**Comment by erickgonzalez** [comment]
Tested on 5.0.2 working as it should.

**Comment by bryanboza** [comment]
Fixed, after the fix #15217 now this is working as should
