### ISSUE TITLE
DIY endpoints

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15206]
See https://docs.google.com/document/d/1PjvNCqk_A6Ir9A2ejHVzCbXKeEmS7Rrkcr_CZ7gSCeE/edit#

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15239

**Comment by DeanGonzalez** [comment]
https://auth5.dotcms.com/docs/latest/scripted-endpoints
