### ISSUE TITLE
Need support the push publish of archived content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15201]
Related to #12793 

We need to support the single push of archived pieces of content, this in order to allow the user to update the status of any content. Right now when you have an archived content we are just allowing do a push remove, and this is removing completely the content and all the versions of it. 

## Expected Behavior
In case you have been pushed a piece of content, for example, a page, and this exists in 10 languages, when you push one, we send all the versions, but in case you need to depreciate just one, then you archive it on sender and when you try to push it, we just have the push remove option and this will delete all the other versions 

## Current Behavior
For archived content we can't do a single push, just allow a push remove 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Configure your push environment 
3. Create a new page 
4. Create the version of the page in two more languages 
5. Push it 
6. Now archive on sender the version of one of the languages 
7. Try to push the archived one page again 

## Your Environment
Tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Safari

**Comment by john-thomas-dotcms** [comment]
Doc Note: Need to make sure docs are clear about what happens when you archive content in a single language, and process to do that without removing all language versions.
