### ISSUE TITLE
Widget Preexecute code not rendering

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15202]
If you have a widget that uses the pre-execute code field that has quotes in it, your page cannot render in LIVE mode.

To reproduce:
1. add this code to a widget content type > pre execute
```
<!--<script src="/test/test" id='test'>
-->
```
2. Add a widget of that type to a page.
3. Try to hit the page in live mode.  Error

**Comment by wezell** [comment]
We need to support $response.sendRedirect()

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15203

**Comment by erickgonzalez** [comment]
The page renders without issues in every mode.

**Comment by bryanboza** [comment]
Fixed, Unable to reproduce on release-5.0.2

**Comment by bryanboza** [comment]
Fixed, neither can reproduce on master
