### ISSUE TITLE
$quote is a reserved word in Velocity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15219]
If you have a content whose type has a field var "quote" or easier yet, you set a velocity variable called $quote to something, it can break all content on a page (not pulled) under it.
Add a widget with this:
```
Setting quote:
#set($quote = "i'm broken")
```

Then add content underneath (with an image or something to see)

![screen shot 2018-08-30 at 11 39 17 am](https://user-images.githubusercontent.com/934364/44862771-6ad90e00-ac49-11e8-980d-ae823ed97456.png)

### Fix
We need to replace the escapes here with their counterparts in the $esc tool

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/util/UtilMethods.java#L1288-L1320

This includes the variables
- quote
- pound
- return
- singleQuote
- pounds
- backSlash

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15221

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the fix

**Comment by erickgonzalez** [comment]
Tested on 5.0.2 Working as it should.

**Comment by bryanboza** [comment]
Tested on release-5.0.2 and works as expected
