### ISSUE TITLE
Detail Page is not showed when using Community License

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#15217]
## Expected Behavior
Value of the Detail Page should be shown when using Community License (is being saved successfully because I checked the DB and also applied a license and the value showed up)

## Known Workarounds
Apply any License and the value shows up.

## Steps to Reproduce (for bugs)
1. Start dotcms with Community License
2. Go to Content Types portlet
3. Click over any content Type
4. Go To Edit
5. Type path of a page and select one option that shows up.
6. The path of the selected page should be set.

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by wezell** [comment]
dupe #15195

**Comment by erickgonzalez** [comment]
@wezell this is not a dupe. This issue is for the UI since if you follow the steps above you are able to reproduce it.

**Comment by bryanboza** [comment]
We need to fix this issue in order to close the #15195

**Comment by erickgonzalez** [comment]
With this PR https://github.com/dotCMS/enterprise-2.x/pull/638 is fixed this issue.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/638 and https://github.com/dotCMS/core/pull/15306

**Comment by erickgonzalez** [comment]
Tested on 5.0.2 working as it should.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and now this is working fine.
