### ISSUE TITLE
Set LIBSASS to generate minified CSS

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15222]
Libsaas now generates Compact CSS, which is not fully minified.  We need LIBSASS to generate and deliver the sass minfied e.g. Compressed.

See the options here:
https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/OutputStyle.java

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/635

**Comment by dsilvam** [comment]
PR fixing tests: https://github.com/dotCMS/core/pull/15299

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 // postgres // FF

**Comment by bryanboza** [comment]
Tested on master too
