### ISSUE TITLE
Vanity URLS Need change the priority to resolve paths 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15223]
We need set priority to vanity URLs in order to resolve paths, this because right now we validate first if the real path exists in dotCMS and if not validate in vanities, and this should be in the other way around.

## Expected Behavior
We need to resolve first the vanity URL and then try to resolve the real path. 

This will useful to sites under maintenance because you only create a temporal path and this will redirect to another page. But right now this will not work because the real path exists. 

## Current Behavior
We validate first if the path exists in the site and then try to resolve as vanity. 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new folder `/test1/` 
3. Add a new page to this folder `index`
4. Create a new vanity `/test1/` and make a redirect to `/about-us/index`
5. Now hit for `http://localhost:8080/test1`

**We need to resolve the vanity without problems.** 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/issues/15223

**Comment by bryanboza** [comment]
Fixed, now the priority works as expected

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and works in the correct order
