### ISSUE TITLE
Navtool not working on edit mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15229]
Adding `$nav.getNav()` on a page returns nothing in edit mode.

Adding `$nav.getNav(2)` on a page returns nothing in edit mode.

Adding `$nav.getNav("/")` on a page returns nothing in edit mode.

And this:  #15162

**Comment by Xander-Steinmann** [comment]
My guess is that it has to do with the URL that starts with /api/v1/page/render

**Comment by wezell** [comment]
@Xander-Steinmann agreed

**Comment by erickgonzalez** [comment]
How to test:
1- Create a simple widget with the following code [navTool.txt](https://github.com/dotCMS/core/files/2112569/navTool.txt)
2- Create a folder e.g **navtest** and mark Show on Menu
3- Create a page inside **navtest** e.g **testpage1** and mark Show on Menu
4- Upload 1 File to **navtest** and mark Show on Menu
5- Create a new folder inside **navtest** e.g **insideFolder** and mark Show on Menu
6- Create a page inside **insideFolder** e.g **testpage2** and mark Show on Menu
7- Add the simple widget created on step 1 to **testpage2**

Now we do some tests changing the code of the widget:

- Leaving the code as it is **$navtool.getNav("/")** should show all navigation:
![image](https://user-images.githubusercontent.com/5278970/45112707-9c4c5080-b105-11e8-8a20-8ef3444afd66.png)

- Changing it to **$navtool.getNav()** or to **$navtool.getNav(2)**, should show only 1 item:
![image](https://user-images.githubusercontent.com/5278970/45112904-34e2d080-b106-11e8-8667-aaf861bc014d.png)

- Changing it to **$navtool.getNav(1)** or to **$navtool.getNav("/navtest")**, should show 4 items:
![image](https://user-images.githubusercontent.com/5278970/45112968-5b087080-b106-11e8-9df6-234f8e7fea89.png)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15253

**Comment by bryanboza** [comment]
Fixed, tested with the comment example and now works as expected
