### ISSUE TITLE
Make rules engine use primeng components

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15231]
As a stakeholder I want to remove jquery and semantic-js from our codebase.

**Comment by fmontes** [comment]
Bring this changes to core-web: https://github.com/dotCMS/dotcms-rules-engine/pull/5/files

**Comment by hmoreras** [comment]
> Bring this changes to core-web: https://github.com/dotCMS/dotcms-rules-engine/pull/5/files

This was fixed with the refactor.

**Comment by wezell** [comment]
done
