### ISSUE TITLE
Unable to see the document contents without license 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15238]
The only workflow that you can see and use without a license is the system workflow since in the starter site the default WF associated with this content type is the document management. Then when you try to see the contents we have a license error. 

## Expected Behavior
We need to be able to see the contents of document management without problems 

## Current Behavior
We have a license error in the log, and we are now displaying contents in the UI 
SC: https://gist.github.com/bryanboza/92d10d55ff8cbdc6cef3c3e9e7891248

## Steps to Reproduce (for bugs)
1. In a community instance of dotCMS 
2. Login as admin 
3. Go to content search portlet 
4. Select the document content type 
5. Check the log file 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15256

**Comment by bryanboza** [comment]
We continue with problems here, after applying for a license when you try to edit some of those contents we still having the message with no actions available 
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/81a0f942-b2d1-4ade-88d1-64ba67c93644/00000331.png

Also in the task portlet we are unable to see the contents when you filter by the document management WF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15312

**Comment by fabrizzio-dotCMS** [comment]
Tested on branch 'release-5.0.2' 
The contents of type Document are all visible without a License.  
You can see the list in the content search. Double click on any entry and get the content edit with window... But no Available actions are presented.
The Log is clean.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and now it is working as expected

**Comment by bryanboza** [comment]
Fixed, this is working ok master too
