### ISSUE TITLE
Content Type field properties don't save changes when deleting characters or adding whitespace

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#15246]
When you edit the `Value` field of any Content Type field property which uses allows for multi-line property values, the changes are not saved if you only delete characters (including whole lines) and/or you only add whitespace (including empty lines).

The only way to get the property to save is by actually adding or changing a non-whitespace character.

## Expected Behavior

All changes to values in the field properties should always be saved (as long as the resulting value is valid for the field).

## Current Behavior

If you change the value in the multi-line editing control for any field that has it, by only deleting characters or lines, the changes will not be saved.  No error message is generated (in the UI, in the browser console, or in the logs).

This affect all of the following field types:
* Checkbox
* Constant Field
* Custom Field
* Hidden Field
* Multi Select
* Radio
* Select

**Note:** The change fails to save even if you also change another property in the same field before hitting the `Save` button for the field.  In this case, the changes to the other property are saved, but the changes to the multi-line property are not saved.

## Possible Solution

This is just a guess, but I'm wondering if we have a change detection algorithm that's not recognizing deletions as changes, and won't actually save unless something has changed.

## Known Workarounds

Change or add at least one non-whitespace character in the field every time you make a change.

**Note:** For a Custom field another workaround is to use a `#dotParse()` directive to include the contents of the field from a VTL file, and then make your changes in the VTL file, rather than putting the code in directly.  But this isn't a valid workaround for Checkbox, Select, Multi-select, etc. fields.

## Steps to Reproduce (for bugs)

_**(On Demo)**_
1. Create a new content type.
2. Add a Hidden Field.
3. Set the `Value` property to the following (including newlines):
```
ABC
DEF
GHI
```
4. Save the field.
5. Edit the field again, and change the `Value` property to the following (by removing one character from the second line):
```
ABC
DF
GHI
```
6. Save the field.
7. Edit the field again and check the `Value` property.
**Result:** The `Value` property was not changed - it still contains all 9 characters.

**Note:** I didn't put specific steps to reproduce, but the same thing happens if you **insert** any white space anywhere in the `Value` property (even in the middle of one of the strings), or if you add or delete whole lines.

## Context

Not good, especially since many people will not go back and check to make sure their changes were saved - until after they go to test their changes on the content editing screen and see that it's not working as expected.

The inability to just delete an option from a Checkbox, Select, Radio, and Multi-select field is guaranteed to be a headache-inducer for some customers.

## Your Environment

* dotCMS version used: 5.0.1 (auth, demo)
* Browser Name and version: Chrome 68.0.3440.75
* Operating System and version: Win 10 Pro
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8? (auth, demo)

**Comment by john-thomas-dotcms** [comment]
Just for the record, I verified that this issue does not exist in 4.x - it's new to 5.0.

**Comment by mattyarbrough** [comment]
This is still an issue
