### ISSUE TITLE
Regex for "URL Pattern" field validation is incorrect and causes an error

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#15243]
If you set the `Validation RegEx` property of a Content Type field to the `URL Pattern` value we provide, and then attempt to enter any value at all into that field for a content item, an error popup appears.

## Expected Behavior

All regex patterns we provide as defaults/templates should work, and should not cause errors.

## Current Behavior

When you use the built-in `URL Pattern` regex, and attempt to save content with any value in the field using that regex, an error popup appears with the message `Illegal character range near index 68 ` followed by the regular expression.

## Possible Solution

The following regular expression works as expected.  I don't guarantee that all the escaping backslashes I added are required, but I can guarantee that more than half of them are:

```
^((http|ftp|https)://w{3}[d]*.|(http|ftp|https)://|w{3}[d]*.)([wd\.\_\-\#\(\)\[\],;:]+@[wd\.\_\-\#\(\)\[\],;:])?([a-z0-9]+.)*[a-z-0-9]+.([a-z]{2,3})?[a-z]{2,6}(:[0-9]+)?(/[/a-zA-Z0-9\.\_\-,\%s]+)*(/|\?[a-z0-9=%&\.\-,\#]+)?$
```

The line of code where this regex is set is here (though it would still need to be escaped more for how it's inserted into the HTML/JS code):

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/structure/edit_field.jsp#L724

## Known Workarounds

Manually edit/create the regex.

## Steps to Reproduce (for bugs)

1. Open any content type with a text field.
2. Open the text field.
3. Next to the `Validation RegEx` property, select `URL Pattern` from the drop-down list.
4. Save the field.
5. Open the `Content` -> `Search` screen.
6. Create a new content item of the Content Type.
7. Fill in all fields, and put something (even just 'a') in the field with the URL Pattern validation.
8. Save the content item.
**Result:** A popup displays the error.

## Context

Ugly and prevents the validation from working.  I'm not sure if it prevents the content item from saving, or if the value you enter is saved without validation (due to a known caching issue when the validation fails).

## Your Environment

* dotCMS version used: 5.0.1 (auth)
* Browser Name and version: Chrome 68.0.3440.75
* Operating System and version: Win 10 Pro
* Application Server and version: tomcat (distro - auth)
* Java Brand and version: 1.8 (??? - auth)

**Comment by john-thomas-dotcms** [comment]
This is still an issue.  Really one we should fix, since it causes errors with vanilla OOTB code.

At the very least, we should remove any validations that just don't work (like the URL Pattern validation).  Just removing this one would be a very easy fix, and it's obvious no one would miss it since it doesn't work.

**Comment by fmontes** [comment]
Needs to be fixed in the BE

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core-web/pull/1302

**Comment by dsilvam** [comment]
Passed Internal QA: Regex properly validating

**Comment by dsilvam** [comment]
Passed QA: Working as expected on master.
