### ISSUE TITLE
Deprecate isInodeIndexed

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15264]
We need to evaluate the usages of isInodeIndexed in our code and see if it's really necessary and also deprecate the methods. For cases when we need to wait, we need to come up with a different alternative (refresh?). 

Also
`reindexNow(List<Contentlet> cons)`
`reindexLater(List<Contentlet> cons)`

the reindex now should just call the `indexContentletList` with the ES `refresh` value set to wait
and the reindexLater should be a commit listener that inserts the identifiers into dist_journal table, e.g. to the `DistributedJournalAPIImpl.addContentletToIndex`

This will allow content that can be indexed asynchronously to be indexed across a cluster

- We need to add a method/property to a Contentlet called `Contentlet.waitForIndex(true|false)` that if it is set, we will either call reindexNow or reindexLater.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15366
