### ISSUE TITLE
Prevent BeanUtils from copying unneeded properties

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15261]
BeanUtils is aggressive when it introspects and copies a Bean's properties and includes things like the getClass method.  To test, hit a url like this:

http://127.0.0.1:8080/dotCMS/login?class.classLoader.defaultAssertionStatus=true

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15262

**Comment by nollymar** [comment]
Tests Result: Success

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.2 and now after hitting the provided URL, I have the expected log: 
https://github.com/dotCMS/core/pull/15262/files#diff-05842eddca2d5cca7decb48ad5521cc3R449

**Comment by bryanboza** [comment]
The same results on master
