### ISSUE TITLE
Wrong message in edit Sites window

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15272]
In the edit Contentlet modal when editing a Site we see `No available Workflow Actions were found.`.

That message does not apply to Sites as Sites does not work with Workflows.

![sitesError.png](https://images.zenhubusercontent.com/570baf67bf93871ccd993571/39a1811d-1ad4-4a00-a716-cb194e35f894)

The validation to display that message should exclude Content Types of type Host.

**Comment by jgambarios** [comment]
Broken in: https://github.com/dotCMS/core/issues/15238

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by dsilvam** [comment]
Fixed in 5.0.2

**Comment by bryanboza** [comment]
Fixed, now we don't this message on 5.0.2
