### ISSUE TITLE
Constant fields do not flush cache when changed

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15283]
### What happens - Widgets don't look like they are updating.

1. Create a new widget
2. add a title field
3. Edit the widget code field, add `This works!` into it
4. Create a new instance of the widget and drop it on the page
5. You should see `This works!` show up.
6. go to backend and edit the content type > widget code field again.
7. Change widget code to read `This does not work`
8. Hit the page on the front end again.  It will display `This works!`
9. Manually flush cache
10. Hit the page on the front end again.  It will display `This does not work`
 
### What should happen
Step 8 should show `This does not work` without the manual cache flush

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15284

**Comment by dsilvam** [comment]
Working as expected in 5.0.2

**Comment by nollymar** [comment]
Working as expected in master
