### ISSUE TITLE
Task04300UpdateSystemFolderIdentifier fails if mysql set to case sensitive

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15287]
If you are running mysql with `lowercase_table_names=0` (as you probably should be) then this upgrade task fails because the table name is `folder`

this happens somewhere from 4.1 to 5.0
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04300UpdateSystemFolderIdentifier.java#L27-L29

**Comment by maverick1981** [comment]
Upgrading from 4.3.3 to 5.0.3 I encountered the same problem for **Task04340TemplateShowOnMenu** too.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04340TemplateShowOnMenu.java
