### ISSUE TITLE
JavaScript Event calls need to fail more gracefully

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#15296]
When logging into the backend of a dotcms instance that has a proxy listing on a port other than 80, the websocket call to the /api/ws/v1/system/events URL fails to connect.  When this happens, it continues to submit requests over and over again.  On my system, it is sending the request 15-20 times per second!
 
## Expected Behavior

If there is a connection problem with websocket calls, I would expect it to try once every 15 seconds or once a minute.  It should NOT crank out the requests as quickly as it can.  Results in high CPU on client machine and if there is another server it happens to connect to, it will place alot of meaningless load on that server.

## Current Behavior

![image](https://user-images.githubusercontent.com/3208956/45588828-ec36ce80-b8e0-11e8-8519-1dc263a3d35c.png)

Also of notice is that the websockets are trying to communicate over port 80 even though the page was loaded from port 8080.
![image](https://user-images.githubusercontent.com/3208956/45588851-1ee0c700-b8e1-11e8-82a6-c7e04ec89e7b.png)

## Known Workarounds

You can configure the ```dotcms.websocket.baseurl``` property to fix issue; however, keep in mind that unless somebody opens up the developer tools or notices their browser burning up the CPU, they will never know that they need to change this setting.

Why is the servername:port decision not being figured out in JavaScript in the browser?  Seems strange to me that this is configured on the server side when the client knows what server and port it is communicating with.  Unless there are compelling reasons, this should be determined via the client.  Not to do so seems problematic - DNS issues, etc.  If the client communicates with the same endpoint that it is making all of the other requests to, that seems much easier to control and less problematic.  If there is a desire to route websocket requests differently that can be done via loadbalancer, proxy, or ingress configuration.

## Steps to Reproduce (for bugs)

1.  On a computer with docker and docker-compose installed, copy this file locally:  https://gist.github.com/brentgriffin/a1da04b005e27d28848a354d021ba938
2.  In the directory with the docker-compose.yml file you just downloaded run:  ```docker-compose pull```
3.  Then run ```docker-compose up```
4.  After system startup and creates starter data, verify frontend works at http://localhost:8080/
5.  Login to backend and open up the developer tools on the network tab
6.  See the failed event requests scrolling by

## Your Environment

* dotCMS version used: 5.0.2 docker image
* Browser Name and version:  Chrome
* Operating System and version: OSX 10.13.6
* Application Server and version:  embedded tomcat
* Java Brand and version:  OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
* Database and version:  Postgres 9.6
* Application module (if apply):

**Comment by nollymar** [comment]
Tests Results:

After following the steps described above, events errors are not shown on the developer tools. However, no portlet can be loaded. Only the sad face is displayed: 

![image](https://user-images.githubusercontent.com/8741395/54295911-ecf3a900-4581-11e9-9e55-0603086a4d01.png)

**Comment by brentgriffin** [comment]
It is failing better - the requests for the events are still failing but not retrying so quickly.  Notice that the URL for events is still wrong:
![image](https://user-images.githubusercontent.com/3208956/54301339-be2f0000-458c-11e9-8678-32cc998a0334.png)

**Comment by freddyucv** [comment]
> It is failing better - the requests for the events are still failing but not retrying so quickly. Notice that the URL for events is still wrong:
> ![image](https://user-images.githubusercontent.com/3208956/54301339-be2f0000-458c-11e9-8678-32cc998a0334.png)

we don't include the port into the web socket url in the default value here:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/util/HttpRequestDataUtil.java#L201

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16412
