### ISSUE TITLE
Sort widget content types by name

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15290]
In edit mode, when adding a widget to a page, the list of available widget types is not sorted alpha.  They should be.

![screen shot 2018-09-14 at 2 49 23 pm](https://user-images.githubusercontent.com/934364/45569397-6443bc80-b82d-11e8-8310-a1e00edb8822.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15293

**Comment by wezell** [comment]
@bryanboza the issue you reported above is not happening because of this card.

**Comment by bryanboza** [comment]
Still happening when you paginate... https://screencast.com/t/ctqeDAtivoz

**Comment by wezell** [comment]
@bryanboza this wasn't what the original card was intended to fix and isn't a bug, it would be an improvement.

**Comment by fmontes** [comment]
I create this one for the listing: https://github.com/dotCMS/core/issues/15486

**Comment by bryanboza** [comment]
We don't have changes here, this list isn't sorted: https://screencast.com/t/ftMtA4PSRf

**Comment by bryanboza** [comment]
Fixed, the main problem was fixed. Tested on release-5.0.3 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, now this list is ordered, tested on the last master
