### ISSUE TITLE
Implementation error after use the persona feature in live mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15305]
We are having an error when you are in the live mode editing a page and you try to use the persona feature. 

## Expected Behavior
We need to be able to use it, and then come back to edit more pages without problems 

## Current Behavior
When you try to see use some persona we are redirecting to some page, and after that when you go to live mode in any page we fake an ajax call there.
SC: https://screencast.com/t/hnZ0wombN

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to edit some page 
3. Go to live tab 
4. Click to any persona 
5. Go back to site browser 
6. Edit another page
7. Go to live tab again 

## Your Environment
Tested on the last master code // Postgres // FF

**Comment by wezell** [comment]
this will be fixed in the new starter
