### ISSUE TITLE
Can not create new content type with a limited user and a blank site

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#15308]
## Current Behavior
When you click over the button to create a new content type as a limited user on a blank site nothing is shown.

This endpoint https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResource.java#L301 is returning empty.

If you create a content type as an admin on the blank site, the base type of that content type is now shown.

## Steps to Reproduce (for bugs)

1. Create a new blank Site
2. Create a new Role
3. Create a new User and assign that Role
4. Give Full permissions to that Role over the new site
5. Give the Role access to the Types & Tags Tool
6. Log in as that User
7. Try to create a new Content Type

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by erickgonzalez** [comment]
Related to https://github.com/dotCMS/core/issues/15285

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15346

**Comment by bryanboza** [comment]
Fixed for now, pending fixes on the card #15285

**Comment by erickgonzalez** [comment]
Still waiting to this ticket https://github.com/dotCMS/core/issues/15304

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Postgres // FF
