### ISSUE TITLE
Create Integration test for DefaultBackEndLoginRequiredWebInterceptor

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15307]
We need to create an integration test for the work made here https://github.com/dotCMS/core/pull/15278 for the ticket https://github.com/dotCMS/core/issues/15274

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15347

**Comment by bryanboza** [comment]
Fixed, those test are running now
