### ISSUE TITLE
Not setting the host when creating a content type

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#15304]
## Current Behavior
When you create a new content type but you leave the Site or Folder field as it is, no value is set at the form so by default is created on the default host.

## Steps to Reproduce (for bugs)
1. Create a new blank Site
2. Create a new Role
3. Create a new User and assign that Role
4. Give Full permissions to that Role over the new site
5. Give the Role access to the Types & Tags Tool
6. Log in as that User
7. Try to create a new Content Type
8. Permission Denied exception is thrown because is trying to create the content type over the default host (in this case demo.dotcms.com) regardless of the value on the Site or Folder says the name of the new site

We need to pass in the contentTypeForm the value of the host that is shown on the Site or Folder field.

## Your Environment
* dotCMS version used: master
* Browser Name and version: FF

**Comment by erickgonzalez** [comment]
This issue is related to https://github.com/dotCMS/core/issues/15285

**Comment by erickgonzalez** [comment]
Tested on master and working now as it should.

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/47242963-b8523b80-d3ad-11e8-9a47-9d9c12280787.png)


core commit: `c2fe93a630a579a56bd7fde7abe2a6644a4a1a1a`

**Comment by fmontes** [comment]
In Content Types is updating the value of the field to "current host"

**Comment by fmontes** [comment]
Needs to update a test for 5.1

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
