### ISSUE TITLE
[REST] : GET method in ContentRelationshipsResource class must not require authentication

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15319]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/96602
Reproducible in dotCMS 5.0.1, 4.3.3

The GET method in the `ContentRelationshipsResource` endpoint is requiring authentication. This was caused by an incorrect change made when the source code was brought into our core functionality.

## Expected Behavior
The endpoint must be accessible by non-authenticated (anonymous) users.

## Current Behavior
The GET method requires authentication.

## Possible Solution
Fix the part of the code that is forcing authentication: https://github.com/wezell/com.dotcms.rest.page/blob/master/src/main/java/com/dotcms/plugin/rest/page/ContentWithRelationsResource.java#L65

## Known Workarounds
Passing down an authenticated user, which is NOT feasible in most cases.

## Steps to Reproduce (for bugs)
1. Start up a dotCMS instance.
2. Using a tool such as Postman, do a GET on the following endpoint: http://localhost:8080/api/v1/contentRelationships/id/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6 WITHOUT passing down any authentication mechanism.
3. The error page is returned instead of the expected JSON response.

## Context
When implementing search mechanisms in their Websites, customers need to retrieve content and its related content to display correct information. Features like these don't require authenticated users, so this change is required.

## Your Environment
* dotCMS version used: 5.0.1, 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: REST Endpoint.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/15327

**Comment by dsilvam** [comment]
Passed internal qa: Able to fetch info with no authenticated user
