### ISSUE TITLE
Unable to render pages in S3 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15310]
We are having problems trying to render pages in S3, this because in previous versions we sent the compiled CSS file and all the dependencies but after the SASS compilation changes, we are not sending the dependencies and we are unable to compile in the static site. 
SC: https://screencast.com/t/DkDVkHhFdvuR

**FYI: We recently change the way to compile those files, then I think we need doing some changes in the S3 stuff** 

## Expected Behavior
We need to send the compiled CSS file and all the dependencies to allow render the page in S3. 

## Current Behavior
We have 2 issues here: 
1- We are not including the CSS dependencies in the bundle 
2- We are unable to render pages in S3: https://screencast.com/t/zXjwWv7N27j

Note: Tested pushing the complete site and have the same problems 

## Steps to Reproduce (for bugs)
1. Configure your push environment to S3 
2. Login as admin
3. Create a new folder
4. Add a new page to the folder and add a new piece of content 
5. Push the page 
6. Try to see the page in the static site 

## Your Environment
Tested on release-5.0.2

**Comment by nollymar** [comment]
After @wezell 's fix the 404 error is not shown anymore. However, the rendering is not working, now a 403 error is thrown: https://www.screencast.com/t/OVyMfF19zOl

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15430

PR for EE: https://github.com/dotCMS/enterprise-2.x/pull/643

**Comment by bryanboza** [comment]
Fixed, now we are rendering the pages, new related card reported on #15527

**Comment by bryanboza** [comment]
Fixed, now we are able to render pages, tested in the last master code
