### ISSUE TITLE
Remove Relationships from Hibernate

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15318]

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15376

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/15426

**Comment by erickgonzalez** [comment]
PR 3: https://github.com/dotCMS/core/pull/15432

**Comment by nollymar** [comment]
CRUD operations over relationships are working fine. However, push publishing related content is failing. A new card was registered here: https://github.com/dotCMS/core/issues/15435

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/15441

**Comment by nollymar** [comment]
Working fine after fixing issue #15435

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
