### ISSUE TITLE
Integration test for the WorkflowResource fire method

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15326]
We need to create an integration test for the `fire` method of the `WorkflowResource` and that test needs to include the case fixed in https://github.com/dotCMS/core/issues/15192

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15351

**Comment by bryanboza** [comment]
Fixed, this integration test is running and not failing 
https://cb.dotcms.com/job/Build_Full_Tester_Func_Int_release-5.0.3_Postgres/7/
