### ISSUE TITLE
Add tab field feature to new content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15339]
As a user I want to be able to add tab and rows/colums and fields inside it to a content type.

## Expected Behavior
User should be able to add a tab "field" and put rows and columns with real fileds inside

## Mock
https://dotcms.slack.com/files/UAGH9G3AR/FCYVBC28G/conent_types_-_tab_divider.mov

## Acceptance Criteria

1. Match the design
2. Filter out the "Tab field" from the list of fields in the right column
3. Tab should be able to be renamed inline
4. Tab should be able to be drag and drop only vertically and between rows (not inside columns)
5. Tab field should take field variables
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
QA: 
Flickering when updated tabs

**Comment by bryanboza** [comment]
Unknown error trying to add tabs with the same name, also after if you delete some tab and you try to add a new one with the same name of the deleted in the next 5 seconds we have the same error, we need to check the performance here. 

SC: https://screencast.com/t/fvZTxWgMYpTt

**Comment by bryanboza** [comment]
Still having the same problem here:  https://screencast.com/t/cAADLAkyzz
To reproduce: 
- Create a new tab 
- Type the name and hit the enter key
- Create a new one with the same process.

**Comment by alfredo-dotcms** [comment]
@bryanboza a fix is currently being worked for that, stay tuned!

**Comment by fmontes** [comment]
Fix published, @bryanboza deploy.

**Comment by bryanboza** [comment]
Need a better error when you type a really long name \
<img width="1680" alt="img1" src="https://user-images.githubusercontent.com/2641437/50991305-fad17300-14d9-11e9-86e9-2dcc8e6ea8ae.png">

Also we are unable to delete the tab, this when the name overrides the delete button 
SC:  https://screencast.com/t/2HEiQ2eYBn

**Comment by bryanboza** [comment]
Now we are validating the max length when you are adding a new tab. But we continue with the same problem when you try to rename the tab using the in-line editing. 
SC: https://screencast.com/t/jAEmwdEV

**Comment by fmontes** [comment]
Fixed, there is an edge case when you add 255 chars paragraph it breaks into two lines but you onle see one, you can edit both lines by moving with arrows keys, is not ideal but because we need this to be responsive is the best we can do without doing javascript.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
