### ISSUE TITLE
URLMap filter serves up pages regardless of path if base path is correct.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15343]
If you have a URL MAP for a content type such as blog so that this page returns the correct blog entry:

 https://demo.dotcms.com/blogs/bill-ackman-s-top-stock-picks

If you add to the path it will still return that same page even if you entered something like

 https://demo.dotcms.com/blogs/bill-ackman-s-top-stock-picks/any/other/path

**Comment by wezell** [comment]
This is expected behavior.
