### ISSUE TITLE
Images can't be removed from Image Fields

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15340]
Tested on latest 5.0.2 version on multiple instances

To reproduce:

1) Create a new content type with a single image field
2) add content using the new content type and upload and publish an image to the image field
3) re-open the piece of content and remove the image and save and publish
4) re-open the content - the image is still there, even though you tried to remove it previously (bug)

Screencast: https://www.screencast.com/t/NUi9daYRu

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15386

**Comment by jgambarios** [comment]
As discussed please add the `@Ignore` Jackson annotations

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgress // FF

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 and now works as expected
