### ISSUE TITLE
Cannot clear text fields when editing content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15353]
When editing content, if you clear the values in a text/textarea/wysiwyg field, the old values persist.  

I am sure this is causing/a dupe of #15340

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/15340

**Comment by bryanboza** [comment]
We have the same case with the time fields, we are unable to clear, when you try it, the system is setting a default value and set this. Although when the default value is in blank in the field properties.
SC: https://screencast.com/t/5kDddVmTrwH

**Comment by wezell** [comment]
Time fields work as they did in previous versions

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 // postgres // FF and now we are able to clear those fields without problems
