### ISSUE TITLE
NG6 content type/field issues

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15352]
Running the latest ng6 build

- [ ] If you drag a field on to a content type, then hit cancel, the field remains on the content type with no values (obviously invalid).

- [ ] Additionally, the "name" of the field type disappears. 

- [ ] Add a field called "test".  Then add another field of the same type.  You will see the second field has the values from the first field already entered

![contenttypes](https://user-images.githubusercontent.com/934364/46146950-14ec8b80-c232-11e8-9a98-1d9953c04c39.gif)

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce those cases on the last master code
