### ISSUE TITLE
OSGi problem on initial start

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#15358]
When dropping an OSGi plugin and its matching fragment plugin into the dotserver/tomcat-8.5.32/webapps/ROOT/WEB-INF/felix/load directory prior to starting up dotCMS, dotCMS throws BundleExceptions and fails to activate the bundle.  Both jar files show up as "Resolved"

![image](https://user-images.githubusercontent.com/3208956/46223979-90296c80-c31a-11e8-8318-0d95a6122484.png)

The specific jar files being used here are from building this:  https://github.com/dotCMS/plugin-demo.dotcms-oauth2/tree/5.0.2

When I restart the OSGi framework or restart the entire server, the plugins load without throwing exceptions and seem to work properly.

![image](https://user-images.githubusercontent.com/3208956/46224220-51e07d00-c31b-11e8-8374-ddedc6edfb01.png)

## Expected Behavior

Expect the plugins to start up correctly (no exceptions) just as they do when I upload them through the backend UI.

Originally found in docker configuration but problem also happens from the 5.0.2 release tarfile

Full catalina.out file with Exception stacktraces are available here for reference:  https://gist.github.com/brentgriffin/af4c8893ceda55d3cd0b89ee0b8e1e1b

## Known Workarounds

Restart OSGI framework, restart dotcms server, or manually upload plugins through backend UI.

## Steps to Reproduce (for bugs)

1.  Download and untar 5.0.2 release
2.  Copy both oauth2 plugin jar files to dotserver/tomcat-8.5.32/webapps/ROOT/WEB-INF/felix/load
3.  Startup dotcms via bin/startup.sh
4.  Notice BundleExceptions in catalina.out and view plugin status on backend at DevTools->Plugins

## Context

Trying to implement a way for dynamic plugins to be automatically deployed in an instance of dotCMS running in a container.  We have the mechanism in place but the OSGi plugins do not work until a workaround is applied.

Clearly this is problematic when trying to automate deployments that need to contain OSGi plugins.

## Your Environment

* dotCMS version used: 5.0.2 - also version 5.0.2 of oauth2 plugin
* Browser Name and version: N/A
* Operating System and version: OSX & linux
* Application Server and version: embedded tomcat
* Java Brand and version: 8
* Database and version: Postgres 9.6 and 10.1
* Application module (if apply):

**Comment by bryanboza** [comment]
Fixed tested with oauth2 and action plugin and works as expected

**Comment by bryanboza** [comment]
Fixed, tested on master and works fine
