### ISSUE TITLE
Change how URLMaps handle multilingual content

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#15369]
Client: https://dotcms.zendesk.com/agent/tickets/96630

## Expected Behavior
As documented: https://doc.dotcms.com/docs/latest/url-maps-multilingual

> Since each language version of content has a different title in the appropriate language, URL maps automatically include the translated title as part of the URL map.

## Current Behavior
404.

## Known Workarounds
Send parameter language_id, but depends on client's use case requirement. 

## Steps to Reproduce (for bugs)
1. Create a Content Type "Test" with a "Title":Text:Indexed and "Body":WYSIWYG
2. Set up a url map like: "/test/{title}" and setup a detail page to print the contentlet.
3. Create an english version with title:"English" and a spanish version with title:"Spanish"
4. Try to hit: /test/english and then /test/spanish, you will get a 404.

## Context
[This code here](https://github.com/dotCMS/core/blob/5.0.2/dotCMS/src/main/java/com/dotmarketing/cms/urlmap/filters/URLMapFilter.java#L188-L199) is ignoring this use case completely.[Checking for the DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE property](https://github.com/dotCMS/core/blob/5.0.2/dotCMS/src/main/java/com/dotmarketing/cms/urlmap/filters/URLMapFilter.java#L189) doesn't make sense. We want to get a result based on the Content Types fields (in this case the title), we shouldn't care about the default language if we find a matching result on ES on the title.

## Your Environment
* dotCMS version used: 5.x

**Comment by wezell** [comment]
If the urlMap



Create a Content Type "Test" with a "Title":Text:Indexed and "Body":WYSIWYG
Set up a url map like: "/test/{title}" and setup a detail page to print the contentlet.

Create one content english version title:"English" and a spanish version title:"Spanish"
Hit: /test/english                      = english
Hit /test/spanish                       = spanish

Create one content english version title:"myPage" and a spanish version title:"myPage"
Hit: /test/myPage                       = english
Hit: /test/myPage?languageId_id=1       = english (session language set to english)
Hit: /test/myPage?languageId_id=2       = spanish (session language set to spanish)

Create one content spanish version with title:"miPagina" 
Hit: /test/miPagina?languageId_id=1 = 404  (session language set to english)
Hit: /test/miPagina?languageId_id=2 = spanish (session language set to spanish)

Create one content english version title:"myPage" and a spanish version title:"miPagina"
Hit: /test/myPage                       = english
Hit: /test/myPage?languageId_id=1       = english (session language set to spanish)
Hit: /test/myPage?languageId_id=2       = REDIRECT TO /test/miPagina (session language set to spanish)
Hit: /test/miPagina                     = Spanish
Hit: /test/miPagina?languageId_id=1     = REDIRECT TO /test/myPage (session language set to english)

Create two contents - 1 english version with title:"myPage" another content (not a version) spanish title:"myPage"
Hit: /test/myPage                       = english
Hit: /test/myPage?languageId_id=1       = english (session language set to english)
Hit: /test/myPage?languageId_id=2       = spanish (session language set to spanish)



Create a config property called ALLOW_URLMAP_TO_SET_LANGUAGE = FIRST_HIT, ALWAYS, NEVER
default = ALWAYS

If FIRST_HIT and a user hits a non-default urlMap as their first page e.g. session.isNew then we set their session language to the language of the urlMap.

If ALWAYS a user hits a non-default urlMap then we set their session language to the language of the urlMap (this negates the first option)

If NEVER, we do nothing to the session language

**Comment by wezell** [comment]
@jgambarios @DeanGonzalez  shared some code to begin to enable this

**Comment by wezell** [comment]
This is not a bug b/c this is how URLMaps were originally designed.

**Comment by wezell** [comment]
As part of this task, we need to move the logic from the `URLMapFilter` to the `URLMapAPIImpl`
