### ISSUE TITLE
Site Variable user permissions broken

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15361]
If a user creates Site Variables and then that user is deleted no other users (including Admin) can access to edit/remove those variables or add new ones.

## Known Workarounds
The recommended approach now that Sites are content is to use the Host content type and add variables to that rather than to do them via Site Variables.

## Steps to Reproduce (for bugs)
1 - Log in as admin@dotcms.com
2 - Add site variable
3 - Log out
4 - Log in as admin2@dotcms.com
5 - Confirm access to site variables
6 - Delete admin@dotcms.com user and assign all ownerships to admin2@dotcms.com
7 - Log out
8 - Flush cache
9  - Reindex
10 - Unable to access site variables, the browser console shows [Log] dotcms.org.1 – {javaClassName: "com.dotmarketing.business.NoSuchUserException", message: "dotcms.org.1"} (layout, line 103)
Nothing is written to the dotcms.log 

Video of replication:
https://drive.google.com/open?id=1kJNWlS2SCgwaywmUIUblJaqVBk4GkVub

## Your Environment

* dotCMS version used: 4.3.3, 5.0.2

**Comment by mattyarbrough** [comment]
This has affected multiple cloud and on premise customers recently

**Comment by oarrietadotcms** [comment]
Hotfix is not the only fix, the real fix has to happen when the user is deleted. Part of the deletion should be replace that user id of the site variable.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF

**Comment by jcastro-dotcms** [comment]
Fix added to 5.0.3 Maintenance Plugin: https://github.com/dotCMS/support/tree/master/maintenance_plugins/com.dotcms.maintenance-5.0.3
