### ISSUE TITLE
Need to hide the persona content types if your license expire 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15360]
The persona feature is an EE feature, but if you have a license and add a new persona content types, and your license expires, we need to hide those ones. 

## Expected Behavior
We need to hide the persona content type and all the content types of that type.

## Current Behavior
We continue showing the persona content types without a license 

## Steps to Reproduce (for bugs)
1. Set an environment with license 
2. Create a new persona content type 
3. Remove the license 
4. Try to edit the added content type 

**Also, we need to remove the persona from the content search portlet or add a valid message that indicates you don't have a license when you try to add a new piece of content in the community edition** 

Right now we show this: 
<img width="1652" alt="persona" src="https://user-images.githubusercontent.com/2641437/46315484-d7b62f80-c58a-11e8-88b8-66c315b2c8e9.png">

And this is the error on the log: https://gist.github.com/bryanboza/45c6ce2f0ed19cff8720a39c3592b14f

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
known issue
