### ISSUE TITLE
Permissions inconsistencies applying cascade permissions from Roles&Tools 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15389]
We have an inconsistency applying for cascade permissions to a site from Roles&Tools portlet. Seems is not affecting their children content. 

## Expected Behavior
If you apply for cascade permissions from Roles&Tools portlet, or if apply it directly from the site properties should be the same. 

## Current Behavior
When you apply for the cascade permissions to a site from the roles&tools portlet, and then go to to see the changes, we are unable to see the changes in the children content. But if you apply the cascade changes from the site properties this works as expected

SC:  https://screencast.com/t/S2MWYSxbRbk

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new copy of the demo site 
3. Go to roles&tools portlet and create a new role with the following permissions (https://screencast.com/t/fENs70Oj36q), 
4. Enable the cascade changes and apply
5. Make sure in the tools tab you have access to home, site and content portlets https://screencast.com/t/tzLApYvg
6. Now add a new user and add the new role to it (https://screencast.com/t/tzJeSfoy03)
7. Login as the new user and make sure you have files, pages under every folder 

**FYI: If you come back to the admin user and cascade permissions from the site properties directly and then login as again as the new user, you are able to see the files and pages without problems.** 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
Note:

It looks like cascading permissions from the Role portlet behaves differently than from the site portlet and the Roles Portlet does not include the Page as Content and the File Asset as Content objects.  The logic for the cascade seems to be taking 2 paths.  We need to unify the cascade logic to a single path that runs in a StatefulThread and use the NotificationAPI to alert when the cascade is complete.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15478

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 and now this works as expected. We need to fix the login as problems reported on card #14116

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
