### ISSUE TITLE
Host Select field is not selecting the displayed host on Content Types

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15388]
Reproduced on dotCMS 5.0.2 release version:

This issue should be resolved immediately AFTER we resolve the permissions issue in:  https://github.com/dotCMS/core/issues/15285

Bug: When a limited user with permissions to create new content types on a non-default host tries to add a new content type, the site or folder field attempts to save the new content type to the default host instead of the host shown in the select field.

<img width="1426" alt="screen shot 2018-10-05 at 11 17 34 am" src="https://user-images.githubusercontent.com/1569167/46549884-ab532980-c890-11e8-87b5-896e590a979f.png">

The select field shows the secondary host that the user has permissions to create content types on, but the denial error below comes from the save of the Content Type being attempted on the default host instead of the host that is shown in the select box.

<img width="1427" alt="screen shot 2018-10-05 at 11 17 21 am" src="https://user-images.githubusercontent.com/1569167/46550070-287e9e80-c891-11e8-9768-720dc89296d9.png">

**Comment by wezell** [comment]
dupe
