### ISSUE TITLE
Need reorder the base types list in the content types portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15382]
We need to reorder the list of base type content types, this on the content types portlet, we recently change something here and lost the order 

<img width="218" alt="order" src="https://user-images.githubusercontent.com/2641437/46496466-5d2d2000-c7d5-11e8-8743-a91fca8e7d92.png">

## Your Environment
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
Fixed in 5.0.3 branch

**Comment by bryanboza** [comment]
Fixed, now we have the previous order again, tested on release-5.0.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master and now we have the same order
