### ISSUE TITLE
[Widget API] Built-in variable $host is overwritten in widget retrieved from dotCMS API

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15387]
Reported via Support: [Ticket 96646](https://dotcms.zendesk.com/agent/tickets/96646)
Reproducible in dotCMS 4.3.3

When dotCMS REST API is used to retrieve a widget (URL: /api/widget/), the widget properties are added to the velocity context. One of these properties is called "host", so it overwrites the builtin $host variable.

## Expected Behavior
Builtin variable $host should be available as an object in the widget code, when the widget is retrieved from the dotCMS REST API.

## Current Behavior
Builtin variable $host is being replaced with widget "host" property, when the widget is retrieved from the dotCMS REST API.

## Possible Solution
Fix code to put widget properties inside a different variable in the velocity context, so $host builtin variable is not overwritten
https://github.com/dotCMS/core/blob/1e858284eb2d70a3e65e371eea67fdf4adffdefc/dotCMS/src/main/java/com/dotcms/rest/WidgetResource.java#L97-L99

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Create a new content of simple widget type, that uses the builtin $host variable.
`<div> Host: $host.map.title</div>`
2. Call the new widget using the dotCMS REST API
`/api/widget/id/<content-id>`
3. $host builtin object properties values are not rendered in widget output. For example, this output is rendered:
`<div> Host: $host.map.title</div>`
Instead of expected output:
`<div> Host: demo.dotcms.com</div>`

## Context
This issue happens when the widget is retrieved from dotCMS API REST, not when the widget is used in a dotCMS page.
This has been reported by customer via Support: [Ticket 96646](https://dotcms.zendesk.com/agent/tickets/96646) 

## Your Environment
* dotCMS version used: 4.3.3

**Comment by wezell** [comment]
preprends "widget" to the original variables in case the user still wants to access the widget variable rather than the context variable.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
