### ISSUE TITLE
Unable to use bulk actions as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15385]
We are unable to use the "common" actions in content types with individual permissions when you are an as limited user. 

## Expected Behavior
As in the workflow filter, we need to be able to execute bulk actions without problems 

## Current Behavior
If you set full permissions to some content type and try to execute bulk actions to multiple pieces of content, we are unable to see the actions if you are as limited user 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content (test) and set full permissions to Chris Publisher  (https://screencast.com/t/yJA3XWnxR)
3. Create 3 new pieces of content and make sure you can execute bulk actions (https://screencast.com/t/kRenghHCL)
4. Now login as Chris Publisher and add 2 new pieces of content 
5. Select the new 2 pieces and make sure you can see the bulk actions list (https://screencast.com/t/9qMbMSENn)

## Known Workarounds
- If you right click as Chris Publisher we have the list of the available actions, and you can execute those ones without problems (https://screencast.com/t/HbbixP0I3)
- As you can see in the image, both contents are in the published step of the system WF, if you check the "Unpublish" properties this has the "Anyone who can Publish Content" (https://screencast.com/t/z4JWumwrxWKE)

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15453

**Comment by bryanboza** [comment]
This is breaking the bulk actions functionality on release-5.0.3, we need some work here...

**Comment by bryanboza** [comment]
Fixed, tested in the last release-5.0.3 code // Postgres // FF and works as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // oracle and now it is working as expected
