### ISSUE TITLE
Dialogs: we need them to work as cool as possible

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15398]
### Problems with dialogs

1. Not centered
2. Animation flicker when the content is an iframe, ex: edit contentlet
3. Dialog grows outside the viewport, ex: create text field in a content type
4.  Is not adjusting to it contents, ex: create several field variables
5. Buttons (cancel and save) are not the right ones, cancel should be secondary and save primary

**Comment by fmontes** [comment]
For QA here is where the `dot-dialog` is being used

<img width="405" alt="screen shot 2018-10-18 at 12 38 55 pm" src="https://user-images.githubusercontent.com/751424/47176416-ce3efe00-d2d2-11e8-86af-db098dafd383.png">

**Comment by alfredo-dotcms** [comment]
extra border on several dialogs
![image](https://user-images.githubusercontent.com/37185433/47243119-534b1580-d3ae-11e8-8a4c-51a442b1d3f9.png)
![image](https://user-images.githubusercontent.com/37185433/47243142-68c03f80-d3ae-11e8-8d6a-bb147f298bb8.png)

**Comment by alfredo-dotcms** [comment]
https://monosnap.com/file/E8QMRxKe5rew7nclVe3hXM8A0TiEda

LAYOUT page broken in FF

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/47244391-97401980-d3b2-11e8-8c53-5d3f683c2729.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/47245198-91980300-d3b5-11e8-9cf7-dc4da0c9c58a.png)

**Comment by fmontes** [comment]
When you are focus in a "multiline" field (like a text area) in a form inside a dialog and hit "enter" it executes the "accept action" but because is a multiline field we should catch that and just allow the field to do his break like action.

**Comment by fmontes** [comment]
Login as error making the dialog too big

**Comment by bryanboza** [comment]
We need to fix some minor problems here: 
- **Login as**: When you try to login as an admin user this dialog request for a password, if you type a wrong password we shows an error here, If you change again your selection we need to update this and clear the error. 
SC: https://screencast.com/t/7Du8YGYIcc

- **Add to bundle:** If the list is empty, we need to remove the drop down symbol 
SC: https://screencast.com/t/2eW9UYNo

- **My Account:** The error message don't have the correct error format
SC: https://screencast.com/t/jU4n9Do23

- **Theme selector:** We need to avoid change the modal size when you filter 
SC: https://screencast.com/t/BuXlxO8X

- **Content Search:**  We are unable to reorder contents we have a js error.
SC: https://screencast.com/t/ncSc04MY5QO

**Comment by fmontes** [comment]
1. Login as: fixed
2. Add to bundle: that's an UX call, please ask to @fishsmith and if he's ok create an issue so I can prioritize it.
3. My account: This message came from the backend, create an issue and ask @dsilvam or @jgambarios to se who can tackle that down
4. Theme selector: fixed
5. Content search: that's a jsp issue, please create an issue so I can prioritize it.

**Comment by bryanboza** [comment]
Fixed, the last problems were reported in separate cards.
