### ISSUE TITLE
Add Widget Search doesn't return correct results

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15397]
In the Add Widget dialogue if you type in multiple words it looks like it returns all widgets of that type, even ones that don't have either of the words in the search box.

## Steps to Reproduce (for bugs)
1. Navigate to a Page in Edit Mode
2.Select Add Widget
3. In 4.3.3 select a widget type and enter two words into the search box or in 5.x select a widget type and enter two words into the title box
4.In both cases the results will be all widgets of that type whether or not they contain any of the words that were entered.

* dotCMS version used: 4.3.3, 5.0.2

**Comment by jtesser** [comment]
@mattyarbrough is working to video this etc..

**Comment by mattyarbrough** [comment]
Video replication: https://drive.google.com/file/d/171XvfoVFh9YFeBBh5mDXnzXsEJ85mS_e/view?usp=sharing

What I believe is happening is that the search is matching on the space character.
