### ISSUE TITLE
Containers that have velocity errors causes 500 error in edit mode

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#15395]
If a container has bad velocity code or bad link to a VTL and you try to open it in edit mode you get an:

"Unknown Error"
"Unfortunately there was an error. Please try again, and if the error persists, please contact support."

If you hit the page from the front end you get a 500 Error

## Expected Behavior
The page should render in edit mode but the container should have a warning in it that the velocity has an error.

## Known Workarounds
Don't write bad code

## Steps to Reproduce (for bugs)
1. Edit a container and add bad velocity code
2. Open a page in edit mode 
3. Add the container tot he page
4. Save the layout and return to edit content. You should see the error

```
#dotParse("/asdasdasdasd")
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15454

**Comment by dsilvam** [comment]
Passed internal QA: No 500 error from frontend and no error in edit mode. We might want to show a error message in the area of the faulty container, though.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the error in the last master

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.0.3
