### ISSUE TITLE
Notifications broken - was "Need update the site selector when you add//remove sites" 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15400]
When you add or remove some site, we need to update the site selector in order to add or remove from the list. 

## Expected Behavior
If you add a new site we need to add the component list 
If you remove we need to remove from the component list 

## Current Behavior
We are not updating this component at all 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Go to sites 
3. Add a new site 
4. Make sure the site has been added to the site list in the site selector 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
Related to changes made in https://github.com/dotcms/core/issues/14966 and fixed in https://github.com/dotCMS/core/pull/15407

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF now it is working as expected

**Comment by bryanboza** [comment]
We are having problems here, we are not updating the site selector when you add a new blank site

**Comment by fmontes** [comment]
Fixed in 5.1, not going to be make it into 5.1

**Comment by fabrizzio-dotCMS** [comment]
This has been already fixed. It behaving as expected.

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Oracle // FF and now this works as expected
