### ISSUE TITLE
Implement "Relationship field" in content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15415]
As a user I want to be able to add relationship fields to my content types

## Expected Behavior
User should be able to drag and drop a relationship field and fill fields to add it to the content type

## Current Behavior
Not implemented

## Mocks
![Screen Shot 2018-10-11 at 9.50.36 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/aa794fb1-2cee-416f-9de6-742a33107024)

![Screen Shot 2018-10-11 at 10.03.50 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/98eb0bf2-d8a3-4b37-b7c5-a64a6a4f0ec7)

## Endpoints
Get the existing relationships: `http://localhost:8080/api/v1/relationships?contentTypeId=XXXXXX`

## Relationship field object

```
clazz: "com.dotcms.contenttype.model.field.RelationshipField"
contentTypeId: XXXXX
indexed: true // always
listed: boolean
name: string
required: boolean
searchable: boolean
sortOrder: number
values: number // One to Many = 0, Many to Many = 1, One to One = 2
relationType: string // velocityVar of the content type you want to relate to but if the relationship existe we should send: "contentType1.contentType2"
```

## Acceptance Criteria

1. Match the design
2. Drag and drop field, fill the form and save
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by hmoreras** [comment]
When editing the field, and check the `required` property if fails the save.

**Comment by bryanboza** [comment]
We need move to use the new v2 of the field resource. Related to #15648

**Comment by bryanboza** [comment]
Here the SC: https://screencast.com/t/W2vuZzijNN0

**Comment by bryanboza** [comment]
Fixed, now we are using the v2 of the resource.

**Comment by fmontes** [comment]
we need to figure it out this: https://github.com/dotCMS/core/issues/15840 in the UI.

**Comment by fmontes** [comment]
CSS style the disabled content types hover state. Is failing.
