### ISSUE TITLE
Session expiration  problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15412]
We are having session problems in the last master, we continuously are losing the session and the redirect to the login page isn't totally working. 

## Expected Behavior
We need to be able to keep the session active the time of your configuration 
```
<session-config>
        <session-timeout>30</session-timeout>
    </session-config>
```

## Current Behavior
We continually lose the session and is redirect to the login page
SC: https://screencast.com/t/krOlymF2z

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
I think you were requesting pages cross domain?

**Comment by wezell** [comment]
this is happening b/c of the new DefaultBackEndLoginRequiredWebInterceptor - though I am not sure why the ws impl would not keep the session open.
```
16:19:47.984  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /c/portal/layout?p_l_id=b7ab5d3c-5ee0-4195-a17e-8f5579d718dd&p_p_id=site-browser&p_p_action=0&&dm_rlout=1&r=1539629002654&in_frame=true&frame=detailFrame&container=true&angularCurrentPortlet=site-browser
```
