### ISSUE TITLE
Host content type needs to be fixed

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15410]
On our demo and starter, the `host` content type got switched to live on the demo host?
1. the `host` structure has both system and fixed checked in the db.  How could it be changed?
2. we need to enforce the `host` content type to only allow it to live on `SYSTEM_HOST`
3.  Language Variable
4. File Asset

We need to insure that system and `fixed` types can never be moved off the `SYSTEM_HOST`
All of these except "Comments" we need to get rid of the "fixed" on comments.
```
       name        | fixed | system |                 host                 
-------------------+-------+--------+--------------------------------------
 Language Variable | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Vanity URL        | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Event             | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Comments          | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 File Asset        | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Forms             | t     | t      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Host              | t     | t      | 48190c8c-42c4-46af-8d1a-0cd5db894797
 Page Asset        | t     | f      | 48190c8c-42c4-46af-8d1a-0cd5db894797
```

**Comment by DrDizzle** [comment]
Also relevant to other "system" content types: Language Variable, File Asset, etc.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15491/files

**Comment by dsilvam** [comment]
Reverting change: https://github.com/dotCMS/core/pull/15498

**Comment by dsilvam** [comment]
PR last fix: https://github.com/dotCMS/core/pull/15499

**Comment by bryanboza** [comment]
Fixed, now the host content type is fixed in the database and live on system host. 

Here the list of the fixed content types and live on system host.
```
        name        | fixed | system |    host     
-------------------+-------+--------+-------------
 Page Asset        | t     | f      | SYSTEM_HOST
 Host              | t     | t      | SYSTEM_HOST
 Forms             | t     | t      | SYSTEM_HOST
 File Asset        | t     | f      | SYSTEM_HOST
 Comments          | t     | f      | SYSTEM_HOST
 Event             | t     | f      | SYSTEM_HOST
 Vanity URL        | t     | f      | SYSTEM_HOST
 Language Variable | t     | f      | SYSTEM_HOST
```

**Comment by wezell** [comment]
comments should not be fixed.

**Comment by bryanboza** [comment]
ok, then we need some work here

**Comment by dsilvam** [comment]
Comments won't be fixed after you upgrade. For fresh install we need to change the starter. In your local you can fix but re-saving comments type. It will be moved to system_host @bryanboza @wezell

**Comment by dsilvam** [comment]
@bryanboza new starter uploaded. You should see comments as not-fixed now. Make sure new starter gets pulled when building
