### ISSUE TITLE
If detail page does not exist for url mapped page, content fails to index

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15423]
If you have a structure that references a detail page that does not exist in the system, the content of that structure cannot be indexed as the getUrlMap method throws an error that is not properly handled by the reindexer - see this:

https://gist.github.com/wezell/97e348cfee48500d3e74707bc9e75f23

**Comment by wezell** [comment]
I have a starter.zip that shows this behavior.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15463

**Comment by dsilvam** [comment]
**Passed internal QA:** Created content type with non existing detail-page (edited 'page_detail' field straight on db column, flushed cache), created three pieces of content of that type and then reindex. 
Got warnings about not able to find the URLMap 

```WARN  business.ESMappingAPIImpl - Cannot get URLMap for structure : type3 and contentlet.id : 265b85a4-1c74-4bc2-bfd1-6d4f7fa4a3a4 , reason: Can't find contentlet: non-existing-page lang:1 live:false```

**but Reindex process completed**

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3, now I'm unable to reproduce, this since now we discard the changes if the detail page doesn't match with  one of the autocomplete options

**Comment by bryanboza** [comment]
the same behavior of 5.0.3 on master
