### ISSUE TITLE
UX: The cancel button isn't closing the modal at the first click adding a new field to content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15428]
When you click on the cancel button the system is validating the required fields in the form instead close the modal, this on the first click, in the second one we close the modal 
 
## Expected Behavior
If you click on the cancel button we need to close the modal at the first click

## Current Behavior
When you click on cancel we are validating the fields of the modal and not closing this one 
SC: https://screencast.com/t/Q0lav0ui
 
## Steps to Reproduce (for bugs)
1. Login as admin  
2. Go to content types and create a new one 
3. Add a new field
4. Without add info click in the cancel button 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
fixed
