### ISSUE TITLE
[Content] The 'Redirect URL' property when creating a custom Page Content Type is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15427]
Reproducible in dotCMS 4.4.1, and latest master.
Reported by customer via Support: https://dotcms.zendesk.com/agent/tickets/96789

When you create your own custom Page Content Type, the field called `Redirect URL` is not working at all.

## Expected Behavior
Content authors should be able to use the `Redirect URL` in their custom Page Content Type.

## Current Behavior
The field is not working in a custom Page Content Type.

## Possible Solution
The `Redirect URL` field is a custom field, created by this VTL: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/WEB-INF/velocity/static/htmlpage_assets/redirect_custom_field.vtl#L7 . Notice how the column name is hard-coded.

## Known Workarounds
None at the moment.

## Steps to Reproduce (for bugs)
1. Create a custom Page Content Type, called "My Page CT".
2. Create a new HTML Page using the "My Page CT" Content Type.
3. Add some content to it, and check that you can load it in an incognito window.
4. Add a valid page reference to the `Redirect URL` field, and click Save / Publish.
5. Load the page in the incognito window. The page does not redirect anywhere.

## Your Environment
* dotCMS version used: 4.4.1, latest master
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Management.

**Comment by jcastro-dotcms** [comment]
Reported by one more customer: https://dotcms.zendesk.com/agent/tickets/97336

This is also reproducible in our Demo Site (v5.0.3)

**Comment by craigWagner99** [comment]
I made the change suggested in https://github.com/dotCMS/core/issues/15814

changing the "onchange" to "onChange" in the file

\dotserver\tomcat-8.5.32\webapps\ROOT\WEB-INF\velocity\static\htmlpage_assets\redirect_custom_field.vtl

And the redirects seem to be working and saving.

Is this valid or will this break other stuff?

**Comment by oarrietadotcms** [comment]
Still reproducible in demo (5.2.1)

Also another client hit this in 5.1.6: https://dotcms.zendesk.com/agent/tickets/99854

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17800

**Comment by bryanboza** [comment]
We need some work here: 
- If you remove this redirect value, we need to clean this from the cache because after delete we continue redirecting 

- We need to include the site value here, this because we are allowing select pages from different sites and we are not including that value, if you select some page from a site different to the default, we are trying to resolve this path with the default site.

**Comment by erickgonzalez** [comment]
@bryanboza the cache is been cleaned since when you save it creates a new version of the page, I guess you are still getting the redirect because of the browser cache

**Comment by jcastro-dotcms** [comment]
IMO, flushing the browser's cache should not be the fix here. We need to investigate why the URL isbeing cached like that.

**Comment by wezell** [comment]
The redirect is a 301, which Chrome caches aggressively.  Different clients have different needs here  - including issac - and we have switched it back and forth over the years of dotCMS's history but the current behavior has not changed since the 3 series:

https://github.com/dotCMS/core/blob/3.7.2/src/com/dotmarketing/services/PageServices.java#L333-L336

**Comment by wezell** [comment]
Regarding the URL - if you need to redirect to another site or to google.com or whatever, you can type the full url in the box.  It works exactly like our vanity urls work and is the same control.  

We should not do more to the control until we replace it with a web component.

**Comment by jcastro-dotcms** [comment]
In that case, @john-thomas-dotcms can we add this to the doc please? So that customers know that they need to flush their browser's cache when/if they update the redirect value

**Comment by bryanboza** [comment]
Ok, according to the @wezell comments that's ok for now... Passed QA

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/page-advanced-properties#Advanced
