### ISSUE TITLE
Remove forced table locks from reindex process

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15421]
When we reindex we force a table lock on the `dist_reindex_journal`  (and in mysql some other tables). We need to remove this locking logic and come up with a way to insure that a cluster fires a renidex once and then performs the cutover switch once.

With our current pattern of saving content using the `dist_reindex_journal` for all deferred content, basically the system will stop allowing content saves while a reindex is being setup or switched.

I'd like to see the lock and unlock clusters completely removed from the ReindexThread and we engineer another way forward.

DB locked up:

https://gist.github.com/wezell/ac22bcb1903abb2a9a321c6005ef3461

**Comment by nollymar** [comment]
Fixed on #16277

**Comment by dsilvam** [comment]
Passed Internal QA: Able to reindex properly with client's dataset

**Comment by bryanboza** [comment]
Fixed, tested reindexing multiple times to make sure everything works as expected and everything works normally
