### ISSUE TITLE
Add relationship2 support to ContentMap (velocity) object

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15424]
The ContentMap object is what is uses across velocity and needs to support the new relationship field.

When a relationship field is called in velocity, we need to lazy load the List<ContentletMap> relationship data into the map and return it for use in velocity.

**Comment by wezell** [comment]
We need to transform the returned content to ContentMap objects.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15662

**Comment by erickgonzalez** [comment]
Working as it should.

Test:
1- Create 2 Content Types with Text Field
2- Add the new Relationship Field to one content type(the child will be the other one)
3- Create 2 contents and related them.
4- Create a simple widget and use the **contentTool.find(identifier)** to get the content
5- Add the widget to a page
6- The widget should return the whole content, inside it must be a ContentMap with the related content (you can get only this by passing the field variable **contentTool.find(id).variableName()**

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF.  Tested with the last comment.
