### ISSUE TITLE
Support multipart in VTLResource

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15433]
Support uploading files. The challenge here is creating a new contentlet that has multiple files associated with it and knowing which multipart item to associate with which file.

For example, you have a content type with 5 binary fields and you only want to upload into the 2 and 5 fields.

I guess we will just get all the mutlparts as a list in velocity and the user can do whatever they want to with it.

Also, how do we handle updates vs. a nulling out?  

Field is called "image"

imageAction=MAINTAIN/DELETE

**Comment by dsilvam** [comment]
To send and upload binaries in a multipart request to the Lightweight Resource, a list of binaries (var names of the field) under the name "binaryFields" needs to be include as a field in the json body (first part). These elements will try to match the following binary parts in the multipart by order, so if you include only one element, it will match the following part, two elements the following two parts and so on. If you include one element without its corresponding part, it will be treated as a delete (if existed before) 

This is our provided implementation. Users are free to implement the upload of binaries in a different way if desired/needed.

Example of different request types: 

```
POST / CREATE

curl -v -u admin@dotcms.com:admin -POST http://localhost:8080/api/vtl/employees -F "json={
   "contentType":"Employee",
   "languageId":1,
   "host1":"demo.dotcms.com",
   "firstName":"Daniel3",
   "lastName": "Silva3",
   "jobTitle": "Dev",
   "email": "daniel.silva@dotcms.com",
   "mobile": "8325553355", 
   "gender": "male",
   "binaryFields": [ "photo", "photo2" ]};
   type=application/json" -F "file=@/Users/danielsilva/Downloads/firstFile.jpg; type=application/jpg" -F "file=@/Users/danielsilva/Downloads/secondFile.jpg; type=application/jpg"
   
PUT / UPDATE TOTALLY

curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/vtl/employees -F "json={
   "identifier":"af047c97-1a91-4642-9cbb-2fbdef4da1cb",
   "contentType":"Employee",
   "languageId":1,
   "host1":"demo.dotcms.com",
   "firstName":"Daniel2",
   "lastName": "Silva2",
   "jobTitle": "Dev",
   "email": "daniel.silva@dotcms.com",
   "mobile": "8325553355", 
   "gender": "male",
   "binaryFields": [ "photo", "photo2" ]};
   type=application/json" -F "file=@/Users/danielsilva/Downloads/testImages/testImage1.jpg; type=application/jpg" -F "file=@/Users/danielsilva/Downloads/secondFile.jpg; type=application/jpg"
   
PATCH / UPDATE PARTIALLY

curl -v -u admin@dotcms.com:admin -XPATCH http://localhost:8080/api/vtl/employees/af047c97-1a91-4642-9cbb-2fbdef4da1cb -F "json={
   "lastName": "Silva Patched",
   "jobTitle": "Dev Patched",
   "binaryFields": [ "photo2" ]};
   type=application/json" -F "file=@/Users/danielsilva/Downloads/secondFile.jpg; type=application/jpg"   
```

**Comment by erickgonzalez** [comment]
Needs Work: 

When passing a bad identifier throws a **500 {"message":null}**  should throw a 404.

**Comment by DeanGonzalez** [comment]
Documented: https://auth5.dotcms.com/docs/latest/scripted-endpoints#sendingFiles
