### ISSUE TITLE
Push publishing related content is not working

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15435]
Log error on the sender: https://gist.github.com/nollymar/db732c768761aaa74593b67c24b6a0ea

Steps to reproduce:

1. Add a relationship between Content Generic (parent) and YouTube (child)
2. Create a new piece of content generic and relate to any Youtube content
3. Try to push the piece of content

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15465

**Comment by nollymar** [comment]
This fix applies for https://github.com/dotCMS/core/issues/15462 as well

**Comment by nollymar** [comment]
Tested on master and now it's working fine

**Comment by bryanboza** [comment]
Unable to reproduce in the last master, now is working as expected
