### ISSUE TITLE
Saving new Events is not refreshing the History and Permissions tabs

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15439]
When a new content is saved and only for **Events** the _History_ and _Permissions_ tabs are not refreshed.
Those tabs are refreshed and work properly with any other content type.

**Comment by fabrizzio-dotCMS** [comment]
Somehow this thing is working properly again.

**Comment by fabrizzio-dotCMS** [comment]
As far as I can see (somehow) this thing is working properly.. I've tried to reproduce the error reported but it seems to be fine.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15610

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15644

**Comment by bryanboza** [comment]
Fixed, tested on master Oracle // FF
