### ISSUE TITLE
Login redirect isn't working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15437]
When your session expires the redirect isn't working

## Expected Behavior
We need to redirect the entire page to the login page 

## Current Behavior
We are reloading the login page into the iframe 
SC: https://screencast.com/t/e7Eh7s00DA2O

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Delete the session cookies 
3. Try to navigate to another portlet 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/15371

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 and now it is working fine. Need retest after fix #15371

**Comment by bryanboza** [comment]
Fixed, retested on master and now it's working as expected.
