### ISSUE TITLE
User not reaching viewtool when coming from VTLResource 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15438]
- [x] Needs to be reachable from tool's init method. 
- [x] Write WorkflowTool init method
- [x] Change WorkflowTool scope to request

Acceptance criteria
- [ ] Auth/User included in GET and POST requests to VTLResource are properly used by tools

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15445

**Comment by DeanGonzalez** [comment]
User permissions are respected in the request to the tool
