### ISSUE TITLE
Problem creating bundle from Rules Engine Portlet

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#15444]
Client ticket: https://dotcms.zendesk.com/agent/tickets/96773

## Known Workarounds
None. 

## Steps to Reproduce (for bugs)

1. Create 3 Rules. ("Rule 1", "Rule 2", "Rule 3")
2. Add each rule to a new bundle. ("Bundle 1", "Bundle 2", "Bundle 3")

Bug 1: "Add to Bundle" dialog will only display 1 bundle name to choose. Even when there are 2 or more.
Bug 2:  User won't be able to create "Bundle 3". Each time the autocomplete feature will replace the new name with a name that already exist. 

## Your Environment
* dotCMS version used: 5.0.2 (demo), 4.3.3 (client version)

**Comment by cvanolinda** [comment]
We did find a workaround for this issue. If you open a new tab between each step, you won't have any issues creating or adding assets to either one or seeing all available bundles.

**Comment by bryanboza** [comment]
Fixed, tested on release 5.0.3 and now I'm able to add rules to bundles without problems

**Comment by bryanboza** [comment]
We continue with the autocomplete problem, now after deleting existing bundles.
SC: https://screencast.com/t/6rzoczBgeW

To reproduce: 
- Login as admin 
- Create  3 rules 
- Add every rule to a different bundle
- Now go to publish queue--> bundles and delete all the bundles
- Try to add the rule to a different bundle again

**Comment by wezell** [comment]
@bryanboza We can hold this case for 5.1 - where we will need good qa on the redone and upgraded rules.

**Comment by bryanboza** [comment]
unable to test because we are having problems trying to see the bundles. We have an error in the JSP file and we can't see the bundles 
SC: https://gist.github.com/bryanboza/9e9e935337e22a191d4651b8ef6f3b9d

**Comment by alfredo-dotcms** [comment]
not able to reproduce
https://monosnap.com/file/24e9ns18iUJRLx56KXDr9e20qetkGG

**Comment by bryanboza** [comment]
ok, seems the problem is the way that we are sending the rules to the bundle because if in a clear instance you create a new bundle of any piece of content, you are able to see the bundle from the publish queue without problems, and after creating a new bundle of a rule we have the problem.
Here the video: https://screencast.com/t/vz0i6UQBV

**Comment by hmoreras** [comment]
last comment of @bryanboza is working now.
