### ISSUE TITLE
Device Type Preview not loading properly for Limited Users on Windows 10

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15442]
Tested on dotCMS 5.02 running on Windows 10 on Edge and Chrome

Device Type Preview not loading properly for Limited Users on Windows 10, even though that limited user has cascaded full rights to everything on the host.  I tested both Demo site and secondary hosts and starter themes and new themes.  Works fine for admin, but not users who are non-CMS admin.

https://www.screencast.com/t/RsOuPUa0bbz

https://www.screencast.com/t/NQklHcB6

**Comment by fmontes** [comment]
Close https://github.com/dotCMS/core/issues/15474
