### ISSUE TITLE
Limited User Unable to reorder menu when page locked by another user

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15450]
1. Log in as limited user 1 and edit and lock a page for editing
2. Log in as limited user 2 and try to reorder the menu
This throws an error

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15452

**Comment by bryanboza** [comment]
We have a JS error saving the changes and now we are unable to come back to the page preview. We need some work here 
SC:  https://screencast.com/t/7PQz7BrNgGh

**Comment by fmontes** [comment]
Fixed here: https://github.com/dotCMS/core-web/pull/841

**Comment by bryanboza** [comment]
We are unable to reorder the menu: https://screencast.com/t/Ed2czSQ6YU

**Comment by erickgonzalez** [comment]
@bryanboza I do not see the **#orderMenu** issue that you show on the SC, can you double check it?
But I see an issue with the redirect after the menu reorders, it always redirects me to the **index** page.

**Comment by erickgonzalez** [comment]
Scratch my last comment, tested on release-5.0.3 and it's working fine.

**Comment by bryanboza** [comment]
Fixed, tested in the last release-5.0.3 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
