### ISSUE TITLE
Make listing-data-table.component navegable with keyboard

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15455]
As a stakeholder I want to make sure our components have the best experience and accessibility as possible.

## Acceptance Criteria

1. Replace all p-dataTable (is deprecated) and use the new [TurboTable component](https://www.primefaces.org/primeng/#/table/edit)
2. Make sure the table is "navegable" with keyboard, it meas that if the table is focus and user press up and down it should select the rows accordingly and if user hit enter it should call the action of "click" in the row, new table component have this [option](https://www.primefaces.org/primeng/#/table/selection)
3. Rows on hover should have 0.1 opacity of the primary color
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
the feature to navigate with keyboard key is on primeNg >= 7, at this moment it's on a `beta release` and some compile errors appears on `dotcms-js` (probably related with the current version of ng 6)

**Comment by fmontes** [comment]
release 6.1.7 still nothing.

**Comment by fmontes** [comment]
Waiting for primeng 7

**Comment by fmontes** [comment]
1. If we're in the filter and hit down we should start selecting rows
2. Improve listing table loading state

**Comment by fmontes** [comment]
Pagination is not working as expected, [this harcoded](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/listing-data-table/listing-data-table.component.html#L19) is breaking it... we need to fix it and add a unit test for it.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
