### ISSUE TITLE
[Content Management] The close icon of the Available Workflow Actions modal is not visible in low resolution screens

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15468]
Reproducible in demo running dotCMS 5.0.2
Reported by customer via Support: https://dotcms.zendesk.com/agent/tickets/96805

## Expected Behavior
The close icon of the modal needs to be visible in low resolution screens.

## Current Behavior
The icon is not visible. When the dialog is dragged down to a visible position, it returns up to the original location.

## Possible Solution
Not available. Maybe a code change can be included to close the modal when the user hits the "Escape" key as well.

## Known Workarounds
Increase the screen's resolution.

## Steps to Reproduce (for bugs)
1. Log into dotCMS.
2. Go to the **Content Search** portlet.
3. Set your screen's resolution to 1366 x 768 or lower, or resize your browser to a similar resolution.
4. Check any contentlet, and click the **Available Workflow Actions** button. Notice how the close button is not reachable.

## Your Environment
* dotCMS version used: dotCMS 5.0.2
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Search.

![no close icon](https://user-images.githubusercontent.com/934364/49239470-d8bfdd80-f3d0-11e8-9081-b145c2e0454b.JPG)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15632

**Comment by bryanboza** [comment]
Fixed, tested on my extra monitor in the minimum resolutions and now I'm able to see the icons without problems
