### ISSUE TITLE
Relationships: Deleting related content leave the Contentlet Cache dirty 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15462]
When a related content is deleted, its title is shown as "null" on the Site Search until the cache is flushed.

https://www.screencast.com/t/g7uxakvdDT

It might be related to recent changes on IndexPolicy. After debugging, the cache is messed up when this line https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L2529 is executed 

## Expected Behavior
Related content should not be altered if it is removed from a relationship 

## Known Workarounds

Flush cache 

## Steps to Reproduce (for bugs)
![delete_relationships](https://user-images.githubusercontent.com/8741395/47231427-75369f00-d392-11e8-8e7d-20a72922b1bf.gif)

## Your Environment

* dotCMS version used: master
* Browser Name and version: Google Chrome

**Comment by nollymar** [comment]
Related to https://github.com/dotCMS/core/issues/15435

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/15465

**Comment by nollymar** [comment]
Tested again and it's working fine after fix.

**Comment by bryanboza** [comment]
fixed, tested on master  // Oracle // FF
