### ISSUE TITLE
Improve content search lisiting in edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15473]
As a stakeholder I want to make sure users have the best experience they can when adding content to a page.

## Acceptance Criteria
1. Select button:
    - [ ] Move to the right final column
    - [ ] Add the "secondary" styling (check the parent library in angular)
2. Table:
    - [ ] Add the title/name column to the first column
    - [ ] Add thumbnail when the contentlet is a media type (image or video)
    - [ ] Check if we can add a thumbnail with the first binary or image fields of a contentlet
    - [ ] When you can't add a thumbnail use the content type icon (check content search "All" to see them)
3. Search:
    - [ ] Add a global search input text field when user select "all" in the dropdown, just like in the original content search portlet.
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by jgambarios** [comment]
Merged: https://github.com/dotCMS/core/pull/15510

**Comment by fmontes** [comment]
![screen_shot_2018-12-13_at_9 04 00_am-1](https://user-images.githubusercontent.com/751424/49947276-724dbb80-feb6-11e8-8f0d-f785b48a74d2.png)

**Comment by alfredo-dotcms** [comment]
@freddyucv issues found:

![image](https://user-images.githubusercontent.com/37185433/50229042-00bab500-036f-11e9-96c3-2ab0aa8e14ac.png)

**Comment by fmontes** [comment]
@nollymar is adding a comment about errors in the relationship.

**Comment by nollymar** [comment]
This change breaks the relationship tab. It is not possible to add related content when there are more than one relationship in a content type, the content popup only shows up for the first relationship (with broken icons) but not for the others. 

![js_error_relationships](https://user-images.githubusercontent.com/8741395/50664675-e7735480-0f7b-11e9-8327-bdbc8ebbc07a.gif)

These errors are displayed in the JS Console: https://www.screencast.com/t/HYmUyHC7

**Comment by fmontes** [comment]
According to @nollymar this rollback [this commit](https://github.com/dotCMS/core/commit/7665313dfb38699e1bef58a457a52ef4f2bae44f#diff-660d421b5d11ca5b54e330c4d44feed9) fix the issue

**Comment by nollymar** [comment]
Now, it's working correctly

**Comment by bryanboza** [comment]
We need to auto update the result when you change any value in the filter, as we do in previous versions. 
SC: https://screencast.com/t/BMAcVXte
FYI: Tested on demo and works as expected.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
