### ISSUE TITLE
Feature Request: Lock pages during approval workflow

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15472]
Currently when a contentlet is in a review/approval workflow stage it can still be edited.  Client is asking to have the ability to preventing editing when content is in a particular workflow stage.

**Comment by wezell** [comment]
@mattyarbrough this is configurable in your workflow steps - meaning, don't unlock the content when you define your workflow scheme

**Comment by asifanoor** [comment]
If we don't add unlock content and content is locked, publisher is unable to publish it. 
Publisher gets the message, unable to execute workflow, only admin or user who locked the content can unlock it.
