### ISSUE TITLE
Site Search Job fails and dies

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15475]
Running a new site search can fail - throwing an unhandled exception that kills the job.  It seems that tika is missing classes that it needs.  So we need to
1. Make sure tika has the classes it needs
2. Make sure that we catch the exception, log it and proceed to finish the site search.
3. This is the file it is blowing up on: `/blog/rss-feed`, which makes sense given the errors below.

This is from my local running dotcms.com : 
https://gist.github.com/wezell/d962eb77b6f424d1be3ea122354763d0

This is from dotcms.com : 
https://gist.github.com/wezell/0ab7addae4904378d04f17b61f04adf9

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15492

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.0.3

**Comment by bryanboza** [comment]
Unable to reproduce on master
