### ISSUE TITLE
UI doesn't degrade gracefully for site browser

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15471]
In resolution of 1366 * 768 or less if you expand the contents of the site browser they will extend past the bottom of the div and it's not possible to scroll down to them.

This has been replicated on demo.dotcms.com

**Comment by wezell** [comment]
![screen shot 2018-11-29 at 12 19 37 pm](https://user-images.githubusercontent.com/934364/49239714-70253080-f3d1-11e8-8084-05a587953d6c.png)

**Comment by alfredo-dotcms** [comment]
@hmoreras now we are able to see all the folder, but there's a white space if the browser is resized

https://monosnap.com/file/OOWVYqTVpxLX9An8J8LBAx9GbQ6TLH

**Comment by mattyarbrough** [comment]
Note possible related issue with the vertical scroll bar not existing on Edit Page, see video here:

https://drive.google.com/file/d/1Ym9SPcCz-aC1QIFf5HzRIuq2NTcdY9M2/view?usp=sharing

**Comment by fmontes** [comment]
@mattyarbrough But in the modern browsers we don't have scrollbard... or am I missing something?

**Comment by fmontes** [comment]
@alfredo-dotcms as per @wezell we're not doing that fix right now.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by dsolistorres** [comment]
Hotfix for 5.0.3
[hotfix-GIT-15471_v5.0.3.zip](https://github.com/dotCMS/core/files/2978894/hotfix-GIT-15471_v5.0.3.zip)
