### ISSUE TITLE
Device preview does not work with Limited User

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15474]
Only visible on latest version in Firefox on Windows 10 (chrome works fine)

To test on PC, running windows 10, using latest Firefox

1) Create a limited user with view to the host and then complete rights to all child objects on that host.
2) Edit one of the pages and try to device type preview.  The bug is that the device type preview fails on load attempt, and returns user back to the page before the device type preview attempt.

**Comment by jgambarios** [comment]
PR:
release-5.0.3 -> https://github.com/dotCMS/core/pull/15488
master -> https://github.com/dotCMS/core/pull/15495

**Comment by wezell** [comment]
We need to update starter with the correct permissions.

**Comment by bryanboza** [comment]
ok, after the last changes we need to set permissions to every limited user on all the devices to allow the preview, if you don't set the permissions to the devices the "device" drop-down will appear disabled. 

Tested on release-5.0.3 // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15533

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle.
