### ISSUE TITLE
PersonaTool getPersonas() does not work on FE with unauthenticated user

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#15484]
As stated in the title

The problem is https://github.com/dotCMS/core/blob/5.0.2/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/PersonaTool.java#L117
Changing the last parameter to true should fix the issue

**Comment by dsolistorres** [comment]
Attached hotfix for 5.0.1:
[hotfix-GIT-15484_v.5.0.1.zip](https://github.com/dotCMS/core/files/2536677/hotfix-GIT-15484_v.5.0.1.zip)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15490

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 trying to use the view-tool from the front end as an anonymous user, and now we return the collections of persona objects.

**Comment by bryanboza** [comment]
Fixed, now we are able to use the view tool without problems on master too. Tested with the last master code
