### ISSUE TITLE
Add widget listing in edit page is not respecting sorting

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15486]
As a user I want to sort the listing by any of the columns and that pagination respect that sorting.

## Expected Behavior
When user sort the table listing and the paginate, the sort order should remain the same

## Current Behavior
When user paginate the sort order mess up

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)

1. Edit a page
2. Select to add a widget
3. Sort the table listing by any of the column (title)
4. Paginate with the button at the bottom
5. Sort order mess up.

## Acceptance Criteria

1. User should be able to sort and paginate without changing the results sorted
2. Move language and select button column to the right: `Title | Author | Step | Lang | Button`
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by alfredo-dotcms** [comment]
this seems to be `BE`, when you click on any column title and any button from the pagination, the selected column params are being sent in the request. So there could be an issue in the query that is being done to sort by `title`.

Note: Sort seems to be working for the other columns

**Comment by alfredo-dotcms** [comment]
might be related to https://github.com/dotCMS/core/issues/15473#issuecomment-448631544
