### ISSUE TITLE
es/search API isn't returning pages if are on the root of the site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15482]
This API is used in the autocomplete of the detail page, and we are not returning the pages that are located in the root of the site. 
API: http://localhost:8080/api/es/search

## Expected Behavior

- [ ] When you made the POST we need to return a complete list of pages that have consistency with the parameter. 

- [ ] Also, we need to be able to use multiple sites, on the Detail Page query on content types, we always are sending the localhost. 

## Current Behavior
We ignore the pages that are located in the root of the site 

## Steps to Reproduce (for bugs)
1. Create a new page under the root of the site 
2. Create a new content type and in the detail page try to use the created page 
3. Make sure the autocomplete is including that page in the list of returned options. 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
I think that this search is not as effective as it could/should be.  We are forcing the use of the the host that is selected for the content type which is not obvious.  We should search all hosts and prepend the suggested urls with the host name (we can boost the selected host to the top so those suggestions come first. Also the search should be wildcarded on both sides.  A very near example of how this search should work is how the filesearch works in github.

**Comment by wezell** [comment]
Looking at the code, we need to query by the path (which includes the page), not the parent path.  We should also make the host optional as you can have a detail page that is not on the host you are on.

```js
    /**
     * Get all the pages in the folder
     *
     * @param string searchParam
     * @returns Observable<DotPageAsset[]>
     * @memberof DotPageSelectorService
     */
    getPagesInFolder(searchParam: string, hostId?: string): Observable<DotPageAsset[]> {
        console.log(searchParam);
        const parsedQuery = this.parseQueryString(searchParam);

        let query = `+basetype:5 +path:*${parsedQuery[0]}*`;
        query += parsedQuery.length > 1
            ? ` conhostName:*${parsedQuery[1]}*`
            : hostId
                ? ` conhost:${hostId}`
                : '';
        console.log(query);
        return this.coreWebService
            .requestView({
                body: {
                    query: {
                        query_string: {
                            query: query
                        }
                    }
                },
                method: RequestMethod.Post,
                url: 'es/search'
            })
            .pipe(pluck('contentlets'));
    }

    parseQueryString(searchQuery: string) {
        searchQuery = searchQuery.replace(/\//g, '\\/');
        const returnVal = new Array();
        if (searchQuery.split(':').length > 1) {
            returnVal[0] = searchQuery.split(':')[1];
            returnVal[1] = searchQuery.split(':')[0];
        } else {
            returnVal[0] = searchQuery;
        }
        return returnVal;

    }
```


also, the values the user selects should include the hostname where the page lives.

**Comment by wezell** [comment]
So, for 5.0.3, we will change +parentPath to +path. For 5.1, as discussed with freddy, we need to support hosts in searches like:

//demo.dotcms.com/about-us/index

and add the hostname to the results list so the user can select the proper page.

**Comment by jgambarios** [comment]
**Note for QA:** For 5.0.3 only these changes https://github.com/dotCMS/core-web/commit/2d737b4c82936de7a8b7c7b3cd8c58407c41796b#diff-894948555847344f8ed778900c24e470R44 were included.

**Comment by bryanboza** [comment]
After the fix included on release-5.0.3 we are including the pages of the root of the site, but if you have a multi-language page, we are returning the same result multiple times, one per language
<img width="597" alt="error1" src="https://user-images.githubusercontent.com/2641437/48277912-a6464480-e411-11e8-80ba-87cf1b0d81bf.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15529

**Comment by hmoreras** [comment]
Can't reproduce the last comment of Bryan, were was showing one result per language.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we don't have the problem of my last comment
