### ISSUE TITLE
Content types meta issue

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15493]
## 1. 
Possible to add two field variables with the same key.  The ui should update the one that is there.  Also, what does the save icon do?
![screen shot 2018-11-01 at 9 33 25 am](https://user-images.githubusercontent.com/934364/47854911-6f40b500-ddb9-11e8-901b-170ddd62ea02.png)

## 2. 
Remove dotted line around the +ADD ROW button.  It looks like a drop zone and it is just a button.  Actually, we need to just make it a button and also have the "add tab" button there as well. 
![screen shot 2018-11-01 at 9 39 16 am](https://user-images.githubusercontent.com/934364/47855354-c5622800-ddba-11e8-961e-4a3cfc8c6922.png)

## 3. 
Getting "unknown errors" popup but no errors in the java log.  There are console errors:

![screen shot 2018-11-01 at 9 41 35 am](https://user-images.githubusercontent.com/934364/47855293-951a8980-ddba-11e8-8f70-fef161535e4e.png)
![screen shot 2018-11-01 at 9 42 49 am](https://user-images.githubusercontent.com/934364/47855298-977ce380-ddba-11e8-8565-98fac5b89f88.png)

## 4.
Strange onfocus style on the tab

![screen shot 2018-11-01 at 10 32 25 am](https://user-images.githubusercontent.com/934364/47858059-8daaae80-ddc1-11e8-92b4-8b6ad5997489.png)

**Comment by fmontes** [comment]
1. We need to talk to Fallas about the UX of that thing.

**Comment by fmontes** [comment]
2. Let's use a split button: default action will be add row and the list will say: add row. add tab

**Comment by bryanboza** [comment]
We have some errors after all these changes: 
- When you are editing multiple variables at the same time, when you save the changes in one of those, we save all the changes 
https://screencast.com/t/LAmTXl51HI

**Comment by fmontes** [comment]
Merged and tested.

**Comment by fmontes** [comment]
Fixed renaming tab issue

**Comment by bryanboza** [comment]
If you type a really long name we are unable to remove the tab...
SC: https://screencast.com/t/PnyFKu6jRC

**Comment by bryanboza** [comment]
Fixed, tested on master // oracle // FF
