### ISSUE TITLE
Upgrade the dot-page-selector.component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15509]
As a stakeholder I want to make sure users will be able to select pages per host

## Expected Behavior
When user type: `//hostname.com/` we should search for the page just for that host

## Current Behavior
User can only select pages searching for all hosts.

## Possible Solution
@wezell start work on this here: https://github.com/dotCMS/core-web/pull/833

## Acceptance Criteria

1. User should be able to use the wildcard `//hostname.com/` to select pages into a specific host
2. Results should display the host information
3. When user select with keyboard (ENTER) dialog should not be close (we did that [here](https://github.com/dotCMS/core-web/blob/96b34d57e8641162ea0c1cde1ec30a782da335ee/src/app/view/components/_common/dot-textarea-content/dot-textarea-content.component.ts#L80))
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by fmontes** [comment]
So the flow should be like:

user type `//` we start searching for a host
    - if user type or select a valid host we allow to search for a page
    - if user select the host we complete the host add the last `/` and let the user ready for search for a page
    - if user type an invalid host we show an error message under the field: "Please select or type a valid host" and we don't allow the user to type the page (because we can search for it)

**Comment by hmoreras** [comment]
progress of this, can be found in core-web branch `issue-15509-wild-card-for-dot-page-selector`, and use the core branch `issue-15482-add-conhostname-to-es-mapping` until this is merged https://github.com/dotCMS/core/pull/15529

**Comment by alfredo-dotcms** [comment]
JS issue
https://monosnap.com/file/QKye8YMLucxhQIUOjPsg2cBYr7C36I

**Comment by alfredo-dotcms** [comment]
no results shown when added a `/` in a correct path
https://monosnap.com/file/PMzTtGpMNULGQ2opa1DqMr5q7Ov4qn

**Comment by bryanboza** [comment]
We have a couple of cases here that we need to support: 

- If you type "//" we need to list all the sites in the component, as we do when you type more than two 
SC: https://screencast.com/t/3lJFTc49xLo

- We need to discard stopped and archived sites, right now we are including all the sites and ignore the site status 

- We need to exclude the "System host" from this list since this is a host just for the system.

**Comment by hmoreras** [comment]
this `If you type "//" we need to list all the sites in the component, as we do when you type more than two` will not happen. User need to type at least 3 characters to see host results.

**Comment by fmontes** [comment]
Fix:

1. The user can type as many `////` he want but until we get 3 valid chars we start looking
2. We align and ellipsis long string results.

**Comment by bryanboza** [comment]
- [ ] When you type `//` we need to list all the sites, but after the fix, you need to type five `/////` to see the list.

- [ ] We still including stopped and archived sites in the list

**Comment by hmoreras** [comment]
possible scenarios on search results: 

// <-- first 20 results 
//dem <-- filter by host , all possible results
indes <-- filter by page , all possible results
//xxxx/page <-- filter by host & page, all possible results.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
