### ISSUE TITLE
NPE trying to see the live version of some page with the template archived 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15503]
Related to #15401 

We have an NPE if you try to see the live preview of a page with the selected template was archived. 

## Expected Behavior
After discussing this with the team, we decided that the user is able to unpublish/archive a template that is currently being used. But if the user tries to see the live mode of the page a message **This page cannot be viewed b/c the template is archived.** should be shown.

## Current Behavior
We are allowing archive the template, but when you are editing the page and try to see the live tab, we show an error at UI and NPE on logs. 
UI: https://screencast.com/t/d2S3IXs8R
Logs: https://gist.github.com/bryanboza/8b447faed1f35856303a96fa93f767a2

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new template 
3. Create a new page using the new template 
4. Go to templates again and archive the new one 
5. Try to edit the created page and go to the live tab 

## Your Environment
Tested on release-5.0.3 // Postgres // FF

**Comment by dsilvam** [comment]
This is still happening

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/17005

**Comment by nollymar** [comment]
Tests results: 
* Backend is working as expected: A message is displayed when Live Mode is selected "This page cannot be viewed on Live Mode because the template is unpublished or archived" 
* Frontend: The page is loaded with a different layout. It seems to be using a different template. Is it ok ?

**Comment by wezell** [comment]
Re: Frontend - is it the 404 page?  I think the page should either throw a 404 or a 500.  It should not be rendered at all.

**Comment by nollymar** [comment]
Nope. It is loading the content but using a different template. No error is shown

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
