### ISSUE TITLE
Unable to navigate public pages as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15506]
In the new edit mode, if you are as limited user and try to navigate to some other page, we are showing an error 500 and we are unable to navigate since the public pages have the anonymous permissions, we should be able to navigate on this pages without problems. 

## Expected Behavior
If the page has the anonymous permissions, then this is a public page, I should be able to navigate on it, just need to disable the edit tab. 

## Current Behavior
We show an error 500 and we are unable to navigate 
SC: https://screencast.com/t/mTgDBLxi

## Steps to Reproduce (for bugs)
1. Login as Chris Publisher 
2. Open the resources/index page
3. On edit mode click on the quest logo
4. Make sure you are able to navigate to the home page and see the page correctly 

## Your Environment
Tested on release-5.0.3 // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15514

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15516

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 and now works as in previous versions

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF and now is working as expected
