### ISSUE TITLE
Need be able to notify the user if something is wrong trying to edit a page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15505]
Related to #15401 

After the related fix, now we are able to modify the template and continue working in the page normally, but in case you try to open the page without change the template, we are not displaying some message to the end user in order to say that something is wrong 

## Expected Behavior
We need to find some way to notify the user about the error via notification. 

## Current Behavior
We are not showing anything and just try to load the page, and it never loads 

## Steps to Reproduce (for bugs) 
1. Login as admin 
2. Create a new template 
3. Create a new page using the new  template 
4. Now go directly to the db and remove the template 
5. Flush the cache 
6. Try to edit the page 

## Your Environment
Tested on release-5.0.1 // Postgres // FF

**Comment by wezell** [comment]
Work has been done here, has this behavior changed?  Needs re-test
