### ISSUE TITLE
Error trying to push content on 5.0.3 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15508]
We are having an error when you try to use the PP feature, we have a NPE on the receiver side and we are unable to push 

## Expected Behavior
We need to be able to push every time of content without problems 

## Current Behavior
We have a NPE error and the bundle is failing 
ST: https://gist.github.com/bryanboza/18b81aed579f44869fdf52004357b37e

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. Run the Integrity checker and make sure you don't have conflicts 
3. Create a new page on receiver and push it 
4. Check the catalina.out file on receiver 

## Your Environment
Tested on release-5.0.3 // Postgres, this on both environments

**Comment by jgambarios** [comment]
Related to changes made in https://github.com/dotCMS/core/issues/15359#issuecomment-435396952

**Comment by bryanboza** [comment]
Fixed, after reverting the changes, now PP is working normally. 
Tested on release-5.0.3 // Postgres // FF. This on both environments
