### ISSUE TITLE
[Content Type] : Unchecking the "required" attribute on Category field and field re-arrangement are failing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15504]
Reproducible our Demo Site (dotCMS 5.0.2), and latest master branch.
Reported via Support: https://dotcms.zendesk.com/agent/tickets/96863

Unchecking the "Required" property of a Category field and reordering fileds in a Content Type is throwing a JS error in the browser's console. This seems to be causing the changes to not be persisted.

<img width="1044" alt="screen shot 2018-11-02 at 12 56 46 pm" src="https://user-images.githubusercontent.com/8779585/47935302-8c4fb380-de9f-11e8-992b-251302e40661.png">

## Expected Behavior
Unchecking the required property of a Category field, and reordering the fields in a Content Type must work.

## Current Behavior
An error is being logged in the browser's console and the changes are not persisted.

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Log into dotCMNS 5.0.2
2. Go to the **Content Types** portlet, and click the **Blog** Content Type.
3. Uncheck the "Required" property of the Category field called "Topic", and click Save.
4. The change is not persisted.
5. Also, reorder any fields in the Content Type, and go to another portlet.
6. Go back to the Blog Content Type. You'll see the reorder of fileds was not saved.

## Your Environment
* dotCMS version used: dotCMS 5.0.2
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Types portlet.

**Comment by wezell** [comment]
We will try to get this into 5.0.3 but it might fall back to 5.1

**Comment by bryanboza** [comment]
We are unable to add category fields in content types after the last changes 
SC: https://screencast.com/t/a1alMElu

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.3 and now it works.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the error on master
