### ISSUE TITLE
Unable to use the view as feature as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15500]
We are unable to view some page as some specific device when you are as limited user 

## Expected Behavior
Since this feature doesn't modify anything, is just view, if you can preview the page, we need to be able to use without problems 

## Current Behavior
When you set the device, the system continues showing the desktop device 

## Steps to Reproduce (for bugs)
1. Login as some limited user (chris publisher)
2. Open any page 
3. Go to the preview tab and select some device 
4. Make sure you have the device simulator 

## Your Environment
Tested on release-5.0.2 // Postgres // FF

**Comment by fmontes** [comment]
Fixed here: https://github.com/dotCMS/core/issues/15474
