### ISSUE TITLE
Elasticsearch can get locked creating indexes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15512]
When we create new indexes in elasticsearch, the transport thread can fail to return and the following calls to elasticsearch can block because of this:

https://gist.github.com/wezell/a91c5017760bb95a50e684a19139d70d

1. Try to create reproducible test case
2. Set the mapping and possible alias at index creation time 
3. ESIndexAPI should not return the CreateIndexResponse, should only make one call and return a boolean of the isAcknowledged 

We will need a method something like this:
```
	public boolean createIndex(final String indexName, String settings,
			int shards, String mappingName, String mapping, String alias) throws ElasticsearchException, IOException {


      return cirb.execute().actionGet().isAcknowledged()
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15522

**Comment by dsilvam** [comment]
Note to QA: Let's at least test index creation is working ok for both content index and sitesearch

**Comment by bryanboza** [comment]
Fixed, tested based in the last comment and works as expected.
