### ISSUE TITLE
Add toast notification handler to angular

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15513]
```
This is FE job but we need @freddyucv to build a little jsp so we can send notification events to test
```

As a stakeholder I want to make sure that developers can send notifications to the user from the backend.

## Expected Behavior
Developers should be able to send a notification through Websockets and be display is a toast component

## Current Behavior
Notifications are only shown in the bell

## Acceptance Criteria

1. Use [toast](https://www.primefaces.org/primeng/#/toast) primeng component
2. Developer should be able to add: 
    1. Timeout
    2. Type
        1. Info
        2. Warn
        3. Error
    3. HTML with links
        1. p
        2. ul and ol
        3. links
3. Add some basic styling to demostrate the functionality
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15656
