### ISSUE TITLE
Saving and publishing a contentlet indexes it 15 times

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15531]
This is a result of our recent index policy changes.

I saw content saving taking a long time last night and was wondering why.  This is why

1. Open a news article, unlock it for editing
2. Hit save and publish
3. The content gets put to the index 15 times
4. We need to discuss.

I added logging to 
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletIndexAPI.java#L575
`System.err.println("----------- Indexing : " + con.getIdentifier());`

```
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6
----------- Indexing : 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6

```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15607

**Comment by jgambarios** [comment]
If someone at some point would like to see how many times a process is reindexing the content adding this logger will be useful:

```
<Logger name="com.dotcms.content.elasticsearch.business" level="debug" additivity="false">
        <AppenderRef ref="Console"/>
</Logger>
```
