### ISSUE TITLE
Error invalidating sessions from logged users tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15538]
We are unable to invalidate logged users from maintenance portlet, we show an error when you try to invalidate some user and we are unable to invalidate the session 

## Expected Behavior
If you have access to this portlet, you need be able to invalidate sessions 

## Current Behavior
We show an error and we are unable to invalidate 
No errors on the log, neither console. 

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Login from other IP to the same server 
3. Go to maintenance --> logged users portlet  
4. Now try to invalidate the remote session 

## Your Environment
Tested on master // Postgres //  FF

**Comment by mattyarbrough** [comment]
Note this is occurring in multiple customer environments

**Comment by jtesser** [comment]
possibly you can update the moddate on user which would cause the token to fail which MIGHT be what is happening

**Comment by jtesser** [comment]
#11969 for reference

**Comment by wezell** [comment]
@bryanboza Please retest

**Comment by bryanboza** [comment]
Not an issue, we are not allowing kill sessions from your same user, you can invalidate sessions but from different users... 

Tested on master // Posgtgres // FF
