### ISSUE TITLE
Add /servlet/ to the DefaultBackEndLoginRequiredWebInterceptor

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15548]
Followup to #15371 - we added `/servlets/` and did not add `/servlet/`

**Comment by wezell** [comment]
PR #15930

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF

**Comment by jgambarios** [comment]
**For documentation:** As part of this change we needed to rename the test servlet path from `/servlet/test` to `/dotTest` and for that reason we need to update the paths in https://dotcms.com/docs/latest/functional-tests
