### ISSUE TITLE
Not able to add new content type fields using the REST API

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15542]
Updating a content type to add a new field is not working if this endpoint is used: `http://localhost:8080/api/v1/contenttype/id/{id}`

According to the documentation https://doc.dotcms.com/docs/latest/content-type-api#updateAContentType, a new field can be added to a content type if all existing fields are sent as part of the PUT request. However, the list of fields is ignored and only the content type properties are updated.

This issue happens only for existing content types. Creating a new one sending all its fields works correctly.

**Note:** An IT or Postman test should be created as part of the fix.

## Expected Behavior

I should be able to edit a content type and its fields using this endpoint `http://localhost:8080/api/v1/contenttype/id/{id}`

## Known Workarounds

The new field can be added using this endpoint instead `localhost:8080/api/v1/contenttype/{id}/fields`

## Steps to Reproduce (for bugs)

Edit **YouTube** content type using postman and sending a PUT request. I used this json object https://gist.github.com/nollymar/6e2a7b1b3ce921a2ca9e2bb57aade9b0

## Your Environment

* dotCMS version used: master
* Database and version: Postgres

**Comment by wezell** [comment]
This endpoint can be used to create a new content type with fields:
`http://localhost:8080/api/v1/contenttype/id/{id}`
after that, if you need to add/edit/delete fields, you need to do it via
`localhost:8080/api/v1/contenttype/{id}/fields`

**Comment by john-thomas-dotcms** [comment]
Note: This seems like a dup of #15600
