### ISSUE TITLE
Workflow scheme can be duped when called via api

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15543]
On our server, when you call for the list of workflows via api, it returns the system workflow twice

![screen shot 2018-11-13 at 2 53 03 pm](https://user-images.githubusercontent.com/934364/48439396-2cd18d80-e754-11e8-9b15-de0acf671909.png)

https://gist.github.com/wezell/a3f355a94407e753480c89d4fa2f9434

**Comment by wezell** [comment]
This needs to be a `Set<String>` not a `List<String>`

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowFactoryImpl.java#L1393

**Comment by jgambarios** [comment]
**NOTE TO QA:** 
Useful links that may help you to test:

* You can see the workflows associated to a content type: http://localhost:8080/api/v1/contenttype/id/a73533c3-31bc-4306-abe4-c76b091bbb0b

* All the existing workflows: http://localhost:8080/api/v1/workflow/schemes/

**Comment by bryanboza** [comment]
Fixed, tested based in the last comment and everything works as expected
