### ISSUE TITLE
[core] Multiple fake site entries added when there's no a default site

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15563]
Reported via support ticket: [96644](https://dotcms.zendesk.com/agent/tickets/96644)
Reproducible in dotCMS 4.3.3, 5.0.3

## Expected Behavior
When there's no default site, dotCMS creates a new brand fake site when it starts and sets the new fake site as the default site.

## Current Behavior
If there's no default site, dotCMS creates a new site fake entry every time the host cache is flushed. When a new fake site is created, is not set as the default site.

## Possible Solution
Fix the `save` method from the `HostAPIImpl` class, when calling the `updateDefaultHost` method:
https://github.com/dotCMS/core/blob/605e5db01a20d93aa04754432ef0253031667599/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPIImpl.java#L414

The `updateDefaultHost` method iterates over all sites to set them as not default if they dont'n match the one that we are setting as default. But the new default fake site created in the `save` method is stored in the `savedHost` variable, not the `host` variable that is send as parameter for the `updateDefaultHost` method. The `host` variable doesn't include new fake site id, so it doesn't match in the loop and it's set a not default.

## Known Workarounds
Set manually a default site, so no new entries are created when dotCSM restarts.

## Steps to Reproduce (for bugs)
1. Log into dotCMS 5.0.3
2. Create a new blank site, and set it as the default site.
3. Unset the new site created in the previous step as the default one (this can't be done from the dotCMS UI but it can be done from the REST API)
4. Flush the Host cache
5. Restart dotCMS
Every time you flush cache, and restart dotCSM or logout and login to dotCMS, a new entry is added for a fake site.
<img width="790" alt="multiple-sites" src="https://user-images.githubusercontent.com/2894221/48645390-2ab53c00-e9ab-11e8-89e4-1f27dfe4b486.png">

**Note**
To replicate the issue in 4.3.3 is required to clean the index, and restart dotCMS (if using localhost to replicate the issue) every time to see new duplicated entries. Also, the default localhost can be removed from UI in 4.3.3, from the Console Search.

## Context
This bug causes multiple fake sites added to dotCMS instance.
This was reported in this support issue: [96644](https://dotcms.zendesk.com/agent/tickets/96644)

## Your Environment
* dotCMS version used: 4.3.3 and 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relavant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): System module (sites)

**Comment by dsolistorres** [comment]
Attached hotfix for 4.3.3 version
[hotfix-GIT-15563_v4.3.3.zip](https://github.com/dotCMS/core/files/2591730/hotfix-GIT-15563_v4.3.3.zip)

**Comment by dsolistorres** [comment]
PR: #15565

**Comment by nollymar** [comment]
After some tests, it's working correctly
