### ISSUE TITLE
Delete container content type tests

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15569]
When a Container Content Type is deleted we need to make sure we are clearing properly all the related references, cache, pages, etc

**Comment by jdotcms** [comment]
DONE

**Comment by fabrizzio-dotCMS** [comment]
I'm marking this as Passed Internal QA however there are new rules to deal with pages referencing missing or deleted containers please refer to : 
https://github.com/dotCMS/core/issues/15973
https://github.com/dotCMS/core/issues/15974
https://github.com/dotCMS/core/issues/15979

**Comment by fabrizzio-dotCMS** [comment]
I'm marking it as Passed-internal-QA. since it was created to account for a fix that has been corrected. But... there are new rules to deal with the deletion of a container in general.
Please refer to:
#15973
#15974
#15979
