### ISSUE TITLE
SPA Support: Add Container Contentlet List to /api/v1/page/render

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15561]
While we provide the the container and the raw rendered html in those containers, we do not provide a list of contentlets as json that are in each of those containers. We need to provide those as they can be used by the SPA when rendering a page.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15661

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // ff
