### ISSUE TITLE
Make sure the states of the container.vtl reflects in the container 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15568]
The states of the `container.vtl` file represents the state of the container itself, we need to make sure the container works properly during the different states of that file.

**Comment by jdotcms** [comment]
currently if the content type are publish, they are rendered on the live tab in the edit mode and in the front end either.
However, the container.vtl state is not being respected by the live tab, neither the front end. It is a cache issue with it.

**Comment by jdotcms** [comment]
The state publish and unpublish are working ok if the container is inside the drawed template
when it is inside raw template (with the parseContainer (...)) does not work correctly

**Comment by jdotcms** [comment]
We were finally able to handle the cache for the advance templates on file based containers

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15677

**Comment by fabrizzio-dotCMS** [comment]
you can still see a Content type that got added before even after changing the status of to file to archived. The Content must no render if you archive the file-asset. 
See https://github.com/dotCMS/core/issues/15984

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16030

**Comment by jgambarios** [comment]
The states of the content types vtl files are being handle properly passing internal QA for this one, for the states of the `container.vtl` please refer to https://github.com/dotCMS/core/issues/15853

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
