### ISSUE TITLE
Allow Image field to be used as the contentlet.titleImage

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15575]
in #15473 we added the property of titleImage to a contentlet that will send the results of the first binary field with an image on any contentlet.
We need to also enable scanning of Image Fields - so the rule will be :

1. return the first ImageField or BinaryField that has an image in it.
2. Title Image needs a specific endpoint meaning, we need to append `titleImage` to get the title image e.g. `/dA/1212-123/titleImage` 
3. If no title image is found, we need to return a 404
4. This needs tests.
5. Remove the title image from the ESMapping - not needed there

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15772

**Comment by wezell** [comment]
To test the latest changes that force explicitly adding `titleImage` to the call:

`http://127.0.0.1:8080/dA/2943b5eb9105` == 404
`http://127.0.0.1:8080/dA/2943b5eb9105/titleImage` == image

**Comment by fabrizzio-dotCMS** [comment]
In this example, I always get theback image even when I hit both URLs 
http://127.0.0.1:8080/dA/2943b5eb9105 == image
http://127.0.0.1:8080/dA/2943b5eb9105/titleImage == image

Even if I do this 
http://127.0.0.1:8080/dA/2943b5eb9105/titleImageLOL
I still get an Image

Here an example that returns an image out of a binary field 
http://127.0.0.1:8080/dA/eae8b6e478
and here how I know this is a binary field 
http://localhost:8080/api/v1/content/versions/?identifier=eae8b6e4-7824-42e4-81dc-51b95cc39540

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15808

**Comment by jgambarios** [comment]
Everything looks good except for the multilingual support, looks like the `/dA` servlet does not respect languages:

Using for testing a `News` contentlet create a Spanish version of it and add a different image, if you try to hit the following URLs only the english version of the image is render:

``` 
http://localhost:8080/dA/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6?language_id=2
http://localhost:8080/dA/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6/titleImage?language_id=2
```

Also, trying to hit directly the file asset in spanish won't work either:
`http://localhost:8080/dA/2943b5eb91/image/spanishimage.png?language_id=2`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15851

**Comment by jgambarios** [comment]
We still have issues with the multilanguage support:
1. Create a spanish version of any `News` content.
2. In the spanish version use a different image than the English version

#### Works:
`http://localhost:8080/dA/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6?language_id=1`

#### Does not work (404):
`http://localhost:8080/dA/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6?language_id=2`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15894

**Comment by jgambarios** [comment]
There is a null pointer exception when:

1. Create a **working** content in spanish language only
2. Request it using the default language `languageId = 1`

The problem can be fix adding the proper returns in lines:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L365
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L374

**NOTE: Before to add the fix an integration test should be write in order to reproduce the bug.**

**Comment by bryanboza** [comment]
Fixed, tested with the attached comments and works as expected
