### ISSUE TITLE
Delete container folder tests

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15571]
Make sure the application behaves properly when a Container folder is deleted.

**Comment by jdotcms** [comment]
Changes on https://github.com/dotCMS/core/pull/15677/files already fixed this one too

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15677

**Comment by fabrizzio-dotCMS** [comment]
I'm marking this as Passed Internal QA however there are new rules to deal with pages referencing missing or deleted containers please refer to : 
https://github.com/dotCMS/core/issues/15974
https://github.com/dotCMS/core/issues/15979

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
