### ISSUE TITLE
Can't deserialise objects using XStream library

### ISSUE THREAD

**Issue by mwoodland** [dotCMS/core#15589]
Since upgrading to dotCMS 5.0.2/5.0.3 I'm no longer able to use the XStream library to deserialise XML into Java objects.

## Expected Behavior
The XStream library should continue to work.

## Current Behavior
When calling XStream.fromXML() I get a StreamException:
`Caused by: com.thoughtworks.xstream.io.StreamException: Cannot create XmlPullParser
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:56) ~[classes/:?]
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65) ~[classes/:?]
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070) ~[classes/:?]`

Further investigation shows that this exception is being caused by the following:
`org.xmlpull.v1.XmlPullParserException: incompatible class: com.dotcms.repackage.org.xmlpull.mxp1.MXParser
        at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:340)
        at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
        at com.thoughtworks.xstream.io.xml.XppDriver.createParser(XppDriver.java:57)
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070)`

Investigation shows that the xmlpull library (XmlPullParserFactory.newInstance()) is getting a resource "/META-INF/services/org.xmlpull.v1.XmlPullParserFactory" from the class loader. This resource is coming from the dotCMS repackaged version of the xpp3-min library, which has "com.dotcms.repackage.org.xmlpull.mxp1.MXParser" in it.

The xmlpull library is then checking whether this MXParser class is an instance of the XmlPullParser class.

This is where the error occurs because we're mixing repackaged and non-repackaged libraries.

The repackaged MXParser class implements the repackaged XmlPullParser class, but the xmlpull library is not repackaged any more so is not using the repackaged XmlPullParser class and so the MXParser class is not an instance of the non-repackaged XmlPullParser. And hence we end up with the incompatible class XmlPullParserException.

## Possible Solution

Either update the repackaged xpp3-min library so that it doesn't use the repackaged xmlpull library and classes/packages.  Or repackage the xmlpull library as well as the xpp3-min library. Or don't repackage either library.

## Steps to Reproduce (for bugs)

Add a plugin that calls XStream.fromXML() and try and get that plugin to deserialise some XML in dotCMS 5.0.2/5.0.3.

## Context
I use a plugin that is fundamental to my use of dotCMS. It relies on using the XStream library to deserialise XML.

## Your Environment

* dotCMS version used: Tried both 5.0.2 & 5.0.3
* Browser Name and version: N/A
* Operating System and version: CentOS 7.5.1804
* Application Server and version: tomcat-8.5.32
* Java Brand and version: jdk-8u152
* Database and version: mysql57-community-release

**Comment by mwoodland** [comment]
It looks like there's been some relatively recent changes in the docms-libs repository here: https://github.com/dotCMS/dotcms-libs/commit/45fc37404b4f507fee815bd1032195b54713b57b#diff-2cccd7bf48b7a9cc113ff564acd802a8.

But I can't see any corresponding updates in the artifactory artifacts at http://repo.dotcms.com/artifactory/. Is there somewhere else I should be looking for the repackaged libraries?

**Comment by mwoodland** [comment]
> It looks like there's been some relatively recent changes in the docms-libs repository here: [dotCMS/dotcms-libs@45fc374#diff-2cccd7bf48b7a9cc113ff564acd802a8](https://github.com/dotCMS/dotcms-libs/commit/45fc37404b4f507fee815bd1032195b54713b57b#diff-2cccd7bf48b7a9cc113ff564acd802a8).
> 
> But I can't see any corresponding updates in the artifactory artifacts at http://repo.dotcms.com/artifactory/. Is there somewhere else I should be looking for the repackaged libraries?

If I build the repackaged libraries using that repo then it doesn't seem to actually repackage the xpp3-min library.

**Comment by jdotcms** [comment]
Have you tried by using another Driver when instance XStream, by default it uses the new XppDriver(), but you can use another such as DomDriver or so

**Comment by mwoodland** [comment]
I've not tried that since I've got a workaround that works and currently have plenty of other issues to do with the dotCMS 5 upgrade to deal with.

Regardless I don't think dotCMS should be including libraries that will not work if you try and use them.
