### ISSUE TITLE
nullProperties making it into contentlet map

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15590]
Open a piece of content and save it.  Then take a look at the contentlet via the json api.  You can see the nullProperties making it into the contentlet map.  It should not be there.

![screen shot 2018-11-23 at 2 06 09 pm](https://user-images.githubusercontent.com/934364/48957822-3e235280-ef29-11e8-8cbc-ec2d442b6a2e.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15593

**Comment by bryanboza** [comment]
Fixed, now we are not showing the null properties in the JSON. Tested on master // oracle // FF
