### ISSUE TITLE
Allow ContentType and Field Resources to accept variable for ContentTypeId

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15602]
The ContentTypeResource and FieldResource expect {ContentTypeId} to be passed in as a uuid.  We need to allow the use of the contentType.variable as well.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15737

**Comment by bryanboza** [comment]
Fixed, tested on the master code// Postgres // FF
