### ISSUE TITLE
WorkflowTool.fire: Return ContentMap instead of Contentlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15603]
https://github.com/dotCMS/core/blob/0f0ab7fb5bd9fc96694f516baf32991ae3a213da/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/WorkflowTool.java#L171

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15680

**Comment by nollymar** [comment]
Test results: Working correctly

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
