### ISSUE TITLE
FieldResource ignoring "type" on certain http methods

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15606]
When using POST/PUT against `/v1/contenttype/{typeId}/fields`, the "typeId" param is not respected (ignored) so it's actually possible to update/create fields belonging to different content types. Also, if "typeId" starts to be taken into consideration, it shouldn't be needed or even used if included in the JSON body. (Discuss)

**Comment by wezell** [comment]
Workaround, set the contentTypeId in the field properties rather than as a path param
