### ISSUE TITLE
Adding support to use Request and Response wrappers in Web Interceptors

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15614]
We want to have the ability to wrap the `HttpServletRequest` and `HttpServletResponse` when using Web interceptors.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15399

**Comment by jgambarios** [comment]
OSGI plugin example: https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.webinterceptor

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
