### ISSUE TITLE
remove unneeded sync in publish method

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15613]
We have seen threads getting backed up in the EsContentletAPIImpl.publish method which had a very old sync block in it.

https://github.com/dotCMS/core/blob/5.0.3/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L421-L447

I believe this should be safe to remove.

**Comment by fabrizzio-dotCMS** [comment]
@wezell  What exactly does it mean "Threads getting backed up" and how did you observe the odd behavior there?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15641

**Comment by jgambarios** [comment]
We need to change this default value `static final int DEFAULT_TIME = 30;` to `3` seconds

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/concurrent/lock/StripedLockImpl.java#L18

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15740
