### ISSUE TITLE
Saving Content fails/freezes with custom list of languages

### ISSUE THREAD

**Issue by jinta** [dotCMS/core#15624]
## Expected Behavior

If I'm overriding the list of supported languages to just a few instead of displaying all of them then creating or updating a contentlet should save correctly without crashing/freezing.

## Current Behavior

When trying to save any change to a contentlet then the "Saving changes.." dialogue never seems to finish but closing that dialogue would let the changes finish processing. This doesn't happen when the list of languages is the full/unrestricted list.

## Possible Solution

The fix would be to update the ```edit_contentlet_js_inc.jsp``` file in the ```saveContentCallback``` function, specifically the ```if(entry)``` bit on line 551 (dotCMS version 5.0.3). 
What happens is that it only checks if the entry is undefined but doesn't check if the entry is empty, which is what's causing the problem.
So update that line to also check for empty entry, i.e.:
```java
if(entry != undefined && entry.length > 0)
```

## Known Workarounds

I have to close the popup to let it process the save.

## Your Environment

* dotCMS version used: 5.0.3
* Browser Name and version: Chrome 70.0.3538.110 (Official Build) (64-bit)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15629

**Comment by jinta** [comment]
The commit should have fixed the unique issue.

**Comment by bryanboza** [comment]
Fixed
