### ISSUE TITLE
Add api link (button) to new content type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15620]
1. We need a generic "api" button/link that we can use across our ui to show an example of how to call the api.

2. Add this to our new content types - it should pop up in a new window.
![screen shot 2018-11-28 at 4 08 48 pm](https://user-images.githubusercontent.com/934364/49182859-634d0200-f329-11e8-82b0-427fb31d5aeb.png)

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/content-type-api#QuickAccess
