### ISSUE TITLE
Create a copy button/label component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15633]
The component should receive a string as a param and when is clicked that string should get copied to the clipboard.

## Icons:
1. `file_copy`

## Solution
We have that implemented in [here](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/components/dot-edit-page-info/dot-edit-page-info.component.html#L3)

## Acceptance Criteria
1. Use the existing icon and [button components](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/dot-icon-button/dot-icon-button.component.html)
2. Replace the hover color of the icon button instead of gray use alpha value of `$black`
3. Component should receive a param called: "text" and that string is the one that gets copy on click and tooltip to add text to a tooltip by default tooltip should say: "Copy"
4. When the user click the button we copy the string to the clipboard and if everything is good we replace the text of the tooltip with "Copied!" for 2 seconds and then gets back to the original text.
5. It should support all the attr of the buttons: secondary, tiny, etc...
6. Replace the copy button in edit mode with this new component
7. Add the component to the content types **(in label mode)**, add it to: field variables and content type variable
8. Work in all the supported browsers (don't forget IE11 and iPad)
9. Multilanguage
10. Unit test

**Comment by bryanboza** [comment]
In the content types case, I think isn't clear, I think we need to use the same button in both cases: https://www.screencast.com/t/Qnjq994d

**Comment by fmontes** [comment]
@bryanboza please refer to @fishsmith and if something else is agreed on this end we'll create a new card. This AC for this one is done.

**Comment by wezell** [comment]
I think we need little "copy" icons next to the var names so it is clear that they will get copied.

**Comment by wezell** [comment]
Freddy shared the mockup with the icons and it looks pretty bad.  I would rather keep it the way it is now.  See below:

<img width="1346" alt="screen shot 2018-12-05 at 10 23 09 am" src="https://user-images.githubusercontent.com/934364/49965899-7eed0680-feec-11e8-8cd7-2bef4f8d664f.png">
