### ISSUE TITLE
Creating New Relationship field with hyphen in the variable name fails to related content

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15630]
Used this curl to create the new field:

```
curl -H "Content-Type: application/json" -v -u admin@dotcms.com:admin -POST  http://localhost:8080/api/v1/contenttype/28039964-5615-4ccf-bb96-ded62adbcc6a/fields -d '{
    "contentTypeId":"28039964-5615-4ccf-bb96-ded62adbcc6a",
    "name": "YouTube Videos",
    "variable": "youtube-videos",
    "clazz": "com.dotcms.contenttype.model.field.ImmutableRelationshipField",
    "values": 1,
    "relationType": "Youtube"}'
```
` "variable": "youtube-videos"`

Then when trying to save and publish a news content with related youtube content, throws error in the UI and this in the log:
https://gist.github.com/dsilvam/26e9a85a5b48d29869a386cda8870b69

**Comment by nollymar** [comment]
A validation in the FieldResource is needed to avoid `-` in the variable property. It is not allowed from the UI, so the RestAPI should have a similar behavior

**Comment by bryanboza** [comment]
Fixed, now we are returning the 400 error on this case
