### ISSUE TITLE
Unable to load the roles drop down in the permissions tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15646]
We are having problems to load this component when you are editing some content and go to this tab twice without close the modal.

## Expected Behavior
We need to be able to load this drop down without problems 

## Current Behavior
We are unable to load the drop down and see the roles 
<img width="1729" alt="permiss" src="https://user-images.githubusercontent.com/2641437/49454428-bb14be80-f7aa-11e8-93aa-0d97c46c7129.png">

## Steps to Reproduce (for bugs)
1. Login as admin  
2. Open any content to edit 
3. Go to the permissions tab 
4. Go to the content tab
5. Go back to the permissions tab 
6. Try to open the roles drop down 

## Your Environment
Tested on master // Oracle // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15784
