### ISSUE TITLE
Cached ContentType in the Contentlet object is causing inconsistencies

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15653]
This **null** validation in Contentlet#getContentType()

```
if (null == this.contentType) {
	try {
			this.contentType =
			APILocator.getContentTypeAPI(APILocator.systemUser())
								.find(getContentTypeId());
	} catch (DotDataException | DotSecurityException e) {
			throw new DotStateException(e);
	}
}
```
that was included as part of this PR https://github.com/dotCMS/core/pull/14960 is causing some inconsistencies on existing contentlets when the content type is modified, because the content type property in the Contentlet object is not updated when the ContentType cache changes. So, these calls can return different results: `contentlet.getContentType().fields()` and `contentlet.getStructure().getFields()`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15654

**Comment by nollymar** [comment]
**Note to QA:** 
Steps to reproduce this issue:

1. Add a one sided relationship field from News to Youtube
2. Add a YouTube's related content to any news
3. Add the other side of the relationship (from YouTube to News)
4. When you open the YouTube's related content set in Step 2, the news is displayed twice

**Comment by erickgonzalez** [comment]
Working as it should

**Comment by bryanboza** [comment]
Unable to reproduce on the last master
