### ISSUE TITLE
Unable to add pieces of content on master 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15678]
We are having a problem trying to add any kind of content in the last master code, we are displaying an unexpected error in the modal and you are unable to add content. 

## Expected Behavior
we should be able to add content without problems

## Current Behavior
We have the follow NPE on the log file and you can't add content 
NPE: https://gist.github.com/bryanboza/e913e8192d19bf99e411992eef47e265

## Steps to Reproduce (for bugs)
1. Make sure you have the last master code 
2. Go to content Search 
3. Try to add a new piece of content 

## Your Environment
Tested on the last master // Oracle // FF

**Comment by dsilvam** [comment]
Fixed in this PR https://github.com/dotCMS/core/pull/15677

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
