### ISSUE TITLE
Improve field-validation-message component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15686]
As a user I want field to be validated after I interact with them, not just focus, but add something to the field.

## Expected Behavior
Validation message should show only if the user interact with the field more than just focus.

## Current Behavior
Validation message show on blur.

## Possible Solution
Field object have properties like: dirty, pristine, etc... check which can do the job

## Acceptance Criteria

1. Rename the component to `dot-field-validation-message` (files and folder included)
2. Make the message show only if the user interact with the field more than just focus/blur
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, now this component works better and validates the field after press any key
