### ISSUE TITLE
Save button in edit field dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15687]
As a user I want to know if I can save a form or not.

## Expected Behavior
Save button in the dialog should be disable until the form value change and form is valid

## Current Behavior
Save button is always enabled.

## Acceptance Criteria

1. Save button in the dialog should be disable until the form value change and form is valid
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
still happens, when field is just created
https://monosnap.com/file/Mv6Y6AdbCieMAoyPn9uUtbTw54bdRI

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF  and now it is working as expected
