### ISSUE TITLE
Add getRelated to Contentlet.java

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15691]
```
    transient Map<String,List<String>> relatedIds = Maps.newConcurrentMap();
    public List<Contentlet> getRelated(final String variableName) {
        //return related list of content
    }
```

Needs to store a cached Map<String,List<String>> of related IDs and hydrate them on every return

**Comment by erickgonzalez** [comment]
Tested Working as it should:
1- Add a new Relationship Field to Content Generic (to News), named **News**
2- Create a new contentlet Content Generic with a Relationship
3- Copy the id of the new contentlet
4- Create a new simple widget with the following code:
`$dotcontent.find('ID').news`
5- Add the simple widget to a page

This should return the Contentlet(s) that are related to the contentlet parent.

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now we are able to get related content without problems, tested with the steps of the last comment and works as expected
