### ISSUE TITLE
Edit mode problems displaying the content details when the content type is related as itself

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15698]
We have problems displaying the content details after import some content to a content type that is related as itself. 

## Expected Behavior
We should be able to handle this case without problems 

## Current Behavior
When you export the system is creating the file just with one column with the name of the field, which is ok, but when you import we set this value as a parent and child.:
Content: https://screencast.com/t/1lRDxbpKb4
CSV to import:  https://screencast.com/t/LPGrsWkn5

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type with just one field 
3. Add a new relationship field and create a relationship to itself 
4. Add a piece of content 
5. Now try to export this content 
6. Using the existing content import a new piece of content 
7. Try to open the new one to edit 

## Your Environment
Tested on master // Oracle // FF

**Comment by nollymar** [comment]
It has not been possible to finish this task until this issue is solved https://github.com/dotCMS/core/issues/15473

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15809

**Comment by dsilvam** [comment]
Passed internal qa: Working as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
