### ISSUE TITLE
Enhancements for containers as a file

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#15695]
As part of the feedback on container as a file, we have to work and double check these items:

1) on the template you should be able to get container from other sites, on the container portlet only the container for your site.
2) ability to add more than one container on the template portlet
**Make sure to include a proper uuid when adding multiple versions to template (ask @freddyucv for more info)**
3) when there is not a container folder do not throw an error. Do just nothing
4) the file based containers on the container portlet, should be rendered such as (name | path (there should be read only))
5) double check if the files on the container file are uncase sensitive.

**Comment by jdotcms** [comment]
Done: the file based containers on the container portlet, should be rendered such as (name | path (there should be read only))

**Comment by jdotcms** [comment]
Done: double check if the files on the container file are uncase sensitive.

On this one:
when there is not a container folder do not throw an error. Do just nothing

**Comment by jdotcms** [comment]
Done: when there is not a container folder do not throw an error.

On this one:
ability to add more than one container on the template portlet

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15743

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
