### ISSUE TITLE
Sorting by Mod.Date in Links, Templates, and Containers portlets is failing in PostgreSQL

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15708]
Reported by customer via Support: https://dotcms.zendesk.com/agent/tickets/97068
Reproducible in dotCMS 5.0.0 and 5.0.3 (Demo Site)

This issue is present in PostgreSQL. However, all DBs must be tested as well.

## Expected Behavior
Ordering information by clicking the **Mod. Date** column in the Links, Templates, and Containers portlets must work correctly.

## Current Behavior
Ordering by **Mod. Date** is throwing the following error on the page:

```
An unexpected system error occurred.

com.dotmarketing.exception.DotDataException: ERROR: column asset.moddate does not exist 
Hint: Perhaps you meant to reference the column "asset.mod_date". Position: 353{ "SQL": 
["select asset.*, inode.* from links asset, inode, identifier,link_version_info 
versioninfo where asset.inode=inode.inode and asset.identifier = identifier.id and 
versioninfo.identifier=identifier.id and identifier.host_inode = 
'48190c8c-42c4-46af-8d1a-0cd5db894797' and asset.inode=versioninfo.working_inode 
and versioninfo.deleted = 'false' order by asset.modDate desc"], "maxRows": [500], 
"offest": [0] }
```

## Possible Solution
The error message seems to indicate a problem with the name of a column.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Log into the back-end.
2. Go to any of the portlets mentioned previously: Links, Templates, or Containers.
3. Click the **Mod. Date** column to order the information.
4. An error is displayed on the page.

## Your Environment
* dotCMS version used: 5.0.0, 5.0.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: PostgreSQL
* Application module: Links, Templates, and Containers portlets.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15709

**Comment by bryanboza** [comment]
Fixed, tested with the last master code // Postgres // FF
