### ISSUE TITLE
ContentAPI.findContentletForLanguage should not hit elasticsearch

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15704]
Testing Edit Mode which makes repeated calls to this method using the PageContextBuilder locked up my Elasticsearch.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15705

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/15715

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
