### ISSUE TITLE
Field Shows up in list even when the Field is not saved due lack of Permissions

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#15707]
Related to #15285 

If a limited user has permissions to see an existing content type, and you try to add a field, we are showing the error and the field isn't added to the content type, but we show the field in the list.
If the page is refreshed the field disappear.

## Steps to Reproduce (for bugs)
1. Create a Role and give access to the Content-Type portlet
2. Create a User and assign to that Role.
3. Create a Blank Site
4. Give Publish permissions to Content Type to that Role on the new Site.
5. As Admin Create a new Content Type on the new Site.
6. Log in as the new User and add a field to the content type, an Access Denied message is shown but the field shows up on the list.

SC: https://screencast.com/t/09RsNrKXXhvK

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
