### ISSUE TITLE
Unable to load the rules engine portlet the first time with a clear instance 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15710]
We have problems loading the rules portlet this the first time you try to open it, after starting a clear instance 

## Expected Behavior
We should be able to load this portlet without problems 

## Current Behavior
The first time we are just showing a gray window and don't load the rules. 
SC: https://screencast.com/t/QJDN5tgO6X34

## Steps to Reproduce (for bugs)
1. Start a clear instance
2. Go to the rules portlet 

## Your Environment
Tested on master // Oracle // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF

**Comment by wezell** [comment]
And page rules work ok?

>
