### ISSUE TITLE
Long file paths break Add File UI

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15725]
If there are a series of nested folders that exceed a certain length (the path I was using was
/subsite1/das-ist-ein-neuer-ordnername/noch-ein-langer-name/noch-ein-level-mit-langem-namen/das-ist-der-letzte-lange-name/und-das-ist-der-letzte-lange-name/noch-ein-level-mit-langem-namen)  if you go to add an image in the GUI editor you can only navigate down about 4 folders and the + box to open the next layer has shifted under the title and can't be clicked anymore.

## Steps to Reproduce (for bugs)

1. Create a folder tree as described above
2. Go to Content Search and select an item with a text area (I used News)
3. Add an image
4. Try to navigate to the last folder in the chain.

## Your Environment

* dotCMS version used: 5.0.3
* Browser Name and version: Safari 12.0.1, Chrome 70.0.3538.110

**Comment by jcastro-dotcms** [comment]
My 2 cents here: I believe we have a size limit at DB level regarding the number of characters for parent paths and asset names.

**Comment by mattyarbrough** [comment]
The issue isn't with the length of the names as such, but rather that in the UI the JS toggle to drop into the next folder level shifts slightly right each layer and by about the 4th or 5th layer is underneath the text and can't be clicked.

**Comment by wezell** [comment]
I think this is a long standing limitation of the dotCMS system.  It just needs to be docced.
