### ISSUE TITLE
Adding $ in content title causes velocity to render improperly

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15735]
Add a $ to the end of a title in a contentlet, the page will now render $content.title  (where content is the type of content) rather than the title.  In 4.3.3 this would render the proper title with a $ at the end.

Video comparison:
https://www.dropbox.com/s/86r5zvtgw7t9il2/github.mp4?dl=0

* dotCMS version used: 5.0.3

**Comment by mattyarbrough** [comment]
Further reports indicate this is also happening in earlier versions of dotCMS

**Comment by JeanMarcGoepfert** [comment]
We are experiencing the same issue.

I’ve reproduced this on the official demo site by adding a $ to the end of the title of one of the events (technology-job-fair), this causes the event title to render incorrectly on [this page](https://demo.dotcms.com/news-events/events/technology-job-fair?id=eed1dc45-fa96-4f48-9c30-30e5a8bd9b58&language_id=1 ) and other pages where that title is used. The content should read “Technology Job Fair $”, instead, the vtl variable is displayed: ("$levent.title").

See screenshots below.

Events Page:

<img width="339" alt="screen shot 2019-01-07 at 11 12 39 am" src="https://user-images.githubusercontent.com/4322064/50743560-8f836900-126d-11e9-9de6-357856dd8f9b.png">

Individual Event Page:

- <img width="282" alt="screen shot 2019-01-07 at 11 15 21 am" src="https://user-images.githubusercontent.com/4322064/50743559-8c887880-126d-11e9-9d8a-2389120e8d5a.png">

**Comment by wezell** [comment]
@mattyarbrough Not a new issue, I just reproduced it on https://demo4.dotcms.com

**Comment by wezell** [comment]
What happens if you use formal reference notation, e.g. `${content.title}`?

**Comment by mattyarbrough** [comment]
Issue still occurs in that case
