### ISSUE TITLE
[Content] : Handling of short Identifiers and Inodes coming from Legacy Files needs improvement

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15730]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97059
Reproducible in dotCMs 4.3.3, 5.0.3

Customers can display contents with binary fields using the `/dotAsset/` servlet, which takes either the Identifier of a file but uses its Inode to return it in the end.

In previous versions of dotCMS, the system allowed Legacy Files to have its Identifier or Inode as a consecutive number instead of being a UUID, as it currently works. Such UUIDs are 36 characters long and are composed of alpha-numeric characters. Whereas the legacy IDs are simple numeric values that might even be just a few characters long.

Once those Legacy Files are migrated to Files As Content, the Identifier and the Live Inode of each file is migrated to Content without any modification. This is causing problems with the way the `/dotAsset/` handles those values.

## Expected Behavior
The `/dotAsset/` servlet must handle both currently valid UUIDs and legacy Inodes composed of only numbers and a few characters long.

## Current Behavior
The `/dotAsset/` servlet is throwing a 404 error when accessing files through this.

## Possible Solution
Inspect the code in the `com.dotmarketing.servlets.BinaryExporterServlet` class.

## Known Workarounds
Go to the File As Content presenting problems, and just click the **Save / Publish** button.

## Steps to Reproduce
1. Start up a clean dotCMS instance. Once
2. Go to the "/images/icons/photos/" folder, and edit the "app-promo.jpg" image. Click the **History** tab to see the current live Inode, and copy it.
3. Shut down dotCMS. Manually change the Inode of the previous image file to be a simple number like: "123123". You will need to drop a few table constraints and update the folder name of the image in the "/assets/" directory.
4. Start up dotCMS again and kick off a new reindex. 
5. Go to the "/images/icons/photos/app-promo.jpg" file again. You'll notice that the binary file s not showing up. Its Identifier es "8d567c31-3a69-45a1-b6ab-151772927cc3".
6. In another browser, go to http://localhost:8080/dotAsset/8d567c31-3a69-45a1-b6ab-151772927cc3.jpg . You will get the 404 error.
7. If you **Save / Publish** the file, the image will be available now.

## Your Environment
* dotCMS version used: 4.3.3, 5.0.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Edit.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/15738

**Comment by bryanboza** [comment]
Unable to reproduce in the last master. Tested on master // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Added fix to dotCMS 5.0.3 Maintenance Plugin: https://github.com/dotCMS/support/tree/master/maintenance_plugins/com.dotcms.maintenance-5.0.3
