### ISSUE TITLE
Misleading error message when CMS anonymous has no sufficient rights on host level has been updated.

### ISSUE THREAD

**Issue by florianschuetz-diva-e** [dotCMS/core#15748]
When the CMS anonymous user has no sufficient rights on host level, dotCMS only outputs an empty page. If for some reason, all permissions checkboxes except from the overall "view" checkbox were missing for a site, this results in an empty white page with no error message visible. 
The request is sent with an error code 500. The log files on dotCMS side did not show any error.

This can be remediate by adding the view checkboxes for files/folders/content etc..

The error message or rather the lack thereof is very misleading.

Expected behaviour would be a 401 (Unauthorized) or 403 (Forbidden) error message instead of just an empty page.

**Comment by jtesser** [comment]
@mattyarbrough can you try to reproduce in 5.x
