### ISSUE TITLE
[core] Log level too verbose for some handled exceptions for File Assets

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15758]
Reported via support ticket: [97249](https://dotcms.zendesk.com/agent/tickets/97249)
Reproducible in dotCMS 4.3.3, 5.0.3

Some handled exceptions for file assets code add records to the log for traceability, but this causes a lot of not required messages appended to the log.

## Expected Behavior
The exceptions in file assets getter methods are handled by code, and the messages can be useful for debugging purposes only, but are not required for information logging level, so the log level should be set to DEBUG for the messages.

## Current Behavior
The exceptions are handled by code, and the messages are added to the log using error level, but are not really required for informational purposes.

## Possible Solution
Change the log level to debug, so the messages are not shown in info logging level.

## Known Workarounds
None.

## Context
This change has been requested by clients for the log can be more clean when using info level.

## Your Environment
* dotCMS version used: 4.3.3 and 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module: System (file assets)

**Comment by dsolistorres** [comment]
PR: #15762

**Comment by bryanboza** [comment]
Fixed, those logs were moved to debug... Tested on master // Oracle // FF

**Comment by oarrietadotcms** [comment]
PR for 4.3.4: https://github.com/dotCMS/core/pull/16206
