### ISSUE TITLE
Create a cache for MultiTreeAPI.getPageMultiTrees()

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15757]
The method MultiTreeAPI.getPageMultiTrees() is one of most important ones in dotCMS - it builds the lists of content, per containers, that live on any given page and ties the whole page_x_container_x_content model together.  The method is called when a page is rendered and the results are cached in the page's rendered Velocity Template.

The issue stared in 5.0, when the PageAPI started calling MultiTreeAPI.getPageMultiTrees() in order to render the response for "layout as service" calls.  The problem with this is that every call to pages, e.g.  `/api/v1/page/render/about-us/index' now hits the database, making the end point unscalable.

Additionally. the MultreeFactory and the MultiTreeAPI are in a state of flux, the API not being fully fleshed out and the MultreeFactory being an old school static method util.  These need to be consolidated and understood in order for cache populations and invalidations to be validated.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15770

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
