### ISSUE TITLE
Add functionality to migrate old relationships to new Relationship Field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15752]
Users need to be able to convert legacy relationships to field based relationships on a case by case basis.

1.  We need to add a button titled `Convert to Relationship Field` to the relationship detail page.  This button will allow an admin to convert a relationship from a legacy relationship to a field based relationship.  This button should be here.

![screen shot 2019-01-02 at 12 46 40 pm](https://user-images.githubusercontent.com/934364/50604309-828d0100-0e8c-11e9-83d6-781852b1c615.png)

When clicked it should ask the user to confirm - via javascript - that they are ok transforming the relationship to a field with the following warning:

> Changing this relationship will change this content type and the related content type by adding a new relationship field to both types.  Relationship, cardinality, and the parent child nature will be maintained, only content related by this the current relationship will now be related by the new relationship fields and the old relationship will be deleted.  Any API calls or lucene queries that rely on the old methods of calling related content will need to be modified to a different syntax in order to function properly (see documentation for more details).
> 
> Are you sure you would like to convert this relationship?

2. When confirmed, we will follow the steps laid out here, programatically:
https://github.com/dotCMS/core/issues/15169

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15793

**Comment by bryanboza** [comment]
After you migrate some legacy relationship to a field, If you open the relationship, edit something and save, this from the relationships tab, we are saving it as a new legacy relationship, this because if you try to edit the relationship, you are able to convert again... and we create a new one every time you save
![2019-01-10_14-59-46 1](https://user-images.githubusercontent.com/2641437/51000928-147fb400-14f4-11e9-9085-b9ad02333144.gif)

**Comment by erickgonzalez** [comment]
After discussing the relationship tab should only show the legacy relationships.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15825

**Comment by nollymar** [comment]
Tests Results: Working as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF

**Comment by bryanboza** [comment]
Note to doc: We need doc the difference to use just one field or two fields as we do after migrate, and doc the advantages

**Comment by john-thomas-dotcms** [comment]
Documented: https://auth5.dotcms.com/docs/latest/upgrading-to-dotcms-5-0#LegacyRelationships
