### ISSUE TITLE
Swap cancel and action button in the jsp

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15778]
```
Users > Role
User > Detail
Push Publish > Dialog
Push Publish > Add to bundle dialog
Workflow > Edit Step
Workflow > Edit Sub Action
Sites > Create New site dialog
roles -> add roll
roles -> add/edit tool
site search -> job scheduler
site search -> create new index
category -> add category
users > Additional Info > Add Contact Info
Menu Link -> edit
Time machine -> settings
folder -> new folder
MultiFile -> upload
languages -> edit language
Rules -> Add to bundle NG dialog
Configuration > Publishing Environments -> add/edit Environment
Configuration > Publishing Environments -> add/edit Endpoint (edited) 
```

## Acceptance Criteria

1. Go for each section and swap the action buttons to be CANCEL | ACTION. Always CANCEL to the left
2. If is a dialog: align the buttons to the right
3. If is a full page: align the buttons centered
4. If there are more than 2 buttons: CANCEL      ACTION       SAVE
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by fmontes** [comment]
```Workflow > Edit Step```

<img width="471" alt="screen shot 2019-01-09 at 2 40 37 pm" src="https://user-images.githubusercontent.com/751424/50927167-97cdd680-141c-11e9-8fa9-6b71c4544474.png">

**Comment by fmontes** [comment]
```Workflow > Edit Sub Action```
![Uploading Screen Shot 2019-01-09 at 2.40.37 PM.png…]()

**Comment by fmontes** [comment]
```languages -> edit language``` <-- also add the "naked" class to the cancel.

<img width="1454" alt="screen shot 2019-01-09 at 2 50 44 pm" src="https://user-images.githubusercontent.com/751424/50927638-fa73a200-141d-11e9-843c-289a836254a8.png">

**Comment by bryanboza** [comment]
We need some work on those ones. 

Add role has a different style: https://screencast.com/t/YZLwppDMK 
Add rules to bundle: https://screencast.com/t/3cnkwZGFo
Pushing rules: https://screencast.com/t/L8Gb1jGX

**Comment by bryanboza** [comment]
Also, we need the same style in the recover password window... 
SC: https://screencast.com/t/pjvuykUQ

**Comment by fmontes** [comment]
As per @wezell we're not doing styling right now... just position.

**Comment by bryanboza** [comment]
Hey @wezell, @fishsmith  testing this card I looked multiple styles for the same button, not sure if this is ok for now, or maybe we can use this card standardize this button in all the system. 
Here some examples: 
Style 1: https://screencast.com/t/dk20IS0mGVv
Style 2: https://screencast.com/t/hHIMCQ8eYy
