### ISSUE TITLE
Create Listeners for content type modifications

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15779]
Create listeners for the different operations that require a GraphQL schema invalidation:

- CRUD on content types and fields.

**Comment by dsilvam** [comment]
Done here: https://github.com/dotCMS/core/pull/15781

**Comment by dsilvam** [comment]
Note for QA:

Any time changes in content types or its fields happen (crud), and make a new GraphQL request, the schema should be regenerated

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF... Tested with Insomnia
