### ISSUE TITLE
relationships of one return Object rather than List<>  in velocity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15797]
If you are calling for a `one` side of a relationship in Velocity, we should return the related object rather than a `List<>`.
So, if you have a many to one relationship, e.g. *Movies* --> *Rating* and 
you want to show the *Rating*'s title  for a movie, you should be able to do `$movie.rating.title` rather than`$movie.rating.get(0).title`

Likewise, if you have a one to one relationship, you should be able to do the same thing.  Take a *Person* and their spouse, another *Person*, you should be able to do

`$person.spouse.firstName`

This needs to happen in 
- Velocity - contentMap
- ContentResource in the searches
- ESContentResourcePortlet
- Graphql

**Comment by erickgonzalez** [comment]
Test:
1- Create a Content Type (Rating) with a Text Field (Rated).
2- Create a Content Type (Cast) with a Text Field (Name).
3- Create a Content Type (Movie) with a Text Field (Title), a Relationship Field One to One (Rating), a Relationship Field Many to Many (Cast).
4- Create contentlets of each Content Type and relate them.

Velocity:
On a Simple Widget add the following code
```
#foreach($con in $dotcontent.pull("+contentType:Movie +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST)",10,"modDate desc"))
$con.title</br>
$con.rating.rated()</br>
$con.cast.size()
#end
```

ContentResource:
`http://localhost:8080/api/content/render/false/query/+contentType:movie/depth/1`

ESContentResourcePortlet:
```
curl -H "Content-Type: application/json" -XPOST http://localhost:8080/api/es/search?depth=1 -d '
    {
        "query": {
            "bool": {
                "must": {
                    "term": {
                        "contentType": "Movie"
                    }
                }
            }
        }
    }'
```

On each call the `rating` field should **not** be a list and the `cast` must be a list.

**Comment by erickgonzalez** [comment]
Can't Test graphQL b/c of this ticket https://github.com/dotCMS/core/issues/16027

**Comment by erickgonzalez** [comment]
GraphQL:
```
{
  movieCollection{
    title
    identifier
    cast{
      name
    }
    rating{
      rated
    }
  }
}
```

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
Documented Here: https://dotcms.com/docs/latest/content-object-in-velocity#FieldRelationship
