### ISSUE TITLE
Allow to change the Identifier asset name

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15803]
We need to allow the user to change the `Identifier` `asset_name`:

- [x] If you upload a new file (with a different name), we ask if you want to update the real url for the asset. If so, we update the identifier, else not.
- [x] We allow people to edit the identifier name on edit content screen.
- [x] When we "rename" or "move" the file, all we need to do is rename the identifier

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15890

**Comment by jgambarios** [comment]
**Note to QA:** This ticket passed the Internal QA but we found some related small cache issues that will be address here: https://github.com/dotCMS/core/issues/16052

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
