### ISSUE TITLE
Hide dialog actions when active tab doesn't need it

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15805]
When editing anything in a dialog with tabs and some of the tabs doesn't need the dialog actions (like save and cancel) we should hide it.

## Acceptance Criteria

1. When editing a field in content types and go to the tab "Field Variables" the Save and Cancel button should hide.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
