### ISSUE TITLE
Don't update the Identifier asset name on regular save 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15804]
Currently any save on a file asset will update the `Identifier` `asset_name`, now we want to avoid that behaviour:

- [ ] On the first upload, we take the name of the file for the identifier
- [ ] On saving, we don't update the identifier with the new file name.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/issues/15800

**Comment by fabrizzio-dotCMS** [comment]
This was a solution initially proposed to solve the update constraint issue that we were seeing but this wasn't implemented to solve the problem.
