### ISSUE TITLE
Change file name by identifier asset name

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15801]
This is mostly a display change where instead of the uploaded file name we display the `Identifier` `asset_name`.

We need to apply that change in:

- [x] We change the browser to show identifier name
- [x] We change edit content "file name" field to show identifier name
- [x] We change the "File Name" to show the identifier name in the Content search
- [x] We need to fix the file asset control to show the proper "resource link"

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15890

**Comment by jgambarios** [comment]
**Note to QA:** This ticket passed the Internal QA but we found some related small cache issues that will be address here: https://github.com/dotCMS/core/issues/16052

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF,  the complete changes should be tested after the fix #16052
