### ISSUE TITLE
Client Side URL Redirection Vulnerability

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#15810]
Since this is a security related issue, details will not be posted here.

dotCMS engineers can access details here:  https://docs.google.com/document/d/1UUrSLLNzariCUAqJPd-oVKIAprzn2HKv-z7HfnVQMXY/edit#

**Comment by brentgriffin** [comment]
Added to known security issues here:  https://dotcms.com/security/SI-46

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15818

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now this work as expected
