### ISSUE TITLE
Arbitrary File Creation Vulnerability

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#15812]
Since this is a security related issue, details will not be posted here.

dotCMS engineers can access details here:
https://docs.google.com/document/d/1eNEJbEu03rjA1dWPfK2TvsiX2dX_h8zZd7uClmA-4zk/edit#heading=h.pjahln66l7zp

**Comment by brentgriffin** [comment]
Added to known security issues here:  https://dotcms.com/security/SI-48

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16109

**Comment by bryanboza** [comment]
Fixed, tested with the steps of the attached files and now I'm unable to reproduce
