### ISSUE TITLE
Redirect URL field doesn't save

### ISSUE THREAD

**Issue by Djacomo** [dotCMS/core#15814]
## Expected Behavior
Redirect URL Page Asset field doesn't save any value.

## Possible Solution
For "dijit.getById()" element change event seems is "onChange" not "onchange":
dojo.connect(dijit.byId('text8'),"**onChange**",updateRedirectValue);
URL to my [gist](https://gist.github.com/Djacomo/a6881f68dafd8d5e71006dd7224b9cd7)

## Steps to Reproduce (for bugs)
1. Edit a Page Asset
2. Insert a "Redirect URL" value (both manually and via "Select Link")
3. Save and Publish the page

## Your Environment
* dotCMS version used: 5.0.3
* Operating System and version: GNU/Linux Ubuntu

**Comment by mattyarbrough** [comment]
This has also been replicated on a client site running Windows, no information in the browser dev console or logs indicating an error.

**Comment by mattyarbrough** [comment]
In the instance I witnessed of this happening there are two 4.1.1 clusters, it happens in one of them but not the other.
