### ISSUE TITLE
Copy page does not create a copy of the Custom Layout

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15813]
Tested on dotCMS Release version 5.0.3

When you copy a page via the site browser, we are not copying the custom layout, so if you make a change to one layout, you end up changing the layout of the other page as well after the copy.  

When we copy a page, we should copy the custom layout as well, so that the Custom Layouts are independent between the copied pages and changes to the Custom Layout of one page does not affect the Custom Layout of the original copied page.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16118

**Comment by dsilvam** [comment]
Passed Internal QA: Copying the page results in a new layout which can be freely modify without affecting the original page.

**Comment by bryanboza** [comment]
After creating the copy, we are including this new `custom page layout`  in the list of templates, this should be used only by the page, we need to exclude those customs from the list 
SC: https://screencast.com/t/cDNICrntK

**Comment by erickgonzalez** [comment]
The comment above is not an issue, the **custom page layout** is shown on the UI to let the users know that the page is using that as a template. But if you go to the template portlet or another page that is using a template (e.g index) you can not see that template in the list of templates.

**Comment by bryanboza** [comment]
That's the expected behavior... Passed
