### ISSUE TITLE
1-1 relationship allows you to add more than 1 contentlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15819]
If you define a relationships as 1 to 1, the UI allows you to add more than one contentlet to the relationship and then throws an error when you try to save.

Also, the error message is not very helpful - it should say that the relationships is 1-1 and you cannot add more than one content to this relationship.

![screen shot 2019-01-10 at 2 29 42 pm](https://user-images.githubusercontent.com/934364/50993119-db8d1280-14e6-11e9-9b37-4b72efd1c3c0.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15830

**Comment by bryanboza** [comment]
I think we need to continue with the relationship validation as we do in previous versions. But we need to validate this on the related window when you try to relate with multiple contents selected, and not when you try to save&publish. Also, we can improve the message. 
We need to validate at this point: 
<img width="1529" alt="rel1" src="https://user-images.githubusercontent.com/2641437/51278857-4b951000-19a1-11e9-89fa-f86064689a6c.png">


Right now after this fix, when you try to relate multiple contents and the relationship is one to one, we add to the relationship just one of the selected contents, and this looks like an issue. Or that we are losing the selection.

**Comment by wezell** [comment]
@bryanboza can you confirm that only one gets added?

**Comment by bryanboza** [comment]
Yes, I think the first selected. But I think we can improve the UX here

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15889

**Comment by fmontes** [comment]
Javascript error in FF when you try to relate 1-1 same content types: Employee - Employee for example.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15911

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
