### ISSUE TITLE
Document Custom Events in core

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15823]
We need to doc the events that are available in core and or edit mode

- Edit Content Window
- Reorder Menu
- Page Navigation
- Add, edit, delete contentlet.

## Acceptance Criteria

1. We need: the string of the event, what it does and what we need to pass along
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
The initial documentation of `ng-events` send from the jsp's to the Angular app: 

https://gist.github.com/hmoreras/b499ed7f174f616674f70248b038e975

**Comment by fmontes** [comment]
https://gist.github.com/fmontes/0385aee25bc6ebddfd5b10818a9d1899
