### ISSUE TITLE
editContentlet macro doesn't work on template VTL code

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15822]
Reported via Support: Ticket [97136](https://dotcms.zendesk.com/agent/tickets/97136)
Reproducible in dotCMS 5.0.3

editContentlet macro fails when it's included directly in a template VTL instead of including it in a container or widget VTL.

## Expected Behavior
editContentlet macro should work and let users edit contentlets when it's displayed in edit mode, even if it's used outside a container.

## Current Behavior
editContentlet macro works when it's included in a container or widget VTL, but doesn't work when it's included directly in a template VTL.

## Possible Solution
It's seems there's javascript code that finds the container that contains the editContentlet macro, and it's triggers an error when there's no container. Maybe an additional check can be included to handle this scenario.

## Known Workarounds
Don't use editContentlet macro directly in a template VTL, but use it inside a separate container.

## Steps to Reproduce (for bugs)
1. Create a new advanced template
2. In the VTL code section, add the editContentlet macro to display the Edit Button for some contentlet(s). For example:
```
<div>
    <h3>News</h3>
    #foreach($con in $dotcontent.pull("+contentType:News",10,"News.title"))
    <div>
        #editContentlet($con.inode)
        News item: $con.title
    </div>
    #end    
</div>
```
3. Create a new page that uses the template from the above step.
4. Open the new page in edit mode.
5. Click the edit button to edit one of the contentlets.
<img width="763" alt="editcontentlet-screen" src="https://user-images.githubusercontent.com/2894221/51045238-bd77ee80-1588-11e9-8792-30dfb036f029.png">

6. The following exception is triggered in the browser by javascript:
```
Uncaught TypeError: Cannot read property 'dataset' of null
    at t.getCurrentContentlet (2.dbe8c60d7632bc667fb8.chunk.js:1)
    at docClickHandlers.edit-content (2.dbe8c60d7632bc667fb8.chunk.js:1)
    at t._next (2.dbe8c60d7632bc667fb8.chunk.js:1)
    at t.__tryOrUnsub (vendor.0afcafa4fe02b99ef907.bundle.js:1)
    at t.next (vendor.0afcafa4fe02b99ef907.bundle.js:1)
    at t._next (vendor.0afcafa4fe02b99ef907.bundle.js:1)
    at t.next (vendor.0afcafa4fe02b99ef907.bundle.js:1)
    at HTMLDocument.<anonymous> (vendor.0afcafa4fe02b99ef907.bundle.js:1)
```

## Context
This has been reported by customer via Support: Ticket [97136](https://dotcms.zendesk.com/agent/tickets/97136)
The client is trying to use the editContentlet macro in the template VTL code instead of including it in a container or widget. 

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Chrome version 71.0.3578.98 (64-bit)
* Operating System and version: macOS version 10.14.2
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module: Page edition

**Comment by Xander-Steinmann** [comment]
As a workaround you can add the missing div yourself. See https://groups.google.com/forum/#!topic/dotcms/jCvvCfYm-DA

But I would also like to see this fixed, if possible.
