### ISSUE TITLE
Upgrade task for FileAsset Content Type

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15828]
We need to create an upgrade task in order to disable the `ReadOnly` property in the `File Name` field for `FileAssets` in order to allow to modify that field from the UI.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15890

**Comment by jdotcms** [comment]
FileAssetsResource
- Does not support shorty id
- if the inode does not exists, return 500

**Comment by jdotcms** [comment]
Note: As part of the issue has to test that the name could be change on diff languages
and that the resource link still working after the rename

**Comment by jdotcms** [comment]
Changing the name on file asset on ESP and ENG, affects both versions (both share the same lang)

**Comment by jdotcms** [comment]
If you add some weird characters to the file name such as:

asset.vtl-----1243~`@#3+-*/./'   ===

The save works fine, but the resource link does not

**Comment by jdotcms** [comment]
Webdav rename works fine

**Comment by jdotcms** [comment]
Push Publish works ok

**Comment by jdotcms** [comment]
Upgrade task works

**Comment by jgambarios** [comment]
Passed internal QA as the Upgrade task works as expected, requested improvements will be handle in https://github.com/dotCMS/core/issues/16488

**Comment by bryanboza** [comment]
Fixed, tested upgrading from 5.1.1 to master and works as expected

**Comment by bryanboza** [comment]
Fixed, tested in all the supported databases and the upgrade task is running without problems

**Comment by bryanboza** [comment]
Fixed, new problems with upgrades created in a separate issue.
