### ISSUE TITLE
Content Types  - Creating a new row and dropping fields into it creates more rows

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15836]
In the content type editor, when you create a new row and drop fields into it, it creates a new row for every field dropped into the row.

**Comment by wezell** [comment]
### Oddness 1

![field-dragging](https://user-images.githubusercontent.com/934364/51187078-0d1c2a00-18a9-11e9-9adb-6a7d98eab742.gif)

**Comment by bryanboza** [comment]
Fixed, tested in the last master code // Oracle // FF and I'm unable to reproduce

**Comment by fmontes** [comment]
@hmoreras found an error here:

>The message regarding this issue is correct however I found this:

https://www.screencast.com/t/aKV4RwRX

    After create a relationship, open it again to make it required, save, and then try to open, crash the first time.
    in the listing the text Required is not present once I make it required (like is in the field videos), a refresh of the page is required, this happening in all fields.
