### ISSUE TITLE
Remove servername and port from portal url generation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15833]
When the dotCMS generates a portal URL, it tries to figure out and include the servername, scheme and port. 

When running behind a proxy, like when in our docker stack, if you try to run the stack on a non-standard port where dotCMS thinks it is running on one port rather than on another, it gets the generated url wrong.  In fact, dotCMS doesn't and can't know what port it is answering on in our docker stack without a plugin and that should not be a requirement.

With the change, it goes from this:
## With Host
https://gist.github.com/wezell/a21419f72a0fc34779fa8351ecc736bd

## Without Host
https://gist.github.com/wezell/db7d56b023a26a14b09fc77770f32dc4

**Comment by wezell** [comment]
Testing - this might affect the "assigned to" workflow email.  If so, we need to give instructions on how to change it.

**Comment by jgambarios** [comment]
https://github.com/dotCMS/core/pull/15834

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
