### ISSUE TITLE
Relationship fields is not working as expected when one of the side of the relationship is removed

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15840]
As a stakeholder I want to make sure relationships works as expected event when one of the side of the relationships (a content type) is removed.

## Possible Solutions
1. Warn the user when try to remove a content type that is related?
2. Remove the relationship field when one of the side is removed?
3. Disabled the the relationship field when one of the side is removed and allow the user to select another relation?

## Steps to reproduce
1. Create a relationship field between A and B
2. Remove B content type
3. Go and check the UI, the relation still "Exist" but is because the endpoint is returning it.

## Acceptance Criteria
1. ?????
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15850

**Comment by erickgonzalez** [comment]
Now the field on the parent is deleted if the child content type is deleted.

**Comment by erickgonzalez** [comment]
New scenario found: 
1- Create a Relationship between A and B 
2- Create a Relationship between B and A using the existing option
3- Delete A, should delete the field on B.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15861

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF  and now it is working as expected
