### ISSUE TITLE
We need to show visual scroller on field properties

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15848]
Tested on latest master (for 5.1)

As you can see in the image below, when adding a text field there is no visual reference to tell the user that there are more properties at the bottom that the user needs to scroll to:

![Screen Shot 2019-01-16 at 3.43.26 PM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/933708e6-585c-461e-8ae1-8c4f79c9b8f1)

Here are the rest of the properties that are only revealed if the user is experienced with dotcms and tries to scroll on their own:

![Screen Shot 2019-01-16 at 3.44.32 PM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/796dd692-996c-41e4-9b13-fc02d6dfd133)

We need a visual reference (scroller) to appear always or something to tell the user that there are more properties below.

**Comment by fmontes** [comment]
Use: https://github.com/MurhafSousli/ngx-scrollbar

**Comment by fmontes** [comment]
We fix this with CSS and the results:

1. Chrome and Safari: will show the scrollbar all the time when needs to scroll (css)
2. Firefox: will show the bar and fadeout (browser default) is like an indicator that you can scroll
3. Edge: will show the Windows scrollbar on hover

**Comment by bryanboza** [comment]
Fixed, now we have an scroller on this window
