### ISSUE TITLE
Make System fields removable

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15847]
We have a bunch of system fields that should be removable. Not saying they shouldn’t be there automatically but they should be removable if the user chooses to.  We will need StartupTasks to update existing content types and will need to update the base types to match

### Content Base Type
No field should be marked as system or fixed

### Page Asset Base Type
Only require
- Title
- Host/Folder
- Url
- Template

### Widget Base Type
Only require
-  Widget Title - ~**IMPORTANT: Make the label of this field editable!**~
- Widget Code

### File Asset Base Type
Only add
- File Name
- Host/Folder
- File Asset
- Metadata tab (should be removable)
- Metadata

### Persona Base Type
Description field should be removable

### Host
- Run Dashboard (should default to false)
- Host Thumbnail

## Acceptance Criteria
The description posted by Will, stating what fields must show up and should be removable.

**Comment by fmontes** [comment]
As per @fishsmith let's make the widget title field label editable.

Sometimes we want to called like "Headline" or something more user-friendly and we end up adding a text field for that.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_45223903_SNAPSHOT // Docker // macOS 13.0 // FF v106.0.3

**Note:** Widget Title - IMPORTANT: Make the label of this field editable! was strikethrough.
