### ISSUE TITLE
We are unable to see the content of a container as a file after unpublish and publish again

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15853]
When you are unsing a container as a file, and you unpublish the file, we need to hide the container of the live version of the page. But when you publish again, we are unable to see the content of the container again in the live version of the page 

## Steps to Reproduce (for bugs) 
1. Login as admin 
2. Upload a new container as a file 
3. Create a new template using this container 
4. Add more containers to the page 
5. Add content to the page containers 
6. Go to site browser and unpublish the `container.vtl` file 
7. Refresh the page from front end 
8. Go and publish the `container.vtl` again
9. Refresh the page 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15857

**Comment by bryanboza** [comment]
We continue with the same problem after adding a piece of content to an unpublished content type, then when you publish the container and go to the page again, you are unable to see the content on live mode...
To recreate: 
- Login 
- Create a new container as a file
- Unpublish the container
- Create a new template using the new container 
- Add a new piece of content to the page and save & publish
- Go and publish the container 
- Try to see the page in live mode

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16061

**Comment by jgambarios** [comment]
I'm still able to see the original issue, sending this ticket back.

**Comment by bryanboza** [comment]
The same happens with the content type (vtl) files

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16175

**Comment by jgambarios** [comment]
The cache issue is fixed, we just need to exclude from the edit mode archived containers.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16185

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
