### ISSUE TITLE
Cardinality Test and convenience method

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15856]
Add an `onlyAllowOne()` method to Relationships (in `ContentletRelationships`?) that can be used to check if a relationship side only allows a single entry

Also, I think we should only allow reordering from a single side of a relationship - in this case, from the parent.  We should not care or store how a child reorders the parent.

Then we need to write these Integration tests to make sure the logic is valid:
- Add Content Type A
- Add Content Type B

- Create one to one from A to B     -->    should allow only 1 from A and only 1 from B
- Create one to many from A to B    -->    should allow many from A, only 1 from B
- Create many to many from A to B   -->    should allow many from A, many from B

- Create one to many from B to A    -->    should allow only 1 from A and many from B

- Create one to one from A to A     -->    should allow only 1 from A field1 and only 1 from field2
- Create one to many from A to A    -->    should allow many from A field1 and only 1 from field2
- Create many to many from A to A   -->    should allow many from A field1 and many from field2

**Comment by nollymar** [comment]
I think the right place would be ContentletRelationshipRecords
