### ISSUE TITLE
Allow users to set CORS Policy

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15862]
Our current CorsFilter 

https://github.com/dotCMS/core/blob/5.0.3/dotCMS/src/main/java/com/dotcms/rest/api/CorsFilter.java#L18

 is set to allow most requests and cannot be easily overridden by system users.  We need to allow users to configure appropriate Cors Policies and headers based on their requirements.  Additionally, we do not seem to care if the header has already been set - we need to allow users to override the set policy on a case by case basis using plugins.

**Comment by brentgriffin** [comment]
For dotCMS engineers:  https://docs.google.com/document/d/1LmYBstgaFrOmOYgRfsYFqezYRRKHwaDxmwPOwLbVIjg/edit#

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15866

**Comment by wezell** [comment]
### CORS Headers:

dotCMS allows you to specify CORs headers to include in its REST responses.  These CORS headers can be set as global defaults and can be overridden on an endpoint by endpoint basis by adding the appropriate entries the `dotmarketing-config.properties` file.   A dotCMS REST resource will send either resource specific headers if any are specified OR fall back to the default CORS headers - the default CORS headers are not additive or "inherited" if they have been overridden for a REST resource.

### Setting Default CORS Headers
To set a default CORS headers, create a property entry in the `dotmarketing-config.properties` that follows this pattern  `api.cors.default.${header-name}=${headerValue}`

This means that if you want to set the default header `Access-Control-Allow-Origin : *`, you add this property  `api.cors.default.access-control-allow-origin=*` to your property file.  dotCMS ships with these properties which are included in all REST API responses.
```
api.cors.default.access-control-allow-origin=*
api.cors.default.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.default.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS
```
### Overriding CORS on specific resources
You can also override CORS headers per resource by replacing `.default.` in the property name with the resource java class name lowercased.  

By way of example, the `/api/content` REST calls are served by the `ContentResouce.class` internally.  To set specific CORS headers for this resource, you would add entries like the following
```
api.cors.contentresource.access-control-allow-origin=https://demo.dotcms.com
pi.cors.contentresource.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.contentresource.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS
```

To get a sense of the resource names that will respect the entries in the dotmarketing-config.properties, see this list of classes:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/config/DotRestApplication.java#L65

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle  // FF... Now we this values by default and also we are able to override for specific resources without problems.
