### ISSUE TITLE
Unable to edit page content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15871]
We have problems when you edit a page content type, this because if you add a new row and a new field, we are moving the existing or `system fields` to a new row too... 

## Expected Behavior
We need to be able to edit this kind of content types without problems in order to create custom content  types 

## Current Behavior
After you edit a page content type we are moving the `system fields` to a new rows 
SC: https://screencast.com/t/PN16ceKDZN

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to content types 
3. Create a new page content type  
4. Add a new wor and add a new text field to this row 

## Your Environment
Tested on master // Oracle // FF

**Comment by bryanboza** [comment]
We continue with problems with the same case: https://screencast.com/t/L87LcAp7jCp

Now the row is disappearing

**Comment by fmontes** [comment]
@bryanboza we add a loading indicator while the field is saved.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF. After this fix, I'm unable to reproduce the problem
