### ISSUE TITLE
Reflected XSS issue

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#15870]
Reflected XSS issue reported - details for dotCMS engineers here:  https://docs.google.com/document/d/1qZad2A6tOQifsaF44bALWOLGWKk-HGyRnIOih14_0zw/edit#

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15872

**Comment by bryanboza** [comment]
Now we are unable to access, we are showing a 401 unauthorized error here. But we need to log something in the security.log file.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15952

**Comment by bryanboza** [comment]
Now we log if you are trying to access from a browser with no session if you try from a browser tab with the session we are not logging anything.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15964

**Comment by bryanboza** [comment]
We need to fix the problem mentioned in my last comment

**Comment by bryanboza** [comment]
Ok, after talk with @wezell seems is ok for now
