### ISSUE TITLE
Unable to display custom tool groups in the left menu 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15878]
We have a JS error when you try to create a custom tool group, and we are unable to add this group to the list in the left menu 

## Expected Behavior
We need to be able to add a group of tools without problems. 

## Current Behavior
If you add a new custom group and enable the checkbox to add to the list of displayed tools in the left menu, we have a JS error and we are unable to load the complete menu 
SC: https://screencast.com/t/4Roc8gBEmkX

<img width="1687" alt="js1" src="https://user-images.githubusercontent.com/2641437/51643409-f5404800-1f31-11e9-9f9b-59255834fc72.png">

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to System --> Roles & Tools 
3. Select CMS Administrator --> Tools and create a custom group of tools 
4. Enable the checkbox to add to the menu list 
5. Refresh the browser tab 

## Your Environment
Tested on master // Oracle // FF

**Comment by bryanboza** [comment]
Also,  we need to set a default value for the icon, this in order to use the minimized view in the left menu. https://screencast.com/t/5lx4Pf0Te

**Comment by wezell** [comment]
I believe this is only the case on oracle and is fixed by adding an iconClass, which you need anyway
