### ISSUE TITLE
Need auto adjust the left menu size in case of translations 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15877]
When you change the CMS language, we need to auto adjust the menu size, this to allow read the entire name of the portlet 

<img width="1665" alt="left" src="https://user-images.githubusercontent.com/2641437/51642126-db046b00-1f2d-11e9-8695-ca163306124d.png">

## Your Environment
Tested on master // Oracle // FF 

## Acceptance Criteria

1. Make it wrap (as per @wezell comment)
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
We need smaller translations

**Comment by wezell** [comment]
Actually, let's wrap the words

**Comment by fmontes** [comment]
<img width="338" alt="screen shot 2019-02-12 at 11 22 31 am" src="https://user-images.githubusercontent.com/751424/52654866-8d3dab80-2eb8-11e9-8d89-7422a9baa91d.png">

**Comment by bryanboza** [comment]
We continue with problems when you have really long names on tools 
SC: https://screencast.com/t/uVDZFBEg3D

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now is working as expected
