### ISSUE TITLE
Add “card” border wrapper to rules

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15886]
The rules have been brought into core-web, which is great.  We just need to add the "card" wrapper around them so they look like the rest of the system.

![screen shot 2019-01-23 at 5 30 00 pm](https://user-images.githubusercontent.com/934364/51698320-de543100-1fd7-11e9-9c46-2b137d5cd5c8.png)

**Comment by fmontes** [comment]
Please add min-height 100% so the shadow show "fullscreen"
