### ISSUE TITLE
Improve naming for converted relationship fields

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15888]
When we convert an existing relationship field we end up with a field that often has the name and variables "Parent" or "Child" in it, e.g.

ParentBlog - parentblog
ChildComment - childcomment

It should be:

Blog - blog
Comments-comments

We should try to be a little smarter in renaming the relationship especially as the variables cannot be changed once set.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15897

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
