### ISSUE TITLE
SPAEM: Create react carousel component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15898]
As a stakeholder I would like to provide a Carousel Widget in the starter site.

## Banner Carousel DotCMS Widget
1. Number of results
2. Sort by
3. Fields to display: title, caption

## Solutions
1. Get Banner contentlets from Content API (or Elastic Search)
2. Build a react component that render those into a Carousel (use reactstrap).
3. Add the widget to the homepage
4. Match the widget with the react carousel component

## Acceptance Criteria
1. Should see the carousel component in the SPA homepage
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
SortBy: title & publish date

**Comment by alfredo-dotcms** [comment]
Data when creating a `Content Type`:
`Number of results` —> Textbox

`Fields to display` —> Checkbox
```
Title|title
Caption|caption1
```

`Sort results by` —> Select
```
Title|title
Modification date|modDate
```

`Sort Order 1` —> Radio
```
Asc|asc
Desc|desc
```
