### ISSUE TITLE
Page endpoint json contentlets not returning in the right language

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15893]
![Screen Shot 2019-01-24 at 4.24.14 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d5bcb7fc-b2db-4bdf-9190-e9da0313397b)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15895

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
