### ISSUE TITLE
Minor: Pagination buttons need the same size in content search modal

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15899]
This is just a UI improvement. 

When you are adding a piece of content to any page, on this modal the pagination buttons should have the same size. 

## Expected Behavior
Both buttons should have the same dimensions  

## Current Behavior
When you paginate on this window the buttons are different 
<img width="1525" alt="pag1" src="https://user-images.githubusercontent.com/2641437/51755956-752af700-2085-11e9-804c-25aba1d20f9b.png">

## Your Environment
Tested on master // Oracle // FF

**Comment by fmontes** [comment]
Should not be the same size, size is based on the content.
