### ISSUE TITLE
Many to Many Relationships are not working on both sides

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15904]
Tested on latest master.  Many-to-many relationships between two content types allow only one relationship on one side of the content fields.  The other side disables the relate content button on the relationship field as if the relationship were "one to many" instead of many to many.

To test first create two content types and add a relationships field to both of them, the first being "many to many" and on the second content type choose "existing relationship" and choose the many to many relationship listed.
Then try to add multiple contentlets from both sides.

In the example relationship below, I was able to add multiples from only one side:

![Screen Shot 2019-01-25 at 1.07.18 PM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/962dd4e5-8dd2-4917-9f78-96827e2978ae)  

this relationship works fine on one side

![Screen Shot 2019-01-25 at 1.02.19 PM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/3246e896-0429-4880-981c-2fe313b0be54)  

but is disabled from the other:

![Screen Shot 2019-01-25 at 1.09.43 PM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/20086cfb-cc33-46f7-9018-1ec3fd234fcd)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15905

**Comment by DeanGonzalez** [comment]
This passes for the 5.1 release.  I did add an enhancement task for post 5.1 on something minor here: https://github.com/dotCMS/core/issues/15904
