### ISSUE TITLE
Default File Type not respected when adding through content

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15923]
If you add a file to a folder via a content add it will be the File Asset file type rather than the folder default.

## Steps to Reproduce (for bugs)
1. Create a new file Content-Type (NewFileType)
2. Set a folder to have NewFileType as the default file type 
3. In Content Search select "add new content" of a type that includes a file upload (Event, for example).
4. In that content select "Add a File" dialogue
5. Navigate to the above folder
6. Select to Add a File rather than using an existing one
7. Once file is uploaded, navigate to the folder in Browser, it is the File Asset content type rather than the NewFileType content type.

## Your Environment

* dotCMS version used: 4.1.1, 5.0.3

**Comment by florianschuetz-diva-e** [comment]
If a user has no access to the default File Asset content type, this just results in an error message that doesn't give a real clue about the reason (in v4). This has already caused issues with out customers.
