### ISSUE TITLE
Page API json method missing properties

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15928]
The page API `/render/` method contains properties (e.g. viewAs) that are not included in the page API `/json/` method.  Edit Mode Anywhere means that these methods need to return the same properties, with the `/render/` method only adding the rendered properties.

### json
![screen shot 2019-01-30 at 7 40 07 pm](https://user-images.githubusercontent.com/934364/52023098-c6921680-24c9-11e9-9344-1890d9d73baf.png)

### render
![screen shot 2019-01-30 at 7 39 51 pm](https://user-images.githubusercontent.com/934364/52023102-ce51bb00-24c9-11e9-9c52-60cd3b049760.png)

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
