### ISSUE TITLE
Missing scrollbar on relate content search window

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15922]
Reported via support ticket: [97411](https://dotcms.zendesk.com/agent/tickets/97411)
Reproducible in dotCMS 5.0.3

The vertical scrollbar is missing when the searchable fields require more space than the window height on the relate content search window.

## Expected Behavior
When the searchable fields require more space than the window height, a vertical scrollbar should be available on the browser for the panel containing the search fields.

## Current Behavior
If the searchable fields require more space than the window height, vertical scrollbar is missing and users can't scroll on the panel containing the search fields.

## Possible Solution
A code/style fix can be done to enable scrolling on the panel containing the search fields. 

## Known Workarounds
Use `Tab` key to move between the search fields, instead of scrolling on the panel.

## Steps to Reproduce (for bugs)
1. Log into dotCMS 5.0.3
2. Add searchable fields to the content type to be used in the relationship (6 or more fields searchable field should be enough)
3. Edit a content item that includes a relationship with the content type from the previous step
4. Click on the Relationships tab to add related content.
5. Click the Relate button to show the related content search window.
6. Vertical scroll bar is missing on the left panel containing the search fiedlds.

<img width="1096" alt="missing-scrollbar" src="https://user-images.githubusercontent.com/2894221/51937879-50aa8400-23d1-11e9-8790-3ebd25ddccd6.png">

## Context
This issue prevents users from using related content search window to search the content to be related.
This was reported by client in this support issue: [97411](https://dotcms.zendesk.com/agent/tickets/97411)

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Chrome version 71.0.3578.98 (64 bit)
* Operating System and version: macOS version 10.14.2
* Application Server and version: not relevant
* Java Brand and version: not relevant
* Database and version: not relevant
* Application module (if apply): content edition

**Comment by wezell** [comment]
@bryanboza please test on 5.1

**Comment by nollymar** [comment]
I think this PR can fix the issue https://github.com/dotCMS/core/pull/15916
