### ISSUE TITLE
Error adding related content using the Relationships Tab

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15921]
It is not possible to add related content using the Relationship Tab. Once you select the related content, it's displayed as "Undefined" on the Related Content table. Watch this video: https://www.screencast.com/t/jocF8673. 

## Steps to Reproduce (for bugs)

1. Create two Content Types A and B
2. Add a non-required relationship field from Content Type A to Content Type B (Many to many)
3. Create a contentlet of Type A without related contents
4. Create a contentlet of Type B and try to related it to the contentlet created on Step 3 using the Relationship Tab. 

**This test was done using relationship fields, however, it's also happening for legacy relationships.**

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16029

**Comment by erickgonzalez** [comment]
Working as it should, now for the Relationship Field this does not apply b/c of this ticket https://github.com/dotCMS/core/issues/16010

**Comment by bryanboza** [comment]
Fixed, after the last changes we are unable to see this tab if don't have legacy relationships
