### ISSUE TITLE
New fire endpoint needs multipart support

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15935]
Workflow fire:

- [x] We need to support multi-part binary files (can have multiple pre put)
- [x] We need to support workflow action names as well as id - these need to a property of the json object
- [x] We need to support relationships as we do in the contentlet resource
- [x] support json param `contentlet` as well as `contentletFormData` for the propertyMap

 

As a user, I need be able to add any kind of contentlets from the new fire endpoint

## Expected Behavior
As in the `/api/content/publish/1` endpoint, we need support multipart 

## Current Behavior
We are unable to upload contents to structures like `fileAssets` using the new fire endpoint of the workflow resource. 

## Your Environment
Tested on master // Oracle // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16294

**Comment by fabrizzio-dotCMS** [comment]
I tried creating and updating 3 different Content types.

- Employee
- fileAsset
- Persona

 And it works just fine. 

Here a curl example used to update an existing contetlet.

` curl -v -u admin@dotcms.com:admin -X PUT \
http://localhost:8080/api/v1/workflow/actions/b9d89c803d/fire?identifier=b105eddc-e4b0-4a7f-85ad-b09d29a1c31b -F "json={
    'contentlet': {    
           "contentType":"fileAsset",
           "languageId":1,
           "hostFolder":"demo.dotcms.com",
           "fileName":"liz2.jpg",       
           "title":"liz!"
     }
   }; type=application/json" -F "file=@//Users/fabrizzio/Downloads/liz.jpg; type=application/jpg"      
`

**Comment by bryanboza** [comment]
Fixed, tested with the provided examples and now this works without problems.... Tested on master

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/workflow-rest-api#ActionExecute
