### ISSUE TITLE
Content resource don't allow send text files via REST

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15934]
We have problems to add new file assets or save content with any binary field when you try to send a text file via REST 

## Expected Behavior
We need to be able to save contentlets with any kind of field without problems 

## Current Behavior
When you try to send a text file, we are showing an invalid field error and we are unable to save the content.
SC: https://gist.github.com/bryanboza/589165add15f7ab1b592feff2afd02d4

**FYI:** If you try with any other file is working as expected. 

## Steps to Reproduce (for bugs)
To recreate you need to send via REST the file assets form values to this endpoint, using a txt file to the `fileAsset ` value `http://localhost:8080/api/content/publish/1` 

## Your Environment
Tested on master // Oracle // FF

**Comment by jdotcms** [comment]
This is layer 8, hehe
You can do this and works fine:
```
curl -v -u admin@dotcms.com:admin -X POST \
 http://localhost:8080/api/content/publish/1 \
 -H 'cache-control: no-cache' \
 -F 'json={
    contentType:'\''fileAsset'\'',
    hostFolder:'\''demo.dotcms.com'\'',
    title:'\''api008b.txt'\'',
    fileName:'\''api008b.txt'\''
};type=application/json' \
 -F 'file=@/Users/jsanca/Documents/tour-mexico.txt;type=application/plain'
```

**Comment by DrDizzle** [comment]
The problem seems to be processing the type text/*,
as application/plain does work, but text/plain does not. From our tests, the same goes for html. So, I'd assume it's about text/* in general.
Many clients prefer using text/* (Postamn will use it automatically for example).
I suggest enabling text/* types.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16251

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16297

**Comment by bryanboza** [comment]
Fixed, tested on master after the last changes and now I'm unable to reproduce
