### ISSUE TITLE
Update getRelatedContent method

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15941]
In moving relationships to a nested field, we will need to rewrite the getRelated content methods to query the nested values appropriately.

if the getRelated call includes additional ES query params and we are querying children, we will need to pass in the related ids to search (either from a previous query or from the contentlet.getRelated("fieldName") and append the condition.

If querying parents, we will need to build query the nested field and append the additional conditions to the parent

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/enterprise-2.x/pull/667
https://github.com/dotCMS/core/pull/16603

**Comment by nollymar** [comment]
**Note to QA:** It is important to test retrieving related content via rest API, especially the case when one content is related to another one and the rest api is called right after (with just a few seconds of difference)

**Comment by erickgonzalez** [comment]
Tested against these 2 REST: **ESContentResource** and **ContentResource** with diff depths and always returning all the relationships even when content is just related and the REST API called right away.

**Comment by bryanboza** [comment]
Fixed, tested both resources and works as expected

**Comment by wezell** [comment]
1. Move relationship cache to relationship cache
2. Add a region to the relationships cache for `content_relations` to store the contentlet relationships so it can be scaled independently of other regions
3. Move getRelated logic to `contentletAPI`
4. invalidate this cache when the `contentletcache` is invalidated 
5. add back to cache lazily

**Comment by nollymar** [comment]
Implemented here https://github.com/dotCMS/core/pull/16783

**Comment by erickgonzalez** [comment]
The following scenarios were tested and working as it should:
- ESContentResource and ContentResource with diff depths
- CRUD of related content
- Reorder related content
- Export content with relationships (legacy relationships are not exported)

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by wezell** [comment]
We need to document/changelog the fact that querying for related content needs to use the apis - either in Java or via rest - and that querying elasticsearch directly for relationships is no longer supported.  These queries should be rewritten to use the apis and the tooling around those, including the `?depth=2` parameter etc...
