### ISSUE TITLE
Change ES to use High Level ES client

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15942]
We need to move away from relying on the ES Transport client and move instead to the High Level ES Client.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high.html

There are performance considerations here and we might want to explore a short lived query cache when querying the live Elasticsearch index.

**Comment by dsilvam** [comment]
Changelog: 
ESIndexResource (unversioned) was deleted. Was marked for deprecation back in 4.0.0

**Comment by wezell** [comment]
We need to make sure we can survive an Elasticsearch outage.

**Comment by dsilvam** [comment]
Example VTL for listing aggregations: 

```
#set($esQuery = '{
    "aggs": {
        "content": {
            "terms": {
                "field": "contenttype",
                "size": 10
            }
        }
    },
    "size": 0
}')

#set($aggsQuery = $render.eval($esQuery))
#set($rawResults = $estool.search($aggsQuery))

#set($results = $json.generate($rawResults.response.aggregations.content.buckets))

#if($UtilMethods.isSet($results) && $results.size() > 0)
    #foreach($aggregation in $results)
         $aggregation.key ($aggregation.docCount)
    #end
#end
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16727
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/669
