### ISSUE TITLE
Containers not showing when moving a folder under application/containers folder 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15946]
On  Site/Browser:

if you add a folder directly under /application/containers/ and upload a bunch of vtl files they will  immediately get listed in the /Site/Containers screen

But if you create a folder lets say... under the host (root folder) and upload a bunch of vtls
Then have it moved under the /application/containers/ folder
 
The new templates will never get shown by the /Site/Containers screen.  

## Expected Behavior

A new Folder with all the vtls should appear in the /Site/Containers screen after moving the new folder

## Current Behavior

The /Site/Containers screen only shows Containers created directly under /application/containers/ via Site/browser

**Comment by wezell** [comment]
Nice one Fabrizzio

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16218

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
