### ISSUE TITLE
FileBrowserDialog file count is wrong when there are files in multiple languages

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15958]
Reported via support ticket: [97215](https://dotcms.zendesk.com/agent/tickets/97215)
Reproducible in dotCMS 4.3.3, 4.4.1, 5.0.3, 5.1.1, 5.1.5, and 5.1.6.

The file count summary on the FileBrowserDialog box (Viewing 1-10 of 10) is wrong when the folder being browsed contains file variants in multiple languages.

## Expected Behavior
FileBrowserDialog box shows a summary of current page/total file count at the bottom of the window: "Viewing 1-10 of 10". The files shown in the dialog are filtered for the current content language when there are variants in other languages. The summary should show the total of files being shown (instead of the total number of files for all the languages file variants).

## Current Behavior
FileBrowserDialog filters the files to show only files for the current content language, when there are variants in other languages. Also, it shows a summary with the current page/total count of the files, at the bottom of the window. The summary shows the total number of files for all the variants instead of the total number of files for the files listed in the window as expected.

## Possible Solution
Fix the code to show the file count of the filtered files by language in the summary.  

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Log into dotCMS 5.0.3
2. Add multiple image files in a new folder. For some of the added files add a version in other language.
<img width="921" alt="multiple-lang-folder" src="https://user-images.githubusercontent.com/2894221/52222061-415f8680-2868-11e9-829d-1d9101787275.png">

3. Go to the Content Search portlet and create a new content item for the Event type (other content type with a File field can work too) 
4. For "Image" field, click on "Browse" button (you can use other field of type File on other content type too) 
5. Go to the folder created in the step 2. 
6. The summary at the bottom of the window shows the total of files on the folder including variants in other languages:
<img width="1050" alt="select-file-summary" src="https://user-images.githubusercontent.com/2894221/52222100-4fada280-2868-11e9-95a9-ab5286031a0c.png">

## Context
This issue causes some confusion to users when they are browsing the folder and navigating between folder pages, since the summary at the bottom doesn't match the number of files being listed in the window.
This was reported by client in this support issue: [97215](https://dotcms.zendesk.com/agent/tickets/97215)

## Your Environment
* dotCMS version used: 4.3.3, 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): Content edition

**Comment by motiv-solutions** [comment]
This is still a problem in core
