### ISSUE TITLE
Push publish fails sending a page built on top of a template that uses containers as files. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15966]
Any page built on top of a template that uses a container as a file doesn't get sent using push publish  
Neither the page nor the containers get sent. 

A stack trace like this comes up : 

`com.dotmarketing.exception.DotDataException: Contentlets could have working versions for each language. at com.dotmarketing.business.VersionableFactoryImpl.findWorkingVersion(VersionableFactoryImpl.java:70) at com.dotmarketing.business.VersionableAPIImpl.findWorkingVersion_aroundBody0(VersionableAPIImpl.java:53)`  

## Expected Behavior

Any page built using the new containers as files should be sent together with all the respective dependencies (templates, containers, and vtls) to the push-publish destination environment 

## Current Behavior

Pages using containers as files aren't copied through push-publish. You'll see an exception and also a success message but in reality, the pages are never sent.

## Steps to Reproduce (for bugs)

1. Register a new container as files (using vtls etc.. ) and make sure they are available under 
Site/Containers.  

2. Then create a template based on the new container you created on step 1.
3. Create a Page Asset using the template created on step 2. 
4. Assuming that you have a push publish environment already configured. On: Site/Browser right click on the page created on step 3. and hit Push-publish. Select a destination environment and hit send. Watch the logs for the exceptions.
5. Verify the destination environment to make sure the page never got sent.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/16035
https://github.com/dotCMS/enterprise-2.x/pull/656

**Comment by bryanboza** [comment]
Tested after the last fixes and now we are able to send the page, but we lost the contents of the page... As in the normal process we need to send the complete page including the contentlets

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16172

**Comment by bryanboza** [comment]
Fixed, tested on the last master code and now we are sending the content as a dependency...
