### ISSUE TITLE
[Content Edit] : Missing vertical scrollbar on Content Edit portlet

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15963]
Reproducible in dotCMS 4.3.3 and the Demo Site (5.0.3).
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97246

When accessing the dotCMS back-end on Windows (even on Mac OS when activating the option to show scrollbars always) the **Edit Content** page is NOT displaying the vertical scrollbar to move up and down through the fields of a Contentlet. For some customers, this is important and required.

In dotCMS 4.3.3, it looks like this:
<img width="1154" alt="scrollbar-not-visible-433" src="https://user-images.githubusercontent.com/8779585/52227401-057eee00-2875-11e9-9318-5ba6d72bb39a.png">

And in dotCMS 5.0.3, it looks like this:
<img width="1154" alt="scrollbar-not-visible" src="https://user-images.githubusercontent.com/8779585/52227353-e1bba800-2874-11e9-9076-c8cf9024f20a.png">

## Expected Behavior
The vertical scrollbar should **always** be displayed, just like the one that shows up in the left main navigation menu.

## Current Behavior
The vertical scrollbar is not displaying at all. It flashes when resizing the window, but then it dissapears.

## Possible Solution
N/A

## Known Workarounds
Use the arrow keyboard keys, or the mouse scroll.

## Steps to Reproduce
1. Log into the dotCMS 4.3.3 back-end.
2. If you expand all the menu items in the left Main Navigation, you'll notice how the vertical scrollbar shows up automatically. This is correct and expected.
3. Now, go to the **Content > Search** portlet, and select the **Blog** Content Type or any other Type that has a long list of fields.
4. Notice how there's no vertical scrollbar on the right side of the page, which is not correct.

## Context
Customers with specific needs and/or requirements and types of Content Authors need this feature to work correctly.

## Your Environment
* dotCMS version used: 4.3.3, 5.0.3
* Browser Name and version: Not relevant.
* Operating System and version: Windows 7
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Editing.

**Comment by john-thomas-dotcms** [comment]
This is a long-standing issue, which I've filed bugs for twice.  The bugs keep getting closed as stale, but this is a daily annoyance for BE users that we should just fix.

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/issues/20947
