### ISSUE TITLE
 Errors after deletes container as a files 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15973]
When you are using a container as a file in a template and this in a page, if you delete the container we are having an exception when you try to open the page. 

## Expected Behavior
We need to find a way to handle that exception, or maybe delete the container references. 

## Current Behavior
When you try to open the page, we have a velocity error 
<img width="1470" alt="velerr1" src="https://user-images.githubusercontent.com/2641437/52306043-54538300-295c-11e9-8298-b0327bb0319b.png">

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new template using the container as a file that we have in the starter 
3.  Use that template in a new page 
4. Go to site browser and delete the folder under this path `/application/containers/`
5. Try to open the page again 

## Your Environment
Tested on master // Oracle // FF

**Comment by fabrizzio-dotCMS** [comment]
We would run into the exact same situation if we deleted or replace only the file **container.vtl** 
Let's suppose a user for some reason decides to first delete container.vtl  and upload a new one. 
The new **container.vtl** FileAsset would be created with a brand new identifier breaking all references with this container

**Comment by jdotcms** [comment]
if the container is in the same host of the page, the container path will be relative (without  the host)
otherwise if the container is not in the same host of the page, the container path will include the host too

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16048

**Comment by bryanboza** [comment]
After deleting the container we are showing a velocity error, this because the identifier is null, after delete any container we need delete the relationship with the template

**Comment by bryanboza** [comment]
Fixed, after discuss with @wezell, that's a know issue
