### ISSUE TITLE
Need update references when you fix conflicts under the application/containers files 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15974]
We have problems after fix conflicts when under this folder (`/application/containers/`) those are the new containers as files, and if you use one on those in a page and then fix conflicts with the integrity checker, we are updating the ID, but not the reference in the pages that are using the container 

## Expected Behavior
We need to update the references of that container

## Current Behavior
We are fixing the conflicts without problems, but when you try to open some of the pages that use the container we have a velocity error. 
![err1](https://user-images.githubusercontent.com/2641437/52308588-553be300-2963-11e9-9c02-9c54f6618bad.jpg)

## Your Environment
Tested on master // Oracle // FF

**Comment by wezell** [comment]
We need to survive if we reference a  container with a bad it

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16084

**Comment by bryanboza** [comment]
Tested after the changes to use path instead id,
-After fix conflicts, we are having a velocity error and we are not able to render the page.

Since we are using path after fix these conflicts we need be able to survive and don't lose the contents of the page, right now we are losing all the contents.
We need to update the multi-three and also invalidate the cache after change the id
<img width="1676" alt="velocity" src="https://user-images.githubusercontent.com/2641437/53581033-70ed7000-3b42-11e9-8e9c-984f6d8c7515.png">

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16194

**Comment by bryanboza** [comment]
We need to invalidate the cache after fix the conflicts

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16209

**Comment by bryanboza** [comment]
After the last changes, we have an NPE in the invalidate, and we are unable to fix the conflicts 
Log: https://gist.github.com/jgambarios/4ebecf6ee62e5ac913180bf06b6daa45

Also, I tried with the simple case (just a folder with some asset) and I have a workflow problem fixing the conflicts, Log:  https://gist.github.com/jgambarios/b243c029a060253bfe7b97f7705ef1bd

**Comment by jgambarios** [comment]
PR:
master: https://github.com/dotCMS/core/pull/16223
release-5.1.0: https://github.com/dotCMS/core/pull/16224

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16227

**Comment by bryanboza** [comment]
Tested after the last changes and we have this: 

- After you fix the conflicts and try to open the page to edit, we are losing the live version of the page

**Comment by jgambarios** [comment]
Closing this ticket as the found issue will be fix in https://github.com/dotCMS/core/issues/16230 and for `5.1.1`
