### ISSUE TITLE
Unable to use the Layout screen when opening a page based on a container as a file that no longer exists. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15979]
The Layout screen becomes useless when opening a page that references a container as a file that has been deleted. 

## Steps to Reproduce (for bugs)

Related with:  https://github.com/dotCMS/core/issues/15973 

* Login as admin
* Create a new template using the Template-designer Option and add a container as a file 
* Use that template in a new page
* Go to site browser and delete the folder under this path `/application/containers/`
* Try to open the page again you'll see the container no longer appears and instead of it there is an exception
* Click on the Layout button that appears on the right-hand side. 
* After doing that the page becomes useless and the user is no longer able to interact with the edit mode.

**Comment by fabrizzio-dotCMS** [comment]
![layout-broken-after-remove-template](https://user-images.githubusercontent.com/37148755/52365700-ab656080-2a0d-11e9-9944-f88f7c5cd7f3.gif)

**Comment by bryanboza** [comment]
Fixed, now we are able to edit the layout, in order to add a new container and continue using the page normally
