### ISSUE TITLE
Show On Menu not respected for pages in folder

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15975]
If you create a folder with Show On Menu selected and pages within that folder have it unselected the following code will still return true on those pages when it should return false:

#set($current = $navtool.getNav("/"))
#set($breadcrumbsList = $contents.getEmptyList())
$navtool.getNav().showOnMenu

## Your Environment

* dotCMS version used: 5.0.3

**Comment by wezell** [comment]
That looks ok, if the about-us folder has show on menu set and the pages under it have it set to false, then:

```
#set($current = $navtool.getNav("/about-us"))
$current.showOnMenu <--------- THIS SHOULD BE TRUE
#foreach($nav in $navtool.getNav().children())
$nav.showOnMenu  <--------- THIS SHOULD BE FALSE
#end
```

**Comment by ekelvin** [comment]
The second one is not showing false but true

**Comment by wezell** [comment]
I still cannot reproduce.  I have "show on menu" checked for the "/about-us" folder and the "/about-us/index" page.  Given  this code:
```
<h3>ROOT folder / </h3>
#set($current = $navtool.getNav("/"))

$current  = $current.showOnMenu <br>
<ul>
    #foreach($child in $current.children)
        <li>
            $child ($child.type) = $child.showOnMenu
                <ul>
                    #foreach($grandchild in $child.children)
                        <li>
                            $grandchild ($grandchild.type)  = $grandchild.showOnMenu
                        </li>
                    #end
                </ul>
        </li>
    #end
</ul>

<hr>
<h3>About Us</h3>
#set($current = $navtool.getNav("/about-us"))

$current  = $current.showOnMenu <br>
<ul>
    #foreach($child in $current.children)
        <li>
            $child ($child.type) = $child.showOnMenu
                <ul>
                    #foreach($grandchild in $child.children)
                        <li>
                            $grandchild ($grandchild.type)  = $grandchild.showOnMenu
                        </li>
                    #end
                </ul>
        </li>
    #end
</ul>
```
![screen shot 2019-02-07 at 8 36 08 am](https://user-images.githubusercontent.com/934364/52414879-7dd2f280-2ab3-11e9-9058-26bd04a00772.png)

If I uncheck show on menu on the "About Us" folder, then that leaf disappears, which is what it should do (see below).  When you uncheck "show on menu" on a folder, we do not recurse and uncheck it on all the underlying pages.  

This means that if I got the nav for "/about-us" and pulled the children, then the "/about-us/index" page will still have show on menu checked and will be displayed.

![screen shot 2019-02-07 at 8 35 17 am](https://user-images.githubusercontent.com/934364/52414825-55e38f00-2ab3-11e9-84b4-177f7ca1870e.png)
