### ISSUE TITLE
QA PP Legacy and field relationships

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15981]
We need to test push publishing with both old and new relationships

1. Does all related content make it to the receiver
2. What happens if you have a legacy relationship on both sides and you migrate it on the sender and push content.
3. Does relationship order get maintained across environments

**Comment by bryanboza** [comment]
After test multiple times, finally we have the specific steps of the process how to do a migration of relationships, new card open here #16217 

We will doc it for release...
