### ISSUE TITLE
Multi-lang container.vtl result in duplicate entries on the containers screen 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15987]
For Containers as files create other versions of container.vtl 
You'll see that for every language a duplicate entry of the container gets listed in the containers screen.

## Steps to Reproduce (for bugs)

1. Log in as  admin
2. Go to Site Browser /application/containers/large-column(lg-1)
3. Create a Spanish version of container.vtl
4. Now go to Site/Containers screen. Notice the container as file gets listed twice

![screen shot 2019-02-07 at 7 56 48 am](https://user-images.githubusercontent.com/37148755/52416260-d489fd80-2aae-11e9-83f0-8e1cef9e792b.png)
![screen shot 2019-02-07 at 7 57 09 am](https://user-images.githubusercontent.com/37148755/52416263-d81d8480-2aae-11e9-9114-f3bb5075b307.png)

**Comment by wezell** [comment]
So we should only show containers in the default language in the portlet - additionally, it is fine for us to have a rule that says if you want to use containers on the filesystem, there needs to be a version in the default language.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16081

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
