### ISSUE TITLE
The Content Types displayed on the content search does not respect container as files states.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15984]
The Content search dropdown does not respect 

## Steps to Reproduce (for bugs)

* Log in as an Admin
* Create a Template that uses a container as a file.
* On Site/Browser: go to **/application/containers/large-column(lg-1)/** and unpublish and archive some of the vtls present there. e.g. blog.vtl
* Now create a new page that uses the new template. And add new content to it using the content search dialog. Verify that the vtls that were archived or unpublished are not showing on the Content-Type drop-down
 ![Screen Shot 2019-02-06 at 3.21.47 PM.png](https://images.zenhubusercontent.com/5aa16c1d4b5806bc2bca0791/406978bb-0cc7-4008-b7a0-edeac7bbbeca)

**Comment by wezell** [comment]
We need to exclude archived content type .vtls from the listing

**Comment by jdotcms** [comment]
PR https://github.com/dotCMS/core/pull/16030
Still on progress but this issue will be fix as part of this PR

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now this is working as expected
