### ISSUE TITLE
Containers Search not filtering Files as Templates 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#15985]
Containers as files cannot be filtered using the Search-box

1. Go to Site/Containers 
2. Enter a keyword on the search box like "Promotion"
3. All Containers matching the search term should show up in the search results. But the "files as templates" ones are always part of the search result regardless of a match o not.

![screen shot 2019-02-06 at 3 43 06 pm](https://user-images.githubusercontent.com/37148755/52376044-c09ab900-2a26-11e9-97b6-5394f8785ff4.png)

**Comment by jgambarios** [comment]
Fixed in `5.1.0`

**Comment by bryanboza** [comment]
Fixed, now those containers appear when you try to filter by name
