### ISSUE TITLE
Problems using multi-language assets as containers

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15988]
Related to #15987 

If you create a multi-language asset (.vtl) under the folder `/application/containers/` we are able to use as a container, but we have errors when you try to add content to this container 

## Expected Behavior
We need to be able to support multi-language containers 

## Current Behavior

- [x] If you create a `container.vtl` file in multiple languages, we are detecting as multiple containers 

- [x] If you create a `container.vtl` and some specific `contentTypes.vtl` we respect only the default language

- [x] If you create an individual container just in a specific language (no default), when you try to add a piece of content in another language we have an error 
Here the ST: https://gist.github.com/bryanboza/c2666b941ae09027aeb9feb44803ebd0

- [x] If you create a multi-language version of one of the `contentTypes.vtl` when you try to add a piece of content we are showing a duplicated content type 
SC: https://screencast.com/t/gieeYc77Nh9l

- [x] Pre-loop and post-loop files are not working on multiple languages

## Possible Solution

- [ ] We need to detect if the `container.vtl` files have the same id, just show one in the containers portlet 

- [ ] The `container.vtl` should use the `contentTypes.vtl` in the same language 

- [ ] If the content does not exist in the default language, we need to catch the exception and just don't add the content to the page

## Your Environment
Tested on master // Oracle // FF

**Comment by wezell** [comment]
It is ok to have a rule that says that while containers as files will respect their language versions, we require all the files to have a version in the default language

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16021

**Comment by jgambarios** [comment]
We still have the duplicated content types issue:

![container1](https://user-images.githubusercontent.com/923947/53046731-576b6a80-3456-11e9-9b88-bc57f0d03daf.png)
![container2](https://user-images.githubusercontent.com/923947/53046732-576b6a80-3456-11e9-94fa-41288fb0b2b3.png)

**Comment by jgambarios** [comment]
### 1. Archived content type vtl
1. **webpagecontent.vtl** in Spanish and Archived

![container2](https://user-images.githubusercontent.com/923947/53524827-16063b00-3aa6-11e9-9e17-0690474d3194.png)

2. We should not be able to see the contents of that content type (or use it) in the edit or live mode as it is archived

![container1](https://user-images.githubusercontent.com/923947/53524826-16063b00-3aa6-11e9-9fe7-bee6652adc35.png)

**RULE:** The content type vtl in the default language will be use for all languages only if the requested language does not have a publish, unpublish or archived version of that content type vtl.

### 2. Deleting content type vtl in a non default language deletes all the references

1. Create a spanish version of the **content type vtl**
2. Delete the spanish version of the **content type vtl**

Removing a **content type vtl** in spanish removed all the container references of that content type in the page even in other languages.
We should not remove all the content type references as we still have the vtl in other language.

### 3. Unpublish/Archived container.vtl 

1. **container.vtl** in Spanish unpublish (same thing if archived), I can still see the Spahish content of the container in the live page

![container3](https://user-images.githubusercontent.com/923947/53524828-16063b00-3aa6-11e9-887a-b239674a7a0b.png)

2. The page in spanish is live and shows the archived container

![container4](https://user-images.githubusercontent.com/923947/53524829-16063b00-3aa6-11e9-9ea0-f60a547831ef.png)

**RULE:** The **container.vtl** in the default language will be use for all languages only if the requested language does not have a publish, unpublish or archived version of the **container.vtl**.

### 4. Deleting container.vtl in a non default language deletes all the references

1. Create a spanish version of the **container.vtl**
2. Delete the spanish version of the **container.vtl**

Removing the **container.vtl** in spanish removed all the container references in the page leaving the container empty even in other languages.
We should not remove all the container references as we still have a vtl in other language.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16163

**Comment by bryanboza** [comment]
Ok after the last changes, now we need to ignore the @jgambarios comment since now we use only the status of the container.vtl in the default language, we don't fully support multi-language containers. 

We have this case: 
- The pre-loop and post-loop files are multi-language, if you have those files in multiple langages we should compile without problems, but if one of those files exist just in one specific language different to the default one, we have problems rendering the page and we are unable to render, and just show a blank page. 
```
20:32:10.473  ERROR directive.ParseContainer - Exception rendering parseContainer (/EDIT_MODE///demo.dotcms.com/application/containers/spanishcontainer//1552444239704.container) at EDIT_MODE/8f2b38fc-bd2c-498a-a6a2-af1fc23d5347.templatelayout[line 3, column 1] @ url:GET//demo.dotcms.com/api/v1/page/render/test1/test2 | lang:1 | ip:127.0.0.1 | Admin:true | start:03-12-2019 07:00:13 CST  ref:http://localhost:8080/dotAdmin/  ?mode=EDIT_MODE
```

**Comment by jgambarios** [comment]
The issues described above will be fix in https://github.com/dotCMS/core/issues/16232
