### ISSUE TITLE
Allow urlmaps in the PageResource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15990]
With an eye towards working on this #15369

1. Leave URLMapFilter untouched
2. copy the urlmap logic (without needing a request or response) and complete the changes in a URLMapAPI
3. Use the URLMapAPI to test for URLMaps in the PageResource
4. Only test for a urlmap if the page url is not found - meaning, try the page by url first, then try urlmap.

**Comment by fmontes** [comment]
Tested with: http://localhost:8080/api/v1/page/render/news/the-gas-price-rollercoaster all good.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres  // FF
