### ISSUE TITLE
We are not validating permissions through relations

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16008]
Related to #9411 

If you set specific read permissions to any content, and this is related to any other content, with the new feature of the endpoints made in the related card, we are to get the content through the `depth` parameter 

## Expected Behavior
We need to validate permissions always before return content 

## Current Behavior
We are not validating permissions, and we are able to get restricted content when is related to some content that you have permissions 

## Steps to Reproduce (for bugs)
1. Try to get the `Gas Price Rollercoaster` content with using this endpoint `http://localhost:8080/api/content/query/+contentType:News +News.title:*gas*/depth/3`
2. From backend remove the anonymous permissions to that content and try again as a limited user. (We are respecting permissions, which is ok)
3. Now add permissions to the limited user to the same content. 
4. Try to make the query again 
5. Now take one of the related contents and make the same process, remove permissions and add permissions just to admin users (e.g, re: `The Gas Price Rollercoaster`  in comments) 
6. Try to get the same content again 
7. You are able to get this content because is related, even though you don't have permissions 

## Your Environment
Tested on master // Oracle // FF

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16051

**Comment by erickgonzalez** [comment]
Followed the steps above and now the related content is not shown if the user doesn't have permissions.

**Comment by bryanboza** [comment]
We still with the same problem, but now via graphQL

**Comment by dsilvam** [comment]
Discussed with @nollymar about it. We will move the permissions validation down to Java API level, where it must belong, so any callers (velocity, rest, graphql) are free of handling this

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16105

**Note te QA:** Please, verify permissions over related content are being respected using GraphQL, and these endpoints: `1. http://localhost:8080/api/content/` (with response type JSON/XML) and `http://localhost:8080/api/es/search`

Additionally, it would be nice to verify that getting relationship fields and categories from velocity is respecting permissions.

**Comment by erickgonzalez** [comment]
Tested against those 2 endpoints: `http://localhost:8080/api/content/` and `http://localhost:8080/api/es/search`, and also against Velocity and it's working as it should.

About graphQL it's returning the correct values but we found out that is not using cache, it's always hitting the DB so this **needs to be fixed**.

**Comment by erickgonzalez** [comment]
Now graphQL it's using cache. All working as it should

**Comment by erickgonzalez** [comment]
Working as it should, now graphQL is using cache instead of the DB.

**Comment by bryanboza** [comment]
Fixed, tested on the REST endpoints and also in the graphQL and now it works as expected
