### ISSUE TITLE
JSONTool can crash the server

### ISSUE THREAD

**Issue by thequicksilver** [dotCMS/core#1600]
If someone does a $json.fetch() and doesn't use a fully qualified URL (i.e. /tools/json.dot vs http://yoursite.com/tools/json.dot), it can cause the JSONTool to bring down one or more nodes in a cluster instead of just failing gracefully and logging the error (ideally spitting out a velocity error on the page).

**Comment by wezell** [comment]
Connect timeout can be configured now
