### ISSUE TITLE
Example .csv download includes the layout fields used to style the Edit Content Screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16011]
When you download the example, .csv needed to import content, it includes all the fields needed to layout the edit content screen - just like we do when we export content as .csv

Given this content type:
![screen shot 2019-02-11 at 1 41 22 pm](https://user-images.githubusercontent.com/934364/52585461-cca9c080-2e02-11e9-9c02-f1776313648f.png)

These need to be excluded:

![screen shot 2019-02-11 at 1 36 35 pm](https://user-images.githubusercontent.com/934364/52585206-2fe72300-2e02-11e9-99b5-831c264db826.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16012

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
