### ISSUE TITLE
Do not show legacy relationship tab if there are no legacy relationships to display

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16010]
If you create a one sided relationship field we should not show the "relationship" tab on the child side of the relationship.  The user would need to add the legacy relationship field if they want to see all the relationships on a piece of content.

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16015

**Comment by bryanboza** [comment]
We need to hide this tab from the editing content type window too...
<img width="1675" alt="rel1" src="https://user-images.githubusercontent.com/2641437/52814954-01b44e00-3063-11e9-9177-e19f9b372307.png">

**Comment by nollymar** [comment]
The logic to hide the tab is going to be implemented by Fox team on another task

**Comment by bryanboza** [comment]
This card need to be fixed on core web by the FOX team

**Comment by wezell** [comment]
Original Card closed, new one opened for the content type window . #16120
