### ISSUE TITLE
FS Containers keying off fileAsset.title rather than fileAsset.fileName

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16017]
I right-click copied/pasted the products.vtl and renamed the copy banner.vtl and added in the banner code.  The issue was the banner content type did not show up in the list as available for use.  This is because the title of the fileAsset was still products.vtl even though the fileName was banner.vtl.

We need to key off the file name, not the title or other fields.

**Comment by wezell** [comment]
Watch the video - banner does not show up even though there is a `banner.vtl`
![banner](https://user-images.githubusercontent.com/934364/52609410-3b127100-2e4b-11e9-83bb-0fe79866d2d4.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16047

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes
