### ISSUE TITLE
getRelatedContent always hitting the db

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16020]
We have a performance regression where we are always hitting the db to populate a relationship result.  You can see this by hitting a content object with a relationship

`ab -n 10000 -c 10 http://localhost:8080/api/content/id/{id}/depth/0`

## 87k+ db queries from glowroot
![screen shot 2019-02-12 at 11 12 15 am](https://user-images.githubusercontent.com/934364/52650019-69c63100-2eb7-11e9-842d-934f1a95aff3.png)

## call stack
![screen shot 2019-02-12 at 11 29 20 am](https://user-images.githubusercontent.com/934364/52651050-7ba8d380-2eb9-11e9-8fe5-bc0ac92b27af.png)

---

**Note:** You might need to set these on OSX as well to prevent socket exhaustion 
`sudo sysctl -w net.inet.ip.portrange.first=32768`
`sudo sysctl -w net.inet.tcp.msl=1000`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/16036

**Comment by bryanboza** [comment]
Since this is a performance thing I'll pass the card
