### ISSUE TITLE
Make collections of types and base types available as root fields

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16028]
Available as root fields under name: `{typeVarNameStartingWithLowerCase}Collection`

ala: 

```
{
  employeeCollection(sortBy:"modDate asc") {
    firstName
    lastName
  }

  newsCollection(sortBy: "title") {
    title
    byline
  }
}
```

Available arguments: 
- query (lucene)
- limit
- offset
- sortBy

Already implemented here: https://github.com/dotCMS/core/pull/16025/files

**Comment by erickgonzalez** [comment]
Needs Work: Missing **contentCollection** baseType and remove **contentletCollection**.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16040

**Comment by bryanboza** [comment]
Fixed, tested and now this works as expected

**Comment by john-thomas-dotcms** [comment]
Looks like this was already documented: https://dotcms.com/docs/latest/graphql#Collections
