### ISSUE TITLE
SPAEM: Make app take and respect language id

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16039]
As a stakeholder I want to make sure SPA use language feature of DotCMS.

## Acceptance Criteria

1. If we open http://localhost:5000/en/about-us page should be shown in that lang
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
`core` branch: issue-16039-SPAEM-Make-app-take-and-respect-language-id

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16139
