### ISSUE TITLE
Legacy Relationships should show the complete list of relationships of the content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16049]
When you add a legacy relationship field to some content type, this filed should show the complete list of relationships, no matter if is new or legacy.

## Expected Behavior
When you add the legacy relationship field to some content type, we need to show the complete list of related contents, 

**FYI: This is the only way to see the complete detail of the contentlet and its relationships** 

**Note:** 
The tab is only for both new and legacy relationships 

- [x] If legacy relationships exist, we need to show the tab to show ALL the existing content relationships both legacy and new (Only if the relationship is one sided)
- [x] If you add the legacy relationship field, we need to hide the tab and show the list into the filed (as we do in previous versions)
- [x] If there are only new relationship fields and no legacy relationships, we need to hide the tab
- [x] And finally, if the content type `A` has relationships with `B,C and D` but you only have the  new relationship field displaying `B`, then we need to show, under the relationships field, only relationships to `C and D` in the legacy relationships field.  We need to hide the related content of `B` to avoid displaying them twice in both the new relationship field and the old legacy field, which would be confusing to the content contributor.  The legacy relationships field should show both OLD and NEW relationships UNTIL a new relationships field is added, then that particular relationship should not display in the legacy relationships field.

## Current Behavior
The legacy relationship field is working just for legacy relationships 

## Your Environment
Tested on master // Oracle // FF

**Comment by john-thomas-dotcms** [comment]
I think it looks something like this @nollymar:

### Show or Don't Show Legacy Relationships Tab:

```
if content type has legacy relationships {
    if content type has a legacy relationship field
        don't show legacy relationships tab
    else
        show legacy relationships tab
}
```

### Contents of Legacy Relationships Tab

```
All legacy relationships on the content type +

for each new relationship on the content type {
    if there's a new relationship field for this relationship on the content type
        don't show the new relationship
    else
        show the new relationship
}
```

**Comment by john-thomas-dotcms** [comment]
Although honestly I don't think there would be a problem showing the new relationship both in a new relationship field and in the legacy relationships tab, so I think the second half of that is unnecessary.  I'd rather the legacy relationships tab just showed all relationships on the content type, regardless of whether there's a new relationship field for it or not.

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16067

**Comment by erickgonzalez** [comment]
Needs Work:

- [ ] If you have a new Relationship field **A** to **B**, and if you add a **legacy Relationship field** into **B** you should be able to see the relationship.

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16116
These rules summarize the behavior: 

1. The relationship tab will be shown when there is at least one legacy relationship.
2. If the relationship tab is shown or the legacy relationship field is added, all relationships will be listed (even those with relationship field)
3. If the relationship legacy field is added to the content type, the relationship tab will be hidden (as in previous versions)

**Comment by erickgonzalez** [comment]
This ticket does not apply since a new ticket was created to overwrite this issue. 
New issue: https://github.com/dotCMS/core/issues/16128
