### ISSUE TITLE
"content" key in Key/Value Field is not displayed in content edit window

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16046]
Reported via support ticket: [97528](https://dotcms.zendesk.com/agent/tickets/97528)
Reproducible in dotCMS 4.3.3, 5.0.3

When an entry is added for Key/Value field using the word "content" for the key, and the contentlet is saved, the next time the content is edited the entry doesn't display in the content edit window.

## Expected Behavior
All Key/Value field entries should display when the content is edited. If the "content" key is used for a new entry for a Key/Value fields, and the contentlet is saved and the edit window is closed, the next time that the content is edited the entry should display.

## Current Behavior
If the "content" word is used for a new entry in a Key/Value field, and the contentlet is saved, the next time that the content is edited (after close the content edit window and open it again), the entry doesn't display.

## Possible Solution
The code that displays the Key/Value field entries, has a condition to skip the entry is the key is equals to "content" word:

https://github.com/dotCMS/core/blob/f8648161970d8a6a88eb6356dc44c4090765e378/dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp#L1007-L1009

That condition can be removed so the entry displays in the content edit window.

## Known Workarounds
There's no known workarounds for this issue.

## Steps to Reproduce
1. Log into dotCMS 5.0.3
2. Add a Key/Value field for a content type.
3. Edit a content item for the the content type from the previous step. Add a new entry to the Key/Value field using the word "content" as the key.
4. Save the content item and close the content edition window.
<img width="1140" alt="content-key" src="https://user-images.githubusercontent.com/2894221/52804418-c6595580-3049-11e9-9e4c-a9e983a6809a.png">

5. Edit the content item again.
6. The entry with the "content" key doesn't display
<img width="924" alt="key-doesnt-show" src="https://user-images.githubusercontent.com/2894221/52804431-cce7cd00-3049-11e9-9736-57062caf4402.png">

## Context
This was reported by client in this support issue: [97528](https://dotcms.zendesk.com/agent/tickets/97528)

## Your Environment
* dotCMS version used: 4.3.3, 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): Content management

**Comment by dsolistorres** [comment]
Attached hotfix for 4.3.3
[hotfix-GIT-16046_v4.3.3.zip](https://github.com/dotCMS/core/files/2910622/hotfix-GIT-16046_v4.3.3.zip)

**Comment by dsolistorres** [comment]
PR: #16190

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Unable to reproduce after the last changes
