### ISSUE TITLE
When checking in a new contentlet, set host more intelligently

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16043]
When we check in a new piece of content that does not have a host, we just stick it on the system host.
This does not work for multi-tenant scenarios. 
What we should do is see if the content type belongs to a specific host and if so, use it - meaning, I create a content type on host A and start adding content to it, I expect that content to live on host A.

We should only fall back to system host if the content type lives on system host.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16044

**Comment by bryanboza** [comment]
Tested with the last changes...

After creating a content type that lives on "demo.dotmcs.com" and this without a site/folder field, the contents of this content type still living on the "system host"... 

- Create a new content type "test" make sure that lives on demo.dotcms.com
- Add a new filed text
- Add a piece of content 

Now on the Query tool run those queries: 
`+contentType:test +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797)` 
and
`+contentType:test +(conhost:SYSTEM_HOST)`

The contentlet lives on system host

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/16508

**Comment by dsilvam** [comment]
Passed Internal QA: Content of a Content type without host field is properly assigned to Content type's host instead of SYSTEM_HOST

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now this works as expected
