### ISSUE TITLE
Add class to rows and columns in the layout editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16054]
As a front end developer I would like the ability to add class to my layouts rows and columns.

## Possible Solution
1. Add a button to the rows to add class rows
2. Add a button to the columns to add class to columns
3. Buttons popup a dialog with: class (text) and buttons: save and cancel
4. Print the classes to the page html

## Acceptance Criteria

1. Add custom classes to rows and column
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by freddyucv** [comment]
We have to update the starter with this new template.vtl

https://gist.github.com/freddyucv/54f4a5bd6298e0bd9412c699949af888

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16302

**Comment by fmontes** [comment]
We need the changes in the template.vtl of the starter.

**Comment by hmoreras** [comment]
In the layout, when adding containers (that are not saved) and add the classes value, the value get overwritten by lates in the containers that are not saved.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
