### ISSUE TITLE
Containers as files are not included when you reorder the container list 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16057]
On containers portlet, when you try to reorder the container list we are just reordering the normal containers and the new containers as files are not included 

## Expected Behavior
We need to be able to reorder the complete list of containers including containers as files 

## Current Behavior
We are not including the new containers as files in the reorder process 

SC: https://screencast.com/t/SZsSb6iqn8UP

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
Also any of the filters in the Containers portlet works on the new Containers as Files.

**Comment by jgambarios** [comment]
The new Containers as Files are part now of the list when we reorder but they do not respect the reorder criteria, Containers as files are always first in the Containers list.
