### ISSUE TITLE
Cache issues changing Identifier Asset Name

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16052]
We have a couple of cases where we are not cleaning properly the contentlet cache when we change the `Identifier` `Asset Name`:

### Case 1
1. Create `File Asset` in English
2. Create a Spanish version of the same `File Asset`
3. Change `File Name` in the Spanish version

The change is not reflected in the English version, flushing the contentlet cache solves the issue

### Case 2
1. Create `File Asset` in English
2. Create a Spanish version of the same `File Asset`
3. Rename in the `Site Browser` the Spanish version the `File Asset` then go to the Edit Window of the `File Asset`

The `File Name` didn't change, I have to clear cache in order to display the correct value

**Comment by fabrizzio-dotCMS** [comment]
Unable to reproduce. It's already fixed.

**Comment by bryanboza** [comment]
I'm able to reproduce, we need fix that

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16122

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
