### ISSUE TITLE
The search component in the content type portlet should be case insensitive 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16069]
We need be able to find by coincidence but is not necessary be case sensitive here 

![gif1](https://user-images.githubusercontent.com/2641437/53046929-d52f7600-3456-11e9-859e-e1e6c60ab723.gif)

## Your Environment
Tested on master // Oracle // FF

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16077

**Comment by bryanboza** [comment]
Fixed, tested on the last master code and now works as expected
