### ISSUE TITLE
[REST] : The "/api/v1/page/render/" Endpoint not fully respecting "language_id" parameter

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16066]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97372
Reproducible in dotCMS 4.4.1, and not working at all in latest version.

The `/api/v1/page/render/{uri: .*}` Endpoint allows you to retrieve the rendered version of a given page and its respective properties. Passing down the Language ID allows developers to retrieve an HTML Page in a specific language.

## Expected Behavior
Passing down the `language_id` parameter in the REST call **must return both the specified HTML Page and its contentlets in such a language**.

## Current Behavior
In dotCMS 4.4.1, the Contentlets are being returned in the specified Language ID, but not the HTML Page. In the latest source code, the Endpoint throws the following message even after passing down the CMS Administrator user:
```
{
    "message": "User:anonymous does not have permissions on Contentlet Contentlet[name: The Test Page, type: Page Asset, lang: 1 ,identifier: bcfef71e-990b-4033-9109-9a8a43e348f5, inode: 1886f5be-1232-425b-ae0d-72cda969be7d]"
}
```

## Possible Solution
N/A

## Known Workarounds
N/A

## Steps to Reproduce
1. Log into the dotCMS back-end. Go to the "/home/" folder and create an HTML Page in English (called "Test Page") and Spanish (called "Pagina de Prueba") using the "Quest - 1 Column (With Content Padding)" template. The URL must be "/home/test"
2. For the English version of the page, add a new Generic Content with the body "My Test Content". For the Spanish version, add a new Generic Content with the body "Mi Contenido de Prueba".
3. Using Postman, make a GET request to http://localhost:8080/api/v1/page/render/home/test passing down Basic Auth. The JSON response is correct.
4. Now, change the GET request to http://localhost:8080/api/v1/page/render/home/test?language_id=2 with the same Basic Auth. The JSON response returns the Contentlet in Spanish, but NOT the HTML Page. You can see it in this screenshot:

<img width="677" alt="rest_call_bug" src="https://user-images.githubusercontent.com/8779585/53037257-58dd6880-343f-11e9-879f-62f48d0a02b6.png">

## Context
In dotCMS 4.4.1, the contentlets in the response are in the correct language, but not the HTML Page. In latest source code, the Endpoint is not recognizing the passed-in user at some point.

## Your Environment
* dotCMS version used: 4.4.1, latest source code
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Page Resource REST Endpoint.

**Comment by Xander-Steinmann** [comment]
I've had similar issues with one of our multilingual sites. DotCMS was unable to open pages in other languages than the default language. If I opened the render URL with "?language_id=5" then the call worked. I've seen this in 5.2.6.
