### ISSUE TITLE
Resize image increase file size substantially

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16079]
Using resize-image filters results in file sizes from 50-100% larger than the original, which is problematic for image heavy pages.

## Steps to Reproduce (for bugs)

1. Upload an image to a folder
2. Call the resize 
https://localhost:8080/contentAsset/resize-image/36155e51-a0c5-4533-b218-fa291829d468/fileAsset/w/600/h/492/filter/Crop/crop_w/500/crop_h/350/crop_x/50/crop_y/70
 
or

https://localhost:8080/contentAsset/image/c7c854b8-7d2c-4bec-b611-84fda3db0aba/fileAsset/filter/Resize,Crop,png/resize_w/600/resize_h/492/crop_w/500/crop_h/350/crop_x/50/crop_y/70

3. Resulting image will be at least 50% larger in file size than the original image.

## Your Environment

* dotCMS version used: 5.0.3

**Comment by wezell** [comment]
The image editor saves images as lossless PNGs by default.  You need to add the jpeg filter on the end of the filter list to compress the resulting image, e.g.


`https://demo.dotcms.com/contentAsset/image/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043/fileAsset/byInode/1/filter/Crop,Jpeg/crop_w/150/crop_h/150/crop_x/206/crop_y/56/jpeg_q/85`

The `jpeg_q/{n}` is a number between 0 and 100 that is the quality of the compression.  Bigger quality, bigger file size.
