### ISSUE TITLE
Change parseContainer directive to use path instead of id in page layout for Containers as files

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16076]
As part of the changes made in https://github.com/dotCMS/core/pull/16048 we are now using the path instead of the container id in the `#parseContainer` directive for Containers as files, regular containers use the id.

The change was applied to the Advance Templates and the Template Designer but we need to add that change also to the Page Layout.

If the container is in the same host of the page, the container path will be relative (without the host)
otherwise if the container is not in the same host of the page, the container path will include the host.

**Comment by fmontes** [comment]
![slack-imgs-1](https://user-images.githubusercontent.com/751424/53183682-63c00680-35c1-11e9-94e5-7de8e53a9118.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16215

**Comment by bryanboza** [comment]
Fixed, tested on the last master and I'm unable to reproduce the problem
