### ISSUE TITLE
It is possible to relate a content to itself

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16074]
When editing a piece of content, if the user wants to relate new ones, he can choose the same content, so it gets related to itself, which is wrong. If you try to do this an error will show up, and on the logs will appear a message like **Can not relate content to itself**

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16160

**Comment by dsilvam** [comment]
Passed Internal QA: Not possible anymore and getting proper feedback in the UI. 

Created related issue about very noisy logging here: https://github.com/dotCMS/core/issues/16165

**Comment by bryanboza** [comment]
Fixed, now we are unable to relate content to itself, but we have some improvements in those cases here #16165...  We can close this one
