### ISSUE TITLE
Import Content: Relationship fields should not be listed as key fields

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16073]
Currently, it is possible to select relationship fields as key fields when importing content. Those fields shouldn't even appear on that list.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16085

**Comment by nollymar** [comment]
Test Results: Success

**Comment by bryanboza** [comment]
Fixed, now those fields are not appearing as key fields...
