### ISSUE TITLE
Internal Server Error trying to get contents with binary fields via graphQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16071]
We have an internal server error when you try to get some content from a content type with binary fields and there is no value set.

## Expected Behavior
We need be able to return results without problems 

## Current Behavior
We return an internal server error and no errors in the log file 

## Steps to Reproduce (for bugs)
1. Create a new content type `test1`
2. Add a text field 'name' 
3. Add a new binary field `file`
4. Now from graphQL execute this query 
```
{
  test1Collection(limit: 10) {
    title
    file{
      name
    }
  }
}
```

## Your Environment
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
Needs Work still getting `Internal Server Error(s) while executing query` when pulling content that does not have a binary file set.

**Comment by erickgonzalez** [comment]
Working as it should now.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
