### ISSUE TITLE
[ElasticSearch] : Reindex is failing to index 3 contents with specific data

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16080]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97590
Reproducible in dotCMS 5.0.3

Customer data set is not finishing the Reindex Process correctly for 3 specific contentlets with the following Identifiers:

- 1a1ae421-016f-4a82-b617-3fb4f6afce03
- 43078ded-24cd-4000-b50d-62956db602ed
- 7b59634e-3884-4409-b115-0343f9de362c

This is the error in the log. As you can see, it's not being handled by the current code:
```
[14/02/19 11:16:57:669 EST] ERROR reindex.ReindexThread$1: Error indexing content [failure in bulk execution:
[0]: index [working_20190214102800], type [content], id [1a1ae421-016f-4a82-b617-3fb4f6afce03_1], message [java.lang.IllegalArgumentException: Document contains at least one immense term in field="partgroup-partnumber-order" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[53, 50, 49, 53, 48, 49, 56, 49, 45, 53, 100, 99, 48, 45, 52, 53, 99, 98, 45, 98, 48, 97, 50, 45, 55, 55, 56, 49, 48, 57]...', original message: bytes can be at most 32766 in length; got 66192]
```

For more information: https://stackoverflow.com/questions/24019868/utf8-encoding-is-longer-than-the-max-length-32766

## Expected Behavior
Reindexing all the content should work as expected.

## Current Behavior
The previous exception is keeping those contents from being added to the ES index.

## Possible Solution
N/A

## Known Workarounds
As suggested by another customer, the `ordermapping` value in the `es-content-mapping.json` file can be changed to include the `ignore_above` property, like this:
```
            {
                "ordermapping": {
                    "match": "*-order",
                    "mapping": {
                        "type": "keyword",
                        "ignore_above": 32766
                    }
                }
            },
```

## Steps to Reproduce
Ask the Support Team for the database dump and additional instructions.
1. Start up dotCMS with the customer's database.
2. Kick off a new reindex.
3. Notice how the process reaches 100% even though 3 records are not reindexed correctly.

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: ES Index

**Comment by nollymar** [comment]
This issue has been fixed. I encourage to remove changes made on `
es-content-mapping.json` when running release 5.1.0

**Comment by erickgonzalez** [comment]
Tested with the client dataset and the reindex finished successfully.
