### ISSUE TITLE
[REST] : Saving/publishing contents via REST does not fully respect the "respectFrontendRoles" parameter

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16089]
Reported via Support:
1. https://dotcms.zendesk.com/agent/tickets/97601
2. https://dotcms.zendesk.com/agent/tickets/97575

Reproducible in dotCMS 5.0.3, latest master.

Because of the changes made to the content save process in dotCMS -- using Workflows instead of directly calling the API -- some classes are not handling or respecting the `respectFrontendRoles` flag correctly.

**Scenario 1:**
In ticket https://dotcms.zendesk.com/agent/tickets/97601, saving an existing content using the `/api/content/publish/1` Endpoint with an Anon User -- after assigning all the correct permissions on the Content Type and Site -- is throwing the following error:
```
User: anonymous does not have Edit Permissions to lock content: f4225996-b325-4be3-befc-5aa4b44d7793
```

**Scenario 2:**
In ticket https://dotcms.zendesk.com/agent/tickets/97575, saving an new content using the `/api/content/publish/1` Endpoint with an Anon User -- after assigning all the correct permissions on the Content Type and Site -- is throwing the following error:
```
User anonymousdoes not have permission to publish contentlet with inode 4e99d989-d3ca-423c-976c-277fd2536487
```

## Expected Behavior
The Content Endpoint should not fail to save/update content.

## Current Behavior
The Endpoint is not working as expected.

## Possible Solution
Look into the source code and take into account both the `REST_API_CONTENT_ALLOW_FRONT_END_SAVING` and `respectFrontendRoles` flags, and how they related to each other.

## Known Workarounds
Fix the code.

## Steps to Reproduce
Follow the steps in the Support Tickets. If necessary, please reach out to @jcastro-dotcms and @dsolistorres 

**Note about permissions**
These are the required permissions for saving and publishing content:
1) For saving, the user/role requires "Edit" permission granted on the Site that will host the content.
2) For publishing, the user/role requires "Publish" permission granted on the Site that hosts the content.
<img width="1013" alt="site-permissions" src="https://user-images.githubusercontent.com/2894221/53258046-435f7d00-3691-11e9-9cf2-c79b04136bf7.png">

3) Also, the "Edit" permission has to be granted on the Content Type that will saved/published.
<img width="1138" alt="content-type-permissions" src="https://user-images.githubusercontent.com/2894221/53258052-49edf480-3691-11e9-9ccb-16b1d04305a4.png">

## Context
The paradigm change on how contents are saved in dotCMS involved changing a lot of code. It'd be a good idea to re-visit classes such as Workflow Actionlets to make sure that dotCMS is behaving correctly when content is added/updated using limited users.

## Your Environment
* dotCMS version used: 5.0.3, latest master
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: REST Endpoints.

**Comment by dsolistorres** [comment]
PR: #16099

**Comment by dsolistorres** [comment]
Hotfix for 5.0.3
[hotfix-GIT-16089_v5.0.3.zip](https://github.com/dotCMS/core/files/2894329/hotfix-GIT-16089_v5.0.3.zip)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce this case in the last master
