### ISSUE TITLE
Internal errors using the graphQL client 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16098]
Here some cases that are causing errors using graphQL:

## Image fields
- [x] If you try to use the `owner{firstName}` and you are an as limited user, this causes an internal server error, and this is the error on log 
Error: https://gist.github.com/bryanboza/4c4d6f142769ad43ed575167580652c4
_In case you try as admin works, we need to return a 401 in case of permissions_

- [x] If you try to get the `baseType` property 
This is causing an NPE https://gist.github.com/bryanboza/b729688df5c7ecd2bde44ba649832477 

- [x] If you try to use the `live, working and locked` property 
This cause another NPE https://gist.github.com/bryanboza/130f263e606f230bcc909a2e0f9b38f7

- [x] Trying to get  properties of content types with multi-language contents  https://gist.github.com/bryanboza/0cb7bdd4f15c479ab45dc7961c324a3d

- [x] Trying to get the `archived` property, this is causing an NPE
https://gist.github.com/bryanboza/8eb560859a3156a2a0ae67ff1943fccf

- [x] Trying to get the `URL map`, NPE
https://gist.github.com/bryanboza/e344838792c57533ab5f91ba9f5ff632

## Environment 
Tested on the last master // Postgres // FF . -- Insomnia

**Comment by bryanboza** [comment]
**Note: Please retest every one of the available properties for: binary, Image and file fields before send back to QA**

**Comment by erickgonzalez** [comment]
Tested with diff fields and it's working as it should. Only for the first bullet, there was a slight change a 401 it's not returned since the other values are returned, so **null** is shown for those values.

**Comment by bryanboza** [comment]
Fixed, new card created on #16212
