### ISSUE TITLE
Content types with called just with numbers are crashing the graphQL schema

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16096]
If you create a new content type and call just with numbers e.g `123` this is crashing the graphQL schema and you are unable to connect from the client. The same happens with the fields names. 

## Expected Behavior
We need support any kind of name supported by dotCMS

## Current Behavior
We don't support names with numbers starting with numbers in content types and neither in fields
**FYI: Vaid = test123, aa999   Invalid= 123, 123test**
<img width="1227" alt="graph1" src="https://user-images.githubusercontent.com/2641437/53210421-59266100-3603-11e9-9682-758b025a7f90.png">
Error: 
```
17:58:40.166  ERROR graphql.AssertException - Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was '123'
graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was '123'
```

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Create a new content type called `123`
3. Try to make some query or refresh the schema from graphQL

## Your Environment
Tested on master // postgres // FF -- Insomnia

**Comment by dsilvam** [comment]
Discussed with @wezell:
Action items: 
1. Restrict content type and field names *not* to start with numbers
2. Skip creation (and log warn) of *GraphQL types and fields for dotCMS types and fields whose names start with numbers (edited)

**Comment by erickgonzalez** [comment]
Needs Work when pulling using query:
```
{
  search(query: "+contentType:123testing", limit: 10) {
    identifier
    title
    contentType
  }
}
```
Error:
```
"data": {
    "search": [
      null
    ]
  },
  "errors": [
    {
      "message": "Can't resolve '/search[0]'. Abstract type 'Contentlet' must resolve to an Object type at runtime for field 'null.search'. Could not determine the exact type of 'Contentlet'",
  ```

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
