### ISSUE TITLE
We need to update the id in the content modal after create a new version of the content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16104]
When you try to create a version of the language the second time we have an error and you are unable to create the new version.

## Expected Behavior
We need to update the content_id in the modal to allow continue creating new versions 

## Current Behavior
If you create a new version of the content from English to Spanish, and then from the Spanish content you try to create a new version in a third language, we have an error 
SC: https://screencast.com/t/fQSLQbDu7Yp
Log: https://gist.github.com/bryanboza/f66bd092756931139b7a3e2af9dc7909

**FYI: if you close the modal and open directly the new version it works, the problem is trying to create a new version more than once from the same content**

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Add a third language in the system 
3. Go to edit some file asset and create a new version in spanish
4. Without close the content modal, try to create a new version in the third language 

## Your Environment
Tested on master //  postgres // FF

**Comment by jgambarios** [comment]
![content-type-null-thirdlang](https://user-images.githubusercontent.com/37148755/53347975-d0981100-38df-11e9-8b15-caf1a1d3357e.gif)

**Comment by jgambarios** [comment]
Closed as it is a dup of https://github.com/dotCMS/core/issues/16112
