### ISSUE TITLE
New file system containers are breaks the edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16108]
With the recent added containers as file feature, the pages in edit mode are crashing when the container is file system.

https://www.screencast.com/t/DF3zsJUrRYo

**Comment by fmontes** [comment]
The UUID for a file system container is not coming in the rendered HTML of the page API.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16136

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master
