### ISSUE TITLE
Unable to delete files that have been deleted from webdav

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16107]
When you try to delete any file via webdav, we are just archiving the content, we don't delete the piece of content at all. But if you try to delete this from backend we don't have actions on this content. 

## Expected Behavior
We need be able to delete the piece of content without problems 

## Current Behavior
The system isn't moving the content to some step of the workflow, then we are leaving the content archived and without available options 
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/ea045fb0-5968-4edb-8a07-86e3101bd288/00000171.png

## Possible Solution
Add a new action to the workflow in order to allow delete the file this on the starter site 

## Your Environment
Tested on master // postgres // FF

**Comment by mattyarbrough** [comment]
This is still an issue in 5.1.6

**Comment by wezell** [comment]
You need to copy the System Workflow > Delete action from the "Archived" step to the other steps so the delete action becomes available to content in the other steps.  See the forum post.

https://groups.google.com/forum/?place=forum/dotcms&showsearch=true&theme=default#!topic/dotcms/F-Bei7DHMRY
