### ISSUE TITLE
AWSS3EndpointPublisher reads files into memory

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16101]
We are doing a `byte[] bytes = IOUtils.toByteArray(is);` in order to calculate a files length.  We have the file, we should be doing a `file.length()`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/657

**Comment by nollymar** [comment]
Tests Results: Success

**Comment by bryanboza** [comment]
Fixed, tested S3 in general and works as expected
