### ISSUE TITLE
Content Type is null Messages appears creating a fileAsset using a third language. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#16112]
If you attempt to create a file Asset for each language. In a row. One after the other and you reach the third language you'll end up getting an error  like "Content-Type is null"

## Steps to Reproduce (for bugs)
1. Create a brand new language let's say: 
Country Code: FI, Language: Finish, Language Code: fi, Country: Finland 
2. Create a file Asset in English, upload an image. Save and Publish
3. Switch to  Spanish -  Hit Accept when the system suggests to auto-populate the new content. Save and Publish
4. Do the Same for the third, when switching to the third language, (in this case, Finish) you'll get the error described above.

This only happens if you do all that in a row. 
After getting the error you can still choose to open any of the previously saved instances, re-open it and proceed to create the new instance using the third language and it'll work just fine.

**Comment by fabrizzio-dotCMS** [comment]
![content-type-null-thirdlang](https://user-images.githubusercontent.com/37148755/53347975-d0981100-38df-11e9-8b15-caf1a1d3357e.gif)

**Comment by fabrizzio-dotCMS** [comment]
09:03:48.074  ERROR servlet.MainServlet - The Content Type is null when attempting to add new content with the inode:
java.lang.IllegalArgumentException: The Content Type is null when attempting to add new content with the inode:
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction.handleContentTypeNull(EditContentletAction.java:1165)
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction._newContent(EditContentletAction.java:1082)
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction.processAction(EditContentletAction.java:325)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16156

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
