### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16114]
Sooo much pink..... These need to be secondary buttons e.g. white

**Add content to a page screen**
![screen shot 2019-02-25 at 11 58 52 am](https://user-images.githubusercontent.com/934364/53354531-f380f000-38f4-11e9-941b-6db96bb49633.png)

**Content type with image on it**
![screen shot 2019-02-25 at 12 00 54 pm](https://user-images.githubusercontent.com/934364/53354612-23c88e80-38f5-11e9-80fc-86dde6038dd8.png)

**Comment by bryanboza** [comment]
Fixed, tested on master and now looks better
