### ISSUE TITLE
Uppercase on Identifier table when editing a file asset

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16115]
Reported via support ticket: [97582](https://dotcms.zendesk.com/agent/tickets/97582)
Reproducible in dotCMS 5.0.3

The asset name column stores uppercase names when file assets are edited from the dotCMS content edit screen. It should store only lowercase names. 

Related to: #15803

## Expected Behavior
The "asset_name" column should store always lowercase names, as that is expected for the code that handles requests that retrieves files using the URL. 

## Current Behavior
When an existing file asset is edited from the dotCMS content editor, or is renamed, and the File Name field is set to a value with uppercase letters, the "asset_name" column is updated with the name containing uppercase letters.

## Possible Solution
Fix the code to store always the file name with lowercase.

## Known Workarounds
There's no known workarounds for this issue.

## Steps to Reproduce
1. Log into dotCMS 5.0.3
2. Upload a new file asset in some folder. 
3. Right click on the file and choose Edit to edit the file asset properties.
4. Change the File Name field to some name containing uppercase letters (directly renaming the file under Site Browser also works)
5. Flush the dotCMS cache.
6. Access the file with the direct URL for it (/folder/myFile.txt). It returns 404 error.

If you run a database query, you can see the "asset_name" column value including uppercase letters:
```
dotcms=> select id, parent_path, asset_name from identifier where id='122555af-512a-42bd-b16b-d4c5f30e5a06';
                  id                  | parent_path |    asset_name
--------------------------------------+-------------+-------------------
 122555af-512a-42bd-b16b-d4c5f30e5a06 | /training/  | testAssetName.txt
(1 row)
```

## Context
This was reported by client in this support issue: [97582](https://dotcms.zendesk.com/agent/tickets/97582)
This causes issues when trying to request files from direct URLs.

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): Content management

**Comment by jgambarios** [comment]
The issue reported here was fixed for `5.1.0` in this PR: https://github.com/dotCMS/core/pull/16122

We we also marked this ticket with the `Release: 5.1.1` label as we are working on case sensitivity/insensitivity improvements and those changes will be present in `5.1.1`

**Comment by wezell** [comment]
We also have "/System folder" as a parent path all over our code base, eg:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/beans/Identifier.java#L271

We need to replace the String literal with FolderAPI.SYSTEM_FOLDER_PARENT_PATH everywhere

**Comment by wezell** [comment]
Things that we need to take into account:

- The stored procs will need to add lower to their logic (let's write a test to make sure it is broken now)
`check_parent_path_when_insert`
`check_parent_path_when_update`
`check_child_assets`
`renameFolderChildren`
`dotFolderPath`
`rename_folder_assets_trigger`
- Ensure the cache is lowering all keys (I think this is working)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16368

**Comment by jgambarios** [comment]
Copy actionlet is failing after this changes:

1. Create a Folder
2. Add a File Asset under that folder
3. Use the copy actionlet on the File asset

https://gist.github.com/jgambarios/6083bc4e8bef2222559de75019fa7672

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16515

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
