### ISSUE TITLE
Test 5.1 Reindexing performance with existing large datasets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16127]
We made reindexing changes in 5.1 that might affect reindexing performance.  Please test against existing customer datasets.

Test with glowroot attached.

**Comment by nollymar** [comment]
Some improvements were applied here: https://github.com/dotCMS/core/pull/16173

**Comment by erickgonzalez** [comment]
Tested with client dataset and with latest changes the reindex took 30 min.

**Comment by bryanboza** [comment]
Fixed, tested with real databases and now looks better
