### ISSUE TITLE
Hide new relationships from legacy relationship field / relationship tab

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16128]
It is confusing to show both the new and the old relationships in the legacy relationship field and tab.

It allows you to edit a relationship (field) in two places in the edit content screen.

**Comment by erickgonzalez** [comment]
Related to: https://github.com/dotCMS/core/issues/16049

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16138

**Comment by dsilvam** [comment]
Passed Internal QA: Only legacy Relationships are being shown in both _Legacy Relationship Field_ and _Relationship Tab_

**Comment by bryanboza** [comment]
Fixed, now we are unable to saw those relationships from the legacy field
