### ISSUE TITLE
Add a Many to one option in the relationship field

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16126]
- Can only be selected for a new relationship
- Should display properly if the field is edited
- under the covers, it creates the new one sided relationship in reverse,  the same way it would if you were adding the child side of an existing one to many relationship.

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/pull/16234

With these changes:
1. A One to Many relationship means Parent --> One / Children --> Many
2. A Many to One relationship means Parents --> Many / Child --> One
3. Internally, a Many to One relationship is saved with cardinality One to Many

**Comment by erickgonzalez** [comment]
Done Working as it should. Also added a two-sided relationship and it's respecting cardinality.

**Comment by bryanboza** [comment]
We need to improve the way that we relate to content, we need the same system of the one-one relationship, this because right now we allow set a lot of content and just are relating to one. 
SC: https://screencast.com/t/cqkbB5j0H77e

**Comment by nollymar** [comment]
I agree, but I suggest to create a new card for this specific requirement because is not part of the scope

**Comment by bryanboza** [comment]
Fixed, a new card created for the UI improvement here #16335
