### ISSUE TITLE
Need to show the flag of the piece of content language in the new relationship field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16129]
When you add a piece of content to other piece and this is in another language, as in the old relationships we need to show the corresponding flag  

## Expected Behavior
Need to show the correct flag and not the US by default 

## Current Behavior
We show the US flag by default 

- If you relate an English piece of content to a Spanish piece we have this: https://screencast.com/t/dPe021f3Uz  // https://screencast.com/t/hxaB0azZ0qr5
- This on the old relationships: https://screencast.com/t/rP7GtjLzf

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
![screen shot 2019-02-26 at 4 33 44 pm](https://user-images.githubusercontent.com/934364/53447958-51d8cc00-39e4-11e9-95d9-2a705b457af9.png)

**Comment by wezell** [comment]
Needed for Color Blind Accessibility ?

**Comment by nollymar** [comment]
The flag is not displayed by default in English, the flag is displayed according to the language of the content being currently edited

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF
