### ISSUE TITLE
Edit a child contentlet removes content relationships

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#16124]
## Expected Behavior
When you edit a child contentlet it should maintain it's relationships.

## Steps to Reproduce (for bugs)
1- Create a Content Type (Rating) with a Text Field (Rated).
2- Create a Content Type (Movie) with a Text Field (Title), a Relationship Field (Rating).
3- Create a Rating contentlet.
4- Create a couple of Movies contentlets and relate them to the Rating created.
5- Edit the rating
6- Check the Movies contentlets, the related content disappeared.

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16131

**Note to QA:** It is important to test a similar scenario editing content through the "Import Content" functionality

**Comment by erickgonzalez** [comment]
Needs Work: we still have the issue described above.

**Comment by nollymar** [comment]
This issue will be solved here: https://github.com/dotCMS/core/issues/16147

**Comment by erickgonzalez** [comment]
working as it should, now if you edit the child contentlet the relationships are kept. I also tested editing child content with the import content tool.

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are unable to reproduce
