### ISSUE TITLE
We need be able to migrate relationships and then push it and detect is the same relationship 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16137]
AS part of the migration process, we need to support that you after migrating some relationship and then try to push it, we need detect is the same relationship and just update the content type and not duplicate the relationship 

## Expected Behavior
We need to be able to update the relationships after migrate to the new ones and then push publish

## Current Behavior
If you push any content type, then migrate the relationship and push again, we are duplicating the relationship and we leave the continent type with the same relationship twice, one legacy and one new one 
SC: https://screencast.com/t/e6ZyNwh4wx

## Steps to Reproduce (for bugs)
1. Have a legacy relationship.
2. Push it.
3. Upgrade the legacy relationship to a new relationship on the _sender_.
4. Push again.

## Your Environment
Tested on master // postgres // FF

**Comment by nollymar** [comment]
Push delete on relationships is not supported, so after pushing migrated relationships, the old ones should be manually deleted on the receiver to avoid conflicts and/or potential issues
