### ISSUE TITLE
Velocity errors are affecting the rendering of the edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16144]
Related to #15640 

After this fix, we need to continue rendering even though the page has some velocity errors, but in this case, this is affecting the rendering of the edit mode 

## Expected Behavior
On those cases, we need to  render normally the edit mode 

## Current Behavior
We are duplicating content, and showing this in other containers 
SC: http://www.screencast.com/t/aOIEoAo2ZNed

Also, we have an error on logs: https://gist.github.com/bryanboza/7a135e8f2a64cb1ab53bfc0b9c999bc5

## Steps to Reproduce (for bugs)
1. Create a new page 
2. Add a new simple widget with this code 
```
$estool.search({
    'query' : {
        'match_all' : {}
    },
    'size':  10
}");
```
3. add a normal piece of content (generic)
4. Create a new widget with the same code 
5. Navigate through tabs, edit, preview, live 

## Your Environment
Tested on master // Postres // FF

**Comment by fmontes** [comment]
Even tho this is not the BEST approach to handle this errors we're good for now. Closing as @wezell requested.

**Comment by bryanboza** [comment]
We need to fix that since this happens just in the new edit mode, in previous versions we don't have the velocity error and we just print a `$code` 
SC: https://screencast.com/t/wRFY0f0nrju

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16279

**Comment by bryanboza** [comment]
After the changes, now I'm unable to reproduce the error, but we need to improve the log error in order to avoid showing too many lines of error in the log file, I think we need try to show 10-15 lines maximum in this case

**Comment by wezell** [comment]
I believe in most cases, we need to see the error in the logs.  We could do better but I think this can pass for now.

**Comment by bryanboza** [comment]
Passed
