### ISSUE TITLE
Change our default ES text analyzer from whitespace to standard

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16141]
We need to change our default analyzer to the "Standard" analyzer

We just hit a case where we were searching a comma separate list of words and the comma is being included in ES's tokenized list.  Turns out punctuation is not getting stripped out by the whitespace analyzer so on demo:

```
+contentType:Blog +Blog.title:America
```
returns nothing whereas with the `?`
```
+contentType:Blog +Blog.title:America?
```
we get a result.

Any word that touches punctuation, like words at at the end of the sentence with a period are now basically unsearchable without wildcards.

it seems like a prime reason we have always been so "fuzzy" with our recommendations  on how to search our content and whether you need `*` before and after terms in your query (edited).

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/es-content-mapping.json#L89

**Comment by wezell** [comment]
- Can we specify a mapping at a field level?
- Can we convert dashes in uuids to underscores, e.g. 4c441ada-944a-43af-a653-9bb4f3f0cb2b --> 4c441ada_944a_43af_a653_9bb4f3f0cb2b
- Can we rewrite the query to search another field?

**Comment by wezell** [comment]
We might want to look at forcing the keyword analyzer on these fields:
```
ESMappingConstants.STRUCTURE_NAME
ESMappingConstants.CONTENT_TYPE
ESMappingConstants.BASE_TYPE
ESMappingConstants.CONTENTLET_HOSTNAME
ESMappingConstants.PARENT_PATH
ESMappingConstants.PATH
ESMappingConstants.URL_MAP
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16618

**Comment by erickgonzalez** [comment]
`+contentType:Blog +Blog.title:America` now returns 1 result
`+identifier:735c44a5_3e6b_4047_a8c3_8ea9146e1762` returns result even it's underscored instead of dashes

but this issue needs work because the `OR` clause is not working e.g `+contentType: (webpagecontent or blog)`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16657

**Comment by erickgonzalez** [comment]
working as it should now, the **OR AND TO** clauses are keeping their case.

**Comment by bryanboza** [comment]
Tested with the provided example and this is working
