### ISSUE TITLE
Modify the way we handle relationships updates when a content is saved

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16147]
Updating related content in a piece of content should consider the following rules: 

1. A list of relationships with their related content needs to be sent. If the list is empty, all relationships will be wiped out. However, if the list is null, changes will be ignored. This rule applies in a relationship level too, so it means:  
    - If a relationship is sent as an empty list (empty string for Rest API), related content on this specific relationship will be wiped out
    - If a relationship is sent as null, related content on this specific relationship will remain unaltered

2. Only relationships that are included in the list will be updated. It means, if a content type has two relationships and only one is sent in the update, the other one will remain unaltered. 

3. Updating a one sided relationship is possible from any of its sides. For example: if there is a relationship from content type A to content type B, it will be possible to add/update related content from a content B as well as from a content A (excepts when the update is done from the UI, in which case, updates must be done on the content type that contains the field) 

**Note:** These rules apply when updating related content through the rest API too.  Remember that in this case, related content can be sent using the relationship name or the relationship field variable (if applies)

**Comment by nollymar** [comment]
Changes implemented here: https://github.com/dotCMS/core/pull/16151

**Comment by nollymar** [comment]
**Note to QA:** Please, also test Import Content using relationships

**Comment by nollymar** [comment]
Additional PR: https://github.com/dotCMS/core/pull/16176 that fixes two scenarios on the Import Content feature:
1. If a relationship field is sent as an empty column, related content will be wiped out
2. If the relationship field is not included in the csv file, the contentlet will be updated without affecting any related content it might have

**Comment by erickgonzalez** [comment]
For consistency purposes, this is how a relationship field will be handled via REST or Import Content:

- Empty String -> wipe out relationships
- A string of ids -> relate content
- No field passed -> related content unaltered

**Comment by erickgonzalez** [comment]
Tested with REST and Import Content functionalities. Working good.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
This was previously documented, but the documentation has been updated for clarity:

* https://dotcms.com/docs/latest/save-content-using-the-rest-api#relationships
* https://dotcms.com/docs/latest/importing-related-content#Existing
