### ISSUE TITLE
Containers are not getting clean out of template 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16154]
### Using the template designer:

1. Create a template
2. Add 3 containers, the same container works, just add it 3 times
3. Save and publish
4. Check those columns in the db
5. Remove two containers in the template
6. Check those columns in the db

## Acceptance Criteria

1. Containers should be removed from a page when they are remove from the template
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16157

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
