### ISSUE TITLE
Custom Content Portlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16161]
Admins need the ability to add  “Custom Content View” portlets that could be configured to only show a base type or a subset of content types (just like the Forms or Vanity Url portlets do now, but configurable).  The difference between those portlets and this “Custom Content View” is that when adding the “Custom Content View” tool to a Role/Tool Group, we would show the admin a button to config the “Custom Content View”.  This can just be a popup textbox in a modal that accepts json, but the admin would be able to specify 1 or more baseTypes OR 1 or more content types to display in the tool.    They would also be able to specify a Custom Name for the tool.  So you could something like this :
```
{
   baseTypes:[“PERSONA”]
   name:”Personas”
}
```
Which would add a Tool called “Personas” to the Tool Group.  Or something like:

```
{
   contentTypes:[“news”,”blogs”],
   name:”News and Blogs”
}
```
This would do two things:
1. Insert a new portlet DB entry with the same values as the `content` portlet but with different init-params that specify the baseTypes or the ContentTypes as a comma separated list.  The portletId can be a camelCased version of the specified name.
2. It would insert an entry into the languageVariable content type that maps the portletIdKey ( camelCased version of the specified name to the portlets real name, e.g. if the portletId = "personaPortlet" then we need a languageKey of
`com.dotcms.repackage.javax.portlet.title.personaPortlet=Persona Portlet`

In the ViewContentAction, we need to check if there are initParams in the portlet instance and if so we need to respect them and only show the baseType/contentTypes specified.

This would add a new Tool under the “Tool Group” called “News and Blogs” that would only show News and Blog content

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/16342

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16468 for fix the content search

**Comment by nollymar** [comment]
Creating a Content Portlet in Oracle is not working https://www.screencast.com/t/8AlU1BR97Z
There is nothing in the logs, so I think it's important to log this kind of errors for future troubleshooting

**Comment by nollymar** [comment]
I have found another issue:
When I create a new Content Portlet for content types, if I type multiple content types separated by comma + whitespace, no error is shown and the portlet is created correctly. But internally only the first content type on the list is actually added. Probably the logic needs a .trim() to clean up whitespaces

**Comment by nollymar** [comment]
**Improvements for this functionality:** 

1. Be able to edit/delete a custom portlet
2. Select content types from a multiple select box, it is less error prone and easier for the user

**Comment by nollymar** [comment]
Tested again in Oracle. Now, it works correctly.

**Comment by nollymar** [comment]
The trim issue commented [here](https://github.com/dotCMS/core/issues/16161#issuecomment-487193669) is fixed: https://github.com/dotCMS/core/pull/16494

**Comment by bryanboza** [comment]
I'm able to reproduce the trim() problem, tested on master // postgres // FF 
SC: https://screencast.com/t/ezIJsudk

**Comment by nollymar** [comment]
Can you please check if your environment is clean? For me it is working correctly and the ITs I implemented to test these cases are passing in Jenkins. I asked @dsilvam to test on his environment and he didn't report any issue either

**Comment by bryanboza** [comment]
Tested again with a totally fresh environment and I'm able to reproduce the problem 
SC: https://screencast.com/t/zYPNzcP5mX

**Comment by wezell** [comment]
@bryanboza please test with the latest master - that allows you to  delete custom portlets.  I added a trim() function so this should work.

**Comment by bryanboza** [comment]
Fixed, tested after the last changes in master and now it works as expected
