### ISSUE TITLE
Very noisy logging when Contentlet validation exception occur

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16165]
We just need a simple ERROR or WARN with the error message in one line. 

We are currently getting this: 
https://gist.github.com/dsilvam/9d295f36dd01e1c8174c824ce0e12939

Some cases for How to reproduce:
- Bad cardinality in relationships
- Try relating a contentlet to itself

**Comment by dsilvam** [comment]
Also, there's not specific feedback about the validation errors shown the UI. We need to include the specific cause of the validation error (see errors in relationships). Take a look at the new Toast notifications to see if they helpful here.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17459

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master, and now we have better feedback at the UI level

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by dsilvam** [comment]
Waiting for ticket: https://github.com/dotCMS/core/issues/17524

**Comment by dsilvam** [comment]
Waiting on ticket: https://github.com/dotCMS/core/issues/17543

**Comment by dsilvam** [comment]
Passed Internal QA Release: Both cases in the description printing one-line errors on the log.

**Comment by bryanboza** [comment]
Fixed, tested on the release-5.2.1 branch, Postgres // FF

**Comment by dsilvam** [comment]
Passed Internal QA: One-line error message logged.

**Comment by bryanboza** [comment]
Fixed, tested on master
