### ISSUE TITLE
Implement redesign of login page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16167]
As a stakeholder I want to implement the new design our UX team did for our Login Page

## Mocks
https://projects.invisionapp.com/d/main#/console/14206936/304817588/preview

## Acceptance Criteria

1. Match the design
2. Background image remains the same
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Looking at the mock we are losing the date here... 
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/b1bed6ff-a3bf-4927-9a60-f17486703e78/00000263.png

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryan test multi-lingual

**Comment by bryanboza** [comment]
yes, already tested, just need to translate the "Welcome" key in more languages
