### ISSUE TITLE
GraphQL - Related content not returning values for some properties

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16164]
When you try to get data from some related content we are returning a lot of values in null... 

<img width="1227" alt="rel1" src="https://user-images.githubusercontent.com/2641437/53766974-01f17d80-3e9a-11e9-8ca2-a79b2a29f4ad.png">

## Your Environment
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
Note to QA: Old relationship fields were excluded from GraphQL. Please test adding one and it should not be available from GraphQL

**Comment by erickgonzalez** [comment]
Working as it should. Now the values of related content are shown and if the content type has a legacy relationship field it does not show on the list of possible fields.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.1 and now this is working as expected.
