### ISSUE TITLE
[Content] : File asset URLs containing the String "/intranet" are incorrectly requiring authentication

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16187]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97645
Reproducible in dotCMS 4.3.3, 5.0.3

If a content author adds a File Asset whose name starts with "intranet", dotCMS is automatically redirecting the request to the front-end login page. For example, a URL such as https://demo.dotcms.com/global/css/intranet-styles.css will always redirect to the front-end login page.

## Expected Behavior
The File Asset should be displayed without issues.

## Current Behavior
The front-end login page is displayed, or a 401 error is returned depending on the dotCMS configuration.

## Possible Solution
As of dotCMS 4.x, code changes were implemented to add Web Interceptors in Filter classes. The URL filter for the `DefaultFrontEndLoginRequiredWebInterceptor` class is `"/intranet"`. Given the way that matching is handled in the `SimpleWebInterceptorDelegateImpl` class, this means that URLs like the one in the previous example will **ALWAYS** be considered as secured resources that require authentication. This code must be re-visited.

## Known Workarounds
There options are:
1. Rename the file name to **NOT** include the String `"/intranet"` anywhere in its absolute path.
2. Use the `/dotAsset` servlet to render the file: https://demo.dotcms.com/dotAsset/{YOUR-FILE-ASSET-IDENTIFIER}.css

## Steps to Reproduce
1. Log into our Demo Site, and go to the **Site Browser**.
2. Create the following folder hierarchy: `/global/css/`, and upload a File Asset that starts with the word `"intranet"`, e.g., `intranet-styles.css`
3. Under the same `/css/` folder, upload the same CSS file with a different name now, e.g., `test.css`
4. In an Incognito Window, go to https://demo.dotcms.com/global/css/test.css . The file loads correctly.
5. Now, go to https://demo.dotcms.com/global/css/intranet-styles.css . The front-end login page is displayed instead.

## Your Environment
* dotCMS version used: 4.3.3, 5.0.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Management.

**Comment by wezell** [comment]
That class is an error - front end permissions should not be governed by an
interceptor.

**Comment by wezell** [comment]
The test is to add CMS_ANON to `/intranet` and see if you can get there on the front end without logging in.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16189

**Comment by bryanboza** [comment]
Unable to reproduce on master
