### ISSUE TITLE
Relationship migration: Parent/Child relation name take the same name after migration

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16183]
When a legacy self-relationship is migrated, both parent and child relation name are taking the same name. This generates potential issues during content edition

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16184

**Comment by erickgonzalez** [comment]
Working as it should now. When you have a self-relationship the suffixes **parent** and **children** are added to the fields.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
