### ISSUE TITLE
Edit a site set it as current site and is not reflecting in the UI

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16186]
Make sure current site is always in sync with UI

## Expected Behavior
When current site is change by editing a site it should reflect the change in the UI (header)

## Current Behavior
When you edit a site, the current site gets changes under the hood but in the site selector of the header you don't see that change.

## Possible Solution
Emit a websocket event to update.

## Steps to Reproduce (for bugs)

1. Create 2 or more sites
2. Edit a site (different that the selected)
3. Go to site browser
4. See the site there doesn't match the one on the header.

## Acceptance Criteria

1. Match the current site selected at all times.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
Here is another case that we need fix - if you are on a non-defualt host and your socket disconnects and then reconnects, the browser (the jsps) and the NG client are out of sync.  To reproduce:

1. login and select "remember me"
2. add a new host
3. go to the browser and select the new host (you should see the empty host)
4. Kill your server and restart
5. Refresh the browser  (now you see the default host, even though the host selector says the new host)

**Comment by wezell** [comment]
The SwitchSiteListener is very noisy when logging in.  There are multiple NPEs when trying to check permission and there is no user.

**Comment by wezell** [comment]
## To Reproduce:
1. be logged out and go to http://localhost:8080
2. delete all your cookies
3. go to http://localhost:8080/admin

**Comment by wezell** [comment]
Error in the log moved to new card #16559
