### ISSUE TITLE
Add field type to each instance of field in content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16180]
As a stakeholder I want users to be able to see which type of fields they're dealing with.

## Mock
![Screen Shot 2019-03-07 at 11.02.49 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/31f86c77-8286-4e97-bb58-6d37010e26a2)

## Extra fix
![Screen Shot 2019-03-07 at 11.05.12 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/f4b1abbc-9ee3-4c1c-a1b3-ce12dbc7e5e6)
Some text is getting cut off in the line.

## Acceptance Criteria

1. Add field type to each field instance in the drop zone and fix the cut of text
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16188

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
