### ISSUE TITLE
Content Type with id:'Host' not found

### ISSUE THREAD

**Issue by reinderien** [dotCMS/core#16192]
On a fresh installation of Ubuntu Server/OpenJDK/DotCMS, all web requests fail.

## Expected Behavior
After having started the service for the first time, I should be able to load a page.

## Current Behavior
The web root cannot be loaded. I am receiving an HTTP 200 with Content-Length of 0, and the following log entries:

```
13:47:56.025  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: 'host' not found in db
13:47:56.027  WARN  web.HostWebAPIImpl - Content Index is fouled up, need to try db: Failed to execute phase [query], all shards failed; shardFailures {[jW
PklQWCTuWnXaHsidwH1w][working_20190308122136][0]: RemoteTransportException[[a2e07940-4a77-4937-9e50-470504ff25e9][127.0.0.1:9300][indices:data/read/search[
phase/query]]]; nested: QueryShardException[No mapping found for [moddate] in order to sort on]; }
13:47:56.029  ERROR business.HostAPIImpl - Content Type with id:'Host' not found
com.dotcms.contenttype.exception.NotFoundInDbException: Content Type with id:'Host' not found
13:47:56.029  ERROR filters.ThreadNameFilter - Unable to retrieve current request host for URI /
13:47:56.030  ERROR filters.CookiesFilter - Exception processing Cookies
javax.servlet.ServletException: Content Type with id:'Host' not found
```

## Possible Solution
Unknown.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Install Ubuntu Server 18.04
2. `apt install openjdk-8-jdk postgresql`
3. `cd ~`
4. `wget https://doc.dotcms.com/physical_downloads/release_builds/dotcms_5.0.3.tar.gz`
5. `mkdir /opt/dotcms`
6. `tar xf dotcms_5.0.3.tar.gz -C /opt/dotcms/`
7. `adduser --system --no-create-home --group dotcms`
8. `chown -R dotcms:dotcms /opt/dotcms`
9. `chmod 640 /opt/dotcms/dotserver/tomcat-8.5.32/webapps/ROOT/META-INF/context.xml`
10. `sudo -u postgres psql`
11. `create database dotCMS;`
12. `create role dotcms login;`
13. `\password dotcms`
14. `grant all on database dotcms to dotcms;`
15. `\q`
16. `vi /opt/dotcms/dotserver/tomcat-8.5.32/webapps/ROOT/META-INF/context.xml`
17. Set database access credentials
18. `vi /opt/dotcms/dotserver/tomcat-8.5.32/conf/server.xml`
18. Set `Connector` `address` attribute to the server IP for correct binding
19. `sudo -u dotcms /opt/dotcms/bin/startup.sh`
20. Access server from Chrome

## Your Environment

* dotCMS version used: 5.0.3
* Browser Name and version: Chrome
* Operating System and version: Ubuntu Server 18.04
* Application Server and version: Tomcat 8.5.32 packaged with DotCMS
* Java Brand and version: OpenJDK 8
* Database and version: PostgreSQL 10.6

**Comment by wezell** [comment]
I am pretty sure your db has never connected.  Check the start of your logs under the dotserver/tomcat/log directory and there will be an error about how it cannot connect to postgres.

It seems like you need to edit your `pg_hba.conf` file.

**Comment by reinderien** [comment]
@wezell That conclusion is incorrect. I went hunting and found the actual database logs, which show that a connection was indeed established, but there are hundreds of query failures.

**Comment by reinderien** [comment]
I found out the actual problem - the database and instance had gotten into a bad state because they were using OpenJDK 10, and a bunch of activation library failures occurred. I had fixed the Java version halfway through, but that wasn't enough. I needed to blast away the entire database and DotCMS instance and start fresh, and starting fresh with OpenJDK 8 resulted in a functional instance.
