### ISSUE TITLE
Folder with blank spaces should be allowed to push and should save

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16216]
Found when working on support ticket: https://dotcms.zendesk.com/agent/tickets/97741
Reproducible in dotCMS 4.3.3, and latest master.

In the dotCMS back-end, as a business rule, a Folder name (URL) **CANNOT** contain any blank spaces. However, when a folder with spaces in its name is uploaded via WebDAV, we're not validating it. This is causing several problems with Push Publishing which are not evident.

## Expected Behavior
A Folder name (URL) CANNOT contain any blank spaces.

## Current Behavior
The back-end is NOT allowing this, but WebDAV is.

## Possible Solution
Code fix.

## Known Workarounds
Remove any blank spaces in your Folder name **BEFORE** uploading it via WebDAV. If not, in the dotCMS back-end, edit such a folder and update its name (URL) to be lower-case and NOT have any blank spaces.

## Steps to Reproduce
1. In your File System, create a Folder called `My Test Folder`. You can add an image file inside if required.
2. Start up your dotCMS instance.
3. Connect via WebDAV (e.g., http://localhost:8080/webdav/live/1). Go to `demo.dotcms.com/about-us/` and paste the `My Test Folder` in there.
4. Log into the back-end, and edit the `/about-us/My Test Folder` folder.
5. Click **Save**. You'll see a modal window saying **"Folder Name (URL) can not contain spaces"**. The system should've never allowed the Folder's URL to be saved as `My Test Folder`, but as `my-test-folder`.

## Context
This is causing several problems with Push Publishing which are not evident. And is also violating our lower-case URLs rule.

## Your Environment
* dotCMS version used: 4.3.3, latest master.
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: WebDAV

**Comment by jcastro-dotcms** [comment]
This issue is still reproducible in latest master. Affected customer: [100692](https://dotcms.zendesk.com/agent/tickets/100692)

**Comment by wezell** [comment]
The fix for this is not to disallow spaces in folder names, it is to support spaces in folder names. Webdav breaks every time we try to rewrite (uppercase, lower case, munge spaces) what it puts into dotCMS. There is not reason dotCMS cannot support folders with spaces in their names.

**Comment by jcastro-dotcms** [comment]
Thanks for the clarification, @wezell . NOTE TO R&D: Please take this into consideration as the current behavior of the system is different:

1. If you edit a folder and add blank spaces to its URL, it fails to save.
2. If you Push Publish a page or file where one or more of its parents is a folder containing blank spaces, the push fails.

**Comment by wezell** [comment]
- Test via 
- WebDav
- Folder Portlet
- Push Publishing
- via URL - make sure the files underneath resolve

**Comment by wezell** [comment]
See also: #18452

**Comment by fmontes** [comment]
You can create a blank space folder with WebDav but then you can't push it

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18932

**Comment by victoralfaro-dotcms** [comment]
Folder names with white spaces are allowed in 4 ways of adding content:
WebDav:
![image](https://user-images.githubusercontent.com/64026161/88821370-d3a3ca80-d17f-11ea-98e9-e03163fc5593.png)

Folder Portlet:
![image](https://user-images.githubusercontent.com/64026161/88821400-dbfc0580-d17f-11ea-908f-5addf71f5975.png)

PP:
![image](https://user-images.githubusercontent.com/64026161/88821701-38f7bb80-d180-11ea-8ac4-ce4e30b30dc1.png)
![image](https://user-images.githubusercontent.com/64026161/88821731-414ff680-d180-11ea-94c3-d03a24ecd85f.png)
![image](https://user-images.githubusercontent.com/64026161/88821758-47de6e00-d180-11ea-992b-f2a57ff1521e.png)

via URL:
![image](https://user-images.githubusercontent.com/64026161/88821828-59c01100-d180-11ea-9375-9db1559d9a22.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // FF
