### ISSUE TITLE
Host dropdown in rules not keeping the value

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16222]
Some dropdowns we're not showing the selected value, instead it was showing the placeholder even where there is a value selected.

<img width="1345" alt="Screen Shot 2019-03-14 at 2 47 25 PM" src="https://user-images.githubusercontent.com/751424/54390555-61a11300-4668-11e9-84ac-38e36405cdcd.png">

**Comment by fmontes** [comment]
Branch currently working on: issue-16222-fix-rules-dropdown

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
