### ISSUE TITLE
Edit mode navigation problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16221]
We have some problems navigating through edit mode. After you change multiple times between edit // preview // live mode we have a JS error and we are unable to navigate. 

## Expected Behavior
We need be able to navigate on these tabs without problems

## Current Behavior
We have a JS error and we are unable to see the live mode 

SC: https://screencast.com/t/8u39U0DOYC9n

## Steps to Reproduce (for bugs)
1. Create a new page 
2. Add a piece of content 
3. Go to live mode 
4. Go back to edit and add another piece of content 
5. Change directly to the live tab again 
6. Repeat the steps 2-5 once again 

Make sure you can continue navigating through tabs 

## Your Environment
Tested on master // Postgres // FF

**Comment by bryanboza** [comment]
This card was not sent to QA before release, after test in the release distro we have problems here and the issue was not solved, If you add an unpublished piece of content to some page, this is breaking the edit mode, you are able to see the piece of content in the live tab and this is causing an error that we show in the log file every time you go to  this tab.
Log: https://gist.github.com/bryanboza/2e86b980e4d92c56acd29f34403e73f2
SC: https://screencast.com/t/KqW0PEZK

**Comment by fmontes** [comment]
@bryanboza this is not happening to us in core/master, maybe you didn't have the change when you tested the first time? can you give it another go?

**Comment by bryanboza** [comment]
Unable to reproduce on master... Tested the first time on release-5.1.0

**Comment by oarrietadotcms** [comment]
In order to fix the problem reported by @bryanboza in this comment: https://github.com/dotCMS/core/issues/16221#issuecomment-473388543

We needed to implement this commit: https://github.com/dotCMS/core/commit/6bbae9907ed062cb8b04bcec5049ebfe12523f4c

I think that commit was linked to the wrong Github issue by mistake.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.1.1 branch and now it works as expected
