### ISSUE TITLE
Not having files in the default language cause issues in Containers as Files

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16232]
Related to: https://github.com/dotcms/core/issues/15988

We found some issues with the following cases:

- The pre-loop and post-loop files are multi-language: 
If one of those files exist just in a language different to the default one we have problems rendering the page and we are unable to render, and just show a blank page. 

```
20:32:10.473  ERROR directive.ParseContainer - Exception rendering parseContainer (/EDIT_MODE///demo.dotcms.com/application/containers/spanishcontainer//1552444239704.container) at EDIT_MODE/8f2b38fc-bd2c-498a-a6a2-af1fc23d5347.templatelayout[line 3, column 1] @ url:GET//demo.dotcms.com/api/v1/page/render/test1/test2 | lang:1 | ip:127.0.0.1 | Admin:true | start:03-12-2019 07:00:13 CST  ref:http://localhost:8080/dotAdmin/  ?mode=EDIT_MODE
```

- The same thing if you have a content type.vtl that exist only in a language different to the default, if you add a piece of content the edit mode show the content without problems, reload the portlet and open the page again, we have the same problem 
Here a video: https://screencast.com/t/IUkuxgMTtY

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16237

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF  and now this works as expected
