### ISSUE TITLE
Content under load hiccups when checked in

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16236]
When you edit and save a piece of content that is under load, the piece of content being checked in loads dirty (uncommitted) values into cache which can cause the piece of content to become unavailable to other threads for 3 seconds until the delayed cache flush finalizer resets the content cache.

To Reproduce:
1. run `ab` against a page, e.g.:
```
ab -n 100000 -c 2 http://127.0.0.1:8080/about-us/index
```

2. Open the `/about-us/index` page and hit "Save and Publish"

You will see errors in the logs for 3 seconds saying that the page is not available

**Comment by wezell** [comment]
I believe there is a good fix here.  There are 2 main things in this commit.
1. It prevents PUTs into cache when we are in a transaction.  This rule seems logical to me as anything we are writing in a transaction can be rolled back.  Our entire cache infrastructure is designed to be loaded lazily - on reads - and never on writes, so I believe enforcing this in code makes sense.
2. Forces DB lookups on specific methods when we are in a transaction.  In this case - the calls to  `IdentifierAPI.find` and `VersionAPI.getContentletVersionInfo`.  I am convinced dirty reads/mutable cache objects are behind some of the odd bugs that we see in our testing infrastructure - things like "Content must be Archived to be Deleted" issue, where you can see the code line above archives the content. 
I played with the global rule "never return from cache and always look up from DB when in transaction" but that really affected backend checkin times.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes

**Comment by wezell** [comment]
@bryanboza while this change worked, it had bad performance implication.  Try importing the move/rating bundle on 5.1 and then try again on master.  I have another change coming that I'd like you to test.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16267

**Comment by bryanboza** [comment]
Tested again on master after the last changes, and now it is faster... Fixed
