### ISSUE TITLE
Webdav issues with Finder

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16231]
We have multiple errors running Webdav with finder (We are not able to reproduce this issues with Cyberduck)

Editing some file https://www.screencast.com/t/mUe0DRKD
Also this is crashing the file https://screencast.com/t/95xmHMz6i

Uploading files https://gist.github.com/bryanboza/d81a1af21e2be3227f2f20cb890c4040

We need to fix that error if continue supporting finder as WebDAV client

**Comment by wezell** [comment]
Will close for now
