### ISSUE TITLE
Missing cache cleanup after fixing conflicts in Integrity Checker

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16230]
After fixing conflicts of the files inside a container the live version of pages using that container are blank.

There is a missing cache we need to clean up after applying the conflicts.

## Steps to Reproduce (for bugs)

1. Create Container as a Files (Folder and files) in the sender using webdav
2. Create the same Container as a Files in the receiver using webdav
3. Create a template and a page using the created Container in the sender.
4. Add content to the page. 
5. Run the integrity checker and validate we have conflicts for the Container Folder and Container files.
6. Fix the Container folder conflicts in the sender node.
7. Fix the Container files conflicts in the sender node.
6. Check the created page -> The Live version of the page is blank.

**Comment by wezell** [comment]
I think after the IC runs on any server (the server making the changes) we need a FULL cache flush.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16323

**Comment by bryanboza** [comment]
Fixed, after fix the conflicts we continue rendering the page without problems
