### ISSUE TITLE
Icon selector in edit toolgroup breaks on invalid values

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16246]
![slack-imgs.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/ee07ae9d-d1f2-4756-9043-b1a4efce36c6)

## Acceptance Criteria

1. Make sure that field doesn't break when invalid value is set, don't just don't show icon.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
also we are unable to see the previous ones on the left menu 
https://screencast.com/t/Zinhdbcm

**Comment by bryanboza** [comment]
After discussing that fix we need to take in consideration those cases 
- Should we set a default icon or remove it totally after upgrade from previous versions? 
- We need to validate the entered value is a valid one, in order to avoid breaking the left menu

**Comment by fmontes** [comment]
We're constrain the icon space so if no icon show it will always be the same size

**Comment by bryanboza** [comment]
Fixex for now, now we support both libraries and also are able to edit without problems
