### ISSUE TITLE
Relating content does not ocurr when the Workflow Action has a Translate Content Sub-action

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16249]
Nollymar and I saw this when testing Master

To reproduce, make sure your Contentlet has a new relationship field, then in the "publish" workflow action, add a translate sub-action to take place after the publish sub-action.  

Bug: After clicking publish, the relationship does not save using the relationship field - it is NULL.

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/16266

**Comment by erickgonzalez** [comment]
Working as it should. Now if you add Translate Content Sub-Action and click publish, the content translated has relationships.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
