### ISSUE TITLE
Get rid of tabs!

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16252]
We need to run codestyle or some such tool to format all our src files to match google's java style guide (only change is my column width to 130 or 140.

https://github.com/google/google-java-format

https://github.com/sherter/google-java-format-gradle-plugin

After that, we need to enforce this in some way - perhaps using the gradle plugin to verify new code.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/661
