### ISSUE TITLE
Use container path in page render

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16263]
We have found errors in the page render where in some places we are using the container path to compare with the container id, the render code in the back end and front end can use the id without problem even if the container is a Container as files, the only thing we need to avoid is to save ids in the Template table where indeed we need to use the path.

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/16264

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16317

**Comment by bryanboza** [comment]
- After those changes, we are unable to add contents to the pages

- Also, we need to add some UI tests in to avoid this kind of basic issues

**Comment by jgambarios** [comment]
We need also to modify the end point `/api/v1/containers/{id}/content/{inode}` to support container paths, right now a request like this:
`/api/v1/containers//application/containers/large-column//content/27108d63-969e-4086-a405-86777be16230` would break the edit mode.

An option is to create a `v2` of the end point and sent the container as a query param supporting ids and paths:  
`/api/v2/content/27108d63-969e-4086-a405-86777be16230?container=/application/containers/large-column/`
or
`/api/v2/content/27108d63-969e-4086-a405-86777be16230?container=123456789`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16392

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
