### ISSUE TITLE
Handle containers in layout and edit page *only* per identifier

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16264]
We did this change: https://github.com/dotCMS/core-web/pull/938/files but handling the containers by path and identifiers is getting more problematic, we need to get back only to identifiers and let the backend handle the containers type.

**Comment by dotcmsCodeReview** [comment]
If we go back to this way, how would we handle someone creating a
template/layout in a json file in a way that can be versioned outside of
dotCMS?

**Comment by fmontes** [comment]
Closing this because the fix will be backend: https://github.com/dotCMS/core/issues/16263

<img width="1936" alt="Screen Shot 2019-03-27 at 11 39 09 AM" src="https://user-images.githubusercontent.com/751424/55108391-2277b680-5099-11e9-856a-c530af1894da.png">
