### ISSUE TITLE
Need disable the available actions (bulk) if you don't have license  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16270]
Since the bulk actions is a EE feature, we need to disable//hide that button when you don't have a license or maybe show a kind of message if you try to use it. 

This because right now if you try to use this button in the community edition, we are not doing anything and seems like the button does not work. 
<img width="1680" alt="bulk" src="https://user-images.githubusercontent.com/2641437/54785010-c4575900-4bea-11e9-8e99-52d8dfa52dd7.png">

Tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryanboza Do the bulk actions work if you use the default workflow?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16298

**Comment by bryanboza** [comment]
Fixed, now we are able to use the actions of the system workflow when you are on the community edition
