### ISSUE TITLE
[Vanity URLs] : Redirection to external URL is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16271]
Reported when working on Support Ticket: https://dotcms.zendesk.com/agent/tickets/97747
Reproducible in dotCMS 4.3.3, and latest master.

As stated in our official documentation: https://dotcms.com/docs/latest/vanity-urls#Uses you can create Vanity URLs that redirect to external sites.

## Expected Behavior
Setting the correct HTTP code, the user should be taken to the URL in the `Forward To` field of the Vanity URL.

## Current Behavior
The URL in such a field is being treated as an internal URL.

## Steps To Reproduce
1. Log into the dotCMS back-end, and go to the **Vanity URLs** portlet.
2. Create a Vanity URL with the following values:
2.1 My Test
2.2 All Sites
2.3 /my-test
2.4 301 - Permanent Redirect
2.5 www.google.com
2.6 0
3. Open a new Incognito Window, and go to http://localhost:8080/my-test
4. The 404 Error Page is displayed, which is wrong. You should have been redirected to www.google.com

**Comment by wezell** [comment]
This works - you are hitting the haproxy ssl redirect.  Try https.

```
mustardgreen:dotcmsMono will$ curl --head https://demo.dotcms.com/aaa
HTTP/2 301
location: www.google.com
date: Thu, 21 Mar 2019 22:03:29 GMT
set-cookie: BACKENDID=172.19.0.3; path=/
cache-control: private
```

**Comment by wezell** [comment]
ah, I see.  It works, you just need to add the protocol, e.g.: https://google.com
```
mustardgreen:dotcmsMono will$ curl --head https://demo.dotcms.com/aaa
HTTP/2 301
location: https://www.google.com
date: Thu, 21 Mar 2019 22:06:07 GMT
set-cookie: BACKENDID=172.19.0.3; path=/
cache-control: private
```
