### ISSUE TITLE
Fix IT ReindexIndexAPITest.addRemoveContentFromIndex

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#16287]
Fix the test ReindexIndexAPITest.addRemoveContentFromIndex that has been failing for a long time on MSSQL, MySQL and Oracle

https://cb.dotcms.com/view/builds%20-%20full%20-%20master/job/Build_Full_Tester_Func_Int_master_Oracle/lastCompletedBuild/testReport/com.dotmarketing.portlets.contentlet.business/ReindexIndexAPITest/addRemoveContentFromIndex/

https://cb.dotcms.com/view/builds%20-%20full%20-%20master/job/Build_Full_Tester_Func_Int_master_MySQL/lastCompletedBuild/testReport/com.dotmarketing.portlets.contentlet.business/ReindexIndexAPITest/addRemoveContentFromIndex/

https://cb.dotcms.com/view/builds%20-%20full%20-%20master/job/Build_Full_Tester_Func_Int_master_MSSQL/lastCompletedBuild/testReport/com.dotmarketing.portlets.contentlet.business/ReindexIndexAPITest/addRemoveContentFromIndex/

**Comment by wezell** [comment]
We need to make these integration tests.  See the work here: #16277

**Comment by nollymar** [comment]
Fixed on #16277
