### ISSUE TITLE
Doc: Standardize REST API Documentation

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16282]
**Note:** This is purely a documentation site issue; no impacts on the product.

* Create Content Types which enable definition of REST APIs, Endpoints, and arguments
* Create Doc pages (or possibly a Container or widget) which display the REST APIs in a standard format, using the new Content Types
* Add content for existing REST APIs to the new Content Types
* Update existing REST API docs to show the standardized format
* Replace the existing "REST API Endpoints" document with a REST API browser page (or section of the doc site) to make it easy to browse our REST APIs and endpoints
* Possible Future: Generate Open API config files using these new Content Types

**Comment by mawentowski** [comment]
Hello,

I am a technical writer who has taken some courses on documenting REST APIs, and am looking for experience assisting open source projects. Do you need any help on this project?

Mark
