### ISSUE TITLE
Submit content via Rest API does not relate to multi-lingual contentlets

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16299]
Tested in 5.0.3 and in 5.1

This bug seems to have been introduced somewhere in the 5.x series.  Easy to test with starter data.  Test this curl command which submits a new employee related to the "South America" location... it works just fine:

```  
curl -v -u admin@dotcms.com:admin -XPOST https://demo.dotcms.com/api/content/newpublish/1 -H "Content-Type:application/json" -d '{
    "ipAddress":"127.0.0.1","stName":"Employee",
    "Parent_Location-Child_Employee":"+structureName:Location +identifier:0c69da5c-2a05-452f-9305-3be6926d5079",
    "gender":"male","firstName":"test1","lastName":"lasttest1"
}'
```  
The employee should be related to the South America location just fine and the submit works.

**BUG**: Now edit the South America Location from the backend, and give it a spanish version.  Then try the curl command again, maybe with a different first and last name, and the relationship does not work to relate the contentlets using the same lucene query.

In 5.0.3 this gave me a strange 404 error with "invalid content fields" messaging, and in 5.1 it just fails to relate the new content being submitted to the location.

There does exist a work around, but not logical that you should have to do this, you pass a single language identidier at the end of the lucene query " +languageId:1" - this then allows the content to be submitted and related property.  Not intuitive because relationships have historically been independent of language.

**Comment by nollymar** [comment]
The fix might be here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/util/RelationshipUtil.java#L83-L84

**Comment by wezell** [comment]
We have a `findContentletByIdentifierAnyLanguage` method.  Maybe use that one?

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16334

**Comment by DeanGonzalez** [comment]
I tested this with front end form and now relating a new contentlet relates the new contnet to both language versions without issue.
