### ISSUE TITLE
Update content types portlet to use v2 endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16296]
As a stakeholder I want to make sure that the UI use the latest version of the content types endpoint.

### Endpoint
Same as before but `v2`.

### Solution
In the FE we're doing a bunch of work to try to fix the legacy content types, the ones that doesn't have layout, columns and rows, now in the new version of the API the backend will take care of that and it will returned a proper content types with all the necessary layout field.

We need to update our component and services to **NOT** do that extra work.

### Extra
The `v1` endpoint receive `workflow` although we send a group of workflows, please update the name of the property to `workflows`.

## Acceptance Criteria

1. Update the endpoint to `v2`
2. Clean up the content type portlet code to not update the layout of a content type
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
1. We need to respect the max 4 columns per row rule
    - If there are more empty cols, clean them up
    - If there are more filled cols, clean and add the fields to the last valid (4th) col
2. Is we have row + row + row (no cols or fields) clean
3. Is we have row + field (no cols) fix.

**Comment by fmontes** [comment]
@wezell found an issue:

1. Edit the news
2. See the publish and expiration fields are disabled

**Comment by bryanboza** [comment]
Fixed, tested on master // Postrgres // FF. After the changes now we are using the new version (v3) of this resource
