### ISSUE TITLE
Create v2 content type endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16295]
As a stakeholder I want content type endpoint to be more robust on the layout part.

### Endpoint
`/api/v1/contenttype/id/{content type id}`

### Solution
1. Create a new vession `v2` of the endpoint
2. Handle all the legacy content types in the backend
    - If a content type doesn't have the proper format (rows, columns, etc) add it before response
3. Error handling
    - If a content type is corrupted, like rows and columns in the wrong position, fix those before response.

### Extra
The `v1` endpoint receive `workflow` although we send a group of workflows, please update the name of the property to `workflows`.

## Acceptance Criteria
1. Endpoint return a content type with full layout
2. Handling legacy content types
3. Handling corrupted layouts in content types 
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16431

**Comment by jgambarios** [comment]
Reverting changes: https://github.com/dotCMS/core/pull/16491 https://github.com/dotCMS/core/pull/16492

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16521

**Comment by fmontes** [comment]
The way we're handling errors here miss typed:

- The error handler method receive a `ResponseView` here: https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-http-error-manager/dot-http-error-manager.service.ts#L51
- But then in each specific error handler receive a `Response` , like [here](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-http-error-manager/dot-http-error-manager.service.ts#L86), [here](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-http-error-manager/dot-http-error-manager.service.ts#L142) and [here](https://github.com/dotCMS/core-web/blob/master/src/app/api/services/dot-http-error-manager/dot-http-error-manager.service.ts#L103)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16921
