### ISSUE TITLE
DB dropped on user add

### ISSUE THREAD

**Issue by JamesArthurHolland** [dotCMS/core#16300]
A colleague had been working on 5.1.0, spent numerous hours adding content.

Tried to add a new user to the system, it crashed and emptied the database table.

**Comment by dotcmsCodeReview** [comment]
I don't think it wiped the db per say. Maybe you were running H2 which is
just for demo purposes and not postgres,mysql,oracle, or mssql

**Comment by JamesArthurHolland** [comment]
Followed the instructions as per https://dotcms.com/docs/latest/basic-aws-installation

**Comment by JamesArthurHolland** [comment]
Do you not think it would be better to invest time in doing an ansible install script, so that people can install by running that instead? Would be easier for yous to know whether it passes tests or not either.

That script installs java-headless, when dotcms needs tools.jar from full jdk.

**Comment by wezell** [comment]
@JamesArthurHolland I have never seen or heard of an issue adding a user causing a database to be emptied. I am fairly sure that something else happened with regards to the server setup.  If you want automated, I would try using some of our docker images.

**Comment by JamesArthurHolland** [comment]
docker images weren't production ready I thought?
