### ISSUE TITLE
Update AjaxDirectorServlet (and friends) to use our common auth and accept json

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16301]
We have a ton of important tooling written as `AjaxActions`.  These actions are not broken, but they do things differently than our jax-rs endpoints.  Rather than rewrite all of these, I would like to do two things:
1. Update the authentication on these tools to match our other resources, which means use the `WebResource.init()` tooling -the WebResource should be the single source of truth and the only place we are doing auth for endpoints in the system.
2. Allow the AjaxActions to take `json`. Most of these endpoints take POSTed form params and there is no reason why we can't extend that and allow them to accept json as well.

3. After doing this update, I would like to create a script that shows the following process in curl.
- Get an auth key and use it to:
- Add a host to a bundle (using json)
- Download the bundle (using json)
- Kick off a push publish of the bundle

![Screen Shot 2019-03-28 at 9 49 18 AM](https://user-images.githubusercontent.com/934364/55163395-185cc300-5140-11e9-8b32-4462cbafb74b.png)

**Comment by wezell** [comment]
### Store AUTH Token
```
export TOK=`curl -H "Content-Type:application/json" -s  -X POST -d  '{ "user":"admin@dotcms.com", "password":"admin", "expirationDays": 365, "label":"for testing" }' http://localhost:8080/api/v1/authentication/api-token | python -c 'import json,sys;print json.load(sys.stdin)["entity"]["token"]'`
```


### Add an object to bundle by Id (any object, not just content)
```
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST  http://localhost:8080/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/addToBundle -d '
{
    "assetIdentifier": "e43fb490-a5b2-403c-845c-8a576cba62fc",
    "bundleName":"testing"
}
'
```
### Add add a contentType by query
```
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST  http://localhost:8080/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/addToBundle -d '
{
    "query": "+contenttype:news",
    "bundleName":"testing"
}
'
```
### Add add a host by name 
```
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST  http://localhost:8080/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/addToBundle -d '
{
    "query": "+host.hostname:demo.dotcms.com +live:true",
    "bundleName":"testing"
}
'
```

### Push the bundle , using the {bundleId} from the above call and a comma separated list of {UUIDs} of the environments you want to send to
```
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST  http://localhost:8080/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/pushBundle -d '
{
    "assetIdentifier": "{bundleId}",
    "remotePublishDate":"2001-01-01",
    "remotePublishTime":"10-00",
    "remotePublishExpireDate":"2051-01-01",
    "remotePublishExpireTime":"10-00",
    "iWantTo":"publish|expire",
    "whoToSend":"UUID-prod-environ1,UUID-prod-environ2",
    "forcePush":true|false
}
'
```
### Download the bundle as a .tar.gz file
```
curl -H "Content-Type: application/json" -H "Authorization:Bearer $TOK" -XPOST  --output my-bundle.tar.gz http://localhost:8080/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/downloadUnpushedBundle -d '
{
    "bundleId":"{bundleId}",
    "paramOperation": "publish|unpublish"
}
'
```

**Comment by nollymar** [comment]
**Tests Results:**
The following scenarios were tested: 

1. Adding content to a bundle - OK
2. Downloading a bundle - OK
3. Pushing a bundle - OK

Although all scenarios are working fine, there is room for improvements. I added a new card for this: https://github.com/dotCMS/core/issues/16457

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
