### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#1630]
In dotCMS 1.9 we ran into this issue as well but it was fixed. We are now running into the problem again that when saving special characters (in a page title for instance), that they are stored incorrectly in the database. This is caused by the CharsetEncodingFilter... It is not called as the first filter because there are some other filters (custom plugin filters for instance) that are called before this filter. 

When I change the web.xml and put the filter mapping of the CharsetEncodingFilter directly beneath the filter declaration then everything works well. Could you guys change the web.xml so this is always the case? (if possible)

**Comment by oarrietadotcms** [comment]
We are having this issue again: https://dotcms.zendesk.com/agent/tickets/97306
