### ISSUE TITLE
Add dot-field-helper to value in checkbox, radio, select and multiselect

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16312]
As a user, I want help to add the correct values to the fields

### Is your feature request related to a problem? Please describe.
When user is creating content type, the fields checkbox, radio, select and multiselect have very specific format for their value field and there is no indication or helper that tell the user what that format is.

### Describe the solution you'd like
We have a `dot-field-helper` to add help information to the form fields, we can use this component to add the help information we need.

### Messages for each field
1. Checkbox and Multiselect:
```
Set options to display like this:
Text|Value
Canada|CA
Mexico|MX
USA|US
```

2. Radio and Select
```
Set options to display like this:
Text|Value
Canada|CA
Mexico|MX
USA|US
 
Note: If you want to use True/False as your data type, you must use your native db representation for true and false, e.g.
True|1
False|0
```

### Mock
<img width="568" alt="Screen Shot 2019-03-29 at 10 19 45 AM" src="https://user-images.githubusercontent.com/751424/55247043-31cb4100-520c-11e9-8de8-d1cef020a3b1.png">

## Acceptance Criteria
1. Add dot-field-helper with specified message to checkbox, radio, select and multiselect
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we have the help button in all these fields
