### ISSUE TITLE
Key/value fields are not added to the index

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16313]
Reproducible in dotCMS 5.1.1

Key/value fields are not added to the index when they are saved as user searchable. 

**To Reproduce**
1. Log into dotCMS 5.1.1
2. Add a Key/Value field for a content type.
3. Save the field as "User searchable".
4. Add values for the Key/Value fields for a content item and save the content item.
5. Do a search from the Content Search portlet or from the Query Tool, using the value added in the previous step for the Key/Value field.
6. The content item is not returned from the search.

**Expected behavior**
The Key/Value field should be added to the index when it's saved as "User searchable", and Content Search should return results when content is searched using the Key/Value field.

**Screenshots**
Added "user searchable" key/value field to the content type:
<img width="503" alt="key-value-field" src="https://user-images.githubusercontent.com/2894221/55247304-dc436400-520c-11e9-876c-9c6d11a37e3c.png">

Saved and published a key/value for a content item:
<img width="964" alt="key-value-field-saved" src="https://user-images.githubusercontent.com/2894221/55247351-fe3ce680-520c-11e9-839b-9240d50dd6d6.png">

Search by key/value doesn't return results:
<img width="1145" alt="search-results" src="https://user-images.githubusercontent.com/2894221/55247375-101e8980-520d-11e9-9d15-443cc9b4f3be.png">

**Comment by brentgriffin** [comment]
Still a problem in 5.1.5

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16675

**Comment by erickgonzalez** [comment]
Working as it should in the release branch.

**Comment by bryanboza** [comment]
Tested in the last master and we continue with problems using this kind of fields 
SC: https://screencast.com/t/ZpFxPlrCt4Q

**Comment by erickgonzalez** [comment]
@bryanboza you need to search it like this `test:1` or `key1:v`

**Comment by bryanboza** [comment]
After making some tests, we detect the problem is the license if you don't have a license, we are unable to search content by this field. After apply a license I'm unable to reproduce the problem

**Comment by bryanboza** [comment]
Fixed, now when you have a license we are adding those fields to the index. New related cards here #16690 & #16691

**Comment by jcastro-dotcms** [comment]
Regarding Bryan's comment:
```
After making some tests, we detect the problem is the license if you don't have a license, we are unable to search content by this field. After apply a license I'm unable to reproduce the problem
```
Is this stated in our official documentation?

**Comment by bryanboza** [comment]
Fixed, new the detected problems should be fixed in the new cards
