### ISSUE TITLE
Existing Field content type can be modified via REST / Java API

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16315]
It's possible to change an existing field's parent content type via REST or Java API. 

To reproduce:
POST the following JSON against the Content Type Resource (/v1/contenttype)

https://gist.github.com/dsilvam/f879dce3230d7b0bdcc4f1ba34d73380

Notice that the BinaryField 'photo' has an `id` field set, with the value of an existing field's id (07cfbc2c-47de-4c78-a411-176fe8bb24a5)

This will make the photo field with that id to change from one content type to another. 

After doing this, the default Persona type will end up without the 'photo' field, which will be moved to the newly created Persona type.

**Comment by bryanboza** [comment]
Fixed, tested on master // Posgres // FF
