### ISSUE TITLE
ShortyCache does not invalidate

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16310]
We never invalidate the shortycache when an identifier or content is checked in.  This means, for example, if you push publish a content that references a shorty driven image or asset and do not push that asset as well - e.g. the image on the about us page, it will 404.  If you then push that image, the 404 image will never recover until you flush cache.  We need to invalidate the shorty cache on content and identifier checkin.

**Comment by wezell** [comment]
dupes #14546

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16379

**Comment by bryanboza** [comment]
After these changes, now we are unable to add folders, we get an error and the folder is not created 
Here the error: https://gist.github.com/bryanboza/8100bc7a6a52ccb5504f82d06d7e2588

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16387

**Comment by bryanboza** [comment]
Fixed, I made a sanity test to make sure everything continues working as expected

**Comment by bryanboza** [comment]
After these changes we are unable to upload file assets, we have an error in the JSP file when you try it 
Here the log: https://gist.github.com/bryanboza/4330b1a7e2ec80354c48266765a62876

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16415

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
