### ISSUE TITLE
Align dot-field-helper and fix the overflow of the field text

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16314]
### Describe the bug
`dot-field-helper` is not align correctly against the text field in the edit content type.

### Steps to reproduce the behavior:
1. Go to Content Types
2. Click in a content
3. Click on Edit Button
4. Scroll down to field: "Detail Page" and "Url Pattern".
5. See the missalignment and if the detail page value is long

### Expected behavior
The `dot-field-helper` should be aligned to the field based on the full touch area, see screenshot.

### Screenshots
<img width="1295" alt="Screen Shot 2019-03-29 at 3 25 51 PM" src="https://user-images.githubusercontent.com/751424/55263586-1f1a3180-5237-11e9-9b7a-38858c44935a.png">

### Desktop (please complete the following information):
 - OS: ALL
 - Browser ALL
 - Version: master

### Additional context
We need to add a class to the input text field that we can add when we have the `dot-field-helper`.

## Acceptance Criteria

1. Align the icon to the label of the field
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master
