### ISSUE TITLE
/public url does not render anything

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16311]
**Describe the bug**
When you go to `/dotAdmin/#/public` the app does not render anything.

**To Reproduce**
1. Go to https://demo.dotcms.com/dotAdmin/#/public
3. See nothing renders

**Expected behavior**
1. If the user is login it should go to the first portlet
2. If user is **not** login it should go to login page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version +5.0.0

**Additional context**
With the recent [changes](https://github.com/dotCMS/core-web/pull/956) in the login page we might need a guard to achieve this.

## Acceptance Criteria

1. `/public` should go to first portlet or login
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
