### ISSUE TITLE
Rules Portlet not displaying Persona when using `Set Persona` actionlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16324]
When adding a rule that uses the `Set Persona` Actionlet, the UI is not displaying the chosen Persona after saving the rule. The value is being saved in DB, so it looks it's only the UI not properly displaying the value. 

Steps to reproduce. 

1. Go go Rules Portlet
2. Create a new Rule and in the `When fired, this Rule performs the following action(s):` section select `Set Persona` and choose any available Persona
3. Toggle the switch at top right corner of the rule
4. Go to a different portlet and come back to Rules Portlet
5. Expand the newly created Rule and notice there's no Persona shown.

**Comment by fmontes** [comment]
Closing in favor: https://github.com/dotCMS/core/issues/16352
