### ISSUE TITLE
[Vanity URLs] : Adding improvements

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16333]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97747
Reproducible in customer environment running dotCMS 4.3.3

Adding some improvements to the way Vanity URLs are loaded into memory after a Vanity URL has been updated and/or a cache flush.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/16337

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/16337

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16413

**Comment by wezell** [comment]
** A Test **
1. deactivating indexes
2. flush cache
3. see if vanity still work

**Comment by bryanboza** [comment]
After trying the test of the last comment, if you don't have active indexes we are unable to resolve the vanity and we are showing a blank page, also we have the following error on logs 
ST: https://gist.github.com/bryanboza/4bd32ada605c311fba7c730866e170d5

**Comment by bryanboza** [comment]
ok, after the @wezell approval seems we are ok for now
