### ISSUE TITLE
Push Publish: New folder doesn't show on navigation

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16341]
Reported via Support: Ticket [97885](https://dotcms.zendesk.com/agent/tickets/97885)
Reproducible in dotCMS 4.3.3, dotCMS 5.1.1

When a new folder is push published, it doesn't show on the site navigation menus on the target server.

### Steps to reproduce the behavior:
1. Create a new folder under a location shown on the site navigation, and enable the "Show on Menu" option for the folder.
2. Check that the new folder is shown on the site navigation menus.
3. Push publish the new folder.
4. Go the target server and open a page to check the site navigation menus.
5. The new folder doesn't show on the navigation menus.

### Expected behavior
When a new folder is push published, and its "Show on Menu" option is enabled, it should show on the navigation menu on the target server.

### Screenshots
New folder created in source environment with "Show on Menu" enabled:
<img width="753" alt="new-folder" src="https://user-images.githubusercontent.com/2894221/55660046-9a449000-57c1-11e9-8e3c-940d911b780e.png">

Navigation menu in the source environment, after creating a new folder:
<img width="805" alt="sender-navigation" src="https://user-images.githubusercontent.com/2894221/55660054-a0d30780-57c1-11e9-9338-95c9f180f1f2.png">

Navigation menu in the target environment doesn't show the folder after push publishing:
<img width="785" alt="target-navigation" src="https://user-images.githubusercontent.com/2894221/55660056-a7617f00-57c1-11e9-93d6-b737a0513b66.png">

### Additional context
This has been reported by customer via Support: Ticket [97885](https://dotcms.zendesk.com/agent/tickets/97885)

**Comment by dsolistorres** [comment]
PR: dotCMS/enterprise-2.x#664

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the last master // Oracle // FF. This on both endpoints
