### ISSUE TITLE
Content not reindexed when Relationships field removed

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16345]
### Describe the bug

When you delete a Relationships field from a content type, the content is not reindexed to remove the relations between the content items.

This shows up if you re-create the Relationships field with the same Velocity variable name (see steps to reproduce below).  Deleting a relationship and re-creating it with the same name is actually a fairly common use case (because that's the only way to change the cardinality of a Relationship), so that means this is a problem customers are likely to see.

### Steps to reproduce the behavior:

1. Create a "One to many" Relationships field named "Relationship Test" in a Content Type (we'll call it Content Type A), to any other Content Type.
    * Note the velocity variable name of the Relationships field is "relationshipTest".
2. Create a new content item of Content Type A.
3. Relate the new content item to a content item of Content Type B, using the new Relationship.
4. Delete the Relationships field ("Relationship Test") from the Content Type.
5. Create a "Many to many" Relationships field in Content Type A - also named "Relationship Test" - relating it once again to Content Type B.
    * Note the velocity variable name of the field is once again "relationshipTest".
6. Open the content item created in step 2, above, and view the Relationships field.
    * **Result:** The old relation (created in step 3, above) displays under the new Relationships field.
7. Flush the cache (System -> Maintenance -> Cache -> All Caches & FLUSH).
8. Open the content item created in step 2, above, and view the Relationships field.
    * **Result:** The old relation (created in step 3, above) still displays under the new Relationships (cache flush did not solve the problem).
9. Re-index the site (System -> Maintenance -> Index -> Rebuild Whole Index & REINDEX).
10. Open the content item created in step 2, above, and view the Relationships field.
    * **Result:** The new Relationships field now shows no relations (the reindex cleared the old relations that should not have been displaying).

### Expected behavior

When a Relationships field is deleted, the content type should be reindexed to remove old relations.

### Desktop (please complete the following information):

 - OS: Windows 10 Pro
 - Chrome v72.0.3626.81

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/16467

**Comment by erickgonzalez** [comment]
Tested with steps provided and it's working as it should. Now if you delete a relationship and add a new one with the same name, it no longer shows the old relations.

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Postgres // FF
