### ISSUE TITLE
Index problems creating content types that starts with numbers 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16347]
Related to #16096 

We have an index problem when you create a content type that starts with numbers, this because the first time we are not setting the variable and this is causing the error. 
Log: https://gist.github.com/bryanboza/8e8cfeaae046f4a93e30d47a6bd37779
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/32103839-b59b-42cc-b63e-3c8adac20721/00000279.png

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to content types portlet 
3. Create a new content type with this name `123`
4. Try to add a piece of content
5. Check your `catalina.out` log file 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
@john-thomas-dotcms: In this issue, Content Type and Field names were restrict not to start with numbers.

**Comment by dsilvam** [comment]
Passed internal QA: Able to add content types who's names start with numbers, and a valid variable name is generated and content of that type can be created

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master, now when the content type starts with numbers, we are adding the first number in letters, this on the variable name

**Comment by dsilvam** [comment]
PRs: 
https://github.com/dotCMS/core/pull/16354
https://github.com/dotCMS/core/pull/16366
https://github.com/dotCMS/core/pull/16369

**Comment by bryanboza** [comment]
We have a pending case here: 
- When you create a new content type that starts with any special character, we exclude this one and the varName start with the next character, but when a next character is a number we have an error in the log and we are unable to create the content type, then we need to fix the problem or maybe send an error message to the backend 
`ERROR contenttype.ContentTypeResource - Invalid content type variable: `

**Comment by bryanboza** [comment]
After the last changes, when you try to add a content type that starts with a special character, now we are replacing this character for a `_`, but then if you try to add to new content types with the following names: 
`*123` the variable name will be  `_123`
``$123 the variable will be `_123`

Then any kind of character will cause an error with the variable, and we are just trying to add a `1` after the name, and we are showing an error in the log `ERROR contenttype.ContentTypeResource - Invalid content type variable: *1231` this because this is an invalid variable name

**Comment by erickgonzalez** [comment]
@bryanboza this works fine on my env. I'm able to create content types with a special character and number and nothing shows up on the logs.

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
