### ISSUE TITLE
Deep rules QA

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16352]
Rules is having different issues with fields, sometimes the options we select or type are not getting persistent. Need to find out and list the problems.

## Acceptance Criteria

1. List in the comments the issues with rules
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
- [ ] Unable to filter dropdowns b/c the toggle switch and "Rule Saved" message takes focus.
Try to create a condition where visitor country is united states

- [ ] Set persona value is not saved

**Comment by wezell** [comment]
![Screen Shot 2019-04-15 at 11 49 37 AM](https://user-images.githubusercontent.com/934364/56146700-ad4f2100-5f74-11e9-9e83-d6606c15012a.png)

**Comment by bryanboza** [comment]
We have an error in the JS console and we are unable to save correctly the actionlet 
sc: https://screencast.com/t/rgLMURPl

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now works as expected
