### ISSUE TITLE
Can't add contentlets to file system container

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16351]
### Describe the bug
When you add a contentlet to a file system container there is a en error in the console.

### Steps to reproduce the behavior:
1. Edit a page with a file system container
2. Add a contentlet
3. The contentlet doesn't show and there is an error in the console

### Expected behavior
Users should be able to add contentlets to any type of containers.

### Problem
When we add a contentlet (or drag and drop and existing one) to a containers, we do a request to get the HTML to:

`/api/v1/containers/id/content/inode`

The problem is that when the container is a file system the url ends up like:

`/api/v1/containers//application/containers/large-column//content/27108d63-969e-4086-a405-86777be16230`

And we get a 404

### Solution
Cody is creatring a new endpoint that we'll be able to use with the following url:

``/api/v2/content/27108d63-969e-4086-a405-86777be16230?container=/application/containers/large-column/` (edited) `

## Acceptance Criteria
1. Users should be able to add contentlets
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
We can use the branch: `issue-16263-changes-tosupport-containerpath-onpagerender`

and do:

```/api/v1/containers/content/2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6?containerId=/application/containers/large-column```

**Comment by bryanboza** [comment]
Fixed, now we are able to add contents without problems
