### ISSUE TITLE
NPE changing the company logo

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16361]
### Describe the bug
We are returning an NPE error on logs every time you try to change the company logo in the configuration portlet 

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to configuration 
3. Try to change the company logo 
4. Upload the image 

### Expected behavior
We need to be able to change it without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF 

### Additional context
Here the error:  https://gist.github.com/bryanboza/b87c7106c2b02cd5329374e03963b10e

**FYI: We are changing the company logo, but return this NPE**

**Comment by Xander-Steinmann** [comment]
We have the same problem in dotCMS 5.1.1 but we can't reproduce this on the demo site.
