### ISSUE TITLE
Expect IT tests to be run from /tomcat8

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16364]
Our IT tests all run from `/tomcat8/webapps/ROOT/`.  The issue is that some of our it-config.properties are set to this path and some are not.  I would like the IT tests to be able to be run locally without having to touch these files, just by symlinking my dev dotCMS folder to /tomcat8.  This should not affect our current it tests

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16365
