### ISSUE TITLE
[Plugins] : The "com.dotcms.repackage.org.w3c.dom.Element" class is still being referenced in dependent JAR

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16377]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/97941
Reproducible in dotCMS 5.1.1

After moving the Tika .JAR over to the ODGi context, the `com.dotcms.repackage.org.w3c.dom.Element` class was removed. Now, dotCMS exposes its un-repackaged version: `org.w3c.dom.Element`

However, the `dot.core-renderer-modified-ukv_2.jar` file still contained a reference to the old `com.dotcms.repackage.org.w3c.dom.Element` class. So, for example, when importing the `com.dotcms.repackage.org.xhtmlrenderer.render.BlockBox` class in an OSGi plugin, the code ends up trying to import the invalid repackaged class and throws a compilation error.

### Expected behavior
The repackaged version of the class should not be referenced anymore.

### Workaround
Follow the current approach with custom OSGi plugins: Provide your own versions of the .JARs that your code needs instead of relying on dotCMS code.

### Desktop:
 - OS: Not relevant.
 - Browser: Not relevant.
 - Version:  Not relevant.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/16378

**Comment by aotearoan** [comment]
@jcastro-dotcms when can we expect 5.1.5 to be released?
