### ISSUE TITLE
Integration tests with a clean starter

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16372]
We need to be able to run all the integration tests without starter data, each of our tests should create their own required sets of data.

So the goals on this ticket are:

- [x] Where ever we are using starter data we need to create our own test data objects.
- [x] Be able to run the Integration tests without to start the application prior to run the tests in order to create the database, the Integration tests should be able to notice if the db is empty and run the schema creation queries.
- [x] Be able to run the Integration tests without the need of having a tomcat folder with the deployed war in it, we should just checkout the code, set properties and run the `test` gradle task.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16797

**Comment by wezell** [comment]
0. create Shell Script to `./runTests.sh mysql` 
1. Shell script to auto parse commit/branch
2. Shell script to shutdown any previous run
3. move Docker folder to ../Docker
4. remove fat starter.zip from testing seed
5. Set DB ports to non-standard ports

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16945
