### ISSUE TITLE
Problems setting  existing fields as required 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16376]
### Describe the bug
We have a problem when you have a content type with some fields, and you change the properties of any of those to make this required after you try to leave this field in blank saving a  content, we continue having the same error even though you set a valid value

### Steps to reproduce the behavior:
1. Create a new content type.
2. Add a Title field (all boxes checked - required, indexed, etc.)
3. Add a Select field. with the following values, and leave all boxes (required etc.) **un**checked.
```
|
0.1|0.1
0.2|0.2
0.3|0.3
```
4. Add 2 content items with titles but no "Version" value.
5. Add a 3rd content item with both a title and a Version value.
6. Change the "Version" Select field to make it required.  (No other boxes checked).
7. Try to change the "Version" value in the first 2 content items you created (in step #4).

### Expected behavior
We need be able to set the values and save without problems 

### Screenshots
Here a video: https://screencast.com/t/jYEBqquHN
 
### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
Tested with the steps provided and it's working as it should.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. New enhancement created #16454
