### ISSUE TITLE
Recurring event status not editable

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16370]
### Describe the bug
Once a recurring event has been created the recurrence controls are no longer displayed on subsequent edits.

### Steps to reproduce the behavior:
1. Go to Calendar
2. Create Event
3. Set a recurrence
4. Save/Publish
5. Close edit window
6. Go to Calendar
7. Select event from list
8. Select Edit, no recurrence controls appear

### Desktop (please complete the following information):
 - OS: Mojave
 - Browser Safari
 - Version 5.1.1

**Comment by wezell** [comment]
![Screen Shot 2019-04-11 at 11 39 10 AM](https://user-images.githubusercontent.com/934364/55970928-83cd8700-5c4e-11e9-978d-6d4178fa5e15.png)

**Comment by bryanboza** [comment]
Tested in the dev branch and we need to try to continue with the same behavior that we have in demo

- We need to be able to edit recurring events and show correctly the recurrence when you try to edit
 
- When need to exclude edit options radios from the concurrency box, we need to include as a new field in the main form.

- When you edit a recurrent event, and you set only this instance, we need to show the edit window as a new single event(not recurrent), as in demo, and after save, delete the recurrent instance of the day that you are editing and create a new single event (not create a copy).

-  When you are editing a recurrent event, and select only this instance, we need to auto set the dates with the same date of the day that you are editing.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16463

**Comment by bryanboza** [comment]
When you try to edit a recurring event only the selected instance, we are opening the event in the same portlet and not in the content modal, as when you try to edit a single event.
SC: https://screencast.com/t/wWjd3tyc

**Comment by jgambarios** [comment]
The issues above will be address in https://github.com/dotCMS/core/issues/16509

**Comment by bryanboza** [comment]
Fixed, this works better now. New enhancements reported in the related card (#16509 )
