### ISSUE TITLE
Delete error message/code from response headers

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16383]
### Describe the bug
We are duplicating the error messages in the response headers which is wrong, the error message should be only in the response body
<img width="1168" alt="00000292" src="https://user-images.githubusercontent.com/2641437/56052230-1e40cf80-5d0e-11e9-87ad-d4e69f153fcb.png">

## Environment 
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17458

**Note to QA:** Please test '/es/search' endpoint too

**Comment by dsilvam** [comment]
Passed Internal QA: No duplicated error messages. Only showing one now.

**Comment by dsilvam** [comment]
Passed QA Release 5.2.1

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
