### ISSUE TITLE
Error adding content from edit mode when user does not have content portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16399]
Two issues - 

- [x] if you delete the "Content" layout and add another layout, say `Assets`, and then try to add a NEW piece of content (not reuse) from edit mode, you will get an NPE.  
See Below:

- [x] if you remove the content portlet for a limited user and add another custom portlet, say "Files", and you try to use it to add content as the limited user , you will get kicked out to the login screen.  

#### how to reproduce the first issue 
![bad-add](https://user-images.githubusercontent.com/934364/56098449-b38ac200-5ece-11e9-96e3-0cda6d505641.gif)

**Comment by erickgonzalez** [comment]
Those changes and then some were made in the main issue https://github.com/dotcms/core/issues/16161
