### ISSUE TITLE
Content API submit fails when field name begins with the same letters as the Content Type Name

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16404]
Saw this on latest master.  I have included a bundle to replicate what I show in the video

I have a content Type called BlogComment and I had created a WYSIWYG field called "Blog Comment" and a relationships field called "Blog Commentor" and both failed until I changed the names of both fields.  It seems to me that they both failed, surprisingly, just because they both started with the same letters as the content type name

![Bug](https://user-images.githubusercontent.com/1569167/56155434-1dab7180-5f78-11e9-9919-b8a058b0c48f.png)

Dropbox bundle: https://www.dropbox.com/sh/78cg9o0mcch6o65/AACydS44u282a1UcVuMqF1Kda?dl=0

Video:
https://www.screencast.com/t/tOzQlUlT

This is the error I see in the log:
```  
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[15/04/19 17:48:13:611 GMT] ERROR business.WorkflowAPIImpl: There was an unexpected error: Contentlet's fields are not valid
[15/04/19 17:48:13:611 GMT] WARN rest.ContentResource: Contentlet's fields are not valid
com.dotmarketing.portlets.workflows.business.DotWorkflowException: Contentlet's fields are not valid
```

**Comment by bryanboza** [comment]
Moved to #16407
