### ISSUE TITLE
Need to improve the error handler in the Set Value sub-action

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16403]
### Describe the bug
We are showing an NPE error when you add a `SetValue` sub-action and you don't set correctly the `velocityVar Name of the field to set:` 

FYI: Right now after the error we are closing the error window and we are not executing the sub-actions after this one. Then we lose the modifications in the content. 
Log: https://gist.github.com/bryanboza/4b56f146d94fc1b7f62ab4d518260396
### Steps to reproduce the behavior:
1. Login as admin
2. Create a new workflow action in any of the existing workflows
3. Add the set value sub-action 
4. Set an unexisting value to the field `velocityVar Name of the field to set:` 
5. Try to add a piece of content to any content type associated with this workflow and execute the action 
6. Check your catalina.out log file 

### Expected behavior
We need to try to show a message with the error in the UI and stop the execution

### Screenshots
<img width="720" alt="set1" src="https://user-images.githubusercontent.com/2641437/56152134-1f713700-5f70-11e9-922e-f9aa017e5b42.png">

### Desktop (please complete the following information):
Tested on master // postgres // FF

**Comment by wezell** [comment]
1. Fail with a `DotContentletStateException`, not an NPE
2. Stop processing
3. Send a toast message sending the error message
