### ISSUE TITLE
Categories not pulled in Front End

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#16409]
### Describe the bug
Categories are not being pulled in Front End.

### dotCMS 
Version: 5.1.1, 5.1.6

### Steps to reproduce the behavior:
1. Create a new Page + Widget with this velocity code from https://dotcms.com/docs/latest/pulling-categories
```
#foreach($news in $dotcontent.pull( "+contentType:News", 10, "modDate desc" ))
    <h2>$velocityCount. $!{news.title}</h2>
    <ul>
    #foreach($cat in $news.topic)
        <li><b>Category Name:</b> $!{cat.categoryName}</li>
        <ul>
            <li><i>Category Key:</i> $!{cat.key}</li>
            <li><i>Velocity Variable Name:</i> $!{cat.categoryVelocityVarName}</li>
        </ul>
    #end
    </ul>
#end
```

2. Hit the front end page.

### Screenshots
Categories not shown. Only the title. 

<img width="1028" alt="Screen Shot 2019-04-16 at 9 21 39 AM" src="https://user-images.githubusercontent.com/8225685/56224126-4ab95c00-602c-11e9-8522-a153090934cc.png">

### Additional context
Client ticket: https://dotcms.zendesk.com/agent/tickets/97962

**Comment by wezell** [comment]
I am not sure the fix is the right one - this could expose all categories to backend users who only have access to a few categories.  We either need an overloaded method that passes the `respectFrontEndRoles` boolean OR get the full category list in the velocity `ContentMap` using the system user and then apply the `permissionAPI.filterCollection` to it with the viewing user.

**Comment by oarrietadotcms** [comment]
Client would like to have this in the next release: https://dotcms.zendesk.com/agent/tickets/98362

**Comment by wezell** [comment]
@oarrietadotcms did you see my comment above?  It is not the right fix.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16826 the CategoryAPI methods already had the `respectFrontendRoles` boolean but was set to false. Regarding the inquiry that this change could expose categories to other users, this was tested and still working as it should, users with limited access to categories keep seeing only the ones they have access on.

**Comment by bryanboza** [comment]
Fixed, now we are able to see that from FE without problems

**Comment by dsilvam** [comment]
Passed Internal QA: Tested with a few combinations of permissions for front end users and it's working correctly.

**Comment by dsilvam** [comment]
Needs Integration tests

**Comment by erickgonzalez** [comment]
PR for IT: https://github.com/dotCMS/core/pull/16898

**Comment by dsilvam** [comment]
Reassigning labels since only integration tests were missing
