### ISSUE TITLE
Refresh custom content portlet after closing edit content window

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16402]
Unlike the normal content screen, when you add a piece of content from a custom content listing screen, the listing does not refresh.  Closing the edit content screen should call refresh on the content portlet or any portlet whose id starts with `c_` 

To reproduce:
1. Create a custom content portlet
2. Go to it, click add content
3. Save a new content item, close content window
4. Custom content portlet does not refresh.  You need to manually hit search to see the new content.

**Comment by wezell** [comment]
@freddyucv is this in master? It is not working for me.

**Comment by bryanboza** [comment]
This isn't working on the last master 
SC: https://screencast.com/t/f2i9m5i6BR

**Comment by bryanboza** [comment]
Fixed tested on master // Posgres // FF

**Comment by wezell** [comment]
This is not working
