### ISSUE TITLE
dotcms.jar POM file does not contain excludes

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16406]
When we register the `dotcms.jar` into artifactory (maven) we generate along with jar a **POM** file with all the dotCMS dependencies inside the `dependencies.gradle`, those dependencies are downloaded together with the main jar when the dotCMS artifact is requested.

**Example:**
```
compile('com.dotcms:dotcms:5.1.1') { transitive = true }
```

Our internal `dependencies.gradle` file contains multiple excludes in order to avoid to download libraries we won't use or would cause conflicts with other existing jars.

**Example:**
```
compile (group: 'org.elasticsearch', name: 'elasticsearch', version: '6.1.3'){
        exclude(group: 'org.apache.logging.log4j')
}
```
In the above case we exclude `log4j` when the `elasticsearch` dependencies are downloaded in order to avoid to have two versions of the `log4j` libraries.

The issue we saw is the **POM** file is created without those `excludes` so we could potentially end up with different versions of the same libraries colliding in OSGI plugins.

### Workaround

The workaround is to exclude the conflicting jar in the dotCMS artifact.
```
compile('com.dotcms:dotcms:5.1.1') { 
        transitive = true
        exclude(group: 'org.apache.logging.log4j') 
}
```

**Comment by oarrietadotcms** [comment]
Client ticket: https://dotcms.zendesk.com/agent/tickets/97946
