### ISSUE TITLE
Content API submit fails when field name begins with the same letters as the Content Type Name

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16407]
### Describe the bug
We have a naming problem when you use the new relationship field and the name is the same of the content type, this is causing some issue and we are unable to add a new piece of content to the content type.

### Steps to reproduce the behavior:
1. Login as admin 
2. Create two new content types  `Blog Comment` and `Blog Commentor`
3. To `Blog Comment` add those new fields `title (text), Blog Comment (WYSIWYG)` 
4. In the same content type, add a new relationship field `Blog Commentor` here the properties: https://screencast.com/t/gCjNOrbpQgM
5. Now on `Blog Commentor` add just one field `Name (text)` and add a relationship to see the existing relationship (Blog Comment//Blog Commentor) and call this one `Blog Comment`
6. Now via Rest-API try to add a Blog Comment piece of content  using this 
7. Create a new page, add a simple widget with the follow vtl code
https://gist.github.com/bryanboza/340252538d4635fe9b296d7f010c13ee
8. From FE try to upload a new comment 

### Expected behavior
We need to be able to add contents without problems 

### Screenshots
SC: https://screencast.com/t/z3Pd8PQ5kzQg

### Desktop (please complete the following information):
Tested on master // Posgtgres // FF 

### Additional context
Here the curl command to test directly the API
```
curl -v -u admin@dotcms.com:admin -XPUT https://ubisoft.dotcms.io/api/content/Publish/1 -H "Content-Type:application/json" -d '{
	title:"test",
	blogComment:"This is blog comment",
	contentHost:"demo.dotcms.com",
	contentType:"BlogComment" 
}'
```

Here the link to download the bundle: https://drive.google.com/file/d/1KE46s7JNenfjONR5M6fMMtF1zL-GeAQ1/view?usp=sharing

**Comment by nollymar** [comment]
Fixed: https://github.com/dotCMS/core/pull/16422

**Comment by erickgonzalez** [comment]
Working as it should now, we can add contents without issues.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes... Tested on master // Postgres // FF
