### ISSUE TITLE
EMA needs to respect styleClass on rows and containers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16414]
We've added the ability to add classes to rows and containers in the UI.  What we need now is to respect/use those in our EMA SPA.

It the `styleClass` property exists, add it to the wrapping containers and rows in React.

**Comment by freddyucv** [comment]
To test:

Using the plugin for SPA.

1- G to Edit Page, Layout
2 - Add class to columns and rows
3- Inpect the page in edit page and you should see the class that you add in the step 2
