### ISSUE TITLE
Workflow selection cut off on Content Types of any Base Type other than "Content"

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16425]
### Describe the bug

On any Content Type of a Base Type other than "Content", when you edit the Content Type to select which Workflow Schemes to apply to the Content Type, the list of Workflow Schemes is cut off, and schemes below the first 3 in the list can not be selected.

### Steps to reproduce the behavior:

1. Create 3 new Workflow Schemes (give them any names or properties you want).
2. Open the Content Types screen (`Types & Tags` -> `Content Types`).
3. Open the `File Asset` Content Type.
4. Click `EDIT` in the header to edit the properties of the Content Type.
5. Click on the `Workflow` field to assign Workflow Schemes to the Content Type.
    * **Result:** The list of Workflows is cut off.
    * **AND** you can not select the 3rd new Workflow Scheme, because there is no way to scroll down to that Scheme in the list.

### Expected behavior

You should be able to select any of the Workflows on the system, when editing a Content Type of any Base Type.

### Screenshots

![image](https://user-images.githubusercontent.com/13456955/56504713-45498f00-64ce-11e9-83e1-8cc1edab326b.png)

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome v72.0.3626.81

### Additional context

* This problem exists for all of the Base Types except `Content`, which includes:
    * Widget
    * File
    * Page
    * Key/Value
    * Vanity URL
    * Form
    * Persona
* The only reason the `Content` Base Type does _not_ have this problem is that the popup window for that Base Type is larger (because it has the 2 additional fields for the URL Map properties).
    * However I expect that if you add enough Workflow Schemes, the `Content` Base Type may also exhibit this problem.

**Final Note:** If this problem happens here, it seems likely that all pull-down lists in all popups may have the same problem.  If possible, the solution should probably fix the control that generates the pull-down for all popups, not just fix the problem in this one popup (or else we'll see the problem again in other places).

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master after the last changes
