### ISSUE TITLE
Self related content blows up if you have both sides - depending on field order

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16420]
### 1. Create a self related content type

- Taxonomy
  - Name
  - Children (1-n relationship)

and you can manage content and the relationship.  And the relationship data looks correct:
```
| parent_relation_name | child_relation_name |      relation_type_value       |
|                      | children            | Taxonomy.children              |
```

### 2. Add the 2nd side of the relationship 
(`parents`) and place the field **below** the `children` so your type looks like:
 - Taxonomy
   - Name
   - Children (1-n relationship)
   - Parents (n-1 relationship)

and you can manage content and the relationship.  And the relationship data looks correct:
```
| parent_relation_name | child_relation_name |      relation_type_value       |
| parents              | children            | Taxonomy.children              |
```

### 3. move the `parents` field above the `children` field.  
Edit the content type and change the field order

 - Taxonomy
   - Name
   - Parents (n-1 relationship)
   - Children (1-n relationship)

and you can no longer edit the content (edit screen is blown up) and the relationship data is broken, e.g., it looks like:

```
| parent_relation_name | child_relation_name |      relation_type_value       |
| children             | children            | Taxonomy.children              |
```

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16427

**Comment by erickgonzalez** [comment]
Tested with the provided steps and can edit content without issues.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
