### ISSUE TITLE
Error trying to upload images from the WYSIWYG editor 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16428]
### Describe the bug
We have an error when you try to upload a new image using the WYSIWYG editor 

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new page 
3. TRy to add new generic content to the page 
4. From the WYSIWYG editor try to add a new image 
5. Select any folder and try to upload a new image from your computer
6. See error

### Expected behavior
We need be able to upload images without problems 

### Screenshots
SC: https://screencast.com/t/0VyMnIBnkpz4

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by jdotcms** [comment]
Not able to reproduce

**Comment by bryanboza** [comment]
Tested in the last master and we are unable to reproduce
