### ISSUE TITLE
Reorder or delete of first Workflow Step prevents access to Actions by "[Not Assigned]" content

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16421]
### Describe the bug

Normally, when you have content with the Workflow Step showing as `[Not Assigned]`, the actions in the first Step of a Workflow Scheme can be taken on that content.

However when you re-order the Steps in the Scheme  to make a different Step the first Step, or delete the first Step of the Scheme, the cache is not updated, so the actions in the new first step are not available to this content until you flush the cache.

#### Problem 1 (Reorder Steps in the Workflow Scheme):

1. Create a new Workflow Scheme.
2. Create a new Step in the Workflow Scheme named `Step 1`.
3. Add an Action named `Action 1` to the first Step of the Scheme.
    * Set 'Who Can Use` to `Anyone who can Edit content`.
    * Check the `All` checkbox in the `Show When` section.
4. Add the new Scheme to a Content Type that has content showing as [Not Assigned]` (e.g. the `File Asset` content type on demo/starter).
5. Open the Content Search screen and right-click on a File Asset showing as `[Not Assigned]`.
    * **Result** _(Correct)_: The `Action 1` action displays in the menu.
6. Create a new Step in the Workflow Scheme named `Step 2`.
7. Add an Action named `Action 2` to the first Step of the Scheme.
    * Set 'Who Can Use` to `Anyone who can Edit content`.
    * Check the `All` checkbox in the `Show When` section.
8. Re-order the Steps in the Scheme so `Step 2` is first and `Step 1` is second.
9. Open the Content Search screen and right-click on a File Asset showing as `[Not Assigned]`.
    * **Result (Error):** The `Action 2` action does **not** display in the menu.
10. Open the System->Maintenance screen, select the `Cache` tab, and flush all caches.
11. Open the Content Search screen and right-click on a File Asset showing as `[Not Assigned]`.
    * **Result** _(Now Correct)_: The `Action 2` action now displays in the menu.

#### Problem 2 (Delete the First Step of the Scheme):

1. Create a new Workflow Scheme.
2. Create a new Step in the Workflow Scheme named `Step 1`.
3. Add an Action named `Action 1` to the first Step of the Scheme.
    * Set 'Who Can Use` to `Anyone who can Edit content`.
    * Check the `All` checkbox in the `Show When` section.
4. Add the new Scheme to a Content Type that has content showing as [Not Assigned]` (e.g. the `File Asset` content type on demo/starter).
5. Open the Content Search screen and right-click on a File Asset showing as `[Not Assigned]`.
    * **Result** _(Correct)_: The `Action 1` action displays in the menu.
6. Go back to the Workflow Scheme, and delete the first Step.
7. Create a new Step in the Workflow Scheme named `Step 2`.
8. Add an Action named `Action 2` to the first Step of the Scheme.
    * Set 'Who Can Use` to `Anyone who can Edit content`.
    * Check the `All` checkbox in the `Show When` section.
9. Open the Content Search screen and right-click on a File Asset showing as `[Not Assigned]`.
    * **Result (Error):** The `Action 2` action does **not** display in the menu.

### Expected behavior

When a user makes changes to the Workflow Scheme which changes which Step is the first Step of the Scheme, the actions in the new first step should be available immediately to any content showing as `[Not Assigned]`.

### Desktop (please complete the following information):

- dotCMS: 5.1.0 (demo)
- OS: Windows 10 Pro
- Browser: Chrome v72.0.3626.81

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jdotcms** [comment]
After some test and research we do not need any change:
1) the first step can not be removed nor reorder
2) if a contentlet is on a step X, you can reorder the step X, but it does not matter (if it is not the first one which is fixed).
3) if the contentlet is on a step X, you can not remove it if it is being referrer by some step or contentlet.

So the only case it is not longer valid, since we not longer valid or reproducible
