### ISSUE TITLE
[Vanity URLs] : Trailing slash in Uri field is causing failure

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16433]
Found when working on Support ticket: [97747](https://dotcms.zendesk.com/agent/tickets/97747)
Reproducible in dotCMS 4.3.3, 5.1.1.

Based on our official documentation, in the **Important Notes** section: https://dotcms.com/docs/latest/vanity-urls#ImportantNotes the **Uri** value of a Vanity URL **can NEVER include a trailing slash when you put such a URI in the browser** because it will fail. However, in the back-end, the value of the **Uri** can have a trailing slash.

In the back-end, if the **Uri** value contains a trailing slash, the URI in the browser will fail EVEN with the trailing slash removed.

### Steps to reproduce the behavior:
1. Log into https://demo.dotcms.com/dotAdmin/#/public/login
2. Go to the **Marketing > Vanity URLs** portlet, and create a Vanity URL with the following values:
2.1 **Title**: Test
2.2 **Site**: All Sites
2.3 **Uri**: /test
2.4 **Action**: 200 - Forward
2.5 **Forward To**: /products/consumer-discretionary
2.6 **Order**: 0
3. In an Incognito Window, go to https://demo.dotcms.com/test and confirm that the **Consumer Discretionary ETF** is displayed correctly.
4. Now, go back to the **Marketing > Vanity URLs** portlet, click the Vanity URL you created and change the **Uri** value from "/test" to "/test/" (notice the trailing slash).
5. Re-load the Incognito Window, you'll get the 404 page.

### Expected behavior
If you save the **Uri** with a trailing slash in the back-end, and put such a uri **WITHOUT** the trailing slash in the browser, the Vanity URL is supposed to be recognized and work correctly.

### Desktop (please complete the following information):
 - OS: Mac OS 10.14.4
 - Browser: Not relevant.
 - Version: Not relevant.

## Acceptance Criteria

1. Match the documentation.
2. Unit test.

**Comment by jcastro-dotcms** [comment]
The issue reported in this ticket is still causing problems with several customers.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18089

**Comment by wezell** [comment]
This url throws an NPE in the log:
http://localhost:8080/DotAjaxDirector/com.dotmarketing.sitesearch.ajax.SiteSearchAjaxAction/cmd/getJobProgress/

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18103

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the problem after the changes.Tested on release-5.2.8 // Postgres // FF
