### ISSUE TITLE
Make sure all PermissionAPI calls use the same key for `tryLock`

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16442]
The StrippedLock used to lock permission loading is re-entrant.  For it to work correctly, the same key must be used on the same thread. We are using two different keys in two places in the PermissionBitFactoryImpl.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16486

**Comment by wezell** [comment]
Please try copying a site and pushing a site.

**Comment by bryanboza** [comment]
Unable to reproduce coping sites
