### ISSUE TITLE
Connection pool closes connections when still active

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16458]
Tomcat 8.5's db connection pool changed the default behavior of how `removeAbandoned=true` operates.  Apparently, in DBCP used by Tomcat 7, `removeAbandoned` would reset the abandoned timeout whenever a sql query was executed by the connection. In Tomcat 8.x, the `removeAbandonedTimeout` became a absolute limit and Tomcat will close an open connection regardless if the system is still using it, which causes transactional issues.  We have seen this have the  unintended effect of closing a connection in the middle of a large scale transactional import or export leaving the db in an inconsistent state. 

Tomcat 8.x answer to this is to set a `jdbcInterceptor` in the db config props that mirrors the older behavior of reseting the abandoned timeout with every query.  We need to update our docs and our default `context.xml` with this property.

`jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer" `

**Comment by wezell** [comment]
PR: #16459

**Comment by jgambarios** [comment]
Reverted changes on `dotCMS/src/main/java/com/dotmarketing/startup/StartupTasksExecutor.java` 
PR: https://github.com/dotCMS/core/pull/16489

**Comment by bryanboza** [comment]
Fixed, tested on master / postgres // FF
