### ISSUE TITLE
"Push Now" Workflow Sub-action is acting like the "Push Publish" sub-action

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16453]
Reproduced this on latest 5.1.1 release

The "Push Now" subaction should push immediately to the configured push publishing environment.  It should not produce a configurable modal.  I believe that somehow the push now code was altered and now is calling the "Push Publish" sub-action instead of the "push now" one-click sub-action.

![Screen Shot 2019-04-24 at 11.10.31 AM.png](https://images.zenhubusercontent.com/5716535fbf93871ccd99b32c/679a4e8e-cfb1-4765-a0d0-3d051d4c888d)

Screencast: https://www.screencast.com/t/gQyqxzBHj

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16574

**Comment by dsilvam** [comment]
Passed Internal QA: Dialog not showing anymore and taking the configured values.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
