### ISSUE TITLE
Create endpoint to get tag suggestions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16462]
As a user I want to be able to get tag suggestions from an endpoint.

### Is your feature request related to a problem? Please describe
In FOX we're creating a [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) to select tags and use it in the edit contentlet, we need an endpoint that we can hit to get the tag suggestions like we do here:

<img width="350" alt="Screen Shot 2019-04-24 at 3 37 51 PM" src="https://user-images.githubusercontent.com/751424/56695830-41249980-66a7-11e9-9a1e-d42d229d8714.png">

### Describe the solution you'd like
In dojo we do:

```
TagAjax.getSuggestedTag(tagName, selectedHostOrFolderId, showTagsForSearch);
```

But we can't do the same in the Custom Element because is standalone and independent from the JSP.

## Acceptance Criteria
1. Create endpoint to get tag suggestions
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
- Deprecate TagAjax
- remove the JSONTagsServlet.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16578

**Comment by dsilvam** [comment]
Note to QA:

Resource live under: `/v1/tags`
Available query params: `name`, `siteId`

Expected behavior:
1. `/v1/tags?name={tagName}` (no siteId): should return tags living under SYSTEM HOST filtered by `tagName`
2. `/v1/tags?name{tagName}&siteId={siteIdentifier}` : should return tags living under Site with`siteIdentifier` and filtered by `tagName`
3. `/v1/tags?`: should return all tags living under any site
4. `/v1/tags?siteId={siteIdentifier}`: same as 3. The `siteId` param only applies if `name` param is present.

**Comment by nollymar** [comment]
Tests results:
The API is working correctly with the different params combinations. However, when all tags are returned (using `localhost:8080/api/v1/tags?`), 127 tags are listed, more than the existing Tags functionality from UI, which returns 123 items.

**Comment by wezell** [comment]
We need to add the persona:true|false property to the returned tag as well.

![Screen Shot 2019-05-28 at 2 20 39 PM](https://user-images.githubusercontent.com/934364/58502113-dfe36080-8153-11e9-9422-32f090c4bf82.png)

**Comment by bryanboza** [comment]
We need some improvements here: 

- [ ] 500 error if you send an invalid site id 

- [ ]  We need to limit return tags from archived sites

**Comment by dsilvam** [comment]
PR for including additional properties: https://github.com/dotCMS/core/pull/16637
*siteId
*siteName
*persona

**Comment by bryanboza** [comment]
We still returning 500 error in case of invalid `siteId`

**Comment by wezell** [comment]
Followup on #16777
