### ISSUE TITLE
Auto-generate key on first time startup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16470]
We need to auto-generate a unique encryption key when dotCMS starts up for the first time, rather than use the one included in the starter.zip

Additionally, we need push publishing not to use the local encryption key when sending/receiving  the auth token for a bundle - a sender should be able to send a bundle to a receiver that has a different encryption key.

**Comment by wezell** [comment]
PR: #16472

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16504

**Comment by nollymar** [comment]
I tested PP with these changes and it's working correctly. These were the tested scenarios: 
1. Sender (Java jdk1.8.0_211), Receiver (Java jdk1.8.0_191). No additional properties set
2. Sender (jdk1.8.0_92), Receiver (Java jdk1.8.0_191). Properties set: 
```
ENCRYPTION_KEY_LENGTH=128
ENCRYPTION_DIGEST_ALGORITHM=SHA-256
```

**Comment by bryanboza** [comment]
Fixed, all the possible cases were tested by @nollymar, we need doc these changes in case of your java version.

**Comment by wezell** [comment]
dotCMS now requires  >=Java 1.8.0_162.  If the java version cannot be updated, you should install 
 the Unlimited Strength Jurisdiction Policy Files (one fo the last downloads at http://java.sun.com/javase/downloads/index.jsp) to be installed for the JRE. Not having this support will result in the InvalidKeyException when attempting to use 192 or 256 bit keys
