### ISSUE TITLE
NPE when the Network tab is refreshed in a cluster environment

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16487]
This error is thrown https://gist.github.com/nollymar/66bcffd27aab0d3f3eb7d5ffcc7b695d when the Network tab is refreshed in any of the nodes.

**Comment by nollymar** [comment]
ServerActionBeanCache needed to be flushed: https://github.com/dotCMS/enterprise-2.x/pull/666/files

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/666

**Comment by dsilvam** [comment]
Note to QA:
Network tab of every node need to be checked to see if it displayed info correctly

**Comment by dsilvam** [comment]
Passed Internal QA: 
Tested with a 3-node cluster. Network tab showing all the expected info and three nodes in green from every node.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes...  Tested with the docker environment
