### ISSUE TITLE
Unable to push entire sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16481]
### Describe the bug
We have problems trying to push an entire site, After configuring the push environment I'm able to push individual pages, and assets, also check for conflicts with the integrity checker, after trying with the site, we have a connection problems 

### Steps to reproduce the behavior:
1. Login 
2. Create a copy of the demo site 
3. Try to push this copy
4. Check your logs 

Here the log: https://gist.github.com/bryanboza/489cf865238318141e871a00fa502d38

**FYI: Tested multiple times and get the same error** 

### Expected behavior
We need to be able to push sites without problems 

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by fabrizzio-dotCMS** [comment]
PEr Bryan request I tried this exercise on my local copy of master and it is easily reproducible.

The Error I'm getting :

14:28:16.525  ERROR pusher.PushPublisher - An error occurred for the endpoint bf-endpoint with address 127.0.0.1:8086. Error: Already connected
com.dotcms.repackage.javax.ws.rs.ProcessingException: Already connected

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16593

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16593

**Comment by jgambarios** [comment]
Further improvements will be handle in https://github.com/dotCMS/core/issues/16597

**Comment by bryanboza** [comment]
Fixed, tested in the release branch, testing with the last java_version and works as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
