### ISSUE TITLE
Allow a custom portlet to be deleted

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16493]
When a user creates a custom portlet, we do not offer them the ability to delete it once is it created. We need to allow a user to delete a custom portlet once it has been created.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16511

**Comment by nollymar** [comment]
Tests Results: Success

**Comment by bryanboza** [comment]
We need to refresh the portlet list after delete any custom portlet, this in order to avoid problems, right now after deleting some portlet this still appearing in the list, and you are able to add again to the toll group.
SC: https://screencast.com/t/8ObaE8eZK

**Comment by wezell** [comment]
It does delete from the list, I think you just had it preselected.  If you hit the list dropdown again, it will be gone.

**Comment by bryanboza** [comment]
Here how this can affect, SC: https://screencast.com/t/wIQ9qHa2W

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16520

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/16522 for reset dropdown

**Comment by bryanboza** [comment]
We need also refresh the dropdown when you delete any custom portlet to avoid this kind of errors:
SC: https://screencast.com/t/Fo30L0m8

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16531 for reset dropdown when deleting a custom portlet

**Comment by dsilvam** [comment]
Passed Internal QA: Dropdown is refreshed after deletion of the custom portlet.

**Comment by bryanboza** [comment]
Fixed, now we are unable to reproduce the problem
