### ISSUE TITLE
Https pagination error

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#16502]
### Describe the bug
When run dotcms on https the pagination fail, because any request to load any page is do on http.

### Steps to reproduce the behavior:
1. Go to LoginAs
2. Open the "Please select a Login AS User" dropdown 
3. try to go to the second page

Also

1. Go to System/Sites
2. Create a new site 
3. the site-selector is not sync, this is because the request to reload the sites current pagination page fail (you can see it in the Network tab)

### Expected behavior
The pagination should work on https

### Desktop (please complete the following information):
 - Run on HTTPS

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16503

**Comment by bryanboza** [comment]
Fixed, tested on the release branch // Docker // FF and now I'm able to paginate without problems

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF, now I'm able to paginate without problems
