### ISSUE TITLE
Live content never makes it into index if different from working

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16505]
### Describe the bug
With the new index changes, when the live and working versions have different inode, the live version never makes it into the index. 

### Steps to reproduce the behavior:
1. create a piece of content.  Save and publish it.
2. Edit the content and just save it.  You should have a live and working version
3. Copy the content identifier.  Go to the luence query portlet.  Run:
`+working:true +identifier:{copied Identifier}`. You will get a result with the working inode
4. Now run `+live:true +identifier:{copied Identifier}`.  You get nothing.

### Expected behavior
Step 4 should return a contentlet with the live inode

**Comment by wezell** [comment]
Documentation site before fix:

![Screen Shot 2019-05-01 at 9 54 22 PM](https://user-images.githubusercontent.com/934364/57053458-32685480-6c5c-11e9-882e-000d0f11b4d6.png)

---
And after fix:
![Screen Shot 2019-05-01 at 9 58 38 PM](https://user-images.githubusercontent.com/934364/57053471-4c099c00-6c5c-11e9-96e3-ecd0132a4843.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16506

**Comment by bryanboza** [comment]
Fixed tested with both queries and now I've results on both cases
