### ISSUE TITLE
Custom Content Portlet Improvements

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16512]
As a user, I want to be able to edit and delete Custom Content portlets without having to edit the database.

Currently Custom Content portlets can be created, but:

* There's no easy way to view them to see what Content Types they display.
    * You can view the portlet and check to see what Content Types display in "Types" list there, but it may not be clear from that whether the portlet is showing specific Content Types you selected, or Base Types.
* There's no way to edit them to either:
    * Change the name of the portlet, or
    * Change what Content Types they display.
* There's no way to delete them.

This means that, for example, if a user adds a new Content Type and wants to add it to the Custom Content portlet, the only way they can do it is to create a new one that has all the desired Content Types, and stop using the old one (without deleting it).  And since they'll likely want to use the same name for the new one as the old one, that means they'll probably have 2 different portlets with the same name - which they won't be able to distinguish between when adding them to a Tool Group.

### Describe the solution you'd like

Allow all basic CRUD operations on Custom Content portlets.  This means that from the UI you should be able to do all of the following:

* Change the portlet name.
* Change the Content Types the portlet displays.
* Delete the portlet.
* View which Content Types it displays.
    * Note: The ideal would be some way to see this list of Content Types from the "Edit Tool Group" popup (where you can choose which portlets to add/delete in the Tool Group).
        * ![image](https://user-images.githubusercontent.com/13456955/57144532-1c4eb700-6d76-11e9-83c8-e5128d8002ce.png)
        * ![image](https://user-images.githubusercontent.com/13456955/57144633-50c27300-6d76-11e9-91e9-ba8d701d812f.png)

### Technical Approach

The bare minimum solution is to provide the ability to delete a Custom Content portlet.  That's not the ideal solution, but it would at least give users some way to do all the basic CRUD operations (e.g. they could "update" a portlet by deleting the old one and creating a new one).

A more useful solution would be to add some kind of an "Edit" button next to the Custom Content portlet when you're viewing it in the "Edit Tool Group" popup.  This would be fairly light-weight, and would re-use the existing Custom Content portlet popup to provide the ability to edit the values.

![image](https://user-images.githubusercontent.com/13456955/57144848-d9d9aa00-6d76-11e9-825e-813e8b81536b.png)

Note: A DELETE button would also need to be added to the Custom Content portlet popup.

## Additional Context

I ran into problems with this unexpectedly on our authoring server which resulted in us having 8 different versions of the "Documentation" Custom Content portlet, 6 of which had the exact same name.  This was ultimately due to a problem which was caused because I didn't flush my browser cache after the server was updated.  If the lack of a browser cache flush is what caused that issue, then it's likely some customers will have the same problem, and will end up with multiple versions of the same Custom Content portlet as well - with no way to edit or delete them.

## Acceptance Criteria

1. Provide some method for all basic CRUD operations.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by john-thomas-dotcms** [comment]
So I just realized that the other thing you can't change now is the _order_ of the Content Types as they show in the portlet.  The Content Types appear in the "Types" list in the order you choose when you create the portlet, and can't be changed after it's created.

While this is a minor issue (especially compared to the missing delete), it I think it makes it even more likely that customers will want to modify (or delete and then recreate) portlets.

**Comment by wezell** [comment]
@john-thomas-dotcms - delete is enabled - see #16493
