### ISSUE TITLE
Can't run Task05040LanguageTableIdentityOff on MS SQL

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#16519]
When upgrading a dotCMS 4.3.3 to 5.1.1 I get an error during startup:
`FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task05040LanguageTableIdentityOff
com.dotmarketing.exception.DotDataException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.{
  "SQL": [" ALTER TABLE language ADD non_idenity_id numeric(19,0); "],
`
### Desktop (please complete the following information):
 - OS: Windows
 - DotCMS version 4.3.3 to 5.1.1
 - Database: MS SQL

### Workaround
I manually executed the queries in the task sequentially, which worked. Then I updated the db_version table.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16547

**Comment by erickgonzalez** [comment]
Working as it should, I was able to upgrade from version 4.3.3 to current master without issues.

**Comment by bryanboza** [comment]
Fixed, tested upgrading from 4.3.3 to master and I'm unable to reproduce the error after the last changes.
