### ISSUE TITLE
Ignore liferay-portlet.xml when deploying new portlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16525]
While we no longer use `liferay-portlet.xml`, our osgi based portlets throw an exception and won't work unless one is included - even though the file does nothing.

1. Our osgi should not throw an error if a `liferay-portlet.xml` is missing
2. We no longer need to ship plugin-seeds with a `liferay-portlet.xml` in our osgi portlet examples.

**Comment by wezell** [comment]
PR: #16528

**Comment by bryanboza** [comment]
fixed, now we are able to deploy the portlet plugin without problems
