### ISSUE TITLE
Can't add form to file system containers

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16539]
## Step to reproduce
1. Create a page with " Large Column (lg-1)"
2. Edit the page
3. Add a form to that container
4. Nothing happen

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16537

**Comment by bryanboza** [comment]
We are not showing the changes after refreshing the page, we need to change the tab and bring back to see the form 
SC: https://screencast.com/t/0BilYwbw

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres //  FF. Now I'm unable to recreate the problem
