### ISSUE TITLE
[Oracle] : Invalid required permissions when creating DB

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16541]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/98169
Reproducible in latest master.

As per our official documentation: https://dotcms.com/docs/latest/database-configuration#Oracle when creating the user schema for running dotCMS with Oracle, a specific list of permissions must be assigned to it in order for the application to run correctly. However, some of them are either invalid or no-longer required.

It's important to determine whether these failing permissions are no longer valid/required, or if they're required by previous versions of Oracle. If that's the case, it should be noted in our doc.

### Steps to reproduce the behavior:
1. Install Oracle.
2. Go to the https://dotcms.com/docs/latest/database-configuration#Oracle documentation to create the user and its respective permissions.
3. Grant the permissions to the user, one by one.
4. The following permissions fail:
4.1 `MGMT_USER`
4.2 `OLAP_USER`

### Expected behavior
The list of required permissions must be precise.

### Desktop:
 - OS: Windows 7
- DB Oracle 11.2.0.2.0
 - Browser not relevant.
 - Version not relevant.

## Acceptance Criteria

1. Make sure dotCMS works as expected with Oracle.
2. Update DB configuration doc.

**Comment by john-thomas-dotcms** [comment]
We currently have no documentation on what the minimum needed permissions are for current versions of Oracle, but we know that the permissions for the `MGMT_USER` and `OLAP_USER` are failing.

So the doc has been updated to remove these failing permissions.  However no work has been done to determine whether all the remaining permissions are truly required or not.  The doc has left all the other permissions there in case they are; at least until ES, Support, or R&D can take the time to test what the minimum requirements are.

https://dotcms.com/docs/latest/database-configuration#database-permissions
