### ISSUE TITLE
Reindexing File Asset causes full reindex.

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16545]
### Describe the bug
In 5.1.1 if you choose to just reindex File Asset you get:     

Running Contents Index Cache
15:56:18.349  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: ‘File Asset’ not found in db
15:56:18.349  INFO  action.ViewCMSMaintenanceAction - Running Contentlet Reindex

and it builds a whole new index

For comparison, choosing just to reindex Blog logs this:  

13:32:00.967  INFO  action.ViewCMSMaintenanceAction - Running Contentlet Reindex on Structure: Blog
13:32:00.969  INFO  action.ViewCMSMaintenanceAction - processAction : Running Contentlet Reindex on structure : Blog
13:32:00.969  INFO  util.AdminLogger - class com.dotmarketing.portlets.cmsmaintenance.action.ViewCMSMaintenanceAction : processAction : Running Contentlet Reindex on structure : Blog

And a full new reindex is not triggered.

### Steps to reproduce the behavior:
1. Go to System -> Maintenance -> Index
2. Click on selector, choose File Asset
3. Hit reindex

**Comment by wezell** [comment]
Found while working on this - If you hit the "delete then reindex" button, the method `ContentletIndexAPI.removeContentFromIndexByStructureInode` does not work and the content is never removed from the index.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16546

**Comment by bryanboza** [comment]
Fixed, now we are able to reindex content types individually

**Comment by bryanboza** [comment]
Fixed, tested on the master branch and works as expected
