### ISSUE TITLE
Epic - Implement Block Editor Field 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16564]
As a content editor, I want the best editing experience I can have while still maintaining clean markup and a consistent look and feel.  Additionally, I want to be able to edit content and documents collaboratively and provide. ProseMirror is a block level editor that would allow for this type of control + experience. Implementing ProseMirror.js is an epic.  We will need 

### Step 3 Impl 
- Define how we want collaborative editing to work - how it should interact with our idea of Content locks and workflow.  
- a new field type called Block Editor `BlockField` created
- Create a websocket implementation to enable prosemirror's collaborative editing. 
- custom prosemirror plugin that can accept and upload images to dotCMS
- custom prosemirror plugin that will allow a editor to select a dotCMS widget to render in a block
- changes to our `ContentTool` to recognize an prosemirror js field and allow a user to select rendered output or the raw .json output.
- Change our content-to-map api to support prosemirror.js fields
- Change graphQL to support prosemirror.js fields
... much more to come

### ~~Step 1~~
- Learn more about prosemirror:
  - https://prosemirror.net
  - https://news.ycombinator.com/item?id=15465125
  - https://discuss.prosemirror.net/t/who-is-using-prosemirror/1230/14
  - https://news.ycombinator.com/item?id=18998042
  - https://juretriglav.si/open-source-collaborative-text-editors/

###  ~~Step 2~~
- Decide on the version of ProseMirror we want to implement. Take a look at the options and examples - sign up for some of the free services and try out the implementations to see what is possible.  We are definitely going to want at some point and need to plan for
  - HTML and Markdown support
  - DnD Image upload / browsing / reuse
  - Link browsing / selection
  - Track changes (content save)
  - Collaborative Editing
  - Contextual Comments (workflow comments?)

** ~~Examples / Options Include~~** 
  - Prosemirror Raw  - https://prosemirror.net/
  - TIP TAP - https://tiptap.dev/
  - Nib - looks pretty clean.  https://github.com/nib-edit/Nib
  - Atlassian's feature rich version  - https://atlaskit.atlassian.com/packages/editor/editor-core
  - A well developed Vue version - https://tiptap.scrumpy.io/
  - czi-prosemirror - A React version which is as close as I've seen to googledocs as anything on the web - https://github.com/chanzuckerberg/czi-prosemirror
  - PubPub - https://www.pubpub.org -  https://github.com/pubpub/pubpub-editor

**Comment by fmontes** [comment]
## Editors created with prosemirror
- https://appleple.github.io/smartblock/
- https://www.youtube.com/watch?v=Zi7sRMcJT-o
- https://tiptap.dev/
- https://demo.paperbits.io/

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/21988
