### ISSUE TITLE
Create dotAsset base type and content type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16565]
The dotAsset base type is a new base type.  dotAssets are distinguished from `fileAsset`s in that the only required field in a `dotAsset` is the `asset` and they are only addressable via their ids, e.g. `/dA/2342354235235`  They not tree-able and do not have urls - that is, you can just throw these into dotCMS and not worry about dupes or url collisions.  dotAssets can live on any host or on the system host and have five fields by default 

- Asset/asset -  BinaryField
- Site or Folder/siteFolder
- Metadata/metadata key value read/write(tika)
- Tags/tags tag field

The site/folder field is only there so that `dotAsset`s can be assigned permissions.  The tag field is there so `dotAsset`s can be assigned tags and searched by tags.  The metadata field is there to hold the searchable tika metadata for the binary asset.  
While these fields are added by default, a customer can choose to delete all of them except the `asset` field . 

The use case for `dotAsset`s is for a blob store for structured files and media.  Think how you can drag and drop an image onto this github task.  We need a structure to handle similar unstructured assets and interactions inside dotCMS. 

### Asset/asset
The `asset` field is just a regular binary field.  It will hold the dotAsset file.  It is required.

### Site or Folder
The Site or Folder field will be used to drive permissions.  It can be removed in which case the content will be stored on the host of the Content Type (like normal content)

### Tags
Allows `dotAsset`s to be tagged. This field can be deleted.

## Auto-Assign Type when a dotAsset is uploaded
Additionally, when a new dotAsset is uploaded into dotCMS, dotCMS will use the values in the  `asset.allowed` field variable to try to intelligently determine the dotAsset type which is being uploaded.  

The algo for this decision tree is
1. ***Exact/on Site*** We have an exact match on the mime or file extension on content types that live on the site that is being uploaded (if we know it) into and to which the user has permissions 
sorted alpha
2. ***Exact/SYSTEM_HOST*** Check if we have an exact match on the mime or file extension on content types that live on the SYSTEM_HOST that is being uploaded into and to which the user has permissions 
3. ***Partial Wildcard/on Site*** Check if we have a partial wildcard match on the mime on content types that live on the host that is being uploaded into and to which the user has permissions 
4. ***Partial Wildcard/SYSTEM_HOST*** Check if we have a partial wildcard match on the mime on content types that live on the SYSTEM_HOST and to which the user has permissions 
5. ***Total Wildcard (or null)/on Site*** Check if we have a wildcard match on the mime on content types that live on the host that is being uploaded into and to which the user has permissions 
6. ***Total Wildcard (or null)/SYSTEM_HOST*** Check if we have a wildcard match on the mime on content types that live on the SYSTEM_HOST and to which the user has permissions 

In all matching cases, if there is only 1 matching Content Type, we will use this one.  If there are more than one matches, we will use the first match based on the content type variable name sorted `alpha`

**Comment by hmoreras** [comment]
Core-web PR: https://github.com/dotCMS/core-web/pull/1272/

**Comment by bryanboza** [comment]
I think here by default we need to save the content and get the permissions from the site who is living the parent (content type). Right now we have the system host by default, and the pieces of content after you save is inheriting permissions from the default site.
SC: https://www.screencast.com/t/axr6yTwJm

**Comment by fmontes** [comment]
> I think here by default we need to save the content and get the permissions from the site who is living the parent (content type). Right now we have the system host by default, and the pieces of content after you save is inheriting permissions from the default site.
SC: https://www.screencast.com/t/axr6yTwJm
-- Same thing happen with any content type, if this is a bug, it requires a new issue

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/18057
