### ISSUE TITLE
Related content in container not showing in edit mode

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16563]
### Describe the bug
Related content doesn't display in edit mode when added, sometimes appears after a minute or two but not always.

### Steps to reproduce the behavior:
1. Create Content types: 
*ContentType A named : Links 
     This Content type only has the following fields : 
     - Label ( var name : label ) 
*ContentType B named : List Links 
     This Content type only has the following fields : 
     LinksList ( var name : linksList and its a Relationship type field of Many-to-Many to Links ) 

2. Create container 
     *Container using the ContentType B ( List Links ), with the following code : 
         #set($content = $dotcontent.find($ContentIdentifier)) 
         <ul class="list-links"> 
          #foreach($link in $content.linksList) 
         <li>$link.label</li> 
         #end 
        </ul>
3. Add 3 ContentType A, resulting in 3 links

4. Create 'advanced' template that parses the container

5. Add new page.

6. Add content to the container
     * Relate the content type-A items. 

7. Save

Container shows empty content. 

Waiting 30-90 seconds seems to make the list items appear if you switch to preview after waiting the allotted time. 

### Expected behavior
List items should appear.

### Video
https://drive.google.com/file/d/1dbneIETPFOfa3sqaV46ymJccOf0EsNnR/view?usp=sharing

### Desktop (please complete the following information):

 - Browser Chrome, Safari
 - Version 5.1.1 (replicated on demo)

**Comment by wezell** [comment]
When calling `$contentlet.relatedField` or `conAPI.getRelatedContent(id, )` we need to use the database to load the relationships and then cache them on the `contentlet` for future lookups. When the relationships get updated, then the contentlet that caches the relationships gets invalidated as well and the relationships get reloaded.  Using the DB will prevent lookups from failing b/c the index lags behind the contentlet db.

**Comment by nollymar** [comment]
PRs:
dotCMS/enterprise-2.x#667
#16603

**Comment by nollymar** [comment]
Now, relationships are loaded from database by default and saved on the contentlet cache for future requests. **This cache only works for relationship fields, so legacy relationships are never cached on contentlets**. 

In case you want pull relationships from index, `GET_RELATED_CONTENT_FROM_DB` can be set to `false`.

**Comment by wezell** [comment]
So if it is a legacy relationship, we should get the related content from lucene as we always have.  If it is a related field, we should get from db/cache unless `GET_RELATED_CONTENT_FROM_DB` = false

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/pull/16670

**Comment by erickgonzalez** [comment]
When calling the content from backend it stills getting it from DB or index (property set to false) instead of cache, if you do the call from REST API **ContentResource** or **ESContentResource** it gets the content from cache after the first time.

Talking with Nollymar, who it's working on this issue, we need to add the cache call at the pullRelated.

**Comment by nollymar** [comment]
Now, contentletAPI.getRelated methods internally invoke contentlet.getRelated that is responsible for caching relatedIds

PR: https://github.com/dotCMS/core/pull/16762

**Comment by nollymar** [comment]
**Note to QA: ** Please test all relationship tests cases (add/edit/sort/remove/push publish/import/export, convert legacy to field, etc), especially for self-related content.

**Comment by nollymar** [comment]
Performance results:

- Reindex took        : 14m 32.527s  (current master with relationships cache changes)
- Reindex took        : 16m 1.474s (dotCMS 5.1.5)

Tested locally with one node, default memory configuration and no existing cache

**Comment by erickgonzalez** [comment]
Tested test cases mentioned here https://github.com/dotcms/core/issues/16563#issuecomment-503789010 and working as it should.

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now I'm unable to reproduce the main problem

**Comment by wezell** [comment]
Note to John - because we are returning relationships out of the db now, there is no need for sleeps or waits in code when calling for a newly created contents' relationships
