### ISSUE TITLE
Google Translate throws up on large strings

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16588]
When using Google to translate content, we are using a GET with a ton of URL parameters.  There is an upper limit to the number of characters that Google Translate will accept via url and it is not hard to hit that with larger content objects.

We need to do a POST and pass a JSON object instead which will allow us to post large content blocks for translation.
The attached bundle shows the issue.  It has a blog entry that cannot be translated. You will need to delete the blog content type from the starter to import this.

[bdeadcba-d728-415c-a1df-d583f9aa9e7f.tar.gz](https://github.com/dotCMS/core/files/3188498/bdeadcba-d728-415c-a1df-d583f9aa9e7f.tar.gz)

**Comment by wezell** [comment]
Commit attached.

**Comment by erickgonzalez** [comment]
Tested with the attached bundle, now large strings can be translated using the service.

**Comment by bryanboza** [comment]
Tested as the last comment of @erickgonzalez and seems now it is working as expected
