### ISSUE TITLE
"All" content selection not working on custom content portlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16587]
Create a custom content portlet that has uses `blogs, news` as content types.

Try to use and search by "all" content types.  It does not work.

![custom-content-types](https://user-images.githubusercontent.com/934364/57871764-188c4d00-77d8-11e9-8898-f347ce4fc928.gif)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16610

**Comment by nollymar** [comment]
**Tests Results:** The issue persists

**Comment by erickgonzalez** [comment]
The issue is because the changes in the ES Analyzer, the `OR` clause is not working.
Ticket to follow up https://github.com/dotcms/core/issues/16141#issuecomment-498300407

**Comment by bryanboza** [comment]
Fixed, tested on the release branch // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
