### ISSUE TITLE
ContentletIndexAPI.removeContentFromIndexByStructureInode does not work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16592]
Found while working on #16545 - From the System > Maintenance > ReIndex screen, if you select a content type and hit the "delete then reindex" button, the method `ContentletIndexAPI.removeContentFromIndexByStructureInode` does not work and the content is never removed from the index.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16602

**Comment by erickgonzalez** [comment]
@john-thomas-dotcms on this commit https://github.com/dotCMS/core/commit/e28926d62f2ebc755a90eb6a4a64ba3ab5b5df18 a couple of methods has been marked as Deprecated

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/16602#issuecomment-496643869 According to that comment we need to add a Timeout on this issue.

**Comment by erickgonzalez** [comment]
PR 2 : https://github.com/dotCMS/core/pull/16640

**Comment by dsilvam** [comment]
Passed Internal QA: It does reindex the content of the selected Content Type, although there's no feedback to the user that this process was completed.

**Comment by dsilvam** [comment]
Passed Internal QA for master with the same observation in the comment above.

**Comment by bryanboza** [comment]
Fixed, tested on the release branch and now we are able to flush the caches sections individually

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
