### ISSUE TITLE
categories cannot be faceted in ES

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16599]
For tags, we use the keyword es mapping which allows us to perform aggregations on the tag field.  We do not offer the same capability with categories.  We need to change categories to use the keyword mapping and change how we put them to a `List<String>` so we can do aggregations on them.

Same for `personas`

**Comment by DeanGonzalez** [comment]
In this instance, I have this query:
```  
{
   "query": {
      "query_string": {
         "query": "+contenttype:document"
      }
   },
   "aggs" : {
      "topic" : {
         "terms" : {
            "field": "categories_dotraw",
            "size" : 20
         }
      }
   },
   "size":0   
}
```  

Which does not allow for aggregating by category, content that has multiple categories:
<img width="1398" alt="Screen Shot 2019-05-21 at 9 47 39 AM" src="https://user-images.githubusercontent.com/1569167/58110944-b784c080-7bad-11e9-87b5-382e6686fe8e.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16618

**Comment by nollymar** [comment]
**Tests results: OK**

Now, categories can be aggregated in a query as tags, so there is no need to use the prefix `_dotraw` anymore. For example:

```

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
