### ISSUE TITLE
Error when login and logout as limited user

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16591]
### Describe the bug
When you login and/or logout as a limited user you get an error in the console and can't logout.

### Steps to reproduce the behavior:
1. Login with: `chris@dotcms.com:chris`
2. Check the console for the error
3. Try to logout
4. Again, check the error.

### Expected behavior
It should login and logout as a limited user with no error.

### Screenshots
![Screen Shot 2019-05-16 at 7.38.16 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/db15d3da-6133-4c4c-8b63-cf4c575555de)

## Acceptance Criteria

1. Fix the error when login and logout as a limited user
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
This still happening when you login and logout twice 
SC: https://screencast.com/t/1hMuvnnqO

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes

**Comment by bryanboza** [comment]
Fixed, tested on release branch // postgres // FF
