### ISSUE TITLE
Containers as Files cache improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16597]
We need to improve the cache handling for the new containers as files, each time we are requesting one of those containers is being build and the build process for some parts always include to read some of the containers files (opening files).

## Example: 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java#L216

For the Push Publish process the integrity checker will look multiple times for the containers dependencies of multiple objects and even if it is the same container on each request we are building the whole container object instead of add it to cache and retrieve later from there.

### Expected behavior
When the container as files is created we cache it in the containers cache.

## Acceptance Criteria
* *Integration tests are required.*

**Comment by wezell** [comment]
Here is the difference getting the page as JSON cached and uncached
### Uncached
```
➜  ab -H 'Authorization: Bearer $TOK' -c10 -n 10000 "http://localhost:8080/api/v1/page/json/about-us/index?language_id=1"

Document Path:          /api/v1/page/json/about-us/index?language_id=1
Document Length:        34074 bytes

Concurrency Level:      10
Time taken for tests:   44.640 seconds
Complete requests:      5140
Failed requests:        0
Total transferred:      177643540 bytes
HTML transferred:       175140360 bytes
Requests per second:    115.14 [#/sec] (mean)
Time per request:       86.848 [ms] (mean)
Time per request:       8.685 [ms] (mean, across all concurrent requests)
Transfer rate:          3886.22 [Kbytes/sec] received
```
### Cached
```
➜ ab -H 'Authorization: Bearer $TOK' -c10 -n 10000 "http://localhost:8080/api/v1/page/json/about-us/index?language_id=1"

Document Path:          /api/v1/page/json/about-us/index?language_id=1
Document Length:        34117 bytes

Concurrency Level:      10
Time taken for tests:   18.090 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      346040000 bytes
HTML transferred:       341170000 bytes
Requests per second:    552.80 [#/sec] (mean)
Time per request:       18.090 [ms] (mean)
Time per request:       1.809 [ms] (mean, across all concurrent requests)
Transfer rate:          18680.62 [Kbytes/sec] received
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17556

**Comment by fabrizzio-dotCMS** [comment]
currently being tested.

**Comment by fabrizzio-dotCMS** [comment]
I tested this issue tracking every use of the vtls using 
`sudo fs_usage pid 6373 | grep vtl`
`container.vt`l is effectively cached and its read from disk just once. 
But the rest of the vtls located under `/application/containers/large-colum/` 
are constantly accessed and read after every hit. Those other files are not cached. 
I constantly get a listing like:
`17:19:17  stat64            erver1/assets/2/1/21b8e6f8-4fcc-4498-81a9-2902de9b17e6/fileAsset/products.vtl    0.000423   java
17:19:17  access            erver1/assets/2/1/21b8e6f8-4fcc-4498-81a9-2902de9b17e6/fileAsset/products.vtl    0.000539   java
17:19:17  stat64            erver1/assets/e/1/e195c885-cc6a-4496-b2e5-413178572122/fileAsset/document.vtl    0.000481   java
17:19:17  access            erver1/assets/e/1/e195c885-cc6a-4496-b2e5-413178572122/fileAsset/document.vtl    0.000286   java
17:19:17  stat64            rs/server1/assets/0/a/0a170280-33c9-456b-9269-d8f6d2767a73/fileAsset/news.vtl    0.000732   java
17:19:17  access            rs/server1/assets/0/a/0a170280-33c9-456b-9269-d8f6d2767a73/fileAsset/news.vtl    0.000220   java
17:19:17  stat64            s/server1/assets/9/b/9bea3dad-c348-4085-b7a6-35ae7986340c/fileAsset/media.vtl    0.000410   java
17:19:17  access            s/server1/assets/9/b/9bea3dad-c348-4085-b7a6-35ae7986340c/fileAsset/media.vtl    0.000227   java
17:19:17  stat64            erver1/assets/2/0/20568a20-8512-480e-80a3-92f43a4ea443/fileAsset/location.vtl    0.000481   java
17:19:17  access            erver1/assets/2/0/20568a20-8512-480e-80a3-92f43a4ea443/fileAsset/location.vtl    0.000314   java
17:19:17  stat64            rs/server1/assets/8/6/869a49c9-6a00-4ece-81b9-a19731746ebf/fileAsset/blog.vtl    0.000523   java
17:19:17  access            rs/server1/assets/8/6/869a49c9-6a00-4ece-81b9-a19731746ebf/fileAsset/blog.vtl    0.000390   java`

My recommendation is we address caching the other files in a separate issue.

**Comment by jgambarios** [comment]
New improvements will be handle in https://github.com/dotCMS/core/issues/17595
