### ISSUE TITLE
[REST] : Category field not validated when creating content via REST

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16595]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/98267
Reproducible in dotCMS 5.1.1, and latest master

When creating a Contentlet via REST having a required filed of type `Category`, dotCMS is **NOT** validating if such a value does belong to a Category or not.

### Steps to reproduce the behavior:
1. Go to the Content Types portlet and create a new type called "Test" with the following specifications:
1.1 `Text` field called "Title", required.
1.2 `Category` field called "Category", pointing to "Event Types", required.
2. Open up a Terminal and enter this cURL command. Notice that the value for the `Category` field does not exist:
```
curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -H "Content-Type:application/json" -d '{
   contentType:"test",
   languageId:1,
   title:"cURL Content 1",
   category: "nonexistingcategory"
}'
```
3. You get an HTTP 200 code and no errors in the log. The Contentlet is created even though the `Category` field is required and must exist.

### Expected behavior
The application should validate the value of the `Category` field before creating the Contentlet.

### Desktop:
 - OS: Not relevant.
 - Browser: Not relevant.
 - Version: Not relevant.

### Additional context
Both the dotCMS back-end and the REST Endpoint must behave the same way and perform the same validations.

## Acceptance Criteria

1. Unit test

**Comment by mattyarbrough** [comment]
This is currently affecting customers.
