### ISSUE TITLE
[core] : Adding more logging to Contentlet validation operations

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16594]
Found when working on Support ticket: https://dotcms.zendesk.com/agent/tickets/98267
Reproducible in dotCMS 5.1.1, latest master.

There are several validation operations executed upon checking in Contentlets that are not making it to the `catalina.out` file. This is making it difficult for the Support Engineers to troubleshoot problems reported by customers.

Adding the correct code to log failures and their root causes will help us solve the problem faster.

### Steps to reproduce the behavior:
1. Create a Content Type called "Test" with two fields:
1.1 **Title**, of type `text`, required.
1.2 **Relation**, of type `relationship`, **required**. The Content Type to associate can be anything. For example, `Location`.
2. As stated in our documentation: https://doc.dotcms.com/docs/5.1.1/latest/docs/latest/save-content-using-rest.html#examples-of-curl-commands-submitting-related-content-using-eithe create new content of type "Test", but DO NOT PASS DOWN the relation value in order to generate a validation error.
3. The error messages in the log file are not clear enough to quickly locate the conflicting Contentlet.

### Expected behavior
The log needs to provide useful information for quick troubleshooting.

### Desktop:
 - OS: Not relevant.
 - Browser Not relevant.
 - Version Not relevant.

## Acceptance Criteria

1. Test using both back-end, the CURL command, and the REST Contentlet endpoint.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/16596/files

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
