### ISSUE TITLE
Update relationship dependencies in an efficient way

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16604]
Be smart when indexing parents/children

**Comment by nollymar** [comment]
PRs:
dotCMS/enterprise-2.x#667
#16603

**Comment by nollymar** [comment]
Now, when any related content  is modified from the parent, children are not reindexed, only the parent. However, if any related content is modified from a child, all parent dependencies are reindexed to reflect those changes

**Comment by wezell** [comment]
So, I'd like to try to only reindex the delta between the existing parent relationships and the new parent relationships.  We only need to reindex ids who have either been added or deleted.

**Comment by nollymar** [comment]
Done as part of this PR: #16603

**Comment by nollymar** [comment]
**Note to QA:**  Please test adding/deleting related content and verify in the log the amount of reindexed contentlets for each operation, considering that:
- if a child contentlet is added/removed/reorder, only the parent contentlet is reindexed
- if a parent or parents contentlet(s) is(are) added/removed, only the parent or parents contentlet(s) modified is (are) reindexed
- children are never reindexed

**Comment by erickgonzalez** [comment]
Working as it should.

When you add, remove or reorder a child contentlet on the parent edit screen, only the parent is reindexed.
`INFO  reindex.ReindexThread - ReindexEntries found : 1`

When you remove or add a parent on the child edit screen, the parent is indexed as well.
`INFO  reindex.ReindexThread - ReindexEntries found : 2`

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgress // FF
