### ISSUE TITLE
Reflected XSS Issue

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#16605]
Reflected XSS issue reported - details for dotCMS engineers here:  https://docs.google.com/document/d/1z3Ds1qEA9niL2qgm5VhdG_9s1KK3hS1X0iRh_g5knMw/edit#

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/16644 -> Release 5.1.6
https://github.com/dotCMS/core/pull/16650 -> Master

**Comment by bryanboza** [comment]
After those changes we are unable to access the admin with `/c`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16654

**Comment by bryanboza** [comment]
Fixed, tested in the release branch and now the `/c` works as expected and also we are blocking the provided URLs

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
