### ISSUE TITLE
JS error listing content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16613]
### Describe the bug
We are unable to show the list of content types when you click on this portlet 

### Steps to reproduce the behavior:
1. Login as admin
2. Go to content types portlet
3. Check your JS console in the browser 

### Expected behavior
We need be able to see the content types list without problems 

### Screenshots
https://www.screencast.com/t/RoQ5AqesRwiX

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
The endpoint change one of it properties, we use that property to set an icon.

<img width="1144" alt="Screen Shot 2019-05-23 at 9 36 43 AM" src="https://user-images.githubusercontent.com/751424/58266269-943d4b00-7d3e-11e9-9cf9-5b9f45f160f9.png">

**Comment by freddyucv** [comment]
I go back after this commit

https://github.com/dotCMS/core/commit/68a3c9169f21015f18cfc43f7bf1acefcf87946c#diff-6b39836219f30dbd2abe144f04df4fb2

and the end point work just like before, I think maybe the new jersey version translate different the enum object into json.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16620

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
