### ISSUE TITLE
Unable to flush caches individually 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16626]
### Describe the bug
We are unable to flush caches by content type individually after you select some content type and hit the flush cache, we are flushing all the caches 

### Steps to reproduce the behavior:
1. Login 
2. Go to system --> maintenance 
3. Select any block of caches in the drop down 
4. Hit the flush caches button 
5. Check your log file and make sure we are flushing just this cache 

### Expected behavior
We need be able to flush the cache blocks individually 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16648

**Comment by dsilvam** [comment]
Passed Internal QA release 5.1.6: Flushing only the selected region plus `parentpermissionablecache` and `permissioncache`. Worth saying that the three regions are being logged a few times with the message:
Building Cache : languagecacheimpl
Building Cache : permissioncache
Building Cache : parentpermissionablecache

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to cache every one individually

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
