### ISSUE TITLE
Don't close any dialog when click outside the dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16639]
As a stakeholder, I want dialogs not show when user clicks outside them.

### Is your feature request related to a problem? Please describe
We just want to make sure users don't close the dialog per accident.

### Describe the solution you'd like
Users should only close the dialog on: X in the right corner, cancel button and esc key (and of course on "save" or any other action that conclude the task for what the dialog was opened)

### Technical Approach
We have to dialogs `dot-dialog` and primeng dialog, both have a property to prevent close when click outside.

## Acceptance Criteria
1. Go over all the dialogs in the angular app and prevent to close it when click outside
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master branch // Postgres // FF & chrome

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
