### ISSUE TITLE
dot-dialog closing when try to select any input text

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16638]
### Describe the bug
If you try to highlight (select) a text in an <input> that is showing inside an opened dialog and the end of your "click" is outside the dialog, the dialog closes.

### Steps to reproduce the behavior:
1. Edit a content type or field
2. Select the text in any field but make sure when you release the click the cursor is outside the dialog
3. The dialog close

![Screen Recording 2019-05-29 at 2.01.34 PM.gif](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/565c24c7-e928-4cc9-8f5c-ae6f5ceb5f50)

### Expected behavior
The dialog should not close.

### Desktop (please complete the following information):
 - Browser **ONLY HAPPEN IN CHROME**
 - Version master

## Acceptance Criteria

1. Prevent the dialog to close when not have to.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on release branch, postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // ff
