### ISSUE TITLE
Hitting cancel on the workflow task detail screen should close modal

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16646]
If you click on a workflow task to view the details, then hit cancel on the workflow task detail screen, it does not close the modal- it opens the task list in the modal.  When you close the modal, you still see the task list again, under it.

![hitting-cancel](https://user-images.githubusercontent.com/934364/58662647-b6176e80-82f8-11e9-8b99-39c65ae621bd.gif)

**Comment by bryanboza** [comment]
fixed, tested on master // Postgres // FF. now the cancel close the window
