### ISSUE TITLE
Content Search: Filtering content using relationship fields is not working

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#16653]
When the search is from child to parent, an empty list is displayed. However, the filter works correctly from parent to child

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16663

**Comment by erickgonzalez** [comment]
Working as it should now, you can search from parent or from the child using the identifier or typing the title of a content related.

**Comment by bryanboza** [comment]
Fixed, tested on master // Posgres // FF
