### ISSUE TITLE
Update "Show Query" properly when searching by a relationship

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16669]
In the content search screen you can search by relationships.  We need to make sure that when "show query" is selected, we give the user the correct API calls to search by relationship rather than the raw lucene.

**Comment by nollymar** [comment]
Now, it's possible to pull content with relationship criteria sending the `related` param, specifying relationships as a comma-separated list. For example: 
```
http://localhost:8080/api/content/render/false/type/xml
/query/+contentType:Youtube%20+languageId:1%20+deleted:false%20+working:true
/orderby/modDate%20desc
/related/Youtube.news:2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6,Youtube.products:70902a06-6e59-46b7-ac7f-2c98c96f9b64
```

This feature was implemented here: 
https://github.com/dotCMS/enterprise-2.x/pull/668/files
https://github.com/dotCMS/core/pull/16736

**Comment by erickgonzalez** [comment]
Tested Working as it should, the Lucene query when you filter by a parent does not show but if you filter by a child it shows. 
The REST API Call working without issues.
Pagination and Total Results showing right on the UI.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
Documented (and rewrote the doc): https://dotcms.com/docs/latest/content-api
