### ISSUE TITLE
Allow JWT signing algorithm to be overridden

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16667]
dotCMS uses signed JWT tokens for remember me and API call and we verify any signed request incoming.  We allow users to override and create a custom SecretKeyFactory for their own signing mechanisms but we have `SignatureAlgorithm.HS256` hardcoded when signing a JWT.

**Comment by jdotcms** [comment]
I swore where were giving the user the ability to do it.
It seems here should be the change
```
private String signToken(final JwtBuilder jwtBuilder) {
            //The JWT signature algorithm we will be using to sign the token
            jwtBuilder.signWith(SignatureAlgorithm.HS256, this.getSigningKey());
            
            return jwtBuilder.compact();
        }
```

**Comment by wezell** [comment]
PR: #16683
