### ISSUE TITLE
Multi language portlet problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16666]
### Describe the bug
We need be able to display all the portlets in the supported languages

<img width="1680" alt="ital" src="https://user-images.githubusercontent.com/2641437/58830908-a2c21700-8608-11e9-9799-68949c50aba0.png">

**Comment by bryanboza** [comment]
The same case with the content search in French 
<img width="1680" alt="FR" src="https://user-images.githubusercontent.com/2641437/58831037-f2a0de00-8608-11e9-9723-b31464e547ee.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16682

**Comment by bryanboza** [comment]
We have more problems:

- The Dashboard (Legacy) this in French 
SC: https://screencast.com/t/G5r0bbJA

- Virtual Links in Spanish 
SC: https://screencast.com/t/qAk6h8Ni

- Task portlet in Chinese
SC: https://screencast.com/t/qAk6h8Ni

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16865

**Comment by bryanboza** [comment]
Fixed, tested every case on master and now this works as expected
