### ISSUE TITLE
Relationship field list of related content overlapping with workflow actions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16685]
Steps to reproduce:
1. Import attached "movies-studios-ratings-bundle.tar.gz" bundle
2. Add a relationship field to the `Studio` type pointing back to `Movie` type
3. Go to Content Search and edit "Walt Disney Pictures" studio

Result will be: https://www.screencast.com/t/raBDPWfx

Movies bundle: 
[movies-studios-ratings-bundle.tar.gz](https://github.com/dotCMS/core/files/3259231/movies-studios-ratings-bundle.tar.gz)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16773

**Comment by dsilvam** [comment]
Passed Internal QA: List showing without overlapping

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
