### ISSUE TITLE
Vanity URL Forward to URL Map Pattern results in 404

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#16684]
### Describe the bug
When creating a Vanity URL that is supposed to forward to a URL Mapped Content Type, results in a 404. No exceptions are being thrown. This problem is also reproducible on the demo site.

Note: This does work in dotCMS 4. 

### Steps to reproduce the behavior:

1. Create a Vanity Url on the demo site with the following information:

- Site: All Sites
- Url: /testurl/([a-zA-Z0-9\-\_]+)
- Action: 200 - Forward
- Forward To: /products/$1
- Save and Publish

2. In private/incognito browser, navigate to: https://demo.dotcms.com/testurl/consumer-discretionary or a matching urlTitle of another contentlet from "Products".

### Expected behavior

Browser is forwarded (transparently) to `/products/consumer-discretionary` with `/testurl/consumer-discretionary` in the address bar.

### Actual behavior

dotCMS 5 Demo Site: Browser gets a 404 page.

dotCMS 4 Demo Site: Browser is forwarded as intended.

### Screenshots

dotCMS 5 demo site: 
![image](https://user-images.githubusercontent.com/9543257/58990738-a4304280-87b4-11e9-98b0-24ea8f9faf0e.png)

dotCMS 4 demo site: 
![image](https://user-images.githubusercontent.com/9543257/58990761-b14d3180-87b4-11e9-9151-f4a2900f0983.png)

### Desktop (please complete the following information):
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version:  74.0.3729.169

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17768

**Comment by yasindilekci** [comment]
Hi @wezell,

We are having a similar issue for a large customer. This is impacting the platform and the end-users.

Could we please get a hotfix for this issue?

Thank you

**Comment by wezell** [comment]
@yasindilekci - I would open a support ticket requesting a hotfix for the issue.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17859

**Comment by wezell** [comment]
@freddyucv @dsilvam this fix is still hitting elasticsearch every request: 


```
ab -c 10 -n 10000 http://localhost:8080/about-us/index
```

![Screen Shot 2020-01-22 at 8 02 58 PM](https://user-images.githubusercontent.com/934364/72948117-37bd8000-3d52-11ea-9bb3-4a326273a473.png)

**Comment by dsilvam** [comment]
@wezell Putting this comment on the proper ticket, following @freddyucv suggestion. New comment under https://github.com/dotCMS/core/issues/17612#issuecomment-577735179. Also putting the _Needs Work_ to that issue instead.

**Comment by bryanboza** [comment]
These changes are breaking the edit mode, we need some work here

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17926

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17933

**Comment by freddyucv** [comment]
Note fo QA:
Algo go to the /services/first-time-investors page, and check that the left side menu is right (it should look exactly as it look in demo site )

**Comment by nollymar** [comment]
**Passed Internal QA:** 
Results: OK.
The original issue has been solved and additional the one that broke Edit Mode

**Comment by dsilvam** [comment]
Merged into 5.2.5 @bryanboza

**Comment by bryanboza** [comment]
Ok, after the last changes we still having problems with the edit mode 
Now if you open an existing page and click into the edit tab, we are redirecting to the edit of the home page, but if you create a new page, we still having the URL pop-up with the error. 

SC: https://www.screencast.com/t/gv83oCt1o

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.5 // Postgres // FF
