### ISSUE TITLE
Relating new content not working / new relationship field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16681]
If you try to relate a new piece of content, via relationship field, it's creating the new content but not relating it.

This works good on 5.1.5 

http://recordit.co/QAPmK4YsBX

**Comment by bryanboza** [comment]
Unable to reproduce on release-5.1.6 branch

**Comment by erickgonzalez** [comment]
Not able to reproduce in latest master

![2019-06-25_11-35-21 (1)](https://user-images.githubusercontent.com/5278970/60120270-ae9f8580-973d-11e9-8991-69063253b6ae.gif)

**Comment by bryanboza** [comment]
I'm able to reproduce in the last master code, but using new content types, here the SC: https://screencast.com/t/tqaUUBH3zlmU

## To Recreate
1- Create a new content type **Genres** (_Genre: text_)
2- Create another content type **Movie** (_Name: text, Movie-Genre: Relationship field_ )
3- Add a new piece of content to Genres and Save&Publish
4- Finally add a new piece of content to Movie and relate to the new Genre
5- Now edit this piece of content and select _relate to a new content_ option 
6- Add the requiered fields and save&publish 
7- Make sure the new piece of content is related

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16800

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF 

Tested with new content types, and now it works as expected
