### ISSUE TITLE
File based zero content containers

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16688]
### Describe the bug
Zero content containers do not use pre/post loop, so creating file based zero content containers results in no content.

Related ticket: https://dotcms.zendesk.com/agent/tickets/98409
 - Version 5.1.5

### Additional context
If the container has 0 contents in it, we need to look for and parse the `./container_code.vtl` file if it exists. Additionally, if the container has 0 contents in it, we need to make sure NOT to parse the pre and post loop vtls

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16689

**Comment by bryanboza** [comment]
We still showing the pre-loop and post-loop when the container has 0 contents

**Comment by bryanboza** [comment]
Fixed, now after setting the max contents field to 0, we skip the _pre-loop_ and _post loop_. 

New enhancement here: #16782
