### ISSUE TITLE
Create a CleanUpStaleMultitree Method/Job

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16697]
A method should be created in the MultitreeAPI  that checks for multitree entries that have personalization and do not have a corresponding persona and delete those multitree entries.
This method should be called by a `StatefulJob` in Quartz that gets fired conditionally whenever a Persona's KeyTag is edited or a Persona is deleted.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16748

**Comment by bryanboza** [comment]
We are having cache problems after you edit the keytag of any persona, we still having the personalization but the pages shows like a blank page, to return the content we need to flush the cache. 
SC: https://www.screencast.com/t/Gn2so4x1

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17341

**Comment by bryanboza** [comment]
Fixed, tested in the last master and I'm unable to reproduce the reported error
