### ISSUE TITLE
Create dot-binary-file component

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16698]
As a developer, I want a custom element so I can render a DotCMS Binary File Field.

### Selector
```html
<dot-binary-file></dot-binary-file>
```

### Common Attributes
| Name                 | Type                                                     |
| -------------------- | -------------------------------------------------------- |
| label                | string                                                   |
| hint                 | string                                                   |
| required             | boolean                                                  |
| required-message     | string and *fallback to: "The field {name} is required"* |
| disabled             | boolean                                                  |
| value                | string of html                                           |

### Extra Attributes

| Name              | Type                                                                                    |
| ----------------- | --------------------------------------------------------------------------------------- |
| accept            | One or more unique [file type specifiers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers) describing file types to allow                  |
| multiple          | A Boolean which, if present, indicates that the user may choose more than one file      |

### Validation
1. Required: 
    - Use `required-message`

#### Status clases
| Class         | If                                                |
| ------------- | ------------------------------------------------- |
| dot-valid     | the input field is valid without errors.          |
| dot-invalid   | the input does not pass validations.              |
| dot-pristine  | a user has not interacted with the control yet.   |
| dot-dirty     | the value of form field has been changed.         |
| dot-touched   | a user tabbed out from the input control.         |
| dot-untouched | a user has not tabbed out from the input control. |

### Mock
<img width="380" alt="Screen Shot 2019-06-17 at 9 43 43 AM" src="https://user-images.githubusercontent.com/751424/59618034-a95e8d00-90e4-11e9-8d16-f3ba94503cb1.png">

### Possible Markup
```html
<dot-label>
    {label}
    <input type="text">
    <input type="file">
</dot-label>
<span>{hint}</span>
<span>{error}</span>
```

### Events
* valueChange: emit when the user change the valueChanges
* statusChange: emit when field change his status, valid, invalid, pristine, etc...

### Error handling
1. Show an error when the file, paste, browse or dropped is not the type passed

## Acceptance Criteria
1. Support drag and drop file
2. Support paste a file in the input text
3. Support paste a url in the input text
4. Habdle errors
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

## Will notes:

1. It should allow a file to be selected and uploaded
2. It should accept DnD file uploads
3. It should take an url, download the file and updload it to the backend
3. It should be configurable as to the acceptable mime types and max file size via field variables, e.g. we need to have variables like `config:accept-mime-types` and `config:max-file-size`
4. When a user selects a valid file, the field should automatically begin uploading the file.  
5. When a user submits the form entry and the files have not uploaded already, we will need to show a message saying we are processing the files.  When the files complete uploading the form will submit automatically without the user having to resubmit. 
6. Once a form has been submitted, we will validate.  If invalid, we will return messages but the user will not have to reupload the files/assets.

**Comment by fmontes** [comment]
Since we don't have the backend ready yet, we need to

1. Click in browse, select a file and emit it
2. Drop a file and emit the file
3. Paste an url, download and emit the file
