### ISSUE TITLE
Create TempResource for Multipart uploads

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16699]
As a user, I want to upload my files into dotcms as easily as possible and to begin uploading files into dotCMS as soon as they have been selected. I also want to be able to send dotCMS a url as a String and have dotCMS go and fetch it for inclusion in a contentlet's binary fields.  In addition, if the uploaded file is an image, the user will need to be able to preview it.

To do this, we need to create an `/api/v1/temp` "tempResource" that can accept a multipart upload and store the files under a temp path that is only accessible to the user who uploaded the asset.  This tempResource should be publically available, though this should be configurable via a property `TEMP_RESOURCE_ALLOW_ANONYMOUS`.  When a file is uploaded, the resource should respond with a unique id that can be used to access the resource.  

The tempResource should also have a method that takes a url and downloads that url (serverside) for use as a temp resource.  When this is done,, the resource should respond with a unique id that can be used to access the resource.  

### ~~Storing the TempResource~~
The files should be stored under the java temp folder, under a folder named `tmp_` + shorty UUID then under the fieldVar, e.g.
```bash
$JAVA_TEMP_FOLDER/temp_4c2e6eb57e7f/fileName
```
The temp UUID is assigned by dotCMS at initial upload time and returned to the client in the response, which is then responsible to reference it future forward.  For security purposes, a temp resource should only be valid for a set amount of time, configurable by a property:`TEMP_RESOURCE_MAX_AGE_SECONDS` which should default to an hour.

### ~~Previewing the uploaded resource~~
If the uploaded TempResource is an image, we will need to show a thumbnail when the file completes the upload.  This means that we will need to have the image filter pathing accept the tmp_{UUID} and reroute to the tmp file path.  This includes the `/dA` and the `/imageServlet` pathing.

### ~~Security: Only the uploading user can preview a TempResource~~
In order to see/retrieve the uploaded tmp file, the user must either be logged in and have a valid session and the session must have a tempResource Set<String> of uploaded tmp files, e.g. `{"tmp_4c2e6eb5-7e7f-42ff-8576-8d5107d21097"}`.  If the user's session contains an attribute tempResource and the tempResource Set contains the file id the user is looking to preview, then the user can see it.  Otherwise, they get a 401.  The user does not need to be logged in.

### ~~Incorporating into the content checkin method~~
When a client checks in an asset and has used the TempResource to upload the binaries, the client can include the temp resource id for the value of the binary field they are trying to include.  If the TempResource exists, then the API can use it to populate the binary field as specified.  For example, using the ContentResource to put a Blog with an image that has been uploaded as a TempResource, you could  put something like:

```json
{
"title":"My blog entry",
"blogImage": "temp_4c2e6eb57e7f4",
"body":"Lorem ipsum...."
}
```
which would, in the checkin method, add the file of the tempResource with id `temp_4c2e6eb57e7f4` as the `blogImage` field for the new or existing content object.

### ~~Cleanup~~
We will need a scheduled cronjob that deletes all TempResource and containing folders with File times older than a configurable time (I would say 1 day).  We already have a tmp cleanup cron in the `BinaryCleanupJob` that should be modified to do this work.

**Comment by wezell** [comment]
```html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
	var pasteTarget = document.getElementById("pasteTarget");
	pasteTarget.addEventListener("paste", handlePaste);
});
function handlePaste(e) {
    for (var i = 0 ; i < e.clipboardData.items.length ; i++) {
        var item = e.clipboardData.items[i];
        console.log("Item type: " + item.type);
        if (item.type.indexOf("image") != -1) {
            uploadFile(item.getAsFile());
        } else {
            console.log(item);
            alert("Discarding non-image paste data");
        }
    }
}
function uploadFile(file) {
    var xhr = new XMLHttpRequest();
    xhr.upload.onprogress = function(e) {
        var percentComplete = (e.loaded / e.total) * 100;
        console.log("Uploaded: " + percentComplete + "%");
    };
    xhr.onload = function() {
        if (xhr.status == 200) {
            var json = JSON.parse(xhr.responseText);
            if(json.image){
               document.getElementById("myPic").src=json.thumbnailUrl;
            }
            document.getElementById("responseRaw").innerHTML=xhr.responseText;
       } else {
            alert("Error! Upload failed");
        }
    };
    xhr.onerror = function() {
        alert("Error! Upload failed. Can not connect to server.");
    };
    var formData = new FormData();
    formData.append("file", file);
    xhr.open("POST", "/api/v1/temp/upload", true);
    xhr.send(formData);
}

function doSubmit(){
    var xhr = new XMLHttpRequest();

    xhr.onload = function() {
        if (xhr.status == 200) {
            var json = JSON.parse(xhr.responseText);
            if(json.image){
                 document.getElementById("myPic").src=json.thumbnailUrl;
            }
            document.getElementById("responseRaw").innerHTML=xhr.responseText;
        } else {
            alert("Error! Upload failed");
        }
    };
    xhr.onerror = function() {
        alert("Error! Upload failed. Can not connect to server.");
    };
    var data = {};
    data.remoteUrl =  document.getElementById("remoteUrl").value;
    data.fileName = document.getElementById("fileName").value;
    //data.urlTimeout=15;
    console.log(data);
    
    xhr.open("POST", "/api/v1/temp/byUrl");
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.send(JSON.stringify(data));
}
</script>
</head>
<body>
<h2>Cut and Paste is just a file upload</h2>
<div style="width: 200px; height: 200px; background: grey" id="pasteTarget">
Click and paste here.
</div>
<h2>Or by URL</h2>
<hr>
url: <input type="text" id="remoteUrl"><br>
filename:<input type="text" id="fileName"><br>
<input type="button" value="submit" onclick="doSubmit()">
</form>
<div>
<img style="width:250px;height:250px;border:1px solid silver;padding10px;" id="myPic" >
</div>
<code id="responseRaw"></code>
</body>
</html>
```

**Comment by wezell** [comment]
PR: #16764

**Comment by wezell** [comment]
We need a parameter that can be set that will completely disable the tempResource

**Comment by john-thomas-dotcms** [comment]
Need to doc in:

**Comment by erickgonzalez** [comment]
Info for Doc and QA:

**TEMP_RESOURCE_MAX_AGE_SECONDS** property TTL of the files, default to 30m (1800 s).
**TEMP_RESOURCE_ALLOW_ANONYMOUS** property that allows anon users to upload temp files, default value true. If the property is set to false and an anon user tries to upload a file it gets a 401 UNAUTHORIZED.
**TEMP_RESOURCE_ENABLED** property that disables or enables the temp resource, default value true. If the property is set to false and someone tries to use the resource it gets a 403 FORBIDDEN.

Examples of Rest API calls (Tested on Postman):

**To Upload Multi Files**
`http://localhost:8080/api/v1/temp`
On the Body, you need to select form-data and as the Key set `file` and as the value select the file (this for each file you want to upload).
On the Headers, you need to add the Origin Header (localhost).

**To Download a File by Url**
`http://localhost:8080/api/v1/temp/byUrl`
On the Body, set a JSON like this:
```
{
	"fileName":"250px-Bocas2.jpg",
	"remoteUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Bocas2.jpg/250px-Bocas2.jpg"
}
```
On the Headers, you need to add the Origin Header (localhost).

Note: If the Origin Header is not set the user gets a 400 BAD REQUEST.

**To Create a Content with the temp file**
Use any of the create content rest api, e.g:
`http://localhost:8080/api/content/publish/1`
With this JSON, On the fileAsset set the id of a temp file:
{"contentType":"fileAsset","hostFolder":"demo.dotcms.com:/images","fileName":"ttestName","fileAsset":"temp_c29bf330f0","title":"ttestTitle"}

Cleanup of the temp files:
These properties already existed
**BINARY_CLEANUP_JOB_CRON_EXPRESSION** Cron expression that instructs when to fire (this expression cannot be changed with the server up).
**BINARY_CLEANUP_FILE_LIFE_HOURS** Files older than this property are going to be deleted (this property can be changed with the server up).

**Comment by wezell** [comment]
We need to change the response for TEMP_RESOURCE_ENABLED=false.  It should return a 404 and not a 403

**Comment by erickgonzalez** [comment]
PR for 404 when disabled https://github.com/dotCMS/core/pull/16886

**Comment by dsilvam** [comment]
Passed Internal QA: Able to create temp resources by either `url` or `multipart` methods, and then check in fileasset content out of the temp resource. 

TEMP_RESOURCE_ALLOW_ANONYMOUS properly working.
TEMP_RESOURCE_ENABLED property working.

**Comment by wezell** [comment]
Bryan, this needs an end to end test - can you get the info from Fox on how they were trying to use it across domains and it wasn't working and retest that case?

**Comment by bryanboza** [comment]
After some testing we need to improve some responses: 
- If you don't send the authentication params we are returning a 500 error, the same thing if you send any user different to the one that upload the temp file 
ST: https://gist.github.com/bryanboza/54a979c9410e8f123ce9f764f187e2db

- We need a security log that register the tempFile id and the id of the user that upload the file
_right now we just log the login of the user_ 

- We have a 500 error in case you don't send one of the required parameters, the same thing if you send one of those in null

**Comment by john-thomas-dotcms** [comment]
For internal documentation/history:

After some discussion of the potential to merge the config properties here in with the newly created `CONTENT_APIS_ALLOW_ANONYMOUS` property, we concluded that we should keep the `TEMP_RESOURCE_ALLOW_ANONYMOUS` as a separate property.

The main use case where this is important is where customers have (or want to have) front-end forms that allow non-authenticated users to submit content, but want to prevent anonymous users from being able to upload files.With our existing file upload mechanism, anonymous users can be prevented from uploading files by simply denying permissions for anonymous users to write to any Content Types which have binary fields (including, but not limited to, the File Asset Content Type).  But with the TempResource, anonymous users could potentially upload files even if they only had write permission to Content Types without Binary fields.

**Comment by john-thomas-dotcms** [comment]
One more comment for documentation/history:

The main privacy concern for file uploads is the exposure of metadata.  After review, we concluded that the TempResource does not pose any privacy risk, since:

1. Files uploaded via the TempResource are not exposed on the front-end.
2. Files uploaded via the TempResource can not be accessed without the file key returned to the application that uploaded the file (so the metadata can not be exposed to another application).
3. We already have a mechanism to strip metadata which could contain private or personally identifying information.
    * Since this mechanism is employed when the files are displayed/returned (rather than when they are uploaded), it will still be applied equally to all files whether they are uploaded using the TempResource or the existing file upload mechanisms.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17123

**Comment by dsilvam** [comment]
Needs work: responses are 500 for a few cases:

*Missing params
*Using wrong user to submit content with temp resource file
*Invalid param values

**Comment by dsilvam** [comment]
Sending fix here: https://github.com/dotCMS/core/pull/17295

**Comment by erickgonzalez** [comment]
Return 400 if file size is greater than max file size. PR https://github.com/dotCMS/core/pull/17344

**Comment by erickgonzalez** [comment]
Tested against the endpoint `http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH` since the `http://localhost:8080/api/content/publish/1` is deprecated and working as it should.

**Comment by bryanboza** [comment]
Fixed, tested with the ` http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH` endpoint and now we are handling exceptions.
