### ISSUE TITLE
Doc: Update and Review all Screen Shots to 5.x UI

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16706]
1. All screen shots need to be updated to the latest release (5.0 minimum).
2. All updated screen shots need to be reviewed by @john-thomas-dotcms or @DeanGonzalez.

**Comment by john-thomas-dotcms** [comment]
All images updated to date have been published on prod.

Need to go through all docs now to mark the ones that still have old images that need to be updated.  Doc content type already has a place to mark these, need to create a new tool to make it easy to review the images and mark the docs with older images.

**Comment by wezell** [comment]
Also - please, animated gifs where applicable.
