### ISSUE TITLE
Field unique feature is not working

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#16728]
### Describe the bug
Right now, I'm able to create diff contents in the same language with the same value on a field that is marked as unique.

### Steps to reproduce the behavior:
1. Create a Content type and add a Text Field and check the unique.
2. Create content and save it.
3. Create new content with the same value as above and save it.
4. An error should pop-up showing that content with that value already exists.

This is because with these changes https://github.com/dotCMS/core/commit/c7af2d8a77702e1cd8caf08136477d89abe874d0#diff-0d54bf61089532e67d512211809b7a69R1798 is not getting any results.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotcms/core/issues/16728

**Comment by dsilvam** [comment]
Passed Internal QA: Now uniqueValues are properly respected, when creating content in the same language. A warning is displayed saying `The field <fieldName> must have a unique value.`

**Comment by bryanboza** [comment]
We need some work here, the unique fields should be case insensitive, right now we are case sensitive, then we are able to add duplicated values (_test // Test_)

**Comment by wezell** [comment]
@erickgonzalez please test and resolve #16904

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16920

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
