### ISSUE TITLE
Add rules to edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16737]
As a user, I want to create/edit rules for the page in order to be able to modify rules of a page.

### Describe the solution you'd like
We need to add a button to the right toolbar of the edit page and load the rule module, the same way we do with layout.

### Mock
<img width="394" alt="Screen Shot 2019-06-17 at 11 11 29 AM" src="https://user-images.githubusercontent.com/751424/59623158-b6817900-90f0-11e9-9369-d14d7952cf1a.png">

### Technical Approach
1. Url: `/#/edit-page/rules?id=123-456-789-0`

### Additional context
We need the page id to pass it to the rules module

## Acceptance Criteria
1. Add rules to edit page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
when you create a rule to a specific page and then you refresh the page, the rule created dissapears, but it is shown in the *Rules general section/module*

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
