### ISSUE TITLE
Internationalization (i18n) dot-form and fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16734]
As a user, I want to translate the content of my forms in order to present them in multilanguage sites.

### Is your feature request related to a problem? Please describe
When user creates fields in a form they can enter a label, hint, etc... but there is no way to translate those to be used in multilanguage sites.

### Describe the solution you'd like
We need to be able to use `Language Variable` contentles to translate the items of the field in a form.

### Technical Approach
When the user create a `Language Variable` he needs to map the key of the contentlet to the `form > field > item` he wants to translate, ex:

1. If we have a form named: "Contact Us" it form variable will be: "ContactUs".
2. If this form has a field named: "Last Name" the field variable will be: "lastName"
3. If the user wants to translate the "name" of the field.

It needs to create a `Language Variable` content with the key: `ContactUs.lastName.name` that is mapping of: `FormVariableName.FieldVariableName.ItemToTranstale`

### Additional context
All this work will be done in the backend.

## Acceptance Criteria
1. `/api/v1/contenttype/id/${contentTypeId}` endpoint should receive `language_id` and return the form fields translated
2. Form in edit page should get back translated when `render` page is asked with `language_id`
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16892

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
