### ISSUE TITLE
Add edit page button in page property dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16747]
As a user, I want edit a page content and layout from property in order to have more control over the page

### Describe the solution you'd like
We need to add a link that will redirect to the edit page.

<img width="1701" alt="Screen Shot 2019-06-18 at 10 21 52 AM" src="https://user-images.githubusercontent.com/751424/59702531-2b1deb80-91b5-11e9-96f5-ed44890d5663.png">

### Technical Approach
To prevent losing the angular state routing, we need to emit an event and listen for it in the angular app and do the redirect to the edit page.

## Acceptance Criteria
1. Add a button to link to the edit page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
After test those changes, if you don't have permissions to edit the page, we still showing this button, but it is not doing anything, we need to wrap it in a permissions check and it should say "View in Edit Mode". 

SC: https://screencast.com/t/wBBi54AG8n

**Comment by bryanboza** [comment]
- Problems with multi language pages:

_We are losing the language of the page when you try to edit, If you click in the page properties of any page in a specific language, when you go to the edit page we need keep this language and redirect to the edit mode of the page in the same language. 
SC: https://www.screencast.com/t/8btPQYmf_

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by wezell** [comment]
PR: #16909
