### ISSUE TITLE
/api/v1/personas does not work on master

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#16744]
This is working on demo:
https://demo.dotcms.com/api/v1/personas

but on master this one does not
http://localhost:8080/api/v1/personas

the issue seems to be on the query:

 +live:true  +conFolder:SYSTEM_FOLDER +conHost:(48190c8c-42c4-46af-8d1a-0cd5db894797 SYSTEM_HOST) +structureType:6

Now I have modified to 
 +live:true  +conFolder:SYSTEM_FOLDER +conHost:(48190c8c-42c4-46af-8d1a-0cd5db894797 OR SYSTEM_HOST) +structureType:6

Including an OR between the conHost values and worked

**Comment by wezell** [comment]
This case needs to be doc'ed and be part of the change log - there are 3 ways to fix it, to add quotes around the terms, to add the `OR` or to add the field inside the parenthesis, e.g. `+(conHost:abd conHost:def)`

**Comment by wezell** [comment]
Find cases in our code where this is happening.

**Comment by wezell** [comment]
fixed in #16748

**Comment by john-thomas-dotcms** [comment]
Documented: https://auth5.dotcms.com/docs/latest/content-search-syntax#OperatorDefault

Also doc'ed in changelogs (though they're not finished yet).
