### ISSUE TITLE
Support Encoding/Decoding of WebP images.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16740]
In order to deliver the fastest web experience possible, we need to be able to support serving images using the webp format.

For more information, see:
https://developers.google.com/speed/webp

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16741

**Comment by erickgonzalez** [comment]
To Test:
Normal Image Filter
`http://localhost:8080/contentAsset/image/1432d672-a564-41c1-9ff9-b7e51e646b84/fileAsset/`

Call to WebPImageFilter: the **q** is the quality needs to be a value between 0 - 100, if you call this filter you can see that the MIMEType is set to **image/webp**
`http://localhost:8080/contentAsset/image/1432d672-a564-41c1-9ff9-b7e51e646b84/fileAsset/filter/WebP/webp_q/1`

**Comment by bryanboza** [comment]
Tested in the last master and we have some problems here: 

- In case you send an invalid ID, we need to catch the exception and show just one line of error in the log file, right now we are showing the complete NPE in the log. 

- The filter is not working on microsoft Edge
![edge1](https://user-images.githubusercontent.com/2641437/60897144-cb9b8480-a224-11e9-959b-8c74df1352ad.png)

**Comment by wezell** [comment]
@bryanboza is you VM out of date? Please insure that you are testing on the latest version of Microsoft Edge.

**Comment by wezell** [comment]
Windows requires Microsoft Edge build 17763+ to work with webp

**Comment by bryanboza** [comment]
After the tests in a Windows, seems the servlet is not working at all.

- When you are running under a Windows instance and you try to use the `webp` filter we get this error 
SC: https://gist.github.com/bryanboza/82151c99ab55403584fa7dfbd8901c4e

_I've the mime property in the `web.xml` file_ 
![mime1](https://user-images.githubusercontent.com/2641437/60909798-65baf700-a23c-11e9-8639-5298bbb46b09.png)

**Comment by erickgonzalez** [comment]
Please test run it on Windows and Linux.

**Comment by dsilvam** [comment]
Tests results:

| OS         | Result                |
|------------|-----------------------|
| MacOS      | Passed                    |
| Ubuntu     | Passed (Tested by @erick) |
| Windows 10 |                       |
| Docker |                       |

**Comment by wezell** [comment]
We also should test a RedHat distro - e.g. CentOS or Amazon Linux

**Comment by wezell** [comment]
Running master in Docker:
```
docker build --pull --no-cache --build-arg BUILD_FROM=COMMIT --build-arg BUILD_ID=origin/master -t test .

docker run -it -p 8080:8080 test
```

**Comment by bryanboza** [comment]
Fixed, tested in every platform and now this filter works as expected...

**Comment by wezell** [comment]
In docker - if you edit an image, select to compress it as webp and then hit "save", it segfaults the docker image:
```
dotcms_1  | 18:14:45.613  WARN  impl.SessionImpl - finalizing unclosed session with closed connection

dotcms_1  | 18:14:49.970  INFO  caffine.CaffineCache - ***	 Building Cache : relationshipcachebyinode, size:1000,Concurrency:32
dotcms_1  | 18:14:53.168  INFO  allocation.DiskThresholdMonitor - low disk watermark [85%] exceeded on [ckLMO3WwSni11ZVTqDcIig][4cdc0c1f-2f63-4cfd-aa45-1c1fbaf4ba91][/data/local/esdata/nodes/0] free: 13.5gb[13.5%], replicas will not be assigned to this node
dotcms_1  | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
dotcms_1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
dotcms_1  | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
dotcms_1  | #
dotcms_1  | # A fatal error has been detected by the Java Runtime Environment:
dotcms_1  | #
dotcms_1  | #  SIGSEGV (0xb) at pc=0x000000000000b8a6, pid=588, tid=0x00007f32bd15bb10
dotcms_1  | #
dotcms_1  | # JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
dotcms_1  | # Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
dotcms_1  | # Derivative: IcedTea 3.12.0
dotcms_1  | # Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
dotcms_1  | # Problematic frame:
dotcms_1  | # C  0x000000000000b8a6
dotcms_1  | #
dotcms_1  | # Core dump written. Default location: /srv/home/core or core.588
dotcms_1  | #
dotcms_1  | # An error report file with more information is saved as:
dotcms_1  | # /srv/home/hs_err_pid588.log
dotcms_1  | #
dotcms_1  | # If you would like to submit a bug report, please include
dotcms_1  | # instructions on how to reproduce the bug and visit:
dotcms_1  | #   https://icedtea.classpath.org/bugzilla
```

**Comment by wezell** [comment]
It might be the hardlink that is used to copy the file to the asset directory in the `BinaryExporterServlet` line ~ 387

**Comment by wezell** [comment]
Notes to Documentation:
- We support webp using both `/dA/` links and  `/contentAsset/image/` links
- Our webp support also includes the quality parameter `webp_q` 
- not all browsers support webp yet, for example safari does not as of this writing.
- We will need to update the image editor doc as its UI has changed (animated gif!)

**Comment by erickgonzalez** [comment]
PR: for issue with docker https://github.com/dotCMS/core/pull/17116

**Comment by erickgonzalez** [comment]
Note to QA: please test in Win, Ubuntu, docker. Upload an image and compress it to webp, also to apply the filter and the image should be rendered.

**Comment by erickgonzalez** [comment]
Uploaded an image and compressed to webp filter, saved without issues and can see it on FE. Tested on MacOS, Ubuntu, Docker (Alpine Linux), Windows and worked without issues.

**Comment by bryanboza** [comment]
Tested by @erickgonzalez in multiple platforms.
