### ISSUE TITLE
Angular portlets are not being refresh on site change

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16754]
### Describe the bug
If you are in an angular portlet (rules or content types) and you change the site (using the dropdown in the header) the portlet is not refreshed (it does refresh in legacy iframe portlets).

### Steps to reproduce the behavior:
1. Go to Rules or content types
2. Select another site in the header dropdown
3. See the portlet didn't refresh
4. If you refresh the browser you'll see the values for the selected site

### Expected behavior
It should refresh the portlet and update the data to match the selected site, like in the iframe portlets.

### Additional context
In previous versions of Angular Router there was no way to do this but looks like that with `RouteReuseStrategy` in Angular 7 we could, something like [this](https://stackoverflow.com/a/48380444/3367318) maybe?

## Acceptance Criteria

1. Reload the angular portlet when site change
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
Angular now provides a functionality to handle navigation request under the same URL, under the property `onSameUrlNavigation`, https://angular.io/api/router/Router#onSameUrlNavigation. This execute the  guards and resolvers of the routes, if is specified in each route, under the property `runGuardsAndResolvers `, https://angular.io/api/router/RunGuardsAndResolvers.  

The most natural way to archive this will be to implement resolvers the routes that we currently have in Angular. After a meeting, Content Types and Rules are the only two portlets  that might need this change. Looks like Content Types share data cross sites, so Rules will be the only one. 

Draft PR: https://github.com/dotCMS/core-web/pull/1092

**Comment by fmontes** [comment]
We need to create an issue to make rules use resolver.

**Comment by wezell** [comment]
Also, templates portlet

**Comment by alfredo-dotcms** [comment]
unable to reproduce locally
https://monosnap.com/file/ad1mOELkOMMBVKH6JItsg78qvh1vzd

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF. Now we refresh in any selection on the site selector
