### ISSUE TITLE
Use ES copy_to feature to replace the catchall field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16750]
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/copy-to.html

To be clear, we need to maintain the `catchall` field in our elasticsearch index.  We are just looking to replace how it is populated.  Currently, we do this in code and it seems like elasticsearch should be able to do this for us more reliably with `copy_to`

We will need to make sure that the catchall works as it does currently - and we need to make sure uuids are searchable.

**Comment by wezell** [comment]
@nollymar let's talk about this one first

**Comment by nollymar** [comment]
`copy_to` feature creates a field in the inverted index and does not modify the `_source` field, which might become a problem for us in case we need to troubleshoot. So, I recommend to keep our current implementation.

These links explain how it works with more detail:
https://stackoverflow.com/questions/30433189/copy-to-and-custom-analyzer-not-working
https://discuss.elastic.co/t/copy-to-not-working/23211/7
