### ISSUE TITLE
Table listing header should not wrap in content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16755]
### Steps to reproduce the behavior:
1. Login in german language
2. Go to content type
3. Check the heading of the last column of the table listing, the arrow wrap

### Expected behavior
It should not wrap.

### Screenshots
<img width="653" alt="Screen Shot 2019-06-19 at 12 35 52 PM" src="https://user-images.githubusercontent.com/751424/59791377-2d547880-928f-11e9-949e-cbac7394fc50.png">

## Acceptance Criteria

1. Make heading listing not wrap 
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
