### ISSUE TITLE
dot-alert-confirm on enter not calling accept

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16769]
### Describe the bug
As a user, I want to hit enter to accept confirmation in the dialog to make actions faster.

### Steps to reproduce the behavior:
1. Go to content types
2. Edit one
3. Click the icon to remove a field
4. Wait for the confirmation dialog and hit enter
5. See that the dialog close but the field was not removed.

### Expected behavior
It should close the dialog but also remove the field (meaning the "accept" action should trigger)

### Additional context
This is a problem with the `dot-alert-confirm` and not only for content types, please everywhere where the component is used

## Acceptance Criteria

1. Enter should trigger accept action
2. When dialog open the `button` should be `focus`
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
