### ISSUE TITLE
Update dot-persona-selector

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16766]
As a stakeholder, I want the dot-persona-selector update so we can use it in the personalization feature.

### Mock
<img width="501" alt="Screen Shot 2019-07-16 at 7 55 55 AM" src="https://user-images.githubusercontent.com/751424/61300554-6ead4a80-a79f-11e9-82f6-e5e12e7176ca.png">

Zeplin: https://zpl.io/a3R3QL8

-------

![Dropdown](https://user-images.githubusercontent.com/751424/61299850-1de92200-a79e-11e9-9ecb-9110e83b6eb2.png)

Zeplin: https://zpl.io/ag6e1kQ

### Describe the solution you'd like
We need a new selector that includes filter and pagination.

Now, the new endpoint returns a list of personas and each has `personalized: boolean` that indicates that the persona selected have a personalized version of the current page. We'll use that to mark the persona option.

#### New endpoint
To get the personas list, now we have to use the url: `/api/v1/page/${pageId}/personas` but the response is a little different, we need to update `DotPersona` interface because there are new properties.

The new endpoints return the `pageId` not sure if we need to add this to the `DotPersona` interface, I think we don't.

#### Internal component we can use
We already have a [dropdown component](https://github.com/dotCMS/core-web/tree/master/src/app/view/components/_common/searchable-dropdown) that support **filter** and **pagination** BUT it doesn't support passing template for items and/or selected item.

The component is really old an the code needs some love, but the idea is to make the component takes templates for the options and the selected item, there is an issue for the component we'll use as a template for the options and, if possible, the selected item: https://github.com/dotcms/core/issues/16756

#### Events
We need to catch and reemit the event from the **delete personalization** event form the [option](https://github.com/dotcms/core/issues/16756).

Also the `searchable-dropdown` emit events that we might need to use internally and also reemit, use accordingly.

## Acceptance Criteria
1. Update the `dot-persona-selector` component
2. Match the mock
3. Make sure it keeps working as it is right now in the edit mode
4. Rename, relocate or move files to match our current architecture if necessary.
5. Work in all the supported browsers (don't forget IE11 and iPad)
6. Multilanguage
7. Unit test

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16925
