### ISSUE TITLE
Doc: Update SiteSearch to use ES stemming

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#16761]
The SiteSearch for our doc site (and for our whole site) is currently using a very limited stemming algorithm, implemented in Velocity, to improve search results.  This code should be replaced once we implement or fix the SiteSearch indexing to use stemming.

This card can't be implemented until a future release, but is here as a reminder until then.

**Comment by wezell** [comment]
This is not correct, we use stemming for our site search, though more stemming features could be added.  See this comment:

https://github.com/dotCMS/core/issues/16746#issuecomment-503566895

I don't think there is anything to doc here.

**Comment by john-thomas-dotcms** [comment]
I believe that the final answer on this was that we use stemming for most of the index, but not for keywords (and there was a good reason for that, though I don't remember what it was now).

In any case, we implemented a "poor man's stemming algorithm" within the doc code for keywords, which allows us to get the improved search results we need there.  So there's nothing more we need to do with this one.
