### ISSUE TITLE
When you DnD a field (reorder) in the same column it shows up the edit field dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16772]
### Describe the bug
When you're editing a content type and you DnD a field inside the same column for reorder it triggers the click like your intention is to edit the field.

### Steps to reproduce the behavior:
1. Go to Content Type
2. Edit any content
3. DnD a field inside the same column (like reordering fields)
4. See how the dialog to edit the field shows up **(only happen in FF)**

### Expected behavior
It should not open, it should only do the reorganizing

### Additional context
1. If you remove [this](https://github.com/dotCMS/core-web/blob/adff3fbfc8a589eace3c187d0c58f005607859a7/src/app/portlets/content-types/fields/content-type-field-dragabble-item/content-type-field-dragabble-item.component.ts#L65) `@HostListener` it stops happening, but we can't remove it because we need the whole `<div>` to be clickable.
2. Maybe something with dragula's version?

## Acceptance Criteria

1. Make sure edit and DnD works as expected.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by fmontes** [comment]
Is failing, when you add a new field and then try to edit the form doesn't open, you have to reload the page to make it open, looks like the flag of not opening the dialog is staying dirty.
