### ISSUE TITLE
Content Search doesn't work if logged in to the backend in Spanish

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#16771]
If you login into the backend with your language set to Spanish the content search screen throws the following JS error:
doSearch is not defined

### Steps to reproduce the behavior:
1. Go to the login screen and change your language to Spanish
2. Go to the content search screen
3. no results and a JavaScript error in the console

### Additional context
Tested and works as expected in other languages.

### Desktop (please complete the following information):
 - OS: Mac

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
fixed here: #16666
