### ISSUE TITLE
Benchmark external elasticsearch performance

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16780]

**Comment by dsilvam** [comment]
Client's DB with around 130K contentlet. 
Master
Reindex took        : 8m 46.694s

5.1.5
Reindex took        : 8m 56.154s

**Comment by dsilvam** [comment]
Master
```
ab -c 15 -n 100000 http://localhost:8080/about-us
Requests per second:    312.64 [#/sec] (mean)
Time per request:       47.979 [ms] (mean)
Time per request:       3.199 [ms] (mean, across all concurrent requests)

**Comment by wezell** [comment]
Ah, crap, I think this was a bad test.  The lack of the trailing slash on the ab command means that you were not testing hitting a page, you were testing getting a 301 redirect for a folder:

The command to test is this:
`ab -c 15 -n 100000 http://localhost:8080/about-us/index`
