### ISSUE TITLE
Problems in the container properties when you edit the max contents field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16782]
### Describe the bug
We have rendering problems when you change the value of the max contents, in the edit container window.  

### Steps to reproduce the behavior:
1. Login as admin
2. Go to containers portlet 
3. Edit any 
4. Set the value of the max contents to 0
5. Make sure you are able to see the code field 
6. Now set the same value to any number > 0 
7. Make sure you are able to see the same fields without problems  

### Expected behavior
We need to render both scenarios without problems 

### Screenshots
SC: https://screencast.com/t/acI975zbKE

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17463

**Comment by erickgonzalez** [comment]
With still have 2 issues here:
1) If you set `Max Contents = 0` the `Code` field is not shown.
2) If you set `Max Contents > 0` the `Code` field is shown and should not be shown.

**Comment by nollymar** [comment]
**Note to QA:** 
The right behavior should be: 
- When `Max Contents = 0`: Hide Pre-Loop, Content Types and Post-Loop fields and show Code field
- When `Max Contents > 0`: Show Pre-Loop, Content Types and Post-Loop fields and hide Code field

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/17489

**Comment by bryanboza** [comment]
We need some work here: 

- After the last changes, now we are we fix the blank spaces, but if you change the `max contents` variable > 0 and then try to disable the toggle editor in the pre loop or post loop fields, we are completely removing the field, and this property should just enable/disable the ace editor. 
SC: https://www.screencast.com/t/AgHPZZYSO3e

**Comment by nollymar** [comment]
Fixed issue with the Toggle Editor check. PR: https://github.com/dotCMS/core/pull/17523

**Comment by dsilvam** [comment]
Passed Internal QA Release: working as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. New improvement of this reported on #17542

**Comment by dsilvam** [comment]
Passed Internal QA: working ok

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
