### ISSUE TITLE
Edit field variables is creating a new one

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16794]
### Describe the bug
We have a problem when you try to edit any field variable and save the changes, this because we are not editing the variable, we are just creating a new one with the new values and leave the old one without modifications.

### Steps to reproduce the behavior:
1. Login as admin
2. Go to content types and create a new one
3. Add a WYSIWYG field and add a new field variable 
4. Now edit this field and edit the name of the variable and save it 
5. Close the edit window and try to edit again 
6. Make sure the variable was edited 

### Expected behavior
1. We need to be able to edit variables value without problems 
2. Only edit the value not the key

### Screenshots
SC: https://screencast.com/t/DjuhVETR

### Desktop (please complete the following information):
Tested on master // Postgres // FF 

## Acceptance Criteria

1. Click in the pencil should focus in the textfield of the value
2. Click in the `key` should do nothing
3. Prevent duplicated variable with the same key, validate this in the FE
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by bryanboza** [comment]
Also, 
- The edit button is not working. If you click on that one, this is not doing anything. In this case, this button should edit the variable, and move the focus to the value of the variable in order to edit.

**Comment by john-thomas-dotcms** [comment]
So there's a few cases here, all of which are inter-related:

1. If you edit the field variable name, it creates a new field variable with the new name, but doesn't delete the old one.
2. If you click the edit (pencil icon) button, it doesn't do anything.
    * You can instead click in the field var name or field var value, and that will allow you to edit them.
    * So either the pencil button should move the cursor into one of those fields, or the button should be removed.
3. If you enter a new field variable with the same name as the old one it allows it, and replaces the value of the old one.
    * It allows this even when the new field var name is exactly the same as the old one (including the same capitalization).
        * It should either not allow duplicates, or prompt you to confirm that you want to wipe out the previous value.
    * In addition, when it does this, capitalization is ignored for purposes of treating them the same.
        * For example, if you already have a field variable named `tinymceprops` and you create a new one with the name `TinyMCEProps`, the value of the new `TinyMCEProps` replaces the value of the old `tinymceprops`.
4. If you create a new field variable with the same name as an old one (regardless of capitalization), and then try to delete one of them _before_ closing the field properties popup, you get an error "This URL does not exist."  So for example:
    1. Create a WYSIWYG field and save it.
    2. Open the WYSIWYG field properties.
    3. Create a new field variable `tinymceprops` and click the "Save" button to the right of it.
    4. Close the field properties popup.
    5. Open the WYSIWYG field field properties again.
    6. Create a new field variable `TinyMCEProps` and click the "Save" button to the right of it.
    7. Click the delete button (garbage can icon) to the right of the `tinymceprops` field variable.
5. It seems like the case of field variable names should be ignored.
    * So it might make sense to convert any field variable name entered into lower-case before saving it.
    * e.g. if you type in `TinyMCEProps` we might want to automatically convert that to `tinymceprops` to avoid issues.  (And in the case of this specific field variable, the code will only recognize the all-lowercase version of the field var name, so it's an example of why forcing lowercase on save might be a good idea).

**Comment by fmontes** [comment]
![Screen-Recording-2019-09-23-at-10 11 28-AM](https://user-images.githubusercontent.com/751424/65444174-bcbc7b00-ddec-11e9-9581-252777b47d83.gif)

1. It should not jump the height
2. When you click outside and lose focus, it should get out of "Edit mode" with means hide the buttons too.

![Screen-Recording-2019-09-23-at-10 02 40-AM](https://user-images.githubusercontent.com/751424/65444226-d52c9580-ddec-11e9-8c21-136d64cb1ca7.gif)
1. The key should not change on click we should disable the click completely.

**Comment by bryanboza** [comment]
We have another problem here, if you have a field variable and add a new one with the same name, we show both at this moment, but if you close the window and open again we have just one and we are overriding the value with the last one 
SC: https://screencast.com/t/UA3mxl5O48LP

We need to prevent this at FE level

**Comment by bryanboza** [comment]
We still with some problems here: 
- Ato some point we are allowing to edit the key of the variable and we are not validating the duplicated ones, and we allow to save 
SC: https://screencast.com/t/YJim2rao3

**Comment by bryanboza** [comment]
When you already have a variable and you try to add one with the same name we lock the save button, but if you try to edit the existing one, we lock both and you can't save changes 
SC: https://screencast.com/t/jFZS2EAFmYi5

**Comment by wezell** [comment]
this is ok, you just need to hit cancel on one of the dupes.

**Comment by bryanboza** [comment]
Fixed, tested on mater // Postgres // FF
