### ISSUE TITLE
Login in two tabs breaks the app in the second

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16790]
### Describe the bug
When you login in a second tab in the same browser it breaks the second tab, we're not catching the errors.

### Steps to reproduce the behavior:
1. Open two tabs of dotcms in login page
2. Login in one and then login in the second
3. You get errors in the some endpoints that we're not catching

### Expected behavior
It should just go to the dashboard (first porlet) with no issues.

### Screenshots
<img width="1189" alt="Screen Shot 2019-06-26 at 3 08 54 PM" src="https://user-images.githubusercontent.com/751424/60215214-60b17d00-9824-11e9-8173-cbff27de6a59.png">

### Additional context
If you are login in 2 tabs and logout in one the other logout as well... you can try to login back in each and get the error too

## Acceptance Criteria
1. App should login and not crash
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by freddyucv** [comment]
according to @jdotcms  this is the expected behavior with this change 

https://github.com/dotCMS/core/blame/master/dotCMS/src/main/java/com/dotcms/cms/login/PreventSessionFixationUtil.java
