### ISSUE TITLE
Long filename issue in WYSIWYG editor

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#16799]
When you add a link in the WYSIWYG editor to a file with a 'long' filename then the filename is cut off and ends with "...", making the link return a 404. I reproduced this on the demo website.

### Steps to reproduce the behavior:
1. Create/find a non-empty file with a very long filename (longer than 25 characters) on your PC 
2. Upload it to dotCMS
3. Edit some content with a WYSIWYG field
4. Add a link to the given file
5. Check the generated URL, it now ends with ...

![image](https://user-images.githubusercontent.com/2195163/60415250-ef364d80-9bda-11e9-994e-9c9da60b6a6e.png)

In my case I had the file with filename:
`a file with a very very very very very very very very very very very very very very very long name.txt`
It resulted in:
`<a href="/about-us/a file with a very very ver..." title="title">/about-us/a file with a very very ver...</a>`

### Expected behavior
It should not cut off the URL. Optionally it should use a link based on the ID

**Comment by ryan-ethode** [comment]
I can confirm that this bug still exists.

**Comment by Xander-Steinmann** [comment]
I don't see this behavior on the demo site any more... Has this been fixed in a particular dotCMS version? Our cloud dotCMS still has this issue.

**Comment by wezell** [comment]
This was fixed here: #17309
