### ISSUE TITLE
Create Interface RestClientProvider and DotRestClientProvider which implements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16807]
DotRestClientProvider should have a single method called RestClientProvider.getRestClient() that returns the rest client.  By default, the `RestClientProvider` should provide the `DotRestClient` which will support BasicAuth, JWT and TLS and can be configured by the following config properties:

```
ES_AUTH_TYPE = BASIC | JWT | TLS
ES_AUTH_BASIC_USER
ES_AUTH_BASIC_PASSWORD
ES_AUTH_JWT_TOKEN
ES_AUTH_TLS_CLIENT_CERT
ES_AUTH_TLS_SERVER_CERT
ES_REST_CLIENT_PROVIDER_CLASS
```

A customer can write their own RestClientProvider and deliver their own custom configured RestClient that can do things like load balance

This will allow customers to inject their own configured RestClient to connect to various Elasticsearch sources

### Defaults
dotCMS will default to the following:
```
ES_AUTH_TYPE = BASIC
ES_AUTH_BASIC_USER=admin
ES_AUTH_BASIC_PASSWORD=admin
ES_REST_CLIENT_PROVIDER_CLASS=DotRestClientProvider.class
ES_AUTH_TLS_CLIENT_CERT=/assets/certs/es-client-cert.pem
ES_AUTH_TLS_SERVER_CERT=/assets/certs/es-server-cert.pem
```

### Using JWT
```
ES_AUTH_TYPE =JWT
ES_AUTH_JWT_TOKEN=asdasdsaf32r23fewfsadgsdfgdfgsdfgsdf..=
```

**Comment by nollymar** [comment]
Changes implemented here: 
https://github.com/dotCMS/core/pull/16727/commits/c6d1a29c9c91d52aca8d82a34bb88f28ad3b36e6
https://github.com/dotCMS/enterprise-2.x/pull/669/commits/e23c0770f37c8b5520516cdb3f87af4968e20f25

**Comment by nollymar** [comment]
**To be considered for documentation:**

By default a high level rest client is provided (com.dotcms.content.elasticsearch.util.DotRestHighLevelClient), which supports two authentication types: BASIC and JWT. Besides, TLS certificates will be used for rest api and transport encryption. A custom high level rest client implementation can be provided setting this property `ES_REST_CLIENT_PROVIDER_CLASS` (fully qualified name of the class).

The DotRestHighLevelClient uses these properties to configure open distro: 

`ES_AUTH_TYPE:` Authentication type. Possible values: **BASIC | JWT**.
When `ES_AUTH_TYPE=BASIC`, credentials must be set through these properties  `ES_AUTH_BASIC_USER` and `ES_AUTH_BASIC_PASSWORD`
When `ES_AUTH_TYPE=JWT`, a valid token (`ES_AUTH_JWT_TOKEN` property) must be set

`ES_TLS_ENABLED:` Enable TLS encryption
`ES_AUTH_TLS_CLIENT_CERT: ` Path (relative to assets folder) where the client certificate is stored
`ES_AUTH_TLS_CLIENT_KEY: ` Path (relative to assets folder) where the private key is stored
`ES_AUTH_TLS_SERVER_CERT: `  Path (relative to assets folder) where the authority certificate is stored

**Comment by dsilvam** [comment]
Passed Internal QA:
Test results [Here](https://docs.google.com/spreadsheets/d/1670wAt-ZOd_Al1YWvHlUOS9JP1JpZenTM9D30iVUVWo/edit#gid=0).

**Comment by dsilvam** [comment]
Custom Rest Client Provider for QA 
[custom-rest-client-provider.zip](https://github.com/dotCMS/core/files/3423389/custom-rest-client-provider.zip)

**Comment by wezell** [comment]
see comment here:

https://github.com/dotCMS/core/commit/caf9a97cd0a52740f54263e704375a43d51f0635#diff-5f546c3c7452af409e686fd9d3050b18R12

**Comment by dsilvam** [comment]
**Passed Internal QA**:  test cases here https://docs.google.com/spreadsheets/d/1670wAt-ZOd_Al1YWvHlUOS9JP1JpZenTM9D30iVUVWo/edit#gid=0. 

OSGI plugin used for Custom REST Client here:
[com.dotcms.elasticsearch.provider.zip](https://github.com/dotCMS/core/files/4258242/com.dotcms.elasticsearch.provider.zip)
