### ISSUE TITLE
We are opening the edit window then you try to reorder fields in content types portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16801]
### Describe the bug
When you are in the content type portlet and you try to reorder some field using the drag and drop, we are opening the edit field window, then is difficult to change the order of the fields 

### Steps to reproduce the behavior:
1. Login as admin
2. Go to content type
3. Open anyone to edit or create a new one 
4. Try to reorder the fields using the drag and drop

### Expected behavior
We need to be able to reorder just moving the fields without problems 

### Screenshots
SC: https://screencast.com/t/ZC1tIlGEsGC

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryanboza please retest

**Comment by bryanboza** [comment]
Unable to reproduce on master
