### ISSUE TITLE
[Roles] : The RoleAPI.findAllAssignableRoles() method is not returning a valid FQN value

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16816]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/98656
Reproducible in dotCMS 5.1.5, and latest master.

The `RoleAPI` class has a method called `findAllAssignableRoles(boolean showSystemRoles)`, which returns all of the assignable Roles in dotCMS, including User Roles. However, when calling the `getFQN()` on every `Role` object returned by such a method, its value is null.

However, when calling a method such as `RoleAPI.findRoleByName("Publisher / Legal", null)`, the FQN value is returned as expected.

### Steps to reproduce the behavior:
1. Create a JSP file that calls `APILocator.getRoleAPI().findAllAssignableRoles(true)` and print the information from every `Role` object.
2. Call the JSP from an Incognito Window, and check that the value returned by `role.getFQN()` is ALWAYS null.

### Expected behavior
Calling the `role.getFQN()` method should not return null.

### Screenshots
<img width="1021" alt="Screen Shot 2019-07-08 at 12 42 47 PM" src="https://user-images.githubusercontent.com/8779585/60834578-30e86a80-a17e-11e9-9ed4-b05e4d6cd1ad.png">

### Desktop:
 - OS: Not relevant.
 - Browser Not relevant.
 - Version Not relevant.

## Acceptance Criteria

1. Create JSP or custom code to see the values returned from calling `findAllAssignableRoles(boolean showSystemRoles)`
2. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/16818

**Comment by bryanboza** [comment]
Fixed, tested with the follow JSP file and now we are able to get all the roles and we are not returning null. 

```
<%@page import="com.dotmarketing.business.APILocator"%>
<%@page import="com.dotmarketing.business.Role"%>
<%@page import="java.util.List" %>
<% 

List <Role> roles = APILocator.getRoleAPI().findAllAssignableRoles(true);

for (Role role : roles){ %>
<h5><br>*<%=role.getFQN()%>	</h5>
<%}%>
```

Tested on master // Postgres // FF
