### ISSUE TITLE
Full reindex keeps showing misleading "in progress" even after all remaining records are already failed

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#16813]
### Describe the bug
When a reindex has failed records once it's reached the point that the only records left to index will continue to fail it still shows the reindex as 'in progress'

### Expected behavior
Once only failed records remain the status should change from 'in progress' to something like 'completed with failures'.

**Comment by wezell** [comment]
This was fixed in 5.1.6

**Comment by mattyarbrough** [comment]
This is still affecting customers in 5.1.6

**Comment by jcastro-dotcms** [comment]
This issue is still reproducible in the latest version.

**Comment by wezell** [comment]
Let's try again @mattyarbrough  - I think this is fixed in 5.3.3!

**Comment by wezell** [comment]
What will happen now is that the index will finish but it will show that there are records that failed.
