### ISSUE TITLE
Add column field to content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16821]
As a users, I want break columns in order to create content types rows and columns easily.

### Is your feature request related to a problem? Please describe
Users can modified the columns in a row after created and this is bad for UX.

### Describe the solution you'd like
We should be able to break colums into more columns.

### Idea
![cols.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/6d9c78bf-d65f-4624-ad9e-ab1e78c38b39)

### Additional context
If a user drop a column inside another, we break it in two, three and four. We separate the fields in each depending where the column is dropped within the fields. Check the screenshot.

Icon name: `view_column`

## Acceptance Criteria
1. Make a dropable column field to break columns
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
