### ISSUE TITLE
Error after execute bulk actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16824]
Related to #16666 

### Describe the bug
We have an error in the response after you execute any bulk action. We are showing an `unable to show available actions` message and also we have an error in the console. 
 
### Steps to reproduce the behavior:
1. Login as admin
2. Go to content search 
3. Select some piece of content and execute a bulk action

### Expected behavior
We need be able to execute those actions without problems 

### Screenshots
<img width="1920" alt="bulk1" src="https://user-images.githubusercontent.com/2641437/60989671-cd884500-a303-11e9-9187-88c4cb65fe3a.png">

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16865

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Now we are able to use the bulk actions without problems
