### ISSUE TITLE
If a content type has a category field that does not have a category specified, velocity throws

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16838]
To reproduce:
1. Add an event to the /about-us/index page container.  Events render
2. Go to the Category portlet and delete the "Events Types" top level category.
3. Flush your cache.
4. Go to the about /about-us/index page and you can see that no event renders.

The worst part about this is that there are no helpful errors in the logs.  I added more debugging and this is what we get:

https://gist.github.com/wezell/3fb528fb85c14b6a2e2c843a409f2ff5

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16839

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
