### ISSUE TITLE
You can't edit content in the browser unless you have the default content search portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16832]
If you remove the default content "search" portlet and replace it with a custom content portlet, you cannot open content to edit in the browser.  

We keep having this issue.  Can't we just make a rule that if we are trying to edit content and we don't find the "portlet" we are looking for to show underneath, we just use the first portlet or something?  I guess I mean, can we make it more robust in case of failure?

**Comment by wezell** [comment]
![no-editing](https://user-images.githubusercontent.com/934364/61010562-b9b10300-a344-11e9-9fff-99489c552a0e.gif)

**Comment by bryanboza** [comment]
Fixed, now I'm unable to reproduce the problem on master... Tested with the latest code // Postgres // FF
