### ISSUE TITLE
Show Country next to language

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16840]
In new edit mode, we are not showing the country code next to the language name.  We do this in most other places in the site.   

![Screen Shot 2019-07-12 at 10 52 02 AM](https://user-images.githubusercontent.com/934364/61139623-a95d6d00-a497-11e9-8886-a302114afe70.png)

**VS**

![Screen Shot 2019-07-12 at 11 25 12 AM](https://user-images.githubusercontent.com/934364/61139664-c1cd8780-a497-11e9-9016-00f4e089febb.png)

**Comment by fmontes** [comment]
Can't change language now in the page.

![Screen Recording 2019-08-20 at 7 30 21 AM](https://user-images.githubusercontent.com/751424/63351627-d0bc1b00-c31c-11e9-9645-feb0302d487b.gif)
