### ISSUE TITLE
Problems deleting content from edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16843]
### Describe the bug
We are having some problems when you try to delete a piece of content from any page and leave the tab. When you bring back to edit mode of the page the content still in the page 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page 
3. Add a new piece of content 
4. Now delete the content and leave the edit mode clicking in another portlet 
5. Bring back to the page and make sure the content is not on the page 

### Expected behavior
We need to save those changes and remove the piece of content from the page 

### Screenshots
https://screencast.com/t/6DLYOYetVP

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
This only happen when you have ONE contentlet in the container, I showed this to @jdotcms because I think this is related with a change he make for the personalization feature.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16856

**Comment by bryanboza** [comment]
Fixed, tested on master and I'm unable to reproduce with the last changes
