### ISSUE TITLE
Update content type page [DEV]

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16846]
As a stakteholder, I want all the pages to be consistent.

### Mock
![Content Types 5](https://user-images.githubusercontent.com/751424/63871222-bf0bf080-c978-11e9-90d4-51f7188e969f.png)

### Add buttom
Works the same as right now, with row and tab but when we click it in the top (sidebar) it should make the fields section to scroll down to where the row and or tab is being added.

### Toolbar
For the toolbar there is a new component @alfredo-dotcms created for edit mode and layout editor, we need to use the same component here.

## Acceptance Criteria
1. Match the mock
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
1. When create a tab (after the dialog close) scroll down
2. Use `transparent` instead of the color.
![Screen Shot 2019-08-30 at 12 46 27 PM](https://user-images.githubusercontent.com/751424/64044546-4cd80f00-cb24-11e9-8303-c88883eec699.png)

**Comment by fmontes** [comment]
Extra scroll when no fields to scroll, needs to remove.

**Comment by alfredo-dotcms** [comment]
@fmontes is this an issue/bug?
![image](https://user-images.githubusercontent.com/37185433/64710935-0fee0f80-d476-11e9-98f8-7706b831c84e.png)

**Comment by fmontes** [comment]
![Screen Shot 2019-09-11 at 3 58 53 PM](https://user-images.githubusercontent.com/751424/64738934-efda4280-d4ad-11e9-8edd-12b490b0b229.png)

The margin doesn't match the mock

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
