### ISSUE TITLE
Show selected workflows in the edit content type dropdown

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16864]
As a stakeholder, I want show workflows selected in order to give more info to the user

### Is your feature request related to a problem? Please describe
Instead of show "N items selected", show the workflows selected

<img width="422" alt="Screen Shot 2019-07-16 at 12 04 17 PM" src="https://user-images.githubusercontent.com/751424/61321835-8f8a9580-a7c9-11e9-83ef-d73d1cd2bb9e.png">

### Technical Approach
In this component we use the [primeng multiselect](https://www.primefaces.org/primeng-7.1.3/#/multiselect) and it have a `maxSelectedLabels` prop to do this.

## Acceptance Criteria
1. Show 3 selected workflows in the edit content type dropdown
2. Make sure it works with long names, use elipsis
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
