### ISSUE TITLE
Allow a user type to be set on the backend in the user manager

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16869]
![Screen Shot 2019-08-29 at 2 39 39 PM](https://user-images.githubusercontent.com/934364/63967215-e3e09080-ca6a-11e9-82cb-efc8c39ee8a4.png)

**Comment by bryanboza** [comment]
We need to refresh the properties when you navigate through tabs... Right now if you change some properties save. Then navigate to other tab and then bring back to the previous one, we are still showing the old properties 
SC: https://screencast.com/t/DbHiG43R4QmZ

**Comment by wezell** [comment]
We should only fix the first case that Bryan Discovered

**Comment by bryanboza** [comment]
Also, we are unable to use both filters, E.g:  Find for a FRONT END user that contains "XXX", this because when you type anything we are resetting the selection in the checkboxes 
SC: https://screencast.com/t/QIQTauJbIKa

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17288

**Comment by bryanboza** [comment]
Fixed, tested on master // Posgres // FF
