### ISSUE TITLE
Create a WebResourceBuilder

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16871]
We need to create a WebResourceBuilder that will allow us to use the builder pattern to specify what auth is required for specific resources.  This builder can call the existing WebResource under the covers to perform its actions.
```
InitDataObject initData = WebResourceBuilder
.params(params)
.requestResponse(request, null)
.allowAnonymous(true)
.requiredPorlet("content")
.requiredRole("roleKey")
.init();
```

- If `response` is null, use the `MockResponse` available on the `WebResource`
- `.allowAnonymous()` should default to false
- tests

**Comment by wezell** [comment]
We need to create a WebResourceBuilder that will allow us to use the builder pattern to specify what auth is required for specific resources
```
InitDataObject initData = WebResourceBuilder
.params(params)
.requestResponse(request, null)
.allowAnonymous(true)
.requiredPorlet("content")
.requiredRole("roleKey")
.init();
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16953

**Comment by jgambarios** [comment]
**Note to QA:** QA will be done for this tasks as part of https://github.com/dotCMS/core/issues/16870
