### ISSUE TITLE
Deprecate Snapshot functionality in favor of ES Snapshots 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#16876]
The snapshots functionality from dotCMS backend/REST API has been *deprecated* in favor of the [ES REST API snapshot functionality](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/modules-snapshots.html)

In order to make the old snapshot functionality work with external ES, two things are now required:

1. Define a volume in the docker-compose.yml mapping a `host dir` to a `container dir`. The docker-compose.yml is located under `WEB-INF/elasticsearch/config`

Example (last line):
```
volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./esnode.pem:/usr/share/elasticsearch/config/esnode.pem
      - ./esnode-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./custom-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - /Users/danielsilva/Documents/es/backup:/usr/share/elasticsearch/data 
```

2. Setting the property `ES_REPO_PATH` in the dotcms-config-cluster.properties with the `host dir` configured above

**Comment by nollymar** [comment]
We can provide support for an external cloud repository. As we are migrating to an external ES, it makes sense to have an external storage if the user wants to use it as a backup
