### ISSUE TITLE
Replace Apache Struts with Struts 1 Forever

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16879]
The struts version shipped with in dotCMS is Struts 1.2.4 which is EOLed and has a number of CVEs against it.  

**Important note:**  EVEN WITH STRUTS 1.2.4 ALL OF THE CRITICAL CVEs HAVE BEEN PATCHED/MITIGATED IN DOTCMS BY OUR UPGRADE TO BEANUTILS 1.9.3 AND THE USE OF THE `SuppressPropertiesBeanIntrospector.class`.

Regardless of the above statement, the visuals of the Struts 1.2.4 inclusion always sets off alarm bells in security audits.  We need to remove the dependency on Apache's Struts and instead use the "Struts 1 Forever" library found here:
https://github.com/kawasima/struts1-forever
which we will fork and maintain a version ourselves.

As a side note, one of our higher profile clients has been using this library for 2 years in various versions of dotCMS and have had no difficulties.

**Comment by wezell** [comment]
Forked: https://github.com/dotCMS/struts1-forever

**Comment by wezell** [comment]
We should repackage this as `com.dotcms.struts`

**Comment by wezell** [comment]
Can we test our osgi plugin that provides a Struts portlet?

**Comment by nollymar** [comment]
PRs:
Core: https://github.com/dotCMS/core/pull/17007
Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/673
Plugins: https://github.com/dotCMS/plugin-seeds/pull/40

**Comment by nollymar** [comment]
Struts portlet plugins (static and OSGi) were modified to support the new dependency

**Comment by john-thomas-dotcms** [comment]
Doc: Information about this change was added to the Changelogs, and a note was added to every document that has the word "struts" in it to make it clear to anyone who happens to be looking at our docs (or seeing them in Google searches) that we're not using the original struts.
