### ISSUE TITLE
Nullpointerexception in ActivatorUtil when registering portlets

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#16877]
### Describe the bug
When restarting dotCMS one of our dynamic plugins doesn't deploy because of the following error:
`Caused by: java.lang.NullPointerException
	at com.dotmarketing.osgi.ActivatorUtil.moveResources(ActivatorUtil.java:128) ~[dotcms_5.1.6_999999.jar:?]
	at com.dotmarketing.osgi.ActivatorUtil.moveVelocityResources(ActivatorUtil.java:95) ~[dotcms_5.1.6_999999.jar:?]
	at com.dotmarketing.osgi.GenericBundleActivator.registerPortlets(GenericBundleActivator.java:418) ~[dotcms_5.1.6_999999.jar:?]`

The cause is that "entries" is null. I'm not sure whether it should be able to be null but it is in our case and simply adding a null-check in the while fixes the issue.

It happens when our OSGi plugin Activator tries to add a portlet. 

https://github.com/dotCMS/core/blob/44450a48bd55d2f0e978891a132ac2a959581ae5/dotCMS/src/main/java/com/dotmarketing/osgi/ActivatorUtil.java#L128

### Workaround
Restarting the framework also fixes the issue but the plugin will be in a bad state each time dotCMS is restarted

### Debug information
When we receive the exception the variables in the method have the following values:
referenceResourcePath: /osgi\isaac-dotcms-davos-creditcardapply-5.1.6-1/ext/stepdown_settings.vm
destinationPath: C:\java\dotCMS\dotserver\tomcat-8.5.42\webapps\ROOT\WEB-INF\velocity/osgi/isaac-dotcms-davos-creditcardapply-5.1.6-1
containerFolder: osgi\isaac-dotcms-davos-creditcardapply-5.1.6-1/

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16878

**Comment by bryanboza** [comment]
Fixed tested with our OSGI portlet plugin and I'm unable to reproduce after the fix.
