### ISSUE TITLE
Unable to show the correct flags for multilingual contents 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16887]
### Describe the bug
We have problems showing the corresponding flag. This when you are adding content to a page 

### Steps to reproduce the behavior:
1. Login as admin 
2. Add two new generic languages (DE- Deutsch // FR- French)
3. Add a new piece of content with versions on those languages 
4. Add a new page 
5. Try to add these pieces of content to the page

### Expected behavior
As in the content search portlet, we need to be able to show the corresponding language flags to those pieces of content 

### Screenshots
<img width="1528" alt="lang1" src="https://user-images.githubusercontent.com/2641437/61483767-be844100-a95a-11e9-963c-17e76dd5422a.png">

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by alfredo-dotcms** [comment]
this is not reproducible on `local` and `demo`
https://monosnap.com/file/QndPoq97tooIVVKW7zR0YaunMjtzt7

**Comment by bryanboza** [comment]
Able to reproduce in the last master, to recreate please make sure you are not creating the version of the new content in the default language. 

SC: https://screencast.com/t/3cwRmSiBsEYb

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
