### ISSUE TITLE
Allow user to select default action in content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16880]
As a user, I want select default actions in content type that we can trigger when a contentlet is saved.

### Describe the solution you'd like
Add a dropdown with the actions in the content type forms.

The actions dropdown will fill the options from `/api/v1/workflow/schemes/actions/NEW` when the workflows are selected.

### Technical Approach
POST `/api/v1/workflow/schemes/actions/NEW`
body: 
```
{
    schemes: [workflowId1, workflowId1]
}
```

## Acceptance Criteria
1. Add a default workflow action dropdown and submit the form with the selected value
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need to improve some behaviors regarding this functionality: 
- If you try to create a new content type and don't select the default WF, we shows an error on log, but not at UI level 
SC: https://gist.github.com/bryanboza/afb738f8c791a5997c9015c10d243b34

- WE shows a URL error if after apply a EE license you try to select the workflow to some content type, but don't select the default action
SC: https://www.screencast.com/t/8TRWNkU4sYU

- The default action is a required field, this value can't be null, but if after set a default action you try to edit the content type and remove the current default action, we are able to save the changes without this value
SC: https://www.screencast.com/t/nM7WhKv2

- If you edit some content type, and remove the selected workflow and set a new one, in the default action drop dow, the previous default action is not completely removed, you can save the changes without select the new default action 
SC: https://www.screencast.com/t/ntlIiL3PpJ13

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
