### ISSUE TITLE
Add button to remove empty columns in content types rows

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16891]
As a user, I want remove empty columns in rows so I don't have to create a new row to change the layout.

<img width="1594" alt="Screen Shot 2019-07-19 at 10 35 01 AM" src="https://user-images.githubusercontent.com/751424/61551254-ebdff600-aa11-11e9-9abd-6739ebe9fe49.png">

## Acceptance Criteria
1. Allow users to remove empty columns
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
