### ISSUE TITLE
[Permissions] : Problems with records returned by the API when querying Site permissions

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16910]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/98778
Reproducible in dotCMS 5.1.5, and latest master.

The `PermissionAPI.getPermissionsByRole(Role role, boolean onlyFoldersAndHosts, boolean bitPermissions)` method returns the permissions associated to a specific `Role`. The assignment of permissions is not versionable, they do not depend on a specific version of your Contentlet. Also, deleting a specific version record of a Site must not affect the permission assignment at all.

There are two situations happening in dotCMS right now:

1. When you assign Site permissions to a Role, the `PermissionAPI.getPermissionsByRole(Role role, boolean onlyFoldersAndHosts, boolean bitPermissions)` method returns duplicate records if the Site has more than one version.
2. Deleting an old version of a Site resets the Site permissions.

### Steps to reproduce the behavior:
1. Log into dotCMS and create a blank test Site called `myTestSite`.
2. Create a JSP file containing this Gist: https://gist.github.com/jcastro-dotcms/0cfd8ba86e3048c44676d611fdf31255 , put it in your Tomcat folder and open it in an Incognito Window. The page must look like this (only three records initially):
<img width="943" alt="permissions1" src="https://user-images.githubusercontent.com/8779585/61730644-09c19980-ad37-11e9-9a00-c04b4acae1e7.png">

3. Go to **System > Roles & Tools > Select the Reviewer Role > Permissions > Add the `myTestSite` Site > Add Edit permissions to Folders and Content/Files** . Now, refresh the JSP file so that you can see the new two records:
<img width="946" alt="permissions2" src="https://user-images.githubusercontent.com/8779585/61730822-6e7cf400-ad37-11e9-869e-5772002991a0.png">

4. Go to the `myTestSite` Site and click **Save / Publish** so a new version is created. Refresh the JSP file once more so you can see the **FIRST** error: The duplicate records:
<img width="946" alt="permissions3" src="https://user-images.githubusercontent.com/8779585/61730938-a8e69100-ad37-11e9-9a8b-96855f6ece55.png">

5. In the `myTestSite` Site, go to the **History** tab and delete the old version of the Site. Refresh the JSP file once more so you can see the **SECOND** error: The permissions on the Site are deleted altogether:
<img width="943" alt="permissions4" src="https://user-images.githubusercontent.com/8779585/61731063-e6e3b500-ad37-11e9-916c-8f185625ecfe.png">

### Expected behavior
1. The method should NOT return duplicate records based on the number of versions that a Site has.
2. Deleting a single version of a Site (or Contentlet) should NOT interfere with the assignment of permissions.

### Additional context
The `PermissionAPI.getPermissionsByRole(Role role, boolean onlyFoldersAndHosts, boolean bitPermissions)` method is used by the `PermissionBitAPIImpl.doesUserHavePermissions(com.dotmarketing.business.PermissionAPI.PermissionableType, int, com.liferay.portal.model.User)` method, which is very sensitive and used by a lot of places in our code. Looking into this issue might also bring some performance improvements in permission lookup and/or filtering.

## Acceptance Criteria

1. Unit test

**Comment by wezell** [comment]
Let's write the broken test case first, then fix it.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16928

**Comment by erickgonzalez** [comment]
Working as it should, both issues have been fixed (duplicate records based on the number of versions and delete a version deletes all permissions).

**Comment by bryanboza** [comment]
Fixed, Integration tests are running without problems...
