### ISSUE TITLE
Add Site/Folder permission assigns wrong permissions to sibling roles

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#16922]
### Describe the bug

When grant permissions on a folder all the sibling roles get also access to the that folder.

Reproducible in Demo (5.1.6)

Reported by a client: https://dotcms.zendesk.com/agent/tickets/98487

### Steps to reproduce the behavior:
1. Create a folder in the ROOT of demo site. Name "Test Permission".

2. Go to System -> Role & Tools 

3. Create a new role under: "Publisher/Legal" -> "Reviewer". Name: "Contributor Sibling" -> Check Can Grant:" "Users" and "Permissions".

<img width="253" alt="Screen Shot 2019-07-25 at 4 23 40 PM" src="https://user-images.githubusercontent.com/8225685/61912895-9c5d6680-aef8-11e9-9f68-9972a6b3c230.png">
<img width="399" alt="Screen Shot 2019-07-25 at 4 24 18 PM" src="https://user-images.githubusercontent.com/8225685/61912910-af703680-aef8-11e9-961e-85f3ab5aa582.png">

4. Go to "Contributor Sibling" -> Permissions and "Add Site/Folder". Search the folder "Test Permission" and add it.

5. Check top "Edit" Permission. 

<img width="1200" alt="Screen Shot 2019-07-25 at 4 27 36 PM" src="https://user-images.githubusercontent.com/8225685/61913043-2279ad00-aef9-11e9-87cd-975b87b0d7a3.png">

6. Click on "Apply Changes" and accept the dialog that says: "You are applying permissions to one or more objects that currently inherit permissions..."

7. Go to role "Contributor" (next to the "Contributor Sibling" role). You will see that "Contributor" now has "View" permission to the folder. 

<img width="950" alt="Screen Shot 2019-07-25 at 4 29 10 PM" src="https://user-images.githubusercontent.com/8225685/61913178-813f2680-aef9-11e9-902b-2eb6d0ca2cab.png">

### Expected behavior
Should only update permissions of the Role we are modifying. Not its siblings. 

### Additional context
Some Dev clues that might help.
1. If you put a breakpoint here: https://github.com/dotCMS/core/blob/5.1.6/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java#L1605
2. With this breakpoint condition: 
```
permission.getRoleId().equals("db0d2bca-5da5-4c18-b5d7-87f02ba58eb6")
```
"Contributor" RoleId is "db0d2bca-5da5-4c18-b5d7-87f02ba58eb6"
```
select role_name from cms_role where id = 'db0d2bca-5da5-4c18-b5d7-87f02ba58eb6'; -- Contributor
```
3. You will see that logic is replacing the `permissionable` that comes from the DB, with the current `permissionable.getPermissionId()` that is the folder we are modifying. 

## Acceptance Criteria

1. Unit test

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16934

**Comment by erickgonzalez** [comment]
Working as it should now. Permissions are only added to the sibling we're modifying, not to the other ones.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master // Postgres // FF
