### ISSUE TITLE
Allow access to TempFileResource from different SessionIds

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16933]
Right now, the `tempFileResource` relies on a SessionId to validate your access to the `tempFileResource` that you have created - if you are the sessioned user who uploaded the tempResource, then you can view/checkin that resource.  The issue arises if you are unauthenticated and try to upload a tempfile via API (an XHR request) and then  access the temp file from an HTTP request or from another HTTP session (e.g. stateless api calls).  These two requests do not share cookies and will not share the `JSESSIONID`, resulting in a 403.  This will limit the usefulness of the the API when trying to use it from a headless resource.

What we need to do is build a request "fingerprint" that is a loose identifier for the user who is uploading the asset and will be shared across requests which we can use to "permission" view access to the `tempFileResource` for a short duration. The request fingerprint will also be checked and if it matches a recent request, will allow access to the newly created `tempFileResource`. The fingerprint should take into account a number of unique identifiers that will give enough protection for the short life of a `TempFileResource` (30m) so that the `TempFileResource` upload capability cannot be used as an attack vector against other users browsers.

**Comment by wezell** [comment]
This code needs some tests - test with different mock requests with different header values and nulls to make sure we are respecting the fingerprint.  Also needs testing from @hmoreras and @fmontes

**Comment by wezell** [comment]
You can test locally by uploading the page here,  and hitting it with http://127.0.0.1:8080/index.html as an unauthenticated user (get an api key).  You should see broken images for thumbnails when you upload.
  
https://github.com/dotCMS/core/issues/16699#issuecomment-504126327

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16973

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17013

**Comment by bryanboza** [comment]
Fixed, now we are able to upload temp files as anonymous user...
