### ISSUE TITLE
Clickable Link Anywhere on Related Content Needs to Select Relate Content Checkbox

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16936]
Reproduced on latest 5.1.6 Release version

To reproduce
Relate any two content types, add a relationship field to one of them and add related content. 

![Screen Shot 2019-07-30 at 4 21 22 PM](https://user-images.githubusercontent.com/1569167/62169932-f25e4f80-b2e6-11e9-87b5-fc1d8cd77f82.png)

**Current behavior:** When searching for related content, "finger" icon appears as if you could select the content to relate, but nothing happens if you click... you have to travel to the right, select the checkbox, then click on Relate.

**Expected behavior:** Expected behavior is that clicking anywhere in the highlighted line, should select the checkbox at the end of the row for you.  This was actually the case before the latest relationship changes

This simple change will make adding multiple related contentlets much faster and much more natural
 
In addition, we should add a second relate button at the bottom of the scroller in addition to the top for better usability (There is room and it is only copying functionality) :

![BottomRelate](https://user-images.githubusercontent.com/1569167/67333658-2c9e4e00-f4de-11e9-8829-a2f47b3c2f4a.png)

Right now if the item you are trying to relate in the list is at the bottom of the scroll, you have to perform a scroll down, check, scroll up, relate.  If we had a bottom relate button as well, then the user would only have to scroll down, check, relate, bypassing the second scroll step.

![scrollCheckRelate](https://user-images.githubusercontent.com/1569167/67333212-6c186a80-f4dd-11e9-839b-ddd26e3b0a16.gif)

**Comment by alfredo-dotcms** [comment]
PR
https://github.com/dotCMS/dotcms-dojo-theme/pull/69/files
https://github.com/dotCMS/core/pull/18047/files

**Comment by jgambarios** [comment]
The new button can be handle in a new ticket, it needs more discussion with the UI team as it depends on the screen size, the size of the list, etc.

**Comment by bryanboza** [comment]
Fixed, tested on the release branch // Postgres // FF. Now we are able to click in the whole line and works as expected.
