### ISSUE TITLE
Paginator in form selection dialog is blocking last row

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16943]
### Describe the bug
When you try to add a form to a page and the listing is more than 1 or 2 the paginator shows on top of the last row and don't allow you to select it.

### Steps to reproduce the behavior:
1. Go to content types and create a 3 more forms
2. Edit a page
3. Click + > Form

<img width="949" alt="Screen Shot 2019-07-31 at 3 32 35 PM" src="https://user-images.githubusercontent.com/751424/62298719-c3ec8b80-b430-11e9-97ec-4f2e81b85890.png">

### Expected behavior
1. Should allow to add the form in the last row
2. It should show the pagination only where there are items to paginate
3. When paginate the dialog should remain the same as the first page

## Acceptance Criteria

1. Update form selector according to the expected behavior
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
