### ISSUE TITLE
Setting up X-Content-Type-Options header causes blank screens in the backend

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#16955]
### Describe the bug
Adding the `X-Content-Type-Options` will make the browser to check and enforce the MIME content-type declared in the server's response. This will cause problems for some backend resources such as the workflows (`http://localhosthtml/portlet/ext/workflows/schemes/workflow_js.jsp`).

Basically, the browser refuses to load the _jsp_ as it's not declared as a script.

### Steps to reproduce the behavior:
1. Add the following header: `X-Content-Type-Options: nosniff`
2. Login into the backend
3. In the menu go to Types&Tags->Workflow
4. The contents are not loaded

### Expected behavior
Setting up this header should not break dotCMS's backend

### Screenshots
Blank page:
![Blank screen](https://user-images.githubusercontent.com/8353755/62524759-7740f000-b836-11e9-9040-e4f20e277642.png)
Error in the console:
<img width="1248" alt="Browser's console error" src="https://user-images.githubusercontent.com/8353755/62524771-7c9e3a80-b836-11e9-9842-8e3adc63478e.png">

### Desktop (please complete the following information):
 - OS: Linux CentOS
 - Browser: Firefox 68.0.1
 - dotCMS: 4.3.3

**Comment by mattyarbrough** [comment]
This is still a problem in 5.1.6

**Comment by oarrietadotcms** [comment]
Another client just hit this one when going live. Posting a comment to see if we can avoid the stale bot.

**Comment by wezell** [comment]
We need to ship with header `X-Content-Type-Options: nosniff` turned on

**Comment by alfredo-dotcms** [comment]
core PR: https://github.com/dotCMS/core/pull/18448

**Comment by alfredo-dotcms** [comment]
for testing
1) create a class 
```
package com.dotcms.security.apps;

import java.io.IOException;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class XContentTypeOptionsFilter implements Filter {
    @Override
    public void destroy() { }
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException
    {
        HttpServletRequest req = (HttpServletRequest) request;
        HttpServletResponse res = (HttpServletResponse) response;
        // Protection against Type 1 Reflected XSS attacks
        // res.addHeader("X-XSS-Protection", "1; mode=block");
        // Disabling browsers to perform risky mime sniffing
        System.out.println("fap se la come");
        res.addHeader("X-Content-Type-Options", "nosniff");
        chain.doFilter(req,res);
    }
    @Override
    public void init(FilterConfig filterConfig) throws ServletException { }
}
```

2) In main/webapp/WEB-INF/web.xml, add the filter:
```
<filter>
        <filter-name>XContentTypeOptionsFilter</filter-name>
        <filter-class>com.dotcms.security.apps.SampleResponseFilter</filter-class>
        <async-supported>true</async-supported>
    </filter>

...

<filter-mapping>
        <filter-name>XContentTypeOptionsFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```

**Comment by nollymar** [comment]
**Passed internal qa:** Using the filter provided, it works correctly

**Comment by bryanboza** [comment]
Fixed, tested with the provided info and now I'm unable to reproduce
