### ISSUE TITLE
PermissionBitFactoryImpl times out - throws DotConcurrentException

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16963]
When a page is hit a user's browser make multiple async requests to pull all the related css and js files required to render the page. In our starter site, some of these js and css file resources are deeply nested in the folder structures, yet inherit permissions from the system host, all the way up the tree.

If a page with all its js/css is requested against a dotcms instance with a cold cache, it can cause a lock within the permissionapi while the permission api does multiple recursive lookups trying to find the parent permissionable.  This can easily be reproduced with our starter data by:

1.  go to http://127.0.0.1:8080/services/wealth-managers/
2. dump your browser cache (or turn on no-caching in the browser debugger)
3. in another admin session, clear the dotCMS cache.
4. refresh - http://127.0.0.1:8080/services/wealth-managers/ - I get back a page with no css
5. watch the dotCMS logs and you will see `DotConcurrentExceptions`

The good news is that the site always recovers once the cache gets warmed up.  Still, we should always be as fine grained as possible when locking resources and release locks as quickly as we can - even if we have to re-lock to perform other actions.

**Comment by wezell** [comment]
PR: #16964

**Comment by fabrizzio-dotCMS** [comment]
Testing

**Comment by fabrizzio-dotCMS** [comment]
I just ran the integrations test on the branch `'origin/issue-16963-permission-concurrency-exception'.` with a clean environment. Brand-new Database, No assets etc.. ad I still see a hand full of failures all linked to the Concurrence Exception error.

The interesting thing this time is they all failed with SYSTEM_HOST

See: 

`Caused by: com.dotcms.concurrent.DotConcurrentException: Unable to acquire Lock on key `PermissionID:SYSTEM_HOST` and thread `Test worker` 
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:94)
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55)
	at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:16)
	at com.dotmarketing.business.PermissionBitFactoryImpl.lambda$2(PermissionBitFactoryImpl.java:2169)
	at io.vavr.control.Try.of(Try.java:62)
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody0(PermissionBitFactoryImpl.java:2169)
	... 113 more`

The Case described in the description of this issue is no longer happening.

**Comment by wezell** [comment]
Interesting - it might be that we are looking for permissions on an asset has no inheritable permissions and we are not caching or storing that fact now and hitting the db every time.

The way the PermissionCache should work is to return null if there is nothing in the cache (cache miss) and to return an empty list if all possible inheritables have been checked and there are no permissions for the asset type. 

I think 1 of two things might be happening - we might be missing the logic where we add and expect an empty list when there are no inheritable permissions, something like permissionCache.addToCache( permissionable, new List());

AND/OR we might be hitting the SYSTEM_HOST and endlessly looping through it because it is its own parent permissionable.

**Comment by fabrizzio-dotCMS** [comment]
I'll give your suggestions a try on a separate branch cut from yours.

**Comment by wezell** [comment]
Thinking about it, I think that the `SYSTEM_HOST` has always been the issue - it is just apparent now b/c we are not running the whole recursive block in nested StrippedLocks.  Take this Host/folder hierarchy:

`/SYSTEM_HOST/demo.dotcms.com/application/themes/quest/bower_components/js`

Before we were locking at the top level, folder `js` and recursing down, locking at each subsequent level.  Obviously, the `js` lock would time out first because it was the first taken - we would never see that the `SYSTEM_HOST` was the root cause.

Now, we are only locking when we select or upsert the db and it is more clear as to what is happening.  

The integration test should be to create a new host, a deep folder structure and a piece of content in the deepest folder (no perms).  Flush the cache and try to load permissions on it to see if we just endlessly recurse.

**Comment by wezell** [comment]
@bryanboza this needs a full click test regression for permissions and permission inherantance

**Comment by fabrizzio-dotCMS** [comment]
Please consider this PR https://github.com/dotCMS/core/pull/17041 before sending this out into QA

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17043

**Comment by jgambarios** [comment]
**Note to QA:** We need a full regression tests for permissions.

**Comment by bryanboza** [comment]
Fixed, tested the principal permissions cases and seems everything is working as expected... Tested on master // Postgres // FF
