### ISSUE TITLE
Clicking item on content References tab throws HTTP Status 400 – Bad Request

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#16961]
**dotCMS version 5x**

Clicking item on content References tab throws HTTP Status 400 – Bad Request

**Steps to reproduce the behavior:**
1. Open a contentlet (in this example, an "Event")
2. Click on References tab
3. Click an item in the list on the tab
4. See error - HTTP Status 400 – Bad Request

**Expected behavior**
Item should open.

**Screenshots**

![image](https://user-images.githubusercontent.com/49727631/62655316-50aeb200-b927-11e9-9509-def09e50f650.png)

![image](https://user-images.githubusercontent.com/49727631/62655331-5906ed00-b927-11e9-8e58-4d9345b434f8.png)

![image](https://user-images.githubusercontent.com/49727631/62655342-61f7be80-b927-11e9-8f2c-9f7b269a368a.png)

Desktop (please complete the following information):
 - OS: n/a
 - Browser Chrome, Firefox

**Comment by dsilvam** [comment]
Passed internal qa: references links are working, although it took a few seconds to be able to click on "Home" references of the Event named "Wealth Management Annual Client Meeting". Please pay attention to this @bryanboza when testing.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

According to the @dsilvam comment, it took some seconds but is redirecting without problems
