### ISSUE TITLE
Personalization FE issues - retest and create individual issues

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16971]
- ~~If you personalize some page for any persona, and when you are in edit mode, in the edit tab and you try to change the persona in the selector, we are moving to the page in edit mode and we are not asking if you want to personalize to this other persona, if you edit something we edit the content to all the other personas, not specifically the selected one. Then to create another personalization you need go to preview and then bring back to edit tab.
SC: https://screencast.com/t/nDU4IgibvT~~

- ~~The "+" button in the persona selector is not doing anything 
SC: https://screencast.com/t/rD3o7E6z~~

- ~~If you have a locked page (products), then open any other page and select any persona in the persona selector, here if you use the internal navigation to go-to products, we are leaving the product page with the persona selected, and we are not doing the personalization. 
SC: https://screencast.com/t/nO37Snck9c~~

- ~~Pagination on the personas selector component is not working properly 
SC: https://screencast.com/t/lvUIlOyV~~

- If you remove all the pieces of content from a personalized version, we should bring back to the default visitor version, but we are not updating properly the persona selector
SC: https://screencast.com/t/Jv9upSpkJGSh

**Comment by fmontes** [comment]
- [] If you lock the page as a "Default Visitor" and then change to a persona and personalize the page (the page gets lock and move to edit) and then you select the "Default visitor" again it will move to "preview and unlock" but it should stay load and edit as it was for the selected persona and the "Default Visitor"

**Comment by bryanboza** [comment]
- We are translating the persona selector when you try to see the Spanish version of the page, and this never brings back to the default language.
SC: https://screencast.com/t/Jc6pecAx
_We don't need to translate anything here, this because I just want to see the Spanish versions of the page not set the language._

**Comment by wezell** [comment]
Freddies behavior above is ok as it is now expected.

**Comment by wezell** [comment]
@bryanboza - this meta issue needs to be retested.

**Comment by fmontes** [comment]
The log issues was moved to: https://github.com/dotCMS/core/issues/16977#issuecomment-533695491
