### ISSUE TITLE
Problems adding forms to pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16970]
We have a UI problem when you try to add a form to a page, we are unable to add one of the forms of the list

### Steps to reproduce the behavior:
- Login as admin
- Edit some page 
- Try to add any form to the page 

### Expected behavior
We need be able to add any of the forms of the list, in this case when you click to the select button we are not doing anything. 

### Screenshots
<img width="890" alt="form1" src="https://user-images.githubusercontent.com/2641437/62724259-d25a1a80-b9cf-11e9-83f7-944a4a5f87a5.png">

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
This was fix here: https://github.com/dotCMS/core/issues/16943
