### ISSUE TITLE
Make ContainerHandler skip file based containers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16988]
When importing a bundle from an older dotCMS - not antique, just say 5.1.1, bundles contain references to File Based Containers, which cause the ContainerHandler to throw up.

We've fixed our ContainerBundler but our ContainerHandler should just skip those references, as they can be safely ignored.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16989

**Comment by bryanboza** [comment]
Fixed, now we are able to import bundles with pages and templates that use a File-Based Containers
