### ISSUE TITLE
Push publish support for default workflow actions

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16984]
We need to include the new default workflow actions as dependency when a Content Type / Workflow is push.

**Comment by john-thomas-dotcms** [comment]
Doc: Need to update the Push Publishing Dependencies doc

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17273

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/17267
https://github.com/dotCMS/core/pull/17273
https://github.com/dotCMS/enterprise-2.x/pull/678

**Comment by fabrizzio-dotCMS** [comment]
I created a custom workflow with 1 step and some actions. Linked the WF a CT and a default Action.

- Created a new instance of the CT and push-published it. The new Workflow is copied, the action is still linked to the CT on the receiver.

- Introduced a default action through the endpoint. The new entry point to an existing workflow using an id (Not a CT). Linked a CT with such WF. Then Created an instance of the CT and push-published the instance. Everything gets copied as expected. The entries on the db look exactly as the items on the table on the sender.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
