### ISSUE TITLE
Create add Persona dialog/form

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16981]
As a user I want to add personas from edit page in order to customize pages for new personas.

### Is your feature request related to a problem? Please describe
When we're editing pages and personalizing, we might want to add a new personas to personalize the page for and we don't want to go all the way to the `Content > Search` to create a new persona.

### Describe the solution you'd like
Create a "Form Dialog" (just like the one in edit mode) with the fields:

1. Host (we already have a component for this)
2. Name
3. Key Tag
4. Photo

Click here will trigger the form:
![Screen Shot 2019-08-12 at 6 51 37 AM](https://user-images.githubusercontent.com/751424/62866361-d935a580-bccd-11e9-9857-cd2d9f8f69d6.png)

### Technical Approach
1. Instead of adding the component in the html, let's included the component dynamically when we need to: https://angular.io/guide/dynamic-component-loader
2. Use the content api to create the persona
3. To upload the photo we need to use the temp resource API.

### Additional context
1. The dialog form needs to work exactly as the content type one, enable and disable the submit button when the form is valid.
2. For the `Photo` field needs to use the temp resource endpoint
3. The `Key Tag` field value should be autogenerated based on the name:

![ScreenRecording2019-08-12at6](https://user-images.githubusercontent.com/751424/62864257-7097fa00-bcc8-11e9-8d1d-d97b02c6684a.gif)

## Acceptance Criteria
1. Add persona from edit page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need some work here: 

- In the photo field, we are filtering the image fields, but we are not recognizing the `.webp` as an image. 
SC: https://screencast.com/t/P2vouVp0BLx

- In the persona filer, if I type some name and don't have consistencies, we return an empty list of personas, but if you add a space, we return again the complete list of personas and ignore the consistencies 
SC: https://screencast.com/t/l73W1GwI2WUY

- Finally, If you type some word in the filter and the person does not exist, and you try to add a new persona with the `+` button, we should include the typed word as name of the persona in the persona form.
SC: https://screencast.com/t/HMetYkz7V

**Comment by bryanboza** [comment]
We need to improve the message in case the persona key already exists
<img width="561" alt="bad request" src="https://user-images.githubusercontent.com/2641437/64354151-1aaf2d00-cfbc-11e9-8d69-b1cee02f27ee.png">

**Comment by fmontes** [comment]
@hmoreras Let's do some improvements here in the http error handler, looks for the error message in `errors[0].message` and if not there show the default.

As it is right now we always show the default.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF... New enhancement here #17195
