### ISSUE TITLE
GraphQL Problems removing/replacing binary values 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16993]
As soon as you remove and/or replace a binary file from a content entity, any following GraphQL queries made on this same content will return a null value for all the binary fields of the same record. 

Note that all other API requests other than GraphQL will return the complete information for those binary fields. 

We think that the removal of a binary content from a record breaks its GraphQL structure and every binary field information cannot pull anymore right after that. If you restore the version before you remove a binary field content of a record from its history, everything works fine right after. 

### Steps to reproduce the behavior:
- Create a new content types `test`
- Add those fields (_Text: name, Binary: bin1, Binary:bin2, Binary: bin3_)
- Add some pieces of content to the new content type
- Via GraphQL made this query
```
{
  testCollection(limit: 10) {
    name
    bin1{name, isImage, size}
    bin2{name, isImage, size}
    bin3{name, isImage, size}
    }
  }
```
- Make sure you are getting the results without problems 
- No go to one of the pices of content and remove the value for `bin2`
- Refresh the query

### Expected behavior
We need to be able to support that scenario 

### Screenshots
SC: https://screencast.com/t/nemspRbCdxxF

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17008
