### ISSUE TITLE
Lots of exceptions log as CookieFilter exceptions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17009]
The CookieFilter is one of the first filters to run in dotCMS.  It logs any error in any request as "Exception processing cookies".  In any event, it says that it is a cookie filter exception and obfuscates the real cause of errors and the CookieFilter should just try to do what it is expected to do.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17010
