### ISSUE TITLE
Create a new Email Content Actionlet that emails an HTML version of the content to the list of users/roles

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17015]
For the new form builder, we need to create a new actionlet that takes very little customization out of the box and will send an HTML based email that includes all the form fields.  The idea is that the actionlet would have 3 params

1. subject, with the default value of `$content.formTitle`
2. to, with the default value of `$content.formEmail`
3. body, with the default value of #dotParse("static/form/default-email.vtl")

In the `static/form/default-email.vtl` .vtl we need to spit out the submitted content as html that can then be send to the emails on record.

Here is the start of the default vtl - needs work obviously
https://gist.github.com/wezell/7226521a17aeba9965069bc5d6698211

**Comment by bryanboza** [comment]
We are printing the complete encoding email in the log file, we need to remove this.
Log: https://gist.github.com/bryanboza/7a4b3838b45e77258ee2cda78b89f708

**Comment by wezell** [comment]
This is in your context.xml, you have smtp set to debug
