### ISSUE TITLE
We are unable to personalize content if the persona is not from the Persona content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17045]
If you add a new `persona`content type and then add some personas, we shows that one in the persona selector when you are editing a page. But if you try to personalize a version of this page for that persona we have a bad request error. 
ST: https://gist.github.com/bryanboza/877c41310afe102c325efaa5db424427

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new persona content type 
4. Add some personas to that content type 
5. Now edit any page 
6. Select one of the new personas in the persona selector and try to personalize 

### Expected behavior
We should be able to allow create personalization of any persona of the list 

### Screenshots
SC: https://www.screencast.com/t/c0jmuXgTs

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17249

**Comment by erickgonzalez** [comment]
Working as it should, now able to personalize pages to new persona content type.

As an enhancement we need to filter the personas regardless of the page, right now if I type the name of another persona that is on another page, it does not show.

**There are 3 personas that start with test on the page 2**
<img width="506" alt="Screen Shot 2019-09-18 at 9 24 23 AM" src="https://user-images.githubusercontent.com/5278970/65162265-34a63200-d9f6-11e9-8d89-79de39f9616f.png">

**But searching for the term test on page 1 does not show any results**
<img width="490" alt="Screen Shot 2019-09-18 at 9 23 59 AM" src="https://user-images.githubusercontent.com/5278970/65162160-104a5580-d9f6-11e9-93a9-37d017090ddb.png">

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
