### ISSUE TITLE
We lose the default site search index after flush cache 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17046]
If you create a new index and set this as default, we are losing the status and leave the system without default index 

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new site search index and set this as default 
3. Create a new page and using the site search view tool pull some result from site search 
https://gist.github.com/bryanboza/27484bac1f6c9d3693c5ecafc9c6eaf0
4. Hit the page from FE
5. Now flush the cache 
6. Reload the page 

**FYI: If you go to the site search portlet we don't have the default as status of the index** 

### Expected behavior
We need be able to keep this status 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
Note: The workaround for this problem is to use a named index.

**Comment by erickgonzalez** [comment]
Working as it should. Now even when flushing cache we're keeping the site search index as default and showing results.

**Comment by bryanboza** [comment]
Fixed, now we are keeping the default and after clear cache still working
