### ISSUE TITLE
Json Serializer improvements for page resource

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17052]
We need to fix some enhancements to that method. 

- We are excluding completely the tag fields 

- We are returning twice the `friendlyName` in the page object 
SC: https://www.screencast.com/t/0qvIZBAad

### Steps to reproduce the behavior:
1. Login as admin 
2. In content types create a new content type `test` with Page as base type
3. Add two new fields to that content type (_Text: Field1 Tag: Field2_)  
4. Now using the page resource try to get that page (_**/api/v1/page/json/{pageUrl}**_) 
5. Make sure you have the `field1` and `field2` in the json response

### Expected behavior
We need to include every type of field without problems in the response 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by wezell** [comment]
We need to set Jackson to automatically serialize all contentlets, regardless of their base type, using the common properties.

**Comment by nollymar** [comment]
Fixed in here: https://github.com/dotCMS/core/pull/17144

**Comment by wezell** [comment]
PR2: #17052

**Comment by john-thomas-dotcms** [comment]
Doc Note: The main change that needs to be highlighted in the Changelogs is that the "friendlyname" field (all lower-case) is no longer returned, since it was a dup of the "friendlyName" (camelcase) field (which is still returned).

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core/pull/17168

**Comment by dsilvam** [comment]
Passed Internal QA: Only one `friendlyName` attribute and tag field including its value

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are including the tags fields in the json response, also, we are not duplicating the friendly name
