### ISSUE TITLE
Persona listing endpoint default persona incorrectly translated

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17050]
### Describe the bug
When you ask for the persona listing and the page is in a specific lang is returning the `Default Visitor` translated.

### API
`/api/v1/page/{pageID}/personas`

### Steps to reproduce the behavior:
1. Go to Edit page
2. Select another language
3. Check the persona selector
4. See that "Default Visitor" said "Visitante por Defecto"

### Expected behavior
It should said: "Default Visitor"

### Screenshots
![Screen Shot 2019-08-21 at 10 03 51 AM](https://user-images.githubusercontent.com/751424/63448372-033c4580-c3fb-11e9-8043-9c5d3b3e3f39.png)

## Acceptance Criteria

1. Fix the persona listing endpoint
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
https://monosnap.com/file/tjyh3YPCAT7bwoKGAr6lpm0s1ZWFzn

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17207

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
