### ISSUE TITLE
Execute JavaScript code from succesCallback field in form

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17078]
As a user, I want execute JavaScript code when the form submit is success.

### Is your feature request related to a problem? Please describe
In the backend there is a new field for forms named: `successCallback`. This field will contain JavaScript code that we need to execute when form submission is success.

### Describe the solution you'd like
Use `eval` to execute this code since what we have is a string of code.

## Acceptance Criteria
1. When the forms submit is success get the code from the `successCallback` field and execute it.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by freddyucv** [comment]
Need a new starter to test, currently the form are not render

**Comment by bryanboza** [comment]
Fixed, now we are able to execute JS code if you add something on this field
