### ISSUE TITLE
The endpoints for personalized and despersonalized needs to respect edit permissions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17075]
### Describe the bug
When you hit the endpoint for **despersonalize** with a user that doesn't have permission to edit the page the endpoint returns a `403` but remove the personalization.

We suspect that the same happen with the Personalize endpoint.

#### Personalize
```
{
    method: RequestMethod.Post,
    url: `/api/v1/personalization/pagepersonas`,
    body: {
        pageId,
        personaTag
    }
}
```

#### Despersonalize
```
{
    method: RequestMethod.Delete,
    url: `/api/v1/personalization/pagepersonas/page/${pageId}/personalization/${personaTag}`
}
```

### Steps to reproduce the behavior:
1. Personalize a page
2. Give permisision to **view** the page to Chris
3. Login as Chris
4. Go to the page
5. Open the persona selector and click the `X` button
6. See how the personalization goes away (you might need to reload the page)

### Expected behavior
It should not allow the user to despersonalize the page.

## Acceptance Criteria

1. Make endpoints to respect **edit** permissions
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17315

**Comment by jdotcms** [comment]
Nice it works pretty fine. I have tested from UI and REST and does not allows to remove the personalization if the user does not have permissions over the page

**Comment by bryanboza** [comment]
After this change we have some problems here: 

- if you add permissions to some limited user to View all the personas (this directly from the content type), we are unable to see the list of personas from the preview mode of the page, we are able to show this just from live. 

- Also, from the live tab, we are unable to see if the page has personalized versions for some specific persona

SC: https://screencast.com/t/pIBPkwM3P

**Comment by fabrizzio-dotCMS** [comment]
> After this change we have some problems here:
> 
> * if you add permissions to some limited user to View all the personas (this directly from the content type), we are unable to see the list of personas from the preview mode of the page, we are able to show this just from live.
> * Also, from the live tab, we are unable to see if the page has personalized versions for some specific persona
> 
> SC: https://screencast.com/t/pIBPkwM3P

I reverted this change and re-tried all the steps listed and I am able to confirm this is a separate issue. I can totally reproduce it even without the security changes that were originally introduced on this ticket.

**Comment by bryanboza** [comment]
Fixed, the new cases were moved to a new card

**Comment by fmontes** [comment]
@bryanboza comments:

We have problems here:  

- After this fix now we are able to see the list of personas just respecting the FE role, but If you have a personalized page and you add full edit permissions to a limited user, when you try to remove the personalization as the limited user we are unable to do it and we have an error on logs. Nothing in UI.

FYI: This is because we are validating permissions to the persona. And I don't have permissions to the personas content type. If I add permissions to the specified persona that works 


ST: https://gist.github.com/bryanboza/dfb44848600d8e970d16d51e812fdb7c
SC: https://screencast.com/t/vp6egJYkRMRy

**Comment by jgambarios** [comment]
The problem described above was fixed in https://github.com/dotCMS/core/issues/17411
