### ISSUE TITLE
Persona selector is disabled when the page is in the root of the site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17085]
We are unable to use the persona selector when the path of the page is located in the root of the site.

### Steps to reproduce the behavior:
1- Login as admin 
2- Go to the Site Browser and create a new page in the root of the site
3- Try to edit the page and try to use the persona selector 

### Expected behavior
We need to be able to use that component at any page without exceptions. 

### Screenshots
SC: https://screencast.com/t/trDXRPCRIUfi

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17228

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
