### ISSUE TITLE
Container box is not growing when add assets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17087]
### Describe the bug
When you add any asset to a page the container box doesn't grow as expected.

![Screen Shot 2019-08-27 at 11.57.16 AM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/2c0c9404-bb27-4f92-bb12-d9d665d11e56)

### Steps to reproduce the behavior:
1. Go to Edit a page
2. Add a content/form/widget
3. See error

### Expected behavior
It should grow the same with all other containers in the row.

## Acceptance Criteria

1. Make the container resize when add and remove assets to the page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We still with the same problem with some specific contents 
SC: https://screencast.com/t/D87L1f7yN

Also, the same thing happens with the videos.
