### ISSUE TITLE
add unique key on workflow_task(webasaset, language_id)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17088]
We do not have a constraint on the workflow_task table based on  `workflow_task(webasaset, language_id)`

This can result in multiple workflow_tasks per contentlet x language which causes issues with tests.

We need a startup task that adds a unique index on those columns

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17456

**Comment by jgambarios** [comment]
Recently we found during tests:

```
db.DotConnect - Executing ALTER TABLE workflow_task ADD CONSTRAINT unique_workflow_task UNIQUE (webasset,language_id)
10:49:58.115  ERROR db.HibernateUtil - ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
com.dotmarketing.exception.DotDataException: ERROR: could not create unique index "unique_workflow_task"
  Detail: Key (webasset, language_id)=(72839e70-7f8e-412f-a895-fd17aa920e14, 1) is duplicated.
```

And the problem is because before running the upgrade task we already had duplicate data in the `workflow_task` table.

We need to analyze what options do we have, clean up the data before to apply the constraint?, on fail just continue without adding the constraint?.

One option could be to use the `HAVING` clausule, something like:

```
GROUP BY webasset
 HAVING COUNT(*)>1;
```

We need to see how heavy could be using the `HAVING` in a big dataset.

**Comment by wezell** [comment]
we should clean up the duped records in our startup task - I think we should only keep the latest one or the one with the longest history or something like

**Comment by jgambarios** [comment]
Just as reference executing explains on postgres shows very similar results between those two queries with **the starter data**:

```
SELECT webasset, language_id
FROM workflow_task
GROUP BY webasset, language_id
HAVING count(*) > 1;
```
```
SELECT *
FROM (SELECT webasset, language_id, count(*) AS duplicated
      FROM workflow_task
      GROUP BY webasset, language_id) ss
WHERE duplicated > 1;
```

**Comment by fabrizzio-dotCMS** [comment]
got it. I'll take care of the dupes clen-up.

**Comment by wezell** [comment]
PR: #17737

**Comment by nollymar** [comment]
A new IT was implemented for changes on https://github.com/dotCMS/core/pull/17737

**Comment by jgambarios** [comment]
Fixing tests for oracle and mssql https://github.com/dotCMS/core/pull/17831
