### ISSUE TITLE
Filter fields when edit a form type content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17098]
As a stakeholder, I want to filter the fields available when creating a "form" so the user can't add fields that don't exist yet in the custom elements.

### Is your feature request related to a problem? Please describe
Now that we created the custom elements for each field, still WIP, we can't allow users to create forms with fields that doesn't exist yet because when they render the form they will not see some of fields with no error or warning, just not show, which is confusing.

### Technical Approach
Get the field list from `projects/dotcms-field-elements` and filter those when editing a form.

## Acceptance Criteria
1. Filter fields when editing a content type of base type form
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we are filtering the list with the components that we already implemented
