### ISSUE TITLE
Create Form module portlet and rotuting

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17099]
As a stakeholder, I want a portlet so marketers can manage forms in order to keep it simple and out of the content types.

### Technical Approach
1. The url will be `forms`
2. We need to re use the exact same modules from `content types` portlet but filtered.

## Acceptance Criteria
1. Create new portlet for `Forms`
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
Listing is done, we need to do the routing for the create/edit

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
