### ISSUE TITLE
Copy/pasting folder switches sites - version 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17113]
On an instance with more than one **Site**, copying and pasting a folder reverts browser to previous Site. 

**Steps to reproduce the behavior:**
1. Login
2. Navigate to Browser
3. Switch to a different Site
4. Copy/paste folder

**Expected behavior**
Browser should remain on the Site you are currently working. 

**Actual Behavior**
Browser reverts back to the original site. Folder is copied correctly on the other site - the issue is the auto-switching back to the original Site. 

**Screenshots**
**1. Mark for Copy** 

![image](https://user-images.githubusercontent.com/49727631/63955044-b505f280-ca49-11e9-8e36-14bf8d496d45.png)

**2. Paste**

![image](https://user-images.githubusercontent.com/49727631/63955490-6573f680-ca4a-11e9-93c0-3cc2b47e1333.png)

**3. Reverts back to original site:**

![image](https://user-images.githubusercontent.com/49727631/63955217-ff876f00-ca49-11e9-8afc-3256784f0ff6.png)

**Desktop:**

 - OS:n/a
 - Browser Chrome/FF
 - Version n/a

**Comment by wezell** [comment]
PR: #17557 17557

**Comment by bryanboza** [comment]
ok, after the last changes now we are not redirecting immediately after pasting the folder//file, but if you refresh the browser or click in the browser portlet to refresh, we are showing the default site content and the new site is selected in the site selector component 
SC: https://www.screencast.com/t/ll9fZAvLF

**Comment by bryanboza** [comment]
Fixed, tested on the release branch // Postrges // FF
