### ISSUE TITLE
Custom Portlet disappear from Tool Group when a new plugin is deployed

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17127]
Reported via Support: Ticket [99096](https://dotcms.zendesk.com/agent/tickets/99096)
Reproducible in dotCMS 5.1.6

When a dynamic plugin is deployed and it includes the custom portlet, the portlet can be added to a Tool Group and it shows in the side bar menu under the Tool Group. However, when a second plugin is deployed that also includes a custom portlet, the previous portlet disappears from the tool group.

### Steps to reproduce the behavior:
1. Deploy a dynamic plugin containing a custom portlet.
2. Go to 'System -> Roles & Tools' portlet, then go to Tool tab, and click the System tool group.
3. Add the custom portlet to the 'System' tool group and save it.
4. Verify that the custom portlet is shown in the side bar menu under the System tool group.
5. Deploy other dynamic plugin that included other custom portlet.
6. The custom portlet previously added to System tool group disappears from the side bar menu.

### Expected behavior
When custom portlets are added to a tool group, they shouldn't be removed from the tool group when a new dynamic plugin containing custom portlets is deployed to dotCMS.

### Screenshots
Dynamic plugin including a custom portlet deployed:
![image](https://user-images.githubusercontent.com/2894221/64129081-2231c480-cd77-11e9-988a-403d68f7aee1.png)

Custom portlet added to System tool group:
![image](https://user-images.githubusercontent.com/2894221/64129094-35dd2b00-cd77-11e9-9e37-0e25d9cabbd7.png)

Custom portlet displayed in sidebar menu:
![image](https://user-images.githubusercontent.com/2894221/64129104-49889180-cd77-11e9-894b-d0dfd7413585.png)

Other dynamic plugin containing a custom portlet deployed:
![image](https://user-images.githubusercontent.com/2894221/64129115-5c9b6180-cd77-11e9-8850-3c42412e2586.png)

Previously added custom portlet disappears from tool group:
![image](https://user-images.githubusercontent.com/2894221/64129122-6e7d0480-cd77-11e9-8460-6b3cf6a44291.png)

### Additional context
This has been reported by customer via Support: Ticket [99096](https://dotcms.zendesk.com/agent/tickets/99096)

**Comment by erickgonzalez** [comment]
This is because Felix framework, every time you deploy a new fragment it reboots the framework since the fragment can affect all the plugins. The fix we approach here was that only when you click over the `Stop` or `Undeploy` option, it's gonna be removed (as intended). The same fix was applied to the workflows actionlets. https://github.com/dotCMS/core/pull/17205

**Comment by erickgonzalez** [comment]
Doc: If you remove a plugin from the **load directory** via the **file system**, you need to **Restart Framework** so the references of the plugin are deleted.

**Comment by dsilvam** [comment]
Passed Internal QA: After deploying second custom portlet, previous one added stays and two of them can co-exists without issues.

**Comment by bryanboza** [comment]
Fixed, now we are not removing the previous custom portlets after upload a new one
