### ISSUE TITLE
You cannot reset permissions on content without a host/folder field that lives on a host 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17136]
#16043 changed how we set contentlet's default host when it does not have a host or folder field.  Because of this, content types that live on a host and without a host/folder field do not have any way to cascade / reset permissions on the underlying content objects.  To test:

1. Create a content type with 1 text field that lives on `demo.dotcms.com`
2. add some content to it
3. Check how it is permissioned, you will see it inheriting from `demo.dotcms.com`
4. Go to the content type, update permissions and then hit "reset". 
5. Go back to the content object and see that it is still inheriting from `demo.dotcms.com`

My take away is that If a content type does not have a host/folder field, we need a way to batch update the host/folder that content lives on in order to effectively update permissions.  4 different ideas include:

1. Message that if you want to respect content type permissions, the content type needs to live on the system host
2. When performing a permissions reset on a content type that does not have a host/folder field, update the content's host/folder field to the host folder field set on the content type before reseting perms.
3. Create a workflow action that takes input and then performs the update in a batch process.
4. Add a button on the content type edit screen that allows a user to reset the host/folder for content that does not have a host/folder field, e.g. something like:

![Screen Shot 2019-09-03 at 5.09.36 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/e1564029-f04a-4abf-8bb1-483a4347151a)

**Comment by DeanGonzalez** [comment]
I would name that button in #4 TO `RESET EXISTING CONTENT` but only show that button if a) there is no "site/folder" field on the content type for publishers to use, and 2) only after the host/folder field on the Content Type itself is changed. Definitely needed functionality..
