### ISSUE TITLE
Update Task05170DefineFrontEndAndBackEndRoles logic

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17146]
We need to update the logic on `Task05170DefineFrontEndAndBackEndRoles`.  The logic for upgrading should be:

1. Everyone gets the front end user role
2. Anyone with layout OR an API Key gets added to the backend user role

**Comment by bryanboza** [comment]
Fixed, tested multiple times upgrading from 4.x and 5.x versions to master and now we are respecting the mentioned rules.
