### ISSUE TITLE
Make sure that current front end logins requires a front end user role

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17148]
Currently, when a user logs into dotCMS they either use the deprecated `LoginAction` or call the `CMSUsersWebAPI.doLoginMacro`

We need to reject logins to those for users that do not have the front end role.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17288

**Comment by jdotcms** [comment]
Have tried to get logged in on BE with a FE user and it was block, ok.
But if you go to front end, the edit mode is being loaded

<img width="1371" alt="Screen Shot 2019-09-25 at 10 52 04 AM" src="https://user-images.githubusercontent.com/19578350/65622864-ccba9300-df83-11e9-93fa-2d5a75b1bf55.png">

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17370

**Comment by jdotcms** [comment]
fixed

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master
