### ISSUE TITLE
rename allow*endUser to require*endUser in the WebResource.InitBuilder 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17147]
In order to clarify what the properties do, we need to rename 
`InitBuilder.allowFrontendUser(bool)` --> `InitBuilder.requireFrontendUser(bool)` 
and  
`InitBuilder.allowBackendUser(bool)` --> `InitBuilder.requireBackendUser(bool)`

**Comment by wezell** [comment]
Please note that there is prelim work on this issue in branch `issue-17147-update-initbuilder`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17210

**Comment by bryanboza** [comment]
Fixed
