### ISSUE TITLE
Unpublished persona should be included in the set persona actionlet on rules 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17153]
- If you have a rule that includes set some persona, and you unpublish that persona, that's breaking the rule 
SC: https://screencast.com/t/qrdX7Wq0

- After you use the quick add persona tool, the personas are added via REST API and leave as unpublished, you can create a personalized version of any page for that persona, but you can't use in the rules engine when you choose a set persona action, this because we include on the list just published persona. 
SC: https://screencast.com/t/mgntKkgds

### Expected behavior
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
We need to change the endpoint from `/NEW` to `/PUBLISH`

**Comment by bryanboza** [comment]
Fixed, now the add persona tool leaves the persona published, the rules actionlet  still showing just published personas in the list
