### ISSUE TITLE
Limit the "login as" list to backend users

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17152]
When showing a list of users to "login as" we need to limit the list only to users that have the Back End User Role.

Additionally, if you try to "login as" a user that is not `user.hasConsoleAccess()`, we should do nothing with the request and spit out a System Notification saying "User {email_address} cannot access the dotCMS backend`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17288

**Comment by jdotcms** [comment]
I have checked the list of login as and the filtering is ok on the ui
I have checked the list on the http://localhost:8080/api/v2/users/loginAsData and the list of user is ok
I have tried to POST a http://localhost:8080/api/v1/users/loginas with a FE user and get a 401, which is ok

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
