### ISSUE TITLE
When no license content types endpoint should NOT return forms or personas

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17163]
### Describe the bug
When there is no enterprise license the content types endpoint is returning `forms` BUT that's an enterprise feature.

### Endpoint
`http://localhost:8080/api/v1/contenttype`

### Steps to reproduce the behavior:
**With NO license**

1.  Go to Content Types
2. In the results locate "Contact Us" or "Persona"
3. That's the error, it should not be in the listing

## Acceptance Criteria

1. Update the endpoint to show results correctly
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17423

**Comment by erickgonzalez** [comment]
Working as it should. Not able to see personas or forms with Community License.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
