### ISSUE TITLE
Get the error message in dot-form

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17166]
As a user, I want more information about the error while try to submit a form so I can fix it.

### Is your feature request related to a problem? Please describe
Right now we're printing in the error the object but some errors came inside the object we need to catch them.

### Describe the solution you'd like
We look for the error message in `errors[0].message` if that doesn't exists we print the whole thing (as it is right now)

### Technical Approach
Try to trigger an error by chaning the code but one error you can trigger is create a form and add one text field that have the "Unique" checkbox selected, submit the form with a text and then try to submit it with the exact same text, since the field is "Unique" the endpoint will fail.

## Acceptance Criteria
1. Print out error mesages
2. Bonus: Please move the error tag after the Submit and Reset button by the end of the form
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by freddyucv** [comment]
Need a new starter to test, currently the form are not render
