### ISSUE TITLE
Unable to select the site/folder field adding content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17169]
We are not able to select the value of this field when you are adding a new content type

### Steps to reproduce the behavior:
1. Login as admin
2. Go to content types portlet 
3. Try to add a new one and make sure you can select the site 

### Expected behavior
We need be able to select this field in order to set the permissions of the content type 
<img width="662" alt="ct1" src="https://user-images.githubusercontent.com/2641437/64376023-84dbc800-cfe4-11e9-8c1e-4bfa6fb7d54a.png">

Tested on master // Postgres // FF

**Comment by wezell** [comment]
This happened because of changes here: #17052 but is now fixed. Please retest.

**Comment by bryanboza** [comment]
unable to reproduce in the last master
