### ISSUE TITLE
Fallback to "no license" screen for forms

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17161]
As a stakeholder, I want to fallback to a feature content when no enterprise license so user knows that Forms is a cool feature for enterprise license.

### Describe the solution you'd like
We might need to catch this in the resolver.

### Mock
![Screen Shot 2019-09-05 at 9 31 02 AM](https://user-images.githubusercontent.com/751424/64356647-7085d400-cfc0-11e9-94bc-99441f74c2bb.png)

All that text is in the language properties.

## Acceptance Criteria
1. Fallback to form feature screen when no enterprise license.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We are not resolving the button key 
<img width="799" alt="key1" src="https://user-images.githubusercontent.com/2641437/64880387-50d05a80-d615-11e9-9cff-dd09a9c0fbe7.png">

**Comment by bryanboza** [comment]
Fixed, now we need to add translations
