### ISSUE TITLE
Link content types entries to contentlets results

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17178]
As a user, I want to see the contentles of a content types easily from content type listing.

### Describe the solution you'd like
Make entries number clickable:

![Screen Shot 2019-09-06 at 11 15 26 AM](https://user-images.githubusercontent.com/751424/64447183-02acdb80-d098-11e9-977b-355b46663a79.png)

And if user clicks for example the one in the "Banner" rows it should link to content search with "Banner" selected:

![Screen Shot 2019-09-06 at 11 17 27 AM](https://user-images.githubusercontent.com/751424/64447215-135d5180-d098-11e9-854d-497db8e55f37.png)

### Technical Approach
Not sure, but might need backend work.

## Acceptance Criteria
1. Link from content type listing to content search.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17216

**Comment by fmontes** [comment]
Need to link host to `/#/c/sites`, host is not ediable so we can use the var name to do this.

**Comment by bryanboza** [comment]
Ok after the discussion with @wezell we need to remove the number of entries and show a `view entries` link, to avoid confusion with the number. 

Also, we need to remove the reorder icon since now we can't reorder by this column

**Comment by bryanboza** [comment]
Some new changes requested here. We should display View ($number)

**Comment by wezell** [comment]
@fishsmith  says just the number

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17367

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Unable to open a piece of content after you use this link. When you click on this link we are redirecting to the content search and display the list of contentlets that you have for the selected content type. But, if you try to select one of these pieces of content we are redirecting to the first available portlet and we are unable to edit or view the selected content. 
SC: https://screencast.com/t/T8SoHlcy3

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
