### ISSUE TITLE
Make dot-binary support "maxFileLength" attribute

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17177]
As a user, I want want to be able to set a "maxFileLength" attr in order to make my content creators more aware of which content use.

### Describe the solution you'd like
With the `maxFileLength` if the user try to upload a file bigger than that we don't allow it and show a message under the field saying: "Your file needs to be XXXXkb max".

Because of the temp resource we use to upload the file will be returning a 500 with the error we can show the error inline in the field and set the field disabled.

### Technical Approach
The user will add the type as a field variable when creating the field in the form:

![Screen Shot 2019-09-06 at 1 34 39 PM](https://user-images.githubusercontent.com/934364/64448190-1ca3e980-d0ab-11e9-8f72-954dc4195048.png)

Then we can get that in the field object, the key will be always: `size` just like the native input.

## Acceptance Criteria
1. Pass size attribute
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
When I reset the form the error in the binary doesn't gets cleaned.

**Comment by bryanboza** [comment]
We are having some errors here: 

- We are showing decimals in the error, we need to show just entire numbers
SC: https://screencast.com/t/Bkdi0raN

- We need to validate the number format from the UI, right now if you add a number with decimals this is breaking the functionality and we are not validating it before save the variable value and this is causing an error uploading new content. 
ST: https://screencast.com/t/Bkdi0raN
SC:https://screencast.com/t/ATPisHdDfDU

**Comment by wezell** [comment]
@bryanboza  we are adding more functionality to the field variables.  These improvements can wait for 5.3

**Comment by bryanboza** [comment]
Ok, I moved the enhancements to the card #17285, but we need to fix those cases here since are totally related to this functionality.

- We are showing decimals in the error, we need to show just entire numbers
SC: https://screencast.com/t/Bkdi0raN

- Also, we are using the wrong way to calculate the size, in case you set the `maxFileLength` to 1000000 in the error we show this like 976kb. 
SC: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/5be5997c-7e65-4844-93ea-7745c6073a62/00000604.png

**Comment by wezell** [comment]
@bryanboza the decimal issue can be another issue - the maxFileLength is in bytes so the conversion is correct.  You can see for yourself here:
https://www.gbmb.org/bytes-to-kb

**Comment by wezell** [comment]
@bryanboza please pass this

**Comment by bryanboza** [comment]
Fixed
