### ISSUE TITLE
Starter sites with scheduled workflow actions cannot be imported

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17173]
If you create a workflow step that includes a scheduled action, and then generate a starter site, the starter cannot be imported due to this constraint, which expects the action to exist before the step can be saved.  I think we should remove this constraint as I could see it affecting PP as well.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/postgres.sql#L2251

Steps:
1- Go to Workflows Portlet and select one.
2- Click over one workflow step.
3- Check **Enable Schedule**, Select one action and set **Scheduled in (seconds)** 
4- Save the workflow step.
5- Go to Maintenance Portlet > Tools Tab.
6- Download Data/Assets
7- Save File
8- Stop dotcms and clean up DB.
9- Move the downloaded file to `tomcat8/webapps/ROOT/`
10- Delete the `Starter.zip` file
11- Rename the downloaded file to `Starter.zip`
12- Start dotcms

**Comment by wezell** [comment]
Actually, it looks like the WorkflowHandler handles this exact case, so PP seems to work.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17256/files

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
