### ISSUE TITLE
Make Binary Fields configurable via field variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17174]
Users always want to limit what types of files can be uploaded and the size of the files that can be uploaded.  We can achieve this by using field variables

For our binary field UI, we should respect the two field variables :

1. `accept` - this is the acceptable mimetypes that the field can take, e.g. */* or image/* or text/*
2. `maxFileLength` - this is the size, in bytes that can be uploaded in the ui.

Keep in mind that these limits are not yet enforced at the API level, only at a UI level

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17175

**Comment by wezell** [comment]
There is some UI funk happening when you upload a file that is too large -
1.  we are not clearing out the field value.
2. if you select another file that is also too large, you get a message and you also get the popup "do you want to change the file name".  That should not happen unless the file is uploaded successfully.

**Comment by erickgonzalez** [comment]
PR for clear out value and avoid message to change the file name if the upload failed https://github.com/dotCMS/core/pull/17363

**Comment by dsilvam** [comment]
Passed Internal QA: We are now clearing out the field when `maxSizeLimit` is violated and not getting the "do you want to change the file name" if you try to upload a new one that also violates the constraint.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
