### ISSUE TITLE
Downgrade webp images to jpeg for safari

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17185]
If you use webp compression for your images, dotCMS should automatically downgrade them to jpegs if the browser does not support the webp format - which means if the browser is safari.

### Notes for documentation
We added a new image "filter" called `Quality` that automatically handles compression.  The filter takes a compression quality `quality_q` between 1 and 100.  When this is used, the image delivered will be compressed as a WebP image unless the requesting browser is Safari, in which case it will be compressed as a jpeg using the value of the `quality_q` .

To use this filter from the `/dA` endpoint, you specify auto compression quality with a url param like `/75q` for 75% quality.  Again, dotCMS will automatically send the correct image based on the visitors browser.

dotCMS now support automatic webp selection when compressing

**Comment by wezell** [comment]
This functionality can be disabled by setting `webp.downgrade.to.jpeg.for.safari=false`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17194

**Comment by dsilvam** [comment]
Passed internal qa: Filter returning jpeg with proper compression when browser is Safari

**Comment by wezell** [comment]
This should also work on iPhones/iPads/mobile safari.

**Comment by wezell** [comment]
PR: #17318

**Comment by erickgonzalez** [comment]
Chrome on ios does not support webp, fix for it: https://github.com/dotCMS/core/pull/17336

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF, Chrome and Safari. Also tested from an iPad device
