### ISSUE TITLE
VisitedUrlConditionlet only works site wide

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17187]
The VisitedUrlConditionlet does not work on a page - it only works if it is enabled site wide.  It is also storing the list of visited urls in session, and we already have this list in session in the clickstream - the rule should use the clickstream data instead.

**Comment by wezell** [comment]
@bryanboza Please test this with a URLMapped url, e.g. something like `/news/american-investors-are-worry-warts`

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Also tested the URLMapped and works fine
