### ISSUE TITLE
Containers.maxContentlet setting does not take personalized content into account

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17181]
1. Create a container and set to `maxContentlets = 1`.
2. Add a contentlet in the container for the default persona.
3. Change personas and try to personalize the page
4. The content you added to the container for the default persona is not displayed for the personalized persona, nor can you add content to the new persona in that container.

This is happening because the container is only set to accept 1 contentlet and thinks it now has 2  contentlets in it, so it is discarding the second contentlet.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17186

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the last master
