### ISSUE TITLE
Add tags field and avatar preview to persona create in edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17198]
As a stakteholder, I want have more fields in the persona create form in order to be able to create more specific personas from the edit page.

### Describe the solution you'd like
1. Use the `autocomplete` primeng component as a field tag, you can use `onKeyUp` when `Enter` key to add tags when doesn't exist in the suggestions
2. Display the preview of the avatar when selected.

## Acceptance Criteria
1. Add tags field and show avatar preview.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
When you have empty value is throwing an error:

![Uploading Screen Shot 2019-09-23 at 12.47.47 PM.png…]()

**Comment by fmontes** [comment]
Can create empty tags:

<img width="562" alt="Screen Shot 2019-09-26 at 10 37 07 AM" src="https://user-images.githubusercontent.com/751424/65707374-a3fcd100-e049-11e9-9e44-7875775c8df2.png">

**Comment by fmontes** [comment]
When hit ENTER in the tag field it submit the form, It shouldn't because we might want to just add a tag

**Comment by fmontes** [comment]
When you enter a `keytag` that exist we disable the save button, throw the error but the button stays disable, we should enable the button if the form is valid and the response from the server is back.

**Comment by bryanboza** [comment]
We are just showing global tags in the autocomplete, then if you create a new persona and add a new tag (newTag) when you try to add another one and use the same tag, we are unable to autocomplete. 
SC: https://screencast.com/t/0Ne0TNKvh2A

Then we have two options here: 
Save the new tags as global tags, or include the site tags in the list

**Comment by fmontes** [comment]
The issue is backend: https://github.com/dotCMS/core/issues/17406

**Comment by fmontes** [comment]
When you use the mouse to select a tag it fails.

**Comment by fmontes** [comment]
We add a "Press enter" to indicate the user how to add the custom tag,

**Comment by bryanboza** [comment]
We need some extra work here: 

- We need to set a max length value here and after this add ... 
SC: https://screencast.com/t/GHDOLRo6ocg

- We have problems adding tags with " (double quote), this breaks the code line and when you try to edit the persona we are unable to see the added tags 
SC: https://screencast.com/t/FrLTy3f3

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes
