### ISSUE TITLE
Upper case letter breaks the query using categories 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17206]
If you have some category that has some space, something like this "new Test", the system is auto-building the variable `newTest`, then if you use this category to filter content, the upper case letter is breaking the query. 

FYI: If you try to get the query we are getting something like this: 
`contentType:ContentTest +(categories:newTest) +deleted:false +working:true`

If you use this in the query tool we are not getting results, but if you try the following, we get the contents.
`+contentType:ContentTest +(categories:new*) +deleted:false +working:true`

### Steps to reproduce the behavior:
1. Login as admin
2. Go to categories 
3. Creta a new category "Test"
4. Add some subcategories "new" && "new Test"
5. Create a new content type and add some category field and set the new category
6. Add a piece of content and add the "new Test" category 
7. Now try to filter the content using this category 

### Expected behavior
We need to be able to filter and show results without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
PR:  https://github.com/dotCMS/core/pull/17217

**Comment by erickgonzalez** [comment]
Working as it should. After creating a category with diff case (test a, Test B, TEST C) we're able to filter ignoring the case e.g `+contentType:Test +(categories:testa)` or `+contentType:Test +(categories:TESTA)`

**Comment by bryanboza** [comment]
Fixed, now this works without problems
