### ISSUE TITLE
OSGI Workflow Actionlet not deleted

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#17203]
### Describe the bug
When deploying the OSGI actionlet plugin it shows on the Sub-Action List and can be added, but when stopping the plugin it does not get removed from the Sub-Action List nor the Actions already added.

### Steps to reproduce the behavior:
1. Upload the com.dotcms.actionlet OSGI plugin.
2. Add the actionlet to an action.
3. Stop the plugin.

### Expected behavior
The actionlet should be deleted from every Action already added and from the Sub-Action List.

The method that is being called by the GenericBundleActivator.java is https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L436

**Comment by wezell** [comment]
Hey, we need to be careful here as subactions can have parameters - and if we delete and recreate them every time, we will lose the configured parameters.  How should we handle this?  Perhaps we just skip the missing subactions when checkin - and maybe send a System Message to admins that there is a missing subaction?  I am open to ideas.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17349

**Comment by jdotcms** [comment]
1) we have added an actionlet via osgi
2) we add the actionlet to an action
3) use the action
4) stop it
5) the references were removed
6) starts again, the actionlet is being able again

**Comment by jdotcms** [comment]
In addition i have restarted the server and the actionlet still there

**Comment by bryanboza** [comment]
Fixed, now we remove the action when you stop or undeploy the plugin
