### ISSUE TITLE
Changing from Preview Mode to Edit Mode loses URLMap

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17202]
Users need to be able to edit URLMapped content in the Edit Mode context.

To reproduce:
1. Browse the demo site in Preview Mode
2. Visit a url mapped page - say a news article
3. Switch to Edit Mode

You lose the URLMapped content that you were viewing and are unable to edit it in context

**Comment by fmontes** [comment]
If you go to: http://localhost:8080/dotAdmin/#/edit-page/content?url=news%2Fu-s-labor-department-moves-forward-on-retirement-advice-proposal

And start moving from EDIT, PREVIEW and LIVE the content of the news item:

![Screen Shot 2019-09-20 at 1 44 27 PM](https://user-images.githubusercontent.com/751424/65354454-c9529080-dbac-11e9-9de6-e9367fb5504a.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17282

**Comment by bryanboza** [comment]
We need some work here: 

When you are in preview mode and navigate to some URLMapped page and then try to edit, we are having an NPE in the logs and we are not able to edit 

SC: https://screencast.com/t/DLnpS8Hc647
ST: https://gist.github.com/bryanboza/67898a4455f7850d16a47456ac565fd6

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
