### ISSUE TITLE
Contentlet.addConstantsToMap() gets called repeatedly

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17214]
This happens for FileAssets or HTMLPages, as the `CONTSTANTS_ADDED` value does not propagate to the FileAsset object when you convert it from a contentlet.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17253

**Comment by erickgonzalez** [comment]
Working as it should, tested publishing/unpublishing file assets, content and HTML pages and nothing was broken with this revert.

**Comment by bryanboza** [comment]
Fixed, everything is working as expected after this change.
