### ISSUE TITLE
Pass down "dot" prefixed field variables as attr to dot-textfield and dot-textarea

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17213]
As a stakeholder, I want give the ability to user to add attributes to the form fields in order so they can custom the behavior of the fields.

### Describe the solution you'd like
A user will add field variables which key is prefixed with `dot:` like `dot:type` and we will pass that as attribute to the internal HTML element of each field.

**The custom elements that have more that one elements we need to see what's the best way to pass this.**

**NOTE:** we need to update `accept`.

### Styles
If the user create a `dot:styles` we don't set that one as att we set it as inline styles for the main element.

## Acceptance Criteria
1. Pass down field variables as attributes and/or inline styles
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we are able to send those parameters via filed variables
