### ISSUE TITLE
New Page Asset: The friendly name is not auto-generated

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17221]
### Describe the bug
On previous versions, the field `friendlyName` was set automatically after typing the Page Title

### Steps to reproduce the behavior:
Create a new Page Asset filling only these fields: Title, Url, Host and Template

### Expected behavior
The field `friendlyName` should be autogenerated automatically when the Page Title is set

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17222

**Comment by erickgonzalez** [comment]
Working as it should. `Friendly Name` field is auto-generated

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
