### ISSUE TITLE
When related content is pulled from the index, duplicates are returned for multilingual content

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17233]
### Describe the bug
When a user creates a multilingual content with relationships and the property `GET_RELATED_CONTENT_FROM_DB` is set to `false` or the relationship is legacy, related content is listed twice

### Steps to reproduce the behavior:
**Scenario 1:** 
1. Set `GET_RELATED_CONTENT_FROM_DB=false` in the dotmarketing properties file and restart the server
2. Create two content types: Character and Movie
3. Add a one-to-many relationship field from Movie to Character
4. Create a Character content in the default language (English)
5. Create a multilingual Movie content (e.g.: English and Spanish) and relate them to the Character created in 4)
6. Open the Edit Contentlet portlet to modify any of the Movie content created in 5) and see the dupe related records

**Scenario 2:** 
1. Set `GET_RELATED_CONTENT_FROM_DB=true` or use the default value (true) 
2. Edit any News content adding a new language version and include some related content
3. Open the Edit Contentlet portlet to edit the News content in 2) and see the dupe related records

### Expected behavior
Related content should not be duplicated on multilingual content

**Comment by nollymar** [comment]
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/680

**Comment by nollymar** [comment]
Note to QA: Please consider to test adding/removing/editing/listing related content using legacy relationships (case 1) and tuning off this flag `GET_RELATED_CONTENT_FROM_DB ` (case 2)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
