### ISSUE TITLE
Problems importing bundles from previous versions

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17239]
Related to #17052 

We are having problems importing bundles that comes from the previous version, after the last changes in the related card, now we have the following error and we are unable to import the bundle. 

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to publish queue and try to import the attached bundle 
3. Check the log file 

### Attached files 
Here the bundle 
[ba7fdd66-5769-45f5-80d0-84ab14c109ba.tar.gz](https://github.com/dotCMS/core/files/3607498/ba7fdd66-5769-45f5-80d0-84ab14c109ba.tar.gz)

### Expected behavior
We need be able to import that bundle without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
Fixed.

PR Core: https://github.com/dotCMS/core/pull/17290
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/684

**Comment by erickgonzalez** [comment]
Bundle attached imported Successfully without issues.
<img width="1385" alt="Screen Shot 2019-09-19 at 4 06 11 PM" src="https://user-images.githubusercontent.com/5278970/65284651-72d74a80-daf7-11e9-8424-fbaae6774c89.png">

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to import this bundle without problems
