### ISSUE TITLE
Field Variables ket should take special char

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17230]
As a user, I want to be able to create field variables keys with special chars like: `dot:type` or `dot-type`

### Is your feature request related to a problem? Please describe
Right now if you try to create a field variables key with `dot:type` the endpoint returned camelcased `dotType`.

## Acceptance Criteria
1. Allow create field variables keys with special chars
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
we do not need to run the field variables through any transformations or camel casing we just need to check for uniqueness and if the key exists, update otherwise insert.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17314

**Comment by erickgonzalez** [comment]
Working as it should, now it let you create Field Variables with special chars as `- : @ # $ % & ( ) _` and updates if the variable already exists.

**Comment by bryanboza** [comment]
Fixed, now we support the special characters on those variables
