### ISSUE TITLE
ContentType endpoint creates invalid entries on the workflow_action_mappings when called several times

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#17238]
When calling the CT endpoint with a URL like `{{serverURL}}/api/v1/contenttype` 
And with a body like 

`{
   "defaultType":false,
    "fixed":false,
    "system":false,
    "clazz":"com.dotcms.contenttype.model.type.ImmutableFileAssetContentType",
    "description":"",
    "host":"48190c8c-42c4-46af-8d1a-0cd5db894797",
    "folder":"SYSTEM_FOLDER",
    "name":"MyFileAsset",
    "systemActionMappings":{"NEW":"7309ed0d-cbf9-4b02-aa3c-8b599fd2a718"},
    "workflow":["d61a59e1-a49c-46f2-a929-db2b4bfa88b2","77a9bf3f-a402-4c56-9b1f-1050b9d345dc"]	
}`

a few times in a row causes 
invalid entries to be created in the table workflow_action_mappings

the content type is reused adding a numeric sequence like:

MyFileAsset
MyFileAsset1
MyFileAsset12
MyFileAsset123

![Screen Shot 2019-09-12 at 3 16 27 PM](https://user-images.githubusercontent.com/37148755/64821542-5162e580-d570-11e9-9b04-27e0c96b5dbf.png)

It's a POST probably it shouldn't attempt to add any new entry if the composite key finds a conflict.

**Comment by jgambarios** [comment]
Closed as this is the expected behaviour.
