### ISSUE TITLE
Upgraded dotCMS - Admin can't login

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17243]
Start with a dotCMS 4.3.2
Upgrade to latest master
Try to login to the backend as admin@dotcms.com/admin - login fails
```
10:04:56.746  INFO  util.SecurityLogger - class com.dotcms.cms.login.LoginServiceAPIFactory$LoginServiceImpl : User admin@dotcms.com / dotcms.org.1 login has failed. User does not have the Back End User Role or any layouts -- ip:0:0:0:0:0:0:0:1,user:null
1
```
This happens because for the admin user, 
`user.hasConsoleAccess() == false`

**Comment by wezell** [comment]
This needs testing - basically we need to test to make sure people can login to upgraded dotCMS instances

**Comment by fabrizzio-dotCMS** [comment]
tested against dotcms-4.3.2-3Cinteractive-20180418124436 mySQL and the problem is not present.

Once I reset the password by doing 
`update  user_ set passwordencrypted='0', password_='admin' where userid='dotcms.org.1';`
It allows me to log in with no problem.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17379

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the main problem
