### ISSUE TITLE
Problems starting an instance with existing database after deployWarTomcat

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17247]
We are having problems when you update your repo and try to start again with the same databse//assets. We are unable to load the login page and the system is getting stuck. 

So far no error on logs, neither console. 

### Steps to reproduce the behavior:
1. Login as admin
2. Start your server 
3. Shutdown 
4. Update your repo and _deployWarTomcat_
5. Start the server again 
6. Try to login 

### Expected behavior
We need be able to reuse the database//assets without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by dsilvam** [comment]
```
at com.dotmarketing.quartz.QuartzUtils.startSchedulers(QuartzUtils.java:777)
      at com.dotmarketing.init.DotInitScheduler.start(DotInitScheduler.java:702)
      at com.dotmarketing.servlets.InitServlet.init(InitServlet.java:155)
```

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/17266
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/681

**Comment by nollymar** [comment]
**Note to QA:** Please test deploying with/without license including an existent DB and a fresh installation

**Comment by erickgonzalez** [comment]
Working as it should now we're able to start dotcms with an existing DB.

**Comment by bryanboza** [comment]
Still happening, we need some work here

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17301

**Comment by erickgonzalez** [comment]
Tested deploying a couple of times with an existing DB and had no issues login or doing normal stuff (create content or content types, ran a reindex, flush cache, publish a page).

**Comment by bryanboza** [comment]
Fixed, after update and deploy some times, I'm unable to reproduce
