### ISSUE TITLE
Unable to see the Events page

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17252]
When you try to open the Events page we are unable to see the content, we are showing as a blank page, but if you try to call the same page using the render API, we are getting the contents that have the page. 

### Steps to reproduce the behavior:
1. From FE try to call this page 
`/news-events/events/`
2. Now login into the backend and try to open the same page 
`Site Browser --> news-events --> events --> index` 

### Expected behavior
We need to render that page without problems 

### Screenshots
FE: https://screencast.com/t/BUNrPp2U5tZ
BE: https://screencast.com/t/9faDBKMb8DJ

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by wezell** [comment]
This will be working in the new starter.
