### ISSUE TITLE
Only one approver sees 'Four Eyes' task in the task list. 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17250]
### Steps to reproduce the behavior:

STEP 1:
I created a group on Demo called "Approver" and added 4 users. I granted near-admin-level permissions to the group and added 4 Users:

​
![image](https://user-images.githubusercontent.com/49727631/64881565-b5dd7d80-d620-11e9-98a3-130de926962a.png)

![image](https://user-images.githubusercontent.com/49727631/64881576-bb3ac800-d620-11e9-8ca0-807ae662788a.png)

​

STEP 2: 
Edited Workflow to include "Four Eyes" approval and added the Role Key to the step:

​
![image](https://user-images.githubusercontent.com/49727631/64881583-c0981280-d620-11e9-9ffe-c7c146b1260c.png)

STEP 3:

Logged in as a contributor user and edited a file "photoshop-keyboard-shortcuts.pdf" and clicked "Save As Draft"

​
![image](https://user-images.githubusercontent.com/49727631/64881591-c55cc680-d620-11e9-84b8-f41b1c914e37.png)

STEP 4:

Task only shows up for one member.

​
![image](https://user-images.githubusercontent.com/49727631/64881607-cd1c6b00-d620-11e9-9025-927bdbbf1e8a.png)

![image](https://user-images.githubusercontent.com/49727631/64881615-d1488880-d620-11e9-9241-023bcdf69e36.png)

![image](https://user-images.githubusercontent.com/49727631/64881628-d60d3c80-d620-11e9-861c-9f6562e501c0.png)

![image](https://user-images.githubusercontent.com/49727631/64881636-d9a0c380-d620-11e9-9347-c59b803e1e66.png)

**Expected Behavior:**
"Four-Eyes" approval should show up in the Tasks list of every User in the approval group as identified by the role Key.

**Actual Behavior:**
Only one of the people in the group gets an entry in their tasks. 

### Desktop (please complete the following information):
 - OS: n/a
 - Browser chrome/FF
 - Version n/a

**Comment by craigWagner99** [comment]
Can we get an update on this? We're seeing this more often as more customers utilize Four Eyes Approval...

**Comment by wezell** [comment]
We can test and merge these changes in 5.2.1 - even though they are not perfect, we will be in a better state than we are now.
