### ISSUE TITLE
FileAssets do not cache FS metadata

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17269]
When serving files from the file system, be they `#dotParsed` or as CSS, images, VTLs or whatever, dotCMS always retrieves the `file.getName()` and the `file.getLength()` from the filesystem in order to build the response.  This causes unnecessary fs stat calls to file system metadata that can cause performance issues when the files are being served by an uncached remote NFS mount.  We need to cache those values in the contentlet so we do not do unnecessary stats and FS operations across network mounts.

**Comment by wezell** [comment]
### To test:
1 Take this velocity:
[get.vtl.txt](https://github.com/dotCMS/core/files/3769271/get.vtl.txt)

2.  upload it as a file called `/application/apivtl/images/get.vtl`

3. from a command line, watch the file on the file system (under your `/assets` directory) where {PID} is the pid of your dotcms

`sudo fs_usage {PID} | grep 60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg`

4. Now hit the the url `http://localhost:8080/api/vtl/images`

5. You will see multiple file stat64 calls, this is reading file metadata off the FS and this is what we should cache when we are able to.  On a slow network mount or NFS, these hits can get expensive
```
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000021   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000009   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000011   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000009   java
15:48:16  rename            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000202   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000014   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000009   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000008   java
15:48:16  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000009   java
15:48:16  open              60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000024   java
15:48:27  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000033   java
15:48:27  stat64            60e-4986-bb79-16b692827441/fileAsset/kim-holtermand-reflections-2560x1440.jpg    0.000021   java
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17549

**Comment by jdotcms** [comment]
test done!
I have changed the sort order and the invalidation works fine.
I have renamed on the webdav and invalidation works fine

After the invalidation, the file is not being fetch anymore.

Note: the only place I have seen the file is not recovery from the cache is on webdav:

for instance on the cyberduck you can click on refresh button how the file is being fetch:

```
11:45:28  stat64            OOT/assets/3/2/32977bcd-88bd-446c-960d-cf0bcff46bd5/fileAsset/char_mander.jpg    0.000021   java        
11:45:28  stat64            OOT/assets/3/2/32977bcd-88bd-446c-960d-cf0bcff46bd5/fileAsset/char_mander.jpg    0.000007   java   
```
