### ISSUE TITLE
Remove sort feature in content types entries column

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17263]
### Describe the bug
The column of entries have the arrow for sorting but is not working for that column

### Steps to reproduce the behavior:
1. Go to Content Types
2. Click on the arrow or row of "Entries"
3. It should sort the result by that column but is not

### Expected behavior
We should not sort by entries

## Acceptance Criteria

1. Remove the sorting feature from the entries column
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by erickgonzalez** [comment]
Entries column not longer have sorting functionality.
