### ISSUE TITLE
LDAP auth broken

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17264]
After changes here: https://github.com/dotCMS/core/commit/2aba8862612fa83d0e19f2d05d67836f0e39a0e9#diff-9e87880a6863e26a534a0dbd4bdc84baL106, the LDAP authentication is broken. 

Steps to reproduce:
1. Configure LDAP server and add a LDAP user
2. Configure dotCMS to use LDAP
3. Change dotCMS to use `userid` as auth method (maybe not needed)
4. Try to login with your LDAP user

Authentication failed.

**Comment by dsilvam** [comment]
Back-end role assigning: https://github.com/dotCMS/enterprise-2.x/pull/682/files
Move consoleAccess validation after auth logic https://github.com/dotCMS/core/pull/17270/files

**Comment by dsilvam** [comment]
Passed Internal QA: LDAP user able to login properly. Back-end role assigned if any of the existing roles for the user has layouts.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2 // openldap
