### ISSUE TITLE
Need allow sort forms by "entries"

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17262]
From the FORM portlet, we nee to allow order the list by `entries`, rigth now e have the icon on the header of the column but this is not working 

### Steps to reproduce the behavior:
1. Login as admin
2. Go to Marketing --> Forms 
3. Try to order the form list by entries

### Expected behavior
We need to allow order without problems 

<img width="1682" alt="forms" src="https://user-images.githubusercontent.com/2641437/64974894-034d2b00-d86b-11e9-85f5-61d79d1af9aa.png">

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/17263
