### ISSUE TITLE
App crash when try to edit a page that doesn't exist

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17271]
### Describe the bug
When you try to edit a page that doesn't exist there are several JavaScript error which cause the app to crash and you have to reload the page.

### Steps to reproduce the behavior:
1. Go to edit a page in [this link](http://localhost:8080/dotAdmin/#/edit-page/content?url=%2Fabout-us%2Ftesting&language_id=1)
2. You get the popup but also in the console you can see some JS errors.

### Expected behavior
We should show the popup but prevent the app to crash.

### Screenshots
![Screen Shot 2019-09-17 at 11 49 02 AM](https://user-images.githubusercontent.com/751424/65066199-2944ff00-d941-11e9-8c17-77d6683b6ecb.png)

## Acceptance Criteria

1. Prevent the app to crash when try to edit a page that doesn't exist
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, now we show the pop-up and we are able to continue navigating without problems
