### ISSUE TITLE
Persona Filter When Personalize Page not Working

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#17283]
### Describe the bug
If you try to filter a persona when trying to personalize a page is not returning results.

### Steps to reproduce the behavior:
1. Create a new persona CT.
2. Add new personas to the created CT.
3. Try to find the persona created when personalizing a page.

### Expected behavior
The personas matching the filter must be returned.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17284

**Comment by dsilvam** [comment]
Passed internal QA: Able to find the persona contentlet of the custom persona type via the filter on personalizing the page

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
