### ISSUE TITLE
Navigating should close the persona selector

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17299]
If you open the persona selector and then click off it to the page and navigate to another page, we should close the persona selector when we bubble up the navigation event (just like we reset to preview mode)

![navigating.gif](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/ed31da84-d2a2-43ec-9b13-a6be759d8d95)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
