### ISSUE TITLE
Unable to add images to pages from the tinyMCE editor

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17309]
If you are adding a new piece of content, and you add an image in the tinyMCE editor, we are unable to render the image and we are just showing the name of the asset. 

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new page
3. Add a new generic content 
4. Try to add a new image from this editor 

### Expected behavior
make sure you are able to see the image without problems from preview and live mode 

### Screenshots
SC: https://screencast.com/t/pcztD4dcUOjP

### Desktop (please complete the following information):
Tested on master // postgres // FF

**Comment by wezell** [comment]
This issue exists in 5.1.6 if not further back. The file name is getting truncated if it is too long and that is breaking the pathing.

**Comment by wezell** [comment]
PR: #17310

**Comment by bryanboza** [comment]
Fixed, now we are able to add images to this editor without problems
