### ISSUE TITLE
Error in log when saving a container or template

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17302]
When a container or template are saved, this exception is thrown in the log:
https://gist.github.com/nollymar/2a58148c5c62f05c240c7b8ac80ffc80

The validator-rules.xml must be modified to be compliant with the struts dependency.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17303

**Comment by erickgonzalez** [comment]
Working as it should. Error no longer shows at the logs.

**Comment by bryanboza** [comment]
Fixed, now we have no errors in the log
