### ISSUE TITLE
Trial License notifications repeating on same page

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17319]
Reproduced on dotCMS 5.1.6

Its ok to place a trial license expiration on each page or every few minutes or something, but they are currently stacking every few seconds vertically making page editing really difficult.  This is a big problem for potential clients who are trying out dotCMS for the first time with a 30 day trial license and these notification pop-up constantly while they are trying to evaluate dotCMS.

We should fix this asap: https://www.dropbox.com/s/osr2xoeawbenqke/TrailLicenseNotifications.mp4?dl=0

**Comment by wezell** [comment]
I believe this is happening because you are not using an API key to authenticate API calls, you are passing a username and password, which is doing a user login, which is firing the notification.
