### ISSUE TITLE
Forward Tuckey Rule not working

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#17329]
### Describe the bug
When using a tuckey rule `type="forward"`, dotCMS redirects to 404.

### Reproducible:

dotCMS 5.1.6 (latest release)

### Steps to reproduce the behavior:
1. Create a page: `/myfolder/mypage` and put some content.
2. Usign a static or dynamic plugin, set up this rule:
```
<rule>
	<from>^.*/tuckeytest/(.*)$</from>
		<to type="forward">/myfolder/mypage</to>
</rule>
```
3. Hit: `<IP:PORT>/tuckeytest/dummy`
4. dotCMS will redirect to 404

### Additional context
Client ticket: https://dotcms.zendesk.com/agent/tickets/99221

## Acceptance Criteria

1. Multilanguage
2. Unit test
3. **_Test Using static and dynamic plugins_**

**Comment by wezell** [comment]
I believe you can make this work if your rule sets the attribute of `CMS_FILTER_URLMAP_OVERRIDE` to the path you want to forward to.
