### ISSUE TITLE
Angular "Add to Bundle" does not handle names typed in.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17323]
1. From the content listing screen, right click and add a piece of content to new bundle called "test123" by adding something to it and typing the name.
2. Go to the content types portlet, select a content type and click on the little dots and select "Add to Bundle" . Instead of selecting the name from the dropdown, clear the selection and type "test123".  Click Add
3. Go to the Bundle portlet and take a look.  You will see that you now have 2 bundles with the same name

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17327

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master
