### ISSUE TITLE
DB error trying to add twice a piece of content in to a page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17328]
We have a DB error when you try to add twice a piece of content into a page. We have the validation at UI level, but after showing the error we are sending the query to the DB

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page
3. Add a new piece of content 
4. Try to add again the same piece of content 

### Expected behavior
After showing the error at UI level we need come back to edit mode normally 

### Screenshots
SC: https://screencast.com/t/Aak3QrXSdw
ST: https://screencast.com/t/Aak3QrXSdw

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by fmontes** [comment]
This was also failing adding forms, fixed to.

**Comment by bryanboza** [comment]
Still happening with forms
SC: https://screencast.com/t/UxMWlAO2a

**Comment by fmontes** [comment]
Redeploy and try again

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
