### ISSUE TITLE
Broken Persona Images when when selecting non-default language

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#17320]
### Describe the bug
Images associated with personas are lost when switching to a different language other than English.

### Steps to reproduce the behavior:
The bug isn't evident because of the images being cached by the browser. In order to see it use chrome dev-tools 

1. Go to site-browser select a page. Create another version of that same page in Spanish.
2. Now Personalize that page.
3. Keep Chrome Dev tool opened to by-pass browser cache.
4. Select Spanish on the language selector
5. Select a different persona using the Persona drop-down selector. Notice how all persona images are gone.

Another way to test it is.. extracting the Persona image URL and open it in a separate tab then change the language on the language selector on the site-browser personalized page view. 

After making a change on the language selector refresh the tab. You'll see the image shows up when the selected language is English but a 404 comes up for Spanish.

### Expected behavior
The Images should be available regardless of the language selection

### Screenshots

![zacatapum](https://user-images.githubusercontent.com/37148755/65437174-909afd00-dde0-11e9-9a91-3eb8e4e15091.gif)

https://www.screencast.com/t/rtRctzNICdbu

### Desktop (please complete the following information):
On a further look, I was able to determine that the request is attended by the ShortServlet
which uses `findContentletByIdentifierOrFallback` 

The Image look-up fails on the following block
`  // if we are using the fallback, and it is not allowed, return empty
            if (fallback && tryLanguage != defaultLanguageId && !contentlet.getContentType().languageFallback()) {
                return Optional.empty();
            }` 

Apparently the `languageFallback` property isn't set for the PersonaContentType

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17322

**Comment by jdotcms** [comment]
the issue is not longer happening, I have open a new clean session. Open the Spain version and the issues are 200 on the chrome tools

**Comment by bryanboza** [comment]
Fixed, unable to reproduce
