### ISSUE TITLE
RULES Tag Actionlet: if you only add a single tag, the tag control breaks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17330]
### Describe the bug
When you add only one **tag** to a rule the controls breaks

### Steps to reproduce the behavior:
1. Go to rules
2. Create a rule and add a condition of tags
3. Add only ONE tag
4. Reload rules and it shows the error:

### Expected behavior
It should handle the tags correctly

### Screenshots
![Screen Shot 2019-09-23 at 11 59 58 AM](https://user-images.githubusercontent.com/751424/65450128-b1bc1780-ddf9-11e9-814a-0a82c99000b3.png)

## Acceptance Criteria

1. Fix the rules tags component
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgrres // FF
