### ISSUE TITLE
RULE Prevent add conditions and actions until the rule is created

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17331]
### Describe the bug
The UI allows you to create conditions and actions before add the name of the rule. Adding the name of the rule is what's trigger the rule creating (hitting the endpoint).

### Steps to reproduce the behavior:
1. Go to rule
2. Click on add rule
3. See all the fields and instead of adding the name of the rule start adding conditions and actions
4. See the error and even the requests errors

### Expected behavior
We need to keep collapsed the module so user don't have access to the components of conditions and actions until the rule gets created.

## Acceptance Criteria

1. Keep the rule closed until user type the name of the rule and the rule get's created
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need some work here: 

- If you add a new rule and add some name after you expand the rule and add conditions and actions if you remove the name, we are allowing keep the rule expanded, we need to collapse again 

- If you do the same thing again and try to enable the rule without a name, we allow save the rule and we set the name previously added, we need to validate all the data before save and show an error if some required value is not typed 

- We are saving the rule just typing the name, then we are able to set blank rules. We need not save the rule until you fill all the fields and enable it

**Comment by wezell** [comment]
@bryanboza please move these to a new card - the issue this was to address wasn't to prevent having a rule with a blank name, but being able to edit conditions and actions without there being a parent rule with an id.  You can see this on 5.1.6/demo.dotcms.com when you add a rule, skip entering anything in the name and just start editing the conditions and actionlets

**Comment by bryanboza** [comment]
> @bryanboza please move these to a new card - the issue this was to address wasn't to prevent having a rule with a blank name, but being able to edit conditions and actions without there being a parent rule with an id. You can see this on 5.1.6/demo.dotcms.com when you add a rule, skip entering anything in the name and just start editing the conditions and actionlets

Moved to a new card #17408

**Comment by bryanboza** [comment]
The main problem was fixed.
