### ISSUE TITLE
Unable to display the personalized version of a page as some specific device 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17332]
In edit mode, when you select some device, we are resetting the selection of all the other dropdowns, then we are unable to preview some specific version  of the page in some specific device 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page 
3. Create a new personalization of this page to some specific device 
4. In edit mode try to see this version for iPad 

### Expected behavior
We need be able to display the personalized version of the page using the filters 

### Screenshots
SC: https://screencast.com/t/1SH4YrMXia

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17361

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. New related card here #17380
