### ISSUE TITLE
Edit mode problems using the What's changed feature 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17337]
If you are editing some page and enable the "What's changed" feature, you need manually disable that before moved to some of the edit mode tabs "edit, preview, live" this because if not we are not able to edit the page. 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page 
3. Create a personalized version for some persona 
4. Now enable the what's changed 
5. Change to the edit tab 

### Expected behavior
We need auto-disable the what's changed before moves to any other tab 

### Screenshots
SC: https://screencast.com/t/1QVo7NLZRoM

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by freddyucv** [comment]
When set the waht changed check this happens:

<img width="1368" alt="Screen Shot 2019-09-25 at 10 29 05 AM" src="https://user-images.githubusercontent.com/10408015/65620768-a8f54e00-df7f-11e9-9ce5-2a68f820ea12.png">

**Comment by bryanboza** [comment]
- We are not refreshing the content of the page when you enable the what's changed and then select another persona

**Comment by wezell** [comment]
What should happen is that when you select a new persona, the what's changed should be unchecked automatically.

**Comment by fmontes** [comment]
Ok, what's change hidden when a persona is selected.

**Comment by bryanboza** [comment]
Fixed, for now we disable this functionality
