### ISSUE TITLE
WorkflowAPIImpl.findActionAvailableOnSchemes Concurrent Modification Exception

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17335]
If you try to upload some theme to a new site via WebDAV, we are showing this error multiple times 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new blank site 
3. Add a new folder /application/themes
4. try to upload the attached folder to the file 

Here the files: 
[theme.zip](https://github.com/dotCMS/core/files/3644015/theme.zip)

**FYI: Unable to reproduce in previous versions**

### Expected behavior
We need to be able to upload those files without problems 

### Screenshots
Here the error: https://gist.github.com/bryanboza/c1a34cbaf8d80f2884df369dd6ec1ee1 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17346

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. After the changes now I'm unable to reproduce the error
