### ISSUE TITLE
Blank page after add menu links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17347]
We have a redirection problem after you add a menu link, we are not able to redirect again to the site browser and leave a blank page.

FYI: No errors in the log, neither console

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to site browser and add a menu link
3. Make sure we are redirecting to the site browser again 

### Expected behavior
We should be able to add menu links without problems 

### Screenshots
SC: https://screencast.com/t/2Wl9vpsmj

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17447

**Note to QA:** Please verify all buttons on the Edit Menu Link portlet are working well

**Comment by dsilvam** [comment]
Passed Internal QA: Properly redirecting on every option available from the Edit / New Menu Link.

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by dsilvam** [comment]
Passed Internal QA Release. Properly redirecting to Site-Browser on _Save_, _Save & Publish_ and _Cancel_ actions.
