### ISSUE TITLE
Content Search screen sidebar fields get cut off

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#17345]
### Describe the bug
Some fields in the search sidebar in the Content Search screen get cut off:

### Steps to reproduce the behavior:
1. Create a content type with at least one Select field that has long values.
    * User Searchable.
    * I used the following in the "Value" property to test:
            `|`
            `This is a long select value|LongValue`
            `Shorter|ShortValue`
2. Open the Content Search screen.
3. Click the `Advanced` button on the sidebar.
    * **Result (correct):** The Select field is shown without being cut off.
    * ![image](https://user-images.githubusercontent.com/13456955/65527580-bd661780-dea7-11e9-8dda-06e54f4f8230.png)
4. Create enough additional fields to ensure that the search sidebar in the Content Search screen will have a vertical sidebar.
    * With a 1920x1080 resolution I had to create 7 fields, but will vary with screen resolution.
5. Open the Content Search screen.
6. Click the `Advanced` button on the sidebar.
    * **Result:** The drop-down arrow/button on the right-side of the Select field will be cut off.
    * ![image](https://user-images.githubusercontent.com/13456955/65526953-c2769700-dea6-11e9-80cd-eb410a6d86a1.png)

### Expected behavior
The sidebar should be sized wide enough to prevent the Select field from being cut off when the scroll bar is displayed.

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome 76.0.3809.100
 - dotCMS Version: 5.1.6 (demo)

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master
