### ISSUE TITLE
Edit image window looks cut 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17356]
We have a problem displaying the edit image window when you are editing some content

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to site browser --> resources --> images
3. Open some image and try to edit 
4. Make sure the edit window looks ok 

### Expected behavior
We need to display this window without problems 

### Screenshots
https://screencast.com/t/HeyS4i1t

### Desktop (please complete the following information):
tested on master // Postgres // FF

**Comment by fmontes** [comment]
<img width="1509" alt="Screen Shot 2019-09-30 at 9 54 06 AM" src="https://user-images.githubusercontent.com/751424/65895208-5396b380-e368-11e9-911d-f454bc9a1a1c.png">

Make the right column grow OR make the content scroll.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
