### ISSUE TITLE
NavCache do not refresh when copying a page with "show on menu"

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17353]
1. Open the site browser and preview the "About Us" page in edit mode.  Click the "About Us" menu dropdown and see that it shows 3 pages,  About Us, Locations and Our Team
2. Back in the site browser, right click on "About Us" and select "copy" . The page copies - though it might take a refresh b/c of the defer but that is ok.  Now you have a page called "index_copy"
3. Preview the "About Us" page again and click the menu - it has not changed.  What you should have is 2 "About Us" entries in the menu.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17472

**Comment by bryanboza** [comment]
We need to wait for this fix in order to test: https://github.com/dotCMS/core/issues/17483#issuecomment-544707041

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 and now we are showing the copy in the menu too

**Comment by dsilvam** [comment]
Passed Internal QA Release: copied page with show on menu properly showing on menu.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
