### ISSUE TITLE
Contentlet 404Cache not getting populated

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17377]
This is important in a real world environment. When you do a contentlet.find(inode), we need to cache the 404 response so we do not continually do unnecessary hits to the database.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17462

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed
