### ISSUE TITLE
Trying to go to a URLMap with 2 levels directly, while logged in gives you a 404

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17371]
1. Create a content type with a urlmap that has more than one matching field
2. Create a content object and show that you can navigate to it.
3. Try to hit that url directly (while still in edit mode) it.  It fails.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/commit/20ec348ec50a51f832986bf229c9bc2f9e80fab4

**Comment by alfredo-dotcms** [comment]
When hitting the URL directly in the browser, the page is loaded on `Preview`, but then when you switch to `EDIT` tab,  there's an error that breaks the app

![image](https://user-images.githubusercontent.com/37185433/65993499-9d59c980-e44e-11e9-8d5e-15e1fe9e37f1.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17416

**Comment by freddyucv** [comment]
we found this bug:

- Create a content type with a urlmap that has more than one matching field
- Create a content and just save (not publish it) object and show that you can navigate to it.
- Hit that url directly (it open the edit-page portlet)
- The Live botton is enabled, though you don't have a live version for that content.

The LIVE button should be disabled

PR: https://github.com/dotCMS/core/pull/17416

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.2 // Postgres... Unable to reproduce
