### ISSUE TITLE
Minor Relationship fixes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17385]
1. When we call the $dotcontent.pullRelated, we should pass in live=true so we can preview what the content looks like when rendered
2. We need to prevent an uncaught NPE when writing out our error messages in our catch clauses.
3. Our log is too noisy when there is a bad velocity pull

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17386

**Comment by erickgonzalez** [comment]
Tested Working as it should. Less noise in the logs, pullRelated shows content.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
