### ISSUE TITLE
Content Type Edit button stops working after removing a workflow action

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#17391]
### Describe the bug
Once you have added a Default action to the ContentType and then getting it removed 
The Content-Type Edit Window becomes useless. 

### Steps to reproduce the behavior:
1. Go to the workflows portlet and create a new one (Let's say you name it `Custom WF`). Then add a new step to it. Add an action to that step. And add an actionlet to that action. 
2. Now go to the Content types Portlet and select a Content-Type. Hit the Edit button. On the edit, dialog select the `Custom WF` you created. Then select and add the action on that WF as the default action for the selected CT. 
3. Hit Save and verify the CT now holds the assigned default action.
4. Now load again the workflows portlet and edit the `Custom WF`. load the Step and remove the action that was created previously.
5. Go back to the Content-Types portlet select the same CT you just modifed and now hit Edit again. The Button becomes useless. And The whole CT portlet stops working.  

### Expected behavior
Once an action is removed from a Workflow any CT that previously had the actions as a default should return to its default state.

### Screenshots
![zacatapum](https://user-images.githubusercontent.com/37148755/65804658-e6083e80-e13f-11e9-9318-301c12b83aff.gif)

**Comment by fabrizzio-dotCMS** [comment]
there's a javascript error:

`ERROR TypeError: Cannot read property 'id' of null
    at e.getActionIdentifier (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at e.initFormGroup (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at e.ngOnInit (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at vendor.89fd12df6ac20169677e.js:1
    at vendor.89fd12df6ac20169677e.js:1
    at Mv (vendor.89fd12df6ac20169677e.js:1)
    at ty (vendor.89fd12df6ac20169677e.js:1)
    at Object.updateDirectives (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at Object.updateDirectives (vendor.89fd12df6ac20169677e.js:1)
    at Dv (vendor.89fd12df6ac20169677e.js:1)
_p @ vendor.89fd12df6ac20169677e.js:1
e.handleError @ vendor.89fd12df6ac20169677e.js:1
(anonymous) @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
e.run @ polyfills.ada2932e2114d304452b.js:1
e.runOutsideAngular @ vendor.89fd12df6ac20169677e.js:1
e.tick @ vendor.89fd12df6ac20169677e.js:1
(anonymous) @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
onInvoke @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
e.run @ polyfills.ada2932e2114d304452b.js:1
e.run @ vendor.89fd12df6ac20169677e.js:1
next @ vendor.89fd12df6ac20169677e.js:1
o @ vendor.89fd12df6ac20169677e.js:1
t.__tryOrUnsub @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t._next @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t.emit @ vendor.89fd12df6ac20169677e.js:1
Lh @ vendor.89fd12df6ac20169677e.js:1
Oh @ vendor.89fd12df6ac20169677e.js:1
onInvokeTask @ vendor.89fd12df6ac20169677e.js:1
t.invokeTask @ polyfills.ada2932e2114d304452b.js:1
e.runTask @ polyfills.ada2932e2114d304452b.js:1
e.invokeTask @ polyfills.ada2932e2114d304452b.js:1
m @ polyfills.ada2932e2114d304452b.js:1
b @ polyfills.ada2932e2114d304452b.js:1
vendor.89fd12df6ac20169677e.js:1 ERROR Error: formGroup expects a FormGroup instance. Please pass one in.

       Example:

       
    <div [formGroup]="myGroup">
      <input formControlName="firstName">
    </div>

    In your class:

    this.myGroup = new FormGroup({
       firstName: new FormControl()
    });
    at Function.e.missingFormException (vendor.89fd12df6ac20169677e.js:1)
    at t._checkFormPresent (vendor.89fd12df6ac20169677e.js:1)
    at t.ngOnChanges (vendor.89fd12df6ac20169677e.js:1)
    at vendor.89fd12df6ac20169677e.js:1
    at vendor.89fd12df6ac20169677e.js:1
    at Mv (vendor.89fd12df6ac20169677e.js:1)
    at ty (vendor.89fd12df6ac20169677e.js:1)
    at Object.updateDirectives (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at Object.updateDirectives (vendor.89fd12df6ac20169677e.js:1)
    at Dv (vendor.89fd12df6ac20169677e.js:1)
_p @ vendor.89fd12df6ac20169677e.js:1
e.handleError @ vendor.89fd12df6ac20169677e.js:1
(anonymous) @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
e.run @ polyfills.ada2932e2114d304452b.js:1
e.runOutsideAngular @ vendor.89fd12df6ac20169677e.js:1
e.tick @ vendor.89fd12df6ac20169677e.js:1
(anonymous) @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
onInvoke @ vendor.89fd12df6ac20169677e.js:1
t.invoke @ polyfills.ada2932e2114d304452b.js:1
e.run @ polyfills.ada2932e2114d304452b.js:1
e.run @ vendor.89fd12df6ac20169677e.js:1
next @ vendor.89fd12df6ac20169677e.js:1
o @ vendor.89fd12df6ac20169677e.js:1
t.__tryOrUnsub @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t._next @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t.next @ vendor.89fd12df6ac20169677e.js:1
t.emit @ vendor.89fd12df6ac20169677e.js:1
Lh @ vendor.89fd12df6ac20169677e.js:1
Oh @ vendor.89fd12df6ac20169677e.js:1
onInvokeTask @ vendor.89fd12df6ac20169677e.js:1
t.invokeTask @ polyfills.ada2932e2114d304452b.js:1
e.runTask @ polyfills.ada2932e2114d304452b.js:1
e.invokeTask @ polyfills.ada2932e2114d304452b.js:1
m @ polyfills.ada2932e2114d304452b.js:1
b @ polyfills.ada2932e2114d304452b.js:1
vendor.89fd12df6ac20169677e.js:1 ERROR TypeError: Cannot read property 'get' of undefined
    at t.addControl (vendor.89fd12df6ac20169677e.js:1)
    at t._setUpControl (vendor.89fd12df6ac20169677e.js:1)
    at t.ngOnChanges (vendor.89fd12df6ac20169677e.js:1)
    at vendor.89fd12df6ac20169677e.js:1
    at vendor.89fd12df6ac20169677e.js:1
    at Mv (vendor.89fd12df6ac20169677e.js:1)
    at ty (vendor.89fd12df6ac20169677e.js:1)
    at Object.updateDirectives (portlets-shared-dot-content-types-edit-dot-content-types-edit-module-ngfactory.27bf65c703be8634b1db.js:1)
    at Object.updateDirectives (vendor.89fd12df6ac20169677e.js:1)
    at Dv (vendor.89fd12df6ac20169677e.js:1)`

**Comment by fabrizzio-dotCMS** [comment]
The Actions are actually removed from the table..  Flushing cache solves the problem.

**Comment by fabrizzio-dotCMS** [comment]
If I execute all the steps listed above and push-publish a piece of content the receiver gets the error.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17421

**Comment by fabrizzio-dotCMS** [comment]
After the cache invalidation code was added to the `WorkflowFactoryImpl` I am no longer able to reproduce the issue

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
