### ISSUE TITLE
Content Selection Screen trying to toggle selectbox

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17396]
If you are in edit mode and go to add a piece of content to a page and instead of hitting the button, you hit the content title (still the hit area) - we get a j/s console error saying that 
`toggleCheckbox is not defined`.  While it doesn't happen all the time, I have seen this break the page and no content can be selected.

![content-selector-looking-for-checkbox](https://user-images.githubusercontent.com/934364/65841177-bdbe4280-e2ed-11e9-8ec1-4fcd7f557be9.gif)

**Comment by fmontes** [comment]
Closed in favor: https://github.com/dotCMS/core/issues/17328

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
