### ISSUE TITLE
FE Problems adding tags to personas 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17419]
After the changes in the related card now we are including all the tags in the autocomplete list in the tag field adding personas, but now we have some problems adding those ones from UI. 

If you type some letters when we show the list of consistencies, and when you select one of those,  we are adding two tags, the selected one and a new one with the word that you have typed in the field 

SC: https://screencast.com/t/eSllLlPJQ09

_Originally posted by @jgambarios in https://github.com/dotCMS/core/issues/17406#issuecomment-537478445_

**Comment by fmontes** [comment]
This was a known issue we worked in the original issue: https://github.com/dotCMS/core/issues/17198
