### ISSUE TITLE
Editing Layouts blows away content that is embedded in template code

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17435]
If you have a #parseContainer call in your template.vtl, you can manage content in that code and even personalize it.  But once you go to the layout editor, any content you had in that container gets wiped out.

We need to leave content in any container that we are not managing in the layout editor.

To reproduce:
1. Add a `#parseContainer` to a template vtl in a theme
2. Create a page with that theme and add other containers to it
3. You can manage the content in the container embedded in the template
4. Go to the layout and change the layout and save it.
5. The content you added to the container on the page has been wiped out.

**Comment by wezell** [comment]
I am ok if we have a multi_tree.UUID pattern that needs to be used for containers controlled by the layout manager vs. ones that are added by customers.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF
