### ISSUE TITLE
Dependencies are not reindexed when saving a content

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17431]
When a content is reindexed after a Save action, its dependencies are not indexed.

Steps to reproduce: 
1. Change comments-comments relationship cardinality to many-to-many
2. Add two new comments: “Parent 1” and “Parent 2"
3. Add a few children to Parent 1, save and close the window
4. Edit “Parent 1” again and add “Parent 2" as parent, then Save

If you close the Edit window and open it again the new parent is not there. It happens only after a Save, Save/Publish works correctly

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17432

**Comment by dsilvam** [comment]
Passed Internal QA: Not parent was lost after following described steps

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2 // Postgres // FF
