### ISSUE TITLE
PullRelated not including live version of content when different from working one

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17451]
### Describe the bug
When using pullRelated method with content that has a live version different from it's working version, it won't show up. This bug can be seen on the authoring server in the doc site. If you have a content that is published already, then save a draft copy of it, it disappears.

### Expected behavior
Live version different from working version should show up when using pullRelated.

Reproduced on 5.2.0

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/17493

**Comment by nollymar** [comment]
**Note to QA:** Please test these scenarios: 
-  `pullRelated` calls with different types of relationships
- Perform calls to the content rest api with `depth` param to return relationships and filter using `live` and `languageId` params

**Comment by erickgonzalez** [comment]
Needs Work
* If no condition is set to the **pullRelatedField** only content that has the same live/working version is shown on the **Edit/Preview Mode** and should be showing the working version.

* Self-related relationships not showing on FE when content has diff live and working versions, also on the **live mode** we are showing the working version of the content and should be showing the live version (when there is no condition set in the **pullRelatedField**).

**Comment by nollymar** [comment]
@erickgonzalez the issue described in Point 2 happens not just for self-related content. 

Fixed: https://github.com/dotCMS/core/pull/17525

**Comment by erickgonzalez** [comment]
new PR https://github.com/dotCMS/core/pull/17539

**Comment by bryanboza** [comment]
Fixed, tested with the provided bundle and now we show the different versions working / live in the correct tabs.

**Comment by bryanboza** [comment]
Fixed, tested on master and works as expected
