### ISSUE TITLE
Default sort order for Custom content portlets should be by modDate

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#17455]
### Describe the bug

In 5.2.0, when you display "All" content types in a custom content portlet, the content is sorted  by content type.  It should, instead, be sorted by modDate by default.

### Steps to reproduce the behavior:
1. Create a custom content portlet which includes 2 or more Content Types.
2. Edit one content item of each of the Content Types.
3. Open the main Content Search portlet.
    * **Result (correct):** Content is sorted with the most recently changed content at the top of the list.
4. Open the custom content portlet.
    * **Error:** Content is sorted by Content Type, so recently edited content of all Content Types is not shown at the top of the list.
5. Change the "Type" field from "All" to a single content type.
    * **Result (correct):** Content is sorted with the most recently changed content at the top of the list.
6. Change the "Type" field back to "All".
7. Click the "Last Edit Date" column header twice (to change the sort order to modDate desc).
    * **Result (correct):** Content is sorted with the most recently changed content at the top of the list.

### Expected behavior

When a custom content portlet is set to show "All" types, the content should be sorted by modDate descending.  This should be true both when:

* The portlet is first opened (since the default value of the "Types" field is "All").
* The Types field is changed from showing a single content type to "All".

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome v76.0.3809.100
 - Version: dotCMS 5.2.0 (release)

### Additional context

This appears to be a side-effect of specifying specific Content Types in the ES query.  I can reproduce the problem by entering a Lucene query of the form `+(contentType:contentType1 contentType:contentType2 contentType:contentType3)` in the Query Tool on the back-end, and entering `score,modDate` as the sort criteria.

The interesting thing is that the same content type is always displayed first in the list of results, no matter what order I put the content types in the search terms.  So, for example, if I change the query to `+(contentType:contentType3 contentType:contentType2 contentType:contentType1)`, the results are identical, with the same content type shown first.

I tried changing the query to specify the terms in many different ways (with and without quotes, different parentheses uses, using implicit and explicit OR, etc.), and the results were always the same.  So I suspect that the only way to get this to work properly may be to remove the "score" from the sort order for custom content portlets.

In truth, using the score only really makes sense if there are values for at least one of the user-searchable fields in the sidebar.  So a simple, generic solution (so the custom content portlets don't have to be a special case) might be to only add the score to the sort order when at least one of the user-searchable fields has a value.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/17474

**Comment by wezell** [comment]
Just to be clear what this change should do - it should sort by `score` when there is any search criteria being sent.  If there is no search crieteria except the baseType or content types, then it should sort by `modDate desc`

**Comment by erickgonzalez** [comment]
Tested working as it should, now custom portlets are sort as **modDate desc** by default.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by dsilvam** [comment]
Passed Internal QA Release: default sorting by `modDate` and when including a search criteria, sorting by `score`
