### ISSUE TITLE
Add the missing Default Actions

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#17464]
Implement the default actions for system action: unpublish, archive, unarchive, delete, destroy

- API Level
- Rest Level
- Have to support body on the put and save the information on all actions.
- Related to #17006
- Support on the language query string parameter for the fires, 
    - language=es
    - language=1
    - language=es-ES
    - language=es_ES

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17476

**Comment by jgambarios** [comment]
Defaults actions is a very important piece and also a big one, we need to:
 1. Document how it works in the dev-wiki.
 2. Include postman tests for the end points we modified in this task.

**Comment by jdotcms** [comment]
OK I will work on it

**Comment by jgambarios** [comment]
**NOTE:** When we are ready to release this functionality we need to create a new starter applying on it the changes in the upgrade tasks made in this task. https://github.com/dotCMS/core/issues/17726

**Comment by erickgonzalez** [comment]
This was tested https://github.com/dotCMS/core/issues/17464#issuecomment-544598094 and also the System Actions in the **Workflow Resource Tests.json** and it's working good.

**Comment by bryanboza** [comment]
Fixed, for now we are able to use that default actions via REST, but we need to wait for the new starter in order to use that actions from the admin console. 

Also, we already have the postman tests on the **Workflow Resource Tests.json**
