### ISSUE TITLE
Form Creator is invalidating all binary submits as "File size is larger than allowed in bytes"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17468]
Recreated on latest demo running 5.2 release version

Create a new form content type with one text field and a binary field.  Then go to any page and add that form to the page.  Then try submitting the form using text field and a small image.  The binary field on the form will always invalidate the image as being too large.

![FormFileSize](https://user-images.githubusercontent.com/1569167/66679177-d0f4da80-ec2a-11e9-9bfc-fd63284a363e.gif)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
