### ISSUE TITLE
[SQLResultsViewTool] canUserEvaluate broken check

### ISSUE THREAD

**Issue by maverick1981** [dotCMS/core#17469]
**BUG Description:**
Contentlets inode determination fail inside canUserEvaluate() method.
It's searching for somenthing splitted by "_" but actually pattern to derive inode/identifier is something like: /VIEW_TYPE/contentlet_inode_identifier/field_inode_identifier
"Content Editor cannot execute the SQLResultsViewTool..." message is showed despite
- user has Scripting role
- ALLOW_VELOCITY_SQL_ACCESS_TO_DOTCMS_DB=true
- ENABLE_SCRIPTING=true
- sql query is running inside a widget.

**BUG REPRODUCTION:**
--> STEP "A"
1. add Scripting role to admin user 

--> STEP "B"
1. Create a new page with blank template
2. add simple widget with simpre sql query inside code field: "select * from language"
3. see SQL error "Content Editor cannot execute the SQLResultsViewTool...".

I can create a branch to fix it in order to merge this easy check recovery after you revision. Let me know.

Regards,
C.

**Comment by wezell** [comment]
A pull request for us to look over would be much appreciated!  If you do make a PR, can you also state in your comment that 

"I hereby agree to the terms of the dotCMS CLA available at: https://gist.github.com/wezell/85ef45298c48494b90d92755b583acb3"

Thanks!

**Comment by maverick1981** [comment]
Will I'm Christiaan Barigelli (Enginering).
Do you need my signature on the CLA or are those from Engineering enough (you should already have I think)?

Bye
