### ISSUE TITLE
Future Time Machine does not display future publish content in listings

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17467]
Recreated on two servers running 5.2 release version

To reproduce:
Create a new news content and set the publication date to the future and the expiration date to the future and "Save" as draft.

Go to the time machine and place the future date in between the publish and expire dates on the content, then navigate to the news listing page.  **Bug is that the future news does not display at all.**

See video:  

![TimeMachine](https://user-images.githubusercontent.com/1569167/66677473-f1229a80-ec26-11e9-846d-312bfaeef5e8.gif)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17588

**Comment by jgambarios** [comment]
**NOTE TO QA:** On this ticket we just fixed the display of future publish contents on listings using the content pull but we still have issues displaying individual future publish contents.

The missing improvements will be handle in: https://github.com/dotCMS/core/issues/17594
