### ISSUE TITLE
Applying an in use license should fail

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#17475]
### Describe the bug
Within a cluster the system will allow you to apply a license that's already in use by another node.

### Steps to reproduce the behavior:
1. In a cluster go to System -> Configuration -> License
2. Select to apply a license that is already in use by another node
3. License is applied successfully.

### Expected behavior
This should not be allowed.

 - Version 5.x

**Comment by wezell** [comment]
This is expected as we no longer tie licenses to servers.  Not to say we won't in the future, but this is how it works currently.  Keep in mind that we reserve the right to audit customers license usage and back charge them for any license violations.
