### ISSUE TITLE
Problems adding a new related content in different languages from edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17481]
When you have a content type with a relationship filed and try to add a new related content editing an existing piece of content, if you change the language we are losing the reference and we are not relating the content. 

### Steps to reproduce the behavior:
1. Create two new content types with just one text field (test1, test2)
2. Add a relationship field in "**test1**" one to many with "**test2**" (not required)
3. Add a single piece of content in test1 and in test2
4. Now try to edit the created content in **test1**
5. On the "**relate**" button in the relationship field click to "**relate new content**" option 
6. This will open a new content modal, change the language and add the piece of content in Spanish
7.  Save & Publish 
8. Edit the piece of content again and make sure the content is related 

### Expected behavior
We need to relate the content without problems, we are losing the reference when you change the language 

### Screenshots
SC: https://www.screencast.com/t/FDsgmJBKkVmZ

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by nollymar** [comment]
It happens for both legacy and relationship fields
