### ISSUE TITLE
Expose Geolocation to Visitor Object

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17495]
We use geolocation in rules but it is not exposed to the visitor object.  We need to expose geolocation data to the visitor with something like `$visitor.geo`

**Comment by jdotcms** [comment]
It works with real ip, however on api's such as the vtl api the visitor is not even set.
<img width="747" alt="Screen Shot 2019-11-05 at 2 02 05 PM" src="https://user-images.githubusercontent.com/19578350/68242020-62126380-ffd5-11e9-98b5-b9be5ea5b4b0.png">

**Comment by jdotcms** [comment]
It works with real ip, however on api's such as the vtl api the visitor is not even set.
<img width="687" alt="Screen Shot 2019-11-05 at 2 06 49 PM" src="https://user-images.githubusercontent.com/19578350/68242118-879f6d00-ffd5-11e9-8b54-d6741453486c.png">
