### ISSUE TITLE
Page won't allow a live view if a page has different Live and working versions 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17490]
Pages with different live and working versions do not allow users to switch to "Live" view in edit mode.

![live-not-working.gif](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/62a7e547-9c53-4c21-ab97-f184d339f47a)

**Comment by wezell** [comment]
Commits 0e20f1b2f2ee014807659636dd07be1988e71e4c and 737d8484297880fd71b2274356a18daf5ea2fbfd

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17491

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce the problem

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF
