### ISSUE TITLE
Limited Backend user can't be created for UI access

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17498]
Tested on two servers running 5.2 released version

The bug is that the "Can Login To Admin UI" does not toggle unless you are a CMS Admin, which is incorrect.

![Screen Shot 2019-10-21 at 11 38 25 AM](https://user-images.githubusercontent.com/1569167/67228874-68121d00-f3f7-11e9-9009-07ae569b198c.png)

If you examine starter users, like Joe contributor, they are backend users and the toggle for can login is set to true.  However there is no way to set up a new user in the system which has these same settings.  I have only been able to toggle new users to true if I make them CMS Admin which would give them complete rights to everything - which is not desired behavior.

![limitedBackendUserBug](https://user-images.githubusercontent.com/1569167/67229045-baebd480-f3f7-11e9-8dd5-2911f90884f2.gif)

**Comment by wezell** [comment]
This is b/c the user does not have any tools assigned to them.
