### ISSUE TITLE
Cannot use #editContentlet Macro to edit events

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#175]
This happens in both 1.9.5 and 2.0 demo.  If you try to use #editContent to edit an event it throws an NPE:  https://gist.github.com/2421338  (This is the error thrown in 1.9.5)

Here is screencast me creating and explaining the issue:  http://screencast.com/t/3GF6WWot

**Comment by wezell** [comment]
Will be addressed when we revamp edit mode
