### ISSUE TITLE
Adding a New Relationship between related Page Content Types does not relate the content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17509]
Tested this on 5.2 released version

To replicate, create a new page content type and give it a relationship field with a many to many relationship to itself.

Then create a page, and after save/publish, close and re-open the page properties.  Then try to choose "Relate New Content" from the relate drop down.  

![Screen Shot 2019-10-22 at 11 50 36 AM](https://user-images.githubusercontent.com/1569167/67314618-387c1700-f4c2-11e9-95d9-bd330c2b116a.png)

After adding the new content and clicking either save, or save&Publish, the new page is created but the relationship is not established and the UI opens the page editor instead of allowing the user to go back to the parent contentlet they were editing.  The only way to establish the relationship, is the close the new page, re-edit the original page, and search for existing pages, check the new page, and save the new relationship.

![RelatingNewPages](https://user-images.githubusercontent.com/1569167/67314538-0f5b8680-f4c2-11e9-8465-d494d035d294.gif)

**Comment by wezell** [comment]
related: #17481

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/17546

**Comment by nollymar** [comment]
**Note to QA:** Please, test self-joins and relationships between different content types using both legacy relationships and relationship fields

**Comment by dsilvam** [comment]
Needs work: 

1. Add a page of a custom page type from the Site-browser
2. Go to page properties from edit-mode and clicking on relate-new content
3. Save & Publish the new content

It should return to the parent content but instead comes back to edit-mode and if you click on the page properties again you won't see the related content.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17576

Now when you add **New Related Content** regardless the portlet (site browser, content search or edit mode) after you **Save/Publish** the new content it will leave open the dialog with the option to go back to the parent content.

**Comment by dsilvam** [comment]
Passed Internal QA Release: steps from previous "Needs work" comment working ok.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF
