### ISSUE TITLE
[Velocity] : Templates are not sharing variable declarations between them

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17500]
Reported via Support: [99389](https://dotcms.zendesk.com/agent/tickets/99389)
Reproducible in dotCMS 5.1.6, 5.2.0, and latest master.

When customers build enterprise-grade Sites, they need to deal with an important amount of global variables and ViewTools that need to be accessed from all the VTL files that are called when displaying an HTML Page. In dotCMS 3.x, if you declare a Velocity Variable in, say, Template A, such a variable is still visible in Template B or C.

However, for dotCMS 5.1.6, a variable declared in Template A will not be available in Template B.

### Steps to reproduce the behavior:
1. Spin up a local dotCMS 5.1.6 instance or above.
2. In the `demo.dotcms.com` site:
2.1 Go to **Site > Templates > Blank**, and change its code to this:
```html
<!doctype html>
<html>
    <head>
    	#set($my_test_site = "mylocal")
        <title>Test Page</title>
        <link href="//$!{my_test_site}:8080/css/style.dot" rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1>My Test Page</h1>
    </body>
</html>
```
2.2 Create a new blank template called "Blank CSS", add the Blank Container to it.
2.3 Create an HTML Page called "test", and open it in an incognito window: http://localhost:8080/test . The font color of the "My Test Page" header **MUST** be black.
2.4 Create a new empty Site called "mylocal", and set its alias to "mylocal" too.
2.5 Add it to the /etc/hosts file in your local machine.

3. Go to the `mylocal` Site now:
3.1 Create a folder called "css".
3.2 Under this folder, upload a file called "branding.vtl" with the following content:
```html
#dotParse("//$!{my_test_site}/css/controller.vtl")
```
3.3 And another file called "controller.vtl" with the following content:
```html
#set($dummy = $response.setHeader("Content-Type", "text/css"))
#set($dummy = $response.setHeader("Cache-Control","max-age=86400"))

h1 {
    color: green;
}
```
3.4 Under the `/css` folder, create an HTML Page called "style.dot" using the "Blank CSS" template. **DO NOT USE THE BLANK TEMPLATE USED FOR THE PREVIOUS /test PAGE!**
3.5 Add a Simple Widget to the page, and enter the following code:
```html
#dotParse("//$!{my_test_site}/css/branding.vtl")
```
4. Refresh the http://localhost:8080/test page, and you'll see that the font color of the header is still black. You'll also get the following error in the dotcms.log file:
```
13:52:53.919  WARN  directive.DotParse -  - unable to resolve /css/branding.vtl getting this: No resource found for [///css/branding.vtl] @ url:GET//mylocal/css/style.dot | lang:1 | ip:127.0.0.1 | Admin:false | start:10-21-2019 01:39:53 CST  ref:http://localhost:8081/ >/LIVE/b0860a8a-6e63-4690-9fc4-7a33804294e3/694805c6-8f07-467f-a434-0da04a93e9e5.fields
13:52:53.919  WARN  directive.DotParse -  - at com.dotcms.rendering.velocity.directive.DotParse.resolveTemplatePath(DotParse.java:92) @ url:GET//mylocal/css/style.dot | lang:1 | ip:127.0.0.1 | Admin:false | start:10-21-2019 01:39:53 CST  ref:http://localhost:8081/ >/LIVE/b0860a8a-6e63-4690-9fc4-7a33804294e3/694805c6-8f07-467f-a434-0da04a93e9e5.fields
```
Specifically here: `No resource found for [///css/branding.vtl]`, notice how the `$!{my_test_site}` variable is coming in empty, that's why you see three slashes instead of two. This is why the CSS style is never resolved. Putting the declaration code in the "Blank CSS" template:
```html
#set($my_test_site = "mylocal")
```
That is, duplicating the declaration code, is the workaround to solve the problem.

### Expected behavior
The font color of the header should be green, as it is in a dotCMS 3.x instance with the very same steps to reproduce.

### Desktop:
 - OS: Not relevant.
 - Browser Not relevant.
 - Version Not relevant.

**Comment by wezell** [comment]
@jcastro-dotcms I'm trying to reproduce this but I am missing something - how is the variable  `${my_test_site}` getting set on the `//mylocal/css/style.dot`?
The page `//mylocal/css/style.dot` is using the 
- Blank CSS template - nothing in it but the blank container
- trying to parse the `//${my_test_site}/css/branding.vtl` but `${my_test_site}` is not set
- which parses the `controller.vtl`

**Comment by jcastro-dotcms** [comment]
@wezell the variable `${my_test_site}` is declared in the **Blank** template, above the `<title>` tag.

**Comment by wezell** [comment]
But the CSS page that is calling it uses the "Blank CSS" template created in step 2.2 - there is no variable declaration in that template.

I tried to reproduce this- I created a template that set a variable, a container that read the variable and set it again, a #dotParse that was added in a widget read the variable and set it again and another #dotParse that read it and set it again.  It was set correctly every time.  

I tried to follow the steps above and from what I see, nothing in the  `//mylocal/css/style.dot` chain sets the variable.

**Comment by jcastro-dotcms** [comment]
@wezell exactly. In dotCMS 3.7.1, the **Blank CSS** template does not require the variable to be declared in there as it is inferred from the previous **Blank** template. As the templates are called in the same request, we shouldn't need to declare variables everywhere. I discussed this with @dsilvam a few days ago and he also thinks this is a bug.

**Comment by wezell** [comment]
So after looking at this, it turns out the variable was empty in both 3.x and 5.x and was never being passed across the page which explains my confusion.

In 4.x, #dotParse changed from a macro to a Directive and the behavior of how`#dotParse` dealt with paths where the specified host does not exist.  In 3.x, if you called the #dotParse macro 
```#dotParse("//iDontExisit.com/css/branding.vtl")```
 and the host did not exist, then dotCMS would fall back to the current host that was calling the `#dotParse`, e.g. doing a`#dotParse("/css/branding.vtl")`

 Since ~4.2, if you call 
```#dotParse("//iDontExisit.com/css/branding.vtl")```
 and the host does not exist, then the system will fall back to the DEFAULT host, in essence doing a `#dotParse("//defaultHost/css/branding.vtl")`

I think regardless of how dotParse was handled in the 3 series, falling back to the default host was always the intended behavior and the correct behavior for creating enterprise-grade multi tenant sites, so you don't have to replicate all the same .vtl files across site and instead call them from default site, whatever its hostname is changed to.
