### ISSUE TITLE
Uploading new Files via webdav checks them in twice and fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17506]
1. Connect to dotCMS via webdav / live
2. Upload a new folder with some new files in it
3. The Upload fails and you are left with a zero length file in dotCMS

**Comment by jcastro-dotcms** [comment]
Reproducible in dotCMS 5.2.0 too

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17530

**Comment by fabrizzio-dotCMS** [comment]
Currently testing it.

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify that uploaded files are checked-in just once.
However, uploading folders with a large number of files often fail regardless of the WebDAV client used. This due to Broken Pipes/Socket reset exceptions.  WebDav still has some problems.
