### ISSUE TITLE
Workflow History is never reset - dotcms 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17516]
When a Workflow has 4-Eye Approval and that is executed once, the history is not reset. Even when moving the content to a previous step for another edit the approval process is not reset and the content gets published instead. 

1. Create content
2. Send to 4-eyes approval
3. Approvers approve
4. Content published
5. Content unpublished 
6. Edit content
2. Send to 4-eyes approval

### Expected behavior
The approvers should have to approve the new edit. 

###Actual Behavior
Content is published

### Reference ticket:
https://dotcms.zendesk.com/agent/tickets/99479

### Desktop (please complete the following information):
 - OS: n/a
 - Browser Chrome/Safari

**Comment by craigWagner99** [comment]
Issue was discovered by Deutsche Bank and the bug was identified by daniel.solis @dsolistorres

**Comment by wezell** [comment]
Will be fixed here: #17904
