### ISSUE TITLE
Url map pattern on the root will fail to upgrade properly to dotCMS 5.2.0

### ISSUE THREAD

**Issue by TheGreatAlexander** [dotCMS/core#17514]
### Describe the bug
If you have an instance of 5.1.6 and have a url map pattern on the root such as /{urlTitle}, the upgrade will disable all url maps and they will return 404s.

### Steps to reproduce the behavior:
1. Create a demo instance of dotCMS 5.1.6
2. Reset the blog url pattern to /{urlTitle} and news url pattern to /{urlTitle} or set another contentType's url pattern to /{variable}/{urlTitle}
3. Upgrade the instance to dotCMS 5.2.0 
4. Reindex
5. And, Voila .... sometimes the blog does not work and sometimes that news will not work.

You will get this error on the dotcms.log:

WARN cache.LegacyContentTypeCacheImpl: Structure with inode: 'system_hostblog' not found in db
This image has blocked the ip and its port with red.
![Screen Shot 2019-10-22 at 9 57 10 PM](https://user-images.githubusercontent.com/1947524/67356479-81aa8600-f517-11e9-9bd8-e6ef1f2c0f7f.png)
![Screen Shot 2019-10-22 at 9 56 49 PM](https://user-images.githubusercontent.com/1947524/67356480-81aa8600-f517-11e9-9922-665688ba277f.png)

![Screen Shot 2019-10-22 at 8 13 28 PM](https://user-images.githubusercontent.com/1947524/67352231-ad743e80-f50c-11e9-8217-329e692c8d41.png)

![Screen Shot 2019-10-22 at 8 29 00 PM](https://user-images.githubusercontent.com/1947524/67352251-b9f89700-f50c-11e9-8086-300fc4aaa3aa.png)

### 
To solve this issue in the upgrade, I simply added a string before the variables like /something/urlTitle and upgraded and everything worked well and had to errors in the logs.

**Comment by wezell** [comment]
Is this the same as is reported here?
https://groups.google.com/forum/#!topic/dotcms/KKHGh_47siE

**Comment by wezell** [comment]
Also need to fix: #18015

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18135

**Comment by dsilvam** [comment]
Passed QA: After setting the URL Pattern to /{urlTitle} for both Blog and News types and upgrading (from 5.1.6) to master, accessing Blog and News URL-Mapped content is working ok.
