### ISSUE TITLE
Blank page when you go to the rules portlet in the community edition 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17512]
We are unable to show the license required message when you are in the community edition and go to the Rules portlet, and we have the error on logs 

### Steps to reproduce the behavior:
1. Login 
2. Go to Marketing --> Rules 

### Expected behavior
As in the other portlets, we need be able to see the license required message 

### Screenshots
SC: https://www.screencast.com/t/RQSwT0vgnV
ST: https://gist.github.com/bryanboza/c9b8157895997dcda366ff49534753e8

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by hmoreras** [comment]
endpoint `http://localhost:8080/api/v1/sites/48190c8c-42c4-46af-8d1a-0cd5db894797/ruleengine/rules` do not bring the attr `message` anymore.

**Comment by nollymar** [comment]
@freddyucv be careful to avoid breaking changes on this task https://github.com/dotCMS/core/issues/16383

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF, now we have the message again
