### ISSUE TITLE
Content with Relationships or Categories can not be saved using the WorkflowResource

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#17529]
If you try to save a content with relationships using the WorkflowResource `/api/v1/workflow/actions/default/fire/PUBLISH` it fails because the checkin method we are using in it sets relationships to null https://github.com/dotCMS/core/blob/f33de02f0d537cc611828c652e642206087af3e8/dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/SystemActionApiFireCommandFactory.java#L223

If you use the old ContentResource `/api/content/newpublish/1` works without issues.

As a workaround to this issue is adding the **Publish** action to the **New** Step and check **New** on **Show When**.

Steps:
1- Create a CT with a text field a relationship field to itself.
2- Create content without any relationship.
3- Create another content but this time relate it to the content above using the identifier.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17535

**Comment by erickgonzalez** [comment]
Please also test creating a content with categories

**Comment by erickgonzalez** [comment]
Tested on master and release-5.2.1. WorkflowResource endpoint creates successfully content with relationships and/or categories.

**Comment by bryanboza** [comment]
Fixed, now we are able to create content with relationships without problems. Tested on release-5.2.1

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
