### ISSUE TITLE
Relationship cardinality not respected

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17524]
### Describe the bug
One to one relationship cardinality is not being respected on a new relationship.

### Steps to reproduce the behavior:

1. Add a rel-field to `Content Generic` pointing to `Youtube`, with cardinality set to `One to One`
2. Add a rel-field back (existing) from `Youtube` to `Content Generic`
3. Add _How does a Mutual Fund work?_ (`youtube`) to _Bear Mountain Lodge Description_ (`content-generic`)

If you go to a different `youtube` content, for example, the one with title _dotCMS and Amazon Eco part 1_ , you will be able to also add it to  a _Bear Mountain Lodge Description_ (`content-generic`), which breaks the cardinality (`One to One`)

Also important to note, that the relationship field  of `youtube`s en _Bear Mountain Lodge Description_ (`content-generic`) is showing only the first related content _How does a Mutual Fund work?_ 

On the Database it's possible to see the three related youtubes to the content generic contentlet.

### Expected behavior
`One to One` cardinality needs to be respected

### Additional context
Found while testing https://github.com/dotCMS/core/issues/16165

## Acceptance Criteria
- [x] All cardinalities need to be respected
- [x] Integration test

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17540

**Comment by dsilvam** [comment]
Passed Internal QA Release: One-to-one cardinality correctly validated.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by dsilvam** [comment]
Passed Internal QA: One-to-one cardinality correctly validated.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
