### ISSUE TITLE
show message when there are no workflows

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17533]
When you hit a content type that does not have a workflow scheme or if a piece of content is in a workflow step without any actions, the left side of the edit content screen just shows blank.  This is confusing when users hit this case and looks odd in the ui.

**Comment by wezell** [comment]
PR: #17536

**Comment by wezell** [comment]
@john-thomas-dotcms note that this needs translations

**Comment by wezell** [comment]
PR: #17537

**Comment by dsilvam** [comment]
Passed Internal QA Release: Showing friendlier info than the previous empty area

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by dsilvam** [comment]
Passed Internal QA:  Showing friendlier info than the previous empty area

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
