### ISSUE TITLE
Task List - Task Detail 'URL' link incorrectly formed

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17532]
Reported via Support: [99571](https://dotcms.zendesk.com/agent/tickets/99571)
Reproducible in dotCMS 5.1.6, and Demo Site (5.2.0)

When opening a Task Detail for a _non-file-asset_ content, the URL field appears as a hyperlink. When you click the link it opens a blank page with an odd URL. 

### Steps to reproduce the behavior:

1. Log In
2. Click on Home -> Tasks
3. Open a non-file-asset task's Task Detail
4.  Scroll down and click on URL

### Expected behavior
It should take you to the content.

### Actual behavior
It opens blank page with odd URL

### Screenshots

![image](https://user-images.githubusercontent.com/49727631/67572808-98f69880-f6fc-11e9-8ec9-88eddf7e16f3.png)

![image](https://user-images.githubusercontent.com/49727631/67573164-4f5a7d80-f6fd-11e9-92ae-8786e2364ec7.png)

### Desktop (please complete the following information):
 - OS: N/A
 - Browser Chrome, FF

**Comment by craigWagner99** [comment]
Is any of this related to https://github.com/dotCMS/core/issues/14654  ?

**Comment by oarrietadotcms** [comment]
Feedback from the client: 

> The fix provided in the ticket opens the pages in view only mode, which editor can’t work on the page further if he/she receive workflow task, that’s my first point

Ticket: https://dotcms.zendesk.com/agent/tickets/99571

**Comment by wezell** [comment]
long term fix: #17532

**Comment by wezell** [comment]
PR: #17838

**Comment by fmontes** [comment]
Just merge and test.

**Comment by nollymar** [comment]
Another PR to remove an invalid line: https://github.com/dotCMS/core/pull/17927/files

**Comment by nollymar** [comment]
Tests results on master: Success

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgres // FF
