### ISSUE TITLE
Not properly tokenizing certain fields when indexing

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17544]
After changing to Standard tokenizer, there were a few fields that needed special treatment. 
Some of them were not properly modified. 

These are: 
`permissions` need to be `whitespace` tokenized. 
`moduser` need to be `keyword`
`owner` need to be `keyword`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17545

**Comment by dsilvam** [comment]
Note to QA: ping me for the QA steps

**Comment by wezell** [comment]
Customer confirmed fix is working for them.

**Comment by bryanboza** [comment]
Tested by the client and works as expected
