### ISSUE TITLE
No validation error when relating a piece of content to itself 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17543]
### Describe the bug
No validation error is being thrown when relating a piece of content to itself  **when a different relationship field also exists and it's valid**. 

### Steps to reproduce the behavior:
1. Edit `Content (Generic)` content type and add a `youtube` rel-field pointing to `Youtube`.
2. Edit `Content (Generic)` content type and add a `sibling` rel-field pointing to `(Content Generic)`.
3. Go to Search Content screen,  edit _Bear Mountain Lodge Description_ a choose itself in the `sibling` rel-field and then try to `Save & Publish` An error will display (**This is good**)
4. Now repeat 3. but instead of clicking on  `Save  & Publish` first choose a valid existing youtube contentlet in the other exiting rel-field `youtube` and now click on  `Save  & Publish` (**No error  showing. Not Good.  The contentlet is saved regardless of the invalid relationship with itself.**)

### Expected behavior
A validation message should be displayed when trying to related a piece of content to itself regardless of having other relationship-fields with valid selections.  

## Acceptance Criteria
1. Integration tests
2. No noisy-full-stack logging

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17558

**Comment by dsilvam** [comment]
Passed Internal QA Release: showing error message when trying to relate to itself regardless of having another valid rel field selected.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.1 // Postgres // FF

**Comment by erickgonzalez** [comment]
Working as it should on the master branch

**Comment by bryanboza** [comment]
Fixed, now we are showing the error in both cases
