### ISSUE TITLE
Copy site does not copy pages content

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17541]
Copying a site does no copy pages content.

#### Test 1
1. Go to the **Sites** portlet
2. **Add Site** -> **Copy an existing Site**
3. **What to copy** -> Select "**All**" option

#### Result
Copied pages used the old containers and do not have content in them

#### Expected Behavior:
The pages should have new containers linked to the new copies of the content.

#### Test 2
1. Go to the **Sites** portlet
2. **Add Site** -> **Copy an existing Site**
3. **What to copy** -> Select everything BUT containers

#### Expected Behavior:
The pages should use the old containers linked to the new copies of the content.

#### Result
?????

If you want to reuse containers from a host, you need to add containers with paths that include hosts
`//demo.dotcms.com/application/containers/

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/17674
https://github.com/dotCMS/enterprise-2.x/pull/694

**Comment by bryanboza** [comment]
- After this fix, now when you create a copy of any site, we are leaving some pages locked by the system admin. 
- Not all the pieces of content have been added to the pages. 
- Also, when you move to the edit tab, we are unable to edit the page. 

Needs some work here. 

SC: https://www.screencast.com/t/lVFykh6T4l

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/17749

**Comment by wezell** [comment]
The needs work tag has been moved to this issue: #17749

**Comment by bryanboza** [comment]
Now we are able to copy the site, new problems moved to a card #17749
