### ISSUE TITLE
Adding a form does not respect personalization

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17554]
If you have a personalized version of a page and try to add a form to it, it does not add to your personalized version of the page, it adds to the default persona.  In addition, it resets all your default persona content to the the personalized persons content.
**reproduce** 
1. Personalize a page
2. Change content around for the new persona
3. Add a form to the page

**Issue** 
1. the form does not add
2. Your personalized content is now content for the default persona 

![personalized-form](https://user-images.githubusercontent.com/934364/67812504-ba95ae00-fa75-11e9-8969-7c68dd6a2fa3.gif)

**Comment by bryanboza** [comment]
Fixed, tested on master and now it works as expected
