### ISSUE TITLE
When copying a contentlet, we do not need to copy workflow history

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17550]
When copying a contentlet, we need to maintain the current contentlets workflow step but we do not need to copy the workflow history for the old contentlet.

It's a new contentlet - there should not be any workflow history.

**Comment by wezell** [comment]
PR needs review

**Comment by dsilvam** [comment]
Maybe a test also?

**Comment by wezell** [comment]
PR: #17624

**Comment by nollymar** [comment]
An integration test was implemented

**Comment by fabrizzio-dotCMS** [comment]
The fix can be verified with the following query
`select h.* from workflow_history h join workflow_task t on h.workflowtask_id = t.id and t.webasset = '276494ed-b054-4d69-b73b-b07eea3271ce'` 

Just execute a workflow task and verify the entries on the `workflow_history` table then make a copy and set on the web asset param the id of the copy-contentlet. Now Re-execute the query. No entries are copied.

**Comment by bryanboza** [comment]
Fixed, now we are not including that history when you made a copy of the content. 
![wfhistory](https://user-images.githubusercontent.com/2641437/72368269-59b86200-36c3-11ea-9993-98cf9c6484d8.png)

Tested on release-5.2.4 // Postgres // FF
