### ISSUE TITLE
Language column wrapping in Chrome on the content search screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17561]
Chrome must have updated and broken nowrap / white-space styles.  All the sudden I am seeing this in Chrome all over the place, including on demo.

![Screen Shot 2019-10-31 at 1 13 18 PM](https://user-images.githubusercontent.com/934364/67970038-b1752000-fbe0-11e9-940f-05f1a9913682.png)

**Comment by wezell** [comment]
PR: #17562

**Comment by dsilvam** [comment]
Passed Internal QA Release: displaying as it should.

**Comment by jdotcms** [comment]
I have tested on Chrome, FF and Safari on Mac OS and looks fine on all of them

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.2.1 // Postgres // FF
