### ISSUE TITLE
GraphQL should not try to use BaseContentTypes as Interfaces

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17560]
We are always going to have issues trying to use the required fields on BaseContent types as "interfaces" for graphql.  In 5.2.0, we removed some required fields and added others to Forms.  In essence, this means that graphql is broken (schema won't generate) for anyone who has forms and upgrades 5.2.0.

I think we have our base content fields that all content has and we just leave it at that.

To test:
Upgrade from dotCMS 5.1.0 and then try to download graphql schema

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17573

**Comment by erickgonzalez** [comment]
Tested against 5.2.0 to 5.2.1 and also to master.
After the upgrade, I was able to refresh the schema successfully.

**Comment by bryanboza** [comment]
After the last changes, now we are unable to use the base types as interfaces, but we continue allowing to use as a collection, but when you try to use this in a request, we are unable to resolve. We need to remove those ones again. 
SC: 
https://www.screencast.com/t/JTPLnlqZlO

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/17701

**Comment by dsilvam** [comment]
Note to QA: Test the scenario described in this comment: https://github.com/dotCMS/core/issues/17560#issuecomment-559257698

**Comment by dsilvam** [comment]
Note to Doc: we need to remove the `fields` from the BaseType list here: https://dotcms.com/docs/latest/graphql#BaseTypes, and only mention that the BaseTypes are available as Collections to group content belonging to the.

**Comment by freddyucv** [comment]
If you start dotCMS without License and then apply one but not restar the tomcat server, then the persona base type is not working (return a HTTP 500 error if you run a query with persona base type)

<img width="1409" alt="Screen Shot 2019-12-06 at 3 35 45 PM" src="https://user-images.githubusercontent.com/10408015/70361128-207c0f00-1846-11ea-9080-be1fc3dc4fe0.png">

After restar tomcat it work

**Comment by nollymar** [comment]
Tests results: Success

**Comment by bryanboza** [comment]
Fixed, now we are able to group content by base type, and you can't use the common fields, new cards reported with problems on #17717
