### ISSUE TITLE
Tags with spaces or scpecial characters not pulling correctly on front end - dotcms 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17568]
In dotcms 5x, tags with spaces or special characters aren't querying correctly in the front end for users. 

See https://demo.dotcms.com/blogs/ 

### Steps to reproduce the behavior:
1. Navigate to https://demo.dotcms.com/blogs/
2. Select a tag from the tag cloud with a space or special character

### Expected behavior
Page should pull the Blog articles with the selected tag

### Actual Behavior
querystring is malformed and results are not consistent with the same search in the Admin query tool. 

### Desktop (please complete the following information):
 - OS: N/A
 - Browser Chrome FF
 - Version : dotcms 5x

![image](https://user-images.githubusercontent.com/49727631/68136825-86921100-feeb-11e9-8044-099ee17a301c.png)

**Comment by wezell** [comment]
please test the tags on the backend - what you are looking at above is implementation.

**Comment by craigWagner99** [comment]
The tag search works fine in the backend - both on the search screen and query screen: 
![image](https://user-images.githubusercontent.com/49727631/68143088-4edc9680-fef6-11e9-921f-39ddf167b020.png)

![image](https://user-images.githubusercontent.com/49727631/68143115-60be3980-fef6-11e9-85fb-8859f4cf68b8.png)

**Comment by oarrietadotcms** [comment]
@wezell does this mean that the velocity code is the one broken in demo?

**Comment by wezell** [comment]
Yup, @oarrietadotcms  it means it is not an issue in the core code base, only in the velocity implementation.  We don't make any guarantees regarding the demo's implemented (velocity) functionality.  As an example, the demo implementation site search has XSS vulnerabilities which get reported to us a "dotCMS security vulnerability".  The truth is that it isn't a security hole in dotCMS - the vulnerability exists only in how the velocity was implemented.

**Comment by craigWagner99** [comment]
Ok, so this *IS* an error in the Velocity file "blog-menu.vtl". 
John Thomas suggested adding the fix here so maybe this can be re-filed as a stater site issue? 

Basically the stuff that ends up in the querystring has to be RegEx'd & have quotes added to it in order for the URL to work. 

My code is below, but I am not a RegExpert so there may be a more efficient way to write it. 

As it stands, this appears to work for tags with spaces and ampersands. I imagine that other special characters would have to be RegEx'd as well. 


`#foreach($f in $blogTags.aggregations)
      #foreach($term in $f.buckets)
  #set( $regTerm = $term.key.replace(" ", "+") )    

  #set( $newTerm = "%22"+$regTerm.replace("&", "%26")+"%22" )
            <li><a href="/blogs/?tag=$newTerm" id="$term.key" data-tag="$term.key">$term.key <span>$term.docCount</span></a></li>
      #end
  #end`
