### ISSUE TITLE
Importing a bundle with relationships fields duplicates relationships

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17572]
### Describe the bug
Importing a bundle with relationships fields sometimes creates duplicates. As a result, one relationship field belongs to two different relationships  
### Steps to reproduce the behavior:

1. Import a bundle with relationship fields (I can provide one. I couldn't attach it to the ticket because it's a big file) . In case my bundle is used, these scripts must be run first:

```
update structure set velocity_var_name = 'calltoaction1234' where inode = '5deeaea3-e3c9-4aef-a4b3-94e4ad48e176';
update field set velocity_var_name = 'imagen123' where inode = '52c92b4e-ab2f-43df-a423-fed67c733e78';

```
2. Run a query over relationship table to detect duplicates: 
<img width="617" alt="Screen Shot 2019-10-31 at 3 20 34 PM" src="https://user-images.githubusercontent.com/8741395/68147445-0c23ba00-ff08-11e9-9004-d14f9bc561a7.png">

### Expected behavior: 
A relationship field should belong to only one relationship

### Acceptance Criteria: 
- [x] Add check constraints before saving a relationship to validate uniqueness
- [x] Implement ITs that validate the constraints
- [x] A relationship field should belong to only one relationship

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/core/pull/17575
https://github.com/dotCMS/enterprise-2.x/pull/690

**Comment by bryanboza** [comment]
Tested on release-5.2.1 // Postgres // FF

**Comment by nollymar** [comment]
Additional code improvements have been implemented on these PRs: 
https://github.com/dotCMS/core/pull/17592
https://github.com/dotCMS/enterprise-2.x/pull/692

**Comment by erickgonzalez** [comment]
Tested again with the latest changes and works as it should, still having only 1 relationship after importing the bundle.

**Comment by bryanboza** [comment]
tested on master, unable to reproduce
