### ISSUE TITLE
Building war from dotCMS core 

### ISSUE THREAD

**Issue by GitCatKitKat** [dotCMS/core#17579]
As a user team from travelsky, we need to know that any convenient way to build war file from dotCMS core code under Windows environment.

When our staffs tring to use gradle to built war file, they found when it was built successfully, they could not find the war file. Meanwhile, they tried using buildwar.bat, it could also not build any war file.

**Comment by wezell** [comment]
```sh
docker run -it -v %cd%:/local dotcms/dotcms-seed
## once you are in the docker image
cd /build/src/core/dotCMS
git pull && git checkout {branch/tag}
./gradlew war
cp build/libs/dotcms_*.war /local/
exit
```
