### ISSUE TITLE
ContentTool.pullRelated and ContentTool.pullRelatedField ignore custom sort

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17578]
ContentTool.pullRelated and ContentTool.pullRelatedField methods do not sort related content when a custom sort is set

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17590

**Comment by nollymar** [comment]
**Note to QA:** Important tests cases: 
1. Self joins
2. Many to One relationships
3. Pull parents/children

**Comment by dsilvam** [comment]
Passed Internal QA Release: Sort working in all cases above. Both `asc` (default) and `desc`

**Comment by erickgonzalez** [comment]
Tested on master, sorting relationships works without issues.

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working as expected
