### ISSUE TITLE
PP fails when existing folder is updated to force a default file type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17571]
#### Test 
1. Receiver has a folder - say `/images` that does not take a default fileType
2. Sender is pushing the `/images/` folder that has a new default fileType of a type that does not exist on the Receiver.  
#### Result
3. Bundle Fails

This can be recreated if you take a simple bundle of just an image from our new starter and try to import it into our old starter.  See attached.

[failed-80cb47a3-b19e-4fd3-ae19-63eaf8b1f050.tar.gz](https://github.com/dotCMS/core/files/3805458/failed-80cb47a3-b19e-4fd3-ae19-63eaf8b1f050.tar.gz)

**Comment by wezell** [comment]
PR: dotcms/enterprise-2.x#691

**Comment by dsilvam** [comment]
Passed Internal QA Release: Bundle successfully importing now.
