### ISSUE TITLE
URL Maps does not working on time machine 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17580]
We have problems trying to use the existing URL maps using the time machine in the future, we are unable to resolve the URL and shows a 404 error. 

ST: https://gist.github.com/jgambarios/8ddf64eb7827e45adbc125bc2800fe36

### Steps to reproduce the behavior:
1. Login as admin
2. Go to site browser and add a new URL map 
3. Go to time machine and select any date in the future 
4. Try to use the URL map

### Expected behavior
We need be able to resolve those URL maps and use the future time machine without problems 

### Desktop (please complete the following information):
Tested on release-5.2.1 branch // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17587

**Comment by fabrizzio-dotCMS** [comment]
This is currently under internal QA.

**Comment by fabrizzio-dotCMS** [comment]
The problems previously seen on time-machine were fixed.
