### ISSUE TITLE
SPA: Render Carousel in /destinations

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17597]
The `/destinations` page in the stater have a Banner Carousel component or widget, we need to create the same in the SPA.

Those components lives here: https://github.com/dotCMS/dotcms-spa/tree/master/components/content-types

And once created with the content type name we need to add it to the map here:

https://github.com/dotCMS/dotcms-spa/blob/master/components/layout/Contentlet.js#L10

## Context:

1. Not sure how the carousel behavior works in the original site, not sure if is jquery or something else.
2. We probably have to use react
3. Can we get the same behavior with pure CSS and a little bit of js?
4. We use to have something like that: https://github.com/dotCMS/dotcms-spa/blob/pre-nextjs/src/Components/BannerCarousel.js

## Acceptance Criteria

1. Render the carousel in the SPA to look and works the same as the regular site
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/dotcms-spa/pull/60

**Comment by fabrizzio-dotCMS** [comment]
Tested. 
Compared to the starter site. 
Dimensions are ok
Transitions are ok.
verified that the info on the request corresponds to the info visually shown

**Comment by fmontes** [comment]
@fabrizzio-dotCMS We still haven't decided if we're going to implement a "Book now" functionality here

**Comment by bryanboza** [comment]
Fixed, the differents are expected, and the main error here now it's working.
