### ISSUE TITLE
SPA: Set active state in nav items

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17606]
We need to set active the nav item based in the page we are:

![Screen Shot 2019-11-08 at 10.47.54.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/7313c687-b316-4c47-a28f-248ae7595233)

## Context:
1. Our nav uses react-router
2. We can use NavLink: https://reacttraining.com/react-router/web/api/NavLink
3. Since this pages are rendering server side and client side we need to find a way to do the match with the url and the nav item href.
4. [This](https://github.com/dotCMS/dotcms-spa/blob/master/components/layout/Nav/ItemLink.js#L5) is the component we use to render each nav item (I think)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/dotcms-spa/pull/61

**Comment by fabrizzio-dotCMS** [comment]
The nav item is selected correctly according to the present page we navigate to. 
However, I noticed that the SPA lacks the "HOME" Nav-item. 
Please add your thoughts @fmontes @jgambarios

**Comment by fabrizzio-dotCMS** [comment]
![Screen Shot 2019-11-25 at 1 44 52 PM](https://user-images.githubusercontent.com/37148755/69572486-d95e6600-0f89-11ea-9480-5cf50127c89e.png)

**Comment by fmontes** [comment]
@fabrizzio-dotCMS @bryanboza the SPA is a work in progress, it will not be 100% exact to the starter, right now we're creating issues to fix bugs and or implement features, the "Home" missing is a bug definitely, which @alfredo-dotcms is working on, there is no issue for that yet because we're in a point where we are fixing small things like this when we found them.

**Comment by bryanboza** [comment]
We have a console error every time you use some of the items of the menu 
![2019-12-11_16-28-00](https://user-images.githubusercontent.com/2641437/70747855-7b05e700-1cee-11ea-93ce-9576c4916411.png)
We need some work here

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/dotcms-spa/pull/76

**Comment by bryanboza** [comment]
Fixed, tested on the last code of this project and now works better.
