### ISSUE TITLE
Workflow Actions - Comments and Assigns dialog box does not display in Edit mode on Page Asset - version 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17600]
### Describe the bug
Comments and Assigns dialog box does not display in Edit mode on Page Asset. 

When a Page Asset has a Workflow step for Send for Review that includes the Comments and Assigns dialog box, the box will NOT appear when activating that step from Edit mode.

### Steps to reproduce the behavior:
1. Go to Page Asset with a review Workflow step that has Comments and Assigns
2. Click on the review step

### Expected behavior
Dialog box should appear to add comments before sending for review. 

### Actual behavior
Messaging is displayed at the top of the Edit window

**In the Page Properties window, the dialog box is displayed as expected**

![image](https://user-images.githubusercontent.com/49727631/68401382-3ca16900-013f-11ea-912b-dfde741ecddf.png)

**Dialog Box should be displayed in Edit mode - instead a message is shown**

![image](https://user-images.githubusercontent.com/49727631/68401085-c13fb780-013e-11ea-9d1b-a849eed4cf44.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser Chrome , FF
 - Version dotcms 5x

**Comment by john-thomas-dotcms** [comment]
Note to QA (@bryanboza): It seems like we might need to run tests inside the Page Editor for each of the Workflow sub-actions and Workflow action fields that generate popups, to make sure the popups are displayed properly.

More generally, when we're testing a new sub-action we might need to add the Page Editor to the list of places we test it (so content editing screen, Content Search screen, Page Editor, Site Browser, etc.).

**Comment by notmattmonroe** [comment]
Note that this is still an issue and customers are requesting action on this.
