### ISSUE TITLE
Relationshipfield always returns English

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#17614]
### Describe the bug
We've experimented with the relationshipfield in dotCMS 5.1.6. It works fine until you use a language other than English. If you have a field called "tiles" and call $tiles it always contains the English content versions. This also happens in our cloud environment.

### Steps to reproduce the behavior:
1. Create a multilingual page (for instance EN and ES)
2. Add multilingual content to it 
3. Add a relationship field to that content (many to many, not required)
4. Relate the content on the page to other multilingual content
5. In the container also display the relationshipField. If the field is called "relatedContent" then use the variable $relatedContent. Or if you pull the content somewhere then use $mypulledcontent.relatedContent

### Expected behavior
In Spanish I expect the relationshipField to contain Spanish content if it is available, not only English

### Workaround
If, for each piece of content in $relatedContent, you call $dotcontent.find() then the correct language version is retrieved

**Comment by wezell** [comment]
@Xander-Steinmann can you reproduce this on the demo?  We've done a lot of work here on 5.2 and this should work as expected in the latest release.
