### ISSUE TITLE
Top-right Site dropdown - info not cleared from session until refresh - version 5.2.1

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17613]
### Describe the bug
Using the top-right site dropdown to change sites doesn't clear the site info from session ($host.identifier)

### Steps to reproduce the behavior:

Using $host.identifier code from https://dotcms.com/docs/latest/display-properties-of-the-current-site:

1. Make an identical page on 2 different sites with a widget containing that code
2. Publish
3. Open page on first site. Info outputs correctly.
4. Change site with upper-right dropdown
5. Open page with the code on that site
6. The OTHER site's information still display.
7. If you close/reopen or refresh it loads the correct site info

### Expected behavior
Site info output should always match the site dropdown. 

### Screenshots
**1st. Screenshot - server info and code output are equal**

![image](https://user-images.githubusercontent.com/49727631/68803570-a4672080-0625-11ea-9982-f612d5008447.png)

**Switch site - open page with same code. IT still shows the old site info**

![image](https://user-images.githubusercontent.com/49727631/68803600-afba4c00-0625-11ea-82cc-f356179c2058.png)

**refresh browser (or close, then open page) and site info is correct:**

![image](https://user-images.githubusercontent.com/49727631/68803642-c365b280-0625-11ea-9276-123b875d4b29.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser chrome/ff
 - Version 5.2.1

**Comment by mattyarbrough** [comment]
Additional reports have come in that this is affecting customers.

**Comment by wezell** [comment]
fixed in 5.2.8
