### ISSUE TITLE
SPA: Better error handling in SPA

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17617]
Currently any error inside the transform page component is mapped as a 404 error making difficult the tracking of the real issue.
We need a better error handling inside the page component adding a 500 error page and displaying the real error in console.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/dotcms-spa/pull/62

**Comment by fabrizzio-dotCMS** [comment]
I introduced a few errors using Chrome's debugger  inside the function 
` function getUpdatedContainer(page, container) ` 
The Error page takes over the screen and render 
![Screen Shot 2019-11-25 at 2 02 46 PM](https://user-images.githubusercontent.com/37148755/69573750-5b4f8e80-0f8c-11ea-9966-6f8bcb286b3d.png)
![Screen Shot 2019-11-25 at 2 02 11 PM](https://user-images.githubusercontent.com/37148755/69573751-5b4f8e80-0f8c-11ea-8324-a1091698b751.png)

**Comment by bryanboza** [comment]
Fixed, now this is working better
