### ISSUE TITLE
Delete PP bundles rest endpoint

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17611]
Currently we don't have a rest endpoint to delete PP bundles and with the UI we have some restrictions, we need a endpoint in order to provide the user more flexibility deleting bundles.

We need two method on the endpoint

1\) DELETE a set of bundle id, user must be BE and has the permission to delete bundles
2\) DELETE all bundles older than ..., user must be BE and has the permission to delete bundles
3\) DELETE all bundles

The endpoint older than, and delete all bundles should include a way to exclude from the deleting a set of id's or the unsent bundles.

**Comment by fmontes** [comment]
1. Do we want to remove ALL bundle with any status?
2. Do we want to remove specific bundles with a specific status?

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17618

**Comment by fmontes** [comment]
### The acceptance criterua agreed with Will was:

1. You can delete: selected, all, all success or all failed
2. The delete happen in the background (there is a message in the popup that said that)
![Screen Shot 2019-12-03 at 12 51 05](https://user-images.githubusercontent.com/751424/70080124-9d4f8480-15cb-11ea-8967-f028311fa452.png)
3. After the work is done we show a toast and refresh the list:
![Screen Shot 2019-12-03 at 12 52 12](https://user-images.githubusercontent.com/751424/70080239-d0921380-15cb-11ea-880e-d9c8a7fe1351.png)

## Cases
1. If you are deleting thousands of items it happen in the background, no indicator and after the toast is show.
2. If you move to another portlet no list to refresh

**Comment by bryanboza** [comment]
After some tests we have some problems here: 
- If you upload locally any bundle and then try to delete using the selected endpoint (`/ids`) we are unable to delete the uploaded bundles locally, and we have this error on logs: https://gist.github.com/bryanboza/e063737fed305c0d303576c672bc820c

- If you try to delete a bundle directly in the endpoint but you send a user that doesn't have access to the bundle, the endpoint is returning a 200 code and it seems you delete the bundle without problems,  but the bundle isn't deleted. 
SC: https://www.screencast.com/t/Wf9lNkOqzF

- If you send an invalid id and try to delete this bundle we have an error in the log that the bundle id does not exist, but the endpoint is returning a 200 error instead 404 

- The postman tests are all in the same folder, we need to respect the recommended structure, one folder by the endpoint, this to identify easier the error in case the test fails. 

- In case you are trying to delete multiple selected bundles, sending a list of IDs, and one of those fails, we are just sending the error notification and we are not receiving the success notification about the ones that were successfully deleted.

**Comment by fmontes** [comment]
1. Working on a fix
2 and 3. That's the way we defined to work, the process happen in a separate thread because there could be thousands of bundles to delete, so we just emit a WS event with the results of the process but the endpoint return a 200 indicating that the process started.
4. Working on the fix
5. ...

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/17729

**Comment by bryanboza** [comment]
We still with problems here: 

- According to the comment on case 2 and 3, we just add the job to a queue, that's why the 200. After this, if you have permissions and find the ids we delete the bundles or not. But when you are logged as a limited user we are unable to resolve the message key. 
SC: https://www.screencast.com/t/o2tTkGen9Wuq

**Comment by fmontes** [comment]
Ooop, we miss adding a new message key fixed here: https://github.com/dotCMS/core/commit/cc38295c7999cdde93934d99a13666a28f779a52

**Comment by bryanboza** [comment]
PR: Fixing the structure of the postman test https://github.com/dotCMS/core/pull/17739

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.2 and now it is working as expected. Tested on release-5.2.2 // Postman // FF 
New related card created here: #17734
