### ISSUE TITLE
VisitorSerializer uses wrong key for geo info

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17616]
When the VisitorSerializer serializes the visitor geo-location information, dotCMS sends the geo object as the key.  See image:

![Screen Shot 2019-11-14 at 11 49 04 AM](https://user-images.githubusercontent.com/934364/68878242-59a4e180-06d5-11ea-9a3b-0c6783ad20af.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17669

**Comment by fabrizzio-dotCMS** [comment]
I had to trick the API to believe that the request was coming from an external IP address, but it looks ok. 

![Screen Shot 2019-12-02 at 11 07 25 AM](https://user-images.githubusercontent.com/37148755/69979660-504caf00-14f4-11ea-830c-54655bbb95a3.png)

**Comment by fabrizzio-dotCMS** [comment]
I had to trick the API to belive the request was coming from an external source 
![Screen Shot 2019-12-02 at 11 13 14 AM](https://user-images.githubusercontent.com/37148755/69979923-cea95100-14f4-11ea-9c8e-79aab35235e6.png)

**Comment by bryanboza** [comment]
Unable to test, we need a couple of pre-requisites at dev environment to test. Tested by @fabrizzio-dotCMS on release-5.2.2 // Postgres // FF
