### ISSUE TITLE
[Push Publishing] : Incorrect bundle audit info caused by data inconsistency

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17626]
Found when working on Support: [99710](https://dotcms.zendesk.com/agent/tickets/99710)
Reproducible in dotCMS 5.0.3, and latest master (5.2.1)

When bundles are sent from one dotCMS instance to another, an audit history is created so that the system can keep track of its publishing status across multiple Endpoints.

However, this data might become corrupt at some point, cluttering the log file with unnecessary/useless information. This confuses Sys Admins who monitor the logs, specially because almost all of the bundles mentioned in the log are **NOT** in the publishing queue anymore and/or have already failed to push.

### Steps to reproduce the behavior:
Ask @jcastro-dotcms for more details and a DB backup that can be installed in a local environment to evidence the behavior.

### Expected behavior
The Bundle Audit History in the log **MUST** provide valid up-to-date information to the user/Sys Admin.

### Additional context
The incorrect report of Bundle Audit History is caused by a combination of several factors:

1. Data inconsistencies.
2. Missing code to control this behavior.
3. Arbitrary change of the value of the `PUBLISHER_QUEUE_MAX_TRIES` property.
4. Potential network problems during the push of the bundle.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/17627

**Comment by erickgonzalez** [comment]
Tested on master and now the logs provide valid up-to-date information.
```
09:39:04.326  INFO  business.PublisherQueueJob - ===========================================================
09:39:04.326  INFO  business.PublisherQueueJob - For bundle '65379507-5e70-4757-9108-dae64658533f':
09:39:04.326  INFO  business.PublisherQueueJob - -> Status             : FAILED_TO_SEND_TO_ALL_GROUPS [4]
09:39:04.326  INFO  business.PublisherQueueJob - -> Re-publish attempts: 1 out of 3
09:39:04.326  INFO  business.PublisherQueueJob - -> NOTE               : This bundle is stalled and its Audit History will NOT be updated properly. You can safely ignore this status, or you can delete its Audit History directly from the database.
09:39:04.326  INFO  business.PublisherQueueJob - ===========================================================

```

**Comment by bryanboza** [comment]
Fixed, now this working  as expected, after test on a provided environment on release-5.2.3 // Postgres // FF
