### ISSUE TITLE
Backup Data/Assets Tool not using ASSET_REAL_PATH

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#17620]
### Describe the bug
Reproducible in latest release 5.2.1 and master.

When ASSET_REAL_PATH is configured (for example in clusters), the logic for _Backup Data/Assets_ is not picking up that value.

1. [Here the variable is declared as null](https://github.com/dotCMS/core/blob/5.2.1/dotCMS/src/main/java/com/dotmarketing/portlets/cmsmaintenance/ajax/CMSMaintenanceAjax.java#L188). 
2. [Here we are getting the value, not assigned before](https://github.com/dotCMS/core/blob/5.2.1/dotCMS/src/main/java/com/dotmarketing/portlets/cmsmaintenance/ajax/CMSMaintenanceAjax.java#L404).

### Steps to reproduce the behavior:
1. Set up the property ASSET_REAL_PATH to a different path than the default one ("/assets")
2. Start up dotCMS
3. Go to Maintenance-->Tools-->Backup Data/Assets
4. You will not get the data from your current assets.

### Additional context
Client ticket: https://dotcms.zendesk.com/agent/tickets/99704

## Acceptance Criteria
1. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17770

**Comment by bryanboza** [comment]
Fixed, now we are respecting that property. Now we have some problems generating the zip, but we will work on this problem here #17738
