### ISSUE TITLE
Filtering content by date range does not seem to work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17621]
In dotCMS 5.2, on the demo site, these queries do not work:

```
+contentType:News +News.sysPublishDate:[20110629 TO 20110630] 
+contentType:News +News.sysPublishDate:[06/29/2011 TO 06/30/2011] 
+contentType:News +News.sysPublishDate:[06/29/2011 00:00:00 TO 06/30/2011 00:00:00]
```

And this returns invalid results:
```
+contentType:News +News.sysPublishDate:[20110629170000 TO 20110629180000]
```

Acceptance Criteria:

- [x] Integration test

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17650

**Comment by nollymar** [comment]
**Note to Doc:** We should include on [this doc](https://dotcms.com/docs/latest/content-search-syntax#DateRange) the list of all date formats supported by dotCMS in a lucene query:

- MM/dd/yyyy hh:mm:ssa
- MM/dd/yyyy hh:mm:ss a
- MM/dd/yyyy hh:mm a
- MM/dd/yyyy hh:mma
- MM/dd/yyyy HH:mm:ss
- yyyyMMddHHmmss
- MM/dd/yyyy HH:mm
- MM/dd/yyyy
- yyyyMMdd
- hh:mm:ssa
- hh:mm:ss a
- HH:mm:ss
- hh:mma
- hh:mm a
- HH:mm

**Comment by freddyucv** [comment]
Passed Internal QA: 
Tested with the queries:

+contentType:News +News.sysPublishDate:[20110629 TO 20110630] 
+contentType:News +News.sysPublishDate:[06/29/2011 TO 06/30/2011] 
+contentType:News +News.sysPublishDate:[06/29/2011 00:00:00 TO 06/30/2011 00:00:00]
+contentType:News +News.sysPublishDate:[20110629170000 TO 20110629180000]

**Comment by bryanboza** [comment]
Fixed, now this is working fine, tested on release-5.2.2 branch
