### ISSUE TITLE
SPA: "Shop" section listing not rendering

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17628]
When you start the server and browse to `Shop > Apparel > XXX` or any other link under "Shop" the page is blank.

## Context
Not sure why, but the contentlets in the page render responde is empty:
 
<img width="510" alt="Screen Shot 2019-11-18 at 16 34 25" src="https://user-images.githubusercontent.com/751424/69099821-57b68780-0a21-11ea-9d71-c53ef8a85373.png">

## Acceptance Criteria
1. Make Shop section render correctly `(/store/apparel/mens)`
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
@wezell looking at this issue, in the response  from `starter.dotcms` there are no contentlets added in the container.

if you start going deeper, in the properties page, there's a template `Store - Product Line` associated, that has a container called `Product Line` with `product-line-container.vtl` in the content

So looking at, https://starter.dotcms.com/application/vtl/store/product-line-container.vtl, seems like the content of the shop pages are being pulled from a related `ProductLineLandingPage.childProductLines`.

According to @fmontes up to this moment, the way the dotcms-spa works is that we receive from the starter the html code in the response so we just rendered it on the dotcms-spa app. But if this is a new way to add content in pages, then we need to find a way to know what we should do on this new approach.

@wezell what do you suggest about how we should handle this?

**Comment by alfredo-dotcms** [comment]
Response from the server

`[
    {
        columns: [
            {
                containers: [
                    {
                        identifier: '854ad819-8381-434d-a70f-6e2330985ea4',
                        uuid: '1572981893151',
                        iDate: 1567004201530,
                        type: 'containers',
                        owner: null,
                        inode: '1c405844-fb05-4fd7-bf54-95ddb97dab30',
                        source: 'DB',
                        title: 'Product Line',
                        friendlyName:
                            'Used in store template to List all of the product lines',
                        modDate: 1567004201545,
                        modUser: 'dotcms.org.1',
                        sortOrder: 0,
                        showOnMenu: false,
                        code:
                            '#dotParse("/application/vtl/store/product-line-container.vtl")',
                        maxContentlets: 0,
                        useDiv: false,
                        sortContentletsBy: '',
                        preLoop: '',
                        postLoop: '',
                        staticify: false,
                        luceneQuery: '',
                        notes: '',
                        locked: false,
                        versionId: '854ad819-8381-434d-a70f-6e2330985ea4',
                        versionType: 'containers',
                        deleted: false,
                        working: true,
                        archived: false,
                        permissionId: '854ad819-8381-434d-a70f-6e2330985ea4',
                        name: 'Product Line',
                        live: true,
                        permissionType:
                            'com.dotmarketing.portlets.containers.model.Container',
                        idate: 1567004201530,
                        new: false,
                        categoryId: '1c405844-fb05-4fd7-bf54-95ddb97dab30',
                        acceptTypes: '',
                        contentlets: []
                    }
                ],
                widthPercent: 100,
                leftOffset: 1,
                styleClass: null,
                preview: false,
                width: 12,
                left: 0
            }
        ],
        styleClass: null
    }
];
`

**Comment by wezell** [comment]
So the SPA and the PageAPI are not set up to handle 0 content containers.  We need to remove them from our starter site and instead allow a user to add a "Product Line Widget" that can be added that will show the results of the products - this basically makes our shop unmanageable via SPA.  @DeanGonzalez @fishsmith we need to discuss.

**Comment by fmontes** [comment]
Chatting with @wezell he came up with the idea of using the `contentType` of the page, in this case `ProductLineLandingPage` as a flag and if we confirm is this instead of rendering the page as usual we can use a NextJs static page to render this one and inside the `getInitialProps` we pull the products and rendering as React Components.

**Comment by wezell** [comment]
### Notes
Product Line is a Page that has a ContentType of `ProductLineLandingPage` and is has relationships/children of Children of `ProductLineLandingPage`s AND `Products`

When querying for the product line and `ProductLineLandingPage` children, you can call the contentAPI with the page id and pass a `depth/1`
`http://localhost:8080/api/content/id/684a7b76-315a-48af-9ea8-967cce78ee98/depth/1`

When querying for product line `PRODUCT` children, you need to query elasticsearch
```
http://localhost:8080/api/content/render/false/type/json/query/+contentType:Product%20+Product.productLine:94ff9a9f-0568-42fd-b1de-66e21fb5fcdf%20+languageId:1%20+live:true%20/orderby/Product.title
```



What things are:
```
https://starter.dotcms.com/store/                <-- just a page
https://starter.dotcms.com/store/snow/           <-- Product Line Page
https://starter.dotcms.com/store/snow/ski-gear   <-- Child Product Line Page
https://starter.dotcms.com/store/products/atomic-vantage-95-c-womens-skis   <-- Child Product detail Page
```
