### ISSUE TITLE
SPA: Fix blog detail page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17632]
### Describe the bug
If you try to render a blog detail page it shows all broken.

### Steps to reproduce the behavior:
1. Go to http://localhost:3000/blog/post/top-8-areas-to-dive-in-french-polynesia
2. Page is all broken

### Expected behavior
Page should render as expected like: https://starter.dotcms.com/blog/post/top-8-areas-to-dive-in-french-polynesia

### Screenshots
<img width="1792" alt="Screen Shot 2019-11-18 at 17 03 41" src="https://user-images.githubusercontent.com/751424/69101510-643cdf00-0a25-11ea-8697-835c900f893a.png">

## Acceptance Criteria

1. Render the blog post detail
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
looking at the response from the PageAPI when `blog-detail` page requested, the response does not contains the HTML code rendered
https://gist.github.com/alfredo-dotcms/8c2442d180f196b94b510c7dedd71722

some work may be needed on the starter

**Comment by wezell** [comment]
You need to use React Slugs to resolve the content on the blog-detail page, not the page API - it works like the news detail page on the SPA 1.0

**Comment by fmontes** [comment]
I think here we can use [dynamic routes](https://nextjs.org/docs#dynamic-routing) from NextJS is a cool example on how to combine nextjs feature with dotcms to do this detail pages.

We can create a nextjs blog item page and with the url title we fetch the data in the server side of node and render the blog item.

Is a cool approach to show off how nextjs feature can work along with dotcms apis.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/dotcms-spa/pull/69

**Comment by bryanboza** [comment]
We need some work here in the search component, when you type something here we are not clearing the component, we just show the word overriding the 'search' 
![search](https://user-images.githubusercontent.com/2641437/70748130-03848780-1cef-11ea-9618-adb42ce894bf.png)

**Comment by bryanboza** [comment]
The blog is throwing an error if there is not publish date
![error1](https://user-images.githubusercontent.com/2641437/70749338-bb1a9900-1cf1-11ea-919c-0f54268f4615.png)
