### ISSUE TITLE
Mock the delete bundles UI

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17636]
We need to show the user a button and on click pull up a dialog with the options of which type of bundle want to remove, we are taking the same approach as workflows in Content Search.

## Acceptance Criteria

1. Admin users can delete everything
2. Other users
    - Can hit "delete all" but only delete theirs bundles
    - Can select and manually delete others users (lower role)
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
### Add new button

<img width="1792" alt="Screen Shot 2019-11-19 at 10 43 27" src="https://user-images.githubusercontent.com/751424/69168037-88e39600-0abb-11ea-99c4-6494a21b0726.png">

When button clicks, show the dialog:

![Screen Shot 2019-11-19 at 10 43 27](https://user-images.githubusercontent.com/751424/69168084-a1ec4700-0abb-11ea-8204-5f87329a695b.jpg)

**Comment by wezell** [comment]
Note -bundles can only be deleted if the user is a CMS admin or is the owner of the bundle.

**Comment by fmontes** [comment]
@wezell users can see bundles they own but also bundles created per another user "below" it. Like since Chris have Jane Reviewer under, Chris will see Jane's bundle which mean he will be able to remove those.
