### ISSUE TITLE
SPA: Contact Us page not render

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17633]
### Describe the bug
When you go to `/contact-us` the page only show header and footer, no content

### Steps to reproduce the behavior:
1. Go to `/contact-us`
2. Page doesn't show content

### Expected behavior
It should show and submit the form.

### Screenshots
<img width="1792" alt="Screen Shot 2019-11-19 at 07 52 16" src="https://user-images.githubusercontent.com/751424/69152189-98ee7c00-0aa1-11ea-8eda-3eb77f0fd816.png">

### Additional context
Check in the http://starter.dotcms.com/c to see how the content was added.

## Acceptance Criteria

1. Contact Us page should render
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
this only happens when you navigate internally, if you put the url on a new browser tab, the form is rendered
