### ISSUE TITLE
Research bundles status and user permissions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17638]
We need to figure out if a user can see ALL the bundles or only the ones assigned or created by it.

Also need to understand all the status a bundle can be at and which ones can be deleted.

**Comment by erickgonzalez** [comment]
Delete All: regardless status

Delete Failed ones (status 4-8): FAILED_TO_SEND_TO_ALL_GROUPS, FAILED_TO_SEND_TO_SOME_GROUPS, FAILED_TO_BUNDLE, FAILED_TO_SENT, FAILED_TO_PUBLISH

Delete Success (status 9): SUCCESS 

Only users with the same Role or a Higher Role can see/delete the bundles (e.g. if Jane Reviewer PP a  bundle, Chris Publisher can see that bundle and delete it).

**Comment by wezell** [comment]
Should we just execute on this and make bundles implement permissionable? 

See: #16924

**Comment by fmontes** [comment]
Ok, the let's just close this one, we keep up deleting the bundles as it is and then work on the permissionable issue.
