### ISSUE TITLE
[core] : Invalid FK still present in .sql files

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17647]
Related to #13373
Reported via Support: [99850](https://dotcms.zendesk.com/agent/tickets/99850)
Reproducible in dotCMS 4.3.3 through latest master (5.2.2).

As per https://github.com/dotCMS/core/issues/13373 , the `FK_workflow_task_asset` foreign key was removed from dotCMS via the following Upgrade Task: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task04235RemoveFKFromWorkflowTaskTable.java

However, it's still present in the .sql scripts, e.g., https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/postgres.sql#L2251

It must be removed as several customers are still bumping into that problem.

### Expected behavior
The FK should not exist anymore.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
Reported by another customer: https://dotcms.zendesk.com/agent/tickets/100005

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/17742

**Comment by wezell** [comment]
Adding to our bug sprint - thanks Jose for the PR!

**Comment by bryanboza** [comment]
Fixed.
