### ISSUE TITLE
Restore Devwiki navigation

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17643]
Currently broken. 

https://auth5.dotcms.com/devwiki/

**Comment by nollymar** [comment]
Fixed. Now it's working

<img width="1481" alt="Screen Shot 2019-11-20 at 12 17 09 PM" src="https://user-images.githubusercontent.com/8741395/69261533-b994ff80-0b8f-11ea-916c-a19b5da14f12.png">
