### ISSUE TITLE
Add travis into core-web

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#17654]
## Acceptance Criteria

1. Run test to every Pull Request into google cloud and notify result in travis.
2. Slack notifications.
3. Change de Pull Request "Details" link to target to the test html report.
4. Update dev wiki.

**Comment by freddyucv** [comment]
Dev Wiki: https://auth5.dotcms.com/devwiki/running-core-web-test-in-travis

**Comment by wezell** [comment]
done
