### ISSUE TITLE
Long polling from back-end UI continues even after login is no longer valid

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#17656]
### Describe the bug

If a user is logged into the back-end UI, and their credentials become invalid (such as when the server is restarted), the Ui continues long polling.  This logs repeated messages in the log files similar to the following:

```
[22/11/19 17:49:01:108 GMT] WARN rest.WebResource: InitDataObject Error: uri:/api/ws/v1/system/events err:Invalid User
```

### Steps to reproduce the behavior:
1. Log into dotCMS in your browser.
2. Reset the dotCMS server.
3. After the server comes back up, view the logs.

### Expected behavior

Ideal behavior would probably be:

1. Stop long polling when a 401 is returned, or when it gets some number of other failures in a row.
2. Restart long polling when the user takes an action.

**Note:** Automatically logging the user out and returning them to the login screen is _not_ suggested as a solution, because it means that if the user has any unsaved changes (such as if they've typed into the Content editing screen without hitting "Save"), they'll lose those changes.  Currently unsaved changes are not currently lost if the connection to the server is lost or your credentials on the server become invalid, so making a change that could potentially change this and cause loss of data is probably not a good direction to go.

### Desktop (please complete the following information):
 - OS: All
 - Browser: Chrome
 - Release: 4.2.1 (demo site)

### Additional context

This is a minor issue, and I'm not sure it's worth taking the time to fix, but I'm logging it to record it.  

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test
5. No data loss when user has unsaved changes and connection is lost or credentials are invalidated.

**Comment by oarrietadotcms** [comment]
Client having this problem:

> But I believe it is certainly major issue and worth spending time to fix, browser endlessly calls backend and puts load on servers and getting 401 errors..

https://dotcms.zendesk.com/agent/tickets/101071

**Comment by nollymar** [comment]
PR Core: #20208 taken from commit https://github.com/motiv-solutions/support/commit/6c11bbd4ada113a77369a35df8e0d0293a93e4e4

**Comment by yolabingo** [comment]
We are seeing issues with a cloud customer on 4.3.3 related to this. Browsers send thousands of requests/minute which eventually can cause a deadlock in postgres and requires we restart dotcms
`GET /api/ws/v1/system/events HTTP/1.1 401 12 "https://example.com/dotAdmin/"
`

The same client (I think? or coming from the same IP with the same user agent) will occasionally send request like
`GET /html/common/keep_alive.jsp?r=1619798867416
`

about every 15 seconds. We see these alternate in the access log - either thousands of requests/minute for `/api/ws/v1/system/events` or a few requests/minute for `/html/common/keep_alive.jsp?r=xxxx` but they are exclusive - when one begins, the other ends. Just an observation.

**Comment by bryanboza** [comment]
Fixed, according to the card documentation now this is working as expected... Tested on release-21.05 // Postgres // FF
