### ISSUE TITLE
SPA: Create <Select /> component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17653]
In the original theme there is a `Select` components created with a JS library, we need to recreate this with a React component.

### Mock
<img width="341" alt="Screen Shot 2019-11-21 at 16 23 19" src="https://user-images.githubusercontent.com/751424/69381936-8465db80-0c7b-11ea-81fc-386766770664.png">

### Describe the solution you'd like
Recreate the component from the library with React use the same css class name but the events use React.

### Technical Approach
1. Download the theme [here](https://drive.google.com/file/d/1uU84O4uHnW4-6t4OqcwxKIDB15tY4dfT/view?usp=sharing)
2. Open `site/header-classic.html`
3. Around line 230 you'll see the select

### Additional context
1. @alfredo-dotcms did this same approach with the carousel
2. Use this components in the language select in the header

## Acceptance Criteria
1. Create and use `Select` component
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by dotcmsCodeReview** [comment]
Can we use our we component?

>

**Comment by hmoreras** [comment]
After review this taks, the current template include a library call Select2. We don't want create a custom library that do the same. So we just are adding the arrow to the current `select` element that is missing in the current starter style. By adding  to this file `/application/themes/travel/css/custom-styles/components/_forms.scss` the following code: 


 // Form select
select.form-input {
  padding-right: 38px;
}

// Form select arrow
 .form-wrap-select:after {
    display: inline-block;
    font-weight: 400;
    content: "";
    font-family: "Material Design Icons";
    font-size: 20px;
    transform: rotate(0deg);
    position: absolute;
    top: 38px;
    right: 15px;
    pointer-events: none;
 }
 
 .form-wrap-select.no-label:after{
    top: 38px;
 }

**Comment by bryanboza** [comment]
The language component is not working as expected, when you select some different language in the drop-down, we need to refresh the page and translate
