### ISSUE TITLE
Include URLMapped content in page api

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17666]
If we ask the page endpoint a page wich is a UrlContentMap page we need to also render the contentlet associated with that page.

More info about UrlContentMap: https://dotcms.com/docs/latest/using-url-mapped-content

### Additional context
Right now we get the page but not the content associated with it which mean that in a SPA we can't render the content of the page, we need to get that in the response of the API in order for us to render the contentlet in the page. It should be at top level of the response object.

## Acceptance Criteria
1. Render conent in page api with URLContentMap 
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/17677

**Comment by fmontes** [comment]
![Screen Shot 2019-12-09 at 14 34 12](https://user-images.githubusercontent.com/751424/70470635-16018580-1a91-11ea-940a-90d8004dd8d6.png)

**Comment by wezell** [comment]
We just had a partner hit this issue with an implementation. I am glad to get this done.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
