### ISSUE TITLE
Render page contentlet object in the page api endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17665]
At the page render api `/api/v1/page/render/url-to-page` we have a `page` property but it doesn't contain ALL the contentlet information of a page (since pages are contentlets).

We need to return all the contentlet object of the page in this endpoint BUT we have to make sure we don't remove all the current page properties since we are using them in edit mode:

- pageURI
- title
- locked
- rendered
- canLock
- identifier
- canRead
- liveUser
- lockedByName
- workingInode
- remoteRendered
- inode

## Acceptance Criteria
1. Render `contentlet` of the page in page object
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Heu @wezell I  have a doubt here: 

- Since the page is a piece of content, we should respect the permissions of this content here, but if the page have the `CMS_Anonimous` we are unable to render without authenticating.  And also, If I try with an intranet user, this doesn't have view permissions to this page, but I'm able to render without problems, then not sure what permissions we are respecting here.

**Comment by wezell** [comment]
This seems right behavior - so here are our "rules" that should govern most of our content related apis moving forward

1. Users need a valid user/api key to be able to access them.  
2. "Front end" users should be able to read LIVE content marked CMS Anonymous + any other content that they have read permissions to.  A "front end" user should never be able to read WORKING content
3. In most cases, "back end" users should be able to read LIVE and WORKING content marked CMS Anonymous + any other content that they have read permissions to

Keep in mind these rules just rough guidelines, but the idea is that if you want to set up the SPA that will only show live content, you should use a an API key for a front end user.  

If you want to set up the SPA to be able to "preview" unpublished or drafted content, you should use an API key for a back end user

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.3 // Postgres // FF
