### ISSUE TITLE
Language Variable with space does not resolve

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17679]
If you create a new language variable called "testing 1" and create english and spanish versions of it - and then call it on a page via $text.get("testing 1") . it will not resolve.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17712

**Comment by bryanboza** [comment]
Fixed, now we are able to resolve those variables without problems. Tested on release 5.2.3 // Postgres // FF
