### ISSUE TITLE
Add creation/updating/deleting of Languages to LanguageResource

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#17671]
The current version of the LanguageResource only allows listing Languages, but neither saving/updating nor deleting. 

We need to implement endpoints for:
* Saving a new Language
* Updating an existing Language
* Deleting an existing Language

Acceptance Criteria:
- [x] e2e/postman test

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17704

**Comment by dsilvam** [comment]
Note for QA/Doc

Three new endpoints were created for the already existing Language Resource:
1. Save a new Language. ` POST /v2/languages/`
Body (`languageCode` and `language` are mandatory) :
`{
	"languageCode":"it",
	"language":"Italian", 
	"countryCode":"IT", 
	"country":"Italy"
}`. 

     Returns 200 code and the new created language.

2. Update an existing Language `PUT /v2/languages/{languageId}`
Body (`languageCode` and `language` are mandatory) :
`{
	"languageCode":"it",
	"language":"Italian Updated", 
	"countryCode":"IT", 
	"country":"Italy"
}`

    Returns 200 code and the updated language.

3. Delete an existing Language. `DELETE /v2/languages/{languageId}`
No body. Returns 200 code.

**Comment by wezell** [comment]
Why a `/v2`?  Can't we consolidate the LanguageResources?

**Comment by dsilvam** [comment]
@wezell `/v2` has been around since 2018/5.0.0

**Comment by wezell** [comment]
Puke.  Ok

**Comment by nollymar** [comment]
**Tests Results: ** Needs work

1. The update operation is creating a new language instead of updating an existing one
2. It is possible to create the same language multiple times without changing any field. It happens in UI too, so if @wezell agrees, this issue can be fixed on a different task
3. The way errors are handled should be unified. For example: if a field is missing during language creation, a JSON with the error message is returned and nothing is logged in catalina.out. However, if any language is updated/deleted with an invalid id, a JSON with the error message is returned and this message is logged in catalina.out too: 
```
09:52:47.435  INFO  util.SecurityLogger - class com.dotcms.rest.exception.mapper.DoesNotExistExceptionMapper : Language not found -- ip:0:0:0:0:0:0:0:1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17736

**Comment by nollymar** [comment]
Tested again and now it works correctly

**Comment by bryanboza** [comment]
Problems with the delete endpoint, this when you try to delete a language that is used by some piece of content. If you try the same case from UI we have an error that you can't delete that language, but if you try from REST, we have an unexpected (500) error and we print this error on logs
SC: https://gist.github.com/bryanboza/434877c35a960c1b624ac7a7e90b0681

**Comment by dsilvam** [comment]
PR to fix deleting language with existing content on it: https://github.com/dotCMS/core/pull/17755

**Comment by wezell** [comment]
What are the permissions needed to add or remove a language using the resource?  It should be limited to users who have access to the language portlet or be admin only.

**Comment by dsilvam** [comment]
@wezell it was implemented like that https://github.com/dotCMS/core/blob/6aa261ce2791e509509e3561247ae345c676d58c/dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java#L167-L168

**Comment by nollymar** [comment]
After the fix provided by @dsilvam , the issue reported by @bryanboza is not happening anymore

**Comment by bryanboza** [comment]
Fixed,  tested on release-5.2.3 // Postgres // FF

**Comment by dsilvam** [comment]
Putting proper label

**Comment by dsilvam** [comment]
Additional changes for postman tests: https://github.com/dotCMS/core/pull/17780
