### ISSUE TITLE
Tags disappear from new File Asset Content Type on copy/paste - version 4.3.3

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17675]
### Describe the bug
Tags disappear from new File Asset Content Type on copy/paste.

### Steps to reproduce the behavior:
1. Create new File CT with a tag field (copy current image CT/add tag field)
2. Create asset of new CT with tags in a folder. Save/publish
3. Copy the file to a different folder & open it

### Expected behavior
File asset should retain its tags

###Actual Behavior
Tags disappear.

### Screenshots

**New CT with tag field located in "images" folder**
![image](https://user-images.githubusercontent.com/49727631/69972753-cc8cc580-14e7-11ea-8bea-23d62ef122eb.png)

**tags intact**
![image](https://user-images.githubusercontent.com/49727631/69972533-6738d480-14e7-11ea-9b74-86def53f2092.png)

**Copied over to new folder**
![image](https://user-images.githubusercontent.com/49727631/69972631-96e7dc80-14e7-11ea-811b-3d9656f53eda.png)

**Tags missing**

![image](https://user-images.githubusercontent.com/49727631/69972663-a404cb80-14e7-11ea-8fab-bda1b5470380.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser chrome / ff
 - Version dotcms 4.3.3

**Comment by hans-auer** [comment]
This issue also happens when using the method below:

`APILocator.getFileAssetAPI().moveFile()`
