### ISSUE TITLE
Past Time Machine not working

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17684]
Tested on latest demo.dotcms.com dotCMS 5.2.1 version.

After going to past time machine and setting these settings on demo.dotcms.com:

<img width="759" alt="Screen Shot 2019-12-03 at 1 10 54 PM" src="https://user-images.githubusercontent.com/1569167/70081743-ba398700-15ce-11ea-80f5-407e46cedfdc.png">

I got this result when trying to view the past time machine:

<img width="1595" alt="Screen Shot 2019-12-03 at 1 11 43 PM" src="https://user-images.githubusercontent.com/1569167/70081777-c6254900-15ce-11ea-873e-992698670341.png">

**Comment by nollymar** [comment]
Tested on 5.2.3 and it's working fine

**Comment by bryanboza** [comment]
Able to reproduce: 

- Seems we have a language conflict here if you try to create a time machine snapshot just in English that works. 
- If you try to create this just in Spanish, that shows the options to see in English and Spanish,  the Spanish works, but if you select English got the error. 
- If you create a new language and then the snapshot in this language when you try to see that snapshot t just appear English in the languages dropdown. And shows the error.
SC: https://www.screencast.com/t/Wmlv9mymK9uh

Tested on release-5.2.3 // Postgres // FF

**Comment by nollymar** [comment]
@wezell how do you want to handle the case @bryanboza describes? The error actually happens because there is no page in Italian

**Comment by wezell** [comment]
I think those should be moved to a new issue.  They are not new behaviors

**Comment by bryanboza** [comment]
@wezell.... This is the same problem why Dean report the card, and are not doing changes here, then not sure if make sense create a new card, I think we just need to prioritize again the card and move to another branch.

**Comment by bryanboza** [comment]
Unable to reproduce on master... The reported cases moved to a new card (#17778)
