### ISSUE TITLE
Integration of services with dotCMS existing implementations

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17691]
In dotCMS we already have multiple implementations that could use the new Integration services and secrets store implementations.

- Google translate actionlet using a google translate service
- The Static Publish (AWS) key could be read from the global dotCMS keys service
- AWS Rekognition - https://github.com/dotCMS/com.docms.rekognition.actionlet
- OAuth Plugin
- SAML Plugin

## Acceptance Criteria
1. Documentation (dev-wiki)

**Comment by wezell** [comment]
This has been completed
