### ISSUE TITLE
UI: Services listing portlet

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17693]
This page will list all installed services both active and not active. 

It will display the following elements
- Logo
- Title
- Button to Configure

Notes:
See attached example 

![Screen Shot 2019-11-27 at 2 22 05 PM](https://user-images.githubusercontent.com/934364/70169738-647de100-1699-11ea-8086-6897621ef381.png)

**Comment by jgambarios** [comment]
### New mockup for the integration services listing

![Integrations 01 1 -V2 (grid view)](https://user-images.githubusercontent.com/923947/71831069-be454280-306d-11ea-946c-73363514e386.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/73031365-7eb67e80-3e01-11ea-84c1-5b2cf0c28ae3.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/73031386-8f66f480-3e01-11ea-83aa-f5bd750bb037.png)

No Configuration (hover)

**Comment by alfredo-dotcms** [comment]
PR `core-web` https://github.com/dotCMS/core-web/pull/1263/files

**Comment by jgambarios** [comment]
Improvements will be handle in https://github.com/dotcms/core/issues/17957
