### ISSUE TITLE
UI: Edit Integration Service for host Screen

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17694]
This is the screen you will see when you click the button form the list page. This page will have varying numbers of text fields, checkboxes and files based on the requirements of the service.

Each text field can have the following information:
- Title/Label (required)
- Hint (optional)
- Placeholder Text (optional)
- Toggle (this will hide the input values, like a password field does) . _A toggle applies for extra params only_

Each Checkbox will have
- Title/Label (required)
- Hint (optional)

~Each File input will have~
~- Title/Label (required)~
~- Hint (optional)~
_Input file implementation is out of the scope of this task_

### Host selector
Each service must have a host selector, meaning the saved properties values for the service are saved by host.

### Ability to add extra properties
This feature will be implemented on this task https://github.com/dotCMS/core/issues/18216

### Examples of different Services
---
![Screen Shot 2019-11-27 at 2 25 09 PM](https://user-images.githubusercontent.com/934364/70170193-33ea7700-169a-11ea-895a-17671a20de2f.png)
---
![Screen Shot 2019-11-27 at 2 23 14 PM](https://user-images.githubusercontent.com/934364/70170202-38af2b00-169a-11ea-9a82-cbbf3e261bcd.png)

--
![Screen Shot 2019-11-27 at 2 22 55 PM](https://user-images.githubusercontent.com/934364/70170203-38af2b00-169a-11ea-88f9-61710f983fc5.png)

See this animated gif re:gitlab for a mental model of the above:

![integrations](https://user-images.githubusercontent.com/934364/68979497-ba164a80-07cb-11ea-92c7-33b374db46a3.gif)

**Comment by jgambarios** [comment]
### New mockups for the Integration services edit screen

![Integrations 03 - V1](https://user-images.githubusercontent.com/923947/71831254-1bd98f00-306e-11ea-80a1-6d7db80f3871.png)

**Comment by wezell** [comment]
Text properties should be a textarea that can grow with a max-height of ~600px and the textarea should use a fixed-width font.  The initial height of the textarea should match our text field height.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1293

**Comment by alfredo-dotcms** [comment]
> Text properties should be a textarea that can grow with a max-height of ~400px and the textarea should use a fixed-width font. The initial height of the textarea should match our text field height.

this will be addressed on another ticket

**Comment by nollymar** [comment]
**Passed internal qa**
