### ISSUE TITLE
Problems editing templates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17709]
When you go to the template portlet and try to edit an existing template we have some problems here and we are unable to edit. 

- First, when you click to edit the template we have a lot of noisy WARN in the log related to the DB transaction: 
https://gist.github.com/bryanboza/ad026117e782b552e6c0a66ffb657780

- Then If you try to remove a container from the template, we are unable to remove a new instance of the "Body" or "Sidebar" text appears below the container; doing this multiple times results in multiple instances of the text
SC: https://www.screencast.com/t/TGXZkKxN

### Steps to reproduce the behavior:
1. Login as admin
2. Go to Site --> Templates 
3. Select one in the list to edit 
4. Try to remove the existing containers  

### Expected behavior
We need to be able to add//delete containers without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by x0rsw1tch** [comment]
Hello @bryanboza. Any chance on getting an ETA or release target for this?
