### ISSUE TITLE
You ca not use Persona Base Type in GraphQL After apply license

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#17716]
### Describe the bug
If you start dotCMS without License and then apply one but not restart the tomcat server, then the persona base type is not working (return a HTTP 500 error if you run a query with persona base type)

### Steps to reproduce the behavior:
1. Start Tomcat
2. Apply License
3. Send the follow query into GraphQL

```
{
  personaBaseTypeCollection(limit:30) {
    title
    modDate
  }
}
```
4. You will get a 500 http error
5. Restar Tomcat
6. Request the query again and it'll be work

### Expected behavior
it should worj without restart tomcat

### Screenshots

<img width="1409" alt="bug" src="https://user-images.githubusercontent.com/10408015/70438787-26dfd600-1a54-11ea-956a-2ef92967d87c.png">

**Comment by wezell** [comment]
Does a cache flush fix it?

**Comment by nollymar** [comment]
I think this is fixed on https://github.com/dotCMS/core/issues/17717

**Comment by bryanboza** [comment]
The same thing is happening if you remove the license, after remove you are able to continue using personas and forms, you need to restart the server.
