### ISSUE TITLE
Unable to add widgets in the sidebar containers 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17710]
When you try to add a new widget into a sidebar container, we have an error on logs and when you change the tab to preview or try to save the page the widget is disappearing. 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page using a template with sidebar 
3. Edit the page 
4. try to add a widget into the sidebar container 
5. Check your log file 

### Expected behavior
Since this is a container, we need be able to add widgets here without problems 

### Screenshots
https://www.screencast.com/t/U7l5hA6R1l5R

### Desktop (please complete the following information):
Tested on master // Postgtres // FF

**Comment by x0rsw1tch** [comment]
Hello @bryanboza. Any chance on getting an ETA or release target for this?

As an aside, this issue isn't limited to adding widgets to a sidebar container. Any pre-existing contentlets in the sidebar will also not render. This is how the issue was initially discovered, I forgot to mention this in the forum.

**Comment by erickgonzalez** [comment]
Unable to reproduce with the latest master. Created a new template with a sidebar, a page using that template and was able to add widgets/content to the sidebar without issues.

https://www.screencast.com/t/NSMzUJC8Nj

**Comment by x0rsw1tch** [comment]
@erickgonzalez @bryanboza 

I was also able to get the sidebar widget to render properly with the file-based containers on the demo site just now.

However I tested again, on the demo site, using regular (legacy?) containers and it's still not working properly. 

Video: https://drive.google.com/file/d/1V2daej-4pyozuPISHquMZ9mWiAJ3SQDZ/view?usp=sharing

**Comment by erickgonzalez** [comment]
Hi, @x0rsw1tch thanks for the new info! I was able to reproduce using the regular containers (not the file-based ones) as you mentioned, gonna take another look at this issue.

**Comment by erickgonzalez** [comment]
Seems that in the latest master that issue was already fixed. Can not reproduce with file-based containers either with non-file based ones.

https://www.screencast.com/t/3E4T0xwf

**Comment by bryanboza** [comment]
Fixed, tested on master and works as expected
