### ISSUE TITLE
GraphQL: null is returned when a base type does not have a content type 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17717]
### Describe the bug

A null object is returned and an exception is thrown when using a fresh installation **without license** and running this query: 

```
{
formBaseTypeCollection(limit: 20) {
    title
  }
}
```

**Log: ** https://gist.github.com/nollymar/238e72836c4a96c8d08be7741d14c706

### Steps to reproduce the behavior:
1. Start a fresh installation without setting a license
2. Run the query

### Expected behavior
The system should handle the exception and return an empty list

## Acceptance Criteria
- [ ] Integration test

**Comment by bryanboza** [comment]
The same thing happens with license, and also with `personaBaseTypeCollection`

**Comment by nollymar** [comment]
Dupe: https://github.com/dotCMS/core/issues/17716

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17765

**Comment by fabrizzio-dotCMS** [comment]
When running without a license the following is returned 

`{
  "data": null,
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'formBaseTypeCollection' in type 'Query' is undefined @ 'formBaseTypeCollection'",
      "locations": [
        {
          "line": 2,
          "column": 1,
          "sourceName": null
        }
      ],
      "description": "Field 'formBaseTypeCollection' in type 'Query' is undefined",
      "validationErrorType": "FieldUndefined",
      "queryPath": [
        "formBaseTypeCollection"
      ],
      "errorType": "ValidationError",
      "path": null,
      "extensions": null
    }
  ]
}`

No issues are reported on the log. 

If I apply the license and restart the server then I get 
`{
  "data": {
    "formBaseTypeCollection": [
      {
        "title": "Jason"
      }
    ]
  }
}`

The license state seems to be cached at all times. In order to see the expected behavior, I need to restart the server. But that seems forgivable.

**Comment by bryanboza** [comment]
Fixed, now we are handling those errors, new enhancement reported here #17716
