### ISSUE TITLE
Navigate to first portlet of section when menu is collapsed

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17720]
When the menu is collapsed and the user clicks in any of the icon we need to make it navigate to the first portlet of the section clicked.

For example, if we click here:
<img width="71" alt="Screen Shot 2019-12-10 at 07 11 29" src="https://user-images.githubusercontent.com/751424/70532306-61ad4100-1b1c-11ea-81a7-74d4f6968e84.png">

We have to navigate to:
<img width="199" alt="Screen Shot 2019-12-10 at 07 12 37" src="https://user-images.githubusercontent.com/751424/70532375-86a1b400-1b1c-11ea-9de1-5d06c117af7a.png">

**Comment by hmoreras** [comment]
This is happening already, after the user clicks, it expand the menu and open the first item.  Instead should we keep the menu collapsed and go to the fist portlet in that section ?

**Comment by wezell** [comment]
This is already done here: https://github.com/dotCMS/core-web/tree/issue-17707-nav-state
