### ISSUE TITLE
Show tooltip with section name when menu is collapsed

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17721]
When the user hover any of the items of the collapsed menu we need to show a tooltip **to the right** with the text of the _name of the section._

<img width="339" alt="Screen Shot 2019-12-10 at 07 14 01" src="https://user-images.githubusercontent.com/751424/70532473-bbae0680-1b1c-11ea-876b-97d958e0a60f.png">

The texts:

<img width="199" alt="Screen Shot 2019-12-10 at 07 15 45" src="https://user-images.githubusercontent.com/751424/70532576-f57f0d00-1b1c-11ea-970c-01fc5919eb4b.png">

We already using the [primeng tooltip](https://www.primefaces.org/primeng/#/tooltip) in others [components](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/dot-copy-button/dot-copy-button.component.html#L2)

**Comment by wezell** [comment]
Works well, minor changes:
1. min-width: 100px
2. max-width: 150px
3. padding: 12px 18x;
4. Text align center 

![Screen Shot 2019-12-16 at 11 41 31 AM](https://user-images.githubusercontent.com/934364/70925398-25388400-1ff9-11ea-9903-864df39def2c.png)
