### ISSUE TITLE
Uploading a bundle with the system workflow breaks the default workflows

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17726]
As part of the work made in https://github.com/dotCMS/core/issues/17464 we need to generate a new starter when we are ready to release the missing default action changes.

**Comment by wezell** [comment]
This is what I am seeing on starter - does not look right:

![Screen Shot 2020-02-04 at 5 09 19 PM](https://user-images.githubusercontent.com/934364/73791909-3720e280-4771-11ea-8466-2416b8658585.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18020

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the problems after the last changes, tested trying to upload bundles generated in previous versions using the default WF. Tested on release-5.2.7 // Postgres // FF
