### ISSUE TITLE
Show submenu as flyout when menu is collapsed

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17722]
When the menu is collapsed and the user right click in any of the icons we are going to show a flyout menu with the options of the submenu:

<img width="205" alt="Screen Shot 2019-12-10 at 07 38 30" src="https://user-images.githubusercontent.com/751424/70536189-e3ed3380-1b23-11ea-8ab8-64346de768e6.png">

**Comment by hmoreras** [comment]
after research, need to discuss possible implementation.

**Comment by fmontes** [comment]
This needs to go css all the way.
