### ISSUE TITLE
TinyMCE does not allow for images to be selected

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17731]
Long standing issue in TinyMCE - experienced by all CMSes that used TinyMCE as their editor:

https://github.com/tinymce/tinymce/issues/3611
https://github.com/silverstripe/silverstripe-framework/issues/6900
Wordpress, etc...

Upgrading tinymce fixes the issue - see mp4 attached

[tinymce-bug.zip](https://github.com/dotCMS/core/files/3952097/tinymce-bug.zip)

**Comment by wezell** [comment]
PR: #17733

**Comment by dsilvam** [comment]
Passed Internal QA: Able to select the image and modify the different properties.

**Comment by bryanboza** [comment]
We have an error trying to upload a new image to this editor. 

To reproduce: 
- In the editor try to add a new image 
- Select some image file
- Cancel the process 
- Try to upload again 

![tinyMCE](https://user-images.githubusercontent.com/2641437/71589078-38fbe400-2ae9-11ea-877c-d1c857420eef.png)

**Comment by wezell** [comment]
@john-thomas-dotcms this upgrades tinyMCE to version 4.9.6, the latest of the 4 series.  Customers with custom tinyMCE plugins and configurations should validate that they work in this version.

**Comment by bryanboza** [comment]
The error reported was moved to a new card (#17781 ). This will pass QA for now

**Comment by bryanboza** [comment]
We have another problem after this upgrade, 

- If you are on the editor and change to "plain" and try to change back to WYSIWYG, we are getting an error here and you can't get the editor back
SC: https://www.screencast.com/t/KcHmFqDSVWK

**Comment by wezell** [comment]
PR: #17786

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.3 // Postgres // FF
