### ISSUE TITLE
Unable to generate new starter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17738]
When generating a starter site, XStream is persisting users as `com.liferay.portal.ejb.UserHBM` rather than as `com.liferay.portal.model.User` which is making them fail to save.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17865

**Comment by erickgonzalez** [comment]
Tested changes against **release-5.2.5** and it's working as it should, a starter can be generated and imported without issues. On the **master** branch, there is an issue related with the new ES changes reported here https://github.com/dotCMS/core/issues/17887

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.5 // Postgres // FF
