### ISSUE TITLE
Add focal point for more intelligent cropping

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17740]
Currently, when we crop an image, you have to specify the starting x and y, and then the width and height.  This means that you can't specify a point and say regardless of the size I crop, I want this to be the center point or included in my image.

We need to be able to say - here is the focal point of my image and I want a 1920x1080px version, a 1024x800px version and a 150x150px thumbnail and have the focal point included in all the versions.

If you specify a focal point + crop larger than the source image can provide, then it should crop out to the limit of the image (not fill)

**Comment by wezell** [comment]
PR: #17779

**Comment by erickgonzalez** [comment]
Tested diff examples such as:

- Combination of crop, webp, and focalpoint: http://localhost:8080/contentAsset/image/81c85f5c-95c2-4feb-88b1-c3c379c365f0/fileAsset/filter/Crop,WebP/crop_w/720/crop_h/364/webp_q/65/fp/.25,.45/

- Combination of crop and focalpoint: http://localhost:8080/contentAsset/image/81c85f5c-95c2-4feb-88b1-c3c379c365f0/fileAsset/crop_h/200/crop_w/200/fp/.45,.36

- Combination of Thumbnail, crop and focalpoint: http://localhost:8080/contentAsset/image/81c85f5c-95c2-4feb-88b1-c3c379c365f0/fileAsset/filter/Thumbnail/thumbnail_h/250/crop_h/100/crop_w/100/fp/.25,.25

Also tested all above with diff file extensions (png, jpeg, webp).

**Comment by bryanboza** [comment]
Fixed, tested with the provided examples on release-5.2.5 and this works as expected...
