### ISSUE TITLE
[plugin-seeds] : The "com.dotcms.servlet" Static Plugin example does not work

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17745]
Reported via Support: [99814](https://dotcms.zendesk.com/agent/tickets/99814)
Reproducible in dotCMS 5.1.6, and latest master 5.2.2

The Servlet Mapping value for the sample servlet in file https://github.com/dotCMS/plugin-seeds/blob/master/static/com.dotcms.servlet/conf/web-ext.xml is not valid. The `/servlets/` prefix belongs to a reserved internal dotCMS servlet and it's not meant to be used by any custom code.

### Steps to reproduce the behavior:
1. Unzip a local dotCMS 5.1.6 distro, and deploy the sample [com.dotcms.servlet](https://github.com/dotCMS/plugin-seeds/blob/master/static/com.dotcms.servlet) plugin.
2. Open an Incognito Window in your browser, and go to http://localhost:8080/servlets/plugins/hello
3. You'll see the following error on the page:
```
401 / Unauthorized

This server could not verify that you are authorized to access the URL requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
```

### Expected behavior
The following sample content should be displayed:
```
Hello world servlet
```

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
This is still an issue.

**Comment by wezell** [comment]
OSGI and servlets are problematic - they need a proxy servlet in our tomcat install and need to be wired, ets...  If you need to add servlet like functionality to dotCMS, the best way to do that in dotCMS 5.x is to write a web interceptor that terminates the filter chain.
