### ISSUE TITLE
Containers as files outside default host

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17749]
Containers as files are not working properly outside default host.

1. Create new site with a container as files
2. Add new template 
3. Add a container as files (using the advance template you have more control on the `parseContainer` directive).

Any of these combinations (path without host, path with host, identifier) can be use with the same result.
```
#parseContainer('/application/containers/large-column(lg-1)/','1576693758718')
#parseContainer('65cf86f5-5686-4e9a-99db-e6cde1499687','1576693846053') 
#parseContainer('//test1.dotcms.com/application/containers/large-column(lg-1)/','1576705055598')
```
4. Create a Page using the template
5. Try to add and save content to that page
6. No content is added

The code is not going to find a host in the path even if the `parseContainer` have it and when there is no host the code will try to find the container in the default host instead of current host (https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java#L165-L172), which is wrong, and when that happen no content can be add to the page.

Things we saw:
* The `/v1/page/{pageId}/content` (`PageResource`) is called with containers without a host even if the template is using the host in the `parseContainer` directive.
* The render endpoint (`http://localhost:8080/api/v1/page/render/folder1/page2?language_id=1`) is removing the host before to send it to the FE:
```
{"entity":{
  ...
  "containers" : {
    ...
    "/application/containers/large-column/" : {
      "container" : {
        "identifier" : "a050073a-a31e-4aab-9307-86bfb248096a",
        "preLoop" : "#dotParse(\"//demo.dotcms.com/application/containers/large-column/preloop.vtl\")",
        "postLoop" : "#dotParse(\"//demo.dotcms.com/application/containers/large-column/postloop.vtl\")",
        "path" : "/application/containers/large-column/",
      }
    }
  },
  ...
  "template" : {
  ....
    "body" : "## Container: Large Column (lg-1)\r\n## This is autogenerated code that cannot be changed\r\n#parseContainer('//demo.dotcms.com/application/containers/large-column/','1576709049598')\r\n"
  }
  }
}
```

## Possible solutions
1. Make the render endpoint to handle better the hosts, if the `parseContainer` does not have it we could append the current host to it.
If the `parseContainer` already has a host we should respect it.
2. We could add a better default in https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java#L165-L172 using the current host but that implies refactor in order to send the host down the flow until that method.

## Acceptance Criteria

1. We need to reproduce this case in integration tests before to fix it

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/17854)

**Comment by fmontes** [comment]
Still not saving content.

**Comment by DeanGonzalez** [comment]
I would like to test this when there is a fix - I can help QA

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17950

**Comment by bryanboza** [comment]
Please retest the #17803 as part of the internal in this card

**Comment by DeanGonzalez** [comment]
I just tested and this did not pass on master.  Make sure you create a file based container on site A, and then use that container on a UI template on site B and then create a page on site B using that template.  Here is a video of the container bug which does not allow the addition of content on the page or the container to be added when editing the layout: https://www.screencast.com/t/ZWviK0KVZQGI

**Comment by DeanGonzalez** [comment]
[testBundle-1c4e7593-04b8-4abe-8bc6-dd657d3c0fca.tar.gz](https://github.com/dotCMS/core/files/4171747/testBundle-1c4e7593-04b8-4abe-8bc6-dd657d3c0fca.tar.gz)

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/17966

**Comment by dsilvam** [comment]
**Passed Internal QA**: tested by @DeanGonzalez

**Comment by bryanboza** [comment]
These changes are breaking the edit mode functionality, you are unable to see the contents of the pages on BE. 

We need some work here.

**Comment by dsilvam** [comment]
Leaving all code changes related to this card into `5.2.6.` since after discussing with @freddyucv they are safe to leave.

**Comment by bryanboza** [comment]
We will move the card to 5.2.7

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18033

**Comment by freddyucv** [comment]
Note for QA:
- Not forget this: https://github.com/dotCMS/core/issues/17749#issuecomment-583468035
- Also test adding another site container in edit-page.
- Also test with advance and not advance template from the old template manager.

**Comment by fmontes** [comment]
How I tested:

1. Create a site
2. Create a file container in the site
3. Create a template in this new site and add the container from this site and from demo
4. Create a page and add, edit, remove content to this page

Also

In demo:
1. Create a template
2. Add containers from demo and from the other site
3. Create a page
4. Add, edit, remove content to this page

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
