### ISSUE TITLE
Content API should validate allowedFileTypes and maxFileLength in binary field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17772]
This issues comes from: https://github.com/dotCMS/core/issues/16852#issuecomment-561285450

As a developer I need to know when I'm creating contentlet with binary fileds, fields variables: `accept` and `maxFileLength` are respected.

## Acceptance Criteria
1. Update the API accordingly
2. Make sure that when importing content with binary fields it works as expected: https://github.com/dotCMS/core/issues/16852
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/plugin-seeds/pull/46)

**Comment by jgambarios** [comment]
Reverting changes https://github.com/dotCMS/core/pull/17825
Because we are unable to start dotCMS because of the changes in the immutable classes.
**NOTE:** Is required to delete the immutables to notice the problem when starting dotCMS (`./gradlew clean`)

https://gist.github.com/erickgonzalez/5534e079f99c229478d60d9bfd9beda7

**Comment by jgambarios** [comment]
New PR: https://github.com/dotCMS/core/pull/17826

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17967

**Comment by erickgonzalez** [comment]
Passed internal QA.

This error is showed on the logs when trying to upload a file whose type is not allowed.
> WARN  business.ESContentletAPIImpl - Name of Binary field [fileAsset] has an not allowed type: application/pdf
> ERROR business.WorkflowAPIImpl - There was an unexpected error: The file type is not allowed

Tested creating content via UI, REST, import CSV file.

**Comment by wezell** [comment]
We need to test the form builder

**Comment by bryanboza** [comment]
After  test the last changes, we need some work here: 

- Need to create the postman tests for this endpoint 
- Binary fields are not working in the new form builder

**Comment by fmontes** [comment]
The max file lenght is not implemented in the field elements

**Comment by bryanboza** [comment]
Moved to a new card
