### ISSUE TITLE
UI: Integration service detail host listing

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17788]
![Integrations 02 - V2](https://user-images.githubusercontent.com/923947/71831390-6bb85600-306e-11ea-9a6e-72fcced7bd35.png)

![Integrations 06 - V2 (delete)](https://user-images.githubusercontent.com/923947/71831408-7246cd80-306e-11ea-87d1-4ca95d517600.png)

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/73031428-af96b380-3e01-11ea-9ce2-231c99071e82.png)

No configurations

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/73031458-c9d09180-3e01-11ea-8316-950baa88be44.png)

**Comment by wezell** [comment]
@alfredo-dotcms  I think we need to talk about this - https://github.com/dotCMS/core/issues/17788#issuecomment-577917343

I thought we were going to lists the hosts and show which ones had customizations or not?

**Comment by alfredo-dotcms** [comment]
@wezell those mocks are for the work done until our last meeting, according to @jgambarios the new features/tasks discussed on the meeting will be addressed on a new ticket

**Comment by alfredo-dotcms** [comment]
PR `core-web` https://github.com/dotCMS/core-web/pull/1263/files

**Comment by jgambarios** [comment]
Improvements will be handle in https://github.com/dotcms/core/issues/17957
