### ISSUE TITLE
Can't use workflow action via api if you don't have proper "view on" set

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17794]
Using the `/api/v1/workflow/actions/fire` endpoint, you cannot reference a workflow action that does not have the proper "view on" set for it, e.g. when saving a contentlet, you can only use workflow actions that have "view on" = `edit`.

This is not correct.  "View On" should be treated like a rendering hint and not as a permission/ business logic.  The only "permission" type checks that should be performed are 

1. Is the content in the right step for the action?  (we can change this future forward if we want)
2. Does the user have permission on the action?

Found when documenting this:

https://dotcms.com/docs/latest/headless-example#step-4-full-crud-with-content-and-workflows

**Comment by jdotcms** [comment]
`[PR](https://github.com/dotCMS/core/pull/17821/files)`

**Comment by fmontes** [comment]
## The test

Edit the system workflow action "Save" and remove all the checks:

![Screen Shot 2020-01-22 at 16 01 36](https://user-images.githubusercontent.com/751424/72938388-822e0500-3d30-11ea-9dc6-fb6acc4f054a.png)

Create a new content type: "Test" with one field "Title"

Do a `PUT` request to: `/api/v1/workflow/actions/fire`

With this json body:

```
{ 
   "actionName": "Save",
   "comments": "saving content again",
   "contentlet": {
      "contentType":"Test1",
      "title":"Title123"
    }
}
```

**Comment by bryanboza** [comment]
Fixed, now we are able to execute this action as @fmontes said in the attached comment https://github.com/dotCMS/core/issues/17794#issuecomment-577407131. 

New related improvement reported here: #17949
