### ISSUE TITLE
Unable to reorder categories 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17798]
We are unable to reorder the categories using the sort order field. If you add some value to this field and then click in the reorder button, we are having an error message and the categories are disappearing. 

Here the stack trace: 
https://gist.github.com/bryanboza/f6462be1c416ef62ccdcbaaced29c29f

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to categories portlet 
3. Add values to the sort order field
4. Click in the reorder button 
5. Check your log file 

### Expected behavior
We need be able to reorder categories without problems 

### Desktop (please complete the following information):
 - Tested on release-5.2.3 // Oracle 11g // FF

**Comment by wezell** [comment]
The fix for this is to reimplement the servlet as a `CategoryResource`

**Comment by dsilvam** [comment]
This is working on master. Please re-test @bryanboza

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgres // FF
