### ISSUE TITLE
Insure ESSearch only allows access to an environments indexes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17799]
We need to make sure that you cannot do more than query using the ESSearch Tooling and that when querying, you are only able to query your indexes

**Comment by wezell** [comment]
Fail:
```
curl --user admin@dotcms.com:admin -XGET http://localhost:8080/api/v1/esindex/docscount/index/security-auditlog-2020.01.14
```

**Comment by nollymar** [comment]
@wezell that case has been fixed here: https://github.com/dotCMS/core/pull/17857

**Comment by dsilvam** [comment]
Passed Internal QA: Only cluster indices are able to be queried.
