### ISSUE TITLE
List and Card View for Content Search

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17795]
In the main content search screen, we need to allow users to select between a list view and a card view.  The card view should show the same preview image/icon that is shown when selecting relationships or content to be dropped on a page.

![listing](https://user-images.githubusercontent.com/934364/71935437-c340e980-3174-11ea-9def-1fe249a27e67.png)

![card-view](https://user-images.githubusercontent.com/934364/71935447-ca67f780-3174-11ea-9775-bc66877482e9.png)

**Comment by fmontes** [comment]
![Grid View (v4)](https://user-images.githubusercontent.com/751424/73566271-154df580-4429-11ea-85b0-760ef0bb2fdf.png)

**Comment by fmontes** [comment]
![Grid View (v4)](https://user-images.githubusercontent.com/751424/73574830-54d20d00-443c-11ea-8c27-353675176000.png)

**Comment by fmontes** [comment]
![Grid View (v4)](https://user-images.githubusercontent.com/751424/73576320-ce1f2f00-443f-11ea-9193-b6505bad5a94.png)

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/18029

**Comment by jdotcms** [comment]
when has a content type selected an refresh the card view, it does not recall the content type selected; consequently shows all types

**Comment by jdotcms** [comment]
On the mocks there is an icon in the left inferior corner, it is not included on the current code.

**Comment by jdotcms** [comment]
there is also an issue when uses the right click several times, it does not close the previous ones opened

<img width="1312" alt="Screen Shot 2020-03-09 at 12 37 16 PM" src="https://user-images.githubusercontent.com/19578350/76262643-88197000-6222-11ea-8b1f-a2b1efb8f84a.png">

**Comment by wezell** [comment]
We lost the ability to click on the image to edit

**Comment by fmontes** [comment]
Multiple select not working backward

**Comment by bryanboza** [comment]
Now we have this view working on  the content search portlet, but this is not implemented on site browser yet, as we request in the title. 

We need some work here

**Comment by fmontes** [comment]
Sorry my bad, we're not putting this in the Site Search just yet

**Comment by bryanboza** [comment]
We have some problems on iPad resolution after those changes, we need be able to use this view on this devices, right now we have this: 
![IMG_0390](https://user-images.githubusercontent.com/2641437/81116561-d9707380-8ee2-11ea-9d4a-a9f097dacac0.PNG)

- With the list view looks cut, but the vie icons looks misaligned
- The card view is not working, we are unable to see the image thumbnail
-  we cut the “…” button from the general view

**Comment by fmontes** [comment]
No extra work need here for the release.

**Comment by bryanboza** [comment]
Fixed, the above mentioned problems was moved to a new card #18456
