### ISSUE TITLE
Cannot browse/select a link beyond 5 sub-folder levels - dotcms 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17792]
### Describe the bug
When choosing to add a link in the wysiwyg via the **browse** button, the link select window only allows the [+] to expand the folder to be clicked on 5th-level sub-folder. Beyond that the [+] is hidden and cannot be clicked. 

### Steps to reproduce the behavior:
1. Add more than 5 sub-folders in file browser
2. Add content to any folder beyond 5th sub-level
3. Create a page in any folder
4. Add generic content to the page w/a wysiwyg
5. Use the link button & **browse** to add link. 
6. Attempt to navigate beyond 5 sub-folder levels

### Expected behavior
Content should be accessible beyond 5th sub-folder.

###Actual Behavior 
The folder pane in the link-select window is not adjustable so after the 5th sub-folder the [+] is completely overlapped by the folder name and cannot be expanded. 

### Screenshots

**Folder level eight deep with content in 8th folder:** 

![image](https://user-images.githubusercontent.com/49727631/71906278-5e16d500-312f-11ea-84d8-5aa3635126fe.png)

**After 5 folder levels, the [+] sign to expand folders cannot be clicked:** 

![image](https://user-images.githubusercontent.com/49727631/71906193-3b84bc00-312f-11ea-85c8-1feec9bc08e5.png)

### Desktop (please complete the following information):
 - OS: N/A
 - Browser Chrome/FF
 - Version 5x

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/17808
https://github.com/dotCMS/dotcms-dojo-theme/pull/68

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.4 // Postgres // FF and I'm unable to reproduce
