### ISSUE TITLE
tinymceprops Field Variables: buttons not being added  - 5.2x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17807]
### Describe the bug
Customizing the wysiwyg via field variables using the methods on https://dotcms.com/docs/latest/the-wysiwyg-field#Customizing doesn't work as stated. Several buttons do not appear even if called out specifically in the code. 

Also one code snippet on the documentation appears to crash dotcms.

### Steps to reproduce the behavior:
1. Add field variable _**tinymceprops**_
2. Add values as per the documentation above. 

e.g. 

`{ toolbar1: "styleselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | image dotimageclipboard  | link unlink | fullscreen" }`

### Expected behavior
All buttons should display on the resulting editor.

###Actual behavior
All buttons do not show up and there are errors in the console. In the above example, the following buttons do not display: image, dotimageclipboard, link, unlink, fullscreen.

Even trying to _just_ add **fullscreen** does not work (see screenshot): 

`{ toolbar1: "fullscreen" }`

### Screenshots

![image](https://user-images.githubusercontent.com/49727631/72096875-be00ad80-32e0-11ea-9c09-18e4f67b685e.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser chrome/ff
 - Version 5.2x

**Comment by craigWagner99** [comment]
In addition, just adding formatting code without including button configuration makes the default buttons disappear:

e.g.

`{style_formats: [ { title: 'Headings', items: [ {title: 'H1', format: 'h1'}, {title: 'H2', format: 'h2'}, {title: 'H3', format: 'h3'}, {title: 'H4', format: 'h4'}, {title: 'H5', format: 'h5'}, {title: 'H6', format: 'h6'} ]}, { title: 'Heading Style Modifications', items: [ {title : 'Smaller', selector : 'h1,h2,h3,h4,h5,h6', classes : 'smaller'}, {title : 'Color: blue', selector : 'h1,h2,h3,h4,h5,h6', classes : 'color-blue'}, {title : 'Color: reversed', selector : 'h1,h2,h3,h4,h5,h6', classes : 'reversed'} ]} ]}`

**Comment by wezell** [comment]
@craigWagner99 just to be clear here, we only support configurations that are supported by the latest version of tinyMCE 4.x.  Some of the documented configurations might include configs that are no longer supported by tiny:

https://www.tiny.cloud/docs-4x/general-configuration-guide/

**Comment by craigWagner99** [comment]
@wezell Copy that. Thank you.
