### ISSUE TITLE
Log File Missing 5.2.3

### ISSUE THREAD

**Issue by NightsDream** [dotCMS/core#17804]
Log file is missing for dotcms 5.2.3
No issue for dotcms 4.X and dotcms 3.X

By right the default log file location should be this path right?
C:\Users\aster\Desktop\dotcms5.2.3\dotserver\tomcat-8.5.32\webapps\ROOT\dotsecure\logs

I'm using mysql 5.7.
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_231

Steps to install dotcms
1) Create database on mysql (dotcms523)
2) Change the context.xml to point the db
`
    <Resource name="jdbc/dotCMSPool" auth="Container"
          factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
          type="javax.sql.DataSource" driverClassName="com.mysql.jdbc.Driver"
          url="jdbc:mysql://localhost:3306/dotcms523?characterEncoding=UTF-8&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC"
          username="root" password="cxzcz" maxActive="60" maxIdle="10" maxWait="60000"
          removeAbandoned="true" removeAbandonedTimeout="60" logAbandoned="true" 
          jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer" 
          timeBetweenEvictionRunsMillis="30000" validationQuery="SELECT 1" testOnBorrow="true" testWhileIdle="true"
          abandonWhenPercentageFull="50"/>`

3) Click on C:\Users\aster\Desktop\dotcms5.2.3\bin\startup.bat
4) Log file missing on C:\Users\aster\Desktop\dotcms5.2.3\dotserver\tomcat-8.5.32\webapps\ROOT\dotsecure\logs

![image](https://user-images.githubusercontent.com/20954805/72080621-0c8d6680-3338-11ea-967a-91e4c974106c.png)

Please help me because log file is very important to me.
Thanks

**Comment by wezell** [comment]
In the 5 series, the log files are all directed to catalina.out generally found under the 
`\dotserver\tomcat-8.5.32\logs` directory.  This behavior can be adjusted by modifying your `WEB-INF/log4j2.xml` file.
