### ISSUE TITLE
Problems adding custom tool groups 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17812]
We have problems when you try to add a custom tool group, this since when you try to add a new tool, all the default ones are disappearing and just show the new one, this happening even if you leave all the defaults selected. Also, you are unable to expand the new one. 

We have an error on the JS console. 
![js](https://user-images.githubusercontent.com/2641437/72171892-7c800900-3399-11ea-92b7-2576f0da9080.png)

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to system --> configuration --> Roles&Tools 
3. Click in the Tools tab, and add a new custom tool group 
4. Save it and enable this to show in the left menu
5. Save the changes 

### Expected behavior
We need to be able to include this portlet on the left menu. 

### Desktop (please complete the following information):
Tested on master // Oracle // FF

**Comment by wezell** [comment]
I cannot reproduce
