### ISSUE TITLE
Need to refresh page rules after edit rules in the page properties tabs

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17813]
We are not refreshing the page info after you from edit mode edit the page properties, and after close the properties modal, we are showing outdated information. 

FYI: If you just edit the page and then edit the properties from the content tab, we are refreshing the information as expected. 

### Steps to reproduce the behavior:
1. Login as admin
2. Go to Site --> Browser and edit some page 
3. In the right menu, go to the Rules tab, and then click on properties 
4. Add//edit some rule and save it 
5. Close the properties modal and make sure we are showing the changes correctly 

### Expected behavior
We need to refresh this window in order to show the changes correctly

### Screenshots
SC: https://www.screencast.com/t/aoaT2uyRYAC

### Desktop (please complete the following information):
 Tested on master // Oracle // FF

**Comment by nollymar** [comment]
In a PO meeting we decided not to fix it
