### ISSUE TITLE
Create Card View component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17815]
Create a Web Component for the card listing of contentlets.

1. Responsive
2. Show thumbnail and fallback to icon
3. Hover state
4. Define how card it dotcms looks like.

## Ideas
1. We might need a "contentlet thumbnail" component so we can do all the fallback from image to icon.
2. Use flex, wrap and min-weight for responsive.

## Inspiration

![Screen Shot 2020-01-10 at 15 29 55](https://user-images.githubusercontent.com/751424/72187813-4d2fc300-33be-11ea-9bdd-7f7d95f540fb.jpg)

**Comment by jdotcms** [comment]
it is responsive

**Comment by jdotcms** [comment]
it shows fallback depending on the type (shows diff icons)

**Comment by jdotcms** [comment]
when fires the right click to get the contextual menu, the previous one is not being closed, Consequently there are a lot of them

![Uploading Screen Shot 2020-03-09 at 12.37.16 PM.png…]()
