### ISSUE TITLE
Infinite Containers

### ISSUE THREAD

**Issue by NightsDream** [dotCMS/core#17827]
I just have 71 containers
I'm using dotCms 5.2.2

![image](https://user-images.githubusercontent.com/20954805/72229172-7ed7a280-35e7-11ea-9170-a5b90447aa1a.png)
![image](https://user-images.githubusercontent.com/20954805/72228986-4f746600-35e6-11ea-8a8e-ad78ee8098b9.png)

When I try to press next page, the containers become something like below. I can see the containers start to duplicates over and over.

![image](https://user-images.githubusercontent.com/20954805/72229185-944ccc80-35e7-11ea-9a98-6eb3b413acbf.png)

![image](https://user-images.githubusercontent.com/20954805/72229016-7d59aa80-35e6-11ea-8f1d-1b71e6a0ff91.png)

When I press again, it loops the previous same container again. (Same duplicates over and over) 

![image](https://user-images.githubusercontent.com/20954805/72229187-96af2680-35e7-11ea-94bd-e26df2c82b06.png)

![image](https://user-images.githubusercontent.com/20954805/72229099-df1a1480-35e6-11ea-9c6a-8c9d97acce5a.png)

I have clear all the caches, rebuild whole index but still get the same problem.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/17903/files)

**Comment by erickgonzalez** [comment]
Tested working as it should now, the pagination of containers.

**Comment by bryanboza** [comment]
Fixed, Unable to reproduce after the last changes  on release-5.2.5 // Postgres // FF
