### ISSUE TITLE
Chrome Site selector is not refreshing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17828]
### Describe the bug
The site selector in the header is not working when add, remove or any actions

### Steps to reproduce the behavior:
1. Go to Sites
2. Create and activate a new site
3. See that the new site is not reflected in the site selector header

The same happens in you delete or archive a site.

### Expected behavior
Site selector in the header should update when a new site is added or sites are edited, removed, archive, etc.

### Screenshots
![Screen Shot 2020-01-13 at 07 46 26](https://user-images.githubusercontent.com/751424/72260610-d7ec0a00-35d8-11ea-947d-fed1ef779813.png)

## Acceptance Criteria

1. Site selector should update accordingly
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
After some research, Angular reacts to the websocket event sent after delete or add a site, right after that we do a call to `api/v1/site` and it comes with the just added site. In the case of delete is comes with the just deleted.

**Comment by fmontes** [comment]
Use the payload to add or remove an item from the collection.

**Comment by fmontes** [comment]
Current site not syncing.

**Comment by fmontes** [comment]
Change site in the dropdown is not reloading the current portlet

**Comment by hmoreras** [comment]
the endpoint `http://localhost:8080/api/v1/site/switch/` is not sending the Web Socket message `SWITCH_SITE` every time the site is changed. need to double check why, to confirm the solution.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.5 // Postgres // FF, Chrome & Edge

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17912
