### ISSUE TITLE
"Send for Review" in Task Detail modal is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17829]
Reported via Support: [99571](https://dotcms.zendesk.com/agent/tickets/99571)
Related to GitHub Ticket: https://github.com/dotCMS/core/issues/17532
Reproducible in dotCMS 5.1.6, and latest master (5.2.3)

If you pass a newly created HTML Page down a given Workflow Step, and go to the **Tasks** portlet to select such a page and move it to the `Send for Review` step, the button is not working.

**IMPORTANT NOTE: The `Send for Review` step IS available and DOES WORK when clicking the three-dot button from inside the Page Edit mode.**

### Steps to reproduce the behavior:
1. Download the Workflow Scheme definitions from here: [workflow-schemes.zip](https://github.com/dotCMS/core/files/4054400/workflow-schemes.zip) , which contains a sample Workflow for dotCMS 5.1.6 and dotCMS 5.2.3. The Workflow is called `Workflow - 2 Stage`
2. Apply a License and upload them to your local dotCMS instance. Change the `Page Asset` Content Type to use this Workflow too.
3. Go to `/about-us/` and create an HTML Page called `Test`. Click **Save**.
4. Go to the **Home > Tasks** portlet, and click the `test` page you created previously.
5. Click the three-dot button, then click `Send for Review`. Nothing happens.

### Expected behavior
The `Send for Review` step must be accessible from both **Tasks** and **Edit Mode** portlets.

## Acceptance Criteria
As mentioned initially, the current workaround is to select the `Send for Review` from the **Edit Mode** portlet when editing the page.

**Comment by wezell** [comment]
We need to move this modal to NG system wide, see:
https://docs.google.com/document/d/1YQERB6VmSnKQ62jQt59OKVtM0b1KlAXY_yzNsKPX9-c/edit?usp=sharing

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/17866/

**Comment by bryanboza** [comment]
Fixed, now this action is firing a modal and after this, we are sending the content for review
