### ISSUE TITLE
[core] : Adding links to long file names into TinyMCE Editor is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17833]
Reported via Support: [100142](https://dotcms.zendesk.com/agent/tickets/100142)
Related to the following GitHub tickets:

* https://github.com/dotCMS/core/issues/17309
* https://github.com/dotCMS/core/issues/16799

Reproducible in dotCMS 5.1.1, 5.2.3 and latest master.

The TinyMCE Editor has problems when inserting a link that references a file with a very long name. For exaple: `a file with a very very very very very very very very very very very very very very very long name.txt`

It truncates the name and displays an ellipsis, which is correct for displaying purposes. However, the real value inside the rich text, when viewing the source, is the following:
```
<p><a href="/about-us/locations/a file with a very very ver...">/about-us/locations/a file with a very very ver...</a></p>
```

### Steps to reproduce the behavior:
1. Go to the `/about-us/locations/` folder, and upload a text file called `a file with a very very very very very very very very very very very very very very very long name.txt`
2. Go to **Content > Search**, select the `Content (Generic)` Content Type and adda new content.
3. In this new content, in the TinyMCE Editor, click the `Insert/edit link`. Browse and select the .TXT file you uploaded previously.
4. Change the TinyMCE Editor mode to **CODE** and check the input. It will look similar to this:
```
<p><a href="/about-us/locations/a file with a very very ver...">/about-us/locations/a file with a very very ver...</a></p>
```

### Expected behavior
Links must no be truncated.

### Additional context
The currently valid workaround is to change the TinyMCE Editor mode to **CODE** and manually update the link to contain the full name of the file.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage

**Comment by fmontes** [comment]
Related: https://github.com/dotCMS/core/issues/17309
PR: https://github.com/dotCMS/core/pull/17310

**Comment by fmontes** [comment]
@jcastro-dotcms is working in a fix because #17310 didn't worked.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/17841

**Comment by jcastro-dotcms** [comment]
Added to Maintenance Support plugin for 5.1.1: https://github.com/dotCMS/support/tree/master/maintenance_plugins/com.dotcms.maintenance-5.1.1

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
