### ISSUE TITLE
Need delete the page references when you delete forms 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17840]
We have problems when you have a form added to some pages and you delete it, we are removing the form but we leave the reference on the page. 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new form 
3. Add this to any page 
4. Delete the form 
5. Check the page and make sure the form was deleted 

### Expected behavior
We need completely delete the form and the reference to the page

### Screenshots
SC: https://www.screencast.com/t/JuQLzu3191HK

### Desktop (please complete the following information):
Tested on release-5.2.4 // Postgres // FF

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
