### ISSUE TITLE
Show Notification if ES is read-only 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17842]
We need to show a UI notification to admins if ES is not available for writing (read-only).  If we have an error message to show, that would be good as well, at least to admins.

We run the check when a piece of content is checked in.  
1. If it passes, we don't run the check again for 5 minutes.
2. If the check fails, we:
  - send a growl notification
  - content checkin fails
  - we set up a timer that will check elasticsearch every minute until it passes (this tries to set the index to read_write)
     - when this passes, we send another growl notification that elasticsearch is available for writing again

**Comment by bryanboza** [comment]
According to the discussion, we need to show a notification error on BE when the ES server is down, to let know the user about the error.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18569

**Comment by freddyucv** [comment]
**Note to QA:** test also

https://github.com/dotCMS/core/issues/17749

**Comment by nollymar** [comment]
Note to QA: Please test this scenario https://github.com/dotCMS/core/issues/17601

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18604

**Comment by freddyucv** [comment]
Note to QA:

Should this case

https://github.com/dotCMS/core/issues/17842#issuecomment-639147129

even with read only indices and cluster in write mode

**Comment by dsilvam** [comment]
Needs work: Setting the cluster to read_only using property `cluster.blocks.read_only_allow_delete` is not contemplated by the code

**Comment by dsilvam** [comment]
Needs work: after leaving the Open Distro container without space, system effectively shows a notification that the indices are read-only but it also says that it was able to put it back to write, which is not true.

**Comment by dsilvam** [comment]
**Passed Internal QA:**

ES Cluster was forced into read-only mode by filling up the disk. 

Once the ES Cluster is in **read-only mode** the following behavior takes place:
* Unable to save content and a notification saying _Live or Working indices are in read-only mode_ is shown
* Unable to save content with legacy relationships. Dialog saying _Cluster is in read-only mode is shown_

Once the space is freed and ES Cluster goes back to **write-mode** the following behavior takes place:
* A Notification is shown saying "Live are Working indices are back in write mode"
* Content that was saved during the read-only period is now shown on Content Search Screen
* No notification is shown when saving new content
* Content with legacy relationships is able to me saved

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18688

**Comment by bryanboza** [comment]
Now we are showing the notification when the ES is in read only mode, but if you try to reindex we are getting an error on logs and we are not showing nothing at UI leven, we need to show another notification related to the error, since the reindex process never starts. 

`13:47:02.567  ERROR util.DotRestHighLevelClientProvider$1 - [host=https://127.0.0.1:9200]`

Tested on release-5.3.3 // Postgres // FF
