### ISSUE TITLE
Update ESIndexResource to only call API methods

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17848]
The ESIndexResource is calling to elasticsearch directly.  We need to call our ES APIs so they can translate the index names appropriately.

Fail:
```
curl --user admin@dotcms.com:admin -XGET http://localhost:8080/api/v1/esindex/docscount/index/security-auditlog-2020.01.14
```

_Originally posted by @wezell in https://github.com/dotCMS/core/issues/17799#issuecomment-574384197_

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17857

**Comment by dsilvam** [comment]
**Needs work**: This is not showing the count info anymore, but 500 response code is returned and an error in the log is printed. We need to respond with 404.

**Comment by nollymar** [comment]
New PR with the fix https://github.com/dotCMS/core/pull/18134

**Comment by dsilvam** [comment]
**Passed Internal QA**: Returning 404 for non existing indices and proper count for existing ones.

**Comment by bryanboza** [comment]
Fixed, tested on master and now it works as expected, Postman tests created

**Comment by nollymar** [comment]
Another PR to fix postman test: https://github.com/dotCMS/core/pull/18359
