### ISSUE TITLE
BinaryExporterServlet returns 404 for existing assets for non logged in users

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17858]
Reported via Support: Ticket [100152](https://dotcms.zendesk.com/agent/tickets/100152)
Reproducible in dotCMS 5.2.3

When a front end user has not logged in and requests an asset from a secured folder (that is, the folder is not assigned to the CMS Anonymous role), the user should be redirected to the login page, and after login verification, the user should be returned to the original page. However, the 404 error is returned and the user is not redirected to the login page.

### Steps to reproduce the behavior:
1. Go to 'System -> Roles & Tools' portlet and create a new role called 'My Site User'.
2. Create a new front end user and assign the new role created in the previous step (or add the role to an existing front end user).
3. Go to 'Site -> Browser' portlet in dotCMS backend.
4. Create a new folder called 'my-protected-site'.
5. Edit folder permissions, add read permissions for 'My Site User' role created in step 1.
6. Remove folder permissions for 'CMS Anonymous' role, so the folder is not public anymore.
7. Add a new a new asset to the folder created in step 2 and publish it (for example: 'my-protected-asset.pdf'.
8. Log out from dotCMS backend.
9. Try to access the asset added in step 7: `/my-protected-site/my-protected-asset.pdf`
10. A 404 error is returned and the following message is shown in the log file:
```
16/01/20 18:06:49:820 CST] ERROR servlets.BinaryExporterServlet: [Exception] An error occurred when accessing '/raw-data/f01da61d-3e6e-476c-85f1-9e50041366c8/fileAsset/': null
```

### Expected behavior
If the front end user is not logged in to the site, then a redirect should happen to the login page.

### Screenshots
Permissions for the protected folder (not CMS Anonymous access granted):
![image](https://user-images.githubusercontent.com/2894221/72574833-1828e200-3890-11ea-97a1-76738dfeee00.png)

### Additional context
This has been reported by customer via Support: Ticket [100152](https://dotcms.zendesk.com/agent/tickets/100152).

**Comment by dsolistorres** [comment]
PR: #17914

**Comment by alfredo-dotcms** [comment]
the issue is still present and the 404 page is showing

**Comment by wezell** [comment]
1. User is not logged in - 401
2. User is logged in and does not have permissions - 403

**Comment by dsilvam** [comment]
Passed Internal QA: The 404 reported by @alfredo-dotcms is because the login-page does not exist. 
If you put a breakpoint on custom-error-page you will see the correct response code is returned - 401 for user not logged in.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
