### ISSUE TITLE
User menu shows empty in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17855]
### Describe the bug
The user menu shows up empty when you are logged in and try to go to the home of the site (which redirect to edit mode of the home).

![Screen Shot 2020-01-15 at 15 41 06](https://user-images.githubusercontent.com/751424/72474519-90b77200-37ae-11ea-8b06-89e4c9216539.png)

### Steps to reproduce the behavior:
1. Login in your localhost
2. Close the tab
3. Open a new tab and go to http://localhost:8080/

### Expected behavior
It should load like:
![Screen Shot 2020-01-15 at 16 03 07](https://user-images.githubusercontent.com/751424/72475453-8a29fa00-37b0-11ea-9835-d5577b9a5c80.png)

## Acceptance Criteria

1. Make sure the user options load under any circunstances
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core-web/pull/1266

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.2.5 // Postgres // FF
