### ISSUE TITLE
Content not added to the index for content type variable 'Title'

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17850]
Reported via Support: Ticket [100164](https://dotcms.zendesk.com/agent/tickets/100164)
Reproducible in dotCMS 5.2.3

If a new content type is created using the variable name 'Title' (or other reserved word for index entry fields), the contentlets for that content type can't be added to the index.

### Steps to reproduce the behavior:
1. Go to 'Content Types' portlet.
2. Add a new content type with the name 'Title' (or other reserved word for index entry fields, for example 'Working'). The automatically generated variable name for the content type will be 'Title'.
3. Add add a user searchable field called 'Anything' to the new content type
4. Go to the 'Search' portlet
5. Add a new item for the new content type created in step 2.
6. Save the new item.
7. The saved item is not shown on the search portlet, and the following message is added to the log:
```
15/01/20 14:01:34:490 GMT] WARN reindex.ReindexQueueAPIImpl: Reindex failed for :IndexJournal [id=1113, identToIndex=fa0d5d9a-fdbc-4bcb-b253-9e0ef1ec84a0, priority=104, delete=false, serverId=null] because bulk index failure:MapperParsingException[Could not dynamically add mapping for field [title.anything_text]. Existing mapping for [title] must be of type object but found [text].]
```

### Expected behavior
Variable names used for content types shouldn't cause conflicts when adding entries to the ES index. A different variable name (for example 'title1' instead of 'title') can be used to avoid conflicts with reserved words.

### Additional context
This has been reported by customer via Support: Ticket [100164](https://dotcms.zendesk.com/agent/tickets/100164)

**Comment by wezell** [comment]
Reserved Content Type variables:
```
basetype
categories
conhost
conhost
conhostname
contenttype
deleted
expdate
host
identifier
inode
languageid
live
locked
metadata
moddate
moduser
originalstartdate
owner
ownercanpublish
ownercanread
ownercanwrite
parentpath
path
path
permissions
pubdate
recurrenceend
recurrencestart
shortid
shortinode
structurename
structuretype
tags
title
type
urlmap
versionts
wfassign
wfcreatedby
wfcurrentstepname
wfmoddate
wfscheme
wfstep
working
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17851

**Comment by dsilvam** [comment]
**Needs work**: The original PR was reverted after merge because it broke the dotCMS start up process. A new PR was created but the code needs to be revisited and tested: 

New PR: https://github.com/dotCMS/core/pull/17973

**Comment by nollymar** [comment]
Passed internal qa. Tested by @alfredo-dotcms

**Comment by bryanboza** [comment]
We need some work here, if you try from UI this is working as expected. We just add a "1" to the variable, but if you try forcing the variable from postman, we are getting a bad response here 
Response: 
```
<!doctype html>
<html lang="en">

<head>
	<title>HTTP Status 400 – Bad Request</title>
	<style type="text/css">
		h1 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 22px;
		}

		h2 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 16px;
		}

		h3 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 14px;
		}

		body {
			font-family: Tahoma, Arial, sans-serif;
			color: black;
			background-color: white;
		}

		b {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
		}

		p {
			font-family: Tahoma, Arial, sans-serif;
			background: white;
			color: black;
			font-size: 12px;
		}

		a {
			color: black;
		}

		a.name {
			color: black;
		}

		.line {
			height: 1px;
			background-color: #525D76;
			border: none;
		}
	</style>
</head>

<body>
	<h1>HTTP Status 400 – Bad Request</h1>
	<hr class="line" />
	<p><b>Type</b> Status Report</p>
	<p><b>Message</b> Bad Request</p>
	<p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a
		client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	</p>
	<hr class="line" />
	<h3>Apache Tomcat/8.5.32</h3>
</body>

</html>
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18449

**Comment by alfredo-dotcms** [comment]
now the endpoint returns a 400 response with a message
![image](https://user-images.githubusercontent.com/37185433/81345850-6ef03c80-9076-11ea-9bae-14d9d083589c.png)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Now it is working as expected.
