### ISSUE TITLE
Constant fields not included in json

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17864]
When we transform a contentlet to json, we do not include constant fields.  They should be included by default.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/17867

**Comment by erickgonzalez** [comment]
Working as it should. When you request content via REST API, the constant fields are returned.

**Comment by bryanboza** [comment]
Fixed, now we are returning this type of fields. Tested on release-5.2.5 // Postgres // FF
