### ISSUE TITLE
When new licenses are added they should be automatically applied

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#17871]
The expected behavior that when you upload a new license pack you have to manually apply the license  rather than the instance
1) detecting that their current license will soon expire 
2) detecting that that there are newer licenses available 
3) automatically grabbing one of the new licenses.  

In particular in cluster environments where all access is through a load balancer (the recommended configuration) it is a hassle to get connected to each node in turn to apply licenses.

**Comment by wezell** [comment]
They will apply as soon as a server is without a license.  The system won't automatically grab another license if it already has a good one.
