### ISSUE TITLE
Update dotCMS docker images to expect externalized ES

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17878]
We need to update our dotCMS docker images to expect externalized ES and we need our docker install to use Open Distro by default

**Comment by nollymar** [comment]
Implemented on this branch: `issue-17878-update-dotCMS-docker-images-to-expect-externalized-ES` 

PR to merge into `dotcms-src-seed` : https://github.com/dotCMS/docker/pull/18

**Comment by nollymar** [comment]
**Note to Doc and QA: **
The reference implementation `03-full-stack` by default deploys one dotcms instance and an Elasticsearch cluster with 3 master nodes. It's possible to scale an additional dotcms instance using this command: `docker-compose up -d --scale dotcms=2`

**Comment by dsilvam** [comment]
Passed QA: This has been tested by a few of us and working as expected.
