### ISSUE TITLE
Unable to execute workflows if you don't have default site permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17876]
If you configure a user with a role that have full permissions to handle any site different to the default one, we are unable to see the workflows, but when you try to add//upload a piece of content, you are unable to see the action 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a copy of the demo site 
3. Add a role (Role1) with full permissions to this new site 
4. Create a user with two roles (BackendUser // Role1)
5. Login as this user and create a new content type 
6. Make sure this content type is associated with the system workflow 
7. Try to upload a new piece of content 

### Expected behavior
We need be able to see the system actions without problems, also need to be sure the roles
"Anyone who can Publish Content"
"Anyone who can Publish Content" 
"Anyone who can Edit Permissions Content"

Are calculated with the current site and not with the default one

### Desktop (please complete the following information):
Tested on release-5.2.4 // Postgres // FF

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17892

**Comment by dsilvam** [comment]
Needs work: When you have a role with only Publish permissions (Not Edit Permissions) over content and add "Anyone who can Edit Permissions Content" to the "Save & Publish" action on the System Workflow, a user with that role only and backend user is able to publish content.

**Comment by freddyucv** [comment]
> Needs work: When you have a role with only Publish permissions (Not Edit Permissions) over content and add "Anyone who can Edit Permissions Content" to the "Save & Publish" action on the System Workflow, a user with that role only and backend user is able to publish content.

This is because when it is going to create a new content the permission are taken from the Content Type, so the permission have to be set over the Content Type to this QA.

like you can see here:

![esta_bien](https://user-images.githubusercontent.com/10408015/73220667-9a34c880-4124-11ea-9714-2f06c743cbd6.gif)

**Comment by nollymar** [comment]
Note to QA: This issue might be related to one reported on the dotCMS' group. Please test if this fix solves this issue too: https://groups.google.com/forum/#!topic/dotcms/1SakXeBfGV4

**Comment by dsilvam** [comment]
**Passed Internal QA:** Original steps behaving as expected. Also issue mentioned by @nollymar does not happen.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.7 and now we are able to execute the WF without problems
