### ISSUE TITLE
Unable to use elasticsearch without SSL

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17879]
Users might want to connect to an elasticsearch provider that does not use SSL - say for local testing.  We need to provide a config that will allow them to do so.  As it stands, we have  `https` hard coded as the protocol which prevent us from connecting to non-ssl elasticsearch endpoints.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17880

**Comment by nollymar** [comment]
**Note to QA:** To run an insecure (http) Open Distro container using this image follow these steps:  
https://github.com/dotCMS/docker/tree/master/images/es-open-distro-1.3.0

- Set this property `opendistro_security.ssl.http.enabled` to false in the file **yml/custom-elasticsearch.yml**

- Recreate the image running: 
`docker build --no-cache --rm -t es-open-distro . `

- Create a container from the image: 
`docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" --name es-open-distro es-open-distro`

- Verify that it is actually running on http: When running this command `curl -XGET http://127.0.0.1:9200 -u admin:admin` , you should obtain a response similar to: 

```
{
  "name" : "Qh65xjX",
  "cluster_name" : "dotCMSContentIndex",
  "cluster_uuid" : "P1GyMQ4QS12ajP9bd2Oh7A",
  "version" : {
    "number" : "6.7.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "2f32220",
    "build_date" : "2019-04-02T15:59:27.961366Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by nollymar** [comment]
**Note to QA and Doc:** To run dotCMS using ES without SSL, the property `ES_TLS_ENABLED` must be set to **false** in the file `it-dotcms-config-cluster.properties`

**Comment by nollymar** [comment]
**Tests results:** Success

**Comment by bryanboza** [comment]
Fixed,  tested on master // Postgres // FF
