### ISSUE TITLE
Double-clicking a Content->Search result on first login takes user to Tasks instead of the content- 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17872]
### Describe the bug
Double-clicking a Content->Search result on first login takes user to Tasks instead of the content. All subsequent double-clicks on Content->Search work as expected. 

### Steps to reproduce the behavior:

1. Clear your browser's cache and login to demo 
2. Go to Content->Search 
3. Select a content type
4. Double-click one of the results. 

### Expected behavior
It should open up the item clicked but instead goes back to Home.

### Screenshots
**Search**
![image](https://user-images.githubusercontent.com/49727631/72826793-1fa90c00-3c3f-11ea-8205-cc6ce3794e66.png)

**Double-click**
![image](https://user-images.githubusercontent.com/49727631/72826896-55e68b80-3c3f-11ea-8d65-26fd12a2f4c9.png)

### Desktop (please complete the following information):
 - OS: N/A
 - Browser Chrome/FF
 - Version: 5x

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17991

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the fix... Tested on release-5.2.7 // Postgres // FF
