### ISSUE TITLE
Testing External Elasticsearch

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17882]
There are some complex scenarios that we need to test and have answers for when using external elasticsearch

- [x]  We need to test our resilience - what happens when connectivity to ES goes away?  And under load - Do we stay up or do we crash and burn?  
 ### What works when elasticsearch is not available?
- [x]  Do static assets still work?  (they should)
**it work but maybe we need some work here: https://github.com/dotCMS/core/issues/17882#issuecomment-598306448**
- [x]  Does the backend work, (can login, etc), save for the content search driven pages?   (it should, for the most part) . What happens when you go to the CMS Maintenance Screen?
- [x]  Do pages with page cache work? (they should)
**NOT WORK:   https://github.com/dotCMS/core/issues/17882#issuecomment-598332743**
**Now work**: https://github.com/dotCMS/core/issues/18153
                          https://github.com/dotCMS/core/issues/18268
- [x]  Do vanity URLs? (they should if they have already been loaded)
**Really does not wokr: https://github.com/dotCMS/core/issues/17882#issuecomment-598335716**
- [x]  Do URLMaps?  (they probably wont)
**Not work https://github.com/dotCMS/core/issues/17882#issuecomment-598349484**
- [x]  Content Checkin (should not)
  - Try adding a new file
**It is does not work https://github.com/dotCMS/core/issues/17882#issuecomment-598306448**
- Do API calls work?  
  - [x]  PageAPI (maybe)
**Not work https://github.com/dotCMS/core/issues/17882#issuecomment-598401024**
  - [x] Content by ID (should)
**it work**
  - [x]  Widget API (should, unless they use a content pull)
**If you use a content pull it not work**
  - [x]  Scripting/VelocityAPI should
 **it does not work https://github.com/dotCMS/core/issues/17882#issuecomment-599701816**
 ### Does the system recover when elasticsearch comes back?
- [x] dotCMS should absolutely and fully recover when ES comes back and all of the above should work.

**it work https://github.com/dotCMS/core/issues/17882#issuecomment-595468659**

### What happens when we try to auto-scale dotCMS up when connected to ES?  
- [x] Does the cluster scale up? In my mind, this should just work without any "rewiring" from ES

### What happens when we try to auto-scale dotCMS down when connected to ES?  
- [x] Does the cluster scale down? In my mind, this should just work without any "rewiring" from ES

### Is it possible to try to connect to an elasticsearch cluster on 2 ips?
- [ ] Should be though maybe this requires some custom code.  It would be good to know

**Comment by freddyucv** [comment]
"Do static assets still work? (they should)"

Tested: Created a new image and add it to a page

**Comment by freddyucv** [comment]
"Does the backend work, (can login, etc), save for the content search driven pages? (it should, for the most part) . What happens when you go to the CMS Maintenance Screen?"

All this work

**Comment by freddyucv** [comment]
"Do vanity URLs? (they should if they have already been loaded)",  it s working

Tested:
1. Create a new vanity URL
2. Go to the URL

**Comment by freddyucv** [comment]
"Do URLMaps? (they probably wont)"

it is working

Tested:

- Created a new Content type setting: detail page and url pattern.
- Create a content
- Got to the new content page

**Comment by freddyucv** [comment]
" Content Checkin (should not)
Try adding a new file"

Tested here https://github.com/dotcms/core/issues/17882#issuecomment-594572534
And Also Tested createing a new File Content and "Save and Publish" it

**Comment by freddyucv** [comment]
"Do static assets still work? (they should)"

You can request a existing Image without problems, but I just try to create a new one obviously you can't but you not get any error message.

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/b448904b-e5ba-4e33-ad78-ba0ab7a4bb75

**Comment by freddyucv** [comment]
" Does the backend work, (can login, etc), save for the content search driven pages? (it should, for the most part) . What happens when you go to the CMS Maintenance Screen?"

- You can login but the site selector not show any site.

<img width="1111" alt="Screen Shot 2020-03-12 at 11 14 48 AM" src="https://user-images.githubusercontent.com/10408015/76547894-8d113600-6453-11ea-805c-c783bb3623bb.png">

- If you try to add content it not work, but you don't get any error in the UI

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/cb7f3b0a-728c-4d76-8510-7892f4567bec

**Comment by freddyucv** [comment]
"Do pages with page cache work? (they should)"

Not work, You get the follow error when you try to go to the page in the edit-page portlet

https://gist.github.com/freddyucv/7e00c07dd87c4f2cd3e3dacfe81cf0b1

If you try to get the page in the Front end you get a 404 HTTP error

**Comment by freddyucv** [comment]
"Do vanity URLs? (they should if they have already been loaded)"

Really the vanity URL is working, I mean dotcms do the forward but the page is not show, probably because of https://github.com/dotCMS/core/issues/17882#issuecomment-598332743

**Comment by freddyucv** [comment]
"Do URLMaps? (they probably wont)"

You get a 404 HTTP errpr

**Comment by freddyucv** [comment]
Do API calls work?
 PageAPI (maybe)

- If you try to get a page  you'll get:

{
  "error": "Cannot parse velocity file : /$dotTheme.templatePath"
}

-

**Comment by freddyucv** [comment]
"Do API calls work?
 
 Widget API (should, unless they use a content pull)"

it work

**Comment by freddyucv** [comment]
"Do API calls work?
 
 Scripting/VelocityAPI should"

it show 

<img width="1596" alt="Screen Shot 2020-03-16 at 12 40 03 PM" src="https://user-images.githubusercontent.com/10408015/76790206-05456780-6784-11ea-9930-eb537ee448f3.png">

when you try to get http://localhost:8080/api/vtl/sitemap

**Comment by john-thomas-dotcms** [comment]
It may be possible to have portions of the BE work when ES is down.  But I'm a little worried that it might sometimes work and sometimes not, depending on how the cache chains are configured in different regions.And I'm worried that might cause intermittent issues on some sites, and/or different behavior on different sites.
