### ISSUE TITLE
Wait until External Elasticsearch is ready

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17883]
When dotCMS starts up, it should wait/spin until it can connect successfully to an external elasticsearch instance.   If it cannot connect after 2 minutes (which might be too long in a containerized environment) dotCMS should give up.

**Comment by wezell** [comment]
PR: #17884

**Comment by nollymar** [comment]
**Tests results:** Success

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
