### ISSUE TITLE
Right click on main nav prevents scrolling

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#17886]
When the main menu is collapsed, using the right click loses focus on the iframe. This prevents scrolling in the main window when you have large lists of content

### Steps to reproduce the behavior on the "new starter":
1. Collapse the main menu
2. Right click on the content search menu
3. Select products
4. Try to scroll the results

See video
https://drive.google.com/file/d/1pTwAJndGEbPnif0nmkw-dJntGBxZUuCL/view?usp=sharing

**Comment by alfredo-dotcms** [comment]
https://github.com/dotCMS/core-web/pull/1274

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the release branch after the changes... Tested on release-5.2.7 // Postgres // FF
