### ISSUE TITLE
Admin console - users: chrome autofills email and password

### ISSUE THREAD

**Issue by zlymeda** [dotCMS/core#17889]
### Describe the bug
When user stores credentials in Chrome, Chrome will autofill emails and password in Admin console - Users screen. The confirm password field is not updated and user gets passwords do not match error.

### Steps to reproduce the behavior:
1. Setup chrome to save and autofill passwords
2. Login to admin console
3. Go to System > Users
4. Create new user
5. Confirm you want to save credentials to chrome
6. Log out, log back in
7. Go to System > Users
8. Search for newly created user
9. Chrome will autofill emails + password, but not confirm password fields. This can be seen from highlighted input fields.

### Expected behavior
Chrome's autofill feature should ignore new passwords. Password fields have autocomplete="off" which does not work. It should be autocomplete="new-password"

### Screenshots
![Autofill](https://user-images.githubusercontent.com/13189224/72964785-104ecd80-3dbb-11ea-9d68-7a1944e0242e.png)

### Desktop (please complete the following information):
 - OS: [Ubuntu 19.04]
 - Browser [chromium]
 - Version [79.0.3945.79]

## Acceptance Criteria
1. Autofill ignores new password fields

**Comment by wezell** [comment]
PR: #17890

**Comment by nollymar** [comment]
Test results: Success

**Comment by nollymar** [comment]
This issue is for 5.2.6

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgres // Chrome 79.0.39
