### ISSUE TITLE
Add multiple contents or widgets to container at the same time

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17891]
As a dotCMS editor, I want to be able to add multiple contents at the same time in the Edit screen in order to reduce clicks/speed content creation. 

### Describe the solution you'd like
A mechanism, such as a checkbox, in the add content screen in order to select multiple items to be added to the container at the same time. 

![image](https://user-images.githubusercontent.com/49727631/72990568-ff4f8d80-3db5-11ea-91ff-57296c191e2a.png)

Related ticket: https://dotcms.zendesk.com/agent/tickets/100327 

## Acceptance Criteria
1. Multiple contents are added in the same way a single contentlet or widget are currently added to containers in the Edit screen. 
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by notmattmonroe** [comment]
There is still a need for this functionality.
