### ISSUE TITLE
User Manager : unable to uncheck "Front-End" user filter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17895]
### Describe the bug
When managing users, you are unable to uncheck the front end user filter.  Expected behavior - The checkboxes should act like radio buttons and should uncheck the other selections.

![user-js-issue](https://user-images.githubusercontent.com/934364/73011503-58351b00-3de2-11ea-8181-ab0bc1273253.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17929

**Comment by dsilvam** [comment]
Passed Internal QA: Now we have radio-buttons that work as expected

**Comment by bryanboza** [comment]
Fixed, now we have the radio buttons and you are able to select just one at the same time
