### ISSUE TITLE
Navtool submenus do not display properly in Edit Mode - 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17896]
### Describe the bug
Side menus using the Navtool do not display properly in Edit mode. Submenu items do not display unless you've built in some click interaction that expands the menu

### Steps to reproduce the behavior:
1. Add "Show on Menu" to child folders/items that are in a side menu (e.g. in Demo, the Subnav Menu container is used on https://demo.dotcms.com/services/first-time-investors).
2. Open a page that uses that side menu in Edit Mode (e.g. https://demo.dotcms.com/services/first-time-investors)

### Expected behavior
Side nav menu should display all links.

###Actual behavior
All side nav links only display on Preview or Live modes.

### Screenshots
**Preview Mode**
![image](https://user-images.githubusercontent.com/49727631/73011994-fd4bf580-3dda-11ea-855c-9f9987803bef.png)

**Edit Mode**
![image](https://user-images.githubusercontent.com/49727631/73012014-05a43080-3ddb-11ea-8a0d-b8b1230614d9.png)

### Desktop (please complete the following information):
 - OS: N/a
 - Browser: Chrome/FF
 - Version: dotCMS 5x

**Comment by nollymar** [comment]
**Note to QA:** The real issue is that the active menu selection get lost when you switch to Edit Mode. Watch video below: 

![Screen-Recording-2020-02-04-at-5 59 39-PM (1)](https://user-images.githubusercontent.com/8741395/73795574-f331db80-4778-11ea-9338-0277e5bbcda5.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/17952

**Comment by dsilvam** [comment]
**Passed Internal QA**: active menu selection maintained after switching to Edit Mode.

**Comment by bryanboza** [comment]
Fixed, now we are showing sub menus without problems when you activate the `show on menu` option. Tested on release-5.2.6 // Postgres // FF
