### ISSUE TITLE
Create a ResetApproversActionlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17904]
We have 2 actionlets that look back in the workflow history and try to determine if a content object has been approved or not.  This works the first time a content is published but breaks down if a piece of content that has been published is returned for further edits.  To fix this, we need to create an WorkflowActionlet called "Reset Approvers" that will delete or rewrite the workflow history for a content object and remove the previous approvals so that the contentlet can be sent through the approval process again.  This Actionlet needs to work for both the `FourEyeApproverActionlet` AND the `MultipleApproverActionlet`

This will fix #17516

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/17922/files)

**Comment by fmontes** [comment]
## How I tested:
1. Create a new workflow with 3 steps: Saved, For Approval and Published
2. In the published I add a sub action that resets all the approvals
3. In the approval a sub action for For Eyes

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgress // FF. New improvement created here #18002
