### ISSUE TITLE
Unable to create rules

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#17901]
### Describe the bug
User with all permission in the current site can not create a new rules

### Steps to reproduce the behavior:
1. add new Role and User
2. Add all permission to the new role in the default site
4. Log in As with the new user
5. Try to create a new rule

### Expected behavior
The rule should be created without problems

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/17906

**Comment by dsilvam** [comment]
**Passed Internal QA**: New rules can be created without issues followings the mentioned steps

**Comment by bryanboza** [comment]
We need some work here: 

I created a role and set the follow permission:
![image](https://user-images.githubusercontent.com/2641437/75299140-e47b9900-57f9-11ea-8085-837b4f41fbcc.png)
I've publish permissions over rules. 

Then create a new user and assign the new role, when I login as the new user, and try to create rules, we are having the follow error on logs: 
https://gist.github.com/bryanboza/862a8eee70ba33e89fabb96b9372de23

Then we have two issues here: 
- I've permissions and I'm unable to create rules
- If you don't have the corresponding permissions, we need show the error on logs and return something to the UI indicating the permissions error, right now we are just showing a blank page.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18066
PR: https://github.com/dotCMS/enterprise-2.x/pull/704

**Comment by dsilvam** [comment]
Needs work: Creating rules for pages is not working. Code changes do not handle that case now

**Comment by freddyucv** [comment]
PR:

core: https://github.com/dotCMS/core/pull/18127
enterprise: https://github.com/dotCMS/enterprise-2.x/pull/709
core-web: https://github.com/dotCMS/core-web/pull/1285

**Comment by dsilvam** [comment]
*Needs work*: Two small details that should be quick to solve:
1. When you try to delete a rule with limited users you get an error message, but the options popup (where the `delete ` option is) remains open. It should disappear. 
2. We should not close the error message after 3 seconds. We should leave visible until the User dismissed or closes it.

**Comment by bryanboza** [comment]
By security reasons we should not print all the information about the user in the error, with the userId or userName is enough 
SC: https://www.screencast.com/t/Q8YdHc8UZH

**Comment by freddyucv** [comment]
PR:

core: https://github.com/dotCMS/core/pull/18181
core-web: https://github.com/dotCMS/core-web/pull/1291
ee: https://github.com/dotCMS/core/pull/18181

**Comment by dsilvam** [comment]
**Passed Internal QA**: All 4 issues/points from previous two comments working as expected.

**Comment by bryanboza** [comment]
After the last changes now the rules portlet works as expected, but now we have problems with the rules on pages, here the SC: 

We need some work here: https://www.screencast.com/t/7sACyqcRv

**Comment by freddyucv** [comment]
PR: 
core: https://github.com/dotCMS/core/pull/18191
ee: https://github.com/dotCMS/enterprise-2.x/pull/718

**Comment by dsilvam** [comment]
**Needs work:** 

Rules on pages:
1. Now you get the proper message when saving a rule without publish permissions on pages (_user does not have publish permissions on the page_), but since the rule still gets saved, it fires on the live version of the page. @bryanboza and I think the rule shouldn't be able to be saved if the role does not have publish permissions on page

**Comment by john-thomas-dotcms** [comment]
I agree, I think that for a user to edit Rules on a page, the user should need _both_ publish permissions on the page, _and_ publish permissions for rules in the site/folder where the page lives.

I don't think Edit permissions on the page are enough, since Rules can change the appearance of the page on the front-end of the site.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/723

**Comment by dsilvam** [comment]
Passed Internal QA: Tested all the scenarios from comments aboce

**Comment by bryanboza** [comment]
Related card on the #18253

**Comment by bryanboza** [comment]
We have a huge stack-trace every time you get the error, we need to catch this exception and print just a line error indicating the permissions error.

**Comment by bryanboza** [comment]
The improvements of this was moved to a new card... This is ok for now
