### ISSUE TITLE
Can not get Indicies Stats if Data is too Big

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#17918]
### Describe the bug
When running a reindex with client data, it does finish successfully. But as the data is too large,  this error is thrown in catalina.out (which avoids Indicies Stats load correctly):

Log:
```
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
        at com.dotcms.content.elasticsearch.business.ESIndexAPI.lambda$0(ESIndexAPI.java:176) ~[dotcms_5.0.0_8852f4e.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_191]
        at com.dotcms.content.elasticsearch.business.ESIndexAPI.getIndicesStats(ESIndexAPI.java:166) ~[dotcms_5.0.0_8852f4e.jar:?]
        at org.apache.jsp.html.portlet.ext.cmsmaintenance.index_005fstats_jsp._jspService(index_005fstats_jsp.java:556) ~[?:?]
```

Error Line:
https://github.com/dotCMS/core/blob/92d5136e129d21111b7d71f7ca3b76a0f70ca55d/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java#L175 --> we need to change this line to Long.

### Steps to reproduce the behavior:
1. Import client data
2. Run a reindex (this took approx 1h30m)
3. Check the Reindex Portlet, the stats of the indices does not show.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18138

**Comment by dsilvam** [comment]
**Needs Work**. 
After successfully reindexing and getting the stats without issues, this exception occurs when re-starting dotCMS, preventing it from properly starting up. 

Error happens in a different part of the code: https://github.com/dotCMS/core/blob/262988a5bd1b9a8a6e3fe1d4db779fe1cefc5284/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java#L1417

We need to check every place we could have a similar casting and also change from `int` to `long` for the `docCount` also just in case like it was done in the PR above.

**Comment by nollymar** [comment]
Fixed here https://github.com/dotCMS/core/pull/18165

**Comment by dsilvam** [comment]
**Passed Internal QA**: working as expected. 
Steps in description and [the comment above](https://github.com/dotCMS/core/issues/17918#issuecomment-601458073) were tested.

**Comment by dsilvam** [comment]
Passed QA: working as expected after going through the steps in the description.
