### ISSUE TITLE
Relationship fields on Host Content do not display in the UI

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17928]
Observed in latest 5.2.4 release on demo.dotcms.com and a new 5.2.4POC server

Does not display relationship in UI:

![Screen Shot 2020-01-30 at 3 50 03 PM](https://user-images.githubusercontent.com/1569167/73493515-82558280-4378-11ea-8006-d0130a38b5d2.png)

However it does display in API CALL with a depth of 1
https://demo.dotcms.com/api/content/id/48190c8c-42c4-46af-8d1a-0cd5db894797/depth/1

![Screen Shot 2020-01-30 at 3 51 21 PM](https://user-images.githubusercontent.com/1569167/73493614-b761d500-4378-11ea-9228-e56c72461830.png)

Easy to reproduce

1. Create a new content type with a single text field and checkbox all properties, user searchable etc.
2. Edit the demo host and add a relationships field to that new content type for the relationship (one to many- but should not matter)
3. Now add a contentlet of the new content type
4. Now go to the host and try to use the relationships field to add the content to the field as a related object and Save/active the host
5. Re-edit the host - the bug is that there is no relationship displaying in the UI

However, if you hit the following API URL you should be able to see the related content really does exist and is related to the host, but the UI does not display the content

https://demo.dotcms.com/api/content/id/48190c8c-42c4-46af-8d1a-0cd5db894797/depth/1

**Comment by DeanGonzalez** [comment]
FYI - relationships on host are really nice for Multi-Tenant implementations to use widgets to pull related contentlets to the host, but these relationships should be viewable from both the Host Content and the related content to manage them properly.

**Comment by nollymar** [comment]
Fixed. PR: https://github.com/dotCMS/core/pull/17961

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test with others content types using multilingual related content

**Comment by dsilvam** [comment]
**Passed Internal QA**: The related content shows up correctly after re-editing the Site. It's also available via REST api by using the `depth` parameter

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgres // FF. Now we are saving the relationship without problems
