### ISSUE TITLE
Center closed nav icons

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17921]
When the nav is closed, the icons are not centered:

![not-centered](https://user-images.githubusercontent.com/934364/73307383-1fcf7b80-41ec-11ea-8593-7feaa2282ffd.png)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1333

**Comment by nollymar** [comment]
Passed internal qa: Tested on Safari, Chrome and Firefox using a laptop and an iPad:

**On a laptop:** 
<img width="1675" alt="Screen Shot 2020-05-22 at 12 47 57 PM" src="https://user-images.githubusercontent.com/8741395/82695627-0fc02980-9c2b-11ea-9f56-37bcfeea4188.png">


**On an iPad:** 
![IMG_7EE03D293A31-1](https://user-images.githubusercontent.com/8741395/82695520-e43d3f00-9c2a-11ea-9494-5c881bcff2b2.jpeg)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF & Safari
