### ISSUE TITLE
The refresh event when you change the site from the site selector is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17937]
When you create a new site and then change this from the site selector we are not refreshing the page in order to update the selection. 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new blank site
3. Go to site browser 
4. Select the created site in the site selector 

### Expected behavior
We need to refresh the page, and show the new selected site 

### Screenshots
SC: https://www.screencast.com/t/T9znLwqRQEz

### Desktop (please complete the following information):
 Tested on release-5.2.5 // Postgres // FF

**Comment by hmoreras** [comment]
related to this one, https://github.com/dotcms/core/issues/18125

**Comment by bryanboza** [comment]
We need some work here: 

We are not refreshing the rules portlet when you switch between sites, then we don't have a way  to know which rule is of which site... 

Please make sure this is working with all the angular portlets

**Comment by fmontes** [comment]
@bryanboza this are new issues.

https://github.com/dotCMS/core/issues/18148
https://github.com/dotCMS/core/issues/18146

**Comment by bryanboza** [comment]
Nothing to check here, the found problem was moved to new cards...
