### ISSUE TITLE
Add clusterId to Config Screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17938]
We need to display the cluster id and the SHA-3 of the company.key for the cluster in the System > Config screen.  Additionally, we should include the cluster ID in the endpoint 
`http://localhost:8080/api/v1/appconfiguration`

## Acceptance Criteria 
- [x] The company key digest should not be exposed to the API unless it is requested by admin user
- [x] The cluster ID and the company key should be displayed as text in UI instead of input fields

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/729 
PR: https://github.com/dotCMS/core/pull/18638

**Comment by fabrizzio-dotCMS** [comment]
Note to QA: This pretty straight forward to test
log in as an admin and hit http://localhost:8080/api/v1/appconfiguration
There should be two fields: clusterId and companyKeyDigest
The cluster-id is grabbed from the table dot_cluster they both need to match.
`select * from dot_cluster`
The second value comes from the table company
check it out by doing 
`select key_ from company`
you can verify that the hash is the correct here
https://emn178.github.io/online-tools/sha256.html

**Comment by nollymar** [comment]
**Passed internal qa:** 

<img width="1603" alt="Screen Shot 2020-06-19 at 11 27 27 AM" src="https://user-images.githubusercontent.com/8741395/85156705-1046e280-b220-11ea-8e94-10f76986acb1.png">

Both fields are exposed to the API (but Company Key Digest is not exposed when the authenticated user is not admin)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF
