### ISSUE TITLE
Make binary fields indexable

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17944]
We should allow users to choose to make binary field indexable.  If the binary field is marked as indexed, the binary field should be indexed (just as we index files in fileAssets).  If I have a `news` content type and it has a binary field  called `pdfVersion` that is marked to be indexed, then we should parse the uploaded pdf with tika and index the results and make them searchable via `+metaData.content:Chicago*`

### Only the first Binary Field marked as "Indexed" will be indexed

We need to add mappings to our ES-Mapping file 
```
metadata.contenttype --> keyword 
metadata.length --> long
metadata.width --> long
metadata.height --> long
metadata.keywords --> keyword
metadata.content --> my_analyzer
```

### Field Variable
We should allow a user to override the fields to be "indexed" that are listed here
`indexMetadataFields`

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/dotmarketing-config.properties#L429

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/17962)

**Comment by erickgonzalez** [comment]
Tested and working fine on Content Base Type, only the first binary field marked as Indexed is being indexed. One issue has been found and reported here: https://github.com/dotCMS/core/issues/18027

**Comment by bryanboza** [comment]
Fixed, some related issues on this card but will work individually in other cards: 
https://github.com/dotCMS/core/issues/18106
https://github.com/dotCMS/core/issues/18107
