### ISSUE TITLE
UI: Unable to scroll down in the image editor 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17940]
When you are editing an image using the image editor, we are unable to scroll down in order to use the controls

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to site browser
3. Select some image and try to edit 
4. Try to scroll to use the controls in the right bar 

### Expected behavior
We need to be able to scroll without problems 

### Screenshots
SC: https://www.screencast.com/t/hgYoR7KcwRQ

### Desktop (please complete the following information):
Tested on release-5.2.5 // Postgres // FF

**Comment by wezell** [comment]
PR: #17942

**Comment by wezell** [comment]
Issue created by #17740

**Comment by nollymar** [comment]
**Passed Internal QA:** 
Tests Results: Success

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. Tested on release-5.2.5
