### ISSUE TITLE
Integration services improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17956]
1. Executing `GET http://localhost:8080/api/v1/service-integrations` when there are no services should a `200` code with an empty list instead of a `500` error.
There is no need to throw an exception in logs
```
11:49:08.519  ERROR secret.ServiceIntegrationResource - Exception on listing all available service-integrations.
com.dotmarketing.exception.DoesNotExistException: No service integration is available to configure. Try uploading a file!
```

---
2. ~Executing `GET http://localhost:8080/api/v1/service-integrations` returns:~
``` json
"entity": [
     {
…
…
     }
          ]
```
~Should be something like `"services"` instead of `"entity"`.~

---
3. The search in the **Services listing** portlet is made in the front end, this should be done by the services rest endpoint.

4. The services listing returned by `GET http://localhost:8080/api/v1/service-integrations` have the wrong order, is returning the configured services at the end, should have the configured services first with alphanumeric order.

5. We need to change the folder where the services yaml files are saved to `/assets/server/services`

6. The Service detail site listing code should be able to handle non existing sites.

7. Executing `DELETE http://localhost:8080/api/v1/service-integrations/serviceExample1/48190c8c-42c4-46af-8d1a-0cd5db894797ABC` with a non existing site id should return `404` instead of a `500` error.

8. Executing `GET http://localhost:8080/api/v1/service-integrations/serviceExample1/48190c8c-42c4-46af-8d1a-0cd5db894797ABC` with a non existing site id should return `404` instead of a `500` error.

9. ~Executing `GET http://localhost:8080/api/v1/service-integrations/serviceExample1/48190c8c-42c4-46af-8d1a-0cd5db894797` with an existing site but if there is not configuration the response message says:  `"Nope. No service integration was found for key ‘serviceExample1’ and siteId ‘48190c8c-42c4-46af-8d1a-0cd5db894797’."`.
We should remove the `Nope.` word.~ _In this case a default configuration is always shown_ 

---
10. Executing:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  “key” : “serviceExample1”,
  “siteId”:”48190c8c-42c4-46af-8d1a-0cd5db894797”,
  “params”: {
    “parameter12”: {
      “value”: “Test - Value1”
    }
  }
}
```

And having in the yaml service file the `parameter1` as required, we are not validating required params, I was able to save without problems.
``` yaml
  parameter1:
    value: “This is a string.”
    required: true
    hidden: false
    type: “STRING”
    label: “This is string param”
    hint: “Test string.”
```
---
11. After Executing:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  “key” : “serviceExample1”,
  “siteId”:”48190c8c-42c4-46af-8d1a-0cd5db894797”,
  “params”: {
    “parameter1”: {
      “value”: “Test - Value1”
    }
  }
}
```

And with the yaml file looking like this:
``` json
  parameter1:
    value: “This is a string.”
    required: true
    hidden: false
    type: “STRING”
    label: “This is string param”
    hint: “Test string.”
```

If I try to see what is saved using `GET http://localhost:8080/api/v1/service-integrations/serviceExample1/48190c8c-42c4-46af-8d1a-0cd5db894797` the response is:
``` json
…
…
"secrets": {
          "parameter1": {
            "hidden": false,
            "type": null,
            "value": "Test - Value1"
          }
        }
```

We are not sending back the right secret info, we are not respecting the yaml file

---
12. Having this secret in the yaml
``` json
  parameter1:
    value: “This is a string.”
    required: true
    hidden: false
    type: “STRING”
    label: “This is string param”
    hint: “Test string.”
```

And Executing:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  “key” : “serviceExample1”,
  “siteId”:”48190c8c-42c4-46af-8d1a-0cd5db894797”,
  “params”: {
    “parameter1”: {
      “value”: “Test - Value1”,
      “hidden”: true,
      “type”: “STRING”,
      “label”: “Test - This is string param”,
      “hint”: “Test string.”
    }
  }
}
```
I was able to change the hidden value from `false` to `true`, we need to respect the yaml file.

Response:
``` json
"secrets": {
          "parameter1": {
            "hidden": true,
            "type": "STRING",
            "value": "*****"
          }
        }
```

---
13. The `GET http://localhost:8080/api/v1/service-integrations/serviceExample1/48190c8c-42c4-46af-8d1a-0cd5db894797` is not sending back in the secrets properties like the `label` and the `hint` required for the service detail window.

---
14. Saving a hidden secret like this:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  “key” : “serviceExample1”,
  “siteId”:”48190c8c-42c4-46af-8d1a-0cd5db894797”,
  “params”: {
    “parameter7”: {
      “value”: “This is hidden value”
    }
  }
}
```

And having this in the yaml file:
``` json
  parameter7:
    value: “This is a string.”
    hidden: true
    type: “STRING”
    label: “This is string param”
    hint: “Test string.”
```
Is not working, is treating the element as a normal secret, the yaml define it is a hidden value, I should not need to send `hidden: true` to the end point.

---
15. Adding the `allowExtraParameters: true` property to the service yaml file allows to add extra secrets to the service. Should we have some defaults or validate missing data for secrets?, example:

Saving properties like the following example where the `NewParameter1` secret is new, meaning no defined in the yaml file:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  "key" : "serviceExample3",
  "siteId":"48190c8c-42c4-46af-8d1a-0cd5db894797",
  "params": {
    "parameter1": {
      "value": "Test - Value1"
    },
    "NewParameter1": {
      "value": "This is hidden value"
    }
  }
}
```

And executing `GET http://localhost:8080/api/v1/service-integrations/serviceExample3/48190c8c-42c4-46af-8d1a-0cd5db894797` returns:

``` json
"NewParameter1": {
            "hidden": false,
            "type": null,
            "value": "This is hidden value"
          }
```
 
Problem: `type` is null.

---
16. The returning data from `GET http://localhost:8080/api/v1/service-integrations/serviceExample3/48190c8c-42c4-46af-8d1a-0cd5db894797` needs to specify somehow if the keys in the service for the given site are keys that exist in the yaml file or are extra keys outside the yaml configuration, this is important for the UI.

17. Executing `GET http://localhost:8080/api/v1/service-integrations/serviceExample1` always returns the `SYSTEM_HOST` with the `configured` flag in `false` even if was already configured.

19. We need to update the Integration services section of the dev-wiki with the latests changes.

---
20. We need to be able to read secrets from code, most of the reads initially will come from code, like viewtools and workflow actiontlets, we need a method to read specific keys for a service and host, we already have a `getSecrets` that may work but a method to request individual keys is still required. But the most important requirement here (https://github.com/dotCMS/core/issues/17682) is that when the method is accessed directly for now we won't validate permissions, the current `getSecrets` implementation is closed to admins and users with the Services portlet enabled. **This improvement will be implemented on this task https://github.com/dotCMS/core/issues/18217** 

---
21. Executing twice:
``` yaml
POST http://localhost:8080/api/v1/service-integrations
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  "key" : "serviceExample6",
  "siteId":"SYSTEM_HOST",
  "params": {
    "parameter1": {
      "value": "Test - Value1",
      "hidden": false,
      "type": "STRING",
      "label": "Test - This is string param",
      "hint": "Test string."
    }
  }
}
```
The system is telling I have more configurations than exiting sites.
![image](https://user-images.githubusercontent.com/923947/74746825-9f6ccb00-522b-11ea-9d64-a5f05a9ded99.png)

---
## QUESTION:
I think the key store just needs to save the secret value, all the other data can be get from the yaml file, we don't need to have duplicated data, or could be faster to save all the secret properties in the key store?

**Comment by wezell** [comment]
Required fields can be added and deleted normally.  If a required field for a configuration does not have a value, then that configuration should not be marked as "configured" in the listing screen. We will need to validate the configurations when we load them into cache.

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18244

**Comment by nollymar** [comment]
**Passed internal QA**
