### ISSUE TITLE
JS Issues when viewing a page in Timemachine

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17951]
We are unable to test this specific case since we have multiple JS errors and we are unable to load the events page from a future time machine snapshot. 

We need some work here: https://www.screencast.com/t/astm5vcVX

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/17594#issuecomment-581649341_

**Comment by alfredo-dotcms** [comment]
now with the new starter the `news event page` does not exist, so based on the evidence, there's no way reproduce this bug

**Comment by jgambarios** [comment]
Probably related to: https://github.com/dotCMS/core/issues/17923

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/81583444-a3157700-936e-11ea-9f3c-e29e1988d37e.png)

**Comment by nollymar** [comment]
I couldn't reproduce any of the issues reported using the same starter

**Comment by bryanboza** [comment]
Fixed, unable to reproduce because we change the starter site, tested multiple pages with the new starter and works as expected.
