### ISSUE TITLE
The content disappears after a copy of the site

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#17954]
### Describe the bug
When you have a page with a advance template and content linked with it, the content just disappears after a site copy.

### Steps to reproduce the behavior:
1. Create a new advanced Templa, include a parseContainer to any container (any type of Container no matter)
2. Create a new page with the new Template
3. Add content
4. Copy the site
5. Go to the new site, and check the copy of the new page

The bug here is that the parseContainer is not changed in the copy of the site, it still point to the container in the original site.

### Expected behavior
The content should be the in the page copied

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/17990
https://github.com/dotCMS/enterprise-2.x/pull/700

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes, now after copy site we have the same contents in the page. Tested on release-5.2.7 // Postgres // FF
