### ISSUE TITLE
[Content Types] : Field delete and update operations are taking a very long time to finish

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#17953]
Reported via Support: [100342](https://dotcms.zendesk.com/agent/tickets/100342), [99311](https://dotcms.zendesk.com/agent/tickets/99311)
Reproducible in dotCMS 5.0.3, 5.1.6, and latest master.

Deleting and moving fields inside a Content Type are both very heavy operations strictly related to the number of Contentlets associated to it. Moving a field from one position to the other is a relatively simple operation. However, deleting a field involves updating a very high amount of records in the database as well as invalidating a lot of information in both memory and file system caches.

Such operations occur backstage, so the user does not realize they're happening and they believe that a field has been deleted/moved immediately, which is not true at all. This causes the user to think they can delete or move other fields right away and, at this point, the application is overloaded with other delete and/or move operations which usually results in two situations: (1) The sort order of fields is completely affected, and (2) the user is not able to delete or move fields anymore because of internal conflicts -- sometimes when seeing the `This URL does not exist` error message -- and the process just hangs without any errors in the log.

### Steps to reproduce the behavior (**please ask the Support Engineers for more details**):
1. Create a Content Type with a high number of fields. Ideally, around 60 fields.
2. Create a high number of Contentlets of the previous Content Type, around 5.000 or more.
3. Start moving and deleting fields. At some point, you won't be able to.

**NOTE TO DEVS: You can add poor man's debug code to this method: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/services/ContentletLoader.java#L586 so you can see how intensive the process is when deleting a field, and how much time it takes for a field to be finally deleted. More involved classes/methods are:**

- https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/contenttype/business/FieldAPIImpl.java#L124
- https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/contenttype/business/FieldAPIImpl.java#L543
- https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/services/ContentTypeLoader.java#L291
- https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/services/ContentletLoader.java#L586

### Expected behavior
If the process of dealing with fields is always complex, then users should be notified about that via UI. For example, blocking the edit page while a field is being deleted/moved while they or someone else is updating the Content Type.

### Additional context
This is causing problems to customers with a high number of Contentlets for a given Content Type.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Unit test

**Comment by wezell** [comment]
This is fixed in master- see #16939
