### ISSUE TITLE
Container last change are not showed in LIVE MODE

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#17964]
### Describe the bug
When you change a Container already linked in a page, and you save and publish it, the last container change are not show in the Page in LIVE mode, until the cache is cleaned.

### Steps to reproduce the behavior:
1. Create a new page
2. Create a new Container, can be empty for now, I mean without add any Content Type in it
3. Add the Container in the page
4. Create a new Content type and add it into the new Container, Save and publish the Container
5. Create a new content and save and publish it
6. Add the content to the page
7. Go to LIVE, the content is not show
8. If you Save and Publish the page then the content is showed.

![Steps](https://user-images.githubusercontent.com/10408015/74066128-20ba9700-49bc-11ea-8684-a11ec0d63416.gif)

![Steps_2](https://user-images.githubusercontent.com/10408015/74066135-24e6b480-49bc-11ea-837a-82fa31f8ebb6.gif)

### Expected behavior
The content should be showed

**Comment by bryanboza** [comment]
Note to QA: We need to retest this one #17594  when this one will be solved

**Comment by hmoreras** [comment]
in the endpoint `api/v1/page/render` the property `rendered `do not have the latest changes., in live mode, until is publish. this might be the expected behavior ?

**Comment by fmontes** [comment]
Not an issue
