### ISSUE TITLE
Content Search: Related Content select box breaks with multilingual content

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17971]
### Describe the bug
A Javascript error is thrown in console when I try to filter by related content field and there is multilingual content 

### Steps to reproduce the behavior:
1. Create a Parent Content Type and a Child Content Type
2. Add a relationship field from Parent to Child (One to Many) and make it "User Searchable"
3. Create multilingual content for Child Content Type (eg:. English and Spanish)
4. Create a content in English for Parent Content Type and relate to the multilingual versions created in Step 3
5. In Content Search, filter by Parent Content Type and by the relationship field created in Step 2. None option is listed and this error is shown in the JS console:

<img width="802" alt="Screen Shot 2020-02-11 at 9 29 48 AM" src="https://user-images.githubusercontent.com/8741395/74245506-1bf22d80-4cb1-11ea-9d63-266330a2e919.png">

### Desktop (please complete the following information):
 - Browser Chrome
 - Version 5.2.4

**Comment by nollymar** [comment]
This PR fixes the issue: https://github.com/dotCMS/core/pull/17977

**Comment by nollymar** [comment]
**Note to QA:** Please test with multilingual and non-multilingual content too

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. Tested on release-5.2.7 // Postgres // FF
