### ISSUE TITLE
When searching for related content, click to relate is disabled

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#17981]
Tested on latest 5.2.4 release.

After creating a relationship between two content types, and then searching for related content, the whole line shows that it is clickable, but nothing happens (this used to work for the whole line) - forcing the user to click on the checkbox at the far right of the row.  That is the first problem.

![relationshipsBug](https://user-images.githubusercontent.com/1569167/74355622-bbcbbc00-4d82-11ea-945a-d3089dca2217.png)

As you see in the image/video, the second problem, is that the clickable relate box is also hidden if there are a lot of show in list columns - which also makes usability difficult for large clients who handle lots of relationships.

![relationshipsBug](https://user-images.githubusercontent.com/1569167/74355311-511a8080-4d82-11ea-8628-9216a6067bff.gif)

**Comment by alfredo-dotcms** [comment]
PR
https://github.com/dotCMS/dotcms-dojo-theme/pull/69/files
https://github.com/dotCMS/core/pull/18047/files

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.8 // Postgres // FF
