### ISSUE TITLE
Update push publish dialog to use Angular one

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#17982]
Right now we have a combination of two dialog to push publish: a dojo and an angular (in content types). We need to remove the dojo in favor of the angular one, in order to do that:

1. **core:** Replace every calling to open the dojo dialog for a Custom Event: `dotcms.pushpublish.asset`.
2. **core-web:** Listen to the event in angular and open the Push Publish dialog we use in content types.

### To consider:
1. Check what we need to pass from `core` and pass it in the event
2. Add a `appendTo="body"` [here](https://user-images.githubusercontent.com/751424/74381608-665ad380-4db1-11ea-99ae-1424a7b17a66.png).
3. We have a different URL to do the `POST` when the object is a Bundle, right now we only using 
4. Wider PP dialog
5. Remove the “push” word in front of each action in the select

```
/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/publish
```

But if is a bundle we need to use:
```
/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/pushBundle
```
    

## Acceptance Criteria

1. Use Angular Push Publish dialog everywhere
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
![test2](https://user-images.githubusercontent.com/751424/75820444-f8774b80-5d61-11ea-87ea-ecee7c4e01ef.gif)

1. Enable and disable Publish and Expire date accordingly
2. Use same styling as edit mode (make this select button default)

**Comment by fmontes** [comment]
### Calendar:
1. Add a hover effect, lightest gray
2. Highlight the "selected" value
3. Add cursor: pointer to the calendar

**Comment by fmontes** [comment]
## Bug
When the push publish is a sub action is still showing the dojo dialog

**Comment by fmontes** [comment]
Don't poppin' when exec WF from edit contentlet.

**Comment by bryanboza** [comment]
We need the same dialog on rules:
![image](https://user-images.githubusercontent.com/2641437/81602458-e4675000-9389-11ea-88ec-29a676d19320.png)

**Comment by wezell** [comment]
Not a blocker

**Comment by hmoreras** [comment]
PR's for PP on Rules: 
https://github.com/dotCMS/core/pull/18492
https://github.com/dotCMS/core-web/pull/1327

**Comment by fmontes** [comment]
The PP for rules comes for 5.3.1 all the others instances went in 5.3.0

**Comment by fmontes** [comment]
Now working in rules

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF

**Comment by wezell** [comment]
The window does not match the original mock.  Ask @fishsmith for it.

**Comment by wezell** [comment]
The dialog should look like this:

![Screen Shot 2020-06-18 at 3 04 59 PM](https://user-images.githubusercontent.com/934364/85061710-4418fe00-b175-11ea-8caf-e3700c70d2be.png)
