### ISSUE TITLE
Our Open Distro image should have a volume

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17997]
When you start and stop our open distro image, we lose the index. In our call to docker, we need to define a persistent volume when we start open distro to maintain the volume.

This should be in the dotStartup.sh script.

**Comment by dsilvam** [comment]
https://github.com/dotCMS/tomcat/pull/15

**Comment by dsilvam** [comment]
**Note to QA** 

Steps to test:
1. Bring up dotCMS via `dotStartup.sh/.bat` 
2. Check elasticsearch is up and indices are ok.
3. Bring down dotCMS via `dotShutdown.sh/.bat` 
4. Check elasticsearch is down. 
5. Repeat steps 1 and 2 and indices should be ok

To check elasticsearch is up/down use:

```curl -XGET https://127.0.0.1:9200/ -u admin:admin --insecure```

**Comment by nollymar** [comment]
**Passed internal QA** . Tests results: Success

**Comment by bryanboza** [comment]
Fixed, tested on master and this is working as expected
