### ISSUE TITLE
Relationship fields disappearing

### ISSUE THREAD

**Issue by joseojeda282** [dotCMS/core#17993]
### Describe the bug
Hello, I've been having an issue with some relationship fields. Sometimes when querying for a contentType a field with relationships to another contentType dissapears, even though I have the depth option.

When I save the content again it reappears for a second and on a refresh of the query it disappears again.

By the way I double checked permissions just in case, but it was working before anyways.

A temporary fix is delete the relationship field on the content type but it happens again after some time

### Steps to reproduce the behavior:
Not really sure. Happens sometimes and seemingnly random and it happened with different content types.

### Expected behavior
Show the fields when querying with the json api.

### Screenshots
![image](https://user-images.githubusercontent.com/54086603/74561687-cdaa8c00-4f47-11ea-8728-cbd4cb74c588.png)

When running the api http://myUrl:8080/api/content/render/false/depth/3/type/json/query/+contentType:SucursalesType

I get this:

![image](https://user-images.githubusercontent.com/54086603/74561848-30038c80-4f48-11ea-82e3-61b5e46318ce.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser: n/a
 - Version 5.1.6
 - Database PostgreSQL

**Comment by nollymar** [comment]
Hi @joseojeda282 . This issue has been fixed. I encourage you to update to our latest release  5.2.5
