### ISSUE TITLE
Create a new site from an existing site broken

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#18012]
### Describe the bug
When you switching between sites in Site Browser and then go to Site manager module and try to create a new site from an existing one an error happens and the site is created but the content does not

### Steps to reproduce the behavior:
1. Create 3 sites from an existing site
2. Go to `Site Browser` and change sites several times (from demo to the new ones created and viceversa)
3. Go back to site manager module and create a new site from an existing one (demo)
4. An error occurred and the content is not copied to the new site

### Expected behavior
A new site must be created from an existing one with all content

### Screenshots
![image](https://user-images.githubusercontent.com/37185433/74852072-bb42a080-5301-11ea-8f14-d5f43d6b094c.png)

### Environment
Browser: Chrome 80.0.3987.106
OS: Mac OS Catalina 10.15.3

**Comment by wezell** [comment]
@alfredo-dotcms what branch is this in?  Is this in master?

**Comment by alfredo-dotcms** [comment]
> @alfredo-dotcms what branch is this in? Is this in master?

**Comment by alfredo-dotcms** [comment]
this happens in `core` master
