### ISSUE TITLE
ENABLE_NAV_PERMISSION_CHECK=true breaks NavTool

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#18016]
### Describe the bug
I have recently upgraded a dotCMS instance from 4.2.2 (5.0.3 > 5.2.4) to 5.2.5. The site relies on NavTool with permission checking enabled to determine whether a page/file in site navigation is available. As an example, we have the following layout (Anon = CMS Anonymous):

```
Path                                 Anon           Authenticated
-----------------------------------------------------------------
/                                    Y             Y
/investments/                        Y             Y
/investments/peformance-reports      Y             Y
/investments/consultants             N             Y
/investments/strategic-actions       N             N
```

In the case of Anon "Y", Anon is inheriting read access from root. In the case of Anon "N", the containing folder has Read access for Anon disabled as shown:

Anon N:

![image](https://user-images.githubusercontent.com/9543257/74868777-cd820600-5324-11ea-9b64-7dce63c4127d.png)

Anon Y Site Root:

![image](https://user-images.githubusercontent.com/9543257/74868806-d70b6e00-5324-11ea-8748-2f7f51fad7fd.png)

When `ENABLE_NAV_PERMISSION_CHECK=false`, everything shows up with complete disregard for permissions, as intended! 

When `ENABLE_NAV_PERMISSION_CHECK=true` is when things break completely, as in, no navigation whatsoever, for any input path. No matter what directory the user is currently in, none of the navigation items display at all, as if the user has permissions to nothing. If explicit View permissions are set at the parent directory, or even the page itself, nothing. Even logged in with a user who has the CMS Administrator role, nothing shows up. I did verify the property was set using $config.

As an aside, this did work perfectly in 4.2.2 before the upgrade, no changes to this code have been made, it's mostly a copy of the demo `$navtool` code from the Quest theme. I know this was an issue as of 5.2.4, not sure if 5.0.x/5.1.x had problems.

Unfortunately, there are no exceptions being triggered, and nothing useful in the logs related to this.

As a test, I spun up a fresh local dotcms instance running 5.2.5, and was able to confirm the issue in a brand new installation.

Left Side:  `ENABLE_NAV_PERMISSION_CHECK=false`
Right Side: `ENABLE_NAV_PERMISSION_CHECK=true`

![image](https://user-images.githubusercontent.com/9543257/74869046-3cf7f580-5325-11ea-8ab9-892262c0938d.png)

The only thing that is in dotmarketing-config-ext.properties is this:

![image](https://user-images.githubusercontent.com/9543257/74869066-484b2100-5325-11ea-9cdd-32c403cc9bde.png)

Cheers!

**Comment by kristopherve** [comment]
@wezell thank you very much for adding this bug to the Bug Sprint list. I have a client I'm working with to upgrade their site since December, and we have been blocked by this bug from proceeding.

Do you have any insight into when this bug will be prioritized?

Thank you for your time!

**Comment by wezell** [comment]
Please test any changes here using `ab -n 10000 -c 15 http://localhost:8080/shop/index`

We need to make sure that we are not hitting the database to perform this lookup.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18180/files)

**Comment by hmoreras** [comment]
Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /shop/index
Document Length:        12397 bytes

Concurrency Level:      15
Time taken for tests:   72.572 seconds
Complete requests:      10000
Failed requests:        0
Non-2xx responses:      10000
Total transferred:      127050000 bytes
HTML transferred:       123970000 bytes
Requests per second:    137.79 [#/sec] (mean)
Time per request:       108.858 [ms] (mean)
Time per request:       7.257 [ms] (mean, across all concurrent requests)
Transfer rate:          1709.64 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.7      0     122
Processing:    28  108  47.4     99     737
Waiting:       28  108  47.3     99     737
Total:         29  109  47.4     99     737

Percentage of the requests served within a certain time (ms)
  50%     99
  66%    113
  75%    124
  80%    131
  90%    159
  95%    190
  98%    233
  99%    264
 100%    737 (longest request)

**Comment by wezell** [comment]
@hmoreras we need to see if the database is getting hit while this test is going on - from the performance, it looks like it is.  You will need to turn on DB logging to see this.  To do this, change the `show_sql` property to true in your `webapps/WEB-INF/classes/hibernate.cfg.xml` and rerun the tests

**Comment by hmoreras** [comment]
if the permission to view a folder is removed ( Destinations ) to the anonymous user. Is still visible in the menu

**Comment by hmoreras** [comment]
> @hmoreras we need to see if the database is getting hit while this test is going on - from the performance, it looks like it is. You will need to turn on DB logging to see this. To do this, change the `show_sql` property to true in your `webapps/WEB-INF/classes/hibernate.cfg.xml` and rerun the tests.
> 
> We should not be hitting the DB with every request.

it looks like is not hitting the DB, just getting a bunch of these : 

> ...16:21:12.716  WARN  navigation.NavResultHydrated - getChildren null @ http-nio-8080-exec-8
16:21:12.724  WARN  navigation.NavResultHydrated - getChildren null @ http-nio-8080-exec-5
16:21:12.726  WARN  navigation.NavResultHydrated - getChildren null @ http-nio-8080-exec-15
16:21:12.726  WARN  navigation.NavResultHydrated - getChildren null @ http-nio-8080-exec-11
16:21:12.739  WARN  navigation.NavResultHydrated - getChildren null @ http-nio-8080-exec-6...

**Comment by hmoreras** [comment]
> if the permission to view a folder is removed ( Destinations ) to the anonymous user. Is still visible in the menu

this is woking as expected currently in master.

**Comment by bryanboza** [comment]
Fixed, tested on master and it works as expected
