### ISSUE TITLE
Pages without CMS_ANON are not redirecting to login

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18010]
You can see this using the old starter site.

Hitting  
https://demo.dotcms.com/intranet

Should result in a 401 which should redirect you to the login page, e.g.
https://demo.dotcms.com/dotCMS/login?referrer=/index

instead, it throws a 500 exception

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18011

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.6 // Postgres // FF
