### ISSUE TITLE
Switching from WYSIWYG to Text and back to WYSIWYG

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18018]
We missed a merge when updating the wysiwyg in 5.2.3.  There is an issue with the wysiwyg field that prevents a user from switching from TinyMCE to Text and Back Again. This has been fixed in master since 5.2.3 but never made it to a release branch. 

I believe this PR fixes it:  #17787

**Comment by dsilvam** [comment]
**Passed Internal QA by @wezell **. Tested on master.

**Comment by bryanboza** [comment]
We need some work here: Switching back and forth between WYSIWYG and hitting cancel on the popup does not cancel completely, because if leaves the wrong editor
