### ISSUE TITLE
Add "Show in list" to Binary Fields

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18022]
When creating a content type that has a binary field, sometimes you want to show the filename in the listing, e.g. dotAssets.

1. We need to add the "Show on Listing" to the binary and if it is selected, we show it.
2. Change dotAsset to default to have "Show on Listing" selected.

**Comment by wezell** [comment]
We need to make sure that we are not going back to the FS to read the filename continually - meaning we need to cache it in the content object in mem lazily so it can be re-read - FS reads are expensive especially on large sites.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18037/files)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.7 // Postgres // FF, now we already have this option on the binary fields. A couple of enhancements already reported on new cards
