### ISSUE TITLE
[Content] : Container not behaving correctly when reaching max contents

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18021]
Reported via Support: [100484](https://dotcms.zendesk.com/agent/tickets/100484)
Reproducible in dotCMS 5.0.3, 5.2.5, and latest master (5.2.6)

The definition of a Container allows you to set the maximum amount of contents it can hold. When editing a page and adding contents to it, there are 2 specific problems that arise once you reach that max number:

1. You cannot re-order contents (specifically when you reach the max contents).
2. The UI allows you to add as many contents as you want. It doesn't take the max contents value into consideration. Even though the changes are NOT persisted, i.e., only the max contents are saved, this is confusing to users.

### Steps to reproduce the behavior:
1. Create a Container that holds **News** contents. Set the value of the `Max. Contents` field to 4.
2. Create a Template that uses the previous Container.
3. Create a page that uses the previous Template, and add content to it.
4. You can reproduce the following errors now:
4.1  After you add the fourth content, you cannot re-order contents anymore.
4.2 The Container allows you to add more than 4 contents.

### Expected behavior
The re-order must works correctly, and the UI must not allow you to add more contents than specified

### Desktop (please complete the following information):
 - OS: Max OS X 10.15.3
 - Browser: Chrome, Firefox

### Additional context
Most customers do set a max number of contents for a given Container. So, not being able to re-order them when reaching the max value is definitely a problem for them. The only workaround is to get rid of the bottom content, re-order the ones that need to be moved, and then add it back.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
PR:
https://github.com/dotCMS/core/pull/18078/files
https://github.com/dotCMS/core-web/pull/1280

**Comment by alfredo-dotcms** [comment]
PR:  D&D fix
https://github.com/dotCMS/core-web/pull/1281

**Comment by fabrizzio-dotCMS** [comment]
I followed the step listed but the content-types suggested here aren't available on the new starter anymore. 
So I tested with a banner but the selected content was too big to allow me to move all the different entries I had added. the container gets overflown. 
So I created my own Content-type and used it  from within the template to render something like ${name}
Doing that I was able to verify that the behavior expected is now in place. 
The Max number of contents is respected at all times and the re-order also works fine. 

The only thing I  found is that if I create a container with an initial max number of contents of 4. it allows me to place 4 contents. But If I go back to the container definition and lower the number to 3. The page continues to show the initial number of contents. Which I think is fine. I am passing the ticket.

**Comment by wezell** [comment]
If you create a container that takes 2 pieces of content, you should be able to add two pieces of content in every language the system supports.  Now, if you add two english contentlets, switch to spanish you cannot add two spanish contentlets.

**Comment by jgambarios** [comment]
Reverted changes in the `release-5.2.8` branch in `core` and `core-web`, this code only live in master now.

**Comment by erickgonzalez** [comment]
Tested the following scenarios and all worked fine:

* Respecting max Contents per language: the limit of max contents is per language, so if the limit is 2 you can 2 contents for each language.
* Re-order contents when max contents are reached: can reorder the contents successfully when the value of the max contents is reached.
* Reach max contents and then changed the value of max contents: changing the value of max contents to a lower value makes one content to disappear.

**Comment by bryanboza** [comment]
This message needs some styling help:
![image](https://user-images.githubusercontent.com/2641437/80040230-df179380-84b6-11ea-875f-11da47393084.png)

**Comment by hmoreras** [comment]
> This message needs some styling help:
> ![image](https://user-images.githubusercontent.com/2641437/80040230-df179380-84b6-11ea-875f-11da47393084.png)

PR: https://github.com/dotCMS/core-web/pull/1308

**Comment by bryanboza** [comment]
According to the PR, this message is hardcoded, we need to translate this when you change the instance language.
SC: https://www.screencast.com/t/otYBmrqiYY

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
