### ISSUE TITLE
Unable to add rules if you don't have default site permissions

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18023]
If you don't have permissions to the default site, we are unable to add rules to some specific site, we are getting a (403- permissions error) and you can't add the rule. 

LOG error: https://gist.github.com/bryanboza/a880b7d627ec4cf6a451bf3e92c2ae96

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new site (blank1)
3. Create a new role and give full permissions to the new site (blank1), also set access to the rules tool
4. Login as the new user 
5. Try to create a new rule 

### Expected behavior
We need be able to add rules to multiple sites if you have the permissions over the site 

### Desktop (please complete the following information):
Tested on release-5.2.6 // Postgres / / FF

**Comment by wezell** [comment]
dupe: #17901
