### ISSUE TITLE
Create a very shallow postgres docker image

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18039]
We need to create a very simple docker image that extends from postgres/postgres:11 that creates the data folder programatically -  so we can run the standard default postgres image.

We should also update our docker-compose examples to use this image and also sets a few environmental variables such as 
```
'shared_buffers=256MB' 
'max_connections=500' -
listen_addresses = '*'
```

**Comment by nollymar** [comment]
Useful links: 
- https://hub.docker.com/_/postgres
- https://github.com/docker-library/postgres/pull/253
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://medium.com/better-programming/running-a-container-with-a-non-root-user-e35830d1f42a
- https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15
