### ISSUE TITLE
Test Site Search functionality

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18035]

**Comment by dsilvam** [comment]
Passed Internal QA: Site search functionality working as expected. 
Tested: 

- Include /exclude paths
- Multilingual
- Own index
- Scheduled index creation
- Multi site

**Comment by dsilvam** [comment]
Passed QA: Site search functionality working as expected.
Re-Tested:

Include /exclude paths
Multilingual
Own index
Scheduled index creation
Multi site
