### ISSUE TITLE
5.2.6 "Accept is mandatory"

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18032]
Trying to save a content from the backend with a binary field with an `accept` value throws this error:

You can reproduce on the current starter in 5.2.6 on the "Contact Us" form entry.  The binary has an `accept=image/*`

![image](https://user-images.githubusercontent.com/934364/75199824-1e816800-5732-11ea-996e-25d57897b717.png)

**Comment by fmontes** [comment]
The accept is a required checkbox.
