### ISSUE TITLE
Hitting the enter key in the relate content popup should search

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18038]
In the content search screen, if you hit enter, it will search.  In the relate content popup, it does not.  We need to enable search when the user enters search crieteria.

We will need a debounce function (like we have on the content search screen) to prevent over zealous fetching

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core/pull/18054

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18122

**Comment by wezell** [comment]
Search should be on top of other search criteria AND also receive focus

**Comment by fmontes** [comment]
## Needs work:

Blog > Author related field is not searching on keydown, others fields does.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/18175 for Blog scenario and language dropdown feedback

**Comment by jdotcms** [comment]
I have tested on master, content search and related. Working fine on FF + MAC OS

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.8 // Postgres // FF
