### ISSUE TITLE
Test Maintenance > Index tab 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18043]
Test should include:
- [x] Full Reindex
- [x] Reindex by content type
- [x] Stop reindex and make active
- [x] Stop reindex
- [x] Download failed records
- [x] Activate/Deactivate Index
- [x] Close Index
- [x] Clear Index
- [x] Delete Index 
- [x] Index snapshot functionalities are not allowed. All buttons and menu options related to this must be removed
- [x] Optimized index
- [x] Flush ES Cache
- [x] Delete Then Reindex
- [x] Set replicas
- [x] Index Health popup

**Comment by dsilvam** [comment]
Note to QA: Set replicas shouldn't appear and it does not. All good.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgress // FF
