### ISSUE TITLE
Cluster Scaling

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18050]
Currently we have a few issues scaling a new cluster.  When you try to use the K8 or docker-compose examples with the latest dotCMS, the cluster never gets joined by the server that initially imported the starter - all you get are these messages:
`Cluster not yet active. Not rewiring`

This is because on initial ClusterFactory startup, the codeblock hits this:
https://github.com/dotCMS/enterprise-2.x/blob/master/src/main/java/com/dotcms/enterprise/cluster/ClusterFactory.java#L71

and the `CLUSTER_INITED` boolean never gets set to `true`

**Comment by wezell** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/702

**Comment by erickgonzalez** [comment]
Tested and working as it should.
Started a 2-node cluster using docker and the second node joined the first one. Adding log and Network Tab screenshot:

```
INFO  cluster.ClusterFactory - Found Servers:[{serverId=51141b43-7284-425b-ad67-ab48d26475b7, clusterId=4fe4fbd283, ipAddress=172.19.0.4, host=null, name=9440836b4784, esTransportTcpPort=null, esNetworkPort=null, esHttpPort=9200, cachePort=5701, lastHeartBeat=1583960550002, key=null, licenseSerial=44e589a7-d2f8-46ea-83e8-cc99f20e7252}, {serverId=72f6c9ef-f78c-4484-aa0d-9e962ed6b7b3, clusterId=4fe4fbd283, ipAddress=172.18.0.4, host=null, name=e35303d96f77, esTransportTcpPort=null, esNetworkPort=null, esHttpPort=9200, cachePort=5701, lastHeartBeat=1583960550019, key=null, licenseSerial=9da162ab-c7ad-42b0-a26f-1f8c8ab709a5}]
```
![Screen Shot 2020-03-11 at 3 03 11 PM](https://user-images.githubusercontent.com/5278970/76463791-aeb5e300-63a9-11ea-83b2-4764d228e211.png)

**Comment by wezell** [comment]
How did the hazelcast transport look?  That is what was not getting started?

**Comment by erickgonzalez** [comment]
Hey @wezell I saw all green on the network tab regarding the Cache Transport (see screenshot attached) and there is no error on the logs regarding the something went wrong when starting the 2nd node (neither the message you were seeing before) and got the ping messages on each node:

> dotcms_2               | 14:33:02.897  INFO  business.HazelcastUtil - Initialized Hazelcast member com.hazelcast.client.impl.HazelcastClientInstanceImpl@d440b49
dotcms_1               | 14:33:02.951  INFO  transport.HazelcastCacheTransportClient - Received Message Ping Thu Mar 12 14:33:02 GMT 2020
dotcms_1               | 14:33:02.952  INFO  transport.HazelcastCacheTransportClient - ACK Received Thu Mar 12 14:33:02 GMT 2020
dotcms_2               | 14:33:02.952  INFO  transport.HazelcastCacheTransportClient - Sending Ping to Cluster Thu Mar 12 14:33:02 GMT 2020
dotcms_2               | 14:33:02.967  INFO  transport.HazelcastCacheTransportClient - Received Message Ping Thu Mar 12 14:33:02 GMT 2020
dotcms_1               | 14:33:02.968  INFO  transport.HazelcastCacheTransportClient - ACK Received Thu Mar 12 14:33:02 GMT 2020
dotcms_2               | 14:33:02.969  INFO  transport.HazelcastCacheTransportClient - ACK Received Thu Mar 12 14:33:02 GMT 2020
dotcms_2               | 14:33:02.969  INFO  transport.HazelcastCacheTransportClient - ACK Received Thu Mar 12 14:33:02 GMT 2020

![Screen Shot 2020-03-12 at 8 36 00 AM](https://user-images.githubusercontent.com/5278970/76532965-f89bd900-643c-11ea-957f-7c1cc0a1f9a3.png)
![Screen Shot 2020-03-12 at 8 36 06 AM](https://user-images.githubusercontent.com/5278970/76532971-fa659c80-643c-11ea-922d-26045dc5a7e5.png)

**Comment by wezell** [comment]
You see how it is only reporting 1 cache node?  When you have a cluster spun up, that number should => number of nodes in the cluster.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/docker/pull/22
