### ISSUE TITLE
Crtl+S should save content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18053]
Users appreciate keyboard shortcuts.  For example, it would be wonderful if hitting Ctrl+S would save the content and just let you resume editing.

I think we have made this possible with workflows and our default actions.  When a user hits ctrl+s, we can fire the default action for "Edit"

**Comment by john-thomas-dotcms** [comment]
Agreed, I use shortcut keys all the time.

I think using default actions would work, but the actual ideal would probably be to allow setting a shortcut key for any workflow action (not just default actions).  For example, Ctrl-S might save, but Ctrl-Alt-S might save and publish.
