### ISSUE TITLE
Remove ES snapshot-related options in the UI

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18059]
The following options in the UI need to be removed: 

1. Maintenance -> Index -> Right click on a index -> "Download Index Snapshot"  
2. Maintenance -> Index -> "Restore Index Snapshot" button 

Also in Sitesearch portlet

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18065

**Comment by nollymar** [comment]
**Passed internal QA**. Both options were removed from UI

**Comment by nollymar** [comment]
**Note to Doc:** Remove this feature from doc

**Comment by bryanboza** [comment]
Fixed, those actions were removed
