### ISSUE TITLE
Login As Bug with limit user

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18069]
### Describe the bug
When You try to Login As with a user without permission in any site, You get a error in the Login As dialog.

<img width="363" alt="Screen Shot 2020-02-28 at 3 03 28 PM" src="https://user-images.githubusercontent.com/10408015/75587382-f3ea2480-5a3b-11ea-8f83-a56f2075362f.png">

but if you refresh the page you get the new user Login.

### Steps to reproduce the behavior:
1. Create a new role. not have permission over any site
2. Create a new user with the new role
3. try to Login As with the new user.

### Expected behavior
Should get a better error message, and after refresh the page the new user should no be login.

**Comment by jcastro-dotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/18129

**Comment by hmoreras** [comment]
Core-web PR: https://github.com/dotCMS/core-web/pull/1287

**Comment by jcastro-dotcms** [comment]
Second PR: https://github.com/dotCMS/core/pull/18179

**Comment by fmontes** [comment]
## Tested
As Freddy described in the STR.

**Comment by bryanboza** [comment]
fixed, tested on master // Postgres // FF

**Comment by bryanboza** [comment]
We need some work here: 

- If you have permissions to see the page, but this page depends of a VTL file, we have an error when you try to see the page and after this continue showing the same error. 
SC: https://www.screencast.com/t/ZihwBAtuYAg

Here the role permissions: 
![image](https://user-images.githubusercontent.com/2641437/80244946-0db47c00-8627-11ea-8a3c-15dc1c638b24.png)

**Comment by bryanboza** [comment]
Fixed, tested on master, new stuff was moved to a card #18384
