### ISSUE TITLE
Remove references to load_records_to_index

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18068]
### Describe the bug
As the reindex logic was modified, we need to remove all references in code of the `load_records_to_index ` db function.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18150/files

**Comment by nollymar** [comment]
**Note to QA:** Please test fresh installations and upgrades on different databases: Postgres, MySQL, Oracle and MSSQL

**Comment by freddyucv** [comment]
**Passed Internal QA:** Check just in postgres but it have integration test for the others data base

**Comment by dsilvam** [comment]
Passed QA: Upgrade from 5.2.8 test in four dbs. Procedure is not there anymore. @bryanboza All upgrades went through without issues. Reindexed worked ok.
