### ISSUE TITLE
Site/folder field need auto detect the parent location and select this path by default 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18062]
When you add one of those fields to a content type, when you try to add a new piece of content this is located by default in the system host, we need auto-detect where lives the parent and set the same location, this because the piece of content will inherit the permissions from the parent 
SC: https://www.screencast.com/t/axr6yTwJm

Tested on release-5.2.7 // Postgres // FF

**Comment by wezell** [comment]
This is working as expected and has always worked. If you want the host to be autoselected, you can mark the site field as "required".
