### ISSUE TITLE
Temp multipart endpoint not auto-assign type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18064]
We have problems trying to use that functionality using the temp multipart resource:

If you try to send something like this:
```
curl --location --request PUT 'http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data-raw '{"contentlet":
    {
        "baseType":"dotAsset",
        "hostFolder":"test.com:/images",
        "asset":"temp_b99bb2b932",
        "tags":"test"
    }
}'
```

We are having an error and we are unable to upload the piece of content
error: ava.lang.String cannot be cast to java.io.File

FYI: If I try sending a multipar directly works as expected.

Here the log with the error : https://gist.github.com/bryanboza/b741ee258f180019137f730cda906614

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/18067

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
