### ISSUE TITLE
Minor Changes to H22 Defaults

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18060]
H22 or some sort of persistent caching is almost a requirement when running a content heavy loaded site as it helps smooth out the load on the content cache.  It can cause issues when a loaded server restarts and takes a long time to start up as it tries to reconnect to a loaded cache.  There is a setting: `cache.h22.recover.if.restarted.in.milliseconds` sets the time threshhold for when a h22 cache should try to recover an existing disk cache - this should be 0 by default so a restarted server will not try to recover a bad cache.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18061

**Comment by fmontes** [comment]
### Tested

1. hit a bunch of pages and look at how many contents are in your h22 cache. Then do a restart and see if there are still that many entries in your H22 cache. it should have flushed when you restarted

2. try to do simultaneous full cache flushes with load on a page - use ab or something (edited) 
```ab -n 100000 -c 15 http://localhost:8080/store/```

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
