### ISSUE TITLE
Save of checkbox field fails if Velocity var name of field is `properties`

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18073]
### Describe the bug

If you create a checkbox field in a content type, and name it so that the Velocity variable name of the field is `properties`, then when you make changes to the field in the content editing screen and then save the content, your changes to that field will not be saved.

**Note:** I expect this will probably be a problem with **_any_** type of field, but the only one I tested with explicitly was checkbox.

### Steps to reproduce the behavior:
1. Open any Content Type.
2. Add a Checkbox field.
    * Name it "Properties".
    * Add "Test|test" to the "Value" field.
3. Go to the Content Search screen and create a new content item of that content type.
    * Leave the checkbox you created un-checked.
4. Save the new content item and close the content editing popup.
5. Re-open the same content item.
6. Check the checkbox, then save and publish the content.
7. Close the content editing popup.
8. Re-open the same content item.
**Problem:** The checkbox is not checked.

### Expected behavior

The user should be able to save changes to any field we allow them to create.

This means that if `properties` is reserved for some reason, then when the user creates the field we should do one of the following:

* Prevent creation of the field with that velocity var name, **_OR_**
* Automatically increment the velocity var name (e.g. to `properties1`) to prevent a conflict.

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Chrome v76.0.3809.100
 - dotCMS v5.2.6 (authoring and demo)

### Additional context

If possible, we should check to see if there are any other hidden potential name conflicts with velocity var names, other than just `properties`.  So we should figure out where this conflict is coming from, and then figure out what other reserved words come from the same place, and make sure this same problem doesn't crop up again with some different velocity var name.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
Additional fix: https://github.com/dotCMS/core/pull/19736

**Comment by nollymar** [comment]
Needs work: It doesn't work for Multiselect fields. The selected value is not kept

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19750/files

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
