### ISSUE TITLE
[core] : Logging improvement when content reindex fails

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18072]
Found when working on dotCMS 5.2.3 upgrade for customer.

Error logging for the specific problem that the customer was having when fully reindexing their instance after upgrading is not clear enough.

### Expected behavior
The system must provide intelligent and useful logging when reporting errors.

### Additional context
Effective error reporting can help Support Engineers save a lot of time when troubleshooting problems in the application.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18092

**Comment by jcastro-dotcms** [comment]
PR # 2: https://github.com/dotCMS/core/pull/18167

**Comment by fmontes** [comment]
## Tested

1. Control Panel > Maintenance > Index
2. Right click in an index and “Desactivate Index”
3. Start DotCMS and see the error

```
13:18:00.880  ERROR business.ESContentFactoryImpl - Elasticsearch error in index 'cluster_3be7b6c05d.working_20200325131750'
13:18:00.880  ERROR business.ESContentFactoryImpl - Lucene Query: [ +contenttype:host +working:true ]
13:18:00.881  ERROR business.ESContentFactoryImpl - ES Query: {"size":10000,"timeout":"15000ms","query":{"query_string":{"query":"+contenttype:host +working:true","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"moddate":{"order":"desc"}}]}
13:18:00.881  ERROR business.ESContentFactoryImpl - Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
```

**Comment by bryanboza** [comment]
Fixdd, tested on master // Postgres // FF
