### ISSUE TITLE
Cannot Change Password from My Account v. 5.2.5 and 5.2.6

### ISSUE THREAD

**Issue by jasontt33** [dotCMS/core#18075]
After logging in to backend in upper right corner click my icon --> My Account --> fill out form to include Current Password --> Check Change Password --> enter a new password  and confirm new password == SAVE button is disabled. IF you take a character away from Current Password and add it back --> SAVE becomes enabled. I suspect a problem with the javascript validation

### Expected behavior
SAVE button should be enabled if Current Password is filled out + Change Passwd = checked + New Password + Confirm New Password match each other. 

![Screen Shot 2020-03-01 at 3 46 36 PM](https://user-images.githubusercontent.com/44835521/75633587-157e1400-5bd4-11ea-8732-6878e996ebe3.png)

### Desktop (please complete the following information):
Mac or Windows
Chrome or Firefox newer versions
dotcms Version 5.2.5 + 5.2.6

### Additional context
N/A

## Acceptance Criteria

1. Should match expected behavior

**Comment by jasontt33** [comment]
Reported by Customer Washington LNI

**Comment by fmontes** [comment]
Fixed: https://github.com/dotCMS/core/issues/18093
