### ISSUE TITLE
Images with + sign in title can't be added to rich text 

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18070]
### Steps to reproduce the behavior:
1. Upload an image with + in the title
2. Add new Content Generic 
3. Select add image and navigate to image from step 1
4. broken image link appears in Content Generic
5. Change name of image to remove + and it now shows in the Content Generic.

### Desktop (please complete the following information):
 - Version 5.1.6 (works correctly in 5.2.5

**Comment by nollymar** [comment]
I was not able to reproduce it in 5.3.5

**Comment by bryanboza** [comment]
Unable to reproduce. I proceed to close the card
