### ISSUE TITLE
In edit mode pre-execute field of a widget doesn't show

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18086]
### Steps to reproduce the behavior:
1. Add a widget with a pre-execute field to a page
2. In live mode it shows 'preexecute field'
3. In edit mode it shows nothing
![Screen Shot 2020-03-03 at 11 10 20 AM](https://user-images.githubusercontent.com/44986962/75800768-b210f500-5d3f-11ea-947d-44e16f37d918.png)
![Screen Shot 2020-03-03 at 11 10 34 AM](https://user-images.githubusercontent.com/44986962/75800770-b2a98b80-5d3f-11ea-83d9-9ee25061caa3.png)

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18139

**Comment by fmontes** [comment]
## Tested:

https://dotcms.com/docs/latest/widget-content-type

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
