### ISSUE TITLE
My Account window messed up

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18093]
The "My Account" window in dotCMS is a bit of a mess.

1. The only "password strength" field should be the "New Password".  Current Password and "Confirm New Password" should not show password strength.
2. the Save Button Active state is inverted - if you correctly "Confirm" the new password, the Save button becomes disabled. If you don't confirm the passwords, it allows you to save.

![Screen Shot 2020-03-04 at 9 32 10 AM](https://user-images.githubusercontent.com/934364/75889831-7dfb0a00-5dfb-11ea-88a9-8e21a3a224f7.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1282/files

**Comment by bryanboza** [comment]
We need some UI help when need to show a error message, we are expanding the window instead to show a multi line error
![image](https://user-images.githubusercontent.com/2641437/76786712-48e8a300-677d-11ea-849e-8559d87f884f.png)

**Comment by jgambarios** [comment]
The problem described above will be handle in a new ticket: https://github.com/dotCMS/core/issues/18143

**Comment by jgambarios** [comment]
Clicking outside the `Change Password` checkbox, meaning on the div that contains the checkbox, disables and enables the password fields without affecting the checkbox state.

**Comment by hmoreras** [comment]
> Clicking outside the `Change Password` checkbox, meaning on the div that contains the checkbox, disables and enables the password fields without affecting the checkbox state.

here the fix PR: https://github.com/dotCMS/core-web/pull/1288/

**Comment by fmontes** [comment]
Close in favor: https://github.com/dotCMS/core/issues/18143
