### ISSUE TITLE
Remove ES replica-setting logic from dotCMS

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18094]
There's still some of this in our code that needs to me removed since this is now controlled at a external Elasticsearch level

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18095

**Comment by dsilvam** [comment]
Note to QA: Please re-test with dotcms connected to an Elasticsearch cluster (at least 2 nodes) and check proper replica count

**Comment by freddyucv** [comment]
Passed Internal QA: 
- tested using this docker compose

https://github.com/dotCMS/core/issues/16914#issue-471967336

- checking number of nodes

<img width="421" alt="Screen Shot 2020-04-03 at 12 27 28 PM" src="https://user-images.githubusercontent.com/10408015/78394222-740a2980-75a8-11ea-8d7a-73e41e1bd1ba.png">
