### ISSUE TITLE
NPE adding a new piece of content to the news dotAsset base type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18108]
We have a NPE error every time you try to add a piece of content to a  `dotAsset` base type. At some point, we are trying to get the name of the binary and here is when we get the NPE. The same thing when you try to execute the copy action to some of these contents. 

ST: https://gist.github.com/bryanboza/f5f3e5845dcb42d84f75ef861e619583

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new content type dotAsset base type 
3. From content search, add a new piece of content 
4. See an error in the logs 

### Expected behavior
We need be able to add a new piece of content of any type without problems 

### Desktop (please complete the following information):
Tested on release-5.2.7 // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18115

**Comment by dsilvam** [comment]
**Passed Internal qa**: Followed mentioned steps without NPE in the logs and content was successfully saved and published.

**Comment by bryanboza** [comment]
Fixed, now we are able to save content of this base type without problems. Tested on release-5.2.7 // Postgres // FF
