### ISSUE TITLE
UserMod updates when user logs in, invalidates JWT cookie

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18101]
When a user logs in we update the user record with the last login date and clear the failed logins, etc.  

What happens is that our JWT cookie implementation checks that the JWT cookie is NEWER than the last user mod date, which is now invalid.

It looks like this:
1. User logs in
2. Login Success, dotCMS sends an access cookie with modDate = now()
3. dotCMS update user record with login success which changes the user.modDate = now()
4. DB commits
4. access cookie is now older than  user.modDate

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18131/files)

**Comment by erickgonzalez** [comment]
This issue probably needs the label **Needs Doc** since a new Resource was created.

**Comment by bryanboza** [comment]
Fixed, new card created in order to add the postman tests here #18213
