### ISSUE TITLE
After reindex finish it is keep checking status

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18100]
### Describe the bug
After the reindex process finish the request, it keep checking the status

### Steps to reproduce the behavior:
1. Start reindex process
2. Wait until the reindex finish
3. Check the browser Network tab
The following request keep to be sent:
http://localhost:8080/dwr/call/plaincall/CMSMaintenanceAjax.getReindexationProgress.dwr

<img width="1535" alt="Screen Shot 2020-03-05 at 2 28 06 PM" src="https://user-images.githubusercontent.com/10408015/76023048-04901400-5eee-11ea-8485-8d54ac5a1719.png">

### Expected behavior
The status request is not sent anymore after the reindex process finish

**Comment by wezell** [comment]
the UI polls to get its information.
