### ISSUE TITLE
Login As is not working

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18117]
### Describe the bug
When You try to Login As, You don't get log in

### Steps to reproduce the behavior:
1. Log in by Admin 
2. Create a new role, add permissions and tools
3. Create a new user
4. Try to login As to the new user
5. You keep log in as Admin

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/975bee2a-3a83-4952-abce-f7e73efff32b

### Expected behavior
Yu should get Login As the new user

### Desktop (please complete the following information):
 - Last in Master

**Comment by wezell** [comment]
Broken by changes here:

#18076

**Comment by fmontes** [comment]
Branch with fix: https://github.com/dotCMS/core/tree/issue-18117-login-as-broken

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/18166

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.2.8 // Postgres // FF
