### ISSUE TITLE
Copy Workflow results in incorrect next step

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18111]
### Steps to reproduce the behavior:
1. Select edit on an existing workflow
2. Select copy
3. Name the new scheme
4. Overview screen shows correct next step
5. Click into any of the steps and the next step drop down displays current step instead and functions with that next step rather than working properly.

### Desktop (please complete the following information):
 - Browser [e.g. chrome, safari] chrome, safari
 - Version [e.g. 22] 5.1.6, 5.2.6
![Screen Shot 2020-03-09 at 9 24 09 AM](https://user-images.githubusercontent.com/44986962/76222278-61d6de80-61e8-11ea-9ec2-e34343ffd161.png)
![Screen Shot 2020-03-09 at 9 24 27 AM](https://user-images.githubusercontent.com/44986962/76222280-626f7500-61e8-11ea-8ee3-728e7277a6d5.png)

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 and I'm unable to reproduce.
