### ISSUE TITLE
Host select not updating ... Grrrrr

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18125]
Adding a host, selecting a new host etc. is not sending a websocket event.

How many times can we fix this?

**Comment by hmoreras** [comment]
this problem is related to this fix, https://github.com/dotCMS/core/issues/17828. which is fixed on master. 

We miss to include this commit https://github.com/dotCMS/core/commit/422088676ffef0164c3a1ce1dac37eed8e5bc5d3 to the release branch.

Looking  forward to include this into 5.2.8

**Comment by bryanboza** [comment]
Fixed, now we are refreshing when you change the site selector
