### ISSUE TITLE
Need a default dotAsset content type

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18120]
We need to add a default dotAsset base type, this because if you try to send any file and you don't have this specific extension in the accept variable we are returning an NPE

Maybe we need to add a default dotAsset base type in the starter site and also need to fix the NPE 
Here the log error: 
https://gist.github.com/bryanboza/b6dc08ca39725096d90b237748931755

### Steps to reproduce the behavior:
1. Start the dotCMS instance 
2. Login as admin 
3. Try to send this curl commad: 
```
curl --location --request PUT 'http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--form 'json={
	 "contentlet": {
		"baseType":"dotAsset",
                "languageId":"1",
		"contentHost":"demo.dotcms.com"
	}
}' \
--form 'file=@/Users/bryanboza/Downloads/Untitled (1).pdf'
```
4. Check your log file

### Expected behavior
We need to handle that case and redirect to a default structure 

### Desktop (please complete the following information):
Tested on release-5.2.7 // Postgres // FF

**Comment by erickgonzalez** [comment]
A new starter was uploaded to artifactory.
PR: https://github.com/dotCMS/core/pull/18393

**Comment by erickgonzalez** [comment]
After downloading the new starter the curl command runs smoothly.

**Comment by bryanboza** [comment]
Fixed, tested on master with the new starter and now we have the default content type
