### ISSUE TITLE
Add depth option to page API

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18123]
### Problem Statement
Users are currently unable to retrieve the content of the relationship field in any of the contentlets inside a requested page using the dotcms page API /v1/page/render/{URL}. This limitation restricts the information accessible for users through the API.

### Steps to Reproduce
1. Create a content type with a relationship field
2. Create a content and add relation
3. Add this content to a page
4. Send a GET request to the dotcms page API /v1/page/render/{URL}.
5. Inside the containers object, see the contentlet added don't show the relationship field content.

### Acceptance Criteria
1. Update the dotcms page API /v1/page/render/{URL} to accept a new parameter named "depth".
2. The "depth" parameter should receive a number representing how deep in the contentlet relationship tree the response should include.
3. When a user sends a request with the "depth" parameter, the API response should include the content of the relationship field in any of the contentlets inside the requested page, based on the provided depth value.
4. API should return an appropriate error message if the "depth" parameter is not a valid number or is outside the allowed range.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
No response

### Quality Assurance Notes & Workarounds
1. Ensure that the new "depth" parameter is thoroughly tested for various valid and invalid inputs.
2. Test the API response to ensure the content of the relationship field in any of the contentlets inside the requested page is included as expected.
3. Verify that the error handling is robust and informative.
6. Perform load testing to ensure that the new feature does not negatively impact the API's performance or stability.

Updated by @fmontes

**Comment by wezell** [comment]
This needs to work when the page is rendered AND when the pageAPI is requesting JSON.

**Comment by zJaaal** [comment]
### Failed Internal QA

Docker Image: `[dotcms/dotcms:master_1fc8dba8_SNAPSHOT]`

When doing a GET request to a page that uses `urlContentMap` the blog inside this field doesn't contain the relationship field `author`.

You can test this url to reproduce it: `http://localhost:8080/api/v1/page/render/blog/post/ecotourism-in-costa-rica?language_id=1&depth=2`

**Comment by zJaaal** [comment]
## Failed Internal QA

Error messages when `depth` param is out of range or invalid are missing.

Docker Image: `[dotcms/dotcms:23.06_0bc51e36_SNAPSHOT]`

**Comment by jdotcms** [comment]
> ## Failed Internal QA
> Error messages when `depth` param is out of range or invalid are missing.
> 
> Docker Image: `[dotcms/dotcms:23.06_0bc51e36_SNAPSHOT]`

PR to fix the this feedback:
https://github.com/dotCMS/core/pull/25054/files

**Comment by zJaaal** [comment]
## Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_8d5b0f5e_SNAPSHOT]`

### Screenshot
https://github.com/dotCMS/core/assets/63567962/2f650bd3-91d2-4cf8-8b6b-6f1fa9e92579

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
