### ISSUE TITLE
404 Cache for URLMaps

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#18133]
There are cases where the regex used for URLMaps is to generic (For example `/{urlTitle}` https://github.com/dotcms/core/issues/17514) forcing the evaluation of almost every frontend request to validate if it is a URLMap, a 404 cache similar to the one we have in Vanity URLs would improve the performance evaluating URLMaps.

Related to:
* https://github.com/dotcms/core/issues/17514 where we fixed issues using URLMaps at the root causing on that case to have very generic regex that would catch almost every request.
* https://github.com/dotCMS/core/issues/18015 where we allow the use of `/`in URLMaps forcing the generated regex to be less restricted o in other words more generic catching more false cases.

**Comment by jcastro-dotcms** [comment]
This is highly common in many customer environments. This is both affecting performance and filling up the logs with unnecessary data.

**Comment by wezell** [comment]
Part of this is effectively done in #17917 where we wrote a query cache for ES.

**Comment by wezell** [comment]
I believe the importance of this issue has been minimized by the addition of the ES query cache.  Let us monitor this after the release of 5.3.0 and see if we are still seeing a lot of slowdowns caused by this issue.

**Comment by eceluci** [comment]
@wezell I have a problem with front-end pages. All pages than I want to access, returns 404.

**Comment by wezell** [comment]
@eceluci  That is not because of this issue.  I would try the listserv/forum. https://dotcms.com/forum/
