### ISSUE TITLE
Site Search not indexing all versions of multi-lang content for URLMapped content

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18132]
Steps to reproduce:
1 - Create a URL-Mapped content (i.e. Blog) in a second language (i.e. Spanish)
2 - Schedule a Site search run for "Now" including demo host and the second language only. 
3 - Your content created in 1. won't show up in the results.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18142

**Comment by nollymar** [comment]
**Needs work:** It works fine when using Spanish language, but if I run the same test using Italian, there is no results. Just in case you need it, the Spanish language has ID=2, but the Italian one has a UUID

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/721

**Comment by freddyucv** [comment]
**Needs Work**: When you search by a Blog content in the default language you get two page: the detail page and the 'blog/index' page, but when you do a search in spanish to the same content you don't get the 'blog/index' page

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18266

**Comment by freddyucv** [comment]
**Needs Work**: new bug

1. Create a new language.
2. Create a Blog content in the new language.
3. Run the site serach with the new language.
4. Search by the new content, you get just the blog/index page, you don't get the blog detail page.

**Comment by dsilvam** [comment]
Case commented above is working

**Comment by freddyucv** [comment]
**Passed Internal QA** : with the language English, spanish and italian

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
