### ISSUE TITLE
Workflows Select Box not loading data after first onChange event in 5.2.5 and higher

### ISSUE THREAD

**Issue by jasontt33** [dotCMS/core#18137]
Found when working on customer upgrade.
Reproducible in dotCMS 5.2.5, and latest master.

 here is how I reproduce in Chrome and FF
log in > go to Content > search > Click Advanced > view workflows > select one > then go to another menu item in dotcms e.g. System Config > browse back to Content Search > Click on drop down in Workflows select box = no items visible.....

![image](https://user-images.githubusercontent.com/44835521/76658974-aeede400-654b-11ea-8653-0229fe39c98e.png)

**Comment by erickgonzalez** [comment]
Not able to reproduce in the latest master. The select box of Workflows always shows values regardless if you navigate back and forth.

https://www.screencast.com/t/pT6ZRXa0jHur

**Comment by fmontes** [comment]
@jasontt33 We can't reproduce in demo and/or master, can you check in demo?
