### ISSUE TITLE
Adding Text Field with numeric data type does not save

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18147]
If you add a text field and select "whole number" or float, it will save the data type as "text"

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18162/files)

**Comment by bryanboza** [comment]
Now this is working as expected but we need some work here: 
- If you add a incorrect value we are not validating until the second character, we need validate with the first character 
- If you type an incorrect value and try to save we are printing too many lines to a simple error, we need to catch the exception and print just a line error 
ST: https://gist.github.com/bryanboza/c72b343c3ffe1a984dc79fcf3a2939db

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.8 // Postgres // FF
