### ISSUE TITLE
Angular porlets do not update when host selector is changed

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18148]
We are not refreshing the angular portlets when you switch between sites, then we don't have a way  to know which rule is of which site.

Originally posted by @bryanboza in #17937 (comment)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1326

**Comment by nollymar** [comment]
**Needs work:** Content Types portlet and Forms portlet have the same issue. The page doesn't refresh when the site is changed

<img width="1680" alt="Screen Shot 2020-05-18 at 2 00 07 PM" src="https://user-images.githubusercontent.com/8741395/82249891-2f481100-9910-11ea-9cb1-c1f980c0dde7.png">

**Comment by bryanboza** [comment]
Fixed, new card reported in the #18565
