### ISSUE TITLE
Wrong error message display in My Account modal

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#18143]
When displaying an error message we are expanding the window instead to show a multi line error.

![image](https://user-images.githubusercontent.com/2641437/76786735-51d97480-677d-11ea-9d25-fbb05cd447a3.png)

Related to: https://github.com/dotCMS/core/issues/18093

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1288

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.8 // Postgres // FF
