### ISSUE TITLE
[ES] : Reindex is parsing some text fields as date fields

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18154]
Reported via Support: [100611](https://dotcms.zendesk.com/agent/tickets/100611)
Reproducible in dotCMS 5.2.6

A full ES Reindex is trying to parse some `text` fields in some Content Types as `date` fields. This is causing WARN messages in the logs such as the following:
```
bulk index failure:MapperParsingException[failed to parse [contentTypeName.enddate]]; nested: IllegalArgumentException[Invalid format: "until further notice"];
```
And causes the reindex to never reach 100%.

### Steps to reproduce the behavior:
1. Ask @jcastro-dotcms for more details on how to set up your data.
2. Kick off a full reindex and what the logs for those kinds of messages.

### Expected behavior
The ES engine should not try to parse simple text fields as date fields.

### Additional context
As discussed with @dsilvam this seems to be related to the system finding two fields with the same name but different data type. So, if the first fields the reindex finds is of type `date`, then another field with the very same name but different data type will be treated as `date` as well.

### Current Workaround
For each field of type `text` that is being treated as `date`, add the following field variable:
- Key = `esCustomMapping`
- Value = `{"type": "text"}`

## Acceptance Criteria

1. Multilanguage
2. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18186

**Comment by wezell** [comment]
dupe:  #18689
