### ISSUE TITLE
When elasticsearch is not available:   page in cache not work

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18153]
It should work but you get the follow error 

https://gist.github.com/freddyucv/f0a48eb362650239dc90fd751907bfdb

If you try to get the page in the Front end you get a 404 HTTP error

**Comment by freddyucv** [comment]
PR https://github.com/dotCMS/core/pull/18225

**Comment by freddyucv** [comment]
**Note to  QA**: The follow case are out of this issue scope:

- The form are not getting render with elasticsearch down after this change, it is a issue for this specific case:

https://github.com/dotCMS/core#workspaces/core-56e1874dff575723435b8c80/board?milestones=Bug%20Sprint%23&filterLogic=any&repos=3729629

- If a widget do a content pull is not getting render after this change either

**Comment by dsilvam** [comment]
**Passed Internal QA**: Pages displaying instead of a 404 when there is no pull from the index.

**Comment by bryanboza** [comment]
Fixed, working as expected for now. 

New cards created to continue this work in the next version. (#18403)
