### ISSUE TITLE
Sort list by empty column show no results and get stuck

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18157]
### Describe the bug
When you have a field not required and show in list and all the contentlets of that content type have that field empty, if you sort by that column it shows not results

### Steps to reproduce the behavior:
https://monosnap.com/file/nTCUfybEb2aXs335w940l3BBCEkmt5

## Acceptance Criteria

1. It should not sort at all
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
dupe: #18159

**Comment by wezell** [comment]
Show on List order is wrong
