### ISSUE TITLE
Content search columns

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18159]
### Describe the bug
The columns are not showing correctly and/or in the right order.

### Steps to reproduce the behavior:
1. Create a content type and add some fields with "show in list"
2. Go to content search
3. The columns that show in field order is not right

### Expected behavior
1. The same order of the fields in content type should reflect in the content search
2. When you have "All" selected we show "Type" column

### Screenshots

When to show the "Type column"
![Screen Shot 2020-03-19 at 10 19 01](https://user-images.githubusercontent.com/751424/77089264-39f73000-69cb-11ea-890f-16b32ce0e1a1.png)

The columns order should be the same as the order of the fields in the content type
![Screen Shot 2020-03-19 at 10 21 30](https://user-images.githubusercontent.com/751424/77089606-a7a35c00-69cb-11ea-961f-7a357c53ea28.png)

## Acceptance Criteria

1. Add the type column when "All" is selected
2. Show the right order of the columns 
3. Work in all the supported browsers (don't forget IE11 and iPad)
4. Multilanguage
5. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on relesase-5.2.8 // Postgres // FF
