### ISSUE TITLE
Usability: Problems with the clickable area on content search 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18155]
Related to #17981 

We have problems with the clickable area, just one column is clickable in case you need to edit a piece of content this from content search, we need to be able to click on the whole line. Also in some cases, the clickable item is not required as in "Products" then you don't have an area to click. 

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to Content --> Products 
3. Try to edit one of the first items

### Expected behavior
We should be able to click in the whole line in order to edit 

### Screenshots
![image](https://user-images.githubusercontent.com/2641437/77008757-627c1d00-692c-11ea-8428-172655ed03c5.png)

### Desktop (please complete the following information):
 Tested on release-5.2.8 // Postgres. // FF

**Comment by wezell** [comment]
dupe: #18159
