### ISSUE TITLE
Searchable radio field causes a javascript error when relating content

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#18152]
Reported via Support: [Zendesk-100744](https://dotcms.zendesk.com/agent/tickets/100744)
Reproducible in dotCMS 5.2.7

If a content type has 2 relationship fields for the same parent content type, both relationship fields will use similar dialogs to relate content for every field. If the parent content type has a searchable radio field, it will cause a javascript error because the widget id for the radio field search field is already registered.

### Steps to reproduce the behavior:
1. Create a new parent content type, for example "Blog Entry"
2. Add a radio field to the parent content type and mark it as "User Searchable"
3. Create a child content type, for example "Featured Blogs"
4. Add a relationship field to the child content type, pointing to the parent content type (for example, the field can be called "BlogEntry1")
5. Add another relationship field to the child content type, pointing to the parent content type (for example, the field can be called "BlogEntry2")
6. Create a couple of content items for the parent type, for example: Entry1, Entry2
7. Create a new content item of the child content type
8. This javascript error is shown at the browser console:
```
build.js?b=5.2.7:2 dojo/parser::parse() error Error: Tried to register widget with id==.noFollowField-R1584528486260 but that id is already registered
    at Object.add (VM579 build.js:2)
    at Object.create (VM579 build.js:2)
    at Object._19a (VM574 dojo.js:2)
    at Object.create (VM579 build.js:2)
    at Object.postscript (VM579 build.js:2)
    at new <anonymous> (VM574 dojo.js:2)
    at Object.construct (VM579 build.js:2)
    at Object.<anonymous> (VM579 build.js:2)
    at Object.map (VM574 dojo.js:2)
    at Object._instantiate (VM579 build.js:2)
```

### Expected behavior
Having a searchable radio field shouldn't cause javascript errors when the content type is used in 2 different relationship fields for the same child content type. Every searchable field should use a unique widget id.

### Screenshots
Parent content type includes a searchable radio field:
![image](https://user-images.githubusercontent.com/2894221/76955903-acd3ae80-68d8-11ea-9ad4-ee13db8f24be.png)

Child content type has 2 relationship fields pointing to the parent content type:
![image](https://user-images.githubusercontent.com/2894221/76955933-b826da00-68d8-11ea-90d9-b5e0ab2ea77c.png)

### Additional context
This has been reported by customer via Support: Ticket [100744](https://dotcms.zendesk.com/agent/tickets/100744).

**Comment by fmontes** [comment]
This commit https://github.com/dotCMS/support/commit/40da494c9446acc025f966bfa81e6e2092e050fe give me another errors in the same widget, working on those.

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/issues/18152

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
