### ISSUE TITLE
com.fasterxml.jackson.core contains vulnerabilities

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#18151]
The dependency com.fasterxml.jackson.core (https://github.com/dotCMS/core/blob/master/dotCMS/dependencies.gradle#L65) contains vulnerabilities and it would be best to upgrade to the latest version, which is 2.10.3 > https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

Also in general it would be good if dotCMS could update their (external) dependencies on a more regular basis as using components with known vulnerabilities is one of the biggest security risks and also listed in the OWASP Top 10: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A9-Using_Components_with_Known_Vulnerabilities

**Comment by wezell** [comment]
We should un-repackage jackson as well.

**Comment by victoralfaro-dotcms** [comment]
@wezell, what about the other `jackson` related dependencies like `jackson-annotations`,` jackson-databind` and other that we repackage as well?

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18864

**Comment by wezell** [comment]
Any customers that are using the repackaged versions of jackson, they will need to change these to use the un-repackaged versions, e.g. like this code change:

https://github.com/dotCMS/core/pull/18864/files#diff-fb89ba3645e6bb0ed0f78d19645f5cffL6
