### ISSUE TITLE
Initial licensed startup of node in cluster doesn't launch hazelcast

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18169]
### Describe the bug
Starting up a node with a cluster license in place in dotsecure/license does not result in hazelcast starting up until the node is restarted, causing issues with autoscaling and with additional nodes joining the cluster (the second node will start it's own hazelcast, other nodes will join it but node one will not).

### Steps to reproduce the behavior:
1.  place license in dotsecure/license folder
2. start instance
3. go to network portlet, no content
4. go to environment portlet, no hazelcast entry
5. restart dotCMS
6. go to network portlet, displays proper content
7. go to environment portlet, hazelcast entry is present

 - Version 5.2.7

**Comment by wezell** [comment]
@notmattmonroe thanks for the report.  This is fixed in the upcoming version 5.2.8.  You can see the issue and the fix here: #18050 .  I am closing this for now.
