### ISSUE TITLE
Reorder fields in related content search popup

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18176]
1. Search should be on top of other search criteria AND also receive focus
2. Languages should be under the search and look like this `language name (CountryCode)` 

![Screen Shot 2020-03-17 at 4 34 11 PM](https://user-images.githubusercontent.com/934364/76899046-36e62d80-686d-11ea-8f88-c225a318021b.png)

**Comment by hmoreras** [comment]
this was done here, https://github.com/dotCMS/core/commit/29966fec5f5de8313068bf6d7730872e4b0ed16c

**Comment by bryanboza** [comment]
According to the point #2 we need some reorder here:
SC: https://www.screencast.com/t/QPI5p1w2RVh

**Comment by bryanboza** [comment]
We still with problems here, according the requested in the card description, the "search" field should be at the top of the list and the focus should be on this one, right now the focus in on language and the search is the last one in the list: 
https://www.screencast.com/t/cfKqaubxhFhJ

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
