### ISSUE TITLE
Title not included in indexed metadata fields, but should be

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18172]
### Describe the bug

The `INDEX_METADATA_FIELDS` property in the dotmarketing-config.properties file specified which metadata fields we index in files.  The current default value for this property does not include `title`, so the title of uploaded files is not indexed by default.

### Steps to reproduce the behavior:
1. Create a file (outside of dotCMS) and set the `title` field in the file metadata to include some unique value (e.g. `abc123xyz`).
2. Upload the file into dotCMS as a File Asset.
3. Use the Query Tool to perform a Lucene query which looks for the unique value (e.g. `+catchall:*abc123xyz*`.
Result: The file is not returned in the search results.

### Expected behavior

By default, the title metadata should be indexed.

So we should add `title` to the list of fields in the `INDEX_METADATA_FIELDS` property in the dotmarketing-config.properties file we ship with.

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Chrome
 - dotCMS 5.2.7

### Workaround

Customers may use the com.dotcms.config plugin to override the value of the `INDEX_METADATA_FIELDS` property, adding the title field to the list of indexed properties.

**Comment by john-thomas-dotcms** [comment]
https://github.com/dotCMS/core/pull/18173/files

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
