### ISSUE TITLE
Vanity url icon wrong in listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18189]
### Describe the bug
Vanity url icon not matching in the listing

![image (1)](https://user-images.githubusercontent.com/751424/77571973-d326ba80-6e93-11ea-84d8-4ac098d9bfcf.png)

## Acceptance Criteria

1. Match the icon
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
I was no able to reproduce, with the lates in master
![image](https://user-images.githubusercontent.com/37185433/82388608-3dbd2800-99f7-11ea-96ed-fb43ae9bad91.png)

**Comment by alfredo-dotcms** [comment]
This also was tested by montes and it was not reproducible

**Comment by bryanboza** [comment]
Fixed, tested on master and I'm unable to reproduce
