### ISSUE TITLE
Get error when try to open page's properties with a limit user

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18188]
### Describe the bug
When you try to get the page's properties with a limit user you get a error 

### Steps to reproduce the behavior:
1. Create a new role, and add view permission for all in demo.dotcms.com site, and edit to page, also add Site in the Tools tab.
2. Create a new user and add the new role
3. Login As with the new user
4. Go to site-browser and try to open any page's properties

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/57981b14-c11e-44c1-9f39-d6d67e01849c

### Expected behavior
Should show the page's properties

**Comment by hmoreras** [comment]
Can't reproduce in current master.

**Comment by bryanboza** [comment]
Able to reproduce in the release branch
![image](https://user-images.githubusercontent.com/2641437/112187321-9d600300-8bc7-11eb-90b8-e796a7cbb257.png)

**Comment by nollymar** [comment]
Dupe of https://github.com/dotCMS/core/issues/20156
