### ISSUE TITLE
Menu with only "Logout as" showing for admin user

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18182]
Instead of the correct menu for admin user. 

Steps to reproduce: 
1. Log in using Admin.
2. Log in as any limited user
3 .Logout as limited user and back to Admin

The only option available after the steps is "Logout as" even for Admin, which leaves the Admin user unable to "login as" anymore or even logout from the backend.

**Comment by hmoreras** [comment]
the service, `api/v1/authentication/logInUser` is not cleaning the `loginAsUser` when logout.

**Comment by wezell** [comment]
On the logout As, we need to remove the `WebKeys.User` from the session AND the `WebKeys.User_ID`

**Comment by fmontes** [comment]
We need to check in 5.2.8

**Comment by hmoreras** [comment]
this is correct in 5.2.8

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18219

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // Password. Unable to reproduce after the last changes
