### ISSUE TITLE
Ship with Empty Starter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18185]
In 5.3.0, we need to ship dotCMS with the empty starter by default.  

I do not think we need to also ship with the demo site starter.zip in our distro - it is too fat.  We should provide directions on how the demo starter can be downloaded and installed if it is desired.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18337

**Comment by freddyucv** [comment]
**needs doc**: we have to change this doc:

https://dotcms.com/docs/latest/deploying-a-custom-starter-site

The full starter can be download here (I think it is the last full starter version)

http://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20200219/starter-20200219.zip

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18439
