### ISSUE TITLE
Improvement validating data on content editing 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18192]
- If you add a incorrect value we are not validating until the second character, we need validate with the first character 

SC1: https://www.screencast.com/t/8A9gQEckI2
SC2: https://www.screencast.com/t/aJIuLXHPot

### To Reproduce: 
- Login as admin
- Crete a new content type 
- Add a text field (whole number)
- Try to add a new piece of content 

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18147#issuecomment-604109596_

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/18212

**Comment by bryanboza** [comment]
We have a problem with the regex expression here, since this is a "whole number", we should not accept decimals, but we are not validating the "." as invalid character, then we need to wait until you click the save button to see the error. We need to show the invalid data validation in the moment that you add this character to the field.

**Comment by hmoreras** [comment]
feedback PR: https://github.com/dotCMS/core/pull/18423

**Comment by dsilvam** [comment]
Passed Internal QA: Validating taking place since the first typed char.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
