### ISSUE TITLE
Unable to add new content to pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18198]
After some recent change now we are unable to add NEW pieces of content to a page, when you are in a edit page and try to add a new content in the content modal we lost completely the "+" button, then we are unable to add a piece of content, this in any content type. 

FYI: this is not a permissions problem since I'm testing with admin user 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page 
3. Try to add a new piece of content of any type 

### Expected behavior
We need be able to add new content to pages without problems 

### Screenshots
SC: https://www.screencast.com/t/5I30M9IMbH

### Desktop (please complete the following information):
Tested on release-5.2.8 // Postgres // FF

**Comment by hmoreras** [comment]
PR:  https://github.com/dotCMS/core/pull/18196

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.8 // Postgres // FF
