### ISSUE TITLE
HTMLPages: Site Search not indexing all versions of mult-lang content in HTMLPages

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18207]
### Content not found
1. Create a new Rich text content en english and spanish:
  **English:** 
  Title: Hello content
  Body: Hi, my name is Vlad Tepes (evil laugh)
  **Spanish:** 
  Title: Hola content
  Body: Hola, mi nombre es Juana de Arco

2. Create a new folder "folder1"
3. Create a page **just** in English "page1" and add the created rich content to the page

4. ` Dev Tools -> Site Search -> Job Scheduler`
Run now (But is the same result for incremental and no incremental scheduled jobs) selecting both languages

5. `Dev Tools -> Site Search -> Search `
Look for "vlad" -> **Nothing is found**
Look for "juana" -> **Page is found**

**NOTE:** Having a version of the page in spanish and english the search looks right, when the page is just in english I see this behavior.

**Comment by dsilvam** [comment]
FIxed by these:
PR core: #18205
PR ee: dotCMS/enterprise-2.x#721

**Comment by freddyucv** [comment]
**Passed Internal QA** : with the language English, spanish and italian

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
