### ISSUE TITLE
ContentletPostHook and ContentletPreHooks not working at least since dotCMS dotCMS 5.1.6

### ISSUE THREAD

**Issue by bartplasmans** [dotCMS/core#18200]
### Describe the bug
we noticed that at least since dotCMS 5.1.6 the contentlet post and prehooks are not beeing triggered anymore.

### Steps to reproduce the behavior:
We are using the code supplied by dotCMS in the example plugins and documentation:

https://dotcms.com/docs/latest/content-hook-contentapi-interceptor-plugin

https://github.com/dotCMS/plugin-seeds/blob/master/OSGi/com.dotcms.hooks/src/main/java/com/dotmarketing/osgi/hooks/SamplePostContentHook.java

This is an example class we use:
its registered through the call " GenericBundleActivator.addPostHook(ContentletPostHook.newInstance())"

public class ContentletPostHook extends ContentletAPIPostHookAbstractImp {

 @Override
       public void checkin(Contentlet contentlet, List<Category> cats, List<Permission> permissions, User user, boolean respectFrontendRoles, Contentlet returnValue) {
              handleContentlet(contentlet);
       }

       @Override
       public void checkin(Contentlet contentlet, List<Permission> permissions, User user, boolean respectFrontendRoles, Contentlet returnValue) {
              handleContentlet(contentlet);
       }

       @Override
       public void checkin(Contentlet contentlet,
              Map<Relationship, List<Contentlet>> contentRelationships, List<Category> cats, List<Permission> permissions, User user, boolean respectFrontendRoles, Contentlet returnValue) {
             handleContentlet(contentlet);
       }

       @Override
       public void checkin(Contentlet contentlet, Map<Relationship, List<Contentlet>> contentRelationships, List<Category> cats, User user, boolean respectFrontendRoles, Contentlet returnValue) {
              handleContentlet(contentlet);
       }

      @Override
       public void checkin(Contentlet contentlet, Map<Relationship, List<Contentlet>> contentRelationships,
              User user, boolean respectFrontendRoles, Contentlet returnValue) {
              handleContentlet(contentlet);
       }

        @Override
       public void checkin(Contentlet contentlet, User user, boolean respectFrontendRoles, Contentlet returnValue) {
              handleContentlet(contentlet);
       }
 
       @Override
       public void checkin(Contentlet contentlet, User user, boolean respectFrontendRoles, List<Category> cats, Contentlet returnValue) {
              handleContentlet(contentlet);
       }

       @Override
       public void checkin(Contentlet currentContentlet, ContentletRelationships relationshipsData, List<Category> cats,
              List<Permission> selectedPermissions, User user, boolean respectFrontendRoles, Contentlet returnValue) {              
handleContentlet(currentContentlet);
       }

private void handleContentlet(Contentlet contentlet) {
           Logger.info(this.getClass(), "handleContentlet : " + contentlet.getContentType().name());
              ….. more lines
}

Were not seeing anything beeing printed in the last function, while in older versions this was working, we used this to update certain content in a custom cache.

### Expected behavior
We should see the logger.info line printed

### Desktop (please complete the following information):
- not applicable

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
Maybe the code path has changed?  I can confirm pre and post are working - at least when saving via the ui -  using the example from our plugin-seeds: https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.hooks:

The method I overrode was:

```
checkin(final Contentlet contentlet, final ContentletDependencies contentletDependencies) {
```

```
09:28:36.877  INFO  hooks.SamplePreContentHook - +++++++++++++++++++++++++++++++++++++++++++++++
09:28:36.877  INFO  hooks.SamplePreContentHook - INSIDE checkin(final Contentlet contentlet,  final ContentletDependencies contentletDependencies)
09:28:36.877  INFO  hooks.SamplePreContentHook - +++++++++++++++++++++++++++++++++++++++++++++++
09:28:36.877  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: demo.dotcms.com : Saving Content , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier: 5b3d20ac-7edf-43e0-823c-61084bca0dfe
09:28:36.912  INFO  reindex.ReindexQueueAPIImpl - addIdentifierReindex: 5b3d20ac-7edf-43e0-823c-61084bca0dfe
09:28:37.016  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: demo.dotcms.com : Content Saved , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier: 5b3d20ac-7edf-43e0-823c-61084bca0dfe
09:28:37.016  INFO  hooks.SamplePostContentHook - +++++++++++++++++++++++++++++++++++++++++++++++
09:28:37.016  INFO  hooks.SamplePostContentHook - INSIDE POSTHOOK checkin(final Contentlet contentlet,  final ContentletDependencies contentletDependencies)
09:28:37.016  INFO  hooks.SamplePostContentHook - +++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by wezell** [comment]
I can reopen this if you can share the code path which is not calling the pre and post hooks.

**Comment by bartplasmans** [comment]
Hi Will,

we found the issue, there was a new checkin methods added which was used by the dotCMS admin on the ContentletAPIPostHook and ContentletAPIPreHook

the added method on the ContentletAPIPostHook is:

public default void checkin(Contentlet contentlet, ContentletDependencies contentletDependencies, Contentlet c) {}

The added method on the  ContentletAPIPreHook is:

       default boolean checkin(Contentlet contentlet, ContentletDependencies contentletDependencies) {

		return true;
	}
	
When we added these methods to our Posthook and Prehook implementations it was triggered again.

greetings Bart
