### ISSUE TITLE
Can't Give New Users Permissions on Folders

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#18208]
Tested on 5.2.7

1) To duplicate, first create a new user (do not use an existing demo user).  Give that user full cms admin permissions:

<img width="1108" alt="Screen Shot 2020-03-27 at 9 04 09 PM" src="https://user-images.githubusercontent.com/1569167/77813485-9d89f900-706e-11ea-8f94-0ab5be5a7442.png">

2) create a new folder and then edit permissions on that folder, and try to add the NEW user and give it permissions to the folder.  The bug is that you can't add the user to the folder permissions.

![Screen Shot 2020-03-27 at 9 07 18 PM](https://user-images.githubusercontent.com/1569167/77813534-01142680-706f-11ea-8624-c8a259cb0df5.png)

We should create a unit test for this.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19732/files

**Comment by nollymar** [comment]
Passed internal QA: 

![Screen Shot 2020-12-29 at 5 12 59 PM](https://user-images.githubusercontent.com/8741395/103317437-2583a180-49f9-11eb-88f4-910fa288e010.png)

**Comment by bryanboza** [comment]
Fixed, able to assign permissions with new user to folders without problems 
![image](https://user-images.githubusercontent.com/2641437/104351440-042bb680-54cb-11eb-8ec4-8a32a567a9ab.png)
