### ISSUE TITLE
Stealing lock by clicking Edit tab on locked page does not unlock the page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18204]
If you edit a page that is locked by another user, and hit edit and have permissions, you are given the choice to "steal the lock".  If you click "Accept", the page gets reset into preview mode and the lock never gets stolen.

Try this on the costa rica page as admin@dotcms.com

![lock-no-workee](https://user-images.githubusercontent.com/934364/77792278-7a475580-703e-11ea-8e7d-86eb59438a79.gif)

**Comment by erickgonzalez** [comment]
Tested this against the latest master and can not reproduce. The lock is stolen and the page view stays at Edit Mode.

**Comment by wezell** [comment]
When the page is locked, you need to hit the "Edit Tab" and not the "unlock" switch.

**Comment by erickgonzalez** [comment]
@wezell  Yes, I tested the same steps that you did on the video

**Comment by erickgonzalez** [comment]
![Screen-Recording-2020-03-30-at-1](https://user-images.githubusercontent.com/5278970/77942082-5ff8bc00-7278-11ea-830b-09f1c4f4b5a1.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1394

**Comment by dsilvam** [comment]
Passed Internal QA: Able to steal lock by clicking on Edit tab and able to make changes.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the release-5.3.7 branch after the last changes
