### ISSUE TITLE
Search and replace utility removes non latin characters for MSSQL

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#18209]
Reported via Support: Ticket [100690](https://dotcms.zendesk.com/agent/tickets/100690)
Reproducible in dotCMS 5.2.7

The search and replace utility causes non latin characters being replaced by invalid characters on MS SQL Server.

### Steps to reproduce the behavior:
1. Set up a 5.2.7 dotCMS instance running on MS SQL Server.
2. Create a new contentlet from the 'Rich Text' content type, containing non latin characters. For example, include these letter from the Russian alphabet: (ижф)
3. Go to 'Control Panel -> Maintenance' portlet, to Tools tab, and then run 'Search And Replace Utility' using any text on the 'String to find' and 'Replace with' fields.
4. Go to edit the contentlet with non latin characters.
5. The non latin characters have been replaced by invalid characters that show as: (???)

### Expected behavior
Search And Replace Utility should work for text containing non latin characters.

### Screenshots
Contentlet containing non-latin characters:
![image](https://user-images.githubusercontent.com/2894221/77824279-1f0d7580-70c7-11ea-9f0b-d1ad8860c4ce.png)

Invalid characters after running 'Search and replace' utility:
![image](https://user-images.githubusercontent.com/2894221/77824288-38162680-70c7-11ea-85dc-321a244227d9.png)

### Additional context
This has been reported by customer via Support: Ticket [100690](https://dotcms.zendesk.com/agent/tickets/100690)

**Comment by dsilvam** [comment]
**Passed Internal QA:** non-latin characters remained after running Search and Replace

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
