### ISSUE TITLE
UI: Edit mode broke in medium size screens

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18203]
### Describe the bug
The toolbar of edit mode is broken in medium size screen

![Screen Shot 2020-03-27 at 2 46 26 PM](https://user-images.githubusercontent.com/751424/77790973-5f1f1a80-702b-11ea-8071-aadfe1b8569d.png)

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
- Previewing label must be placed above the device view
- Lock icon must be positioned next to the CANCEL button
- Language and Device dropdown should hide labels when viewport is narrow

![image](https://user-images.githubusercontent.com/37185433/82936163-68553680-9f4b-11ea-9206-2f6951c3ae7d.png)

**Comment by alfredo-dotcms** [comment]
`core-web` working branch: issue-18203-UI-Edit-Mode-Broken-On-Tablet

**Comment by alfredo-dotcms** [comment]
changes so far:

![image](https://user-images.githubusercontent.com/37185433/88431047-cb7e1080-cdb6-11ea-9e9a-13465e49882d.png)

**Comment by fmontes** [comment]
![Untitled-3](https://user-images.githubusercontent.com/751424/88584558-08dcdb00-d00f-11ea-9fa2-f394535c0180.png)

1. Move "Save" message to a toast
2. Lang, device and persona all collapsed and tooltip to show the selected option
3. Lock switch message "locker by..." into a tooltip.
4. Remove the message of "Phone - 414 x 731

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1391

**Comment by dsilvam** [comment]
Passed Internal QA: 
These four items working as expected
1. Move "Save" message to a toast
2. Lang, device and persona all collapsed and tooltip to show the selected option
3. Lock switch message "locker by..." into a tooltip.
4. Remove the message of "Phone - 414 x 731

**Comment by bryanboza** [comment]
We need some work here: 

If the display is smaller than the device size, we need add some scroll here in order to allow see the complete screen
![image](https://user-images.githubusercontent.com/2641437/90298392-61a1d580-de4f-11ea-995b-cd1d4045d8c0.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1414

**Comment by ivorpad** [comment]
PR: https://github.com/dotCMS/core-web/pull/1424

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
