### ISSUE TITLE
Spaces in File Assets are replaced with "+" instead of "%20" 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#18214]
Reported via Support: [101269](https://dotcms.zendesk.com/agent/tickets/101269)
Reproducible in **ALL dotCMS VERSIONS** lower than 5.3.0.

dotCMS is replacing spaces in File Assets with a plus sign instead of %20.

If you upload a file asset with spaces in the filename, dotCMS is placing **+** in the generated filename instead leaving it a space or using **%20**. 

The actual filename works, just not what dotCMS generates for you.

### Steps to reproduce the behavior:
1. Upload a file with spaces in the filename. (in this example "abc 128 - original.png")
2. Open the File Asset
3. The Resource Link lists the file as `/abc 128 - original.png?language_id=1`
4. Mouseover the Resource Link. The link address is `https://demo.dotcms.com/abc+128+-+original.png?language_id=1` 

![image](https://user-images.githubusercontent.com/49727631/78034536-7d3b9200-732d-11ea-84b9-14971c4c3390.png)

### Expected behavior
Clicking the Resource Link should display the File Asset. 

### Actual behavior
404
![image](https://user-images.githubusercontent.com/49727631/78034501-6e54df80-732d-11ea-8f05-b8e63cff7b82.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser: Chrome /FF

**Comment by jcastro-dotcms** [comment]
The fix for this issue was included as part of another ticket: https://github.com/dotCMS/core/commit/533d6512219bfc93e53eb2cda7c828ac99b62880#diff-05e32bedcf64b74811872e9e6a67a74a

**Comment by jcastro-dotcms** [comment]
Also reported by customer: [100859](https://dotcms.zendesk.com/agent/tickets/100859)
