### ISSUE TITLE
Allow local/private access to status API

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18215]
Containers require a probe that can query the status of dotCMS and restart the node if that status is unreachable or is bad.  We have an endpoint that allows for this, e.g:
`/api/v1/system-status` and 
`/api/v1/system-status?extended`

But by default it only allows access from localhost -we should enable it from all private networks so containers can be checked remotely.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18228

**Comment by dsilvam** [comment]
Passed Internal QA: This is working.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.0 // Postgres // FF and now works as expected
