### ISSUE TITLE
Apps UI: Integrate Dot-Field-Variables component into DotApps to support extra properties

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18216]
Depending of the configuration of the service an option to add more properties could be present, so we need to add the ability to add extra properties, those properties are per selected host and the new properties will have the same types of the existing form values (text fields, checkboxes and files).

Some UI requirements: 

- [x] The section should be called "Custom Properties"
- [x] Use a toggle button to enable/disable hidden fields 
- [x] When a hidden variable is added the "value" will be shown in stars
- [x] A hidden variable once added is not editable in any way, you can only *delete* it
- [x] An existing variable can be changed to hidden
- [x] the hidden value can not be seen, even if you *inspect it* on the browser's dev plugin

**Comment by alfredo-dotcms** [comment]
PR: issue-18216-Integrate-DotKeyValue-into-DotApps

**Comment by nollymar** [comment]
I have found an issue: if I mark an existing field as hidden, a new row is created with **the same key** and ***** as values. The right behavior should be to modify the current row

**Comment by alfredo-dotcms** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1319

**Comment by nollymar** [comment]
Passed internal qa
