### ISSUE TITLE
Apps - Backend: Add ability to read secrets from code

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18217]
We need to be able to read secrets from code, most of the reads initially will come from code, like ~viewtools~ and workflow actiontlets, we need a method to read specific keys for a service and host, we already have a getSecrets that may work but a method to request individual keys is still required. But the most important requirement here (#17682) is that when the method is accessed directly for now we won't validate permissions, the current getSecrets implementation is closed to admins and users with the Services portlet enabled.

**Comment by nollymar** [comment]
Examples that show how to get secrets from a host:

```
$apps.getKey("google-translate", "apiKey")
$apps.getKey("$hostId", "google-translate", "apiKey")
``` 
Get the current host (based on the HostWebApi). If no value is found, then we fall back to SYSTEM_HOST

**Comment by wezell** [comment]
done
