### ISSUE TITLE
Text field "number" validation is not validating decimal

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18235]
### Describe the bug
If you create a text field and in "Data type" you select "Whole number" and the when you create a contentlet of this type is not validating correctly.

### Steps to reproduce the behavior:
1. Create a content with a text field and in data type select "Whole number"
2. Create a contentlet and in the field add the value decimal like: "0.1"
3. See there is no error there, it should show an error

## Acceptance Criteria

1. Validate number and decimal correctly
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/103671878-252b5f00-4f41-11eb-8f55-17254fa1eefe.png)

not able to reproduce

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
