### ISSUE TITLE
Apps: Move Google Translation Service to apps

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18233]
Doc: https://dotcms.com/docs/latest/translate-content-sub-action

Put the logo in our static S3 bucket.

It should still respect putting the key in the `dotmarketing-config.properties` file.

**Comment by fmontes** [comment]
There is a PR for this: https://github.com/dotCMS/core/pull/18323

**Comment by erickgonzalez** [comment]
**Note to Doc:**

We need to update the images of the doc because there are really old and also we need add to the doc that you can configure the `API_KEY` via apps.

**Comment by ivorpad** [comment]
1. Tested with a wrong API Key and got an Error: "Error executing Translation Actionlet"

<img width="446" alt="Screen Shot 2020-08-18 at 6 48 10 PM" src="https://user-images.githubusercontent.com/52452/90543371-e3fb0400-e185-11ea-984b-4058fe724193.png">

2. Tested 5 languages: Spanish, Japanese, Dutch, Italian, Danish and received their respective translations.

<img width="1485" alt="Screen Shot 2020-08-18 at 7 07 43 PM" src="https://user-images.githubusercontent.com/52452/90543527-1efd3780-e186-11ea-8464-26829724ad69.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF. New card related to the translation service created here #19131
