### ISSUE TITLE
Apps - Backend: Configurations added to SYSTEM_HOST are counted twice.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#18242]
### Describe the bug
Adding an individual configuration for the site (SYSTEM_HOST) under any app-key always results in 2 configurations counted.

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18244

**Comment by nollymar** [comment]
Passed internal qa
