### ISSUE TITLE
Can't use a content type with a quote in its name

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#18241]
### Describe the bug
When you have a content type/structure with a single quote in its name ten dotCMS starts to function incorrectly. The content will not be displayed any more in a container and you can't add content to a container which handles that type. The add/edit content window will be empty.

### Steps to reproduce the behavior:
1. Go to demo.dotcms.com (5.2.7, it also happens in 5.2.6)
2. Open the homepage and select the edit mode
3. Click on the "+" of the container containing "Snowmobiling" and click on Content. 
You will see a popup with a list of content (I chose this container since it has the option to add "Rich Text")

4. Open the content type "Rich Text"
5. Edit the content type and set the name to "Rich's Text"
6. Open the homepage and select the edit mode
7. Click on the "+" of the container containing "Snowmobiling" and click on Content
You will now see an empty popup (See the screenshot below) 

![image](https://user-images.githubusercontent.com/2195163/78150655-e4456d80-7437-11ea-8324-7549131dea02.png)

### Expected behavior
The system should be able to handle a special character in a content type name. 

### Workaround
Remove all ' from all your content type names. I haven't tested it with a " yet but I can imagine that this could also cause issues.

### Extra remark
I've noticed an extra issue in my 5.2.6 instance. Containers that contained a widget with a quote in its name were not displaying content any more. This was both on the front-end and in the dotCMS back-end. If you are fixing this issue please also look in other places for possible escaping issues regarding the content type name.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19687/files

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to use the content types even when have quotes in their names.
