### ISSUE TITLE
MonitorResource consumes too many resources

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18245]
In a production environment, the MonitorResource should be as light weight as possible and consume too many resources.

We have a large production environment where the status checks performed by the MonitorResource are consuming up to 10% of the total app resources, specifically the DB check.  The DB check runs an unbounded count on the contentlet table and that performs a full table scan in order to return the value.  See image below from a production site that is using the `/api/v1/system-status` endpoint

![Screen Shot 2020-04-01 at 5 52 39 PM](https://user-images.githubusercontent.com/934364/78190394-ed3b3c80-7441-11ea-9058-b51bff21dffe.png)

**Comment by wezell** [comment]
PR: #18247

**Comment by dsilvam** [comment]
Passed Internal QA: Profiler not showing bottlenecks in the db check

<img width="1549" alt="Screen Shot 2020-04-14 at 5 22 43 PM" src="https://user-images.githubusercontent.com/1576794/79279854-976c8880-7e74-11ea-8c99-91761f8fc89a.png">
