### ISSUE TITLE
Apps - UI: Refactor Dot-Field-Variables component

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18249]
Changes include: 

- [x] Remove the '+' button. 
- [x] A row with empty fields should be always shown by default to allow users add new properties without clicking a '+' button
- [x] When a user is editing a row, two buttons should appear: Cancel and Save
- [x] If a user clicks on Save, a new empty row will be created above
- [x] Trash and Pencil buttons should not be removed from the table

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1297

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1300/files

**Comment by nollymar** [comment]
https://github.com/dotCMS/core/pull/18290

**Comment by nollymar** [comment]
Passed internal qa

**Comment by nollymar** [comment]
**Note to QA:** Please test Field Variables feature

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF
