### ISSUE TITLE
Apps - UI: Maintain the App header when editing the entry for a host

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18255]
Maintain the App header when editing the entry for a host and take the user back to the app site selector page when the image or title are clicked

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1305

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Posgres // FF
