### ISSUE TITLE
[core] : Site Variables fail to display when referencing a non-existing user

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18256]
Reported via Support: [100876](https://dotcms.zendesk.com/agent/tickets/100876)
Reproducible since dotCMS 4.3.3, and latest master (5.2.8)

If you have a User that created a Site Variable, and then delete such a User, the `Edit Site variables` modal will not show up. The only error message is displayed in the browser's console:
```
dotcms.org.2898 
Object { javaClassName: "com.dotmarketing.business.NoSuchUserException", message: "dotcms.org.2898" }
```

### Steps to reproduce the behavior:
The steps to reproduce need to be simulated via database queries because dotCMS 4.3.3 demands you select a user to replace when deleting a user. You need to make up a User ID for the `LastModifierId` of a Site Variable to reproduce the problem.

### Expected behavior
The code must handle these kinds of situations and return the default value.

## Acceptance Criteria

1. Work in all the supported browsers (don't forget IE11 and iPad)
2. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18260

**Comment by dsilvam** [comment]
**Passed Internal QA:** Dialog opens and shows "Unknown" for the deleted user. Also adding new variables works ok. 

<img width="792" alt="Screen Shot 2020-04-24 at 1 48 23 PM" src="https://user-images.githubusercontent.com/1576794/80246623-532a7680-8632-11ea-8b8e-d038fc53e8f5.png">

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
