### ISSUE TITLE
Apps - UI: Remove confirmation message on save

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18250]
If the user clicks on Save to create/edit a configuration, we shouldn't display a confirmation popup. Just execute the save operation and go back to the previous page. 

In case an error occurs during the save process, show a growl message on the page once the redirect to the previous page is executed

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1303/files

**Comment by nollymar** [comment]
Passed internal qa
