### ISSUE TITLE
Allow to run an upgrade task by gradle

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18263]
would like to have the ability to run an upgrade task in the command line by gradle

**Comment by fmontes** [comment]
Hey @wezell what do we do with this one?

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18264/files

To test the jar from the repo **com.dotcms.upgrade.Upgrade** and add it to **core/libs/plugins**.
