### ISSUE TITLE
When ES is down the form are not getting render

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18268]
### Describe the bug
When Elasticsearch is down the form are not getting render 

### Steps to reproduce the behavior:
1. Go to a page with a form, for example, contact-us/index
2. Down Elasticsearch
3. Go again to contact-us/index

### Expected behavior
The Form should get render because the page is already in cache

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18281

**Comment by dsilvam** [comment]
Passed Internal QA: Form rendering when Elasticsearch is down

**Comment by bryanboza** [comment]
Fixed, tested on master and after kill the ES, we are able to render the page on FE and also add data to the form, after start the server again you are able to see the saved data.
