### ISSUE TITLE
inconsistent urls in content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18286]
Sometimes, when a page content URL is loaded from graphql, it returns only the page url and does not include the full path, e.g. the  `/destinations/costa-rica` page will sometimes return

`url: costa-rica`

rather than the full path.

`uri: /destinations/costa-rica`

I believe we have an issue that is a result of how/when a content is loaded into cache but I do not have a reproducible case.  See the screen shot of this happening in the wild.

<img width="737" alt="Screen Shot 2020-04-06 at 6 00 33 PM" src="https://user-images.githubusercontent.com/934364/78812910-2facce00-799a-11ea-9cc6-b36b6414acbb.png">

**Comment by fabrizzio-dotCMS** [comment]
note to QA:
use apache benchmark like these:

`ab  -H "Authorization: Bearer $TOK" -n 10000 -c 10 -g cr-page.data -v 3  http://localhost:8080/api/v1/page/json/destinations/costa-rica`

Ask me how to get a token 

against a version of master prior to commit `3e94b693c609022f77c91cb51a59b00b5ef1beb8`

here some of the urls I used

http://localhost:8080/api/content/id/a0f592c3-bfa9-421f-94c2-b2c3b156d116
http://localhost:8080/api/v1/page/json/store/products/aqua-sphere-cub-kid-mask-goggles
http://localhost:8080/api/content/render/false/type/json/query/contentType:Image
http://localhost:8080/api/content/query/*/limit/1000

**Comment by alfredo-dotcms** [comment]
for internal qa, scenarios tested, locally vs demo.dotcms:

Result: No diferences were found between demo and the implementation in localhost

Rest
```
http://localhost:8080/api/content/id/a0f592c3-bfa9-421f-94c2-b2c3b156d116
http://localhost:8080/api/v1/page/json/store/products/aqua-sphere-cub-kid-mask-goggles
http://localhost:8080/api/content/render/false/type/json/query/contentType:Image
http://localhost:8080/api/content/render/false/type/json/query/contentType:htmlpageasset
http://localhost:8080/api/v1/page/json/destinations/costa-rica
```

```
http://localhost:8080/api/content/query/*/limit/1000
baseType	“FILEASSET”,
baseType	“CONTENT”,
baseType	“HTMLPAGE”
```

GraphQL
```
{
  webPageContentCollection {
    titleImage{
      isImage
    }
  }
  
}
```

```
{
  htmlpageassetCollection {
    title
    url
    live
    host{hostName}
    hostFolder{folderPath}
  }
  
}
```

**Comment by nollymar** [comment]
**Needs work:**  After this change, it is not possible to select a Forward-To asset if I try to add a new vanity url: 

<img width="1679" alt="Screen Shot 2020-06-17 at 5 40 45 PM" src="https://user-images.githubusercontent.com/8741395/84957911-d8298d80-b0c1-11ea-8081-1c3b0ecb7b0f.png">

**Reason:** NullPointerException

**Comment by nollymar** [comment]
Fix: https://github.com/dotCMS/core/pull/18694

**Comment by nollymar** [comment]
Passed internal qa. After the fix, it works: 

<img width="1650" alt="Screen Shot 2020-06-17 at 6 01 13 PM" src="https://user-images.githubusercontent.com/8741395/84959232-90f0cc00-b0c4-11ea-81e9-2fef254ff1ea.png">

**Comment by bryanboza** [comment]
Fixed, tested with the provided info in release-5.3.3 // Postgres // FF
