### ISSUE TITLE
dots are not centered in action button in edit mode

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#18283]
The dots in the action menu button are not centered. See image

![Screen Shot 2020-04-08 at 11 45 55 AM](https://user-images.githubusercontent.com/1561349/78804972-d5f2d680-798e-11ea-8f26-088c3cc8766f.png)

## Acceptance Criteria

1. Center dots and test in all browsers

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1392

**Comment by dsilvam** [comment]
Passed Internal QA: Dots are now centered.

**Comment by bryanboza** [comment]
Fixed, now this looks better
