### ISSUE TITLE
Apps - Backend: Remove fallback behavior from sites configuration

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18289]
Currently, when SYSTEM_HOST has a secrets configuration and the rest of the sites don't, we are using the secrets configured for SYSTEM_HOST on those other sites as a fallback. We should remove this behavior as it can be confusing for end users

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18306

**Comment by nollymar** [comment]
Passed internal QA
