### ISSUE TITLE
Replace dotcms-field-elements with dotcms-webcomponents

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18288]
1. We need to test that `dotcms-webcomponents` are working
2. If everything is good, we need to replace `dotcms-field-elements` in our `deployWarTomcat` task.

## Top update:
1. Need to publish `dotcms-webcomponents` to npm
2. Need to update the the `build.gradle` to install this new package
3. Needs to update the `vtls` files to call the right JS file
    - `dotCMS/src/main/webapp/WEB-INF/velocity/static/content/content_form_macro.vtl`
    - `dotCMS/src/main/webapp/WEB-INF/velocity/static/content/content_form.vtl`

## Challenges:
1. Fields Web components might not be working as expected in `dotcms-webcomponents`
2. Testing: you can use symlinks to map from `tomcat8` to `dist` inside `dotcms-webcomponents` for dev.

## Acceptance Criteria

1. Update dotcms to use the new fields web components
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
This internal QA will required a little bit of regression tests in the whole form

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgress // FF
