### ISSUE TITLE
Create drop zone web component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18294]
## How it works
1. User will grab files from their OS and will drag them browser
2. User will drop the files in the drop zone (components)
3. Files start upload (show loading indicator)
    - Success: we show success message
    - Error: we show error message

## The component
1. Add classes depending on the event so we can do styling later:
  - When the files touch the drop zone
  - When the files are dropped
  - While the files are getting uploaded
  - When the files are of the drop zone
2. To upload you need to do 2 request
    - **temp api**: we have a [service](https://github.com/dotCMS/dotcms-webcomponents/blob/master/src/components/contenttypes-fields/dot-form/services/dot-upload.service.ts) for 
that
    - **Fire new workflow action to create dotasset:** and send the temp_file_id as the asset property, e.g. `asset:temp_id_123`:

```
PUT {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH
{
    "contentlet": {
        "baseType":"dotAsset",
        "asset":"{{temporalFileId}}",
        "tags":"test"
    }
}
```

#### To Save:
```PUT {{serverURL}}/api/v1/workflow/actions/default/fire/NEW```

#### To Publish
````PUT {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH````

## Acceptance Criteria

1. Be able to drop files and create dotassets
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
Mocks: https://github.com/dotCMS/core/issues/18296

**Comment by hmoreras** [comment]
PR's: https://github.com/dotCMS/dotcms-webcomponents/pull/23 
 and https://github.com/dotCMS/core/pull/18342
