### ISSUE TITLE
Add Page API to graphql

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18297]
Users want to use graphql to pull information about their pages which includes everything we use to support our EMA.  We need to enable this:

```graphql
page(url:"/about-us/index", pageMode:"LIVE", languageId:"en-us", persona:"persona"){
    url
    title
    ...
    tempate
    layout{
        rows{
            columns{
                offset
                width
                containers{
                    id
                    uuid
                    title
                    render
                    acceptContentTypes{
                        variable
                        name
                    }
                    contentlets{
                        id
                        title
                    }
                }
            }
        }

        header
        footer
        theme
        sidebar{
            width
            leftRight
        }
    }
    render
    urlmappedContent{
        title
        id
    }
}
```

- The list of contentlets in a container will all return common properties, e.g. inode, baseType, etc...
- Contentlets will also include a `map` property that will include all the properties of the Contentlets map.  \(the Page Object should include this too\)
- Customers can also request a `render` property at the Page and Container level.  If this is specified, we will returned the rendered output for that page or container.
- Pages are queried by host \(defaults to current host, `url`, `pageMode` \(LIVE/PREVIEW\), `languageId` and `persona`.
- at the base level, we should include the ViewAs information
- at the base level, there is a URLMap property that will be populated if there is a urlMap on the page.  This will also have the map property.

**Comment by dsilvam** [comment]
Documentation: https://docs.google.com/document/d/1jAyU__4x3koc4WQ_rigSGLM530j8VuQA3kBhD1vW-oU/edit?usp=sharing
