### ISSUE TITLE
Generate Metadata for all binaries

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18299]
We need to create a base amount of metadata for all binaries uploaded into dotCMS.  Additionally, we need to be able to return this from a contentlet per binary field basis. Having this metadata separated from the actual file on the filesystem will allow us to cache the metadata and avoid costly I/O ops to NFS mounted files.   It will also allow us to begin exploring storing files in other medium, such as blob stores, and retrieving those stored files lazily without having to share an nfs filesystem.

Below is the base metadata that is generated for every binary uploaded into dotCMS, stored under the inode folder as `fieldVar-metadata.json`.  If the binary is also indexed by elasticsearch, the tika metadata will overlay on top of this metadata.

```
fileName
contentType (mime)
length
sha256 - this is the checksum of the file uploaded
modDate
isImage
Dimension
```

```java
Map<String,Object> Contentlet.getBinaryMetadata(field or fieldVar){
   tries to load it from cache otherwise reads it and sticks it into cache
}

```

We need to fix the `ResourceLink` on the `contentlets/edit_field.jsp` to be able to support all binaries

**Acceptance criteria:** Implement ITs for the new logic

We should overlay the basic metadata on top of the tika metadata - basic meta should take precedence.

**Comment by wezell** [comment]
Let's verify that the SHA matches what you would get from a command line:

`shasum -a 256 --check`

**Comment by wezell** [comment]
### Phase 1 - Metadata
1. Get code into shape to get code merged into master even if not plugged in
2. Replace calls for file attributes that now go to the FS, with calls for metadata (file name, file size, mod_date, contentType, isImage, dimensions).  Metadata generation needs to happen for all binary fields - not just those that are indexed - if a binary is marked as indexed, then we generate the full metadata for it.  If not, then we only generate the basic metadata.

### Phase 2 - Files
2. Replace all saves to the `/assets` with the `LegacyFileStorageImpl`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19303

**Comment by fabrizzio-dotCMS** [comment]
I don't think QA will be needed here since this API isn't hooked up anywhere. No way to consume it or test except for the TestCases associated with it.
