### ISSUE TITLE
When try to submit a form get permission error

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18292]
### Describe the bug
When try to submit a form get permission error, the reason is the Actionlet to save and save draft a Contentlet are hard coding the respectFrontendRoles parameter.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/SaveContentAsDraftActionlet.java#L102

### Steps to reproduce the behavior:
1. Go to Contact-us
2. Fill the form and submit it

### Expected behavior
The form should be submit

**Comment by freddyucv** [comment]
PR:  https://github.com/dotCMS/core/pull/18300

**Comment by dsilvam** [comment]
Passed Internal QA: Forms are now submitting. However, file attachment "Headshot" is getting into the saved content. This is happening on demo as well.

**Comment by bryanboza** [comment]
Fixed, tested on master // Posgres // FF 

New card created here: #18346
