### ISSUE TITLE
Get Lock error permission when a limited user create a content

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18309]
### Describe the bug
When a user with WRITE permission over the content type create a new contentlet it is getting a lock error permission.

### Steps to reproduce the behavior:

https://www.screencast.com/users/FreddyRodriguez/folders/Default/media/c4d488b2-e055-4322-bc3a-c5415e8aa25c

### Expected behavior
Should not show any error

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18313

**Comment by dsilvam** [comment]
Passed Internal QA: Limited user with write permissions over the content type is able to "Save" a new content of that type.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
