### ISSUE TITLE
Apps - use fileName a key

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18303]
Right now, our App definition expects a key.  We should just use the fileName (without the .yml) extension as the key.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/18757

**Comment by fabrizzio-dotCMS** [comment]
Note for QA: Don't forget to remove the field key from your yml files.

**Comment by nollymar** [comment]
**Passed internal QA:** Tested using UI and Rest API

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF
