### ISSUE TITLE
Form submission not sending files

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18312]
This is happening on the Contact-us form in starter.

If you fill all the fields, including the binary field, it creates the content without the file. 

Reproduced on demo (5.2.8) and master. ![Screen Shot 2020-04-15 at 1.09.46 PM.png](https://images.zenhubusercontent.com/56e984726caf56c9d38dd540/2d20c94d-630a-45bf-811a-65d5934b492a)

**Comment by wezell** [comment]
@fmontes this looks like the webcomponent is broken

**Comment by alfredo-dotcms** [comment]
this seems to be working fine on latest master
https://monosnap.com/file/k1zOmAUktCDUJoP6C1aD5dx847CiVR

**Comment by bryanboza** [comment]
This seems that is working fine, but "My Interest" field lost the value once that you leave the field. 
![image](https://user-images.githubusercontent.com/2641437/159562865-cc7062e2-bb0c-4c36-b337-09576ce56486.png)

We need to take care of this.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1938/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

<img width="1571" alt="Screen Shot 2022-05-19 at 5 29 19 PM" src="https://user-images.githubusercontent.com/8741395/169414843-a5635c92-49ba-4422-9b2f-dec109deb4a9.png">

**Comment by bryanboza** [comment]
Fixed tested on release-22.06 // Docker // FF 
![image](https://user-images.githubusercontent.com/2641437/170086459-cf9a0bee-2a1b-4201-9b2a-fdac9a63185d.png)
