### ISSUE TITLE
Update ResourceLink to support ALL binary fields

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18310]
On the edit content screen, we need the `ResourceLink` to support all binaryfield.  We also need to update the filebrowser.js to allow the use and selection of 

- Update ResourceLink to support ALL binary fields
- Update WebBrowserAPI to optoinally return dotAssets

| var | pathing |
| ----- | ------ |
| idPath |  `/da/{identifierShorty}/{fieldVar}/{fileName} + ({languageId}!={defaultLanguage} ) ? "?languageId={languageId}":""`
| versionPath | `/da/{inodeShorty}/{fieldVar}/{fileName}`
| path | `https://{hostName}/{parentPath}/{fileName} + ({languageId}!={defaultLanguage} ) ? "?languageId={languageId}":""`

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18317/files)

**Comment by jdotcms** [comment]
Needs UI: when it is a contentlet with a binary two links are being rendered (version path and id path)
and when it is a file three of them (path also), both scenarios needs UI

**Comment by fmontes** [comment]
Move the link inside the "info" dialog

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18340

**Comment by erickgonzalez** [comment]
Tested and working as it should: 
* if there is no other language set in the system the IdPath not shows the language_id param.
* All the links are under the INFO button.
* ResourceLink only shows to FileAsset, not dotAsset base type.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
