### ISSUE TITLE
If a page does not exist in the default language, the language switcher kicks you out of edit mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18311]
We need some work here.

- If you create a Spanish page and try to see this in EN we are having en error related to the URL and the system redirects to the site browser again. 
- If the page exist just in a language different to the default one, we need to disable the other languages in the lang drop down to avoid this kind of errors or just show the empty page as in previous versions

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18084#issuecomment-613003138_

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
