### ISSUE TITLE
Edit contentlet binary and files field toolbar

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18329]
We the addition of [links](https://github.com/dotCMS/core/issues/18310#issuecomment-616644159) to all binary fields we need to do a better job of the information we show and the actions we can do on the fields, we need to revamp this:

![Screen Shot 2020-04-20 at 15.56.27.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/bed67ebf-e671-4fc5-a3a9-a3b40553ad6f)
--------------------------------------------
![Screen Shot 2020-04-20 at 15.56.41.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/8857d4ce-33c5-4f07-aafd-0a43103d66c4)

## Toolbar
Create a toolbar (icon buttons) with all the options need it:

1. Links
    - Preview
    - Copy
2. Remove
3. Info

And for images we need to add:
1. Edit
2. Clip

**Comment by wezell** [comment]
Should the links be under the info button?

**Comment by fmontes** [comment]
@wezell Could be... We can look into in the UI work.
