### ISSUE TITLE
Allow VanityUrls to pass parameters

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18325]
While it is possible to add parameters to a vanity URL

### Problem 1, you cannot specify a language_id in a vanity URL.
You have a vanity URL for a page that is ONLY in spanish e.g.
`/espanol --> /pages/esto-pagina-en-espanol`

An english visitor to `/espanol` will get a 404 b/c there is no english version of the page. Sadface.

To fix this,  you try to specify a language parameter in the vanity:
`/espanol --> /pages/esto-pagina-en-espanol?language_id=2`

While the parameter is ... passed, it is not seen by the CMSFilter as a real parameter and thus the page is never found. You still get a 404.

### Problem 2, original parameters get stripped out of vanitys that have params in them already.
ASay you have a vanity url that wants to pass part of the request uri as a param.  We allow this:
`/newpages/(.*) --> /destinations/costa-rica?param1=$1`

But the issue here is that the incoming url parameters are all stripped out, e.g, with 
`/newpages/costa-rica?param2=true` 

the `param2` does not get passed down to the page.

1.  If you pass parameters to a vanityUrl which also specifies parameters, they

**Comment by wezell** [comment]
There is a cool side effect of development.  You can use vanity urls to add params over parts of your site based on the vainty url.  For example, I added these two vanities:

```
/blog(.*)  --> /blog$1?language_id=1

/destinations(.*)  --> /destinations$1?language_id=2
```
and this has the effect of forcing spanish on everything under the `/destinations` folder
and forcing english on everything under the `/blog` folder.  We used to need a tuckey filter to do things like this - see:
https://dotcms.com/docs/latest/multi-site-language-configuration#RewriteRules

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18332

**Comment by dsilvam** [comment]
Passed Internal QA: Both cases in the description working

**Comment by dsilvam** [comment]
Passed QA. Note: If the same query param is set from the admin and also passed in the URL, the former will always override the latter. 

E.g.  Vanity URL in admin `/espanol` -> `/pagina-en-espanol?language_id=2` 
URL Hit: `/espanol?language_id=1`, results in the page in Spanish
