### ISSUE TITLE
Update docker container to allow for DB configuration

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18334]
Our docker image currently supports the ability to configure the DB out of the box using these properties:

https://dotcms.com/docs/latest/docker-image-configuration-options#dotCMSDBOptions

We need to support these variables with our 5.3.0 docker image and "dockerize" the `WEB-INF/classes/db.properties` file

We should also remove the db configuration from the context.xml in our docker image.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/18358

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/docker/pull/24
https://github.com/dotCMS/core/pull/18372

**Comment by fabrizzio-dotCMS** [comment]
For testing details on this issue see https://github.com/dotcms/core/issues/17843

**Comment by dsilvam** [comment]
Passed QA: DB Configuration successfully passed via environment variables to the docker image. Ran against local postgres DB
