### ISSUE TITLE
Implement a mechanism to lock nodes in a cluster

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18335]
As a user, I want to have a mechanism that handles cluster locks in order to avoid concurrent access of some logic that should be executed by one node at a time, for example the execution of upgrade tasks.

This mechanism can be implemented using a lock in database that keeps node timestamps to control lock access

Or we should use a tried and true library like shedlock:

https://github.com/lukas-krecan/ShedLock

**Comment by wezell** [comment]
Done as part of #21882
