### ISSUE TITLE
Unable to add content to pages using MySQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18341]
We have a SQL error when you try to add a piece of content or form to any page, and we are unable to add the form 

Error:  https://gist.github.com/bryanboza/95e5093a088df8069a1e147a6f6eb846

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new piece of content or form  
3. Create a new page 
4. Try to add the form to the page 
5. Check your log file 

### Expected behavior
We need be able to add content to pages without problems 

### Desktop (please complete the following information):
Tested on master // MySQL // FF

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18347

**Comment by dsilvam** [comment]
Passed Internal QA: Tested against MySQL on Docker. Able to add new content to a new page.

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now I'm unable to reproduce
