### ISSUE TITLE
Id path does not work if content is not published

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18345]
If you have an asset that is not published and you -as a backend user - try to view the asset using the "id path" you get a 404, even if you are cms admin. 
The id path means this:

`/dA/{identifier}/{binaryFieldVar}/{optional: fileName}`

You should be able to preview an asset as a backend user.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18349/files)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF
