### ISSUE TITLE
Unable to create a site search index using MySQL as database 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18343]
We have an error when you are using MySQL as database in a dotCMS instance, we have a `failure: null` error and we are unable to create the index 

ST: https://gist.github.com/azuysc/d6b17e536f315fcb665db434c3a316bf

### Steps to reproduce the behavior:
1. Start a dotCMS instance using MySQL as a database 
2. Login as admin 
3. Go to site search and try to create a site search index 

### Expected behavior
Site search should work in all the supported databases 

### Desktop (please complete the following information):
Tested on master // MySQL // FF

**Comment by freddyucv** [comment]
I can not reproduce the error

**Comment by bryanboza** [comment]
Fixed, unable to reproduce
