### ISSUE TITLE
Unable to add files to binary fields on forms 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18346]
When you add a form to a page and this contains a binary field, when you add some file to the binary and save the content, we are losing this file and save just the content with the normal fields 

### Steps to reproduce the behavior:
1. Login as admin 
2. Create a new form with a binary field
3. Create a new page and add the form 
4. Go to FE and try to save a new piece of content that contain some file to the binary
5. From BR make sure we save the content in the form without problems 

### Expected behavior
We need be able to save the values of every field without problems 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by jcastro-dotcms** [comment]
NOTE TO SUPPORT: Previous references to the Maintenance Plugin are incorrect. This code fix has not been packed into a Hotfix Plugin yet.

**Comment by hmoreras** [comment]
two scenarios here. when the file size is bigger that allowed, the error message don't show up.  Second, there is no way to set a value to the dot-binary-file field in cases when we load a form value.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/dotcms-webcomponents/pull/40

**Comment by fabrizzio-dotCMS** [comment]
Working in master as expected.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF

**Comment by bryanboza** [comment]
New enhancement reported #19557 9557

**Comment by bryanboza** [comment]
This is not working from FE, we still getting problems when you add a form to a page and try to add a binary from FE. Please take look

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/dotcms-webcomponents/pull/41/files

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres and Edge
