### ISSUE TITLE
Support INDEX_POLICY on query string

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18357]
Currently the INDEX_POLICY is only supported on the contentlet body, lets make it also possible on the query string.

**Comment by dsilvam** [comment]
Passed QA: Tested with `{{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH?indexPolicy={policy}` with both `force` and `wait_for`  and it's getting the proper value at the `internalCheckin` point
