### ISSUE TITLE
Unable to use future time machine snapshots 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18355]
We have problems trying to use the future time machine snapshots, we are unable to navigate in tho it and see the contentns.

### Steps to reproduce the behavior:
1. Login as admin 
2. Go to time machine and try to see the site in a future date 
3. Make sure you are able to navigate without problems 

### Expected behavior
We need be able to navigat though pages and see the content without problems 

### Screenshots
![imagen](https://user-images.githubusercontent.com/2641437/80232560-56ae0580-8612-11ea-905e-1ae04bdf1c2b.png)

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by DeanGonzalez** [comment]
Here is my Future Time Machine reproducible test case on demo.dotcms.com: 

![TimeMachineBug](https://user-images.githubusercontent.com/1569167/80236895-0edeac80-8619-11ea-9ea0-f86d518b522f.gif)

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18434

**Comment by dsilvam** [comment]
Passed QA: Future time machine showing content again.
