### ISSUE TITLE
Apps - UI: Display warnings when sites have invalid configurations

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18350]
As a user I would like to see warnings when any site configuration is invalid.
Warnings should be displayed in the following way: 

1) First Screen (where all services are displayed): a warning icon with a tooltip that contains the number of sites with warnings. Location: at the same level where the number of configurations is displayed

2) Second Screen (where all sites of a service are listed):  a warning icon with a tooltip that contains the number of secrets with warnings. Location: to the right of each site row

3) Third Screen (Details Page): a warning icon to the right of the invalid secret. If the user clicks on the icon, a modal with additional details is displayed.

The way the backend logic will be implemented to support this requirement is defined on this card: https://github.com/dotcms/core/issues/18218

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1309/files

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, some improvements reported on the card #18414
