### ISSUE TITLE
All Vanity URLs intermittently stop working, cache flush required to fix

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18364]
### Describe the bug

All vanity URLs on the dotCMS production site stop working once every 2-3 days.  A flush of the `vanityurlcache` region fixes the problem immediately.

### Steps to reproduce the behavior:

On our prod server, all we have to do is wait.  May be difficult to reproduce on a test system (see Additional context, below).

### Expected behavior

All Vanity URLs should continue to work without flushing the cache.

### Desktop (please complete the following information):
 - OS: All
 - Browser: All
 - dotCMS Version: 5.2.8 (dotcms.com)

### Additional context

* This problem is seen most often for Vanity URLs which are instances of the `Doc Redirect` content type.
    * This content type was created from the Vanity URL base type, and does not have any additional fields (just the system fields supplied by the base type).
    * However it's possible that the problem may be related to there being multiple vanity URL content types on the same server, or to having any vanity URLs using a content type other than the included `Vanity URL` content type.
* The problem happens even when there are no evictions shown for the `vanityurlcache` region.
    * It's possible that changing the cache region to use the Timed Cache provider might be a workaround for this problem, but we haven't tried it yet (we'd prefer to find and fix the root cause).
* It may not be easy to reproduce on a test system without significant traffic.
    * It takes 2-3 days on our prod server, which has hundreds of documentation vanity URLs; but the problem hasn't happened on our authoring server at all.
    * So isolation may require adding some kind of logging or debugging to our prod server and then waiting for the problem to happen again (check with appropriate parties before doing this).

## Related Issues

The following issues may be related, and we may want to address some of these at the same time:

* https://github.com/dotCMS/core/issues/17278
* https://github.com/dotCMS/core/issues/16684
* https://github.com/dotCMS/core/issues/18133

## Acceptance Criteria

1. Vanity URLs continue working without the need to flush the cache (regardless of the cache chain configuration, and even if there are a large number of evictions).
2. No problems when using multiple different Vanity URL content types (with or without additional fields added to the content type).
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
dupe: #17278

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18378/files

**Comment by dsilvam** [comment]
Passed Internal QA: Working on Prod dotcms.com
