### ISSUE TITLE
Cannot edit file asset with indexed Binary field containing specific file content

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18369]
### Describe the bug

If:
* A File Asset content type contains a Binary field with the Indexed property set to true, and
* A content item of this type uploads a file with specific content (see below) to the Binary field.

Then:
* When editing the content item in the BE, the content editing popup appears but then blanks out, and JS errors show in the browser console.

This makes it impossible to edit any fields of the content item from the back-end UI, when the binary field contains specific file contents.

### Steps to reproduce the behavior:

1. Save the attached file on your local system (somewhere you can upload it from into dotCMS).
2. Rename the file extension to `.vtl` (i.e. `file_js_error_demo.vtl`).
3. In the starter (or on demo), go to the Content Types screen, and edit the existing `File` content type.
4. Edit the `File Asset` Binary field.
5. Set the `Indexed` property to true, and save the field.
6. Go to any folder in the Site Browser tree.
7. Create a new file,
    * Upload the file saved in step 1.
    * Save and publish the file.
    * Exit the popup.
8. Double-click to edit the newly created file.
**Result:** The content editing popup appears normally at first, then errors appear in the browser console, and the content editing popup blanks out (showing nothing except the "X" to close the popup).

### Expected behavior

The contents of the Binary field should not be evaluated in any way when the content editing popup is opened.

### Demo File

The following file reproduces this error on the starter or demo:

[file_js_error_demo.txt](https://github.com/dotCMS/core/files/4542045/file_js_error_demo.txt)

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Both FF and Chrome
 - dotCMS Version: 5.2.8 (authoring and demo)

### Additional context

* The problem does **not** happen if the `Indexed` property of the Binary field is set to false.
* For this problem to be reproducible, the paths in the file need to have appropriate values:
    * The JS file referenced by the first line must not exist on the system.
    * The page referenced by the second line must exist on the system.
    * The paths in the included file work to reproduce the problem on the current starter (and on the current demo site).
* I only tested this on File Asset content types.
    * But it's possible it might happen to any content type containing a Binary field.
* Depending on what kind of evaluation is happening, this problem could potentially cause completely different issues, depending on the contents of the file in the Binary field.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by john-thomas-dotcms** [comment]
Just a note: When I look at the browser console and open a bunch of other file assets, I'm seeing errors with almost every file I open - but the errors are different for each file (since the contents of each file are different).The sample file (included above) is the only one so far that changes anything the user sees on the BE, but this problem appears to affect a very large number of files.

**Comment by wezell** [comment]
the issue is that we are now including the metadata.content in the metadata key/value display, whereas we used to exclude it if we were showing the metadata field.  We need to hide the contents of the metadata field

**Comment by wezell** [comment]
PR: #18374

**Comment by hmoreras** [comment]
tested and working on branch `issue-18369-metadata-content`

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
