### ISSUE TITLE
Image File Browser Upgrade

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18363]
In this screen:

![Screen Shot 2020-04-28 at 08 51 45](https://user-images.githubusercontent.com/751424/80502164-85d3b800-892d-11ea-99f4-c2476a0b0026.png)

## Acceptance Criteria
1. Style card view
2. Show dot assets in folders and hosts
3. Drag and drop files in folders and hosts

**Comment by bryanboza** [comment]
After this changes, pagination is not working on this window, If you try to select an image from a folder that contains multiple ones, we are unable to see the list, we are showing just 23 images and we are unable to paginate to see more images. 
SC: https://www.screencast.com/t/JE8psOd8q5k

**Comment by bryanboza** [comment]
Unable to use the filter after paginate, If you are in the page 2 and try to filter using the name, we are not getting result. Tested in the first page and work as expected.

**Comment by bryanboza** [comment]
Fixed, new case reported in a new card... Tested on master // Postgres // FF
