### ISSUE TITLE
WorkflowResource: Bulk Fire should support Default Action

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18366]
Currently dotCMS has the ability to fire an action for several contentlets, it is called bulk actions.
We need the same support for default action, basically to send multiple contentlets

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/20115

**Comment by erickgonzalez** [comment]
Working as it should.

**FWIW to Doc and Test**
 
PATCH  /api/v1/workflow/actions/default/fire/{systemAction}
Body:
```
{
    "query":"{lucene query}",
	"contentlet": {
        "{fieldName}":"{newValue}"
	}
}
```
The response will be all the contentlet updated and also we included a summary:
```
"summary": {
            "affected": X,
            "failCount": Y,
            "successCount": Z,
            "time": W
        }
```

A couple of examples:

1) This one will update the value of the title field for every contentlet of the generic Content ContentType 
```
PATCH  /api/v1/workflow/actions/default/fire/PUBLISH
{
    "query":"+contentType:webPageContent",
	"contentlet": {
        "title":"Update title batch POSTMAN"
	}
}
``` 
Summary Response:
```
"summary": {
            "affected": 24,
            "failCount": 0,
            "successCount": 24,
            "time": 2249
        }
```

2) This one will update only one contentlet of the generic Content ContentType
```
PATCH /api/v1/workflow/actions/default/fire/PUBLISH?inode=cc12b1ea-61d2-4595-8630-c8a89981a33b
{
	"contentlet": {
        "title":"NEW TITLE POSTMAN"
	}
}
```

**Comment by bryanboza** [comment]
Fixed, tested with the provided examples on release-21.05 // Postgres // FF
