### ISSUE TITLE
Apps - Make apps resilient to site a site delete event.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#18373]
### Describe the bug
When a site with secrets gets deleted the secrets count is off and the secrets that were associated with the site remain in the secret store

### Steps to reproduce the behavior:
1.  Create a couple of different sites then go to Apps.
2. Add secrets for two or more sites. Verify the configurations count shown next to the App
3. Now Remove one of the sites and verify again the configurations count.

## Acceptance Criteria
1. Secrets must be removed from the secrets store on a site delete event.
2. Secrets count must remain accurate even after sites are removed.
3. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18365

**Comment by nollymar** [comment]
Fixed. Passed internal qa
