### ISSUE TITLE
After import, custom content portlet shows wrong content

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18379]
### Describe the bug

If you select a custom content portlet, and import content, after the import is completed, the wrong content is shown in the portlet.

### Steps to reproduce the behavior:

1. Create a custom content portlet which displays only content of 2 specific content types.
2. Add the custom content portlet to a Tool Group.
3. Open the custom content portlet by selecting it in the navigation sidebar.
4. In the `Type` selector in the left sidebar, select one of the content types.
5. Import some content into this content type.
6. When the import is finished, press the `Finished Importing` button.
    **Result:** Although the custom content portlet is still selected in the left sidebar, all content on the system is displayed in the list (the list is no longer filtered to display only content types allowed in the custom content portlet).
7. Click on the `Type` selector in the left sidebar.
    **Result:** All content types are listed in the `Type` selector (rather than just the content types allowed in the custom content portlet).

### Expected behavior

The custom content portlet should continue filtering the content types and content after the import is complete.

### Screenshots

Before import:

![image](https://user-images.githubusercontent.com/13456955/80511035-67bb8700-8930-11ea-9316-022e2354e878.png)

After import:

![image](https://user-images.githubusercontent.com/13456955/80510977-56727a80-8930-11ea-9cd6-354cee0b1d72.png)

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome
 - Version: dotCMS 5.2.8

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
Findings:
on this line https://github.com/dotCMS/core/blob/9e9f3ef6312b9c4a06242af62678096a20923faa/dotCMS%2Fsrc%2Fmain%2Fwebapp%2Fhtml%2Fportlet%2Fext%2Fcontentlet%2Fimport_contentlets_results.jsp#L68

the link could be missing attributes/params to let the BE know what Content Types to return after redirect.

The content types loaded after are set here:
https://github.com/dotCMS/core/blob/c4cf11432823a0f1fcebcb65e206f4157ae96e6d/dotCMS%2Fsrc%2Fmain%2Fwebapp%2Fhtml%2Fportlet%2Fext%2Fcontentlet%2Fview_contentlets.jsp#L32
