### ISSUE TITLE
Add constraint for case-insensitive uniqueness of Content Type variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18382]
We have a test that accidently added new `Host` content type, except lowercase `host`, which our schema allows.  We should not allow this at the database level:

We have this constraint:
```
alter table structure add constraint unique_struct_vel_var_name unique (velocity_var_name);
```

It should be lower
```
alter table structure add constraint unique_struct_vel_var_name unique (lower(velocity_var_name));
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18395

**Comment by dsilvam** [comment]
The validation was included at API level instead of a DB constraint.

**Comment by nollymar** [comment]
**Passed internal qa:** Success. Tested through the content type api

**Comment by bryanboza** [comment]
We need some work here: 

- Now we have the validation, but if you try to add a `host` content type at UI level we have the error in the log, but we are not showing a notification in the UI

- If you try via API, we have the 400 response error wich is ok, but we need work in the response body, right now we are returning this: 
```
<!doctype html>
<html lang="en">

<head>
	<title>HTTP Status 400 – Bad Request</title>
	<style type="text/css">
		h1 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 22px;
		}

		h2 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 16px;
		}

		h3 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 14px;
		}

		body {
			font-family: Tahoma, Arial, sans-serif;
			color: black;
			background-color: white;
		}

		b {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
		}

		p {
			font-family: Tahoma, Arial, sans-serif;
			background: white;
			color: black;
			font-size: 12px;
		}

		a {
			color: black;
		}

		a.name {
			color: black;
		}

		.line {
			height: 1px;
			background-color: #525D76;
			border: none;
		}
	</style>
</head>

<body>
	<h1>HTTP Status 400 – Bad Request</h1>
	<hr class="line" />
	<p><b>Type</b> Status Report</p>
	<p><b>Message</b> Bad Request</p>
	<p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a
		client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	</p>
	<hr class="line" />
	<h3>Apache Tomcat/8.5.32</h3>
</body>

</html>
```

**Comment by dsilvam** [comment]
Comment above fixed by PR: https://github.com/dotCMS/core/pull/18449

**Comment by nollymar** [comment]
**Passed internal qa:** The error reported by @bryanboza has been solved.

Testing in UI, this popup is displayed:
<img width="1673" alt="ContentTypeError" src="https://user-images.githubusercontent.com/8741395/81434094-3c544b80-912b-11ea-9d88-1d563071af83.png">


And the API response is a 400 error with this message: 

```
{
  "message": "Content-type is not valid (Invalid content type variable: host)"
}
```

**Comment by bryanboza** [comment]
After the last changes now the endpoint is returning the response with the error, but when you try from UI, we are closing the new content type form and showing the error, after you close the pop-up we redirect to content types portlet. We need to redirect to the `add new content type` form again in order to update the name and create the content type. 

Also since this is a handled error, we need show on logs just a line error, rigth now we are printing too many lines of error here: 
LOG: https://gist.github.com/bryanboza/1d85ae05f1001e66660957bdd1af973c

**Comment by bryanboza** [comment]
Fixed, the pending case was moved to a new card.
