### ISSUE TITLE
Download Data/Assets and Backup Data/Assets creates diff zip 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#18388]
Both Tools (Download Data/Assets and Backup Data/Assets) should create the exact same zip, but right now the Download one contains more info than the Backup one (Identifiers, Language, Relationships). Seems that the issue is that the **Download** one calls the one under **ViewCMSMaintenanceAction** and the **Backup** one call **CMSMaintenanceAjax**.

The one under **ViewCMSMaintenanceAction** has been updated recently but the one under **CMSMaintenanceAjax** no. Maybe the approach should delete the one under **CMSMaintenanceAjax** and modify the call of the Backup to use that one as well, so in the future, we only maintain one method.

https://github.com/dotCMS/core/blob/a4974b9a32740a6824ac00fac566ac868e164306/dotCMS/src/main/java/com/dotmarketing/portlets/cmsmaintenance/ajax/CMSMaintenanceAjax.java#L443

https://github.com/dotCMS/core/blob/a4974b9a32740a6824ac00fac566ac868e164306/dotCMS/src/main/java/com/dotmarketing/portlets/cmsmaintenance/action/ViewCMSMaintenanceAction.java#L565

Expected Behavior 
Both options should generate the same zip file.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18389

**Comment by hmoreras** [comment]
![image](https://user-images.githubusercontent.com/31667212/80627476-3664b900-8a0d-11ea-9bee-a9e9482e7b5b.png)

Looks good.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
