### ISSUE TITLE
If you have permissions to see the page, but this page depends of a VTL file, we have an error when you try to see the page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18384]
We need some work here: 

- If you have permissions to see the page, but this page depends of a VTL file, we have an error when you try to see the page and after this continue showing the same error. 
SC: https://www.screencast.com/t/ZihwBAtuYAg

Here the role permissions: 
![image](https://user-images.githubusercontent.com/2641437/80244946-0db47c00-8627-11ea-8a3c-15dc1c638b24.png)

 - In case you don't have permissions to any site, we need use the login variable, email or userId (depending your configuration) to show in the error message 
![image](https://user-images.githubusercontent.com/2641437/80250273-ba472b80-8630-11ea-9b09-3dbe175176ec.png)

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18069#issuecomment-619175096_

**Comment by fmontes** [comment]
Closing as per @victoralfaro-dotcms completion.
