### ISSUE TITLE
Add a Put/Regenerate SecretKey

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18381]
We should give a user the ability post into or regenerate the SecretKey that is stored in the company db table.  This is CMS_ADMIN only.  When this is hit, it should 

0. Insure the posted "secret" is a valid `javax.security.key`
1. build an in memory list of PP endpoint config values (decrypted)
2. insert the new company.key_ (or if value is not passed, regenerate it) 
3. Reinsert the PP endpoint config values using the new key

We should add this to the existing `CMSConfigResource`

The endpoint should return the SHA-3 value of the new key

**Important things to be considered:**
- [x] Flush Apps cache after the key is regenerated
- [x] A confirmation message should be displayed to the user before regenerating the key, suggesting him to export existing secrets as they will be blown away after the operation
- [x] The keystore password must be generated lazily and stored in database as a new column in the `dot_cluster` table

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/729 
PR: https://github.com/dotCMS/core/pull/18638

**Comment by fabrizzio-dotCMS** [comment]
Got to: Control Panel > Configuration 
and find this new button.

![Screen Shot 2020-06-18 at 14 06 54](https://user-images.githubusercontent.com/37148755/85069018-9b689f80-b170-11ea-8704-f21962a06a63.png)

It should only be available to admin users
By clicking on that button the Key that is used to cipher the Apps Secrets and to secure the Push publish endpoints will be regenerated. Therefore two things must be tested here.

1. We need to validate that the environment is able to send and receive via push-publish.
2. We need to validate that the apps can still be used. But with a small disclaimer. As we are regenerating the key used to cipher the secrets. The secrets are no longer accessible. For that reason, the file dotSecretsStore.p12 will be backed up and a brand new one will be set in place. In other words, any previously-stored secret will be lost. In the near future we will offer the possibility to export them prior to the key regeneration process. For now, they are only backed up.

**Comment by nollymar** [comment]
I found a small issue. When the database is H2, the server throws an error during the startup process https://gist.github.com/nollymar/99e6a060148b7690ad0d68e1383b59d8

Apparently the h2.sql file was not updated to include the `cluster_salt` column.

**Comment by wezell** [comment]
We do not support H2 anymore  :)

**Comment by nollymar** [comment]
Fixed https://github.com/dotCMS/core/pull/18745

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF
