### ISSUE TITLE
File Links are duping the file name in the url

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18387]
If you have a file or image field on a piece of content and select a dotAsset, the file link will include the name twice.

For example a new Shop Page:

![Screen Shot 2020-04-28 at 7 33 31 PM](https://user-images.githubusercontent.com/934364/80547900-5baee400-8987-11ea-9226-d97c7e3e5f9d.png)

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18383/files)

**Comment by fmontes** [comment]
If you add an image to the WYSIWYG it gets the double link

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master // Postgress // FF
