### ISSUE TITLE
Bottleneck in Field.fields(clazz)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18397]
Benchmarking this api call: `http://localhost:8080/api/v1/page/render/index?language_id=1`

```
ab -H "Authorization:Bearer $TOK" -n 10000 -c 10 http://localhost:8080/api/v1/page/json/index
```

It looks like we have a bottleneck in this code in `ContentType.java`.  The asSubclass is sloooow.  We use subclass b/c the immutables are subclasses.

```java
  @JsonIgnore
  @Value.Lazy
  public List<Field> fields(final Class<? extends Field> clazz) {
    return this.fields()
    .stream()
    .filter(field -> Try.of(()->field.getClass().asSubclass(clazz)!=null).getOrElse(false))
    .collect(Collectors.toList());
  }
```
![Screen Shot 2020-04-29 at 5 50 58 PM](https://user-images.githubusercontent.com/934364/80650474-0e437d00-8a42-11ea-8150-5b43df958b58.png)

---

Our performance goes up like 500% If I replace this with a simple string comparison
```java
  @JsonIgnore
  @Value.Lazy
  public List<Field> fields(final Class<? extends Field> clazz) {
    final String clazzName = clazz.getName().replace(".Immutable",".");
    return this.fields()
       .stream()
       .filter(field -> 
       field.getClass().getName().replace(".Immutable",".").equals(clazzName) 
    )
    .collect(Collectors.toList());
  }
```

**Comment by wezell** [comment]
Now performance looks like 

![Screen Shot 2020-04-30 at 10 01 51 AM](https://user-images.githubusercontent.com/934364/80719556-a46eb600-8ac9-11ea-9ac8-182fbb61a37d.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18398

**Comment by wezell** [comment]
![Screen Shot 2020-04-25 at 2 04 15 PM](https://user-images.githubusercontent.com/934364/80735097-308ad880-8ade-11ea-8b03-2fe465d1c470.png)
