### ISSUE TITLE
Drag and drop images into the WYSIWYG

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18401]
We need to allow users to enrich their content with images very easily with just dropping an image in their WYSIWYG fields.

### Right now the have to do a big process to achieve this:

1. Click in the WYSIWYG add image button
2. Click browse
3. Drag and drop to upload the image
4. Select image
5. Click "insert"
6. Image in place.

The idea is to reduce all this just to drop the image and that's it.

![Drag and Drop Image in WYSIWYG](https://user-images.githubusercontent.com/751424/80752295-7ea4d980-8ae8-11ea-80e1-ecc133422861.png)

### Things to consider:
1. If the contentlet have a **Site/Folder field** we save the image into whatever is selected there, if nothing is selected or the field doesn't existe save it to **System Host**
2. We need to position the image where the **cursor is** inside the WYSIWYG field
3. WYSIWYG have CODE and PLAIN, we don't allow dropping there.
4. Need to add the "EDIT" button to the inserted image to edit the image right there.

## Acceptance Criteria

1. Allow user to drop and edit images in WYSIWYG fields
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, new improvements of this functionality in here: #18629 and #18630
