### ISSUE TITLE
Apps - UI: Make a param to set "autofocus" on Dot-Key-Value component and set it false in Dot-Apps Form page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#18409]
As a user, I need that the form configuration page in Dot-Apps, focus on the first element, once the page loads.

Current Behaviour: the page loads with focus on the dynamic field variables input (if AllowExtraParams is enabled), otherwise there is no focus event.

Desired: once the page loads the focus should be done in the first field of the form.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1317

**Comment by nollymar** [comment]
Passed internal qa
