### ISSUE TITLE
Allow dotParse to use dotAssets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18402]
We need to allow dotParse to use dotAssets (or any binary field I guess).  The path to the file can be exactly like the identifier path, e.g. ~`/dA/{identifier}/{fieldVar}`. We will just need to resolve the file and parse it in velocity.

**Comment by wezell** [comment]
PR: #18578

**Comment by erickgonzalez** [comment]
Tested working as it should, now we allow that the **#dotParse** resolves the id path of a file.
E.g:
`#dotParse("/dA/76ccc52493/binaryfield")`
or as it worked before using the absolute path
`#dotParse("/test.vtl")`

More info at https://dotcms.com/docs/latest/include-of-a-vtl-or-html-file#Syntax

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
