### ISSUE TITLE
Apps: Warning icon overlaps label

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18415]
There are 3 issues: 

1. The icon overlaps the "Configurations" label

![Screen Shot 2020-04-30 at 5.48.34 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/b3469021-50cd-4242-9495-ff4072012b30)

2. The word "Configurations" on the tooltip should be changed to "Configuration(s)"

![Screen Shot 2020-04-30 at 5.58.57 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/04a5b787-4494-453f-a2f2-b8eff4ab0c9e)

3. The color of the warning icon should be the same in all pages. The icon is showing black in the Details Page

**Comment by alfredo-dotcms** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1318

**Comment by alfredo-dotcms** [comment]
PR
https://github.com/dotCMS/core-web/pull/1343/files

**Comment by fabrizzio-dotCMS** [comment]
One small detail needs. Where it says.. `1 Invalid Secrets` it should say  `1 Invalid secret(s)`

![Screen Shot 2020-06-15 at 10 24 37](https://user-images.githubusercontent.com/37148755/84682207-8bdc2300-aef2-11ea-96f4-4c5b42fbf874.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18667

**Comment by bryanboza** [comment]
Fixed on the card #18414
