### ISSUE TITLE
Add flyouts to collapsed menu

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18410]
As a user I want to be able to go to any portlet when the menu is collapsed.

### Mock
![Screen Shot 2020-04-30 at 16 00 28](https://user-images.githubusercontent.com/751424/80763719-6474f680-8afc-11ea-96e1-a9b9523bb73f.png)

### Context
1. Remove tooltip
2. Click to the icon remain the same (going to first porlet)

## Acceptance Criteria
1. Show flyout menu on hover.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
Flyouts are showing on right click, we need to change the event to hover.

**Comment by fishsmith** [comment]
@fmontes feedback on the design

1. I think we can tighten up the spacing. I think the top level we could do 45px height between menu items and 40px for the submenu. In your design we have a height of 50px for both.
2. Think we should use the same colors as the extended menu. Not a fan of the white flyout.

See image
![flyout-idea](https://user-images.githubusercontent.com/1561349/80989460-f5044d00-8e02-11ea-9d77-b219865dd4a6.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF
