### ISSUE TITLE
Apps: Warnings are not loaded correctly

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18414]
If I have 3 configured sites with missing required fields, the tooltip only displays 2 sites with warnings, but if I go to the site details, the warning is displayed for the field. I have attached some screenshots for further details:

**Image 1:** Incorrect count

![Screen Shot 2020-04-30 at 5.58.57 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/868e6037-27ce-4cce-9bb4-09b97792b9d1)

**Image 2: ** Incorrect count because SYSTEM_HOST doesn't have a warning

![Screen Shot 2020-04-30 at 5.59.09 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/bb11eb76-a58f-4b10-bb36-7245f351f03a)

**Image 3:** Correct

![Screen Shot 2020-04-30 at 5.59.24 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/fc61a8a9-8e38-4c0d-896b-63dd28f3e4ce)

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18418

**Comment by nollymar** [comment]
Fixed. Passed internal qa

**Comment by nollymar** [comment]
Fixed on https://github.com/dotCMS/core/issues/18415

**Comment by fabrizzio-dotCMS** [comment]
This issue has been corrected in master. Therefore I am marking it as passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
