### ISSUE TITLE
Apps: Error deleting all configurations

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18413]
After clicking "Delete All", I got an unexpected error and this stack trace: https://gist.github.com/nollymar/e3422e200a6ac79d1ca13b1f563616b9

**Steps to reproduce:** 
1. Create 4 sites and activate just 2 of them
2. Add a secret configuration for the 2 active sites
3. Click on Delete All

**Comment by fabrizzio-dotCMS** [comment]
https://github.com/dotCMS/core/pull/18418

**Comment by nollymar** [comment]
Passed internal qa
