### ISSUE TITLE
Drag and drop images into containers in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18411]
### Problem
People needs to click like 4 times to add an image to a container.

### Solution
Allow uses to drag files (images) from their file system  and drop it in a container in a page

### Technical Approach
1. We need to inject JavaScript code in the iframe to allow to do this (`apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/html/libraries/iframe-edit-mode.js.ts`)
2. We upload the image to the [temp resource](https://github.com/dotCMS/core-web/blob/52678885de27b0e23bab69de2b2afe9beb9c166a/libs/dotcms-field-elements/src/components/dot-form/services/dot-upload.service.ts#L46)
3. We [create a dotasset](https://github.com/dotCMS/core-web/blob/52678885de27b0e23bab69de2b2afe9beb9c166a/libs/dotcms-webcomponents/src/services/dot-asset/dot-asset.service.ts#L15) with the image
4. We add the dotasset contentlet to the container

### Rabbitholes
1. The container might not accept dotassets
2. User will try to add other file types
3. We need to show indication than the image is uploading
4. We need to handle errors

### No goes
1. No video just images
2. No multiples images

**Comment by alfredo-dotcms** [comment]
Add in starter in path `/application/containers/default` the file `dotasset.vtl`

**Comment by alfredo-dotcms** [comment]
[dotasset.vtl.zip](https://github.com/dotCMS/core/files/6833195/dotasset.vtl.zip)

**Comment by alfredo-dotcms** [comment]
core-web PR: https://github.com/dotCMS/core-web/pull/1707/files

**Comment by fmontes** [comment]
I did a soft QA here, my findings:

1. If you create a container (not file) and add "Activity" you can dragover files and add the marker
2. Is not respecting the max contentlet field, there is in `data-max-contentlets="2"` that we need to check

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core-web/pull/1713

**Comment by alfredo-dotcms** [comment]
A) normal steps:
- https://github.com/dotCMS/core/issues/18411#issuecomment-881696586
- go to edit page and drag and drop an img into a container

B) with custom template:
- create 2 custom containers http://localhost:8080/dotAdmin/#/c/containers
- one with only `Activity` 
![image](https://user-images.githubusercontent.com/37185433/128393404-397db2f2-4a11-4bfb-a175-b34dc0cd6ba9.png)

- one with 2 max contentlets with dotAssets
![image](https://user-images.githubusercontent.com/37185433/128393829-2d4a1222-4c44-4321-bc90-6eec4aa56193.png)


- create a new template with both containers
![image](https://user-images.githubusercontent.com/37185433/128393723-4c4fb591-8b75-4663-8784-44ea982eab2f.png)

- create a new page with the new template
- Follow steps from **A)**

**Comment by nollymar** [comment]
**Passed internal QA:** Tested using full and empty starter. It works as expected

**Comment by bryanboza** [comment]
We have problems when you try to drag and drop images, if you set the `max contents=2` you are able to drag&drop just one images, if you set that property =3, then you are able to put just two contents here. Now if you try to add the contentlets via backend, you are able to use the 2 or 3 without problems. 

We need some work here

**Comment by nollymar** [comment]
New fix: https://github.com/dotCMS/core-web/pull/1743

**Comment by nollymar** [comment]
**Passed internal QA:** The issue reported by @bryanboza was fixed

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09  // docker
