### ISSUE TITLE
[ES] : Reindex gets stuck on specific failure scenarios

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18424]
Found when working on Customer Upgrade Request: [100261](https://dotcms.zendesk.com/agent/tickets/100261)

Customers upgrading from very old versions of dotCMS usually carry a lot of data inconsistencies and configurations that are no longer valid in recent versions. Issues like this will never be reproducible with Starter data, and are only found when working on upgrades. Content Types that are no longer valid in terms of fields, are causing the reindex to never end. That is, the reindex status is never updated correctly.

An additional issue has been found regarding the **DOWNLOAD FAILED RECORDS AS A CSV FILE**, in which records that are still in the process of being reindexed are included in the list. This is causing errors and sends an empty CSV file to the user.

### Steps to reproduce the behavior:
You can ask the Support Team for a database backup that can be used to reproduce this.

### Expected behavior
The reindex and the download of failed records must work correctly.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18425

**Comment by nollymar** [comment]
**Note to QA:** An easy way to generate failed records using the old starter is running this script on your database: `update field set field_type = 'categories_tab' where field_name='Product Number' and structure_inode in (select inode from structure where name='Product')`

**Comment by fabrizzio-dotCMS** [comment]
I was able to simulate the re-index error running the query 
`update field set field_type = 'categories_tab' where field_name='Product Number' and structure_inode in (select inode from structure where name='Product')
`
After doing that you must flush the cache to guarantee that the reindex will break next time it'll try to look at the content of type Product.

The reindex indeed breaks. But it'll continue to work reindexing whatever content finds next. 
In the Log file, you can see that even after the failure a number of successful records are getting written. Meaning it doesn't stop. 

```
Caused by: com.dotmarketing.business.DotStateException
	at com.dotcms.contenttype.model.field.FieldBuilder.builder(FieldBuilder.java:60) ~[dotcms_master_e856d62.jar:?]
	at com.dotcms.contenttype.model.field.FieldBuilder.builder(FieldBuilder.java:37) ~[dotcms_master_e856d62.jar:?]
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.impleClass(ImplClassFieldTransformer.java:39) ~[dotcms_master_e856d62.jar:?]
	... 52 more
Caused by: java.lang.NullPointerException
	at com.dotcms.contenttype.model.field.FieldBuilder.builder(FieldBuilder.java:43) ~[dotcms_master_e856d62.jar:?]
	at com.dotcms.contenttype.model.field.FieldBuilder.builder(FieldBuilder.java:37) ~[dotcms_master_e856d62.jar:?]
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.impleClass(ImplClassFieldTransformer.java:39) ~[dotcms_master_e856d62.jar:?]
	... 52 more
10:56:07.602  WARN  reindex.ReindexQueueAPIImpl - Reindex failed for :IndexJournal [id=6170, identToIndex=1f5c10a8-b87d-4889-9289-147f35f074cf, priority=300, delete=false, serverId=null] because An error occurred when mapping the properties for Contentlet with ID='1f5c10a8-b87d-4889-9289-147f35f074cf', Inode='b877e3d3-b694-46a6-bc3c-326a375d7da6', Content Type 'a1661fbc-9e84-4c00-bd62-76d633170da3': Unable to load data for Field 'Product Number' of type 'unknown/invalid' with ID [5d9617ce-0a6a-49fb-b4b5-6e18ae4de1b2]: null
10:56:07.613  INFO  tika.TikaUtils - Metadata read from: /Users/fabrizzio/code/servers/server1/assets/6/1/61ae2336-8b35-4cee-97b3-232e03d4696c/fileAsset-metadata.json
10:56:07.633  INFO  tika.TikaUtils - Metadata read from: /Users/fabrizzio/code/servers/server1/assets/4/a/4a8feeda-e4b7-4df2-9ff4-53ae8a3c5f6e/fileAsset-metadata.json
10:56:07.666  INFO  tika.TikaUtils - Metadata read from: /Users/fabrizzio/code/servers/server1/assets/8/3/838aeea4-5701-4763-acef-2856608d36d8/fileAsset-metadata.json
10:56:07.736  INFO  reindex.BulkProcessorListener - -----------
10:56:07.736  INFO  reindex.BulkProcessorListener - Reindexing Server #  : 1 of 1
10:56:07.736  INFO  reindex.BulkProcessorListener - Total Indexed        : 0
10:56:07.736  INFO  reindex.BulkProcessorListener - ReindexEntries found : 500
10:56:07.736  INFO  reindex.BulkProcessorListener - BulkRequests created : 811
10:56:07.736  INFO  reindex.BulkProcessorListener - Full Reindex Elapsed : 13.736s
10:56:07.736  INFO  reindex.BulkProcessorListener - -----------
```
In this scenario, I corrupted all content of type `Product` by updating a field with an invalid type. 
When switching over to the newly generated index all other content is available but the content of type product which is the one we altered. 

I was able to verify that the file with failed records is available for download for as long as the message of failure isn't been dismissed.

**Comment by bryanboza** [comment]
Fixed, tested breaking contents directly from the database with the provided examples and the reindex continue as expected.
