### ISSUE TITLE
Custom Content Portlets don't accept content Language Variables

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18429]
### Describe the bug

You can enter a Language variable key as the name of a custom content portlet, and it will be replaced properly if the Language variable key is defined using a legacy Language variable (in the Languages portlet).  But if you define the key using a content Language variable, the value will not be replaced.

### Steps to reproduce the behavior:
1. Open the Languages portlet.
2. Select English.
3. Create a new Language variable with the key `portlet.title.1` and the value `Title 1`, and save changes.
4. Open the Content Search portlet.
5. Create a new Language Variable content item with the key `portlet.title.2` and the value `Title 2`, and publish it.
6. Open the `Roles & Tools` portlet and select a Role.
7. Click on the `Tools` tab.
8. Click the `CREATE CUSTOM CONTENT TOOL` button, and create a new tool with the following values, then hit `OK` to save it:
    * Tool Name: `portlet.title.1`
    * Id: _(leave the same as the title)_
    * Base Types: _(leave blank)_
    * Content Types: `Activity`
9. Click the `CREATE CUSTOM CONTENT TOOL` button again, and create a new tool with the following values, then hit `OK` to save it:
    * Tool Name: `portlet.title.2`
    * Id: _(leave the same as the title)_
    * Base Types: _(leave blank)_
    * Content Types: `Banner`
10. Click any Tool Group which is visible to the admin user, to edit it.
11. Add both of the new custom content portlets to the Tool Group, and save the changes.
    * **Result:** The name of the first portlet appears as `Title 1` in the list of portlets, and the name of the second portlet appears as `portlet.title.2`.
12. Save the changes and return to the Tools screen.
    * **Result:** Also in the Tool groups list, the name of the first portlet appears as `Title 1` and the name of the second portlet appears as `portlet.title.2`.
13. Refresh your browser.
14. Open the edited tool group in the navigation side bar, and view the portlet names.
    * **Result:** The name of the first portlet (using a legacy Language var) will be replaced properly, but the name of the second portlet (using a content Language var) will not be replaced.

### Expected behavior

Users should be able to use content Language variables to set the names of custom content portlets.

### Screenshots

Definition of the `Activites` legacy language variable:

![image](https://user-images.githubusercontent.com/13456955/80979771-a04ddb80-8ddc-11ea-85da-9b8925233d58.png)

Definition of the `Banners` content Language variable:

![image](https://user-images.githubusercontent.com/13456955/80979616-6f6da680-8ddc-11ea-8bbd-bd67dcfff682.png)

Back-end with both the above language variable defined:

![image](https://user-images.githubusercontent.com/13456955/80979872-beb3d700-8ddc-11ea-8787-b415ae768cb3.png)

### Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome and FF
 - Version: dotCMS 5.2.8 (demo and distro)

### Additional context

* There are 3 different places where the content Language variable is not properly replaced.
    * See steps 11, 12, and 14, above.
* More generally, users should be able to use content Language variables anywhere legacy Language variables work.
    * The content Language vars will never be fully adopted until they work everywhere the legacy ones do.
* Would it make sense to make changes to the legacy Language variable code, so that if a search for a legacy language var fails, it automatically checks content Language vars?
    * It may not make sense - but if we could do it at this level, it would ensure that the content Language vars work everywhere the legacy ones do, without us having to do a search for all places where we're currently checking for legacy Language vars.

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Work with multiple language versions of the same content Language var
4. Unit test

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
