### ISSUE TITLE
Create endpoint to get image url from DotAsset

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18427]

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18431/files)

**Comment by fmontes** [comment]
We need to have all the filter information from: https://dotcms.com/docs/latest/the-wysiwyg-field#ImageURLFormat

**Comment by fmontes** [comment]
El endpoint: `{{serverURL}}/api/v1/content/resourcelink?identifier=52991186-96a2-4617-9090-23f2081be2cb`

**Comment by erickgonzalez** [comment]
Working as it should, the endpoint returns all the fields and accept the language as a query param, or you can pass the inode instead.

**Comment by bryanboza** [comment]
We need some work here in the responses: 

- If you send an invalid identifier, we need to return a 404 instead 400 
https://www.screencast.com/t/nHkpRfHw

- By default the dotAsset is taking the system host if you don't specify one, then when you get the link we are returning a not useful href... We need to remove this value from the response 
![image](https://user-images.githubusercontent.com/2641437/83679985-86e7ad00-a59d-11ea-8480-5918c7b385f2.png)

**Comment by dsilvam** [comment]
@bryanboza if for a given identifier you can more than one ResourceLinks, then is not ok to expect 404 for a non-existing identifier. You should get 200 and an empty list instead.

**Comment by dsilvam** [comment]
@jdotcms this endpoint should be rename to plural, like the convention is
`resourcelinks` instead of `resourcelink`

**Comment by bryanboza** [comment]
Fixed, new postman test created in the last PR
