### ISSUE TITLE
Containers not resolved properly 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#18438]
### Describe the bug
When creating a brand new site (a blank site) and adding an index page to it. The page is missing content and I see broken container errors in the log.

### Steps to reproduce the behavior:
1. Create a blank site.
2. Add an index page (Using any of the templates from demo site) like **Default Template (demo.dotcms.com)**
4. Now open up the page. you'll see the page looks incomplete also an exception shows up in the logs. 

Here's a gist with the exception I'm seeing:
https://gist.github.com/fabrizzio-dotCMS/e43722b4160f02ba05aa981cfb0e90d3

### Expected behavior
The Page should look complete as it does in the demo site.

### Screenshots
<img width="1373" alt="Screen Shot 2020-05-06 at 09 25 22" src="https://user-images.githubusercontent.com/37148755/81195807-8d254200-8f7b-11ea-86e4-a8aed46de2e9.png">

## Acceptance Criteria

1. Containers must be resolved 
2. The new page should show the contents and containers

**Comment by fabrizzio-dotCMS** [comment]
The  heuristic used to solve the original problem described here https://github.com/dotCMS/core/issues/17749 
Was adding support to relative paths always assuming the current site. 
But in this case, the blank site lacks containers 
And the path used when picked  the template  
points directly to the current host (which lacks containers on it)
VelocityResourceKey [path=/PREVIEW_MODE///blank1/application/containers/default//1562770692396.container
doesn't exists.

When selecting another site's template we should use a direct reference to the other site using the full path or copy the container into the local site.

**Comment by wezell** [comment]
dupe: #18780
