### ISSUE TITLE
GraphQL: bad data in relationship data prevents schema generation

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18443]
Contact me for the dataset to reproduce. 

Steps to reproduce:
- Import db dump
- Try to fetch the schema from a GraphQL Client (e.g. Insomnia) 

Schema won't be able to be retrieved and an NullPointerException will be shown in the logs.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18544

**Comment by freddyucv** [comment]
**Pass Internal QA:** Tested with the client Database, and running several GraphQL request with Insomnia

**Comment by bryanboza** [comment]
Fixed, tested by @freddyucv with a real data and works as expected
