### ISSUE TITLE
Update the Enterprise Message in older screens

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18442]
We need to update the old "get Enterprise" messages in the different screens in the system.  You can see the old messages in community edition here:

- Time Machine
- ESSearch
- Workflows
- Rules
- Publishing queue

These should be updated to look like 

![Screen Shot 2020-05-06 at 4 16 56 PM](https://user-images.githubusercontent.com/934364/81225609-7d2b5380-8fb7-11ea-9c61-101760b0ffed.png)

**Comment by alfredo-dotcms** [comment]
Material Design Icons for pages:

- Elastic Search: find_in_page
- Time Machine: update
- Publishing Queue: cloud_upload
- Workflow: device_hub

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18545/files

**Comment by fabrizzio-dotCMS** [comment]
When Clicking on Request a Trial License from **Configuration > Network** 
the License Request page opens within the iframe.

![Screen Shot 2020-06-15 at 11 53 27](https://user-images.githubusercontent.com/37148755/84689921-f2ffd480-aefe-11ea-9f1b-1cee5e07c69c.png)

anywhere else it opens as a brand new page on the same target window.

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core/pull/18668/files

**Comment by bryanboza** [comment]
When you click in the request a trial license button we need to open this in a new tab, but we are opening this in the same tab, then we los the navigation in the system.

**Comment by alfredo-dotcms** [comment]
https://github.com/dotCMS/core-web/pull/1360
https://github.com/dotCMS/core/pull/18712

**Comment by nollymar** [comment]
Passed internal qa. Now the Request License button triggers a new browser tab

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Now we have this new window working as expected.
