### ISSUE TITLE
GraphQL: Related content always returned in default language

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18444]
This is regardless of the language specified in the lucene query.

Steps to reproduce:

1. Create two content types and a relationship field from the first to the second. 
2. Create content for both types in a second language.
3. Query the collection, including the relationship field, for the first type using a lucene query `(query:"+languageId:{secondLangId}")`

The related content needs to be returned in the provided language

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18551

**Comment by freddyucv** [comment]
Pass Internal QA:
Test:

- Create two content: A and B
- A with one field: text_1
- B with two field: text_2 and a_b (relationship field)
- Create content for A and B in spanish, and related them
- With Insomnia request:
{
  BCollection(query:"+languageId:2") {
    text2
    aB {
      text1
     }
  }
}

**Comment by freddyucv** [comment]
**Passed Internal QA**: Tested with this steps

https://github.com/dotCMS/core/issues/18444#issue-614120307

**Comment by bryanboza** [comment]
Fixed, tested on relase-5.3.2 // Postgres // Insomnia
