### ISSUE TITLE
Remove db config from shipped context.xml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18440]
dotCMS 5.3 expects the db to be configured in the file `/ROOT/WEB-INF/db.properties`.  We should not have db config in the context.xml any longer.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18441

**Comment by nollymar** [comment]
**Note to Doc:** As we will not continue shipping with `context.xml`, this documentation should be updated: https://dotcms.com/docs/latest/database-configuration#Configuration.

Related to: https://github.com/dotCMS/core/issues/17843

**Comment by nollymar** [comment]
**Note to QA:** Please test these scenarios after making sure : 
1) Test using local environment: Make sure the `context.xml` doesn't exist in META-INF. Start the server with your `db.properties`  and check the logs. The server should run without issues

2) Test using docker: Generate a local dotcms image and run `02-single_node` implementation using this image. Take a look at the dotcms log. Tomcat shouldn't throw any exception

**Comment by dsilvam** [comment]
Passed QA: Neither locally nor on docker is the context.xml error happening anymore.
