### ISSUE TITLE
Card View on iPad resolution

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18456]
We have some problems on iPad resolution after those changes, we need be able to use this view on this devices, right now we have this:

![IMG_0390](https://user-images.githubusercontent.com/2641437/81448739-213e0780-913c-11ea-9bb3-b9dad0a2966b.PNG)

- With the list view looks cut, but the vie icons looks misaligned
- The card view is not working, we are unable to see the image thumbnail
- we cut the “…” button from the general view

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/dotcms-webcomponents/pull/31/files
https://github.com/dotCMS/core/pull/18508/files

**Comment by alfredo-dotcms** [comment]
@QA: Based on a discussion with @fishsmith, the min width supported by the app is 1024px, so when login with small devices they should be used on landscape mode.

- the VIEW button (the one used to switch between card view and list view) must be moved, after the "showing 1-40 of ..." label

**Comment by fmontes** [comment]
Is merged and built

**Comment by nollymar** [comment]
**Passed internal QA:** Tested on an iPad and works fine on a landscape layout. 

![IMG_06B94CAAFC77-1](https://user-images.githubusercontent.com/8741395/82238643-3fa2c080-98fd-11ea-94b8-36c8e4ee7b27.jpeg)


Additionally, it was tested on Safari.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.0 // Postgres //FF. Now we support this devices but just in landscape mode.
