### ISSUE TITLE
ESQueryCache never inits in a cluster

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18458]
If you are running dotCMS in a scaleable cluster, the ESQueryCache never inits.  I believe this is because the boolean value is a `static final` and is probably getting inited before a license has been applied to the server (from a license pack).

### Look, no cache

![Screen Shot 2020-05-08 at 10 26 26 PM](https://user-images.githubusercontent.com/934364/81461708-aa286380-917b-11ea-810e-03ed50755fdc.png)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18459

**Comment by nollymar** [comment]
Passed internal qa
