### ISSUE TITLE
[Push Publishing] : Exclude and Include Patterns might fail to push

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18452]
Found when working on Support: [101210](https://dotcms.zendesk.com/agent/tickets/101210)
Originally reported in: [99603](https://dotcms.zendesk.com/agent/tickets/99603)
Reproducible in all versions of dotCMS.

When troubleshooting a Push Publishing problem, I ran into a Hotfix Plugin that solved a Static Push Publishing bug for the specified customer. The Bundler classes are:

- `FileAssetBundler`
- `HTMLPageAsContentBundler`
- `URLMapBundler`
- `BundlerUtil`

They're part of this Hotfix Plugin: https://github.com/dotCMS/support/commit/08bc0fff436c37eb23cecfdbf3283a9a90ffed08#diff-c7bdd23aa16a538c13c04b384858ab18

Based on feedback from the developer of the plugin, the code changes fixed a problem where files an HTML Pages failed to push because they had blank spaces in their path or name. It's very important for the R&D Team to analyze this fix and consider whether the code changes must be included in our core code or not. This is specially important as Bundler classes affect both Push Publishing and Static Push Publishing.

### Steps to reproduce the behavior:
1. Set up both Push Publishing and Static Push Publishing environments.
2. Push files and/or HTML Pages containing blank spaces in their path or name.

### Expected behavior
Both Push Publishing and Static Push Publishing need to work.

## Acceptance Criteria

1. Unit test

**Comment by nollymar** [comment]
The fix was not applied because I was not able to reproduce this issue. I pushed successfully (static and dynamic push) a full site with folders, file assets and page assets with blank spaces in their names.

**Comment by dsilvam** [comment]
Passed QA: 
* Able to pushed file whose name contained spaces
* Able to pushed folder whose name contained spaces
* Able to push file whose named contains spaces under a folder whose name contained spaces
