### ISSUE TITLE
XSSPreventionWebInterceptor can be bypassed

### ISSUE THREAD

**Issue by Frint0** [dotCMS/core#18463]
### Description:
The default protected paths are stored in the `XSS_PROTECTED_PATHS_DEFAULT` variable. One example entry is `\\A/html/`. All an attacker needs to do is append another forward slash to bypass this simple filter. Hence no `Referer` header will be required and a XSS payload or CSRF can be achieved.

### More Information Here:

https://pwnable.club/cve-hunting-on-dotcms#failed-xss

**Comment by Va1a** [comment]
Thank you for helping make dotCMS safer!! 🔥🔥🔥🔥🔥🔥

**Comment by wezell** [comment]
@Frint0 thanks for the report!  This has already been brought to our attention by another researcher and is fixed in the upcoming 5.3.0 release of dotCMS.  Fix is found here #18354 

I'm going to close this issue in favor of the one that has the work on it.
