### ISSUE TITLE
Custom portlets are removed from the menu

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#18464]
### Describe the bug
We have some OSGi plugins that add a portlet to dotCMS. We noticed that these portlets sometimes disappear since we upgraded to dotCMS 5.1.x. I investigated this and noticed that when a portlet is removed (for instance when the framework restarts or when you redeploy a plugin) that the portlet is also removed from the menu. You can see that in https://github.com/dotCMS/core/blob/68a3c9169f21015f18cfc43f7bf1acefcf87946c/dotCMS/src/main/java/com/dotmarketing/business/portal/PortletFactoryImpl.java#L151. This code is called by unregisterServices() in the GenericBundleActivator.

The portlet should not be removed from the menu when the plugin framework restarts, or even when you remove the plugin. 

I think removing line 151 in the PortletFactoryImpl solves the issue.

### Steps to reproduce the behavior:
1. Create a OSGi plugin that adds a portlet and which calls unregisterServices() when stopping
2. Deploy the plugin
3. Add the portlet to the menu (make sure you can see it in the menu)
4. Restart the plugin framework (or remove the plugin)
5. Refresh the page. The portlet will have been removed from the menu.

### Expected behavior
The plugin should remain in the menu until it is removed in the Roles, Tabs & Tools menu.

**Comment by wezell** [comment]
@Xander-Steinmann what version are you running?  Changes were made here: #17127 , in 5.2.0, that should prevent this behavior?

**Comment by Xander-Steinmann** [comment]
I was running version 5.1.6 and it seems that this is indeed fixed in 5.2.x. Thanks!
