### ISSUE TITLE
javaScriptify method can be escaped -> leads to XSS 

### ISSUE THREAD

**Issue by ghost** [dotCMS/core#18462]
### Description:
The `javaScriptify` method in `dotCMS/src/main/java/com/dotmarketing/util/UtilMethods.java` does not escape `\`, so an attacker can escape a string and execute Javascript code to achieve XSS.

### More Information Here:

https://pwnable.club/cve-hunting-on-dotcms#failed-xss

**Comment by Va1a** [comment]
Thank you for helping make dotCMS safer! 🔥🔥🔥
