### ISSUE TITLE
[core] : Key Value field is not returning data in correct order

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18479]
Reported via Support: [101274](https://dotcms.zendesk.com/agent/tickets/101274)
Reproducible in dotCMS 5.2.8, and latest master (5.3.x)

Key/Value fields are not only used to store configuration or internal values of a Contentlet. They can also be used to display important information to users; thus the importance of keeping the order in which data is entered.

### Steps to reproduce the behavior:
**NOTE: Please reach out to Jose Castro if the issue is not reproducible using Starter data.** 
1. Create a Content Type with a key/value field, e.g., `My CT`.
2. Add at least 8 Key/Value entries, and save the contentlet. It's VERY IMPORTANT that the entries are real words and not random text. For example:
```
Power (W)
Output Voltage (VDC)
Output Current (A)
Voltage Input (VAC)
Operating Temperature (ºC)
Dimensions L x W x H (mm)
Airflow
Input Connector
```
3. Re-open the content, and see how the order of the values has changed.

### Expected behavior
The order of Key/Value fields must be kept.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18480

**Comment by alfredo-dotcms** [comment]
Tested and looks fine
![image](https://user-images.githubusercontent.com/37185433/82266400-d20b8a00-9926-11ea-8401-5792ddc5781b.png)

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
