### ISSUE TITLE
UI problems adding content types with reserved names 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18474]
After the last changes now the endpoint is returning the response with the error, but when you try from UI, we are closing the new content type form and showing the error; After you close the pop-up we redirect to content types portlet. 

We need to redirect to the `add new content type` form again in order to update the name and create the content type. And not exit entirely from the flow

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18382#issuecomment-626014197_

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1406

**Comment by fabrizzio-dotCMS** [comment]
upon entering a reserved word such as a file or host (regardless of casing) the error dialog shows up and then the new CT dialog re-appears... Which is expected.  However, as a side note, I was able to reuse names such as Blogs.Even. though there was another CT already using that name.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
