### ISSUE TITLE
NPE trying to a content from binary field in other language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18485]
We have a JSP error and this causes an NPE error. This when you have a content type with a binary field, and after adding a new piece of content in the default language you try to create a new version of the content in another language 

Log: https://gist.github.com/bryanboza/7791f874605d0a9d9f16a69fbac66602

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new content type with a text and binary field 
3. Add a new piece of content 
4. Try to create the Spanish version of the created content 

### Expected behavior
We need be able to add multiple versions without problems 

### Desktop (please complete the following information):
Tested on release-5.3.0 // MySQL // FF

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18486/filesl)

**Comment by bryanboza** [comment]
Fixed, tested on mater // Postgres // FF
