### ISSUE TITLE
[core] : The Drop Old Assets Versions tool fails when deleting many records

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18494]
Reported via Support: [101256](https://dotcms.zendesk.com/agent/tickets/101256)
Reproducible on dotCMS 3.6.0, and latest master.

As part of their upgrade, the customer is carrying out several cleanup tasks on their dataset. This includes getting rid of very old versions of dotCMS versionable objects via the **Drop Old Assets Versions** tool. Our code is presenting performance issues because of the high number of records to delete. This is causing the DB connection socket to close before finishing the cleanup operation.

### Steps to reproduce the behavior:
**NOTE: This probably needs customer data to be reproducible in order to simulate old versions along time.** 
1. Set up a dotCMS instance with a lot of information and old versions.
2. Go to **Maintenance > Tools > Drop Old Assets Versions > Select a recent date > Click Execute**, and let the background process run.
3. Monitor the `dotcms.log` and, after a while, you'll see a `socket closed` stack trace.

### Expected behavior
The code must be able to handle the deletion of old asset versions without regards to the amount of data to be deleted.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18507

**Comment by erickgonzalez** [comment]
**Note to QA:** The best way to test this is with the full starter since it has old versions of contentlets.

**Comment by bryanboza** [comment]
Fixed, tested with an old starter and I'm unable to reproduce the problem in the last master version.
