### ISSUE TITLE
Add edit properties image button

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18496]
As a user I want to be able to edit the properties of the inserted image in the WYSIWYG.

### Describe the solution you'd like
Let's add a new button next to Edit

<img width="949" alt="Screen Shot 2020-05-14 at 11 42 44" src="https://user-images.githubusercontent.com/751424/81967825-bdeb2400-95d8-11ea-92c5-423d986ab3e8.png">

### Additional context
The old button that opened the "properties" dialog will be opening the file browser (there is an issue for it)

## Acceptance Criteria
1. Add the new "Properties" button
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/18506

**Comment by erickgonzalez** [comment]
Needs work. Tested on master and the menu is not showing.

**Comment by bryanboza** [comment]
We need some work here: 

- If you click in the properties, and try to select another image and you doble click, we are inserting the image twice 
SC: https://www.screencast.com/t/D8oq0jYkSycF

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF
