### ISSUE TITLE
Open File Browser with one click from WYSIWYG

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18498]
As a user I want to be able to browse for image from the WYSIWYG really quick.

### Is your feature request related to a problem? Please describe
Right now, if you want to open the file browser is a two click process:

<img width="547" alt="Screen Shot 2020-05-14 at 12 05 11" src="https://user-images.githubusercontent.com/751424/81969484-4ec2ff00-95db-11ea-9ac9-5c3b9656a07b.png">

### Describe the solution you'd like
We need to open just in **Click 1**

### Additional context
There was some work being done related to this in this issue: https://github.com/dotCMS/core/issues/18496

## Acceptance Criteria
1. Open the file browser with one click
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested in release-5.3.2 // Postgres // FF
