### ISSUE TITLE
Create User on the UserResource

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18526]
We need to have the ability to create an user and assign permissions by REST

1) the only admin user must be able to create users
2) the user may have the following attributes at least:
    
    - UserId. (Optional, if this is pass and the id is not being used, could use it to create it, otherwise throw an error)
    - Name
    - Last Name
    -  Email
    - char[] password
    - frontend: boolean (false by default)
    - backend: boolean (false by default)
    - Roles: []                    (empty by default)
 
Note: list of roles to add to the user

**Comment by erickgonzalez** [comment]
we have a plugin that already do this https://github.com/dotcms-plugins/com.dotcms.user-registration-app might want to revisit and include in core.

**Comment by erickgonzalez** [comment]
Taken care of here https://github.com/dotCMS/core/pull/24997/files#diff-4e600e002bbe0d28d6bc0a7d639c8814c662423598207e815f6312691d2ff775
