### ISSUE TITLE
Error running upgrade task Task05200WorkflowTaskUniqueKey

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18524]
Using customer data, I got this error trying to upgrade from 5.2.3 to 5.3.0: 

```
10:37:29.985  ERROR db.HibernateUtil - ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
java.lang.NullPointerException
	at com.dotmarketing.startup.runonce.Task05200WorkflowTaskUniqueKey.executeUpgrade(Task05200WorkflowTaskUniqueKey.java:54)

```
Apparently, this occurs when the `language_id` column in the `workflow_task` table is null.

We should try to set the `language_id` to the default language when `language_id=null` before executing the constraints

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18845

**Comment by freddyucv** [comment]
**Passed Internal QA:** Tested with the follows steps

1. Running the follow statement in data base

```
update workflow_task set language_id=2, webasset = '388f8690-a64f-4982-9c81-cf6f3ec5ea30' where webasset = '388f8690-a64f-4982-9c81-cf6f3ec5ea30' or webasset = '7e83ba27-a5d4-4a46-a3d9-7cfc83afe460'

update workflow_task set language_id=null where webasset = 'bfd84905-4c01-405d-89f0-e09d81a7a82e'
```

To have duplicate register with the same language_id and webasset and register with the language_id equals to null

2. Used the web service to run the upgrate task

```
 POST http://localhost:8080/api/v1/upgradetask
{
	"upgradeTaskClass":"com.dotmarketing.startup.runonce.Task05200WorkflowTaskUniqueKey"
}
```

**Comment by bryanboza** [comment]
Fixed, tested upgrading from dotcms_4.x series to dotcms_5.3.5 // Oracle 12c
