### ISSUE TITLE
[core] : Get related parents fails when related content is archived

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18525]
Reported via Support: [101318](https://dotcms.zendesk.com/agent/tickets/101318)
Reproducible from dotCMS 5.2.0, until latest master (5.3.0)

### Describe the bug
The Content API is failing when retrieving the related parents of a given Contentlet based on its corresponding Relationship. The execution flow is as follows:

1. The user opens up a Contentlet for editing.
2. The system used the API to retrieve the Contentlet's data, including its related Contentlets.
3. The API queries the ES Index for the related Contentlets. That is, the related Identifiers as Strings.
4. Such Identifiers are used to instantiate the Contentlets. However, **if the current Version Info is not found in the database, or if it's currently archived, a null object is passed down**.

This null object is causing an NPE when opening the Contentlet Edit modal.

### Steps to reproduce the behavior:
NOTE: This was reproduced using the customer's dataset. The steps might change or depend on the specific test data.
1. Create two Content Types: `Parent CT`, and `Son CT`, and relate each other.
2. Add a Contentlet of type `Son CT`, and a couple of `Parent CT` Contentlets. Relate the `Son CT` Contentlet to the parents. Make sure you can edit the `Son CT` content without issues.
3. Archive on of the `Parent CT` Contentlets, and then open up the `Son CT` content.
4. You'll see an error message in the Contentlet Edit modal.

### Expected behavior
Our code needs to handle situations in which the Version Info does not exist, or is archived.

## Acceptance Criteria

1. Multilanguage
2. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18535

**Comment by nollymar** [comment]
**Passed Internal QA**. This change was tested through an IT. There isn't an easy way to test it functionally

**Comment by wezell** [comment]
Legacy Relationships are not displaying

**Comment by nollymar** [comment]
This PR fixes the issue @wezell commented: https://github.com/dotCMS/core/pull/18648

**Note to QA:** Please verify legacy relationships are listed correctly (with/without archived related content) in both sides of a relationship (parents and children)

**Comment by erickgonzalez** [comment]
Tested working as it should. The content lists correctly using legacy or new relationships, either the content (parent or child) was archived or not.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF and seems after the changes everything is working as expected
