### ISSUE TITLE
Create new message service

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18531]
### This new message service will replace the current `dot-message.service`

1. Fetch all the messages in the login screen using the [new api](https://github.com/dotcms/core/issues/18530)
2. Store them in IndexedDB using https://www.npmjs.com/package/ngx-indexed-db
3. Create a method that receive a key and return the message

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1346
