### ISSUE TITLE
Create endpoint to load all the messages keys

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18530]
Create an endpoint that we can pass the language (string) and return all the messages keys, if no lang is passed return the messages keys for the default lang

Endpoint:
```
/api/v2/languages/{language}/keys
```
E.g:
```
/api/v2/languages/en_us/keys -> english messages
/api/v2/languages/it/keys -> italian messages
/api/v2/languages/default/keys -> default messages (dotcms ships english messages)
/api/v2/languages/1/keys -> 404 language with that locale not exists
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18548

**Comment by erickgonzalez** [comment]
PR2: https://github.com/dotCMS/core/pull/18615

**Comment by john-thomas-dotcms** [comment]
`/i18n` as a name doesn't really say anything about what the endpoint does.  Can we call it `/keys` (e.g. `/api/v2/languages/{language}/keys`) or something like that instead?

**Comment by wezell** [comment]
@john-thomas-dotcms totally agree

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18631 for the feedback
