### ISSUE TITLE
Popping open tail log window should resize with the popup window.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18556]
When you are tailing logs in dotCMS using the tail log window, you can resize the window, which is nice.  The issue is that when you resize the window, it will resize in width but not in height.  

The log box should resize as the window resizes,  something like `position: absolute;left:5px;right:5px;top:5px;bottom:5px; `

![Screen Shot 2020-05-27 at 12 28 04 PM](https://user-images.githubusercontent.com/934364/83047174-ff86c080-a015-11ea-8045-a7202c444fb7.png)

**Comment by john-thomas-dotcms** [comment]
It would also be really, really nice if you could change the number of lines to tail, so you could look back a little farther without having to ssh to the server...

**Comment by jcastro-dotcms** [comment]
It would also be great if we could scroll up too. As it is right now, if you scroll up and new logging is being loaded, the scroll goes back to the latest position and you can't go back up anymore.

**Comment by wezell** [comment]
The ui should be that if the user scrolls up, then the follow "unselects".  To reenable follow, the user should have to check the checkbox again.

**Comment by fmontes** [comment]
Log content needs to be 100% height of the window

**Comment by hmoreras** [comment]
to configure logs locally, follow: https://dotcms.com/docs/latest/dotcms-log-audit-logging#TailLogLocations 
replace the path in `TAIL_LOG_LOG_FOLDER` with the absolute path.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/dotcms-dojo-theme/pull/72 and https://github.com/dotCMS/core/pull/18803

**Comment by erickgonzalez** [comment]
Tested and working as it should. Now:

- When scrolling up, unselects the `follow` checkbox.
- When resizing the window, it will resize in width and in height.

**Comment by bryanboza** [comment]
After the last changes not the functionality is working ok, but the popup looks cut at the top... 
Here the SC: 
![image](https://user-images.githubusercontent.com/2641437/87828600-8730c480-c83a-11ea-8b57-5ffe49b9f479.png)

We need some styling improvements here,  maybe add the logo or something in the header

**Comment by wezell** [comment]
Guys, this issue has grown from what should have been a 1 line css change to taking what, a month?  Support uses this screen every day and I keep waiting to see the improvement and now it looks like its not even going to make it into 5.3.5?

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/18934 this add spacing in the top of the buttons in the popup, as Bryan suggest. Any other suggestion we should treat it as a new issue/improvement so we don't feel this took longer that actually took. My two cents.

**Comment by bryanboza** [comment]
Fixed, now this window fits correctly, all the other improvements will be moved to #18983

**Comment by bryanboza** [comment]
Fixedm tested on release-5.3.5 // Postgres // FF
