### ISSUE TITLE
File as Container can only be added once to a template

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18558]
In 5.3.0, we added the ability to link to file containers across hosts.  The issue is that this now limits us to only allowing one container of that type on any given layout.  If you add more than 1, the second instance will disappear.

Old school containers work as expected.

**Comment by bryanboza** [comment]
We need some work here: 

We have two cases here, to reproduce: 

- Create a file-based container, and create a template and add the same container 3 times.
- Create a new page using this container
- Add 3 different pieces of content 1 to each container 
- Now to the layout editor and add two new ones and use the same container in both. 
- Save it, and go to the content editor 

**Here the first case, we are auto-assigned content to the new containers** 

- Now, Go to the layout editor again and add two more with exactly the same container
- Save again and go back to edit 

All the previous ones lose the content

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18570

**Comment by freddyucv** [comment]
Note to QA: test also

#17749

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.1 // Postgres // FF
