### ISSUE TITLE
Create a Resource to upload Bundles

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18563]
Create a Resource that translate the logic from RemotePublishAjax, it will be basically an endpoint to upload a bundle.

+info: https://dotcms.com/docs/latest/remote-publishing-bundle-api#remote-publishing-bundle-apidocumentation-for-the-dotcms-con

**Comment by dsilvam** [comment]
Make uploadBundle functionality the priority here

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18760

**Comment by dsilvam** [comment]
@jdotcms suggests splitting this into two different methods; one for sync; one for async.

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/18862

**Comment by erickgonzalez** [comment]
When there is no license, should throw `403 Forbidden`, now it's returning 500. We should add an option to the WebResource to validate license `requireLicense`.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18923 for feedback

**Comment by erickgonzalez** [comment]
Working as it should, now returns 403 when you try to use the resource without a license.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
