### ISSUE TITLE
Add cors filter to graphql servlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18567]
We need to add our standard cors filters to the DotGraphqlServlet.  The pattern should be the same as our JAX-RS Cors filter- use the default one unless it has been specifically configured for graphql.  You can see the logic here in this plugin:

https://github.com/dotcms-plugins/com.dotcms.graphql.cors/blob/master/src/main/java/com/dotcms/graphql/GraphqlCorsWebInterceptor.java#L48

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18568

**Comment by fmontes** [comment]
Tested in the working version of the dotcms-spa against starter
