### ISSUE TITLE
Recurrent workflow error using the full starter 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18566]
When you start a fresh instance using the full starter, we have a recurrent error on the logs related to the some workflow 

Here the WARN: https://gist.github.com/bryanboza/1d03f51d545a7de268880eb073a0433e

### Expected behavior
We need continue supporting this starter 

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
Related to: https://github.com/dotCMS/core/issues/18591
