### ISSUE TITLE
Unable to import starter with XML 1.1 characters in it

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18576]
XML spec disallows certain UTF characters, depending on if it is XML 1.0 or XML 1.1.  If a customer creates content that uses a valid XML 1.1 UTF character, we are unable to import that starter into the dotCMS as the importer throws up.

We use XStream to serialize the lists of content and by default XStream does not write an XML prologue, e.g. `<?xml version="1.1" encoding="UTF-8"?> at the top of its generated files.  This causes the XML deserialization to fail.  We have hit this issue with Push Publishing and the bundler and we use a class called `DotPrettyPrintWriter` to serialize our PP xml.  We need to use the same class when we write our starter .xml

@jcastro-dotcms has an example of a starter that we are unable to import if you need to test.

**Comment by wezell** [comment]
PR: #18584

**Comment by fabrizzio-dotCMS** [comment]
I was able to reproduce the error by importing a Customer starter (Ask me which one if that is of your interest). 
I was able to verify that once the re-index had finished there were 12 records left with errors.  
That didn't prevent the re-index process from finishing successfully and make the newly generated index the default-one.  

About the resulting errors, they can be downloaded in JSON format through the new endpoint 
http://localhost:8080/api/v1/esindex/failed
Once the user dismisses those records on the UI they're no longer available for download. 
That's all good. 
All the other functionalities available on the re-index tab continue to work as expected. 
you can still delete or deactivate indices as well as check their health status. 

All the other options available through the Reindex drop-down continue to work as they used to. Though they do not use the progress-bar.

A couple of small  details: 

- The list of failed records always comes back in a different order when requested. (Not a big deal)
- The field server-id returned in the JSON with the failed records is always null.

![Screen Shot 2020-06-16 at 17 51 35](https://user-images.githubusercontent.com/37148755/84840213-2411ff00-affc-11ea-8c91-f36cc4885e15.png)

**Comment by bryanboza** [comment]
Fixed, testes with the provided starter and I'm able to reindex and continue without problems
