### ISSUE TITLE
Relationships cache on receiver out of sync after deleting a relation and pushing content

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18571]
### Describe the bug

When:
* Two content items (items A and B) both have relationship fields to each other, and
* A relation between the content items is deleted from one content item (item B), and
* That content item (item B) is pushed,

Then:
* On the receiver, the relationship no longer shows as existing on the content item which was pushed (item B),
* But the relationship does still show as existing on the other content item (item A).

A Relationship cache flush on the receiver is necessary to solve the problem.

### Steps to reproduce the behavior:

On the sender:

1. Create a content type with a self-relationship (both parent and child relationship fields).
2. Create a relationship between two content items.
3. Push both content items to the receiver.
4. On the child content item, delete the relationship.
5. Push just the child content item to the receiver.

On the receiver:

6. View the parent and child content items.
    * **Result:**
        * On the sender, neither the parent nor the child shows a relationship to each other.
        * But on the receiver, the child shows no relationship, but the parent still shows it's connected to the child.
7. Flush the Relationship cache.
8. View the parent and child content items.
    * **Result:** The relationships on both content items now match those on the sender (neither show as related to each other).

### Expected behavior

On the receiver, the relations on both content items should be updated when only one content item is pushed.

### Desktop (please complete the following information):

* OS: Win 10 Pro
* Browser: Chrome
* Version: dotCMS 5.3.0

### Additional context

* This seems like it might be a common problem when relations are deleted.
    * I expect it won't happen when relations are added, since the new relation will likely get inserted into the Relationship cache on the receiver.  (But we should check to be sure).
* This is not an issue with one-sided Relationships (where only one Content Type has a Relationship Field for the relationship).
    * But, although I found this with a self-relationship, I suspect it happens with any relationship when a relation is deleted **and** when both content items have Relationship Fields for the relationship.
* Users updating relationships and pushing them often do not have admin permissions on the receiver.
    * So as it stands, fixing this problem requires that a content creator on the _sender_ contact an admin on the _receiver_ (not good, especially in large organizations).
* The simplest solution is to automatically flush the Relationship cache on the receiver when it receives any content which contains a relationship.
    * But this could cause performance issues on large sites with lots of related content, so I think we need a more targeted solution than that.
    * For example, it might make sense to handle this when building the dependencies on the sender, rather than on the receiver when it gets the pushed content.

## Acceptance Criteria

1. Ensure that pushing either content item causes relationships on both to be updated properly on the receiver.
2. Limit the performance impact on receiver.
3. Verify proper operation after add, delete, and delete+add of relations.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/739

**Comment by dsilvam** [comment]
Passed Internal QA: After going through the mentioned steps the relationship is not shown neither in the parent nor in the child content

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. Testes on release-5.3.6 // Postgres
