### ISSUE TITLE
DotCMS uses incorrect language when adding new content

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#18575]
### Describe the bug
When you are adding content to a page that does not have the default language (or language with id 1) then adding content on a page will automatically set the language id to 1. This is particularly frustrating when you have a site that does not have English and does not default to English. Because after adding a new piece of content the content will 'disappear' since it is not the correct language and will not be visible. This is very confusing for our clients and has caused a couple of 'what the...' moments for our developers as well.

### Steps to reproduce the behavior:
1. Go to demo.dotcms.com and log in
2. Go to the website browser
3. Right-click on a folder and add a new page
4. Switch to Espanol (ES)
5. Create the page with title "Test ES" and url test-es
6. Edit the page
7. Click on the add content + and select "content"
8. Click on the + select "rich text" to create a new piece of content for the page
You will now see that the new piece of content is English (US) and not Spanish (ES).

### Expected behavior
I would expect the system to use the currently selected language. 

Even though it seems to work fine on the demo site is actually doesn't when you change the default language. That's because the code explicitly uses languageId 1 here:
https://github.com/dotCMS/core/blob/ce5fa71080983fd92a0a70b19e754f7b22c25c67/dotCMS/src/main/webapp/html/ng-contentlet-selector.jsp#L124

That line should be fixed. Possibly it can be replaced with "&lang=" + getSelectedLanguageId();

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)

**Comment by erickgonzalez** [comment]
Also let's check with the Content Pallette.

**Comment by erickgonzalez** [comment]
PR: #25615

**Comment by erickgonzalez** [comment]
Needs Work Still reproducible in `master_8d30d6e_SNAPSHOT`

**Comment by bryanboza** [comment]
This was fixed just adding a new piece of content with the regular process, we have pending when you try from the content. New case opened here #25900
