### ISSUE TITLE
Permission Tab showing for user without the "EDIT_PERMISSIONS" permission

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18583]
If you create a role that does not include "Edit Permissions" and grant it to a limited user, they can still see the permissions tab.  This tab should be hidden from the user if they do not have "EDIT_PERMISSION" on the content.

**Note**  they cannot see or edit the permissions, which is good.  The bug is that the tab is displayed.

![Screen Shot 2020-06-03 at 9 07 54 AM](https://user-images.githubusercontent.com/934364/83640257-e207a880-a579-11ea-8c16-10f6e0f8952d.png)

![permission-tab](https://user-images.githubusercontent.com/934364/83640284-ec29a700-a579-11ea-8659-eb2dcb1fcd4d.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19027

**Comment by nollymar** [comment]
Note to QA: Please, test this fix works when you add/edit content too

**Comment by dsilvam** [comment]
Passed Internal QA: Permissions tab not shown on content edit screen if user does not have Edit Permissions. However, the Permissions tab is still shown on Content Types. Not sure if this should also we covered by this issue @wezell @alfredo-dotcms

**Comment by bryanboza** [comment]
As @dsilvam  says in their comment, we still showing the edit permissions tab in the content type and also in the categories portlet.  We need some work here: 
![image](https://user-images.githubusercontent.com/2641437/90583094-8f0ebc00-e18c-11ea-8b83-18f8c0392c4f.png)

**Comment by alfredo-dotcms** [comment]
PRs:
`core-web` https://github.com/dotCMS/core-web/pull/1418
`core` https://github.com/dotCMS/core/pull/19138

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
