### ISSUE TITLE
Apps - Backend: Editing a configuration wipes out the API Secret value

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18587]
When I edit a configuration for site, if I modify any field except the API Secret field, the configuration is saved with my changes but the API Secret value is wiped out.

**Steps to reproduce:** 

1. Add a new configuration for a site that contains these fields: 
    a. Enabled (Boolean)
    b. API Key (Text)
    c. API Secret (Hidden Text)

2. Edit the configuration modifying the API Key and save it.
3. Try to edit the configuration again and notice how the API Secret value disappears

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18713

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
