### ISSUE TITLE
Apps - UI: There is no way to go back to the main Apps screen 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18586]
As a user, I need a breadcrumb that allows me to go back to the main Apps screen that shows all the configurations. Currently, the only way to do that is using the nav tool menu on the left

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1341

**Comment by fabrizzio-dotCMS** [comment]
The bread crumb is there. I can click on any single app and would open the next level in the bread crumbs path. I can always click on the parent element Apps and it would take me to the apps listing.

**Comment by nollymar** [comment]
I'm getting these errors and the breadcrumb is not loading: 

<img width="1667" alt="Screen Shot 2020-06-17 at 2 18 04 PM" src="https://user-images.githubusercontent.com/8741395/84940480-82df8300-b0a5-11ea-8689-1bf71c57fd62.png">

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1353

**Comment by nollymar** [comment]
**Passed internal qa:** The error I had reported above has been fixed

**Comment by bryanboza** [comment]
Fixed, now we have the breadcrumb and works as expected. Tested on master // Postgres // FF
