### ISSUE TITLE
Content Type/ Edit Bug

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18595]
When you add to a content type a default action (by rest), which is not the NEW (for instance PUBLISH), the edit button stop working on the angular content type portlet

Set Default action by REST: 

PUT http://localhost:8080/api/v1/workflow/system/actions

`{
	"actionId":"<contentTypeId>",
	"contentTypeVariable":"fileAsset",
	"systemAction":"PUBLISH"
}`

**Comment by fmontes** [comment]
Catch the error.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1352

**Comment by bryanboza** [comment]
Fixed, after set this default action, now we are able to edit the content type without problems
