### ISSUE TITLE
Apps: Test Rest API endpoints

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18593]
Using this documentation: https://auth.dotcms.com/devwiki/apps-rest-api , verify the Apps endpoints work well

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/18743/

**Comment by fabrizzio-dotCMS** [comment]
If you have a parameter that has a default value set in the yml App descriptor. then you change the value and then you remove that value via DELETE: http://localhost:8080/api/v1/apps/ rest endpoint. The default value will continue to be returned that is desired behavior.

The first point is the intended behavior. Waiting for @wezell's confirmation

**Comment by dotcms-corp** [comment]
That is right, the default value should be returned if there is no value

**Comment by nollymar** [comment]
**Passed internal qa:** After the fix, the `upload-app` endpoint returns a `400-Bad Request`  when yml file is duplicate

<img width="1280" alt="Screen Shot 2020-06-25 at 4 31 20 PM" src="https://user-images.githubusercontent.com/8741395/85797501-607ee280-b701-11ea-85e8-6ec5a8dcd39a.png">


**Note:** The first case reported by @bryanboza wasn't tested because it wasn't considered an issue.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // Postman and now we have the right response codes
