### ISSUE TITLE
Create `Page` GraphQL Field with first level properties 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18599]

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/732

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18760

**Comment by dsilvam** [comment]
Note to QA: 
All expected properties are in the postman collection/folder `GraphQL/Page API`

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // MySQL
