### ISSUE TITLE
ReindexThread always runs - never stops

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18605]
This Thread is doin a Database request two times for second here:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java#L179

I think is better is it. just is Paused when not exists reindex to proccess and start it again when a reindex is push into  the queue, here could be a good place:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ContentletIndexAPIImpl.java#L581

Also the ReindexThread can try to procces the same reindex more than once, it keep a 'lastIdIndexed' to know witch content is already been proccesing:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexQueueFactory.java#L274

but after a empty response from the database this index is set to 0

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexQueueFactory.java#L283

so it possible that meanwhile wait for a put reindex request the ReindexThread awake again and try to reindex the same contentlet again (it happend to me locally several times)

### Describe the solution you'd like

I think the ReindexThread should pause after finish to send all the reindex request, and if a new reindex is register or a reindex fail it thread is start again.

**Comment by wezell** [comment]
Important note -  a dotcms server can/should handle not just locally saved content, but content that has been imported by other servers in the cluster - indexing should be distributed across dotCMS nodes in a cluster which for the most part it is.

If we were to revisit this code, the next step would be to leverage a multi-consumer queue (at least once) like kafka or redis streams to handle the queuing/de-queuing and retrying of the content to be indexed.

**Comment by wezell** [comment]
> Important note - a dotcms server can/should handle not just locally saved content, but content that has been imported by other servers in the cluster - indexing should be distributed across dotCMS nodes in a cluster which for the most part it is.
> 
> If we were to revisit this code, the next step would be to leverage a distributed multi-consumer queue (at least once) like kafka or redis streams to handle the queuing/de-queuing and retrying of the content to be indexed.

Such a queue implementation will be covered in this issue
https://github.com/dotCMS/core/issues/18149

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19470

**Comment by nollymar** [comment]
**Note to QA:** Please test the creation/edition of pieces of content. Besides, it's important to run a full reindex, especially in a clustered environment

**Comment by fabrizzio-dotCMS** [comment]
I did set up a two-nodes cluster (node-1, and node-2) on my local machine. 
Then I tested the following scenarios:

1. I edited single pieces of content and verified the changes became visible for both nodes. No problem. The edition of one single piece of content seems to be processed by the same node issuing the reindex operation.

2. I made modifications on content-types that already had a number of pieces of content and I can tell that the reindex operation isn't necessarily attended by the node issuing the operation. The changes in the pieces of content are picked by the two nodes smoothly.

3. I tested bulk workflow actions. Firing them from the content search portlet and I was able to verify the ReindexThread workload is distributed on both nodes (Or at least the movement on the logs give me such an impression).  
I see entries like :
```
13:46:16.438  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 5590/6/12
13:46:16.463  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 5600/5/10
13:46:16.479  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 5604/2/4
13:46:16.496  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 5608/2/4
13:46:16.508  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 5610/1/2
```
in both Node-1 and Node-2
The workload doesn't seem to be distributed evenly between the two nodes but that doesn't seem to be an issue.

4. I fired a reindex operation and again the Reindex Process seems to be distributed between the two nodes
I see something like this going on in both nodes. The progress is visible on the UI from the two nodes.

```
13:38:13.631  INFO  reindex.BulkProcessorListener - -----------
13:38:13.631  INFO  reindex.BulkProcessorListener - Reindexing Server #  : 2 of 2
13:38:13.631  INFO  reindex.BulkProcessorListener - Total Indexed        : 250
13:38:13.631  INFO  reindex.BulkProcessorListener - ReindexEntries found : 300
13:38:13.632  INFO  reindex.BulkProcessorListener - BulkRequests created : 250
13:38:13.632  INFO  reindex.BulkProcessorListener - Full Reindex Elapsed : 5.632s
```

which again makes me think the operation is distributed and processed by the two nodes.

Therefore I am passing it to QA

**Comment by bryanboza** [comment]
After these changes we have too many lines of the same message which is causing a lot of noise in the logs, we need to take care of this. 
![image](https://user-images.githubusercontent.com/2641437/99304639-3c3eb200-2818-11eb-9224-a5a18bebe222.png)

**Comment by nollymar** [comment]
Fixed. The message will be logged every 60 minutes: 
PR: https://github.com/dotCMS/core/pull/19600

**Comment by bryanboza** [comment]
Fixed, now we don't have this message in the logs.
