### ISSUE TITLE
Pull request for 4.3.3

### ISSUE THREAD

**Issue by westermarck** [dotCMS/core#18612]
After we started to use the scaling of images in dotCMS (v 4.3.3) we experienced poor image quality with many compression artifacts.

When I examined the image I realized that when no quality parmeter was given the compression quality defaulted to 75%. 75% is a bit aggressive in my opinion and since we were reluctant to change all the image URLs I patched the ShortyServlet (in com.dotmarketing.servlets) to read a configuration parameter with a default compression quality when the filter is initializing. This was made in static plugin which seems to be working properly.

Since the feature might be useful for others I have now moved the changes into my forked dotCMS/core repository in github. But I cannot find a branch for 4.3.3 in the origin repository only a 4.3.3 tag so I can't create a pull request with the code.

Is there an alternative branch, with a name that is not obvious too me, that I can use or would it be possible to create a 4.3.3-branch in the repository so that I can create a pull request?

**Comment by wezell** [comment]
This sounds like a good change.  I think you can make a PR  against 4.4 just so we can see the code?

**Comment by westermarck** [comment]
There was apparently a couple of other commits that was not merged into 4.4 that also sneaked their way into the PR. Please disregard the commits that are not by me in the PR. :)
