### ISSUE TITLE
Converting relationships results in a new relationship inode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18616]
When we convert old relationships to new field based relationships, we are deleting the old relationship and creating a new relationship with a new inode.  This has a number of bad ramifications in a push publishing/multi-environment dotCMS installation.  If you convert the relationship in auth and prod, and then push related content from auth to prod, you will end up with multiple related content fields and lost relationship data becuse the relationship inode is now different on both the environments.

At the end, it basically means that in order to migrate a relationship, you need totally delete the relationship from all environments except the one you are converting, convert the relationship and finally and re-push all the related content to the different environments.
In customers with large amounts of related content, this is just not feasable.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18617

**Comment by nollymar** [comment]
**Note to Doc:** With this change, it isn't required to delete the old legacy relationship as described in Option 2 [here](https://dotcms.com/docs/latest/push-publishing-migrated-relationships) because the migration is executed over the original relationship record

**Comment by erickgonzalez** [comment]
Tested working as it should. Now when you migrate a legacy relationship to a new relationship field it preserves the inode of the relationship.

**Note to QA:** I use an old starter that has legacy relationships, you need to change the starter version [here](https://github.com/dotCMS/core/blob/b90e8e8b76ade6a4929c8f6ea7967c93652d546c/dotCMS/build.gradle#L171) to **20190911**

**Comment by erickgonzalez** [comment]
As an enhancement for a future release maybe we should hide the **Relationship Tab** in the Content-Type when there are no legacy relationships.
