### ISSUE TITLE
What's changed feature is not detecting changes on forms 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18614]
Related to #18356 

Since forms are content, we need to detect changes if you add a form and then activate the what's changed feature 

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page
3. Add a new piece of content and publish the page 
4. Now, addd a form 
5. Go to preview and try to enable the wha't changed

### Expected behavior
Make sure you are able to see the form as part of the changes

### Desktop (please complete the following information):
Tested on release-5.3.2 // Postgres // FF

**Comment by wezell** [comment]
Corner case and the HTML is client side, which the HTMLDiff will not render properly
