### ISSUE TITLE
Support multiple site hosts for URLMap detail pages

### ISSUE THREAD

**Issue by samuelmaddock** [dotCMS/core#18610]
As a content author, I want to be able to map a content type to detail pages on multiple site hosts in order to share a content type across multiple sites.

### Is your feature request related to a problem? Please describe
We have a single content type which we want to have appear in multiple sites within a shared dotCMS instance. We've set the content type to live under the System Host so it's accessible to both. However, the host path used by the detail page determines where the pages actually load.

### Describe the solution you'd like
The Detail Page input on a content type should support multiple entries. One for each host site where the content should appear.
<img width="475" alt="Screen Shot 2020-06-05 at 11 28 49 AM" src="https://user-images.githubusercontent.com/1656324/83894777-c4744380-a71f-11ea-91f8-d7ad651b4067.png">

## Acceptance Criteria
1. Content type can be assigned multiple detail pages with different host sites.
2. URLMapped pages load in each site with a defined detail page.

**Comment by wezell** [comment]
This used to work this way - If your URL Mapped content was on the SYSTEM HOST, you could specify a relative url path, e.g. `/events/detail-page` and the url mapped content would show on any host that had a page under `/events/detail-page`.  Does this not work now?

**Comment by samuelmaddock** [comment]
> Does this not work now?

Using the demo site, it seems to only allow choosing a detail page in a specific site host. The PUT request sent back to the server includes a `detailPage` property assigned to a GUID. I believe that would mean it's only allowed to link up to one htmlassetpage.
