### ISSUE TITLE
Edit mode containers broken

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18613]
### Describe the bug
There is a problem when you add a second "Call to action" contentlet to the same container

This is happening with a specify theme

### Steps to reproduce the behavior:
1. Go to a page
2. Add 2 call to actions contentlets to the same containers
3. Try to edit

### Expected behavior
No matter what contentlet we put in a container it should just work.

### Screenshots
<img width="1792" alt="Screen Shot 2020-06-05 at 15 06 05" src="https://user-images.githubusercontent.com/751424/83922746-1d52d480-a73e-11ea-8397-7c33d70c67ba.png">

### Additional context
You need to download [this bundle](https://dotcms.slack.com/archives/D0291KRQD/p1591388859002200) and import it to your local environment

## Acceptance Criteria

1. Need to work with any contentlets
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.2 // Postgres // FF
