### ISSUE TITLE
Apps - Test configurations with dynamic fields

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18611]
As part of the testing process, configurations with dynamic fields should be tested.

**Important:** To support dynamic fields in Apps, it was required to modify the widget used to add/edit Field Variables. Please, verify the Field/Variables widget keeps working as expected

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1357

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, now we are disabling the button when you have an empty value. Tested on release-5.3.4 // Postgres // FF
