### ISSUE TITLE
[WebDAV] : Default Index Policy for files is failing intermittently

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18626]
Reported via Support: [101298](https://dotcms.zendesk.com/agent/tickets/101298)
Reproducible in dotCMS 5.2.8, and latest master (5.3.1)

### Describe the bug
In recent versions, dotCMS included Index Policy flags that indicate the time when a content is added to the ES Index. From an efficiency standpoint, there are two types of indexing mechanisms: 

1. **DEFER**: Adds the specified content to the ES Index Queue for further indexing. The Contentlet -- i.e., File Asset, Simple Content, HTML Page, etc. -- is saved in the database, but will not be indexed immediately. This policy is very performant.
2. **WAIT_FOR**:  The indexing process will kick off, and the saving must wit for it to finish. Evidently, there's a performance penalty involved, but the content indexing will be completely guaranteed.

When uploading File Assets in batch via WebDAV into dotCMS, the **DEFER** policy is being used by default. However, depending on the amount of files to be uploaded and their respective size, the indexing process seems to be failing at some point. This causes the File Assets to not be indexed correctly -- they display only one publishing indicator: 

<img width="556" alt="indicator" src="https://user-images.githubusercontent.com/8779585/84083634-41612080-a99f-11ea-8900-f81d5e8bd616.png">

This is causing problems when Push Publishing such files. The situation can get worse when several files/folders are uploaded and the logs don't indicate what specific file is failing.

### Steps to reproduce the behavior:
1. Set up a local dotCMS 5.2.8 instance, and connect to it via WebDAV.
2. Create a `/temp/` folder in the default Site for you to upload File Assets.
3. Ask Jose Castro for the folder with sample files. Upload the files from such a folder to you instance.
4. You'll notice that one or more File Assets are not being indexed correctly. No errors are displayed in the log.

### Expected behavior
Uploading File Assets via WebDAV needs to work correctly.

### Additional context
After discussing the issue with the R&D Team, it was determined that the Indexing Policy for WebDAV must be set to **WAIT_FOR**.

## Acceptance Criteria

1. Unit test

**Comment by fmontes** [comment]
Apply the fix: https://github.com/dotCMS/support/commit/47938784f6ecb5e53d18fb3d25847ee6a6faed2c

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18857

**Comment by dsilvam** [comment]
Passed Internal QA: all files uploaded correctly via webDAV.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5. // MySQL. // FF and now I'm unable to reproduce
