### ISSUE TITLE
Improve the drag and drop message if you don't have the right permissions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18629]
Related to #18401 

After add this functionality, now we need a permissions to publish in the dotAsset content type to allow to drag and drop files. If you don't have those permissions we are showing a `400 - Bad Request`  message to the end user at UI level. 

We need to improve that and show a friendly message 

![image](https://user-images.githubusercontent.com/2641437/84188545-028ba300-aa51-11ea-8698-e2e7da88bdd3.png)

### Steps to reproduce the behavior:
1. Login as admin
2. Create a new page and set permissions to a limited user to publish on this page 
3. Set permissions to the same limited user in the `Rich Text` content type 
4. Login as the limited user and edit the page 
5. Try to drag and drop any image into the WYSIWYG field 

### Expected behavior
We need to improve the error message 

### Desktop (please complete the following information):
Tested on release-5.3.2 // Postgres // FF

**Comment by fmontes** [comment]
![image](https://user-images.githubusercontent.com/751424/135667911-a3e0a49c-c0f1-4999-8ffb-f1169c86f14f.png)

We need to improve the endpoint error `api/v1/workflow/actions/default/fire/PUBLISH`

**Comment by erickgonzalez** [comment]
This error was because the user does not have permissions over the contentType/baseType **dotAsset** so it can't upload the file successfully. The message was updated to clarify the situation.
`Content-Type could not be resolved based on base type, check permissions for user 'dotcms.org.2735' over the base type 'dotAsset'`
