### ISSUE TITLE
[Push Publishing] : Wrapper object is dropping the Identifier value

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18621]
Found when working on Support: [101210](https://dotcms.zendesk.com/agent/tickets/101210)

### Describe the bug
Part of the code changes that were implemented in the ticket #17994 involved improving the way pushed data is read from the bundle. The generated XML-to-Java objects were being stored in a list so the code wouldn't have to do it twice, given the way the code works now.

However, at some point, the `ContentWrapper` object is randomly dropping the value of the content's `identifier`. This is causing the push to fail for incorrect reasons. Rolling back the code changes that stored the `ContentWrapper` objects in a list solved the Push Publishing problem for the customer.

### Steps to reproduce the behavior:
This was reproduce in the customer's Push Publishing environment. Please contact Jose Castro for more information.

### Expected behavior
The `ContentWrapper` object should not be dropping any property.

### Additional context
For the time being, the fix will be a simple rollback of the code change that kept the XML files from being read twice. However, it'd be great if the R&D Team could investigate if the problem can be solved by completely cloning the generated `ContentWrapper` object, instead of jus storing it in a list.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/728/files

**Comment by dsilvam** [comment]
Difficult to reproduce. Passing this one after feedback from support.
