### ISSUE TITLE
Apps: Need exclude the archived sites from the apps portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18639]
We need to exclude the archived sites from the list of sites in the apps portlet, this because does not make sense add configurations to that sites and will cause confusion with the active sites. 

### Steps to reproduce the behavior:
1. Login as admin 
2. Create two new sites
3. Add a yml configuration file 
4. Archive the added sites
5. Make sure we are not listing those sites 

### Expected behavior
We need to exclude the archived site from the list 

### Desktop (please complete the following information):
Tested on release-5.3.2 // Postgres // FF

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18809

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
We still including archived sites in this portlet: https://www.screencast.com/t/WF8MRz8Ybq

**Comment by nollymar** [comment]
@bryanboza this issue is marked as "Next Release". I think that is why you're still seeing archived sites in 5.3.4.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // MySQL // FF
