### ISSUE TITLE
Apps - UI problems editing the size of the fields

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18637]
In the new apps portlet we have the option to edit the size of the fields, but we can misalign completely the portlet when those fields have values 

![image](https://user-images.githubusercontent.com/2641437/84294534-8a7fb480-ab06-11ea-9421-62bd8c811542.png)

### Expected behavior
We need to set limits to this functionality 

### Desktop (please complete the following information):
Tested on release-5.3.2 // Postgres // FF

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1354

**Comment by nollymar** [comment]
Passed Internal QA

![Screen Shot 2020-06-18 at 11 51 37 AM](https://user-images.githubusercontent.com/8741395/85049309-20948a00-b15a-11ea-931b-6ae50e394f37.png)

**Comment by bryanboza** [comment]
We need to set a minimum size to those fields, because it does not make sense allow minimize totally the field, without knowing if it has a value or not. 
![image](https://user-images.githubusercontent.com/2641437/85069890-18e0df80-b172-11ea-926e-4cab140d6766.png)

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1359/files

**Comment by nollymar** [comment]
Internal QA Results: 

Now, when I resize a field, the other fields are resized as well.  It happens in Google Chrome and Firefox: 

![Apps-Video](https://user-images.githubusercontent.com/8741395/85635002-7bd6e880-b642-11ea-9642-4e9744a4feba.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1365

**Comment by wezell** [comment]
The fields need a min-width and a max-width.  It seems like you added a min-width but left the max-width at 100% of the bounding div

**Comment by nollymar** [comment]
Passed internal qa. Setting a max-width fixed the issue

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // MySQL // FF
