### ISSUE TITLE
JSP Custom Portlet Right Click Open In a New Tab

### ISSUE THREAD

**Issue by Invisibilities** [dotCMS/core#18634]
Hi guys, when I tried to open the below href as "Open In a New Tab" in the custom portlet jsp. It will redirect me to the workflow task instead of the custom portlet.
How to solve this issue?
I cannot find any documentation about this.
I know there is a frame prevent me for doing this.
Before we upgrade the dotcms from 3.5 to 5.2, it allows us to do so but after upgrade to 5.2, it doesn't allow do it.
Please advice.
Thanks

```
<%
String submitURL = PortletURLUtil.getRenderURL(request,null,null,"updatePage");
%>

function goToPage(id){
    var url = "<%=submitURL %><%=Constants.CMD%>=id=" + id;
    window.location = url;
}

<a href="#" id="<c:out value="${data.loginId}"/>" onclick="goToPage('<c:out value="${data.loginId}"/>')"><c:out value="${data.loginId}"/></a>
```

**Comment by Invisibilities** [comment]
anyone can help?

**Comment by fmontes** [comment]
Hi,

Can you try to do the redirect to:

```/dotAdmin/#/c/{PORTLET_ID}```

Let me know how it goes.

**Comment by Invisibilities** [comment]
> Hi,
> 
> Can you try to do the redirect to:
> 
> `/dotAdmin/#/c/{PORTLET_ID}`
> 
> Let me know how it goes.

Thanks for the helping.
Let me explain my real requirement.
My requirement is when user right-click and open as new tab within the frame (custom portlet), it will open as new tab and go back to the custom portlet.
Lets say my custom portlet call 'Registration List'. When user click on the 'view' button with right click open as new tab, it will open as new tab with the 'registration details'. 
But now, when I click and open as new tab of 'view' button, it will redirect me to the workflow task portlet instead of 'registration details'.
I think there is a frame on dotcms 5.2 prevent me to do this.

When I tried the link on browser
http://localhost:8080/c/portal/layout?p_l_id=331de289-fe25-4617-aab4-c70ec960a24c&p_p_id=registrationDetails&p_p_action=0&p_p_state=maximized&angularCurrentPortlet=registrationDetails&p_p_mode=view&_registrationDetails_struts_action=%2Fadmin%2FregistrationDetails#
it will redirect me to workflow task.
