### ISSUE TITLE
[Content Export] : Code improvement required to remove content export limit.

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18641]
Reported via Support: [101581](https://dotcms.zendesk.com/agent/tickets/101581)
Reproducible in dotCMS 5.2.8

### Describe the bug
The Content Export functionality needs to put Contentlets through several permission and security verifications before they can be exported as an Excel file. Because of this, as a standard procedure, we've always recommended customers to set a 10,000 content export limit. In previous versions of dotCMS allowed up to 100,000 contents to be exported.

We need to look into the code behind this feature, and perform the appropriate performance improvements to allow customers to export more contents.

### Steps to reproduce the behavior:
1. Set up a local dotCMS 5.2.8 instance.
2. Export the contents of a specific Content Type. Ideally, there must be at least 20,000 contents.
3. Wait for the Excel file to generate. You'll see that only 10,000 contents made it into the file.

**NOTE: Please contact Jose Castro if a specific database is required.** 

### Expected behavior
The system should be able to export all contents of the specified type.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
There's also the situation in which the export is not being cancelled in the back-end. For example, if you try to export 10,000-20,000 contentlets, but you want to cancel the process, the code will still be running and will generate the expected results.

We need some new code to cancel the execution of the export altogether if the user decides to cancel the download.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18679

**Comment by jcastro-dotcms** [comment]
Curl call used to increase max result limit:
```
curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_all/_settings' -d '{
  "index.max_result_window" : "100000"
}'
```

**Comment by dsilvam** [comment]
Passed Internal QA: Able to export more than 10k contents.

**Comment by dsilvam** [comment]
Passed QA: Able to export `File Asset` content type. Resulting CSV file was 52.8 Mb.
