### ISSUE TITLE
[Logging] : Improvement on error logging in several classes

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18645]
Found when working on Support: [101298](https://dotcms.zendesk.com/agent/tickets/101298)
Reproducible in almost all versions of dotCMS.

This ticket is an improvement, and it's meant to keep track of several improvements made to the error logging in some dotCMS classes, specially the ones related to the Push Publishing process.

### Steps to Reproduce
Given that this is a code improvement, the way to check the new logging is to generate all kinds of errors in, for example, Push publishing. Then, compare with a previous dotCMS version.

### Expected behavior
The system needs to log more useful information upon specific error situations.

### Additional context
An adequate logging of error or conflict situations is crucial for the Support Team to address issues from customers in a timely manner.

**Comment by jcastro-dotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/18646
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/730

**Comment by fmontes** [comment]
Logs, no need Bryans QA.
