### ISSUE TITLE
Apps - UI: Create new Select field on DotApps configuration form

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#18642]
A new SELECT field needs to be created to support the DotApps configuration form

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1348/files

**Comment by nollymar** [comment]
**QA not needed:** This change cannot be tested until the backend supports select fields. A new card has been created for this: https://github.com/dotCMS/core/issues/18686
