### ISSUE TITLE
Modify `Site' GraphQL Field to be content 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18644]
Migrate `Site` field into Contentlet to be able to have all the Contentlet properties available.

**Comment by dsilvam** [comment]
PR core: #18651
PR ee: dotCMS/enterprise-2.x#732

**Comment by dsilvam** [comment]
Missing Postman Tests

**Comment by dsilvam** [comment]
PR postman tests: https://github.com/dotCMS/core/pull/19049

**Comment by dsilvam** [comment]
**Note to QA**: When requesting the `host` field of a piece of content via GraphQL, now `host` itself is Content, so [all the fields inherited from content](https://dotcms.com/docs/latest/graphql#RootType) should be available for `host` also.  

Same thing applies for the GraphQL Page API. If you request the `site` field of a page, you should have all the inherited fields from content. See `GraphQL.PageAPI.GivenRequestByURI_SiteFieldContainsAllFields` for a example of this in Postman.

**Comment by bryanboza** [comment]
Fixed, tested release-5.3.7 // Postgres // FF . After the changes, now we are able to get the site field and all the attributes without problems
