### ISSUE TITLE
UI: Problems handling SVG images 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18656]
We have some UI problems uploading images when the image is an SVG - in some cases we are not able to resize the image and show a small thumbnail. 

Then we are crashing the UI and the image override all the window

SC: https://www.screencast.com/t/wmjjSPSTMUts

### Steps to reproduce the behavior:
1. Login as admin
2. Go to content search, select the image content type and try to upload a new piece of content 
3. Select the attached image 
4. Make sure you are able to see the image thumbnail without problems 

Here the image: https://drive.google.com/file/d/1eLtsJ1ipUrBuxpCBsjEFKnMNVK2xiqUf/view?usp=sharing

### Expected behavior
We need be able to resize the image and show it without problems 

### Screenshots
https://www.screencast.com/t/wmjjSPSTMUts

### Desktop (please complete the following information):
Tested on release-5.3.2 // Postgres // FF 

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
Not able to reproduce in master:
- chrome
https://monosnap.com/file/uPEYLm1MWBNDycQfy8ZBHOK0tIckM1

- firefox
https://monosnap.com/file/64729ctX6sqfQmsKIsAvjiLvwgMwA0

**Comment by bryanboza** [comment]
Please try with this file: https://drive.google.com/file/d/1RnI-fBmDf29wt3-eVb-vs5fl6c08XA7l/view?usp=sharing

**Comment by alfredo-dotcms** [comment]
I did @bryanboza, if you see the video you'll see I used that img and also another from a camara

**Comment by bryanboza** [comment]
Fixed, tested with other images and not able to reproduce, seems something related to the image is the problem
