### ISSUE TITLE
GraphQL request unnecessary error

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18661]
### Describe the bug
If you do a request to a content type and ask for a field (not required) but one of the contentlets doesn't have a value in the field it returns results but also an error which make FE client throws error

### Steps to reproduce the behavior:
1. Create a content type and add a non required field
2. Create some contentlets and leave the field empty
3. Query the contentlets in graphql but ask for the field
4. See error at the end

### Expected behavior
It should not return an error

### Screenshots
![Screen Shot 2020-06-12 at 12.37.45.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/7f108671-3dc4-494f-a00e-bfc35734e9fc)
![Screen Shot 2020-06-12 at 12.37.32.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/ca07d743-1b9b-4d15-aa40-be2fcd8e2d87)

## Acceptance Criteria

1. No error back
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
I wonder if this is true for only specific fields, e.g. tags.

**Comment by fmontes** [comment]
You can try this query in auth:

```
query codeshare {
    CodeshareCollection(
      query: "+urlMap:/codeshare/display-related-content-listed-by-categories-in-a-multilingual-environment"
    ){
      authorName
      code
      description
      title
      urlTitle
      dateCreated
      company
      seoDescription
    	tag
    }
}
```
