### ISSUE TITLE
[Reindex] : Inconsistent data is causing the reindex to fail

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18673]
Found when working on Support ticket: [100806](https://dotcms.zendesk.com/agent/tickets/100806)
Reproducible in **ALL versions of dotCMS.**

When working on datasets from customers, specially customers coming from very old versions of dotCMS, it's fairly common run into data inconsistencies that break the Reindexing Process. For example, Contentlets whose `host_inode` belongs to a Simple Content Type instead of a Site, among other situations.

### Steps to reproduce the behavior:
This was reproduced in a customer environment. In a local development environment, you can simulate this by changing the `host_inode` column of a contentlet in the `identifier` table to point to, for example, the Identifier of an `Event` contentlet.

### Expected behavior
The system needs to report a more precise error message so that the Enterprise Support team can identify the root cause of the problem in a timely manner.

### Additional context
Better error messages help the Support Team react a lot faster.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18674

**Comment by wezell** [comment]
I believe this is addressed (somewhat) here: #18584 - PR: #18576

**Comment by jcastro-dotcms** [comment]
@wezell this is actually an improvement on the error handling, and not a reindex problem per se. The PR is just meant to provide more information to errors caused by data inconsistencies present in very old data sets. The reindex behaved correctly.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18674

**Comment by dsilvam** [comment]
Passed Internal QA: Additional logging taking place.
