### ISSUE TITLE
TempFileAPI calls new FileOutputStream(File)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18676]
This is an anti-pattern and causes heap memory to grow and only gets cleaned up in Full GC.

https://dzone.com/articles/fileinputstream-fileoutputstream-considered-harmful

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18681

**Comment by fmontes** [comment]
QA: Check that upload of dotassets are ok.

**Comment by jdotcms** [comment]
We have uploaded multiple dotAsset (dotAsset uses temp api) and works ok
