### ISSUE TITLE
Unable to show the push publish modal from edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18678]
When you add a push publish sub-action to some push publish action and try to fire this from edit mode, we are unable to show the push publish modal. 

### Steps to reproduce the behavior:
1. Login as admin 
2. Apply for a EE license 
3. Create a new page 
4.  Go to workflows --> system workflow and add the `push publish` sub-action to the `publish` action
4. Go to site browser again and edit the page 
5. From the "..." button try to fire the publish action
6. Make sure you are able to see the PP modal

### Expected behavior
We need be able to show this modal from anywhere that you fire the action 

### Screenshots
SC: https://www.screencast.com/t/S9IMizy1L

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by fmontes** [comment]
We need to extract the pp dialog component to not do the pp request so we can reuse it.

**Comment by fmontes** [comment]
When we don't have enviroments we are going to:

1. Check if we have envs when the click "publish"
2. If we don't have envs we show a grow/toast with the message: contentlet not published because no envs and click to fix this
3. If we have env, we show the PP dialog

**Comment by erickgonzalez** [comment]
PR core: https://github.com/dotCMS/core/pull/18952

**Comment by erickgonzalez** [comment]
- [X] Add only `PP Actionlet` to WF with no env (show toast)
- [X] Add only `PP Actionlet` to WF 
- [X] Add only `User Can Assign` to WF
- [X] Add only `Allow Comments` to WF
- [X] Add only `PP Actionlet` and `User Can Assign` to WF
- [X] Add only `PP Actionlet` and `Allow Comments` to WF
- [X] Add only `User Can Assign` and `Allow Comments` to WF
- [X] Add only `PP Actionlet`, `User Can Assign` and `Allow Comments` to WF
- [X] `Enter` should move to the next step of the wizard (if there is a next step and the current one is valid)
- [X] When `User Can Assign` and check `Include Users from Parent Roles` should show parent roles/users
- [X] The dialog when exec the WF is different from the Content Search and the Edit Page (that's ok) but must behave the same

**Comment by wezell** [comment]
We moved away from the enter button because we need to support line breaks in the comments field.  It should tab to the next button.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF. Case #3 moved to a new card https://github.com/dotCMS/core/issues/19158
