### ISSUE TITLE
Apps - Backend: Support select fields in yml files

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18686]
As a user, I'd like to see select fields when I set a configuration for a site. It should be defined using yml files as it works for other fields

**Comment by alfredo-dotcms** [comment]
the endpoint needs to return a value with the following structure to be able to return a SELECT field:

```
{
        dynamic: false,
        name: 'select',
        hidden: false,
        hint: 'This is Select!',
        label: 'Select label:',
        options: [
            {
                label: 'uno',
                value: '1'
            },
            {
                label: 'dos',
                value: '2'
            }
        ],
        required: true,
        type: 'SELECT',
        value: '1'
    }
```

**Comment by fabrizzio-dotCMS** [comment]
PR : https://github.com/dotCMS/core/pull/18942

**Comment by nollymar** [comment]
Passed internal QA. Tested on SAML integration

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Tested based in a dev-wiki example
