### ISSUE TITLE
File rename when creating a file content gives an error 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#18685]
Give a file a name, then search for a file. the suggestion to rename the file is not working![Screen Shot 2020-06-17 at 10.12.58 AM.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/f39c5d17-1a7f-40b9-93a3-32b9795449ed)

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/18692

**Comment by bryanboza** [comment]
Fixed, new problem reported here #18710
