### ISSUE TITLE
Move index dynamic mappings from JSON to code

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18689]
The dynamic mapping is read from the file `es-content-mapping.json`. We need to get rid of this file and move those settings to Java and apply them when the index is created

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18751

**Comment by nollymar** [comment]
**Note to QA:** To test this fix, you need to have kibana up and running. Please ask me if you need help

Test cases: 
**_Case 1: Verify dates are mapped correctly_**
1. Create a content type 
2. Add a (Date/Date-Time/Time) field and mark it as System Indexed
3. Create a new piece of content with a date
4. Check the mapping set in Kibana --> Read the next comment

**_Case 2: Verify numbers are mapped correctly_**
1. Create a content type 
2. Add a (Decimal/Whole Number) field and mark it as System Indexed
3. Create a new piece of content with a number
4. Check the mapping set in Kibana 

**_Case 3: Verify booleans are mapped correctly_**
1. Create a content type 
2. Add a Radio field, setting it as a Boolean (True/False) and mark it as System Indexed
3. Create a new piece of content with a boolean value
4. Check the mapping set in Kibana 

**_Case 4: Verify texts with date format are mapped correctly_**
1. Create a content type 
2. Add a text field and mark it as System Indexed
3. Create a new piece of content with a string with format: yyyy-MM-dd
4. Create another piece of content with a free text in the field (no date)
5. Verify both pieces of content are saved correctly
6. Check the mapping set in Kibana for the field

**Comment by nollymar** [comment]
**How to get the mapping of a field in Kibana:**

Go to the Dev Tool console and run a query similar to this one: 

```
GET /cluster_be42a31462.live_20200715102955/_mapping/field/calendarevent.location
```
where:
**full index name:** _cluster_be42a31462.live_20200715102955_
**field name (including content type variable):** _calendarevent.location_

<img width="1257" alt="Screen Shot 2020-07-15 at 11 18 37 AM" src="https://user-images.githubusercontent.com/8741395/87569580-f2d52f00-c68c-11ea-8425-63e35e64d74c.png">

**Comment by wezell** [comment]
fixes #18154

**Comment by nollymar** [comment]
Additional fix: https://github.com/dotCMS/core/pull/18909

**Note to QA:** Please test lucene queries over text fields using whitespaces in search criteria. For instance: `contenttype.mytextfield:this is my text`

**Comment by bryanboza** [comment]
Fixed, tested with Kibana and every field works as expected
