### ISSUE TITLE
[Workflows] : The AVAILABLE WORKFLOW ACTIONS button is failing with specific Lucene queries

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18697]
Reported via Support: [101613](https://dotcms.zendesk.com/agent/tickets/101613)
Reproducible in dotCMS 5.2.8 up to latest master (5.3.2)

Several improvements have been made to the ES implementation in dotCMS. As part of that, the `WhitespaceAnalyzer` is not being used anymore. However, there's code that is still using this code and applying other outdated verifications to Lucene queries. For some specific ones, this is causing an error that is keeping the `AVAILABLE WORKFLOW ACTIONS` button from working as expected.

### Steps to reproduce the behavior:
Ask Jose Castro for the details on how to reproduce the error.

### Expected behavior
The outdated validations applied to the Lucene query must be removed..

### Additional context
It'd be great if the R&D Team could go over the master source code and verify that we're not using ES Analyzers that are no longer valid.

## Acceptance Criteria

1. Unit test

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18701

**Comment by wezell** [comment]
@jcastro-dotcms can you provide us with the bad query that was fixed by this change?

**Comment by wezell** [comment]
Note for QA - we have the customer database to test against.

**Comment by jcastro-dotcms** [comment]
@wezell working with Victor who has a local environment with customer database.

**Comment by victoralfaro-dotcms** [comment]
`AVAILABLE WORKFLOW ACTIONS` button correctly displays dialog meaning that lucene queries are read OK.

![image.png](https://images.zenhubusercontent.com/5e9dc4dff37aec55f61ae012/07473f73-f6ec-4900-a358-17045594cf5b)

**Comment by victoralfaro-dotcms** [comment]
AVAILABLE WORKFLOW ACTIONS button correctly displays dialog meaning that lucene queries are read OK.

![image](https://user-images.githubusercontent.com/64026161/87704391-8ffd9980-c759-11ea-930f-6d216e7535f1.png)


Also unit tests were updated.
