### ISSUE TITLE
SAML plugin consuming a lot of resources when multiple hosts are used

### ISSUE THREAD

**Issue by jasontt33** [dotCMS/core#18699]
### Describe the bug
U of Akron was experiencing a lot of performance issues and we loaded Glowroot to illuminate their  bottlenecks and Will was able to see issues resolving each idp host on every request. U of Akron at the time had quite a few hosts. 

The `SiteIdpConfigResolver` should be something like:
```
	public IdpConfig resolveIdpConfig( final HttpServletRequest request ) throws DotDataException, IOException, JSONException
	{
		final Host server = WebAPILocator.getHostWebAPI().getCurrentHostNoThrow(request);
		return this.resolveIdpConfig( server.getIdentifier() );
	}
```

### Expected behavior
Less resource consumption. Only look up idp config once or minimize idp resolutions

### Screenshots
![image](https://user-images.githubusercontent.com/44835521/85057904-56903900-b16f-11ea-802f-c017ae618ec8.png)

### Desktop (please complete the following information):
NA

### Additional context
Glowroot can be loaded on U of Akron to get up to date metrics if needed

## Acceptance Criteria

Less resource consumption. Only look up idp config once or minimize idp resolutions

**Comment by wezell** [comment]
@jdotcms is taking care of this in the saml project
