### ISSUE TITLE
[UI] Asset information window needs some help with log names

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18691]
When you have an asset with a really long name and you upload to the system and then try to get the asset information, we are showing just part of the name instead to show the complete in multiple lines 

### Expected behavior
We need to show the complete path in multiple lines or made bigger the window 

### Screenshots
![image](https://user-images.githubusercontent.com/2641437/84943723-08613400-b0a2-11ea-9b9c-aa7beb9d07a3.png)

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by hmoreras** [comment]
unable to reproduce but found this one, in the permissions tab
![image](https://user-images.githubusercontent.com/31667212/85460611-a2bcee00-b560-11ea-80d5-c1535d844951.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF
