### ISSUE TITLE
PP action not getting call when publish a page from edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18698]
1. Add PP sub action to publish
2. Edit a page
3. Publish

The PP dialog is not getting show.

This might need BE work.

**Comment by hmoreras** [comment]
this is related to server error, and that might be the reason the notification to the FE never arrives: 

Log: https://gist.github.com/hmoreras/c09bc4a038a30ebb01acf69dc8a2d4ba

**Comment by fmontes** [comment]
Dupe https://github.com/dotCMS/core/issues/18678
