### ISSUE TITLE
PP filters bad descriptor breaks the all of the filters

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18705]
If you have a PP filter with a yaml error in it, it throws an error and does not load any of the PP filters.

**Comment by erickgonzalez** [comment]
**Note to QA:** Easiest way to test is to remove the space between the colon and the value.
 E.g. `title:Content and Relationships`

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18828

**Comment by erickgonzalez** [comment]
Tested and working as it should. Now if a YAML file has an error it'll be logged and will continue with the next one, in the end only the filters without error will be loaded.

**Comment by bryanboza** [comment]
As improvement we need some work here: 

- As in the apps portlet, we need a better validation here, this because we are validating withe spaces but not if you remove a required property or if you add a property that is not expected.

- Also, we need to add some info in the log regarding the file will be ignored by an error in the yaml file.

**Comment by fmontes** [comment]
@bryanboza as improvements, create new issues for this, can't make this a blocker.

**Comment by erickgonzalez** [comment]
There is already a log when the filter Is gonna be ignored:
```
publishing.PushPublishFiltersInitializer - unable to load PP filter:/Users/erickgonzalez/Documents/dotcms/tomcat8/webapps/ROOT/assets/server/publishing-filters/ContentOnly.yml cause: Unrecognized field "propiedad" (class com.dotcms.publishing.FilterDescriptor), not marked as ignorable (6 known properties: "default", "title", "defaultFilter", "filters", "roles", "key"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 20, column: 1] (through reference chain: com.dotcms.publishing.FilterDescriptor["propiedad"])
```

**Comment by bryanboza** [comment]
Fixed, the requested improvements were moved to a new card #18986
