### ISSUE TITLE
Push Publishing Dialog needs work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18704]
The selector for choosing to Push, Remove or Push and Remove should look like this:

![Screen Shot 2020-06-18 at 3 04 59 PM](https://user-images.githubusercontent.com/934364/85061818-6a3e9e00-b175-11ea-8e59-36a892bf8255.png)

**Comment by fmontes** [comment]
1. UI adjust
2. Fix default selected
3. Sort options

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.3 // Postgres // FF
