### ISSUE TITLE
[Layout] : Container id is being duplicated

### ISSUE THREAD

**Issue by luisbacca** [dotCMS/core#18714]
Reported via support : [101617](https://dotcms.zendesk.com/agent/tickets/101617)
Reproducible in dotCMS 5.2.8 up to latest master (5.3.2)

In Dotcms is possible to add the same container to a page multiple times, however a client ia hhaving an issue where the layout id of some container is being duplicated. For example, the attribute uuid is being duplicate. Please look at the following json : 

```json
"body" : {
      "rows" : [ {
        "columns" : [ {
          "containers" : [ {
            "identifier" : "/application/containers/fpo/",
            "uuid" : "2"
          }, {
            "identifier" : "/application/containers/fpo/",
            "uuid" : "3"
          }, {
            "identifier" : "/application/containers/fpo/",
            "uuid" : "4"
          } ],
          "widthPercent" : 100,
          "leftOffset" : 1,
          "styleClass" : null,
          "preview" : false,
          "width" : 12,
          "left" : 0
        } ],
        "styleClass" : null
      } ]
    },
    "sidebar" : {
      "containers" : [ {
        "identifier" : "/application/containers/fpo/",
        "uuid" : "1"
      }, {
        "identifier" : "/application/containers/fpo/",
        "uuid" : "2"
      }, {
        "identifier" : "/application/containers/fpo/",
        "uuid" : "1"
      } ],
      "location" : "left",
      "width" : "medium",
      "widthPercent" : 30,
      "preview" : false
    }
```

### Steps to reproduce the behavior:
Ask Luis Bacca for the details on how to reproduce the error.

### Expected behavior
The container ids should be unique on a page. 

## Acceptance Criteria

1. Work in all the supported browsers (don't forget IE11 and iPad)
2. Unit test

**Comment by dsilvam** [comment]
To take into consideration: if you call `{{serverURL}}/api/v1/page/{pageId}/layout` including a layout with existing containers **but do not specify the "uuid"**, the existing content switches from uuid "-1" to uuid "1" in each different execution.

**Comment by freddyucv** [comment]
**Note QA**: the issue just happened when try to add the same file container twice (o more) in a sidebar

**Comment by freddyucv** [comment]
> To take into consideration: if you call `{{serverURL}}/api/v1/page/{pageId}/layout` including a layout with existing containers **but do not specify the "uuid"**, the existing content switches from uuid "-1" to uuid "1" in each different execution.

This is another bug so I am going to create a new issue

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core-web/pull/1368

**Comment by dsilvam** [comment]
Passed Internal QA: UUID for containers are not duplicated now.

**Comment by bryanboza** [comment]
We need some work here: 

- If create the template using the template designer and now from the layout of the page, we are not reflecting the changes here, the `uuid` still being the same that before 
![image](https://user-images.githubusercontent.com/2641437/87831965-17bed300-c842-11ea-9009-14eb0a528584.png)

- We have another weird behavior here, that we need to take look, if using this template you add the same content to the 3 containers in the slide-bar, and then try yo publish the page, we are loosing the content of those containers 
SC: https://www.screencast.com/t/Exk6WPCxzF
