### ISSUE TITLE
5.3.2 Main nav does not scoll

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18716]
On a short screen, he main dotCMS navigation does not show a scroll bar if the options overflow the screen.

![dotCMS_5_3_2_Scroll_bar](https://user-images.githubusercontent.com/934364/85158860-c0214d80-b22a-11ea-9084-8fe282d29097.JPG)

![dotCMS_5_3_2_Scroll_bar_1](https://user-images.githubusercontent.com/934364/85158877-c3b4d480-b22a-11ea-8979-98c1fe42e210.JPG)

**Comment by erickgonzalez** [comment]
Tested and now we have a scroll with the expanded menu and with the collapse menu we show the options to fit the screen.

**Comment by bryanboza** [comment]
Fixed tested and I'm unable to reproduce after the last changes
