### ISSUE TITLE
File rename when creating a file content is not updating the resource link

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18710]
Related to #18685 

After fix the related card now we are getting a new problem, when you rename an existing file name we are not updating the showed resource link in the info tab, then if you try to open the one that we show we are getting a 404 error  

### Steps to reproduce the behavior:
1. Login as admin 
2. Upload a new file asset 
3. Now edit this and rename the asset 
4. Publish it 
5. try to edit again 
6. Click into the info tab 
7. Try to open the resource link 

### Expected behavior
We need to update this resource link after you edit the file name 

### Screenshots
![image](https://user-images.githubusercontent.com/2641437/85076349-2cde0e80-b17d-11ea-9819-baf2da688e28.png)

### Desktop (please complete the following information):
Tested on master // Postgres // FF

**Comment by hmoreras** [comment]
Unable to reproduce, in master current commit `e8d741602ace40bf2b7303fda0d98fb890556aba `

**Comment by hmoreras** [comment]
Unable to reproduce, in master current commit e8d741602ace40bf2b7303fda0d98fb890556aba
