### ISSUE TITLE
De-Inode and de-hibernate legacy tables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18726]
When dotCMS originally started out \(circa 2001\), everything inherited from the class Inode and was persisted by Hibernate and the InodeFactory.  This pattern requires objects have entries in two tables, the inode table and the table that stores the object.  This is inefficient and causes issues when one of those tables gets out of sync.

We need to begin the process of removing Inodes and hibernate from everything.  At the end of this process, we can delete the InodeFactory and the Inode.class itself

Each one of these classes needs a few things
- Remove from hibernate.hbm.xml
- DBTransformer
- A new JSON serialization/deserialization mechanism
- Be included in the starter.zip creation and ingestion

**Comment by prestonso** [comment]
Marking as closed per @wezell as we have an epic representing this.
