### ISSUE TITLE
Run Integrity Checker as a scheduled job

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18725]
We need to create a stateful scheduled job that fires the integrity checker on a timed basis (once an hour?).  Additionally, when the integrity checker finds an issue, we need to fire a Growl that alerts all admins that the PP environments are out of sync and that they should resolve the issues from the PP portlet.

Obviously, the running and schedule of this Job should be updatable in the dotmarketing-config properties file.

**Comment by victoralfaro-dotcms** [comment]
@wezell one question. What happen if a user enters to the "Publishing Environments" and a scheduled integrity check is taking place?

**Comment by wezell** [comment]
they should see the little in progress indicators, right?
