### ISSUE TITLE
Update dev-scripts to add core-web release branch creation

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18724]
For `core-web` is simpler:

1. Banch out from master to `release-ver.si.on`
2. Push the branch

## Acceptance Criteria
1. Make the script also create and push `core-web` branch
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
Done. Implemented here: https://github.com/dotCMS/dev-scripts/pull/1
