### ISSUE TITLE
PP Filters: Shallow Push should include tree (and maybe multi-tree )entries

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18742]
I believe that when we shallow push an object, we should also include the objects tree and multi-tree entries (though we can ignore the associated objects).

I believe without this, shallow push will not behave as expected.  Here are some examples.

### Scenario # 1
You have a page and add a piece of content to it.  You then shallow push that page.  On the receiver, the page shows up blank.   You shallow push the added content and the page is still blank. 
You would need to push with dependencies for any changes to a page to be visible.

### Scenario # 2
You create a content type with a relationship field to itself.  You shallow push this content type.
You then create content A and shallow push it.  You create content B and relate it to A and shallow push it.  Both A and B will exist on the receiver but the relationship between them will not.   In fact there is no way to shallow push the relationship between them.

## Acceptance Criteria
Both scenarios # 1 and # 2 must work correctly.

**Comment by bryanboza** [comment]
This filter is allowing to have incorrect data on the receiver side, this because we can send required values in null
SC: https://www.screencast.com/t/5rJm3eQhaI

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/18742?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/18742?planning-poker) with Zenhub @rjvelazco @hmoreras @jdotcms @jcastro-dotcms

**Comment by fmontes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/18742?planning-poker) with Zenhub @hassan-mustafa-baig

**Comment by jcastro-dotcms** [comment]
- Core PR: https://github.com/dotCMS/core/pull/23178
- Enterprise EE: https://github.com/dotCMS/enterprise/pull/889

**Comment by bryanboza** [comment]
Fixed, tested on release-22.12 // Docker // FF 

Note: We don't take this comment in consideration for now https://github.com/dotCMS/core/issues/18742#issuecomment-650346805
