### ISSUE TITLE
UI issue with import/export - grayed-out fields are checked instead of just gray - 5.1.6

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#18748]
When attempting to import content, fields that are grayed out show that they are also checked. This is confusing because it looks like they are being treated as key fields and unable to be deselected.

Referencing zendexk ticket: https://dotcms.zendesk.com/agent/tickets/101645 

### Steps to reproduce the behavior:
1. Go to Content->Search
2. Click on 'Import Content'
3. See error

### Expected behavior
Fields not available to be used as key fields should be grayed out, but not checked. 

###Actual behavior

See screenshot

### Screenshots

Version 5.1.6:

![image](https://user-images.githubusercontent.com/49727631/85321639-9e260600-b48a-11ea-924d-2a2e03546aee.png)

### Desktop (please complete the following information):
 - OS: N/A
 - Browser N/A
 - Version 5.1.6

**Comment by alfredo-dotcms** [comment]
this looks with latest master
![image](https://user-images.githubusercontent.com/37185433/101413028-32551f80-38a9-11eb-8a6c-6fa4a1b87d1c.png)

**Comment by bryanboza** [comment]
Unable to reproduce on release-20.12 // Postgres // FF.  The grayed fields appear totally disabled
