### ISSUE TITLE
[plugin-seeds] : The "com.dotcms.hooks" Osgi plugin is not working

### ISSUE THREAD

**Issue by luisbacca** [dotCMS/core#18756]
Found when working on support: [101651](https://dotcms.zendesk.com/agent/tickets/101651)
Reproducible in dotcms 5.2.8 up to 5.3.2

The sample hook plugin is not calling the right checkin method.  

### Steps to reproduce the behavior:
1. Run an instance of dotcms 5.2.8
2. Deploy sample hook plugin from https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.hooks
3. Update any content by save or save/publish
4. Notice no log lines are printed in catalina.out for [checkin method](https://github.com/dotCMS/plugin-seeds/blob/7099c4090e3199203bcb13a84b84d7e080dbf809/OSGi/com.dotcms.hooks/src/main/java/com/dotmarketing/osgi/hooks/SamplePreContentHook.java#L38) 

### Expected behavior
The log lines for the checking method should be printed in catalina.out

## Acceptance Criteria

1. Unit test

**Comment by luisbacca** [comment]
PR : https://github.com/dotCMS/plugin-seeds/pull/62

**Comment by dsilvam** [comment]
Passed Internal QA: Additional logging present in dotcms.log after deploying Hooks plugin.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // Oracle // FF
