### ISSUE TITLE
dojo/parser error in console when adding more than 2 relationship fields - 5.2x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#18764]
In dotCMS 5.2.8 Content Types with more than 2 Relationship Fields cause dojo error in the console.

Related ticket:
https://dotcms.zendesk.com/agent/tickets/101608

Recreated issue in demo.dotcms.com:

Steps:
1. Create New Content Type called `Gen Con`
2. Add a **Text** field called `Title`, and check `Required`, `User Searchable`, and `Show in List`.
3. Add 3 new Relationship fields:
 a. First field named `Image`, related to the `Image` Content Type, and set `One to many`.
 b. Second field named `Image Small`, related to the `Image` Content Type, and set `Many to one`.
 c. Third field named `File`, related to the `File` Content Type, and set `Many to one`.
4. Open the Browser's Console.
5. Go to Content->Search.
5. Create new contentlet of the new `Gen Con` content type.

See the error in the console:
```
dojo/parser::parse() error Error: "Tried to register widget with id==FolderHostSelector1593015459695-tree but that id is already registered"
    Dojo 18
    handleCallback https://demo.dotcms.com/dwr/engine.js?b=5.3.2:861
    <anonymous> https://demo.dotcms.com/dwr/engine.js?b=5.3.2 line 600 > eval:6
    <anonymous> https://demo.dotcms.com/dwr/engine.js?b=5.3.2 line 600 > eval:7
    _eval https://demo.dotcms.com/dwr/engine.js?b=5.3.2:600
    stateChange https://demo.dotcms.com/dwr/engine.js?b=5.3.2:1648
    onreadystatechange https://demo.dotcms.com/dwr/engine.js?b=5.3.2:1493
build.js:2:66686
```

SCREENSHOTS:

![image](https://user-images.githubusercontent.com/49727631/85630678-aff9db80-b639-11ea-8aca-e83042729dec.png)

![image](https://user-images.githubusercontent.com/49727631/85630724-cd2eaa00-b639-11ea-870c-8800dd678b0d.png)

**Comment by fmontes** [comment]
Fixed here: https://github.com/dotCMS/core/issues/18152

**Comment by fmontes** [comment]
@jcastro-dotcms update new steps to reproduce this, so we have another test case to fix.

**Comment by jcastro-dotcms** [comment]
Steps have been updated.

**Comment by dsilvam** [comment]
Passed Internal QA: Not able to reproduce.

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps on release-5.3.5 and now I'm unable to reproduce
