### ISSUE TITLE
Workflow Action dialog always shows Push Publish option

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#18761]
Reproducible in dotCMS 5.3.2

The Workflow Action dialog shows the Push Publish options even if the Push Publish subaction is not included in the workflow action being executed.

### Steps to reproduce the behavior:
1. Add a new action to a workflow step
2. Check the "User can assign" option for the action under "Comment-and-Assign" section
3. Enable "Editing", "Locked", "Unlocked", "Unpublished" and "New" options under "Show When" section
4. Add only the "Save action" to the subactions (don't add Push Publish or Push Now subactions)
5. Save the action
6. Create a new contentlet for a content type that uses the workflow that contains the new action
7. Click the button to execute the new action for the created contentlet
8. The workflow action dialog shows, but includes Push Publish options, even if the Push Publish subaction is not included in the action being executed.

### Expected behavior
The workflow action dialog should allow the user to assign the workflow task, not the Push Publish actions if the action doesn't include the Push Publish subaction.

### Screenshots
Workflow action with "User can assign" option enabled:
![image](https://user-images.githubusercontent.com/2894221/85589207-9d16e500-b600-11ea-9e63-b2a07beb7775.png)

Workflow actions available for the content:
![image](https://user-images.githubusercontent.com/2894221/85589324-b4ee6900-b600-11ea-922a-bf56b8663846.png)

Workflow action dialog showing Push Publish options:
![image](https://user-images.githubusercontent.com/2894221/85589553-e36c4400-b600-11ea-939d-af5d9d34f955.png)

**Comment by erickgonzalez** [comment]
Passed Internal QA. Now if you check **User Can Assign** or **Allow Comments** or both it only shows the option(s) selected, not the PP dialog.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.3 // Postgres // FF
