### ISSUE TITLE
Apps: Resource API should consider License level to show results

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18762]
As Apps is an enterprise feature, all GET endpoints in the Apps Resource API should consider the license level to return results. When a community license is used, the endpoint shouldn't fail but return ~empty results~ a 403 error to keep consistency with others APIs. PUT, POST and DELETE requests shouldn't be affected by this change.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/18822

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // MySQL // FF
