### ISSUE TITLE
PP a self-joined relationship from the parent contentlet does not push the child contentlet

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#18775]
When you PP a contentlet that have a self-joined relationship, the "parent" contentlet should push the "child" contentment. Right now is not being pushed.

Steps to Reproduce:

1. Create a new content type and relate to itself
2. Create 2 contentlets (test1 and test2) and relate one to the other (test2 related to test1)
3. PP test2, since test1 is related to it should be pushed

**Comment by john-thomas-dotcms** [comment]
@bryanboza, 2 questions:hat PP filter are you using when you see this problem?

(Note that, future-forward, any bugs we file against PP will need to be specify the PP filter used).

**Comment by bryanboza** [comment]
Hey @john-thomas-dotcms :
1- Content and Relationships
2- This is new in 5.3.3

**Comment by erickgonzalez** [comment]
**Note to QA:**

E.g Test1 and Test2, Test2(acting as parent) is related to Test1(acting as child):
- Send contentlet with relationships, should send other contentlets (Sending Test2 should send Test1 as well).
- Send contentlet without relationships, but it's related to another one (Sending Test1 should not send Test2).

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18783

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.3 // Postgres // FF

**Comment by nollymar** [comment]
Integration tests implemented here: https://github.com/dotCMS/core/pull/18797
