### ISSUE TITLE
Apps - UI: Show the Enterprise Screen when the license level is Community

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18779]
If a user tries to load the Apps portlet, the Enterprise Screen should be shown indicating to the user that an Enterprise license is required

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1371

**Comment by nollymar** [comment]
Passed Internal QA: 

<img width="1467" alt="Screen Shot 2020-07-14 at 11 18 38 AM" src="https://user-images.githubusercontent.com/8741395/87450161-cd302300-c5c3-11ea-891f-13717f179252.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // Postgres // FF
