### ISSUE TITLE
Workflows not working in Oracle after upgrade to 5.3.x

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#18782]
Reported by a client: https://dotcms.zendesk.com/agent/tickets/101641

As part of this [Upgrade Task](https://github.com/dotCMS/core/blob/5.3.2/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05195CreatesDestroyActionAndAssignDestroyDefaultActionsToTheSystemWorkflow.java#L66): . dotCMS is setting the column value to `StringPool.BLANK`. I[n Oracle the Blanks are handled as NULLs](https://stackoverflow.com/a/13278879/886865):. One case where we are getting NPE is here: we expect the condition value is `""` and not `null`

https://github.com/dotCMS/core/blob/5.3.2/dotCMS/src/main/java/com/dotcms/workflow/helper/WorkflowHelper.java#L787

**Comment by jcastro-dotcms** [comment]
See potential hotfix code here: https://github.com/dotCMS/support/commit/cb6cc2c0cb4fb9466423255b11e0a079e81978e1

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18784/files)

**Comment by bryanboza** [comment]
Unable to test in 5.3.4, we have an error trying to upgrade. 
Here the log: https://gist.github.com/bryanboza/3cae42f61dd6e059d9e5471cd783206b 

Need retest in 5.3.5, seems was fixed on this PR: https://github.com/dotCMS/core/pull/18895/files

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 and now I'm able to upgrade and also use workflows without problems
