### ISSUE TITLE
Problems with Site Search and special characters

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#18781]
Reproducible in current demo (5.3.2)
Reported by a customer: https://dotcms.zendesk.com/agent/tickets/101695

1 - spin up a 5.3.2
2 - create a new page using blank template 
3 - add new content with the text `identificaçãotest`
4 - run a new site search
5 - check the site search and get no results for `identificaçãotest`... but do get a single result, the test page, for `otest`.

**Comment by wezell** [comment]
This is not an issue.  We ship with the standard analyzer for english by default.  In this case, the customer needs to update their es-sitesearch-settings and mapping files - seen here:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/es-sitesearch-settings.json
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/es-sitesearch-mapping.json

to use the Portuguese analyzer.  
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#portuguese-analyzer

Once they do this, site search should work as expected for `identificaçãotest`

My guess by looking at the settings is that the asciifolding is munging the search up. See this:

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html
