### ISSUE TITLE
Container error using templates from different sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18780]
We have problems when you use a file-based container and templates from different sites, we have a NotFoundInDbException and we are unable to edit the page. 

## To recreate: 
- Login as admin
- Create a new site 
- Add a new page on this site (using the default template)
- Open the page and try to edit to add some piece of content

## Stacktrace 
ST: https://gist.github.com/bryanboza/9eccb75cd8c597cf1542e58a1212dd5e

![image](https://user-images.githubusercontent.com/2641437/85771255-f9e5ce80-b6d8-11ea-936a-56bd578d1663.png)

## Expected 
We need be able to support that case since is a common use case 

## Testing info: 
Tested on release-5.3.3 // Postgres // FF 

**Fix: The fix was use always absolute path into the page's layout, the relative path only will be allow in advance template and it should be resolve using the current host.
Also was created a Task Upgrate to change all the relative path in not advance template into absolute path.
Also a Job was created to change all the host's name in the absolute path when the host's name was changed in edit content**

**Comment by jcastro-dotcms** [comment]
As @bryanboza said, this is a very common use case. Please treat this ticket as high priority

**Comment by fmontes** [comment]
Next release based on this conversation: https://dotcms.slack.com/archives/CE1TBQU00/p1593122028046400

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18935

**Comment by freddyucv** [comment]
**Note to QA**: Tested:

- Running the Task05370ChangeContainerPathToAbsolute Task upgrade with the end point
```

POST  http://localhost:8080/api/v1/upgradetask {
    			"upgradeTaskClass":"com.dotmarketing.startup.runonce.Task05370ChangeContainerPathToAbsolute"
			}
```

the follow statement was run in the data base before and after the task upgrade

select count(*) from template where drawed_body LIKE '%demo.dotcms.com%’,

the result before the tsk upgrade was 0, after was 43.
- A new page was created, add a File Container into the layout, and check in data base if the path is absolute.
- Created a new template in the Template manager and add a File Container into it, check in data base if the path is absolute.
- Created a new Template in the Template Manager, add a Container (any type), add a slide bar and add the same Container into it, check if the UUID are sequencials.
- A new page was created, Add a FileContainer (in the same site) into the Layout, copy the site checking the copy container check, and check that in the site the page is linked with the container in the new site and not with the container in the original site.
- A new page was created, Add a FileContainer (in the same site) into the Layout, copy the site unchecking the copy container check, and check that in the site the page is linked with the container in the original site.
  - Copied demo.dotcms.com, and create a new site named new_site_1, created a new page in new_site_1, and add a FileContainer from the demo.dotcms.com, copy the new_site_1 (created a new site named new_site_2), checking the copy containers check, Cheking that the containers in the new page in linked with the containers in demo.dotcms.com
- Change the host's name, in any host anc check that the all the page are working
- Create a new advanced template with a relative path, add this template to a new page, it should work in resolve the relative path in the current host, copy the site checking the copy containers check, the container in the new page should be resolve with the container in the new site.
- Created a new page add content into it, and rename the host, the page should has the content after the host's name.

**Comment by freddyucv** [comment]
PR
core: https://github.com/dotCMS/core/pull/19059
ee: https://github.com/dotCMS/enterprise-2.x/pull/743

**Comment by wezell** [comment]
**Container resolution strategy**
1. If the container exists on the //host referenced host, use it
2. If not there, try the default host

**Comment by wezell** [comment]
Also, we need to show the host next to the container in the layout screen.

**Comment by freddyucv** [comment]
PR:
core: https://github.com/dotCMS/core/pull/19122
core-web: https://github.com/dotCMS/core-web/pull/1419
ee: https://github.com/dotCMS/enterprise-2.x/pull/743

**Comment by dsilvam** [comment]
Needs work - All the cases above working, but the following case is not:
* Bring up an instance with starter, then rename `demo.dotcms.com` to `renamed.dotcms.com` and then execute the upgrade task (via curl, see comment from @freddyucv ). If you check the REST API por the page, you will see in `layout` the old site name (before renaming) instead of the new name.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/19260

**Comment by dsilvam** [comment]
Passed Internal QA: Failing case mentioned above is now working.

**Comment by bryanboza** [comment]
After the changes, now we are unable to change the template from a page that is using the template from a different site 
SC: https://github.com/dotCMS/core/issues/8538

**Comment by dsilvam** [comment]
Passed Internal QA: Failures reported by @bryanboza on the last comment are working as expected

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9. // Postgres // FF

**Comment by ian-b-cooper** [comment]
This is seen here [](https://dotcms.zendesk.com/agent/tickets/105352) as a current customer issue

**Comment by swicken-dotcms** [comment]
This will not be backported to 5.3.8.X as the changes are too extensive
