### ISSUE TITLE
Create Github Action to integrate CI/CD with slack

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#18796]
This integration consist in
- Send a Slack DM to the user responsible for a submitted/updated PR
- Send a message to the entire `ci-cd` Slack channel

The message being sent must have information about the PR overall status data as well as per every test type with the corresponding links to tests results and GA PR link.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18798
