### ISSUE TITLE
Host Aliases needs to be mapped as keywords

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18805]
We have an issue where a host alias matching the wrong values.  

For example, auth-client.dotcmscloud.com will match auth-testing.com because hyphen after the auth tokenizes the value.

We need to map host aliases as keywords if we are going to use elasticsearch to look them up.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/18829

Really a keyword not work for the Alias because it is a set of string split by whitespace so we use a whitespace analizaer instead
