### ISSUE TITLE
Add count to our GraphQL API 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18801]
See https://graphql.org/learn/pagination/

**Comment by AshishG09** [comment]
Hi @dsilvam ,

We would like to have the "totalCount" functionality as mentioned here https://graphql.org/learn/pagination/#end-of-list-counts-and-connections

Thanks!
Ashish Guhe

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19032

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/19065

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // Insomnia
