### ISSUE TITLE
Layout edit displaying incorrectly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18830]
## Steps to reproduce:

1. Use travel starter
2. Create a new page with "Default Template"
3. Add [this layout](https://user-images.githubusercontent.com/751424/86628177-c7648d00-bf86-11ea-95a7-591998cc611d.png)
4. Go to content and back to layout editor and see the error:

<img width="1792" alt="Screen Shot 2020-07-06 at 12 47 03" src="https://user-images.githubusercontent.com/751424/86628227-d5b2a900-bf86-11ea-9f6f-f4bdf516c4b2.png">

**Comment by alfredo-dotcms** [comment]
Findings so far:

- this only happens on pages that starts with `index*`in the URL and must be located in *root* (on any other folder does not happens)
- Only occurs when you switch from options in the right tab menu (eg: from *Content* --> *Layout*)
- If you are located in the url `http://localhost:8080/dotAdmin/#/edit-page/layout?...` and the layout is broken, you can reload your browser's page and then it will load fine
- this started happening on this commit `d10976e37fbd005724454de1ffbb088f340e5b48` June 5th

**Comment by alfredo-dotcms** [comment]
A temporary fix was found in https://github.com/dotCMS/core-web/pull/1375, so far what we have found is the following:

- For some reason the page's `State` is being mutated in `DotEditPageInfoComponent`, declared in `dot-edit-layout-designer.component.html`.
- The values `sizex` and `rows` in the `grid.config` object are being changed after the initial render (this only happens on the page called `index*` located in **root** specifically)
- The temporary fix makes a deep clone of the page state and pass it to the `DotEditPageInfoComponent`, so any mutation won't affect the original page state.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-5.3.4 // Postgres // FF
