### ISSUE TITLE
Wonky Field Reordering

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18834]
Seen on a few instances.  To reproduce:

1. Start with the empty stater
2. Edit the host field
3. Try to make the host field 1 column

![wonky-field-order](https://user-images.githubusercontent.com/934364/86789438-4dd7a800-c035-11ea-8ec7-f1e020249daf.gif)

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/19430

**Comment by freddyucv** [comment]
**Note to QA** Also test Push Publish with the host Content type in the empty starter

**Comment by dsilvam** [comment]
Passed Internal QA: Now the steps in the video result in one column one row.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes
