### ISSUE TITLE
New PP dialog sets everything to AM

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18843]
When you use the new push publishing dialog, there are a few issues:

1. Even though it is in 24h time, if you set it to publish at 16:00, it sets to publish at 4:00am
2. Please insure that the unpublish at works as well

bonus: If possible we should be able to type into the text box to quickly adjust the time

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1370

**Comment by erickgonzalez** [comment]
Passed Internal QA. Now it's respected the 24h format, tested against PUSH, REMOVE, and PUSH-REMOVE.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF
