### ISSUE TITLE
Add Content selector blows up for customers with lots of content types

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18840]
If you have a customer with 50 widget types, the selector when adding one to a page does not scroll - instead you have to scroll the screen which looks pretty bad.

![lots-of-content-types](https://user-images.githubusercontent.com/934364/86813416-27723680-c04e-11ea-8892-9ead4891daa2.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18894

**Comment by fabrizzio-dotCMS** [comment]
Looks good.  I created a lot of widgets. moved to edit mode on an existing page. Then tried adding a new piece of content in one of the existing containers. The dropdown loads correctly and is scrollable.

**Comment by bryanboza** [comment]
Fixed, I create a lot of widgets here and I'm able to scroll without problems
