### ISSUE TITLE
APPS - UI: Textarea/Inputs must have height to support 4 lines max 

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#18854]
~The textarea/inputs in the config form page must have height to support 4 lines max~
The max size should be set to 300px

**Comment by nollymar** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1373

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.5 // Oracle // FF
