### ISSUE TITLE
Unable to remove or set the default status on any index of site search

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#18872]
Once an index has been marked as default 
such status can not be re-assigned to any other index. 

You can not remove it or set it on a brand new index.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/18876

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF. Now we are able to remove the default and set new default indexes without problems
