### ISSUE TITLE
Reindex not working in Oracle, dotCMS startup failing

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#18878]
Client ticket: https://dotcms.zendesk.com/agent/tickets/101789

Oracle doesn't support LIMIT clause: https://github.com/dotCMS/core/blob/v5.3.3/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexQueueFactory.java#L151

FYI: we are already handling that case in the same class: https://github.com/dotCMS/core/blob/v5.3.3/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexQueueFactory.java#L294-L296

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18895

**Comment by bryanboza** [comment]
We have this one on this branch:
`11:12:00.024  WARN  cluster.ClusterFactory - cluster table scheme not setup. will catch up later:ORA-00933: SQL command not properly ended`

We need some work here

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4.1 branch // Oracle // FF
