### ISSUE TITLE
Create Angular interceptor to replace core-web.service

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18885]
The HTTPClient from angular that core-web service uses is deprecated, also core-web service is an interceptor which Angular now have we have two routes here:

1. Update core-web service to use the new http client, this is the shorter route
2. Create an http interceptor and remove core-web service from the whole app.

I incline for the 1.

**Comment by alfredo-dotcms** [comment]
Duplicate: https://github.com/dotCMS/core/issues/19073
