### ISSUE TITLE
You can still add a field with variable host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18882]
re: #17515 
re: #18603

It is possible via the UI to create a field with a reserved variable, such as "host".  This has the unfortunate effect of making any Push Publishing event for that content type fail.
```
18:30:25.714  INFO  util.ActivityLogger - class com.dotmarketing.util.ActivityLogger: system : Save Field Action , User system/system user added field fields-1 to Banner Structure.
18:30:25.717  ERROR handler.ContentTypeHandler - An error occurred when processing Content Type in '/Users/will/git/dotcms5/tomcat8/webapps/ROOT/assets/bundles/formBundle-01ED7PTCVSSZ2Z9KQM50WDTSTW/working/bancosantander.dotcms.io/4c441ada-944a-43af-a653-9bb4f3f0cb2b.contentType.json' with ID 'Banner': 4c441ada-944a-43af-a653-9bb4f3f0cb2b
com.dotmarketing.exception.DotDataException: Field variable not compatible with GraphQL. Field variable:host
	at com.dotcms.contenttype.business.FieldFactoryImpl.getFieldVariable(FieldFactoryImpl.java:302) ~[classes/:?]
	at com.dotcms.contenttype.business.FieldFactoryImpl.dbSaveUpdate(FieldFactoryImpl.java:252) ~[classes/:?]
	at com.dotcms.contenttype.business.FieldFactoryImpl.save(FieldFactoryImpl.java:161) ~[classes/:?]
	at com.dotcms.contenttype.business.FieldAPIImpl.save_aroundBody0(FieldAPIImpl.java:208) ~[classes/:?]
	at com.dotcms.contenttype.business.FieldAPIImpl$AjcClosure1.run(FieldAPIImpl.java:1) ~[classes/:?]
```

  I am not sure if this is because of the graphql refactor.  When a user tries to create a field with a reserved word, the system should suggest/force a valid variable such as `host1`.

[formBundle-01ED7PTCVSSZ2Z9KQM50WDTSTW.tar.gz](https://github.com/dotCMS/core/files/4921829/formBundle-01ED7PTCVSSZ2Z9KQM50WDTSTW.tar.gz)

**Comment by wezell** [comment]
1. Allow existing fields - those coming in with an id and variable (via pp or whatever) to be persisted as is.
2. For any new fields being added where the variable is not specified, we should save with a non-conflicting variable
3. When generating the graph on graphql, and a content type has a conflicting variable, we should prepend an underscore to the content instance variable (not the content interface variable).

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18897

**Comment by dsilvam** [comment]
Note to QA:
* Test 1: creating a new field with name `Host` results in a variable `host1` or so... but not `host` 
* Test 2: forcing a new field variable to be `host` (sending it via REST) should result in: 
  * No errors in GraphQL schema generation 
  * The `host` field won't show its value but the inherited field's value instead 
  * Push-publishing the content type should work

**Comment by freddyucv** [comment]
**Passed Internal QA**: Tested

- Create a Content Type with a field with name 'host', the alias was createed with variable name equals to 'host1'.
- Send a Push publish request with the new Content Type after change directly in database the variable name by 'host',  and it work ok, Also send a GraphQL request trying to get the host field name and it work ok too
- Create a new content type with a field with variable name equals to 'host' and it was created with the host variable name

**Comment by bryanboza** [comment]
Fixed, now I'm unable to create fields with this variable, we are adding a # at the end of the variable. Tested on master // Postgres // FF
