### ISSUE TITLE
Set ES custom mappings when a field is created

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18887]
Currently, custom ES mappings are applied only when a full reindex is run. It would be great if those mapping could be applied automatically when a new field is created. In case of any failure setting the mapping, we should log errors but don't prevent the saving of the field nor the creation of content.

This requirement applies for PP too. Meaning, if a new field is pushed, the ES custom mapping should be applied (if possible) without interrupting the push in case of failure.

**Note to QA and Doc:**
When a field is created, the `esCustomMapping` field variable is ignored, as the field variable is saved after the field is created, not as part of the field creation process itself. Therefore, the `esCustomMapping` will be applied only after a full reindex as always. 

However, during field creation only these mappings will be applied without requiring a full reindex: 
- `keyword` in case of relationship fields
- `bool` for boolean
- `integer` for numbers
- `float` for decimals
- `text` for text fields

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18899

**Comment by nollymar** [comment]
**Note to QA:** 

The scenarios described on this [comment](https://github.com/dotCMS/core/issues/18689#issuecomment-658855478) need to be tested when a new field is created. Please take a look at the "Note to QA and Doc" above where precedence orders are described.

Besides, it is important to verify that PP works correctly and the receiver maps fields in its indices  accordingly.

**Comment by alfredo-dotcms** [comment]
3 tests done and checked with kibana:

A) created fields and verified without reindex
B) added customMapping and verified after reindex
C) PP fields created and verified on receiver host after reindex

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // Kibana
