### ISSUE TITLE
Create a LoggerResource

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18889]
Create a Logger Resource that allow us to change the log level of an appender

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/18896

**Comment by erickgonzalez** [comment]
When an invalid level is sent should throw a 400 Bad Request, `Invalid Level`.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18910 for feedback

**Comment by erickgonzalez** [comment]
With the latest changes now the resource works as it should and throws the response according to the error.

**Comment by bryanboza** [comment]
We need to validate some kind of permissions here, right now we are able to change that just with a registered user, no matter if have admin privileges or not

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 branch // Postgres // FF. My last comment was a confusion with a saved session cookie
