### ISSUE TITLE
File name header on layout is not present until the layout is saved. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#18892]
1. Select any page and go to Edit Mode - Layout. ( missing header) 
2. modify the layout. 
3. save the layout.
4. now the header is present, in the top left corner. 

![image.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/eecbcb10-e79d-41a0-87b1-3cbda8d4e90c)
![image.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/fabac5b1-a902-4cee-a67f-25997158025a)

**Comment by alfredo-dotcms** [comment]
Not able to reproduce on master
https://monosnap.com/file/GOfWogcHw1zIzLYrqTwG17AV2sv62E

**Comment by bryanboza** [comment]
Unable to reproduce on master, we have recent changes on this part
