### ISSUE TITLE
Never include SYSTEM_HOST or SYSTEM_FOLDER in bundle

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18893]
Every dotCMS instance should already have a SYSTEM_HOST and a SYSTEM_FOLDER.  We should never include them in our bundles.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/754

**Comment by dsilvam** [comment]
Passed QA: Given by our automated tests.
