### ISSUE TITLE
NPE on Site Browser when opening folders

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18901]
This is happening on 5.3.4 and 5.3.5 with auth data. 

When clicking on a folder on Site Browser, you get the spinning forever and a NPE on the network tab coming from DWR

**Comment by wezell** [comment]
Good.  I think we need to write a test that serializes / deserializes types of content then calls the map transformers on them.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18913
