### ISSUE TITLE
SQL Error in Oracle on cluster init 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18918]
The following WARN is shown when starting up in Oracle:

```11:12:00.024  WARN  cluster.ClusterFactory - cluster table scheme not setup. will catch up later:ORA-00933: SQL command not properly ended```

**Comment by dsilvam** [comment]
PR core: https://github.com/dotCMS/core/pull/18919
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/738

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4.1 branch // Oracle // FF
