### ISSUE TITLE
File based container-structures are based on title of asset, not FileName 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18921]
If you have a file based container, the available content types for that container should be based on the file names of the files in the folder.

Our issue is that we base the content type variable on the title of the file asset - which is very different than basing it on the File Name.

You can reproduce this issue on our starter site.  
1. Open the /application/containers/default/banner.vtl
2. Change the title - not the file name to I_am_not_a_banner.vtl
3. Go to edit mode and try to add a banner.  It is no longer in the list of available content types.
4. Hit the page API endpoint, you will see the wrong content type var being sent by the api

The list of container-structures should be based on the file name, not the title.

This is probably broken in webdav too.  

![Screen Shot 2020-07-20 at 5 35 24 PM](https://user-images.githubusercontent.com/934364/87989206-99676880-caaf-11ea-9a87-d379f5c53864.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18924

**Comment by victoralfaro-dotcms** [comment]
![image](https://user-images.githubusercontent.com/64026161/88687492-8e1acb00-d0b5-11ea-8074-d79e857697db.png)
![image](https://user-images.githubusercontent.com/64026161/88688391-81e33d80-d0b6-11ea-9b91-2081aa9c1606.png)
```
{
"entity": {
"canCreateTemplate": true,
"containers": {
"//demo.dotcms.com/application/containers/default/": {
"containerStructures": [
{
"id": "7673e601-26d4-4dbc-b6ad-7028599df656",
"structureId": "4c441ada-944a-43af-a653-9bb4f3f0cb2b",
"containerInode": "a40481db-680e-47b3-99c9-025b00cb5883",
"containerId": "69b3d24d-7e80-4be6-b04a-d352d16493ee",
"code": "#dotParse(\"//demo.dotcms.com/application/containers/default/banner.vtl\")",
"contentTypeVar": "Banner"
},
...
}

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
