### ISSUE TITLE
Workflow: Creating new Workflow Action results in a duplicate Action in the Workflow Step

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#18929]
## Describe the Issue

When you create a new Workflow Action, type in the Title of the action, and then hit save, the Action is created in the Workflow Step twice.

## Steps to Reproduce

1. Create a new Workflow Action.
2. Enter the Name of the new Action.
    * It can be any name, just make sure it doesn't match the name of another existing Action.
3. Press the "Save" button **without** first clicking in another field on the screen.
4. Click the "Cancel" button to return to the Workflow Scheme view.
    * **Result:** There are now 2 copies of the Workflow Action in the Workflow Step.
5. Open each of the duplicate actions and view the "Action Id" fields.
    * **Result:** Both actions have the same name, but different Ids (meaning there really were two different Actions created).

## Proposed Solution

This appears to happen because we automatically create an action when the user types in a name, and then moves out of the Name field.  But if the user moves out of the Name field to hit the Save button, we save twice - once automatically, and once because the user hit the Save button (when the action did not yet have an Action Id assigned).

The simplest solution, then, may be to change the automated save logic to either:

* Delay for half a second or so, and check again if the action has an Id before performing the auto-save, or
* Recognize that the Name field was exited to hit the Save field, and do nothing in that case.

## Environment

OS: Win 10 Pro
Browser: Chrome and FF
Version : 5.3.4 (demo)

**Comment by erickgonzalez** [comment]
Reproduced in demo(22.10.1)
