### ISSUE TITLE
Add a System Secrets yaml folder

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18939]
We need to add an /apps under /src/main/resources/apps
and use this folder to store the system apps YAML, such as for SAML.

This folder will hold the yaml files that we ship with. We should also read the files in the asset/server/apps folder and merge the results as our available apps.

System folder app should take precedence over apps in the asset/server/apps folder

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18965

**Comment by nollymar** [comment]
Passed internal QA

**Comment by nollymar** [comment]
This [PR](https://github.com/dotCMS/core/pull/18997) fixes the issue reported above

**Comment by bryanboza** [comment]
Fixed, now we have this folder in the core repo
