### ISSUE TITLE
Run Integration tests for each db in parallel in Github Actions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18938]
On merges to the `master` branch the integration tests are run on each DB we support. I.e. Postgres, MySQL, Oracle, SQL Server.

These can be run in parallel to minimize execution time. Currently they run in serial. 

![image](https://user-images.githubusercontent.com/1576794/88099570-f707bd80-cb60-11ea-8176-c905c36cc818.png)

**Comment by wezell** [comment]
Closing - Dupe: #19034
