### ISSUE TITLE
Bring back GraphQL Fields for BaseType Interfaces 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18946]
Some time ago we removed the fields from the GraphQL Interfaces representing Base types in dotCMS. See https://github.com/dotCMS/core/issues/17560. 

We need them back but not as a hardcoded list but instead dynamically getting them from each BaseType list of required fields.

As of version 5.3.7, this will be the list of available fields per Base Type:

* [ Page Base Type ](https://gist.github.com/dsilvam/32fa657592d186aacf0f2dc1adb9882a)
* [ Persona Base Type](https://gist.github.com/dsilvam/800cbef3d3905970ef5ec906e97ab0f1)
* [ FileAsset Base Type](https://gist.github.com/dsilvam/0056c313c740819ef0af72f96e406bad)
* [KeyValue Base Type](https://gist.github.com/dsilvam/34be86bab9ecd50879d13101f70d4872)
* [Widget Base Type](https://gist.github.com/dsilvam/f98bce08a124fb321c0775b524de858e)
* [VanityURL Base Type](https://gist.github.com/dsilvam/0c7594c968ffcd63abf1b4dcc9316d35)
* [DotAsset Base Type](https://gist.github.com/dsilvam/dd9218bae82d473fc061e3cc49968269)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19014

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19014

**Comment by dsilvam** [comment]
Note to QA: The available fields are in the postman test collection called `GraphQL.Test BaseType fields`

**Comment by freddyucv** [comment]
**Passed Internal QA**: Check postman test

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/graphql#BaseTypes
