### ISSUE TITLE
dotCMS startup failing on MSSQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18940]
We have an error starting a dotCMS instance using MSSQL as a database. 

We are unable to import the `user_preferences` and the server is not starting up.

Here the error: https://gist.github.com/bryanboza/179853334265ea81859c8bd92398d816

Tested on release-5.3.4.1 // mssql-2017 // FF

**Comment by dsilvam** [comment]
I tested with the same Docker image we use for our tests (`image: "mcr.microsoft.com/mssql/server:2017-latest"`) and this didn't happen. I was able to start without problems.
