### ISSUE TITLE
Allow dotGenerated folder placement to be configurable

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18958]
dotCMS has always stored the dotGenerated files under the assets directory.  For clustered sites that do large amounts of image transformations, this can cause large amounts of network traffic as images are read and written as they are transformed.

We need to be able configure dotCMS to store dotGenerated assets under local storage in order to minimize the I/O over nfs.  This has the downside of forcing every dotCMS instance to do their own image transformations and to consume local storage, rather than sharing the burden and storing everything on nfs, but in performance tests, doing the image transformations locally performed much better than using the nfs based storage.

**Comment by wezell** [comment]
dotCMS default behavior can be configured via the dotmarketing-config variable - either LOCAL or SHARED. The default is LOCAL.  If the value is not set, then dotCMS will store the generated files in the LOCAL e.g. dotsecure directory

`DOTGENERATED_DEFAULT_PATH=SHARED|LOCAL`

**Comment by wezell** [comment]
PR: #18967

**Comment by dsilvam** [comment]
Passed Internal QA: By default `dotGenerated` is now stored under `dotsecure`, but changing`DOTGENERATED_DEFAULT_PATH` to `SHARED` makes `dotGenerated` to live under `assets`

**Comment by bryanboza** [comment]
Fixed, tested based on the last comment, tested on release-5.3.6 // Postgres // FF
