### ISSUE TITLE
Move the EMA plugin into an dotcms app

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18962]
As a stakeholder, I want to have the EMA plugin into a dotcms app to ship with dotcms out of the box.

EMA plugin: https://github.com/dotcms-plugins/com.dotcms.ema

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18985

**Comment by erickgonzalez** [comment]
**To Test:**

1- Add the APPS Tool
2- Navigate to the APPS Tool and select the EMA APP
3- Click over one host and set the value of your rendering server
4- Save the app configuration
5- Navigate to Browser Tool and the index page

The content that should show up is your rendering server.

**Comment by bryanboza** [comment]
Fixed, after configure the service, now we are doing the call every time you try to open a page
