### ISSUE TITLE
GraphQL - Fetching a contentType collection with no content produces error

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#18977]
Steps to reproduce: 

1. Create a new Content Type. Don't create content for it 
2. Try to fetch the GraphQL collection 

A 500 error will be returned

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18978

**Comment by victoralfaro-dotcms** [comment]
New Content Type created
![image](https://user-images.githubusercontent.com/64026161/88730582-a1e52200-d0f3-11ea-9019-22635706f3c0.png)

GraphQL Query executed without errors
![image](https://user-images.githubusercontent.com/64026161/88730616-b9bca600-d0f3-11ea-8234-9cad4e70ffab.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // Insomnia 
![image](https://user-images.githubusercontent.com/2641437/89344754-9cdc2180-d663-11ea-93b1-dad9b3958e63.png)
