### ISSUE TITLE
APPs - UI: Add markdown support for hint field in Form Detail Page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#18973]
As an user I want to have support to use `MARKDOWN` in the **hint** fields of the form detail page.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1389

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
