### ISSUE TITLE
Implement a rest that returns user based on a role

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#18979]
When the next assign Popup is showed, Angular needs the list of the users (if the next assign is a role) to fill up the select to choice the next assign user.

**Comment by wezell** [comment]
There is a bit more logic to this than just calling getUsersForRole - there is a switch that says " Include Users from Parent Roles" that can be selected if the chosen role is an actual role and not a user.  We need to maintain that logic

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18984

**Comment by erickgonzalez** [comment]
Tested working as it should.

**Note to Doc:**
API: 
`/api/v1/roles/{roleId}/rolehierarchyanduserroles` -> get Role and User of the specific roleId
`/api/v1/roles/{roleId}/rolehierarchyanduserroles?roleHierarchyForAssign=true` -> get Role and User of the specific roleId and their respective parents
`/api/v1/roles/{roleId}/rolehierarchyanduserroles?name={roleName}` -> get Role and User of the specific roleId and filter the result by name (starts with)

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/rest-api-endpoints#RoleResourceRules
