### ISSUE TITLE
_text fields should not be created in the ES index by default

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18988]
Currently, `_text` fields are being created in the index for each content field  with the purpose of being used in queries that require an equivalent `text` field. This change was implemented when we migrated to ES 6. However, those fields have never been used and should only be created if the property `CREATE_TEXT_INDEX_FIELD_FOR_NON_TEXT_FIELDS ` is on (its default value is `false`)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19205

**Comment by nollymar** [comment]
**Note to QA:** To test this change you just need to run a full reindex with this property `CREATE_TEXT_INDEX_FIELD_FOR_NON_TEXT_FIELDS ` on/off and verify with kibana whether `_text` fields are created accordingly.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
