### ISSUE TITLE
Need to improve the yaml validations on PP filters 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18986]
Related to #18705

- As we do in the apps portlet, we need a better error validation, this because we are validating withe spaces but not if you remove a required property or if you add a property that is not expected. The same thing if a boolean property is set as a numeric value, If you try this will have an NPE when you try to execute

- Also, we need to add some info in the log regarding the file that will be ignored by an error in the yaml file.

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18705#issuecomment-664670146_

Reasons for the YAML can be ignored:

- [X] - Without White Spaces between property and value
- [x] - Remove required Property (**Title, Roles or Filters**, **default** property if not set it will be set to true as default, properties inside **Filters** are not required).
- [x] - Add New Property.
- [x] - Add New Property to Filters property.
- [x] - Boolean property set as any other value than `true | false` e.g `default: blabla` (if you set the `default` value to a number it will be set as `true` this is how the yaml parser jar behaves, but if you set to any other string it will throw an error)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19054

**Comment by ivorpad** [comment]
Reasons for the YAML can be ignored:

 - Without White Spaces between property and value

**Passed an invalid YAML property `default:false` — got an error the length of `entity` is 4.**

```bash
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 33]
20:33:18.951  WARN  publishing.PushPublishFiltersInitializer - while scanning a simple key
 in 'reader', line 2, column 1:
    default:false
    ^
could not find expected ':'
 in 'reader', line 3, column 1:
    roles: DOTCMS_BACK_END_USER
    ^
```

 - Remove required Property (Title, Roles or Filters, default property if not set it will be set to true as default, properties inside Filters are not required).

**After removing any of the required properties I get a warning and `entity` length is 4.**

```bash
20:37:23.334  WARN  publishing.PushPublishFiltersInitializer - unable to load PP filter:/Users/ivor/development/dotcms/tomcat8/webapps/ROOT/assets/server/publishing-filters/ContentOnly.yml cause: 1 error(s): The required field `Title` isn't set on the incoming file.
20:37:23.334  WARN  publishing.PushPublishFiltersInitializer - 1 error(s): The required field `Title` isn't set on the incoming file.
``` 

 - Add New Property.

**Added a new unknown property, got a warning and `entity` length is 4.**

```bash
20:39:59.191  WARN  publishing.PushPublishFiltersInitializer - Unrecognized field "hello" (class com.dotcms.publishing.FilterDescriptor), not marked as ignorable (6 known properties: "default", "title", "defaultFilter", "filters", "roles", "key"])
```

 - Add New Property to Filters property.

**Added a new unknown property to the filters property got a warning and `entity` length is 4.:**

```bash
20:46:42.991  INFO  publishing.PushPublishFiltersInitializer - FilterDescriptor{key=ContentOnly.yml, title=Content and Relationships, default=false, roles=DOTCMS_BACK_END_USER, filters{{excludeQuery=, excludeClasses=[ContentType, Template, Containers, Folder, Host, Links, Workflow, Language, Rule, User, OSGI], dependencies=true, excludeDependencyQuery=, excludeDependencyClasses=[ContentType, Template, Containers, Folder, Host, Links, Workflow, Language, Rule], forcePush=false, relationships=true, hello=true}}}	
```

 - Boolean property set as any other value than true | false e.g default: blabla (if you set the default value to a number it will be set as true this is how the yaml parser jar behaves, but if you set to any other string it will throw an error)

**Default boolean set to `hello` and got a warning, again the entity array's length is 4.**

```bash
20:50:50.311  WARN  publishing.PushPublishFiltersInitializer - unable to load PP filter:/Users/ivor/development/dotcms/tomcat8/webapps/ROOT/assets/server/publishing-filters/ContentOnly.yml cause: Cannot deserialize value of type `boolean` from String "hello": only "true" or "false" recognized
 at [Source: (sun.nio.ch.ChannelInputStream); line: 2, column: 10] (through reference chain: com.dotcms.publishing.FilterDescriptor["default"])
20:50:50.311  WARN  publishing.PushPublishFiltersInitializer - Cannot deserialize value of type `boolean` from String "hello": only "true" or "false" recognized
```

Once I set everything back 5 filters are returning again.
