### ISSUE TITLE
Contentlet buttons doesn't show on edit mode with an EMA page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18996]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fmontes** [comment]
I did a little fix using `setInterval` works but not ideal. Needs to find a better solution.

**Comment by wezell** [comment]
We need something here.

**Comment by fmontes** [comment]
Closed in favor: https://github.com/dotCMS/core/issues/19711

**Comment by erickgonzalez** [comment]
Not relevant to 21.06 LTS
