### ISSUE TITLE
Key/Value field back as string in the page API

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18990]
**Describe the bug**
When you have a page with a piece of content that have a Key/Value field the response of that field is an string of an object instead of the objet itself

**To Reproduce**
1. Go to https://starter.dotcms.com:8443/api/v1/page/render/store/products/tecnica-jt-3-pearl-girls-ski-boots-2020
2. Search for the `specifications1` field
3. See the response there

![Screen Shot 2020-07-28 at 11 55 36](https://user-images.githubusercontent.com/751424/88702932-49009400-d0c9-11ea-8605-97ef84609674.png)

**Expected behavior**
It should be an object so in the FE we don't have to parse it

## Acceptance Criteria

1. Fix the response accordingly
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
Key Value should always come back as an object.

**Comment by fmontes** [comment]
Check this in all the other endpoints

**Comment by fmontes** [comment]
I checked content, graphql, es search api and all worked as expected, the only problem is in the Page API.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/19278/files)

**Comment by bryanboza** [comment]
Fixed, tested on release 5.3.9 // Postgres // FF
