### ISSUE TITLE
Automate EE jar build and push to repo

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18992]
Whenever a merge is made into EE master, we should automate the build and push of the ee jar to artifactory

1.  Docker Image 
We need to develop a private docker image that takes a EE commit and optionally a dotCMS commit (default to master) and  builds the ee. jar and push it to repo.dotcms.com when the build is complete. We can use the SHA hash as a naming convention when we push the ee.jar to repo.dotcms.com

2. GitHub action that fires whenever a merge to master is made that builds and pushes the ee jar.

3. we can see where else we need to automate

Please complete #18994 before this task

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/744
