### ISSUE TITLE
Limited User unable to use File Based Container

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18991]
Using file based containers in a new template that utilizes the template designer. Our users are able to select the templates but, they are not able to make changes to the templates via the layout tab. They get a not found error when trying to save after adding a container or row. We have traced this to a permission issue as I do not get the same issue logged in as a super user. We created a user group called Template Designer and tried to add some users to that group. What permissions do we need to give our users in order for them to utilize the layout feature in our templates that are using the template designer?

Our file based containers are located in the /application/containers folder and the templates are called Landing Page - Template Designer and Standard Page - Template Designer. We placed the Templates in their own Layout tab in order to permission the templates separate from other content.

We were told to use the global “tempalate-layout” permissions on the website host. We tested this, but were not able to make it work. Here are the results of our testing:

- tested w/ normal user permissions = cannot see templates
- added template designer role = can see templates, add to page, lock for editing, adding a container via the layout tab results in "OK" message (failure)
- added view templates-layouts on host for template designer role = no change
- added edit templates-layouts = no change
- added view templates = no change
- added edit templates = no change
- added main view permissions = no change

Via:  https://helpdesk.dotcms.com/hc/en-us/requests/101188 
Would it be possible for you to get us some specific documentation on how to permission file-based containers for user access

**Comment by jdotcms** [comment]
I wasn't able to reproduce it locally

These are the permissions for the limited user
<img width="1374" alt="Screen Shot 2020-09-16 at 2 06 09 PM" src="https://user-images.githubusercontent.com/19578350/93387055-d9d03200-f825-11ea-80dd-8443241a10ee.png">

and I give permission over the Blog (which is one of the content types of the default file container)
<img width="1466" alt="Screen Shot 2020-09-16 at 2 07 43 PM" src="https://user-images.githubusercontent.com/19578350/93387172-07b57680-f826-11ea-93a8-a39910ee1f6c.png">
 
and I was able to modify the layout as a Joe Contributor and add Blogs

<img width="1547" alt="Screen Shot 2020-09-16 at 2 08 55 PM" src="https://user-images.githubusercontent.com/19578350/93387319-40555000-f826-11ea-9a42-3b279612d8dc.png">

**Comment by jcastro-dotcms** [comment]
After further discussion and troubleshooting, the issue was caused by a missing VIEW permission. This ticket can be closed.

**Comment by bonddenn** [comment]
Unfortunately, further testing has revealed that the view permission in question did not fully resolve this issue. It only served to clarify the issue somewhat. Here are the permissions we are using:

Host/Site:
![site](https://user-images.githubusercontent.com/71653200/93780537-49636a00-fbf6-11ea-8027-f7c1cff5c5db.jpg)

Folder:
![folder](https://user-images.githubusercontent.com/71653200/93780546-4c5e5a80-fbf6-11ea-9df8-b7a785a5ef25.jpg)

This user also has View/Edit/Publish permissions for many content types.

Currently, when we edit our page we can go to the Layout tab, add/remove layout boxes (such as columns) and containers, and save. When we go back to the Content tab, everything seems to work (this is what we saw on our call). However, if an administrator then clears the Template cache or we wait for a long time, the layout boxes (columns) will reappear, as will any containers we remove. The Layout tab may no longer match the containers shown on the Content tab. I can replicate this every time, so please let me know if you'd like to jump on a quick call to see it.

Please reopen this ticket, as this continues to be a critical issue that's blocking our use of the layout tool.

**Comment by bonddenn** [comment]
I should also mention that these permissions have only worked on our development server. Identical permissions are not working on our production server at all. On production, a user with these permissions still cannot successfully save any layout changes on the Layout tab.

**Comment by jdotcms** [comment]
wasn't able reproduce, even after cache clean the layout and content still ok

**Comment by bonddenn** [comment]
@jdotcms what are your permissions in the /application folder and on the container.vtl files?

**Comment by wezell** [comment]
@bonddenn we are unable to reproduce on the latest version locally.  Can you still reproduce this behavior on demo?  We would be happy to jump on a call if you can so we can look at it together.

**Comment by bonddenn** [comment]
@wezell yes, happy to do that whenever you guys are available

**Comment by bonddenn** [comment]
just to update you, we are in the queue for a dotCMS system update in the next week or two, and so our current plan is to wait for that to happen and see if this issue persists in our system. particularly because you cannot replicate it, but also because the update will simply happen before we can troubleshoot further.
