### ISSUE TITLE
D&D in WYSIWYG stop working

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19018]
**Describe the bug**
The ability to D&D images into a WYSIWYG stop working 

**To Reproduce**
1. Go to edit a content with a WYSIWYG field
2. D&D an imagen into the WYSIWYG field
3. Nothing happen

**Expected behavior**
It should allow users to drop images and insert them

## Acceptance Criteria

1. Allow user to drop images in WYSIWYG fields
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
We need some work here: 

- If you drag and drop some file but don't select the specific folder we are uploading the asset, but we are not able to show the thumbnail, also we have a JS error on console 
![image](https://user-images.githubusercontent.com/2641437/89229373-89b34e00-d59e-11ea-8d89-21fed41e122e.png)

**Comment by fmontes** [comment]
I fix this by selections System Host by default, on dialog show.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // FF
