### ISSUE TITLE
From Browser, you can delete archived pages, regardless of workflow

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19015]
If you archive a page from the browser screen, you are still presented with a "Delete Page" option even though that option is not available in the workflow step the page is on.

![Screen Shot 2020-07-31 at 9 08 19 AM](https://user-images.githubusercontent.com/934364/89037941-6aea5880-d30d-11ea-9b88-2bfe74b61d01.png)

**Comment by wezell** [comment]
PR: #19016

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postrges // FF
