### ISSUE TITLE
Run Integration tests for each DB provider in parallel and on PRs

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19034]
Right now the Integration Tests are executed like the following:
* On PRs, only in Postgres
* On merges to master, in each DB Provider. I.e. Postgres, MySQL, Oracle, MSSQL. This happens sequentially.

We need to run on all DB Providers also on PRs but we need to run them in parallel to decrease execution time.

**Comment by wezell** [comment]
This should run as a Job Matrix

**Comment by wezell** [comment]
We also need to Ignore the `ESReadOnlyMonitorTest` as it takes 20m to complete.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19301
