### ISSUE TITLE
Adding mappings cause transactions to time out

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19033]
When creating new indexes, we are generating the ES mappings from the content type definitions and putting them to the index - this is good - the issue arises when a customer has a ton of content types and fields, the action of putting the mappings takes longer than our db Transaction timeout.  This is because the whole index creation process and mapping process is being done in a single transaction.

We need to break apart these actions into a mutli-step process
Step 1. transaction{
Create new indexes and add the default es- mappings and update the IndiciesInfo like we used to
}
Step 2. add the custom mapping based on the fields

Also, I think we might want to explore looping over the content types and putting the field mapping per content type (with logging) rather than in one giant put. 

Besides, it probably makes sense to build the mappings Json once and then apply it to both live and working, rather than doing all the work twice

Finally, when a number is mapped as a whole number and this number is bigger than the datatype limits, the index fails: 

```
bulk index failure:ElasticsearchException[Elasticsearch exception type=mapper_parsing_exception, reason=failed to parse field [directlanguage.id] of type [integer] in document with id '023deb52-6257-4bcd-a08f-e619467b070b_1'. Preview of field's value: 1572423270292']]; nested: ElasticsearchExcepti...
```
Integer values should be mapped as `long` and float values as `double`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19035

**Comment by nollymar** [comment]
**Note to QA:** This needs to be tested with a custom dataset. Please ask me

**Comment by dsilvam** [comment]
Passed Internal QA: Reindexed without issues on custom starter. Also retested #18689
#18887. Everything ok.

**Comment by bryanboza** [comment]
Fixed, able to reindex without problems
