### ISSUE TITLE
Unable to scroll in the collapsed menu

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19030]
If you add multiple items to some tab, and then collapse the main menu, when you try to see the portlets of this tab, we are unable to scroll to see the complete list 

![image](https://user-images.githubusercontent.com/2641437/89346578-8a171c00-d666-11ea-9968-3a2d65677aa8.png)

**To Reproduce**
1- Login as admin
2- Go to control panel --> roles&tools 
3- Select the admin role and add too many portlets in one tab
4- Collapse the menu
5- Try to see the items of the tab  

**Expected behavior**
We need be able to show the complete list or add a scroll here 

**Desktop (please complete the following information):**
Tested on release-5.3.6 // Postgres // FF

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1396/files
Video demo: https://monosnap.com/file/jZpVkjJbu13IXRdLuxHH3WLpzmNzup

**Comment by fabrizzio-dotCMS** [comment]
I added 30 items to a menu entry. I can see all of them without a problem. They collapse just fine. No scrollbar

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
