### ISSUE TITLE
UX: Need to recognize the 'Enter' key as accept when you are creating a new bundle  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19042]
When you try to add some piece of content to a bundle and you type any new name for the bundle and hit the `Intro` key, we need to recognize this as accept and create the bundle 

FYI: This works in previous versions 

**To Reproduce**
1. Login as admin 
2. Configure your push environment 
3. Try to add any piece of content to a bundle 
4. Type the name of the bundle and press Enter

**Expected behavior**
We need to create the bundle with the typed name when you press the enter key 

**Desktop (please complete the following information):**
Tested on release-5.3.6 // Postgres // FF

**Comment by nollymar** [comment]
**Internal QA:** Needs work
It only works if there is at least one bundle created. When there are no bundles and you try to add the first one, the Enter doesn't work.

**Comment by nollymar** [comment]
**Internal QA:** Now it works correctly,  but there is a debugger enabled that will make the execution stops if the JS Console is open 

![Screen Shot 2021-09-21 at 12 42 59 PM](https://user-images.githubusercontent.com/8741395/134221314-d8c4df77-e75f-4f92-8263-89530fb4d5cb.png)
