### ISSUE TITLE
Need to improve the error messages when you are uploading bundles 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19043]
Related to #18293 

After the related card, now we are able to download bundles using filters, but when any bundle with filters fail to upload the content, we need to improve the errors here, because right now the error is not explicit. 

![image](https://user-images.githubusercontent.com/2641437/89553751-278b6080-d7cb-11ea-807f-76ec6e8096b6.png)

**To Reproduce**
1. Login as admin
2. Create a new content type and add a piece of content 
3. Add this piece of content to a bundle 
4. Download the bundle using the filter "Only selected items"
5. Try to upload in a new server 

**Expected behavior**
We need to be clear with the error 

**Desktop (please complete the following information):**
Tested on release-5.3.6 // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
@bryanboza the error message above (in the bundle detail window image) actually looks OK to me.  It's relatively specific - the content type doesn't exist.

I think we could potentially improve it by showing the content type name as well as the content type ID, but I don't think that's critical for the user to figure out what went wrong with the bundle upload.

Are there some specific improvements you think we need in the error message there?

**Comment by erickgonzalez** [comment]
Not able to show the content type name, since the error is thrown in the handler (receiver) and since the content type doesn't exist we can't get the name.
