### ISSUE TITLE
Add an "Apply a Filter" option to the download bundle popup

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19048]
Add an "Apply a Filter" checkbox to the bundle download popup.  This will:

* Ensure that, by default, bundle downloads and uploads continue to work the same as in previous versions; and
* Prevent users from accidentally leaving content out of a downloaded bundle that is necessary for that bundle to be successfully uploaded.

This change will only apply to downloaded bundles, not to pushing content.  (For an explanation why download is different from push, please see **Additional context**, below).

## Describe the solution you'd like

1. When downloading a bundle, add an "Apply a Filter" checkbox to the popup.
    * This checkbox will always default to false (unchecked).
2. When the "Apply a Filter" checkbox is **_not_ checked** (the default state):
    * The PP filter selection field will show no filter name, and will be disabled.
    * The bundle will be downloaded without using a PP filter
        * Instead, the bundle will be downloaded the way bundles were downloaded before PP filters were implemented - with all dependencies included, and with the equivalent of Force Push enabled.
3. When the "Apply a Filter" checkbox is **checked**:
    * The PP filter selection field will be enabled.
    * The PP filter selection field will, by default, show whichever PP filter is specified as the default in the system (based on the value of the **default** fields in the filter files).

## Describe alternatives you've considered

Changing the default filter applied will not fully meet the needs, because:

* There is no guarantee that an appropriate filter exists on the server where the download is performed.
    * An appropriate filter would need to both include all content and perform a Force Push.
    * But since users can alter the PP filters any way they want, there's no guarantee such a filter will exist.
* The PP filter that makes sense as the default for pushing content may not (and often will not) be the best default filter for downloading bundles.
    * Downloading bundles has some fundamental differences from pushing content; see **Additional context** below.

## Additional context

Downloading and then uploading a bundle is fundamentally different from a content push in 2 ways:

1. The person uploading the bundle may not be the same person who downloaded it
    * ...and therefore the person uploading it may not know which filter was applied when the bundle was downloaded.
    * In fact, the person uploading the bundle may not even know what filters even exist on the server the bundle was downloaded from.
2. There may be a significant time delay between the download and the upload.
    * So even if the same person downloads and then uploads a bundle, they may not remember which filter was applied at the time of download.

Both of these mean that it's more important for us to default to "include everything" options when downloading a bundle than when doing a content push.

**Comment by jcastro-dotcms** [comment]
After double-checking with @john-thomas-dotcms , there is already an option to apply Push Publishing Filters to a bundle download. We can close this ticket now.
