### ISSUE TITLE
SVG files stuck in working state after copying/uploading to dotCMS

### ISSUE THREAD

**Issue by yasindilekci** [dotCMS/core#19058]
**Describe the bug**
When you copy an asset via the WebDAV protocol to dotCMS, the asset first goes into a "working" state and afterwards it goes into the "live" state. This is an automatic process that dotCMS handles for you.

It seems like that the assets are sometimes stuck in the "working" state, especially with SVG files. So the state of these assets are not updated from "working" to "live".

However, this not always the case. It's rarely that it gets stuck in the "working" state, but still it should not be happening. It prevens assets from getting live.

We have verified this with SVG files, please keep the focus on this file type.

**To Reproduce**
1. Get 30 to 40 random SVG files
2. Use any WebDAV software to copy over assets, we use Beyond Compare
3. Connect via WebDAV with URL https://demo.dotcms.com/webdav/live/1
4. Select **ALL** SVG files and copy them over (make sure to copy them all over at once to dotCMS via WebDAV)
5. Login to dotCMS admin, and check if all SVG files are in the "live" state. If they are, delete them all and reupload them until you get at least one SVG file which is stuck in the "working" state.

**Expected behavior**
All uploaded SVG files should be converted from "working" state to "live" state after copying/uploading them to dotCMS via the WebDAV protocol.

**Screenshots**
Usually an orange circle is being shown when an asset is in the "working" state. However, when this issue occurs, the orange circle is not showing, instead the green check mark is shown which is aligned left (this means "stuck in working state"), see screenshot below.

![screenshot-1](https://user-images.githubusercontent.com/10976988/89783975-25513b00-db18-11ea-9062-aa1b6d2604cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: does not apply, it's the WebDAV protocol.
 - Version: does not apply

**Smartphone (please complete the following information):**
 - Device: does not apply
 - OS: does not apply
 - Browser does not apply
 - Version does not apply

**Additional context**
Does not apply

**Comment by wezell** [comment]
I wonder if this is a dupe of #18626  - obviously you have not tried to reproduce in 5.3.5 but it would be worth a test.
