### ISSUE TITLE
Apps Label field do not match mock

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19063]
When configuring SAML, I saw an issue where the label is the same size as the hint field. Looking at the mocks, it seems like the labels should be a little bigger and heavier (bolder)

![Screen Shot 2020-08-10 at 3 21 27 PM](https://user-images.githubusercontent.com/934364/89822080-9d6e2f80-db1d-11ea-9fab-4d00bdeba081.png)
.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1400/

**Comment by fabrizzio-dotCMS** [comment]
I compared the current UI on master with the mocks in https://scene.zeplin.io/project/5e160be0a1eeb8521b342add
and also against the current version deployed in demo. The field label looks bigger and bolder.
