### ISSUE TITLE
Move Amazon Rekcognition to apps

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19060]
We have an actionlet that automatically tags images using Amazon's rekognition.  We need to update that, convert it to an app and add it to the apps we ship with OTB.

AWS Rekognition - https://github.com/dotCMS/com.docms.rekognition.actionlet

When an error executing the actionlet is reach, just log it and move on.

**Comment by erickgonzalez** [comment]
**Note to Doc:** This actionlet needs to be after the Save Actionlet since it relates the generated Tags to the contentlet inode.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19103

**Comment by ivorpad** [comment]
1. I tested with valid key and key secret and got the expected results.
2. If the Contentlet have tags the Amazon Rekognition tags are appended to the existing tags.
3. Tested with an empty binary and no tags were generated, but received: `20:16:31.385  WARN  actionlet.RekognitionActionlet - There is no Binary Field or an Image is not set in it`
4. Tested with a PDF and no tags were generated but received: `20:20:16.793  WARN  actionlet.RekognitionActionlet - There is no Binary Field or an Image is not set in it`
5. If there's no tags field: `20:14:44.582  WARN  actionlet.RekognitionActionlet - There is no Tag Field in the Content Type`
6. If there's no binary field: `20:15:47.644  WARN  actionlet.RekognitionActionlet - There is no Binary Field or an Image is not set in it`
7. It appears there's a bug after adding a file that's not an image. To reproduce:
     - Add an Image > publish > click the action name > close
     - Open > delete image > add a PDF > publish > click the action name 
     - Delete PDF> add an Image > click the action name
      - In the history there's a version with the PDF and the tags generated for the image
8. With invalid tokens I see an error in the logs: `20:28:38.640  WARN  actionlet.RekognitionActionlet - Unable to autogenerate the rekognition tags: The security token included in the request is invalid. (Service: AmazonRekognition; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 7a9ed2f1-78f9-42ae-bcf1-60f0877a7235; Proxy: null)`

**Comment by erickgonzalez** [comment]
Is not a bug, this is because you are generating tags without saving a new version of the contentlet, so it's adding them to the current one. The new image is not even been saved, if you close and open the contentlet you will still see the PDF.

As mentioned above: This actionlet needs to be after the Save Actionlet since it relates the generated Tags to the contentlet inode.

**Comment by bryanboza** [comment]
Fixed, tested and after configure the app, we are doing the call, unable to see if this works because we have no servers running to see how it is working, but I'm sure we are doing the call 
`12:18:08.102  INFO  ema.EMAWebInterceptor - GOT AN EMA Call --> /api/v1/page/render/QA/123123`
