### ISSUE TITLE
Not Allow delete Containers 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#19068]
**Describe the bug**

**To Reproduce**
1. Create a new container
2. Create a new page
3. Add the containers into the new page
4. Try to delete de container
5. The container is deleted

**Expected behavior**
Should show a message saying that the container can not be deleted, if you create a template in the Template Manager and add the cotainer into in, and later try to delete the container show the follow message:

<img width="626" alt="Screen Shot 2020-08-10 at 4 17 37 PM" src="https://user-images.githubusercontent.com/10408015/89837012-49674900-db25-11ea-98d5-cfd954868b86.png">

**Comment by wezell** [comment]
The issue with preventing the deletion of these containers is that 100s of pages with custom layouts could be using a container - their names would be meaningless - and this would be very painful to track down and fix.  I am ok messaging a warning that the container is still in use in templates and letting the delete happen.
