### ISSUE TITLE
Update core-web.service to use the non-deprecated httpclient

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19073]
We need to update Angular from 7 to 10: https://update.angular.io/#7.0:10.0 and to do that we need to update the httpclient we're using in `core-web.service` because is deprecated.

Here is the doc on the new httpclient: https://angular.io/guide/http

## Acceptance Criteria

1. Update core-web.service to use the new httpclient.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1431

**Comment by nollymar** [comment]
**Note to QA:** Run a smoke test of the whole app focusing on the requests made from UI

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, testes on release-20.10.1 // Postgres // FF
