### ISSUE TITLE
Incorrect filter name in the bundle details 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19075]
After we add the push publish filters, now we are showing the filter information in the bundle details when you push something, but here we show the name of the `yml` file of the real name of the filter 
![image](https://user-images.githubusercontent.com/2641437/89946745-9eb46080-dbe0-11ea-856d-2fa575dfc60b.png)
e filter instead of the filter name. 

We need to show the name of the filter here in order to avoid confusions to the end-user 

**To Reproduce**
1. Login as admin 
2. Configure your push environment 
3. Try to push anything 
4. Now in the publish queue try to see the bundle details 

**Desktop (please complete the following information):**
Tested on release-5.3.6 // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19390

**Comment by bryanboza** [comment]
Fixed, tested with every one of the filters and now we are showing the correct name. Tested on release-20.10.1
