### ISSUE TITLE
dotParse macro no longer shows the file name on pages

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#19078]
Tested on latest dotcms 3.5 on demo.dotcms.com using Chrome

The dotParse macro has always shown the name of the file as an editable link when placing the dotParse macro in a widget such as the VTL include widget.  For some reason, the link has now changed to the identifier of the file, which is not as helpful and ends up making it one step harder to know which file is being parsed on the page.

We need to return to displaying the name of the file in the link to the vtl being parsed as we have always done in prior versions.

![Screen Shot 2020-08-12 at 2 34 45 PM](https://user-images.githubusercontent.com/1569167/90054473-e94ddf80-dca9-11ea-976c-24ec3e0c5282.png)

**Comment by wezell** [comment]
Fixed in 5.3.8
