### ISSUE TITLE
Apps cannot store multi-line secrets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19074]
If you have a field in your app that has `hidden: true`, you cannot save a value that needs to support line breaks.  This is because the password field that we use to show the secret is only a single line.

We need to use a textarea and display the ***** as we do now, but that needs to be displayed in a text area.

We could implement something like this:

https://stackoverflow.com/questions/12895774/how-to-make-a-textarea-act-like-a-password-field

**Comment by alfredo-dotcms** [comment]
- hidden fields will behave like Textarea.
- once saved the data will be returned as **** from the BE
- if you change the value it will be visible until saved

**Comment by alfredo-dotcms** [comment]
*Note to QA: this only applies to hidden fields defined in the YML file, the dynamic fields that are hidden don't support this

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1409

**Comment by bryanboza** [comment]
I think this is not meged at the release branch, I still getting just a line of ***
![image](https://user-images.githubusercontent.com/2641437/91907682-82e42d80-ec67-11ea-86de-f467578a37fd.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF
