### ISSUE TITLE
Change order of tabs in Publishing Queue

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19071]
![Screen Shot 2020-08-11 at 12.11.46.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/240b431d-0ecc-411b-8007-a8fea0143fe3)

## Acceptance Criteria

1. Make Status / History first tab
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
