### ISSUE TITLE
Unable to logout from master 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19081]
If you are logged as admin, we are unable to logout this option disappear from the profile options 
![image](https://user-images.githubusercontent.com/2641437/90078159-38ebd580-dcc1-11ea-8ee4-0f7c0b861806.png)

**Expected behavior**
We need be able to logout, this when any user

**Desktop (please complete the following information):**
Tested on master // Postgres // FF

**Comment by alfredo-dotcms** [comment]
@bryanboza unable to reproduce with latest master in core-web!

try again with a fresh install

**Comment by bryanboza** [comment]
Fixed, this was fixed with a change of @fmontes this morning.
