### ISSUE TITLE
Create SYSTEM_THEME .vtls

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19086]
**Is your feature request related to a problem? Please describe.**
We want to ship dotcms empty but with the ability to create pages out of the box. 

A page needs a template, a template needs a theme and a container, we don't want the user to have to create all that for just create a page so we are creating a [SYSTEM_CONTAINER](https://github.com/dotCMS/core/issues/19080) and here a SYSTEM_THEME

**Describe the solution you'd like**
A theme can contain all this files:

![Screen Shot 2020-08-13 at 07 31 33](https://user-images.githubusercontent.com/751424/90140511-16949f00-dd37-11ea-83a7-b4b25169f318.png)

In this case we're going to create a theme with just ONE file `template.vtl` and inline that file we are going to have:

1. CSS grids and normalize
2. All the meta information
3. The layout HTML: rows, columns and sidebar
4. A box for the header and for the footer

**A page with this theme should look like this**

![Empty theme](https://user-images.githubusercontent.com/751424/90141451-5f008c80-dd38-11ea-8c0e-399e072862c9.jpg)

## Acceptance Criteria

1. Create a system theme
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19460/files

This will be integrated once the task https://github.com/dotCMS/core/issues/19080 gets done!

**Comment by alfredo-dotcms** [comment]
To test this manually, the steps are: 
- set your env with an empty starter
- in *Site Browser* add the `template.vtl` file into the path `/application/themes/system-theme`
- in *Containers*, create a new one with at least 1 `Max Contents` and add in `Content` at least `$title` to identify it later
- in *Templates*, create a new `Template Designer` (you should be able to see populated the `Theme` dropdown) 
- in *Site Browser* create a new page with the new template and start testing

Things to tests:
1. CSS grids (columns & rows)
2. All the meta information in header
3. The layout HTML: rows, columns and sidebar
4. A box for the header and for the footer

**Comment by alfredo-dotcms** [comment]
[template.vtl.zip](https://github.com/dotCMS/core/files/5393871/template.vtl.zip)

**Comment by nollymar** [comment]
**Internal QA:** I am not able to see the footer

<img width="1457" alt="Screen Shot 2020-10-26 at 4 21 28 PM" src="https://user-images.githubusercontent.com/8741395/97334951-48ec6d80-184b-11eb-9908-9cb3ebdf2767.png">

**Comment by alfredo-dotcms** [comment]
[template.vtl.zip](https://github.com/dotCMS/core/files/5555228/template.vtl.zip)

**Comment by alfredo-dotcms** [comment]
![Uploading image.png…]()
