### ISSUE TITLE
JS errors on edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19082]
We have some JS errors on the console when you open any page on edit mode 
![image](https://user-images.githubusercontent.com/2641437/90078984-d6e09f80-dcc3-11ea-8650-cededc808ab6.png)

**To Reproduce**
- Login as admin
- Try to edit some page 
- Check the browser console 

**Expected behavior**
We need to clear those errors 

**Desktop (please complete the following information):**
Tested on master // Postgres // FF

**Comment by alfredo-dotcms** [comment]
@bryanboza unable to reproduce with latest master in core-web!

try again with a fresh install

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last release-5.3.7
