### ISSUE TITLE
Move Template portlet to Angular

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19087]

**Comment by fmontes** [comment]
### Internal QA
- Needs right click
- Should we clear checkbox when show archive?
- The bulk actions result action always say archive
- When you delete several templates they get removed from the system and list but the state of the action button remains
    - After execute the actions we should uncheck all the elements
-

**Comment by hmoreras** [comment]
feedback items: https://github.com/dotCMS/core-web/pull/1542

**Comment by bryanboza** [comment]
After play a little bit on this portlet here some of the things that needs some work: 

- Problems using templates on Safari 
![image](https://user-images.githubusercontent.com/2641437/105246437-e00a4e00-5b38-11eb-943b-51fec6d67a86.png)
- When you are adding a new template, the ESC key should close the window 
- As in other portlets the archived ones should be represented by a red color 
![image](https://user-images.githubusercontent.com/2641437/105246871-78a0ce00-5b39-11eb-8862-908f6c515b6b.png)
- When you are filtering for a some specific content and we have no results, we need to hide the template list empty message 
![image](https://user-images.githubusercontent.com/2641437/105247009-b6055b80-5b39-11eb-862f-da39a3a06b52.png)
- We need to refresh the portlet when you change the site from the site component. 
- Unable to create templates with themes from another sites 
- Unable to bring back to previous versions from the  history tab
- The theme componen is not refreshing after you previously have changed the site component 
![image](https://user-images.githubusercontent.com/2641437/105248182-940cd880-5b3b-11eb-89fa-f5642483c916.png)
- Unable to publish the template from  the designer 
- We lost the preview tab (not sure if was on purpose)

**Comment by fmontes** [comment]
1. Looking which version I wasn't able to reproduce in `Version 14.0.1 (16610.2.11.51.8)`
2. Yes: https://github.com/dotCMS/core/issues/19838
3. New design
4. Yes: https://github.com/dotCMS/core/issues/19839
5. Yes: https://github.com/dotCMS/core/issues/19840
