### ISSUE TITLE
With SAML enabled, explicit logout takes you to the native login page, instead of re-authing through SAML

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19098]
## Describe the bug

When SAML is enabled, if a user explicitly logs out of the dotCMS back-end, they are taken to the `/dotAdmin/#/public/login` URL, instead of the plain `/dotAdmin` URL.  This page does not redirect to the SAML authorization.

This means that any time a user explicitly logs out of dotCMS, they can not log back in (or get reauthenticated) using SAML unless they explicitly type in the `/dotAdmin` URL.

## To Reproduce

1. Log into the back-end using SAML.
2. Log out from the back-end user menu, at the top-right of the screen.
**Result:** You are redirected to the `/dotAdmin/#/public/login` page, which displays the native login screen instead of authorizing through SAML.

## Expected behavior

I'm not sure why a logout redirects to the longer `/dotAdmin/#/public/login` URL to begin with, but I see at least 2 possible solutions:

1. Change dotCMS to login to the standard `/dotAdmin` path after a logout (instead of `/dotAdmin/#/public/login`.
2. Update SAML to recognize and perform authorization when the `/dotAdmin/#/public/login` path is hit (as well as the standard `/dotAdmin` path).

## Desktop (please complete the following information):

- OS: Win 10 Pro
- Browser: Chrome
- Version: dotCMS 5.3.6.1

## Additional context

This appears to be a hold-over from the behavior of the SAML plugin.  I think it's most properly classified as a long-time bug in the plugin that we've now brought into the core.

Since this has existed in the plugin for a long time, the priority might be closer to an enhancement request than a bug.  But with SAML now in core, more customers are likely to use SAML and run into this problem, so I think we should give it the priority of a regular bug (not an old bug).

**Comment by wezell** [comment]
Users need to bounce somewhere.  Maybe they should go to `/` ?

**Comment by john-thomas-dotcms** [comment]
Yeah, we could have a discussion about where a logged-out user should go - but I think going back to the login page is fine.  Which means they could just bounce to `/dotAdmin` - so if SAML is enabled it will take over, but if it's not they'll still hit the native login (so no real behavior change if SAML is not enabled, just a different URL).

**Comment by john-thomas-dotcms** [comment]
The only reason this is an issue is because logout adds `/#/public/login` to the end of the URL it bounces the user to.  So if we remove that from the bounce URL, or change SAML to intercept that, this issue will go away.

**Comment by wezell** [comment]
the logout screen in master:

![Screen Shot 2020-10-09 at 5 24 13 PM](https://user-images.githubusercontent.com/934364/95632749-55538680-0a54-11eb-8efe-1abf7efcdb6e.png)

**Comment by hmoreras** [comment]
after testing the styling issue, looks like a styling issue.

**Comment by erickgonzalez** [comment]
PR:https://github.com/dotCMS/core/pull/19366

**Comment by erickgonzalez** [comment]
Logout Page shows without issues.
<img width="1268" alt="Screen Shot 2020-10-14 at 4 25 17 PM" src="https://user-images.githubusercontent.com/5278970/96051971-db4b4500-0e39-11eb-957e-1c348796d38f.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.3.8.4 LTS release only. The 5.2.8.4 LTS release is several commits behind, which made the code back-port not possible.

**Comment by Zakinator123** [comment]
Was this included in 5.3.8.5? In our 5.3.8.5 installation with SAML not enabled, logging out of the admin does not lead to that logout page. We're using an OAuth2 OSGi plugin to provide an SSO experience for the admin login, so preferably logging out shouldn't lead to the dotCMS login page.
