### ISSUE TITLE
Full reindex fails in a race condition

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19091]
As the `ESMappingUtilHelper.addCustomMapping` is executed in a commit listener, the ReindexThread might run at the same time the mapping for indexed field is being set and the full process fails:

![Screen Shot 2020-08-13 at 9.25.34 AM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/4955fd2c-e108-491e-b647-e14f46001e94)

**_On the other hand, we need to make sure we are setting custom mapping per content type instead of per field each time._**

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19092

**Comment by nollymar** [comment]
**Note to QA:** Please, test a full reindex several times using a custom starter

**Comment by bryanboza** [comment]
Fixed, tested reindexing multiple times using the full starter and now I'm unable to get those errors. 

Tested on release-5.3.6.1 branch // Postgres // FF
