### ISSUE TITLE
Template Rest API CRUD 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19096]
We are going to create the Template portlet in angular, so we needs endpoints to:

1. List all template (with pagination)
2. Get a template
3. Edit a template
3. Remove a template

### Extra context:
We have an endpoint we use to create/edit the layout of a page `/api/v1/page/32680740-2120-4d68-bbc2-c47a5b13f139/layout`

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/19134/files)

**Comment by bryanboza** [comment]
- We need more test to the calls of the endpoints: 
  * Publish Template
  * Unpublish Template 

![image](https://user-images.githubusercontent.com/2641437/94313783-991a9c00-ff3c-11ea-94c6-96a8563b084a.png)
We are returning a 200 but the inode is not published or unpublished, we return as failed inode, then the test should not pass in this case 

- We are not resolving the key when you try to edit a template as limited user 

![image](https://user-images.githubusercontent.com/2641437/94313962-ebf45380-ff3c-11ea-8b08-8261c515c234.png)

- We are able to archive a template that is already archived, if the template is archived this wf action is not available for the same inode 

![image](https://user-images.githubusercontent.com/2641437/94314454-c1ef6100-ff3d-11ea-97d7-57b57a3b7914.png)

- We are able to delete published templates, if the template is not archived we should return an error if you try to delete

**Comment by jdotcms** [comment]
403 is showing the right message
<img width="1017" alt="Screen Shot 2020-09-28 at 2 01 46 PM" src="https://user-images.githubusercontent.com/19578350/94480232-3969fe00-0193-11eb-859c-e5ef0780ffdf.png">

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/19350/files

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
