### ISSUE TITLE
Problems adding links in the wysiwyg editor using the community edition

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19102]
Related to #19041 
After the changes in the related cards, now every time you try to add a piece of content that includes a WYSIWYG field, we are getting an error on the log file asking for a license. 
```14:39:46.932  INFO  log.accessLog - Method execution failed: 
java.lang.RuntimeException: need enterprise license
	at com.dotcms.enterprise.achecker.tinymce.ACheckerDWR.getSupportedGudelines(SourceFile:38) ~[ee-master-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) ~[dot.dwr-3rc2modified_3.jar:?]
...
```

And you have problems trying to insert links on those fields
SC: https://www.screencast.com/t/B2ZJjkZVM8i

**Expected behavior**
We need be able to fully use those fields in the community edition 

**Desktop (please complete the following information):**
Tested on release-5.3.6.1 // Postgres // FF

**Comment by fmontes** [comment]
The error only happen when you add an image first.

**Comment by Xander-Steinmann** [comment]
As mentioned in #19041: the WYSIWYG editor does not return correct links for images, files and pages

**Comment by fmontes** [comment]
The problem here is not related with the license, is the z-index game between dojo and tinymce

**Comment by bryanboza** [comment]
We need some work here: 
After you add a link and then try to edit the same one, we need to show the link information when you open again the link properties, we are doing this just the first time, after you unselect the piece of text and then select again in order to edit the link we are not remembering the link properties. 
SC: https://www.screencast.com/t/JZgfEVWWbCE

**Comment by fmontes** [comment]
1. This thing only happen:

**In Firefox**
- When you select the string WITH dobleclick
- If the cursor is in the word doesn’t happen
- If you select by click and dragover doesn’t happen

2. I think we need a new card for that

**Comment by fmontes** [comment]
According to Will, not a bug due how it happen.

**Comment by bryanboza** [comment]
According to the conversation this is fine for now, tested on release-5.3.7 // Postgres // FF
