### ISSUE TITLE
Pushing Destinations fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19110]
1. Set up a sender running the demo site (current starter) and a receiver running a new starter taken from starter.dotcms.com
2. Set up PP
3. go to Content > Destinations, select the 4 destinations.
3. try to push them - select Content and Dependencies.  It will fail.  Try just pushing the selected objects.  It will fail.

It is failing because of the events.  Try to push the events.  Then try to push destinations.  It will fail.

```
Failed to publish because an error occurred: Unable to update Cache or Reindex Content: identToRemove=[931d36c9-000b-41c3-ad93-c2a08bd10bf4], contentId=[null id], contentInode=[null inode], lang=[null lang]
```

**Comment by nollymar** [comment]
Cannot reproduce it. I was able to PP destinations without issues

**Comment by erickgonzalez** [comment]
Able to reproduce against 5.3.7 but no against the latest master, probably fixed here: https://github.com/dotCMS/enterprise-2.x/pull/745/files.

The fastest way to test:
* Start a dotcms instance that runs the full starter.
* Navigate to the `Destinations` Tool under `Content`
* You'll see 2 contentlets.
* Navigate to `Publishing Queue` Tool under `Publishing`
* Upload this bundle (this bundle was created using the old version of starter and the Content and Relationships Filter)
[destinations_contentDepen-01EH2R4QYZZVPYVTW9MXX61QJ8.tar.gz](https://github.com/dotCMS/core/files/5151786/destinations_contentDepen-01EH2R4QYZZVPYVTW9MXX61QJ8.tar.gz)
* Bundle should be successfully uploaded.
* Navigate to the `Destinations` Tool under `Content`
* You'll see 4 contentlets.

**Comment by bryanboza** [comment]
Fixed, tested according on the @erickgonzalez comment and works fine
