### ISSUE TITLE
ElasticSearch issue on content search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19118]
**Describe the bug**
Can't search for contentlets

**To Reproduce**

1. Steps to reproduce the behavior:
2. Start empty
3. Create the folders for to have a theme `application/themes/default`
4. Create a container with 10 max contentlets of Content Generic and add the variable `$body`
5. Create a template, select the only theme and add the content container
6. Create a page with this template
7. Add a contentlet of content generic to the page
8. Create another content generic and another page so you have 4 pieces of content
9. Go to Content Search
10. Now try to filter for a content type: Content Generic and or Page Aseet
11. You will no results and an error in the console:

```15:48:33.135  WARN  business.ESContentFactoryImpl - ----------------------------------------------
15:48:33.135  WARN  business.ESContentFactoryImpl - Elasticsearch error in index 'cluster_3447c5d07f.working_20200817153739'
15:48:33.135  WARN  business.ESContentFactoryImpl - ES Query: {"size":40,"timeout":"15000ms","query":{"match_all":{"boost":1.0}},"post_filter":{"query_string":{"query":"+contenttype:webpagecontent +languageid:1 +deleted:false +working:true -basetype:6 -basetype:3","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"desc_dotraw":{"order":"asc"}}]}
15:48:33.135  WARN  business.ESContentFactoryImpl - Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
15:48:33.135  WARN  business.ESContentFactoryImpl - ----------------------------------------------```

Tested on release-5.3.7

**Comment by bryanboza** [comment]
I'm able to reproduce this problem in the release branch, but this is a problem in the community edition, tried in the EE edition and I'm unable to reproduce.

**Comment by fmontes** [comment]
The problem was related of a saved sort, when you saved from the "Add > Content" using "All" in the content type it breaks the saved sort for the Content Search portlet.

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/19126
