### ISSUE TITLE
Insert link with bad url in the WYSIWYG editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19113]
**Describe the bug**
I tested the above code in a tinymceprops field and the file browser pops up now. There is still a problem with the url though:
Image: /shared-images/templates/base template thumbnail.pngbase template thumbnail.png
File: /version.txtversion.txt
Page: undefined

**To Reproduce**
1. Go to create a content type with a WYSIWYG
2. Add a link
3. Check the url is wrong

**Reference**
https://github.com/dotCMS/core/issues/19041#issuecomment-672700530

## Acceptance Criteria

1. Fix the link url
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
FIx: https://github.com/dotCMS/core/commit/5b26570851be2a18d323405efdd0bab474088d67

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
