### ISSUE TITLE
API call does not display categories properly if the content has a child category. v 5.3+

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19121]
API call does not display categories properly if the content has a child category.

Issue reported: https://dotcms.zendesk.com/agent/tickets/102151

And here: https://dotcms.zendesk.com/agent/tickets/102210

**To Reproduce**

1. Add a child category to a contentlet
2. Use a general API call to get information on that Content Type 

**Expected behavior**
All information about the contentlets should display. Instead, if the contentlet has no top level category in addition to the child category, no category info will display. 

If the contentlet HAS a top level category and a child category, only the top level category will display. 

EXAMPLE:

I added child category "Kung Fu" to the Top-level category "Action" to be used for the "Movies" content type on Demo.

![image](https://user-images.githubusercontent.com/49727631/90547785-a3819300-e151-11ea-8015-c36e184a9b2e.png)

I added a contentlet called "Ip man" that included the "Kung Fu" category but not its parent "Action"

![image](https://user-images.githubusercontent.com/49727631/90547822-aed4be80-e151-11ea-9874-5aedf5e453cf.png)

Used API call: https://demo.dotcms.com/api/content/render/false/query/+contentType:MOVIES

![image](https://user-images.githubusercontent.com/49727631/90547884-c1e78e80-e151-11ea-81e4-3eb258e01c67.png)

You can see that the contentlet "Ip Man" is not displaying Categories at all. The one below it "Dune" IS displaying its top level category.

If I add the top-level category "Action" to "Ip Man" the call only displays "Action" not "Kung Fu"

![image](https://user-images.githubusercontent.com/49727631/90548017-f65b4a80-e151-11ea-9d03-6c38f94ea45a.png)

![image](https://user-images.githubusercontent.com/49727631/90548047-0115df80-e152-11ea-8167-d2ab63a1c242.png)

**Comment by wezell** [comment]
This needs to work in all the APIs, 
- contentAPI
- ESSearch
-PageAPI
-GraphQL

**Comment by erickgonzalez** [comment]
The issue here actually is with a second-level child category, e.g.:
```
Parent Category
                    |____Child Category
                                         |____GrandChild Category
```
If you add `Child Category` to a contentlet it shows up, but if you add the `GrandChild Category` it does not.

**Comment by erickgonzalez** [comment]
To Test use this bundle, that will create a category with a second-level child category, a content type that will use that category, and a few contentlets. And also will add a new Category field to the page Content-Type and create a new page with categories.
[CategoriesIssue-01EH53CVN6DR5MYVQVRC7ZDF9E.tar.gz](https://github.com/dotCMS/core/files/5157226/CategoriesIssue-01EH53CVN6DR5MYVQVRC7ZDF9E.tar.gz)


- **contentAPI** = `/api/content/render/false/query/+contentType:CtWithCat`
- **ESSearch** = `/api/es/search` with body
 ```
{
        "query": {
            "bool": {
                "must": {
                    "term": {
                        "contentType": "CtWithCat"
                    }
                }
            }
        }
    }
```
- **PageAPI** = `/api/v1/page/render/testpagecategories` under the page entity you should see the category field and the value.

- **GraphQL** = using insomnia use this query:
```
{
  search(query: "contentType:CTWithCat", limit: 10) {
...on CtWithCat{
    title
    modDate
    modUser {
      firstName
      lastName
    }
    
      categoriezzz{
        name
      }
    }
  }
}
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19207

**Comment by bryanboza** [comment]
Fixed, tested with the provided data and now works as expected. Tested on master // Postgrres // FF
