### ISSUE TITLE
Add images or add links not working, file browser not returning results

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19127]
When you try to add an image you see the results for the images, even the total doesn't match the result, but if you try to add a link no pages shows.

### Steps to reproduce
1. Create pages and upload images
2. Create a Content Generic, try to add an image and then try to add a link
3. See there is no results for the links, even when you have pages and other files.

![Screen Shot 2020-08-19 at 11 10 12](https://user-images.githubusercontent.com/751424/90668183-e5234400-e20c-11ea-8d54-1bb6aaeb5171.png)

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/19128

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
