### ISSUE TITLE
Unable to create templates using the template designer 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19123]
We are unable to use the template designer, this because when you try to open it, we are getting a blank window and it never loads. 

![image](https://user-images.githubusercontent.com/2641437/90579490-646c3580-e183-11ea-8889-23cf7be9fc3d.png)

- Login as admin 
- Go to Site --> Templates 
- Try to create a new one using the template designer 

**Expected behavior**
We need to be able to create templates using this tool

**Desktop (please complete the following information):**
Tested on master // Postgres // FF

**Comment by wezell** [comment]
Cannot reproduce.  We can reopen if needed

**Comment by bryanboza** [comment]
Ok after retest seems I have the specific steps how to reproduce: 

- Start with the blank starter
- Login as admin 
- Upload this bundle https://drive.google.com/file/d/1vrsrTIWnZfSX8tUGAsWdGJvgtpwyg8eQ/view?usp=sharing 
- Now make sure you have the container and the theme in the demo.dotcms.com site
- Go to templates and try to use the template designer 

Here we are unable to use it. This is a really common case of how to start my own environment, we need to fix

**Comment by fmontes** [comment]
This was failing when the site have alias.

**Comment by erickgonzalez** [comment]
Tested and working as it should, now after uploading the bundle able to use the Template Designer to create templates.

**Comment by bryanboza** [comment]
Fixed, tested with this fix and now we are able to use the template designer without problems
