### ISSUE TITLE
Can't push publish from old dialog

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19133]
**Describe the bug**
Can't push publish from a subaction when also have "Assignable" or "Commentable"

**To Reproduce**
1. Edit the System Workflow
2. Add Push Publish sub action to the Publish action and mark Commentable and assignable [like this](https://user-images.githubusercontent.com/751424/90689507-6c80af80-e22d-11ea-8150-0773524291c2.png)
3. Go to Site Browser, right click and "Publish" try to PP with the dialog that is show, you get the error

**Expected behavior**
We should show the new dialog wizard we add in: https://github.com/dotCMS/core/issues/18678
Should respect selected PP Filter.

**Note:** In the Task Tool we are still using the old dialog, migrate this one as well.

**Comment by hmoreras** [comment]
PR's:  https://github.com/dotCMS/core/pull/19238  and https://github.com/dotCMS/core-web/pull/1420

**Comment by bryanboza** [comment]
I'm still getting this error when try to add a new piece of content and "publish", then oush publish is failing 
![image](https://user-images.githubusercontent.com/2641437/93140949-8b455b00-f6a0-11ea-8934-1e3fdb22988e.png)

Log: https://gist.github.com/bryanboza/a52ec4d98f5076c7d5aa139fc9f93030

**Comment by erickgonzalez** [comment]
We need to first check if the WF Step has `Save Content` actionlet if it does, we need to save the content and then pop-up the modal. If it does not have the actionlet pop-up the modal.

Another scenario to test:
* Create a WF Step that has: `Save Actionlet` and `Assign`
* Save and Publish a new content.
* Edit the content created, change the title, and apply the new WF Step created.

The content changes should be saved and assigned to the user selected. Right now is being assigned but the changes are lost.

**Comment by erickgonzalez** [comment]
Tested working as it should. Now if you have a WF that has Push Publish and/or Assign and/or Comments and Save Content, the content changes get saved.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF
