### ISSUE TITLE
TextTool view tool cannot check if language variable exists

### ISSUE THREAD

**Issue by kunal999** [dotCMS/core#19135]
**Describe the bug**
If I refer to a language variable key that is not defined, the TextTool just sets the key as the value. As a result, I cannot use the isSet method to check if a key exists - contrary to the TextTool documentation. - https://dotcms.com/docs/latest/texttool#ExampleLanguageVariable

**To Reproduce**
1. In your .vtl file, add a reference to an undefined language variable e.g. $text.xyzKey
2. The value of $text.xyzKey is set to "xyzKey"
3. $UtilMethods.isSet($text.xyzKey) always returns true

**Expected behavior**
$UtilMethods.isSet($text.xyzKey) should return false

**Comment by erickgonzalez** [comment]
Reproduced in demo(22.10.1)
