### ISSUE TITLE
[Vanity URLs] : Evaluation order is not being set

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19147]
Reported via Support: [102022](https://dotcms.zendesk.com/agent/tickets/102022)
Reproducible as of dotCMS 5.3.5, and up.

As per our official documentation, Vanity URLs can have a specific evaluation order. Even though it's not recommended at all to have multiple URLs matching the same incoming URL, users can determine which Vanity URL is verified first: https://dotcms.com/docs/latest/vanity-urls#Order

The Vanity URLs are not being returned in the appropriate ortder.

**To Reproduce**
1. Go to the **Vanity URLs** portlet, and create at least 5 Vanities over the `demo.dotcms.com` host, so that it's easier to see the problem. **NOTE: Put different values in the `order` field.**
2. Create a JSP file, called `vanity-checker.jsp`, containing code similar to this one:
```java
<%@page import="com.dotmarketing.business.web.HostWebAPI"%>
<%@page import="com.dotmarketing.business.web.WebAPILocator"%>
<%@page import="com.dotmarketing.business.web.LanguageWebAPI"%>
<%@page import="com.dotmarketing.business.APILocator"%>
<%@page import="com.dotcms.vanityurl.business.VanityUrlAPI"%>
<%@page import="com.dotmarketing.beans.Host"%>
<%@page import="com.dotmarketing.portlets.languagesmanager.model.Language"%>
<%@page import="com.dotcms.vanityurl.model.CachedVanityUrl"%>
<%@page import="java.util.List"%>

<ul>
        <%
            final HostWebAPI hostWebAPI = WebAPILocator.getHostWebAPI();
            final LanguageWebAPI languageWebAPI = WebAPILocator.getLanguageWebAPI();
            final VanityUrlAPI vanityApi = APILocator.getVanityUrlAPI();
            final Host host = hostWebAPI.getCurrentHostNoThrow(request);
            final Language language = languageWebAPI.getLanguage(request);

            List<CachedVanityUrl> cachedList = vanityApi.findInDb(host, language);
            for (final CachedVanityUrl cached : cachedList) {
                %>
                <li> <%= cached.vanityUrlId%> / <%= cached.pattern %> / <%= cached.order %> </li>
                <%
            }
        %>
</ul>
```
3. Copy the `vanity-checker.jsp` file under the `/webapps/ROOT/` folder of your Tomcat.
4. Go to http://localhost:8080/vanity-checker.jsp . As you can see, the value of the `order` property is always zero.

**Expected behavior**
The Vanity URL API should return all the Vanity URLs in ascendant order.

**Additional context**
This is causing resolution problems in environments that handle dozens or hundreds of Vanity URLs.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19150

**Comment by erickgonzalez** [comment]
Working as it should, following the instructions provided in the description and the vanities URL are shown in ascendant order.

**Comment by bryanboza** [comment]
Fixed, working as expected after the changes, tested on release-5.3.8 // Postgres // FF
