### ISSUE TITLE
Unable to execute some workflow actions from task portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19141]
When you assign a pice of content to some user and then try to apply some workflow action from the task portlet, we are getting some problems with some specific actions: 

## Case1: 
- Assign some piece of content to the current user 
- Go to the task porlet and try to execute the copy action
- We are getting this error:  https://gist.github.com/bryanboza/bde034e84cdb8a23a492349db4b37018

## Case2: 
- Go to workflows and add this sub-action to the published//draft step https://www.screencast.com/t/u4KaHFDYqx
- Add a new piece of content 
- Assign to the current user 
- Go to task portlet and try to apply this action to the content 
- We are getting this error: https://gist.github.com/bryanboza/e5a7a54a596b5e04bef3c2048caa8be8

**FYI: Both cases are using this tool.  If you open the task and try to execute directly from the modal works as expected** 
![image](https://user-images.githubusercontent.com/2641437/90943161-e2c01600-e3d5-11ea-9900-4314131c2607.png)

### Testing info
Both cases was tested on release-5.3.7 // Postgres // FF

**Comment by erickgonzalez** [comment]
Case 1: Not able to reproduce in release-5.3.7, please double-check.
Case 2: PR https://github.com/dotCMS/core/pull/19146

**Comment by fmontes** [comment]
Case 2 pass internal QA

**Comment by bryanboza** [comment]
@erickgonzalez tested again and now I have this error using the execute button 
![image](https://user-images.githubusercontent.com/2641437/91105289-f31dfe00-e62c-11ea-9680-0940154316ac.png)

**Comment by fmontes** [comment]
I can't reproduce this last comment @bryanboza

**Comment by erickgonzalez** [comment]
Not able to reproduce in the latest release-5.3.7 neither FF nor Chrome. Able to execute the `Copy` and the `Assign` Workflow without issues.

**Comment by bryanboza** [comment]
After the last changes, now I noticed that if you try to execute the copy action for a pice of content that is in a language different to the default, we are creating the new version in the default language, we are not respecting language here: 
![image](https://user-images.githubusercontent.com/2641437/91231184-0cd14b00-e6ea-11ea-94c2-57d22f17507e.png)

**Comment by wezell** [comment]
@bryanboza this is a new issue.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.7 // Postgres // FF
