### ISSUE TITLE
GraphQL Page API - Implement 'urlContentMap' field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19159]
```
urlContentMap{
        title
        id
// rest of properties of Contentlet
    }
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19162

**Comment by wezell** [comment]
We should name the variable:

`URLMapContent`

**Comment by freddyucv** [comment]
**Passed Internal QA**: Postman Test review

**Comment by bryanboza** [comment]
Fixed, tested with a page request and now this field is working as expected
