### ISSUE TITLE
Make Saml metadata generation admin only

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19157]
There are no security concerns with sharing the public key, but in an abundance of caution, we should make the endpoint admin only.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/19171)

**Comment by erickgonzalez** [comment]
Tested Working as it should, when hitting the endpoint to request SAML Metadata `api/v1/dotsaml/metadata/{IdpConfigId}` using a non-admin user returns `403 Forbidden` and `{
    "message": "com.dotmarketing.exception.DotSecurityException: SAML metadata is only accessible by administrators"
}`

**Comment by bryanboza** [comment]
Fixed, tested on authoring and now we are able to get this just as admin user

**Comment by bryanboza** [comment]
New error related to the resource reported here #19377
