### ISSUE TITLE
[Content] : Limited user cannot create multilingual content

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19155]
Reported via Support: [102120](https://dotcms.zendesk.com/agent/tickets/102120)
Reproducible as of dotCMS 5.3.3 and up.

If permissions are set correctly, a Limited User can create a new Contentlet of a given Content Type without problems when the default language is selected. However, creating a new version using another language -- e.g., Spanish -- is trowing an exception on the Edit Content page.

**To Reproduce**
1. Log into the back-end, and grant the **Contributor** role the required permissions to create and publish contents of type `Rich Text`:
1.1 In the `Publisher / Legal > Reviewer > Contributor` role, check **Add Children** for the Demo Site, and **Publish** for the `Content/Files`.
1.2 In the `Rich Text` Content Type, add the **Contributor** role and check **Publish**
2. Log in as Joe Contributor.
3. Go to **Content Search** and create a content of type `Rich Text` in English. This works as expected. Close the dialog.
4. Open up the contentlet you just created, and change the Language dropdown to Spanish. The following error is displayed on the Content Edit modal:
```
An unexpected system error occurred.An exception occurred processing JSP page [/html/portal/view_portlet_inc.jsp] at line [87] 84: 85: boolean portletException = false; 86: 87: cachePortlet.render(renderRequest, renderResponse); 88: 89: SessionMessages.clear(renderRequest); 90: SessionErrors.clear(renderRequest); Stacktrace:
--
```

**Expected behavior**
If permissions are set correctly, a Limited User must be able to create content in any available language.

**Comment by fmontes** [comment]
The fix: https://github.com/dotCMS/core/commit/3699b98dc5e9d9d2126e20ed7c5fb207f56f7c86

**Comment by jcastro-dotcms** [comment]
@fmontes that is not the code fix for the latest version of the code. It only works specifically for version 5.3.3

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19178

**Comment by erickgonzalez** [comment]
Working as it should. After giving the required permissions able to create multilingual content as a limited user.

**Comment by bryanboza** [comment]
Fixed, after the fix now I'm able to add multilingual contents without problems.
