### ISSUE TITLE
Handle enter key to primary action in all dialogs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19158]
**Is your feature request related to a problem? Please describe.**
So the [ENTER] key should "hit" the primary action button in all the dialogs in the system.

**Additional context**
The thing is that you can be focus in any element in the page, including elements behind the dialog and the dialog overlay.

## Acceptance Criteria

1. ?????
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
Thils should be global, somehow.

**Comment by alfredo-dotcms** [comment]
Based on a discussion this only applies to the Angular's dialog and not the dojo dialog, and must be implemented in a general way and not on specific/individuals dialogs

**Comment by alfredo-dotcms** [comment]
updated PR: https://github.com/dotCMS/core/pull/22491/files

**Comment by fabrizzio-dotCMS** [comment]
I tested this against the following dialogs:

- Create Templates (Next Button does not react to ENTER)

![Screen Shot 2022-07-11 at 22 23 23](https://user-images.githubusercontent.com/37148755/178408093-ec79d543-61b8-4cd4-ae18-ceb262f00f28.png)

- Apps / Import  (The main dialog behaves correctly but once a file has been chosen and an invalid password is submitted)  You'll see an invalid request dialog. Which does not react to ENTER even after having set the focus on it. The only way to dismiss the dialog is by clicking on ACCEPT.

![Screen Shot 2022-07-11 at 20 43 33](https://user-images.githubusercontent.com/37148755/178397141-5ccc94a9-49ba-4ab7-ad67-b6d43a393659.png)

- Push Publish (The dialog does not gain focus immediately, you need to click on anywhere on the screen first, or use the tab button to navigate all the screen until the focus lands on the dialog)

- Content-Type  (Behaves just fine)

In general, the dialog seems to execute a default action associated with the Key ENTER
But in general terms, the dialogs should gain focus by default and in most cases, they don't.

**Comment by nollymar** [comment]
The improvements suggested by @fabrizzio-dotCMS will be implemented on https://github.com/dotCMS/core/issues/22566

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.09_a506dc69_SNAPSHOT // Docker // FF
