### ISSUE TITLE
PP Filters reloads when flushing cache

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19152]
**Is your feature request related to a problem? Please describe.**
When a PP Filter YAML file is changed you need to restart the server to get the changes loaded.

**Describe the solution you'd like**
Add the init call of the PP Filters to the flush of the cache **SystemCache**

**Steps**

1. Startup dotcms
2. Check the filters using this endpoint `api/v1/pushpublish/filters`
3. Navigate in your local to `/assets/server/publishing-filters/`
4. Make a change in one of the YAML files.
5. Flush Cache **SystemCache**
6. Check again the filters using this endpoint `api/v1/pushpublish/filters` and check that your change is there.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19386

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 //Postgres // FF
