### ISSUE TITLE
[Layout] : Custom layout doesn't refresh after saving changes

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#19165]
Reported via support : [102095](https://dotcms.zendesk.com/agent/tickets/102095)
Reproducible in dotCMS 5.3.6.1

After customize the layout for a page and saving the changes, if the user go to Content view on the right sidebar and then go back to Layout view, the old layout for the page is shown on the view.

**To Reproduce**
1. Go to 'Site -> Browser' and create a new page using a template with a theme (instead of an advanced template)
2. Add some content to the page, and save it. Go back to the Site Browser.
3. Right click the page and click the Open(Preview) option from the context menu (the issue only happens when using the context menu).
4. Click 'Layout' on the right-side bar to go to Layout view.
5. Customize the layout of the page, for example, add a new column to the first row of the layout:
![image](https://user-images.githubusercontent.com/2894221/91302010-07fcad80-e763-11ea-8846-423c27ca6ac7.png)

6. Click 'Content' on the right-side bar, and then click 'Layout' again to go back to Layout view.
7. The saved changes for the layout don't show on the view:
![image](https://user-images.githubusercontent.com/2894221/91302040-15b23300-e763-11ea-9577-5257fbd503ea.png)

**Expected behavior**
The layout changes should be shown for the page that is being edited.

**Additional context**
This is a minor issue. If the user go back to the Site Browser after saving layout changes and open the page again, the changes are shown.

**Comment by wezell** [comment]
I could not reproduce this on demo - currently running 5.3.7

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/19252

**Comment by bryanboza** [comment]
Unable to reproduce after the changes, tested on release-5.3.9 // Postgres // FF
