### ISSUE TITLE
Invalid sort gets stored and executed by UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19169]
We try to be clever on the content search screen and "save" the query params and sort that has been used to display the contents in a cookie and or the session.  If you are using custom types, do a lot of filtering and as you use the UI in edit mode and what not, this can cause the content search screen to return ultimately 0 results.  See the below report from a customer - you can see that it is trying to sort by `desc_dotraw` which basically means es is trying to sort by nothing.

---

> I think I have found the error we have been looking for and it might not be browser session based at all. I was able to replicate by going in and out of Edit mode for a page and the content search and selecting a specific type. I did this almost a dozen times and then the issue happened. When it did I managed to get the log trace going and found the following log entire directly related to what was happening.
> 
> First we get the following log: 
> [26/08/20 18:17:44:563 GMT] WARN business.ESContentFactoryImpl: ---------------------------------------------- 
> [26/08/20 18:17:44:563 GMT] WARN business.ESContentFactoryImpl: Elasticsearch error in index 'cluster_fw-prod-cms-cluster.working_20200722142226' 
> [26/08/20 18:17:44:564 GMT] WARN business.ESContentFactoryImpl: ES Query: {"size":41,"timeout":"15000ms","query":{"match_all":{"boost":1.0}},"post_filter":{"query_string":{"query":"+contenttype:glossary +deleted:false +working:true +((+owner:user-0d4a21a6-3480-4e9d-b560-6f4a9a233526 +ownercanread:true) (permissions:p29a71d8e-f26a-4848-9111-3f8173240456.1p* permissions:p611a15fe-3515-4aef-9c99-8bb68af9dc31.1p* permissions:p02088e05-5ff5-43c2-a4fa-11a7272cb199.1p* ) )","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"desc_dotraw":{"order":"asc"}}]} 
> [26/08/20 18:17:44:564 GMT] WARN business.ESContentFactoryImpl: Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed] 
> [26/08/20 18:17:44:564 GMT] WARN business.ESContentFactoryImpl: ----------------------------------------------
> 
> If I then run that query against the ElasticSearch instance and the working index I get the following error from Es for the QUery dotCMS is throwing at the index:
> 
> { 
> "error": { 
> "root_cause": [ 
> { 
> "type": "query_shard_exception", 
> "reason": "No mapping found for [desc_dotraw] in order to sort on", 
> "index_uuid": "D1BIb0gVSkSFgSTr1-Ps_Q", 
> "index": "cluster_fw-dev-cms-cluster.working_20200608165532" 
> } 
> ], 
> "type": "search_phase_execution_exception", 
> "reason": "all shards failed", 
> "phase": "query", 
> "grouped": true, 
> "failed_shards": [ 
> { 
> "shard": 0, 
> "index": "cluster_fw-dev-cms-cluster.working_20200608165532", 
> "node": "WyYJwdunT_mKRojRe1Wk4Q", 
> "reason": { 
> "type": "query_shard_exception", 
> "reason": "No mapping found for [desc_dotraw] in order to sort on", 
> "index_uuid": "D1BIb0gVSkSFgSTr1-Ps_Q", 
> "index": "cluster_fw-dev-cms-cluster.working_20200608165532" 
> } 
> } 
> ] 
> }, 
> "status": 400 
> }
> 
> This was the query I ran to generate that error which replicates what I saw in the CMS. 
> GET cluster_fw-dev-cms-cluster.working_20200608165532/_search 
> { 
> "size": 41, 
> "timeout": "15000ms", 
> "query": { 
> "match_all": { 
> "boost": 1 
> } 
> }, 
> "post_filter": { 
> "query_string": { 
> "query": "+contenttype:glossary +deleted:false +working:true +((+owner:user-0d4a21a6-3480-4e9d-b560-6f4a9a233526 +ownercanread:true) (permissions:p29a71d8e-f26a-4848-9111-3f8173240456.1p* permissions:p611a15fe-3515-4aef-9c99-8bb68af9dc31.1p* permissions:p02088e05-5ff5-43c2-a4fa-11a7272cb199.1p* ) )", 
> "fields": [], 
> "type": "best_fields", 
> "default_operator": "or", 
> "max_determinized_states": 10000, 
> "enable_position_increments": true, 
> "fuzziness": "AUTO", 
> "fuzzy_prefix_length": 0, 
> "fuzzy_max_expansions": 50, 
> "phrase_slop": 0, 
> "escape": false, 
> "auto_generate_synonyms_phrase_query": true, 
> "fuzzy_transpositions": true, 
> "boost": 1 
> } 
> }, 
> "_source": { 
> "includes": [ 
> "inode", 
> "identifier" 
> ], 
> "excludes": [] 
> }, 
> "sort": [ 
> { 
> "desc_dotraw": { 
> "order": "asc" 
> } 
> } 
> ] 
> }
> 
> SO there is something wrong with the field the query is trying to sort on and it is not indexed correctly to actually use as a sort.
> 
> The same error happens then with any and all content types selected: 
> [26/08/20 18:51:32:075 GMT] WARN business.ESContentFactoryImpl: ---------------------------------------------- 
> [26/08/20 18:51:32:075 GMT] WARN business.ESContentFactoryImpl: Elasticsearch error in index 'cluster_fw-prod-cms-cluster.working_20200722142226' 
> [26/08/20 18:51:32:075 GMT] WARN business.ESContentFactoryImpl: ES Query: {"size":41,"timeout":"15000ms","query":{"match_all":{"boost":1.0}},"post_filter":{"query_string":{"query":"-contenttype:forms -contenttype:host +(conhost:96cf012a-6072-407d-affc-2c7f2209e2fa conhost:system_host) +deleted:false +working:true +((+owner:user-0d4a21a6-3480-4e9d-b560-6f4a9a233526 +ownercanread:true) (permissions:p29a71d8e-f26a-4848-9111-3f8173240456.1p* permissions:p611a15fe-3515-4aef-9c99-8bb68af9dc31.1p* permissions:p02088e05-5ff5-43c2-a4fa-11a7272cb199.1p* ) )","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"desc_dotraw":{"order":"asc"}}]} 
> [26/08/20 18:51:32:075 GMT] WARN business.ESContentFactoryImpl: Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed] 
> [26/08/20 18:51:32:075 GMT] WARN business.ESContentFactoryImpl: ----------------------------------------------
> 
> So something with that field or the scenario we are coming across causes it to go in and to of flux. One minute it all works fine the next we get this.

**Comment by wezell** [comment]
PR: #19170

**Comment by fmontes** [comment]
1. Create a content type with 2 field: both show in list but only one required
2. Create multiple pieces of content and don't fill the non-required field in any
3. Go to content search and sort by that empty field
4. We get no results.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF and after try multiple times I'm unable to reproduce
