### ISSUE TITLE
Hazelcast Discovery Conflicts with AutoWire

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19163]
If you set Hazelcast to 
```
<property name="hazelcast.discovery.enabled">true</property>
```
Autowire will not work.  This was set to true to enable discovery for kubernetes installs but it borked our default autowire

![Screen Shot 2020-08-25 at 7 43 50 PM](https://user-images.githubusercontent.com/934364/91305275-cd9e0b00-e778-11ea-8716-43bbaf86f84d.png)

**Comment by wezell** [comment]
PR: #19164

**Comment by bryanboza** [comment]
Fixed, this revert a change that we made in a previous release and was tested directly with the client by @wezell
