### ISSUE TITLE
Iframe component set url twice

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19166]
**Describe the bug**
When you login or reload a page the iframe component trigger the `setUrl` twice which.

**To Reproduce**
1. Login or reload a page
2. Check [this method](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/iframe/iframe-porlet-legacy/iframe-porlet-legacy.component.ts#L135) and see how gets called twice

**Expected behavior**
We should not set the url twice on load

**Additional context**
The second set url happens because of this: https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/iframe/iframe-porlet-legacy/iframe-porlet-legacy.component.ts#L47

## Acceptance Criteria

1. Check how to not make the set twice
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core-web/pull/1434

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF
