### ISSUE TITLE
[core] : Display the dotCMS version number in the back-end

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19175]
**Is your feature request related to a problem? Please describe.**
In older versions of dotCMS -- 3.x and lower -- it was possible for users to see the current version of dotCMS they were running. As of dotCMS 4.x, the version number is displayed in the Login page only.

**Describe the solution you'd like**
Display the dotCMS version number in the modal window that shows your profile picture, at the top-right corner.

**Describe alternatives you've considered**
Display the dotCMS version number at the bottom or top of the page.

**Additional context**
If you are already logged in, the only way to check the version number is to log out to get to the Login page, and the log back in.

**Comment by wezell** [comment]
System > Maintenance > System Info

![Screen Shot 2020-08-26 at 7 27 09 PM](https://user-images.githubusercontent.com/934364/91366605-39609200-e7d2-11ea-9f09-b498533e8700.png)

**Comment by wezell** [comment]
closing for now
