### ISSUE TITLE
"UPLOAD NEW FILE" button does not work in Image/File fields

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19181]
## Describe the bug

When you add a file to an Image or File field in a content item, the "UPLOAD NEW FILE" button does not work.  More specifically, the upload popup appears **behind** the `Select a file` popup, so it just can't be used.

## To Reproduce

1. Login as admin.
2. Create a new content type with just a Title field and an Image field.
3. Create a new content item of the new content type.
4. Click the "Browse..." button next to the Image field.
5. In the `Select a file` popup, select any folder.
6. Press the "UPLOAD NEW FILE" button.
    * **Result:** After a few browser footer messages saying it's waiting for the host, nothing appears to happen.
7. Close the popup.
    * **Result:** The upload popup is now displayed - because it was actually opened **behind** the `Select a file` popup, instead of in front of it.
        * But, since the `Select a file` popup has already been closed, even if you select a file in the upload popup, you can not select it for the field.

## Expected behavior

The upload popup should appear in front of the `Select a file` popup.

## Screenshots

https://www.screencast.com/t/42f4NrMrUjc

## Desktop (please complete the following information):

* OS: Win 10 Pro
* Browser: Chrome, Edge (Chromium-based), and FF
* Version: 5.3.7

**Comment by wezell** [comment]
need to set the focus on the window

**Comment by bryanboza** [comment]
After you upload a new image we are not auto refreshing the modal, then we are unable to see the uploaded image, we need to manually refresh the folder in order to select the uploaded image

**Comment by fmontes** [comment]
New issue for that: https://github.com/dotCMS/core/issues/19335

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Official PR: https://github.com/dotCMS/core/pull/19324/files
