### ISSUE TITLE
Problem uploading files from the content editor if the folder accept just specific extensions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19182]
Related to #19181 

If you create a folder with filters (accept just specific extensions), and then try to upload files from the content editor, we are not showing the filter exception at the moment, we finish the process and the file was not uploaded and when you open try again, here we have the error.  

The same thing if you try from the WYSIWYG editor. 

SC1: https://www.screencast.com/t/G9JkxKUY

**To Reproduce**
- Login as admin
- Create a new folder that accepts just jpg images (*.jpg) 
- Go and try to add new content (rich text)
- From the content editor try to upload a new file 
- Select some file with an extension different to the one that accepts the folder 
- Save it 
- Now try to add another file again 

**Expected behavior**
We need to show the error at the moment to let the user know about the error 

**Desktop (please complete the following information):**
Tested on master // Postgres // FF

**Comment by wezell** [comment]
We need to change the error message from the legacy method - spitting it out in dojo - to using a growl message

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19351

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF 
Now we have a better error message 
![image](https://user-images.githubusercontent.com/2641437/96159160-9377fc80-0ed1-11eb-92f5-59a3cdc544ee.png)
