### ISSUE TITLE
Site name in the starter site should be `demo.dotcms.com` instead of `starter.dotcms.com`

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19203]
## Describe the bug

Currently, the Site name set in the starter site - and thus on our actual dotCMS demo site - is `starter.dotcms.com`.  It should be `demo.dotcms.com` instead.

In addition, the following 2 aliases for are not needed and should be removed:

* test.dotcms.com
* test2.dotcms.com

## To Reproduce

1. Open the dotCMS demo site, or a clean starter.
2. Open the Sites portlet (Control Panel -> Sites).
    * **Result:** The Site name is set to starter.dotcms.com, instead of demo.dotcms.com.

## Expected behavior

The Site name should be demo.dotcms.com, and the only 2 aliases for the site should be `localhost` and `127.0.0.1`.

## Screenshots

![image](https://user-images.githubusercontent.com/13456955/91865524-55c35b00-ec26-11ea-91ed-adfbb4978f8f.png)

## Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome
 - Version: dotCMS 5.3.7

**Comment by erickgonzalez** [comment]
We need to generate a new full starter with these changes.

**Comment by wezell** [comment]
Also make sure the destinations make it to the starter.

**Comment by erickgonzalez** [comment]
> Also make sure the destinations make it to the starter.

Done 
![Screen Shot 2020-09-01 at 11 32 46 AM](https://user-images.githubusercontent.com/5278970/91886644-de51f380-ec46-11ea-9b94-49847a1889e8.png)

**Comment by fmontes** [comment]
We need to update css that got error-deleted in the starter

![image (7)](https://user-images.githubusercontent.com/751424/92039659-a88a3900-ed32-11ea-9a4f-9d1d8e2b7105.png)
------------------
![image (6)](https://user-images.githubusercontent.com/751424/92039663-a9bb6600-ed32-11ea-8195-f12cb75b751f.png)
------------------
![image (5)](https://user-images.githubusercontent.com/751424/92039665-aa53fc80-ed32-11ea-82ea-8d737fef0f92.png)

**Comment by erickgonzalez** [comment]
PR for the new starter: https://github.com/dotCMS/core/pull/19231

**Comment by erickgonzalez** [comment]
demo.dotcms.com has been updated.

**Comment by fmontes** [comment]
Changing the name of the site we have problems with the containers as file in the layout because they keep pointing to the old site.

**Comment by erickgonzalez** [comment]
entries at DB level were updated, a new starter has been generated `20200909`

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF
