### ISSUE TITLE
"Language" and "Host" Search fields missing when relating content on Content Types with multiple relationship fields - v5.1.2+

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19204]
As reported in tickets:
https://dotcms.zendesk.com/agent/tickets/102261 - v5.3x
https://dotcms.zendesk.com/agent/tickets/102245 - v5.1.6

If a Content Type has multiple relationship fields the Language and Host 'Search" fields disappear when attempting to relate the content. 

Flushing cache seems to temporarily fix the problem, but it comes back.

This occurs in version 5.1.2+

**To Reproduce**
1. Add multiple Relationship fields to a Content Type.
2. Create a new contentlet of the Content Type
3. Attempt to relate content

**Expected behavior**
All "Search" fields in the Relationship modal should be available.

Instead, Language and Host fields disappear even though their labels are still there.

**Screenshots**

MP4 demonstrating the issue:
[2020-08-28_11h49_31.zip](https://github.com/dotCMS/core/files/5157298/2020-08-28_11h49_31.zip)

![image](https://user-images.githubusercontent.com/49727631/91873200-5d8ef980-ec3e-11ea-91d1-5e9277bd9171.png)

![image](https://user-images.githubusercontent.com/49727631/91873217-61228080-ec3e-11ea-9bc2-f91465b0beab.png)

![image](https://user-images.githubusercontent.com/49727631/91873239-65e73480-ec3e-11ea-8fe7-d0410b0f30fa.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: Chrome/FF

**Additional context**

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/19226/

**Comment by jasontt33** [comment]
http://travel.developer-ingenico.com/dotAdmin

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF
