### ISSUE TITLE
Unable to connect via GraphQL in community edition 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19206]
We are getting an error trying to generate the GraphQL schema when you are using the community edition, and we are unable to made any request. 

ST: https://gist.github.com/bryanboza/9bfcca9f75699c77433baa531331396a

**To Reproduce**
1- Start a dotcms instance 
- Try to connect via GraphQL

**Expected behavior**
We need to return a 200 code and the error about the license should be in the message. If not we need to be able to made the request and just don't return information about personas 

**Desktop (please complete the following information):**
Tested on release-5.3.8 // Postgres // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19259#issue-485379846

**Comment by dsilvam** [comment]
Note to QA: Expected result is that persona fields are just simply not available.

**Comment by freddyucv** [comment]
**Passed Internal QA:** Test with this query

```
{
  webPageContentCollection {
    title
  }

}
```

response without license(after create a content in the empty starter):

```
{
  "data": {
    "webPageContentCollection": [
      {
        "title": "Test_1"
      }
    ]
  }
}
```

**Comment by bryanboza** [comment]
Fixed, tested with the community edition on release-5.3.8... Now we are unable to get personas from graphQL

**Comment by bryanboza** [comment]
We need be able to get personas when you are in a EE edition. Needs some work here

**Comment by bryanboza** [comment]
Fixed, now we can connect from a community edition, new card opened here #19276
