### ISSUE TITLE
Binary images can not be viewed on FE if there is a working version of the content item

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19201]
## Describe the bug

Binary Images in content can not be accessed using the `/contentAsset/image` path if there is a Working version of the content.  This is true even if there is a Live version of the content that contains the image.

## To Reproduce

1. On back-end of the dotCMS demo site, reset the workflow for the Blog content item titled `Easy Snowboard Tricks You can Start Using Right Away`.
    * You can do this by right-clicking on the content item in the `Blogs` custom content search portlet.
    * _Note:_ This does not have anything to do with causing the bug - it's just necessary to ensure the content item is in the "Editing" step of the workflow (so the "Save as Draft" workflow action will be available in step 3, below).
2. Display the following image (from the front-end of the dotCMS demo site) in a different browser session (such as an Incognito Window): https://demo.dotcms.com/contentAsset/image/f1d378c9-b784-45d0-a43c-9790af678f13/image
    * This is the image from the "Easy Snowboard Tricks You can Start Using Right Away" Blog content.
    * Result (Correct): The image displays in the browser.
3. In the back-end, edit the "Easy Snowboard Tricks You can Start Using Right Away" content item.
    * Execute the "Save as Draft" workflow action.
4. Refresh the tab with the URL from step 2 (https://demo.dotcms.com/contentAsset/image/f1d378c9-b784-45d0-a43c-9790af678f13/image).
    * **Result (Wrong):** The URL now fails to display an image.
    * Specifically, the URL is being rewritten to `https://demo.dotcms.com/dotCMS/login?referrer=/contentAsset/image/f1d378c9-b784-45d0-a43c-9790af678f13/image`.
        * This suggests that permission to access any Binary images in the content item using this path is being denied for anonymous users - but it should not be since there is a live version of the content that contains the image.
5. Now access the same image using the `/dA` path: https://demo.dotcms.com/dA/f1d378c9-b784-45d0-a43c-9790af678f13/image
    * Result (Correct): The image is displayed in the browser.

## Expected behavior

**Specifically:**

When a Binary field for a content item that currently has both live and working versions is accessed, the Binary field from the current live version should be returned without attempting to authorize the user.

* This should be true regardless of whether the Binary field is an image or a file, and regardless of what path format is used to access the binary field.  This includes at least all of the following formats (though there might be others we support that aren't in this list):
    * `/dA/{id}`
    * `/contentAsset/image/{id}/{binaryFieldVar}`
    * `/contentAsset/raw-data/{id}`

**More generally:**

The permissions checks for different image access paths (e.g. `/dA/{id}` vs. `/contentAsset/image/{id}/{field}`, etc.) should behave the same.

* Even though the code to parse the paths is (and must be) different, the code to check the permissions should, if at all possible, be the same.
* Having different code doing the same permissions checks duplicates effort, and is bug-prone.

## Desktop (please complete the following information):
 - OS: Win 10 Pro
 - Browser: Chrome, FF, and Edge (the Chromium version)
 - Version: 5.3.7

## Additional context

I believe this bug has been around for a while.  I'm pretty sure I've been bitten by it before, but since the problem went away when the content was published, I didn't realize it was a bug.

But it's actually pretty ugly.  It's not an abstract issue or an edge case - it's continually biting us on our own documentation site, including our production site.

* Alot of our documentation uses the `/contentAsset/image` path.
    * And in some of these cases, using the `/dA` path is not an option - because the image filters being applied are not available with the `/dA` path format.
* So this bug means any time we create unpublished version of these documents, the images in the documents stop being displayed on the front-end.

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/19208

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19228

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. Tested on release-5.3.8 // Postgres // FF
