### ISSUE TITLE
Apps: Move fetch content from listing and detail (and anything else) to the resolver

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19211]
To avoid blank screen when we get to the route we need to load the content and the resolver and fill the component with that data.

For example: [this](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-apps/dot-apps-list/dot-apps-list.component.ts#L56) should be fetched in the resolver.

The same applies for detail pages, when this pages loads all the content should be there unless there is an user action to ask for data.

## Acceptance Criteria

1. Make sure all the content on the pages is loaded when the routing ends avoid blank states
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1445/files

**Comment by alfredo-dotcms** [comment]
core-web branch: issue-19211-Apps-Move-fetch-data-to-resolver

**Comment by nollymar** [comment]
Passed internal qa
