### ISSUE TITLE
Tinymceprops can't handle #dotParse when editing a page

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#19214]
You can change the tinyMCE properties by using tinymceprops. This works fine with static JSON but you can also use velocity in this. This also works fine when you edit content from the content search portlet, but when you are on a page and you want to edit a piece of content the #dotParse is rendered as a DIV which breaks the javascript:

![image](https://user-images.githubusercontent.com/2195163/91940810-5e846180-ecf8-11ea-9e8a-6dcc94133783.png)

**To Reproduce**
1. Go to the Rich Text content type on the demo site
2. Add tinymceprops with value #dotParse("/tinymceprops.json") to the WYSIWYG, using Field Variables.
3. Create a file in the ROOT called tinymceprops.json with some valid value in it, for instance
`{ toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | fullscreen", convert_urls: false, plugins: "fullscreen" }`
4. Go to the Content Search portlet and open a Rich Text content 
**or**
5. Go to a page that contains a Rich Text like /destinations/index
6. Edit the piece of content on it. The result will be an empty popup and a javascript error:
_Uncaught SyntaxError: expected expression, got '<'_

**Expected behavior**
The popup should open normally

**Additional context**
I think the edit view of the page renders the #dotParse with an icon or something instead of as JSON. This breaks the javascript since it expects a JSON object but actually gets raw HTML code, which does not parse.

**Workaround**
Do not use #dotParse in a tinymceprops field (which is a pity when multiple WYSIWYG editors need the same config)

**Comment by wezell** [comment]
@Xander-Steinmann workaround for now.  In the `tinymceprops` field variable add a $dontShowIcon before your dotParse and it will prevent this from happening.
```
#set($dontShowIcon="true") #dotParse("/testing.json")
```

**Comment by wezell** [comment]
This also adds back the "show .vtl filename" functionality

![Screen Shot 2020-09-02 at 1 19 48 PM](https://user-images.githubusercontent.com/934364/92015687-2ba19400-ed1f-11ea-9ee5-7905dca583a1.png)

**Comment by wezell** [comment]
PR: #19217

**Comment by erickgonzalez** [comment]
Working as it should. The edit content dialog shows up correctly in both options (from Content Search and from a page).

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF

**Comment by jdotcms** [comment]
the issue could be fixed by two ways:
1) Change the custom field to #dotParse('//starter.dotcms.com/application/vtl/custom-fields/url-title.vtl')
2) Copy the vtl to the new site

Probably an improvement could be to show a better error message when the content editor is being rendered
