### ISSUE TITLE
Sort in "show on listing" column with no data for any content returns no result

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19210]
Coming from: https://github.com/dotCMS/core/issues/19169#issuecomment-685113754

## STR

1. Create a content type with 2 field: both show in list but only one required
2. Create multiple pieces of content and **don't fill the non-required field in any of the contentlets**
3. Go to content search and sort by that empty field
4. We get no results.

## Acceptance Criteria

1. It should show results
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19250

**Comment by fabrizzio-dotCMS** [comment]
The problem previously reported has. been fixed. 
Plus the sort feature works just fine. The sort is performed on the rows with values different from empty. Empty rows are always sent down to the bottom.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.8 // Postgres // FF
