### ISSUE TITLE
Push-publishing archived pages in the receiver results in pages losing their URL.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#19221]
Tested issue #18920 against **release-5.3.8** and found another problem. I did it with pages and file-assets 
basically I had a sender with a folder with pages and images. I sent each one of them (one by one) to the receiver.
Once in the receiver, I verified the contents to ensure the items had been sent correctly. Then I had the items on the receiver archived. Back on the sender, I introduce a change (like removing and adding a new contentllet) for pages. Then I push-publish the page again. The page effectively gets unarchived but the url property is no longer there.  if you open the page properties dialog. You'll see it is missing. there too.. 
Files-Assets are not affected by this bug.
see attached gif
 
![gonne-url](https://user-images.githubusercontent.com/37148755/92034016-e040b300-ed29-11ea-883e-c5b9e5546199.gif)

_Originally posted by @fabrizzio-dotCMS in https://github.com/dotCMS/core/issues/18920#issuecomment-685987381_

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/749

**Comment by bryanboza** [comment]
We still be able to reproduce the same case here: 

Tested with two servers of release-5.3.8 // Postgres (both updated 09/11)

To recreate: 
- Create a new page 
- Add a new piece of content to the page
- Push it 
- Go to the receiver site and unpublish/archive the page 
- From sender add a new piece of content to the page 
- Try to push again 
- Check the page on receiver 

![image](https://user-images.githubusercontent.com/2641437/92980871-d23f1080-f454-11ea-9bbd-feef830844c0.png)

**Comment by nollymar** [comment]
The ee.jar used for this test was outdated. Please test it again

**Comment by bryanboza** [comment]
Tested with the last version of the ee.jar, now after push the second time the page is appearing as the same status of the page in the sender side, but the page still being associated to the archived step on receiver, and we have no workflow actions to execute 
SC: https://www.screencast.com/t/TvAMnbx8ka

We need some work here

**Comment by wezell** [comment]
Latest comments already reported in #19200. and #19193
