### ISSUE TITLE
Ship dotCMS with latest Tomcat version

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#19241]
We need to upgrade to the latest version of tomcat - along with a few security updates, this will allow us to do a few things:

1. Set us up to run in Java > 8
2. Allow us to set the SameSite Attribute on Tomcat Cookies.
3. The latest tomcat versions have a few security fixes that, while they don't apply to us, shows good project hygiene.

**Comment by dsilvam** [comment]
New tomcat branch created: https://github.com/dotCMS/tomcat/tree/9.0.41

**Comment by wezell** [comment]
Please also add the sameSite attribute to our default tomcat:

https://stackoverflow.com/questions/57505939/how-to-set-samesite-cookie-in-tomcats-cookie-processor
