### ISSUE TITLE
[Content] : Multi-tree reference being wiped out after content edit

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19245]
Reported via Support: [102338](https://dotcms.zendesk.com/agent/tickets/102338)
Reproducible in dotCMS 5.3.6.2, our Demo Site, and latest master.

The Multi-tree data structure is being wiped out when a content present in more than one HTML Page is updated or moved around in its Container.

**To Reproduce**
1. Create two HTML Pages: `test-1`, and `test-2` using the Default Template.
2. Go to the `test-1` page, select `Rich Text`, and add the "Before You Book" Contentlet.
3. Now, go to the `test-2` page, select `Rich Text`, and add the "Before You Book" and "Adventure travel done right"  Contentlets.
4. Make sure that both pages still have the Contentlets you added. One for `test-1`, and two for `test-2`.
5. Go back to `test-2`, and switch the "Adventure travel done right" Contentlet up in the Container for it to come first now.
6. Go to the Maintenance portlet and flush all caches.
7. Go to the `test-1` page, and you'll see that its reference to the "Before You Book" Contentlet is gone.

**Expected behavior**
HTML Pages must be able to retain its content structure, unless direct manipulation or a deletion takes place.

**Additional context**
There's currently no workaround for this issue, as it looks like the problem comes from the source code. Specifically, one of the database queries.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/19253/files)

**Comment by erickgonzalez** [comment]
Tested working as it should. After adding/deleting/moving content from one page is still visible from the other page.

**Comment by erickgonzalez** [comment]
Also got a response from client affected by this issue and said it's working fine.

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps on MySQL and Postgres and now I'm unable to reproduce, based in the clients feedback this is working as expected.
