### ISSUE TITLE
Content Search: When a workflow action is executed, the execution results are not displayed

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19257]
After a workflow action is executed on a piece of content, this message is always shown: "Unable to show available actions".
**Version: 5.3.8**

![Screen Shot 2020-09-11 at 08.33.06.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/0591dd1c-1dc1-458f-a22b-8957c818947d)

**Steps to reproduce:** 
1. Go to Content Search and select any piece of content.
2. Click on "Available Workflow Actions" and click "Copy", then select the Copy option to execute the action.
3. After the execution is done, you should see the message "Unable to show available actions" as shown above.

**Reason:** a JS is failing

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19258

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes, tested on release-5.3.8 // Postgres // FF
