### ISSUE TITLE
Support GraphQL Schema invalidation across cluster

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19255]
Currently this is cached per JVM so this is problematic on a cluster setup. 
We need to use our normal cache regions for this as well.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19256

**Comment by dsilvam** [comment]
Note to QA: Test that modifying the data model (create/modify content types and/or fields) invalidates the GraphQL cached-schema.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
