### ISSUE TITLE
Limited User can not edit Categories

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19267]
**Describe the bug**
As a Limited user with the required permissions, I can not edit categories. The form loads blank.

<img width="1628" alt="Screen Shot 2020-09-10 at 5 04 49 PM" src="https://user-images.githubusercontent.com/5278970/93222996-cd1be300-f72c-11ea-9d92-825cc50c1f29.png">

**To Reproduce**
1. Give the required permissions over categories to a limited user (Add Children and Edit over the All Sites).
2. Log in as the limited user.
3. Navigate to `Categories` Tool.
4. Click over one category
5. Move to the `Properties` Tab, it should load all the info of the Category.

**Expected behavior**
A limited user with the required permissions should able to edit categories.

Reproducible in demo (5.3.7) and master.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19296

**Comment by bryanboza** [comment]
We need some work here: 

- To edit an existing category or a sub level category we don't need the "Add children" permissions, this should be just to edit a top level category. 
- We need be able to edit categories just with the edit permissions

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19326

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
