### ISSUE TITLE
Content pop-up is not always loading the content list 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19263]
When you are on edit mode and try to add a new piece of content to any page, the content pop-up is not always loading the list of all the contents  

**To Reproduce**
- Login as admin 
- Create a new page 
- Try to add a new piece of content 
- In the content pup-up, make sure always auto load the list of all the contents 

**Expected behavior**
We should be able to display that list and also use the filter without problems 

**Screenshots**
SC: https://www.screencast.com/t/6dlXUovvKMo4

**Desktop (please complete the following information):**
Tested on release-5.3.8 // Postgres // FF

**Comment by wezell** [comment]
Another case:
1. Load starter site
2. Order by content type
3. Go to page... 4
4. Try to change content types to "Blog"

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19269

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after those changes... Tested on release-5.3.8 // Postgres // FF
