### ISSUE TITLE
Importing bundle with pages and content taking too long

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19270]
This is happening in our postman tests: 

```
POST http://sidecar:8080/api/bundle?sync=true [200 OK, 869B, 1m 40.7s]
curl-tests_1     |   ┌
curl-tests_1     |   │ { bundleName: 'assets.tar.gz',
curl-tests_1     |   │   status: 'SUCCESS' }
curl-tests_1     |   └
curl-tests_1     |   ✓  Bundle uploaded sucessfully
```

Bundle includes:
* HTMLPage /blog/index
* HTMLPage /blog/destinations/costa-rica
* Contentlet [Blog] Ecotourism in Costa Rica
* Blog Detail Page /blog/blog-detail
* Dependencies of each item above

We could glowroot this and determine what can be optimized to lower this time.

**Comment by wezell** [comment]
dupe #19646
