### ISSUE TITLE
Add "Get token" option to "Add End point" screen

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#19275]
Add option to get token automatically from the receiver

**Comment by dsilvam** [comment]
Passed Internal QA: This is working as expected, although I have a doubt. Is 404 the correct response code when trying to get a token with a limited user?

**Comment by bryanboza** [comment]
@dsilvam No, in case of a limited user should return a `401 Unauthorized Error`

**Comment by freddyucv** [comment]
> @dsilvam No, in case of a limited user should return a `401 Unauthorized Error`

but it should be a bug from the original end point

**Comment by dsilvam** [comment]
I think it should be 403 actually. @bryanboza @freddyucv . But yes, freddy is right.

**Comment by bryanboza** [comment]
We need some work here: 

- When you are requesting a token we need to disable the buttons from the main window, this because if you click on save or cancel we are closing the window without request the token, and lost your input data
![image](https://user-images.githubusercontent.com/2641437/101796888-074c1500-3acf-11eb-924c-3d9cf5e32876.png)

- Need to fix the response code on the endpoint in case of limited user, according to the discussion should be (403-Forbidden)

**Comment by victoralfaro-dotcms** [comment]
Tested on release-20.12 local branch.
Main buttons were removed.
![image](https://user-images.githubusercontent.com/64026161/102370246-7a97d000-3f82-11eb-8d59-c9a7736a8496.png)
Error message telling its forbidden shows.
![image](https://user-images.githubusercontent.com/64026161/102370806-1fb2a880-3f83-11eb-83f5-3524e157e59a.png)
Log message.
![image](https://user-images.githubusercontent.com/64026161/102371205-8f289800-3f83-11eb-8ccc-ed2d71aa703a.png)

**Comment by bryanboza** [comment]
We get a 500 error in case of invalid server url.  We need to handle this exception, the same thing at log level, we need just a line with a clear error "Invalid server url"

![image](https://user-images.githubusercontent.com/2641437/103585895-928bb100-4ea9-11eb-9bc4-dc8c1a77ed83.png)

**Comment by victoralfaro-dotcms** [comment]
New message error when server is not valid
![image](https://user-images.githubusercontent.com/64026161/104051283-86f00100-51ad-11eb-918c-3e1e973d75a3.png)
Algo an error is log:
![image](https://user-images.githubusercontent.com/64026161/104051330-9707e080-51ad-11eb-8fd2-21bac95d61b2.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.01 // Postgres // FF
