### ISSUE TITLE
Legacy containers personalization/cache issue

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19285]
If you use page personalization with a legacy container, and the page initially loads with the default persona, the personalized versions do not show the personalized content.  To reproduce:

1. Using the starter site, create a new page with just the Banner Container in it.  The Banner container is a legacy container.
2. Personalize this container for 2 or 3 of the personas, adding different banners for Eco, Ocean, etc.
3. Publish the page.
4. In an incognito window test to see if personalization works by switching personas - it might, depending on how the page cache was loaded
5. In your incognito, set yourself to the default persona
6. In the dotCMS backend, flush the cache
7. In your incognito window, refresh the page (loading mutlitrees for the default persona).
8. Test to see if personalization works by switching personas - the banners do not display for the personas.

If, after the cache flush, you load the page with a non-default/personalized persona, the personalization works normally.

The video below shows the banners working, then flushing the cache (with the default persona selected) and then the banners disappearing.

![legacy-container](https://user-images.githubusercontent.com/934364/93606637-52560080-f996-11ea-8c61-43f816746bdd.gif)

**Comment by freddyucv** [comment]
PR https://github.com/dotCMS/core/pull/19447

**Comment by dsilvam** [comment]
Passed Internal QA: Following the steps described in the ticket description changing personas display the proper personalized version of the page.

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now it works as expected... Tested on release 20.11
