### ISSUE TITLE
Card view in content search loading in the background

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19290]
**Describe the bug**
When you load the content search portlet in list view you can see some images broken in the console, those images are from the card view which should not be loaded if the user don't ask for it.

**To Reproduce**
1. Go to demo.dotcms.com content search portlet (in list view mode)
2. Open the browser console
3. See error

![Screen Shot 2020-09-21 at 12 47 25](https://user-images.githubusercontent.com/751424/93808022-ae27c000-fc08-11ea-8892-e1dafd6fbf0b.png)

**Expected behavior**
Card view should only load when users ask for it or when is set in the local storage

## Acceptance Criteria

1. Make sure card view load on demand.
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20782/files

**Comment by nollymar** [comment]
**Passed internal QA:** 
![Screen Shot 2021-08-16 at 4 00 00 PM](https://user-images.githubusercontent.com/8741395/129628899-c42d10cf-71f9-4165-9430-9c4231491ef3.png)

**Comment by nollymar** [comment]
**Needs work:** View this [comment](https://github.com/dotCMS/core/pull/20782#issuecomment-901223478)

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF
