### ISSUE TITLE
Create an Schedule Github Action to clean the test result repo

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19295]
**Is your feature request related to a problem? Please describe.**
To improve the timing on running the test we need to remove the last two weeks of report from the repo: https://github.com/DotCMS/test-results/

**Describe the solution you'd like**
We need to clean up and only have the last two weeks of tests, this means, we need to remove all the branches in which the last commit was 2 weeks ago.

Using a Schedule Github Action that should:
1. Everyday
2. After office hours.

## Acceptance Criteria

1. Create the Schedule Github Action
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by ivorpad** [comment]
PR https://github.com/dotCMS/test-results/pull/1
