### ISSUE TITLE
Cache busting on login route

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19299]
SAML and other single signons means we need to have a logout page like other systems have - see googles:

![Screen Shot 2020-09-22 at 12 20 52 PM](https://user-images.githubusercontent.com/934364/93909734-155b7800-fcce-11ea-9871-d109681954b3.png)

Additionally, we need to bust the browser cache whenever a user requests or is redirected to the login screen on dotCMS.  This is so the login properly redirects whenever SAML login is enabled.

`/dotAdmin/` --> `/dotAdmin/#/public/login`

**Comment by hmoreras** [comment]
this is donde under this PR: https://github.com/dotCMS/core-web/pull/1447/

**Comment by fmontes** [comment]
Close it as per Will request
