### ISSUE TITLE
Simplify Quartz Impl

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19291]
When we start quartz, we start 3 schedulers - the `SequentialQuartzScheduler`, the `StandardQuartzScheduler` and the `LocalQuartzScheduler`.  Each of these 3 schedulers have thread pools of 50 threads just sitting there doing nothing - that is 150 threads sitting around that we don't need.

We should simplify our quartz impl and only have 1 Scheduler with say 10 threads.  We do not need any more than that.  Additionally, we should replace the local quartz scheduler with standard java scheduled tasks.

Also, there are a number of jobs in the `DotInitScheduler` that we no longer need.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19293

**Comment by fabrizzio-dotCMS** [comment]
Note to QA:
I would recommend we smoke-test all quartz related functionality to verify none of that is broken
e.g. 
 
- Site search 
- Job Scheduler Portlet / User Jobs
- Fire some common operations that we know are tied to Quartz like:    
     - Delete a field from a content type
     - Apply cascade permissions
     - Delete persona
     - Reset Permissions
     - Delete User
- Additionally to that we need to verify the number of threads associated with each scheduler. For this, we could use The Control Panel - Maintenance Portlet - Threads Tab. From there do `Reload Threads` and compare the output against demo. 

You should be able to identify that the number of threads associated with a Quartz scheduler is significantly lower. 

Threads named like: `"DotMarketingQuartzLocalScheduler_Worker-37"`  should no longer appear.

Only threads like: `QuartzScheduler_DotMarketingQuartzScheduler`

**Comment by alfredo-dotcms** [comment]
Internal QA results:

- [x] Site search

Fire some common operations that we know are tied to Quartz like:
- [x] Delete a field from a content type
- [x] Apply cascade permissions
- [x] Delete persona
- [x] Reset Permissions
- [x] Delete User
- [x] Job Scheduler Portlet / User Jobs

**Comment by fabrizzio-dotCMS** [comment]
Additional Note to QA: 
The **Job Scheduler** Portlet has been affected by this change. 
 - The **User Jobs** and **Recurrent Campaign**  Tabs has been removed.
 - While System Job Tab is still available it can also be accessed via Control panel - Maintenance

**Comment by nollymar** [comment]
**Internal QA:** Now, only 10 threads are running: https://gist.github.com/nollymar/ed84fdf019752c76d1785b424f3ed4a4

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 based on the provided comments
