### ISSUE TITLE
Static Plugins not compiled against AspectJ

### ISSUE THREAD

**Issue by oarriet** [dotCMS/core#19297]
-I am not 100% sure about this one-, but I believe that the static plugins are not compiled against the `AspectJ` and this causes that annotations as `WrapInTransaction` are being ignored. 

Meaning that each time a Java class has been modified using static plugins, we are losing the whole transaction logic (to mention just one example).

I have an example of a [stacktrace dotCMS source](https://gist.github.com/motiv-solutions/77b6e0006fc63d308a1582cb7ea8f57c). See the difference between [this stacktrace from distro](https://gist.github.com/motiv-solutions/95c45b79f0264f286b123f0f888251d8) running several static plugins modifying for example: BrowserAjax.java and ESContentletAPIImpl.java.

[In this case we are losing all this code.](https://gist.github.com/motiv-solutions/77b6e0006fc63d308a1582cb7ea8f57c#file-gistfile1-txt-L32-L38)

**Comment by wezell** [comment]
@oarriet 

I am not sure this is going to be resolved - we pretty much consider static plugins as deprecated at this point.  They do not work well in our docker images and OSGi can take care of most of what static plugins can do.

**Comment by oarriet** [comment]
@wezell understood.
