### ISSUE TITLE
RSS Feed for Release Notes/Changelog

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19298]
Requested by Sebastian Carreras - Exted Stay America / ESA in ticket: 
https://dotcms.zendesk.com/agent/tickets/102440

As a developer I would like to have an RSS feed / email notification of release notes So that we can be proactively informed of when these changes occur and review to see if an upgrade is appropriate for us.

Possible ideas:
- Update the github tags that are created ( https://github.com/dotCMS/core/tags ) to reference the Change Log Documentation ( https://dotcms.com/docs/latest/changelogs#release-5.3.8 ) and have devs subscribe to Github Releases
- Provide a feed for the changelog page https://dotcms.com/docs/latest/changelogs

Additionally:
- it would be nice if the dockerhub registry also pointed at the changelog documentation ( https://hub.docker.com/r/dotcms/dotcms/ )

**Comment by wezell** [comment]
This is implementation and not a dotCMS issue
