### ISSUE TITLE
Content Search list doesn't paginate when adding content to a container - dotCMS v5.3.x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19307]
When trying to add content / widgets to a page's container, the results aren't paginated. Refining the search does not add the pagination either. 

**To Reproduce**

1. Open a Page that has containers
2. Click on the (+) button to add contents
3. Scroll down to the bottom of results
4. No pagination appears

**Expected behavior**
If there are more results that are available, there should be pagination to browse to the correct content. 

**Screenshots**
185 Matching Results
![image](https://user-images.githubusercontent.com/49727631/94036191-a93e4a00-fd89-11ea-93f9-0377d6bd34ce.png)

Scroll to bottom - no pagination

![image](https://user-images.githubusercontent.com/49727631/94036618-1c47c080-fd8a-11ea-965f-47f23257f9ff.png)

Refine search - 53 Results

![image](https://user-images.githubusercontent.com/49727631/94036291-c4a95500-fd89-11ea-8084-25bb1631ddc8.png)

No pagination 

![image](https://user-images.githubusercontent.com/49727631/94036592-1356ef00-fd8a-11ea-9c3a-7f2690fc9295.png)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: Chrome/FF
 - Version: 5.3x

**Additional context**

**Comment by wezell** [comment]
This is a dupe:  #19304
