### ISSUE TITLE
Can't add new custom tool group to dotCMS menu

### ISSUE THREAD

**Issue by yasindilekci** [dotCMS/core#19306]
**Describe the bug**
When I create a new custom tool group, it doesn't appear in the dotCMS menu on the left side of the page.

**To Reproduce**
1. Login to the demo website
2. Click on Control Panel -> Roles & Tools
3. Click on System -> Tools (tab)
4. Click on 'Create custom tool group'
5. Give the group a name and add at least one tool
6. Click save

**Expected behavior**
The custom tool group should appear in the left side menu in dotCMS admin UI (but it doesn't).

**Screenshots**
![image](https://user-images.githubusercontent.com/10976988/93988316-d9391d80-fd88-11ea-8d05-dd8417a99ab4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (but this shouldn't matter)
 - Browser Chrome (but this shouldn't matter)
 - Version 85.0.4183.102 (but this shouldn't matter)

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
Not applicable

**Comment by wezell** [comment]
You need to assign the tool to a role that you have.  Unless it is assigned to a role, it will not show up.
