### ISSUE TITLE
Starter export for personalized pages exports them all

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19300]
To test:

1- Add a new page
2- Add content to the page
3- Change the persona
4- Delete the content added in the step 2.
5- Add a different content to the page.
6- Check from the FE that if you change persona, the content changes.
7- Go to Maintenance > Tools.
8- Export Data/Assets
9- Copy the zip file `webapps/ROOT/dotsecure/backup/` to another location.
10- Clean up the dotcms instance.
11- Copy the zip file from the location to `webapps/ROOT/`
12- Delete the `starter.zip`
13- Change the name of the zip file to `starter.zip`
14- Start the instance.

Check from the FE that if you change persona, the content changes.

![Screen Shot 2020-09-22 at 12 25 17 PM](https://user-images.githubusercontent.com/934364/93910156-b34f4280-fcce-11ea-8f91-e2927dae899f.png)

**Comment by erickgonzalez** [comment]
Seems like the bug is at the export level, every entry value is being set to `dot:default` instead of the actual value.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19313

**Comment by erickgonzalez** [comment]
**Note to QA:**

This can be also tested using the new starter `20200925`, the home page banner should change between personas.

**Comment by bryanboza** [comment]
Fixed, tested with the new starter and this is working as expected. Tested on release-5.3.9 // Postgres // FF
