### ISSUE TITLE
Edit Mode: Adding Content on Page missing pagination

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19304]
![Screen Shot 2020-09-22 at 5 24 54 PM](https://user-images.githubusercontent.com/934364/93939356-afd0b100-fcf8-11ea-8cce-d8e4f6fa8798.png)

- the field order needs to be the same as the content search screen
- Customers need to be able to paginate
- We need the "Search All" box even when you select a content type.  

### Video
https://drive.google.com/file/d/17hYAccJ6J3iFZxEsdV2ltFfCUUuz8Riq/view

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/19318

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF
