### ISSUE TITLE
Large bundles can take too long for load balancers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19321]
If you are trying to generate a large bundle, say your whole site, we try to do that in a single request.  While the bundle is being generated, we are returning nothing to the client http request - and this can cause load balancers to time out.  The same can happen when generating a starter.zip

We need to split apart bundle generation and bundle downloading.

1. We need to change "Download Bundle" to "Create Bundle" or "Generate Bundle" which fires a stateful background job to build the bundle.  
2. Once a bundle is built, the user should see the option to download bundle from the drop down menu.  Additionally,  we could show a growl that includes the link to download the generated bundle

**Generate Endpoint**
* Invalid FilterKey, it will use the default filter.
* Invalid Operation, it will use UNPUBLISH.

**Comment by wezell** [comment]
PR: #19342 

Core-Web: dotCMS/core-web#1440

**Comment by fmontes** [comment]
Needs postman tests

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
These changes were not back-ported into 5.2.8.4 as they were too extensive.
