### ISSUE TITLE
Introduce ability to run integration tests on all db providers via commit message

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19323]
Currently the integration tests run against Postgres on PRs. We need a way to fire the tests on all dbs, indicated by an special commit message.

**Comment by victoralfaro-dotcms** [comment]
These are the commit messages to run ITs with a specific DB vendor to use:
run-postgres
run-mysql
run-oracle
run-mssql
run-all

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19343
