### ISSUE TITLE
After upload image the list is not refreshing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19335]
From: https://github.com/dotCMS/core/issues/19181#issuecomment-698581069

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19382

**Comment by fabrizzio-dotCMS** [comment]
yup. Now it's working as it should. Tested on release-20.10.1

**Comment by bryanboza** [comment]
Now we are refreshing if you try from site browser, but if you try from a modal adding a image from a WYSIWYG field we are not refreshing, you need to do that manually 
Here the video: https://www.screencast.com/t/wzfDPfuIMQ

Tested on relase-20.10.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested in a fresh environment and now it is refreshing after upload. Tested on release-20.10.1
