### ISSUE TITLE
[core] : GIF files not showing up correctly in the backend

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19338]
Reported via Support: [102410](https://dotcms.zendesk.com/agent/tickets/102410)
Reproducible in dotCMS 5.3.4, our Demo Site (5.3.8 and 5.3.9), and latest master.

**Describe the bug**
GIF files are a supported image format in dotCMS. However, such file types are not being displayed correctly in specific portlets/dialogs in the back-end. Other image formats show up as expected.

**To Reproduce**
1. Log into our Demo Site: https://demo.dotcms.com/dotAdmin
2. Go to the **Site Browser**, then go to the `/images/gallery/` folder and upload the following GIF file. You'll see that the image file will show up correctly in there:

![10-off-50](https://user-images.githubusercontent.com/8779585/94294644-59908780-ff1d-11ea-9ed6-2344f88e2a78.gif)

3. Create a Content Type called `Test CT` with two fields:
3.1 Text Field called `Title`.
3.2 Image Field called `Image`.
4. Create a new Contentlet of type `Test CT`. For the Image field, click the **BROWSE...** button to open up the File Selector widget. Go to the `/images/gallery/` folder, and you'll notice that the GIF image is showing up as broken:

<img width="663" alt="file_selector" src="https://user-images.githubusercontent.com/8779585/94296075-7f1e9080-ff1f-11ea-8436-477842575bba.png">

5. When you select the file, you'll notice that the image is also broken in the **Content Edit** portlet:

<img width="668" alt="content-edit" src="https://user-images.githubusercontent.com/8779585/94296143-99586e80-ff1f-11ea-8833-f459f3411fc4.png">

**Expected behavior**
dotCMS must be able to handle common image file types.

**Additional context**
As mentioned before, the GIF file shows up correctly when you double-click/edit the image Contentlet itself from the **Site Browser**. The Image Servlet used to render the preview here is: https://demo.dotcms.com/contentAsset/image/235a4654-9e13-48d8-b972-43bba312def3/fileAsset/filter/Thumbnail/thumbnail_h/250/r/60354484

However, the Image Servlet used in the **Content Edit** portlet is: https://demo.dotcms.com/dA/235a4654-9e13-48d8-b972-43bba312def3/250w/20q/rand/0.8582981095344357?language_id=1

**Comment by john-thomas-dotcms** [comment]
So just a couple notes:

**Comment by john-thomas-dotcms** [comment]
So just a couple notes:

* It appears we changed the URL format that displays the thumbnails in the content editing portlet and the file/image field file selection modal.
    * So a quick fix might just be to change the paths back to the `/contentAsset/image` format.
* But I'm wondering if there might be a more general issue with the `/dA` format not supporting image transformations with GIF files.
    * The new (`/dA`) paths seem to work fine with images other than GIFs.
    * The `/contentAsset/image` paths seem to work fine with GIFs.
    * So that suggests the new (`/dA`) paths might not handle GIF transformations properly.

**Comment by wezell** [comment]
Also interesting, this does not look broken on master - I tried an image field and the card view and both worked.

![Screen Shot 2020-09-25 at 2 48 31 PM](https://user-images.githubusercontent.com/934364/94304841-34604100-ff3e-11ea-854c-89f189675172.png)

**Comment by victoralfaro-dotcms** [comment]
Working as expected.
![image](https://user-images.githubusercontent.com/64026161/97459235-2ae14480-1901-11eb-86bb-2f9205343c7c.png)

**Comment by jcastro-dotcms** [comment]
**NOTE FOR QA:** This issue must be tested in a Cloud Instance, as it is **NOT** reproducible in a local environment.

**Comment by dsilvam** [comment]
It is @jcastro-dotcms but you need to run on Docker.

**Comment by victoralfaro-dotcms** [comment]
Tested on a local docker image.
Browsing for gif image creating new contentlet.
![image](https://user-images.githubusercontent.com/64026161/97606888-e7a4d580-19d5-11eb-90f6-69b07c02bd53.png)
Selecting image file
![image](https://user-images.githubusercontent.com/64026161/97607012-0acf8500-19d6-11eb-8543-6c9c05fb743e.png)

**Comment by bryanboza** [comment]
Fixed, tested in a docker instance and now it works as expected 
![image](https://user-images.githubusercontent.com/2641437/97630918-d8358480-19f5-11eb-8be5-c3a45419fa70.png)


Tested with this image: `dotcms/dotcms:20.10.1-prerelease`
