### ISSUE TITLE
Content Search screen not filtering on "select" fields - 5.2x+ - reproducable in demo

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19337]
When using the "Advanced" search options on the Content Search screen, content does not appear if you filter on a 'select' field. 

As reported in https://dotcms.zendesk.com/agent/tickets/102489

**To Reproduce**
Steps to reproduce the behavior in DEMO:
1. Create Content Type with a Select field with 2 options (or more)
2. Add contentlets with each option 
3. Go to Content Search and open Advanced options
4. Select any option to filter on the Select field

**Expected behavior**
Contentlets with the select value should appear.

**Actual behavior**
No Contentlets Appear.

SCREENSHOTS

Content Type
![image](https://user-images.githubusercontent.com/49727631/94294315-41bd0180-ff25-11ea-8e79-70b6a835bc90.png)

Select Field Options

![image](https://user-images.githubusercontent.com/49727631/94294351-513c4a80-ff25-11ea-8dc3-ab6f3ee3e51d.png)

Search Screen - no search options selected - shows all contentlets

![image](https://user-images.githubusercontent.com/49727631/94294436-73ce6380-ff25-11ea-8274-7c71b44e5a05.png)

Search Screen - Advanced options - Select field value selected - no contentlets shown

![image](https://user-images.githubusercontent.com/49727631/94294476-82b51600-ff25-11ea-9a32-2291b8ea2e7b.png)

The Queries from "Show Queries" 

```
Velocity Content Pull (cut and paste for use in a Widget):

#foreach($con in $dotcontent.pull("+contentType:Announcement +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +(Announcement.announcementType:\${esc.quote}\${esc.quote} Announcement.announcementType_dotraw:\${esc.quote}\${esc.quote}) +(Announcement.announcementType:\${esc.quote}news\${esc.quote} Announcement.announcementType_dotraw:\${esc.quote}news\${esc.quote})",10,"score,modDate desc"))
...
#end
```

```
Lucene Query (Copy this query for the back-end Query Tool):

+contentType:Announcement +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +(Announcement.announcementType:"" Announcement.announcementType_dotraw:"") +(Announcement.announcementType:"news" Announcement.announcementType_dotraw:"news") +languageId:1 +deleted:false +working:true
```

```
REST API Call URLEncoded (Use this URL for external applications or JavaScript on your Page):

http://demo.dotcms.com:8082/api/content/render/false/query/+contentType:Announcement%20+(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797%20conhost:SYSTEM_HOST)%20+(Announcement.announcementType:%22%22%20Announcement.announcementType_dotraw:%22%22)%20+(Announcement.announcementType:%22news%22%20Announcement.announcementType_dotraw:%22news%22)%20+languageId:1%20+deleted:false%20+working:true/orderby/score,modDate%20desc
```

**Comment by jasontt33** [comment]
testing

**Comment by toor33** [comment]
testing 2

**Comment by toor33** [comment]
blam blam blam

**Comment by Lhusar** [comment]
Is there any news about this? It has been more than a month.

thanks,
Lukas

**Comment by victoralfaro-dotcms** [comment]
Both contentlets are shown when specifying each in the `Announcement Type` filter.

![image](https://user-images.githubusercontent.com/64026161/98693752-4e12e780-2336-11eb-8241-c8fb53aeea75.png)

![image](https://user-images.githubusercontent.com/64026161/98693710-42bfbc00-2336-11eb-8a31-9f51de3b886a.png)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes, tested on release-20.12 // Postgres // FF
