### ISSUE TITLE
Allow SAML logout without cross-origin XHR request to SAML auth server to avoid CORS restrictions

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19359]
**Describe the bug**
To log out, a SAML user's browser sends an XHR request to their SAML auth server. This places a burden on the SAML server admins to ensure that dotCMS-referred logout requests receive proper CORS headers.

**To Reproduce**
1. Log in to back end with a SAML user
2. Click "Logout"
3. Backend UI is still available - the user was not logged out

**Expected behavior**
"Logout" should work without requiring CORS changes on the SAML server

**Comment by jdotcms** [comment]
This is already done, will be include on the next release

**Comment by jcastro-dotcms** [comment]
The official code changes are being worked on this other ticket: https://github.com/dotCMS/core/issues/19098
