### ISSUE TITLE
Create new logout page for SAML

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19353]
**Is your feature request related to a problem? Please describe.**
Create a new logout page

![Screen Shot 2020-09-29 at 10.11.35.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d12b1598-76b8-4719-ac74-ba70c682b72e)

The route: `/dotAdmin/#/public/logout`

**Describe the solution you'd like**
When click on the button we need to navigate to `/dotAdmin/#/public/login` with a `queryParam` to bust the cache

## Acceptance Criteria

1. Create new logout page
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
I think the sign in button should be right aligned

**Comment by wezell** [comment]
related: #19299
