### ISSUE TITLE
What's changed feature is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19355]
When you are on edit mode and try to use the What's changed feature, we are just showing a blank page and this feature is not working at all. 

![image](https://user-images.githubusercontent.com/2641437/94603891-210de800-0254-11eb-9c79-223414c1aa30.png)

We are getting a JSP errors in the log: 
https://gist.github.com/bryanboza/4a7e5ee9986b687812f90e40ceabf11b

**To Reproduce**
1. Login as admin
2. Create a new page 
3. Add a piece of content 
4. From edit mode, try to use the What's changed feature 

**Expected behavior**
We need to show the differences here 

**Desktop (please complete the following information):**
Tested on release-5.3.9 // Postgres // FF

**Comment by wezell** [comment]
PR: #19356

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF

**Comment by ian-b-cooper** [comment]
Support requested via zendesk here: https://dotcms.zendesk.com/agent/tickets/105718
