### ISSUE TITLE
Error adding multilingual content to a page that just exist in the default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19354]
We are getting an error when you try to associate a piece of content in some language that does not have versions in the default language or the language of the page. 
ST:  https://gist.github.com/bryanboza/efaf265928770767117d102be416f242

**To Reproduce**
1. Login as admin 
2. Create a new page in the default language (English)
3. Try to add a new piece of content to this page in Spanish 
4. Check your log file 

**Expected behavior**
We need be able to associate this content without errors 

**Desktop (please complete the following information):**
Tested on release-5.3.9 // Postgres // FF

**Comment by wezell** [comment]
@bryanboza can you do a screen cap for this?

**Comment by bryanboza** [comment]
Seems the piece of content is added, but we still with the error on the log, nothing in UI
