### ISSUE TITLE
Unable to edit category permissions as limited user even you have full rights 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19364]
Related to #19267 

If you add full rights (`Edit Permissions`) to some limited, when you log in as this user you are unable to see the permissions tab  
![image](https://user-images.githubusercontent.com/2641437/94725819-97285280-0319-11eb-9066-4f9b003e8d65.png)

**To Reproduce**
1. Login as admin 
2. Move to configuration --> Users --> Permissions and set full permissions to a limited on `All Sites`
3. Login as limited 
4. Select some category and make sure you are able to edit the permissions 

**Expected behavior**
We need be able to see the tab permissions when you have the `Edit Permissions`

**Desktop (please complete the following information):**
Tested on release-5.3.9 // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19422

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF
