### ISSUE TITLE
ContentType REST API does not accept field variables - e.g. WYSIWYG customization

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19376]
Unable to use a single REST API call to create Content Type that includes a WYSIWYG field with tinyMCE field variables.

According to our documentation at https://dotcms.com/docs/latest/create-content-types-of-each-base-type#multipleContentTypes a user should be able to use a single API call to create a Content Type, field and field variables. However if you include a WYSIWYG field with tinyMCE properties you must use TWO calls to create the full content type. In that link you can see the JSON includes a field with field variable, implying it should work.

As reported in zendesk ticket: https://dotcms.zendesk.com/agent/tickets/102306

Documentation link: https://dotcms.com/docs/latest/create-content-types-of-each-base-type#multipleContentTypes

**To Reproduce**
1. Export a Content Type with a customized wysiwyg to JSON 
2. Make REST API call using that JSON to create new Content Type on dotCMS instance.

**Expected behavior**
Content Type should be created with all fields and variables.

**Actual Behavior**
Content Type will not be created. You have to do one call to create the content type then a second to update it with the fields and variables. 

(Initially tested by Craig, Todd, Dean and Daniel with the same results)

**Comment by wezell** [comment]
You can see the field variables being resolved here:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/contenttype/transform/field/JsonFieldTransformer.java#L90

**Comment by victoralfaro-dotcms** [comment]
@wezell this issue is currently for when creating a new content type. But what about when updating it?
If a JSON with changes at any of the field variables level, should it update them the same way it does when creating new?

**Comment by wezell** [comment]
@victoralfaro-dotcms updating the content type should work in the same way, I think

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19641

**Comment by bryanboza** [comment]
Fixed,  tested using the provided examples in the documentation and now we are able to see the filed variables in the created content type..
