### ISSUE TITLE
Remove cancel option from the Integrity Check

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#19370]
Remove any code supporting the option of cancelling the Integrity Check at the java backend and the UI.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19409

**Comment by freddyucv** [comment]
**Passed Internal QA:** Cancel button is not showed when request a integrity checker

**Comment by bryanboza** [comment]
Fixed, now we don't have the cancel button any more.
