### ISSUE TITLE
What's changed is not detecting changes with widgets and forms 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19373]
If you have a page and you add a piece of content type widget or form and then try to use the `what's changed` feature, we are not detecting changes with these types of contents. Also, we are getting an error on logs 
Log: https://gist.github.com/bryanboza/5a9490e3c53d2b33f1c6f435ddb811d8

**To Reproduce**
1. Login as admin 
2. Create a new page, add a single piece of content and publish the page 
3. Add a widget to the page and try to see what's changed 

**Expected behavior**
We need be able to mark the differences from the live and working version of the page in any type of content 

**Desktop (please complete the following information):**
Tested on release-5.3.9 // Postgres // FF

**Comment by erickgonzalez** [comment]
Reproduced in demo
