### ISSUE TITLE
"414 Request-URI Too Large" when trying to delete large bundle

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19378]
**Describe the bug**
A bundle containing thousands of items cannot be deleted. 

DotCMS backend UI displays "Sorry an error occurred" message

The id of each bundle item is included in the url, causing "414 Request-URI Too Large"  server response
`https://example.comhtml/portlet/ext/contentlet/publishing/view_publish_queue_list.jsp?layout=com.dotmarketing.business.Layout@xxx&delete=id,id,id,id,...`

**To Reproduce**
Select the bundle in the backend UI and "Delete"

**Expected behavior**
Bundle is deleted

**Screenshot**
![Screen Shot 2020-10-02 at 12 14 30 PM](https://user-images.githubusercontent.com/628954/94958257-77756380-04ac-11eb-8923-a43e07e9d6ea.png)

**Comment by yolabingo** [comment]
cloud support - references ticket #102518

**Comment by wezell** [comment]
We should use the delete method on the BundleResource rather than the jsp call that we do now:

https://demo.dotcms.com/html/portlet/ext/contentlet/publishing/view_publish_queue_list.jsp?layout=com.dotmarketing.business.Layout@f6e4577&offset=0&limit=10&delete=48190c8c-42c4-46af-8d1a-0cd5db894797

**Comment by yolabingo** [comment]
To reproduce this issue on demo.dotcms.com:

-  set up a dummy receiver in Publishing Environments
-  create a bundle with all contentlets 
-  push publish the bundle to the dummy receiver, in order to move it the bundle to **Pending**
-  browse to Publishing Queue -> Pending and select the bundle (this selects all items in the bundle as well)
-  click "Delete"

The Delete action fails because the URL includes the IDs of all selected items in the bundle.

Video of the issue: https://drive.google.com/file/d/11zm1H_4V6cwctMhzn571vb5O2u5EBR8Z/view

**Comment by victoralfaro-dotcms** [comment]
Still see the erroneous behavior
![image](https://user-images.githubusercontent.com/64026161/99308809-1ddbb500-281e-11eb-87e2-d394f0a095cb.png)

**Comment by bryanboza** [comment]
Unable to reproduce after the last changes, tested on release 20.12 // Postgres // FF
