### ISSUE TITLE
Show cache size estimates cache screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19379]
It would be great if we could estimate the per object and per region cache sizes to help us when we are recommending how a customer should size their cache regions.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19425

**Comment by dsilvam** [comment]
Passed Internal QA: Showing size estimates per object and per region. 

<img width="1389" alt="Screen Shot 2020-10-26 at 12 48 38 PM" src="https://user-images.githubusercontent.com/1576794/97215078-a0c2a000-1789-11eb-9c6c-7ed4ded015ce.png">

**Comment by bryanboza** [comment]
Fixed, tested on release 20.11 // Postgres // FF
