### ISSUE TITLE
Replace HibernateUtil with DotConnect in all operations where the Fat Contentlet is used

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19399]
This is part of a bigger change. 

We have a legacy data model that needs to be updated and improved to streamline operations. Additionally, we have a number of classes that still rely on Hibernate which we need to get rid of. Hibernate causes us a number of issues that are hard to debug. Here is the main challenge - how to do this work without breaking existing customers implementations.

**Comment by nollymar** [comment]
**Note to QA:** Please, read the Note to QA of this card #19394

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
