### ISSUE TITLE
Add a create_date to the identifier table

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19396]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

We need to add a new column (create_date) to the identifier table to store the iDate of the Inode

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19441

**Comment by nollymar** [comment]
**Note to QA:** Test with #19395

**Comment by bryanboza** [comment]
Fixed, tested on release 20.11 // Postgres // FF 

![image](https://user-images.githubusercontent.com/2641437/98294407-85b81300-1f75-11eb-83f1-9c9a39a568ed.png)
