### ISSUE TITLE
Add an asset_subtype to the identifier table

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19397]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

We need to add a new column to the identifier table called _asset_subtype_ to store the contentType.variable

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19441

**Comment by nollymar** [comment]
**Note to QA:** Test with #19395

**Comment by nollymar** [comment]
Internal qa by @alfredo-dotcms

**Comment by bryanboza** [comment]
Fixed, tested on release 20.11 // Postgres // FF

**Comment by wezell** [comment]
This has an upgrade task - we need to test upgrading in all dbs

**Comment by fabrizzio-dotCMS** [comment]
I was requested to verify that the new column is added successfully in Oracle. And So I did. 
![Screen Shot 2020-11-23 at 15 39 37](https://user-images.githubusercontent.com/37148755/100018727-82f55480-2da2-11eb-95cd-23d790e08fea.png)
 
Log output:

15:33:46.367  INFO  startup.StartupTasksExecutor - Running Upgrade Tasks: Task201013AddNewColumnsToIdentifierTable
15:33:46.429  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ======================================================================
15:33:46.429  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ==> Executing upgrade script
15:33:46.429  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ======================================================================
15:33:46.429  INFO  db.DotConnect - Executing alter table identifier add owner varchar2(255)

15:33:46.501  INFO  db.DotConnect - Finished Executing alter table identifier add owner varchar2(255)

15:33:46.501  INFO  db.DotConnect - Executing alter table identifier add create_date date

15:33:46.602  INFO  db.DotConnect - Finished Executing alter table identifier add create_date date

15:33:46.602  INFO  db.DotConnect - Executing alter table identifier add asset_subtype varchar2(255)

15:33:46.683  INFO  db.DotConnect - Finished Executing alter table identifier add asset_subtype varchar2(255)

15:33:46.683  INFO  db.DotConnect - Executing create index idx_identifier_asset_subtype on identifier (asset_subtype)

15:33:46.844  INFO  db.DotConnect - Finished Executing create index idx_identifier_asset_subtype on identifier (asset_subtype)

15:33:46.850  INFO  startup.StartupTasksExecutor - Database upgraded to version: 201013

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify that the upgrade task is applied successfully on MS-SQL 
![Screen Shot 2020-11-23 at 21 06 49](https://user-images.githubusercontent.com/37148755/100042483-265d5e00-2dd1-11eb-91e8-f038dee77b38.png)


21:05:24.017  INFO  startup.StartupTasksExecutor - Running Upgrade Tasks: Task201013AddNewColumnsToIdentifierTable
21:05:24.128  INFO  db.DotConnect - Executing SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
21:05:24.132  INFO  db.DotConnect - Finished Executing SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
21:05:24.133  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ======================================================================
21:05:24.133  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ==> Executing upgrade script
21:05:24.133  INFO  runonce.Task201013AddNewColumnsToIdentifierTable - ======================================================================
21:05:24.133  INFO  db.DotConnect - Executing alter table identifier add owner NVARCHAR(255)
21:05:24.277  INFO  db.DotConnect - Finished Executing alter table identifier add owner NVARCHAR(255)
21:05:24.277  INFO  db.DotConnect - Executing alter table identifier add create_date datetime
21:05:24.410  INFO  db.DotConnect - Finished Executing alter table identifier add create_date datetime
21:05:24.410  INFO  db.DotConnect - Executing alter table identifier add asset_subtype NVARCHAR(255)
21:05:24.448  INFO  db.DotConnect - Finished Executing alter table identifier add asset_subtype NVARCHAR(255)
21:05:24.448  INFO  db.DotConnect - Executing create index idx_identifier_asset_subtype on identifier (asset_subtype)
21:05:24.493  INFO  db.DotConnect - Finished Executing create index idx_identifier_asset_subtype on identifier (asset_subtype)
21:05:24.521  INFO  startup.StartupTasksExecutor - Database upgraded to version: 201013

**Comment by bryanboza** [comment]
Fixed, tested on MySQL and Postgres and works as expected.
