### ISSUE TITLE
Add an owner field to the identifier table

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19395]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

We need to add a new column to the identifier table to store the owner field for the contentlet, the user.id who initially created it

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19441

**Comment by nollymar** [comment]
**Note to QA:** Cards #19396 and #19397 can be tested using these tests cases.

Please test the following scenarios:

**Case 1:** 

Using a fresh installation with a full starter verify that the columns `owner`, `create_date` and `asset_subtype` are created in DB (`identifier` table). Then, create different pieces of content, as well as containers, templates and links. Verify that new values are set for the new columns for each piece of content, container, template and link created.

`select owner, create_date, asset_subtype from identifier where id=?`

_Note:_  Containers, templates and links shouldn't have any `asset_subtype`.  

**Case 2:** 
Run an upgrade from an older dotcms version. With the upgrade, the existing data should have values set on the 3 new columns. You can verify it executing this query: `select owner, create_date, asset_subtype from identifier` or `select * from identifier where owner is null and create_date is null and asset_subtype is null`
Besides, create pieces of content, templates, containers and links and check values in the `identifier`  table as you did in _Case 1_ .

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF 

After run the UT we are setting this values to all the registers in the identifier table 
![image](https://user-images.githubusercontent.com/2641437/98297024-6e7b2480-1f79-11eb-834e-874587a30429.png)
