### ISSUE TITLE
Get rid of the Fat Contentlet, e.g. contentlet.business.Contentlet

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19394]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

**Comment by nollymar** [comment]
**Note to QA:** Please test all the different operations over contentlets: add, edit, remove, archive, push and import/export

The QA on this card includes these two more: #19398 #19399 , so they can be tested together.

**Comment by fabrizzio-dotCMS** [comment]
a Small issue was found regarding the title of a dotAsset it was reported in a separate bug https://github.com/dotCMS/core/issues/20655 to avoid blocking QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF

**Comment by bryanboza** [comment]
Some new issues reported but nothing blocker for now
