### ISSUE TITLE
Make sure metadata is generated only if needed

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19407]
Metadata generation should be smart when a new version of a content (that contains an image) is created or copied and the image is not modified, the metadata shouldn't be regenerated. The existing metadata file should be copied instead.

Use the SHA to verify if the metadata already exists, in which case we should link the existing metadata to the new version of the piece of content.

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/issues/19234

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF
