### ISSUE TITLE
Make the primary key of the identifier table as long as the dbs can handle as a primary key

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19401]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

We need to make this as large a field as can be a primary key for each of the main DBs.   (maybe not more than a `varchar(1000)`

**Comment by nollymar** [comment]
The primary key length was increased to `varchar(750)`.
PR: https://github.com/dotCMS/core/pull/19463

These are the max limits allowed per database: 

**Postgresql:** 2730 bytes

**Oracle**
Prior to Oracle 12c, regardless of the character semantics used, the maximum size of a VARCHAR2, NVARCHAR2 and RAW columns in a database are as follows.

VARCHAR2 : 4000 bytes
NVARCHAR2 : 4000 bytes
RAW : 2000 bytes
With the introduction of Extended Data Types, Oracle 12c optionally increases these maximum sizes.

VARCHAR2 : 32767 bytes
NVARCHAR2 : 32767 bytes
RAW : 32767 bytes

**MSSQL**
Bytes per primary key:	900

**MySQL**
Engine	                                                          Limit
InnodB with innodb_large_prefix disabled	  768 bytes
MySAIM	                                                          1000 bytes
InnodB with innodb_large_prefix enabled	  3072 bytes

**Comment by nollymar** [comment]
**Note to QA:** This card can be tested at the same time of #19395 

**Test 1:** Run a fresh installation and verify the length of the `id` column in the `identifier` table. It should be 750
**Test 2:** Run an upgrade from an older dotCMS version and verify the length as well

**Comment by nollymar** [comment]
It won't be implemented for now. The PR was reverted.

**Comment by wezell** [comment]
closing this in favor of the deterministic ids
