### ISSUE TITLE
Set Folder's Default File Type based on Parent Folder's default File Type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19410]
As a convenience, it would be nice that if you are adding a sub folder to a folder a specific default file type, that it would inherit the default file type of the parent.

So, you have a folder called `/images` with a default file type of `Image`.

When you add `/images/new-images`, via the browser or via webdav, it should default to file type `Image`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19429

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
This is not working in the release 20.11, we are not setting this value when you try to add a new sub-folder 
SC: https://www.screencast.com/t/o2zO8KDdg

**Comment by nollymar** [comment]
Fixed: https://github.com/dotCMS/core/pull/19610

**Comment by fabrizzio-dotCMS** [comment]
I was able to confirm the child folder in both scenarios inherits the `Default File Asset Type`.  
Works fine from Web Dav and Fie Browser. The selected type is inherited.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF, now this is working as expected in both cases, from site browser and webdav
