### ISSUE TITLE
Create an example custom field that uses a React component/App

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19414]
What we need is an example on how to write a custom field in dotCMS using another javascript framework, Vue or React.

The pattern would be to implement a component that runs in an iframe and takes and sets the custom field's value

1. Learn about how custom fields work in dotCMS:
https://dotcms.com/docs/latest/custom-field

2. Implement a React Component that either had a Markdown Editor or a different WYSIWYG which the user could use.

3. Write some rough documentation on how you did it.

**Comment by alfredo-dotcms** [comment]
# Implementing a Custom Field with a ReactJS app [Markdown Editor](https://github.com/uiwjs/react-markdown-editor)

## Steps:

1. Create the `Custom Field`
2. Create the `VTL file`
3. Create and build the `ReactJS app`
4. Upload the `ReactJS app`
5. Create a content based on the new `Custom Field`

### 1. Create the Custom Field
- A) Go to `Content Model` --> `Content Types` and add a new `Content`
- B) Add a `Custom Field` and set a `Name` (the Name must be unique). E.g. **customReactApp**
- C) In the `Value` field you need to set the path of the VTL file. E.g. 
`#dotParse("/application/vtl/custom-fields/iframeReactApp.vtl")`

### 2. Create the VTL file
- A) Go to `Site` --> `Browser` and create the `VTL` file based on the name and path set on step **1. C**
- B) Open the `VTL` and add the following code:
```
1   <iframe
2       id="reactAppIframe"
3       style="border:0"
4       src="http://localhost:8080/react-app/index.html"
5       height="500px"
6       width="100%"
7   >
8   </iframe>
9  
10  <script>
11  const hiddenFieldValue = document.getElementById("$field.getVelocityVarName()");
12  const iframe = document.getElementById("reactAppIframe");
13    
14  // Set data to the iframe to be loaded in the React App
15  iframe.dataset.value = document.getElementById("$field.getVelocityVarName()").value;
16
17  iframe.onload = () => {
18      iframe.contentWindow.document.addEventListener("custom-field-react-app",
19          (event) => {
20                
21              // Prevent default and stop propagation to avoid conflict issues
22              event.preventDefault();
23              event.stopPropagation();
24                
25              // Update value of hidden field related to the custom field
26              hiddenFieldValue.value = event.detail;
27          });
28      };
29  </script>
```
***Notes:** on `line 18` the `Custom Event` name must match with the name declared later on step 3. B.

### 3. Create and build the [ReactJS app](https://reactjs.org/)

- A) In your terminal create a ReactJS App:
```
npx create-react-app custom-field-react;
cd custom-field-react;
npm i --save-dev @uiw/react-markdown-editor;
```
- B) Set homepage path as relative in your App configuration. To do it, open `package.json` file and add the following:
```
"homepage": "./"
```
- Edit `App.js` to add the MarkdownEditor:
```
1   import React, { useState, useEffect } from 'react';
2   import MarkdownEditor from '@uiw/react-markdown-editor';
3
4   function App() {
5       const [data, setData] = useState('');
6
7       useEffect(() => {
8           setData(window.frameElement?.dataset?.value || '');
9       }, []);
10
11      function updateMarkdown(editor, data, value) {
12          const customEvent = new CustomEvent('custom-field-react-app', {
13              detail: value,
14              bubbles: true,
15              cancelable: true,
16          });
17          const elem = document.querySelector('.App');
18          elem.dispatchEvent(customEvent);
19      }
20
21      return (
22          <div className="App">
23              <MarkdownEditor
24                  value={data}
25                  height="70vh"
26                  onChange={updateMarkdown}
27              />
28          </div>
29      );
30  }
31
32  export default App;
```
***Notes:** on `line 12` the `Custom Event` name must match with the name declared on step 2. B.

- C) In your terminal build your ReactJS App:
```
 npm run build;
```

### 4. Upload the ReactJS app
- Grab all files and folders from the folder `build` and upload them into the DotCMS server.
***Notes:** The location must match the one defined on the VTL file on `line 4` on step 2. B

### 5. Create a content based on the new `Custom Field`
- A) Go to `Content` --> `Search` and add a new Custom Content created on step 1. B.

**Comment by wezell** [comment]
Repo found here:
https://github.com/dotcms-plugins/custom-field-react

**Comment by alfredo-dotcms** [comment]
# dotCMS Custom Field - React Markdown Editor   

This example shows to create a custom field that leverages prebuilt react components - in this case, the 
[SimpleMDE - Markdown Editor](https://github.com/sparksuite/simplemde-markdown-editor)

The patterns that this plugin uses to enable this react component can be used to incorporate any 3rd party javascript component (NG/Vue/React based) as a content control.  It uses a .vtl file to render the custom control in an iframe on the content editing screen and writes any changes made in the editor to the content's custom field value. 

## Steps:

1. Clone and build the `ReactJS app`
2. Upload the `ReactJS app` into dotCMS.
3. Create the `Custom Field`
4. Create a content based on the new `Custom Field`


### 1. Clone and build the [ReactJS app](https://reactjs.org/)

- A) In your terminal git clone the dotCMS Custom Field - React Markdown Editor App:
```
git clone https://github.com/dotcms-plugins/custom-field-react.git;
```

- B) Install dependencies
```
cd custom-field-react;
npm install;
```

- C) Build your ReactJS App:
```
 npm run build;
```

### 2. Upload the ReactJS app into dotCMS
- Grab all content from folder `build` and upload them into the DotCMS server, in path: 
```/react-app/```

### 3. Create the Custom Field
- Go to `Content Model` --> `Content Types` and add a new `Content`
- Add a `Custom Field` and set a `Name` (the Name must be unique). E.g. **customReactApp**
- In the `Value` field you need to set the path of the VTL file (uploaded on Step 2). E.g. 
`#dotParse("/react-app/customFieldReactApp.vtl")`

### 4. Create a content based on the new `Custom Field`
- A) Go to `Content` --> `Search` and add a new Custom Content

**Comment by alfredo-dotcms** [comment]
@wezell I just simplified the steps, please take a look and share some thoughts:
https://github.com/dotCMS/core/issues/19414#issuecomment-730029111

Repo with simplified folder structure & files:
https://github.com/dotcms-plugins/custom-field-react

**Comment by wezell** [comment]
Nice, thanks @alfredo-dotcms !
