### ISSUE TITLE
Update logic in StartupTasksExecutor to support calver

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19424]
When an upgrade task is run, we get the taskId as a substring of the task name: https://github.com/dotCMS/core/blob/91b79533377c6787a9a840dd79314cc33ce97df0/dotCMS/src/main/java/com/dotmarketing/startup/StartupTasksExecutor.java#L172 . This logic assumes the taskId is a 4-digit number. 

However, we will use different naming convention from now on: _"Our upgrade tasks will use calver naming convention as well, respecting the task creation date with the format `YYMMDD`. For instance, if I create an upgrade task today, the name would be `Task201009...` . Note: if more than one upgrade task is created the same day, a consecutive number will be used to guarantee sequentiality and uniqueness, e.g.: `Task201009...`  and `Task2010091...`"_ . As this change will break the existing logic, it should be updated to support the new naming convention.

On the other hand, the **Upgrade Task Convention**  section on the devwiki should be updated accordingly.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19462

**Comment by nollymar** [comment]
**Note to QA:** Please test an upgrade using any database

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF. Tested upgrading in the 4 DBs
