### ISSUE TITLE
Allow endpoint to search for inode and identifier

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19421]
When calling this endpoint `/api/v1/templates?filter=` the filter param could be a title, inode or identifier.
E.g:
* /api/v1/templates?filter=Destination
* /api/v1/templates?filter=9004-12

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19469

**Comment by erickgonzalez** [comment]
Tested and working as it should, this also works with the current template portlet using the Search box.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF
