### ISSUE TITLE
Webdav should use the db

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19428]
When listing files in folders, webdav has been relying on the content index to know if a file exists, has been written to, etc.  This causes a number of issues and forced us to make this change, which can slow uploading: #18626

We need to rely on the database when performing webdav operations.

**Comment by wezell** [comment]
Took care of this as well in the PR #19410

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19429

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, tested on release 20.11// Postgres // FF
