### ISSUE TITLE
Save Dimensions fields in Basic metadata (only for images)

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19434]
Basic metadata contains: 
- fileName
- modDate
- length
- SHA
- contentType

In the case of images, we should store "Dimensions" as part of the basic metadata. Currently, it is being stored only in the full metadata.

**Comment by wezell** [comment]
We also need a isImage() that stores the result from `UtilMethods.isImage(File)`

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/issues/19234
