### ISSUE TITLE
ES error starting release-20.10.1

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19431]
We are getting an ES error when you are starting the release-20.10.1 branch. 
Stack trace: https://gist.github.com/bryanboza/9234c7ebeff8d24c8546568cda9589ce

**To Reproduce**
1- Move to this branch 
2- Start a fresh instance 
3- Check the log file 

**Expected behavior**
We need to startup without problems 

**Desktop (please complete the following information):**
Tested on release-20.10.1 // postgres // FF

**Comment by erickgonzalez** [comment]
@hmoreras faced the same issue and was able to make it work increasing the resources of Docker.
