### ISSUE TITLE
Apps - UI: Add a Button type

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19439]
A button type should be supported to allow integration with third-party systems. For example: GitHub to subscribe to a repo.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1480

**Comment by nollymar** [comment]
Passed internal QA

<img width="1494" alt="Screen Shot 2020-10-28 at 11 34 19 AM" src="https://user-images.githubusercontent.com/8741395/97466827-89aeba00-1911-11eb-9fd7-5669373b427a.png">

**Comment by bryanboza** [comment]
Fixed, tested on release 20.11 // Postgres // FF
