### ISSUE TITLE
Use consistant ids for objects that have other unique keys

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19443]
When we create new objects in dotCMS we assign them random UUIDs.  This works fine for objects that do not have other primary keys, but for objects that have other unique keys, this causes unneeded conflicts.  If we used a repeatable hashing id for these objects, we could avoid many conflicts that we currently suffer from.

The key generation algo should take a list of Strings that it concatenates and then hashes to generate the id.  The resulting hash can be run the ShortyAPI.uuidIfy(String) to give us a uuid-like identifier (or we could just take the first 36 chars of the hash).  Each object that gets hashed should have a unique prefix pre-pended to insure uniqueness between object types.

## What to hash
- [x]  Content Types 
contentType:{baseType}:{velocity_var}
- [x]  Fields
field:{contentType_velocity_var}:{field_velocity_var}
- [ ]  Field Variables
fieldvariable:{contentType_velocity_var}:{field_velocity_var}:{field_variable_key}
- [x]  Personas
persona:{persona.keyTag}
- [x]  Categories
category:{categoryPath based on category_velocity_var_name path separated by >}
- [x]  Language
language:{languageKey}
- [x]  Folders
folder:{host.hostName}:{folder.path}
- [x]  Pages
pageAsset:{host.hostName}:{page.path}:{language}
- [x]  Files
fileAsset:{host.hostName}:{file.path}:{language}
- [x]  Hosts
host:{host.hostName}

**Comment by fabrizzio-dotCMS** [comment]
Not for QA: This will require testing Push-publishing all the above items
