### ISSUE TITLE
Mysql 8.0.21 can't create the dotcms DB for version 5.3.8

### ISSUE THREAD

**Issue by arrowwind** [dotCMS/core#19442]
Description: I am using Mysql 8.0.21 when I first run the dotCMS 5.3.8. The mysql can't be created. 
The sql can not execute. 

Modify:
For the file mysql.sql. The sql should change to below codes.

create table structure (
   inode varchar(36) not null,
   name varchar(255),
   description varchar(255),
   default_structure tinyint(1),
   review_interval varchar(255),
   reviewer_role varchar(255),
   page_detail varchar(36),
   structuretype integer,
   `system` tinyint(1), -- change here
   fixed bit not null,
   velocity_var_name varchar(255),

**Comment by wezell** [comment]
MySQL support has been deprecated and we recommend using Postgresql.  As it stands currently, we only support MySQL 5.x.

**Comment by arrowwind** [comment]
OK. Pls update the information in the webpage, such at https://www.dotcms.org/docs/latest/database-configuration#MySQL
