### ISSUE TITLE
URL maps which match the URL map pattern and content values fail with 404 on customer system

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19452]
**Describe the bug**

Customer upgraded from an earlier release to 5.3.8.  The system has 2 content types with URL Maps which worked fine before the upgrade, but which, after the upgrade, return 404 for the (valid) URL-mapped URLs.  The URL maps on these content types continue to return 404 even if the URL map patterns are changed.

If new content types are created, the URL maps on the new content types work without problems.

**To Reproduce**
1. Download the bundle containing the customer data
    * You can download the bundle from here (accessible to dotCMS users only): https://drive.google.com/file/d/1fiPystXp5YVSjn10Gk1GDzuCmPwAhlGz/view?usp=sharing
    * The bundle was created by adding all content of the 2 affected content types to the bundle and downloading it.
2. Start up a clean 5.3.x system.
3. Upload the bundle to your test system.
4. Hit one of the following URLs on the front-end:
    * /debrief/2014/Fall/
    * /debrief/2014/Fall/red-carpet-service
**Result:** The URLs return 404 (though the content matching those URLs exist, and those URLs work properly in the customer system that was not upgraded).

**Expected behavior**

The URLs above should take you to a valid URL-mapped page, since they match valid content for the URL Maps.

**References**

* Support Ticket: https://dotcms.zendesk.com/agent/tickets/102349

**Additional context**

* The URL maps of these 2 content types currently overlap.
    * However, the URL Maps for these content types fail even when they do not overlap at all.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19459

**Comment by dsilvam** [comment]
Passed Internal QA: The bundle did not include the detail page so one needed to be configured. Then hitting http://prod-duncan-upgrade.dotcmscloud.com:8080/debrief/2014/Fall/ returns the proper content. As a side note, if I try to reference the host by alias, it doesn't work, it tries to redirect to the login page many times.

**Comment by bryanboza** [comment]
Fixed, tested on relesase-20.11 // Postgres
