### ISSUE TITLE
Remove UserProxy from Hibernate

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19453]
We need to remove the legacy code used in the UserProxy from hibernate and all the classes that use it.

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/core/pull/19455
https://github.com/dotCMS/enterprise-2.x/pull/759

**Comment by nollymar** [comment]
**Note to QA:** Please test all operations related to users (add, edit, delete, list), including the user's additional info tab and reset password.

**Comment by nollymar** [comment]
**Additional PRs:** 
https://github.com/dotCMS/enterprise/pull/780/files
https://github.com/dotCMS/core/pull/20106

**Comment by fabrizzio-dotCMS** [comment]
Found couple of issues reported here: 
https://github.com/dotCMS/core/issues/20139
https://github.com/dotCMS/core/issues/20140

**Comment by fabrizzio-dotCMS** [comment]
The Reported bugs listed above are either fixed or non-applicable. Labeling it as Passed

**Comment by bryanboza** [comment]
@nollymar @fabrizzio-dotCMS .... I'm doing some regression over users and roles, but we have some list of the features that this change will affect?

**Comment by nollymar** [comment]
@bryanboza  you should perform testing over:
- User creation/edition/deletion
- PP users

**Comment by bryanboza** [comment]
Fixed, tested on release-21.04 // Postgres... After doing some regression over the mentioned areas in the comment, everything works as expected
