### ISSUE TITLE
Cannot add existing content from multiple sites to a container - 5.2x+

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19465]
As reported in https://dotcms.zendesk.com/agent/tickets/102679

When adding content to a container you are unable to select content from any other host besides the current one.

This only occurs with EXISTING content as you CAN create NEW content from the (+) Add Content window and it will be added to the container. 

**To Reproduce**
1. Create a CT with a Site/Folder field in order to add content to multiple sites.
2. Create contentlets of the Content Type on each site
3. Create a container for the Content Type
4. Create a template for the container
5. Create a New Page with the template/container
6. Click (+) to add content - only content from the current host will appear.
7. (Optional) Click (+) to add a NEW contentlet which WILL be added.

**Expected behavior**
Content select list should show allowable content from any host. 

**Screenshots**
NEW CONTENT TYPE
![image](https://user-images.githubusercontent.com/49727631/96495002-cd683c00-120c-11eb-99d0-1859d486fae9.png)

CONTENTLETS ON DIFFERENT HOSTS

on demo.dotcms.com:
![image](https://user-images.githubusercontent.com/49727631/96495112-f983bd00-120c-11eb-83b6-d93d5dd4bff0.png)

on 'other' site:
![image](https://user-images.githubusercontent.com/49727631/96495144-0bfdf680-120d-11eb-96a3-6982bcfbb8dc.png)

CONTAINER
![image](https://user-images.githubusercontent.com/49727631/96495206-26d06b00-120d-11eb-89d0-3ba197132a63.png)

PAGE
![image](https://user-images.githubusercontent.com/49727631/96495314-4cf60b00-120d-11eb-9b62-4422cf9088cb.png)

CONTENT SELECT
![image](https://user-images.githubusercontent.com/49727631/96495360-6008db00-120d-11eb-9ba6-3f5675ff6f06.png)

CONTENT ADDED
![image](https://user-images.githubusercontent.com/49727631/96495489-8f1f4c80-120d-11eb-8e5b-7ffe9071a15f.png)

ADD a NEW CONTENTLET AND SELECT OTHER SITE:
![image](https://user-images.githubusercontent.com/49727631/96495598-b83fdd00-120d-11eb-9842-ee999df2095f.png)

THE *NEW* CONTENTLET *WILL* APPEAR
![image](https://user-images.githubusercontent.com/49727631/96495707-cbeb4380-120d-11eb-8f1a-327d94e708ad.png)

**Comment by craigWagner99** [comment]
UPDATE:
If you add "USER SEARCHABLE" to the "SITE or FOLDER" field the contents _do_ appear:

![image](https://user-images.githubusercontent.com/49727631/96504766-c8aa8480-121a-11eb-810c-fba237e30760.png)

![image](https://user-images.githubusercontent.com/49727631/96504795-d4964680-121a-11eb-97fe-2d6255e4dfb4.png)

**Comment by john-thomas-dotcms** [comment]
So to clarify the issue:

If you do not have "User Searchable" set on the Site or Folder field of a content type, and a piece of content lives on a specific Site (rather than the System Host), it is not possible to add that content item to a Page on any Site other than the Site it lives on.
