### ISSUE TITLE
Remove all of the template struts code

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19476]
We need to remove all of the template struts code (struts-config, action directory, struts directory).

This needs to be done after we migrate the template portlet to a new angular portlet.

**Comment by fmontes** [comment]
Quick level. Not too deep. @erickgonzalez

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20017

**Comment by erickgonzalez** [comment]
**Note to QA:**

Please hard test on templates and pages.

I tested the following things:
* CRUD Templates
* CRUD Templates-Layouts
* CRUD Pages
* PP Templates
* PP Pages

**Comment by fmontes** [comment]
Pass but I found two things:

https://github.com/dotCMS/core/issues/20024
https://github.com/dotCMS/core/issues/20029

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF. New cards associated to this card
