### ISSUE TITLE
Unable to fix folder conflicts using the integrity checker

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19471]
We are getting a SQL error when you try to fix a folder conflict using the integrity checker 

Here the ST: https://gist.github.com/bryanboza/2a76364a79aad079c27805793a06ff2f

**To Reproduce**
1. Start both servers 
2. Configure your push environment 
3. Create a new folder and push it 
4. Delete the folder from the receiver side and create a new one with the same name 
5. Run the Integrity checker and fix the conflicts on the remote side 

**Expected behavior**
We need be able to fix the conflicts without problems 

**Desktop (please complete the following information):**
Both servers running Release-20.10.1 // Postgres

**Comment by bryanboza** [comment]
Fixed, tested on release-20.10.1 // Postgres // FF

**Comment by victoralfaro-dotcms** [comment]
Conflicts were fixed at the remote site
