### ISSUE TITLE
Get template owner and idate (create_date) from the identifier table

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19477]
- Modify get methods to make sure it's pulling the values from the identifier (also check the templateTransformer).
- Check that when it's saving a new template, saves the values on the identifier table.

To test:
1- Create a new template
2- Check the DB `select * from identifier where id = {ID}` the columns `owner` and `create_date` should be populated.
3- Call the endpoint `v1/templates?filter={ID}` the owner should be populated.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19552

**Comment by ivorpad** [comment]
`select * from identifier where id = {ID}`

<img width="1677" alt="Screen Shot 2020-11-16 at 7 14 34 PM" src="https://user-images.githubusercontent.com/52452/99291588-5a200d00-2840-11eb-8a45-4d3c7cf4b679.png">

Payload from `GET  v1/templates?filter={ID}`

<img width="1919" alt="Screen Shot 2020-11-16 at 7 16 28 PM" src="https://user-images.githubusercontent.com/52452/99291595-5be9d080-2840-11eb-9bf9-1876df35930c.png">

**Comment by bryanboza** [comment]
Fixed tested on release-21.01 // Postgres // FF
