### ISSUE TITLE
Implement Front End Login / Logout on starter site

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19484]
On the starter, we need to create a folder that is only available to intranet users.  

We then need to create a login page that allows a user to login as bill@dotcms.com.

Then if the user is logged in, we need to add a logout button to the top nav that will allow the user to logout.

 https://docs.google.com/document/d/1vNN0ca8L4iIVKqdokBQ2Z6C6jS-N6vG0mjBXnYLqu5g/edit

**Comment by fmontes** [comment]
We need to create a web component for login

**Comment by fmontes** [comment]
@ivorpad updated the web components to be able to import specific components

I think we should take this approach: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

Amazon Amplify provides a serie of components to all the auth process, login, register, etc... and they are customizable via: components props and css properties, we should be able to do the exact same thing.
