### ISSUE TITLE
Wrong defaults

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19486]
1.  bad login delay
By default we use a exponential delay for failed login requests - often times this grows.... exponentially and adds delays of minutes when a bad login occurs.  This is a killer for support where multiple people are trying the same failing login and it basically blocks the ui.
We should just wait 2 seconds for a failed login by default. 

2.  Clickstreams
Clickstreams are deprecated and should be removed. We need to turn off the scheduled jobs as well

2.  Linkchecker
Linkchecker has been deprecated and should be removed.

**Comment by wezell** [comment]
PR: #19487

**Comment by jcastro-dotcms** [comment]
Great! Are these new setting included in the configuration plugin/script we use when generating Cloud Instances?
