### ISSUE TITLE
If a field is marked unique, we should es map it as keyword

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19489]
When we checkin a contentlet that has a unique field that is stored as text we need to map it in elasticsearch as a keyword.
This is because when we validate a unique record, we do an elasticsearch query against the value of the field.  When the key contains a space or a dash, this unique lookup will fail.

To reproduce
1. Create a content type with a single unique field
2. Add one contentlet with the value of this field 'aaa-bbb-ccc'
3. Add one contentlet with the value of this field 'aaa-bbb-ddd'

**Comment by jcastro-dotcms** [comment]
For existing distros/customers, the current workaround is to add a Field Variable to the unique field with the following:
```
esCustomMapping --> {"type": "keyword"}
```

**Comment by wezell** [comment]
Also fix: #19458

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19628

**Comment by nollymar** [comment]
**Note to QA:** Please test with unique text fields and unique numeric fields as well

**Comment by fabrizzio-dotCMS** [comment]
![Screen Shot 2020-12-03 at 17 37 04](https://user-images.githubusercontent.com/37148755/101101456-42f65480-358e-11eb-817d-36d4dc5f23c5.png)
According to this. It is getting mapped as a keyword
The query used through Kibana to get such info
is has to have the following form
`{full_index_name_including_cluster_id}/_mapping/field/{field_id}`
e.g.
`cluster_b4776add5e.working_20201201164912/_mapping/field/tmycontenttype.title`

**Comment by bryanboza** [comment]
Fixed, tested on release 20.12 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.3.8.4 LTS release only. The 5.2.8.4 LTS release is several commits behind, which made the code back-port not possible.
