### ISSUE TITLE
Apps - UI: Create Export buttons on Site listing configuration page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#19490]
As an user, I need buttons to export the apps configuration in the Site listing configuration page
![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/60c898c0-311e-4dea-badc-34a45736281c)

I need 2 buttons:
A) A button that exports all existing configurations (disabled if none exist) --> located before to the `DELETE ALL` button
B) A button that export a single configuration --> located before to the `+` button of every existing site configuration

When clicked a dialog show open asking for a password.

Also in the main apps page
![image](https://user-images.githubusercontent.com/37185433/97510711-f2665880-194a-11eb-973e-64b63ebbbd5f.png)

I need:
A) A button that exports all existing configurations (disabled if none exist) --> located on the right, after the `SEARCH` input

Endpoint doc: https://authoring.dotcms.com/devwiki/apps-rest-api

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1498

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, now we have both buttons working as expected
