### ISSUE TITLE
Add Metadata button to SAML App

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19503]
We need to add a "Generate Metadata" button to our saml App.  When clicked, it should hit the endpoint in a new window of

`/api/v1/dotsaml/metadata/{HOST_ID}`

**Comment by wezell** [comment]
Dependent on this: #19490 19440

**Comment by nollymar** [comment]
**Passed internal QA:** The button was included and when clicked, a new window is opened and the metadata loaded
