### ISSUE TITLE
Container rewriter can use the wrong field

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19509]
In 5.3.9 we introduced the logic to force template using file based containers to use full pathing based on the 
`//hostname/application/container/{name}` pattern.  I believe this happens in the `drawedBody` and `body` fields of our existing containers.

In doing so we created a few processes that can break a site.  They do this by updating the path to an incorrect hostname value which makes the vtl inaccessible and there is no way to recover it.

- `Task05380ChangeContainerPathToAbsolute`
This job uses the wrong field `contentlet.title` to update the existing containers
- `UpdateContainersPathsJob`
I am not sure about this but saw it update the container paths as well.
- `HostCopyJob`

Additionally, the logic of "fall back to the default host if host is not found" is broken as well.  You can see this by intentionally breaking the hostname of a site with a default single host and you will see that the containers are no longer referenceable.

To reproduce:
1. Use a fresh starter site
2. On the host content type, move the alias field above the hostname
2. Rename the hostname from demo.dotcms.com to `test this hostname, please`
3. try to edit the default template
4. try to edit a page.

**Comment by wezell** [comment]
The code here needed some work - 
1. if the cache invalidations threw an exception, it would prevent the SQL from running (this happens if dotCMS cannot find the container files)
2. If the original hostname started with the new hostname, the code would just replace the matching substring of the host, not the entire hostname

**Comment by bryanboza** [comment]
Seems we still getting the error here, tested in a fresh instance of the release without do the upgrade and following the same steps I'm able to reproduce: 
![image](https://user-images.githubusercontent.com/2641437/97758584-cec71d80-1ac4-11eb-8d51-9b3cd54ef5f9.png)

Here the log error: https://gist.github.com/bryanboza/8e34643d184974a94b9e09b6cb03ad96

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/19528

**Comment by dsilvam** [comment]
Passed Internal QA: Case in description not happening. Value of `parseContainer` correctly replaced on db after changing the host name. Template able to being edited and page using it rendering without issues.

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now I'm unable to reproduce the problem, tested on release 20.10.1 // Postgres // FF
