### ISSUE TITLE
drag/drop a contentlet in Content -> Search triggers "Error You can't drop folders. Try again."

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19512]
**Describe the bug**
In Content -> Search, drag/drop any contentlet to produce "Error You can't drop folders. Try again."

**To Reproduce**
1. Go to Content -> Search
2. Click and drag any contentlet
3. UI responds "Drop File to Upload"
4. Drop the item within the dashed border 
5. "Error You can't drop folders. Try again."

**Expected behavior**
Contentlets probably should not be dragable on this screen

**Screenshots**
https://user-images.githubusercontent.com/628954/97617051-eaf28e00-19e2-11eb-9252-aea67fd5a711.gif

**Comment by alfredo-dotcms** [comment]
IMO the action done here: https://user-images.githubusercontent.com/628954/97617051-eaf28e00-19e2-11eb-9252-aea67fd5a711.gif

can not be avoided, that's a browsers behaviour (a string link is being dropped to the Assets drop zone), so the alert received validates that only valid assets can be dropped.

A fix will be done to update the error message showed, cuz right now it's misleading.

**Comment by nollymar** [comment]
PR Web-Components: https://github.com/dotCMS/dotcms-webcomponents/pull/44

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, the message was updated. Tested on master // Postgres // Chrome 
![image](https://user-images.githubusercontent.com/2641437/104350020-5075f700-54c9-11eb-93b0-47789f041d8a.png)
