### ISSUE TITLE
Apps - UI: Create Import button on Apps listing configuration page 

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#19517]
As a user I need a button that import configurations --> located on the right, after the SEARCH input and before the Export button

Once clicked a dialog should open to ask for the file to be imported and a password to decrypt the file

Endpoint doc: https://authoring.dotcms.com/devwiki/apps-rest-api

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1503

**Comment by fabrizzio-dotCMS** [comment]
Even though this already had passed internal QA I am sending it back. 
Per Will's request, we want the dialog that takes a password to do the export using the priming-ng component that measures the strength of the new password. 
https://primefaces.org/primeng/showcase/#/password

**Comment by alfredo-dotcms** [comment]
PR with the new password component: https://github.com/dotCMS/core-web/pull/1512/files

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Some improvements here: 

- When you click in the import button the focus in the new modal should be in the browse button and not in the password one, this because you have no selected file to know what is the password 

- After you get an error in the import process we should show the error message and then come back to the import window, right now we show the error and close the window 

- We need some translations on this portlet SC: https://www.screencast.com/t/rgspzFMTG2

**Comment by alfredo-dotcms** [comment]
> Some improvements here:
> 
A) * When you click in the import button the focus in the new modal should be in the browse button and not in the password one, this because you have no selected file to know what is the password
B) * After you get an error in the import process we should show the error message and then come back to the import window, right now we show the error and close the window
C) * We need some translations on this portlet SC: https://www.screencast.com/t/rgspzFMTG2

IMO:
"C"  is a bug, and "A" & "B" improvements

For "A" IMO should focus on the first DOM element, so maybe placing the File Input component first and then the password input below

**Comment by alfredo-dotcms** [comment]
Bug "C" weird, the code for the translation is there and should work, same as "Export" header label.
![image](https://user-images.githubusercontent.com/37185433/102121473-a2175d00-3e09-11eb-99e4-ff1e160cd06b.png)


core
https://github.com/dotCMS/core/blob/d15c5db8f08ed0148f9c33287cf1eefde11b45bc/dotCMS%2Fsrc%2Fmain%2Fwebapp%2FWEB-INF%2Fmessages%2FLanguage.properties#L3633

core-web
https://github.com/dotCMS/core-web/blob/680b17b905dd72edb2d7aeb83c1c3060662c81e4/src%2Fapp%2Fportlets%2Fdot-apps%2Fdot-apps-import-export-dialog%2Fdot-apps-import-export-dialog.component.ts#L101

**Comment by bryanboza** [comment]
According to the @alfredo-dotcms comment then I will pass this card, we need some work on the translation.properties file
