### ISSUE TITLE
JS error trying to download images from image editor

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19524]
If you try to use the download button in the image editor, we are getting a JS error on the browser and we are unable to download the image. 
![image](https://user-images.githubusercontent.com/2641437/97758063-b99dbf00-1ac3-11eb-8192-78e3b70e4b1f.png)

**To Reproduce**
- Start a dotcms instance 
- Apply for the license 
- Go to content search, select the image content type
- Edit some image and try to download from the editor 

**Expected behavior**
We need to be able to download the image without problems. 

**Desktop (please complete the following information):**
Tested on release-20.10.1

**Comment by john-thomas-dotcms** [comment]
This bug was reported by a customer via support ticket https://dotcms.zendesk.com/agent/tickets/102790

The customer is on 5.2.8, so it appears this problem is not new.

**Comment by erickgonzalez** [comment]
Reproduced in demo(22.10.1)

**Comment by wezell** [comment]
dupe: #22891
