### ISSUE TITLE
Rely on Elasticsearch index.max_result_window size to dictate the max limit of query results

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19527]
**Describe the bug**

Reproduced on demo.  Reported by customer: @https://dotcms.zendesk.com/agent/tickets/102760

When you run `$dotcontent.pull()`, if you attempt to display any content past the 10,000th result, no results are returned.

This is true even if you supply an offset and reasonable limit.  For example, the following will never return any results, even if you have more than 10,000 content items of the content type:

```
$dotcontent.pull( "+contentType:ctVarName", 9999, 10, "modDate desc" )
```

**To Reproduce**

1. Create a simple content type, with just a Title field.
    * User Searchable, Show in List, **_not_** Unique.
2. Create more than 10,000 items of the content type.  For example:
    * Create one content item
    * Export it
    * Open the CSV in a spreadsheet program
    * Copy the line 11,000 times.
    * Use a formula to set the Title so it increment for each row (e.g. `="Title "&(row(A2)-1)`)
    * Save the spreadsheet as CSV
    * Import the CSV
        * Note: Depending on where you're running, you may need to break the CSV into multiple files to be able to import it without the import timing out.
3. Working: Add a page that uses a content pull with a limit of 10 and an offset of 9990 to display all the results of the pull.  Example:
```
        <ul>
        #foreach( $item in $dotcontent.pull( "+contentType:SuperSimple", 9990, 10, "title asc" ) )
            <li>$item.title</li>
        #end
        </ul>
```
4. Not working: Change the offset from 9990 to 9991 and display the page again.
    * **Result:** No results are displayed.

**Expected behavior**

Contents past the 10,000th result should be returned.  A hard-coded maximum for the limit makes sense, but does not make sense for the offset.

**Comment by wezell** [comment]
Question - does the same query work from the API?  Or is the issue a problem with the `$dotcontent` tool?

**Comment by Ephys** [comment]
@wezell Hi, I opened the original ticket :) Yes the issue is with both the api and `$dotcontent`

**Comment by fabrizzio-dotCMS** [comment]
This PR https://github.com/dotCMS/core/pull/19696
Only solves the count limitation that we experienced against the 10K hard limit.
However, we're still limited by such restrictions.  

Currently, ES (7.x) offers a couple of alternatives to get elements passed the 10K limit 

1.  The scroll API.
2. and search_after queries. 

both methods aren't suitable for pagination and only offer the possibility to bring a batch of elements in a sequence. 
If you wanted to gain access to the second batch of elements forcefully you have to have requested the previous batch first.
 Making them useless for random page access.

if you really want to be able to access elements passed such limit. ES offers a way to configure such value. See the example below. But it is not recommended.

Taken from ES doc

**index.max_result_window**
_The maximum value of from + size for searches to this index. Defaults to 10000. Search requests take heap memory and time proportional to from + size and this limits that memory. See Scroll or Search After for a more efficient alternative to raising this._


```
curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_all/_settings' -d '{
  "index.max_result_window" : "100000"
}'
```

**Comment by john-thomas-dotcms** [comment]
So @fabrizzio-dotCMS
1. When customers need to access 50,000 or more items, what is the recommended method?
    * This number of content items is not uncommon, so we need to be able to offer a recommendation to them on how to access them - whether that's by changing configuration or something else.
2. Does it cause performance issues to just set the limit to 100,000 or higher, if the number of content items never gets that high?
    * If the only performance hit happens when accessing large numbers of content items - but not from just changing the configured limit - then it might make sense to increase the default value so far fewer customers will run into the limit (and then need to manually change it).

**Comment by fabrizzio-dotCMS** [comment]
Well, the pagination is still limited to 10K. This remains unsolved satisfactorily. We need to get a bit more creative here I think. for now, our current implementation allows accessing the whole number of items if we set a limit above 10K. 

So let's say you have 50000 elements.
if you do...

```
<ul>
        #foreach( $item in $dotcontent.pull( "+contentType:SuperSimple", 0, 10001, "title asc" ) )
            <li>$item.title</li>
        #end
</ul>
```
Setting the second param (limit) to any number above 10K breaks the limit. 

As far as I can tell in our logic... if you specify a limit above 10K.
We switch to a method called 

`contentFactory.indexSearchScroll(buffy.toString(), sortBy)`

that basically retrieves the whole thing.
So we can still gain access to the whole number of elements but we would be losing pagination capabilities.

**Comment by john-thomas-dotcms** [comment]
Thanks @fabrizzio-dotCMS.

**Comment by john-thomas-dotcms** [comment]
So it sounds like we should maybe go forward with what we have, but maybe put in a new card to look at how to be able to paginate past 100,000 items?

**Comment by fabrizzio-dotCMS** [comment]
As an additional note to QA  this PR 
https://github.com/dotCMS/core/issues/19527
Solves the count problem on the UI. However, the pagination problem remains unsolved. 
You can only navigate up to 10K items. passed that you'll see a warning message in the console 

```
17:20:11.827  WARN  business.ESContentFactoryImpl - ES Query: {"from":10080,"size":40,"timeout":"15000ms","query":{"match_all":{"boost":1.0}},"post_filter":{"query_string":{"query":"-contenttype:forms -contenttype:host +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:system_host) +languageid:1 +deleted:false +working:true","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"moddate_dotraw":{"order":"desc"}}],"track_total_hits":10000000}
17:20:11.827  WARN  business.ESContentFactoryImpl - Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10120]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]
17:20:11.827  WARN  business.ESContentFactoryImpl - ----------------------------------------------
```

**Comment by nollymar** [comment]
**Internal QA:** 

The pagination count shows the total of records (it was broken):

![Screen Shot 2021-01-04 at 5 22 42 PM](https://user-images.githubusercontent.com/8741395/103587092-7b9e8c00-4eb4-11eb-8fda-5420131eb2cd.png)

And as explained, the pagination breaks after 10000 records: 

when I reach this page: 

<img width="1669" alt="Screen Shot 2021-01-04 at 5 22 56 PM" src="https://user-images.githubusercontent.com/8741395/103587197-b6a0bf80-4eb4-11eb-8703-b1a7594afcc6.png">

I can't get further results: 

<img width="1677" alt="Screen Shot 2021-01-04 at 5 23 56 PM" src="https://user-images.githubusercontent.com/8741395/103587164-a4bf1c80-4eb4-11eb-874d-780d03fedbc2.png">

and the log shows this error: 

17:20:11.827  WARN  business.ESContentFactoryImpl - Elasticsearch error in index 'cluster_c7851e68ce.working_20210104163611'
17:20:11.827  WARN  business.ESContentFactoryImpl - ES Query: {"from":10080,"size":40,"timeout":"15000ms","query":{"match_all":{"boost":1.0}},"post_filter":{"query_string":{"query":"-contenttype:forms -contenttype:host +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:system_host) +languageid:1 +deleted:false +working:true","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"_source":{"includes":["inode","identifier"],"excludes":[]},"sort":[{"moddate_dotraw":{"order":"desc"}}],"track_total_hits":10000000}
17:20:11.827  WARN  business.ESContentFactoryImpl - Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10120]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]
17:20:11.827  WARN  business.ESContentFactoryImpl - ----------------------------------------------

**Comment by bryanboza** [comment]
Ok based on the discussion, seems that is a ES limitation. 

For now you need to configure a ES property as @fabrizzio-dotCMS said in his comment, which is not recommended but works for now. 

We need to doc it.

**Comment by fabrizzio-dotCMS** [comment]
since using the following command  raises security issues against Opendistro

```
curl -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_all/_settings' -d '{
  "index.max_result_window" : "100000"
}'
```

In order to accurately test please use a command like this to modify the max_result_window for a  particular given index 

```
PUT /cluster_43ce015992.sitesearch_20210105202055_ce4fa5db-4fc5-11eb-bb56-acde48001122/_settings 
{
  "index.max_result_window":"100000"  
}
```

You must provide the fully qualified name of your indices which can be extracted from the table indicies 

something like 

`SELECT * FROM indicies`

@bryanboza

**Comment by wezell** [comment]
In order to change this in dotCMS globally, you will need to add the property     
```
"index.max_result_window": 100000
```

to the `WEB-INF/classes/es-content-settings.json`

**Comment by bryanboza** [comment]
Tested after the recent changes and we still getting the same ES error after set this property, also tested with this query in a widget and neither works, we get the same error. 

```$dotcontent.pull( "+contentType:myTest", 10000, 1, "modDate desc" ) ```

Need some work here.

**Comment by wezell** [comment]
@bryanboza you need the changes and then need to run a reindex.  Did you do that?

**Comment by bryanboza** [comment]
Thanks @wezell seems that that's it, after run the full reindex now this works as expected
