### ISSUE TITLE
Credentials penalization is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19526]
When you type incorrect credentials on the login page, we should have time penalizations according to the number of wrong attempts, but right now if you type any wrong value we the system is showing the progress bar and never finish. 
![image](https://user-images.githubusercontent.com/2641437/97891661-b1789600-1cf4-11eb-9a6a-4cdb4365f797.png)

**To Reproduce**
- Start the dotcms instance 
- Type a wrong password and try to login 

**Expected behavior**
The time penalization needs to be exponential according to the number of attempts

**Desktop (please complete the following information):**
Tested on release-20.10.1 // Postgres // FF

**Comment by wezell** [comment]
Taken care of in: #19486
