### ISSUE TITLE
Visitor location dialog in rules too narrow

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19539]
**Describe the bug**
The visitor location map dialog is too narrow

**To Reproduce**
1. Go to rules
2. Create a rule
3. Add a condition and select "Visitors location"
4. Click on the button: "Show map"
5. See the error:

![Screen Shot 2020-11-03 at 16.00.11.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/9adaf56d-f4ca-48be-9387-f37ce866abf8)

**Expected behavior**
It should looks like this:

![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/66861d0e-7ca1-43bc-ae07-8c1b22d5314e)

## Acceptance Criteria

1. Make the map dialog wider
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1511

**Comment by erickgonzalez** [comment]
Tested working as it should, visitor map shows as expected

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now the map looks as expected
