### ISSUE TITLE
CSV Importer should use _dotraw for text key and unique fields

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19536]
If a user selects a key field while importing, the importer tool should use the _dotraw when performing the query to check if the field exists, etc.

Likewise for content types with unique fields, we should use _dotraw to validate a content's uniqueness 

This is a performance issue - without using the _dotraw, the importer can be slow and the uniqueness not return accurate results.

**Comment by wezell** [comment]
Related to this: #19489

**Comment by nollymar** [comment]
**Note to QA:** A query similar to this one:

`17:03:22.809  INFO  util.ImportUtil - buffy: +structureName:TestContentType +working:true +deleted:false +TestContentType.title_dotraw:"Nolly 2" +languageId:1`

should be logged when validations are run during the Import Content process. For this example the `title` field was selected as a key

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19628

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify that the query varies depending on the fields used to determine the uniqueness.
if a key field is selected then the query would be performed on top of the sha256 fields. if the Content-type has 3 fields marked as unique then the query would use the 3 fields to compose the query while selecting only non-unique fields would make the system execute a query on top of the draw fields. 
functional wise seems ok.

**Comment by bryanboza** [comment]
Fixed, tested on release 20.12 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.3.8.4 LTS release only. The 5.2.8.4 LTS release is several commits behind, which made the code back-port not possible.
