### ISSUE TITLE
Can't delete conditions in rules

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19538]
**Describe the bug**
If you have a rule with some conditions you can't delete them

**To Reproduce**
1. Go to rules
2. Click on add rule
3. Create a condition
4. Try to delete the condition

**Expected behavior**
You should be able to delete the conditions even if the condition is emtpy.

**Additional context**
Work in demo so we might broken in the NG10 upgrade.

## Acceptance Criteria

1. Allow users to delete conditions
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by hmoreras** [comment]
I possible delete rules until are valid on `release-20.11`

**Comment by fmontes** [comment]
No apply.
