### ISSUE TITLE
The `{languageIso}` static publishing config variable includes a dash (-) when no country code is configured

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19533]
**Describe the bug**

The `{languageIso}` static publishing configuration variable is replaced with the full ISO code of the language, which is composed of the language code, followed by a dash, followed by the country code - for example `en-US`.

However when there is no country code configured in the Language in dotCMS, the `{laguageIso}` variable still includes the dash - for example `en-`.

**To Reproduce**
1. Configure a Language which includes just the language code, but no country code.
2. Set up static publishing to an S3 endpoint, and in the configuration, include the following value:
    * `aws_bucket_name=dotcms-bucket-{hostname}-{languageIso}`
3. Push content to the static endpoint.
4. View the folders in the S3 bucket.
    * **Result:** The bucket name is set to `dotcms-bucket-dotcms.com-en-` (with a dash at the end).

**Expected behavior**

The `{languageIso}` variable should not display a dash if no country code is included in the Language configuration.

**Additional context**

Related to support ticket: https://dotcms.zendesk.com/agent/tickets/102774

**Comment by wezell** [comment]
I believe the `langauge.toString()` method should be used to build the bucket name
