### ISSUE TITLE
Problems with the apps portlet in the community edition 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19537]
As a EE feature when you are in the community edition we need to show a message of a required license in case you open the apps portlet using the community edition, but this is not working as expected. 

In the release branch, we are showing a permissions error 
![image](https://user-images.githubusercontent.com/2641437/98026740-35a04b80-1dd1-11eb-8999-1d41e3fb51cc.png)

Also, In the master branch, we are redirecting to the dashboard portlet 

**To Reproduce**
- Start a dotcms instance 
- Without apply a license try to navigate to the apps portlet 

**Expected behavior**
We need to be able to show the required license message without problems as in all the EE features 

**Desktop (please complete the following information):**
Tested on release-20.10.1 // Postgres // FF

**Comment by fabrizzio-dotCMS** [comment]
I also verified in master and the background screen doesn't even load. it gets redirected to the dashboard.
This was working not long ago.

**Comment by nollymar** [comment]
I couldn't reproduce it.

<img width="1673" alt="Screen Shot 2021-05-04 at 12 02 20 PM" src="https://user-images.githubusercontent.com/8741395/117041520-981acb80-acd0-11eb-9082-aa2326c080bf.png">


<img width="1677" alt="Screen Shot 2021-05-04 at 12 02 01 PM" src="https://user-images.githubusercontent.com/8741395/117041594-a4068d80-acd0-11eb-8049-26f26547556c.png">

**Comment by bryanboza** [comment]
Seems this was fixed with another card, I will close this one. Tested on release 21-05
