### ISSUE TITLE
Layout editor coming from edit page broken

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19540]
**Describe the bug**
The layout editor loads broken (all grid mess up) when you came from edit content

**To Reproduce**
1. Go to edit a page
2. Click on "Layout"
3. See the grid is all broken
4. If you refresh it gets fixed.

**Expected behavior**
It should load correctly

## Acceptance Criteria
1. Fix layour editor on load
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
This is the same issue as: https://github.com/dotCMS/core/issues/18830

**Comment by erickgonzalez** [comment]
Tested and Working as it should, layout loads correctly.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.11 // Postgres // FF
