### ISSUE TITLE
Apps: add the ability to disable | enable the new Button type

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#19543]
We're thinking that maybe the new supported button type can be enabled|disabled  based on a property until the values on the secrets are persisted. It means:
- when a secret configuration is created, the button type will always be disabled.
- when a secret configuration is edited, the button type will always be enabled.

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core-web/pull/1509/files

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, tested on release-21.01 // Postgres // FF
