### ISSUE TITLE
Fix the logout on SESSION_DESTROYED event from websocket

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19542]
**Describe the bug**
With the new SAML feature we change the way we logout from DotCMS. Instead of hitting the endpoint we just jave to link to: `/dotAdmin/logout`

We have to do the same thing, redirect to `/dotAdmin/logout` in the `LoginService`, specifically [here](https://github.com/dotCMS/core-web/blob/master/projects/dotcms-js/src/lib/core/login.service.ts#L62).

## Acceptance Criteria
1. Update the callback in websocket event to redirect to `/dotAdmin/logout`
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Tested on demo site
