### ISSUE TITLE
Deleting a user is not replacing the owner on identifier table

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19555]
When you delete a user you need to select another user to replace all the references, since we add a new column on the identifier table `owner` we need to replace also this value.

To reproduce:
1. Create a new user and grant CMS Admin role.
2. Create content as a new user.
3. Check the DB `select * from identifier where id = {ID}`, and see the `owner` value is the new user.
4. As the admin user, delete the new user and select `Admin2` as the user to replace.
5. Wait until the delete finishes.
6. Check the DB `select * from identifier where id = {ID}`, and see the `owner` value should be `Admin2`.

Note: this is making this test fail https://raw.githack.com/dotCMS/test-results/issue-19477/projects/core/current/integration/postgres/reports/html/classes/com.dotmarketing.business.UserAPITest.html#delete since now it pulls the `owner` value from the identifier instead of the inode for templates.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19563

**Comment by bryanboza** [comment]
Fixed, tested on release-20.12 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Code changes in this ticket are not applicable for LTS dotCMS 5.2.8.4 and 5.3.8.4 releases.
