### ISSUE TITLE
Minor: UI error after use the field variables tab editing fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19556]
When you try to edit some field on content types and navigate to the field variables tab, if you close the window and then try to edit the same field again, we are leaving the selected tab field variables, but we are showing the properties tab. 

![image](https://user-images.githubusercontent.com/2641437/98288079-eb070680-1f6b-11eb-86b3-80ac68e2088e.png)

Here the video how to reproduce: 
https://www.screencast.com/t/1PtaN4WTXiTS

**Expected behavior**
We need to reset this selection every time you edit some field

**Desktop (please complete the following information):**
Tested on release-20.11

**Comment by fmontes** [comment]
Still happening.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1586

**Comment by fmontes** [comment]
This is showing like double ink (or border)


https://user-images.githubusercontent.com/751424/108101818-65f0ba80-704d-11eb-9f99-7d844cad99c9.mov

**Comment by hmoreras** [comment]
feddback PR: https://github.com/dotCMS/core-web/pull/1589

**Comment by bryanboza** [comment]
Fixed, tested on release 21.03 // Postgres // Safari
