### ISSUE TITLE
Content Type Detail page is not add in bundle

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#19558]
When Push Publish a Content Type with a detail page, the page is not add into the bundle as dependencies.

Step to reproduce:

1. Create a new page.
2. Create a new Content Type, and add the new page as detail page.
3. Publish the Content Type with all it's dependencies
4. No errors is reproted but the detail page is not send to the receiver

**Comment by dsilvam** [comment]
Needs work: The detail page gets pushed as a dependency but when trying to open it on the receiver it throws an error both in the UI and in the logs. 

Error in UI: 
This URL does not exist.
The page you are trying to access does not exist.

Error in the logs:
```
16:43:52.378  WARN  mapper.ResourceNotFoundExceptionMapper - Cannot parse velocity file : /$dotTheme.templatePath
org.apache.velocity.exception.ResourceNotFoundException: Cannot parse velocity file : /$dotTheme.templatePath

Caused by: org.apache.velocity.exception.ResourceNotFoundException: cannot find resource:/$dotTheme.templatePath
	at com.dotcms.rendering.velocity.services.IncludeLoader.writeObject(IncludeLoader.java:94) ~[dotcms_master_4d9b602.jar:?]
	at com.dotcms.rendering.velocity.services.DotResourceLoader.getResourceStream(DotResourceLoader.java:72) ~[dotcms_master_4d9b602.jar:?]
	... 116 more
Caused by: org.apache.velocity.exception.ResourceNotFoundException: cannot find resource:/$dotTheme.templatePath
```

**Comment by dsilvam** [comment]
Passed Internal QA: Detail page successfully  sent as a dependency of the content type and able to edit it via site-browser.

**Comment by dsilvam** [comment]
Passing QA on this one.

**Comment by wezell** [comment]
The detail page should not be a dependency - it causes too much dependency recursion.  We should instead add a new filter called `includeContentDetailPage` and default it to false.  If the filter does not specify a value for it, it should be false as well.

**Comment by bryanboza** [comment]
This issue was reverted on release-20.11.1.... Need rework and assign to a new release
