### ISSUE TITLE
[logging] : General logging improvements

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19566]
Found when working on Support tickets.
Reproducible as of dotCMS 5.3.8, and up.

Simple logging improvements that add clarification on some error situations we ran into.

**Expected behavior**
Improved logging messages.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19568

**Comment by fabrizzio-dotCMS** [comment]
Passing it to QA
I didn't test each and every logging change introduced here 
But I did review All of them and they all look good to me.

**Comment by bryanboza** [comment]
Fixed
