### ISSUE TITLE
Add a "Download" button to the Log Files tab in the Maintenance portlet

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19560]
**Is your feature request related to a problem? Please describe.**

Many customers - including all dotCMS Cloud customers, and users of our own auth and prod servers - do not have direct access to the server to be able to download the dotCMS log files.

We have a "Log Files" tab in the Maintenance portlet, but it only allows tailing logs, so doesn't allow you to look at anything that happened more than a few minutes ago.

Our own support staff run into this literally every single day.  We need an easier way for customers (and our own team) to pull down full log files, without needing to ask their IT staff (or ours) to retrieve those files for them.

**Describe the solution you'd like**

Add a "Download" button to the "Log Files" tab.  The tab already has all the code which allows users to select the log files and open them - it just needs a download button which can fetch the entire file to download it.

Note that, since we may not be able to generate a URL to the log files (due to permissions on the server folders), one way to do this might be to create a temporary file with the contents of the requested log file, and then provide a link to download the temporary file.

**Describe alternatives you've considered**

I suppose we could do the same thing with a REST API, but that seems like it would be alot of work when the Log Files tab already has 99% of the code needed to be able to do this.

**Additional context**

This lack of access to the log files becomes even more pronounced on docker instances, where access to the log files requires not just access to the server, but also knowledge of special docker commands to retrieve the files.

So the more we and our customers move to containerized deployments, the more pronounced the need for a direct download of the log files is going to become.

Need to be tested against a docker instance.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19830

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.3.8.4 LTS release only. The 5.2.8.4 LTS release is several commits behind, which made the code back-port not possible.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
