### ISSUE TITLE
Always PP items that were explicitly added 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19571]
When doing PP we always should PP the items that were explicitly `Add to the Bundle`, regardless of the push history of the item (Unless the filter excludes it explicitly).

It does not make sense to manually select something to push, push it and nothing happens with a success message. 

Steps to Reproduce:
1- Configure PP env
2- Create a new content in the sender env
3- PP to the receiver env, using the `Only Selected Items` Filter.
4- Delete it, directly, on the receiver env.
5- PP the content again (without making any new changes).

It should be pushed again but since it hasn't changed since the last push it does not push.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19584

**Comment by bryanboza** [comment]
Fixed, tested on release 20.12 // Postgres // FF. This config on both environments
