### ISSUE TITLE
Add Endpoint to delete a layout from a role

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19581]
We need an endpoint that removes a layout from a role.  The role can either be a group role or a user role.  

Endpoint to remove a toolgroup: **/api/v1/toolgroups/{toolgroupId}/_removefromcurrentuser**
Endpoint to add a toolgroup: **/api/v1/toolgroups/{toolgroupId}/_addtocurrentuser**

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19680

**Comment by bryanboza** [comment]
Fixed, new card added in order to validate this information from UI.
