### ISSUE TITLE
Update Starter and Empty Starter to have an initial Tool Group "Welcome"

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19582]

**Comment by nollymar** [comment]
Versions `empty_20210305` and `20210305` of the starter were generated to include the Welcome page

**Comment by bryanboza** [comment]
Fixed, now we have this portlet enabled as default in both starters

**Comment by bryanboza** [comment]
After this change now the "don't show this again" checkbox is not working, we are unable to hide this portlet

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/20092

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now it is working as expected
