### ISSUE TITLE
Text area fields on Widgets do not update after saving if you delete the contents of the field

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19595]
As reported in: https://dotcms.zendesk.com/agent/tickets/102947

Discovered on version v5.3.8, recreated in current Demo - v20.10.1

**Describe the bug**
Text area fields on Widgets do not update after saving if you delete the contents of the field.

**To Reproduce**
1. Create a new widget Content Type with a Text Area field
2. Create a contentlet of the widget and enter a value in the text area.
3. Save/Publish/Close
4. Reopen the contentlet, delete the contents of the Text Area field
3. Save/Publish/Close
5. Reopen.

**Expected behavior**
The Text Area field should be empty since the value was deleted. 

**Actual behavior**
The deleted contents remain.

**Flushing cache and reindexing do not remedy the issue**

**TEXT AREA HAS VALUE**
![image](https://user-images.githubusercontent.com/49727631/99449422-6316ea00-28e5-11eb-9084-21f7edce03f3.png)

**DELETE AND SAVE**
![image](https://user-images.githubusercontent.com/49727631/99449608-70cc6f80-28e5-11eb-80ee-3ec42da71a15.png)

**CLOSE**
![image](https://user-images.githubusercontent.com/49727631/99449870-922d5b80-28e5-11eb-9369-7f4f96299f13.png)

**REOPEN - VALUE HAS RETURNED**
![image](https://user-images.githubusercontent.com/49727631/99449887-98233c80-28e5-11eb-9961-17eb9a5d6f7c.png)

**Comment by wezell** [comment]
Workaround, toggle the editor and then save.  It will work then.

![clear-text-area](https://user-images.githubusercontent.com/934364/99462079-f27dc680-2900-11eb-9fff-cfecb197e5ae.gif)

**Comment by erickgonzalez** [comment]
Reproduced in demo(22.10.1)
