### ISSUE TITLE
Create a Getting Starter Portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19590]
![Template Listing Copy 2](https://user-images.githubusercontent.com/751424/99317322-7c5b6000-282b-11eb-9e4e-7b3ffe8ac234.png)

**Comment by alfredo-dotcms** [comment]
core-web branch: `issue-19590-Create-starter-portlet`

**Comment by alfredo-dotcms** [comment]
CORE: PR https://github.com/dotCMS/core/pull/19640/files

**Comment by alfredo-dotcms** [comment]
CORE-WEB: https://github.com/dotCMS/core-web/pull/1520/files

**Comment by alfredo-dotcms** [comment]
![screencapture-localhost-8080-dotAdmin-2020-12-02-08_23_27](https://user-images.githubusercontent.com/37185433/100884995-c1140780-3477-11eb-9ed7-ceae14e94118.png)

![screencapture-localhost-8080-dotAdmin-2020-12-02-08_22_52](https://user-images.githubusercontent.com/37185433/100885008-c6715200-3477-11eb-90ce-2121e105fb45.png)

**Comment by alfredo-dotcms** [comment]
Url to see it: http://localhost:8080/dotAdmin/#/starter
