### ISSUE TITLE
Can't login when you have a corrupt SAML config

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19606]
If you have a corrupt configuration of your SAML secret, we are getting an error and we are unable to login in the app

Log: https://gist.github.com/bryanboza/9cf8e503a93c1cee4cd78ef35b070050

**Desktop (please complete the following information):**
Tested on release-20.11 // Postgres

**Comment by camkinney** [comment]
I encountered this issue and resolved it by appending ?native=true to my dotAdmin url.

This section in the Docs is available for more information: https://www.dotcms.com/docs/latest/saml-authentication#ForceNative
