### ISSUE TITLE
Unable to start an instance using MSSQL as db

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19613]
When you try to start an instance using this db,  we are getting a FATAL error and we are unable to start the server

Here the error: https://gist.github.com/bryanboza/a0a02b4b6b6fe1789779431715110d77

**Expected behavior**
We need be able to start instances in all the supported databases without problems 

**Desktop (please complete the following information):**
Tested on release 20.11 // MSSQL 2018

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19619

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify that the latest changes pushed to `ImportStarterUtil` on release-20.11 fix the problems starting up  under MS-SQL

**Comment by bryanboza** [comment]
Fixed, tested on MSSQL 2018 and now we are able to start with the full starter without problems, tested on release-20.11

**Comment by nollymar** [comment]
Note to QA: this change needs to be tested in all databases

**Comment by bryanboza** [comment]
Tested on MSSQL_2018 and works fine.... 
Tested on MySQL_5.7 works fine...
Tested on PSQL 11 works fine... 
Tested by @fabrizzio-dotCMS in Oracle and works as expected.

**Comment by fabrizzio-dotCMS** [comment]
I verified importing starter `20201119` on Oracle and it looks all good.

**Comment by bryanboza** [comment]
Fixed...
