### ISSUE TITLE
Version 20?

### ISSUE THREAD

**Issue by JohnRiv** [dotCMS/core#19631]
Why have versions numbers `20.10.1` and `20.11` been released this month?
How do they compare with `5.3.8` & `5.3.9`?

**Comment by jdotcms** [comment]
hi @JohnRiv 

DotCMS switched to CalVer (Calendar Version) versioning, so 20.10 (October) and 20.11 (Nov). 
I guess on the previous versioning they could be 5.4 and 5.4.1, but now we use CalVer

Here you can see the change logs: https://dotcms.com/docs/latest/changelogs

Best,
J

**Comment by JohnRiv** [comment]
👍  thanks for the info!

**Comment by wezell** [comment]
cool.  Also, you can see the blog on the change here:

 https://dotcms.com/blog/post/moving-to-calendar-based-version-numbers
