### ISSUE TITLE
Content API not returning name or title in dotAsset

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19639]
**Describe the bug**
When you request a content by id using `/api/content/id/{IDENTIFIER}` the name and title came back a `'unkown'`.

**To Reproduce**
1. Drag and drop a file to the content search
2. Request that content using the url `/api/content/id/{IDENTIFIER}` 
3. Check the name and title properties

<img width="1684" alt="Screen Shot 2020-12-01 at 12 45 33" src="https://user-images.githubusercontent.com/751424/100783716-bef86d00-33d3-11eb-8892-31979dc1b37d.png">

**Expected behavior**
Should come back with the filename.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.12 // Postgres // FF 
![image](https://user-images.githubusercontent.com/2641437/101212265-0c781280-363e-11eb-95fa-9e19eb510266.png)

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.3.8.4 LTS release only. The 5.2.8.4 LTS release is several commits behind, which made the code back-port not possible.
