### ISSUE TITLE
Push Publish performance 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19646]
Need to rely on Glowroot (or other tools) to determine the bottlenecks and then work on the strategy to handle those.

**Comment by freddyucv** [comment]
PR

core: https://github.com/dotCMS/core/pull/19930
ee:https://github.com/dotCMS/enterprise/pull/773
testing: https://github.com/dotCMS/core/pull/19873

**Comment by wezell** [comment]
Please take this change into consideration - it will need to be updated and use the shared XStream instance

https://github.com/dotCMS/enterprise/blob/master/src/main/java/com/dotcms/enterprise/publishing/remote/handler/ContentHandler.java#L1161-L1184

**Comment by freddyucv** [comment]
PR:
ee: https://github.com/dotCMS/enterprise/pull/785
core: https://github.com/dotCMS/core/pull/20173

**Comment by dsilvam** [comment]
let's make sure static publish works

**Comment by dsilvam** [comment]
PR to fix static publish: https://github.com/dotCMS/core/pull/20296

**Comment by dsilvam** [comment]
First results: Downloading a bundle with the whole site, on a provided custom data-set, took 38 minutes. However it required increasing the maximum heap size to 4Gb (-Xmx4G) for the process to finish. It didn't seem to finish with our shipped value of 1GB.

**Comment by dsilvam** [comment]
Heap space consumption when downloading bundle with entire site (custom data set). 

<img width="1354" alt="Screen Shot 2021-04-29 at 18 02 25" src="https://user-images.githubusercontent.com/1576794/116628671-401d4700-a915-11eb-9201-bc5ce4293e5a.png">

Heap memory consumption passed 1gb during the execution of the ContentBundler and never got lower than that.

**Comment by freddyucv** [comment]
After these PRs:

https://github.com/dotCMS/enterprise/pull/796
https://github.com/dotCMS/core/pull/20345

we got a better memory use

<img width="1039" alt="last_1Gb" src="https://user-images.githubusercontent.com/10408015/117198096-d1713b00-ada5-11eb-98d4-f056e4eefe78.png">

**Comment by freddyucv** [comment]
After performance change we get a OutOfMemoryEroor with huge file, I tested with a 1Gb file

**Comment by dsilvam** [comment]
PR for big files and OOM: https://github.com/dotCMS/core/pull/20392

**Comment by freddyucv** [comment]
**Note QA**: 
- Test with huge file, I mean add into a bundle a 1 Gb size File Asset 
- Also test with a -Xmx equals to 1 Gb

**Comment by dsilvam** [comment]
Needs work: 

Testing with custom dataset

Timemachine

Multiple occurrances of error: 
12:00:56.904  ERROR bundlers.FileAssetBundler - cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn : Unable to write file
com.dotcms.publishing.DotBundleException: cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn

which is because of missing assets 

Two different errors in the URLMapBundler while running Timemachine which doesn't seem to prevent it to work, but worth taking a look. 

Sitesearch

11:58:20.102  INFO  ajax.SiteSearchAjaxAction - Job Started : User:dotcms.org.1; Date: 2021-05-18 16:58:20; Job Identifier: sitesearch

Multiple occurrances of error: 
12:00:56.904  ERROR bundlers.FileAssetBundler - cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn : Unable to write file
com.dotcms.publishing.DotBundleException: cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn

Same errors in the URLMapBundler as when running Timemachine

Sending back to @frodriguez to take a look. Errors already shared.

**Comment by dsilvam** [comment]
Passing internal QA.

**QA Download Bundle performance - Testing with custom dataset and 1 GB heap size** 

* **Download bundle whole site**  
  Resulting size: tar.gz 11,399,414,704 bytes (12.08 GB on disk) for 517,944 items
  Time taken: 31 minutes 

* **Downloading bundle with big file (1GB)** 
  Finished without OOM

* **PP bundle  with big file (1GB)**
  Finished without OOM


**Regression tests - Testing with custom dataset**

**Timemachine**

Multiple occurrances of error: 

```12:00:56.904  ERROR bundlers.FileAssetBundler - cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn : Unable to write file com.dotcms.publishing.DotBundleException: cant get host for main.bundle.js reason Source file does not exist/Users/danielsilva/Documents/NodeA/assets/2/1/2184e8c5-ca57-40ee-8eca-f1bbeef09348/fileAsset/.ukn```
, which is because of missing assets 

Two different _known errors_ in the URLMapBundler while running Timemachine which doesn't prevent it to work. 

**Sitesearch**
Same error because of missing assets as in Timemachine
Same _known errors_ in the URLMapBundler as when running Timemachine
Index created and searching working

**Push publish**
Working under different scenarios: 
Working single page / sigle content
Pages with live/working versions 
Content types with relationships 
Not working when copying demo site and publishing to a receiver with starter. Existing error on 21.04 https://gist.githubusercontent.com/dsilvam/2cab30f5319c958083995ae202232f08/raw/55902db9db4d60d1491c6ea9c1a21ee0ddd32a1c/gistfile1.txt

**Static file & Static publish to S3**
Working. Same two different _known errors_ happening. Got some pushing full folders but worked as individual files. @swicken-dotcms also helped testing pushing S3 bucket with good results.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF
