### ISSUE TITLE
Imported Vanity URLs are applied to all Sites

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19649]
**Describe the bug**
Vanity URL 301/302 redirects imported from CSV file are active on all sites - not just on the site identified in the CSV file.
Additionally, these imported Vanity URLs are displayed in the backend for all sites, not just the site to which they belong.

**To Reproduce**
1. Create and active two empty sites
2. Create a single Vanity URL 301/302 redirect on each site
for example:
`site-a.dotcms.com/url-a` redirects -> /redirect-a
`site-b.dotcms.com/url-b` redirects -> /redirect-b
3. Confirm that the redirect url on site A is ignored for site B and vice-versa
for example, 
`site-a.dotcms.com/url-b` should not redirect
`site-b.dotcms.com/url-b` should redirect
4. Export the Vanity URLs as a CSV file
5. Edit the CSV file to create two new Vanity URL redirects - one for each site
The CSV file will look something like
```
title,site,uri,action,forwardTo,order
site-b-redirect-import,af478ae6-9972-469d-867c-d9da1c9774fd,/url-b-import,302,/redirect-b-import,0
site-a-redirect-import,da2134a7-aadb-4713-a16a-faf1dae1d128,/url-a-import,302,/redirect-a-import,0
```
6. Import the Vanity URLs from the edited CSV file
7. Observe that both new redirect URLs will be redirect on both sites
for example
`site-a.dotcms.com/url-b-import` should not redirect but it does
8. In the backend Marketing -> Vanity URLs, both new Vanity URLs will be visible no matter which site is selected. 

**Expected behavior**
Imported Vanity URL redirects should respect the Site ID specified in the CSV file

**Screenshots**
`site-b-redirect-import` should not be visible on `site-a.dotcms.com`
<img width="801" alt="Screen Shot 2020-12-03 at 2 29 22 AM" src="https://user-images.githubusercontent.com/628954/100990954-b4db8900-350f-11eb-9288-3f4031289b78.png">
<img width="968" alt="Screen Shot 2020-12-03 at 2 32 28 AM" src="https://user-images.githubusercontent.com/628954/100991060-d0469400-350f-11eb-8758-78fe64f81735.png">

**Attachment**
Bundle containing two empty sites and two Vanity URL redirects. The sites need to be activated, then these Vanity URLs can be exported to begin at step 4.
[vanityurl-01ERKZMEVM8F0K02NWGYCY9SSZ.tar.gz](https://github.com/dotCMS/core/files/5635126/vanityurl-01ERKZMEVM8F0K02NWGYCY9SSZ.tar.gz)

**Comment by yolabingo** [comment]
cloud support issue https://dotcms.zendesk.com/agent/tickets/103024

**Comment by Xander-Steinmann** [comment]
There is a workaround: after manually editing the vanity URL + save/publish it works as expected.
