### ISSUE TITLE
Allow TinyMCE props to be set system wide

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19651]
Most of our customer want to customize the tinyMCE implementation that we ship with in dotCMS.  We added the ability to customize that using the field variable `tinymceprops` - yay for us!   It would also be nice to have a default configuration file that could be edited that would affect all the wysiwyg fields without having to go to each content type and add the appropiate field variable.  It should work like this:

1. look for the file `/application/wysiwyg/tinymceprops.vtl` on the host the user is on.  if it exists, use it
2. if not, look for the file `/application/wysiwyg/tinymceprops.vtl` on the default the user is on.  if it exists, use it
3. If no `tinymceprops.vtl` file is found, just maintain current behavior.

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
