### ISSUE TITLE
Need to update the ES image path in the  dotStartup.sh file 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19653]
After the last changes, we have moved the ES images,  then we need to update this in our `dotStartup.sh` file to avoid problems starting up the dotCMS instance

Old path: `gcr.io/cicd-246518/es-open-distro:1.3.0`
New path: `dotcms/es-open-distro:1.3.0`

**Expected behavior**
We need to be able to start an instance without problems 

**Desktop (please complete the following information):**
Tested on release-20.11.1

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/tomcat/pull/16

**Comment by nollymar** [comment]
Note to QA: To test this change, it is required to delete your `dot_opendistro` container and your `gcr.io/cicd-246518/es-open-distro:1.3.0` image. Then, just run a fresh install using `dotStartup.sh`

**Comment by fabrizzio-dotCMS** [comment]
I removed my open_distro container and image gcr.io/cicd-246518/es-open-distro:1.3.0
Then removed my tomcat and started with a fresh install. it all worked just fine. I'm passing it.

**Comment by bryanboza** [comment]
Fixed, tested on release-20.12 and now this works as expected
