### ISSUE TITLE
GraphQL: Allow filtering of related content items returned

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19652]
**Is your feature request related to a problem? Please describe.**

Customers would like to be able to retrieve only a subset of related content items when retrieving related content using GraphQL.

Support ticket: https://dotcms.zendesk.com/agent/tickets/102950

**Describe the solution you'd like**

Allow a filter to be supplied with a relationship field, to limit which related contents are returned.  Ideally, the filter should take a Lucene query which provides the criteria that a related content item must match for that content item to be returned.

**Describe alternatives you've considered**

The only real workaround is to retrieve all of the related content items, and then perform filtering in the client application to only display the desired ones.  This obviously both increases the amount of work needed in the client application, and increases the network load required (especially if the number of requests from client applications is high).

**Additional context**

The $dotcontent.pullRelatedField() velocity method allows specification of a filter on the related content items returned (via the `condition` parameter): https://dotcms.com/docs/latest/pull-and-display-related-content#ContentTool.  The enhancement requested here would allow customers to apply the same type of filter to GraphQL queries.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19685

**Comment by freddyucv** [comment]
It is not work

**Comment by victoralfaro-dotcms** [comment]
Running test locally using postman.
![image](https://user-images.githubusercontent.com/64026161/103776905-beb44880-4ff5-11eb-8035-1c23e04dd37f.png)

**Comment by bryanboza** [comment]
Fixed, the provides tests runs locally without problems
