### ISSUE TITLE
Language, Device & Persona labels not hidden when viewport is narrow --> Site Browser -> Edit Page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#19656]
**Describe the bug**
In Edit Page, when the browser's viewport is small, the Language, Device and Persona dropdowns buttons should hide the labels

**To Reproduce**
1. Go to 'Edit Page'
2. Open any page
3. Make your browser smaller

**Expected behavior**
The Language, Device and Persona dropdowns buttons should hide the labels

**Screenshots**
![image](https://user-images.githubusercontent.com/37185433/101095908-4e448280-3584-11eb-8df6-4b270b67b47a.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1529

**Comment by nollymar** [comment]
Passed internal QA. Now it works as expected:

<img width="933" alt="Screen Shot 2020-12-22 at 1 49 26 PM" src="https://user-images.githubusercontent.com/8741395/102922776-91e02d00-445c-11eb-99df-25c40a53535e.png">

**Comment by bryanboza** [comment]
Fixed, now we collapse those ones when you made the browser smaller 
![image](https://user-images.githubusercontent.com/2641437/104515738-d02ebf00-55b8-11eb-8beb-7e6338ae378a.png)
