### ISSUE TITLE
Add history tab

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19668]
In the template detail screen we need to add "History" table, right now we are only showing the "Push history".

**Comment by fmontes** [comment]
This needs to add the "History" table, right now we are only showing the "Push history"

**Comment by fmontes** [comment]
After our meeting:

1. Update the delete function to use the new endpoint 
2. Remove bring back using "param"
3. Edit the template by inode (@erickgonzalez will work on and endpoint for this)

**Comment by erickgonzalez** [comment]
PR core web: https://github.com/dotCMS/core-web/pull/1545

**Comment by fmontes** [comment]
1. Edit a version
2. Go back to history tab
3. Click in another version
4. Doesn't load

**Comment by bryanboza** [comment]
Fixed tested as part of the main card
