### ISSUE TITLE
Velocity mailerTool issue with utf-8 encodings

### ISSUE THREAD

**Issue by TheDepths** [dotCMS/core#19666]
dEC Customer here advised to log an issue in gitHub.  Logged via support ticket ##103043 (4.3.3).

Through some testing we've noticed that the dotCMS mailtool has an encoding issue when HTML format is set to "true". We've logged a ticket for this before, but were told it was our exchange server because dotCMS support tested and it worked with gmail. However, I've since discovered that gmail actually converts all emails to UTF-8 encoding so it only appears to work with Google correcting this issue in transit. I've also been able to show that this issue only happens when HTML is set to true. It otherwise works fine with our exchange server. I would also like to point out that we receive html email from a variety of service providers without issue (HTML being the de-facto standard these days).

**To Reproduce**  In any browser:
Character issue/html: #set($error = $mailer.sendEmail('someemail@someaddress.com','somereplyto@someaddress.com','hello, from dotCMS! â, ê, î, ô, û ...', 'hello, from dotCMS! â, ê, î, ô, û ...', true))

Works/text: #set($error = $mailer.sendEmail('someemail@someaddress.com','somereplyto@someaddress.com','hello, from dotCMS! â, ê, î, ô, û ...', 'hello, from dotCMS! â, ê, î, ô, û ...', false))

Outlook and some other clients displays diamond question marks in place of the characters.

**Additional context**
It appears as though many users that experiencing this are attempting to use the setContent() method vs. the preferred setText().

See the top answer here: https://stackoverflow.com/questions/15044027/utf-8-charset-doesnt-work-with-javax-mail (https://stackoverflow.com/questions/15044027/utf-8-charset-doesnt-work-with-javax-mail)

**Comment by fmontes** [comment]
@wezell Do you have a PR for this?

**Comment by wezell** [comment]
fixed in: #19856

**Comment by bryanboza** [comment]
Fixed, tested on release-21.04 and now it works as expected
![image](https://user-images.githubusercontent.com/2641437/115590001-ba9ef480-a28d-11eb-9b74-6fa973fd446d.png)
