### ISSUE TITLE
date range filter in Content Search yields exception/500 when trying to select Workflow Action

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19677]
**Describe the bug**
When filtering by a Date/DateTime range in Content -> Search which returns more than 40 (more than one page of) results, "Select All Content(s)" -> "Available Workflow Actions" silently fails, rather than opening the Workflow modal.

**To Reproduce**
1. create a Content Type with a user-searchable Date or DateTime field - for example "Birthday" with a "Date" field
2. create more than 40 contentlets of this type
3. In Content -> Search, specify `Type = Birthday` to show the Date filter field
4. filter by a date range that includes more than 40 contentlets `[YYYYMMDD TO YYYYMMDD]`
5. select all contentlets by clicking `All 40 content items on this Page are selected. Select all N contents`
6. click `AVAILABLE WORKFLOW ACTIONS` - it will silently fail, not opening the modal
7. the ajax POST to `api/v1/workflow/contentlet/actions/bulk` will return a 500
8. dotcms.log will log an exception

**Expected behavior**
workflow action should apply to the date-range-filtered contentlets  

**Screenshots**
video  https://drive.google.com/file/d/1JsGhxOvTmKvtYY7cRJpwIgTD8R7finKz/view?usp=sharing

**Additional context**
bundle of "birthday" contentlets used to test [date-range-test-01ES1Q6AYEAJ76XVC57PQ7KG45.tar.gz](https://github.com/dotCMS/core/files/5661512/date-range-test-01ES1Q6AYEAJ76XVC57PQ7KG45.tar.gz)
HAR file which includes POST data and headers (had to add .txt extension) [date-range-error_demo.dotcms.com.har.txt](https://github.com/dotCMS/core/files/5661513/date-range-error_demo.dotcms.com.har.txt)
dotcms.log [dotcms-exception-date-range.log](https://github.com/dotCMS/core/files/5661531/dotcms-exception-date-range.log)

**Comment by yolabingo** [comment]
cloud support ticket https://dotcms.zendesk.com/agent/tickets/103083

**Comment by yolabingo** [comment]
Note this similar issue when selecting date ranges, the trying to Export rather than select a Workflow https://github.com/dotCMS/core/issues/18128

**Comment by erickgonzalez** [comment]
PR for EE: https://github.com/dotCMS/enterprise/pull/805
PR core: https://github.com/dotCMS/core/pull/20483

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
