### ISSUE TITLE
UI: Scroll problems in the content search when you have tag fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19688]
We are losing some fields in the content search filter when you have a tag field and add multiple tags to filter 

Here a video how to reproduce: https://www.screencast.com/t/MHaReBAkzxf

**To Reproduce**
- Login as admin
- Create a new content type with two fields (F1: Text | User searchable and F2:Tag | User searchable )
- Add a new piece of content 
- Go to content search, select the new content type and try to filter the results  adding more than one tag 

**Expected behavior**
We need add an scroll bar here, or be able to expand the fields to the blank space above 

**Desktop (please complete the following information):**
Tested on release-20.12 // Postgres // FF

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19719/files

**Comment by nollymar** [comment]
**Passed Internal QA:** 

<img width="1674" alt="Screen Shot 2021-01-04 at 5 56 49 PM" src="https://user-images.githubusercontent.com/8741395/103587962-47c46600-4eb6-11eb-8035-20d1b4a08a67.png">

**Comment by bryanboza** [comment]
Fixed, now we hace an scroll bar here. Tested on release-21.02 // Postgres // Chrome
