### ISSUE TITLE
Logout window needs translation 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19693]
When you are using a dotCMS instance in some specific language and you logout, we are showing the logout window and messages in English, since the server is in other language, we need to translate this and keep the language until you change it again 
![image](https://user-images.githubusercontent.com/2641437/101943807-62563880-3bb1-11eb-885d-e9eec0e8da11.png)

- In the login window change the language to german 
- Login 
- Now logout and make sure we keep that language according your configuration 

**Expected behavior**
We need to keep the language until you change it again 

**Desktop (please complete the following information):**
Tested on release 20.12 // Postgres // FF

**Comment by erickgonzalez** [comment]
Reproduced in demo(22.10.1)
