### ISSUE TITLE
Add the "don't show again" checkbox

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19701]
Add the "Don't show again" checkbox.

![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/8968869e-559f-4263-a781-1a9cbd6333ea)

When checked it should hit the endpoint from this issue: https://github.com/dotCMS/core/issues/19581

There is already a branch in core with that branch `issue-19581-remove-layout-from-user`

We have 2 endpoint, one to remove (checked) and one to add (unchecked).

To add the portlet, you do a `PUT /api/v1/toolgroups/gettingstarted/_addtocurrentuser` to remove it you `DELETE /api/v1/toolgroups/gettingstarted/_removefromcurrentuser`

**Comment by bryanboza** [comment]
Fixed, this functionality will be tested as part of the portlet
