### ISSUE TITLE
sitesearch_audit object cannot save large exclude string

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19706]
**Describe the bug**
Customer wants to exclude a lot of pages from the site search which sit on the root folder of the site, so they need lengthy Include or Exclude patterns for their Job Schedulers. Eventually this will trigger an exception when `sitesearch_audit.path` exceeds the database varchar 500 characters limit.

**To Reproduce**
1. Site Search -> Job Scheduler -> Paths -> Include or Exclude 
2. Enter a string of more than 500 characters "/admin, /dotAdmin, /static/*,..."
3. Click Schedule
4. check dotcms log:
```
ERROR job.SiteSearchJobImpl: can't save audit data 
com.dotmarketing.exception.DotDataException: ERROR: value too long for type character varying(500){ 
"SQL": ["insert into sitesearch_audit (job_id,job_name,fire_date,incremental,start_date,end_date,host_list,all_hosts, lang_list,path,path_include,files_count,pages_count,urlmaps_count,index_name) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"]
```
**Expected behavior**
either the site search index completes without error, or UI validates the string length when creating the Job Scheduler

**Comment by yolabingo** [comment]
cloud support ticket https://dotcms.zendesk.com/agent/tickets/103147

**Comment by john-thomas-dotcms** [comment]
Currently, the only known workaround for this is to manually run a SQL query to increase the size of the DB column (allowing a longer exclude string) - as suggested by @nollymar.

* It might make sense to increase the size of the column by default.
* It also might make sense to find another way to exclude items from the index.

**Comment by yolabingo** [comment]
related feature request https://github.com/dotCMS/core/issues/19707
