### ISSUE TITLE
add another mechanism to include/exclude content from site search indexes

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19707]
**Is your feature request related to a problem? Please describe.**
Customer has a lot of content in the site root and uses lengthy Include/Exclude patterns in Site Search -> Job Scheduler. Their exact request is:
> We want to exclude a lot of pages from the site search but they sit on the root folder of the site. So the best we can do is to add each url to the exclude. Unfortunately this is breaking this api. Is there any workaround? Is there a better way to exclude a page than to add it to the exclude?
> 
> It would be great if there was a property or feature in DotCMS on the pageAsset content type that we could use to toggle on and off inclusion into the site search index. That way we don't have to whitelist every single URL.

Issue https://github.com/dotCMS/core/issues/19706 addresses "breaking the api"...

**Describe the solution you'd like**
A mechanism to influence Site Search inclusion/exclusion beyond "path"

**Describe alternatives you've considered**
- property on a PageAsset content type (or any content type?)
- using Tags or Categories?

**Comment by wezell** [comment]
This could be implemented in logic the template.vtl, something like the pseudo code below

```
#if($request.getAttribute("User-Agent")=="DOTCMS-SITESEARCH" && !$dotPageContent.searchMe )
   #stop 
#end
```

**Comment by jcastro-dotcms** [comment]
New customer report: [104580](https://dotcms.zendesk.com/agent/tickets/104580)
