### ISSUE TITLE
Make XStream initialization static

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19715]
We have a few places in code where we instantiate a new XStream instance which turns out to be a somewhat expensive operation.  We need to just instantiate it once and then use it repeatedly.
This is from the `PublishAuditAPIImpl`:

![Screen Shot 2020-12-16 at 2 54 58 PM](https://user-images.githubusercontent.com/934364/102399608-d6784e00-3fae-11eb-8c55-838e979d6df4.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/19768
