### ISSUE TITLE
Lazy load buttons for edit contentlets in the page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19711]
Improve usability and performance in edit mode

**Comment by fmontes** [comment]
What I did:

https://user-images.githubusercontent.com/751424/104471322-524ec180-5580-11eb-9510-c88369b033bc.mp4

**Comment by erickgonzalez** [comment]
Tested changes:

- [x] white space to iframe of the page view
- [x] remove cancel button
- [x] improve drag and drop (shows element, blue highlight, scroll)

**Comment by bryanboza** [comment]
Fixed, excellent change, now it looks better and fells more efficient

**Comment by fmontes** [comment]
When you edit a VTL from the edit mode the edit vtl button disappear.

**Comment by fmontes** [comment]
Is an on BE bug: https://github.com/dotCMS/core/issues/19871

**Comment by erickgonzalez** [comment]
Not relevant to 21.06 LTS
