### ISSUE TITLE
Blank screen showing when close pick template type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19713]
**Describe the bug**
When close the dialog of pick design or advanced we end up in a blank screen

**To Reproduce**
1. Go to template list
2. Click on + button
3. Close the dialog

**Expected behavior**
It should redirect to template listing

## Acceptance Criteria

1. Redirect to template listing when closed new dialog
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
