### ISSUE TITLE
Only 10 parent related contents retrieved when editing a child content

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#19723]
Reported via Support: [103067](https://dotcms.zendesk.com/agent/tickets/103067)
Reproducible in dotCMS 20.11

Legacy relationships only list 10 related parent items in the relationship tab when editing a child contentlet.
This issue doesn't impact new relationship fields, unless this configuration property is set to `false`:
```
GET_RELATED_CONTENT_FROM_DB=false
```

**To Reproduce**
1. Set this configuration property to `false`:
 ```
GET_RELATED_CONTENT_FROM_DB=false
```
2. Create a many-to-many relationship between 2 content types. Create a relationship field pointing to children items on the parent content type and another relationship field pointing to parent items on the child content type.
3. Add more than 10 contentlets for the parent content type.
4. Add a new contentlet for the child content type.
5. Relate more than 10 parent contentlets on the child contentlet and save the child contentlet.
6. Flush the relationship cache.
7. Edit again the child contentlet: only 10 parent contentlets are listed for the relationship field.

**Expected behavior**
If there are more than 10 related parent contentlets, they should be listed when editing a child contentlet.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 / Postgres // FF
