### ISSUE TITLE
Nodes from a cluster can return different oldest nodes to switch over to a new index

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#19738]
Reported via Support: [103105](https://dotcms.zendesk.com/agent/tickets/103105)
Reproducible in dotCMS 20.11

When all records in a full reindex have been added to the new index, dotCMS will switch over to the new created index. In a cluster, every node is running its own reindex thread, that will detect that there are no more records to include in the new index, and then the switch over can be done. In order to avoid multiple nodes doing the index switch over at the same time, dotCMS delegates the switch over to the oldest node in the cluster. All the nodes should return the same node as the oldest, so all the nodes will skip the logic to do the switch over, with the exception of the one node that returns itself as the oldest one. This method has the logic to return the oldest node from the cluster:

https://github.com/dotCMS/core/blob/7ea4c467b701f3b9ab65f5ef2e99fa8a32b73bfd/dotCMS/src/main/java/com/dotcms/cluster/business/ServerAPIImpl.java#L160-L188

This method returns the oldest node, using these steps:
1) If there's already a cached server id as the oldest one, it returns the cached value.
2) If it's the first time a full reindex runs after the node started, and there isn't a cached server id yet, all the server directories (under /assets/server path) are compared and sorted using the directory modification date. The directory with oldest modification date is returned as the id for the oldest server.

The issue is that modification date for server directories can be changed when hitting 'Network tab' (that will cause a test file to be added under the server directories). Since the modification date is changed, different nodes can be returned as the oldest, causing unexpected behavior for the switch over to the new index. 

**To Reproduce**
1. Create a new dotCMS cluster with 2 or more nodes.
2. Start the cluster nodes.
3. Check that the first node started (oldest) has generated server id greater than the second node. For example:
    - Node 1:
        - Id 'e4c6361b-d878-4c90-8911-1bf71bcf98c4'
        - Server directory 'assets/server/e4c6361b-d878-4c90-8911-1bf71bcf98c4'
        - Server directory creation/modification timestamp: 2020-12-26 08:41:39.243087555
    - Node 2:
        - Id '26ea8723-3a9d-4c22-9a44-d7bc051d007c'
        - Directory 'assets/server/26ea8723-3a9d-4c22-9a44-d7bc051d007c'
        - Server directory creation/modification timestamp: 2020-12-26 08:42:31.903386062

You might have to repeat this step until the first node that starts has a greater id than the second one (since the server id is auto-generated it can be return different results every time).
4. Run a full reindex. The switch over to the new index will be done by the first node (oldest). The second node will delegate the switch over to the first node and will cache the first node id as the oldest one. You will see this log message for the second node when it delegates the switch over to the first node:
```
[26/12/20 09:08:58:578 CST]  INFO business.ContentletIndexAPIImpl: fullReindexSwitchover: Letting server [e4c6361b-d878-4c90-8911-1bf71bcf98c4] make the switch. My id : [26ea8723-3a9d-4c22-9a44-d7bc051d007c]
```
On the other hand, you will see this log message for the first node when it does the switch over to the new index:
```
[26/12/20 09:08:59:978 CST]  INFO business.ContentletIndexAPIImpl: -------------------------------
[26/12/20 09:08:59:978 CST]  INFO business.ContentletIndexAPIImpl: Reindex took        : 32.978s
[26/12/20 09:08:59:978 CST]  INFO business.ContentletIndexAPIImpl: Switching Server Id : e4c6361b-d878-4c90-8911-1bf71bcf98c4
[26/12/20 09:08:59:978 CST]  INFO business.ContentletIndexAPIImpl: Old indicies        : [working_20201225084413,live_20201225084413]
[26/12/20 09:08:59:979 CST]  INFO business.ContentletIndexAPIImpl: New indicies        : [working_20201225090827,live_20201225090827]
[26/12/20 09:08:59:979 CST]  INFO business.ContentletIndexAPIImpl: -------------------------------
```
5. Hit the 'Network tab', that will cause modification timestamp be changed for server directories.
6. Check the modification file for server directories, verify that the second node has the oldest timestamp now:
     - Node 1:
         - Directory 'assets/server/e4c6361b-d878-4c90-8911-1bf71bcf98c4'
         - Modification timestamp: 2020-12-26 09:11:24.224352560
     - Node 2:
         - Directory 'assets/server/26ea8723-3a9d-4c22-9a44-d7bc051d007c'
         - Modification timestamp: 2020-12-26 09:11:24.058703444

    The modification date change is caused because a test file is created and removed in every server directory when the cluster health is checked after hitting the 'Network tab'. Test files are removed in order of served ids, that explains why the second node (with minor id) has an older modification date than the first node (with greater id). Here is located the code that removes test files under server directories:

https://github.com/dotCMS/core/blob/7ea4c467b701f3b9ab65f5ef2e99fa8a32b73bfd/dotCMS/src/main/java/com/dotcms/rest/ClusterResource.java#L174-L186

7. Restart the first node. The second node still has cached the first node id as the oldest one, but the first node has been restarted and will not have a server id cached as the oldest node now.
8. Run a new full reindex. After all records have been included to the new index, the switch over won't happen: the nodes will be stuck without neither of the nodes activating the new index and doing the switch over. Node 1 will be stuck delegating the switch over to the second node and you will see this repeated message in the log:
```
[26/12/20 09:13:41:194 CST]  INFO business.ContentletIndexAPIImpl: Running Reindex Switchover
[26/12/20 09:13:41:196 CST]  INFO business.ContentletIndexAPIImpl: fullReindexSwitchover: Letting server [26ea8723-3a9d-4c22-9a44-d7bc051d007c] make the switch. My id : [e4c6361b-d878-4c90-8911-1bf71bcf98c4]
```
Meanwhile, node 2 will be stuck delegating the switch over to the first node and you will see this repeated message in the log:
```
[26/12/20 09:13:37:184 CST]  INFO business.ContentletIndexAPIImpl: Running Reindex Switchover
[26/12/20 09:13:37:187 CST]  INFO business.ContentletIndexAPIImpl: fullReindexSwitchover: Letting server [e4c6361b-d878-4c90-8911-1bf71bcf98c4] make the switch. My id : [26ea8723-3a9d-4c22-9a44-d7bc051d007c]
```

**Expected behavior**
Oldest node should be always returned as the first node started from the cluster, no matter that 'Network tab' changes modification date for the server directories under 'assets/server' path. When doing the switch over to a new index, all nodes should delegate the switch over to the same node (oldest).

**Screenshots**
Switch over got stuck, neither of the nodes do the switch over the new index:

![image](https://user-images.githubusercontent.com/2894221/103173921-a7ba6d00-4823-11eb-9991-0fa1d6e0bef5.png)

**Comment by erickgonzalez** [comment]
Tested, even though the first node has a greater id the switchover went smoothly.

PR: https://github.com/dotCMS/core/pull/19859
PR EE: https://github.com/dotCMS/enterprise/pull/771

**Comment by jcastro-dotcms** [comment]
Excluding code changes from LTS releases for the amount of extra code required to implement actual fix is dangerously high.

**Comment by bryanboza** [comment]
Fixed, testing following the provided steps and works as expected.
