### ISSUE TITLE
[Improvement] Be able to ignore RuleBundler

### ISSUE THREAD

**Issue by oarriet** [dotCMS/core#19739]
From client: https://dotcms.zendesk.com/agent/tickets/103231

The client implemented this: 

> I'm considering is it possible to build a plugin which will just exclude RuleBundler in com/dotcms/publisher/pusher/PushPublisher.java, saying at com/dotcms/publisher/pusher/PushPublisher.java:293 I modify like below:

```
if (Config.getBooleanProperty("PUSH_PUBLISHING_RULES_OVERWRITE", true)) {
	list.add(RuleBundler.class);
}
```

The client is looking for the possibility to be part of future releases. We can discuss here.

**Comment by erickgonzalez** [comment]
You can ignore Rules using the PP Filters. https://dotcms.com/docs/latest/push-publishing-filters
