### ISSUE TITLE
Export Content doesn't work when all languages are selected

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19734]
The option to export multilingual content doesn't download any file.

Reproducible on version 20.11. 

**Steps to reproduce:** 
1. Using a fresh install, go to Content -> Products. 
2. Select All languages.
3. Click in the header checkbox to select all pieces of content. You should see this message: "All 40 content item(s) on this Page are selected. Select all 69 content(s)." 
4. Try to export content. This message should display "Exporting contents of type 'Product' to CSV file. Please wait...", the page is refreshed and no file is downloaded.

**Comment by ian-b-cooper** [comment]
Customer requested support: https://dotcms.zendesk.com/agent/tickets/106787

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
