### ISSUE TITLE
Using web pages navigation in edit mode then editing page properties takes you back to the original page you opened

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#19737]
Steps to reproduce.
1. Open a page in edit mode
2. navigate to another page using the websites nav
3. edit the page's properties
4. hit save or save and publish
5. close the properties window 

Results: you are taken back to the page you originally opened in edit mode

**Comment by ivorpad** [comment]
A fix has been released and we managed to improve the UX removing unnecessary reloads when no properties were saved. So, two things need to be tested

Test  # 1

1. Go to another route in the website within the iframe
2. Open properties
3. The page should stay in the page you originally opened in edit mode

Test # 2

1. Open a page in edit mode
2. Open 'Properties' and close without saving.
3. It should not reload the page and the route in the iframe should remain.

**Comment by erickgonzalez** [comment]
Tested and working as it should.

**Comment by bryanboza** [comment]
Fixed, tested and now works as the @ivorpad comment
