### ISSUE TITLE
[ViewTool] The sql Tool is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19746]
Found when working on Support ticket: [103236](https://dotcms.zendesk.com/agent/tickets/103236)
Reproducible as of dotCMS 5.1.6, up to latest master.

No results are being returned after enabling the `sql` ViewTool. The page displays empty results, and error messages are logged to the dotcms.log file.

**To Reproduce**
1. Set up a local dotCMS instance. Enable SQL access as explained here: https://dotcms.com/docs/latest/executing-a-sql-query#Requirements
2. Create a dummy HTML Page, and add a Simple Widget with the code shown in this section: https://dotcms.com/docs/latest/executing-a-sql-query#ExampleQueryEmployee
3. Save the Widget, and go back to the test page.
4. The page shows up without errors. However, the section containing the SQL code shows no results, and the following is logged:
```
09:51:58.115  WARN  viewtools.SQLResultsViewTool - Scripting called with errorjava.lang.NullPointerException @ url:GET//demo.dotcms.com/api/v1/page/render/test | lang:1 | ip:127.0.0.1 | Admin:true | start:01-04-2021 08:39:33 CST  ref:http://localhost:8080/dotAdmin/  ?language_id=1 >/EDIT_MODE/be8fa1a3-bbcb-4801-b935-117c2abd9762/694805c6-8f07-467f-a434-0da04a93e9e5.fields
09:51:58.115  ERROR viewtools.SQLResultsViewTool - Content Editor cannot execute the SQLResultsViewTool becase it does not have enough permissions to do it @ url:GET//demo.dotcms.com/api/v1/page/render/test | lang:1 | ip:127.0.0.1 | Admin:true | start:01-04-2021 08:39:33 CST  ref:http://localhost:8080/dotAdmin/  ?language_id=1 >/EDIT_MODE/be8fa1a3-bbcb-4801-b935-117c2abd9762/694805c6-8f07-467f-a434-0da04a93e9e5.fields
0
```

**Expected behavior**
When enabled and used properly, the SQL ViewTool must work without problems

**Additional context**
After debugging the error, we found that the offending line:
https://github.com/dotCMS/core/blob/ea32540ea1eebca68ab1f2a130d7875a8315b682/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/SQLResultsViewTool.java#L231
Is expecting a different value for the `fieldResourceName` variable. It's unclear why or when this changed, but the current format of the `fieldResourceName` variable does not match the structure that the code is expecting.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19761

**Comment by erickgonzalez** [comment]
We need to update our doc since now the DB is defined in the **db.properties** file instead of the **context.xml** and the examples are not working, here I post some examples that work:

Updated example 1 using **Product** Content-Type (b/c **Employee** Content-Type no longer exists):
```
<h2>Calling the SQL Tool from a Content:</h2>
    <br/>
    #set($query = "SELECT distinct identifier,text1,text3,text4,text6 FROM Contentlet WHERE structure_inode='a1661fbc-9e84-4c00-bd62-76d633170da3'") 
    <strong>Query: </strong> $!{query}
    <br/>
    <br/>
    #set($resultsList = $sql.getSQLResults("default", "$!{query}", 0, 25))

    <table border="1">
        <tr>
            <th><h3>Product Number</h3></th>
            <th><h3>Title</h3></th>
            <th><h3>Retail Price</h3></th>
            <th><h3>Sale Price</h3></th>
        </tr>
        #foreach($product in $resultsList)
            <tr>
            <td>$!{product.text4}</td>
            <td>$!{product.text1}</td>
            <td>$!{product.text3}</td>
            <td>$!{product.text6}</td>
            </tr>
        #end
    </table>
```

Updated example 2 (b/c the Content-Type name was changed):
```
<h2>Calling the SQL Tool from a Content:</h2>
<br/>
#set($query = "select * from identifier where id in (select identifier from contentlet where structure_inode in (select inode from structure where structuretype = 5 AND velocity_var_name = 'htmlpageasset'))")

<b>Query:</b> $!{query}

#set($resultsList = $sql.getSQLResults("default", "$!{query}", 0, 4))
<br/>
<br/>
#if($resultsList.size() > 0)
    #foreach ($res in $resultsList)
        <li><b>ID:</b> $res.get("id")</li>
        <ul>
            <li><b>Parent Path:</b> $res.get("parent_path")</li>
            <li><b>Asset Name:</b> $res.get("asset_name")</li>
            <li><b>Asset Type:</b> $res.get("asset_type")</li>
        </ul>
    #end
    <br />
#end
```

Updated example 3 (same reason as above):
```
<h2>Calling getParameterizedSQLResults Tool from a Content:</h2>
<br/>

#set($paramsList = $contents.getEmptyList())
#set($temp = $paramsList.add(5))
#set($temp = $paramsList.add("htmlpageasset"))

#set($query = "select * from identifier where id in (select identifier from contentlet where structure_inode in (select inode from structure where structuretype = ? AND velocity_var_name = ?))")

<b>Query:</b> $!{query}
<br/>
<b>Params:</b> $!{paramsList}
<br/>
<br/>

#set($resultsList = $sql.getParameterizedSQLResults("default", "$!query", $paramsList, 0, 4))

#if($resultsList.size() > 0)
    #foreach ($res in $resultsList)
        <ul>
            <li><b>ID:</b> $res.get("id")</li>
            <li><b>Parent Path:</b> $res.get("parent_path")</li>
            <li><b>Asset Name:</b> $res.get("asset_name")</li>
            <li><b>Asset Type:</b> $res.get("asset_type")</li>
        </ul>
    #end
    <br />
#end
```

**Comment by bryanboza** [comment]
Fixed, now this tool is working as expected, We need to update the doc with the provided examples 
![Uploading image.png…]()
