### ISSUE TITLE
Thumbnail creator filter is not working for .pdf files

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#19753]
**Describe the bug**
In prior dotCMS versions the following path could be specified to create a thumbnail image from a page in the .pdf by referencing the file in this way (for example): 

localhost:8080/dA/accd72e9ae/120w/thumb

This no longer works in the current released version.  There was also a way to specify the specific page which should be used for the thumbnail, however, if a page is not specified then the first page of the .pdf should be used.

**Comment by yolabingo** [comment]
support issue https://dotcms.zendesk.com/agent/tickets/103182

customer wants to produce thumbnail images from PDF's

We tried permutations of several filters to try convert a PDF to a thumbnail, or even just a png or jpeg file, to no avail 
```
/contentAsset/image-thumbnail/{id}/fileAsset
/contentAsset/image/{id}/fileAsset/filter/Png
/dA/{shorty_id}/thumb
/dA/{shorty_id}/png
```
In all cases, dotcms returns the full .pdf file.

The only activity seen in dotcms.log is when using using `.../thumb` or `/contentAsset/image-thumbnail/...`:
```
21:50:52.057  WARN  exporter.ImageFilterExporter - Exception in resize=class com.dotmarketing.image.filter.ResizeImageFilter :nullcom.dotmarketing.image.filter.ResizeImageFilter.runFilter(ResizeImageFilter.java:51)
21:50:52.057  WARN  exporter.ImageFilterExporter - null
21:50:52.057  WARN  exporter.ImageFilterExporter - com.dotmarketing.image.filter.ResizeImageFilter.runFilter(ResizeImageFilter.java:51)
```

PDF files are listed as supported in the docs https://dotcms.com/docs/latest/image-resizing-and-processing#fileTypes

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19797

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF

**Comment by bryanboza** [comment]
Need to add some postman tests to this endpoint

**Comment by erickgonzalez** [comment]
PR for postman test: https://github.com/dotCMS/core/pull/19864

**Comment by bryanboza** [comment]
Fixed, now we are able to see the thumbnail to this kind of files, tested on release 21.03 // Postgres // FF
