### ISSUE TITLE
Update docker images to use java 11

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19756]
I would like to select a java version that is compiled with backported support for one of the new pauseless collectors, e.g. Shenandoah or ZGC.

We do not need to ship with those collectors turned on by default, but they should be enable-able by passing in docker/JVM config (we currently support this)

**Comment by dsilvam** [comment]
PR Docker repo: https://github.com/dotCMS/docker/pull/47

**Comment by wezell** [comment]
We need to update these images to use:
`adoptopenjdk/openjdk11:alpine`

Also, can we verify that this image includes `Shenandoah` and also that there is aarch version of the image
