### ISSUE TITLE
UI: Need reload the tab when you disable the What's changed feature in edit mode 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19764]
When you are editing a page and try to use the "what's changed". When you disable this field, we need to reload the tab in order to hide the results of this feature 

**To Reproduce**
1. Create a new page 
2. Add some pieces of content 
3. Publish the page 
4. Go to the preview tab and enab le the what's changed 
5. Make sure you don't have changes and then disable the checkbox again 

**Expected behavior**
We need to reload the tab and come back to the preview 

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/103707163-c8956780-4f73-11eb-9190-18c28630b7b1.png)

**Desktop (please complete the following information):**
Tested on release- 21.01 // Postgres // FF

**Comment by wezell** [comment]
dupe #22673
