### ISSUE TITLE
VersionableResource: Get Versionables

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19778]
Create an endpoint in which you pass an identifier or inode and get the versionables, things to consider:

* User must have view permissions
* If an identifier is passed all the versionables must be returned.
* If an inode is passed only the versionable for that specific inode must be returned.

Endpoint: GET api/v1/versionables/{identifierOrInode}

**Comment by erickgonzalez** [comment]
PR: #20314

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
