### ISSUE TITLE
VersionableResource: Delete a specific version of an element by inode 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#19776]
Create an endpoint in which you pass an inode and that version will be deleted, things to consider:
* Inode can not be live or working
* User must have edit permissions
* If it's a container must delete any content type relationships before deleting the version

Endpoint: **DELETE api/v1/versionables/{inode}**

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19781

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
