### ISSUE TITLE
Replace moment for date-fns

### ISSUE THREAD

**Issue by ivorpad** [dotCMS/core#19784]
Moment.js has been deprecated and this library has been known for its huge size, we need to replace it with date-fns which is smaller and tree-shakeable.

https://momentjs.com/docs/#/-project-status/
https://bundlephobia.com/result?p=date-fns@2.16.1

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1741

**Comment by alfredo-dotcms** [comment]
Note to QA: this task is about replacing validations of dates and times, also the date/time locale based on the language selected. So a smoke test around the whole app needs to be made. Testing:


![image](https://user-images.githubusercontent.com/37185433/132920344-a2b824e8-290f-4cf3-a5fe-e330af8ac30a.png)

![image](https://user-images.githubusercontent.com/37185433/132920749-06e249be-1db9-411c-a66e-b33c338bdb71.png)

![image](https://user-images.githubusercontent.com/37185433/132920597-8b442ac7-a60a-4aac-acc2-256739c2ae61.png)

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, I did a sanity test to all the mentioned components in the above comment, and everything is working as expected

**Comment by alfredo-dotcms** [comment]
to fix:

this fix solves a path not found for a Locale for `Date-fns`, based on the chosen app language

![image](https://user-images.githubusercontent.com/37185433/133337557-29d6046d-2a5d-4c8a-abb1-f2b328855af7.png)

PR: https://github.com/dotCMS/core-web/pull/1760/files

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF
