### ISSUE TITLE
We are not updating the portlet title when you are navigating through the backend 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19792]
After the new changes in Site --> Templates, this title is overriding the title of the other portlets and when you navigate in anyone we always show Templates 
![image](https://user-images.githubusercontent.com/2641437/104350953-63d59200-54ca-11eb-8812-7b18cda9562d.png)

**To Reproduce**
1. Login as admin
2. Navigate to Site -- > Templates 
3. Add a new template 
4. Now navigate to other portlets and make sure we are updating the title 

**Expected behavior**
We need to show the correct portlet title to everyone. 

**Desktop (please complete the following information):**
Tested on master // Postgres // Chrome

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1547

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
