### ISSUE TITLE
Starter Page: Add descriptions & links missing on starter page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#19802]
As a user I need to be able to have a valid description and working link of all elements on the starter page.

Based on the image, we need descriptions(red boxes) and links(yellow circles)
![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/ce9aa25d-4a75-4e36-b445-168921f6e6ac)
*Jason Smith @fishsmith , will provide the descriptions and links to be implemented

Welcome:
You are logged in as Admin. To help you get started
building with dotCMS we have provided some quick links.

- Create data Model
Description: Define your contents’ structure and relationships using multiple types of fields.
Link: /content-types-angular/create/content
Opens on new window: No

- Add content
Description: Create content that fuels your digital experiences. 
Link: /c/content/new/webPageContent
Opens on new window: No

- Design a layout
Description: Use our Drag-n-Drop UI to build grid-based layouts.
Link: /templates/new/designer
Opens on new window: No

- Create a page
Description: Put it all together and build your first page and fill it with content.
Link: /c/content/new/htmlpageasset
Opens on new window: No

- GraphQL API
Description: Query content, assets and pages and specify what data you want returned.
Link: https://dotcms.com/docs/latest/graphql
Opens on new window: Yes

- Content API
Description: Create and query content, assets and pages.
Link: https://dotcms.com/docs/latest/content-api
Opens on new window: Yes

- Image Resizing and Processing
Description: Crop, resize, apply filters and retrieve any image in the system.
Link: https://dotcms.com/docs/latest/image-resizing-and-processing
Opens on new window: Yes

- Page Layout API
Description: Get any page in the system. Including its layout and content information.
Link: https://dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas
Opens on new window: Yes

- Generate API Key
Description: Generate an API key or token to authenticate your requests.
Link: https://dotcms.com/docs/latest/rest-api-authentication#APIToken
Opens on new window: Yes

- Documentation
Description: Explore our online documentation and guides.
Link: https://dotcms.com/docs/latest/
Opens on new window: Yes

- Examples
Description: Learn by example, community contributed code examples.
Link: https://dotcms.com/codeshare/
Opens on new window: Yes

- Community
Description: Join our helpful community of dotCMS users.
Link: https://dotcms.com/forum/
Opens on new window: Yes

- Training Videos
Description: Watch online training videos and courses.
Link: https://dotcms.com/courses/
Opens on new window: Yes

- Write a Review
Description: Share your thoughts and let us know what you think.
Link: https://dotcms.com/review/
Opens on new window: Yes

- Feedback
Description: Can’t find something? Make a suggestion.
Link: https://dotcms.com/contact-us/
Opens on new window: Yes

**Comment by alfredo-dotcms** [comment]
Core: https://github.com/dotCMS/core/pull/19828/files

**Comment by alfredo-dotcms** [comment]
update PRs
core: https://github.com/dotCMS/core/pull/19846

**Comment by nollymar** [comment]
**Internal QA:** 

Links and descriptions were updated as required. 

<img width="1676" alt="Screen Shot 2021-01-25 at 12 36 34 PM" src="https://user-images.githubusercontent.com/8741395/105743743-98a20a00-5f0a-11eb-9fc1-cefac6e9760f.png">


However, I found a couple of observations that probably are not part of the scope of the task: 
- The Getting Started link is displayed as a submenu option and the property translation is missing

<img width="163" alt="Screen Shot 2021-01-25 at 12 10 13 PM" src="https://user-images.githubusercontent.com/8741395/105743599-9049cf00-5f0a-11eb-8e0e-2c0c3810d144.png">

- The "Write a Review" link is broken: https://dotcms.com/review/

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/105873123-c3e73080-5fc0-11eb-8ac5-627aa8c714b7.png)

design changes requested!

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1567/files

**Comment by nollymar** [comment]
With the new design suggestions, this is how it looks: 
<img width="1675" alt="Screen Shot 2021-01-26 at 2 13 05 PM" src="https://user-images.githubusercontent.com/8741395/105893443-18020d00-5fe1-11eb-9471-1ad32a56a5b6.png">

**Comment by bryanboza** [comment]
Fixed, the descriptions were updated correctly... Tested on release-21.03 // Postgres // FF
