### ISSUE TITLE
Allow mail session to be configured via environmental variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19813]
Currently, SMTP does not work out of the box when using our docker image.  It is possible to inject a mail context into tomcat but this involves having to mung around with mounting context.xml and or server.xml files.

It would be ideal if dotCMS could configure the mail session using environmental variables - even to provide deep configuration such as TLS and SMTP authentication.  This would allow the dotCMS docker image to be configured without needing to map in extra files.

Here is the list of properties that can be overridden.

https://javaee.github.io/javamail/docs/api/index.html?overview-summary.html

**Comment by victoralfaro-dotcms** [comment]
@wezell environment variables are picked by mail config but once the SMTP settings are read from JNDI they are not included in the mail session properties when sending an actual mail.

**Comment by victoralfaro-dotcms** [comment]
Testing it locally without Docker
```
---------- MESSAGE FOLLOWS ----------
Message-ID: <1916769394.1616007934602.JavaMail.victoralfaro@fischer.lan>
From: "dotcms.org" <support@dotcms.com>
To: Victor Alfaro <victor.alfaro@dotcms.com>
Subject: dotCMS Password Assistance
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_Part_1_2029000647.1616007830477"
X-RecipientId: null
X-Peer: 127.0.0.1

------=_Part_1_2029000647.1616007830477
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

<html><body><p>To reset your password please follow the link below:</p><p><a href="https://localhost/dotAdmin/#/public/resetPassword/ZNkgeULT5WTijvhOHgRnFEghBfbgkc:1616007830460">https://localhost/dotAdmin/#/public/resetPassword/ZNkgeULT5WTijvhOHgRnFEghBfbgkc:1616007830460</a></p><p>If you didn't make a request to change your password, your account security may be at risk; please contact the administrator.</p></body></html>
------=_Part_1_2029000647.1616007830477--

------------ END MESSAGE ------------

```

**Comment by bryanboza** [comment]
Fixed, tested via docker with the provided steps by @victoralfaro-dotcms and work fine.

**Comment by wezell** [comment]
We need to comment out the line:
```
    <Resource name="mail/MailSession" auth="Container" type="javax.mail.Session" mail.smtp.host="localhost" />
```
from our context.xml so that this functionality works out of the box.

**Comment by wezell** [comment]
Also, @rweiner we need to update this doc to show how to configure your mail server using environmental variables:

https://dotcms.com/docs/latest/mail-configuration

**Comment by bryanboza** [comment]
Fixed, tested after the last change and works as expected, the resource fragment in the context.xml now is commented by default 
![image](https://user-images.githubusercontent.com/2641437/114912769-a36b8d00-9ddd-11eb-808b-80dc10f72f27.png)

**Comment by swicken-dotcms** [comment]
Excluding from 5.2.8.5 as the code changes were not functional there.
