### ISSUE TITLE
Site Browser: When creating a New Page it is not being redirected to Edit Page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#19812]
**Describe the bug**
When creating a New Page and Publishing, it is not being redirected to Edit Page to be able to make changes.

**To Reproduce**
1. Go to 'Site Browser'
2. Click on Add a new page
3. Add some content in the dialog and press "PUBLISH"
4. Page is created, but it is not being redirected to "EDIT PAGE"

**Expected behavior**
Once page is published, it needs to be redirected to EDIT PAGE to be able to make changes

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
