### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19823]
PR: https://github.com/dotCMS/core/pull/19804

**Comment by wezell** [comment]
We need to smoke test the different languages and our backend ui

**Comment by bryanboza** [comment]
not sure if this is the cause, but we have a lot of things without translations 
![image](https://user-images.githubusercontent.com/2641437/105902615-80062280-5fe4-11eb-994f-ad2204be5029.png)

**Comment by bryanboza** [comment]
Here some areas that still without translations: 

- Logout 
- Templates portlet
