### ISSUE TITLE
Content types tabs needs to be framed like in templates

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19824]
**Describe the bug**
In one of the refactor the tabs inside a content type lost it frame.

**To Reproduce**
1. Go to content type
2. Click on any content types
3. Click on any tab

![Screen Shot 2021-01-19 at 10.11.37.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d78baadd-60dd-445b-ac9d-1f90ec25f984)

**Expected behavior**
It should have the same frame.

**Additional context**
See the template code and use the same components.

**Comment by ivorpad** [comment]
PR: https://github.com/dotCMS/core-web/pull/1557

**Comment by victoralfaro-dotcms** [comment]
![image.png](https://images.zenhubusercontent.com/5e9dc4dff37aec55f61ae012/18201aba-2859-44f1-b5c7-92859091fe2b)
![image.png](https://images.zenhubusercontent.com/5e9dc4dff37aec55f61ae012/629a03a1-7fce-472f-8466-7c45b210586c)
![image.png](https://images.zenhubusercontent.com/5e9dc4dff37aec55f61ae012/3a388a68-17eb-4524-a511-dc2076ba93e9)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postres // Safari
