### ISSUE TITLE
[core] : Legacy IDs are not compatible with Shorty API

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19832]
Reported via Support: [103342](https://dotcms.zendesk.com/agent/tickets/103342)
Reproducible as of dotCMS 5.3.8, and latest master

Initially, dotCMS used numeric IDs for their objects instead of using UUIDs, like we do now. For customers coming from very old versions of dotCMS, there are still several objects that have IDs that are both numeric, and very short, even shorter than the expected minimum of the Shorty API.

This is causing unexpected behavior in the application. There is not a clear error message or alert that would let the user know why or what happened.

**To Reproduce**
Please ask Jose Castro for more information, as customer data needs to be replicated here.

**Expected behavior**
The API needs to handle both legacy and new types IDs.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19834

**Comment by wezell** [comment]
We need to create a LegacyImpl that looks for a number, where the default implementation expects UUID / characters

**Comment by jdotcms** [comment]
Note for change log doc:

Clients with legacy ids, have to include this property on their dotmarketing-config.properties
```
dotshortyapi_use_legacy=true
```

In order to use the implementation that support the legacy ids

**Comment by erickgonzalez** [comment]
Fixed tested on client DB. When the property is set to `true` is able to resolve legacy ids.

**Comment by bryanboza** [comment]
Since this was tested with the client DB, then is not necessary double QA. Passed
