### ISSUE TITLE
No results when filtering template should not show the empty state

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19839]
**Describe the bug**
When we filter template and we get no results we show the "empty state"

**To Reproduce**
1. Go to template list
2. Search for something like: "sfsdfsdf"
3. See the empty state

**Expected behavior**
The empty state is only for when there is NO template in the system.

For no results in filtering we should show a "No Results" message.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1559

**Comment by bryanboza** [comment]
Fixed, tested on release 21.02 // Postgres // FF
