### ISSUE TITLE
Advanced template broken in Safari

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19841]
**Describe the bug**
When you try to create or edit an advanced template in Safari you get:

![image](https://user-images.githubusercontent.com/2641437/105246437-e00a4e00-5b38-11eb-943b-51fec6d67a86.png)

**To Reproduce**
1. Go to edit a advanced template in Sarai
2. See the error

**Expected behavior**
Should work as in Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/105246437-e00a4e00-5b38-11eb-943b-51fec6d67a86.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // Safari
