### ISSUE TITLE
Template endpoint not respecting current site

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19845]
**Describe the bug**
The template list endpoint is not respecting and returning only templates from the current site

**To Reproduce**
1. Create a new site
2. Add a template
3. Go to the template listing
4. Switch site and refresh page...
5. See the error

**Expected behavior**
It should bring only the templates of the current site when no site is passed in the query params.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19847

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
