### ISSUE TITLE
Need to add site selector filter to the theme selector dropdown

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19849]
**Is your feature request related to a problem? Please describe.**
We need to be able to select theme from different hosts and as the theme selector is now that can be possible.

<img width="661" alt="Screen Shot 2021-01-22 at 09 18 00" src="https://user-images.githubusercontent.com/751424/105509164-db59ad00-5c92-11eb-92b3-ad5a71615034.png">

**Describe the solution you'd like**
Next to the input text filter add a [site selector component](https://github.com/dotCMS/core-web/blob/master/src/app/view/components/_common/dot-site-selector/dot-site-selector.component.ts) and when user change it it list the theme inside the selector host

**Describe alternatives you've considered**
The theme endpoint take a queryParam for the host

**Additional context**
We need to make the template property dialog a little wider so the new dropdown next to the input text looks good.

**Comment by fmontes** [comment]
Known issue: https://github.com/dotCMS/core/issues/19874

**Comment by bryanboza** [comment]
We need to reset that filter every time you close that window. Right now if you have some theme selected, then made some search in a different site and finally just close the window without select  another one, when you open the window again the thees still filtered.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
