### ISSUE TITLE
Reload the template portlet when user change the site in the top-right selector

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19840]
**Describe the bug**
When the user change the site the portlet is not refreshed so we keep seeing the list of template from the previous site.

**To Reproduce**
1. Go to template
2. Change the site
3. See the template list not refreshing

**Expected behavior**
1. If we are in the list, it should reload the list
2. If we are in any other section of the portlet we should redirect to the list and refresh the data

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
