### ISSUE TITLE
Can't access Container Detail 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#19867]
**Describe the bug**
Can't access Container Detail  and error show up. 

Log: https://gist.github.com/hmoreras/b477d068283da4b69851e40895a65543 

**To Reproduce**
1. Go to http://localhost:8080/dotAdmin/#/c/containers
2. Click on any Container
3. See error

![image](https://user-images.githubusercontent.com/31667212/105891308-1a129e80-5fd6-11eb-920a-84d8b0729893.png)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19870

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
