### ISSUE TITLE
Containers pagination needs double click to change on templates portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19868]
When you have multiple containers and need to paginate to add into a container using the new templates portlet, you need double click in the number to reload the list. We need do this just with one click 
![image](https://user-images.githubusercontent.com/2641437/105896908-120a2d00-5fdd-11eb-9f5f-6a193df35cb3.png)

**To Reproduce**
- Login ad admin 
- Create multiples containers 
- Add a new template
- Try to paginate the list to add a container into a template 

**Desktop (please complete the following information):**
Tested on release-21.02 // Postgres // FF

**Comment by bryanboza** [comment]
Also, need press enter to find for consistences, we need do this automatically after key-press 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2641437/105897668-15ea7f00-5fde-11eb-8150-0489c67cb656.png">

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1568

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
