### ISSUE TITLE
Back Port 19620 into 5.3.8.3

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19865]
We need to backport the changes (including the change to core-web) from #19620 into 5.3.8.3

https://github.com/dotCMS/core/issues/19620

**Comment by fmontes** [comment]
We need to bring in this: https://github.com/dotCMS/core-web/pull/1528/files to 5.3.8 and create a new version.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the problem after those fixes
