### ISSUE TITLE
UI hangs when creating a new page

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#19866]
**Describe the bug**
When you create a new page from the browser then hit Save, you get the spinner but are never taken to the new page in edit mode. If you hit refresh your then taken to the new page in edit mode.

**To Reproduce**
1. Right click on folder in browser and select New -> Page
2. Name your page , select template, and hit Save or Save and Publish
3. Spin shows but you are left there until you refresh the page

**Expected behavior**
You should be take to the page in edit mode.

**Comment by fmontes** [comment]
False alarm, fixed when updated auth to latest release 21.02
