### ISSUE TITLE
Edit Permissions Tab only visible when user has role CMS_ADMIN

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19863]
dotCMS version 5.3.8

Only the Users with the role CMS_ADMIN are able to see the **Permissions** Tab at Content Type and Contentlets.

Screenshot of user role permissions:
![image](https://user-images.githubusercontent.com/5010638/105817792-5e8e4200-5fb6-11eb-9e03-c6b0d296c3fb.png)

![image](https://user-images.githubusercontent.com/5010638/105817856-7b2a7a00-5fb6-11eb-8923-7ab634385bc0.png)

![image](https://user-images.githubusercontent.com/5010638/105817917-88476900-5fb6-11eb-804d-2dd2c356b67f.png)

Screenshot of Content Type permissions:
![image](https://user-images.githubusercontent.com/5010638/105817960-97c6b200-5fb6-11eb-8541-4accccaa4094.png)

Screenshot of the view of the user of the Content Type with Edit_Permissions_Permission:
![image](https://user-images.githubusercontent.com/5010638/105818004-a6ad6480-5fb6-11eb-9bef-bcd517215bb2.png)

From: dotcms/core-web#1565
reported by: @JohannesDienst

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
