### ISSUE TITLE
Add thumbnail to the relation ship field search table

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19879]
**Is your feature request related to a problem? Please describe.**
We need to add thumbnail to the relationship field content search.

**Describe the solution you'd like**
https://images.zenhubusercontent.com/3729629/46d60162-d529-4051-916d-2b3ce4838d55/screen_recording_2021_01_29_at_12_46_53_pm.mov

**Describe alternatives you've considered**
We did this in the content search list, there is a whole logic to do it, take a look there.

**Comment by alfredo-dotcms** [comment]
this is not possible to be done with current data structure.

![image](https://user-images.githubusercontent.com/37185433/106655813-78ec9080-655f-11eb-89df-ac7c0b1b7c4f.png)
that table use the same code as in the content search list (so no logic is needed), the thing is that the data loaded are Blog Comments and that kind of content does not have an img that can be used as thumbnail

*Blog Comment
![image](https://user-images.githubusercontent.com/37185433/106656049-c7019400-655f-11eb-93c7-ffe85f3782a1.png)


VS

*Blog
![image](https://user-images.githubusercontent.com/37185433/106656110-dc76be00-655f-11eb-9dbf-db6e2614016d.png)

**Comment by wezell** [comment]
Blog comments do not have an image so thumbnails cannot be shown
