### ISSUE TITLE
Tab inside edit field dialog doesn't show active state

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19878]
**Describe the bug**
When you edit a field in a content type, the tab "Overview" doesn't load "active"

**To Reproduce**
1. Go to any content type
2. Click on any field
3. See the tab "Overview" without the underline that indicate is active

https://images.zenhubusercontent.com/3729629/791ca4f7-027d-4c02-9cf2-c08650f570b6/screen_recording_2021_01_29_at_11_54_59_am.mov

**Expected behavior**
Tab should show active state

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
