### ISSUE TITLE
[core] : Remove unnecessary Web Token

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19877]
Reported via Support: [103228](https://dotcms.zendesk.com/agent/tickets/103228)
Reproducible in dotCMS 5.3.8, up to latest master.

The Password Reset feature is using a Web Token to work. As per discussing with @wezell and @jdotcms , such a Token is not necessary at all, and might interfere with the proper workflow.

**To Reproduce**
Please ask me for more details about the reproducible case.

**Expected behavior**
The Password Reset shouldn't use a Web Token.

Doc regarding email config https://dotcms.com/docs/latest/mail-configuration#ExampleGmail

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19915

**Comment by bryanboza** [comment]
Fixed, tested on release 21.03 // Postgres // FF 

Tested with those cases: 

- success
- valid token with bad passwords
- expired token (after 30 minutes should expire)
- trying to change the password twice with the same token
