### ISSUE TITLE
Bring Back is not working as desired on Page content type. 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19876]
Reported in v5.2.8 in Zendesk 103441
Recreated on Demo v21.01

**Describe the bug**
Bring Back is not working as desired on Page content type. 
Adding / removing contentlets from containers on a Page doesn't seem to be recorded in the version history and using Bring Back doesn't reflect content changes on the page. 

**To Reproduce**
1. Create new page. Save.
2. Add content to a container. Save.
3. Change content in the container. Save.
4. Use 'Bring Back' to go to the 1st version of the page. Save.
5. Preview page.

Content changes should be reflected but they are not.

**Screenshots**

BUILD NEW PAGE WITH 2 CONTENTS IN THE CONTAINER
![image](https://user-images.githubusercontent.com/49727631/106199146-a4940300-617a-11eb-90d7-2d75637a2572.png)

THE HISTORY TAB
![image](https://user-images.githubusercontent.com/49727631/106199171-aeb60180-617a-11eb-82df-f3c19b7c6359.png)

REMOVE ONE OF THE CONTENTS
![image](https://user-images.githubusercontent.com/49727631/106199297-db6a1900-617a-11eb-94fe-de9e2092623d.png)

THE HISTORY TAB
![image](https://user-images.githubusercontent.com/49727631/106199347-ed4bbc00-617a-11eb-9211-14cd9d97e698.png)

CLICK "BRING BACK" TO THE PREVIOUS VERSION
![image](https://user-images.githubusercontent.com/49727631/106199402-094f5d80-617b-11eb-8f2d-8d2cffee3a71.png)

STILL ONLY ONE CONTENTLET IN THE CONTAINER
![image](https://user-images.githubusercontent.com/49727631/106199468-1ff5b480-617b-11eb-9a47-6d4549051238.png)

**Comment by wezell** [comment]
This is not an issue and is how dotCMS has worked since day 1.  We don't version the page <-> contentlet relationships.

**Comment by swicken-dotcms** [comment]
Reopening this as it's a consistent question within support, changing to an enhancement
