### ISSUE TITLE
Theme selector pagination not resetting back to its initial page

### ISSUE THREAD

**Issue by ivorpad** [dotCMS/core#19874]
When navigating through the pagination in the theme selector and switching sites the pagination is not reset back to its initial position.

**To Reproduce**

https://user-images.githubusercontent.com/52452/106163370-5fc39880-6189-11eb-9228-8a2e2875f928.mp4

**Expected behavior**
When switching sites and page of the pagination should be set back to 1.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1721

**Comment by nollymar** [comment]
**Internal QA:** The theme selector now displays themes correctly considering filters. However, the Host filter is displayed only when empty sites are created. If I try to use it on cloned sites, the filter is hidden.


https://user-images.githubusercontent.com/8741395/128903197-67c8d9df-59ac-4044-8d65-6298bf9f02cc.mov

A new issue was created here: https://github.com/dotCMS/core/issues/20781

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF
