### ISSUE TITLE
Make the relate button sticky in relation content search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19880]
**Is your feature request related to a problem? Please describe.**
We need to keep the "RELATE" button showing when user scroll in the relationship content.

**Describe the solution you'd like**
<img width="1444" alt="Screen Shot 2021-01-29 at 12 49 54 PM" src="https://user-images.githubusercontent.com/751424/106315295-ab7d4d00-6230-11eb-85a9-73a37a8e380c.png">

**Describe alternatives you've considered**
This can be done in pure CSS

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19883

**Comment by nollymar** [comment]
**Internal QA:** Passed

![screencast 2021-02-25 10-54-29](https://user-images.githubusercontent.com/8741395/109179532-00d94b00-7758-11eb-8806-e18a01826169.gif)

**Comment by bryanboza** [comment]
Fxed, tested on release-21.03 // Postgres // Safari
