### ISSUE TITLE
Use labels instead of values for radio fields in Search Portlet results

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#19889]
Content editors see labels instead of values for Radio fields, when editing a new or existing content. Also, when fields are searchable, they see the labels in the search portlet, in the search section in the left. But in the search result listing, they see the values instead of the labels.

**Proposed Solution**
Show labels instead of values for result listing.

**Screenshot**
This screenshot shows the difference between search section in the left, that uses labels, and search results in the right, that use values:

![image](https://user-images.githubusercontent.com/2894221/106676795-2752fe80-657d-11eb-869f-250d3b79646e.png)

**Comment by erickgonzalez** [comment]
Customer ticket https://dotcms.zendesk.com/agent/tickets/109334
