### ISSUE TITLE
While edit or creating a template and switch site we should redirect to template listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19886]
**Is your feature request related to a problem? Please describe.**
While you are editing or creating a template if you change the site selector in the top bar we should redirect to the template listing.

**Describe the solution you'd like**
We need to redirect to the template list.

**Describe alternatives you've considered**
We can do the same approach we took here: https://github.com/dotCMS/core-web/blob/release-21.02/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.ts#L77

Make sure this works in any state of the portlet, we might want to move things more globally within the template portlet.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
