### ISSUE TITLE
Custom Page Layout is not sending in Push Publish

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#19890]
**To Reproduce**
1. Steps to reproduce the behavior:
2. Create a Page with any templae
3. Push the page
4. Change the template o create a custom one
5. Push Again and the Page in the receiver is going to keep the same layout

**Expected behavior**
The page in the receiver should have the last change in the layout

**Comment by john-thomas-dotcms** [comment]
Just a note: It will be really important for support to be able to backport this fix to LTS patch releases.

So if possible, we ask that you please keep the code changes as small as possible (no refactoring if it's at all possible).

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19892
