### ISSUE TITLE
Bring in dotcms-webcomponents

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19906]
### Description
- This is a StencilJs library, so we need to use `nx` for this: https://www.npmjs.com/package/@nxext/stencil
- Original repo: https://github.com/dotCMS/dotcms-webcomponents/

### Acceptance criteria
1. Build and be ready for `npm publish`
2. Tests needs to run
3. Be able to pull into `dotcms-ui`

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1618
