### ISSUE TITLE
Invalidate cache in the HTML for logout/SAML work

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19902]
When we logout the browser is not cleaning the cache so SAML can act accordingly.

We need to add the cache control to the `index.html` in angular.

```html
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="cache-control" content="no-store"/>
<meta http-equiv="cache-control" content="must-revalidate"/>
<meta http-equiv="expires" content="0" />
<meta http-equiv="pragma" content="no-cache" />
```

More info: https://stackoverflow.com/questions/1341089/using-meta-tags-to-turn-off-caching-in-all-browsers

### Consider
Check that the cache is invalid only for the HTML file and no images, fonts and other assets

**Comment by hmoreras** [comment]
![image](https://user-images.githubusercontent.com/31667212/107063643-3cf43e00-67a0-11eb-8282-30825005e831.png)
The resources like images, external css, font files are using memory or disk cache.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1580

**Comment by bryanboza** [comment]
Fixed, tested with SAML in a local configuration and now we are redirecting as expected.
