### ISSUE TITLE
Rules: We are able to add empty tags 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19909]
When you are adding a new rule and use the "add tag to visitor" actionlet, we are adllowing to add empty tags and this is causing an error in the logs 

Error: https://gist.github.com/bryanboza/387b679814c5d789a88f74d3469f1be2

![image](https://user-images.githubusercontent.com/2641437/106932486-6ac47e80-66dd-11eb-80e4-28326f2b39a6.png)

**To Reproduce**
- Login as admin 
- Create a new rule 
- Select the mentioned actionlet 
- Try to add emty tags 

**Expected behavior**
We need to validate this before add the tag 

**Desktop (please complete the following information):**
Tested on release-21.02 // Postgres // FF

**Comment by nollymar** [comment]
**Internal QA:** Needs work
I can still add empty tags

<img width="1663" alt="Screen Shot 2021-08-31 at 5 53 28 PM" src="https://user-images.githubusercontent.com/8741395/131585950-1ac90ca5-58d6-4e44-8f53-0b7b139d75ea.png">

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core-web/pull/1747

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Needs some work here, now we are printing a really noisy log and we are adding the tag in the UI, we show an error, but we should to avoid this instead add the empty tag:
LOG: https://gist.github.com/bryanboza/9b652044bbc1dc0046dbfe82ac0004a3
![image](https://user-images.githubusercontent.com/2641437/133523918-ef64b574-49d0-4fa3-babf-58bb5dc06732.png)
