### ISSUE TITLE
json.fetch does not handle arrays

### ISSUE THREAD

**Issue by mabouza** [dotCMS/core#1991]
The JSONTool that ships with dotCMS is not able to deal with JSON arrays, e.g.

```
[
{
id: "1",
title: "First Title"
},
{
id: "2",
title: "Second Title"
},
{
id: "3",
title: "Third Title"
}
]
```
You have to wrap the list as a json property in the string which is clunky.   Reason is that JSON arrays are not really valid json objects and fail json validation, .e.g. jsonlint.com, but the fact is most everyone is returning them via their web services and so we should handle.

Additionally, it would be very nice if we could provide a way for users to pass Headers to allow for basic auth and other header properties to the tool.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9121

**Comment by DeanGonzalez** [comment]
Hey Shay,
I just tested using this example that Will gave me... working

https://gist.github.com/DeanGonzalez/721b6aadcf23ca85f31603bd443836b3

**Comment by dotcmsCodeReview** [comment]
We need to test that our non-array json pulls still work as well.

**Comment by DeanGonzalez** [comment]
Tested and see John already documented here during 3.3 release: http://authoring.dotcms.com/docs/latest/jsontool#Iteration

**Comment by shaydotcms** [comment]
Passed QA. Array and non-array json pulls are working. Tool allows to pass headers
Tested locally in master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
