### ISSUE TITLE
Update <dot-copy-button /> button component UI

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19912]
**Is your feature request related to a problem? Please describe.**
We want the button to look like the API button:

![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/d81e65e8-46d7-4a08-9bd9-9aa21fb7b88e)

**Describe the solution you'd like**
1. Copy for the label
2. Should take a tooltip param (optional)
3. Reuse what you can from the `dot-api-link` css

Where to test:
- Edit Mode of any page

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Docker // FF
