### ISSUE TITLE
Forgot password and reset password needs to handle error

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19916]
**Is your feature request related to a problem? Please describe.**
When you are resetting the password, DotCMS requires certain requirements, and the server returns a 500 with some error messages when they do not match.

**Describe the solution you'd like**
Check the error and display them.

**Describe alternatives you've considered**
Just show the errors. No mocks apply here.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1583

**Comment by erickgonzalez** [comment]
- The forgot password page http://localhost:8080/dotAdmin/#/public/forgotPassword does not handle errors.
- Success message twice?

<img width="699" alt="Screen Shot 2021-02-11 at 2 05 54 PM" src="https://user-images.githubusercontent.com/5278970/107692379-513dac80-6c72-11eb-98c8-2caf05494367.png">
<img width="590" alt="Screen Shot 2021-02-11 at 2 05 18 PM" src="https://user-images.githubusercontent.com/5278970/107692374-4f73e900-6c72-11eb-8928-9a7e964d5f05.png">

**Comment by hmoreras** [comment]
Feddback & test updates: https://github.com/dotCMS/core-web/pull/1588

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19950

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/19962

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
