### ISSUE TITLE
Sign in button redirect to recover password while recovering the password

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19917]
**Describe the bug**

**To Reproduce**
1. Click on Recover Password
2. Enter email
3. Recover password
4. Click on sign in
5. It redirects to recover the password.

**Expected behavior**
Iti should log in.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1582

**Comment by bryanboza** [comment]
Fixed, tested on release 21.03 // Postgres // FF
