### ISSUE TITLE
Google Translate Sub-action is sending error with even with valid translation key

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#19910]
When creating a workflow sub-action using the "Translate Content" subaction, the expected behavior is that when you click on the subaction and add a valid key to the properties of the Translate content subaction:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/1569167/106933197-a57ee480-66e6-11eb-9a94-76418d6e4171.png">

When the user uses the action on content via the workflow the Translate action should translate the content into all the installed language versions that are configured on the instance.

This works in dotcms 5.3.9 - however in the current release version it is generating an error in the dotcms log and does not work:

`ERROR business.WorkflowAPIImpl: There was an unexpected error: Error executing Translation Actionlet`

Contact me if you need a valid translation api key for google

**Comment by DeanGonzalez** [comment]
Will commented that this related issue may have caused the conflict: https://github.com/dotCMS/core/issues/18505

**Comment by wezell** [comment]
This was caused by the change of the return type from `JsonObject` to `Map` in  #18505

**Comment by jdotcms** [comment]
Oh my bad, I thought it was being used only on viewtool.
@DeanGonzalez  Remember you can configure the translation service  by apps too:
<img width="1441" alt="Screen Shot 2021-02-04 at 1 48 46 PM" src="https://user-images.githubusercontent.com/19578350/106947245-bf70f500-66ef-11eb-9229-88300ccc831b.png">

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19911

**Comment by DeanGonzalez** [comment]
Hey Devs & QA, could you test the "Ignore Fields" property on the translation action.  I do not see it being respected either in the 5.3.9 version I was testing.  Please let me know if I need to generate another ticket.

![ignoreFields](https://user-images.githubusercontent.com/1569167/107287024-5d85f780-6a2f-11eb-9be2-d07d14b257d1.jpg)

**Comment by victoralfaro-dotcms** [comment]
Created a Blog content:
![image](https://user-images.githubusercontent.com/64026161/109324054-ca640480-7819-11eb-9bbd-c569eeb588ff.png)

After hitting the Translate workflow there is a spanish copy of the blog content.
![image](https://user-images.githubusercontent.com/64026161/109323935-a30d3780-7819-11eb-8626-997385d32031.png)

**Comment by bryanboza** [comment]
Fixed, now I'm able to translate without problems
