### ISSUE TITLE
Add a simple logger to velocity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19920]
Sometimes you want to log something out from velocity.  We need a tool that will allow you to do something like:

$logger.info("this info should be in the log")

or

$logger.warn("this WARN should be in the log")

**Comment by x0rsw1tch** [comment]
Question, is there any difference between this and the `$dotlogger` ViewTool?

**Comment by wezell** [comment]
Ha!  That is a great question and the answer is no, they are almost exactly the same.  I was unaware that we had the dotlogger in our stack and recreated the wheel - makes sense that we already had it as it is low hanging fruit.  Closing this issue.
