### ISSUE TITLE
System assets (theme, container and template) to create a page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19929]
We need to create a "System" theme, container, and template. We update the starters to have all this so when a user starts DotCMS from scratch it'll be able to create a page without having to create all the assets manually (theme, template, and containers).

### To do so
1. We added "File" template types.
2. We update the starters to have a system template and it assets

**Comment by bryanboza** [comment]
Fixed, tested on both starters and now we are able to use this template without problems
