### ISSUE TITLE
Lost Padding in the content search screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19922]
For some reason, we have lost the padding under the controls (above the listing) in the content search screen.  This is happening only in master and not the release branch.

![Screen Shot 2021-02-08 at 12 37 40 PM](https://user-images.githubusercontent.com/934364/107259177-b0998380-6a0a-11eb-8db6-9c27095833a1.png)

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/issues/19824

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/dotcms-dojo-theme/pull/79/files
https://github.com/dotCMS/core/pull/19964/files

**Comment by nollymar** [comment]
**Internal QA:** Fixed
<img width="1680" alt="Screen Shot 2021-02-25 at 10 23 58 AM" src="https://user-images.githubusercontent.com/8741395/109175288-a8a04a00-7753-11eb-9083-996797ac539e.png">

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release 21.04
