### ISSUE TITLE
Add Icon Selector to tools portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19933]
Follow on to #19592 We need to add the icon selector webcomponent to the tools portlet here:

/dotAdmin/#/c/roles

![Screen Shot 2021-02-09 at 3.13.52 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/5b2b7235-cb9c-4b4f-8c1f-907e45b03faa)

@fmontes 
Question, should we hide the color picker here or should we allow it?

**Comment by fmontes** [comment]
> Follow on to #19592 We need to add the icon selector webcomponent to the tools portlet here:
> 
> 
> 
> /dotAdmin/#/c/roles
> 
> 
> 
> ![Screen Shot 2021-02-09 at 3.13.52 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/5b2b7235-cb9c-4b4f-8c1f-907e45b03faa)
> 
> 
> 
> @fmontes 
> 
> Question, should we hide the color picker here or should we allow it?

I think it would be cool for users to add colors to their icons in the sidebar, but this will required backend work to save the icon color and get that in the API.

**Comment by alfredo-dotcms** [comment]
Based on @fmontes's opinion, this task won't have a color picker, just the icon picker

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/dotcms-webcomponents/pull/51/files
https://github.com/dotCMS/core/pull/19961/files

**Comment by victoralfaro-dotcms** [comment]
Icon dropdown added.
![image](https://user-images.githubusercontent.com/64026161/109037227-1daa4b80-7690-11eb-9114-7b3b5ecff305.png)
![image](https://user-images.githubusercontent.com/64026161/109037260-269b1d00-7690-11eb-837e-0d7366dd9c62.png)

**Comment by nollymar** [comment]
Additional PR: https://github.com/dotCMS/core/pull/19963

**Comment by nollymar** [comment]
**Internal QA:** Passed

<img width="506" alt="Screen Shot 2021-02-25 at 10 49 33 AM" src="https://user-images.githubusercontent.com/8741395/109178973-6c6ee880-7757-11eb-8ae5-79dc7063d205.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
