### ISSUE TITLE
Images uploaded to an Image Field via Drag-and-Drop from a file manager will not display as images

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19939]
As reported in https://dotcms.zendesk.com/agent/tickets/103549 and recreated on current Demo v21.x

Images uploaded to an Image Field via Drag-and-Drop from a file manager will not display as images.

The files do not get saved as "Files"  - they become 'dotAsset' files.

This breaks the display of the contentlet. 

In the example from demo (see screenshots) the entire contentlet - even the fields that are not Image Fields - will fail to display

**To Reproduce**
1. Create a new content type with an Image Field or add an Image Field to an existing content type.
2. Add a contentlet including an image in the Image Field via browse/upload instead of drag/drop
3. Add contentlet to a page. It should display as normal. 
4. Edit the contentlet by inserting a new image by dragging a file from a local file explorer to the field.
5. Save/publish

**Expected behavior**
Image should display as normal.

**Actual Behavior**
None of the contentlet's fields display. Content appears blank.

CONTENTLET - IMAGE ADDED NORMALLY
![image](https://user-images.githubusercontent.com/49727631/107555459-d191de00-6b9c-11eb-93ed-7fbff936470a.png)

NORMAL CONTENTLET DISPLAY ON FE
![image](https://user-images.githubusercontent.com/49727631/107555560-ea01f880-6b9c-11eb-8802-2fa2ee104bfb.png)

REPLACE IMAGE VIA DRAG AND DROP
![image](https://user-images.githubusercontent.com/49727631/107555612-fe45f580-6b9c-11eb-8438-c8c6d619dce1.png)

CONTENTLET EDIT SCREEN AFTER DRAG AND DROP
![image](https://user-images.githubusercontent.com/49727631/107555653-0dc53e80-6b9d-11eb-9d24-8da6612c24b7.png)

PAGE EDIT SCREEN AFTER CHANGING IMAGE
![image](https://user-images.githubusercontent.com/49727631/107555701-1b7ac400-6b9d-11eb-965a-84042da524c8.png)

FRONT END VIEW OF THE PAGE AFTER CHANGING IMAGE (NOTE ALL FIELDS MISSING)
![image](https://user-images.githubusercontent.com/49727631/107555756-2cc3d080-6b9d-11eb-892a-e5fc39744b0c.png)

CONTENT->SEARCH - IMAGE WAS UPLOADED AS dotASSET, NOT FILE
Note that the first image was uploaded as a "File" and the drag/dropped file was uploaded as a "dotAsset"
![image](https://user-images.githubusercontent.com/49727631/107555885-5250da00-6b9d-11eb-8a62-f918f92ee45a.png)

**Comment by john-thomas-dotcms** [comment]
So, to be clear, the problem is not just that the image which was dropped won't display - it's that, after adding the image using drag-and-drop, the entire content item won't display.

**Comment by dsilvam** [comment]
Passed Internal QA: Followed steps in the description and working as expected.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF
