### ISSUE TITLE
Automatically delete old ES indices (indexes)

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19931]
**Is your feature request related to a problem? Please describe.**

Customers regularly have issues with a large number of old ES indices causing performance slowdowns.  In addition, older indices sometimes cause more serious issues, such as in this ticket: https://dotcms.zendesk.com/agent/tickets/103543

Inactive indices still consume file handlers and other OS resources.  And it's extremely rare that any index more than 3 reindexes back is ever actually used.

**Describe the solution you'd like**

Add a feature to automatically clear out old indices.  This could be done a number of ways, including:
* Set a maximum number of non-active indices to store

Non-active indexes over the limit, or older than the specified date, would be automatically deleted (meaning it would happen in the background, with no user action required).

It would make sense to have a notification message in both the log and when old indexes are deleted (like how we have a message now when a reindex completes).

We need a stateful job that runs once a day to pull a list of indexes and delete any of these unused indexes.

1. We should never delete any indexes listed in the `indicies` table, nor should we delete any site search indexes.
2. `MAX_INACTIVE_INDEX_SETS_TO_KEEP=2`.  This would keep the active indexes (always keep the active) and keep the previous live+working indexes.    Anything beyond that would be deleted.  We default to 2.

**Describe alternatives you've considered**

Right now, the only solution is to periodically manually delete the old indexes one-by-one.  In addition to this requiring manual work (which can easily be missed), it's also time-consuming.

**Additional context**

The ideal solution would be to set a maximum size limit on old indices.  When the limit is reached, the oldest indexes are deleted, until the total index size is under the limit again.

**Comment by bryanboza** [comment]
We have pending the UI notification, since we are deleting something we need to let the end user about that.

**Comment by john-thomas-dotcms** [comment]
I don't think we need a UI notification.  This isn't like an active delete; it's a scheduled trim of no-longer-used data, controlled by config.

So, we do need log messages.  But a notification may confuse more than it helps.

**Comment by wezell** [comment]
@dsilvam @bryanboza I agree with John - we don't need a notification here, just a distinct log message.

**Comment by dsilvam** [comment]
@bryanboza restoring the Passed Internal QA based on the comments above.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
