### ISSUE TITLE
Allow users to disable drag-and-drop into TinyMCE (WYSIWYG fields)

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19956]
**Is your feature request related to a problem? Please describe.**

Customers are asking for the ability to disable drag-and-drop of images into WYSIWYG fields, as in this ticket: https://dotcms.zendesk.com/agent/tickets/103519

The use of drag-and-drop can bypass the normal controls customers put in place through their TinyMCE configuration.

**Describe the solution you'd like**

Add a Field Variable to allow disabling drag-and-drop in WYSIWYG fields.

**Describe alternatives you've considered**

Although this could also be performed through a configuration property or other means, that would mean that, to configure WYSIWYG fields, customers would have to configure things in different places (`tinymceprops` field variable and configuration property) - so it would be best if this could be configured via Field Vars, to keep the config consistent.

**Comment by wezell** [comment]
@john-thomas-dotcms  this config disallow DND on both the wysiwyg and the wysiwyg image selector popup?  Or just the wysiwyg?

**Comment by john-thomas-dotcms** [comment]
The WYSIWYG itself was the main concern.  I'm honestly not sure how to handle the file selector popup - seems like that shouldn't matter as long as users are selecting the dotCMS site/folder in the popup normally, and just using DND to select the local file to upload.

Ultimately, the purpose is to prevent users from bypassing the TinyMCE config.  But if users can select files from their local disk, DND to select files shouldn't bypass anything, so that should be OK (I think).

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21578/files

**Comment by alfredo-dotcms** [comment]
Note to QA & doc: To disable D&D a **field variable** called `drag-and-drop` must be set to `false`.

![image](https://user-images.githubusercontent.com/37185433/150438454-5812c176-94e7-49a2-8059-a5925fcf6365.png)

**Comment by fabrizzio-dotCMS** [comment]
Works just fine.

**Comment by bryanboza** [comment]
Fixed, now we are able to add this propertly and disable the D&D functionality. Tested on release-22.03 // Docker // FF

**Comment by wezell** [comment]
Please convert the variable to camel case, e.g. `dragAndDrop`

**Comment by alfredo-dotcms** [comment]
Note to QA: now the variable name is called `dragAndDrop`

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21776/files

**Comment by fabrizzio-dotCMS** [comment]
Tested again using the camel-cased var `dragAndDrop`

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 and now the only way to this property work is using the camel-case `dragAndDrop`.
