### ISSUE TITLE
Date time field, should respect the time zone from format or company

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#19951]
Currently, dotcms is not respecting the timezone set in the Configuration (Configuration > Basic Config > Locale), for example, if I set the locale to **EST** and I add a new contentlet in another place in the world where the timezone is diff, let's say **GMT-6 (Costa Rica)** the timezone of the server should be respected and the date should be parsed to this timezone.

Steps to Reproduce:

1. Change the server locale to **EST**
2. Create a new ContentType with a text and date/time field.
3. Create a new contentlet.
4. If you are in the EST timezone the time shouldn't change, but if you are outside the timezone the time in the contentlet should be diff than the provided.

Additionally, if a user sends the contentlet via REST API this needs to be parsed as well.

Steps to Reproduce, using the content Type created above:

1. Create a new contentlet:
```
PUT {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH
{
    "contentlet": {
       "contentType":"myStructure1",
       "title":"testingContentlet", 
       "publishDate":"03/11/2021 17:30:00"
    }
}
```
2. If you are in the EST timezone the time shouldn't change, but if you are outside the timezone the time in the contentlet should be diff than the provided.

**Comment by jdotcms** [comment]
With this change, this is now possible:
```

<content> 
<stName>RestApiTestEmergencyNotice</stName>

<title>foreWarn Message</title>

<message>&lt;p&gt;BU foreWarn - TEST - This is a TEST of the Bradley University foreWarn emergency notification system. This is only a TEST.&lt;/p&gt; </message>

<publishDate>2021-02-10 13:17:36 GMT +1400</publishDate>

<displayOnHomepage>3</displayOnHomepage>

</content>
````

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/19954/files)

**Comment by jdotcms** [comment]
To test you can do
1) create a content type

RestApiTestEmergencyNotice
    - title: txt
    - message: txt
    - publishDate: date
    - displayOnHomepage: txt number

do a PUT
put {{serverURL}}/api/content/publish/1

```
<content> 
<stName>RestApiTestEmergencyNotice</stName>
<title>foreWarn Message</title>
<message>&lt;p&gt;BU foreWarn - TEST - This is a TEST of the Bradley University foreWarn emergency notification system. This is only a TEST.&lt;/p&gt; </message>
<publishDate>2021-02-10 13:17:36  GMT +1400</publishDate>
<displayOnHomepage>3</displayOnHomepage>
</content>
```

The time zone should be translated to the resulting date

**Comment by fmontes** [comment]
I tested with the following values:

- Send this `"2021-02-10 13:17"` and DotCMS returns in the API `"2021-02-25 11:49:03.914"`
- Send this `"13:17"` and DotCMS returns in the API `"2021-02-25 11:49:50.421"`
- Send this `"10/10/22"` and DotCMS returns in the API `"2021-02-25 11:50:44.301"`

**Comment by erickgonzalez** [comment]
```
do a PUT
put {{serverURL}}/api/content/publish/1

<content> 
<stName>RestApiTestEmergencyNotice</stName>
<title>foreWarn Message</title>
<message>&lt;p&gt;BU foreWarn - TEST - This is a TEST of the Bradley University foreWarn emergency notification system. This is only a TEST.&lt;/p&gt; </message>
<publishDate>2021-02-10 13:17:36  GMT +1400</publishDate>
<displayOnHomepage>3</displayOnHomepage>
</content>
```

This is wrong, this endpoint was deprecated 2 years ago. We should be using the **workflow** endpoint e.g:
```
{
    "contentlet": {
       "contentType":"myStructure1",
       "title":"GMT-6 v2", 
       "publishDate":"17:30:00 GMT -06:00 "
    }
}
```

And it's not working, it should set the Time to `11:30:00`

**Comment by bryanboza** [comment]
We need to add some postman test here...

**Comment by bryanboza** [comment]
Fixed
