### ISSUE TITLE
Smart Push Publishing Retry

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19965]
### Is your feature request related to a problem? Please describe.

When you push a bundle and it fails, dotCMS automatically retries the bundle.  But there are some kinds of PP errors (like integrity issues) which simply will not succeed on a retry - so the retry just sucks up network bandwidth and fills up the logs, with no chance of actually succeeding.

### Describe the solution you'd like

1. When a PP bundle fails to publish, change the retry behavior, based on the type of error received.  For example:

* If there's a network error, or if the receiver returns a hibernate error, the sender should attempt to send the bundle again (and the retry count should be respected).
* But if the receiver returns an error related to integrity or bad data in the bundle, the sender should not attempt to retry the bundle at all.

2. In the PP queue AND the popup message, distinguish between bundles that will (or are being) retried, and those that have finally failed.

Right now, when a bundle fails, 2 things happen:
* A popup message (growl) appears saying the bundle failed.
* The queue shows "Failed" for a period of time, and then the bundle is eventually retried.

Since customers see that the bundle failed, it's very common for them to manually attempt to re-push the same content again (creating a new bundle and adding it to the queue).  This causes the same content to be in 2 different bundles, which slows performance (because now both bundles repeatedly retry) - especially if the bundle is large, or the reason for the failure is one that will not be resolved by re-pushing the bundle.

Ideally:
* The growl should say the the bundle failed, but will be retried another X times.
* The PP queue status should show as `Failed...Retrying` instead of just `Failed`.

### Additional context

Push publishing issues make up about 1 out of every 7 support tickets.  Some relatively small changes in the PP queue functionality could reduce the number of issues customers report, and significantly speed up the time it takes to isolate and resolve push publishing issues (for both our own support team, and for customers to help themselves).

**Comment by erickgonzalez** [comment]
@john-thomas-dotcms right now the growl notification will only appear at the end of the retries. I think we discussed this when implementing and agree that a growl notification in every failure until it reaches the max of retries was going to be too noisy.
