### ISSUE TITLE
Create a Host Integrity Checker

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19967]
If we move to the idea of a hostName acting as the site key for various functionality, such as apps, push publishing and to calculate known ids based on asset paths, we will need to be able to check if the hostname/host.identifiers match between two environments.  In order to do this we should have an integrity checker than verifies that the hostNames+ids match and if not, allow an administrator to fix either locally or remotely.

**Comment by victoralfaro-dotcms** [comment]
PRs:
https://github.com/dotCMS/core/pull/20966
https://github.com/dotCMS/core/pull/21213

**Comment by dsilvam** [comment]
Passed Internal QA:
Fixing conflicts both at the sender and the receiver and then successfully push publishing. Test from master to demo.

**Comment by bryanboza** [comment]
We have a SQL error trying to fix conflicts when the site have data. 
https://gist.github.com/bryanboza/759587eb9906a262463941cd3ee1a82f

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // MSSQL 

Now we are able to fix site conflicts locally and remotely without problems
