### ISSUE TITLE
Release automation pending actions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19969]
* Publish "GitHub Releases" in the other repos. I.e. `enterprise`, `core-web`, `plugin-seeds`, `docker`, `dot-cicd`
   For all of them except the tag points to `release-YY.MM`. Tag name convention is `vYY.MM`, release description is `YY.MM Release`

* ~Empty commit to master branch of `https://github.com/dotCMS/demo.dotcms.com` repo to kick start the upgrade to the lastest dotcms docker image~ Not implemented for now

* Slack message to #dotcms channel announcing the release

**Comment by wezell** [comment]
Slack message - "This automated script is excited to announce the release of a new version of dotCMS - dotCMS v.xxxx"

**Comment by dsilvam** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1651

**Comment by dsilvam** [comment]
Passing QA based on the feedback from the automation process
