### ISSUE TITLE
Performance issues with GraphQL under load

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19974]
There are a few bottlenecks to graphql calls when a server is under extreme load.  

The first is that the `DotTransformerBuilder`, which converts a contentlet to a map.  When the looks up the strategy to use, it , does a `Config.getStringProperty` which calls down to Apache's property file impl.   Turns out Apache's impl blocks when it tries to reload the properties from the filesystem.  This causes the DotTransformerBuilder and thus GraphQL to block until the file can be re-read from the filesystem.

![Screen Shot 2021-02-19 at 10 03 46 PM](https://user-images.githubusercontent.com/934364/108606601-f2bab180-7388-11eb-8273-6b706c5a2c81.png)

Secondly, the `ContentType.fields(String fieldVar)` does a String.replace to normalize the class names and remove the `Immutable` portion of the name.  Turns out String.replace is a regex, which has to compile, etc..  This has performance implications under load.  Instead of this, we need to just to a simple string replace (indexOf, substring etc..)

![Screen Shot 2021-02-20 at 2 38 11 PM](https://user-images.githubusercontent.com/934364/108606667-4a591d00-7389-11eb-9077-b416ccf264ff.png)

**Comment by swicken-dotcms** [comment]
Change relies on files that do not exist yet in 5.2.8, excluding this fix from LTS release.
