### ISSUE TITLE
Automation of the Code-freeze / Release branch creation

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19971]
Currently there's a [script](https://github.com/dotCMS/dev-scripts/blob/master/scripts/create_push_release_branch.sh) that covers pretty much all the steps but it relies on already cloned github repos and it's fragile to local mods (jdk version, npm versions, among others) . 

This script needs to run on Docker, in a Github Workflow that gets fired manually, same as our Workflow for publishing Docker images

**Comment by victoralfaro-dotcms** [comment]
PRs:
https://github.com/dotCMS/dot-cicd/pull/32
https://github.com/dotCMS/core/pull/20779
