### ISSUE TITLE
Add static cache to Graphql

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19981]
Customers using GraphQL can write really heavy queries- requesting thousands of results that recurse to related content and include asset metadata.  When querying GraphQL, we need a way to cache the results to ensure consistant performance. 
 We need to add a  `cacheTTL` property that the user can provide to cache  the queries results.  When this is specified, the query should be run then stored for the TTL time.  Subsequent identical queries should return the same data from cache, instead of generating it every time.

We need to get with @fmontes and our front end devs to figure out how this should work and how we can make it work easiest with the apollo graphql js client

We should take the params either using the `request.getParameter` or `request.getHeader`

- `dotcachettl` - the cache will have a default ttl, this will override it. We should use a Tuple2 to store the cache response and the expire time. If cacheTTL is <=0, then live results are returned.
- `dotcachekey` optional - if not set, would be the hash of the query and params.  If set, this would force the cache lookup and put to be based on this key

We will have to set up a default cache region in our config - I would say we use the Expiring cache and hold 5000 responses for 10m.

This is an ee only feature.

A prototype of the cache behavior can be found here, though it needs some work to be added to the core code base:

https://github.com/dotcms-plugins/com.dotcms.graphql.cache

**Comment by wezell** [comment]
So `dotcachettl=0` will be no-cache and `dotcachettl=-1` will do a cache.remove on the key

**Comment by wezell** [comment]
We need to allow for "dirtyReads" or refresh async that will still return an expired result while the new result is being built and added into cache.

**Comment by dsilvam** [comment]
**Note to QA/Doc:** 

The GraphQL Cache is an expiring cache that can be controlled by different configuration options. 

**Setting TTL by config property**
The cache region comes configured as a TimedCacheProvider and it ships with a default TTL of 15 seconds which means a successful GraphQL response (code 200) will be cached for that time. 
To change it set `cache.graphqlquerycache.seconds` to the desired time. This config is present in the `dotmarketing-config.properties` file.

**Setting TTL at request time**
When this method is planned to be used is recommended to have a long TTL configured in the cache region so it doesn't mess with the desired behavior (i.e., invalidations when not expected). A recommended practice is to set the `cache.graphqlquerycache.seconds` at least twice the maximum TTL you want to set at request time. 

The request time TTL can be set by sending `dotcachettl` argument either as request parameter or request header
This argument has two special values: 
* 0: Bypasses the cache
* -1 (minus 1): bypasses the cache and clears this entry for the given key/query 

**Cache Key**
By default the cache key is the GraphQL query itself. A custom key to be used instead can be specified at request time by providing the argument `dotcachekey` either as a request parameter or request header. 

**Refresh in background**
By providing the request time argument `dotcacherefresh` dirty reads from cache are allowed while a background cache refresh for the given query (or custom key) will take place. This argument can also be sent as a request parameter or request header.

**Comment by bryanboza** [comment]
Fixed, tested based on the provided examples and it is working as expected. Tested on docker // release-21.11 // FF

**Comment by swicken-dotcms** [comment]
Excluding from LTS releases as the changes are too extensive
