### ISSUE TITLE
Backend broken fonts when no internet access

### ISSUE THREAD

**Issue by manuel-miranda** [dotCMS/core#19980]
**Is your feature request related to a problem? Please describe.**
Fonts needs to be downloaded when starting dotCMS, if there is no internet access like an intranet, backend fonts and labels are broken.

**Describe the solution you'd like**
Get the required resources or fonts (in this case) deployed in the release.

**Describe alternatives you've considered**
Get internet access but for some scenarios this is not possible, whatever reason (security, compliance, etc.)

**Additional context**
![image](https://user-images.githubusercontent.com/29102758/108741102-fb7fc480-74fb-11eb-9d9e-9fe5de3931ef.png)

**Comment by wezell** [comment]
Dupe #20431

**Comment by fmontes** [comment]
You can download google fonts and generate css with this tool: https://google-webfonts-helper.herokuapp.com/fonts

**Comment by hmoreras** [comment]
PR's: 
https://github.com/dotCMS/core-web/pull/1670
https://github.com/dotCMS/core/pull/20473
 https://github.com/dotCMS/dotcms-dojo-theme/pull/81/files

**Comment by fmontes** [comment]
Broken fonts.

<img width="1274" alt="Screen Shot 2021-06-08 at 1 39 38 PM" src="https://user-images.githubusercontent.com/751424/121247195-30234c00-c85f-11eb-896d-b8d526c10926.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
