### ISSUE TITLE
Unable to add fields to content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19987]
When you try to add a new filed to a content type, we are getting a JS error and we are unable to add the field 
![image](https://user-images.githubusercontent.com/2641437/108775967-60044900-7527-11eb-99e2-f6c8454e4093.png)

**To Reproduce**
- Login as admin 
- Create a new content type 
- Try to add a text filed 

**Expected behavior**
We need be able to add fields without problems 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core-web/pull/1593

**Comment by dsilvam** [comment]
Passed Internal QA: Able to add fields to new and existing content types

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
