### ISSUE TITLE
NPE trying to add a page to a site that does not have templates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19999]
When you try to add a new page to a blank site or any other that doesn't have templates, we are getting a NPE error and we are unable to add the page because the templates checkbox is empty 
![image](https://user-images.githubusercontent.com/2641437/108924669-ae394b00-7600-11eb-8237-69828770d003.png)

**To Reproduce**
- Login as admin 
- Create a new site 
- Select this site 
- Try to add a new page 

**Expected behavior**
We need be able to allow use templates from another sites and create the page without problems 

**Desktop (please complete the following information):**
Tested on release 21.03 // Postgres // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20003

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02.2 // Postgres // FF
