### ISSUE TITLE
Can't logout when close the tab

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19991]
**Describe the bug**
When you close a logged in tab and open it again you can't logout

**To Reproduce**
https://user-images.githubusercontent.com/751424/108870803-17e43580-75be-11eb-8b31-972c7d236f0e.mov

**Expected behavior**
It should log out normally

**Comment by dsilvam** [comment]
Passed Internal QA: Able to log out after the steps in the video

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postges // Safari... Now I'm unable to reproduce following the provided steps
