### ISSUE TITLE
UX: Welcome portlet: Redirection problems using the links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20000]
When you are navigating on this portlet and try to use one of the links, we are opening a modal in order to add a new piece of content, if you add a new piece of content we are redirecting to the content portlet which is ok, but if you accidentally click in the wrong link and just close the modal, we need to bring back into the same portlet. 

**To Reproduce**
- Login as admin 
- Enable the option to show this portlet 
- Using this one, try to add a new piece of content
- Close the modal without add anything. 
- We are redirecting to the content portlet 

**Expected behavior**
We need brick back into the same portlet if you don't add anything, this because if you click in any link accidentally and close this, does not make sense two or three more clicks to bring back into the portlet gain 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by fmontes** [comment]
As per @fishsmith this is good this way.
