### ISSUE TITLE
UX: Welcome portlet: Needs a confirmation to remove this portlet from the list 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20001]
Since the "Don't show this again" checkbox is an operation that removes a portlet from the list, we need a confirmation message here, in to inform to the end user that this will remove the portlet from the list and make sure they are agree with this and is not clicking here by mistake 
![image](https://user-images.githubusercontent.com/2641437/108926240-96af9180-7603-11eb-8231-29d94abca5eb.png)

**Expected behavior**
Need a confirmation message to make sure the end user is agree with this, and after conform this, we need to hide this field. 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by wezell** [comment]
This is ok - as it is non-destructive.  The user can reenable the portlet from the "My Account" modal
