### ISSUE TITLE
Drag fields in content types are not sticking to the cursor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20015]
**Describe the bug**
When you try to D&D a field you can't see the element stuck to your cursor

**To Reproduce**
1. Go to content types
2. Edit one
3. Try to add a field
4. See that the field is not stuck to your cursor

**Additional context**
We need the dragula classes in the component
https://github.com/dotCMS/core-web/blob/2fb1356f22a3599b2ff4a072eb1bc1a7364412c3/src/app/portlets/dot-edit-page/content/services/html/libraries/dragula.css.ts

**Comment by bryanboza** [comment]
Foxed, tested on release 21.03 // Postgres // FF
