### ISSUE TITLE
Theme selection modal editing the page layout is broken 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20011]
When you are editing a page and try to edit the layout, we are having some problems when you try to select the theme and you are in a site that don't have themes 

**To Reproduce**
- Login as admin
- Make sure you are in a EE edition 
- Create a new blank site 
- Add a new page on this site 
- Edit the page layout and try to change the theme 

**Expected behavior**
We need be able to change the site in a selector and find for themes without problems 

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/109067430-201e9c80-76b4-11eb-9ff5-4d3224d34796.png)

**Desktop (please complete the following information):**
Tested on release-21.02.2 // Postgres // Safari

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02.2 // Postgres // FF

**Comment by bryanboza** [comment]
Tested on release-21.03 and we are not refreshing property this component, need to type anything in order to refresh and show the multiples sites.

**Comment by fmontes** [comment]
@bryanboza this is not merged into 21.03 yet, ask @dsilvam when he's merging it.

https://github.com/dotCMS/core-web/pull/1598

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
