### ISSUE TITLE
Auto scroll while dragging fields in the content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20020]
**Is your feature request related to a problem? Please describe.**
We need to autoscroll the content type layout when the user is dragging a field and get close to the bottom or top

**Describe the solution you'd like**
We can use the same we use in edit mode

**Additional context**
We need this library: https://www.npmjs.com/package/dom-autoscroller

Here is a demo: https://codepen.io/michaelbowlin/pen/GxVwvM

And here how we did it in edit mode https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/content/services/html/libraries/iframe-edit-mode.js.ts#L135

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1615

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
