### ISSUE TITLE
JS Error when removing and adding containers to a template

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#20021]
Reproducible in dotCMS 21.01

A JS error can happen when adding and removing containers in the template designer.

**To Reproduce**
1. Go to the template designer to create a new template.
2. Add 3 rows to the template, and add one container to every row.
3. Remove the second row
4. Click ' Add Row' to add another row
5. One of the 2 existing rows doesn't show anymore, and a JS error is shown in browser console:
```
build.js?b=21.01:2 dojo/parser::parse() error Error: Tried to register widget with id==select_splitBody2 but that id is already registered
    at Object.add (VM3617 build.js:2)
    at Object.create (VM3617 build.js:2)
    at Object._19a (VM3612 dojo.js:2)
    at Object.create (VM3617 build.js:2)
    at Object.postscript (VM3617 build.js:2)
    at new <anonymous> (VM3612 dojo.js:2)
    at Object.construct (VM3617 build.js:2)
    at Object.<anonymous> (VM3617 build.js:2)
    at Object.map (VM3612 dojo.js:2)
    at Object._instantiate (VM3617 build.js:2)
(anonymous) @ build.js?b=21.01:2
_2ed @ dojo.js?b=21.01:2
then._2fa.then @ dojo.js?b=21.01:2
otherwise @ dojo.js?b=21.01:2
parse @ build.js?b=21.01:2
addRow @ layout?p_l_id=b7ab5d3c-5ee0-4195-a17e-8f5579d718dd&p_p_id=templates&p_p_action=1&p_p_state=maximized&angularCurrentPortlet=templates&p_p_mode=view&_templates_struts_action=%2Fext%2Ftemplates%2Fedit_template&_templates_cmd=design&_templates_referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3Db7ab5d3c-5ee0-4195-a17e-8f5579d718dd%26p_p_id%3Dtemplates%26p_p_action%3D1%26p_p_state%3Dmaximized%26angularCurrentPortlet%3Dtemplates%26_templates_pageNumber%3D1%26_templates_struts_action%3D%252Fext%252Ftemplates%252Fview_templates:437
eval @ VM6163:3
_onClick @ build.js?b=21.01:2
_19a @ dojo.js?b=21.01:2
_onClick @ build.js?b=21.01:2
(anonymous) @ dojo.js?b=21.01:2
(anonymous) @ build.js?b=21.01:2
```

**Expected behavior**
Containers should be added or removed without JS errors.

**Screenshots**
Template created with 3 rows:
![image](https://user-images.githubusercontent.com/2894221/109360130-48d99a00-784c-11eb-8d06-e8db63a49243.png)

Removed second row from the template:
![image](https://user-images.githubusercontent.com/2894221/109360182-5d1d9700-784c-11eb-96c3-a7e7879ac8d2.png)

Added one row after removing second row:
![image](https://user-images.githubusercontent.com/2894221/109360264-7e7e8300-784c-11eb-8b8b-4e0ad1b5c69f.png)

**Comment by wezell** [comment]
The "designed template" portlet and issue does not exist in the latest release.
