### ISSUE TITLE
Template portlet: extra requirements

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20028]
1. When you hit `SAVE` we don't redirect to the listing
2. We need to add the message for "Loading..." and "Saved" when user clicks the "SAVE" button.

**Comment by hmoreras** [comment]
Edit was not showing due a previous commit. fix https://github.com/dotCMS/core-web/pull/1616/files

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
