### ISSUE TITLE
Delete a used template from the three dots fail

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20029]
**Describe the bug**
If you try to delete a template that has a page assigned to it from the three-dot button in the listing, you get an error in the console.

**To Reproduce**

https://user-images.githubusercontent.com/751424/109720265-7a65a480-7b6f-11eb-90b0-e2c0a9ca5cb5.mp4

**Expected behavior**
It should show the message no matter where is getting delete it from.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1609

**Comment by bryanboza** [comment]
Fixed, tested on release 21.03 // Postgres // FF. Now this is working as expected
