### ISSUE TITLE
Task details: We lost the file icons when you attach a file to a piece of content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20047]
When you use the task portlet to see the task details to some piece of content that is executing a workflow, if you attach some file we are losing the icon, also if you click on it we are unable to open this file. 
![image](https://user-images.githubusercontent.com/2641437/110152667-a4091080-7da7-11eb-9fea-b9d0ffe8e845.png)

**To Reproduce**
- Login as admin 
- Got o the task portlet 
- Open any piece of content that is executing this WF 
- Attach some file 

**Expected behavior**
We need be able to see the icon of the file extension, also if you click <s>we should open this file</s> on `Remove` button we should remove the file

**Desktop (please complete the following information):**
Tested on release -21.03 // Postgres // FF

**Comment by nollymar** [comment]
Passed internal QA

<img width="1510" alt="Screen Shot 2021-07-30 at 4 05 36 PM" src="https://user-images.githubusercontent.com/8741395/127711450-3ba6e613-4988-438b-87b7-0352eb74d3db.png">

**Comment by bryanboza** [comment]
Seems we lost something here, If you try to attach some file we are unable to see the icons in grid view, we are getting this 
![image](https://user-images.githubusercontent.com/2641437/129952182-60edde79-80fe-44c7-90bf-ba6a002c5be7.png)
 
We need some work here 

Tested in docker // Image: 21.09_0712a84

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF.  Now the icons looks ok
