### ISSUE TITLE
Unable to add containers as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20059]
If you set permissions to a limited user to add containers in some specific site, when you try to add a new one we are getting a JS error and you can't add the containers because at UI level we get just a blank page 
![image](https://user-images.githubusercontent.com/2641437/110359249-e1b5a580-8002-11eb-8ad8-c3d471ae9a0b.png)

**To Reproduce**
- Login as admin
- Go to the site permissions 
- Add permissions to some limited user to add containers (Chris Publisher)
- Login as this user and try to add a container 

**Expected behavior**
We need be able to add containers without problems if you have the correct permissions 

**Screenshots**
Here the permissions in the site: 
![image](https://user-images.githubusercontent.com/2641437/110359436-1a557f00-8003-11eb-8b37-06a87c2a329c.png)

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by wezell** [comment]
Not ideal but not a blocker I don't think.  Can a non-admin still use the containers be used in a custom layout

**Comment by bryanboza** [comment]
Yes, we are able to use the containers from the layout stuff without problems. Seems the problem is only adding new ones
