### ISSUE TITLE
Anonymous users cannot fire actions when specified by their identifier

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20053]
**Describe the bug**
Anonymous users cannot fire specific actions when you make a call to the workflow API and use the specific action ID to execute that action. Default actions can be used by anonymous users without issue. 

Ticket: https://dotcms.zendesk.com/agent/tickets/103557
dotCMS Version: 21.02.2

**To Reproduce**

1. On the demo starter, modify script.js in the travel theme. At the bottom of the file, change the JavaScript that submits a blog comment to:

```javascript
	// ADD COMMENT
		$("#webup").submit(function(e) {
			e.preventDefault();
			  var pageUrl = $( "#returnUrl" ).val();
			  var dataObj= {
				'contentlet': {
				  'title': 'Re: ' + $( "#blogTitle" ).val(),
				  'contentHost': 'demo.dotcms.com',
				  'contentType': 'BlogComment',
				  'blog': $( "#blogId" ).val(),
				  'postDate': $( "#todayDateTime" ).val(),
				  'commentAuthor': $( "#commenterId" ).val(),
				  'body': $( "#commentBody" ).val(),
				  }
			  };
			  console.log(dataObj);
			  
			  $.ajax({
				  url: '/api/v1/workflow/actions/b9d89c80/fire',
				  type: 'PUT',
				  contentType: 'application/json',
				  cache: false,	
				  data: JSON.stringify(dataObj),
				  beforeSend: function (request){
				  // This sends the user who authenticates against the dotCMS server
				  // In a real world example, you could use session based authentication
				},
		   
				success: function(data,status,xhr) {
				  window.location = pageUrl;
				},
				error: function(data,status,xhr) {
				  console.log(data);
				},
			}); //ajax
		}); //webup
```
2. Load up the page and go to a blog post. Attempt to make a comment and you will see an error in the console stating '401 Invalid User'

**Expected behavior**
Anonymous users should be able to check-in contentlets should they have the right permissions for that content type by calling the action by ID.

**Comment by bryanboza** [comment]
Fixed, tested using the provided postman tests and now it works as expected
