### ISSUE TITLE
[dev] : The "deployWarTomcatDev" task is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20057]
Found when working on Support tickets.
Reproducible as of dotCMS 5.3.8.2, and latest master.

The `deployWarTomcatDev` is not working.

**To Reproduce**
1. Set up a local dev environment, run `./gradlew clean deployWarTomcat` and start up dotCMS. This works as expected.
2. Stop dotCMS, run `./gradlew deployWarTomcatDev`, and start dotCMS again.
3. Inspect the logs, and you'll see a high number of errors, and dotCMS not starting correctly.

**Expected behavior**
The Gradle task should work as expected.

**Additional context**
This task saves a lot of time when we need to debug code in EE. It'd be great to have it working again.

**Comment by wezell** [comment]
No customer should be developing from source.  We should remove this task and just tell people to run  `deployWarTomcat`.  and turn on debugging OR better yet, give a quick docker example of how to turn on remote debugging in a docker install.  It is super easy and straightforward.
