### ISSUE TITLE
Send Cookies Secure and HttpOnly

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20063]
When sending cookies, we only want to send cookies that have the secure flag set and the httponly flag set properly.

HttpOnly should be set on all cookies.

The secure flag should be set on Cookies that are set securely.

**Comment by wezell** [comment]
You can test by hitting dotCMS locally
```
curl --head https://local.dotcms.site:8443
```

**Comment by victoralfaro-dotcms** [comment]
Sent cookies:
```
$ curl --head https://local.dotcms.site:8443
HTTP/1.1 404
Strict-Transport-Security: max-age=3600;includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: JSESSIONID=CAF56B29EAC5FDBBE1BA5323005E101C; Path=/; Secure; HttpOnly; SameSite=Strict
vary: accept-encoding
Content-Type: text/html;charset=ISO-8859-1
Transfer-Encoding: chunked
Date: Tue, 09 Mar 2021 18:48:19 GMT
```

**Comment by bryanboza** [comment]
Fixed, now we have all those cookies in the response. Tested on release-21.03

**Comment by swicken-dotcms** [comment]
Removed from 5.2.8.5 after discussion regarding it being a potentially breaking change for scripts.
