### ISSUE TITLE
Time penalization in wrong login attempts is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20075]
By security, we have a time penalization every time that you try to login with a wrong user or password, and this is an incremental value in seconds, but this is not incrementing after many wrong attempts 

**To Reproduce**
- Start your dotCMS instance 
- Try to login with a wrong password 
- Try again with the same credentials
- Make every time you try with a wrong value the time penalization is incrementing 

**Expected behavior**
We need to increment this value in every attempt 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by wezell** [comment]
This was changed on purpose because it got too big too quick - we had accounts that would spin for minutes.  I believe right now we are waiting 2 seconds by default which should be enough to honeypot any brute force attackers
