### ISSUE TITLE
System Template

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20071]
We need to implement **Templates as a File**, those templates will live under `application/templates/` and have the following files:
* **Properties.vtl**:
```
$dotJSON.put("title", "System Template")
$dotJSON.put("friendly_name", "The System Template...")

## This properties only if is a Design Template
$dotJSON.put("theme", "system_theme")
```

* If it is an Advanced Template **Body.vtl** e.g
```
#parseContainer('/application/containers/banner/','1615825205295')
   
```
* If it is a Design Template **layout.json** e.g (this is the system template)
```
{
      "body":{
         "rows":[
            {
               "styleClass":"",
               "columns":[
                  {
                     "styleClass":"",
                     "leftOffset":1,
                     "width":12,
                     "containers":[
                        {
                           "identifier":"//default/application/containers/system/",
                           "uuid":"1"
                        }
                     ]
                  }
               ]
            }
         ]
      },
      "header":true,
      "footer":true,
      "sidebar":null
}
```

System Template will be shipped in the empty starter and will be a Design Template as a file.

When a new page is created and there is no `Default Template` available, the page should default to `SYSTEM_TEMPLATE`. 

The SYSTEM_TEMPLATE should show the header/footer and have 1 full with a row with the system_container in it.

We need to test PP of Templates as a File.

Design Template as a File should support layouts?? **YES**

When creating a page that uses a Template as a File, the template Id should be saved as a Path.

**Comment by fmontes** [comment]
Yes, it should support layouts.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20138
PR EE: https://github.com/dotCMS/enterprise/pull/789

**Comment by fmontes** [comment]
When you create a page with a system template the layout have the container id `/application/containers/system/` but the container id is: `//default/application/containers/system/`

**Comment by erickgonzalez** [comment]
Fixed with the new starter
