### ISSUE TITLE
Implement the inline editing in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20082]
## Description
In the inline edit at the field level.

## Design
https://github.com/dotcms/core/issues/20081

## Context

We are going to ask the dev to add custom data attributes in the fields they want to inline edit.

```html
<p 
    class="banner-title"
    #if ($EDIT_MODE) 
        data-mode="minimal|full"
        data-inode="${IDENTIFIER_INODE}"
        data-field-name="title"
        data-language="${CONTENT_LANGUAGE}"
    #end
>
        $title 
</p>
```

We need to get that attr to allow users to edit and hit the endpoint and save the content.

## TinyMCE
We are going to initialize tinymce in inline mode

We can get the library from

```
/html/js/tinymce/js/tinymce/tinymce.min.js
```

TinyMCE in inline mode demo: https://www.tiny.cloud/docs-4x/demo/inline/

## Error handling
1. All the errors will be shown in the **toast component**
2. If all the data attr are not in the element, when the user focus we show an error so they can ask their devs to fix it and we don't do anything else, request or events
3. The endpoint will return error messages when failed and we show them in the toast
4. Depending on how it fails the request, we should revert the changes

**Comment by fmontes** [comment]
The whole edit mode starts in this component `apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.html`

**Comment by fmontes** [comment]
### QA feedback

1. We create a issue to modify the endpoint we don't have to pass the content type since we are passing the inode: 
2. We need to catch errors in the blur events to make sure we don't crash the app.

**Comment by bryanboza** [comment]
Fixed, now this is implemented, some bugs reported but in different cards, We can pass this one. Tested on release-21.05 // Postgres // FF
