### ISSUE TITLE
Upgrade task to update icons

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20087]
**Is your feature request related to a problem? Please describe.**
We deprecated font-awesome from your system.

This means that all the clients that use icons with the prefix `fa-` in their tools will get no icon for the next upgrade.

**Describe the solution you'd like**
We need to check if the icon starts with `fa-` we change it to `label_important`

This way the customer will see a different icon but at least see something and will be able to go to change it.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20101

**Comment by bryanboza** [comment]
Fixed, now we have a default icon to every portlet after upgrade. 
![image](https://user-images.githubusercontent.com/2641437/114573813-f1de2780-9c35-11eb-9a8c-3ca0475978fa.png)
