### ISSUE TITLE
Edit mode: Inline editing 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20083]
## Is your feature request related to a problem? Please describe.
Allow users to edit content directly on the page in edit mode.

https://user-images.githubusercontent.com/751424/110978048-83e9cc00-8328-11eb-9a79-ead46a8b7bbb.mp4

## How it works
1. Customer adds some data attributes in the HTML inside the container or SPA to make a piece of the contentlet editable. For example, they can make editable the `title`
```html
<h1 
    #if ($EDIT_MODE) 
        data-language="${CONTENT_LANGUAGE}"
        data-mode="minimal"
        data-inode="${ContentInode}"
        data-field-name="title"      
    #end
>
    $!{title}
</<h1>
```
2. We write some JavaScript that will get all those HTML tags
3. On `click` or `focus` of any of those tags we init the inline editing process
    - Add `Save` and `Cancel` button
    - Hit the new endpoint to save the content
    - Update the DOM accordingly

## Additional context
1. We are creating a new endpoint for this functionality
2. We will support `ctrl + b`, `ctrl + i`, `ctrl + u` for extra html
3. We will use `contenteditable` feature

**Comment by fmontes** [comment]
Added inline editing in:

1. Home
2. Blog
3. Products detail

**Comment by bryanboza** [comment]
After play a little bit with this functionality we need some work here: 

- This is not working on Safari and IE  (need support all the browsers)
- We are not respecting If you try to add a new line  
https://user-images.githubusercontent.com/2641437/117032242-90eac200-acbe-11eb-8cbe-43e524d75cb8.mov
- We have error trying to edit some texts 
![image](https://user-images.githubusercontent.com/2641437/117032630-deffc580-acbe-11eb-8364-50d8d0fb421a.png)
- We are unable to edit the font type, just `bold, italic and underline` 
![image](https://user-images.githubusercontent.com/2641437/117032926-28e8ab80-acbf-11eb-98f0-08286618c9a6.png)

**Comment by fmontes** [comment]
> This is not working on Safari and IE (need support all the browsers)
- IE we don't support
- Safari is a bigger Safari thing, we created an issue with a refactor in the way we load all the libraries, out of this scope

> We are not respecting If you try to add a new line
- This is fine for our use case, the editor gets removed from the DOM on blur, so we just printing the HTML from the container, if the field is just text is going to work this way.

> We have error trying to edit some texts
- Fixed

> We are unable to edit the font type, just bold, italic and underline
- This is intentional, we have a basic and a full editor, this is the basic.

**Comment by fmontes** [comment]
Starter updated to fix the issue with the banner.
