### ISSUE TITLE
Create endpoint to update a field in specific inode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20080]
## Description
The general idea of inline editing is to allow users to update specific fields of a contentlet.

## Endpoint
We need an endpoint that will take:
2. inode OR identifier + language OR Query
2. Map<fieldVariable,Value>
3. Workflow Default Action [EDIT, PUBLISH, UNPUBLISH, DELETE]

And with that, it will load the working contentlet, update the contentlet by just updated the pass it field with the passed value.

## Consider
1. You need to make sure you update the right language (with the passed inode or with the identifier+lang)
2. This endpoint will then run the specified workflow action
3. Return the updated contentlet so we can update the DOM accordingly
4. Handle errors

## Errors
1. User don't have permissions
2. User try to set an empty value to a required field
3. Bad format, from the frontend we are only going to submit string (for version 1)
4. Other errors?

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/20115

**Comment by fmontes** [comment]
At the end of the day we didn't create a new endpoint we just used the workflows fire one but we upgraded so we don't have to pass a `contentType`, now the endpoint just get the content type from the inode.

**Comment by bryanboza** [comment]
Fixed, tested on releaase-21.05 // Postgres // FF
