### ISSUE TITLE
Static push publishing a page in the default language that uses pullRelatedContent with a language filter does not function

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20091]
**Describe the bug**
Static push publishing a page that is in the dotCMS instances default language that uses pullRelatedContent filtered to that language does not pull the related content. 
If you create pages using the same VTL file in other languages, these pull the related content without issue. 

Tested on: dotCMS 5.3.8.4

Related ticket: https://dotcms.zendesk.com/agent/tickets/103385

**To Reproduce**
1. Deploy a blank starter
2. Add a second language, Spanish (es)
3. Create a content type called `Test Content` with a title and a text field called `Language` 
4. Create a content type called `Test Related Content` with a title and a text field called `Language`
5. Create a one to many relationship on `Test Content` to `Test Related Content` called `Related Content`
6. Create 3 contentlets for `Test Related Content`, with the language field saying `English`. Create the ES (Spanish)
 versions of these contentlets with the language text field saying `Spanish` 
7. Create a `Test Content` with the language field saying `English` and relate it to all 3 of the `Test Related Content` contentlets you created in step 6.
8. Create the spanish version of the `Test Content Type` with the language field saying `Spanish`.
9. Create a vtl file in `application/vtl` called `test.vtl` with the following code
```vtl
#foreach($con in $dotcontent.pull("+contentType:TestContent +(conhost:8a7d5e23-da1e-420a-b4f0-471e7da8ea2d conhost:SYSTEM_HOST) +languageId:$dotPageContent.languageId",10,"modDate desc"))
    <h1>$con.title</h1>
    <p>$con.language</p>
    #foreach ($relatedField in $dotcontent.pullRelatedField("$con.identifier", "TestContent.relatedContent", "+languageId:$dotPageContent.languageId"))
        <p>$relatedField.title</p>
        <p>$relatedField.language</p>
    #end
#end
```
10. Create a template that parses that test.vtl file `#dotParse("//default/application/vtl/test.vtl")`
11. Create a directory called 'test', and in that directory create a English page called 'en-us' that uses the template you created.
12. In the same directory create a separate  Spanish page called 'es-us' that uses the same template. Do not use the same page and create a Spanish version, it must be separate.
13. Create a push publishing endpoint to a Static S3 bucket, and force push the test folder to it.

In the S3 Bucket you will see test/en-us and test/es-us

The content of en-us will be:
```html
    <h1>Content 2</h1>
    <p>English</p>
        <h1>Content 1</h1>
    <p>English</p>
```

The content of es-us will be:

```html
    <h1>Content 1</h1>
    <p>Spanish</p>
            <p>Related Content 2</p>
        <p>Spanish</p>
            <p>Related Content 1</p>
        <p>Spanish</p>
        <h1>Content 2</h1>
    <p>Spanish</p>
            <p>Related Content 3</p>
        <p>Spanish</p>
```

In the Spanish page, the related content is pulled, in the default language (English) the related content is not.

If the default language were Spanish (es), this behaviour would be reversed.

**Expected behavior**
Using pull related to pull content filtered by the page language should work correctly for the default language.

**Additional context**
This only occurs for the default language. What appears to be happening is that the default language fallback is firing even on pages that are already in the default language, and the rendering of default language fallback pages appears to be failing to properly use pullRelatedContent where the language is specified. This happens even if you switch `#foreach ($relatedField in $dotcontent.pullRelatedField("$con.identifier", "TestContent.relatedContent", "+languageId:$dotPageContent.languageId"))` to `#foreach ($relatedField in $dotcontent.pullRelatedField("$con.identifier", "TestContent.relatedContent", "+languageId:1"))`, so it does not appear to be related to the `$dotPageContent.languageId` ViewTool property. 

This could also mean we are doing double work, in that we are rendering pages in the default language twice. Once normally, and once as a 'fallback' even though it is not necessary.

**Comment by dsilvam** [comment]
Setting 
```
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=true
DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true
```
Makes the pullRelated work when requesting `en_us` in Spanish and defaulting it to default  lang (English).

The other option is to avoid, when requesting in Spanish, defaulting the `en_us` page to default lang, which is achievable by setting

```
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=false
DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=false
```

**Comment by JohnRiv** [comment]
@dsilvam how would I set those in my docker-compose.yml? I just tried this and didn't see any change in the files pushed to S3 when following the steps above to reproduce:

```
services:
  ...
  dotcms:
    image: dotcms/dotcms:5.3.8.4lts
    environment:
      ...
      "DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE": 'true'
      "DEFAULT_PAGE_TO_DEFAULT_LANGUAGE": 'true'
```

**Comment by dsilvam** [comment]
@JohnRiv they would need to be prefix with `DOT_`. So in that case: 
```
"DOT_DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE": 'true'
"DOT_DEFAULT_PAGE_TO_DEFAULT_LANGUAGE": 'true'
```
For more info about it you can check: 
* https://dotcms.com/docs/latest/changing-configuration-properties#EnvironmentVariables
* https://dotcms.com/docs/latest/docker-image-configuration-options#dotCMSConfigOptions

**Comment by JohnRiv** [comment]
Thank you @dsilvam. Using this configuration appears to have worked:
```
"DOT_DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE": 'false'
"DOT_DEFAULT_PAGE_TO_DEFAULT_LANGUAGE": 'false'
```
That prevents the English file from being included in the Spanish folder, which is even better since it is no longer pushing that file for each active language.

**Comment by john-thomas-dotcms** [comment]
Reopening because this is still an issue, and we have other customers seeing it.

Changing the value of those parameters doesn't work for one new customer: https://dotcms.zendesk.com/agent/tickets/104015

**Comment by john-thomas-dotcms** [comment]
Reopening because this is still an issue, and we have other customers seeing it.

Changing the value of those parameters doesn't work for one new customer: https://dotcms.zendesk.com/agent/tickets/104015

Even if changing those properties did work around the issue, that's not a valid workaround, because that changes the behavior of the whole front-end site, not just the behavior for push publishing.

**Comment by wezell** [comment]
When generating a site statically, we need to generate the default language last.  This will give us a 80/20 solution whereby customers will not be surprised when they visit a statically rendered page and it is in a different language than the default.

**Comment by wezell** [comment]
This issue has been moved to #20469
