### ISSUE TITLE
Add the "Don't show this again" checkbox to Edit User Page

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20090]
The "Show Getting Started Page" checkbox is currently displayed in the My Account popup, but as an enhancement, we should include it in the Edit User Page.

**Important note:** The endpoint should be executed automatically when the checkbox is checked/unchecked without hitting Save to persist the change.

![Screen Shot 2021-03-12 at 10.10.48 AM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/04031f88-b497-4415-a937-79cfbc9eba9e)

**Comment by alfredo-dotcms** [comment]
This needs a new endpoint or an upgrade to the existing one, to be able to get a userId to show/hide the starter page

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20119

**Comment by nollymar** [comment]
**Internal QA:** Needs work.

This change breaks the "Don't show this again" checkbox of the Welcome Page

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1642/files

**Comment by bryanboza** [comment]
Fixed, now we are able to control that from the user configuration portlet. New issue reported on this card #20234
