### ISSUE TITLE
Upload button applying a license on Safari does not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20097]
When you are navigating using Safari and try to apply a EE license, the upload button is not working, is downoading the file and you are unable to apply the license.

**To Reproduce**
- Start a fresh instance 
- Login using Safari 
- Go to configuration --> License 
- Try to upload a license pack 

**Expected behavior**
We need to be able to apply the license without problems 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20143

**Comment by fabrizzio-dotCMS** [comment]
Tested satisfactorily under Firefox Chrome and Safari.

**Comment by bryanboza** [comment]
Fixed, tested on master and now it works as expected.
