### ISSUE TITLE
Subfolders in Site Browser are not sorted alphabetically if the folder Name is changed

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20104]
As reported in https://dotcms.zendesk.com/agent/tickets/103795 
Reported in v5.3.8.4
Recreated in Demo v21.03 

Subfolders in Site Browser are not sorted alphabetically if the folder Name is changed.

If a folder's Title and Name are NOT the same, dotCMS uses the Title field to sort alphabetically.
This makes the folders appear out of order when using the Site Browser.

**NOTE: Root-level folders DO get sorted on Name, not Title. Issue ONLY occurs on sub-folders.**

**To Reproduce**
1. Create a folder at root level
2. Create a few sub folders where the Titles and Names agree
3. They appear to be sorted alphabetically sorted
4. Add another folder where the Title and Name are different

The folder is sorted by Title not Name

SCREENSHOT ONE - folders appear out of order ('x-ray' appears before 'barn'):

![image](https://user-images.githubusercontent.com/49727631/111502250-ad816980-8713-11eb-8da7-633b453d7ef9.png)

SCREENSHOT TWO - Folder detail of 'x-ray' showing the title is 'baby'

![image](https://user-images.githubusercontent.com/49727631/111502451-d6a1fa00-8713-11eb-983e-2b530d9267c5.png)

SCREENSHOT THREE - changing the title to 'x-ray'

![image](https://user-images.githubusercontent.com/49727631/111502583-f802e600-8713-11eb-942e-32f62bbc3b75.png)

SCREENSHOT FOUR - folder now appears in appropriate alphabetical sort order

![image](https://user-images.githubusercontent.com/49727631/111502661-0e10a680-8714-11eb-8387-4c3c724ceb3a.png)

**Comment by wezell** [comment]
Please include the above change in any fix - it changes the default sort to `mod_date desc` rather than `mod_date asc`

**Comment by ivorpad** [comment]
`bat` title is `zoot` and it's sorted as expected.

![Screenshot 2021-06-04 at 23.08.30.png](https://images.zenhubusercontent.com/5eac6c48896abe40e7f6d73e/bcd78630-de84-43d3-b50a-24ba0b8999c2)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgtres // FF
