### ISSUE TITLE
Due to changes in chrome, admin tools are breaking with 

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#20111]
Due to stricter checking in Chrome certain components of the admin console are breaking with the "Refused to Execute Script Error – its MIME type (‘text/html’) is not Executable" error.

For example, in workflow_js.jsp it has 
<%response.setContentType("text/html");%>

and Chrome will refuse to load the workflows

Changing this to
<%response.setContentType("application/javascript");%>

Allows workflows to load properly.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome 89.0.4389.82

**Comment by dsilvam** [comment]
In what version of dotCMS is this happening? Looks like it got fixed in 5.3.2: https://github.com/dotCMS/core/pull/18448

**Comment by notmattmonroe** [comment]
This was in 5.2.4, good to see that it's resolved!
