### ISSUE TITLE
Push publishing is not respecting time zones and is basing publish time on the clients system (browser) time

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20110]
**Describe the bug**
Push publishing is not respecting time zones. This is causing unexpected behaviour when push publishing bundles where your system time is ahead of server time. 

If your system time (e.g. the time set on your computer/laptop) is ahead of the servers time, regardless of whether the system time is set wrong or if you are in a time zone ahead of server time, your bundle will be set to publish in the future.

If your system time is behind server time, the bundle will publish immediately. This includes if you manually select a time in the future. If that time is behind server time, it will publish immediately.

The time on the receiver does not seem to matter. 

Ticket: https://dotcms.zendesk.com/agent/tickets/103734

Reproduced on dotCMS version 21.03

**To Reproduce**
There are multiple ways to reproduce the various behaviours.

1. Change your system time zone to ahead of UTC
2. Go to demo.dotcms.com
3. Create a 'dummy' push publishing endpoint. 
4. Try to push publish any content
5. Go to the publishing queue, this content will be set to publish in the future.

You can also reproduce incorrect behaviour by keeping your system time behind UTC, then attempting to publish something 'in the future', but still behind UTC. This content will publish immediately, despite being set to publish in the future.

For example, my local time was 9:30am, UTC was 1:30pm. I set something to publish at 11:40am, and it immediately tried to publish it. 

**Expected behavior**
Push publishing should account for time zones.

**Comment by wezell** [comment]
We need to add a timezone selector to the push publishing dialog - on the same row as the publish / expires date selectors.  This timezone picker is just a dropdown - that default to the user's browser timezone but should allow them to select another timezone to publish/expire the content if they wish. 

When we send the date/time for the publish expire values, we need to include the timezone so dotCMS can calculate the correct PP times.

**Comment by alfredo-dotcms** [comment]
@wezell question, how complex you want it to be the timezone picker? 
if you really want a dropdown then based on research, set in timezones **depends on the place**, so it's **not a whole number (GMT +12/-12 )** and as a dropdown **it takes space to fit that new component on the same row**
![image](https://user-images.githubusercontent.com/37185433/116916508-a7374600-ac0a-11eb-957b-6db95deaa7ad.png)

on the other hand, if you want it to be just an input (the user will have to enter GMT with no location reference), instead of a dropdown, then I think it can be put on the same row as the publish and expire components

**Comment by alfredo-dotcms** [comment]
based on discussion, 

- We show the “current time zone” (based on the user's browsers)
- If user clicks it
- Show the dropdown to change it (filled with a list of timezones used in BE)
@fmontes will create a mock and uploaded to this task

*Note: since the P&P endpoint will receive a new parameter `timezone` a new BE task needs to be created @nollymar

**Comment by fmontes** [comment]
https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=664%3A10773

**Comment by nollymar** [comment]
PR Core: #20352

**Comment by nollymar** [comment]
Passed internal QA: Tested on environments with timezones ahead and behind.

**Comment by wezell** [comment]
Additionally, we added the TzData package to our docker image.  We need to test what setting this as an environmental variable does to the timezone value and if pushing on time still works.  @swicken-dotcms is it ok if we reach out to you for a test case here?

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // Docker... New enhancement reported here #20615 

This card also was tested bby @swicken-dotcms

**Comment by oarriet** [comment]
hi guys, I have some feedback here: 

Reproducible on demo.dotcms.com

1. If your local system is in AEST, and you try to select another Timezone, for example EST
![image](https://user-images.githubusercontent.com/944787/125830318-28ed57d9-fc13-48f4-9ffb-2688fd3b5394.png)

2. You are not able to select a date "from the past", meaning you can't select a date in EST Timezone. 
![image (1)](https://user-images.githubusercontent.com/944787/125830414-49766454-c369-4636-9e44-a2e027128d6e.png)

**Comment by wezell** [comment]
Oscar, thanks!  I moved your comment to a new issue.

**Comment by john-thomas-dotcms** [comment]
Note: There is a way to work around the issue for customers without the fix, though it may involve manual work (calculating time zone differences) by users, depending on their local time zones.

* If all your users are in the same time zone, and you set the server (on the OS) to that same time zone, you should not see the problem.
* If you have users whose local time is behind the server time zone, they will be able to publish content immediately without problems, but they'll need to manually adjust for the time zone difference if publishing at a future time.
* If you have users whose local time is ahead of the server time zone, they will need to manually adjust for the time zone difference each time they push publish.

In all cases, the time zone set in the back-end of dotCMS (in the Configuration Tool/portlet) should match the server OS time zone.

**Comment by jcastro-dotcms** [comment]
Changes cannot be back-ported to dotCMS 5.3.8.7 LTS release because of differences in existing code.
