### ISSUE TITLE
Requesting a remote token from the Push Publishing tool invalidates a user's session

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20117]
When setting up a new endpoint, we allow the user to remotely request a token from the receiver.  The issue is that when we do the remote request, we are just passing back the remote response as our servers response.  The remote response has a new JSESSIONID and all new cookie values which then invalidates the user's session.

![Screen Shot 2021-03-19 at 3 45 38 PM](https://user-images.githubusercontent.com/934364/111835005-c6804b00-88ca-11eb-8caa-353739b8eb85.png)

**Comment by bryanboza** [comment]
Fixed, tested on release 21.04 // Postgres // FF

**Comment by swicken-dotcms** [comment]
Not adding this to LTS as the code does not yet exist there.
