### ISSUE TITLE
Add GraphQL playground as portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20129]
**Is your feature request related to a problem? Please describe.**
GraphQL API is one of the most useful features in DotCMS and there is nothing within the system for users to test or use it.

**Describe the solution you'd like**
We can use the HTML version of the GraphQL playground to add it to DotCMS as a portlet

https://www.npmjs.com/package/graphql-playground-html

**An example on how is used in pure HTML**
https://github.com/graphql/graphql-playground/blob/master/packages/graphql-playground-html/minimal.html

**Describe alternatives you've considered**
Import the library from npm and initialize into an angular component

Create the portlet module as usual.

**Additional context**
The route should be `/graphql`

**Comment by fmontes** [comment]
1. Use `light` theme
2. Is not autocompleting in the `search` query like
```
query Search {
  search(query: "+contentType:webPageContent", limit: 10) {
    identifier
  }
}
```
3. Need to remove the settings and the tracing button
<img width="1449" alt="Screen Shot 2021-03-26 at 8 47 28 AM" src="https://user-images.githubusercontent.com/751424/112649355-fae69080-8e0f-11eb-8336-702a2ea8ab15.png">

**Comment by fmontes** [comment]
Let's use `graphiql`

**Comment by wezell** [comment]
Also, needs new starters, right?

**Comment by erickgonzalez** [comment]
@wezell yes we have another task for it #20145

**Comment by bryanboza** [comment]
After play a little bit with this portlet we have some inconsistencies here: 

- If you are logged in as a limited user and you try to get content which you don't have permissions, you are able to get this content without problems, seems we always are sending the query with admin credentials
- You are able to see the query history of other users, this need to be filtered by user
- If you made a query with some syntax error, we are printing exactly what you have in the editor in the logs, including all queries, notes etc... We need to catch this exception and print just the line of the error.

**Comment by fmontes** [comment]
> If you are logged in as a limited user and you try to get content which you don't have permissions, you are able to get this content without problems, seems we always are sending the query with admin credentials
 N/A

> You are able to see the query history of other users, this need to be filtered by user
We're using a regular external library and it saves the history in the local storage, so nothing to do here.

> If you made a query with some syntax error, we are printing exactly what you have in the editor in the logs, including all queries, notes etc... We need to catch this exception and print just the line of the error.
Needs to talk to @dsilvam because this is a backend work

**Comment by bryanboza** [comment]
Fixed, After this feedback then we will close this card. New card created here #20324
