### ISSUE TITLE
Cluster Ids cannot contain underscores.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20122]
If you set your DOTCMS_CLUSTER_ID to a value with underscores, e.g. `CLIENT_TESTING_SERVER`, you will be unable to create or use new indexes.  This is because  when we parse the index value to find out if it is a valid cluster, we mistakenly split the value on the underscore.

To test, start clean and pass the environmental variable ~`DOT_DOTCMS_CLUSTER_ID=MY_DOTCMS_CLUSTER`~ `DOTCMS_CLUSTER_ID=MY_DOTCMS_CLUSTER`.

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release 21.04 // Postgres // FF

**Comment by swicken-dotcms** [comment]
Cannot move this change to 5.2.8.5, changed file is too different.
