### ISSUE TITLE
Either "Live" or "Working" indices are in read-only mode

### ISSUE THREAD

**Issue by yang-wj** [dotCMS/core#20125]
![image](https://user-images.githubusercontent.com/50098975/112075503-9cbd7180-8bb3-11eb-8365-173c563bf496.png)

**Comment by wezell** [comment]
This is an issue with your elasticsearch cluster.  Most probably, your disk has less than 20% free space and the indexes have been marked as read-only.  You need to google how to fix "elasticsearch read only"
