### ISSUE TITLE
Add a copy for the host_id that is shown on an app list

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20135]
Sometimes you want to copy the host_id for a given configuration in the apps. We need a copy feature over the host id to make copying the host_id to your clipboard easier.

![Screen Shot 2021-03-23 at 4.13.24 PM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/3118e9f5-04bd-4bd6-848d-03fd61707810)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1640

**Comment by fabrizzio-dotCMS** [comment]
Looks Good to me. Passing it.

**Comment by bryanboza** [comment]
Fixed, now we can copy the id just clicking the text. Tested on release-21.05 // Postgres // FF
