### ISSUE TITLE
No selection in drop downs need some improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20137]
When you have a drop down and you want to leave this unselected, we are showing the "empty" word, we need change this and show a blank field or something like "No selection"

![image](https://user-images.githubusercontent.com/2641437/112224467-ed9f8b00-8bf0-11eb-8cc0-065bd2d7dbf0.png)

**To Reproduce**
- Login as admin
- Create a new content type 
- Add a date time field
- edit the content type and try to select the Publish field 

**Desktop (please complete the following information):**
Tested on release-21.04 // Postgres // FF

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
