### ISSUE TITLE
Cant filter by roles

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20139]
Description: 
The System Roles screen is showing an error when clicking on the role item itself.

1. Go to  System -> Roles & Tools 
2. Click on The role "Scripting User"
3. An Error message pops up and No filtering is happening
4. The exception seems to be a javascript problem perhaps some of the items on the map that is sent from the back have changed somehow. I assume that since there are no visible exceptions in the logs. 
5. Additionally whenever I click on the Front-End user I get empty rows (See screenshot 2)

**Screenshots**
Screenshot - 1 Error Reported
![Screen Shot 2021-03-23 at 17 58 58](https://user-images.githubusercontent.com/37148755/112234138-74f4fa80-8c01-11eb-929b-0ab290618160.png)

Screenshot - 2 No info displayed.
![Screen Shot 2021-03-23 at 18 00 24](https://user-images.githubusercontent.com/37148755/112234215-a66dc600-8c01-11eb-89be-3822fa46ca75.png)

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify the issue has been fixed.

**Comment by bryanboza** [comment]
Fixed, tested on release 21.04 // Postgres // FF
