### ISSUE TITLE
Trim key and values saved by apps

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20134]
When an app has optional properties, it is possible to store a key and a value that start with a whitespace.

We need to trim() the key and the values that are stored in the app.

**Comment by fabrizzio-dotCMS** [comment]
I tried adding blank spaces to the front and also to the tail of the value prior to store it. 
I even debugged the code to make sure the password fields are also trimmed properly. 
It works fine for both protected and non-protected. Custom and regular properties were verified too.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF

**Comment by swicken-dotcms** [comment]
Excluded from 5.3.8.5/5.2.8.5 as AppsHelper.java is too different in the changed areas to safely bring back code changes
