### ISSUE TITLE
Personas portlet is not showing the  license required message 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20149]
When you are in a community edition and go to Marketing --> Personas, we are just showing a blank page, this instead to show a license requiered message as we do in all the others enterprise portlets, also we are printing an error in the log file.
![image](https://user-images.githubusercontent.com/2641437/112526122-38431380-8d67-11eb-8ccb-90fb73a37443.png)

Here the log: https://gist.github.com/bryanboza/15da0ab9d88145c5da7cce5f1d46ef24

**To Reproduce**
- Login as amin in an instance without a licenses 
- Go to Marketing --> Personas
- Check your log file 

**Expected behavior**
We need to show a message that personas is a EE feature and avoid to print those multiple lines in the log 

**Desktop (please complete the following information):**
Tested on release-21.04 // Postgres // FF

**Comment by erickgonzalez** [comment]
I guess this is because the Personas portlet is not a portlet per se, is a custom content portlet meaning it's the content portlet that only pulls Personas

**Comment by bryanboza** [comment]
Sure, but since now this is a default portlet in our starter site, we need to do something here, just show a blank page and an error in the log seems like something is broken and we are not informing the end user about the required license
