### ISSUE TITLE
Update both starters to add new features

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20145]
**Is your feature request related to a problem? Please describe.**

### Empty
1. GraphQL Portlet under Dev Tools.
2. System template and system container.

### Full
1. Inline editing in the full starter added to Blog, Destination, Home and Products
2. Examples of FileAssetTemplates for Design and Advanced.
3. GraphQL Portlet under Dev Tools.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20322

**Comment by fmontes** [comment]
We need to remove the checkbox in the rows that have file templates.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF
