### ISSUE TITLE
User is logged out when accessing content if the Role does not have the 'Content' portlet tool group

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20156]
As reported in: https://dotcms.zendesk.com/agent/tickets/103849
v5.3.8.4
Recreated on v5.3.8.2 local Docker instance

User is logged out when accessing content if the Role does not have the 'Content' portlet tool group assigned.

**To Reproduce**

1. Create a new back-end Role with permissions on a single site on the instance (no "All Sites" permissions).  (SCREENSHOT 01)
2. Create a Content Type, create a few contentlets and add the Role to its permissions. (SCREENSHOT 02)
3. Add Tool groups to the Role, including a custom group to the new Content Type, BUT DO NOT ADD the "Content" group. (Screenshot 03)
4. Login as the new User and access the custom tool group (SCREENSHOT 04)
5. Try to open a contentlet
6. Contentlet opens with no fields - only the error:

![image](https://user-images.githubusercontent.com/49727631/112657389-60427d80-8e20-11eb-9254-c66a57d2e3dc.png)

Then User is automatically logged off. 

This error appears in the dotcms.log:

`[23/03/21 14:36:18:468 EDT] WARN action.EditContentletAction: User is not set or user does not have access to portlet:content`

**Screenshots**

SCREENSHOT 01
![image](https://user-images.githubusercontent.com/49727631/112656305-42c0e400-8e1f-11eb-9c47-18f17a99e049.png)

SCREENSHOT 02
![image](https://user-images.githubusercontent.com/49727631/112656431-67b55700-8e1f-11eb-9c38-5e1eb5ee74df.png)

SCREENSHOT 03
![image](https://user-images.githubusercontent.com/49727631/112656897-da263700-8e1f-11eb-9ec5-f1aa73250c00.png)

SCREENSHOT 04
![image](https://user-images.githubusercontent.com/49727631/112657028-faee8c80-8e1f-11eb-9ef7-488003d01d60.png)

**Comment by fabrizzio-dotCMS** [comment]
I can log in with the new holding the new Role as explained on the  steps above  and instead of getting logged off I can not see the contentlets

**Comment by bryanboza** [comment]
After try to test I'm unable to follow the steps, this because after create a new content type, I'm unable to see this in the list of tools creating the new custom group 
To reproduce: 
- Login as admin
- Create a new site 
- Create a new content type 
- Add some pieces of content 
- Crete a new role with full permissions over the new site 
- Try to create the a new custom tool group and add the new content type

**Comment by bryanboza** [comment]
Fixed, now we are able to open this pieces of content without problems, a new case related to permissions reported here: #20206
