### ISSUE TITLE
Editor in rules trying to add a condition for a session attribute

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#20153]
Reproducible in dotCMS 21.03

When creating a rule from dotCMS backend UI, if a new condition is added to evaluate if a session attribute exists, the user cannot specify the session attribute key.

**To Reproduce**
1. Go to 'Rules' portlet
2. Click on '+' button to create a new rule
3. Set any name for the new rule
4. Add a new condition for the rule. In the condition type drop down, chose 'Session Attribute'
5. In the comparison drop down, chose 'Exists'
6. There is no field to chose the session attribute key. 

**Expected behavior**
The user should be able to chose the session attribute key to evaluate the condition (that the specified session attribute exists).

**Screenshots**
Condition without field for the session attribute key:

![image](https://user-images.githubusercontent.com/2894221/112565609-f89a1d00-8da2-11eb-8bc3-59ca33da6e4f.png)

- [x] Request Session
- [x] Browser (field order)
- [x] Request Parameter
- [x] Request Attribute
- [ ] do not automatically deactivate the rule on change unless the rule is invalid - otherwise, keep the rule active

**Comment by wezell** [comment]
The same is true for Request Attributes and Request Parameters

**Comment by wezell** [comment]
Also, the browser conditionlet is out of order

**Comment by alfredo-dotcms** [comment]
Core-Web PR: https://github.com/dotCMS/core-web/pull/1678

**Comment by alfredo-dotcms** [comment]
@QA: in this task several things were fixed!
- conditions for key/value attribute are not possible (eg. request attribute, request parameter, session attribute, etc)
- do not deactivate the rule unless the rule is invalid
- conditions components are out of order (eg. Browser)
- Logger (logs in console) must be deactivated in Prod
- Visitor's country not keeping the label once saved (shows the value)
- style miss-aligned conditions and rules controls

**Comment by alfredo-dotcms** [comment]
DotCMS v3
![image](https://user-images.githubusercontent.com/37185433/122303510-ea9afa80-cec0-11eb-9f6b-e885354bc6a2.png)

**Comment by alfredo-dotcms** [comment]
Demo - current version
![image](https://user-images.githubusercontent.com/37185433/122303546-fab2da00-cec0-11eb-851e-434735e1243d.png)

**Comment by alfredo-dotcms** [comment]
After fixes
![image](https://user-images.githubusercontent.com/37185433/122303598-069e9c00-cec1-11eb-953e-300ed5d5f73f.png)

**Comment by fabrizzio-dotCMS** [comment]
For Internal QA.
![Screen Shot 2021-06-22 at 11 21 04](https://user-images.githubusercontent.com/37148755/122971332-2d8b2100-d34c-11eb-987b-0b29ccec83b2.png)

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core-web/pull/1682

**Comment by fabrizzio-dotCMS** [comment]
Rules can't be added to a Bundle. The dialog shows up but it doesn't accept a bundle name. Therefore no bundle is created and no rule can be added.
![Screen Shot 2021-06-24 at 13 31 23](https://user-images.githubusercontent.com/37148755/123331113-13904080-d4fc-11eb-8c72-05844e3294c0.png)

PP for rules workss in demo.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF and now this looks better

**Comment by wezell** [comment]
We need to also not disable the rule if a user changes an `actionlet`

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core-web/pull/1689

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
