### ISSUE TITLE
Cutting and Pasting into the new Icon Selector does not work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20157]
I was trying to update dotcms.com and found this issue.  If you try to cut and paste a value into the icon selector field, and then hit save, it does not persist.  You need to actually select it from the list.

try copying and pasting
`accessible` 
or 
`settings_applications`

Also, lets update our icon list to this:

[material-icons.json.txt](https://github.com/dotCMS/core/files/6213805/material-icons.json.txt)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1641/files

**Comment by nollymar** [comment]
**Needs work:** if I copy and paste a value into the icon selector and save it, the value is not persisted. Video attached

https://user-images.githubusercontent.com/8741395/114094287-bfbd7600-9881-11eb-9e70-5e25adcf2453.mov

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-21.04 // Postgres // FF
