### ISSUE TITLE
Focal Point is lost when hitting save on the image editor and then publish.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20154]
**Describe the bug**
Focal point MD isn't set from content version to version 

**To Reproduce**
1. Let's start by uploading a brand new Image File-Asset
2. Click on Publish
3. Then Open-Up the image editor by double-clicking on the image. Set a Focal Point anywhere.
4. Hit Save
5. At the Content Editor level - Hit Publish.
6. Close and re-open the  Content Editor dialog and verify the Image doesn't have any Focal-point

**Expected behavior**
The Focal Point data must be persisted from version to version after hitting publish. And now it isn't.
Additionally to the compress drop-down isn't working on the Image Editor. And that also needs to be fixed.

**Comment by alfredo-dotcms** [comment]
Not fixed, steps to reproduce:

1. add an image
2. add focal point
3. click SAVE
4. close dialog
5. open img dialog
6. change focal point
7. click PUBLISH
8. close dialog
9. open img dialog
10. click METADATA tab in dialog

you'll see that the metada info is not present

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF
