### ISSUE TITLE
Workflow Sub-action Drop-down not sorted correctly

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#20168]
**Describe the bug**

The `Comment on Workflow` and `Translate Content` sub-actions are not sorted within the list in the sub-action drop-down.  All the other sub-actions are sorted alphabetically, but these 2 sub-actions are just tacked onto the end of the list.  Looks bad, and makes both of these hard to find.

## To Reproduce
1. Open any Workflow Action.
2. Open the Sub-action drop-down.
3. Scroll to the bottom of the list.
**Result:** See screenshot below.

## Expected behavior

All sub-actions in the list should be sorted in alphabetical order.

## Screenshots

![image](https://user-images.githubusercontent.com/13456955/112999178-9420ea00-9123-11eb-9f12-fddc96e3071f.png)

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
