### ISSUE TITLE
Problems with the site selector after push a site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20169]
We are unable to change between sites and see the site content after you push a site 

**To Reproduce**
- Start two instances (sender: full starter //  receiver: empty)
- Apply licenses 
- Configure your push environment 
- Create a new template that uses the default container 
- Push this template
- We push the demo site by dependency, now try to change the site selector 

**Expected behavior**
We need be able to continue navigating without problems 

**Desktop (please complete the following information):**
Tested on release 21.04 // Postgres // FF

**Comment by wezell** [comment]
The session cookie requires the secure flag - so you need to test this against an https port, e.g. https://local.dotcms.site:8443
