### ISSUE TITLE
Double border around portlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20170]
Related to #19824 -  We have somehow created a double gray border around out portlet frame/card.  See below

---

![Screen Shot 2021-03-30 at 2 47 11 PM](https://user-images.githubusercontent.com/934364/113040724-1ed70880-9167-11eb-9c9d-fea0dc4b25e9.png)

---

![Screen Shot 2021-03-30 at 2 47 19 PM](https://user-images.githubusercontent.com/934364/113040727-1ed70880-9167-11eb-839b-2393b44b2f61.png)

**Comment by alfredo-dotcms** [comment]
the double border is actually a scrollbar of the left side menu, and it appears based on user's Mac system configuration
![image](https://user-images.githubusercontent.com/37185433/114091259-ae6e6c80-9875-11eb-8999-3a7f8790c9de.png)

some workaround were tried to fix this, but not a single one were good enough to fulfill design requirements, so based on that @fmontes suggested that at this moment this won't be fixed

**Comment by wezell** [comment]
Makes sense, thanks Alfredo!
