### ISSUE TITLE
[SAML] : Authentication process must check for both User ID and Email

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20189]
Reported via Support: [103304](https://dotcms.zendesk.com/agent/tickets/103304)
Reproducible in **ALL** versions of dotCMS.

When a user attempts to log into dotCMS via SAML, the system will try to find an existing user based on the Authentication Type configured in the back-end: `Use ID`, or `Email Address`.

However, there are situations in which the User ID coming from SAML is completely different from the existing one in dotCMS. This causes the application to create a brand new User in dotCMS with the exact same information, but different ID.

**To Reproduce**
Steps to reproduce the behavior **in an environment with SAML authentication**:
1. Log into dotCMS via SAML making sure it works.
2. Log in with an Admin User -- in case the logged-in user is NOT a CMS Admin -- go to the **Users** portlet and look for the first name of the user that logged in in step 1.
3. You'll see that there are two users now, which is incorrect.

**Expected behavior**
dotCMS must make sure that the incoming SAML user matches any existing user by checking both the User ID and Email, regardless of the existing Authentication Type used by the native login page. After checking for both, if no match is found, then proceed with the creation of a brand new User.

**Comment by swicken-dotcms** [comment]
Changes occur in a class that does not exist in 5.2.8.X, not moving back to 5.2.8.5
