### ISSUE TITLE
File Metadata does not get generated if custom attributes are initially written.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20192]
**Description**
The real useful File Metadata doesn't get generated if the binary already has custom attributes
This is because the basic heuristic used to generate the metadata says. if it already has metadata do not generate it. 
And the finder method does not differentiate if the metadata present on the binary is made up exclusively from custom attributes. it only states that it already has metadata associated. Therefore the other metadata is never generated.
 
Additionally, when copying metadata from version to version we only must copy custom attributes. if it does make sense. 
I've seen cases in which a binary gets replaced from an image to pdf or txt. and stuff like that.

**To Reproduce**
1. Upload an image, then before publishing it. Open the Image Editor and add a focal point 
2. Hit Save and then Publish the close the window.
3. Now Re-open the Content editor for the same file and verify the MD
4. See There is no MD except for the focal point

If you initially publish the file and then come back to add the focal point it'll work as expected.

**Comment by wezell** [comment]
Ah good catch. Every binary must have system generated metadata.

**Comment by alfredo-dotcms** [comment]
this is still happening when doing steps 1 through 4. This issue can be related with https://github.com/dotcms/core/issues/20154

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 and I'm unable to reproduce
