### ISSUE TITLE
dotCDN app

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20198]
**Steps To Test:**
1. Clone the plugin repo https://github.com/dotCMS/com.dotcms.dotcdn
2. Create the jars of the plugin `./gradlew jar`
3. Upload jars to dotcms
4. Configure App (Contact @erickgonzalez )
5. Add CDN portlet

**APP**
Will have 3 String fields:

CDN domain: required.
CDN API/Client Key: required and hidden.
CDN Zone ID: required.

**Resource (This can be tested using the Portlet)**
Will have a couple of endpoints that will hit the bunny API to get the responses:

GET /stats: receives 2 dates and a string that is the hostId to find the according zoneId.
DELETE /: receives a string (could be several separated by comma), a boolean to invalidateAll and a string that is the hostId to find the according zoneId.
If the invalidateAll boolean is set to true, will call the PurgeCache endpoint.

**ViewTool**
User will be able to get files by sending the fileUrl where it lives in the CDN.
E.g
`<img src="$dotcdn.cdnify("/images/DJI_0055.JPG")">`

**Actionlet**
Users will be able to add an actionlet to their workflow, this actionlet will have 2 params:

URL(s) to purge: can be set to specific url(s) to be purged. Use comma (,) as a delimiter.

Purge Contentlet: It creates a list of patterns that should be purged using the `$contentlet object`.
E.g. `/dA/$contentlet.shorty/{fileName}` or `/dA/$contentlet.shortyInode/{fieldName}/{fileName}`
The default value for the Purge Contentlet is false.

**Comment by fmontes** [comment]
Here is the plugin and you can ask @erickgonzalez for the secrets for the app.

[plugin.zip](https://github.com/dotCMS/core/files/6416426/plugin.zip)

**Comment by fmontes** [comment]
@bryanboza You can ask @erickgonzalez or me how to get and install the plugin.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF 
![image](https://user-images.githubusercontent.com/2641437/118195922-5e04a480-b409-11eb-8f75-025a9bc77539.png)
