### ISSUE TITLE
Update listing template to work with file templates

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20191]
**Is your feature request related to a problem? Please describe.**
In the template listing, we need to link the file template to the site browser.

**Describe the solution you'd like**
1. Since we need to link to the template folder we need to hit an endpoint to set in the session the selected folder in the side browser.
2. Remove the right click from the file template row
3. Remove the ... from the file template row

**Describe alternatives you've considered**
We might want something in the router service to do this and be reusable.

**Comment by fmontes** [comment]
We need to remove the checkbox from the file templates.

![image](https://user-images.githubusercontent.com/751424/116894708-9a592900-abef-11eb-8679-6cf432dd4aea.png)

**Comment by bryanboza** [comment]
We need some work here: 
- According to the description, we need to remove the checkbox from the template row
- If you click on some of those templates we are redirecting to the site browser, we need to ignore that click

**Comment by fmontes** [comment]
Bad merge, fixed.

**Comment by bryanboza** [comment]
- Need to add the system template to the full starter

**Comment by bryanboza** [comment]
Fixed, seems is not necessary add this to the full starter
