### ISSUE TITLE
Link file containers in the listing to site browser

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20193]
**Is your feature request related to a problem? Please describe.**
In the container listing, we need to link the file template to the site browser.

**Describe the solution you'd like**
Since we need to link to the container folder we need to hit an endpoint to set in the session the selected folder in the side browser.

**Describe alternatives you've considered**
We need to hit the endpoint first. See the blocked issue.

**Comment by fmontes** [comment]
We need to remove the checkbox from the file templates

**Comment by bryanboza** [comment]
Still getting the checkboxes in the system templates

**Comment by bryanboza** [comment]
Fixed, the comment will be moved to this card #20191
