### ISSUE TITLE
Imported content inherits permissions from site instead of content type

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20196]
As reported in https://dotcms.zendesk.com/agent/tickets/103835 v5.3.8.4
Tested locally on 5.3.8.2

**Describe the bug**
If a Content Type has individual permissions set, its contentlets should inherit those permissions. 
However, if you import content, the imported contentlets inherit from the site as if the permissions weren't set on the Content Type.

Additionally, cascading permissions from the Content Type to the imported contentlets does not reset their permissions even if you add a Site/Folder field to the Content Type.

**To Reproduce**
1. Create Content Type and set permissions so it no longer inherits from the site (SCREENSHOT 01)
2. Import Contentlets from a CSV (SCREENSHOT 02)
3. Open a contentlet's permissions - it is inheriting from the site (original) instead of the Content Type (SCREENSHOT 03)

- You can individually re-permission the contentlets
- Cascading / Resetting all children from the content type does NOT re-permission contentlets even when you add a Site/Folder field.
- Updating contentlets via import does not update permissions 

SCREENSHOT 01 - Content Type Permissions - Individually set.

![image](https://user-images.githubusercontent.com/49727631/113910473-7d6f3880-979e-11eb-86e0-d3d03cae3795.png)

SCREENSHOT 02 - Imported Contents

![image](https://user-images.githubusercontent.com/49727631/113911321-7ac11300-979f-11eb-91a9-1fc8cfcad7c7.png)

SCREENSHOT 03 - Imported Contentlet Permissions

![image](https://user-images.githubusercontent.com/49727631/113911486-a93eee00-979f-11eb-9ac0-941aa0c10a10.png)

**Comment by wezell** [comment]
Two questions - 

In this example, does the NewNew content type have a host folder field on it or not? 
if, when importing NewNew you add a host_id column with **SYSTEM_HOST** do the imported contents permission correctly?

**Comment by wezell** [comment]
Related to #14736

**Comment by wezell** [comment]
closed in favor of #20504
