### ISSUE TITLE
Updating User Pojo invalidates quartz jobs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20216]
In 21.04 we have updated the signature on the User.java pojo. This causes a number of stored quartz jobs from being able to fire.

This is happening on Prod and Auth.  I think we need a startup task that removes the bad job and re-queues them with the right version of the pojo.  Also, the Job Scheduler JSP allows you to delete any failed jobs which is a better practice.   If we can't get at the job data because it is stored as a serialized pojo, we should at least just delete these jobs. 

See:

![Screen Shot 2021-04-08 at 7 36 37 PM](https://user-images.githubusercontent.com/934364/114108828-f4d9c080-98a1-11eb-8268-34feb0c73c58.png)

**Comment by nollymar** [comment]
**Note to QA:** As it is not possible to get the data to re-queue the job again with the new Pojo, a button to manually delete the job will be included in the System Job table for each row with errors.

**Comment by nollymar** [comment]
Fixed:

<img width="1470" alt="Screen Shot 2021-04-13 at 11 32 33 AM" src="https://user-images.githubusercontent.com/8741395/114588159-00cfd480-9c4c-11eb-951b-175fa173e227.png">

**Note to QA:** Please ask me for a dataset to test if you need it.

**Comment by bryanboza** [comment]
Fixed, now we can delete those jobs without problems
![image](https://user-images.githubusercontent.com/2641437/114903957-9302e480-9dd4-11eb-9894-95cf0c4bdbdb.png)

After delete: 
![image](https://user-images.githubusercontent.com/2641437/114904014-9f873d00-9dd4-11eb-9328-d19ea3afdf3d.png)
