### ISSUE TITLE
Workflow Actionlet to Notify the Workflow Creator

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#2022]
Clients are requesting a couple of actionlets that seem like they should be included:
1.  Notify Creator - Would notify the person who created the workflow.  This would allow them to notify the person who started the workflow that it has been updated or resolved.
2.  Notify History - We keep track of the history of the workflow, would be simple enough to just the notification email to anyone who has ever been assigned the issue.

**Comment by john-thomas-dotcms** [comment]
Another related request that came up: Ability to also **Assign to** the user who moved the content into the current step (e.g., the content creator, or to the previous user in the workflow).

The use case here is that when reviewing content, if the edit is rejected, users want to be able to reassign it to the person who originally made the change.  Makes sense, but hard to do now without a plugin.
