### ISSUE TITLE
Workflow UI Filtering Improvement

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#2023]
Currently we have the filter to show the user's assigned workflows ("me") and if you are CMS admin you can see workflows assigned to anyone ("all").  Clients are requesting that we add a filter that would allow users to see any workflows they created.  This would give them a better idea of where their workflow was at in the process.

**Comment by john-thomas-dotcms** [comment]
+1.  See also https://github.com/dotCMS/core/issues/11999

**Comment by wezell** [comment]
This needs to be wrapped up in #11999
