### ISSUE TITLE
Move dotCMS docker image code into core

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20246]
We need to move the dotCMS docker image building code into the core of dotCMS - more of a monorepo pattern.  This will allow us to easily make version specific changes to our docker image and docker image building tools that track the specific dotCMS release they belong to.

**Comment by dsilvam** [comment]
PRs:
Core: https://github.com/dotCMS/core/pull/20467
EE: https://github.com/dotCMS/enterprise/pull/803
Dot-CICD: https://github.com/dotCMS/dot-cicd/pull/22

**Comment by bryanboza** [comment]
Fixed
