### ISSUE TITLE
Build docker images programatically with github action

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20248]
We need to stop with manually building and pushing images to our docker hub and instead create a github action that builds the correct docker images (multi-arch), tags them appropriately based on the build information and pushes it to dockerhub.  To do this, we should create a (manual?) github action that builds, tags and pushes the dotCMS image.  

We also need to embrace the ideas of `unique` tags and `stable` tags.  A `unique` docker tag is an immutable pointer to a build at a given time and should never change.  A stable tag is like `latest` or `5.3.8` and gets repointed based on the latest version of the release.

### Unique Tags
All built images should be uniquely (immutably) tagged in docker hub based on the dotCMS version number followed by an underscore and then the short git commit hash, e.g. `git log -1 --pretty=%h`.    So, when building say `v21.03`, the action would build the image and uniquely tag it:

`dotcms/dotcms:v21.03_7eacd49`

or in the case of `5.3.8.5`

`dotcms/dotcms:v5.3.8.5_40c7361`

And push the image + unique tags to dockerhub.

If we rebuild the 5.3.8.5 image to include either changes to the Docker build process or to the dotCMS code, it will have a new git hash which would be reflected by a new unique tag, e.g.  `dotcms/dotcms:v5.3.8.5_71f7361`

### Stable Tags
If the docker image you are building is for a new release, we build it and tag normally it with its unique tag and then we  update the corresponding stable tags to this new image as well.

In the case of pushing a new Agile Release, say **v21.03**, we would build our uniquely tagged image `dotcms/dotcms:v21.03_7eacd49` and then point the stable tags: `latest` and `v21.03` to it.  If/when we need to push out a point release `v21.03.1`, we again build a new uniquely tagged image `dotcms/dotcms:v21.03.1_cd45d54` and repoint the stable tags `latest` and `v21.03` to this image.    

We will maintain a stable tag for `latest`, for each "major" version, e.g. `v5.3.8` or `v21.03`  and possibly for `lts`?  Should we also maintain a stable tag for each version point release?

**Comment by wezell** [comment]
We are going to add 2 parameters when building the image

- Custom Label (things prerelease, or saml-test) which gets added to the docker image tag
- Update stable tags?  true|false

If you choose update stable tags, then your new image will also update the stable tags on which it is based, e.g.
lets say you are releasing a new LTS version for 21.05 - `21.05.7`.  You would add `lts` as the custom label and you would also say `Update stable tags=true`.  These are the tags that would be added to your newly built image:

```
unique tag : 21.05.7_lts_abc124
stable.tag : 21.05_lts
stable.tag : 21.05
```

**Comment by victoralfaro-dotcms** [comment]
@wezell with that example in mind, shouldn't we define a `21.05.7_lts` stable tag as well? Or it's enough with the unique one?

**Comment by victoralfaro-dotcms** [comment]
New repos:
- https://github.com/dotCMS/discover-docker-tags-action
- https://github.com/dotCMS/publish-docker-image-action

PRs:
Dot-CICD: https://github.com/dotCMS/dot-cicd/pull/25
Core: https://github.com/dotCMS/core/pull/20552
