### ISSUE TITLE
Updating focalpoint removes other metadata

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20240]
1. From a new starter, open an image and set a focal point and hit "save and publish".
2. close edit contentlet screen
3. reopen edit content screen, check metadata. Only the focalpoint meta is there.

![Screen Shot 2021-04-13 at 10 34 21 AM](https://user-images.githubusercontent.com/934364/114570466-d843dc80-9c43-11eb-96cd-792bb8995c06.png)

**Comment by fabrizzio-dotCMS** [comment]
it's a dupe of https://github.com/dotCMS/core/issues/20154

**Comment by fabrizzio-dotCMS** [comment]
it's a dupe of https://github.com/dotCMS/core/issues/20192
