### ISSUE TITLE
Content Type Product breaks when rendering on the Contentlet edit dialog. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20257]
Under certain circumstances, I get the following warn on my logs 

`14:27:06.005  WARN  directive.DotParse -  - at com.dotcms.rendering.velocity.directive.DotParse.throwNotResourceNotFoundException(DotParse.java:181) @ url:GET//demo.dotcms.com/c/portal/layout | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:04-14-2021 02:26:43 CST  ref:http://localhost:8080/dotAdmin/  ?p_p_id=content&p_p_action=1&p_p_state=maximized&p_p_mode=view&_content_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_content_cmd=edit&inode=45d90b05-c1eb-48dd-98ad-171c63445175&in_frame=true&frame=detailFrame&container=true&angularCurrentPortlet=content`

This seems the cause of a javascript property breaking the fron-end 
`<%=field.variable()%>tinyPropOverride =  <%= com.dotcms.rendering.velocity.util.VelocityUtil.getInstance().parseVelocity(field.fieldVariablesMap().get("tinymceprops").value(),ctx) %>;`

Because of the velocity evaluation returning an empty string. 

This only happens with Products 
but it isnt always the case.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes, tested on release-21.05 // Postgres // FF
