### ISSUE TITLE
Dates with format yyyy-MM-dd HH:mm:ss.SSS are mapped as texts in ES

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20252]
Sometimes, dates with format `yyyy-MM-dd HH:mm:ss.SSS` are indexed as `text` fields, causing warnings in the reindex process like this: 

```
16:51:57.762  WARN  business.ESContentFactoryImpl - Class org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception 
[type=illegal_argument_exception, reason=Fielddata is disabled on text fields by default. Set fielddata=true on [moddate] in order to load 
fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field 
instead.]
```

**Comment by nollymar** [comment]
PR version 5.3.8.5: #20254

**Comment by nollymar** [comment]
**Note to QA:** Please run a full reindex

**Comment by fabrizzio-dotCMS** [comment]
Just tried a full reindex on a  fresh dotCMS with the full starter. No error like that appeared anywhere. I'm assuming that means it has been fixed.

**Comment by swicken-dotcms** [comment]
Not moving to 5.2.8.5 as it requires ES changes not implemented in that version.

**Comment by bryanboza** [comment]
Fixed, tested doing a full reindex many times and no errors like this one after the changes, tested on release-21.05 // Postgres // FF
