### ISSUE TITLE
[Push Publishing] : Improving error message when finding unique content match

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20250]
Found when working on Support ticket: [103981](https://dotcms.zendesk.com/agent/tickets/103981)
Reproducible in **ALL** versions of dotCMS.

The `ContentHandler.findUniqueContentMatch` method: 

https://github.com/dotCMS/enterprise/blob/009a721b83032eecd8320e64cb0b38014cdd87a7/src/main/java/com/dotcms/enterprise/publishing/remote/handler/ContentHandler.java#L845

Is meant to find contents that must be considered equal based on at least one unique field, even though their Identifier is not the same. When running into such situation, the error message that the system logging is not very descriptive, and slows down the troubleshooting process.

**Expected behavior**
Better error messages speed up the troubleshooting process for the Support Team.

**Comment by jcastro-dotcms** [comment]
Enterprise PR: https://github.com/dotCMS/enterprise/pull/792

**Comment by fabrizzio-dotCMS** [comment]
Checked the source code, and it all looks good. I'm passing it.

**Comment by bryanboza** [comment]
We need some work here: 

If you have a PP environment and you have in the receiver side some piece of content with a unique field, and this does not exist on the sender, and you create a multi-lingual content with the same unique value on sender and try to push. We push the version in the other  languages, but in the language that already exist this value, we are overriding the existing one and leave it on receiver as different contents, not as a multi-lingual version of the main content. 

To recreate: 
- Create a content type with two fields (Name, LastName(Unique) )
- Create a new piece of content with those values (Mac, Book)
- Now push it 
- Delete from sender the piece of content 
- Crete a new multilingual piece of content with the same values (Mac, Book ) This on Spanish and English
- Try to push it 
- Now check the identifier of the contents in the receiver side 

We push boot pieces of content, but the english one is overriding the content that already exist on the receiver, then have a different identifier that the Spanish one, we lost the multi-lingual version and it is leaving as two individual contents

**Comment by wezell** [comment]
@bryanboza please move this to a new card

**Comment by bryanboza** [comment]
Ok, we will pass this one for now, the problem was moved to a new card #20384

**Comment by swicken-dotcms** [comment]
Discovered conflicts with the EE code, no longer pushing this to 5.2.8.5
