### ISSUE TITLE
Move site copy to a REST Call

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20272]
**Is your feature request related to a problem? Please describe.**
Site copy is a useful feature that users have expressed a desire to be able to access via a REST API call

**Describe the solution you'd like**
Move the initiation of site copy to a REST call, so that the Quartz job can be scheduled (with options) outside of the dotCMS backend

**Comment by jdotcms** [comment]
How to:

```
curl --location --request PUT 'http://localhost:8080/api/v1/site/_copy' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "copyFromSiteId":"8a7d5e23-da1e-420a-b4f0-471e7da8ea2d",
    "copyAll":true,
    "copyTemplatesContainers":true,
    "copyContentOnPages":true,
    "copyFolders":true,
    "copyContentOnSite":true,
    "copyLinks":true,
    "copySiteVariables":true,
    "site": {
        "siteName":"postman.copy.host.com"
    }
}'
```

It would need license and the host should exists

**Comment by bryanboza** [comment]
Fixed, tested on master and now the REST API is working as expected
