### ISSUE TITLE
[Containers] : Improving error message when deleting Container in use

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20277]
Found when working on Support: [103908](https://dotcms.zendesk.com/agent/tickets/103908)
Reproducible in **ALL** versions of dotCMS.

Deleting a Container that is being used in at least one Template in the system can be hard to track down. The error message displayed to the user only shows the title of the Template that is allegedly using the Container. Templates across different Sites can have the exact same name, so we need a few more things in the error message, such as:

- Template's title.
- Template's ID.
- The Site name where such a Templates lives in.

**To Reproduce**
1. Create a dummy Container.
2. Add it to a Template.
3. Un-publish/Archive/Delete the Container.
4. The error message only shows you: The title of the Container you want to delete, and the just title of the Template that is still referencing it.

**Expected behavior**
More information in error messages can greatly improve both user experience, and troubleshooting process for the Support Team.

**Comment by fmontes** [comment]
Needs tests.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20303

**Comment by bryanboza** [comment]
Fixed, now we are showing the complete info in a pop-up
![image](https://user-images.githubusercontent.com/2641437/120838279-df40ea00-c524-11eb-91c5-e2b89e8f5a4d.png)

Tested on release-21.06 // Postgres // FF
