### ISSUE TITLE
[Content Types] : The "Site or Folder" field dropdown randomly disappears

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20270]
Reported via Support: [103962](https://dotcms.zendesk.com/agent/tickets/103962)
Reproducible in dotCMS 5.3.8.4 ( branch `release-5.3.8.4`), and probably latest master.

Several Content Types stop displaying the `Site or Folder` dropdown from the Content Type Edit Modal randomly.

**To Reproduce**
1. Reach out to Jose Castro for details on the required data.
2. Set up a dotCMS 5.3.8.4 instance.
3. Reach out to Jose Castro in order to find the failing Content Type.

**Expected behavior**
The `Site or Folder` field must show up in the Edit Modal all the time.

**Additional context**
The customer needs this feature to work in order to continue with their authoring tasks.

**Comment by hmoreras** [comment]
Findings: The siteSelector trust in a single property `hostname` to display the name of the Host assigned to the contentType. The query to get this info is the following: 

`http://localhost:8080/api/content/render/false/query/+contentType:host%20+identifier:SYSTEM_HOST`

If we use this with any identifier except `SYSTEM_HOST` the object come with `hostName` and `hostname`. but with `SYSTEM_HOST` only comes `hostName` so the reference get lost in the Front End, and do not display the dropdown.

**Comment by hmoreras** [comment]
working on branch `release-21.06`

**Comment by bryanboza** [comment]
After this fix now we are able to see the drop-down, but if you try to use the filter typing more than 3 characters we are getting the same problem again

![image](https://user-images.githubusercontent.com/2641437/124043028-66b83680-d9c7-11eb-979b-254d7a997dd8.png)

Also, after update  the site, we getting this:

![image](https://user-images.githubusercontent.com/2641437/124043381-2a390a80-d9c8-11eb-8a7b-7f2c60c95d12.png)

After talk with @jcastro-dotcms we need some work here.

**Comment by jcastro-dotcms** [comment]
**NOTE TO SUPPORT:** For a subsequent dotCMS 5.3.8.6 LTS patch, we just need Jonathan's fix, as this new issue reported by Bryan is only reproducible in more recent versions of dotCMS.

**Comment by bryanboza** [comment]
Fixed, tested on the real dataset and the fix works as expected...
