### ISSUE TITLE
Can't add servlets in an OSGi plugin in 5.3.8.4 and 21.03

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#20286]
**Describe the bug**
We're upgrading OSGi plugins for version 5.3.8.4 (LTS) but all the custom servlets are no longer accessible and I'm not sure about Filters. The logs return an error:

[22/04/21 07:19:27:567 GMT] ERROR lang.Class: Error initializing OSGIProxyServlet
javax.servlet.ServletException: Error initializing OSGIProxyServlet
at com.dotmarketing.osgi.OSGIProxyServlet.service(OSGIProxyServlet.java:64) ~[dotcms_21.03_999999.jar:?]`

**To Reproduce**
1. Build the https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.webinterceptor plugin using gradlew jar
2. Deploy the fragment and the plugin on demo.dotcms.com
3. Try to access https://demo.dotcms.com/app/helloworld?action=wrap
4. Check the logs: you'll see the OSGIProxyServlet error

This happens to all the servlets I've tested so far, viewtools work fine. We've also not been able to find a workaround for this so our upgrade is halted for now.

**Comment by wezell** [comment]
No, the support for the OSGI "whiteboard" and servlets/filters has been deprecated.  There are two ways you can go to use servlet/filter functions:
1. You can refactor them into WebInterceptors - it is a fairly straight forward process to do so. 
2. You can use this Utility Class `TomcatServletFilterUtil` to register your filters/servlets in your OSGI Activator:

https://github.com/dotCMS/com.dotcms.csrffilter/blob/master/src/main/java/com/dotcms/csrf/filter/TomcatServletFilterUtil.java

**Comment by Zakinator123** [comment]
@wezell I tried bringing in the TomcatServletFilterUtil into our Spring MVC based OSGi plugin and ran into [this exception](https://github.com/dotCMS/com.dotcms.csrffilter/blob/02a5398f5f44881f8723df732f9251fc5b7e32a6/src/main/java/com/dotcms/csrf/filter/TomcatServletFilterUtil.java#L39) despite having everything set up similarly to the csrffilter plugin example you linked. Furthermore, [line 66](https://github.com/dotCMS/com.dotcms.csrffilter/blob/02a5398f5f44881f8723df732f9251fc5b7e32a6/src/main/java/com/dotcms/csrf/filter/TomcatServletFilterUtil.java#L69) in the TomcatServletFilterUtil will be deprecated with Tomcat 9, which is coming soon to dotCMS. Do you have any further guidance on how to proceed with 

We have a big custom plugin that heavily uses Spring very much like [this plugin seed](https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.spring), and we'd prefer to not have to refactor the whole thing to user WebInterceptors and take Spring out.

Do you think it would be alright to have a WebInterceptor delegate to the Spring DispatcherServlet by calling the DispatcherServlet's `dispatcherServlet.service(HttpRequestServlet request, HttpResponseServlet response)` or something like this?

Please give guidance on how to proceed - if refactoring to WebInterceptors is the only way then so be it, but that would definitely be the last resort.

**Comment by wezell** [comment]
@Zakinator123 You should absolutely try to have a WebInterceptor delegate to your Spring DispatcherServlet - you'll probably need to do some init work on the Spring DispatcherServlet to give it context but this should totally work.

Not sure what is up with the exception you are seeing in the TomcatServletFilterUtil  but you are right to point out that it won't be supported future forward. I haven't dug into the guts of Tomcat 9 but I'd hope that it will (better) support dynamic servlet registration even after the default Web Context is stood up.
