### ISSUE TITLE
Content palette in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20284]
We're adding a content palette in the sidebar that will allow users to create content faster

### How it works

1. Drag and drop a content type in a container
2. Start filling the form 
3. Save and publish
4. Content will be created and add it to the container.

### Design
https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=386%3A736

### Prototype
https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=417%3A10038&scaling=min-zoom&page-id=386%3A736

**Comment by fmontes** [comment]
We need to remove some content types from the pallete.

We need to do this by hardcoding a list until we do It dynamically:

<img width="467" alt="Screen Shot 2021-08-16 at 4 53 39 PM" src="https://user-images.githubusercontent.com/751424/129639052-be743f8b-b20e-4266-a798-7423d9a8162d.png">

**Comment by fmontes** [comment]
The "full starter" looks broken.

<img width="2176" alt="Screen Shot 2021-08-16 at 5 05 54 PM" src="https://user-images.githubusercontent.com/751424/129639899-b545c966-8d31-4937-a10f-117355128e76.png">

**Comment by fmontes** [comment]
1. Create a config var in `dotCMS/src/main/resources/dotmarketing-config.properties`
2. `CONTENT_PALLETE_HIDDEN_CONTENT_TYPES`
3. And add: Host, Vanity URL, Language Variables and Personas

**Comment by fmontes** [comment]
I left comments in the code review for @hmoreras

**Comment by bryanboza** [comment]
Fixed, now we have the content pallet running and working on release-21.10
