### ISSUE TITLE
HTTP 301 redirect loop when using Vanity URLs to remove trailing slashes

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#20280]
**Describe the bug**
A Vanity URL with a 301/302 HTTP redirect from a URL with a trailing slash to the same URL (a page, not a folder) without a trailing slash will loop indefinitely redirecting to the URL with no trailing slash.

This issue does not occur on 5.1.6, it does occur on 5.3.8.x. We observed this during an upgrade.

**To Reproduce**
1. Go to https://demo.dotcms.com/dotAdmin/#/c/vanity-urls
2. Create a new Vanity URL 
  Uri:` /redirect-me/`
  Action: 301
  Forward to: `/redirect-me`
3. Publish
4. In another browser/wget/curl visit https://demo.dotcms.com/redirect-me/
5. dotcms first returns a 301 redirect from `/redirect-me/` to `/redirect-me` as expected
6. however, the request for `/redirect-me` returns a 301 redirect to `/redirect-me` looping indefinitely 

It does not seem to matter if these urls corresponds to existing content on the site or not.

<img width="581" alt="Screen Shot 2021-04-20 at 10 37 29 PM" src="https://user-images.githubusercontent.com/628954/115497500-04092880-a229-11eb-8e3d-08f877538656.png">

**Comment by wezell** [comment]
PR:  https://github.com/dotCMS/core/pull/20363

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 /// Postgres // FF
