### ISSUE TITLE
Create integration test for Static publish

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20297]

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/21182

**Comment by bryanboza** [comment]
Fixed, now we have the test running and all in green 
https://raw.githack.com/dotCMS/test-results/master/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.enterprise.publishing.staticpublishing.StaticPublisherIntegrationTest.html
