### ISSUE TITLE
UI: onclick event over a site in Apps doesn't cover the whole row

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20304]
More details on this video: 

https://images.zenhubusercontent.com/3729629/703bc90e-29a8-4154-8b5f-4ddea5fce0b3/kapture_2021_04_26_at_10_47_56.mp4

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core-web/pull/1658

**Comment by nollymar** [comment]
Passed internal QA: Now, it works as expected

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
