### ISSUE TITLE
Unable to use the login-as feature 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20319]
If you are logged as an admin and you try to login as any other user we are showing an error and we are unable to use that functionality 

![image](https://user-images.githubusercontent.com/2641437/116604454-6201d400-a8eb-11eb-89d5-737ff07399c4.png)

**To Reproduce**
- Login as admin 
- Try to login as any other user 

**Expected behavior**
If you are an admin user you should be able to login as any other user 

**Desktop (please complete the following information):**
Tested on release-21.05 // Postgres // FF

**Comment by erickgonzalez** [comment]
Unable to Reproduce.

https://user-images.githubusercontent.com/5278970/117197565-31b3ad00-ada5-11eb-8283-0e62d6e204da.mov
