### ISSUE TITLE
NPE trying to access to the tags portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20328]
We are unable to list the tags, when you try to open this portlet we are getting a NPE error and you can't see the list of tags 
![image](https://user-images.githubusercontent.com/2641437/116736644-655d9400-a9ad-11eb-95b7-29e3cd274c8f.png)

LOG: https://gist.github.com/bryanboza/5059e889af0f2a0e62f55415d18c23bb

**To Reproduce**
- Login as admin 
- Go to Content Model.--> Tags

**Expected behavior**
We need be able to list the tags without problems 

**Desktop (please complete the following information):**
Tested on release-21.05 // Postgres

**Comment by erickgonzalez** [comment]
Not able to reproduce in release-21.05

**Comment by bryanboza** [comment]
Seems this is related to the browser, unable to reproduce on chrome, but still happening on Safari, since this is a supported browser, we need to fix...
![image](https://user-images.githubusercontent.com/2641437/117076265-594a3d00-acf3-11eb-9460-784cda23e0ea.png)

**Comment by jdotcms** [comment]
Fixed, approve internal
<img width="699" alt="Screen Shot 2021-05-17 at 11 43 29 AM" src="https://user-images.githubusercontent.com/19578350/118533312-29dcfc80-b705-11eb-80c1-5ca8f4266053.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Now we are able to use the tags portlet without errors.
