### ISSUE TITLE
Change the bundle output to tar/gzip in PushPublisher 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20325]
This is when doing normal push publishing. Currently it returns a DirectoryBundleOutput, so files are added to the folder and the folder is compressed at the end. 

The only one that returns TarGzipBundleOutput is the one used when downloading a bundle. So we are missing out on the performance enhancements related to this (~30%) when doing PP.

**Comment by dsilvam** [comment]
Passed Internal QA: Tested PP running both sender and receiver on Docker on the `21.06-prerelease` image

**Comment by bryanboza** [comment]
Fixed, tested doing some quick regression over PP and everything looks good
