### ISSUE TITLE
Improve performance of upgrade task Task201014UpdateColumnsValuesInIdentifierTable

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20336]
This task takes more than an hour to execute on datasets with more than 100.000 contentlets.

More details: 
https://gist.github.com/dsilvam/11e5ebc174498921e7cfd571860f5fad

**Comment by nollymar** [comment]
It turns out that some triggers were affecting the performance of the UT. After retesting with the same dataset, the UT takes just a second.

**Comment by bryanboza** [comment]
Fixed, tested upgrading the provided dataset and now we have a better performance on this task.
