### ISSUE TITLE
Setting COOKIES_HTTP_ONLY=TRUE or COOKIES_SECURE_FLAG=always/https causes cookie duplication

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20334]
**Describe the bug**
Setting either of the properties `COOKIES_HTTP_ONLY=TRUE` or `COOKIES_SECURE_FLAG=always/https` will cause dotCMS to create duplicate cookies. 
This is reproducible on both master and LTS.
This causes 500 errors for sites that have a lot of cookies as the header gets overfilled and rejected. 

Ticket: https://dotcms.zendesk.com/agent/tickets/104029

**To Reproduce**
Using a clean demo starter
1. Set either `COOKIES_HTTP_ONLY=TRUE` or `COOKIES_SECURE_FLAG=always` for your environment
2. Add some cookies using the cookietool to `html_head.vtl` for the travel theme at `application/vtl/themes/travel/html_head.vtl`
For example, I added this:
```
$cookietool.add("testCookie1","testCookie1")
$cookietool.add("testCookie2","testCookie2")
```
3. Navigate to the demo homepage and open your browser tools. Check the cookies for the application and start navigating around the site. You will see these test cookies become duplicated. The number of duplications will vary greatly. 

 
**Expected behavior**
There should only be a singular copy of any given cookie.

**Additional context**
This occurs with either flag set, or both flags set. It does not occur when neither flag is set.

**Comment by swicken-dotcms** [comment]
Given the flags being set causing the issue the belief is that the issue is caused here:

https://github.com/dotCMS/core/blob/3283e9732fe28b329cf3fd3633534a76a6f4806d/dotCMS/src/main/java/com/liferay/util/CookieUtil.java#L187

I tried generating a new cookie instead of using the one existing in the request, and removing the resetting of path to see if those were causing issues but the problem persists. I do believe it has something to do with the path setting, as I end up with multiples of cookies when I reach new paths that generate them.

![image](https://user-images.githubusercontent.com/78741732/117156470-b8f42700-ad8b-11eb-8746-3bc21ea3ba09.png)

As you can see there are now multiple copies of the same cookie, each with different paths. The same behaviour is seen on live sites with different variations on the same 'domain'.

**Comment by swicken-dotcms** [comment]
Checked on auth (which is on 21.06) and I am still seeing duplicate cookies:

![image](https://user-images.githubusercontent.com/78741732/122263787-d2b57d80-cea4-11eb-8288-8ef2c0629268.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF

**Comment by wezell** [comment]
Looks like we should remove any leading and/or trailing `.`

**Comment by wezell** [comment]
Actaully, looking at this, we need to remove the CookieUtil.setCookiesSecurityHeaders method that tries to rewrite all cookies and instead rely on the `CookieServletResponse` wrapper to enforce the HTTP_ONLY and SECURE

**Comment by victoralfaro-dotcms** [comment]
After adding the cookies via velocity code at `html_head.vtl` and navigating around the site no cookies were duplicated.

![image](https://user-images.githubusercontent.com/64026161/122831403-147c6480-d2a7-11eb-97bf-33bee65e1564.png)
