### ISSUE TITLE
Create mock for the configuration

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20347]

**Comment by ivorpad** [comment]
<img width="474" alt="Screenshot 2021-05-07 at 09 33 40" src="https://user-images.githubusercontent.com/52452/117414349-50d24c00-af17-11eb-8619-51f855758787.png">

**Comment by ivorpad** [comment]
Updated

![Uploading Screenshot 2021-05-10 at 20.11.21.png…]()
