### ISSUE TITLE
[Content Types] : Deleting field is throwing an error

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20342]
Reported via Support: [103972](https://dotcms.zendesk.com/agent/tickets/103972)
Reproducible in dotCMS 5.3.6.3, and latest master

Deleting a field from a given Content Type is throwing an error related to a completely different field. The same thing happens when moving any field around. The error is related to a `Relationship` field, as it seems the code is having problems updating its properties.

**To Reproduce**
**NOTE: Please reach out to Jose Castro for the specific data source, and the steps to reproduce. This issue is not reproducible with the Demo Starter:**

**Expected behavior**
Users must be able to delete fields without problems.

**Additional context**
Went through the field delete logic with @freddyucv , and found a potential bug in our API.

**Comment by erickgonzalez** [comment]
This is breaking the relationships, aren't being saved at all.

**Comment by jcastro-dotcms** [comment]
Temporarily removing the `LTS: Next` label. As per the R&D Team, the original fix is causing problems in other places of the system, so the code changes need to be rolled back.

**Comment by erickgonzalez** [comment]
PR for fixing problems that the original PR caused: https://github.com/dotCMS/core/pull/20379

To backport this to LTS you will need both PRs:
#20344 and #20379

**Comment by bryanboza** [comment]
Fixed, tested with a provided data set and now we are able to delete the field without problems. Tested on release-21.06 // Postgres // FF
