### ISSUE TITLE
Setting Time Zone to PST causes Content Search to list incorrect Date/Time Field entries 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20361]
As reported in https://dotcms.zendesk.com/agent/tickets/104133 dotcms: 5.3.8.4
Verified in local 5.3.8.2 (Docker).

If the Locale is set to PST in System->Configuration, it causes Content->Search to read Date/Time fields that are set within 7 hours of the next day to display one day later in the list. 

If you open the contentlet, the Date/Time fields are unchanged.

**To Reproduce**
1. Set Locale to PST in System->Configuration/
2. Create a new contentlet and set one of the date fields to within 7 hours of the next day.
e.g: 5/21/2021 at 8:45 PM
3. Save the contentlet.
4. Go to Content-> Search & list that Content Type. The Date/Time field Date displays one day later than was set on the contentlet.

SET LOCALE TO PST:

![image](https://user-images.githubusercontent.com/49727631/117456932-5bd4ae80-af0e-11eb-9226-ae798c9c75cb.png)

SET TIME/DATE FIELD

![image](https://user-images.githubusercontent.com/49727631/117456888-4f505600-af0e-11eb-9309-304d7be5097c.png)

CONTENT->SEARCH LISTS IT ONE DAY LATER

![image](https://user-images.githubusercontent.com/49727631/117457061-7c046d80-af0e-11eb-9985-d9c8d358f3db.png)

**Comment by craigWagner99** [comment]
This looks like it's happening in reverse on the other side of GMT:
https://dotcms.zendesk.com/agent/tickets/104154

They are in Spain and the Content->Search list shows date/time fields as the _previous_ day

**Comment by wezell** [comment]
We need to test adding the TZdata package to our docker image and setting the server TZ via an environmental variable.

**Comment by swicken-dotcms** [comment]
It does appear adding TZdata package and configuring the timezone via the TZ variable resolves this issue. 

dotCMS picked up the timezone correctly automatically (I set it to PST) and when I set a contentlet date/time it appeared to function properly: 

![image](https://user-images.githubusercontent.com/78741732/123109316-21b16480-d409-11eb-8384-ca0e87754af6.png)

![image](https://user-images.githubusercontent.com/78741732/123109477-473e6e00-d409-11eb-9579-44222e370c7a.png)

**Comment by jcastro-dotcms** [comment]
Docker fix is already in master. It requires defining the timezone by setting the TZ env variable.
