### ISSUE TITLE
We need to create a bash script that imports Content types in our native json format 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20369]
The customer should be able to pulldown a dotCMS git repo with a folder containing the definition of CT and import them from a dotCMS instance via the CLT Which internally relies on the _**/api/v1/contenttype**_  endpoint to do the import/export 

The CLT will use internally CURL But it will initially be written in bash. or python. 
The idea is to be able to checkout a directory from say github and then push that directory into a dotCMS instance.

Define a folder structure that we can also use when generating bundles that can be used to push these assets into a dotCMS instance.

Best efforts for knowable IDs:  We will need to update the creation of sites, content types, folders and files and use a sha256 of their hostName+language+path as the identifier for these assets.  If that hash already exists in the db, we will just create a new UUID and use it instead.
See: #19443

Pass a directory  and push its content into a dotCMS instance.
1. Sites 
   - file extension pattern = `.site.json`
   - add site based on siteName
   - include identifier in the json
   
2. ContentTypes (should be the same format as we get from the API)
   - file extension pattern = `.contenttype.json`
   - do a find on the passed in directory for
   - if content type exists (by var) then we update
   - else we put a new content type
   
3. File Assets - via webdav (can reuse the webdav endpoint)
   - https://dotcms.com/docs/latest/scripting-webdav
   - Best efforts for knowable IDs:  We will need to update the creation of folders and files and use a sha256 of their hostName+language+path as the identifier for these assets.  If that hash already exists in the db, we will just create a new UUID and use it instead.
   - Use the bundle layout found here: https://docs.google.com/spreadsheets/d/1iO7lq23Rdcev_-sFB5WdX8-KrEsy96dUTdMhvHY8IrE/edit#gid=0

The scripts/files should accept ContentTypes/fields with and without inodes.  If the contenttype definition includes the inode  and they do not match the ones we have in the dotCMS instance, the script should fail.

**Comment by nollymar** [comment]
**Documentation and example:** https://github.com/dotCMS/core/tree/master/tools/cli

**Comment by nollymar** [comment]
**Internal QA:** This feature doesn't work with a community license

**Comment by wezell** [comment]
@rweiner doc is here:
https://github.com/dotCMS/core/tree/master/tools/cli

**Comment by nollymar** [comment]
New PR: #20658

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
According to the documentation of this script here:
```https://github.com/dotCMS/core/tree/master/tools/cli```

If you are importing a whole bundle and you get an error we need to continue with the other pieces, but if you are importing. a single content type or a a site and  you get any error, we need to stop the import and show a clear error in the log, we should not continue and import with errors.
 
- Right now if try to import a content type and the json file have errors, we are creating the content type without files and we are not showing errors in the script log, neither the dotCMS log. 

- Also we are returning a 200 code when we have errors in the import process. 

- If you try to import a site that already exist we are getting the error but we are returning 200 code 
```== dot-cli 2021-07-22T15:31:20Z Exporting config ...
== dot-cli 2021-07-22T15:31:20Z identifiers file is identifiers-2021-07-22T15:31:20Z
tee: /Users/bryanbozacastillo/Desktop/core/tools/cli/logs/site.log: No such file or directory
== site 2021-07-22T15:31:21Z Pushing Site
Verifying my.cool-bike.com against remote host.
 response code was 200
A site named my.cool-bike.com already exists.
== site 2021-07-22T15:31:21Z done.
```

**Comment by fabrizzio-dotCMS** [comment]
This is not an error. 
Simply I'm trying to figure out if there's a site already named "my.cool-bike.com" through a find by name operation and the result is 200. Because it already exists.

**Comment by fabrizzio-dotCMS** [comment]
new PR https://github.com/dotCMS/core/pull/20710

**Comment by fabrizzio-dotCMS** [comment]
A new card is created to deal with the CT update problem https://github.com/dotCMS/core/issues/20712

**Comment by fabrizzio-dotCMS** [comment]
I made a few changes on ContentTypeAPIImpl's save method that guarantee that when no site is set we use System-host as the default. Also fixed a small bug that would wipe out the incoming fields when no site-id was specified

**Comment by nollymar** [comment]
**Internal QA: Passed**

Now, if an empty host is sent, `SYSTEM_HOST` is set. But, if an invalid non-empty host is sent, the `default` host is used instead. It isn't a consistent behavior, however, it is how the API works

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now it is working better, new enhancements will be fixed in the new related card. other behaviors depends of the API. This is ok for now. 

Tested on release-21.07 // Postgres // FF
