### ISSUE TITLE
EMA - Allow developer to override proxy edit/preview url selectively

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20380]
Our EMA allows a global override of a site URL to proxy to for editing and preview.  This proxy URL points to a server or instance that is running the SPA/node server remotely and has to be accessible to the server/instance running dotCMS  The issue arises when there are multiple developers who each want to work on components locally and still be able to edit and preview their work.  There is no way to point EMA to one place for one user and another place for another. 

It would be nice to allow a developer to specify what url they want to proxy their request to - to pass a url param of the server to which they want to proxy edit mode.  This would allow developers to proxy edit mode to their local environments using ssh tunnels or tools like NGrok - https://ngrok.com/

Another use case - if a customer wants to use EMA for only a subsection of their site, e.g. our documentation site.  How can we enable EMA in those cases - on a folder specific basis?

**Comment by wezell** [comment]
We currently provide a plugin that incorporates this functionality.  It can be found here: https://github.com/dotcms-plugins/com.dotcms.ema-ovr

**Comment by fmontes** [comment]
We need to move the plugin to core
