### ISSUE TITLE
dotCDN Invalidation improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20389]
1. In the workflow invalidation action, we need to invalidate all the pages that the content is placed on.  To do this, we need to query the mutlitree table and find where the content is being reused and send invalidations for those pages.

2. Make sure to require the portlet in permissioning the Rest Resources

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/com.dotcms.dotcdn/pull/3

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
