### ISSUE TITLE
Some discrepancies found indexing metadata

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20386]
As it is known, binaries are indexed including these fields by default (and their corresponding `_dotraw` ): 
```
"author",
"contenttype",
"filesize",
"height",
"length",
"moddate",
"name",
"path",
"title",
"width"
```

Currently, the `_dotraw` is not generated for all fields: 

![Screen Shot 2021-05-13 at 1.01.24 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/b5a13ba3-64d9-4500-877c-71465e19a47d)

In addition to that, I found two more issues: 
1.  ~The field `metadata.moddate` is being indexed as a number instead of a date~. This issue won't be solved.
2. The folder `metaData` (under assets) used on previous versions is not deleted when we upgrade version.
3.  In previous versions, when the `metadata.content` was empty, the field was indexed as: 
```
metadata.content	NO_METADATA
metadata.content_dotraw	
```

Now, it is indexed as: 
```
 metadata.content 
```

**Comment by nollymar** [comment]
**Passed internal QA:**  Success

Now, metadata fields are indexed correctly:

<img width="691" alt="Screen Shot 2021-05-17 at 11 16 13 AM" src="https://user-images.githubusercontent.com/8741395/118522334-8a6a3a80-b701-11eb-8de4-25f748b1a4dc.png">

Besides, I have verified the `metaData` folder is deleted after an upgrade.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the problem after the changes. Tested on release-21.05 // Postgres // FF
