### ISSUE TITLE
[Content] : Many to One relationship not displaying in Content Search

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20399]
Reported via Support: [104034](https://dotcms.zendesk.com/agent/tickets/104034)
Reproducible in dotCMS 5.3.8.4, and latest master.

The **Content Search** portlet is not displaying a specific many-to-one relationship as expected. Even though relationships in ElasticSearch changed in more recent versions of dotCMS, the application needs to handle the appropriate queries to accomplish it.

**To Reproduce**
Please reach out to Jose Castro for the specific details.

**Expected behavior**
dotCMS needs to handle the required steps to display this type of related content.

**Additional context**
The customer has upgraded from dotCMS 5.1.6 to 5.3.8.4. Back in 5.1.6, relationships were stored differently, so they're expecting the UI to behave the same way it used to.

**Comment by nollymar** [comment]
**Note to QA:** Please test filtering by related content using different cardinalities. It is important to verify that the queries displayed in the Advance Search are correct and return the same results 

![Screen Shot 2021-08-23 at 3 54 54 PM](https://user-images.githubusercontent.com/8741395/130518596-314dfe56-3b0d-4489-a61c-c60b2cee0daf.png)


_Remember that the Content API returns 10 records by default, if you want more results add the limit to the url path. For example: `/limit/15`_

**Comment by fabrizzio-dotCMS** [comment]
Testing a One-sided Many-To-Many Relationship where I have two instances of the parent and 5 instances of the child and 
The two parents have 4 of the children assigned in common but only one parent has a relationship with one of the children as follows :
![Screen Shot 2021-09-01 at 16 31 27](https://user-images.githubusercontent.com/37148755/131754161-45d3466c-0981-4406-a48c-46b2466ba9a6.png)
![Screen Shot 2021-09-01 at 16 31 40](https://user-images.githubusercontent.com/37148755/131754169-c3df69ea-5236-47f6-9ae1-f1235421c4aa.png)

Then I apply a filter on the parent relationship field choosing the child that only belongs to one parent. (In the pics from above that would be `#5`)

The results shown on Content-search are accurate. Only the parent that has a relationship with child#5 appears. So far so good. The I hist show query.

![Screen Shot 2021-09-01 at 16 39 07](https://user-images.githubusercontent.com/37148755/131754584-ae6fa5e2-fed3-4c5f-9b04-a6039a862388.png)

The Query build for the CURL isn't accurate. If executed it returns the two parents. It should only show the one that actually holds the relationship with child#5.

**Comment by fabrizzio-dotCMS** [comment]
Tested with the customer Database with @jcastro-dotcms's help. The issue reported by the customer is fixed 
The Many to One Relationship filter works as expected.

**Comment by bryanboza** [comment]
Tested with a custom data set by @fabrizzio-dotCMS and it is working as expected. I will close this card
