### ISSUE TITLE
URL field values are not included in Pages exported from Content->Search

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20405]
As reported in https://dotcms.zendesk.com/agent/tickets/104204 v5.3.8.2 and tested in current Demo v21.04

**Describe the bug**
CSV files exported from Content->Search include the **url** field in the header, but all the values are empty.

**To Reproduce**
1. Go to Content->Search
2. Choose a Page content type
3. Select all for export
5. Export to CSV
5. See error

**Expected behavior**
CSV file should contain the values for the URL field.

![image](https://user-images.githubusercontent.com/49727631/118667331-8b5ea300-b7b9-11eb-8590-ff7a9a9abd45.png)

**Comment by john-thomas-dotcms** [comment]
Unfortunately, the only workaround for this appears to be to use the REST API to import/export content (instead of the import/export feature).

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
