### ISSUE TITLE
Using 'select all' on categories before deleting will delete even deselected items

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20400]
As reported in https://dotcms.zendesk.com/agent/tickets/104172 v5.1.6
Recreated on 5.1.6 and current Demo v21.04

**Describe the bug**
If you have more than 10 top-level categories or sub-categories and you select all of them (even the unseen ones), deselect a few, then choose 'Delete' it will delete even the deselected categories. 

**To Reproduce**
1. Create more than 10 top-level or sub-categories
2. Click the top select box to select all categories
3. Click the link to select all categories not listed on the screen
4. Deselect some of the categories
5. Click "Delete"

**Expected behavior**
ONLY those categories that were selected should be deleted.

**Actual Behavior**
All categories - even ones that are not selected - are deleted. 

**Screenshots**
SCREENSHOT 01 - CATEGORIES - only 10 of the total are displayed

![image](https://user-images.githubusercontent.com/49727631/118532679-da023380-b70c-11eb-86ea-969437368361.png)

SCREENSHOT 02 - Select All using the top select box

![image](https://user-images.githubusercontent.com/49727631/118532771-f1d9b780-b70c-11eb-9fce-b1a055e7c83b.png)

SCREENSHOT 03 - Click the link to select all of the Categories
![image](https://user-images.githubusercontent.com/49727631/118534283-a9bb9480-b70e-11eb-9ebe-573a596048bf.png)

SCREENSHOT 04 - Deselect a few categories

![image](https://user-images.githubusercontent.com/49727631/118532961-25b4dd00-b70d-11eb-84ba-7dcd5dd6cf87.png)

SCREENSHOT 05 & 06 - Delete... everything is deleted, even the deselected categories

![image](https://user-images.githubusercontent.com/49727631/118533069-41b87e80-b70d-11eb-816c-c6496a098efb.png)

![image](https://user-images.githubusercontent.com/49727631/118533113-48df8c80-b70d-11eb-8d59-7d29df842350.png)

**Comment by craigWagner99** [comment]
To make sure this is only happening on Categories and not ALSO happening on Content->Search:


1. Created 51 contentlets on Demo
2. Navigate to Content->Search
3. Select all on the page using the top select box
4. Click link to select all other contentlets
5. Deselected a few
6. Available workflow actions->Archive

Only the selected items (48 items) were Archived. 
The three I deselected were preserved.

Then to make sure, I filtered so I was just looking at those 48 archived items and:

1. Select all  on the page with select box
2. Click link to select all contentlets
3. Deselected a few
4. Available workflow actions->Archive

The ones I deselected were preserved.

So it looks like in current version, the Content->Search list is fine, but Categories has the bug.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22180/files

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22269/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, this is working better after the last changes. Tested on release-22.06 // Docker // FF
