### ISSUE TITLE
Introduce ability to request velocity-rendered fields values in the GraphQL request

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20407]
As a GraphQL Content API User I want to be able to specify in the GraphQL query if a given field should be returned velocity-rendered in the response.  

One way of achieving this would be by passing an GraphQL argument to the field indicating so. 

Example: 
```
{
  webPageContentCollection(query: "+identifier:911868a2-b1f5-475a-bd70-1def8a12f331") {
    title
    body(render: true)
    myTextArea(render: false)
    identifier
  }
}
```

**Comment by wezell** [comment]
This is how you get both the rendered and the raw version - using aliases

```
webPageContentCollection(query: "+identifier:11c6ce1a-bdfe-4468-af81-33b4be3ea6ed") {
    title
    identifier
    rawBody: body(render: false)
    renderedBody: body(render: true)
    myTextArea(render: false)
  }
```

**Comment by dsilvam** [comment]
Note to QA/Doc:

GraphQL Contentlet fields now take a "render" parameter that will return the rendered value of the field. It only works for field of types: WysiwygField, TextField, TextAreaField, CustomField, ConstantField.

For QA: Postman test is `GraphQL / Test Render Content Fields`

**Comment by victoralfaro-dotcms** [comment]
![image](https://user-images.githubusercontent.com/64026161/122136043-f45c2980-cdfe-11eb-8ce1-c93a1c6531a3.png)
![image](https://user-images.githubusercontent.com/64026161/122136169-253c5e80-cdff-11eb-9aa2-1dfc764d46e1.png)

**Comment by bryanboza** [comment]
Fixed, tested using the render parameter as in the provided example, also checked the postman test and both cases are working as expected. Tested on release-21.06 // Postgres
