### ISSUE TITLE
Set Cache-control header based on HTMLPage cacheTTL

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20412]
When caching assets, CDNs generally key off the `Cache-control` header.  Internally, dotCMS also cache pages (pageCache) for a set period of time which is configurable on a page by page basis.

When a page is set to pageCache for a specific period of time, say 60 seconds, we should also add a Cache-control header to the page so that external caches can also respect that time and timeout.

**Comment by erickgonzalez** [comment]
The easiest way to test this is to create a new page and set the CacheTTL other than default e.g `55`, then hit the page and check the headers.

**Comment by ivorpad** [comment]
All good. ![Screenshot 2021-06-04 at 18.52.29.png](https://images.zenhubusercontent.com/5eac6c48896abe40e7f6d73e/e450bde4-53a0-4234-93bc-e9367de45d44)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
