### ISSUE TITLE
Add a header if there is a matching vanity url

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20416]
It is hard to debug redirects or vanity urls in the dotCMS.  It would be very helpful if we included a http-header that indicated which vanity url has been triggered for any given request.

**Comment by ivorpad** [comment]
Works as expected

<img width="463" alt="Screenshot 2021-06-04 at 22 56 27" src="https://user-images.githubusercontent.com/52452/120861833-375d0800-c588-11eb-9fc9-a3c141f6b084.png">

**Comment by jcastro-dotcms** [comment]
Code changes are part of the dotCMS 21.06.2 LTS release.
