### ISSUE TITLE
Static publish could skip image

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20414]
**Describe the bug**
if you a page that generated the follow code: 

```
 <a class="thumbnail-classic-figure" href="/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w">
<img src="/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w/50q/Foto8.jpg" alt="Foto8">
</a>
```

The image files are created in to the bundle statically, so

if the URL `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w` is processed first the image file called `1200w` is created into the bundle in the folder `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg`
THEN when the URL `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w/50q/Foto8.jpg` is processed an Exception is throw because the `1200w` is already a file

in other hand, 

if the the URL `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w/50q/Foto8.jpg` is processed first then a file called `Foto8.jpg` is created in `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w/50q/`
THEN when `/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w` is processed a exception is throw because `1200w` is already a directory

**Comment by wezell** [comment]
This is a know issue where files and images use overlapping paths when being rendered.  The fix is in any implementation  always end your your /dA/  paths with the asset file name rather than as a folder. 

Bad
```
<img src="/dA/b6cf8343-1523-442f-b22f-05faef44d81b/Foto8.jpg/1200w/50q/">
```
Good
```
<img src="/dA/b6cf8343-1523-442f-b22f-05faef44d81b/1200w/50q/Foto8.jpg">
```
