### ISSUE TITLE
Hide Container/Content controls when inline editing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20427]
The container and content controls seem to lie on top of the Inline editing controls.

![Screen Shot 2021-05-21 at 1 26 44 PM](https://user-images.githubusercontent.com/934364/119175932-780d3b00-ba38-11eb-9d33-fc0130ebe9fd.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05. Now we hide those controls when you are editing the text
