### ISSUE TITLE
Add Icon, Show on Pallet to Content Type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20426]
We need to add the Icon picker and a sort_order to the content type screen and the db.  The icon selected will be displayed wherever we need to show the content types icon, for example, in the content type listing screen:

![Screen Shot 2021-05-21 at 11 19 17 AM](https://user-images.githubusercontent.com/934364/119160598-70449b00-ba26-11eb-9ab2-e06bb35b479c.png)

For the show on pallet, in the database, we are going to need to add an int field that will store the order on pallet for the content type.  If that is set to 0, the content type will not be shown on the pallet, otherwise the idea is that the content types will show up in that order on the new content pallet.

Pallet design TBD....

**Comment by fmontes** [comment]
"Checkbox" is for "show on Pallet"

Maybe the field in the db is pallet_order, which if it is `<=0` we don't show it.

**Comment by erickgonzalez** [comment]
- [X] Add new fields to .sql files.
- [X] UT to existing clients to add new fields.
- [X] ContentType Bean.
- [X] Factory and SQL's.
- [X] API level
- [X] Resources
- [X] Check import starter without new fields (use old starter).
- [X] Check export starter.
- [X] Check import starter with new columns.
- [X] Check PP
- [X] Check GraphQL

**Comment by fmontes** [comment]
This needs work because we need to add the icon selector web component in the edit content type dialog.

**Comment by wezell** [comment]
The `ContentType` object, when `contenttype.icon` is called, should return either the icon or the basetype's icon if the icon is not set.  This can be evaluated lazily in the ContentType.java

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF
