### ISSUE TITLE
Add a mechanism to prevent folders from automatically copying title field to the name field.

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20424]
**Describe the solution you'd like**
Please provide a mechanism to prevent folders from automatically copying the title field to the name field. 

A new property `AUTOPOPULATE_FOLDER_NAME_FIELD` should be created (default value will be true). 

When a property is set to false, the name field should not be auto-populated.

**Comment by c9482** [comment]
Few suggestions:

- For a new folder, the name field should still be defaulted
- The suggested name field should be all in lower case 
-  Or provide mechanism to plug in a custom script overriding this functionality

**Comment by swicken-dotcms** [comment]
Follow up ticket: https://dotcms.zendesk.com/agent/tickets/110051

Re-opening this issue.

**Comment by erickgonzalez** [comment]
Another Follow up ticket https://dotcms.zendesk.com/agent/tickets/110303

**Comment by erickgonzalez** [comment]
Note to QA:

1- Start dotcms.
2- Create a folder
3- Check that the folder name is autopopulated.
4- Run the following curl:
```
curl --location 'http://localhost:8082/api/v1/system-table' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "key":"AUTOPOPULATE_FOLDER_NAME_FIELD",
    "value":"false"
}'
```
5- Create a new folder.
6- Folder Name field should not be autopopulated.

**Comment by dsolistorres** [comment]
QA Internal Approved:
The folder name isn't autopopulated when `AUTOPOPULATE_FOLDER_NAME_FIELD` property is set to false.
![image](https://github.com/user-attachments/assets/329acd1a-c24a-4c5d-b80e-cd8a9fa1edab)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b00ffaf**, Docker, macOS 14.5, FF v126.0.1
