### ISSUE TITLE
We are not listing the selected push environments when you try to push something

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20433]
UI: After change the component, now we are not listing the selected environments when you try to push something, you need to click in the drop down to see the environments selected. When we open the push modal we are just displaying a `Select Environment` text and you need to click here to see the list 

We need to avoid that extra click, and list the ones that was previously selected in the same component 

![image](https://user-images.githubusercontent.com/2641437/119405605-c28ff100-bc9e-11eb-98ba-9745fabcb1a3.png)

**Desktop (please complete the following information):**
Tested on release-21.05 // FF

**Comment by nollymar** [comment]
PR Core-web: https://github.com/dotCMS/core-web/pull/1674

**Comment by nollymar** [comment]
Passed internal QA:

<img width="375" alt="Screen Shot 2021-06-10 at 10 55 29 AM" src="https://user-images.githubusercontent.com/8741395/121566098-c8960980-c9e2-11eb-800a-db4126487b9c.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
