### ISSUE TITLE
unable to access metadata attribute directly from vtl files 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20457]
We have always supported this format to access the metadata attribute from vtls

```
#foreach($file in $dotcontent.pull("+contentType:FileAsset +metaData:image/jpeg",2,"modDate desc"))
    <h3>MetaData:</h3>
    <p>$file.metaData</p>
    <ul>
    ##Loop through all metadata field key, values
    #foreach($field in $file.metaData.entrySet())
        <li><b>$field.key</b> $field.value</li>
    #end
    </ul>

    <p>Content type: $file.metaData.contentType</p>
    <p>File Size: $file.metaData.fileSize</p>
#end
```

We lost these capabilities after the recent changes on the metadata APIs

as a workaround customer could still gain access to the metadata attribute through the fileAsset attribute like this:

```
#foreach($file in $dotcontent.pull('+basetype:4 +metadata.contenttype:image/*', 3, 'modDate'))
name : $file.fileAsset.name <br>
size : $file.fileAsset.fileSize <br>
width : $file.fileAsset.width <br>
height : $file.fileAsset.height <br>
#end
```

**Comment by nollymar** [comment]
**Passed internal QA:** Now, testing something like: `$dotcontent.find('4e62f9c1-ef60-45d0-b93c-cdf52a581fc6').metaData.title` on a page, displays the image title.

**Comment by bryanboza** [comment]
Fixed, now we are able to get this information via vtl files.. Tested on release-21.06 // Postgres // FF
