### ISSUE TITLE
[REST] : Filtering Endpoint in User Resource is incorrectly parsing some parameters

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20450]
Found when working on Support: [104264](https://dotcms.zendesk.com/agent/tickets/104264)
Reproducible in dotCMS 5.3.8.4 LTS, and latest master.

The `includeAnonymous` and `includeDefault` parameters are not being respected when passed down to the Endpoint call. For example, using the Demo Starter, accessing the Endpoint with these parameters:

- http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/false/includedefault/false

Returns the exact 13 records as this call:

- http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/true/includedefault/true

This is incorrect because passing down `true` for both the `includeAnonymous` and `includeDefault` variables must include the `Default User` and the `Anonymous User` as part of the result set. That is, the total records should be 15.

Also, our official documentation does not provide enough details to use the Endpoint: https://dotcms.com/docs/latest/rest-api-endpoints#UserResourceRules . We need to describe what parameters are required, and optional.

**To Reproduce**
### Scenario # 1
1. Start up dotCMS, and log in with a user who has Back-End access.
2. Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/false/includedefault/false . Total results is 13.
3. Now, call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/true/includedefault/true . Total results is 13, which is incorrect.

### Scenario # 2
1. Start up dotCMS, and log in with a user who has Back-End access.
2. Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/start/3/limit/5 . Total results is 5, which is incorrect because we're specifying pagination between 3 and 5.

### Scenario # 3
1. Start up dotCMS, and log in with a user who has Back-End access.
2. Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/ . Total results is 1, which is correct. However, the `total` attribute is `13`, which is the total number of Users in the system. It should indicate the total results that were returned, not the total Users in the system.

**Expected behavior**
Filtering parameters must be respected.

**Additional context**
**NOTE:** By default, the `system` user is excluded from the list of results returned to the user. This is correct, and expected.

**Comment by hmoreras** [comment]
Still can reproduce scenario 2 and 3, under branch `release-21.06`

**Comment by erickgonzalez** [comment]
Scenarios #2 and #3 are not an issue because the `total` is the total amount of users that the query returned, in this case, no query sent so all users (13) are returned.

Even if your URL looks something like: `{{serverURL}}/api/v1/users/filter/limit/3/start/2` the `total` will be 13 but there are paginated, **limit means per_page and start means the page number**

But a bug was found when you hit `{{serverURL}}/api/v1/users/filter/` without specifying limit, we're setting to 1, now is set to 40.

**Comment by erickgonzalez** [comment]
after discussing this we created a new issue to refactor the UserResource to improve pagination: https://github.com/dotCMS/core/issues/20529 since it's working funky and is not using the new pagination like we use in other Resources.

**Comment by bryanboza** [comment]
Fixed, tested on release 21.06 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Code changes are part of the dotCMS 21.06.2 LTS release.
