### ISSUE TITLE
When generating a site statically, we need to generate the default language last.  

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20469]
When generating a site statically, we need to generate the default language last.  This will give us a 80/20 solution whereby customers will not be surprised when they visit a statically rendered page and it is in a different language than the default.

_Originally posted by @wezell in https://github.com/dotCMS/core/issues/20091#issuecomment-832022002_

**Comment by dsilvam** [comment]
Static publish not working on master. Sending back

**Comment by dsilvam** [comment]
Needs work: Default language is not the latest. In a test with four languages Spanish came last overwriting the others

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/823

**Comment by dsilvam** [comment]
**Passed Internal QA:** Default language generated last. 

Tested by: 
*  Creating a page in 4 languages and adding a piece of content in those four languages. 
* Configuring a `STATIC` endpoint with `static_publish_to=dotcms-static` so the bucket/folder gets overwritten by each language
* Then checking the content of the page at the bundle folder location: `/assets/static_publishing/01FBA1W1ZW6RDHBY2MZNBNC4PF-static/dotcms-static` 

Page/Content was in default language

**Comment by bryanboza** [comment]
After test this changes, seems this fix is working just for the Static pushing locally, when you try using S3, we still getting the order of the languages aleatory. 

We need some work here, need to fix this for S3 too...

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/826

**Comment by dsilvam** [comment]
Passed Internal QA: Default language last in both AWS s3 and Static endpoints

**Comment by bryanboza** [comment]
Fixed, now this is working for both environments, static and AWS... Tested on release-21.07 // Postgres

**Comment by jcastro-dotcms** [comment]
The following commit is required for this fix, but it's not referencing the GitHub ticket correctly: https://github.com/dotCMS/enterprise/commit/f509d66b06e36360567c7732a4adc10337b269a9
