### ISSUE TITLE
Full image path showing on the "reuse content" popup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20460]
I believe this is due to the new metadata changes but am not sure.

If you have a file asset content type and the fileAsset field is checked show on menu, we are displaying the full server path when you try to add the content  object to a page.  You can see this on demo with the "Image" file type.  

![Screen Shot 2021-05-28 at 10 05 08 AM](https://user-images.githubusercontent.com/934364/119996024-3d595480-bf9c-11eb-8aed-dddc20177860.png)

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
