### ISSUE TITLE
Automate detection/restart when PublisherQueueJob is not running

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#20475]
**Is your feature request related to a problem? Please describe.**

Customers semi-regularly run into an issue where Push Publishing fails to work properly because the PublisherQueueJob is not running.

There are several possible reasons why the job could not be running, but the ultimate problem is that:
1. Push Publishing fails silently (PP bundles get added to the queue without errors, but just never get pushed).
2. There's no way to tell what the problem is without digging deep into the logs, and
3. Restarting the job requires manual intervention by server administrators (either our own Cloud Engineering team, or the customers' IT department).

**Describe the solution you'd like**

When a bundle is added to the queue, perform a check to verify that the PublisherQueueJob is running.  If it's not running, then:

* Ideally: Restart the job.
    * And write a log message indicating that the problem was found and fixed - so we can see if there's a persistent problem with this on particular systems.
* Alternately: Log a notification - both in the UI and in the logs - that says what the problem is.

**Describe alternatives you've considered**

We could potentially add this check to the Integrity Checker, rather than when a bundle is pushed.  But this would be less than ideal, because it would require a manual check to detect the problem.

**Additional context**

We see this problem regularly on Cloud customers.

**Comment by john-thomas-dotcms** [comment]
One customer reported a similar issue.  In this case, the PP job was running, but it turned out the issue was caused because the "On Misfire" setting for the job was blank (when it should have been set to "Run Once".

So, this feature needs to both check that the job is running, and make sure that all settings for the job are correct.

**Comment by wezell** [comment]
It seems like the PublisherQueueJob was either dead or stuck in some sort or deadlock.  We need to figure out the case where this job is being descheudled.

Also, we should always print something in the next Run and Misfire Instructions - we need to change the jsp code to show more information

**Comment by wezell** [comment]
It would be good to have an idea of why this is happening - 

- Is a throwable being thrown?
- Is there a db deadlock that is stopping the job?

**Comment by wezell** [comment]
See also #20487

**Comment by wezell** [comment]
Closed and will reopen if we see again

**Comment by swicken-dotcms** [comment]
https://dotcms.zendesk.com/agent/tickets/110049 Related ticket, customer is on 22.09

**Comment by wezell** [comment]
Issue was fixed in 22.10:

#23041
