### ISSUE TITLE
Modify ImageServlet to migrate images set in company_logo to dotAssets

### ISSUE THREAD

**Issue by ivorpad** [dotCMS/core#20478]
- Verify in the service if there's an image set in the database. If the image is set as a dotAsset we bail, otherwise migrate the current image to dotAssets
- Forward the company_logo to dotAssets if it's set in the database

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/20503

**Comment by fmontes** [comment]
This one don't need QA because we're sending to QA the epic.
