### ISSUE TITLE
[Push Publish] : Pushed content is not visible because of dead Reindex Thread

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20487]
Reported via Support: [104309](https://dotcms.zendesk.com/agent/tickets/104309)
Reproducible in dotCMS 5.3.8.4, and latest master.

The customer has a Push publishing setup composed of one sending instance, and three receiving instances. Pushing a piece of content worked in all three of them. However, the content was not showing up at all in one instance, even though the status of the push was successful.

Upon further inspection, we noticed that the Reindex Thread was not processing any content at all. We proceeded to manually restarting the thread, and it all went back to normal.

**To Reproduce**
We haven't been able to reproduce this behavior locally. It happens randomly, under unknown circumstances.

**Expected behavior**
The system should be able to restart the Reindex Thread if it's not available.

**Additional context**
We have an internal routine that we use to restart the Reindex Thread. If a code fix is not feasible, we can automatically execute the routine every X minutes so that the thread is restarted if necessary.

**Comment by wezell** [comment]
dupe
