### ISSUE TITLE
License present, but not from the license pool

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20489]
**Describe the bug**
This is happening in auth.dotcms.com.

Is trying to rewire the cluster every minute.  It has a license, but not from the license pool.

![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/1dd50270-3e81-479e-8fc8-4fd8326eaeee)

It makes dotCMS think that there is no licensed servers:

![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/e6f086aa-f84d-498d-9b40-45d5d3b0f88d)

Will said: I just tried to apply the matching license and it failed and then I applied another license and it took network tab looks normal now but I still see it rewiring all the time

**Comment by wezell** [comment]
Keep in mind that this is a dockerized environment and that the `/dotsecure` folder is being recreated on every startup.

**Comment by wezell** [comment]
Cannot reproduce since we fixed the oom exception
