### ISSUE TITLE
Error adding a new pice of cotnent to a page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20486]
If you create a new page and then try to add a new piece of content to the page, we are getting an NPE error 
Here the log: 
https://gist.github.com/bryanboza/c4b10122088c7637431541d985b56ee3

**To Reproduce**
- Create a new page 
- Try to add a new piece of content to the page 
- Check your log 

**Expected behavior**
We should be able to add new pieces of content without problems 

**Desktop (please complete the following information):**
Tested on master // Postgres // FF

**Comment by erickgonzalez** [comment]
Unable to reproduce.

**Comment by erickgonzalez** [comment]
After gathering more info, this is only reproducible on Safari.
