### ISSUE TITLE
Workflow: Can not import when next assign role or permissions not exists

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20488]
When importing a workflow scheme, if the next assign or permission roles do not exists should be able to import.

The next assign will be set to current user (anon)
And the permission will be skipped

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/20490

**Comment by hmoreras** [comment]
Now is possible to import the workflow attached in this comment without error, under branch `release-21.06`  
[workflow-schema-work-change-request-preprod2.json.zip](https://github.com/dotCMS/core/files/6633096/workflow-schema-work-change-request-preprod2.json.zip)

**Comment by bryanboza** [comment]
Fixed, tested with the provided example and now I'm able to import without problems

**Comment by jcastro-dotcms** [comment]
Code changes are part of the dotCMS 21.06.2 LTS release.
