### ISSUE TITLE
Error retrieving content references in multilingual setup

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#20494]
**Describe the bug**
You can't view/edit a piece of content when it has a reference in the non-default language on a page that is not available in the default language. For instance when de default language is EN and you have a piece of content on it that is available for EN + NL and the NL piece is placed on a page that is only available in NL then you can't open the piece of EN content.

**To Reproduce**
1. Go to demo.dotcms.com
2. Open the 'Booking date selector' code widget (which is located on the homepage) and create a Spanish version of it (note: it could be any content)
3. Save/publish the Spanish version of the content
4. Create a new Page Asset only in Spanish and put the Spanish 'Booking date selector' on it. This all works fine
5. Open the homepage in EN and open the 'Booking date selector' OR open the 'Booking date selector' in the content tab -> ERROR

**Expected behavior**
You should be able to edit the content

**The cause**
When calculating the references the multitrees are retrieved and the code looks for a page in the language of the content _that you are opening_, not the language of the content reference. 
https://github.com/dotCMS/core/blob/702102e2cbf772c99c4b414d09a15081d86a5708/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1195
I think there should be something like 'multitree.getLanguageId()', or if that does not exist you probably first need to look up the reference's language and use that. 

**Workaround**
A workaround is to create a default language version (EN in the example) for each page

**Comment by Xander-Steinmann** [comment]
[stacktrace.txt](https://github.com/dotCMS/core/files/6606644/stacktrace.txt)

**Comment by Xander-Steinmann** [comment]
I tested it successfully locally by replacing the above code:
`            final IHTMLPage page = loadPageByIdentifier(tree.getParent1(), false,
                            APILocator.getUserAPI().getSystemUser(), false);
`
But I'm not sure whether this will cause issues in some cases.

**Comment by wezell** [comment]
@Xander-Steinmann can you generate a PR with your changes?

**Comment by dsilvam** [comment]
Note to QA: 
* References shown are now taking into consideration the selected language, meaning the parent page needs to have a version in the selected language so the reference can be included
* 'Persona' column was added

**Comment by victoralfaro-dotcms** [comment]
Created Spanish version of booking date selector.
![image](https://user-images.githubusercontent.com/64026161/127919054-d0b16752-0813-4870-b2d0-d2cc5c1b0be7.png)
Created Spanish asset page.
![image](https://user-images.githubusercontent.com/64026161/127919448-302a7c49-8db8-4b71-9a7a-84cf34a87e8a.png)
Content was able to be edited.
![image](https://user-images.githubusercontent.com/64026161/127919946-4aba3510-9c8d-4c95-8636-9a05af4890f3.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF
