### ISSUE TITLE
Many-to-many relationships between a single content type removes relationships on save/publish

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20491]
As reported in https://dotcms.zendesk.com/agent/tickets/104279 v5.3.8.4
Recreated in demo v21.05

If you have a content type that has a many-to-many relationship to itself it can cause other contentlets to lose that relationship. 

The log does not throw any errors.

1. Create a content type with a many-to-many relationship to itself.
2. Create 3 contentlets, A, B, C
3. On A, add a relationship to B and C - save/publish
4. On B add a relationship to A and C - save/publish
5. On C add a relationship to A and B - save/publish
6. Reopen A, the relationship to C has been lost
7. Re-add C to A - save/publish
8. Reopen B, all relationships are lost.
9. Re-add A and C to B - save/publish... The relationships appear to hold at this point. But you get an unsaved changes warning when you re-open even if you don't make changes.
10. However if you add a relationship to a different content - D - the relationships break down again.

STEP 3
![image](https://user-images.githubusercontent.com/49727631/120706379-a2221c80-c47e-11eb-8214-a33db2a247de.png)

STEP 4
![image](https://user-images.githubusercontent.com/49727631/120706416-ad754800-c47e-11eb-98b5-017d93790345.png)

STEP 5
![image](https://user-images.githubusercontent.com/49727631/120706454-ba923700-c47e-11eb-80fc-c8e288a85d63.png)

STEP 6
![image](https://user-images.githubusercontent.com/49727631/120706488-c847bc80-c47e-11eb-9226-ada79867fb68.png)

STEP 7
![image](https://user-images.githubusercontent.com/49727631/120706525-d564ab80-c47e-11eb-9841-b97a6e3466b6.png)

STEP 8
![image](https://user-images.githubusercontent.com/49727631/120706581-e57c8b00-c47e-11eb-915f-6c61ea0ca78d.png)

STEP 9
![image](https://user-images.githubusercontent.com/49727631/120706640-f7f6c480-c47e-11eb-9b7d-f809d0e10c2d.png)

RELATIONSHIPS HOLDING
![image](https://user-images.githubusercontent.com/49727631/120706753-1492fc80-c47f-11eb-8b27-c72215ee9e5f.png)

![image](https://user-images.githubusercontent.com/49727631/120706881-4015e700-c47f-11eb-9e0a-14a120f7301d.png)

![image](https://user-images.githubusercontent.com/49727631/120706906-4906b880-c47f-11eb-874b-a8710b4b8136.png)

BUT YOU GET THE UNSAVED MESSAGE WARNING
![image](https://user-images.githubusercontent.com/49727631/120706854-38eed900-c47f-11eb-9818-b4bb88252915.png)

STEP 10
![image](https://user-images.githubusercontent.com/49727631/120706969-5de34c00-c47f-11eb-9a41-e206333eac8b.png)

RELATIONSHIPS ARE LOST AGAIN
![image](https://user-images.githubusercontent.com/49727631/120707018-6a67a480-c47f-11eb-9870-1a0bd3c3dba8.png)

**Comment by dsilvam** [comment]
Passed Internal QA: Going through steps 1 to 5 and when reopening A,B and C the related content was not lost.

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now I'm unable to reproduce the problem

**Comment by jcastro-dotcms** [comment]
This issue is NOT reproducible in neither dotCMS 5.3.8.6 nor 21.06.2 LTS releases.
