### ISSUE TITLE
Problems trying to login from a PC if you are using mssql as db

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20499]
We are getting an exception when you try to log in using a PC on an instance with MsSQL as DB. We get this exception and you are unable to login. 

Here the error: https://gist.github.com/bryanboza/e40090d38b2380e02c440f9ac69faa4a

**Expected behavior**
We need be able to login from any device using any of the supported browsers 

**Desktop (please complete the following information):**
Tested on release-21.05 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05.1 branch using docker and now we are able to login in both environments, Mac and PC without problems

**Comment by jcastro-dotcms** [comment]
Code changes are already present in dotCMS 21.06.2 LTS release.
