### ISSUE TITLE
Workflows: Can not copy a workflow with Notify Assigned Actionlet is used

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20501]
Steps

1) Go to any workflow.
2) Open any step and creates a new action, add the notify assignee actionlet (not need to modify any actionlet parameters)
3) Try to copy the workflow

Result:

The WF can not be copied b/c the notify assigned actionlet

Expected

The WF should be copy fine

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
