### ISSUE TITLE
Unable to create a multilingual blog

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20505]
Easy to reproduce:

1. Go to the demo site
2. Go to blogs - open a blog
3. change the language selector to spanish
4. In the Populate Espanol content with the english content popup - say yes
4. You get a portlet error

**Comment by victoralfaro-dotcms** [comment]
Attached video of missing error.

https://user-images.githubusercontent.com/64026161/123883578-92271c80-d906-11eb-8013-193c91838a08.mov

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes

**Comment by jcastro-dotcms** [comment]
This issue is NOT reproducible in the dotCMS 5.3.8.6 LTS release.
