### ISSUE TITLE
Create a "Bulk Move" Action for Content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20504]
We need to create a move bulk action on the content search screen.  This action should be available like the other bulk actions are and should allow a user to select host or folder to which they would like to move the content.

![Screen Shot 2021-06-08 at 1 43 33 PM](https://user-images.githubusercontent.com/934364/121233413-a96f6e80-c860-11eb-8a1a-8eac00a868f8.png)

Once they have selected the host/folder, they can hit the button to "Apply" the move and we would send the selected list of contents \(as a lucene query\) to an endpoint that would then perform the "move". Just like the bulk workflow actions, the endpoint will produce a report of the contents that were successfully moved.  We should be able to use the new BulkContentUpdate endpoint to effect the move.

Once moved, the important thing is that the moved contents will now inherit the permissions from where they have been moved to - if they were moved to the system\_host, they will inherit permissions from the content type.

Adding this this should take care of issues #20196 and #14736 and give customers a way update the permissions on any given content type.

**Comment by fmontes** [comment]
### Proptotype:
https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=1087%3A11702

**Comment by wezell** [comment]
We need to add the following to the `FolderSearchResultView`
```
    public boolean canAddChildren() {
        return true;
    }

```
 because it is possible to be able to "read" a folder but not be able to add to it.  For example a limited user might be able to put content into this folder:
```
//bigcompany.com/departments/human-resources/
```
but not:
```
//bigcompany.com/departments/ or //bigcompany.com/
```

If the user does not have canAddChildren on the folder, then the UI should disable the "send" button and show a message "You do not have add permissions to this folder"

**Comment by wezell** [comment]
Also, we need to add a placeholder to our text box that says:
"start typing for suggestions"

**Comment by erickgonzalez** [comment]
Current rules for Page/Folder selector: 

- a host search start with `//`. 
- type text, will look for pages/folders 
- when a host is selected should do a page/folder search right away. 
- when the user type a folder that do not exist an error message should be displayed indicating a new folder will be created.
- when there are empty result an error message should be displayed
- when use user do not have permissions to move to specific folder an error message should be displayed. 
 

Places where to test workflows in the UI: 

- Content Search: right click on list item, bulk action button, selected and item and in the right buttons. 
- Site Browser:  right click on list item
- Edito Mode: Top right button. under Properties button at the right.
- Tasks: bulk actions button,   selected and item and in the top right circular button.

**Comment by jdotcms** [comment]
Note For documentation:
On the Move Actionlet you can do something like this:
```
//default/$webapi.findIdentifierById($content.getIdentifier()).getParentPath()
```

In order to move a contentlet from one site to the default site, but keeping the same folder paths.

**Comment by bryanboza** [comment]
Need discuss about the permissions that I should have to move some asset

**Comment by swicken-dotcms** [comment]
Excluded from 5.3.8.6 as the changes are too major to backport.

**Comment by bryanboza** [comment]
Fixed, a list with problems and enhancements are reported in the new card: #20905
