### ISSUE TITLE
Mockito not being garbage collected in Java 11

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20506]
We use Mockito for rendering the HTML pages in processes like SiteSearch. When running these processes, a lot of instances are left uncollected, eventually throwing a `java.lang.OutOfMemoryError: Java heap space`. This seems to be after moving to Java 11 and GC changes. 

Solution is to stop using Mockito, expect for tests, and just use a skeleton implementation of the HttpServletRequest and HttpServletResponse.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/806

**Comment by dsilvam** [comment]
Passed Internal QA. Based on the feedback of: 
* Running site-search on auth
* Running PP between two docker instances 
* Results of different automated tests

**Comment by bryanboza** [comment]
Fixed, tested based in the last comment and everything is working ok. Tested on release 21.05.1 // MS-SQL // FF
