### ISSUE TITLE
Refactor UserResource filter endpoint

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20529]
The UserResource is not using our new Pagination methods, so we need to migrate this endpoint to a v2, that uses the pagination.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java#L218-L291

Example of the new Paginator that we use in our Resources:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/template/TemplateResource.java#L128-L174

**Comment by jcastro-dotcms** [comment]
**NOTE TO DEVS:** For testing purposes, it's easier to use the Full Starter which already has a lot of users.

### Test Scenario # 1
1. Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/false/includedefault/false . Total results is 13.
2. Now, call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/true/includedefault/true . Total results should be 15.

### Test Scenario # 2
Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/start/3/limit/5 . Total results must be 3, as both "start" and "limit" are inclusive.

### Test Scenario # 3
Call the filtering method of the User Endpoint like this: http://localhost:8080/api/v1/users/filter/ . Total results must be 13, as the Default and Anonymous Users are not included by default.

**Comment by fmontes** [comment]
### More tests:

http://localhost:8080/api/v1/users/filter/limit/100/includeanonymous/adasdfsd12213/includedefault/asdasasd

Bad values fallback to `false`.

Query by text: http://localhost:8080/api/v1/users/filter/query/bill

**Comment by jcastro-dotcms** [comment]
As per discussion with @dsilvam , the way parameters are specified in the filtering method in the `com.dotcms.rest.api.v1.user.UserResource` does not fit our REST standard. Filtering criteria must not be specified via path parameters, but as query String parameters. The new fix will include such changes as well, which means that the URLs to the Endpoint will change. This endpoint is not used anywhere inside the dotCMS back-end, so we're good.

I have updated the test scenarios [in my previous comment](https://github.com/dotCMS/core/issues/20529#issuecomment-1371193868) for both IQA and QA.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.02 // Docker // FF 

Note to doc: 

The follow parameters both are **OPTIONAL**, but if you don't send the default value is **FALSE**

```
includeanonymous
includedefault
```
