### ISSUE TITLE
Limited user breaks page.layout if not permissioned

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20527]
If you have a limited user who can edit pages but does not have permissions to edit "templates" on a site, and this user updates a page.layout in the system, it will cause the layout for the page to break and the page become unusable until the cache is flushed.  This is because the method retrieves the page layout from cache, modifies it (nulls out the inode) and then throws a permission error - leaving the object from cache dirty and 1/2 modified.

https://user-images.githubusercontent.com/934364/121723436-80dfb280-cab4-11eb-941a-6a61c8a321f0.mp4

Our rule is that if a user can edit a page, they can edit the page layout.

To reproduce, create a limited user with these permissions and try to edit a page layout.  The save will fail and the page will become unusable due to the dirty object in cache.

![Screen Shot 2021-06-10 at 10 29 27 PM](https://user-images.githubusercontent.com/934364/121622136-746b4380-ca3b-11eb-9763-07fe4a5d84f9.png)

**Comment by bryanboza** [comment]
After this change, now all the pages of the starter site are leaving locked by the admin user, not sure why but all the pages are locked, maybe we need take look of this.

**Comment by dsilvam** [comment]
Unable to reproduce. Not all pages are locked, just the same pages as previous two starters.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last release-21.06 // Postgres // FF
