### ISSUE TITLE
Logging in with a limited user fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20523]
If you try to login with a limited user - someone who does not have the sites portlet - you get kicked out because of the changes in #20393

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/site/SiteResource.java#L140

We use the site listing and current site api calls to populate the site selector in the top right corner of the admin.

![Screen Shot 2021-06-10 at 6 05 47 PM](https://user-images.githubusercontent.com/934364/121603683-247a8580-ca17-11eb-9fbe-e78d2aea689c.png)

**Comment by bryanboza** [comment]
NPE when you try to login as as limited user without site roles
Log: https://gist.github.com/bryanboza/18969f29eb835726eef22176e3b1c27d

FYI: Tested using pg as database.

**Comment by jdotcms** [comment]
this is not related to site resource, seems more related to the Pub/Sub framework

**Comment by bryanboza** [comment]
Fixed, the reporter error was moved to another card #20320
