### ISSUE TITLE
Folders under site are not ordered alphabetically 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20531]
When you add a new folder we need to order alphabetically but we are not ordering 
![image](https://user-images.githubusercontent.com/2641437/121734103-8d164080-cab1-11eb-90d1-8bc4fa1b4f56.png)

**To Reproduce**
- Login as admin 
- Add a new folder 
- Make sure was ordered in with all existing ones 

**Expected behavior**
We need to order the list of folders alphabetically 

**Desktop (please complete the following information):**
Tested on release-21.06 // Postgres // FF

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
