### ISSUE TITLE
Allow customization of Login page and reset password flow

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20543]
As reported in https://dotcms.zendesk.com/agent/tickets/104472 v5.2.8.3 

The reset password link on the dotCMS login page is not customizable. 

When using dotCMS with a service like SAML/LDAP, that password reset link is not ideal as it does not lead users to the proper password reset flow for the external account service. 

**Describe the solution you'd like**

A mechanism, such as a configuration setting, to customize the dotCMS login page. This should specifically include the ability to edit the password reset link.

**Comment by wezell** [comment]
This was done in #19970
