### ISSUE TITLE
UI for run the Move subaction

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20550]
Feedback: 
https://github.com/dotCMS/core/issues/20504#issuecomment-870671763
https://github.com/dotCMS/core/issues/20504#issuecomment-870673098
https://github.com/dotCMS/core/issues/20504#issuecomment-870675512

**Comment by hmoreras** [comment]
Current rules for Page/Folder selector: 

- a host search start with `//`. 
- type text, will look for pages/folders 
- when a host is selected should do a page/folder search right away. 
- when the user type a folder that do not exist an error message should be displayed indicating a new folder will be created.
- when there are empty result an error message should be displayed
- when use user do not have permissions to move to specific folder an error message should be displayed. 
 

Places where to test workflows in the UI: 

- Content Search: right click on list item, bulk action button, selected and item and in the right buttons. 
- Site Browser:  right click on list item
- Edito Mode: Top right button. under Properties button at the right.
- Tasks: bulk actions button,   selected and item and in the top right circular button.
