### ISSUE TITLE
Site Resource improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20557]
Related to #20393 

- We need to validate if the site already exists and return the correct message  as we print in the log: 
``` Field [hostName] must be unique```

- Need to validate if we can catch the exception and print just a line error in case already exist another site with the same name. Right now we are too noisy printing the complete jersey error 

- Need to update all the postman test to use "SiteIdentifier" instead "hostIdentifier" variable 

- Need to add a postman test that try to delete the default site

**Comment by jcastro-dotcms** [comment]
Changes were not back-ported to dotCMS 5.3.87.6 LTS because the code doesn't exist in there yet.
