### ISSUE TITLE
UI issues/improvements

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#20566]
- [x] 1) Reorder menu button needs the html rewritten. Currently it outputs a bootstrap button with two font awesome icons. This should use native dotCMS backend styles and inline svg icons. We do not load font awesome anymore.
- [x] 2) The add button on the content search screen has the 3 dot menu but should be using the + icon
- [x] 3) In the Content Search dialog "Content Type" should be first like its in the normal content search screen
- [x] 4) in the site browser the files/pages need to be listed most recent modified first

Reorder button screen shot
<img width="953" alt="menu-reorder-btn" src="https://user-images.githubusercontent.com/1561349/122986966-12c9a400-d36e-11eb-942c-93e399957dff.png">

Add button screenshot
<img width="1289" alt="plus-button" src="https://user-images.githubusercontent.com/1561349/122984289-d6e10f80-d36a-11eb-9103-41311b71e88b.png">

Content Search Dialog
<img width="662" alt="content-type-order" src="https://user-images.githubusercontent.com/1561349/122987243-61773e00-d36e-11eb-873e-3a6816a2eeb7.png">

List order wrong on file browser
<img width="1034" alt="Screen Shot 2021-06-23 at 10 00 46 AM" src="https://user-images.githubusercontent.com/1561349/123111354-d730e780-d40a-11eb-9512-85681d8ee72d.png">

**Comment by alfredo-dotcms** [comment]
Core-web PR: https://github.com/dotCMS/core-web/pull/1702/files

**Comment by alfredo-dotcms** [comment]
@rweiner once merged, this https://dotcms.com/docs/latest/navtool-viewtool#ExampleAddReorderButton needs to be updated with

```
#if ($EDIT_MODE && $PUBLISH_HTMLPAGE_PERMISSION)

      #set($_formId="dot_form_menu_$date.date.time")
      <form class="dotcms__navbar-form" action="${directorURL}" method="post" name="${_formId}" id="${_formId}">
        <input type="hidden" name="cmd" value="orderMenu" />
        <input type="hidden" name="hostId" value="${host.identifier}" />
        <input type="hidden" name="referer" value="${VTLSERVLET_URI}" />
        <input type="hidden" name="pagePath" value="${VTLSERVLET_URI}" />
        <input type="hidden" name="startLevel" value="1" />
        <input type="hidden" name="depth" value="2" />
        <a href="javascript:document.getElementById('${_formId}').submit();" class="reorder-menu-link" data-original-title="Reorder Menu">
            <i class="arrow-up"></i> 
            <i class="arrow-down"></i> 
        </a>
      </form>

 #end
```

**Comment by nollymar** [comment]
**Internal QA:** Needs work. 
Points 1 and 2 don't seem to be fixed. However, 3 and 4 are displayed as expected. 
<img width="1676" alt="Screen Shot 2021-08-04 at 4 47 55 PM" src="https://user-images.githubusercontent.com/8741395/128260286-a773147c-5411-4b90-9743-cc448f74dc1e.png">



<img width="279" alt="Screen Shot 2021-08-04 at 4 50 52 PM" src="https://user-images.githubusercontent.com/8741395/128260300-edf3a465-3d3e-4408-9bf6-bfda3a2b04a4.png">

<img width="1673" alt="Screen Shot 2021-08-04 at 4 45 15 PM" src="https://user-images.githubusercontent.com/8741395/128260688-2a01d2b4-5b42-4a9f-8300-207d490744de.png">

**Comment by alfredo-dotcms** [comment]
steps for #1
- change lines 82 to 87 in `header.vtl` in `/application/themes/travel` with https://github.com/dotCMS/core/issues/20566#issuecomment-880788529
![image](https://user-images.githubusercontent.com/37185433/128397161-b6dfbee0-e1ff-49ca-bc17-811fc6b438f9.png)

-edit a page
*this prob needs to be changed on starter (empty & full)

**Comment by nollymar** [comment]
Point #1 is working after applying the changes explained in the comment [above](https://github.com/dotCMS/core/issues/20566#issuecomment-893662851)

**Comment by alfredo-dotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/20772/files

*all icons that appear in a list view style must be replaced with a `+` icon

**Comment by nollymar** [comment]
Internal QA: Passed

After the latest changes, the icon displays correctly

![Screen Shot 2021-08-06 at 3 07 05 PM](https://user-images.githubusercontent.com/8741395/128566051-daaae04a-2af4-4d1b-a7fb-0e3d3e7a82f5.png)
