### ISSUE TITLE
Unable to create a new page using the system template on docker 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20585]
When you are using a dotcms instance that is running on docker, and you try to create a new page using the system template, we are getting a NPE and we are unable to create the page

Here the log: https://gist.github.com/bryanboza/053ff7c22b2a8d0dea2c43545e7381a6

**To Reproduce**
- Start a dotcms instance running on docker 
- Go to site browser 
- Try to create a new page using the system template 
- Check your log file 

**Expected behavior**
We should be able to create pages without problems 

**Desktop (please complete the following information):**
Tested on using the dotcms:21.06-prerelease // mssql

**Comment by erickgonzalez** [comment]
I think this is fixed by this https://github.com/dotCMS/core/pull/20593 but it's worth to test again.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF
