### ISSUE TITLE
Don't try to move or rewrite license.zip file on startup.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20591]
2 issues:
1. When starting up a dotCMS instance that has a license file under `/assets/license.zip` dotCMS will try to move/rename that file to a `imported_timstamp_license.zip`.  If the license file is mounted read only, it can cause the system startup to fail.

2. In an orchestrated environments where the license is mounted on the pods, for every new container that is started, it will make another copy of the license.zip resulting in multiple versions of the same license file to be copied again and again.  Let's just let the file be read in every time on startup, as this will not hurt anything.

**Comment by wezell** [comment]
actually, looking at this code, we should just set the environmental variable 

`DOT_ARCHIVE_IMPORTED_LICENSE_PACKS=false`

**Comment by wezell** [comment]
mislabeled a commit message - see 0171ab39b4

**Comment by fabrizzio-dotCMS** [comment]
I placed a license pack marked read-only under my assets directory and launched dotCMS in debug Mode. 
The pack doesn't get renamed if DOT_ARCHIVE_IMPORTED_LICENSE_PACKS is set to false. 
The server starts up correctly. I'm passing it.

**Comment by bryanboza** [comment]
Fixed, tested based on the info provided by @fabrizzio-dotCMS and now it works as expected
