### ISSUE TITLE
ESReadOnlyMonitorJob is killing the reindex process 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20607]
Related to #18366 

After the release-21.05. we merge the changes of this monitor, this is a job that runs every 5 minutes. Then, now when you try to run a reindex of a big database that takes more than 5 minutes, this job is killing the process and we are unable to finish the reindex.

We are getting a "read-only" notification and an error in the log 
![image](https://user-images.githubusercontent.com/2641437/123880065-1e354600-d8ff-11eb-84e2-a77352de9aed.png)

Log: https://gist.github.com/bryanboza/1ec66eef15d0c70dbf6c1227702b5812

**Expected behavior**
We need to be able to run a reindex job that takes more than 5 minutes 

**Workarround**
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java#L212

**Desktop (please complete the following information):**
Tested on release-21.06 // Postgres // FF

**Comment by wezell** [comment]
Please just make the `ESReadOnlyMonitorJob` a notification and have no business purpose.  It has caused too many issues for something that we have run fine without for years.

**Comment by dsilvam** [comment]
Passed Internal QA: ESReadOnlyMonitor not stopping the Reindex when no current active indices exist

**Comment by bryanboza** [comment]
Fixed, after this fix now we are able to reindex databases with a lot of registers without problems. Tested on release-21.06 // Postgres // FF
