### ISSUE TITLE
Not able to Create/Copy a Site

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20609]
We're not able to create/copy a site.

STR:
1- Go to **Sites** Porltet.
2- Click over **Add Site**.
3- Select any of the two options.
4- Fill the required fields.
5- Save/Activate.

There is no error shown at UI level, but at there is an error at the logs:  https://gist.github.com/hmoreras/4613a48dd29fe3725c39d4c1223295e6

Reproduced on master(6/30).

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF and I'm unable to reproduce

**Comment by jcastro-dotcms** [comment]
I was not able to reproduce this issue in neither dotCMS 5.3.8.6 nor 21.06.2
