### ISSUE TITLE
[Permissions] : Contentlets intermittently losing permissions

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20618]
Reported via Support: [104635](https://dotcms.zendesk.com/agent/tickets/104635)
Reproducible in dotCMS 5.3.8.5 LTS

The customer reported a situation in which their **PROD** instance started to intermittently redirect users to the dotCMS login page. After checking the logs, they noticed a lot of messages like this one:
```
19:31:33.612  WARN  servlet.VelocityServlet - User does not have permission in content: {CONTENT-TYPE-NAME}
```
The permissions via the dotCMS back-end were checked, and they were all normal, i.e., inheriting from parent. Since this was a production issue impacting users ability to interact with pages, they kicked off a full cache flush which resolved the issue.

**Additional context**
We believe this problem might be related to #19608 , which is already included in the 5.3.8.5 LTS release. Even though the issue is NOT the same -- because the permissions display correctly in the dotCMS back-end -- there seems to be something going on with this.

**Comment by wezell** [comment]
When this happens in a `5.3.8` version, can we get eyes on it before we flush cache?

**Comment by wezell** [comment]
We will reopen if we see this again.
