### ISSUE TITLE
Upgrade postgres driver

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20614]
The Pub/Sub on postgres 13 was throwing a driver error.
We can try to see if there is a new driver to upgrade

**Comment by wezell** [comment]
@jdotcms I upgraded my postgres to 13.3 and am not seeing any errors. I am not sure what is happening in your environment?  Can you share a stack trace?

**Comment by jdotcms** [comment]
This whas the error I was getting.
Debugging I realized, when getting the connection for the Pub/Sub throws this error
```
No suitable driver found for jdbc:pgsql://dotcms:dotcms@localhost/dotcms
java.sql.SQLException: No suitable driver found for jdbc:pgsql://dotcms:dotcms@localhost/dotcms
    at java.sql.DriverManager.getConnection(DriverManager.java:689) ~[?:1.8.0_282]
```

**Comment by wezell** [comment]
I think you need to rebuild your environment as there are .jars you need outside of the default Postgres Driver
