### ISSUE TITLE
Push Publishing Endpoints: Port number is appended to "Address To" field contents instead of host

### ISSUE THREAD

**Issue by cobbg** [dotCMS/core#20628]
**Describe the bug**
When adding a push publishing endpoint, the "Address To" field will accept an entire URI and append the port number to the end of it. This port number, if used in the string, should be appended behind the host value only.

**To Reproduce**
Add a push publishing environment and then add an endpoint. Give your endpoint a name, HTTPS (or HTTP) type, something like "api.testing.com/apigateway" as the address, and 443 (or any arbitrary number) as the port number. The endpoint will then be listed as `https://api.testing.com/apigateway:443`.

**Expected behavior**
The endpoint should be listed as `https://api.testing.com:443/apigateway`, with the specified port immediately after the host itself.

**Screenshots**
![Screen Shot 2021-07-08 at 3 07 42 PM](https://user-images.githubusercontent.com/32490417/124977320-5a9f2b00-dffe-11eb-8e53-e3bb895adb81.png)

**Additional context**
This problem is reproducible regardless of the operating system, browser, or platform used to access the admin portlet.

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
