### ISSUE TITLE
Container displays Add button twice under specific situations

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20623]
Reported via Support: [104562](https://dotcms.zendesk.com/agent/tickets/104562)
Reproducible in dotCMS 5.3.8.4LTS, and latest master.

Customers coming from very old versions of dotCMS might run into specific problems because of their legacy data. It seems like the old way of adding Containers to a Template in the **Advanced Template** portlet might be interfering with the new Page Edit UI. This is causing the **Add Content** button -- the purple plus sign -- to show up twice when adding or moving contents around inside a specific Container.

**To Reproduce**
Please ask me for more details on the necessary data for reproducing this problem.

**Expected behavior**
The **Add Content** button should appear only once, and not be affected by changing information inside a Container at all.

**Screenshots**
<img width="518" alt="duped-button" src="https://user-images.githubusercontent.com/8779585/124663270-188fb100-de67-11eb-9288-5f002d716fe8.png">

**Additional context**
It's worth noting that the duped button **IS NOT** keeping users from adding or dragging Contentlets around the Container. Clicking either button will allow users to add Contentlets without problems.

**Comment by alfredo-dotcms** [comment]
Steps:
- get a db from https://dev-suny-upgrade.dotcmscloud.com/dotAdmin
- edit page `index.dot` in `/about/diversity`
- add a content in container:
![image](https://user-images.githubusercontent.com/37185433/127022966-eb6eb41f-aefa-4ab6-a0a0-0453b328b17a.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1711

**Comment by nollymar** [comment]
**Passed internal QA:** I tested with a custom dataset and I was able to add/remove content in a page. The button never displayed twice.

**Comment by bryanboza** [comment]
Tested by @nollymar with a custom data
