### ISSUE TITLE
Update Site do not update  aliases

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20638]
Update Site does not update  aliases

STR:
1- Create a new Site without aliases.
2- Run the following REST API call to update the site and add some aliases.
```
PUT {{serverURL}}/api/v1/site?id={{siteId}}

{
    "siteName": "{siteName}",
    "aliases":"postman.hostalias1.com postman.hostalias2.com"
}
```
3- Check that the aliases are not null.

**Comment by erickgonzalez** [comment]
Update site aliases work fine but we're not able to update siteName, creating a new issue for it #20688

**Comment by jdotcms** [comment]
Gonna close b.c this work

**Comment by bryanboza** [comment]
Fixed, tested o master and I'm unable to reproduce.
