### ISSUE TITLE
Problems the first time you try to navigate to the network tab 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20647]
When you start a dotCMS instance, apply the license and then try to navigate to the network tab, we are getting a NPE error and we are unable to see the network info 

Here the log: https://gist.github.com/nollymar/11d0f36f5a0a4521e01d004a206434a9

FYI: the second time that you navigate to the portlet we are able to see the info without problems 

**To Reproduce**
- Start a dotCMS instance
- Apply the license 
- Go to configuration --> network tab

**Expected behavior**
Once the license is applied you need be able to see the network info without problems

**Desktop (please complete the following information):**
Tested on release-21.07b // Postgres // FF

**Comment by wezell** [comment]
I believe that the cluster gets "wired" in the heartbeat cronjob that runs every minute.  I wonder if this is a timing issue that happens if you apply the license and then hit the network tab before the wiring has a chance to occur.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/822

**Comment by victoralfaro-dotcms** [comment]
No erros at `Network` nor logs
![image](https://user-images.githubusercontent.com/64026161/127247332-51c9a800-610e-4d7f-b5a5-10a003802ff9.png)
![image](https://user-images.githubusercontent.com/64026161/127247379-17e25b07-d2f9-4199-86cb-9e80cf8e78c2.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Code fix was not included in the 5.3.8.6 LTS release because the Pub/Sub feature is not available in there.
