### ISSUE TITLE
HEARTBEAT_TIMEOUT and LICENSE_REPO_LEASE_EXPIRE_MINUTES

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20646]
We have 2 config variables that control when a license is returned to the license repo.  The `LicenseRepoDAO` uses the variable `LICENSE_REPO_LEASE_EXPIRE_MINUTES` with a default of 10m and the `ServerFactoryImpl` uses `HEARTBEAT_TIMEOUT` which also defaults to 10m.  

While we generally set the `HEARTBEAT_TIMEOUT`, we do not normally set the `LICENSE_REPO_LEASE_EXPIRE_MINUTES`.  This means that setting the `HEARTBEAT_TIMEOUT` lower, say to like 5m, in order to free licenses for new nodes coming online will not work as expected.  We do not have any documentation on the property `LICENSE_REPO_LEASE_EXPIRE_MINUTES`.

We should consolidate these values into `HEARTBEAT_TIMEOUT` and use this value throughout the system.

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise/pull/820

**Comment by erickgonzalez** [comment]
Working as it should now after 10 min (default **HEARTBEAT_TIMEOUT**) it releases the license.

**Comment by bryanboza** [comment]
Fixed, tested on a cluster of release-22.02 // Docker // FF. The server release the license after 10 minutes
