### ISSUE TITLE
Different behavior in the content portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20648]
As in previous versions we need to show the message "No results found" message the you are in the content portlet and select a content type that is empty 

Previous versions: 
![image](https://user-images.githubusercontent.com/2641437/125345792-32713e00-e316-11eb-891c-345aace047be.png)

Release: 
![image](https://user-images.githubusercontent.com/2641437/125345853-47e66800-e316-11eb-8bfd-6584bef54a9d.png)

**Desktop (please complete the following information):**
Tested on release-21.07 // Postgres // FF

**Comment by bryanboza** [comment]
Seems this is a major problem, If you add a content to this content types, we are not able to see the list of the contents filtered, need show all the contents to allow see the new piece of content

**Comment by nollymar** [comment]
**Note to QA:** Recompile and test again because we were using a wrong webcomponents version. 
It was already fixed.

**Comment by victoralfaro-dotcms** [comment]
Message showed
![image](https://user-images.githubusercontent.com/64026161/126008791-96058eee-bd87-48a2-b023-cf2ad2938ab9.png)

**Comment by bryanboza** [comment]
Fixed, now it is working as expected
