### ISSUE TITLE
Cleanup / Update backup and starter zip generation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20651]
We need to do some work on maintenance starter.zip / backup functionality.

1. We should incorporate the resources in the exporter plugin into the MaintenanceResource and allow the assets and database(SQL) to be downloaded via API

2. In the backend, if the system is running postgresql, there should be 3 buttons
- download assets
- download db (SQL)
- download starter.zip 

if the system is not running postgres, there should only be:
- download assets, 
- download starter.zip 

3. We should change the starter.zip generation and generate the starter in the assets directory (maybe under the bundle directory so it automatically gets deleted).

4. We need to remove the non-downloading "backup" buttons as users click those and they just fill up disk space.

**Comment by john-thomas-dotcms** [comment]
I think that on dotCMS Cloud instances, all of these buttons could potentially be problems - customers will click them, thinking they'll get something, but all they'll do is eat up disk space with files the customers can't access.

So a couple suggestions:
A. Have a config property which would hide all of these buttons.
B. Create endpoints that could be hit to trigger these downloads, rather than (or in addition to) the buttons.

The combination of both of these would allow cloud admins to trigger the downloads easily, but prevent users from triggering the downloads without unnecessarily using up disk space for files they can't access.

**Comment by john-thomas-dotcms** [comment]
One ticket (of many) where #4 in the original bug report is happening: https://dotcms.zendesk.com/agent/tickets/105601

**Comment by wezell** [comment]
We need to hide the "backup" buttons on the UI and add a config property `ALLOW_STARTER_ZIP_GENERATION_ON_DISK` that defaults to `false`.  If this is set to true, then we show the buttons.

**Comment by victoralfaro-dotcms** [comment]
PR:
https://github.com/dotCMS/core/pull/21290

**Comment by victoralfaro-dotcms** [comment]
Notes to QA:
- Start the DotCMS app with a starter and a valid license
- Go to the `Maintenance` portlet and select the `Tools` tab
- Verify "backup" (mentioned in the description) buttons are gone, unless the `ALLOW_STARTER_ZIP_GENERATION_ON_DISK ` property is set to `true`
- Verify the `Download DB` button shows only when the system is running `Postgres`
- Verify something is retrieved for three buttons: download assets, download db (SQL) and download starter.zip
- Verify that starter generation folder is somewhere inside the `bundles` folder

**Comment by dsilvam** [comment]
Needs work:
* "Download Data Only" does generate the starter zip under bundles but returns this in the UI: 
<img width="1655" alt="Screen Shot 2022-01-12 at 9 16 06" src="https://user-images.githubusercontent.com/1576794/149172485-62066f26-ecc5-4350-9d7d-ffffa2ef1238.png">

* "Download DB Dump" returns "{"message":"error=2, No such file or directory"}" in the UI

Also, not sure if "Download ZIP File" is the right name for the first section or should it be "Download Starter ZIP File"

**Comment by wezell** [comment]
Turns out that pg_dump does not work with db versions newer than itself, meaning pg_dump v.12 will not work with pg_dump v.13.  We need to upgrade the binaries to Postgres 14 and test them on our docker images

**Comment by dsilvam** [comment]
Passed Internal QA: all options working as expected including the pg_dump

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02. // Docker // FF
