### ISSUE TITLE
The Set Response Headers Rule Action does not allow single quotes in the value

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#20659]
## Describe the bug

When you add a Rule Action to Set Response Header, the `Value` field does not allow single quotes.  However, single quotes are needed for certain types of headers - especially the (common and increasingly used) Content-Security-Policy header.

## To Reproduce
1. Open the Rules portler.
2. Create and name a new Rule.
3. In the Actions section, select `Set Response Header`.
4. Set `Key` to `Content-Security-Policy`.
5. Set `Value` to `default-src 'self' cdn.example.com;` (which is a valid CSP header value).

**Result:** An error is displayed in red under the `Value` field with the message `Input cannot contain quote [" or '] characters.` (see screenshot, below).

## Expected behavior

Allow the use of single quotes in the `Value` property for all of the following Rule Actions:
* Set Request Attribute
* Set Response Header
* Set Session Attribute

## Screenshots

![image](https://user-images.githubusercontent.com/13456955/125643523-42a0725d-ca4f-4ba9-a914-0d163656c2c7.png)

## Additional context

* Multiple customers have reported this problem in relation to the Content-Security-Policy response header:
    * https://dotcms.zendesk.com/agent/tickets/104751
    * https://dotcms.zendesk.com/agent/tickets/103393
* The CSP header is used to help prevent XSS attacks, so this is a security-related issue.
* Although customers have, so far, implemented these headers using HTTP or Velocity code, this isn't a good solution.
    * This is exactly what the `Set Response Header` Actionlet was designed for, so we need to make it work for this case.
* Although the CSP header is the only common header or attribute that I'm aware of that currently uses single quotes, we should expect that other headers and attributes will need this in the future.
    * So, we should change the Value field to allow this in all of them, to prevent future issues with the attribute Actionlets.

**Comment by dsilvam** [comment]
PR core-web https://github.com/dotCMS/core-web/pull/1706

**Comment by dsilvam** [comment]
Passed Internal QA: Able to set the Responder Header with the proper value via `Set Response Header` actionlet. 
Header value: `Content-Security-Policy: default-src 'self' cdn.example.com`

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF
