### ISSUE TITLE
DotAsset Title is presented different on two search types

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20655]
**Describe the bug**
On the Release branch 21.07, a fresh install loaded with an empty starter presents a contentlet of type dot-asset on the content-search screen. First with the title `a083e942-5fb0-47ef-9619-6f8f40593474` which corresponds to the identifier. Then if a  filter is applied on the type drop-down box selecting dot-Asset the same contentlet is presented with the title `company_logo.png` which corresponds to the file name. 

Clearing the cache does not solve the issue. However, hitting save or publish does.

**To Reproduce**
1. Get a fresh install of the release branch 21.07, all brand new. empty db.. etc..  
2. Go to Content-Search screen locate an entry with the title `a083e942-5fb0-47ef-9619-6f8f40593474` You can double-click to verify the image. But do not hit save or publish. Just close the dialog.
2. Click on 'The Type Drop-down and select dot-asset
3. The Contentlet displayed is the same asset but the title shown is the file name this time.

**Expected behavior**
The title of the asset should be the same at all times

**Screenshots**
![Screen Shot 2021-07-13 at 07 52 42](https://user-images.githubusercontent.com/37148755/125512517-d20d570d-5ce5-4b98-9084-0fecd9d892fe.png)

![Screen Shot 2021-07-13 at 07 53 06](https://user-images.githubusercontent.com/37148755/125512534-e2a2bf63-726b-4638-8de2-fe8d7ef6667a.png)

Related to https://github.com/dotCMS/core/issues/19394

**Comment by wezell** [comment]
When importing the starter, we need to load/copy the assets before we import the content - this will allow the `contentlet.getTitle()` method to read an assets filename when called.

**Comment by nollymar** [comment]
**Note to QA:** Please, it is important to test an upgrade as well, where the database contains several dotAssets

**Comment by wezell** [comment]
Title should always be calculated as:
1. if the map has a `title` key, use that
2. Otherwise, use the value of the first show on list field
3. Otherwise, send the ...identifer

**Comment by nollymar** [comment]
In addition to Will's comment, we agreed that the title field (in database) should only be saved if there is an explicitly added field title

**Comment by fabrizzio-dotCMS** [comment]
I did various exercises here importing content that already had a title set. It all was nulled as expected.
Creating custom content types with different fields. Always the first index + show on list field is used unless there's a field called title. If no suitable field is found we fall back down to the identifier.  Which is good. 

when the title is empty we default again to the first suitable field. Also good. 

and if none then we show the identifier. I wasn't able to create an empty titled contentlet.
My Only concern here is that we have lost the ability to extract titles from content using a SQL Query. Unless of course, we have an explicit field named "title".  But the complexity of the query increases because now an additional join is needed/
That's my only observation @wezell Besides that I didn't find anything therefore I'm passing it.

**Comment by wezell** [comment]
Great QA Fabrizzio!

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
Excluding this ticket from the LTS release because of the required Upgrade Task.

**Comment by wezell** [comment]
@jcastro-dotcms  Upgrade task is not needed for this to work, it was just doing cleanup.

**Comment by swicken-dotcms** [comment]
Not needed on LTS, changes impacted to not exist in <=21.06

**Comment by erickgonzalez** [comment]
We can backport these to fix the issue that the UUID is being set as Title:

* https://github.com/dotCMS/core/pull/20694/files#diff-b5d82de048877f797337b47640a36eadbde435004223134e7301ee64ebe9ededR1994
* https://github.com/dotCMS/core/pull/20694/files#diff-1367236d40a612b923ececfa521053143f026f60f035c9f9963aae4efdfaf034
