### ISSUE TITLE
Selecting a date in Content Search advanced search returns zero results

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20667]
As reported in https://dotcms.zendesk.com/agent/tickets/104773 v5.3.8.5 
Recreated in current demo v21.06

Search using a date field (i.e. Start Date) on Content->Search returns zero results.

1. Go to Content->Search and select a Content Type with a date field. e.g. Events
2. Click on Advanced Search
3. Use the date picker to select a date or enter a date manually

SCREENSHOT ONE:
Content->Search on the Events Content Type. Observe that at least one contentlet has a Start Date of 12/3/2019:

![image](https://user-images.githubusercontent.com/49727631/125796692-766f6b13-2cc1-4dfc-8078-b27c4ac31c9b.png)

SCREENSHOT TWO:
Either manually enter or use the date picket to select 12/3/2019 and click Search. Zero results returned. 

![image](https://user-images.githubusercontent.com/49727631/125797089-b201bb09-9b08-4267-9f18-83c75fa08a7c.png)

**Comment by craigWagner99** [comment]
It is understood that the search should include a date range but from a UI perspective perhaps the field should not include a date picker - or at least have additional options. 
It is confusing from a visual standpoint where other drop-down fields will find the value selected.

**Comment by john-thomas-dotcms** [comment]
Bottom line: 2 problems here:

* We're providing a date picker control, but if you use the date picker control, it doesn't work.
* We're providing a control that selects a date, but the query relies on both date and time.

So, potential solutions:
* Remove the date picker control completely.
    * Require users to type in the date range manually
* Keep the date picker control, and when a user selects a date with it, translate that into a date range for the query.
* Add a second date picker, so the user can select start and end dates for the query.

**Comment by alfredo-dotcms** [comment]
things to do:
- the date/time format `[20190101033000 TO 20210101033000]` will be done on the BE. the 2nd date/time will be added in the BE (system's current time)
- the FE datepicker must be able to display date and time (currently only shows date)

**Comment by alfredo-dotcms** [comment]
Core Branch: issue-20667-content-search-datetime-fields-needs-formating

this is WIP, some BE changes needs to be done!
