### ISSUE TITLE
Move to a glibc based docker image

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20666]
While alpine images are small, the problem with them is that their c library is based on `musl` rather than `glibc`.   `musl` is smaller than `glibc`, but it also can be much slower, there are fewer libraries for it and prohibits us from trying/running different builds of openjdk.  I believe it would be a good thing to be able to try different java distros and find the ones that give us the best performance.

This article lays out good arguements for running some of the glibc based distros.

http://crunchtools.com/comparison-linux-container-images/

https://pythonspeed.com/articles/base-image-python-docker-images/

**Comment by jcastro-dotcms** [comment]
Thanks to @dsilvam , I was able to back-port this change into dotCMS 21.06.2 LTS release by doing the following:

1. Doing a `git cherry-pick 7348f0afca0dc1d732095515fa63d1bc75c13357`
2. Doing a `git cherry-pick 98060e5`

This feature is not available in dotCMS 5.3.8.6 LTS release.
