### ISSUE TITLE
Error deploying a fresh install using mssql

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20669]
This exception is thrown using MSSQL as database in a fresh installation with full starter: https://gist.github.com/nollymar/bf3c3ce38097531d368d2d1f6e036a38

**Comment by fabrizzio-dotCMS** [comment]
I found that `Task210527DropReviewFieldsFromContentletTable` was getting stuck on my instance however setting the current connection to support auto-commit fixed the issue 
here's the PR https://github.com/dotCMS/core/pull/20693

After that the upgrade worked correctly. I'm passing it

**Comment by bryanboza** [comment]
Fixed, tested after the last changes and now we are able to start and run the instance without problems using this DB

**Comment by swicken-dotcms** [comment]
Not required for 5.3.8.6

**Comment by swicken-dotcms** [comment]
Commit above was a reversion, referenced incorrect ticket when committing.
