### ISSUE TITLE
[Relationships] : Drag-and-drop in Relationship fields for Child contents must not be allowed

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20672]
Reported via Support: [104656](https://dotcms.zendesk.com/agent/tickets/104656)
Reproducible as of dotCMS 5.3.8.4, and in Demo Site (21.06)

Considering the scenario where you have a parent and child Content Types: `My Parent` and `My Child` respectively, with a `Relationship` field from parent to child with Many-to-Many cardinality.

In dotCMS, the `Relationships` field allow users to re-order the items in the list. For example, when you create a content of type `My Parent` and associate it to contents of type `My Child`, you can re-order those elements via drag-and-drop inside the `Relationships` field.

Conversely, if you go to a content of type `My Child`, and relate more contents of type `My Parent` to it, you CANNOT re-order any elements in there. This is expected behavior as dotCMS doesn't have the required internal structures to handle and store the re-ordering from both parent and child perspectives.

However, the UI must be able to handle this situation. For example, it should allow the drag-and-drop operation to work **ONLY** when a parent content is re-ordering child contents in a `Relationship` field, but **NOT** the other way around.

**To Reproduce**
1. Create a parent and child Content Types, named `My Parent` and `My Child`.
2. Add a new `Relationship` field to `My Parent` pointing to `My Child`. And add the `Relationship` field to `My Child` as an existing relationship.
3. Add contents from both types.
4. If you add a parent content, and relate many child contents to it, you'll see that you can drag-and-drop those items and the changes will be saved.
5. **BUT**, if you add a child content and related many parent contents to it, the drag-and-drop operation will not save any changes at all. 

**Expected behavior**
If this is expected or a system limitation, the UI must assist users and **NOT** let them drag-and-drop contents in a `Relationship` field where such changes cannot be saved.

**Additional context**
We need to add a section in our Documentation explaining this item re-ordering exception in particular.

**Comment by fabrizzio-dotCMS** [comment]
For the specific scenario described. The drag and drop option is disabled. But it continues to work for others as expected.

**Comment by bryanboza** [comment]
Fixed, unable to D&D after the last changes. Tested on release-22.02 // Docker // FF
