### ISSUE TITLE
Basic Config Tab Under Configuration Portlet is not working

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20671]
If navigate to the Configuration Portlet there are several errors at the browser console.
The color picker is not loading either the background image.

![Screen Shot 2021-07-15 at 12 57 09 PM](https://user-images.githubusercontent.com/5278970/125842259-19cfa2af-5be6-470b-829b-6f97feb4e14d.png)

Reproducible in master as well.

**Comment by victoralfaro-dotcms** [comment]
No errors in browser console.
![image](https://user-images.githubusercontent.com/64026161/126714514-a6b0f52f-89ee-44ef-88a6-2ea769c3e3dc.png)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes. Tested on release-21.07 // Postgres // FF
