### ISSUE TITLE
Unable to pick time in earlier zone

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20674]
Reproducible on demo.dotcms.com

1. If your local system is in AEST, and you try to select another Timezone, for example EST
![image](https://user-images.githubusercontent.com/944787/125830318-28ed57d9-fc13-48f4-9ffb-2688fd3b5394.png)

2. You are not able to select a date "from the past", meaning you can't select a date in EST Timezone. 
![image (1)](https://user-images.githubusercontent.com/944787/125830414-49766454-c369-4636-9e44-a2e027128d6e.png)

I think we should allow users to select at least 1 day in the past.

_Originally posted by @oarriet in https://github.com/dotCMS/core/issues/20110#issuecomment-880878209_

**Comment by nollymar** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1708

**Comment by nollymar** [comment]
Passed internal QA

<img width="1677" alt="Screen Shot 2021-07-30 at 4 25 43 PM" src="https://user-images.githubusercontent.com/8741395/127713080-e29256d8-e05a-4c8f-8c23-20991bfc5fd2.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09. // Postgres // FF

**Comment by swicken-dotcms** [comment]
These changes are being excluded from the 5.3.8.X LTS release due to the changes between 5.3.8.X and the current code base being too extensive.
