### ISSUE TITLE
Create Transaction Annotation

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20696]
Currently we have the ability to wrap transactions into transactions, which is ok.

But there are some scenarios that we need a precondition or dependency that should be out of the transaction.

The current workaround is to create a thread and wait for the result on the current transaction thread, this allow us to use a need connection, consequently a new transaction; works but it is odd, and probably a waste of resources create a parallel process that is in a separated thread only b/c the necessity of the transaction.

The idea would be to have the ability to create a method that creates a new transaction (with a new connection) even if it is already on a transaction, do whatever need to do, and get back to the original transaction for instance

```
WrapInTransaction
method A();

WrapInTransaction
method B()

Transaction
method C()

then you do something like

A();  // a is being called, and transaction 1 is started

A () { // A is running into transaction 1

     B();  /// A calls B, so it is on the same A transaction 1

}


B() { // B is running into transaction 1

     C(); // B calls  C, but this is not into transaction 1, C starts a new transaction, when C is done, B will continue with the rest of the work for transaction 1.
}
```

**Comment by wezell** [comment]
I think the important thing with this is to name it correctly - something like `externalTransaction`

**Comment by jdotcms** [comment]
In order use the external transaction you have to do
```
@WrapInTransaction(externalize = true)
```

This will create a new transaction instead of using the current one wrap in transaction.
