### ISSUE TITLE
Unable to login with  non-admin user due to the requiresPortlet("sites") recently added to the SitesResource

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20717]
**Describe the bug**
We can not log in using Chris Publisher.

**To Reproduce**
1. Get a fresh install using 21.07 and the full starter 
2. Try to log in using Chris Publisher
3. You'll see we can not log in using this user. The log reports it is due to the lack of the portlet "sites" which does not apply to the two endpoints used here. Current site and Sites.

**Expected behavior**
You should be able to log in using C.P.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
