### ISSUE TITLE
NPE on tags via graphql if no tags present 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20719]
If you use graphql to pull tags on a content object and there are no tags defined, you get a fat npe in the logs, a null result  and graphql will raise an error.

We should just return an empty list.

![Screen Shot 2021-07-28 at 9 40 51 AM](https://user-images.githubusercontent.com/934364/127332536-bc67b17b-dd82-45ba-a395-08167846b59c.png)

**Comment by victoralfaro-dotcms** [comment]
Tested with Insomnia
![image](https://user-images.githubusercontent.com/64026161/127546458-a8a7e99f-71bd-4b83-9d1d-cc38c7ddea8d.png)

No error logs found.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF
