### ISSUE TITLE
We are skipping the workflow_task dependency in the push publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20718]
When you have a push publish environment, we are now leaving the pieces of content that you push in the correct workflow step, because we are not sending the info that is in the `workflow_step` table.

Push is working fine but everything is leaving in the `New` step on the receiver side.

FYI: We are updating the status correctly, but the content is leaving in the same step 
![image](https://user-images.githubusercontent.com/2641437/127200514-27873c33-736f-4d5a-8977-fa9df2c59766.png)

**To Reproduce**
- Start two instances and configure your push enviroment 
- Upload some assets on the receiver side 
- Try to push 
- Check the step on the sender side 

**Expected behavior** 
We need to be able to push anything without problems and should leave in the other side in the same WF step 

**Screenshots**
This is the receiver side: 
![image](https://user-images.githubusercontent.com/2641437/127201799-06d32aeb-11b2-4ecb-9043-d90edda9bacd.png)

**Desktop (please complete the following information):**
Tested on release-21.07 // Postgres // FF

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/824

**Comment by victoralfaro-dotcms** [comment]
Asser on sender side:
![image](https://user-images.githubusercontent.com/64026161/131580869-bd8d924f-e2cd-416e-861d-75eb4ccc20ae.png)

Asset on receiver side:
![image](https://user-images.githubusercontent.com/64026161/131580820-88e23d2b-4b33-4f75-a451-2513006f11c5.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker
