### ISSUE TITLE
NPE trying to fix folder conflicts 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20714]
We are getting an NPE error and we are unable to fix the folder conflicts 

Here is the log: https://gist.github.com/bryanboza/5ca45b9d0a434da2605573194f445984

**To Reproduce**
- Start and configure  your PP environment 
- Create a new folder manually in both sides, this with the same name 
- Add some assets to the folder on the receiver side 
- Run the Integrity Checker 
- Try to fix the conflicts on the receiver side 

**Expected behavior**
We need to be able to fix conflicts without problems 

**Desktop (please complete the following information):**
Tested on release-21.07 // MSSQL

**Comment by nollymar** [comment]
Passed internal QA: I ran the integrity checker and after listing the conflicts I was able to fix and push them successfully

<img width="1490" alt="Screen Shot 2021-08-02 at 3 41 30 PM" src="https://user-images.githubusercontent.com/8741395/127921505-5fb5d106-5588-4a1c-9a6c-59560796acab.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.08 // MSSQL // Docker

**Comment by swicken-dotcms** [comment]
This change is not required for 5.3.8.6
