### ISSUE TITLE
Problems trying to import file assets 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20715]
If you upload some assets to your server, then export and delete the contents, if you try to import again we are getting some errors with the url, the same thing if you try to import in another instance. 

**To Reproduce**
- Start the instance and login as admin
- Create a new folder and upload multiple files via the UI
- Go to the File Assets content type and export all the contents 
- Delete the files uploaded in step 2
- Try to import the CSV file 

**Expected behavior**
We need be able to import without problems 

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/127190222-5c48ee27-de32-4efc-8188-89aadaf5583d.png)

**Desktop (please complete the following information):**
Tested on release-21.07 // MSSQL

**Comment by nollymar** [comment]
This is happening in 5.3.8 also

**Comment by wezell** [comment]
@bryanboza is the url a local url or an external url?  If it is local, I think this is expected behavior.  Can you share some of the .csv files?

**Comment by bryanboza** [comment]
Hey, this is an internal URL, then seems that make sense that it fails

**Comment by wezell** [comment]
Nothing to do here
