### ISSUE TITLE
"Login As" Data Constraints

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20721]
The Login As Data should be only available for someone with the Login As Role.

In addition we want to remove the UserResource v2 and put the logic only on the UserResource v1.

**Comment by jdotcms** [comment]
1) User Resource v2 does not longer exists.
2) the functionality from v2 has been moved to v1 (loginAsData endpoint) and the v1 is not longer deprecated.
3) it is a breaking change since we remove existing functionality (by deleting the v2) 
4) Angular is broken b/c is pointing to non-existing endpoint, needs to use the v1 instead

**Comment by bryanboza** [comment]
Need to exclude the current role, this because if you are logged as admin, does not make sense the admin user is in the list of the users to login as

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Docker

**Comment by jcastro-dotcms** [comment]
Changes could not be back-ported to dotCMS 5.3.8.7 LTS release because they break the back-end.
