### ISSUE TITLE
Error upgrading to 21.06 using a managed database

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20725]
Upgrading to 21.06 using a non-superuser and a Postgres database that contains system triggers fails with this exception:  `ERROR: permission denied: "RI_ConstraintTrigger_a_168966" is a system trigger` 

**To Reproduce**
1. Configure system triggers in your DB
2. Create a non-superuser in your DB and set the credentials in  your `db.properties`
3. Try to upgrade dotCMS

**Additional context**
Probably you will require a managed database like Amazon Aurora to reproduce it.

**Comment by nollymar** [comment]
**Passed internal QA:** I tested an upgrade using both the full starter and a custom data set.

**Comment by swicken-dotcms** [comment]
Code changes already added to LTS in 21.06.1, which we have based 21.06.2 on. Marking as part of LTS.
