### ISSUE TITLE
Create download button to Manifest

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20729]
![109065800-1f890480-76ba-11eb-87ef-8d08ee4f370d](https://user-images.githubusercontent.com/10408015/127543030-b047b3c6-7ff6-407d-af7c-4573e10accf3.png)

**Comment by wezell** [comment]
Should hit a resource that based on the bundle id, returns the contents of the Manifest in the zip.  Something like:
https://stackoverflow.com/questions/15667125/read-content-from-files-which-are-inside-zip-file

We should set a header to force a download, I think it is `Content-Disposition`

**Comment by wezell** [comment]
`Content-Disposition", "attachment; filename=manifest_{bundleShorty}.csv`

**Comment by wezell** [comment]
We need to hide the download manifest button if there is no manifest.

Also, we should still read data from older bundles like their name, etc..  Test this with the assets.tar.gz bundle that we use for testing.
