### ISSUE TITLE
Error saving Destination pages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20733]
It is not possible to create/edit Destination pages in current master. It seems like the `/html/portlet/ext/contentlet/field/relationship_field.jsp` file is corrupted 

**Steps to reproduce it:** 

1. Deploy a dotcms instance using full starter
2. Try to add a new Destination page or edit an existing one
3. You should see these exceptions in the log: https://gist.github.com/nollymar/f6b47fd42304f63c21f1203df3022678

**Comment by bryanboza** [comment]
Fixed, unable to reproduce, tested on release-21.09 // Postgres // FF
