### ISSUE TITLE
Content Export tool is not exporting relationships correctly

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20746]
Reported via Support: [104835](https://dotcms.zendesk.com/agent/tickets/104835)
Reported as of dotCMS 5.3.8.5, up to latest master (21.06)

One of the Content API methods used by the **Content Export** tool to export Related contents to the CSV file is not referencing down the correct `User` object. This is causing Content Authors NOT being able to export Contentlets that DO NOT have **CMS Anonymous** access.

**To Reproduce**
Please ask me for details on the required data.

**Expected behavior**
The **Content Export** tool must be able to export Relationship data without problems.

**Additional context**
The method called by the **Content Export** tool:

https://github.com/dotCMS/core/blob/0d57f0dce65ea4f27a283c1fb5c02fb5fb80c18f/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1380

Passes down a `null` value as the User, which is expected. The subsequent method sets the System User as a fallback in case the incoming user is indeed `null`. However, the specific call to the next method IS NOT using the fallback User, it's passing down `user` instead of `currentUser`:

https://github.com/dotCMS/core/blob/0d57f0dce65ea4f27a283c1fb5c02fb5fb80c18f/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1433-L1435

The only workaround for now is to add the **CMS Anonymous** Role to the related Contentlets so that they can be exported without problems.

**Comment by nollymar** [comment]
**Internal QA:** Passed. Tested with a custom dataset.
