### ISSUE TITLE
Auto save layout changes in editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20744]
**Is your feature request related to a problem? Please describe.**
Auto save layout edits.

https://user-images.githubusercontent.com/751424/127926165-8ea045d9-8f18-422c-aadd-c43e1eac87f3.mp4

**Describe the solution you'd like**
We need to get rid of the buttons in both, layout page and templates.

**Describe alternatives you've considered**
You need to check the layout change, it triggers an evento.

**Comment by erickgonzalez** [comment]
Note to QA:
* Auto-save will be set to 10 sec after the last change
OR
* If the user changes something, hasn't passed 10 sec and exits the template will be saved.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // docker
