### ISSUE TITLE
Remove bundle.xml file from bundle

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20752]
With the manifest file we not need the bundle.xml file anymore so We should not create it anymore

Also after the manifest file the bundle.xml file is not contains the assets anymore (because The manifest changes use another Map to include the assets), so We have to check if this code is working how expected

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/publisher/receiver/BundlePublisher.java#L205

Also we have some PublisherConfig's properies include into the bundle.xml that right now is not include in the manifest, so we should include this information into the manifest file as csv headers

**Comment by freddyucv** [comment]
Note to QA: Test with incremental bundle in Time Machine and Site Search

**Comment by dsilvam** [comment]
Internal QA Results: 
* Push publish working
* Site Search + incremental working
* Time machine couldn't be test because of this: https://github.com/dotCMS/core/issues/21097
