### ISSUE TITLE
Unable to run the Integrity Checker using Safari

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20754]
We are unable to run the integrity checker when you are navigating in safari. 

- If you don't have conflicts we are unable to see the "No conflicts" message 
- If you have conflicts we are unable to see the conflicts window 

**To Reproduce**
- Start a dotCMS instance 
- Create some conflicts 
- Using safari, try to run the integrity checker 

**Expected behavior**
Since Safari is in the list of the supported browsers, we need be able to use this feature from this browser 

**Desktop (please complete the following information):**
Tested on release-21.08 // MSSQL // Safari

**Comment by fmontes** [comment]
We don't support Safari
