### ISSUE TITLE
Add Uri capture pattern to redirect rule actionlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20762]
The dotCMS rules engine contains the nice ability to redirect users that match the rule criteria.  This is a powerful capability, though it is lacking in one important feature- the redirect destination has no access to the current url to use when building its redirect.  This means that it is impossible to do things like redirect someone from host A to host B while using the same url.  Or to redirect them to the same host but with specific parameters set.

To fix this we need to add a field to the redirect actionlet called uri to rewrite that would allow a user to specify regex groups to capture that could be used when building the final redirect, e.g.

```
/(.*). ---> https://cdn.demo.dotcms.com/$1

```

If nothing is set for the pattern, then we just do the redirect normally.  Otherwise, use the matchers to rewrite the url

STR:
1- Create a page with the URL `test` at root level
2- Create a Rule with the Conditionlet `CurrentURL | REGEX | /test(.*)` and the Actionlet `Redirect Request To | MOVED_TEMP | /store$1`
3- In a private window hit the URL `localhost:8080/test?tags=climbing`
4- This should redirect to the store page and only show the items that are tagged with climbing
![Screen Shot 2021-10-25 at 11 58 02 AM](https://user-images.githubusercontent.com/5278970/138746120-462dad1c-4123-4a58-89b4-9e63baaba8a6.png)

We want to achieve here is that the params are shared even with a redirect.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.11 // Docker // FF

**Comment by ian-b-cooper** [comment]
Can we investigate if we can backport this to 5.3.8.10? Would like to get this fix for a customer in hopes it helps to address some issue outstanding here: https://dotcms.zendesk.com/agent/tickets/106942

**Comment by erickgonzalez** [comment]
Not back portable since could potentially break things.
