### ISSUE TITLE
Property name for workflows for creation of Content Types differs from retrieval

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20768]
**Describe the bug**

- When you create a content type via the content type API, you submit workflows via a list in a property called `workflow`
- When you retrieve a content type via the content type API, you get the workflows in a list called `workflows`
- If you submit a new content type with the workflows under the property `workflows` they do not get assigned.

Reproduced on: master and 5.3.8.5

Support Ticket: https://dotcms.zendesk.com/agent/tickets/104909

**To Reproduce**
1. Create a new content type via a `POST` REST Call to `/api/v1/contenttype` with the following payload:

```
{
    "clazz": "com.dotcms.contenttype.model.type.ImmutableSimpleContentType", 
    "defaultType": false, 
    "name": "The Content Type 1", 
    "description": "THE DESCRIPTION", 
    "host": "48190c8c-42c4-46af-8d1a-0cd5db894797", 
    "owner": "dotcms.org.1", 
    "variable": "TheContentType1",
    "fixed": false, 
    "system": false, 
    "folder": "SYSTEM_FOLDER",
    "workflow":[
        "d61a59e1-a49c-46f2-a929-db2b4bfa88b2"
    ]
}
```

2. Collect the identifier of the content type you created.
3. Call a `GET` request to `/api/v1/contenttype/id/{typeId}`
4. Create a 2nd content type with this payload:

```
{
    "clazz": "com.dotcms.contenttype.model.type.ImmutableSimpleContentType", 
    "defaultType": false, 
    "name": "The Content Type 2", 
    "description": "THE DESCRIPTION", 
    "host": "48190c8c-42c4-46af-8d1a-0cd5db894797", 
    "owner": "dotcms.org.1", 
    "variable": "TheContentType2",
    "fixed": false, 
    "system": false, 
    "folder": "SYSTEM_FOLDER",
    "workflows":[
        "d61a59e1-a49c-46f2-a929-db2b4bfa88b2"
    ]
}
```
The returned content type will have the list of workflows under the property `workflows`

5. Collect the identifier of the content type you created.
6. Call a `GET` request to `/api/v1/contenttype/id/{typeId}`

The returned content type will not have any workflows assigned. 

**Expected behavior**
Creation and updating of content types should be possible using the property `workflows` as well as `workflow` (to support existing implementations)

**Comment by wezell** [comment]
In order to maintain backwards compatibility, we need to support both `workflow` and `workflows` in our workflow submit and update our examples to use `workflows`
