### ISSUE TITLE
[Push Publishing] : User who pushed content shows up as System User in the receiver

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20776]
Reported via Support: [104940](https://dotcms.zendesk.com/agent/tickets/104940)
Reproducible in dotCMS 5.3.8.5, and latest master (21.08)

The way it has worked in the past is that, if the User doing the push from the sender exists on the receiver, then the push is performed using the permissions that User has on the receiver. If the User **does NOT exist** on the receiver (at all), then the push is performed as the `System User`.

We may have broken that when we did the Front-end User/Back-end User changes a while ago (around early 5.3.x maybe).

**To Reproduce**
1. Set up a dotCMS Push Publishing environment.
2. Create a BE user on the sender.
3. Push that User from the sender to the receiver.
4. Verify that the User you created before has all the rights and permissions to push successfully from the sender.
5. Logging in as the new User, push a piece of content from the sender to the receiver.
6. In the receiver, the `Mod User` value shows up as `System User` instead of the name of the test User who actually pushed the content.

**Expected behavior**
The `System User` should only be used when the User who pushed the content does not exist on the receiver.

**Additional context**
The Push Publishing mechanism should not require the User to have admin permissions on the receiver for the content to be published as the actual user (rather than as the `System User`).

**Comment by john-thomas-dotcms** [comment]
This is actually a significant issue, and in some limited circumstances may present a security issue.  With this bug, any user can push any content, regardless of the permissions they have on the receiver.

In previous versions, if a user existed on both sender and receiver, the permissions of the user (on the receiver) were used to determine if the push would succeed or fail.  Now, however, the push always succeeds, no matter what permissions the user has on the receiver.  So, users who previously were not allowed to push some content are now able to.  And this presents potential security issues.

The only workaround right now (to prevent a user from being able to push anything) is to prevent users from being able to push to the endpoint completely (preventing them from pushing any content of any type).  This is obviously not an ideal solution.

**Comment by wezell** [comment]
So, permissions to push content are driven by the permissions on the sender's environment and or the filters they have access to.  We should always prioritize a successful push over a push that attempts to send a mirror of what is on the sender's environment.

**Comment by wezell** [comment]
This was changed here:
#11559

**Comment by swicken-dotcms** [comment]
Excluding from LTS, if this behaviour is required we can change the config variable.
