### ISSUE TITLE
If a user with restricted access views their folders in site browser first, they can see the Add Content button when they navigate to other folders

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20774]
As reported in https://dotcms.zendesk.com/agent/tickets/104936 v5.3.8.5
Recreated in current Demo version: "MASTER - AUGUST 05, 2021"

**Describe the bug**
If a user with restricted access views their folders in site browser first, they can see the Add Content button when they navigate to other folders. (UI issue)

They can click the add content button and select which content to add, but they are not able to add content. 

**To Reproduce**
1. Restrict a Role to be able to add to specific folders
2. Login as a user with that Role
3. In Site->Browser navigate to a folder where the Role has permissions
4. Then navigate to a folder where the Role does NOT have permission
5. Observe the Add Content button

**Expected behavior**
Add content button should be invisible except on folders where the Role has permissions

**Screenshots**

01: Role has permissions to add content to just one folder (images)

![image](https://user-images.githubusercontent.com/49727631/128547997-f98945b1-a6f0-4b26-bbc6-9d2c1c9cc003.png)

02: Logged in as user with test role. Navigate to restricted folder first. No Add Content button.

![image](https://user-images.githubusercontent.com/49727631/128548108-98b03944-c42a-4b6b-9e77-08475d4bc693.png)

03: Navigate to folder where Role HAS permissions (images). Add Content Button appears.

![image](https://user-images.githubusercontent.com/49727631/128548185-96a79fcf-f011-40a5-804d-491d243fbcaa.png)

04: THEN navigate to any other folder - Add Content persists.

![image](https://user-images.githubusercontent.com/49727631/128548261-2fcd1701-9923-4281-bf05-122ce1692120.png)

05: Click the Add Content button - add a Page (for example). Content creation screen opens, but unable to save.

![image](https://user-images.githubusercontent.com/49727631/128548397-3dd9b196-3e31-476e-864f-3c41a9cf617a.png)

**Comment by erickgonzalez** [comment]
Now when navigating to another folder that the user does not have permission to add content, the button doesn't show.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 and now the button appear and disappear according the permissions of the folder.
