### ISSUE TITLE
SAML - Allow expression substitution from SAML roles mapped to dotCMS roles by role key

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#20773]
When SAML authentication is configured in dotCMS and roles are inherited from IdP, dotCMS follows this approach for roles that come in SAML assertion attributes (`build.roles` property is set to `all` or `idp`):

1. If there is no dotCMS role with the same role key as the role name sent from IdP, a new dotCMS role will be created and its key will be set to the role name sent in the assertion attribute.
2. But it dotCMS already has a role with the same role key as the role name sent from IdP, then dotCMS won't create a new role but it will assign the matching role to the user (in case the user has not been assigned to that role yet)

This approach allows mapping IdP roles with existing dotCMS roles. For example, I can assign an existing dotCMS role as 'CMS Administrator' to a user automatically when the user logs in for the first time. However the IdP can have some constraints in role names, like not allowing spaces, so I can't send the role 'CMS Administrator' in the assertion attribute. With some substitution mechanisms enabled, I would be able to send a role name as 'CMS_sepsep_Administrator' and dotCMS will replace it with the appropriate role key 'CMS Administrator'. 

### Proposed Solution
A new configuration property for the SAML plugin will allow adding a substitution expression to use when mapping dotCMS role keys. For example:
```
role.key.substitution=/_sepsep_/ /
```
That substitution expression will replace the string `_sepsep_` with white space before matching role name from IdP against role key from dotCMS.

**Comment by wezell** [comment]
@dsolistorres   What version of dotCMS and SAML is this happening on?

**Comment by dsolistorres** [comment]
@wezell I tested this with 5.3.8.x, not the latest version. It's not an issue for users that can keep CMS Administrator accounts as native accounts without mapping them to IdP users, but some users want to map CMS Administrator to their IdP too.

**Comment by jdotcms** [comment]
why can not map the CMS Admin users?
If the name id is the same of the user id | email, dotCMS will take their roles, clean, and then sync with whatever is on the idp

**Comment by dsolistorres** [comment]
In this case, they are using Okta as IdP, and it seems that it doesn't allow creating user groups with names that contain spaces. So they cannot create a user group with the name "CMS Administrator" to be mapped to the dotCMS role key. It's really a limitation of the IdP allowed names in this case.

**Comment by jdotcms** [comment]
I see, this is something we have to work on.

**Comment by erickgonzalez** [comment]
Passing QA based on the tests are working: https://raw.githack.com/dotCMS/test-results/release-21.10/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.auth.providers.saml.v1.SAMLHelperTest.html

Since this needs the creation of roles on the IdP.

**Comment by erickgonzalez** [comment]
I tested this via debug, @jdotcms is looking for a way to check this via UI if is possible.

**Comment by bryanboza** [comment]
Fixed, after configure my SAML authentication locally and map the role via custom properties, now we are able to add roles to user using that method. 

Tested on release-21.10 // Docker // FF
