### ISSUE TITLE
Theme paginator is not displaying the Host filter

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20781]
When there are multiple cloned sites, the Host select box is not displayed in the theme paginator.

**Steps to reproduce:** 
1. Start a fresh installation using full starter
2. Clone the demo.dotcms.com site multiple times
3. Add or modify themes in any of the new sites
4. Go to Templates and create a new template using the designer
5. Try to filter themes. Only the themes that belong to the current host are displayed

A video is attached with further details.

https://user-images.githubusercontent.com/8741395/128916027-dd1ad2b5-98ed-45ff-b1d7-f3e90a88ce08.mov

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1734

**Comment by nollymar** [comment]
I**nternal QA:** Fixed. Now I can filter by host

<img width="1237" alt="Screen Shot 2021-08-31 at 6 08 48 PM" src="https://user-images.githubusercontent.com/8741395/131587158-cfc9de1f-b567-49c6-94e9-a14b486a3b09.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF
