### ISSUE TITLE
Listing row should have the same min-height

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20788]
**Describe the bug**
When the listing row have the actions on the right the height is more.

**To Reproduce**
1. Go to content types listing
2. See the height of the table rows

**Expected behavior**
We need all to have the same min-height no matter the content

**Screenshots**
![Screen Shot 2021-08-12 at 12.22.03 PM.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/5951e62e-8936-4c0d-8edc-c3a1e6cc3077)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF
