### ISSUE TITLE
The System Info tab is not loading

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20798]
Due to this exception: https://gist.github.com/nollymar/fc0a0a18a77c9c67b44a9f66071dbb85 when I try to open the System Info tab, the page is displayed blank. This error occurs when the dotCMS instance is running on docker.

dotCMS version: 21.09

![Screen Shot 2021-08-16 at 4 12 38 PM](https://user-images.githubusercontent.com/8741395/129631164-92b0254f-4198-40a1-8958-28dd5040e929.png)

**Comment by erickgonzalez** [comment]
Missing module `jdk.management`

**Comment by nollymar** [comment]
**Internal QA:** Passed

![Screen Shot 2021-08-17 at 11 56 29 AM](https://user-images.githubusercontent.com/8741395/129768681-5d362882-2a03-4044-8848-3f2debf07153.png)
###

**Comment by wezell** [comment]
@erickgonzalez glad you took the time to learn how we were building with jlink!  Boss fix!

**Comment by bryanboza** [comment]
fixed, tested in the last docker image of release-21.09 and this is loading as expected
