### ISSUE TITLE
When try to import a Bundle get a OutOfMemoryError

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20799]
The 'publishQueue' method take a long time to process each event

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/dotpubsub/QueuingPubSubWrapper.java#L89

so when a lot of Event are triggered then you can get a OutOfMemoryError because it take a lot time to clean the events again

**Comment by wezell** [comment]
@freddyucv what is the fix here?  I'm interested in what we can do to optimize/ speed this up.

**Comment by freddyucv** [comment]
> @freddyucv what is the fix here? I'm interested in what we can do to optimize/ speed this up.

https://github.com/dotCMS/core/pull/20787/files

Also fixing a " Infinite recursion (StackOverflowError)" here

https://github.com/dotCMS/core/pull/20787/files#diff-8fe164f82df910ef8511244401889d147c62ca47a04787b7d2463b0054798b0bR1

... and a NullPointerException here

https://github.com/dotCMS/core/pull/20787/files#diff-9ed24279e1ab8d9a0aeb618048cefe72d70d8eb68de4a108855ce9467aa8eba9R206

**Comment by wezell** [comment]
Successfully imported Dean's 12000 contentlets with a 1GB heap.  It took an hour to import but did not slow down over time.

![Screen Shot 2021-08-18 at 6 49 11 PM](https://user-images.githubusercontent.com/934364/129982086-83038d1d-4000-4cf8-8a12-792bbecc619b.png)

**Comment by dsilvam** [comment]
Needs retesting of https://github.com/dotCMS/core/issues/20320

**Comment by nollymar** [comment]
**Internal QA:**  Passed

I was able to scale up and down a cluster successfully.

<img width="1673" alt="Screen Shot 2021-08-24 at 11 47 50 AM" src="https://user-images.githubusercontent.com/8741395/130657435-0b5134b8-9283-498e-b1d2-c2ce2be53d64.png">

Cache invalidation took place in both nodes as expected.

**Comment by bryanboza** [comment]
Fixed, able to start a cluster and stop the nodes individually 

Here the cluster running:
![image](https://user-images.githubusercontent.com/2641437/131708802-8daadfe7-da30-4e19-af3b-fde494b01daf.png)

Shutting down one of the nodes: 
![image](https://user-images.githubusercontent.com/2641437/131708858-171fa8be-0d05-4e6a-8e34-40c7b7e461ba.png)

After start again is connecting to the cluster without problems

**Comment by swicken-dotcms** [comment]
Changes not necessary for 5.3.8.6
