### ISSUE TITLE
Warning log message incomplete for not allowed categories when retrieving content

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#20801]
Reproducible in dotCMS 21.08

When content is retrieved via REST API, the user can lack permissions to view the categories associated with the content. In that case, a warning message is generated in the log. However, the log message is missing information.

**To Reproduce**
1. Create a new root category and some child categories.
2. For the categories created in the previous step, remove permissions for CMS Anonymous so the categories are not accessible for non-logged users.
3. Create a new content type and add a category field associated with the category root created in step 1.
4. Grant access to CMS Anonymous to the new content type.
5. Create a new contentlet for the content type created in the previous step. Choose a category for the category field, save and publish the contentlet.
6. Send a REST API request without credentials (non-logged user) to retrieve the content from the previous step.
7. The content will be retrieved without the categories, which is expected since CMS Anonymous doesn't have permission to view the categories. This warning message is shown in the log:
```
WARN strategy.DefaultTransformStrategy: Unable to get categories from content with id 
```

**Expected behavior**
The warning message should include more information, such as the field name.

**Additional context**
Here is the line with the warning message:

https://github.com/dotCMS/core/blob/e200badda04f7426159939f113a205aace77b592/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/strategy/DefaultTransformStrategy.java#L311-L312

**Comment by wezell** [comment]
@dsolistorres do you have a quick pr?

**Comment by jcastro-dotcms** [comment]
Thanks @dsolistorres , I'll take care of the code fix.

**Comment by fabrizzio-dotCMS** [comment]
Way better.

`09:15:04.841  WARN  strategy.DefaultTransformStrategy - An error occurred when adding Categories to Contentlet with ID '1a8b0e0bf771003d559d60998ed683ac': User doesn't have permission to read the category = 9f94bd5966e8857a89c82e76123d567b`

**Comment by bryanboza** [comment]
Fixed, now this is working better, tested on release-21.10 // Docker // FF
