### ISSUE TITLE
List view in the upload fields modal is not working propertly

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20817]
Seems we lost something here, If you try to attach some file we are unable to see the icons in grid view, we are getting this. The same thing attaching an image from the WYSIWYG fiels 

![image](https://user-images.githubusercontent.com/2641437/129952182-60edde79-80fe-44c7-90bf-ba6a002c5be7.png)
 
We need some work here 

Tested in docker // Image: 21.09_0712a84

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/20047#issuecomment-901335057_

**Comment by wezell** [comment]
This should be fixed.  It used to look like this:
![Screen Shot 2021-08-24 at 4 27 31 PM](https://user-images.githubusercontent.com/934364/130685356-75e6f5e8-4cf7-4230-80a3-5c022e029221.png)

**Comment by nollymar** [comment]
**Internal QA:** Passed
<img width="1299" alt="Screen Shot 2021-09-10 at 2 26 07 PM" src="https://user-images.githubusercontent.com/8741395/132907132-696e4018-8294-4686-9717-cf581eb2bf5d.png">

<img width="721" alt="Screen Shot 2021-09-10 at 2 26 52 PM" src="https://user-images.githubusercontent.com/8741395/132907098-19999256-b260-4715-8890-3f517d3905b4.png">
<img width="1435" alt="Screen Shot 2021-09-10 at 2 27 33 PM" src="https://user-images.githubusercontent.com/8741395/132907111-1f91fcb5-bd3d-4dd4-a33e-0c79558cbfb7.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF

**Comment by nollymar** [comment]
**Additional PR:** https://github.com/dotCMS/dotcms-dojo-theme/pull/83
