### ISSUE TITLE
Create SaveDraft for templates

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#20820]
Create a rest endpoint for template that saves a draft instead of a new version; with that functionality the auto save will just stored on the top without creating many versions of the template for each save
requirements:
1 - if the template does not have an identifier -> create a new version
2 - if the template does not have an inode -> create a new version 
3 - if the template has an id but does not exists  -> create a new version 
4 - if the working version is the same inode of the live version  -> create a new version 
5 - if the user updating the template is not the same of the user that created the working version  -> create a new version 

Otherwise override the template by using the same inode + id.

**Comment by bryanboza** [comment]
Fixed, now we have the endpoint and works as expected, tested on release-21.10 // Docker

FYI: this is just the endpoint, not used yet from the UI
