### ISSUE TITLE
Add simple endpoint to monitoring resource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20827]
The monitoring resource `/v1/system-status` is good but it too broad a check to be used as a health check for a dotCMS pod.  For example, in many cases, dotCMS front end can run/survive/recover if there are es or db outage or hiccups.  If there is a db or es outage, we should not necessarily be restarting pods.  

We need a new "simple" endpoint.  `/v1/system-status/alive`
The endpoint does not return any data.  It should call   It's only job is to return a response code - 200 if the server is up and 503 if it cannot respond.

All we need to check is that dotCMS is up and can return a 200 response code.

**Comment by wezell** [comment]
Tested taking down ES and the database and this check still returns 200.

**Comment by bryanboza** [comment]
Fixed, now we the endpoint and is working as expected, Also postman test added
