### ISSUE TITLE
Remove Batik Dependency

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20847]
When switching my IDE compiler/compliance to java 11, I get a lot of errors with classes that use SAX and XML.  This is happening because we ship with Batik which has a deep dependency tree and includes specifically the `xml-apis:xml-apis` which are now part of java.

We used to use Batik to read SVG images but we no longer need it as we now include `com.twelvemonkeys.imageio:imageio-batik` which provides an `ImageReader` that can read SVGs.

See howlgers comment here on the conflict between including `xml-apis` and the system module `java.xml`:

https://stackoverflow.com/questions/58226222/xml-api-jar-and-org-xml-sax-classes-having-issues-with-java-11

> The system library module java.xml contains the package org.xml.sax.helpers and therefore no JAR on the classpath (= <unnamed> module) is allowed also to contain the org.xml.sax.helpers package.

**Comment by wezell** [comment]
We need to just verify that the SVGImageReader is working and remove the`getSVGImageDimentions` method. SVG image dimensions are somewhat indeterminate

**Comment by fabrizzio-dotCMS** [comment]
according to this https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-batik/3.7.0
isn't meant to exist on its own. it depends on several artifacts to function correctly. 

I was able to isolate the individual dependencies filtering out the transitive dependencies.    
so the list comes down to this: 

   ```
    compile(group: 'org.apache.xmlgraphics', name: 'batik-transcoder', version: '1.14'){
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-dom', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-xml', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-svg-dom', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-bridge', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-css', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-gvt', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-util', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-anim', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-i18n', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-constants', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-ext', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-parser', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-script', version: '1.14') {
        transitive = false
    }
    compile(group: 'org.apache.xmlgraphics', name: 'batik-awt-util', version: '1.14') {
        transitive = false
    }
    compile (group: 'org.apache.xmlgraphics', name: 'xmlgraphics-commons', version:'1.5') {
        transitive = false
    }
    compile( group: 'org.apache.xmlgraphics', name: 'batik-codec', version:'1.10') {
        transitive = false
    }
    compile group: 'xml-apis', name: 'xml-apis', version: '1.3.04'
    compile group: 'xml-apis', name: 'xml-apis-ext', version: '1.3.04'

```

The dependency tree looks much cleaner 

```
+--- org.apache.xmlgraphics:batik-transcoder:1.14
+--- org.apache.xmlgraphics:batik-dom:1.14
+--- org.apache.xmlgraphics:batik-xml:1.14
+--- org.apache.xmlgraphics:batik-svg-dom:1.14
+--- org.apache.xmlgraphics:batik-bridge:1.14
+--- org.apache.xmlgraphics:batik-css:1.14
+--- org.apache.xmlgraphics:batik-gvt:1.14
+--- org.apache.xmlgraphics:batik-util:1.14
+--- org.apache.xmlgraphics:batik-anim:1.14
+--- org.apache.xmlgraphics:batik-i18n:1.14
+--- org.apache.xmlgraphics:batik-constants:1.14
+--- org.apache.xmlgraphics:batik-ext:1.14
+--- org.apache.xmlgraphics:batik-parser:1.14
+--- org.apache.xmlgraphics:batik-script:1.14
+--- org.apache.xmlgraphics:batik-awt-util:1.14
+--- xml-apis:xml-apis:1.3.04 -> 1.4.01
+--- xml-apis:xml-apis-ext:1.3.04
```

**Comment by nollymar** [comment]
After these changes, I've been able to manipulate svg images successfully:

<img width="1423" alt="Screen Shot 2021-09-10 at 12 56 53 PM" src="https://user-images.githubusercontent.com/8741395/132897098-809b3978-1054-409e-a0f0-ffc13c8d9b15.png">


<img width="1399" alt="Screen Shot 2021-09-10 at 12 57 21 PM" src="https://user-images.githubusercontent.com/8741395/132897119-5cc56360-1646-47ca-a9c4-472b32ef64e0.png">


<img width="809" alt="Screen Shot 2021-09-10 at 12 57 27 PM" src="https://user-images.githubusercontent.com/8741395/132897145-c30a1f9e-fd09-49f1-82b4-00ccefd5c3e1.png">

**Comment by bryanboza** [comment]
We need some work here: 

After this changes now we are getting some problems using svg images: 
- If you edit using the image editor, we are unable to see the thumbnail  
![image](https://user-images.githubusercontent.com/2641437/133643588-257eed53-eaf8-4f76-b229-0809ad8a3834.png)
- We are overriding the UI when you open to edit 
![image](https://user-images.githubusercontent.com/2641437/133643675-619a5bf0-ff86-48c6-b341-29dc8ed8dacd.png)

**Comment by nollymar** [comment]
The second issue is out of the scope of this task, as it is happening on older versions. It is not a consequence of these changes

**Comment by bryanboza** [comment]
Fixed, the mentioned bug was moved to a new card #21051
