### ISSUE TITLE
Automate Docker image generation on commits to Release branch

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20841]
Using this parameter values:

* Custom label to add as part of the tag : "" (empty)
* Update stable tags: false
* Update also the "latest" tag (relies on update_stable input to be set to true): false
* Dry Run (does not publish to docker hub): false

Once published a notification to #developers channel in slack including the image name would be useful.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20843
