### ISSUE TITLE
System Workflow should be used as default when no license is set

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20840]
If you deploy a fresh installation using full starter data, it isn't possible to edit a piece of content if a community license is used. The reason is that a default workflow is not set at startup time for the existing content types and there is no way to change it unless an enterprise license is set.

![Screen Shot 2021-08-24 at 10.45.30 AM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/383e51a1-5566-4592-87b5-db9f2e0ecb6c)

![Screen Shot 2021-08-24 at 10.45.54 AM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/698afcc9-f0fb-4165-8ca7-df672c3a7f7d)

**Comment by wezell** [comment]
When saving a content type when you have a community license, we automatically set the workflow to the default workflow.

**Comment by nollymar** [comment]
This issue happens when you try to edit a Blog

**Comment by fmontes** [comment]
This is a backend fix.

**Comment by fmontes** [comment]
**STR**

1. Start with full starter
2. Edit a blog post
3. See the error.

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/751424/170785276-d734f40f-0f86-4b3d-9226-6a26d9ed0187.png">

You can't trigger any workflow.

**Comment by jdotcms** [comment]
I think the issue is b/c the Blog is already on another workflow, I mean it is not orphan content.
I think you have to pay to use this content type

**Comment by fmontes** [comment]
By default, you can save blogs now without license.

**Comment by josemejias07** [comment]
QA Failed.

Tested on release-22.07 // Docker // OS12.5 FF 103.0.1 (**22.07_69e8413e_SNAPSHOT**)

When editing the Blog using a community license, the user is unable to edit some fields. (Title, tags, texts)
![Screen Shot 2022-08-02 at 2 49 19 PM](https://user-images.githubusercontent.com/110418590/182473253-0ccb79d1-445d-47f7-ab22-37ad29d8d41e.png)
![Screen Shot 2022-08-02 at 2 51 19 PM](https://user-images.githubusercontent.com/110418590/182473272-76c2d82e-9ed6-4070-9ec2-d3187f0fba06.png)

**Comment by fmontes** [comment]
Not a fix.
