### ISSUE TITLE
[EPIC]: Provide Simplified Way to Manage Content

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20858]
**Is your feature request related to a problem? Please describe.**
We hear over and over again the **browser tree** and clicking on folders to get to edit mode is confusing for non-technical people.

**Describe the solution you'd like**
We want to provide an easier way for users to create and edit their own content, especially pages.

We need shortcuts to create pages and contentlets but also a faster way to manage users' content, like most recent for example to create a "user-tailored" content list.

**Describe alternatives you've considered**
Create an angular portlet that will act as the first portlet for users.

**Additional context**
- We need mocks
- We need to check what endpoints do we need
- We need to add this portlet to the starter

**Rough ideas**

![image](https://user-images.githubusercontent.com/751424/131032929-216bd375-bead-4222-8b1f-6bb6e7d5b93e.png)

--------

![image](https://user-images.githubusercontent.com/751424/131599285-679707bb-a21c-4a61-915e-490827e9504f.png)

**Comment by wezell** [comment]
@fmontes is the basically the new page manager?

**Comment by fmontes** [comment]
> @fmontes is the basically the new page manager?

Not exactly, this was thinking on managing all contentlets

**Comment by fmontes** [comment]
Closed and using Page Manager for starting.
