### ISSUE TITLE
When you remove a Site/Folder field it moves all contentlets to SYSTEM_HOST regardless of where the Content Type lives

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20850]
**Describe the bug**
When you remove a site/folder field from a content type, all contentlets of that content type are moved from where they currently live to `SYSTEM_HOST`

Ticket: https://dotcms.zendesk.com/agent/tickets/105076

Reproduced on: 5.3.8.5 and 21.08

**To Reproduce**
1. Create a new Content Type that lives on a Site (not `SYSTEM_HOST`)
2. Create a contentlet of that type. 
3. Check the JSON response (click History tab/JSON) to see the host listed. It will be the UUID of the site.
4. Add the Site/Folder field to the content type.
5. Remove the Site/Folder field from the content type. 
6. Check the JSON response for the contentlet again, the host field will now be `SYSTEM_HOST`

**Expected behavior**
The contentlet should either stay where it was set on the Site/Folder field, or it should be reset to where the Content Type lives. Having it go to `SYSTEM_HOST` feels like unexpected behaviour.

**Comment by wezell** [comment]
yeah, I would say that I believe it should move to where the content type lives.

**Comment by wezell** [comment]
Now that we have the Move subaction, we should just not reset all the content locations - the content should just continue living where it was originally placed.

**Comment by wezell** [comment]
Additionally, I do not believe we need to run a reindex on the content content type.

**Comment by bryanboza** [comment]
Fixed, tested on releaes-21.10 // Docker // FF
