### ISSUE TITLE
Release License on Shutdown

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20856]
When dotCMS is shutdown, we do not release the license it was using.  Instead we rely on the HeartbeatJob to clean up the licenses of non-responsive servers.  This means that when looking at a scaling cluster, it seems like the cluster has bad members because their licenses have not been released.

We need to release the license on normal shutdown so that the cluster will not be out of sync.

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify that the server id is properly registered when the server starts up and removed when the server is shutdown by simply doing `SELECT * FROM sitelic`

**Comment by bryanboza** [comment]
Fixed, tested with docker cluster on release-21.10
