### ISSUE TITLE
Make sure our threadpools have names

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20869]
We spin up a lot of threadpools and many times it is hard to identify what thread and threadpool goes where.  This change automatically adds a thread name patterns to the threadpools that use the DotConcurrentFactory which means that each thread spun up on the pool will automatically have a name that associates it to the pool.

**Comment by fabrizzio-dotCMS** [comment]
A few threads still don't have a name but all threads dispatched by ConcurrentFacotry have a name.
