### ISSUE TITLE
Create a blog demo for nextjs example repo

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20864]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
- https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

**Comment by wezell** [comment]
This work is being done here:

https://github.com/dotCMS/next.js/tree/canary/examples/cms-dotcms

**Comment by fmontes** [comment]
Closing in favor of: https://github.com/dotCMS/core/issues/21804
