### ISSUE TITLE
Reorder window have some problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20868]
If you are reordering the menu in a page we have some problems in this screen: 

- The cancel button does not working 
- The save changes takes some time, then you can click multiple times and this cause the page reload multiple times too 

**To Reproduce**
- Edit some page 
- Try to reorder the menu
- Made some change 
- Click multiple times on the Save changes button 

**Expected behavior**
We need to save that changes faster or at least lock the button after click on it 

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/131189549-de3dfe87-c4a5-4e4d-a295-9f1e46d2e3b5.png)

**Desktop (please complete the following information):**
Tested on release-21.09 // Docker // FF

**Comment by nollymar** [comment]
Additional PR: https://github.com/dotCMS/core-web/pull/1742

**Comment by nollymar** [comment]
**Internal QA:** Fixed

**Comment by bryanboza** [comment]
Fixed, now the cancel button works and we are disabling the save button after one click, tested on docker // release-21.09
