### ISSUE TITLE
Clicking on a page/file in the site browser moves it. Also Right click menu does not show up correctly

### ISSUE THREAD

**Issue by rweiner** [dotCMS/core#20877]
**Describe the bug**
This was found in auth on 8/30/21
When you click on a file,image,page (anything except a folder) in the site browser instead of opening the item it will move the text to the top of the page. Double clicking allows you to open it without the UI bug

Right click menu issue:
When you right click a line in the site browser the menu gets cut off

**To Reproduce**
1. Go to site browser
2. Single Click on a image, file or page
3. See the text move
4. right click the first or second line in the site browser 
5. see menu cut off

**Expected behavior**
These UI bugs shouldn't be there

**Screenshots**
<img width="1079" alt="Screen Shot 2021-08-30 at 8 51 02 AM" src="https://user-images.githubusercontent.com/4575564/131367616-58e6ef8b-0f7b-4672-8ad5-b51e5975e5c7.png">

<img width="1076" alt="Screen Shot 2021-08-30 at 8 51 14 AM" src="https://user-images.githubusercontent.com/4575564/131367472-68cc778a-b9d1-4219-ba95-e5595f6d63bb.png">

**Comment by hmoreras** [comment]
![image](https://user-images.githubusercontent.com/31667212/134426160-313f32ec-1e71-43e3-8acb-6ce3ccadc7f5.png)

The menu still cut-off

**Comment by wezell** [comment]
Let's remove the "rename" from the old browser. It has always been difficult to work with and I am not sure that its code path is correct when renaming different assets, e.g. fileAssets, pages, links

**Comment by bryanboza** [comment]
Fixed, tested on release-21.11 // docker // FF
