### ISSUE TITLE
Widlcard search for timezone

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20888]
In the company portlet, when we search for a timezone it only matches against the first characters. We need to wildcard match.

**Comment by nollymar** [comment]
PRs: https://github.com/dotCMS/core-web/pull/1754 https://github.com/dotCMS/core/pull/20889

**Comment by nollymar** [comment]
**Internal QA:**  Passed.

The filter search works correctly from both: the Basic Config time zone select box and the Push Publish popup

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF
