### ISSUE TITLE
SAML Logins do not update the Last Login date

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20893]
**Describe the bug**
SAML Logins do not update the last login date in the user portlet. 

Tested on: 21.09/5.3.8.5
Ticket: https://dotcms.zendesk.com/agent/tickets/105139

**To Reproduce**
1. Log in as a user via SAML
2. Check that users last login date via the Users portlet

**Expected behavior**
All logins should update the last-login date.

**Comment by erickgonzalez** [comment]
Still not updating the last login date.

**Comment by bryanboza** [comment]
Fixed, now we are updating that property. Tested with SAML configuration in the release-21.10 // docker 
![image](https://user-images.githubusercontent.com/2641437/135531729-dd945624-b674-40a4-9a88-2ffcd1c91c5f.png)
