### ISSUE TITLE
Updates to gzip compression settings in server.xml Docker template 

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#20892]
1) In the [Docker server.xml template](https://github.com/dotCMS/core/blob/master/docker/dotcms/ROOT/srv/templates/tomcat/OVERRIDE/conf/server-9.0.41.xml), gzip compression is enabled on ports 8080 and 8443 Connectors only. 
It should be enabled on all ports (cloud uses 8082 extensively).

```
compression="on"
compressionMinSize="128"             
compressableMimeType="text/html,..."
useSendfile="false"
```

2)  `compressableMimeType` should include fonts and svg
```
font/eot
font/otf
font/ttf
image/svg+xml
```

3) Port 8081 Connector can probably be removed. 
Cloud does not use or need 8081.

**Comment by yolabingo** [comment]
I thought we could remove 8081 as far as Cloud Engineering is concerned but upon closer inspection, each connector does serve a different purpose. 8081 is the dotCMS port to use behind an HTTP proxy listening on port 80.

Additionally, 8081 is used in all our existing [docker-compose examples](https://github.com/dotCMS/docker/blob/3232f1a51a1de54c0ccd0788944cd30d78050136/examples/01-single-node-clean/docker-compose.yml#L47). These examples s

Some significant Connector settings are
```
port
proxyPort # the listening port on the external proxy server 
scheme
secure
```
<img width="688" alt="Screen Shot 2021-10-01 at 3 35 54 PM" src="https://user-images.githubusercontent.com/628954/135688834-352c3d70-8aeb-4849-8504-eabc888b7465.png">

**Comment by wezell** [comment]
PR: #21453
