### ISSUE TITLE
Create endpoint to get config properties

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20891]
**Is your feature request related to a problem? Please describe.**
Need a way to get configuration variables (`dotmarketing-config.properties`) so we can custom our UI or change it behavior.

**Describe the solution you'd like**
Create an enpoint `/api/v1/config?query=PROP_1,PROP_2` where in a queryparam we can pass a list of property name to get back in a json object as a key value pair.

**Additional context**
The REST api should also respect the blacklist built for the `/api/v1/jvm` endpoint, meaning, it can't be used to pull back things like the db password, etc...

In fact, there might be a white list in the `dotCMS/src/main/resources/dotmarketing-config.properties` of variables that can be requested.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // docker... This is used by the content pallet and also the postman test are running
