### ISSUE TITLE
Move actionlet enhancements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20905]
Related to #20504 

After the related card, we have some enhancements 

- [x] This text need some styling 
![image](https://user-images.githubusercontent.com/2641437/131898503-ea793763-8011-4946-8e2b-e5b486439995.png)

- [x] According to the card we need to add the Move action in the bulk actions list (Need to add in both starters)
![image](https://user-images.githubusercontent.com/2641437/131898667-f54f9cbe-9609-4108-bc57-362dcb6744f8.png)

- [x] We need to validate the path in lowercase, If you type a path in upper case and the folder exist in lowercase, the is showing a message that a new folder will be created, and it is moving to the existing one.
![image](https://user-images.githubusercontent.com/2641437/131899975-de1e8043-dd99-4e57-b835-d52abd00e5bd.png)

- [x] If you select some suggested paths, then delete some the "/" then put type this again, we are showing a message that the url does not exist 
https://user-images.githubusercontent.com/2641437/131911797-e84495e9-d3aa-41d1-9d17-5db7bf05e5b9.mov
The same thing if you manually type the complete path, just work if you select one of the suggesting paths 

**Desktop (please complete the following information):**
Tested on release-21.09 // Docker

**Comment by hmoreras** [comment]
info message changes: https://github.com/dotCMS/core-web/pull/1751

**Comment by bryanboza** [comment]
After the last fix, now we are unable to create a new folder if the path does not exist. We need some work here

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // docker
