### ISSUE TITLE
Create prerender.io App

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20903]
We need to create an app that implements the prerender.io filter as a WebIntercepter and allows a user to configure  prerender and the options available 

Here is the filter
https://github.com/greengerong/prerender-java

and here are the configuration options available:
https://github.com/greengerong/prerender-java/blob/master/src/main/java/com/github/greengerong/PreRenderSEOFilter.java#L18

The initial implementation should be a plugin that can with with 5.3.8.x and we should also build this into the core

**Comment by wezell** [comment]
PR: #21795

**Comment by jdotcms** [comment]
Waiting just for internal QA

**Comment by jcastro-dotcms** [comment]
Internal QA performed with our Demo Site:

- Go to **Settings > Apps > dotCMS prerender App** and set the `prerenderToken` for both System Host and demo.dotcms.com Sites. If you don't have it, please reach out to me.
- Use the following CURL command to simulate a request that will go through the Prerender service:
```
curl -v -s -H 'User-Agent: twitterbot XXXX' -H 'Host: www.demo.dotcms.com' https://demo.dotcms.com/index 2>&1 | grep -i  x-prerender
```
Notice the `XXXX` after the User Agent's name, which is required for the request to go through the service.
- Check the Crawler Visits page in the Prerender Dashboard: https://dashboard.prerender.io/crawl-stats and make sure that there's an entry matching your request. For example, using the `twitterbot` Agent, you should get something like this:

<img width="756" alt="twitterbot" src="https://user-images.githubusercontent.com/8779585/168127379-6aabdd54-e899-4603-8cb3-3c139e0c4532.png">

Prerender may take a few minutes to refresh the Dashboard, so your request might not show up immediately. If you don't have access to the Dashboard, please reach out to me.

**Comment by bryanboza** [comment]
Fixed, tested on demo.dotcms.com and now we are able to connect using the prerender app. 
![image](https://user-images.githubusercontent.com/2641437/171966064-35b8868f-c161-4f0a-8949-c30883a28c61.png)
