### ISSUE TITLE
SPA: Update the demo.dotcms vercel script

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20900]
### Describe the bug
We have the nextjs starter demo deployed in Vercel and pointing to demo.dotcms.com.

The problem is that demo.dotcms.com restart every 24h, so when that happened we lose the token we have stored inside Vercel env tokens.

### To Reproduce
Go to: http://demospa.dotcms.com/ and see how is broken because auth.

### Expected behavior
It should add restart the token in Vercel every day after demo restart.

### Additional context
We have this [script](https://github.com/dotCMS/demo.dotcms.com/blob/master/vercel-env-load.sh#L92) that is not working.

This script is the one that runs every 24h.

1. Not sure why is not working
2. I think we have to pass that the env var applies to all targets.

### Acceptance criteria
- Keep the http://demospa.dotcms.com/ working  everyday

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/20900?planning-poker) with Zenhub @rjvelazco @hmoreras

**Comment by rjvelazco** [comment]
**To shared information**

The `unauthorized user` error we got on the website was due to Vercel's default behavior of deploying the last successful build. Not being the latest demo version, the token was outdated.

**Comment by fmontes** [comment]
Working now:

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/751424/194653324-3d034fff-724e-42ba-bd4d-1268d50ea5e8.png">
