### ISSUE TITLE
PAGE EDITOR: Robust data saving and error handling

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20904]
### Problem

Customers can modify the DOM of a page with JavaScript which can lead to having duplicated containers and/or contentlets.

Since we create the payload we use to save the page using the containers DOM elements and data attribute this might result in duplicated containers which makes the endpoints fail.

A container DOM element look like this:

```html
<div
    data-dot-object="container"
    data-dot-identifier="//demo.dotcms.com/application/containers/banner/"
    data-dot-uuid="1">
    <div
        data-dot-object="contentlet"
        data-dot-inode="fcfe6e4a-b90d-454c-b9ae-18c79aa83972"
        data-dot-identifier="2e5d54e6-7ea3-4d72-8577-b8731b206ca0"
    >
    <!-- CONTENTLET INFORMATION -->
    </div>
</div>
```

**Out of this HTML, we create a payload like this:**

```JSON
[
    {
        "identifier": "//demo.dotcms.com/application/containers/banner/",
        "uuid": "1",
        "contentletsId": ["2e5d54e6-7ea3-4d72-8577-b8731b206ca0"]
    }
]
```

**If the user duplicated the container DOM element the payload will be:**

```JSON
[
    {
        "identifier": "//demo.dotcms.com/application/containers/banner/",
        "uuid": "1",
        "contentletsId": ["2e5d54e6-7ea3-4d72-8577-b8731b206ca0"]
    },
    {
        "identifier": "//demo.dotcms.com/application/containers/banner/",
        "uuid": "1",
        "contentletsId": ["2e5d54e6-7ea3-4d72-8577-b8731b206ca0"]
    }
]
```

And since is the same container id and uuid the endpoint fails.

**Describe the solution you'd like**

1. Update the endpoint to do an upsert when the payload have duplicated containers instances
2. Update the UI to show an error when the endpoint to save the page fails.

**Comment by jcastro-dotcms** [comment]
Customer report: https://dotcms.zendesk.com/agent/tickets/105111
