### ISSUE TITLE
Respect the order of params passed to /dA

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20913]
The /dA call does a good job of simplifying some of our image filters, but the order of operations are hard coded in the Servlet.  This means that if you try to `resize` AND apply `webp`, it will not work and the resulting image is `.png`

This should be a webp image:

https://demo.dotcms.com/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/270w/webp/diving.jpg

WebP only works if you use the quality param:

https://demo.dotcms.com/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/270w/50q/diving.jpg

What we need to do is respect the order of the param arguments and based upon them, run the filters in that order.

**Comment by fishsmith** [comment]
The simple image path does not respect the filter order. 

EXAMPLE 1:
https://dotcms.com/contentAsset/image/b0cf4b1c-e7ab-4a1c-8bfa-ee48021f2dd7/image/resize_w/1280/crop_w/512/crop_h/240/fp/.75,.4

Order: Resize > Crop Width > Crop Height 

EXAMPLE 2:
https://dotcms.com/dA/b0cf4b1c-e7ab-4a1c-8bfa-ee48021f2dd7/1280w/512cw/240ch/fp/.75,.4

Order: Crop Width > Crop Height > Resize

**Comment by nollymar** [comment]
This change should have tests
