### ISSUE TITLE
Generate secure password for users

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20915]
**Is your feature request related to a problem? Please describe.**
Admin users need an easier way to generate a secure password.

**Describe the solution you'd like**

https://user-images.githubusercontent.com/751424/132049638-83cf022e-8c7b-4e71-a529-ec621175ecce.mp4

**Comment by wezell** [comment]
![Screen Shot 2021-09-07 at 3 40 59 PM](https://user-images.githubusercontent.com/934364/132401615-90e5af4a-4ba9-473a-b586-e5bbececee02.png)

**Comment by alfredo-dotcms** [comment]
PRs
Core: https://github.com/dotCMS/core/pull/20988/files
core-web: https://github.com/dotCMS/core-web/pull/1759

**Comment by wezell** [comment]
The generator generates passwords that do not match our default regex pattern.  You can see the password that was trying to be saved because I changed the field to `text`

![Screen Shot 2021-09-21 at 5 57 54 PM](https://user-images.githubusercontent.com/934364/134253474-54ac4ecf-c3d0-4c07-af82-a39f616a6801.png)

**Comment by nollymar** [comment]
**Internal QA:** Passed

https://user-images.githubusercontent.com/8741395/135652858-c7c53cfc-4027-47d2-b0c3-cbef749f8d20.mov

**Comment by bryanboza** [comment]
After this fix now the generate secure password stuff is working, but we need some improvements here: 

- The `reveal` filed should be like a checkbox or something like in the attached image 
![image](https://user-images.githubusercontent.com/2641437/138144217-a1de1b2f-a2bc-455f-b19e-8555fd9bc0fc.png)

Right now we have this: 
![image](https://user-images.githubusercontent.com/2641437/138144160-4a82ee5d-bcc3-480a-82a7-08e415281b3a.png)

- When you click in the copy button, we need to send a notifications that the text was copied to clipboard

**Comment by fmontes** [comment]
1. Reveal no, we decided to go with the word not the icon
2. The notification should be in the same button, change it to "COPIED" and after 2 seconds back to "COPY"
3. Definitely we need to do that.

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/138336083-24e018f7-b442-4af2-a65f-bca7f62e0ed7.png)

**Comment by alfredo-dotcms** [comment]
PRs
CORE: https://github.com/dotCMS/core-web/pull/1781
Core-WEB: https://github.com/dotCMS/core-web/pull/1782

**Comment by bryanboza** [comment]
Fixed, tested on release-21.01 // Postgres // FF

**Comment by wezell** [comment]
Labels are missing on authoring.

**Comment by wezell** [comment]
![Screen Shot 2021-11-02 at 3 08 01 PM](https://user-images.githubusercontent.com/934364/139929202-d409f5d7-721d-42d3-8416-fb59c23aadb1.png)
