### ISSUE TITLE
Update Powermock and Mokito to Java 11 supported version

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#20929]
For Java 11 we will need to update Powermock to a java 11 supported version.   This also requires us to update Mokito as the updated Powermock does not support Mokito1 any more

org.mockito:mockito-core:1.+ to org.mockito:mockito-core:2.+
org.powermock:powermock-api-mockito:1.6.5 to org.powermock:powermock-api-mockito2:2.0.9

org.powermock:powermock-module-junit4:1.6.5 to org.powermock:powermock-module-junit4:2.0.9

Known code changes:
   invocation.getArgumentAt(. needs to be changed to invocation.getArgument(

Check out these comments.   There is question on whether Mokito is going to continue to have support,  we should consider alternatives.

https://stackoverflow.com/questions/52966897/powermock-java-11

We should use a global ignore as in the stackoverflow post  so we do not need to modify all the code.  
powermock.global-ignore=com.sun.org.apache.xerces.*,javax.xml.*,org.xml.*,org.w3c.*

We already use a PowerMockIgnore annotation and should see if these should all be moved to the global ignore 

@PowerMockIgnore({"javax.management.*", "javax.crypto.*", "jdk.internal.reflect.*"})

**Comment by spbolton** [comment]
Since mokito 2.1.0. Matchers for specific types will not match null values.  To specifically accept nulls we need to use public static <T> T nullable(Class<T> clazz). e.g. nullable(Stiring.class).   This causes PageResource tests to fail as webResource.init returns null when params is null.  
To handle the following in PageResource.searchPage for example

```
 final InitDataObject initData = webResource.init(null,  request, response,
                true, null);

```
In PageResourcesTest we need to modify 

` when(webResource.init(anyString(), any(HttpServletRequest.class), any(HttpServletResponse.class), anyBoolean(), anyString())).thenReturn(initDataObject);`
       to
`when(webResource.init(nullable(String.class), any(HttpServletRequest.class), any(HttpServletResponse.class), any(Boolean.class), nullable(String.class))).thenReturn(initDataObject);`
       
There may be other failed tests due to this issue we need to resolve,  and check whether the parameter really should be nullable, we should not just make all anyString() to nullable but there are a number of places where the webresource.init method is set to match and all of these should have the two string paramters as nullable

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/21548
