### ISSUE TITLE
NPE /api/v1/folder/byPath

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20939]
When calling the endpoint `/api/v1/folder/byPath` but no body is sent, will throw an NPE. 

We need to validate that the `Path` property is coming in the Body.

STR:
1- On postman call this endpoint `/api/v1/folder/byPath`
2- Leave the body set to none.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF. Also the postman test is running success
