### ISSUE TITLE
Edit contentlet scrollbar hidden or hard to click

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20947]
**Describe the bug**
The scrollbar in the edit contentlet dialog is hard to click and is always hidden, you can only scroll with your mouse wheel.

**To Reproduce**

https://user-images.githubusercontent.com/751424/132398742-47376a37-900a-43b9-a36c-78d3b3fa7071.mp4

**Expected behavior**
We need to show the scrollbar before the sidebar and not after.

**Screenshots**
<img width="1662" alt="Screen Shot 2021-09-07 at 1 15 38 PM" src="https://user-images.githubusercontent.com/751424/132399000-3a1f2518-56a1-4103-be68-8590017885c9.png">

**Additional context**
Probably a CSS issue.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF
