### ISSUE TITLE
Fix dot.dnsjava update version for java11 and Duplicate classes

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#20940]
Prefer to remove use of repackaged jar and use new version directly 

internal apis used, requires explicit allow or version without dependencies

dnsjava-2.1.8.jar -> jdk8internals
   org.xbill.DNS.spi.DNSJavaNameServiceDescriptor     -> sun.net.spi.nameservice.NameService                JDK internal API (jdk8internals)
   org.xbill.DNS.spi.DNSJavaNameServiceDescriptor     -> sun.net.spi.nameservice.NameServiceDescriptor      JDK internal API (jdk8internals)

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    dnsjava:dnsjava:jar:2.1.8:compile
    com.dotcms.lib:dot.dnsjava:jar:2.0.8_2:compile
  Duplicate classes:
    lookup.class
    jnamed$1.class
    dig.class
    jnamed$2.class
    jnamed$3.class
    update.class
    jnamed.class

**Comment by wezell** [comment]
PR: 20953
