### ISSUE TITLE
Material icon selector web component needs to search using wildcard

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20946]
### Is your feature request related to a problem? Please describe.
The selector allows you to search but only look for icons that "start with" the input, for example, if you search for "photo"

**Returns**
- photos
- photo_gallery

**But not**
- camera_photo
- location_photos

### Context
This is a web components so it lives here: https://github.com/dotCMS/core-web/tree/master/libs/dotcms-webcomponents

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // docker // FF
