### ISSUE TITLE
NAVIGATION: two sections opened at the same time

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20942]
**Describe the bug**
Navigation open two groups when both have the same component

**To Reproduce**

https://user-images.githubusercontent.com/751424/132392689-a4cc2791-28f3-4d7c-8f59-677a5eb7e36a.mp4

**Expected behavior**
1. Should only open the section in which portlet I click
2. If a user gets to the section by URL we open the first section that has that portlet

**Screenshots**
<img width="985" alt="Screen Shot 2021-09-07 at 12 14 43 PM" src="https://user-images.githubusercontent.com/751424/132391853-24ce3e65-f759-4af2-adc8-dc8e535ba629.png">

**Comment by rjvelazco** [comment]
https://user-images.githubusercontent.com/72418962/133849217-35927625-b3cf-441e-a3d4-de7083543bdd.mov

**Comment by bryanboza** [comment]
Still getting the same error: 
![image](https://user-images.githubusercontent.com/2641437/135351492-bde0226d-886b-442c-9665-1a8a4954cb9e.png)

Tested on docker // Postgres // Chrome  
Docker image: 21.10_8f36dd3_SNAPSHOT

**Comment by fmontes** [comment]
@bryanboza That's not the error, that's expected we show the first one we found in the nav.

The error was that it was opening both.

**Comment by john-thomas-dotcms** [comment]
The issue @bryanboza is referencing is that even though now, it does display the portlet in only one tool group, the path to the portlet remains the same no matter which tool group you open it in.

That means that if you refresh the tab or bookmark the page and come back to it, you'll end up under the wrong tool group.

It would be ideal if it remembered not just which portlet you opened, but where you opened it, so a refresh/bookmark would take you back to the same place.  But that could potentially go in a separate card.

**Comment by fmontes** [comment]
@john-thomas-dotcms yes, that a limitation we have because our URLs don't have information about the tool groups so when the page gets reload we only know that the "site-browser" is selected so we go through the menu object and we open the first tool group we found with "site-browser" in it.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF

New card was created here: #21098
