### ISSUE TITLE
Assigning roles to users triggers a lot of requests

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20945]
**Describe the bug**
When you assign or remove roles to users it triggers a lot of HTTP requests and with customers having a lot of roles and users it can take up to 15-20 seconds to have the UI responsive again.

**To Reproduce**

https://user-images.githubusercontent.com/751424/132396865-aae4db16-f3ca-48a8-b004-38f222ffa769.mp4

**Expected behavior**
It should not do many requests.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/21022 .
* Need to discuss if we want to create a new endpoint to bring a list of child roles, given an id.

**Comment by erickgonzalez** [comment]
We create a couple of new endpoints:

* `/api/v1/roles` to get the root roles.
* `/api/v1/roles/{roleId}` to get a specific role.

On both endpoints exist a query param called `loadChildrenRoles` that is set by default on **true** meaning that will pull the data of the children roles. This property can be set to **false** so only the data of the requested role will be pulled.

**Comment by erickgonzalez** [comment]
The number of requests was decreased significantly.

![Screen Shot 2021-09-28 at 12 33 11 PM](https://user-images.githubusercontent.com/5278970/135145537-068d428f-0a55-4862-8f91-f430517a3f9b.png)

**Comment by erickgonzalez** [comment]
The number of requests was decreased significantly.

![Screen Shot 2021-09-28 at 12 33 11 PM](https://user-images.githubusercontent.com/5278970/135145537-068d428f-0a55-4862-8f91-f430517a3f9b.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker. Now we have just one request per operation.
