### ISSUE TITLE
Users tabs (permissions and API keys) content not updating 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#20943]
**Describe the bug**
The content of the tabs of "Permissions" and "API Access Keys" are not getting updated when user select another DotCMS user.

**To Reproduce**

https://user-images.githubusercontent.com/751424/132395153-41dd61c5-3777-4275-bdaa-9f1045bb5b98.mp4

**Expected behavior**
1. Tab content should update to match the user selected
2. User selected name should be shown as title in the tab content (same as other tabs)

**Screenshots**
<img width="1098" alt="Screen Shot 2021-09-07 at 12 42 00 PM" src="https://user-images.githubusercontent.com/751424/132395056-7070a2ca-3741-412e-b1d3-8bbd88c2b70c.png">

**Additional context**
Please check why the "Loading..." indicator stays after the content shows, looks like a bug.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Postgres // FF
