### ISSUE TITLE
Response code in Integrity Checker producing a 502

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20965]
When the sender request the integrity data to the receiver, it keeps asking if the results are ready, and when they're not, the receiver response with a 102 code. When behind a proxy, this 102 ends up in a 502, failing on the sender. 

We need to use a different code for expressing the "processing" status.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // docker // FF. Also the postman test is running success

**Comment by jcastro-dotcms** [comment]
Changes cannot be back-ported to dotCMS 5.3.8.7 LTS because of considerable differences in existing code.
