### ISSUE TITLE
Large Bundles make the viewing publishing queue slow

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20971]
When bundling and pushing large bundles - say > 10,000 contentlets, the publishing_queue screen takes a very long time to load.  This is because when listing the bundle, we read in all the contents that belong to the bundle and try to report on them.  
If a bundle is large, we should only report on the top 2 or 3 contents unless a customer clicks view the entire contents (or something that can make the screen more performant).

To reproduce, generate a few large bundles and see if the performance of viewing the bundles gets slow.

**Comment by freddyucv** [comment]
How it is working after the change

https://user-images.githubusercontent.com/10408015/134360242-1933fc16-696c-4d62-b209-5c32711348b4.mov

**Comment by wezell** [comment]
We need a similar fix in all the push publishing queue pages - and keep in mind that the show / hide for large bundles cannot just be superficial - we need to stop reading/resolving the assets after the first 20 unless the user has asked for the whole list.

**Comment by victoralfaro-dotcms** [comment]
The loading of a large bundle summary at Status/History is quite good actually now.

https://user-images.githubusercontent.com/64026161/139502574-8a9d9cf3-5a6a-4881-96c7-018203c11ab6.mov

**Comment by bryanboza** [comment]
Fixed, tested on release-21.11 // Docker // FF
