### ISSUE TITLE
Not retry when a Bundle fail by Integrity Conflicts

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#20978]
When a Bundle fail by Integrity conflicts should no be retry automatically, it is just if the conflicts are not mark to be resolve in the receiver automatically

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/20978?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by dsilvam** [comment]
Estimating to 3 because of also adding an integration test.
