### ISSUE TITLE
Retry bundle does not work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20974]
This is from the status popup and the listing screen

**Comment by freddyucv** [comment]
this is broke from 21.05 with the PP performance changes

**Comment by dsilvam** [comment]
Still needs work: The retry is working but despite of the push being successful in the receiver and the content actually making it through, the sender shoes "Failed to Publish".

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker // FF and this is working fine, new improvement related to the message was moved to a new card #21124
