### ISSUE TITLE
New App: prerender.io

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20989]
We have a number of customer who are looking to enable prerender.io on their dotCMS hosted sites.  We need to create an app that can connect a dotCMS instance to prerender.io.

There is a filter that is available here

https://github.com/greengerong/prerender-java

we should just lift it and re-implement as a Webinterceptor.  All config should be done in the app.yml

**Comment by fmontes** [comment]
Closing in favor: https://github.com/dotCMS/core/issues/20903
