### ISSUE TITLE
Unsupported Actions Display in Host Content Type Edit Screen

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21018]
**Describe the bug**
When creating or editing a Host content type, a user is able to select a workflow and default actions that are unable to be executed on a Host once created. 

![Screen Shot 2021-09-16 at 8 36 53 AM](https://user-images.githubusercontent.com/90852779/133642102-564889af-8760-4fc9-867c-cbcf97c61ec1.png)
![Screen Shot 2021-09-16 at 8 38 35 AM](https://user-images.githubusercontent.com/90852779/133642399-4e27d5a9-bfa1-4450-bae3-49741b3b767a.png)

**To Reproduce**

1. Go to the host content type in demo
2. Click on edit and select a workflow
3. Right click on host in browser view
4. See that actions related to selected workflows are unable to be used

**Expected behavior**
All unsupported actions should be removed from the edit screen view when creating or editing a Host content type.

**Comment by wezell** [comment]
Hosts do not support workflowa
