### ISSUE TITLE
Changing the Focal Point followed by "Save" - Shouldn't generate a new version of the Contentlet - just update the Metadata

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21034]
**Description**
Updating Focal Point and Hitting Save - Shouldn't generate a new version of the Contentlet - just update the Metadata

**To Reproduce**
1. Go to 'content search. Find an image 
2. Open the Editor Click on the image and set a focal-point anywhere
3. Save and Publish the image. Check there's one version of the contnet  
4. Close the image and re-open the editor. Make a change on the focal point and hit save this time.
5. Check there's another version of the contentlet

**Expected behavior**
A new version of the contentlet should be generated only if the image is modified
A change on the Focal point should only update the metadata on the current version of the contentlet
Only A change on the image should create a new version

**Comment by wezell** [comment]
cannot reproduce
