### ISSUE TITLE
Set Persona Action in Rules Engine does not display the list of Personas

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#21049]
Found on dotCMS 21.09 using Chrome

Under the content tab, click search and then find the Persona Content Type.  Add a new persona contentlet.

Now go to the Marketing > Rules and try to use the Set Persona Action - Bug is that you will only see an empty list - no persona contentlets display.  Reindex and cache flush did not fix either

<img width="2037" alt="PersonaBug" src="https://user-images.githubusercontent.com/1569167/134188772-fbfefee9-1495-40f7-b73d-4a2631c6460a.png">

**Comment by wezell** [comment]
issue caused by the change to deterministic ids

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes // Tested on release-21.10 // docker
