### ISSUE TITLE
[Categories] : Improve error/warning logging in Category API

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21053]
Reproducible in ALL versions of dotCMS.

Most of the error messages/logging in the `CategoryAPIImpl` class report the IDs or Inodes of involved contents or fields upon errors that were found when interacting with Categories. However, many times those errors are caused by a specific User not having the right permissions for it. The messages we have no are NOT including the User ID in them, which makes troubleshooting very complex when inspecting dotCMS instances with dozens of users.

**To Reproduce**
The STR from this ticket can be used here: #20801 . In that ticket, the improved error message is:
```
WARN  strategy.DefaultTransformStrategy - An error occurred when adding Categories to Contentlet with ID 'eec45817-d525-4b13-bb42-aff48b65561a': User doesn't have permission to read the category = b5ea40ac-fd38-4857-a2b1-f7f8ef9cb8f0
```
However, as you can see here: `User doesn't have permission to read the category = b5ea40ac-fd38-4857-a2b1-f7f8ef9cb8f0` , this part of the error message comes from the Category API, and is NOT indicating what User ID has problems with this operation.

**Comment by erickgonzalez** [comment]
Needs Work: seems that this fix has broken some tests, we need to take a look.
