### ISSUE TITLE
Update docker image to use TLS 1.2 when sending mail 

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21063]
update: adding env var 
`DOT_MAIL_SMTP_SSL_PROTOCOLS: 'TLSv1.2'` 

should resolve this issue with any SMTP server that supports TLS 1.2.

I think we need to update JavaMail.

**Describe the bug**
```
ERROR util.Mailer - javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
javax.mail.MessagingException: Could not convert socket to TLS
```

When sending mail via AWS SES using standard SMTP settings
```
DOT_MAIL_SMTP_PORT: 587
DOT_MAIL_SMTP_AUTH: 'true'
DOT_MAIL_SMTP_STARTTLS_ENABLE: 'true'
```

**To Reproduce**
1. run docker image `dotcms/dotcms:21.06.3_lts`
2. configure SMTP relay using TLS
3. request a password reset email

**Additional context**
This seems to be a result of the addition of `TLSv1, TLSv1.1` to disabledAlgorithms:
```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```
in `/java/conf/security/java.security` when we updated to java 11.0.12.

JavaMail is a precompiled jar 
```
Implementation-Version: 1.3.2
Specification-Title: JavaMail(TM) API Design Specification
Specification-Version: 1.3
Extension-Name: javax.mail
```
JavaMail 1.3 only supports TLS 1.0

If I remove `TLSv1, TLSv1.1` from `java.security:jdk.tls.disabledAlgorithms` then dotCMS can send mail.

**Comment by wezell** [comment]
Need to update to JavaMail 1.6

**Comment by yolabingo** [comment]
Two potential work arounds

1) send mail unencrypted
2) override the default `java.security` file - to do so in docker

copy `/java/conf/security/java.security` from the container
remove `TLSv1, TLSv1.1,` from 
```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```
and mount it in the container, replacing the original java.security file

**Comment by cobbg** [comment]
Attempting to mount in a modified `java.security` file is problematic on Kubernetes due to the directory and file permissions being owned by root.

It seems that using the environment variable below resolves TLS issues with the existing image and AWS SES.

```
DOT_MAIL_SMTP_SSL_PROTOCOLS: 'TLSv1.2'
```

**Comment by yolabingo** [comment]
Regardless of the version of JavaMail we should add 
`ENV DOT_MAIL_SMTP_SSL_PROTOCOLS=TLSv1.2
`

when building docker images

**Comment by wezell** [comment]
We need to do this on our current docker image by default

**Comment by wezell** [comment]
should we do that or just add it to the dockerize default template?  I'd hate to have our env variables in 2 places.

**Comment by wezell** [comment]
Add this to our LTS docker images
```
ENV DOT_MAIL_SMTP_SSL_PROTOCOLS="TLSv1.2"
```
