### ISSUE TITLE
session_replication_role upgrade failure when using AWS RDS

### ISSUE THREAD

**Issue by cobbg** [dotCMS/core#21065]
**Describe the bug**
When upgrading an existing version of dotCMS to 21.06.3, the database upgrade script encounters the error below.

```
18:02:46.998  INFO  db.DotConnect - Executing SET session_replication_role TO 'replica'
18:02:47.003  FATAL runonce.Task201014UpdateColumnsValuesInIdentifierTable - Unable to execute SQL upgrade
org.postgresql.util.PSQLException: ERROR: permission denied to set parameter "session_replication_role"
```
This is due to a difference in the way the managed RDS service controls roles vs. typical PostgreSQL. Adding the `rds_replication` role to the user in question seems to produce the same error. Adding the `rds_superuser` role, or simply using the default `postgres` user, results in the upgrade script completing successfully. Revoking the former role after the upgrade procedure completes does not seem to cause an adverse issues with normal operations.

This was not a problem in the past when upgrading databases running on RDS.

**To Reproduce**
1. Import an existing dotCMS database that will trigger an upgrade when dotCMS 21.06.3 connects.
2. Start dotCMS and watch the log entries related to the upgrade task.

**Expected behavior**
The upgrade to complete successfully without granting a superuser role to the dotCMS user.

**Additional context**
This has only been tested on AWS RDS PostgreSQL. Other managed database services may have a similar issue, but they have not been tested.

**Comment by wezell** [comment]
Interesting.  Actually, the only reason we added the `SET session_replication_role TO 'replica'` in order to allow the upgrade script to work on Aurora Postgres. So to be clear, `SET session_replication_role TO 'replica'` does not work on RDS but does on Aurora
