### ISSUE TITLE
Make widgets headless support

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21079]
**Is your feature request related to a problem? Please describe.**
Typically widgets code allows you to create a listing of any content types and use the `widgetCode` to create the template. 

This will work very well with regular pages but in headless (using the APIs) the response is a string of HTML which is not useful in JavaScript frameworks.

**Describe the solution you'd like**
We need to modify the `widgetCode` field to allow developers to add not only HTML but create their JSON data and this data will be returned in the APIs while the HTML will be use for tomcat generated pages.

**Code Example**
```
#set($blogs = $dotcontent.pullPerPage("+contentType:Blog +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST)", $page, 6, "Blog.postingDate desc")))

#set($resultList = [])

#foreach($con in $blogs)

    // RENDER HTML FOR PAGES
    <h3 class="post-title"><a href="/blog/post/$!{con.urlTitle}">$!{con.title}</a></h3>

    #set($resultdoc = {})
    $resultdoc.put("identifier", ${doc.identifier})
    $resultdoc.put("inode", ${doc.inode})
    $resultdoc.put("title", ${doc.title})
#end

// RETURN JSON FOR APIS
$dotJSON.put("docs", ${resultList})
```

**Comment by wezell** [comment]
![Screen Shot 2021-10-20 at 3 12 41 PM](https://user-images.githubusercontent.com/934364/138157048-079570d4-0110-4888-84a3-1c472cdf4c35.png)

**Comment by freddyucv** [comment]
**Passed Internal QA**: Tested with the follow case:

- Create a Content Type called type_1, with a text field named title.
- Create a widget content  type named 'widget-test' and in the 'widgetCode' field set the follow:
<code>
#set($blogs = $dotcontent.pull("+contentType:Type1", -1, ""))

#set($resultList = [])

#foreach($con in $blogs)

    <h3>$!{con.title}</h3>

    #set($resultdoc = {})
    #set($resultdoc.identifier = ${con.identifier})
    #set($resultdoc.inode = ${con.inode})
    #set($resultdoc.title = ${con.title})

    #set($notUsedValue = $resultList.add($resultdoc))
    
#end

$!dotJSON.put("docs", ${resultList})
$!dotJSON.put("test", "test")
</code>
- Create a page and add a new 'widget-test' contentlet
- Request to: http://localhost:8080/api/v1/page/render/page-test
and you should get the 'widgetCodeJSON' into the contentlets
- Also check that the page is rendered how is expected

**Comment by bryanboza** [comment]
Fixed, tested according to the provided steps and now we have the same result in both cases: 

From graphQL:
![image](https://user-images.githubusercontent.com/2641437/142944349-d9e76d1c-5091-4d1f-946a-0c5e6cf88c1f.png)

From browser:
![image](https://user-images.githubusercontent.com/2641437/142944415-08b40771-a5a7-444e-a4b9-c2736e674e46.png)


Tested on release-21.12 // Docker // FF
