### ISSUE TITLE
PDF thumbnail not showing for files in content search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21080]
**Describe the bug**
The thumbnails of the PDF in content search not showing when the asset is a `file` content type.

**To Reproduce**
1. Upload a PDF as a `dotasset` and one as a `file`
2. Search for them in content search
3. Set the view to "Card"

**Expected behavior**
Thumbnails should show in all PDF assets

**Screenshots**
![image](https://user-images.githubusercontent.com/751424/134723828-479c38ee-5c3f-4b38-bb56-dfb759b54af9.png)

**Comment by rjvelazco** [comment]
The pdf icon in a file content type is only visible in the startup file that is on `demo`. When you upload a new pdf as file content type, the thumbnail is being shown.

**Comment by fmontes** [comment]
Updated the starer, closing.
