### ISSUE TITLE
[Static Publishing] : Only images with "/contentAsset/" are being pushed by dependency in URL Mapped content

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21094]
Reported via Support: [105289](https://dotcms.zendesk.com/agent/tickets/105289)
Reproducible in dotCMS 5.3.8.5, 5.3.8.6, up to latest master (21.09)

URL Mapped contents can have **Image** fields in their type definition. Such images should be pulled by dependency when those pieces of content are pushed to an S3 bucket. However, depending on how the URL is being built, dotCMS will **NOT** include them in the bundle. For example, when referencing an image file, if the URI is built like this:
```
<img src="/contentAsset/image/${content.imageField.identifier}"/>
```
The Static Publishing process will be able to find such an image, and push it to S3. However, if the URI is created based on the actual path and name of the image file, like this:
```
<img src="${content.imageField.path}${content.imageField.fileName}"/>
```
The `src` attribute would be, for example: `/asset/img/my-picture.jpg`. The system will not be able to find it, and image will **NOT** be included by dependency.

**To Reproduce**
Please reach out to me in order to get more information on the required data set.

**Expected behavior**
If we're parsing the page/content/VTL files looking for paths, we should recognize any valid image path (not just the /contentAsset/image/ format).

**Additional context**
There are currently two workarounds for this problem:

1. Push the folder containing the image files separately, as those images will NOT be pulled by dependency.
2. Change the `src` attribute from using the image path to using the `/contentAsset/` servlet.

**Comment by wezell** [comment]
Image/File fields for URLMapped content and/or HTMLPage content should be pushed as dependencies
