### ISSUE TITLE
Navigation: Need remember the tool-group when you have a portlet associated to two or more groups 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21098]
We are not remembering the tool-group when you have a portlet that is associated to two or more groups and you refresh the page. 

We are reloading page and open the navigation tree in the first group, and not in the one you was located.

For now is a minor issue but we need to find some way to remember the selection. 

Still getting the same error: 
https://user-images.githubusercontent.com/2641437/135351697-d2aa2f4d-64c8-466d-b083-e9065d29d48b.mov

Tested on docker // Postgres // Chrome  
Docker image: 21.10_8f36dd3_SNAPSHOT

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/20942#issuecomment-930561289_

**Comment by wezell** [comment]
If we hear about issues with this, we can revisit.
