### ISSUE TITLE
CONTENT SEARCH: Card view actions not working

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21090]
**Describe the bug**
If you click any of the actions in a particular card app crash.

**To Reproduce**

https://images.zenhubusercontent.com/3729629/e5c6e9c5-f64c-4654-98b1-3ac8688ab6c7/kapture_2021_09_29_at_09_57_42.mp4

**Expected behavior**
No crash

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker
