### ISSUE TITLE
[Static Publishing] : All binary files should be added by dependency when pushing content

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21095]
Related to Support ticket: [105289](https://dotcms.zendesk.com/agent/tickets/105289)
Reproducible in dotCMS 5.3.8.5, 5.3.8.6, up to latest master (21.09)

When static pushing contents or HTML Pages to an S3 bucket, dotCMS should be able to scan the generated HTML code and include any images or files which are referenced in the content itself, even if they aren't referenced in the actual source code of the page.

**To Reproduce**
1. Create a Content Type with its respective URL Map detail page, and all the required information.
2. For the specific Mapped Content, add a **Text** field and an **Image** field.
3. In the Velocity code that renders the information of the mapped content, just display the text field.
4. Push that piece of content to an S3 bucket.

**Expected behavior**
The file referenced in the **Image** field should have been added to the bundle as a dependency.

**Additional context**
Customers are having problems with this process as it is because they have to (1) push the HTML Pages or contents they need, and then (2) push the binary files separately, which might include unnecessary files.

**Comment by wezell** [comment]
Is this a file asset or a dotAsset?  If it is a dotAsset, what should be pushed where?  If the image is referenced on the page anywhere on the page in a `src=/images/path/image.jpg` attribute, the image should be pushed.  If this is not the case, we have an issue.

**Comment by wezell** [comment]
What we could do is a generic "FolderPatternBundler" that we can set a config variable that would would specify folders to scan for and then push what is referenced in them.

**Comment by wezell** [comment]
If you reference the image using the `/dA` pathing, it will push as expected.
