### ISSUE TITLE
Past Time Machine not working

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#21097]
Steps to reproduce: 

* Go to Time Machine portlet and set a Time machine run for Demo host and English
* After finished select the newly created snapshot 

You will get the following screen: 

![image.png](https://images.zenhubusercontent.com/56e984726caf56c9d38dd540/a3e9920e-9cd4-43fb-8bd4-d90d13915f69)

Reproduced on demo / 21.09 and 21.10-snapshot

**Comment by victoralfaro-dotcms** [comment]
Snapshot is loaded correctly:
![image](https://user-images.githubusercontent.com/64026161/136116302-d11dcedc-49f0-476e-a442-cd6ca138f900.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.10 // Docker and now we are able to open the snapshot without problems

**Comment by ian-b-cooper** [comment]
Quality control tested by Non-Dev. Fix confirmed
