### ISSUE TITLE
QA Redis PubSub and Cache

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21100]
From: #18149 
We need to do internal QA on redis

- Clustering up and down - 5 nodes 
- Importing 10000 pieces of content in a at least a 2 node cluster
- Cache surviving a server restart
- Two totally different instances - e.g. auth/prod can use the same redis both for cache and pub/sub

We can allocate AWS resources for this

See the devwiki 

https://auth.dotcms.com/devwiki/redis

**Comment by wezell** [comment]
Turn on Redis Pubsub

```
DOT_PUBSUB_PROVIDER_OVERRIDE=com.dotcms.dotpubsub.RedisPubSubImpl

```
Turn on the Redis Cache Chain
```
cache.default.chain=com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotcms.cache.lettuce.RedisCache
```

**Comment by bryanboza** [comment]
@nollymar can you provide me the steps or how to test, or a quick guide to set the required property on the docker-compose file.

**Comment by wezell** [comment]
Run a cluster with Redis and set these env variables in your docker-compose

```
DOT_DOT_PUBSUB_PROVIDER_OVERRIDE=com.dotcms.dotpubsub.RedisGroupsPubSubImpl
DOT_CACHE_DEFAULT_CHAIN=com.dotmarketing.business.cache.provider.caffine.CaffineCache,com.dotcms.cache.lettuce.RedisCache
```

**Comment by nollymar** [comment]
@bryanboza in the docker-compose-examples you can find the steps: https://github.com/dotCMS/core/tree/master/docker/docker-compose-examples/dotcms-redis

**Comment by nollymar** [comment]
**Test updates:** Using an AWS instance, I was able to deploy a cluster with 4 nodes successfully, however, when I deployed the 5th node, all the nodes got unresponsive. My ssh connection got stuck also. Might it be a resource allocation issue?

**Comment by wezell** [comment]
Please take screenshot of the cache stats page.

**Comment by nollymar** [comment]
**Test updates:** 
- Using an AWS instance with more memory (14GB available) I was able to deploy a cluster with 5 nodes successfully.
- I imported a csv file with ~15.5k pieces of Rich Text content without any issue in a 2-node cluster. It took 18 mins.

However, I found an odd behavior in the live/working status each time I created a piece of content and it seems to be related to the cache state:

**Case 1:**
1. I used a 5-node cluster but surely this error can be reproduced with less nodes.
2. I created a piece of content (FAQ) and saved it. The entry was included in the redis cache.
3. I published the same piece of content but the status icon was never updated in the Content Search view (in the same node where I had saved/published) and there was no entry for the new inode (live version) in the Redis Cache. However, in the 5th node I could see the piece of content published.
4. After flushing cache, the status icon was correct in all the nodes (green) but I had two entries in the redis cache for the same working version and none for the live one.

![Screen Shot 2021-12-08 at 4 30 11 PM](https://user-images.githubusercontent.com/8741395/145290210-3bffe75a-d7fd-4761-8e21-22268f6a9efe.png)
<img width="1151" alt="Screen Shot 2021-12-08 at 4 28 43 PM" src="https://user-images.githubusercontent.com/8741395/145290222-4e17c9ec-bbda-401d-b386-2209c0ba4526.png">

I reproduced the same error trying to create a Blog Comment. This is the video:



https://user-images.githubusercontent.com/8741395/145291236-8750771f-bd77-4838-9f00-89629abd2506.mov


<img width="1137" alt="Screen Shot 2021-12-08 at 4 18 15 PM" src="https://user-images.githubusercontent.com/8741395/145290481-4571760b-2d87-4997-b96e-08bba84a565b.png">

**Case 2:** 
I created a Blog Comment and hit Save. I couldn't find the piece of content in none of the nodes, it just disappeared after I closed the popup. In this case flushing the cache didn't work. 

The dotCMS version I used to test was `dotcms/dotcms:21.12_dd8bdb4_SNAPSHOT`

**Comment by wezell** [comment]
#needswork

**Comment by jcastro-dotcms** [comment]
Excluding ticket from dotCMS 5.3.8.7 LTS release as code doesn't exist there.

**Comment by nollymar** [comment]
**Tests updates:** I ran the test again using a 3-node cluster and everything works correctly. I was able to save/update content on each of the nodes and all these changes were reflected on each one as expected.

After that, I created two clusters (with 2 nodes each one) sharing the same Redis server. Both clusters behave correctly. I'm attaching some screenshots with more details: 
<img width="1677" alt="Screen Shot 2021-12-13 at 12 59 36 PM" src="https://user-images.githubusercontent.com/8741395/145885238-bf7c2a7c-13c4-456c-83c1-5a886d327bcd.png">

![Screen Shot 2021-12-13 at 1 00 22 PM](https://user-images.githubusercontent.com/8741395/145885267-9f511cc8-1535-4396-add8-c7668d706fe5.png)
<img width="731" alt="Screen Shot 2021-12-13 at 1 01 14 PM" src="https://user-images.githubusercontent.com/8741395/145885317-6b6ecf14-39fa-4749-84d1-148438be4246.png">

![Screen Shot 2021-12-13 at 1 09 34 PM](https://user-images.githubusercontent.com/8741395/145885399-c11128ee-547c-4c03-a4e3-fe5dcf33c3c2.png)

![Screen Shot 2021-12-13 at 1 08 17 PM](https://user-images.githubusercontent.com/8741395/145885386-b89007a3-fed3-40a6-9a2d-047f28876ac5.png)
