### ISSUE TITLE
We are not saving the IP in the last login variable when you are using SAML

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21109]
In the user information we save the last login date that is composed by the `date@IP` but we have a little difference when you are using SAML, this because we save just the date and not the IP address. 

Here with the normal login: 
![image](https://user-images.githubusercontent.com/2641437/136054800-3dedfab3-c1dc-4412-9c10-677b0ad05958.png)

Here with SAML: 
![image](https://user-images.githubusercontent.com/2641437/136054913-5d94c09d-8ce8-45ef-b8c9-3461fa36d35f.png)

**Expected behavior**
We need save the complete date and IP address in both scenarios 

**Desktop (please complete the following information):**
Tested on release-21.10 // docker // FF

**Comment by jdotcms** [comment]
Not it is showing the PR

**Comment by bryanboza** [comment]
Fixed, now we have this info when you login using SAML... Tested on release 21.12 // Docker // FF
