### ISSUE TITLE
Unable to edit events 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21113]
When you try to edit an event, we are getting an error in the JS console and we are unable to edit. We just display a empty modal and never loads the data 
![image](https://user-images.githubusercontent.com/2641437/136075951-94d15ea8-92c0-4d85-845e-97752146bd1d.png)

**To Reproduce**
- Login as admin
- Go to Content --> Events 
- Try to edit any event 
- Check your console

**Expected behavior**
We need be able to edit any event without problems 

**Desktop (please complete the following information):**
Tested on release -21.10 // Docker

**Comment by nollymar** [comment]
This error seems to be related to the time zone change: https://github.com/dotCMS/core/issues/20899
