### ISSUE TITLE
Unable to start an instance using oracle as DB

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21119]
If you use Oracle as DB we are unable to start the instance this because we are getting an error in the company table. 

Here the log: 
https://gist.github.com/bryanboza/50e3c379d51ef064a1ebd0c99a320c03

**Expected behavior**
We need be able to start with any of the supported data bases without problems 

**Desktop (please complete the following information):**
Tested on release-21.10 // Oracle 12c

**Comment by nollymar** [comment]
**Note to QA:** The upgrade process should be tested as well in Oracle
