### ISSUE TITLE
Replace What's changed with the htmldiff js library

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21122]
We need to remove daisydiff from our core code base and instead use the HTMLDiff tool in EditMode to provide the "what's changed" functionality.

The DaisyDiff libraries are old XML based libs that are out of date and will not work future forward.  They should be deleted from our dependencies.

 

**Was:**
Related to #20217

After the changes now I tested and now we are getting this error when you try to use the what's changed 
https://gist.github.com/bryanboza/b9c323d10c899b65d6941ea4ef007443

We need some work here

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/20217#issuecomment-930547770_

**Comment by wezell** [comment]
Needs retesting after the #21097

**Comment by bryanboza** [comment]
We need to move to the next release

**Comment by wezell** [comment]
Do not forget to remove the old HTMLDiff libraries and java code as part of this task.

**Comment by wezell** [comment]
remove 
```
daisydiff jar
com.dotmarketing.util.diff.*
HTMLDiffUtilProxy
```

**Comment by hmoreras** [comment]
Core Web PR: https://github.com/dotCMS/core-web/pull/1855

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF

**Comment by wezell** [comment]
@erickgonzalez @jdotcms we also need to remove the classes in our EE jar:

https://github.com/dotCMS/enterprise/blob/release-22.02/src/main/java/com/dotcms/enterprise/HTMLDiffUtil.java
https://github.com/dotCMS/enterprise/blob/release-22.02/src/main/java/com/dotcms/enterprise/HTMLDiffUtilProxy.java

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise/pull/852
