### ISSUE TITLE
Time machine looks miss-aligned when you are using the system in spanish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21120]
When you are using Spanish as language and you try to create a time machine snapshot, we have some UI problems in the time machine modal

![image](https://user-images.githubusercontent.com/2641437/136130881-daf1a6ad-4de4-4e8f-a8d6-5c389f9bc15e.png)

**To Reproduce**
- Set the Spanish as language 
- Login as admin 
- Go to time machine and try to create a past time machine snapshot 

**Expected behavior**
We need be able to create snapshots without problems

**Desktop (please complete the following information):**
Tested on release-21.10 // Docker

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21528/files

**Comment by nollymar** [comment]
**Internal QA:** With the new changes, it looks misaligned too:
![Screen Shot 2022-01-19 at 11 38 57 AM](https://user-images.githubusercontent.com/8741395/150176750-b4661f22-ca03-4dce-9dfa-63fa9fdba118.png)


Discussing with @fmontes , we suggest to arrange the buttons this way: 
“Guardar y ejecutar” | “Guardar” (1rst line)
Desactivar Trabajo (Second line)

Both lines aligned to the left considering the gray box alignment. Please reach out to us for questions.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21563/files

**Comment by nollymar** [comment]
**Internal QA updates:** Passed. It looks better now

![Screen Shot 2022-01-21 at 2 54 45 PM](https://user-images.githubusercontent.com/8741395/150591862-811e021e-442c-4ee5-8e91-b79479a015b9.png)

**Comment by bryanboza** [comment]
Fixed, not this looks better 
![image](https://user-images.githubusercontent.com/2641437/151047612-2fc5c2d9-0b4b-49a4-af45-a3a6ed1f0c76.png)

Tested on release-22.02 // Docker // FF
