### ISSUE TITLE
The system allows the creation of folders with empty title

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21129]
**Describe the bug**
It's possible to create folders with an empty or null title. Folder's title should be required, otherwise it might break navigation.

![Screen Shot 2021-10-07 at 9 33 53 AM](https://user-images.githubusercontent.com/8741395/136406559-da4bea8d-cdd8-41b6-8ca1-1404043ab029.png)

**Comment by fmontes** [comment]
@jdotcms is going to do the backend validation here.

**Comment by bryanboza** [comment]
Now, it is working as @hmoreras describe in the last comment, but If you enable the show on menu option, we are getting an error and after closer the error window we are showing a waiting modal that never finish, we need some work here. 

Attached the video how to reproduce: 

https://user-images.githubusercontent.com/2641437/178778324-ac5fd0a9-3099-4835-8580-00a651da6a62.mov

**Comment by josemejias07** [comment]
Fixed. Tested on release-22.07 // Docker // OS12.5 FF 103.0.1
