### ISSUE TITLE
Upgrade Failing b/c Task210816DeInodeRelationship (MySQL, MSSQL)

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21141]
When you try to upgrade an instance using MySQL as database, we are getting stuck in the upgrade task `Task210816DeInodeRelationship`. We are not showing errors but the process get stuck and the server never starts. 

We need to tale look why we are getting this: 
Log: 
```
16:06:23.314  INFO  startup.StartupTasksExecutor - Running Upgrade Tasks: Task210816DeInodeRelationship
16:06:23.330  INFO  db.DotConnect - Executing SET default_storage_engine=INNODB
16:06:23.330  INFO  db.DotConnect - Finished Executing SET default_storage_engine=INNODB
16:06:23.330  INFO  runonce.Task210816DeInodeRelationship - ======================================================================
16:06:23.330  INFO  runonce.Task210816DeInodeRelationship - ==> Executing upgrade script
16:06:23.330  INFO  runonce.Task210816DeInodeRelationship - ======================================================================
16:06:23.330  INFO  db.DotConnect - Executing UPDATE relationship as r SET mod_date = i.idate FROM inode i WHERE r.inode = i.inode
```  

**Expected behavior**
We need to support  upgrade from previous versions in any database 

**Desktop (please complete the following information):**
Tested on release-21.10 // MySQL-5.7

**Comment by erickgonzalez** [comment]
Tested upgrade from release-21.09 to issue-21141 (branch of release-21.11) using MySQL and MSSQL.
MySQL: https://gist.github.com/erickgonzalez/9d9142f1bff6e4216041c6f10284f0bc#file-mysql
MSSQL: https://gist.github.com/erickgonzalez/9d9142f1bff6e4216041c6f10284f0bc#file-mssql

**Comment by bryanboza** [comment]
Fixed, tested on both databases and now it works as expected, tested upgrading from the lts branch to the release branch.
