### ISSUE TITLE
[Bulk Actions] : Executing action on many contents can get timed out in cloud instances

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21154]
Found when working on Support: [105339](https://dotcms.zendesk.com/agent/tickets/105339)
Reproducible as of dotCMS 21.06.3, up to latest master (21.10)

There are several customers that have several thousands of contents of a given type. If you try to execute a given Workflow Action on all of them, the bulk action dialog will time out and the summary table with the results of the execution will not be displayed. **This problem will NOT happen locally**. For security reasons, the default timeouts for development environments are not as strict as the ones used in Cloud instances, so the official fix must be tested in there.

**To Reproduce**
Reach out to me to get more information on a data set that has large amounts of contents for a given type.
1. Go to the Content Search.
2. Select a Content Type that has, ideally, thousands of contents.
3. Select all published contents from it.
4. Create a custom Workflow Action that un-publishes/archives/deletes them. This is important so that we can make sure that dotCMS will take longer to execute all actions on the contents.
5. Run the action, and wait for about 1 minute. You'll see the `Unable to show available actions` in the section where the summary table should be displayed:

<img width="620" alt="img-5" src="https://user-images.githubusercontent.com/8779585/137163258-c58c6209-459d-43d0-bbe7-0c2fd98e486d.png">

**Expected behavior**
The bulk actions dialog should not time out as it provides extremely important information on failed contents. It needs to wait for the action to finish so that Users can deal with the failed records.

**Additional context**
We have several customers with very big data repositories. Improving the way the bulk actions dialog works is very important.

**Comment by wezell** [comment]
We should look into SSE (Server Sent Events) and send reporting on a per content success or fail.  Using SSE, let us send back the results as they come back from the API and show the progress of the contents as the bulk process is applied.

https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/sse.html

**Comment by wezell** [comment]
we need to test the example in `16.4.1. Simple SSE resource method` and change the GET to a POST.   We should hit it with curl, something like 

`curl -N -XPOST https://local.dotcms.site:8443/api/events`

and see if we get the SSEvents back

**Comment by wezell** [comment]
Here is an example of how we can write a StreamingOutput with Jersey:

https://github.com/dotCMS/core/pull/21229/files#diff-0d46b518923b30c3e2a192a3fe90fa4e336039b8683e2646aba0db4db82b73c4R114

**Comment by freddyucv** [comment]
Note to QA: Contact @dsilvam to get a big data base to test

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 and now we are refreshing the number of contents that where applied the action in real time. 

https://user-images.githubusercontent.com/2641437/152602337-d022568e-b1bd-4899-8eb3-b13e1db4ef6b.mov
