### ISSUE TITLE
Large amount of data in indexed WYSIWYG field causing issues with index

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21152]
**Describe the bug**
Reproduced on: 21.06.3, 5.3.8.6

Related Ticket: https://dotcms.zendesk.com/agent/tickets/105435

When adding an image to a WYSIWYG field it was added as a base64 binary encoded string rather than an asset. It is believed this was caused by dragging and dropping the image into the WYSIWYG field.

This isn't unique to binary data, it can be reproduced with any large amount of text.

**To Reproduce**
1. From an empty starter, Create a contentlet with a WYSIWYG field that is indexed.
2. Add a new contentlet of that type and add a massive amount of text into the WYSIWYG field
3. The new contentlet will save, but will not show up in the search portlet. 
4. Add a new contentlet, it will not show up in the search portlet.
5. Save changes to an existing contentlet then re-open it, the workflow actions on the right side will not show properly (it thinks you're looking at a previous revision)
6. Attempt to reindex, the reindex will get stuck early and not progress.

**Expected behavior**
Either it should be able to handle this data or should block the attempt to index it.

**Comment by dsilvam** [comment]
Unable to reproduce. Both @bryanboza and I tried to and couldn't. Seems to be working ok on master

**Comment by wezell** [comment]
What version of elasticsearch is everyone running?  My guess is that it is tied to our use of opendistro 1.3.0

**Comment by victoralfaro-dotcms** [comment]
Added 2.1 MB text:
![image](https://user-images.githubusercontent.com/64026161/142014201-ed17cbb1-d69b-4dba-b368-787f6e1167a2.png)

It's shown at the search portlet 
![image](https://user-images.githubusercontent.com/64026161/142014343-3c1058cd-f813-4929-afc8-df12b0113f16.png)

Could reopen it and the workflow actions are shown correctly
![image](https://user-images.githubusercontent.com/64026161/142016451-8155c0c6-c70b-41e3-a52c-75501ccf2433.png)

Reindex run:
![image](https://user-images.githubusercontent.com/64026161/142016974-975dbe20-9945-43c8-8263-c263bef3acf0.png)
