### ISSUE TITLE
Forms CSP/Security: 'unsafe-eval' is required when using dotcms forms

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#21159]
**Describe the bug**

When using dotcms forms on pages, this uses eval() on the successCallback JS string when it's time to execute. This will be prevented from executing if `'unsafe-eval'` is not enabled for sites using CSP..

**To Reproduce**
1. Create a form contentlet, doing whatever for success callback
2. Add form to a page
3. Submit form
4. Error displays

**Expected behavior**
`eval()` shouldn't be needed. Executing the success callback without `eval()` would be ideal.

**Screenshots**

![image](https://user-images.githubusercontent.com/9543257/137222148-44e9d303-bb98-48ef-a85c-672472af1621.png)

Context: https://github.com/dotCMS/core-web/blob/2e0b6195de6ee470833722ccdb074c9dfac1fd3c/libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-form/dot-form.tsx#L179

Edit: Being CSP conscious, the script tags being injected with dotcms forms should also come with a hash. As a workaround, I had to take the code generated by `content_form.vtl` so I could inject a generated nonce we are using.

![image](https://user-images.githubusercontent.com/9543257/137222839-02ba5277-82eb-48cc-aea9-66793c318a18.png)

**Comment by swicken-dotcms** [comment]
Because of the need for our forms to evaluate velocity code, eval must be called. We are leaving this issue open to see if there is another way to do this, but as it stands the current workaround is to use other forms than the dotCMS form builder forms if you require CSP headers.

**Comment by wezell** [comment]
So we need a new edit point that returns a response of type `application/javascript` that includes the callback that is defined in the contentType, e.g. something like

```javascript
application/javascript


const {idOrVar}_formSuccessCallback = new function(){

   // contentlet is an object
   // e.g. contentlet.inode, contentlet.firstName

   window.location='/contact-us/thank-you?id=' + contentlet.identifier

}

```


When we render a form on a page, we need to inject the javascript src file into the DOM, something like the script equivalent of `<script src="/api/v1/forms/formCallback/{idOrVar}"> `

**Comment by freddyucv** [comment]
Tested:

- Create a Content Type called 'type-test', with a text field called 'test'.
- Create a new container called 'test-container', and add the 'type-test' Content Type with the follow code
`<h1>$!{test}</h1>`
Also add the follow code as 'Pre Loop'
```
<script>console.log("This is a test");</script>
<style>h1 {color: red;}</style>
```
- Create a new Template called 'template-test' and add the 'test-container'
- Create a new page called 'page-test' with the 'template-test' Template and add a newly 'type-test' content and publish it.

**ContentSecurityPolicy.header equals to default-src 'self'**

- Set ContentSecurityPolicy.header to default-src 'self' in the 'dotmarketing-config.properties' file. Try to go to te 'page-test' page, The page is showed but without style and the "This is a test" message is not printed in the console, also you got three security error in the console like:

<img width="1629" alt="Screen Shot 2021-12-10 at 08 28 08" src="https://user-images.githubusercontent.com/10408015/145589641-6ab942b3-594a-4e38-b18c-1930fb907979.png">

Header value: Content-Security-Policy: default-src
Also if you see the Page source code, you don't see any nonce in the style or script blocks.

**ContentSecurityPolicy.header equals to default-src 'self';style-src {style-src nonce}**

- Set ContentSecurityPolicy.header equals to default-src 'self';style-src {style-src nonce} in the 'dotmarketing-config.properties' file. Try to go to te 'page-test' page, The page is showed  with style but the "This is a test" message is still not printed in the console, also you got only one security error in the console.
<img width="1599" alt="Screen Shot 2021-12-10 at 08 25 19" src="https://user-images.githubusercontent.com/10408015/145589220-97b12272-b50b-440f-879e-949351e61c1c.png">


Content-Security-Policy: default-src;style-src 'nonce-cHdyMU9nUDZObWNyVUIyTHhUeHU='
Also if you see the Page source code, you can see the style block with a nonce value like:

`<style nonce='cHdyMU9nUDZObWNyVUIyTHhUeHU='>`

the page has two style block.
The script block not has any nonce value.

**ContentSecurityPolicy.header equals to default-src default-src 'self';style-src {style-src nonce};script-src {script-src nonce}**

- Set ContentSecurityPolicy.header equals to default-src 'self';style-src {style-src nonce};script-src {script-src nonce} in the 'dotmarketing-config.properties' file. Try to go to te 'page-test' page, The page is showed  with style and the "This is a test" message is printed in the console, also you not got any security error in the console.

<img width="1632" alt="Screen Shot 2021-12-10 at 08 27 14" src="https://user-images.githubusercontent.com/10408015/145589493-641fc0a6-54e1-47c2-b428-8e74e09ea048.png">

Content-Security-Policy: default-src;style-src 'nonce-TlBqTk1BY0VHcjJMZVlxeGtsREY=';script-src 'nonce-TlBqTk1BY0VHcjJMZVlxeGtsREY='
Also if you see the Page source code, you can see the style and script block with a nonce value like:

`<script nonce='TlBqTk1BY0VHcjJMZVlxeGtsREY='>console.log("This is a test");</script>`

**Comment by dsilvam** [comment]
**Needs work:** 
When the property is set then we're getting a NPE when trying to open pages in edit mode. 
Stacktrace:
```
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_211]
	at java.util.Optional.<init>(Optional.java:96) ~[?:1.8.0_211]
	at java.util.Optional.of(Optional.java:108) ~[?:1.8.0_211]
	at com.dotcms.security.ContentSecurityPolicyUtil.getNonceFromCurrentRequest(ContentSecurityPolicyUtil.java:230) ~[classes/:?]
	at com.dotcms.security.ContentSecurityPolicyUtil.calculateNonceToScript(ContentSecurityPolicyUtil.java:193) ~[classes/:?]
	at com.dotcms.security.ContentSecurityPolicyUtil.lambda$static$2(ContentSecurityPolicyUtil.java:94) ~[classes/:?]
	at com.dotcms.security.ContentSecurityPolicyUtil.apply(ContentSecurityPolicyUtil.java:183) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityModeHandler.eval(VelocityModeHandler.java:108) ~[classes/:?]
```

**Comment by dsilvam** [comment]
Also form submission is not working. Throwing JS errors on the successCallback:
```
Uncaught SyntaxError: missing = in const declaration

const formSuccessCallback_897cf4a9-171a-4204-accb-c1b498c813fe = function(contentlet){console.log('123123123123123123123')};```

**Comment by freddyucv** [comment]
> * ContentSecurityPolicy.header

**Note to QA**: this just happend when you use a old form to test this feature because they has a ID like: **897cf4a9-171a-4204-accb-c1b498c813fe**, for the newly form the '-' is removed from the ID.

so it is better test this issue with a newly created form and with a form the already exist in the full stater.

**Comment by dsilvam** [comment]
Getting these: https://gist.github.com/dsilvam/2eea05272510faa20bd5712b8499db13

@freddyucv will check it out

**Comment by freddyucv** [comment]
> Getting these: https://gist.github.com/dsilvam/2eea05272510faa20bd5712b8499db13
> 
> @freddyucv will check it out

We got those error using this value:

ContentSecurityPolicy.header=script-src 'self' {script-src nonce};style-src 'self' fonts.googleapis.com {style-src nonce}

it is because something we have inline style like:

`<div style="width=400px;"></div>`

we can turn it in:

```
<style>
	class_1 {
		width=400px;
	}
</style>
<div class=“class_1”></div>
```
and it is going to work, if we are not using a form into the page that we are trying to render.
If we are using a form then, we got some more error because we have some dynamic imports, so in this case if we have to use this value:

ContentSecurityPolicy.header=script-src 'self' {script-src nonce};style-src 'unsafe-inline'

**Comment by dsilvam** [comment]
Passed Internal QA: Tested with values from above and expected results.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.-02 with the full starter and now it is working as expected.
