### ISSUE TITLE
Make background threads Daemon threads

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21161]
Many times, when stopping dotCMS, the shutdown script has to forcefully kill the java process. Potentially, this happens because many threads we run are not marked as "daemon" threads and never die.  Most of the time, when we "stop" tomcat, we end up hitting this condition. 

https://github.com/dotCMS/tomcat/blob/9.0.41-java-11/bin/catalina.sh#L564

It would be better if our background threads did not prevent tomcat from shutting down.

**Comment by victoralfaro-dotcms** [comment]
Added a command to show a message when there was no clean exit at https://github.com/dotCMS/tomcat/blob/9.0.41-java-11/bin/catalina.sh#L564. It never occurred.
