### ISSUE TITLE
Icons in Card View not matching Content Type Icons

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21162]
@alfredo-dotcms commented on [Thu Oct 14 2021](https://github.com/dotCMS/core-web/issues/1779)

Icons in Card View --> Content Search should match icons that appear on List View --> Content Search

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/cf9562b5-6039-4661-a549-783c8910eb0c)

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/8789870f-1a46-412d-b08b-ef4fd1eead25)

**Comment by nollymar** [comment]
**Internal QA:** Passed

<img width="1669" alt="Screen Shot 2022-01-11 at 6 01 10 PM" src="https://user-images.githubusercontent.com/8741395/149035056-fb5c9d72-9fca-49a3-aafc-61f83b4c1ae6.png">
<img width="1672" alt="Screen Shot 2022-01-11 at 6 00 54 PM" src="https://user-images.githubusercontent.com/8741395/149035060-88b37179-cd0b-468b-9568-283088756604.png">

**Comment by bryanboza** [comment]
Fixed, now it is matching... Tested on master // Postgres // FF
