### ISSUE TITLE
Exception trying to deploy using full starter in Oracle

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21170]
When I deploy a fresh installation using full starter I get an exception when contentlets are being imported

**Log details:** https://gist.github.com/nollymar/bc3b4bfc99a0e673eb7654022cc902d8

**Comment by fabrizzio-dotCMS** [comment]
I was able to test the exact same scenario on 21.0.6-LTS and it worked just fine.  
I successfully saved the exact same event with the whole text with no problem. 
Looks like a combination of our driver + java 11 triggers the error.

**Comment by wezell** [comment]
Oracle support is being removed.  21.06 is the last LTS version that will support Oracle.
