### ISSUE TITLE
[Content Import] : Adding improvements to Content Import tool

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21177]
Found when working on Support ticket: [105339](https://dotcms.zendesk.com/agent/tickets/105339)
Reproducible as of dotCMS 21.06.3, up to latest master (21.10)

Using the specific customer dataset, we found some errors and points of improvement related to importing high amounts of records via CSV files. **IMPORTANT: These improvements are not meant to replace the expected major refactoring/improvement on the Content Import feature as a whole. They address specific situations found when troubleshooting an error reported by the customer.**

**To Reproduce**
Please reach out to me so that you can get an example of a dataset, and the CSV file that can be used for testing.

**Expected behavior**
Avoid excessive non-useful logging when both previewing and importing contents via CSV file.

**Additional context**
Increased memory settings can greatly improve the content preview and import times.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
