### ISSUE TITLE
SPA: Dropping contentlet in the same position lose contentlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21187]
If you drop the content in the same position, we are not reloading de page.

https://user-images.githubusercontent.com/72418962/137985172-5b180ae6-d482-4df0-9104-418c3515d7fb.mov

_Originally posted by @rjvelazco in https://github.com/dotCMS/core/issues/21164#issuecomment-947081538_

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12 // Docker // FF and now I'm unable to reproduce the problem.
