### ISSUE TITLE
Device Dropdown in Preview Mode Doesn't Sort and Limits 10 Devices

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21195]
**Describe the bug**
We create device previews via a dotCMS supported content type `device`. There is no limit to how many you contentlets you can create, however when in preview mode there is a limit of 10 device types shown regardless of how many contentlets of this type exist. There is also no way to sort alphabetically, and it is limited to a last modified date sort. 

**To Reproduce**
1. Go to 'demo.dotcms.com'
2. Create 12 `device` contentlets and publish them
3. Go to any page in preview mode
4. See only 10 device types instead of the full 12 and not be able to sort them

**Expected behavior**
Regardless of how many device types are created, all should be able to be accessed and previewed within preview mode. Due to the large number of devices customers may have, there should also be an option to sort via alphabetical order, rather than the default last modified date for ease of use. 

**Screenshots**

![Screen Shot 2021-10-25 at 7 24 34 AM](https://user-images.githubusercontent.com/90852779/138713896-8ea982bd-f40c-4677-a102-6a2ba14b7ea8.png)
![Screen Shot 2021-10-25 at 7 29 48 AM](https://user-images.githubusercontent.com/90852779/138714865-c94b0e1a-e283-4abc-a1e8-3ec65a2092e2.png)
![Screen Shot 2021-10-25 at 7 25 42 AM](https://user-images.githubusercontent.com/90852779/138714129-bc48d70b-e806-4596-a3da-016918c8dbd3.png)
1ce9b0e4.png)

(Note the `Tablet Portrait` and `Tablet Landscape` are not present due to the limit

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Versions: All

**Additional context**
Support requested: https://dotcms.zendesk.com/agent/tickets/105550

**Comment by wezell** [comment]
We should show up to 40 devices by default and sort them `title asc`

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1828/files

**Comment by nollymar** [comment]
**PR core-web:** https://github.com/dotCMS/core-web/pull/1828

**Comment by nollymar** [comment]
**Internal QA:** Passed.

I was able to list up to 40 devices in the dropdown list. All of them sorted by title asc

**Comment by bryanboza** [comment]
Fixed, we are able to list more that 50 devices in a drop down here. tested on master // Postgres // FF 
![image](https://user-images.githubusercontent.com/2641437/149230783-34b5c068-3e69-49d2-990c-30f5e2e0bf78.png)
