### ISSUE TITLE
200 redirects to external links are not rendering properly

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21198]
**Describe the bug**
200 redirects to external links are not rendering properly. This is because we are now sending the header `x-content-type-options: nosniff` and no `content-type` header is being set by the vanityurl forward method (which is really like a proxy if you use an absolute url).

We need to return the content type header that is returned from the proxied result.

Reproduced on: 5.3.8.6.1 and 21.10

**To Reproduce**
1. Create a Vanity URL that does a 200 redirect to https://www.google.com
2. Attempt to go to that Vanity URL, you will see the source for google printed out.

**Expected behavior**
The page being directed to should render properly

**Additional context**
Internal links to dotCMS pages work as long as you use the relative path and not the full URL.

**Comment by wezell** [comment]
Let's save the headers from the response in an map in the `CircuitBreakerUrl` class

**Comment by freddyucv** [comment]
> Let's save the headers from the response in an map in the `CircuitBreakerUrl` class

done

**Comment by dsilvam** [comment]
Passed Internal QA: properly redirecting now.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12 and now it is redirecting as expected
