### ISSUE TITLE
[Content Types] : Title property is displaying incorrectly when given variable names are present

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21199]
Reported via Support: [105480](https://dotcms.zendesk.com/agent/tickets/105480)
Reproducible as of dotCMS 5.3.8.5, up to latest master (21.10)

Creating different custom **Widget** Content Types is a common practice in customer instances. Internally, dotCMS will set the value of the `Title` equal to the `Widget Title` field. However, if you have another field named `Title Size`, the system is grabbing this new field as the value for the `Title` field, which is incorrect.

**To Reproduce**
1. Create a new **Widget** Content Type, named `Test Widget CT`.
2. Create a new content of type `Test Widget CT`, with title `My Test Content`.
3. Change the value of the **Type** dropdown to `All`. You'll see that the `Title` column is correctly displaying `My Test Content`
4. Now, go back to the `Test Widget CT` definition, and add a new **Select** field named `Title Size` with the following values:
```
Small|1.8em
Large|3em
```
5. Create another content of type `Test Widget CT`, with title `My Second Test`. Leave the default value for the `Title Size` field.
6. You'll see that the `Title` column is NOT displaying the expected `My Second Test` title. It's displaying `1.8em` 

**Expected behavior**
The official contentlet's title must be the Widget's title.

**Additional context**
This is causing problems to the customer because dotCMS uses the `title` property when adding contents to a page. Given that most of their contents have the exact same value: `1.8em` , adding them to the page is very difficult.

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)
