### ISSUE TITLE
Problems importing a whole site if the theme does not exist 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21203]
If you have a custom site and try to import from a bundle into your local instance, we are getting errors regarding the theme validation, and we are unable to import the site. 

According to the discussions seems we need to: 

`
We are going to either need to turn off the "theme validation" when importing or run passed through the list of contents to import /application/containers, then /application/templates , then /application/themes before we import any pages.  Or maybe we just import fileAssets before we import any other contentlets
`

This to avoid this kind of problems and be able to import those bundles without problems 

Here the log: https://gist.githubusercontent.com/bryanboza/d9e30cdbf70e4278b0eda0df48cd0a22/raw/e6bf97329998a8ae7235c019a63e75514c3f9b7d/gistfile1.txt

**To Reproduce**
- Login ad admin
- Setup your license 
- Ask for the custom bundle to @DeanGonzalez or me 
- Try to import it 

**Expected behavior**
We need be able to import the whole site without problems 

**Desktop (please complete the following information):**
Tested on release-21.11 // Docker // Postgres

**Comment by freddyucv** [comment]
it is fix with https://github.com/dotCMS/core/issues/21257
