### ISSUE TITLE
Relatable Content Disappears After Sorting

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21215]
**Describe the bug**
As reported in Zendesk: [https://dotcms.zendesk.com/agent/tickets/105544](https://dotcms.zendesk.com/agent/tickets/105544)

When setting up a relation via the relate button (in the parent element), a window opens in which the contentlets that can be related can be selected. If you click on "title" to change the sorting, all contentlets disappear and a selection is only possible by reopening the parent element in the edit view

**To Reproduce**
1. Go to demo.dotcms.com
2. Click into to any "blog" contentlet from the content search portlet
3. Click "relate"
4. Click any available filter
5. All available related content disappears

**Expected behavior**
Related content would sort as expected from the selected filter

**Screenshots**

![Screen Shot 2021-11-01 at 8 14 33 AM](https://user-images.githubusercontent.com/90852779/139694926-3a9715d3-5008-4fd0-acfc-1b2c0fff34a3.png)

![Screen Shot 2021-11-01 at 8 14 57 AM](https://user-images.githubusercontent.com/90852779/139695035-152c8112-480b-4f3b-bc52-a28435db3617.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 5.3.8, 21.06.3-LTS, 21.10

**Comment by jdotcms** [comment]
The issue is that these kind of custom fields are being indexed such as 
```
{contentTypevar}.{fieldVariable}
````
for instance
```
BlogAuthor.firstName
```

And the client side is just sending firstName, as soon as they send the content type var + first Name, the sort will be ok

**Comment by erickgonzalez** [comment]
Working as it should, now able to sort by any filter and the content shows up.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
