### ISSUE TITLE
Create UI to let Dot Palette show contentlets based on Content Type selected

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21211]
As a user I want that based on a Content Type selected on the Dot Palette, to show the contentlets available. Then if a contentlet is dragged, it must be added to the page

Mocks:
https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=1701%3A17524

**Comment by alfredo-dotcms** [comment]
Core-web Branch: `issue-21211-create-palette-to-show-contentlets`
Mock: https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=386%3A736

**Comment by nollymar** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1794

**Comment by fabrizzio-dotCMS** [comment]
I couldn't break it. I'm passing it

Tried the following scenarios:

- Created a brand new Content-type. With a title and Binary. Created a brand new page with the respective template and containers to support the contents of the new content type.

- Created 194 instances of the custom CT to ensure pagination works correctly. Pagination seems to work just fine.  (Page size is 25 BTW)

- Changed the structure of the CT removed the title field and the changes are reflected consistently on the items shown in the results list. 

- Created a few items in a different language and they aren't shown. Unless I'm on a page in that particular language. Which is fine. 
 
- Compared the behavior of the filter used to search for content with the behavior of the content-search portlet and they work consistently alike. Looks like the search uses a "starts with" criteria.  It would be better if this was a "like" criteria.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
