### ISSUE TITLE
Content Search endpoint needs to support pagination

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21212]
As a user I need that the Content Search endpoint `/api/content/render/false/query/+contentType:Activity` needs to support pagination, so the UI can do the right implementation

Pagination attributes must be on the Header Response of the request and should be
![image](https://user-images.githubusercontent.com/37185433/139316353-8bb5877e-16f8-4286-a335-d81a4dd27691.png)

**_Updates:_** The pagination won't be implemented on this card. However, the endpoint was modified to retrieve these new properties:
```
__icon__: "contentIcon"
contentTypeIcon: "star"
```

**Comment by alfredo-dotcms** [comment]
The endpoint also needs to return, the following attr
```
__icon__: "contentIcon"
contentTypeIcon: "star"
```

**Comment by nollymar** [comment]
The pagination will be implemented as a service in FE. New changes in the BE to send `__icon__` and `contentTypeIcon` in the endpoint response

**Comment by nollymar** [comment]
**Note to QA:**  The ContentAPI should return `__icon__ ` and `contentTypeIcon` as part of the output.

**Comment by fabrizzio-dotCMS** [comment]
Passing internal QA. 
I was able to verify that the two new properties are always returned 
`contentTypeIcon` reflects the option of choosing when creating the content-type  
while `__icon__` always comes back as  "contentIcon" which is the icon for content entries. 
which totally makes sense for me.

**Comment by bryanboza** [comment]
Since this is a change in the endpoint we need to add some postman tests here...

**Comment by fabrizzio-dotCMS** [comment]
> Since this is a change in the endpoint we need to add some postman tests here...

postman added

**Comment by bryanboza** [comment]
Fixed, now we have the test running and working as expected. Tested on release-21.12 // Docker // FF
