### ISSUE TITLE
Site or folder field has different defaults/unexpected behaviours when the field is required vs. not

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21216]
**Describe the bug**
When the Site or Folder field of a content type that lives on System Host is set to required, the field defaults to the Site you currently have selected. When it is not required, the field defaults to system host.

Reproduced on: 21.10 and 5.3.8.6.1

Related Ticket: https://dotcms.zendesk.com/agent/tickets/105614

**To Reproduce**
1. Create 2 Content Types on System Host
2. Add Site or Folder fields to both, make one required
3. Go to a Site and try to add a contentlet of the type with the field that isn't required, it default to System Host
4. Add a contentlet of the type with the field that IS required, it will default to the Site you have selected

**Expected behavior**
This will require some discussion, but I feel it should always default to the selected site.

Also, if System Host isn't a valid selection when the field is required it should not be selectable.

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1).

**Comment by wezell** [comment]
This is expected behavior.  Setting a site field as required means that the content has to live on a host and not the system host.
