### ISSUE TITLE
Persist Contentlets as Json : Phase II

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21219]
- Complete the development for MSSQL
- Stop writing to the legacy columns and fix what that breaks (
- Delete field process
  - If a field is deleted, do not delete/modify existing json values
  - On hydration, just ignore any json property that does not map to a field
  - If a deleted field is re-added, and the data type is invalid we should try to parse/convert the value to the new data type
  - Remove `ContentletFactory.DBSearch` method

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/21730

**Comment by erickgonzalez** [comment]
Only applies to 22.03 LTS.
