### ISSUE TITLE
Radio Button Field Transforms Values on Export

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21223]
**Describe the bug**
As found within a customer ticket: [https://dotcms.zendesk.com/agent/tickets/105572](https://dotcms.zendesk.com/agent/tickets/105572 )

When using the radio button field for "True/False" data types, exported values are transformed to `TRUE` or `FALSE` regardless of what is placed within the value field, then unable to be imported with those transformed values due to them throwing an error. 

**To Reproduce**
1. Go to demo.dotcms.com
2. Create a content type that only contains a radio field
3. select the "True/False" data type
4. Input line 1 as `Yes|1` and line 2 as `No|0`
5. Create two contentlets of this type, one for `Yes` and one for `No` 
6. Export those contentlets and see they have been transformed to `TRUE` and `FALSE` 
7. Delete original two contentlets
8. Try to import unaltered csv
9. See error

**Expected behavior**
Values set for the "True/False" data types should be respected on export and not transformed to a non-compatible state

**Screenshots**

![Screen Shot 2021-11-03 at 8 36 09 AM](https://user-images.githubusercontent.com/90852779/140092536-2f5fca23-9f04-467a-8ad2-8994fbb65b8a.png)
![Screen Shot 2021-11-03 at 8 37 32 AM](https://user-images.githubusercontent.com/90852779/140092780-b9715fca-85e3-4926-b8c5-042352b8e810.png)
![Screen Shot 2021-11-03 at 8 38 38 AM](https://user-images.githubusercontent.com/90852779/140093014-96345496-bc7f-4204-b0e6-5237f869924a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1
 - Browser: Chrome
 - Versions: 21.10, 5.3.8.5

**Comment by wezell** [comment]
When importing content, we should do more work to parse the correct data format, e.g. if we are storing as a boolean, we should accept values like 1, t, TRUE, or truE as `true` and 0,f,FALSE,falsE as false

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF. New enhancement created here: #21614
