### ISSUE TITLE
Improve upload temp files API

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#21225]
**Is your feature request related to a problem? Please describe.**
Currently, the temp API fails if just one of many binaries is not successful. Make it more efficient and resilient

**Describe the solution you'd like**
Should upload as many binaries as could and if some of them fail just return an error message but do not break the whole transaction.

**Additional context**
We need to make sure we return clear error messages when it fails as well.

**Comment by erickgonzalez** [comment]
**Note To QA**

To test, try to upload several files using the tempResource, and one with a fail scenario, all others should upload successfully. Previously, it failed all b/c one failed.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12 // Docker // FF
