### ISSUE TITLE
Losing changes in edit contentlet when lock/unlock

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21239]
**Describe the bug**
When the user edits a contentlet and does lock/unlock the pages refresh and the changes are lost

**To Reproduce**
We don't have a STR right now, we need to try find one, look at the "Additional context"

**Expected behavior**
Changes should not be lost at any time and not warning while editing.

**Additional context**
@john-thomas-dotcms :
> Newer versions of the content editing screen have a change in behavior which is not good.  Although I can't reproduce it consistently, it's caused me to lose quite a bit of work already, so want to bring it up here.
In earlier versions, if you edited something in the content editing screen without locking the content first, and then you locked the content, you would keep your work (so you could then change it).  But now, most of the time, if I make changes and then later hit the button to lock the content, it wipes out my changes when the lock is applied.  There is no warning asking me if I'm sure I want to lose my changes or anything like that - it just wipes them out.

@wezell 
>  I believe it is a particular workflow action combined with the locked/unlocked state of the content

**Comment by john-thomas-dotcms** [comment]
Steps to reproduce:

**Comment by john-thomas-dotcms** [comment]
Steps to reproduce:

On auth:
1. Find a content of the Documentation content type which is unlocked and in the Editing step.
2. Open that content in the content editor (but do not lock the content).
3. Click the "Documentation" tab, and make changes to the "Documentation" field.
4. Execute the "Lock and Edit" Workflow action.
**Result:** The screen immediately blanks, the browser waits for a response from the server, and then the content editing screen is reset (back to the "Content" tab), and changes to the "Documentation" field have been wiped out.

Note:
* There is no warning or prompt about losing changes - they're just wiped out.
* In prior versions, when you took this action (which has not changed):
    * The content editing screen was not reset, and
    * Changes to the "Documentation" field were not wiped out.

**Comment by fabrizzio-dotCMS** [comment]
I was able to recreate the same conditions that we have (in auth and prod) that cause losing content when locking the content. 

1. Create a Workflow let's say "Lock and Edit Workflow" that has one single action that we're gonna name "Lock and Edit" linked to an Actionlet "Lock Content"
2. Create a Content-type that has one single text area element and link the CT to the System-Workflow and the recently created "Lock and Edit Workflow".  
3. Now create an instance of the CT. We need to System Workflow here to be able to save the content in the first place. Once created it can be removed leaving the CT with only  "Lock and Edit Workflow" for simplicity.

The "Lock Content" Actionlet is internally linked to the class `com.dotmarketing.portlets.workflows.actionlet.CheckoutContentActionlet`
Which internally only locks the content. No save is performed. 

![Screen Shot 2022-01-04 at 09 44 08](https://user-images.githubusercontent.com/37148755/148085322-ebf98f4a-6aff-4bbb-bdc6-6e801d9089de.png)


It should look something like this:

![Screen Shot 2022-01-04 at 09 42 07](https://user-images.githubusercontent.com/37148755/148084599-a982086f-c88e-4b9a-be28-0dc64a43f742.png)

**Notice that there are two actions shown "Lock for Editing" and "Lock and Edit"** 

Apparently, they both accomplish the same. But there are a few subtle differences.

The first one  "Lock for Editing" is exclusively linked to a an ajax callback in the front-end 
`<a onclick="makeEditable('d4bf10c2-d112-4d0a-80d6-5233b1142669');" id="lockContentButton">Lock for Editing</a>`

The second one "Lock and Edit" is executed via workflows.
`<a style="" class="schemeId42cc0a2d-f544-441d-822a-dec8439070e2 schemeActionsDiv" onclick="contentAdmin.executeWfAction('90fe677b-5a73-44b8-8d23-393f8f7efaca', false)">Lock and Edit</a>
`
The fact that there are two ways to accomplish the same (through those actions) makes me think that has kept the problem "hidden". I believe this is an old issue. 

As the second one gets executed via workflow.  There's a custom event that gets fired at the end that forces the reload and makes the unsaved changes get lost. 

I can not simply disconnect the custom event. As the Action can be linked to more than one Sub-Action  "Actionlet".
I am open to suggestions here @wezell @jdotcms @john-thomas-dotcms

**Comment by wezell** [comment]
@john-thomas-dotcms I am pretty sure that this behavior has not changed (meaning it has been like this for awhile).  I think what is happening now is that more of the content we are editing has been left in a state (maybe the previous documentation writer left content in a different state than others? Or the workflow subaction changed?) that forces the "refresh" of the loaded content when that action is executed, which causes your changes to be lost.  We can get it fixed but I am pretty sure it is not new behavior.

**Comment by fabrizzio-dotCMS** [comment]
Apparently @john-thomas-dotcms There was a change introduced when the new move action was created that was causing the reload dialog  behavior.  New pull requests with a fix are waiting to be merged so this can be tested.

**Comment by nollymar** [comment]
**Additional PR on core-web:** https://github.com/dotCMS/core-web/pull/1830

**Comment by nollymar** [comment]
**Internal QA:** With the fix applied, changes aren't lost when the "Lock and Edit" button is hit. However, a message that says "Content Saved" is displayed. This message is shown also when "Unlock / Discard Changes" button is clicked. As this behavior is not consequence of the current changes, the internal QA passed.


https://user-images.githubusercontent.com/8741395/148435909-950cff00-e316-4d35-8204-17e9a14f6e95.mov

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12. // Docker // FF and now it is working better after the changes.
