### ISSUE TITLE
[Permissions] : Content and Content Type getting incorrect parent permissionable

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21246]
Reported via Support Ticket: [105645](https://dotcms.zendesk.com/agent/tickets/105645)
Reproducible as of dotCMS 5.3.8.6, 5.3.8.6.1, up to latest master (21.10)

When you create a Site, and then create a Content Type that points to it right after that, the **Parent Permissionable** of such a type displayed in the **Permissions** tab shows as `System Host`. This is not correct.

When you create a piece of content using the previously created Content Type, this contentlet will display the incorrect `System Host` parent permissionable as well. However, in most cases, when you access the Content API to get its JSON representation, the `host` attribute IS displaying the Identifier of the expected Site, and not `SYSTEM_HOST`.

Here's a demonstration video:

https://user-images.githubusercontent.com/8779585/140574067-b79ece17-4ef3-4701-b88f-c4548d1a2e88.mov

**To Reproduce**
1. Create a new Site named `mytestsite.com`.
2. Create a new Content Type named `My CT`, and set the **Site or Folder** field to point to `mytestsite.com`.
3. Check the **Permissions** tab on `My CT`. You'll see that the Parent Permissionable is pointing to `System Host`.
4. If you create a content of type `My CT` and check its permissions, you'll see that the Parent Permissionable is pointing to `System Host` as well. And, in most cases, if you access this content by clicking the `json` link in the **History** tab, you'll see that the `host` attribute is actually pointing to the Identifier of the `mytest.com` Site.

**Expected behavior**
The Content Type must point to the Site that was selected when it was created since the beginning.

**Additional context**
In several cases, after waiting for one or two hours, the Content Type and all the contents of such a type would start showing the right Site as the **Parent Permissionable**. We have not been able to figure out how or what would cause dotCMS to "fix itself".

**Comment by wezell** [comment]
@jcastro-dotcms Screenshots/screencap please

**Comment by jcastro-dotcms** [comment]
@wezell sure! A screencap has been added to the ticket's description.

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.12)
