### ISSUE TITLE
Static Push Publishing multilingual content - only one language version is pushed to both language folders

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#21255]
As reported in: https://dotcms.zendesk.com/agent/tickets/105619
Recreated in v5.3.8.6

**To Reproduce**
1. Create S3 bucket with `aws_bucket_folder_prefix={hostname}/{languageIso}`
2. Create new page with at least 2 language versions
3. Push Publish page contentlet via Content->Search using default push action (not workflow).
4. Only one language version is pushed to both places.
5. Push Publishing reports 'Success' regardless of outcome

Additionally, the push occasionally creates the language folder incorrectly (e.g. 'id-id' instead of 'fr-fr')

**Screenshots**

**Folder created incorrectly:**

![image](https://user-images.githubusercontent.com/49727631/140999410-d17f65ff-864f-49c5-ac04-917390bcd681.png)

**Contents of both folders is the same field instead of different language versions:**

![image](https://user-images.githubusercontent.com/49727631/140999514-18edea57-ebb9-4ba8-801e-ed6f916006aa.png)

![image](https://user-images.githubusercontent.com/49727631/140999543-c62e9561-e22f-4885-b6e0-5edee2361cf2.png)

**Comment by wezell** [comment]
This is fixed in the latest LTS
