### ISSUE TITLE
Avoid orphans Anonymous Template

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#21257]
**Describe the bug**

When we update a page's layout directly in the edit page portlet a  Anonymous Template is created to this page
A Anonymous Template is a template with a One to One relationship with a page, these templates are not list in the template listing, so a user can delete it manually.
Right now when a page with a Anonymous Template is deleted the Template is not deleted so we are having orphans Anonymous Template, also when a Layout page is changed and this page has a Anonymous Template a new Template 's version is created, I think we don't need to create a new template version in this case, we just should override the old template.

Right now we have 85 Anonymous Template (or version) in the full starter and just 23 are been using in any page.

I used the follow SQL query to get the before data:

<code>select count(*) from template where title LIKE 'anonymous_%'</code>
<code>select count(*) from contentlet where text5 in (select identifier from template where title LIKE 'anonymous_%')</code>

**To Reproduce**
1. Create a new Designer Template
2. Create a new Page using the template created before.
3. Go to 'Site Browser' portlet and open the page.
4. Go to the 'Layout' tab, you need a enterprise license for it
5. Do any change in the page's layout.
6. Check in Data base  that a new tamplete's version was created
7. Delete the page created before and check in Data Base the the Anonymous Template still exists.

**Expected behavior**
When a page is deleted and it is using an Anonymous Template we should delete the Template too automatically.
Also when a page's layout is changed and the page is using already an Anonymous Template we should not create a new template's version.
We need a Upgrade task to delete all the orphans Anonymous Template

**Comment by wezell** [comment]
Maybe we need to move away from the use of the anonymous templates and instead just store the page layout on the HTMLPage object itself.

**Comment by freddyucv** [comment]
> Maybe we need to move away from the use of the anonymous templates and instead just store the page layout on the HTMLPage object itself.

... and in the Data base? we should use a field in the contentlet table, maybe create a new field for the Page Content Type?

maybe we can just save in the field's value what we save right now into drawed_body body field in a template table
