### ISSUE TITLE
Add the ability to stop/abort a workflow on velocity script actionlet

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#21252]
Currently if an user calls

```
$workflow.abortProcessor()
```

The workflow is aborted by not stopped (which means next actionlets after the abort will continue the execution)

The idea is, if an user calls on a velocity script actionlet the abort, the workflow is aborted and stopped.

**Comment by ian-b-cooper** [comment]
Quality control tested by Non-Dev, fix confirmed
