### ISSUE TITLE
Web socket is not working

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#21266]
Also, what websocket client lib are we using?

**Comment by wezell** [comment]
fixed in #21289

**Comment by wezell** [comment]
Also, need to test #21299

**Comment by dsilvam** [comment]
Left comment on this issue #21299

**Comment by victoralfaro-dotcms** [comment]
Notifications are showed:
![image](https://user-images.githubusercontent.com/64026161/148574708-28494108-a4f3-46f2-9f5f-09062a114e09.png)

Browser console:
![image](https://user-images.githubusercontent.com/64026161/148579683-ce5641cf-fdc3-4f0a-bf38-539f9719479f.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Postgres // FF
