### ISSUE TITLE
Remove asset from a bundle is not working

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#21262]
**Describe the bug**
When you try to remove a asset from a bundle in the Bundles tab in Publishing Queue it not work

**To Reproduce**
1. Add a contentlet into a Bundle
2. Go to the Bundles tab in the Publishing Queue portlet 
3. Try to remove the contentlet from the bundle
4. The contentlet is not removed

**Expected behavior**
The contenetlet should be removed

**Comment by dsilvam** [comment]
Passed Internal QA: Content properly removed now

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF. Now we are able to remove without problems
