### ISSUE TITLE
Move System Template to WEB-INF/velocity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21265]
We need to move the System Template and System Containers to velocitie's static `WEB-INF/velocity/application` pathing.

**Comment by fmontes** [comment]
As per @wezell we need to update the starter here.

**Comment by jdotcms** [comment]
just waiting for some @jcastro-dotcms changes and starter changes

**Comment by bryanboza** [comment]
Fixed, now we are able to use pages using the system template and this one includes the system container. 

Tested on release-22.06 // Docker // FF
