### ISSUE TITLE
The 'Get Token' button on push publishing endpoint configuration does not appear until you enter endpoint configuration

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21274]
**Is your feature request related to a problem? Please describe.**
The 'Get Token' button on push publishing endpoint configuration does not appear until you enter endpoint/port information. 

This creates confusion, as the user is presented with a requested configuration variable and no indication how to obtain it.

**Describe the solution you'd like**
The button should always exist. 

It should either start greyed out (with hover text explaining why), or provide an error message when you press it prior to entering your endpoint config.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21553/files

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 // Docker // FF
