### ISSUE TITLE
Broken style when opening a VTL file in file browser

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21270]
when a VTL file is open on the file browser the VTL content style is broken on the dialog

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/b4e0c76c-8261-43b9-8c44-6810c0f6e0ed)

**Comment by alfredo-dotcms** [comment]
CORE PR: https://github.com/dotCMS/core/pull/21271/files

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me now. Passing it.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12 // Docker // FF
