### ISSUE TITLE
SiteBrowser Portlet should use DB

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21283]
This is part of a bigger issue: #21136 .

The idea here is to be able to load the SiteBrowser Portlet without indices and cache, so should be based on DB.

STR:
1- Start dotcms.
2- Navigate to Maintenance Portlet
3- Flush All Caches.
4- Deactivate both indices (live and working).
5- Navigate to Site Browser Portlet.

All content (file assets, folders and pages) should list up.

**Comment by erickgonzalez** [comment]
Note to test:

Start dotcms.
Navigate to Maintenance Portlet and deactive the indicies.
Flush All Cache
Navigate to Site Browser Portlet and folders/pages/files should be loading. (it does not mean that the pages should render without indicies).

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF 

![image](https://user-images.githubusercontent.com/2641437/149401398-35b89dfd-f4d6-46be-933e-5ae11d75d1e1.png)
