### ISSUE TITLE
Template Portlet should use DB

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21284]
This is part of a bigger issue: #21136 .

The idea here is to be able to load the Template Portlet without indices and cache, so should be based on DB.

Templates as file should load as well.

STR:
1- Start dotcms.
2- Navigate to Maintenance Portlet
3- Flush All Caches.
4- Deactivate both indices (live and working).
5- Navigate to Templates Portlet.

All templates should list up.

**Comment by erickgonzalez** [comment]
After the changes made to fix this ticket, it was also fixed the page render (just need to work on the navtool but will do it in another ticket).

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
