### ISSUE TITLE
Site selector component is not working propertly 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21299]
When you add a new site, we are not updating the site selector component, then we are unable to switch different sites, we need to update that component every time you add//remove any site 
![image](https://user-images.githubusercontent.com/2641437/143137810-a5d1fecd-547d-40c2-9038-4a6b22a5b1f1.png)

**To Reproduce**
- Login as admin 
- Create a new site 
- Make sure we are updating the site selector component and you are able to select the new site 

**Expected behavior**
We need to update the component and add the new site to the list 

**Desktop (please complete the following information):**
Tested on release-21.12 // Docker // FF

**Comment by bryanboza** [comment]
Fixed, after the fix #21266. Tested on 21.12 // Docker // FF

**Comment by dsilvam** [comment]
@bryanboza this is not working in master for me. Please retest
