### ISSUE TITLE
[SASS] : JSass library is failing to compile SCSS file

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21293]
Reported via Support: [105703](https://dotcms.zendesk.com/agent/tickets/105703)
Reproducible as of dotCMS 21.06.3, up to latest master (21.11)

We provide an option for Web Developers to compile their SASS files internally from dotCMS. However, it seems like newer versions of such files are not being compiled correctly by the third-party library we use. Under a specific scenario, this is causing dotCMS to go down without any error stack trace or warning in the `dotcms.log` file.

**To Reproduce**
Please reach out to me for the files you need to upload to reproduce the error.

**Expected behavior**
We need to use a new third-party library for compiling SASS files, or update the existing one.

**Additional context**
Both @fmontes and I looked at this issue in a screen share, and used [CodeKit](https://codekitapp.com/) to compile both the CSS files provided by the customer, and the original latest version of the SASS files in the Foundation Framework: https://github.com/foundation/foundation-sites/tree/develop/scss

We confirmed that both sets can be compiled by CodeKit without problems, just a few warnings that the customer is also aware of. However, both of them are failing to compile inside dotCMS.

**Comment by wezell** [comment]
LibSass, which jsass uses under the covers has been deprecated. You can see the remarks here 
https://sass-lang.com/libsass
and 
https://github.com/sass/libsass

While we will maintain the current functionality, I do not see an easy/secure way forward to support newer sass features.  There is a branch being worked on, slowly, of Sass 4.0 in the libsass repo but it does not appear to be be complete.

**Comment by wezell** [comment]
There are two options/workarounds for this
1. don't use newer Sass features as libsass does not and will not support them (libsass is deprecated). 
2. Compile the sass files externally and upload them into dotCMS.
