### ISSUE TITLE
We are not showing the progress bar when you are adding a new copied site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21298]
When you are adding a new site, we are just listing the site, no matter if the site is not ready jet. We need to show a progress bar as we do in previous versions and leave this unusable before the background job has ended. 

<img width="1578" alt="Screen Shot 2021-11-23 at 3 14 24 PM" src="https://user-images.githubusercontent.com/2641437/143131089-49aa64b7-09c1-44e7-93b7-ccc728e494d1.png">

**To Reproduce**
- Login as admin
- Apply the EE license to your instance 
- Try to add a new site (copy of demo)
- Make sure we are keeping the end-user updated of the process 

**Expected behavior**
We need to show a progress bar of the job that we are doing on the backhrgound 

**Desktop (please complete the following information):**
Tested on release-21.12 // Docker // FF

**Comment by alfredo-dotcms** [comment]
-Findings:
the progress bar is shown or not, based on this condition:https://github.com/dotCMS/core/blob/b5d7b3c52420824b518c9e7445453dcfdde397e6/dotCMS/src/main/webapp/html/portlet/ext/hostadmin/view_hosts_js_inc.jsp#L433

so when site list data is loaded from the endpoint `/dwr/call/plaincall/HostAjax.findHostsPaginated.dwr`, the attribute `hostInSetup` of the new site is always on `false`, so no triggering is done to start displaying the progress bar

**Comment by bryanboza** [comment]
Fixed, now we are showing the progress bar as expected. 
![image](https://user-images.githubusercontent.com/2641437/152435021-1ee11afe-09e9-4565-b818-c2c4ffa81fe0.png)

Tested on release-22.02 // Docker // FF
