### ISSUE TITLE
DnD content already in container from pallet blows up

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21297]
Like #20509 but happens when content is dragged and dropped into a container from the pallet. See below:

https://user-images.githubusercontent.com/934364/143120466-76b864ee-56b7-448a-9403-0e958609a960.mp4

**Comment by nollymar** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1806

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me now.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // Chrome
