### ISSUE TITLE
[Content] : Tool Group with no portlets causes problem with content editing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21309]
Reported via Support: [105789](https://dotcms.zendesk.com/agent/tickets/105789)
Reproducible as of dotCMS 5.3.8.6.1, up to latest master (21.11)

For unknown reasons -- specially with customers coming from very old versions of dotCMS -- there are cases in which instances have Tool Groups that have no portlets assigned to them; that is, a menu item with no links under it. This problem was solved in more recent versions, where you cannot create a Tool Group without adding at least one portlet to it.

However, when upgrading older data sets, the error displayed in the log when running into this specific situation is not descriptive at all. In the end, the continuous migration of back-end portlets to Angular will hopefully resolve this problem as well.

**To Reproduce**
Please reach out to me for more information on how to reproduce this.

**Expected behavior**
The application must provide more information on what is causing this error. For example, indicating the name of the Tool Group.

**Additional context**
The lack of a more descriptive error ended in several days for troubleshooting in order to get to the root of the problem, including having to create a cloned instance of the failing environment. The currently valid workaround is to remove the invalid Tool Group altogether.

**Comment by alfredo-dotcms** [comment]
unable to reproduce on master due to data legacy, @jcastro-dotcms was able to fix and validate that the fix worked
