### ISSUE TITLE
Require license message in the personas portlet is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21307]
We are unable to show the required license message when you are using the community edition and you try to access to the personas portlet, we are showing an error in the log and display a blank page. 

Here is the error:
https://gist.github.com/bryanboza/d94e24853d4adab7a7379982257422bf

**To Reproduce**
- Login as admin 
- Try to navigate the personas portlet 

**Expected behavior**
As in the other EE portlet when you are using the community editions and try to access them, we need to show a message about the EE is required to use. 

**Desktop (please complete the following information):**
Tested on release-21.12 // Docker // FF

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/core/pull/22189/files
https://github.com/dotCMS/core-web/pull/1977/files

**Comment by nollymar** [comment]
**Internal QA:** Passed


<img width="1670" alt="Screen Shot 2022-05-18 at 4 46 35 PM" src="https://user-images.githubusercontent.com/8741395/169161306-1c3104bf-0c8d-42c9-a908-ed6736eaa412.png">
