### ISSUE TITLE
Contentlet version comparison

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21319]
**Is your feature request related to a problem? Please describe.**
DotCMS can handle versions of components and users and bring back older versions, the problem is there is no easy way to preview and or compare the versions to make a decision on which version to bring back.

**Describe the solution you'd like**
1. Add a "Compare" button next to each version of a contentlet in the "History" tab
2. On click "Compare" we open a new popup with the compare component/

**Describe alternatives you've considered**
In the future this will be it own tab and/or maybe be part of the contentlet edit directly.

**Additional context**
This will be built as an MVP for a prospect we are working on and the due date is **December 15th.**

**APIs**

- To get all the versions of a contentlet: `/api/v1/content/versions?identifier=CONTENTLET_IDENTIFIER&groupByLang=1`
- To get the content type: `/api/v1/contenttype/id/CONTENT_TYPE_ID` (your going to need it to know what type if each field and render accordingly)

**How to render each field**
| Field                                                                                                           | Description                                                                                                                             |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| `text, textarea, checkbox, constant, keyValue, radio, select, multiselect, tag, constant, custom field, hidden` | All this needs to be compared as a string                                                                                               |
| `image`                                                                                                         | render image                                                                                                                            |
| `file`                                                                                                          | identifier as a string and add a download button with the URL  `/dA/identifier`                                                         |
| `binary`                                                                                                        | try to render as an image if fail, compare value as a string, and add a download button                                                 |
| `category`                                                                                                      | create a separated per comma string out of the value and compare it as a string                                                         |
| `date, date and time, time`                                                                                     | use the `new Date()` and then compare as a string (we need to talk about timezones here)                                                |
| `wysiwyg`                                                                                                       | we need to render the value with: https://npm.io/package/htmldiff-angular and style accordingly (we need to talk about CSS basics here) |
| `key value`                                                                                                     | let's render a line for each key/value pair and compare it as a string.                                                                 |
| `site or folder`                                                                                                | as a string, altho is only the id.                                                                                                      |
| `related content, legacy related content`                                                                       | N/A                                                                                                                                     |

**Libraries**

- https://github.com/dfoverdx/htmldiff-js: this compares HTML string and gives you back HTML with `<ins>` and `<del>` tags that we can style accordingly, maybe we can use just this one for all comparison HTML and strings. [Use example](https://stackblitz.com/edit/angular-ivy-qmolbx?file=src/app/app.component.ts)

**UI**
[Figma file](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2001%3A33242)

**Comment by fmontes** [comment]
### Technical information
API: https://demo.dotcms.com/api/v1/content/versions?identifier=2e5d54e6-7ea3-4d72-8577-b8731b206ca0

It takes the `identifier` and also `groupByLang=1`

**Comment by bryanboza** [comment]
If you add an image in the last version and publish it to a new version of the content, when you compare with the older versions we are unable to remove the image or mark in red and seems like the image always was there. We need some way yo mark the image as a difference of the previous contents. 
![image](https://user-images.githubusercontent.com/2641437/146860774-82cd0518-72fa-4734-bace-5cb3fac1ccfe.png)

**Comment by bryanboza** [comment]
Fixed, tested on the last docker image of 21.12 and now it is working as expected
