### ISSUE TITLE
Upgradation Error

### ISSUE THREAD

**Issue by arockia-probytes** [dotCMS/core#21317]
Our client is using the enterprise 3.4.2 version and We are trying to upgrade to 4+ version. While starting 4+ in server, the admin login screen is showing user-id instead of Email Address. and login also showing error.
![image](https://user-images.githubusercontent.com/55879880/143441489-9d084886-4e5e-45cf-804d-32c220d2511c.png)

**Comment by wezell** [comment]
Not the place for a support request
