### ISSUE TITLE
Relationship dialog, contentlet selections are not preserved between pages

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#21321]
**Describe the bug**

When opening a relationship dialog from a relationship field, and the list is paginated, selected contentlets between 2 or more pages are not preserved when navigating between pages. This behavior occurs on 5.3.8.6.1 and the demo site (currently 21.11).

**To Reproduce**

To reproduce on the demo site:

1. Create some copies of `Banner` contentlets to induce pagination (need >20).
1. Create a new or existing `Banner Carousel` widget.
1. Open relationship dialog for `Banners` field
1. Select a `Banner` from page one
1. Click on next button to get to second page
1. Select another `Banner` from page two
1. Click relate button

Only the latest selected contentlet from page two shows up in the list, the contentlet selected from page one does not show up in the list.

**Expected behavior**

Both selected contentlets should show up as related contentlets.

**Screenshots**
Attached a video demonstrating the problem: 

https://user-images.githubusercontent.com/9543257/143957530-a5cb4d48-30c0-4bd6-869c-738f09330609.mp4

**Comment by ian-b-cooper** [comment]
Customer has requested support as seen here: https://dotcms.zendesk.com/agent/tickets/105865

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21395/files

**Comment by fabrizzio-dotCMS** [comment]
Looks good. Passing internal QA

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
