### ISSUE TITLE
Relationship Dialog, column sort breaks result list

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#21320]
**Describe the bug**
When opening a relationship dialog from a relationship field, then sorting by a specific field, all results disappear.

**To Reproduce**

On the demo site (can also be reproduced on versions: 5.3.8.6.1 and 21.06.3)

1. Create a new contentlet or edit an existing contentlet containing a relationship field
2. Click on relate button to open the relate contentlets dialog
3. Click on a column header to sort
4. All available contentlets disappear

**Expected behavior**
Contentlets are sorted by the selected column

**Screenshots**

Attached is a video showing that clicking the column header to sort on multiple Content Types, new and existing, result in the same outcome.

https://user-images.githubusercontent.com/9543257/143939947-7260e577-0e13-4a26-901e-c7825fd509c7.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (latest), Firefox (latest)

**Comment by ian-b-cooper** [comment]
Support requested from customer as seen here: [https://dotcms.zendesk.com/agent/tickets/105863](https://dotcms.zendesk.com/agent/tickets/105863 )

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/146816235-9ccaaf28-2aaf-4df8-9f4e-54c4c944e7f7.png)

the params `Layout` and `Caption` on the payload seems to be failing on the BE, other params like `title` and `step` are working fine

**Comment by wezell** [comment]
will be fixed in #21215
