### ISSUE TITLE
Fix Gradle Daemon processing

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21339]
Newer Gradle version uses separate daemon processes for performance.   These run as separate threads with their own local path and not the original runtime path.   new File() should not be used in gradle to reference the project root but project.file() instead that will then point to the correct location.  This fix should prevent the need to disable the Daemon processing when running.

**Comment by spbolton** [comment]
https://github.com/dotCMS/core/compare/issue-20852-maven-integration-branch

https://github.com/dotCMS/core/commit/b5120315890977eae17a4f75f0f68ddea195633f

**Comment by dsilvam** [comment]
Passed Internal QA: tested by successfully running `./gradlew createDist` and verifying that the message 
`Starting a Gradle Daemon (subsequent builds will be faster)` is shown.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
