### ISSUE TITLE
Cant create pages on the release branch  I get a javascript Error 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21336]
Can't create pages on the release I get a javascript Error 

1. Go to site-browser and try to create a brand new page on any language
2. The Content-Edit Window pops up. Fill in all the required fields. Then hit save.
3. The Progres bar appears but it sits there forever. The operation never completes
4. Check the javascript console There's an error related to TinyMCE

![Screen Shot 2021-12-01 at 14 04 01](https://user-images.githubusercontent.com/37148755/144306222-07fee28e-34ff-4bad-a0f5-bdb233f3a3ce.png)

**Comment by wezell** [comment]
@fabrizzio-dotCMS looks like this: #21303.  Did it get merged cleanly, meaning, did the jsp changes make it in there?

**Comment by fabrizzio-dotCMS** [comment]
the error is triggered by this property ENABLE_GZIP in the `dotmarketing-config` if the property is included with a value of false tiny-mce loads fine. 
As long as this property exists with a value like:

`ENABLE_GZIP=false`

We're fine and since this has been validated in the docker-image and there's a fix already in master I'm closing this ticket
