### ISSUE TITLE
Fix @Nullable annotation dependency

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21340]
@Nullable annotation used by Immutables is pulling in from  org.elasticsearch.common.Nullable it should be import javax.annotation.Nullable jcr-305
Should come back to look at correct use of Nullable as jcr-305 and find bugs has been deprecated and other alternatives like checker need to be looked at.

**Comment by spbolton** [comment]
https://github.com/dotCMS/core/commit/e1d81c64f48c6ba50ec98b15fff4598f0d8f3fc6

**Comment by freddyucv** [comment]
Tested:

- Clean all the Immutable class.
- Generate Immutables again and check that they are using the 'javax.annotation.Nullable'

**Comment by dsilvam** [comment]
Passed Internal QA: after re-generating the immutables they are created with the proper annotation

**Comment by bryanboza** [comment]
Fixed, tested on master...
