### ISSUE TITLE
InodeFactory uses wrong Category class import

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21343]
InodeFactory checks class against "Categories" it is being compared against org.eclipse.persistence.internal.oxm.schema.model.Content instead of com.dotmarketing.portlets.categories.model.Category based upon the import

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/21479

**Comment by freddyucv** [comment]
I don't think really any of the updated methods are being used.

**Comment by spbolton** [comment]
@freddyucv If any code can be removed then great,  The code path is an error case that I suspect is never being called, but the org.eclipse import version of Content is definitely never going to match and causes problems when the dependency is gone.   The main issue for maven is really removing the bad org.eclipse.persistence.internal.oxm.schema.model.Content import from this class, if this is removed and the class will still work as before then that is all we need here.

**Comment by freddyucv** [comment]
> @freddyucv If any code can be removed then great, The code path is an error case that I suspect is never being called, but the org.eclipse import version of Content is definitely never going to match and causes problems when the dependency is gone. The main issue for maven is really removing the bad org.eclipse.persistence.internal.oxm.schema.model.Content import from this class, if this is removed and the class will still work as before then that is all we need here.

really this method

https://github.com/dotCMS/core/blob/f91a88bf54c8362653bc0ccd71c83189673eb438/dotCMS/src/main/java/com/dotmarketing/factories/InodeFactory.java#L2018

is being using so really we can't remove all the methods, let me check
