### ISSUE TITLE
We are unable to show the complete list of contents after upload large bundles 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21341]
When you push or import large bundles and then go to the publish queue, we are showing just a preview of the first 3 contents, but If you try to see the complete list we are unable to display it. 

https://user-images.githubusercontent.com/2641437/144469404-fe0428d3-1e84-48bc-b0af-14a9c44c46c7.mov

**To Reproduce**
1. Start a dotCMS instance
2. Import a large bundle (more than 10 pieces of content)
3. Go to publish queue 
4. Try to see the complete list of contents of the bundle 

**Expected behavior**
We need be able to display the whole list without problems 

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/2641437/144469682-b2cd7988-a6a4-48db-a207-01a1edb987f9.png)

**Desktop (please complete the following information):**
 Tested on release-21.12 // Docker // FF

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/144926490-357d8064-c7be-44d5-9dfc-988d7fdc76bb.png)

seems like the endpoint that was being used is not available anymore

**Comment by freddyucv** [comment]
This bug just happned with Imported bundle.
I mean when you create a bundle using the "Add to bundle" option and the Push publish it, it not happned

**Comment by victoralfaro-dotcms** [comment]
The code changes fix the error described in this issue.

https://user-images.githubusercontent.com/64026161/145914445-d5b5a5a2-59d6-4ee9-b196-f39044b2eaac.mov

However, when clicking on the `Manifest` results in the behavior @alfredo-dotcms is describing: a 404. 

https://user-images.githubusercontent.com/64026161/145914527-78cd3eda-f2c2-4a63-ba0d-d9870cbbfc3a.mov

I don't think this is related at all.

**Comment by bryanboza** [comment]
Fixed, the main error was fixed after those changes, new card related here #21420
