### ISSUE TITLE
Upgrade to ElasticSearch client 7.10.2

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21344]
7.10.2 is latest version with apache license.   After this we will need to move to opensearch client.    This change requires changes from both branches  'elasticsearch-7-10-2' of enterprise and core

**Comment by spbolton** [comment]
https://github.com/dotCMS/core/commit/8a862462000f55a4304a58dfe435f180bb022110

**Comment by dsilvam** [comment]
EE PR: https://github.com/dotCMS/enterprise/pull/849

**Comment by dsilvam** [comment]
Passing QA based on the tests results
