### ISSUE TITLE
Minor Improvements to Pallet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21357]
Two things:

1. the search box text is too small.  It should be the same or almost the same as the content search screen, e.g.
![Screen Shot 2021-12-03 at 11 58 15 AM](https://user-images.githubusercontent.com/934364/144642173-f3ac4c63-e756-4ccf-9d4e-e1fa4a3cc6e0.png)
2. When you click on the arrow to "reuse content" we should place the cursor into the search box to prevent a user from always having to click into it.  Or maybe just when the pallet is shown, the cursor is automatically put there
3. The content list should sort by our default sort for most everything, `mod_date desc`
4. We should show 40 contents by default

**Comment by erickgonzalez** [comment]
There is a couple of bugs:
1) Double animation when going from content types to reuse content.
2) Scroll block reuse content arrow.

**Comment by fmontes** [comment]
> 2. Scroll block reuse content arrow.

Can't make this work because this is a OSX behavior

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
