### ISSUE TITLE
Not able to add content to a page

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21359]
**Describe the bug**
With the latest master (Dec 3rd) you are not able to add content to a page using the + button or the content palette to add new one. The only way to add content is reusing content via the content palette.

**To Reproduce**
1. Create a new page.
2. Edit Mode of the page.
3. Drag **Rich Text** to a container
4. Create the content.
5. Publish Content = Should show on the page but it doesn't

Another test:
1. Create a new page.
2. Edit Mode of the page.
3. Click over the + button
4. Select any content. = Should be added to the page but only shows a loading icon.

**Expected behavior**
Be able to add content to the page successfully.

**Screenshots**
<img width="1146" alt="Screen Shot 2021-12-03 at 12 24 09 PM" src="https://user-images.githubusercontent.com/5278970/144653625-139bf215-c8a4-4fb0-acc9-45c2e877e89a.png">

**Comment by fabrizzio-dotCMS** [comment]
Since I was able to succesfully execute the steps listed above I am Passing It.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the change
