### ISSUE TITLE
Login Should work without indicies

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21360]
Right Now if you try to log in without indices it shows only a blank page and the login form returns a 500 error, nothing shows up in the log.

STR:
1. Navigate to Maintenance Portlet.
2. Deactivate both indices (working and live)
3. Flush Cache
4. In an incognito window try to log in

<img width="1662" alt="Screen Shot 2021-12-03 at 2 14 50 PM" src="https://user-images.githubusercontent.com/5278970/144667097-685a00cf-b1f8-44a3-9a20-24fd8342044a.png">

You should be able to log in successfully even if the indices are deactivated.

**Comment by bryanboza** [comment]
Fixed. tested on master // Postgres // FF
