### ISSUE TITLE
Custom bubble menu for Image block

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21369]
**Is your feature request related to a problem? Please describe.**
For Image blocks, we need a custom bubble menu.

**Describe the solution you'd like**
For now, the bubble menu should only include:

1. Links
2. Align left, center, right.

**Describe alternatives you've considered**
I'm uncertain if we have to create a new component, extension, and plugin OR just reuse what we have an hide buttons.

**Additional context**
Need to talk to @rjvelazco about development.

**Comment by rjvelazco** [comment]
The property `content` is for nested nodes [[See Prossmirror Content Expression](https://prosemirror.net/docs/guide/#schema.content_expressions) & [Tiptap Schema](https://tiptap.dev/api/schema#content)]. What we are saving in the `attrs` property is not a registered `node` in the editor's schema but is just an object.
