### ISSUE TITLE
Add a text label or on-hover tooltip for switch that (de)activates Rules

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21374]
I think adding a label to this switch would improve clarity in the Rules UI

<img width="1024" alt="Screen Shot 2021-12-06 at 12 03 18 PM" src="https://user-images.githubusercontent.com/628954/144907520-c4541070-5acb-4d34-b501-3ce0b8db098f.png">
. 

## Acceptance Criteria
Let's add an on-hover tooltip to the switch.

**Comment by swicken-dotcms** [comment]
Re-opening, this is the type of low hanging fruit that should be easy to fix and improve the customer experience a lot.

**Comment by damen-dotcms** [comment]
Hey @Melissa-dotCMS ,

Can you provide some design input here? Thanks!

**Comment by bryanboza** [comment]
After the last changes I noticed that we don't add a label, we just add a kind of hint 

![Image](https://github.com/dotCMS/core/assets/2641437/9dbf3da3-90c9-4568-981b-053f39bbb59c)

What do you think about this design @Melissa-dotCMS ?

**Comment by fmontes** [comment]
Rules portlet don't have our design system is old code with a bunch of patches, so is not easy to implement our new design system without a bigger refactor, my recommendation is just do as good as possible here.

@bryanboza the tooltip is what is was asked here in this issue.

@erickgonzalez I think the label of the tooltip should be as simple as "Enable this rule" and move on, this portlet is not a priority right now.

**Comment by bryanboza** [comment]
Fixed, as @freddyucv mentioned in the previous comment, this is what we fix here, just the label 


![Image](https://github.com/dotCMS/core/assets/2641437/95520067-9bc0-4dc4-81be-387c7f1bbad2)


Tested on master
