### ISSUE TITLE
Allow UVE apps to send a custom HTTP header(s) for Authentication

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21376]
It would be useful if the UVE app could send custom HTTP headers like `Authorization:` or `HTTP Basic Auth` with its requests, so clients need not rely on IP whitelists to secure their rendering servers.

More broadly, perhaps this could be done with some or all outbound HTTP requests.

Cloud customers have asked us for the public IPs of their cloud servers in order to restrict access to their rendering servers. These IPs change at the whim of AWS, which imposes work on both dotCMS (to provide a current list of public IPs) and on cloud customers (to update their firewalls when the IPs change).

**Comment by yolabingo** [comment]
@fmontes @wezell does this seem reasonable?

**Comment by swicken-dotcms** [comment]
Second user is now asking for this capability

**Comment by yolabingo** [comment]
Amplify provides HTTP auth. I think we should support both **Basic** and **Bearer** auth.

**Comment by erickgonzalez** [comment]
Customer ticket https://dotcms.freshdesk.com/a/tickets/28990

**Comment by rjvelazco** [comment]
@yolabingo @erickgonzalez Just to clarify, is this ticket meant for both UVE and EMA? They are two different APPS, and I believe we should keep this focused on UVE only since the client is using this APP


![dotcms-app-screenshot](https://github.com/user-attachments/assets/7361c6a8-aad6-4927-a893-b2cb1bf3bd57)

**Comment by erickgonzalez** [comment]
@rjvelazco yes let's focus on UVE.

**Comment by yolabingo** [comment]
I second "UVE only" - thanks for asking. This issue was filed in 2021 when we had only EMA and I updated the issue for UVE. We have the same problem with both EMA and UVE but no need to fix it for EMA if it is going away.

**Comment by hmoreras** [comment]
@yolabingo , the UVE loads in a iframe, we can't send HTTP headers there, but we can send query params that can be used to do a login. is the query param approach is something we would like to follow ?

**Comment by yolabingo** [comment]
Ah bummer. My feeling is that probably won't buy us much, but I know very little about this feature.

**Comment by yolabingo** [comment]
Questions:

1) When you successfully submit HTTP Basic Auth credentials, the browser stores them and sends the auth header automatically on subsequent requests. _If_ the browser sends the auth headers in an iframe, then Basic Auth can work in UVE so long as the user first visits and logs into the app site directly. I don't know if browsers do this with iframes, we should check that.

2) Can we use something like this or would it break other things?
```
<script>
    var myIFrame = document.querySelector('#myiframe');
    var myUrl = 'http://localhost:1234/api/test';
    var myHeaders = [
        ['Authorization', 'Bearer 1234567890']
    ];

    populateIFrame(myIFrame, myUrl, myHeaders);

    function populateIFrame(iframe, url, headers)
    {
    ...
```

https://gist.github.com/scottoffen/d15ca8fc8094d7267dca941a8c8731eb

**Comment by yolabingo** [comment]
Closing this. The browser does ask the user for user/pass for the UVE iframe, so UVE appears to work fine with HTTP Auth. We encountered an application issue that led us astray.
