### ISSUE TITLE
RedisPubSub with Redis Streams does not work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21389]
Our `RedisPubSubImpl` works but the `RedisGroupPubSubImpl` does not.  This is because the `xgroupCreate` was throwing an unlogged error when setting up and we were not returning the RedisConnection to the pool.

**Comment by nollymar** [comment]
**Internal QA:** Passed

Using this implementation `com.dotcms.dotpubsub.RedisStreamsPubSubImpl`, I was able to deploy a 2-node cluster successfully.
![Screen Shot 2021-12-13 at 4 01 47 PM](https://user-images.githubusercontent.com/8741395/145888330-dad2d3b2-0626-47e3-bbc9-de3121b96a75.png)

**Comment by bryanboza** [comment]
The QA of this was moved to the card #21100
