### ISSUE TITLE
Migrate existing Slack Incoming Webhooks to an app

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#21383]
Slack Webhooks are going to be deprecated. They (Slack) recommend to migrate them to Slack Apps.
Right now these are the workflows using webhooks:
- core-cicd-tests.yml
- pre-release-process.yml
- publish-docker-image-on-release.yml
- release-process.yml

We need to invest some time researching if an App could cover every notification or if do we need each for every workflow.

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21383?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms
