### ISSUE TITLE
NavTool Should work without indices

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21385]
This is part of a bigger issue: #21136 .

Since now it's able to render pages without indices (fixed in #21284) but the nav Tool wasn't working.
The nav tool should be able to list correctly even if the indices are deactivated.

STR:
1- Start dotcms.
2- Navigate to Maintenance Portlet
3- Flush All Caches.
4- Deactivate both indices (live and working).
5- In an incognito window hit the FE.

The nav tool should show up.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Postgres // FF
