### ISSUE TITLE
Make userId immutable

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21392]
Once a user object has been created/inited, you should not be able to edit the userId.

**Comment by erickgonzalez** [comment]
I tested this via BE using debug mode since there is no way at FE to change the userId.

**Comment by bryanboza** [comment]
Fixed, tested creating a template with this code: 
```
$user.setUserId("admin")
User: $user.getUserId()
```
After use it in a page, now we are getting the original userId, and now we can't override this value. 
![image](https://user-images.githubusercontent.com/2641437/147963120-8dd9120b-e44a-4e43-abb5-f08ff90f2d78.png)

Tested on release-21.12 // Docker // FF
