### ISSUE TITLE
fix password size validation annotations

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21408]

**Comment by freddyucv** [comment]
Tested, with a password with less than 6 characters and you get the follow

- Error in the dialog

<img width="360" alt="Screen Shot 2021-12-22 at 15 04 40" src="https://user-images.githubusercontent.com/10408015/147155070-fdf54ea1-2ede-4df2-bada-ca94a6ac444d.png">

- Error in the log file:

```
15:02:49.857  INFO  business.LocalSystemEventsAPIImpl -  Filtered Audience for event with key `dotGoogleTranslate-config`  is `0` long. 
15:03:08.654  WARN  exception.ValidationException - [ErrorEntity{errorCode='password', message='The password must be a string with a length of 14 and 32', fieldName='null'}]
```

For now it is printing the stack trace too

- The '/v1/apps/export' end point response with a 400 HTTP error.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/21456

**Comment by victoralfaro-dotcms** [comment]
Shorter than 14 chars:
![image](https://user-images.githubusercontent.com/64026161/148262283-88c340f2-4fc1-44ec-9477-1589fc736d42.png)
```
11:35:03.199  WARN  exception.ValidationException - [ErrorEntity{errorCode='password', message='The password must be a string with a length between 14 and 32', fieldName='null'}]
```

Longer than 32:
![image](https://user-images.githubusercontent.com/64026161/148262459-7c8982c4-b84b-451b-b6f0-efa5c1d5f9d4.png)
```
11:33:08.498  WARN  exception.ValidationException - [ErrorEntity{errorCode='password', message='The password must be a string with a length between 14 and 32', fieldName='null'}]
```

In range:
```
11:35:53.583  INFO  apps.AppsHelper - Secrets export: ExportSecretForm{ all={false} {Site SYSTEM_HOST keys: dotGoogleTranslate-config}}
11:35:53.584  INFO  apps.AppsUtil - Apps Password Override supplier has been provided.
11:35:53.618  INFO  apps.AppsAPIImpl -  exporting : AppsSecretsImportExport{`[{SYSTEM_HOST with : 1 secrets. }]`}
```

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
