### ISSUE TITLE
Host Selector Improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21417]
1. When there are a lot of sites, searching for sites is painful. We need to preprend a `*` to the front of what is typed in the site selector (if it does not already start with a `*`) to allow for wildcard searching.

https://user-images.githubusercontent.com/934364/146081241-06318494-9431-4526-95aa-39837545657d.mp4

2. We need to up the number of sites shown before we paginate - we should show at least 40 sites before we paginate.

**Comment by alfredo-dotcms** [comment]
core-web PR: https://github.com/dotCMS/core-web/pull/1820/files

**Comment by fabrizzio-dotCMS** [comment]
Testing on this is currently blocked. The site selector isn't showing all the available sites. This was already fixed on the Release branch. Will test again after the release branch has been merged into master.

**Comment by nollymar** [comment]
**Internal QA:** Passed

<img width="1671" alt="Screen Shot 2022-01-11 at 6 06 21 PM" src="https://user-images.githubusercontent.com/8741395/149035497-e5e730f7-b00f-4b91-bfe3-f325b6a9d3ce.png">

<img width="1676" alt="Screen Shot 2022-01-11 at 6 06 07 PM" src="https://user-images.githubusercontent.com/8741395/149035522-17887ca3-8b0a-49b4-aabd-6b2450d3c8d0.png">
<img width="838" alt="Screen Shot 2022-01-11 at 6 05 52 PM" src="https://user-images.githubusercontent.com/8741395/149035527-b6f62301-ff66-44f5-bae1-0c5fb8f3eeb0.png">

**Comment by wezell** [comment]
nice QA screenshots Nolly!

**Comment by bryanboza** [comment]
Fixed, tested on master and now the site selector component is working as expected.
