### ISSUE TITLE
Site Browser: Unable to open some folders  

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21419]
**Describe the bug**
An exception is thrown trying to open some folders in a receiver: https://gist.github.com/nollymar/99205cd6e86a543ed895f5656269d85f

<img width="1675" alt="Screen Shot 2021-12-15 at 10 30 45 AM" src="https://user-images.githubusercontent.com/8741395/146215621-89788433-2621-496e-9fad-00043499abc8.png">

This issue happens with a custom dataset

On the other hand, if I try to push those folders from the sender, it fails as well with a similar exception: 

```
Failed to publish because an error occurred: An error occurred when processing Contentlet in 
'/data/shared/assets/bundles/01FPZ7XAKQPNB2VRDWPXHV50WT/live/dotcms.com/1/0-d2b30470-06df-4611-be63-8a076501c133.content.xml' 
with ID 'c633f85c-57af-4c21-af02-eb54401c0242': 'Unable to populate contentlet from table columns for
 ID='c633f85c-57af-4c21-af02-eb54401c0242', Inode='a6dbd962-b5c2-4441-a022-d4be05389a02', 
Content-Type 'dba3b94b-9e42-485a-bcf9-2af8fad5ac3b': Unable to obtain property value for field 'text_area1' 
in Contentlet with ID='c633f85c-57af-4c21-af02-eb54401c0242', Inode='a6dbd962-b5c2-4441-a022-d4be05389a02',
 Content Type 'dba3b94b-9e42-485a-bcf9-2af8fad5ac3b': com.google.gson.stream.MalformedJsonException: 
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10 path $'
```

**Comment by wezell** [comment]
In fixing this issue, can we remove the GSON dependency?

**Comment by fabrizzio-dotCMS** [comment]
> 
@wezell @nollymar 
In the spirit of keeping PR smaller can We please handle this as a separate issue?

**Comment by nollymar** [comment]
**Internal QA:** I have tested in prod and it's working correctly with the fix

**Comment by bryanboza** [comment]
Fixed, tested with the provided dataset and the last version of 21.12 and now I'm able to open this folder without problems.

**Comment by nollymar** [comment]
> > 
> 
> @wezell @nollymar In the spirit of keeping PR smaller can We please handle the GSON thing as a separate issue?

I created a new issue for the GSON stuff here: #21641
