### ISSUE TITLE
Unable to move a piece of content between sites modifying the site/folder field

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21416]
if you create a new piece of content and save it, then try to modify and change the site/folder field and save again, if you edit again, we are not modifying this value.

The same case if you do that with a vanity URL when you save it works, but if you try to modify and then curl this URL, still resolving in the same site, and if you try in the new site this returns a 400 error. 

**To Reproduce**
- Setup a licensed environment
- Create a new piece of content/vanity URL
- Save it 
- Modify the piece of content and change the site/folder value to the root of another site 
- Save it 
- Now try to edit again and make sure the value was updated. 

**Expected behavior**
We need to be able to modify this value without problems 

**Desktop (please complete the following information):**
 Tested on release-21.12 // Docker // FF

**Comment by nollymar** [comment]
**Internal QA:** Passed

I was able to move pages and generic content among sites and folders successfully.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.12 // Docker // FF
