### ISSUE TITLE
Frame Resize Bug submitted on behalf of Deutsche Bank/Sunny Metkar

### ISSUE THREAD

**Issue by markmarkham** [dotCMS/core#21413]
**Describe the bug**

```On a content having "image" field, clicking on Browse button opens "Select a file " popup showing project folder structure on left pane.```

```Client reported that there is no handle to resize the left pane and they have to rely on horizontal scrollbar which shows only when expanded folders are long enough for need of scrollbar. This is not user friendly for them or consistent with other screens. ```

```dotCMS version 5.1.6```

**To Reproduce**

**Expected behavior**

```All we need is existing functionality/handle which is available on Site > Browser to expand left pane to see the long folder names easily on Image field >browse menu.```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete t
![unnamed (1)](https://user-images.githubusercontent.com/70216723/146026351-cbc82fe4-3943-4c18-b855-cbe6802d45b3.png)
he following information):**

**Additional context**

**Comment by alfredo-dotcms** [comment]
PRs:
Core: https://github.com/dotCMS/core/pull/21449
Dojo-theme: https://github.com/dotCMS/dotcms-dojo-theme/pull/84

**Comment by fabrizzio-dotCMS** [comment]
Looks Good to me. Passing internal QA

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
