### ISSUE TITLE
Find a way to add "Compare" button to Task Detail

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21414]
**Is your feature request related to a problem? Please describe.**
When users gets to the task detail page, there is no way to know what are the changes they need to review.

**Describe the solution you'd like**
We need to add the "Compare contentlet" functionality we added in History in Task Detail as well.

- label of the button should be `Compare to previous versions`
- in the compare dialog, the dropdown that contains version dates must show relative dates if changes were made before a week, otherwise show the standard datetime. Also make it 20px wider and add the author who did the change
- in the compare dialog change the DIFF/PLAIN switch button to img attached 
![image](https://user-images.githubusercontent.com/37185433/149372291-14943da4-cf42-4a11-9eb3-846afbdb5878.png)

**Additional context**
Also, let's do a little of a revamp on the comments form to show it all the time.

**Mocks**
<img width="1693" alt="Tasks" src="https://user-images.githubusercontent.com/751424/149179865-2a664114-4b6b-4183-a9bf-87bb39baa800.png">

![image](https://user-images.githubusercontent.com/37185433/149594286-80ec8a87-3f6e-49c3-bd26-974889f4057c.png)

**Comment by alfredo-dotcms** [comment]
PRs:
CORE = https://github.com/dotCMS/core/pull/21543/files
CORE-WEB = https://github.com/dotCMS/core-web/pull/1843/files

**Comment by fabrizzio-dotCMS** [comment]
I was able to validate that the date changes from relative to absolute for the desired period using my debugger I'm passing it.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 // Docker // FF
