### ISSUE TITLE
dotCDN not purging content page when page is updated

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21424]
Right now if you add the dotCDN Purge action to any step and call it from a page, it doesn't invalidate the content in it only invalidates the page.

STR:

1. Add the dotCDN plugin
2. Configure the App
3. Navigate to Workflows
4. Add the dotCDN Purge action to the Publish Step
5. Create a page
6. Create a Rich Text
7. Add the content to the page
8. Publish the page

Should invalidate the page and the content as well.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/com.dotcms.dotcdn/pull/8

**Comment by bryanboza** [comment]
Fixed, following the provided steps, now we are invalidating the page. 
Here the log of the publish step
https://gist.github.com/bryanboza/b069414c6cc738adcc64c295f31fdb0a

Tested on release-22.02 /// Docker // FF
