### ISSUE TITLE
Remove TestParser and PrettyDump legacy xml processing

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21426]
To test this, we need to make sure that the Compliance checker is working in our wysiwyg:
![Screen Shot 2021-12-15 at 3 43 37 PM](https://user-images.githubusercontent.com/934364/146262203-092c3578-d2a6-4d5c-b734-5e62782791dc.png)

**Comment by spbolton** [comment]
https://github.com/dotCMS/enterprise/compare/issue-21426-remove-unused-legacy-parsers?expand=1

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise/compare/issue-21426-Remove-TestParser-and-PrettyDump-legacy-xml-processing?expand=1

**Comment by freddyucv** [comment]
Tested:  to make sure that the Compliance checker was working right after the change, I test if the Web Content Accessibility Guidelines (WCAG) was working as expected: 

For more information about WCAG: https://www.w3.org/WAI/GL/WCAG20/tests/

Test Cases:

- 1.0 Level A
it was test with the follow html: `<img src="rex.jpg"/>`
Error thrown out: "img element missing alt attribute.( All img elements must have an alt attribute. "
HTML to fix: `<img src="rex.jpg" alt="A black and brown cat named Rex."/>`

- 1.0 Level AA

it was test with the follow html:  

```
<label>First name:</label>
<input type="text" name="firstname" tabindex="1" />

```
Error thrown out: input element, type of \"text\", missing an associated label.( input element that contains a type attribute value of \"text\" must have an associated label element. An associated label is one in which the for attribute value of the label element is the same as the id attribute value of the input element. )

HTML to fix: 

```
<label for="firstname">First name:</label>
<input type="text" name="firstname" id="firstname" tabindex="1" />
```

- 2.0 AA

it was test with the follow html:  
```
<head>
<meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
</head>
```

Error thrown out: : Document missing title element.( title element must be present in head section of document. )

HTML to fix: 
```

<head>
<meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
<title>OAC Testfile - Check #50 - Negative</title>
</head>


```

The doc said this rules is really level 3 but you get the error with level 2 in dotcms (I mean in master)

https://www.w3.org/WAI/GL/WCAG20/tests/test54.html #

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise/pull/843

**Comment by dsilvam** [comment]
Passed Internal QA: Tested following the test cases mentioned in @freddyucv 's comment

**Comment by bryanboza** [comment]
Tested with the provided examples and we are getting this: 

![image](https://user-images.githubusercontent.com/2641437/152417998-0f9e082c-49a5-4920-941b-10a6f237a018.png)

I don't know why the name of the columns are `0` and also don't know what's this  `_ERR_1( _DESC_1 )`

**Comment by dsilvam** [comment]
Passed Internal QA: Not getting what @bryanboza reported.

**Comment by bryanboza** [comment]
Ok tested after the last changes, and now we have the name of the columns, which is better that we had, but we need to work in the error descriptions because right now the descriptions are not clear and we need something more descriptive. 
![image](https://user-images.githubusercontent.com/2641437/156841641-842ba176-70a5-4ede-a2c4-c62fa3cdc22b.png)
