### ISSUE TITLE
DateUtil.prettyDateSince is off by 1 minute

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21428]
When we call the DateUtil.prettyDateSince - for example, when we are showing the last ping on the license portlet -  we are off by a minute.  This means that we show things like the last ping, it takes 2 minutes for it to register anything but "seconds ago".  It should change to "1 minute(s) ago" after 1 minute.

![Screen Shot 2021-12-16 at 10 09 41 AM](https://user-images.githubusercontent.com/934364/146397047-0f8d71e9-edb9-40e7-8175-c90389ff20a7.png)

**Comment by alfredo-dotcms** [comment]
not fixed
https://monosnap.com/file/yT6JewvuNoccnAMwZCng38N1Z76IDp

**Comment by wezell** [comment]
Good QA but that is fixed, I think.  We ping the servers every minute, so the time resets.

**Comment by erickgonzalez** [comment]
Working as it should, it refreshes every second it hits the cluster servers. But when one it's down updates every minute
<img width="1421" alt="Screen Shot 2022-01-19 at 3 16 38 PM" src="https://user-images.githubusercontent.com/5278970/150207141-1c888775-dfbf-4a0a-8f2f-ca659d06e82e.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF. Now we increment the time in seconds, but after every minute the server ping again and reset the time.
