### ISSUE TITLE
[URL Maps] : Text field as whole number referenced in URL Map is causing content to not be saved

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21434]
Reported via Support ticket: [105978](https://dotcms.zendesk.com/agent/tickets/105978)
Reproducible as of dotCMS 21.06.4, up to latest master (21.12)

`Text` fields in a Content Type can be referenced in URL Map Patterns to use the information entered by content authors and build out the expected URL. However, when the **Data Type** of such a `Text` field is set as **Whole Number**, and users try to save a piece of content of the Content Type that field belongs to, an error shows up on the Edit Modal.

**To Reproduce**
1. Create a new Content Type named `My Test CT`. **DO NOT ADD ANY URL MAP INFORMATION YET.**
2. Add a text `Title` field to it, and add another text field with the following properties/values:
2.1. Name = `ID`
2.2. Data Type = `Whole Number`
2.3. `Required` / `User Searchable` / `Show in List` / `Unique` 
3. Create a piece of content of this type with the following information:
3.1. Name = `First Entry`
3.2. ID = `1`
4. Now, go back to the edit dialog of the `My Test CT` type, and enter the following information for its URL Map:
4.1. Detail Page = `//demo.dotcms.com/blog/blog-detail`
4.2. URL Pattern = `/{id}/`
5. Open up the `First Entry` contentlet you created before, and click **Publish**.
6. You'll get the following error message in the UI:
```
class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```
The only error message in the log is:
```
[17/12/21 17:50:45:158 UTC] ERROR ajax.ContentletAjax: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```

**Expected behavior**
The URL Map should be able to use text fields with **Whole Number** data types without problems.

**Additional context**
If you follow the exact same STR, but select the **Text** Data Type instead, no error is displayed and the content can be saved as expected.

**Comment by bryanboza** [comment]
Fixed, following the provided steps now I'm able to publish the piece of content without problems. Tested on release-22.02 // Docker // FF
