### ISSUE TITLE
Clean up docker image

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21454]
We need to clean up how our docker image runs.  This includes

- [x] removing `dockerize` and the dockerized templates 
- [x] removing the init/waiting scripts for db and elasticsearch
- [x] using only dotCMS environmental variables to configure docker.  This means that for the most part, configuring the DB, ES, and dotCMS options should be the same whether you are running locally or in docker.
- [x] Removing hazelcast customizations - if hazelcast is to be used, admins should mount a custom hazelcast.xml file
- [x] Centralizing all config variables into a `config-defaults.sh`
- [x] Allow for APR to init and run
- [x] Incorporate the changes from the other docker issues, e.g.: 
     - #21440
     - #21063
     - #20892

**Comment by wezell** [comment]
PR: #21453

**Comment by wezell** [comment]
### Testing

- [ ] **APR loading correctly:** 

early in the startup, you should see a lines in the logs that look like:
```
22-Dec-2021 17:07:01.837 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.23] using APR version [1.6.5].
22-Dec-2021 17:07:01.837 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
22-Dec-2021 17:07:01.838 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
22-Dec-2021 17:07:01.841 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1f  31 Mar 2020]
```

- [ ] **DB Configuration**
You should only have to set the following env vars.  What you set them to depends on your config
```
DB_BASE_URL="jdbc:postgresql://db.dotcms.site/dotcms"
DB_USERNAME="dotcmsdbuser" 
DB_PASSWORD="password" 
```

- [ ] **ES Configuration**
You should only have to set the following env vars.  What you set them to depends on your config
```
DOT_ES_ENDPOINTS="https://es.dotcms.site:9200"
DOT_ES_AUTH_BASIC_USER="admin" 
DOT_ES_AUTH_BASIC_PASSWORD="admin" 
```
- [ ] **Asset share**
To test this, map in a volume on `/data/shared`, e.g. 
```
docker run -it -v $PWD/data:/data/shared -p8443:8443 dotcms-test
```

Test to make sure that the right directories are created, e.g.
`./assets` and `./felix`.  Upload a file and make sure that it works.

- [ ] **Plugins**
With the shared volume, upload an osgi plugin.  Make sure that it is there and working when you restart the container with the same shared directory,

- [ ] **Custom Starter**
Pass in the environmental variable for a custom start to load.  Make sure it loads cleanly.
```
docker run -it -v $PWD/data:/data/shared -p8443:8443 --env CUSTOM_STARTER_URL=https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20211201/starter-20211201.zip dotcms-test
```

**Comment by nollymar** [comment]
Additional PR required: https://github.com/dotCMS/dot-cicd/pull/39

**Comment by wezell** [comment]
We need to update this documentation:

https://dotcms.com/docs/latest/docker-image-configuration-options
