### ISSUE TITLE
Using resize image filters results in a larger file size, even if the image is made smaller

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21458]
**Describe the bug**
When you apply resize filters to an image without compression, the resultant image is always larger in size than the original even if the size of the image is reduced. 

Reproduced on: 21.06.4, 21.11 

Related ticket: https://dotcms.zendesk.com/agent/tickets/106144

**To Reproduce**
1. Upload an image
2. Resize to be smaller in the resize tool, you will see the image file size increase

**Expected behavior**
Images shouldn't increase in file size when being made smaller. 

**Screenshots**
![image](https://user-images.githubusercontent.com/78741732/147589451-c40885f0-35b7-432b-b3e6-5776ff936e65.png)
Original (file size 5k)

![image](https://user-images.githubusercontent.com/78741732/147589502-23ab25c9-d91e-4856-b458-27dbc5543302.png)
Resized to 75% of original (file size 10k)

**Additional context**
While much of the size gain can be mitigated with compression, this ideally should not be required.

**Comment by wezell** [comment]
Not a bug - when we resize, we convert to a lossless PNG - you need to apply compression after you resize to convert back to a compressible .jpg or .webp

**Comment by rboylsonvaro** [comment]
How would we re-size an image without compression?
