### ISSUE TITLE
WAIT_FOR Index Policy Parameter Not Passed Down Via REST API

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21469]
**Describe the bug**
When saving content via REST and using the "WAIT_FOR" index policy, the policy is not passed down and is defaulted to "DEFER" 

**To Reproduce**
1. Create a PUT call pointing towards https://demo.dotcms.com 
2. Add a contentlet's identifier and "WAIT_FOR" as query parameters
3. Tail logs while making the call
4. See "DEFER" is passed down rather than "WAIT_FOR"

**Expected behavior**
The call will pass down the "WAIT_FOR" parameter rather than the default "DEFER" if specified. 

**Screenshots**
![Screen Shot 2022-01-04 at 8 34 44 AM](https://user-images.githubusercontent.com/90852779/148092669-f6ed9630-924c-4e9f-9995-9f53b65fe134.png)
![Screen Shot 2022-01-04 at 8 47 30 AM](https://user-images.githubusercontent.com/90852779/148093841-87dae558-44c8-40aa-8a37-786e6d6b4030.png)

**Additional context**
As reported in a customer ticket: https://dotcms.zendesk.com/agent/tickets/106162

**Comment by nollymar** [comment]
PR: #22110

**Comment by alfredo-dotcms** [comment]
looks good to me!

![image](https://user-images.githubusercontent.com/37185433/166058433-3b575069-87f1-461c-88ba-b369a2b6adbe.png)

**Comment by alfredo-dotcms** [comment]
url for testing:
`http://localhost:8080/api/v1/workflow/actions/b9d89c803d/fire?identifier=09841761-aea5-4a1c-a3f3-21e0bc9f7124&indexPolicy=WAIT_FOR`

**Comment by wezell** [comment]
While we are here, we test this as well - if you stop the ReindexThread (add a breakpoint) and pass `DEFER`, the content should never be indexed.

**Comment by wezell** [comment]
If you pass `DEFER`, it should be much faster than a `WAIT_FOR`
