### ISSUE TITLE
On missing assets installs - content edit dialog breaks  

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21477]
**Description**
This is a very unlikely scenario for customers. But for us devs it is quite likely to happen.

The thing is this file `/application/wysiwyg/tinymceprops.vtl` is required. by TinyMCE to run properly 
if the file isn't found on an install this cause a javascript error when initializing a var. Which can be confusing when investigating issues or testing stuff against a customer database.

**To Reproduce**
USe a customer db and no assets to startup dotCMS

**Expected behavior**
Content Editor should never break

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/148452576-1088a99f-2e75-442f-a52e-17ec2ad7a042.png)

looks good to me!

**Comment by bryanboza** [comment]
Fixed, tested with a custom data set and it works as expected
