### ISSUE TITLE
HostAPI refactor

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21476]
We need to attack 2 issues over here:

- [x] **Improve HostCache**: it will behave just like the VanityURL cache, it will load all the hosts (the first time it's called), if there is any change to any host the whole cache will be flush and will be loaded the next time is called.
- [x] **Permissions NOT being respected**: The `findAllFromDB()` method is always using the System User to retrieve information.
- [x] **Rely on DB instead of ES**: sometimes have a few race conditions in the UI where we are expecting content to be there and it has not been indexed yet (or failed to index) and is not visible, so this will allow us to always have the updated content.
- [x] **Rely on Var Name instead of name**: As described in here: #21782

**Comment by fmontes** [comment]
Nolly left some comments in the PR

**Comment by hmoreras** [comment]
To QA: 
-  Rely on Var Name instead of name: go to the content types portlet, rename the host content, go back to the listing page and make sure load correctly. 
-  Rely on DB instead of ES: Turn off the indexes, create a new site and make sure the sites are listing correctly.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
