### ISSUE TITLE
[GraphQL] : Second Binary field in a Content Type is not loading the expected metadata

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21486]
Reported via Support: [106158](https://dotcms.zendesk.com/agent/tickets/106158)
Reproducible as of dotCMS 21.06.4, up to latest master (21.12)

We use Tika to load the metadata for the value of a **Binary Field** in a Content Type. However, if you have an additional **Binary Field**, the expected metadata is not being loaded correctly for it.

**ADDITIONAL NOTE: We're also having some class casting problems in the following methods:**
https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L87-L89

https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L115-L117

https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L119-L121

**Where the values return as `Integer` objects sometimes, and then as `Long` values later. This causes that the value returned to the user defaults back to zero all the time.**

**To Reproduce**
Reach out to me for the data set and specific STR. However, for reproducing this in our Demo Site:
1. Create a Content Type named `TwoColumnImageBlock` with three fields:
1.1. Title: `Text`
1.2. Image: `Binary` / `User Searchable` / `Show in List`
1.3. Mobile Image: `Binary`
2. Create a new content of such a type, and upload two different images to each binary field.
3. In the **Dev Tools > GraphQL** portlet, enter the following query:
```
query IMAGE_WIDTH {
  TwoColumnImageBlockCollection {
    image {
      idPath
      size
      width
      height
    }
  }
}
```
The `size`, `width` and `height` properties return as expected.
4. Now, query the second Binary field:
```
query IMAGE_WIDTH {
  TwoColumnImageBlockCollection {
    mobileImage {
      idPath
      size
      width
      height
    }
  }
}
```
5. The `size`, `width` and `height` properties all return zero as their value.

**Expected behavior**
Metadata should be available in all Binary Fields.

**Additional context**
After discussing this behavior with @fabrizzio-dotCMS , it seems like metadata generation for the non-first Binary field is not working as it should. Unfortunately, there's currently no workaround for this issue.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested with the privided example using insomnia and now it is working as expected. Tested on release-22.02
