### ISSUE TITLE
Key/Value fields needs some styling help

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21480]
When you try to add a key value field from FE side, those changes needs some styling help

![image](https://user-images.githubusercontent.com/2641437/148259345-ed92ad76-775e-462b-9499-480e475a24fe.png)

**To Reproduce**
- Login as admin
- Create a new page 
- Add a Form that contains a key/value field
- Add this form to a page 
- Now try to see that page from FE

**Expected behavior**
The UI of those fields needs be consistent with all the other fields 

**Desktop (please complete the following information):**
Tested on release-21.12 // Docker. // Chrome

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1848/files

**Comment by fabrizzio-dotCMS** [comment]
![Screen Shot 2022-02-02 at 10 00 54](https://user-images.githubusercontent.com/37148755/152199315-18c2d2bc-7f7d-41a1-8d6b-b60b3e3e5cc2.png)

They look alright.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 // Docker // FF
