### ISSUE TITLE
[REST] : Updating one Binary Field is removing the value from the other Binary Field

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21482]
Reported via Support: [106154](https://dotcms.zendesk.com/agent/tickets/106154)
Reproducible as of dotCMS 5.3.8.6.2, and latest master (21.12)

Back when the old REST API **was NOT deprecated yet**: https://dotcms.com/docs/latest/save-content-using-the-rest-api , customers were able to either update multiple binary fields, or just one of them, as described here: https://dotcms.com/docs/latest/save-content-using-the-rest-api#multipleBinaryExample

However, with the new Workflow REST API, if you try to update just one binary field, the API removes the value from the other binary field altogether. This is causing both data loss, and customers unwilling to update their custom code to use the new Workflow REST API.

**To Reproduce**
1. Create a new Content Type named `Test` -- set its default action as "Publish" -- and add the following fields:
1.1. **Text Field** named `Title` / `User Searchable` / `Show in List`.
1.2. **Binary Field** named `Image` / `User Searchable` / `Show in List`.
1.3. **Binary Field** named `Video`.
2. Create a new content of such a type with the following data:
2.1. Title = `Test 1`
2.2. Image = Any JPEG file.
2.3. Video = A different JPEG file again -- a video file is NOT necessary.
3. Create a new Advanced Template called `Template One` with the code in the `deprecated-rest-template.txt` file. Replace `{ID-OF-YOUR-CONTENTLET}` with the Identifier of the content you created in the previous step:

[deprecated-rest-template.txt](https://github.com/dotCMS/core/files/7816791/deprecated-rest-template.txt)

4. Create an HTML Page called `/test-1`, using `Template One`.
5. In an Incognito Window, open the `/test` page and enter (1) a new title, and (2) a new image file for the `Image` field.
6. The `Image` field is updated and the `Video` file is still there, as expected.
7. Now, create another Template called `Template Two` with the with the code in the `workflow-rest-template.txt` file, and do the same thing you did with the other template

[workflow-rest-template.txt](https://github.com/dotCMS/core/files/7816799/workflow-rest-template.txt)

8. Create an HTML Page called `/test-2`, using `Template Two`.
9. If you follow the exact same steps as with the first Template, you'll see that the `Image` field is updated too. However, the `Video` field lost its value.

**Expected behavior**
The new recommended API must work the same way as the deprecated API.

**Additional context**
Having the new REST API is very important for customers to start migrating their custom code to using the new API.

**Comment by wezell** [comment]
We might need a new issue, called "Save as Draft not overwriting existing images when the inode does not change".  Let's see where we get with this issue.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/22109

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF. I'm unable to reproduce after the last changes.

**Comment by bryanboza** [comment]
This is working as expected, but in the postman test we are calling the test  as the issue number, which is not a good practice

As default we need try to use a short description of the problem 
![image](https://user-images.githubusercontent.com/2641437/170530052-56184ab7-08bd-4cb6-9de5-096b2e1bea05.png)

**Comment by nollymar** [comment]
@bryanboza the postman test was renamed: https://github.com/dotCMS/core/pull/22333
