### ISSUE TITLE
Refactor MailEngine to support smtps and other JavaMail properties

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21488]
Opening this for discussion. Possible issues to address:
1. JavaMail protocol is hard-coded as "smtp" - we probably should support both "smtp" and "smtps"
2. More generally, perhaps we should set all `mail.*` env/system vars in the JavaMail Session to allow a more transparent way to configure JavaMail in dotCMS
3. Does all dotCMS outgoing mail use `MailEngine.java` or do other bits of code use JavaMail?

JavaMail provides two protocols to send mail: 
1. **smtp**: initial SMTP exchange is unencrypted; may use `mail.smtp.starttls.enable=true`to encrypt user creds and email data
Unencrypted SMTP uses port 25, `starttls` uses port 587
2. **smtps** aka "smtp over ssl" aka "tls wrapper" - all traffic is encrypted, no need for `starttls`
SMTPS uses port 465
The smtps protocol uses `mail.smtps.*` (note trailing s: smtp**s**) for its properties, vs `mail.smtp.*` for smtp properties.

DotCMS hard-codes the smtp protocol in [MailEngine.java](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/liferay/util/mail/MailEngine.java#L216-L236)
`Transport tr = session.getTransport("smtp");`
We se a few other `mail.smtp.` properties here as well.

I propose we pass `mail.*` properties set at runtime to JavaMail, e.g. 
`DOT_MAIL_TRANSPORT_PROTOCOL: smtps` or `-Dmail.transport.protocol=smtps`

JavaMail supports _many_ properties.

**Desired behavior**
Following JavaMail conventions - note the use of SMTPS vs SMTP properties, based on the protocol 

configure dotCMS to use use smtps:
```
      DOT_MAIL_HOST: email-smtp.us-east-1.amazonaws.com
      DOT_MAIL_USER: abc123
      DOT_MAIL_TRANSPORT_PROTOCOL: smtps
      DOT_MAIL_SMTPS_PASSWORD: 123abc
      DOT_MAIL_SMTPS_AUTH: 'true'
      DOT_MAIL_SMTPS_PORT: '465'
```

configure dotCMS to use smtp + starttls:
```
      DOT_MAIL_HOST: email-smtp.us-east-1.amazonaws.com
      DOT_MAIL_USER: abc123
      DOT_MAIL_TRANSPORT_PROTOCOL: smtp
      DOT_MAIL_SMTP_PASSWORD: 123abc
      DOT_MAIL_SMTP_AUTH: 'true'
      DOT_MAIL_SMTP_PORT: '587'
      DOT_MAIL_SMTP_STARTTLS_ENABLE: 'true'
```
We want to support other properties as well, for example
`      DOT_MAIL_SMTPS_SSL_PROTOCOLS: TLSv1.2`

We should continue to support unencrypted/unauthenticated SMTP as well.

**JavaMail properties**
[mail.smtp.* properties](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html)
`Note that if you're using the "smtps" protocol to access SMTP over SSL, all the properties would be named "mail.smtps.*".`

[other JavaMail properties](https://docs.oracle.com/javaee/6/api/javax/mail/package-summary.html) 
Note these two:
```
mail.host | The default host name of the mail server for both Stores and Transports. Used if the mail.protocol.host property isn't set.
mail.user | The default user name to use when connecting to the mail server. Used if the mail.protocol.user property isn't set.
```

**Snippet from a standalone JavaMail example**
```java
String smtpUserName;
String smtpUserPassword;

Properties props = System.getProperties();
props.put("mail.user", smtpUserName);
props.put("mail.host", "email-smtp.us-east-1.amazonaws.com");
props.put("mail.transport.protocol", "smtps");
props.put("mail.smtps.port", "465");
props.put("mail.smtps.auth", "true");
props.put("mail.smtps.ssl.protocols", "TLSv1.2");

Session session = Session.getDefaultInstance(props);

MimeMessage msg = new MimeMessage(session);
msg.setFrom(new InternetAddress(fromUserEmail, fromUserFullName));
msg.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
msg.setSubject(subject);
msg.setContent(body, "text/html");

Transport transport = session.getTransport();
transport.connect(smtpUserName, smtpUserPassword);
transport.sendMessage(msg, msg.getAllRecipients());
```

**Comment by wezell** [comment]
Just a note to the developer: dotCMS does not use `MailEngine.java` so this class can be ignored/removed. We need to make the changes in the `MailAPIImpl.java` to set up the mail context appropriately.

**Comment by wezell** [comment]
@yolabingo Looking at the code, it looks like all these configs should work.  Can you verify that if they do and if they do not, can you share your config the stack trace you get?

**Comment by yolabingo** [comment]
Here is one example, attempting to using SMTPS: 
```
DOT_MAIL_TRANSPORT_PROTOCOL: smtps
DOT_MAIL_SMTPS_HOST: email-smtp.us-east-1.amazonaws.com
DOT_MAIL_SMTPS_USER: ***
DOT_MAIL_SMTPS_PASSWORD: ***
DOT_MAIL_SMTPS_AUTH: 'true'
DOT_MAIL_SMTPS_PORT: '465'
DOT_MAIL_SMTPS_SSL_PROTOCOLS: TLSv1.2
```
which results in the following error. 
`javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25`
Stack trace attached.
[smtps-port465-53862.log](https://github.com/dotCMS/core/files/7858234/smtps-port465-53862.log)

**Comment by jdotcms** [comment]
after looking the code we do not have the code support for SMTPS

example: https://www.rgagnon.com/javadetails/java-0570.html

Needs changes here:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/mail/MailAPIImpl.java#L85

and more important here:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/liferay/util/mail/MailEngine.java#L219

**Comment by nollymar** [comment]
@yolabingo I have tested using smtp and smtps protocols and both cases work for me. 

**Example 1: Using smtp and properties** 
```
        String smtpUserName = "XXXX";
        String smtpUserPassword = "XXXX";

        MailAPI myMailAPI = new MailAPIImpl();
        Session session = myMailAPI.getMailSession();

        Properties props = session.getProperties();
        props.put("mail.smtp.user", smtpUserName);
        props.put("mail.smtp.password", smtpUserPassword);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.auth", "true");
        props.put("mail.transport.protocol", "smtp");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");

        MimeMessage msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress("XXXX@gmail.com", "XXXX"));
        msg.setRecipient(Message.RecipientType.TO,
                new InternetAddress("XXXX@gmail.com"));
        msg.setSubject("Test Send Email");
        msg.setContent("Hello World!", "text/html");

        Transport transport = session.getTransport();
        transport.connect(smtpUserName, smtpUserPassword);
        transport.sendMessage(msg, msg.getAllRecipients());
```

**Example 2: Using smtp and env variables** 
```
        String smtpUserName = "XXXX";
        String smtpUserPassword = "XXXX";

        MailAPI myMailAPI = new MailAPIImpl();
        Session session = myMailAPI.getMailSession();

        MimeMessage msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress("XXXX@gmail.com", "XXXX"));
        msg.setRecipient(Message.RecipientType.TO,
                new InternetAddress("XXXX@gmail.com"));
        msg.setSubject("Test Send Email");
        msg.setContent("Hello World!", "text/html");

        Transport transport = session.getTransport();
        transport.connect(smtpUserName, smtpUserPassword);
        transport.sendMessage(msg, msg.getAllRecipients());

//MY ENV VARIABLES
"DOT_MAIL_SMTP_USER": "XXXX@gmail.com"
"DOT_MAIL_SMTP_PASSWORD":"XXXX"
"DOT_MAIL_SMTP_HOST": "smtp.gmail.com"
"DOT_MAIL_SMTP_PORT", "587"
"DOT_MAIL_SMTP_STARTTLS_ENABLE", "true"
"DOT_MAIL_SMTP_SSL_PROTOCOLS", "TLSv1.2"
"DOT_MAIL_SMTP_AUTH", "true"
```

**Example 3: Using smtps and env variables** 
```
        String smtpUserName = "XXXX";
        String smtpUserPassword = "XXXX";

        MailAPI myMailAPI = new MailAPIImpl();
        Session session = myMailAPI.getMailSession();

        MimeMessage msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress("XXXX@gmail.com", "XXXX"));
        msg.setRecipient(Message.RecipientType.TO,
                new InternetAddress("XXXX@gmail.com"));
        msg.setSubject("Test Send Email");
        msg.setContent("Hello World!", "text/html");

         //Here you have two options, send the protocol as a parameter or set the env var 'DOT_MAIL_TRANSPORT_PROTOCOL': 'smtps' as you did before
        Transport transport = session.getTransport("smtps");  

        transport.connect(smtpUserName, smtpUserPassword);
        transport.sendMessage(msg, msg.getAllRecipients());

//MY ENV VARIABLES
"DOT_MAIL_SMTPS_USER": "XXXX@gmail.com"
"DOT_MAIL_SMTPS_PASSWORD":"XXXX"
"DOT_MAIL_SMTPS_HOST": "smtp.gmail.com"
"DOT_MAIL_SMTPS_PORT", "587"
"DOT_MAIL_SMTPS_STARTTLS_ENABLE", "true"
"DOT_MAIL_SMTPS_SSL_PROTOCOLS", "TLSv1.2"
"DOT_MAIL_SMTPS_AUTH", "true"
```




What @jdotcms says shouldn't affect your test, unless you explicitly enable to use our custom authenticator (which is not your case). Please try these examples and let me know.

**Comment by nollymar** [comment]
MailAPI should be used instead of MailEngine. The authenticator is not used unless you explicitly set it, I think it is there for testing purposes.

> after looking the code we do not have the code support for SMTPS
> 
> example: https://www.rgagnon.com/javadetails/java-0570.html
> 
> Needs changes here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/mail/MailAPIImpl.java#L85
> 
> and more important here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/liferay/util/mail/MailEngine.java#L219

**Comment by jdotcms** [comment]
Good clarification @nollymar

**Comment by wezell** [comment]
@yolabingo 

I am being told that the environmental variables work, and have worked that way for a year.  Which means that we should be able to do this in 21.06.  If you have questions, please reach out to Nolly for assistance.
```
//MY ENV VARIABLES
"DOT_MAIL_SMTP_USER": "XXXX@gmail.com"
"DOT_MAIL_SMTP_PASSWORD":"XXXX"
"DOT_MAIL_SMTP_HOST": "smtp.gmail.com"
"DOT_MAIL_SMTP_PORT", "587"
"DOT_MAIL_SMTP_STARTTLS_ENABLE", "true"
"DOT_MAIL_SMTP_SSL_PROTOCOLS", "TLSv1.2"
"DOT_MAIL_SMTP_AUTH", "true"
```
or 
```
//MY ENV VARIABLES
"DOT_MAIL_SMTPS_USER": "XXXX@gmail.com"
"DOT_MAIL_SMTPS_PASSWORD":"XXXX"
"DOT_MAIL_SMTPS_HOST": "smtp.gmail.com"
"DOT_MAIL_SMTPS_PORT", "587"
"DOT_MAIL_SMTPS_STARTTLS_ENABLE", "true"
"DOT_MAIL_SMTPS_SSL_PROTOCOLS", "TLSv1.2"
"DOT_MAIL_SMTPS_AUTH", "true"
```

**Comment by yolabingo** [comment]
I was under the false impression that we propagated all the DOT_MAIL* env vars to JavaMail and therefore could set any property in the JavaMail docs, and things would just work. 

As it stands dotCMS does not seem to support smtps - just "smtp" and "smtp + starttls"
Perhaps we do not need to support both "smtp + starttls" and "smtps" so long as our docs are clear about this. 

@nollymar the config example for smtps is using the starttls port, not the smtps port: 
```
//MY ENV VARIABLES
"DOT_MAIL_SMTPS_USER": "XXXX@gmail.com"
"DOT_MAIL_SMTPS_PASSWORD":"XXXX"
"DOT_MAIL_SMTPS_HOST": "smtp.gmail.com"
"DOT_MAIL_SMTPS_PORT", "587"
"DOT_MAIL_SMTPS_STARTTLS_ENABLE", "true"
"DOT_MAIL_SMTPS_SSL_PROTOCOLS", "TLSv1.2"
"DOT_MAIL_SMTPS_AUTH", "true"
``` 
port 587 = smtp + starttls
port 465 = smtps

JavaMail needs mail.transport.protocol set to smtps. 
Also, starttls and smtps are mutually exclusive, so starttls should be false (or omitted) for smtps.

Can you try your test with these changes and see if it works?
```
"DOT_MAIL_SMTPS_PORT", "465"
"DOT_MAIL_SMTPS_STARTTLS_ENABLE", "false"
"DOT_MAIL_TRANSPORT_PROTOCOL", "smtps"
```

I would expect something like this to work if smtps were supported:
```
      DOT_MAIL_TRANSPORT_PROTOCOL: smtps
      DOT_MAIL_SMTPS_AUTH: 'true'
      DOT_MAIL_SMTPS_PORT: '465'
      DOT_MAIL_SMTPS_STARTTLS_ENABLE: 'false'
      DOT_MAIL_SMTPS_SSL_PROTOCOLS: 'TLSv1.2'
      DOT_MAIL_SMTPS_HOST: email-smtp.us-east-1.amazonaws.com
      DOT_MAIL_SMTPS_PASSWORD: ***
      DOT_MAIL_SMTPS_USER: ***
```
It fails with
```
01:14:56.621  ERROR util.Mailer - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053) ~[mail.jar:1.5.2]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697) ~[mail.jar:1.5.2]
	at javax.mail.Service.connect(Service.java:364) ~[mail.jar:1.5.2]
	```

**Comment by nollymar** [comment]
A new fix was included to support `smtps` when the Password Recovery email is sent: #21625
