### ISSUE TITLE
Toggle to Code in WYSIWYG Makes UI Jump

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21492]
**Describe the bug**
This is present only for content types where a contentlet requires scrolling to view all fields. When creating a new or editing an existing contentlet of this nature with a WYSIWYG field, when toggling to code the UI "jumps" to the next field which can hide the previous field from view. This has been reported as confusing to end users

**To Reproduce**
1. Go to demo.dotcms.com
2. Create a content type with a title and 3 WYSIWYG fields
3. Create a new contentlet of this type and toggle to code on the first WYSIWYG field

**Expected behavior**
The UI will remain in place after toggling to code, so no confusion is made whether some action has been completed or not. 

**Screenshots**
![Screen Shot 2022-01-07 at 8 14 51 AM](https://user-images.githubusercontent.com/90852779/148572775-41e27730-527d-406f-89df-508568aef844.png)

![Screen Shot 2022-01-07 at 8 15 18 AM](https://user-images.githubusercontent.com/90852779/148572844-930e0886-8580-4a38-9db6-47a079bb0864.png)
![Screen Shot 2022-01-07 at 8 15 53 AM](https://user-images.githubusercontent.com/90852779/148572940-1dc984b1-41ad-43ea-86a6-0fa09e4cb419.png)

**Desktop (please complete the following information):**
 - Version: 5.3.8.6, 21.06.3, 21.12

**Additional context**
As seen in this customer ticket: https://dotcms.zendesk.com/agent/tickets/106187

This may be a screen resolution issue, as when the browser window is zoomed out this issue fails to occur.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21986/files

**Comment by fabrizzio-dotCMS** [comment]
After the fix the height on the editor still changes but not so much as it used to. 
I'm passing it.

**Comment by bryanboza** [comment]
Fixed, tested on release 22.06 // Docker // FF. Unable to reproduce after the changes
