### ISSUE TITLE
Uploading Multiple Files UI Shows Blank in Some Resolutions

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21491]
**Describe the bug**
When uploading multiple files via the browser tree, a pop-up box shows up for files selection. When this is done at some lower resolutions, this can show blank

**To Reproduce**
1. Set screen resolution to 1366 * 768 or lower
2. Go to browser tree on demo.dotcms.com
3. Attempt to upload multiple files

**Expected behavior**
The hope is the screen resolution would be supported for all aspects of the dotCMS UI

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/90852779/148566067-cbbdaf91-ccda-423c-867b-a50c633dca45.png)

**Desktop (please complete the following information):**
 - Browser: All browsers
 - Version: 21.06.3 and 21.12

**Additional context**
As reported in a customer ticket here: https://dotcms.zendesk.com/agent/tickets/106062

**Comment by fmontes** [comment]
Not an issue
