### ISSUE TITLE
Template designer: container selector breaks while there are "Unsave Changes" 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21504]
**Describe the bug**
Modify the template and while changes are unsaved (Unsaved Changes showing) the container selector is showing the wrong options.

**To Reproduce**
1. Create a template
2. Change the theme
3. While “Unsaved Changes” showing, click in the container options
4. See the options are not correct.

**Expected behavior**
Container selector should always show the containers correctly

**Screenshots**

Good:
![image](https://user-images.githubusercontent.com/751424/148991191-de549208-68e2-42ef-ad5a-d33d3f8a1169.png)

Bad:
![image](https://user-images.githubusercontent.com/751424/148991240-cc71e487-6d40-4cdc-a4d6-44559593a69b.png)

**Additional context**
This might be some state management issue

**Comment by erickgonzalez** [comment]
Working as it should but found a couple of bugs meanwhile testing it. https://github.com/dotCMS/core/issues/21558

**Comment by bryanboza** [comment]
Fixed, tested on release-22.01 // Docker // FF
