### ISSUE TITLE
Create basic render for images in block editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21508]
**Is your feature request related to a problem? Please describe.**
We need to create the file to render dot image in the container.

**Describe the solution you'd like**
We need to add the vtl here: `/core/dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock`

**Describe alternatives you've considered**
We need to render this using image API from dotcms and add lazy to lazy load all the images by default.

**Additional context**
- Related issue: https://github.com/dotCMS/core/issues/21302
- The name of the block is `dotImage`

**Comment by fmontes** [comment]
@jdotcms super weird because I saw the PR but when I add the code:

```
$dotContentMap.get('blocks').toHtml()
```

In edit mode is rendering this 

```
$content.text $content.text
```

That I don't know where are them coming from.


<img width="1127" alt="image" src="https://user-images.githubusercontent.com/751424/159553510-3f2b997e-17dd-42c9-9cc1-d60193e32650.png">

**Comment by wezell** [comment]
Please make sure to null escape all velocity variable references with a `!`, e.g. `$!content.text`

**Comment by fmontes** [comment]
Scaping done: https://github.com/dotCMS/core/pull/21891
