### ISSUE TITLE
Add State Management to palette 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21507]
It seems that we need to add State Management to our Content Reuse Palette.  This is the place holder for it.

**Comment by nollymar** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1856

**Comment by fabrizzio-dotCMS** [comment]
the description on this ticket doesn't get me a lot to work with testing-wise. So I tried to verify that the palette works as expected compared to demo. and the only observation I have is that the reordering feature does not work. I can not rearrange the order on which stuff get added into a container. But that also happens in demo for which I will report that as a separate issue

**Comment by bryanboza** [comment]
Fixed, tested the main functionality of the content palette and still working as expected after those changes. Tested on release-22.03 // Docker // FF
