### ISSUE TITLE
Date/Time Field Changes for All Language Versions in URL Mapped Content

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21518]
**Describe the bug**
When dealing with multi-lingual URL mapped content, when the `date/time` field is updated for one language version it is then updated for all other language versions too. 

**To Reproduce**
1. Go to demo.dotcms.com
2. Create a Spanish version of a blog content type
3. Change the posting date of the english version
4. See the Spanish version populate that same date automatically 

**Expected behavior**
The date.time field would be populated on the inode and not the identifier to allow for distinct `date/time` values across language versions.  Another possibility would be to have multiple dates available and be able to set which one would be served as the `published` or `posting` date

**Screenshots**
Possible solution if you can set "Another Date" Field in Screenshot

![Screen Shot 2022-01-12 at 11 15 31 AM](https://user-images.githubusercontent.com/90852779/149206740-97d8968a-0795-4401-b31d-010d27e53fb4.png)

**Desktop (please complete the following information):**
 - Versions : 22, 21.06.4 

**Additional context**
As reported by a customer: https://dotcms.zendesk.com/agent/tickets/106208

**Comment by wezell** [comment]
Currently, we rely on the `identifier.syspublish_dates` to find content that needs to be published and unpublished.  We could implement another pattern of
1. filtering list of content types that have publish dates
2. doing a es query to pull unpublished content whose date has passed
3. publish that content
2. filtering list of content types that have expire dates
3. doing an es query where that has passed and the content is live
4. unpublishing those.

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21518?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
We have another bug here:

If we try to create a Contentlet with a expire date for today it is getting:

<img width="303" alt="Screen Shot 2022-04-28 at 12 04 04" src="https://user-images.githubusercontent.com/10408015/165818186-023dcbce-8a05-40cc-852e-4d4ec8bbcea1.png">

Even if the time if after the right now time.

Step to reproduce:

- Create a Content Type with an expire field.
- Create a new Contentlet and try to set a expire date for today (maybe two or three hours later than the current time)

**Comment by wezell** [comment]
One other rule -we should not autopublish content that is in the archived state, only if it is in the working state.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/869

**Comment by dsilvam** [comment]
Passed Internal QA. Different versions of a Blog in different languages keep their own posting date (publish date), correctly updating the unpublish/publish status.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF

**Comment by freddyucv** [comment]
**Needs Work:** when created a contentlet froma oOntent Type what does not have any publish date it keep publishing automatically.

Step to reproduce:

- Create a New Content Type, Named whatever you want
- Add just a Text field and called it title
- Create a Contentlet from the previos created Content Type, just Save it not publish.
- After a bit while the Contentlet is going to publish automatically.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise/pull/880

**Comment by bryanboza** [comment]
Fixed, tested on release-22.08 // Docker // FF
