### ISSUE TITLE
Metadata Versioning 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21519]
Metadata should include a version attribute.
dotCMS should be somehow aware of the current metadata version number being released. So that every time the metadata gets extracted from its repository the version attribute must be compared against the current metadata version. If older or inferior the MD must be regenerated lazily.

The idea behind this approach is to avoid having to reindex or rebuild the whole metadata. The system must be smart enough to regenerate and replace lazily the old MD

**Comment by wezell** [comment]
Fabro, I added this one: #21515
