### ISSUE TITLE
Change to FILE_SYSTEM for Metadata Storage

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21516]
We need to change the default of our MetaData Storage Provider from the database to the File System (as we have had in the past).  To do this, we need to set the StoragePersistenceProvider to return the `FILE_SYSTEM` provider rather than the db provider.

This is because in certain cases, on initial startup on loaded systems that are calling for metadata, the DB provider can cause resource issues with database connections and file system access.

This property can still be configured as needed.

**Comment by wezell** [comment]
PR: #21517

**Comment by erickgonzalez** [comment]
Now `metada.json` file lives under `FILE_SYSTEM`.

**Comment by bryanboza** [comment]
Fixed

**Comment by erickgonzalez** [comment]
Not relevant to 5.3.8 LTS
