### ISSUE TITLE
Add metadata version number to binary metadata

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21515]
We need to include a metadata version number property in the binary metadata that we store. When reading metadata from the metadata provider, we should always check the metadata version number to know if the system needs to regenerate the metaData to include new properties. 

The `BINARY_METADATA_VERSION` should be an int (in code) that follows the same pattern as our StartupTasks, eg, the date formated like `YYYYMMDD`;

**Comment by fabrizzio-dotCMS** [comment]
Please Test that you add custom metadata (e.g. adding a focal point) then bump up the version of the metadata through the property BINARY_METADATA_VERSION put a number incredibly high like **20440101** and then restart the server. Verify the metadata comes back after a restart with the new version number **BINARY_METADATA_VERSION** and also that the custom metadata gets preserved. Meaning the focal point should still be there.

**Comment by nollymar** [comment]
**Internal QA:** In general, the internal QA passed. I only noticed this warning logged multiple times when the server is starter using full starter: 
```
16:01:01.300  WARN  hydration.MetadataDelegate - error calculating metadata 
16:01:01.300  WARN  hydration.MetadataDelegate - the binary `/data/shared/assets/f/4/f489ef7f-4a55-47b8-a342-29dc1ac8899d/fileAsset/_video.scss` isn't accessible 
16:01:01.301  WARN  hydration.MetadataDelegate - com.dotcms.storage.FileStorageAPIImpl.generateMetaData(FileStorageAPIImpl.java:269)
16:01:01.305  INFO  caffine.CaffineCache - ***	 Building Cache : esquerycache, size:10000,Concurrency:32
16:01:01.306  INFO  caffine.CaffineCache - ***	 Building Cache : esquerycountcache, size:10000,Concurrency:32
16:01:01.307  WARN  hydration.MetadataDelegate - error calculating metadata 
16:01:01.307  WARN  hydration.MetadataDelegate - the binary `/data/shared/assets/f/4/f4d84147-2d6e-4b4b-93e0-93b1d57320c2/fileAsset/login-api.vtl` isn't accessible 
16:01:01.307  WARN  hydration.MetadataDelegate - com.dotcms.storage.FileStorageAPIImpl.generateMetaData(FileStorageAPIImpl.java:269)
``` 
If this warning doesn't impact customers with huge datasets, I wouldn't see it as a concern

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested forcing to generate a new metadata increasing the property `BINARY_METADATA_VERSION` and we are regenerating the metadata without problems and keeping the same values 
Originally: 
![image](https://user-images.githubusercontent.com/2641437/156670973-7ce37c73-7fd1-4a67-b167-76fd181b0b4a.png)
After upgrade: 
![image](https://user-images.githubusercontent.com/2641437/156671039-1c896445-f769-4f33-9547-423f92356d78.png)
