### ISSUE TITLE
[Static Publishing] : Problem with multi-language contents

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21537]
Reported via Support: [106166](https://dotcms.zendesk.com/agent/tickets/106166)
Reproducible as of dotCMS 5.3.8.x, up to latest master (22.01)

Static pushing content that is available in several languages may cause dotCMS to fail pushing it in all of their versions. 

**To Reproduce**
1. Set up the Static Publishing configuration -- if you have any questions, ask me about this.
2. Create a simple test HTML Page in English, and push it. Make sure it made it to your S3 bucket correctly.
3. Now, create 3 more Languages so that you have: English, Spanish, French, German, and Italian.
4. Create versions of the test HTML Page in all five languages.
5. Delete all the contents from your S3 bucket. Then, clear your pushed asset history in dotCMS.
6. Finally, push the test HTML Page once more. Not all language versions are being pushed.

**Expected behavior**
The number of available languages for a content should affect the result in Static Publishing.

**Additional context**
Both @freddyucv and I inspected the code, and found the problem with it.
**Note:** Please reach Jose for more information.

**Comment by jcastro-dotcms** [comment]
Enterprise PR: https://github.com/dotCMS/enterprise/pull/846

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF. 

Now we are pushing the all the pages as dependency.
