### ISSUE TITLE
Edit Template Properties Modal makes changes get lost

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21558]
**Describe the bug**
If you update any of the template properties that are in the Edit option, unsaved changes get lost.

**To Reproduce**
1. Create a new Template Design
2. Add a couple of containers
3. Click over the Edit button
4. Add some description
5. Click Save
6. The layout got lost
**And**
1. Create a new Template Advanced
2. Add a couple of containers
3. Click over the Edit button
4. Add some description
5. Click Save
6. The Save button for the Code is Disabled, so you can't save your changes.

**Expected behavior**
Edit Template Properties shouldn't lose changes.

**Screenshots**

https://user-images.githubusercontent.com/5278970/150189223-d93298eb-9c48-4346-8447-b64e29a6fae3.mov

https://user-images.githubusercontent.com/5278970/150189417-5b6db570-1382-4acb-b2de-7c04158b95ad.mov

Tested on release-22.02.

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/152869362-95c516d8-047f-49b9-ab41-14f6169a40f4.mp4

**Comment by bryanboza** [comment]
Still happening in the last release image. Tested on docker with the image `22.02_f1f7950_SNAPSHOT ` generated yesterday and I'm able to reproduce 
Here the video:

https://user-images.githubusercontent.com/2641437/153259652-4e78a2c1-b894-4f8a-a84c-33bb5b79d783.mov
