### ISSUE TITLE
Add forms from content palette error

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21552]
**Describe the bug**
When you drag and drop a form to the page, there is an error in the because of the `successCallback` and the page “hangs”.

If you refresh the page, the form is added.

**To Reproduce**
1. Edit a page
2. Click on "Forms" on the content palette
3. Drag and drop the Contact us form
4. See error in the console and the page

**Expected behavior**
It should add the form correctly.

**Additional context**
Seems related to the success callback recent changes.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1868

**Comment by bryanboza** [comment]
We need some work here, we are getting an error if you try to D&D and then leave the form in some area where you are unable to see the blue indicator, we are not adding the form and we get this error 
Attached the video:

https://user-images.githubusercontent.com/2641437/153251567-1cb07b96-322c-4dbc-9649-396e0b874e26.mov

**Comment by hmoreras** [comment]
fix error reported by Bryan: https://github.com/dotCMS/core-web/pull/1877/

**Comment by bryanboza** [comment]
Still getting problems with this functionality

Now we don't have this error, but once that you have been added the form to the page and you try to reorder we have multiple JS errors in console. 
![image](https://user-images.githubusercontent.com/2641437/153306437-fec20025-3d50-465d-8cbc-61d6a998e45d.png)
