### ISSUE TITLE
allow Dockerfile to build with gid=0

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21572]
When building a docker image, we give the user the ability to specify the USER_NAME, UID and GID of the user to run as.

```
ARG USER_UID="65001"
ARG USER_GID="65001"
ARG USER_NAME="dotcms"

# Creating default non-user 
# the useradd 
RUN groupadd -g $USER_GID $USER_NAME && \
	useradd -l -d /srv -g $USER_GID -u $USER_UID $USER_NAME

# Copy our build
COPY --from=build-cms --chown=dotcms:dotcms /srv/ /srv/
COPY --chown=dotcms:dotcms ROOT/ /
```

The issue is that in some cases, for example in openshift, you need to be able to specify a `USER_ID=65001` with the ROOT group for GID, e.g. `USER_GID=0`.    This breaks our Dockerfile build because we explicitly add whatever group has been specified.

Also, if you specify a `USER_NAME`, you can see that we do not use it when we are `chown`ing the files, which will break as well.

**Comment by nollymar** [comment]
**Passed QA:** I tested the image locally and also deployed it in our servers successfully
