### ISSUE TITLE
Remove "Unsaved changes" from auto saving

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21600]
**Is your feature request related to a problem? Please describe.**
Saying “Unsaved Changes” is confusing because users might think that a button is to be pressed but is not button there.

**Describe the solution you'd like**
Remove "Unsaved Changes" and only leave "Saving" and "Saved"

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
