### ISSUE TITLE
Change `coreWebReleaseVersion` and `webComponentsReleaseVersion` to correct version for 22.01 branch

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#21603]
Currently `coreWebReleaseVersion` and `webComponentsReleaseVersion` properties at `core`'s `gradle.properties` file are pointing to `rc`. They should be pointing to `22.1.0-rc.1` instead.
This is done through the release process workflow which is failing to update so. Therefore this issue is contemplating to fix this `dot-cicd` bug.
As a third task the release automation process should be run again.

discussion: https://github.com/dotCMS/core/discussions/new

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21603?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21621
