### ISSUE TITLE
BinaryMap still hits fs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21617]
When customers are using the vtl api, e.g. `/api/vtl/myendpoint` they are scripting in velocity and getting binary asset information from Velocity's `BinaryMap` class.  This class does not use the new metadata information available to dotCMS and instead hits the FS for all its information.  We need to change that and have the BinaryMap class hit the metadata caches first to save NFS traffic and calls.  Take a look at the amount of time being taken by FS operations in this trace:

![Screen Shot 2022-01-26 at 5 21 41 PM](https://user-images.githubusercontent.com/934364/151258090-daa5348d-e22a-4dd6-9cfe-3ec844c3ab64.png)

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21617?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by jdotcms** [comment]
I am wondering how the metadata cache will save the FS hit, b/c it only stores the meta but not the content (or may I wrong @fabrizzio-dotCMS )?

**Comment by fabrizzio-dotCMS** [comment]
Sorry I had not seen this issue before. Thanks for the @mention @jdotcms 
I don't see any use of the content in the class. Looks pretty simple to re-write using the Metadatda API
it should have everything you need there 
Simply repace this
`file = content.getBinary(field.getVelocityVarName());`
With this:
`Metadata meta = content.getBinaryMetadata(field.getVelocityVarName())`

and make Metadata meta class attribute. Pretty much it has all you need to accomplish what's already being done. 
Replaces all uses file with metadata

**Comment by freddyucv** [comment]
We already have this commit: https://github.com/dotCMS/core/compare/issue-21617-binarymap-metadata

**Comment by freddyucv** [comment]
> Sorry I had not seen this issue before. Thanks for the @mention @jdotcms I don't see any use of the content in the class. Looks pretty simple to re-write using the Metadatda API it should have everything you need there Simply repace this `file = content.getBinary(field.getVelocityVarName());` With this: `Metadata meta = content.getBinaryMetadata(field.getVelocityVarName())`
> 
> and make Metadata meta a class attribute. Pretty much it has all you need to accomplish what's already being done. Replaces all uses of file with metadata
> 
> hit me up if you need some further info.

@fabrizzio-dotCMS But ,does the MetaData class have the file's content?

@jdotcms we can avoid hit the FS not just with the content, we can avoid to hot the FS to get the file size for example, like here:

https://github.com/dotCMS/core/compare/issue-21617-binarymap-metadata#diff-5d020b11df402f7d88d21a048d38a913cd5446d3bbed67c8cd5317bfe59b1728R72

**Comment by jdotcms** [comment]
if it is the case, the metadata would be enough

**Comment by fabrizzio-dotCMS** [comment]
Metadata doesn't have the content I don't think it is needed here anyways.

**Comment by fabrizzio-dotCMS** [comment]
on `21.06.6` I can see  that the Metadata class has (title, name, size, sha256, path, contentType, modDate, isImage, width and height)

**Comment by freddyucv** [comment]
**Pass Internal QA:** Step to test

- Create a new Content Type call type_1 and add a Text Field call test.
- Create two new file in /applicaction/vtl/test
get.vtl

```
#if($pathParam)
   #set($contentList = [$dotcontent.find($pathParam)])
#else
    #set($contentList = $dotcontent.pull("+structureName:Type1 +(conhost:$!{host.identifier} conhost:SYSTEM_HOST)",0,"Type1.test"))
#end

#set($resultList = [])
#foreach($contentlet in $contentList)
    #set($contentlet_test = {})
    $contentlet_test.put("test", $contentlet.test)

    $resultList.add($contentlet_test);
#end
$dotJSON.put("list", $resultList)
```

post.vtl

```
#set($actionId = "b9d89c803d") // save-workflow-action id
#set($savedContent = $workflowtool.fire($bodyMap, $actionId));
$dotJSON.put("savedObject", $savedContent.getMap())
```

- Create a new type_1 contentlet.
- Use postman to send several request to 
 GET: http://localhost/api/vtl/test/[new contentlet id]

- Use postman to send several request to 
 POST: http://localhost/api/vtl/test
BODY: {
    "contentType":"Type1",
   "languageId":1,
    "test": "Testing"
}

**Comment by bryanboza** [comment]
Testing following the provided steps and I'm unable to confirm because the "glowroot" tool is not registering the transaction that access the `vtlResource`. 

After ask to @freddyucv he doesn't know why this is happening, then I'm unable to confirm this fix is working, please retest following those steps and make sure this is working.

**Comment by dsilvam** [comment]
Passed Internal QA. Looking better:
<img width="1296" alt="Screen Shot 2022-03-14 at 16 19 36" src="https://user-images.githubusercontent.com/1576794/158270442-b1b939a7-6fb6-4ee4-b77d-2c46d9815f61.png">

**Comment by bryanboza** [comment]
Fixed, tested by @dsilvam and it is working for him.

**Comment by erickgonzalez** [comment]
Not relevant to 5.3.8 LTS

**Comment by erickgonzalez** [comment]
We need to first backport this one https://github.com/dotCMS/core/issues/20446 since it uses methods modified/created in there.
