### ISSUE TITLE
Template Publish UI Suggestion

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21612]
**Is your feature request related to a problem? Please describe.**
In previous versions of dotCMS (such as 5.3.8.6) when creating a new template or updating an existing one, users had the ability to  access publish, as well as save, workflow options directly within the creation window. In versions 21.06 and later, users must return to the template portlet to publish. 

**Describe the solution you'd like**
Provide users the full workflow options within the template edit screen to avoid having to go back to the template portlet, particularly when they need to publish

**Describe alternatives you've considered**
Create a default option of  "publish" when editing or creating a new template, or revert to the 5.3.8.6 template UI experience

**Additional context**
Currently in demo you can see unsaved changes
![Screen Shot 2022-01-26 at 7 16 21 AM](https://user-images.githubusercontent.com/90852779/151190815-5ed04646-3a4e-4201-a5b2-89ae75d796ec.png)

Then you must go back to the templates portlet to access workflow options
![Screen Shot 2022-01-26 at 7 17 28 AM](https://user-images.githubusercontent.com/90852779/151191011-bb2ec2a6-ae1d-4b7c-acdb-43921de067c4.png)

This has been requested by a customer: https://dotcms.zendesk.com/agent/tickets/106409

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1867/files

**Comment by fabrizzio-dotCMS** [comment]
The Publish Button should be enabled at all times **while the template is in a working state**. And Not only while I make changes on the active editor.
Let's consider this scenario: 
I open The Template editor remove a container and then leave the editor. then I reopen the template and I want to publish it.
The Publish button isn't enabled. In order to be able to publish the template, I would need to introduce another change.

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF

**Comment by swicken-dotcms** [comment]
Only backport this for 22.03
