### ISSUE TITLE
Container Resource

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21626]
**Is your feature request related to a problem? Please describe.**
Create container resource endpoints.

**Describe the solution you'd like**
CRUD endpoints.

**Comment by fmontes** [comment]
Needs to check @jdotcms PR.

**Comment by jdotcms** [comment]
Working on fixing the curls

**Comment by jdotcms** [comment]
Doc
https://docs.google.com/document/d/1z71A5oF_V3xuqnGrNVSFDniniQGf6oBhIA4soy9IAck/edit?usp=sharing

**Comment by jcastro-dotcms** [comment]
Based on [the GoogleDoc posted by Jonathan](https://docs.google.com/document/d/1z71A5oF_V3xuqnGrNVSFDniniQGf6oBhIA4soy9IAck/edit?usp=sharing) and the Postman tests, this is working as expected.

Passed Internal QA.
