### ISSUE TITLE
[Push Publishing] : Pushing single archived content un-publishes all its versions in receiving instance

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21624]
Reported via Support ticket: [106349](https://dotcms.zendesk.com/agent/tickets/106349)
Reproducible as of dotCMS 21.06.6, up to latest master (22.01)

In dotCMS, you can have the same Contentlet available in more than one language. Even if you only select, for example, the English version of it, the application will push all the other languages as well. At some point, users might need to archive only ONE specific language version without affecting the other ones. However, this is causing ALL the other language versions to get un-published.

**To Reproduce**
1. Set up a Push Publishing environment.
2. In the sender, set up four languages: English, Spanish, French, and Italian.
3. In the sender, create a test `Rich Text` content, and create a version in all four languages.
4. Push such a content to the receiver. All four versions will be pushed.
5. In the sender, ONLY archive the Italian version of the content.
6. Push the English version, which is NOT archived.
7. All versions of the content in the receiver will get un-published.

**Expected behavior**
The Push Publishing mechanism must be smart enough to push the archived version, and leave the other ones as they are.

**Additional context**
The currently valid workaround is to delete/destroy the archived version of the conflicting content in the sending instance, and push it again.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/855

**Comment by dsilvam** [comment]
Passed Internal QA: After following the described steps only the Italian version was left archived on the receiver.

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps and now we are able to archive just one version and push the content without problem. Tested on release-22.03 // Docker // MSSQL
