### ISSUE TITLE
Bring Back do not update the content in edit mode. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#21629]
**Describe the bug**
If the user bring back a version and close the modal in edit mode without a saving or publish, the content in the edit page don't get updated.  

**To Reproduce**

https://user-images.githubusercontent.com/31667212/151598545-968adbea-fc40-4eee-b524-71021fe28fde.mp4

**Expected behavior**
Should update the content in the edit page.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF
