### ISSUE TITLE
URL Mapped Content Fails with More than 1 Field Variable

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21639]
**Describe the bug**
When creating URL mapped content, often a user will want to use a content type's field variables to leverage within the URL map pattern. When using one field this works fine, however if the user wishes to use 2 or more this will cause it to fail

**To Reproduce**
1. Go to demo and edit the `blog post` content type 
2. In the `Url Pattern` field change the current value to `/blog/post/{id}/{urlTitle}`
3. Save the content then try to access Blog URL mapped content on demo.dotcms.com
4. See all url mapped content return a 404

**Expected behavior**
A URL map pattern is not limited in how many fields of a content type it can include

**Screenshots**
![Screen Shot 2022-01-31 at 1 51 27 PM](https://user-images.githubusercontent.com/90852779/151879018-920d4c84-86e1-4698-aada-04b445fb2a5c.png)
![Screen Shot 2022-01-31 at 1 51 36 PM](https://user-images.githubusercontent.com/90852779/151879045-e5e1e1b2-7a8a-4f76-b34a-95ead3f0c6fd.png)

**Desktop (please complete the following information):**
 - Version 22, 21.06.6

**Additional context**
As reported by a customer: https://dotcms.zendesk.com/agent/tickets/106441

**Comment by wezell** [comment]
All fields used in a url map need to be marked as indexed.
