### ISSUE TITLE
Unable to generate password for users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21634]
We recently added a generate password option when you are adding/editing a user. But in the release branch we are unable to see this button, seems has been disappeared and this is causing you are unable to create or modify the user password. 

When you try to type the password we are getting the security validation error 
![image](https://user-images.githubusercontent.com/2641437/151624979-73d89865-d28c-4abd-b0ee-c320fd16731a.png)

And you are unable to create or edit a user. 

**Expected behavior**
We need to bring back the generate password functionality, also, we need be able to type some password that meets with the security expectations and save it without problems 

**Desktop (please complete the following information):**
Tested on release-22.02. // Docker // FF

**Comment by fabrizzio-dotCMS** [comment]
![Screen Shot 2022-02-01 at 14 41 03](https://user-images.githubusercontent.com/37148755/152047939-9a1b6bbf-d1ab-43dd-ae5c-9508e8f9531d.png)

We're missing an i18n key there.
Needs Work.

**Comment by alfredo-dotcms** [comment]
![image](https://user-images.githubusercontent.com/37185433/152050078-4a704a62-c7ae-43e4-8ab6-623c7bcaf23a.png)

https://github.com/dotCMS/core/pull/21643/files

**Comment by fabrizzio-dotCMS** [comment]
it was the local storage.
Once cleared the proper label showed up

**Comment by wezell** [comment]
should we be storing the i18n messages in local storage using the dotCMS version number as a key so that it will invalidate when a dotCMS instance is updated?

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF. The @wezell comment will be moved to a new card to fix that from FE prospective. card #21659
