### ISSUE TITLE
json.fetch times out in dotCMS when there are more than 50 results - v5.3.8.8

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#21631]
As reported in https://dotcms.zendesk.com/agent/tickets/106421 
Tested and confirmed bug in local 5.3.8.8 instance

json.fetch times out in dotCMS when there are more than 50 results - v5.3.8.8

Using just the api call in a browser all results will display. But when you use json.fetch in a widget there is a timeout error if there are mor ethan 50 items. 

**To Reproduce**
1. Create widget that uses` #set($jsonResponse = $json.fetch($url))`
2. Fetch results that have more than 50 items.
3. Items are not displayed

The dotcms.log shows this error:

```
[28/01/22 17:00:29:177 UTC] WARN http.CircuitBreakerUrl: Connection attempts failed Read timed out
[28/01/22 17:00:29:177 UTC] ERROR viewtools.JSONTool: Error on parsing the String: , message: No content to map due to end-of-input
```

**Comment by craigWagner99** [comment]
Workaround: If you manually add a timeout you can fetch more than 50 results.
`$json.fetch( URL, Timeout )`

**Comment by wezell** [comment]
This is a timing issue.  json calls default to 2 seconds timeout and it seems like the remote endpoint is not able to provide more records than 50 within that window.
