### ISSUE TITLE
Remove GSON dependency

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21641]
GSON dependency must be removed and Jackson should be used instead.

**Comment by fabrizzio-dotCMS** [comment]
Note for QA: 
I would say at least we should do a smoke test to verify that stuff like 

- Push publish. 
- Site search 
- Content types
- and the index in general.

I think we should probably compare the new index against an old version. 
Or run some ES Queries to verify it's all working as expected.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested the mentioned modules and seems that everything is working as expected. Tested on release-22.04 // Docker
