### ISSUE TITLE
[WebP] : WebP filter is breaking image file

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21657]
Reported via Support ticket: [106460](https://dotcms.zendesk.com/agent/tickets/106460)
Reproducible as of dotCMS 5.3.8.9, up to latest master (22.01)

Applying the `/webp_q/` filter to a specific image is causing the generated image to break completely.

**To Reproduce**
1. Upload the following File Asset to any folder in your dotCMS instance:

![middle-donut-brand](https://user-images.githubusercontent.com/8779585/152237889-496acf69-ea95-432a-95d4-8c64767ff62c.png)

2. Open it up, and copy the either the **Version Path** or the **ID Path** link. It should lool like this: https://demo.dotcms.com/dA/f920a68a12/fileAsset/middle-donut-brand.png
3. Paste it in another tab, and make sure it shows up correctly.
4. Now, add the following filters to it: https://demo.dotcms.com/dA/f920a68a12/fileAsset/middle-donut-brand.png/70w/webp_q/100
5. As you can see, the image breaks now.

**Expected behavior**

**Screenshots**
The WebP filter should not break the image file at all.

**Additional context**
The only currently valid workaround is to remove the `/webp_q/` filter from the URL altogether.

**Comment by wezell** [comment]
This is because this is not a valid `/dA` path.  The `webp_q` param is for use with the more verbose `/contentAsset/image` pathing.  The correct path for `/dA` 
is https://demo.dotcms.com/dA/f920a68a12/fileAsset/middle-donut-brand.png/70w/100q
