### ISSUE TITLE
Once a fileAsset is saved. the file itself can not be replaced using Save.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21656]
Discovered while testing https://github.com/dotcms/core/issues/21414
Found in master reproducible in the current demo

**To Reproduce**

1. Go to Content Search and create a File asset.  Choose any image and hit save. Then close the dialog.
2. Open the File asset again and hit remove. Now replace the file with a different image. Hit **Save** again. Then close the dialog.
3. Now on content search notice the image didn't get updated. Open the dialog again. You'll see that in fact, the file is still the old one. It didn't get replaced with the second one. Hitting save didn't take any effect replacing the binary.
4. Also notice that when reopening the dialog and double-clicking the image opens a different image.

This only happens when using Save. Replacing the file and hitting publish allows me to create a new version of the file and the newly uploaded file gets replaced indeed.

It might be a matter of the thumbnail not getting updated. But it totally gives the feeling that the file isn't getting updated

**Expected behavior**
You should be able to replace the file as many times as you want.

**Comment by erickgonzalez** [comment]
Please test both views (card and list).

**Comment by bryanboza** [comment]
Fixed, tested on release-22.02 // Docker // FF. Now we are updating the thumbnail without problems
