### ISSUE TITLE
Add backdrop-filter to our popup overlay background

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21660]
**Is your feature request related to a problem? Please describe.**
We want to make the app looks more "appy" (Jason's words) so for the overlay of the dialogs we want to add:

```
    backdrop-filter: blur(5px);
```

**Describe the solution you'd like**
We need to add this for primeng dialog and our custom dot-dialog component.

**Comment by alfredo-dotcms** [comment]
Note to QA: this can be checked comparing demo with the effect on the background `blur` of this img
![image](https://user-images.githubusercontent.com/37185433/152573502-660d5936-df04-4795-a9c1-351b760fa0a7.png)

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/core-web/pull/1870/files
https://github.com/dotCMS/core/pull/21665/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

![Screen Shot 2022-03-01 at 11 20 15 AM](https://user-images.githubusercontent.com/8741395/156206974-a0b51207-e338-4a10-824c-5df4f68a43d5.png)
![Screen Shot 2022-03-01 at 11 18 22 AM](https://user-images.githubusercontent.com/8741395/156206983-4a22ff7d-f23c-4421-a639-3bf94908bf64.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Docker // FF
