### ISSUE TITLE
On Templates Portlet "Show Archived" Checkbox not working.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21666]
**Describe the bug**
This bug is reproducible in **Master**. even after the latest merge from the release has already taken place. 
**Doesn't happen on the release branch.**

**To Reproduce**
1. Go to Templates portlet. 
2. Select any template and unpublish it then archive it
3. Now click on the "Show archived" checkbox located on the top 
4. I can not see any error on the javascript console nor on the network tab. The Portlet just blinks but nothing happens. No archived templates are shown. **The Checkbox can not be checked**

**Expected behavior**
Archived templates should become visible while the checkbox is checked and vice versa

**Comment by jdcmsd** [comment]
I think this one was solved in [https://github.com/dotCMS/core/issues/21885](https://github.com/dotCMS/core/issues/21885), right?

**Comment by waqasakramdot** [comment]
Customer reported this issue on 22.03: https://dotcms.zendesk.com/agent/tickets/108496
