### ISSUE TITLE
Add config property to open asset files using O_DIRECT to work around kubernetes page cache/memory limit issue

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21669]
Opening for discussion. This issue effects dotCMS Cloud and may impact more self-hosted customers over time as k8s adoption increases.

**Is your feature request related to a problem? Please describe.**
We are seeing DotCMS kubernetes pods evicted for high memory use, seemingly due to [this long-standing issue](https://github.com/kubernetes/kubernetes/issues/43916) in kubernetes. DotCMS pods that serve diverse and/or large file assets accrue significant linux page cache (aka file cache) use that leads to the pods being evicted. High traffic can exacerbate the issue, and unwanted evictions during periods of high traffic are obviously more impactful.

When dotCMS reads or writes a file, that file is loaded into memory in the Linux page cache on the k8s node running the dotCMS pod. This page cache memory use is applied toward the memory limit of the pod(s) that accessed the file. The pods have no ability to relinquish this memory - it will reside in memory on the host node so long as the host node doesn't need to reclaim this page cache memory for other tasks. 

**Describe the solution you'd like**
Provide a boolean config property such as `DOT_FILESTREAM_BYPASS_PAGE_CACHE` - when enabled, dotCMS opens file assets using `O_DIRECT` which tells linux not to store the files in the page cache. See [Add support for O_DIRECT](https://bugs.openjdk.java.net/browse/JDK-8164900#:~:text=JDKJDK%2D8164900-,Add%20support%20for%20O_DIRECT,-Export)

**Describe alternatives you've considered**
One suggested workaround is to run a privileged k8s sidecar that runs a cronjob to prune the cache routinely
`echo 1 > /proc/sys/vm/drop_caches`

Downsides to this:
1. This evicts the page cache for all pods on the node, so lower-traffic pods that aren't impacted by this issue lose the benefit of the page cache, which can be significant.
2. Cron is not a great tool here - hard to know how frequently this purge needs to happen. A busy pod might exceed its memory limit between cron executions. Perhaps better to have a simple daemonized process evicting file cache when it reaches a certain size.

**Additional context**
This k8s issue is almost 5 years old, so it may not be resolved any time soon. It is even referenced in the [node eviction docs](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#active-file-memory-is-not-considered-as-available-memory).

Any site experiencing this issue should use a CDN to serve its static assets. Bypassing or frequently purging the page cache will likely result in 

- increased throughput on the assets file system (probably NFS or EFS)
- slower response times for file asset requests as dotCMS waits on the file system
- higher load in dotCMS

**Comment by wezell** [comment]
Maybe we use a library like https://github.com/smacke/jaydio
