### ISSUE TITLE
Cannot push publish to a Static S3 bucket with SSE AES-256 encryption

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21678]
**Describe the bug**
If we are pushing to an S3 bucket with SSE AES-256 encryption enabled we get a 403 access denied error

Reproduced on: 21.01
Related ticket: https://dotcms.zendesk.com/agent/tickets/106536

**To Reproduce**
1. Create an S3 bucket with a policy to enable SSE. Instructions for the bucket policy are here:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html

2. Set up push publishing to this bucket. 
3. Push any asset. 

You will see errors in your logs like this: 
```
[08/02/22 21:45:13:314 GMT] ERROR staticpublishing.AWSS3EndPointPublisher: Can't push file: /data/shared/assets/bundles/01FVDMNV1AY02CZXZF3P6V1B2S-static/live/demo.dotcms.com/1/images/blogs/Foto8.jpg, reasons : 
 Retry #: 0, Error: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 8PP78049QW7S983R)
 Retry #: 1, Error: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: P98G06GWWMJHT1BA)
 Retry #: 2, Error: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: QA582DD96MH6KW6W)
 Retry #: 3, Error: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: KWK0P4ZQ40HJ0514)
[08/02/22 21:45:13:318 GMT]  INFO util.PushPublishLogger: class com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher : Status Update: Bundle sent
[08/02/22 21:45:13:331 GMT]  INFO util.PushPublishLogger: class com.dotcms.publishing.PublisherAPIImpl : [BundleID: 01FVDMNV1AY02CZXZF3P6V1B2S] Completed Publishing Task
[08/02/22 21:46:03:104 GMT]  INFO quartz.DotJobStore: Handling 1 trigger(s) that missed their scheduled fire-time.
[08/02/22 21:46:03:130 GMT]  INFO util.PushPublishLogger: class com.dotcms.publisher.business.PublisherQueueJob : Status Update: Success
```
The bundle shows 'Success' even if all files fail to send. 

**Expected behavior**
In order to support SSE AES-256 encryption we need to send a header alongside the requests to the API, `x-amz-server-side-encryption`
We could add a configuration when setting up your bucket (credentials, name etc.) to enable this on buckets that require it. 

If there are no plans to support this encryption, then it should error out correctly and report that the bundle failed.

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21678?planning-poker) with Zenhub @victoralfaro-dotcms @freddyucv

**Comment by damen-dotcms** [comment]
Starting in Jan 2023, Amazon automatically encrypts all data in S3.

**Comment by freddyucv** [comment]
Now the SSE AES-256 encryption is the DEFAULT behavior so we don't need to  chance the bucket policy and add the header to each upload file request

<img width="868" alt="Screen Shot 2023-02-13 at 15 32 50" src="https://user-images.githubusercontent.com/10408015/218579437-3fe1c784-8bdb-451e-9893-8955cd44bbc8.png">
