### ISSUE TITLE
[WebP] : Default quality for WebP filter is breaking image file

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21694]
Related to ticket #21657

Reported via Support ticket: [106460](https://dotcms.zendesk.com/agent/tickets/106460)
Reproducible as of dotCMS 5.3.8.9, up to latest master (22.01)

When using the default quality value for the WebP filter, for example: `/dA/{SHORTY_ID}/fileAsset/image-file.png/70w/webp` , that is, without explicitly specifying the quality value, dotCMS is returning a broken "pixelated" image.

**To Reproduce**
1. Use the image attached in ticket #21657 , and upload it to your dotCMS instance.
2. Make sure that the image without filters is loading correctly. For example: `http://localhost:8080/dA/56763bd5f1/fileAsset/middle-donut-brand.png`
3. Apply the conflicting filters to the image, for example: `http://localhost:8080/dA/56763bd5f1/fileAsset/middle-donut-brand.png/70w/webp`
4. The image returns like this:
![broken](https://user-images.githubusercontent.com/8779585/153457140-64974290-fa41-4cbb-8cc4-d5994aa2946d.png)

**Expected behavior**
We need to determine what is causing the WebP filter to render a broken image.

**Additional context**
The only workaround so far is to stop using the WebP for the time being.

**Comment by wezell** [comment]
Additional Context:
The image breaks if you use the webp filter.  It works if you use the quality filter:

Broken:
https://demo.dotcms.com/dA/95e4f568cc79f63c9ca3c31f74323f1f/fileAsset/700w/webp

Working:
https://demo.dotcms.com/dA/95e4f568cc79f63c9ca3c31f74323f1f/fileAsset/700w/50q

**Comment by wezell** [comment]
I believe the issue is that the ShortyServlet is setting too many filters when a user passes `/webp`.  It should only run the `/webp` filter at the end.  We will also need to test with `/jpeg/` and  `/jpegp`

**Comment by wezell** [comment]
Looks like the `/jpeg/` and `/jpegp` filters are broken in the shorty servlet

**Comment by nollymar** [comment]
PR: #22042

**Comment by fabrizzio-dotCMS** [comment]
after applying the webP filter the image looks consistent
Tested with jpg and png files

**Comment by nollymar** [comment]
After several tests, I can confirm that filters are applied in the correct order. This card was also tested https://github.com/dotCMS/core/issues/20913

**Comment by bryanboza** [comment]
Fixed, tested again in release-22.06 // Docker // FF

**Comment by erickgonzalez** [comment]
This can't be backported to 5.3.8 and 21.06 LTS because it needs the changes from https://github.com/dotCMS/core/issues/20913
