### ISSUE TITLE
/dA requires a trailing slash to work

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21702]
When using the `/dA` asset path, we require a trailing slash for it to work, which should not be the case.  We should not need the trailing slash for `/dA` to work.

This does not work:
[https://dotcms.com/dA/9b1a1daa-683f-40b2-9fc4-4ad0e94a8a54/diagram1](https://dotcms.com/dA/9b1a1daa-683f-40b2-9fc4-4ad0e94a8a54/diagram1)

This works:
[https://dotcms.com/dA/9b1a1daa-683f-40b2-9fc4-4ad0e94a8a54/diagram1/](https://dotcms.com/dA/9b1a1daa-683f-40b2-9fc4-4ad0e94a8a54/diagram1/)

**Comment by dsilvam** [comment]
Passed Internal QA: Test with `http://localhost:8080/dA/2b100ac707/image` and `http://localhost:8080/dA/2b100ac707/image/` on starter data. Both working

**Comment by bryanboza** [comment]
Fixed, as @dsilvam told in the previous comment, after those changes both cases are working, with and without the `/` character. 

Tested on release-22.03 // Docker // MSSQL
