### ISSUE TITLE
When editing a piece of content, update the page title with the content title

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21701]
When editing multiple pieces of content in dotCMS in multiple tabs, every tab starts with "dotCMS Content Management Platform:". This makes it very difficult to know which tab is which when switching back and forth between them.

It would be helpful if when you open a piece of content, or navigate through the system we change the html page `title` dynamically based on what you are editing or doing, e.g. when editing content, update the title to either "new content" if the content has not been saved or to whatever the content title is, e.g. "My blog about dotCMS".  This would make the tabs more parseable.

![Screen Shot 2022-02-11 at 10 29 09 AM](https://user-images.githubusercontent.com/934364/153620152-5f740175-22ad-412c-a8dc-9f983224afb7.png)

Also, maybe when editing content, we should update the fav.icon to the icon for the content type you are editing?  Is that too much or would that be slick?

**Comment by wezell** [comment]
if it is a new contentlet, then we change it to `new contentType.name`

if it is an existing contentlet, we change it to `contentlet.getTitle()`

**Comment by alfredo-dotcms** [comment]
PRs:
core-web = https://github.com/dotCMS/core-web/pull/1903/files
core = https://github.com/dotCMS/core/pull/21790/files

**Comment by alfredo-dotcms** [comment]
Demo = https://monosnap.com/file/KkBuZw1z6GlpNGJHGn8datwXH3VWuO

**Comment by fabrizzio-dotCMS** [comment]
I couldn't get this to work with the latest master. I'll have someone else try ti on Monday

**Comment by fabrizzio-dotCMS** [comment]
We're missing this condition 
`if it is a new contentlet, then we change it to new contentType.name`
The content edition dialog show the CT but the page title does not 

Everything else seems alright

**Comment by nollymar** [comment]
**Core-web:** https://github.com/dotCMS/core-web/pull/1927

**Comment by fabrizzio-dotCMS** [comment]
Looks good.
