### ISSUE TITLE
When relating content, clicking anywhere on the content list should check the relate box

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21700]
When you are relating content and you click on the content in the listing screen, it should check the "relate" checkbox.

![Screen Shot 2022-02-11 at 10 06 14 AM](https://user-images.githubusercontent.com/934364/153616201-7d1ce3c1-5529-4f28-92be-1422db0af58e.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21722/files

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
