### ISSUE TITLE
Move EMA overwrite url plugin into core and support rewrites

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21713]
**Is your feature request related to a problem? Please describe.**
As a stakeholder, I want to move the move this plugin into core so we can have that functionality out of the box.

Also, we would like to include new functionality to allow dotCMS users to config and point different folders to specific EMA servers.

**Describe the solution you'd like**
In the plugin configuration where we set the string of the EMA server we need to support now a JSON object with the following format:

```json
{
    rewrites: [
        {
          source: '/:path*',
          destination: `https://my-old-site.com/:path*`
        }
    ]
}
```

1. Users can add as much as they needs
2. Fallback should be considered
3. Maybe we can follow the pattern match as the native browser: https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API#concepts_and_usage

**Additional context**
1. We need to update the documentation for this.
4. Plugin: https://github.com/dotcms-plugins/com.dotcms.ema-ovr

**Comment by jdotcms** [comment]
[PR](https://github.com/dotcms-plugins/com.dotcms.ema-ovr/pull/1/files) for plugin
