### ISSUE TITLE
UI: Type Error displays when uploading files via image fields 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#21715]
Discovered in ticket: https://dotcms.zendesk.com/agent/tickets/106562 v 21.04.06.4.
Recreated on local 21.06.4 and in current demo v22.02

When uploading an image via an image field, the following error displays when you select a folder and use the UPLOAD NEW FILE button.

The error:

TypeError:dijit.byId(...) is undefined

The error does not seem to affect the upload, but you must click on the error to dismiss it.

**To Reproduce**
1. Select a Content Type that contains an Image field.
2. Create a new contentlet
3. Click on BROWSE to select a file from your computer
4. Select a folder to upload TO on the left side of the modal window.
5. Click the UPLOAD NEW FILE button
6. Error is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/49727631/153946230-0e11b84a-7d32-4861-846e-780581c57ef7.png)

**Comment by erickgonzalez** [comment]
Able to reproduce only when the Dev Tools Browser Console is open

https://user-images.githubusercontent.com/5278970/159794592-6b1686a8-705f-4146-a620-bbf108fc1ccb.mov

**Comment by nollymar** [comment]
PR: #22125

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF. Now we are unable to reproduce
