### ISSUE TITLE
Update dotCDN to use JWT + lambda to proxy CDN requests and pass them to bunny.net

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21721]
Bunny.net is a great CDN solution that has one drawback for using it as our CDN.  As it stands right now, an account can only have 1 API key and we have to create a separate bunny account for each of our customers using it.  To work around this, need a proxy service that secretly stores that api key and which our plugin can call when doing API requests to bunny.   To do this, we can use signed JWT tokens to validate incoming requests and proxy them through to bunny.net.  We can do this in 3 steps.

1. we need to build a OSGI plugin "JWT Generator" that will generate a JWT token that we can use to auth incoming CDN requests. The JWT token would include in the claims:
   - PullZoneId
   - CDNHost

This JWT token should be signed by a private key that only we have.  

2. We then need to create a lambda that expects a JWT `Authorization: Bearer` header and that validates the JWT token.  If the token is valid, the lambda proxies the request to `bunny.net, with our bunny.net api authorization key. 

3. Finally, we need to update the dotCDN plugin to accept a JWT and the to use that JWT when making API requests - which would be calling our lambda to be proxied to bunny.

### More Information 
- https://www.jeremydaly.com/verifying-self-signed-jwt-tokens-with-aws-http-apis/

**Comment by prestonso** [comment]
Marking as closed per @wezell.
