### ISSUE TITLE
Content with 2 Relationship Fields of Same Type Also Shows Non-Available Languages

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21735]
**Describe the bug**
In the instance of a content type that has two relationship fields for the same content type, when relating the same content on each field the second relationship field shows both the language the content is in, as well as all languages that are available in the system as crossed out. This becomes a jarring UI experience when instances have a very large number of languages available. 
**To Reproduce**
1. Go to demo.dotcms.com
2. Created a content type with a title and two relationship fields, each field having a many to many relationship using the same content type
3. Create a contentlet of that type and use two of the same contentlets in each relationship field and one distinct in each. 

**Expected behavior**
You would not see languages crossed out even if it is content that is already existing in the other relationship field. 

**Screenshots**
![Screen Shot 2022-02-16 at 8 01 11 AM](https://user-images.githubusercontent.com/90852779/154310241-274077a3-b509-4d14-a01a-32490b3779f7.png)
![Screen Shot 2022-02-16 at 8 03 28 AM](https://user-images.githubusercontent.com/90852779/154310296-54178d18-1d8e-4308-a043-1523d50228d6.png)

**Desktop (please complete the following information):**
 - Version 21.06.6, 22

**Additional context**
As seen in a customer ticket: https://dotcms.zendesk.com/agent/tickets/106565

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21998/files

**Comment by fabrizzio-dotCMS** [comment]
Fixed the related items no longer appear crossed out. 
![Screen Shot 2022-04-25 at 15 59 25](https://user-images.githubusercontent.com/37148755/165182032-ee551597-b946-48ac-ab89-84dfabb7830e.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
