### ISSUE TITLE
We are not refreshing the site selector component when you add//remove sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21734]
When you add or remove any site. we are not refreshing the site selector component 

**To Reproduce**
- Login as admin
- Create a new site 
- Make sure the site selector component add the new site to the list 

**Expected behavior**
We need be able to add/remove sites and this should add or remove from this component 

**Desktop (please complete the following information):**
Tested on release-22.03 // Docker // FF

**Comment by nollymar** [comment]
**Internal QA:** Passed
<img width="842" alt="Screen Shot 2022-02-28 at 3 27 16 PM" src="https://user-images.githubusercontent.com/8741395/156053837-94009b26-1433-48e6-8bde-d2fff4ee75d9.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 // Docker // Chrome
