### ISSUE TITLE
Add form from content palette needs some help 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21747]
When you are editing a page and you D&D the forms content type to the container, we are displaying a pop-up that needs some styling help 

![image](https://user-images.githubusercontent.com/2641437/154719803-37f92686-ff82-44cd-9261-66c930d1868d.png)

**Desktop (please complete the following information):**
Tested on release-22.03 // Docker // FF

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1967

**Comment by fabrizzio-dotCMS** [comment]
yeap looks better now

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
