### ISSUE TITLE
ShowFields Variable Makes Related Contentlets Uneditable

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21748]
**Describe the bug**
When using the `ShowFields` field variable within a relationship field in a content type, that related content cannot be clicked into and edited.
**To Reproduce**

1. Go to demo.dotcms.com
2. Create a content type with a relationship field that uses the "ShowFields" variable and provide some values of the child content type fields for the value
3. Create a new contentlet with some related contentlets and publish, then try to click into the related content within the parent
4. See that you cannot click into the content to edit it

**Expected behavior**
You'll be able to click into the related content even when the parent content type uses the `ShowFields` field variable

**Screenshots**
![Screen Shot 2022-02-18 at 6 08 55 AM](https://user-images.githubusercontent.com/90852779/154730799-a68174f7-c40d-48d7-8eff-ef825c6392f7.png)

![Screen Shot 2022-02-18 at 6 07 58 AM](https://user-images.githubusercontent.com/90852779/154730808-f6a5c148-db6a-482d-b534-25448651d448.png)

**Desktop (please complete the following information):**
 - Version 21.06.6, 22

**Additional context**
As seen from a customer ticket here: https://dotcms.zendesk.com/agent/tickets/106596

**Comment by dsilvam** [comment]
Needs work:
Clicking on the rel fields is now properly redirecting to editing the related content, but 
after adding `profilePhoto` to Blog-Author field on Blog content type, the profile photo is not shown.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.03 // Docker // FF.  Now we are properly redirecting to the related content whrn you click in the relationship field
