### ISSUE TITLE
400 Bad requests (such as malformed URIs) do not make it past Tomcat and display a stacktrace in the browser

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21742]
**Describe the bug**
Bad requests do not make it past the tomcat server and generate a 400 error that puts a stacktrace into the users browser. This exposes some server information. Because they do not hit the web application, they do not utilize our custom error pages.

Reproduced on: 21.02
Related ticket: https://dotcms.zendesk.com/agent/tickets/106577

**To Reproduce**
1. Go to https://demo.dotcms.com/?search={ (copy and paste this, if you click it will encode the URI and not generate the error)

**Expected behavior**
The error page should not contain stack trace data or server information. This can be done by adding
```
<Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false"/>
```
to `server.xml`

**Comment by wezell** [comment]
This needs to be done in the tomcat repo and the docker repo.

See: #21849

**Comment by erickgonzalez** [comment]
another customer hitting this: https://dotcms.zendesk.com/agent/tickets/107009

**Comment by erickgonzalez** [comment]
Tomcat8 doesn’t have the ability to set errorCode via Valve, this feature is Tomcat9 https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Error_Report_Valve

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/tomcat/pull/27

**Comment by nollymar** [comment]
**Internal QA:** Passed

![Screen Shot 2022-09-02 at 10 56 09 AM](https://user-images.githubusercontent.com/8741395/188192796-d2793ea3-7b5e-4c9f-8006-f8bc5e484069.png)

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.09_845c64ab_SNAPSHOT // Docker // FF

To reproduce:
Delete everything from docker including volumes and compose up again

**Image reference**
![Screen Shot 2022-09-02 at 1 56 37 PM](https://user-images.githubusercontent.com/110418590/188227655-8300c92c-0dc6-41fe-8ad2-3da736c232b2.png)

**Comment by nollymar** [comment]
@josemejias07 @bryanboza I've updated the servers to the same docker image and they are working as expected: 
![Screen Shot 2022-09-02 at 3 45 29 PM](https://user-images.githubusercontent.com/8741395/188232873-f2fba242-758c-4656-9597-b3c7a096784d.png)
![Screen Shot 2022-09-02 at 3 45 47 PM](https://user-images.githubusercontent.com/8741395/188232913-2331b3eb-dae5-4124-883a-4a25ffdde68f.png)

**Comment by josemejias07** [comment]
**Approved** QA - Tested on 22.09_845c64ab_SNAPSHOT // Docker // FF

Testing in 
**http://localhost:8080/?search={**
