### ISSUE TITLE
Content objects passed to Workflow SubActions are not fully hydrated

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21741]
**Describe the bug**
When using a Velocity Script Actionlet subaction on a workflow, the `$content` object is not fully hydrated and is missing several fields:

- Relationships
- Categories
- Hidden Fields
- Site

In many cases it's possible to do a `$dotcontent.find` using the identifier after saving, however there are circumstances that someone may want to check these fields prior to a save and stop the workflow from completing at all.

Reproduced on: 21.02, 21.06

Related ticket: https://dotcms.zendesk.com/agent/tickets/106594

**To Reproduce**

1. Make a copy of the System Workflow and add a Velocity Script Actionlet subaction to the save action, above all other subactions (so it occurs before the contentlet is checked in)
2. Make the subactions code print out the values of the fields listed earlier
```vtl
$dotlogger.info("=====PRINTING VALUES OF FIELDS=====")
$dotlogger.info("$content.testRelationship")
$dotlogger.info("$content.testCategories")
$dotlogger.info("$content.testHidden")
$dotlogger.info("$content.testSite")
```
3. Create a content type with all of the listed fields. I called them `Test FieldType` when creating them to match the fieldvars in the earlier logging. The relationship field can be with any content type.
4. Open the logs to view, and create a version of that contentlet. The logs will print out:
```
$content.testRelationship
$content.testCategories
$content.testHidden
$content.testSite
```
Meaning this object is not fully hydrated with all relevant content information

**Expected behavior**
This object should be fully hydrated in case the user wants to make decisions on the action using them.

**Comment by wezell** [comment]
In an incoming contentlet, you would get the new relationships/categories like this:
```
$workflow.contentletDependencies.relationships
$workflow.contentletDependencies.categories
```
