### ISSUE TITLE
Site or folder field misbehaving

### ISSUE THREAD

**Issue by noud** [dotCMS/core#21759]
dotCMS Platform 21.11 (Panther / November 16, 2021)

i create a content type with the first field a site or folder field.

now if i create content and put a value other then default in the site or folder field,
that content doesn't show up anymore in the backend UI after i save and publish the content
and when i want to re-edit that content..

further more $content.site.hostName is empty.

further more if i create content with the site or folder field to default,
save and publish and re-edit the content again and put another value in 
the site or folder field, this is not picked up it stays default.

**Comment by wezell** [comment]
If we can reproduce this, I would like to write a broken test and then fix it in code.

**Comment by noud** [comment]
the content does show in the correct place.

but still $content.site.hostName is empty.

and further more if i create content with the site or folder field to default,
save and publish and re-edit the content again and put another value in
the site or folder field, this is not picked up it stays default.

**Comment by wezell** [comment]
Possible dupe: #21772
