### ISSUE TITLE
SASS files that worked in 20.10 don't work in 21.06

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#21768]
## Describe the bug

* Initial customer report in the following ticket: https://dotcms.zendesk.com/agent/tickets/105703
* Additional information (including files to reproduce) available in the following ticket: https://dotcms.zendesk.com/agent/tickets/106643

Customer reported that they have SASS code which worked in their 20.10 instance, but causes errors when using the same exact files in 21.06.

## To Reproduce

Please see the second linked ticket (106643, above) for details on how to reproduce.

## Expected behavior

SASS files which worked in earlier dotCMS releases should continue to work without changes in later dotCMS versions (at least as long as we continue to support SASS using the same SASS library [libsass]).

## Desktop (please complete the following information):

 - OS: dotCMS Cloud customer, on the latest infrastructure stack
 - Browser: N/A (Server-side)

## Additional context

* The customer builds their SASS code on top of the Foundation SASS framework.
    * The error is being caused when including just some of the Foundation framework includes - without any of the customer's custom SASS code on top of it.
        * Please see the second linked ticket (106643, above) for details.
* Libsass is deprecated, but it's still in dotCMS, and still supported, even in master.
    * Since we haven't changed the version of libsass we ship with, it appears something else in dotCMS has changed which prevents these files from compiling properly in newer versions.

**Comment by wezell** [comment]
will be fixed in #22196
