### ISSUE TITLE
Remove the double save of content when calling checkin

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21771]
When saving a new contentlet, we currently persist the contentlet twice when we save the contentlet.  We need to save the contentlet once to avoid the performance penalty of saving the content twice.

**Comment by nollymar** [comment]
PR: #21805

**Comment by fabrizzio-dotCMS** [comment]
> Possibly this issues: #21759 #21373

 #21759 I was able to modify the site and folder field and the content would appear under a different site/folder upon modifying the field
#21373 seems to work fine for me.

**Comment by bryanboza** [comment]
Fixed, tested on release 22.04 // Docker // FF
