### ISSUE TITLE
Add Ability to Create Unique Field Values Per Site

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21781]
**Is your feature request related to a problem? Please describe.**
In some cases, when customers wish to use a global content type that contains some unique field, they would like that field to be unique only for the Host they are creating on at the time, rather than globally. Currently, if marked unique the field must be unique across all hosts. 
**Describe the solution you'd like**

Change the existing Unique property to "Unique across sites" and add a new property "Unique per site".

**Additional context**
This has been requested by a customer: https://dotcms.zendesk.com/agent/tickets/106676

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/21781?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/21843

**Comment by dsilvam** [comment]
Passed Internal QA. Behaving as expected for each case (true|false) for property `unique_per_site`

**Comment by wezell** [comment]
Sorry guys, I got it wrong, the variable needs to be in camelCase, e.g. `uniquePerSite`

**Comment by bryanboza** [comment]
We need to respect the camel case, we need some work here

**Comment by dsilvam** [comment]
Passed Internal QA. Renamed property working as expected. Tested via Docker.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF. Now we are respecting the camel case
