### ISSUE TITLE
Add portlet to menu from content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21788]
**Is your feature request related to a problem? Please describe.**
To add a [custom content tool](https://dotcms.com/docs/latest/custom-tool-groups) we have to go to:

```
Settings > Roles and Tools > and like 3-4 more clicks
```

https://user-images.githubusercontent.com/751424/156370074-3300ed21-6967-4384-973b-199e0685ba00.mp4

**Describe the solution you'd like**
We can add one button (shortcut) to the content type process of create or edit to add the custom tool with one click.

**Additional context**
The idea is to improve the UX on this process and attempt to make users to use more this feature because it is compelling to put  content closer to content creators.

- [Figma Prototype](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=2322%3A33363&node-id=2322%3A33364&viewport=383%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=2322%3A33364)
- [Figma File](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2322%3A33363)

**Comment by fmontes** [comment]
Do we need an endpoint for this?

**Comment by wezell** [comment]
waiting on #21789
