### ISSUE TITLE
Sanitizing file name

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21791]
We need to sanitize file names and remove invalid characters as files are ingested into dotCMS.

**Comment by wezell** [comment]
See Hotfix plugin for 5.1.6+

https://github.com/dotCMS/patches-hotfixes/tree/master/com.dotcms.security.multipartrequest

**Comment by ian-b-cooper** [comment]
Quality control tested by Non-Dev. Fix confirmed

**Comment by freddyucv** [comment]
**Pass Internal QA**: Tested with

`curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/cont,  hostFolder:'default',  title:'PomPom.png',  fileName:'Pom<Pom.png'};  type=application/json"  -F "file=@../../../../../../../Users/freddyrodriguez/Downloads/Pom<Pom.png;  type=application/png"`

With THROW_ON_BAD_FILENAMES equals to true, I got the "... Invalid filename uploaded : Pom<Pom.png"  Exception in the file log and the HTTP response was 400.

With THROW_ON_BAD_FILENAMES equals to false, I did not get any exception, the File was created in dotCMS and the HTTP response was 200

**Comment by bryanboza** [comment]
Fixed, tested on release 22-03 // Docker // FF
