### ISSUE TITLE
Add a UI to content types to add it as a custom content tool

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21797]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to quickly add content types as custom content tools to the menu.

**Describe the solution you'd like**
Add an option to the `...` button in each row of the content type list.

https://user-images.githubusercontent.com/751424/156370074-3300ed21-6967-4384-973b-199e0685ba00.mp4

**Describe alternatives you've considered**
Other way will be while creating / editing the content type (in the dialog) but we'll work on that in a different issue.

**Additional context**
- [Figma Prototype](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=2322%3A33363&node-id=2322%3A33364&viewport=383%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=2322%3A33364)
- [Figma File](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2322%3A33363)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1955/files

**Comment by fabrizzio-dotCMS** [comment]
There are 2 issues here: 

1. If I create two content tools of the same Content-Type (each one using a different Data view: List, Card) 
 Only the one created to use the **List** Data view shows the existing elements.
 
https://user-images.githubusercontent.com/37148755/169389437-14c0c1a9-7107-4b94-b881-f4d48d5a42d1.mov

2. Once the Content-tool is created and added to a group menu.  It will become visible only if the Group menu is currently expanded. If the elements get added into a menu group that is collapsed it won't show until the entire page is reloaded. 

https://user-images.githubusercontent.com/37148755/169390385-984580b6-d8b0-40bd-a920-38db3ee9540a.mov

**additionally to that according to the video originally posted here the group menu where the element got added should be expanded to reveal the new addition.**

**Comment by fabrizzio-dotCMS** [comment]
- I was able to confirm that the new custom tool groups added manually will appear upon calling 

    http://localhost:8080/api/v1/menu
    After flushing the cache. We need to add an invalidation after having added new tool groups.

**Comment by fabrizzio-dotCMS** [comment]
new PR https://github.com/dotCMS/core/pull/22284

**Comment by alfredo-dotcms** [comment]
core-web PR: https://github.com/dotCMS/core-web/pull/1995/files

**Comment by nollymar** [comment]
**Internal QA:** Needs work 

The issues reported by @bryanboza were fixed. However, when I add a custom tool selecting Card View, I get a blank page


https://user-images.githubusercontent.com/8741395/172255255-081b1a29-0ec3-4009-a42c-fbd0221013d6.mov

**Comment by nollymar** [comment]
**Internal QA:** Passed

Apparently, there was an issue packaging the webcomponents library in the release and it was causing some side effects. Now, it works as expected.

**Comment by bryanboza** [comment]
Fixed, a new improvement reported on #22411
