### ISSUE TITLE
Fix dotcms library page api

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21799]
**Describe the bug**
When a developer uses the `get` page method of the library and pass the `language` is not picking up the language variable.

It must do a request with the url like `/api/v1/page/json/index?language_id=2` but is doing `/api/v1/page/json/index`

**To Reproduce**
I created a little demo here: https://codesandbox.io/s/weathered-cloud-2h10j4?file=/src/App.tsx

**Expected behavior**
This is only happening with the latest version `0.0.18`.

**Additional context**
This api lives here `libs/dotcms/src/lib/api/DotApiPage.ts`

We are using a [custom http client](https://github.com/dotCMS/core-web/blob/5a56251b636fc2d7a18b2d9da9f9b453eb6399d3/libs/dotcms/src/lib/utils/DotCMSHttpClient.ts) I'm not sure if that's a good idea or if we need a bigger refactor.

This http client is used by other classes so any changes here can break other methods.

**Comment by hmoreras** [comment]
The call to the endpoint should be with the `params` attribute: 

`dotcms.page
  .get({
    url: "/index",
    params: { language: "2"}
  })`

**Comment by fmontes** [comment]
We need to update the docs and the example (if any) to use the params correctly.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/22492
