### ISSUE TITLE
Next.js example detail blog page not working

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21806]
**Describe the bug**
When users click in any of the blog to go to the detail page it always goes to the same: "French Polynesia Everything You Need to Know"

**To Reproduce**
1. Run the project
2. Go to http://localhost:3000
3. Click in any blog post but "French Polynesia Everything You Need to Know"
4. See how it shows "French Polynesia Everything You Need to Know"

**Expected behavior**
It should show the blog detail of the post you clicked.

**Screenshots**
<img width="1954" alt="Screen Shot 2022-03-03 at 7 06 13 AM" src="https://user-images.githubusercontent.com/751424/156570631-705a7e80-ba6b-4be0-a27e-7037236f7e7e.png">

**Additional context**
The problem seems to be with the GraphQL query we are doing is not picking up the `urlTitle` we pass.

**Comment by oidacra** [comment]
Used `query: +urlmap:/blog/post/${slug}`, instead `query: +Blog.urlTitle_dotraw:${slug}`

**Comment by oidacra** [comment]
Finally we will use: 
`const showPreviewPosts = (preview) => {
  return (preview === true) ? '+working:true +deleted:false' : '+live:true +deleted:false'
}`

PR: https://github.com/dotCMS/next.js/pull/1
