### ISSUE TITLE
Render the new block field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21808]
**Is your feature request related to a problem? Please describe.**
After https://github.com/dotcms/core/issues/21935 we now need to update the render of the block detail page.

**Describe the solution you'd like**
- Make sure all the blocks looks good
- Link the related contentlets to their respective pages in `demo.dotcms.com`
- Images should work as expected and use the dotCMS image API

⚠️ If you find any difficult by implementing this, please let everyone know because the idea is that this is easy to do for our customer.

**Comment by fmontes** [comment]
Hold on this one while we update the block editor field.

**Comment by oidacra** [comment]
New Block editor content rendered and styled with prose (tailwind)
PR: https://github.com/dotCMS/next.js/pull/1
![Screen Shot 2022-04-19 at 3.01.36 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/9d487d59-f7f6-43ae-9a66-ca3fe622ecf8)
