### ISSUE TITLE
Limit of 250 Widgets and Forms in Content Selector Popup

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21811]
Customer issue: https://dotcms.zendesk.com/agent/tickets/106701

**To Reproduce**
1. Create over 250 widgets (the 251 lets called "z test widget")
2. Go To Browser Portlet
3. Edit Any Page
4. Click over the + button in a container
5. Select Widget
6. Search for the widget (z test widget)

**Expected behavior**
All widgets/forms should be loaded to the selector.

The issue is this line over here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/ng-contentlet-selector.jsp#L55 the limit is set to 250 and should be -1 (so no limit).

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/21811?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by victoralfaro-dotcms** [comment]
![image](https://user-images.githubusercontent.com/64026161/159585735-cbd0eaae-f72e-478d-8f54-ec5b959b0e6f.png)

![image](https://user-images.githubusercontent.com/64026161/159584842-8af5b5e2-681c-40d3-a81c-f7c5fa5b3504.png)

![image](https://user-images.githubusercontent.com/64026161/159585848-0c4babff-a3a2-49e5-80ce-60e320bdca0c.png)

![image](https://user-images.githubusercontent.com/64026161/159585887-b1f6fa9b-1942-45fd-b3a9-096b9e14094d.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
