### ISSUE TITLE
Reload contentlet on edit using #editContentlet macro

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21818]
**Is your feature request related to a problem? Please describe.**
In edit mode, when you edit a contentlet and save (or publish) you can see the new content in the page without having to reload.

If you edit a piece of content but using the macro `editContentlet($inode)` it doesn't refresh the content.

**Describe the solution you'd like**
It must refresh the content, regardless of what you use to edit it.

**Additional context**
To re-render a piece of content, we use an endpoint that take the container and the contentlet and give us back the HTML that we just replace in the DOM.

When we edit the contentlet, normally we look for the parent container. We do that [here](https://github.com/dotCMS/core-web/blob/master/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/dot-edit-content-html/dot-edit-content-html.service.ts#L186).

This works when we edit a contentlet in the structure is `Container > Contentlet`.

But when we edit a contentlet using the macro `editContentlet($inode)`, that macro could be in for example a widget (like in the blog listing page in full starter) so that structure is like:

`Container > Widget (which is also a contentlet) > Contentlet`

So, we end up passing to the endpoint the final contentlet when we should pass the widget one.

**To fix this,** we need to look if the contentlet we are editing is inside another contentlet we should pass the parent contentlet.

This issue is related to https://github.com/dotCMS/core/issues/21670

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/22011

**Comment by fmontes** [comment]
Had to revert this because of this: https://github.com/dotCMS/core/pull/22233

**Comment by hmoreras** [comment]
move the delay to the angular side, PR: https://github.com/dotCMS/core-web/pull/1989

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
