### ISSUE TITLE
Allow PP filters to be added/updated via the UI or a REST call

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21823]
**Is your feature request related to a problem? Please describe.**
Currently the only way to list PP filters is by directly playing the updated YML files into the PP filter directory. This adds unnecessary complexity to updating these filters, especially for cloud customers as they need to engage support for updates to filters.

**Describe the solution you'd like**
While having a UI that allows users to create/configure PP filters directly would be ideal,  it is a complex thing to add.

Allow users to perform CRUD operations on the YML files, either via the backend or via a REST call. Also allow them to download their current configuration, as they need to know what they are working with.

The following GoogleDoc created by Jonathan: https://docs.google.com/document/d/1sbrX3711dsQe2t1U5snnuFpqMIQ3jaxiSmKEwrJZT1Q has all the details for every action that can be executed on Push Publishing Filters.

**Comment by wezell** [comment]
PR: #21837

**Comment by jcastro-dotcms** [comment]
As per requirements established in this ticket: https://github.com/dotCMS/core/issues/18715 - PP Filters: Allow users to specify the order filters appear in the list

> ### Technical Approach
> 
> * Add an "order" property (integer) to the PP filter .yml file.
> * If an "order" property exists in the file, set the order value to that number.
>     * If no "order" property exists in the file, set the order value to some large number (so these get sorted last).
> * Sort the filters in the list based on the order value.
>     * If multiple filters have the same "order" value, sort them in alphabetical order at the appropriate point in the list.
> 
> So in summary, if the filter has no "order" property then treat is as having an order of 10000 or something like that, and then make the sort order basically order, filterName.


Right now, the PP Filters are not being returned in alphabetical order. This needs to be fixed.

**Comment by bryanboza** [comment]
Fixed, tested adding new filter from the REST API call, and this is working as expected, also the postman test are running and passing
