### ISSUE TITLE
UI: Create content type modal needs some styling help to show the required license message 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21839]
When you are using the community edition and you try to create a new content type, we are showing a message regarding some functionality that is just for EE editions. But we need some styling on this modal to show that message 
![image](https://user-images.githubusercontent.com/2641437/157555847-62b36e02-4237-466b-a1b5-e268ad173a75.png)

**To Reproduce**
- Login 
- Make sure you don't have a valid license in your instance 
- Try to create a new content type

**Expected behavior**
We need a better UI on this modal, specially to show the license message 

**Desktop (please complete the following information):**
Tested on release-22.03 // Docker // FF

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1945

**Comment by fmontes** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/751424/162491107-e3368d99-7451-4884-ad29-092313f230ed.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
