### ISSUE TITLE
[Static Push] Removing a Page removes all files related to the page, not only the page

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21832]
If you do a Static Push and then Remove (via push) any page all the files that the page needs to renders successfully (images, CSS, etc) are removed.

**To Reproduce**
1. Setup AWS S3 Env
2. PP the index page
3. Create another page that also uses the Default Template (same that index page uses).
4. Push this new page
5. Check on your S3 server the pages(index and the created one) renders (also check the images and CSS).
6. Remove (via PP) the created page.
7. Check the index page, all images are now 404 and also the CSS is missing.

**Expected behavior**
Related files (images/CSS) shouldn't be removed since could be used by other pages.

Customer ticket https://dotcms.zendesk.com/agent/tickets/106677

**Comment by dsilvam** [comment]
Passed Internal QA: Followed described steps and the index page is left intact.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
