### ISSUE TITLE
Need improve the error message when you type something wrong adding a new field true/false

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21840]
When you are adding a new filed (Radio // Select) and set the true/false validation,  and then you type something wrong in the value, we are showing an error related to the JSON object, we need a better and more specific error here
![image](https://user-images.githubusercontent.com/2641437/157557446-7f5c98db-4324-48f3-8087-fec6ea3283a9.png)

**To Reproduce**
- Login as admin
- Crete a new content type 
- Add a select field selecting the true/false validation 
- Add this to the value field ( 1|test )
- Try to save it 

**Expected behavior**
We need a better error here and come back to the add field window after the error 

**Desktop (please complete the following information):**
Tested on release-22.03 // Docker // FF

**Comment by oidacra** [comment]
We need to improve the backend message(more clear) and add the error type, to show the message in the frontend. @fmontes
