### ISSUE TITLE
Security headers not applied consistently after tomcat configuration change

### ISSUE THREAD

**Issue by Jaffacakes82** [dotCMS/core#21842]
**Describe the bug**
Updating the tomcat configuration to enable HTTP security headers for dotserver (version 5.2.8.4) does not apply these headers unilaterally across resources that dotCMS serves.

**Expected behavior**
Security headers applied to all resources that dotCMS serves.

**Screenshots**
**No headers on root resource:**
<img width="394" alt="Screenshot 2022-03-10 at 13 59 11" src="https://user-images.githubusercontent.com/4850159/157678524-8c447bc1-df3e-45fc-a01d-c86858ddf7ac.png">

**Security headers on some resources:**
<img width="400" alt="Screenshot 2022-03-10 at 13 57 42" src="https://user-images.githubusercontent.com/4850159/157678544-710bc7d0-a7b0-4704-8fb6-c2c581e4a35e.png">

**Desktop (please complete the following information):**
Chrome 99.0.4844.51

**Additional context**

**Comment by wezell** [comment]
Jeff:

Work has been done here since v.5.2.8.  I would suggest upgrading to a newer LTS version.  If that is not possible, I would suggest writing a quick interceptor plugin that can add the headers you are looking for.

If you try against demo.dotcms.com, you get:

```sh
curl --head https://demo.dotcms.com
HTTP/1.1 200
Strict-Transport-Security: max-age=3600;includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
x-dot-server: fb7d0d056b13|2fbe5a703f
Set-Cookie: JSESSIONID=C52DB76CE311A63DCAB66199A3859CDA; Path=/; Secure; HttpOnly; SameSite=Strict
Set-Cookie: opvc=53105b1e-d9fe-4e91-88d0-b422046cade7; Path=/; Secure; HttpOnly; SameSite=Strict
Set-Cookie: sitevisitscookie=1; Max-Age=153792000; Expires=Sat, 23-Jan-2027 14:16:29 GMT; Path=/; Secure; HttpOnly; SameSite=Strict
Set-Cookie: dmid=2d6d5ebc-3b37-48e4-8056-462446ff71b8; Max-Age=153792000; Expires=Sat, 23-Jan-2027 14:16:29 GMT; Path=/; Secure; HttpOnly; SameSite=Strict
Cache-Control: max-age=0
vary: accept-encoding
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 10 Mar 2022 14:16:29 GMT
Connection: close
```

And on an asset:
```bash
curl --head https://demo.dotcms.com/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/270w/50q/diving.jpg
HTTP/1.1 200
Strict-Transport-Security: max-age=3600;includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
x-dot-server: fb7d0d056b13|2fbe5a703f
Content-Disposition: inline; filename="diving.jpg"
Expires: Fri, 10 Mar 2023 14:18:13 +0000
Cache-Control: public, max-age=31536000
Last-Modified: Thu, 10 Mar 2022 12:05:17 +0000
ETag: W/dot:b77151f2-7206-4b03-862d-68217432d54d:1646913917000:10684
Accept-Ranges: bytes
Content-Type: image/webp
Content-Length: 10684
Date: Thu, 10 Mar 2022 14:18:12 GMT
Connection: close
```

**Comment by Jaffacakes82** [comment]
Thanks @wezell. Do you know if we get this capability by upgrading to 5.3.8? Trying to reduce scope for major breaking change.

**Comment by wezell** [comment]
Joe: 

I always feel like customers make a mistake - out of an abundance of caution or for whatever reason - not upgrading to the latest LTS version.  It seems like a lot of effort and time to spend to still be a year and a half behind.  My recommendation is that if you are going to take the time upgrade, upgrade to the latest version (whatever it is) so you aren't in a similar position a year from now.

If you are concerned about breaking changes, I would say try updating to the latest version and if a breaking change becomes a blocker for you, the first thing to do is communicate about it with us and see if there are valid workarounds or other options.  Only then consider trying a 5.3.8 upgrade to see if the upgrade is any better.

My .02 :)
