### ISSUE TITLE
Unable to save content of a Widget with WYSIWYG Code view

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21855]
**Describe the bug**
We're unable to save the content of a Widget that has some WYSIWYG as Code View.

**To Reproduce**
1. Import the bundle attached (this include the Widget Content-Type) [widget-01FY6Z8X3X666KDTAPVX7WJ5SG.tar.gz](https://github.com/dotCMS/core/files/8255330/widget-01FY6Z8X3X666KDTAPVX7WJ5SG.tar.gz)
2. Try To add new content, just fill the required fields and the WYSIWYG change them to CODE.
3. You'll see an error at UI and in the logs.

I've gotten 3 diff errors on the logs but at the end the Caused by is all the same `value too long for type character varying(255)`
https://gist.github.com/erickgonzalez/e15193ac369511a556a2e7962f272fca
https://gist.github.com/erickgonzalez/cb850ea8dea47d3de65d0d60925c0d97
https://gist.github.com/erickgonzalez/479cf0cec7ecc970f5ae7238fd0218f3

**Expected behavior**
Should be able to create/edit content even if the WYSIWYG is in Code view.

**Workarounds**
There are 2 workarounds:
- Left the WYSIWYG View as WYSIWYG
- Uncheck the Toggle Editor in each Text Area

**Additional Info**
I was able to reproduce this on demo (22.03) and 5.3.8.9 LTS.
Customer ticket https://dotcms.zendesk.com/agent/tickets/106784

**Comment by waqasakramdot** [comment]
Another Ticket: https://dotcms.zendesk.com/agent/tickets/111150

**Comment by zJaaal** [comment]
## Passed Internal QA

Tested on master branch.

### Screenshot
https://github.com/dotCMS/core/assets/63567962/3ea9a577-bbbc-4f4b-a158-d5b0b00cd57d

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_dc3cb0b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
