### ISSUE TITLE
Skip SYSTEM_TEMPLATE

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#21862]
On the template portlet list, we need to filter the template with the identifier: SYSTEM_TEMPLATE

this is ready only template, so shouldn't be on the templates screen, but should be on the edit mode when creating a new page.

This is the PR with the BE changes:
https://github.com/dotCMS/core/pull/21494/files

https://user-images.githubusercontent.com/934364/163397202-d103c00a-e65b-43d4-84b7-4083a699ec6c.mp4

**Comment by wezell** [comment]
Also, the system template should never be added to a bundle or pushed.

**Comment by fmontes** [comment]
This is fixed by: https://github.com/dotCMS/core/issues/21853
