### ISSUE TITLE
Static Push is not pushing url map content page

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21863]
**Describe the bug**
When doing Static Push of a full site isn’t pushing the pages that are built with URL map content.

**To Reproduce**
1. Upload the following bundle: 
[test_Static_Push_Detail_Page-01FY9QEKD5ZPRA2SDQDW22AE40.tar.gz](https://github.com/dotCMS/core/files/8273894/test_Static_Push_Detail_Page-01FY9QEKD5ZPRA2SDQDW22AE40.tar.gz)
2. Configure AWS S3 Push.
3. Static Push the site, from the Sites Portlet.

**Expected behavior**
After finishing the push, static pages of the content should be created.

**Workaround**
After finishing pushing the site, go to the Search Portlet and push the content explicitly, static pages of the content are created.

**Additional context**
Customer ticket: https://dotcms.zendesk.com/agent/tickets/106799
Tested in demo (22.03) and 21.06.7

**Comment by dsilvam** [comment]
Passed Internal QA: Correctly pushing URL-mapped content pages to AWS S3

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF

**Comment by erickgonzalez** [comment]
Backported with this other https://github.com/dotCMS/core/issues/21613
