### ISSUE TITLE
Drag handler appears outside the editor when first load

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#21860]
Is your feature request related to a problem? Please describe.

Drag handler appears outside the editor.

<img width="1638" alt="drag-handler-overflow" src="https://user-images.githubusercontent.com/72418962/158633505-dbb3328a-37a2-4803-9e5d-5106e2b4386d.png">

Describe the solution you'd like
We need to hide the handler when the block editor is first loaded.

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by rjvelazco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/21860?planning-poker) with ZenHub @hmoreras @oidacra

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1925

**Comment by fmontes** [comment]
Fixed but: https://github.com/dotCMS/core/issues/21897
