### ISSUE TITLE
CORS configuration based on sites and used aliases

### ISSUE THREAD

**Issue by CyberDracula** [dotCMS/core#21876]
Currently CORS can be set only by resource (java class) or a default one:
[https://dotcms.com/docs/latest/cors-header-configuration](https://dotcms.com/docs/latest/cors-header-configuration)

But, in a larger implementation you will want to use dotCMS on multiple sites. So the need of a more versatile CORS configuration is a must.

We should have a way to add CORS based on the origin. Each site configured can have a dynamic `access-control-allow-origin` based on the given hosts/aliases.

Example: 
In dotAdmin > Configuration > Sites we have 3 sites:

1. `Host = site.net` and `Aliases = main.alternative.net, www.site.net` 
2. `Host = other.site.net` and `Aliases = other.alternative.net, www.other.site.net`
3. `Host = something.web.com` and `Aliases = www.something.web.com`

So dotCMS API should respond with CORS `access-control-allow-origin` for this hosts & aliases based on 'Origin' in the request. If not in the list we could go to default configuration `api.cors.default.Access-Control-Allow-Origin`.
Same should apply to all other CORS headers. 

![exmp_cors_dotcms](https://user-images.githubusercontent.com/1976475/159369067-c05dd549-0ad8-4f8a-8877-4fd777930723.png)

**Comment by wezell** [comment]
@CyberDracula thanks for the idea.  I wanted to share that we also have this plugin that lets you set headers per host:

https://github.com/dotcms-plugins/com.dotcms.headerapp

**Comment by CyberDracula** [comment]
> 

Thanks for the plugin URL, didn't know about it. It can help on other headers (like security) but I've done a quick test and it doesn't seem to overwrite the default CORS settings added in `dotmarketing-config.properties`.
