### ISSUE TITLE
OSGI restart needs to be cluster aware

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21882]
When uploading an OSGI plugin, only one server in a cluster should read the uploaded plugin, move it to `felix/load` and re-write the `osgi-extras.conf`.   After that is done, when we restart the osgi framework, we need to restart it on all the servers in the cluster so they pick up the changes in `osgi-extras.conf`.

Additionally, when a user clicks the "restart framework" button, it should send a cluster message and restart it across all nodes in the cluster.

**Comment by fmontes** [comment]
Advace QA test need it.

**Comment by jdotcms** [comment]
In order to test you may want to use a docker test cluster example.
As soon as you have the cluster running.
Restart the Osgi Framework in one node will restart in a few seconds the Osgi in the other node.
