### ISSUE TITLE
Template show archive not working

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21885]
**Describe the bug**
When you attempt to show archive templates is not working

**To Reproduce**
1. Go to Template and create at least 2
2. Archive a template
3. Click on “Show Archive” checkbox
4. See error.

**Expected behavior**
It must show list all the templates including archives.

**Screenshots**
https://images.zenhubusercontent.com/3729629/5f3d1adb-138b-49fb-8c23-a1ee58cd9741/template_archive.mp4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dsilvam** [comment]
Passed Internal QA: "Show Archived" working as expected.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF and now I'm unable to reproduce after the changes.

**Comment by swicken-dotcms** [comment]
Related Ticket: https://dotcms.zendesk.com/agent/tickets/108084

**Comment by erickgonzalez** [comment]
Only applies to 22.03 LTS
