### ISSUE TITLE
Problems creating containers

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21899]
Related to #21883 

We are getting some problems when you try to add a new container to the system 

- We are getting a random error the when the instance is totally fresh and you try to add a block editor to the container
![image](https://user-images.githubusercontent.com/2641437/160199624-3ff1c032-a0d0-46ad-8d5a-80273597eb17.png)

**To reproduce:** 
- In a fresh install try to create a new container that includes the block field 

We have a NPE in the log when you save a new container
Here the log: https://gist.github.com/bryanboza/53878e9e74123d4deceb41029c8e1c7b

**To reproduce:** 
- Just need to create a new container and save it 

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/21883#issuecomment-1079428888_

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/21921)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
