### ISSUE TITLE
Tippy is showing unnecessarily

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21897]
**Describe the bug**
The bubble menu and drag handler is showing unnecessarily

**To Reproduce**

https://user-images.githubusercontent.com/751424/160023971-d9af7951-df76-493c-a59d-be0223283efa.mp4

**Expected behavior**
1. Make sure bubble that doesn't show just on load
2. Hide bubble on scroll.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
