### ISSUE TITLE
Unordered and ordered list not showing bullets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21894]
**Describe the bug**

**To Reproduce**
1. Add a block field 
2. Create a content 
3. Add list block
4. See error.

**Expected behavior**
It must show number or bullet accordingly.

**Context**
We need to make sure that none of the external styles affect the block editor blocks.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/570fbdcebf93871ccd997222/42a925b6-fd46-4f5b-9d13-e2c5b3eba038)

**Comment by bryanboza** [comment]
Still happening for me. Tested on release-22.04 // Docker // FF 

Also, this needs internal QA before sent to the QA project.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
