### ISSUE TITLE
Tags under specific site aren't listing

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21904]
**Describe the bug**
If you create some tags under a specific site, that site Tag Storage is set to itself, when you create content and try to list those tags aren't showing.

**To Reproduce**
1. Create a blank site
2. Set the Tag Storage of that site to itself.
4. Create a Content-Type that lives under the new site, with text and a tag field.
5. Navigate to the Tags Portlet.
6. Add some tags that will live under the new site.
7. Create content and try to list the new tags that live under the specific site.

https://user-images.githubusercontent.com/5278970/160436470-6354419a-2112-48bd-a1ed-42d1e1633a2d.mov

**Workaround**
Add a site/folder field and select the specific site, that way the tags will be listed.

**Expected behavior**
I think should be like this:
* If the Content-Type lives under the specific site and there isn't a site/folder field, we should be able to list tags under it and also global ones.
* If the Content-Type lives under the System Host and there isn't a site/folder field, we should be able to list only global tags.
* If the Content-Type lives under the specific site or System Host and there is a site/folder field, we should be able to list tags under the site that is selected in the field and the global ones.

**Additional context**
Customer ticket: https://dotcms.zendesk.com/agent/tickets/106884
Reproducible in 21.06.7 LTS and 22.03.

**Comment by wezell** [comment]
It seems that the TagAjax is not respecting the host that is sent with the tag lookup.

**Comment by wezell** [comment]
It would be ideal if we generate new methods on the `TagResource` to replace the `TagAjax`, which should be depreciated.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/21997

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on relase-22.06 // Docker // FF
