### ISSUE TITLE
Remove `calendar_reminder` table 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21917]
`calendar_reminder` table should be removed from all databases, including all its references in code.

**Comment by alfredo-dotcms** [comment]
some properties files still have reference to that table
![image](https://user-images.githubusercontent.com/37185433/168646320-a85e6e07-8381-4961-bc56-2c7a8ce3e6f6.png)

![image](https://user-images.githubusercontent.com/37185433/168646421-ba52e08d-7d19-47ea-98e2-e3252ad15cf4.png)

**Comment by fabrizzio-dotCMS** [comment]
new PR https://github.com/dotCMS/core/pull/22235
