### ISSUE TITLE
Problems editing pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21922]
We are getting some problems when you try to edit some pages, now we are requesting a EE license to edit some page 
![image](https://user-images.githubusercontent.com/2641437/160886467-a9e8351c-d9f9-4a41-b068-faa209a291d9.png)

Also, if you apply  the license and then try to edit the page, we get an `undefined` error and we are unable to edit the page 
![image](https://user-images.githubusercontent.com/2641437/160886635-3fe4d181-c4dd-4e1a-8432-558c1e27c9df.png)

**FYI: No errors in the log file** 

**Expected behavior**
We need to be able to edit pages without problems in both versions community and enterprise 

**Desktop (please complete the following information):**
Tested on release-22.04 // Docker

**Comment by dsilvam** [comment]
Passed Internal QA: Tested with Contact-us index page. Able to edit it with both Enterprise or Community.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
