### ISSUE TITLE
dotCDN does not invalidate /index pages

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21920]
If you have a site running off a CDN and you edit an index page, say, `https://mysite.com/about-us/index`, dotCDN invalidates ONLY that path `https://mysite.com/about-us/index`.  It does not invalidate the folder version of that page path, e.g. `https://mysite.com/about-us/`

When invalidating a page in dotCDN, we need to check if it is the index page and if so, also invalidate the folder path.

**Comment by erickgonzalez** [comment]
This is already merged in dotcdn repo
