### ISSUE TITLE
PullRelatedField is not pulling the content in any order

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#21929]
**Describe the bug**
The `$dotcontent.pullRelatedField()` method is not returning the related content in the same order that the related content was added when the sort parameter is not used. 

**To Reproduce**

1. Create 4 contents of the Content-Type Blog Comments (c1, c2, c3, c4).
2. Create a blog and relate the 4 comments.
3. Reorder the comments (c4,c1,c2,c3)
4. Create a Code Snippet Widget with the code:
```
#set($id = "ID OF THE CREATED BLOG")
#set($comments = $dotcontent.pullRelatedField($id,"Blog.blogComment", "+languageId:1", 3, ""))
<h3>Comments</h3>
#foreach($comment in $comments)
<div>
Blog comment: $comment.title
</div>
#end
```
5. Create a page and add the created widget.
6. Check the order of the comments, should be the same as the one of the content (c4, c1, c2). But is showing (c4,c2,c3).

**Expected behavior**
When no sort parameter is specified, the `$dotcontent.pullRelatedField()` method should return the related content in the same order that the related content was added.

**Screenshots**
ORDER BY MOD DATE
![OrderByModDate](https://user-images.githubusercontent.com/5278970/161089752-0478ffa6-1c40-471f-ad92-4c895bff116c.png)
ORDER AT THE CONTENT
![OrderContentRelationships](https://user-images.githubusercontent.com/5278970/161089758-5fe1a381-a326-4474-8e2a-00c73a438b45.png)
ORDER SHOWING IN THE PAGE
![OrderPageRender](https://user-images.githubusercontent.com/5278970/161089769-6ee7a779-109c-4083-a74e-634a04da912a.png)

**Additional context**
Customer Ticket: https://dotcms.zendesk.com/agent/tickets/106898
Reproducible in demo (22.03)

**Comment by nollymar** [comment]
PR: #22054

**Comment by fabrizzio-dotCMS** [comment]
Tried the steps listed in the description and it all looks good there. Also tried adding a couple of sort condition they are respected as well. As far as I can tell it is working as expected
