### ISSUE TITLE
Render the new block editor fields in the blog detail page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21936]
**Is your feature request related to a problem? Please describe.**
After https://github.com/dotcms/core/issues/21935 we now need to update the render of the block detail page.

**Describe the solution you'd like**
- Make sure it looks exactly as it is now
- Link the related contentlets to their respective pages
- Images should work as expected and use the dotCMS image API

**Additional context**
⚠️ If you find any difficult by implementing this, please let everyone know because the idea is that this is easy to do for our customer.
✅ See this issue to understand how to render blocks in vtl: https://github.com/dotCMS/core/issues/21302

**Comment by hmoreras** [comment]
this [PR](https://github.com/dotCMS/core/pull/21972)  need to be merged to reflect the custom layout for the for the content blocks in `dotContent.vtl` under the folder `/application/vtl/blog/blocks` in http://starter.dotcms.com:8443/

**Comment by fmontes** [comment]
Waiting for server update to 22.04

**Comment by fmontes** [comment]
Merged and running: https://starter.dotcms.com:8443/blog/post/french-polynesia-everything-you-need-to-know

**Comment by bryanboza** [comment]
Fixed. Tested on release-22.04 // Docker // FF
