### ISSUE TITLE
Add more aggragation fields to SiteSearch index

### ISSUE THREAD

**Issue by Djacomo** [dotCMS/core#21948]
Since the siteSearch index works on "keyword" meta tag, we would like to add another field to"meta" tag in the "SiteSearch" index (not ES Index neither live or work indexes).

At the moment we can populate "keyword" metadata and we would like to know if is possible index more than one meta HTML fields, likes "porfolio", "markets".

It would be great if more then one meta tag could be added, so that we can write different ES queries.

For example:

```
<meta name="keyword"> k1, k2</meta>
<meta name="portfolio">foo, goo</meta>
<meta name="markets">foo1, goo1</meta>
```

We could also aggregate over "portfolio" and "markets".

If you can access to helpdesk, this is my open ticket [#106788](https://helpdesk.dotcms.com/hc/en-us/requests/106788).

**Comment by wezell** [comment]
@Djacomo would a normal content search work for this - it is possible to search html pages using the normal content search.  Maybe create an aggregation of a normal content search and a site search?

**Comment by Djacomo** [comment]
My idea is very simple:

```

**Comment by Djacomo** [comment]
My idea was to add a field to the file "es-siteseach-mapping.json", so in the SiteSearch Index will be a new field equal to "keyword" in the index. 

```
        "keywords": {
          "type": "keyword",
          "doc_values" : true
},
    "portfolio": {
      "type":  "keyword",
     "doc_value": true
},

```
There are some info that exists only in the rendering page phase, not actually present as a field of a page or a Content Type.
