### ISSUE TITLE
Update vtl render block to support alignment

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21941]
**Is your feature request related to a problem? Please describe.**
If you render **any block** in will not align correctly because the `vtl` file that we use to render doesn't support it.

**Describe the solution you'd like**
We need to add styling to align the blocks using the block properties.

**Describe alternatives you've considered**
Maybe classes and we add that to the CSS in the block?

**Comment by fmontes** [comment]
Needs to create a custom container because system doesn't support block field render yet.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
