### ISSUE TITLE
Unable to add existing widgets to a page

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21957]
We are getting an error in the JS console when you try to add a widget that already exists to a page 

**To Reproduce**
- Login ad admin
- Create a new folder
- Create a new page 
- Try to add an existing widget to the page  (comes from the starter)

**Expected behavior**
We need be able to add those ones to pages without problems 

**Screenshots**
![image](https://user-images.githubusercontent.com/2641437/161650392-30a4d5ea-9520-4ddd-9bfe-4837f39f5fd1.png)

**Desktop (please complete the following information):**
Tested on release-22.04 // Docker // FF

**Comment by fabrizzio-dotCMS** [comment]
On a closer look this has front-end code I'm not familiar with

**Comment by wezell** [comment]
related to #21700

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/21969/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now I'm unable to reproduce.  Tested on release-22.04 // Docker // FF
