### ISSUE TITLE
Add `live: true` to fetch the pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21956]
**Describe the bug**
Pulling data without `live: true` param can get working version of the blog posts.

**To Reproduce**
1. Edit a blog
2. Save it (not publish it)
3. Render the blog page and see your changes

**Expected behavior**
We always need to show the live version of the blog posts. **Includes listing and detail pages.**

**Comment by oidacra** [comment]
Added with the preview mode in this ticket: `https://app.zenhub.com/workspaces/lunik-61780f8ea7866b001141b588/issues/dotcms/core/21807`

**Comment by oidacra** [comment]
Finally we will use:
preview: +working:true +deleted:false
Live: +live:true +deleted:false
PR: dotCMS/next.js#1
