### ISSUE TITLE
Add an EMA token/key when initing a EMA environment

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21959]
When we set up an NextJS EMA environment, we need to generate a unique token - `EMA_ACCESS_TOKEN` that should be saved in the .env file.  This token will be needed to append to the EMA url.  If the token sent by EMA does not equal the token in the App, the ema request should fail.

In the demospa example, the ema path should be:

https://demospa.dotcms.com/ema?token={EMA_ACCESS_TOKEN}

**Comment by fmontes** [comment]
@jcastro-dotcms not working, when I setup ema and try to edit the page I get this error.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/751424/181116349-8ae38480-e112-4a1b-b2b3-04441f026352.png">

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/181377020-f0053c4c-d56d-4a60-a097-f86a6c2f4d18.mp4
