### ISSUE TITLE
Host/Folder field should render optional folders 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#21961]
The component we use to choose a host/folder must be modified to support: 
- Displaying optional folders: those that have an entry in the `identifier` table but not in `folder`.
- The creation of optional folders. 

Probably, we might need a new component to support it.

![Screen Shot 2022-04-05 at 11.15.11 AM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/43c808c2-f736-40db-ab01-5588d23743ee)

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/21961?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by fmontes** [comment]
Closing, will take care of in the new edit-content
