### ISSUE TITLE
Content type contextual menu cutting off

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21979]
**Describe the bug**
The contextual menu in the last rows of the content types is cutting off.

**To Reproduce**
1. Go to content types
2. Scroll down to the last items
3. Click on the three dots (if you don't have applied a license)
4. See the cut.

**Expected behavior**
It should show completely

**Screenshots**
![image_720](https://user-images.githubusercontent.com/751424/162073893-a7a0fc31-55d2-4d7f-8ba8-e16f7b4cd44b.png)

**Comment by oidacra** [comment]
The class: `.p-datatable-wrapper` has a style `overflow-x: auto;` Works if you remove it (overflow: visible|initial|etc;). 

![Screen Shot 2022-04-07 at 11 05 35 AM](https://user-images.githubusercontent.com/1909643/162247870-9d0d2f9a-4ce1-4f1a-bae1-00b0947e8ef0.png)

**Comment by fmontes** [comment]
Tested and merged.

**Comment by bryanboza** [comment]
Fixed, now we are unable to reproduce after the last changes. New enhancement related to close that menu when you click out of it will be reported in a new card.
