### ISSUE TITLE
Need to auto refresh the site browser after move any folder or file 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21973]
We need to auto refresh once the folder has been moved, right now we made a kind of refresh but after this, we are showing the folder in both locations, then if you try to open any of those we are getting a JS error 
![image](https://user-images.githubusercontent.com/2641437/161651813-ead52aa0-c5b2-4436-aa0a-454dc20953d7.png)

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/21801#issuecomment-1088136557_

**Comment by bryanboza** [comment]
This problem is causing multiple problems if you try to use the folder in the old path:
- If you try to open we are not loading the files 
- if you try to push it, we are getting this error: https://gist.github.com/bryanboza/fac98f487c2c4656afb5d3353de5ab3d

**Comment by nollymar** [comment]
This issue is reproducible in demo too. Not just in 22.04.

**Comment by oidacra** [comment]
Works as expected. You can move the files or folder and don't need to refresh to see the changes.

**Comment by fmontes** [comment]
We try to repro this with:

1. Create a new folder in `/application`
2. Copy the folder
3. Paste in `/campaing`

And it works as expected.

**Comment by bryanboza** [comment]
Attached the requested video about how to reproduce: 
https://user-images.githubusercontent.com/2641437/189463185-e4772e63-64fa-457a-8461-284c04005635.mov

FYI: Im able to reproduce just in Chrome (Version 104.0.5112.101 (Official Build) (x86_64))

**Comment by fmontes** [comment]
Unable to reproduce consistently and we'll take care when refresh browser portlet.
