### ISSUE TITLE
On StoryBlock, toHTML should use the system user

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#21971]
Currently when an user overrides the toHtml of the storyblock, it is using the current user to retrieve the folder and is getting complicated the permissions. 

It does not make sense to use the current user on an internal include, would be better to use the system user

**Comment by hmoreras** [comment]
Adding a custom vtl now works.

- add an new folder call `blocks` under `/application/vtl/blog/`
- create a file `dotContent.vtl` with the following content: https://gist.github.com/hmoreras/0588d4b65ea22d516cfade92fc1aae8b
- add `$!{URLMapContent.get("body1").toHtml('/application/vtl/blog/blocks/')}` to the `/application/vtl/blog/blog-detail.vtl`
- Add a `block editor` editor field to the blog content type, with the name body.
- Search a Blog and a a product in the Block Editor field. 

Should look like this: 


<img width="1076" alt="image" src="https://user-images.githubusercontent.com/31667212/162257846-928bc3cd-fe7f-4a12-bfa3-d2ee01bd39be.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
