### ISSUE TITLE
Dot-KeyValue (webcomponent) should not allow D&D when disabled

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21983]
when Dot-KeyValue (webcomponent) is set as disabled it should not allow D&D

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1942/files

**Comment by alfredo-dotcms** [comment]
Blocked/Depends on https://github.com/dotcms/core/issues/21982

**Comment by alfredo-dotcms** [comment]
https://github.com/dotCMS/core/issues/21983#issuecomment-1091997860
done!

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
