### ISSUE TITLE
DotCms-Webcomponents unit tests not working

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#21982]
After the upgrade of NG, NX & PrimeNg (https://github.com/dotCMS/core-web/pull/1842) the unit tests for DotCms-Webcomponents stopped working

```
nx run dotcms-webcomponents:test --watchAll
nx run dotcms-webcomponents:e2e --files=path_file
```

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/dcb304f3-4cf9-4a80-b9fa-b113bf781d8b)

**Comment by prestonso** [comment]
Marking closed per @fmontes.
