### ISSUE TITLE
Update default config

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22006]
Our config has a bunch of unused or incorrect values set.

`PUSH_PUBLISHING_RULES_OVERWRITE` should be set to `false`.  

`DEFAULT_PAGE_CACHE_SECONDS` is too low.  Only very customized pages should have this set lower.

`json.web.token.allowhttp` should be disallowed by default

**Comment by jcastro-dotcms** [comment]
For testing purposes, you can create a JSP file that pulls the value of any of the updated properties. Or, you can go to the **Settings > Maintenance > Cache** portlet, click `Refresh Stats`, and check the size values of the following Cache Regions in the table:
```
cache.categoryparentscache.size=30000
cache.taginodecache.size=50000
cache.taginodesbyinodecache.size=50000
cache.tagcache.size=50000
cache.identifier404cache.size=30000
cache.shortyidcache.size=25000
cache.velocitycache.size=5000
```
