### ISSUE TITLE
Blank Binary Field Causes Error on Import

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#22004]
**Describe the bug**
When importing contentlets with a binary field, if the binary field has a null value, dotCMS throws an error in the logs and nothing is imported. Note, the content can be imported fine if the binary field is removed from the CSV when imported.
**To Reproduce**
1. Go to demo.dotcms.com
2. Create a CT with a text field and a binary field that is not required.
3. Create some contentlets of that type in a CSV with only a text value and a null value in the binary field column, then try to import those contentlets without any key fields selected

**Expected behavior**
A null value in the binary column of a CSV would not effect its ability to be imported successfully. 

**Desktop (please complete the following information):**

 - Version, 5.3.8.10, 22.03

**Additional context**
Related to a customer issue: https://dotcms.zendesk.com/agent/tickets/107012

**Comment by nollymar** [comment]
PR: #22046

**Comment by fabrizzio-dotCMS** [comment]
tried importing the following file
[CSV_Template (2).csv](https://github.com/dotCMS/core/files/8557565/CSV_Template.2.csv)
against a CT with a title text field and 2 non-required binaries
neither an Empty string nor a blank between commas breaks the import.
