### ISSUE TITLE
CurrentVisitorUrl rule does not take urlmap into account

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22007]
Trying to use rule to do redirects on our doc site and it is not correctly capturing the url.  This basically makes rules useless for site redirects on sites that use urlmaps

The rule is trying to redirect a user from https://dotcms.com to https://www.dotcms.com but the issue is that it does not take URLMaps into account when rewriting the url.  This means that someone visiting a urlmapped page

https://dotcms.com/docs/latest/markdown-syntax

ends up getting redirected to the urlmap detail page

https://www.dotcms.com/documentation/index

![Screen Shot 2022-04-11 at 5 01 41 PM](https://user-images.githubusercontent.com/934364/162832044-f9c0a436-b81d-497e-bd24-55c8d22a8407.png)

**Comment by wezell** [comment]
PR: #22142

**Comment by fabrizzio-dotCMS** [comment]
Here's what I did to verify this PR

- I added the following entry to my /etc/hosts. `127.0.0.1   dotcms.com` 
- then I created a dummy page like /documents/rest-endpoint-documentation on my local instance
- then I added a Rule almost identical to the one listed in the first comment above `Request Header` `Host` is `dotcms.com:8080` 
- And then fired the rule putting this on my browser `http://dotcms.com:8080/documentation/rest-endpoint-documentation` and then verified the redirection effectively takes the user to 
- https://www.dotcms.com/documentation/rest-endpoint-documentation
 
As far as I can tell the PR https://github.com/dotCMS/core/pull/22142 is good to go as it is and can be merged

**Comment by fabrizzio-dotCMS** [comment]
I added a Rule configured to intercept everything under blogs /blog/post/(.*) and set a header 
Also created a VanityURL that intercepts the specific URL of a blog post and redirects to the blog's index. 
I was able to verify that both the vanity and the Rule work together in conjunction As the redirection takes place correctly and the header is also set in the response

**Comment by bryanboza** [comment]
Fixed, tested on release-22.-7 // docker // FF
