### ISSUE TITLE
The image on load is not centered

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22015]
**Describe the bug**
When block editor loads in the edit contentlet, the content image that have center is not showing centered.

**To Reproduce**
1. Add an image to a block editor and center
2. Save the content and close the dialog
3. Edit the contentlet
4. Image is not centered (but the bubble menu show the center icon selected)

**Expected behavior**
It must show centered on load.

**Screenshots**
<img width="688" alt="image" src="https://user-images.githubusercontent.com/751424/163070770-e1398fd4-f7e4-48db-be02-19f4031f4128.png">

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1951

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF. Now we can center the image without problems
