### ISSUE TITLE
Add decoration with instructions on empty editor and block

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22038]
**Is your feature request related to a problem? Please describe.**
Users don't know what they can do in the block editor, there is no information about the keyboard shortcuts.

**Describe the solution you'd like**
Add a decoration indicating:

1. That they can press `/`
2. For headings
    - What block they are creating or editing
    - When the block is empty we add the decorator with the name of the block

**Additional context**

https://user-images.githubusercontent.com/751424/164047464-c84ddf54-3ff3-4ca9-b9db-ce56502995f4.mp4

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/164248242-3d6fba99-99ff-4e56-ba3e-1ab6a7b2a3f5.mp4

**Comment by bryanboza** [comment]
Fixed, tested on release 22.04 // Docker // FF
![image](https://user-images.githubusercontent.com/2641437/164314738-38986488-9dc9-480f-aa66-7b4ef79526f3.png)
