### ISSUE TITLE
Support field variables to add customization to block editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22037]
**Is your feature request related to a problem? Please describe.**
Users want to add customizations to the block editor. For example, custom CSS to the parent div to change the width, height, or border.

**Describe the solution you'd like**
Users will add a field variable called `styles` add valid css styles as string to eventually be added to a custom class called `dotcms-block-editor.block-custom-styles` that will overwrite the default block editor styles.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/31667212/165360657-f839e129-e027-472c-8b66-e84fc4a4df07.png">

**Additional context**
In this very same object, users will be sending other configurations like a white list of content types or a list of blocks they want to allow in this field.

**Comment by fmontes** [comment]
I'll be doing Internal QA to this one.

**Comment by oidacra** [comment]
Works, apply the css to the editor using filed variables.
![Screen Shot 2022-05-06 at 3.35.04 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/b7fd785c-ae5b-492f-92b6-1b9a04d05849)![Screen Shot 2022-05-06 at 3.35.23 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/2fc83310-739f-456d-bf72-382bf0cfa469)

**Comment by oidacra** [comment]
The field attribute is filled with this:
![Screen Shot 2022-05-11 at 12.42.49 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/7d7ea329-5a41-46a0-aa3f-e7fe5b1fa533)


Create this CSS and apply it to the Blocks Editor:
![Screen Shot 2022-05-11 at 12.47.06 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/7bab3c23-7143-41f9-8685-49848515c22d)

We need to mention in the documentation, that if we use text CSS properties, it can be applied (inherited) to the content of the editor.

**Comment by oidacra** [comment]
Example:
![Screen Shot 2022-05-11 at 12.23.59 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/9b98c069-a1e9-4c37-99b4-3d457f849890)


![Screen Shot 2022-05-11 at 12.23.54 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/7d3e6c11-cade-4cf7-ad93-5fe2198eaccf)

**Comment by fmontes** [comment]
For now, you can change:

1. width and height
2. font family
3. font size (but not specific block)

For now this is enough but I will discuss with @wezell to see what else we need to do here.

**Comment by bryanboza** [comment]
ok, after the @wezell comment the this is ok for now. 

The improvement was moved to #22293
