### ISSUE TITLE
Upgrade from dotCMS v21.06.4LTS to Agile dotCMS v22.03 GraphQL Outputs Empty Results When Category Keys Contain a Capital Letter

### ISSUE THREAD

**Issue by TheGreatAlexander** [dotCMS/core#22036]
**Describe the bug**

GraphQL search query returns no results when the category key/variable id of a collection contains capital letters.  For example, travelAndLeisure, travelAndWellness.  The search only outputs results if category key/variable id  one word, for example: apparel, outdoor, water.

**To Reproduce**
1. Go to demo site demo.dotcms.com
2. Go to CATEGORIES ---> PRODUCT LINE
3. Create three new categories with two or three separate words:  Extreme Sports, Travel and Leisure  and Travel And Wellness
4. Go to Products and add one of those categories to three different contentlets
5. Reindex
6. now to test go to:

https://www.dotcms.com/product/features/graphql/index

Or,

Admin GraphQL Tool

7. Execute a search using the category keys or ids:

query  {
  search(
    query: "+contentType:product +(categories:travelAndLeisure)", 
    limit: 5, 
    offset:5, 
    sortBy:"title"
  ){
    identifier
    title
    ...on Product {
     	description
      urlTitle
      tags
    }
  }
}

![Screen Shot 2022-04-17 at 6 12 42 PM](https://user-images.githubusercontent.com/1947524/163737383-167c1fc0-129d-4ca1-97d2-8c62762b7adf.png)
![Screen Shot 2022-04-17 at 6 13 14 PM](https://user-images.githubusercontent.com/1947524/163737394-80a877c8-762f-4b15-8e33-e88f46a72c4c.png)
![Screen Shot 2022-04-17 at 6 13 44 PM](https://user-images.githubusercontent.com/1947524/163737414-93970c2b-7672-44d2-aa21-417f9dc4b635.png)

If I search the categories that are one word I get a response
![Screen Shot 2022-04-17 at 6 14 32 PM](https://user-images.githubusercontent.com/1947524/163737432-98324d60-4216-4142-b055-92c826cf3d43.png)

I tested this further on the demo site admin interface in the graphQL 

I did a search that included all categories and saw that the contentlets had categories.

![Screen Shot 2022-04-17 at 6 28 25 PM](https://user-images.githubusercontent.com/1947524/163845734-977ffa16-afba-4ffe-b044-74e84e67efdb.png)

Then, I did a search with the category it had (extreme sports) and I got no results.

![Screen Shot 2022-04-17 at 6 28 45 PM](https://user-images.githubusercontent.com/1947524/163845821-a069e7e2-6b3f-4b1f-8459-e978d25e2a16.png)

8. See error
There are no errors because there are no results

**Additional context**

**Comment by nollymar** [comment]
@TheGreatAlexander did you test changing the limit/offset parameters? 

This query is working for me
```
query {
search(
	query: "+contentType:product +(categories:travelAndLeisure)",
	limit: 5,
	offset:0,
	sortBy:"title"
){
    identifier
    title
    ...on Product {
      description
      urlTitle
      tags
    }
	}
}
```

**Comment by TheGreatAlexander** [comment]
@nollymar Indeed, it was the offset option that needed to be set to 0 in order for anything. Thank you so much for pointing that out.

To avoid confusion, I suggest you update this default query on the Search Tab of the GraphQL playground page, and set offset to 0.

https://www.dotcms.com/landing-pages/headless-cms/graphql-cms


query  {
  search(
    query: "+contentType:activity", 
    limit: 5, 
    offset:5, 
    sortBy:"title"
  ){
    identifier
    title
    ...on Activity {
     	description
      urlTitle
      tags
    }
  }
}
