### ISSUE TITLE
Control what contentlet types you can add

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22039]
**Is your feature request related to a problem? Please describe.**
Users want to limit the type of content they can have in a block field.

**Describe the solution you'd like**
User will be passing a white list in the content types variables, we will only show the ones passed in the list.

If no list set, we show all the content types.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/31667212/167894109-2b893b76-600f-4328-8403-6a121d6aab56.png">

**Additional context**
Here's an example on how to use this new REST Endpoint:
```
curl --location --request POST 'http://localhost:8080/api/v1/contenttype/_filter' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "filter" : {
        "types" : "calendarEvent,Vanityurl,webPageContent,htmlpageasset,FileAsset",
        "query": "",
        "orderBy": "",
        "direction": "",
        "page": 1
        "perPage": 40
    }
}'
```
***Parameters***
If no parameters are specified at all, the REST Endpoint will return **ALL Content Types that are accessible by the User calling the service**:

- `types`: The comma-separated list of Velocity Variable Names matching the Content Type information that will be returned.
- `query`: Allows you to filter the list of Content Types by either their names or Velocity Var Names. It uses wildcards so that it will match at least one character.
- `orderBy`: The sort criterion for the results. Defaults to the Content Type's name.
- `direction`: Determines the sort direction in ascending (ASC) or descending (DESC) order. Defaults to "ASC".
- `page`: The results page being requested, for pagination purposes. Defaults to the first page.
- `perPage`: Total amount of results per page, for pagination purposes. Defaults to 10.000 when querying ALL Content Types, and 500 for filtered Content Types.

**Comment by rjvelazco** [comment]
I was doing internal QA and I found these two unexpected behavior:

 - **Go Back button does not work when thet contenttype does not exist**
1. Add a new variable with a value that does not exist like: `contentTypes: whatevet`.
2. Go to the block editor.
3. Open the suggestions menu, use `./`.
4. Select `contentlets`.
5. See the error message and the button to go back.
6. Click the go back button.
7. See the error.

If you want to see the behavior, here is a [video](https://www.loom.com/share/89a8ac893c714f71b4c1bae022e19771).

- *Unexpected attributes on the editor*
1. Add a new value on the `contentTypes` variable which starts with `"`, it could be `contentTypes: "new-attribute`.
2. Go to the block editor.
3. Inspect the element using the developer tools of the browser.
4. Look up for `dotcms-block-editor` tag.
5. See the unexpected attribute.

If you want to see the behavior, here is a [video](https://www.loom.com/share/8c34ebe0d1494552887df6418ae92aa0).

**Comment by hmoreras** [comment]
Rafael feedback : 
https://github.com/dotCMS/core-web/pull/1994
https://github.com/dotCMS/core/pull/22281

**Comment by oidacra** [comment]
Works as expected. Fixed the problem mentioned by Rafael.


<img width="699" alt="Screen Shot 2022-05-25 at 12 47 42 PM" src="https://user-images.githubusercontent.com/1909643/170363755-edf90f01-f520-4107-8240-c39ffa717b32.png">

<img width="691" alt="Screen Shot 2022-05-25 at 12 48 04 PM" src="https://user-images.githubusercontent.com/1909643/170363751-59c89308-ce3c-4e97-9d5a-b509ae478bbe.png">

**Comment by bryanboza** [comment]
Fixed, this is working as expected...
