### ISSUE TITLE
Prune old Time Machine backups from the back end

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#22033]
**Is your feature request related to a problem? Please describe.**
Time Machine backup files are saved indefinitely. Over time they can consume a substantial amount of disk space. 

I believe the only way to remove these files from the dotCMS backend is to delete a Time Machine backup job, which will delete all backups for that job.

Otherwise, pruning old Time Machine files requires direct access to the file system.

**Describe the solution you'd like**
A couple suggestions:
1) manual BE delete - allow BE admins to "delete Backups older than dd-mm-yyyy" or "delete all but the previous N backups"
2) automated - specify "number of backups to save" on the Time Machine job

**Comment by wezell** [comment]
We should have a config option called:
`PRUNE_TIMEMACHINE_OLDER_THAN_DAYS`

with a default of 90.  We should delete timemachine snapshots older than the configed number of days.

**Comment by yolabingo** [comment]
I think this will be helpful

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/28586

**Comment by dsilvam** [comment]
Passed Internal QA: Job properly deleting backups older than the specified number of days.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_f28fc49**, Docker, macOS 13.0, FF v124.0.2
