### ISSUE TITLE
Filter contentlets in suggestions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22045]
**Is your feature request related to a problem? Please describe.**
Allow the block editor to filter Content of specific Content Type. The results will show the first 40 maches.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1973

**Comment by oidacra** [comment]
It's Working.

**Comment by bryanboza** [comment]
We are unable to list the content types, clocked by #22044

**Comment by hmoreras** [comment]
The endpoint for the backend was merged May 18th, https://github.com/dotCMS/core/commit/9f8c8c79213fd571834dca7fbfdf810c500c65a7, now can be tested.

**Comment by rjvelazco** [comment]
Sometimes the filter breaks and does not work.

To reproduce:
1. Go to a blog.
2. Open the suggestions menu. Type `/`.
3. Go to `contentlets`  and then to `Activity`.
4. Type something like `/fa`.
5. See the error.

**Comment by fmontes** [comment]
Working, not it searches substring in ALL indexed fields.

**Comment by bryanboza** [comment]
Fixed, tested on releases-22.06 // Docker // FF
