### ISSUE TITLE
Filter content types in suggestions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22044]
**Is your feature request related to a problem? Please describe.**
Allow the block editor to filter Content Types. The results will show the first 40 maches. 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/31667212/166714713-2f6ae4c2-b378-483b-87e4-14364904fbeb.png">

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core-web/pull/1971

**Comment by oidacra** [comment]
Works as expected.

![Screen Shot 2022-05-06 at 1.31.14 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/5bd07d95-7ad1-41c5-98f0-9c02a677ce5a)

**Comment by bryanboza** [comment]
We need some work here: 

We are unable to get the list of content types, we are getting a 404 error in the request 

Here the log: https://gist.github.com/bryanboza/28ca21cd8419db64dcf302c74d8585e8

Tested on release-22.06 // Docker // FF 
Image: dotcms:22.06_c668cdf_SNAPSHOT

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
