### ISSUE TITLE
OSGI: Read exports from uploaded fragment, then discard fragment

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22055]
When a fragment is uploaded, we need to read the `Export-Package` from the manifest and add them to our osg-extras file.  Once this is done, we can move the fragment to the undeployed folder and restart the osgi framework.  

We should not allow fragments to be loaded unless forced as they interfere with the loading of other osgi plugins.

**Comment by jdotcms** [comment]
Working on this

**Comment by jdotcms** [comment]
In addition we are working on master a change to support rewire instance when the framework restart

**Comment by erickgonzalez** [comment]
Only affects 22.03

**Comment by jcastro-dotcms** [comment]
Internal QA approved!

The OSGi Plugin used for testing was `com.dotcms.viewtool`.

By default, when you drag-and-drop both the `Plugin JAR` and the `Fragment JAR`, dotCMS is only displaying the plugin JAR in the list. The `Fragment JAR` is displayed in the `Available Plugins` dropdown at the top-left corner of the portlet in case the User needs to deploy it as well.

**Comment by erickgonzalez** [comment]
Is working with D&D but no with upload plugin button.

**Comment by wezell** [comment]
Upload button fixed in this PR: #22295

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF 

Now we are excluding the fragment from the list and just are showing the correct plugins
