### ISSUE TITLE
lazy load workflow history in workflowprocessor

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#22068]
Seen in cloud servers - requests such as

`PUT /api/v1/workflow/actions/fire?identifier=ID`

may be slow for content with long workflow histories. Will suggested to lazy load this history.

See https://dotcms.slack.com/archives/CSHTYUR7H/p1650647952454859

**Comment by wezell** [comment]
Please note, the slow content in question have 100's of versions and WorkflowHistories.  In any event, you can see that 40% of time when calling workflow fire is in pulling the history from the db.
![Screen Shot 2022-04-22 at 3 55 44 PM](https://user-images.githubusercontent.com/934364/164784966-2153beaa-afda-40f4-9ae5-907a96cb73bf.png)
f

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/22082

**Comment by nollymar** [comment]
**Internal QA:** Passed

In order to test it, I set a breakpoint on the WorkflowProcessor.getHistory() to make sure it would be called only with these actionlets: Reset Approvals, Require Multiple Approvers and 'Four Eyes' Approval.
