### ISSUE TITLE
Remove the 40 limit in the content types request

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22066]
**Describe the bug**
When user select "contentlet" block, and have more than 40 content types it will only show the first 40.

**To Reproduce**
1. Create more than 40 content types
2. Add contentlets to a block field
3. See the content types list
4. You can only see 40 content types.

**Expected behavior**
The user should be able to add a contentlet from any content type in the system.

**Comment by fmontes** [comment]
No limit only brings 10, we need to add a huge limit, 1000.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
