### ISSUE TITLE
Missing DB_MIN_IDLE parameter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22078]
Running 22.03 instances it seems that the database pool is not releasing connections and is taking the `DB_MAX_CONNECTIONS` parameter as a fixed size connection pool.  Every 22.03 dotCMS instance takes at least 100 db connections and in docker, 200 db connections, and not releasing them.

You can see this in psql:

```
dotcms.com=# select datname, count(*) as sessions from pg_stat_activity group by datname order by sessions desc;
      datname       | sessions
--------------------+----------
 abc.dotcms.com     |      102
 1234.dotcms.com    |      101
 xyz.dotcms.com     |      101
                    |        5
```

Looking at the code, it is clear that we are not reading the `DB_MIN_IDLE` environmental value nor are we setting a `setMinimumIdle` on the connection pool config.

**Comment by nollymar** [comment]
**Internal QA:** Passed.

Before (using image `22.04_d122d81_SNAPSHOT`):

<img width="878" alt="Screen Shot 2022-04-26 at 3 50 22 PM" src="https://user-images.githubusercontent.com/8741395/165391062-48e46d97-bf21-4fe8-a884-1fcfd5b26671.png">

After (using image `22.04_3679e05_SNAPSHOT`):

<img width="897" alt="Screen Shot 2022-04-26 at 3 54 15 PM" src="https://user-images.githubusercontent.com/8741395/165391138-03543792-ff03-41b3-a546-cb19a38a8c5d.png">

**Comment by swicken-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22079

**Comment by erickgonzalez** [comment]
Only applies to 22.03
