### ISSUE TITLE
Missing blockquote .vtl

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22072]
**Describe the bug**
As a user, I want to be able to add and render blockquotes in the block editor

**To Reproduce**
1. Create a `blockquote` in the block editor
2. Add the content to a page
3. See it doesn't render

**Expected behavior**
It should render all the default blocks.

**Additional context**
The default .vtls for the storyblock editor is missing a vtl for `blockquote`

**Comment by rjvelazco** [comment]
PR: #22084

**Comment by rjvelazco** [comment]
PR: #22084

**Comment by wezell** [comment]
closed in favor of #22074

**Comment by bryanboza** [comment]
Fixed, tested on release-22.05 // Docker // FF
