### ISSUE TITLE
Allow users to edit image properties when adding an image via the image browser on an image field

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22081]
**Is your feature request related to a problem? Please describe.**
When adding an image via the image field, after uploading it it returns you directly to the contentlet you were adding the image to. This does not allow you to add any image properties (like alt text), requiring the user to find the image on the file system after and add the properties manually.

Related ticket: https://dotcms.zendesk.com/agent/tickets/107161

**Describe the solution you'd like**
When uploading via the browser, allow the user to modify the properties of the image before finalizing the process.

**Comment by katokalen** [comment]
For additional context we have accessibility requirements on our projects so are looking for fields like alt text to be easily editable when an image is uploaded within a widget or auto-filled in based on another property. There is a work around mentioned above but it's breaking the flow of our content authors and isn't enforced.
