### ISSUE TITLE
PageCache needs to respect javax.servlet.forward.request_uri

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22083]
There are places in code - for example vanityurls - that we do servlet forwards for various urls.  For example, you can use a VanityUrl very much like a urlmap and redirect a pattern to a specific detail page that can then query and render the content, e.g.
```
/blogs/(.*) --> /blogs/detail-page
```
In such cases, you would get the "correct" url from the `$request.getAttribute("javax.servlet.forward.request_uri")`, parse it and use that to find the correct content to return on the detail page.

The issue is that if you have page-cache set on `/blogs/detail-page` it does not take the original `javax.servlet.forward.request_uri` url into account when building the cache key and so two different blogs can appear to have the same content.  This was biting us on our documentation site and affects customers as well.  See:

 https://dotcms.zendesk.com/agent/tickets/107153

We need to add the value of `request.getAttribute("javax.servlet.forward.request_uri")` to our page cache key so that each individual page can be properly cached.

**Comment by fmontes** [comment]
Check Will's draft PR.

**Comment by jcastro-dotcms** [comment]
**NOTE TO QA:** Here are some steps to reproduce this issue and verify the fix:

## Before the fix:
1. Start up dotCMS with the full starter.
2. Open up the Page Properties for `/blog/blog-detail`, and set a Cache TTL of 180.
3. Create a Vanity URL with the following values:
4.1 Uri = `/blogs/(.*)`
4.2 Forward To = `/blog/detail-page`
5. Flush all caches, and check the specific Page Cache Region via the REST Endpoint: http://localhost:8080/api/v1/caches/provider/Caffine%20Memory%20Cache/objects/BlockDirectiveHTMLPageCache . It must be empty.
6. In an Incognito Window, go to the following URL: http://localhost:8080/blogs/french-polynesia-everything-you-need-to-know . The JSON response will show a key like this:
```json
{
  "entity": {
    "6b08ac52-0a39-42d9-895f-a5ae303e2a09_1655924606629": [
      {
...
...
```
7. Now, go to this other URL: http://localhost:8080/blogs/5-snow-sports-to-try-this-winter . If you check the Cache REST Endpoint again, you'll get the very same entry you got before, which is wrong.

## After the fix:
1. Just follow the very same steps mentioned above. But, you'll see that you'll get two cache entries now, which is correct and expected.
2. For http://localhost:8080/blogs/french-polynesia-everything-you-need-to-know ,  you'll see something like this:
```json
{
  "entity": {
    "anonymous_1_null_null_null_/blogs/french-polynesia-everything-you-need-to-know_426171a9-5e56-47f7-a380-452b9ca8bdd2_2022-06-23 22:18:06.915_e3b21fcbad32ab6f509ed672a41f34a0": [
      {
...
...
```
3. And, when you go to http://localhost:8080/blogs/5-snow-sports-to-try-this-winter , you'll see two entries with different keys now: 
```json
{
  "entity": {
    "anonymous_1_null_null_null_/blogs/french-polynesia-everything-you-need-to-know_426171a9-5e56-47f7-a380-452b9ca8bdd2_2022-06-23 22:18:06.915_e3b21fcbad32ab6f509ed672a41f34a0": [
      {
...
    }],
   "anonymous_1_null_null_null_/blogs/5-snow-sports-to-try-this-winter_426171a9-5e56-47f7-a380-452b9ca8bdd2_2022-06-23 22:18:06.915_e3b21fcbad32ab6f509ed672a41f34a0": [
      {
...
    }]
...
```

**Comment by dsilvam** [comment]
Passed Internal QA: Working as expected following steps in Jose's comment and Issue description.

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and this is working as expected. Tested on release-22.07 // Docker // FF
