### ISSUE TITLE
No HTML RegEx Invalidates Period (.) When Used

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#22094]
**Describe the bug**
When you add the "No HTML" validation RegEx to a field in a content type then try to save a contentlet with a period in that field (.) the RegEx is triggered and the period is treated like HTML.  

**To Reproduce**
1. Go to demo.dotcms.com
2. Add the "No HTML" RegEx to a text field in a content type
3. Create a new contentlet of that type that contains a sentence with a period

**Expected behavior**
Periods alone would not trigger the "No HTML" RegEx invalidation.
**Screenshots**

![Screen Shot 2022-04-27 at 7 50 12 AM](https://user-images.githubusercontent.com/90852779/165546515-1dd4ae3a-f47b-4b80-bc21-034a38539f4f.png)
![Screen Shot 2022-04-27 at 7 50 32 AM](https://user-images.githubusercontent.com/90852779/165546591-28ce71a1-c679-4449-831a-b57a2542dadf.png)

![Screen Shot 2022-04-27 at 7 50 44 AM](https://user-images.githubusercontent.com/90852779/165546635-f512b968-a6de-441c-930b-99a5ae06459b.png)

**Desktop (please complete the following information):**
 - Version 22.03

**Additional context**
As reported by a customer: https://dotcms.zendesk.com/agent/tickets/107136

**Comment by wezell** [comment]
Dupe: #21190

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1980/files

**Comment by nollymar** [comment]
**Needs Work:** An upgrade task is required for existing data

**Comment by nollymar** [comment]
PR containing the upgrade task: #22214

**Comment by erickgonzalez** [comment]
This has been backported to 22.03.2 but the UT wasn't.

We need to run this query to fix any possible use:

```
update field set regex_check= '^[^<><|>]+$' where regex_check= '[^(<[.\n]+>)]*' or regex_check= '[^(<[.\\n]+>)]*';
```

**Comment by bryanboza** [comment]
Now it is working as expected but we need some improvement here: 
- When you try to add a piece of content with any character not allowed  by this validation, we are getting multiple lines of the same error in the log file, we need to catch this exception and just print some of those. 
Here the error in the log: https://gist.github.com/bryanboza/20a0606bef1c563f8e970f67509cf4e0

**Comment by bryanboza** [comment]
Now it is working as expected but we need some improvement here: 
- When you try to add a piece of content with any character not allowed  by this validation, we are getting multiple lines of the same error in the log file, we need to catch this exception and just print some of those. 
Here the error in the log: https://gist.github.com/bryanboza/20a0606bef1c563f8e970f67509cf4e0

**Comment by fabrizzio-dotCMS** [comment]
> Now it is working as expected but we need some improvement here:
> 
> * When you try to add a piece of content with any character not allowed  by this validation, we are getting multiple lines of the same error in the log file, we need to catch this exception and just print some of those.
>   Here the error in the log: https://gist.github.com/bryanboza/20a0606bef1c563f8e970f67509cf4e0

@bryanboza there's a common practice here where before an exception gets thrown support likes it to be printed out first. They don't like exceptions to be missed. And at the end, the exception appears a repeated number of times. It is not something specific of this issue.. try violating the validation of any other fields and you'll see the exact same behavior.  
I've pointed this out many times before and the answer has always been.. it's better for the exception to be there X number of times than to be missed. I think this escapes the scope of this Issue.. 
Please let's hear what @wezell has to say.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected, new enhancement reported here #22382
