### ISSUE TITLE
Velocity render for block editor doesn’t support nested nodes

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#22092]
**Describe the bug**
Velocity render for block editor doesn’t support nested nodes. For example, if you have a nested list like:

* Item
   - Sub-Item
   - Sub-Item

We are not showing the `sub-items`.

**To Reproduce**
1. Go to any blog contenttype.
2. Edit the content and add a `nested list` or a `blockquote` with any other type of block inside.
[[See an example in the video](https://www.loom.com/share/a0b84c81120846ee8dc8b907db7b69df)]
3. Save and Publish.
4. Go to the blog post page.
5. See the error.

**Expected behavior**
We must render the nested nodes.  For now, I only found the cases we can see in the video, but we have to find a solution that works for all cases to avoid the same behavior in the future.

**This issue was already solved in the [nextjs block editor render](https://github.com/dotCMS/dotcms-nextjs-example/pull/135)**

**Screenshots**
Find the video [here](https://www.loom.com/share/a0b84c81120846ee8dc8b907db7b69df)

**Additional context**
By default, tiptap allows to nest nodes. That means nodes like `ul`, `blockquote`, etc..., can contain `heading`, `list`, and any other node inside.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
