### ISSUE TITLE
We are not listing multi-language contentlets in the blog editor field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22106]
When you are working in a blog editor field and you try to add a new piece of content to the field using the preselected options in the menu, when you click on some specific content type we are listing just English contents, we are not including the pieces of content in other languages, no matter if you are creating a piece of content in any other language. 

![image](https://user-images.githubusercontent.com/2641437/165801697-9ce9f1ac-36fd-40d1-932c-90c0076a171e.png)

**To Reproduce**
- Login as an admin 
- Go to content Search 
- Add a new piece of content in Spanish  
- Go to blogs and try to add a new piece of content in Spanish 
- Try to add the created piece of content to the blog editor

**Expected behavior**
We need to include the Spanish contentlets in the preselected list. 

**Desktop (please complete the following information):**
Tested on release-22.04 // Docker // FF

**Comment by prestonso** [comment]
Works as designed. Marking won't fix per @wezell.
