### ISSUE TITLE
Need to check the dot-md-icon-selector component behavior when you hit "enter"

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22104]
When you are creating/ copying a content type and you press the enter key, we are moving to the icon field and not creating the new content type directly. 

According to a discussion with @fmontes, this seems this is related to the web component. 

**To Reproduce**
- Login as an admin 
- Go to content types 
- Try to copy a content type and hit the enter key

**Expected behavior**
We need to try to create the copy directly 

**Desktop (please complete the following information):**
Tested on release-22.04 // Docker // FF

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1970/files

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
