### ISSUE TITLE
Remove Repackaged JSONObject, JSONArray and JSONException

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22118]
We have 2 versions of these classes in our classpath.  We need to remove the repackaged ones:
```
com.dotcms.repackage.org.codehaus.jettison.json.*
```
and replace them with the ones we control:
```
com.dotmarketing.util.json.*
```

**Comment by nollymar** [comment]
PR EE: https://github.com/dotCMS/enterprise/pull/870
