### ISSUE TITLE
DB Exporter does not stream output

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22116]
When exporting a database, the DBExporter plugin intentionally streamed the output of `pg_dump` to the response.  When we moved the exporter plugin into the core, we lost that functionality and instead wait for a file to be written before we start streaming back to the response.  This basically breaks the functionality in production environments and means that when run against an instance behind a gateway or load balancer, the load balancer will close the connection before the file gets generated.  We need to stream the output to the response.

https://dotcms.slack.com/archives/CSHTYUR7H/p1651247161716419

**Comment by jcastro-dotcms** [comment]
For Internal QA purposes, you can go to **Settings > Maintenance > Tools > Export dotCMS Content** and click `DOWNLOAD DB DUMP`, which must generate the appropriate DB backup file.

For official QA, I believe it might be a good idea to test this with a big dataset.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF

**Comment by erickgonzalez** [comment]
Only applies to 22.03 LTS
