### ISSUE TITLE
Clean up Storyblock toHtml velocity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22128]
Most of the code for the velocity representation of the storyblock field should reduced to `#foreach($x in $x.y)` type loops.  In order to work this way, the `JSONArray` needs to implement `Collection` - which it should have anyway.  
Additionally, `marks` should be broken out into their own vtl files and the `marks` marco should be placed in the global macros file so it only loads once.

**Comment by fmontes** [comment]
PR: https://github.com/dotCMS/core/pull/22121

**Comment by fmontes** [comment]
@wezell points the PR to release.

**Comment by nollymar** [comment]
@fmontes I think this is the right PR: [#22133](https://github.com/dotCMS/core/pull/22133), but it should target `release-22.05`. The old one (#22122) should be closed.

**Comment by wezell** [comment]
the RIGHT #22133

**Comment by jdotcms** [comment]
this solves also [22074](https://github.com/dotCMS/core/issues/22074)

**Comment by jdotcms** [comment]
this solves also [22092](https://github.com/dotCMS/core/issues/22092)

**Comment by fmontes** [comment]
Tests not getting the folder with the VTL, @jdotcms is looking.

**Comment by wezell** [comment]
@spbolton will take a look as to why this is failing.
