### ISSUE TITLE
When logged in to front end, automatically redirect to back-end edit mode

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22124]
**Describe the bug**
If a user has both roles (BE and FE) and logins into the FE, if you paste/type the URL it automatically redirects you to BE to the page in edit mode.

**To Reproduce**
1. Create a user with both roles (**FE and BE**) and also add the following Roles:
<img width="569" alt="Screen Shot 2022-05-02 at 8 21 16 AM" src="https://user-images.githubusercontent.com/5278970/166250324-8e60088e-e554-42a8-be3a-2c716d2ff1ce.png">

2. In a private window, go to the FE and access the Members Only Section.
3. Type for example `destinations` after the host.
4. It redirects you to the destinations index page but in the BE edit mode.

**Expected behavior**
Should show the page in FE mode.

**Workaround**
Navigate to the desired page using the nav.

https://user-images.githubusercontent.com/5278970/166250724-42ef52d8-6a25-4faa-bd9c-fec425444780.mov

Customer ticket: https://dotcms.zendesk.com/agent/tickets/107078
Also reproducible in demo (22.03).

**Comment by wezell** [comment]
I think we need to update the `VelocityNavigateEditMode` class and check if the user session is a front end session or backend session.  If the session is not a backend session, we should not spit out the javascript event.

We will probably have to do the same work in the `VelocityServlet.goToEditPage` - we should not redirect a user if they are not LoginMode.BE

**Comment by nollymar** [comment]
PR: #22161

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
