### ISSUE TITLE
"View Statistics" Data Never Loads

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#22131]
**Describe the bug**
When right clicking on a page asset within the "site browser" portlet, there is an option to "view statistics" of the page. Currently, when you try to access that functionality, a loading bar shows up and the page never loads. 

**To Reproduce**

1. Go to demo.dotcms.com
2. Right click on any page asset
3. Select "view statistics"

**Expected behavior**
The "view statistics" page would load as expected

**Screenshots**

![Screen Shot 2022-05-03 at 6 28 57 AM](https://user-images.githubusercontent.com/90852779/166461776-0d3ab5a8-273c-44ba-a43f-4cd3ae572d35.png)

![Screen Shot 2022-05-03 at 6 28 34 AM](https://user-images.githubusercontent.com/90852779/166461703-e101aa55-bd8f-401d-9048-5803ec4f6c90.png)

**Desktop (please complete the following information):**
 - Version 21.06.7, 22.03

**Additional context**
As requested by a customer: https://dotcms.zendesk.com/agent/tickets/107197 

The customer has also requested a way to view all page statistics centrally

**Comment by wezell** [comment]
Remove the button when clickstreams are disabled

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22201/files

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/22361

**Comment by fabrizzio-dotCMS** [comment]
I can confirm that the view statistics option goes away from the pop-up menu once the ENABLE_CLICKSTREAM_TRACKING option is set to false. However, the functionality was broken due to some column typos introduced in the postgres.sql script

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF
