### ISSUE TITLE
The push publish button in the expansion menu on the users portlet doesn't just push the selected user, it pushes all users

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22149]
**Describe the bug**
When you utilize the menu in the top right corner of the users portlet to push publish, it pushes every user and not only the selected one.

![image](https://user-images.githubusercontent.com/78741732/166721634-c53b30f7-f21e-4ca1-9000-a39d2ddf58bb.png)

Reproduced on: 22.03, 21.06
Ticket: https://dotcms.zendesk.com/agent/tickets/107128

**To Reproduce**
1. Set up a sender/receiver
2. Go to the users portlet
3. Select a user
4. Click the 'Push Publish' button in the top right menu, every user will be included in the bundle

**Expected behavior**
The button should either only push the selected user, or it should be explicit that it will push every user.

**Comment by freddyucv** [comment]
Really we support both "Include all the users into the bundle" or "include just a specific user into the bundle"

https://www.dotcms.com/docs/latest/pushing-users

We are going to change the menu labels by: "Push All Users" and "Add All Users to Bundle"
 
<img width="230" alt="Screen Shot 2022-07-01 at 11 57 04" src="https://user-images.githubusercontent.com/10408015/176946618-b86a3d3b-43b3-4645-8da6-172ee4644889.png">

**Comment by freddyucv** [comment]
**Doc : Needs Doc**: We need to update this

https://www.dotcms.com/docs/latest/pushing-users

**Comment by victoralfaro-dotcms** [comment]
Sender users:
![image](https://user-images.githubusercontent.com/64026161/180888491-89b87e36-479f-458b-bd7a-717aa00d16a8.png)
Receiver users:
![image](https://user-images.githubusercontent.com/64026161/180888616-182e4089-c9f9-4071-a42b-bc16c8328c10.png)
Details at sender's publish queue:
![image](https://user-images.githubusercontent.com/64026161/180888801-a794014d-0cfe-48a8-8ca2-0881524e55e1.png)
Pushed user at receiver:
![image](https://user-images.githubusercontent.com/64026161/180888875-7e1435c2-80bb-4661-9558-a035cf5b73ce.png)

**Comment by bryanboza** [comment]
Fixed , tested on release-22.07 // Docker // FF. Now I'm able to push a single user using this button without problems
