### ISSUE TITLE
Contentlet loosing in the page after layout change

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22140]
**Describe the bug**
When create a new page, add content and change the layout the content get's lost

**To Reproduce**
1. Create a new page
2. Add content
3. Edit the layout and add a new box + container (Default)
4. Back to edit and see the content lost

https://user-images.githubusercontent.com/751424/166516269-ddbe253b-bca1-43e2-9608-c3f1bbded38b.mp4

**Expected behavior**
Content should never get lost in the page.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes, tested on release-22.06 // Docker // FF

**Comment by erickgonzalez** [comment]
Test these issues after backporting https://github.com/dotCMS/core/issues/23181 and https://github.com/dotCMS/core/issues/23180

**Comment by erickgonzalez** [comment]
Not reproducible in 21.06 LTS
