### ISSUE TITLE
Access Image Version Path from Right Click

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#22146]
**Is your feature request related to a problem? Please describe.**
Some customers use the image "version path" quite often for queries. It takes a few clicks to access the version path (right click edit image, click info on the image, then copy/past the path), which can be tedious for consistent use. 

**Describe the solution you'd like**

Ideally, the version path could be accessible or copy/pasted directly from the right click options on the image

**Describe alternatives you've considered**

There could be an option for the version path of an image to be displayed as part of the sort values that are shown by default in the browser tree.

**Additional context**

![Screen Shot 2022-05-04 at 7 15 47 AM](https://user-images.githubusercontent.com/90852779/166700577-9a8083dc-f24f-4606-80bd-300b0d29c8a9.png)

![Screen Shot 2022-05-04 at 7 16 41 AM](https://user-images.githubusercontent.com/90852779/166700765-613b183e-6215-411b-8ed3-db894ba9bf84.png)

![Screen Shot 2022-05-04 at 7 16 55 AM](https://user-images.githubusercontent.com/90852779/166700800-eda4a50a-b1c0-4417-8989-b68d84ed4bee.png)

This has been requested by a customer: https://dotcms.zendesk.com/agent/tickets/107194

**Comment by dankusner** [comment]
Another option vs right click is to have the value appear as one of the columns in the list view.  We just need easier access to a copyable display of the url.

**Comment by rjvelazco** [comment]
PR: #22286

**Comment by fmontes** [comment]
This code breaks the site browser, we have to build twice to make it work... @jcastro-dotcms will be working in a fix.

**Comment by jcastro-dotcms** [comment]
Second PR created to avoid random JS issue: https://github.com/dotCMS/core/pull/22494

**Comment by bryanboza** [comment]
Fixed, tested on release-22.-7 // Docker // FF
