### ISSUE TITLE
Allow greater configuration of S3Client to target additional endpoints beyond AWS

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22151]
**Is your feature request related to a problem? Please describe.**
There are multiple different S3 Object stores available beyond AWS. These all still utilize the S3 SDK from AWS, so we should be able to allow configuration of our S3Client to target endpoints that are not in AWS.

Related Ticket: https://dotcms.zendesk.com/agent/tickets/107260

**Describe the solution you'd like**
Allow configuration of the endpoint similar to how we allow configuration of bucket names, region etc. 

We should be able to change the targeted endpoint here, in AWSS3Storage: 

```
private AWSS3Storage(DotAmazonS3Client s3client) {
     this.s3client = s3client;
     this.s3client.setEndpoint("xxx");
```
While I think we should still only officially support AWS S3 buckets, allowing endpoint configuration would give a lot more options for pushing to various S3 Object stores in dotCMS.

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22151?planning-poker) with Zenhub @freddyucv @victoralfaro-dotcms

**Comment by freddyucv** [comment]
We need to support a new property here:

<img width="574" alt="Screen Shot 2022-12-08 at 09 04 56" src="https://user-images.githubusercontent.com/10408015/206482592-cfffbb4d-32cb-482a-9144-edf2ab95e250.png">

something like aws_end point, this new property must not be showed there because is optional but we need to doc it

Also we need to support a new attribute here to storage the endpoint

https://github.com/dotCMS/enterprise/blob/afa92d030c54a4840b603b06b686e53b0022a6b2/src/main/java/com/dotcms/enterprise/publishing/staticpublishing/AWSS3Configuration.java#L9

to be use here:

https://github.com/dotCMS/enterprise/blob/74eb783e5e7527617d231c32397f48a3d2020e26/src/main/java/com/dotcms/enterprise/publishing/staticpublishing/AWSS3EndPointPublisher.java#L60

We have to places where we need to set this new attribute

- https://github.com/dotCMS/core/blob/7cab67f0185a33d988cfd24f71fc2cbb5fff3326/dotCMS/src/main/java/com/dotcms/publisher/endpoint/bean/impl/AWSS3PublishingEndPoint.java#L68
- https://github.com/dotCMS/enterprise/blob/74eb783e5e7527617d231c32397f48a3d2020e26/src/main/java/com/dotcms/enterprise/publishing/staticpublishing/AWSS3Publisher.java#L434

**Comment by freddyucv** [comment]
Note to QA: Tested with https://play.min.io/

Configuration:

aws_access_key=GpBxrREx1679hl4k
aws_secret_access_key=0nm7Y8htIPO1Rnon6YfGb1jBQ199x4Zj
aws_bucket_name=dotcms-bucket-{hostname}-{languageIso}
aws_bucket_region=us-east-1
aws_endpoint=https://play.min.io/

You can create you own acces_key and secret going into https://play.min.io/
userName: minioadmin
password: minioadmin

**Comment by freddyucv** [comment]
PR:

core: https://github.com/dotCMS/core/pull/23589
ee: https://github.com/dotCMS/enterprise/pull/894

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise/pull/895

**Comment by oidacra** [comment]
Tested with DigitalOcean

<img width="1236" alt="Screenshot 2022-12-20 at 2 11 50 PM" src="https://user-images.githubusercontent.com/1909643/208747730-ba3ab62c-9069-4fab-a3e3-52a47a2e48d9.png">

**Comment by oidacra** [comment]
I had 2 errors in my machine, but I don't know is related to my machine is M1.
1) 
```13:34:00.215  ERROR csspreproc.CSSPreProcessServlet - Exception while serving compiled css file '/application/themes/travel/css/styles.scss' : null
java.lang.NullPointerException: null
	at com.dotcms.csspreproc.CSSPreProcessServlet.writeResponseData(CSSPreProcessServlet.java:257) ~[dotcms_master_999999.jar:?]
	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:215) ~[dotcms_master_999999.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor950.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.dotcms.enterprise.publishing.bundlers.a.a(SourceFile:331) ~[ee-master-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.a.generate(SourceFile:133) ~[ee-master-SNAPSHOT.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:140) ~[dotcms_master_999999.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:64) ~[dotcms_master_999999.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:191) ~[dotcms_master_999999.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]`


```
13:34:00.221  ERROR business.PublisherQueueJob - An error occurred when trying to publish bundles: 'long com.luciad.imageio.webp.WebPEncoderOptions.createConfig()'
java.lang.UnsatisfiedLinkError: 'long com.luciad.imageio.webp.WebPEncoderOptions.createConfig()'
	at com.luciad.imageio.webp.WebPEncoderOptions.createConfig(Native Method) ~[dot.webp-imageio-core-0.1.5.jar:?]
	at com.luciad.imageio.webp.WebPEncoderOptions.<init>(WebPEncoderOptions.java:26) ~[dot.webp-imageio-core-0.1.5.jar:?]
	at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.java:30) ~[dot.webp-imageio-core-0.1.5.jar:?]
	at com.dotmarketing.image.filter.WebPImageFilter.runFilter(WebPImageFilter.java:36) ~[dotcms_master_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.exporter.ImageFilterExporter.runFilter(ImageFilterExporter.java:90) ~[dotcms_master_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.exporter.ImageFilterExporter.exportContent(ImageFilterExporter.java:60) ~[dotcms_master_999999.jar:?]
	at com.dotmarketing.servlets.BinaryExporterServlet.doGet(BinaryExporterServlet.java:403) ~[dotcms_master_999999.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.a(SourceFile:346) ~[ee-master-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.generate(SourceFile:117) ~[ee-master-SNAPSHOT.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:140) ~[dotcms_master_999999.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:64) ~[dotcms_master_999999.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:191) ~[dotcms_master_999999.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]
```

**Comment by erickgonzalez** [comment]
Let's backport this only to 23.01 LTS

**Comment by bryanboza** [comment]
Tested with the provided configuration and we are unable to push. 

Here the log error: https://gist.github.com/bryanboza/f17835008569947cd91b4f96c77d29ca

Tested on release-23.02 // Docker // FF

**Comment by freddyucv** [comment]
Test again with  digitaloceanspaces and it works

**Comment by wezell** [comment]
Also fixes the "Get Token" button being displayed when you edit the config.

![Screen Shot 2023-02-06 at 1 07 34 PM](https://user-images.githubusercontent.com/934364/217050911-d7456199-c90d-494a-800d-c2945db49eca.png)

**Comment by freddyucv** [comment]
Test again with two servers: 

- wasabisys: https://console.wasabisys.com/

  You need to use different URL when the bucket already exists or the bucket need to be created 

  The URL to use when the Bucket exists is https://s3.ap-northeast-1.wasabisys.com/<bucket-name>
  bucket-name is the  real bucket name
   When the Bucket does not exists is https://s3.ap-northeast-1.wasabisys.com

- digitalocean: https://cloud.digitalocean.com/

  You can use the same URL no matter whether the bucket exists or not  
  https://<bucket-region>.digitaloceanspaces.com

 bucket-region is the region where the Bucket was created if it exists and If the Bucket does not exists is the region where we want to created the bucket

Also both was test using the aws_validation_bucket property and it works good

**Comment by bryanboza** [comment]
Fixed, tested on releas-23.02 // Docker // FF 

We need to doc about the configurations

**Comment by bryanboza** [comment]
Seems we are not using the endpoint properly. We need some extra work here

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/enterprise/pull/898

**Comment by oidacra** [comment]
Tested:
<img width="1470" alt="Screenshot 2023-02-14 at 10 41 43 AM" src="https://user-images.githubusercontent.com/1909643/218786360-1ebe2eb1-f183-4495-b016-68d90eed7da8.png">

Logs:
```
10:38:28.804  INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublisherAPIImpl : [BundleID: 01GS897K194D6FK93MBWNM7B3V] Asset added to Push Publish Queue. Action: Publish, Asset Type: contentlet, Asset Id: 6c918e8e4d6dc0120c2326bd5a267291, User: dotcms.org.1
10:38:30.894  INFO  business.PublisherQueueJob -
10:38:30.894  INFO  business.PublisherQueueJob - Found 1 bundle(s) to process.
10:38:30.894  INFO  business.PublisherQueueJob -
10:38:30.894  INFO  business.PublisherQueueJob - Processing bundle: ID: 01GS897K194D6FK93MBWNM7B3V. Status: Starting. Publish Date: 2023-02-14 15:38:00.0
10:38:30.894  INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending.
10:38:30.894  INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublisherQueueJob : Pre-publish work started.
[class com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher]
10:38:30.912  INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublisherQueueJob : Pre-publish work complete.
10:38:30.913  INFO  util.PushPublishLogger - class com.dotcms.publishing.PublisherAPIImpl : [BundleID: 01GS897K194D6FK93MBWNM7B3V] Started Publishing Task
10:38:30.920  INFO  publishing.PublisherAPIImpl - Start of Bundler: b
10:38:30.920  INFO  publishing.PublisherAPIImpl - End of Bundler: b
10:38:30.920  INFO  publishing.PublisherAPIImpl - Start of Bundler: FileAssetBundler
10:38:30.920  INFO  bundlers.FileAssetBundler - +baseType:4  +(path:/test-title ) +(conhost:8a7d5e23-da1e-420a-b4f0-471e7da8ea2d  )
10:38:30.920  INFO  publishing.PublisherAPIImpl - End of Bundler: FileAssetBundler
10:38:30.920  INFO  publishing.PublisherAPIImpl - Start of Bundler: HTMLPageAsContentBundler
10:38:30.920  INFO  bundlers.HTMLPageAsContentBundler - +baseType:5 +(path:/test-title ) +(conhost:8a7d5e23-da1e-420a-b4f0-471e7da8ea2d  )
10:38:30.944  INFO  publishing.PublisherAPIImpl - End of Bundler: HTMLPageAsContentBundler
10:38:30.944  INFO  publishing.PublisherAPIImpl - Start of Bundler: URLMapBundler
10:38:30.944  INFO  bundlers.URLMapBundler - Start bundler
10:38:30.948  INFO  publishing.PublisherAPIImpl - End of Bundler: URLMapBundler
10:38:30.948  INFO  publishing.PublisherAPIImpl - Start of Bundler: BinaryExporterBundler
10:38:30.949  INFO  servlets.BinaryExporterServlet - Exporter "Content Image Fields Resizer" registered for path /resize-image
10:38:30.949  INFO  servlets.BinaryExporterServlet - Exporter "Export Field Content" registered for path /raw-data
10:38:30.949  INFO  servlets.BinaryExporterServlet - Exporter "Image Filter Exporter" registered for path /image
10:38:30.949  INFO  servlets.BinaryExporterServlet - Exporter "Image Thumbnail Field Exporter" registered for path /image-thumbnail
10:38:31.099  INFO  publishing.PublisherAPIImpl - End of Bundler: BinaryExporterBundler
10:38:31.099  INFO  publishing.PublisherAPIImpl - Start of Bundler: b
10:38:31.103  INFO  publishing.PublisherAPIImpl - End of Bundler: b
10:38:31.103  INFO  publishing.PublisherAPIImpl - Start of Bundler: e
10:38:31.103  INFO  servlets.BinaryExporterServlet - Exporter "Content Image Fields Resizer" registered for path /resize-image
10:38:31.103  INFO  servlets.BinaryExporterServlet - Exporter "Export Field Content" registered for path /raw-data
10:38:31.103  INFO  servlets.BinaryExporterServlet - Exporter "Image Filter Exporter" registered for path /image
10:38:31.103  INFO  servlets.BinaryExporterServlet - Exporter "Image Thumbnail Field Exporter" registered for path /image-thumbnail
10:38:31.108  INFO  publishing.PublisherAPIImpl - End of Bundler: e
10:38:31.289  INFO  util.PushPublishLogger - class com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher : Status Update: Bundle push starting
10:38:31.289  INFO  util.PushPublishLogger - class com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher : Status Update: Pushing bundle
10:38:31.289  INFO  staticpublishing.AWSS3Publisher - Pushed languages: [en-us]
10:38:31.505  INFO  staticpublishing.AWSS3EndPointPublisher - Creating bucket, name: aeq-testing-pp , Region: us-east-1
10:38:31.937  INFO  staticpublishing.AWSS3EndPointPublisher - Pushing File: /test-title, retries: 0
10:38:32.203  INFO  util.PushPublishLogger - class com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher : Status Update: Bundle sent
10:38:32.214  INFO  util.PushPublishLogger - class com.dotcms.publishing.PublisherAPIImpl : [BundleID: 01GS897K194D6FK93MBWNM7B3V] Completed Publishing Task
10:39:00.265  INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublisherQueueJob : Status Update: Success
10:39:00.269  INFO  business.PublisherQueueJob - ===========================================================
10:39:00.269  INFO  business.PublisherQueueJob - For bundle '01GS897K194D6FK93MBWNM7B3V':
10:39:00.269  INFO  business.PublisherQueueJob - -> Status             : SUCCESS [9]
10:39:00.269  INFO  business.PublisherQueueJob - ===========================================================
10:39:01.391  INFO  delegate.SystemEventsJobDelegate - The event: 6e394c7b-4f3f-493d-b148-9b9c7e150ca8, has been skipped on the server: ce2ad9a9-ad3c-4a10-a368-fb3f951b4699`

**Comment by josemejias07** [comment]
**Approved QA** - macOS 13.0 // FF v109.0.1

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_b5fd2762_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1

**Comment by dsilvam** [comment]
Note to QA: Only thing left to test is https://github.com/dotCMS/core/pull/24041

**Comment by erickgonzalez** [comment]
@bryanboza @josemejias07 please check this again in 23.03 since I think we have some missing changes in master, so in release-23.03 will be also missing

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_3d55dd2c_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0.1

@erickgonzalez 

![Screenshot 2023-03-10 at 10 35 40 AM](https://user-images.githubusercontent.com/110418590/224371707-f823370d-c0de-4114-87e9-0d6928ba2b2e.png)

**Comment by erickgonzalez** [comment]
Tested in Wasabi and Digital Ocean.

**Comment by erickgonzalez** [comment]
Worth to test against AWS as well to check nothing is broken.
