### ISSUE TITLE
If there isn't space after `data-identifier` breaks edit contentlet  

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22157]
**To Reproduce**
1. Create a new content of Rich Text
2. Change the Wysiwig view to Code and paste the following code:
```
<img src="/dA/7f71124d8d/shark-feeding.jpeg" alt="shark-feeding.jpeg" data-field-name="asset" data-inode="7f71124d-8dd8-4081-b6a0-eb036464e940" data-identifier="1acf2998-b36d-4dd7-bb73-06ce2531ee09"/>
```
4. Save and Publish
5. Try to edit the content again, see the error

If you add this content to any page, you'll see that the content renders without issues.

**Expected behavior**
The issue seems to be here https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/browser/BrowserUtil.java#L183
That method only splits by space and since there is no space after the UUID of the data-identifier it gets all instead of only the UUID.

Also, we should check if the identifier is NULL here https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/browser/BrowserUtil.java#L169

Reproducible in 22.03 and demo (22.05)
Customer ticket: https://dotcms.zendesk.com/agent/tickets/107265

**Comment by erickgonzalez** [comment]
Customer hitting this: https://dotcms.zendesk.com/agent/tickets/111210

Also, a new workaround was found: `Also, we found that changing the attribute from "data-identifier" to "data-contentletidentifier" also fixes the issue.`

**Comment by waqasakramdot** [comment]
Customer hitting this again: https://dotcms.zendesk.com/agent/tickets/112614
