### ISSUE TITLE
SAML: Redirect is not working

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#22156]
When dotCMS is configured with SAML, and the original request is not dotAdmin (another url)
dotCMS should recall the original request as soon as get login

Currently it is always redirecting to dotAdmin

**Comment by swicken-dotcms** [comment]
Related ticket: https://dotcms.zendesk.com/agent/tickets/107268

**Comment by bryanboza** [comment]
Fixed, I did smoke testing over the app, using SAML and it works as expected.

**Comment by erickgonzalez** [comment]
customer hitting this: https://dotcms.zendesk.com/agent/tickets/108546

**Comment by erickgonzalez** [comment]
marking this as excluded b/c we haven't seen this in 21.06 LTS
