### ISSUE TITLE
Correct the generated REST URLs from Content Search "Show Query" 

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#22168]
**Describe the bug**
On demo.dotcms.com, going to Content -> Search -> "Show Query" generates REST URLs like so
`http://demo.dotcms.com:8082/api/content/render/false/query/title:blog...`

There are a few issues 
1)  `:8082`
2) `demo.dotcms.com` - as best I can tell this is the host name of the Default site. 
      Perhaps this should this be the Basic Config -> Portal URL? Not sure.
3) `http` scheme is incorrect even though we are using the `https` Tomcat connector port

Maybe best/simplest to just provide an absolute path like
`/api/content/render/false/query/title:blog...`

**Comment by swicken-dotcms** [comment]
In working on this we should look at how we show queries for child->parent queries. 

Currently when you filter to a parent on the search portlet it shows queries like this: 
```
Velocity Content Pull (cut and paste for use in a Widget):
#foreach($con in $dotcontent.pull("+contentType:Blog +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +identifier:(a7df3f39-a18a-4b16-b369-aa9d7acb0b27 OR 0edfee78-2a75-4f3d-bf20-813aae15d4e9 OR 2b100ac7-07b1-48c6-8270-dc01ff958c69 OR 3d6fa2a4-2b48-4421-a2f5-b6518a7c0830)",10,"score,modDate desc"))
...
#end
```
This query isn't valid, it's a hardcoded list of identifers. If you added another relationship it wouldn't be captured here. For child->parent relationships the example should be pullRelatedField, not pull.

**Comment by dsilvam** [comment]
Passed Internal QA. 
* Now it's showing a relative path without including the host and port for the REST API URL
* When filtering by one or more relationship fields, it's properly including a pull related for each rel field that users can use to narrow the search and match the results of the search.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF

**Comment by bryanboza** [comment]
Now we have a relative path in the `REST API Call URLEncoded` but we still having the same thing in the `REST POST API Curl Call`. We need some work here 
![image](https://user-images.githubusercontent.com/2641437/182421000-766fd74f-7d54-4c3c-870c-03a0737b8901.png)

**Comment by dsilvam** [comment]
Passed Internal QA: now working with full url.

**Comment by bryanboza** [comment]
We still getting problems here: 

 - Now when you try to use the API link we are doing the call, but we are opening it in a new tab with the `about:blank` title

![image](https://user-images.githubusercontent.com/2641437/182483227-29f83666-cfa9-4776-ae90-c6ecb61e4aba.png)

**Comment by bryanboza** [comment]
Fixed, the pending request was moved to a new card: #22681 

Tested on release-22.07 // Docker // FF
