### ISSUE TITLE
DotCMS Cors redirect request not Access-Control-Allow-Origin pararm

### ISSUE THREAD

**Issue by fchenxi** [dotCMS/core#22166]
**Describe the bug**
Add config from https://www.dotcms.com/docs/latest/cors-header-configuration Setting Global CORS Headers, but in site redirect to a image cdn, with 403  Referrer Policy: strict-origin-when-cross-origin

**Screenshots**
as image:

![屏幕快照 2022-05-06 下午11 15 03](https://user-images.githubusercontent.com/7944322/167162876-3c46a968-da61-40a4-b346-c01a7aedae2b.png)

![屏幕快照 2022-05-06 下午11 15 14](https://user-images.githubusercontent.com/7944322/167162912-603cf4d4-6798-46a1-80ea-0e2a1ed5aa3f.png)

**Desktop (please complete the following information):**
 - OS: mac 10.13
 - Browser chrome
 - Version dotcms 5.3.8

please help how to solve 403 cors. thanks a lot.

**Comment by fchenxi** [comment]
add my dotmarketing-config.properties

## Sets default cors headers for dotCMS APIs
## api.cors.default.xxxx:yyy
## will be sent by default as a header, e.g
## api.cors.default.access-control-allow-origin=*         --> Access-Control-Allow-Origin : *
## api.cors.default.access-control-max-age=*              --> Access-Control-Max-Age : 0
## api.cors.default.access-control-allow-credentials=true --> Access-Control-Allow-Credentials:true
api.cors.default.Access-Control-Allow-Origin=*
api.cors.default.Access-Control-Allow-Methods=GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH
api.cors.default.Access-Control-Allow-Credentials=true
api.cors.default.Access-Control-Allow-Headers=*
api.cors.default.Access-Control-Expose-Headers=*


api.cors.default.access-control-allow-origin=* 
api.cors.default.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.default.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS

## You can also set headers per resource by specifying the resource name (java class name lowercased), e.g. for the contentresource
# api.cors.contentresource.access-control-allow-origin=https://demo.dotcms.com
# api.cors.contentresource.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
# api.cors.contentresource.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS


api.cors.contentresource.access-control-allow-origin=*
api.cors.contentresource.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.contentresource.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS

## XSS PROTECTION FOR ADMIN SCREENS

# In order to minimize XSS and CSRF vunerabilities, dotCMS will block direct access to all files under the /html and /dotAdmin directories
# unless dotCMS is sent a valid referer (or Origin) header.  This is enabled by default but it can be turned off by this property:

# XSS_PROTECTION_ENABLED=false

**Comment by fchenxi** [comment]
add my dotmarketing-config.properties config
api.cors.default.Access-Control-Allow-Origin=*
api.cors.default.Access-Control-Allow-Methods=GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH
api.cors.default.Access-Control-Allow-Credentials=true
api.cors.default.Access-Control-Allow-Headers=*
api.cors.default.Access-Control-Expose-Headers=*


api.cors.default.access-control-allow-origin=* 
api.cors.default.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.default.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS

api.cors.contentresource.access-control-allow-origin=*
api.cors.contentresource.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.contentresource.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS

**Comment by wezell** [comment]
Those cors are only for the apis - maybe try adding the `strict-origin-when-cross-origin` using a rule?

**Comment by fchenxi** [comment]
add config works

api.cors.default.access-control-allow-origin=*
api.cors.default.access-control-max-age=*
api.cors.default.access-control-allow-credentials=true

api.cors.default.Access-Control-Allow-Origin=* always
api.cors.default.Access-Control-Allow-Methods=GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH
api.cors.default.Access-Control-Allow-Credentials=true
api.cors.default.Access-Control-Allow-Headers=*
api.cors.default.Access-Control-Expose-Headers=*


api.cors.default.access-control-allow-origin=* always
api.cors.default.access-control-allow-headers=Authorization, Accept, Content-Type, Cookies, Content-Type, Content-Length
api.cors.default.access-control-allow-methods=GET, HEAD, POST, PUT, DELETE, OPTIONS

but which one works?
