### ISSUE TITLE
set the allowUnrecognizedProperties option in our jackson ObjectMapper to keep backwards compatibility  

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#22174]
**Describe the bug**
The most recent version of dotCMS introduced a `modelVersion` attribute that didn't exist in prior versions using the contentlet as json. We want to be able to run against older versions of dotCMS that lack such properties. And prevent any potential situation if 
new attributes are added down the road. 

**To Reproduce**
The problem basically occurs when you run a dotCMS version greater than 22.03 create a piece of content that gets stored as json and then go back to a prior version keeping the same db 

**Expected behavior**
We should be able to continue to use dotCMS even on an older version that support contentlet as json

**Additional context** 
sample stack trace:
```
rkflows, Personalization, Multilingual, I18N, L10N,"[truncated 861 chars]; line: 1, column: 1336] (through reference chain: com.dotcms.content.model.ImmutableContentlet$Json["modelVersion"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla
```

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/22175

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Note to QA:** Considering that this fix isn't included in older versions, I tested this way: 
1. Deploy a dotCMS instance (22.06) using full starter
2. Go to the database to add a new field to the `contentlet_as_json`: 

```
update contentlet 
set contentlet_as_json = jsonb_set(contentlet_as_json, '{nollys_field}', '"completed"')

/*Make sure your new field was included to any piece of content*/
select contentlet_as_json from contentlet where inode={REPLACE_BY_INODE}
```

4. Restart the server. You should not see the exception described above.
