### ISSUE TITLE
Inline editing allows you to edit content displayed by relationship, but publishing the page doesn't publish the related content

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22173]
**Describe the bug**
When using inline editing on a page in a container that displays related content, you can add the ability to edit the related content, however that content is not published when the page is published leaving the related content in a working state and not reflecting the changes on a live page.

Related Ticket: https://dotcms.zendesk.com/agent/tickets/107280

Reproduced on: 22.03

**To Reproduce**
1. From a demo starter, Edit the `Banner` content type and add a relationship field to the content type `Device`
2. Relate the `Banner` contentlet on the index page (identifier `2e5d54e6-7ea3-4d72-8577-b8731b206ca0`) with a `Device`
3. Edit `banner.vtl` in `/application/containers/banner/`
4. Make relationship field `Name` visible and editable in  the `banner.vtl` file
```
   #foreach( $content in $dotcontent.pullRelatedField( "$!{ContentIdentifier}", "Banner.device", "*" ) )
                             <div class="group-lg">
                        
                        <a class="button button-primary button-leaf" href="$link"
                        #if ($EDIT_MODE)
                                data-language="${CONTENT_LANGUAGE}"
                                data-mode="minimal"
                                data-inode="${content.inode}"
                                data-field-name="name"      
                            #end
                        >$content.name</a>
                    </div>
                    #end
```
5. Open the index page make an edit on the relationship field `Name`.
6. Publish the page.
7. Go to [demo.dotcms.com](http://demo.dotcms.com/) and check the edit relationship field `Name` text changes not reflected.
8. Open the index page for editing again
9. Click the Edit button on the `Banner` contentlet
10. Click on Device relationship to open that contentlet (A warning popup will appear, click OK)
11. See changes reflected on the Device contentlets `Name` field
12. Click the publish button of Device contentlet.
13. Go to [demo.dotcms.com](http://demo.dotcms.com/) and check the relationship field `Name`, the text changes are now properly reflected.

**Expected behavior**
Any inline changes that are done should be published when hitting the publish button on the page. Content editors will not be aware of which individual fields are related fields, so when they do not update after publishing it will generate confusion.

We need to figure out how to be aware of related content that is shown on a given page, and run a Publish on those contentlets when the page us published.

**Comment by hmoreras** [comment]
There is a workaround to fix this: 

1. Go to `Workflows` - `System Workflows`. 
2. Got to `Save`. 
3. Add the sub-action `Publish Content`
4. Now inline editing in the related content and then publish, should work. 

There will be a new issue to fix this with an extra data attribute. https://github.com/dotCMS/core/issues/22241

**Comment by fmontes** [comment]
A bit of context

1. When the inline editing save the content it triggers the default workflow action
2. When you publish dotCMS page, it publishes all the direct content in the page but not the related ones.

Typically, the content types default workflow action is "Save", so when the inline edit save it doesn't publish.

So the workaround is what @hmoreras proposed in the comment: https://github.com/dotCMS/core/issues/22173#issuecomment-1129356595
