### ISSUE TITLE
How to include custom blocks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22171]
**Is your feature request related to a problem? Please describe.**
As a user and developer, I want to be able to add new blocks to my editor.

Adding new blocks will allow fellow content creators to add special content for our use case.

For example, we would like to add a block to search and insert YouTube videos, or tweets or some company information from external APIs.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
We need to find a way where developers can give us a URL of a JavaScript file, that file will contain the block code, and we initialize that.

If not a URL, we can ask them to upload the files in some folder in dotCMS, and we get it from there.

**Additional context**
This is a research issue.

**Comment by fmontes** [comment]
**On the Angular / Web Components side**

1. Developers will create their own blocks, here is [an example](https://prosemirror.net/examples/dino/)
2. Create an `init` method in the web component
3. The `init` will receive an array of blocks
4. It will initialize the editor with the receives blocks.

**On the JSP side**
1. Using [JavaScript modules,](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) we'll import the user's custom blocks from an URL (dotCMS or external)
2. Get the web component
3. Call the `init` method with the array of imported blocks (JavaScript modules)

**Comment by rjvelazco** [comment]
**On the Angular side**
We can create a `@input()` method that allows us to send the custom blocks from the  `JSP` side. Here is an example approach:

- File: `apps/dotcms-block-editor/src/app/dot-block-editor/dot-block-editor.component.ts`
- Code:
<img width="1680" alt="angular-method" src="https://user-images.githubusercontent.com/72418962/167199860-9fb0a7a4-60ee-43d1-b6d1-3fc1f31632c3.png">

**On JSP side**
We can get the `dotcms-block-editor` component and call the method:

- File: `dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp`
- Code:
<img width="1680" alt="JSP-side" src="https://user-images.githubusercontent.com/72418962/167200294-f05ebfc7-1c0b-4a1e-b8c2-c1379969dd7c.png">

**Comment by wezell** [comment]
It would be good to allow custom marks as well.

**Comment by fmontes** [comment]
Close in favor of the EPIC
