### ISSUE TITLE
Create osgi system framework

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22184]
We need to create a different "system" osgi framework that we use to load our system bundles.  It should be as small a framework as possible, with the minimal bundles needed in order to run.  This framework should start up once on startup - and we will need it started to load and reindex our starter - and should really never unload or restart.

It should hold the SAML bundle and the Tika bundles and that should be it.

**Comment by bryanboza** [comment]
Fixed, tested with multiple plugins and now it still working as expected.
