### ISSUE TITLE
Rules do not display if a condition specifies a request header not on list

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22186]
If you select a condition that checks for a request header that is not on the list, and refresh the portlet, the select control will not display.

**Comment by wezell** [comment]
Also, selecting "Visitors Country" from the condition list refreshes the screen

**Comment by alfredo-dotcms** [comment]
when selecting `Visitors Country` BE throws a 400 error
![image](https://user-images.githubusercontent.com/37185433/168133745-3b86a100-4e68-4fac-bdaf-225ee9ca1c07.png)

with error description:
`error: "dotcms.api.error.bad_request: Could not create Component Instance of type UsersCountryConditionlet from provided model Condition [id=d28fffde-2cac-4da7-8019-30089d737ef7, conditionletId=UsersCountryConditionlet, conditionGroup=246fe53e-b9c3-4f1b-8d1a-84a49a381193, values=[ParameterModel [id=null, ownerId=null, key=comparison, value=is, priority=0], ParameterModel [id=null, ownerId=null, key=country, value=null, priority=0]], modDate=2022-05-12 17:25:27.709, operator=AND, priority=1]: validation failed for parameter 'country'"`

**Comment by alfredo-dotcms** [comment]
PRs: 

core-web: https://github.com/dotCMS/core-web/pull/1983/files

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me passing it.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes, tested on release-22.07 // Docker
