### ISSUE TITLE
Task220330 ChangeVanityURLSiteFieldType is running although you are in the last DB version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22199]
We are getting an error when you try to upgrade a server that already has the VanityURL changes introduced in the last starter `https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20220504/starter-20220504.zip`,  then we are trying to run this task, this is returning an empty value and is breaking the server and you are unable to start. 

We need to add a validation to skip that in case you are already in the last DB version. 

**To Reproduce**
- Start a server with the last starter site 
- Try to upgrade to master or to release-22.06 image
- You will have the error in the log file and the server is unable to start

**Expected behavior**
We need skip this task if you already in the last DB version

**Desktop (please complete the following information):**
Tested upgrading from 22.05 to master or 22.06 image // Docker // FF

**Comment by wezell** [comment]
@freddyucv exactly - ideally, upgrade tasks should be idempotent and should be able to be run multiple times without error

**Comment by dsilvam** [comment]
Another PR: https://github.com/dotCMS/core/pull/22302

**Comment by freddyucv** [comment]
**Note to QA:** Test doing a upgrade from 22.03

**Comment by dsilvam** [comment]
Passed Internal QA: https://github.com/dotCMS/core/issues/22282#issuecomment-1159067437

**Comment by bryanboza** [comment]
Fixed, tested upgrading from 22.03 to 22.06. Everything works as expected now.
