### ISSUE TITLE
We are changing the relationship selection once that you create the field

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22198]
When you are creating a new relationship and select the `many to many` options, after you create the filed and then try to edit again, we are changing that selection to `one to many`

https://dotcms.slack.com/files/U028X160J/F03EU0XBWRK/screen_recording_2022-05-10_at_4.20.53_pm.mov

**Expected behavior**
We need to keep the selection without problems 

**Desktop (please complete the following information):**
Tested on release-22.05 // Docker // FF

**Comment by oidacra** [comment]
Works as expected. The behavior was fixed.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF

**Comment by erickgonzalez** [comment]
Not reproducible in 5.3.8 nor 21.06 LTS
