### ISSUE TITLE
Import external images into dotCMS as dotAssets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22194]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to import external images into dotCMS system.

**Describe the solution you'd like**
We need to download the images and upload it as a `dotAsset`. Nothing too fancy, just a one click interaction.

https://user-images.githubusercontent.com/751424/167741509-341f7c8f-6f60-4274-a7a7-3e3102955614.mp4

**Error handling**

https://user-images.githubusercontent.com/751424/167741969-15468563-8156-4ceb-9762-6bb75f7988d3.mp4

**Describe alternatives you've considered**
N/A

**Additional context**
We already have all the plumbing to do the upload we do it with the `dotAsset` image, we need to reuse all that.

**Figma**
- [Prototype](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=310%3A8774&node-id=2554%3A34509&viewport=241%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=2554%3A34509&show-proto-sidebar=1)
- [Prototype Error](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=310%3A8774&node-id=2554%3A34593&viewport=241%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=2554%3A34573&show-proto-sidebar=1)

- [Design](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2554%3A34509)
- [Design Error](https://www.figma.com/file/xyjX828sx4rbAdjOB06dTG/DotCMS?node-id=2554%3A34573)

**Comment by fmontes** [comment]
As per Will, all the images will be `dotAsset`, no external blocks or manual import will be required.

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/23348

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_a953eb1e_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0
