### ISSUE TITLE
Move To Dart Sass

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22196]
Libsass is deprecated and not cutting it for us anymore.  We need to move to use dart sass.  This process would look like:

1. In our docker image build, wget the latest version of dart sass from github based on arch type.  Stick it somewhere knowable, e.g. under `WEB-INF/bin`.  Binaries can be found here: https://github.com/sass/dart-sass/releases/tag/1.50.0
2. Rewrite the `DotLibSassCompiler` to shell out and call dart sass under the covers.
  - we might need to pass the `--load-path=` option for each subfolder that is included in the sass compilation
3. return the resulting CSS
4. Remove jsass and libsass from our proj
### Things to note
1. If there is an error in the css style sheet, lets try to spit that error to the user if they are logged in.  We do this now with libsass.
3. We probably want to provide a config variable that if set can override the path to dart-sass binary.

### Things to test
1.  As a test, please make sure we can compile Bootstrap 5 out of the box.
2. The `DotLibSassCompiler` would break on compiling the latest foundation.  We need to test that the Dart impl can compile that successfully 
3. We need to insure that this runs on both intel linux and arm64 linux docker images

## Steps To Reproduce - Scenario 1
1. Start up dotCMS via Docker with our Demo Starter, and open up any page. All of them must load just fine, with all the CSS showing up as expected.

## Steps To Reproduce - Scenario 2
1. Start up dotCMS via Docker with the Empty Starter and a valid license.
2. Upload the Test Bundle [attached to my comment below](https://github.com/dotCMS/core/issues/22196#issuecomment-1234653561). It contains all the required Foundation 6 folders, the test Template, and the test HTML Page for testing.
3. Open up the `/test` page and make sure that you see the plain non-styled HTML Page first.
4. Go to **Site > Templates** and open up the `Foundation Template`. Un-comment the style sheet reference in line # 7.
5. Go back to the `/test` page and make sure that you're seeing the CSS styling showing up.

## Steps To Reproduce - Scenario 3
1. Coordinate with @manuel-miranda to set up an AWS Graviton instance with the Demo Starter. All test pages in there must load just fine.
2. After that, ask Manuel to reset the environment to use the Empty Starter, upload a valid license, and upload [the same test bundle from my comment below](https://github.com/dotCMS/core/issues/22196#issuecomment-1234653561). Make sure it works as well.

**Comment by jcastro-dotcms** [comment]
Foundation 6 test bundle: [foundation-6-test-page.zip](https://github.com/dotCMS/core/files/9472502/foundation-6-test-page.zip)

**Comment by fmontes** [comment]
The bundle didn't create a template for me so I did it manually with this code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/application/themes/foundation/assets/foundation.dotsass" />
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>
```

**Comment by bryanboza** [comment]
Step 1: 
Tested with the last docker image at at page level everything still running normally 

Step 2: 
Tested with the provided bundle and I'm able to see the style without problems 
![Image](https://user-images.githubusercontent.com/2641437/188238030-42f73c46-27bf-4979-a54a-4a3112021114.png)

**Comment by bryanboza** [comment]
Fixed, tested on AWS instances and also tested the static push and everything still working as expected. 

Here the bundle pushed to S3 instance:
![image](https://user-images.githubusercontent.com/2641437/189700744-b2508ccb-519f-4311-81b2-bab1e239f3d3.png)

Tested on release-22.09 // Docker // FF
