### ISSUE TITLE
Time penalization is not working when you try wrong attempts in the login window 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22202]
When you do a wrong attempt in the login window, we need to set a time penalization that should be increased in every wrong attempt. This is not working right now which is wrong because we are able to set up a boot to test credentials by brute force.

**To Reproduce**
- Setup a server locally 
- In the login window try different wrong credentials 
- Make sure every attempt the time penalization is increasing 

**Expected behavior**
We need to increase this time exponentially in every wrong attempt 

**Desktop (please complete the following information):**
Tested on release-22.06 // Docker // FF

**Comment by wezell** [comment]
We turned the exponential time increase off and fixed it to 2sec.
