### ISSUE TITLE
Disable system container row in the listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22217]
**Is your feature request related to a problem? Please describe.**
As a stakeholder, I don't want users to be able to edit the system container.

Recently, we move the system container from file to memory, so now is not editable. https://github.com/dotCMS/core/issues/21853

**Describe the solution you'd like**
Make the row look disabled, remove the three-dot contextual button and disable the click.

**Mock**

<img width="1548" alt="Screen Shot 2022-05-12 at 14 54 19" src="https://user-images.githubusercontent.com/751424/168167201-21c01208-dbd9-4e78-975d-e5c364729617.png">

**Additional Context**
This is JSP work.

**Comment by fmontes** [comment]
@jcastro-dotcms make the work to the container being returned in the list, now we have to do the frontend.

**Comment by hmoreras** [comment]
PRs: https://github.com/dotCMS/dotcms-dojo-theme/pull/86
https://github.com/dotCMS/core/pull/22254

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
