### ISSUE TITLE
Experiments Feature - Backend Experiment Setup Steps & Workflow, Epic

### ISSUE THREAD

**Issue by dotCMSJack** [dotCMS/core#22223]
This epic, for the Experiments features \(a.k.a. A/B Testing\), includes the work related to UI/UX Development. For the A/B Test setup steps and workflow.

**Comment by jack-diego** [comment]
[Spec AB Testing May11.pdf](https://github.com/dotCMS/core/files/8688692/Spec.AB.Testing.May11.pdf)
