### ISSUE TITLE
Experiments Feature - Reporting Back-End, Epic

### ISSUE THREAD

**Issue by dotCMSJack** [dotCMS/core#22227]
Back-End/Reporting plumbing for Experiments feature. This includes ingesting data into the appropriate DB and DB structure/architecture. This epic also includes all work that will enable the UI/UX team to build & display reports on the appropriate pages.

**Comment by jack-diego** [comment]
[Spec AB Testing May11.pdf](https://github.com/dotCMS/core/files/8688675/Spec.AB.Testing.May11.pdf)
