### ISSUE TITLE
Experiments Feature - Data Collection, Epic

### ISSUE THREAD

**Issue by dotCMSJack** [dotCMS/core#22222]
This epic, for the Experiments features \(a.k.a. A/B Testing\), includes the work related to Data Collection and the mechanism\(s\) we'll use. This data-collection mechanism, whether it's a javascript page tag or server-side collection mechanism, needs to be flexible to be used for any feature, not just for A/B Testing Experimentation.

**Comment by jack-diego** [comment]
[Spec AB Testing May11.pdf](https://github.com/dotCMS/core/files/8688694/Spec.AB.Testing.May11.pdf)
