### ISSUE TITLE
Experiments Feature - Test Type & Calculation, Epic

### ISSUE THREAD

**Issue by dotCMSJack** [dotCMS/core#22225]
Test Type - Bayesian inference, plus Multi-Armed-Bandit functionality. Will suggests using this: https://content.clickhouse.tech/docs/en/sql-reference/functions/machine-learning-functions/#bayesab 

Question: If we're going to use Bayesian Inference, do we use Beta or Gamma distribution? (I think beta is for variables/outcomes that are integers, and gamma is for integers + non-integers)

**Comment by jack-diego** [comment]
Will suggests using this: https://content.clickhouse.tech/docs/en/sql-reference/functions/machine-learning-functions/#bayesab

**Comment by jack-diego** [comment]
[Spec AB Testing May11.pdf](https://github.com/dotCMS/core/files/8688684/Spec.AB.Testing.May11.pdf)
