### ISSUE TITLE
Experiments Feature - Traffic Split Mechanism, Back-end, Epic

### ISSUE THREAD

**Issue by dotCMSJack** [dotCMS/core#22226]
Mechanism for driving traffic to the test variations. Need to first split the overall traffic percentage \(example, 5% of total traffic\) into the test, as set/specified by the customer. Then, we need to split the test traffic to each of the variations, as set by the customer.

Stretch goal: the Overall Traffic Split can also be required to fit certain rules \(similar to personalization\). Example, if the visitor is from USA, then they can be included in the test traffic. If not, then the visitor will be excluded.

**Comment by jack-diego** [comment]
[Spec AB Testing May11.pdf](https://github.com/dotCMS/core/files/8688680/Spec.AB.Testing.May11.pdf)
