### ISSUE TITLE
Limited User Can't Open Page if it has a content that doesn't have permissions over

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22237]
**Describe the bug**
If a limited user can edit/publish a page, but if that page contains content that doesn't have any permissions (but the content has cms anonymous), the limited user can't even open the page in BE.

```
15:31:57.679  INFO  util.SecurityLogger - class com.dotcms.rest.exception.mapper.DotBadRequestExceptionMapper : User:user-9f530a53-37eb-45eb-8a1e-891ab163c487 does not have permissions on Contentlet Contentlet[name: test content admin only, type: Rich Text, lang: 1 ,identifier: 6db826afbfb6aed182531bd2cde58665, inode: 22085dcb-8f3a-4b38-9ca8-16703c38bfcb] -- ip:127.0.0.1,user:testUser testUser [ID: user-9f530a53-37eb-45eb-8a1e-891ab163c487][email:testuser@dotcms.com]
```

**To Reproduce**
1. Create a Role, and add to it the Site Browser Tool.
2. Create a new user, give it BE, FE Roles, and also the created Role.
3. Create a new root folder e.g `testFolderPage` and give it the following permissions:
![FolderWhereThePageLivesPermissions](https://user-images.githubusercontent.com/5278970/168686789-75b22431-d0a9-4967-ae48-9e949f15d6ae.png)
4. Create a page inside it.
5. Create a new root folder, e.g `testFolderContent` and give it the following permissions:
![FolderWhereTheContentLivesPermissions1](https://user-images.githubusercontent.com/5278970/168686927-70f8562b-64d3-48c3-b986-6bf8dac9fc37.png)
6. Edit the site, to add the following permissions:
![SitePermissions](https://user-images.githubusercontent.com/5278970/168687277-d2cadc1c-0631-4f70-b9e3-86831927e5f9.png)
7. Create a new Rich Text content inside the `testFolderContent`.
8. Add the created content to the page, the admin user should look at the content:
![PageAsAdmin](https://user-images.githubusercontent.com/5278970/168687399-bd91b548-7c09-4c1a-935b-3e6bd19204f1.png)
9. log in as the limited user, and the site browser should look like this:
![SiteBrowserAsLimitedUser](https://user-images.githubusercontent.com/5278970/168687553-215d94f0-4732-4000-a517-711910a24825.png)
10. Try to open the page and get the error message:
![ErrorMessage](https://user-images.githubusercontent.com/5278970/168687589-8ec20a85-3a48-4e96-bfc2-38d461d5b64f.png)

**Expected behavior**
Should be able to edit a page that they have EDIT permissions on even if it has a piece of content on it that the user cannot edit

**Screenshots**

https://user-images.githubusercontent.com/5278970/168853812-275d5915-9388-4628-ac39-96fcb511e996.mov

Reproducible in 22.03 and 22.05.
Customer ticket: https://dotcms.zendesk.com/agent/tickets/107265

**Comment by wezell** [comment]
So, if a user has "READ" but not have "EDIT" on a piece of content that is on a page, we should show the content, allow the content to be re-ordered or added, but not show any of the edit controls for the content.

Users should also be able to reuse content that they only have read to - again, they should just not be able to edit it.

**Comment by wezell** [comment]
If the content in question has CMS_ANON read permissions, but not BACK_END READ permissions the user should be able to open and manage the page.  It is ok if the user gets an error when they try to edit the content

**Comment by rjvelazco** [comment]
I think I found a bug here. 

If I go to the `edit` page, I cannot edit the `admin content` but I can remove that content without having the right permissions. 

**To Reproduce**
1. Login as the `testUser`.
2. Go to the Page and Edit Content.
3. You are able to remove the `admin content`.  ([Full video here](https://www.loom.com/share/c5a727c0c8624f50806dc14963e59a93))

https://user-images.githubusercontent.com/72418962/175404745-cf779c46-b685-4861-afa2-06ca0e42be8f.mov

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now we are able to see the content in the page when you re login as a limited user. 
![image](https://user-images.githubusercontent.com/2641437/178841515-d56153a2-8a75-4f6f-8576-dc19240c3135.png)

Tested on release-22.07 // Docker // FF
