### ISSUE TITLE
Pagination not working when querying related content by Rest API

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#22236]
**Describe the bug**
When using the Content API with /related, /limit, and /offset path.
Changing the offset parameter does not do anything. As a result Content API always returns the same contentlets.

Related Ticket: https://dotcms.zendesk.com/agent/tickets/107332

Reproduced on: 22.03

**To Reproduce**
1. Go to `http://demo.dotcms.com/api/content/render/false/query/+contentType:Destination%20+languageId:1%20+deleted:false%20+working:true/orderby/score,modDate%20desc/related/Destination.activities:574f0aec-185a-4160-9c17-6d037b298318/limit/1/offset/0.`
2. Go to `http://demo.dotcms.com/api/content/render/false/query/+contentType:Destination%20+languageId:1%20+deleted:false%20+working:true/orderby/score,modDate%20desc/related/Destination.activities:574f0aec-185a-4160-9c17-6d037b298318/limit/1/offset/1.`
3. Verify the results of both api's After changing the offset result is still the same.

**Expected behavior**
In Content API when we use /related /limit /offset. After changing the offset next page result should appear.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/22738

**Comment by bryanboza** [comment]
Fixed, tested on release-22.09 // Docker // FF
