### ISSUE TITLE
Move Unique per site to a field variable

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22250]
In order to give more control over unique fields, we added a config property called `uniquePerSite` that controls whether fields marked unique are unique globally or per site.

We should have created a `uniquePerSite` field variable that controls, at the field level, whether the unique field is measured on a per site basis or a global basis.  The default for this is `false` which would maintain the behavior of the unique field values in all dotCMS versions except 22.05, where the default was changed by accident.

We should revert the change to the default that was made in issue :
https://github.com/dotCMS/core/issues/21781

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
