### ISSUE TITLE
Replace Alert(...) to an Angular Component/Service to show successfully when the user edits info in My Account

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22277]
**Is your feature request related to a problem? Please describe.**
As a user, when I switch to My Account, passing all validations and saving the form successfully, I get a browser's native `alert (...)` to show that the form was saved successfully.

**Describe the solution you'd like**
Create a shared reusable service to create(or reuse DotGlobalMessageService, DotMessageDisplayService) a toast to inform the user.

**Describe alternatives you've considered**
use something like: https://www.primefaces.org/primeng/toast

**Additional context**
To Reproduce
- Login as an admin
- Go to My Account
- Type the current password and save a new one

![Screen Shot 2022-05-23 at 1.36.27 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/70738748-b962-4789-ad1e-639d507b2aa0)

**Comment by fmontes** [comment]
Dupe https://github.com/dotCMS/core/issues/22276
