### ISSUE TITLE
Reading osgi import packages fails when osgi version specifies a range 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22287]
When an osgi plugin/fragment is uploaded, we attempt to read the packages and automatically add them to our `osgi-extras` file.  The issue is that we are doing a simple split of the string on a comma.  OSGi allows the version of packages to specify a range, and this range is in quotes and has a comma in it.  The import looks like:

```
...
 nguagesmanager.model,com.dotmarketing.util,com.liferay.portal.model,c
 om.liferay.portal.util,io.vavr;version="[0.10,1)",javax.servlet.http;
 version="[3.1,4)",org.apache.velocity,org.apache.velocity.app,org.apa
 che.velocity.context,org.apache.velocity.exception,org.apache.velocit
 y.runtime,org.apache.velocity.runtime.directive,org.apache.velocity.r
 untime.parser.node,org.osgi.framework;version="[1.8,2)"
```

Uploading a plugin that has imports like the above blows osgi up.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF
