### ISSUE TITLE
UI: WhatsChanged checkbox does not look as marked   

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22280]
When you enable the What's Changed checkbox, we are not enabling the check, and it looks as unchecked. 
![image](https://user-images.githubusercontent.com/2641437/169899488-67ca2174-c785-43c3-a8d1-1e58ac08ec6d.png)

**To Reproduce**
- Create//open any page 
- Go to the preview tab 
- Enable the What's changed 

**Expected behavior**
This should looks enabled when you select the option 

**Desktop (please complete the following information):**
Tested on release-22.06 // Docker // FF

**Comment by alfredo-dotcms** [comment]
related to #22673
