### ISSUE TITLE
Fix test Task220330ChangeVanityURLSiteFieldTypeTest.html#runTUTwice

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22282]
~We are unable to upgrade from a previous version to release-22.06 using MSSQL, the upgrade task created in the previous release `Task220330ChangeVanityURLSiteFieldType ` is not running in this database~

This test is continuously failing in MSSQL: 

https://raw.githack.com/dotCMS/test-results/master/projects/core/current/integration/mssql/reports/html/classes/com.dotmarketing.startup.runonce.Task220330ChangeVanityURLSiteFieldTypeTest.html#runTUTwice

Last update by @nollymar

**Comment by nollymar** [comment]
I have updated the card description

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/22302

**Comment by freddyucv** [comment]
**Note to QA:** Test doing a upgrade from 22.03

**Comment by dsilvam** [comment]
Passed Internal QA: Upgraded from 22.03 to 22.06 and Site field has the proper type.
