### ISSUE TITLE
Need to be able to set per-block styling in blog editor 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22293]
Related to #22037

We need to be able to define some specific style per block in this editor.

Right now we are just able to set a global style to the whole field, should be cool to be able to have individual styles

**Comment by john-thomas-dotcms** [comment]
+1 on this.

It seems that for content types which can be added, this can probably be done in the VTL file for the content type.

But for the built-in block types, it would be nice to be able to style each of them differently.  Maybe just have a field variable for each block type, which allows you to specify a class name?
