### ISSUE TITLE
Introduce way to flush memory for macros

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#22297]
**When macros are loaded then difficult to remove them**
One exemplary [issue](https://dotcms.zendesk.com/agent/tickets/107380) clearly describes macros that are loaded and after that difficult to remove.

**The possible solution**
Introduce a way that can reset the macro manager that is loading macros.

**Useful discussion related to macro**
https://groups.google.com/g/dotcms/c/jqyrQMPjO_Y/m/f7PuCxcuBAAJ

**Comment by wezell** [comment]
There are system macros that always should be loaded and available - those are found here:
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/system.properties#L120

So if we flush them, we will need to re-read them when we rebuild the cache.

So let's do this - when building the cache of velocity macros, we need to 
1. read in ones in the system.properties first
2. find (content search) and read any file whose name is `dot_velocity_macros.vtl` and read those in
3. allow any of these to be overridden at the page level


If a change is made to any file name  `dot_velocity_macros.vtl` then we are going to flush the macro cache and rebuild it.

**Comment by fmontes** [comment]
### Accepance criteria
- Macros should be in cache after cache flush
