### ISSUE TITLE
Include Swagger UI in dotCMS backend as a Tool

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#22298]
This change brings a new "Tool" into dotCMS called `API Playground`, which consists in an adapted version of Swagger UI.  This allows users to view and test the REST APIs available in dotCMS

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise/pull/876

**Comment by dsilvam** [comment]
Note to QA:
* Add the "API Playground" portlet to the left menu by going to Settings -> Roles & Tools -> System -> CMS Administrator - Tools
* Go to the new API Playground menu item wherever you placed it and should get a list of the API endpoints
* Hit some GET endpoints and should get answer

**Comment by bryanboza** [comment]
We are unable to execute multiple calls by an error with the request body 

![image](https://user-images.githubusercontent.com/2641437/179797532-381b5dc2-a0e2-4dfb-8544-15f8552fcc30.png)

Error message: 
```
{
  "message": "MessageBodyReader not found for media type=*/*, type=class com.dotcms.workflow.form.WorkflowStepAddForm, genericType=class com.dotcms.workflow.form.WorkflowStepAddForm."
}
```

This is happening in multiple request

**Comment by dsilvam** [comment]
@bryanboza That's our of the scope of this issue. Needs to be worked on separate multiple cards.

**Comment by bryanboza** [comment]
@dsilvam do you think that allow to execute calls from this portlet is out of the scope? Not sure about that, I think this is the main functionality of this portlet, but not sure

**Comment by dsilvam** [comment]
It's a progressive work @bryanboza - to make them all work we need to include annotations in a lot of places. For this first iteration we decided to make at least the workflow different fire methods to work. The description was updated to reflect this.

**Comment by dsilvam** [comment]
@bryanboza I just turned this issue into an epic and created issues for the remaining tasks.

**Comment by dsilvam** [comment]
Rest of annotations will be worked on a separate epic https://github.com/dotCMS/core/issues/22659

**Comment by bryanboza** [comment]
Passed!!
