### ISSUE TITLE
Edit Contetlet: Content Name icon go out of the input when scrolling. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#22300]
**Describe the bug**
Content Name icon go out of the input when scrolling. 

**To Reproduce**
1. Go to Content Types screen
2. Pick Blog, edit the content type. 
3. scroll, see the issue. 

**Expected behavior**
should keep in the input when scrolling.

**Screenshots**
https://images.zenhubusercontent.com/3729629/95172584-7f40-4a3c-bc65-45eb301a5c9c/edit_content_icon.mov

**Comment by oidacra** [comment]
That icon belongs to LastPass. Not to DotCMS
