### ISSUE TITLE
XMLTool not working

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22307]
When trying to use the XMLTool, we are getting an exception:

```
Cause of error: Invocation of method 'find' in  class com.dotcms.rendering.velocity.viewtools.XmlTool threw exception java.lang.NoClassDefFoundError: org/jaxen/JaxenException at .....
```

**Comment by dsilvam** [comment]
Passed QA. Tested using the example from the Doc site https://www.dotcms.com/docs/latest/xmltool. 
<img width="1233" alt="Screen Shot 2022-08-09 at 12 35 49" src="https://user-images.githubusercontent.com/1576794/183721940-585edbe1-497a-4944-81cb-c48a4119e1df.png">
