### ISSUE TITLE
Rest API: Pulling Relationships from child

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22319]
We need to be able to pull relationships from the child (Lucene query) and get the parents, it must accept pagination so it needs to limit, offset and sort.

This method works but just via viewtool https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/content/ContentTool.java#L396-L423

Parameters this endpoint should accept
- identifier of parent
- relationship field variable
- lucene condition to filter children
- limit
- offset
- orderby

**Comment by erickgonzalez** [comment]
This was only backported to 22.03.2 since the customer needed to upgrade successfully.  Enhancements aren't backported to LTS.

**Comment by bryanboza** [comment]
Fixed tested based in the curl test and this is working as expected
