### ISSUE TITLE
Relationships will get cleared if you Save a contentlet before they are loaded

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22323]
**Describe the bug**
When you open a contentlet in the backend the relationships are lazy loaded. If you submit the contentlet prior to this load completing it will save the relationships with an empty list, clearing all existing relationships.

Related ticket: https://dotcms.zendesk.com/agent/tickets/107486
Reproduced on: 22.05

**To Reproduce**
1. Throttle your network speed to slow 3G in Chrome dev tools.
2. Open a contentlet with a relationship.
3. Hit Save immediately, before the relationship loads. 
4. Close and re-open the contentlet. The relationship will now be empty.

**Expected behavior**
The relationships should not be changed if they were not loaded when the Save button was pushed.

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/22467

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF. Unable to reproduce after the last changes.

**Comment by rjvelazco** [comment]
There is a bug on `auth`, after we `drag & drop` a relation, we never save the content.

https://user-images.githubusercontent.com/72418962/183519451-58ac729d-7f0e-4276-bcee-40b004dfd678.mp4

**Comment by rjvelazco** [comment]
PR: #22699

**Comment by rjvelazco** [comment]
**Note for QA:** I couldn't reproduce the `issue` on my `local` using `starter`, so I have to download `auth assets & database` -Thanks @nollymar for helping me with that-. You can find the resources I used [here](https://drive.google.com/drive/folders/1ytTlz4obpOilrsSNv5PRLoCfgRjyeFaK?usp=sharing).

**Comment by fmontes** [comment]
Wait for the auth server update to do this QA>

**Comment by bryanboza** [comment]
Fixed, teste in the authoring server trying to reorder the relationship field and it is working as expected.

**Comment by erickgonzalez** [comment]
Another customer hitting this https://dotcms.zendesk.com/agent/tickets/109320

**Comment by swicken-dotcms** [comment]
Another customer hitting this: https://dotcms.zendesk.com/agent/tickets/109485

**Comment by erickgonzalez** [comment]
this one needs the changes of https://github.com/dotCMS/core/issues/21735 so backporting 2 in 1 commit

**Comment by erickgonzalez** [comment]
Missing change that wasn't related to this https://github.com/dotCMS/core/commit/a65114716bc8d24267fe891a367406b77d140f0e#diff-651d81e1153f4e138156a2558002f2d07d4fb5c27b84fcf6d54bf944f7eb9aa6
