### ISSUE TITLE
Fix Storybook tasks in Nx

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22335]
**Describe the bug**
After the core-web to core merge Storybook tasks for all apps and libs are broken

**To Reproduce**
1. Run `npx nx run appname:storybook`
2. See the terminal

**Expected behavior**
It should run correctly in `dotcms-ui`, `dotcms-block-editor` and `dotcms-webcomponents`

**Comment by oidacra** [comment]
Using https://github.com/dotCMS/core/pull/22400 as base branch

**Comment by oidacra** [comment]
Fixed in branch https://github.com/dotCMS/core/pull/22514
