### ISSUE TITLE
Upgrade Nx, Angular and all the npm packages possibles

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22337]
**Is your feature request related to a problem? Please describe.**
Let's make sure we keep all the packages up-to-date waiting for Angular 14.

**Describe the solution you'd like**
- To update Nx and Angular, we should use Nx migrate: https://nx.dev/cli/migrate
- Make sure you update Storybook to the latest version
- For the rest of the packages, we have to go manual or use `npx npm-check-updates -u` (careful)

**Additional context**
Good luck :)

**Comment by oidacra** [comment]
https://github.com/dotCMS/core/pull/22400
