### ISSUE TITLE
Content Palette not showing all available content types

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22338]
**Describe the bug**
Content Palette should show all the available content types to add to the page you're editing.
But if there are more than 40 content types, some content types aren't being pulled, because we're doing the following call:
```
/api/v1/contenttype?filter=&orderby=modDate&direction=DESC&per_page=40
Request Method: GET
```
We're limiting the content types to 40.

**To Reproduce**
1. Create 40 widgets
2. Go to any page and edit mode.
3. See the content palette is not pulling all the widgets.

**Expected behavior**
Should pull all the content types that one is able to add to the page.

Reproducible in 22.03.1 and demo (22.05)
Customer ticket https://dotcms.zendesk.com/agent/tickets/107482

**Comment by wezell** [comment]
FYI, what we did here is not acceptable - just searching within the initial results without doing another api request.

**Comment by fmontes** [comment]
## The problem
We fetch ONLY 40 content types and sort by mod date, after that we:

1. Remove all the content types that containers in the page wont take
2. Remove all the content types in the property `CONTENT_PALETTE_HIDDEN_CONTENT_TYPES`.

Container takes **ALL the content types** with the `baseType === "WIDGET"` and with


which can lead to leave WIDGETS or even other content types accepted by the page outside the palette.

**Comment by fmontes** [comment]
For the quick fix for the LTS we can change the 40 for like 500 to bring as much as possible of the `baseType === "WIDGET"`

**Comment by jcastro-dotcms** [comment]
The palette is returning duplicate Widget Types:

<img width="255" alt="Screen Shot 2022-07-11 at 11 54 52 AM" src="https://user-images.githubusercontent.com/8779585/178333591-861222ff-be50-4a70-bff2-add279b6de18.png">

Confirmed with @rjvelazco

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF

**Comment by erickgonzalez** [comment]
Only applies to 22.03 LTS

**Comment by erickgonzalez** [comment]
After discussing with Freddy Montes, we applied the fix described here https://github.com/dotCMS/core/issues/22338#issuecomment-1149258801 but limited to 100 content types.
