### ISSUE TITLE
Fix inline editing in blog detail page (update starter)

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22348]
**Describe the bug**
You can't inline edit the title of the blog post in the full starter, it just doesn't save and for the "body" that now is a block editor, we don't support inline editing yet.

**To Reproduce**
1. Start a dotCMS with full starter
2. Go to edit a blog detail page
3. Edit inline the title 
4. See is not saving.

**Expected behavior**
1. For the title, it should save
2. For the body, it should not have inline editing.

**Additional context**
The title is because in the `blog-degail.vtl` we're not passing the correct inode.

**This needs to be fixed in starter:** https://starter.dotcms.com:8443/

**Comment by hmoreras** [comment]
The `blog-degail.vtl` is now updated in the starter

Old version: https://gist.github.com/hmoreras/7cad8985b9121abe538e98467106a52b

Updated version: https://gist.github.com/hmoreras/2451fb40274464828f7d45c31e218567

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF. Tested with the last starter site
