### ISSUE TITLE
Create dotStartPages in startup tasks

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22356]
- title, 
- a binary field for the screencap 
- a url (textarea) - this needs to be mapped into elasticsearch as a keyword
- an sortOrder integer field that will be used to sort the start pages.

**Comment by nollymar** [comment]
PR: #22721

**Comment by nollymar** [comment]
**Internal QA:** Passed. (Tested on docker image `22.09_06a002b3_SNAPSHOT`)

A Favorite Page content type was included

![Screen Shot 2022-09-01 at 5 24 24 PM](https://user-images.githubusercontent.com/8741395/188023207-079d5a01-3394-465f-a6aa-8320fdbb0697.png)

**Comment by bryanboza** [comment]
Fixed, tested on release 22.09 // Docker // FF
