### ISSUE TITLE
Allow users to edit custom content tool

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22353]
We added the ability to create custom content tools - we need to also add the ability to EDIT the custom content tools.  This would allow an admin to rename the tool or add/remove BASE_TYPES and or Content TYPES to it.  Right now, the only option is to delete the tool and recreate it.
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27915
```

**Comment by muhammadfaizandotcms** [comment]
One of our customers is asking about this fix: https://dotcms.zendesk.com/agent/tickets/108605

**Comment by ian-b-cooper** [comment]
Another request from a customer for this enhancement: https://dotcms.zendesk.com/agent/tickets/109356

**Comment by muhammadfaizandotcms** [comment]
Another request from a customer for this enhancement: https://dotcms.zendesk.com/agent/tickets/109471

**Comment by erickgonzalez** [comment]
We're able to edit them via REST API https://github.com/dotCMS/core/issues/27920#issuecomment-2032468585
