### ISSUE TITLE
Date and Date/Time fields can't be blanked

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#22350]
**Describe the bug**
After a date has been saved to a **Date** or a **Date and Time** field in a Content Type, attempting to clear it and save it as blank throws an error ("Unable to convert string to date -0400").

**To Reproduce**
1. Create a Content Type with a non-required Date or a Date and Time field.
2. Create a contentlet of that type.
    * If you set no default value, assign the Date or Date and Time field a value, and save or publish.
3. Erase the value in the Date or Date and Time field and attempt to save or publish.
4. See error.

**Expected behavior**
Blank Date or Date and Time fields should save normally.

**Screenshots**
![date-error](https://user-images.githubusercontent.com/102264829/172177244-2106c8fb-53e2-4e0b-86b4-024d783e3938.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser: Brave
 - Version: Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64)

**Additional context**
A non-required Date or Date and Time field that defaults blank and is never assigned a date in the first place will save correctly.

**Comment by jdcmsd** [comment]
Additional info!

So there are two different values being expressed here. If we assume the date field variable is `test`, then:
1. `document.getElementById("test").value` holds the saved date as `2022-06-15 00:00 -0400`
2. `document.getElementById("testDate").value` is the dijit interface object, which holds the saved date as `6/15/2022`

(The former also corresponds with the formatting used when defining default values in the Content Type settings.)

If you attempt to hand-erase the date, the `testDate.value` becomes set to `''`, but the `test.value` lands at `' -0400'`, which is the value seen in the error above.

Before and after hand-erasing:
![Screen Shot 2022-06-07 at 12 23 00 PM](https://user-images.githubusercontent.com/102264829/172433221-840408e6-50c8-421b-b044-c00601159019.png)

However, if you use a Custom Field to create a "Clear" button that sets both values to `''`, the blank date **will** save correctly! It's probably not a solution we should be recommending to users, but it illustrates the nature of the problem well.

Below is an example I wrote that's on Demo right now, but I guess won't be for long. Here are deep links to the [content type](https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/185a68dc18201b7114a73fbcfacd26f3) and a [contentlet](https://demo.dotcms.com/dotAdmin/#/c/content/83ae91d5-38d9-4c94-88d9-5489b268a784), regardless, for those curious within the next 18 hours or so!

![Screen Shot 2022-06-07 at 12 27 24 PM](https://user-images.githubusercontent.com/102264829/172434181-b1768dd9-7b25-4162-81d1-5356e14d6346.png)

```
#set($content = $dotcontent.find($request.getParameter("inode")))

<script>
    function prevClick(){
        document.getElementById('aaa').value="${date.format("yyyy-MM-dd", $content.modDate)} 00:00 -0400";
        document.getElementById('aaaDate').value="${date.format("M/d/y", $content.modDate)}";
    }
    function currClick(){
        document.getElementById('aaa').value="${date.format("yyyy-MM-dd", $date)} 00:00 -0400";
        document.getElementById('aaaDate').value="${date.format("M/d/y", $date)}";
    }
    function clearClick(){
        document.getElementById('aaa').value="";
        document.getElementById('aaaDate').value="";
    }
</script>

<div>
 <button dojoType="dijit.form.Button" id="previousDateButton" onclick="prevClick">Previous Mod Date</button> 
 <button dojoType="dijit.form.Button" id="currentDateButton" onclick="currClick">Current Date</button>
 <button dojoType="dijit.form.Button" id="clearDateButton" onclick="clearClick">Clear</button> 
</div>
```

**Comment by erickgonzalez** [comment]
Closing in favor of https://github.com/dotCMS/core/issues/22667
