### ISSUE TITLE
Users can create fields with reserved var names

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22372]
**Describe the bug**
User can add `identifier` and `inode` fields content types, with the variable name “identifier” or "inode".  These variable names should be reserved.

**To Reproduce**
1. Go to content types
2. Create or edit a content type
3. Add a text field with the name "identifier"
4. See that user can create it and the var name is "identifier"

**Expected behavior**
Users should not be able to create those named fields.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AndreyDotcms** [comment]
This issue should be fixed here https://github.com/dotCMS/core/issues/26796

**Comment by josemejias11** [comment]
Tested on **master_cf9b773** / // Docker // macOS 13.5.1  // FF v117.0
<img width="1134" alt="Screenshot 2024-01-09 at 4 22 46 PM" src="https://github.com/dotCMS/core/assets/129882031/758cb59a-09d8-44af-a8d0-c96616abde1e">
