### ISSUE TITLE
Upgrade task that makes DB column into timestamp + timezone does not translate the times to UTC

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22383]
**Describe the bug**
We are now storing all dates on contentlets in UTC, where before they were stored in their locale time. 

The upgrade task we created does not translate existing dates into their offset UTC time, so when existing contentlets date fields are read, they are translated incorrectly. 

For example: If a contentlet had a date field that read 17:00CST and we upgraded the database, the time in the contentlet screen on the upgraded version would read 12:00.

**To Reproduce**
1. Start a demo instance of dotCMS prior to the date change (21.09)
2. Upgrade past 21.09

Compare a date field before and after, the date will be different in the upgraded environment unless the environment was set to UTC.

**Expected behavior**
We need to check the users timezone in the upgrade task to get the offset and when updating the date fields in contentlets we need to translate that field. 

In my previous example, 17:00CST would need to be stored as 22:00UTC

**Comment by wezell** [comment]
dupe: #22381
