### ISSUE TITLE
Change logo in backoffice UI not working for all logo sizes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22410]
**Describe the bug**
If users add a logo that is not 16px height it just show bad, we need to make sure all the logos can work as good as possible.

**To Reproduce**
1. Go to Settings > Configuration
2. Upload a horizontal or vertical logo
3. See how bad it looks

Use this as a example
![PragmaticPlay-logo-promotipn](https://user-images.githubusercontent.com/751424/173861890-dadb6fb1-5e2e-4333-86a3-7676be33c822.png)

**Expected behavior**
It should take all the height possible and only have to margin to not get to the edges

**Comment by erickgonzalez** [comment]
Doesn't apply to 5.3.8 LTS

**Comment by rjvelazco** [comment]
It looks good, we don't show the logo when the menu is closed, as we do with the dotCMS logo, but I think that's the expected behavior.

https://user-images.githubusercontent.com/72418962/174387371-37b11dab-10b4-4242-933b-4e9ff0d05f5c.mov

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Docker // FF. New card reported here #22461
