### ISSUE TITLE
Do not cache bad shorty DB results

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22430]
When loading a ShortyId from the database, if there is a database error like the database is too loaded, we were catching that error and returning NoShorty.  The problem with this pattern is that these bad shorties end up in our cache which means that they will always return a 404 until the shorty region is flushed.  Instead of catching the error and returning a NoShorty, we need to throw an exception and do not add the bad shorty to the cache.

**Comment by oidacra** [comment]
Internal QA: QA feedback will be provided by support. Working in the Production site of the customer. @swicken-dotcms
