### ISSUE TITLE
Push Publishing to S3 - Region Problems

### ISSUE THREAD

**Issue by cobbg** [dotCMS/core#22449]
**Describe the bug**
Push Publishing to S3 does not work in some regions. This is because some AWS regions (presumably newer ones) do not support Signature Version 2, which is a protocol for authenticating inbound API requests to AWS services.

Additionally, if the target S3 bucket resides in a region that only supports SV4, the region-specific endpoint must be used opposed to the generic `s3.amazonaws.com`.

**To Reproduce**
1. Create an S3 bucket in a region such as Frankfurt (eu-central-1) that only supports SV4.
2. Attempt to PP some content to this bucket.
3. An error will be returned from AWS. Sometimes in the form of a generic HTTP 400 error without a comprehensive description; other times, you may receive a different error depending on the type of request and region.

**Expected behavior**
Push Publishing to S3 should work for all major regions. (Possibly with the exception of GovCloud and AWS "local zone" regions.)

**Additional context**
Official AWS documentation on the subject can be found [here](https://docs.aws.amazon.com/general/latest/gr/s3.html).

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22449?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by dsilvam** [comment]
PR core: https://github.com/dotCMS/core/pull/23491
PR ee: https://github.com/dotCMS/enterprise/pull/893

**Comment by dsilvam** [comment]
Passed Internal QA: Able to push to buckets in eu-central-1 region.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF. Tested using the. region provided in the previous comment `eu-central-1 region`
