### ISSUE TITLE
Log Fail to Create on dotCMS 22.03.1. Invalid File Path

### ISSUE THREAD

**Issue by Invisibilities** [dotCMS/core#22448]
**Describe the bug**
Fail to create log file on dotCMS 22.03.1 and JAVA 11

**To Reproduce**
1. Extract the dotcms_22.03.1.zip, downloaded from official website
2. Go to META-INF/context.xml add MSSQL configuration
3. Elasticsearch startup
4. Swap the log4j.xml at WEB-INF/log4j
5. startup.bat on dotserver/tomcat-9.0.41/bin (Not sure why dotcms/bin/startup.bat is not working, it shows "Could not create the Java virtual machine" and the command prompt closes in a very fast speed. I capture the error with video and slow speed to read it)

Screenshot:
![dotcms](https://user-images.githubusercontent.com/28775752/174266023-8ce125cb-9a36-4eb8-a45d-b1e1efa86001.png)
![dotcms1](https://user-images.githubusercontent.com/28775752/174266509-e9cdb927-bd3e-4b06-a8ba-11c097f531e7.png)
![dotcms2](https://user-images.githubusercontent.com/28775752/174266930-97db8541-970d-4d80-be00-c08f94c27293.png)

**Comment by swicken-dotcms** [comment]
We are no longer supporting Windows binary installs from the command line. Binary install support in general is being deprecated and docker installs are suggested.
