### ISSUE TITLE
DotCms CDN how to integrate

### ISSUE THREAD

**Issue by fchenxi** [dotCMS/core#22458]
**Describe the bug**
See from dotcms docuemnt https://www.dotcms.com/docs/latest/CDN,  dotcms support cdn integrate, but how to config cdn secret key or username/password?
Please help describe detail how to do it, thanks a lot.

**Desktop (please complete the following information):**
 - OS: [e.g. IOS]
 - Browser [chrome, safari]
 - Version [dotcms 5.3.8]

**Comment by wezell** [comment]
As that document says, it is a feature available to dotCMS Cloud customers.  If you are a cloud or dotCMS Enterprise customer, please reach out to your customer success manager for more information.
