### ISSUE TITLE
Return experiment results (partial/total)

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#22457]
Create a end point to get the result from a experiment

URL:

`GET  /experiment/{id}/result`

Response body:

```
{
     total_sessions: xx,
     total_events: xx,
     goals: {
          primary: {
               metric: "REACH_PAGE",
               variants: {
                   original: {
                        multi_by_session: {
                             count: xx,
                            percentage: xx
                         },
                        unique_by_session: {
                            count: xx,
                            percentage: xx
                        },
                    },
                   variant_a: {
                        multi_by_session: {
                             count: xx,
                            percentage: xx
                         },
                        unique_by_session: {
                            count: xx,
                            percentage: xx
                        },
                    }
                }
            }
      }
}
```

### Acceptance criteria
- Create the End Point
-Create a Util class to connect and sent a query to cubeJs
- Create the API to be use by the End point to get the Experiment Results, this API is going to use the Util class to hit a query to cubeJs.
- Create all the class that we need to get the Result of a PAGE_REACH Goal.

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22457?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/23895

**Comment by freddyucv** [comment]
Second PR: https://github.com/dotCMS/core/pull/23973

**Comment by dsilvam** [comment]
Third PR: https://github.com/dotCMS/core/pull/24034

**Comment by victoralfaro-dotcms** [comment]
Page Reach Experiment
Page B
![image](https://user-images.githubusercontent.com/64026161/217396631-713365f6-d8d3-4465-87c8-a7122d7f37ab.png)
Experiment:
![image](https://user-images.githubusercontent.com/64026161/217396665-5899ed38-fb9c-4839-810d-16ae1c32d074.png)
Pagina B Variant
![image](https://user-images.githubusercontent.com/64026161/217396692-9325b1c2-a795-47e9-b501-ca49e0001349.png)

**Comment by bryanboza** [comment]
Fixed, this is just usable via API, We don't have a way to see that response from UI. 

Tested using the API // Release_23.03
