### ISSUE TITLE
Scale was removed from image filters in favour of resize as it is more efficient, but we should map Scale to Resize

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22463]
**Describe the bug**
When fixing this issue: https://github.com/dotCMS/core/issues/20446 it seems we removed the ability to call 'Scale' on filters 

Reproduced on: 21.06.8, 22.06

Related Ticket: https://dotcms.zendesk.com/agent/tickets/107661

**To Reproduce**
1. Try to scale any image: https://www.dotcms.com/contentAsset/image/6a50a56c-c281-4282-b9ba-fa9f07fea4da/fileAsset/scale_w/800/scale_h/500
2. The scale filters will not work

Here is the resize:  https://www.dotcms.com/contentAsset/image/6a50a56c-c281-4282-b9ba-fa9f07fea4da/fileAsset/resize_w/800/resize_h/500

**Expected behavior**
Scale is documented and functions the same way as resize, we should just map scale to resize so to keep backwards compatibility.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF
