### ISSUE TITLE
promote contentlet version

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#22477]
To promote a variant we need to create a copy of all Contentlet with a version in the Variant in the DEFAULT variant.

Also we need to make these new copies being the ones for the DEFAULT variant LIVE Version for each Contentlet.

Also and need a endpoint to promote a Variant.

URL: `/v1/variants/<variant_id>/_promote`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24450

**Comment by dsilvam** [comment]
Needs work: If you try it on a already promoted variant, it gives 500.

**Comment by wezell** [comment]
idempotent!

**Comment by victoralfaro-dotcms** [comment]
Experiment set:
![image](https://user-images.githubusercontent.com/64026161/233749548-f71e2e4d-f534-40ce-b3b0-827912e32f15.png)
Experiments reports:
![image](https://user-images.githubusercontent.com/64026161/233749587-9c3b9153-8c02-48dd-9571-9d501d307ff2.png)
Promote variant:
![image](https://user-images.githubusercontent.com/64026161/233749623-ea2f6b90-bdaa-446c-b104-47c4fabf6c3a.png)
Idempotent call to promote endpoint:
```
curl -i --location --request PUT 'http://localhost:8080/api/v1/variants/dotexperiment-2fbb502494-variant-1/_promote' \           ✔  17:19:09 
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--header 'Cookie: access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3MTgxNjdjOC1jN2ZmLTQyYzAtOWY1MC1mMjdlMjI4NWU2ZTMiLCJ4bW9kIjoxNjgyMTE4NzA2OTE0LCJzdWIiOiJkb3RjbXMub3JnLjEiLCJpYXQiOjE2ODIxMTg3MDYsImlzcyI6IjU4ZmRlMDY0ZmQiLCJleHAiOjE2ODIyMDUxMDZ9.1jfef6dhgd7N4KmE2tpcs0IHywym4UmaecRebBJOV_U'
HTTP/1.1 200
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
x-dot-server: fischer.lan|3394322e2b
Set-Cookie: JSESSIONID=C55AF081856B11DF59CD6E55EC162AD5; Path=/; Secure; HttpOnly
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,HEAD,OPTIONS,PATCH
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: *
Access-Control-Expose-Headers: *
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Content-Length: 0
Date: Fri, 21 Apr 2023 23:46:05 GMT
```

**Comment by victoralfaro-dotcms** [comment]
Needs work: regardless of the returned `200` http status, the variant's contents are not being displayed after the being promoted.

**Comment by bryanboza** [comment]
After test this stuff seems we need some work here: 

- We must to add postman tests for this endpoint
- We need to add a message the selected variant has been promoted 
- We need be able to select just one variant in the radio buttons ""
![image](https://github.com/dotCMS/core/assets/2641437/341d7354-c30e-4b1c-a0bf-c4d7a25efb0c)

- Once the variant is promoted, we need to disable the promote button 
- At chart level, we need to indicate when a variant is promoted, also in the table

**Comment by oidacra** [comment]
Points 2 and 3 are fixed in this PR in master: https://github.com/dotCMS/core/pull/24811
@dsilvam

**Comment by dsilvam** [comment]
Needs work: we should include the "promoted" message in the table as well
