### ISSUE TITLE
NormalizationFilter does not set javax.servlet.forward.request_uri

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22478]
In fixing the matrixparameters issue here #22390 we added a requestwrapper.  This had the side effect of preventing the requestDispatcher from correctly setting the parameter:
`request.getAttribute("javax.servlet.forward.request_uri")`.  

This had the side effect of, in Velocity, if you called:
`$!{request.getAttribute("javax.servlet.forward.request_uri")}` on a page you would get `/servlets/VelocityServlet` rather than the Original path sent by the browser.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2641437/175607477-540227c2-019c-4589-8937-f6c640ad11d4.png">
