### ISSUE TITLE
Transform WYSIWYG field to block editor fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
1. Is content type level
2. We need to update the content in all the contentlets in that content types
3. We might need to wipe the history (so we need a warning)
4. Microservice or client?
5. Enterprise functionality
6. There is no "reverse", once is done is done.
7. No custom blocks supports

**Acceptance criteria**
- Allow users to change the field type
- Support basic blocks: p, h1-h6, marks like bold, link, italic etc.
- Partial support to images, images that are inline inside a `<p>` which is the natural code of the WYSIWYG

**Comment by fmontes** [comment]
### From the WYSIWYG field properties
1. Click in a button to transform
2. It will change the DB but not update the contentlets
3. The contentlets will be updated when open and save (which the block editor will take the string of HTML and turn it to JSON)
4. `toHTML()` method will check the format of the text (JSON or HTML), if JSON all remains the same, if HTML it will return the HTML for the block editor to take over and turn it into JSON.

**Comment by jcastro-dotcms** [comment]
Based on my initial investigation, it seems like it's possible to transform a `WYSIWYG` field into a `Story Block` field by changing a few attributes in the JSON data received by the REST Endpoint used to update a field:
```
{{serverURL}}/api/v3/contenttype/{CONTENT_TYPE_ID}/fields/move
```
In the JSON payload, if you update the following attributes to the specified values:
* `"clazz": "com.dotcms.contenttype.model.field.ImmutableStoryBlockField"`
* `"fieldType": "Story-Block"`
* `"fieldTypeLabel": "Block Editor (Beta)"`

The field will be transformed correctly. The FE Team will be double-checking on this.

**Comment by wezell** [comment]
**To test:**
StoryBlockMap.toHTML()
e.g.

in velocity `$blogContent.bodyField.toHTML() `

**Responses**
API Responses
GraphQL

**Comment by fmontes** [comment]
Needs to setup a call.

**Comment by rjvelazco** [comment]
The `api` is not sending the `contentlet` data.

**To Reproduce**

1. Create a `contentlet` of a `contenttype` with a `WYSIWYG` field.
2. Add content to the new `contentlet`.
3. Open the `contentlet` > `history` > `click` on `json`
<img width="1546" alt="JSON" src="https://user-images.githubusercontent.com/72418962/188022628-133bfd74-1978-4191-8c74-763ceb29fb06.png">

4. You should see a `json` with the `contentlet` data:
<img width="1792" alt="Screen Shot 2022-09-01 at 6 22 56 PM" src="https://user-images.githubusercontent.com/72418962/188023222-b15d5d71-0b8b-4bcc-9d3e-3da87669539f.png">

5. Now, go to the `contenttype` and `convert` the field into a `Block Editor`.
<img width="728" alt="Screen Shot 2022-09-01 at 6 21 11 PM" src="https://user-images.githubusercontent.com/72418962/188022849-d684a252-7686-4422-94df-66bcdffda1f7.png">

6. Go back to the `contentlet` > `history` > `click` on `json`.
7. See the error, the `contentlet` data is now `empty`:
<img width="1792" alt="Screen Shot 2022-09-01 at 6 24 40 PM" src="https://user-images.githubusercontent.com/72418962/188023190-75274b51-be81-4010-a327-1bc8ea3a17ab.png">

If you think, this is not an `issue/bug` let me know.

**NOTE:** If we `flush` all cache, the reference of that `contenttype` get lost.
**NOTE 2:** Once we `save & publish` we get the data back:
<img width="1792" alt="Screen Shot 2022-09-01 at 6 26 31 PM" src="https://user-images.githubusercontent.com/72418962/188023348-2c359325-f897-4f09-8a75-e473522c5202.png">

**Comment by bryanboza** [comment]
We have problems here: 

- If you have a WYSIWYG. field with a validation regex, and you migrate to the new Blog Editor field, and after this you try to add // modify some piece of content, we are getting and error about the field format, and we are unable to complete the action 


![Image](https://user-images.githubusercontent.com/2641437/193914799-15aaa45b-9f70-43c1-92a6-24e5b403cf67.png)

**Comment by fmontes** [comment]
As per @wezell this is not an issue.

**Comment by bryanboza** [comment]
Ok, after the last review, we will not fix this problem. 

Marked as know issue...
