### ISSUE TITLE
Support inline editing for block editor field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22487]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hmoreras** [comment]
In order to support inline editing, the following attributes are needed in a html element:  
-`data-language`
- ` data-inode`
- `data-field-name`
- `data-content-type`
- data-content

This is an example in in a VTL file. 

`        <div
            class="section-blog-post-content"
            #if ($EDIT_MODE)
                data-language="${CONTENT_LANGUAGE}"
                data-inode="$URLMapContent.inode"
                data-field-name="blogContent" 
                data-content-type="Blog"
                data-content="$esc.html($!{URLMapContent.get("blogContent").getContent()})"
            #end
        >

            $!{URLMapContent.get("blogContent").toHtml('/application/vtl/blog/blocks/')}
       
        </div>`

**Comment by fmontes** [comment]
@hmoreras Please login to starter and update accordingly

https://starter.dotcms.com:8443/

**Comment by hmoreras** [comment]
starter update done.

**Comment by rjvelazco** [comment]
When trying to update the block editor value using the inline editing, the `update` never ends and throws an error in the console.

**To reproduce**
1. Go to a blog.
2. Enable editing.
3. Click on the `block editor` field.
4. Do some changes.
5. Hit the `update` button.
6. See the error.

**Additional Information**
It seems that the error is here:

https://github.com/dotCMS/core/blob/04c9dcbfb0369d6521f7ac3c03bb1e0bf9295868/core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-block-editor-sidebar/dot-block-editor-sidebar.component.ts#L62-L89

**Video**

https://user-images.githubusercontent.com/72418962/191851364-61baf9c9-b67c-484f-a680-a0898457f811.mov

**Comment by hmoreras** [comment]
Support inline editing in the nextjs starter, https://github.com/dotCMS/dotcms-nextjs-starter/pull/139

**Comment by hmoreras** [comment]
Scenario when save content fails: 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/31667212/192380605-7c8acd76-e796-4261-95d4-541320d35d2c.png">
