### ISSUE TITLE
Tail Log Popup issues

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#22496]
- [ ] ~The popup stops tailing log after leaving it open for a while. I noticed it after 3 ~ 4 hours.~. _This issue will be fixed on #22669_ 
- [x] Whitespaces are printed sometimes at the beginning of the lines: 

![Screen Shot 2022-06-29 at 4.03.46 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/d983bc3a-e792-4647-9f5e-e9347ffe297b)

**Comment by alfredo-dotcms** [comment]
I'm not able to reproduce that the log stops logging
https://monosnap.com/file/ie0pMxfpVBFkKk4qsF3rh9H0FAtUBQ

I tested it during 15 hours, without letting the computer be on Sleep mode

**Comment by nollymar** [comment]
The popup freeze will be solved for the next release https://github.com/dotCMS/core/issues/22669

**Comment by bryanboza** [comment]
Fixed, the pending things was moved to a new card #22669
