### ISSUE TITLE
Normalization filter is too aggressive

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22498]
Normalization filter is also disallowing slashes and equals signs, which is leading to some issues with URIs

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22498?planning-poker) with Zenhub @victoralfaro-dotcms @freddyucv
