### ISSUE TITLE
Drag-N-Drop Navigation reorder not affecting changes to nav menu

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#22501]
Reproduced on demo.dotcms.com running 22.06 and another server running 22.05 using Chrome browser

To reproduce:

1. Login to demo.dotcms.com and edit the homepage

<img width="1183" alt="2022-06-30_13-29-57" src="https://user-images.githubusercontent.com/1569167/176740743-9a276c3a-97c3-4666-b9ff-165e36c8c939.png">

2. In edit mode, cock on the re-order icon for the main nav

<img width="456" alt="Screen Shot 2022-06-30 at 1 26 14 PM" src="https://user-images.githubusercontent.com/1569167/176740455-1f893285-07ec-4e34-9ffb-ef7193b03310.png">

3. Drag-n-drop a navigation item to re-order the nav

4. Error is that no re-order takes place - nav menu is not affected

Expected behavior is that the navigation should be re-ordered matching what was re-ordered by the drag-n-drop.

**Comment by rjvelazco** [comment]
There is a bug. If we tried to re-order `sub-menu-items`, no re-order takes place.

**To Reproduce**
1. Go to Any page.
2. In edit mode, go to re-order menu items.
3. Change the order of a `sub-menu`.
<img width="504" alt="Screen Shot 2022-07-12 at 5 05 29 PM" src="https://user-images.githubusercontent.com/72418962/178595372-bd6e2887-0f08-4eb3-9431-e553465ed0b4.png">
4. See the error, the sub-menu hasn't changed.

**Video**
https://user-images.githubusercontent.com/72418962/178594068-eea1df15-11d0-49a3-bd7f-8a111bb092bc.mov

Tested on Docker: `22.07_43e606c8_SNAPSHOT`

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF. Now we are able to reorder this menu without problems
