### ISSUE TITLE
Permissions migration from DWR to REST endpoints

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22524]
**Is your feature request related to a problem? Please describe.**
As a stakeholder I want to modernize the permissions UI, the first step is to move the architecture to REST endpoints.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jdotcms** [comment]
there are the endpoint to create the READ
This give you the current permission for an asset per user, (if it has READ, EDIT, etc)
http://localhost:8080/api/v1/permissions/_byasset?assetId=97484802ec1482d63635ef5fe15767da

This is the dropdown in the left side with the permission tree
http://localhost:8080/api/v1/roles/_tree

This give you the dropdown in the right side with the users
http://localhost:8080/api/v1/users/filter/

**Comment by fmontes** [comment]
Close, this is being worked in Scout.
