### ISSUE TITLE
Consolidate LoginFactory and LoginAction

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#2252]
We need to remove the LoginAction (or leave as a stub) and consolidate on the LoginFactory.  We currently use the LoginAction for portal logins and the LoginFactory for front end and remember me logins.  Whichever way we choose, we need to be sure that we log - in the security log - failed logins both by username and username+password.  We also should log any information we can get from the users browser like the other request headers etc.

**Comment by wezell** [comment]
1. Removed all the legacy LoginFactory stuff
2. removed liferay login stuff
3. Unified everything to the LoginServiceAPI
4. Added a LoginEvent object that can be deployed via OSGI and can listen to logins
5. JWT tokens are now assigned even for session based logins (helping us go stateless)
6. all logins in the system now use 1 method, front end and back end

### Things to test
- LDAP login
- LDAP front end login
- CAS login
- SAML login

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/508

**Comment by wezell** [comment]
Closing for now
