### ISSUE TITLE
Relationships are not respecting changes to requiredness

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22532]
**Describe the bug**
When you change the existing required state of a relationship, the requiredness does not change functionally. It correctly displays the checkbox based on your selection, but when actually managing relationships it does not respect the state of the checkbox.

Reproduced on: 22.03/22.06

**To Reproduce**
1. Create a relationship between two content types, set it to required
2. Attempt to create a contentlet without specifying a related content
3. Save, you will correctly get an error stating the relationship is required
4. Change the relationship to Not Required (unchecked)
5. Reopen the relationship, the required checkbox will remain unchecked
6. Attempt to create a contentlet without specifying a related content
7. Save, you will no incorrectly still receive the error stating a relationship is required

**Acceptance Criteria**
You should be able to change the requiredness of a relationship

**Comment by erickgonzalez** [comment]
Another customer hitting this: https://dotcms.zendesk.com/agent/tickets/108057

**Comment by alfredo-dotcms** [comment]
looking at this seems like the verification of requiredness happens in the BE and for some reason the changes in the CT model is not updated

![image](https://user-images.githubusercontent.com/37185433/184453149-8592722f-0df7-4600-87bc-73ca9efdfd30.png)

**Comment by jcastro-dotcms** [comment]
## IQA Status: Unable to Reproduce
I confirmed with @bryanboza that this issue is not reproducible with the provided steps to reproduce in the latest stable dotCMS 22.10 Docker image. Creating a required `Relationships` field in a Content Type and then removing such a status is not causing the required message to keep showing up.

**Comment by fmontes** [comment]
Looks like this is for a specific version, we might need to patch it up.

**Comment by bryanboza** [comment]
Tested on release- 22.10 and I'm unable to reproduce

**Comment by erickgonzalez** [comment]
Still happens on 22.03.4 LTS need to debug to check what is going on

**Comment by erickgonzalez** [comment]
Not reproducible in 23.01 LTS

**Comment by dsolistorres** [comment]
PR for 22.03 LTS:
https://github.com/dotCMS/core-web/pull/2015
