### ISSUE TITLE
CLI: Tokens must not be saved in plain text

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#22545]
We need to be able to log in and save the currently selected user and the respective returned token for the given selected dotCMS instance.
using the KeyTar library

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/23949

**Comment by fabrizzio-dotCMS** [comment]
Note for QA: 
in the user directory, there should be a hidden directory named .dotcms
inside that directory, there should be a file named dot-service.yml
This is where the user profile and dot-cms instances are saved/configured and this is where the token used to be saved
So.. just make sure it does not appear here.
In case the OS does not support password storage natively using a Key-Ring or something 
then the access token gets saved as plain text in this file. But I don't really know how to simulate such scenario

**Comment by nollymar** [comment]
**Internal QA:** Passed
