### ISSUE TITLE
404 redirect not working

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22559]
We rely on the custom-error-page.jsp to use our custom vanity urls as redirects.  This is somehow broken in 22.07 and master.

To see:  https://prod.dotcms.com/this-does-not-exist

Should return: https://prod.dotcms.com/404

**Comment by dsilvam** [comment]
Passed Internal QA and QA: This was broken on auth and prod and after updating to the 22.07 with the fix this is working now.
