### ISSUE TITLE
We are unable to edit users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22554]
In the release branch, we are unable to edit users, If you go to Settings --> Users and here you select any user we are not loading the user details, then you are unable to edit.
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/2641437/178350839-cde8cef3-182a-4a0c-a94d-be1b1f8d78c3.png">

Here the error in the JS console: 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/2641437/178351929-3b2a84fe-2cf6-45f1-82a4-4723ee8851cb.png">

Here the log: https://gist.github.com/bryanboza/aad82b334b80bc1be90bd29443a00b8f

**To Reproduce**
- Login as an admin
- Go to Settings--> Users 
- Select any user 

**Expected behavior**
When you select some of the users we are unable to load the user details 

**Desktop (please complete the following information):**
Tested on release-22.07 // Docker // FF

**Comment by oidacra** [comment]
It's working now. `22.07_2af7a97c_SNAPSHOT`

![Screen Shot 2022-07-25 at 11 54 31 AM](https://user-images.githubusercontent.com/1909643/180832942-818dd6a8-fc90-4255-9170-b46563f2d94b.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF
