### ISSUE TITLE
Improvements for ENTER key event

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#22566]
The following improvement suggestions came after this change https://github.com/dotCMS/core/issues/19158

- Create Templates (Next Button does not react to ENTER):

![178408093-ec79d543-61b8-4cd4-ae18-ceb262f00f28](https://user-images.githubusercontent.com/8741395/178769315-06e4a94d-d6de-4874-8e26-b056fa1d12be.png)

- Apps / Import (The main dialog behaves correctly but once a file has been chosen and an invalid password is submitted) You'll see an invalid request dialog. Which does not react to ENTER even after having set the focus on it. The only way to dismiss the dialog is by clicking on ACCEPT.

![178397141-5ccc94a9-49ba-4ab7-ad67-b6d43a393659](https://user-images.githubusercontent.com/8741395/178769398-c32e554b-3f57-4df0-8d76-5ab25298dc21.png)

- My Account Save confirmation dialog does not react to ENTER

![178523236-db8bdc29-26f5-4178-881f-f14bfbeff36e](https://user-images.githubusercontent.com/8741395/178769561-ac23580c-77cd-4b0b-ad8a-78358ad6a01f.png)

- Push Publish (The dialog does not gain focus immediately, you need to click on anywhere on the screen first, or use the tab button to navigate all the screen until the focus lands on the dialog)
- Content-Type (Behaves just fine). This is a perfect example of what most dialogs should behave like. Gain the focus and set it on the first active component or action,

In general, the dialog seems to execute a default action associated with the Key ENTER
But in general terms, the dialogs should gain focus by default and in most cases, they don't.

**Comment by nollymar** [comment]
PR: #22821

**Comment by nollymar** [comment]
**Internal QA:** Passed.

A few comments: 
- Create template: The enter key event works when you select the default option (Template Designer), but if for some reason you change it to Template Advanced, it won't work. I think it is ok because there is no way to change the default option using just the keyboard.
- Push Publish: The change was made to this popup: 
<img width="424" alt="Screen Shot 2022-08-30 at 5 42 44 PM" src="https://user-images.githubusercontent.com/8741395/187556818-f53b41a7-675f-43db-985a-38618e2a9b86.png">

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.09_a506dc69_SNAPSHOT // Docker // FF
