### ISSUE TITLE
Placeholder remains when D&D an image in the block editor. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#22580]
**Describe the bug**
When drop an image the placeholder remains randomly. 

![image.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/c3f6ef1e-f8c8-4a5d-8205-a8c40f3e903d)

**To Reproduce**
1. Drag and drop a few images  in the block editor.

**Comment by fmontes** [comment]
Close in favor: https://github.com/dotCMS/core/issues/22859
