### ISSUE TITLE
Import/Export Content Tool generating diff key/value field 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22582]
**Describe the bug**
When using the import/export content tool, that lives in Content Search, if the content type has a key/value field, it's generated diff when exported than importing. We should be consistent and generate the same.

Export:
`{Current Rating, Amp=350A, Voltage, DC=1000, Interrupting Rating DC=50000, Characteristic=aR}`
Import:
"{'Current Rating Amp':'350A', 'Voltage DC':'1000', 'Interrupting Rating DC':'50000', 'Characteristic':'aR'}"

**To Reproduce**
1. Create a content type with 2 fields (Text and key/value).
2. Create a couple of content of this content type.
3. Export the content (click over the + button, to see the option).
4. Open the generated file.
5. Go to the import content (click over the + button, to see the option).
6. Select the created content type
7. Click over Download Sample CSV
8. Open the sample CSV
9. Check that the key/value field on both CSV are diff

**Expected behavior**
We should be consistent and export the same way that the import is expected.

Reproducible in 22.03 LTS and demo (22.06).

**Comment by Ehryk** [comment]
Any updates on this? Why was the priority label removed?

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/23446

**Comment by erickgonzalez** [comment]
The customer confirmed that the fix solved the issue.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.01_ca54c27a_SNAPSHOT** // Docker // macOS 13.0 // FF v106.0.3

Fields are still differ from the expected file and the exported one.

Reference:
![Screenshot 2022-12-13 at 1 26 32 PM](https://user-images.githubusercontent.com/110418590/207426917-90de9108-8644-4350-8cca-276f83b380f7.png)

**Comment by erickgonzalez** [comment]
In the end, it isn't necessary to be the same, but the key/value was printed without quotes. Maybe worth testing if one of the values has special char such as a comma.

**Comment by josemejias07** [comment]
**Approved with Note** - Tested on 23.01_77ad4776_SNAPSHOT // Docker // macOS 13.0 // FF v108.0

According to DEV this was not supposed to be exactly the same, so the ticket was closed a second time.
