### ISSUE TITLE
Login form not show

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22598]
**Describe the bug**
When you try to login  to dotCMS the frontend not find the propper route after the update to Ng 14.

**To Reproduce**
1. Go to login form
2. See error
![Screen Shot 2022-07-20 at 10.15.12 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/aecdf2b1-8e4d-4fff-a396-b14fa24599da)

**Expected behavior**
Show the login form.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by victoralfaro-dotcms** [comment]
Login form showed.
![image](https://user-images.githubusercontent.com/64026161/180884294-9a869be6-2660-477f-8ded-e89f032329ca.png)
Was able to sign in.
![image](https://user-images.githubusercontent.com/64026161/180884437-faee4ef6-bbc2-4cd6-aa00-045df3b76c0b.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 and now I'm unable to reproduce.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.09 // Docker // FF
