### ISSUE TITLE
Fix route redirect after update to Ng 14

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22608]
**Describe the bug**
Error in redirect with the update of angular 14.

**Steps to test**
Case 1:
- Go to http://localhost:8080/dotAdmin, the app needs to redirect to http://localhost:8080/dotAdmin/#/public/login

Case 2:
1. Go to the site Browser
2. Double click a page to edit, the app needs to redirect to edit the page correctly

Case 3:
1. Go to Content-Type,
2. Click the icon of + (add new content type). The app needs to show the dialog correctly.

Case 4:
1. Go to Content-Type,
2. Click one content type to edit. The app needs to show the dialog.

***The error showed in console (Path not matched)***
![image](https://user-images.githubusercontent.com/1909643/184177135-30849adc-5490-42b9-851d-6e1ce0a2eb94.png)

**Comment by oidacra** [comment]
https://github.com/dotCMS/core/pull/22609
and
https://github.com/dotCMS/core/pull/22599

**Comment by victoralfaro-dotcms** [comment]
/dotAdmin redirected:
![image](https://user-images.githubusercontent.com/64026161/186515419-2efeeb12-ee3f-4318-be44-ef905aadebe8.png)

Openning page:
![image](https://user-images.githubusercontent.com/64026161/186518626-d3c3b73b-04ed-434e-b2c8-78414fdbcfeb.png)
![image](https://user-images.githubusercontent.com/64026161/186518660-d2b0271b-e674-4c8e-a9bd-4cc6bff1b3d0.png)

Adding content-type:
![image](https://user-images.githubusercontent.com/64026161/186518830-b1c9bbb2-4b5c-4e27-833c-558cc23742af.png)
![image](https://user-images.githubusercontent.com/64026161/186518866-18fca30f-d280-46e4-a698-988dcbdb38b4.png)

Editing content-type:
![image](https://user-images.githubusercontent.com/64026161/186519072-d7f314a3-e9ce-4eb3-926c-d7986d36fba3.png)

**Comment by josemejias07** [comment]
Approved QA - Tested on 22.09_0cf62c23_SNAPSHOT // Docker // FF
