### ISSUE TITLE
Token with spaces can not be translate by using language variables

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#22607]
Currently things such as the menu can be translate by using language variables, however the Menu for instance uses the Name of the tab, "Dev Tools" for example and the language variables do not allow spaces between the words.

The solution would be to identified the Menu token with a space, if exists, will replace the spaces by ., use everything lowercase and look for the token, if has a translation used it, otherwise use the default way.

**Comment by nollymar** [comment]
PR: #22610

**Comment by fabrizzio-dotCMS** [comment]
This is a very specific case. 
Apparently, the customer was trying to translate the Layout Menu "Dev Tools" to a corresponding key that has to match the String "Dev Tools"  but the UI does not allow creating such a key. 
Therefore this fix first attempts to find a matching string like "Dev Tools" if not found a fallback is applied trying to find something like dev.tools for the given language. 

This case works no doubt about it.

You can visit Content Model / Languages and create a new default Language Variable like dev.tools in on the desired target language. And it'll get replaced in the Layouts menu. 

But it is confusing that you can also have language variables created in content search named exactly the same and they won't get picked up by the dotCMS UI

also, you can create Language Variables from Content search and have them have blank spaces in between. 

I am passing this case but. It is confusing how  language variables can be created from within two different contexts and be disconnected

**Comment by bryanboza** [comment]
Fixed, tested on release-22.09 // Docker // FF
