### ISSUE TITLE
missing locales for velocity

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#22603]
**Describe the bug**
`$data.format()` does not return localized date formats in the latest dotcms versions. 

In 5.3, the following returns the proper, localized, month name `julliet 2022`: 
```
$date.format( "MMMM yyyy", $date.getDate(), $date.getLocale().forLanguageTag("fr-CA") )
```
In newer releases including 21.06 and 22.03, this returns `Jul 2022` - the same result as when specifying an invalid locale.

Additionally, in 5.3, 
`$date.getLocale().getAvailableLocales()` returns ~160 locales: `ar_AE ar_JO ... in_ID en_GB`

In 21.06, this returns only 3: `en_US_POSIX en en_US`

**To Reproduce**
Use this vtl snippet 
[locales.vtl.txt](https://github.com/dotCMS/core/files/9155751/locales.vtl.txt)

```
\$date.getLocale().getAvailableLocales():
#foreach ( $i in $date.getLocale().getAvailableLocales() )
$i
#end

For each ["en-US", "en-US-POSIX", "en", "fr-CA", "invalid"]:
#set( $locales = ["en-US", "en-US-POSIX", "en", "fr-CA", "invalid"] )
#foreach( $locale in $locales)

=-=-=-= $locale =-=-=-=
\$date.getLocale().forLanguageTag($locale):  $date.getLocale().forLanguageTag(\$locale)
\$date.format("MMMM yyyy", \$date.getDate(), \$date.getLocale().forLanguageTag(\$locale) ):  $date.format("MMMM yyyy", $date.getDate(), $date.getLocale().forLanguageTag($locale) )
#end
```
See the output for each dotcms version in 
[53.out.txt](https://github.com/dotCMS/core/files/9155743/53.out.txt) and
[2106.out.txt](https://github.com/dotCMS/core/files/9155744/2106.out.txt)

This may impact other VTL, or may reach beyond velocity, but these are the only examples we have encountered.

Perhaps this is related to locale changes from Java 8 -> 9?
See 
https://openjdk.org/jeps/252 
https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html#providers
some blog posts on the issue
https://javachannel.org/posts/help-my-java-locale-is-wrong-in-jdk11/ 
https://incusdata.com/blog/locale-problems-upgrading-java8

related cloud support tickets:
https://dotcms.zendesk.com/agent/tickets/106269
https://dotcms.zendesk.com/agent/tickets/107921

**Comment by yolabingo** [comment]
On a lark and based on suggestions I read, I built a local `22.06` container with installed locales 
`apt install -y locales-all` 
then started dotcms with changed locale search order
`JAVA_OPTS: -Djava.locale.providers=HOST,JDK,CLDR,COMPAT`

but running with changed locale providers seems to break dotcms templates altogether.

**Comment by erickgonzalez** [comment]
Only for 21.06 and 22.03

**Comment by erickgonzalez** [comment]
we need to change the java-base in the dockerfile `11.0.15.9.1-amzn-locale` https://github.com/dotCMS/core/issues/22722

**Comment by erickgonzalez** [comment]
related to https://github.com/dotCMS/core/issues/22852
