### ISSUE TITLE
Fix NG0100: ExpressionChangedAfterItHasBeenCheckedError in DotDeviceSelectorComponent

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22617]
**Describe the bug**
When you go to edit a page, in console show this error:
` NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'. Find more at https://angular.io/errors/NG0100`

**To Reproduce**
1. Go to Site Browser, and double click a page (to go to edit page)
2. See error in console:
![Screen Shot 2022-07-22 at 12.20.31 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/49c739dc-ab2d-45bd-87c6-aa71a7c1afd2)

**Expected behavior**
Fix the error in DotDeviceSelectorComponent .

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/22643

**Comment by victoralfaro-dotcms** [comment]
Not seeing specific error in console.
![image](https://user-images.githubusercontent.com/64026161/186489340-5f34bb35-339e-4bb1-82b8-ee0c1d297aa4.png)

**Comment by bryanboza** [comment]
Fixed, tested on release 22.09 // Docker  // FF 

New card releted to the other errors here:  #22848
