### ISSUE TITLE
GraphQL page api anon permissions not working

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22615]
**Describe the bug**
When user try to get a page from the GraphQL API get error 500, looks like is related to permissions

**To Reproduce**
Run this query as anon user:

```
query ContainerRendered {
  page(url: "/index", languageId:"1") {
    url
    containers {
      identifier
      rendered {
        uuid
        render
      }
    }
  }
}
```

**Expected behavior**
It should return a response.

**Screenshots**
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/751424/180481739-192203a3-257e-4704-b1c3-e39a6f0b7124.png">

**Comment by victoralfaro-dotcms** [comment]
Run the mentioned query and got this response:
![image](https://user-images.githubusercontent.com/64026161/180847997-22d21961-f795-4330-89ce-4441e41c7c08.png)

**Comment by bryanboza** [comment]
Fixed, tested with the provided query and it works as expected. 
![image](https://user-images.githubusercontent.com/2641437/181103998-36423fa7-7526-4428-ba05-2ea388fa8293.png)
