### ISSUE TITLE
Password checker returns inconsistent results

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#22646]
**Describe the bug**
Password checker will pass simpler passwords and fail more complex passwords that should pass.

**To Reproduce**
1. Create User
2. enter password: Context2021!
3. save fails with message indicating it doesn't meet requirements
4. enter password: Context
5. save succeeds

**Expected behavior**
A simpler version of a failed password should not succeed.   A password that meets all requirements should succeed.

**Desktop (please complete the following information):**
 - OS: Mac OS 12.4
 - Browser Chrome and Safari
 - Version 22.03.1 LTS

**Comment by wezell** [comment]
Getting fixed here:
#22204

**Comment by wezell** [comment]
Additionally, you can try to override the default password REGEX found here:


https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/portal.properties#L309

by using an env variable, e.g.
```
DOT_PASSWORDS_REGEXPTOOLKIT_PATTERN=/[!#%+1234567890:=?@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]{8,}\\Z/
```
