### ISSUE TITLE
Cannot change date or time fields to never on an existing contentlet

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22667]
**Describe the bug**
You cannot change the expire date on an existing contentlet to 'never'. It throws the error `Unable to convert string to date +0000` (This issue makes it so you cannot manually unpublish content that has been published with an expire date.)

Also if you try to clear out a date field it throws the same error.

And if you try to clear out a time field, it sets automatically the time to 12:00 AM.

Related ticket: https://dotcms.zendesk.com/agent/tickets/108062 and https://dotcms.zendesk.com/agent/tickets/108761

**To Reproduce**

1. Create a content type with Publish and Expire fields
2. Create a contentlet of that content type, set the expire time to some time in the future
3. Save, then re-open the contentlet
4. Click the 'never' option and attempt to save the contentlet
5. You will see the following error:

![image](https://user-images.githubusercontent.com/78741732/182454164-830ba7a4-9793-40b6-9983-bda032389f20.png)

To Reproduce the clear out of a time field:
1- create a content type with a time field
2- create a contentlet of that content type and set up a time.
3- Save and re-open the contentlet.
4- Clear out the time by deleting the value.
5- Save and Publish
6- Re-open the contentlet, you'll see that the time is set to 12:00 AM.

**Expected behavior**
You should be able to remove expiry dates from contentlets with the 'never' option.

And you should be able to clear out date/time fields.

Reproducible in demo(22.09) and 22.03 LTS.

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/22667?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by freddyucv** [comment]
**Pass Internal QA**: test with the steps in the desccription

**Comment by erickgonzalez** [comment]
another customer hitting this https://dotcms.zendesk.com/agent/tickets/109207

**Comment by jdcmsd** [comment]
Still seeing this issue on 23.03, but inconsistently. Sometimes I get this after blanking a date field, sometimes not:

![image](https://user-images.githubusercontent.com/102264829/224363147-6cc14aec-f304-4729-b652-6562aee7240a.png)

I'm not sure if it makes a difference, but for a little while it seemed like if I erased it by triple-clicking vs backspacing, it would make a difference, but now even that is a bit inconsistent. 

I thought I was seeing it happen more with workflows that include Save Draft Content sub-actions, but the more I test the less I'm convinced that's a factor, too. 

It's a real puzzle.

**Comment by dsolistorres** [comment]
New PR: https://github.com/dotCMS/core/pull/24413
To handle all the different time zones, we can get rid of the timezone offset when the user set the field value as blank.

**Comment by erickgonzalez** [comment]
Customer ticket hitting the new issue https://dotcms.zendesk.com/agent/tickets/110404

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.03_5108019d_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Unable to unchecked the ' Never ' box to a contenlet with expiration Date and Time fields

https://user-images.githubusercontent.com/129882031/230936033-e9f23ce4-7e1f-474c-be9e-4aa5764155e3.mov

**Comment by erickgonzalez** [comment]
@josemejias07 I don't think this is an issue, this is reproducible in demo.

This is because the expire date field is set at content type level, and since you're leaving blank we default to check the `Never` checkbox

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_2539461f_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Note: Please see comment form dev above.

**Comment by waqasakramdot** [comment]
Another customer is having this on dotCMs (23.0.1) https://dotcms.zendesk.com/agent/tickets/111152
