### ISSUE TITLE
What's Changed UI issues

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22673]
**Describe the bug**
The **What's Changed** presents 2 UI issues:
1- The checkbox isn't checking (but it works).
2- When enabling the What's Changed Feature, there is no way to disable it.

**To Reproduce**
1. Site > Browser
2. Select any page
3. Go to Preview Mode
4. Click over the What's Changed Checkbox 
5. Checkbox doesn't check but enables the feature**(First issue)**
6. Click over again the Checkbox to disable the feature
7. Nothing happens **(Second Issue)**

**Expected behavior**
We should check the checkbox whenever the feature is enabled, and we should be able to disable the feature.

**Screenshots**
https://user-images.githubusercontent.com/5278970/182632491-99b3c08a-b114-4261-9db8-d50793cac2ee.mov

Reproducible in 22.03.2 LTS, demo (22.06).

Customer ticket: https://dotcms.zendesk.com/agent/tickets/108067

**Comment by nollymar** [comment]
dupe of #22280

**Comment by alfredo-dotcms** [comment]
PR https://github.com/dotCMS/core/pull/22752

**Comment by nollymar** [comment]
**Internal QA:** Passed

https://user-images.githubusercontent.com/8741395/188005512-aaf174fc-a1fb-4a94-a874-b3892fe2158b.mov

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.09_a506dc69_SNAPSHOT // Docker // mac OS 12.6  FF 105.

**Note:** I did made some changes to the UI using the layout tool of the browser and no changes were recorded. 
I know that this is a part of the Time Machine functionality therefore I'm not sure if the changes I made will count as a proper workflow.

**Comment by erickgonzalez** [comment]
Not reproducible in 21.06 LTS
