### ISSUE TITLE
Time Machine: We are not respecting the expire value when you set this in a content type

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22679]
Id you add a system indexed fields type date time, we are able to set as a Publish/Expire values in the content type, but we are not respecting this in the future time machine snapshots. 

https://user-images.githubusercontent.com/2641437/182687314-fb2bdc9b-e303-4490-999d-cd809cfe5d4b.mov

**To Reproduce**
- Add a new content type of page type 
- Add two date/time fields (system indexed)
- Edit the content type and set this values in the Publish and Expire fields 
- Create a new page of that type and make sure to set an expiration date
- Now go to the time machine portlet and try to see your site after the expiration date of the page 

**Expected behavior**
We need to respect the expiration date and don't show it as live in the time machine, because for this date the page should not be published. 

**Desktop (please complete the following information):**
Tested on release-22.07 // Docker // FF

**Comment by freddyucv** [comment]
It is happening at least from 22.06

**Comment by bryanboza** [comment]
We can move this to Next Release @dsilvam
