### ISSUE TITLE
We replace the UserID with a hashed version of the UserID when creating SAML users

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#22692]
**Describe the bug**
We replace the UserID with a hashed version of the UserID when we create SAML users. This can cause issues where the UserID is used as a reference against other data. 

Ticket: https://dotcms.zendesk.com/agent/tickets/107795

**To Reproduce**
1. Configure SAML as SSO
2. Log in as a new user. 
3. UserID will be hashed.

**Expected behavior**
While this is a good solution for dealing with invalid UserIDs, there are scenarios that a client will WANT their UserIDs to be in dotCMS, so this should be configurable.

**Comment by bryanboza** [comment]
Fixed, now we are able to add the follow property to the SAML configuration `hash.userid=false` and disable this. 

By default this is enabled and here is the `UserId` 
![Image](https://user-images.githubusercontent.com/2641437/187741111-cdca8a88-4ff1-434d-ba1c-021b7dd22041.png)


After disable the property and create the role again, this is the `UserId`
![Image](https://user-images.githubusercontent.com/2641437/187741288-09581359-d6f3-406e-b81f-1665cbc1f29a.png)

Tested on release-22.09 // Docker // FF
