### ISSUE TITLE
Can't save changes in Work Flow if user with special characters or new user is added.

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#22696]
**Bug Description**
Can't save changes in Work Flow if user's name has special characters or if user is recently created in 'Who can Use' panel.

**To Reproduce**
1. Go to 'Work Flows'
2. Select any Work Flow step.
3. In 'Who can Use' make sure that an user with special characters or new user is already added (I've created an user with name 'Aurélie Leclerc').
4. In 'Show When' panel change some options.
5. Click 'Save'.
6. 'FAILURE: null' error pops up.

**Expected behavior**
No error messages pops up, the message expected is 'Saved'.

**Screenshots**
![Screen Shot 2022-08-08 at 9 10 51 AM](https://user-images.githubusercontent.com/12899960/183463536-cf365348-601f-4515-b2ad-2eb012ccae13.png)
![Screen Shot 2022-08-08 at 9 11 20 AM](https://user-images.githubusercontent.com/12899960/183463619-e519d2e8-3844-4781-98c4-dcd21efdaf9d.png)
![Screen Shot 2022-08-08 at 9 17 02 AM](https://user-images.githubusercontent.com/12899960/183464679-547ffafa-a7be-45b2-af4a-8631090172f3.png)
<img width="1204" alt="Screen Shot 2022-08-08 at 10 59 33 AM" src="https://user-images.githubusercontent.com/12899960/183483212-cecdafe2-0095-4a91-a48d-7052a3a6385e.png">
![Screen Shot 2022-08-12 at 10 15 50 AM](https://user-images.githubusercontent.com/12899960/184410101-d60325fd-e5d3-466f-88a9-8f9cc3b9e7ca.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave (Chrome)
 - Version: 1.41.100

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Monterey
 - Browser: Brave (Chrome)
 - Version: 1.41.100

**Additional context**
If you add an user with special characters/recently created and do changes in 'Show When' panel you will be able to save changes, but if an user with special characters is already added in 'Who can Use' panel and then make some changes the error message appears.

**Comment by nollymar** [comment]
PR: #22753

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me.  Passing it

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes. Tested on release-22.09 // Docker // FF
