### ISSUE TITLE
Log Viewer: Roll back filter and highlight features

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#22691]
For performance reasons, we need to temporarily roll back this implementation https://github.com/dotCMS/core/issues/21848

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/22688

**Comment by bryanboza** [comment]
Fixed, tested in the last snapshot of release-22.07 and we reverted the change without problems, everything looks like in previous versions.
