### ISSUE TITLE
Limited user without Search Portlet can't Edit Content From Edit Page Portlet

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22698]
**Describe the bug**
If a limited user has permissions to edit a page and content but doesn't have in their portlets the Search Portlet, when trying to edit anything from the Edit Page Portlet an error is thrown. 

Content is able to be edited from the site browser, right clicking edit.

**To Reproduce**
1. Create a limited user, with BE permissions, edit permissions over pages and content.
2. Add only the Site Content Tool.
3. log in as the limited user.
4. Open a page
5. Click over the properties tab that shows on the right on the screen.
6. Get an error.
7. Go back to the Site Portlet
8. Right click over the page
9. Edit Properties
10. You can edit them successfully.

**Expected behavior**
You should be able to edit content within the Edit Page, regardless of the portlets you have assigned.

**Screenshots**
https://share.vidyard.com/watch/hhd62XKZsN6Z6DKNMgEmdN

Reproducible in demo (22.06) and 22.03.2 LTS.
Customer ticket https://dotcms.zendesk.com/agent/tickets/107890 and https://dotcms.zendesk.com/agent/tickets/110050

**Comment by waqasakramdot** [comment]
Another customer hitting it: https://dotcms.zendesk.com/agent/tickets/113220

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_39ca5c4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

**Comment by waqasakramdot** [comment]
Another customer hitting this here: https://dotcms.zendesk.com/agent/tickets/114420
