### ISSUE TITLE
Image Field Pathing in Velocity resulting in null values

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#22702]
**Describe the bug**
Pathing for image fields is not working as per our documentation: https://www.dotcms.com/docs/latest/displaying-images-with-binary-image-fields

The following statements produce a NULL return for image fields when iterating over content in a velocity pull of content (where "screenshot" is the var name of an image field):

$newsItem.screenshot.shorty
$newsItem.screenshot.shortyUrl
$newsItem.screenshot.image.identifier

`#foreach($newsItem in $dotcontent.pull("+contentType:news",10,"modDate desc"))
    $newsItem.screenshot.shorty<br>
    $newsItem.screenshot.shortyUrl<br>
    $newsItem.screenshot.map.identifier<br>
#end`

This bug and NULL returns hinders returning image fields and filtering on image fields.  When fixing these three calls as per our documentation we should take the opportunity to make an improvement.  What front end developers really want is the dotAsset image path:
     Ex: /dA/a27c14b8-a09a-4d3a-844a-2baee22fa14e/fileAsset
     
This is needed to then add all image filtering at the end of that path (resizing, focal point, cropping, etc.)

When iterating with a foreach loop over all content with image fields, the following method should be added to give the full dotAsset image path:

$newsItem.screenshot.path (or something like that)

This should return, for example: /dA/a27c14b8-a09a-4d3a-844a-2baee22fa14e/fileAsset

This would be a more efficient than making the front end developer type this all the time:

/dA/$newsItem.screenshot.image.identifier/fileAsset (current)    VS    $newsItem.screenshot.path (suggested)

**Comment by wezell** [comment]
closed in favor of #22704
