### ISSUE TITLE
Create custom tool from Content Type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22724]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to add content types to the navigation as easy and fast as possible while creating or edit a content type.

**Describe the solution you'd like**
Add a "Add to menu" button to the toolbar.

<img width="1462" alt="Screen Shot 2022-08-09 at 16 13 03" src="https://user-images.githubusercontent.com/751424/183771232-7d3f5991-483b-49be-9238-9370b3b75434.png">

https://user-images.githubusercontent.com/751424/220363003-75e491fe-55b9-435d-b5eb-e2c30ad066b9.mp4

And show the same dialog we use from the listing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** [`dotcms/dotcms:master_70229c6b`]



https://user-images.githubusercontent.com/72418962/226982356-926fd2ff-9a34-4266-8ef8-11618d8de45d.mov

**Comment by fmontes** [comment]
@josemejias07 out of this scope, create a new ticket to be triaged.

**Comment by bryanboza** [comment]
We need a clearer message when you try to add a content type to a menu twice, right now we are generating the ID based in the name. Then for the end user is easier to understand if we show names instead IDs on this message 

![Image](https://user-images.githubusercontent.com/2641437/231285261-c7db361d-3c38-4aa2-8186-16375bc98621.png)

**Comment by josemejias11** [comment]
> @josemejias07 out of this scope, create a new ticket to be triaged.

https://github.com/dotCMS/core/issues/24602

**Comment by bryanboza** [comment]
Both problems was moved to new cards https://github.com/dotCMS/core/issues/24602 and https://github.com/dotCMS/core/issues/24601
