### ISSUE TITLE
Include Locale in java packaging

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22722]
We need to include the `jdk.localedata` in our java-seed that we use to run dotCMS

**Comment by nollymar** [comment]
PR: #22723 22723

**Comment by wezell** [comment]
@yolabingo Can you share the steps to test this change?

**Comment by yolabingo** [comment]
`$date.getLocale().getAvailableLocales()` 
should return long list of locales, rather than just `en_US_POSIX en en_US`

and
`$date.format( "MMMM yyyy", $date.getDate(), $date.getLocale().forLanguageTag("fr-CA") )`
should return month name in French `aout`

**Comment by nollymar** [comment]
**Internal QA:** Passed
It is working as expected with the examples provided. 
Using this code snipped for example:

```
<b class="d-block">Locales: $date.getLocale().getAvailableLocales().size()</b>
<b class="d-block">Locale in French: $date.format( "MMMM yyyy", $date.getDate(), $date.getLocale().forLanguageTag("fr-CA") )</b>
#foreach($locale in $date.getLocale().getAvailableLocales())
       <a class="text-capitalize">${locale.country}</a>#if(${velocityCount} < $date.getLocale().getAvailableLocales().size()), #end
#end
```

I get this output: 
<img width="1414" alt="Screen Shot 2022-08-18 at 5 15 42 PM" src="https://user-images.githubusercontent.com/8741395/185504616-c130a46b-0e24-40c6-aa85-6b66157ac0bc.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.09 // Docker // FF 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2641437/185952144-720f5077-b634-4708-bf9e-b0c005290eaa.png">

**Comment by wezell** [comment]
@erickgonzalez @jdotcms I wonder if the missing timezones are why the TimeZone startup task was not adjusting the offsets correctly?

**Comment by jdotcms** [comment]
> @erickgonzalez @jdotcms I wonder if the missing timezones are why the TimeZone startup task was not adjusting the offsets correctly?

@wezell I am not sure if it is the case, @erickgonzalez do you know if their instance has just such as 3 locales, or bunch of them?

**Comment by wezell** [comment]
@swicken-dotcms this might might fix the timezone startup task.  I am thinking this because that startup task does a timezone lookup and uses the timezone data to calculate the offset to update the dates with.  It might be (I haven't tested) that if the timezone is not available in java that it just returns UTC, which would throw everyones dates off.
