### ISSUE TITLE
Site Selector not showing pagination

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22734]
**Describe the bug**
We updated the site selector in 22.02, but we missed/broke a few things.
1. We should show more hosts by default. I would say we should a least 20 per page if not more.
2. When a user clicks on the host selector, their cursor should focus in on the input box so they can immediately start typing.
3. We should show the pagination controls if they are needed

**To Reproduce**
1. Create over 10 sites.
4. Open the pagination.

**Expected behavior**
According to @fmontes Pagination controls should be in one line.

**Screenshots**
![Screen Shot 2022-08-10 at 11 20 46 AM](https://user-images.githubusercontent.com/5278970/183980109-148d88c8-3879-4b1e-a010-0e98a7daf30e.png)

Reproducible in 21.06 LTS.

**Note:** demo (22.08) the site selector doesn't even paginate so I couldn't test over there.
![Screen Shot 2022-08-10 at 11 48 04 AM](https://user-images.githubusercontent.com/5278970/183981448-16f4a05a-82c5-4d85-bbc5-29cd0e058be7.png)

**Comment by erickgonzalez** [comment]
Customer ticket: https://dotcms.zendesk.com/agent/tickets/108172

**Comment by nollymar** [comment]
PR: #22765

**Comment by nollymar** [comment]
Note to QA: According to #21417, we should show at least 40 sites before we paginate

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22773/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

Now, the pagination is not displayed and the max records listed is 15:
<img width="1675" alt="Screen Shot 2022-08-18 at 4 53 44 PM" src="https://user-images.githubusercontent.com/8741395/185502686-2f2a2a47-10fc-4f98-ae7d-2ae1a2460703.png">


This change also works when applying a filter: 
<img width="1672" alt="Screen Shot 2022-08-18 at 4 53 59 PM" src="https://user-images.githubusercontent.com/8741395/185502705-e6a60b75-001d-4a9a-879d-36740f7da969.png">

**Comment by josemejias07** [comment]
Failed QA - Tested on 22.09_cb5a8a1d_SNAPSHOT // Docker // FF

Max number of sites showing on the search drop down should be set to 15. Right now only shows 10 entries tops.

**Comment from** Nollymar on https://github.com/dotCMS/core/issues/22734#issuecomment-1216079537

The max number of records to be listed will be 15.

![Screen Shot 2022-08-19 at 11 47 47 AM](https://user-images.githubusercontent.com/110418590/185678711-f749bd4f-8fe7-4a09-949b-9b0aced44633.png)

**Comment by nollymar** [comment]
@josemejias07 please test again with a new docker image because that image was corrupted. I tried with this one `22.09_82a5e0cb_SNAPSHOT` and it's working

**Comment by wezell** [comment]
@nollymar @josemejias07  - also, please confirm that 
1. the cursor is focus in the search box when you click the control
2. Bonus test - Keyboard navigation up and down works

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.09_82a5e0cb_SNAPSHOT // Docker // FF

Selection of objects of the drop down fields should be perform by the use of up and down keys. Currently focus only remains on the search field.

Comment from Will https://github.com/dotCMS/core/issues/22734#issuecomment-1221329879

The max number of records is working fine.

**Comment by nollymar** [comment]
@josemejias07, the use of the keys has never been enabled for this dropdown and is not part of the scope of this issue. Could you please file a new card, so we can discuss the priority of this new requirement with @wezell ?

**Comment by nollymar** [comment]
Sorry @josemejias07 I hadn't seen this comment https://github.com/dotCMS/core/issues/22734#issuecomment-1221329879

> @josemejias07, the use of the keys has never been enabled for this dropdown and is not part of the scope of this issue. Could you please file a new card, so we can discuss the priority of this new requirement with @wezell ?

**Comment by nollymar** [comment]
@josemejias07 as discussed on the meeting, the new requirement for the keys will be implemented on https://github.com/dotCMS/core/issues/22835. So, I think we can pass this one, right?

**Comment by josemejias07** [comment]
Pass QA - Tested on 22.09_2c7af5a0_SNAPSHOT // Docker // FF

Additional pending behavior will be work on https://github.com/dotCMS/core/issues/22835

Thanks @nollymar
