### ISSUE TITLE
[UI] Add new Icon of Experiments in Page Edit

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22758]
Add a new Button to access to Experiment Feature.
This feature will be enabled by the config property `EXPERIMENTS_ENABLE`

Endpoint for getting config properties: `https://demo.dotcms.com/api/v1/configuration/config`
token: `EXPERIMENTS_ENABLE=true|false`

![Screen Shot 2022-08-15 at 1 51 10 PM](https://user-images.githubusercontent.com/1909643/184697396-10dc3d6e-e386-415d-a101-ca93617e2064.png)

**Comment by dsilvam** [comment]
Passed Internal QA: Showing Icon when property enable. Not showing when property absent or disable
