### ISSUE TITLE
Expose An Endpoint for getting Subcategories

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#22755]
**Is your feature request related to a problem? Please describe.**
We already have an endpoint to get Categories **/api/v1/categories/** However There is no endpoint to get subcategories against a catagrory

**Describe the solution you'd like**
We may expose an endpoint **/api/v1/categories/{catagory}** that will return all information including subcategories
OR
something like **/api/v1/categories/{catagory}/subcategories** to get only subcategories against category

**Comment by erickgonzalez** [comment]
Customer requested https://dotcms.zendesk.com/agent/tickets/108325

**Comment by erickgonzalez** [comment]
This has been taken care of https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoriesResource.java
