### ISSUE TITLE
Improve performance of DB Metadata impl

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22779]
When rolling out the metadata changes, we provided two impls, one a fs based impl and one a db impl\.  The DB impl was intended to be our default impl because it helped lower our dependency on the NFS share but we found that in actuality, it caused a bottleneck because it had to do a DB lookup, then write a temp file before it could return the metadata\.  <span data-preserve-white-space></span>

We should improve\/tune up this impl so that it can become our default impl and just return the metadata using a single db query without having to write a tmp file\. <span data-preserve-white-space></span>

**Comment by wezell** [comment]
Link to subfeature: https://dotcms.productboard.com/feature-board/planning/features/14928643

**Comment by jdotcms** [comment]
Waiting for Fabro's QA

**Comment by fabrizzio-dotCMS** [comment]
PR is https://github.com/dotCMS/core/pull/22834

**Comment by fabrizzio-dotCMS** [comment]
I performed a load test using the tool called "siege" 
https://medium.com/@guy.callaghan/load-testing-with-siege-3fa6a1e8118d
Feeding it with a file with 103 transactions. Each transaction is meant to generate metadata for 50 different binaries.
[metadata-load-testing.txt](https://github.com/dotCMS/core/files/9892102/metadata-load-testing.txt)

The test environment was seeded with 5300 separate file assets
the test was executed against both implementation DB vs FILE_SYSTEM in 3 rounds on every round the intermediary files were completely removed and the whole cache was flushed

 a summary of the results can be seen here https://docs.google.com/spreadsheets/d/1Qr0EByhNI_RUmtmhd8D6_oXRB0B24dQFyr8zaXq9Ako/edit#gid=0
