### ISSUE TITLE
UT Task210901UpdateDateTimezones not running successfully

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22771]
Customers upgrading to 22.03 LTS are seeing issues with their time values, it seems that this task is not running as it should.

We need to check the following:
1- it’s changing the column type but not updating the values, need to investigate why?
2- it’s only updating the date fields, we should update the `mod_date`
3- Even if run, we think the offset has to be multiple by -1, this is because it tells us how many seconds our timezone has a difference between UTC, so we need to add/subtract this accordingly.

Ask support for dataset to test this.

### Acceptance Criteria
- Database dates must be in `UTC` timezone after running the task.
- Additionally, all date columns in the `contentlet` table must be in `UTC` timezone and correctly transformed into the right time based on the Locale selected by the customer in the BE.
- Check dates and times in the `contentlet` table before and after the update.

**Comment by erickgonzalez** [comment]
For current customers that experience this issue we need to:
1- Run this query to get the customer timezone:
`select udt_name from information_schema.columns where table_name='contentlet' and column_name='date25';`

2- Go to https://dateful.com/time-zone-converter and check the hours diff between timezones, e.g between UTC and EST is -5 hours (meaning EST is 5 hours behind UTC)

3- run the following queries, modify as needed: (one for each date field and also for mod_date)

update contentlet set date1 = date1 + interval '18000' SECOND where date1 is not null;

**Comment by erickgonzalez** [comment]
Only applies to 22.03 LTS

**Comment by erickgonzalez** [comment]
Need to consider change timezone e.g EDT/EST

**Comment by wezell** [comment]
See also: #22722

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/22771?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by erickgonzalez** [comment]
We need also to update `syspublish_date` and `sysexpire_date` of the identifier table

**Comment by bryanboza** [comment]
We need some work here, after testing multiple times locally, with a real data set we are unable to get the expected results.

**Comment by bryanboza** [comment]
Fixed, finally we are able to run de upgrade and get the corresponding date/time in each piece of content. 

Tested in a real database in postgres // Release-22.10
