### ISSUE TITLE
Create default variant

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#22790]
We need to create a `default variant`, so we need to:

**Create a new TaskUpgrade to:**

- Create a `default variant` in the variant table
- Add a new variant field to "contentlet_version_info", the default value should point to the `default variant`

**Comment by freddyucv** [comment]
PRs:

https://github.com/dotCMS/core/pull/22868

**Comment by dsilvam** [comment]
Note for QA: Verify all records in `contentlet_version_info` have variant = DEFAULT

**Comment by dsilvam** [comment]
Needs work: failing upgrade in MSSQL: https://gist.github.com/dsilvam/4fbe28b5b844920588a546b1cc914e66

**Comment by victoralfaro-dotcms** [comment]
MSSQL:
```select * from variant```
```DEFAULT,Variant use by DEFAULT when a Contentlet is created,0```
New contentlet creadted:
![image](https://user-images.githubusercontent.com/64026161/195953431-bc9784c6-8488-4a8e-b7ad-5261b23885bb.png)
```select * from contentlet where title = 'dinho'```
```183eecb3-8f40-47dc-bf9c-590f1ce0a4fc,0,dinho,2022-10-14 22:28:56.275 +00:00,dotcms.org.1,0,dinho,c541abb1-69b3-4bc5-8430-5e09e5239cc8,"",7781f30550cac8ec7cb04ca227ecc82e
```
```select * from contentlet_version_info where identifier = '7781f30550cac8ec7cb04ca227ecc82e'```
```7781f30550cac8ec7cb04ca227ecc82e,1,183eecb3-8f40-47dc-bf9c-590f1ce0a4fc,183eecb3-8f40-47dc-bf9c-590f1ce0a4fc,0,,2022-10-14 22:28:56.503 +00:00,2022-10-14 22:28:56.977 +00:00,DEFAULT
```

**Comment by victoralfaro-dotcms** [comment]
Upgrade from 22.08 to master:
```
17:08:01.355  INFO  startup.StartupTasksExecutor - Running Upgrade Tasks: Task220824CreateDefaultVariant
17:08:01.371  INFO  startup.StartupTasksExecutor - Database upgraded to version: 220824
17:08:01.403  INFO  startup.StartupTasksExecutor - Running Upgrade Tasks: Task220825CreateVariantField
```
