### ISSUE TITLE
Redirect traffic for the different variants

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#22818]
We need to inject the traffic code as well with #22812 

If the user is into the experiment, we need to redirect in JS code to the right variant that he should use

To know if the user is into a Experiment and what variant he is using we need to use the cookies create in : https://github.com/dotCMS/core/issues/22813

it should be something like:

https://github.com/dotCMS/core/pull/22626/files#diff-164d80c06c39a7434852ce6577df1954cb608b2fa64032a0f4656867752f58c5R1

The custom event is trigger is the user is into a experiment after call the shouldBeIntoExperiment end point

https://github.com/dotCMS/core/pull/22626/files#diff-9417bef73d32b061e75306b404886f1b00b867e22696a5ba0b0717473190c922R7

I not sure that trigger the event is the best way to implement it

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22818?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
**Note to QA:**

First the last case commented here: https://github.com/dotCMS/core/issues/22812#issuecomment-1324331079

Also this case should work:

-  Create/Start a Experiment int the /blog/index page without rules
- Request the home page and make sure that you was assign to a experiment, you must because the experiment not have any rules
- Check what variant was assign to you. make sure that it was not the DEFAULT variant, if it is the DEFAULT Variant then remove the local storage and cookie and try again
- After you was assing into a Experiment with a variant different a DEFAULT then navigate into the blog/index page and you are going to be redirect into /blog/index?variantName=... page

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/23417

**Comment by dsilvam** [comment]
Needs work: redirection is not happening.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/23448

**Comment by dsilvam** [comment]
Needs work: redirect is not happening if your first page of the session is the one of the experiment

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/23489

**Comment by dsilvam** [comment]
Passed Internal QA: Traffic properly redirected to the expected variant.
