### ISSUE TITLE
Track event Server side

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#22817]
We are going to user this plugins to send the event from DotCMS server to jitsu:

https://github.com/dotCMS/com.dotcms.jitsu

do we need to include this code into the dotCMS core when we get out with Experiment?

We need to save some more data in each Event like:

- Variant that the visitor is using
- Experiment name.

https://github.com/dotCMS/com.dotcms.jitsu/pull/1/files#diff-57dcb40725e634f6dbc4b3f0eb30c3b305a422567d67d5154707b168e4a98027R135

**Acceptance Criteria:**

- Move the plugin code into core
- Make postman test if it is possible and/or integration test (don't forget the JOB https://github.com/dotCMS/com.dotcms.jitsu/blob/main/src/main/java/com/dotcms/jitsu/webinterceptors/EventLogRunnable.java#L34)
- Include the code to storage the new data

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22817?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by wezell** [comment]
We will need the Jitsu Key from the App, which is issue #23052

**Comment by freddyucv** [comment]
Note to QA:

- Set the follow into the config properties 

EVENT_LOG_TOKEN=js.cluster1.customer1.3c7ftd589dwax9eqpz
EVENT_LOG_POSTING_URL=http://localhost:8081/api/v1/event

The values depende of the jitsu that you are using in my case I use a online account, in this case you can get the values right here:

<img width="1553" alt="Screen Shot 2022-11-02 at 14 36 42" src="https://user-images.githubusercontent.com/10408015/199597500-81dd7065-be37-454e-aca1-cf7abee81396.png">

- Include this JS code into the pages, I included it into the travel theme into the /application/travel/header.vtl file 

<script src="//$mySite/s/lib.js"
        data-key="js.XXXXXXXX"
        data-init-only="false"
        defer></script>
<script>window.jitsu = window.jitsu || (function(){(window.jitsuQ = window.jitsuQ || []).push(arguments);})</script>

Again you can get the key from

<img width="1584" alt="Screen Shot 2022-11-02 at 14 40 00" src="https://user-images.githubusercontent.com/10408015/199598098-5e758baa-dcb4-46ef-b1f1-7f7ab9c3cdaf.png">
