### ISSUE TITLE
Contentlet editor behaving oddly (styles broken?) in 22.09

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#22810]
**Describe the bug**
Seen in Auth (22.09) while trying to edit documentation, starting today.

**To Reproduce**
1. Open any Documentation contentlet on Auth.
2. The third ("Documentation") tab — containing markdown in a WYSIWYG editor in Code mode — appears all wedged to the left of the window. 
    1. Also it is possible to "scroll" down away from the field altogether, by placing the cursor outside of the field (but inside of the bottom left section) and scrolling down.
    2. The fourth tab ("Documentation Markdown," which contains a block editor) now features a field too large to fit vertically into the pane, leading to a scroll within a scroll within a (third, invisible) scroll.

**Expected behavior**
- All the text should occupy the entire field
- The field should not exceed the view height
- the bottom left section should not scroll unless there's stuff to scroll through (and even then, there should probably be a scrollbar)

**Additional context**
Temporary Workaround for item 2: If you hit Undo and Redo as soon as the code field loads, it will blank itself and re-enter the text, and then it will be placed correctly. However, even saving this does nothing to repair the field, and the next time it loads, it will be askew again.

**Screenshots**
![image](https://user-images.githubusercontent.com/102264829/185695770-844a9973-542e-4d68-8eb6-36bb7d2481be.png)
![image (1)](https://user-images.githubusercontent.com/102264829/185695784-35301a53-c275-4124-a28b-c85b1ae34d7a.png)
![image (2)](https://user-images.githubusercontent.com/102264829/185695793-8ba6eeac-be69-4e53-840a-85ffa911496c.png)

**Desktop (please complete the following information):**
OS: macOS Montgomery 12.5
Browser: Brave
Version [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (arm64)]

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22828/files

**Comment by nollymar** [comment]
**Internal QA:** I still see the issue on authoring (docker image: `22.09_9d06a7e1_SNAPSHOT`)


https://user-images.githubusercontent.com/8741395/187549739-a6df6d71-efd1-4d9a-8327-aec89d307d14.mov

**Comment by bryanboza** [comment]
Fixed, tested on authoring and now it is working as expected.
