### ISSUE TITLE
Create new JSON Field Type

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#22829]
- [x] - graphql responses should map to a new map object or the JSONObject (which is now a map)
- [x] - velocity/contentmap should return a Map<String,Object> or the JSONObject (which is now a map)
- [x] - content api puts should accept the prop as json

**Comment by wezell** [comment]
- api responses should be just an extension of the json object
- graphql responses should map to a new map object or the JSONObject (which is now a map)
- velocity/contentmap should return a Map<String,Object> or the JSONObject (which is now a map)
- content api puts should accept the prop as json
-

**Comment by wezell** [comment]
Missing Field Icon and translations:

![Screen Shot 2022-09-28 at 3 44 16 PM](https://user-images.githubusercontent.com/934364/192874408-277aaec6-af49-4790-88d5-c3e817a695d4.png)

**Comment by oidacra** [comment]
Icon Fixed.

![Screen Shot 2022-09-29 at 10.22.40 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/c9869a73-7a2c-420a-b52c-d86ae66ba376)

**Comment by victoralfaro-dotcms** [comment]
GraphQL response:
```
{
	"data": {
		"ExperimentCollection": [
			{
				"name": "my experiment",
				"description": "my experiment desc",
				"trafficAllocation": 100.0,
				"trafficProportion": {
					"variants": [
						{
							"name": "default",
							"trafficPercentage": 50.0
						},
						{
							"name": "variant1",
							"trafficPercentage": 50.0
						}
					],
					"type": "SPLIT_EVENLY"
				}
			}
		]
	}
}
```

**Comment by bryanboza** [comment]
After test this field, we need some work here: 

- We have problems when you set the `Required` property, we get the required exception no matter if you have content in the field or not. 
![Image](https://user-images.githubusercontent.com/2641437/193730204-7a9d9f3e-6be9-4455-b578-f67c1c20befb.png)

- We need to catch the required exception and print just a line error on the logs, right now when you have the exception we are printing too many lines just for the required error. Here the stack-trace 
https://gist.github.com/bryanboza/90b4c7eb1609bc57916ded4243934359

- We are not saving the data on this field, attached the screen cast 
https://user-images.githubusercontent.com/2641437/193731001-81f44c0e-36ff-48c2-a0eb-1edd503ca2e8.mov

**Comment by fabrizzio-dotCMS** [comment]
I was able to verify the required field case has been fixed.
In most cases, validation is applied over the entered text to ensure it corresponds to a structured JSON
However I was able to save invalid JSON like this: 

`{}
 {}
 {}`

or this

`
{} LOL

`
![Screen Shot 2022-10-13 at 17 17 10](https://user-images.githubusercontent.com/37148755/195728138-0f4fa943-7bd9-4401-bb74-54c0d48fb6e5.png)

still needs work.

**Comment by fabrizzio-dotCMS** [comment]
Passed IQA

**Comment by bryanboza** [comment]
After test some things here are some improvements: 

- We need to catch the json exception and print just a line error. Here is the log that we have right now 
https://gist.github.com/bryanboza/077a5f2503b9a22880ebe97892c4ce74

- We need to remove the validation regex fields from the field properties 
![Image](https://user-images.githubusercontent.com/2641437/196235068-68e14c0e-af88-4e1f-ac35-6cc9deaed039.png)

**Comment by hmoreras** [comment]
support of json filed on compare versions, https://github.com/dotCMS/core/pull/23182

**Comment by bryanboza** [comment]
We have a new case that needs some work here: 

- If you save a piece of content that includes a json field, then editing this piece of content you try to clean the field and leave it blank, we are unable to do that. 

https://user-images.githubusercontent.com/2641437/196291372-2b9e1761-df75-4a6e-b61f-e6c495b204cf.mov

**Comment by dsilvam** [comment]
@bryanboza That's an old issue. If you try the same with a normal text_area the same thing will happen.

**Comment by bryanboza** [comment]
Regarding the required exception here is the new card: #23184

**Comment by bryanboza** [comment]
Regarding the toggle editor problem, it was also moved to a new card: #23187
