### ISSUE TITLE
Allow for keyboard navigation on NG dropdowns

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22835]
**Acceptance Criteria:**
- Like the site selector.  The rule is
Up/Down arrows go up and down
tab goes to the next element
enter selects

### Example of Dropdowns in NG app
* Login As dialog
![image](https://user-images.githubusercontent.com/37185433/191061624-062676cd-3df7-44ff-ba53-eaf05c779afd.png)

* Persona dialog
![image](https://user-images.githubusercontent.com/37185433/191062014-11f8f077-97a3-4ebc-ab8c-880f547055ce.png)

* Edit Layout - Add Container
![image](https://user-images.githubusercontent.com/37185433/191062187-0f450eb6-9bd5-4eda-994d-296c326786e2.png)

* Theme selection
![image](https://user-images.githubusercontent.com/37185433/191062325-17bca946-8e96-44d8-91a2-e335015f5419.png)

* Create template 
![image](https://user-images.githubusercontent.com/37185433/191062505-16d5bef6-e21b-48db-b7a3-a7097757701d.png)

**Note**: If you do "Inspect" on your browser and find css class "dijit", then it's a DOJO dropdown (implementation not included on this task)
![image](https://user-images.githubusercontent.com/37185433/192600269-d52f2e2e-4f3a-4abe-875a-15da3ba14fd2.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23005/files

**Comment by alfredo-dotcms** [comment]
https://github.com/dotCMS/core/pull/23005#issue-1375971829

**Comment by nollymar** [comment]
**Internal QA:** Needs work

When I tested the up/down arrows in the PP modal, it selected more than one user after hitting Enter. However, when I used the mouse, it just selected one


https://user-images.githubusercontent.com/8741395/192639894-bb03e44c-9847-4e61-ab3c-e0bbb05b8338.mov

**Comment by alfredo-dotcms** [comment]
Notes for new findings on https://github.com/dotCMS/core/issues/22835#issuecomment-1260078706

4) this won't be fixed on this task, the way that component was built in Rules is too attached and trying to fix it has lots of potentials to break rules.
**Explanation**: every time an option is pick from the dropdown, the whole Rule Action components get re-rendered so you endup with new html components that makes you loose focus and can not continue navigating with the keyboard

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23079

**Comment by nollymar** [comment]
**Internal QA:** Passed

According to the comment left [here](https://github.com/dotCMS/core/issues/22835#issuecomment-1262917909), I tested cases 2.B and 3 which are working as expected.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.11_4889b92f_SNAPSHOT // Docker // macOS 12.6 FF v106.0.3

**Feedback**
[Feedback_#22835.xlsx](https://github.com/dotCMS/core/files/9921782/Feedback_.22835.xlsx)

@alfredo-dotcms You can leave your comment on the .xlsx file or here as a comment with the related line on the file.
