### ISSUE TITLE
Update the image node block to support dot-images and html images

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22832]
**Is your feature request related to a problem? Please describe.**
We need to support default HTML images blocks because:

1. Convert WYSIWYG field to block editor
2. Copy and paste HTML images.

Currently, we only support special `dot-asset` images, and we're going to keep supporting this but also regular images `<img>`.

**Describe the solution you'd like**
We can extend the tiptap Image node.

By default the image node have this content:

```
{
    attrs: {
        alt: null
        src: "https://source.unsplash.com/8xznAGy4HcY/800x400"
        title: null
    },
    type: "image"
}
```

We can keep it that way and add extra data when the image is a `dotAsset` like this:

```
{
    attrs: {
        data: {...} || null,
        alt: null
        src: "https://source.unsplash.com/8xznAGy4HcY/800x400"
        title: null
    },
    type: "image"
}
```

We set to `null` when is just a regular HTML image.

### Angular Component

We have `dotcms-image-block` for render this images, but I think we don't need this anymore, we can use a plain `<img>` but I let the developer determinate this.

### Drag and Drop

This will remain the same, we'll upload the image and create the dotAsset. The rendering might change.

### HTML images

When block editor receives a `<img>` it should parse it and create the block.

### Image properties
Will be a dialog with a form. We might add more fields. [Prototype](https://www.figma.com/proto/xyjX828sx4rbAdjOB06dTG/DotCMS?page-id=310%3A8774&node-id=2854%3A33786&viewport=445%2C-952%2C0.25&scaling=min-zoom&starting-point-node-id=2854%3A33786&show-proto-sidebar=1)

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/751424/186231866-ed4d813f-c92e-4952-b05c-bb138d3594b6.png">

### Acceptance criteria
- Add images / create dotAsset by drag and drop and/or copy and page the image file
- Copy and paste HTML with images should render the image
- Convert a field from WYSIWYG should render images in the content

**Comment by rjvelazco** [comment]
**Bug Report**

Some images are coming with empty attributes:

<img width="1792" alt="bug" src="https://user-images.githubusercontent.com/72418962/191788326-1352da36-236b-4c26-9eee-d40a2d44980d.png">

**More Information**

I think it's related to the `dotImage.vtl` [files](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock/dotImage.vtl)

**Comment by rjvelazco** [comment]
**Update**

It wasn't a bug at all. What happened is that I started a `dotCMS` instance using `full starter`. The initial `JSON` for blogs in `starter` is outdated. Since we changed the `Image Node`, the `object` of that `node` is different.

This only happens with the blogs coming from `starter`. If we create a new blog and use the image `node`, everything works as expected.

**To illustrate:**

**JSON in Starter**

```JSON
{
    "type": "doc",
    "content": [
        {
            "type": "dotImage",
            "attrs": {
                "textAlign": "center",
                "data": {
                    "AUTO_ASSIGN_WORKFLOW": false,
                    "__icon__": "jpegIcon",
                    "archived": false,
                    "asset": "/dA/2a4fb69a-1f79-4bef-be47-20dec8669c78/asset/isalnds-french-polynesia.jpeg",
                    "assetContentAsset": "2a4fb69a-1f79-4bef-be47-20dec8669c78/asset",
                    "assetVersion": "/dA/8d429bc7-8b44-49fb-9e3b-8f1689a64480/asset/isalnds-french-polynesia.jpeg",
                    "baseType": "DOTASSET",
                    "contentType": "PDF",
                    "extension": "jpeg",
                    "folder": "SYSTEM_FOLDER",
                    "hasLiveVersion": true,
                    "hasTitleImage": true,
                    "host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
                    "hostName": "demo.dotcms.com",
                    "identifier": "2a4fb69a-1f79-4bef-be47-20dec8669c78",
                    "inode": "8d429bc7-8b44-49fb-9e3b-8f1689a64480",
                    "isContentlet": true,
                    "languageId": 1,
                    "live": true,
                    "locked": false,
                    "mimeType": "image/jpeg",
                    "modDate": 1649794690727,
                    "modUser": "dotcms.org.1",
                    "modUserName": "Admin User",
                    "name": "isalnds-french-polynesia.jpeg",
                    "owner": "dotcms.org.1",
                    "path": "/content.8d429bc7-8b44-49fb-9e3b-8f1689a64480",
                    "publishDate": 1649794690727,
                    "size": 102816,
                    "sortOrder": 0,
                    "stInode": "657897dfb36ef211ebfb4128de818787",
                    "statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
                    "title": "isalnds-french-polynesia.jpeg",
                    "titleImage": "asset",
                    "type": "dotasset",
                    "url": "/content.8d429bc7-8b44-49fb-9e3b-8f1689a64480",
                    "working": true
                },
                "href": null
            }
        }
    ]
}
```

**New JSON**

```JSON
{
    "type": "doc",
    "content": [
        {
            "type": "dotImage",
            "attrs": {
                "textAlign": "left",
                "src": "/dA/6b3f8de01f13cb117f9e849dd9a68857/asset/countOddPentafib.png",
                "alt": "image.png",
                "title": "countOddPentafib.png",
                "style": null,
                "href": null,
                "data": {
                    "AUTO_ASSIGN_WORKFLOW": false,
                    "__icon__": "pngIcon",
                    "archived": false,
                    "asset": "/dA/6b3f8de01f13cb117f9e849dd9a68857/asset/countOddPentafib.png",
                    "assetContentAsset": "6b3f8de01f13cb117f9e849dd9a68857/asset",
                    "assetVersion": "/dA/d27bf9d4-727e-4980-844f-e85132369c44/asset/countOddPentafib.png",
                    "baseType": "DOTASSET",
                    "contentType": "dotAsset",
                    "extension": "png",
                    "folder": "SYSTEM_FOLDER",
                    "hasLiveVersion": true,
                    "hasTitleImage": true,
                    "host": "SYSTEM_HOST",
                    "hostName": "System Host",
                    "identifier": "6b3f8de01f13cb117f9e849dd9a68857",
                    "inode": "d27bf9d4-727e-4980-844f-e85132369c44",
                    "isContentlet": true,
                    "languageId": 1,
                    "live": true,
                    "locked": false,
                    "mimeType": "image/png",
                    "modDate": "2022-09-22T16:13:56.103+00:00",
                    "modUser": "dotcms.org.1",
                    "modUserName": "Admin User",
                    "name": "countOddPentafib.png",
                    "owner": "dotcms.org.1",
                    "path": "/content.d27bf9d4-727e-4980-844f-e85132369c44",
                    "publishDate": "2022-09-22T16:13:56.103+00:00",
                    "size": 59786,
                    "sortOrder": 0,
                    "stInode": "f2d8a1c7-2b77-2081-bcf1-b5348988c08d",
                    "statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
                    "title": "countOddPentafib.png",
                    "titleImage": "asset",
                    "type": "dotasset",
                    "url": "/content.d27bf9d4-727e-4980-844f-e85132369c44",
                    "variantId": "DEFAULT",
                    "working": true
                }
            }
        }
    ]
}
```

As you can see, we are missing the `src, alt, title` attributes. That's why the images are rendered `empty`.

**What do we have to do?**

We must update the `JSON` data of the blogs in the `dotCMS starter` using the new node image.

**Comment by rjvelazco** [comment]
After talking to @fmontes, I realized we should support both `json formats` because the block editor has already been used in customer projects.

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/199106383-ec123d1d-4c6a-49a0-9c1c-303ac9373c51.mp4

**Comment by rjvelazco** [comment]
> Kapture.2022-10-31.at.14.39.10.mp4

1. The position of the form should already be resolved after updating the `dotcms-block-editor.js` in this PR: https://github.com/dotCMS/core/pull/23274

https://user-images.githubusercontent.com/72418962/199143948-ef484146-e037-4bed-b055-e8dc9ae8ecd7.mov

Docker Image: `22.11_dc7d7bcd_SNAPSHOT`

2. I'll take a look at the `bubble menu`.

**Comment by fmontes** [comment]
QA in the update done.

1. Start a 23.09 on docker
2. Create a block editor field
3. Add images by drag and drop
4. Upgrade to 22.11
5. Make sure the image shows in the BE

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.09 upgraded to 22.11 // Docker // macOS 13.0 // FF v106.0.3
