### ISSUE TITLE
Add relationship is broken in many to one relationship

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#22840]
**Describe the bug**
Trying to add a new relationship to `many to one` relationship is failing.

**To Reproduce**

1. Crea a new `contenttype` with a `many to one` relationship field.
2. Create a new `contentlet` for that `contenttype`.
3. Try to add a `new relationship`.
4. See error.

**Expected behavior**
The relationship should be added normally.

**Screenshot**

https://user-images.githubusercontent.com/72418962/186279265-88239194-0cae-4953-869f-d9f7bffa56d8.mov

**Comment by rjvelazco** [comment]
PR: #22841

**Comment by jcastro-dotcms** [comment]
**IQA Passed**

## Test Scenario -- with the Empty Starter:
1. Create a new Content Type named `Related CT` with a simple Title field.
2. Create a content of such a type.
3. Create a new Content Type named `Test CT` with (1) a simple Title field, and (2) a Relationships field pointing to the previous CT and selecting "Many to one".
4. Create a content of type `Test CT`, and relate the content of type `Related CT` created initially.
5. The Relationships field gets populated correctly now.

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now it is working as expected. 

Tested on release-22.09 // Docker // FF

**Comment by erickgonzalez** [comment]
This was broken by this one https://github.com/dotCMS/core/issues/22323
