### ISSUE TITLE
Clicking crumbtrail targets "undefined" window

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22843]
When a user clicks the crumbtrail at the top of the dotCMS admin screens, it loads the screen in a new tab.  If you click the crumbtrail in that new tab, it works as expected.

![bad-target](https://user-images.githubusercontent.com/934364/186438284-fc8d0fc8-4bfa-4b85-ae3b-41bad07c5774.gif)

<img width="884" alt="Screen Shot 2022-08-24 at 9 50 11 AM" src="https://user-images.githubusercontent.com/934364/186435721-03573f56-3874-4dcb-8faf-2082b7104d9b.png">

**Comment by alfredo-dotcms** [comment]
https://github.com/dotCMS/core/pull/22948/files

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.10_e9a89d0a_SNAPSHOT // Docker // macOS 12.6 FF 105
