### ISSUE TITLE
Catch Throwable in PublisherJobQueue

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22850]
Every once in awhile something is killing our `PublisherJobQueue` stateful job in Quartz.  When this happens, we do not see anything in the logs and the job just stops and never restarts.  While we catch `Exception`, I think we should catch `Throwable` exceptions to prevent the job from dying.

**Comment by nollymar** [comment]
PR: #22851

**Comment by nollymar** [comment]
**Internal QA:** Passed.

I checked this out using the IDE debugging feature. For this reason, I'm passing QA too
