### ISSUE TITLE
Categories - $contentlet.categories can be slow

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22864]
In #16409 we updated how our `ContentMap` pulls and returns categories when they are called `$contentlet.categoryField`.  This was good because we fixed the fact that categories now respected the user's permissions to view them.  The unfortunate side effect was that because permission lookups are not free, we made the calls to a content's category field slower.  This is especially noticeable when displaying a large list of content with a deep category tree.  

Additionally, in #20684 we removed categories from hibernate but there are a number of places where we are still joining the inode table when pulling a list of categories.

This is true even though we no longer save an inode when we save a category, nor do we select against the inode table when mapping db results to the Category object

**Comment by wezell** [comment]
Was missed in #20684

**Comment by wezell** [comment]
PR #22866

**Comment by erickgonzalez** [comment]
Code changes not in 21.06 LTS

**Comment by jcastro-dotcms** [comment]
## Internal QA: Passed

**Comment by jcastro-dotcms** [comment]
Code changes have already been deployed and tested in a customer environment. No QA is required.

**Comment by fmontes** [comment]
Deployed to customers, QA  not need it.

**Comment by wezell** [comment]
@erickgonzalez I think this will need to be pulled back for LTS 22.10 as well?
