### ISSUE TITLE
api.cors.default config can't override/set through docker compose 

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#22875]
**Describe the bug**
There are different config for api.cors such as `api.cors.default.access-control-max-age` these configs can't override or set through docker compose

**Expected behavior**
These properties should be overridden through docker-compose such as `DOT_API_CORS_DEFAULT_ACCESS-CONTROL-MAX-AGE`

**Comment by erickgonzalez** [comment]
Fixed in https://github.com/dotCMS/core/issues/26391
