### ISSUE TITLE
Block editor: Add a "delete" button to the contentlet block

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22881]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to delete all my blocks easily, for the contentlet block I only can do it with "delete" key in the keyboard which make it extra hard.

**Describe the solution you'd like**
Add a bubble menu like in the other blocks with the “Delete” button to click.

**Acceptance Criteria**
- Add “trash” icon button to the bubble menu of the contentlet
- When the user clicks the button the contentlet block gets deleted

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/22881?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_f1c4cdcc_SNAPSHOT // Docker // macOS 13.0 // FF v106.0.3
