### ISSUE TITLE
Block editor: Not show bubble menu on reorder D&D

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22898]
**Describe the bug**
When you drag and drop to reorder blocks the buble menu shows up because the block get selected automatically.

**To Reproduce**
1. Edit a block editor
2. Add a couple of blocks
3. Reorder blocks by drag and drop

https://user-images.githubusercontent.com/751424/187737989-14fd22a8-4679-4ae4-beae-fe95b063e8a9.mp4

**Expected behavior**
It should not show the bubble menu or select the block.

**Screenshots**

**Acceptance Criteria**
Bubble menu should NOT show when reorder blocks by D&D

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/22898?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_b8dcf115_SNAPSHO // Docker // macOS 13.0 // FF v106.0.3
