### ISSUE TITLE
Block editor: Contentlets inside the block editor not being push published

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22899]
**Describe the bug**
When you push publish a contentlet that have a block editor field with a contentlet in it, the contentlet is not pushed.

**To Reproduce**
1. Create a content type with a block editor
2. Create a contentlet and in the block editor add a contentlet or image block
3. Push publish that contentlet
4. See in the server, the image broken.

**Expected behavior**
It should push the related content inside the block editor.

**Additional context**
- We need to make sure this works with images and contentlets in the block editor.
- Make sure the related content doesn't exist in the destination

**Comment by jdotcms** [comment]
The StoryBlockAPI has a method called getDependencies, that is useful to achieve which contentlets to PP

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/22899?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by rjvelazco** [comment]
Tested on Docker: `22.11_85a28087_SNAPSHOT`
