### ISSUE TITLE
Block Editor: Add UI to configure block editor field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22908]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to control which types of contentlets and assets blocks can be added in the block editor.

Currently, I can use field variables to do this, but it is not a very straightforward process, it required to go and read the docs, and it can get confusing occasionally.

### Describe the solution you'd like

This is a two part: content type field property and the block editor.

#### Field Properties

We are still going to use field variables to do this, but we're going to put a nice UI in front of that so they user can do all this by just clicking.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/751424/188019684-9e008ffe-9bf0-4d7d-96a9-a46dd2857464.png">

[Figma Prototype](https://www.figma.com/proto/1pZBoBlMAI8xYFFIbbj5Mg/dotCMS?page-id=61%3A1123&node-id=61%3A1559&viewport=-470%2C573%2C0.5&scaling=min-zoom&starting-point-node-id=61%3A1559)

### Acceptance criteria
- User can edit a block field and see a new tab "Settings"
- Specific settings TBD

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/22908?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by fmontes** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/751424/205969824-1c8c2471-ecd2-46d5-a98d-5f85dc22fa54.png">

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/23515

**Comment by rjvelazco** [comment]
### Note For QA

The Allowed Assets options are commented out (In the code) because they have not yet been implemented in the block editor. https://github.com/dotcms/core/issues/22928#issuecomment-1291152223

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: 23.01_ca54c27a_SNAPSHOT

As @rjvelazco stated in his previous comment, based on Freddy's screenshot, only the first option will be displayed for now. And that field will hold the different components that can be added to a Block Editor field, which is working as expected.

**Comment by bryanboza** [comment]
We need some work here: 

https://user-images.githubusercontent.com/2641437/211050093-e3e1ef05-0104-4abd-a64b-2d3856647464.mov

**Comment by bryanboza** [comment]
@rjvelazco 
Since the card is assigned to the release and the functionality is not like the description, the `Needs Work` label is needed because the cards require to be tested more than once by the QA department and this require an extra effort

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.01_2cd19f13_SNAPSHOT** // Docker // macOS 13.0 // FF 108.0.2

1. Paragraph can still be seeing even thought it was not sleeted on the allowed blocks from settings
![Screenshot 2023-01-09 at 1 31 22 PM](https://user-images.githubusercontent.com/110418590/211392634-afde41e6-4ae6-4639-87ef-1ade059391ee.png)

2. Please remove quotes from the word Paragraph on the selector drop down
![Screenshot 2023-01-09 at 1 30 28 PM](https://user-images.githubusercontent.com/110418590/211392903-22256d0b-6497-412f-ba75-ebda53269342.png)

**Comment by jcastro-dotcms** [comment]
@josemejias07 the `Paragraph` option will always be present in the Story Block field by default. Unfortunately, (1) we forgot to mention that in the ticket's description, and (2) we need to take it out of the list of values for the `Allowed Blocks` field.

As discussed with @fmontes , we're going to create a separate ticket to handle that. This situation is not a blocker, so we can move on.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_fe436a1d_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.2

**Comment by bryanboza** [comment]
We still needing some work here... Seems we are not totally filtering the kind of types that we are allowing to add in that field 

https://user-images.githubusercontent.com/2641437/211414361-6e147077-65e7-4273-9cfe-b9eca0284639.mov

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF
