### ISSUE TITLE
Block Editor: Add char count information

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22904]
**Is your feature request related to a problem? Please describe.**
As a content author I want to know how long is the content I'm creating, this can help to optimize my content for SEO and improve performance.

**Describe the solution you'd like**
We can use the existing extension: https://tiptap.dev/api/extensions/character-count

**Describe alternatives you've considered**
N/A

**Additional context**
- How do we count contentlets and images?
- Where do we show this?
- Should we have a field var to enable and disable?

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/23198

**Comment by rjvelazco** [comment]
### Needs Doc

We add two new variables for the Block Editor Field

- `charLimit` (number): To set a limit on the number of chars. This is only visual, the user can continue typing even if it exceeds the limit.

| Without `charLimit`  |  `charLimit = 5000` |   
|---|---|
| <img width="284" alt="without-charLimit" src="https://user-images.githubusercontent.com/72418962/197844054-f66b395f-ff72-4c79-a684-234205f565b6.png"> | <img width="396" alt="charLimit" src="https://user-images.githubusercontent.com/72418962/197843904-87b5e0b0-c940-498c-9b8c-a68595cebf49.png">|  

- `displayCountBar` (boolean): Control whether to show the counts bar (which defaults to true if not set).

| `displayCountBar = true`  |  `displayCountBar = false` |   
|---|---|
| <img width="281" alt="Count-Bar" src="https://user-images.githubusercontent.com/72418962/197844984-5eb991f8-8f4b-46e4-822b-7da60d281b69.png"> | <img width="239" alt="No-Count-Bar" src="https://user-images.githubusercontent.com/72418962/197845028-ce83857d-4fe4-468c-b46a-4895b30fc2ff.png"> |

**Comment by fmontes** [comment]
Not showing in the docker image for 22.11, maybe we didn't built the JavaScript? @rjvelazco

**Comment by rjvelazco** [comment]
> Not showing in the docker image for 22.11, maybe we didn't built the JavaScript? @rjvelazco

Oh, you are right! It has to be built it manually. Here is a PR: #23274

**Comment by rjvelazco** [comment]
It's now working in Docker Image: `22.11_dc7d7bcd_SNAPSHOT`

https://user-images.githubusercontent.com/72418962/199144196-2c5b1b1c-839f-4eee-9ecc-71dd4eff8061.mov

**Comment by fmontes** [comment]
For QA, the `charLimit` act as a warning and will not prevent the content to be saved.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_b8dcf115_SNAPSHOT // Docker // macOS 13.0 // FF v106.0.3
