### ISSUE TITLE
Allow users to edit the fields labels in the system fields for any content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22901]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to change the labels of the content types fields to make it more friendly for my content creators.

I know I can change it for custom field, but system fields are limited and some of these fields are presented to the content creators.

**Describe the solution you'd like**
Let's allow the user to change the labels from the UI.

**Describe alternatives you've considered**
Tried to use `readOnly` property from the fields, but after some talking we decided to go all in.

**Additional context**
We have to test as much as possible this because we're uncertain if the endpoints will support this label changes for everything.

**Acceptance Criteria**
Allow users to edit all the system fields labels in any content type

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_c6c88d20_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1
