### ISSUE TITLE
Block Editor: White list Assets content types

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22928]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to control which content types can be added to the editor from the "Assets" item.

### Describe the solution you'd like
Using field variables, users can be white to list the blocks for the Assets.

The users should be able to add a `allowedAssets` field variable to white list the blocks.

### Describe alternatives you've considered
N/A

### Additional context
We already [did this](https://github.com/dotCMS/core/issues/22164) for contentlets with the var `allowedBlocks`.

### Acceptance criteria
- User should be able to add `allowedAssets` and the value a coma-separated block variables to white list them
- In the suggestion, user should only see the white list blocks under "Assets"
- If no variable is set, we show all the dotAseets
- User can have dotAssets and regular contentlets in this list because they might have contentlets that represent assets for them

**Comment by jdotcms** [comment]
I think this will be storage as a content type - field variable

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/22928?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by fmontes** [comment]
We decided to go another route.
