### ISSUE TITLE
Workflow API unable to archive contentlet

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#22921]
### Describe the bug
The user is unable to archive content through workflow API.
Related Ticket: https://dotcms.zendesk.com/agent/tickets/108331

### To Reproduce
1. Create a content and only save it.
2. Call the workflow API.
3. Check the response.
```{"message": "Can't change state of checked out content or where inode is not set. Use Search or Find then use method"}```

### Expected behavior
Contentlet must be archived

```
curl --location --request PUT 'https://demo.dotcms.com/api/v1/workflow/actions/fire' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGlhNmVhMzIzMC02YmE4LTQ3ZjEtOGM3OC0xMGE3ZTIyNzAwOTAiLCJ4bW9kIjoxNjYyMDc3MDY0MDAwLCJuYmYiOjE2NjIwNzcwNjQsImlzcyI6IjVjMjMwN2E0MjciLCJleHAiOjE2NjI5NDEwNjQsImlhdCI6MTY2MjA3NzA2NCwianRpIjoiYWMwMzU2MmItZjdiNS00OTkzLTg5NDUtOTE0YTRkYTIyOTExIn0.MjCNu8JLC6iFW5UNrbmRlapnRxLcqesYiTtkB7HBAss' \
--header 'Content-Type: application/json' \
--data-raw '{
    "actionName": "Archive",
    "contentlet": {
        "identifier": "e6dbb53e9f107d3633ef8329bfea0ce4"
    }
}'
```
Note: Workflow API is working fine for other actions like publish.

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1)

**Comment by erickgonzalez** [comment]
![Screenshot 2023-11-09 at 3 59 41 PM](https://github.com/dotCMS/core/assets/5278970/5b545c7f-38d4-4a88-ae82-48242f0e54b3)

Content Archived successfully and got 200 from the endpoint.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
