### ISSUE TITLE
Custom "Date and Time" field display different date in Detail Page and List View

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#22945]
### Describe the bug
Custom "Date and Time" field display different date in Detail Page and List View
Related Ticket: https://dotcms.zendesk.com/agent/tickets/108378
### To Reproduce
1. log in to [Demo Site](https://demo.dotcms.com/dotAdmin/#/public/login?r=1655383397360).
2. Create a new content type with the `Date and Time` field.
3. Set TimeZone to your country's timezone other than UTC from the Configuration portlet.
4. Create a contentlet with `Date and time` `08/09/22 01:00 AM`.
5. Check the date in the search content screen it is showing the previous day's date.

### Expected behavior
The date should be the same in the column and the edit contentlet modal

### Screenshots
![Screenshot from 2022-09-08 15-30-29](https://user-images.githubusercontent.com/103441252/189100496-fe5275b2-ab26-4274-bc88-c1e5e561524c.png)
![Screenshot from 2022-09-08 15-30-43](https://user-images.githubusercontent.com/103441252/189100500-cb475fc1-6306-4209-9d0c-695a7f1a1733.png)

**Comment by fmontes** [comment]
Let's check the response from the API to see if is coming correctly.

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/22945?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by hmoreras** [comment]
the `ContentletAjax.searchContentlets.dwr` is returning the date incorrectly.

**Comment by erickgonzalez** [comment]
Closing in favor of this one https://github.com/dotCMS/core/issues/23128
