### ISSUE TITLE
Unable to relate to new content in a different language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22940]
When you have a content type with a relationship, and you edit a piece of content, we need to be able to relate to new piece of content, but if you try to do this and add a new piece of content in a different language, after save this new content, we are not relating to the original one. 
![image](https://user-images.githubusercontent.com/2641437/188926240-5caa4bc4-abd2-4dc8-8453-22d09dc2913f.png)

FYI: If you try in the same language it is working as expected 

### To Reproduce
- Create two new content types (CT1 // CT2) with just a title field type text
- Add a new relationship filed to CT1 (CT1: parent // CT2: child)
- Add a new pice of content on CT2
- Add a new piece of content in CT1 and relate to the one on CT2
- Now edit the created content, try to relate to a new piece of content (as in the attached image)
- Create a new piece of content in Spanish 
- Bring back to the original content and make sure the content was related (you must to have the new piece of content in the related list)

### Expected behavior
We must to relate the content no matter the language without problems 

### Desktop (please complete the following information):
Tested on release-22.09 // Docker // FF 

### Acceptance criteria
- You should be able to relate to some content in any language

**Comment by nollymar** [comment]
Workaround: The only way to relate the new piece of content is closing the Edit Content modal (from the parent) and opening it again
