### ISSUE TITLE
Language with same name but different country code is sharing same properties file

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#22947]
### Describe the bug
Language with the same name but a different country code is sharing the same properties file.
When I update a language variable in one language, Changes get synchronized with another language that has the same language code but a different country code.

Related Ticket: https://dotcms.zendesk.com/agent/tickets/108376
### To Reproduce
1. log in to [Demo Site](https://demo.dotcms.com/dotAdmin/#/public/login?r=1655383397360).
2. Create a new language with the `en` language code and 'GB' country code.
3. Edit `com.dotcms.repackage.javax.portlet.title.c-Content` variable.
4. Now go to another language that has the same language code but a different country code.
5. Check the value of `com.dotcms.repackage.javax.portlet.title.c-Content`. it is synchronized.

### Expected behavior
Each language must maintain its own language variables.

### Screenshots

![Screenshot from 2022-09-06 21-57-04](https://user-images.githubusercontent.com/103441252/189183343-be9fed82-bb57-4dfd-858f-1fca6d776e61.png)
ages.githubusercontent.com/103441252/189183324-080da55e-accb-4305-a149-c6b21bf178c0.png)
![Screenshot from 2022-09-08 22-04-42](https://user-images.githubusercontent.com/103441252/189183331-621079c6-9e4f-4eaf-a7ba-3b7c6f3fa57e.png)
![Screenshot from 2022-09-08 22-04-27](https://user-images.githubusercontent.com/103441252/189183634-2f16b299-d92c-4465-b9c6-3eb307dbca7f.png)

![Screenshot from 2022-09-08 22-04-57](https://user-images.githubusercontent.com/103441252/189183332-44363ded-3ba9-4a80-9a14-701c45a5a79d.png)

**Comment by erickgonzalez** [comment]
Reproduced in demo (22.10.1) but is a low priority maybe this can be achieved with new language properties.

**Comment by john-thomas-dotcms** [comment]
Will be addressed with #27978
