### ISSUE TITLE
Workflow action improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22955]
Related to card #22756 

We need to return a `404` error instead `500`, when you send a invalid content Id 

Ty this query 
 ```
 PUT http://localhost:8080/api/v1/workflow/actions/fire
 {
    "actionName": "save",
    "comments": "saving content",
    "contentlet": {
      "contentType":"MyType",
      "title": "Content 2",
      "mycats": ["baby", "toddler", "backcountry"], 
      "identifier": "8aba98ce177103c2e81b5b4ab73bb4ad"
    }
}  
```

In case you send an invalid `identifier` value we need to return the 404 error and not the 500 

#### Acceptance Criteria ####
- Need to catch the exception, return the 404 code and the correct error in the message

**Comment by jdotcms** [comment]
This will be fixed by: [PR](https://github.com/dotCMS/core/pull/23065)
