### ISSUE TITLE
Disable submit button after submitting form

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#22951]
### Describe the bug
When a user clicks on submit button to submit a form that button does not disable so If the form takes time to submit meanwhile user thinks the button is not clicked so he clicks again so the form is resubmitted. In slow form submission, the admin receives more than 1 form even 10 forms due to multiple clicks on submit button.

### To Reproduce
Open a form
Fill that form
Click on submit button
Submit button is not disabled while submission

### Expected behavior
Submit button should be disabled while submission but after an error, this should enable again, In case of success submission page redirects to thank you page so the team can decide whether submit button would enabled after success or not.

### Acceptance Criteria
- Users should not be able to submit the form more than once

Customer Ticket: https://dotcms.zendesk.com/agent/tickets/108371

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/22951?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/22972

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.10_e9a89d0a_SNAPSHOT // Docker // macOS 12.6 FF v105 
![Untitled](https://user-images.githubusercontent.com/110418590/192637467-8e387c3f-2426-4649-af22-60a5b039f20d.gif)

**Comment by erickgonzalez** [comment]
Check 21.06 LTS.
