### ISSUE TITLE
UI - Favorite Page: highlight Star icon on CREATE page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#22963]
As a user once that a new Favorite Page is **created** the Star icon needs to be highlighted to show that there's a contentlet created

![image](https://user-images.githubusercontent.com/37185433/189765865-66dcaafa-d315-42ad-aab9-b8e59ffc426e.png)

### Acceptance criteria
- When created a new favorite page the Star icon needs to be highlighted
![image](https://user-images.githubusercontent.com/37185433/193340420-eb5cc396-10a3-4da3-9b3f-35c504948678.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23090/files

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/23135
