### ISSUE TITLE
Update Empty Starter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22967]
We need to update the empty starter

- [x] delete the `/application` folder as we don't need the file based system container any longer
- [x] remove the calendar event and the calendar based categories
- [x] Rename "Page Asset" to "Page"
- [x] Remove all optional fields from the host content type
- [x] Remove "Home" Navigation
- [x] Change webpagecontent.body to the block editor
- [x] Add new dotAsset types
   - [x] Image (new type, accepts image/*)
   - [x] Video (new type, accepts video/*)

### Left Nav
```
Getting Started
Site Manager
   Browser
   Pages (Custom tool, pulls PageAsset Basetype)
   Containers
   Templates
   Vanity URLs
Content
   Search All
Digital Assets
   Images (Custom tool)
   Videos (Custom tool)
   Files (Custom tool, pulls dotAssets && fileAssets)
Schema
   Content Types
   Categories
   Tags
   Workflows
   Language
Developers
   Query Tool
   GraphQL
   Site Search
   ES Search
   API Playground
   Plugins
System
   Sites
   Rules
   Apps
   Users
   Roles & Tools
   Maintenance
   Configuration
```

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/22967?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by hmoreras** [comment]
New starter https://repo.dotcms.com/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/com/dotcms/starter/empty_20221004

**Comment by fmontes** [comment]
One thing I have noticed in using the empty starter is that the fileAsset.fileName field is marked as read only, and users are not allowed to change file names from the UI.   We need to make sure that the fileName field is not marked as read only.

We need to run this before we create the `starter.zip`
```
 update field set read_only=false from structure where field.velocity_var_name='fileName' and structure_inode = structure.inode and structure.structuretype=2;
```

![Screen Shot 2022-10-05 at 2 04 15 PM](https://user-images.githubusercontent.com/934364/194130453-1add0ac7-99c0-4ca3-8e57-8ac3902d65ed.png)

**Comment by hmoreras** [comment]
feedback done under the same version, https://repo.dotcms.com/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/com/dotcms/starter/empty_20221004

**Comment by josemejias07** [comment]
**QA Feedback** on 22.10_520c98f4_SNAPSHOT // Docker // macOS 12.6 FF v105 Empty Starter

Added contentlets **Image** and **Video** are lacking of a description on the content type portlet

![Screen Shot 2022-10-10 at 2 45 10 PM](https://user-images.githubusercontent.com/110418590/194949699-7da93d0f-c5e4-4db8-b576-629c2b1f6bef.png)

**Comment by hmoreras** [comment]
Descriptions to be updated. 

- Image: Media image file content
- Video: Media video file content
- Content (Generic): Basic default web page content
- Favorite Page: Store user's favorite page

**Comment by hmoreras** [comment]
Reference updated with content type descriptions: 
https://repo.dotcms.com/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/com/dotcms/starter/empty_20221010
PR: https://github.com/dotCMS/core/pull/23136

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.10_f5f5ec65_SNAPSHOT // Docker // macOS 12.6 FF v105 **Empty Starter**

Thank you for adding the additional descriptions @hmoreras

**Comment by hmoreras** [comment]
@jcastro-dotcms , use this PR, https://github.com/dotCMS/core/pull/23174 to update the broken test. thanks.
