### ISSUE TITLE
UI - Favorite Page: unhighlight Star icon on DELETE page

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#22965]
As a user once that a Favorite Page is deleted, the Star icon needs to be unhighlighted to show that there's no favorite page

### Acceptance criteria
- When deleted a favorite page the Star icon needs to be unhighlighted

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_511ed969_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
