### ISSUE TITLE
UI - Favorite Page: Edit Page --> Favorite Page dialog = Remove button 

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#22964]
### Parent issue
#22343 

As a user once that a new Favorite Page is created, I need to be able to remove it from the Favorite Page dialog

![image](https://user-images.githubusercontent.com/37185433/205178340-c7bb6225-6c7c-43b7-a927-8cef3471102a.png)

### Acceptance criteria
- This applies only on the Edit Page portlet, on the dialog that opens when you click the STAR icon
- the "Delete" button needs to be placed on the bottom left section of the dialog
- If action is Create, then "Delete" button needs to be deactivated
- If action is Edit, then "Delete" button needs to be Activated
- If "Delete" button is clicked data (contentlet) needs to be removed from the DB

**Comment by renofathoni23** [comment]
Good morning. I am interested in solving this issue, can I work on it? @alfredo-dotcms

**Comment by alfredo-dotcms** [comment]
Hi @renofathoni23 thank you for the interest, I’m working on it as we speak, coming in the upcoming version of DotCMS

**Comment by fabrizzio-dotCMS** [comment]
Save a Favorite Page. Come back to it using the star icon and make a change then hit save. 
You'll get a bad request responsee like this: 
![Screen Shot 2022-12-22 at 17 18 44](https://user-images.githubusercontent.com/37148755/209241620-9510f09f-1622-4347-833c-407494dab056.png)

**Comment by alfredo-dotcms** [comment]
@fabrizzio-dotCMS not an issue, cuz once this task https://github.com/dotcms/core/issues/23061 gets done, that error won't be happening/showing

**Comment by nollymar** [comment]
**Internal QA:** Needs work

I didn't notice the issue reported by @fabrizzio-dotCMS , however The STAR icon keeps highlighted for the page when the favorite page is archived. Archived pieces of content should be filtered out

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24337/files

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_03732ac4_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Archiving a favorites page breaks the menu and its no longer usable 

https://user-images.githubusercontent.com/129882031/230930324-b20352d0-1dab-4a6f-b6fb-d43dcaa532bf.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_03732ac4_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Created a new card for the above issue #24603
