### ISSUE TITLE
KeyValue Sorting Capabilities are broken 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#22975]
### Describe the bug
If you add elements to a key value then save 
then reorder them via drag and drop. Then save again. The new version doesn't get saved respecting the new order of the elements.

The bug is reproducible in master and demo. 

### To Reproduce
1. Create a CT with a KeyValue Field 
2. Create an instance of that CT.  And fill the key-value field with keys like 1,2,3 (The values are not important on this test).
3. Save the content. And Close the dialog
4. Re-Open the dialog. Then change the order of the elements on the KeyValue Via Drag-and-drop. Hit Save again. 
5. Close the dialog again. And Re-Open.
6.  Verify the new order established in step 4. Is lost 

### Expected behavior
You should be able to change the order of the elements on the UI save and recover the pre-established order. 

### Screenshots
I believe the bug originated due to a change introduced in the class **JSONObject**

Where the inner map implementation was changed from LinkedHashMap into a plain HashMap

![Screen Shot 2022-09-13 at 16 49 27](https://user-images.githubusercontent.com/37148755/190024330-22f7a369-f5c7-459a-a2c4-97e9ec7d619e.png)

### Acceptance criteria
- We should be able to manipulate the order of the elements added to the KeyValue

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/22997

**Comment by nollymar** [comment]
**Internal QA:** Passed

I was able to sort key/values once and again without issues

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.10_a3659b56_SNAPSHOT // Docker // macOS 12.6 FF v105

Sorting animation is not looking as intended on all browsers. FireFox animation is looking different from Chrome's.

See below
**FF**
![Untitled](https://user-images.githubusercontent.com/110418590/192863325-d09e28af-68b9-42fc-ac51-48ec00d7e2fe.gif)


**Chrome**
![Untitled2](https://user-images.githubusercontent.com/110418590/192863363-836a6015-8c1d-4e05-b6db-ae99f25b226c.gif)

**Comment by alfredo-dotcms** [comment]
@note to QA: This is using native browser Drag and Drop animation, it's not something we can control with current implementation.
