### ISSUE TITLE
Experiment Scheduling

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22989]
### User Story
As a user, I need to set up the start and end dates to schedule and run an experiment.

### Acceptance Criteria

- The user can select a start date and time and an end date and time for the experiment.
- The dates and times selected are saved and displayed correctly.
- The time needs to be in 30-minute steps
- Allow clear dates

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Designs
<img width="672" alt="Screenshot 2023-04-17 at 5 26 24 PM" src="https://user-images.githubusercontent.com/1909643/232615662-b1c74826-6e58-4c2d-8d9c-a9334f009aa6.png">

<img width="724" alt="Screenshot 2023-04-17 at 5 26 43 PM" src="https://user-images.githubusercontent.com/1909643/232615656-f69688a5-122c-429b-8f20-9ce94bf7b321.png">
<img width="701" alt="Screenshot 2023-04-17 at 5 26 30 PM" src="https://user-images.githubusercontent.com/1909643/232615660-d724688b-31b9-42c1-a647-e8d8b3cbb2e8.png">

**Comment by oidacra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22989?planning-poker) with Zenhub @alfredo-dotcms @fmontes @hmoreras @rjvelazco

**Comment by oidacra** [comment]
@freddyucv @dsilvam please add endpoint

**Comment by freddyucv** [comment]
**Needs Works:** Now we are setting day, hour and minutes to the START/STOP scheduling, we don't need to set hour and minutes there

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/24050

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/24050

**Comment by freddyucv** [comment]
**Pass Internal QA**: we have a bug when try to remove the start and end date to a Experiment, but we are going to creare a new issue for it because it is a backend issue

**Comment by freddyucv** [comment]
**Needs work:** We should not allow to set end date if we don't have a start date

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24213

**Comment by dsilvam** [comment]
Passed Internal QA: Able to remove start and end dates from scheduling after initially set.

**Comment by bryanboza** [comment]
Tested on release-23.05 and we need some work here: 

- We are not validating you set both values start and end dates, you can start an experiment without any of those, then the experiment never will start or never will end. 
- We need to make the validation at FE and endpoint level too 
- We need postman test for the endpoint 
- In case the start date is after the end date, we are showing an error at UI level but we need to catch this exception and print just a line error in the log, this because right now we are printing to many lines of noisy in the log. 
Here the stack trace: https://gist.github.com/bryanboza/613e1ba6eaf4d08f263cd60381025853

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24649

**Comment by hmoreras** [comment]
new Rules added. 

1. End date can't be set in the past never.
2. When the start date is set, the end date minimum start time, should be +30 min.
3. If the start date value is lower that the end date, the end date should be cleared

PR: https://github.com/dotCMS/core/pull/24711

**Comment by dsilvam** [comment]
If you set a future date with same hours at the start date then you can edit the future date and make it the same as the start date, which fails upon trying to save. 

![Image](https://user-images.githubusercontent.com/1576794/234338158-f946e4cc-9c4d-4e8c-87c1-900598096c44.png)

**Comment by dsilvam** [comment]
Passed Internal QA: This is respecting now the minimun length for the Experiment, which is 90 days by default.

**Comment by bryanboza** [comment]
Fixed, now we are disabling all the invalid options once that you set the start date. Also tested at API level and we are returning the correct error codes and messages.
