### ISSUE TITLE
[UI] Change Traffic Load of experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22988]
## Is your feature request related to a problem? Please describe.
As a user, I want setup the Traffic Load of the experiment.

Call when clicking Setup
![Screenshot 2022-12-20 at 11.06.30 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/87c7cfbc-5275-4413-a22e-732b6018bb54)

Sidebar
![Screenshot 2022-12-20 at 11.06.44 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/179d8f95-398e-4007-8063-12a4ab84d121)
## Describe the solution you'd like
Reuse the sidebar to show the slide.

## Acceptance criteria
- Change using a slide, the Traffic Load of the experiment
- Show the change in the card.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/24053

**Comment by bryanboza** [comment]
This notification needs some styling help 

![Image](https://user-images.githubusercontent.com/2641437/223276564-c89c2581-8cf3-42fa-9280-676005aa4765.png)

**Comment by hmoreras** [comment]
QA notification margin fix PR: https://github.com/dotCMS/core/pull/24412

**Comment by dsilvam** [comment]
Passed Internal QA: styling fixed. 



![Image](https://user-images.githubusercontent.com/1576794/226657396-08926213-dbb4-4884-967c-468e4dab6649.png)

**Comment by bryanboza** [comment]
In case you try to set this value = 0, we are showing a success notification, but this value must be > 0. We need to show a kind of WARN notification or maybe just disable the button, and avoid set this to 0. 

https://user-images.githubusercontent.com/2641437/231282769-6bf708bc-2af8-4c7b-b89b-cd4cf1a4d303.mov

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24662

**Comment by dsilvam** [comment]
Passed Internal QA: Slider starting at 1. API was already accepting values from 1 to 100.
