### ISSUE TITLE
[UI] Run an experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22985]
## Is your feature request related to a problem? Please describe.
[Experiment] - Run an experiment

## Describe the solution you'd like
Add a button to run an experiment with variations and goal configurated. Update the status of the experiment.

Additional:
Implement the changes from Product Design; these changes include
- Resize header (and refractory to add a tag of status and button for a start/stop experiment)
- Use a tag to show the status of the experiment
- Move the button of Start Experiment to the header
- Use correct colors/sizes/margins for each status tag
- Remove the status component
- Create a component to show details of the experiment

## Describe alternatives you've considered
Button to run the experiment.

![Screenshot 2023-01-20 at 10.30.14 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/715a315c-0f29-4d3b-b4af-fd7e38bbcf92)

## Additional context
N/A

## Acceptance criteria
- Button removed if the experiment doesn't have set variations (more than 1) and a goal already set.
- Run the experiment, and show a dialog with the final information of the experiment (start date, end date, variations, objective).
- Update the status of the experiment.

**Comment by oidacra** [comment]
PR https://github.com/dotCMS/core/pull/23885

**Comment by dsilvam** [comment]
Passed Internal QA according to what was defined in the scope. 
However took note of these two points: 
* The experiment should not be modifiable when it’s already RUNNING or SCHEDULED
* When you start an experiment with a “Scheduling” set by the user, it should go to SCHEDULED status until the job makes it start, instead of RUNNING

**Comment by oidacra** [comment]
The first point, was resolved today with this PR: https://github.com/dotCMS/core/issues/24651 to master.

**Comment by victoralfaro-dotcms** [comment]
No variations nor goal defined:
![image](https://user-images.githubusercontent.com/64026161/232939412-1569e330-db61-4432-97fb-c73df52d3c8e.png)
No goal:
![image](https://user-images.githubusercontent.com/64026161/232939486-84fcc11b-438c-4a7a-bbce-4c5acec58a3f.png)
Variants and Goal defined:
![image](https://user-images.githubusercontent.com/64026161/232939920-e62a4e78-88c9-43a2-b55a-f1d5c2e4b6f2.png)
Running experiment:
![image](https://user-images.githubusercontent.com/64026161/232940040-912441b1-5991-4172-a8e2-5cbea4556ff6.png)

**Comment by bryanboza** [comment]
Fixed, new cards related to the required postman test created here: #24967
