### ISSUE TITLE
"Key" vs "Token" labeling

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#23007]
We use "key" and "token" interchangeably in some places (E.g., using **Settings -> Users -> {User} -> Api Access Keys** which leads to the "Token" modal), though the two aren't quite the same, e.g.:

- https://security.stackexchange.com/a/161953
- https://nordicapis.com/the-difference-between-api-keys-and-api-tokens/

It might be worth firming up the usage at the UI level. The final strings do appear to be tokens, since they have the two periods interspersed that seem to suggest the [header/payload/signature](https://jwt.io/introduction/) structure.

As a possible starting point, the "API Access Keys" element described above appears to be defined in `Language.properties`:

https://github.com/dotCMS/core/blob/5576c53baa8a17ca5140a36f628cf7db48df86fe/dotCMS/src/main/webapp/WEB-INF/messages/Language.properties#L303

https://github.com/dotCMS/core/blob/5576c53baa8a17ca5140a36f628cf7db48df86fe/dotCMS/src/main/webapp/WEB-INF/messages/Language.properties#L308

I found this, also, though I'm less sure of its corresponding element:

https://github.com/dotCMS/core/blob/8dfd881fa4e0fb5c065c15c835b7e3ec0a29f93a/core-web/apps/dotcms-ui/src/app/portlets/dot-starter/dot-starter.component.spec.ts#L40

https://github.com/dotCMS/core/blob/8dfd881fa4e0fb5c065c15c835b7e3ec0a29f93a/core-web/apps/dotcms-ui/src/app/portlets/dot-starter/dot-starter.component.spec.ts#L41

There may be other points where this comes up, not to mention in other languages. (Couldn't say offhand how that distinction plays in, say, French.)

**Comment by jdcmsd** [comment]
Getting the ball rolling with a first PR: https://github.com/dotCMS/core/pull/23008

Let me know if I've done anything askew from the standard approach.

**Comment by fmontes** [comment]
We need to double check if there are more cases.

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/23007?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by bryanboza** [comment]
Fixed, tested on release-22.10 // Docker // FF. 

![Image](https://user-images.githubusercontent.com/2641437/193908478-5aaba065-514b-48db-8228-7ff7c5e52911.png)


Now we are using token everywhere.
