### ISSUE TITLE
Support Variant with URL Map

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23023]
### Is your feature request related to a problem? Please describe.
When we try to render a URLMAP with a specific variant it is not working because the URLMapContent is render with the DEFAULT variant no matter if it had a version in the specific variant.

### Describe the solution you'd like
The contentlet should be render in the specific variant

### Additional context
here the Contentlet is returned with the DEFAULT variant version all the time

https://github.com/dotCMS/core/blob/3283e9732fe28b329cf3fd3633534a76a6f4806d/dotCMS/src/main/java/com/dotmarketing/cms/urlmap/URLMapAPIImpl.java#L63

### Acceptance criteria
- The contentlet should be render in the right version
- The redirect traffic must work with a URL Map
- Integration test

**Comment by freddyucv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23023?planning-poker) with Zenhub @fabrizzio-dotCMS

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and it is working as expected. Tested on release-23.06 // Docker // FF
