### ISSUE TITLE
Modify Favorite Page content type in ContentTypeInitializer

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#23040]
The ContentTypeInitializer implementation needs to be modified to: 

- [x] Rename the Favorite Page content type to `dotFavoritePage`. The same applies for the velocity var name. This operation might require an insert (in case the content type doesn't exist) or an update.

- [x] Make url field unique

**Acceptance Criteria:** 
- [x]  This change should include ITs
- [x]  As a user I should be able to see the `dotFavoritePage` content type in both cases coming from an upgrade or a fresh installation. The original Favorite Page content type should not exist anymore
- [x]  The url field must be unique

**Comment by alfredo-dotcms** [comment]
LGTM
![image](https://user-images.githubusercontent.com/37185433/194615051-5b4247d8-100b-4d48-b799-39fc062def7b.png)

**Comment by josemejias07** [comment]
**QA Feedback** on 22.10_520c98f4_SNAPSHOT // Docker // macOS 12.6 FF v105

Label ' Unique ' should be added to the url field
![Screen Shot 2022-10-10 at 3 20 48 PM](https://user-images.githubusercontent.com/110418590/194954441-cd8aa954-0261-4605-8e3a-ad0b68c04edf.png)


**Note**: Functionality is working as intended

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.10_520c98f4_SNAPSHOT // Docker // macOS 12.6 FF v105

 ' Favorite Page ' should had been renamed to **dotFavoritePage** as requested on the card description. And also please add a description to the field

![Screen Shot 2022-10-10 at 3 29 10 PM](https://user-images.githubusercontent.com/110418590/194955214-7a64a59e-841e-4a30-9353-483445b29635.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.11

We changed the content type name to dotFavoritePage 

![Image](https://user-images.githubusercontent.com/2641437/199309705-ff0b2d9d-1d0e-4152-a6c4-2d15155ad977.png)


and, also we the url field is unique 

![Image](https://user-images.githubusercontent.com/2641437/199309639-d9cb8e14-c4d3-405d-a6d5-1cc09eaed51f.png)
