### ISSUE TITLE
Front end Log viewer Search capabilities

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#23043]
### Describe the bug
This task account for the work required to make the log viewer capable of searching and highlighting keywords entered on the filter box

### Acceptance criteria
Once the log is capable of navigating through the log pages we should be to:

1. Enter text into the search box and highlight any matches in the text currently shown.
2. For a keyword to become a valid searchable candidate it must contain at least 3 chars
3. Every new entry that arrives into the view product of a log update must be processed and highlight any new occurrence
4. once the Keyword is removed the highlight occurrences must be removed
5. Once a keyword is entered and enter key is hit all none matching lines must be removed. In order to accomplish this functionality more efficiently, we should only process a certain number of pages and never the whole log as it wouldn't scale when the log is too large.

**Comment by freddyucv** [comment]
**Needs work**: When you are filter by any and then the log get more lines, the lines lines are show up without any filter

https://user-images.githubusercontent.com/10408015/195661583-d48e9db0-4366-4425-a398-e43a3834126c.mov

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/23177

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_45223903_SNAPSHOT // Docker // macOS 12.6 FF v105
