### ISSUE TITLE
Create Analytic App

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23052]
We need to create a dotAnalytics App that takes at 3 config properties:

1. Client ID - plain text (this is what will segment the data in the data warehouse)
2. Client Secret - secret field
3. Analytics ID - plain text  (used to write to Jitsu)
4. a key/value field for additional properties that if set will be used to override the defaults.
   - Analytic ID Configurator
   - Analytics Write URL
   - Analytics Read URL

We will use the Client ID and Client Secret to request and keep an Auth Token in memory in each server in the cluster.  Auth Tokens are short lived tokens that expire in 1-2 hours.  When they expire (or before, if possible), we will need to request a new auth token.

1. We will need a AppEventListener that (if there is no Jitsu Analytics ID set) will get an auth token and use it to get a Jitsu Analytics ID from the configurator.  We should then store that jitsu Analytics ID in the App for use by other servers in the cluster
2. When requesting data from the data warehouse, we will use the Client Id and Client Secret to request an Auth Token.  This token is stored/cached in server memory and used when querying the data store.  If the token expires, we should request a new token
3. If analytics configuration has been set by environmental variables and a user makes a change to the dotAnalytic config using Apps, we should send a system notification/toast that says: 

> dotAnalytics is configured using environmental variables - any configuration done within the App screen will be ignored.

I would create token service that uses a Caffeine cache with an expiring entry for the auth token (maybe request a new one a minute before it expires).

**Comment by victoralfaro-dotcms** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23052?planning-poker) with Zenhub @dsilvam @freddyucv @oidacra

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23202

**Comment by spbolton** [comment]
Flow for Access Token Request

Is Auth in an unrecoverable error state, e.g. invalid secure secret, missing details
     Return exception, need to direct to configuration page to update security.
Is token in 1 min (configurable) window of expiry and update request thread (should not need a dedicated thread for this just a background job in executor but should not run in parallel) not already running
	yes - spawn thread to update token
			On success
             	Update cached token
			On failure
				If temporary error, e.g. network connection error, recoverable retry max 2 (delay ?) ?
                                If a  permanent error, e.g. secret is wrong report  error notification exception, set status, do not keep retrying block further requests.
		return old token immediately.
    No Expired
		spawn thread to update token if thread not already running
		block for new token ( timeout auth exception, timeout must take into account any retry and delay, and preferably not fully block entire system, maybe add spinner until this timeout )
	No
		return existing token from cache no block. (edite

**Comment by victoralfaro-dotcms** [comment]
One way to IQA this implementation is to locally run the `AnalyticsAPIImplTest` integration test. To do this you have follow this steps:
- Have a dotcms db for tests up and running
- Have ES up and running
- Make the changes to properties files when you usually run ITs locally
- At `it-dotmarketting-config.properties` add the following line:
```
analytics.idp.url=http://localhost:61111/realms/dotcms/protocol/openid-connect/token
```
- Build if you think you have to
- Start the docker compose with the analytics infrastructure services which can be found at https://github.com/dotCMS/internal-infrastructure/blob/initial-analytics/dot-analytics/configurator/deployment/docker-compose/docker-compose-dev.yaml and start the `configurator` quarkus service. For more details read: https://github.com/dotCMS/internal-infrastructure/blob/initial-analytics/README.md
- Run/Debug from the IDE or run the local IT by executing: 
```
./gradlew integrationTest --tests "AnalyticsAPIImplTest" -PdatabaseType=postgres
```
