### ISSUE TITLE
Return Bayesian result including probability that B beats A

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#23050]
Modify experiment endpoint to get and model data from Cube.js "datasource". Identify how the data is modeled from the results of running a Cube.js query and adapt to it to be passed to `BayesianAPI` to determine how the variants are doing in a given experiment.
Cube.js results are currently stored in objects of this class: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/cube/CubeJSResultSet.java

To see how this is invoked we can refer to the following code: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/experiments/business/ExperimentsAPIImpl.java#L818

Acceptance Criteria:
- Start locally the analytics infrastructure (steps to do so can be found in issue: https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641)
- Start dotCMS instance as https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641 indicates it.
- Create an experiment for a page
- Create one variant for that page under the recently created experiment
- Define a REACH_PAGE goal as you want including the variant page
- Access the frontend site, preferably using new sessions (incognito and/or other browsers) and navigate using the variant more than the original option
- Access the `/v1/experiments/<experiment id>/results` and look for the `bayesianResult` element within the response JSON.
- Verify that the suggested option is actually the variant and that the `probabilities` map shows the actual probability for the tested options with, obviously, a greater value in favor of the variant.

**Comment by victoralfaro-dotcms** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23050?planning-poker) with Zenhub @dsilvam @freddyucv @oidacra

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24443

**Comment by freddyucv** [comment]
**Need Works:**

Right now the response is like this:

```
{
  ...
  "bayesianResult": {
            "differenceData": null,
            "distributionPdfs": null,
            "inFavorOf": "B",
            "quantiles": null,
            "suggested": "DEFAULT",
            "value": 0.10000000000000006
        },
  ...
}
```

-  it need to remove some attributes from the current Response like: differenceData, distributionPdfs, inFavorOf, quantiles
- Show only two decimal places in the value attribute.
- Change suggested by suggestedWinner, Also when the is not any winner right now we are showing the value of _TIE_, we should change it by just TIE.

**Comment by freddyucv** [comment]
Pass Internal QA: Right now when the Bayesian is greater than 51% we are setting a suggested Winner.

We need to discuss if we need to set a value to be like a bounder, for Example we only are going to set a suggested Winner if the Bayesian is greater than 95% o any other value, also if we are going to use this value we need to discuss if this value is going to be set by Experiment or not.

**Comment by bryanboza** [comment]
Fixed, now we have this value in the table of results. 

Tested on master // Docker // FF
