### ISSUE TITLE
Set language in docker image to C.UTF8

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23056]
Our docker image is set to using a non UTF8 language as its default.  The result of this is that we cannot store files that contain extended characters in their names.  The fix for this is to set the environmental variable `lang` in our docker image to `C.UTF8`.  You can see this work by adding the environmental variable to a docker config:
```
    environment:
      LANG: 'C.UTF-8'
```
We need to add this environmental variable by default to our docker image

To test example create a PDF file called `July groups – net adjustment results (145 KB PDF), updated May 2019.pdf` and try to upload it into a dockerized dotCMS.  This will fail with a message like:

```
[28/09/22 21:04:37:340 UTC] ERROR temp.TempFileResource: Malformed input or input contains unmappable characters: /data/shared/assets/tmp_upload/temp_a547a9e844/July groups Ã¢Â€Â" net adjustment results (145 KB PDF), updated May 2019.pdf
com.dotmarketing.exception.DotRuntimeException: Malformed input or input contains unmappable characters: /data/shared/assets/tmp_upload/temp_a547a9e844/July groups Ã¢Â€Â" net adjustment results (145 KB PDF), updated May 2019.pdf
at com.dotcms.rest.api.v1.temp.TempFileAPI.createTempFile(TempFileAPI.java:185) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.rest.api.v1.temp.TempFileResource.lambda$0(TempFileResource.java:171) ~[dotcms_22.03.2_999999.jar:?]
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/shared/assets/tmp_upload/temp_a547a9e844/July groups Ã¢Â€Â" net adjustment results (145 KB PDF), updated May 2019.pdf
at com.dotcms.rest.api.v1.temp.TempFileAPI.createTempFile(TempFileAPI.java:172) ~[dotcms_22.03.2_999999.jar:?]
... 7 more
```
 

export LANG=C.UTF8

**Comment by spbolton** [comment]
@wezell  Looks like there is an issue causing this.


In windows startup.bat we have the following
set JAVA_OPTS=%JAVA_OPTS% -Djava.awt.headless=true -Xverify:none -Dfile.encoding=UTF8 -server -XX:+DisableExplicitGC -Dsun.jnu.encoding=UTF-8

but in startup.sh we have this, it is missing the sun.jnu.encoding property that sets the filename encoding.   If this was resolved it would not require the underlying system encoding to be set.

JAVA_OPTS="$JAVA_OPTS -Djava.awt.headless=true -Xverify:none -Dfile.encoding=UTF8 -server -XX:+DisableExplicitGC"

**Comment by yolabingo** [comment]
@spbolton `JAVA_OPTS`  is appended to on several lines, but it looks to me like this property is present. Is this correct?
```
JAVA_OPTS="$JAVA_OPTS -Djava.awt.headless=true -Xverify:none -Dfile.encoding=UTF8 -server -XX:+DisableExplicitGC"
...
# Set encoding
JAVA_OPTS="$JAVA_OPTS -Dsun.jnu.encoding=UTF-8"
```
https://github.com/dotCMS/core/blob/master/bin/startup.sh#L62
https://github.com/dotCMS/core/blob/master/bin/startup.sh#L72-L73

**Comment by spbolton** [comment]
Yes unless the line is commented out it should be appending the two sections together so maybe it is already there in this case.   We should probably have the .bat and .sh work the same to prevent confusion.

**Comment by hmoreras** [comment]
No error in the log shown when uploading the file.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.11_16e848e4_SNAPSHOT // Docker // macOS 13.0 // FF v107.0

Files Asset name is still not showing the correct format.
![Screenshot 2022-11-22 at 3 31 55 PM](https://user-images.githubusercontent.com/110418590/203425664-4950507f-b894-4cbc-939a-72a088880016.png)


 21:31:36.681  WARN  font.FileSystemFontProvider - Building on-disk font cache, this may take a while
release_branch-dotcms-1         | 21:31:36.682  WARN  font.FileSystemFontProvider - Finished building on-disk font cache, found 0 fonts
release_branch-dotcms-1         | 21:31:36.682  WARN  font.PDTrueTypeFont - Using fallback font 'LiberationSans' for 'AAAAAF+font00000000292bd08e'

**Comment by jcastro-dotcms** [comment]
As discussed with @yolabingo , the current PR will overwrite very important and necessary changes that are already in place in the `master` branch: https://github.com/dotCMS/core/pull/23229

He kindly provided me with a nicer fix for this issue as well: https://github.com/dotCMS/core/pull/23420/files , which will be implemented instead.

**Comment by fmontes** [comment]
> **Failed QA** - Tested on 22.11_16e848e4_SNAPSHOT // Docker // macOS 13.0 // FF v107.0
> 
> Files Asset name is still not showing the correct format. ![Screenshot 2022-11-22 at 3 31 55 PM](https://user-images.githubusercontent.com/110418590/203425664-4950507f-b894-4cbc-939a-72a088880016.png)
> 
> 21:31:36.681 WARN font.FileSystemFontProvider - Building on-disk font cache, this may take a while release_branch-dotcms-1 | 21:31:36.682 WARN font.FileSystemFontProvider - Finished building on-disk font cache, found 0 fonts release_branch-dotcms-1 | 21:31:36.682 WARN font.PDTrueTypeFont - Using fallback font 'LiberationSans' for 'AAAAAF+font00000000292bd08e'

Hey @josemejias07, please create another ticket for the UI, this ticket was for the error/exception

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_aae089fb_SNAPSHOT // Docker // macOS 13.0 // FF v107.0.1
