### ISSUE TITLE
UI - Favorite Page: Edit Favorite page dialog on DotFavoritePage Listing portlet

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#23061]
As a user I need that when I click the edit button on a DotFavoritePage in the Listing portlet, a dialog needs to open showing the data of the favorite page and it will allow me to edit it

![image](https://user-images.githubusercontent.com/37185433/193062819-855b10c6-9cf5-458a-a557-e4a5f046b6a1.png)

Acceptance criteria
- When a favorite page is clicked a dialog needs to open and load the existing saved data
-  The URL field must be Read only
- if data is modified on the dialog it needs to persist
- the dialog content layout needs to meet the 2 column redesign
![image](https://user-images.githubusercontent.com/37185433/211934241-54962209-5d5f-4500-94ef-b82d0dfbc542.png)

**Comment by wezell** [comment]
Please use the same redesigned 2-column component/screen that we show when adding/editing on in edit mode

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23617

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24336/files

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_2539461f_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
