### ISSUE TITLE
SameSite=strict breaks login; Allow SameSite Cookie property to be overridden 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23072]
In 22.03, we shipped with tomcat set to force the session cookie to `SameSite="strict"`. This has the effect of preventing the session in a SAML based login from persisting across the login process and results in a new session being set up once the user has logged in and the loss of the redirect url that was set in their session.

I believe `SameSite="lax"`will allow SAML redirects to work again.  In any case, we should make the SameSite setting configurable by setting an environmental variable.

**Comment by wezell** [comment]
dupe: #23071

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/23073

**Comment by hmoreras** [comment]
the cookies, now have the "lax" in the "SameSite" property.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.11 // Docker and now this property is in lax, also tested on demo and we don't have value here before this change. 

![Image](https://user-images.githubusercontent.com/2641437/204846043-bba35ce0-c712-44c7-bd63-afecda1f8681.png)
