### ISSUE TITLE
Unable to add categories to bundles 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23078]
We are not allowed to add categories to a bundle in order to push. When you try this, we are not getting errors but the category is not added to the existing bundle. 

FYI: No errors ithe n the log, neither in console 

- Login as an admin 
- Configure your push environment 
- Go to Content Model -- > Categories 
- Select any category and try to add to a bundle 
- Check the bundle and make sure the category was added 

### Expected behavior
We need to be able to add categories to bundles and push without problems 

### Desktop (please complete the following information):
Tested on release-22.10 // Docker // FF 

### Acceptance criteria
- We need to be able to add categories to bundles
- Push Categories

**Comment by erickgonzalez** [comment]
Customer ticket https://dotcms.zendesk.com/agent/tickets/108576
Reproducible in 22.03.2 LTS

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/23078?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms @oidacra

**Comment by freddyucv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Maintenance-61770c654506a300167b30f4/issues/dotCMS/core/23078?planning-poker) with Zenhub @oidacra

**Comment by dsilvam** [comment]
Passed Internal QA: Described steps working as expected. 
Cats are *all* sync'ed, meaning, there's no ability to push only one category, but all of them, so the menu option was updated to reflect this.

**Comment by bryanboza** [comment]
We still having problems to add categories to the bundle

https://user-images.githubusercontent.com/2641437/198695077-fa6cfc7e-fde4-4289-a8b3-2cded5ddc664.mov

Tested on release-22.11 // Docker // FF

**Comment by dsilvam** [comment]
@bryanboza please read the comments before marking the issue as "needs work". there is no way to push only one category, so the selection you're doing on the video doesn't make anything. Read the last comment please.

**Comment by bryanboza** [comment]
@dsilvam yes I know this, but as you can see in the video we are not indicating in the bundle that categories was included, as we do with any other content, we have to list all the content that will be pushed in the bundle.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.11 // Docker // FF

**Comment by erickgonzalez** [comment]
No back portable to 21.06 LTS since DependencyManager changed a lot between 21.06 and 22.12, e.g Manifest.
