### ISSUE TITLE
Add units (seconds) to Page Properties Cache TTL label

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#23074]
Specifying the units as seconds on Page Properties -> Cache TTL in the backend would be nice, something like:
**Cache TTL (seconds):**

screenshot:
<img width="519" alt="Screen Shot 2022-09-30 at 3 16 00 PM" src="https://user-images.githubusercontent.com/628954/193357424-2dd5049a-dcf4-4057-ac2a-92dc473c4b15.png">

**Comment by dsilvam** [comment]
Let's add the change here please: https://github.com/dotCMS/core/blob/96bd74a66f9d882b6214926f36ce406e79887a13/dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPI.java#L55C25-L55C45
