### ISSUE TITLE
Create default list of classes that can be added in the layout manager

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23086]
We need to add a styles.json file in a template theme folder, e.g. `/application/themes/travel/styles.json` that we use to auto-suggest classes for the layout.  If the file is found, read it and use them to suggest classes when the user is typing.

```
{"layoutClasses":["padding-10", "full-width", "bg-blue", "padding-4","col-sm-10"])
```

**Comment by fmontes** [comment]
Closing this since we're redoing template builder.
