### ISSUE TITLE
Login as functionality is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23087]
If you are logged as an admin user, and you try to use the login as functionality this is not working, we are showing an error and you are unable to start the session as another limited user. 

### To Reproduce
- Login as admin
- Try to login as some other specific user 

### Expected behavior
We need to be able to see the session as some other users 

### Screenshots
![image](https://user-images.githubusercontent.com/2641437/193734832-a724cdd6-bd12-4ddc-9a75-706e6c169adc.png)

### Desktop (please complete the following information):
Tested on release-22.10 // Docker // FF

**Comment by wezell** [comment]
This works - I just tested on demo.  Remember, you need to enter your password, not Steve's, e.g. `admin`
