### ISSUE TITLE
[UI] Add new experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23095]
## Is your feature request related to a problem? Please describe.
As a user, we want to create a new experiment.

## Describe the solution you'd like
- Create a button in List Experiments to create a new experiment

![Screen Shot 2022-10-05 at 11.47.13 AM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/76c77933-b4ea-4f13-b117-23cccaf457ea)
- Open a Sidebar and ask for:
- - Title (Required, max 255)
- - Description (Required, max 255)

## Describe alternatives you've considered
![Screen Shot 2022-10-05 at 12.04.04 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/4cf483a6-1a4d-4075-bc02-1ab1859f20e2)

## Acceptance criteria
- Active bottom to create an experiment
- open the Sidebar and, as required, title and description (no more than 255 characters)
- The sidebar has a Save button and X (close)
- When save go to list (By now)

**Comment by oidacra** [comment]
Small fix: https://github.com/dotCMS/core/pull/23214

**Comment by dsilvam** [comment]
Passed Internal QA: Creating an experiment with _name_ and _description_ working as expected.

**Comment by bryanboza** [comment]
We have just a basic functionality in UI for now, but when you are creating a new experiment, we are not indicating that both fields are required, we need some distinction as we do in all the system. Also not sure if the `description` field should be required or not. 
![image](https://user-images.githubusercontent.com/2641437/199823920-97adc03f-248c-438f-bf92-8f38ecbf95da.png)

Maybe this is a design question @fmontes

**Comment by oidacra** [comment]
I talked with @fmontes and our pattern to follow in required inputs is a red asterisk.

- Required red asterisk, fixed in the ticket https://app.zenhub.com/workspaces/falcon-6176e9d907eb0000106ee8e1/issues/dotcms/core/22983
- No resizable Textarea fixed in the ticket https://app.zenhub.com/workspaces/falcon-6176e9d907eb0000106ee8e1/issues/dotcms/core/22983
- The order, We can create an issue for that. Now, it is necessary to start an experiment directly from frontend.

**Comment by bryanboza** [comment]
Fixed, all the issues mentioned above was moved to new cards
