### ISSUE TITLE
Site Selector not switching - reproducable!

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23106]
When you change the site selector, many times nothing happens.  Here is how to reproduce:

1. Create 2 sites - site1 and site2 (the site selector should get a down-arrow added to it automatically once you have more than 1 site)
2. create a page on site1
3. navigate to the browser screen, site1
4. make sure the site selector works.  If it does not seem to, click on the site you are on first (site1), then click on the other site (site2), it should refresh
5. double click on your page, going to edit mode.  Then, navigate back to the browser.
6. Try to change to site2.   Nothing will happen.  Click on site1 (the site the browser is on) then click on site2.  The browser should refresh.

https://user-images.githubusercontent.com/934364/194139532-7c23e57b-c8b0-4452-9f3e-9e751f4d8d08.mov

**Comment by fmontes** [comment]
@jdotcms have his change and @wezell have a change in the FE, we need to make internal QA both of this to make sure it work as expected.

https://github.com/dotCMS/core/commit/5552e0d743b399e331003171a245d0e1c35b3fc4

**In the FE change, make sure this is doesn't work this component in another places**

**Comment by rjvelazco** [comment]
I could not reproduce this issue after the merge of this PR: #23219

**Comment by josemejias07** [comment]
**Failed QA** - Tested on 22.11_45223903_SNAPSHOT // Docker // macOS 12.6 FF v106.0.3

Issue is still happening. Please make sure user is able to switch sites as he likes.  
![testsite](https://user-images.githubusercontent.com/110418590/199815982-3a891031-f2b1-4a5d-99de-3b93597d4998.gif)

**Comment by rjvelazco** [comment]
@josemejias07 The changes did not build correctly in `22.11_45223903_SNAPSHOT,` you can try with `22.11_b8dcf115_SNAPSHOT`

https://user-images.githubusercontent.com/72418962/200080177-06d1d7d8-7701-4cd5-9a82-6311f4c82b58.mov

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_b8dcf115_SNAPSHOT // Docker // macOS 13.0 // FF v106.0.3

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_b8dcf115_SNAPSHOT // Docker // macOS 13.0 // FF v106.0.3

**Comment by jcastro-dotcms** [comment]
### Internal QA: Passed
Adding several Sites and clicking around as per the steps to reproduce from Will is now working as expected. Changing the selector from one Site to another one is working correctly.

**Comment by swicken-dotcms** [comment]
reproduced in 22.03
