### ISSUE TITLE
Unable to make a bulk Publish using 40+ contentlets

### ISSUE THREAD

**Issue by josemejias07** [dotCMS/core#23118]
### Description
User is unable to sent a bulk publish with 40 or more contentlets using the content search portlet

### To Reproduce
1. Go to Content -> Search
2. Click on checkbox to select all items
3. Go to Available Workflow Actions
4. Publish All

### Expected behavior
User should be able to do a bulk publish using 40 or more contentlets

### Screenshots
![Screen Shot 2022-10-06 at 2 12 31 PM](https://user-images.githubusercontent.com/110418590/194409596-e97a1d90-cecf-4251-815c-62de985ecfe7.png)

### Desktop
 - macOS 12.5
 - Browser Chrome 105.0

### Acceptance criteria
TBD

**Comment by bryanboza** [comment]
FYI : Unable to reproduce on demo

**Comment by nollymar** [comment]
FYI: I was able to reproduce it on master. Demo works fine!. Demo is running 22.09

**Comment by erickgonzalez** [comment]
Not reproducible
