### ISSUE TITLE
UI showing wrong date when changing Timezones

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#23128]
### Describe the bug
UI is not updating correctly the date part when changing timezones, is updating the time part successfully.

### To Reproduce
1. Create a content type with a text field and date/time field, and select **Show in List** for both fields.
2. Check that the timezone is in **UTC** (Configuration Portlet).
3. Create content with the following values:
```
Title: 6 Oct 2 am
Date/Time: October 6 2022, 2:00 AM
```
4. Check the listing that shows the date entered.
5. Change the timezone to **US/Pacific**
6. Go back again to the content listing
7. The Date/time should be updated to `October 5 2022, 7:00PM`
8. If you enter that content it shows the right date/time.

### Expected behavior
Show update the date as well, not only the time.

### Screenshots

https://user-images.githubusercontent.com/5278970/194618772-764a5d54-eb33-45d6-9881-39a07e3c95fd.mov

Reproducible in demo (22.09) and 22.03.2 LTS

**Comment by erickgonzalez** [comment]
Customer ticket https://dotcms.zendesk.com/agent/tickets/108695

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Scout-617823d88f8ed0000f6cc82a/issues/dotCMS/core/23128?planning-poker) with Zenhub @freddyucv @victoralfaro-dotcms @fabrizzio-dotCMS

**Comment by freddyucv** [comment]
**Passed Internal QA:**  Tested follow the steps in the description, all work how expected

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.11_45223903_SNAPSHOT // Docker // macOS 12.6 FF v106.0.3
