### ISSUE TITLE
Remove 10k Push Publishing Limit

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#23131]
When PP a whole site or a content-type for which the amount of content is greater than 10K, only 10K will be pulled and pushed.

**STR**
Create a site in which the amount of content is greater than 10K and PP the whole site.
Or ask support for a DB of a customer.

**Expected behavior**
All content should be bundled and pushed, we should do the same fix as here https://github.com/dotCMS/core/issues/22520

Reproducible in 22.03 LTS.

Customer ticket https://dotcms.zendesk.com/agent/tickets/108561

**Comment by swicken-dotcms** [comment]
Another customer hitting this: https://dotcms.zendesk.com/agent/tickets/115368

Also, switching back to a defect, as this is not a request for enhancement but rather a request to fix functionality

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/28660

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Test with two sites with more than 10k contentlets and it works

**Comment by bryanboza** [comment]
Fixed, tested with an example dataset and now we are able to push more than 10k contents.
