### ISSUE TITLE
Tags: BE endpoint create action

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23150]
### Is your feature request related to a problem? Please describe.
As a developer, I want to be able to have an endpoint to create tags in the system.

### Acceptance criteria
- [ ] Use the pattern url `/api/v1/tags/`
- [ ] Write curl tests
- [ ] Developer should be able to create one or more tags

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/23150?planning-poker) with Zenhub @hassan-mustafa-baig @hmoreras @jcastro-dotcms @jdotcms @rjvelazco @zulqarnainvd

**Comment by hassan-mustafa-baig** [comment]
There is already TagResource developed by other developers @fmontes

**Comment by fmontes** [comment]
Resource exists
