### ISSUE TITLE
Tags: BE listing endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23155]
### Is your feature request related to a problem? Please describe.
As a developer, I want to be able to have an endpoint to list, filter and paginate tags in the system.

### Acceptance criteria
- [ ] Use the pattern url `/api/v1/tags/`
- [ ] Write curl tests
- [ ] Developer should be able to  list, filter and paginate tags

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/23155?planning-poker) with Zenhub @hassan-mustafa-baig @hmoreras @zulqarnainvd @jdotcms @jcastro-dotcms @rjvelazco

**Comment by hassan-mustafa-baig** [comment]
There is already TagResource developed by other developers that contains this rest endpoint @fmontes 
reference: (https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/TagResource.java)

**Comment by fmontes** [comment]
Resource exists
