### ISSUE TITLE
Unable to add Content to new Block editor

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23163]
If you create a new piece of content that has a block editor in it, and try to add a piece of content to it, you are unable to do so.  This is because we are passing `+languageId:0` in the content query we use to search content. 
If a piece of content is not saved, we should just not pass the languageId in the query.
 
To reproduce, 
1. go to the demo, 
2. create a new blog content object but don't save it.
3. In the block editor, try to add/link a piece of content .  This is what you get:

![Screen Shot 2022-10-12 at 5 05 10 PM](https://user-images.githubusercontent.com/934364/195448336-36003a0e-3476-4a45-b353-0152e4cddd8b.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.10 // Docker // FF 

Now we are able to add multiple contents from any type without problems 
![Image](https://user-images.githubusercontent.com/2641437/195954024-9d1b4978-94e3-40c7-9a32-7f92842f1afd.png)
