### ISSUE TITLE
Add a "Velocity Secrets" app and viewtool

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23175]
When coding integrations in Velocity, you sometimes need to securely store Access Tokens, keys, urls, passwords etc for use in integrations\.  While we do not want to expose the whole "App" infrastructure to Velocity as that would be a security risk,  it would be nice to have a specific App \- called "VelocitySecrets" or something, that would be used to store and manage these "secrets"\.  
  
The  "VelocitySecrets" app would just have a key\/value field to which an administrator could add their secret tokens, ids and keys\.  Scripters and front end devs could then access these variables in a velocity script by calling `$dotsecrets.keyName`  

We can use the same permission pattern that we do for scripting privileges \- meaning we would check the last editor of the running velocity script calling the `$dotsecrets` to make sure they were a scripting user before outputting the secret\.

**Comment by wezell** [comment]
Link to feature: https://dotcms.productboard.com/feature-board/planning/features/15857619

**Comment by jdotcms** [comment]
A new add called velocity secrets has been add, to test add config to system host and default host, for instance:

![Screen Shot 2023-03-15 at 4 09 40 PM](https://user-images.githubusercontent.com/19578350/225455382-2b6d4ab0-66b7-4aab-9154-06111d30dbca.jpg)
![Screen Shot 2023-03-15 at 4 09 36 PM](https://user-images.githubusercontent.com/19578350/225455384-09c50820-fe07-4ad6-94a0-566381bd1e44.jpg)

Then request on velocity 
```
curl --location --request GET 'http://localhost:8080/api/vtl/dynamic/' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--header 'Content-Type: text/plain' \

--data-raw '$dotJSON.put("secretKey1", $dotsecrets.secretKey1)
$dotJSON.put("secretKey3", $dotsecrets.secretKey3)
$dotJSON.put("unknown", $dotsecrets.unknown)
$dotJSON.put("systemSecretKey1", $dotsecrets.getSystemSecret('\''secretKey1'\''))
$dotJSON.put("systemSecretKey2", $dotsecrets.getSystemSecret('\''secretKey2'\''))
$dotJSON.put("systemUnknown", $dotsecrets.getSystemSecret('\''unknown'\''))
$dotJSON.put("systemDefault", $dotsecrets.getSystemSecret('\''unknown'\'', '\''systemdefault'\''))'
```

The result should be something such as
```
{
    "secretKey1": "default-value1",
    "secretKey3": "value3",
    "systemDefault": "systemdefault",
    "systemSecretKey1": "value1",
    "systemSecretKey2": "value2",
    "systemUnknown": null,
    "unknown": null
}
```

**Comment by swicken-dotcms** [comment]
Reopening as this is actively being worked on

**Comment by erickgonzalez** [comment]
since it's new feature will only backport to 23.01 LTS

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_ae620c0_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
![Screenshot 2023-06-30 at 1 25 32 PM](https://github.com/dotCMS/core/assets/129882031/6a6c26ab-f81c-4901-b99f-db0f994577e3)
