### ISSUE TITLE
Modifying designer template removes content from pages

### ISSUE THREAD

**Issue by flackend** [dotCMS/core#23181]
Making modifications to a template (e.g. adding a new row and container) will remove the content from pages that are using that template.

1. Log into https://demo.dotcms.com/dotAdmin
2. Go to the templates portlet (https://demo.dotcms.com/dotAdmin/#/templates)
3. Open "Default Template"
4. Add a new row
5. Add a new "Default - demo.dotcms.com" container to the new row
6. Click publish
7. Visit an activities page (e.g. https://demo.dotcms.com/activities/skiing)

Tested on demo site **22.09 (9/13/2022)**, also in 21.06.11 LTS

Discovered while debugging https://github.com/dotCMS/core/issues/23180.

https://user-images.githubusercontent.com/1828159/196226161-3e06b7cb-75c5-4c12-b2c5-15e03d5c1584.mp4

**Comment by flackend** [comment]
See https://github.com/dotCMS/core/issues/23180#issuecomment-1285844610

**Comment by fmontes** [comment]
@freddyucv you're up

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23181?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
PR https://github.com/dotCMS/core/pull/24376

**Comment by victoralfaro-dotcms** [comment]
Row added and published:
![image](https://user-images.githubusercontent.com/64026161/225448115-3e9b08e1-2502-42ab-8e6e-0fda65d35391.png)
Frontend: Shows page normally
![image](https://user-images.githubusercontent.com/64026161/225448219-1797a646-cb03-4d4a-92c7-19417c890ef3.png)

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_86e392fc_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

After adding a second container to the default template design, it duplicates the previously added content to the first added container.


https://user-images.githubusercontent.com/129882031/229932327-31739a0b-a756-4da6-b451-9f8ef0aa45ad.mov


Also a .js error don't show the content title

![Screenshot 2023-04-04 at 3 58 12 PM](https://user-images.githubusercontent.com/129882031/229932316-4e7d0f87-3f1b-4c1e-8eb1-fa96d1fc1fad.png)

**Comment by freddyucv** [comment]
Should be fix with this PR https://github.com/dotCMS/core/pull/24614

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_9b7edfe2_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
