### ISSUE TITLE
Need to improve the required exception 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23184]
When you have a required field and try to add a new piece of content leaving this field empty, we are getting the required error, but at the log level, we are printing multiple lines of error. 

We need to catch this error and try to print just a line error to avoid a lot of noise in the logs 

Here is the stack trace:  https://gist.github.com/bryanboza/aa7320c447aaa21b303b1651dc8f204e

### To Reproduce
- Login as admin
- Create a new content type with a required field
- Try to add a new piece of content 
- Leave this field blank and try to save it 
- Check your log file

### Expected behavior
We need to print just a line error indicating the corresponding field cannot be empty. See the ticket's PR to compare the old noisy stack trace with the smaller new one:

- https://github.com/dotCMS/core/pull/30100

### Desktop (please complete the following information):
 Tested on release-22.10 // Docker // FF

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_839cebb**, Docker, macOS 14.5, FF v126.0.1

**Comment by jcastro-dotcms** [comment]
@josemejias11 as of this Docker image: `trunk_324de85` , the code fix is present and the new validation error is being logged.

**Comment by bryanboza** [comment]
Fixed, tested in the last trunk and now we have this: 

```
dotcms-1         | 17:35:11.859  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: system : Contentlet to be saved:  , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier:
dotcms-1         | 17:35:11.862  WARN  business.ESContentletAPIImpl - Field [bin] is required
dotcms-1         | 17:35:11.862  WARN  business.ESContentletAPIImpl - Contentlet with ID 'Unknown/New' ['test'] has invalid/missing field(s). - Fields: [REQUIRED]: bin (bin)
dotcms-1         | 17:35:11.862  WARN  business.ESContentletAPIImpl - com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:7385)
dotcms-1         | 17:35:11.862  ERROR business.WorkflowAPIImpl - Failed to fire Workflow Action 'Publish' [b9d89c80-3d88-4311-8365-187323c96436]: Contentlet with ID 'Unknown/New' ['test'] has invalid/missing field(s). - Fields: [REQUIRED]: bin (bin)
```
