### ISSUE TITLE
Unable to create contentlet through workflow API even if user has appropriate permissions 

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23199]
### Describe the bug
Related Ticket: https://dotcms.zendesk.com/agent/tickets/108778

When `/api/v1/workflow/actions/fire `is called with other users' credentials except for the admin token.
API always returns 400 bad request
Request: 
```
curl --location --request PUT 'https://demo.dotcms.com/api/v1/workflow/actions/fire' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGljNmY5MDc3Ny0xZWU4LTRlYzktYjZjMi05MGI2OGZjMDgyMGUiLCJ4bW9kIjoxNjY2MjgyNTEwMDAwLCJuYmYiOjE2NjYyODI1MTAsImlzcyI6ImU4MWJjMGY5ZTciLCJleHAiOjE3NjA5MDA0MDAsImlhdCI6MTY2NjI4MjUxMCwianRpIjoiOThiOWMwMzUtOWFkZC00OTY1LTk5NzgtMjYyM2JiOGM5YmYxIn0.QHLhJBKTgc81HJ6hvk35Bj9qsC_iHQ_TmTpb_VtxjP4' \
--header 'Content-Type: application/json' \
--data-raw '{
    "actionName": "publish",
    "comments": "saving content",
    "contentlet": {
        "contentType": "test",
        "title": "2022-09-19 16:15:22.423"
    }
}'
```
Response:
```
{
    "entity": "",
    "errors": [
        {
            "errorCode": "unknown",
            "fieldName": null,
            "message": "Unable to execute Workflow: The Workflow Action name (publish) is invalid"
        }
    ],
    "i18nMessagesMap": {},
    "messages": [],
    "permissions": []
}
```
### To Reproduce
1. Go to demo site.
2. Create Test content type.
3. Create a user and a custom role.
4. Assign permissions to the role to create contentlet.
5. Now call the workflow API to create contentlet.
6. Check the error

### Expected behavior
A new contentlet must be created.

### Screenshots

[error.log](https://github.com/dotCMS/core/files/9832124/error.log)
![Screenshot from 2022-10-17 22-37-27](https://user-images.githubusercontent.com/103441252/197005651-a03c254d-5821-4dc2-88c2-df7ee2c5eb21.png)
![Screenshot from 2022-10-17 22-37-50](https://user-images.githubusercontent.com/103441252/197005658-1c5e3a3d-c1e2-4451-85fa-4bc8bab37352.png)
![Screenshot from 2022-10-17 22-38-05](https://user-images.githubusercontent.com/103441252/197005663-ba2b7d7c-64cc-453a-974f-a217d5f1de36.png)

**Comment by jdotcms** [comment]
I have done a research about it, basically on the permission api the roles "anyone how can ..." are not working as an expected when the permissionable is a workflow action.
In that case when the permissionable is a wf action and the permission is anyone how can... should check if the user has permission to use the type

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23199?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/24179

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24179

**Comment by dsilvam** [comment]
Passed Internal QA: Able to save & publish content via the provided curl and a limited user. (Daniel Publisher from starter)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_3650a5d0_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

![Screenshot 2023-04-12 at 3 24 04 PM](https://user-images.githubusercontent.com/129882031/231588396-4db29e5e-1d57-4750-a333-acbc27458ec3.png)
