### ISSUE TITLE
Bug: Unable to add 2 block editors to a content type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23216]
Easy to reproduce:

1. Create a content type with a text title field and 2 block editor fields.
2. Add a new piece of content with all the fields filled out.
3. Close the editing screen.  
4. Reopen the editing screen.  The content in the 2nd block is gone.

![Screen Shot 2022-10-24 at 2 28 41 PM](https://user-images.githubusercontent.com/934364/197598949-777de15e-cc88-4a55-93af-63fd718a109c.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.10 // Docker // FF
