### ISSUE TITLE
Fix: NullPointerException when try to add a Contentlet without version in the DEFAULT Variant

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23222]
We need to change this method to allow

https://github.com/dotCMS/core/blob/639ef463f44d9774412895edb9272b8dc884768d/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L1065

to look in all the variants

this come from this comment:

        What should we do with this method?

https://github.com/dotCMS/core/blob/639ef463f44d9774412895edb9272b8dc884768d/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L1065

We should look for all the variant too, I am getting a NullPointerException when I try to add a Contentlet with just one version in a specific variant (different to DEFAULT one)

_Originally posted by @freddyucv in https://github.com/dotCMS/core/issues/22791#issuecomment-1267260926_

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23222?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
**Note to QA**:

You need to create a contentlet without version in the DEFAULT variant to do that you need:

- Create a variant directly into data base: 
Insert into variant (name, description) VALUES ('Testing', 'This is a test')
- Add into the browser a new session storage item call variantName with the value of 'Testing'
- Create a new contenlet in the contentlet portlet, check in the contentlet_version_info that the value of the field variant_id is 'Testing' for this content.

To Test:
- Remove the session storage item.
- Create a new Page.
- Add the contentlet created before into the page, it should be add without any exception, also you can checn the multi_tree table if the register exists:
SELECT  * from multi_tree WHERE parent1 = '<page's ID>'

The contentlet is not going to be render even when we add the variantName query param because the register had 'DEFAULT' in the variant_id field, we need to send the variant_id as query params when we add a new contentlet but we are going to to that in another issue

**Comment by freddyucv** [comment]
> Member

Yes it is because that contenetlet not had any version in the DEFAULT variant, we need to create a new issue for that

even I don't know if the fix is not list that kind of contentlet (at least for now)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker 

This case was moved to a new card #23343
