### ISSUE TITLE
Block Editor: Allow users to insert images from external sources

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23238]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to search and insert images from external sources (URL) into the block editor.

### Describe the solution you'd like
We show the user an input text field where he can type or paste an image URL and a button to insert the image into the block.

### [Mocks and prototype](https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?node-id=1%3A2&t=gIg7ovYDTHW45I9q-1)

https://user-images.githubusercontent.com/751424/203644378-8e99c98c-cb4a-47dd-8bcb-5f0a339ec72c.mp4

### Additional context
We're not validating the url in this issue, we are leaving that to the user at this moment.

### Acceptance criteria
- User will enter the URL into the field
- User can insert the image by clicking the button or tabbing into focus the button and hit enter in the keyboard.
- The image gets inserted in the editor

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.01_288ffc92_SNAPSHOT** // Docker // macOS 13.0 // FF 108.0.2

Reference: 
![Screenshot 2023-01-06 at 10 38 59 AM](https://user-images.githubusercontent.com/110418590/211056738-f43159a4-485d-4054-b988-9efd973d2046.png)

**Comment by rjvelazco** [comment]
@josemejias07 This issue hasn't been merged yet (https://github.com/dotCMS/core/pull/23709).

**Comment by josemejias07** [comment]
Hi @fmontes,

We need to figure out if this is going to be on this or the next release. Can you please add the label as it correspond.

Thanks!

**Comment by fmontes** [comment]
@josemejias07 this release, but still not merge.

**Comment by fmontes** [comment]
### Known issues:

1. User can insert broken images (we'll not validate urls)
2. User can try to download a broken image and we only show an error.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_fe436a1d_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.2
