### ISSUE TITLE
Send and Accept hostName and folderPath as valid ids in content type resource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23239]
When adding a content type via api, we currently expect 2 values - `host` and `folder`.  Unfortunately, these values are always the uuid of either the host and the folder.

We need to modify our content type api to accept a hostname in the host field, e.g. `demo.dotcms.com` and a folder path in the folder field, e.g. `/` or `/about-us/`.  

Additionally, we should be sending these values along side with the host and folder ids via our contentType resource.

Acceptance criteria:

- Content-type should continue to work as always the property host should manage a host id or a site name. Field Folder always has taken a folder id. 

- The new property  folderPath could be used to capture an existing the folder in the form of  `/folder1` or `/folder1/folder2`
But it also can be used as follows: `site-name:/folder1/folder2` 

- Keep in mind that there is a new rule when it comes to create the CT. When no host is specified the CT is created now under the default host and System-folder

- Always fixed CT should be created under SYSTEM-HOST
- Whatever CT that gets imported  from the Starter should remain as it is. This means that if the CT was set to be under any specific host or folder that should be respected.

**Comment by alfredo-dotcms** [comment]
LGTM!

**Comment by bryanboza** [comment]
Fixed, tested on release-23.03 // Docker // FF
