### ISSUE TITLE
Add image from dotCMS content

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23235]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to search and insert images (file and dotAssets) from the dotCMS system to my block editor.

### Describe the solution you'd like
1. Add an "Image" item to the suggestion menu
2. When user select "Image"
3. Replace the suggestions with a bigger panel with two elements:
    1. A input type search
    2. A list of images ordered by mos recent
4. User can insert the image by 
    1. Click the image
    2. Using tab to move to the desired image and hit enter
5. The search will be pure text for now.

### [Mocks and prototype](https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?node-id=1%3A2&t=gIg7ovYDTHW45I9q-1)

https://user-images.githubusercontent.com/751424/203641779-a7c53a97-69a3-4009-82f9-0bdf0980bafe.mp4

### Additional context
The default query for search will be something like:

```
+contentType:(image OR fileAsset) +path:/images +contentType:image/jpeg || +contentType:(image OR fileAsset)
```

### What's next for this?

1. Set up a field variable to allow the user to define his very own query
2. Add tabs for External images and Upload images
3. Set up a field variable to set the folder to upload images.

### Acceptance criteria
- User can select "Image" from suggestion menu
- User can search for images using text
- User can click an image to insert
- User can hit enter to insert the focused image
- User can scroll to view more images
- By default, user should see the last 20 images sorted by `modDate`

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/23235?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by fmontes** [comment]
<img width="1035" alt="Screenshot 2022-12-27 at 15 15 20" src="https://user-images.githubusercontent.com/751424/209723075-a0b6669b-50a1-46d1-a619-2178054e6d8b.png">

<img width="790" alt="Screenshot 2022-12-27 at 15 14 06" src="https://user-images.githubusercontent.com/751424/209723085-d291161f-b1ae-4814-abba-d7102ab76f3d.png">

<img width="766" alt="Screenshot 2022-12-27 at 15 10 42" src="https://user-images.githubusercontent.com/751424/209723088-50bd77b4-2b7c-4102-ab9a-7290f54863b8.png">

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/209981483-f92a2ba6-f4fc-41bc-8b67-f36c5768d2fd.mp4

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_288ffc92_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1
