### ISSUE TITLE
Bock Editor: Allow user to insert image from local files

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23237]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to insert an image from my local files to the editor.

### Describe the solution you'd like
At this point, [we have an "Image"](https://github.com/dotcms/core/issues/23235) block in the suggestion menu, we would like to extend this functionality:

1. Add tabs to the image panel
2. The first tab will be for the current approach and the second will be for this task, uploading images from the local files.
3. When user clicks "Upload" it will open the file system window to browse for an image
4. After user select the image we upload as dotAsset and inserted, the same approach that we do when user drops an image in the editor.

### [Mocks and prototype](https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?node-id=1%3A2&t=gIg7ovYDTHW45I9q-1)

https://user-images.githubusercontent.com/751424/203642424-b3d7e0c1-cbf3-4d68-8d26-9899a3aed9f9.mp4

### Additional context
We should reuse all the uploading and creating dotAsset code from the drag and drop functionality.

### Acceptance criteria
- User should be able to insert an image from it local files
- Make sure the functionality of adding images from dotCMS doesn't breaks.

**Comment by fmontes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/23237?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @jdotcms @rjvelazco

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.02_f7c276a6_SNAPSHOT** // Docker // macOS 13.0 // FF v109

Upload popup should take over the window so we don't have a background scrolling of the blog editor. Basically a takeover

![takeover](https://user-images.githubusercontent.com/110418590/215800537-59fd2668-7227-4ea6-bdce-f7dc27e3dbf8.gif)

**Comment by fmontes** [comment]
The scroll is not par of this issue, but we are going to fix it in these two issues

#23977

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_20326b3b_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1

**Comment by erickgonzalez** [comment]
Commit for 23.01.3 https://github.com/dotCMS/core/commit/20e63abf72de84d88698a6263e24cd21aa06c15e
