### ISSUE TITLE
Implement GET experiment by Id

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#23247]
Acceptance Criteria: 
* Include everything available for the Experiment in the response
* Postman tests

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23247?planning-poker) with Zenhub @victoralfaro-dotcms @freddyucv

**Comment by bryanboza** [comment]
According to the discussion we need some work in the postman tests here...

**Comment by dsilvam** [comment]
Included additional postman for invalid/non-existing id case. Rename tests.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.11 // Docker // FF
