### ISSUE TITLE
Containers: Use $dotcontentmap.XXXX for variables

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23248]
### Is your feature request related to a problem? Please describe.
When a user is creating a container, we provide a shortcut dialog so they can easily insert variables, right now the code that injects is old and use direct `$varName`, we need to use the new `$dotcontentmap` object.

### Describe the solution you'd like
Update the add variables dialog to insert `$dotcontentmap.varName`.

### Acceptance criteria
- Add variables dialog in containers should add `dotcontentmap.varName` instead of `$varName`

**Comment by zulqarnainvd** [comment]
I didn't see the $dotcontentmap property in the response.
![image](https://user-images.githubusercontent.com/113915849/200784285-19f496d7-7a4a-46f9-8437-d913520f407f.png)

**Comment by zulqarnainvd** [comment]
@fmontes

**Comment by fmontes** [comment]
Yes, we're going to need to add it manually with the `variable`, something like `$dotContest.${variable}`
