### ISSUE TITLE
Categories: Add child count to the categories list response

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23254]
### Is your feature request related to a problem? Please describe.
As a dotCMS developer I need to show the children count for a category in the list.

### Describe the solution you'd like
Add child count to the response of the categories listing API. We only need the direct childrens.

### Describe alternatives you've considered
N/A

### Additional context
Branch out from `canary`

### Acceptance criteria
- Update the category listing API to have direct child count

**Comment by fmontes** [comment]
`/api/v1/categories?direction=ASC&per_page=40&showChildrenCount=true`

**Comment by fmontes** [comment]
We need to support children in the child endpoint as well, like:

/api/v1/categories/children?inode=9e882f2a-ada2-47e3-a441-bdf9a7254216&howChildrenCount=true

And any other endpoint that can show categories.

**Comment by hassan-mustafa-baig** [comment]
@fmontes 
We are showing children count only on the listing pages that are:  

1. one is for the top level categories 
2. another one is for children categories

**Comment by bryanboza** [comment]
We are getting a SQL error when you call this endpoint 

https://gist.github.com/bryanboza/be52856a57bacc568a171a135636dd56

This is returning the corresponding results, but we need to take care of this error 
https://gist.github.com/bryanboza/be52856a57bacc568a171a135636dd56

Tested on release-23.02 // Docker // Postman

**Comment by hassan-mustafa-baig** [comment]
url should be like this
http://localhost:8080/api/v1/categories?filter=&page=0&per_page=5&orderby=category_name&direction=ASC&showChildrenCount=true

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/23450/files and https://github.com/dotCMS/core/pull/24088/files

**Comment by erickgonzalez** [comment]
https://dotcms.zendesk.com/agent/tickets/113067
