### ISSUE TITLE
Categories: Add child categories

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23252]
### Is your feature request related to a problem? Please describe.
As a user I want to be able to browse in and out of the categories and it childrens.

### Describe the solution you'd like
- When the user clicks in a category row, if have children is should goes into the listing of the children.
- The breadcrumb should update
- When user clicks in the breadcrumb items it should list that category
- The last item of the breadcrumb have no link

### Additional context
- [Prototype](https://www.figma.com/proto/WVFNA9vfZ5CYTJGwuordsY/Portlets-%2F-Categories?page-id=0%3A1&node-id=1%3A209&viewport=819%2C-507%2C0.15&scaling=min-zoom&starting-point-node-id=1%3A209)
- [Mocks](https://www.figma.com/file/WVFNA9vfZ5CYTJGwuordsY/Portlets-%2F-Categories?node-id=286%3A1774)

### Acceptance criteria
- Allow user to browse the categories and it children from table and breadcrumb

**Comment by zulqarnainvd** [comment]
https://github.com/dotCMS/core/pull/23260
