### ISSUE TITLE
Healthcheck function doesn't clean up after itself - 5.3.4.1

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#23267]
### Describe the bug
When running the healthcheck via api files and folders are created in the asset store  but folders are not cleaned up after the healthcheck is complete resulting in consumption of disk space and inodes for empty folders.

### To Reproduce
Access /api/v1/system-status/
asset storage check creates file and deletes, with a new folder and file with random UUID
file is deleted but folder is not

### Expected behavior
In local storage or traditional NFS this will not consume space but will consume inodes.   With distributed filesystems like hadoop or AWS EFS it consumes space as well and can rapidly scale up to be a significant amount of space with frequent health checks.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF
