### ISSUE TITLE
Unable to assign contentlets in a secondary language from the task screen if there is a working version of the default language

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#23280]
### Describe the bug
When working from the tasks screen in dotCMS on a contentlet that is not in the default language when there is also a working version of the default language, the assign function does not work.

Reproduced on: 22.10, 22.03.2

Related ticket: https://dotcms.zendesk.com/agent/tickets/108709

### To Reproduce
1. From a demo starter, create a Test content type with only a title using the System Workflow
2. Add full permissions to the Reviewer role as shown in the screenshot
![image](https://user-images.githubusercontent.com/78741732/199288605-51ee027a-39e4-4240-b88b-6b303a3f84c7.png)
3. Create two new workflow actions on the System Workflow
![image](https://user-images.githubusercontent.com/78741732/199288912-81fcda64-a42a-4bd6-9b54-3dd3c7b53009.png)
![image](https://user-images.githubusercontent.com/78741732/199289035-8de8c0bd-66a0-4f1f-a940-3154583968b3.png)
4. Create two contentlets of the Test content type, one in English and one in Spanish. SAVE AND DO NOT PUBLISH! You want these both to be in a working state and not a published state.
![image](https://user-images.githubusercontent.com/78741732/199289523-232b0e42-acfa-4298-bc20-edb9c864a131.png)

5. Use 'Send to Review' action to assign the SPANISH CONTENTLET this to a reviewer from the Search portlet
6. Use Login As and log in as Nick Reviewer
7. Go to the tasks page, select the assigned contentlet and click 'Send to Publisher'
8. You will be presented with the following error:
![image](https://user-images.githubusercontent.com/78741732/199290025-dedd8dc2-3a3e-47f5-a836-79769ebafc1e.png)

### Expected behavior
You should be able to assign a working version of a non-default language even if there is a working version of the default language. 

### Additional context
This does not happen from the Search portlet. The reason being is that the Search portlet uses saveContent.dwr whereas the Tasks portlet calls the workflow task API. When calling the workflow task API it is hitting this code: 

https://github.com/dotCMS/core/blob/4fc0fb6a4dc6f7f784197621aa2b7acd1aca9b87/dotCMS/src/main/java/com/dotmarketing/business/VersionableAPIImpl.java#L350-L350

When hitting this code it compares the inode specified in the contentlet (which is the language you are trying to assign) to the inode of the default language working version. This mismatch makes it believe you are not firing a task against the current working inode.

**Comment by fabrizzio-dotCMS** [comment]
After a little bit of research, I was able to track the root of the problem to the Task detail Dialog itself
When Task is executed from here the language param isn't get sent. Therefore the default is assumed causing the Versioning API to fail to locate the working version 
![Screen Shot 2022-12-13 at 16 25 31](https://user-images.githubusercontent.com/37148755/207458665-5a8f70c2-4e71-4537-80ef-94019cd51fea.png)

The Alternative is to fire the workflow via Bulk-Actions 
This dialog includes the proper language para and it succeeds to execute the workflow
![Screen Shot 2022-12-13 at 16 25 49](https://user-images.githubusercontent.com/37148755/207459114-d511f9a9-8c9f-4979-9bcd-20a7625c3fea.png)

**Comment by fabrizzio-dotCMS** [comment]
The workflow action dialog (which is an angular component) does the workflow execution and should pass the language id
![Screen Shot 2022-12-13 at 22 34 58](https://user-images.githubusercontent.com/37148755/207506759-f116a6b2-59a6-4d8a-a4c0-c4fe0c335c38.png) 

This needs work from a front-end engineer

**Comment by alfredo-dotcms** [comment]
after some research, seems more like a BE issue

**Comment by fabrizzio-dotCMS** [comment]
I just confirmed it's front-end 
Take this POST URL as an example 
http://localhost:8080/api/v1/workflow/actions/af70c952-ef76-4104-b39f-655569c4f152/fire?inode=c8e1960a-a521-484d-b6f7-00f94efcb491&indexPolicy=WAIT_FOR

The missing param is `language` as it can seen in the screenshot below

![Screenshot 2023-01-09 at 13 15 07](https://user-images.githubusercontent.com/37148755/211389438-5c9c4548-ae4e-478e-aa5b-98f2fbe288f1.png)

I apologize for not including that info in the ticker

**Comment by fabrizzio-dotCMS** [comment]
https://github.com/dotCMS/core/pull/23767

**Comment by alfredo-dotcms** [comment]
looks good to me!
![image](https://user-images.githubusercontent.com/37185433/215910801-42bbdb3d-d557-4ab6-95a9-c3898088df53.png)

**Comment by josemejias07** [comment]
Blocked by #24262

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.03_3d55dd2c_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0

We can assign a working version of the contenlet in a secondary languages but we are failing to inherited the permissions of the contenlet to the secondary language


https://user-images.githubusercontent.com/110418590/224085669-fd7d2b4d-c39b-46f8-87f0-085de4f0d170.mov

**Comment by josemejias07** [comment]
> I just checked again and it all looks alright for me.. permissions and workflow wise. @josemejias07 is going to revise on his side again

It might had being some wrongful configuration on my side, but I'm looking this okay now.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_3d55dd2c_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0.1
