### ISSUE TITLE
Fix DotImage

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23294]
The DotImage component should use the nextJS Image component and also support the alt and captions that are set on the image.

Right now it gets squashed unproportionally to 16rems

<img width="948" alt="Screen Shot 2022-11-03 at 4 05 43 PM" src="https://user-images.githubusercontent.com/934364/199823304-5a868071-04b0-413f-be57-4ffcd11b63d9.png">

**Comment by fmontes** [comment]
Closing, new UVE examples fix this.
