### ISSUE TITLE
Get categories by ID

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23307]
### Is your feature request related to a problem? Please describe.
As a developer I want to be able to get the category information by ID

### Describe the solution you'd like
We need a new endpoint to get categories by ID

### Additional context
1. Do we need the child categories in the response?
2. How do we do this performance wise?

### Acceptance criteria
- User should be able to get a category using the variable name

**Comment by fmontes** [comment]
We need to add childcount param.

**Comment by hassan-mustafa-baig** [comment]
[http://localhost:8080/api/v1/categories/<<inodeOrKey>>

you can pass **category Inode** or **category Key** in the place of **<<inodeOrKey>>**

**Comment by fmontes** [comment]
Tried this:

http://localhost:8080/api/v1/categories/9e882f2a-ada2-47e3-a441-bdf9a7254216?showChildrenCount=true

And this:

http://localhost:8080/api/v1/categories/ageOrGender?showChildrenCount=true

With the **full starter** and it didn't show the child count.

**Comment by manuelrojas** [comment]
We need to make sure that the child's got count. 

URL: http://localhost:8080/api/v1/categories/children?direction=ASC&per_page=40&inode=96479128c90c36b367572ecda15037f2&showChildrenCount=true

**Comment by hassan-mustafa-baig** [comment]
I have been testing this functionality and I have observed that this functionality is working fine 

**http://localhost:8080/api/v1/categories/ageOrGender**    
I was testing getByKey so the key is **ageOrGender** without providing **showChildrenCount=true**

![image](https://user-images.githubusercontent.com/111717530/226495156-ae59c407-f96d-4158-88ca-a80e2e22a2f1.png)


**http://localhost:8080/api/v1/categories/ageOrGender?showChildrenCount=true**    
I was testing getByKey so the key is **ageOrGender** with providing **showChildrenCount=true**

![image](https://user-images.githubusercontent.com/111717530/226495422-b1c4fcbd-42e9-4256-be36-413a2189100a.png)



**http://localhost:8080/api/v1/categories/9e882f2a-ada2-47e3-a441-bdf9a7254216**    
I was testing getById so the id is **9e882f2a-ada2-47e3-a441-bdf9a7254216** without providing **showChildrenCount=true**
![image](https://user-images.githubusercontent.com/111717530/226495614-83d3165c-4d0e-4825-a139-5fcc8c89b82e.png)



**http://localhost:8080/api/v1/categories/9e882f2a-ada2-47e3-a441-bdf9a7254216?showChildrenCount=true**    
I was testing getById so the id is **9e882f2a-ada2-47e3-a441-bdf9a7254216** with providing **showChildrenCount=true**
![image](https://user-images.githubusercontent.com/111717530/226495614-83d3165c-4d0e-4825-a139-5fcc8c89b82e.png)

![image](https://user-images.githubusercontent.com/111717530/226495778-387e4d70-3572-4568-a4f8-9a589fcf2348.png)
