### ISSUE TITLE
[UI] Reuse Edit Mode to change variant content

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23319]
## Is your feature request related to a problem? Please describe.
Reuse the Browser (Edit Mode) to handle the variants when the user clicks to view/edit button of one variant

![Screenshot 2022-11-08 at 1.38.17 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/20668e2a-d70c-46d9-956a-e4fc124cc7f9)

go to.
[![edit-page.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/57cc0037-a661-4e1b-b59c-389a64370cd4)](https://www.figma.com/file/fAoCk4swhiwplkU5GP21YD/Portlet-%2F-Experiments?node-id=366%3A5998&t=JM1MAXyd4ovhHFN5-4)

## Describe the solution you'd like
- Use query params as discriminant isExperiment=1 to show/hide parts of Edit Mode.
- A button to go back to the experiment (query param experimentId=xxxx-xxx-xxx-xxx)

## Describe alternatives you've considered
N/A 

## Acceptance criteria
-  Hide the LIVE tab
- Hide Lock Page
- Show a Back to Experiments Button.

**Comment by dsilvam** [comment]
PR: [#23580](https://github.com/dotCMS/core/pull/23580)

**Comment by dsilvam** [comment]
Passed Internal QA.
* Able to View the Original Variant
* Able to Edit the other Variants. 
* Back button returning to the Experiment.
