### ISSUE TITLE
Contextual options are not correct

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23313]
## Describe the bug
1. The system containers should not have the ... button
2. The contextual menu that shows when the user clicks the ... button on every row is not showing the right options.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/751424/200432553-1361dbeb-0492-45b3-9cb2-ee52d22e5277.png">

## To Reproduce
1. Go to new containers portlet
2. Click on the ... button in any rows
3. See the options

## What should be the options?
Options are defined by three things:

1. The dotCMS license in the system
2. If there is a push-publish environment set
3. The status of the container that could be: 
    - Published
    - Unpublished
    - Archived

### No license

**Published:**
- Edit
- Publish
- Unpublish
- Duplicate

**Unpublished:**
- Edit
- Publish
- Archive
- Duplicate

**Archived**
- Unarchive
- Delete

### License

**Published:**
- Edit
- Publish
- Unpublish
- Duplicate
- **Add to Bundle**

**Unpublished:**
- Edit
- Publish
- Archive
- Duplicate
- **Add to Bundle**

**Archived**
- Unarchive
- Delete

### With push publish
To add push publish you need to create an environment, [here is the video on how to do it](https://user-images.githubusercontent.com/751424/200434163-b4b8dfbf-b40d-45e8-94bf-424a9e156d8d.mp4).

**Published:**
- Edit
- Publish
- Unpublish
- Duplicate
- Add to Bundle
- **Push Publish**

**Unpublished:**
- Edit
- Publish
- Archive
- Duplicate
- Add to Bundle
- **Push Publish**

**Archived**
- Unarchive
- Delete

### Additional context
We did this in template, here is some code [you can use as base](https://github.com/dotCMS/core/blob/master/core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.ts#L360).

### Acceptance criteria

- [x] User should not see the ... button in the system container
- [x] User should see the options in the ... based on the information above.

**Comment by zulqarnainvd** [comment]
@fmontes I also need a dotCMS license for this work

**Comment by fmontes** [comment]
License sent over slack.

**Comment by zulqarnainvd** [comment]
@fmontes are you sure we need to remove the delete option in the archive container in license mode because it is available in without license mode?

**Comment by zulqarnainvd** [comment]
@fmontes are you sure we need to add an archive option in published containers in the license mode and push publish environment?

**Comment by fmontes** [comment]
> @fmontes are you sure we need to remove the delete option in the archive container in license mode because it is available in without license mode?

Good catch, no we don't I just updated the description.

**Comment by fmontes** [comment]
> @fmontes are you sure we need to add an archive option in published containers in the license mode and push publish environment?

Good catch, updated the comment.
