### ISSUE TITLE
When the Experiment start PUBLISH all the contentlet with experiment's variant version

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23331]
### Is your feature request related to a problem? Please describe.

When the Experiment start we need to PUBLISH all the contentlet that had version into any Experiment's variant.

### Describe the solution you'd like

We need to do that into the start API method

https://github.com/dotCMS/core/blob/99fa75b06d17ed830f85152a34bd2e73e9fa2b19/dotCMS/src/main/java/com/dotcms/experiments/business/ExperimentsAPIImpl.java#L300

We need to iter over all the expriment's variant and look for all the contentlet_version_info with this variant and PUBLISH them all.

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23331?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
**Pass internal QA**: 

- Create a new Experiment using the /block/index page.
- Create a new variant into this experiment using the end point directly.
- Storage the variantName item into the sessionStorage with the name of the newly variant.
- Create new version of two contentlet added into the /blog/index page.
- Start the contentlet and check into the datebase if the two contentlets's version was publish.

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps and this is working, however, this is not working properly in the UI
