### ISSUE TITLE
Menu Nav in the BE not showing options when collapse

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#23341]
### Describe the bug
When login into dotcms BE and having the Menu Nav collapse, some of them aren't being listed, it just shows empty.
![Screen Shot 2022-11-10 at 2 29 38 PM](https://user-images.githubusercontent.com/5278970/201199493-8c119d71-c021-4bf5-ad88-956e10197250.png)

This is a sporadic issue, but customers with previous versions are hitting this (I have seen it in 5.3.8.14 and 22.03.3), and only have seen it in Chrome (we're suspicious that could be related to a browser update.

### To Reproduce
1. Login into the BE.
2. Menu Nav must be collapsed
3. Hoover over the diff menus.
4. See the error

### Expected behavior
All menu items should show up.

**Comment by hmoreras** [comment]
QA: try on expand and collapse the menu several times and then do hover over the options. 

https://user-images.githubusercontent.com/31667212/209867927-8fe849b3-d88f-44ec-93bb-c6179cab4070.mov

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_288ffc92_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1
