### ISSUE TITLE
Display PDFs and Video in the content edit screen.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23359]
I don't know where we lost it, but we used to show pdf preview images in our backend when editing content.  Also, while we are at it, it would be great to be able to show video previews as well.

We will need components for this in our next iteration of our ui.  For now, make do.

![Screen Shot 2022-11-14 at 5 42 55 PM](https://user-images.githubusercontent.com/934364/201783542-30ea8e1a-8072-454c-b373-95aae6970771.png)

![Screen Shot 2022-11-14 at 5 42 45 PM](https://user-images.githubusercontent.com/934364/201783554-a4bd168b-296f-4bf2-8589-653e6d11d824.png)

**Comment by rjvelazco** [comment]
**Passed Internal QA**

Docker Image: `23.01_ca54c27a_SNAPSHOT`

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_681bdc7a_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0
