### ISSUE TITLE
UI fixes for containers

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23362]
### Describe the bug
This issue is to handle multiple small issues in the UI/UX of containers.

https://user-images.githubusercontent.com/751424/201795250-2209e1bf-c3d7-4e39-8669-bd70ea1fb4ac.mp4

### Acceptance criteria

- [x] The API button should not show on create
- [x] Pre-loop and post-loop labels are wrong
- [x] The name field should be focused on load when create

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23377
