### ISSUE TITLE
Webdav is not working on 22.10.1 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23363]
When you try to connect via WebDAV to the server running our 22.10.1 version we are getting an error and we are unable to connect, seems we are missing a library and this is causing the error.

Stack: https://gist.github.com/bryanboza/9e4ca23a646974e626d48c373d7b175a

### Expected behavior
We need to be able to connect and use WebDAV without problems 

### Desktop (please complete the following information):
Tested on release-22.10.1 // Docker // Cyberduck

**Comment by wezell** [comment]
fixed in 22.12
