### ISSUE TITLE
Remove "paper" portlet wrapper

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23369]
When we were all about Material Design, we wanted our portlets to reflect a layered, paper like UI with different objects having different depths.  Now that styles are changing, we would like to reclaim that unused white space for both cleanliness and other things.  

![Screen Shot 2022-11-15 at 2 39 00 PM](https://user-images.githubusercontent.com/934364/202010433-5b209d00-d679-4e7c-bc5b-259b899c7fad.png)

This will also have to be done on the:

- [ ] Content Types Screen 
- [ ] Apps Screen
- [ ] New Containers Screen
- [ ] Rules Screen
- [ ] Templates Screen
- [ ] Edit Mode - page render

**Comment by zulqarnainvd** [comment]
@fmontes Box shadow still showing on the header.
![image](https://user-images.githubusercontent.com/113915849/209638083-e8bb81be-1f02-4572-aa50-4ed7730a1286.png)

**Comment by fmontes** [comment]
Shadow removed `23.01_19fba79e_SNAPSHOT`

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_7a5556e7_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1

**Comment by bryanboza** [comment]
Need to apply this change to: 

Forms:
![image](https://user-images.githubusercontent.com/2641437/210592988-f7cae2bd-ee4a-4a9b-8990-f7f73f5406ea.png)

Apps: 
![image](https://user-images.githubusercontent.com/2641437/210593103-1baed130-7c2b-46d7-bba0-5cf988fa8b96.png)

Content Types:
![image](https://user-images.githubusercontent.com/2641437/210593188-141508f9-7b86-4a66-a36e-f6471e860ad4.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF
