### ISSUE TITLE
Unable to bring back old versions of templates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23366]
When you are working with some template and go to the history tab and try to bring back to an old version of this, we are getting an exception and we are unable to bring back

![image](https://user-images.githubusercontent.com/2641437/201998167-f28d8976-f3f4-41df-85d6-5d2138c6f777.png)

Stack: https://gist.github.com/bryanboza/93181818e54ed66aef0533030bd2fd83

### To Reproduce
- Create a new template
- Edit the template and create a new version
- Go to the history tab and try to bring back the previous version 

### Expected behavior
The previous version should be rendered. 

### Desktop (please complete the following information):
Tested on release-22.11 // Docker // FF 

### Helpful Information
This endpoint is returning 2 entries: System Template and the actual template we want to bring back. 
https://demo.dotcms.com/api/v1/templates/?filter=d4d638fe-2ca6-4e6e-a4aa-013d6e2b97fa

Let's use the entry[1] instead of entry[0].

**Comment by erickgonzalez** [comment]
Not reproducible in 22.03 but in demo (23.01) yes

**Comment by AndreyDotcms** [comment]
To reproduce this issue take in count the next video:

https://github.com/dotCMS/core/assets/127987858/e0de0e23-62e4-4e50-9737-c7d0992bd49e

This could be a FE issue, feel free to reach me in case to have some doubts.

**Comment by erickgonzalez** [comment]
**On-Hold:** Waiting for UI/UX to check if we should add a button in the template editing to bring back an old template.

**Comment by erickgonzalez** [comment]
UI/UX will be done in another ticket https://github.com/dotCMS/core/issues/28417

**Comment by erickgonzalez** [comment]
Works as intented! Now it renders the previous version.

**Comment by bryanboza** [comment]
Ok after this fix, now we are able to render the previous version, but we still unable to bring back to this version, New card related to it here #28417
