### ISSUE TITLE
Block editor does not show content in inline editing

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#23382]
### Describe the bug
In edit mode, when you `click` on the `block editor field` the side bar shows up but it's empty.

### To Reproduce
1. Go to a blog page.
2. Go to Edit Mode.
3. Click on`block editor field`
4. See the error.

### Expected behavior
The block editor should be displayed with its content not empty.

### Screenshots

https://user-images.githubusercontent.com/72418962/202290506-d471cbd2-0ac9-4eb6-a831-ab05305b15ed.mov

### Additional context
----

### Acceptance criteria
- It should open the block editor with its content.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA:  FAILED
As per discussion with @rjvelazco , it may be that something UI-related went wrong when the Docker image was generated.

**Comment by rjvelazco** [comment]
@jcastro-dotcms It's failing in docker but it's working locally on `release-23.01`. I'm going to generate a new image.


https://user-images.githubusercontent.com/72418962/207439550-cf9fd11f-7bb7-441e-9e87-aed59b993902.mov

**Comment by rjvelazco** [comment]
@jcastro-dotcms It's working now in the new Docker Image: `23.01_a953eb1e_SNAPSHOT`, can you try again?

https://user-images.githubusercontent.com/72418962/207470736-a88ece2f-3169-4a08-a17e-e1b3188a80bf.mov

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA:  PASSED

* Docker Image: **23.01_a953eb1e_SNAPSHOT**

Confirmed that there was never a problem with the code fix, but with the Docker image.

**Comment by josemejias07** [comment]
Hi @rjvelazco,

Could you be so kind and check this alignment. We are getting some overlapping there that we need to check. 

![Screenshot 2022-12-15 at 3 02 57 PM](https://user-images.githubusercontent.com/110418590/207980613-4efa27cc-615d-4c83-b75f-5cba882a518f.png)

**Comment by rjvelazco** [comment]
Hey, @josemejias07, here is the PR: #23594, waiting for approval.

**Comment by josemejias07** [comment]
Hi @rjvelazco,

Can you please take a look at this. When I try to edit the blog, I'm getting this warning. 

![Screenshot 2022-12-19 at 11 44 45 AM](https://user-images.githubusercontent.com/110418590/208487754-c64b4c2d-a0c7-4de2-9ce8-cb094753c039.png)

**Comment by rjvelazco** [comment]
@josemejias07 It's working for me in the last docker image (`23.01_5fa1e679_SNAPSHOT`). The error says: "The URL does not exist", maybe the page you are trying to `edit` is `archived` or was `deleted`?

<img width="1291" alt="Screenshot 2022-12-19 at 1 59 23 PM" src="https://user-images.githubusercontent.com/72418962/208490116-44d690a3-f744-4422-9844-5f95f416e7ed.png">

**Comment by josemejias07** [comment]
Hi @rjvelazco,

As discussed over Slack, this must be related to a db expiring setting that we may have. We can ignore this feedback.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_c3349038_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1
