### ISSUE TITLE
When you hit the Publish action from the tasks page you get the Push Publish dialog

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#23395]
### Describe the bug
When you try to use the Publish action from the tasks page (the dropdown on the task itself) you get the Push Publish dialog box instead of firing the publish action

Related Ticket: https://dotcms.zendesk.com/agent/tickets/109059

Reproduced on: 22.10, 5.3.8.14, demo (23.03)

### To Reproduce
From the demo starter
1. Add the tasks portlet to your user if it does not exist
2. Save a contentlet so it will be assigned to you
3. Go to the tasks screen
4. Open the task for the contentlet you saved
5. Click the dropdown and click 'Publish' 
![image](https://user-images.githubusercontent.com/78741732/202561380-3b8559fa-f5c1-48e7-bbde-ea470d6d6810.png)
6. The push publish dialog box will open

### Expected behavior
This should run the publish action, and not open the push publish dialog box

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d8ef9ab_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
