### ISSUE TITLE
Setup Ongoing Static Code Analysis using SonarQube

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#23405]
In order to improve code quality, specifically security, dotCMS has elected to use SonarQube to perform static code analysis.

SonarQube has identified 10 issues when running against our dotCMS/core Master branch. \(https://github.com/dotCMS/core\) Here are the links to the issues:

* 15 Blocker Severity Vulnerabilities --  https://sonarqube.dotcms.site/issues?resolved=false&severities=BLOCKER&types=VULNERABILITY

* 3 Critical Severity Vulnerabilities -- https://sonarqube.dotcms.site/issues?resolved=false&severities=CRITICAL&types=VULNERABILITY

The security team at dotCMS would eventually like to include SonarQube as part of the ongoing QA process, but in order to do so we need to resolve some of the outstanding issues, and in the process gain better understanding of how to use SonarQube.

\`\`\`\[tasklist\]

## Tasks

- \[x\] Gain better understanding of SonarQube by working to resolve the 15 "Blocker" and 3 "Critical" issues reported
- \[x\] Identify & list out any false negatives reported in the test so we can discuss with the team; if we're going to use SonarQube we'll need a "best practices" document and we'll need to help people quickly close off false negatives
- \[x\] Identify if the "estimates" in SonarQube are at all useful or reliable; assumption is that they are not
- \[x\] Evaluate if SonarQube would be a good fit to be added to ongoing QA efforts; why or why not?
- #23696
- #23900
- \[ \] https://github.com/dotCMS/core/issues/23696
- \[ \] https://github.com/dotCMS/core/issues/23900
\`\`\`

**Comment by fabrizzio-dotCMS** [comment]
Note for QA: 
We need to validate in the current release branch 23.01 that.. 
we can upload multiple files
we can deploy OSGI plugins
that in general we can load and unload portles
and in general do a smoke test

**Comment by fabrizzio-dotCMS** [comment]
related to https://github.com/dotCMS/core/issues/23578

**Comment by fabrizzio-dotCMS** [comment]
new PR sent against release 23.01 https://github.com/dotCMS/core/pull/23643

**Comment by alfredo-dotcms** [comment]
OSGI plugin deployed
![image](https://user-images.githubusercontent.com/37185433/209232085-cdbf5030-0300-4437-87a9-7c110d7689b7.png)

PP filters
![image](https://user-images.githubusercontent.com/37185433/209232125-fbb108e5-7d6b-4010-a5d3-104873028d7b.png)

PP Publish
![image](https://user-images.githubusercontent.com/37185433/209232200-7b109ce6-ec6c-4db7-a5f0-d58c3e7d99c7.png)

Content Search - Multiple Img uploaded
![Screen Shot 2022-12-22 at 3 54 08 PM](https://user-images.githubusercontent.com/37185433/209232621-de94aff6-221b-4fa1-853a-7449abec911f.png)


![image](https://user-images.githubusercontent.com/37185433/209232473-768ec3ca-1fa0-4383-8ec1-d95ac7435454.png)

**Comment by bryanboza** [comment]
Hey guys, after test some of the mentioned areas above, I noticed we have some errors here: 

The plugin portlet is showing an console error when you try to refresh 
![image](https://user-images.githubusercontent.com/2641437/210667496-f8776cb1-fef1-4d73-872f-340157f9d4c4.png)
Also, If you. try to upload from BE using Safari this is not working 

We are getting an error importing content 
Here the log: https://gist.github.com/bryanboza/72f69c670d0cd43b185beb2e548027c1
Here the error: 
![image](https://user-images.githubusercontent.com/2641437/210667743-8bc8e735-5bf1-4c3d-aa19-646a7853e4ed.png)

**Comment by fabrizzio-dotCMS** [comment]
I wasn't able to reproduce this issue on my instance of release23-.01
I created a Content-Type like this :

![Screenshot 2023-01-05 at 10 09 30](https://user-images.githubusercontent.com/37148755/210826829-a4363138-4cf7-42b5-a7aa-fca11fbafc8b.png)

The I used the file from the prior comment to do a content import.

Here's the image of the resulting content 

![Screenshot 2023-01-05 at 10 08 37](https://user-images.githubusercontent.com/37148755/210826665-e86edbda-dbff-4300-8947-ec827c0217b2.png)

Additionally if any javascript issue surfaced here I'd suggest we move it to a separate issue since the vulnerability fixes addressed here only concerned java code, @bryanboza @damen-dotcms @wezell

**Comment by bryanboza** [comment]
After discuss with @fabrizzio-dotCMS seems this is an issue related to the browser session, for some reason I have something wrong in my session and break this. 

After test multiple times, we noticed this is working fine on Chrome, and we are able to reproduce 100% of the times in Safari

**Comment by bryanboza** [comment]
Fixed, the problems mentioned above was split to two separated cards, We will take care of this in future releases. 
#23740 and #23741

**Comment by damen-dotcms** [comment]
I reopened this as a demo issue. It can be closed. Sorry I didn't mean to imply the original scope wasn't done.. I just wanted to re-organize it as a sample epic.
