### ISSUE TITLE
Insure zip file integrity

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23401]
We have an issue when a user uploads an invalid zip file.  For more information, see here:
https://docs.google.com/document/d/1ZRLax-cK-uirZ5uDYW57HWNlvEpi_Llkjtr71gke4hA/edit#heading=h.pkblndqgydjw

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/commit/6f9a9760a9c723fdcf5f0b4540e287a0c4f67375

**Comment by jcastro-dotcms** [comment]
Please reach out to me in order to get the steps to reproduce and additional required information for testing the fix.

**Comment by fmontes** [comment]
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/751424/205755518-28e1d78d-c29f-4bf3-a4bd-57ad948c5365.png">

<img width="2230" alt="image" src="https://user-images.githubusercontent.com/751424/205755595-6c7378d6-26a2-4c17-9a67-0f4350a4a945.png">

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **22.12_116d59d4_SNAPSHOT** // Docker // macOS 13.0 // FF v107.0.1
