### ISSUE TITLE
[UI] Remove description text from dropdown in Editor Page

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23406]
### Is your feature request related to a problem? Please describe.
As the first step to show variants on Editor Page, we need to remove the description of the dropdowns and fix all text font (size and color).

### Describe the solution you'd like
Use the approved design from [Figma](https://www.figma.com/file/fAoCk4swhiwplkU5GP21YD/Portlet-%2F-Experiments?node-id=344%3A4390&t=yDKMMe9lpTj3OUTj-4) 
![Screenshot 2022-11-21 at 2.23.07 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/d26746bc-7af3-48d8-a5c4-74533e3c0af4)

### Describe alternatives you've considered
N/A

### Additional context
Minimal updates in details of the Editor page to begin to implement show Variants of experiments.

### Acceptance criteria
- Remove the description from the Language dropdown
- Remove the description from the Device dropdown
- Remove the description from the Personas dropdown
- Verify all the font colors and sizes.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/23484

**Comment by dsilvam** [comment]
Passed Internal QA: Not showing the labels anymore on the dropdowns.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.01_ca54c27a_SNAPSHOT** // Docker // macOS 13.0 // FF v107.0.1

Reference
![descriptions](https://user-images.githubusercontent.com/110418590/207373132-312ec898-33e2-4851-81ad-030682f4d119.gif)

**Comment by oidacra** [comment]
The change requested was:
From 
<img width="1537" alt="Screenshot 2022-12-13 at 10 43 27 AM" src="https://user-images.githubusercontent.com/1909643/207382663-db939266-a831-46fa-a572-49a89593e69f.png">

To:
<img width="1183" alt="Screenshot 2022-12-13 at 10 51 14 AM" src="https://user-images.githubusercontent.com/1909643/207382713-8525c455-c17a-4409-aace-0b6f562ec712.png">

The description of the dropdown needs to be removed. We need to take into consideration the resolution of the screen, if the resolution is below 1545 pixels, the dropdowns only show the icons like the video.
