### ISSUE TITLE
Allow table cell to transform text to headings and list

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23432]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to transform the text inside a cell into Headings and lists (ordered and unordered)

### Describe the solution you'd like
When the user selects the text we show the bubble menu and inside that we have the "Transform" dropdown, so the user can transform the text into Headings or Lists.

### Acceptance criteria
- User should be able to have heading and lists of blocks inside a cell by transforming the text.

**Comment by rjvelazco** [comment]
**NOTE**:

Looks like `<h3>`  has an extra-padding, not sure if it's an issue.

<img width="955" alt="extra-padding" src="https://user-images.githubusercontent.com/72418962/207406524-e32382f3-73b2-4516-a40e-6bc5c32d1692.png">

**Comment by josemejias07** [comment]
### Approved QA - Tested on **23.01_681bdc7a_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0
