### ISSUE TITLE
Start/Stop Plugin should perform relevant actions in a cluster environment

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23439]
### Is your feature request related to a problem? Please describe.
Starting/Stopping a plugin does not start/stop it in a cluster environment.
If a customer wants to start/stop a plugin in a cluster, They need to undeploy it.

Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/109171

### Describe the solution you'd like
Start/Stop Plugin should perform relevant actions in a cluster environment.
If a customer clicks on the stop button, then the plugin should also stop in all other nodes.

**Comment by wezell** [comment]
Will not fix. You need to undeploy a plugin to deactivate it in a cluster.
