### ISSUE TITLE
UI: Add/Remove Edit contentlet for a page into a specific Variant

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23434]
### Is your feature request related to a problem? Please describe.
When Add, Remove a contentlet into the Edit Page portlet we need to add o remove this contentlet just to the specific variant that we are working on.

### Describe the solution you'd like
So we need to check if the variantName item into the sessionStirage exists and if it exists then we must sent it into the end point request as a Query Paramas.

Right now it is working in the end point level but we need to make it work from the UI.

### Additional context

Edit contentlet should work by now but we need to make sure 
Also make sure that edit any property of the page is going to create a new version of this page for the specific variant

### Acceptance criteria
- Add or Remove  contenlet from the UI when the variantName item is set into the session Storage should wor, this mean the contentlet should be Add or remove just for the specific variant
- Edit any page or contentlet should edit or create (if it not exists yet) the version for the specific variant

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23434?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
PRs:
https://github.com/dotCMS/core/pull/23465
https://github.com/dotCMS/core/pull/23468

**Comment by freddyucv** [comment]
Note to QA: To test this you need :

- Create a new variant: you ca create it creating one for a specific experiment (you must use the ed point directly), 
OR inserting it directly into data base: INSERT INTO variant values (Name, description) VALUES ('Testing', 'Testing')

- After that you must create a new item into the session Storage in the browser called variantName the value must be the name of the variant that you just create.

**Comment by dsilvam** [comment]
Passed Internal QA. Working as expected.

**Comment by bryanboza** [comment]
Blocked by this comment https://github.com/dotCMS/core/issues/23159#issuecomment-1349620084 

Need some work here

**Comment by dsilvam** [comment]
Passed Internal QA: Fixed here https://github.com/dotCMS/core/issues/23543

**Comment by bryanboza** [comment]
Fixed, tested on release 23.06 // Docker // FF
