### ISSUE TITLE
Add marks to the table cell text content

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23431]
### Is your feature request related to a problem? Please describe.
As a user I want to be able to add have the text in my table with:

- Bold
- Italic
- Strikeout

Also add links to it and align texts left, right and center.

### Describe the solution you'd like
Use the bubble menu with the marks that we do for text to apply inside the table cell.

### Acceptance criteria
- Users should be able to select the text and from the bubble menu add marks to it.

**Comment by rjvelazco** [comment]
Passed Internal QA.

Docker Image: `23.01_ca54c27a_SNAPSHOT`
