### ISSUE TITLE
Block Editor: Create video block node and insert from dotCMS content

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23436]
### Is your feature request related to a problem? Please describe.
As a user, I want to insert videos in the block editor from the dotCMS system to my block editor.

### Describe the solution you'd like
1. Open the suggestion
2. Select "Videos"
3. Show the modal with the tabs, same as images
4. List all the videos and filter
5. Click the video to add the video

### Describe alternatives you've considered
For now just this, we have other tasks for add videos from external URL and user file system.

### Acceptance criteria
- User should be able to add videos from dotCMS dotAssets
- 
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/23920
- [ ] https://github.com/dotCMS/core/issues/23920
```

**Comment by fmontes** [comment]
```tasklist



```

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/23933

**Comment by fmontes** [comment]
In `master` branch

1. Upload a video from the block editor
2. Then try to add the video from the content search.
3. Video is not found.

**Comment by rjvelazco** [comment]
@fmontes I could not reproduce the `issue` with the latest docker image for `master`, [[Tag](https://github.com/dotCMS/core/actions/runs/4105814850/jobs/7083549240#logs): `dotcms/dotcms:master_eb903521`]. Could that be a problem with the docker image?

I'm adding a video below with the steps, trying to reproduce the issue. Let me know if I'm wrong in any step.


https://user-images.githubusercontent.com/72418962/217261272-5bfb2a81-0e5d-41e1-901d-28299effcd39.mov

**Comment by fmontes** [comment]
There is a bug where is doesn't show in the list certain videos which meta type is `application/mp4` we created an issue for it:

https://github.com/dotCMS/core/issues/24051

**Comment by fmontes** [comment]
I am not able to repro this error in the current docker version, please try again.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_2539461f_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
