### ISSUE TITLE
Add the table block to the vtl render

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23430]
### Is your feature request related to a problem? Please describe.
As a user, I want to be able to use the `toHTML()` velocity method and have tables render with default code.

### Describe the solution you'd like
In the folder `/dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock` we need to create a `{blockName}.vtl` file and add the need it codes to render a table.

### Acceptance criteria
- User should be able to render a table in a container from a block editor.

**Comment by hmoreras** [comment]
**Documentation**

To create a custom table block, just create a `table.vtl` file under `application/vtl/blog/blocks` an use this as an example: 

````
#parse( "static/storyblock/render.vtl" )

<table class="custom-class">
 #foreach($row in $item.content)
  <tr>
     #foreach($cell in $row.content)
        #if( $cell.type == "tableHeader" )
            <th colspan="$!cell.attrs.colspan" rowspan="$!cell.attrs.rowspan" colwidth="$!cell.attrs.rowspan" >#renderContentBlock($!cell.content)</th>
        #elseif($cell.type == "tableCell" )
            <td colspan="$!cell.attrs.colspan" rowspan="$!cell.attrs.rowspan" colwidth="$!cell.attrs.rowspan">#renderContentBlock($!cell.content)</td>
        #end
     #end
  </tr>
 #end
</table>
````

**Comment by rjvelazco** [comment]
**Passed Internal QA.**

**Docker Image:** `23.01_19fba79e_SNAPSHOT`

**Comment by rjvelazco** [comment]
**NOTE FOR QA**

This issue is only for the `.vtl` render not for the table styles ([that is another issue](https://github.com/dotCMS/core/issues/23575)). So, the table my looks like this:

<img width="1792" alt="working" src="https://user-images.githubusercontent.com/72418962/209719021-a0e11bb3-4831-4521-85c8-17487ed1436f.png">

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_1f508cbf_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1
