### ISSUE TITLE
Allow filter by content types in the containers endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23443]
### Is your feature request related to a problem? Please describe.
As a developer, I want to be able to filter containers results by content types inside.

### Describe the solution you'd like
Allow to pass a queryparam with the content types variables to filter.

### Acceptance criteria
- [ ] Developer should be able to pass a query param to filter containers by content types
- [ ] The query param should be one or multiple content types variables

**Comment by fmontes** [comment]
Not working.

**Comment by zulqarnainvd** [comment]
![Screenshot from 2023-02-02 00-05-35](https://user-images.githubusercontent.com/113915849/216149172-f98ec227-972a-4d73-92d4-78a554310d44.png)

**Comment by zulqarnainvd** [comment]
When I change parameter and search from Widget it's throwing error. I also informed @hassan-mustafa-baig

**Comment by zulqarnainvd** [comment]
![Screenshot from 2023-02-02 13-43-57](https://user-images.githubusercontent.com/113915849/216275031-b8dcce87-ded9-439b-ac35-7b9f2607fbc5.png)
![Screenshot from 2023-02-02 13-44-40](https://user-images.githubusercontent.com/113915849/216275041-29ceeec3-3f06-469a-956e-c547b5019a09.png)

**Comment by zulqarnainvd** [comment]
[screen-capture (5).webm](https://user-images.githubusercontent.com/113915849/216622641-1df95b2e-ef4c-428b-bd69-2c004ca3765d.webm)

**Comment by zulqarnainvd** [comment]
@hassan-mustafa-baig I added a video above it is not filtering some of the content types.

**Comment by hassan-mustafa-baig** [comment]
> @hassan-mustafa-baig I added a video above it is not filtering some of the content types.

okay. I will check it with the content types that are not working as demonstrated by you

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/218574513-23581156-95f4-4e53-bc7c-77278685122b.mp4

**Comment by zulqarnainvd** [comment]
@fmontes Ack

**Comment by fmontes** [comment]
We can test the last comment now.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
Containers are now being filtered by the Content Types they can render.

Additional defect were found during IQA:
* https://github.com/dotCMS/core/issues/24163
* https://github.com/dotCMS/core/issues/24164

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_9ddae518_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
