### ISSUE TITLE
Filter does not work on the image selector for image fields

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#23449]
### Describe the bug
The filter search box in the image selector for image fields does not function. You can type into it but the results do not change.

Reproduced on: 22.03.2, 22.10.1

### To Reproduce
1. Open the image selector on an image field
2. Attempt to filter using the filter box

The results in the window will not change. 

### Expected behavior
The filter should work

### Acceptance criteria

- [ ]  We need to also be able to filter by folder
- [ ]  We need to show file assets and dotassets
- [ ]  Make dotassets be able to filter by folders as well (folder field)

**Comment by waqasakramdot** [comment]
Here one of our customers reported this issue https://dotcms.zendesk.com/agent/tickets/109231

**Comment by fmontes** [comment]
![image](https://user-images.githubusercontent.com/751424/218795394-41727985-5071-4594-99ab-db7b9b5683d8.png)

- [ ] We need to also be able to filter by folder
- [ ] We need to show file assets and dotassets
- [ ] Make dotassets be able to filter by folders as well (folder field)

**Comment by rjvelazco** [comment]
### Passed Internal QA

Docker image: `dotcms/dotcms:master_be0bf8fa`

**Comment by hassan-mustafa-baig** [comment]
Filter is working perfectly fine. I have tried to reproduce it on the master branch but I was unable to reproduce it. Let me share the evidence here

https://user-images.githubusercontent.com/111717530/220470097-e63b3c37-fe0e-4b06-9c63-b394fcda9a85.mp4


When I was trying to upload multiple files then it was basically replacing all with the last file therefore I am under the impression that multiple files upload is not supported yet

**Comment by rjvelazco** [comment]
Hey, @hassan-mustafa-baig! As I mentioned in my previous comment and in the video, the filter works with images, the problem starts when you create a `dotAsset` and upload an image


https://user-images.githubusercontent.com/72418962/220634436-eaf1af05-7c33-4d27-9b68-452eb882ca32.mov

**Comment by fmontes** [comment]
First PULL REQUEST: https://github.com/dotCMS/core/pull/24048

**Comment by hassan-mustafa-baig** [comment]
https://venturedive-plantiga.slack.com/files/U03TTHG6L6R/F04R2S962NN/screencast_2023-02-24_07_55_36.mp4

So the functionality is working fine and here is the evidence of the fix

**Comment by erickgonzalez** [comment]
another customer hitting this: https://dotcms.zendesk.com/agent/tickets/110261

**Comment by wezell** [comment]
@fmontes I was thinking about this fix over the weekend and there is another issue with it, it will not work unless the customer's data is using the content_as_json field.   In my mind, there are two ways to go from here.

1. Create a startup task that fires and runs in the background and updates every piece of content to use the `content_as_json` field.
2. Use elasticsearch to provide a final filter for the assets after initially filtering them by DB.

**Comment by fmontes** [comment]
@wezell I like number 2, sounds less prune to errors to me? cc: @jdotcms @jcastro-dotcms

**Comment by wezell** [comment]
#2 is going to be easier.  I started some non-working code on the plane, let me commit it.

**Comment by fmontes** [comment]
We need to work with this change as starting point:

https://github.com/dotCMS/core/compare/master...issue-23449-use-es-to-filter

**Comment by erickgonzalez** [comment]
Note to QA: please test with old assets (meaning that the `contentlet_as_json` is empty) if needed ask support for a customer data
