### ISSUE TITLE
Categories being removed from content items when updating content via CSV file upload

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#23440]
### Describe the bug
I tested on 5.3.8.10 this is a feature but from 22.03.XX when uploading multiple content items via CSV file upload, those content items will be stripped of their categories (unless keeping those columns in the CSV file upload).

### To Reproduce
1. Create test content type with categories as field
2. Create few contents let with categories e.g Age/Gender (Boyes, Girls)
3. Export those content lets as CSV
4. strip categories column
5: Import now these contents
6:Categories will be gone

### Expected behavior
Should be passed as lists:
- Any list -> we will overwrite them.
- Empty list -> will delete all entries.

If the column is not present -> will keep the same.

### Additional context
 Will quoted:
 "Our pattern with checking in content with Categories, Relationships is pretty simple.  Both of these properties should be passed in as lists.  So the rule is this - if you pass any list in, we overwrite what is there - and this includes an empty list, which should basically delete all entries.  If you do not include the category/relationship property, we should just maintain what was there previously."
 
 Related Ticket: https://dotcms.zendesk.com/agent/tickets/109228

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_c6c88d20_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1
