### ISSUE TITLE
Container save button enabled on edit

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23459]
### Describe the bug
When user edit a container, the "Save" button is enable even when the form hasn't changed.

### To Reproduce
1. Go to containers
2. Click on any containers (with tabs and code)
3. See the save button enabled.

### Expected behavior
It should only enable when the form changes.

### Acceptance criteria
- User should not be able to save the container if nothing has changed.

**Comment by zulqarnainvd** [comment]
@fmontes it's already fixed in this ticket. #23533

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/207437128-b16e0255-921f-4b00-802b-6ceb30d526e4.mp4

**Comment by fmontes** [comment]
https://user-images.githubusercontent.com/751424/207457236-3c4e5e6f-5264-4b0e-b5d8-fff1573aaddd.mp4

**Comment by hmoreras** [comment]
Working as expected: 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/31667212/209722868-3893423d-c82c-4905-99be-65e4d5ba0e3c.png">
