### ISSUE TITLE
Container when delete a content type tab it should focus on another

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23460]
### Is your feature request related to a problem? Please describe.
When the user is deleting a content type from the code tabs, it should focus on the previous or after.

### Describe the solution you'd like
We need to let the user focused on another tab is existed because it gets out of context.

If there is a previous tab we use a tab, if not, we use the next tab if there is no tab left we will have an "empty state" (design coming soon).

### Additional context
We need an empty state, I'll be working on this.

### Acceptance criteria
- Users should be able to remove tabs without losing focus of the code component.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker image: `master_e37e2c7f`

Tabs are focused based on the following criteria:
* If there's a previous tab, such a tab is selected.
* If there's NO previous tab, the next tab is selected.
* If there are NO tabs at all, a help message is displayed.
