### ISSUE TITLE
[UI] Being able to edit Experiment Variant name

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#23479]
Currently is not possible. If you need to rename, you would need to delete a create a new Variant. 

Proposed: 

![Screenshot 2022-12-01 at 11.15.53.png](https://images.zenhubusercontent.com/56e984726caf56c9d38dd540/240ecf87-8ace-4fb5-9c93-2eac3ab7bc94)

A edit pencil icon when the name is mouseovered, which displays the sidebar when clicked. 

Acceptance criteria:
* Being able to rename the variant 
* Automated tests

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23479?planning-poker) with Zenhub @freddyucv @oidacra

**Comment by dsilvam** [comment]
Needs work: it works only the first time. Further attempts result in infinite loading and no "save" icon. 
<img width="479" alt="Screenshot 2023-01-12 at 12 02 18" src="https://user-images.githubusercontent.com/1576794/212144575-3a706cee-4b53-49c8-9419-7a9e9bb55892.png">

**Comment by oidacra** [comment]
Details fixed with https://github.com/dotCMS/core/pull/23812

**Comment by dsilvam** [comment]
Passed Internal QA: Now it's working as expected. Multiple updates are taking effect.

**Comment by bryanboza** [comment]
UX: The enter key should save the changes, same as click in the save icon.

**Comment by oidacra** [comment]
Fixed with PR https://github.com/dotCMS/core/pull/23970

<img width="432" alt="Screenshot 2023-01-31 at 5 14 51 PM" src="https://user-images.githubusercontent.com/1909643/215895957-e08d4a93-d6b3-4587-9d63-bc3617908505.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/23970

**Comment by dsilvam** [comment]
Passed Internal QA: Saving on enter and proper name in success message.

**Comment by bryanboza** [comment]
We still needing some work here: 

- Now we are showing the name of the experiment instead the variant name, this when you are adding the variant, when you remove this we are showing the corresponding name 
![Image](https://user-images.githubusercontent.com/2641437/220732483-e3ea743b-9a03-490e-93f2-ba6ea7203564.png)

- We need to add a confirmation dialog before delete the varint, as we do in the GOALS, we need to be consistent with the delete behavior in all the portlet 
![Image](https://user-images.githubusercontent.com/2641437/220733504-23952b12-daf2-4502-abac-ea9e23081746.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
