### ISSUE TITLE
Task: Remove JSass and dependencies

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23475]
Static security scanners are currently flagging dotCMS installations because we ship with the apache commons text library which has a known vulnerability - text4shell.

Even though we are not susceptible to the vulnerability, the optics do not look good and will raise questions from our clients.  Removing jsass, which we no longer use, will remove the dependency.  The affected library is:

`org.apache.commons:commons-text:1.8`

This is what we look like to static security scanners:

![Screen Shot 2022-12-01 at 10 22 38 AM](https://user-images.githubusercontent.com/934364/205091298-9bbd57be-c115-4a83-b738-e0e2a3071ab4.png)

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker image: `23.01_a953eb1e_SNAPSHOT`

I verified that the JSASS library is no longer present in our libraries folder: `/srv/dotserver/tomcat-9.0.60/webapps/ROOT/WEB-INF/lib/` . Additionally, Docker Hub is no longer showing any Critical CVE alert for the specified image:

<img width="1283" alt="docker-verification" src="https://user-images.githubusercontent.com/8779585/207983512-066645cf-ecb1-4ddc-b92a-962c40c4ab6a.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker

**Comment by erickgonzalez** [comment]
Can't backport to 22.03 LTS since dotLibSassCompiler still uses it (migration to dart sass was in 22.09).
