### ISSUE TITLE
REST Resource for test data creation 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#23493]
Currently, our Postman tests use Bundles to import/create the data needed to test against. This worked for some time but it has brought a lot of issues every time we make changes in starter or in the PP process. 

The desired approach consist of writing a new endpoint to be called to create the test data. It needs to return a Map with the identifiers, names, etc created by the java code and to be used by the postman tests. 

@jdotcms please fill in the implementation details if you have them

**Comment by jdotcms** [comment]
Close b/c dupe https://github.com/dotCMS/core/issues/27693
