### ISSUE TITLE
Make Site Selector Show Selected Site Correctly

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23505]
In the Site Selector, there's a gray box on the site that isn't selected. Let's remove that bray box. 

<img width="352" alt="Screenshot 2022-12-05 at 12 26 28 PM" src="https://user-images.githubusercontent.com/114953617/205713794-ca7791d3-1d05-43f1-bda0-13cfa171e1c6.png">

Update by @fmontes 

### Problem
dotCMS has the concept of "default site" and to show that we are using the same state as hover, which is confusing and bad.

### Fix
Update the CSS and the HTML, so the default site is "bold" and have an `*` on the right side of the text.

**Comment by damen-dotcms** [comment]
That's a bad Stalebot. Bad!

**Comment by fmontes** [comment]
Put a star (or something) next to the default and remove the background.

**Comment by zulqarnainvd** [comment]
### **Passed Internal QA**

Branch: **Master**

https://user-images.githubusercontent.com/113915849/225002092-369a65a1-3b66-4433-a94e-59ad0ad6709e.webm

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **Master** // Local // macOS 13.0 // FF v111.0

*In need of QA in 23.04 release branch*

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.05_becff921_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
