### ISSUE TITLE
Users should be able to download the file in all supported types in the image editor.

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23500]
### Is your feature request related to a problem? Please describe.
Users should be able to download the file in all supported types in the image editor.
Users can download the file through URL in PNG, JPEGP But these options are not available in UI.
All options must be available.

### Describe the solution you'd like
PNG
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200
JPEG
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200/jpeg_q/65
WEBP
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200/webp_q/65
PNG
https://demo.dotcms.com/dA/d77576ce6e3a/200w
JPEG
https://demo.dotcms.com/dA/d77576ce6e3a/200w/jpeg/80
JPEGP
https://demo.dotcms.com/dA/d77576ce6e3a/200w/jpegp/80
WEBP
https://demo.dotcms.com/dA/d77576ce6e3a/200w/webp/80We

![Screenshot from 2022-12-05 15-56-47](https://user-images.githubusercontent.com/103441252/205620651-ed9f95f1-9bdf-497e-b3b0-7952dd0fb096.png)

**Comment by wezell** [comment]
dupe #22891
