### ISSUE TITLE
Make Navigation Item Names Consistently Plural 

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23504]
We have a bunch of places in the navigation where the Item Names are inconsistent.

Webinar should be Webinars

<img width="282" alt="Screenshot 2022-12-05 at 12 23 02 PM" src="https://user-images.githubusercontent.com/114953617/205713326-0bba5901-c924-43c7-99f1-8e7eea29f24f.png">

Images, Videos, File Assets

<img width="284" alt="Screenshot 2022-12-05 at 12 23 07 PM" src="https://user-images.githubusercontent.com/114953617/205713376-44812c15-4bb3-46ac-82ec-f38e845a7a9a.png">

Customers, Testimonials

<img width="282" alt="Screenshot 2022-12-05 at 12 23 13 PM" src="https://user-images.githubusercontent.com/114953617/205713447-26b7b072-401e-45ed-9e6c-2499f19560fb.png">

**Comment by fmontes** [comment]
We need to do this in the starter
