### ISSUE TITLE
We need to register extra data in each jitsu event

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23526]
### Is your feature request related to a problem? Please describe.
We need to register some extra values like: experiment's id, variant's name use by the user and current lookBackWindows values, language and persona, this values are going to be use later when we gather the data from cubejs.

### Describe the solution you'd like
Some extra values like lookbackWindows, experiment's id, variant's name need to be set in the bowser because we have all this values into the local storage, I think the best way to do this is using this: https://jitsu.com/docs/sending-data/js-sdk/snippet#persistent-properties 

In the case of language and persona we need to set these into the server, right here:

https://github.com/dotCMS/core/blob/0addf9cd0e8e0951b628185c17e3417c07d129ad/dotCMS/src/main/java/com/dotcms/jitsu/EventLogWebInterceptor.java#L107

### Acceptance criteria
- lookbackWindows, experiments'id and variant's name should be register in any jitsu event

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23526?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
Note to QA: 

-  Start the internal-infrastructure, dotCMS and config the Analytics App, how tell here:

https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641

- Create / Start an Experiment, you are going to add goal and start it using the end point directly, for now it is not allow to do it using the UI.
- Navigate for the Front End.
- Check if you have new Event using cubeJS, cubeJS is started in the 4001 port.

Note: I think is easier if you start with the full starter.

**Comment by victoralfaro-dotcms** [comment]
Experiment after update goal:
```
{
    "entity": {
        "createdBy": "dotcms.org.1",
        "creationDate": 1674066126068,
        "description": "This is a Dinho experiment",
        "goals": {
            "primary": {
                "conditions": [
                    {
                        "operator": "EQUALS",
                        "parameter": "url",
                        "value": "thank-you"
                    },
                    {
                        "operator": "EQUALS",
                        "parameter": "referrer",
                        "value": "home"
                    }
                ],
                "name": "Reach thank-you page",
                "type": "REACH_PAGE"
            }
        },
        "id": "e44daa18-03fb-4404-8dd5-c8e903d955ea",
        "identifier": "e44daa18-03fb-4404-8dd5-c8e903d955ea",
        "lastModifiedBy": "dotcms.org.1",
        "lookbackWindow": 10,
        "modDate": 1674066728455,
        "name": "Dinho",
        "owner": "dotcms.org.1",
        "pageId": "e5f131d2-1952-4596-bbbf-28fb28021b68",
        "permissionId": "e44daa18-03fb-4404-8dd5-c8e903d955ea",
        "permissionType": "com.dotcms.experiments.model.Experiment",
        "scheduling": null,
        "status": "DRAFT",
        "targetingConditions": [],
        "trafficAllocation": 100.0,
        "trafficProportion": {
            "type": "SPLIT_EVENLY",
            "variants": [
                {
                    "id": "dotexperiment-e44daa1803-variant-1",
                    "name": "Original",
                    "url": "/activities/activity-detail-page?variantName=dotexperiment-e44daa1803-variant-1",
                    "weight": 50.0
                },
                {
                    "id": "dotexperiment-e44daa1803-variant-2",
                    "name": "variant_1",
                    "url": "/activities/activity-detail-page?variantName=dotexperiment-e44daa1803-variant-2",
                    "weight": 50.0
                }
            ]
        }
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "permissions": []
}
```

**Comment by bryanboza** [comment]
This si enough QA for now, we need to wait more advances here to allow to test it via UI
