### ISSUE TITLE
Clean up experimet_data item in the Local Storage

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23530]
### Is your feature request related to a problem? Please describe.
Right now we are storage a expriment_data item into the local storage with all the information about the Experiment where the user is into, this object look like:

```
{
    experiments: [
        {
             id: "4872c761-c9e1-443f-ae9c-a9cc0f2e2c42", 
             name: "Testing Experiment 2", 
             pageUrl: "/blog/index",
             variant: {
                 name:  "dotexperiment-4872c761c9-variant-2"
                 url: "/blog/index?variantName=dotexperiment-4872c761c9-variant-2"
             }
        }
     ]
     includedExperimentIds: ["4872c761-c9e1-443f-ae9c-a9cc0f2e2c42"]
}
```

Where:
- experiments contains the experiments where the user is into.
- includedExperimentIds: the Running experiments the last time this user hit the shouldBeIncluded end point.

We need to clean up this object and rib off the experiment that was eneded.

### Describe the solution you'd like

Right now we include into the page's HTML code a list of the current experiment Running.

https://github.com/dotCMS/core/blob/b7337cbeb5ecc9eb574df41b725f8c2449daa0cc/dotCMS/src/main/resources/experiment/js/init_script.js#L2

https://github.com/dotCMS/core/blob/97f295724561417c5cf0bf82d89a5854f62ca41f/dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPIImpl.java#L607

We use this list to know when we need to hit the shouldBeIncluded end point agian.

but now we can use this list to know if a experiment into experiment_data was ended, I mean if a Experiment's id is into the experiment_data  but it is not into the currant Running experiment list then we can rib this Experiment off the experiment_data.

### Acceptance criteria
- Rip a Ended Experiment off the experiment_data automatically
- Remove the code to create the Experiment's cookies, we are not going to need them anymore
https://github.com/dotCMS/core/blob/97f295724561417c5cf0bf82d89a5854f62ca41f/dotCMS/src/main/java/com/dotcms/experiments/business/web/ExperimentWebAPIImpl.java#L91

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23530?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
Note to QA:

- Start dotcms with the full starter
- Create new Experiment in the /index Page
- Create second Experiment in the /index/blog page
- Create third Experiment in the contact-us/thank-you page
- Logout to the Backend.
- Go to localhost:8080/index, check the localStorage you should not have the experiment_data there.
- Start the first Experiment and go to localhost:8080/index using the front end. Now you should have the experiment_data item into the localStorage with one item in the experiment and included list.
- Start the others two Experiment. and go to the localhost:8080/index again you should still have just one experiment there 
- Now close the tab and go to  localhost:8080/index again, Now you should have the experiment_data item into the localStorage with 3 item in the experiment and included list.
- Now one by one Stop the Experiment after Stop one, close the tab logout to the backend and finally go again to the localhost:8080/index page each time The Experiment ended should be removed from the experiment_data Item in both list: experiments and included

Note: You need to use the End point directly to start/stop an Experiment and set a Goal to an Experiment.

**Comment by dsilvam** [comment]
Passed Internal QA: Behaving exactly like described steps.
