### ISSUE TITLE
Protect Default and Original Variants

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23536]
The default variant should not be deletable or modifiable. 
The original variant of an Experiment should not be deletable or modifiable. 

Acceptance criteria
* Integration tests 
* Failure when attempting to delete the Default Variant via Java API
* Failure when attempting to delete the Original Variant of an Experiment via REST or Java API.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.02 // Docker // FF. Now we are unable to delete default variants. 

Pending to add the postman test to pass QA....

**Comment by dsilvam** [comment]
Passed Internal QA: Postman already in master and passing: 
```[Iteration: 1 - deleteOriginalVariant_shouldFail](https://raw.githack.com/dotCMS/test-results/master/projects/core/postman/reports/html/Experiments_Resource.postman_collection.html#)```
```Response Code:405 - Method Not Allowed```

**Comment by bryanboza** [comment]
Fixed, tested on release 23.03 // Docker // FF 



![Image](https://user-images.githubusercontent.com/2641437/221027268-b8a24bac-d408-4f15-a6e6-bd8946e7bbc4.png)

Now we are unable to delete the original variant
