### ISSUE TITLE
Identify the issue which causes 6 hour postman runs and remove the condition OR remove the test - whatever easiest

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#23538]
### Acceptance criteria
- Use
- Bullet
- Points

**Comment by jcastro-dotcms** [comment]
The fix for this issue was added to this PR: https://github.com/dotCMS/core/pull/23763

It includes my initial code fixes along with Victor's changes and his improvements on parallelizing the execution of Postman Test.
