### ISSUE TITLE
[UI] Add Goal 

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23537]
### Is your feature request related to a problem? Please describe.
As a user can select a goal for the experiment

- REACH_PAGE
- BOUNCE_RATE

 `PATCH {{serverURL}}/api/v1/experiments/{{experimentId}}`
`{
    "goals": {
        "primary": {
            "name": "Reach thank-you page",
            "type": "REACH_PAGE",
            "conditions": [
                {
                    "parameter": "url",
                    "operator": "EQUALS",
                    "value": "thank-you"
                },
                {
                    "parameter": "referrer",
                    "operator": "EQUALS",
                    "value": "home"
                }
            ]
        }
    }
}`

### Describe the solution you'd like
Use a sidebar to show the 2 options

N/A

### Additional context
N/A

### Acceptance criteria
- Click on + set experiment Goal.
- Select the Goal Type
![Screenshot 2022-12-19 at 1.59.16 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/69ba80d8-1b25-4fee-bbc6-4fb8a46fb0db)

- Update the view
![image.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/2a3ef99a-7e5a-47b0-8dc4-97431c537ea1)

**Comment by dsilvam** [comment]
Needs work: 
1. Remove the text before the list of Goals to choose from. 
2. Modify the "Page View" goal option to be 
"Reach Page
Whether the user visits a particular page during her session"

**Comment by oidacra** [comment]
Needs work:
- Remove the text before the list of Goals to choose from. **Done!**
-Modify the "Page View" goal option to be
- "Reach Page **Done!**
- Whether the user visits a particular page during her session." **Done!**
- Modify the "Bounce Rate" goal description to be:
- "Percentage of visitors whose last visited page of the session was this page, without any activity while on it."**Done!**

**Comment by oidacra** [comment]
https://github.com/dotCMS/core/pull/23819

**Comment by dsilvam** [comment]
Passed Internal QA: Requested modifications in place. Working as expected.

**Comment by bryanboza** [comment]
- We are not resolving keys `experiments.goal.bounce_rate`

![Image](https://user-images.githubusercontent.com/2641437/214426007-2c7d55ed-5ccc-46be-8cf7-9da8676766a8.png)

**Comment by oidacra** [comment]
Fixed with PR: https://github.com/dotCMS/core/pull/23969

<img width="487" alt="Screenshot 2023-01-31 at 4 52 29 PM" src="https://user-images.githubusercontent.com/1909643/215892001-5b4a6a27-4d65-43fb-89dc-6dcb7cc98066.png">

**Comment by dsilvam** [comment]
Passed Internal QA: Showing the proper text for Bounce Rate

**Comment by bryanboza** [comment]
We are showing a disabled generic element when you try to add a new goal, we need to hide this 

![Image](https://user-images.githubusercontent.com/2641437/220725020-2d36e3e4-d38e-49f7-bdf6-7baa63e00b18.png)

**Comment by oidacra** [comment]
With https://github.com/dotCMS/core/issues/23847 will disappear.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
