### ISSUE TITLE
Task: Upgrade Postgres JDBC Driver

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23531]
The PostgreSQL jdbc driver dotCMS ships with has a sql injection vulnerability:
https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-2970521

Note: dotCMS is **NOT vulnerable** to this issue as we not use the affected code `ResultSet.refreshRow()` anywhere in dotCMS.  This update is for optics and to appease the static security scanning gods.

**Comment by wezell** [comment]
Additionally, I removed the unused MySQL and Oracle drivers - which is why this is marked as a breaking change.

If customers are relying the MySQL or Oracle drivers to connect to their 3rd party DB, this will no longer work.  Customers will need to provide their own drivers in their plugins.

**Comment by bryanboza** [comment]
According to the branch code we have the change 

```
    compileOnly (group: 'org.postgresql', name: 'postgresql', version: '42.5.1') {
        transitive = false
    }
```

We need to run a sanity check to make sure we don't break anything with this change
