### ISSUE TITLE
Make show archive a checkbox on Browser screen

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23547]
[![Screenshot_2022-12-08_17-13-20.png](https://mrkr.io/s/63921b30890bb8bcf39dfffb/2)](https://mrkr.io/s/63921b30890bb8bcf39dfffb/0)

Show Archive on the Browser screen is inconsistent with the rest of the backend screens. It should be changed to a checkbox and aligned left.

## Steps to Reproduce
See screenshot

## Acceptance Criteria
Make Consistent with Template screen

## Wireframes / Designs / Prototypes
See screenshote

## Sub-Tasks

---

**Reported by:** Jason A Smith (jason@dotcms.com)

**Source URL:** [https://local.dotcms.site:8443/dotAdmin/#/c/site-browser](https://local.dotcms.site:8443/dotAdmin/#/c/site-browser)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63921b30890bb8bcf39dfffe_58cba456ff7bebde?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3200 x 1333</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1666 x 1064</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by hmoreras** [comment]
Dojo Theme PR: https://github.com/dotCMS/dotcms-dojo-theme/pull/89

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_288ffc92_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.1
