### ISSUE TITLE
Use the right query params name to render the page when change the render Mode

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23543]
### Is your feature request related to a problem? Please describe.
Right now when we are into a Experiment in change between the different Mode (EDIT and PREVIEW) we are concatenating a variationName query paras into the URL, this name is wrong the right one  is variantName.
 
### Describe the solution you'd like
We need to change the query params name in all the places where we are using it.

### Acceptance criteria
- Render the Page with the specific Variant when we switch between mode in the Edit Page Portlet.
- Render the Page with the specific Variant after save.

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23543?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/23858
