### ISSUE TITLE
Users are unable to search with complete email addresses in global search field in content search screen

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23541]
### Describe the bug
Users are unable to search with complete email addresses in the global search field in the content search screen.
Whenever a user enters the '@' character in a search, they don't get desired results.
However, the search works fine with a complete email address when a user enters an email into an email field instead of a search field.
Reproduced: 22.12
Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/109355

### To Reproduce
1. log in to the demo site and create a test content type with a text field.
2. Make sure the text field is user searchable.
3. Create a couple of contentlets and enter emails address into the text field.
4. Now try to search by adding a complete email address into the search field in the content search screen.
5. See the result.

### Expected behavior
Search should return results based on the email entered into the search field.

### Screenshots
![Screenshot from 2022-12-08 18-28-41](https://user-images.githubusercontent.com/103441252/206460303-e0ba9725-6ec3-4480-bd16-3741e14c60cf.png)
![Screenshot from 2022-12-08 18-28-53](https://user-images.githubusercontent.com/103441252/206460314-250801f7-8847-4b25-863d-e7d475639ac3.png)
![Screenshot from 2022-12-08 18-29-05](https://user-images.githubusercontent.com/103441252/206460318-226f97ed-d1a9-473c-b534-09a2c95a5f5b.png)
![Screenshot from 2022-12-08 18-29-18](https://user-images.githubusercontent.com/103441252/206460327-dcce50e2-857b-4563-8304-fd646863d97c.png)

**Comment by wezell** [comment]
This is because the field is tokenized - you would need to set a `esCustomMapping` as keyword for the field to index it without tokenization
