### ISSUE TITLE
Add metadata information to the dotAsset object

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23552]
### Is your feature request related to a problem? Please describe.
As a developer, I want to be able to have access to all the metadata information of the file itself.

### Describe the solution you'd like
The `dotAssets` are just regular content types with a binary field, that field holds a file in which we have metadata, we need to expose that metadata in the API responses, but not only for dotAssets but for all content types with a binary field.

This is already working in Graphql, but we need it in:

1. Page API
2. Content API
3. Elastic Search API

### Acceptance criteria
- Add binary field metadata information.

**Comment by bryanboza** [comment]
Hey guys, we need to add some postman tests in order to validate this new functionality in each one of the mentioned endpoints

**Comment by fmontes** [comment]
Postman test added.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF
