### ISSUE TITLE
Date Time field should highlight today's date

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23551]
[![Screenshot_2022-12-08_18-12-25.png](https://mrkr.io/s/639229093f6c783738e3340a/2)](https://mrkr.io/s/639229093f6c783738e3340a/0)

## Problem Statement
The calendar tool doesn't highlight todays date.

## Acceptance Criteria
Today's date should be highlighted on the calendar or be selected by default.

## Sub-Tasks

---

**Reported by:** Jason A Smith (jason@dotcms.com)

**Source URL:** [https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list](https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/639229093f6c783738e3340d_6f43f28defb0a5ee?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3200 x 1333</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1666 x 1064</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by wezell** [comment]
@fishsmith you can default to today by setting the default value for the field as "now"

**Comment by wezell** [comment]
@fishsmith and the class to style "todays date" is `dijitCalendarCurrentDate`

**Comment by hmoreras** [comment]
Dojo Theme PR: https://github.com/dotCMS/dotcms-dojo-theme/pull/90

**Comment by bryanboza** [comment]
![image](https://user-images.githubusercontent.com/2641437/210834221-ea84cbe7-96ed-4203-ab27-7cdb1335d5b1.png)
