### ISSUE TITLE
Can't close query dialog on content search screen

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23554]
[![Screenshot_2022-12-08_21-24-18.png](https://mrkr.io/s/63925602fe339a194e18b1d6/2)](https://mrkr.io/s/63925602fe339a194e18b1d6/0)

## Problem Statement
Can't close query dialog on content search screen

## Steps to Reproduce
1. Do a content search
2. Show the Query
3. Try to close the dialog

## Acceptance Criteria
We should add a close button, plus have it close when you click off of it

See screenshot

## Sub-Tasks

---

**Reported by:** Jason A Smith (jason@dotcms.com)

**Source URL:** [https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list](https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63925602fe339a194e18b1d9_d0b23091c14e38c3?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3200 x 1333</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1466 x 973</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
There is already an issue being working on this: https://github.com/dotCMS/core/issues/23554

**Comment by fmontes** [comment]
The fix was bringing back the title.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.02 // Docker // FF
