### ISSUE TITLE
Relate Content screen thumbnails are not scaled correctly 

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23553]
[![Screenshot_2022-12-08_20-18-17.png](https://mrkr.io/s/6392468927507e7e77984acc/2)](https://mrkr.io/s/6392468927507e7e77984acc/0)

## Problem Statement
Relate Content screen thumbnails are not scaled correctly 

## Steps to Reproduce
See screenshot

## Acceptance Criteria
Image should be cropped not stretched

## Sub-Tasks

---

**Reported by:** Jason A Smith (jason@dotcms.com)

**Source URL:** [https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list/d9355094-cc5b-4754-8301-a27d6bf3a902](https://local.dotcms.site:8443/dotAdmin/#/c/c_Blogs_list/d9355094-cc5b-4754-8301-a27d6bf3a902)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6392468927507e7e77984acf_e2c465caf54e77f7?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3200 x 1333</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1666 x 1007</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Can't repro
