### ISSUE TITLE
Build and deploy frontend locally no npm

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23556]
### Is your feature request related to a problem? Please describe.
Since we have a monorepo with the Frontend and the Backend there is no need to use npm registry to publish and deploy dotCMS angular app.

### Describe the solution you'd like
Build the angular app using npm and nx and put the files in the tomcat folder.

**Comment by wezell** [comment]
Also includes these two commits eea87ee39fd1d20f896ef9863451b49439f1a13a   and 06d59b578d6997629e728bead07faff0b355edd9
