### ISSUE TITLE
Block editor: Add styles to starter to support table

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23575]
### Is your feature request related to a problem? Please describe.
As a strakeholder I want our demo to look the best possible and show good the content of a block editor with a table

### Describe the solution you'd like
1. Add styles to the full starter to support table content
2. Add a table to one of the blog posts in the block editor field

### Describe alternatives you've considered
We might need to add default table styles in the theme

### Additional context
Make sure don't break tables in other contents

### Acceptance criteria
- Show off a table inside a blog post block editor fields

**Comment by hmoreras** [comment]
**Documentation**

To create a custom table block, just create a `table.vtl` file under `application/vtl/blog/blocks` an use this as an example: 

`<table>
 #foreach($row in $item.content)
  <tr>
     #foreach($cell in $row.content)
        #if( $cell.type == "tableHeader" )
            <th colspan="$!cell.attrs.colspan" rowspan="$!cell.attrs.rowspan" colwidth="$!cell.attrs.rowspan" >$cell.type</th>
        #elseif($cell.type == "tableCell" )
            <td colspan="$!cell.attrs.colspan" rowspan="$!cell.attrs.rowspan" colwidth="$!cell.attrs.rowspan">$cell.type</td>
        #end
     #end
  </tr>
 #end
</table>`

**Comment by hmoreras** [comment]
We need to add the following basic rules to  `application/themes/travel/css/custom-styles/components/_tables.scss`

`.table-block {
  table-layout: fixed;
  width: 100%;
  
  th {
    padding: $table-condensed-cell-padding;
    border: 1px solid $table-border-color;
    background: $table-bg;
  }
  
  td {
    padding: $table-condensed-cell-padding;
    border: 1px solid $table-border-color;
  }
  
  p {
    margin-bottom: 0px
  }
}

.section-blog-post .table-block p:first-of-type {
  font-size: 1.2em;
} `

**Comment by rjvelazco** [comment]
It's working properly.

Tested on [starter:8443](https://starter.dotcms.com:8443/)

<img width="1792" alt="table-styles" src="https://user-images.githubusercontent.com/72418962/209716596-95bf7f63-1617-47fc-aeba-3af1ef3590d8.png">

**Comment by josemejias07** [comment]
**Approved QA** - Tested on https://starter.dotcms.com:8443 // Docker // macOS 13.0 // FF v108.0.1
