### ISSUE TITLE
Containers: On "save" redirect to list

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23607]
### Describe the bug
When user edit a container and hit "Save" is not redirecting to list.

### To Reproduce
1. Edit a container
2. Hit "Save" button
3. See that redirect to list not working

### Expected behavior
When user edit a container and save, it should redirect to list.

### Screenshots
https://user-images.githubusercontent.com/751424/208225990-4ac281fb-cf3e-4ea1-b58d-5b0d72cdaa19.mp4

### Acceptance criteria
- When user edit a container and save, it should redirect to list.

**Comment by hmoreras** [comment]
is now redirecting. `docker image: master_e86506e1`
