### ISSUE TITLE
CS: Reorganize top bar

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23601]
### Is your feature request related to a problem? Please describe.
As a stakeholder, I would like to rearrange the top bard to provide a better user experience.

### Mocks
[Figma](https://www.figma.com/file/y4zaZ1287q2YClfYBzmPbO/Portlets-%2F-Content-Search?node-id=1%3A209&t=8aeIH207nJ2wQCw5-1)

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/751424/208220357-668ee5d1-5a34-493e-83e3-9d246394036b.png">

### Acceptance criteria
- [x] Global search field to the center of the list/card view
- [x] Workflow actions button to the right
- [x] Card/list view buttons to the left

**Comment by wezell** [comment]
- make sure the search box gets focus on page enter

**Comment by fmontes** [comment]
@josemejias07 

> After clicking on ' Clear ' the focus should return to the search field.
Nice to have, not in this scope, create a issue for it.

> should we have remove the left menu as it shows on the mock up
No, the mock wasn't focused 1-to-1 it was just showing what needs to be changed.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_c6c88d20_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1
