### ISSUE TITLE
CS: Research to bring file tree as a column

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23602]
### Problem Statement

N.A

### Steps to Reproduce

N.A

### Acceptance Criteria

N.A

### dotCMS Version

N.A

### Proposed Objective

N.A

### Proposed Priority

N.A

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

N.A

### Assumptions & Initiation Needs

N.A

### Sub-Tasks & Estimates

N.A

**Comment by wezell** [comment]
We should also look at replacing some of the legacy BrowserAjax calls with BrowserResource calls

**Comment by fmontes** [comment]
We need to show the system host.

**Comment by fmontes** [comment]
Close to create a new one with the new template.
