### ISSUE TITLE
When edit mode is loading the palette UI isbroken

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23619]
### Describe the bug
When user goes to "Edit mode" the lading indicator in the palette shows twice with the input text field

### To Reproduce
1. Go to edit a page
2. Click on "Edit" tab
3. See error

### Expected behavior
It should only show the loading indicator in the middle of the panel and nothing else.

### Screenshots
<img width="282" alt="Screenshot 2022-12-20 at 08 17 22" src="https://user-images.githubusercontent.com/751424/208687971-a16ad7ad-0ae5-4f35-942f-59d7b2ec4dad.png">

### Acceptance criteria
- User should only see the ONE loading indicator in the palette while loading the content types.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.01_288ffc92_SNAPSHOT** // Docker // macOS 13.0 // FF v108.0.2
