### ISSUE TITLE
[UI] Delete Goal

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23612]
### Is your feature request related to a problem? Please describe.
Add three dots menu to the card of the selected goal.

![Screenshot 2022-12-19 at 2.02.05 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/f33b47bb-04d3-4406-897c-2b633b296f84)

### Describe the solution you'd like
Show an option of removing the goal

### Acceptance criteria
- Add a Goal
- With the menu of 3 dots, remove it
- If the card does not have a goal, the title does not show the green check.

```
@DELETE
@Path("/{experimentId}/goals/primary")

**Comment by dsilvam** [comment]
Passed Internal QA: Deleting Goal working as expected.

**Comment by bryanboza** [comment]
We need some work here: 

- We need to be consistent with the delete button (experiments have a delete button, here we have an icon, also both should have red color) 
- We are not resolving keys `experiments.goal.bounce_rate`
- Are need to fix the grammar in the confirmation dialog  “Are you want to delete this goal?”
Maybe
“Do you want to delete this goal?” or
“Are you sure you want to delete this goal?”

![image](https://user-images.githubusercontent.com/2641437/214389668-079a112f-14ce-4c27-997f-43a02bc73c7d.png)

**Comment by oidacra** [comment]
- We need to be consistent with the delete button (experiments have a delete button, here we have an icon, also both should have red color) will be resolver by https://github.com/dotCMS/core/issues/23968

**Comment by oidacra** [comment]
All comments fixed with PR: https://github.com/dotCMS/core/pull/23969
<img width="358" alt="Screenshot 2023-01-31 at 4 40 52 PM" src="https://user-images.githubusercontent.com/1909643/215891258-2f45f894-0ef7-4ac4-bd68-43df226f60a0.png">

**Comment by dsilvam** [comment]
Passed Internal QA: Confirm dialog for deleting shows proper message and buttons. The delete icon was left for another card.

**Comment by bryanboza** [comment]
- We need to add a confirmation dialog before delete the varint, as we do in the GOALS, we need to be consistent with the delete behavior in all the portlet 
![Image](https://user-images.githubusercontent.com/2641437/220733504-23952b12-daf2-4502-abac-ea9e23081746.png)
