### ISSUE TITLE
[BE] Change Split Traffic

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23623]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/31667212/217646772-5764cc51-a3d4-443c-985b-82cba8858f75.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/31667212/217646856-102f3357-a69a-4b81-a1ff-96256433fdcc.png">

**Comment by oidacra** [comment]
@freddyucv @dsilvam please add the endpoint to do this.

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/24113

**Comment by hmoreras** [comment]
QA: Traffic split can be edited when the experiment is draft. ca be either evenly split or custom split in this case the sum of all the variants must be 100. otherwise will throw an error.

**Comment by freddyucv** [comment]
**Need Works:** If you try to save a values that sum more than 100% like:

Variant 1: 100%
Variant 2: 50%

You got the follow error after click the "Done" button

<img width="452" alt="Screen Shot 2023-03-01 at 09 38 20" src="https://user-images.githubusercontent.com/10408015/222190822-4fa6c4cc-e112-4b55-8d32-bb24d9323129.png">

it is not a friendly message also I thin we should show a error message and disabled the "Done" button and even not sent the request to the Backend

**Comment by wezell** [comment]
We should not allow invalid percentages to be saved - or if we do, then
they become relative, e.g.
100%/50% become 66% /  33%.  Whatever makes us more robust and less error
prone.

**Comment by hmoreras** [comment]
*QA*: two decimals are allowed with traffic custom split. the sum of all the weights must be between 99,5 ( we will round up to 100 ) to 100, otherwise will be an invalid value, and the form will be invalid 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/31667212/224065769-62bf502c-bfd3-4f62-a5b0-6dd7abcf65c1.png">

**Comment by freddyucv** [comment]
**Needs Work**: I think is better do the validation into the onChange Events

**Comment by bryanboza** [comment]
We need some work here: 

- When you add a new variant the first time we split the % automatically to 50/50, but after this if you remove the variable and add a new one again, we are not recalculating this and we are living that in 100/0 
- 

https://user-images.githubusercontent.com/2641437/231514619-3a5b587e-bb03-4ff4-bfd3-a6c71dabe93f.mov

**Comment by dsilvam** [comment]
Passed Internal QA. This is working on master.

**Comment by bryanboza** [comment]
This still happening on release-23.06. Please we need to do internal after send again to QA

**Comment by hmoreras** [comment]
This is working as expected on master,  added to next release
https://github.com/dotCMS/core/assets/31667212/bc55aae7-335b-459f-b9ac-acd91b816391

**Comment by bryanboza** [comment]
Tested on the last image of master and this is happening again, we need to double check

**Comment by dsilvam** [comment]
Needs work: this happens after doing the custom splitting. When you do a custom split, then remove a variant, and add a new one we are not splitting anymore.

**Comment by freddyDOTCMS** [comment]
Pass IQA:

The fixed here was: When you have a" Custom Split" and remove all the Variants then the Split come back automatically to "Split Evenly", so when you add a new Variant we are splitting again.

However we can still have 0% of percentages to one Variant with the follow steps:

1. Create a Variant.
2. Change to "Custom Split".
3. Add a new Variant and the Percentage to the new one is going to be 0, that is ok because the Split is Custom

**Comment by bryanboza** [comment]
We need some work here, since we are allowing decimals, this is accepting just the comma (,) sign to accept decimals, we need to set this by the locale of the local environment, it can change between comma and dot ("," & ".")

**Comment by dsilvam** [comment]
@bryanboza that's a different issue. Stated issue on the description/video was solved. Please do not count it as "Needs Work" and remove the label and mark as Passed if that's the case.

**Comment by dsilvam** [comment]
@bryanboza 
* "Needs Work" removed. 
* Sent back to QA Backlog. 
Please update in the report.

**Comment by bryanboza** [comment]
The SUM of the numbers should be always 100%. Right now we are able to assign % more than 100%

![Image](https://github.com/dotCMS/core/assets/2641437/bd30853c-475a-4d1b-895f-fda0bf1499c5)

**Comment by john-thomas-dotcms** [comment]
This card is completed.  The additional cases were moved into separate cards.

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected. 

The extra case has been moved to a new card: https://github.com/dotCMS/core/issues/26961
