### ISSUE TITLE
Content type edit button not showing the icon

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23639]
[![Screenshot_2022-12-21_15-37-21.png](https://mrkr.io/s/63a32831d405eeeae6f5a2c0/2)](https://mrkr.io/s/63a32831d405eeeae6f5a2c0/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/1d7ed8c7a69d47cbecacca9f41d56f18](https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/1d7ed8c7a69d47cbecacca9f41d56f18)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a32831d405eeeae6f5a2c3_eff7df7b2e90297e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Yes it is, the shadow might makes you feel differente.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/751424/210644521-a7b285e5-ac8d-4766-8f6f-581109489670.png">

**Comment by Melissa-dotCMS** [comment]
I don't know if the problem is in the container of the text, maybe it is bigger and it's not hogging the text, or maybe the text is left aligned


![Image](https://user-images.githubusercontent.com/119896467/212979627-b5ae45d3-6efa-4ec5-8922-67f03a68dba4.png)

**Comment by fmontes** [comment]
The pen icon is not showing
