### ISSUE TITLE
This dropdown is not consistent with the rest of the dropdowns

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23634]
[![Screenshot_2022-12-21_15-20-04.png](https://mrkr.io/s/63a3242451769ed1090fc343/2)](https://mrkr.io/s/63a3242451769ed1090fc343/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content](https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a3242451769ed1090fc346_c912a49b3f444b2c?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Is a web component, not sure if is going to be easy to fix, let's do research.

**Comment by fmontes** [comment]
![Image](https://user-images.githubusercontent.com/751424/213021126-fdfc11d6-44e6-4ec7-8853-a1de5545b562.png)
