### ISSUE TITLE
1- If the user sets the Default Action to "Publish" it should allow them to set the Publish Date field (Right now is desabled). 2- The "Publish Date Field" should be hidden when the "Default Action" is not set to Publish.

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23636]
[![Screenshot_2022-12-21_15-29-33.png](https://mrkr.io/s/63a3265de2b39f43a40b2024/2)](https://mrkr.io/s/63a3265de2b39f43a40b2024/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content](https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a3265de2b39f43a40b2027_845378b983c798a3?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Same, we need to talk about this approach globally.
