### ISSUE TITLE
The close icon should not exist on a dropdown selector

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23637]
[![Screenshot_2022-12-21_15-31-12.png](https://mrkr.io/s/63a326c0c5c441fe6b4f6f91/2)](https://mrkr.io/s/63a326c0c5c441fe6b4f6f91/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content](https://demo.dotcms.com/dotAdmin/#/content-types-angular/create/content)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a326c0c5c441fe6b4f6f94_103883a6b539f10c?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
In this case, yes, because we want the user to be able to clear the value.
