### ISSUE TITLE
Should not appear if disabled

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23641]
[![Screenshot_2022-12-21_17-32-27.png](https://mrkr.io/s/63a3432b41aae5d2212f0286/2)](https://mrkr.io/s/63a3432b41aae5d2212f0286/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8](https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a3432b41aae5d2212f0289_be6b6ec257889b19?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Same case as History and Permissions, we needs to make the call globally.
