### ISSUE TITLE
Content type fields columns breaking in smaller screens

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23644]
Cards of images should be responsive to the size of the column, if the user sets the 4-column row, and add 3 images, the 4th one is squished to a minimum size, making it hard to drag and drop, understand the text, and even find the column.

[![Screenshot_2022-12-21_17-39-37.png](https://mrkr.io/s/63a344d9e2b39f43a40b58a5/2)](https://mrkr.io/s/63a344d9e2b39f43a40b58a5/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8](https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a344d9e2b39f43a40b58a8_3ac80a309f857788?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Known issue: https://github.com/dotCMS/core/issues/23816

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.02_3220636c_SNAPSHOT** // Docker // macOS 13.0 // FF v109

Top menu needs the same fix as the content fields

![Screenshot 2023-01-23 at 11 12 42 AM](https://user-images.githubusercontent.com/110418590/214107804-3e1b1d9a-3591-4adc-9168-14a9e8721fbd.png)

**Comment by fmontes** [comment]
Not related with this issue, create a new issue for this.

**Comment by bryanboza** [comment]
Hey @josemejias07 , I think this is specific for the field columns. But of course we need to fix that too, If you want create a new card and associate to this one. 

If the columns thing looks better, we can pass this one for now.

**Comment by josemejias07** [comment]
Related to #23891
