### ISSUE TITLE
Space in between not consistent

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23642]
[![Screenshot_2022-12-21_17-34-04.png](https://mrkr.io/s/63a3438c824de788cae0a1a2/2)](https://mrkr.io/s/63a3438c824de788cae0a1a2/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8](https://demo.dotcms.com/dotAdmin/#/content-types-angular/edit/b343bf54f69a6de243cb73936c358ba8)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63a3438c824de788cae0a1a5_12d3adf256182a29?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
The checkbox is it owns group so it have (I think) the same space as the label + input group, we can discuss this.

**Comment by fmontes** [comment]
We need to have `21px` top margin to the checkboxes.
