### ISSUE TITLE
When user adds contentlet it create two extra blocks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23668]
### Describe the bug
When you add a contentlet block it adds two extra paragraph blocks.

### To Reproduce
1. Type `/`
2. Select "Contentlets" and follow to add one
3. See the contentlets is added and two extra empty paragraphs as well

### Expected behavior
It should just add a contentlet block and one extra paragraph with the cursor focused, ready for the user to keep adding content.

### Acceptance criteria
- User should be able to add a contentlet, no extra paragraph and let the cursor ready to keep adding content.

**Comment by hmoreras** [comment]
Can't reproduce docker image: **23.01_06be9a4f_SNAPSHOT**

Only add the content and a exta `p` to be ready to keep typing. 

https://user-images.githubusercontent.com/31667212/211064004-5c496aa7-3464-474c-8066-279f2d7f2019.mov
