### ISSUE TITLE
Unable to invalidate Script API response cache.

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23660]
### Describe the bug
Unable to invalidate Script API response cache.
Related Ticket: https://dotcms.zendesk.com/agent/tickets/109335.
I implemented the cache through this documentation: https://www.dotcms.com/docs/latest/scripting-api#ResponseCaching.

### To Reproduce
1. Go to the demo site.
2. Create a new content type test with a title field.
3. Create a new script API GET endpoint.
4. Deploy the API with the file I attached.
5. Try to invalidate the cache with https://www.dotcms.com/docs/latest/tag-based-caching-block-cache#dotCacheInvalidate.

### Expected behavior
The cache should be invalidated.

### Additional context
When a script API response is cached the key becomes` anonymous_1_/api/vtl/test`

[get.zip](https://github.com/dotCMS/core/files/10302147/get.zip)

**Comment by wezell** [comment]
The Tag based caching does not invalidate the  api response caching.  They should just add a nonce to their requesting url when they want to invalidate
