### ISSUE TITLE
QA: Test upgrades in both databases 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23665]
As part of the process we need to be able to upgrade from our last release version to the current release without problems. 

Then we need to test this in both databases 
- Postgres 
- MSSSL 

### Expected behavior
We need to be able to upgrade without problems

**Comment by josemejias07** [comment]
**QA Comment** - Tested on 23.01 Branch // Local 

**Postgres :**
[logs.zip](https://github.com/dotCMS/core/files/10314939/logs.zip)
https://gist.github.com/josemejias07/94b2b679ceb73f9648a48441998d25c9

**MSSQL :**
Pending

**Comment by bryanboza** [comment]
I tested MSSQL and now it is working. 


Tested upgrading from LTS_22.03 to release branch-23.02 

New card reported regarding blog editor field. https://github.com/dotCMS/core/issues/23918
