### ISSUE TITLE
Key Functionality Needs to use Buttons instead of Links

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23675]
[![Screenshot_2022-12-28_15-20-00.png](https://mrkr.io/s/63ac5ea0bfd3a37ab11b9867/2)](https://mrkr.io/s/63ac5ea0bfd3a37ab11b9867/0)

Things like "Publish" should be a button, not just a text link.

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Activities/d77576ce-6e3a-4cf3-b412-8e5209f56cae](https://demo.dotcms.com/dotAdmin/#/c/c_Activities/d77576ce-6e3a-4cf3-b412-8e5209f56cae)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac5ea0bfd3a37ab11b986a_7e3deb5074038489?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Depends on the design.
