### ISSUE TITLE
Redesign User Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23678]
[![Screenshot_2022-12-28_15-48-30.png](https://mrkr.io/s/63ac654ea89d916f87da7e5b/2)](https://mrkr.io/s/63ac654ea89d916f87da7e5b/0)

All dropdown items should look like normal items not like a link, with a padding of 14px, white background, and black text, with a hover and focus state.

#### Design:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/751424/226416048-161047a3-224f-47e0-9341-03cbc252bc7a.png">

#### Component to use:

https://primeng.org/menu

You can use the [property separator of the menu modem
](https://primeng.org/menumodel) for the lines

You can add HTML or custom content for the first item like this

```
this.items = [{
            label: '<h2>File</h2>',
            escape: false,
            //...
        }
```

#### Design
Don't match the design just leave how it looks like right now because it will match when we do the final redesign in all the primeng components.

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Activities](https://demo.dotcms.com/dotAdmin/#/c/c_Activities)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac654ea89d916f87da7e5e_ef75c95a446ae4c6?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Melissa-dotCMS** [comment]
Design solution: https://www.figma.com/file/mFPPOVeafZ931xjbXiZHCA/Issues-re-designs?node-id=12%3A344&t=QKCSTGR8wrPxXVE1-1

**Comment by zJaaal** [comment]
Found a bug where a new tab is open on logout

Reported by: @oidacra 

https://user-images.githubusercontent.com/63567962/232585017-9748d523-1ebb-402b-8294-7095f770091a.mov

**Comment by zJaaal** [comment]
Found a bug that when you `Login As` another user, you coudln't see the current site on the toolbar

Reported by: @alfredo-dotcms 

<img width="1512" alt="Screenshot 2023-04-20 at 1 41 59 PM" src="https://user-images.githubusercontent.com/63567962/233432813-54398916-1372-4149-8b16-04f777c50dbc.png">

**Comment by rjvelazco** [comment]
## Passed Internal QA

**Docker Image:** [`dotcms/dotcms:master_1fc8dba8_SNAPSHOT`]

https://github.com/dotCMS/core/assets/72418962/dd325168-674f-4e1e-b722-9d19c33f2a8f

**Comment by bryanboza** [comment]
According to the provided mock this is not the same that we have right now 
This is what we have right now:
![Image](https://github.com/dotCMS/core/assets/2641437/03b631b3-6a38-4f93-9a48-0e3de78841f6)


This is the mock: 
![Image](https://github.com/dotCMS/core/assets/2641437/0f25995c-6c3b-4450-bf16-eba320a6eba1)

We are loosing the user image on this menu

**Comment by fmontes** [comment]
The new look and feel come with the new theme, which is not being implemented right now.
