### ISSUE TITLE
Move Edit Image Button

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23676]
[![Screenshot_2022-12-28_15-36-19.png](https://mrkr.io/s/63ac6273dfff2d89dc9bf374/2)](https://mrkr.io/s/63ac6273dfff2d89dc9bf374/0)

The "Edit Image button" should be placed to the left of the "Remove Button", not on top of the image.

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Activities/d77576ce-6e3a-4cf3-b412-8e5209f56cae](https://demo.dotcms.com/dotAdmin/#/c/c_Activities/d77576ce-6e3a-4cf3-b412-8e5209f56cae)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac6273dfff2d89dc9bf377_f52a4cce08f8944f?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 764</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Why?

**Comment by Melissa-dotCMS** [comment]
It is hard to read and understand the text as the button has a blur, and is not consistent with the rest of the platform and buttons
