### ISSUE TITLE
The background should not be grey

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23688]
[![Screenshot_2022-12-28_16-59-25.png](https://mrkr.io/s/63ac75eda89d916f87da96a8/2)](https://mrkr.io/s/63ac75eda89d916f87da96a8/0)

Change the background to white, set the title as an input field same as the other ones

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac75eda89d916f87da96ab_a2dfecc8fe40e11b?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Melissa-dotCMS** [comment]
It doesn't need a background, leave it in white

**Comment by fmontes** [comment]
We need to do this in the new edit contentlet
