### ISSUE TITLE
Block editor: let's show the + button all the time

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23687]
[![Screenshot_2022-12-28_16-48-11.png](https://mrkr.io/s/63ac734b9ef24c39dd0f40c2/2)](https://mrkr.io/s/63ac734b9ef24c39dd0f40c2/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac734b9ef24c39dd0f40c5_22125cadea4463fa?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Not the case because in hover we have a button there. We talked show the button all the time, never agreed upon.

**Comment by fmontes** [comment]
Let's keep the + button on empty block

**Comment by rjvelazco** [comment]
### Passed Internal QA

Docker Image: [`dotcms/dotcms:23.05_03732ac4_SNAPSHOT`]

https://user-images.githubusercontent.com/72418962/230925113-3b9ad3f1-6c85-406f-9eca-790b15315220.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_03732ac4_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
