### ISSUE TITLE
Should be a button not a dropdown

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23689]
[![Screenshot_2022-12-28_17-01-30.png](https://mrkr.io/s/63ac766af92bad90de682cea/2)](https://mrkr.io/s/63ac766af92bad90de682cea/0)

As there is only one option should be a "Relate" button not a dropdown

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac766af92bad90de682ced_a9609d88d8e052a1?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
We need to do this in the new edit contentlet.
