### ISSUE TITLE
The action block needs to be re-designed

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23685]
[![Screenshot_2022-12-28_16-45-54.png](https://mrkr.io/s/63ac72c26284061e295f37ea/2)](https://mrkr.io/s/63ac72c26284061e295f37ea/0)

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac72c26284061e295f37ed_dee42de87e6ad046?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
It depends on the design.
