### ISSUE TITLE
Standardize Form Label Formatting across dotCMS Application

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23683]
### Problem
In JSP world the labels looks different from in Angular world, we need to make them match Angular.

[![Screenshot_2022-12-28_16-33-59.png](https://mrkr.io/s/63ac6ff75eb740a73e5e3fb7/2)](https://mrkr.io/s/63ac6ff75eb740a73e5e3fb7/0)

### Acceptance Criteria
1. Labels should be text color (there is a CSS var for that)
2. If the field is required, we should add a `*` after, we need to do this in CSS, so we don't have to touch too much CSS

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac6ff75eb740a73e5e3fba_2b1902237f7ff684?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
1. The "new" format for labels is: `Label *` the * is red.
2. This issues scope is only for JSP the Angular side have another issue.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.02_20326b3b_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1

I don't think this has been deployed to the latest docker image 
![Screenshot 2023-02-01 at 10 35 53 AM](https://user-images.githubusercontent.com/110418590/216105242-384d94a6-8e9c-4091-9c5e-f32419ea02d9.png)

**Comment by fmontes** [comment]
This is not 23.2 is master, sorry I didn't provide the label.

Also, you can always check the pull request associated to the issue and found where it was merged.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_feeb5c57_SNAPSHOT** // Docker // macOS 13.0 // FF V110.0
