### ISSUE TITLE
If it's not clickable it should not be visible

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23686]
[![Screenshot_2022-12-28_16-47-09.png](https://mrkr.io/s/63ac730db9e40abf925247bf/2)](https://mrkr.io/s/63ac730db9e40abf925247bf/0)

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac730db9e40abf925247c2_1573e3c22b084bda?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Melissa-dotCMS** [comment]
Leave out the tabs that are dessabled

**Comment by fmontes** [comment]
We need to define the global pattern about this kind of UI.
