### ISSUE TITLE
Let's show the whole path when select a folder in the host selector

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23681]
[![Screenshot_2022-12-28_16-27-36.png](https://mrkr.io/s/63ac6e78f92bad90de682101/2)](https://mrkr.io/s/63ac6e78f92bad90de682101/0)

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac6e78f92bad90de682104_ea4aeec31b13723b?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by zulqarnainvd** [comment]
it is also effect on search filter because host selector is a widget which is used in application widely.
![image](https://user-images.githubusercontent.com/113915849/224991379-04178071-af48-4e9e-89f5-52e554e0946e.png)

**Comment by zulqarnainvd** [comment]
Also need some backend work, because in edit mode there is no way to get parent path from folder. I also informed @hassan-mustafa-baig and @fmontes

**Comment by hassan-mustafa-baig** [comment]
@zulqarnainvd 
changes have been made here https://github.com/dotCMS/core/pull/24364/commits/b9b173a72c6be2bc4aecac57cbd1d57c47abfa67

and it will provide you additional property parentPath in the response of BrowserAjax.getFolderSubfolders call just like this:

e.g: **application/apivtl**

throw 'allowScriptTagRemoting is false.';
(function() {
    var r = window.dwr._[0];
    //#DWR-INSERT
    //#DWR-REPLY
    r.handleCallback("5", "0", [{
        inode: "361cecbb-c052-4a29-b53c-642619e759c1",
        fullPath: "demo.dotcms.com:/search",
        defaultFileType: "33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d",
        parentPath: "/application/apivtl/",
        name: "search",
        absolutePath: "/search",
        id: "bc66bb8b-cd77-4528-9a14-555fc779586e",
        type: "folder"
    }, {
        inode: "457e207e-911d-414d-83fa-13afe9e35882",
        fullPath: "demo.dotcms.com:/sitemap",
        defaultFileType: "33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d",
        parentPath: "/application/apivtl/",
        name: "sitemap",
        absolutePath: "/sitemap",
        id: "960cf1a7-3e47-409e-b9e5-e2d7dbe26135",
        type: "folder"
    }]);
}
)();

**Comment by zJaaal** [comment]
The input field is not resizing correctly, you can see that it cuts some folders and when it gets bigger it doesn't resize to the needed size.

https://user-images.githubusercontent.com/63567962/231297827-8772fe23-761d-4f6e-b5c0-974561fdfc6e.mov

**Comment by fmontes** [comment]
Fixed in the edit contentlet, we're not doing anything in the content search sidebar, not growing there.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1

We need to add some spacing between this fields 

![Screenshot 2023-04-21 at 10 05 27 AM](https://user-images.githubusercontent.com/129882031/233684120-cb8bdc53-ced5-4777-9f61-5f675f6a4c45.png)

**Comment by fmontes** [comment]
Not the case... thats a pop up and it could grow as big as possible.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on ** 23.05_745ecbda_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
