### ISSUE TITLE
Padding should be consistent on the button and field

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23684]
[![Screenshot_2022-12-28_16-44-20.png](https://mrkr.io/s/63ac7264852f45e8e48faf09/2)](https://mrkr.io/s/63ac7264852f45e8e48faf09/0)

### Acceptance criteria
1. The padding in the button should be 1rem (14px).

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac7264852f45e8e48faf0c_3352bf861d558f60?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Even tho we'll be redesigning this in the new edit contentlet is a small fix I think is worth to do.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_3220636c_SNAPSHOT** // Docker // macOS 13.0 // FF v109
