### ISSUE TITLE
The delete button looks disabled

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23715]
[![Screenshot_2023-01-03_16-55-22.png](https://mrkr.io/s/63b45dfa56216ca50f53fb26/2)](https://mrkr.io/s/63b45dfa56216ca50f53fb26/0)

## Wireframes / Designs / Prototypes
Set the delete button to default
## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/templates/new/designer](https://demo.dotcms.com/dotAdmin/#/templates/new/designer)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63b45dfa56216ca50f53fb29_c6b8b1a0ee8bfe40?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Melissa-dotCMS** [comment]
Design solution:
https://www.figma.com/file/mFPPOVeafZ931xjbXiZHCA/Issues-re-designs?node-id=2%3A66&t=cTFNW9VVaUSnFoqS-1
