### ISSUE TITLE
This popup has a different animation than the rest of the popups

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23711]
[![Screenshot_2023-01-03_16-39-34.png](https://mrkr.io/s/63b45a467b3003e62e2f32cc/2)](https://mrkr.io/s/63b45a467b3003e62e2f32cc/0)

## Wireframes / Designs / Prototypes
Please leave it without animation for consistency reasons.

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/templates/new/designer](https://demo.dotcms.com/dotAdmin/#/templates/new/designer)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63b45a467b3003e62e2f32cf_9e68affe298d9785?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
If the comparison is with dojo popups we can't unify.

**Comment by fmontes** [comment]
Check the animations against Content Type popups.

The solution is to use: https://primefaces.org/primeng/dynamicdialog
