### ISSUE TITLE
Add the word "image" to the placeholder instead of file

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23714]
## Problem Statement
Doesn't say image, is confusing to know what should the user drop or browse

[![Screenshot_2023-01-03_16-52-00.png](https://mrkr.io/s/63b45d3056216ca50f53f93a/2)](https://mrkr.io/s/63b45d3056216ca50f53f93a/0)

## Steps to Reproduce
1. Go to templates
2. Edit a template
3. Hit the "Edit button" to see the template properties
4. See the error in the input

## Acceptance Criteria
Users should read in the input placeholder: "Drop or paste image or image url"

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/templates/new/designer](https://demo.dotcms.com/dotAdmin/#/templates/new/designer)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63b45d3056216ca50f53f93d_88f9621550503a17?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_1b118337_SNAPSHOT** // Docker // macOS 13.0 // FF v109
