### ISSUE TITLE
Stream Starter Zip Generation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23733]
### Proposed Objective

Maintenance

### Proposed Priority

Priority 2 - Important

### dotCMS Version

All / dotCMS Cloud

### Problem Statement

Two problems - 
1. when a user requests a starter.zip from the back end, dotCMS goes off, dumps all data and assets into a local temp folder, zips the resulting files into an archive and only then starts sending the response to the end user.  When dotCMS is running behind a load balancer, generally the user's connection is timed out before the temp zipping process is completed and no .zip is delivered.
2. The process above expects to create the temp folder in the `/dotSecure` folder, which in containerized environs is not mapped in and is just container based storage.  If a customer requests new starters repeatedly, this can cause the host servers to run out of disk space (as the entire asset directory is being copied as well). 

### Steps to Reproduce

Hit 

`/api/v1/maintenance/_downloadStarterWithAssets`

1. You will see the temp files built under `/dotsecure`
2. You will see the request waiting until the temp files are all built and copied before the download begins.

### Acceptance Criteria

Hit 

`/api/v1/maintenance/_downloadStarterWithAssets`

1. No temp files should be built anywhere
2. The request should start to stream the download much sooner (almost immediately)
3. The resulting starter.zip should be able to be used to bootstrap a dotCMS instance.
4. The endpoint should return a response that implements `javax.ws.rs.core.StreamingOutput`

**Comment by erickgonzalez** [comment]
The endpoint doesn't exist in 21.06 LTS

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_b5fd2762_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1



release_branch-dotcms-1         | 21:34:59.023  INFO  starter.ExportStarterUtil - Adding all Assets into compressed file...
release_branch-dotcms-1         | 21:35:05.491  INFO  maintenance.MaintenanceResource - Compressed Starter file 'backup_1676064898008-2023-02-10_09-34-58.zip' has been generated successfully!


No temp files created on dotsecure 
![TBA305277312775-InvoiceCourier_66916](https://user-images.githubusercontent.com/110418590/218210627-1cc720f3-bd43-4f81-a4f2-f1958f1f0470.png)

**Comment by bryanboza** [comment]
Fixed!
