### ISSUE TITLE
Close the gap in the dojo dialogs title

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23739]
[![Screenshot_2023-01-05_17-30-04.png](https://mrkr.io/s/63b7091cc4b2b2d7bbc672a5/2)](https://mrkr.io/s/63b7091cc4b2b2d7bbc672a5/0)

## Problem Statement
There is a margn in the title bar of all dojo dialogs.

## Steps to Reproduce
1. Go to content search
2. Click the Show query dropdown
3. Click show query
4. See the error

## Acceptance Criteria
Dialog should not have a gap in the title

---

**Reported by:** Freddy Montes (freddy@dotcms.com)

**Source URL:** [http://localhost:8080/dotAdmin/#/c/content](http://localhost:8080/dotAdmin/#/c/content)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63b7091cc4b2b2d7bbc672a8_c5fdaf00ad154a62?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1556 x 891</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
@zulqarnainvd found an issue here:

<img width="1854" alt="image" src="https://user-images.githubusercontent.com/751424/217353242-f337d3da-00ce-4ed9-95d3-5df352d3fb1c.png">

**Comment by zulqarnainvd** [comment]
Noted

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_b5fd2762_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1
