### ISSUE TITLE
We are not refreshing the site selector component when you stop//archive a site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23747]
### Proposed Objective

Accessibility (WCAG)

### Proposed Priority

Priority 3 - Average

### dotCMS Version

Tested on release-23.01 

### Problem Statement

When you create// stop //archive a site, we need to fire an event to update the site selector component, right now we are just doing this when you create a new site. 

When you stop/archive sites, we are just removing from the list, but if we leave just one in the list we need to remove the drop down and leave just the only one in the list. 

https://user-images.githubusercontent.com/2641437/210900212-21cb44f5-90c8-4767-bb43-0c9be93b1daa.mov

### Steps to Reproduce

- Login as admin
- Create a new site 
- Make sure we are updating the site selector with the multiple selection 
- Now archive the site and make sure we are removing the drop-down and leave just one site again 

### Acceptance Criteria

We need to fire an event to update this component in each of the transactions mentioned above

**Comment by wezell** [comment]
Not a blocker for 23.01

**Comment by damen-dotcms** [comment]
Won't fix.
