### ISSUE TITLE
Unable to import content using Safari 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23741]
We are getting an error when you try to import content in Safari 

### To Reproduce: 
- Create a new cotnent type with two fields (name{tex} , body{blog} )
- Add a new piece of content 
- Export it 
- Delete the created content from the cotent type  
- Open the exported CSV and delete the (identifier, language) column 
- Save changes and try to import this CSV 

Here the log: https://gist.github.com/bryanboza/72f69c670d0cd43b185beb2e548027c1
Here the error: 
![image](https://user-images.githubusercontent.com/2641437/210667743-8bc8e735-5bf1-4c3d-aa19-646a7853e4ed.png)
 Here my CSV file: 
[TEST!_contents_1_4_2023.csv](https://github.com/dotCMS/core/files/10348140/TEST._contents_1_4_2023.csv)

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/23405#issuecomment-1371535041_

**Comment by fmontes** [comment]
Don't support Safari.
