### ISSUE TITLE
Block Editor Content Type should be fixed to the line it was originally opened

### ISSUE THREAD

**Issue by josemejias07** [dotCMS/core#23752]
### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

### dotCMS Version

23.01_288ffc92_SNAPSHOT

### Problem Statement

macOS 13.0 // FF v108.0.2

### Steps to Reproduce

Scrolling issue appears due to the ' Select a Content type ' pop up does not gets fixed to where it was originally opened

![scroll](https://user-images.githubusercontent.com/110418590/211056096-ecdd1c8c-81f7-4b82-9663-0303c8a0ed98.gif)

### Acceptance Criteria

Pop up should remain fixed to the place it was opened

**Comment by damen-dotcms** [comment]
Won't action at this time. 

Can be solved by clicking out of the add content menu.
