### ISSUE TITLE
Take the `Paragraph` option out of the `Allowed Blocks` field

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#23764]
### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### dotCMS Version

23.01

### Problem Statement

The `Paragraph` block type in the **Story Block** field is supposed to be always present by default. Unfortunately, this is confusing as it shows up in the `Allowed Blocks` section, which is conveying Users that it might be removed altogether.

### Steps to Reproduce

1. Create a Content Type with a Story Block field.
2. Edit such a field and go to the `Settings` tab.
3. Uncheck the `Paragraph` option.
4. Create a Contentlet of such a type. Notice that the `Paragraph` block type is still present.

### Acceptance Criteria

The `Paragraph` block type must not be present in the `Allowed Blocks`field, as it must always present in the field.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/22908#issuecomment-1376316528

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/23864

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_3220636c_SNAPSHOT** // Docker // macOS 13.0 // FF v109

Note: Some tweaks and improvements still going on this, getting addressed on different cards. This particular cars is done. @fmontes
