### ISSUE TITLE
Unable to start LTS release using MSSQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23761]
### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

### dotCMS Version

Tested trying to start dotcms:22.03.4_lts_48f1f38

### Problem Statement

We are getting an error running this upgrade task `Task220912UpdateCorrectShowOnMenuProperty` and the server is not starting 

Same error running the tests
https://raw.githack.com/dotCMS/test-results/release-22.03.4/projects/core/current/integration/mssql/reports/html/classes/com.dotmarketing.startup.runonce.Task220912UpdateCorrectShowOnMenuPropertyTest.html

Here the complete error locally 
https://gist.github.com/bryanboza/d317e2820e16eece766dec1bc4f36756

### Steps to Reproduce

Try to start a docker server using the last LTS version 

### Acceptance Criteria

We need to be able to start this server without problems

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/23813/files

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/23867

**Comment by erickgonzalez** [comment]
After the changes in https://github.com/dotCMS/core/pull/23867 customer were able to upgrade successfully.

**Comment by dsilvam** [comment]
Passed Internal QA: Tested upgrading from `22.10` to `23.02_c42fb65d_SNAPSHOT` using docker/docker-images. Upgraded successfully to 23.02, including the execution of the UT  `Task220912UpdateCorrectShowOnMenuProperty`.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.02 // Docker // FF

**Comment by erickgonzalez** [comment]
UT doesn't exist in 21.06 LTS
