### ISSUE TITLE
[Defect]: Landing page is not loading when created using 'Landing Page' template on Demo site

### ISSUE THREAD

**Issue by kanika141290** [dotCMS/core#23770]
### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### dotCMS Version

22.12

### Problem Statement

Landing page is not loading when created using 'Landing Page' template on Demo site

### Steps to Reproduce

1. Login to https://demo.dotcms.com/dotAdmin
2. Navigate to Site > Browser
3. Create a new folder and then create a new Landing page.
4. Select the template as 'Landing Page'
5. Save and publish the page.
6. Gettings CSS error and landing page is not loading.

### Acceptance Criteria

New landing page created should load successfully

**Comment by john-thomas-dotcms** [comment]
Screenshot of the error:
<img width="1505" alt="LandingPageIssue" src="https://user-images.githubusercontent.com/13456955/211619056-15dfe7f2-eac3-4265-9698-52074fc09bdd.png">

**Comment by jcastro-dotcms** [comment]
This is caused by the Dart Sass lib being too strict with some validations. Here's the fix for it:

- Edit the `/application/themes/landing-page/css/custom/_base.scss` file.
- Go to line # 32 and add the required blank space before "75px", like this:
```css
min-height: calc(50vh - 75px);
```
- Publish the file, and you're good to go.
