### ISSUE TITLE
Use docker buildx GH Action

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#23780]
Since there's a Docker buildx GH action we should use it instead of having our customized one.

**Comment by victoralfaro-dotcms** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23780?planning-poker) with Zenhub @dsilvam @freddyucv @oidacra

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23795

**Comment by dsilvam** [comment]
Passed QA based on GHA feedback
