### ISSUE TITLE
The URL for images is not working

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23788]
[![Screenshot_2023-01-11_20-05-13.png](https://mrkr.io/s/63bf167911d6e78036c049b0/2)](https://mrkr.io/s/63bf167911d6e78036c049b0/0)

## Problem Statement
Try to add an image by pasting a URL from Unsplash and another one from google images and non of them works.

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/templates/new/designer](https://demo.dotcms.com/dotAdmin/#/templates/new/designer)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63bf167911d6e78036c049b3_e0a5c7129fd3cba0?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
It doesn't workl with this image: https://camo.githubusercontent.com/348b98fd80647f7c763163c1fa81e0592a8828ec4bacb6c5511c77e8580c802e/68747470733a2f2f6d726b722e696f2f732f3633626631363739313164366537383033366330343962302f32

**Comment by zulqarnainvd** [comment]
![image (1)](https://user-images.githubusercontent.com/113915849/225368793-c27df4c8-121a-4f4a-8af9-a4f7370a8fd7.png)

**Comment by fmontes** [comment]
We need to check this in the backend.
