### ISSUE TITLE
Containers: Add support for file containers

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23798]
### Is your feature request related to a problem? Please describe.
In dotCMS we have 3 types of containers:

1. System: user can't edit it
2. DB: Are the ones we create with the UI and the containers API
3. FILE: containers that are creating by adding a set of files in the file system.

Currently, we're not correctly supporting the FILE type.

### Describe the solution you'd like
1. List of the file containers
2. The row of a file container should have the url
3. The row of a file container should NOT have:
    - Checkbox or be able to be selected
    - Three dots actions buttons
    - Be able to apply actions to
4. When the user clicks the row of a file container, it should link to the Site Browser with the containers folder opened (currently working in the JSP containers)
5. The containers API response have a `"source" : "FILE"` property to indicate the type of container.

### Additional context

**Original containers**

<img width="1208" alt="Screenshot 2023-01-12 at 11 30 27" src="https://user-images.githubusercontent.com/751424/212137877-23e14f0e-f4a5-4437-9fa5-c9decc184b19.png">

**Figma**
https://www.figma.com/file/k1LhfC4OxI4ZQr2erCFhKM/Portlets-%2F-Containers?node-id=1%3A209&t=mUxKSmLeBzbVAqOr-1

**‼️ To view file containers, run dotCMS with the full starter**

### Acceptance criteria
- List the file containers
- System containers always on top
- When user clicks the file container row it should go to the site browser with the containers opened
- User should not be able to run actions on file containers

**Comment by rjvelazco** [comment]
### Failed Internal QA.

Docker image: [`dotcms/dotcms:master_bd915908`]

We are adding a double `//` a the beginning of the `URL`. It's no part of the Figma design which only has one.


|  Figma Design  |  Old Porlet |  New Porlet |
|---|---|---|
| ![Image](https://user-images.githubusercontent.com/72418962/222328899-0d287a91-1ada-451b-a680-d2c05537aa94.png) | ![Image](https://user-images.githubusercontent.com/72418962/222329202-768d3324-d518-457c-a1c9-d1eae21c5ad2.png) | ![Image](https://user-images.githubusercontent.com/72418962/222328729-aa349798-f4a0-41fd-8d0a-83ab2ceb7d96.png)  |

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_646c3cbf_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

https://user-images.githubusercontent.com/129882031/230211874-7cfa5121-1481-408c-971f-571075f68803.mov


4. When the user clicks the row of a file container, it should link to the Site Browser with the containers folder opened

**Comment by jcastro-dotcms** [comment]
@josemejias11 , as per discussion with the Lunik Team, this issue happens in our Demo Site as well. I have created a new ticket in order to address the redirect issue: https://github.com/dotCMS/core/issues/24644

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_14850342_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
