### ISSUE TITLE
Pipeline tweaks

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#23808]
This issue is covers several improvements:
- Use GHCR.io registry to consume docker images considered as dependencies for the tests (ITs and postman)
- Adjust wait for DB and Open Distro wait-for time at ITs
- Introduce action to remove published dotcms `cicd` image consumed by postman tests
- Update postman `checkBundleStatus` function at `Push Publish from sender` collection to fail whenever it can't determine the result of publishing of the bundle rather than hanging.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23809

**Comment by dsilvam** [comment]
Passed QA based on GHA feedback
