### ISSUE TITLE
Asset download missing directories 8 and 9

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23810]
### Proposed Objective

Developer Experience

### Proposed Priority

Priority 1 - Show Stopper

### dotCMS Version

22.03-23.01.0

### Problem Statement

We have the ability to download a dump of the asset directory from the backend.  The issue is that our pattern to match which directories to include is missing directories /8/ and /9/.

### Steps to Reproduce

- Go to the maintenance tab > tools
- Click "Download Assets"
- it works, but if you unzip the assets, it is missing directories /8 and /9

### Acceptance Criteria

include directories 8 and 9

**Comment by erickgonzalez** [comment]
Customer ticket https://dotcms.zendesk.com/agent/tickets/109693

**Comment by dsilvam** [comment]
Passed Internal QA: Properly including folders `8` and `9` when downloading the assets.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_3220636c_SNAPSHOT** // Docker // macOS 13.0 // FF v109

**Comment by erickgonzalez** [comment]
Not reproducible in 21.06 LTS.
