### ISSUE TITLE
Content type field variables cut off

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23816]
[![Screenshot_2023-01-13_20-49-23.png](https://mrkr.io/s/63c1c3d39165a8659ceb96be/2)](https://mrkr.io/s/63c1c3d39165a8659ceb96be/0)

## Problem Statement
When the field variable is too long, it cut off.

## Steps to Reproduce
1. Edit a content type
2. Add rows with 4 columns
3. Add one field to each column with a long title

## Acceptance Criteria
- Needs to show Title
- Needs to show Type
- Needs to show Variable Name - with "Copy" icon
- Users have "unlimited" characters... so some truncation is needed.

## Wireframes / Designs / Prototypes
- Needs UI

---

**Reported by:** Freddy Montes (freddy@dotcms.com)

**Source URL:** [http://localhost:8080/dotAdmin/#/content-types-angular/edit/657897dfb36ef211ebfb4128de818787](http://localhost:8080/dotAdmin/#/content-types-angular/edit/657897dfb36ef211ebfb4128de818787)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63c1c3d39165a8659ceb96c1_36d8a4e2737e5abf?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 109.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1551 x 1805</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

```[tasklist]
### Tasks
- [ ] Provide Design @Melissa-dotCMS 
- [ ] Update Feature
```

**Comment by fmontes** [comment]
I need to work on this design, is not working yet.

**Comment by bryanboza** [comment]
same thing after the changes 
![image](https://user-images.githubusercontent.com/2641437/228945662-8d471a8f-81a6-43a9-8bd9-5e08cece1fd8.png)

**Comment by fmontes** [comment]
New design:

![Image](https://user-images.githubusercontent.com/751424/229258876-02c95973-8b66-40b0-a134-3c52a1ddf7e2.png)

1. The expand should not make the layout jump, just go over.
2. For the Required, Indexed etc... boxes use the PrimeNG Chip component (chip not chips)
3. The delete field should have the confirmation dialog.

**Comment by fmontes** [comment]
As per @wezell request we need to update the design to make the variable name visible and not hide under a tooltip in the button.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.03_a3030c6a_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** [`dotcms/dotcms:23.05_14850342_SNAPSHOT`]


https://user-images.githubusercontent.com/72418962/232894371-0f0ed906-3104-496c-9716-c50b50dff269.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_14850342_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

**Comment by zJaaal** [comment]
Some changes were requested and it required a new design, I'm working on it right now. Here is the new design:

![Frame 167](https://user-images.githubusercontent.com/63567962/235179408-6775be93-82d1-4162-a5e1-8997510d984e.png)

**Comment by rjvelazco** [comment]
### Failed Internal

**Docker Image**: [`dotcms/dotcms:master_1fc8dba8_SNAPSHOT`]

We still have the old design. After a talk with @zJaaal, it seems his changes were lost in the merge from `release-23.05` to `master`.

![Image](https://github.com/dotCMS/core/assets/72418962/6df673d4-ae9f-46a5-8b82-1f9c14248af1)

**Comment by zJaaal** [comment]
Right now we have an open PR https://github.com/dotCMS/core/pull/24882 merging the changes to `Release 23.06`

**Comment by rjvelazco** [comment]
## Passed Internal QA

**Docker Image**: [`dotcms/dotcms:23.06_1aa99392_SNAPSHOT`]

https://github.com/dotCMS/core/assets/72418962/2015a00e-ef2d-4800-8e02-1e299833cd8c

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_ec9b3270_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_ec9b3270_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
 
Still showing when using FireFox
![Screenshot 2023-05-31 at 3 07 51 PM](https://github.com/dotCMS/core/assets/129882031/279de53e-727a-4e55-aee4-40efc9e6dd45)

**Comment by fmontes** [comment]
Create a new ticket for the header, the scope of this task is just for the fields.

**Comment by fmontes** [comment]
Our min support is landscape iPad and this even looks good in portrait with 2 columns



![Image](https://github.com/dotCMS/core/assets/751424/d1c657e6-196b-48f5-a721-e5822fbaf660)

And landscape:



![Image](https://github.com/dotCMS/core/assets/751424/f165220d-45e4-4048-964d-bb8520fea1f4)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_906f4029_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Created a related issue here #25119
