### ISSUE TITLE
Website Defaults Need to Only have Supported Langauges

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23825]
[![Screenshot_2023-01-17_16-41-38.png](https://mrkr.io/s/63c6cfc2d3a5688e4bf79c66/2)](https://mrkr.io/s/63c6cfc2d3a5688e4bf79c66/0)

## Problem Statement
If the user sets a language, the entire website should be in that language (right now is in English even if I select Spanish) if we can't do that, it's better not to have the option to change the language

## Sub-Tasks

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/public/login?r=1673973452314](https://demo.dotcms.com/dotAdmin/#/public/login?r=1673973452314)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63c6cfc2d3a5688e4bf79c69_2039417e4f727e08?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by fmontes** [comment]
Let's translate the Getting Starter

**Comment by fmontes** [comment]
@wezell ask me to send you guys this.

**Comment by fmontes** [comment]
Stale and close
