### ISSUE TITLE
Filter Contentlets by DEFAULT Variant in Contentlet Portlet and Site Browser

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23833]
### Proposed Objective

Core Improvement (Features)

### Proposed Priority

Priority 2 - Important

### User Story

If a Contentlet has different versions in different variant we are showing all the versions into the Contentlet Portlet listing.
We need tshow there only the DEFAULt Variant Version.

### Acceptance Criteria

We need to show only the DEFAULT Variant version of the Contentlet in the Contentlet Portlet listing.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24148

**Comment by freddyucv** [comment]
**Needs Work**: When create two version to the same page it is failing

Step to reproduce:

- Create a Page
- Create an Experiment using this page.
- Create a Variant and edit it. And change de Page's Layout.
- Go to the Browser or the "Search all" Portlet in both cases you are going to see the two pages version.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24210

**Comment by victoralfaro-dotcms** [comment]
Page created:
![image](https://user-images.githubusercontent.com/64026161/221916596-81b3f1d8-723a-4b05-94aa-45439c2a3050.png)
Experiment created:
![image](https://user-images.githubusercontent.com/64026161/221916726-29abe7b9-9c9e-44e1-bedc-59f0433d6ca3.png)
Original:
![image](https://user-images.githubusercontent.com/64026161/221916893-d8d0620b-a285-41a8-b800-fd86ee8f7569.png)
Variant:
![image](https://user-images.githubusercontent.com/64026161/221917006-4cbed9b1-1a7d-4df1-94c1-c14f25024f3f.png)
Variant's layout:
![image](https://user-images.githubusercontent.com/64026161/221917403-58b07f6a-0a9f-4272-9ad1-26bc715dd6dc.png)
Showing just one version:
![image](https://user-images.githubusercontent.com/64026161/221917869-a4e05cc8-8b8e-438d-8dee-30178b4f2934.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.03 // Docker // FF
