### ISSUE TITLE
We need to set the clusterId into the jitsu Event

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23834]
### Proposed Objective

Core Improvement (Features)

### Proposed Priority

Priority 2 - Important

### User Story

Right now we have the line that set the clusterId in the EventLogWebInterceptor commented

https://github.com/dotCMS/core/pull/23698/files#diff-d728800ddc8741a2057c0709a77ccf4c9d2e6c833536579add9b3ba8b922b9ddR124

because it is throwing a error when the Event arrived to jitsu telling that it is not able to alter the ClickHouse Event table.

Also I think we are setting a clusterId in another place into the internal-infrastructure and maybe this is the reason why it failing when we set the clusterId in the WebInterceptor class, because right now we already have the math to cubeJS and we are creating the table into the ClickHouse table.

https://github.com/dotCMS/core/blob/161cc995faa192a0104ba57f8e7c11272be1f18d/cicd/docker/setup/config/dev/cube/schema/Events.js#L26

https://github.com/dotCMS/internal-infrastructure/blob/409d494b7a095c4a788b51080790d1666288b2ea/dot-analytics/configurator/deployment/docker/clickhouse/build-src/init-db.sh#L10

### Acceptance Criteria

Save the clusterId into the jitsu Event

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23834?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by john-thomas-dotcms** [comment]
No longer applicable
