### ISSUE TITLE
Delete from SessionStorage the Key variantName

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23837]
### Proposed Objective

Core Improvement (Features)

### Proposed Priority

Priority 3 - Average

### User Story

As a user, I want to delete the SessionStorage key `variantName` when DotEditContent is destroyed (OnDestroy)

### Acceptance Criteria

- When you return to ExperimentConfiguration, the sessionStorage key `variantName` must not exist.

<img width="1104" alt="Screenshot 2023-01-18 at 9 49 53 AM" src="https://user-images.githubusercontent.com/1909643/213202870-38a0c8d7-efcc-46d6-8ced-e1b4592fe268.png">

**Comment by freddyucv** [comment]
When you go to the layout tab the variantName is removed from the session Storage we should keep it when we go into the layout tab

**Comment by bryanboza** [comment]
Fixed, tested on release-23.03 // Docker // FF
