### ISSUE TITLE
Add to REACH_PAGE Goal the configurations

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23847]
### Proposed Objective

Core Improvement (Features)

### Proposed Priority

Priority 3 - Average

### User Story

As a user, I want to be able to add the name of the REACH_PAGE Goal and set the next conditions:

- parameter
- - url (Mandatory)
- operator (Mandatory)
- - EQUALS or COINTAIN
- value (Mandatory)

### Acceptance Criteria

- Add a REACH_PAGE Goal and show a sidebar with the required inputs
- When saving it, go to the config page and show the changes.

### Assumptions & Initiation Needs
Body 

```{
    "goals": {
        "primary": {
            "name": "asdasd",
            "type": "REACH_PAGE",
            "conditions": [
                {
                    "parameter": "url",
                    "operator": "EQUALS",
                    "value": "value"
                }
            ]
        }
    }
}

**Comment by oidacra** [comment]
PR https://github.com/dotCMS/core/pull/24196

**Comment by dsilvam** [comment]
Passed Internal QA: Working as expected. Able to configure the goal via the UI and it's properly registering the events and the goal itself.

**Comment by bryanboza** [comment]
Fixed, this is working as expected at UI level, some new cards related to goals were reported. 

https://github.com/dotCMS/core/issues/24693
https://github.com/dotCMS/core/issues/24692

We can close this card for now. Tested on release 23-05 // Docker // FF
