### ISSUE TITLE
Portlets content errors when loading content

### ISSUE THREAD

**Issue by josemejias07** [dotCMS/core#23894]
### Problem Statement

Once the docker image get loaded an error occurred when loading the content portlets

https://gist.github.com/bryanboza/f042e01c60422f6c63086fdb4ac21eba

16:40:40.806 ERROR portlet.StrutsPortlet - org.apache.jasper.JasperException: An exception occurred processing [/html/portal/layout_portal.jsp] at line [19]
release_branch-dotcms-1     |
release_branch-dotcms-1     | 16:     <% if (Validator.isNotNull(tilesPortletSubNav) ) {%>
release_branch-dotcms-1     | 17:       <liferay:include page=“<%= Constants.TEXT_HTML_DIR + tilesPortletSubNav %>” flush=“true” />
release_branch-dotcms-1     | 18:     <%}%>
release_branch-dotcms-1     | 19:     <jsp:include page=“<%= Constants.TEXT_HTML_DIR + tilesContent %>“></jsp:include>
release_branch-dotcms-1     | 20:   </div>
release_branch-dotcms-1     | 21:
release_branch-dotcms-1     | 22: <%}else{ %>
release_branch-dotcms-1     |
release_branch-dotcms-1     |
release_branch-dotcms-1     | Stacktrace:
release_branch-dotcms-1     | 16:40:40.808 ERROR servlet.MainServlet - com.dotcms.repackage.javax.portlet.PortletException

![Screenshot 2023-01-25 at 10 40 49 AM](https://user-images.githubusercontent.com/110418590/214634223-8403801a-34e9-4435-b6d0-5b6b5001843d.png)

### Steps to Reproduce

1. Build the latest Docker image 23.02_c42fb65d_SNAPSHOT
2. https://localhost:8443/c
3. Go to any content portlet ( https://localhost:8443/dotAdmin/#/c/c_Banners )
4. Check the error logs

### Acceptance Criteria

User should be able to get access to the used content

### dotCMS Version

23.02_c42fb65d_SNAPSHOT

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by fmontes** [comment]
After check in with @bryanboza, false alarm.
