### ISSUE TITLE
Content type fields headers breaking in smaller screens

### ISSUE THREAD

**Issue by josemejias07** [dotCMS/core#23891]
### Problem Statement

Headers should should be responsive to the size of the window 

![214107804-3e1b1d9a-3591-4adc-9168-14a9e8721fbd](https://user-images.githubusercontent.com/110418590/214624569-5d49fc7b-64c4-44fe-bbb8-178d4628084c.png)

### Steps to Reproduce

1. Go to https://localhost:8443/c
2. Resize the window using any corner of the browser
3. Check the rendering of the headers

### Acceptance Criteria

App should be responsive on the whole of it

### dotCMS Version

23.02_c42fb65d_SNAPSHOT

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/23644

**Comment by fmontes** [comment]
iPad

<img width="718" alt="image" src="https://github.com/dotCMS/core/assets/751424/c4366794-f0c7-43d3-b4ca-a80cf38a8a73">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_74dd67e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

![Simulator Screenshot - **iPad Air (5th generation)** - 2023-07-17 at 11 23 29](https://github.com/dotCMS/core/assets/129882031/81bcc625-05fa-447a-b2b5-93da04dc620e)
