### ISSUE TITLE
Delay response when user authentication invalid

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23903]
### Problem Statement

When a user tries to login and they pass an invalid password, we add a 2 second sleep before returning an invalid response.

When the user email or userId does not exist, we return immediately. This difference can be used to probe a dotCMS system for valid user emails/ids.  We should delay any bad login by 2 seconds to prevent such brute force attacks.

### Steps to Reproduce

1. Try to Login with a bad password - you will see the response wait 2 seconds before it returns.
2. Try to Login with a nonexistent user - you will see the response return immediately.

### Acceptance Criteria

Login with a nonexistent user - you will see a 2 second delay.

### dotCMS Version

5.x-23.01

### Proposed Objective

Security

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
As per @jcastro-dotcms fixed here:  https://github.com/dotCMS/core/issues/23915
