### ISSUE TITLE
Image editor crop zone not resizing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23925]
### Problem Statement

When the user add a crop zone to the image, it should be able to resize it and is not working.

### Steps to Reproduce

1. Edit a "Blog" contentlet
2. In the image field click on "Edit" (need license)
3. Click the `Crop` button
3. Try to resize

https://user-images.githubusercontent.com/751424/214959995-a51bfa1e-bbeb-483c-a4ad-80c3e0510fe4.mp4

### Acceptance Criteria

Users should be able to resize the crop area from the corner.

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_feeb5c57_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
