### ISSUE TITLE
Image editor `Clip` button doesn't work

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23927]
### Problem Statement

The clip button in the image editor is not copy to the dotCMS clipboard, the image.

### Steps to Reproduce

1. Edit an image
2. Resize or do some changes
3. Click the `Clip` button
4. Now try to use it in a WYSIWYG field

Here is a walkthrough on how that button works: https://youtu.be/I08KR_0DaYk?t=265

### Acceptance Criteria

Users should be able to use the clip button to add images to the WYSIWYG

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_22c57977_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
