### ISSUE TITLE
BLOCK EDITOR: Can't add image when white list the blocks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23920]
### Problem Statement
When you try to add an image, it won't and shows an error in the browser console.

### Steps to Reproduce
1. Edit a block editor field
2. In "Settings" tab block list some blocks and **include images**
3. Try to add an image to that field
4. See the error

### Acceptance Criteria
- User should be able to add images even when whitelist blocks.

**Comment by erickgonzalez** [comment]
PR for 23.01 https://github.com/dotCMS/core/pull/23922

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.02_f7c276a6_SNAPSHOT** // Docker // macOS 13.0 // FF v109

After editing the content blog type to add any other allowed content type, we are loosing the already present content, whether are paragraphs or a table as the video example below shows.

![blog editor](https://user-images.githubusercontent.com/110418590/215604774-edcf2c20-350c-458e-aa3e-c20dd7145f73.gif)

**Comment by rjvelazco** [comment]
Looks like it is a known issue. When we remove a node from the `Schema` and then tiptap tries to parser a `JSON`, it throws an error and the content gets lost.

- https://github.com/ueberdosis/tiptap/issues/3437
- https://github.com/ueberdosis/tiptap/issues/2283

**Comment by fmontes** [comment]
We remove the blocks when white list, so no blocks, no content and that's expected.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_99f657b4_SNAPSHOT** // Docker // macOS 13.0 // FF v109.0.1

All other issues will be addressed with the below cards.

https://github.com/ueberdosis/tiptap/issues/3437
https://github.com/ueberdosis/tiptap/issues/2283

**Comment by erickgonzalez** [comment]
Commit above should be ignored, is for another issue #23237
