### ISSUE TITLE
Update Starter Logic

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23930]
We need to update our starter logic to include the correct asset directories

### Proposed Priority

Priority 2 - Important

https://docs.google.com/document/d/1UZO9md55XL5xAz5FReJMLy90SnteXZSYCDTI3OX0cP4/edit

**Comment by victoralfaro-dotcms** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23930?planning-poker) with Zenhub @dsilvam @freddyucv @oidacra

**Comment by wezell** [comment]
Taken care of in #23937

**Comment by victoralfaro-dotcms** [comment]
These were the starters that used to include the `license.zip` asset.
```
starter-empty_20220718.zip
starter-empty_20220902.zip
starter-empty_20220908.zip
starter-empty_20221004.zip
starter-empty_20221011.zip
starter-empty_20221013.zip
starter-empty_20221018.zip
starter-minimal_20230103.zip
```
License portlet with latest empty starter:
![image](https://user-images.githubusercontent.com/64026161/217089752-3f48ace5-137a-4b14-acaa-96e2d77d30b7.png)

**Comment by oidacra** [comment]
Tested with `23.03_SNAPSHOT`

`starter-empty_20220718.zip` ✅ 
<img width="1462" alt="Screenshot 2023-02-28 at 10 38 57 AM" src="https://user-images.githubusercontent.com/1909643/221902643-12781da4-1d6d-400d-9438-d21e0e1f9e73.png">

`starter-empty_20220902.zip` ✅ 
<img width="1470" alt="Screenshot 2023-02-28 at 10 47 22 AM" src="https://user-images.githubusercontent.com/1909643/221904917-fb8de632-a494-47bc-a1fa-f40622799ff6.png">

`starter-empty_20220908.zip` ✅ 
<img width="1452" alt="Screenshot 2023-02-28 at 10 50 11 AM" src="https://user-images.githubusercontent.com/1909643/221905721-adb998e9-0f9f-4a4a-a0ca-35275de7e473.png">


`starter-empty_20221004.zip` ✅ 
<img width="1447" alt="Screenshot 2023-02-28 at 11 06 33 AM" src="https://user-images.githubusercontent.com/1909643/221910261-5b568a85-37be-4cf7-8814-2f5d6d054a7e.png">


`starter-empty_20221011.zip` ✅
<img width="1477" alt="Screenshot 2023-02-28 at 11 08 15 AM" src="https://user-images.githubusercontent.com/1909643/221910721-308adb32-a225-47b4-861d-ccf5d4491233.png">


`starter-empty_20221013.zip` ✅
<img width="1466" alt="Screenshot 2023-02-28 at 11 09 37 AM" src="https://user-images.githubusercontent.com/1909643/221911014-02e0bd12-7314-4f23-b738-2f22b34ec850.png">


`starter-empty_20221018.zip` ✅
<img width="880" alt="Screenshot 2023-02-28 at 11 12 05 AM" src="https://user-images.githubusercontent.com/1909643/221911619-d144531b-5db4-4d5c-bcaa-05f8ee45feb9.png">


`starter-empty_20230112.zip` ✅
<img width="883" alt="Screenshot 2023-02-28 at 11 13 06 AM" src="https://user-images.githubusercontent.com/1909643/221911872-a023a2cf-7327-4597-a686-89da11d4089e.png">


`starter-minimal_20230103.zip` ✅
<img width="881" alt="Screenshot 2023-02-28 at 11 14 26 AM" src="https://user-images.githubusercontent.com/1909643/221912211-71c58037-935b-4711-b2b7-a216869c096f.png">

**Comment by oidacra** [comment]
Using a starter file with `license.zip`
<img width="867" alt="Screenshot 2023-02-28 at 11 51 55 AM" src="https://user-images.githubusercontent.com/1909643/221922285-636b7b12-0636-4e7c-aeaa-55eae41884c9.png">
