### ISSUE TITLE
Sanitize SVG images

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#23947]
### Problem Statement

See the link below. 

### Steps to Reproduce

See the document above.

### Acceptance Criteria

Demonstrate that the problem does not exist anymore after fix.

### dotCMS Version

LTS 23.01+

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://drive.google.com/file/d/1j47zWxTVR-_5HPzDaIkasxMsecHj3bWh/view?usp=sharing

**Comment by mbiuki** [comment]
This is as well's been reported here: https://docs.google.com/spreadsheets/d/13YB04SgYYROvWMHVSb35tBQJqJPMlA13uk3W0tLgkL8/edit?usp=sharing

**Comment by mbiuki** [comment]
Some leads:

Ensure the output is correct, secure, and optimized for use on the web. This should apply to prominent extentions, e.g., .zip, .pdf, .jpeg, .txt, .jpg, .tar. etc.

### Requirements

- Should limit to only a set of extensions.
- Should not accept an upload w/o and extension.


### Example for SVG
Some common sanitation libraries for SVGs include:
2. SVGO (SVGO is a Node.js-based tool that optimizes SVGs by removing unnecessary information, compressing shapes, and reducing the file size).
3. svg-cleaner (svg-cleaner is a command-line tool that removes unnecessary code from SVGs and optimizes them for use on the web).
4. Scour (Scour is a Python-based tool that optimizes SVGs by reducing the file size and removing unnecessary information).
These libraries can help improve the performance and compatibility of SVGs, and can also help to secure SVGs by removing malicious code and improving code quality.

**Comment by mbiuki** [comment]
Check MIME Type not just the extension.

**Comment by mbiuki** [comment]
Additional suggestions:
- Disallow uploading SVG images.
- Use a library to sanitize SVG images so that any javascript is sanitized.
- Use a CSP header which will ensure javascript is not executed.

**Comment by mbiuki** [comment]
This gets a medium score according to CVSS v3.1: 6.4 ([AV:N/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:H](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:H&version=3.1)

**Comment by mbiuki** [comment]
https://stackoverflow.com/questions/14968433/validating-xml-with-xsd-and-xmlns

**Comment by mbiuki** [comment]
use this library: https://github.com/bgalek/safe-svg
There could be an svg which safely runs, totally valid svg: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script
So we want to let the uploader know that the file contains script.

**Comment by damen-dotcms** [comment]
This is fixed with the XSS changes -- we'll be putting out a blog post and updating docs to show users how to remedy this soon.

**Comment by mbiuki** [comment]
@damen-dotcms, please give a reference link to the publishing document that would mitigate this issue, thanks.

**Comment by damen-dotcms** [comment]
Gets a little annoying updating in 90 and GitHub. (=

This is as "done" as we can make it until we re-do the demo site. The demo site is full of in-line styles and JS and that's causing problems getting a clean score with the scanning tools. Once the demo site has been cleaned up, all that remains is flipping the "on" switch on the CSP rule.

https://docs.google.com/document/d/1ESTqqJQZmDBndDXbOnVBF1LpR5psrwLlNKxZPAqe6eE/
