### ISSUE TITLE
Account enumeration issue

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#23946]
### Problem Statement

See this link: https://drive.google.com/file/d/1cOz4LnxO-O4Afv59EUuftCXQjPbqPCVT/view?usp=sharing

### Steps to Reproduce

Please see the document above.

### Acceptance Criteria

Test and demonstrate that the issue is fixed.

### dotCMS Version

LTS 23.01

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

**Comment by damen-dotcms** [comment]
Dupe of #23915

**Comment by bryanboza** [comment]
Fixed, tested as part of the dupe #23915
