### ISSUE TITLE
Do not inject experiment code into customers html

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23943]
### Problem Statement

Looking at this code:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPIImpl.java#L320-L328

We have many customers who use pages to send back json or other types of content. 
- At this point we should never automatically inject experiment javascript code into customers html pages
-  We should have a viewtool that will spit out the required code that is simple to include in customer templates
- If we wanted to do this in the future, we would need some sort of config switch AND make sure they had analytics configured AND make sure they had experiments running AND make sure the page was returning html before injecting AND we would want to use `indexOf(String)` to do the replacement rather than scanning ALL the HTML which is going to be an expensive operation.  Bottom line, I don't think we should do it.
  

### Steps to Reproduce

Look at the source of dotcms.com - we are injecting javascript right after the `<head>` tag

### Acceptance Criteria

Don't inject the code.

### dotCMS Version

23.02

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/23943?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by hmoreras** [comment]
After testing the following code is not in the html anymore: 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/31667212/225685240-382c598d-bb90-4403-994e-dc7aede2aa7b.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF

**Comment by erickgonzalez** [comment]
Didn't found the experiments code in the html
