### ISSUE TITLE
Re-do Field Variable Logic

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#23942]
### Problem Statement

See document

### Steps to Reproduce

Steps are in the document shared above.

### Acceptance Criteria

Demonstrate that the issue fixed by posting results to the GH issue ticket.

### dotCMS Version

LTS: 23.01, 22.03
Latest release versions.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://drive.google.com/file/d/1MTTEMZj3822BYPZN4TkRLY0UPAW8vd5N/view?usp=share_link

**Comment by rjvelazco** [comment]
### Passed Internal QA
 
 - Tested on Docker image:  [`dotcms/dotcms:trunk_255430f `]
 
 ### Videos
 
 #### Reproduce the `issue` in the `demo` site
 
https://github.com/dotCMS/core/assets/72418962/72fa0e17-b3f7-406c-b6ad-4ec745a0f243

 #### Test the fix on `docker`

https://github.com/dotCMS/core/assets/72418962/b6d1cdce-fb36-427c-960a-ec4a39f6d147

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_bd37789**, Docker, macOS 13.0, FF v124.0.2

<img width="897" alt="Screenshot 2024-05-08 at 3 20 44 PM" src="https://github.com/dotCMS/core/assets/129882031/bdb9097d-bf7b-404e-bb28-1399dffc35a5">

<img width="897" alt="Screenshot 2024-05-08 at 3 22 04 PM" src="https://github.com/dotCMS/core/assets/129882031/6a515278-2a20-4ffa-809e-0116ace2406a">

<img width="897" alt="Screenshot 2024-05-08 at 3 22 17 PM" src="https://github.com/dotCMS/core/assets/129882031/bb1d34d2-97f2-4e75-ae7e-3722f0b5a758">
