### ISSUE TITLE
Clipboard has UX Issues after Dojo Upgrade

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23941]
[![Screenshot_2023-01-30_17-27-03.png](https://mrkr.io/s/63d7fde7a189f8eba0938873/2)](https://mrkr.io/s/63d7fde7a189f8eba0938873/0)

### Problem Statement
There are three different fonts and weights of text. (needs re-design)
The text is not aligned between each other or the box below.
Should we add a button with the option of adding an image to the clipboard?

### Steps to Reproduce
1. Edit a content with WYSIWYG field
2. Click on the "Clipboard" button

```[tasklist]
### Acceptance Criteria
- [x] Fix the alignment
- [ ] Use the system font
```

### dotCMS Version
All

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Rich-Text/b56cfea1-b78a-495f-af35-29de0af8cd0a](https://demo.dotcms.com/dotAdmin/#/c/c_Rich-Text/b56cfea1-b78a-495f-af35-29de0af8cd0a)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63d7fde7a189f8eba0938876_2d4007537d54bcb7?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 109.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1352 x 878</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1352 x 844</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by rjvelazco** [comment]
### Failed Internal QA

Docker Image: [`dotcms/dotcms:master_4ea0b063`]

#### Errors
1. There is not `Add image to clipboard` button.
2. If I `copy` an image and then open the `clipboard`, I am not able to see the image.
 
#### Video

https://user-images.githubusercontent.com/72418962/228972501-6afef3d8-f633-44cc-bdc3-c23c9d97f5b4.mov

**Comment by fmontes** [comment]
Is working
