### ISSUE TITLE
Improve startup performance

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23982]
### User Story

Starting a dotCMS instance against a large scale environment can take a long time.  One reason for this is that we need to load vanityUrls before we can serve content. If a customer has a lot of sites and a lot of VanityUrls, we have seen it take up to 8 minutes for dotCMS to start up and load.

### Acceptance Criteria

Faster time to start.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CSHTYUR7H/p1675277411732569

**Comment by nollymar** [comment]
PR: #24029

**Comment by josemejias11** [comment]
**Approved QA** - Tested with the provided dataset
