### ISSUE TITLE
SALES: Collaboration - support for annotations

### ISSUE THREAD

**Issue by stefan-dotcms** [dotCMS/core#23990]
### User Story

As a content editor, I'd like to create annotations on all content types and support collaboration with team mates and drive content velocity and time-to-value for my content projects.

References:

- Create annotations: https://doc.sitecore.com/ch/en/users/35/content-hub/marketing-resource-management--annotate.html
- Tools: https://doc.sitecore.com/ch/en/users/35/content-hub/content-user-manual--annotation-tools.html

### Acceptance Criteria

- Ability to create annotations
- Have the proper UI support for tooling around annotations

### Proposed Objective

Sales

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
Marked as closed as this issue is too stale.
