### ISSUE TITLE
SALES: Image Editor - sync the UI with the rest of the application

### ISSUE THREAD

**Issue by stefan-dotcms** [dotCMS/core#24004]
### User Story

The UI of the Image Editor looks from a different era.

The UI of the Image editor needs to match the rest of the dotCMS back-end UI.

It currently looks cluncky and a hack.

### Acceptance Criteria

The UI of the Image editor needs to match the rest of the dotCMS back-end UI

### Proposed Objective

Sales

### Proposed Priority

Priority 2 - Important

**Comment by damen-dotcms** [comment]
Dupe of #24015
