### ISSUE TITLE
Block Editor: Allow users to add options to the suggestion menu

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24032]
### Parent Issue
#21988 

### User Story

As a developer, I want to be able to add options to the suggestions menu to allow my content author to use my custom blocks from the block editor default UI.

### Acceptance Criteria

- Get actions from the field variables.
- Render the actions with the name and icon provided.
- Call the action (editor command) when the content author selected it.
- Show a warn is the command doesn't exist or throws an error.
- Make sure the block editor don't crash because of the custom action.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

```[tasklist]

```

**Comment by fmontes** [comment]
New errors in the console:

![Image](https://user-images.githubusercontent.com/751424/222255810-eaef2e44-cf1f-4377-8c06-0bd85efcde94.png)

If you pass the `customBlocks` and have no actions, it trows an error as well:

![Image](https://user-images.githubusercontent.com/751424/222256039-62c70e07-5e54-438a-ba51-939cfcf3e75a.png)

**Comment by fmontes** [comment]
Here is a video on how to do this: https://youtu.be/u5Lx1UZfCK8

**Comment by bryanboza** [comment]
Fixed, tested on release 23.03 // Docker // FF 

We need to doc how to do this as we explain in the video, I'll add the doc label
