### ISSUE TITLE
We are not respecting the widget language when you have a multilingual page have a working version in non-default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24059]
### Problem Statement

Related to #23890

When you have a multi-lang page, and this is associated with a multi-language widget. When you create a working version of the page in any language different from the default, we are showing the widget in the default language and not the page language  

### Steps to Reproduce

- Create a new page 
- Create a new widget with the following code 
```
#set($navRootLevel = $navtool.getNav("/ca/", 2))
#foreach($primaryLevel in $navRootLevel)
-----</br>
$primaryLevel.title</br>
#foreach($secondaryLevel in $primaryLevel.children)
$secondaryLevel.title</br>
#end
#end
```
- Create a version of the page in Spanish 
- Create the version of the widget in Spanish 
- Make sure we are showing the Spanish widget when you are on the Spanish page 
- Now create a working version of the Spanish page 
- Check the widget again (now we are showing the English version )

### Acceptance Criteria

We need to show the widget in the same language as the page 

### dotCMS Version

Tested on release-23.02 // Docker // FF 

### Proposed Objective

Application Performance

**Comment by erickgonzalez** [comment]
Customer ticket: https://dotcms.zendesk.com/agent/tickets/109808

**Comment by erickgonzalez** [comment]
Not reproducible in 22.03 LTS
