### ISSUE TITLE
Revisions to Default Workflow Action Names

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24068]
[![Screenshot_2023-02-09_16-24-08.png](https://mrkr.io/s/63e51e28b16123534d122faf/2)](https://mrkr.io/s/63e51e28b16123534d122faf/0)

### Problem Statement
The "Save" icon is confusing as the primary action written is "Publish", is better to write the word Save for every button that has that double action like Saving and Publishing.
Set the button as "Publish and Save"

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Images/6a0b27f7-2416-4424-abc4-2d13aade54ce](https://demo.dotcms.com/dotAdmin/#/c/c_Images/6a0b27f7-2416-4424-abc4-2d13aade54ce)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63e51e28b16123534d122fb2_eacb46f4f733e311?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 109.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1352 x 878</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1352 x 844</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by jdotcms** [comment]
This is just the name of the action on the system workflow, it can be renamed or even change the configuration

**Comment by damen-dotcms** [comment]
Let's make sure it's good, and then make those changes to the master file that gets deployed.

**Comment by damen-dotcms** [comment]
Hey @Melissa-dotCMS ,

What should the buttons say here. 

I think "save" means "publish" - seems to indicate that in the workflows. I don't think there is a save without publishing. 

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/114953617/223582552-bdfbbda2-e8c0-4a79-970f-7946d7a1a616.png">

Save

Save & Publish

**Comment by damen-dotcms** [comment]
This whole thing is super confusing if you aren't an expert in dotCMS. 

Like... how Save can mean "Published" when editing, but there's a "Save and Publish" when it's already published. But I think they mean the same thing. 

I think we just need to take off the "Save" by itself since that's the confusing step in my mind. 

But also... "Approve" means "Publish." 

I think we need to dig into all the words here. Tabling this for later.

**Comment by wezell** [comment]
The words and actions are 100% configurable by an admin in this screen.  If we need to make changes here, we need to be making them in our starter site.  Any changes to our starter will not be reflected in any current implementation as their workflows are already set up.
