### ISSUE TITLE
When Edit a Contentlet into A Experiment need to refresh the page to see the changes

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24065]
### Problem Statement

When you edit any Contentlet from a Page inside an Experiment you don't see the change immediately you need to refresh the page.
This is because when you edit any Contentlet inside the Edit Page Portlet we sent a hit to a end point to render the Contentlet with the change into the Container, We need to include the variantName query parameter in this request to render the Contentlet using the current variant.``

### Steps to Reproduce

- Create a Page
- Create a ContentType and add a test field call 'title'.
- Create a Container and add the newly Contentlet Type and the 'title' field to be render inside the Container
- Create one Contentlet of the newly created ContentType, use "DEFAULT VERSION" as 'title' value, publish it.
- Create a Page, change the layout to use the newly created Container and add the newly created Contentlet. 
- Create an Experiment using the newly Page
- Create  a Variant inside the Experiment and edit it, Change the title field value of the Contentlet to "VARIANT INSIDE TE EXPERIMENT VERSION".
- Save and close the Dialog, you can not see the change onto the page neither in PREVIEW nor EDIT Mode
- Refresh the page and now you can see the Page

### Acceptance Criteria

See any change make to a Contenlet immediately without refresh

### dotCMS Version

last in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

- [] Include the Query Params inside the Request to render the Contentlet.
- [] Make any change need into the Endpoint

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24065?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by dsilvam** [comment]
PR; https://github.com/dotCMS/core/pull/24159
