### ISSUE TITLE
[UI] Stop Experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24074]
### User Story

As a user, I want to be able to Stop a Running Experiment.

### Acceptance Criteria

- Show Stop Experiment only in Running Status
- When you click the Stop Experiment, the button needs to show a saving status
- The view needs to be updated with the status defined in the backend. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

Only Running experiments show the Stop Experiment Button.

**Comment by oidacra** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24074?planning-poker) with Zenhub @hmoreras

**Comment by oidacra** [comment]
`/{experimentId}/_end`

**Comment by freddyucv** [comment]
**Passed Internal QA:** it is working the follow was test:

- After Start an Experiment without Scheduling try to Stop it.
- After Start an Experiment with Scheduling try to Stop it.
- Try to Stop an Experiment but Cancel in the popup dialog.

**Comment by dsilvam** [comment]
@bryanboza we're going to change the terminology here. Basically you won't "Start" an Experiment if it has a Scheduling. The button will show as "Schedule Experiment". We'll let you know when this one is ready to re-test.

**Comment by dsilvam** [comment]
@bryanboza this was fixed in here https://github.com/dotCMS/core/issues/24585

**Comment by bryanboza** [comment]
Same thing again, we changed the terminology, but after you schedule an experiment, we don't have a way to cancel this job in order to modify something or simply if I don't want this experiment run

**Comment by dsilvam** [comment]
@bryanboza this is gonna be worked here https://github.com/dotCMS/core/issues/25108

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
