### ISSUE TITLE
Render Page with specific variant is not working with SYSTEM_CONTAINER

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24071]
### Problem Statement

When you try to render a Page using that use the SYSTEM_CONTAINER in a specific Variant is it render with the DEFAULT Variant.

### Steps to Reproduce

- Create A Page and use the SYSTEM_TEMPLATE.
- Add A Generic Content into this Page with a title of "DEFULT VERSION"
- Create an Experiment in this page and Crate a variant.
- Edit the Variant and edit the Contentlet change the title to "EXPERIMENT VERSION"
- Close the Dialog and you are not going to see the change.
- Even if you refresh the page is render with the DEFAULT version.

### Acceptance Criteria

- The page must be render with the specific variant when we are using the SYSTEM Container

### dotCMS Version

last in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24071?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
Really the bug was not just with the SYSTEM_CONTAINER 
The System Container use the $dotContentMao object to get the Contentlet title and other properties really the bug was with this Object was not setting right when we were using variants so The bug was going to happend with any Container that use the $dotContentMap object

**Comment by dsilvam** [comment]
Passed Internal QA: After changing the content title in the variant, it properly renders the changed title.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
