### ISSUE TITLE
Add a new Contentlet inside a Experiment is not working

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24072]
### Problem Statement

When you are editing a Variant into an Experiment and try to add a new created Contenlet inside the Page this new Contentlet is not render in the page

### Steps to Reproduce

- Create a Page.
- Create a new Experiment using this page.
- Create a new variant and Edit it.
- Add a new Contentlet into the Page, you must created a new Contentlet not use an already exiting Contentlet.
- Close de Dialog and the Contentlet is not render, even if you refresh the Contentlet is not render

### Acceptance Criteria

When you are editing a variant inside a Experiment and add a new created Contentlet into a Page, it must be render

### dotCMS Version

last in master

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24072?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now I'm able to upload a new piece of content from a variant without problems.
