### ISSUE TITLE
Started Experiments with an Schedule should become SCHEDULED instead of RUNNING

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24092]
### Problem Statement

The Experiments API is returning the Experiment in the wrong state. 

### Steps to Reproduce

1. Create a new Experiment
2. Set a Scheduling for the future
3. Start the Experiment 

It will become RUNNING instead of SCHEDULED

### Acceptance Criteria

* Steps above should result in a Experiment with SCHEDULED status.
* Postman test 

### dotCMS Version

master / 23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24092?planning-poker) with Zenhub @victoralfaro-dotcms @freddyucv @oidacra

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24112

**Comment by bryanboza** [comment]
Fixed, tested on release-23.03 // Docker // FF. 

Multiple improvements coming from UI/UX in a new cards
