### ISSUE TITLE
Add a Contentlet without DEFAULT Version into a Variant Page is not working

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24096]
### Problem Statement

When you EDIT a Variant and try to add a new Contentlet into  the Experiment's Page, the new added Contentlet is not render.

### Steps to Reproduce

- Create a Page
- Crate an Experiment and a Variant.
- Edit the Variant and go to the Edit Tab.
- Add a new Contentlet into the Page.
- The Contentlet is not showed when the page is render even when you refresh

### Acceptance Criteria

The new added Contentlet must be render.

### dotCMS Version

lastes in master

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24096?planning-poker) with Zenhub @dsilvam @victoralfaro-dotcms

**Comment by dsilvam** [comment]
Passed Internal QA: Adding a new Contentlet to the Page on a Variant displays the content right away without the need to refresh.

**Comment by bryanboza** [comment]
We are getting this NPE every time you add//remove a pice of content from a variant 
```
testing_mssql-dotcms-dev-1     | 18:42:41.686  ERROR concurrent.DotConcurrentFactory - null
testing_mssql-dotcms-dev-1     | com.dotmarketing.business.DotStateException: null
testing_mssql-dotcms-dev-1     | 	at com.dotmarketing.db.DotRunnableFlusherThread.run(DotRunnableFlusherThread.java:46) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotcms.concurrent.DotConcurrentFactory$DotConcurrentImpl.lambda$delay$0(DotConcurrentFactory.java:967) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotcms.concurrent.DelayedDelegate.executeDelegate(DelayedDelegate.java:47) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotcms.concurrent.DotConcurrentFactory$DelayQueueConsumer.run(DotConcurrentFactory.java:714) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at java.lang.Thread.run(Thread.java:829) [?:?]
testing_mssql-dotcms-dev-1     | Caused by: java.lang.NullPointerException
testing_mssql-dotcms-dev-1     | 	at com.dotcms.rendering.velocity.services.ContentletLoader.invalidate(ContentletLoader.java:670) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotcms.rest.api.v1.page.PageResourceHelper$1.run(PageResourceHelper.java:168) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotmarketing.db.DotRunnableFlusherThread.lambda$runNetworkflowCacheFlushThread$0(DotRunnableFlusherThread.java:29) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
testing_mssql-dotcms-dev-1     | 	at com.dotmarketing.db.DotRunnableFlusherThread.runNetworkflowCacheFlushThread(DotRunnableFlusherThread.java:29) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	at com.dotmarketing.db.DotRunnableFlusherThread.run(DotRunnableFlusherThread.java:43) ~[dotcms_23.05_5f0e862.jar:?]
testing_mssql-dotcms-dev-1     | 	... 9 more


```

**Comment by dsilvam** [comment]
Bug reported by @bryanboza fixed in https://github.com/dotCMS/core/pull/24631

**Comment by victoralfaro-dotcms** [comment]
Contentlet added to variant and rendered right away at edit:
![image](https://user-images.githubusercontent.com/64026161/232854446-7afb4879-96e7-4de1-a60d-f1b08c01ff72.png)
And preview:
![image](https://user-images.githubusercontent.com/64026161/232854674-73e6f20a-339c-431d-bc8f-033a5a59373b.png)
No errors found in the logs.

**Comment by bryanboza** [comment]
We need some work here: 

Following the provided steps after you add a new piece of content from a variant edit mode, after you try to edit this piece of content we are getting an error, and we are unable to edit 


![Image](https://github.com/dotCMS/core/assets/2641437/955bcc11-c2e0-435a-972d-b6d32de228eb)


Here the log: https://gist.github.com/bryanboza/e6d2a8743c8151f006703f8283ecf32b

**Comment by dsilvam** [comment]
Passed Internal QA: able to edit the newly created and added piece of content. Also original bug is still not happening.

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF
