### ISSUE TITLE
Make Visual Compare Tool use Equal Width Columns

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24109]
[![Screenshot_2023-02-14_16-42-14.png](https://mrkr.io/s/63ebb9e67e410184d5486ceb/2)](https://mrkr.io/s/63ebb9e67e410184d5486ceb/0)

### Problem Statement

Top align content in both, and make columns 50% so we're comparing apples to apples. It's impossible to quickly visually compare when the columns have different widths.

### Steps to Reproduce

Updated by @fmontes 

https://user-images.githubusercontent.com/751424/225406205-a5e6c960-8f3a-49e2-9f70-a95d02f78d32.mp4

### Acceptance Criteria

- [x] Make sure both side of comparison are equal with.

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://authoring.dotcms.com/dotAdmin/#/c/c_Documentation/4fd773c7-8b71-4aa9-acbc-529a2d325f6d](https://authoring.dotcms.com/dotAdmin/#/c/c_Documentation/4fd773c7-8b71-4aa9-acbc-529a2d325f6d)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ebb9e67e410184d5486cee_a854dd59e557cb4c?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2134 x 1200</td></tr><tr><td><strong>OS</strong></td><td>Windows 15.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2134 x 981</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.8000000715255737x</td></tr></table>

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** [`dotcms/dotcms:master_70229c6b`]



![Image](https://user-images.githubusercontent.com/72418962/227014106-f9eb822b-b9d5-402c-9fde-1e7e09d98afb.png)

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_03732ac4_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Top menu is breaking in compare view

![Screenshot 2023-04-06 at 2 58 40 PM](https://user-images.githubusercontent.com/129882031/230492935-4750f5f0-ba77-4ad4-b59e-ca55309c7088.png)

**Comment by zJaaal** [comment]
### Passed Internal QA

Docker Image: [`dotcms/dotcms:23.05_d8108e60_SNAPSHOT`]

https://user-images.githubusercontent.com/63567962/231867123-9cd9f89d-f4dc-48a4-857e-4c1764f0f2cc.mov
