### ISSUE TITLE
Update pg_dump to use postgres 15

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24119]
### User Story

`pg_dump` is backwards compatible but not future compatible.  Right now, we ship with `pg_dump` from postgres 13, which refuses to dump databases from postgres servers running version 14 or 15.

We need to update to pg_dump from version 15 so we can dump from postgres servers running version 14 or 15.

To reproduce, try to get a db dump (from the maintenance tools screen) from demo.

### Acceptance Criteria

We should be able to generate db dumps from postgres versions > 12 and <=15.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

**Comment by ken-slough** [comment]
Confirmed this as well with docker install, using dotCMS version 22.03.5 LTS
The current version of Ubuntu in the dotCMS container does not even allow a manual install of pgclient tools to coincide with version 15 of postgres. Only work around is to manually pg_dump data from the db container.

**Comment by erickgonzalez** [comment]
same as https://github.com/dotCMS/core/issues/24689
