### ISSUE TITLE
Create a developer docker environment

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24116]
### User Story

As a dotCMS developer, it would be very helpful if I could run a docker image that would 
1. Contain everything that is needed to run dotCMS, db, opensearch and dotCMS
2. Could be pointed to an environment to clone
3. And could be used to run dotCMS in debug mode for plugin development

### Acceptance Criteria

Create an all in one dotCMS environment
- a single image/ no docker-compose
- be able to clone another dotcms instance (with a user/pass or token)
- runs dotCMS in development mode 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Internal QA:** Passed
It works really nice and saves tons of time!
