### ISSUE TITLE
Form builder has no save function

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24127]
[![Screenshot_2023-02-15_23-36-27.png](https://mrkr.io/s/63ed6c7bb329723033401992/2)](https://mrkr.io/s/63ed6c7bb329723033401992/0)

### Problem Statement
It appears to autosave, but you'd never know that. 

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/forms/edit/c62c4c46692d1190fe55708a2c6887c2](https://demo.dotcms.com/dotAdmin/#/forms/edit/c62c4c46692d1190fe55708a2c6887c2)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ed6c7bb329723033401996_92586e22c3354d63?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2134 x 1200</td></tr><tr><td><strong>OS</strong></td><td>Windows 15.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2134 x 1030</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.8000000715255737x</td></tr></table>

**Comment by fmontes** [comment]
It works this way.
