### ISSUE TITLE
Time machine first view

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24126]
[![Screenshot_2023-02-15_23-27-03.png](https://mrkr.io/s/63ed6a47dcf61891b66348c7/2)](https://mrkr.io/s/63ed6a47dcf61891b66348c7/0)

### Problem Statement
Select snapshot above makes no sense. awful icon, tiny font. there's no context for the two drop-down boxes, which when toggled on past the dropdowns do nothing (on demo site). If you go to future, you can select a date in the first and something else (language) in the second? Then once you do select those from the mystery dropdowns, it takes you to a page preview with a fast black modal notice that says something like "close the preview when you're done" then it goes away and there's no close button or indication it's a preview. The close button happens to be hiding in the blue circle in the upper right. 

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/time-machine](https://demo.dotcms.com/dotAdmin/#/c/time-machine)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ed6a47dcf61891b66348ca_c281fe04f6988022?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2134 x 1200</td></tr><tr><td><strong>OS</strong></td><td>Windows 15.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2134 x 1030</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.8000000715255737x</td></tr></table>

**Comment by swicken-dotcms** [comment]
Closing due to feature deprecation/replacement being planned: https://github.com/dotCMS/core/issues/27826
