### ISSUE TITLE
Customer not able to download data/assets

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24125]
### Problem Statement

A customer in 21.06.13 is trying to download data/assets but keeps getting the following error:
```
ERROR util.ExportStarterUtil: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870) ~[?:?]
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487) ~[?:?]
at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426) ~[?:?]
at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:?]
```
I investigate this and found out that the problem seems to be related to some customer roles, but there isn't anything weird about them.

I created the same roles on a local instance of 21.06 LTS and can't reproduce it.

I discussed this a bit with @jdotcms and agreed that this logic needs some refactoring. https://github.com/dotCMS/core/blob/e57fe35469a4e63208190368ca4ec9bf379e8f09/dotCMS/src/main/java/com/dotmarketing/business/Role.java#L165-L182

### Steps to Reproduce

Contact support for customer dataset.

### Acceptance Criteria

You should be able to download the data/asset successfully.

### dotCMS Version

21.06 LTS

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer ticket: https://dotcms.zendesk.com/agent/tickets/109742

**Comment by swicken-dotcms** [comment]
Solved by https://github.com/dotCMS/core/issues/23877
