### ISSUE TITLE
User is unable to lock content because of validation limit on locked_by column of contentlet_version_info

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#24133]
### Problem Statement

Needs to increase character length limit of locked_by column of contentlet_version_info.
If the user id character length from the user_ table is greater than 36 then the user is unable to lock the content.
Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/110022.

### Steps to Reproduce

1. login to the demo site
2. create a new user and give appropriate permissions to create or edit the content.
3. Change the user-id from the user__ table in the database and set the length greater than 36.
4. Now login with newly created user credentials and try to lock the content.
5. See the toast error on the screen.

### Acceptance Criteria

Customers coming from pretty old versions go through this UT `Task00795LiveWorkingToIdentifier` which creates tables with 36 lengths.

We need a UT which updates the `locked_by` to 100 for the following tables, just for Postgres:
- contentlet_version_info
- container_version_info
- template_version_info
- link_version_info

### dotCMS Version

22.03.4

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

```
ERROR: value too long for type character varying(36){
  "SQL": ["UPDATE contentlet_version_info SET working_inode=?, live_inode=?, deleted=?, locked_by=?, locked_on=?, version_ts=? WHERE identifier=? AND lang=?"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    "86d192d9-e480-437e-a44b-c513a7e8f14d",
    "86d192d9-e480-437e-a44b-c513a7e8f14d",
    false,
    "5b3b6246b6b69ad75d8f4a33492299d0ba4440b4e9f38b54588b5984738ac894",
    "2023-02-13 08:14:14.162",
    "2023-02-10 09:24:08.237",
    "61ac84bc-fd71-432f-90a0-5d3565e516c6",
    1
  ]
}

```

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on release-23.06 // Docker // FF
