### ISSUE TITLE
Bring WYSIWYG Controls Down to Content

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24136]
[![Screenshot_2023-02-16_16-14-48.png](https://mrkr.io/s/63ee5678d881a43e0d4b29ba/2)](https://mrkr.io/s/63ee5678d881a43e0d4b29ba/0)

### Problem Statement
When you click to edit inline, the WYSIWYG controls need to show up next to the content; currently they float above it about 200 px.

Also, it auto-saves but there is no message saying it auto-saved.

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://authoring.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fsecurity%2Fsecurity-at-dotcms&language_id=1&host_id=8a7d5e23-da1e-420a-b4f0-471e7da8ea2d](https://authoring.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fsecurity%2Fsecurity-at-dotcms&language_id=1&host_id=8a7d5e23-da1e-420a-b4f0-471e7da8ea2d)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ee5678d881a43e0d4b29bd_62451aaefc80ce47?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2134 x 1200</td></tr><tr><td><strong>OS</strong></td><td>Windows 15.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2134 x 1030</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.8000000715255737x</td></tr></table>

**Comment by fmontes** [comment]
Not happening.

![Image](https://github.com/dotCMS/core/assets/751424/b33131e4-cb31-4093-8b8d-df214a3501be)

**Comment by damen-dotcms** [comment]
Hey @fmontes what's the reason not to do this one?

**Comment by fmontes** [comment]
@damen-dotcms tested in latest and is working
