### ISSUE TITLE
SAML Allow Users with repeat email

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#24138]
### User Story

As a client I want to be able to have the same users on diff IDP, but with diff users ids.
The user will set a property on the SAML config to allow users with diff id but same email

saml.allowuserswithdiffid.repeatedemail=true

When this property is on, instead of using the normal approach to look for the user by id/fallback email, will look for only by identifier, if the user does not exists but the email already exists, the user email coming from the SAML will be modified with the goal to avoid conflicts with the user email constraints

### Acceptance Criteria

Users with multiple IDPs with repeat user will be able to get login with SAML by faking the email

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/24184/files)

**Comment by fmontes** [comment]
@erickgonzalez did you add this to the LTS?

**Comment by fmontes** [comment]
Deployed to customer and working.
