### ISSUE TITLE
System Host is not selectable in Site/Folder field

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#24147]
### Problem Statement

If there is a host/folder field added to a content type, and then the content is added to a particular host such as in the following example:

https://user-images.githubusercontent.com/1569167/219488497-c395a0b4-3e5f-4180-b6f2-610dada0233c.mp4

We need to be able to always select "System Host" to make content global when content is first saved and when it is later edited.  "System Host" should not disappear as an option.

### Steps to Reproduce

Add a new host, then edit a piece of content that has a host/folder field from a new content type.  All hosts and system host should be selectable.

### Acceptance Criteria

"System Host" should not disappear as a selectable option when editing or creating content

### dotCMS Version

demo.dotcms.com - 23.01

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
@DeanGonzalez are you still able to repro this?

**Comment by erickgonzalez** [comment]
this was fixed here https://github.com/dotCMS/core/issues/24908

**Comment by prestonso** [comment]
Please close when fixed @erickgonzalez! Closing.
