### ISSUE TITLE
CMSFilter updating language param

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24158]
### Problem Statement

Using rules to redirect a language change is not working as it should when params are sent.

### Steps to Reproduce

1- Create 2 Rules as the following (one with English and one with Spanish):
<img width="1391" alt="Screenshot 2023-02-17 at 11 32 30 AM" src="https://user-images.githubusercontent.com/5278970/219755467-82f14935-8961-4b2d-916d-dbdef3cf83f1.png">

2- Hit from the FE the following pages, (just change the language part of the URL):
- When hitting `/es/index` should show Spanish page
- When hitting `/en/index` should show English page
- When hitting `/es/index?test` should show Spanish page
- When hitting `/en/index?test` should show English page

### Acceptance Criteria

Language should be consistent and should show the right page.

### dotCMS Version

23.01 LTS and demo (23.02)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer ticket: https://dotcms.zendesk.com/agent/tickets/109906

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_accf5f2d_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
