### ISSUE TITLE
Vanity URLs/ Redirect browse issue

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24156]
[![Screenshot_2023-02-17_16-07-39.png](https://mrkr.io/s/63efa64bedf9a4a79ebe2382/2)](https://mrkr.io/s/63efa64bedf9a4a79ebe2382/0)

### Problem Statement
If I click the "click here to browse" button, it opens the browser dialog, but then quickly logs me out and takes me to the login screen. 

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://authoring.dotcms.com/dotAdmin/#/c/vanity-urls/d2ab6537-a4b5-4b92-b376-bb518d489623](https://authoring.dotcms.com/dotAdmin/#/c/vanity-urls/d2ab6537-a4b5-4b92-b376-bb518d489623)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63efa64bedf9a4a79ebe2385_9c40fd7498d0f9bc?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2134 x 1200</td></tr><tr><td><strong>OS</strong></td><td>Windows 15.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2134 x 973</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.8000000715255737x</td></tr></table>

**Comment by damen-dotcms** [comment]
Hey @fmontes ,

What's going on with this one?

**Comment by erickgonzalez** [comment]
Not Reproducible in latest.
