### ISSUE TITLE
Build master docker image on every merge

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24157]
We always need a current dotCMS master image.  We should build and push one on every merge to master.

**Comment by damen-dotcms** [comment]
Hey @wezell ,

Are you concerned about using too many GitHub action minutes if we do this every merge?

@fmontes suggested nightly builds. Would that work?

**Comment by wezell** [comment]
Not worried about the minutes at all. We just need to add the action. I
would start by doing it on every merge.  We will need another job to delete
old master builds from dockerhub.

**Comment by wezell** [comment]
This is completed
