### ISSUE TITLE
Fix MSSQL Integration test performance and timeout issues

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#24169]
MSSQL integration tests are consistently taking much longer to run and often timing out the entire test run.   We need to identify the cause of this and understand whether this is an infrastructure issue with the test environment or something that could be impacting the performance of our customers in production.   WorkflowAPITest seems to be a good proxy for this issue.   Possible causes for the slowness need to be investigated.

- Insufficient resources allocated to the docker container running MSSQL in test
- Differences in locking behavior between Postgres and MSSQL,  MSSQL can lock a whole table in a transaction that may be blocking requests.
- Impact of missing indexes on essential tables.   This could be made worse if the tables themselves are getting larger.   Larger tables may be occurring  if preceding tests are not fully cleaning up test data.   This should be suspected if the tests seem to not be impacted the same when running locally on an individual test class with a clean database.   If this is the case the missing indexes should be resolved as we are likely to have similar if not more data in a production system.

The risk of not fixing this issue is that we are not able to properly asses any impact on MSSQL of any changes we make.  This puts a large risk of a release breaking any customer that uses MSSQL.  We may easily introduce code that will break on MSSQL and not pick it up in testing, or make a large impact on performance without the ability to know in advance.

**Comment by spbolton** [comment]
There are two main parts to this issue.  Firstly we were making a request to the DB every time we requested for a connection from DbConnectionFactory, regardless of whether the connection was created or pulled from the connection pool.  There was no check also to see if the connection was already at the correct isolation level.  This issue causes at least a 20% overhead in running on tests and maybe more where we request connections frequently.

There are also failures in the processing based upon a difference in the transaction isolation level set for MSSQL vs Postgres.    Postgres uses the default READ_COMMITTED isolation, but we were setting MSSQL to use SNAPSHOT_ISOLATION.   This is causing some tests to fail as the code is expecting to see changes from a different transaction.    SQL Server defaults to READ_COMMITTED but out of the box handles a little differently than Postgres, it will lock tables aggressively and if used in DotCMS will cause locking and slow down concurrent processing.    SQL Server has a DB option that can be enabled called READ_COMMITTED_SNAPSHOT as well as ALLOW_SNAPSHOT_ISOLATION.  These enable row level snapshotting that then mimics the behavior of Postgres.   This option affects the functionality when using READ_COMMITTED isolation level.    There is also a separate SNAPSHOT_ISOLATION level that can be set,  this is a higher isolation level and guarantees repeatable reads and is closer in behavior to the higher SERIALIZABLE isolation it requires ALLOW_SNAPSHOT_ISOLATION feature to be enabled but is separate to the behavior change when using  READ_COMMITTED isolation level.    We do need the DB options enabled on SQL Server, but we should always use READ_COMMITTED in the current system to get the correct behavior across databases unless we can change the code to work at a higher level.  Our existing customers should have READ_COMMITTED_SNAPSHOT and ALLOW_SNAPSHOT_ISOLATION enabled, and we have these set as required for setup in our documentation.  It may help to have a check on startup to ensure that these are actually set.

**Comment by erickgonzalez** [comment]
Since we're not longer supporting MSSQL this ticket will be closed.
