### ISSUE TITLE
Organize CLI commands  in sub-commands

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#24168]
Commands must be organized so that all related operations are placed together under one common command 
the main should serve as the umbrella for all related sub-commands like this:

```
contenttype             pull                       varname
(Main command).   (subcommand).   (Options and or Parameters)
```

here some examples 

```
dotcli site --help
dotcli site pull demo.dotcms.com
```
where dotcli is the name of the cli-it self. followed by the main command and then the sub-command

Additionally 
sub-commands like site pull  or content-type pull must work directly using an option that represents the site name or the content-type variable name respectively

Pull commands should always save pulled info in a file 
where the file name is confirmed by the content-type variable  
or site-name followed by the respective extension (json,yml)

Also, the pulled info must be presented completely on screen 

Acceptance Criteria

1. dot-cli commands must be organized using subcommands as it was explained above
2. pulled info should always get saved in files using var-name or site name

**Comment by fabrizzio-dotCMS** [comment]
https://github.com/dotCMS/core/pull/24144

**Comment by nollymar** [comment]
- [ ] Use of param -idOrVar should be standardized for content types/sites commands, sometimes it is required as `idOrVar=XX`, others `idOrName=XX` or just `XX`
- [ ] Please check out doc for params, sometimes the `--help` option displays params that don't apply for some commands
- [ ] Improve the doc for copy site command, it's a bit confusing
- [ ] The description doc for `host push` and `host pull` is the same "Retrieves sites....."

**Comment by nollymar** [comment]
**Internal QA:** Passed
