### ISSUE TITLE
UI - Favorite Page portlet: Add empty state design on contentlets table

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24161]
### Parent Issue
#22343 

![image](https://user-images.githubusercontent.com/37185433/219765781-fbfd3fa2-2d08-4ecd-b0f9-539f8d1471e3.png)

design mock - WIP

**Comment by fmontes** [comment]
![Image](https://user-images.githubusercontent.com/751424/233150723-4f6f615d-4e03-4bb1-b25a-9aaa54f221c7.png)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_a44c4a30_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
![Screenshot 2023-05-11 at 10 51 41 AM](https://github.com/dotCMS/core/assets/129882031/a1b78350-e462-4a86-a749-ed67a12e3b3a)
