### ISSUE TITLE
Relationship fields couldn't update with workflow apis

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#24167]
### Problem Statement

When workflow action apis use to update/add relationship fields for a contentlet then there are two behaviors occur.

1. It returns a message with Exception If space uses between queries.
Example:  
```
"contentlet": {
    "regions":"(+contentType:Region) +identifier:994d34aaf93f98c90a666d6fef537812"
  }
  
  OR
  
   "contentlet": {
    "regions":"(+contentType:Region) +Region.title:('PSGNU058')"
  }
```

Response:

`{"message":"The map contains an invalid value: class com.dotmarketing.portlets.structure.model.ContentletRelationships"}`

2: It returns contentlet data but didn't update relationship field however the last update date change for contenlet

Example:
```

 "contentlet": {
  "regions":"(+contentType:Region)+Region.title:*Asia*"
  }


```
Response:
Contenlet data in json -- Omit that response for bravery 

### Steps to Reproduce

Create two contenttypes e.g Movie, Region

Create a relationship field one-to-many in Movie with Region

Create two Region contentlets e.g Asia, Africa

Create a contenlet of Movie and don't assign region to it yet because try to add with Workflow API

At last do REST api call with correct identifier and inode

```
curl -X 'PUT' \
  'https://demo.dotcms.com/api/v1/workflow/actions/b9d89c80-3d88-4311-8365-187323c96436/fire?identifier=33c53dd87135947b76147a347a765424&language=-1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "contentlet": {
    "regions":"+contentType:Region +Region.title:*Asia*"
  }
}'
```

### Acceptance Criteria

If REST body is correct then Workflow REST api should update relationship field according to data otherwise should return meaning full error response.

### dotCMS Version

23.0.1

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110108

**Comment by fmontes** [comment]
Needs to check the PR

**Comment by fmontes** [comment]
@jcastro-dotcms Please check the PR, fix the conflicts, run the tests and let's internal QA this.

**Comment by waqasakramdot** [comment]
A customer is hitting this indirectly. https://dotcms.zendesk.com/agent/tickets/113060

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: PASSED
Relationship fields can be successfully updated via the Workflow API now. Here are the steps to reproduce:

1. In your `docker-compose.yml` file, set the following environment variable:
```
DOT_CONTENT_APIS_ALLOW_ANONYMOUS: 'WRITE'
```
2. Create a Content Type called `Region` with the following field:
2.1 `Text` field named `Title`.
3. Create another Content Type called `Movie` with the following fields:
3.1. `Text` field named `Title`.
3.2. `Relationships` field named `Regions`, pointing to the `Region` type and selecting the `One to many` cardinality.
4. Create two Contentlets of type `Region`:
4.1. Title = `Asia`
4.2. Title = `Africa`
5. Create a Contentlet of type `Movie` with the title `My New Movie`, but **DO NOT ADD** any Region to it, as it'll be added via cURL.
6. Copy the Identifier of the `My New Movie` Contentlet and paste it in the following cURL command:
```curl
curl -X 'PUT' -u "admin@dotcms.com:admin" \
  'http://localhost:8080/api/v1/workflow/actions/b9d89c80-3d88-4311-8365-187323c96436/fire?identifier=<CONTENTLET_IDENTIFIER_HERE>&language=-1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "contentlet": {
    "regions":"+contentType:Region +Region.title:*Asia*"
  }
}'
```
7. Check the `My New Movie` Contentlet in the dotCMS back-end, and make sure it's related to the `Asia` Region now.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0

**Comment by bryanboza** [comment]
Fixed, tested on master, following the provided steps and now it is working as expected 
![image](https://github.com/dotCMS/core/assets/2641437/3c7921fb-ea02-4280-be53-51d05618009b)
