### ISSUE TITLE
Block editor - Write documentation for the remote extensions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24165]
### Parent Issue

#21988 

### Task

Create the documentation on how to include remote extensions to dotCMS block editor.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Complete this doc: https://docs.google.com/document/d/1Dcg-CTZw8o4fFB8GXq6ECj7pmoYR34CM7kE02lXykRM/edit#
- [ ] Talk with @jdcmsd to make sure he have all that is need it.
```

**Comment by manuelrojas** [comment]
https://docs.google.com/document/d/1Dcg-CTZw8o4fFB8GXq6ECj7pmoYR34CM7kE02lXykRM/edit#
