### ISSUE TITLE
UI - Favorite Page portlet: add / edit favorite page from context menu

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24160]
### Parent Issue
#22343 

### Task
As an user I want to be able to Create/Edit a favorite page directly from the listing table context menu (currently to create a new favorite page a user needs to go first to EDIT MODE and click on the star icon to create it)

![image](https://user-images.githubusercontent.com/37185433/219758482-6aa3899b-dc83-4fa6-85bf-2e601cb1050d.png)

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- On the context menu a new option for Add/Edit Favorite will be added
- if option selected, then the ADD/EDIT Favorite dialog will be shown with the page data

**Comment by zJaaal** [comment]
### Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_21c1c10b_SNAPSHOT]`


#### Screenshot
https://github.com/dotCMS/core/assets/63567962/e555ebc4-fd5f-4ed3-9fe2-77ef13c78d29

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_8c0a542e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
