### ISSUE TITLE
[Containers] : Save button is disables under specific circumstances

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#24164]
### Problem Statement

The `SAVE` button is not being enabled when trying to add a new Content Type to a new Container.

### Steps to Reproduce

1. Go to the new Containers portlet: http://localhost:8080/dotAdmin/#/containers and create a new Container.
2. Type in "1" in the `Max Contents` field, so that the `Content Type Code` field shows up.
3. Click the "+" button and add the `Contact` content type.
4. Type in any code in there.
5. The `SAVE` button is not enabled. Even if you try to change the Container's name or description, it remains disabled.

### Acceptance Criteria

The `SAVE` button must be enabled after any change is made.

### dotCMS Version

Latest master.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Found during IQA of https://github.com/dotCMS/core/issues/23443

### Assumptions & Initiation Needs

If you type in any characters for the default `Activity` content type, then the `SAVE` button is enabled. This is the only way to make it work. So there seems to be a problem with JS events at some point?

**Comment by rjvelazco** [comment]
### Passed Internal QA

Docker Image: [`dotcms/dotcms:master_bd915908`]


https://user-images.githubusercontent.com/72418962/222325779-62af6f27-edcd-4ccb-8bd1-5d08acf5fb4c.mov

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_5ce847f3_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
