### ISSUE TITLE
UI - Favorite Page portlet: Refresh Page portlet's data when site changed

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24172]
- current behaviour:on the Pages portlet page when you have multiple sites and you change site, the list of page contentlets shown on the table is not updated

- expected behaviour: on the Pages portlet page when you have multiple sites and you change site, the list of page contentlets shown on the table needs to be updated

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24175/files

**Comment by nollymar** [comment]
Internal QA: Needs work

When a site doesn't have pages, the table is not refreshed correctly



https://user-images.githubusercontent.com/8741395/221942658-a4dcb865-5b5e-4167-b288-9331f6d4ece8.mov

**Comment by alfredo-dotcms** [comment]
Note to QA: @wezell decided that the Favorites section needs to list favorite pages of all sites, so changing the current site won't have any effect on that listing.

**Comment by alfredo-dotcms** [comment]
@nollymar on the page's table the content is being reloaded (you can check it with another site with content) but on the scenario you found it seems like is loading forever, that's because the other site has no contentlets at all (empty state). 

There's another task https://github.com/dotCMS/core/issues/24161 to address that empty state design.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_3d55dd2c_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
