### ISSUE TITLE
UI - Favorite Page portlet: Create context menu for workflow action on right click - listing table

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24174]
### Parent Issue
#22343

**Comment by rjvelazco** [comment]
## Fail Internal QA

**Docker Image**: [`dotcms/dotcms:master_3b0b1cfc`]


### Steps to reproduce.

1. Open the context menu using the `right click`.
2. Scroll on the list.
3. The context menu gets fixed on the screen.



https://user-images.githubusercontent.com/72418962/235934411-9be8bae8-561e-4fc9-9e80-c593f387026d.mov

**Comment by fmontes** [comment]
Needa internal QA again.

**Comment by zJaaal** [comment]
Working on an Issue reported by @josemejias11 where Context Menu is not working for Favorite Panel 3 Dots

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_21c1c10b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
