### ISSUE TITLE
Content Search: Add "host" fields to all the content types search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24194]
### Parent Issue

#23599 

### User Story

As a user, I want to be able to search for any content types using within the file system or using the folders as filter field.

### Acceptance Criteria

- [x] Add host field to filter **under "type"** for ALL content types
- [x] Keep the host field filter applied when change type field
- [ ] ~In the content type field editor, remove the "User Searchable" checkbox in the host field (Angular)~

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

1. Make the system host searchable by default in the backend
2. If the field is searchable by default, it should pop up in the frontend.

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** `dotcms/dotcms:master_e3b29163`


https://user-images.githubusercontent.com/72418962/224056579-ae51d994-5ecf-4749-bbb4-cb760b4f1e07.mov

**Comment by wezell** [comment]
Clear button needs to clear the host/folder selection.

![Image](https://user-images.githubusercontent.com/934364/225652395-c5c67960-4a76-477e-9b19-bfb50064ac6e.png)

**Comment by fmontes** [comment]
The clear is clearing the filter, but the host field is keeping selected the folder, needs to fix the UI.

**Comment by rjvelazco** [comment]
### Note for QA:

We will be working this acceptance criterion: _In the content type field editor, remove the "User Searchable" checkbox in the host field (Angular)_, in this card:   https://github.com/dotCMS/core/issues/24290

**Comment by bryanboza** [comment]
According to the discussion in slack we need to show this field always under the advances filter. 

Right now we are not ignoring at all the value of this checkbox. 

- If you enable the check, this is showing under advanced 

![Image](https://user-images.githubusercontent.com/2641437/234053972-7f1061d4-bae1-4a2f-8117-599dcbbbf51e.png)

- But if you disable this, we are showing in the regular search 

![Image](https://user-images.githubusercontent.com/2641437/234054169-901fef34-4dbd-4360-863b-38aa912adc95.png)

**Comment by fmontes** [comment]
We need to make sure that the host is ALWAYS under "Advanced"

**Comment by fmontes** [comment]
Showing always under advanced.

**Comment by bryanboza** [comment]
Fixed, now we are always showing this filed in the advanced search. Tested on release-23.05 // Docker // FF
