### ISSUE TITLE
[UI] Move input 'Set Name of the Goal' outside of the conditions of Reach_Page goal

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24197]
### Parent Issue

https://github.com/dotCMS/core/issues/22770

### User Story

As a user, I want to add the `Name of goal ` for Reach Page or Bounce Rate

### Acceptance Criteria

Input `Name of goal` as the first input and the selection of goals second.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="557" alt="Screenshot 2023-02-23 at 3 22 13 PM" src="https://user-images.githubusercontent.com/1909643/221022239-fc0c7a10-8931-44f2-8b33-4c1a62861f4c.png">

**Comment by oidacra** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/24197?planning-poker) with Zenhub @hmoreras

**Comment by freddyucv** [comment]
**Passed Internal QA:** It is working the follow was check

- The Goal's Name es mandatory
- The apply button is disabled meanwhile the name is not set
- The name is always showed after set

![Image](https://user-images.githubusercontent.com/10408015/225075054-00a6732f-1101-42d5-817a-76600efade23.png)

**Comment by bryanboza** [comment]
After some discution we need some variations here: 

- We need to change the fields order, at put name as last 
- We need to remove the pre-set value "Primary Goal"
- We need to double check this functionality since we are not updating the name in the selection 
![image](https://user-images.githubusercontent.com/2641437/231904525-890e3b96-f6df-4d51-88fb-06e810f3cccc.png)

**Comment by dsilvam** [comment]
In addition to @bryanboza's input we will pre-fill based on the selected metric  but adding a "goal" to the Metric: 

Reach Page -> Maximize Reaching a Page
Bounce Rate -> Minimize Bounce Rate

This will be modifiable by the User.

**Comment by victoralfaro-dotcms** [comment]
Name required:
![Image](https://user-images.githubusercontent.com/64026161/232934987-5b21c614-fa21-4147-9608-556bfd275728.png)
Name set:
![Image](https://user-images.githubusercontent.com/64026161/232934951-ff7ca568-6db7-41a5-9d2c-684ef075f38f.png)
Goal option changed:
![Image](https://user-images.githubusercontent.com/64026161/232935183-a3de3d39-0b66-40e3-ae76-dc1679f9b295.png)
Goal saved:
![Image](https://user-images.githubusercontent.com/64026161/232935300-545e61f9-65f0-4f24-a61e-a11775cd7e3d.png)

**Comment by bryanboza** [comment]
We set the max length to 50 characters, since this can be en explicative name we need to change this to 255 characters at least 

![Image](https://github.com/dotCMS/core/assets/2641437/b32fff1b-a86f-4039-8245-867fb591efc3)

**Comment by oidacra** [comment]
https://github.com/dotCMS/core/pull/25146 @dsilvam @bryanboza

**Comment by dsilvam** [comment]
Passed Internal QA: new limit of 255 for Goal Name.
