### ISSUE TITLE
Cache Stats displays incorrect TTL for Caffine Memory Cache regions using default "indefinite" TTL

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#24199]
### Problem Statement

Cache stats displays "100s" for cache regions using the default TTL, which is incorrect. The default TTL is basically forever - INTEGER.MAX seconds.

<img width="589" alt="Screenshot 2023-02-23 at 2 17 28 PM" src="https://user-images.githubusercontent.com/628954/221039437-d2493b04-f788-42f4-aee5-d503681f9e47.png">

When setting a custom TTL, for example
`DOT_CACHE_CONTENTLETCACHE_SECONDS: '456'`
the custom TTL value is correctly displayed.

### Steps to Reproduce

Log into demo.dotcms.com

Settings -> Maintenance -> Cache -> Refresh Stats

### Acceptance Criteria

Display correct TTL in Cache Stats

### dotCMS Version

All supported versions

### Proposed Objective

Core Features

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://dotcms.slack.com/archives/CSHTYUR7H/p1677180023116509

**Comment by yolabingo** [comment]
@jdotcms

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/24212/files)

**Comment by bryanboza** [comment]
Fixed, after the change now we are showing infinity in some specific cache regions. 

Tested on release-23.05 // Docker // FF
