### ISSUE TITLE
Image resize controls on the edit content screen don't do anything

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24195]
[![Screenshot_2023-02-23_18-44-01.png](https://mrkr.io/s/63f7b3f10500c17e13ceb6e4/2)](https://mrkr.io/s/63f7b3f10500c17e13ceb6e4/0)

### Problem Statement
Image resize controls on the edit content screen don't do anything. See screenshot.

### Steps to Reproduce
1. Edit a piece of content that has an image filed.
2. Browse and select an image
3. Try to use the zoom in and out.

### Acceptance Criteria

- [x] Removed the control
- [x] Clean up the code if needed.

### Sub-Tasks & Estimates

---

**Reported by:** Jason A Smith (jason@dotcms.com)

**Source URL:** [https://mlh-temp.dotcms.site/dotAdmin/#/c/c_Services/a1e25423-6eef-4ac3-8cbc-33307acd2bdc](https://mlh-temp.dotcms.site/dotAdmin/#/c/c_Services/a1e25423-6eef-4ac3-8cbc-33307acd2bdc)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63f7b3f10500c17e13ceb6e7_4fd7530b4f8e8de5?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 110.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3840 x 1600</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.1.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1968 x 1122</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by wezell** [comment]
Only affects community edition customers.

**Comment by manuelrojas** [comment]
### Internal QA results:

Controls has been removed.

`Tested on: dotcms/dotcms:master_SNAPSHOT`

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/3438705/225429778-806f86ba-1525-4c4f-8c9d-c50eb6674999.png">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_054e1d36_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
