### ISSUE TITLE
Favorite Pages View: Edit Mode must consider language and device

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24219]
### Parent Issue

#22343

### Problem Statement

If I click on a page using the new pages list, it takes me to the Edit Mode without respecting the page language and the default device. 

### Steps to Reproduce

1. Using full starter, open any existing page in English from the new Pages view.
2. Once in Edit Mode, change the device
3. Go back to the Pages View and open a page in Spanish (for example: Destinos)
4. You should see the Edit Mode in English and the last selected device

https://user-images.githubusercontent.com/8741395/221628050-3f97a21a-dbaf-4631-8737-9f8baa03b0ce.mov

### Acceptance Criteria

When I click on any page from the list, it should behave the same way the site browser does, respecting page language and device.

### dotCMS Version

23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24232/files

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_2e52dde7_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
