### ISSUE TITLE
Add number of pages in the contentlet HTML

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24217]
### Parent Issue

#23223

### User Story

As a developer, I want to be able to know if a contentlet is being used on more than one page.

We need to ask the user if he would like to edit a contentlet just for the page it's being edited, or for all the pages that use that contentlet.

The page builder uses `data-attr` to get all the information about a contentlet or container (identifier, inode, lang, etc.), we need to add the number of pages as well.

### Acceptance Criteria

- [ ] Add `data-dot-on-number-of-pages="N"` to the `<div data-dot-object="contentlet">` element.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

http://localhost:8080/api/v1/page/render/test?language_id=1&mode=EDIT_MODE

In this enpdoint you will get the "rendered" property is where the HTML comes.

**Comment by hassan-mustafa-baig** [comment]
Functionality has been added. Check the response on my branch **issue_24217**

![image](https://user-images.githubusercontent.com/111717530/222304013-0793775f-e3ce-4b6f-9785-fd10d71891eb.png)

**Comment by rjvelazco** [comment]
### Fail Internal QA

Docker image: `dotcms/dotcms:master_b6f00959`

#### Error: The attribute `data-on-number-of-pages` is always `0` with new `contentlets`.

Step to reproduce:

1. Create a new `contentlet`. I create a `rich text`.
2. Add the new `contentlet` to multiple pages.
3. Go to any page that has that `contentlet`.
4. Go to edit mode.
5. Inspect the element and see its attributes.
6. See the error.


**Screenshot*

<img width="475" alt="issue-24217-add-number-of-pages-in-the-contentlet-html" src="https://user-images.githubusercontent.com/72418962/224434450-eed932b3-c35a-44a6-99ea-4cdf93720aa5.png">


**Video**


https://user-images.githubusercontent.com/72418962/224433638-2673ce75-3459-4426-802d-6047702a5e48.mov

**Comment by jcastro-dotcms** [comment]
@bryanboza I double-checked the Postman Test `dotCMS/src/curl-test/PagesResourceTests.json` , and there is already a valid test that is checking for the new HTML attribute present in edit mode only. We're good to go!
