### ISSUE TITLE
Favorite Page: Limited users can try to edit favorite pages they didn't create

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24220]
### Parent Issue

#22343

### Problem Statement

When a favorite page is assigned to a limited user, the star isn't highlighted which is ok, but the limited user can open the Favorite Page to try to edit it even when he didn't create it.

### Steps to Reproduce

1. Using admin user, create a favorite page and assign it to a limited user
2. Log in using the limited user and try to open the favorite page to edit it. The modal breaks.

https://user-images.githubusercontent.com/8741395/221644569-1916f84b-0858-482b-92cc-2af245df071b.mov

### Acceptance Criteria

**We need to discuss the best fix** 

### dotCMS Version

23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by alfredo-dotcms** [comment]
this needs a new EP, @jdotcms will be working on it

**Comment by nollymar** [comment]
PR: #24369

**Comment by josemejias11** [comment]
**No need to Test**

Since the creation of this ticket the assignation of bookmarks has been put on hold.

**Comment by bryanboza** [comment]
Since this functionality is discarded we can close this card
