### ISSUE TITLE
[SASS] : Minify CSS output by default

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#24227]
### Parent Issue

Requested by Enterprise Support

### Task

We need to update our current Dart SASS Compiler configuration to return minified CSS files by default. In order to accomplish that, the following property in the `dotmarketing-config.properties` file must be set like this:
```
dartsass.compiler.expanded.css=false
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

After an SCSS file is compiled by Dart SASS, it removes as many extra characters as possible, and writes the entire stylesheet on a single line.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Slack convo: https://dotcms.slack.com/archives/C028Z3R2D/p1677520685381909

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_46f4640b_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
![Screenshot 2023-04-11 at 3 17 52 PM](https://user-images.githubusercontent.com/129882031/231290380-c83a41fa-23d4-45aa-bf30-592ae60d248a.png)
