### ISSUE TITLE
Favorite Page: Snapshots should be displayed when the language is changed

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24221]
### Parent Issue

#22343

### Problem Statement

If the language is changed in Edit Mode, existing favorite pages are loaded with blank snapshots.

### Steps to Reproduce

1. Using full starter create some favorite pages in English
2. Open an existing page in Edit Mode and change the language to Spanish
3. Go back to the Favorite Pages view http://localhost:8080/dotAdmin/#/pages and see how the existing favorite pages are loaded. Snapshot images are broken.

https://user-images.githubusercontent.com/8741395/221646026-9dc52209-bc76-4c6f-8aba-c1f9118a7520.mov

### Acceptance Criteria

Snapshots in favorite pages view should be displayed correctly no matter the language selected in Edit Mode.

### dotCMS Version

23.03

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by alfredo-dotcms** [comment]
@nollymar after debuging no idea why changing the LANG in Edit mode breaks the path of the resource, right now I'm using the attr `screenshot`, but if I change it to `screenshotVersion` it works!
![image](https://user-images.githubusercontent.com/37185433/221710640-c3acded2-7a60-462d-a369-68472c624aea.png)

but no idea if that's ok

**Comment by nollymar** [comment]
add this param to the path: `?language_id=`

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24234/files

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_7d8de130_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0.1
