### ISSUE TITLE
Unify SCSS Colors Variables for Angular and Dojo

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24239]
### Task

We need to unify the SCSS colors variables, so we can easily change colors in the dojo widgets and angular components in one place.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Acceptance Criteria
- [ ] One SCSS variable file with colors should be used in Angular components and Dojo Widgets
- [ ] Identify and replace CSS where there are not colors
```

**Comment by zantili** [comment]
bro yall compain a lott
