### ISSUE TITLE
When Experiment is running Variant modifications should be limited.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24236]
When the experiment is running: 

- Variants only can be viewed, change the `edit` button for `view`
- Variants Name can't be edited, remove the ability to be edited. 

![image.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/1e280e82-2479-4a1d-bfdf-bd9c48b321d9)

**Comment by freddyucv** [comment]
We still can edit the variant layout doing this

1. Create a Page
2. Create a Experiment.
3. Set a Variant and a Goal.
4.  Start the Experiment.
5. Click on the "View" Variant Button.
6. Click on the Layout Button.
7. Change the Layout.

But we are going to create a new issue for this

**Comment by bryanboza** [comment]
We have problems here: 

I think what we are doing in the PR is not the best solution for this case, as in al the other features in the system we should restrict that functionality at API leven not just in FE.

We need to validate this in the API and be able to catch the response and then restrict the functionality in the FE site, also we need to add postman test to that endpoint to validate all the restrictions that we are listing in multiple cards.

**Comment by dsilvam** [comment]
@bryanboza we will work on this on this issue https://github.com/dotCMS/core/issues/24656

**Comment by bryanboza** [comment]
Closed, I don't test this b/c we have no fix here. Just moved to a new card
