### ISSUE TITLE
Notification when a variant is created is wrong.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24237]
When a variant is created, the notification displays the experiment name instead the variant name. 

![image.png](https://images.zenhubusercontent.com/59aeea41b0222d5de4768181/3e09073c-aab3-40a9-84d5-4d19651a509b)

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/24324

**Comment by freddyucv** [comment]
**Passed Internal QA:** Now it is showing the Variant Name

**Comment by bryanboza** [comment]
Fixed, now it looks better 
![Image](https://user-images.githubusercontent.com/2641437/229600705-58ce750d-5634-4e23-b0da-d2281f2e8e17.png)


Tested on relese-23.05 // Docker // FF
