### ISSUE TITLE
Nested dotcache causes issues

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24247]
### Parent Issue

https://github.com/dotCMS/core/issues/24075

### Problem Statement

Nested dotcache blocks cause some pages don't load successfully since it's caching the wrong context.

### Steps to Reproduce

Ask support for customer data.

### Acceptance Criteria

Pages should render successfully even with nested dotcache blocks

### dotCMS Version

23.01

### Proposed Objective

Customer Support

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer Ticket: https://dotcms.zendesk.com/agent/tickets/110078

**Comment by erickgonzalez** [comment]
The code that broke this was included in 23.01.

**Comment by erickgonzalez** [comment]
The customer tested the fix and confirmed that is working as it should.

**Comment by josemejias11** [comment]
**Approved QA** 

Costumer confirmed fix is working as expected.
