### ISSUE TITLE
[Integration Tests] : The `build.gradle` file is pointing to an outdated empty starter

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#24269]
### Problem Statement

In the latest master -- as of March 3rd, 2023 -- the Empty Starter being used by the CICD server for running the Integration Tests is the following:

https://github.com/dotCMS/core/blob/405bdbfc5a6b49c56f8ca0b5b35e553a40c100a8/dotCMS/build.gradle#L281-L284

As you can see, the valid Empty Starter is `empty_20230112`, whereas the one used by the CICD is way behind: `empty_20220718`. We need to update this and fix the tests that are failing because of any potential data changes between starters.

### Steps to Reproduce

1. Create a branch with the `testsStarter` attribute pointing to the correct Empty Starter: `empty_20230112`
2. Commit your changes and create a PR so that the CICD will kick off the Integration Tests workflow.
3. Go through the failed tests and check whether they're failing because of data problems or not.

### Acceptance Criteria

Developers need to remember updating both `starter` and `testsStarter` properties when a new Empty Starter is generated.

### dotCMS Version

Latest `master` and any previous version in which the Empty Starter is not `empty_20220718`

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

There's nothing to test from a dotCMS back-end standpoint. Only the Integration Tests results must be checked.

**Comment by fmontes** [comment]
@jcastro-dotcms let's speak with @spbolton about this.
