### ISSUE TITLE
Block editor field required not validating

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24263]
### Parent Issue

#21988 

### Problem Statement

If you create a content type with a block editor field required, and then create a piece of content leaving the block editor in blank, it still save the content.

### Steps to Reproduce

1. Create a content type with a required block editor
2. Create a content of that type and leave the block editor field empy
3. Save... and see the error.

### Acceptance Criteria

- [ ] Field that is required and empty should not allow the user to save the content
- [ ] A required field dialog (like in the other field) should show

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by manuelrojas** [comment]
### Internal QA Results:

@zulqarnainvd  It looks like if a move the cursor to other point in the Editor even when it is empty, it doesn't validate as required. 

https://www.loom.com/share/11b7a6fd5494496d85e40d4acd974117

cc @fmontes

**Comment by bryanboza** [comment]
We need some work here, now we are validating that field include something, but after you save the content, you try to edit the field and save it empty we are allowing to do that and leave the field without content

**Comment by fmontes** [comment]
horizontal line
block quote
code block
paragraph

Are blocks, and if have any it means it have content.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.03_fb6e0850_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

1. Unable to save content in a Block Editor when the block editor is a required field. 

2. When you save the block editor with content as a non required field and then you edit the content type to be required, the previously saved  content gets deleted.


https://user-images.githubusercontent.com/110418590/226470937-6b0d321e-eabb-4d27-b529-bcb1f5f6c9aa.mov

**Comment by fmontes** [comment]
Fixed the validation with the field named "Editor"

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_c8ba2dc2_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
