### ISSUE TITLE
File Browse Not Working as Expected

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24272]
### Parent Issue

https://github.com/dotCMS/core/issues/22729

### Problem Statement

The File Browse Dialog is not working as expected, in some scenarios doesn't show any content, and in others shows content that it should not.

### Steps to Reproduce

There are 3 scenarios here:

1- Try to create a Link, when you click over the Browse button and navigate over the destinations folder, nothing is shown.
2- Try to create a new Vanity URL, click over the Browse button and navigate over the destinations folder, it's displaying normal content when it should not.
3- From a WYSIWYG, is not displaying pages (it used to work).

### Acceptance Criteria

How it worked in previous versions:

- Scenario 1, should display pages, file assets, and dotassets.

- Scenario 2, should display pages and file assets.

-Scenario 3, should display pages and file assets.

### dotCMS Version

21.06.13 LTS, 23.01 LTS, 23.02.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer ticket https://dotcms.zendesk.com/agent/tickets/110305

**Comment by erickgonzalez** [comment]
Another customer hitting this: https://dotcms.zendesk.com/agent/tickets/110389

**Comment by erickgonzalez** [comment]
Another Customer https://dotcms.zendesk.com/agent/tickets/110414

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.03_5108019d_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
