### ISSUE TITLE
Creating a content in a third language in a row throws an error

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24286]
### Problem Statement

If you are creating content if multiple languages without leaving the edit content screen, when you reach the third language it throws an error:
```
java.lang.IllegalArgumentException: The Content Type is null when attempting to add new content with the inode: 
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction.handleContentTypeNull(EditContentletAction.java:1147) ~[dotcms_23.02_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction._newContent(EditContentletAction.java:1079
```

### Steps to Reproduce

1- Create 3 languages (English, Spanish, and Italian).
2- Create a content in the 3 languages without leaving the edit content screen.
3- When reaching the 3rd language see the error

https://user-images.githubusercontent.com/5278970/223226760-9916b260-4871-413c-bbf5-306797f080cd.mov

### Acceptance Criteria

Should be able to create multilingual content successfully.

### dotCMS Version

21.06 LTS and demo (23.02)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer ticket https://dotcms.zendesk.com/agent/tickets/110293

**Comment by muhammadfaizandotcms** [comment]
Another customer just reported this issue: https://dotcms.zendesk.com/agent/tickets/110722

**Comment by erickgonzalez** [comment]
Another customer: https://dotcms.zendesk.com/agent/tickets/110856

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_94a8586_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
