### ISSUE TITLE
[UI] Container and Route for Reports of Experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24288]
### Parent Issue

https://github.com/dotCMS/core/issues/23625

### User Story

As a user, I want to be able to go to reports of experiments, 

### Acceptance Criteria

- Router working
- Container with the Name of the experiment
- Content with an empty body

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1049" alt="Screenshot 2023-03-06 at 4 08 16 PM" src="https://user-images.githubusercontent.com/1909643/223231939-a237a91b-7ee0-403f-9d3d-cb9355dc0897.png">

**Comment by oidacra** [comment]
Note for QA:
- Router working: Icon to go to reports:
<img width="1431" alt="Screenshot 2023-03-23 at 3 46 18 PM" src="https://user-images.githubusercontent.com/1909643/227334289-db069ee7-b4ff-4e2c-9f80-57b94cee0910.png">

- Container with the Name of the experiment (Header):
<img width="1459" alt="Screenshot 2023-03-23 at 3 49 30 PM" src="https://user-images.githubusercontent.com/1909643/227334824-5b0cdf7a-acd1-433f-b650-35f32bc80d2c.png">


- Content with an empty body
<img width="1531" alt="Screenshot 2023-03-23 at 3 48 18 PM" src="https://user-images.githubusercontent.com/1909643/227334548-191b07aa-cd5e-41c3-8909-231fa119c65a.png">

**Comment by dsilvam** [comment]
Passed Internal QA: All described in the QA note is present for running Experiments.

**Comment by bryanboza** [comment]
Fixed, tested on master// docker // FF
