### ISSUE TITLE
Refreshing the page blocks the Persona Selector

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24283]
### Problem Statement

If you are editing a page as a custom persona, and you hit refresh the persona selector stops working.

### Steps to Reproduce

1- Click over any page to open Edit Mode.
2- Select another Persona e.g `Eco Enthusiast`
3- Refresh the page
4- After it, the Persona Selector stops working.

### Acceptance Criteria

Persona Selector should continue working regardless the refresh of a page.

### dotCMS Version

23.01.1 and demo (23.02)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer Ticket: https://dotcms.zendesk.com/agent/tickets/110315

**Comment by fmontes** [comment]
Not happening in demo anymore.
