### ISSUE TITLE
CLI: Pull languages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24281]
### Parent Issue

#24279

### Task

Implement `language pull` command. The command should support these _optional_ parameters: 

- _language_id_: If a `language_id` is provided, the pull operation should get the language details using JSON format by default (or YML if specified by the _fmt_ param). In case a `language_id` is not specified, a list with all the languages in the system should be retrieved.
- _fmt_ or _format_: Used to define possible output values: JSON, YAML, YML. If not set, default to JSON.
- _i_ or _interactive_:  Used to break down a long process into stages
- _to_ or _saveTo_: Filename where the output will be saved to. Only used when _language_id_ is set. The file format is given by the _fmt_ ()or _format_ param.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

I should be able to run the `language pull` command using any of these params: _language_id_, _fmt_ or _format_, _i_ or _interactive_,  _to_ or _saveTo_

**Comment by jgambarios** [comment]
1. When pulling a language with an ID that does not exist, we get a generic error message, but we need a more detailed response message, maybe with a 404 and a Not found.

```
lang pull 4813464
[ERROR] ❗  Error occurred while pulling Language Info: [4813464].
```

2. Using the default stater with the default languages where `es-ES` with ID `2` exists, we try to pull using just using the language code:
```
lang pull es

{
  "id" : -1,
  "languageCode" : "LANG__404",
  "countryCode" : "LANG__404",
  "language" : "LANG__404",
  "country" : "LANG__404"
}
Output has been written to file [./LANG__404.json].
```

**Comment by nollymar** [comment]
The code was updated to display this message instead: 



![Image](https://github.com/dotCMS/core/assets/8741395/2af2ae87-8a13-43ee-9172-c7be4de34fbe)

**Comment by nollymar** [comment]
**Note to QA:** Please consider this punchlist when testing 

1. make sure iso codes are all case insensitive
2. show the iso in the listing
3. make sure we support languages without countries
4. id should be optional

**Comment by fabrizzio-dotCMS** [comment]
When running a pull on a none existing lang we should get a 404 like this 

javax.ws.rs.NotFoundException:  Status: (404) With error: {
  "message" : " `fr-FRA` is an invalid language tag "
}

Currently, we're getting a nice formatted message but it looks like sometimes we display the Http code and some other times we don't. We need to  standardize

**Comment by fabrizzio-dotCMS** [comment]
This effort has used the status codes returned by the existing endpoint. and all other error messages will be standardized in a separate ticket. Therefore this is passing.
