### ISSUE TITLE
Block Editor: Error uploading images in a different default language.

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#24285]
### Problem Statement

An error message shows up when trying to insert an image with different default site language into WYSIWYG editor.

### Steps to Reproduce

1.- Upload an image in Spanish language (assuming that English is the default site language).
2.- Open/Create a new Blog entry.
3.- Insert the image uploaded (Spanish language) into WYSIWYG editor.

![Screenshot 2023-03-06 at 11 57 27 AM](https://user-images.githubusercontent.com/12899960/223217043-519c21ce-df1d-47b2-9fc9-ede479f78370.png)
![Screenshot 2023-03-06 at 11 57 52 AM](https://user-images.githubusercontent.com/12899960/223217132-f02ed3b5-4960-4e73-a6ba-c5912ca2122a.png)
![Screenshot 2023-03-06 at 11 58 22 AM](https://user-images.githubusercontent.com/12899960/223217221-510270ca-da7b-457c-915d-8c4e6712a8e5.png)
![Screenshot 2023-03-06 at 11 58 36 AM](https://user-images.githubusercontent.com/12899960/223217267-89f6d34d-4057-4a3f-9fc5-d3104785a53b.png)

### Acceptance Criteria

Able to insert images with different languages.
![Screenshot 2023-03-06 at 11 59 27 AM](https://user-images.githubusercontent.com/12899960/223217468-edd40cca-6f69-449d-a60c-5b810b4117d6.png)

### dotCMS Version

Demo 23.02

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110285

**Comment by manuelrojas** [comment]
@fmontes 

Testing on [Demo](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries ) when adding a image with Language as Spanish the reference returned by the API throws 404.

Example: https://demo.dotcms.com/dA/c4e226910a373f48af59532dedcb1e25/fileAsset/jakub-neskora-A9tqu5iCFCQ-unsplash.jpg

we are using the following API https://demo.dotcms.com/api/content/_search which returns 

```
fileAsset: "/dA/c4e226910a373f48af59532dedcb1e25/fileAsset/jakub-neskora-A9tqu5iCFCQ-unsplash.jpg"
fileAssetContentAsset: "c4e226910a373f48af59532dedcb1e25/fileAsset"
fileAssetType: "d5ea385d-32ee-4f35-8172-d37f58d9cd7a"
fileAssetVersion: "/dA/0eb3ca51-b19a-4d2b-a1a1-9a0f19c76e9a/fileAsset/jakub-neskora-A9tqu5iCFCQ-unsplash.jpg"
fileName: "jakub-neskora-A9tqu5iCFCQ-unsplash.jpg"
```

Testing locally `fileAssetVersion` works **correctly** for both Spanish and English images it looks like the `fileAsset` keeps related to the original contentlet language. 

Looking to image gallery it is using `fileAssetVersion`

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/3438705/234986049-d7f2e4f7-9eb5-45c4-a641-674b2448d197.png">

**Comment by zJaaal** [comment]
### Passed Internal QA

Docker Image: `[dotcms/dotcms:master_3b0b1cfc]`

https://user-images.githubusercontent.com/63567962/235757953-379af6d6-24e5-494a-8c3e-4aef94276b9c.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_707fea3d_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
