### ISSUE TITLE
Ensure that sessions can be serialized and replicated across servers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24291]
### Parent Issue

#24294 

### User Story

We have an issue where we are trying to store things in dotCMS user sessions that are not serializable.  This is preventing session objects from being shared across dotCMS clusters as the objects stored in session must be serializable to be sent over the wire to other dotCMS nodes.

I have found two places where this is happening - DWR and in our antique portlet processor.  I am pretty sure both can be changed/ripped out without impacting dotCMS functionality.

### Acceptance Criteria

Make sure session objects can be properly serialized - you can test this by setting up redis and redisson to try to persist/cluster tomcat session objects.

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by rjvelazco** [comment]
### Passed Internal QA

Docker Image: [`dotcms/dotcms:master_22fddf4b`]

I tested this using this [Docker Compose files](https://github.com/dotCMS/core/tree/master/docker/docker-compose-examples/with-redis) as @jcastro-dotcms told me.

**Comment by bryanboza** [comment]
Fixed, for now we just identify two cases where we are showing the serialized error on the log and after talking with @jcastro-dotcms those are already caught, then we can pass this card for now and we will be pending to this error in any new case to report.
