### ISSUE TITLE
Allow user to edit page or master contentlet in inline editing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24297]
### Parent Issue

#23225

### User Story

As a user, I want to be able to inline edit a piece of content in a page but be able to choose if it will edit for all the pages that use that content or only the one I am working on.

### Mock
[Figma Prototype](https://www.figma.com/proto/trbwjLuf5F6KaU1rFucNeg/Portlets-%2F-Edit-Page?page-id=0%3A1&node-id=569%3A4774&viewport=4311%2C-717%2C0.42&scaling=min-zoom&starting-point-node-id=569%3A4774)

![image](https://user-images.githubusercontent.com/751424/223448894-9b5d7a3c-0bea-4cac-b78f-6d9a23288df0.png)

### Acceptance Criteria

- [ ] Show the dialog only when the content is used in multiples pages
- [ ] Allow the user to edit the contentlet for this page or all pages.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

We are doing the exact same thing as here: https://github.com/dotCMS/core/issues/23225

**Comment by wezell** [comment]
I wish this dialog was one click rather than two.

**Comment by fmontes** [comment]
As per @damen-dotcms let's make "All Pages" the default selection when opens.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 //  Docker // FF
