### ISSUE TITLE
SALES: multi-site switching in Edit Mode (Anywhere)

### ISSUE THREAD

**Issue by stefan-dotcms** [dotCMS/core#24300]
### Parent Issue

If I have multiple sites on my instance, and I want to switch from site A to B while in Edit Mode (Anywhere), I want to stay in Edit Mode and NOT switch to the site browser outside Edit Mode (Anywhere) for a much better user experience.

https://user-images.githubusercontent.com/124192451/223496694-76c1d3f8-33d7-4e90-b5ab-1beef3bce29b.mp4

### User Story

As a content editor, I want to stay in Edit Mode when I switch from site A to site B.

### Acceptance Criteria

In a multi-site instance of dotCMS, switching from site A to site B while in Edit Mode (Anywhere), the content editor stays in Edit Mode (Anywhere).

The switch works for both traditional as well as headless and hybrid-headless dotCMS.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
Marked as closed as this issue is too stale.
