### ISSUE TITLE
Multi Metadata Provider/Chainable Metadata Provider

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24307]
### Parent Issue

- [x] Store Assets in S3 

### User Story

Short Story Long: 
We built a cool FileStorage tool to store our assets File Metadata.  Initially, to access File Metadata, we tried using the `DataBaseStoragePersistenceAPIImpl` as DEFAULT  but this had a downside when running in at load in a cluster - each node in the cluster needed to do db hits to generate the metadata for every asset `SQL calls = (number of nodes * assets requested)`.  And when a node/container cycled, the new nodes needed to re-do all those sql queries.   This had the effect of swamping the DB and nodes were unable to process requests while they were trying to load metadata for the assets.

So we rolled back to the `FileSystemStoragePersistenceAPIImpl`, which mirrored the older behavior and stored the File Metadata on the NFS share.  This has the benefit that once one node has generated the metadata, the other nodes can pick it up with no load on the DB and that all metadata survives restarts.  But it has the downside that we are still reliant on the NFS share for metadata and assets and that adding the metadata file/folder takes up a number of fs inodes from the NFS share.

Where I would like to be is to have a combination of both - a chain where the Storage providers are checked in order.  In our case the `FileSystemStoragePersistenceAPIImpl` is checked first and if the metadata is not found, then the `DataBaseStoragePersistenceAPIImpl` is checked.  If the `DataBaseStoragePersistenceAPIImpl` finds the metadata then it returns it and it gets written to the NFS mount (or in the local filesystem, configurable) for future access and then returned as json to dotCMS.

The same would happen when we persist the metadata, we write it to the FileSystem first and then to the DB.

The point of a configurable chain is that 
1. By backing up the db we have a full snapshot of all asset metadata that will also perform well in a cluster, which is what we want.  We can then rely on the FS as a cache.
2. It would allow is to also write a `RedisStoragePersistenceAPIImpl` and configure it into the chain as well, after the NFS FS and before the DB or even use it to replace the NFS FS as the cluster persistence layer.
3. With these changes and confidence that we all our asset metadata is in the DB, we can start to store file assets by their sha256 hash, effectively de-duping them.
4. Once we are storing the assets by their sha256, we can start to store them in an s3 bucket 

### Acceptance Criteria

- Store file asset metadata in both the FS and the DB.
- Wipe out the fs metadata and be able to start a dotCMS and pull the metadata from the DB which would repopulate the FS metadata. 

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
The redis may be interesting on the chain, however we have to discussion if we want to have second level Redis cache (which is the basic) and Storage on Redis for full cache

**Comment by fmontes** [comment]
Work in progress... S3 implementation

**Comment by jcastro-dotcms** [comment]
I'm touching base with @josemejias11 ti set up the appropriate configuration variables to test all Metadata Providers.

**Comment by bryanboza** [comment]
Fixed, tested the 4 providers and it is working as expected. 

## Using File System 
![Image](https://github.com/dotCMS/core/assets/2641437/c069f055-6dd7-481f-be1c-49ea727ec1b3)

## Using MEMORY (redis)
![Image](https://github.com/dotCMS/core/assets/2641437/f32aa9d4-a735-4385-87ea-11e0c7fec305)

## Using Amazon S3 bucket 
![Image](https://github.com/dotCMS/core/assets/2641437/dd541523-91e2-4e9d-bd1b-ddd54eb8829c)
![Image](https://github.com/dotCMS/core/assets/2641437/22a8c1a9-13f1-4269-bcf3-e864bb3cfdfb)
![Image](https://github.com/dotCMS/core/assets/2641437/dfc2b986-6fbd-48f9-a753-234e9913fb25)

## Using DataBase as provider 
![Image](https://github.com/dotCMS/core/assets/2641437/2a24957a-1926-470b-b740-2ae84f8fb62f)
