### ISSUE TITLE
Can't search for contentlets in edit page palette

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24308]
### Problem Statement

As a user I want to be able to search for contentlets in the content palette while editing a page.

### Steps to Reproduce

1. Edit a page
2. On the right side content palette, open a content type
3. Select a content type
4. Now try to search a contentlet in the input
5. See the error

### Acceptance Criteria

- [] User should be able to search for contentlets while typing.

### dotCMS Version

23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/751424/223570334-0464aa4f-27b4-4ab1-a278-f9d50e93d2e0.png">

**Comment by wezell** [comment]
Please let me know how/what commit broke this?

**Comment by zulqarnainvd** [comment]
@wezell this [commit](https://github.com/dotCMS/core/commit/9520a295c810856f339da140c125257ba15f388c?diff=split#diff-81ccac1ec7b670929a255d1e6ee7e3a43c1e3fbe784ed28ba32bfec78b578516) was broke the search of contentlet.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_3d55dd2c_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
