### ISSUE TITLE
Delete variant should have confirmation dialog

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24306]
We should a confirmation dialog before the used is able to delete a variant in draft mode. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/31667212/223771367-17608312-176e-41bd-b5e4-1f3833b3735a.png">

**Comment by dsilvam** [comment]
Passed Internal QA: Confirmation dialog in place and working.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
