### ISSUE TITLE
Set FavIcons to Match Sitewide

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24311]
### Problem Statement

The FavIcons don't match between pages.

### Steps to Reproduce

Open some random pages of dotCMS... note how the FavIcons don't match.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/114953617/223583190-ebd8a96b-deb6-4867-8613-9d9c89621440.png">

### Acceptance Criteria

Every page in dotCMS should have the same FavIcon.

### dotCMS Version

Demo

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by damen-dotcms** [comment]
We probably need a new FavIcon to fix this. Both of the examples are really pixelated. That won't dramatically improve, but we don't need the gray circle around the dot... I think both are dated logos.

**Comment by fmontes** [comment]
Not only that, the dot is also in the logout.

@Melissa-dotCMS will create an incredible one.

**Comment by fmontes** [comment]
Let me check with @fishsmith
