### ISSUE TITLE
Investigate expiration time for JWT tokens

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#24313]
### User Story

The time limit for a JWT (JSON Web Token) is determined by the value of the "exp" claim (expiration time) in the token's payload. This value represents the number of seconds since the Unix epoch (January 1, 1970, at 00:00:00 UTC) after which the token will expire. 

- It's important to choose an appropriate expiration time to balance security and usability, as a longer expiration time increases the risk of a compromised token being used maliciously, while a shorter expiration time can result in users having to log in more frequently.
- Expiration time must be set for inactivity i.e. if the user keeps activity expiration time must extend.

Look into JWT functions to see if if also support a "refresh token" mechanism, which allows a new access token to be generated after the previous one has expired, without requiring the user to log in again. --> based on session or ip or some user signature.
The refresh token typically has a longer expiration time than the access token, and can be used to obtain a new access token when needed.

### Acceptance Criteria

1. Once the expiration time has passed, the JWT will no longer be considered valid and any attempts to use it will result in an error.
2. The expiration time is typically set when the token is issued, and can be customized based on the requirements of the application or service that is using the JWT. 
3. Recommendation to set the expiration time to a reasonably short duration, e.g., 15-30 minutes, to reduce the risk of a compromised token being used maliciously. This also encourages users to stay active and engaged with the service application.
4. It is a good practice to implement a refresh token mechanism to enable users to obtain a new access token without having to re-authenticate every time the token expires. The refresh token can have a longer expiration time than the access token, such as several days or even weeks, but it should be securely stored and transmitted.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by mbiuki** [comment]
See section 3.2.4.2 in https://drive.google.com/file/d/1qPeVkljCwoOeWlO2doFWA4H5DubqJ_EI/view?usp=sharing

**Comment by sfreudenthaler** [comment]
Treat this as a Spike/Investigation

**Comment by wezell** [comment]
So we use JWT in 2 places:
### LOGIN
1. Session Cookie - When the user logs in, we set a JWT session session cookie that includes an `exp` date 30m in the future
2. Long-term Cookie - If the user clicks "Remember Me" when they login, we set a long lived (2 week)  cookie that includes an `exp` date 30m in the future   

### API KEYS
3. JWT `Authorization: Bearer` token.  These are created from the User screen and are intended to be used when calling APIs.  These include `exp` dates that are set when a user creates the API key

**Comment by mbiuki** [comment]
This investigation is sufficient at this point in time. Closing ticket.

**Comment by mbiuki** [comment]
For more info on JWT tokens and how to configure them see:
https://www.dotcms.com/docs/latest/authentication-using-jwt
