### ISSUE TITLE
LanguageWebAPI is mapped 5 times in the toolbox.xml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#2431]
We need to map it to $text and update all our .vtls to use only $text and not

$languagewebapi
$langbackendwebapi
$globalvars
$glossary

**Comment by john-thomas-dotcms** [comment]
I'm not sure if anyone has looked at the .vtls in the starter, but note that we removed everything except the $text tool from the docs a little while ago, so hopefully at least it will get customers using just $text moving forward.
