### ISSUE TITLE
[UI] Modal not removed after created Experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24327]
### Parent Issue

https://github.com/dotCMS/core/issues/23095

### Problem Statement

After update PrimeNg when we destroy the sidebar not remove the background modal (Blur)

### Steps to Reproduce

- Go to lists experiment
- Press Add new Experiment
- Fill the name and description
- Save

### Acceptance Criteria

- After creat the experiment, the backend blur needs to be removed.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1647" alt="Screenshot 2023-03-09 at 11 00 16 AM" src="https://user-images.githubusercontent.com/1909643/224081201-a8f98d03-df34-42f9-a3ea-1d5ba626aa32.png">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24367

**Comment by dsilvam** [comment]
Passed Internal QA: No more blur after creating an Experiment.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
