### ISSUE TITLE
[UI] Open the traffic split sidebar from the Variants traffic indicator. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24339]
### Task

As a user I want to be able to edit the traffic split from the variant traffic indicator. 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/31667212/224175557-a79a4db0-a96f-46a1-86f5-d48f3f1ea79b.png">

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The sidebar should open when click the traffic indication in the variant description. 
Refactor Variants step to follow the same behavior as other steps.

**Comment by dsilvam** [comment]
Passed Internal QA: Removing the Traffic Split from the Traffic section will be complete on a separate card

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF
