### ISSUE TITLE
[UI] Create a detail Angular component to use in Reports and Goals

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24332]
### Problem Statement
As a user, I want to be able to send a template reference or an array of data to a detailed Angular component so that it can similarly display the data as the Figma file.

### Steps to Reproduce
N/A

### Acceptance Criteria

- The detail Angular component should be able to receive a template reference or an array of data as input.
- The data should be displayed in a similar way as the Figma file.
- The component should be thoroughly tested to ensure that it functions correctly.

### dotCMS Version
N/A

### Proposed Objective

The objective is to create a reusable Angular component that can be used to display detailed information in a visually appealing and consistent manner.

### Proposed Priority
Medium

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- Figma design file [LINK](https://www.figma.com/file/fAoCk4swhiwplkU5GP21YD/Portlet-%2F-Experiments?node-id=1464-12048&t=TqrVA2dnHLCpJgCE-4)

### Assumptions & Initiation Needs

- Angular framework is being used
- Developers have access to the Figma design file

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by bryanboza** [comment]
Fixed, now we have the angular component displaying the mock data. Tested on release-23.06 // Docker // FF
