### ISSUE TITLE
[UI] Experiments Reports

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24330]
### Parent Issue

https://github.com/dotCMS/core/issues/22455

### User Story

As a user, I want to be able to see a report of my Running/Ending Experiment

### Acceptance Criteria

No response

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="982" alt="Screenshot 2023-03-06 at 4 02 05 PM" src="https://user-images.githubusercontent.com/1909643/223229942-79024ebf-2ec4-4f3b-9baf-089369254b4a.png">

### Sub-Tasks & Estimates

- [x] #24288
- [x] #24331
- [x] #24332
- [x] #24530
- [x] #24626

**Comment by john-thomas-dotcms** [comment]
Completed
