### ISSUE TITLE
Allow to create an Experiment via REST API without a description

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24346]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As a User, I want to be able to create an Experiment via REST API without requiring a description. 

### Acceptance Criteria

Being able to create an Experiment without needed to provide a description. 
Postman Test

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24663

**Comment by bryanboza** [comment]
Fixed, tested on release 23.06 // Docker // FF
