### ISSUE TITLE
We are losing the image field value when you edit a piece of content from a variant 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24350]
### Problem Statement

When you are editing a variant and you try to edit a piece of content that include a image field, we are losing that value and we are getting an error when you try to save 

https://user-images.githubusercontent.com/2641437/224428095-49605f37-2ab0-41bf-8fd5-a35550d10057.mov

### Steps to Reproduce

- Login as admin
- Create a new variant to index page 
- Edit the variant and try to edit the content 
- Change the text color and try to save the changes
- Make sure you are able to save without problems 

### Acceptance Criteria

We need be able to save changes without problems 
After save the content we need to make sure we are keeping the image in the field 
Need to test the same case for binary and file fields

### dotCMS Version

Tested on release-23.03 // Postgres // FF 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, tested on release-23.03 // Docker // FF

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25235

**Comment by dsilvam** [comment]
Passed Internal QA: Able to edit the content while on a variant and save/publish without losing the image.

**Comment by bryanboza** [comment]
We needs some work here. 

When you have a page that contains a piece of content with an image, when you create the new variant, we are excluding this piece of content from the page 


https://github.com/dotCMS/core/assets/2641437/f20f1736-0b95-4157-ba47-388bcd5c231d


Tested on master // Docker // FF

**Comment by freddyucv** [comment]
Unable to reproduce
