### ISSUE TITLE
File Browser Only Showing Content in the Backend Language

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24358]
### Parent Issue

https://github.com/dotCMS/core/issues/22729

### Problem Statement

If you upload a file to dotcms to any language other than the one used in the BE, that file won't appear in the File Browser.

### Steps to Reproduce

1- Login into dotCMS in English.
2- Go to any folder in the Site Browser.
3- Select Spanish as the content language.
4- Upload any file.
5- Create a new content type with an Image Field.
6- Create new content and try to select the uploaded file 
7- The File Browser shows **No Files Found**
8- Log out dotcms
9- Login into dotCMS using Spanish as the Language.
10- Create new content and try to select the uploaded file

### Acceptance Criteria

File Browser Dialog should be filtering by using the language selected in the content selector not the one in the BE.

### dotCMS Version

21.06 LTS, 22.03 LTS, 23.01 LTS, and demo (23.02)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110451

### Quality Assurance Notes & Workarounds

Login to the BE using the Language in which the file exists.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_86e392fc_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

![Screenshot 2023-04-04 at 3 34 52 PM](https://user-images.githubusercontent.com/129882031/229928318-ce8cec58-9765-4bdc-ad1b-e6d458e25614.png)

**Comment by josemejias11** [comment]
Hi @erickgonzalez,

Can you please try and retest this using **23.05_86e392fc_SNAPSHOT** I can only approved cards that are already deployed to Docker.

Thanks!

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_86e392fc_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
