### ISSUE TITLE
Configuration of S3Client to target endpoint unable to sent css files

### ISSUE THREAD

**Issue by josemejias07** [dotCMS/core#24351]
### Problem Statement

When trying to sent a css files through PP to  a S3 server is unable to compile the css file 

### Steps to Reproduce

Create a new endpoint with the below configuration 

<img width="574" alt="206482592-cfffbb4d-32cb-482a-9144-edf2ab95e250" src="https://user-images.githubusercontent.com/110418590/224436834-239d6bba-41ed-4e06-8004-e912577f79a0.png">

Using

aws_access_key=9GIUDSGWFGUDCD2ZQ0QK
aws_secret_access_key=iirgvcH1iwy3BRDwc61FLAiwZjTeCkMtjZ6h0eJe
aws_bucket_name=dotcms-bucket-{hostname}-{languageIso}
aws_bucket_region=us-east-1
aws_endpoint=https://s3.ap-northeast-1.wasabisys.com

### Acceptance Criteria

CSS files should get through PP to a targeted endpoint

### dotCMS Version

23.03, 23.01.1 LTS

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/blob/83e766658b4144d8defd8126374b08ce7591e3cf/dotCMS/src/main/java/com/dotcms/mock/response/DotCMSMockResponse.java#L155

https://gist.github.com/josemejias07/14c8061549ff4d95da50b803f9f79bdd

**Comment by josemejias07** [comment]
Related to #22151

**Comment by freddyucv** [comment]
**Pass Internal QA** Now the css file was compiled and sent successfully

**Comment by erickgonzalez** [comment]
Customer hit this using AWS https://dotcms.zendesk.com/agent/tickets/110514

**Comment by josemejias07** [comment]
hey @freddyucv,

did you test this using docker? Im not you if it is in the last snapshot.

thanks!

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.03_1d848519_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

**Comment by erickgonzalez** [comment]
@josemejias07 I think that is due to the way our stater is built since we make a few recommendations here when using Static Publishing https://www.dotcms.com/docs/latest/static-publishing-best-practices
