### ISSUE TITLE
Implement "compare" for the block editor field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24365]
### Parent Issue

#21988 

### User Story

As a user, I want to be able to compare previews versions of a contentlet block editor field.

The ideas are that I can see in plain HTML what changes between the two versions so I can easily understand where I am.

### Acceptance Criteria

- [ ] Add block editor field as HTML to the compare screen

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
For internal QA: try with converted content from WYSWYG

**Comment by fmontes** [comment]
1. Top align all the cells
2. Make sure it work with converted from WYSIWYG fields

**Comment by fmontes** [comment]
Needs work, we need to constrain vertical videos



![Image](https://user-images.githubusercontent.com/751424/234901863-0f072a0e-c833-4bb2-8d61-5f2c981ab453.png)



Like we do inside the block editor here:



![Image](https://user-images.githubusercontent.com/751424/234901983-97146702-09c0-4ca8-9e5d-e853e8e8a292.png)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_9bc82721_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
