### ISSUE TITLE
Automatically Convert fat content to json content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24366]
### Task

There are a number of places where we rely on the database to search content - host searching, image browser.  When we moved to the `contentlet_as_json` field, these places stopped working unless all the old fat content in the system had been converted to use the json content, which does not happen automatically.

We need a startup task that is a bit different than our current startup tasks.  It should set up a background task that converts all content to `contentlet_as_json` in the database.  In order to minimize the impact the issue, it should start with all content of type `host` and once those are updated, move on to any content that does not have a value in the `contentlet_as_json` field.

The job should be as low impact as possible.  I would rather not use the checkin method if at all possible.  The job does not need to be super performant and should favor a slow, steady process that does not tax the servers rather than finishing as quickly as possible.  Additionally, we should not need to fire a reindex on the contents that we update as none of the underlying fields should have changed.

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Dupe: https://github.com/dotCMS/core/issues/24093
