### ISSUE TITLE
Block Editor: Crashing with AllowedBlocks

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#24370]
### Parent Issue

#21988 

### Problem Statement

After adding the Allowed Blocks in the content type, Block Editor throws an error and remove the content.

### Steps to Reproduce

Add the following Allowed Blocks and then go to the block editor to edit content.

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/3438705/225092294-551935fe-bc91-48c6-b034-41951783d5ea.png">

### Acceptance Criteria

It allows to add the Allowed Blocks without breaking the Block Editor Functionality.

### dotCMS Version

23.03

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_1d848519_SNAPSHOT** // Docker // macOS 13.0 // FF 111.0
