### ISSUE TITLE
Lightweight / Content Job Runner

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24385]
### Task

Customers want a way to reliably ingest 3rd party content for use within dotCMS.  

Many / most of our customers use the provided `$json` and `$import` tools to pull api responses at runtime from 3rd party systems and incorporate them into dotCMS pages and/or VTL API responses.  Just today, a customer was asking to pull the latest news from an investor news api and add the latest 3 articles to the main site navigation.  While this can be done, what this means is that every page hit in dotCMS is going to have to go out and do a remote call in order to render a page.  Our current answer is to wrap such a call and render the nav in a "block cache" for a period of time but this is not simple and also has the downside of possibly caching a null or empty response (or if the cache gets flushed etc).

It would be super nice if we had a screen that would allow you to specify a "Content Job".  This Content Job would consist of a unique key, a cron expression and a velocity script to be run.  The defined job would be run based on the cron expression and the job results would be stored in a content type called "contentJob" with the unique key and the text results of the script run. If the job failed for any reason, we would not store the results of the job and users could pull the results of the last run of the contentJob.  It could act as a cache for remove content and content synchronizations.

### How would this be used?
In the example above, the ideal state would be for the HTMLer/developer to be able to access the latest investor news using a Velocity viewtool.   We could provide a local viewtool and rest api that would allow you to access the results of the latest run of the content job for use on a page.  You could access the latest results of a job by calling `$dotjob.get("latest-news-articles")` or if you wanted json, maybe `$dotjob.json("latest-news-articles")`, which would return the results as a JsonObject.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Just a few of many references from our listserv:

https://groups.google.com/g/dotcms/c/wdr88u_bPdM/m/3quHX7g_UR4J
https://groups.google.com/g/dotcms/c/YUtfEJpYTCY/m/e5J8_2N88lkJ
https://groups.google.com/g/dotcms/c/70LbNkV8ypA/m/g1kG4dAGBwAJ

**Comment by prestonso** [comment]
Closing as this is now represented in Airfocus as an epic.
