### ISSUE TITLE
Error upgrading in Postgres 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24380]
### Parent Issue
This issue comes from support 

### Problem Statement

We are getting a data error when you try to upgrading from 22.03.4_lts  => 23.01.1 

### Steps to Reproduce

From a 22.03.4_LTS try to upgrade to the release branch 

### Acceptance Criteria

We need to be able to upgrade from LTS to the release branch without problems 

### dotCMS Version

22.03.4_lts

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by freddyucv** [comment]
**Note to QA**: this error just happened when the PK of the contentlet_version_info has a name different of contentlet_version_info_pkey, so to really test this case we need to start up dotcms in  22.03.4_lts and change the name of the PK.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/24376

**Comment by victoralfaro-dotcms** [comment]
`22.03.4` contentlet_version_info properties:
![Image](https://user-images.githubusercontent.com/64026161/225700192-1ca23c30-fe2e-48d0-a879-471b6353c1d5.png)

**Comment by erickgonzalez** [comment]
Only applies to 23.01 LTS

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 23.01 Branch // Local // Postgres 15 // macOS 13.0 // FF v111.0

Logs:
[catalina.out.zip](https://github.com/dotCMS/core/files/11142234/catalina.out.zip)


![Screenshot 2023-04-03 at 2 22 44 PM](https://user-images.githubusercontent.com/110418590/229619544-198d33ae-875b-43ee-8000-b15d32566049.png)
