### ISSUE TITLE
Block Editor adds trailing space to hyperlinks or marks

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#24406]
### Problem Statement

The Block Editor seems to add a lot of space throughout the page source, and one effect of this is that a trailing space appears inside anchor tag text, which ends up looking pretty sloppy on the front end.

(Edit: It does something similar after marks, too; [see comment](https://github.com/dotCMS/core/issues/24406#issuecomment-1480130200).)

### Example

Here's how some text appears in the Block Editor

![image](https://user-images.githubusercontent.com/102264829/225927705-414e05f1-9f5b-4903-92cc-54c00164797f.png)

And here's how it renders on the front end:

![225927885-8a59be68-8057-4fdb-8f56-603e6e05305c (1)](https://github.com/dotCMS/core/assets/102264829/d17b07b3-5d1b-4836-811f-3ee6f419f498)

Similarly, links followed by an intentional space will still have their underlines (visible in the above instance only on hover) stretch to include that trailing space, which looks a bit sloppy. 

And here's what the source code looks like:

![image](https://user-images.githubusercontent.com/102264829/225928105-6242fc93-b1ad-4beb-8d1e-0b334c7dca4e.png)

I think that huge nebula of whitespace has made its way into the `<a>` tag.

### Steps to Reproduce

1. Open a contentlet with a Block Editor field
2. Type some dummy text or find some existing text, and insert a link in the middle of some contiguous text (e.g., ending right before a punctuation mark, or a link that only occupies half of a word)
3. Publish
4. Find an extra space added before the punctuation etc.

### Acceptance Criteria

No extra spaces should be added.

### dotCMS Version

Tested in 23.03, 23.02 (Demo)

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Mostly just a restatement of the above, but [here's a Slack convo](https://dotcms.slack.com/archives/CQQMX585N/p1679061479715769).

### Assumptions & Initiation Needs

I suspect this issue can be substantially resolved through the use of `.trim()` in a handful of places. I haven't scouted out the code to get a sense of where it might go, though.

**Comment by jdcmsd** [comment]
It seems that it's not just links, but marks as well. E.g., here's how it renders punctuation after bolded text:

![image](https://user-images.githubusercontent.com/102264829/227013686-e178c226-5a2c-41b4-b2fb-0a84661ffa83.png)

**Comment by wezell** [comment]
@jdcmsd can you check the stored value json (pull content via api) to verify if this is in the storage or in the velocity code?

**Comment by jdcmsd** [comment]
Confirmed that the excess spaces are not in storage. Example:

```
{"type":"text","marks":[{"type":"bold"}],"text":" loads faster across locales"},{"type":"text","text":"."}]}
```

vs.

![image](https://user-images.githubusercontent.com/102264829/227233991-c0b9f005-dc8d-4138-a2d9-2a4a36441217.png)

**Comment by jdcmsd** [comment]
I think I've got a fix for this ready!

Comparisons below between text in the editor vs published

### Before (on Demo)

![Screenshot 2023-06-02 at 4 53 35 PM](https://github.com/dotCMS/core/assets/102264829/53ed68e0-3245-45c4-a0f4-3a3b37bdba92) ![Screenshot 2023-06-02 4 53 27 PM (1)](https://github.com/dotCMS/core/assets/102264829/7c3fdb47-c0b2-48dd-aa0f-dae69a5f7327)


### After (localhost)

![Screenshot 2023-06-02 at 5 24 59 PM](https://github.com/dotCMS/core/assets/102264829/fb42d197-3140-4fd8-a8e3-b74996e1a9d7) ![Screenshot 2023-06-02 at 5 26 14 PM](https://github.com/dotCMS/core/assets/102264829/d133ae68-aa4e-4398-a1e6-7768ebad4342)

The solution mostly involved a bunch of block comments, though this also gave me the chance to mend (via conditionals) some other small issues, where we'd see busted up inline styles like `style="text-align: ;"`.

**Comment by jdcmsd** [comment]
Found and fixed another unrelated error; table cells/headers were reading from `rowspan` for both `rowspan` and `colwidth`. Included it in the PR.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_78d179c2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by josemejias11** [comment]
> Interesting. What's the HTML source code look like?
@jdcmsd 
[Issue #24406.html.zip](https://github.com/dotCMS/core/files/11822067/Issue.24406.html.zip)

**Comment by jdcmsd** [comment]
Oh yeah, still very spacey.

![image](https://github.com/dotCMS/core/assets/102264829/c8a4aed5-fa13-40c5-b09b-028f29ffd1f0)

**Comment by jdcmsd** [comment]
I spun up a container using `master_78d179c2_SNAPSHOT` and pulled a few of the files from its tomcat deployment, such as:

- `/srv/dotserver/tomcat-9.0.60/webapps/ROOT/WEB-INF/velocity/VM_global_library.vm`
- `/srv/dotserver/tomcat-9.0.60/webapps/ROOT/WEB-INF/velocity/static/storyblock/render.vtl`

I found that these were still in their original form, prior to the changes in [#25144](https://github.com/dotCMS/core/pull/25144).

When I was originally testing my changes, every time I would run `gradlew deployWarTomcat`, the files in the tomcat folder would adopt the changes made to the source code. So, could this just be a question of needing to recompile?
