### ISSUE TITLE
UI - Favorite Page portlet: styles changes and reorder of item appearance

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24418]
### Parent Issue

#24326 

- Add To Bundle command needs to match same order on Content Search portlet
- Listing Page - Language dropdown should have a min-width of 175px so it does not jump in most cases.
- Listing Page - Search box should be ~ 250px (bigger than the language drop down by default).
- Listing Page - Clicking anywhere on the favorites accordion bar should open the favorites accordion.
- Listing Page - If there are no favorites, the favorites accordion should default to closed.
- Adding a Favorite - the url should be editable (maybe we update the thumbnail when changed?)
- The empty favorites listing is not centered:
![image](https://user-images.githubusercontent.com/37185433/226474489-9ea15f32-c730-42e8-90da-1908b98f7acf.png)

new design:
![image](https://user-images.githubusercontent.com/37185433/226738434-967847a0-8964-4ef4-866d-90f4f6884d11.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24382

**Comment by alfredo-dotcms** [comment]
PR: [issue-24418-pages-portlet-appearance-fixes](https://github.com/dotCMS/core/pull/24433)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_46f4640b_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
