### ISSUE TITLE
Error when right click on role name

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#24424]
### Problem Statement

When try to use functions using right click on role name doesn't load panel, there's an error message in console browser
`Uncaught TypeError: Cannot read properties of undefined (reading 'id')`

### Steps to Reproduce

1.- Go to Settings->Roles & Tools.
2.- Right click on any Role name.

![Screenshot 2023-03-20 at 4 58 40 PM](https://user-images.githubusercontent.com/12899960/226490513-eac6d05a-21ff-4410-b2fd-015ad9472788.png)
![Screenshot 2023-03-20 at 4 58 54 PM](https://user-images.githubusercontent.com/12899960/226490540-a4e1b907-6f93-4e72-83c5-b442bd78be25.png)
![Screenshot 2023-03-20 at 4 59 25 PM](https://user-images.githubusercontent.com/12899960/226490590-4e9a6b96-f9d3-4a0c-9c84-0b60da3b3103.png)
![Screenshot 2023-03-20 at 4 59 38 PM](https://user-images.githubusercontent.com/12899960/226490612-6e7329a3-510c-4bd6-bd1f-0846c077e990.png)

### Acceptance Criteria

When right click on role name error message shouldn't appears and be able to use any function inside of it (e.g. Edit, Lock, Unlock, Delete role).

### dotCMS Version

Demo (23.02) and dotcms-qa-lts2301

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110620

**Comment by swicken-dotcms** [comment]
Another customer hit this: https://dotcms.zendesk.com/agent/tickets/110862

**Comment by erickgonzalez** [comment]
Not reproducible in 22.03 LTS.
