### ISSUE TITLE
[UI]  Add the 'Tick' to the head of the missing sections & Hide Not working sections (Target)

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24431]
### Parent Issue

#24343

### User Story

All sections must contain the "Tick"

### Acceptance Criteria

All sections must contain the "Tick"
Hide Target sections since is not working yet. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 / Docker // FF
