### ISSUE TITLE
Favorite Pages: We need to catch when a page does not exist and not leave the portlet

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24438]
### Parent Issue
#24326 

current

https://user-images.githubusercontent.com/37185433/228674522-275fda18-eaab-4fdb-917f-5117530723b3.mov

fix

https://user-images.githubusercontent.com/37185433/228674136-df9a815b-25df-41d5-a8f6-63f8293be82b.mov

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24517/files

**Comment by jgambarios** [comment]
I see some errors based on permissions.

### Login As Chris Publisher - No `Dot Favority Page` permissions
Chris's user does not have permissions to the `Dot Favority Page` content type, and if I go to the Favorites Pages portlet:

![image](https://user-images.githubusercontent.com/923947/232151731-65a1621d-bd41-4bdd-befb-7bb0712ebe25.png)

### Login As Chris Publisher - With `Dot Favority Page` permissions
![image](https://user-images.githubusercontent.com/923947/232152164-8dbe5ebc-7b6c-48d0-953a-6107e68dfd9d.png)

I added to Chris's user permissions over the `Dot Favority Page` content type, and if I go to the Favorites Pages portlet:
![image](https://user-images.githubusercontent.com/923947/232152078-0d078a03-dd5e-4c2e-8009-5471aaa793ed.png)

---
That should not be the proper behaviour on wrong or missing permissions, the different sections of the portlet should load, even if they are empty, and/or maybe some modal with a Permissions error?.

**Comment by jgambarios** [comment]
We are handling now the case when the page does not exist but, even if the page does not exist, we should be able to delete the related Favorite Page element.

![image](https://user-images.githubusercontent.com/923947/232154766-8ece980f-f634-47a1-bc01-d1840dc1341a.png)
![image](https://user-images.githubusercontent.com/923947/232154807-07323cb0-93cc-4747-9c51-1b45cde36efb.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24722

**Comment by fmontes** [comment]
1. Add a page to fav assign Cris
2. Add permission to fav content type to Cris
3. Login as Cris
4. Go to pages
5. Try to EDIT the fav (not the page)
6. See the error.

**Comment by fmontes** [comment]
QA not needed because we're removing the "Share with" dropdown which will change all the permissions in this feature.
