### ISSUE TITLE
[UI] Add autofocus to the experiments forms that start with an input

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24430]
### Parent Issue

#24343

### User Story

Add autofocus to the experiments forms that start with an input

### Acceptance Criteria

Add autofocus to the experiments forms that start with an input

- [ ] Create Experiment Form 
- [ ] Add Variant From
- [ ] Set Goal Form

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Autofocus on inputs.

**Comment by bryanboza** [comment]
Fixed, now we have auto focus in the inputs mentioned above. Tested on release-23.05 // Docker // FF
