### ISSUE TITLE
Block editor: Drag and drop and copy/page video files to the editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24445]
### Parent Issue

#21988 

### User Story

As a user, I want to be able to drop or paste video files directly to the editor, the same way we do with images.

### Acceptance Criteria

- [ ] Drop a video, upload as dotAsset and insert to the editor

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/751424/227037304-706f1dca-34c2-4599-a0dc-cb38c161a313.png">

**Comment by bryanboza** [comment]
We have problems using the copy/paste on FF, if you try this on chrome, this is working as expected, but in FF we are just pasting the name of the file instead insert the video 

![Image](https://user-images.githubusercontent.com/2641437/231516552-373f5d7c-bd2e-45a4-acbd-486bfdaf0748.png)

**Comment by rjvelazco** [comment]
@bryanboza The `Clipboard` event is not fully supported on Firefox [MDN Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard)

<img width="734" alt="Screenshot 2023-04-12 at 1 12 36 PM" src="https://user-images.githubusercontent.com/72418962/231532781-e26b08b2-20ce-4c38-b28e-f4127ca46e24.png">

In fact, the `DataTransfer` for `files` is only activated on `drag&drop` not on `copy/paste`. [MDN DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer)

<img width="643" alt="Screenshot 2023-04-12 at 1 14 09 PM" src="https://user-images.githubusercontent.com/72418962/231533337-3a8c1176-313a-46c7-baf1-7691d119e5c8.png">

Currently, Firefox can only read `text`, `links`, and `images` on the `copy/paste` event. [MDN Clipboard Read](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read). However, other types of files like `documents` or `videos` can be read only in the drag&drop event.

**Comment by fmontes** [comment]
[We're ok](https://dotcms.slack.com/archives/CQQMX585N/p1681321000017929) with copy/paste not working in Firefox.

**Comment by fmontes** [comment]
@jdcmsd We need to add to the docs that copy and paste videos in the block editor don't work, but they can drag and drop or use menu to insert.

**Comment by bryanboza** [comment]
Fixed, since this is a known issue we will not fix that for now. Doc should be added
