### ISSUE TITLE
Favorites listing - the three dot menu actions need to be for the page content and not the Favorite content.  I believe this will need an endpoint - get state and workflow actions by URL.

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24442]
### Parent Issue
#24326 

Favorites listing - the three dot menu actions need to be for the page content and not the Favorite content. 

https://user-images.githubusercontent.com/37185433/229938763-ec3716f3-a7dc-4a08-901c-1f49739a9f86.mov

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24534

**Comment by josemejias11** [comment]
Blocked by https://github.com/dotCMS/core/issues/24861

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_21c1c10b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
