### ISSUE TITLE
Unable to copy a folder when the folder contains a page that has two versions live and draft

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#24441]
### Problem Statement

Unable to copy a folder when the folder contains a page that has two versions live and draft.
Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/110489

### Steps to Reproduce

1. log in to the demo site.
2. Create a new folder and inside the new folder create a new page and publish it.
3. Now edit the page and save it instead of publishing it.
4. right click on the folder and click mark for copy.
5. Try to paste the folder into another folder.
6. see the logs.

### Acceptance Criteria

The folder should be copied when it contains a page that has two versions live and draft.

### dotCMS Version

23.02

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

[error.log](https://github.com/dotCMS/core/files/11042850/error.log)

**Comment by erickgonzalez** [comment]
Note to QA:

Please also test with multilingual files.
