### ISSUE TITLE
File Browser Dialog doesn't show files in default lang as fallback if they doesn't exist in requested lang

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24444]
### Parent Issue

https://github.com/dotCMS/core/issues/22729

### Problem Statement

If a file doesn't exist in the requested language (only exists in the default lang) it's not showing in the file browser.

In older versions we fallback to the default lang.

### Steps to Reproduce

1- Create a content type with an image field.
2- Create new content and navigate to `/images/gallery/winter` to view files.
3- You are able to view all files (since they exist in English, the default lang).
4- Create new content but in Spanish and navigate to `/images/gallery/winter` to view files.
5- Message no files found.

### Acceptance Criteria

We should show files in the default lang if they don't exist in the requested lang.

### dotCMS Version

23.01 and demo (23.02), probably all LTS are affected by this.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110451

**Comment by dsolistorres** [comment]
**Note for QA**
When testing the fix for this issue, the File Browser dialog can be also tested when creating a new Menu Link. Menu links aren't multi-language, but they use the default language, so the File Browser dialog should show files in the default language.

**Comment by markatdotcms** [comment]
https://dotcms.zendesk.com/agent/tickets/111182

**Comment by markatdotcms** [comment]
https://dotcms.zendesk.com/agent/tickets/111181

**Comment by erickgonzalez** [comment]
Note to QA:

Default Lang: English

Folder with assets:
1- English
2- English and Spanish
3- Spanish

A.C:
Language English: 1 and 2
Language Spanish: 1, 2 and 3

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d8ef9ab_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
