### ISSUE TITLE
[UI] Change the mod date to be user friendly (Like Templates)

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24457]
### Parent Issue

#24343

### User Story

Use relative dates in the listing table in experiments. 

### Acceptance Criteria

Date should be relative. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24476

**Comment by dsilvam** [comment]
Passed Internal QA. Showing user friendly dates now. 



![Image](https://user-images.githubusercontent.com/1576794/229640869-c94a8768-2ea5-46c0-b86e-0a3a526bb2c6.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
