### ISSUE TITLE
Block editor: support YouTube videos

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24455]
### Parent Issue

#21988 

### User Story

As a user I want to be able to add youtube videos blocks to the editor.

### Acceptance Criteria

- [ ] User should paste a YouTube link and create a youtube block
- [ ] The input in the external video tab should take youtube links now

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

Use [Tiptap extension](https://tiptap.dev/api/extensions/placeholder)

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_2539461f_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Please implement the same behavior from the youtube video loader to the url video on the ' + ' and set it to lay below the video frame 

![Screenshot 2023-04-10 at 3 30 33 PM](https://user-images.githubusercontent.com/129882031/231003186-8afb81fd-822b-4d36-be34-f707a437e2cd.png)

**Comment by zJaaal** [comment]
This is happening in demo, we are working this for this release, here is the [ticket](https://github.com/dotCMS/core/issues/24594)

**Comment by fmontes** [comment]
@bryanboza read the comments.

**Comment by bryanboza** [comment]
ok, according to comments we move this to a new card. We can close this one and continue working on #24594
