### ISSUE TITLE
Exclude content in non default-variant version from PP

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24467]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

This happend any time we edit a Contentlet inside an Experiment's Variant and try to Publish it

### Steps to Reproduce

- Create a Page
- Create a ContentType and add a Text field called title
- Create a new Contentlet and set the title to "DEFAULT VERSION".
- Add the Contentlet inside the Page and Publish it.
- Create a Experiment using the newly created page.
- Add a Variant and Edit it.
- Edit the Contentle tinside the Page: Change the title by "VARIANT VERSION", and publish it.
- Push Publish this newly created Contentlet.
- Go to the target after the PP finished and check look for the new Contentlet into the Search Contentlet portlet, it is not showed.
- Go to the Query Tool and look for the Contentlet using its identifier, both version are showed.

### Acceptance Criteria

- The Contentlet must be showed in the Contentlet Serach Portlet after PP.
- In The QueryTool just the DEFAULT version must be list.
- Also check the contentlet_version_info table we must not have any version for the Variant.

### dotCMS Version

it was tested using the latest in master
Also you need to enabled the Experiment features to test it

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Not necessary to change this (at least for the foreseeable future).  You would need to have a very large number of experiments with experiment-only variants for this to be a problem.
