### ISSUE TITLE
Block editor add video.vtl to render a video by default

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24465]
### Parent Issue

#21988 

### User Story

As a user I want to be able to render videos our of the box in dotCMS block editor

### Acceptance Criteria

- [x] Rename video-node to `dotVideo`
- [ ] Add a `dotVideo.vtl` to `dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock/dotImage.vtl`
- [ ] Render video using the `<video>`

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Here is how we render images

```
<div style="text-align: $!item.attrs.textAlign">

    #if ($!item.attrs.href != "null")
    <a href="$!item.attrs.href">
    #end
        <img
            src="#if($!item.attrs.src && $!item.attrs.src != "null")$!item.attrs.src#{else}$!item.attrs.data.asset#end"
            alt="#if($!item.attrs.alt && $!item.attrs.alt != "null")$!item.attrs.alt#{else}$!item.attrs.data.title#end"
            title="#if($!item.attrs.title && $!item.attrs.title != "null")$!item.attrs.title#{else}$!item.attrs.data.title#end"
        />
    #if ($!item.attrs.href != "null")
    </a>
    #end

</div>
```

So you can have an idea for video.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_accf5f2d_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
