### ISSUE TITLE
Allow additional (2nd) variant input to Bayesian calculation (ABC Testing)

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#24473]
Parent Issue
https://github.com/dotCMS/core/issues/22760

User Story
As a Experiments User, I want Bayesian calculation allow to in include a second variant. That is the original (A) and the two variants (B and C). Able to have a results that takes into consideration based on https://www.evanmiller.org/bayesian-ab-testing.html#binary_abc_implementation.

Acceptance Criteria
- Start locally the analytics infrastructure (steps to do so can be found in issue: https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641)
- Start dotCMS instance as https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641 indicates it.
- Create an experiment for a page
- Create two variant for that page under the recently created experiment
- Define a REACH_PAGE goal as you want including for each variant page
- Access the frontend site, preferably using new sessions (incognito and/or other browsers) and navigate using one of the variants more than the other variant and the original option
- Access the /v1/experiments/<experiment id>/results and look for the bayesianResult element within the response JSON.
- Verify that the suggested option is actually the chosen variant to be navigated the most and that the probabilities map shows the actual probability for the tested options with, obviously, a greater value in favor of the variant.

Proposed Priority
Priority 2 - Important

External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
No response

Assumptions & Initiation Needs
No response

Quality Assurance Notes & Workarounds
No response

Sub-Tasks & Estimates
No response

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24533

**Comment by dsilvam** [comment]
Passed Internal QA: Results returned as expected: 

https://gist.github.com/dsilvam/31895818ed484f0d592eb8ee39c7e12e

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
