### ISSUE TITLE
Subfolders in Site Browser are not sorted alphabetically if the folder Name is changed #20104

### ISSUE THREAD

**Issue by MarkMarkham2** [dotCMS/core#24482]
### Problem Statement

Subfolders in Site Browser are not sorted alphabetically if the folder Name is changed #20104

### Steps to Reproduce

To Reproduce
Create a folder at root level
Create a few sub folders where the Titles and Names agree
They appear to be sorted alphabetically sorted
Add another folder where the Title and Name are different
The folder is sorted by Title not Name
![Browser folder tree](https://user-images.githubusercontent.com/128837754/227597433-4551f696-b0d7-45b0-840c-0793fde9ef17.png)
![Site or Folder tree](https://user-images.githubusercontent.com/128837754/227597629-3020df66-4d7d-48e9-87a7-c5687f5479a5.png)

reported and verified in https://dotcms.zendesk.com/agent/tickets/110684

### Acceptance Criteria

all folders even if renamed should be  sorted alphabetically 

### dotCMS Version

PLATFORM EDITION: 23.01

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

reported and verified in https://dotcms.zendesk.com/agent/tickets/110684

https://dotcms.slack.com/archives/C028Z3R2D/p1679676989653299

### Assumptions & Initiation Needs

reported fixed in https://github.com/dotCMS/core/issues/20104
but this view was over looked
![Site or Folder tree](https://user-images.githubusercontent.com/128837754/227598902-c412e63f-99fc-4802-a481-8415963240b3.png)

**Comment by erickgonzalez** [comment]
Working as it should, now the site selector is sort by folder name (the same sort as the Site Browser)

![Image](https://github.com/dotCMS/core/assets/5278970/d67f4800-b866-4ce1-8128-b27a0bf59288)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
