### ISSUE TITLE
Block editor: `[Object, object]` in the value when save a contentlet with no changes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24481]
### Parent Issue

#21988 

### Problem Statement

When you save or publish a contentlet with a block editor field with out change it saves `[Object, object]` as it value

### Steps to Reproduce

https://user-images.githubusercontent.com/751424/227599330-2667be9b-f0a8-4b81-aef7-9e6093209505.mp4

```[tasklist]
### Acceptance Criteria
- [ ] Block editor should save the content correctly when no changes made

```

### dotCMS Version

23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by bryanboza** [comment]
Fixed, tested on release 23.03 // Docker // FF. 

Tested with a new content type with a block field and also using the block content type from the starter site and I'm unable to reproduce
