### ISSUE TITLE
UI fixes in Angular

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24486]
### Parent Issue

#24317

### Problem Statement

Fix the list of the UI issues in Angular:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/751424/227608768-30c55b28-7ef8-43fe-83c1-0311617570e3.png">
- Make it wider to read the full text.
- Check if we can make it to fit the text, maybe using `fit-content`

--------------------

<img width="776" alt="image" src="https://user-images.githubusercontent.com/751424/227609077-080b0fd2-6b36-4c8a-b9d3-a7da3045c8bc.png">

- Make it rounded, external use the `md` variables
- Internal boxes the `sm` variable

--------------------

<img width="672" alt="image" src="https://user-images.githubusercontent.com/751424/227609376-f94816f8-a4e1-460e-aa97-0ed76a68f214.png">

- Use `md` variable for both
- See if in the top module you can use `overflow: hidden` and round the wrapper box

--------------------

<img width="623" alt="image" src="https://user-images.githubusercontent.com/751424/227609896-ec65cffd-ab61-4727-ab11-7bc218453ac1.png">

- Center the lock icon

### Steps to Reproduce

N/A

### Acceptance Criteria

N/A

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Looks good to me... the lock icon could be 0.5px more centered, but is fine.

**Comment by wezell** [comment]
Needs Work - we are hiding the content type variable names which is really primary information

![Screen Shot 2023-04-04 at 3 53 34 PM](https://user-images.githubusercontent.com/934364/229905516-0481e9cc-3d50-4760-b66c-5874f7b30ab3.png)

**Comment by zJaaal** [comment]
That is being fixed in this [PR](https://github.com/dotCMS/core/pull/24547) It is actually solved, but I saw the opportunity to refactor an old button that was being used in that component, but is a really old button and it's being used in several places so I'm not sure about that refactor

**Comment by fmontes** [comment]
@wezell we're working that in here: https://github.com/dotCMS/core/issues/23816
