### ISSUE TITLE
Generating a thumbnail for /members/index fails.. Again, we should be able to save a favorite even without a thumbnail.  On the favorites listing, if we don't have a thumbnail, we should show a skeleton.

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24496]
### Parent task
https://github.com/dotCMS/core/issues/24326

### Description

skeleton thumbnail when no screenshot was created/saved from html
![image](https://user-images.githubusercontent.com/37185433/228083640-44f8b85c-c0e2-4c18-8ab0-0ffe36b79e32.png)

skeleton thumbnail when error creating screenshot from html
![image](https://user-images.githubusercontent.com/37185433/228083702-78a6f237-83a4-4836-837e-da86e34fe447.png)

### Steps:
1) Go to a Site Browser, and open `Colorado Preseason Special`
2) try to create a favorite page and a generic thumbnail will be shown
3) go to pages portlet and verify the generic thumbnail is shown

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24510

**Comment by fmontes** [comment]
The library we use to generate thumbnails [don't support some CSS properties](https://html2canvas.hertzen.com/features/) and my guess is that the template for "Colorado Preseason Special" use some of those.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_9dc362cb_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1

When creating a bookmark for a page created with nothing in it, should we implement a generic thumbnail for it as well?
![Screenshot 2023-05-10 at 3 22 05 PM](https://github.com/dotCMS/core/assets/129882031/b92b6512-9212-401c-b01f-ca32cb6d0e6c)

**Comment by fmontes** [comment]
If the page is blank this is expected, we're not reading the pixels in the image to id that is white and fallback.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_8c0a542e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
