### ISSUE TITLE
Content with an invalid detail page fails to render/instanciate

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24490]
### Parent Issue

If you have a contentlet of a Content type that has 
1. an invalid detail page and 
2. No content type urlmappattern

The api calls with this content come back empty and pages with this content on them will fail to render and give a 404 instead.  This is happening on our current starter site - the homepage will not load and gives a 404 instead.

![Screen Shot 2023-03-24 at 3 56 37 PM](https://user-images.githubusercontent.com/934364/227626650-47fcb757-b878-43ee-86c7-9c74d7ca9ce6.png)

### Problem Statement

We need to be more resilient of bad data and not crap out when a content type's detail page gets wiped out by accident

### Steps to Reproduce

1. On a fresh starter site /  demo site, edit products and remove the urlMapPattern
2. from the contentlet search screen find the page `product-detail` and delete/destroy it.
3. flush the cache
4. try to hit the public homepage - you get a 404

### Another Broken Case:
1. On a fresh starter, open a piece of YouTube content for editing.
2. You will see a "Preview" button. If you click it, you go to Edit Mode and see a "This URL does not exist." message.  We should not show a "Preview" button unless the content has a valid urlMap.

### Another Broken Case:
1. On the new pages screen, you will see a bunch of Youtube videos shown as "pages.  If you click on them, you will get the "This URL does not exist." message.  We should not be showing these at all.

### Acceptance Criteria

We should be able to delete a detail page, flush cache and still see pages where the content lives

### dotCMS Version

23.03

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, tested on release-23.05 // Docker // FF 

Tested every one of the cases described above and now it is working as expected
