### ISSUE TITLE
CLI: Push languages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24507]
### Parent Issue

#24279

### User Story

As a user, I want to be able to push new or updated language information to dotCMS using a command line interface (CLI). I should be able to provide a file containing the language information in either JSON or YAML format. The CLI should be able to parse the file and save the language information to my CMS configuration. If a language already exists in the database, I should be able to update its information with the new data provided in the file. This will allow me to efficiently manage language information and keep it up-to-date with the latest changes.

### Acceptance Criteria

1. The CLI should accept a valid file path to a JSON or YAML file containing language information.
2. If the file path is invalid or the file cannot be parsed as JSON or YAML, the CLI should display an error message indicating the issue.
3. If the language information in the file is already in the application's database, the CLI should update the existing language record with the new information provided in the file.
4. If the language information in the file is not already in the application's database, the CLI should create a new language record using the information provided in the file.
5. The CLI should display a success message indicating that the language information was successfully saved or updated in the database.
6. If there are any errors during the saving or updating process, the CLI should display an error message indicating the issue and roll back any changes made to the database.
9. The CLI should be well-documented with clear instructions on how to use it and what to expect during the language information saving or updating process.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jgambarios** [comment]
When pushing a YAML file we should be able to infer the file type using the file name, currently it is required to pass the format.

Not working
```
lang push -f japanese.yml
[ERROR] ❗  Unable to parse the input file. Please check that it is a valid JSON or YML file.
```

Working
```
lang push -f japanese.yml -fmt YAML 
Attempting to save language with code [ja]
The id [5017431] provided in the language file will be used for look-up.
Language with code [ja] successfully pushed.
---
id: 5017431
languageCode: "ja"
countryCode: "JP"
language: "Japanese"
country: "Japan"
```

**Comment by nollymar** [comment]
**Note to QA:** Please consider this punchlist when testing 

1. make sure iso codes are all case insensitive
2. show the iso in the listing
3. make sure we support languages without countries
4. id should be optional

**Comment by fabrizzio-dotCMS** [comment]
I verified the items from the Notes above. And they're all fine.
The language command is looking great I liked very much that we can add a brand new lang simply by specifying the iso code. That makes it extremely simple to use. 

however, I found a couple of small details that I feel we need to fix.

When attempting to create a language using a command like:

`dot lang push --byIso=fr-FRA`

we get an answer from the server like:

```
Attempting to create language with iso code [fr-FRA]
javax.ws.rs.NotFoundException:  Status: (404) With error: {
  "message" : " `fr-FRA` is an invalid language tag "
}
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:58)
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:20)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
	at com.sun.proxy.$Proxy53.create(Unknown Source)
	at com.dotcms.cli.command.language.LanguagePush.pushLanguageByIsoCode(LanguagePush.java:119)
	...

```

Things to notice here:

1. We should try to show only simplified messages to the user and omit the stack-trace 
2. Since we're trying to create a new language here this error should be a BadRequest, not a 404

On the other hand when we do 

`dot lang pull lol `

The error is 

```
[ERROR] ❗  Language not found: lol
[ERROR] ❗  A language with id or ISO code [lol] could not be found.
```

In this case, the error shown here doesn't have a stack trace which is fine but I would have expected to see here the 404 code coming back.

**Comment by fabrizzio-dotCMS** [comment]
This effort has used the status codes returned by the existing endpoint. and all other error messages will be standardized in a separate ticket. Therefore this is passing.
