### ISSUE TITLE
[UI] Promote winner

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24500]
### Parent Issue

https://github.com/dotCMS/core/issues/22455

### User Story

As a product owner, I want to promote the winner functionality and update the experiment screens once a variant is promoted.

### Acceptance Criteria

- Winner functionality is successfully promoted
- Experiments screens are updated with the promoted variant
- Only can promote a Running or Ended Experiment.
- Can Promote more than one time at the same experiment
- If the variant is promoted, show a tag to identify it.
- If the Bayesian gets a clear winner, show a tag to identify it.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Image](https://user-images.githubusercontent.com/1909643/236876178-5994a38f-e3b8-4ff0-8f2b-0fa8884398a6.png)

### Assumptions & Initiation Needs

- Up and Running experiment with at least one variant

## Subtasks
- [x] #24764

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24811

**Comment by bryanboza** [comment]
A lot of new changes implemented after this card, the acceptance criteria has been deprecated by new functionality
