### ISSUE TITLE
Triage software composition analysis reports

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#24503]
### Task

There are a number of SCA reports available. Security team would like to ask development to analyse those reports and fix applicable ones. Reports are available here: 

1. https://github.com/dotCMS/core/security/dependabot?page=1&q=is%3Aopen+severity%3Ahigh%2Ccritical
2. https://drive.google.com/file/d/10eT0J5Sa_3m9Wbz_t3Ov_EPWrhxVzu3a/view?usp=sharing

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by sfreudenthaler** [comment]
stale.  @mbiuki can revisit and decide to refresh this card, drop it, or merge with another card where applicable

**Comment by mbiuki** [comment]
A list of the new compilation is located here: https://drive.google.com/drive/folders/1fEtzKXrXiGOoW8EgMx6KJRH_K7sGYz0I?usp=drive_link
This is an epic and whould be on top of the 3rd party package update drills that we conduct at the moment.

**Comment by sfreudenthaler** [comment]
probably split this into analyse and patch epic (issues)
