### ISSUE TITLE
Traffic redirect not Working in index page

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24511]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When you create a Experiment inside the root index page the redirect traffic is not working it show the DEFAULT Version all the time no matter if the user is assign into any other Variant.

### Steps to Reproduce

- Start dotCMS up with the full starter.
- Create a Experiment in the /index Page.
- Create a variant change whatever you want, called in variant_1.
- Change the traffic split to 99% to variant_1 and 1% to the DEFAULT Variant
- Add a Goal and Start the Experiment.
- Log out and GO to the Index page
- Check the experiment_data item into the LocalStorage to make sure that you was assign to variant_1.
- Check if you are seeing the variant_1.

### Acceptance Criteria

The redirect must work even into the index page.

### dotCMS Version

latest in master
Also you need to enabled the Experiment feature.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
It was fix in this PR https://github.com/dotCMS/core/pull/24569

**Comment by dsilvam** [comment]
Needs work: When accessing the index page directly it is not redirecting to the variant.

**Comment by dsilvam** [comment]
Needs work: Before redirecting the page to the version on the variant, the version on the default variant is showing for a short moment. We need a way to avoid this.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/24741

**Comment by dsilvam** [comment]
Passed Internal QA: Redirect happening to the expected Variant and no flickering.

**Comment by bryanboza** [comment]
Fixed, now this is working in the index page.
