### ISSUE TITLE
Unable to create a site search index 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24524]
### Problem Statement

Currently, the site search index portlet is not loading the job scheduler tab, and we are unable to create a search index. This is preventing us from providing an effective search experience for our users and may lead to users being unable to find the content they need.

JSP Error: https://gist.github.com/bryanboza/175041c31ce690dd47b5af4bb7d02ab3

### Steps to Reproduce

- Login as admin
- Go to Dev-Tools --> Site Search
- Try to create a new site search index using the job scheduler 

### Acceptance Criteria

- The job scheduler tab should be visible and functional in the site search index portlet.
- When I create a new search index, the process should complete successfully and the search index should be available for use on the website.
- The search index should include all relevant content on the website, including pages, documents, and other assets.
- The search index should be optimized for performance and speed, so that users can quickly find the content they need.

### dotCMS Version

Tested on master 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0
