### ISSUE TITLE
[UI] Clean up the session storage with the key SESSION_STORAGE_VARIATION_KEY  when the session expires

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24531]
### User Story

As a user, when the session expires, I want to clean up the session storage with the key of the constant SESSION_STORAGE_VARIATION_KEY.

### Acceptance Criteria

- The Session Storage with the key SESSION_STORAGE_VARIATION_KEY should be cleared when the session expires.
- Clearing Session Storage key should not affect the user's browsing experience.
- The cleaning process should not cause any data loss or corruption.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dsilvam** [comment]
Passed Internal QA: `variantName` removed from sessionStorage on session expiration.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
