### ISSUE TITLE
Unable to edit a template vtl files 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24545]
### Problem Statement

Currently, when I attempt to edit a VTL file in the template editor, my changes are not being saved, even though no errors are being displayed. This is limiting my ability to make updates and improvements to our templates. 

### Steps to Reproduce

- Log in to dotCMS as a user with permissions to edit templates.
- Navigate to the template editor and select a template that contains a VTL file.
- Open the VTL file and make changes.
- Attempt to save the changes by clicking the "Save" button.
- Notice that the "Saving Changes" message appears briefly, but the changes are not actually saved.

### Acceptance Criteria

- I should be able to edit a VTL file in the template editor and have my changes be saved properly.
- When I click the "Save" button, the changes should be saved immediately and without error.
- If there are any errors preventing the changes from being saved, they should be displayed clearly and with instructions on how to fix them.
- The system should save the changes even if the VTL file contains complex code or syntax.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by freddyucv** [comment]
I reproduced it with the blog-detail.vtl

**Comment by fmontes** [comment]
@bryanboza we need more detail steps on this, since we can repro.

**Comment by prestonso** [comment]
@bryanboza Any update here?

**Comment by prestonso** [comment]
Closing due to no response.
