### ISSUE TITLE
[UI] Order the experiment listing

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24541]
### Parent Issue

#24343

### User Story

- Order of Experiment Listing should be 1. Running, 2. Scheduled, 3, Draft, 4. Ended, 5. Archived

### Acceptance Criteria

- [ ] Order of Experiment Listing should be 1. Running, 2. Scheduled, 3, Draft, 4. Ended, 5. Archived

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA. Properly ordered. 



![Image](https://user-images.githubusercontent.com/1576794/230495758-560cb34e-8971-4814-ac57-e06096e01308.png)
