### ISSUE TITLE
Create new Complete Status for Experiment

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24540]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### User Story

When a Variant of an Experiment is promoted we need to move the Experiment to a new Status called `Completed`,
The Experiment is able to move to this new Status from Ended.

We need to create a new end point for this

URL: `/v1/experiments/<experiment_id>/_complete?variantName=<variant> `

'variantName' is the name of the Variant to be promoted.

### Acceptance Criteria

The Endpoint must respond the following according to the current Experiment Status.

- DRAFT: must response 400, it is not possible to go from DRAFT to Completed
- SCHEDULED: must response 400, it is not possible to go from DRAFT to Completed.
- RUNNING and ENDED: 200, Also the Experiment's current Status must change.

Also if the Experiment or the Variant doesn't exist the endpoint must respond 404. 

Also the Variant must be promoted and all the Experiment's Variants must be archived

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
After discussing together with @freddyucv we're not doing this.
