### ISSUE TITLE
CLI: Delete languages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24549]
### Parent Issue

#24279

### User Story

As a user, I want to be able to delete a language using a CLI command by providing either its id or tag. 

When I use the delete language command, I should be able to provide either the language's id or tag as a parameter. The command should then verify that the language exists in the system and prompt me to confirm that I want to delete it. If I confirm, the language should be removed from the system, and I should receive a confirmation message that the deletion was successful.

If I try to delete a language that does not exist or provide incorrect input, the command should provide an appropriate error message explaining the issue.

Overall, the delete language CLI command should provide a simple and efficient way to manage the languages in dotCMS, allowing me to easily remove any unnecessary languages and keep my data organized.

### Acceptance Criteria

1. The user can provide either the language's id or tag as a parameter to the command.
2. The command verifies that the language exists in the system before proceeding with the deletion.
3. The command prompts the user to confirm that they want to delete the language before proceeding.
4. If the user confirms, the language is deleted from the system and a confirmation message is displayed.
5. If the user cancels the deletion or provides invalid input, the command does not delete the language and displays an appropriate error message.
6. After the language is deleted, it is no longer listed in the system's language inventory.
7. The language cannot be accessed or modified after it has been deleted.
8. If the user tries to delete a language that is already deleted, an error message should be displayed.
9. The delete language command should not affect any other data or functionalities in the system.
10. The delete language command should be properly documented in the system's user guide or help menu.

**Comment by jgambarios** [comment]
When removing a language with an ID that does not exist, we get a generic error message, but we need a more detailed response message, maybe with a 404 and a Not found.

```
lang remove 4813464
[ERROR] ❗  Error occurred while pulling Language Info: [4813464].
```

**Comment by nollymar** [comment]
**Note to QA:** Please consider this punchlist when testing 

1. make sure iso codes are all case insensitive
2. show the iso in the listing
3. make sure we support languages without countries
4. id should be optional

**Comment by fabrizzio-dotCMS** [comment]
The following error message must be presented better to the end-user
When removing a language that still has content attached to it and we do

`dot lang remove 1`

Attempting to delete the following language:
language: [English] id: [1] code: [en] country:[United States] countryCode: [US] isoCode: [en-us]

Are you sure you want to continue? [y/n]: y
```
javax.ws.rs.WebApplicationException:  Status: (400) With error: {
  "message" : "Error deleting Language: Content using this Language exists.  You cannot delete a Language until all content using it has been deleted."
}
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:61)
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:20)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
	at com.sun.proxy.$Proxy53.delete(Unknown Source)
	at com.dotcms.cli.command.language.LanguageRemove.call(LanguageRemove.java:61)
```

**Comment by fabrizzio-dotCMS** [comment]
This effort has used the status codes returned by the existing endpoint. and all other error messages will be standardized in a separate ticket. Therefore this is passing.
