### ISSUE TITLE
[UI] Limit the Experiment name to 50 characters when you add the experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24546]
### Parent Issue
#24343

### User Story
As a user, I want the header component of Experiments to have a character limit and an ellipsis to be added when the content exceeds the limit. Additionally, I want a tooltip to be displayed when hovering over the header component to show the full-text title.

### Acceptance Criteria

- The header component of Experiments will have a character limit of 50.
- If the content of the header component exceeds 50 characters, an ellipsis will be added to the end of the content.
- When the user hovers over the header component, a tooltip will display the full-text title.
- The tooltip will disappear when the user moves the mouse away from the header component.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs

- The header component of Experiments currently does not have a character limit or ellipsis.
- The tooltip feature will be added to the header component.

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by dsilvam** [comment]
Needs work: I think we can prevent the user from typing more than 50 chars by disallowing it.

**Comment by dsilvam** [comment]
Passed Internal QA: better validation now. 



![Image](https://user-images.githubusercontent.com/1576794/233419718-2e7effb9-339d-41ef-b260-e778a6ec6fed.png)

**Comment by bryanboza** [comment]
We need to do the same validation at BE level, after this fix we are just allowing 50 characters in FE but we shows a different message on Backend... 

Need to be consistent 


![Image](https://github.com/dotCMS/core/assets/2641437/3771a292-2254-4b0b-9ed3-66af76baac9b)

**Comment by hmoreras** [comment]
Working as expected on master, moved to next release. 

https://github.com/dotCMS/core/assets/31667212/433cc012-9e40-4270-b5f7-2f11964bc683

**Comment by dsilvam** [comment]
Sticking like this for v1. Not fixing what was reported by @bryanboza on this card.

**Comment by bryanboza** [comment]
Ok, after the second revision we need two thing here: 

@dsilvam in order to close this one please create the new card related to the BE part to keep the record and leave this as a pending thing to fix. 

And related to the message, 


![Image](https://github.com/dotCMS/core/assets/2641437/23be0697-1fbe-49e4-aad3-e0b620fc0268)

I think we are showing unnecessary information `and has 51` is not necessary, is ok just say that you have more than 50, this b/c after 51 characters you are unable to continue typing

**Comment by oidacra** [comment]
New acceptance criteria handled.

<img width="641" alt="Screenshot 2023-07-03 at 11 05 51 AM" src="https://github.com/dotCMS/core/assets/1909643/a89b9a6c-8eb9-4a61-aa75-f1a8331b68f3">

**Comment by bryanboza** [comment]
Fixed, now we showing the correct WARN 

![Image](https://github.com/dotCMS/core/assets/2641437/129100b8-f0bb-4c54-a15f-3145c6fad101)

Tested on master // Docker // FF
