### ISSUE TITLE
Allow customers to create sandboxes / experimental / training sites

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24550]
### User Story

Customers want to be able to spin up shallow replicas of their site for temporary use and to experiment.

### Acceptance Criteria

TBD

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110778

### Sub-Tasks & Estimates

- [ ] #24116 Self contained Docker Image

**Comment by fmontes** [comment]
Moved to AirFocus
