### ISSUE TITLE
Avoid validating scheduling when archiving an Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24553]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

When an ended Experiment is tried to be archived, it can fail on a validation on its Scheduling. 

### Steps to Reproduce

Try to archive an ended Experiment which ended a few days ago.

### Acceptance Criteria

Archiving an ended Experiment doesn't never fail.

### dotCMS Version

23.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
Passed Internal QA. User can archive ended experiments now.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF 

Unable to reproduce after the change
