### ISSUE TITLE
Block Editor Video Node MimeType Property Typo

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#24556]
### Parent Issue

https://github.com/dotCMS/core/issues/23863

### Problem Statement

In the `block editor` video node `json`. The property is called `mineType` which is a typo, while in `dotAsset` the property is called `mimeType` which is the correct name.

#### in block editor:

```json
{
  "type": "dotVideo",
  "attrs": {
    "src": "/dA/3f6ba3f29edc30313a922179fa43acd5/asset/dotCMS - Remote block editor extensions.mp4",
    "mineType": "application/mp4",
    ...
  }
}

```

#### dotAsset:

```json
{
  "contentlets": [
    {
      "publishDate": "2023-03-31 18:25:48.926",
      "assetContentAsset": "3f6ba3f29edc30313a922179fa43acd5/asset",
      "mimeType": "video/mp4",
      ...
    }
  ]
}
```

### Steps to Reproduce

1. Go to any blog.
2. Add a video.
3. Get the blog content.
4. Look for the `blogContent` property.
5. See the Video Node Block, there a `mineType` property.

https://user-images.githubusercontent.com/72418962/229902066-ade6604b-f74e-4a8c-9bde-fd964c2940d7.mov

### Acceptance Criteria

Rename the property from `mineType` to `mimeType` in the video node `json`.

### dotCMS Version

Release-23.05

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CQQMX585N/p1680619492805539

**Comment by manuelrojas** [comment]
Passed Internal QA
Docker Image: [dotcms/dotcms:23.05_9344a860_SNAPSHOT]

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/3438705/231312932-03c3dff9-a0e7-47bd-8d72-173f3082cd3a.png">
