### ISSUE TITLE
Favorite pages: Show archive filter is not working (check blog pages and all pages)

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24561]
### Parent Issue

https://github.com/dotCMS/core/issues/24326

### Problem Statement

Show archived not working - at least when I archive a blog and check "show archived", nothing shows up.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/37185433/229943007-d242ffbb-4bcc-4b07-b923-4e763f8e2760.png)

### Acceptance Criteria
1) archive a page
2) click on "Archive" checkbox and you shoul see it

Show archived should display archived pages

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24562/files

**Comment by jgambarios** [comment]
"Show Archived" check box works as expected, but the list shows archived elements when it should no.

![image](https://user-images.githubusercontent.com/923947/232530262-fd85cf1a-3230-4cca-9126-a16675add0d7.png)

A fix for it was sent in https://github.com/dotCMS/core/pull/24635 - Waiting for that merge to re-test this functionality.

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24676/files

**Comment by fmontes** [comment]
Ok this is not showing the skeleton row now, but I just discovered that you can click an archived item and it throws a not found url. Will be fix in a next issue.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_21c1c10b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Archive filter is not hidden the cards from the Bookmarks view

https://github.com/dotCMS/core/assets/129882031/53837269-d714-44e0-9f9f-0fea3d4a0c66

**Comment by fmontes** [comment]
Yeah, for version one that's expected.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
