### ISSUE TITLE
badType:url while importing Page content type

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#24572]
### Problem Statement

When page content type exports so all contentlets have full path in "url" column (csv file) e.g 

/safety-health/safety-topics/topics/populated-cities

So while importing those urls creates badType:url error because "url" field accepts only words without "/" e.g 

populated-cities

### Steps to Reproduce

Create a New Page content type or use the existing Page content type

Create new contentlet for Page content type and export it.

In export (csv) file url comlumn will have full url path

### Acceptance Criteria

The url path should have only last word(s) as path or while importing page content type should configure in such as way that It preassume the full path as url

### dotCMS Version

Almost all versions: Tested on 22.03.5 - 23.03

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110773

**Comment by erickgonzalez** [comment]
closing in favor of https://github.com/dotCMS/core/issues/28306
