### ISSUE TITLE
Listing Page - When you click a page to preview, we are going to need a spinner (or spinning cursor, something) or something that shows things are "happening"

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24578]
### Parent Issue

https://github.com/dotCMS/core/issues/24326

### Task

Listing Page - When you click a page to preview, we are going to need a spinner (or spinning cursor, something) or something that shows things are "happening"

### Mock
![image](https://user-images.githubusercontent.com/37185433/230479196-285a7b5b-73f1-48c6-b5ce-5c9125a54778.png)

Use spinner component from primeNG
https://primeng.org/progressspinner

### Steps
- Go to `Pages` portlet
- Click on a page to redirect to EDIT MODE

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24580

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_410eb1e5_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1

We are using two types of spinners. One for the Pages view and one for the preview of the page itself. Lets use one design across the app. (Basically the size)

Its hard to see, but its there.

https://github.com/dotCMS/core/assets/129882031/4694f175-70a4-463f-be42-ed478f43602d

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_a44c4a30_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
