### ISSUE TITLE
When you click `Edit` go straight to EDIT in Edit Page.

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24583]
### Parent Issue

#24343

### User Story

In the configuration screen in experiments the edit button in each variant show load the edit mode in the edit tab

### Acceptance Criteria

Edit button in variant should go directly to edit tab in edit mode

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: After clicking on Edit a Variant it's going straight to Edit mode.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_f16ce945_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
