### ISSUE TITLE
Rename from "Start Experiment" to "Schedule Experiment" when the Experiment has schedule

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24585]
### Parent Issue
#23625

### User Story
As a user, I want the "Start Experiment" button to be renamed to "Schedule Experiment" when a schedule has been added to the experiment so that it accurately reflects the action that will occur.

### Acceptance Criteria
- The button label changes from "Start Experiment" to "Schedule Experiment" when a schedule is added to the experiment.
- The button label remains as "Start Experiment" when no schedule is added to the experiment.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The experiment scheduling functionality is already implemented.
- The "Start Experiment" button is currently displayed before a schedule is added to the experiment.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: Button labeled "Schedule" when Scheduling present, and "Start" when it is not.
