### ISSUE TITLE
Update EMA to allow for multiple paths / endpoints

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24581]
### User Story

Customers want to roll out headless experiences for limited portions of their site.  Right now, our EMA system allows you to configure a rendering endpoint 1 PER site and is expecting the whole site to be built with EMA enabled.

By way of example, we are trying to get our documentation site built as an SPA - we do not want to touch the rest of the site - but it would be great if we could point all `/docs/latest/*` requests to the SPA which could be in charge of rendering the doc site in edit mode.

Having this ability would allow dotCMS customers to roll out headless pages/solutions across portions of the their site incrementally without forcing them into an 100% headless solution.

To do this, I think we should change the EMA App/plugin/code and add a key/value pair.  The key would be a regex pattern that a EMA request will be matched against and the value will be the receiving endpoint for any requests that matched the pattern. 

### Acceptance Criteria

Allow portions of a site/site content to be rendered using "EMA" without forcing the entire site to be rendered as EMA.

1. Make sure these pages render in EMA:
https://demospa.dotcms.com/destinations

3. Enable EMA on the demo site for only the /destinations 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Is a key value, where key is the path or regex and the value is the url to the frontend.

Do we need auth token?

**Comment by fmontes** [comment]
```
[
    {
    "pattern":"/blogs/(.*)" ,
    "urlEndpoint":"https://demospa.dotcms.com/ema",
    "headers":[
      {"Authorization", "Bearer TOKEN"}
   
      ],


   ]
```

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA
Here's an example of the JSON configuration that can be used for testing purposes (ping me for the EMA Server URL):
```json
[
   {
      "pattern":"/blogs/(.*)",
      "urlEndpoint":"<EMA-SERVER-URL>",
      "includeRendered":false,
      "headers":{
         "authenticationToken":"",
         "X-YOUR-HEADER":"dotCMS"
      }
   },
   {
      "pattern":".*",
      "urlEndpoint":"<EMA-SERVER-URL>",
      "includeRendered":false,
      "headers":{
         "authenticationToken":"",
         "X-YOUR-HEADER":"dotCMS"
      }
   }
]
```
You can add as many URL Patterns as necessary. Reach out to me for testing backwards compatibility as well.

**Comment by danielmdob** [comment]
Passed internal QA.

**Comment by bryanboza** [comment]
This is working fine if you add the whole expression, but in case you want to render some specific URL this is not working 

Tested using just the first part of the expression:
```
[
   {
      "pattern":"/blogs/(.*)",
      "urlEndpoint":"<EMA-SERVER-URL>",
      "includeRendered":false,
      "headers":{
         "authenticationToken":"",
         "X-YOUR-HEADER":"dotCMS"
      }
   }
]
```

**Comment by jcastro-dotcms** [comment]
After double-checking with @fmontes , I confirmed that going to the /index page **and THEN** clicking the Blogs page inside the Edit Mode will not work with the EMA rendering process.

The Lunik Team can take a look at it to see if we can figure out a way to accomplish that. So, @bryanboza please create a new ticket for it.

**Comment by bryanboza** [comment]
Fixed, tested on master with the EMA app and this is working as expected, after play with this server I noticed we have an error regarding the navigation, but it was reported in a new card #25718
