### ISSUE TITLE
Unable to add Rich Text content to the index page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24590]
### Problem Statement

When you start with the full starter and try to add a new piece of content type rich text to the index page, we are getting a generic error and we are unable to add this to the page. 

![image](https://user-images.githubusercontent.com/2641437/231015836-53f982ae-ec3a-4ed6-ae16-1c8c69a9307b.png)

We need to take look of this error since the index page is using the default container and also the default container include de webPageContent.vtl file. then we need to support that type of content without problems 

Here the log: https://gist.github.com/bryanboza/ea51802aa886cb53a97e1bdf9a282442

### Steps to Reproduce

- Start a new instance using the full starter 
- Login as admin 
- Try to edit the index page 
- Try to add a new piece of content type Rich Text to the page 

### Acceptance Criteria

- We need be able to add that piece of content to this container without problems 
- In case of error we need to be more specific and bring more details to the end user 

### dotCMS Version

Tested on release 23.05 // Docker // FF 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
This issue was introduced in the fix for this ticket: https://github.com/dotCMS/core/issues/23225

We're closing this one in favor of the original one.
