### ISSUE TITLE
Template Builder: We are not listing the default container adding a container to some template

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24591]
### Parent
#24535 

### Problem Statement

Currently, when I attempt to select a container for my templates in the template portlet, the list of available containers does not include the default containers that are provided by dotCMS.

![image](https://user-images.githubusercontent.com/2641437/231016799-d32f1a5c-cd4c-40a9-8233-a0eb9de690eb.png)

FYI: If you try to find for "default" using the filter we are able to select that one without problems. 

### Steps to Reproduce

- Log in to dotCMS as a user with permissions to manage templates.
- Navigate to the template portlet and select a template to edit.
- Attempt to select a container for the template by clicking the "Container" dropdown.
- Notice that the list of available containers does not include the default containers that are provided by dotCMS.

### Acceptance Criteria

- The list of available containers in the template portlet should include all default containers provided by dotCMS.
- When I select a container from the dropdown, the system should correctly apply that container to my template without error.
- If there are any errors preventing the container from being applied, they should be displayed clearly and with instructions on how to fix them.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by danielmdob** [comment]
@fmontes pretty sure this shouldn't happen in the new template builder, just in case it's relevant.

**Comment by danielmdob** [comment]
> @fmontes pretty sure this shouldn't happen in the new template builder, just in case it's relevant.

* is not happening.
