### ISSUE TITLE
When loading a page in edit mode, make the pages favorites star load async.  Right now, if the query fails, the whole page load fails.  You can see this by deactivating you indexes and browsing to a page and try to edit it.

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24604]
### Parent Issue

https://github.com/dotCMS/core/issues/24326

### Task

When loading a page in edit mode, make the pages favorites star load async. Right now, if the query fails, the whole page load fails. You can see this by deactivating you indexes and browsing to a page and try to edit it

- Current: 
![image](https://user-images.githubusercontent.com/37185433/231304134-ea4174d0-1e90-4a81-9d4d-22c0d0731795.png)

- Expected
![image](https://user-images.githubusercontent.com/37185433/231304021-241181ba-f89f-444d-8d4a-6e6411a6a4ef.png)

- Current: not loading page 
![image](https://user-images.githubusercontent.com/37185433/231515509-4021e94c-a397-4be2-b811-6fcfa5091d04.png)

- Expected:
![image](https://user-images.githubusercontent.com/37185433/231515319-2e93371e-0ce0-45d3-b0fb-4da2911a0b6f.png)

### Steps
- Go to `Maintenance` 
- Deactivate Indexes 
![image](https://user-images.githubusercontent.com/37185433/231304370-ccf91bd2-8fd6-4d5c-a8ec-56c00ac9759c.png)
- Go to `Pages` portlet

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24606

**Comment by fmontes** [comment]
STR:

1. Desactivate both indexes (live and working)
2. Try to edit content any page
3. The page should load and just show a toast saying that the favorite was not loading
4. Edit page should work as normal

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_707fea3d_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1

![Screenshot 2023-05-08 at 8 58 31 AM](https://user-images.githubusercontent.com/129882031/236866947-aa61bbdc-3497-4799-9383-b33b9203e297.png)

Not able to load the Favorites page after the indexes are deactivated

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_707fea3d_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
