### ISSUE TITLE
Favorite Pages: The dropdown Share with should list users with backend role only

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24612]
### Parent Issue

#22343

### Problem Statement

When a favorite page is created, a frontend user can be selected from the list, even when this user cannot log in to the backend and access the page. For this reason, it makes sense to share favorite pages with users that have a backend role only.

### Steps to Reproduce

1. Create a user with only front-end role.
2. Log in as admin and go to the Favorite Pages portlet.
3. Open a page in Edit Mode and click on the star to create a favorite page for the page.
4. A modal is displayed. Open the dropdown list _Share with_ and you will see the user created in Step 1 listed.

### Acceptance Criteria

Users with frontend roles should be filtered out from the dropdown list _Share with_. Only backend roles should be listed.

### dotCMS Version

23.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
We are removing the Share With dropdown.
