### ISSUE TITLE
Favorite Page: Replace Share with dropdown with a multiselect group 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24611]
### Parent Issue
#22343 

### Task

As a user, I'd like to use a [primeNG multiselect group](https://primeng.org/multiselect) to improve usability when I select the user/role to share with a favorite page:
 
<img width="740" alt="Screen Shot 2023-04-11 at 10 37 51 PM" src="https://user-images.githubusercontent.com/8741395/231342853-e52d3f75-ec52-47b1-86d0-37d16d50bb6a.png">

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

The dropdown list _Share with_ is using a[ primeNG multiselect group](https://primeng.org/multiselect)

**Comment by fmontes** [comment]
Not applied anymore because #24742
