### ISSUE TITLE
[UI] Validate in Traffic Allocation the input need to be greater than 0 and max 100.

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24616]
### Parent Issue

[#22988](https://github.com/dotCMS/core/issues/22988)

### User Story

As a user, I want to ensure that the input value is between 1 and 100 so the allocation is accurately distributed.

### Acceptance Criteria

- The input field in the sidebar form should only accept values between 1 and 100.
- If the input value is less than 1 or greater than 100, an error message should be displayed.
- The allocation should be correctly distributed based on the input value.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Now the slider starts at 1 so all possible values are valid. 

<img width="615" alt="Screenshot 2023-04-18 at 9 38 48" src="https://user-images.githubusercontent.com/1576794/232829636-d93690a0-e995-465e-a9f5-f82f104be7cc.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
