### ISSUE TITLE
Block editor: Import image is not updating the reference

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24629]
## Parent
#21988 

## Problem Statement
Users can import images from external URLs using the "Import" button in our block editor. However, after importing, the image `src` is not getting updated to the `dotAsset` newly created contentlet.

## Steps to Reproduce
1. Open the block editor.
2. Add an image block using an external URL.
3. Click the "Import" button to download the image and create a piece of content in dotCMS.
4. Print the JSON object of the editor and see the image block is not referencing the new asset

## Acceptance Criteria
1. After user imports an image using the "Import" button, the image block `src` should update to the new contentlet
2. The imported image should be displayed correctly in the block editor, without any broken links or errors.
3. ~Show a message to the user to let them know that they need to save the contentlet to update the block field data.~ on chat with Jason we decided no.

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc
- [Slack conversation about the issue](https://dotcms.slack.com/archives/CQQMX585N/p1681406162048349)

## Assumptions & Initiation Needs
1. Users have proper access to dotCMS to import and create content.
2. The import functionality is working as expected, and the problem is only related to updating the image block reference.

## Quality Assurance Notes & Workarounds
- Ensure that the image block reference update does not cause any side effects or issues with other features in the block editor.
- Test the solution with various image formats and sizes to ensure compatibility and performance.
- Monitor any reported issues related to image import or the block editor after implementing the fix.

**Comment by fmontes** [comment]
Question... we can update the image block reference but somehow we need to force the save.

**Comment by zJaaal** [comment]
After importing the image if you make changes to the properties and hit apply, you can see the import button is appearing again. 

https://user-images.githubusercontent.com/63567962/235767027-3a321aa2-a9f2-4cbb-a625-dfadb5105045.mov

**Comment by fmontes** [comment]
Note to QA: this is very old and is was already shipped, please double check.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_e66ec4d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
