### ISSUE TITLE
UI - Favorite Page: Add Pages portlet to Main menu

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24636]
### Parent Issue

#22343 

### User Story

As an user I need that the link to access the PAGES portlet to be shown on the main menu 

### Acceptance Criteria

- PAGES portlet needs to be shown on the main menu inside the "Site" category
- it needs to be added for empty and full starter

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by rjvelazco** [comment]
## Failed Internal QA.

**Docker Image**: [`dotcms/dotcms:23.06_21c1c10b_SNAPSHOT`].
**Empty Starter Tag**: [`empty_20230509`].
**Full Starter Tag**: [Not Found].

It's working on the Empty Starter Tag:

<img width="1630" alt="Screenshot 2023-05-12 at 12 04 55 PM" src="https://github.com/dotCMS/core/assets/72418962/b5ef4702-d868-4eda-8a1a-6191188fffaa">

However, No new `Full Starter` Tag was generated. You can see the `starter` tags here: [https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/](https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/). The las full starter image was generated on January 12, 2023.

**Comment by fmontes** [comment]
Updated full starter 1

**Comment by fmontes** [comment]
New starter:


```“CUSTOM_STARTER_URL”: ‘https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20230518/starter-20230518.zip’```

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `dotcms:23.06_4907a0b3_SNAPSHOT`

The Full Starter has the **Site > Pages** portlet now.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_e6619ec9_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

CUSTOM_STARTER_URL: "https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20230518/starter-20230518.zip"
