### ISSUE TITLE
[UI] Disabled delete icon when Experiment is different from Draft.

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24651]
### Parent Issue
#24343

### User Story
As a user, I want the delete icon to be disabled when the Experiment is not in Draft state at the Goal level, so that I don't accidentally delete a goal of a non-draft Experiment.

### Acceptance Criteria
- The delete icon is disabled when the Experiment is not in Draft state at Goal level.
- The delete icon is enabled only when the Experiment is in Draft state at Goal level.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
None

### Assumptions & Initiation Needs
None

### Quality Assurance Notes & Workarounds
None

### Sub-Tasks & Estimates

**Comment by freddyucv** [comment]
**Pass Internal QA**: Not the Goal delete button is disabled when the Experiment is Running or Ended

**Comment by bryanboza** [comment]
Fixed, tested on release 23.06 // Docker // FF
