### ISSUE TITLE
UI Problems with dotCMS Site Browser and Containers Portlets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24654]
### Problem Statement
In dotCMS, the Site Browser and Containers portlets have UI problems, specifically the topbar needs to add 16px in the top margin.

### Steps to Reproduce
1. Login to dotCMS
2. Go to the Site Browser and Containers portlets
3. Observe the UI of the topbar

### Acceptance Criteria
1. The topbar of the Site Browser and Containers portlets should have 16px in the top margin.
2. The UI should be checked for any other issues.

### Assumptions & Initiation Needs
- No additional resources are needed.
- Assume that the topbar of the Site Browser and Containers portlets currently does not have 16px in the top margin.

### Quality Assurance Notes & Workarounds
1. Check the UI of the topbar of the Site Browser and Containers portlets to ensure that it has 16px in the top margin.

**Comment by fmontes** [comment]
@zJaaal found even more screens with this problem, check here: https://github.com/dotCMS/core/pull/24655#issue-1671642993

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.05_14850342_SNAPSHOT** // Docker // macOS 13.0 // FF v111.0

Time Machine 
![Screenshot 2023-04-19 at 9 30 51 AM](https://user-images.githubusercontent.com/129882031/233127026-1be7f34f-4ab2-45eb-b945-f2a3da05da38.png)

And now that we are here, we could give this a bit of spacing and alignment as well.
![Screenshot 2023-04-19 at 9 33 48 AM](https://user-images.githubusercontent.com/129882031/233127231-1693c6b5-0c77-4e4f-a336-3a4a047c4f09.png)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
