### ISSUE TITLE
Remove Slash Character in Block Editor Field

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24674]
### Problem Statement

When using the block editor in dotCMS and attempting to add new content by clicking the "+" button, an automatic "/" character is added to the field. If the user then decides to close the menu by pressing the "escape" key, the slash character is not removed from the field.

This is avoiding to show the "+" button again when you click in the editor

### Steps to Reproduce

- Login as admin 
- Open the dotCMS Block Editor.
- Click on any field to add content.
- Notice a "/" character automatically appears in the field.
- Use the "escape" key to close the menu.
- Notice the slash character remains in the field.

### Acceptance Criteria

- When using the block editor in dotCMS, clicking the "+" button to add content will not add a "/" character to the field.
- If the user decides to close the menu by pressing the "escape" key, any previously added "/" character will be removed from the field.
- The user should be able to continue adding content without any interference from the removed slash.

### dotCMS Version

Tested on release-23.05 // Docker FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 4 - Trivial

**Comment by rjvelazco** [comment]
### Passed Internal QA

Docker image: [`dotcms/dotcms:master_4f314e4`]

https://github.com/dotCMS/core/assets/72418962/1f99b77a-4e80-4083-a855-4da89467ec6d

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_df40f48_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
