### ISSUE TITLE
Losing table data when reordering in block editor field

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24677]
### Problem Statement

As a dotCMS user, I am experiencing a bug where I lose table data when I try to reorder the table by dragging and dropping in the block editor field.

https://user-images.githubusercontent.com/2641437/232914457-8cb493a6-3ec8-478b-a14d-f3723d175d2d.mov

### Steps to Reproduce

- Log in to dotCMS.
- Navigate to a content type that includes a block editor field containing a table with data.
- Try to reorder the table by dragging and dropping a row.

### Acceptance Criteria

- When I drag and drop the table row, the data in the row should not disappear or become corrupted.
- The reordered table should contain all the original data.

### dotCMS Version

Tested on release-23-05 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
This is happening in demo and is related to a library extension issue, is a know issue that in order for us to fix we need to either hack something or fork the table block from prosemirror and fix it there because tiptap said they will not fix it.
