### ISSUE TITLE
Unable to Reorder Contents Editing a Page

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24678]
### Problem Statement

As a content editor, I am unable to reorder contents while editing a page. When I try to drag and drop contents, it doesn't work and I receive an error in the JS console.

![image](https://user-images.githubusercontent.com/2641437/232915946-aaf6d005-3432-45ee-951c-6381c5ba4e2b.png)

### Steps to Reproduce

- Login to dotCMS as a content editor.
- Navigate to a page that has contents.
- Click on "Edit Page" to open the page in edit mode
- Try to drag and drop any content to reorder it.

### Acceptance Criteria

- Content editors should be able to easily reorder contents while editing a page.
- Contents should be reordered on the page based on the order set in the contents editor.
- No errors should be displayed in the JS console while reordering contents.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
