### ISSUE TITLE
Starter update - Activities URL field should be unique

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24673]
### Parent Issue

#23225 

### Problem Statement

As a content contributor, we need to ensure that the URL title field is unique in the starter site. Currently, this field is not set as required, which leads to issues when attempting to edit or update activity for a specific page. Without a unique URL title, it is impossible to match content and corresponding activity, making it difficult to display the correct information.

https://user-images.githubusercontent.com/2641437/232883180-2e10cc95-901d-4388-b417-31e47b6b2daa.mov

### Steps to Reproduce

- Login as admin 
- Open the index page 
- Attempt to edit or update activity for a specific page in the starter site.
- Notice that the corresponding activity is not displayed correctly due to the lack of a unique URL title field.

### Acceptance Criteria

URL title fields in the starter site must be unique and set as required.
It should be possible to edit or update activity for a specific page and have the corresponding activity displayed correctly.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Looks like this is just an update in the starter

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/assets/751424/22acbfc7-fb44-499c-9e17-4db058526c56

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_e66ec4d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
