### ISSUE TITLE
[UI] Show Report Icon at Experiments List when the experiment has status ENDED

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24670]
### User Story
As a user, I want to see a report icon at the Experiments List when the experiment has status ENDED, so I can quickly  view their reports.

### Acceptance Criteria

- The report icon is next to the modified experiment column in the Experiments List.
- The report icon is only displayed for experiments with ENDED/RUNNING status.
- Clicking on the report icon go to the report for the corresponding experiment.

### dotCMS Version
master

### Proposed Objective
Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Report Icon showing on both Ended and Running.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
