### ISSUE TITLE
Contentlets are remove  from an Variant Version Page

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24688]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When try to render a Page Inside an Variant for no Default Persona the Contentlet are gone.

### Steps to Reproduce

- Start dotCMS up with the full starter
- Create an Experiment using the index Page.
- Add a new variant and add a Contentlet to the Page into the Variant.
- Add a Goal set the split to 99% for the no Default Variant, to make sure that you are going to be inside this Variant.
- Start the Experiment.
- Log out and close the tab.
- Add a new tab and go to the index Page.
- You can see that the URL was redirect to .../index?variantname=...&redirect=true
- Change the Persona and all the Content is gone

I think is happend even when you remove a Contentlet from the Page inside the Variant

### Acceptance Criteria

- The Contentlet must not be remove for the no Default Persona inside a variant.

### dotCMS Version

lastes in Master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: working as expected when changing Persona on a variant of a page.

**Comment by bryanboza** [comment]
Fixed, now the variant contents still present after you change the persona.
