### ISSUE TITLE
Copy button on Page Edit portlet should copy the entire URL, not just the path

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#24683]
### Problem Statement

Previously (tested in 5.3.8) this button had a different icon and copied the full URL, now it only copies the path. This is not very useful, and it should still copy the entire URL.

The button is also labelled 'Copy URL' and thus should copy the full URL.

### Steps to Reproduce

1. Open a page in dotCMS
2. Press the Copy URL button
![Screenshot 2023-04-19 at 10 51 23 AM](https://user-images.githubusercontent.com/78741732/233114515-08038fb7-698e-4451-9626-f7393a5b0a11.png)
3. Paste the URL, it will only be the path

### Acceptance Criteria

The button should copy the full URL

### dotCMS Version

Latest, 23.01

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved QA** - Tested on ** master_93b8698d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
