### ISSUE TITLE
Set max_length for goal name on experiment

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24692]
### Problem Statement

As a dotCMS user, I need a max_length value to be set for the goal name on experiment, as currently there is no limit to the length of the text, which leads to UI issues when adding really long names. Additionally, a postman test for the endpoint needs to be included.

![image](https://user-images.githubusercontent.com/2641437/233185115-6520d458-1e27-49c3-ba98-0b164a15636a.png)

### Steps to Reproduce

- Login to dotCMS and navigate to the experiments module.
- Create a new experiment by adding a long name for the goal in the field provided.
- Observe that the UI breaks due to the long length of the text.

### Acceptance Criteria

- The goal name field on experiments should have a max_length value set to avoid breaking the UI due to long text input.
- The length of the goal name should be limited to a reasonable amount, such as 50 characters.
- A postman test for the endpoint that includes the max_length validation should be included.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Quality Assurance

### Assumptions & Initiation Needs

- The max_length value to be set for the goal name field needs to be specified by the product team.

### Quality Assurance Notes & Workarounds

- QA should validate that the max_length value set for the goal name field is working as expected and the UI is not breaking.

**Comment by oidacra** [comment]
@bryanboza what is the `max_length` expected? @dsilvam

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24757

**Comment by dsilvam** [comment]
Passed Internal QA: 50 limit working as expected.

**Comment by bryanboza** [comment]
Fixed tested on master // Docker // FF
