### ISSUE TITLE
Cannot push publish to S3 buckets in the us-east-2 region

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#24698]
### Problem Statement

When you attempt to push publish to S3 buckets in us-east-2/eu-central-1 you get a return of '400 bad request'. This appears to occur in the deprecated function 'doesBucketExist'. 

AWS logs show this as a malformed authorization header. 

According to cloud this could be due to a couple of reasons
1. us-east-2/eu-central-1 is the only US region that supports Signature Version 4 only (does not support both Version 2 and Version 4), this seems the most likely cause since it's claiming our header is malformed. 
2. We might not be using region specific endpoints

### Steps to Reproduce

1. Create an S3 bucket in the us-east-2 region/eu-central-1
2. Configure PP to push to that bucket
3. Attempt to push to the bucket
4. Get a 400 bad request.

### Acceptance Criteria

You should be able to push to buckets in all AWS regions. Let's test against:

- [x] eu-central-1
- [x] eu-west-1
- [x] us-east-1
- [x] us-east-2
- [x] us-west-1
- [x] us-west-2
- [x] ca-central-1

### dotCMS Version

23.03, 23.01

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

Update the doesBucketExist call to use doesBucketExistV2

**Comment by swicken-dotcms** [comment]
This is not stale

**Comment by wezell** [comment]
#22449 did not fix the issue?

**Comment by swicken-dotcms** [comment]
@wezell no it did not

https://dotcms.zendesk.com/agent/tickets/114366 ticket on 23.10.24

**Comment by dsolistorres** [comment]
Internal QA passed: bundle successfully was push published to S3 bucket in us-east-2 region

![image](https://github.com/dotCMS/core/assets/2894221/7c20abad-b251-45c1-bd8a-a3c06f365f07)

**Comment by bryanboza** [comment]
Fixed, tested on the last master and now it is working as expected
