### ISSUE TITLE
PP a folder with Archived Content Fails

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24705]
### Problem Statement

If you try to PP folder that contains archived content, if fails.

`Failed to publish because an error occurred: An error occurred when processing Workflow Task in '/data/shared/assets/bundles/01GYFRD81FZ8G699P9TDQ2H3MD/working/www.loans.com.au/1/422974622f905bcab3338eadf52e114e.contentworkflow.xml' with Title: webb-Nebula.png And ID '8ed7f3b2-db83-4adf-b447-826c4c021cc0': ERROR: insert or update on table "workflow_task" violates foreign key constraint "fk_workflow_task_asset" Detail: Key (webasset)=(422974622f905bcab3338eadf52e114e) is not present in table "identifier".{ "SQL": ["INSERT INTO workflow_task (id, creation_date, mod_date, due_date, created_by, assigned_to, belongs_to, title, description, status, webasset, language_id) values (?,?,?,?,?,?,?,?,?,?,?,?)"], "maxRows": [-1], "offest": [0], "params": [ "8ed7f3b2-db83-4adf-b447-826c4c021cc0", "2023-04-21 02:36:25.867", "2023-04-21 02:36:32.992", null, "7a2c45a2-4496-488b-a16a-58af39c716b8", "7a2c45a2-4496-488b-a16a-58af39c716b8", null, "webb-Nebula.png", "", "d6b095b6-b65f-4bdb-bbfd-701d663dfee2", "422974622f905bcab3338eadf52e114e", 1 ] }`

### Steps to Reproduce

1- Configure PP.
2- Create a folder in the sender.
3- Upload 2 files to the created folder.
4- Archive one of the files.
5- PP the whole folder.
6- Get the error.

### Acceptance Criteria

We should be able to PP folder with files whichever state they are.

### dotCMS Version

23.01.2 LTS

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111095

### Quality Assurance Notes & Workarounds

As a workaround since the content is already archived probably won't be needed anymore, so delete it and try again to PP the folder.

**Comment by dsolistorres** [comment]
This issue is fixed in a PR that was created for a related issue.

PR: https://github.com/dotCMS/core/pull/25180

Related issue:
https://github.com/dotCMS/core/issues/25044

**Comment by erickgonzalez** [comment]
If another customer hit this after the upgrade to the LTS, we should remove the FK, that no longer exist in the current version and was a problem of development.

UT to remove was created in 4.2.2 but was removed from postgres.sql until 5.1.6.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
