### ISSUE TITLE
Edit Page: The content is not saved when the iframe is quickly closed

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#24709]
### Parent Issue

- N/A

### Problem Statement

When creating a new `contentlet` using the `dot palette`, if the `iframe` is closed too fast or the internet is slow. The content is not saved in the page and the following error is obtained in the console.

#### Error
<img width="454" alt="console-error--on-page-editing" src="https://user-images.githubusercontent.com/72418962/233492627-de85611d-038d-4473-b2f4-4e535c5a7914.png">

### Steps to Reproduce

To reproduce this `issue` quickly, go to the `Network` tab in the Developer Tools and set the internet connection as `Slow 3G`.

1. Go to Page.
2. Drag a Content-Type from the Pallete and Drop it in a container.
3. Create a new Contentlet
4. Save or Publish.
5. Close the iframe.
6. See the error.

https://user-images.githubusercontent.com/72418962/233489231-69ca261a-ee2d-46d5-9fe1-b4babf67c6eb.mov

### Acceptance Criteria

-  When the content is saved and the user is allowed to close the iframe, the content should not be lost.

### dotCMS Version

`master`

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- N/A

### Assumptions & Initiation Needs

When you try to add something from the content pallet, we use a `placeholder` to determine the position where that content should be added. It is very possible that by closing the `iframe` right after saving the content, we are removing the `placeholder` from the `DOM`, and when we try to replace the `placeholder` with the `contentlet`, having removed it before, it throws the error.

### Quality Assurance Notes & Workarounds

To test this issue, make sure to slow down your internet connection, you can set it as `slow 3G` in the `Network` tab of the developer tools.

**Comment by fmontes** [comment]
We take care of this in edit contrent
