### ISSUE TITLE
Fix Undo/Redo Issues in Block Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24716]
### Problem Statement
In the block editor, when a user hits ctrl+z to undo an action, it does not work as expected because the updateChartCount add entries to this history on every keystroke.

### Steps to Reproduce
1. Navigate to the block editor 
2. Type some words
3. Hit ctrl+z to undo the change

### Acceptance Criteria
1. We need to find a way to updateChartCount without adding steps to the ctrl+z history.
2. ctrl+z should work for text and words
3. The editor `isEmpty` should work correctly.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
Note to QA:

1. The command Z is time based, means that the editor save data debounced
2. Make sure you check the editor empty, like when is required and is empty
3. Make sure it saves the information about char count etc in the DB (use the API)
4. Tests languages and history that content is getting saved correctly.
5. Also tests that if you open a contentlet and the block editor is not touched but have content still saves correctly.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_ea5adb9f_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS
