### ISSUE TITLE
Avoid Drag and Drop of Any Object in Edit Mode

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24727]
### Problem Statement

As a dotCMS user, I want to avoid the ability to drag and drop any object as content in edit mode to prevent a console error. Currently, the system allows users to drag and drop any objects into the content area during edit mode, causing the system to try to add the item as content. This action results in a console error, and the item is never added, resulting in an incomplete action.

Same thing if you try to remove the added item. 

https://user-images.githubusercontent.com/2641437/234070464-3e81e3f5-22b6-4d37-a0be-81905a310620.mov

### Steps to Reproduce

- Open dotCMS and log in
- Navigate to the Site Browser of the dotCMS backend.
- Add a new page
- Edit the created page and go to Edit mode.
- Attempt to drag and drop any object into the content area.

### Acceptance Criteria

- When in Edit mode, users should not be able to drag and drop any object into the content area.
- The system should not throw a console error when attempting to drag and drop an item in Edit mode.
- The user should receive a clear message indicating that the action is not possible.

### dotCMS Version

Tested on release-23.05 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
We need to check here in the dropzone that what is getting drop is actually a contentlet, widget or form.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_e66ec4d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
