### ISSUE TITLE
dotCMS CLI: Implement endpoint to push files to dotCMS

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24738]
### Parent Issue

#24753

### User Story

As a user, I'd like to have an endpoint to push files from my local environment to dotCMS using the CLI. This endpoint should: 

- Create any nested folders needed in dotCMS
- Receive an optional desiredState parameter with values: live or working (live by default if not specified)
- Also, it should receive an optional language (defaults to default language, if not specified)
- If a file is archived, we should unarchive/publish it

### Acceptance Criteria

The endpoint should support these operations: 

- [ ] Create any nested folders needed in dotCMS
- [ ] Receive an optional desiredState parameter with values: live or working (live by default if not specified) and save the files considering this status
- [ ] Also, it should receive an optional language (defaults to default language, if not specified)
- [ ] If a file is archived, we should unarchive/publish it
- [ ] Make sure zero length files can be pushed. Related to #24042

Besides, tests should be implemented accordingly.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dcolina** [comment]
Internal QA: PASSED.

Related to #24740
