### ISSUE TITLE
Favorites can get into an unrecoverable state

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24735]
### Problem Statement

Not sure how I did this but I have 2 favorites that no longer work.  That is fine - we show the skeleton and it looks ok.   The problem is that I am unable to edit or delete the favorite even though I am a CMS_ADMIN.

https://user-images.githubusercontent.com/934364/234127754-fe1f6dad-8204-4e4c-961b-34a596805e3d.mov

The call to the "Actions" endpoint fails with a 404 and the call to the _checkPermissions fails with a 404.  As a CMS Admin, I should be able to edit any content object.

### Steps to Reproduce

Not sure.

### Acceptance Criteria

CMS admin should always be able to edit a favorite

### dotCMS Version

23.06

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
We might fix this here: https://github.com/dotCMS/core/issues/24438

**Comment by fmontes** [comment]
Not needed.
