### ISSUE TITLE
[UI] Allow default and two variants

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24748]
### Parent Issue
#24343

### User Story
Revert #24456.  allow again two variants. 

### Acceptance Criteria
In the experiment creation, allow the default and two variants. 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: Allowing two variants + default and properly redirecting.

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
