### ISSUE TITLE
Favorite pages: Remove the `Share with` dropdown

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24742]
### Parent Issue

#22343 

### User Story

As a stakeholder I want to simplify this feature to release ASAP.

We are removing the "Share with" dropdown and user will be able to create favorites only for themselves for now.

### Acceptance Criteria

1. Remove the `Share With` dropdown
2. Make sure clean up everything including testing, services, store and state related to this
3. Add `+owner:dotcms.org.2795` to the favorite pages list query (in the portlet)
4. Add `+owner:dotcms.org.2795` to the query to get the "start" in the edit page

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24751

**Comment by rjvelazco** [comment]
## Passed Internal QA

The dropdown menu has been removed.

**Docker Image**: [`dotcms/dotcms:master_3b0b1cfc`]

![Image](https://user-images.githubusercontent.com/72418962/235947680-137a74e0-61dd-4293-9406-55967d9f7dd4.png)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_707fea3d_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
