### ISSUE TITLE
dotCMS CLI: Implement files push command

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24740]
### Parent Issue

#24732

### User Story

As a user, I'd like to execute the `files push` command to upload file(s) or/and folder(s) from my local machine to a remote server (dotCMS) by specifying the location of the local directory or file.

Examples: 
```console
files push /cli/project/workspace/path --dry-run
files push /cli/project/workspace/path
files push /cli/project/workspace/path/files/live/es-es/demo.dotcms.com
files push /cli/project/workspace/path/files/live/en-us/demo.dotcms.com/images
files push /cli/project/workspace/path/files/live/en-us/demo.dotcms.com/images --dry-run
files push /cli/project/workspace/path/files/live/en-us/demo.dotcms.com/application/themes/landing-page/header.vtl
```

This command should consume the endpoint implemented here: #24738

### Acceptance Criteria

- [ ] The "push" operation should allow the user to upload file(s) or/and folder(s) from their local machine to dotCMS.
- [ ] The user should be able to preview changes that would be made on the remote server without applying them through the "--dry-run" option.
- [ ] The "push" operation should display appropriate progress messages as the file(s) or/and folder(s) are uploaded.
- [ ] If a file is archived, we should unarchive/publish it
- [ ] Make sure zero length files can be pushed. Related to #24042
- [ ] Implement tests accordingly

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dcolina** [comment]
Note: I have noticed that some actions have changed in definition, so it would be good to update the user history to avoid confusion.

This can be checked by looking at the result of the. `files push --help` command 

Otherwise, the task meets each of the requirements specified in the acceptance criteria.

Internal QA: PASSED.
