### ISSUE TITLE
[UI] Change endpoint of promote winner

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24764]
### User Story
As a user, I want to promote a variant as default.

### Acceptance Criteria
- Show if a variant is already promoted
- Show the winner if exist
- Can promote N times the variants
- Show a successful message of the promoted variant
- Update the Report UI with the promoted variant

### dotCMS Version
master

### Proposed Objective
Promote the selected variant

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The button to call the dialog already exist.

### Sub-Tasks & Estimates
- [x] Change endpoint
- [x] Finish implementation of UI
- [X] Saving State

**Comment by dsilvam** [comment]
Update of the functionality: Promoting a variant now ends the Experiment, thus it is not possible to promote more than once.

**Comment by bryanboza** [comment]
Fixed, now we are able to promote a winner and this is working as expected. 

Tested on master // docker // FF
