### ISSUE TITLE
Favorites Pages: Fix Incorrect URLContentPage Title When Adding 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24761]
### Problem Statement
When adding a URLContentPage to favorites, the title is not correct and instead displays the title of the detail page instead of the content. 

### Steps to Reproduce
1. Edit a blog post page
2. Add the page to fav
3. See the page is "Blog Details"

### Acceptance Criteria
- The title of the URLContentPage page when added to favorites should be the title of the content and not the title of the detail page.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
- Quality Assurance should verify the title of the URLContentPage is correct when added to favorites. 
- There is no workaround for this issue.

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image**: [`dotcms/dotcms:master_3b0b1cfc`]



https://user-images.githubusercontent.com/72418962/235951390-8e44072c-97c8-4e7c-8b02-e690094d0a5f.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_9dc362cb_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
