### ISSUE TITLE
Test upgrade from LTS to release

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24774]
### Problem Statement

As part of the release process, we need to make sure we'll be able to upgrade the instance from a LTS to the last version of the release 

### Steps to Reproduce

- Test using Postgres as DB
- Made a smoke test over the basic functionality 

### Acceptance Criteria

We need to be able to upgrade without problems. 

### dotCMS Version

Release-23.05 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by josemejias11** [comment]
**QA Comment**

Upgrade task completed 

**Log:**  
[catalina.out.zip](https://github.com/dotCMS/core/files/11346808/catalina.out.zip)
