### ISSUE TITLE
LogViewer connection times out.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#24775]
### Problem Statement

The log viewer disconnects when the load balancer times out. 
The old implementation used a servlet to feed the front end and used a keep-alive strategy sending a blank space every 20 seconds. That implementation got replaced by a much more modern Server-Sent Events approach. 
However, we still need to keep the connection alive 

### Steps to Reproduce

since this is happening behind an LB reproducing the original problem has implications,
But apparently, 
Firefox offers an option to simulate a time-out setting the value of `network.http.connection-timeout` in `about:config`

### Acceptance Criteria

The log viewer should remain connected and functional even after long periods of inactivity

### dotCMS Version

23.01

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

The keepAlive response is sent to the browser


![Image](https://user-images.githubusercontent.com/8741395/236952782-b5eb8c86-cbc7-40a0-9612-e25a4bc0477d.png)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_fd9a1256_SNAPSHOT** // Docker // macOS 13.0 // FF v112.0.1
