### ISSUE TITLE
Allow configuration of default folders for site/folder and image fields by role/user

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#24779]
### User Story

As a user Io want to be able to specify default folders for image fields and for the site/folder on a per role/user basis. Right now, in the event that a user does not have access to the default folder on the field they are sent to the root. 

### Acceptance Criteria

- Ability to configure default fields per user/role
- Simple UI to manage this

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Relative corner case that we don't expect to be high enough priority to address.

**Comment by weiyiwang-dotcms** [comment]
Another customer with the same request here:

https://dotcms.freshdesk.com/a/tickets/28386

**Comment by weiyiwang-dotcms** [comment]
Another request for this feature on this ticket: 28386
