### ISSUE TITLE
Block Editor Crash when the Same Contentlet is Added

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24797]
### Problem Statement
When an user attempts to add the same contentlet into the editor, the block editor crashes. 

### Steps to Reproduce
1. Open the dotCMS block editor
2. Attempt to insert the same contentlet into the editor

### Acceptance Criteria
1. Update the query so it will not allow the same contentlet to be inserted
2. Ensure that the block editor will not crash when the same contentlet is added

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** [`dotcms/dotcms:master_e68255c5`]


https://github.com/dotCMS/core/assets/72418962/2be1bde6-ec77-4b93-95d7-175f05a73ea1

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_3d7a559_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
