### ISSUE TITLE
Fix Favorite Pages Query for Current User

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24798]
### Problem Statement
In the favorite pages, the user is not seeing the pages added to favorite because in the query, we are hardcoding a user ID. 

### Steps to Reproduce
1. Login to dotCMS
2. Add a page to favorite
2. Go to favorite pages
3. Check if page added to favorite is displaying

### Acceptance Criteria
We need to make sure that in the query we add the current user ID.

### External Links 
N/A

### Assumptions & Initiation Needs
- Assumption: dotCMS is properly configured
- Initiation Need: dotCMS source code

### Quality Assurance Notes & Workarounds
- Quality Assurance Note: Test the query with different user IDs to make sure that the query works properly
- Workaround: N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image**: [`dotcms/dotcms:master_3b0b1cfc`]



https://user-images.githubusercontent.com/72418962/235961671-7295a562-7197-4b5d-95dd-733560b4215d.mov

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_a44c4a30_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
