### ISSUE TITLE
Labels - was Tagagories

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24794]
Right now, Categories and Tags have some mutually exclusive features:

- Categories:

    - Separated into "groups" \(top\-level Categories\)\.

    - Hierarchical\.

    - Pre\-defined\.

        - Content contributors can not add new categories, which provides important control to content architects\.

    - Different labels \(Categories\) can be shown on different content types\.

    - Multiple different labels can be shown on a single content type\.

- Tags:

    - User\-addable\.

    - Easy to add \(get tag suggestions as\-you\-type\)\.

    - Easy to query \(e\.g\. `+tags:$value`\)\.

    - Used with personalization \(Visitor object tag counts, personalized content pulls\)\.

We need to create some kind of taxonomy that combines some of these features, to allow things like:

- Tags with hierarchy \(or at least grouping\)\.

    - For example, tags which are "grouped" into categories \(like Color, Style, etc\.\)\.

- Tags which apply only to certain content types\.

    - So, for example, product\-related tags don't show up in tag suggestions when editing employee content items\.

- Categories which affect personalization\.

Ideally, the resulting changes should allow creation of the equivalent of both existing Tags and existing Categories in the new thing\. So, for example, you could duplicate the functionality of either Tags or Categories with a single taxonomy, by just changing the configuration or options of it\.

Technical Approach

There are 3 basic options:

1. Add tag features to Categories

- e\.g\., Allow users to dynamically add categories, search for and select categories as\-you\-type, simplified queries, category tags for personalization

1. Add hierarchy and grouping of some kind to Tags

- e\.g\., Separate tags by content type \(or maybe assign Tags to Categories\), allow specification of a tag group, etc\.

1. Create some new taxonomy \(e\.g\. "Tagegories"\) which combine features of both\.

Option 1 may be the best choice, but it will likely depend on implementation details\.

Note: Categories are also Permissionable\. This isn't a necessity for what this card is about, but it's a very nice feature, so makes using Categories as a starting point an even better option, if that could work\.

<p></p>

**Comment by wezell** [comment]
Link to feature: https://dotcms.productboard.com/feature-board/planning/features/12019885

**Comment by swicken-dotcms** [comment]
Commenting as this is not stale

**Comment by prestonso** [comment]
Closing as we're accounting for this work in an epic (Taxonomy Labels).
