### ISSUE TITLE
Workflow: Fix individual permissions

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#24801]
### Parent Issue
N/A

### User Story

When a limited user uses the individual permissions on a fire action, it throws an exception even if the content type has owner role with edit permission checked.

### Acceptance Criteria

- [ ] Allow limited users to publish content with a specific role
- [ ] Have to create an integration test broken to reproduce the case and once, the unit test is done, fix it

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/24645
https://github.com/dotCMS/core/issues/24817

**Comment by jdotcms** [comment]
STP:
1) create a content type with a CMS OWNER full (EDIT PERMISSION checked)
2) Run the following curl using limited user credentials
curl --location --request PUT 'http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--header 'Cookie: access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3MTgxNjdjOC1jN2ZmLTQyYzAtOWY1MC1mMjdlMjI4NWU2ZTMiLCJ4bW9kIjoxNjgyOTY5Mzc2MDAxLCJzdWIiOiJkb3RjbXMub3JnLjEiLCJpYXQiOjE2ODI5NjkzNzYsImlzcyI6ImQ0NTk1MTg2MGQiLCJleHAiOjE2ODMwNTU3NzZ9.sbS4FnjfBiWjoq8JbxfW2p4JlcsQwUQ9Dal4Mcj7wTI' \
--data '{
    "contentlet":{
        "identifier":"1b2b25b6ea0e4fbb5806e2e0865be9d5",
        "contentType":"webPageContent",
        "title":"Test3-11",
        "contentHost":"default",
        "body":"Test body"
    },
    "individualPermissions": {
        "READ":["CMS Owner"],
        "WRITE":["CMS Owner"],
        "PUBLISH":["CMS Owner"],
        "EDIT_PERMISSIONS":["CMS Owner"]
    }
}'

**Comment by jdotcms** [comment]
The result should be a contentlet created by the limited user with full permissions

**Comment by jdotcms** [comment]
[Feedback PR](https://github.com/dotCMS/core/pull/24997)

**Comment by bryanboza** [comment]
Foxed, tested on release-23.01 // Docker // FF
