### ISSUE TITLE
Favorites pages: Add the role key when create a new fav

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24817]
### Parent Issue

#22343 

### User Story

As a user, I want to be able to have boomarks created just for me.

### Acceptance Criteria

- [ ] Add the CMS owner role key when the user saves a favorite
- [ ] User should only see their own created bookmarks

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

- [] #24801
- [] #24645

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_8b14ad11_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Failing Acceptance Criteria

1. User should only see their own created bookmarks


https://github.com/dotCMS/core/assets/129882031/6247794b-c264-4d28-9984-a22f6a09a70b

**Comment by fmontes** [comment]
Hi @josemejias11, this is expected, as admin and admin2 both have access to the content type that stores the favorite.

They should only see the ones they created in the bookmark panel, but on the content search, they will see everything they have access to.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.05_849e8a4c_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
