### ISSUE TITLE
NavTool method getNav must return only published links

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24829]
### Problem Statement

When `$navtool.getNav("$VTLSERVLET_URI")` method is called. It returns unpublished links as well.

### Steps to Reproduce

1. log in to [Demo Site](https://demo.dotcms.com/dotAdmin/#/public/login?r=1655383397360).
2. Go to Site->Browser portlet.
3. Create a folder named `test`
4. Create 2 links (one published and one unpublished), and select Show On Menu on both.
5. Create a page
6. Create a code snippet widget and add it to the page:
```
#set($list = $navtool.getNav("/test"))
#foreach($l in $list)
$l </br>
#end
```
7. Navigate to Live Mode
8. Unpublished link is shown.

### Acceptance Criteria

When $navtool.getNav is called only published items must appear in the result set.

### dotCMS Version

23.01.1, and demo.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111213

### Quality Assurance Notes & Workarounds

Workaround is to archive the link

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_94a8586_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by AndreyDotcms** [comment]
Please provide more info about why it was rejected. I tested it on Master and works as expected

**Comment by josemejias11** [comment]
Hey @AndreyDotcms,

Please just let me know what you find out after our second slack talk. Thanks!

**Comment by AndreyDotcms** [comment]
The fix for this issue can be reproduced in docker and locally. At the moment to reproduce the fix, the last image of master was: ` image: dotcms/dotcms:master_af34217_SNAPSHOT
`
https://github.com/dotCMS/core/assets/127987858/a9bd51b8-7357-4fb2-bdae-806bb3cb04e7

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_f961f46_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
