### ISSUE TITLE
Promoting a Variant on a running Experiment should end the Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24831]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As an Experiments User, I want an Experiment to be ended, if running, once I promote a Variant 

### Acceptance Criteria

* A running Experiment is ended when a Variant is promoted. 
* Postman tests. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, once that you promote the varian the experiment ends
