### ISSUE TITLE
Move the search field to the left in the content search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24834]
### User Story

As a stakeholder I want to move the content search to the left and make it closer to the global search in this screen.

### Acceptance Criteria

Move the search field to the and the toggle for list and card to the right of this.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by alfredo-dotcms** [comment]
LGTM!

![Image](https://github.com/dotCMS/core/assets/37185433/1e94d39c-c037-4f3b-924d-48e9572d977b)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_ce67386_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
