### ISSUE TITLE
Dependency Update : JSON Small and Fast Parser

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24849]
### Task

dotCMS is currently using
net.minidev/json-smart 2.3

2.4.9 from Mar 07, 2023 seems to be the smallest upgrade we could make that doesn't have reported security vulnerabilities

https://mvnrepository.com/artifact/net.minidev/json-smart

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by mbiuki** [comment]
@jcastro-dotcms any updates on this? Any PR for this ready to review?

**Comment by jcastro-dotcms** [comment]
@mbiuki not yet, I just started looking into this a few minutes ago.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_110141b**, Docker, macOS 13.0, FF v121.0.1
