### ISSUE TITLE
Dependency Update : XStream Core

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24845]
### Task

dotCMS is currently using
com.thoughtworks.xstream/xstream 1.4.8

All listed versions have reported issues.
https://mvnrepository.com/artifact/com.thoughtworks.xstream/xstream

@spbolton or @wezell how should we handle this?

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, sanity test pushing content through different servers and everything continue working as expected. 

Tested on master // Docker
