### ISSUE TITLE
Dependency Update : H2 Database Engine

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24846]
### Task

dotCMS is currently using
com.h2database/h2 1.3.176

All listed versions have reported issues.
https://mvnrepository.com/artifact/com.h2database/h2

Let's try with `2.1.214`

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Smoke test nothing breaks after the version upgrade. Keep an eye of the H2 Cache that is behaving fine.

**Comment by bryanboza** [comment]
Fixed, tested doing a sanity test over the maintenance tab cleaning caches and everything still working as expected, we can close this card for now.
