### ISSUE TITLE
Dependency Update : Jetty HTTP Client

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24848]
### Task

dotCMS is currently using
org.eclipse.jetty/jetty-client 8.1.14.v20131031

https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-client

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by mbiuki** [comment]
This looks like it is a transitive dependency. 
artifactId=jetty-client
groupId=org.eclipse.jetty
version=11.0.20
