### ISSUE TITLE
Update Starter & Demo SIte to Support SEO Metadata Fields under Page Properties by Default

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24856]
[![Screenshot_2023-05-08_14-44-48.png](https://mrkr.io/s/64590ae05d2af2f4d17a9e82/2)](https://mrkr.io/s/64590ae05d2af2f4d17a9e82/0)

### Acceptance Criteria

Change "SEO Title" to Page Title in Starter

Change "SEO Description" to Meta Description in Starter

Change "SEO Keywords" to Meta Keywords in Starter

Add "Include in Sitemap"

Add Dropdown for "Sitemap Importance" with values 0.0, 0.1, 0.2,... 1.0 

Add Datepicker for Last Update Date

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://moz.com/learn/seo/robots-meta-directives

Indexation-controlling parameters:

    Noindex: Tells a search engine not to index a page.

    Index: Tells a search engine to index a page. Note that you don’t need to add this meta tag; it’s the default.

    Follow: Even if the page isn’t indexed, the crawler should follow all the links on a page and pass equity to the linked pages.

    Nofollow: Tells a crawler not to follow any links on a page or pass along any link equity.

    Noimageindex: Tells a crawler not to index any images on a page.

    None: Equivalent to using both the noindex and nofollow tags simultaneously.

    Noarchive: Search engines should not show a cached link to this page on a SERP.

    Nocache: Same as noarchive, but only used by Internet Explorer and Firefox.

    Nosnippet: Tells a search engine not to show a snippet of this page (i.e. meta description) of this page on a SERP.

    Noodyp/noydir [OBSOLETE]: Prevents search engines from using a page’s DMOZ description as the SERP snippet for this page. However, DMOZ was retired in early 2017, making this tag obsolete.

    Unavailable_after: Search engines should no longer index this page after a particular date.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64590ae05d2af2f4d17a9e85_40c3983f001fc1e3?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 112.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
I know @fishsmith was working on this. Please check with him before starting.

**Comment by damen-dotcms** [comment]
Jason completed this!
