### ISSUE TITLE
Update Starter & Demo SIte to Support Sitemaps by Default

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24857]
Going to https://demo.dotcms.com/sitemap.xml gives a 404 error.

[![Screenshot_2023-05-08_14-45-41.png](https://mrkr.io/s/64590b15d80e39f8086ecbf1/2)](https://mrkr.io/s/64590b15d80e39f8086ecbf1/0)

### Problem Statement

By default, the sitemap should be located right under the top level domain. 

So like... mysite.com/sitemap.xml -- we need to set that up in the starter.

We also need the Sitemap.xml file to follow proper formatting 

### Acceptance Criteria

* Sitemap respects values like NoIndex and Importance, set under the page properties. (#24856)
* Sitemap is automatically updated.
* Sitemap uses proper XML formatting.
* Sitemap is located at /sitemap.xml

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* sitemaps.org - Protocol | https://www.sitemaps.org/protocol.html
* Build and Submit a Sitemap | Google Search Central  |  Documentation  |  Google for Developers | https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
* How to Create an XML Sitemap (and Submit It to Google) | https://ahrefs.com/blog/how-to-create-a-sitemap/

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://demo.dotcms.com/sitemap.xml](https://demo.dotcms.com/sitemap.xml)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64590b15d80e39f8086ecbf4_120aaa057d01475a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 112.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
I know @fishsmith was working on this. Please check with him before starting.
