### ISSUE TITLE
Dependency Update : TwelveMonkeys :: ImageIO :: Metadata

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24853]
### Task

dotCMS is currently using
com.twelvemonkeys.imageio/imageio-metadata 3.7.0

3.7.1 from Dec 11, 2021 seems to be the smallest upgrade we could make that doesn't have reported security vulnerabilities
	https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-metadata

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by mbiuki** [comment]
upgrade to 3.10.1?

**Comment by mbiuki** [comment]
We are at 3.10.1. Closing this ticket.
