### ISSUE TITLE
Dependency Update : Apache Commons Compress

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24854]
### Task

dotCMS is currently using
org.apache.commons/commons-compress 1.15

1.21 from Jul 12, 2021  seems to be the smallest upgrade we could make that doesn't have reported security vulnerabilities
	https://mvnrepository.com/artifact/org.apache.commons/commons-compress

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by mbiuki** [comment]
We are 1.26.0. Closing this ticket. Taken care of when we did Maven upgrade.
