### ISSUE TITLE
Dependency Update : SnakeYAML

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24850]
### Task

dotCMS is currently using
org.yaml/snakeyaml 1.30

2.0 from Feb 26, 2023 seems to be the smallest upgrade we could make that doesn't have reported security vulnerabilities

**NOTE: The SnakeYAML library was updated to version 2.2** 

https://mvnrepository.com/artifact/org.yaml/snakeyaml

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The best way to test this is to startup up dotCMS and make sure no errors related to YAML file handling are logged. Additionally, create and edit existing HTML Pages and their contents, and try to Push Publish them, even if you don't have a valid receiving environment.

**Comment by jdotcms** [comment]
I have started several times
created several pages and edit them
PP and so on 
Not any SnakeYML on the log or so

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_13c8dda**, Docker, macOS 13.0, FF v124.0.2
