### ISSUE TITLE
Add "Social Sharing" and "Search Engine Results Page" to the Preview Options

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24859]
[![Screenshot_2023-05-08_14-52-37.png](https://mrkr.io/s/64590cb5a1a32d1f61b4ced2/2)](https://mrkr.io/s/64590cb5a1a32d1f61b4ced2/0)

### Acceptance Criteria

For social, we should model it loosely after this.

https://socialsharepreview.com/

For SERP, we should model it loosely after this.

https://dnschecker.org/google-serp-preview-optimization-tool.php

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64590cb5a1a32d1f61b4ced5_54041aacd0dc4640?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 112.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
Closing as a dupe! (=
