### ISSUE TITLE
3 Dots menu es not working on Favorites Pages portlet

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#24861]
### Problem Statement

Currently the 3 Dot menu is not working when trying to edit a Favorites Page

### Steps to Reproduce

1. Go to https://localhost:8443/c
2. Add a page to favorites
3. Go to the Favorites page portlet
4. Try to click on the 3 dot menu

### Acceptance Criteria

3 Dots menu should be functional on the Favorites page portlet

### dotCMS Version

**master_707fea3d_SNAPSHOT**

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2023-05-08 at 9 18 06 AM](https://user-images.githubusercontent.com/129882031/236863538-5d2068a6-3a00-4b10-b8dd-33ad9f3108bf.png)

**Comment by zJaaal** [comment]
This bug was a side effect for another fix I made in this issue https://github.com/dotCMS/core/issues/24174. I'm working on it there, so I'll close this one in favor of that one
