### ISSUE TITLE
Favorite Pages: Update the edit content breadcrumb

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24879]
### Parent Issue

#22343 

### User Story

As a user I want to be able to browse back and forth between edit a page a the new page portlet.

### Acceptance Criteria

Update the breadcrumb to say: `Pages > Page Name` when editing a page.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by zJaaal** [comment]
### Notes for QA

To test this you need to be sure that you have` Pages Portlet` activated in your environment (should be activated by default on 23.06) and it should appear on the `Navigation Menu` under the `Site` section, also, if the `Pages Portlet` is not in the `Navigation Menu`, the breadcrumb should be the original one, it shouldn't change to the new one, the new one that redirects to `Pages Portlet`, only appears if the `Pages Portlet` is on the `Navigation Menu`.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `dotcms:23.06_4907a0b3_SNAPSHOT`
The system breadcrumb is displaying the appropriate links now. When clicking an HTML Page from the `Pages` portlet, it looks like this:

<img width="974" alt="from-pages" src="https://github.com/dotCMS/core/assets/8779585/da228f83-b8a5-4293-89fc-26ea8d235730">


When clicking it from the `Site` portlet, it looks like this:

<img width="823" alt="not-from-pages" src="https://github.com/dotCMS/core/assets/8779585/09bf6ea9-83f6-441e-a190-c939b17be6e2">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_e6619ec9_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
