### ISSUE TITLE
Postman and Unit global tests results not actual status

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24873]
### Parent Issue

https://github.com/dotCMS/core/issues/24867

### Problem Statement

Then a PR gets its different tests run, the global status of the results is not reflecting the actual results. 

Take a look at the following screen: 

<img width="851" alt="Screenshot 2023-05-08 at 13 49 53" src="https://user-images.githubusercontent.com/1576794/236920221-4f27ddaa-fec5-41a8-884c-979bf020af1e.png">

It's showing success for both Unit and Postman tests when in really the Unit didn't run and the Postman have at least 3 collections failing. 

### Steps to Reproduce

* Send a PR 
* Wait until tests run
* Check the global tests statuses 

### Acceptance Criteria

The global status reflected in the comment at PR level needs to reflect the actual tests results. 

<img width="851" alt="Screenshot 2023-05-08 at 13 49 53" src="https://user-images.githubusercontent.com/1576794/236920533-85bda4a2-4557-420e-8dab-9e244c886b1e.png">

### dotCMS Version

master / 23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by john-thomas-dotcms** [comment]
The acceptance criteria for this card is -
