### ISSUE TITLE
Listing Page - Save the users last search/state of the search box.  If a user has filtered for something, that is what they should come back to.

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24887]
Save the users last search/state of the search box. 
If a user has filtered for something, that is what they should come back to.

params to be saved:
- Keyword
- languageId
- archived

the params needs to be stored on session storage: session storage works like this
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by zJaaal** [comment]
### Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_d034bdf1_SNAPSHOT]`

### Screenshots
https://github.com/dotCMS/core/assets/63567962/31111c9b-abc6-4168-8051-5fd804dbca72

#### Session Storage

<img width="1512" alt="Screenshot 2023-05-17 at 3 01 19 PM" src="https://github.com/dotCMS/core/assets/63567962/0c699422-1899-44e0-8b3a-348ccdde1364">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_4907a0b3_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
