### ISSUE TITLE
There is no way to configure WYSIWYG to use the virtual path of an image when inserting one

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#24894]
### Problem Statement

When configuring `WYSIWYG_IMAGE_URL_PATTERN` you cannot configure it to just use the virtual path (the one seen in the browser). This used to be `WYSIWYG_IMAGE_URL_PATTERN={path}{name}` however the `getPath` method that populates the path was changed to use the /dA/ pathing. 

We need a way to get the classical path.

For example, if I put an image into the browser in `/images/image1.png` I currently have no way to have that be the path when I add the image to a WYSIWYG field. You can only configure the `/dA/` pathing. 

### Steps to Reproduce

1. Set `WYSIWYG_IMAGE_URL_PATTERN={path}{name}` in your configuration
2. Add an image to a WYSIWYG field
3. Check the code, you will see it has /dA/ pathing

### Acceptance Criteria

You need to be able to configure the WYSIWYG image insertion to use the classical file path

### dotCMS Version

Master
22.03

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by swicken-dotcms** [comment]
Second customer hitting this: https://dotcms.zendesk.com/agent/tickets/112037

**Comment by EdgarPsda** [comment]
Another customer for tracking this issue: https://dotcms.zendesk.com/agent/tickets/112609

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Here before set the property:
![Image](https://github.com/dotCMS/core/assets/2641437/899e0a81-596b-47b7-85dc-7bebdbc1adbf)

Here after set the property: 
![Image](https://github.com/dotCMS/core/assets/2641437/f354d5be-942f-420c-950f-fc2e5e9f011b)
