### ISSUE TITLE
Fix: Bayesian calculation in Goal to minimize a Metric 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24895]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

We have to type of Goal:

- Goal to minimize for Example Bounce Rate, when you have a Bounce Rate goal you want to minimize the amount of Bounce Rate for a specific page, so in this case each Bounce Rate is a fail.
- Goal to maximize for example Reach Page, when you have a Reach Page Goal you want to Maximixe the amount of times the a specific page is reach, so in this case is Reach Page is a Success.

Right now we are taking the amount from the Goal as a Success no matter the kind of Goal the it is, so in the case of we are taking the fail as success.

### Steps to Reproduce

- Create a Experiment, Add a Bounce Rate, a Variant, and 100% of traffic location.
- Start it.
- Go to the Front end to be assign inside the Experiment.
- Navigate into the Experiment's Page, and Close the Tab.
- Check the Experiment Result, You must have a Bounce Rate inside the Variant that you was assing, and this Variant is going to be the winner.

### Acceptance Criteria

The Winner must be the Variant with less Bounce Rate.

### dotCMS Version

latest in master

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dsilvam** [comment]
Needs work: It's counting properly when there is no bounces on the index page. There's an issue comparing between the received value and the expected value.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25112

**Comment by dsilvam** [comment]
Again needs work: It's counting bounces and non-bounces as non-bounces/conversions.

**Comment by freddyucv** [comment]
Fix here: https://github.com/dotCMS/core/pull/25254/commits/dfea43e740b5857fdd0b52a40fa83c5789876ee3

**Comment by dsilvam** [comment]
Passed Internal QA: counting properly bounces and non-bounces even on the index page.

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF 

Now it is working as expected on index page
