### ISSUE TITLE
Calculate credibility interval and risk for Bayesian implementation

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#24903]
### Parent Issue
#23625

### User Story
As a developer, I want to include a 95% credibility interval and risk calculation for AB Testing and ABC Testing in our Bayesian logic.

### Acceptance Criteria
- AB Testing and ABC Testing should include a 95% credibility interval and risk calculation.
- The Bayesian logic should be updated to include the new calculations.
- The new calculations should be tested thoroughly to ensure accuracy.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The current Bayesian logic is working correctly.
- There is no need to change the current workflow of AB and ABC Testing.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Research and implement 95% credibility interval and risk calculation for AB Testing - 3 hours
- Research and implement 95% credibility interval and risk calculation for ABC Testing - 3 hours
- Update Bayesian logic to include new calculations - 2 hours
- Test new calculations thoroughly - 4 hours

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24963

**Comment by dsilvam** [comment]
Passed Internal QA: Conversion rate range included.

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF
