### ISSUE TITLE
Lost ability to select system host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24908]
### Problem Statement

Seems like we broke this when we updated the system host field.  This is happening in 23.01 as well.

If a content type has a host / folder field that is NOT marked as required, you should be able to select the SYSTEM_HOST as a  valid option. This is especially important for vanity urls, where if they are on the SYSTEM_HOST, then they work for all hosts.

## Here is master/23.01
You can see that SYSTEM_HOST is not available below:
![Screen Shot 2023-05-10 at 5 35 00 PM](https://github.com/dotCMS/core/assets/934364/cd991413-6506-40b6-b934-2544060657f0)

## Here is 21.06
![Screen Shot 2023-05-10 at 6 01 52 PM](https://github.com/dotCMS/core/assets/934364/7a50592c-4ddb-422d-86c0-ae8d6412afac)

### Acceptance Criteria

If a content type's host/folder field is NOT required, you should be able to select the SYSTEM HOST.

### dotCMS Version

23.01 - 23.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_003371a4_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by bryanboza** [comment]
After those changes now always by default the site/folder field have "System host" pre-selected, and we are not respecting the site/folder field of the content type. 

https://github.com/dotCMS/core/assets/2641437/8388d5e6-ed25-415a-9483-a10cb4715a77

## Acceptance Criteria
- We need to select by default the same location that you have on the content type 
- Tests

**Comment by fmontes** [comment]
We can move on.

**Comment by bryanboza** [comment]
Fixed, this has been the behaviors for a long time ago.
