### ISSUE TITLE
Favorite Pages: The open/closed state of the favorites accordion should be remembered (local storage).  I close it, leave the page and come back and it is open again.

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#24911]
- The open/closed state of the favorites accordion should be remembered (local storage). I close it, leave the page and come back and it is open again

https://github.com/dotCMS/core/assets/37185433/4ea278ad-f76f-40b1-805c-464b791b3ef1

**Comment by fmontes** [comment]
We are storing the open/close bookmark in the local storage, so if you collapse and refresh the page it should stay collapse and vice versa.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_92c6837e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
