### ISSUE TITLE
Favorite Pages: Unable to create bookmark image for /members page

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24916]
### Parent Issue

#22343 

### Problem Statement

I am trying to create a bookmark for a page that does not have CMS_ANONYMOUS view on it and we cannot seem to get a thumbnail of it.

![Screen Shot 2023-05-11 at 1 45 01 PM](https://github.com/dotCMS/core/assets/934364/41de0dec-8254-4f1d-8a77-808f5e7a60e1)

### Steps to Reproduce

To reproduce:
- in edit mode, browse to "members only" page.
- try to make a bookmark for it.
- You will see the preview fail to generate.

### Acceptance Criteria

Be able to create a thumbnail for any page in the system.

### dotCMS Version

23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
It looks like the problem is with the way the theme loads the Google Fonts it crashes the library, we can update the theme and the starter.

**Comment by alfredo-dotcms** [comment]
seems like in that template there's a JS snippet that breaks the thumbnail generation process:

```
<script type="text/javascript">!function(e,n,t){"use strict";var o="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800",r="__3perf_googleFonts_cf86d";function c(e){(n.head||n.body).appendChild(e)}function a(){var e=n.createElement("link");e.href=o,e.rel="stylesheet",c(e)}function f(e){if(!n.getElementById(r)){var t=n.createElement("style");t.id=r,c(t)}n.getElementById(r).innerHTML=e}e.FontFace&&e.FontFace.prototype.hasOwnProperty("display")?(t[r]&&f(t[r]),fetch(o).then(function(e){return e.text()}).then(function(e){return e.replace(/@font-face {/g,"@font-face{font-display:swap;")}).then(function(e){return t[r]=e}).then(f).catch(a)):a()}(window,document,localStorage);</script>
```

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_003371a4_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
