### ISSUE TITLE
Exclude content variants from Pages

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24910]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

Pages screen is currently showing content on variants, which is, for now, an Experiment-only functionality. 

### Steps to Reproduce

* Create a new Experiment
* Create a new Variant of the Page
* Create new content for the Variant
* Go to Pages portlet and see the content on the Variant listed.

### Acceptance Criteria

Content on Variants should be excluded from Pages. 

### dotCMS Version

23.06/master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/24945

**Comment by hmoreras** [comment]
IQA: After creating a page => create an experiment under that page => Create a Variant  and under that variant add a new Blog, I can only see that blog in the Variant edit page. I am unable to see that new blog in the Content Search Portlet or Pages Portlet

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

New cases open in a new card #25353
