### ISSUE TITLE
Friendly message when Analytics App is not properly configured

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24922]
### Parent Issue

https://github.com/orgs/dotCMS/projects/7/views/4?filterQuery=label%3A%22Team+%3A+Falcon%22+-status%3ANew%2CFuture%2C%22Next+1-3+Sprints%22+sprint%3A%40current+&pane=issue&itemId=22617666

### Problem Statement

Currently, when the User haven't configured the Analytics App and try to go to the results in an Experiment, a dialog with a Bad Request error is returned to the User. 

This needs to be replaced with a friendly message indicating the problem and the action that is needed. 

<img width="425" alt="Screenshot 2023-05-11 at 16 13 55" src="https://github.com/dotCMS/core/assets/1576794/a57c075b-ee25-4629-85e1-aabad6ebdef3">

### Steps to Reproduce

* Do not configure the Analytics App
* Create an Experiment, add a variant, set a goal and start it. 
* Go back to the listing of Experiments and click on the bars icon at the far right on the running Experiment

It will fail with the Dialog above. 

### Acceptance Criteria

A friendly message indicating what is happening and how to solve it needs to be presented to the User. 

Possible message: 
“Analytics App not properly configured. Go to Apps and set the correct values for ‘Analytics Integration’”

### dotCMS Version

master / 23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Maybe something like "The Analytics App is not fully configured. Please open the Apps tool, and provide values for the following missing properties in the ‘Analytics Integration’: <<list of missing properties>>"

**Comment by oidacra** [comment]
Needs work:
The endpoint still retrieving `http://localhost:8080/api/v1/experiments/551e9a65-7f24-4fc4-ae9a-26cdde594509/results` the same message

**Comment by victoralfaro-dotcms** [comment]
New PR: https://github.com/dotCMS/core/pull/25354
