### ISSUE TITLE
Filtering does not put exact matches on the top of the site dropdown when searching

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24921]
### Problem Statement
When you search in the sitesearch dropdown it does not float exact matches to the top. This means it can be impossible to search for an item when it matches against more items than are in the list. 

### Steps to Reproduce

1. Create many (20+) sites that have the same text in them (for example example1.test.com, example2.test.com, then just test.com)
2. Attempt to search for just test.com. This will provide many results, but will not float the exact match (test.com) to the top. If it does not appear on the page at all, then it will never be selectable.

### Acceptance Criteria
1. Exact matches should be at the top of the search results.

### Sub-Tasks & Estimates

---

**Reported by:** Scott Wicken (scott.wicken@dotcms.com)

**Source URL:** [https://shsu-prod.dotcms.cloud/dotAdmin/#/c/workflow](https://shsu-prod.dotcms.cloud/dotAdmin/#/c/workflow)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/645d4c8cb9b28c6ecb89b761_ccfcb34bbe9c4903?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 112.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3440 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.2.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1713 x 1162</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by damen-dotcms** [comment]
Came from Scott.

While it's good we have a wildcard search, we need to have it so that if it's an exact match we put that at the top of the list.

The main site "shsu.edu" is not showing up on the list because the sub-domains all haev "shsu.edu" included in them.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected, we are showing the exact match on the top of the list 

![Image](https://github.com/dotCMS/core/assets/2641437/8d0755d8-9c5b-4d71-aa2a-5e3863bfdf43)
