### ISSUE TITLE
Favorite Page: User should be able to edit a bookmark even when the page is archived or deleted

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#24925]
### Parent Issue

#22343

### Problem Statement

A Page can be deleted or archive and still have a Bookmark, in this case, if the user tries to edit the bookmark it shows an error and prevents the user to editing.

<img width="416" alt="Screenshot 2023-05-12 at 10 02 41 AM" src="https://github.com/dotCMS/core/assets/72418962/c52c94c3-9b01-4ea3-a618-c94279419ed7">

### Steps to Reproduce

1. Add a Bookmark of a Page
2. Go and delete or archive the page
3. Try to edit the bookmark from the pages porlet
4. See the error

### Acceptance Criteria

- [x] User should be able to see the contextual menu of the bookmark with the bookmark options
- [x] User should be able to edit the bookmark and update the fields or delete it.

Updated by @fmontes 

### dotCMS Version

`release-23.06`

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
While testing this I found this one: https://github.com/dotCMS/core/issues/24984

**Comment by fmontes** [comment]
That's expected, what we fix here is that user can edit the bookmark itself not the page.

**Comment by fmontes** [comment]
Also when the page is a `urlContentMap` can't be edited when archive but a regular page can, and is also expected.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_003371a4_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Please see comments from Dev.
