### ISSUE TITLE
[UI] Limit name & mark steps as required. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24940]
### Parent Issue
#24343

### User Story

- Limit the variant Name yo 50 characters. 
- Add asterisk to the titles of required steps of Experiment configuration screen.

### Acceptance Criteria

- Should be a validation so the variants name can't be more than 50 characters
-  Add asterisk to the titles of required steps of Experiment configuration screen. 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: 
* Red asterisk showing for required steps
* Variant name limited to 50 chars.

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is working according to the @dsilvam comment. 

New card open here: https://github.com/dotCMS/core/issues/25340
