### ISSUE TITLE
CLI: Overwrite files instead of creating multiple copies 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24943]
### Parent Issue

#24753

### Problem Statement

The CLI creates multiple copies of a file when a content type/site/language/file is pulled. The CLI should always overwrite the existing file.

### Steps to Reproduce

Using the new CLI: 

1. Pull a content type, site, language and/or file. By default, a new json file will be created with the content type/site/language/file name 
2. Pull the  content type/site/language/file again and you'll notice that a new file with fileName(1).json is created. It should overwrite the existing one.

### Acceptance Criteria

The CLI should overwrite files instead of creating new copies of existing content types/sites/languages/files. In case of conflicts, the user must use the tool they chose for versioning their files.

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
when these commands were initially developed we still didn't have a folder tree structure as we now do. Replacing the file doesn't really fix the problem. The CT, language, and site must be saved accordingly to the file tree structure. Therefore we need to take into consideration a workspace or root folder marker.  These additional bits of work will be undertaken as part of this effort.

**Comment by fabrizzio-dotCMS** [comment]
Note to QA 
this is what the CLI folder structure should look like 
https://docs.google.com/spreadsheets/d/1iO7lq23Rdcev_-sFB5WdX8-KrEsy96dUTdMhvHY8IrE/edit?pli=1#gid=16818197

verify that.. when calling a pull command anything that downloads and creates a file locally also creates a local workspace
the local workspace is a set of folders like 
`content-types,` `files`, `sites`, `languages`, and also a hidden file `.dotworkspace.yml `that serves as a marker for the workspace itself.

When executing a command like `pull FileAsset` the file resulting from this execution should end up saved under the folder content-types. Even if the ct is pulled multiple times the file should always get overridden. Same for Sites and Languages

Also.. no matter where within the workspace you are the result of pulling should always stick to the folder structure e.g. 
Let's say we do 
```
mkdir test
cd test
ct pull  FileAsset

```
This action should create a workspace and place the CT under the folder content-types
Now let's do 
```
cd sites 
files pull //default/robots.txt 

```
The result of pulling that file from within the folder sites should still leave the file in the propper directory structure under the topmost files folder
