### ISSUE TITLE
[UI] Hide default conditions in Bonce Rate/ Reach Page Goal at Experiment Configuration

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#24948]
### Parent Issue
#24343

### User Story
Hide default conditions in Bonce Rate/ Reach Page Goal at Experiment Configuration

#### Bounce Rate 

<img width="941" alt="image" src="https://github.com/dotCMS/core/assets/31667212/949e8929-2525-48ed-9293-325874ee0a68">

#### Reach Page 

<img width="848" alt="image" src="https://github.com/dotCMS/core/assets/31667212/87a90d3c-515c-477f-a5ea-0f4b82ff6b1a">

#### Bounce Rate 

<img width="905" alt="image" src="https://github.com/dotCMS/core/assets/31667212/71268686-66d4-4cce-b420-3b61747027a7">

#### Reach Page 

<img width="899" alt="image" src="https://github.com/dotCMS/core/assets/31667212/7e3623c9-2ff3-4d99-9e97-05503c902b10">

### Acceptance Criteria
Default condition shouldn't be shown in Bonce Rate or Reach Page

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: Params hidden from the Goal section.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
