### ISSUE TITLE
Searching moves the result set down

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24953]
### Problem Statement

See the movie:

https://github.com/dotCMS/core/assets/934364/ca1ae588-faa3-4a18-8adc-ec4050914ee5

### Steps to Reproduce

We moved the search bar - now when we search, the result set gets pushed down just a little bit

### Acceptance Criteria

the resultset should not be pushed down.

### dotCMS Version

23.06

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_a1c971b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
