### ISSUE TITLE
UI Styling Problem after Reopening Window

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24954]
### Problem Statement

As a dotCMS user, I am encountering styling problems with the UI related window after reopening it for the second time. The UI elements are broken or missing, making it difficult to interact with the window.

https://github.com/dotCMS/core/assets/2641437/42846c26-2b1d-4372-9fdd-dede59d3e0d1

### Steps to Reproduce

- Log in to dotCMS.
- Open the UI-related window (any blog detail).
- Close the window.
- Open the window again.
- Observe that the UI elements are missing or broken.
- Clear the search in the left component 

### Acceptance Criteria

- The UI related window should display correctly every time the user opens it.
- All UI elements should be visible and appear as designed.

### dotCMS Version

Tested on dotCMs-23.06 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
@bryanboza can't reproduce, please attach video.


https://github.com/dotCMS/core/assets/751424/f01287e4-511c-45b5-9ee3-855d2ac252f4

**Comment by zJaaal** [comment]
## Passed Internal QA

Tested on latest `master` branch

### Screenshots

https://github.com/dotCMS/core/assets/63567962/cd9a39a5-01c1-478f-a574-ff13c2c602b2

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_183eee1_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

We need also to adjust the scrolling of the take over

https://github.com/dotCMS/core/assets/129882031/f70f16e3-afab-4c14-a2a4-61bcb8b021c2

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eb200d2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
