### ISSUE TITLE
Simplify the task of applying updated licenses

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#24962]
### Parent Issue

The process of replacing expiring Enterprise licenses to multi-node servers is cumbersome. It generally requires direct backend interaction with each individual node. Node selection is usually managed by a load balancer, and is beyond the control of the person applying the updated licenses.

"How do I update the licenses on multiple nodes?" is a common question for support.

### User Story

As a dotCMS administrator, I want to be able to upload a new Enterprise license and have a simple, repeatable, process to apply the updated licenses to all servers.

Perhaps one aspect is we could have dotCMS prefer certain licenses, something like:

- When selecting a license to apply dotCMS sorts the licenses by expiration date, selecting the licenses with the latest dates first.
- Or, there is a mechanism in the backend that allows an admin to assign an affinity, perhaps the ability to mark individual licenses as "preferred" or "not preferred"

This still requires a "server roll" which is not ideal, and is probably beyond the reach of many dotCMS admins. Still, it seems like a good start. 

There are existing REST endpoints that might offer a solution, but these would need to be executed on each node. If there is a nice REST solution, we should document it. 

<img width="498" alt="Screenshot 2023-05-17 at 12 14 47 PM" src="https://github.com/dotCMS/core/assets/628954/2769753d-2d97-4798-a608-65b8fd86fba8">

### Acceptance Criteria

Provide and document a reliable process to apply updated dotCMS licenses.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
We will revisit if resurfaced, it appears to be a dying problem.
