### ISSUE TITLE
Need to create postman test for the delete experiment endpoint 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#24967]
### Parent Issue

Originally posted here https://github.com/dotCMS/core/issues/22985#issuecomment-1511764955

### Problem Statement

We need to validate all the possible scenarios calling the delete endpoint of experiments. We need to validate behavior, response codes, and permissions. 

- [x] Validate you are able to delete the experiment without problems 
- [x] Validate what happens if you send an invalid {experimentId} (404 should be returned) 
- [x] Validate we are unable to delete RUNNING, ENDED, and ARCHIVED experiments (we need to return a 400 error and a message indicating just DRAFT or SCHEDULED experiments can be deleted)

### Steps to Reproduce

- Open Postman and create a new Request
- Set the Request method to DELETE
- Add the URL of the Experiment you want to delete to the Request URL field. (e.g. http://localhost/api/v1/experiments/{experimetnId)
- Add the Authorization token to the Headers
- Send the DELETE request
- Verify that the experiment is no longer present in the system

### Acceptance Criteria

- The mentioned test should be created and running as part of the CI/CD process 
- Don't forget to add validation to the tests

### dotCMS Version

Tested on release-23.06 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/26441
