### ISSUE TITLE
Not getting Results when use a Detail Page (Url Map) in an Experiment

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24974]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When create a new Experiment using a Detail Page (Url Map), You always get the results with all the fields in 0

### Steps to Reproduce

- Start dotCMS up using the full starter.
- Create an Experiment using the blog-detail page.
- Add a Variant and a Goal (anyone).
- Logout and close the Browser tab
- Open a new tab and go to the blog-detail page.
- Go to the Experiment result, you are going to see 0 total session, You should have 1.

### Acceptance Criteria

The sessions must be counting when you are using a Detail Page inside an Experiment

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: sessions being counted and also conversions.

**Comment by bryanboza** [comment]
Fixed, now it is working as expected. Tested on master // Docker // FF
