### ISSUE TITLE
Asking for Authentication all the time when use a Detail Page inside Experiment

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#24975]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When you create an Experiment using a Detail Page (Url Map) and after Start the Experiment you go to the Detail Page the Front end Login dialog is showed asking for login/password.

### Steps to Reproduce

- Start dotCMS up using the full starter.
- Create an Experiment using the blog-detail page.
- Add a Variant and Add a new content to the page, I think that the bug just happend when you Add/Remove a Contentlet or change the Layout of the page.
- Add any Goal and start the Experiment.
- Logout and close the Browser tab
- Open a new tab and go to the blog-detail page.
- You are going to be ask for login/password.

### Acceptance Criteria

You must not be ask for login/password.

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: This working as expected. Not redirecting to the login page when getting a variant assigned.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
