### ISSUE TITLE
Template Builder: Implement the Box Component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24979]
### Parent
#24535 

### User Story
As a user of the Template Builder, I want to be able to add a box component, so I can create more complex layouts.

### Acceptance Criteria
- The box component should be implemented using the design provided.
- The box component should use primeng components with it variants

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
[Figma](https://www.figma.com/file/ECuBLIRWZjEzLzmlPrA0Rk/Template-Builder?type=design&node-id=344%3A16814&t=rH9rs6dgDWwkwwcf-1)

<img width="458" alt="image" src="https://github.com/dotCMS/core/assets/751424/c68a6756-7bdf-4aef-9a0d-db84b6eb6290">

### Assumptions & Initiation Needs
- The design for the box component has been provided.
- The primeng components have been identified.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Implement the design for the box component
- Integrate the box component with the primeng components

**Comment by zJaaal** [comment]
We have an error importing Global Styles from `dotcms-scss` is being solved in this [PR](https://github.com/dotCMS/core/pull/25029)

<img width="1153" alt="Screenshot 2023-05-24 at 11 52 31 AM" src="https://github.com/dotCMS/core/assets/63567962/a575fd0b-3885-42f5-8e27-2545f18d3e51">
