### ISSUE TITLE
Favorite Pages: Portlet still showing up even after being removed

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#24986]
### Parent Issue

Found when IQA'ing ticket: https://github.com/dotCMS/core/issues/24879

### Problem Statement

Limited Users still have access to the **Pages** portlet even after a CMS Administrator has removed access to it. In other portlets, such as **Templates**, when the User reloads the browser, it is taken to the first portlet available in their menu.

### Steps to Reproduce

1. Open the **Page Properties** in the `/index` page, and give Chris Publisher -- a limited User -- full access permissions.
2. In the **Roles & Tools** portlet, give him access to the **Pages** portlet.
3. Log in as Chris, and open up the **Pages** portlet. You should have access to it.
4. In a **SEPARATE BROWSER SESSION**, log in as the CMS Admin and remove Chris' access to the **Pages** portlet.
5. Reload the browser in Chris' session. The **Pages** portlet is still showing up.

### Acceptance Criteria

Once a CMS Administrator has revoked a limited User's permission to a portlet, they shouldn't have access to it anymore.

### dotCMS Version

23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

As per conversation with @fmontes , the `MenuGuardService` should be added to the **Pages** Angular portlet.

### Assumptions & Initiation Needs

If you follow similar steps, but using the **Templates** portlet instead, you'll see that the limited User doesn't have access to the portlet as soon as the CMS Admin revokes it form the **Roles & Tools** portlet.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `dotcms/dotcms:23.06_86480ec5_SNAPSHOT`

Now, after the **Pages** portlet is removed from the limited User's layout, refreshing the tab is redirecting you to the first available portlet in the current menu.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_86480ec5_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
