### ISSUE TITLE
Favorite Pages: Not Able To Add Bookmark To Archive Page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24984]
### Problem Statement
When a user archive a page and then goes to a list that includes the archive page, they can try to add/edit that page to a bookmark from the context menu, but the page doesn't exist.

### Steps to Reproduce
1. Archive a page in dotCMS
2. Go to a list that includes the archived page
3. Try to add the archived page to a bookmark from the context menu

### Acceptance Criteria
- Users should not be able to see the option to "Add Bookmark" or "Edit Bookmark" on an archive page

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_003371a4_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
