### ISSUE TITLE
Favorite Page: Hide Favorite Page Content Type from Content Search

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24980]
### User Story
As a user, I don't need to see the the Favorite Page content type from the content search.

### Acceptance Criteria
- Hide the Favorite Page content type from the content search.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- All necessary content types are currently available in the dotCMS backend.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Verify that the Favorite Page content type is hidden from the content search.

**Comment by zJaaal** [comment]
## Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_8d5b0f5e_SNAPSHOT]`

### Screenshot

https://github.com/dotCMS/core/assets/63567962/b385041d-2484-4e79-9721-3410eee454ae

**Comment by zJaaal** [comment]
Found this issue while IQA: https://github.com/dotCMS/core/issues/25080
