### ISSUE TITLE
[UI] Add Bayesian standard curves to Experiment's report

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24982]
### Parent Issue

*No response*

### User Story

As a user, I want to be able to see the chart of the Bayesian method using the data generated, so I can understand better the definition of the suggested winner.

### Acceptance Criteria

- Use a tab to change from Daily results and Bayesian details
- Generate a Chart showing the 3 standard curves.
- Show a detailed table showing the values used to generate the chart.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo of generation https://stackblitz.com/edit/js-x76d2k?file=index.js

### High-level Wireframe

![Multiple Charts](https://github.com/dotCMS/core/assets/1909643/2eb6199c-47d4-460b-9424-56bbf5767f18)

### Assumptions & Initiation Needs

- All the data necessary to generate the chart and show the details comes in the result endpoint.

### Quality Assurance Notes & Workarounds

*No response*

\`\``[tasklist]
### Sub-Tasks & Estimates
- [x] #25518
- [x] #25519
- [ ] #25520
`\`\`

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF
