### ISSUE TITLE
Application is currently not able to show third languages country codes

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#24988]
### Problem Statement

Application is currently unable to display the country code for the third language (any besides English or Spanish)

### Steps to Reproduce

1. Open the application
2. Navigate to the language settings
3. Select a third language
4. Navigate to a page where the country code should be visible
5. Observe that the country code is not displayed

### Acceptance Criteria

The country code should be properly displayed regardless of the selected language

### dotCMS Version

#release-23.06

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

Attached the screenshot

![Screenshot 2023-05-18 at 4 57 38 PM](https://github.com/dotCMS/core/assets/129882031/56ef0835-b683-4269-b49c-2e8b44d37498)

**Comment by fmontes** [comment]
The Language missing the country code - the language dropdown should deal with this better

**Comment by fmontes** [comment]
Not show the `()` if no country code.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_e66ec4d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
