### ISSUE TITLE
Punch List : Redis Session Manager

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24990]
### Parent Issue

https://github.com/dotCMS/core/issues/24294

### User Story

- [x] Make connection pool size configrable
- [x] If the environmental variable `DOT_DOTCMS_CLUSTER_ID` is set, use it to prefix all gets/sets/keys/ in REDIS. See our current redis cache implementation.  Doing this will allow multiple clusters to share the same session redis store.
- [x] rename `master` branch to `trunk` and make it the default in github.
- [x] change java packaging to `com.dotcms`
- [x] Test getting a single jedis connection when we `initializeRedisConnection`.  When we start now, it looks like we are configured correctly but then errors happen later once sessions start getting created.
- [x] don't dump connection stack traces into the logs - make those debug.  Think in about a production environment and a redis server becoming unavailable.  All those session logs would swamp a server/logging very quickly. Just log a 1 line warn that contains the reason we cannot connect to redis.
- [x] Verify resiliency - take the redis server down while using the dotCMS and then bring it back up and make sure that we reconnect automatically.
- [x] create a github action that automatically jars and publishes the artifact to our repo at https://repo.dotcms.com when a merge is made to the trunk branch.
- [x] Many web requests are single requests - done by bots or by session-less CDNs whatever. In most cases, we should not persist an anonymous session.  We need to make sure that a single call to a front end asset or page is not enough to persist that.  Maybe we have a switch that enables it on the front end and if that is not set then we only persist backend sessions `TOMCAT_REDIS_ENABLED_FOR_ANON_TRAFFIC`
- [x] Unify redis config - we now have two ways to configure redis, one in the `RedisClientFactory` which uses a class called `MasterReplicaLettuceClient` and one in the  `RedisSessionManager`.   In the `MasterReplicaLettuceClient`, we can fall back and use the the environmental variables used by the `RedisSessionManager` if the ones for the `MasterReplicaLettuceClient` are not passed in.  We can reuse as many properties from the `RedisSessionManager` as possible, including min/maxConnections, SSL, etc...

### Acceptance Criteria

Finish the punch list.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
@jcastro-dotcms @bryanboza Not sure how to test this, maybe we send this directly to QA?

**Comment by jcastro-dotcms** [comment]
@fmontes I agree. I can pass @bryanboza some instructions on how these improvements can be tested.

**Comment by bryanboza** [comment]
Fixed, tested on master with the last redis example and now this is working as expected. Some of the tested scenarios 

- Able to start with saving the session with redis and the regular cache 
- Able to all the parameters are configurable and you are able to see reflected those changes 
- Able to start dotCMS with redis cache provider 

![Image](https://github.com/dotCMS/core/assets/2641437/42086971-9615-4911-84f1-b49c4a115e40)
