### ISSUE TITLE
Favorite Pages: Allow User Cross-Site Page Editing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24992]
### Problem Statement
In pages portlet when you try to cross-site edit a page from a bookmark user can go to edit page but the CSS are broken.

### Steps to Reproduce
1. Create another site
2. Navigate to Pages portlet
3. From site A add a bookmark
4. Switch to site B
5. From nookmarks, try to edit the page
6. See how the CSS are broken

### Acceptance Criteria
User should be able to edit a boomarked page from any site

### External Links
N/A

### Assumptions & Initiation Needs
If the page we try to edit is in a diferent site that the current site, we need to change the current site before go to edit the page.

Yes, we're changing the current site under the hood.

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
## Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_81de48de_SNAPSHOT]`

### Screenshot

https://github.com/dotCMS/core/assets/63567962/aae7c49e-01a1-46a3-b546-619b0859a8cb

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_81de48de_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
