### ISSUE TITLE
Favorite Pages: Fix Stuck State in the New Pages Portlet When Changing Sites

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24991]
### Problem Statement
When a user changes the site within the new pages portlet, the page list gets stuck in a loading state.

### Steps to Reproduce
1. Navigate to the new pages portlet in the DotCMS backend.
2. Change the site from the dropdown menu.
3. Observe the page list getting stuck in loading state.

### Acceptance Criteria
- Change the site should refresh the page list.
- User should be able to have bookmarks cross-sites.

### External Links
N/A

### Assumptions & Initiation Needs
- The new pages portlet should be functioning correctly.
- The user should have access to change the site within the new pages portlet.

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
## Failed Internal QA

If you go to `edit-page` and go back to `Pages Portlet` and change the host, the search of the listing table is not being triggered

Docker Image: `[dotcms/dotcms:23.06_60c068ac_SNAPSHOT]`

### Screenshots


https://github.com/dotCMS/core/assets/63567962/5e093cf6-669e-4a3a-b45e-ffb9c0552bf5

**Comment by alfredo-dotcms** [comment]
@zJaaal can you please check again with the latest code from release, seems like it does not happen with the work done on https://github.com/dotCMS/core/pull/25005

**Comment by zJaaal** [comment]
### Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_7df7c26a_SNAPSHOT]`

#### Screenshots
https://github.com/dotCMS/core/assets/63567962/8703b73e-1620-4d97-8f13-64613f81fe79

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **23.06_81de48de_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Page listings are not getting reloaded after changing the site to a newly created one.

Steps:

1. Add a new site
2. Go to pages
3. Switch to the new site
4. Create a new page
5. Bookmark new page
6. Go to pages
7. Scroll through the page list and change sites

Please see video for reference

https://github.com/dotCMS/core/assets/129882031/a0317fcc-3648-4cef-8938-d5c91131bde9

**Comment by fmontes** [comment]
Fixed and tested in FF

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_906f4029_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
