### ISSUE TITLE
Relationship Name can get too long

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#250]
Last week we ran into a problem with a relation name in 1.9.5.0. We had created a relation which had a very long name (because the structures had long names). This was no problem, but every time we tried to save content that used this relation, we got an error in the log (dotCMS gave no error). It said that it couldn't save the field in Tree or Treemap since the name was too long. 

This is a minor bug. Adding some validation to the length of the relationship name will solve this problem.

**Comment by wezell** [comment]
We need to use a camelCased version of the releationship without _Parent and _Child
