### ISSUE TITLE
Phase 1: Leverage AI in dotCMS

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25003]
Purpose: Leverage the power of Machine Learning technology in the dotCMS product.

### Goals

* Implement features that leverage the power of Machine Learning \(ML\) and Large Language Models \(LLM\)
* Enable customers to tap into the power of ML/LLM for their own content
    * Generate new content
    * Assist with editing and managing content
* Utilize AI to improve existing dotCMS features
* Utilize AI to improve dotCMS ease of use for
    * Developers
    * Content Architects
    * Content Editors

### Phases

Work will be implemented in phases:

I. Short-term \(year-end 2023\):

* Help customers with common, in-demand tasks
* Demonstrate the potential of the technology in dotCMS
* Implement as quickly as possible

II. Medium-term \(Q2-Q3 2024\):

* Provide deeper capabilities
* Demonstrate more integrated capabilities
* Implement without major code changes

III. Long-term \(Later\):

* Identify and begin working towards the AI “killer” app for CMS
* Deliver on the full potential of the technology
* Integrate fully into core code

### Scope

This epic covers just the phase I, Short-term.

All features implemented in this phase must be deliverable without changes to the core code base.  This means changes must be implemented in one of the following ways:

* Velocity code
    * For example, Custom Fields, Custom Blocks, or Scripted APIs
* OSGI Plugin
    * This may include a stand-alone plugin, Workflow actionlet plugin, or plugins specific to other dotCMS features

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Capability Survey and Risk Estimate: https://docs.google.com/document/d/1dvfGViFF7cxNAMNErJpqbubOMlwJWOtiXG9rCWQK8po/edit?usp=sharing
* Ideation: https://docs.google.com/document/d/1VNH4BTWU9jATXSr28v6EgszmOAqlDS7e3ha8aOhPqEo/edit?usp=sharing

Inte

\`\`\`\[tasklist\]

### Subtasks

**Comment by prestonso** [comment]
Marking closed as all this is now accounted for in Airfocus.
