### ISSUE TITLE
Include new Bayesian results in A/B/C Testing

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#25001]
### Parent Issue
#23625

### User Story
As a scrum master, I want to enhance A/B/C Testing Bayesian calculations by including a 95% credibility interval and measured risk.

### Acceptance Criteria
1. A 95% credibility interval is added to the A/B/C Testing Bayesian calculations.
2. Measured risk is incorporated into the calculations.
3. The updated calculations accurately reflect the statistical significance and confidence level of the test results.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/25063

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
- Start analytics infrastructure docker containers
- Setup analytics integration app like it's described in https://github.com/dotCMS/core/issues/23245#issuecomment-1360066641
- Create an experiment with two variants and a goal and start it
- Generate some events according to the goal you defined (probably is better to use `Reached page`) for original and both variants
- Go to experiment details page and check for results in the network tab
- Verify that Bayesian results should include data for 3 variants (original + 2 variants)

**Comment by oidacra** [comment]
Passed IQA:
3 Variant (1 Original +2 Variants) set.
<img width="1426" alt="Screenshot 2023-07-05 at 10 09 50 AM" src="https://github.com/dotCMS/core/assets/1909643/82b5b6c3-330b-4a2d-ac52-7c846f5c987f">

Goal set:
<img width="1426" alt="Screenshot 2023-07-05 at 10 11 23 AM" src="https://github.com/dotCMS/core/assets/1909643/6c953d30-1632-498d-8992-eb7f2ea8b1af">


Response:
<img width="558" alt="Screenshot 2023-07-05 at 10 08 43 AM" src="https://github.com/dotCMS/core/assets/1909643/289239d1-3834-41f2-8720-7b749dc14547">

Summary table
<img width="1240" alt="Screenshot 2023-07-05 at 10 08 47 AM" src="https://github.com/dotCMS/core/assets/1909643/2995a049-f2af-4f68-b3f6-9d683ca8970a">

**Comment by bryanboza** [comment]
Fixed, now we have this in the results... Tested on master / Docker // FF
