### ISSUE TITLE
[UI] Fix loading state in Run Experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25019]
### Problem Statement

- When you run an experiment, the button doesn't change the state to IDLE and stuck in loading.

### Steps to Reproduce

- Create a new experiment
- Add a variant
- select a goal
- Click in RUN Experiment

### Acceptance Criteria

- When you run the experiment, and it is successful the button needs change to STOP EXPERIMENT, and able to click it (No Loading state)

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Bug reported not happening.

**Comment by bryanboza** [comment]
Unable to reproduce, tested on master // docker // FF
