### ISSUE TITLE
Experiments Job Fails to Run without EE License

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25031]
### Problem Statement

The Experiments job in dotCMS regularly prints an error in the log every few minutes if the EE license is missing.

Here is the log: https://gist.github.com/bryanboza/cef84ae0e6127aece6bc8e52671299bc

### Steps to Reproduce

- Start a dotCMS instance without an EE license.
- Login as admin and wait 
- Check the log for the error message.

### Acceptance Criteria

- The Experiments job should run without errors regardless of the presence of EE license
- Errors should not be generated in the log when the EE license is missing.

### dotCMS Version

Tested on release-23.06 // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by oidacra** [comment]
No error showed in the logs (catalina.out).

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d8ef9ab_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
