### ISSUE TITLE
PP content set as working state instead of live state when there is archived version in other language

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#25044]
### Problem Statement

When a live content is push published and there is an archived version of the content in other language, the content is push published to working state instead of live state as expected.

### Steps to Reproduce

1. Create a new content in English (or default language)
2. Publish the content
3. Create a version of the content in Spanish or another language
4. Archive only the Spanish version (the English version is still live)
5. Push publish the content
6. Go the receiver: the English version was push published as working instead of live

### Acceptance Criteria
Content should be push published in the same state in the receiver.

### dotCMS Version

22.03.6 and  23.05

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://dotcms.zendesk.com/agent/tickets/111625
https://dotcms.zendesk.com/agent/tickets/111552

**Comment by dsolistorres** [comment]
PR for this issue: https://github.com/dotCMS/core/pull/25180

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
