### ISSUE TITLE
[UI] Show in the details of Reports the Probability to be Best and Conversion rate range

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25053]
### Parent Issue

#24343

### User Story

As a user,
I want to display the Probability to be Best and the Conversion rate range in the details component of Experiment Reports so that users can easily access this important information.

### Acceptance Criteria

- Only leave the columns: Variants, Conversions, Sessions, Conversion Rate, Probability to be Best, Conversion Rate Range
- The first column shows a Thorphy icon to show the suggested winner.
- In bold the row of the suggested winner.
- If the variant is **Promoted**, show a tag showing that.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="1249" alt="Screenshot 2023-06-06 at 1 49 33 PM" src="https://github.com/dotCMS/core/assets/1909643/4b95a50a-f115-4d66-827a-085a150d479b">

### Assumptions & Initiation Needs

- All the information needed comes from the `results` endpoint

### Sub-Tasks & Estimates

to be defined

**Comment by oidacra** [comment]
The title of the last column is `Conversion Rate Range (95%)`

**Comment by dsilvam** [comment]
Passed Internal QA: This is showing as expected. Proper column names and proper results.

**Comment by bryanboza** [comment]
Fixed, tested based in the last comment and now we have this title in the last column. Tested on master // Docker // FF
