### ISSUE TITLE
Rename Bounce Rate to Exit Rate and create real Bounce Rate

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25057]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

Right now our Bounce Rate is taking all the pageview events that happen in one Experiment session and if the last one was the Experiment page then we count it as a Bounce Rate, really this definition is a Exit Rate.

A Bounce Rate should be if inside the Experiment Session just one pageview Event with URL equals to the Experiment's Page happened .

### Steps to Reproduce

- Start dotCMS with the full starter.
- Create a Experiment in the blog/index page, and set a Bounce Rate goal.
- Start the Experiment.
- Log out and close the Tab.
- Navigate to the Index page and after that to the Exit Page, Close the tab.
- GO to the Experiment Result and you are going to see that you have a session and you not have any success.

 but it is not really a Bounce Rate because you visited the Index page first, so you should have a success here.

### Acceptance Criteria

We must have Exit Rate and Bounce Rate Goal both of them working right

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by oidacra** [comment]
IQA Passed:
- Experiment configurated
<img width="1342" alt="Screenshot 2023-08-01 at 5 57 52 PM" src="https://github.com/dotCMS/core/assets/1909643/96783742-257a-4b1d-afdd-6f1afd069429">

- Navigate to the Index page and after that to the Exit Page, Close the tab.
- GO to the Experiment Result and you are going to see that you have a session and you not have any success.
Response of results:
<img width="907" alt="Screenshot 2023-08-01 at 5 55 03 PM" src="https://github.com/dotCMS/core/assets/1909643/a19285a5-57e4-4f7f-8783-8c3827996935">

CubeJS:

<img width="2982" alt="Screenshot 2023-08-01 at 5 57 28 PM" src="https://github.com/dotCMS/core/assets/1909643/20df68d1-ad26-4c7f-b730-2111f1302749">

**Comment by dsilvam** [comment]
Note to IQA: We need to test both Bounce and Exit rate goals

**Comment by oidacra** [comment]
IQA: Exit Rate Goal

Test Plan
![Image](https://github.com/dotCMS/core/assets/1909643/64dd4ec2-a49f-4e54-a3b0-2f9a8defdfde)

Case 1A (V1):
![Image](https://github.com/dotCMS/core/assets/1909643/d7501dac-a0d1-4619-9989-dd08b59994d5)
Session ✅, Conversion ✅

Case 1B (Original):
![Image](https://github.com/dotCMS/core/assets/1909643/90df586b-3b56-45ff-beee-8dcdbce07dc1)
Session ✅, Conversion ✅

Case 2 (Original):

![Image](https://github.com/dotCMS/core/assets/1909643/6b8efa85-c273-4d48-912b-89d41f3aa655)
Session ✅, Conversion ❌

Case 3 (Original):

![Image](https://github.com/dotCMS/core/assets/1909643/b1d95c04-3a73-4e30-aca3-0083b17d8dba)
Session ✅, Conversion ❌

**Comment by dsilvam** [comment]
Passed Internal QA: Bounce rate working as expected.

**Comment by bryanboza** [comment]
Fixed, now the bounce rate goal is working as expected:


![Image](https://github.com/dotCMS/core/assets/2641437/4e87afce-b7cc-4505-9d78-fed22cef3b37)
