### ISSUE TITLE
Request to support in depth/multi-depth Lightweight Endpoints

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#25064]
### User Story

For example, If I created a file “`/application/apivtl/podcasts/search/get.vtl”` and then tries to search for a get.vtl file in `“/application/apivtl/podcasts/”` ignoring 'search' folder. 

Currently, Lightweight Endpoints only support 1 depth so please support multi-depth support for such endpoints.

### Acceptance Criteria

As I described in the above example so the acceptance criteria would be to return response for more than 1 depth resource such as 

`/application/apivtl/podcasts/search/get.vtl`

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111578

**Comment by wezell** [comment]
This pattern can be easily achieved using the current tooling.  You just need to use the initial `get.vtl` as a controller.  So in this case, in the file `/application/apivtl/podcasts/get.vtl` you can:

```
## parse the get from the subpath
#if($UtilMethods.isSet($pathParam))
    $set($pathParam=$pathParam.replaceAll("/", "").replaceAll(".", ""))
    #dotParse("/application/apivtl/podcasts/$pathParam/get.vtl")
    #stop
#end
$dotJSON.put("firstEndpoint", true)
```
