### ISSUE TITLE
History tab loads old contentlet versions in no particular order

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#25079]
### Problem Statement

Old contentlet version must be presented ordered by mod_date DESC
But when loading history it shows like this: 
![Screen Shot 2023-05-30 at 12 11 00 PM](https://github.com/dotCMS/core/assets/37148755/203e337d-de45-4ae2-ab80-0496763f0786)

### Steps to Reproduce

The issue can be seen in our authoring env 
https://authoring.dotcms.com/dotAdmin/#/c/c_Blogs/297ecaf3-132f-4a1e-bb79-b609087ac2ec

you might need to reload the contnetlet edit window a couple of time before the problem presents 

### Acceptance Criteria

we should be able to load the history tab and the old versions should always load order by mod date descendant 

### dotCMS Version

release 23.06 

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
Internal QA: Passed



![Image](https://github.com/dotCMS/core/assets/8741395/3776f884-d9b0-482b-8181-6ae8d4e5c4fb)

**Comment by wezell** [comment]
Is there a test because this happens a lot?  Also what does this look like with multi-lingual content?

**Comment by bryanboza** [comment]
Fixed, tested with regular content-lets and now we have a sequential order 

![Image](https://github.com/dotCMS/core/assets/2641437/00bdd910-7447-48cf-a154-223b86d1b596)

Also tested with multi-language content and works as expected 

![Image](https://github.com/dotCMS/core/assets/2641437/26781f8f-f869-43c2-bbdc-8433a0efa9f2)

Tested on release-23.06 // Docker // FF

**Comment by fabrizzio-dotCMS** [comment]
> Is there a test because this happens a lot? Also what does this look like with multi-lingual content?

@wezell I did add a test
