### ISSUE TITLE
Favorite Pages: Add Trash Icon to Bookmark Dialog Form

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25072]
### User Story 
As a dotCMS stakeholder, I want to keep consistency and the "remove bookmark" button doesn't looks like our "remove entity" button.

### Acceptance Criteria
- Add a trash icon to the remove button
- Make the button `p-secondary` and `p-text`

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by rjvelazco** [comment]
## Passed Internal QA

**Docker Image:** [`dotcms/dotcms:23.06_455c859e_SNAPSHOT`]

<img width="1122" alt="Screenshot 2023-06-01 at 9 55 28 AM" src="https://github.com/dotCMS/core/assets/72418962/f726e26a-f7f4-4b8a-9f52-9747173054c9">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_906f4029_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
