### ISSUE TITLE
Favorite Pages: Table Sorting Issue

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25073]
### Problem Statement
In the pages portlet when the page load the table is sorted by "Last Edited" but the header cells is not showing that.

### Steps to Reproduce
1. Login to dotCMS
2. Navigate to the Pages portlet
3. Notice the table is sorted by "Last Edited" but the header cell is not showing that

### Acceptance Criteria
The "Last Edited" cell should show that is being used for sorting.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_455c859e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

I created this issues related to sorting #25111
