### ISSUE TITLE
Favorite Pages: Content Type item of DotFavoritePages has entry point to broken portlet

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#25080]
### Problem Statement

Since we removed the `DotFavoritePage` from `Content Search`, we need to get rid of the link that points to `Content Search` filtering by` DotFavoritePage`

### Steps to Reproduce

https://github.com/dotCMS/core/assets/63567962/0276d23d-27da-4c45-b928-1a31e55e78ca

### Acceptance Criteria

- Content Type Item `View(n)` link shouldn't point to `Content Search` portlet
- Be sure that the user cannot go to `Content Search` portlet while filtering by `DotFavoritePage` content type using other link as this one

### dotCMS Version

`Release 23.06`

### Proposed Objective

Please Select

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_7c32fc02_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image:** [`dotcms/dotcms:23.06_86480ec5_SNAPSHOT`]

https://github.com/dotCMS/core/assets/72418962/e9612172-0f5f-410e-884b-ee8f164940a7
