### ISSUE TITLE
Favorite Pages: Notifying the user when a workflow action request fails

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25096]
### User Story
As a dotCMS user, I want to receive a notification when a workflow action request fails, so I can take swift action. 

### Acceptance Criteria
- In the catchError of the workflow action trigger, show a toast with the error message.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
1. Start dotCMS no license full starter
2. Go to pages
3. Trigger "publish" on a blog page
4. You should see a toast with the error

### Sub-Tasks & Estimates:
N/A

**Comment by zJaaal** [comment]
## Passed Internal QA

Docker Image: `[dotcms/dotcms:23.06_906f4029_SNAPSHOT]`

### Screenshot 

https://github.com/dotCMS/core/assets/63567962/16629986-72c8-4b1b-9de5-e0ef66e5bf70

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_906f4029_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
