### ISSUE TITLE
[UI] Add the ability to edit inline the description of a Experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25092]
### Parent Issue

#24343

### User Story

As a user, I want to be able to edit the description of an Experiment inline. If the description still needs to be added during the creation step, I expect to see a message prompting me to add it in the Experiment Configuration.

### Acceptance Criteria

- The user can edit the description inline of an Experiment directly on Experiment Configuration.
- If the user has not provided a description during creation, a message is displayed in the Experiment Configuration section.
- The updated description is saved and reflected in the Experiment details.
- If the Experiment is `RUNNING` we cant edit the description

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Description added at the creation action.
<img width="1338" alt="Screenshot 2023-05-31 at 1 23 16 PM" src="https://github.com/dotCMS/core/assets/1909643/9eb1ccb4-c9d9-434a-80d0-88fa18e96e61">

Add if the description is missing (inline too).
<img width="1251" alt="Screenshot 2023-05-31 at 1 29 30 PM" src="https://github.com/dotCMS/core/assets/1909643/21e7facd-ba82-4b40-b4c0-b34352758e19">

**Comment by dsilvam** [comment]
Passed Internal QA: Able to inline include/edit the description of the Experiment.

**Comment by bryanboza** [comment]
We need to trim before save the description, right now if you add a blank space and save the description we take this as a character and save it in blank 

![Image](https://github.com/dotCMS/core/assets/2641437/756f7d03-4319-4b80-a8d6-50d43e281286)

**Comment by oidacra** [comment]
Fixed with #25410 https://github.com/dotCMS/core/pull/25410

**Comment by victoralfaro-dotcms** [comment]
IQA using `dotcms/dotcms:master_c8552f9_SNAPSHOT`
![image](https://github.com/dotCMS/core/assets/64026161/50e399f7-ad3f-4a18-bc4c-520a51dec7ee)
![image](https://github.com/dotCMS/core/assets/64026161/a16190f6-d1ec-416d-a738-8a47881db1c9)
![image](https://github.com/dotCMS/core/assets/64026161/02536119-884a-4228-8a14-49e02c84a940)
![image](https://github.com/dotCMS/core/assets/64026161/8a02028e-6154-4881-a7de-797b25d13389)

**Comment by bryanboza** [comment]
Fixed, tested on master /// Docker // FF and now it is working as expected.
