### ISSUE TITLE
Stopping a Scheduled Experiment needs to move it to Draft

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25095]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As an Experiments API User, I want to be able to End an Scheduled Experiment and have it moved to Draft. 

### Acceptance Criteria

* Upon call the _end_ endpoint on a Scheduled Experiment, it needs to move to Draft state. 
* Postman tests. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25105

**Comment by dsilvam** [comment]
Passing Internal based on tests results.

**Comment by bryanboza** [comment]
Fixed, now we are moving the experiment to draft after cancel the scheduling 

![Image](https://github.com/dotCMS/core/assets/2641437/2490be4b-d6ef-4b85-abb3-467a7ff8a34d)
