### ISSUE TITLE
Update Normalization Filter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25097]
### Problem Statement

We had a regression - urls with double slashes were no longer being blocked which allows access to protected resources.

### Steps to Reproduce

Without authentication, try to visit a backend url like https://demo.dotcms.com//html/images/star_on.gif.  This should not be accessible and result in a 404 without auth.

### Acceptance Criteria

block invalid requests

### dotCMS Version

22.03

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 1 - Show Stopper

**Comment by nollymar** [comment]
**Internal QA:** passed

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF 

We are getting a 404 now
![Image](https://github.com/dotCMS/core/assets/2641437/d0db42fc-406a-434d-9dcb-0e6e2a5e8eb4)
