### ISSUE TITLE
[UI] Allow cancel a Experiment in `SCHEDULED` status

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25108]
### Parent Issue
#24343

### User Story
As a user, I want to cancel a Scheduled Experiment

### Acceptance Criteria

- Add a secondary style button with the label `Cancel Scheduling` 
- The button to cancel the schedule is displayed when the Experiment status is SCHEDULED.
- Clicking on the `Cancel Scheduling`  button show a ConfirmPopup and if the user selects YES move the Experiment Status to DRAFT.
- Show a message after a `successful` saving of Experiment status. Title: Scheduled Experiment canceled, message: Experiment { NAME } canceled successfully.
- The canceled Experiment is no longer displayed in the scheduled Experiment list
- The endpoint to use is `/scheduled/{experimentId}/_cancel`
- Rename from `Stop Experiment` label to `End Experiment` when the Experiment has the status RUNNING

Blocked by: https://github.com/dotCMS/core/issues/25095

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Group 30](https://github.com/dotCMS/core/assets/1909643/05679d2a-fc10-4955-9e99-3b87a11fbbd6)

**Comment by dsilvam** [comment]
Passed Internal QA: Now there's an option to Cancel an Scheduled Experiment. When canceled it goes back to Draft state.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now we are able to cancel the scheduler experiments without problems
