### ISSUE TITLE
Favorite Pages: Fix Contextual Menu for Invalid Bookmark URLs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25114]
### Problem Statement
If a user edits a bookmark and changes the URL to an invalid one, the contextual menu in the card won't show.

### Steps to Reproduce
1. Log into dotCMS
2. Create a bookmark for a valid URL
3. In the card, click the contextual menu (three vertical dots)
4. Select "Edit"
5. Change the URL to an invalid one
6. Click "Save"
7. Try to open the contextual menu again
8. See the error

### Acceptance Criteria
- User should be able to see the menu in the bookmark card for "Edit" event when the bookmarked page URL doesn't exist

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
## Passed InternalQA

Docker Image: `[dotcms/dotcms:23.06_c2efd860_SNAPSHOT]`


### Screenshots
https://github.com/dotCMS/core/assets/63567962/ef72756f-94f4-43d9-a61b-c4cac0a5c4a5

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_92c6837e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
