### ISSUE TITLE
Stopped sites are not listed

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25120]
### Problem Statement

Stopped sites are not listed in the site selector.

### Steps to Reproduce

1- Create a new site
2- Only click Save

### Acceptance Criteria

Stopped sites should be listed in the site selector, only archived ones shouldn't be shown.

### dotCMS Version

23.01 LTS +
Demo (22.05)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111732

### Assumptions & Initiation Needs

From what I see the endpoint is not returning them 

```
api/v1/site?filter=*&per_page=15&archive=false
```

### Quality Assurance Notes & Workarounds

You would need to Start (Publish) the sites

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eecb137_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by erickgonzalez** [comment]
Doesn't apply to 22.03 LTS.
