### ISSUE TITLE
Pages - Block Editor - NPE 

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#25121]
### Problem Statement

When including a contentlet with a block editor field with empty value (not required) on a container, the page render of that container disappear because a NPE error

```
 WARN services.DotResourceLoader: filePath: /PREVIEW_MODE/65119febe0dc5eca4b9282f5d129a5be_1_DEFAULT.contentlet, msg:null @ url:GET//demo.dotcms.com/api/v1/page/render/direct | lang:1 | ip:38.25.183.2 | Admin:true | start:06-01-2023 12:04:36 UTC  ref:https://demo.dotcms.com/dotAdmin/  ?mode=PREVIEW_MODE
java.lang.NullPointerException: null
	at com.dotcms.rendering.velocity.services.ContentletLoader.buildVelocity(ContentletLoader.java:180) ~[dotcms_23.05_e3c7a96.jar:?]
	at com.dotcms.rendering.velocity.services.ContentletLoader.writeObject(ContentletLoader.java:653) ~[dotcms_23.05_e3c7a96.jar:?]
	at com.dotcms.rendering.velocity.services.DotResourceLoader.getResourceStream(DotResourceLoader.java:48) ~
	````

### Steps to Reproduce

1. Create a Content Type with a block editor field not required
2. Create a Content instance with a block editor as an empty value
3. Create a Container for the the particular Content Type previously created
4. Create a Template that includes the Container previously created
5. Create a Page based on the Template previously created
6. Add the contentlet previously created with a block editor saved as an empty value
7. Try to render, the whole container piece will be not rendered

### Acceptance Criteria

Even when the block editor contains an empty value, the rest of the container velocity should render and just return nothing on the velocity

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
This issue was reported for a client, so it will be good to be on the next LTS release

**Comment by jdotcms** [comment]
Reference to zendesk: https://dotcms.zendesk.com/agent/tickets/111588

**Comment by danielmdob** [comment]
Passed internal QA.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_3d7a559_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by waqasakramdot** [comment]
Another customer is hitting this. https://dotcms.zendesk.com/agent/tickets/112613

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS
