### ISSUE TITLE
[UI] Set the Y-axis legend of Chart to `Conversion`

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25122]
### Parent Issue
#24343

### User Story

As a user,
I want to view the correct label of the y-axis of chart.

### Proposed Objective
Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="988" alt="Screenshot 2023-06-02 at 1 01 27 PM" src="https://github.com/dotCMS/core/assets/1909643/3c4b626c-3f59-42fe-b29d-b3e1319bd20b">

**Comment by dsilvam** [comment]
Passed Internal QA: Showing conversions on the Y-axis

**Comment by bryanboza** [comment]
Fixed, now it is called conversions. Tested on master // Docker // FF
