### ISSUE TITLE
Show Edit Content Button for URLMapped Content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25125]
### Task

If you go to a page that has a urlmapped content in edit mode - it looks like you can edit the content.  The issue is that generally, if you click the edit button, it will take you to the widget for the detail page `.vtl`. This is not intuitive for content editors.  The workaround is to add the macro
```
#editContentlet($URLMapContent.inode)
```
somewhere in the display of the urlmapped content but this does not always happen.

Just like we do where there are nested vtls - we need to detect when there is a URLMapped piece of content and display a big edit content button somewhere on edit mode.  

The priority of this issue is somewhat more important now that we have the "Pages" screen which surfaces URLMapped content.

See screen recording.  I was only able to get to the URL mapped content because I just added the `#editContent` macro to the detail page vtl.

https://github.com/dotCMS/core/assets/934364/7f82fb99-8e19-4282-8bbe-dccd678ffde8

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

A user should be shown - somewhere on the page - a button that clearly indicates that they can click it and edit content.

**Comment by fmontes** [comment]
@jdotcms @freddyucv @jcastro-dotcms @rjvelazco we need to talk about this.

**Comment by fmontes** [comment]
Closing this because we are fixing it UX wide
