### ISSUE TITLE
Browse button on Create New Template form not spaced well and does not really look like a button. 

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25139]
[![Screenshot_2023-06-02_19-48-05.png](https://mrkr.io/s/647a4774517aa5709251182c/2)](https://mrkr.io/s/647a4774517aa5709251182c/0)

### Sub-Tasks & Estimates

---

**Reported by:** Scott Wicken (scott.wicken@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/templates/new/designer](https://demo.dotcms.com/dotAdmin/#/templates/new/designer)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/647a4774517aa5709251182f_2621ab3bcfd144c3?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 113.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3440 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.2.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1720 x 1225</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by wezell** [comment]
Dupe #23712
