### ISSUE TITLE
[UI] Add to the Goal list the `coming soon goals`

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25130]
### Parent
#24343 

### User Story
As a user, I want to see the coming next goals we are working

### Acceptance Criteria
Add 4 Goals as coming soon shown in the UI:
- Click on Element
- Time on site 
- Time on Page 
- Rules-based
### Proposed Objective

Core Features

### Figma

https://www.figma.com/file/fAoCk4swhiwplkU5GP21YD/Portlet-%2F-Experiments?type=design&node-id=1816-13266&t=Fr11ygR0L2UPaGMp-0

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="780" alt="Screenshot 2023-06-14 at 3 51 55 PM" src="https://github.com/dotCMS/core/assets/1909643/14ca76c4-828d-4c98-8771-b2e97286d998">

**Comment by victoralfaro-dotcms** [comment]
Verified the 4 coming soon goals
![image](https://github.com/dotCMS/core/assets/64026161/f962fbe3-b22b-4a80-85c7-f36da5ce41bd)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 


![Image](https://github.com/dotCMS/core/assets/2641437/cd738b63-c668-4273-88a1-c9b551c406c5)
