### ISSUE TITLE
Unable to edit VTL on a variant inside a Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25132]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

There's an error when a VTL is tried to be edited from a variant version of a Page inside an Experiment. 
This happens when using the Edit VTL button (code icon). 

### Steps to Reproduce

1. Create an Experiment on a Page with a VTL widget
2. Create a Variant
3. Try to edit the VTL widget on the Variant by using the "code" button

It will fail. 

### Acceptance Criteria

Editing the VTL via de edit code button works inside a Variant of the Page needs to work as expected. 

### dotCMS Version

master / 23.06 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
Also test the `#editContent($UrlMapContent.inode)` macro

**Comment by dsilvam** [comment]
Needs work: This is working only first time. Following attempts to save don't actually save.

**Comment by hmoreras** [comment]
Pass internal QA: Able to edit a vtl file in a variant. 


https://github.com/dotCMS/core/assets/31667212/a8ae79ad-5d19-41a9-b28c-da34a6d70e61

**Comment by bryanboza** [comment]
Fixed tested on master // Docker // FF 

Now I'm able to update the page variant without problems.
