### ISSUE TITLE
Site Browser is not sorting items by default

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25136]
### Problem Statement

When you navigate the first time to the Site Browser portlet the items of the selected folder aren't sorted by any column.

### Steps to Reproduce

1- Start dotcms with a full starter
2- Navigate to the Site Browser Portlet.
3- Go to `application/themes/landing-page`
<img width="1721" alt="Screenshot 2023-06-01 at 10 20 28 AM" src="https://github.com/dotCMS/core/assets/5278970/00cd0ef1-89af-4d9f-b6d0-1373fed52491">

### Acceptance Criteria

Should be sorted by modDate by default.

### dotCMS Version

22.03 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111604

### Quality Assurance Notes & Workarounds

Click on one of the column headers will sort them.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eecb137_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
