### ISSUE TITLE
dotCMS CLI: Improve error responses

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#25148]
**Parent Issue**
#24753 

To respond to erroneous requests, it is better to avoid sending the full stack trace; it is more elegant to respond with an entity containing the description of the error or set of errors, as the case may be.

For example, on `site remove` command, if you are going to remove a site, the site must be previously archived, on the other way you will receive the following message:

![Image](https://github.com/dotCMS/core/assets/29883881/f77b34c4-9908-4de3-bedf-366c43a8cc1e)

The full stack trace is not needed, this message is too hard for the user.

On the other hand, there are some cases where we return an error, but it would be clearer to return a warning, for example:

When we are going to create a new site with the `site push` command:

![Image](https://github.com/dotCMS/core/assets/29883881/274eb7a8-8be7-48cc-80fb-40a5939cb911)

Note that the final result of the operation is satisfactory, so there is little point in displaying an error message beforehand.

**Comment by nollymar** [comment]
We might want to display the stacktrace when a `-verbose` flag is enabled

**Comment by nollymar** [comment]
Closed in favor of #25582
