### ISSUE TITLE
Quarantine / Prevent ReDos Regexes 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25147]
### Problem Statement

We have customers who are using a number of Vanity URLs that contain regexes, some of which suffer from exponential backtracking and lead to site and server slowdowns and DDOS.

Here is an example customer ticket.  
https://dotcms.zendesk.com/agent/tickets/111806

Here is the discussion in Slack:
https://dotcms.slack.com/archives/G5VQBQ4H0/p1685727481560459

Here are some links that describe the problem:
https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

### Steps to Reproduce

Take this regex pattern `([a-z0-9\\-]*)*?$` and this String `abababababababababababab a`.  It takes more than 2 seconds to return `matcher.matches()` and is an example of catastrophic backtracking.

### Acceptance Criteria

We need to prevent and quarantine regexes that take over 2 seconds to match, especially when they are being used in vanity urls.

### dotCMS Version

23.05

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
PR: #25151

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested the basic functionality of Vanity URLs using the provided regex and seems everything is working as expected 

Tested on master // Docker // FF
