### ISSUE TITLE
Enable Experiments on Auth

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25149]
### User Story

We need to start testing Experiments and sending events with real traffic. Enabling Experiments on Auth is a good way to achieve this. 

### Acceptance Criteria

Experiments enable and ready to run on Auth. 
This implies having the Analytics infrastructure running and dotCMS properly configured to communicate to it. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
@dsilvam here is the log for access token and analytics key at auth.dotcms.com
```
dotcms-auth_1      | 05:31:32.362  INFO  analytics.AnalyticsAPIImpl - Forcing ACCESS_TOKEN refresh for clientId analytics-customer-customer1
dotcms-auth_1      | 05:31:32.365  WARN  network.IPUtils - unable to resolve hostname, assuming the worst:host.docker.internal unknown host
dotcms-auth_1      | 05:31:32.386  WARN  network.IPUtils - unable to resolve hostname, assuming the worst:host.docker.internal unknown host
dotcms-auth_1      | 05:31:32.409  INFO  analytics.AnalyticsAPIImpl - For clientId analytics-customer-customer1 found this ANALYTICS_KEY response:
dotcms-auth_1      | {"response":{"jsKey":"js.cluster1.customer1.kc6wh5dsag2txw2uos","m2mKey":"m2m.cluster1.customer1.8q0fuztlhtrth0f70"},"statusCode":200}
dotcms-auth_1      | 05:31:32.443  INFO  apps.SecretsKeyStoreHelper - KeyStore loaded successfully after `1` tries.
```
![image](https://github.com/dotCMS/core/assets/64026161/1f045b7d-bbd0-4a72-b231-c396393fd082)
![image](https://github.com/dotCMS/core/assets/64026161/1ffbbee9-a19c-4c01-828b-158dbca3b988)
