### ISSUE TITLE
[BE] url-param Metric/Goal for Experiments

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25156]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As a User of the Experiments feature, I want to be able to define a Goal based on a Metric that tracks if a given url-param either exists, or contains/equals a value, this after visiting the page of the Experiment. 

### Acceptance Criteria

This conversion counts when a given url-param meets one of the following conditions: 
* Exists
* Contains a value
* Equals a value

Also it needs to meet being present after visiting the page of the Experiment. 

* Automated tests required. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Backend PRS:

https://github.com/dotCMS/core/pull/25507

https://github.com/dotCMS/core/pull/25534

https://github.com/dotCMS/core/pull/25535

**Comment by oidacra** [comment]
Frontend PR: https://github.com/dotCMS/core/pull/25681

**Comment by bryanboza** [comment]
Fixed, tested via UI after the fix: https://github.com/dotCMS/core/issues/25598 and this is working fine
