### ISSUE TITLE
Fix Duplicated Sites in Apps Detail

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25169]
### Problem Statement
Users are finding that the app list is showing duplicate sites. 

### Steps to Reproduce
1. Open the app portlet
2. Click on any app
3. Click on "see more" button
4. See duplicated sites.

### Acceptance Criteria
- App list sites should not be duplicated

### External Links
None

### Assumptions & Initiation Needs
- The cause of the duplicated sites should be investigated

### Quality Assurance Notes & Workarounds
- A workaround may be to manually delete the duplicate sites from the app list

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF and I'm unable to reproduce 

Also, tested on the authoring server after upgrade and now we are not having duplicated sites
