### ISSUE TITLE
Advance template is missing the Publish button added to the template designer

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25174]
### Problem Statement

On the enhancement request here: https://github.com/dotCMS/core/issues/21612 we added a Publish button to the Template Designer, but we did not add the same Publish button to the Advanced Template editor

They should share the same capabilities here.

Related ticket: https://dotcms.zendesk.com/agent/tickets/111842

### Steps to Reproduce

1. Open the advanced template editor, there will be no Publish button

### Acceptance Criteria

1. Add a publish button to the Advanced Template editor

### dotCMS Version

23.05, 23.01 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

You can still publish the template by right clicking and clicking publish from the template list

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/26368

**Comment by erickgonzalez** [comment]
Only to 23.01 LTS, not master since template builder redesign.
