### ISSUE TITLE
[UI] New Goal `URL Parameter` to experiment

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25187]
### Parent Issue

#22455

### User Story

As a user,  
I want to create a new goal for Experiments called 'URL Parameter' so that I can detect a specific URL parameter submitted on any page.

### Acceptance Criteria
- Add the New Goal to the existing sidebar of `select goal`
- Name of the new goal: `URL Parameter`
-  Description of the new goal: `Detect a specific URL parameter submitted on any page`
- should include a required input field to enter the name of the query parameter.
- should have a required dropdown menu to select the operator, with options: `Exists`, `Contain`, and `Equal`
-  All the titles, descriptions, placeholders, and labels need to be translated

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Mocks
![Screenshot 2023-06-08 at 12 10 47 PM](https://github.com/dotCMS/core/assets/1909643/4b2b441c-084a-402e-b7da-4f2f53ebd453)

![Screenshot 2023-06-08 at 12 07 27 PM](https://github.com/dotCMS/core/assets/1909643/9decaae3-783f-4cb0-b283-9a2dd5dff38b)

**Comment by freddyucv** [comment]
Pass Internal QA: UI is working as expected also the request payload is the expected one

**Comment by dsilvam** [comment]
@oidacra  @hmoreras  Let's test whether the third input gets disabled when selecting the `Exists` operator
