### ISSUE TITLE
Data mixing issue when ordering values of Content Type with multiple key/value fields

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25189]
### Problem Statement

The current system is experiencing issues wherein the data of key/value fields within a content type. They become mixed up when attempting to order the values. This problem arises specifically when the content type contains two key/value fields.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/127987858/bc9c9b69-c5fb-48d6-9cbf-9ba8bb2ce7a5

### Acceptance Criteria

The sorting functionality should be applied to each key/value field independently, without mixing or altering the data between fields.

### dotCMS Version

23.01+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer ticket https://dotcms.zendesk.com/agent/tickets/111874

**Comment by erickgonzalez** [comment]
Another customer hitting this: https://dotcms.zendesk.com/agent/tickets/112022

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_dc3cb0b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
