### ISSUE TITLE
Unable to specify resample_opts - value not carried all the way down the method call

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25193]
### Problem Statement

When resizing images, we have the ability to send a parameter called `resize_ro` that takes an integer from 1 to 15 and specifies what resampling options should be used when downscaling the image.  The issue is that the final call to the `ImageFilterApiImpl` ignores the value passed in and sends the `DEFAULT_RESAMPLE_OPT` instead, which is a faster but worser algo called `bilinear` `3`.

https://github.com/haraldk/TwelveMonkeys/blob/master/common/common-image/src/main/java/com/twelvemonkeys/image/ResampleOp.java#L140-L214

This can result in some large images being resized looking jagged or rough.

It can be worked around by updating the configuration value for the default resizing algo to one that does not make images look jagged.
`DOT_IMAGE_DEFAULT_RESAMPLE_OPT=12 or 15`

### Steps to Reproduce

Call an image with a specific resample option value from 1 to 15.  You should be able to see big changes in the resized image qualities

## Here is a 1
https://local.dotcms.site:8443/contentAsset/image/d90e722b-988a-49f6-98dc-a317d55a8c8b/asset/filter/Resize/resize_w/800/resize_ro/1
![image](https://github.com/dotCMS/core/assets/934364/f2349baf-77c4-4f37-9a10-52b2eea690d2)

## Here is a 15
https://local.dotcms.site:8443/contentAsset/image/d90e722b-988a-49f6-98dc-a317d55a8c8b/asset/filter/Resize/resize_w/800/resize_ro/15
![image](https://github.com/dotCMS/core/assets/934364/b3334277-c897-4509-95cb-0bcf97e25967)

### Acceptance Criteria

be able to set the resample_ops

### dotCMS Version

23.06

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_f961f46_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
