### ISSUE TITLE
Template Builder: Implement Theme Selector

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25201]
### Problem Statement
The current template builder does not have a theme selector. We need to implement a theme selector in the template builder to allow users to change the look and feel of their templates.

### Steps to Reproduce
1. Navigate to the template builder.
2. Select the template you wish to edit.
3. Add a new component called “Theme Selector”
4. Create a new component and deprecate the old one that have some change detection issues.

### Acceptance Criteria
1. The look and field of the theme selector should be the same as right now.
2. The theme selector should allow users to change the look and feel of their templates.
3. The old component should be deprecated and a new one should be created to prevent any change detection issues.

### External Links
N/A

### Assumptions & Initiation Needs
It is assumed that the developers have the necessary knowledge and skills to implement the theme selector.

### Quality Assurance Notes & Workarounds
The developers should ensure that the look and field of the theme selector are the same as right now. The developers should also

**Comment by fmontes** [comment]
Let's fix the little UI stuff.

**Comment by fmontes** [comment]
![Image](https://github.com/dotCMS/core/assets/751424/0ff49b9c-e702-4efb-81b7-c6919349c290)

**Comment by zJaaal** [comment]
## Passed Internal QA

Tested on `master` branch

### Screenshot
https://github.com/dotCMS/core/assets/63567962/27231269-a7dd-4dbf-9aec-cb1a911374c2

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eb200d2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
