### ISSUE TITLE
getResizeUri Method Returns An Incorrect URL

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#25203]
### Problem Statement

When using the getResizeUri method to generate a URL for a resized binary image, the URI includes a double slash "//" before the width field.

### Steps to Reproduce

1. Create a content type with a binary field
2. Create a container for displaying this content type
3. Add the following code for displaying the content in the container
$dotContentMap.<name_of_binary_field>.getResizeUri(1000,800)
<img src="${dotContentMap.<name_of_binary_field>.getResizeUri(1000,800)}" />
4. Add the container to a template
5. Create a page that uses the template
6. Add content to the page
7. The page should now display the resize URI and the image. The resize URI has two slashes "//"

### Acceptance Criteria

Remove one of the slashes returned by the getResizeUri method

### dotCMS Version

23.01.2

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111880

### Quality Assurance Notes & Workarounds

When using a relative path, the image using the resize URI does not load.
When using an absolute path, the image using the resize URI does load.

**Comment by erickgonzalez** [comment]
Need to include this since it will break because of https://github.com/dotCMS/core/issues/25097
