### ISSUE TITLE
Favorite Pages: Bookmarks List Does Not Open From Default Collapsed View

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25211]
### Problem Statement

The bookmarks list does not open from its default collapsed view. This issue prevents users from viewing their bookmarked items when they are added to the list

### Steps to Reproduce

1. Open the application
2. Navigate to the bookmarks list
3. Add bookmarks to the list from the default collapsed view
4. Observe that the list does not open

### Acceptance Criteria

The bookmarks list should expand when the user interaction from its default collapsed view, allowing users to view their bookmarked items.

### dotCMS Version

23.06

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

Attached a video for reference

https://github.com/dotCMS/core/assets/129882031/cae22faf-fbb0-4609-9464-03dbab5be750

**Comment by josemejias11** [comment]
According to @wezell this is bydesign.

**Comment by fmontes** [comment]
Done by design.
