### ISSUE TITLE
New method of generating shorty IDs to include the language ID is creating issues with static PP

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25217]
### Problem Statement

We recently updated the shorty URL generator in the binary map to generate using the language ID:
https://github.com/dotCMS/core/blob/b03cc053c90e60ee33ea6a390ddd8bc24b28715c/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/content/BinaryMap.java#L127

This is necessary for multi-lingual files, however it is causing issues with static push publishing. When you static push, the site is rendered and the filename is taken from the rendered HTML. We are now pushing with the language ID included. On S3 buckets this is causing some issues with URI encoding, resulting in 404s for some images.

Related ticket: https://dotcms.zendesk.com/agent/tickets/111404

### Steps to Reproduce

1. Create a Content type (testCt) with a title and a binary field (let's called image).
2. Create new content for the created content type
3. Create a new page and add the following code:
```
#foreach($con in $dotcontent.pull("+contentType:TestCt +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +variant:default",10,"modDate desc"))
$con.image.shortyUrl </br>
#end
```
4. Language is appended to the URL.
5. Set up an Static Push
6. Push that page.

The image will have `?language_id=1` in its name.

### Acceptance Criteria

The file cannot be pushed with query params as part of the name, which means finding a way to make it not render with query params as part of the name when generating the page in a static context

### dotCMS Version

Master, 23.01

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsolistorres** [comment]
PR: https://github.com/dotCMS/core/pull/25255

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_cce8853_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
