### ISSUE TITLE
Get Error on Log when try to Publish a Template that have the SYSTEM_CONTAINER 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25219]
### Problem Statement

When Add the SYSTEM_CONTAINER inside a Template and try to publish it, we are getting the follow error on the log

https://gist.github.com/bryanboza/0bce95597d72c586893cf3d60285fa7e

it seems like everything is working right anyway

### Steps to Reproduce

- Create a new Template.
- Add the SYSTEM_CONTAINER.
- Try to publish the Template.
- Check the Log File.

### Acceptance Criteria

We must not get any error on the Log

### dotCMS Version

Release 23.06, but I suppose that it is happening in the latest in master too

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_f30e8d2c_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
