### ISSUE TITLE
We are not cleaning the cache Page correctly

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25221]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

Right now we are cleaning the Page Cache when any change come over the Page, but we are cleaning this Cache using the MultiTree of the page but a Page can be render on any Variant even when it does not have any MultiTree specific for that Variant (it is render by fallback but the Cache is full with the result).
Maybe we need to clean up the Page's Cache for all the existing no archived Variants

### Steps to Reproduce

Pending

### Acceptance Criteria

The cache must be clean for all the Variant where the Page was render no matter the existing MultiTree 

### dotCMS Version

Lates in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
I fixed to issue with this PR:

Steps to reproduce

First Case:

- Create an Experiment, Create a Variant
- Add a Contentlet in the Variant Version
- Change the Variant Version Layout.
- You must keep the Contentlet added before inside the Variant (We was losing it before the Change)


Second Case:

- Create an Experiment, Create a Variant
- Add a Contentlet in the DEFAULT Variant
-Go to view the Variant Version you should see the recently added Contentlet

This behavior proof that we are cleaning the cache of the Variant when the Default was changed, but in the future we are going to change this behavior    https://github.com/dotCMS/core/issues/25590

**Comment by dsilvam** [comment]
Passed Internal QA: both cases working as stated in the comment above.

**Comment by bryanboza** [comment]
Fixed, tested based on the cases commented above and both are working now, new card related this reported here #25545
