### ISSUE TITLE
PP - Integrity Checker, fixing conflicts is setting up identifier columns as null

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25224]
### Problem Statement

The asset_subtype, create_date, and owner fields is being set to null when fixing conflicts with the Integrity Checker.

### Steps to Reproduce

1. Start two dotCMS instances, and set the PP.
2. Publish a picture on the root folder of the sender instance and a different picture on the root folder of the receiver instance
3. Rename the file on the receiver to the same name as the one on the sender
4. Run the Integrity Checker.
5. It should generate a conflict.
6. Use the following query to verify that the asset_subtype is set: `select * from identifier where id = 'IDENTIFIER'`
7. Fix the conflict with IC.
8. Clean cache.
9. Run again the query to verify that the asset_subtype is set (actually the value is being set to null): `select * from identifier where id = 'IDENTIFIER'`

### Acceptance Criteria

The asset_subtype, create_date, and owner fields should not be set to NULL when the conflict is fixed.

### dotCMS Version

23.01 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Note to QA/Dev:

This should also apply to everything that is content meaning (host, pages, file assets)

**Comment by erickgonzalez** [comment]
another customer hitting this https://dotcms.zendesk.com/agent/tickets/112304 in 22.03.7 LTS

**Comment by bryanboza** [comment]
Fixed, tested on release-23.07 // Docker // FF
