### ISSUE TITLE
Unable to run Experiment when a new version of the page is created

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25222]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

Where a new Variant of the Page is created and changes are made to it, like adding new content, it fails to Run the Experiment showing an error on a system dialog. 

### Steps to Reproduce

1. Create an Experiment 
2. Add a Variant and add a new or existing Content to it
3. Set a goal
4. Attempt to Run the Experiment

You will get a Dialog with the error saying that is not possible to start the Experiment. 

### Acceptance Criteria

The Experiment needs to be able to Start given the steps above. 

### dotCMS Version

master / 23.07 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
**Pass Internal QA:** Working right now

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the last master // Docker // FF
