### ISSUE TITLE
Template Disappearance and Anonymous Renaming After Sequential Edits in 'Browser' and 'Templates' Portlets

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25227]
### Problem Statement

After creating a new template and modifying it via the 'Browser' and 'Templates' portlets, the template's name changes to 'anonymous xxxxxx', and then disappears completely from the list. This issue prevents further editing or use of the created template and introduces unexpected behavior.

### Steps to Reproduce

1. Open the application
2. Create a new template and save changes
3. Navigate to the 'Browser' portlet
4. Create a new page, save changes, and edit the previously created template using the 'Edit --> Layout' option
5. Navigate to the 'Templates' portlet
6. Edit the newly created template and save changes
7. Observe that the template's name has been changed to 'anonymous xxxxxx'
8. Edit the newly renamed template and save changes
9. Observe that the template disappears from the list

### Acceptance Criteria

The template should persist in the list, retaining its original name after any edits, for further use or editing.

### dotCMS Version

23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

Attached the video reference 

https://github.com/dotCMS/core/assets/129882031/9b93040f-12b9-4389-989a-1e8eb97228e0

**Comment by freddyucv** [comment]
**Note to QA**: we need to make sure that the follow rules are meet

- When a Template is created in the Template Builder is not a Anonymous Template.
- If you are using a not Anonymous Template on just one Page, and change something using the Page Layout then the Original Template is changed.
- If you are using a not Anonymous Template on more than one Pages, and change something using the Page Layout then the Original Template is copied and a Anonymous Template is created.
- I the Page is already using an Anonymous Template and we change the Layout then a new version of the Template is created.

**Comment by dsilvam** [comment]
Passed Internal QA: Keeping the original name and being able to modify it exactly as the video shows and still is listed.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eecb137_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
