### ISSUE TITLE
[UI] Handle the size of the inline inputs

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25239]
Handle the jump of the UI when you edit Inline an input when:
- Edit inline a description of the experiment
- Edit inline the name of a variant
- Edit the Traffic split values.

Expected behavior

- In edit description: When the description's edit icon is clicked, the height of the input should not move/push the existing UI.
- When you Edit a Variant Name: When the variant`s name edit icon is clicked, the height of the input should not move/push the existing UI below or above.
- When you edit a Traffic Split from Evenly to Custom, the height of the input should not move/push the existing UI below or above.

### Experiment Description and Variant Name
https://github.com/dotCMS/core/assets/1909643/9de5ba15-d9a2-4647-8e3c-53b7c8b2284e

### Traffic split 
https://github.com/dotCMS/core/assets/1909643/62d7a19d-d40b-46c5-b7f4-57f64bc2ec69

**Comment by hmoreras** [comment]
Passed Internal QA : There is no "jump" when editing the fields. 

https://github.com/dotCMS/core/assets/31667212/1fcd3fb1-8548-48cb-aaa7-72ce588f36e6

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
