### ISSUE TITLE
Block Editor Search not working for special chars

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25230]
### Problem Statement

When looking for a contentlet/image/video that in the file name contains special chars, when you type one of these nothing is returned.

### Steps to Reproduce

1- Go to any Blog
2- Add a new block
3- Select Image
4- Type `shark`
5- You'll see some images named `shark-feeding`
6- Type `shark-`
7- Nothing is returned

### Acceptance Criteria

Block Editor searches should allow special chars.

### dotCMS Version

23.01 and demo (23.05)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111992

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS

**Comment by danielmdob** [comment]
Passed internal QA.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_c08f900_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
