### ISSUE TITLE
[UI] Add Promote variant to Summary Table

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25231]
### Parent Issue

https://github.com/dotCMS/core/issues/22455

### User Story

As a user, 
I want to add a column in the Summary table with a button by variant to promote the selected variant' row.

### Acceptance Criteria

- Remove the same functionality from the header ( Button and Modal)
- When viewing the Summary table, I should see a new column with a button labeled "Promote."
- Clicking on the "Promote" button should trigger a Confirmation Popup to continue with the action.
- When the action is successful, show a message about it.
- When the variant is already promoted, show a Tag of 'Promoted' and all the buttons of "Promote" disabled
- The Default variant can not be promoted.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
[FIGMA](https://www.figma.com/file/fAoCk4swhiwplkU5GP21YD/Portlet-%2F-Experiments?type=design&node-id=3508-25520&t=cJGHcYBrM2K6YcRq-4)

### Before promote
<img width="1157" alt="Screenshot 2023-06-15 at 12 02 00 PM" src="https://github.com/dotCMS/core/assets/1909643/d5cdae0e-a2a6-4d49-a58a-d5ebd36e8df8">

### ConfirmPopup
<img width="483" alt="Screenshot 2023-06-14 at 12 38 52 PM" src="https://github.com/dotCMS/core/assets/1909643/1365f88b-6f12-49a0-801d-bd23df8b8eea">

### Promoted state

<img width="1136" alt="Screenshot 2023-06-15 at 12 02 20 PM" src="https://github.com/dotCMS/core/assets/1909643/123062a6-5c01-494d-8940-0fe28cfaae41">

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25263

**Comment by victoralfaro-dotcms** [comment]
Verified in `dotcms/dotcms:master_8fff3a7_SNAPSHOT`
Summary table
![image](https://github.com/dotCMS/core/assets/64026161/0ce36af2-3f44-4ed9-a430-07ac2c6ab8f2)
Removed from header
![image](https://github.com/dotCMS/core/assets/64026161/d7eb42a5-d9df-4951-af58-2608dda8ece3)
Dialog modal after clicking `Promote`
![image](https://github.com/dotCMS/core/assets/64026161/29e5cad5-f8c0-425e-96a0-f350267d8886)
Summary table with tag
![image](https://github.com/dotCMS/core/assets/64026161/fdb426ae-1ffb-41f4-9eaf-038c05169ecc)

**Comment by bryanboza** [comment]
Fixed, tested at UI level and now this is working as expected.
