### ISSUE TITLE
We need to support load a Image by Identifier inside a Variant

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25238]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

If we have a Content with the follow code:

```
<div class="banner bg-image-full bg-overlay-30 context-dark" style="background-image: url('/dA/$!{ContentIdentifier}/image/1200w/50q/$!{imageBinaryFileTitle}');">

...
</div>
```

This is not going to work if we try to render this Content inside a No DEFAULT Variant because right now we are handle the currentVariant just in Browser side and we sent it as a Query Params when we need to use it on Backend, for example when we Edit a Contentlet, but in this case we don't have any control of this code because it is a User Code so we can not include the Query Params there.

In short we need a way to use the current Variant value in this case.

A possible solution could be use the referer header as a second level when we try to get the current Variant, so it is going to be something like:

- If the variantName Query Parameter  exists the use it as the current Variant.
- If not then check the referer Header if the Query Params exists there then take it as Current Variant.

We can use a WebInterceptor  that fires on `/dA` and `/contentAsset` and set the CurrentVariant as a Request attribute.

I am not sure if this solution is going to work on BE, so we need to implemented a different second level in this case maybe use a "flash" session variable with a expire time. 

### Steps to Reproduce

- Start dotCMS using the full starter.
- Create a Experiment using the /index page.
- Create a Variant and Edit the 'Explore the World' Content, and change the Image.
- Even when the Image is saved correctly, you are still going to see the old image render on the Page even when you are inside the Variant.

### Acceptance Criteria

We must support the use of Identifier inside the image URL.
Also check if this kind URL work as well: /dA/${dotContentMap.identifier}/image/1200w/50q/$dotContentMap.image.name

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
IQA using `master_a34f8e2_SNAPSHOT`
Edit mode for `/index` page
![image](https://github.com/dotCMS/core/assets/64026161/94ad1a20-91e2-4cc3-a525-31aa3b0c4074)
Preview for the same page
![image](https://github.com/dotCMS/core/assets/64026161/ac1822df-d6f8-4197-8bd5-23f95c466dae)
Serving original:
![image](https://github.com/dotCMS/core/assets/64026161/27a33461-343d-41f1-b34b-33dd3a816931)
Serving variant:
![image](https://github.com/dotCMS/core/assets/64026161/46916073-016e-4c2b-8b73-ec42063971cb)

**Comment by victoralfaro-dotcms** [comment]
Testing VTL image path edition with this value: 
![image](https://github.com/dotCMS/core/assets/64026161/06d62876-4c39-45f7-831b-45476015a09b)
Preview of index page
![image](https://github.com/dotCMS/core/assets/64026161/c60f0a6d-57ef-4737-88ea-c14663e11e10)
FE served page:
![image](https://github.com/dotCMS/core/assets/64026161/f82579d8-3d23-41a1-b1ba-135d5c7b225f)
Adding variant:

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
