### ISSUE TITLE
sysPublishDate no longer appears to be part of the ElasticSearch object we create for indexing

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25233]
### Problem Statement

The sysPublishDate field is no longer returned on contents from the `$dotcontent` object and you can no longer query against it. 

This is listed here as a default field on all content: https://www.dotcms.com/docs/latest/how-content-is-mapped-to-elasticsearch#SystemUniversal

Related ticket: https://dotcms.zendesk.com/agent/tickets/111634

### Steps to Reproduce

1. Start up dotCMS with demo content
2. Save/Publish one of the products in the Products content type
3. Go to the velocity playground viewtool
4. Run this code
```
#set($now = $date.format("yyyyMMddHHmmss", $date.getDate()))
## Get a Java Calendar Object
#set( $cal = $date.calendar )
## Add 24 hours (int code 10)
$cal.add( 12, -30 )

#set($halfHourAgo = $date.format("yyyyMMddHHmmss", $cal.time))
#set($products = $dotcontent.pull("+contentType:Product +modDate:[$halfHourAgo TO $now]", 10, ""))

#foreach($product in $products)
$product.modDate
#end
```

This will return 1 products modDate

5. Then, run this code
```
#set($now = $date.format("yyyyMMddHHmmss", $date.getDate()))
## Get a Java Calendar Object
#set( $cal = $date.calendar )
## Add 24 hours (int code 10)
$cal.add( 12, -30 )

#set($halfHourAgo = $date.format("yyyyMMddHHmmss", $cal.time))
#set($products = $dotcontent.pull("+contentType:Product +sysPublishDate:[$halfHourAgo TO $now]", 10, ""))

#foreach($product in $products)
$product.modDate
#end
```

Nothing will be returned.

You can also look at any resulting object to see there is no sysPublishDate returned on them. You can still see a publish date from the content API.

### Acceptance Criteria

1. You should be able to query by publishDate
2. You should be able to access the publish date on the resulting object 

### dotCMS Version

23.01, 23.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111634
https://dotcms.zendesk.com/agent/tickets/113030

**Comment by erickgonzalez** [comment]
Lets test:
- Query content using sysPublishDate.
- Publish date should be accessible in the content object.
- If you publish content and then unpublish, the publish date must be empty.
- PP must send the publish date.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_39ca5c4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
