### ISSUE TITLE
Unable to read svg width and height

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25247]
### Problem Statement

Our svg handling is subpar - because we have been relying on ImageReaders to get the width and height of an SVG and it fails.  This prevents us from being able to generate thumbnails for example.

### Steps to Reproduce

To test, upload the following svg image file in dotCMS

![solr](https://github.com/dotCMS/core/assets/934364/8eafedcc-072a-4bb9-88fe-9d0a5d425ded)

---
In the listings, this is what we see:
![Screen Shot 2023-06-15 at 2 28 21 PM](https://github.com/dotCMS/core/assets/934364/3a578abc-5081-4785-b85a-d8690adaf136)

----
And this is what we have in the metadata:

![Screen Shot 2023-06-15 at 2 28 10 PM](https://github.com/dotCMS/core/assets/934364/4e2a95b6-302d-4490-95c1-7b7293723b31)

### Acceptance Criteria

We should be able to get a good thumbnail and image size data for SVGs.

### dotCMS Version

23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Internal QA:** passed

<img width="1518" alt="Screen Shot 2023-06-30 at 10 06 42 AM" src="https://github.com/dotCMS/core/assets/8741395/01ea6d81-8f25-4a2b-bd30-c5d48792f9ba">
<img width="1677" alt="Screen Shot 2023-06-30 at 10 06 35 AM" src="https://github.com/dotCMS/core/assets/8741395/388907ab-6313-4b90-82ec-81f03f283303">

**Comment by bryanboza** [comment]
We need some work here: 

After test using the same image on docker we are able to upload the file without problems, but after you upload it, and go back to content search, we are getting the follow error trying to generate the thumbnail. 

https://gist.github.com/bryanboza/db5151246bb6b8605e1031de8abbf1ee

Tested using the last docker image of master.

**Comment by bryanboza** [comment]
We still having problems here, after upload this image and try to edit using the image editor, we are getting the error again and we are unable to generate the thumbnail 
Error: 
```
testing_pg-dotcms-1         | 22:49:07.531  ERROR servlets.BinaryExporterServlet - [BinaryContentExporterException] An error occurred when accessing '/image/4152bd8c-3c88-4fd9-b420-5fc8524d441d/fileAsset/byInode/true/resize_w/256/quality_q/20': unable to parse svg file: /data/shared/assets/4/1/4152bd8c-3c88-4fd9-b420-5fc8524d441d/fileAsset/test.svg : Invalid byte 1 of 1-byte UTF-8 sequence.
```


![Image](https://github.com/dotCMS/core/assets/2641437/24ef4bfe-964a-47b4-a293-bc96fd1db598)

**Comment by nollymar** [comment]
@bryanboza what version are you using to test? 
It is working in demo site that is running 23.07

<img width="1678" alt="Screen Shot 2023-07-20 at 8 09 44 PM" src="https://github.com/dotCMS/core/assets/8741395/24c9aa93-6021-4213-893b-7929d3b33f31">

**Comment by bryanboza** [comment]
As I mentioned in the previous comment to reproduce you need to edit this image using the image editor. 

Steps to reproduce: 
- Login as admin 
- Upload a new image 
- Open it and edit using the image editor
- Apply any filter (grayscale) and save it 

Tested with the last master image // Docker // FF

**Comment by nollymar** [comment]
A new PR was sent to fix the thumbnail for the case @bryanboza reported

**Comment by bryanboza** [comment]
Fixed, based in the previous comment we can pass this one and now move to the new card.
