### ISSUE TITLE
The Show Preview button show render the page in PREVIEW MODE

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25243]
### Problem Statement

When you click the "Show Pewview" button on the Edit Page Portlet it is open a new windows and render the Page in LIVE MODE, we need to open it on LIVE MODE

### Steps to Reproduce

- Start dotCMS with the full starter.
- Open any Page and make any chance, save it but don't publish
- Click the Show Preview button, you are going to get the LIVE Version of the page

### Acceptance Criteria

You must go the Working version on the page

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Showing preview mode instead of Live.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_78d179c2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

Not in **master**

**Comment by josemejias11** [comment]
Hi @erickgonzalez,

Please see;

https://github.com/dotCMS/core/assets/129882031/2d6dc857-4ff8-4865-b5bf-48ffcc1de039

**Comment by freddyucv** [comment]
> Hi @erickgonzalez,
> 
> Please see;
> 
>  Screen.Recording.2023-06-22.at.8.52.31.AM.mov

That is the expected behavior

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_86f6fb2b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
