### ISSUE TITLE
Cannot remove more than one bookmark from Pages Tool per visit

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#25240]
### Parent Issue

https://github.com/dotCMS/core/issues/22343

### Problem Statement

If you set multiple bookmarks, and then try to remove them, only the first removal will go through. In order to remove another, you need to reload the Pages tool.

### Steps to Reproduce

1. Spin up a local version of 23.06 with Demo starter
2. Go to Site -> Pages
3. Select 4-5 pages for bookmarking
4. Expand bookmarks accordion view
5. Remove one bookmark
6. Now try to remove another bookmark
    - Nothing will happen
7. Browse to a different portlet and then back to Pages 
8. You can now remove a second bookmark
9. Attempting to remove a third bookmark will fail.
10. Return to step 7.

### Acceptance Criteria

An arbitrary number of bookmarks should be able to be added or removed at any time.

### dotCMS Version

23.06

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
