### ISSUE TITLE
Can't create new Layouts

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#25253]
### Problem Statement

New layouts are now replacing the original template and then all subsequent layouts are not created.

Here is video:

https://github.com/dotCMS/core/assets/1569167/2f6dc728-4803-4a67-8d0a-5e89262fe834

### Steps to Reproduce

Startup 23.06 and create a new page and adjust the layout of a page that is using a template.  Make sure that the page properties then say, "custom layout".  Go back and look at templates - the original template is replaced with the layout name - this is a bug.  Secondly, create a secondary template and new page and try to create a different layout on that new page.  All new layouts are disabled.

### Acceptance Criteria

Saving layouts should never save over or change a template.  Many layouts for many pages should be allowed.

### dotCMS Version

23.06

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

### Quality Assurance Notes & Workarounds

Only work around is to create new templates instead of layouts.

**Comment by wezell** [comment]
dupe: #25227
