### ISSUE TITLE
Favorite Pages: Minor issues/cleanup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25251]
### Problem Statement

Bookmarks are looking good.  There are a few minor issues that need addressing.

- [x] We need to add an `X` icon in the search box to the right to clear the existing search
- [x] The bookmarks need a mouseover/hover state change to show that they are selected (blue border / border blur / lift off page or something)
- [ ] ~When you visit a page, the main nav section closes.  It reopens if you click on "Pages" in the crumbtrail.  It does not do this when using the browser.  I wonder if we should get rid of the "auto-close" on the nav and only have "auto-close" if you click on one of the nav links.~
- [x] Exiting out of a content modal takes you back to the content search - like if you click create a page, pop the content window, close the content window.
- [x] On the bookmark query, the order jumps around as you publish/unpublish pages- we need to use this as the query order: `dotFavoritePage.order ASC, identifier` so that it is more fixed.
- [ ] When a workflow executes on a page or whatever, we do not update the screen listing.  I think we need something like we use on the contentsearch and refresh the listing after 5s so it looks like things are working.
- [ ] We need the starter to come with a few bookmarks.  I added some, we just need to generate a new starter.
- [x] The bookmark panel jumps on search pages. Needs to do something in the height.
- [x] Allow to create contentlets from `/pages/new/CONTENT_TYPE`

### Steps to Reproduce

none

### Acceptance Criteria

Fix the above issue.

### dotCMS Version

23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by rjvelazco** [comment]
### Failed Internal QA

Steps to Reproduce:

1. Go to `pages`
2. Click on `Create Page`
3. Create a `blog` and `save and publish`.
4. Click on `Create Page` again.
5. Try to create a new `blog`. 
6. See the error.

https://github.com/dotCMS/core/assets/72418962/7b689740-6919-42bf-a7d0-348ba990bc49

**Comment by fmontes** [comment]
>  When a workflow executes on a page or whatever, we do not update the screen listing. I think we need something like we use on the contentsearch and refresh the listing after 5s so it looks like things are working.

We need to do this... basically is refresh the list of pages when a workflow is triggered inside the iframe.

**Comment by fmontes** [comment]
Final fix: when user triggers a a workflow in the edit contentlet the page list under needs to updated.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_cce8853_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
