### ISSUE TITLE
Add a button to save a custom page layout as a Template

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#25268]
### User Story

As a page builder, I want to know that time I spend building a Layout (instead of a Template) won't have been wasted if I later decide I want to reuse said Layout. 

### Acceptance Criteria

Adding a button to Save Layout as Template would solve this problem, and make clearer how the two categories relate to one another.

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### Assumptions & Initiation Needs

Between the Page API's ability to fetch a Layout, the Template API's ability to publish a template, and the common ground Layouts and Templates share in the `body` property, it seems trivial to convert a Layout into a Template headlessly. This would just grant that same power to traditional UI users.

There are some design decisions that would need to be made — mostly, would this be better on the Layout Designer, or the Page properties, near the Template selector? Etc. (Or both?)

**Comment by fmontes** [comment]
Move to airfocus
