### ISSUE TITLE
Remove “LIVE” Tab

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25275]
### Task

Remove this from the Page Preview Navigation Menu.

<img width="651" alt="image" src="https://github.com/dotCMS/core/assets/114953617/8eeec4fc-6078-475e-ad36-bae4208f76cf">

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=428-13060&t=n7GFPgGsVyiLrLsH-0

**Comment by nollymar** [comment]
**Internal QA:** Passed

This works once you enable the feature flag `DOT_FEATURE_FLAG_SEO_IMPROVEMENTS`

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_524e70e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
