### ISSUE TITLE
Remove “Show Preview” Link

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25274]
### Task

Remove this from the Page Preview Top Navigation Menu.

<img width="650" alt="image" src="https://github.com/dotCMS/core/assets/114953617/ab8f3357-eeeb-4519-b16e-13e2b5e356c7">

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=428-13060&t=n7GFPgGsVyiLrLsH-0

**Comment by nollymar** [comment]
**Internal** QA: Passed

After enabling the flag FEATURE_FLAG_SEO_IMPROVEMENTS, the Show Preview link didn't show anymore:



![Image](https://github.com/dotCMS/core/assets/8741395/ac9cc372-68ca-419b-965d-a9b6ac840d27)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. 

After enable this feature flag we are removing this link.
