### ISSUE TITLE
Move “What’s Changed” Checkbox to Right Side

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25279]
### Task

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=428-13060&t=n7GFPgGsVyiLrLsH-0

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

**Comment by bryanboza** [comment]
Fixed, tested on master  // Docker // FF
