### ISSUE TITLE
Ensure Preview Uses Correct Sizes for “User Defined” Devices

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25277]
### Task

Currently the dimensions that a user sets get modified; the fake tablet or phone wrapper should not interfere with the size the user has set. This makes it so people have to guess to get the real size of a phone to show up; we need to make it more predictable.

<img width="618" alt="image" src="https://github.com/dotCMS/core/assets/114953617/7d401d02-e34b-4ac9-941b-35430ac5596c">

<img width="272" alt="image" src="https://github.com/dotCMS/core/assets/114953617/56e6860d-d932-4bcf-ae1f-72b0ad92535f">

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

**Comment by nollymar** [comment]
Implemented on #25815
