### ISSUE TITLE
Change “Edit” Button Behavior to Always Open “Standard” View

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25278]
### Task

Currently, when you hit "Edit" it takes you to Edit Mode based on what is selected in the Device Preview.

Going forward, no matter what preview screen or device a user has selected, when they hit edit they should always be taken to the “standard” edit screen. 

If a user wants to edit on a smaller screen they can simply adjust their browser width. But editing on a small screen is not an action we want to encourage, as many users aren't fully aware of how responsive design works and think that what they edit will only edit the "iPhone version" and not the overall version.

<img width="620" alt="image" src="https://github.com/dotCMS/core/assets/114953617/c4b27e7e-eab3-40e7-9c18-e0636d0930e3">

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

**Comment by nollymar** [comment]
I was trying to recreate the issue, but I couldn't. I was able to reproduce it easily a few months ago but now I can't. 

I don't have the track of changes that could have fixed it.

**Comment by bryanboza** [comment]
I'm able to reproduce on the last master, we need some work here 

https://github.com/dotCMS/core/assets/2641437/c56dc9f8-6ee5-4ada-aefb-0a829df655d6

**Comment by dcolina** [comment]
Internal QA: Needs work.

I found an issue testing [this](https://github.com/dotCMS/core/issues/17332) 

https://github.com/dotCMS/core/assets/29883881/74a15b28-2c46-4b5b-b4bb-beadc6632744

Step by step:
```

1. Create a new device
2. Create a new page
3. Select viewing using the new device
4. Edit
```

**Comment by nollymar** [comment]
I couldn't reproduce the last issue reported by @dcolina . He tested again following the same steps and he couldn't either.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_226a23f_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
