### ISSUE TITLE
Depreciate certain ciphers

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#25285]
### Parent Issue

https://docs.google.com/document/d/1DY6cHWRQ0tBE9PMXNvs58I2k2DAA95AoECILa7HF5LY/edit?usp=sharing

### Problem Statement

See: https://docs.google.com/document/d/1DY6cHWRQ0tBE9PMXNvs58I2k2DAA95AoECILa7HF5LY/edit?usp=sharing

### Steps to Reproduce

https://docs.google.com/document/d/1DY6cHWRQ0tBE9PMXNvs58I2k2DAA95AoECILa7HF5LY/edit?usp=sharing

### Acceptance Criteria

https://docs.google.com/document/d/1DY6cHWRQ0tBE9PMXNvs58I2k2DAA95AoECILa7HF5LY/edit?usp=sharing

### dotCMS Version

Site issue.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
These are not being used in our cloud environments (dotCMS.com is hosted separately).

**Comment by mbiuki** [comment]
@wezell - if this only is for dotCMS.com and so that site is hosted differently and so it is not a concern to our product, let's close this ticket, thanks.

**Comment by wezell** [comment]
We added an ALB in front of dotCMS so I think this issue is moot.
