### ISSUE TITLE
Build New Social Media Tile Preview Tool for Twitter

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25288]
### Task

Build New Social Media Tile Preview Tool for Twitter

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

See notes here:

* Social Media Tile & Search Engine Results Page Preview Tool Messages | dotCMS - Google Docs || https://docs.google.com/document/d/1O8PMni7FzD9YmIHdz-De43MnHpO--0_W49ZwYxLt9DM/edit

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=298-6800&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190 

Design - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-6961&t=kzAG714FzCpMdHYC-0 

Sanity Check Requirements - https://socialsharepreview.com/?url=https://dotcms.com

**Comment by dcolina** [comment]
Internal QA: Needs work.

*twitter:card*

When the tag exist but is empty.

`<meta name="twitter:card"  />`

The expected message `twitter:card meta tag found, but is empty! ` it is not shown.


![Image](https://github.com/dotCMS/core/assets/29883881/9d95f360-3e7c-421d-bf9a-bd26b1304d4a)

**Comment by nollymar** [comment]
Fixed on #26388

**Comment by dcolina** [comment]
Internal QA: Needs work.

**twitter:card**

*Case 1:*

When `twitter:card` is found twice.

```
<meta property="twitter:card" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
<meta property="twitter:card" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
```

The expect message `More than 1 twitter:card meta tag found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/286b050c-2f19-4f84-9a0b-2dcc49684044)

*Case 2:*

When `twitter:card` is found, but is empty.

`<meta property="twitter:card" >`or `<meta property="twitter:card" content="">`

The expected message `twitter:card meta tag found, but is empty!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/914262ed-fb74-4112-b6c4-b22256383539)


**twitter:title**

*Case 1:*

When `twitter:title` and `og:title` and `meta tag title` not found.

The expected message `twitter:title meta tag not found, and HTML Title not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/f180479c-3486-4e41-bf2e-5fe2ac3d4c57)

*Case 2:*

When `twitter:title` is found twice.

```
<meta property="twitter:title" content="TWITTER TITLE LOREM IPSUM. is longer enough.">
<meta property="twitter:title" content="TWITTER TITLE LOREM IPSUM. is longer enough.">
```

The expected message `More than 1 twitter:title meta tag found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/9b884c01-5ff2-4361-b684-ff3628a8ec1a)

*Case 3:*

When `twitter:title` is found, but is empty.

`<meta property="twitter:title" >` or `<meta property="twitter:title" content="">`

The expected message `twitter:title meta tag found, but is empty!` does no match.

![Image](https://github.com/dotCMS/core/assets/29883881/385d9a68-e401-43cd-9b77-5dcf379a838f)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**twitter:title**

*Case 1:*

When `twitter:title` and `og:title` and `meta tag title` not found.

The expected message `twitter:title meta tag not found, and HTML Title not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/af6d8078-ef2f-4ba8-8dee-673308e58677)

*Case 2:*

When `twitter:title` and `og:title` not found, but `meta tag title` is found.

`<title>TEST</title>`

The preview title is missing. It must show the HTML Title instead.

![Image](https://github.com/dotCMS/core/assets/29883881/bcf9fdfa-8880-4c89-81d6-57a5241bf514)

*Case 3:*

When `twitter:title` has 70 characters.

`<meta name="twitter:title" content="TEST TITLE *******************TEST TITLE *******************.........." />`

The expected message `twitter:title meta tag found, but it has more than 70 characters` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/4a2abe82-b235-445f-9d3b-e18737715e16)

*Case 4:*

When `twitter:title` has 30 characters.

`<meta name="twitter:title" content="TEST TITLE *******************" />`

The expected message `twitter:title meta tag found, but it has fewer than 30 characters of content.` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/4923ae95-aa4d-40e6-ae06-e36907d9b28d)

**twitter:description**

*Case 1:*

When `twitter:description` and `og:description` and `HTML meta tag description` not found.

The expected message `twitter:description meta tag, and Meta Description not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/b7791701-5c25-43d5-a269-6519eb3097ed)

*Case 2:*

When `twitter:description` and `og:description` not found, but `HTML meta tag description` is found.

`<meta name="description" content="DESCRIPTION ****TEST.Lorem ipsum dolor sit amet, consectetur adipiscing elit." />`

The preview description is missing. It must show the HTML description instead.

![Image](https://github.com/dotCMS/core/assets/29883881/a3107427-a3ad-4563-9f63-a2534e071a8b)

*Case 3:*

When `twitter:description` has 30 characters.

`<meta name="twitter:description" content="Lorem ipsum dolor sit ametTEST" />`

The expected message `twitter:description meta tag with valid content found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/ce710c56-a9cf-4c04-bfb1-b0e5230a549b)

*Case 4:*

When `twitter:description` has 200 characters.

`<meta name="twitter:description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ante metus, posuere quis posuere eu, varius nec ante. Aenean nec dictum purus. Nullam rhoncus velit mauris, vel fringilla purus mollis ege" `

The expected message `twitter:description meta tag found, but it has more than 200 characters.` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/0d136fef-900d-44a6-82d3-e8609719d4d0)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**twitter:title**

*Case 1:*

When `twitter:title` is not found, and `og:title` not found, but `meta tag title` is found.

`<title>HTML TITLE</title>`

The expected message `Problem: twitter:title meta tag not found! Showing HTML Title instead.` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/c8a7c610-0b47-46aa-9a3d-f20eb044ff82)

*Case 2:*

When `twitter:title` is found, and has more than 70 characters.

`<meta name="twitter:title" content="Lorem ipsum dolor sit amet****Lorem ipsum dolor sit amet****//////////+++++" />`

The title on the preview length must be less than 70 characters.

![Image](https://github.com/dotCMS/core/assets/29883881/6ea63be1-438b-4aa8-a759-034dd6a6c605)

**Comment by dcolina** [comment]
Internal QA: PASSED.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_731b526_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Added card
https://github.com/dotCMS/core/issues/26497
