### ISSUE TITLE
Update Tab Navigation Component Design

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25280]
### Task

Need to update the tab navigation component.

It's OK if we just change the base CSS to make this is a system-wide design tweak wherever we use the tab nav menus like this.

See designs under "External Links."

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=372-9191&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190

Navigation - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=372-9190&t=n7GFPgGsVyiLrLsH-0

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
