### ISSUE TITLE
Build New Social Media Tile Preview Tool for LinkedIn

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25289]
### Task

Build New Social Media Tile Preview Tool for LinkedIn

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

See notes here:

* Social Media Tile & Search Engine Results Page Preview Tool Messages | dotCMS - Google Docs || https://docs.google.com/document/d/1O8PMni7FzD9YmIHdz-De43MnHpO--0_W49ZwYxLt9DM/edit

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=298-6800&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190 

Design - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-7119&t=kzAG714FzCpMdHYC-0 

Sanity Check Requirements - https://socialsharepreview.com/?url=https://dotcms.com

**Comment by dcolina** [comment]
Internal QA: Needs work.

See the comments on this card [](https://github.com/dotCMS/core/issues/25287).

**Comment by nollymar** [comment]
Fixed on #26388

**Comment by dcolina** [comment]
Internal QA: Needs work.

See the comments on this card [25287](https://github.com/dotCMS/core/issues/25287.)

**Comment by dcolina** [comment]
Internal QA: Needs work.

See the comments on this card [25287](https://github.com/dotCMS/core/issues/25287).

**Comment by dcolina** [comment]
Internal QA: PASSED.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_df4427b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
