### ISSUE TITLE
[UI] Edit Page Portlet menu is under Navmenu when you do a refresh page

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25298]
### Problem Statement

When you go to Edit Page, and do a refresh, the menu Icono is under of Navebar (right menu)

### Steps to Reproduce

- Go to Edit Page
- Refresh page

### Acceptance Criteria

- After a refresh, the menu icon needs to be accessible.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Initial state
<img width="1569" alt="Screenshot 2023-06-21 at 11 36 38 AM" src="https://github.com/dotCMS/core/assets/1909643/5d42b389-397b-41c4-8003-ba3166fab1d3">
### Disappear after refresh
<img width="1574" alt="Screenshot 2023-06-21 at 11 36 46 AM" src="https://github.com/dotCMS/core/assets/1909643/3cfabbd4-c652-4345-9097-bc14ae4c8157">

**Comment by victoralfaro-dotcms** [comment]
Verified in `dotcms/dotcms:master_1d987fc4_SNAPSHOT`
Before refresh
![image](https://github.com/dotCMS/core/assets/64026161/684efc82-6382-46ac-bfc1-50f838f9b805)
After refresh
![image](https://github.com/dotCMS/core/assets/64026161/6e563b73-652e-49c0-9cf2-90ed220210bb)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d8ef9ab_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
