### ISSUE TITLE
Date format has changed for fields in newer versions of dotCMS

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25293]
### Parent Issue

https://github.com/dotCMS/core/issues/25008

### Problem Statement

Same as the issue above, seems that we only fixed for API responses but no for VTL ones.

### Steps to Reproduce

1- Create a widget with the following code:
```
PostingDate vs ModDate</br>
#foreach($con in $dotcontent.pull("+contentType:Blog +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST)",10,"modDate desc"))
$con.postingDate vs. $con.modDate <br>
#end
```
2- Add the widget to a page
3- Check the dates, are diff formats

![Screenshot 2023-06-20 at 3 20 18 PM](https://github.com/dotCMS/core/assets/5278970/dd7d308a-a6cf-490e-bb7a-896ded1be847)

### Acceptance Criteria

The date format should be the same as the one of the modDate.

### dotCMS Version

23.01 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112060

**Comment by wezell** [comment]
the above compares the .toString() methods of the Date objects.   The db date is a `java.sql.Timestamp` and the contentType date is a `java.util.Date` - this is not really an issue as the values are not wrong.

```
#foreach($con in $dotcontent.pull("+contentType:Blog",10,"modDate desc"))
$con.postingDate vs. $con.modDate
$con.postingDate.class vs. $con.modDate.class <br>
#end
```

**Comment by dsolistorres** [comment]
PR ready for this issue:
https://github.com/dotCMS/core/pull/25521

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_dc3cb0b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0


![Screenshot 2023-07-21 at 12 11 21 PM](https://github.com/dotCMS/core/assets/129882031/6a046576-9823-4456-8732-b180e653cf6d)

**Comment by erickgonzalez** [comment]
Not reproducible in 22.03 LTS
