### ISSUE TITLE
Creating Pentest Automation Using GitHub Workflow

### ISSUE THREAD

**Issue by TommyB13** [dotCMS/core#25291]
### User Story

As a developer, I want to be able to automate penetration testing using a workflow in GitHub Actions, so I can generate reports of potential vulnerabilities.

### Acceptance Criteria

The workflow must successfully run a penetration test on the latest version of dotCMS at a specified time and push the results to a separate repository where the results will be stored.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

In order for the workflow to run, an AWS server must be set up with dotCMS running via docker and it must be set up as a self-hosted runner with the repository so that the workflow can run on the server.

**Comment by sfreudenthaler** [comment]
stale. @mbiuki can revisit and decide to refresh this card, drop it, or merge with another card where applicable

**Comment by mbiuki** [comment]
This was a research and it is completed by hiring a Summer intern in 2023. All findings and presentation slides are put here: https://drive.google.com/drive/folders/1Og9cwhMyD8JCsEpmS04b4NdhfiC7JUdW?usp=drive_link
This ticket may be closed.

**Comment by mbiuki** [comment]
@sfreudenthaler this was an interesting project - please review.

**Comment by sfreudenthaler** [comment]
Lots of interesting stuff in this prototype.  

1. Not sure what the `false positive` rate looks like today and what would be acceptable
2. Is there overlap/redundancy with other security testing we're doing?  
3. the branch never got merged back to `master`... What are the implications there?  and crucially.  Is the prototype now considered "stale"? (FWIW I think the concept or the [Automate & Conquer](https://docs.google.com/presentation/d/1nmJmAHxskGIV8Q5ibjTNfZYNAC9gw6uz3scBU1mTGuc/edit#slide=id.g260fb2a9825_0_719) deck are still very much valid
4. Who would review the findings?
5. Would the findings block merge?
6. Could the reporting python be modified to create github issues automatically? 
7. I spot-checked an example of the `Nikto Scan Report` and I'm concerned that it's not going to be actionable for engineers
![Image](https://github.com/dotCMS/core/assets/31257998/6680dfb1-9919-4f56-89e1-fbced1181ae8)
