### ISSUE TITLE
Build New Search Engine Results Page Preview Tool for Google

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25290]
### Task

Build New Search Engine Results Page Preview Tool for Google

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

See notes here:

* Social Media Tile & Search Engine Results Page Preview Tool Messages | dotCMS - Google Docs || https://docs.google.com/document/d/1O8PMni7FzD9YmIHdz-De43MnHpO--0_W49ZwYxLt9DM/edit

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=298-6800&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190 

Design - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=523-11475&t=URNtP1TkxmYhhpH9-0

**Comment by nollymar** [comment]
**Internal QA:** Needs work

The description in the Title card is empty


![Image](https://github.com/dotCMS/core/assets/8741395/364088da-f035-4c42-8f5d-cd2b9f11b579)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**Favicon**

*Case 1:*

When `Favicon not found!`

The expected message `Favicon not found! is missing.

![Image](https://github.com/dotCMS/core/assets/29883881/4cac961a-d800-4733-97a1-87c3b93c8b52)

*Case 2:*

When `Favicon` exists, but it has an invalid link.

The expected message `Favicon found, but Image Link is not valid!` is missing.

![Image](https://github.com/dotCMS/core/assets/29883881/0a7dce04-79c2-488e-a123-0865a2c1ccd5)

**Title**

*Case 1:*

When `HTML Title not found!`

The expected message `HTML Title not found!` is missing.

![Image](https://github.com/dotCMS/core/assets/29883881/b007baf0-04ec-49a7-a727-a64a12fd5906)

*Case 2:*

When the `HTML Title is empty`.

```
<title></title>
```

The expected message `HTML Title found, but is empty` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/477a744e-2b6c-4a03-9794-e573f55c606f)

**Comment by manuelrojas** [comment]
@dcolina 
Case 2:
When Meta Description is duplicated.
<meta name="description" content="Hello world and It has enough characters to show." />
<meta name="description" content="Hello world and It has enough characters to show." />
This is fine because it is `og:description`

**Comment by manuelrojas** [comment]
@dcolina There is another task for this:

Case 2:

When Favicon exists, but it has an invalid link.

The expected message Favicon found, but Image Link is not valid! is missing.

**Comment by nollymar** [comment]
The other issues have been fixed on #26388

**Comment by dcolina** [comment]
Internal QA: Needs work.

**Favicon**

*Case 1:*

When meta tag is found, but is empty.

`<link rel="icon" />`

The expected message `Favicon not found, but Image Link is not valid!` does not match.

![Screenshot 2023-10-13 at 10 40 57](https://github.com/dotCMS/core/assets/29883881/33a28f5b-13c8-48c2-aa65-6557b336d351)

**Description**

*Case 1:*

When meta tag exists, and it has between 55 and 160 characters.

`<meta name="description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pharetra maximus enim ac tincidunt. Vivamus vestibulum sed enim sed consectetur." />`

The expected message `Meta Description found!` does not match.

![Screenshot 2023-10-13 at 10 47 07](https://github.com/dotCMS/core/assets/29883881/c6fc1f75-1c0f-4744-9e0e-eefe9507de1f)

*Case 2:*

When meta tag exists, and it has more than 160 characters.

`<meta name="description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pharetra maximus enim ac tincidunt. Vivamus vestibulum sed enim sed consectetur. Nulla malesuada libero a tristique bibendum. Suspendisse blandit ligula velit, eu volutpat arcu ornare sed." />`

The expected message `Meta Description found, but it has more than 160 characters.` does not match. And preview has the wrong length, it has 159 characters when it must be 160.

![Screenshot 2023-10-13 at 10 53 58](https://github.com/dotCMS/core/assets/29883881/c478218e-d43c-4074-9d31-708c84cb540a)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**HTML Title**

*Case 1:*

When Title length = 30 characters.

`<title>HTML TITLE -------------- TEST</title>`

The expected message `HTML Title found, with an appropriate amount of content!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/288679cb-4ef0-4838-bdf2-d4dcd41325dc)

*Case 2:*

When Title length = 60 characters.

`<title>HTML TITLE -------------- TEST******************************</title>`


The expected message `HTML Title found, with an appropriate amount of content!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/a3c0595d-d8fb-4ed1-a43a-c92833ebd352)

**HTML Description**

*Case 1:*

When Description length = 55 characters.

`<meta name="description" content="DESCRIPTION ****TEST.Lorem ipsum dolor sit amet.-------" />`

The expected message `Meta Description found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/436cce3b-32f9-4927-9721-3d7b82ff09e1)

*Case 2:*

When Description length = 160 characters.

`<meta name="description" content="DESCRIPTION ****TEST.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ante metus, posuere quis posuere eu, varius nec ante. Aenean nec dictum purus" />`

The expected message `Meta Description found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/f64e083a-11f3-498d-8594-3719f77e8fb5)

**Comment by dcolina** [comment]
Internal QA: PASSED.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_df4427b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Added card https://github.com/dotCMS/core/issues/26497
