### ISSUE TITLE
Fixing a Page Conflict on the local node  - makes the page disappear from site browser. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#25295]
### Parent Issue

Discovered while working on https://github.com/dotCMS/core/issues/25229

### Problem Statement

if you fix a page conflict via Integrity Checker on the local node makes the page disappear from site-browser
The page continues to exist locally and can be accessed via content search but for some reason, it is no longer available in site-browsers' source folder. 

### Steps to Reproduce

Since we now have Deterministic identifiers creating a conflict between a sender and receiver becomes a bit tricky but not impossible. In order to reproduce 
Set up a push-publish environment (sender and receiver) both using full-starter.

1. On the receiver node create a folder let's say we name it "foo"
2. On that folder create a page and name it "bar" 
3. Repeat these same 2 steps but this time on the sender node. Verify the identifiers on the pages named "foo" are the same
4. Now in order to trick the deterministic identifiers on the receiver node cut the page named "bar" and paste it somewhere else outside the folder "foo".  
5. Now still on the receiver recreate the page "bar" inside the folder "foo". Verify this time the identifiers on the sender's "bar" page and the receiver's "bar" page are not the same. We have created a conflict!
6. Now set up the Publishing Environments on the sender. Once ready hit "Check Integrity" an Error must be reported here.
7. Now that you have seen that there's an error on the Pages Tab. Hit the Fix Button  On the Local Node. 
8. Now still on the sender Verify the page is no longer visible on the folder "foo"
9. Verify the page appears in the content search. The folder is correct but the page can not be accessed via Site-Browser and **now it lacks title.** 

See the video for the steps:

https://github.com/dotCMS/core/assets/37148755/7e0a9c35-d40b-4f46-9bbd-2d32a724a0d8

### Acceptance Criteria

We should be able to access the pages via site-browser at any time.  

### dotCMS Version

Reproducible in master

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
This is getting fixed in here https://github.com/dotCMS/core/issues/25224
