### ISSUE TITLE
Support SEO feature flag

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25299]
### Parent Issue

#24862

### User Story

In order to start implementing changes related to SEO improvements, as a user, I want to be able to enable/disable this feature through a property called `FEATURE_FLAG_SEO_IMPROVEMENTS`. By default, this property will be off, this means that if the property doesn't exist, we asume it is off, therefore, we shouldn't need to include this property in the dotmarketing-config.properties to make it work.

### Acceptance Criteria

- If the property  `FEATURE_FLAG_SEO_IMPROVEMENTS`  is set to true, I enable the SEO improvements changes
- If the property  `FEATURE_FLAG_SEO_IMPROVEMENTS` is set to false, I disable the SEO improvements changes
- If the property  `FEATURE_FLAG_SEO_IMPROVEMENTS` does not exist, I disable the SEO improvements changes

### Proposed Objective

Marketing

### Proposed Priority

Priority 3 - Average

**Comment by manuelrojas** [comment]
It could be verified by adding the `DOT_FEATURE_FLAG_SEO_IMPROVEMENTS=true` environment variable and it shouldn't display the show preview button:

![image](https://github.com/dotCMS/core/assets/3438705/f51df877-69d2-45d9-bff0-cc47f2b173d2)

In your local, you can just add: 

`export DOT_FEATURE_FLAG_SEO_IMPROVEMENTS=true`

then it will need to be re-deployed with Docker this could be done by adding the following in the environment variables:

"DOT_DOTFAVORITEPAGE_FEATURE_ENABLE": 'true'

**Comment by nollymar** [comment]
**Internal QA:** Passed

After enabling the flag  `FEATURE_FLAG_SEO_IMPROVEMENTS`, the Show Preview link didn't show anymore:



![Image](https://github.com/dotCMS/core/assets/8741395/ee6add09-0762-4a2f-9dc0-3a72bb665bf5)

**Comment by bryanboza** [comment]
Fixed, tested based in the last comment and it is working as expected.
