### ISSUE TITLE
Limited users cannot create content types on System Host

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25296]
### Problem Statement

Limited users cannot create content types on System Host, even with full permissions to 'All Sites'

### Steps to Reproduce

1. From a demo starter, add full permissions to Publisher/Legal role to All Sites and demo.dotcms.com
2. Login as Chris Publisher
3. Try to create a content type and select system host

System host will not be present in the drop down

### Acceptance Criteria

1. Limited users should be able to create content types on System Host if given the proper permissions

### dotCMS Version

23.06, 23.01, 21.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Related ticket: https://dotcms.zendesk.com/agent/tickets/112015

### Assumptions & Initiation Needs

We are checking if the user has the CMS_ADMIN role, and we're not checking permissions. 

SiteResource is not returning the System Host https://demo.dotcms.com/api/v1/site?filter=*&per_page=15&system=true

**Comment by swicken-dotcms** [comment]
This is note stale, 2nd customer hitting this: https://dotcms.zendesk.com/agent/tickets/114646

**Comment by dsolistorres** [comment]
Internal QA passed: limited user can select System Host when creating a new content type

![image](https://github.com/dotCMS/core/assets/2894221/b20abbe5-7d25-45c9-8c9e-081a56229c8a)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_eee6dc3**, Docker, macOS 13.0, FF v121.0.1
