### ISSUE TITLE
[UI] Add to Bundle to the 3 dots Menu in Experiment Configuration

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25316]
### Parent Issue

N/A

### User Story

Add the add to Bundle option in the experiments configuration page and listing. 

### Acceptance Criteria

-  should be present in the configuration page options at the top right
-  Should be present in the listing page. 
- Add To Bundle should be present in all experiment states 
- Only present if has enterprise license

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by oidacra** [comment]
Due to a change in the backend, the Dialog of Add To Bundle no will show until this [PR](https://github.com/dotCMS/core/pull/25544) will be merged (we fix the frontend problem in that PR)

**Comment by bryanboza** [comment]
Fixed tested on master // Docker // FF
