### ISSUE TITLE
Template Builder: Adjust the UI  for Perfection in Template and Layout Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25322]
### User Story
As a dotCMS user, I want to be able to adjust the UI of the template builder to look perfect in the Template Editor and in the Layout Editor, so that I can create a more visually appealing website.

### Acceptance Criteria
- The Template Editor and Layout Editor should look good, using the provided screenshots as reference.
- The Template Builder should be responsive down to iPad

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="1714" alt="image" src="https://github.com/dotCMS/core/assets/751424/2f9d923f-19d9-4289-acff-b7603109bb70">

### Assumptions & Initiation Needs
- The Template Builder should be compatible with all major browsers.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Design the UI of the Template Builder (est. 10hrs)
- Test the UI of the Template Builder (est. 8hrs)

**Comment by fmontes** [comment]
There was an issue with the padding and the feature flag, need to test that.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_35fde56_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
