### ISSUE TITLE
dojo buttons have no borders

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25336]
### Problem Statement

When we updated the shared style sheet, our dojo buttons lost their borders. 
# 23.06

![Screen Shot 2023-06-23 at 3 33 29 PM](https://github.com/dotCMS/core/assets/934364/9b126e09-f158-49e2-9d7f-0e44ebfa5170)
# master
![Screen Shot 2023-06-23 at 3 31 50 PM](https://github.com/dotCMS/core/assets/934364/2d42b0e3-2b28-442b-b77d-b69d8b3fea3f)

### Steps to Reproduce

Look at the buttons in master 

### Acceptance Criteria

should look like 23.06

### dotCMS Version

23.07

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by fmontes** [comment]
Fixed.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_e622545`]
- Server: [QA Master](https://dotcms-qa-master.dotcms.site/dotAdmin/)

### Video

https://github.com/user-attachments/assets/328a3c39-fa3e-4c6b-a35a-327866b31f3e

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_dd1fbce**, Docker, macOS 14.5, FF v126.0.1
