### ISSUE TITLE
Editing Variants with Image-Containing content causes error

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25345]
### Problem Statement

Currently in dotCMS, if a piece of content containing an image is added to an experiment variant, attempts to edit that variant can result in errors.

We are showing an error in the UI and printing the following error multiple times in the log:
![image](https://github.com/dotCMS/core/assets/2641437/0afc3c4f-245d-4a5e-88ad-1823d6505148)

Stack trace: https://gist.github.com/bryanboza/49d5b0a73ecf56bc3c0c0d8ed27cdd5b

### Steps to Reproduce

- Create a new experiment in dotCMS
- Add a new variant
- Add a new piece of content,  type image to the variant
- Save the variant
- Attempt to edit the variant
- Note the error message and inability to proceed with the edit

### Acceptance Criteria

- When editing a variant, if the variant contains content with images, the processing of those images should not cause errors
- Variants with image-containing content should be editable without requiring workarounds or special handling
- Tests 

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by freddyucv** [comment]
it is working

**Comment by bryanboza** [comment]
Seems that this problem was fixed in a recent change, we can close this card for now. 

Tested on master / Docker // FF
