### ISSUE TITLE
Teamplate Builder: Fix Autosave in Layout Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25342]
### Problem Statement
In the layout editor when it loads, it autosaves even when nothing has changed.

### Steps to Reproduce
1. Login to dotCMS (apply for license)
2. Edit a page
3. Go to layout

### Acceptance Criteria
Layout should not be saved if nothing changed.

### External Links
https://github.com/dotCMS/core/assets/751424/839c75f0-1c1a-4e64-a25f-d5e640748370

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
This [PR](https://github.com/dotCMS/core/pull/25389) solves this Issue.
