### ISSUE TITLE
GitHub Action to generate a Release Candidate

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25350]
### User Story

A GitHub Action that performs a series of steps when a Release Candidate is ready to be selected is needed.

Steps to perform include:

1. The action will get a list of commits between two given commits: 
* commit 1: previous release
* commit 2: the desired commit to choose as Release Candidate

2. It will then iterate through this list and parse each commit message and filter the list by the ones matching a keyword that specifies that it is the final commit of a GitHub issue. E.g. "final commit #12345". (we need to come up with a convention for this). It will then parse the Github issue number contained in the message to build a list of GitHub issues. 
3. Once the list of Github issues is formed, each one will be labeled with the "Release Candidate" label.  
4. Tag the given commit as the "Release Candidate" 

### Acceptance Criteria

The output of the GitHub action being:
1. A list of GitHub issues contained in the Release Candidate
2. The list of GitHub issues labeled with the "Release Candidate" label. 
3. A new tag "Release Candidate" pointing to the selected commit. 

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/25725

**Comment by victoralfaro-dotcms** [comment]
Please refer to: https://auth.dotcms.com/devwiki/automated-changelog

**Comment by victoralfaro-dotcms** [comment]
Github Action in action:
![image](https://github.com/dotCMS/core/assets/64026161/0b8f6db1-0bce-4f4e-964b-a8e3ad583ae9)
### Generate Changelog
Found one commit matching [conventional commits](https://auth.dotcms.com/devwiki/conventional-commits):
```
Executing command: git log issue-25350-release-candidate 8a9e7a599339f21176de5a88e187b29b46e89be6..16065cc2e892fbf4653d6e10ac6852385cbbebd1 --pretty="|||||%n%H%n%s%n%b"
Filtered commits:
[
  {
    "sha": "16065cc2e8[9](https://github.com/dotCMS/core/actions/runs/5793287359/job/15700823819#step:4:10)2fbf4653d6e[10](https://github.com/dotCMS/core/actions/runs/5793287359/job/15700823819#step:4:11)ac6852385cbbebd1",
    "subject": "ci(dev-cycle): release changelog generation",
    "body": "Introducing a Github Action to generate, based on Github repo commits, a release candidate changelog.",
    "refs": [
      "25350"
    ]
  }
]
Getting issues for sha [[16](https://github.com/dotCMS/core/actions/runs/5793287359/job/15700823819#step:4:17)065cc2e892fbf4653d6e10ac6852385cbbebd1]
Extracting issues numbers from refs: 25350
Processing issue 25350 found in sha [16065cc2e892fbf4653d6e10ac6852385cbbebd1]
Fetching issue 25350
Issues found:
[
  [25](https://github.com/dotCMS/core/actions/runs/5793287359/job/15700823819#step:4:26)350
]
```
###  Label Issues
```
Processing labels Release Candidate for issue 25350 with operation ADD
Affected issues: [25350]
Ignored issues: []
```
###  Create RC tag
```
==============
Executing cmd:
==============
git tag -a "release_candidate" -m "Release candidate tag" 
cmd_result: 0

==============
Executing cmd:
==============
git push origin "release_candidate" 
To https://github.com/dotCMS/core
 * [new tag]               release_candidate -> release_candidate
```
### Changelog Report
```
# Changelog for tag release_candidate


| Issue | Title                                         | Link                                          | Commits                                                                                     |
|-------|-----------------------------------------------|-----------------------------------------------|---------------------------------------------------------------------------------------------|
| 25350 | GitHub Action to generate a Release Candidate | https://github.com/dotCMS/core/issues/25350   | - *[16](https://github.com/dotCMS/core/actions/runs/5793287359/job/15700823819#step:7:17)065cc2e892fbf4653d6e10ac6852385cbbebd1*: ci(dev-cycle): release changelog generation   |
```

**Comment by bryanboza** [comment]
Need some work here, this action is just labeling the first 30 cards with the "Release" label, and all the other ones still having the `Next Release`

**Comment by victoralfaro-dotcms** [comment]
This will be fixed as soon https://github.com/dotCMS/core/pull/26549 gets merged
