### ISSUE TITLE
PP: pushing new folder with limited user fails

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25371]
### Problem Statement

When you try to PP a newly created folder as a limited user, which has full permissions over the folder, it fails due "lack of permissions".

### Steps to Reproduce

1- Create a new folder
2- Edit Folder Permissions and give Edit Permissions to the Chris Publisher user.
3- Configurate PP and give Chris Publisher the ability to push.
4- Try to PP the folder as the limited User
5- Get a `1` in the PP dialog and an error in the logs (sender).

https://github.com/dotCMS/core/assets/5278970/8e7a9718-bca6-4855-928d-8d09544fcfb6

### Acceptance Criteria

Limited users should be able to PP folder successfully if they have the correct permissions.

### dotCMS Version

23.01 LTS and demo.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112040

### Quality Assurance Notes & Workarounds

Give CMS Admin Role to the limited user.

**Comment by waqasakramdot** [comment]
Customer is hitting this: https://dotcms.zendesk.com/agent/tickets/112619

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. I'm able to push a folder as a limited user without problem

**Comment by erickgonzalez** [comment]
another customer hitting this https://dotcms.zendesk.com/agent/tickets/113019
