### ISSUE TITLE
Template Builder: Fixing Style Class Dialog UI/UX

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25376]
### Problem Statement
In the template builder, the style class dialog needs to be fixed in order to improve the UI/UX.

### Steps to Reproduce
1. Log in to dotCMS
2. Go to the template builder
3. Open the style class dialog

### Acceptance Criteria
- The scroll should be fixed.
- The textfield should grow to accommodate the content.

### External Links 
https://github.com/dotCMS/core/assets/751424/26b6eeeb-9508-4f6d-84ee-61f256d5410a

[Figma](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Portlets-%2F-Edit-Page?type=design&node-id=1406%3A3042&mode=design&t=uEeEDmgQfIFDQB5G-1)

### Assumptions & Initiation Needs
- Assume that the UI/UX of the style class dialog needs to be improved.
- Need to initiate the process of fixing the UI/UX.

### Quality Assurance Notes & Workarounds
- QA should test the scroll and textfield grow functions.
- If the scroll and textfield grow functions are not working properly, a workaround may be to adjust the textfield size manually and use the scrollbar.

**Comment by josemejias11** [comment]
**Failed QA** - Tested on **master_a07bfad_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
![Screenshot 2023-07-13 at 12 10 02 PM](https://github.com/dotCMS/core/assets/129882031/d34a63f0-db32-4ff5-acb9-f6d5825ffb34)


Still needs to adjust limits a bit more. (Using firefox)

**Comment by fmontes** [comment]
Hey @josemejias11 You need to scroll.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_fd03f7e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
