### ISSUE TITLE
Template and Layout API Should Fallback to System Theme

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25379]
### Problem Statement
The template and layout API should handle the fact that frontend can not set the `themeId` and instead of returning an error, it should fallback to system theme.

### Steps to Reproduce
1. Verify that the `themeId` is not set on the template and layout API
2. Observe that an error is returned instead of falling back to the system theme

### Acceptance Criteria
1. When the `themeId` is not set on the template and layout API, the system should fallback to the system theme instead of returning an error.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
To test this:
1. Create a template with no theme
2. Create a page with that template
3. Edit the page

It should edit the page normally, it was returning a 404.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
