### ISSUE TITLE
Template Builder: Add System Container and 3 Columns Width to Box

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25377]
### User Story
As a dotCMS user, I want to be able to add a system container and 3 columns width to a box in the template builder, so I can quickly and easily design my page templates.

### Acceptance Criteria
- A new box in the template builder should have a system container and 3 columns width by default.
- The user should be able to change the number of columns and remove the system container.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The user must have the necessary permissions to edit the template builder.
- The user should be familiar with the template builder and how to use it.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Create a new box with 3 columns width and system container by default.
- Allow the user to change the number of columns and remove the system container.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_35fde56_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
