### ISSUE TITLE
[UI] Go out of edit mode when navigating to another page using nav_menu while editing a variant

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25385]
### Problem Statement

Currently, when editing a variant in dotCMS and trying to navigate to another page using the nav_menu, there is no mechanism in place to automatically exit the edit mode. This can lead to the unintended addition of new pieces of content associated with the variant to pages without experiments.

Also, this is breaking the UI and you are unable to go back to the page after navigating to a different page on edit mode. 
https://github.com/dotCMS/core/assets/2641437/cafd5f98-4abc-496b-9adf-845fb413f8a7

### Steps to Reproduce

- Login to dotCMS.
- Navigate to variants and select a variant to edit.
- Click on the nav_menu.
- Select a page without experiments from the menu.

### Acceptance Criteria

- When editing a variant, navigating to another page using the nav_menu should automatically exit the edit mode.
- The user should be directed to the selected page without any unintended content additions or associations with the variant.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
About this:

"When editing a variant, navigating to another page using the nav_menu should automatically exit the edit mode."

really it should exit the Experiment mode

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/25546 
QA Notes: Cover scenario when the running link get lost while doing internal navigation.

**Comment by oidacra** [comment]
IQA Passed
Running the link now works if you do internal navigation.

<img width="1584" alt="Screenshot 2023-07-26 at 1 35 16 PM" src="https://github.com/dotCMS/core/assets/1909643/1be51966-7782-40cf-9d47-14d188be6fcb">

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
