### ISSUE TITLE
Unknown Error When Promoting Variant as Limited User

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25382]
### Problem Statement

When a limited user tries to promote a variant without the proper permissions, an unknown error occurs, and the promotion is not completed.
![image](https://github.com/dotCMS/core/assets/2641437/3c88fea3-621a-4ff8-b701-8f30f643f5d1)

Error: https://gist.github.com/bryanboza/1c70a1828c635025a5c6170f900a9346

**FYI: If the user is able to add variants, schedule, and start the experiment, now sure why we need extra permissions to promote.** 
 
### Steps to Reproduce

- Log in as a limited user.
- Navigate to the experiment variants tab.
- Select a variant to promote.
- Click on the promote button.

### Acceptance Criteria

- When a limited user tries to promote a variant without the proper permissions, an error message should be displayed, indicating that the user does not have the necessary permissions to perform the action.
- The promotion should not be completed, and the variant should remain in its current state.
- Postman tests 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
We need to set up the permissions for experiments to utilize the Template-Layouts rights (on the site) as a proxy for rights to edit experiments.  The permissions then will end up looking like this:

To edit experiments, you need both:
* Edit rights on the Page
* Edit rights for Template-Layouts on the site

To start experiments and promote variants, you need both:
* Publish rights on the Page
* Publish rights for Template-Layouts on the site

The potential challenge here is that someone who can schedule an experiment to start can ultimately start it even if they don't have publish rights.  So, in an ideal world, we'd also hide the schedule properties in the experiment from users without Publish rights.  If this would be easy to do, then we should do it.

But for MVP, it's OK if we don't hide the schedule based on permissions; this is similar to how you can set up content types with auto-publish dates that content editors without publish permissions can set.

**Comment by hmoreras** [comment]
*Passed Internal QA: * 


https://github.com/dotCMS/core/assets/31667212/7d60f5c0-a8b9-4e6a-a663-4b99f009d4fc

**Comment by bryanboza** [comment]
Since this change involves a change in the API, we need to add a Postman test here.

**Comment by freddyucv** [comment]
> Since this change involves a change in the API, we need to add a Postman test here.

I created a new issue for it https://github.com/dotCMS/core/issues/26208

**Comment by bryanboza** [comment]
Ok we can close this one, new card for the test created on #26208
