### ISSUE TITLE
Template Builder: Fix Template Portlet Issue with Required Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25381]
### Problem Statement
In the template portlet when creating a new template, the form marks the theme field as required but it is not.

### Steps to Reproduce
1. Log into dotCMS
2. Go to the Template Portlet
3. Click "Create" and select "Design" in the modal
4. The form will show the theme field as required but it is not

<img width="733" alt="image" src="https://github.com/dotCMS/core/assets/751424/962d9a4a-178d-4007-b4fb-158df933db36">

### Acceptance Criteria
1. Remove the required * to the theme field.
2. Nice to have: default selected "System Theme"

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b94ad25_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
