### ISSUE TITLE
[UI] Unable to Edit Experiment Variant on Locked Page

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25380]
### Problem Statement

When a page is locked by another user and a limited user tries to add a new experiment variant, there is no indication that the page is locked, and the variant cannot be edited.
https://github.com/dotCMS/core/assets/2641437/348e5209-9e7d-4c35-bd22-da07e829a4ea

### Steps to Reproduce

- Have a page locked by another user.
- Log in as a limited user.
- Create a new experiment and navigate to the experiment variants tab.
- Try to edit the experiment variant on the locked page.

### Acceptance Criteria

- When a limited user tries to edit an experiment variant on a locked page, a message should be displayed indicating that the page is locked and cannot be edited.
- The limited user should not be able to make changes to the experiment variant until the page is unlocked.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
After a discussion, the plan is to treat the experiment config like page properties with respect to locks.  This means:

* There is only one lock on the page.
   * There is not a separate lock for each variant.
* You can't edit the experiments config (including variants) unless you lock the page.
    * And this means you can't edit the experiments or variants if someone else has the page locked.
* If you want to prevent someone from editing the page after you've scheduled an experiment, you can lock the page.

To make things relatively simple to implement, I suggest:
* When someone clicks the button to edit experiments, we check to make sure the user has a lock on the page.
* If they don't have a lock, we popup a modal with the message "You must lock the Page before you can edit Experiments."
    * Doing it this way means we don't have to check to see if another user has a lock (and then notify which user it is, etc.).
    * Because by forcing the user to lock the page, we're forcing them to go through those other checks without us having to worry about them within experiments.

**Comment by wezell** [comment]
So - in dotCMS we have the concept of "canLock".  What this returns is a boolean if the user could lock/unlock the asset if they wanted to.  I would suggest that we use this rather than force a lock on the page.  This would mean that an admin could always edit experiments but users could lock a page and other users would not be able to modify the experiments.

I don't like the idea of forcing the user to lock the page before editing the experiment.

**Comment by hmoreras** [comment]
Changes: 

Following the same behavior that we have when the experiment is running, then the page is blocked by other user: 

* Display `View` in the button of the variants.
* in the variant screen, display the error message that the page is blocked and hide the edit button.


https://github.com/dotCMS/core/assets/31667212/546e3e1a-200f-43da-90b3-4ab286821aba

**Comment by oidacra** [comment]
Disabled Edit Button will be fixed with https://github.com/dotCMS/core/issues/26193

**Comment by oidacra** [comment]
IQA Passed
Tested: Not allow edit variant if the page is Locked.

<img width="1814" alt="Screenshot 2023-10-02 at 12 23 07 PM" src="https://github.com/dotCMS/core/assets/1909643/734daff7-e079-4050-bf98-e645bbd3f74b">


<img width="703" alt="Screenshot 2023-10-02 at 12 22 58 PM" src="https://github.com/dotCMS/core/assets/1909643/542d4451-46c4-4cfd-a747-eea9fac3e651">

**Comment by bryanboza** [comment]
We need some work here, when you are navigating inside the variant, we are just looking the message about the page is locker, but we don't have the lock component. 

It means if you are an admin user, we are unable to unlock the page locked by some limited or by other admin, then you need go go out, and unlock and then come back to experiments again. 

We need be able to unlock the page at any moment editing the page/variant or experiment 

![Image](https://github.com/dotCMS/core/assets/2641437/26737b50-9d3b-48be-93ab-69e78dd0c859)

**Comment by john-thomas-dotcms** [comment]
@bryanboza it's OK that you can't unlock the page while editing the variant on a page that's already locked by another user.  The intent is that the user must explicitly go back to the main page to unlock it before they make any changes to experiments - whether in the experiment configuration or inside a variant.

When the page is locked by a user, the button a different user must press to view the variant is explicitly labeled "View".  This is the clue that you can't change it when you get there, so the lack of a lock/unlock when you get there isn't a problem, it's expected.

**Comment by bryanboza** [comment]
Won't fixed...
