### ISSUE TITLE
Template Builder: Add Class to Template with Enter Key

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25396]
### Problem Statement

Currently, in dotCMS, it is necessary to type a class name and then click on the name in the drop-down list in order to add a new class to a template. This process should be simplified by allowing users to add a new class simply by pressing the Enter key.

![image](https://github.com/dotCMS/core/assets/2641437/06b1f2fc-8dfc-4a2e-bbba-aae7219b1aa5)

### Steps to Reproduce

- Open dotCMS and navigate to the template editor.
- Click on the "Add Class" button.
- Type a new class name in the input field.
- Press the Enter key.

### Acceptance Criteria

- When pressing the Enter key after typing a new class name, the class should be added to the list without requiring an additional click.
- The added class should be visible and editable in the template editor.
- The existing functionality of typing and clicking on the name in the drop-down list should still work as expected.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
also keyboard navigation

**Comment by danielmdob** [comment]
As reviewed with @fmontes, automatic scrolling is not happening while moving through different options using keyboard navigation. It was verified with [this Stackblitz](https://stackblitz.com/edit/angular-ivy-9wse7d?file=src%2Fapp%2Fapp.component.ts). It will be fixed when upgrading to more recent versions of `primeng`.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_e66ec4d_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
