### ISSUE TITLE
Template Builder: End user should be notified in case you are unable to drag and drop boxes into the row 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25398]
### Problem Statement

As an end user of dotCMS, I want to be notified if I am unable to drag and drop a box into the template designer so that I can understand why it is not possible and find an alternative solution.

https://github.com/dotCMS/core/assets/2641437/c0c3f2b9-8c1c-487d-8dbb-91d8c78650dc

### Steps to Reproduce

- Log in to dotCMS.
- Go to the template designer.
- Attempt to drag and drop more than 4 boxes into the template designer.

### Acceptance Criteria

- When attempting to drag and drop a box into the template designer, the system should provide a clear error message indicating the reason why it is not possible.
- The error message should provide guidance on alternative solutions or actions to be taken.
- The error message should be displayed prominently and clearly visible to the end user.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Make the add box 1 column and expand up to 3 if we have space.

**Comment by danielmdob** [comment]
Passed internal qa, screenshot:


![Image](https://github.com/dotCMS/core/assets/29465918/1aaa75b4-98e5-4857-bfa9-fc900d03eae6)

**Comment by zJaaal** [comment]
Found a problem while testing. For some reason we lost this behavior due to the fix of this [Issued](https://github.com/dotCMS/core/issues/25619) so I'll take a look and fix it.

**Comment by fmontes** [comment]
1. You can drop 1 box and it will grow to the right up to 3 cols width
2. Drag to the top or bottom edges will scoll.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
