### ISSUE TITLE
Enable the use of vtl in the select and multiselect Field type

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#2539]
What we often have is a structure with one or more  select fields for which the content is pulled from some external system. Right now we solve this using JavaScript and custom fields, but it would we much easier if we could just use VTL in the value field of such a field type. It would be the responsibility of the person wrting the VTL that he returns valid pipe separated list. Leading and trailing spaces and empty lines would have to be ignored.

**Comment by koenpeters** [comment]
+1
