### ISSUE TITLE
Template Builder: Problems Assigning Theme in New Template Designer

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25399]
### Problem Statement

As a user of the new template designer in dotCMS, I am facing difficulties in assigning a theme to my template. When I try to assign a theme, the system does not reflect the changes and the assigned theme does not take effect. Which is causing an error when the new template is assigned to a page. 

https://github.com/dotCMS/core/assets/2641437/aa7bd0f5-3e89-4150-ab96-598e0ba47224

Here the stack trace: https://gist.github.com/bryanboza/22261d1e98839c93fea9a03c30a5aad6
### Steps to Reproduce

- Log in to dotCMS.
- Go to the new template designer.
- Open an existing template or create a new one.
- Click on the "Theme" option or tab.
- Select a theme from the available options.
- Save the template and exit the template designer.
- Assign the created template to a new page 
- Go to edit mode 

### Acceptance Criteria

- You should be able to assign the template to a page and edit the page without problems 
- When a theme is assigned to a template in the new designer, the system should save and reflect the changes correctly.
- The assigned theme should be visible and applied to the template when reopening it in the designer.
- If the assigned theme is not taking effect, the system should display an error message or notification indicating the issue.
- The error message/notification should provide guidance on alternative solutions or actions to be taken.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Working on this here: https://github.com/dotCMS/core/issues/25379
