### ISSUE TITLE
Experiment URL is case sensitive 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25409]
### Problem Statement

Currently, the experiment URL in dotCMS is case-sensitive. This means that if a user enters the URL in lowercase or uppercase, it will not redirect to the different variants
![image](https://github.com/dotCMS/core/assets/2641437/29e394ec-c9d2-4154-a3eb-11479e8aad67)

When you use an upper-case letter it is redirecting to the page, but not to the experiment. And this is not counting the session on experiment results. 

If you go to the cube server, it is counting the events in different sessions but this is ignored by the experiment. 
![image](https://github.com/dotCMS/core/assets/2641437/99720ae3-5ba5-490d-afc9-ccdcbaa9ccf6)

Also tested the reach page goal, and this is the same case, it is case-sensitive, and any variation in the URL is not taken into consideration. 
![image](https://github.com/dotCMS/core/assets/2641437/8fe1e851-1a0e-492f-baa0-d1e87b4f905a)

### Steps to Reproduce

- Create a new folder (test) and a new page into it (index)
- Create an experiment on this page.
- Access the experiment URL by typing "Test/Index" (first letters uppercase).
- Observe that the page does not redirect to the correct experiment page.

### Acceptance Criteria

- When a user enters the experiment URL in lowercase, it should redirect to the correct experiment page.
- The experiment URL should not be case-sensitive.
- Postman tests

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25707

**Comment by victoralfaro-dotcms** [comment]
IQA using: 
Serving variant:
![image](https://github.com/dotCMS/core/assets/64026161/869a1151-329d-4bfa-a10d-058bd85e0f37)
Serving original:
![image](https://github.com/dotCMS/core/assets/64026161/7442e473-909f-480a-8147-d93c11633f74)

**Comment by bryanboza** [comment]
We need some work here:

I’m creating a folder called QA , when I navigate in the browser I’m going to localhost:8080/QA but internally we are changing this to lowercase, then we are not counting the conversions, if I do the same case but in the experiment I use qa it is working.

Then the issue is because the experiment is case sensitive

**Comment by dsilvam** [comment]
PR; https://github.com/dotCMS/core/pull/25924

**Comment by hmoreras** [comment]
Internal QA: Able to access the experiment even when the url is manipulated with uppercase letters.

**Comment by bryanboza** [comment]
Fixed, now we are able to count sessions and get conversions using different camel case combinations
