### ISSUE TITLE
Template Builder: Esc key should close the confirmation dialog when deleting a box/row

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25401]
### Problem Statement

Currently, when trying to delete a box or row in dotCMS, the user must manually close the confirmation dialog by clicking on the NO button. It would be more efficient if the dialog could be closed by simply pressing the Esc key.

![image](https://github.com/dotCMS/core/assets/2641437/a01f09de-d98b-4f6c-944d-fe9c32365b6b)

### Steps to Reproduce

- Access the dotCMS template designer.
- Select a box or row that you want to delete.
- Click on the delete button to open the confirmation dialog.
- Press the Esc key.
- The confirmation dialog remains open, requiring the user to manually close it by clicking on the NO button.

### Acceptance Criteria

- When deleting a box or row on the template designer, pressing the Esc key should close the confirmation dialog.
- Pressing the Esc key should not trigger any unintended actions or navigation.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Not show the confirmation in the box delete actions unless there are containers in it.

**Comment by danielmdob** [comment]
> Not show the confirmation in the box delete actions unless there are containers in it.

@fmontes does this apply to rows as well when they don't have boxes in them?

**Comment by zJaaal** [comment]
## Passed Internal QA

Tested in `master` branch

### Screenshots

https://github.com/dotCMS/core/assets/63567962/4138088e-8928-46e4-900b-6fab837c7f3e

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_6dd852a_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
