### ISSUE TITLE
Showing a binary field to showFields in a Relationship Field shows path instead of thumbnail

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25411]
### Problem Statement

If on a Relationship Field you set the field variable ShowFields and one of those is a binary field, we're showing the path of the file instead of a thumbnail
<img width="734" alt="Screenshot 2023-06-30 at 4 06 55 PM" src="https://github.com/dotCMS/core/assets/5278970/7d94f78b-08b7-4678-9258-366276e3deb2">

### Steps to Reproduce

1- Create a content type child with a text field and a binary field (both required and indexed).
2- Create a content type parent with a text field and a relationship field to the child content type.
3- Create a contentlet of the child
4- Create a contentlet of the parent and relate the child.
5- By default the title and the thumbnail are shown.
6- Add the following Field Variable to the Relationship Field:
```
key: showFields
value: title, {variable name of the binary field}
```
7- Go back to the parent contentlet and see the issue.

### Acceptance Criteria

When adding a binary or an image field to the showField should show a thumbnail of the file if possible.

### dotCMS Version

22.03+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112164

**Comment by erickgonzalez** [comment]
Needs Work! Now it's not showing the path but is not showing the thumbnail

![Screenshot 2023-09-20 at 2 09 44 PM](https://github.com/dotCMS/core/assets/5278970/f6bf788e-a48c-40f6-9b50-cd26d782a9cc)

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are showing the thumbnail after set the field variable. 

![Image](https://github.com/dotCMS/core/assets/2641437/e957d242-b245-431c-b679-2651311469b1)

**Comment by waqasakramdot** [comment]
Does this issue solve the problem for both Binary and Image fields? To get detailed information, please refer #26418

**Comment by erickgonzalez** [comment]
@AndreyDotcms can you check if this works for both fields, as @weiyiwang-dotcms is asking?

**Comment by AndreyDotcms** [comment]
Hello @waqasakramdot  and @erickgonzalez, I fixed the issue for both field types and tested the functionality. I have rechecked it again and everything works correctly.


https://github.com/dotCMS/core/assets/127987858/6ba76de9-c124-4892-97d7-93d57667cf66

**Comment by erickgonzalez** [comment]
Awesome, thanks for the confirmation @AndreyDotcms.
