### ISSUE TITLE
Include Slack notification when publishing master docker image 

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#25416]
### User Story

As a dev-ops, I want to receive a Slack message bot notification when publishing a Docker image by pushing to the `master` branch.

### Acceptance Criteria

- When a Docker image is published by pushing to the `master` branch, a Slack message bot notification is sent.
- The Slack message should include details such as the name of the Docker image, the commit message, and the username of the person who pushed the changes.
- The Slack notification should be sent to a specified channel or a list of channels.

### dotCMS Version

master

### Proposed Objective

The objective of this user story is to improve the deployment process by providing immediate notification to the dev-ops team when a Docker image is published.

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

_to_define_

### Assumptions & Initiation Needs

- The Slack workspace and necessary permissions for the bot integration have been set up.
- The deployment process uses Git for version control and Docker for containerization.

### Quality Assurance Notes & Workarounds

_to_define_

### Sub-Tasks & Estimates

- Configure the Slack bot integration (2 hours)
- Update the deployment script to trigger the Slack notification (4 hours)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25555

**Comment by dsilvam** [comment]
Passed QA - messages properly sent
