### ISSUE TITLE
Change Test Results Github Action to be more generic to include more test types

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#25415]
### User Story
As a dev-ops engineer, I want to adapt DotCMS's core test results publishing Github Action to be more generic and accept other types of tests.

### Acceptance Criteria
- The adapted Github Action should be able to handle test runs for different types of tests, such as `pentest` and `CLI`.
- The adapted Github Action should store the results of these tests effectively.

### dotCMS Version
master

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates
_to_define_

**Comment by dsilvam** [comment]
QA Passed: based on feedback from the devs.
