### ISSUE TITLE
[UI] Fixes in Chart of Experiment's Reports

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25427]
### Problem Statement

- `Y-axis` shows decimals
-  Use `sessions.variants` to show the conversions in Y-axis instead of `multiBySession` from the endpoint
- Start the char in 0

### Steps to Reproduce

- Run all experiments Infrastructure, 
- Create one experiment with variants and a goal
- Use the page to get values.

### Acceptance Criteria

- Not show decimals in Y-axis
- The conversions from the chart and the Summary table have to be the same values.

### dotCMS Version

master.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Imagen from QA
![Image](https://github.com/dotCMS/core/assets/1909643/3812ce37-d19b-40e1-8be4-ef2b5552b167)

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is showing just entire numbers, no more decimals. 

Working as expected.
