### ISSUE TITLE
[UI] Show a no `Analytics App not Properly Configured` page

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25425]
### User Story

As a user, I want to know early as possible if the experiment App is properly configurated.

### Acceptance Criteria

- Create a Guard to precheck if I can go to Experiment's List
- If the `Analytics App` is not properly configurated show an Empty page with the final design and information
- Validate if the app is properly configurated from `/v1/experiments/_healthcheck` response

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Screenshot 2023-06-27 at 12 10 52 PM (1)](https://github.com/dotCMS/core/assets/1909643/0ea837fd-39de-4fa2-8799-d0bf348751f1)

**Comment by oidacra** [comment]
Waiting for https://github.com/dotCMS/core/issues/25504 endpoint.

**Comment by freddyucv** [comment]
Pass Internal QA: Working as Expected

**Comment by bryanboza** [comment]
Fixed, we can close this card for now, this functionality needs will be modified by this new card #https://github.com/dotCMS/core/issues/25876
