### ISSUE TITLE
Some sites do not appear in the site selector drop-down menu unless the site is searched for

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#25429]
### Parent Issue

I'm not sure if this may be related to how the site-selector menu only displays up to 15 of the most recently edited sites.

I filed another Github feature ticket for this [here](https://github.com/dotCMS/core/issues/25420)

My hunch is that dotCMS first filters for the 15 most recently modified sites, then it shows the user the sites he has access to out of those 15 sites.

### Problem Statement

When there are many sites for a dotCMS instance, users may not see all the sites they have access to in the drop-down selection menu for sites. This is happening just for some users and not all, but for that subset of users, this issue occurs consistently.

It does not block them completely from accessing their sites. They are able to search for their sites using the search bar, and the missing site pops up at that point.

### Steps to Reproduce

Log in to a dotCMS instance that has more than 15 sites
Click the site-selector drop-down menu and note which sites are shown. (Currently, there is a limit of 15 on how many sites will be shown in this menu)
Log in as another user who does not have privileges to all the sites
Even though the number of sites is fewer, the sites may not all show up when this user clicks the site drop-down menu

### Acceptance Criteria

Have the site drop-down menu show all sites for which the particular logged in user has access

### dotCMS Version

23.01

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
I just wanted to let you know that this is intended. The filter box is the way to search for sites.
