### ISSUE TITLE
When filter by All in the Browser Portlet we are showing the No DEFAULT Version of the Contentlet

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25478]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

If we create a new Version of any pages on any no DEFAULT Variant this new version is showed on the Browser Porllet when the Filter is All

![image (4)](https://github.com/dotCMS/core/assets/10408015/bcd940f0-63d2-4122-bcde-e57f4be1204f)

### Steps to Reproduce

- Start dotCMS with the full starter
- Create a new Experiment using Index Page.
- Create a new Variant, and change the banner.vtl using the Edit file button.
- Go to the Browser Portlet and change the filter to show All, also go to application/containers/banner.
- You are going to see the banner.vtl file twice.

### Acceptance Criteria

We must not show the Variant version on the Browser Portlet

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Banner in Variant excluded from the Site Browser as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c74b482_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
