### ISSUE TITLE
Editing a Page is Loading the Material Icons Relatively

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25472]
### Problem Statement
Currently, when users edit a page in dotCMS, the material icons load relatively instead of absolutely, which causes the page to not render correctly.

### Steps to Reproduce
1. Login to dotCMS.
2. Edit an existing page.
3. Observe that the material icons are loading relatively instead of absolutely.

### Acceptance Criteria
- All references to material icons should be loading absolutely.
- All pages should render correctly with the material icons loading absolutely.

### External Links
N/A

### Assumptions & Initiation Needs
- We assume that the reference to material icons is in the front end code.

### Quality Assurance Notes & Workarounds
- To test that the material icons are loading correctly, users can preview the page and observe the rendering.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
