### ISSUE TITLE
Process Variants as a separate entity when Push Publishing

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25479]
### Parent Issue

https://github.com/dotCMS/core/issues/25134

### User Story

As a Push Publish User, I need that the Variants created during an Experiment get successfully pushed when push publishing an Experiment. 

### Acceptance Criteria

Variants successfully being pushed to the Receiver when pushing an Experiment. 

This requires: 

- [ ] * Add Variants as dependencies of an Experiment
- [ ] * VariantWrapper
- [ ] * VariantBundler
- [ ] * VariantHandler

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass Internal QA: When you sent an Experiment that has a Variant the Variant is sent as Dependency.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
