### ISSUE TITLE
Template Builder: Identifier is displayed instead of container's name after changing layout and adding several containers

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25485]
### Parent Issue

Template Builder

### Problem Statement

When the layout is adjusted to a left sidebar and several containers are added, the system begins to display the identifier of the container instead of its name

### Steps to Reproduce

1. Go to /dotAdmin/#//templates
2. Create a designer template 
3. Change the layout to a left sidebar
4. Add multiple containers to the sidebar
5. Notice that the system displays the identifier of the container, not the name

### Acceptance Criteria

Upon changing the layout to a left sidebar and adding multiple containers, the system presents the identifier of the container instead of its name.

### dotCMS Version

23.07

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

![Screenshot 2023-07-11 at 2 54 56 PM](https://github.com/dotCMS/core/assets/129882031/6509205f-e323-43c4-b4da-7c796aaba930)

**Comment by danielmdob** [comment]
Passed internal qa:
<img width="789" alt="image" src="https://github.com/dotCMS/core/assets/29465918/0485ded4-d913-4215-bd3c-bca2a99bd4ea">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d0a4af2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
