### ISSUE TITLE
Block Editor: Add Superscript and Subscript Mark

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25489]
### User Story
As a user, I want to be able to add superscript marks in the block editor, so I can easily add formatting to my content. 

### Acceptance Criteria
The block editor should have an option to add superscript marks in the text. 

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
No assumptions or initiation needs

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by wezell** [comment]
Are we better served making this an example of a custom mark?

**Comment by danielmdob** [comment]
Was doing some tests when I noticed it was possible to do an interesting text combination, at least when using the hotkeys for the tiptap editor. Namely having superscript text in the subscript, and the other way around. Do we want to allow that behavior?

### Screenshots:

**In editor**
<img width="497" alt="image" src="https://github.com/dotCMS/core/assets/29465918/a8a3646b-d89b-45f8-adcb-86b065906b27">

**In HTML**
<img width="523" alt="image" src="https://github.com/dotCMS/core/assets/29465918/6de5a774-f6c9-44bc-a889-a11e661dc16c">

**Comment by fmontes** [comment]
> Was doing some tests when I noticed it was possible to do an interesting text combination, at least when using the hotkeys for the tiptap editor. Namely having superscript text in the subscript, and the other way around. Do we want to allow that behavior?
> 
> ### Screenshots:
> **In editor** <img alt="image" width="497" src="https://user-images.githubusercontent.com/29465918/254703882-a8a3646b-d89b-45f8-adcb-86b065906b27.png">
> 
> **In HTML** <img alt="image" width="523" src="https://user-images.githubusercontent.com/29465918/254704074-6de5a774-f6c9-44bc-a889-a11e661dc16c.png">

If tiptap allow it, we cool.

**Comment by zJaaal** [comment]
# Passed Internal QA

Tested on Docker Image: `[dotcms/dotcms:master_2e3b05d_SNAPSHOT]`

## Screenshot

https://github.com/dotCMS/core/assets/63567962/3beba002-fa61-447b-925b-83f454dfa9e3

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_df40f48_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
