### ISSUE TITLE
[UI] Add icons to Experiments Goals

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25495]
### User Story
As a user, I want to identify the Experiments goals with an Icon.

### Acceptance Criteria

- add a icon as designed at the figma.

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Image](https://github.com/dotCMS/core/assets/31667212/4d5538ac-760e-4e54-8718-9bdd1b325016)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/25528

**Comment by oidacra** [comment]
IQA Passed:
All the Goals have icons.

<img width="949" alt="Screenshot 2023-07-26 at 1 31 34 PM" src="https://github.com/dotCMS/core/assets/1909643/1d5dad2a-eaa2-42af-a1c5-8d0e3dff655e">

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. Now each goal have their own icon
