### ISSUE TITLE
Edit Contentlet: Find out what properties, metadata or info a File and Binary field have

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25503]
### Parent Issue

#23599 

### Task

We need to figure it out  properties, metadata or info a File and Binary field have for the UX design.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Make a list of all the properties, metadata or info a File and Binary field have.

**Comment by jcastro-dotcms** [comment]
Here's the list of properties (metadata) that are generated from files in dotCMS:
1. `modDate`
2. `sha256`
3. `length`
4. `title`
5. `version`
6. `isImage`
7. `fileSize`
8. `name`
9. `width`
10. `contentType`
11. `height`

Files of the following type return all the previous 11 metadata properties:
* `GIF`
* `MOV`
* `PNG`
* `JPEG`
* `WEBP`
* `SVG`

Files of the following type **DO NOT** return neither the `width` nor `height` properties, as expected:
* `PDF`
* `TXT`
