### ISSUE TITLE
Create a health check endpoint for Experiments configuration

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25504]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As an Experiment user, I need a message stating that what's needed to use the Experiment feature is not properly configured with the option of contacting support. For this an endpoint for health checking is needed. 

### Acceptance Criteria

Having an endpoint available for heath checking Experiments feature
`/v1/experiments/health`

Responses:
* No id
* Not configured properly

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass Internal QA: It return false if:

- dotCMS can not get the analytics key: Client ID or Secret are wrong.
- The Jitsu Server URL was set wrong.
- The app is not config at all

- But when the CubeJS Server URL is wrong it return TRUE any way, we are going to fix it on another card

**Comment by bryanboza** [comment]
We will close this card for now, we need some extra work here, we move this to the card #https://github.com/dotCMS/core/issues/25893
