### ISSUE TITLE
[UI] Task: Add the Chart of the 2/3 standard curves.

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25519]
## Parent Issue
#24982 

## Acceptance Criteria
- Show a chart with the 3 standard curves
- Add a Tab with the name `Bayesian Results`

## Proposed Objective
User Experience

## Proposed Priority
Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA. Curves showing appropriately when having successes and failures on the original and variants. 

![Image](https://github.com/dotCMS/core/assets/1576794/603dc36f-3992-41ce-85b5-b584bf547d2f)
