### ISSUE TITLE
Export assets without old versions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25510]
### Task

It would be great to be able to download the assets directory of just the live and working files, without having to download old versions.  My thinking is doing something like this:

Build an in memory bloomfilter of all inodes from the live and working versions - keep in mind that this list can be huge - millions of ids.  Here is an easy way to construct a bloomfilter:

https://www.baeldung.com/guava-bloom-filter

And here is the sql query for the live and working inodes.
 
```
select 
  live_inode 
from 
  contentlet_version_info 
where 
  live_inode is not null 
UNION 
select 
  working_inode 
from 
  contentlet_version_info 
where 
  working_inode <> live_inode 
and 
  working_inode is not null
```

then when building the list of assets to include, we would use a file filter to exclude those whose inodes are not in the bloomfilter.  This would prevent older versions of the assets from being included in the zip.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

1. Go to the **Settings > Maintenance > Tools** portlet.
2. In the **Export dotCMS Content**, click both the `Download Assets` and the `Download Data/Assets` buttons.
3. You must see a dialog asking if you want to include old assets versions or not. If you choose to include them, the generated ZIP file will be larger compared to not including them.

**Comment by fmontes** [comment]
Check the PR.

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: PASSED
- Docker Image: `master_11244bf_SNAPSHOT`

In the **Settings > Maintenance > Tools** portlet, in the **Export dotCMS Content** section, when clicking either the `Download Assets` or the `Download Data/Assets` buttons, the following dialog will show up:

<img width="474" alt="Screenshot 2023-08-28 at 9 28 22 AM" src="https://github.com/dotCMS/core/assets/8779585/1075f486-9ab4-42ff-b524-6639d8b70cbe">

If Users click `Yes`, the generated bundle will include absolutely all versions of the assets in dotCMS. If they click `No`, only their live and working versions will be added.

Using the Full Starter, including all asset versions generated a 265,2MB bundle, whereas NOT including them generated a 99,5MB bundle.

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA
All download buttons inside the `Export dotCMS Content` in the `Settings > Maintenance > Tools` portlet must be tested to make sure the new dialog shows up where it's expected.

Additionally, the generated Starter ZIPs must be tested as well.

**Comment by fmontes** [comment]
From @jcastro-dotcms 

Here’s the list of steps you can follow to verify the correct behavior of the Binary Cleanup Job:
1. Set the following configuration properties in the docker-compose.yml file:
```
DOT_BINARY_CLEANUP_JOB_CRON_EXPRESSION: '0 0/3 * 1/1 * ? *'
DOT_CLEANUP_TMP_FILES_OLDER_THAN_HOURS: 0
DOT_CLEANUP_BUNDLES_OLDER_THAN_DAYS: 0
```
2. Start up dotCMS with an Enterprise License.
3. Create some File Assets so that temp files are generated.
4. Add contents to a Bundle so that bundle files are created.
5. Wait for about three minutes and you should see the following message in the log:
```
STARTING TMP/TRASH FILE CLEANUP
```
And then:
```
ENDING TMP/TRASH FILE CLEANUP
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-09-27 at 10 03 50 AM](https://github.com/dotCMS/core/assets/129882031/3bc893d9-1287-47aa-b8cd-08a361a21ffa)
