### ISSUE TITLE
All Widgets are being rendered when converting to json without having to pass the render flag

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25523]
### Parent Issue

*No response*

### Problem Statement

When making an API call to content or a list of content, we are automatically trying to render the widgets in that content.  We should only be doing this if the api call has specified to return rendered content - this is currently causing issues in authoring as there is a widget that is doing `$request.sendRedirect("https://google.com")` and things like that that mungs up the underlying API request object.

### Steps to Reproduce

Create a new code widget with the value `${request.session.invalidate()}`.  Hit this widget from the backend using the content API - e.g. using a url like

https://demo.dotcms.com/api/content/id/d89d04a50c0724428d86fd12194194be
And it will cause you to logout.

You should have to pass `/render/true` or `?render=true` in order for velocity to try to render the content.  Also, we should not be reusing the underlying API request when doing the render and instead should be using a MockRequest that has the same properties to avoid any underlying funk.

### Acceptance Criteria

Have to pass `/render/true` or `?render=true` in order for velocity to try to render the content.

### dotCMS Version

23.06

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*

**Comment by erickgonzalez** [comment]
Reproducible on 23.01 LTS but no on 22.03 LTS

**Comment by wezell** [comment]
Caused by the changes here: #21079

**Comment by dcolina** [comment]
### Internal QA: Passed

Based on the attached video, the functionality behaves as expected, and the Internal QA is approved.


https://github.com/user-attachments/assets/1065a311-4aa6-41db-ab72-9305bdabb8ee

According to the feature specifications, widgets are not rendered automatically. Rendering must be triggered explicitly using `/render/true` or `?render=true`. As seen in the JSON, the `code` key contains the defined block of code, while the `parsedCode` key displays the rendered output. In this specific case, we can observe the result of the defined sum operation. Furthermore, a code injection test to disable the session was performed, and as expected, it was not executed, ensuring the functionality is secure and working correctly.

This verification demonstrates compliance with the specifications and validates the correctness of the implementation.

**Comment by bryanboza** [comment]
Fixed, tested and now we are unable to excecute malisious code here. 

Tested with an example of velocity and now it is working as expected. 
![Image](https://github.com/user-attachments/assets/c82a5267-5c61-46e2-9566-8fa486328a2d)

#### Result after pass the parameter 
![Image](https://github.com/user-attachments/assets/3b07eb0f-ff72-4899-a81e-eba0f373619c)

**Comment by mbiuki** [comment]
Please check this conversation: https://dotcms.slack.com/archives/C5LHLNZ25/p1732822029694909

**Comment by fabrizzio-dotCMS** [comment]
We're currently mocking the request that gets passed into the velocity context.  The mocked request has been limited to only allow accessing attributes. We need to override the getCookies Method to cut that functionality on the mocked request, too.

**Comment by mbiuki** [comment]
https://github.com/dotCMS/core/issues/30840 will cover the remaining work.
