### ISSUE TITLE
[UI] Move detail table to be reusable 

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25520]
### Parent Issue
#24982

### User Story
Move the table to be reusable between Bayesian and daily chart. 

### Acceptance Criteria

<img width="1164" alt="image" src="https://github.com/dotCMS/core/assets/31667212/3d9568d1-1f68-4c54-a7a6-6fa6acce98d5">

<img width="1133" alt="image" src="https://github.com/dotCMS/core/assets/31667212/fae4dff8-cdca-4517-98c6-72e9215a4809">

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by oidacra** [comment]
IQA Passed:
The same detail table showed below charts.

Daily Results
<img width="1210" alt="Screenshot 2023-08-01 at 6 03 31 PM" src="https://github.com/dotCMS/core/assets/1909643/33751ce3-393a-4214-a5f4-8dc57202bc24">

Bayesian Chart
<img width="1235" alt="Screenshot 2023-08-01 at 6 03 36 PM" src="https://github.com/dotCMS/core/assets/1909643/f0d7c061-f5da-4a9d-8b55-8446937d3b8c">

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF
