### ISSUE TITLE
Fix the Site Search Schedule Window

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25542]
### Problem Statement

At some point in the dojo upgrade/ui update the site search scheduler fails to render. We need this to render.
![Screenshot 2023-07-18 at 1 49 15 PM](https://github.com/dotCMS/core/assets/934364/680d6133-b5a8-4124-89b0-aa393a81a132)

### Steps to Reproduce

In the starter site, click on `Dev Tools > Site Search > Job Scheduler` and you will see a blank screen.  You should see fields that allow you to schedule the site search job. 

### Acceptance Criteria

You should see fields that allow you to schedule the site search job. 

### dotCMS Version

23.07

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by wezell** [comment]
Also see #24524

**Comment by fmontes** [comment]
This is working in master and demo.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_eb200d2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
