### ISSUE TITLE
Cancel a Running/Scheduled Experiment

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25548]
### Parent Issue

https://github.com/dotCMS/core/issues/25547

### User Story

As an Experiments User, I want to be able to cancel an Experiment when it is Running or Scheduled which means it needs to go back to Draft state. 

### Acceptance Criteria

Allow Cancel a Running/Scheduled Experiment

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Tasks
- [ ] [UI] Add Cancel to Menu list in Experiment List
```

**Comment by dsilvam** [comment]
Passed Internal QA: Able to Cancel both Running and Scheduled Experiments. The Experiment goes back to DRAFT state as expected and in case it had an Scheduling defined it stays.

**Comment by bryanboza** [comment]
After abort an experiment it is coming back to Draft state, but we are not allowing to start the experiment again 

![Image](https://github.com/dotCMS/core/assets/2641437/6ca27a2a-7168-4179-b94e-544610d2aca5)

**Comment by dsilvam** [comment]
Passed Internal QA: Able to start the Experiment right away after aborting it.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. 

Now this is working as expected.
