### ISSUE TITLE
[Redis] : Create sample `docker-compose.yml` files for the Redis Session Manager feature

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#25541]
### Parent Issue

https://github.com/dotCMS/core/issues/24294

### Task

We need to create the `docker-compose.yml` files for showcasing the Redis Session Manager feature in a clustered dotCMS environment. This must also include the expected `README` file explaining how it can be activated/deactivated, along with the most important configuration properties.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

As an additional task, as discussed during the Lunik PO meeting, Docker examples related to MS SQL Server should be removed from our repository as only PostgreSQL is being supported now.

**Comment by bryanboza** [comment]
Fixed, tested starting a dotCMS with redis instance with the provided example.
