### ISSUE TITLE
Add specific date to the content workflow history screen - 5.1.6

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25554]
### User Story

In order to satisfy compliance requirements, it is important that the user and date/time is shown for when a content or asset is published or approved in dotCMS.  In newer versions, we have this data visible on the workflow screen.  In older versions, we only provide the vague "More than a year ago" type messages.  We need to create a hot fix plugin that includes the specific date/time in the task detail screen.

We should also add this to the 5.1.6.k branch/build.

![Screenshot 2023-07-19 at 9 18 27 AM](https://github.com/dotCMS/core/assets/934364/e9695596-69d0-4403-827e-8e0f3620c6a1)

Internal Ticket: https://dotcms.zendesk.com/agent/tickets/111749

### Acceptance Criteria

Show the specific date and time that an asset has been approved/published or pushed through the workflow.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
I think this is the line ```<div style="float:right;"><%=UtilMethods.dateToHTMLDate(comment.createdDate()) %> - <%=UtilMethods.dateToHTMLTime(comment.createdDate()) %></div>```

**Comment by erickgonzalez** [comment]
There is already a hotfix with this https://github.com/dotCMS/support/blob/master/hotfixes/hotfix-GIT-17532_v5.1.6/ROOT/dotserver/tomcat-8.5.32/webapps/ROOT/html/portlet/ext/workflows/view_workflow_task.jsp#L340
