### ISSUE TITLE
Unable to Search for Non-English Pages with the Block Editor Hyperlink Feature

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#25567]
### Problem Statement

The block editor field includes an option to add hyperlinks to text. When adding a hyperlink, there is a search bar that appears. Searches from that search bar only return results for pages that are set to English.

### Steps to Reproduce

1. Navigate to demo.dotcms.com
2. Create a new content type "Test Hyperlink"
3. Add a block editor field to the content type
4. Create and publish 2 new pages
  a. "Page English" with English set as the language
  b. "Page Spanish" with Spanish set as the language
5. Create a new content using the "Test Hyperlink" content type, setting the language to English
6. Add some text, highlight the text, and add a hyperlink
7. In the search bar that appears, search for "page". You should notice that only "page-english" appears as an option
8. Change the language of the content you are trying to create to Spanish
9. Repeat steps 6 and 7. Only "page-english" will appear, even though we would expect "page-spanish" to appear.

### Acceptance Criteria

Have the hyperlink search feature in the block editor return pages for the corresponding language pages.

### dotCMS Version

23.01.3

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112456

You will notice in the attached screenshot that the request for _search has languageId:1 as part of its query.

![Screenshot 2023-07-19 at 12 21 16 PM](https://github.com/dotCMS/core/assets/136110669/065a409e-09c9-4e7a-8590-7a6545944f2b)

**Comment by fmontes** [comment]
Fix the query and make sure that includes: dotAssets, fileAssets, Pages and URLMaps contentlets.

**Comment by fmontes** [comment]
This might results in some changes in the Pages listing query.

**Comment by danielmdob** [comment]
Passed internal QA, screenshot:



![Image](https://github.com/dotCMS/core/assets/29465918/60d36300-ef0f-402e-bcdc-5ef025c66cdf)

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS
