### ISSUE TITLE
Template Builder: Implement Autosave in the template portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25573]
### User Story
As a dotCMS user, I want to have the ability to autosave my work in the template builder, so I can more easily track changes and avoid data loss.

### Acceptance Criteria
- Autosave should be enabled by default
- Autosave should save the template every 5 seconds
- Autosave should have the same approach as the layout editor

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Autosave should not interfere with any existing functionality 
- Autosave should work across all browsers

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by zJaaal** [comment]
## Passed Internal QA

Docker Image: `[dotcms/dotcms:master_524e70e_SNAPSHOT]`

### Screenshots
#### Templates Portlet
https://github.com/dotCMS/core/assets/63567962/69231599-58db-4b48-9bd9-ad435ecc211b
#### Edit Page Portlet
https://github.com/dotCMS/core/assets/63567962/a47c3b13-9e11-49a9-9007-1e62124f5efe

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
