### ISSUE TITLE
Redis / Session-less testing and improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25570]
### Parent Issue

https://github.com/dotCMS/core/issues/24990

### Problem Statement

We have redis session sharing hooked up to our testing environment and have turned off sticky sessions.  There are a few issues that I have seen and need to be tested/validated in a sessionless environment.

- [x] Test that limited users can login.  I tried to create a limited user and was not able to login to the back end.
- [x] Test that "Login As" works. I was not able to login as either
- [x] Test that the front end login works.  I could see it work under the `/members` path for "Bill Internet"  but when I tried to create a new User and login to the front end, it did not work.
- [x] We will probably also have to test to make sure that SAML login works.

### Steps to Reproduce

Set up a clustered testing environment without sticky sessions.  Test that the above work consistantly.

### Acceptance Criteria

We should be able to complete the above.

### dotCMS Version

23.07

### Proposed Objective

Application Performance

### Proposed Priority

Please Select

**Comment by bryanboza** [comment]
Fixed
