### ISSUE TITLE
Update Build / Release Information

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25571]
### User Story

We get a lot of our build information from `ReleaseInfo.class` that relies on gradle's build properties.  This does not work with our current and future release process.  Instead, we need to update that class to show information that should be read/calculated during the build process, including the git tag (or branch if not a tag), the git hash of the build and the build date/time.

Also, we need to think about this working when we convert to maven builds.  We cannot write the logic in Gradle.

### Acceptance Criteria

See the attached for what info we should be seeing in the System Info tab for "ReleaseInfo".  4 properties:

- version
- buildDate
- build
- name

![Screenshot 2023-07-19 at 4 07 35 PM](https://github.com/dotCMS/core/assets/934364/a1381c83-9a68-41d4-ac34-5e66988fb8d5)

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by spbolton** [comment]
Ok,  it may need a little tweaking but in the parent/pom.xml file we have the buildnumber-maven-plugin that will run on all modules. This should be adding to the META-INF on the jar files, although there may be an issue with the META-INF not being created on the main core jar atm.  The configuration of the plugin is currently just and example and we can customize this how we need. 
  
I also have it configured to drop a properties file.  this is currently going into target/classes/build.properties, so is readable from the classpath.  It may be possible to use maven resource filtering to template any values into the existing properties file, but that may be a little more risky and harder to implement.    What values we want to add we will have to work on.   The plugin pulls in some standard properties and commit hash but some of the values we may need to define as maven properties and will override as a -D parameter in the build step this would include the build run id and the branch name or pr id / name. https://www.mojohaus.org/buildnumber-maven-plugin/

```
#Created by build system. Do not modify
#Mon Oct 02 14:11:29 EDT 2023
name=dotcms-core
version=1.0.0-SNAPSHOT
timestamp=1696270289204
revision=7b76a372a9e4839c5bef0156efd47b2a390a22f6
```

Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 11
Build-Tool: Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c
 )
Build-Jdk: 11.0.20.1 (Eclipse Adoptium)
Build-Os: Mac OS X (13.5.2; aarch64)
Specification-Title: dotcms-core
Specification-Version: 1.0
Implementation-Title: dotcms-core
Implementation-Version: 1.0.0-SNAPSHOT
Implementation-URL: https://github.com/dotCMS/dotcms-build-parent/dotcms
 -core
Java-Vendor: Eclipse Adoptium
Java-Version: 11
Os-Arch: aarch64
Os-Name: Mac OS X
Os-Version: 13.5.2
SCM-Build: ci-maven-sonarqueue-site
Scm-Connection: scm:git:git@github.com:dotCMS/core.git
Scm-Revision: 7b76a37
Scm-Url: https://github.com/dotCMS/core

**Comment by fabrizzio-dotCMS** [comment]
I tested the build generation using Maven
The generated build that is displayed on  System | Maintenance | System Info matches the last commit number. 

![Screenshot 2023-11-16 at 13 00 35](https://github.com/dotCMS/core/assets/37148755/ef20a469-0d6c-4f82-9149-de2906006073)

Some of the other properties displayed have changed their value like 
name, which used to be  dotCMS Platform 
and version which according to the screenshot should have had the tag or branch name 

According to this thread 
https://dotcms.slack.com/archives/CQNF9PCFQ/p1698168804390869
stakeholders agree that whatever value is used in the .properties file is what should be displayed 

However, in the conversation, it is also stated that the build date and time should be displayed and currently we're only seeing the date. 


![Screenshot 2023-11-16 at 11 23 09](https://github.com/dotCMS/core/assets/37148755/883e6652-86fc-4343-97d2-fe26911a49ac)

**Comment by fabrizzio-dotCMS** [comment]
The new version shows the build info satisfactorily 
![Screenshot 2023-11-21 at 14 32 18](https://github.com/dotCMS/core/assets/37148755/fe23ed01-cbf8-4703-a7b9-168c54b5a3ed)

**Comment by bryanboza** [comment]
We need to revert some changes here: https://github.com/dotCMS/core/pull/27023 

After it we need to retest this card.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
