### ISSUE TITLE
Add Contentlet inside Original change Variants too

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25590]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When we add a Contentlet on the Original/Default Variant outside an Experiment it Contentlet is included inside any Experiment's Variant too

### Steps to Reproduce

1. Create a Page.
2. Create an Experiment using the newly created Page.
3. Create a Variant and called it V1
4. Add a Contentlet to the Page outside the Experiment.
5. Go to Edit the V1 Variant and the newly created Contentlet is going to be showed inside the Variant.

Before the Step 4 you need to clean the Cache for the moment when this issue was created, but after finish this issue 
https://github.com/dotCMS/core/issues/25221  that is not going to be need.

### Acceptance Criteria

The newly contentlet must not be showed in the Variant.

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/26026

**Comment by dsilvam** [comment]
Passed Internal QA: Content added outside of Experiment/Variant is not visible inside Variants.
