### ISSUE TITLE
Variable Typo in Block Editor

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#25591]
### Problem Statement

The word count and character count variables that currently appear in the Block Editor are, respectively, `wordCount` and `chartCount`. I think the second one should probably be `charCount`.

I made a PR to rectify it: https://github.com/dotCMS/core/pull/25589

However, I'm just opening up this Issue in case there's discussion needed re: the existing `chartCount` variables in the existing Block Editors out in the wild. Does something like this require a UT? Is it reasonable to believe it will correct itself over time?

I'll include a minor breaking change entry in the following release notes, too, in case anyone has done any development using that data.

### Steps to Reproduce

N/A

### Acceptance Criteria

Just making sure that there are no dangers or snags.

### dotCMS Version

22.12 - 23.07

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by fmontes** [comment]
Let's check if this fix is ok or needs work.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_f113f07_SNAPSHOT`

If you save a Contentlet with a Block Editor field and check the payload in the POST request, you can see that the property is called `charCount` now.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_658e1bc_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
