### ISSUE TITLE
Need to create postman test for the promote endpoint 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25592]
### Problem Statement

As part of the rules, every new endpoint should have the postman test in order to have a good testing coverage in our CI/CD process, after create this endpoint we don't add those test. 

### Steps to Reproduce

Promote Experiments API

### Acceptance Criteria

- Positive tests
- Negative tests
- Validate response codes 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Duplicate of https://github.com/dotCMS/core/issues/26208
