### ISSUE TITLE
[UI] Update the payload of the URL Parameter Goal to match endpoint update

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25598]
### Parent Issue
#25187 

### User Story

Update payload to match endpoint update and  add validation. 

### Acceptance Criteria

1. Update de UI to mach a new payload of the backend. 

```
{
  "parameter": "queryParameter",
   "operator": "EQUALS",
   "value": {
      "name": "testName",
      "value": "testValue"
    }
}
```

2. When the Operator is `EXIST` value should not be required and be disabled. 
 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by freddyucv** [comment]
Pass Internal QA: working as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
