### ISSUE TITLE
Rebuild Edit Locale Page

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25606]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

We are rebuilding the Edit Locale workflow.

![image](https://github.com/dotCMS/core/assets/114953617/7b293992-4d50-43d2-b948-36f53133d455)

Current Demo Site Reference Link :https://demo.dotcms.com/dotAdmin/#/c/languages 

Need to re-do this delete window as well.

<img width="440" alt="image" src="https://github.com/dotCMS/core/assets/114953617/dd746b38-015a-4a5a-9e97-3fbca075ac2d">

And let’s move the “Make Default” from the List Language Page Right Click Menu over to the Edit Language Page. This is a major action, doesn't belong in just a right-click menu. Should have some sort of "Confirmation" screen like "Type locale 'EN-US' to continue."

<img width="335" alt="image" src="https://github.com/dotCMS/core/assets/114953617/f57906fa-2690-45cb-8ac6-30aa8bee8c7e">

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent

### Acceptance Criteria

Edit Locale

<img width="537" alt="image" src="https://github.com/dotCMS/core/assets/114953617/fb89f7c7-1025-477a-835d-97bc4905c024">

* On the Edit Locale screen, only the "Locale Display Name" is editable.
* For the Locale Display Name, users can put in anything they want, say up to 50 characters. We can sanity check this with some real world examples, like "Cook Islands Māori (mi-ck)" (which is about the longest language I can find.)

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* UX Designs for this screen in Figma - https://www.figma.com/design/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=755-99112&t=fVFBeDmef9gr7FYh-4

* Localization Improvements - Phase 1 | dotCMS Internal Documentation - Google Docs || https://docs.google.com/document/d/1bjEM89vkt8TUcKiNgbCY8BPYfpTg_AX3Sb-Brxvy5AA/edit#heading=h.1au2wb52pnxk

### Sub-Tasks & Estimates

```[tasklist]
### Tasks

```

**Comment by john-thomas-dotcms** [comment]
This is done
