### ISSUE TITLE
Rebuild Add New Locale Workflow

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25605]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

We are rebuilding the Add New Locale workflow.

![image](https://github.com/dotCMS/core/assets/114953617/e302476a-93be-45f8-bb6c-a6edc7090e04)

Current Demo Site Reference Link :https://demo.dotcms.com/dotAdmin/#/c/languages 

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent

### A new window starts with "Standard Locale" selected...

<img width="427" alt="image" src="https://github.com/dotCMS/core/assets/114953617/e774c44f-d9b2-406c-9447-1968d4a97666">

* For the "Standard Locale" view, Language is Required, but Country is optional.
* The point of this screen is to help a user build a "standard" Locale ID.
* As a user selects a Language and Country, this will define the Locale ID field. For example, selecting the Language "English - en" would give the Locale ID of "en". If the user continues and selects a country, the Locale ID field would be appended, so like if a user picked a Country of "United States - US" then the final Locale would be "en-us" (keep the Locale ID lower-case).
* There is no "Locale Display Name" field shown, but (from the example above) we'll store that data as "English (en-us)" or "English (en)" -- "{Language} ({Locale ID})" is the pattern.
* Since Language is a required field, we can either disable to Locale Button until a Language is selected, or we can give an error message if the User tries to "Add Locale" before selecting a Language. Suggest, "A Language is required to create a Locale."
* We also have to check to ensure that the Locale ID is not already in use by that Customer. If, for example, they already have "en-us" defined, we would need to show an error message. Suggested, "This Locale ID is already in use."
* Note : For now, the Languages and Country drop-downs will all be in English; if users want to localize the Locale Display Names, they can use a Custom Locale.

### For the "Custom Locale" option...

<img width="438" alt="image" src="https://github.com/dotCMS/core/assets/114953617/f06eca33-bc18-44d5-9c06-1f18813223ce">

* For the "Custom Locale" view, we'll show two fields -- Locale ID, and Locale Display Name.
* For the Locale ID, users can put in any characters up to 5-letters. It's required.
* For the Locale Display Name, users can put in anything they want, say up to 50 characters. We can sanity check this with some real world examples, like "Cook Islands Māori (mi-ck)" (which is about the longest language I can find.) 
* Important that the Locale Display Name supports non-standard characters, so accents, or Chinese Characters would all be allowed.
* We also have to check to ensure that the Locale ID is not already in use by that Customer. If, for example, they already have "en-us" defined, we would need to show an error message. Suggested, "This Locale ID is already in use."

### Standard Locale

https://www.figma.com/design/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=755-97827&t=fVFBeDmef9gr7FYh-4

### Custom Locale

https://www.figma.com/design/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=1483-46681&t=fVFBeDmef9gr7FYh-4

### Sub-Tasks & Estimates
```[tasklist]
### Tasks

```

**Comment by john-thomas-dotcms** [comment]
This is done
