### ISSUE TITLE
Rebuild List Locales Page

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25604]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

We are rebuilding the Locales Listing Page.

![image](https://github.com/dotCMS/core/assets/114953617/f9507e29-8866-43a1-bc6d-8f4407c79b64)

Current Demo Site Reference Link : https://demo.dotcms.com/dotAdmin/#/c/languages

Note that items on this page have a Right Click menu.

<img width="315" alt="image" src="https://github.com/dotCMS/core/assets/114953617/527ae3ab-04b4-42d5-90d5-aa970075083d">

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent

### Acceptance Criteria

- Rewrite in Angular \(will also likely need to build out API to support this\)
- Redesign and Remove “Right Click Menu” Functionality
- In the Right Click Menu, we can ignore “Add To Bundle” as we’ll be removing this functionality.
- Since we’re moving all of the Language Variables to one page, we can ignore the “Edit Variables” for each language too.
- The button for “Edit Default Language Variables” can just be “Edit Language Variables” and we’ll show all the language variables there.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Localization Improvements - Phase 1 | dotCMS Internal Documentation - Google Docs || https://docs.google.com/document/d/1bjEM89vkt8TUcKiNgbCY8BPYfpTg\_AX3Sb-Brxvy5AA/edit#heading=h.jh28903atgoj

* UX Designs can be found here, when they are ready - https://github.com/dotCMS/core/issues/27594

* Figma: https://www.figma.com/file/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=0-1&mode=dev

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28456
- [ ] https://github.com/dotCMS/core/issues/28474
- [ ] https://github.com/dotCMS/core/issues/28993
- [ ] https://github.com/dotCMS/core/issues/29003
`\`\`

**Comment by nollymar** [comment]
**Note to QA:** Please test [this card](https://github.com/dotCMS/core/issues/27939) as well
