### ISSUE TITLE
Rebuild Edit Default Language Variables Page using Content Items

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25607]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

<p dir="ltr" style="line-height:1.7999999999999998;margin-top:8pt;margin-bottom:12pt;" id="docs-internal-guid-95bdcc8a-7fff-57f7-3dd7-e1eae237dd07"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:316px;"><img src="https://lh7-us.googleusercontent.com/8Vqa_YitbzJ-F7AxARFqaSj_LzjghjEN1iYXTbcH9Y12BmInVkBeP-_dihlW5-d5FD4_QlF6JQ29aNE9WbXHcgcqlgI5RNcL7qiyztTRQgspuBKASLj6hVZPcMcSWact4-wPrcwDOTBQYKFdjqj1RHw" width="624" height="316" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.7999999999999998;margin-top:8pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Current Demo Site Reference Link :</span><a href="https://demo.dotcms.com/dotAdmin/#/c/languages" style="text-decoration:none;"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#1155cc;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://demo.dotcms.com/dotAdmin/#/c/languages</span></a><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p><p dir="ltr" style="line-height:1.7999999999999998;margin-top:8pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">This page is like a translation matrix; when a developer uses a Language Key, depending on the locale selected it would show the following copy. Simplified example.</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

| Language Key               | EN-US \* | ES-US | ZH-US   |
| -------------------------- | -------- | ----- | ------- |
| cat-some-language-variable | Cat      | Gato  | 猫       |
| dog-some-language-variable | Dog      | Perro | 狗    | 

</div><p dir="ltr" style="line-height:1.7999999999999998;margin-top:8pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">* Indicates site&rsquo;s default locale.</span></p><p dir="ltr" style="line-height:1.7999999999999998;margin-top:8pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Assistant,sans-serif;color:#14151a;background-color:transparent;font-weight:300;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(Also note that Default Locale won&rsquo;t be under the Content Model &gt; Languages in the future. We need to move the default Locale to work on a site-by-stie basis.)</span></p>

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent

### Acceptance Criteria

- Rewrite in Angular (will also likely need to build out API to support this)
- Fix issue where page has multiple scrollbars and chops content half-way down.
- List All Languages, across in columns. 
- Site Default Locale, then All Other Locales in Alphabetical Order across the top. (It’ll be rare that any site will have more than 5 languages… 2-3 is generally the sweet spot.)
- We can get rid of the dropdown to filter by language, in the upper left.
- Have the Ability to Sort by Column, to easily show missing translations
- Preserve “Filter” Functionality, but improve UX so it’s clear what the empty box at the top does. 
- Language Key field needs to be long enough to easily tell what’s there without scrolling. Likely doesn’t / shouldn’t be a text field as it’s not really editable. Some values are long… com.dotcms.repackage.javax.portlet.title.c-All so maybe like “com.dotcms….title.c-All” (first 10 letters, and last 10 letters – with the full value shown on mouseover.) Good if these are still copy-able. May be cool to have a little mouse-over copy link, like Gmail does for email addresses.

<img width="357" alt="image" src="https://github.com/dotCMS/core/assets/114953617/65a3c6f0-9bcf-4103-bc1e-5082ab4bacec">

- The “Add New Property” button should be renamed to the “Add New Language Variable” button.
- Adding a language variable adds it for all available languages. And adding a new language adds the appropriate language variables for the new language.
- May work to use the “Row Editing” feature in PrimeNG Datatables. Suggestion for UX Design. https://www.primefaces.org/primeng-v14-lts/table/edit 

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Localization Improvements - Phase 1 | dotCMS Internal Documentation - Google Docs || https://docs.google.com/document/d/1bjEM89vkt8TUcKiNgbCY8BPYfpTg_AX3Sb-Brxvy5AA/edit#heading=h.i4uia7o6l3gd

* UX Designs can be found here, when they are ready - https://github.com/dotCMS/core/issues/27594

### Assumptions & Initiation Needs

#27703  will need to be completed before we can do this work.

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
```

**Comment by john-thomas-dotcms** [comment]
We've decided not to implement this screen at this time.  We can re-open this card when this project comes back on our roadmap.
