### ISSUE TITLE
Metadata keywords don't return in response to ES query and Content api

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#25618]
### Problem Statement

FileAsset metadata keywords don't return in response to ES query and content API.

### Steps to Reproduce

Create a Fileasset with keywords in metadata then try with ES query

`{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "wildcard": {
                  "metaData.keywords": "*keyword*"
                }
              }
            ]
          }
        },
        {
          "term": {
            "contenttype": "FileAsset"
          }
        }
      ]
    }
  }
}`

It will return FileAsset with metadata information but missing keywords.

And If you try content API `/api/content/id/bbd31ade-4435-440e-a3b9-1a52508542a4`, It will not return keywords in metadata as well

### Acceptance Criteria

I tested with keywords that don't return however Metadata should return all key-value pairs.

### dotCMS Version

23.*

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112436

**Comment by nollymar** [comment]
**Note to QA:** With these changes, it is possible to customize what keys are considered in the basic metadata using the property `BASIC_METADATA_OVERRIDE_KEYS` . The basic metadata is the only metadata info displayed as part of the apis response. This property is a comma-separated list and in case you don’t set it, we use these values by default: `version,name,title,path,contentType,sha256,isImage,length,fileSize,modDate,width,height`

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0
