### ISSUE TITLE
Template Builder: Improving UX for Drag Row

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25619]
### User Story 
As a dotCMS user, I want to be able to drag rows in the template builder with ease, so I can create templates quickly and intuitively.

### Acceptance Criteria 
- On mousedown, the element should lift right away and the cursor should become a grabbed cursor.
- User should be able to scroll while dragging rows.
- On mousedown and drag a box or row to show the grabbing cursor as well.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by zJaaal** [comment]
Found this error while running storybook. Might be related to this.
<img width="459" alt="Screenshot 2023-08-03 at 12 47 26 PM" src="https://github.com/dotCMS/core/assets/63567962/a1e18aa8-0d5e-4791-a433-102f441cbd2d">

**Comment by zJaaal** [comment]
## Failed Internal QA

When you add new rows or boxes the scroll on drag is lost for those items

Docker Image: `[dotcms/dotcms:master_524e70e_SNAPSHOT]`

### Screenshots
https://github.com/dotCMS/core/assets/63567962/064a4521-03c5-4409-9b35-1b89023f0342

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_74e2d1a_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
