### ISSUE TITLE
MonitorResource throws exception if DOT_SYSTEM_STATUS_API_IP_ACL is not set

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25613]
### Problem Statement

The MonitorResource throws an exception if the DOT_SYSTEM_STATUS_API_IP_ACL is not set.   This makes the resource return unhelpful error statuses like 400 or 500 and throw a stack trace in the logs.  This is because the default SYSTEM_STATUS_API_IP_ACL includes a ipv6 address  `0:0:0:0:0:0:0:1` which is un-parseable to the IPUtils.   

Unless the env variable DOT_SYSTEM_STATUS_API_IP_ACL is set without the ipv6 address, the monitoring endpoint does not work.

### Steps to Reproduce

Spin up a clean dotCMS instance.  Hit it with the following:

```
curl -v --header "X-Forwarded-For: 1.2.3.4" https://local.dotcms.site:8443/api/v1/probes/alive
```

You will get a 400 or 500 error and a bunch of errors in the logs.  

**Note:** the current demo.dotcms.com site has the `DOT_SYSTEM_STATUS_API_IP_ACL` set, so it does not suffer from this error

### Acceptance Criteria

You should either get a 403 forbidden if your ip address is not part of the list OR you should get a 200 if your ip is part of the DOT_SYSTEM_STATUS_API_IP_ACL

### dotCMS Version

23.07

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA:
Here's the list of steps to force dotCMS to return the `SERVICE_UNAVAILABLE` (503) and `FORBIDDEN` (403) statuses:

1. Start up dotCMS making sure it's up and running as expected.
2. Using Postman, create a GET Request with the following URL:
```
{{serverURL}}/api/v1/probes
```
3. Bring ES down.
4. Send the previous GET Request. You must get the `SERVICE_UNAVAILABLE` status.
5. Shut dotCMS down.
6. Update the `SYSTEM_STATUS_API_IP_ACL` config property to NOT reference your localhost at all. For instance: 
```
10.0.0.0/8,172.16.0.0/12
```
7. Start dotCMS and send the GET Request once more. You must get the `FORBIDDEN` status now.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_21e04e1_SNAPSHOT`

dotCMS is now returning the expected HTTP Status based on the expected scenario. Using Postman with a `GET {{serverURL}}/api/v1/probes` request:

-  `SERVICE_UNAVAILABLE` (503): You can check this by shutting down the Elasticsearch service.
- `FORBIDDEN` (403): You can check this by setting this property in the `docker-sompose.yml`file: `"DOT_SYSTEM_STATUS_API_IP_ACL"`.  Just make sure your localhost is not allowed.
