### ISSUE TITLE
[UI] Add end experiment as part of the options in the listing.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25627]
### Parent Issue
#24343

### User Story
Stop experiment should be part of the options in the listing experiments page. 

### Acceptance Criteria
The user should be able to stop an experiment in the listing page. 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by oidacra** [comment]
IQA Passed:
![Screenshot 2023-08-09 at 12 44 48 PM](https://github.com/dotCMS/core/assets/1909643/1aaac09f-ad25-440d-90f1-ff39076bcc5d)

**Comment by bryanboza** [comment]
Fixed, now we are able to see that option from the available options listing
