### ISSUE TITLE
Non-existing URL page is showing up in 'Pages' portlet

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25628]
### Parent Issue

[Pages]

### Problem Statement

Within the 'Pages' portlet, a page with a non-existing URL is being displayed.

### Steps to Reproduce

1. Go to https://localhost:8443/dotAdmin/#/pages
2. Observe that a page with a non-existing URL is displayed

### Acceptance Criteria

The 'Pages' portlet should display only valid pages with working URLs for navigation.

### dotCMS Version

23.07

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

**/store/products/robert-august-what-i-ride-tuflite-pc-surfboard**

![Screenshot 2023-07-26 at 9 45 54 AM](https://github.com/dotCMS/core/assets/129882031/16e8bfb3-9802-4ec3-b72d-8b7adedb39d2)

**Comment by bryanboza** [comment]
Related to #https://github.com/dotCMS/core/issues/25624 please test this one too as part of the fix

**Comment by fmontes** [comment]
Close in favor: https://github.com/dotCMS/core/issues/25624
