### ISSUE TITLE
dotCMS CLI: Unable to recover token from key-chain for service

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#25634]
### Problem Statement

When you run CLI test workflow (GHA) you get the following exception:

`com.starxg.keytar.KeytarException: The name org.freedesktop.secrets was not provided by any .service files`

This problem only occurs when we run the CLI tests in the cloud via the GitHub actions workflow. It is important to note that these tests run in a Linux environment (Ubuntu), which is not exactly the same as the one used locally for development (which is MacOS).

The classes that present this problem are the following

`com.dotcms.api.client.HybridServiceManagerTest` `com.dotcms.cli.command.StatusCommandTest`

Here is the link to the workflow used to start the tests:
[](https://github.com/dotCMS/core/actions/workflows/cli-cicd-tests.yml
)

### Steps to Reproduce

1. Git checkout [22706-configure-gha-and-testcontainers-for-cli-test]( https://github.com/dotCMS/core/tree/22706-configure-gha-and-testcontainers-for-cli-test ) branch

2. Make a simple change, commit and push.

3. Watch the workflow log.

### Acceptance Criteria

1. The workflow must finish successfuly

### dotCMS Version

22706-configure-gha-and-testcontainers-for-cli-test

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
No Internal QA is needed as it is passing on a Ubuntu install
