### ISSUE TITLE
Favorite Pages: Missing dividing lines on the table of the 'Create Page' takeover

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25635]
### Parent Issue

[Pages]

### Problem Statement

The table in the 'Create Page' takeover is missing dividing lines. This issue affects the aesthetic presentation of the table.

### Steps to Reproduce

1. Go to https://localhost:8443/dotAdmin/#/pages
2. Observe that the table is missing dividing lines

### Acceptance Criteria

The table in the 'Create Page' takeover should have clear dividing lines to improve readability and maintain a consistent visual presentation.

### dotCMS Version

23.07

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### Quality Assurance Notes & Workarounds

![Screenshot 2023-07-26 at 10 42 35 AM](https://github.com/dotCMS/core/assets/129882031/589e0de5-386b-483f-8f07-752b55fff09f)

**Comment by danielmdob** [comment]
Passed internal QA, screenshot:


![Image](https://github.com/dotCMS/core/assets/29465918/cb020728-3f93-4567-a836-f4c7cfb52e24)

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_d0a4af2_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
