### ISSUE TITLE
[UI] Change Experiments default/standard chart to display Conversion Rate instead of Conversions/Day

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25638]

**Comment by john-thomas-dotcms** [comment]
## The Problem:
Currently, when showing the Experiment results, the default/simple chart show the number of conversions/day for each variant.

This works reasonably well when the traffic is split evenly among all the variants.  But when the split is uneven, the information shown by the chart isn't meaningful, because the chart gives no context.

Consider an experiment with the original and one variant, variant A; if the original gets 80% of the traffic and variant A only gets 20%.  Even if they both perform equally well (same conversion rate), the chart will show the original as having 4x as many conversions as variant A.

For example, assume on day 1 the original is sent 80 sessions, 40 of which convert, and variant A is sent 20 sessions, 10 of which convert.  On day 2, the original is sent 80 sessions, 35 of which convert, and variant A is sent 20 sessions, 15 of which convert.  The chart will show variant A with the most conversions on both days, even though variant A performed just as well as the original on day 1, and performed significantly better on day 2.

Note: The table below the chart shows the conversion rate, so it doesn't have this problem.  The problem is only with the unit we've chosen to show on the chart Y axis.

## The Solution
We need to change the chart so that for each variant, instead of showing conversions/day, it shows conversion rate/day.  (Note that this means the left axis show a percentage, not a whole number).

This would change the example above, so the original would show as 50% on day 1 and 43.75% on day 2, and variant A would show as 50% on day 1 and 75% on day 2.  This would make it clear in the chart that variant A did just as well as the original on day 1, and did better on day 2.

**Comment by oidacra** [comment]
Blocked by #25779

**Comment by dsilvam** [comment]
Passed Internal QA: Default graph showing Conversion Rate pero dat instead of # of Conversions per day.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

![Image](https://github.com/dotCMS/core/assets/2641437/b7a0d9f4-e119-4f94-ac4c-6b8433cb98f2)
