### ISSUE TITLE
We require a SAML app property to map old SAML configuration IDs to site IDs

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25636]
### User Story

As a user I want to be able to map configuration IDs used in legacy SAML implementations to site IDs so I do not have to update the login URL on the IDP.

### Acceptance Criteria

1. The `/api/v1/dotsaml/login/{configuration_id}` path should either route to `/api/v1/dotsaml/login/{site_id}` or be a valid route itself.

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Ticket: https://dotcms.zendesk.com/agent/tickets/112111

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS
