### ISSUE TITLE
[UI] Replace the Empty List of Experiments with `DotEmptyContainerComponent`

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25637]
Replace the Empty Component
<img width="955" alt="Screenshot 2023-07-26 at 2 11 31 PM" src="https://github.com/dotCMS/core/assets/1909643/29a816e5-ef7f-41b5-9f51-783d26af057a">

With `DotEmptyContainerComponent`
<img width="1512" alt="Screenshot 2023-07-26 at 2 19 21 PM" src="https://github.com/dotCMS/core/assets/1909643/9317192a-8f63-415a-9a41-4d3ad0dd33a0">

Same content.

**Comment by hmoreras** [comment]
IAQ blocked by: #25504
