### ISSUE TITLE
Pagination not working on related endpoint

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25666]
### Problem Statement

When using offset and limit with this endpoint `/api/v1/content/related` no results are returned.

### Steps to Reproduce

1. Create a Content Type with a Title and a Relationship field (named Devices to the Device CT).
2. Create a content of the created CT, and relate all 3 devices.
3. Make the following Curl call:
```
curl --location 'http://localhost:8080/api/v1/content/related' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGkyY2MwODZlYS1jMWUyLTQ5N2ItODY3Yy1lMDNhOGQyNGVkM2MiLCJ4bW9kIjoxNjc5OTQyMTQ5MDAwLCJuYmYiOjE2Nzk5NDIxNDksImlzcyI6IjE5ZDY3YmJhMmMiLCJsYWJlbCI6InBwIiwiZXhwIjoxNzc0NTkxMjAwLCJpYXQiOjE2Nzk5NDIxNDksImp0aSI6IjUyZjhkOWMyLWZkZjItNDYzMy1hYjlmLTY3OTg5MWExMzhlNCJ9.oyGBU6MxIHHDAmYmu4bbA6Y1baTUpF6vOCPro7E9WJA' \
--data '{
   "identifier":"6e2529b080eecaf689de9aa19fa1361d",
   "fieldVariable":"devices"
}'
```
All 3 devices should be returned.
4- Now let's add limit and offset to Curl call:
```
curl --location 'http://localhost:8080/api/v1/content/related' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGkyY2MwODZlYS1jMWUyLTQ5N2ItODY3Yy1lMDNhOGQyNGVkM2MiLCJ4bW9kIjoxNjc5OTQyMTQ5MDAwLCJuYmYiOjE2Nzk5NDIxNDksImlzcyI6IjE5ZDY3YmJhMmMiLCJsYWJlbCI6InBwIiwiZXhwIjoxNzc0NTkxMjAwLCJpYXQiOjE2Nzk5NDIxNDksImp0aSI6IjUyZjhkOWMyLWZkZjItNDYzMy1hYjlmLTY3OTg5MWExMzhlNCJ9.oyGBU6MxIHHDAmYmu4bbA6Y1baTUpF6vOCPro7E9WJA' \
--data '{
   "identifier":"6e2529b080eecaf689de9aa19fa1361d",
   "fieldVariable":"devices",
   "limit":1,
   "offset": 2
}'
```
Nothing is returned, but the second device should be returned.

### Acceptance Criteria

when using offset and limit should return results if they're available.

### dotCMS Version

22.03 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112490

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_pre-release_23.08_8d30d6e** // Docker // macOS 13.0 // FF v113.0
