### ISSUE TITLE
Add support for h4, h5, h6 headlines in Block Editor

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#25660]
### User Story

We have different support requests to offer h4,h5, and h6 headlines in Block Editor

### Acceptance Criteria

Block Editor should have h4, h5, h6 blocks so customers can add those headlines.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Ticket: https://dotcms.zendesk.com/agent/tickets/112593

Slack: https://dotcms.slack.com/archives/C028Z3R2D/p1673979176428059

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_74e2d1a_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_74e2d1a_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
