### ISSUE TITLE
Allow editing of contentlet on detail page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25678]
### User Story
As a dotCMS user, I want to be able to edit either the contentlet that generates the urlmap page or the detail page itself, so I can make changes to the page quickly and efficiently.

### Acceptance Criteria
- The design will have a dropdown in the edit button with two options: 
    - Edit the contentlet
    - Edit the detail page
- The user must be able to edit the detail page without having to edit the contentlet
- The user must be able to edit the contentlet without having to edit the detail page

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
[Figma](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Portlets-%2F-Edit-Page?type=design&node-id=1748%3A6895&mode=design&t=c7ANGZCO2J2XReUK-1)

### Assumptions & Initiation Needs
1. Check if the page is urlMap (or generated), because in the response of the Page API there is a `urlContentMap` property
2. If that property is set is where you will add the options to the "Edit" tab
3. To open the edit contentlet in the dialog, maybe we can use routing because we already have that in others sections like pages or content search.
4. This should be behind a feature flag and also needs to accommodate for SEO new tooling.
5. So you can bring out the new buttons from SEO toolbar into this.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by fmontes** [comment]
Waiting for UX

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/assets/751424/97c29b7a-107a-443b-ac6a-e483792907d2

**Comment by fmontes** [comment]
Known issue: https://github.com/dotCMS/core/issues/26314

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
