### ISSUE TITLE
Create an $ai Velocity viewtool

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25672]
_This description is copied (with minor formatting changes) from the signed SOW._

## Purpose

Allow executing the AI plugin API method(s) via a Velocity viewtool

## Requirements

* Create a java class which can be called as a Velocity viewtool
    * This java class will be integrated into the dotCMS plugin (https://github.com/dotCMS/core/issues/25668)
* Configure the toolbox.xml file to enable the class as a viewtool (see below)
* Implement the following methods in the class:
    * `build( string prompt, string context )`
        * Creates a prompt string, given a basic prompt, and a JSON-formatted list of parameters as context
        * To create the full prompt, it adds all the parameters in the JSON to the main prompt, as context for the prompt
        * Return: string
    * `addContext( string prompt, string param, string value )`
        * Given a prompt, modifies it to add the supplied parameter and value as context to the prompt
        * Return: string
    * `submit( string prompt )`
        * Submits a supplied string as a prompt to the ChatGPT API, through the plugin (https://github.com/dotCMS/core/issues/25668)
        * The only additional context to be included in the prompt string is the Role Prompt from the App configuration (https://github.com/dotCMS/core/issues/25593)
            * To include any other context, the user must either use the build method (above), or manually add it to the prompt string
        * Return: JSON string, containing:
            * The HTTP status
            * The response text (either the ChatGPT response string if successful, or an error message if unsuccessful)
            * (If there are other values that might be needed in the response JSON, please suggest them)
    * `submitRaw( string prompt)`
        * Same as `submit`, but does not add in any context (e.g. the Role Prompt) from the App configuration
        * Return: JSON string (same as submit, above)

## Tech

* Java
* Configuration file
    * This just requires adding five lines to the Toolbox.xml file, as described here: https://www.dotcms.com/docs/latest/toolbox-xml
    * The following plugin-seed provides a framework for adding a new Velocity Viewtool to dotCMS via plugin: https://github.com/dotCMS/plugin-seeds/tree/master/com.dotcms.viewtool

## Testing

* Manual display and verification of a test page
    * dotCMS will provide 1-3 dotCMS pages which call the Velocity viewtool with different test data
    * dotCMS will perform manual testing on the test environment before sign-off

## Deliverables

* Java class included in the plugin (https://github.com/dotCMS/core/issues/25668)
* toolbox.xml file configuration (5 lines)

**Comment by wezell** [comment]
### Semantic Search
#### Viewtool
`$ai.search`

__Semantic Search `default` content index__
`$ai.search.query(String prompt)`

__Semantic Search Specific Content Index__
`$ai.search.query(String prompt, String index)`

__Pull Semantically Related Content__
`$ai.search.related(Contentlet content)`


### Chat/Completions

__Viewtool__
`$ai.completions`

__Summarize based on content (specific index)__
`$ai.completions.summarize(String prompt/query, String content Index)`

__Summarize based on content  (`default` index)__
`$ai.completions.summarize(String prompt)`

__Raw Prompt__
`$ai.completions.prompt(Map prompt)`

**Comment by fmontes** [comment]
Done
