### ISSUE TITLE
[UI] Add Multi-Lang and Personas on experiments (variants)

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25688]
### Parent Issue
#24343

### User Story
Add multi language and personas as part of the experiment. 

### Acceptance Criteria
User should be able to change between language and personas in experiments ( variants ) 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by oidacra** [comment]
IQA Passed:
Dowpdown Personas/Language on Variant view/edit
Personas Dropdown
![Screenshot 2023-08-09 at 11 28 46 AM](https://github.com/dotCMS/core/assets/1909643/71ed90b5-2034-4149-9165-45c59ea21376)


Language Dropdown
![Screenshot 2023-08-09 at 11 28 37 AM](https://github.com/dotCMS/core/assets/1909643/481ea229-d9b6-469c-bf7d-c384b0ff4412)

**Comment by bryanboza** [comment]
This is affected by the new SEO tool bar, if you enable that feature this is not working as expected. We are missing the drop-down and the content is not displaying correctly 


https://github.com/dotCMS/core/assets/2641437/55e4091a-2685-42d5-a7fe-bbaa111a9fa7

We need some sync work here.

**Comment by dsilvam** [comment]
Passed IQA: When activating SEO_IMPROVEMENTS we are still showing the confirmation dialog when clicking on the Edit tab.

**Comment by bryanboza** [comment]
We need some work here: 

- When you create a personalized version of a variant for some specific persona, and you add some pieces of content to it, you are unable to see it outside the variant.  

Based on that, in that case you are creating a personalized version of the VARIANT not to the PAGE. And if you go out the experiments and try to edit the page from edit mode, we are showing that you have a personalized version of the page, and this is not real b/c if you open this version you are unable to see the content of this version b/c those contents are just for the variant. 

Here a video to try to explain it better: 


https://github.com/dotCMS/core/assets/2641437/b3e1a8cb-e4da-4b30-bc33-e3aca8bbd645

**Comment by dsilvam** [comment]
Passed Internal QA: Personalization only visible in the Variant of only applied there.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now we are able to have personalized versions for variants and also for pages individually.
