### ISSUE TITLE
Sorts on site browser are always using the Mod Date

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25680]
### Parent Issue

https://github.com/dotCMS/core/issues/25136

### Problem Statement

The different sorts at the site browser like name, mod user, etc, are always using the mod date as the sort criteria, causing not to filter the data as expected.

### Steps to Reproduce

1- Start dotcms with a full starter
2- Navigate to the Site Browser Portlet.
3- Go to `application/themes/landing-page`
4- Try to sort by name (ascending or descending).

### Acceptance Criteria

2 things we should check:
1. The user should be able to sort by name, mod date, mod user, etc. 
2. By default, this feature should sort content based on mod date regardless of the object type.

### dotCMS Version

demo (23.07)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
We are unable to sort by mod_User 
 
After test in the last master image, now we are able to sort by all the mentioned parameters above, but if you try to sort by mod_user this is not working.

**Comment by erickgonzalez** [comment]
I'm able to sort by Mod User, I'm using docker image `master_8d30d6e_SNAPSHOT` @bryanboza can you please double-check this?

https://github.com/dotCMS/core/assets/5278970/29530b0d-2950-4eb3-b74c-9ba244637414

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
