### ISSUE TITLE
Keep Experiment End date on pushing

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25697]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When pushing a Running Experiment that has Start/End Date on the receiver we need to keep the same Start/End Date

### Steps to Reproduce

- Create an Experiment on the sender
- Set S End Date 15 days later.
- Set Goal and Add Variant.
-Start the Experiment
- Send The Experiment.
- You are going to see that the End Date is not the same that come from the sender.

### Acceptance Criteria

The Start/End Date must be the same from the sender

### dotCMS Version

kastest in master

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dsilvam** [comment]
Passed Internal QA: keeping the end date on the different possible states of the Experiment after being pushed.

**Comment by bryanboza** [comment]
Fixed, now we are keeping the end date after push the experiment


![Image](https://github.com/dotCMS/core/assets/2641437/202f9180-582b-4029-88b1-649447e92b93)
