### ISSUE TITLE
Call the Ended API Method on the Receiver when it is needed

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25699]
### Parent Issue

https://github.com/dotCMS/core/issues/25689

### Problem Statement

We have different cases when we need STOP an Experiment on the Receiver when publish it:

Of course in all these cases the Experiment is RUNNING on the receiver

- The Experiment is on DRAF on the Sender and Running on the Receiver, it could happend if you send the Experiment on DRAFt the first time and then Start ir on the Reciever, Also later it can be send on RUNNING the first time and  canceled on the sender.
- The Experiment was sent as RUNNING the first time and then it is STOPPED on the sender, in this case the Experiment finish as ENDED on the receiver but the Stop method is not call.

### Steps to Reproduce

- Create a Page and an Experiment.
- Create a Variant and set a Goal
- Start the Experiment
- Send the Experiment to the Receiver
- Stop the Experiment on the sender and send it again.
- Go to the FE on the receiver and check on the local storage that we still have a Running Experiment

### Acceptance Criteria

The Local Storage must be clean

### dotCMS Version

lates

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass Internal QA: Work as Expected

**Comment by bryanboza** [comment]
Fixed, tested as part of the card #25696
