### ISSUE TITLE
Stop Any Running Experiment on the Receiver when there is a Running Experiment already

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25696]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

Just one Running for Page is allowed so if we sent a Running Experiment to any Environment and there alreasy exists a RUNNING Experiment for the same page then we need to force it to stop and save and Running the new one.

Right now the PP process is failing

### Steps to Reproduce

- Start a Sender and a Receiver, and config all that you need to PP
- Create a Page and Experiment, Create a Variant and a Goal
- Start the Experiment, and send it to the receiver.
- Stop the Experiment on the Sender, Create a new Experiment and Start it.
- Send the new Experiment to the REceiver

### Acceptance Criteria

The already running Experiment on the receiver must be stopped, The PP must no failed

### dotCMS Version

lastes in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass Internal QA: Work as Expected

**Comment by bryanboza** [comment]
Fixed, now we are able to send a experiment running although you already have another experiment running, we basically are forcing to overriding the existing config every time you send an experiment.
