### ISSUE TITLE
[UI] Verify Back icon and Science icon beside Name of experiment on Header inside View/Edit Variant

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25692]
### Parent Issue
#24343

### Acceptance Criteria
- View the Icon of Back in the Header
- View the icon of `science` beside the Name of the Experiment at the right
- Fix the contrast of `Copy Url`
- View if we can replace the icons from dot-icon to use PrimeNg icons.

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="1481" alt="Screenshot 2023-08-02 at 2 45 23 PM" src="https://github.com/dotCMS/core/assets/1909643/549fddf5-66f8-4612-8da4-0a47fca06b68">

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/25705

**Comment by dsilvam** [comment]
Passed Internal QA: All items described working as expected.

**Comment by bryanboza** [comment]
According with the new design that we are implementing in all the system, this is inconsistent with the buttons design as you can see in this card https://github.com/dotCMS/core/issues/25356 .

Also the "<" back button looks as part of the text, I think we need some styling help here to be consistent with all the new system appearance

**Comment by bryanboza** [comment]
We can close this card, we continue this case on the card #25772
