### ISSUE TITLE
Access Experiments results gathered on Prod from the Authoring server after pushing an Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25690]
### Parent Issue

https://github.com/dotCMS/core/issues/25134

### User Story

As an Experiments User, I need to be able to access from the sender/authoring server the data gathered at the receiver/production once an Experiment is pushed. 

### Acceptance Criteria

The data/results gathered in the production/receiver server is accessible from the sender. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass Internal QA: Now If you send: A Running Experiment the the data is share between Sender and Receiver.
-

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
