### ISSUE TITLE
[UI] Define the the minimum of data required to show Bayesian Chart

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25693]
### Parent Issue

#24343

### User Story

As a user, I want to see the chart with enough reliable data gathered to show it.

### Acceptance Criteria
- Define the minimum data required to show a reliable chart.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Based on our discussions, there are 2 parts to this:
1. Don't show data if there are no sessions that failed to convert.
    - This will cause an error in the calculations.
2. Don't show data until a minimum number of sessions have been routed through the Experiment.

For #1, for MVP, this is a simple if/then.
* I'm concerned that we may run into cases where there aren't any conversion failures for a very long time.
    * But I think this would be an outside case.
* A more robust way to handle this would be that if there are no conversion failures within some number of sessions, we would insert a "fake" conversion failure just to make the calculations work.
    * But this can wait until after MVP - and until we've seen how often (if at all) this corner case comes up in real experiments.

For #2, we should create a config variable that specifies the minimum number of sessions required before the graph is shown.
* From a statistical standpoint, it would be best to make the default value 30.
    * But that would make it challenging to do demos.
* So, let's start the value at 10 for now, and we can change it later if needed.
* We'll use the same minimum value (and the same config property) for both the simple and Bayesian charts.

**Comment by freddyucv** [comment]
Pass Internal QA:

Now it not show any data until we have 10 session at least.
and not show the Bayesian char until it have at least one session fail on each Variant

**Comment by bryanboza** [comment]
Fixed, tested on master and now we need at least 10 sessions to start seen the data results graphics.
