### ISSUE TITLE
 Unable to access pages from any portlet in the application

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25701]
### Parent Issue

Pages

### Problem Statement

There is an issue preventing access to pages from any portlet within the application. This severely impacts navigation and overall usability of the application.

### Steps to Reproduce

1. Go to any portlet in the application
2. Attempt to access a page
3. Notice that pages cannot be accessed from any portlet

### Acceptance Criteria

Users should be able to access pages from any portlet within the application.

### dotCMS Version

23.07

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

### Quality Assurance Notes & Workarounds

https://github.com/dotCMS/core/assets/129882031/9ce63555-5aa1-4319-bdb5-94b3d7fca3bd

**Comment by erickgonzalez** [comment]
Not Reproducible.
