### ISSUE TITLE
[UI] Esc Key should close the confirmation dialogs using experiments

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25715]
### Problem Statement

When a confirmation dialog is open in the experiments section of dotCMS, pressing the Esc key does not close the dialog. This behavior is inconsistent with standard UX expectations and can be confusing for users.

![image](https://github.com/dotCMS/core/assets/2641437/74efe48e-9864-4da8-9e22-c516e1909816)

### Steps to Reproduce

- Open an experiment in dotCMS.
- Perform an action that triggers a confirmation dialog (e.g., deleting a variant).
- With the confirmation dialog open, press the Esc key.
- Observe that the confirmation dialog does not close.

### Acceptance Criteria

- Pressing the Esc key should close the confirmation dialog in the experiments section of dotCMS.
- Users should not need to use alternate methods (e.g., clicking on the "X" button) to close the dialog when the Esc key is pressed.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
@bryanboza , No fix needed. 

This issue, is related to the `ConfirmPop` of primeng, https://primeng.org/confirmpopup 

The behavior of this component is different that the "Confirm Dialog", so is his behavior, meaning that the closing on `scape` or any  key is not part of the functionality since is treated more like an "inline" notification.

**Comment by bryanboza** [comment]
You can see this works on the new template builder, we are able to close the modal with the ESC key this notification. We need to be consisten and allow the same on experiments

**Comment by hmoreras** [comment]
reference on how is implemented, `dotcms-remove-confirm-dialog`, need to that reusable

**Comment by hmoreras** [comment]
Internal QA: user can now close inline dialogs with escape.

**Comment by bryanboza** [comment]
Fixed, now we are able to close this dialog just pressing Esc.
