### ISSUE TITLE
Not catch Event when the User is not assign to an Experiment

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25710]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When you have an Experiment with less of 100% of traffic proportions and I user is not assign to the Experiment, then we must not catch any Event and wait until the lookBackWindows expire before try to assign the user again

### Steps to Reproduce

- Create a Page
- Create an Experiment
- Set the traffic proportion to 1%
- Add a Variant, set a Goal and start the Experiment.
- Log out and close the tab.
- Navigate to any page , check that you Experiment is NONE (on the localStorage)
- Close the tab and open a new one.
- Open the Network tab and refresh the page, you are going to see a hit to '/api/v1/experiments/isUserIncluded'
it should wait 30 minutes before hit the isUserIncluded Endpoint again
- Go to localhost:4001 and filter the Events by Experiment=NONE, you are going to see that Event for this user was caught

### Acceptance Criteria

When you have Running Experiment with a traffic load less than 100% and you were not assign inside any Experiment, then:

- Must not catch any Event for this User.
- Must wait until the lookBackWindows is expired before try to assign the User again

### dotCMS Version

lastes in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
When a user is not routed to the experiment, we still want to record the page view.  But we need to send that page view without a variant ID, so we can tell that user was not routed to the experiment.

**Comment by john-thomas-dotcms** [comment]
Note that we may need to update the field definitions in clickhouse to allow us to store null values for the experiment ID and variant ID.

**Comment by john-thomas-dotcms** [comment]
Closing this as not needed.  We actually want to store all events, even if they're not being routed to the experiment.
