### ISSUE TITLE
Specify the insert order on SQL query at `Task230119MigrateContentToProperPersonaTagAndRemoveDupTags`

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25720]
### Problem Statement

A client is facing an issue when try to update from `23.01.3` to `23.01.4`. 
Here are the logs that correspond to it:
```
12:28:08.677  INFO  runonce.Task230119MigrateContentToProperPersonaTagAndRemoveDupTags - ==> Executing upgrade script
12:28:08.677  INFO  runonce.Task230119MigrateContentToProperPersonaTagAndRemoveDupTags - ======================================================================
12:28:08.677  INFO  db.DotConnect - Executing INSERT INTO tag_inode
SELECT tag.tag_id, aux.inode, aux.field_var_name, aux.mod_date
FROM (SELECT tag_inode.*, tag.tagname
      FROM tag_inode
               JOIN tag ON tag_inode.tag_id = tag.tag_id
      WHERE tagname LIKE '%:persona') aux,
     tag
WHERE tag.tagname = REPLACE(aux.tagname, ':persona', '') AND NOT EXISTS (SELECT 1 FROM tag_inode WHERE tag.tag_id = tag_id AND aux.inode = inode)
com.dotmarketing.exception.DotDataException: ERROR: column "mod_date" is of type timestamp with time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 53
        at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:793)
        at com.dotmarketing.startup.StartupTasksExecutor.executeBackportedTasks(StartupTasksExecutor.java:256)
      
Caused by: org.postgresql.util.PSQLException: ERROR: column "mod_date" is of type timestamp with time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 53
```

The reason for this problem is that the columns in the `tag_inode` table are ordered differently for the current client. The issue is only affecting this particular client at the moment. To prevent this problem from occurring with other clients and to resolve it for affected clients, the insert query at [Task230119MigrateContentToProperPersonaTagAndRemoveDupTags](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task230119MigrateContentToProperPersonaTagAndRemoveDupTags.java) needs to be adjusted to specify the order of the fields that are being inserted.

### Steps to Reproduce

1. Restore the database of the client on your local machine.
2. Try to run dotcms on `23.01.4` using the database of the client.
3. You should be able to see the error on the logs.

### Acceptance Criteria

The insert query needs to specify the order of the fields that are being inserted.

### dotCMS Version

23.01.4

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Another way to test it:

Run the following queries against the DB:

```
-- removes all the entries
truncate table tag_inode;

-- delete table
drop table tag_inode;

-- create the table again but change the sort of the columns
create table tag_inode (
   tag_id varchar(100) not null,
   mod_date timestamptz,
   inode varchar(100) not null,
   field_var_name varchar(255),
   primary key (tag_id, inode)
);
```

After that run the following curl:

```
curl --location 'http://localhost:8082/api/v1/upgradetask' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data '{
    "upgradeTaskClass":"com.dotmarketing.startup.runonce.Task230119MigrateContentToProperPersonaTagAndRemoveDupTags"
}
'
```

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master** // PostgresSQL 15 // macOS 13.0 // FF v113.0
