### ISSUE TITLE
Order of comments in Task details modal.

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#25729]
### Problem Statement

When a Task (details modal), The list of comments is ordered the old one first; Ideally is the newest first.,

### Steps to Reproduce

1.- Go to Dashboard -> Task.
2.- Open any task details (modal).
3.- The list of comments is ordered from oldest to newest.

![Screenshot 2023-08-08 at 11 45 50 AM](https://github.com/dotCMS/core/assets/12899960/bf4329f0-b059-476a-9455-2d79a7526779)

### Acceptance Criteria

The list of comments should be the newest first.

### dotCMS Version

21.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112830

**Comment by Neehakethi** [comment]
https://dotcms.zendesk.com/agent/tickets/114161

**Comment by erickgonzalez** [comment]
Needs Work: 

New comments are set on top, which is good, but previous comments are still sorted from oldest to newest.
![Screenshot 2024-01-03 at 3 31 36 PM](https://github.com/dotCMS/core/assets/5278970/e6c32c64-f9eb-439c-902c-76b7bb6c8d28)

STR:
1- Create a new content
2- Save and Publish
3- Unpublish the content
4- Go to Tasks Portlet
5- Open the created content

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8aae521**, Docker, macOS 13.0, FF v121.0.1
