### ISSUE TITLE
[UI] Content palette should show when editing a variant

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25722]
### Parent Issue
#24343

### User Story

1. Open an experiment with at least one variant.
2.  Click to edit the variant.
3. When the variant opens in Edit mode, look at the screen. **Result**: There is no content palette shown
4. Click the Preview tab.
5. Click the Edit tab, and look at the screen. **Result**: This time, the content palette is shown

**Second scenario**: 
1. Open an experiment with at least one variant.
2.  Click to edit the variant.
3. refresh de page (f5)
4. the content palette don't show

### Acceptance Criteria

Content palette should be visible in both scenarios. 

The content palette should be shown in step 3, but it's not

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by oidacra** [comment]
If you do a refresh page (F5) disappear.

**Comment by dsilvam** [comment]
Passed IQA: Content palette showing even after refreshing the page.

**Comment by bryanboza** [comment]
Fixed, now we are showing the content palette editing variants. Tested on master // Docker // FF
