### ISSUE TITLE
Updates to Getting Started Page

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25739]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Infinite scroll; load top 50.

There is no sorting on this page. It should always just show the most new items on top and the past down on the bottom of the list.

There is no filtering on this page. At least not now. Just trying to keep it all dirt simple for launch.

When users get to the bottom of the list they see the "Other Resources" section of links.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=301-8743&mode=design&t=zcsn1PQTj67Ckt7K-0

**Comment by damen-dotcms** [comment]
Re-working this slightly since we first talked about it.

Instead of building a "View All" page for announcements, we'll just send the users back to the "Getting Started" landing page they see when they first sign in. 

We'll need to make a few updates to the "Getting Started" page to get it ready to hold the Announcements.

Designs coming soon, but it should be less work than building a View All page from scratch.

**Comment by dcolina** [comment]
Internal QA: Needs work.

There is a unexpected character '='.

![IQA](https://github.com/dotCMS/core/assets/29883881/c4378fcf-1d20-4f12-a255-9249990c1813)

**Comment by dcolina** [comment]
Internal QA: Passed.

As you can see in the following image.

![Image](https://github.com/dotCMS/core/assets/29883881/18cc7f59-112b-48f8-a4fb-9457563b804f)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now we are showing the new page without problems.
