### ISSUE TITLE
Pull announcements from the feeding endpoint

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25735]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Task

This card is meant to integrate FE logic with the endpoint implemented on #25734

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Announcements should be pulled from the endpoint as a JSON

**Comment by nollymar** [comment]
Dupe of #25738

**Comment by dcolina** [comment]
Internal QA: Passed.

**Comment by bryanboza** [comment]
Fixes, tested on master and it is working as expected some enhancements reported here: https://github.com/dotCMS/core/issues/25736#issuecomment-1915291003

**Comment by bryanboza** [comment]
We need some work here: 

We are unable to pull announcements in multiple languages, if you change the default lang we are unable to use the announcements in the selected language. 

- We need to pull the announcement in the session language, and if this does not exist pull the default language.

**Comment by manuelrojas** [comment]
**Internal QA Approved** 

![image](https://github.com/dotCMS/core/assets/3438705/87a66bbf-ef55-403c-bab4-2d7dda6cf1a2)
