### ISSUE TITLE
Supporting push remove Experiments

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25730]
### Problem Statement

Currently, when trying to push to remove a running experiment in dotCMS, the error message displayed is not clear and does not provide enough information to understand the issue.
![image](https://github.com/dotCMS/core/assets/2641437/0ae01368-c2ea-4918-89a2-379743b7c535)

### Steps to Reproduce

- Log in to dotCMS.
- Create a new experiment and run it 
- Now push to the receiver side 
- Attempt to push the remove the same experiment
- Observe the error message displayed.

### Acceptance Criteria

- When attempting to push remove a running experiment in dotCMS, a clear error message is displayed, providing relevant information about why the action was not successful.
- The error message includes details such as the experiment still running, any dependencies preventing the removal, or any other relevant information.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Really this change is more than just fix a message, we need to support these two different cases:

- If the Experiment is in Draft, Scheduled, Ended, or Archived state on the receiver then just Remove the Experiment
- If the Experiment Running on the receiver then: Stop the Experiment and Remove the Experiment

Also

Removing an Experiment from the receiver won't remove the data from the analytics infrastructure
So, the data will still be viewable on the sender unless it's also explictlly removed from the sender
This is intended

**Comment by freddyucv** [comment]
We still handle better all the permission error from UI, but we created a new card for that https://github.com/dotCMS/core/issues/25747

**Comment by freddyucv** [comment]
**Pass Internal QA**: Now when we do a Push/Remove the Experiment got removed from the receiver no matter what is the Experiment's Status.

When the Experiment was removed before on the receiver and after you do a PUSH/REMOVE then we do nothing and the Push/Remove is showed as successfully

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_86dc2de_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_86dc2de_SNAPSHOT**, Docker, macOS 13.0, FF v113.0


I'm getting this error 

test 	Failed to Send 	Returned 400 status code for the endpoint test with address dotcms-qa-master.dotcms.site

**Comment by dsilvam** [comment]
Passed Internal QA: This is working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_534774e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
