### ISSUE TITLE
Setup CMS Endpoints for Announcements Feed

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25734]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Assumptions & Initiation Needs

I think all we need to include are:

- Locale (All English to Start is Fine)
- Type (If we wanted more flexibility, we could have an icon URL instead of a fixed "type" here, that may be the way to go)
- Title
- URL
- Date

Also want to make sure that if we push content with a typo, or that needs to be modified after it's consumed that the various instances of dotCMS will update as soon as we push an update -- even to older Announcements.

This should be something that we can edit form the dotCMS Marketing Website Controls. It's important that adding new announcements is fairly bulletproof and easy to do.

**Comment by manuelrojas** [comment]
Internal QA Approved: Successfully tested through integration with the front-end.

**Comment by nollymar** [comment]
**Note to QA:** By default, announcements are pulled from dotcms.com. If you want to fetch announcements from your local environment, you need to set the property ANNOUNCEMENTS_BASE_URL to localhost, this way: ANNOUNCEMENTS_BASE_URL=http://localhost:8080/

**Comment by bryanboza** [comment]
We need some FE work here: 

- When you have new notifications we are showing a "true" in the announcements icon as you can see in the follow image  

![Image](https://github.com/dotCMS/core/assets/2641437/79cd25ca-e83c-4b6e-b5e2-df286467913d)

**Comment by dcolina** [comment]
Internal QA: Passed.

**Comment by bryanboza** [comment]
Fixed, tested on master and this is working as expected for V1. We have some limitations here but after the discussion in the meeting those are known issues for now and will be fixed on future versions.
