### ISSUE TITLE
Build Logic for Showing Unread Announcements

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25738]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Any time you close the Announcements Menu, that will clear all of the "Unread" messages.

Announcements Menu should close when you click off it, or click on any Announcement, or the "View All" button, or any links from the Announcement Menu.

**Comment by nollymar** [comment]
We should include the utm info as part of the url as well. 
It should be: `?utm_source=dotcms-platform&utm_medium=announcement-menu&utm_campaign={SITE_KEY}`

for example: https://demo.dotcms.com/activities/sport-fishing?utm_source=dotcms-platform&utm_medium=announcement-menu&utm_campaign=demo.dotcms.com

**Comment by nollymar** [comment]
**Note to QA:** By default, announcements are pulled from dotcms.com. If you want to fetch announcements from your local environment, you need to set the property `ANNOUNCEMENTS_BASE_URL` to localhost, this way: `ANNOUNCEMENTS_BASE_URL=http://localhost:8080/`

**Comment by dcolina** [comment]
Internal QA: Passed.

**Comment by nollymar** [comment]
Additional PR: https://github.com/dotCMS/core/pull/27464

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
