### ISSUE TITLE
We are breaking the page when editing variant layout and pushing changes

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25732]
### Problem Statement

As a user of dotCMS, I encounter a problem where editing the layout of a variant and attempting to push the changes results in breaking the page.

![Screenshot 2023-08-08 at 2 02 57 PM](https://github.com/dotCMS/core/assets/2641437/9e8b9e5b-7c46-4022-bb60-2dee08992c7c)

### Steps to Reproduce

- Log in to dotCMS.
- Navigate to the page that has a variant.
- Push it 
- Edit the layout of the variant, making necessary changes.
- Attempt to push the changes using the provided button or relevant action.
- Observe that the page breaks and does not render correctly.

### Acceptance Criteria

- When editing the layout of a variant in dotCMS and pushing the changes, the page should not break.
- The changes made to the layout should be successfully applied to the variant without causing any rendering issues on the receiver side
- The page should render correctly after the changes have been pushed. 

### dotCMS Version

Tested on master // docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
This is not really happening like this anymore but the newly layout is not getting send to the receiver, so in the receiver the layout is not changed

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/26202

**Comment by dsilvam** [comment]
Passed Internal QA: tested on Auth/Prod setting up a new page with a new Experiment. The Variant had a custom layout and it was properly included when pushing.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_df4427b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
