### ISSUE TITLE
Build Announcements Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25737]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Should have a max height, aprox 80% as large as the height of the screen. If the content of the menu extends beyond that, then the menu should use scroll bars.

Note that if no connection or Announcements can be found, we would simply [not show them in the menu](https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=109-14305&mode=design&t=zcsn1PQTj67Ckt7K-0).

#### Static Links for Announcements Menu

**Knowledge Center**

Documentation | https://www.dotcms.com/docs/latest/table-of-contents?utm_source=dotcms&utm_medium=application&utm_campaign=announcement_menu

Blog | https://www.dotcms.com/blog/?utm_source=dotcms&utm_medium=application&utm_campaign=announcement_menu

dotCMS User Group | https://groups.google.com/g/dotcms

**Contact Us**

Customer Support | https://www.dotcms.com/services/support/?utm_source=dotcms&utm_medium=application&utm_campaign=announcement_menu

Professional Services | https://www.dotcms.com/services/professional-services/?utm_source=dotcms&utm_medium=application&utm_campaign=announcement_menu

Menu will always show most recent 5 Announcements.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=8-7460&mode=design&t=zcsn1PQTj67Ckt7K-0

**Comment by manuelrojas** [comment]
`DOT_FEATURE_FLAG_ANNOUNCEMENTS` This requires this feature flag enable in order to being able to QA.

For now it is just the UI Component.

@nollymar ☝

**Comment by nollymar** [comment]
**Internal QA:** Needs work

Being focused only in UI changes, I found a couple of issues:

- The scroll bar should be aligned to the right of the modal
- The modal is not being closed when I click the Show All link


https://github.com/dotCMS/core/assets/8741395/d96944ab-a5d8-47d2-b831-65d34ac78a7e

**Comment by jgambarios** [comment]
Everything looks good, also the scroll bar now it is properly aligned, and the modal is being closed when the “Show All” link is clicked.

**Comment by bryanboza** [comment]
Fixed, now it is working under the feature flag and working as expected.
