### ISSUE TITLE
Updates to User Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25742]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

These are just intended to be visual updates to the existing UI to bring them into alignment with the new Announcement Menu designs.

Note, we will only attempt to do this work if it won't impact getting the "core" issues from this epic included into the next LTS. 

This should not be behind the feature flag, any updates to this menu can go out for all users.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=267-58840&mode=design&t=SoL7QkLHLl5dFBUC-0

**Comment by nollymar** [comment]
Internal QA: Passed

The suggested design changes were applied as expected

**Before**


![Image](https://github.com/dotCMS/core/assets/8741395/a8a06068-f495-4496-9df5-795a1798f2b6)

**After**

![Image](https://github.com/dotCMS/core/assets/8741395/91ad36c9-5378-4937-a8c1-f4f540dfe063)
