### ISSUE TITLE
Updates to Notifications Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25741]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

These are just intended to be visual updates to the existing UI to bring them into alignment with the new Announcement Menu designs.

Note, we will only attempt to do this work if it won't impact getting the "core" issues from this epic included into the next LTS. 

This should not be behind the feature flag, any updates to this menu can go out for all users.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=301-8276&mode=design&t=SoL7QkLHLl5dFBUC-0

Prototype - https://www.figma.com/proto/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?page-id=[…]ting-point-node-id=365%3A5287&show-proto-sidebar=1&mode=design](https://www.figma.com/proto/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?page-id=1%3A3&type=design&node-id=365-5287&viewport=423%2C256%2C0.08&t=iA2tfdAhDYCq2WAP-1&scaling=scale-down&starting-point-node-id=365%3A5287&show-proto-sidebar=1&mode=design

### Quality Assurance Notes & Workarounds

A good way to spawn a notification is to go to Settings > Maintenance > Index > and hit "Reindex".

**Comment by nollymar** [comment]
**Internal QA:** Needs work

The notification is listed in the notifications menu. However, the notifications number is shown over the Announcements Menu icon  

https://github.com/dotCMS/core/assets/8741395/3a0ce18a-0bdb-49ea-b3e5-e79b0c323a30

**Comment by jgambarios** [comment]
Everything looks good now, and the notification’s number is in the right place.

![image](https://github.com/dotCMS/core/assets/923947/737e8a7b-94f7-4dc0-adf6-2aae5865096a)

**Comment by bryanboza** [comment]
Fixed, now it is working as expected. Tested on master // Docker // FF
