### ISSUE TITLE
"Select All" checkbox malfunctioning in Firefox for the Tags portlet

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25758]
### Problem Statement

In the Tags portlet, the "Select All" checkbox does not operate as intended when accessed via the Firefox browser. This impacts the user's ability to perform bulk actions on tags.

### Steps to Reproduce

1. Open the application in the Firefox browser
2. Navigate to the Tags portlet
3. Attempt to use the "Select All" checkbox to select all tags in the list
4. Observe that the checkbox does not select all tags as expected

### Acceptance Criteria

Within the Tags portlet, the "Select All" checkbox should allow users to select all tags in the list when using the Firefox browser.

### dotCMS Version

**master_pre-release_23.08_8d30d6e**

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
There is still an issue on 23.10.24.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker imaage: [`dotcms/trunk_ 8348dfb`]

### Video


https://github.com/dotCMS/core/assets/72418962/1631563b-9fcf-41b2-9117-a41067d7a80c

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_8348dfb**, Docker, macOS 14.5, FF v126.0.1

Select all functionality is working however selecting individual checkboxes stoped working 

https://github.com/dotCMS/core/assets/129882031/40b73eba-6b7d-4549-8908-a9cdaffcbd7a

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master
Both Select All and Single Select work correctly

Firefox:

https://github.com/dotCMS/core/assets/144152756/4c5f5eaa-b01e-4639-ab58-58e71e049ea9


Chrome:

https://github.com/dotCMS/core/assets/144152756/4d96b037-7ec6-4b41-b70e-b7f85b504700

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_3df97a1**, Docker, macOS 14.5, FF v126.0.1
