### ISSUE TITLE
Design System: Implement the theme for the input and textarea component in primeng

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25759]
### Parent
#25355

### User Story
As a dotCMS user, I want to be able to customize the theme of the input and textarea components in the primeng library, so I can have a more consistent look and feel across my web applications. 

### Acceptance Criteria
- Apply the provided Figma design to the input and textarea components of the primeng library. 
- Ensure that the components are styled according to the provided design.
- Update the stories for Storybook
- The classes for the label + input are already in place, make sure it works.
- Also include Dojo textfields and textarea

### Proposed Objective
Core Features 

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:

- [Figma](https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=947%3A22546&mode=design&t=BAPICcGMn5maa8lv-1) - [PrimeNG](https://primeng.org/inputtext)
- [Figma](https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=947%3A22547&mode=design&t=BAPICcGMn5maa8lv-1) - [PrimeNG](https://primeng.org/inputtextarea)

### Assumptions & Initiation Needs
- The user is familiar with Figma and primeng.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Research the current styling of the primeng input and textarea components: 1 hour
- Implement the styling according to the Figma design: 5 hours
- Test the components to ensure they are styled correctly: 2 hours

**Comment by fmontes** [comment]
![image](https://github.com/dotCMS/core/assets/751424/7d4be948-124c-4aa8-be2b-46a08f36f033)

<img width="783" alt="image" src="https://github.com/dotCMS/core/assets/751424/1229f8d8-377b-4d4d-b551-d4cf87b2ec2a">

InputGroup needs work.

**Comment by fmontes** [comment]
<img width="231" alt="image" src="https://github.com/dotCMS/core/assets/751424/244c0619-0975-4ee9-a15f-11b6edc2892a">

Disabled colors are weird... we need to look at this.

**Comment by fmontes** [comment]
<img width="278" alt="image" src="https://github.com/dotCMS/core/assets/751424/b71dbbf7-2b5a-47c9-8b33-a9bfe1478543">

The small border-radius should be 4px not 6px, there was an error in the Figma and I just fixed.

**Comment by fmontes** [comment]
<img width="493" alt="image" src="https://github.com/dotCMS/core/assets/751424/46c28363-78b6-4e61-8026-7fdebad85362">

let's fix this one as well.

**Comment by josemejias11** [comment]
Tested on **master_b295876_SNAPSHOT** / // Docker // macOS 13.5.1  // FF v117.0
