### ISSUE TITLE
Publish all the related assets modal styling

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25753]
### Problem Statement

The "Publish All the Related Assets" modal in dotCMS needs some styling help as it appears to be lacking proper design and formatting.

![Screenshot 2023-08-09 at 4 33 36 PM](https://github.com/dotCMS/core/assets/2641437/602a8949-1b58-488d-99ad-ca95883cdb7a)

### Steps to Reproduce

1- On the Site Browser Portlet
2- Create a folder
3- Inside the folder create the following:
3.1- File Asset
3.2- Page
3.3- Folder
4- Right click on the folder created in step 2.
5- Publish (All)

### Acceptance Criteria

- The "Publish All the Related Assets" modal should have a clean and professional design.
- The modal should be properly formatted with clear headings and labels for each section.

### dotCMS Version

tested on master // docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Will be considered when redesigning the Site Browser
