### ISSUE TITLE
[UI] Improve experiment listing options & all row should be clickable.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25766]
### Parent Issue
#24343

### User Story

Improve the experience with the experiment listing options. 

### Acceptance Criteria

In the experiment listing page: 

- All row should be clickable, currently only the name is. 
-  Add Cancel Scheduling as part of the options in the Schedule experiments.  
- Go to the configuration as part of the options should be available in all states; for running the option should be "**View**", for the others should be "**Edit**"

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: The three points in the description working as mentioned.

**Comment by bryanboza** [comment]
Running Experiment: 


Draft: 
![Image](https://github.com/dotCMS/core/assets/2641437/769a36b0-1b55-4f15-a4e3-3ea184cb5261)
