### ISSUE TITLE
Template Builder: Unknown error trying to use the side-bar on the new template builder  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25778]
### Problem Statement

When you are creating/editing a new template using the template builder and enable the side-bar, we are getting an unknown error. 
![Screenshot 2023-08-14 at 9 25 36 AM](https://github.com/dotCMS/core/assets/2641437/c3efebf0-f44c-4c9f-8ccc-39239032f6dd)

Here the log error: https://gist.github.com/bryanboza/7c3ed931c4d26ba784ec65d2bc86bcf5

### Steps to Reproduce

- Go to the dotCMS website and log in to the admin panel.
- Navigate to the template builder section.
- Open the new template builder.
- Attempt to use the side-bar by clicking on different options.
- Observe the unknown error that occurs.

### Acceptance Criteria

- When users click on options in the side-bar, no unknown error should occur.
- Users should be able to use the side-bar without any issues.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
@bryanboza I'm not able to reproduce it in the latest of master. Am I reproducing it the right way or we need to do something else?

https://github.com/dotCMS/core/assets/63567962/58ac8036-3fc3-4190-95c1-33ba6cedb3e5

**Comment by fmontes** [comment]
@bryanboza please take a second look here... we might fixed this in other tickets.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0

I was unable to reproduce the error.
