### ISSUE TITLE
[UI] Change Running label to "Running until <<Date>>"

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25773]
### Parent Issue
#24343

### User Story

Add the end date in the running tag
<img width="753" alt="image" src="https://github.com/dotCMS/core/assets/31667212/2f2060e0-6085-44e0-8077-0dbb76aea3dd">

### Acceptance Criteria

- Just show the date here, not the date & time; they can scroll down to the Scheduled section for details

Should be present in: 

- Edit Mode page
- Experiments Configuration Page 
- Experiments Results Page

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by oidacra** [comment]
IQA Passed:
- Edit Mode page
<img width="633" alt="Screenshot 2023-09-05 at 1 22 14 PM" src="https://github.com/dotCMS/core/assets/1909643/727af5e3-1385-4d89-a4db-756d8e2d3210">

- Experiments Configuration Page
<img width="1168" alt="Screenshot 2023-09-05 at 1 21 26 PM" src="https://github.com/dotCMS/core/assets/1909643/8c9e3d7d-db90-416d-bc33-510bc5d0b02a">

- Experiments Results Page
<img width="788" alt="Screenshot 2023-09-05 at 1 21 35 PM" src="https://github.com/dotCMS/core/assets/1909643/7af32309-f71f-40aa-b4c5-a42cd24f14a4">

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
