### ISSUE TITLE
[UI] Change how the "Back" button is displayed when you're editing a variant

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25772]
### Parent Issue
#24343

### User Story

The spacing between the back button and the variant name varies sometimes

### Acceptance Criteria

Be consistent with the back button: 

<img width="2003" alt="Screenshot 2023-09-06 at 10 12 36 AM" src="https://github.com/dotCMS/core/assets/1909643/8202b618-19f5-4a9c-8ec1-e1c65d238489">
<img width="2003" alt="Screenshot 2023-09-06 at 10 12 43 AM" src="https://github.com/dotCMS/core/assets/1909643/0a6cdc26-2a3e-47b0-bff1-c10bb4640ed7">
<img width="2006" alt="Screenshot 2023-09-06 at 10 12 56 AM" src="https://github.com/dotCMS/core/assets/1909643/1b6af678-b45f-4836-8e9e-36362702e741">
<img width="2005" alt="Screenshot 2023-09-06 at 10 13 21 AM" src="https://github.com/dotCMS/core/assets/1909643/72fc8bdc-ffaf-49d0-b56e-7b84c8f0b85b">

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by hmoreras** [comment]
Passed internal QA: we are now using the `p-button-rounded`

**Comment by bryanboza** [comment]
We need to double check that merge, I'm running the last master and we still having the same back icon 


![Image](https://github.com/dotCMS/core/assets/2641437/2be9fffc-8f51-4a40-8e37-93a91b60bc36)

**Comment by hmoreras** [comment]
fix in the SEO toolbar, here https://github.com/dotCMS/core/pull/26191

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0

![Screenshot 2023-09-26 at 1 54 28 PM](https://github.com/dotCMS/core/assets/129882031/b0392a8b-9f6f-4683-b95b-857c1aa78d85)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0
