### ISSUE TITLE
Fix Create Persona Form Fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25791]
### Problem Statement
The create persona form fields are broken. The host field needs to be 100%, and the upload field is not showing.

### Steps to Reproduce
1. Log in to dotCMS.
2. Go to edit a page
3. Click in the persona selector
4. Click + button.

### Acceptance Criteria
1. The host field needs to be 100%.
2. The upload field should show.

### External Links 

<img width="478" alt="image" src="https://github.com/dotCMS/core/assets/751424/28a0f6fb-5ec2-4dca-99df-b7916895fbd7">

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
The QA team should test to ensure the host field is 100% and the upload field is showing correctly. If the problem persists, the team should create a workaround to ensure the form fields are functioning correctly.

**Comment by zJaaal** [comment]
## Note to QA:

This ticket only refers to the UI look in the form. The file upload field button is not working and we already created an issue to look at that. https://github.com/dotCMS/core/issues/25810

**Comment by rjvelazco** [comment]
### Failed Internal QA

- Tested on `master`

**Error:** The `upload file field` is not visible.

https://github.com/dotCMS/core/assets/72418962/fb4898d2-75d8-4c13-a35b-3d7b6d4e790a

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `master`

https://github.com/dotCMS/core/assets/72418962/bc1a5a25-1477-4a67-8983-3b68acdbd392

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_839d283_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
