### ISSUE TITLE
When uploading multiple files, the files are always in English

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25797]
### Problem Statement

The multiple files option always uploads them in English, so we probably have a static value somewhere. 

### Steps to Reproduce

https://github.com/dotCMS/core/assets/127987858/1b69d466-31c0-4d64-b034-e85f1228671f

### Acceptance Criteria

Ideally, 
1- Use the language selected in the dropdown menu. 
2- If you have All, use the default language. 

The solution to the problem should be effective in both the `site browser` and the `rich text`.

### dotCMS Version

master

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Customer Ticket: https://dotcms.zendesk.com/agent/tickets/112898

**Comment by erickgonzalez** [comment]
Issues seems to be here https://github.com/dotCMS/core/blob/eeeb200ed0b870a9f80e9a68e0d4cd68be707d06/dotCMS/src/main/java/com/dotmarketing/portlets/files/action/UploadMultipleFilesAction.java#L236

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_af68a64**, Docker, macOS 13.0, FF v113.0

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_af68a64**, Docker, macOS 13.0, FF v113.0

500 error showing up when trying to upload multiple files

https://github.com/dotCMS/core/assets/129882031/5a162565-3e5f-404b-b1c7-7682964785e1

**Comment by AndreyDotcms** [comment]
The provided error was caused in the following commit #25850. It's being fixed here #26304, and now it should be working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c77be3e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
