### ISSUE TITLE
[Containers] : Fix Issue with Blank Containers After Filtering

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25809]
### Parent
#23140

### Problem Statement
In the containers when I select a content type to filter and there is no containers with that filter it shows blank instead of the "No results found" message.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/c7751c7b-63bf-48c6-b2ed-b5605fe47499

### Acceptance Criteria
When a user selects a content type to filter containers in dotCMS and there is no containers that match the filter, the page should show a "No results found" message instead of blank

### External Links
N/A

### Assumptions & Initiation Needs
- It is assumed that this bug is reproducible in the latest version of dotCMS
- No additional resources are needed to initiate this bug

### Quality Assurance Notes & Workarounds
- N/A

**Comment by zJaaal** [comment]
Solved in this PR: https://github.com/dotCMS/core/pull/25966


https://github.com/dotCMS/core/assets/63567962/985b0f50-34f7-46d2-ab95-fc265db44b9f

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_3cd5549_SNAPSHOT`

The **Containers** portlet is now displaying the `No results found` message when filtering for a Content Type that is not being referenced in a Container.

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_7713bff_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-09-18 at 9 47 37 AM](https://github.com/dotCMS/core/assets/129882031/e6a8aba2-69e2-4873-b864-bc04c1a6e91e)

Icons and texts overlapping

**Comment by fmontes** [comment]
We have a ticket for UI issues: https://github.com/dotCMS/core/issues/25808 this is being worked there,

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_7713bff_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Issues will be logged into #25808
