### ISSUE TITLE
[Containers] : Only show containers from current site

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25805]
### Parent
#23140

### Problem Statement
In the containers porlet we are listing containers from all site.

### Steps to Reproduce
1. Log in to dotCMS
2. Create 2 sites
3. Add a container to second site
4. Navigate to the New Containers Portlet (http://localhost:8080/dotAdmin/#/containers)
5. Notice that containers from all sites are listed

### Acceptance Criteria
The Containers Portlet should only list containers from the current site.

### External Links
N/A

### Assumptions & Initiation Needs
The containers endpoint should take the site id.

### Quality Assurance Notes & Workarounds
N/A

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_3cd5549_SNAPSHOT`

The **Containers** portlet is only displaying the Containers of the selected Site now.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_7713bff_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
