### ISSUE TITLE
Preview Screen Not Using Correct Width / Height when Rendering

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25815]
[![Screenshot_2023-08-17_19-20-05.png](https://mrkr.io/s/64de72e56b8fd94e18f99cd6/2)](https://mrkr.io/s/64de72e56b8fd94e18f99cd6/0)

<img width="440" alt="image" src="https://github.com/dotCMS/core/assets/114953617/0492ff0c-bc00-49e5-8c34-8af344ec6d13">

### Parent Issue

https://github.com/dotCMS/core/issues/25811

### Problem Statement

The width of the screen says it will be 414 pixels wide, however we're taking up part of that 414 pixels to render the fake phone. We need the screen inside of the fake phone to be 414 pixels wide, not 375 pixels wide.

Form what I can tell, this is an issue with all screen sizes. We're rendering them all smaller than we should be.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest25293&language_id=1&device_inode=](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest25293&language_id=1&device_inode=)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64de72e56b8fd94e18f99cd9_39ec93e98208a860?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3008 x 1692</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>3008 x 1304</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by nollymar** [comment]
**Internal QA:** Passed

I tested with all the configured devices and it works as expected.



![Image](https://github.com/dotCMS/core/assets/8741395/ce776d67-02ea-44ea-be4f-bdad6b229d45)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_658e1bc_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
