### ISSUE TITLE
Button Wobble Between Edit and Preview

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25813]
[![Screenshot_2023-08-17_19-10-05.png](https://mrkr.io/s/64de708dd3b34ff3605f6d4f/2)](https://mrkr.io/s/64de708dd3b34ff3605f6d4f/0)

https://github.com/dotCMS/core/assets/114953617/31b2fb3b-9a37-4be5-aed1-a94735536600

### Parent Issue

https://github.com/dotCMS/core/issues/25811

### Problem Statement

There's a bit of button wobble when you toggle between edit and preview, it's most noticeable if you look at the "lock" icon to the right of these two buttons.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64de708dd3b34ff3605f6d52_ac4ec670c9058f58?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3008 x 1692</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>3008 x 1554</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by nollymar** [comment]
PR: #25848

**Comment by nollymar** [comment]
**Internal QA:** Passed. The original issue was fixed. However, I noticed that the cursor is not changing to a hand when I hover over the links.  I'll file a new issue for this 



https://github.com/dotCMS/core/assets/8741395/4bca22ea-21fe-4654-a1ef-662fba2764a5

**Comment by bryanboza** [comment]
Fixed, tested in master and now I'm unable to reproduce the problem reported.
