### ISSUE TITLE
Add Persona Form File Upload Failed

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#25810]
### Problem Statement

When you try to update an image in the Add Persona Form, it doesn't work, the request is failing.

## Screenshot of how to reproduce

https://github.com/dotCMS/core/assets/63567962/1c7ba5f0-6b4b-46d8-8f07-b7bd30000602

### Acceptance Criteria

We should be able to upload an image for our new Persona

### dotCMS Version

`master latest`

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by zJaaal** [comment]
## Passed Internal QA

Now the button is working as expected

Tested in master.

https://github.com/dotCMS/core/assets/63567962/ba8349a2-9d1a-4687-adb2-de8870bf6aa8

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_839d283_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

**Comment by bryanboza** [comment]
We need some styling help here when you type long tags
![Image](https://github.com/dotCMS/core/assets/2641437/36be367c-1054-4b88-8ade-0011b50c43f7)

Also when you are typing 
![Image](https://github.com/dotCMS/core/assets/2641437/36182cba-7d55-4d64-9f0d-9363a9552a80)

Not sure if we need to add one tag by line @fmontes @Melissa-dotCMS 
![Image](https://github.com/dotCMS/core/assets/2641437/6e93c308-aca6-49ae-9b0d-d259e89e0c82)

**Comment by josemejias11** [comment]
> We need some styling help here when you type long tags ![Image](https://user-images.githubusercontent.com/2641437/267475963-36be367c-1054-4b88-8ade-0011b50c43f7.png)
> 
> Also when you are typing ![Image](https://user-images.githubusercontent.com/2641437/267476073-36182cba-7d55-4d64-9f0d-9363a9552a80.png)
> 
> Not sure if we need to add one tag by line @fmontes @Melissa-dotCMS ![Image](https://user-images.githubusercontent.com/2641437/267476371-6e93c308-aca6-49ae-9b0d-d259e89e0c82.png)


**Not seeing that one on my side**

![Screenshot 2023-09-12 at 4 05 00 PM](https://github.com/dotCMS/core/assets/129882031/80774378-331a-403d-b0ad-339714f6b94f)

**Comment by fmontes** [comment]
@bryanboza other ticket.

**Comment by bryanboza** [comment]
Moved to a new card: #26081

**Comment by bryanboza** [comment]
This cards needs to be completed in the next card.
