### ISSUE TITLE
4k Monitor View Shouldn't be in a Fake Tablet

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25814]
[![Screenshot_2023-08-17_19-17-53.png](https://mrkr.io/s/64de7261598a070f77fe8ab3/2)](https://mrkr.io/s/64de7261598a070f77fe8ab3/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

When you preview a 4k Monitor, it shouldn't have a fake phone / tablet wrapper around it. 

Do we need a design for this? Or can we just load the screen without the fake wrapper like we do with default preview?

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest25293&language_id=1&device_inode=](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest25293&language_id=1&device_inode=)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64de7261598a070f77fe8ab6_ef00d8391003d6c1?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3008 x 1692</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>3008 x 1554</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.



https://github.com/dotCMS/core/assets/29883881/067803f9-7a32-4a64-9278-aa064f71ebe4

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
