### ISSUE TITLE
Create Github Action to update issues with labels

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#25818]
### User Story
As a dev-ops, I want to create a GitHub Action to be utilized in the third job of [dotCMS core release-process workflow](https://github.com/dotCMS/core/blob/master/.github/workflows/release-process.yml). This action should accept the following inputs:
- A mandatory GitHub issue label to be removed from its usage in issues.
- An optional GitHub issue label to be added to previously affected issues.

### Acceptance Criteria
- The GitHub Action is successfully integrated into the third job of the [dotCMS core release-process workflow](https://github.com/dotCMS/core/blob/master/.github/workflows/release-process.yml).
- The action accepts a required input for a GitHub issue label to be removed.
- The action optionally accepts an input for a GitHub issue label to be added.
- When the action is triggered, it removes the specified label from associated issues.
- If provided, the action adds the optional label to previously affected issues.

### dotCMS Version
master

### Proposed Objective
Enhance the release process by automating the removal and potential addition of GitHub issue labels during the workflow.

### Proposed Priority
Priority 2 - Important

### External Links
- [GitHub dotCMS core release-process workflow](https://github.com/dotCMS/core/blob/master/.github/workflows/release-process.yml)

### Assumptions & Initiation Needs
- The GitHub Action should be written using appropriate scripting language (e.g., YAML, Bash, Python).
- Access to the dotCMS repository and GitHub Actions configuration is required.
- The action will leverage GitHub API for label manipulation.

### Quality Assurance Notes & Workarounds
- Comprehensive testing should be performed on a sample release to ensure proper label removal and addition.
- Ensure that the action is well-documented and commented for future maintenance.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/25834

**Comment by bryanboza** [comment]
Here’s the idea for improving our release labeling process:

Currently, when an issue is passed, we add the “next release” and “QA approved” labels. When it’s time to release, we manually rename “next release” to the specific version label (e.g., “Release xx.xx”) and then create a new “next release” label. This ensures that all release cards are correctly tagged with the corresponding release label.

For automation, we could either take all cards with the next release label, add a new custom label with the provided $release_name, and remove the next release label, or follow the same approach we currently use: rename the label and create a new one.

The goal is to automate this process so these label changes happen automatically when the release is triggered.

**Comment by bryanboza** [comment]
This is now working, but we need to set the label color to `#fbca04` to maintain a consistent format across all releases.

Also, the label should be "Release : 24.11.29" we are currently missing the `:`
