### ISSUE TITLE
Mobile Portrait & Landscape are Reversed.

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25811]
[![Screenshot_2023-08-17_19-01-46.png](https://mrkr.io/s/64de6e9a5b642c4932fe81f5/2)](https://mrkr.io/s/64de6e9a5b642c4932fe81f5/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Clicking on Portrait view, should show the preview taller than wide, and Landscape should be wider than tall. But it's reversed at the moment.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64de6e9a5b642c4932fe81f8_3712884ccea28884?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3008 x 1692</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>3008 x 1554</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
Happening with Tablet too.

![Pasted_Image_8_17_23__2_03_PM](https://github.com/dotCMS/core/assets/114953617/71f2df7a-e0fb-49cc-8ed9-7d928ae93372)

**Comment by nollymar** [comment]
PR: #25848

**Comment by nollymar** [comment]
**Internal QA:** Passed



![Image](https://github.com/dotCMS/core/assets/8741395/52a7ab31-e9dd-4d92-9fde-86147819866b)

**Comment by bryanboza** [comment]
Fixed, tested on master and this is as the first version. 

![Image](https://github.com/dotCMS/core/assets/2641437/c6c9ffb1-2eb1-49c2-835a-dafccfe93ce4)
