### ISSUE TITLE
Recreating a field with same name diff type uses the same id

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25827]
### Problem Statement

When trying to recreate a field with a new data type but keeping the same name. It appears that the system is reusing the same ID as the previously deleted field, causing some unexpected behavior, for example when PP since the field type won't match but the id do, PP fails.

### Steps to Reproduce

1- Create a content type
2- Create a field (type: relationship field, name: test)
3- Check the id of the field by looking at the API (write down this id somewhere)
4- Delete the field
5- Create a field (type: WYSIWYG, name: test)
6- Check the id of the field by looking at the API
7- It's the same id

### Acceptance Criteria

We should take into consideration the field type when generating the deterministic Id.

### dotCMS Version

22.03 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![image](https://github.com/dotCMS/core/assets/5278970/52795424-26ba-4986-9b74-97be60c3cdbf)

**Comment by erickgonzalez** [comment]
Working as it should, ID now is diff:

![Image](https://github.com/dotCMS/core/assets/5278970/9dd83e65-f105-412a-9877-762f76beb77e)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_af68a64**, Docker, macOS 13.0, FF v113.0
