### ISSUE TITLE
Implement a "super push" command to sync the files from to repo to the target dotcms env

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25822]
### Parent Issue
https://github.com/dotCMS/core/issues/24354

Having the input provided by #25821 , implement a CLI command that receives a list of files (or binaries) to be sync on a target dotCMS instance. This command should receive as well: 

- The target dotCMS env
- dotCMS API Token, provided as a github secret

**Expected result:** 
The target dotCMS instance should reflect all the changes made in the source GitHub repo, including destructive actions (folder, content type, file deletions). The command should provide feedback of the progress and execution. In case of error, provide the details.

Include tests accordingly.

**Comment by bryanboza** [comment]
Fixed, tested on master // dotcms-cli-1.0.0-20231002.205953-1.jar
