### ISSUE TITLE
Spacing and Copy on Lock Message

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25829]
[![Screenshot_2023-08-18_16-46-54.png](https://mrkr.io/s/64dfa07e4fbdc381494a902d/2)](https://mrkr.io/s/64dfa07e4fbdc381494a902d/0)

Slightly better image.

![image](https://github.com/dotCMS/core/assets/114953617/5ceae097-dd3d-4a66-a899-ba881e3acf54)

### Parent Issue

https://github.com/dotCMS/core/issues/25811

### Problem Statement

The spacing on this message isn't aligned with the new style guide. Nor is the orange color on the lock.

We need a new design that accounts for this text. I'll work with Melissa to provide one as soon as she's back.

Also, the copy is bad. 

Should just say, "Locked by **{User Name}**" instead of "This Page is locked by user..." 

### Steps to Reproduce

Find content that is locked by another user, so you can see the locked by message.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest%2Ftesting&language_id=1&device_inode=](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Ftest%2Ftesting&language_id=1&device_inode=)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64dfa07e4fbdc381494a9030_14fb54e65bca62e8?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1302</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
We'll also clean up the copy on this error message.

![image](https://github.com/dotCMS/core/assets/114953617/0e82ac2c-43c1-4d16-83e3-e85b81462aca)

> # Careful! This Page is Locked!
> 
> {User Name} ({User Email}) has already locked this page, and if you unlock it now, any changes they are working on will be lost. 
> 
> It is strongly advised to talk to the person who locked the page before taking this action.
> 
> Are you sure you want to unlock this page?

Lastly, the button here should be red, not blue. The user is taking a dangerous action.

**Comment by nollymar** [comment]
It won't be solved as there will be a new implementation that will remove the usage of locks
