### ISSUE TITLE
Template Builder: Improve UX to show that the top buttons are draggables

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25826]
### User Story 
As a dotCMS user, I want to be able to easily identify the drag buttons in the template builder, so I can quickly and easily create my webpages.

### Acceptance Criteria
- Add the six dots icons to the drag buttons
- Change the text to just "Row" and "Column"
- When user hover the button, rotate and lift using shadow and position

### Proposed Objective
Core Features

### Proposed Priority 
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Design Drag Buttons
- Update Text on Buttons
- Add Animation on Mouse Hover

**Comment by rjvelazco** [comment]
### Passed Internal QA

Tested on `master`

https://github.com/dotCMS/core/assets/72418962/69a22d7d-2e70-4f97-adef-66a737b9b3d1

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_658e1bc_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
