### ISSUE TITLE
Create and configure a docker container action to invoke the CLI

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25824]
### Parent issue
#24354 

Using [this guide](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) and the dockerfile and entrypoint.sh implemented on #25823, create a docker container action that executes on each push made on a GitHub repo.

**Comment by fabrizzio-dotCMS** [comment]
This task was completed and demonstrated on the 27th of September 2024 
From that demonstration, it was concluded that using a Docker action to rebuild an image upon every push action is not the optimal way to invoke the CLI to accomplish synchronization. Therefore a brand new task has been created to cover the rework required to convert the Docker action into a script to set up and run the CLI

https://github.com/dotCMS/core/issues/26300
