### ISSUE TITLE
Introduce limit for relationship field 

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#25837]
### User Story

We'd like to propose enhancing the existing multiple relationship field functionality, which currently enables (many-to-many, one-to-many, and many-to-many) relationships between fields of different content types. To provide more control over these relationships, we suggest implementing a new feature involving a customizable limit mechanism, possibly in the form of a field variable.

To elaborate, this feature would empower administrators to specify a numerical limit on the number of contentlets that can be associated as part of this relationship. For instance, with a limit set to three, the relationship content type would only permit the inclusion of up to three distinct contentlets.

By introducing this enhancement, we aim to provide users with a finer level of control over the relationships established between content types, aligning the system more closely with specific use cases and content management requirements.

Here is an attached example in which Team can only add up to three players
<img width="1018" alt="image" src="https://github.com/dotCMS/core/assets/102758033/4142b7af-ec0e-42ee-bb3e-b7a75117a488">

### Acceptance Criteria

The proposed enhancement request will be accepted If multiple relationship fields allow a limit for adding content.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112907

**Comment by waqasakramdot** [comment]
Another customer requested for it https://dotcms.zendesk.com/agent/tickets/116591

**Comment by johnvasquez** [comment]
I would like to add to the initial description that adding both a lower and upper limit is the expectation.

**Comment by fmontes** [comment]
Moved to AirFocus
