### ISSUE TITLE
Unable to use dotcms lib in plugin

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25836]
### Problem Statement

Trying to use  `compile('com.dotcms:dotcms:23.07')` as a dependency - while we are generating the pom file, it reference a non-existent tika version:
```
➜  git:(master) ✗ ./gradlew jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/will/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.dotcms.core.plugins:com.dotcms.tika-api:1.0.0-SNAPSHOT.
  Searched in the following locations:
    - https://repo.dotcms.com/artifactory/libs-release/com/dotcms/core/plugins/com.dotcms.tika-api/1.0.0-SNAPSHOT/maven-metadata.xml
    - https://repo.dotcms.com/artifactory/libs-release/com/dotcms/core/plugins/com.dotcms.tika-api/1.0.0-SNAPSHOT/com.dotcms.tika-api-1.0.0-SNAPSHOT.pom
    - https://repo.dotcms.com/artifactory/libs-release/com/dotcms/core/plugins/com.dotcms.tika-api/1.0.0-SNAPSHOT/com.dotcms.tika-api-1.0.0-SNAPSHOT.jar
  Required by:
      project : > com.dotcms:dotcms:23.07
```

### Steps to Reproduce

Try to build a plugin with `dotcms:23.01-23.07`

### Acceptance Criteria

should be able to build a plugin with dotCMS

### dotCMS Version

`dotcms:23.01-23.07`

### Proposed Objective

Technical User Experience

### Proposed Priority

Please Select

**Comment by jcastro-dotcms** [comment]
### NOTE TO IQA AND QA:
As discussed in the Lunik Team, JARs defined as `SNAPSHOT` cannot be published to the `libs-release` section in the Artifactory Repository. For the current dotCMS versions, the only alternatives to bypass the reported error message are the following:

1. Compile the plugins against `'com.dotcms:dotcms:23.06'`.
2. Compile against `'com.dotcms:dotcms:23.07'` BUT set the `transitive` attribute to `false` and manually add all the dependencies as required.

Otherwise, we'll have to wait for the next dotCMS release that includes this code change to come out so the fix can be tested properly.

**Comment by fmontes** [comment]
Can't verify until release is out.

**Comment by fmontes** [comment]
`implementation 'com.dotcms:dotcms:23.10.24'`

**Comment by fmontes** [comment]
Note to QA, contact @jcastro-dotcms

**Comment by fabrizzio-dotCMS** [comment]
I can get to build the rest plugin with the latest `24.06.26` 
<dependencies>
        <dependency>
            <groupId>com.dotcms</groupId>
            <artifactId>dotcms-core</artifactId>
            <version>24.06.26</version>
            <scope>provided</scope>
        </dependency>
        
    </dependencies>

**Comment by bryanboza** [comment]
this is causing errors using the last starter: 



![Image](https://github.com/dotCMS/core/assets/2641437/dad83212-d947-4636-9079-14833b7facca)

We need to update the libs and push to NPM

**Comment by bryanboza** [comment]
Fixed, after update the libraries, now this is working as expected
