### ISSUE TITLE
Template Builder: Fix Save Header/Footer/Sidebar Issues

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25840]
### Problem Statement
In the template builder, save header and footer information is not working.

### Steps to Reproduce
Looks like is only happening from the edit page layout

1. Go to the dotCMS template builder
2. Create a new template
3. Save
4. Edit the template and edit header, footer and sidebar
5. See if it saves

### Acceptance Criteria
- Save header, footer and sidebar should work.
- It should work from edit page layout and template

### External Links
N/A

### Assumptions & Initiation Needs
- It is assumed that the issue is related to the template builder save button not working properly.
- The developer needs access to the dotCMS template builder.

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
Check header and footer as well.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- **Docker Image:** [`dotcms/dotcms:master_7e2f633`]


https://github.com/dotCMS/core/assets/72418962/c0d2467d-419b-492d-bd9b-88d7dc347cd6

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
