### ISSUE TITLE
Block Editor: Open link in new window checkbox in the block editor. Don't save the selection.

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#25842]
### Problem Statement

This selection can't be saved when checking or unchecking the option "Open link in new window" checkbox and adding an image into the block editor.

### Steps to Reproduce

1.- Add an image into the block editor.
2.- Add a URL link.
3.- Open link panel and uncheck the option "Open link in a new window."
4.- The uncheck selection still needs to be saved.

https://github.com/dotCMS/core/assets/12899960/b7083b0d-5829-4e6f-a971-ff809493716e

### Acceptance Criteria

The selection check/uncheck option should be saved.

### dotCMS Version

Demo
QA 23.01

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112923
https://dotcms.slack.com/archives/CSHTYUR7H/p1692642079655649

**Comment by zJaaal** [comment]
## IQA: PASSED

Now is fixed.

Version: `master-latest`

### Screenshot

https://github.com/dotCMS/core/assets/63567962/2fe3ec0f-1d12-4437-8cf6-d47f23979e84

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_226a23f_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
