### ISSUE TITLE
Apps : Fix Hidden Secrets Not Saving in Dot Velocity Secrets

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25855]
### Problem Statement
In the app "Dot Velocity Secrets" the hidden secrets are not getting saved. Users are inputting the secret but it is not being saved and therefore inaccessible in the app.

### Steps to Reproduce
1. Go to apps > Dot Velocity Secrets app
2. Create a new hidden value
4. Click save
5. Observe that the secret is not saved

### Acceptance Criteria
We need to make sure that we hide the value in the UI, but we actually send the real value to the backend. 

### External Links
https://github.com/dotCMS/core/assets/751424/4bd91927-411d-4f05-ba26-b9ee9dc8d735

### Assumptions & Initiation Needs
We assume that the problem is related to the backend code not properly saving the hidden values.

### Quality Assurance Notes & Workarounds
We can test the functionality by manually inputting hidden values in the UI and then verifying that they are saved in the backend. As a workaround, users can manually re-enter the secret each time they need to access it.

**Comment by bryanboza** [comment]
Ok, now we are able to save hidden secrets, but I think we need a UX improvement here because the way this is working is a little bit weird, let me explain this in the follow video: 

https://github.com/dotCMS/core/assets/2641437/b5488276-64e1-4d9f-b09e-4d604a39fcb6

**Comment by fmontes** [comment]
@bryanboza 100% new ticket

**Comment by bryanboza** [comment]
Mover to card #26179

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0

**Comment by jdcmsd** [comment]
Reopening — I'm seeing this behavior again on 24.04.24 as a possible regression. Seems on subsequent saves, the `*****` values overwrite the values underneath.

**Comment by jdcmsd** [comment]
Sorry, disregard; will open new ticket.
