### ISSUE TITLE
Template Builder: Add a Link to Themes in listing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25860]
### User Story
As a dotCMS user, I want to be able to link to themes easily, so I can quickly find and access them.

### Acceptance Criteria
- A link to the theme folder in the template listing and template detail should be added.
- The link should be easy to find and navigate to.

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
![Image](https://github.com/dotCMS/core/assets/751424/4253fa59-e373-480d-9d78-3e6096199319)

This link to the Site Browser to the corresponding theme folder open, we might need some backend work for this.

### Assumptions & Initiation Needs
- The link must be added in a way that does not interfere with the existing navigation of the template listing and builder.
- We need extra backend work to be able to link to the folder like we did in the containers portlet

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Create a link to the theme folder in the template listing and template detail: 2 hours

**Comment by jdotcms** [comment]
1)  create a new property on the templateView called such as templatePath
2) use this snippet to get the actual path and set it
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/DotTemplateTool.java#L356


Thanks

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: PASSED
In the **Site > Templates** portlet, if available, the name of the Template's theme is displayed and it will take you to the theme's folder in the **Site > Browser** portlet when clicked. The link will not be available for a given Template under the following circumstances:

1. It's a Template as File.
2. It's an Advanced Template.
3. It uses the System Theme.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0

Issues will be work on #26203
