### ISSUE TITLE
Shift Preview Menu Down

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25867]
[![Screenshot_2023-08-23_14-47-58.png](https://mrkr.io/s/64e61c1e66571c11a489cfdb/2)](https://mrkr.io/s/64e61c1e66571c11a489cfdb/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Need to move the preview menu down so we can see the blue selector behind it. This design shifted since we started the project, sorry about that!

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64e61c1e66571c11a489cfde_1da7c5f219182376?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 912</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
Dupe #26257

**Comment by dcolina** [comment]
Internal QA: PASSED.

You can see it in the image below.



![Image](https://github.com/dotCMS/core/assets/29883881/87dee912-e895-4bef-88ff-25f1dcb11a4c)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
