### ISSUE TITLE
Some webp images cannot be decoded

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25861]
### Problem Statement

There are some instances of webp images that cannot be read using the old `javavp8decoder`.  

### Steps to Reproduce

- Unzip the attached image
- Upload this image
- Try to view/resize

[test-image.webp.zip](https://github.com/dotCMS/core/files/12413051/test-image.webp.zip)

### Acceptance Criteria

The attached image needs to be resizable?

### dotCMS Version

23.08

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA:
As per discussion with @wezell , the test [test-image.webp.zip](https://github.com/dotCMS/core/files/12413051/test-image.webp.zip) file attached to the ticket's description is corrupted, and will not work for testing the code fix. Please use a different WebP file for that.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: master_21e04e1_SNAPSHOT

I used this test WebP file: [my-webp-image.webp.zip](https://github.com/dotCMS/core/files/12528298/my-webp-image.webp.zip) and was able to upload and manipulate the image without any issues.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_658e1bc_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
