### ISSUE TITLE
[UI] - Improve Experiment health check "lock" screens.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25876]
### Parent Issue
#24343

### User Story
If the Analytics key isn't configured, give a marketing focused message, along the lines of:

Experiments is an advanced feature that enables you to perform A/B tests to help improve your ability to achieve specific goals.

Please contact your Customer Success representative for more information.

<img width="955" alt="image" src="https://github.com/dotCMS/core/assets/31667212/fa8bd3b9-da11-4bd2-a36e-af634ac26bf4">

**Analytics App not Configured Properly**

<img width="1108" alt="image" src="https://github.com/dotCMS/core/assets/31667212/0fcbacba-75d6-4c2c-9e73-a77ea644681a">

### Acceptance Criteria

Respect the message for the two different scenarios. 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates
\

**Comment by hmoreras** [comment]
valid values for health check endpoint: 

"entity": {
        "health": "OK"
    },

>  OK, NOT_CONFIGURED, CONFIGURATION_ERROR

**Comment by dsilvam** [comment]
Passed Internal QA: Three states reflected on the UI. 
1. Proper message when not Analytics App is configured
2. Proper message when Analytics App is incorrectly configured
3. Proper access to Experiments when App configured correctly.
