### ISSUE TITLE
Using showFields field variable replicates title to all items

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25870]
### Problem Statement

When you use the `showFields` field variable to select which fields you want to show at a relationship, if one of those is the Title field, it will replicate the same for all items.

### Steps to Reproduce

1- Create a child Content type with a couple of fields (Text:Title, Text:ConsId).
2- Create a parent Content Type with a relationship field
3- Add the Field Variable to the relationship field: `showFields = consId,title`.
4- Create a couple of child contents with diff values.
5- Create parent content and relate the child ones.

![Screenshot 2023-08-23 at 10 29 42 AM](https://github.com/dotCMS/core/assets/5278970/5d452f8b-4e9c-4891-8f1b-1be7431b5179)

### Acceptance Criteria

Should show the correct value for each of the items related.

### dotCMS Version

22.03 LTS +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113027

**Comment by erickgonzalez** [comment]
Showing correct values

![Image](https://github.com/dotCMS/core/assets/5278970/478bb4c8-b2b8-43be-a772-136c9a31ee76)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_af68a64**, Docker, macOS 13.0, FF v113.0
