### ISSUE TITLE
Metrics Stage 3: Save metrics data to Analytics Infrastructure

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25886]
We need to connect the Experience plugin to the analytics infrastructure, so that when the plugin is installed on a system, the data it collects can be sent to the analytics DB.

### Data Format
* The metrics data will be sent to the analytics infrastructure as a JSON string.
    * Note that the format may change later, when a reporting tool is selected, to optimize the data analysis or reporting.  But for now we just want to ensure that the data can be sent successfully.

### Execution
* Sending of the metrics data should be executable via a Java method.
    * It should _not_ be triggerable via an API method.

### Logging
* DEBUG level logging should be implemented to log every time the data is sent.
    * This should include, at a minimum, the full data sent (the JSON string) and the response from the analytics infrastructure.
* WARN level logging should be implemented to log any time the data fails to send.
    * This should include, only the error state and error message.
    * It should not include the full data sent.
* No INFO level logging should be implemented.

**Comment by victoralfaro-dotcms** [comment]
PRs:
- https://github.com/dotCMS/core/pull/26587
- https://github.com/dotCMS/com.dotcms.experience/pull/1

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
- Start a dotCMS docker container with corresponding code changes
- Clone the `com.dotcms.experience` plugin repo like this:
```
git clone git@github.com:dotCMS/com.dotcms.experience.git
```
Or
```
git clone https://github.com/dotCMS/com.dotcms.experience.git
```
- Checkout the working branch:
```
git checkout -b issue-25886-plugin-metrics
```
- Build the plugin jar
```
./gradlew jar --rerun-tasks
```
- In the plugins portlet upload the previously generated plugin jar (`<com.dotcms.experience repo folder>/build/libs/com.dotcms.experience-1.0.jar`)
- Import into your postman the collection located at `<com.dotcms.experience repo folder>/src/test/curl-test/Metrics.postman_collection.json`
- Run request and make sure  the http status is a `200`

**Comment by dsilvam** [comment]
Passed Internal QA. 

Running requests with Analytics Up: 

```
single-node-full-starter-dotcms-1      | 15:36:36.719  DEBUG metrics.MetricsPayloadSenderRunnable - Sending to [http://host.docker.internal:8081/api/v1/event] the following metrics: {
single-node-full-starter-dotcms-1      |     "payload": "some metrics"
single-node-full-starter-dotcms-1      | }
single-node-full-starter-dotcms-1      | 15:36:36.746  DEBUG metrics.MetricsPayloadSenderRunnable - Response from metrics endpoint [http://host.docker.internal:8081/api/v1/event]: Response{response={"status":"ok"}, statusCode=200}
```
Running requests with Analytics Down: 
```
single-node-full-starter-dotcms-1      | 15:38:54.877  WARN  metrics.MetricsPayloadSenderRunnable - Failed to send metric to http://host.docker.internal:8081/api/v1/event, got a -1 :
single-node-full-starter-dotcms-1      | 15:38:54.877  WARN  metrics.MetricsPayloadSenderRunnable - Failed metrics post: {
single-node-full-starter-dotcms-1      |     "payload": "some metrics"
single-node-full-starter-dotcms-1      | }
```
