### ISSUE TITLE
Metrics Stage 3: Create scheduled job to save metrics

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25888]
Modify the Experience plugin to create a scheduled job which automatically saves all the metrics to the analytics infrastructure on a schedule.

### Job
* The job should be named "dotCMS Metrics Scheduler".
* The job should be started when the plugin is started.
* The job should be stopped when the plugin is stopped.
* When the job runs, it should execute the method to save the metrics to the analytics infrastructure (https://github.com/dotCMS/core/issues/25886).

### Schedule
* The schedule should be settable via a configuration property, `METRICS_SAVE_SCHEDULE`.
    * The property should accept a cron expression.

### Logging
* DEBUG level logging should be implemented to log when the job runs.
    * This should include the cron expression (as specified in the config property).
* No INFO or WARN level logging should be implemented.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/20

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: The Job is working

**Comment by dsilvam** [comment]
Let's have a Config property for the scheduling

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/23

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: a couple of thing here

First: When. I tested locally for me did not work move my local time forward  I must to wait until the CRON time was arrived and it got run.

Second: For some reasons even when my local time is set to be "Central Standard Time" on the code it take my Default Zone as UTC so the Job got run 6 hours before that it was set on the CRON but I am not sure if it is a local problems so we are going to wait until this issue https://github.com/dotCMS/core/issues/27452 to check if it happended on the server too

**Comment by freddyDOTCMS** [comment]
QA NOt needed because the Job is not sending the Metric Snapshot to the Endpoint yet
