### ISSUE TITLE
[UI] Add the ability to Abort a Running Experiment

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#25894]
### Parent Issue
#24343

### User Story

The user should be able to cancel an experiment while is running.

### Acceptance Criteria

- Add in the experiment configuration page and listing an option that cancel and experiment if is running. 
- Label `Abort Experiment` 
- Should have a confirmation, that lets the user know that any data already collected will be discarded: 

> 
> Cancelling the Experiment will delete any data already collected.  If you wish to stop the Experiment but keep the data already collected, please select "End Experiment" instead.
> 
> Do you wish to continue?"
> 

Confirmation Dialog labels: Cancel and Abort Experiment 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Passed Internal QA: Ability to Abort an Experiment in place and working as expected.
