### ISSUE TITLE
Creating a contentlet in a 2nd language removes related content

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25896]
### Parent Issue

https://github.com/dotCMS/core/issues/24415

### Problem Statement

In the content editor, when you create another version of a contentlet in another language it removes related content. This happens whether you select to copy fields from the default language. Because of how related content works, it is removed from all languages.

### Steps to Reproduce

1. Start up the demo starter
2. Open up a blog with an author
3. Select 'ES' from the language dropdown
4. Select 'Yes' when it asks `Populate Espanol - Espana content with English - United States content ?` (it happens whether you select Yes or not, just easier to test this way)
5. Save/Publish 
6. Reopen the English version, the author will not be related anymore

### Acceptance Criteria

The relationship should not be lost when creating a version in an additional language

### dotCMS Version

22.03.8, 23.01.6 and 23.08.16

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://dotcms.zendesk.com/agent/tickets/113119

_No response_

**Comment by waqasakramdot** [comment]
Another customer hitting: https://dotcms.zendesk.com/agent/tickets/113119

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_af68a64**, Docker, macOS 13.0, FF v113.0
