### ISSUE TITLE
Unable to reuse content inside the variants 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25901]
### Problem Statement

In experiments, users are unable to reuse content inside the variants in dotCMS. When attempting to reuse content from another container section, the content does not appear correctly in the list of contents. Even if you are inside the same variant 

https://github.com/dotCMS/core/assets/2641437/fd9e341c-4822-4c5b-b7a9-c014f20bae79

### Steps to Reproduce

- Log in to dotCMS.
- Create an experiment
- Add a variant for this experiment page.
- Add a new piece of content inside the variant 
- Attempt to reuse content from another container in the same variant

### Acceptance Criteria

- We need to list all the content added inside the variant if you try to add a new piece of content from a different container ( if you are in the same variant)

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
Tested using `dotcms/dotcms:master_0b9267e_SNAPSHOT`
New content added to variant
![Image](https://github.com/dotCMS/core/assets/64026161/2bf33737-4873-4435-9753-e52d96cf1d2d)
Content found when adding
![Image](https://github.com/dotCMS/core/assets/64026161/53a2e8aa-82c1-4efa-986f-a0fbc53f507f)
![Image](https://github.com/dotCMS/core/assets/64026161/e7984f6c-2d9c-4c88-903c-ef652558efe4)
Preview
![Image](https://github.com/dotCMS/core/assets/64026161/b4aee22f-4312-44a3-8784-38343216bc92)
![Image](https://github.com/dotCMS/core/assets/64026161/d94184c8-f972-4f40-bf28-80491a7e820e)

**Comment by bryanboza** [comment]
After the last changes, now we are unable to see the regular contents when you are into the variant, we are just listing the contents that you create inside the variant 
Here the video: 

https://github.com/dotCMS/core/assets/2641437/ead921aa-75a4-4003-a9fa-fdc9a28f7842

**Comment by oidacra** [comment]
IQA Passed:
- Original Acceptance Criteria: Reuse content from another container in the same variant ✅
<img width="1310" alt="Screenshot 2023-09-21 at 1 04 26 PM" src="https://github.com/dotCMS/core/assets/1909643/110b45b4-f586-4f80-8684-3001fe8ff872">

Bug fixed
- See the regular contents when you are into the variant not just list the contents that you create inside the variant ✅

![Sep-21-2023 13-09-12](https://github.com/dotCMS/core/assets/1909643/5cf7dc88-ca32-4841-8303-c1d93010a524)

**Comment by bryanboza** [comment]
We still having problems here: 

We are inconsistent between the contents that we show with the traditional way to add content to a page//variant and with the contents that we show from the content pallet 

- Attached a video with the description 
https://github.com/dotCMS/core/assets/2641437/8882fd57-fb3c-4daa-8fd9-39bec0fc3744

**Comment by john-thomas-dotcms** [comment]
So, to clarify the issue highlighted by @bryanboza in his last comment:

When you create new content while editing a variant, then, while editing that variant:
1. The new content will be displayed in the content list when using the "+" button.
2. But the new content will not be displayed in the content palette (even while editing that variant).

**Comment by victoralfaro-dotcms** [comment]
Tested using image: `dotcms/dotcms:master_534774e_SNAPSHOT`
New content added to variant's container
<img width="1051" alt="image" src="https://github.com/dotCMS/core/assets/64026161/05d01ab3-3a93-4bb4-9efb-a22ba145ea6d">

**Comment by bryanboza** [comment]
We need to refresh the content palette when you change the language drop down, this because after you change the lang, we are refreshing the page, but if you try to add a new piece of content we are still showing the list of contents in the other language. 

https://github.com/dotCMS/core/assets/2641437/0633d0e7-e0c1-4e6b-b7b6-41879de71e77



This is happening just on experiments, b/c on the regular edit mode when you change that value we are redirecting to the preview tab, then if you try to edit we refresh the whole page.

**Comment by hmoreras** [comment]
Refresh the content palette with lang change: https://github.com/dotCMS/core/pull/26450

**Comment by dsilvam** [comment]
Passed Internal QA: Content is being refreshed and showing in the proper language upon changing it in the Language dropdown.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

 Now it is working as expected, but we still having problems with the content pallette, this problem is a separated issue and was moved to this card: https://github.com/dotCMS/core/issues/26773
