### ISSUE TITLE
Content pallet is not respecting language drop-down in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25900]
### Problem Statement

The content pallet in dotCMS does not respect the language drop-down selection, causing when you try to add a new piece of content to the page we are ignoring the selection and always try to add a new piece of content on the default language 

**This is totally distinct if you try to add the content from the + button.** 

https://github.com/dotCMS/core/assets/2641437/9d348562-a6cd-44a1-a3f9-f22e8db64ac5

### Steps to Reproduce

- Log in to dotCMS.
- Create a multi-language page 
- Try to edit the page 
- Select any language of the page different than the default 
- Try to add a new piece of content using the content pallet 
- Observe that the content displayed in the pallet does not match the selected language.

### Acceptance Criteria

- When a language is selected from the language drop-down in the content pallet, we need to respect that selection and the new piece of content modal should be in the same language 
- We need to be consistent in the both ways to add content to the page 

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
I found another similar case which causes an obscure error when trying to drag non-default language content from the content palette to the page:

**Comment by john-thomas-dotcms** [comment]
I found another related problem when trying to drag non-default language content from the palette onto the page.

Steps to reproduce (on demo, running v23.08.16 built on 08/22/2023):
1. Open an existing Activity.
2. Change the language to Spanish, and copy confirm to copy the default language content to the Spanish version.
    a. Change the title to make the Spanish language version distinct.
    b. Save the Activity.
3. Open one of the Destination pages (like Costa Rica) in the page editor.
4. Change the Language to Spanish.
5. Select the Edit tab.
6. Drag the Spanish language Activity from the content palette into a container that will accept it.
**Result:** The error message below:
![image](https://github.com/dotCMS/core/assets/13456955/dc7175ae-d963-41e5-a792-5d91171099c7)

The error message reads:
```
Content 'Foto4.jpg' [ 91e68829-8c85-45cb-8b2b-cdf7a2104c23 ] has already been added to Container '//demo.dotcms.com/application/containers/default/'
```

**Comment by erickgonzalez** [comment]
This is not longer reproducible in latest master, seems that this was fixed with the new page editor.
