### ISSUE TITLE
 Key/Value field escaping colon and comma characters to HTML encoded version.

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#25903]
### Problem Statement

Key/Value field escaping colon, comma ~and double-quote~ characters to HTML encoded version.

Content Items having key value fields storing values containing colon, comma, ~and double-quote~ characters are not displayed as expected once exported. 
They display the HTML-encoded values. 
It converts it to `&#58`, `&#44` and ~`&#34`~

### Steps to Reproduce

1. Start up dotCMS with demo content.
2. Edit one of the products in the Products content type: Add a new key-value pair containing special characters like comma, 
colon (See attached Screenshot: Key value field added)
3. Publish the content 
4. Export the content to a CSV.
5. Check the value of the key-value field stored and if It has HTML encoded values (Screenshot provided: Exported content)
<img width="1182" alt="Add Key value Field " src="https://github.com/dotCMS/core/assets/139247809/2256b844-a0d3-4c1d-9d87-3c7a6e215f58">
<img width="1142" alt="exported content" src="https://github.com/dotCMS/core/assets/139247809/8da1ffee-6c02-4f23-9958-45f6a29abbdd">

### Acceptance Criteria

The content in the key-value fields should be displayed as given instead of HTML-encoded values.
For commas and colons, it's working not encoded, so let's skip the encoding.

Q: How are we supposed to escape quotes??
A: There is no way to escape quotes since it's a JSON inside a CSV. So, quotes will be kept as encoded.

### dotCMS Version

23.01.4
23.08.16
23.01.6

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113023

**Comment by dsolistorres** [comment]
Internal QA passed:
Exported CSV file shows commas and colon characters without escaping them for key/value fields:
![image](https://github.com/dotCMS/core/assets/2894221/ab61b138-9b08-4604-9d86-f40e41e7ecdf)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_19b2057**, Docker, macOS 13.0, FF v121.0.1
