### ISSUE TITLE
CLI Workflow is missing the systemActionMappings attribute

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#25913]
### Problem Statement

We should support systemActionMappings as they are essential part of Workflows and our models don't know anything about that attribute 

### Steps to Reproduce

Pull a CT using the cli  e.g. FileAsset
Now compare it against this https://demo.dotcms.com/api/v1/contenttype/id/fileAsset
notice the file pulled using the CLI does not have that attribute

### Acceptance Criteria

The files should both martch

### dotCMS Version

current master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Internal QA:** passed.

I have tested pulling several content types and I could see the systemActionMappings array returned
