### ISSUE TITLE
Styles in template dropdown when creating new pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25918]
### Problem Statement

When creating new pages on dotCMS, the styles in the template dropdown are not displayed properly or are missing, resulting in a loss of styling options for the user.

![image](https://github.com/dotCMS/core/assets/2641437/85449ded-cc50-4d81-a47c-6fd49c057fde)

Here is the previous style:
![image](https://github.com/dotCMS/core/assets/2641437/9338628b-1bac-4ff0-a1b4-3d04767d3dce)

### Steps to Reproduce

- Log in to the dotCMS 
- Navigate to the section for creating new pages.
- Click on the dropdown menu to select a template for the new page.
- Observe that some or all of the styles in the template dropdown are either not displayed or are missing.

### Acceptance Criteria

- When creating a new page, all the styles in the template dropdown should be properly displayed and available for selection.
- The styles should be visually consistent and clearly distinguishable in the template dropdown.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
<img width="460" alt="image" src="https://github.com/dotCMS/core/assets/751424/637d818e-0f7d-4a95-b962-5739d2d2cd8e">

**Comment by rjvelazco** [comment]
### Passed Internal QA

Tested on `master`

https://github.com/dotCMS/core/assets/72418962/036563b6-acac-4218-8dad-10b2552ce0c7

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_26aa457_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Template title gets cutoff if is long enough.
![Screenshot 2023-09-05 at 12 20 20 PM](https://github.com/dotCMS/core/assets/129882031/444c9a1a-139e-4bfe-b419-20bfdc1a3527)

**Comment by fmontes** [comment]
@josemejias11 create another issue for that.

**Comment by josemejias11** [comment]
> @josemejias11 create another issue for that.

https://github.com/dotCMS/core/issues/26059 @fmontes
