### ISSUE TITLE
Template Builder: File containers are not getting saved correctly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25917]
### Problem Statement
Currently when creating file containers in the template builder, the containers do not save correctly.

### Steps to Reproduce
1. Create a template
2. Add a file container
3. Create a page with this template
4. Add content
5. Edit the template and add the same container
6. See how the content in the page gets duplicated

The problem is we are sending the `identifier` for the new file containers and the endpoint expects the `path`.

### Acceptance Criteria
Content in a page should not be duplicated

### External Links 
In the old template builder, this is how we update the id:

https://github.com/dotCMS/core/blob/master/core-web/apps/dotcms-ui/src/app/api/services/dot-template-containers-cache/dot-template-containers-cache.service.ts#L29

### Assumptions & Initiation Needs
- The issue is isolated to the file containers not saving correctly.
- The solution requires the path to be sent as the id.

### Quality Assurance Notes & Workarounds
- Test that the file containers are now saving correctly.
- If there are any issues, check to make sure the path is being sent as the id.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now it is working as expected.
