### ISSUE TITLE
Template Builder: Add Host to Container List

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#25916]
### Problem Statement

As a dotCMS user, when using the Template Builder feature and attempting to select a container from the container list, I want to see the container's name and site.

<img width="1168" alt="duplicated-container-issue" src="https://github.com/dotCMS/core/assets/72418962/c4b9ae67-0ccc-4c60-b26c-ac34057595eb">

### Steps to Reproduce

1. Go to Template.
2. Select any `Design Template`
3.  Click on the "Add Container" option.
4. See the error.

Note: You should have two Sites and a container with the same name on each side.

### Acceptance Criteria

Displays the site alongside the container name in the container list. This enhancement will make it convenient for users to identify the name and site associated with each container.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
@rjvelazco Also add sort by name

**Comment by zJaaal** [comment]
Scroll Height for dropdown is too much, I added a PR fixing it 

<img width="1512" alt="Screenshot 2023-08-29 at 1 37 01 PM" src="https://github.com/dotCMS/core/assets/63567962/3292a6d3-c75b-435d-b219-4fee2885e513">

**Comment by zJaaal** [comment]
### Passed Internal QA

Tested on `master/lastest`

#### Screenshot

https://github.com/dotCMS/core/assets/63567962/45c39142-d1d7-4ecc-a123-43d0474fa62a

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_26aa457_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
