### ISSUE TITLE
Template Bulder: Need to disable the auto publish when the template is archived 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25937]
### Problem Statement

As part of the new requirements, we are firing the auto-publish job 5 seconds after you do some changes, but this is causing an error when the template is in the `archived` state, this b/c the publish is not an available workflow action. 

Then we are getting an error on the log and also printing an error at the UI level. 

https://github.com/dotCMS/core/assets/2641437/1ada2c76-f60f-49b6-bda5-363923777790

Here is the noisy log: 
https://gist.github.com/bryanboza/f34d0498bdefe465cb3fd778835c73b8

Additionally, if you continue doing changes here, we get a JS error and then we are unable to navigate to any other portlet or go out of it. 

### Steps to Reproduce

##Case 1
- Login as admin 
- Navigate to templates portlet 
- Archive some existing template 
- Try to edit it, and wait for the auto-publish job

##Case 2
- After finishing the case1 continue doing some changes in the template 
- Wait 5 seconds and try to navigate to another portlet 

### Acceptance Criteria

- If the template is archived we need to disable the auto-publish 
- We need to catch the exception and print just a line error in the log 
- We need to be able to continue navigating after the error need

### dotCMS Version

Tested on master  

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by rjvelazco** [comment]
### Passed Internal QA

We decided to keep the notification instead of disabling the `auto-publish` in this [Slack Conversation](https://dotcms.slack.com/archives/CQQMX585N/p1693340596190949)
#### Tested on `master`

https://github.com/dotCMS/core/assets/72418962/40ba0d50-ae6c-4299-a1d2-8ece289d8c44

**Comment by fmontes** [comment]
We are not disabling autosave... the message that is not saving is ok, but we are making sure that the app don't crash.

**Comment by bryanboza** [comment]
Fixed, now it is working better and it is not breaking the portlet. We can close this card for now, some improvements moved to a new card https://github.com/dotCMS/core/issues/25981
