### ISSUE TITLE
Redesign the SEO Cards

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#25941]
### Parent Issue

#24862 

### Task

Based on the meeting with Melissa, We want to redesign the SEO Cards

Design: https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-6961&mode=design&t=fV0RU7xG0A8s2c99-0

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dcolina** [comment]
Internal QA: PASSED.

You can see the new design implemented.

![Image](https://github.com/dotCMS/core/assets/29883881/706492ea-7cc2-4c83-9422-8a345834c031)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
