### ISSUE TITLE
SEO Improvements: Validate when favicon or preview image are broken

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25959]
### Task

When I run the validations for Google, Twitter, Facebook or LinkedIn, the system should verify that a favicon and preview images actually exist (404 validation), not just verify that the tags exist in the html. In case they don't exist, we should display the error. 

This is how it looks now: 
<img width="1229" alt="Screenshot 2023-08-28 at 4 30 59 PM" src="https://github.com/dotCMS/core/assets/8741395/6930aa0d-c0fc-4fc9-b0d6-abbdefc903d6">

As you can notice, it says that a favicon is found, but the image is broken

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The SEO validations should verify 404 responses for favicon and preview images. In case any of these images is broken, we should display an error with the message in the section validation.

**Comment by dcolina** [comment]
Internal QA: PASSED.

https://github.com/dotCMS/core/assets/29883881/8e7e0ae8-0d74-493f-82db-2735c47d88b4

**Comment by josemejias11** [comment]
**Approved with note**: Tested on **master_3c41b76_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Note:
Image looks good on the app but if you go to the url, it shows a 404 https://localhost:8443/application/themes/travel/img/favicon.png
