### ISSUE TITLE
[UI]: Don't show Archived Experiments by default

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25965]
We have a filter to allow limiting which Experiments are shown in the list, based on the state of the Experiment.  Right now, by default, all states are selected by default (Draft, Running, Ended, Archived, Scheduled).

We need to make 2 changes to this list of filters:
1. Unselect Archived by default.
    * Archived Experiments should not be shown by default; the user should have to manually change the filter to show them.
2. Move Scheduled after Draft.
    * So, the order of the filters in the list should be: Draft, Scheduled, Running, Ended, Archived

**Comment by bryanboza** [comment]
Fixed, now this is working as expected. Tested on master // Docker // FF
