### ISSUE TITLE
SEO Improvements: Use a hand cursor for "Edit" and "Preview" buttons

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25962]
### Problem Statement

The cursor is not changing to a hand when I hover over the "Edit" and "Preview" links.

https://github.com/dotCMS/core/assets/8741395/4bca22ea-21fe-4654-a1ef-662fba2764a5

### Steps to Reproduce

Open the Edit Mode when the SEO Improvements feature flag is enabled and hover over "Edit" and "Preview" buttons.

### Acceptance Criteria

The hover event should behave the same way in all the buttons that exist in the Edit Mode toolbar

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by wezell** [comment]
I saw this too Nolly, thanks for reporting it.

**Comment by dcolina** [comment]
Internal QA: PASSED.

https://github.com/dotCMS/core/assets/29883881/ebb4e294-6e36-49fc-85ab-41861f7b9987

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
