### ISSUE TITLE
remove remote call from js

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25972]
### Problem Statement

The lib.js we ship with includes a call to jitsu.com - we need to remove this and have it call the local environment.

### Steps to Reproduce

look at your network tab

### Acceptance Criteria

not make call to jitsu.com

### dotCMS Version

23.08

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
See:
https://github.com/dotCMS/jitsu/commit/af591d413c2056ef3dbc0ef6192375df8fe762f4

**Comment by oidacra** [comment]
IQA Passed:
lib.js now comes from the local environment

![Image](https://github.com/dotCMS/core/assets/1909643/7ff51c50-336c-4b24-99ee-10efa7e6f2d4)
