### ISSUE TITLE
Document the pre-release and release github actions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25979]
### User Story

As a dotCMS dev, I need to have documentation available so when issues arise I know where I can go a look for troubleshooting. Currently there's no way to fix any issues besides of contacting the developer of the actions. 

### Acceptance Criteria

Documentation explaining how these two processes work and how to troubleshoot. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
Documentation added to the devWiki:
- https://authoring.dotcms.com/devwiki/automated-release-process
- https://authoring.dotcms.com/devwiki/pre-release-process
