### ISSUE TITLE
Update _button.scss disabled serverity state

### ISSUE THREAD

**Issue by prince-kumar** [dotCMS/core#25985]
### Parent Issue

Update _button.scss disabled serverity state is not handled, It opens up the default state and severity 0 

### Problem Statement

Update _button.scss disabled serverity state is not handled, It opens up the default state and severity 0 
Browser chrome and safari. 
Mac os 13.3 (22E252)
Apple M1 Pro

### Steps to Reproduce

Run the core locally and turn on the experiment to achieve the state and the button locally. 

### Acceptance Criteria

The basic update button severity should be mapped to the update branch. 

### dotCMS Version

[v23.99.13](https://github.com/dotCMS/core/releases/tag/v23.99.13)

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Are you still seeing this? Can you give us more information? a screenshot?

**Comment by prestonso** [comment]
@prince-kumar Any update here?

**Comment by prince-kumar** [comment]
we can close the issue now.

**Comment by prestonso** [comment]
Thanks @prince-kumar!
