### ISSUE TITLE
Container Selector: Improve UI/UX for grouped options

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#25987]
### Task

Improve `ui`/`ux` for dropdown grouped option header

![dropdown-grouped-options](https://github.com/dotCMS/core/assets/72418962/1b6a6c29-6b39-40bf-8580-84a5bc3bfa12)

### Proposed Objective

ORK: User Experience

### Proposed Priority

Priority: 3 Average

### Acceptance Criteria

Add a light gray background

**Comment by zJaaal** [comment]
# Passed Internal QA

Tested on master Latest

## Screenshot

https://github.com/dotCMS/core/assets/63567962/6c8b7f35-c878-4c6b-9dfc-16d9fbe6dc6a

**Comment by wezell** [comment]
@zJaaal what does it look like if you search for "default"?

**Comment by zJaaal** [comment]
@wezell It looks like this: 

<img width="342" alt="Screenshot 2023-09-07 at 10 14 09 AM" src="https://github.com/dotCMS/core/assets/63567962/495ce1e6-e9f5-4f86-90d2-97fad687becc">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_839d283_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
