### ISSUE TITLE
Template builder: Improvements working on archived templates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25981]
### Parent Issue

Related to #25937 

### Problem Statement

When you are working in an archived template we need some improvements: 

- We need to catch the exception and print just a line error in the log, something like: 
```Template can not be published because is archived```
Right now we are printing multiple lines of error which is too noisy 

- After getting the error, we are showing a kind of error that just say `OK` which does not make sense say ok if something is wrong, we need to change that to some error message
![image](https://github.com/dotCMS/core/assets/2641437/69b31e61-ebc9-43e6-baa3-0fe1362a2949)

### Steps to Reproduce

- Login as admin 
- Go to templates 
- Create a new template 
- Archive it
- Made some change and wait 5s 

### Acceptance Criteria

- We need to print just a line error
- The message should indicate what is failing 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
This is not happening anymore we can edit archived templates normally.
