### ISSUE TITLE
Template Builder: Unknown error appears when editing templates and selecting themes in the application

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25995]
### Problem Statement

An "Unknown Error" message appears when attempting to edit templates or select a theme within the application. This issue hinders the ability to customize templates and themes, impacting overall usability.

### Steps to Reproduce

1. Open the application
2. Go to the templates portlet
3. Attempt to edit a template 
4. Try to change the theme 
5. Wait 5 seconds and observe that an "Unknown Error" message is displayed

### Acceptance Criteria

Users should be able to edit templates and select themes without encountering errors.

### dotCMS Version

Tested on pre-release version 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

![Screenshot 2023-09-05 at 12 18 05 PM](https://github.com/dotCMS/core/assets/129882031/ca773529-2c89-4b65-a21c-7d58bb38a98e)

https://gist.github.com/josemejias11/b17827e2679e60c779c891ef24373a90

**Comment by bryanboza** [comment]
Fixed, tested on the release candidate and now I'm unable to reproduce.
