### ISSUE TITLE
Create a site selector for the container selector when working on templates/layouts

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#25998]
### User Story

Currently, when you open the dialog to select a container, it shows you all containers on all sites you have permission to in alphabetical order.

This is both messy and has the potential for accidentally selecting containers from other sites, especially if they share names.

As a user I want to see containers for the site I am working on, with the option to select other sites should I want a container from another site. 

### Acceptance Criteria

1. There should be a dropdown on the container selector for which sites containers you are looking at
2. The site you are currently on should be automatically selected when the dialog is opened

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Related ticket: https://dotcms.zendesk.com/agent/tickets/112729

**Comment by binarybasher** [comment]
To add, it would be *really* useful to have a Site setting that allows you to restrict all relations (containers, templates, content, related content...) to that site only.
This would avoid a user (who has access to multiple sites) from accidentally selecting items from different sites, which would have lead to all kinds of issues later.

**Comment by erickgonzalez** [comment]
The redesign of the Container Selector has been done, and now it's easier to identify the site where the container lives.

<img width="258" alt="Screenshot 2024-01-17 at 9 46 40 PM" src="https://github.com/dotCMS/core/assets/5278970/5c344797-ce7e-4321-b3cc-3261161c3580">

**Comment by hannahlaek-wt** [comment]
> The redesign of the Container Selector has been done, and now it's easier to identify the site where the container lives.

I just upgraded my dotCMS instance from 5.2.x to 23.01. I am seeing the new dropdown for Add Container in the Site -> Page Layout editor, but in my old instance all of our container selections were there but now I'm just seeing the containers that point to the application/ folder. I see the containers that we need when I go to make an Advanced Template (it looks like the old dropdown for selecting a container on the page layout editor) but it's not in the Designer Template. We really would like all our containers to show in the Site Layout editor but it's this new dropdown that's not showing all options. Is it something to do with this design change or updated Theme & Templating? Thanks
