### ISSUE TITLE
'accept' field  variable for File Base Types is not being enforced

### ISSUE THREAD

**Issue by TheGreatAlexander** [dotCMS/core#26037]
### Problem Statement

'accept' field  variable is not being enforced.

### Steps to Reproduce

WebDav to the demo.dotcms.com a PDF document and store anywhere you want:

<img width="705" alt="Uploaded PDF via Webdav" src="https://github.com/dotCMS/core/assets/1947524/6a6a9f33-3f19-46e8-872b-ef9ba7dfae33">

Then, you will not find it in the PDF Content Type (by the way there are images displaying in this content type.
<img width="1680" alt="PDF does not display in PDF File Type" src="https://github.com/dotCMS/core/assets/1947524/aba2ce87-a168-4845-81ef-40677634285b">

Finally, you can find the PDF in the File Content Type

<img width="1669" alt="PDF shows in File type" src="https://github.com/dotCMS/core/assets/1947524/da4261bf-c2b3-4589-9c22-c847f76fe2d1">

The same occurs with an image:

WebDav a folder called Media on the root directory with some images on it.

<img width="668" alt="webDav Folder" src="https://github.com/dotCMS/core/assets/1947524/11fc7cf1-f850-4fe9-b180-ef522b6b7663">

Then, they all get stored in the FILE content type, instead of the IMAGE content Type

<img width="1676" alt="displaying-the-items" src="https://github.com/dotCMS/core/assets/1947524/3525f386-0b45-460a-965e-f62097ee47d1">

### Acceptance Criteria

If we set to accept image/* variable for File Base Type Image, then anywhere I log the image it should be "stored" in the Image Content Type.

### dotCMS Version

 PLATFORM EDITION: 23.09.7 - SEPTEMBER 07, 2023

It also happens on 

 23.01.5 - AUGUST 16, 2023 -

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
This is not a bug, `accept` only applies when you upload from the backend.

**Comment by idx-venture** [comment]
Hi, @fmontes !  Should not this apply to files that you upload via WebDav?  We seldom upload any files via backend. 

May I suggest to extend this property as an enhancement to the field directive so it also applies via WebDav?

Have a great day!

**Comment by fmontes** [comment]
@idx-venture We are "deprecating" a little bit webdav in favor of dotCLI: https://www.dotcms.com/docs/latest/cli
