### ISSUE TITLE
Radio Button no longer accept 1/0 as valid when searching in ES

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26046]
### Parent Issue

https://github.com/dotCMS/core/issues/21944

### Problem Statement

When doing a query using 1/0 as a boolean value, it does not return anything.

### Steps to Reproduce

1- Create a Content Type with a Radio button.
2- Select True/False
3- Paste the following code in the value:
```
Yes|1
No|0
```
4- Create 2 contentlets, one with Yes and one with No.
5- Navigate to the Query Tool, and paste the following code (modify accordingly to the content type and field name):
```
+ContentType.radioButton:1
```
6- One content should return.

### Acceptance Criteria

1/0 should be accepted as valid values when doing ES searches.

### dotCMS Version

22.03.9, 23.01 LTS and demo.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, now we are getting results doing this query 


![Image](https://github.com/dotCMS/core/assets/2641437/636f1a2e-a6b9-4bb2-868e-5579e1cccb9c)
