### ISSUE TITLE
Edit Contentlet: Allow User Write Code

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26045]
### Parent Issue

#25445 

### Task

As a dotCMS user, I desire the capability to write code directly in the binary field.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

dotCMS users should have the ability to write code directly instead of being required to upload a file.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- **Fima Design**: https://www.figma.com/file/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?type=design&node-id=479%3A17595&mode=design&t=cOHbia6V2I3zTbcp-1

- **Prototype**: https://www.figma.com/proto/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?node-id=365-14264&scaling=scale-down&page-id=365%3A14229&starting-point-node-id=365%3A14264&mode=design&t=dBd4KhDyJmk0nuPC-1

![Binary Field Write Code](https://github.com/dotCMS/core/assets/72418962/b6663a88-0aae-4495-85ce-5f3a7a3c89c8)

### Needs
- Required file name field
- Configure the **syntax highlighting** of the Monaco editor based on the extension (file name) entered by the user.

### Assumptions
- When a user "saves" the code, we need to write the code out to a temp file using the tempAPI. Then, when we finally save the content, we reference the temp file for the binary field, which will get picked up.

**Comment by wezell** [comment]
@rjvelazco Rafa - the previous PR for writing the code should not be used here.  Instead, when you "save" the code, we need to write the code out to a temp file using the tempAPI.  Then, when we finally save the content, we reference the tempfile for the binary field, which will get picked up.

**Comment by rjvelazco** [comment]
@wezell Ticket updated, thank you, Will!
