### ISSUE TITLE
[UI] Add icons to Experiment' status

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26044]
### User Story

Add icons to Experiment' status

### Acceptance Criteria

Add icons to Experiment' status

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=1312%3A22690&mode=design&t=HBxruAJsaFZUhB0d-1

<img width="682" alt="Screenshot 2023-09-11 at 11 54 01 AM" src="https://github.com/dotCMS/core/assets/1909643/6f5c6ff1-b10e-486d-a398-88b4f865fcc5">

**Comment by oidacra** [comment]
Waiting the implementation of https://github.com/dotCMS/core/issues/26057 to use `p-chips` instead of `p-tag`

**Comment by dsilvam** [comment]
Passed Internal QA: All new icons showing in the Experiment config/result screens

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
