### ISSUE TITLE
Template title truncated when too long

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26059]
### Problem Statement

When a template title is sufficiently lengthy, it appears truncated in the application, making it challenging for users to identify and differentiate between templates based on their full titles.

### Steps to Reproduce

1. Open the application
2. Navigate to the section where templates are displayed or edited
3. Create or edit a template with an exceptionally long title
4. Observe that the title gets cutoff and doesn't display in its entirety

### Acceptance Criteria

emplate titles, regardless of length, should be displayed in full or be accommodated with a mechanism like ellipsis with a tooltip showing the full title upon hovering. (Maybe?)

### dotCMS Version

23.9.5

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
Closing as @fmontes marked won't fix.
