### ISSUE TITLE
Edit Contentlet: Replace Current Binary Field with webcomponent

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26053]
### Parent Issue

#26047 

### Task

As a dotCMS user, I have a requirement to utilize the new binary field functionality. To accomplish this, it is necessary to replace the existing `.jsp` binary field with the implementation of the new binary field.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- Should not break current functionality

### Assumptions & Initiation Needs

You can find the component in the `.jsp` file at the following location: [edit_field.jsp](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp).

In order to use the component in the `.jsp` world, it is necessary to build the corresponding `.js` file.

**Comment by fmontes** [comment]
Done in other place.
