### ISSUE TITLE
HTML Entity Codes Get Converted To The Symbol

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#26065]
### Problem Statement

When uploading pieces of code to dotCMS, any code that happens to match an HTML entity tag gets converted to the symbol.

### Steps to Reproduce

Upload a Javascript (.js) file asset containing the string "$curren" to a dotCMS site
Open the file in the built-in dotCMS editor
The file editor will display the "$curren" as a "¤" symbol

![Screenshot 2023-09-12 at 2 05 52 PM](https://github.com/dotCMS/core/assets/136110669/3c752c04-1361-4617-ba72-47592745f7f3)

### Acceptance Criteria

Don't evaluate HTML Entities in code uploaded to dotCMS.

### dotCMS Version

22.03.8

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113242

https://github.com/dotCMS/core/issues/18773
https://github.com/dotCMS/core/issues/16460

**Comment by fmontes** [comment]
Fixed with the new binary field.
