### ISSUE TITLE
Content Editor Inconsistent Behavior With Long Text Files

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#26064]
### Problem Statement

- When editing a text file with a long line of text that requires significant amounts of side scrolling in the built-in content editor of dotCMS, the location of the cursor does not correspond to the space where the text actually gets added.

- The end of the text file does not display in the content editor.

### Steps to Reproduce

Add a file asset to the site by uploading a very long single-line text file using the content page (you may use the attached js file as an example)
Open the file asset in dotCMS site browser
Scroll to the end of the file all the way to the right. You will see that the end of the text file is truncated.
![Screenshot 2023-09-12 at 1 49 48 PM](https://github.com/dotCMS/core/assets/136110669/edd7cc79-d1fc-40b6-ad27-1bc617b89b89)

Try adding text near the end of the file using the editor. You will see that the text does not get added at the position of the text cursor.
![Screenshot 2023-09-12 at 1 53 20 PM](https://github.com/dotCMS/core/assets/136110669/fe320e37-42ce-4a61-be2c-c3b06a70af09)

NOTE: When the text wrap feature is enabled in the editor, everything works as expected.

### Acceptance Criteria

Improve the text editor functionality when handling long text files

### dotCMS Version

22.03.8

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113242

**Comment by fmontes** [comment]
Fixed with the new binary field.
