### ISSUE TITLE
Eliminate the use of caching for storing analytics access tokens

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#26068]
### User Story
As a backend developer, I want to eliminate the use of caching for storing analytics access tokens. Instead, I propose using an in-memory object, most likely a Java ConcurrentMap, to manage these tokens. This change is essential for optimizing our analytics token management.

### Acceptance Criteria
- The codebase is modified to replace the caching mechanism with a Java ConcurrentMap for storing analytics access tokens.
- The access token renewal process is updated to fetch a new access token when it is null for existing clients, such as the CubeJsClient.
- The changes are thoroughly tested and verified to work as expected.
- Documentation is updated to reflect the new token management approach.

### dotCMS Version
master

### Proposed Objective
The objective of this task is to enhance the efficiency and reliability of analytics access token management by transitioning from caching to using a Java ConcurrentMap.

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_External links related to this task._

### Assumptions & Initiation Needs
- Access to the codebase and necessary development environments.
- Knowledge of the existing caching mechanism for analytics access tokens.
- Collaboration with other developers for code review and testing.
- Clear communication with the team to ensure a smooth transition.

### Quality Assurance Notes & Workarounds
_Quality assurance guidelines, potential issues, and workarounds._

### Sub-Tasks & Estimates
1. Modify code to replace caching with ConcurrentMap - 4 hours
2. Update access token renewal process - 4 hours
3. Testing and debugging - 4 hours

_Total estimated time: 12 hours_

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/26073

**Comment by victoralfaro-dotcms** [comment]
Steps the reproduce:
- Set up and start a analytics infrastructure
- Create an experiment to a page of your choose
- Create a variant and goal (Page reach)
- Start the experiment
- Go to the served pages and navigate to generate some analytics data to be collected, use several browsers to generate enough data.
- Go to the experiment page and verify that in fact the data was collected.

**Comment by dsilvam** [comment]
Passed Internal QA based on the feedback from @john-thomas-dotcms

**Comment by bryanboza** [comment]
Fixed, tested based on the provided steps and this is working. Tested on master // Docker // FF
