### ISSUE TITLE
Caret icons don't return to default state after clicking outside the dropdown

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26074]
### Parent Issue

PAGES

### Problem Statement

When interacting with a dropdown, the caret icons (indicating up/down state) do not revert to their default state if a user clicks outside the box to exit the dropdown.

### Steps to Reproduce

1. Open the application
2. Navigate to a section with a dropdown menu that has caret icons
3. Click on the dropdown to expand it and observe the change in the caret icon's direction
4. Without selecting an option, click outside the dropdown box to close it
5. Observe that the caret icon does not revert to its original state

### Acceptance Criteria

Upon exiting the dropdown by clicking outside, the caret icon should return to its default state, indicating the dropdown is closed.

### dotCMS Version

23.9.5

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

https://github.com/dotCMS/core/assets/129882031/b8329d30-da66-4b03-976f-a62b76f9eed6

**Comment by fmontes** [comment]
Not reproducible in the current version.
