### ISSUE TITLE
UX: Close the preview when you click outside of the modal 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26089]
### Parent Issue
Related to : #25813 

### Problem Statement

On edit mode, when you are editing a page and you click in the preview modal we are opening a modal with all the devices configuration that we have added to the system, but to close this we need to click again in the preview button. 

We need to be able to close at the moment that you click out of the modal, this is to make the navigation easier for the end user and avoid still navigating with this modal opened. 

![image](https://github.com/dotCMS/core/assets/2641437/187f22db-bf2f-4160-8815-bfe84850274e)

### Steps to Reproduce

- Login as admin
- Open a page 
- In edit mode click on the preview button 
- Click out of the modal to make sure we are closing it 

### Acceptance Criteria

- We need to automatically close if you do any click out of the modal. 
- We need to come back to edit mode and continue navigating normally 

### dotCMS Version

Tested on master // docker // Chrome 

### Proposed Objective

Quality Assurance

**Comment by nollymar** [comment]
**Internal QA:** Passed



https://github.com/dotCMS/core/assets/8741395/f078c34b-d571-4b0b-ae8b-328ee010516b

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_fad2bfd_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
