### ISSUE TITLE
Template Builder: Add Theme Information to the Template Listing Response

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26106]
### User Story
As a dotCMS user, I want to view theme information associated with a template in the template listing response, so that I can quickly and accurately review my templates.

### Acceptance Criteria
- The endpoint should be updated to include a new property with the full theme object.
- The property should be appended to the end of the returned response.
- The property should be labeled appropriately.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The endpoint for getting the list of templates should already be set up.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Update endpoint: 1 hour
- Add new property to response: 1 hour

**Comment by jcastro-dotcms** [comment]
## Internal QA: NOT NEEDED
This PR was used by https://github.com/dotCMS/core/issues/25860 to display the link to the Template's theme, and it's working as expected.

**Comment by jcastro-dotcms** [comment]
Postman test not needed.

**Comment by bryanboza** [comment]
Fixed, tested calling the API directly and now the theme information comes in the response.
