### ISSUE TITLE
EMA: Fix proxyEditModeURL Query Param for Edit Mode Anywhere

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26111]
### Problem Statement
In Edit Mode Anywhere the querey param `proxyEditModeURL` to override the EMA url is not working.

### Steps to Reproduce
1. Set EMA
2. Edit a page and add to the url `&proxyEditModeURL=https://other-server.com`
3. See how it doesn't override the URL

### Acceptance Criteria
- The query param `proxyEditModeURL` should override the EMA url
- The URL provided in the query param should be used instead of the default EMA url
- This needs to be fixed in the old plugin as well so outdated customers can use it.

### External Links 
None

### Assumptions & Initiation Needs
We need to make sure the query param works in both the plugin and in the core.

### Quality Assurance Notes & Workarounds
Testers need to verify that the query param correctly overrides the EMA url. As a workaround, testers can manually enter the URL instead of using the query param.

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected.  Now we are able to override the default EMA configuration, via a parameter in the navigation URL.
