### ISSUE TITLE
Suggested tags don't work when the content is located in a folder

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#26131]
### Problem Statement

For tag fields, dotCMS displays a list with suggested tags when the user types a word in the field. However, the list with suggestions is not working if the content being edited is located under a folder instead of being located in a site root.

### Steps to Reproduce

1. Create a new folder under a site.
2. Add a tag field and a site/folder field to a content type.
3. Create a new content from the content type from step 2 and select the folder created in step 1.
4. Type a word in the tag field.
5. The list with suggested tags doesn't show. Also, the request to the `/api/v1/tags` endpoint returns this error:
```
{
    "error": "dotcms.api.error.bad_request: Given site id `f80e96e153325b450b46d1df58a713fb` isn't valid."
}
```

### Acceptance Criteria

The suggestion list should work even if the content is located under a folder and not under a site root.

### dotCMS Version

23.08.16

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c77be3e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c77be3e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-09-28 at 8 59 49 AM](https://github.com/dotCMS/core/assets/129882031/64092989-5d04-4cd1-982e-93a5b0858baf)
