### ISSUE TITLE
Remove `:persona` from tag when doing ES

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26158]
### Parent Issue

https://github.com/dotCMS/core/issues/22872

### Problem Statement

When doing an ES query, if the content has a TAG field and one of the tags is a persona, we add `:persona` to the tag. This is confusing since we get rid of the `:persona` tags.

### Steps to Reproduce

1- Create a Content Type (**TestTags**) with a tag field (**tags**)
2- Create a persona (**personatag**)
3- Create a content of **TestTags** and add the **personatag**.
4- Go to the ES Query Portlet and run:
```
{
"query" :
{
"query_string" :
{
"query" : "+contentType:TestTags +TestTags.tags:(\"personatag\")"
}
},
"size":10
}
```

### Acceptance Criteria

Since we removed the `:persona` tags, this should not be appended.

### dotCMS Version

22.03+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/108233

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-09-29 at 1 56 13 PM](https://github.com/dotCMS/core/assets/129882031/7c11773c-d156-4b3d-9706-f02cc0563e68)

Query is still showing relation to personatag

**Comment by erickgonzalez** [comment]
@josemejias11 It's working in your screenshot. You can't see the `:persona` not longer happening.

Before:
<img width="1300" alt="Screenshot 2023-10-02 at 5 31 53 PM" src="https://github.com/dotCMS/core/assets/5278970/f33b9876-c091-41c7-b00a-9bcde7bc53c5">

After:
<img width="1157" alt="Screenshot 2023-10-02 at 5 34 26 PM" src="https://github.com/dotCMS/core/assets/5278970/54cdb56e-294c-41b8-8709-913567476aec">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
