### ISSUE TITLE
Remove Persona Icon from Tag Field

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26159]
### Parent Issue

https://github.com/dotCMS/core/issues/22872

### Problem Statement

There is no difference between persona and regular tags; there are just tags created in a different way and seems that showing the icon might confuse users, like in this case when you want to add the regular tag but it adds the persona one. So the icon on the tag won't make any difference since when doing an ES search, it looks for tag_name which is the same for both tags.

### Steps to Reproduce

1- Create a Tag named **test**
2- Create a persona named **test**
3- Create a Content Type with a Tag Field.
4- Create content and search for `test` the persona icon will be shown.

### Acceptance Criteria

Show the tag icon for all tags.

### dotCMS Version

22.03+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/108233

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

New tag content type does not show the correct icon yet.
![Screenshot 2023-09-28 at 12 00 58 PM](https://github.com/dotCMS/core/assets/129882031/03faf4dc-3cfb-41dc-8a63-0c70f70ece74)

**Comment by erickgonzalez** [comment]
@josemejias11 The icon is on the tag field inside the contentlet.

Before:
<img width="531" alt="Screenshot 2023-10-02 at 5 24 25 PM" src="https://github.com/dotCMS/core/assets/5278970/c179b27c-3297-46b1-9d13-e77a322ec798">

After:
<img width="550" alt="Screenshot 2023-10-02 at 5 25 36 PM" src="https://github.com/dotCMS/core/assets/5278970/162c132c-3751-4116-94ea-3b8635feed78">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-02 at 11 28 29 AM](https://github.com/dotCMS/core/assets/129882031/f7c13b4a-a29b-4d18-9d91-f917bca9c219)


thanks @erickgonzalez
