### ISSUE TITLE
User Automatically Logged In Despite Expired Access Token

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#26164]
### Parent Issue

https://github.com/dotCMS/core/issues/19094

### Problem Statement

When logging into dotCMS, the amount of time users stay logged in should depend on the json.web.token.days.max.age property. But what actually happens is that the user will stay logged in for up to a day if the user does not explicitly log out AND if the browser remains open.

This is a security problem, affecting all backend users.

### Steps to Reproduce

1. Log in as a back-end user
2. Close the browser tab, but do not log out, and do not close the browser
3. Navigate to dotCMS backend again later in the day
4. User will be logged in automatically

### Acceptance Criteria

Have the user session time out based on the value of json.web.token.days.max.age rather than persist for a day based on the cookie that is set when the user successfully logs in.

### dotCMS Version

22.03.3

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113258
https://github.com/dotCMS/core/issues/19094
https://dotcms.slack.com/archives/G01N0AU1NUC/p1694806839882959

**Comment by jcastro-dotcms** [comment]
Closing in favor of:

* https://github.com/dotCMS/core/issues/29698
