### ISSUE TITLE
Unable to view more than 20 items in a publishing queue bundle

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#26170]
### Problem Statement

When viewing a bundle with more than 20 items, only the first 20 items in the bundle are listed by default.
There is a "view all" button, but clicking on the "view all" button displays a blank area where the list should load.

### Steps to Reproduce

Log in to demo.dotcms.com/dotAdmin
Content > Search
Select 21 pieces of content > Available Workflow Actions > Add To Bundle
Site > Publishing Queue > Bundles
You will see the bundle you added display 20 of 21 pieces of content, along with a "View all" button
Open the browser developer tools
Click the "View all button"
Nothing will load, even though the page will display the text "Showing all the assets"
The browser console will show a 404 error on a Get request for the assets

### Acceptance Criteria

Have the "View all" button successfully display all the assets added to the bundle

### dotCMS Version

23.09.7

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113328
https://dotcms.slack.com/archives/G01N0AU1NUC/p1695070150308529

**Comment by haleyjhankins** [comment]
Hello, is there any update on this bug?

**Comment by AndreyDotcms** [comment]
Internal QA passed

<img width="385" alt="image" src="https://github.com/dotCMS/core/assets/127987858/20b79b5c-76d5-42d3-a55f-c7631f9358a2">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_68f4331**, Docker, macOS 13.0, FF v121.0.1
