### ISSUE TITLE
[UI] Prevent editing of Experiment/variants when page locked by another user

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#26187]
Experiments are considered part of the page properties.  It should not be possible for a user to edit the Experiment or any variants when the page is locked by another user.

1. Prevent a user from editing an Experiment if canLock() for the Page is false for that user.
    * In the Experiments configuration screen, disable all buttons and links that allow changing Experiments parameters.
    * For each disabled button, add a tooltip:
    `The Page is currently locked by another user.  You cannot edit the Experiment until the Page is unlocked.`

2. Prevent a user from editing a variant if canLock() for the Page is false for that user.
    * Display the "View" button next to the variant, instead of the "Edit" button.  (The same as we do now when the Experiment is running).

**Comment by hmoreras** [comment]
Other comments to take in consideration: 

> Normally in dotCMS, if another user has a lock, an admin can't just edit the content - the admin has to force unlock the content first.
So, in the scenario where admin has the page locked, admin2 shouldn't be able to edit the experiment (or any variants).  They should get the same message about the paged being locked as a limited user would get.
Basically, if the page is locked, we should treat all users the same - whether they're an admin or not.  An admin can then go steal the lock to make changes if they want, but that doesn't change how we treat them before they steal the lock.
