### ISSUE TITLE
[Containers]: Fix Container Content Types Variable List Showing Rows and Columns

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26180]
### Problem Statement
When creating or editing a container content type, the variable list is showing rows and columns, which should not happen.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/a59f8c74-7771-498f-a77a-e08daddc086e

### Acceptance Criteria
- Filter the list of variables to not include rows and/or columns
- Confirm with the old portlet

### External Links
N/A

### Assumptions & Initiation Needs
- Assume that the variable list should not show rows and columns when creating or editing a container content type
- No initiation needs

### Quality Assurance Notes & Workarounds
- Test by creating or editing a container content type to ensure that the variable list does not show rows and columns
- No workarounds available

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/assets/751424/11bde6b8-f062-4e6a-a013-dfa1b9e92d8f

**Comment by fmontes** [comment]
There is more work to be done in the variables and we have a ticket for that:  https://github.com/dotCMS/core/issues/26293

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-02 at 2 37 48 PM](https://github.com/dotCMS/core/assets/129882031/bd99590f-4866-4f6c-9d5a-cd40147a0481)
