### ISSUE TITLE
Whole "Hover" Needs to be a Link

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26199]
[![Screenshot_2023-09-20_18-29-48.png](https://mrkr.io/s/650b3a1cc650c249f47e0ca2/2)](https://mrkr.io/s/650b3a1cc650c249f47e0ca2/0)

https://github.com/dotCMS/core/assets/114953617/1f96a8fc-3ceb-4194-aac6-c830ef4bba53

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

When you hover over this area, the color changes and you get a hand cursor. But only the text is a link. The whole thing should be a link, not just the text and icon.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/650b3a1cc650c249f47e0ca5_97029cd18ba2d2d5?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
Let's fix this for all the links in the Preview Menu, not just the social. Devices have the same issue. Thanks!

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
