### ISSUE TITLE
[Containers] Fix Tabs and Rows Variables Height

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26197]
### User Story
As a dotCMS user, I want to be able to adjust the height of the tabs and rows in the containers portlet, so I can better organize my content.

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Fix tabs in containers, [see image](https://github.com/dotCMS/core/assets/751424/20d9cf88-0e2c-4d66-a265-8f92604cb452)
- [ ] Field rows should have padding of 0.25rem, [see image](https://github.com/dotCMS/core/assets/751424/2f71cf5e-e685-45c3-9bb6-4ea1539d34e0)
```

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/assets/751424/80f919cd-32f1-40dc-a12b-a103901961b3

**Comment by fmontes** [comment]
Still needs work

https://github.com/dotCMS/core/assets/751424/cf3a8a55-fcf7-4d7d-8a4d-54281cf0aab9

**Comment by fmontes** [comment]
Ready to QA

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_df4427b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
