### ISSUE TITLE
Preview Menu Placement is Off

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26195]
[![Screenshot_2023-09-20_17-42-04.png](https://mrkr.io/s/650b2eec41bac6db3aab0b0a/2)](https://mrkr.io/s/650b2eec41bac6db3aab0b0a/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

The Preview Menu was meant to open below the line, and also it's loading pretty far to the right.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/650b2eec41bac6db3aab0b0d_ed6cdbbdf4e1650e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.



![Image](https://github.com/dotCMS/core/assets/29883881/b9f59278-14f8-4571-968d-b6c8a9a219d9)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
