### ISSUE TITLE
Block Editor: Add a Toolbar Permanetly

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26212]
### User Story
As an editor, I want to be able to access a toolbar from the block editor, so I can quickly format text, insert images, and access other content.

### Acceptance Criteria
- The toolbar should be accessible from the block editor. 
- The toolbar should include options for formatting text, inserting images, and accessing other content.

### Proposed Objective
Core Features

### Proposed Priority 
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
We are going to add this toolbar with our default options:

<img width="1382" alt="image" src="https://github.com/dotCMS/core/assets/751424/c065ae52-1722-49fe-aebd-c150c45c6131">

### Assumptions & Initiation Needs
- All necessary components for the toolbar should be in place.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Create the toolbar - 8 hours
- Add formatting options - 4 hours
- Add image insertion options - 4 hours
- Add options for accessing other content - 4 hours

**Comment by rjvelazco** [comment]
Is this going to be `enabled`/`disabled` based on a `field variable`? @fmontes

**Comment by fmontes** [comment]
We are not doing this anymore for now, we revisit if we have to.
