### ISSUE TITLE
Tags are not being imported if header order is different on import file

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#2621]
I could not import tags If I interchange header order of import file.

For Instance If header order is Host_ID / Tag_Name then import fails; where as if it is Host_ID / Tag_Name its working fine.
http://screencast.com/t/eHMyzKDXBC

**Comment by shaydotcms** [comment]
This is the error in logs:
https://gist.github.com/shaydotcms/b0a36bc94c24a9c640e594e4a4166638

**Comment by wezell** [comment]
Nothing done on this
