### ISSUE TITLE
Toolbar: Error when the page is locked by the admin user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26221]
### Problem Statement

When you have a page locked by the Admin user and you are logged in as another admin, the tollbar notification appears as expected, but the switch does not. 

![image](https://github.com/dotCMS/core/assets/2641437/86b79946-4497-4c9a-94e2-c992b9720327)

The switch looks like it unlocked, then you need to lock and then unlock it again. 

### Steps to Reproduce

- Login as admin 
- Open any page and lock it 
- Logout 
- Login as another admin user 
- Open the page and try to unlock 

### Acceptance Criteria

The switch should appear locked and you need to be able to unlock it without problems. 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
Internal QA: Passed

When the page is locked, other users will see the lock: 



![Image](https://github.com/dotCMS/core/assets/8741395/0ea794d7-b6a6-4637-8bbf-3963603db012)



When the page is unlocked, this is how they see it: 


![Image](https://github.com/dotCMS/core/assets/8741395/b345e988-d6ec-4a23-a930-6845be7e8567)

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_5dfa55c8_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Blocked by card https://github.com/dotCMS/core/issues/26585

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8a0c462_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
