### ISSUE TITLE
Prevent tag chips from jumping

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26235]
### Parent Issue

UI

### Problem Statement

The tag field chips jump when you hover over them. 

### Steps to Reproduce

hover over the tag field

https://github.com/dotCMS/core/assets/934364/2caf2aad-749b-4aff-9a9b-14ca6a82f503

### Acceptance Criteria

should not jump

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by fmontes** [comment]
We need to update the source SCSS to have this code.

**Comment by bryanboza** [comment]
Fixed, tested on master and now this is not happening anymore.
