### ISSUE TITLE
[UI] Implement a trim input text directive

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26231]
### Parent Issue

#25716

### Problem Statement

Not allow emitting a text with white spaces at the beginning or at the end of a text input

### Steps to Reproduce

- Go to Experiment
- Select a Draft Experiment (or create a new one)
- Add a new variant
- Edit the name of the variant
- add spaces to the name at the beginning
- save the new name

### Acceptance Criteria

- Do Not allow input with spaces at the beginning or the end (Trim)
- Add to name when you add an Experiment
- Add to name when you add a Variant
- Add to name when you name a Goal
- Add to DotExperimentsInlineEditTextComponent when you edit inline a description of the Experiment or rename a Variant

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by bryanboza** [comment]
Fixed, now we trimmall the inputs mentioned in the comment. 

Tested on maste // Docker // FF
