### ISSUE TITLE
Fix Page Version with different Templates.postman_collection.json test

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26255]
### Task

The test is currently failing in master for this reason:
![Screenshot 2023-09-25 at 11 45 42 AM](https://github.com/dotCMS/core/assets/8741395/57185e96-544a-4926-9913-f0f23267fc08)

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
@jcastro-dotcms welcome :)

**Comment by john-thomas-dotcms** [comment]
This may be fixed already.  Please check

**Comment by dsilvam** [comment]
This test is passing. Closing it.
