### ISSUE TITLE
Read More Section Styling

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26262]
[![Screenshot_2023-09-25_18-46-45.png](https://mrkr.io/s/6511d595b53e1a1d741ccfa9/2)](https://mrkr.io/s/6511d595b53e1a1d741ccfa9/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Need to make sure the section header matches the designs.

### Acceptance Criteria

Should match designs, and have a blue background.

<img width="752" alt="image" src="https://github.com/dotCMS/core/assets/114953617/e869b6a5-9394-4ff5-8dcc-cdc3a2d884e8">

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-7119&mode=design&t=WWlVjRD0uq9HQPy8-0

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6511d595b53e1a1d741ccfac_cf5522c1f181dcfb?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1172</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.

As shown below:

![Image](https://github.com/dotCMS/core/assets/29883881/c7e92736-4c1e-46a5-a42d-58aa339b3a1e)

**Comment by bryanboza** [comment]
Fixed, tested on the last master edition and now the read more section looks better 


![Image](https://github.com/dotCMS/core/assets/2641437/bdbc55ef-03c2-4952-bfcb-cce225e18360)
