### ISSUE TITLE
Use Copy from Desigsn on Section Headers

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26261]
[![Screenshot_2023-09-25_18-43-20.png](https://mrkr.io/s/6511d4c80aca614476004a86/2)](https://mrkr.io/s/6511d4c80aca614476004a86/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

We need these headers to match the designs.

So like "Title" and not "Og:title" -- the messages can still call out the various "OG" Tags but for the section headers we can just say "Title"

<img width="756" alt="image" src="https://github.com/dotCMS/core/assets/114953617/76fd41f8-0681-4e21-8cf7-c4cb4f743e0c">

Need to make this change across all the cards.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-7119&mode=design&t=WWlVjRD0uq9HQPy8-0

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6511d4c80aca614476004a89_c30eec7df3cd1bfa?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1172</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.

![Screenshot 2023-09-28 at 16 12 25](https://github.com/dotCMS/core/assets/29883881/0a5a2f2a-afd7-402d-ac7b-fb2a538cedb4)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
