### ISSUE TITLE
[Containers] : Add New Portlet for New Containers UI

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26267]
### User Story
As an editor, I want to be able to add a new portlet for the new containers UI, so I can have old and new working together.

### Acceptance Criteria
- Assign the new UI to the current portlet in the XML 
- Create a new portlet in the XML and assign the old UI, call it Containers Legacy
- Check if we need to update the starters or if the new UI shows as it is right now

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Understand the differences between the old and new portlet

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by fmontes** [comment]
Note to QA:

Test the whole containers portlet, everything in it.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_eb391b4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

Looking good. Added cards https://github.com/dotCMS/core/issues/26595 https://github.com/dotCMS/core/issues/26590 https://github.com/dotCMS/core/issues/26591 

Any other added issue will be linked here as well.
