### ISSUE TITLE
Update Spacing on "External Link" Icons

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26260]
[![Screenshot_2023-09-25_18-36-31.png](https://mrkr.io/s/6511d32f897063d5cc7c0466/2)](https://mrkr.io/s/6511d32f897063d5cc7c0466/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Update Spacing on "External Link" Icons

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-7119&mode=design&t=WWlVjRD0uq9HQPy8-0

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6511d32f897063d5cc7c046b_f7d0202861f3fee9?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1172</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.

![Image](https://github.com/dotCMS/core/assets/29883881/0bcd4f6b-f5f8-4274-b6a1-58a6d1cf56ac)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3c41b76_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-19 at 11 56 17 AM](https://github.com/dotCMS/core/assets/129882031/f329ec5f-e5fd-481b-89e5-c560d9d8cd1a)
