### ISSUE TITLE
Losing Experiments Data when Moving Page to Different Path

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26272]
### Problem Statement

When a page is moved to a different path, the experiment data associated with that page is lost. This means that any ongoing or completed experiments on the page cannot be accessed or analyzed, causing a loss of valuable data and hindering the ability to make data-driven decisions for optimization.

### Steps to Reproduce

- Select a page that is currently involved in an experiment.
- Move the page to a different path or location 
- Attempt to access the experiment data for the moved page.
- Notice that the experiment data is no longer available or accessible.

### Acceptance Criteria

- When a page is moved to a different path, the experiment data associated with the page should not be lost.
- The experiment data should remain intact and accessible after the page has been moved.
- The link between the page and its associated experiments should be maintained, even after the page's location has changed.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
It was fixed with thus changes https://github.com/dotCMS/core/commit/354ec8b41314d9f30231e056c8e16072d02a5ab6

**Comment by bryanboza** [comment]
Fixed, now we are able to move the page without lose the experiment data 

Tested on master // Docker // FF
