### ISSUE TITLE
/api/v1/browser endpoint only returns up to 300 results

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#26276]
### Problem Statement

When querying the api/v1/browser endpoint, the results returned caps at 300 files, even if the maxResults parameter sent in the request body is greater than 300.

### Steps to Reproduce

Upload 500 files to a dotCMS folder
Send a request to the v1/browser endpoint with the following request body:

{
  "hostFolderId": "INSERT_FOLDER_ID",
  "maxResults": 500,
  "showWorking": true,
  "showArchived": true,
  "showFolders": true,
  "showFiles": true,
  "showPages": false,
  "sortByDesc": true,
  "showLinks": false,
  "showDotAssets": true,
  "languageId": 1
}

There will only be 300 results in the returned json

### Acceptance Criteria

Allow the /api/v1/browser endpoint to return more than 300 results

### dotCMS Version

23.01.6

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113402
https://dotcms.slack.com/archives/C028Z3R2D/p1695668949628129

**Comment by erickgonzalez** [comment]
This is not a bug we have the following property to prevent performance issues https://github.com/dotCMS/core/blob/ab066307c027e0620f7694b910b332b494f5a7fb/dotCMS/src/main/java/com/dotcms/browser/BrowserQuery.java#L44
