### ISSUE TITLE
[UI] Text in experiment data results needs be aligned 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26271]
### Problem Statement

The Experiment Data Results text in the UI is not aligned correctly, causing it to appear misaligned. This negatively impacts the user experience and can lead to confusion and misunderstandings.
![image](https://github.com/dotCMS/core/assets/2641437/5b50cce4-5807-4d91-9f70-adbb34266333)

### Steps to Reproduce

Navigate to the Experiment Data Results section in the UI.
Observe that the text is not aligned properly.

### Acceptance Criteria

- The Experiment Data Results text is aligned correctly in the UI.
- The alignment is consistent across different devices and screen sizes.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
Looks like the initial alignment issue was afixed before, but we are reducing the amount of decimals to avoid alignment issues and to be consistent with the summary table. 

Before
<img width="217" alt="Original 18 181818" src="https://github.com/dotCMS/core/assets/31667212/bea3f8ee-c5e7-4452-b140-c5697cc7367c">

<img width="278" alt="Pasted Graphic 4" src="https://github.com/dotCMS/core/assets/31667212/95018793-2370-4d25-a8c8-732ff76e2f96">

<img width="304" alt="14 000000000000002" src="https://github.com/dotCMS/core/assets/31667212/77466ea9-b2e9-44e8-b83e-12cc359bd57c">


After 

<img width="242" alt="Original 18 18" src="https://github.com/dotCMS/core/assets/31667212/463a9d9e-cfa0-4dde-8c4b-6d20fccd2213">

<img width="224" alt="image" src="https://github.com/dotCMS/core/assets/31667212/50d4ecf9-a4b6-42ae-8b86-7885f26caa56">

<img width="235" alt="Pasted Graphic 3" src="https://github.com/dotCMS/core/assets/31667212/0b5300d1-9d08-48e7-9066-7bdcb1550c23">

**Comment by oidacra** [comment]
IQA Passed: Names of the variant trimmed.
<img width="484" alt="Screenshot 2023-11-14 at 3 58 02 PM" src="https://github.com/dotCMS/core/assets/1909643/229acc21-ea60-4652-99c5-2ddddf39b1f2">

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF 


![Image](https://github.com/dotCMS/core/assets/2641437/fc27fa18-c349-4e12-89c3-cdd0479e6069)

Now it looks aligned
