### ISSUE TITLE
Experiments not Considering Redirection from Vanity URLs

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26273]
### Problem Statement

Currently, experiments in dotCMS are not taking into consideration the redirection from vanity URLs. This means that if a user accesses a page through a vanity URL, any experiments associated with that page will not be applied. This can lead to inconsistent user experiences and inaccurate experiment results."
Here is the configuration used to test:
![image](https://github.com/dotCMS/core/assets/2641437/4f75cbed-f973-4573-bb66-49de0889025c)

### Steps to Reproduce

- Set up an experiment for a specific page 
- Create a vanity URL that redirects to the target page of the experiment.
- Access the target page through the vanity URL.
- Observe that the experiment is not applied to the page.

### Acceptance Criteria

- When a page is accessed through a vanity URL, any experiments associated with that page should be applied.
- Users accessing the page through the vanity URL should experience the variations defined in the experiments.
- Experiment results should accurately reflect the behavior of the experiments for users accessing the page through vanity URLs.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

- QA should verify that experiments are correctly applied when accessing pages through vanity URLs.
- Workarounds may include manually accessing the page using the actual page URL instead of the vanity URL to ensure that experiments are applied properly.

**Comment by john-thomas-dotcms** [comment]
Let's test if this problem exists when the Vanity URL uses a 301 or 302 redirection (instead of a 200 forward).  If it works with 301 or 302, then this is an outside case, and we can potentially address it later.

**Comment by bryanboza** [comment]
Fixed, tested using a vanity URL and now this is working as expected 

![Image](https://github.com/dotCMS/core/assets/2641437/0a44c4a1-64f2-4133-903e-6f710db89650)

Tested on master // Docker // FF

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/26803

**Comment by erickgonzalez** [comment]
Previous commits were a typo those were actually for #26683
