### ISSUE TITLE
Relationship throwing error when the child content is a copy of original child content

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26283]
### Problem Statement

The issue arises when a hero content instance that has already been linked to a page is cloned for creating a new hero instance, and that new instance is subsequently tried to be associated with a page. What follows is an error message saying there has been a violation of the field's relationship cardinality, even though the new (cloned) hero instance hasn't been associated with any pages yet.

What seems to be happening is that the action of cloning an existing hero instance associated with a page seems to affect the page that the original hero is associated with, making it have two associations: one with the original hero instance and another one with its clone, preventing the cloned version from being mapped to another page since doing so makes it violate the 1:1 cardinality rule of the relationship field.

### Steps to Reproduce

1. Create a content type (Such as page asset)(Example: Pretender Hero) having a one-on-one relationship field with another content type (Hero)
2. Create content Test Page 1: Relate Hero One
3. Copy Hero One and Create Here Two (Copy of One)
4. Now create Test page 2 and try to Relate Hero Two (Throwing an error)

Content A is related to Page A
When copying content A (let’s call it Content B) and relating it to Page B throws an error.

<img width="976" alt="Screenshot 2023-09-25 at 4 55 31 PM" src="https://github.com/dotCMS/core/assets/139247809/dc3ea1e3-7545-4b86-8936-77f0baa38587">

### Acceptance Criteria

The copy of the content should work fine.
New Content shouldn't have any relationship, and old content should keep the relationship (this only applies to one-to-one, many-to-one relationships)

### dotCMS Version

5.3.8
23.09.7

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113330

https://dotcms.slack.com/archives/G01N0AU1NUC/p1695677834584179

**Comment by erickgonzalez** [comment]
Working as it should, now original content keeps the relationship, and copied content doesn't have any relationship,.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_f68e6f2**, Docker, macOS 13.0, FF v124.0.2
