### ISSUE TITLE
Edit Mode: It is not possible to open the Edit tab when using the old toolbar

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26297]
### Problem Statement

When the flag `DOT_FEATURE_FLAG_SEO_IMPROVEMENTS` is off, there is no way to open the Edit tab. When I click on it, it always switches to the Preview tab. I've included a video for more details.

https://github.com/dotCMS/core/assets/8741395/f086b639-90a4-432a-8b58-64a4ddc65ef2

### Steps to Reproduce

1. Using the old toolbar (just turn off the flag `DOT_FEATURE_FLAG_SEO_IMPROVEMENTS`)
2. Open a page in Edit Mode.
3. Click on the Edit tab, you will see that it switches back to Preview.

### Acceptance Criteria

I should be able to open the Edit tab using the old toolbar

### dotCMS Version

Docker image used: `master_5c27e3e_SNAPSHOT`

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by nollymar** [comment]
**Internal QA:** Passed


https://github.com/dotCMS/core/assets/8741395/d122a13c-1fd0-4c07-882b-0ae26bbc00b0

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-09-28 at 9 19 50 AM](https://github.com/dotCMS/core/assets/129882031/14e146d9-bc74-4c4e-b132-ea6414d8cf2a)
