### ISSUE TITLE
Build docker image in release candidate process

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#26296]
### User Story
As a dev-ops engineer, I want to add a Github Action step to the existing 'Release Candidate' Github workflow to build and publish the corresponding Docker image.

### Acceptance Criteria
1. The Github Action step must be added to the 'Release Candidate' workflow.
2. The step should build the Docker image from the source code.
3. The Docker image should be tagged appropriately, including version information.
4. The Docker image should be pushed to a Docker registry or container repository.
5. The workflow should trigger automatically when changes are pushed to the repository.

### dotCMS Version
master

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### External Links
- [Link to 'Release Candidate' Github workflow](to_define)
- [Link to Docker registry/repository](to_define)

### Assumptions & Initiation Needs
- Access to the Github repository and workflow configuration.
- Proper authentication and permissions for Docker registry/repository.

**Comment by bryanboza** [comment]
Fixed, tested  with the release process and now it is working as expected
