### ISSUE TITLE
CLI: Create a GHA that invokes the CLI

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26300]
### Task

The action will generally be triggered by a workflow that is fired when a new commit/merge happens in a branch.

The action will take env variables to configure it. It should be: 
- The target dotCMS env
- dotCMS API Token, provided as a github secret
- any cli config flags

Besides, destructive actions should be supported. For example:  folder, content type, file deletions.

As we add new features to the CLI, we should also make sure our github action will support them.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
How to test this.
Here's a  public GitHub Repo that uses these actions
https://github.com/fabrizzio-dotCMS/dot-cli-push-2.0

QA could be done on this repo or installing these scripts in a brand new repo 

The scrips need to be placed under a folder [.github/workflows](https://github.com/fabrizzio-dotCMS/dot-cli-push-2.0/tree/main/.github/workflows) 


The CLI needs to know basically 2 things

The target instance URL (This should be defined as a var)

![Screenshot 2023-10-04 at 11 01 29](https://github.com/dotCMS/core/assets/37148755/6c8abec7-e5cb-4e35-a3f9-33016b9618dd)

A Token that grants access to the instance  (This should be defined as a secret)

![Screenshot 2023-10-04 at 11 01 12](https://github.com/dotCMS/core/assets/37148755/2aca5a1d-b5e0-42a3-a601-69af4d566d81)

The following permission is required in order for the workspace to be persisted

![Screenshot 2023-10-04 at 11 03 41](https://github.com/dotCMS/core/assets/37148755/537cfd39-b28f-4d63-b649-eedb90a72807)

**Comment by nollymar** [comment]
**New requirement:** We need to support `--remove` flags for content types, sites and languages. Currently, it is only supported for files

**Comment by dcolina** [comment]
Internal QA: PASSED.
