### ISSUE TITLE
Validation required for import tags

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#2631]
When I click on import with out choosing any file, It's saying "Tags were successfully imported".

http://screencast.com/t/gaGnLCwh8nRi

**Comment by shaydotcms** [comment]
Unable to reproduce on **master_4.0**

![image](https://cloud.githubusercontent.com/assets/8741846/23620892/3d91e994-025e-11e7-8c14-8b9af9e08e9d.png)
