### ISSUE TITLE
Edit embedded content-let's through Block Editor field

### ISSUE THREAD

**Issue by binarybasher** [dotCMS/core#26316]
### User Story

Currently on v23.1.6 LTS

Opening a content-let with a block editor field, you cannot click through into an embedded content-let (inside the block editor).

This means you need to search for the embedded content-let from the content search screen.

It makes editing those embedded content-let's really clunky and awkward (think tab, accordion features that are using block editor to manage content).

### Acceptance Criteria

Opening a content-let with a block editor field that has embedded content-let's, you can click through them to open in edit mode (as you would related content-let's).

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by binarybasher** [comment]
Hi,

Just following-up on this as content editors are having a really hard time editing content-lets that were embedded into the block editor fields.

Unfortunately, to make matters worse, the titles of the content-lets are often very long and are truncated in the block editor view.

Thank you,
Ryan

**Comment by wezell** [comment]
The behavior we are looking for can be enabled by setting an object to local storage and then navigating to the new/existing edit content window

```
let returnValue = { inode: $currentInode, title: $currentContentTitle.replace("\"", "") };
localStorage.setItem("dotcms.relationships.relationshipReturnValue",  JSON.stringify(returnValue));
```

**Comment by john-thomas-dotcms** [comment]
When working on this issue, please also check https://github.com/dotCMS/core/issues/27824.  27824 is lower priority, but if it's low-hanging fruit to add that while implementing this one, please pull it into the sprint to do that.

**Comment by oidacra** [comment]
Implemented for JSP Only.

**Comment by dsilvam** [comment]
Failed Internal QA: 
Found an issue when editing the embedded content. 
Steps to reproduce: 

1. Edit an existing blog
2. Embed a new piece of content
3. Save & publish the parent content
4. Edit the embedded content by clicking on the pencil icon but make no changes, just click on return to the content. 

Bug: uou'll see the embedded content is no longer present in the block editor field.

**Comment by oidacra** [comment]
Bug handled by https://github.com/dotCMS/core/issues/28699

**Comment by dsilvam** [comment]
Passing the QA of the work that was scoped for this issue. There's a remaining work pending for it to function properly but it's an old issue and not simple to fix. Captured here https://github.com/dotCMS/core/issues/28699/.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_0f45973**, Docker, macOS 14.5, FF v126.0.1

After adding a contentlet to an existing blog entrie, save it and publish it. The blog entrie disappears from the portlet.

https://github.com/dotCMS/core/assets/129882031/e617a8d2-1f34-409f-87de-f865ec02935f

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_6d0d4a5**, Docker, macOS 14.5, FF v126.0.1

**Comment by erickgonzalez** [comment]
Since this is a new functionality, it will be only backported to 24.04 LTS.

**Comment by josemejias11** [comment]
**QA Comment**

The issues found and reported on this previous comment https://github.com/dotCMS/core/issues/26316#issuecomment-2161166806 was fixed on a different PR. Is not reproducible anymore.
