### ISSUE TITLE
Misalignment of CTA Icons

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26327]
### Problem Statement

Call-to-Action (CTA) icons  of the application are misaligned.
### Steps to Reproduce

1. Open the application
2. Navigate to any section where CTA icons are present
3. Observe the alignment of the icons relative to other UI elements

### Acceptance Criteria

All CTA icons should be properly aligned with adjacent text, buttons, and other UI elements, maintaining visual harmony and clear interaction cues.

### dotCMS Version

23.9.5

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### Quality Assurance Notes & Workarounds

tested using Firefox

![271102475-b4cde97a-c4ba-499e-a6b2-044181825299](https://github.com/dotCMS/core/assets/129882031/264a4a19-3000-406a-8c3d-2f3b50f91f60)

**Comment by oidacra** [comment]
Removed the icon of material, and used the primeng icon

**Comment by nicobytes** [comment]
IQA with **trunk_477606b**

Chrome

![Image](https://github.com/user-attachments/assets/f4f0de05-a0fa-4182-9709-df163f5c70a0)

Firefox

![Image](https://github.com/user-attachments/assets/a6443ecc-b5c7-4c94-9ccc-b96227278cd4)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_477606b**, Docker, macOS 14.5, FF v126.0.1
