### ISSUE TITLE
Edit Content: Lack of mimeType and File Extension in Response when Uploading File by URL via Temp API 

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26340]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

When uploading a file by URL using the temp API, the response doesn't include the `mimeType` or the file extension. We rely on this information for two purposes:

1. **Show user preview**: We use the file extension to provide users with a preview of the uploaded file.
2. **Validate accepted files**: We validate whether the file is of an accepted type by checking the `mimeType`.

To upload an image by URL, you can use the following request. After making the request, you will be able to see the backend response:

```bash
curl --location 'https://demo.dotcms.com/api/v1/temp/byUrl' \
--header 'Origin: https://demo.dotcms.com/' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=848F60EDEF9BA94FBEC1802B3D242BAC; access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3MTgxNjdjOC1jN2ZmLTQyYzAtOWY1MC1mMjdlMjI4NWU2ZTMiLCJ4bW9kIjoxNjk2MDExNjQwODg5LCJzdWIiOiJkb3RjbXMub3JnLjEiLCJpYXQiOjE2OTYwMTE2NDAsImlzcyI6ImY2MmJhMDJhM2UiLCJleHAiOjE2OTYwOTgwNDB9.EjEFk0Q-BTVr1pkjfXVTDMZkbKV01EkZWlMvWkTX5bc' \
--data '{
    "remoteUrl":"https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80"
}'
```

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

1. If the external URL provided in the request body does not include the file extension, we should still be able to retrieve the `mimeType` and determine the file extension.

**Desired Response** 

```bash
{
    "tempFiles": [
        {
            "fileName": "photo-1575936123452-b67c3203c357.png",
            "folder": "",
            "id": "temp_0e2c70590a",
            "image": false,
            "length": 99768,
            "mimeType": "image/png",
            "referenceUrl": "/dA/temp_0e2c70590a/tmp/photo-1575936123452-b67c3203c357",
            "thumbnailUrl": null
        }
    ]
}
```

**Current Response** 

```bash
{
    "tempFiles": [
        {
            "fileName": "photo-1575936123452-b67c3203c357",
            "folder": "",
            "id": "temp_0e2c70590a",
            "image": false,
            "length": 99768,
            "mimeType": "unknown",
            "referenceUrl": "/dA/temp_0e2c70590a/tmp/photo-1575936123452-b67c3203c357",
            "thumbnailUrl": null
        }
    ]
}
```

### Assumptions & Initiation Needs

It would be a nice addition to have the backend be able to receive an array of accepted extensions/mime types. With this enhancement, the backend could validate if the external source is included in the array of accepted types.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `Master`


https://github.com/dotCMS/core/assets/72418962/3cccabe0-2be5-4b49-b87c-9079e003969a

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_6a4a847_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
