### ISSUE TITLE
Can't assign folder to a Role in Roles & Tools screen

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#26342]
### Problem Statement

A system error message appears when adding a folder to Role in the "Roles & Tools" screen.

### Steps to Reproduce

1.- Go to Settings -> Roles & Tools.
2.- Select a Role.
3.- Go to the Permissions tab.
4.- Add a folder.

![Screenshot 2023-10-03 at 8 13 55 AM](https://github.com/dotCMS/core/assets/12899960/1681fc7d-03df-4ffd-863d-ad886a8a49a2)

https://github.com/dotCMS/core/assets/12899960/729467a1-dc1e-463c-8be2-2d3c3b67b83d

### Acceptance Criteria

The user should be able to add folder in the permissions tab.

### dotCMS Version

Version: 22.03.10 

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CSHTYUR7H/p1696274710255499

https://dotcms.zendesk.com/agent/tickets/113468

**Comment by erickgonzalez** [comment]
Not Reproducible in current LTS (23.01 and 23.10)
