### ISSUE TITLE
Rules do not fire on 'Show Preview'

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#26341]
### Problem Statement

`Show Preview` (soon to be renamed to Open in New Tab) shows a front-end version of the page. Even though the user is authenticated, this version should fire rules to be as close to 'Live' as possible. 

### Steps to Reproduce

1. Create a rule that you know will fire on every page/request, for example:
![image](https://github.com/dotCMS/core/assets/78741732/1dc6e0d0-85d0-42fd-b3db-1d9452a6ef65)
2. Go to the index page and click show preview. 
3. Open chrome dev tools and refresh the page. 
4. Check the response headers, you will see it did not add the test header
5. Open the index page in incognito with chrome dev tools open, you will see the test response header

### Acceptance Criteria

1. Show Preview (or any loading of pages outside of the admin portal, even when authed) should show the page as delivered to a front-end user

### dotCMS Version

23.01, master

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Related ticket: https://dotcms.zendesk.com/agent/tickets/113448

**Comment by dsolistorres** [comment]
This is working now for rules evaluated on every request, but rules evaluated on every page are not triggered yet when the page is loaded in preview mode.

**Comment by dsolistorres** [comment]
Internal QA Approved:
- This works now for rules evaluated on every request and on every page.
