### ISSUE TITLE
Content field variables added from container screen are incorrect

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26348]
### Problem Statement

The dotContentMap is not working on containers, if you create a container using the following piece of code 
```
<h1>$!{dotContentMap.title}</h1>
<hr />
<p>imageImageWidth: $!{dotContentMap.imageImageWidth}</p>
#if ($UtilMethods.isSet(${imageImageURI})) 
   <p>There should be an image here</p>
   <pre>
       <code>
           $!{dotContentMap}
       </code>
   </pre>
   <img src="$!{dotContentMap.imageImageURI}" alt="$!{dotContentMap.imageImageTitle}"  /> 
#end 
<hr />
#if ($UtilMethods.isSet(${binaryBinaryFileURI})) 
<p>binaryBinaryFileURI:</p>
   <a href="$!{dotContentMap.binaryBinaryFileURI}?force_download=1&filename=$!{dotContentMap.binaryBinaryFileTitle}">$!{dotContentMap.binaryBinaryFileTitle}</a> 
#end 
<hr />

${binaryBinaryFileURI}
```

Then you use this container in a template, this is not showing anything after you add a new pice of content 

### Steps to Reproduce

- Login as admin
- Create a new content type with 3 fields (TEXT: title BINARY: bin IMAGE: img)
- Create a container 
- Add the 3 variables of the fields and use the provided code 
- Create a new template using the container 
- Create a new page using the template 
- Add a new piece of content 

### Acceptance Criteria

- We need to show the information requested in the container 

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed Internal QA. 
In order to the the URI of the image you actually need to reference it like this:
```<img src="$!{dotContentMap.img.rawUri}" alt="$!{dotContentMap.imgImageTitle}"  /> ```

**Comment by bryanboza** [comment]
We still getting some problems here with the generated code: 

https://github.com/dotCMS/core/assets/2641437/834b09f2-35d6-4a57-8daa-cf7abe3eef29

**Comment by bryanboza** [comment]
Seems that this behavior is expected when you use a dotAsset file. Tested on a fileAsset and this is working now
![image](https://github.com/dotCMS/core/assets/2641437/24ca40e0-8ec0-48cc-8a9b-17489fbfb4c2)
