### ISSUE TITLE
Template Builder: Change auto publish to auto save

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26349]
### Problem Statement
In the dotCMS Template Builder, the user can only auto publish changes and this can cause issues. 

### Steps to Reproduce
1. Log into the dotCMS Template Builder.
2. Make changes to an existing template.
3. Notice that auto publish is the only option to save the changes.

### Acceptance Criteria
Change the request from auto publish to auto save.

### External Links
N/A

### Assumptions & Initiation Needs
- Assume the user has access to the dotCMS Template Builder.
- Initiation requires the development team to make the necessary coding changes.

### Quality Assurance Notes & Workarounds
- Quality Assurance team should test the changes in the Template Builder to ensure the auto save function works properly.
- Workaround is to use the auto publish function, but be aware of any potential issues.

**Comment by fmontes** [comment]
Note to QA: we just change the publish to save... nothing added to the UI, we need a bigger discussion to improve the UI.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. Pending the UI improvements

**Comment by erickgonzalez** [comment]
Only for 23.10 LTS
