### ISSUE TITLE
Make default lookback window match default duration

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#26345]
## Problem

When the lookback window is shorter than the duration of the Experiment, the same user may end up seeing different variants of the page during the run of a single Experiment.

The current default lookback window is 10 days.  But the current default duration is 14 days.  So, our current defaults make it likely that some users will see different variants during the same run of an Experiment.  This is not ideal.

## Solution

By default, set the lookback window to the default duration.  The lookback window could still be overridden by explicitly setting the `EXPERIMENTS_LOOKBACK_WINDOW` property, but otherwise it would automatically sync with the default duration.

Note: An ideal solution would set the default lookback window separately for each Experiment, to match the Experiment duration.  But we can meet the 90-95% case with the solution outlined above.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/26346
