### ISSUE TITLE
SEO - Small UX fixes

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26359]
[![Screenshot_2023-10-04_16-10-30.png](https://mrkr.io/s/651d8e769fec384b99d608f5/2)](https://mrkr.io/s/651d8e769fec384b99d608f5/0)

### Parent Issue
- Red: The icons are aligned in the center of the item

- Purple: We are missing a scroll bar

- Blue: We are missing a divider line between the default and user devices.

- Green: The Twitter Title changed.

### Acceptance Criteria

- Red: The icons should be aligned with the title of each item, please make sure that even the Social Media titles are aligned (Please also check if the size of the icon is the same as the design)

- Purple: Add a scrollbar in each of the device columns.

- Blue: Add a divider line between the default and user devices.

- Green: The Twitter should be changed to:
X (Formerly Twitter)

### Sub-Tasks & Estimates

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Ffrench-polynesia-everything-you-need-to-know&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&device_inode=](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Ffrench-polynesia-everything-you-need-to-know&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&device_inode=)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/651d8e769fec384b99d608f8_14e8a68587a616d2?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 117.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1512 x 982</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1512 x 913</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: Needs work.

@manuelrojas I am not sure whether there is a bug, but I have some doubt about the scroll behavior of the Devices panel.

Following the acceptance criteria I think it should be two scroll bars and it seems to have only one.

https://github.com/dotCMS/core/assets/29883881/6d92ebae-d990-4d93-8911-0fe7756fb50b

**Comment by dcolina** [comment]
Internal QA: PASSED.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3c41b76_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-19 at 10 35 20 AM](https://github.com/dotCMS/core/assets/129882031/c1f4b955-b4c8-4f35-8861-9a35c86305a4)
