### ISSUE TITLE
Create a endpoint to retrieve paginated contentlets

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26363]
### User Story
As an API user, I want the endpoint to retrieve both the unmodified Contentlet (variant: DEFAULT) and its modified Variant using as a parameter the ContentType.

### Acceptance Criteria
- The endpoint returns the unmodified Contentlet (variant: DEFAULT).
- The modified variant of the Contentlet is also retrieved and returned by the endpoint.
- The returned data should be appropriately formatted and consistent.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### Assumptions & Initiation Needs
- It is assumed that the endpoint currently does not differentiate between the DEFAULT variant and its modified counterpart.
- The mechanism to distinguish between DEFAULT and modified variants needs to be precise and reliable.

### Quality Assurance Notes & Workarounds
- Ensure the DEFAULT variant is accurately identified and returned.
- The modified variant, if present, should also be retrieved accurately.
- Test with a variety of contentlets to ensure consistent and expected results.

### Sub-Tasks & Estimates
1. Review the current endpoint behavior.
2. Adjust data retrieval logic to identify and fetch the DEFAULT and modified variants.
3. Modify the endpoint to return the new data set.
4. Test to ensure accuracy and reliability.

**Comment by john-thomas-dotcms** [comment]
Completed previously as part of other Experiments work.
