### ISSUE TITLE
Design System: Fix Table Header Sort Icon Misplacement

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26366]
### Parent
[25355](https://github.com/dotCMS/core/issues/25355)

### Problem Statement
The table header sort icons is currently misplaced, wrapping to the next line.

### Steps to Reproduce
1. Log into dotCMS
2. Navigate to the table view, for example Pages
3. Observe that the sort icons are misaligned with the header

<img width="897" alt="image" src="https://github.com/dotCMS/core/assets/751424/2ba0bb28-532e-4752-b867-8b50741245e2">

### Acceptance Criteria
1. The sort icon should be moved to the right of the header
2. The sort icon should be properly aligned and not wrap to the next line

### External Links
https://primeng.org/table#custom-sort

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
1. QA team should manually test the table view to ensure that the sort icons are properly aligned with the header
2. As a workaround, users can manually adjust the width of the column to prevent the sort icons from wrapping to the next line

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3f81f03**, Docker, macOS 13.0, FF v113.0

**Comment by bryanboza** [comment]
We need some work here: 

- If you are using FireFox as browser, this looks misaligned, the icon is above the text instead to be aligned 

![image](https://github.com/dotCMS/core/assets/2641437/ea830750-4163-43ef-b657-71a9941c6a9e)

We need to be consistent in all the supported browsers.

**Comment by fmontes** [comment]
Not happening in FF for me.
