### ISSUE TITLE
Design System: Block Editor Input styles are not being applied

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26370]
### Parent Issue

https://github.com/dotCMS/core/issues/25355

### Task

As a dotCMS user, it would be fantastic to have the ability to view accurate styling for inputs in the Block Editor. This enhancement would significantly improve the overall user experience by delivering a more polished and seamless UX/UI.

![Screenshot 2023-10-05 at 12 01 08 PM](https://github.com/dotCMS/core/assets/72418962/5d0a804f-e23b-4f6a-b7eb-27355476e50b)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- All style elements in the block editor should match our design system.

### Assumptions & Initiation Needs

To prevent the styles from being affected by hashing and encapsulation, let's create a separate .css file.

This approach will ensure that the styles remain unaffected by any automatic hashing or encapsulation processes.

**Comment by bryanboza** [comment]
Fixed, tested on the last master edition and now the read more section looks better 


![Image](https://github.com/dotCMS/core/assets/2641437/bdbc55ef-03c2-4952-bfcb-cce225e18360)
