### ISSUE TITLE
Use of Png filter on images results in a 404

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#26374]
### Problem Statement

When using the Png filter it results in a 404 when trying to access the image

https://demo.dotcms.com/contentAsset/image/5005364a8ce21d15ee81797e66e53bf1/fileAsset/filter/Png

### Steps to Reproduce

1. Start up a demo starter
2. Attempt to access an image with the Png filter, such as `/contentAsset/image/5005364a8ce21d15ee81797e66e53bf1/fileAsset/filter/Png`

### Acceptance Criteria

Use of the Png filter should correctly generate a Png and not a 404

### dotCMS Version

23.01.7/master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by yolabingo** [comment]
ref Cloud support ticket https://dotcms.zendesk.com/agent/tickets/113624

**Comment by erickgonzalez** [comment]
Working as it should

![Image](https://github.com/dotCMS/core/assets/5278970/1cd8e96a-10be-4ab1-8f56-d9c492ceec3e)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now it is working as expected


![Image](https://github.com/dotCMS/core/assets/2641437/4ef947d2-98de-452e-85c9-76f2dea5b7ff)
