### ISSUE TITLE
CLI: Implement a global pull for languages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26384]
As a user, I want to be able to pull languages in just one command. Currently, I have to manually run the language pull command for each language I have in the system.

Implement unit and ITs as needed.

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me passing it

**Comment by bryanboza** [comment]
Fixed, tested on docker && dotcms-cli-1.0.0-20231002.205953-1.jar and it is working as expected as part of the global pull
