### ISSUE TITLE
pushing multi-lingual contexts with a different number of folders under each language can cause loss of content

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26380]
### Problem Statement

When pushing multi-lingual context with a different number of folders under each language 
like this :
![Screenshot 2023-10-05 at 13 58 29](https://github.com/dotCMS/core/assets/37148755/29be6fb5-5a8d-4b2b-a123-69f62dfcaddd)

Can cause content loss

I suspect that the one-pass algorithm that we are using encounters the local folder under lang (es-es) with fewer folders (images) and determines that all other remote folders not present locally should be marked for removal 
and so it does. Later on, it encounters the other language en-us and discovers that all other folders under root are there. but it is unable to reconcile them and figure out they are not supposed to be removed.

https://github.com/dotCMS/core/assets/37148755/8b172ffe-fdad-4869-b09f-078c6a458a95

### Steps to Reproduce

Here's a workspace with an example:
[multi-lang-folders.zip](https://github.com/dotCMS/core/files/12822837/multi-lang-folders.zip)

in order to see it. unzip the archive. Now configure an instance of dotCMS with the empty starter and add an additional language like Spanish (es)

now push the unzipped archive to the dotCMS instance using the master push command like this:

`dot push /Users/../multi-lang-folders --removeAssets --removeFolders --token *** --errors`

the first time these files get pushed they should get all created 
When re-running the push command a second time. The expected behavior would be to have no changes and nothing getting pushed. 

But what actually happens is that all folders are removed from the dotCMS instance.

### Acceptance Criteria

We should never lose content

### dotCMS Version

current master has it 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dcolina** [comment]
Internal QA: PASSED.

The following video shows the scenario working fine.

https://github.com/dotCMS/core/assets/29883881/34fba486-4fe9-44b2-98c9-03e80df546d9

**Comment by bryanboza** [comment]
Fixed, tested on master and I'm unable to reproduce
