### ISSUE TITLE
CLI: Implement a global pull for sites

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26385]
As a user, I want to be able to pull sites in just one command. Currently, I have to manually run the sites pull command for each site I have in the system.

Implement unit and ITs as needed.

**Comment by fabrizzio-dotCMS** [comment]
I tried pulling all sites, then I archived one of the sites and retried pulling the site remains the same on the client. 
But that's a sync issue. the Global  pull  is all good. Pasig it

**Comment by bryanboza** [comment]
We need some work here, after pull my changes in a local JSON file for some specific site, and run the --dry-run again. We still detecting changes between both files.

**Comment by bryanboza** [comment]
Fixed, tested on docker and it is working as expected.
