### ISSUE TITLE
[UI] Styling issues on experiments

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26387]
### Problem Statement

- The variants list in dotCMS appears to be misaligned, causing difficulty in reading and navigating through the variants.
![image](https://github.com/dotCMS/core/assets/2641437/81f0deb0-b4bd-4a21-9d2c-056c398b549f)

- Also, we need to increase the max size of the description field, this because we are doing a kind of scrolling when you are editing the description which is not necessary since we have a lot of space here

https://github.com/dotCMS/core/assets/2641437/7d7db2aa-21fb-400a-a006-d7fd96d1b7d9

### Steps to Reproduce

- Login to the dotCMS Admin Panel.
- Navigate to Pages portlet 
- Open a page that has an experiment with multiple variants.
- Look for the variants list on the page.

### Acceptance Criteria

- The variants list should be aligned properly, with consistent spacing and indentation.
- The variants should be easy to read and navigate through.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Variants properly aligned one below the other. Tested with 1 and 2 variants + original.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_534774e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
