### ISSUE TITLE
CLI: Allow custom param configuration in the GHA

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26386]
### User Story

As a user, I want to be able to set the flags and other input sent to the GHA implemented [here](https://github.com/dotCMS/core/issues/26300) through a .env file.

### Acceptance Criteria

It should work this way: 
- I define a .env file at the root of my github repository. This file is optional and would contain key/value properties with the params I want it to be used when the GHA runs on each push.
- The GHA should use default params and only consider the ones defined in the .env file if exist.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
Tested the integration on this public repo https://github.com/fabrizzio-dotCMS/dot-cli-push-3.0
I liked that the params can be passed with and with out quotes
e.g. 
`DOT_CLI_OPTS=" --removeAssets --removeFolders --removeSites --removeContentTypes --removeLanguages" `
Passing it.

**Comment by bryanboza** [comment]
Fixed, tested on the last CLI version and now I'm able to add myy token to this file and this is working without problems.
