### ISSUE TITLE
[UI] Change Experiment mod date display from simple date to date/time

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#26399]
## Problem

When a user sends an Experiment to a PP receiver, and then restarts the Experiment on the PP sender on the same day, but doesn't push it again, then from the UI there's no way to tell why the Experiments on sender and receiver are out of sync.

To Reproduce:
1. Start an Experiment on the PP sender.
    * Although this problem still exists for scheduled Experiments, for simplicity of reproduction, start it without scheduling it.
2. Push the Experiment to the PP receiver.
3. Abort and restart the Experiment on the PP sender.
    * Again, for simplicity, just start it.
4. View the Experiments screen for the Page on both sender and receiver.

**Result:** Both sender and receiver show identical "Created" and "Modified" dates in the Experiments list, and show identical "Running until" dates in the Page editor and Experiments config screen.

## Solution

Change the Created and Modified dates to display the full date and time (to minutes, not seconds) in the Experiments list.
* This will make it easy to see if an Experiment was modified on the sender after it was pushed to the receiver.

**Comment by dsilvam** [comment]
Passed Internal QA: Proper date formatting is now displayed, including time. 

![Image](https://github.com/dotCMS/core/assets/1576794/fae85bcc-2cc1-4293-b5e5-aae9bf469fe0)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

![Image](https://github.com/dotCMS/core/assets/2641437/c2e206b7-4b4e-467d-a63c-4b3f6c0d94b3)
