### ISSUE TITLE
PostDatabase mirroring link failed

### ISSUE THREAD

**Issue by cyh920s** [dotCMS/core#26397]
### Problem Statement

After executing the command `curl -o docker-compose.yml https://dotcms.com/run/clean && docker-compose up`, I found that the PostGres database has been unable to connect

![image](https://github.com/dotCMS/core/assets/39732011/3b7aac4a-e2ca-4e47-9942-fe2eb4956153)
![image](https://github.com/dotCMS/core/assets/39732011/981ea8ca-5293-4746-b5e1-ef4f4665dde8)

### Steps to Reproduce

none

### Acceptance Criteria

none

### dotCMS Version

23.05

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
Closing as we can't reproduce; please let us know if you're still seeing this @cyh920s!
