### ISSUE TITLE
Containers: Auto-generated code on containers does not working for dotAssets

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26395]
### Parent Issue

Related to #26348 

### Problem Statement

The code automatically generated on containers is not working for dotAssets in dotCMS.

If you are creating a new container and use the `Add Variable` stuff we are generating a piece of code to display some of the field  properties, but this work just for `fileAssets`, if you reference to a `dotAsset` this will not work as expected 

https://github.com/dotCMS/core/assets/2641437/28ef3ca8-1cca-4dde-81d0-fddcea432219

### Steps to Reproduce

- Login as admin
- Create a new content type that includes an image field 
- Create a container 
- Add the `Image image` variable for that field 
- Add a new template that use the container 
- Create a new page that use the template
- Publish a new content on that page 
- View the page on the front-end.

### Acceptance Criteria

Tested on master // Docker // FF 

### dotCMS Version

- The code automatically generated on containers for dotAssets should work correctly.
- The dotAssets content should be displayed as expected on the front-end when viewing the page.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Closed in favor of this one: https://github.com/dotCMS/core/issues/26293
