### ISSUE TITLE
Make sure the we are using the last Token to get the Events

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#26392]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

To calculate the Experiment's Result we need to get the Experiment's Events from the CubeJS Server, We use this Events with Pagination by 1000 Events for each Page, but we use the token that was active when we got the first page all the time if this page expired on the middle of the result calculation then we got a error, what we need to do here is take the last token every time we request the current Page.

Important thing here we already have a Job to renew the token before it expired, the chance is just about to take this renewed token to get the current page Event.

### Steps to Reproduce

- Start dotCMS up using a low value to the Token expire time attribute (I used 2 minutes).
- Create an Experiment, and start it 
- Create a lot of Event on the CubeJs Server, I reproduced the error with 100.000 and 200.000 (it does not happend all the time).
- Get the result of the Experiment.

of course here you can used a lower value to the Token Expire time (just a few seconds) and you are going to need lees Events to reproduce the error.

### Acceptance Criteria

We need to guarantee that the result calculation is going to finish no matter if the token expire on the middle of the calculation Also we need to make sure the it is not going to fail if the token is expired on the middle of a request to get the current page

### dotCMS Version

lastes on master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Do not apply anymore.
