### ISSUE TITLE
Copy Change for Google SERP Preview

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26402]
[![Screenshot_2023-10-09_21-48-33.png](https://mrkr.io/s/652475318a5f04745a5dcba8/2)](https://mrkr.io/s/652475318a5f04745a5dcba8/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Should be Google "Search Engine Results Page" not "Social Media Preview Tile"

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fblog-detail&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fblog-detail&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/652475318a5f04745a5dcbab_d852818454458ad7?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 118.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by dcolina** [comment]
Internal QA: PASSED.

![Image](https://github.com/dotCMS/core/assets/29883881/d3786480-1547-4192-9b7a-39a328e97c2c)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3c41b76_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-19 at 11 54 52 AM](https://github.com/dotCMS/core/assets/129882031/4cb6d0c6-17a2-4fcc-8d55-7c1632d340be)
