### ISSUE TITLE
[UI] Improve the input of the date/time select

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26408]
### User Story
As a user, when I navigate to the "Schedule experiment" step in the "Experiment Configuration", I expect the input field to have the correct CSS styling for consistency and clarity.

### Acceptance Criteria
- The input field in the "Schedule experiment" step should have the appropriate and consistent CSS styling.
- The input field should be visually consistent with other input fields across the application.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### Assumptions & Initiation Needs
- Assuming that other parts of the application have a consistent input CSS styling that this input should match.
- The current CSS for the input might be outdated or overridden by other styles.

### Quality Assurance Notes & Workarounds
- Ensure cross-browser consistency for the input field's appearance, like the Figma file.

### Sub-Tasks & Estimates
1. Review and identify the incorrect CSS styling in the "Schedule experiment" input.
2. Update the CSS to ensure it's consistent with other input fields.
3. Test on various browsers and screen sizes.

**Comment by oidacra** [comment]
Fixed with the implementation of #26409 
Old:

![Image](https://github.com/dotCMS/core/assets/1909643/d8f860df-2c96-44cd-ad0f-0932c2fa5e88)

![Image](https://github.com/dotCMS/core/assets/1909643/8d9e83a9-2895-46bc-afbe-17b24a6cf319)


New:

![Image](https://github.com/dotCMS/core/assets/1909643/9e19c9be-48cd-468b-8627-944cd134b6d4)

**Comment by dsilvam** [comment]
Blocked by: https://github.com/dotCMS/core/issues/26565

**Comment by hmoreras** [comment]
PR to set default min time frame from 14 to 7 days: https://github.com/dotCMS/core/pull/26608

**Comment by dsilvam** [comment]
Passed Internal QA: Min is 7 days now.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8a0c462_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
