### ISSUE TITLE
Keep the same running id when scheduling then publish an Experiment

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26400]
### Parent Issue

https://github.com/dotCMS/core/issues/25665

### Problem Statement

When an Experiment is Scheduled at the Sender, the system does not generate a running id, so, if pushed to the Receiver, when both Experiments start, they will end up with different running ids hence the inability to see the results from the Sender. 

The running id needs to be generated at the moment of Scheduling and passed by when starting the Experiment.

### Steps to Reproduce

1. Create a new Experiment with an valid Scheduling (starts in the future)
2. Schedule the Experiment
3. Push Publish the Experiment

When the Experiments in both the Sender and Receiver start, they will have different running ids, hence, results gathered from the Receiver won't be accesible from the Sender. 

### Acceptance Criteria

After going through the steps mentioned above, the results gathered from the Receiver need to be accesible from the Sender. 

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed Internal QA: Tested directly on Auth/Prod. Scheduled Experiment was pushed and once running and after gathering results, they can be accessed from both Auth and Prod.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
