### ISSUE TITLE
Preview Button should always take user to Default Preview 

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26419]
[![Screenshot_2023-10-11_15-07-50.png](https://mrkr.io/s/6526ba462f1749772af6b97e/2)](https://mrkr.io/s/6526ba462f1749772af6b97e/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Currently the Preview Button doesn't work when you are on a Preview Screen. It should always take a user back to the Default Preview View.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6526ba462f1749772af6b981_cbd625e1623fbe91?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 118.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 940</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by nollymar** [comment]
**Internal QA:** Passed



https://github.com/dotCMS/core/assets/8741395/e35472f6-f74c-40e1-ae06-673eaa8c102d

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_fad2bfd_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
