### ISSUE TITLE
[UI] Unable to Create Bundles from Experiments

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26416]
### Problem Statement

The "Add to Bundle" component in dotCMS is not allowing input of text, preventing users from creating bundles from experiments.
![image](https://github.com/dotCMS/core/assets/2641437/8a246eeb-c9ce-42d3-919d-dcf98c4668c7)

### Steps to Reproduce

- Log in to dotCMS.
- Navigate to the Experiments section.
- Open any experiment.
- Locate the "Add to Bundle" component.
- Attempt to input text in the component field.

### Acceptance Criteria

- Users should be able to input text in the "Add to Bundle" component field.
- The entered text should be saved and used to create a bundle from the experiment.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Full text input available again. Able to either choose an existing bundle or type the name of a new one.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 


![Image](https://github.com/dotCMS/core/assets/2641437/10dfeb19-8f75-43a2-9aa5-d6fb0cd0d007)
