### ISSUE TITLE
Template Builder: System Template should create layout always

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26415]
### Problem Statement
When you create a page with a system template, and only that page have the system template, if you try to save the layout it tries to edit the template instead of create the layout.

### Steps to Reproduce
1. Create a page with system template (make sure is the only page with the system template)
2. Edit the page and click in "Layout"
3. Change the layout
4. See there is an error because it tried to edit the system template instead of a layout.

### Acceptance Criteria
We should create a layout out of a system template all the time.

### External Links
N/A

### Quality Assurance Notes & Workarounds
Testing should ensure that the template is not modified when the user is editing the layout of a page. If the template is modified, the user should be able to revert the changes. As a workaround, the user can edit the template in the dotCMS admin panel instead of using the Layout Builder.

**Comment by freddyDOTCMS** [comment]
Note to QA: Really we need to create a layout just if the Template is been using for more than 1 Page, but in the Case that the Template is the SYSTEM TEMPLATE then we need to create a layout all the time

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/27175

**Comment by dsilvam** [comment]
Passed Internal QA: Creating a custom layout when modifying the layout of a page which had SYSTEM_TEMPLATE assigned.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8aae521**, Docker, macOS 13.0, FF v121.0.1
