### ISSUE TITLE
Error pushing experiments that contains multi-lang variants 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26425]
### Problem Statement

When you create an experiment to a multi-lang page, and you create one variant for the default language and the other variant for another language. If you try to push this experiment, we are getting an error trying to bundle the experiment and of course the push fails 

Here the error: https://gist.github.com/bryanboza/9acbf67f3269fe590afa63d8d57be5c3

### Steps to Reproduce

- Login as admin
- Create a multi language page 
- Create an experiment to that page with one single variant 
- Add a new variant for a this page but in another language 
- Try to push it 

### Acceptance Criteria

- We need be able to support experiments with variants in all the languages that the page exist 
- We need be able to push it without problems 

### dotCMS Version

Tested on master // docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by victoralfaro-dotcms** [comment]
Internally QA tested at `dotcms/dotcms:master_731b526_SNAPSHOT`
Sender pages at root
<img width="1625" alt="image" src="https://github.com/dotCMS/core/assets/64026161/5d475a01-92bb-43df-9332-ce7026e6f4fe">
Receiver pages at root
<img width="1631" alt="image" src="https://github.com/dotCMS/core/assets/64026161/950ed1aa-c259-4520-ad2a-b6dc40438c07">

**Comment by dsilvam** [comment]
Passed Internal QA: Working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_eb391b4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

![Screenshot 2023-11-03 at 11 45 52 AM](https://github.com/dotCMS/core/assets/129882031/70c382e2-8651-4632-9ebf-b675be873ff6)
