### ISSUE TITLE
Block Editor: Add align-justify option to menu

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26421]
### Problem Statement

The customer is looking for an align-justify option in the block editor.

### Steps to Reproduce

![image](https://github.com/dotCMS/core/assets/139247809/a9315cdb-5f91-4b91-adff-d8883eedd440)

Block editor options should include the align-justify option.

### Acceptance Criteria

Block editor options should include the align-justify option.

### dotCMS Version

23.01.7

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/G01N0AU1NUC/p1696967234785899
https://dotcms.zendesk.com/agent/tickets/113666

**Comment by rjvelazco** [comment]
**Dev Note:** Tiptap already has an extension for that: https://tiptap.dev/api/extensions/text-align

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master


https://github.com/dotCMS/core/assets/144152756/f6183ba8-25c5-473c-9ba1-738b0c6362b5

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8a0c462_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
