### ISSUE TITLE
Exact Match Filtering by Labels in Content Search

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#26432]
### Problem Statement

When I look to filter my content items in the content search screen, I would like to filter by labels and only see content that contains the labels I have selected. However, if I have labels that share an initial string, I return content of multiple labels instead of just the label I chose.

For example, two labels `string` and `string continued` when filtered by the label `string` brings content with both label results.
![Screenshot 2023-10-12 at 2 06 48 PM](https://github.com/dotCMS/core/assets/90852779/d98b80f5-608b-4c45-8dfa-a56fe5ddc372)
![Screenshot 2023-10-12 at 2 07 05 PM](https://github.com/dotCMS/core/assets/90852779/4e6a8653-d15a-4e25-9d38-481e59d1f8d5)

This impacts content editors in the backend severely, as they will have to sort through 1000's of documents and are relying on this filtering to be exact. 

### Steps to Reproduce

Create a content type with a select field and insert two values into the select field, one with a single word and another with the same word followed by any additional string you desire (e.g, `string` and `string continued` then make the field user searchable.

Go to the content search tool, create two content items each using one of the labels created in the select field. Choose the content type created, and filter by the first label. you will see the two content items, each with their own separate labels, displayed instead of the second content item being filtered out. 

### Acceptance Criteria

Label values must filter by exact matches.

### dotCMS Version

demo
23.01

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113681

**Comment by prestonso** [comment]
Closing as we'll be covering this within the Content Search Portlet Enhancements epic.
