### ISSUE TITLE
Design System: Fix Dropdown Search in Dojo

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26435]
### Problem Statement
The current dropdown is broken when user search for options.

### Steps to Reproduce
1. Go to System > Configuration > Publishing Environments (Tab)
2. Click on Add Environment
3. In the "Who Can Send to this Environment" select, type a letter
4. See the error

<img width="534" alt="image" src="https://github.com/dotCMS/core/assets/751424/22c83df3-e30e-4000-b416-5e6f79c43c72">

### Acceptance Criteria
- The dropdown should filter the options when user searches
- We should be able to show 2 lines in the options, for example in the template selector
- Make the highlight string bold

### External Links
N/A

### Assumptions & Initiation Needs
- The search functionality should be consistent across all selects

### Quality Assurance Notes & Workarounds
N/A

**Comment by KevinDavilaDotCMS** [comment]
# Pass internal QA
Tested in master

https://github.com/dotCMS/core/assets/144152756/51d9d42d-5ecd-4995-8062-8333708feecc

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_226a23f_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-17 at 3 05 26 PM](https://github.com/dotCMS/core/assets/129882031/b750e37c-d885-44e8-8f5b-10451217fee7)
