### ISSUE TITLE
Misalignment of Bundle Selector Drop-down Button

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26431]
### Parent Issue

Experiments

### Problem Statement

The caret bundle selector is not right-aligned when no elements are displayed.

### Steps to Reproduce

1. Open the application
2. Navigate to a section where the caret bundle selector is present, ensuring it's in a state with no elements displayed
3. Observe the alignment of the caret bundle selector

### Acceptance Criteria

The caret bundle selector remains in its default alignment even when no elements are present, causing visual inconsistency.

### dotCMS Version

23.09.5

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2023-10-12 at 1 40 01 PM](https://github.com/dotCMS/core/assets/129882031/3266420c-b6b3-4c16-80b4-b0f96c79d9f2)

**Comment by oidacra** [comment]
It cannot be reproduced in FF or Chrome.

<img width="1951" alt="Screenshot 2024-09-20 at 10 50 35 AM" src="https://github.com/user-attachments/assets/4bc75aff-0dab-42a9-9b50-6b9c2d84202f">
