### ISSUE TITLE
Pages: Unable to push pages from this portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26451]
### Problem Statement

When you are in the new pages portlet and you right click and try to publish some page, we are not including the page into the bundle and we are sending an empty bundle. 
![image](https://github.com/dotCMS/core/assets/2641437/40841b02-96b4-459c-b873-13633f68c06c)

### Steps to Reproduce

- Login as admin 
- Configure your push environment 
- Create a new page 
- Go to the Site --> Pages portlet and try to push it 
- Check the bundle from publish queue and make sure it contains the page 

### Acceptance Criteria

- We need be able to push any page from this portlet 
- Bundle should include the selected page 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
The payload set in the UI is not passing down a valid Identifier when push publishing the page:

<img width="1802" alt="Screenshot 2023-10-18 at 10 38 25 AM" src="https://github.com/dotCMS/core/assets/8779585/a6c4d953-0599-4f6f-8060-cb4d1b4a46ae">

cc. @zJaaal

**Comment by bryanboza** [comment]
We need some work here, tested with the last master code and we still sending an empty bundle when you try to push something from this portlet 
![image](https://github.com/dotCMS/core/assets/2641437/0f566e3f-0a06-4313-867a-4bd64047a21d)

**Comment by zJaaal** [comment]
Can you reproduce that and give me the exact steps @bryanboza ? I tested it again in `master-latest` and it's working.

**Comment by fmontes** [comment]
@bryanboza provide a video please I tested this morning in master

**Comment by bryanboza** [comment]
https://github.com/dotCMS/core/assets/2641437/b341b5e3-029c-49ed-998f-4a30652f7214

**Comment by bryanboza** [comment]
Fixed, It was caused by an error generating the image, we are not taking the last UI changes. Now it is working as expected

**Comment by erickgonzalez** [comment]
Only for 23.10 LTS
