### ISSUE TITLE
Unable to add forms to experiment variants on dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26452]
### Problem Statement

Users are unable to add forms to experiment variants in dotCMS.

![image](https://github.com/dotCMS/core/assets/2641437/a8a64754-b7d8-46bb-ba33-50fadb0663bc)

Here the log error: https://gist.github.com/josemejias11/bd0721ba3e305e14ac19300cccae09cb

### Steps to Reproduce

- Log in to dotCMS.
- Navigate to the experiments section.
- Create a new experiment.
- Add multiple variants to the experiment.
- Attempt to add a form to one of the experiment variants.
- Notice that there is no option or functionality to add a form to a variant.

### Acceptance Criteria

- Users should be able to add forms to experiment variants in dotCMS.
- There should be a clear and intuitive way to add forms to each variant.
- The added form should be visible and functional within the experiment variant.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
It is happening even outside Experiment

**Comment by dsilvam** [comment]
Passed Internal QA: Working both inside and outside Experiments. Tested on Docker.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now forms are working as expected inside and outside experiments.,
