### ISSUE TITLE
Edit Content: Update Inode in the URL with New Inode on Contentlet Save

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26460]
### Parent
#25445

### User Story
As a content creator, when I save a new content I want the URL in the address bar to match the saved contentlet inode.

### Acceptance Criteria
- Update the inode in the URL when user edit a piece of content
- Update the url from "Create" to "edit" when the content is saved the first time.

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
- The Angular routing system must be used to update the inode in the URL with the new inode.

### Assumptions & Initiation Needs
- The Angular routing system must be properly configured.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Configure Angular routing system: 1 hour

**Comment by rjvelazco** [comment]
Solved here: https://github.com/dotCMS/core/issues/26969

**Comment by rjvelazco** [comment]
Solved in this ticket https://github.com/dotCMS/core/issues/26969
