### ISSUE TITLE
[UI] Fix show Name of Goal added by the user when set goal at Experiment Report's Summary

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26474]
### Problem Statement

As a User, I am clear about the name of the Goal in the Experiment Report's Summary

### Steps to Reproduce

- Go to an Experiment with an Exit Rate Goal
- Go to reports

### Acceptance Criteria

- In the Summary component, show the **Name of Goal** added by the user. 

<img width="1018" alt="Screenshot 2023-10-20 at 11 22 30 AM" src="https://github.com/dotCMS/core/assets/1909643/86c85449-ffc0-4e63-a8eb-c5f2da4486b6">

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1434" alt="Screenshot 2023-10-19 at 3 26 37 PM" src="https://github.com/dotCMS/core/assets/1909643/9303b98d-784c-48a3-8323-6782f7411ceb">

**Comment by dsilvam** [comment]
Passed Internal QA: Showing the full Goal Name, which is, the one entered by the User.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_eb391b4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
