### ISSUE TITLE
Search filter can't find/filter images

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#26477]
### Problem Statement

Search filter can't find/filter images when trying to add them into the image field. Also, the images are multiplicated if the search filter field is clear and the backspace key is pressed multiple times.
Only new images can be filtered.

### Steps to Reproduce

1.- Open/create a contentlet with an image field.
2.- Click on the Browse button to add an image.
3.- Type the name of an image to search.

![Screenshot 2023-10-19 at 2 24 14 PM](https://github.com/dotCMS/core/assets/12899960/d7a54e6b-9fcd-49c3-a1d8-3d829a4ceb17)
![Screenshot 2023-10-19 at 2 24 28 PM](https://github.com/dotCMS/core/assets/12899960/090ac0a8-f20f-47a8-8e4b-683051e05509)
![Screenshot 2023-10-19 at 2 25 04 PM](https://github.com/dotCMS/core/assets/12899960/d7c0c8ea-1652-4ac7-8411-a3c31cc74bff)

https://github.com/dotCMS/core/assets/12899960/3850fd04-63e7-480c-8d95-84f8ce257fbe

### Acceptance Criteria

The images should be able to filter/search and show depending on the words inserted into the search/filter field.

### dotCMS Version

Demo
QA 22.03

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CSHTYUR7H/p1697741820007979
https://dotcms.zendesk.com/agent/tickets/113797

**Comment by erickgonzalez** [comment]
@EdgarPsda, if you try to filter inside a folder, does it behave the same way?

**Comment by AndreyDotcms** [comment]
I was unable to replicate the backspace error on master. It only occurred in the QA server and demo.


https://github.com/dotCMS/core/assets/127987858/632728b6-9be8-4084-9b90-830ee4206a06

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF and I;m unable to reproduce
