### ISSUE TITLE
Unable to push experiments 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26476]
### Problem Statement

After the last changes, when  you trey to push an experiment we are getting an error generating the bundle and we are unable to push it. 

Here the error: https://gist.github.com/bryanboza/9c250c974c1d5f4f355ab455c532b6e6

<img width="1549" alt="image" src="https://github.com/dotCMS/core/assets/2641437/7f5602c1-0df6-49a3-9388-01366085b418">

### Steps to Reproduce

- Setup a push env
- Login as admin
- Create a new page 
- Add an experiment to the page 
- Try to push the experiment 
- 

### Acceptance Criteria

We need be able to push the experiments without problems 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed IQA: Experiments able to be pushed again.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_eb391b4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
