### ISSUE TITLE
Pubsub Connection should prefer SSL

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26481]
### Problem Statement

The `pgjdbc-ng` driver/connection we use for pubsub does not force SSL connections to the postgres database.  When upgrading our RDS instances to use postgres 15.4 the PubSub failed to connect.  You can fix this by adding 
`?ssl.mode=prefer` that will tell the connection to prefer SSL. 

### Steps to Reproduce

Try running dotCMS against a postgres instance that does not allow non-ssl connections

### Acceptance Criteria

PubSub needs to autowire correctly.

### dotCMS Version

23.10

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, tested starting the server using psql 15 with the single jdbc url: 
```
 "DB_BASE_URL": "jdbc:postgresql://db/dotcms"
```

Now is not necessary add the `?ssl.mode=prefer` to start 

Tested on master // Docker // FF
