### ISSUE TITLE
Edit Content: Deprecate Old Content API Endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26498]
### User Story
As a dotCMS stakeholder, I want to deprecate the old content API endpoint `api/content/id/{identifier}` in favor of the new endpoint `api/v1/content/{identifier}`, so I can keep my content up to date.

### Acceptance Criteria
- Make sure the new endpoint have the same options as the old one
- Mark the old endpoint as deprecated in the documentation.
- Update the documentation with the new endpoint.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The new endpoint is already available.
- The documentation has already been updated to reflect the new endpoint.

### Quality Assurance Notes & Workarounds 
N/A

### Sub-Tasks & Estimates
N/A

**Comment by jdcmsd** [comment]
While testing out the `v1` series, I notice there may be some permissions asymmetries that might warrant a closer look. As a user with limited permissions, I figure these sorts of issues may be less obvious to full admins, so let me know if I've spotted a bug or maybe I'm just missing something.

On Auth, I've got full permissions to engage with Documentation content, and yet I was getting `403 Forbidden` messages when I tried to use this `GET` on a contentlet:

`/v1/content/resourcelinks`

And yet this one, its subordinate, worked just fine:

`/v1/content/resourcelinks/field`

For reference, here's the `/resourcelinks/field` one that succeeded:

```
curl -X 'GET' \
  'https://authoring.dotcms.com/api/v1/content/resourcelinks/field/diagram2?identifier=37982cb8ca95bfdd3296f688347c56fe&language=-1' \
  -H 'accept: application/json;charset=UTF-8'
```

and here's the `/resourcelinks/` that failed:

```
curl -X 'GET' \
  'https://authoring.dotcms.com/api/v1/content/resourcelinks?identifier=37982cb8ca95bfdd3296f688347c56fe&language=-1' \
  -H 'accept: application/json;charset=UTF-8'
```

However: I _was_ able to use both successfully on a Call to Action contentlet also on Auth (id `f07fc013-4136-42d7-af4b-4ceb93da3cab`, field `image`).

What do folks think about this?

**Comment by fmontes** [comment]
@jdotcms
[fix(core): Add "depth" option to new Content API Endpoint](https://github.com/dotCMS/core/commit/5e7599a4b6a8ce4386942a078ba36e46b4fa76a8) https://github.com/dotCMS/core/issues/26498

We need to QA only the depth for now.

**Comment by fmontes** [comment]
check the cache of the depth

**Comment by fmontes** [comment]
Let's try in postman
