### ISSUE TITLE
Misalignment of Character Inside Icon Image on ' + ' CTA When Adding Content in Edit Mode

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26507]
### Parent Issue

Edit Mode (Page)

### Problem Statement

The character (likely '+') inside the icon image for the ' + ' Call-to-Action (CTA) button appears misaligned.

### Steps to Reproduce

1. Navigate to the section/page where content addition is possible
2. Enter edit mode
3. Locate and observe the ' + ' CTA button
4. Observe the alignment of the character inside the icon image

### Acceptance Criteria

In edit mode, when adding content, the character inside the icon image should be centered and align

### dotCMS Version

23.10

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2023-10-18 at 1 20 50 PM](https://github.com/dotCMS/core/assets/129882031/33ac50ba-1bee-4462-acdc-dbfeb04fa68d)

**Comment by oidacra** [comment]
Works now as expected.
<img width="1877" alt="Screenshot 2024-09-20 at 1 56 26 PM" src="https://github.com/user-attachments/assets/9aae551f-3e66-48d6-bdf7-875047a0c9cd">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4359825**, Docker, macOS 14.5, FF v126.0.1
