### ISSUE TITLE
[UI] - Make AI Text Block Production-ready

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26504]
### Parent Issue

#26495

### User Story

As a user of the Block Editor, I want to have an AI Content Prompt Extension so that I can efficiently and effectively generate and create content with AI suggestions.

Endpoint: `/api/v1/ai/text/generate`

### Acceptance Criteria

- The Block Editor should have an "AI Content " command in the list
- Users should be able to activate the AI suggestions with a single click or command.
- Users should have the option to accept, modify, or reject AI suggestions.
- Error handling of the AI endpoints are not in the scope of this task.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

**Command Menu**
<img width="1398" alt="Screenshot 2023-10-24 at 11 32 21 AM" src="https://github.com/dotCMS/core/assets/1909643/447459e9-9e47-47c8-9e57-f674cfa853e1">

**Prompt Input**
<img width="1390" alt="Screenshot 2023-10-24 at 11 32 28 AM" src="https://github.com/dotCMS/core/assets/1909643/87aabb0a-5178-44be-8ad2-c5b55e476204">
<img width="1398" alt="Screenshot 2023-10-24 at 11 32 34 AM" src="https://github.com/dotCMS/core/assets/1909643/7efeb240-7744-4165-b186-1b9bb883a864">

**Content Generated**
<img width="1387" alt="Screenshot 2023-10-24 at 11 32 45 AM" src="https://github.com/dotCMS/core/assets/1909643/a87d421c-cdab-4f09-9114-56362a49efb8">

### Assumptions & Initiation Needs

- Assuming the AI Image Prompt Extension has the necessary APIs and SDKs for integration.
- Users have a basic understanding of the Block Editor functionalities.

### Quality Assurance Notes & Workarounds

- Ensure that the AI suggestions do not interfere with the normal functioning of the Block Editor.

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26519
- [ ] https://github.com/dotCMS/core/issues/26665
- [ ] https://github.com/dotCMS/core/issues/26666
- [ ] https://github.com/dotCMS/core/issues/26667
`\`\`

**Comment by hmoreras** [comment]
QA notes: 

1. Install the last version of the AI plugin.
2. Add the token key in the apps configuration portlet. 
4. Create a content that has a block editor on it, or use one that already have it like BLOG.
5. In the Editor type /ai, select the AI Content. 
6. Type a prompt and hit enter, wait for the response. 
7. Once the response is done, text should added to the editor, and a context menu should  show. 
8. All functions of the context menu should work.

**Comment by dsilvam** [comment]
Passed Internal QA: Working as described in the QA Notes. Used token key provided by @hmoreras and the three options in the context menu working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_5973727**, Docker, macOS 13.0, FF v121.0.1
