### ISSUE TITLE
Add support of urlTitle for URL map content as hyperlink in Block Editor

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#26501]
### User Story

When we add a hyperlink in Block editor for a URL map contentlets it creates a hyperlink as an inode URL but not with a title. As a workaround, the customer has to copy the URL manually and paste into the hyperlink dialog.

![image](https://github.com/dotCMS/core/assets/102758033/9cd39c3c-ab2d-4436-9fcb-6792a8200ee5)

### Acceptance Criteria

Block Editor supports adding URL title for URL map content as a hyperlink.

### Proposed Objective

Customer Success

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113814

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `745ee55`

https://github.com/user-attachments/assets/f36c251a-760c-468a-ba70-401897b25a54

**Comment by bryanboza** [comment]
Fixed, tested on main // Docker // FF
