### ISSUE TITLE
CORS not applied when specifying resource

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26503]
A quick test looks good for `DEFAULT` - setting
```
        DOT_API_CORS_DEFAULT_ACCESS_CONTROL_ALLOW_CREDENTIALS: 'false'
        DOT_API_CORS_DEFAULT_ACCESS_CONTROL_ALLOW_METHODS: 'PUT'
        DOT_API_CORS_DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN: 'http://example.com/'
```
returns
```
Access-Control-Allow-Methods: PUT
Access-Control-Allow-Credentials: false
Access-Control-Allow-Origin: http://example.com/
Access-Control-Allow-Headers: *
Access-Control-Expose-Headers: *
```

I found that the example in the docs for a 
[Resource Specific Header](https://www.dotcms.com/docs/latest/cors-header-configuration#ResourceSpecificHeaders) does not appear to work - trying to set headers for "content" resource
```
        DOT_API_CORS_CONTENTRESOURCE_ACCESS_CONTROL_ALLOW_CREDENTIALS: 'false'
        DOT_API_CORS_CONTENTRESOURCE_ACCESS_CONTROL_ALLOW_METHODS: 'PUT'
        DOT_API_CORS_CONTENTRESOURCE_ACCESS_CONTROL_ALLOW_ORIGIN: 'http://example.com/'
```
does not change the default headers for 
`curl -ks --head -X OPTIONS http://localhost:8082/api/content`
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,HEAD,OPTIONS,PATCH
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: *
Access-Control-Expose-Headers: *
```

_Originally posted by @yolabingo in https://github.com/dotCMS/core/issues/26391#issuecomment-1760405238_

**Comment by yolabingo** [comment]
another customer request for this https://dotcms.freshdesk.com/a/tickets/27925

**Comment by wezell** [comment]
Added a branch to this issue that does not fix the original issue but it allows cors filters to be overridden by the system table

**Comment by erickgonzalez** [comment]
Working as it should, now we're able to apply CORS by resource.
![Screenshot 2024-10-09 at 4 26 31 PM](https://github.com/user-attachments/assets/b579c341-a5d1-4771-bddd-ea73068f0d15)

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
