### ISSUE TITLE
CLI  Files Push - continues to attempt folder removal after having succeed the first time

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26508]
### Parent Issue

https://github.com/dotCMS/core/issues/26380

### Problem Statement

Our "CLI Files Push" command explores the local file system and makes a comparison against the remote contents of the dotCMS instance it wants to synch with. 
Once the command recognizes a folder that needs to be removed it creates a tree-like data structure that represents all the files and folders hierarchically organized. Then that tree-like structure gets passed down to the next service that will process all the items marked for deletion.
The problem is that once a folder is deleted for a language or state combination.  
subsequent attempts to delete that same folder under other language and state combinations will error out with an ugly exception. 

### Steps to Reproduce

When testing the solution for https://github.com/dotCMS/core/issues/26380 
You should see 404 error messages for each and every combination of status and language where the folder could have been 

### Acceptance Criteria

Once a folder is marked for delete. Only one single attempt should be made. All unnecessary subsequent attempts should be dropped deletion

### dotCMS Version

current master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
This issue found by @nollymar is due to a change in the logical name. When we create a new version using a whole different binary the logical name on the contentlet changes there for the next time we do a pull a brand new file file with a different name gets created (jumbo.jpeg). The issue is that we're not removing the old  (dummy.jpg) 
Currently, we don't have a way to track what other names an asset could have had. Only the underlying file name comes with the metadata. But upon several changes the underlying file name becomes useless. 

As for now, it has been decided that this issue won't be fixed for v1. If This becomes an issue in the future will fix it.

**Comment by nollymar** [comment]
**Internal QA:** Passed

Considering @fabrizzio-dotCMS ' comment above, I'm passing the internal QA after testing the case specified in the card description.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF... 

Maybe we need to include this in the doc...
