### ISSUE TITLE
Edit Content: Add Date and Date and Time Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26512]
### Parent
#25445

### User Story
As a Content Architect in dotCMS, I want to be able to add a Date and Date and Time Field to the Edit Content Form, so I can easily create and edit content.

```[tasklist]
### Acceptance Criteria
- [x] Update the forn to render a Time field
- [x] Update the form to render a Date field
- [x] Update the form to render a Date and Time field
- [x] Ensure the fields include label, hint, required and their respective field variables.
- [x] Ensure that fields are responsive and adjust it width to the parent element
- [x] "Default Value" should work select the corresponding option unless the value is set from the backend (see video)
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Use https://primeng.org/calendar

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
We need to add the show icon attr so it looks like this:



![Image](https://github.com/dotCMS/core/assets/751424/4527254c-419e-4552-a71f-9bb0e3f6196a)


For the time, let's change the icon to a clock.

**Comment by rjvelazco** [comment]
### Failed Internal QA

- Tested on: `master`


https://github.com/dotCMS/core/assets/72418962/85254970-b718-47e3-9664-5289ddf61db5


### Steps to Reproduce:
1. Add the three fields: Date, Time, and Date and Time.
2. Add a default value for each field.
3. Create a new `contentlet`.
4. Set the Date to January First for both `Date` fields.
5. For time, set 12:00
6. Save changes, go to search, and then go to the same `contentlet.`
7. See the error, `Date` is going to be December 31th and `Time` is going to be `20:00`

**Comment by zJaaal** [comment]
As we discussed this can be related of how are we going to manage the Locale in the edit content, so this should be fixed when we start working on it. Any thoughts @fmontes?

**Comment by fmontes** [comment]
@zJaaal We should fix this here, this should be at least saving the date correctly, let's research.

**Comment by zJaaal** [comment]
I'm taking a look at it

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `master`

https://github.com/dotCMS/core/assets/72418962/619cdc24-f984-4549-91a9-d6e673179fda

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_961942e_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
