### ISSUE TITLE
OSGi/Felix - Discard fragment JARs after upload 

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#26518]
### User Story

As a plugin developer, having the plugin fragments in the undeployed list is confusing. After they have been processed, redeploying them from the undeployed state has no effect as it does not put them through the upload behavior again (reading in packages). Deploying them can actually cause issues with the felix framework starting, as well.

### Acceptance Criteria

Discard the fragment after processing
Provide a message to the user letting them know the packages in the fragment have been added to the exported packages list

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
You can use this as a test
[header-app.zip](https://github.com/dotCMS/core/files/15100614/header-app.zip)

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker: [`dotcms/trunk_ 2b727f8`]

### Issue

When adding a `fragment` we are showing `New OSGI Plugins has been installed` instead of `The packages in the fragment have been added to the exported packages list.`

### Video

https://github.com/dotCMS/core/assets/72418962/123fcd98-15f0-4401-a13d-bd852a8b15d1

**Comment by rjvelazco** [comment]
Are there any updates here, @fmontes @jdotcms? Are we going to add the `The packages in the fragment have been added to the exported packages list.`?

**Comment by jdotcms** [comment]
We do, we imported the packages and then discard

**Comment by dsilvam** [comment]
Failed IQA: This is missing the message requested in the description/acceptance-criteria

**Comment by dsilvam** [comment]
Passed Internal QA: Properly discarding fragment and showing expected message. 



![Image](https://github.com/dotCMS/core/assets/1576794/e5608dae-4dd2-48bd-8ec3-2063b974f1d6)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d04bdd9**, Docker, macOS 14.5, FF v126.0.1
