### ISSUE TITLE
[UI] Add `DotMessageService` to Block Editor to able translate the labels/messages

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26520]
### User Story

Translations do not exist in block editor. 

### Acceptance Criteria

Add the ability to translate strings. in block editor. 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by john-thomas-dotcms** [comment]
Some work was already done to make the strings used by the AI plugin translatable.  But the actual translations weren't performed.

So, we need to ensure that the translations are actually performed, and the translated strings are available in the right place for them to show up in the BE.  The way this should be done is that the Language variables with the translations should be added by the plugin when it loads; the code to do this should exist already in the plugin.

**Comment by oidacra** [comment]
Block Editor does not have the service for translations. This will be the first time using BE translations in Block Editor..

**Comment by john-thomas-dotcms** [comment]
We do not need to support translation of content in the AI block.  We need to support translation of the strings the AI blocks use (meaning the labels on the fields in the popup).

**Comment by oidacra** [comment]
Correct. That is the main. Labels, error messages, name of menu.
