### ISSUE TITLE
Edit Content: Add Tags Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26526]
### Parent
#25445

### User Story
As a Content Architect in dotCMS, I want to be able to add a Tags field to the Edit Content Form, so I can easily create and edit content.

```[tasklist]
### Acceptance Criteria
- [x] Update the forn to render a Tags field
- [x] Ensure the fields include label, hint, required and their respective field variables.
- [x] Ensure that fields are responsive and adjust it width to the parent element
- [x] "Default Value" should work select the corresponding option unless the value is set from the backend (see video)
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Use the chips components: https://primeng.org/chips
- We might have to change to autocomplete later on because this will use suggestions

### Quality Assurance Notes & Workarounds
The tag field should be tested to ensure that it is working as expected.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on: `master`

https://github.com/dotCMS/core/assets/72418962/68176a60-f13b-4dbf-b1cf-97a03fb1707e

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_4893f5b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
