### ISSUE TITLE
Truncated SEO Titles need Ellipsis 

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26531]
[![Screenshot_2023-10-26_16-39-07.png](https://mrkr.io/s/653a962b14d46bc022f8b4e8/2)](https://mrkr.io/s/653a962b14d46bc022f8b4e8/0)

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653a962b14d46bc022f8b4ef_7f8e757eb3a116a2?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 118.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by zJaaal** [comment]
# IQA Passed

Now we can see the ellipsis when the text needs to be truncated.

Docker Image: `[dotcms/dotcms:trunk_b00ffaf]`

## Screenshot


https://github.com/user-attachments/assets/4d5576c6-886f-4f91-b461-6cdbceadea5c

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
