### ISSUE TITLE
404 Error page not displaying

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26533]
### Problem Statement

404 redirects to our custom page are not working when an incorrect URL is entered.

### Steps to Reproduce

1. Login to (https://dotcms-qa-lts2203.dotcms.site/dotAdmin/#/c/content) 
2. Try accessing https://dotcms-qa-lts2203.dotcms.site/abcd
3. It doesn't re-direct to the custom page 

### Acceptance Criteria

The incorrect URL should redirect to our custom page

### dotCMS Version

22.03.10

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113853

**Comment by erickgonzalez** [comment]
This works well for 23.01 +, so let's take a look directly at 22.03 LTS.

**Comment by dsolistorres** [comment]
This issue was already reported and fixed on the main branch: #22559
We're going to back port the fix to 22.03 LTS
