### ISSUE TITLE
Determine what's needed for Support to support/maintain the Analytics infrastructure

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26537]
### Task

Make Support has what's needed to successfully support/maintain the Analytics infrastructure.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Support has what's needed to Cloud Engineering to support/maintain the Analytics infrastructure

**Comment by john-thomas-dotcms** [comment]
Not a development activity.  Handled in the GTM process with marketing & other teams.
