### ISSUE TITLE
Enable better logging for getPageByPath in HTMLPageAssetAPIImpl.java

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26546]
### User Story

We have an issue with one of the customers seeing errors as below.

25/10/23 09:40:45:059 GMT] ERROR business.HTMLPageAssetAPIImpl: Unable to find/index [25/10/23 09:40:45:090 GMT] WARN servlet.VelocityServlet: Page '/index' not found [25/10/23 09:40:45:091 GMT] WARN servlet.VelocityServlet: Page '/index' not found

(https://github.com/dotCMS/core/blob/8dd5b7ac2159bf3e50909dca3c47e3f9eac069d6/dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPIImpl.java#L251-L251)

Logger.error(this.getClass(), "Unable to find" + uri);
Better logging be added here to log the host details and language ID for better identification.

### Acceptance Criteria

Better logging functionality added.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://dotcms.zendesk.com/agent/tickets/113869

_No response_

**Comment by waqasakramdot** [comment]
Another customer requested for these error message: https://dotcms.zendesk.com/agent/tickets/116342

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA:
The easiest way to test this is to go to the `Page API - [api/v1/page] / Getting Available Workflow Actions In Page` Postman test and run all the requests in there. But, for the last one -- `Get Workflow Actions1 -- in the JSON body, in the `url` attribute, pass down a non-existing URL. This will return the updated error message in the log.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2c23184**, Docker, macOS 14.5, FF v126.0.1
