### ISSUE TITLE
Rename 'Next Release' label to release label when release runs

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#26547]
Certainly, here's the user story and related information in markdown format:

### User Story
As a dev-ops engineer, I want to modify the release process by changing the current GitHub release process workflow to rename the `Next Release` label to the recently created release label.

### Acceptance Criteria
1. The GitHub release process workflow is updated to automatically rename the label `Next Release` to the label of the most recently created release.
2. This change should take effect immediately after a new release is created.
3. The release label should accurately reflect the content of the release.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links
- [Link to the current GitHub release process workflow]
- [Link to GitHub release label documentation]

### Assumptions & Initiation Needs
- Access to the GitHub repository's workflow configuration.
- Knowledge of GitHub Actions and workflow modification.
- Consistent labeling for releases within the repository.

### Quality Assurance Notes & Workarounds
- Test the modified release process workflow with various release scenarios to ensure the `Next Release` label is correctly renamed to the recently created release label.
- In case of issues, refer to GitHub Actions documentation and seek support from the development team.

### Sub-Tasks & Estimates
- Modify the GitHub release process workflow: 4 hours
- Test and verify the modified workflow: 2 hours

Total estimated time: 6 hours

**Comment by bryanboza** [comment]
This is not working, it just is removing the tag to some ones and leave the others with the label... We need some work here.

**Comment by john-thomas-dotcms** [comment]
Done!
