### ISSUE TITLE
Hide the download button for bundles pushed to static environments

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26542]
### Problem Statement

Users trying to download bundles pushed to static environments 
This results in 500 error as currently these bundles are not downloadable

Hiding the download button for these bundles is the solution to avoid such scenarios.

### Steps to Reproduce

1. Try downloading bundles pushed to static environments
2. This results in a 500 error 

### Acceptance Criteria

Remove the download button for these bundles 

### dotCMS Version

22.03.10
23.01

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1698341701309859
https://dotcms.zendesk.com/agent/tickets/113829

**Comment by AndreyDotcms** [comment]
Screenshots provided by the customer:

![bundle 500](https://github.com/dotCMS/core/assets/127987858/d7aeb8a8-fdc0-409f-8c11-1a619ad55669)
![dl bundle](https://github.com/dotCMS/core/assets/127987858/5a547943-34d4-4a17-82ff-ac61da64057e)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
