### ISSUE TITLE
[UI] Not load the AI extensions if the plugin is not properly installed and configured

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26556]
### Parent Issue
#26495

### User Story
As a user, I want the AI Plugin for the Block Editor to not load if it's not properly installed and configured, ensuring a smooth and error-free experience in the content editing environment.

### Acceptance Criteria
- The AI content and image nodes  should not appear in the Block Editor if  the AI plugin it is not correctly installed and configured.
- The Block Editor should function normally without any disruption or errors due to the AI Plugin not loading.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- Assumption that the plugin has a mechanism to check its installation and configuration status.
- Need for clear documentation on proper installation and configuration steps for the AI Plugin.

### Quality Assurance Notes & Workarounds
_to_define_

Depend of https://github.com/dotCMS/core/issues/26723

**Comment by oidacra** [comment]
Can we use the endpoint directly and if we get a `404` assume the plugin is not installed?. @john-thomas-dotcms @dsilvam

**Comment by john-thomas-dotcms** [comment]
Yes, anything we can do to reliably determine if the plugin is installed.  But we need to make sure it doesn't cause an error in the log if the plugin isn't installed - it should just fail silently.

**Comment by oidacra** [comment]
@hmoreras we need to do a small test for this.

**Comment by oidacra** [comment]
We use `api/v1/ai/image/test` to detect if the plugin is installed. This does not validate if the plugin has the key. We will handle that with an error(retrieve a 500 status). @john-thomas-dotcms @dsilvam

**Comment by hmoreras** [comment]
QA notes:

1. Install the last version of the AI plugin.
2. Add the token key in the apps configuration portlet.
3. Create a content that has a block editor on it, or use one that already have it like BLOG.
4. In the Editor type /ai.
5. AI Content and AI image should be present. 
6. Remove the plugin. 
7. Go to the content an in the editor try to filter by ai like spep 4. 
8. nodes should not be present.

**Comment by dsilvam** [comment]
Passed Internal QA: AI Options not showing when plugin is either stopped or removed.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_52eaaa9**, Docker, macOS 13.0, FF v121.0.1
AI extension not showing after the plugin was stoped.
<img width="1128" alt="Screenshot 2024-01-23 at 9 05 49 AM" src="https://github.com/dotCMS/core/assets/129882031/7019d6ba-bf41-4a5b-a88e-819d7b32cc6d">
