### ISSUE TITLE
Improve performance to the Experiment results end point

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#26550]
### Problem Statement

Right now the Experiment results end point is taking to much time, this is because we are getting all the Event and then calculate success and failures on dotCMS, what we want now is move the most of this calculation to CubeJS and try to get a summary instead of all the Events from CubeJs Server. 

### Steps to Reproduce

- Create an Experiment, no  matter the goal.
- Create a lot of Events (More than 100k), I did it using postman and request directly to JitSu Server.
- Go to the result Experiment Page

### Acceptance Criteria

The Results End Point must we tasted with a lot of data (more than 100k Events) and duplicated this data for each test, we need to make sure that the response time is not duplicated each time the data is duplicated

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by freddyDOTCMS** [comment]
PR com/dotCMS/core/pull/26586

**Comment by bryanboza** [comment]
Fixed, this was tested with the internal servers and the performance increase significantly. We can pass it for now
