### ISSUE TITLE
[UI] Add a Regenerate to the properties of Image Node

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26554]
As a user, I want regenerate the suggested image by the plugin using the same prompt
<img width="975" alt="Screenshot 2023-11-16 at 11 41 42 AM" src="https://github.com/dotCMS/core/assets/1909643/565cf22f-fb2f-4a7b-83a3-98f4baa25d03">

**Comment by oidacra** [comment]
Confirm @john-thomas-dotcms if we need it.

**Comment by john-thomas-dotcms** [comment]
The user must be allowed to regenerate the image when creating the initial image.  Once the user selects "Accept", the image becomes a normal image block, and re-generation will no longer available.

**Comment by john-thomas-dotcms** [comment]
Although the UX design has changed from the image in this card, the regenerate function is available now.

**Comment by dsilvam** [comment]
This do not apply like the card states. Closing it.
