### ISSUE TITLE
Edit Content: Fix Margin and Padding of Columns and Fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26564]
### Problem Statement
In the edit content form, the margin and padding of the columns and fields need to be fixed.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/dae30098-fa89-43d7-a8b0-094557ab540e

### Acceptance Criteria
- Margin between fields should be ALWAYS 24px (1.5rem).

### External Links
N/A

### Assumptions & Initiation Needs
I think we have two choices here:

1. We remove the gap and update the `.field` to be 1.5rem
2. We set the `.field` margon to 0 and use only gap

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
# IQA PASSED

We can see now the form has the correct spacing between them.

https://github.com/dotCMS/core/assets/63567962/9fda5158-0495-4c41-b612-e215e4d74d27

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_4893f5b_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
