### ISSUE TITLE
QA: Investigate and write a plan how to implement security testing in our process 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26588]
### Task

As part of the new plans for the QA department, I want to investigate how to implement the use of Kali Linux as a testing tool, to do a kind of security testing for dotCMS. 

We need to cover all the kind of attacks, cross site scripting etc... 

Note: We have multiple curses and guides available on Udemy. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- Read and investigate the use of Kali Linux 
- Download this distribution 
- Do a kind of demo using the tool 
- Create a text document with a plan with pros/cons to use this tool and how to implement this in our department 

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.kali.org/

**Comment by josemejias11** [comment]
**QA Comment**

Below a first advance on this task.

[Kali Linux Tools](https://docs.google.com/document/d/1TqUjZLYaooP9l_CelEhZOAkBQr4S_4HaTBbRwLLhvMM/edit?usp=drive_link)

[Technical Guide for Security Testing](https://docs.google.com/document/d/1dCWTurxUcecIon97v0vlQ4pr0ExW84WrWipN8XEQFJA/edit?usp=drive_link)
