### ISSUE TITLE
Unable to Lock Pages

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26585]
### Parent Issue

SEO Improvements

### Problem Statement

Functionality is used to prevent simultaneous editing conflicts, but attempts to activate the lock are failing.

### Steps to Reproduce

1. Open the application and navigate to the relevant page editing section
2. Select a page that needs to be locked for editing
3. Attempt to apply a lock to the page to restrict editing access
4. Observe the behavior and any error messages

### Acceptance Criteria

Page should successfully be locked

### dotCMS Version

23.11

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

https://github.com/dotCMS/core/assets/129882031/c149ead6-0971-48a2-add7-88a27b91c3ba

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8a0c462_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
