### ISSUE TITLE
API Token Loading Error with Status 400

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26599]
### Problem Statement

Attempts to load an API token using the endpoint /api/v1/apitoken/remote result in an error with HTTP status code 400 (Bad Request). 

### Steps to Reproduce

1. Add API endpoint: /api/v1/apitoken/remote
2. Get Token
3. Observe the response returned by the server

### Acceptance Criteria

A successful request should return an API token, with a typical HTTP status code of 200 (OK) or a similar success code, depending on the API design.

### dotCMS Version

23.11

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

![Screenshot 2023-11-02 at 10 34 25 AM](https://github.com/dotCMS/core/assets/129882031/594f43be-2a2b-4704-8ceb-0f0e082855ad)

**Comment by wezell** [comment]
@josemejias11 keep in mind, the login you should be using is the admin login on the remote server, not the local server.

**Comment by josemejias11** [comment]
> @josemejias11 keep in mind, the login you should be using is the admin login on the remote server, not the local server.

Hi @wezellm,

Got it, thanks! I did not know that.  👍
