### ISSUE TITLE
Incorrect Redirection from /c/containers to /starter URL

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#26591]
### Parent Issue

Containers

### Problem Statement

The URL endpoint /c/containers is expected to redirect users to /starter.

### Steps to Reproduce

1. Launch the application
2. In the browser, navigate to <application domain>/c/containers
3. Observe the behavior and destination URL

### Acceptance Criteria

Navigating to /c/containers should automatically redirect the user to the /starter URL.

### dotCMS Version

23.11

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by KevinDavilaDotCMS** [comment]
# Pass internal QA
Tested in master

https://github.com/dotCMS/core/assets/144152756/6dfa1ad3-7185-4817-9d58-637c2a55b4c4

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_51c24cb_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
