### ISSUE TITLE
Design System: Absolute overlays overlap navigation

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26603]
### Parent Issue

#25355

### Problem Statement

There is an issue with the absolute items overlapping menu items in several areas of our system, including the Template Builder, Contetype Dialog, new Edit Content portlet, and other locations. This may cause some inconvenience with UI/UX.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/72418962/f2b9e5ee-1724-4bfc-9245-35fa8217ea84

### Acceptance Criteria

Overlapping absolute items with menu items can negatively impact the UX/UI and should be avoided.

### dotCMS Version

`master`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by bryanboza** [comment]
Fixed, tested on master and now I'm unable to reproduce
