### ISSUE TITLE
Dot Field Helper: Text Overflows Dialog

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26602]
### Problem Statement

The styles of the `Dot Field Helper` are broken. When a work is too long, the text overflows the dialog.

### Steps to Reproduce

1. Navigate to "Content Types."
2. Choose "Blog."
3. Click "Edit."
4. Select the "Question Mark Helper" icon within the "URL Pattern" field.
5. Observe the error.

![Screenshot 2023-11-03 at 1 41 22 PM](https://github.com/dotCMS/core/assets/72418962/1b3db32b-24f8-4888-8386-9859baaf020f)

### Acceptance Criteria

The text should not overflow the dialog. 

### dotCMS Version

`master`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by KevinDavilaDotCMS** [comment]
# Passed Internal QA
Tested in master

https://github.com/dotCMS/core/assets/144152756/ae68085c-f802-493d-a938-993ac06454ac

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected. 


![Image](https://github.com/dotCMS/core/assets/2641437/38570961-5480-4601-b3a6-1c75294af424)
