### ISSUE TITLE
Change sort order of site selector search results

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#26614]
## Problem

The site selector only shows a maximum of 15 sites in the list (see https://github.com/dotCMS/core/issues/25429).  There is a search function, but the results of the search function are sorted by the last modification date (oldest at the top), so if a site name is a subset of another site name, it may not be reachable with the site search.

An exact match of a site name will always appear at the top of the list (see ).  But anything short of an exact match will make some sites unreachable with the site selector - and customers may not always know the exact site name.

## Solution

The full solution would be to allow paging in the site selector search results.  However, that would require significant rework of the site selector, which is planned for later (an angular rewrite).  A faster solution is to change the sort order of the search results to string length (ascending), so it shows the shortest match at the top of the list.

This change will require:
1. A modification of the endpoint to allow a sort parameter.
2. Implementation of a sort by length in the endpoint.
3. Update of the UI to call the endpoint with the sort parameter set to string length.
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26615
```

**Comment by wezell** [comment]
closed in favor of #25740
