### ISSUE TITLE
Can't change state of checked out content or where inode is not set 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26616]
### Problem Statement

after pushing, deleting, and re-push the same asset under the live branch for any language several times 
we were getting a 500 with the message `Can't change state of checked out content or where inode is not set `

When performing an update operation on which the contentlet gets replaced a prior archived version  might exist 
Two problems here were spotted. 

1. Sometimes a checkout contentlet lacks of id and if the desired status is live the following publish operation will fail. Therefore a check-in needs to happen in the middle. this is a bit counter-intuitive but the checkout is forcing the generation of a new version. Therefore we need to have a check-in operation
2. Sometimes the archived piece of content is neither live nor working. We need to account for such problems too. the old code would only account for live or working 

### Steps to Reproduce

Use a workspace like this: 
[es-tes.zip](https://github.com/dotCMS/core/files/13283403/es-tes.zip)
and push the files using 
files push /path-to-the-workpsace --removeAssets --removeFolders
Then go to the backend and remove the pushed image 

Repeat the process several times

### Acceptance Criteria

No matter how many times we repeat the process. should always be able to push delete and repush

### dotCMS Version

current master 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment]
Internal QA: PASSED.

The scenario described above is no longer reproduced.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after test multiple times.
