### ISSUE TITLE
Edit Content: Make Binary Field Preview Works with File ContentTypes

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26628]
### Parent Issue

#25445

### Task

As a dotCMS user, I would like the ability to preview the Binary Field with any ContentType, such as "Content", "File", "Page", and so on.

https://github.com/dotCMS/core/assets/72418962/56b9ce0b-675b-411f-873b-31491e0f1cff

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Binary Field preview should work with any ContentType, such as "Content", "File", "Page", and so on.

### Assumptions & Initiation Needs

The backend response might vary depending on the ContentType, which could be the reason for the issue.

**Comment by fmontes** [comment]
Binary:

1. File name is required but not marked as required
2. There is a null in the hint location
3. Hint color and spacing is wrong and we should not show hint below in the jsp

**Comment by fmontes** [comment]
If add a binary + block editor jsp breaks

**Comment by rjvelazco** [comment]
@fmontes I already fixed the bugs in this PR: https://github.com/dotCMS/core/pull/26802

Regarding the `Hint Styles`, those are global for all the fields. There is ticket open to make them match the new design system here: https://github.com/dotCMS/core/issues/26807

**Comment by fmontes** [comment]
Needs work: for some reason this file: http://localhost:8080/dotAdmin/#/c/site-browser/2df50869-bae9-4dcf-b500-68f6d4b8c111

`/application/templates/design.../layout.json`

is not working as code and can't be edited.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_21b5d08**, Docker, macOS 13.0, FF v113.0
