### ISSUE TITLE
Design System: Fix Wrong Dojo Button Hit Area

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26621]
### Parent
[#25355](https://github.com/dotCMS/core/issues/25355)

### Problem Statement
The buttons in dojo hit area are not clickable and users need to hover the text to actually click.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/3b928120-94fd-4b5c-b5f8-32c52ba34ce0

### Acceptance Criteria
The whole button should be clickable.

### External Links
N/A

### Assumptions & Initiation Needs
- The issue is limited to dojo hit area
- Testing on multiple browsers is required

### Quality Assurance Notes & Workarounds
- Test the button on different browsers
- If issue persists, try to hover the text to click

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c74b482_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
