### ISSUE TITLE
Edit Content: Update Binary Field Style - Responsive

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26649]
### Parent Issue

#25445

### Task

We need to update the binary field styles to match the changes.

### Proposed Objective

Please Select

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- The binary field should match the design.
- Should look great on EMPTY state - Reponsive.

![image](https://github.com/dotCMS/core/assets/72418962/b361277d-cbec-4e08-bc52-b34a4c7d97d7)

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- **Figma Design**: https://www.figma.com/file/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?type=design&node-id=479%3A17452&mode=design&t=2TuB9YyKFpEN0gUs-1

- **Prototype**: https://www.figma.com/proto/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?node-id=365-14264&scaling=scale-down&page-id=365%3A14229&starting-point-node-id=365%3A14264&mode=design&t=dBd4KhDyJmk0nuPC-1

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_39ca5c4_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
