### ISSUE TITLE
Global Push must enforce the order on which push sub commands are applied

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26643]
### Problem Statement

if for example, we decide to include a new site folder like this:

```
└── demo2.dotcms.com
│               ├── activities
│               ├── application
│               │   ├── apivtl
│               │   │   ├── search
│               │   │   └── sitemap

```
and assuming the site does not already exist and expecting the CLI to create it 
a few considerations must be taken into account.

The global push must apply the following order when creating items 

1. Push Languages
2. Push Sites
3. Push Content-Types
4. and finally, push Files 

In order for the example from above to succeed the site must be properly created first following the definition of the site in the file `sites/demo2.dotcms.com.json` if present. if not the site should still be created 

Likewise, when the site is created if we want it to use any specific language the language must have been created beforehand

As a side note 
We should probably replace any file that lacks identifiers used to create an element with an updated one containing the identifiers etc. 

### Steps to Reproduce

create a cli workspace
that has a site folder name that does not exist already on dotCMS
and also add the site definition under the site folders. 
you'll see the site gets created. But the cli fails when it reaches the site definition 

### Acceptance Criteria

a coherent order must be used when applying commands.
so that we can use items introduced in a cli-workspace deifinition when pushing or creating new elements 

### dotCMS Version

current master

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Additional note:** The global pull should include a sorting criteria as well.

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by bryanboza** [comment]
We need some work here: 

- We need to define the order to execute the actions, right now if you have a file on working and live folders, we are executing the workflow first on live and then on working. Then the file is leaving on draft instead published.

**Comment by nollymar** [comment]
**Internal QA:** Passed

I tested the global push using multiple sites on different languages.
