### ISSUE TITLE
Edit Content: Create Setting Tab for Binary Field

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26656]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

Create a settings tab for the binary field to allow the user to configure whether they want the Write Code and Import by URL methods.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

We must allow users if they want to write code and import by URL modes.

### Assumptions & Initiation Needs

This new tab will be similar to the `Block Editor` setting tab:

- [Dot Block Editor Settings Tab Component Source Code](https://github.com/dotCMS/core/blob/2eff4cc9bf9ec699d075b4a1c2a668e4583b2ed3/core-web/apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/dot-block-editor-settings/dot-block-editor-settings.component.ts)

![Block Editor Settings](https://github.com/dotCMS/core/assets/72418962/9fdb680e-f890-4756-a9d8-97753e85a29a)

**Comment by fmontes** [comment]
Close in favor of: https://github.com/dotCMS/core/issues/26906
