### ISSUE TITLE
Fix Menu label if we are missing the translation key

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26660]
### Task

Because the menu labels are content and or live in the language.properties, they can get out of sync in different environments.  Same thing happens if we remove tools from the backend, they can still show up with funky names in the front end.

 
![Screenshot 2023-11-13 at 11 06 07 AM](https://github.com/dotCMS/core/assets/934364/296426ef-5d8c-4aaf-b5cf-ad3bfbc24f4f)

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_13c2337_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
