### ISSUE TITLE
Retaining Edit Mode Settings in when you click on "Open In a new tab" 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26679]
### Problem Statement

Users experience a loss of selected settings, specifically language and persona, in dotCMS when switching to a new tab from the edit mode. This issue occurs upon using the "Open In a New Tab" button, leading to a reset of these preferences and necessitating reselection, which hampers user efficiency and workflow continuity.

Also, this is inconsistent because what you have in the selection is not what we are showing on this new tab. 

![image](https://github.com/dotCMS/core/assets/2641437/075f44bc-9f7b-46ea-bbdb-8ea35d765e9b)

### Steps to Reproduce

- Log into the dotCMS backend with appropriate credentials.
- Navigate to the edit mode interface.
- In edit mode, select specific settings such as a particular language and persona.
- Click on the "Open In a New Tab" button to view the content in a new browser tab.
- Observe that the new tab does not retain the previously selected language and persona settings.

### Acceptance Criteria

**Consistency in Settings Across Tabs**: When a user opens content in a new tab from the edit mode, the new tab should retain all the settings (language, persona) selected in the original tab.
**User Confirmation**: Upon clicking "Open In a New Tab", if feasible, a prompt or indication should confirm the retention of settings in the new tab.
**Fallback Mechanism**: In cases where settings cannot be transferred to the new tab, provide a clear message or indication to the user about the need to reselect the settings.
**Documentation Update**: Ensure that the feature's documentation clearly explains how settings are managed when opening content in a new tab from edit mode.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Not happening in UVE.
