### ISSUE TITLE
Unable to add content on second Language to Page Variant

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26683]
### Problem Statement

An error is occurring when a content in a second Language is attempted to be added to a Variant of an Experiment.

### Steps to Reproduce

1. Create page only in English
2. Create content in English
3. Create content in Spanish
4. Add content in English to the page
5. Create experiment
6. Create a variant and edit it and inside the variant change language to Spanish
7. Try to add the content in Spanish

### Acceptance Criteria

This needs to work without issues.

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/26692

**Comment by hmoreras** [comment]
Pass Internal QA: In a page that only has an English version, in an experimental variant, I can add content in Spanish when I switch languages inside the variant - edit mode.

**Comment by oidacra** [comment]
I have not been able to reproduce the behavior:
Variant:
<img width="1830" alt="Screenshot 2023-11-21 at 10 53 20 AM" src="https://github.com/dotCMS/core/assets/1909643/32468492-db91-46a1-ade9-2327b9ba58e1">
<img width="1824" alt="Screenshot 2023-11-21 at 10 53 12 AM" src="https://github.com/dotCMS/core/assets/1909643/ddace8bb-42c0-40eb-9bdd-e140681fe193">


Original:
<img width="1831" alt="Screenshot 2023-11-21 at 10 54 06 AM" src="https://github.com/dotCMS/core/assets/1909643/babececc-5a57-4920-8928-a3cb6bfea1af">
<img width="1823" alt="Screenshot 2023-11-21 at 10 53 45 AM" src="https://github.com/dotCMS/core/assets/1909643/ec9371cf-91be-4203-a3e2-2dd77087b441">

**Comment by bryanboza** [comment]
Fixed, tested again in a fresh env and seems that now it is working , I think the fail was related to a lost of connectivity with the analytics infrastructure. 

**Note to doc:** We have a limitation here and is that you are unable to use content from one variant in another one, even is both are under the same experiment, this is by design and this is ok for V1. @jdcmsd 

Not sure if we need to doc it
