### ISSUE TITLE
Restoring Reorder Rows Functionality in Content Type Editing

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26680]
### Problem Statement
We recently lost the ability to reorder rows while editing a content type. 

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/a978885c-6726-4abb-a95c-e5429dafda1b

### Acceptance Criteria
Bring back reorder rows by drag and drop grabbing the row from the top border.

### External Links
None

### Assumptions & Initiation Needs
We assume that the reorder rows functionality was lost due to a bug or unexpected change in code. We will need to investigate the source of the issue and identify a solution to restore the functionality.

### Quality Assurance Notes & Workarounds
We can manually reorder rows by entering the row numbers in the Row Order fields in the content type editor, but this requires more time and effort than the drag and drop reorder rows functionality. We should strive to identify and fix the underlying bug to restore the expected functionality.

**Comment by erickgonzalez** [comment]
LTS: Only for 23.10 LTS

**Comment by rjvelazco** [comment]
### Needs Work

- Tested on `master`

**Issue**: When moving rows at the top or bottom, the container is not scrolling, making it impossible to reach.

#### Steps to Reproduce

1. Go to Content Type.
2. Select Blog.
3. Take the first row.
4. Try to move it to the end of the list.
5. See the error.

#### Video
https://github.com/dotCMS/core/assets/72418962/d014e83a-4853-4ab6-898c-6bfb02082dfb

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `Master`

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_85402c6_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
