### ISSUE TITLE
Styling and Functionality Issue with Content Types in dotCMS Containers

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26686]
### Problem Statement

In dotCMS, there is a styling and functionality issue when managing content types in containers. Specifically, once all content types are removed from a container, users are unable to associate any new content types with that container. This problem not only affects the usability of the platform but also hinders content management workflows.

https://github.com/dotCMS/core/assets/2641437/4c22b322-e3fd-4a44-a202-8cb46fe38934

### Steps to Reproduce

- Log into the dotCMS backend with appropriate credentials.
- Navigate to the Containers section.
- Select a container and remove all associated content types.
- Attempt to add a new content type to the now-empty container.
- Observe that the interface does not allow the addition of new content types to the container.

### Acceptance Criteria

**Re-association Capability:** Ensure that users can associate new content types with a container even after all existing content types have been removed.

**UI/UX Improvements:** Enhance the styling of the content type association interface to make it clear and intuitive, especially when no content types are currently associated.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Seems we are able to associate new ones, but you need to click in the center,  seems it is working just if you click on the text but the font and background both are white.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3afdf5a**, Docker, macOS 13.0, FF v121.0.1
