### ISSUE TITLE
Block Editor: Fix Scrolling in the "Change To" Dropdown

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26694]
### Problem Statement
In the block editor the "change to" dropdown doesn't allow user to scroll with keyboard arrows or mouse.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/566d742b-bfb8-49cd-bd4c-63a1980f7a96

### Acceptance Criteria
1. Users should be able to scroll through the options of the "Change To" dropdown using the keyboard arrows or the mouse.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_85402c6_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
