### ISSUE TITLE
Setup Analytics infrastructure for Postman tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26691]
### Task

There's the need to test the Experiment Goals and for this we need to setup Analytics infrastructure for Postman tests.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Analytics infrastructure available to be used from Postman tests.

**Comment by john-thomas-dotcms** [comment]
We don't need to set up a separate environment for testing.  Instead, we'll use the existing prod infrastructure, and just ensure the test data has the IDs necessary to separate it from real reports (which it does by default anyway).
