### ISSUE TITLE
Workflow Fire Endpoint Should Support Multiple Date Format

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26704]
### Problem Statement
The workflow action fire endpoint is not saving content when the field date is not in a particular format, but dotCMS have utilities to support multiples dates format.

### Steps to Reproduce
This request

```shell
curl --location --request PUT 'https://demo.dotcms.com/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data '{ "contentlet" : {
  "stInode" : "cebb2c1ede5efc847664c10793bf5d51",
  "languageId" : 1,
  "someDate" : "2023-11-22T14:50:17.050Z"
  }
}'
```

And the response have no time.

### Acceptance Criteria
1. The endpoint should support multiple date formats and use the dotCMS existing utility to achieve that.
2. The content should be saved regardless of the date format used.

### Assumptions & Initiation Needs
It is assumed that the dotCMS existing utility is able to support multiple date formats and that the endpoint can be updated to use it.

### Quality Assurance Notes & Workarounds
The QA team should test that the endpoint is working correctly with different date formats and that the content is saving regardless of the date format. If the endpoint is not working as expected, the workaround is to use the particular date format that the endpoint currently supports.

**Comment by fmontes** [comment]
I ran test with different format and here are the results:

2023-11-22T14:50:17.050Z <-- worked
2023-11-22 <-- worked
11/22/2023 <-- worked
Nov 22, 2023 <-- worked
2023-11-22 14:50:17 <-- worked

22-11-2023 <-- worked but: 5/15/28
2023/11/22 <-- worked but: 7/11/2190
22-11-2023 14:50:17 <-- worked but 5/15/28

20231122T145017Z <-- Unable to convert string to date 20231122T145017Z
22/Nov/2023 <-- Unable to convert string to date 22/Nov/2023
1637598617 <-- Unable to convert string to date 1637598617

**Comment by jdotcms** [comment]
Now we support unix timestamp as part of a date field

**Comment by fmontes** [comment]
Needs work:

If I pass a full timestamp (date and time) the result in the API is `55896-02-28 04:59:24.0` and the field in the HTML is empty.

The same happens if the field is date and time.

To get this timestamp, I use JavaScript `new Date().getTime()` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

**Comment by fmontes** [comment]
Ok this request with ts works now:

```
curl --location --request PUT 'http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGllYzBmY2QyMC1kY2Y0LTQ4MjQtYjhkYS0zZDQyNjM1YTgwMmIiLCJ4bW9kIjoxNzA1NDEyODExMDAwLCJuYmYiOjE3MDU0MTI4MTEsImlzcyI6IjBkMTY5MmQwNmYiLCJsYWJlbCI6InRvayIsImV4cCI6MTgwMDA3OTIwMCwiaWF0IjoxNzA1NDEyODExLCJqdGkiOiJlY2UzOWNkNS1hMzA5LTQ5ZTItODg4Mi0wNzczMDU4OTFlYzMifQ.xHffohmcU-MDRzLF91Mh5DhlkkEH0XnKKU6wGMPEBTc' \
--data '{ "contentlet" : {
  "stInode" : "5067938ad5fb9fd77fe26ed1adba3f9b",
  "languageId" : 1,
  "date" : 1705414566662,
  "dateAndTime" : 1705414566662,
  "time" : 1705414566662
}}'

```

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
