### ISSUE TITLE
Upgrade Tomcat Version

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26722]
### Task

We must upgrade the Tomcat version from 9.0.60 to the latest minor release (~9.0.83~).

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

dotCMS should run smoothly.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114003

**Comment by mbiuki** [comment]
See discussion here: https://dotcms.slack.com/archives/C5LHLNZ25/p1700167187708379

**Comment by sfreudenthaler** [comment]
Question...
Don't think we're going to backport this LTS 23.10 and before

For upgrade to take effect for a specific customer, they would need to upgrade

**Comment by jcastro-dotcms** [comment]
Here's the work that's been done for this upgrade:
- Core PR: https://github.com/dotCMS/core/pull/27153
- The comparison between the previous 9.0.60 version and the new 8.0.84: https://github.com/dotCMS/tomcat/compare/9.0.60...9.0.84

**Comment by bryanboza** [comment]
Fixed, tested on the last master and the server still running normally. No changes detected.

**Comment by bryanboza** [comment]
We need some work here: this is breaking the tomcat dependency and now the JSP portlets are not loading....

**Comment by bryanboza** [comment]
Fixed, here: https://github.com/dotCMS/core/pull/27597

Waiting for the merge!!!

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF . Now I'm unable to reproduce the issue
