### ISSUE TITLE
Resolve a11y problems on Edit Content

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#26728]
### Task

1. Resolve erros on browser in new edit content page
![Screenshot 2023-11-16 at 15 51 50](https://github.com/dotCMS/core/assets/144152756/ae4e2652-967b-4d1b-84c0-d8a6a2c61856)

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Test on `master`

https://github.com/dotCMS/core/assets/72418962/a29bc53a-1d70-4ad4-87c4-30108d6d045c


#### Note for QA: Some fields like the Binary Field, Block Editor, and Check Boxes need some research to improve the `a11y`.

**Comment by rjvelazco** [comment]
### Note for QA

Some fields like the Binary Field, Block Editor, and Check Boxes need some research to improve the `a11y`.
