### ISSUE TITLE
Create a new field type that is an open relationship either all or multiple content types

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#26721]
### User Story

As a user I want to be able to have a single field that relates multiple contentlets of different content types, and allows me to order them for use on the page. Other CMS' have similar functionality, typically called something like a 'Content Picker'

### Acceptance Criteria

1. Have a new field type that can relate to multiple content types
2. Have a way to reference containers for display of those contents

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
Closing as this is now present in the Product backlog for prioritization.
