### ISSUE TITLE
Default signing key

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#26731]
Default Signing Key
The json.web.token.hash.signing.key property allows you to specify your own default signing key to use with the auto login feature. If you do not specify your own key, dotCMS will use the following standard key:

rO0ABXNyABRqYXZhLnNlY3VyaXR5LktleVJlcL35T7OImqVDAgAETAAJYWxnb3JpdGhtdAASTGphdmEvbGFuZy9TdHJpbmc7WwAHZW5jb2RlZHQAAltCTAAGZm9ybWF0cQB+AAFMAAR0eXBldAAbTGphdmEvc2VjdXJpdHkvS2V5UmVwJFR5cGU7eHB0AANERVN1cgACW0Ks8xf4BghU4AIAAHhwAAAACBksSlj3ReywdAADUkFXfnIAGWphdmEuc2VjdXJpdHkuS2V5UmVwJFR5cGUAAAAAAAAAABIAAHhyAA5qYXZhLmxhbmcuRW51bQAAAAAAAAAAEgAAeHB0AAZTRUNSRVQ=

Note: Even when you implement your own [signing key factory](https://www.dotcms.com/docs/latest/authentication-using-jwt#SigningKeyFactory), you should use the same key for all tokens, and therefore you should set your own default signing key. This ensures that JSON web tokens can be created and parsed properly every time the user returns to the dotCMS backend.

Why default signing key is allowed?

---

Rename the key so that it's not as misleading (and therefore less tantalizing for a researcher to report). 
in `SecretKeySpecFactoryImpl.java` currently named `DEFAULT_SECRET`

**Comment by mbiuki** [comment]
Some risks to consider:

1.  If many instances of dotCMS use the same default key, it becomes a predictable target for attackers. This makes it easier for malicious actors to forge valid tokens.
2. Lack of Uniqueness: A default key does not provide uniqueness for each deployment, which is a best practice for security. Unique keys ensure that breaches in one instance do not compromise others.
3. Exposure: If the default key is widely known, it entails the risk of unauthorized access.
4. Compromise of Token Integrity: The security of JWT relies on the secrecy and integrity of the signing key. Using a publicly known key undermines this, potentially allowing attackers to manipulate or forge tokens.

Solution. Create a mechanism to use a custom, unique signing key for each dotCMS installation on the fly and ensure it is kept secure - vault?. Regularly rotate the keys is also a critical part of maintaining security.

**Comment by sfreudenthaler** [comment]
from @wezell 
> false positive.  The key identified was thought to be used, but it was a poorly named variable that we're actually using to make sure the key isn't there.

**Comment by mbiuki** [comment]
https://dotcms.slack.com/archives/C028Z3R2D/p1695752148118199

**Comment by mbiuki** [comment]
This issue I logged is the one: https://github.com/dotCMS/core/issues/26285

**Comment by mbiuki** [comment]
Task
Dummy secrets would need to be renamed from DEFAULT.

See here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/auth/providers/jwt/factories/impl/SecretKeySpecFactoryImpl.java#L22C7-L22C7

**Comment by sfreudenthaler** [comment]
dup #26285
