### ISSUE TITLE
[UI] Change button with new style in Variations

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26738]
### Problem Statement

When the user sees the options to manage the variant is not easy to understand. The weight does not look like a button.

### Steps to Reproduce

- Go to an Experiment
- Add a Variant

### Acceptance Criteria

- Implement a proper way to show all the options to a user.
- Use a text button in the weights.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Screenshot 2023-11-15 at 11 04 00 AM (1)](https://github.com/dotCMS/core/assets/1909643/1f751cd9-0d7e-4502-add4-2be23ff00c23)

**Comment by hmoreras** [comment]
iQA: Add same behavior to Traffic and scheduling.

<img width="1753" alt="image" src="https://github.com/dotCMS/core/assets/31667212/2bc57af8-59e6-4036-a6b6-0a336d0f23f4">

**Comment by oidacra** [comment]
Solved with https://github.com/dotCMS/core/pull/26785/files

**Comment by hmoreras** [comment]
Pass IQA, all links looks the same.

**Comment by bryanboza** [comment]
Fixed, now it looks better, and respect the UI design
