### ISSUE TITLE
CLI: Implement a global pull for files

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#26744]
As a user, I want to be able to pull files for all sites with just one command. Currently, I have to manually run the file pull command for each site I have in the system.

Implement unit and ITs as needed.

**Comment by bryanboza** [comment]
Fixe, tested on master // Docker // dotCLI: dotcms-cli-1.0.0-20231002.205953-1.jar

**Comment by bryanboza** [comment]
We need some work here: 

- After play a little bit with the CLI I noticed we are unable to pull files to a different workspace if you already have configured some specific path. Even if you send the `--workspace` command. 
Here a video trying to explain the case: 

https://drive.google.com/file/d/10Rr-caf6Fdy8Y5mPAQ9BuNqrLig8jSDz/view?usp=sharing

**Comment by fabrizzio-dotCMS** [comment]
Note for QA: The new PR allows using the --workspace modifier to create or use the workspace in the same folder where it is specified. No parent folder discovery happens. So we can have a workspace within a workspace (Which is not a good practice at all) but you have to use the workspace modifier to indicate the folder of use

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
