### ISSUE TITLE
Update GitHub Workflows for dotCMS Docker Image Build Using Maven Outputs

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#26748]
### User Story
As a dev-ops engineer, I want to update the Github workflows that have steps to build and/or push a dotCMS docker image build.

### dotCMS Version
master

### Proposed Objective
Integration

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://drive.google.com/file/d/1r8_FZUYHbwLCM-mMvTyRQchAO4xZUTEq/view?usp=drivesdk

### Assumptions & Initiation Needs
1. Maven build process outputs can be easily integrated into GitHub workflows.
2. Existing GitHub workflows are well-documented.

### Sub-Tasks & Estimates
1. Update GitHub workflows: 2 days
2. Replace explicit Docker actions: 1 day
3. Test and validate Docker image tags: 1 day

### Acceptance Criteria
1. GitHub workflows for dotCMS Docker image builds are updated to leverage outputs from the main Maven build process.
2. Explicit Docker build/push actions are replaced with reusable Maven outputs for building and tagging the Docker image.
3. Docker image is pushed with correct tags derived from Maven build process.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
QA: Failed Internal. Some issues with the resulting image having zero-byte files as consequence.

**Comment by dsilvam** [comment]
Passed IQ: Both remaining issues got solved. Passing this one.
