### ISSUE TITLE
Edit Content: Unify Block Editor Inputs and  Introduce "Field" and "Contentlet" Inputs

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26742]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

We currently have an `input` field for each block editor variable. To get the variables, we need to receive the `field` and the `contentlet` as `inputs`, and extract them from there.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

We need to update the inputs where we are using the `Block Editor`:

1. [New Edit Content - Angular](https://github.com/dotCMS/core/blob/master/core-web/libs/edit-content/src/lib/components/dot-edit-content-field/dot-edit-content-field.component.html)
2. [Old Edit Content - JSP](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp)
3. [Dot Block Editor Sidebar](https://github.com/dotCMS/core/blob/master/core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/components/dot-block-editor-sidebar/dot-block-editor-sidebar.component.html)
4. [Dot Content Compare Block Editor](https://github.com/dotCMS/core/blob/master/core-web/apps/dotcms-ui/src/app/view/components/dot-content-compare/components/dot-content-compare-block-editor/dot-content-compare-block-editor.component.html).

### Quality Assurance Notes & Workarounds

**Note: ** Please make sure the current Block Editor variables work after the update.

**Comment by fmontes** [comment]
Note to QA:

This was just a refactor of code, we tested that all the field variables and remote blocks in the block editor worked as expected.
