### ISSUE TITLE
Reset language filter on Site Browser after Add a Contentlet inside a Page

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#26758]
### Problem Statement

After add a newly created Contentlet inside a Page the filter on the Site Browser is reste to All Language

### Steps to Reproduce

- GO to Site Browser
- Check or set that the Languege is set to Any value different to All.
- Edit any page and add a  Contentlet inside the Page
- Go back to Site Browser and check the filter was changed to All

### Acceptance Criteria

The Language Filter must not changed after add a newly create Contentlet

### dotCMS Version

latest in master

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by oidacra** [comment]
Passed IQA
 Language Filter (in Site Browser)) not changed after adding a newly created Contentlet.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_6a4a847_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
