### ISSUE TITLE
Clear Experiment Variant upon server errors 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26760]
### Problem Statement

If an unexpected error happens when editing a Variant of a Page inside Experiments, the `variantName` is not cleared from sessionStorage, making any further content created to be on that variant, making it not-accessible. 

### Steps to Reproduce

Force a server error when editing a Variant inside an Experiment. 
Then after that, create new Content. 

Content won't be visible. 

### Acceptance Criteria

Upon any server error when creating/editing a Variant inside Experiments, the `variantName` attribute on the session storage needs to be cleared. 

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
Passs Internal QA: Now thw variantName is remove from the sessioNStorage all the time

**Comment by bryanboza** [comment]
This is a little bit complicated to test, It is more backend. We can set this as QA not needed
