### ISSUE TITLE
Browsing for a redirect should show page's URL

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#26770]
### User Story

When you go to the page properties tab and try to set the page redirect, the browser only shows the page's title and description. I think it should also show the URL.

In this screenshot, I'm trying to redirect a page to the index page in this folder. Page Titles and Descriptions can be vague or sound similar to other pages in the section or folder. For Example: Download dotCMS and Download Page. 

<img width="2199" alt="Screenshot 2023-11-20 at 2 03 21 PM" src="https://github.com/dotCMS/core/assets/1561349/f58397ef-0f48-4dab-a51c-217dbb8da0c9">

### Acceptance Criteria

Show URL in the listing

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by wezell** [comment]
We should not be using the "redirect" field any longer - we should use rules to do these types of redirects.  I am going to remove the field from the starter.
