### ISSUE TITLE
Edit Content: Lack of File Extension in Response when Uploading File by URL via Temp API

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26788]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

The response doesn't include the file extension when uploading a file by URL using the temp API. We rely on this information for two purposes:

1. **Show user preview**: We use the file `extension` to provide users with a preview of the uploaded file.
2. **Validate accepted files**: We validate whether the file is of an accepted type by checking the file `extension`.

To upload an image by URL, you can use the following request. After making the request, you will be able to see the backend response:

```bash
curl --location 'https://demo.dotcms.com/api/v1/temp/byUrl' \
--header 'Origin: https://demo.dotcms.com/' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=848F60EDEF9BA94FBEC1802B3D242BAC; access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3MTgxNjdjOC1jN2ZmLTQyYzAtOWY1MC1mMjdlMjI4NWU2ZTMiLCJ4bW9kIjoxNjk2MDExNjQwODg5LCJzdWIiOiJkb3RjbXMub3JnLjEiLCJpYXQiOjE2OTYwMTE2NDAsImlzcyI6ImY2MmJhMDJhM2UiLCJleHAiOjE2OTYwOTgwNDB9.EjEFk0Q-BTVr1pkjfXVTDMZkbKV01EkZWlMvWkTX5bc' \
--data '{
    "remoteUrl":"https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80"
}'
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

 If the external URL provided in the request body does not include the file extension, we should still be able to determine the file extension.

**Desired Response** 

```json
{
    "tempFiles": [
        {
            "fileName": "photo-1575936123452-b67c3203c357.png",
            "folder": "",
            "id": "temp_0e2c70590a",
            "image": false,
            "length": 99768,
            "mimeType": "image/png",
            "referenceUrl": "/dA/temp_0e2c70590a/tmp/photo-1575936123452-b67c3203c357",
            "thumbnailUrl": null
        }
    ]
}
```

**Current Response** -Missing Extension-

```json
{
    "tempFiles": [
        {
            "fileName": "photo-1575936123452-b67c3203c357",
            "folder": "",
            "id": "temp_0e2c70590a",
            "image": false,
            "length": 99768,
           "mimeType": "image/png",
            "referenceUrl": "/dA/temp_0e2c70590a/tmp/photo-1575936123452-b67c3203c357",
            "thumbnailUrl": null
        }
    ]
}
```

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_ a66d047`]

### Video

https://github.com/dotCMS/core/assets/72418962/d782a6f3-8de2-4f39-913b-adf63fde04cb

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Postman
