### ISSUE TITLE
We don't update the Folder name on the browser 

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#26782]
### Problem Statement

When you change the name of a folder on the browser tree, we don't update it. See screenshot.

The folder was originally called "starter." I renamed it to dotcms, but the tree still shows  "starter."

![update-folder-name](https://github.com/dotCMS/core/assets/1561349/30ee0109-d6d2-40b7-a849-019074d50ce5)

### Steps to Reproduce

1. Goto the browser
2. right click on a folder and click Edit Folder
3. Change the name and hit save
4. The result folder name is changed, but the tree is not updated. Not even when you refresh the screen or clear the cache

### Acceptance Criteria

Folder name changes when you edit it

### dotCMS Version

23.10.24

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
@fishsmith can't reproduce this in our 23.10.24 QA server nor demo.

https://github.com/dotCMS/core/assets/5278970/809c719b-f50c-4488-b88d-a5304216dc7b
