### ISSUE TITLE
Edit Content: Add JSON Field

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26792]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

As a user, I want to have access to the JSON field in the new `Edit Content`.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The new JSON Field should allow the user to create JSON Objects.

### Assumptions & Initiation Needs

We need to configure Monaco Editor to set the highlight for JSON syntax.

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master

https://github.com/dotCMS/core/assets/144152756/a8011125-93c2-4d1c-b9db-d65557aa8d08

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a7af331_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
