### ISSUE TITLE
Unable to compare history of older versions (Older than latest 20)

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26815]
### Problem Statement

When trying to compare the history of older versions.
The drop-down populates only the latest 20.
If we are trying to compare with older versions using the compare option available (It gives no result and is blank).

### Steps to Reproduce

Adding a video recording from the demo

https://github.com/dotCMS/core/assets/139247809/176a3d7d-e35b-4f19-9505-c685f3cb2bff

/api/v1/content/versions?identifier=5c011d0f871d54af49a77a7b65a213ba&groupByLang=1
Gives only results of the latest 20 but not all versions (This has to be matched with the FE history tab).

### Acceptance Criteria

User should be able to compare with older versions: this will be achieve by clicking the compare button in the history tab.

### dotCMS Version

22.03
23.01

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1701100290496229
https://dotcms.slack.com/archives/G01N0AU1NUC/p1701110596817649

https://dotcms.zendesk.com/agent/tickets/113986

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_ad285d0**, Docker, macOS 13.0, FF v121.0.1
