### ISSUE TITLE
"Are you sure you want to close the editor?" appears even when no content was changed, nothing was clicked.

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26814]
### Problem Statement

"Are you sure you want to close the editor?" appears even when no content was changed and nothing was clicked.

This prompting works as expected for all other content types except for Page content Content Type

### Steps to Reproduce

Attaching a video 

https://github.com/dotCMS/core/assets/139247809/9a4d0eca-3c48-4bdd-b76c-d6998d4addea

### Acceptance Criteria

If you open content from the content search screen and close it, we need to be able to close it without asking for changes because you have everything as the original.

### dotCMS Version

23.01.9

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/G01N0AU1NUC/p1701098251741019
https://dotcms.slack.com/archives/G01N0AU1NUC/p1701102531636229

https://dotcms.zendesk.com/agent/tickets/114200

**Comment by prestonso** [comment]
Closing as this will be accounted for in the Edit Content Enhancements epic.
