### ISSUE TITLE
Change order of config precidence

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26825]
### Task

We implemented the ability to set config properties via the db.  We need to update the order of precedence of the db config and make sure that anything configured via environmental variable takes precedence over what is configured in the DB.

### The order of precedence should be 
1. ENV Variable
2. DB
3. dotmarketing-config.properties

### Proposed Objective

Please Select

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

If you set a config variable via env variable, and then set the same variable differently in the db, the env variable should still be respected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_cf3883d**, Docker, macOS 13.0, FF v121.0.1
