### ISSUE TITLE
Edit EMA: Add Menu to Select Page Language

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#26821]
### Parent Issue

#26644

### User Story

As a Client I want to be able to change the language of my page, so I can edit the content for any language that I use to publish my content.

### Acceptance Criteria

- We should be able to see a button that opens a menu with the possible languages.
- We should be able to select a language from that menu.
- We should be able to see the language id on the query params of the page.
- We should be able to see the proper page for the language we selected.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- We should use this component for showing the list and filtering https://primeng.org/listbox 
-  We should use this component to show and hide on command https://primeng.org/overlaypanel
- [Figma prototype](https://www.figma.com/proto/trbwjLuf5F6KaU1rFucNeg/Edit-Page?page-id=1902%3A6704&type=design&node-id=1909-28315&viewport=-4440%2C653%2C1&t=dXS6aDZhnpbb3rgx-1&scaling=scale-down&starting-point-node-id=1909%3A28315&mode=design)
- Endpoint `/api/v2/languages`

**Comment by fmontes** [comment]
Needs work:

1. Should close on select
2. Should show selected option when get from URL

We might consider to use autocomplete here.

**Comment by zJaaal** [comment]
We addressed those issues in this PR https://github.com/dotCMS/core/pull/26877 because we decided that Persona Selector and Language Selector should have the same look.
