### ISSUE TITLE
Apps List Portlet Scrolling on Smaller Screens

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26834]
### Problem Statement
Currently, the apps list portlet doesn't scroll on smaller screens.

### Steps to Reproduce
1. Open dotCMS on a smaller screen
2. Navigate to the apps list portlet
3. Observe that the portlet does not scroll

### Acceptance Criteria
Portlet should scroll accordingly when opened on smaller screens.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
I think I fix this, please test first.

**Comment by rjvelazco** [comment]
@fmontes Yes, it was already fixed!

- Tested on Docker Image: `dotcms/master_4a3fb81`

### Video

https://github.com/dotCMS/core/assets/72418962/072c4b8d-7cd9-4118-b5b9-721ac65ce0da

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_c4e5541**, Docker, macOS 13.0, Safari 17.3

Failed testing on Safari 17.3

**Comment by fmontes** [comment]
@josemejias11 @bryanboza we don't support Safari: https://www.dotcms.com/docs/latest/requirements

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c4e5541**, Docker, macOS 13.0, FF v121.0.1

**Comment by erickgonzalez** [comment]
This was fixed inside another fixed and Freddy doesn't recall when or how.
