### ISSUE TITLE
[UI] Implement Handle Errors from endpoint

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26853]
### Parent Issue
#26495 

### User Story
As a user, I wish to visually see when the image generation process fails, enabling me to quickly understand and respond to any issues that occur during this process.

### Acceptance Criteria
- Implement a clear visual indicator in the UI for when the image generation fails.
- Implement the design from UI in Figma
- Users should be able to understand the nature of the error from the visual indicator.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="792" alt="Screenshot 2023-11-30 at 11 34 55 AM" src="https://github.com/dotCMS/core/assets/1909643/58d54637-db70-42da-bc29-96a3a0049d13">

### Assumptions & Initiation Needs
- Assumes that the current system does not have sufficient visual indicators for image generation errors.
- Requires access to the UI design and development resources to implement the visual indicators.

**Comment by oidacra** [comment]
Blocked by https://github.com/dotCMS/core/issues/26851

**Comment by dsilvam** [comment]
Passed Internal QA: Error message displayed to the user when setting an invalid key and attempting to generate either AI Content or AI Image blocks.

**Comment by josemejias11** [comment]
**Approved with Note**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
UI for the error handling looks quite different to the proposed one
<img width="1281" alt="Screenshot 2024-01-23 at 1 06 11 PM" src="https://github.com/dotCMS/core/assets/129882031/e8acc358-8617-4fdb-8349-deff83501eae">
