### ISSUE TITLE
CLI: Pushing files whose name contain whitespaces fail

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26879]
### Problem Statement

Using the GHA, I tried to push a folder with files whose filenames contain whitespaces and special characters but it failed with the error shown in the image below
![Screenshot 2023-12-04 at 12 33 47 PM](https://github.com/dotCMS/core/assets/8741395/95df8897-fa44-4962-b6d9-04cf9e195997)

### Steps to Reproduce

Ask me for the list of files to be pushed.

### Acceptance Criteria

- [ ] The push operation should not fail, otherwise please update the doc specifying the naming convention supported.
- [ ] We should support pulling/pushing files or folders that contain unicode characters

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** needs work

I have tested with several files and folders with special characters using the GHA. The folders are pushed empty.

This is what I have in my repo:


![Image](https://github.com/dotCMS/core/assets/8741395/f22cf31b-1e7d-45e9-b8cb-e25f602898cd)



This is what I see in my server:


![Image](https://github.com/dotCMS/core/assets/8741395/83e9f122-0fc7-4606-902c-ccf174e08d71)



I have attached both folders for future reference



[live files.zip](https://github.com/dotCMS/core/files/14464807/live.files.zip)

**Comment by jgambarios** [comment]
After some testing, we found out that the test files mentioned in the previous comment are rejected by the dotCMS security layer. Therefore, in this particular case, it is the dotCMS core that does not support these files, not an issue with the CLI. During the product owner meeting, it was decided that supporting the characters in those files will not be addressed at the moment.

**Comment by nollymar** [comment]
Considering @jgambarios' comment, I think we're good passing the Internal QA

**Comment by bryanboza** [comment]
Fixed, tested on the latest CLI and now I'm unable to reproduce the error 


![Image](https://github.com/dotCMS/core/assets/2641437/fd283d78-91b9-4c56-904a-0b10d8f087f4)

**Comment by bryanboza** [comment]
We need to replace some special characters as we do in the backend side... Like the (")

We are allowing to upload this from CLI and is causing when you try to open the file 
![Image](https://github.com/dotCMS/core/assets/2641437/f3b3c2f7-97f7-4efb-a4f7-1deb9fc50015)

**Comment by fabrizzio-dotCMS** [comment]
The issue is that the admin basically replaces certain characters they don't like when uploading files. It doesn't reject the file; it simply changes the name by removing what it doesn't like.

The problem with the CLI is that it allows uploading files with those characters that the admin removes. Although it uploads fine, it breaks the admin when the file is opened.

During the meeting, it was said that the CLI should NOT do the same, i.e., it should not just change the name and be done with it, as that would cause conflicts. It was said that the CLI should apply the regex or whatever is applied to the file name, and if the name after validation is different from the original name, it should fail because it has unsupported characters. Then it should return an error message saying the name has invalid characters or something similar.

**Comment by fabrizzio-dotCMS** [comment]
here's a user friendly list with all the illegal characters that we should probably add to the documentation

```
List of Illegal Characters:
----------------------------
Character: " (ASCII code: 34)
Character: < (ASCII code: 60)
Character: > (ASCII code: 62)
Character: | (ASCII code: 124)
Character: NUL (ASCII code: 0)
Character: SOH (ASCII code: 1)
Character: STX (ASCII code: 2)
Character: ETX (ASCII code: 3)
Character: EOT (ASCII code: 4)
Character: ENQ (ASCII code: 5)
Character: ACK (ASCII code: 6)
Character: BEL (ASCII code: 7)
Character: BS (ASCII code: 8)
Character: HT (ASCII code: 9)
Character: LF (ASCII code: 10)
Character: VT (ASCII code: 11)
Character: FF (ASCII code: 12)
Character: CR (ASCII code: 13)
Character: SO (ASCII code: 14)
Character: SI (ASCII code: 15)
Character: DLE (ASCII code: 16)
Character: DC1 (ASCII code: 17)
Character: DC2 (ASCII code: 18)
Character: DC3 (ASCII code: 19)
Character: DC4 (ASCII code: 20)
Character: NAK (ASCII code: 21)
Character: SYN (ASCII code: 22)
Character: ETB (ASCII code: 23)
Character: CAN (ASCII code: 24)
Character: EM (ASCII code: 25)
Character: SUB (ASCII code: 26)
Character: ESC (ASCII code: 27)
Character: FS (ASCII code: 28)
Character: GS (ASCII code: 29)
Character: RS (ASCII code: 30)
Character: US (ASCII code: 31)
Character: : (ASCII code: 58)
Character: * (ASCII code: 42)
Character: ? (ASCII code: 63)
Character: \ (ASCII code: 92)
Character: / (ASCII code: 47)

```
Too long to be included as an Error message

**Comment by dcolina** [comment]
Internal QA: Passed.

Steps followed for the test.
Using GitHub Actions and dotCLI:

**Environment configuration**

- Create a new repository called `white-spaces-test` and clone it.
- Set the variables required by the actions in the new repository.
- Enable permissions to push the repository through GitHub Actions.
- Configure the new repository with the GitHub Actions seed to have the flow that allows synchronizing changes in our `dotCMS` instance.

**Test**

- Login against the dotCMS instance through `dotcli login`.
- Within the new repository, execute the `dotcli pull` command to download the workspace of the dotCMS instance against which you have logged in.
- Create a new folder with the name `kings league` in the directory
`white-spaces-test/files/live/en-us/demo.dotcms.com/images/gallery/kings league`
- Copy image files inside this folder
- Run the git add command. to include the files to staging
- Run git commit with a descriptive message
- Finally, run the git push command.

After the execution of the git push command, the execution of the GitHub Actions was triggered and it can be seen in the `Run dotCMS CLI` step that the push command has been successfully executed.

Then we can observe our dotCMS web instance to see the changes executed via GitHub Actions.

![Image](https://github.com/dotCMS/core/assets/29883881/5e696611-3bfe-4f50-b027-342b7df6d2c6)
![Image](https://github.com/dotCMS/core/assets/29883881/aca728be-946b-4505-8f3d-9932aaa442f2)

You can see the path of the image that everything is right.

**Comment by bryanboza** [comment]
Fixed, tested on master and the last CLI version and now we are handling files and folders with blank spaces in the name.
