### ISSUE TITLE
GraphQL Dates not using the right format

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26890]
### Problem Statement

When using GraphQL to pull up Date Fields, the format is wrong.

### Steps to Reproduce

1- Navigate to the GraphQL Portlet
2- Run the following query:
```
query ContentAPI {
  BlogCollection(query: "", limit: 1, offset: 0, sortBy: "score") {
    title
    modDate
    postingDate
  }
}
```
3- Check the date format, for modDate comes as it should but Date Fields don't:
```
{
        "title": "test blog new",
        "modDate": "2023-12-05 21:35:04.675",
        "postingDate": "Tue Dec 05 21:34:00 UTC 2023"
      },
```
### Acceptance Criteria

Date Field format should be the same as the modDate

```
{
        "title": "test blog new",
        "modDate": "2023-12-05 21:35:04.675",
        "postingDate": "2023-12-05 21:34:00.000"
      },
```

### dotCMS Version

23.01 +

### Proposed Objective

Customer Success

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114381

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_cf9b773**, Docker, macOS 13.0, FF v113.0
<img width="1134" alt="Screenshot 2024-01-10 at 9 31 06 AM" src="https://github.com/dotCMS/core/assets/129882031/898d2a48-73a1-408e-9c84-05131fc00fd7">
