### ISSUE TITLE
Suggested Improvements for Simple Widget/Widget Code fields

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#269]
Suggestion for improving simple widgets and the Widget Code field on widget structures in the following ways:

Here is a simple mockup: http://i1174.photobucket.com/albums/r618/dean_dotcms/SimpleWidgetImprovements.jpg

1) We make the box expandable lengthways the way that a wysiwyg is expandable
2) We offer client some syntax highlighting
3) We offer a way to search the codeshare site and/or documentation site for help (this would popup browser window with listing of results that lead to the appropriate detail pages on the codeshare/doc sites)

**Comment by wezell** [comment]
adding syntax highlighting #7421

**Comment by wezell** [comment]
Code highlighting done in 3.6
