### ISSUE TITLE
Edit Content: Investigate how the `Assign and Comment` option in a Workflow Action works

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#26903]
### Parent Issue

#25445 

### Task

We need to do some research on how the `Assign and Comment` option in a Workflow Action works as we move to the new Contentlet Edit mode built 100% on Angular. The existing code must be analyzed in order to determine whether new endpoints must be created or not.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
@jcastro-dotcms Let's timebox this to 2-3h and see where we can get.

**Comment by jcastro-dotcms** [comment]
### How the pop-up dialog works
Every action in a Workflow is looped and displayed to the user in the following code:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/contentlet_actions_inc.jsp#L233

Clicking a button -- i.e., Workflow Action -- has the option to display a second dialog based on the criteria defined in this line:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/contentlet_actions_inc.jsp#L241

Which means that, if at least one condition is met, such a dialog will show up if the Workflow Action:

- Has a Push Publishing Actionlet.
- Is assignable.
- Is commentable.
- Has a Move Actionlet BUT the destination path is not set yet.
- There's custom code set in the Actionlet.

The method that will be called is located here:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet_js_inc.jsp#L823

And, if the Workflow Action is "popupable", then the `PushHandler.js` file will take care of displaying the dialog:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet_js_inc.jsp#L842

Where information such as the Push Publishing environments and the Role Read Store is retrieved:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/dotcms/dojo/push/PushHandler.js#L192

Finally, it calls the `show` method in this file:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/dotcms/dijit/RemotePublisherDialog.js#L25

And dispatches an Angular Dialog event which takes care of accepting user input:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/dotcms/dijit/RemotePublisherDialog.js#L154

**Comment by jdotcms** [comment]
How to do a comment

On the Action
<img width="518" alt="Screenshot 2023-12-12 at 12 02 59 PM" src="https://github.com/dotCMS/core/assets/19578350/75f3d9a4-b8cd-479a-85ab-1b11f7fb5cc2">

As a Json:
<img width="777" alt="Screenshot 2023-12-12 at 12 03 14 PM" src="https://github.com/dotCMS/core/assets/19578350/66ccb2a5-aaed-4eba-acf5-6ce268856df8">

How to call it
```
curl --location --request PUT 'https://demo.dotcms.com/api/v1/workflow/actions/2766135b-f003-4738-8e94-e7b69f41f9d4/fire' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data '{
    "comments":"This is a Test title comment test",
    "contentlet" : {
        "contentType":"webPageContent",
        "contentHost":"demo.dotcms.com",
        "title":"Test Title",
        "body":"Test Body"
    }
}'
```

Will looks such as this as a result on Task Porlet
<img width="1592" alt="Screenshot 2023-12-12 at 12 14 27 PM" src="https://github.com/dotCMS/core/assets/19578350/b3d51e65-5b54-4747-ab55-a11f0c3f932d">

**Comment by jdotcms** [comment]
If you want to do assign, simple version

<img width="500" alt="Screenshot 2023-12-12 at 12 18 12 PM" src="https://github.com/dotCMS/core/assets/19578350/2cf64e7f-4426-412c-b6c4-b4c8c7f197c7">

The json looks like
<img width="560" alt="Screenshot 2023-12-12 at 12 18 36 PM" src="https://github.com/dotCMS/core/assets/19578350/8f3bea4b-7118-4c4b-8b39-ec28b6d070d7">

The call will looks ike
```
curl --location --request PUT 'https://demo.dotcms.com/api/v1/workflow/actions/2766135b-f003-4738-8e94-e7b69f41f9d4/fire' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data '{
    "assign":"1cad5929-b42d-4049-b76e-3ce39e042574",
    "contentlet" : {
        "contentType":"webPageContent",
        "contentHost":"demo.dotcms.com",
        "title":"Test Title3",
        "body":"Test Body"
    }
}'
```

And finally the result will be

<img width="1498" alt="Screenshot 2023-12-12 at 12 20 54 PM" src="https://github.com/dotCMS/core/assets/19578350/cdd280a4-432b-4340-8463-54ff2d8b5f81">

**Comment by jdotcms** [comment]
if you select a role instead of an user
<img width="488" alt="Screenshot 2023-12-12 at 12 51 55 PM" src="https://github.com/dotCMS/core/assets/19578350/f597d746-f9bb-4b6d-aea1-c042160cdbe8">

the json looks like
<img width="522" alt="Screenshot 2023-12-12 at 12 52 11 PM" src="https://github.com/dotCMS/core/assets/19578350/cdedba2f-f033-4996-8b79-6cb1ccaf1e08">
 the rest is similar to the previous example
