### ISSUE TITLE
Edit Content: Develop Key/Value Field

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#26904]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### User Story

As a dotCMS user, I want to be able to add non-structured information to my content using a Key/Value Field, so I can conveniently store and retrieve additional information associated with my content.

### Acceptance Criteria

- Users should be able to add multiple key-value pairs.
- Users should be able to edit and delete existing key-value pairs.
- The `Key/Value` Field component should be integrated into the Edit Content Library.
- The `Key/Value` Field should provide a convenient way to add and manage non-structured information.
- The `Key/Value` Field should support a variety of data types for both keys and values.
- The `Key/Value` Field should be customizable and adaptable to different content types and use cases.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

- The dotCMS team can reuse the existing Key/Value Field component located at https://github.com/dotCMS/core/blob/master/core-web/apps/dotcms-ui/src/app/view/components/dot-key-value-ng/dot-key-value-ng.component.ts.
- Some refactoring may be required to integrate the component into the Edit Content Library and align with dotCMS standards and requirements.
- The development team has access to the necessary resources and documentation to extract and modify the logic of the existing component.
- We may need to implement the `ControlValueAccessor`.

### Sub-Tasks & Estimates

- Extract the logic of the existing Key/Value Field component
- Refactor the component to align with dotCMS standards
- Integrate the component into the Edit Content Library
- Test the functionality of the Key/Value Field
- Perform code review and address any necessary changes

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master, in the three cases: EditContent, EditContent Field Variables, Apps => Velocity Secrets

https://github.com/dotCMS/core/assets/144152756/ca5d4f99-26bf-47ad-8f15-9f3b40255ffc
