### ISSUE TITLE
Edit Content: Add Settings to Binary Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26906]
### Parent
#25445 

### User Story
As a content editor, I want to be able to apply settings to binary fields, so I can control the behavior easily.

```[tasklist]
### Tasks
- [x] Able to set accept, import from URL, code and specify file name in the code
- [x] Field variable called `systemOptions` to store all settings in one place
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
<img width="669" alt="image" src="https://github.com/dotCMS/core/assets/751424/0be39d39-e27e-466d-8e75-321d3c10f7d7">

[Figma](https://www.figma.com/file/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?type=design&node-id=2537%3A18224&mode=dev&t=oIXlAG7q8dGzcKVd-1)

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by rjvelazco** [comment]
### Failed Internal QA

- Tested on Docker image: `dotcms:master_93e976d`

**Steps to reproduce**
1. Disable the `File Name` option and enable the `editor` option.
2. Try to save.
3. See the error.

#### Video
https://github.com/dotCMS/core/assets/72418962/b46e1b00-d8d0-4962-b723-dcacb3963e80

Also, check out the HTML. There is a `type="text" />` as a text below the file name input.

#### Screenshot

![text below the file name input](https://github.com/dotCMS/core/assets/72418962/83c4e20f-83cf-456c-9fa7-016747ca5037)

**Comment by fmontes** [comment]
I forgot to add this in the ticket but: we need to have all this settings in `true` by default. cc: @zulqarnainvd

**Comment by zJaaal** [comment]
We decided to roll back the option to enable/disable the modification of the file name from the code editor in this [PR](https://github.com/dotCMS/core/pull/27585). Here is the ticket that explains this decision further, exactly on the **Notes** section of the comment https://github.com/dotCMS/core/issues/27583.

cc: @bryanboza

**Comment by bryanboza** [comment]
Fixed, according to the last comment we will continue this work on the card #27583. 

We can close this one for now.
