### ISSUE TITLE
Edit Content: Style the dojo custom fields to make it work as good a possible

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#26901]
### Parent Issue

#25445 

### Task

All of these Custom fields needs to look good on the new Legacy Custom field
![Screenshot 2023-12-06 at 16 26 32](https://github.com/dotCMS/core/assets/144152756/18a3d4d8-c1d4-4425-b5ec-12b837437ae7)

```[tasklist]
### Tasks
- [ ] og-preview
- [x] text-count
- [x] color-picker
- [x] url-title
- [x] banner-layout
- [ ] set-template
- [ ] page-layout
- [x] vimeo-search
- [x] geolocation
- [x] youtube-search
- [ ] userID
```

This changes includes
- [ ] Fullscreen
- [ ] Set width/height on field variables
- [ ] Change backgrounds

### Observations
Some Custom Fields needs a File field to work, but now we dont have that field, so first we need to research about File field and then apply the Custom Field

**Comment by fmontes** [comment]
When you do this, don't move the field out of their own content types. Save the changes here in the comments, or maybe you can create a gist.

**Comment by KevinDavilaDotCMS** [comment]
Gist with updated custom fields
https://gist.github.com/KevinDavilaDotCMS/7f68a52b746e2ea71294759410294647
