### ISSUE TITLE
Create a CLI executable for Silicon architecture (aarch64 / arm64) and test it

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#26917]
Create a dotCM-cli executable tailored for Silicon architecture, specifically aarch64/arm64 with native Quarkus packaging procedure, more specifically with GraalVM for native image generation.

**Comment by manuelrojas** [comment]
Internal QA: **Passed**

I was able to download and install `dotcms-cli-1.0.0-SNAPSHOT-osx-aarch_64`

After installing I was able to Login Successfully:

<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/f5c5dce6-5966-47e6-bc0b-6afcdcfd85b7">

Also I was able to see the instance:

<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/b84c7896-8e16-4060-b820-c79f4de51530">

Status command:
 
<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/24218efb-be86-4351-8058-3ff3ce1427f7">

**Comment by bryanboza** [comment]
Fixed, tested on my M2 apple computer and works as expected,
