### ISSUE TITLE
 ERROR util.DotRestHighLevelClientProvider$1  Elasticsearch Attempt #1 : Connection refused

### ISSUE THREAD

**Issue by LukasKuchta** [dotCMS/core#26920]
### Parent Issue

[error.log](https://github.com/dotCMS/core/files/13603100/error.log)

### Problem Statement

I'm trying run the latest version 23.10.24 in my own kubernetes cluster. Pod is running but after while is restarted. I looked at the logs and there are many errors . I attached the error log file for better investigation.

The nodes have 2CPU and 8GB ram. 

### Steps to Reproduce

Make a deployment unit with this container dotcms/dotcms:23.10.24_abd985f
Tray to deploy into kluster
Wait a minute and check wheter dotCMS is runniong or not.

### Acceptance Criteria

Deploy to the cluster and dotCMS will runing and be able to accept user requests

### dotCMS Version

23.10.24

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 1 - Show Stopper

**Comment by LukasKuchta** [comment]
First error inside the log 

`ERROR db.TomcatDataSourceStrategy - ---------- Error getting dbconnection jdbc/dotCMSPool from context.xml
javax.naming.NameNotFoundException: Name [jdbc/dotCMSPool] is not bound in this Context. Unable to find [jdbc].`

**Comment by erickgonzalez** [comment]
Need to run ES and DB containers as well.
