### ISSUE TITLE
Redis Improvements

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26932]
### Task

Currently the Redis only works 1 to 1 (one instance to one redis), we want multiple dotCMSs to one redis (M to 1), to achieve that we need to include a prefix in every single key on redis to identify the instance owner and this is the cluster id

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The entries on the redis should have a cluster prefix in order to be multi cluster.

### Assumptions & Initiation Needs

Redis should be running and configured as part of the cache chain for at least one region

**Comment by fmontes** [comment]
We need to confirm with @erickgonzalez

**Comment by jdotcms** [comment]
Steps to test:
1) run docker compose of this: https://gist.github.com/jdotcms/83e22602d1280b3df6b6aed5252ec696

this will create, dotcms master image + elastic + postgres + redis

2) add a license to get redis available
3) add some contentlets 
4) go to the maintenance portlet and refresh stats

```
<h2 style="outline: none; box-sizing: border-box; margin: 0px 0px 0.2em; padding: 0px; font-size: 22.16px; font-weight: normal; line-height: 25.484px; color: rgb(85, 85, 85); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: left;">Redis Provider</h2>
Region | Size
-- | --
dotCMS: contentletcache | 13


```

**Comment by bryanboza** [comment]
According to the discution with @wezell 

`We shouldn't use the shorty because it's not a UUID. If we wanted to do anything it should be hashed` 

We need some work here.

**Comment by jdotcms** [comment]
done [PR](https://github.com/dotCMS/core/pull/27992/files)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 


![Image](https://github.com/dotCMS/core/assets/2641437/92491d0b-07a5-4820-9516-8fd40d46cf99)
