### ISSUE TITLE
Add Catalina Log Back

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26934]
### Task

Catalina.log has been missing for quite some time.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Navigate to the Log Viewer Tab and you should be able to see Catalina.out.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master**, Docker, macOS 13.0, FF v113.0

Catalina log from my last build on LTS
![Screenshot 2023-12-14 at 12 35 41 PM](https://github.com/dotCMS/core/assets/129882031/77d32446-bdce-445f-9b6d-6059306fa41b)
