### ISSUE TITLE
Mandatory Inclusion of 'dotcms-webcomponents.esm.js' File in DotCMS Docker Image for Frontend Functionality

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26957]
### User Story
As a system administrator, I need to ensure that the Docker image of DotCMS includes the file `dotcms-webcomponents.esm.js` in the folder `/srv/dotserver/tomcat-9.0.60/webapps/ROOT/dotcms-webcomponents`. This file is currently missing, resulting in the inability to use forms on the Edit Page.

### Acceptance Criteria
- The Docker image of DotCMS must contain the file `dotcms-webcomponents.esm.js`.
- The file should be located in the `/srv/dotserver/tomcat-9.0.60/webapps/ROOT/dotcms-webcomponents` directory.
- After deploying the Docker image, forms on the Edit Page in the frontend should be functional.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
![Screenshot 2023-12-08 at 11 47 58 AM](https://github.com/dotCMS/core/assets/1909643/155b8353-ef82-4cd5-b100-524042e66a44)
<img width="1888" alt="Screenshot 2023-12-08 at 11 17 37 AM (1)" src="https://github.com/dotCMS/core/assets/1909643/a5f590f3-6ce2-49c9-a520-553b51552b09">

### Assumptions & Initiation Needs
- Assume that the current Docker image generation process is missing the required file.
- Initiation needs include accessing the Docker image building process and environment for verification and testing.

### Quality Assurance Notes & Workarounds
- Implement checks to ensure the file is included in future Docker builds.
- Investigate the root cause of why the file is currently omitted.

**Comment by dsilvam** [comment]
Passed Internal QA: file included upon docker image generation

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
