### ISSUE TITLE
Metrics: Count non-system fields in Host content type

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26954]
### Parent Issue

https://github.com/dotCMS/core/issues/26943

### User Story

Have the ability to get the count of non-system fields in the Host content type

### Acceptance Criteria

* Have the count of non-system fields in Host content type available in the Metrics endpoint in the Experience plugin. 
* Integration test. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/3

**Comment by dsilvam** [comment]
Note to QA: 
This is the number of fields in the "Host" content type what are deletable.

**Comment by hmoreras** [comment]
Pass Internal QA: after adding / removing fields to the `host` content type the key `SITES_NON_SYSTEM_FIELDS_ON_CONTENT_TYPE` gets updated correctly in the endpoint: http://localhost:8080/api/v1/dotexp/stats , ignoring the row or columns.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now we are counting the ammount of changes on this variable 

`SITES_NON_SYSTEM_FIELDS_ON_CONTENT_TYPE": 10`
