### ISSUE TITLE
Edit EMA: Decouple Edit Page Nav Bar from Router Module

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#26966]
### Parent Issue

https://github.com/dotCMS/core/issues/26644

### Task

The current Nav Bar from Edit Page is tied up to the router of `edit-page` we need to make this component as dumb as possible, to make it more reusable.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- This component should only emit the link we need to navigate.
- This component should take all that it needs through Angular Inputs.
- This component should not handle the logic to create the Nav Bar, it should take the model it needs to render it.
- This component should work exactly as it works right now, but with the advantage of being reusable.

**Comment by zJaaal** [comment]
Closed in favor of this https://github.com/dotCMS/core/issues/26965

**Comment by fmontes** [comment]
We decided not to to the decoupling because it will be take too much time to implement and we have a set date.
