### ISSUE TITLE
Edit EMA: Research about how the old Edit Page Nav Bar works

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#26960]
### Parent Issue

https://github.com/dotCMS/core/issues/26644

### Task

Take notes about how we get to the different portlets/dialogs/side panels, inside the `edit-page`. We need to make a decision of how are we going to implement this Nav Bar based on the result of this ticket.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Timeboxed: 1h

**Comment by zJaaal** [comment]
# FIndings
- The current Nav Bar does not depend on anything but the Router of that portlet. So it can be safe to remade it, since all is handled by the portlets in the routes.
- Since most of the routes are already libraries, we don't have to move anything outside of the `edit-page` but we have to move an small component that holds some [SEO Tools](https://github.com/dotCMS/core/tree/master/core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-page-tools-seo), it looks really self contained so it shouldn't take much time to do it.
- At this point of research, if we are going to re-made the Nav Bar we must re-do two things:
   1. The Nav Bar as UI and logic to conditional render items based on feature flags and license status.
  2. The routing to make it work similar as the current one in `edit-page`
  
## Conclusions
By re-doing the Nav Bar we can save time in moving some services that are contained by the nav bar. Also we have the opportunity to clean some code that is not needed due to new implemented features, as the new Template Builder.

We are also considering the use of side panels as our main tool to render this portlets, therefore by redoing the Nav Bar and the router module, we have more control of the functionality of it and is easier to explore and test this possibility.
