### ISSUE TITLE
GraphQL Cache not working

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26970]
### Task

Make GraphQL Cache work by default and use the cache TTL by default.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Steps To Reproduce:

1- Create a content type named **Nature** with a text field.
2- Create a couple of contentlets
3- Do the following curl:
```
curl --location 'http://localhost:8080/api/v1/graphql' \
--header 'Content-Type: application/json' \
--data '{"query":"{\nNatureCollection(query: \"*\", limit: 10, offset: 0, sortBy: \"score\") {\n    title\n  }\n}","variables":{}}'
```

It should return the created contentlets.
4- Create a new content
5- Do the same query, it should return the same results.

Note: by default the cache is 15s, so steps 4 and 5 must be done within that timeframe.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
