### ISSUE TITLE
SiteSelector not showing all possible sites for limited user

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26980]
### Problem Statement

When a limited user has permissions for specific sites, not all these sites show up in the site selector.
### Steps to Reproduce

1- Create 17 new sites.
2- Create a New User.
3- Create a New Role and Assign to this user.
4- Assign the Browser Portlet to this role.
5- Give permission to the first and last created site.
6- Login as the limited user.
7- Site Selector doesn't show up all possible sites.

### Acceptance Criteria

It should show all sites for which the limited user has permission (limited to 15).

### dotCMS Version

23.01+

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114515

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to see the sites in the site selector when you have the respective permissions as a limited user 


![Image](https://github.com/dotCMS/core/assets/2641437/b904152d-6e9f-46f9-a8b1-5e84990559a8)
