### ISSUE TITLE
Missing Display of API Link Button

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#26982]
### Problem Statement

Problem Statement: API Link Button Not Displaying in dot-edit-page-info-seo Component Due to *ngIf="innerApiLink" Possible Interference

### Steps to Reproduce

Navigate to the edit page component in the application, should be able to copy the API link.

### Acceptance Criteria

The API Link button should be successfully displayed in the dot-edit-page-info-seo component.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Steps I followed:** 
- Make sure the SEO feature flags are enabled
- Go to the Edit page
- Try to copy the URL using the "Copy URL" link

**Comment by bryanboza** [comment]
We still needing some work here: 

![Image](https://github.com/dotCMS/core/assets/2641437/6b17dc56-daf0-45f5-8f0d-3552294215b9)
We don't have the API link on the page header.

**Comment by jgambarios** [comment]
When editing a page, the API link it is visible and working as expected.

![image](https://github.com/dotCMS/core/assets/923947/edc7c461-c6a2-455e-b3fa-c486b10909a9)

**Comment by bryanboza** [comment]
Fixed, tested on release-23.12.21 // Docker // FF
