### ISSUE TITLE
files pull command is not detecting any new files added under a new site folder 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26985]
### Problem Statement

files pull command is not detecting any new files added under a new site folder 

### Steps to Reproduce

1. connect your CLI with an instance running full starter
2. create a brand new workspace by using the global pull  `dot pull `
3. create a new site using the command `dot site create my-brand-new-site.com`
4. within the workspace navigate to `files/working/en-us/`
5. make a directory with the name we used to create the new site `my-brand-new-site.com`
6. make another folder (images) inside of it. And put a jpeg on it.  
7. now come back to the root of the workspace and do `dot files push --dry-run` 
8. You'll see no changes are reported when it should have discovered the file and folders added 

### Acceptance Criteria

new file/folders should always be discovered 

### dotCMS Version

master

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
