### ISSUE TITLE
Set Response Headers Rule Action does not allow double quotes in the value

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#26987]
### Parent Issue

We previously fixed this for single quotes only https://github.com/dotCMS/core/issues/20659 

### Problem Statement

DotCMS Rule "Set Response Header" should, but does not, accept double quote characters in the response header value.

Single quote and double quote characters play different roles in HTTP headers so we need to support both. 

See ['HTTP/1.1' RFC 7230 section-3.2.6](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6) 

```
Field Value Components

   Most HTTP header field values are defined using common syntax
   components (token, quoted-string, and comment) separated by
   whitespace or specific delimiting characters.  Delimiters are chosen
   from the set of US-ASCII visual characters not allowed in a token
   (DQUOTE and "(),/:;<=>?@[\]{}").

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

   A string of text is parsed as a single value if it is quoted using
   double-quote marks.

     quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
     qdtext         = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
     obs-text       = %x80-FF
```

Also, see this note on MDN 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data#directives
<img width="803" alt="Screenshot 2023-12-12 at 10 36 51 AM" src="https://github.com/dotCMS/core/assets/628954/9f125b76-d2c2-4707-bf16-44d34f9ec87d">

### Steps to Reproduce

Try to include `"` in a Response Header string

<img width="909" alt="Screenshot 2023-12-12 at 10 07 49 AM" src="https://github.com/dotCMS/core/assets/628954/826f212c-507f-4377-9e91-bc4c4f8fd4d7">

### Acceptance Criteria

`"` should be accepted.

### dotCMS Version

all

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/27788

**Comment by dsilvam** [comment]
Passed Internal QA: Working as expected. 



![Image](https://github.com/dotCMS/core/assets/1576794/7298f7f7-16b6-4d5d-8951-d5de9e90d11e)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_ed06491**, Docker, macOS 13.0, FF v121.0.1
