### ISSUE TITLE
Maven Build missing RedisSessionManager

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26991]
### Task

We need to add the RedisSessionManager.jar and other required libs to the `tomcat/lib` directory

This can be tested by setting up Redis and testing the RedisSessionManager against it.

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
Basically follow the steps described at: https://github.com/dotCMS/core/tree/master/docker/docker-compose-examples/with-redis-session

**Comment by dsilvam** [comment]
Passed Internal QA: Checked following the steps in the doc from above.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF...

Following the provided steps now this is working using maven.
