### ISSUE TITLE
Adding DEBUG logging to the SASS compilation process

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#27008]
### Task

We need to add DEBUG level logging to the SASS file compilation process in order to provide more details on how dotCMS is handling the request and how the result is generated. This will help diagnose problems in customer dotCMS instances as well.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

After enabling the **DEBUG** level for the `CSSPreProcessServlet` class, you will see a lot more details when trying to load an SCSS file. You can set that level by running the following code in your browser's console:
```javascript
fetch('/api/v1/logger/', {
  method: 'PUT',
  body: JSON.stringify({
    name: 'com.dotcms.csspreproc.CSSPreProcessServlet',
    level: 'DEBUG'
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log) 
```
Using our Demo Site, if you go to this URL:
```
http://localhost:8080/application/themes/travel/css/styles.dotsass
```
You will see the additional **DEBUG** logging now.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Support ticket: https://dotcms.zendesk.com/agent/tickets/114365

**Comment by bryanboza** [comment]
Fixe, tested on master // Docker // FF 

After enable the DEBUG now I have this in the log 
```
testing_pg-dotcms-1         | 17:07:51.534  DEBUG csspreproc.CSSPreProcessServlet - ---- CSS Pre-Process Compiler ----
testing_pg-dotcms-1         | 17:07:51.535  DEBUG csspreproc.CSSPreProcessServlet - -> Original URI = /DOTSASS/application/themes/travel/css/styles.dotsass
testing_pg-dotcms-1         | 17:07:51.535  DEBUG csspreproc.CSSPreProcessServlet - -> File URI     = /application/themes/travel/css/styles.dotsass
testing_pg-dotcms-1         | 17:07:51.535  DEBUG csspreproc.CSSPreProcessServlet - -> Actual URI   = /application/themes/travel/css/styles.scss
testing_pg-dotcms-1         | 17:07:51.536  DEBUG csspreproc.CSSPreProcessServlet - The SASS Compiler generated a null output for file 'demo.dotcms.com:/application/themes/travel/css/styles.dotsass', but cached data can be returned.
testing_pg-dotcms-1         | 17:07:51.536  DEBUG csspreproc.CSSPreProcessServlet - Returning contents of file 'demo.dotcms.com:/application/themes/travel/css/styles.dotsass' [ verbose = false ]
```
