### ISSUE TITLE
Content export with Publish Date Parameter leads to 400 Bad Request error

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#27007]
### Problem Statement

Content export with Publish Date Parameter leads to 400 Bad Request error

### Steps to Reproduce

1. Create a content type with publish and expire date fields set 
![image](https://github.com/dotCMS/core/assets/139247809/c98d465a-6fea-41d8-992c-4b89e3d4d6ab)
2. Create contentlets using the test content type
3. Try to filter the content with date filters and export the content, try using something like this:
 `[01/01/2023 TO 12/13/2023]`
 
![image](https://github.com/dotCMS/core/assets/139247809/e54e2320-65dd-4668-b6d9-6a6d0a539227)

**Note: This is also happening when filtering using Categories**

4. click export, and this results in 400 bad request error 
![image](https://github.com/dotCMS/core/assets/139247809/12cd128f-2fd1-41d5-bb24-f4c765766083)
 

**Second scenario should be fixed**

1. Create content type with a category field, and make it user searchable.
2. Create contents using the content type
3. Attempt to filter the content using over 177 categories, which equates to more than `6584` characters. 
4. click export, and this results in 400 bad request error. 

### Acceptance Criteria

Export of data should be successful even when you filter content regardless the type of field. Let's check:

- [x] Category Field
- [x] Date Field

### dotCMS Version

23.01.8
23.10.24

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114531

**Comment by swicken-dotcms** [comment]
Additional customer hitting this: https://dotcms.zendesk.com/agent/tickets/114193

It appears to happen with more than just the date filter.

**Comment by AndreyDotcms** [comment]
It is important to set the 'user searchable' option for newly created fields, so they can be used in filters.
![image](https://github.com/dotCMS/core/assets/127987858/ab524ecf-3f48-42b8-a79b-6e3473efdda6)

**Comment by erickgonzalez** [comment]
Was able to export content using a date filter and also several categories selected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8aae521**, Docker, macOS 13.0, FF v121.0.1
