### ISSUE TITLE
Eager strategy for system table

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27020]
### User Story

Currently the system table is totally lazy and loads the 404 or hit as soon as they are requested
The idea would be to do a preload eager when the app starts to load in a separated thread the environments and table entries to the cache

### Acceptance Criteria

Avoid many load to the cache on api query

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
in order to test this you can do this
1)
```
insert into system_table(key,value) values ('DOT_ENV_1','DOT_ENV_1_VALUE')
insert into system_table(key,value) values ('DOT_ENV_2','DOT_ENV_2_VALUE')
insert into system_table(key,value) values ('DOT_ENV_3','DOT_ENV_3_VALUE')
```

2) start dotCMS and while until it loads

3) Hit the system cache such as
```
http://localhost:8080/api/v1/caches/provider/Caffine%20Memory%20Cache/keys/system_group
```

Look for the keys: 'dot_env_1', 'dot_env_2', 'dot_env_3'

So, if the keys are on the system cache means the system table has been uploaded in advance

**Comment by jcastro-dotcms** [comment]
### IQA: PASSED
The entries added to the System Table are now loaded eagerly into the cache. You can test it like this:

1. Start up dotCMS.
2. Using the Postman example, create 3 or 4 entris for the System Table.
3. Restart dotCMS.
4. Go to this REST Endpoint to check for all entries of the System Table cache: http://localhost:8080/api/v1/caches/provider/Caffine%20Memory%20Cache/keys/SYSTEM_GROUP . All the entries you added must already be there.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_270ac3c**, Docker, macOS 13.0, FF v121.0.1
<img width="569" alt="Screenshot 2024-03-06 at 10 39 43 AM" src="https://github.com/dotCMS/core/assets/129882031/0881b47e-2345-46ba-862c-15e4f995f551">
<img width="569" alt="Screenshot 2024-03-06 at 10 38 46 AM" src="https://github.com/dotCMS/core/assets/129882031/e1f50128-cc57-412d-bec4-ebfd7c1480b2">
