### ISSUE TITLE
Create a CLI executable for macOS Intel architecture (x86_64) and test it

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27028]
Create a dotCM-cli executable tailored for macOS Intel architecture, specifically x86_64  with native Quarkus packaging procedure, more specifically with GraalVM for native image generation.

**Comment by manuelrojas** [comment]
Internal QA: **Passed**

I was able to download and install `dotcms-cli-1.0.0-SNAPSHOT-osx-aarch_64`

After installing I was able to Login Successfully:

<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/f5c5dce6-5966-47e6-bc0b-6afcdcfd85b7">

Also I was able to see the instance:

<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/b84c7896-8e16-4060-b820-c79f4de51530">

Status command:
 
<img width="948" alt="image" src="https://github.com/dotCMS/core/assets/3438705/24218efb-be86-4351-8058-3ff3ce1427f7">

**Comment by nollymar** [comment]
**Internal QA:** Needs work

When I run the global pull command to push any file, I get this exception: https://gist.github.com/nollymar/e58674b48a8539d9e664c1ac888f032f#file-push-xml-log

I tested with .xml, .txt and svg images, in all the cases I got the same exception.

**Comment by dcolina** [comment]
Sorry, I don't get it. When does the error occur, either after you run the global pull command or after you run the global push command?

**Comment by nollymar** [comment]
**Internal QA:** Passed
