### ISSUE TITLE
Fix AI Plugin Detection for AI Extensions in Block Editor Components (Sidebars)

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27033]
### Problem Statement

The Block Editor now detects if the AI Plugin is loaded. It works in the creation of a page. But when you try to edit content, the extensions of AI Content and AI Image do not work.

### Steps to Reproduce

- Go to Browser
- Select a page with a content created with Block Editor
- Go to Edit
- Try to use the Ai Content or Ai Image extension
- The Extension are not loaded

### Acceptance Criteria

- AI extensions should be visible in the Block Editor when the AI Plugin is installed.
- The system must correctly validate the installation status of the AI Plugin.
- Ensure that the `dot-block-editor-sidebar` and `dot-content-compare-block-editor` components reflect the AI Plugin's status accurately.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1328" alt="Screenshot 2023-12-15 at 4 47 43 PM" src="https://github.com/dotCMS/core/assets/1909643/86b461f0-6c7a-4c80-9854-dcce2cfe4cfd">

### Assumptions & Initiation Needs

- Plugin of AI loaded and working.

**Comment by oidacra** [comment]
Notes to IQA:
Expected behavior: If the plugin AI Plugin was not installed, the Block Editor won't show the AI Extension in Block Editor. 

Where:
We have a Block Editor when you try to create a Page (Blogs use block editor). And in Edit Page when you try to edit the content, the Block Editor Sidebar appears here.

How 
- Go to Pages, and create a page type Blog
- Go to the block editor and try to filter doing `/` AI Extensions (without the plugin won't be there in the list).

With the plugin
<img width="726" alt="Screenshot 2023-12-20 at 11 16 32 AM" src="https://github.com/dotCMS/core/assets/1909643/d4f14bcf-861e-434d-88ea-427335cebc52">

Without the plugin
<img width="539" alt="Screenshot 2023-12-20 at 11 17 59 AM" src="https://github.com/dotCMS/core/assets/1909643/50e69362-b080-4d00-a25d-e5223f424dc5">

Need to test both, creating a post and trying edit the content (They are 2 direferents Block Editors one is a JSP file and the other is an Angular) and both need have the same behaviour.

**Comment by hmoreras** [comment]
Internal Pass: Initially, the AI options do not appear. After setting up the plugin-token, the AI options become visible. If I remove the plugin, they are also removed.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
<img width="1150" alt="Screenshot 2024-01-23 at 10 18 41 AM" src="https://github.com/dotCMS/core/assets/129882031/58c8f99a-f760-47f7-b971-1ad7f1ebc8fc">
