### ISSUE TITLE
Metrics: Count of contentlets in content types with URL maps

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27043]
### Parent Issue

https://github.com/dotCMS/core/issues/27041

### User Story

Being able to retrieve the count of contentlets in content types with URL maps, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the total of contentlets in content types with URL Maps

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR Experience: https://github.com/dotCMS/com.dotcms.experience/pull/2

**Comment by dsilvam** [comment]
Note to QA:
1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting `http://localhost:8080/api/v1/dotexp/stats` 
3. Create a a new Contentlet of a Content-Type which has a URLMap. 
4. Hit the endpoint again and make sure the count increased for the entry `URL_MAPS_LIVE_CONTENTLETS_IN_CONTENT_TYPES_WITH_URL_MAP`

**Comment by hmoreras** [comment]
pass IQA, working as expected with image: master_25f4e64

**Comment by hmoreras** [comment]
pass IQA, working as expected with image: master_25f4e64

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
