### ISSUE TITLE
Metrics: Count of  content types with URL maps

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27042]
### Parent Issue

https://github.com/dotCMS/core/issues/27041

### User Story

Being able to retrieve the count of content types with URL maps, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the  /dotexp/stats Endpoint with the total of Content Type using a Url Map

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR Experience: https://github.com/dotCMS/com.dotcms.experience/pull/4

**Comment by freddyDOTCMS** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting `http://localhost:8080/api/v1/dotexp/stats` 
3. Create a a new  Content-Type filling the Url Pattern and Detail page attribute 
4. Hit the endpoint again and make sure the count increased for the entry `URL_MAPS_CONTENT_TYPES_WITH_URL_MAP`

**Comment by oidacra** [comment]
IQA Passed:
Create a new Content-Type, and with that change the count.

<img width="1425" alt="Screenshot 2023-12-20 at 4 13 24 PM" src="https://github.com/dotCMS/core/assets/1909643/b75c5407-d038-4cc4-8056-0929c292b4cb">


Before:
<img width="658" alt="Screenshot 2023-12-20 at 4 10 23 PM" src="https://github.com/dotCMS/core/assets/1909643/97b9118a-b832-44e9-97b6-68b54198b232">

After:
<img width="644" alt="Screenshot 2023-12-20 at 4 11 23 PM" src="https://github.com/dotCMS/core/assets/1909643/2c54e8f6-a1ed-45df-bd06-a13812ce5c4f">
