### ISSUE TITLE
Metrics: Count URL Map Patterns with more than one variable

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27044]
### Parent Issue

https://github.com/dotCMS/core/issues/27041

### User Story

Being able to retrieve the count of  URL Map Patterns with more than one variable, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the total of  URL Map Patterns with more than one variable

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR Experience: https://github.com/dotCMS/com.dotcms.experience/pull/5

**Comment by freddyDOTCMS** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting http://localhost:8080/api/v1/dotexp/stats
3. Create a a new Content-Type filling the Url Pattern and Detail page attribute, make sure that you use at least 2 variables on the Url Pattern attribute for example '/testing/{title}/{title}'
4. Hit the endpoint again and make sure the count increased for the entry URL_MAPS_COUNT_URL_MAP_PATTER_WITH_MORE_THAT_ONE_VARIABLE

**Comment by oidacra** [comment]
IQA Passed using `master_25f4e64`:
Added
<img width="632" alt="Screenshot 2023-12-20 at 4 34 28 PM" src="https://github.com/dotCMS/core/assets/1909643/4a2344d6-b7d7-4d27-be14-6f18e67a9156">
 
After
![image](https://github.com/dotCMS/core/assets/1909643/03ea4e87-f99d-4468-be16-d569823ad44b)

Before
![image](https://github.com/dotCMS/core/assets/1909643/95adbee0-eb4b-4a57-a18c-15db2859712d)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
