### ISSUE TITLE
Metrics: Count aliases on all Sites

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27055]
### Parent Issue

https://github.com/dotCMS/core/issues/26943

### Task

Add the count of non-system fields in the Host content type to the stats endpoint

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- Have the count of non-system fields in Host content type available in the Metrics endpoint in the Experience plugin.
- Integration test.

**Comment by dsilvam** [comment]
PR Experience: https://github.com/dotCMS/com.dotcms.experience/pull/7

**Comment by dsilvam** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting `http://localhost:8080/api/v1/dotexp/stats` 
3. Include new aliases on existing active Sites.
4. Create a new Site with aliases and activate it.
5. Hit the endpoint again and make sure the count increased for the entry `SITES_ALIASES`

**Comment by oidacra** [comment]
IQA Passed:
Add a new alias to the site.
![image](https://github.com/dotCMS/core/assets/1909643/45b6c213-dce4-489b-a5e3-2417be84b99f)


Before
![image](https://github.com/dotCMS/core/assets/1909643/3bb4d4a4-c746-46b7-8311-5330bdf573f3)

After
![image](https://github.com/dotCMS/core/assets/1909643/1e7fe1c8-68a5-4c82-9b42-df778fb0efcf)

**Comment by bryanboza** [comment]
I'm unable to upload this plugin, after run the "./gradlew jar" and try to upload to the plugin portlet, we are loading the plugin, showing the notification that a **"new plugin has been installed"** but we are not listing as a plugin, also when you hit the url `http://localhost:8080/api/v1/dotexp/stats` this does not exist. 

Tested on master // Docker // FF

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF... 

The previous error was caused by a configuration error with the transaction to maven. Maybe we need to create some doc about it.
