### ISSUE TITLE
Don't save loading nodes in the block editor.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#27051]
### Parent Issue
#26505

### User Story
The loading nodes should not be saved as part of the content in case the user decides to safe the content while waiting the de AI to response. 

### Acceptance Criteria
- When the user save the content the loading nodes should not be part of the content sent in the endpoint. 

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- Assume that the current system supports image regeneration but contains a bug or issue that prevents it from functioning correctly.
- Initial testing and identification of the bug will be required before proceeding with development fixes.

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates
_to_define_

**Comment by hmoreras** [comment]
QA notes: 

You need to have the AI plugin running, in order to generate the loading nodes: 

<img width="275" alt="image" src="https://github.com/dotCMS/core/assets/31667212/f7a9a568-5244-4d3a-b3a0-ed285df0e85c">

- With AI content, select AI content, write a prompt when the response is done, use the option re-generate, that will create a loading node like the following: 
<img width="841" alt="image" src="https://github.com/dotCMS/core/assets/31667212/b410384f-c049-435b-b57d-ba258a9fb157">

- With AI image, select AI Image, write a prompt, and the loading node will be shown in the document, like this one: 
<img width="456" alt="image" src="https://github.com/dotCMS/core/assets/31667212/6931cc18-98ac-47e7-b8af-b1818c380c47">

1. Save the content while the loading nodes are in the document ( don't wait for the response).
2. Close the content and open it again. 
3. No loading nodes should be present in the block editor.

**Comment by dsilvam** [comment]
Passed Internal QA: Loading nodes are not saved when closing the Edit Contentlet dialog either with or without saving the content.
