### ISSUE TITLE
Edit Content: We lose the binary field thumbnail after applying some filter to the image 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27068]
### Parent
#25445 

### Problem Statement

Users are experiencing an issue in dotCMS where the thumbnail associated with an image in a binary field is lost after applying filters to the image. This problem affects the visual representation and quick identification of images, impacting user experience and content management efficiency.

https://github.com/dotCMS/core/assets/2641437/8a2989ef-b1c6-4dc1-8857-a41000d39d62

### Steps to Reproduce

- Log into the dotCMS backend with appropriate credentials.
- Navigate to a content type with a binary field that includes image uploading.
- Upload an image to this binary field and observe the generated thumbnail.
- Apply a filter to the image using the available image editing tools in dotCMS.
- Notice that the thumbnail for the image disappears or fails to update after applying the filter.

### Acceptance Criteria

**Thumbnail Preservation:** Ensure that thumbnails are either preserved or appropriately updated when filters are applied to images in a binary field.
**Thumbnail Regeneration:** If the thumbnail cannot be preserved, the system should automatically regenerate a new thumbnail that reflects the applied filters.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
We needs some work here:
- Once that you edit an image, we are unable to open the editor again

**Comment by fmontes** [comment]
We fixed that here: https://github.com/dotCMS/core/pull/27160

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_693a20f**, Docker, macOS 13.0, FF v121.0.1

I'm not seeing the ' Edit ' tool in the binary field contentlet

<img width="1528" alt="Screenshot 2024-01-16 at 3 55 09 PM" src="https://github.com/dotCMS/core/assets/129882031/3a0ab606-5514-4000-a789-2e8a2cde385c">

**Comment by bryanboza** [comment]
We need some work here: 

- After the last changes we are not detecting the file that you add and we show an error if is required and if not we save just the other fields and when you try to edit the created content the binary is empty 

https://github.com/dotCMS/core/assets/2641437/edf4ff81-3e42-4717-908a-db99969b0295

**Comment by rjvelazco** [comment]
@bryanboza That `issue` was fixed in this PR: https://github.com/dotCMS/core/pull/27358

**Comment by bryanboza** [comment]
Fixed, tested on docker // master // FF

**Comment by bryanboza** [comment]
We are experiencing this error again in the last master version 

![Image](https://github.com/dotCMS/core/assets/2641437/228bd6ee-f2d3-43ad-bff5-5dad315a59f3)
