### ISSUE TITLE
Metrics: Count of  documents in indexes

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27072]
### Parent Issue

https://github.com/dotCMS/core/issues/27070

### User Story

Being able to retrieve the count of Number of documents in indexes, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the total of documents in indexes

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/8

**Comment by freddyDOTCMS** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting http://localhost:8080/api/v1/dotexp/stats
3. Create a new Contentlet
4. Hit the endpoint again and make sure the count increased for the entry SITE_SEARCH_COUNT_INDIXES_DOCUMENT

**Comment by oidacra** [comment]
IQA Passed: 
<img width="1800" alt="Screenshot 2023-12-26 at 12 34 39 PM" src="https://github.com/dotCMS/core/assets/1909643/a82e43b9-61ef-47a7-98d1-3edbfda443de">


After
![image](https://github.com/dotCMS/core/assets/1909643/1d2ea240-2da5-4485-bee5-c9135b043e40)

Before
![image](https://github.com/dotCMS/core/assets/1909643/df0d3eaa-6ebb-4cd7-8ae9-8d5557289ee8)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
