### ISSUE TITLE
Metrics:  Total size of indexes

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27073]
### Parent Issue

https://github.com/dotCMS/core/issues/27070

### User Story

Being able to retrieve  the total size of all indexes, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Total size of indexes

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/8

**Comment by freddyDOTCMS** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting http://localhost:8080/api/v1/dotexp/stats
3. Run a reindex and wait until it finish 
4. Hit the endpoint again and make sure the value for the entry SITE_SEARCH_TOTAL_INDIXES_SIZE must be duplicated

**Comment by oidacra** [comment]
IQA Passed

<img width="1930" alt="Screenshot 2023-12-26 at 12 21 04 PM" src="https://github.com/dotCMS/core/assets/1909643/22dbe42d-dc47-43b7-a11a-9ced26ba733c">

Before
![image](https://github.com/dotCMS/core/assets/1909643/0ab26e85-4745-4a51-b903-9070080a3a66)

After
![image](https://github.com/dotCMS/core/assets/1909643/c640b3b0-4cc0-47ba-b087-f25e435bd358)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 


![Image](https://github.com/dotCMS/core/assets/2641437/5ee9ef1c-bdb1-459a-9a7a-0c906ab500d5)
