### ISSUE TITLE
Metrics: Count of  Site Search indexes

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27071]
### Parent Issue

https://github.com/dotCMS/core/issues/27070

### User Story

Being able to retrieve the count of ES  indexes, and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the total of ES indexes

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/8

**Comment by freddyDOTCMS** [comment]
Note to QA:

1. Install the Plugin. First the fragment and then the actual plugin
2. Make sure you're getting a response when hitting `http://localhost:8080/api/v1/dotexp/stats` 
3. Runa Reindex
4. Hit the endpoint again and make sure the count increased by 2 for the entry `SITE_SEARCH_COUNT_INDIXES `

**Comment by oidacra** [comment]
IQA Passed:
<img width="2705" alt="Screenshot 2023-12-26 at 12 49 52 PM" src="https://github.com/dotCMS/core/assets/1909643/cfcbabe9-fcce-4137-b7b0-f310110ad753">


Before:
![image](https://github.com/dotCMS/core/assets/1909643/473d7a87-a427-4d98-a745-6c55d84ae5bf)

After:
![image](https://github.com/dotCMS/core/assets/1909643/8628a7f1-31ee-425b-83d8-718dac116bf2)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
