### ISSUE TITLE
Create a CLI executable for Linux  architecture (x86_64) and test it

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27087]
Create a dotCM-cli executable tailored for Linux platform, specifically x86_64 with native Quarkus packaging procedure, more specifically with GraalVM for native image generation.

**Comment by dcolina** [comment]
To test linux-x86_64 distribution from MacOS Silicon is necessary to run a ubuntu docker instance as follow:

`docker run --rm -it --platform linux/amd64 --entrypoint bash ubuntu`

Once into the container, you must download the artifact that contains the executable, uncompress and run it.

**Comment by dcolina** [comment]
This is an example of how to test the `dotcms-cli` executable for Linux x86_64 arch.

https://github.com/dotCMS/core/assets/29883881/760bf70e-c4c9-4e39-b193-b1ca0167f7ba

**Comment by fabrizzio-dotCMS** [comment]
The executable presents a problem running the global pull
```
 [1] Sites to pull
████████████████████████████████████████████████████████████████████████████████████████████████████  100%

 Output has been written to [/workspace1/sites].


[ERROR] ❗  Error in command [pull] with message:
  Class com.dotcms.contenttype.model.type.ContentType$ClassNameAliasResolver has no default (no arg) constructor
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); l...
run with -e or --errors for full details on the exception.
root@5946c1cea8fa:/workspace1#
```

**Comment by manuelrojas** [comment]
@dcolina @nollymar 

**Internal QA Approved**, executed the following commands successfully:

`dotcli pull`

![image](https://github.com/dotCMS/core/assets/3438705/a06ea331-1214-4a70-a4bf-ddbfca48af89)

`dotcli login`
`dotcli instance --activate demo`
`dotcli status`


![image](https://github.com/dotCMS/core/assets/3438705/7a0aec76-c924-4eb7-9902-af06467b7e8e)

**Comment by manuelrojas** [comment]
Failed with the *dotcmscli-push*

![image](https://github.com/dotCMS/core/assets/3438705/10006ef4-6e4a-41ee-9533-1fdbafb9feb0)

**Comment by manuelrojas** [comment]
**Passed Internal,** Tested with:

`dotcli pull`

`dotcli push --dry-run`

![image](https://github.com/dotCMS/core/assets/3438705/9aa2d6e3-f9da-4e00-9d06-db86da31fe4f)


`dotcli push`


![image](https://github.com/dotCMS/core/assets/3438705/666f70a7-f4a7-4bf2-a51a-ec4d3098e273)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // [dotcms-cli-1.0.0-20231002.205953-1-linux-x86_64.tar.gz]


![Image](https://github.com/dotCMS/core/assets/2641437/3fd0a33f-d5f2-4341-87ca-7cd37debb147)
