### ISSUE TITLE
Metrics:  Count site properties changed from default values

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27085]
### Parent Issue

https://github.com/dotCMS/core/issues/26943

### Task

Add the count of site properties that changed from default values.
These include:
* Tag storage not set to the default site
* Host thumbnail not empty
* Run Dashboard set to true
* **Extra**: site has any [site variables](https://www.dotcms.com/docs/latest/site-variables) set

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR Experience: https://github.com/dotCMS/com.dotcms.experience/pull/10

**Comment by freddyDOTCMS** [comment]
The count of "Tag storage not set to the default site" is not working.

Steps:

- Start dotcms up with the full starter
- Create a new empty Site, let call it Site2
- Create a new empty Site, let call it Site3
- The value of the Metric 'SITES_NON_DEFAULT_TAG_STORAGE' must be 0
- Change the Tag Store to Site_ from demo.dotcms.com to Site_2.
- Now the value of the Metric 'SITES_NON_DEFAULT_TAG_STORAGE' must be 1
- Change the Tag Store to Site3 from Site_2 to demo.dotcms.com again.
- Now the value of the Metric 'SITES_NON_DEFAULT_TAG_STORAGE' must be 0 again but it is still 1

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Work as Expected

**Comment by bryanboza** [comment]
We need some work here, the **Extra** is not implemented yet...

**Extra: site has any [site variables](https://www.dotcms.com/docs/latest/site-variables) set**

All the properties that I have for sites are those ones: 
```
"SITES_ACTIVE_SITES": 18,
"SITES_ALIASES_ACTIVE_SITES": 2,
"SITES_ALIASES_ALL_SITES": 2,
"SITES_NON_DEFAULT_TAG_STORAGE": 1,
"SITES_NON_SYSTEM_FIELDS_ON_CONTENT_TYPE": 9,
"SITES_RUN_DASHBOARD_TRUE": 0,
"SITES_WITH_INDIVIDUAL_PERMISSIONS": 1,
"SITES_WITH_THUMBNAIL": 0,
"SITE_SEARCH_COUNT_INDICES": 0,
"SITE_SEARCH_COUNT_INDICES_DOCUMENT": 0,
"SITE_SEARCH_TOTAL_INDICES_SIZE": "0b",
```

**Comment by dsilvam** [comment]
Removed "Needs work" based on the discussion with @bryanboza and @john-thomas-dotcms . The extra/optional metric was captured on a new ticket https://github.com/dotCMS/core/issues/27288

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
