### ISSUE TITLE
Create a CLI executable for Windows architecture (x86_64) and test it

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27088]
Create a dotCM-cli executable tailored for Windows platform, specifically x86_64 with native Quarkus packaging procedure, more specifically with GraalVM for native image generation.

**Comment by nollymar** [comment]
This Internal QA is blocked by #27414

**Comment by nollymar** [comment]
For now, we won't provide a Windows executable. As an alternative, a user can use Windows Subsystem for Linux (WSL) to run the CLI.
