### ISSUE TITLE
Metrics: Count of Language variables (old-style and as content)

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27097]
### Parent Issue

https://github.com/dotCMS/core/issues/27095

### User Story

Being able to retrieve the count of Language variables and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the count of Language variables

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/11

**Comment by hmoreras** [comment]
QA: This ticket modify 3 variables: 

`LANGUAGES_OLD_STYLE_LANGUAGES_VARIABLE `: this should increase when adding a new entry in the `Edit Default Language Variables` in the Language portlet ( http://localhost:8080/dotAdmin/#/c/languages ). this is working as it should. 


`LANGUAGES_LIVE_LANGUAGES_VARIABLE` and `LANGUAGES_WORKING_LANGUAGES_VARIABLE`: create a content type with a field of `key/value`. Then create a content and that should increase the variable depending of the state ( publish or working ) of the content.  If you create a new version of that content in other language the variable should not increase the value. 

Currently if a content has one language live and other in working state, it count double, once for each variable, and should just be present in one.

**Comment by hmoreras** [comment]
Pass internal QA, based on my previous comment.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
