### ISSUE TITLE
Metrics: Check if the default language has been changed from English

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27098]
### Parent Issue

https://github.com/dotCMS/core/issues/27095

### User Story

Being able to check if the default language was changed by English and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with a boolean value to report if the default language was changed by English

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/11

**Comment by dsilvam** [comment]
Passed Internal QA: Reporting properly if the Default Language was changed from English.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 
![Image](https://github.com/dotCMS/core/assets/2641437/f530a387-37c2-49e5-9e13-cbb097e08749)
