### ISSUE TITLE
Metrics: Count of content items with non-default Language versions

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27099]
### Parent Issue

https://github.com/dotCMS/core/issues/27095

### User Story

Being able to retrieve the count of content items with non-default Language versions and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the count of content items with non-default Language versions

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/14

**Comment by hmoreras** [comment]
QA notes: the following variables need to be checked: 

`CONTENTLETS_WORKING_NOT_DEFAULT_LANGUAGE_COUNT`: SUM of Content that is not in default language in working state. 
`CONTENTLETS_LIVE_NOT_DEFAULT_LANGUAGE_COUNT`:  SUM of Content that is not in default language in live state.

**Comment by hmoreras** [comment]
Needs work: If I have the content in the default language and then I create a version in another language, is not taking in consideration that content and it should.

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/16

**Comment by hmoreras** [comment]
Pass Internal QA variables are working like this https://github.com/dotCMS/core/issues/27099#issuecomment-1875970354

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
