### ISSUE TITLE
Minor performance improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27103]
### Task

Seeing high memory usages and performance impacts from the `BinaryViewStrategy.transform`.  Seeing how these changes affect tests.

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
![Screenshot 2023-12-21 at 5 16 12 PM](https://github.com/dotCMS/core/assets/934364/d689650c-3d15-49a8-aa3f-29dd8d71759e)

**Comment by prestonso** [comment]
Closed as #27104 resolves this but remains unmerged, and this is a minor issue.
