### ISSUE TITLE
CLI: Pull command should ignore empty site folders 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27100]
### Problem Statement

If a blank site existing in a dotCMS instance is pulled using the CLI, an empty folder is created in the local workspace. it is inconsistent with how the CLI handles empty folders in general (the CLI ignores empty folders, never pull them)

### Steps to Reproduce

- Using the UI, create a blank site
- Run a global pull using the CLI. You will see in your workspace an empty folder with the site name under `files/live/en-us`

### Acceptance Criteria

The CLI should not create empty folders

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by bryanboza** [comment]
Fixed, tested with the last CLI version and now it is working as expected
