### ISSUE TITLE
Inconsistencies with Status Errors in `com.dotcms.ai` when we use Text and Image Generation APIs

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27124]
### Problem Statement
Inconsistencies and unclear error messaging have been identified in the handling of keys/tokens for text and image generation APIs. Specific issues include incorrect status codes and misleading or unclear error messages under various scenarios.

#### No Key/Token Scenario
- For text generation:
  1. Invoke text generation API without a key/token.
  2. Observe a 500 status code with an error message not reflecting the actual problem.
- For image generation:
  1. Invoke image generation API without a key/token.
  2. Notice a 500 status code, and the endpoint's shape is different from the dotCMS standard.

#### Wrong Key/Invalid Token Scenario
- For text generation:
  1. Use an incorrect or invalid API key for text generation.
  2. Observe a 200 status code with a body message indicating an incorrect API key.
- For image generation:
  1. Use an incorrect or invalid API key for image generation.
  2. Notice a 500 status code, but the error message is 'JSONObject["data"] is not a JSONArray.' which is unclear.

### Acceptance Criteria
- Appropriate and consistent status codes for different key/token scenarios.
- Clear and accurate error messages reflecting the actual issue.
- Alignment of the API endpoint's shape with dotCMS standards.

### dotCMS Version
Plugin com.dotcms.ai-23.12.1

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links
- API documentation: [Link to relevant API documentation]
- Error logs and reports: [Link to error logs]

### Assumptions & Initiation Needs
Assuming the issue lies in the API's error handling mechanism and inconsistency in endpoint design. Access to API codebase and error logs is necessary for further investigation.

### Quality Assurance Notes & Workarounds
Currently, front-end detection of incorrect API keys is required for text/image generation. A standard approach for error handling across APIs should be developed.

**Comment by dsilvam** [comment]
We have workarounds for this for v1.
