### ISSUE TITLE
Metrics: Count sites with permissions not inheriting from System Host 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27131]
### Parent Issue

https://github.com/dotCMS/core/issues/26943

### Task

Return the count of sites with individual permissions at the request time. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Have the count of sites with individual permissions as part of the metrics returned in the `/stats` endpoint in the Experience plugin.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/13

**Comment by dsilvam** [comment]
Sites inheriting from system host:
<img width="985" alt="Screenshot 2024-01-16 at 8 34 09 AM" src="https://github.com/dotCMS/core/assets/1576794/8221adb9-dc9b-460c-9661-718e540fef2c">

Sites not inheriting from system host - notice the individual permissions
<img width="985" alt="Screenshot 2024-01-16 at 8 34 25 AM" src="https://github.com/dotCMS/core/assets/1576794/bed62e54-6359-4086-b8f2-6018ac3804e4">

**Comment by hmoreras** [comment]
pass IAQ: the flag `SITES_WITH_INDIVIDUAL_PERMISSIONS` get modified if add individual permissions and decrease if the user reset the permissions

**Comment by hmoreras** [comment]
pass IAQ: the flag SITES_WITH_INDIVIDUAL_PERMISSIONS get modified if add individual permissions and decrease if the user reset the permissions

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
