### ISSUE TITLE
Metrics: Count of containers in system

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27142]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of containers in system and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of containers in system

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/67

**Comment by dsilvam** [comment]
Passed Internal QA: 
Properly counting live containers. Including both file + regular containers. 
Properly counting working containers. Including both file + regular containers. 
Properly excluding archived containers from the counts, both file + regular.
