### ISSUE TITLE
Metrics: Count of all template-builder templates

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27147]
### Parent Issue
https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of all template-builder templates and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of all template-builder templates

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/60

**Comment by freddyDOTCMS** [comment]
Note to QA: Steps to test:

- Start dotCMS with the latest in master
- Hit this endpoint http://localhost:8082/api/v1/telemetry/stats
- Look for the Metric COUNT_OF_TEMPLATE_BUILDER_TEMPLATES, the value should be equals to all the Not File or Advanced Template.

To check what is the right value for this Metric:

- Go to Site Layout/Templates
- All templates on the list should be counted, excluding the File and Advanced templates.
- How to know if a template on the List is a File Template?, If you click on the Template and the Site Layout/ Browser is opened then this is a File Template.
- How to know if the Template is advanced?, If you click on the Template from the List and when it is opened you see Code then this is a Advanced Template.

Also you should create a new Template, Archived/Delete Template and see how the number change

**Comment by dsilvam** [comment]
Passed Internal QA: Properly showing the count of working/live designed templates.
