### ISSUE TITLE
Metrics: Count of all templates used in pages

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27146]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of all templates used in pages and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of all templates used in pages

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/61

**Comment by freddyDOTCMS** [comment]
Note to QA: Steps to test:

- Start dotCMS with the latest in master
- Hit this endpoint http://localhost:8082/api/v1/telemetry/stats
- Look for the Metric COUNT_OF_PAGE_TEMPLATES.
- Create a new Template.
- Create a new Page using the newly created Template
- Hit the Endpoint again and the Metric must have the same value.
- Publish the Page and the Metric must be plus by 1.
- Archived the Page and the Metric must be minus 1

**Comment by dsilvam** [comment]
Needs work: Let's split this one into two different metrics: Live and Working Pages

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/65/

**Comment by dsilvam** [comment]
Passed Internal QA. Properly returning the count of templates as separate metrics for working and live pages. 
Also taking into consideration designed, advanced, and file templates for the count.
