### ISSUE TITLE
Metrics: Count of containers used in templates

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27143]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of containers used in templates and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of containers used in templates 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
This note contains various cases to assist with the QA process. Below is a list of the cases that have been tested:

### Initial State

After starting with an empty Starter, both metrics COUNT_CONTAINERS_USED_IN_LIVE_PAGES and COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0.

### Test 1: Excluding System_Container

- Create a Drawn Template: Use SYSTEM_CONTAINER and name it T1.
- Create a Page: Use the T1 Template and name it P1. Do not publish it. Both metrics should remain 0, as SYSTEM_CONTAINER is not counted for Telemetry.
- Publish P1: Both metrics should remain 0.

### Test 2: Counting Drawn Template

- Unpublish P1.
- Create a Container: Name it C1.
- Add C1 to T1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1.
- Publish P1: COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0.


### Test 3: Counting Each Container Once

- Unpublish P1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 0.
- Create a C2 Container.
- Create a New Drawn Template: Name it T2, and add C1 and C2.
- Create a New Page P2: Use T2. Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2.
- Publish P1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 1.
- Publish P2: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 2.

### Test 4: Counting Working/Live Version Correctly

- Create a New Container: Name it C3.
- Add C3 to T1: Save it, do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 (C1 and C3 in T1 Working version) and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 2.
- Publish T3: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 3.

### Test 5: Counting Advanced Template

- Create a New Container: Name it C4.
- Create a New Advanced Template: Name it T3.
- Add C4 to T3: Do not publish.
- Create a New P3 Page: Use T3. Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 3.
- Publish P3: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 4.
- Create a New Container: Name it C5.
- Add C5 to T3: Just save. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 4.
- Publish T3: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 5.

### Test 6: Counting File Template

- Create a New Container: Name it C6.
- Create a FileTemplate:
- Create an application folder at the root.
- Create a templates folder inside the application folder.
- Create a T4 folder inside templates.
- Create a properties.vtl file inside T4 with the following content. Save and publish:
- bash
- Copy code
- $dotJSON.put("title", "T4")
- $dotJSON.put("friendly_name", "File Template Advanced Example")
- Create a file called body.vtl with the content:
- shell
- Copy code
- ## Container: Default
- #parseContainer('C5's id','1')
- Create P4 using T4: Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 5.
- Publish P5: Ensure that the body.vtl file is also published. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 6.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/69

**Comment by oidacra** [comment]
## Test 1: Excluding System_Container ✅
<img width="684" alt="Screenshot 2024-06-18 at 11 02 31 PM" src="https://github.com/dotCMS/core/assets/1909643/50c26066-df3e-4778-8a6a-9b9642969034">
<img width="1475" alt="Screenshot 2024-06-18 at 11 02 38 PM" src="https://github.com/dotCMS/core/assets/1909643/e8651535-56f4-4fc4-96ef-739ae309d406">


## Test 2: Counting Drawn Template ✅
Add C1 to T1: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 0.  ✅
<img width="1455" alt="Screenshot 2024-06-18 at 11 06 00 PM" src="https://github.com/dotCMS/core/assets/1909643/1f9789b1-e4c6-4654-9287-3a699a830bf9">
<img width="684" alt="Screenshot 2024-06-18 at 11 02 31 PM" src="https://github.com/dotCMS/core/assets/1909643/c27ed628-bd4a-451c-8b4b-a9862ab04259">

Publish T1: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 1 ✅
<img width="707" alt="Screenshot 2024-06-18 at 11 07 39 PM" src="https://github.com/dotCMS/core/assets/1909643/cf0fc201-adef-413a-b751-3f48cb67387f">


## Test 3: Counting Each Container Once ✅
Unpublish T1: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 0. ✅
<img width="684" alt="Screenshot 2024-06-18 at 11 02 31 PM" src="https://github.com/dotCMS/core/assets/1909643/eb163fe3-f33b-4f71-bc0a-c172e9dd5241">

Create a C2 Container.
Create a New Drawn Template: Name it T2, and add C1 and C2. Do not publish. COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 0. ✅
<img width="684" alt="Screenshot 2024-06-18 at 11 02 31 PM" src="https://github.com/dotCMS/core/assets/1909643/17457885-f654-4b30-9db9-2c96651b349c">

Publish T1: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 1.  ✅
<img width="736" alt="Screenshot 2024-06-18 at 11 12 03 PM" src="https://github.com/dotCMS/core/assets/1909643/a19b87ac-c866-4bc9-bc3e-431b2e39784b">

Publish T2: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 2.  ✅
<img width="709" alt="Screenshot 2024-06-18 at 11 12 30 PM" src="https://github.com/dotCMS/core/assets/1909643/9ad1d57f-cf21-47fd-9d0d-8867d50eacbe">

## Test 4: Counting Working/Live Versions Correctly ✅
Create a New Container: Name it C3.
Add C3 to T1: Save it, do not publish. COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 2. ✅
<img width="769" alt="Screenshot 2024-06-18 at 11 16 25 PM" src="https://github.com/dotCMS/core/assets/1909643/43e8e9ab-9144-4c52-b0fa-700e03315943">

Publish T1: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 3. ✅
<img width="756" alt="Screenshot 2024-06-18 at 11 16 32 PM" src="https://github.com/dotCMS/core/assets/1909643/aee5bd8d-3ee1-440e-aa20-350330a1c14b">

## Test 5: Counting Advanced Template ✅
Create a New Container: Name it C4.
Create a New Advanced Template: Name it T3.
Add C4 to T3: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 3. ✅
<img width="756" alt="Screenshot 2024-06-18 at 11 16 32 PM" src="https://github.com/dotCMS/core/assets/1909643/6202b91d-0fa5-438b-a381-d46200c524dd">

Publish T3: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 4. ✅
<img width="1473" alt="Screenshot 2024-06-18 at 11 20 46 PM" src="https://github.com/dotCMS/core/assets/1909643/7c447580-448b-4529-9a42-6e1aaa407f03">
<img width="814" alt="Screenshot 2024-06-18 at 11 20 36 PM" src="https://github.com/dotCMS/core/assets/1909643/6f821b0b-fc6e-4b1e-b6bb-c9333202c732">

Create a New Container: Name it C5.
Add C5 to T3: Just save. COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 4. ✅
<img width="768" alt="Screenshot 2024-06-18 at 11 22 53 PM" src="https://github.com/dotCMS/core/assets/1909643/b7e62876-8624-422a-a828-dfff88051781">

Publish T3: COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 5. ✅
<img width="734" alt="Screenshot 2024-06-18 at 11 23 57 PM" src="https://github.com/dotCMS/core/assets/1909643/12f53527-97f2-4cd6-b907-b7694ed4eb9e">

## Test 6: Counting File Template ✅
COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 5.  ✅
<img width="1485" alt="Screenshot 2024-06-18 at 11 30 42 PM" src="https://github.com/dotCMS/core/assets/1909643/5cccb4fd-f8aa-47bb-8e06-3d32dcc0e7cd">
<img width="658" alt="Screenshot 2024-06-18 at 11 30 33 PM" src="https://github.com/dotCMS/core/assets/1909643/7bf3e56b-1558-45c1-8803-f27909693cc1">


Publish T4: Ensure both files are published. COUNT_STANDARD_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 6. ✅
<img width="1504" alt="Screenshot 2024-06-18 at 11 32 18 PM" src="https://github.com/dotCMS/core/assets/1909643/8fb0549b-5e73-49f5-bae3-a3f4f540875e">
<img width="713" alt="Screenshot 2024-06-18 at 11 32 10 PM" src="https://github.com/dotCMS/core/assets/1909643/82a22cf0-1805-48d8-a11e-50110d2cdcc0">


## Test 7: Not Counting Archived Templates  ✅
Unpublish and Archive: T1, T2, T3.
Delete T4.
Finally Check: Both metrics must be 0.  ✅
<img width="840" alt="Screenshot 2024-06-18 at 11 34 49 PM" src="https://github.com/dotCMS/core/assets/1909643/43abc305-4ab6-4c4f-a94b-b9e85ee4b40b">
<img width="1498" alt="Screenshot 2024-06-18 at 11 34 43 PM" src="https://github.com/dotCMS/core/assets/1909643/b262476f-8215-4384-929b-f622f025d1df">
<img width="1490" alt="Screenshot 2024-06-18 at 11 34 38 PM" src="https://github.com/dotCMS/core/assets/1909643/e1eb3d87-4993-42f2-8b6b-b09ea499f04f">


## Test 8: Counting File Container ❌
Create a Page P5 using T5, don't Publish COUNT_FILE_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 0 ✅
<img width="1494" alt="Screenshot 2024-06-18 at 11 40 36 PM" src="https://github.com/dotCMS/core/assets/1909643/6d6eb945-9d46-4c85-a7c0-b5b17418c352">
<img width="1497" alt="Screenshot 2024-06-18 at 11 40 29 PM" src="https://github.com/dotCMS/core/assets/1909643/b020caee-c347-43ec-a678-dca45217c7db">
<img width="752" alt="Screenshot 2024-06-18 at 11 40 11 PM" src="https://github.com/dotCMS/core/assets/1909643/2c26e16b-f13f-4524-8212-fec62f8c35f7">


Publish P5, COUNT_FILE_CONTAINERS_USED_IN_LIVE_TEMPLATES must be 1 ❌
<img width="1467" alt="Screenshot 2024-06-18 at 11 47 11 PM" src="https://github.com/dotCMS/core/assets/1909643/cc84e985-00c5-43bf-b669-a8393b3a1641">
<img width="822" alt="Screenshot 2024-06-18 at 11 47 41 PM" src="https://github.com/dotCMS/core/assets/1909643/c824d50c-faaa-4629-ae21-3b8a918a281f">

**Comment by freddyDOTCMS** [comment]
I test again and the Test 8 is working for me
