### ISSUE TITLE
Metrics: Count of themes in system

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27149]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of themes in systemit as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of themes in system

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/66

**Comment by dsilvam** [comment]
Passed Internal QA: Properly counting the Themes in the system. 
Counting unpublished and published themes that include a template.vtl. Expected.
Not counting archived themes. Expected.
