### ISSUE TITLE
Responsive Design Issue with Experiment Results Chart Not Resizing Properly

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27141]
### Problem Statement
The chart displayed in the Experiments section of the dotCMS does not resize correctly when the sidebar is open. This results in an improper view at 1300px width, affecting the user's ability to analyze data effectively.

### Steps to Reproduce
1. Navigate to the Experiments section within dotCMS.
2. Open the sidebar if it's not already open.
3. Resize the browser window to 1300px width.
4. Observe that the chart does not resize or reflow to accommodate the reduced viewport width with the sidebar open.

### Acceptance Criteria
- The chart should be fully visible and properly scaled when the browser window is at 1300px width with the sidebar open.
- The chart should maintain its aspect ratio and reflow its elements to fit the available space without horizontal scrolling or content clipping.
- Users should be able to interact with the chart (zoom, scroll, select) within the resized window.

### dotCMS Version
master

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### External Links
- Screenshot illustrating the issue:
![image (10)](https://github.com/dotCMS/core/assets/1909643/9ccd5504-2ff1-4e26-a607-b17a4c6579ec)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/27282

**Comment by hmoreras** [comment]
pass Internal QA:  the graphic resizes in small screens. 

<img width="870" alt="image" src="https://github.com/dotCMS/core/assets/31667212/03af3042-9f07-4787-a840-82213be42d8b">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_8aae521**, Docker, macOS 13.0, FF v121.0.1
