### ISSUE TITLE
Metrics: Count of all templates

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27145]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of all templatess and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of all templates

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/56

**Comment by dsilvam** [comment]
Needs work: We are not counting the file templates.

**Comment by dsilvam** [comment]
Passed Internal QA: Counting advanced, designed and file templates. Properly excluding archived ones.
