### ISSUE TITLE
Metrics: Count of containers used in pages

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27144]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of containers used in pages and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of containers used in pages

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/68

**Comment by dsilvam** [comment]
Failed IQA: When you add containers to the working version of a page that already had a live version, we are incorrectly attributing these new containers as used by the live page instead of the working.

**Comment by freddyDOTCMS** [comment]
This note contains various cases to assist with the QA process. Below is a list of the cases that have been tested:

### Initial State

After starting with an empty Starter, both metrics COUNT_CONTAINERS_USED_IN_LIVE_PAGES and COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0.

### Test 1: Excluding System_Container

- Create a Drawn Template: Use SYSTEM_CONTAINER and name it T1.
- Create a Page: Use the T1 Template and name it P1. Do not publish it. Both metrics should remain 0, as SYSTEM_CONTAINER is not counted for Telemetry.
- Publish P1: Both metrics should remain 0.

### Test 2: Counting Drawn Template

- Unpublish P1.
- Create a Container: Name it C1.
- Add C1 to T1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1.
- Publish P1: COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0.


### Test 3: Counting Each Container Once

- Unpublish P1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 0.
- Create a C2 Container.
- Create a New Drawn Template: Name it T2, and add C1 and C2.
- Create a New Page P2: Use T2. Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2.
- Publish P1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 1.
- Publish P2: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 2.

### Test 4: Counting Working/Live Version Correctly

- Create a New Container: Name it C3.
- Add C3 to T1: Save it, do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 (C1 and C3 in T1 Working version) and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 2.
- Publish T1: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 3.

### Test 5: Counting Advanced Template

- Create a New Container: Name it C4.
- Create a New Advanced Template: Name it T3.
- Add C4 to T3: Do not publish.
- Create a New P3 Page: Use T3. Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 3.
- Publish P3: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 4.
- Create a New Container: Name it C5.
- Add C5 to T3: Just save. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 2 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 4.
- Publish T3: COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 5.

### Test 6: Counting File Template

- Create a New Container: Name it C6.
- Create a FileTemplate:
      Create an application folder at the root.
      Create a templates folder inside the application folder.
      Create a T4 folder inside templates.
      Create a properties.vtl file inside T4 with the following content. Don't publish, with this code:
```
$dotJSON.put("title", "T4")
$dotJSON.put("friendly_name", "File Template Advanced Example")
```
     
Create a file called body.vtl with the content, don't publish:

```
## Container: Default
#parseContainer('Copy here C6's Id','1')
```
- Create P4 using T4: Do not publish. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 1 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 5.
- Publish P5: Ensure that the body.vtl file is also published. COUNT_CONTAINERS_USED_IN_WORKING_PAGES must be 0 and COUNT_CONTAINERS_USED_IN_LIVE_PAGES must be 6.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/70

**Comment by dsilvam** [comment]
Passed Internal QA: Tested the 7 cases included above. All of them counting the metrics as expected.
