### ISSUE TITLE
Metrics: Count of themes used by templates

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27150]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of themes used by templates versions and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of themes used by templates

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/59

**Comment by freddyDOTCMS** [comment]
Note to QA: Steps to test:

- Start dotCMS with the latest in master
- Hit this endpoint http://localhost:8082/api/v1/telemetry/stats
- Look for the Metric TOTAL_USED_THEMES.
- - Go to the /application/themes, All the Sub Folders here are themes.
- Let create a New Theme, Create a new SubFolder in '/application/themes', copy the template.vtl file from another theme
- Check the Metric again and the value must be the same.
- Create a new Template and set the newly created Theme.
- Check the Metric again and the value must be plus 1.
- Archived the newly created Templare.
- - Check the Metric again and the value must be minus 1.

**Comment by dsilvam** [comment]
Failed IQA: 
1. Assigned a new theme to a template
2. Re-assigned previous old theme to the template

Error: the new theme is still counted as "used"

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/64

**Comment by dsilvam** [comment]
Failed Internal QA: Returning 0 count when I have one working template using a theme. 
Took a look at the query and it's looking by folder's inode when it needs to be by identifier becase that is what the "theme" field holds.

**Comment by dsilvam** [comment]
Working as expected: 
* Counting the themes used by live templates.
* Counting the themes used by working templates.
