### ISSUE TITLE
Metrics: Count of Number of files in themes

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27151]
### Parent Issue

https://github.com/dotCMS/core/issues/27137

### User Story

Being able to retrieve the Count of Number of files in themes and include it as part as the /dotexp/stats Endpoint response

### Acceptance Criteria

Include a new attribute on the /dotexp/stats Endpoint with the Count of Number of files in themes

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/62

**Comment by freddyDOTCMS** [comment]
Note to QA: Steps to test:

- Start dotCMS with the latest in master
- Hit this endpoint http://localhost:8082/api/v1/telemetry/stats
- Look for the Metric TOTAL_LIVE_FILES_IN_THEMES and TOTAL_FILES_IN_THEMES, the value should be equals to all the files under the /application/themes folder, the right value is a little more then 200 files so I don't recommend you to count this files

To check what is the right value for this Metric:

- Go to Site Layout/Browser
- Go to the /application/themes, All the Sub Folders here are themes.
- Let create a New Theme, Create a new SubFolder in '/application/themes', copy the template.vtl file from another theme
- check the Metric again and both Metric should be plus 1.
- Now Create another File in this new SubFolder just Save (Don't publish), TOTAL_FILES_IN_THEMES must be plus 1 but  TOTAL_LIVE_FILES_IN_THEMES must keep the same.
- Publish the last File created and TOTAL_LIVE_FILES_IN_THEMES must be plus 1.
- Archived the File and both metric must be minus 1.

**Comment by oidacra** [comment]
IQA Failed:
Original values: 218
<img width="776" alt="Screenshot 2024-06-05 at 1 03 33 PM" src="https://github.com/dotCMS/core/assets/1909643/bfc0ec34-93e2-4aa6-b033-b74b1282d5e4">
<img width="674" alt="Screenshot 2024-06-05 at 1 03 15 PM" src="https://github.com/dotCMS/core/assets/1909643/9cf8ea89-830e-4fc8-b377-3fbc11bda918">

After creating the new subfolder and copying the template 
expected TOTAL_FILES_IN_THEMES 219
expected TOTAL_LIVE_FILES_IN_THEMES 219

<img width="636" alt="Screenshot 2024-06-05 at 1 12 26 PM" src="https://github.com/dotCMS/core/assets/1909643/b9c88b58-c995-4582-9b52-1a75bc085c55">
<img width="720" alt="Screenshot 2024-06-05 at 1 07 45 PM" src="https://github.com/dotCMS/core/assets/1909643/9c3c79fb-2ad7-4df1-95eb-0624f4ea79e8">

Has 220 each.

**Comment by freddyDOTCMS** [comment]
> IQA Failed: Original values: 218 <img alt="Screenshot 2024-06-05 at 1 03 33 PM" width="776" src="https://private-user-images.githubusercontent.com/1909643/336939534-bfc0ec34-93e2-4aa6-b033-b74b1282d5e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTMxMzMsIm5iZiI6MTcxNzYxMjgzMywicGF0aCI6Ii8xOTA5NjQzLzMzNjkzOTUzNC1iZmMwZWMzNC05M2UyLTRhYTYtYjAzMy1iNzRiMTI4MmQ1ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTg0MDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTExZGY5ZTFlODU3YTllMzI4NzhlYmFiMDdjM2M5OGE4NTM1MjU4NGRhMTA4YWVhYjg0YjhkMzJlMzg2YWJmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9m_EZ9auz8ChyaxIo8_vdG5AVnQXxVa34rBN8IdZ_xQ"> <img alt="Screenshot 2024-06-05 at 1 03 15 PM" width="674" src="https://private-user-images.githubusercontent.com/1909643/336939537-9cf8ea89-830e-4fc8-b377-3fbc11bda918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTMxMzMsIm5iZiI6MTcxNzYxMjgzMywicGF0aCI6Ii8xOTA5NjQzLzMzNjkzOTUzNy05Y2Y4ZWE4OS04MzBlLTRmYzgtYjM3Ny0zZmJjMTFiZGE5MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTg0MDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRhMWVhNThkNGRiODdjM2IzZDExYmFlZTBmY2ZkOTU2MTg3NWUyNzQxNDBkYzY0OTAyMDkwZjY0ZDUzN2FhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uEt-V3yEX9GVKmHaUu2e9dcuO3npdv3ifzne4SMGiJo">
> 
> After creating the new subfolder and copying the template expected TOTAL_FILES_IN_THEMES 219 expected TOTAL_LIVE_FILES_IN_THEMES 219
> 
> <img alt="Screenshot 2024-06-05 at 1 12 26 PM" width="636" src="https://private-user-images.githubusercontent.com/1909643/336948906-b9c88b58-c995-4582-9b52-1a75bc085c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTMxMzMsIm5iZiI6MTcxNzYxMjgzMywicGF0aCI6Ii8xOTA5NjQzLzMzNjk0ODkwNi1iOWM4OGI1OC1jOTk1LTQ1ODItOWI1Mi0xYTc1YmMwODVjNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTg0MDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI2NGJjZTNlMDE4ZjQyYjA5ZGEwY2U5ODE5ZmQzMzkxMDc5Y2QyZGQwODJiMTg3MGFkZGI3M2E3MzAwOGZlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KpOjQzNaMwEIiyazEA_De-rS2St9_lRQyBqSrjmShPs"> <img alt="Screenshot 2024-06-05 at 1 07 45 PM" width="720" src="https://private-user-images.githubusercontent.com/1909643/336948909-9c3c79fb-2ad7-4df1-95eb-0624f4ea79e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTMxMzMsIm5iZiI6MTcxNzYxMjgzMywicGF0aCI6Ii8xOTA5NjQzLzMzNjk0ODkwOS05YzNjNzlmYi0yYWQ3LTRkZjEtOTVlYi0wNjI0ZjRlYTc5ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTg0MDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUxYzI1M2RlNDU1ODcxNDQ3MjFlZDNkM2M0YzgwMWIwNDNkNzI0NWY4ZjZjZDVkZDRkYWUyZTIzODA0MTU3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L96b8Isuhc8t68It-po1rT6JjPdizzQgIT-g1XL5gw8">
> Has 220 each.

It is working as expected but I found another bug.
To create a Theme is need to: Create a SubFolder in the 'application/themes' and also create a template.vtl file inside this SubFolder.
Right now if we create a SubFolder in  'application/themes'  and create a File inside it but not the 'template.vtl' file then this file is count even when this SubFolder is not really a Theme

**Comment by dsilvam** [comment]
PR: Count of all templates used in LIVE pages

**Comment by oidacra** [comment]
IQA Passed:

<img width="1342" alt="Screenshot 2024-06-06 at 12 54 13 PM" src="https://github.com/dotCMS/core/assets/1909643/c3ab9eaf-03bd-42b3-a0b5-f5b06b650433">

<img width="728" alt="Screenshot 2024-06-06 at 12 53 29 PM" src="https://github.com/dotCMS/core/assets/1909643/94ca275c-7ad1-4284-9cb2-292f8cdd185b">

**Comment by oidacra** [comment]
@freddyDOTCMS is it ok if we count the pages?
