### ISSUE TITLE
Refactoring Metric stats End point response

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27177]
### User Story

We need to do a couple of thing here:

- Move all this logic outside the Resource class to a Util class

https://github.com/dotCMS/com.dotcms.experience/blob/main/src/main/java/com/dotcms/experience/DotExperienceResource.java#L107-L111

This logic is going to be used later inside the Job so we need to make it reusable.

- Change the JSON format of the response, including Categories, Features and description:

the new JSON format should be like

```
[
        {
          "name": "ACTIONS",
          "value": 9,
          "description": "Count of workflow actions in all schemes",
           "category": "WORKFLOWS",
            "features": "Differentiating Features"
        },
        {
          "name": "CONTENT_TYPES_ASSIGNED_SCHEMES",
          "value": 0,
          "description": "Count content types assigned schemes other than System Workflow",
           "category": "WORKFLOWS",
            "features": "Differentiating Features"
        },
        {
          "name": "SCHEMES",
          "value": 1,
          "description": "Count of workflow schemes",
           "category": "WORKFLOWS",
            "features": "Differentiating Features"
        },
        {
          "name": "COUNT",
          "value": 1,
          "description": "...",
           "category": "LANGUAGES",
            "features": "Differentiating Features"
        },
        {
          "name": "IS_DEFAULT_LANGUAGE_NOT_ENGLISH",
          "value": false,
          "description": "..."
           "category": "LANGUAGES",
            "features": "Differentiating Features"
        },
        ...
]
```

### Acceptance Criteria

Change the End point JSON response to the new format

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
I think we need to talk about what the data should look like.  If we are going to use a json field, I would try to flatten its values and skip adding metadata into each json "column".  Also, if we do use real columns for things, I would dupe their values in the json itself, which could save use time.

```sql
create table client_usage_metrics(
   id long sequence,
   client_env varchar(255) not null, 
   server_id varchar(255) not null,
   schema_version int default 0,
   data jsonb,
   mod_date timestamptz
)

```

and the jsonb would be something like:

```
{
  "client_env": "dotcmscorp_prod", 
  "schema_version": 0,
  "server_id": "dotcmscorp_prod-1",
  "mod_date": "2024-01-01 21:56:43+00", 
  "workflow_actions": 9,
  "content_types_assigned_schemes": 0,
  "workflow_schemes": 1,
  "is_default_language_not_english": false,
  ...
}

```

**Comment by spbolton** [comment]
I agree with Will, I think a flat structure will be better initially and we should treat these the same way I have been suggesting for configuration keys and maybe follow the same casing rules also for consistency e.g.  workflow.contentTypesAssignedSchemes or workflow.content-types-assigned-schemes,  using both of these models we can parse the key for its hierarchy and convert the local part easily between any format.  

I am not sure whether we may have some issues with the ORM framework with jsonb fields,  using the structure above we are really representing a flat Hashmap and this can be a simple child table in a 1-many relationship.  On a basic implementation would restrict all values to be stored as Strings and any conversions done on the client,  there are ways we could optimize the storage later without modifying the structure of the data we are sending but this is probably sufficient for a simple implementation.

**Comment by dsilvam** [comment]
Passed Internal QA: Metrics displaying correctly with included metadata.
