### ISSUE TITLE
 Plugin error modal missing accept button in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27176]
### Problem Statement

In dotCMS, there is an issue where the error modal for plugins does not display the 'Accept' button. This absence hinders users from acknowledging and closing the error message, potentially obstructing further actions or troubleshooting steps.

![image](https://github.com/dotCMS/core/assets/2641437/9fa231e8-3bc2-414f-8895-6c67dee3714b)

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Engage in an activity that involves the use of plugins (e.g., activating a plugin).
- Trigger an error that would typically bring up the error modal for plugins.
- Observe that the error modal appears but lacks an 'Accept' or 'Close' button.

### Acceptance Criteria

**Visible Accept Button**: Ensure that the error modal for plugins consistently displays an 'Accept' or 'Close' button to allow users to acknowledge the error.
**Functional Button:** The button should not only be visible but also functional, allowing users to close the modal effectively.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by gortiz-dotcms** [comment]
Seems like it's already fixed

![image](https://github.com/user-attachments/assets/baf23231-ff45-433a-9447-c8df4f2e0faf)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b5017f1**, Docker, macOS 14.5, FF v126.0.1
