### ISSUE TITLE
Edit Page: Expose the languages that a page is available on via REST

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#27185]
### User Story

As a dotCMS User, I want to be able to quickly determine what languages an HTML Page is available on, so that I can help Content Authors create a page in a language that doesn't exist yet.

### Acceptance Criteria

The new method will be called like this:
```
http://localhost:8080/api/v1/page/{PAGE_ID}/languages
```
And the expected JSON response must look like this:
```json
{
    "entity": [
        {
            "country": "United States",
            "countryCode": "US",
            "defaultLanguage": true,
            "id": 1,
            "isoCode": "en-us",
            "language": "English",
            "languageCode": "en"
            "translated": true // The page HAS an English version
        },
        {
            "country": "Espana",
            "countryCode": "ES",
            "defaultLanguage": false,
            "id": 2,
            "isoCode": "es-es",
            "language": "Espanol",
            "languageCode": "es",
            "translated": false // The page DOES NOT have a Spanish version
        }
    ],
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

### Steps to Reproduce

1. Create three languages in your dotCMS instance:
1.1. English
1.2. Spanish
1.3. French
2. Create an HTML Page **ONLY in English**. Copy its Identifier.
3. Call the new REST method: http://localhost:8080/api/v1/page/{PAGE_ID}/languages and pass down the page's Identifier.
4. The JSON response must look like the one in the **Acceptance Criteria** section. The `translated` must be present for ALL languages, but its value must be `true` for the English language only.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
We used here: https://github.com/dotCMS/core/issues/27281

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF

Tested using the provided test in postman..
