### ISSUE TITLE
Experience Plugin Interfering with License Upload in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27189]
### Problem Statement

The Experience Plugin in dotCMS is causing the license upload functionality to crash. This issue is preventing users from successfully uploading new licenses, a critical task for maintaining and updating their dotCMS instances.

![image](https://github.com/dotCMS/core/assets/2641437/38dcb6c8-4133-4c78-b7af-2350623d6f62)

### Steps to Reproduce

- Log into the dotCMS backend with the necessary administrative credentials.
- Navigate to the section for uploading or updating the dotCMS license.
- Attempt to upload a new license while the Experience Plugin is active or recently used.
- Observe that the license upload process crashes or fails to complete successfully.

### Acceptance Criteria

**Compatibility Between Plugin and License Upload:** Ensure that the Experience Plugin does not interfere with the license upload functionality. Users should be able to upload licenses seamlessly, regardless of the state or usage of the Experience Plugin.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
This will probably get taken care of when we clean up the experience plugin to remove extraneous (and dangerous) functions.

Putting in as a 1 pointer for now, but will likely go away once that work is done.

**Comment by freddyDOTCMS** [comment]
Note to QA: Working as expected

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_ac8b0bb**, Docker, macOS 13.0, FF v121.0.1
