### ISSUE TITLE
remove unneeded DB hit from edit content screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27187]
### Task

On the edit content screen we call for a list of 100 structures that are never used.  This results in an unneeded db hit every time and can be removed.

```
List<Structure> structures = StructureFactory.getStructuresByUser(user, "", "name", 100, 0,"asc");
```

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/27188
