### ISSUE TITLE
Experiments: Handling Empty Analytics Key in App Configuration in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27193]
### Problem Statement

There is an issue in dotCMS where an empty value in the analytics key field within app configurations leads to an error. This situation can cause disruptions and confusion for users configuring apps, especially when the significance of the analytics key is not clear or accidentally left blank.

We need to show a clear message in case your configuration is not healthy. 

https://github.com/dotCMS/core/assets/2641437/571439f7-413a-40ad-b872-e5c8745571e9

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Navigate to the app configuration section.
- Enter or edit the configuration settings for an app that requires an analytics key.
- Leave the analytics key field empty and attempt to save the configuration.
- Try to create a new variant for some page 

### Acceptance Criteria

- **Clear User Guidance**: Provide a clear and informative message to the user when the analytics key field is left empty, explaining the necessity of this field and guiding them to enter a valid value.
- **Error Prevention Mechanism:** Ensure that leaving the analytics key field empty does not lead to an error, but rather to a user-friendly prompt or notification for corrective action.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

**Comment by freddyDOTCMS** [comment]
PR https://github.com/dotCMS/core/pull/27192

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/27192

**Comment by hmoreras** [comment]
pass internal QA:  when the configuration is not set properly show the message `Analytics App not Configured Properly`

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_cd9a412**, Docker, macOS 13.0, FF v113.0

**Comment by hmoreras** [comment]
Note to QA:  just spoke with Jose and give him the correct params and avoid to add the `Analytics Key` manually and is working as it should in the latest of master: master_ddd7297

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_693a20f**, Docker, macOS 13.0, FF v121.0.1
