### ISSUE TITLE
Default workflow action - 404 - not found

### ISSUE THREAD

**Issue by LukasKuchta** [dotCMS/core#27199]
### Problem Statement

Hi, I'm trying to use workflow API for bulk upsert operation. Based on the documentation it should be possible:

https://www.dotcms.com/docs/latest/save-content-using-workflows

But when I send a request I'm getting 404 not found. 

Can you someone give me hints about what is wrong please? The content type Product exists in dotcms ecosystem. 

When i use non-default workflow like this, it works. But only one record is possible to send. No contentlets atribute is available.  I need to send multiple data with one request. 

![scr](https://github.com/dotCMS/core/assets/105702630/47e48f92-8da3-4778-8c65-9952780fc2eb)
I attached the screenshot with the url and part of json. 
![not_found](https://github.com/dotCMS/core/assets/105702630/d3d0f9ce-8fad-4020-ac52-a4ab7b3d8499)

Thanks for advice 

### Steps to Reproduce

Create simple content type with one field
Try to send two items over default workflow api like NEW/EDIT. Based on documentation. 
The server returs 404 not found

### Acceptance Criteria

Server should return results.

### dotCMS Version

SERVER: F2E57172 | COMMUNITY EDITION: 23.12.22 - DECEMBER 21, 2023 11:29 PM

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
@LukasKuchta We've made improvements here; are you still seeing this on the Workflows endpoint? If so please feel free to reopen.
