### ISSUE TITLE
VanityURL.postman_collection.json

### ISSUE THREAD

**Issue by rashik1144** [dotCMS/core#27266]

**Comment by rashik1144** [comment]
This gives "500 Internal Server" error message when wrong input is provided. This also have the same problem mentioned here: https://github.com/dotCMS/core/issues/27229
![image](https://github.com/dotCMS/core/assets/128124382/3605ec76-dc49-45e2-b83e-0ef1123c1175)

**Comment by rashik1144** [comment]
@mbiuki This allow the XSS injection in the alias. However, this is admin only feature. 
![image](https://github.com/dotCMS/core/assets/128124382/a8d88d81-baff-4f79-a1f2-3fe274e68bac)

**Comment by mbiuki** [comment]
Low priority, won't fix.
