### ISSUE TITLE
Edit Content : Add a button to the Content Type screen to enable the new edit mode

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#27289]
### Parent Issue

#25445 

### Task

In order to allow users to be able to interact with the new Edit Content portlet, we're going to temporarily add a button to the edit dialog of every Content Type that will enable the new Angular-based portlet. This way, we can let users interact with it without completely overriding the existing one.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Official design and location of the button still pending.

### Assumptions & Initiation Needs

It was decided that a new column named `metadata` will be added to the `structure` table. This can hold the new temporary parameter, and any other information we may need in the future.

**Comment by zJaaal** [comment]
# IQA Passed

Now if we have the Feature Flag for the new Edit Content activated we can decide whether or not use it from Content Types.

docker image: `[dotcms/dotcms:master_a38321e]`

## Screenshots

https://github.com/dotCMS/core/assets/63567962/dcd73481-b3c0-4209-8595-ad31883895d9

**Comment by hmoreras** [comment]
additional feedback and findings here: https://github.com/dotCMS/core/issues/27522

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b4779ec**, Docker, macOS 13.0, FF v121.0.1
