### ISSUE TITLE
Announcements Menu UI/UX Refinement

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27285]
### Parent Issue

#25733 

### Task

1. Ensure that the background code is adjusted to enhance the overall visual appeal, keeping it consistently white and avoiding the use of the user variable color.
2. Correct typographical errors in the resources section.
3. Align icons with the title in the resources section to ensure a cohesive visual presentation.
4. Implement the old-style welcome message.
5. ~Ensure that the separator line color matches the color of the right button in the top bar for a consistent visual appearance.~ Remove the separator line between the notifications and announcements buttons.
6. Adjust the padding for the notifications menu.
7. Increase the width of the user menu.
8. Optimize the titles of APIs and services to be less wide. (Based on Figma)
9. Add underlines to the announcements menu Show All button.
10. Increase the height of the announcements section slightly.  (Based on Figma)

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
Internal QA: Passed

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_cf3883d**, Docker, macOS 13.0, FF v121.0.1
<img width="1280" alt="Screenshot 2024-01-17 at 12 01 34 PM" src="https://github.com/dotCMS/core/assets/129882031/40632fd0-9c02-446f-aad1-1cb24170db46">
