### ISSUE TITLE
Edit Page: Resolve Error When Editing Non-Existent Language Page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27281]
### Problem Statement
When a user is editing a page in language 2 and this page has no language 1 version, if the user tries to select language 1, the page editor throws an error and kicks the user out of the page editor.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/a4e4c7b1-798d-4e0d-8add-6e2b5f1b2758

```[tasklist]
### Acceptance Criteria
- [ ] User should be able to create the language version if doesn't exist and then edit the page
```

### External Links
New endpoint: https://github.com/dotCMS/core/issues/27185

This endpoint will tell you if the page have or not a version for the selected language, which allows you to change the flow.

So now instead of using the language API, you can use the page language API.

**Comment by fmontes** [comment]
Now in edit mode, when you try to delete a piece of content you get double confirmation... For what I can tell is because this one: https://github.com/dotCMS/core/blob/2aa5e22c52988ef0252064a23dffe4dac47cecb4/core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-edit-page-view-as-controller-seo/dot-edit-page-view-as-controller-seo.component.html#L33-L37

**Comment by oidacra** [comment]
Double confirmation fixed with https://github.com/dotCMS/core/pull/27353

**Comment by dsilvam** [comment]
Passed Internal QA: It is now offering the user to create the page on the selected language and performing that action is working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
