### ISSUE TITLE
Edit EMA: Add a UI warning when attempting to drag to an invalid contentType or the container has no available space

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27284]
### Parent Issue

#26644

### User Story

As a user, I want to easily identify which containers allow me to add a `contentType`, so I can focus my efforts effectively

### Acceptance Criteria

Containers that do not support the current content type should display a warning to indicate either "invalid content" or "unavailable space".

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### [Figma Design](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2628%3A16161&mode=design&t=3XhZIQ1DdDvDT9M8-1)

![UI Warning for invalid contentType](https://github.com/dotCMS/core/assets/72418962/7f347216-9940-4e85-9bd8-280cc587be18)

**Comment by fmontes** [comment]
Container takes all widgets, and right now is not, drag a widget and see how all the containers in the page get's blocked.

**Comment by rjvelazco** [comment]
@fmontes You are right! Here is the fix: https://github.com/dotCMS/core/pull/27314
