### ISSUE TITLE
CLI: We need to create the ".dotcms" folder when you install the tool 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27298]
### Problem Statement

AS part of the CLI implementation, we need to create the .dotcms folder in the ROOT directory once that you install the tool in your computer, right now after install it, you need to run some command in order to create it. 

This can cause confusion with the users since if you try continue configuring it without run any command we are not able to locate this folder to instance the profile. 

### Steps to Reproduce

- Download the dotcli 
- Install it in your computer 
- Try to navigate to the config folder `~/.dotcms` folder 

### Acceptance Criteria

- We need to auto create as part of the installation process 
- If not we need to doc this as part of the process 

### dotCMS Version

Tested on master // docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
This issue will be fixed through the creation of the `init` command. The command will be implemented on [this card](https://github.com/dotCMS/core/issues/27423)
