### ISSUE TITLE
Edit Ema: Update ema next dotcms app

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27302]
### Parent
#26644 

### Problem Statement
Non-admin users are currently unable to use the new edit mode in dotCMS, because we are validating the route with the `/apps` endpoint and that endpoint have specific permissions.

### Steps to Reproduce
1. Set the ema next app.
2. Give permission to user Chris to edit a page
3. Login as Chris
4. Attempt to access the new edit mode and see the endpoint fail

### Acceptance Criteria
We need to create a new endpoint that can be enabled by the settings of the app and this endpoint needs to returns the site app settings.

**Comment by jdotcms** [comment]
when not configuration
<img width="1413" alt="Screenshot 2024-01-11 at 8 54 37 AM" src="https://github.com/dotCMS/core/assets/19578350/6e0f9ee4-e156-408e-956a-adaf12cfe1b0">

the result is
<img width="772" alt="Screenshot 2024-01-11 at 8 54 31 AM" src="https://github.com/dotCMS/core/assets/19578350/93e52af9-ade0-4204-8350-00b29326c1a7">

**Comment by jdotcms** [comment]
When config with Admin
<img width="1449" alt="Screenshot 2024-01-11 at 8 54 59 AM" src="https://github.com/dotCMS/core/assets/19578350/ed472a5b-ecce-4282-99cb-3f61cc1e6461">

the result is:
<img width="671" alt="Screenshot 2024-01-11 at 8 55 13 AM" src="https://github.com/dotCMS/core/assets/19578350/93c9f3f4-4b45-47fb-939a-265d7c3d76cb">

**Comment by jdotcms** [comment]
When trying with  FE
<img width="1200" alt="Screenshot 2024-01-11 at 8 55 26 AM" src="https://github.com/dotCMS/core/assets/19578350/961b00dc-f2b7-4e63-bc79-66d0ecae7067">

**Comment by jdotcms** [comment]
When trying with limited BE user
<img width="833" alt="Screenshot 2024-01-11 at 8 55 44 AM" src="https://github.com/dotCMS/core/assets/19578350/b7c9b47e-261b-46a6-8188-b51ffc101fab">

<img width="602" alt="Screenshot 2024-01-11 at 8 56 01 AM" src="https://github.com/dotCMS/core/assets/19578350/bb607aa9-5083-491f-9a11-87e320f62b54">

the result is
<img width="458" alt="Screenshot 2024-01-11 at 8 56 08 AM" src="https://github.com/dotCMS/core/assets/19578350/f17dd693-14dd-4a68-886d-8a9805cdf707">

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
