### ISSUE TITLE
The language id is not being set when create a new user by rest api

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27319]
### Problem Statement

The language id is not being set when create a new user by rest api

```
curl --location 'https://demo.dotcms.com/api/v1/users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data-raw '{
    "userId":"userid-spanish-12345678",
    "active":true,
    "firstName":"SpanishUser",
    "middleName":"S",
    "lastName":"Spanish",
    "nickName":"Spanish",
    "email":"spanish@dotcms.com",
    "male":true,
    "languageId":2,
    "password":["1","2","3","4","5","6","7","8"],
    "roles":["DOTCMS_BACK_END_USER", "CMS Administrator"]
}'
```

This request returns an user with english language, instead of spanish!

### Steps to Reproduce

Run the curl

### Acceptance Criteria

The user has to have spanish version of the language set

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now this is working as expected 
![Image](https://github.com/dotCMS/core/assets/2641437/b23fbbb2-e7ba-4be7-a89b-7feafff30f6e)

**Comment by wezell** [comment]
We need to make sure that this accepts the iso code for the language.

**Comment by jdotcms** [comment]
New PR has been pushed, now the postman reflects the lang_country nomenclature expected on the db

**Comment by jcastro-dotcms** [comment]
### Internal QA: PASSED
The User API is now accepting bot the ISO code and the Language ID when creating Users. For instance, passing down the Language ID:
```curl
curl --location 'https://demo.dotcms.com/api/v1/users' \                                                                                                                                                             ‹system: ruby 2.6.10p210›
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
 --data-raw '{
    "userId":"userid-spanish-12345678",
    "active":true,
    "firstName":"SpanishUser",
    "middleName":"S",
    "lastName":"Spanish",
    "nickName":"Spanish",
    "email":"spanish@dotcms.com",
    "male":true,
    "languageId":2,
    "password":["1","2","3","4","5","6","7","8"],
    "roles":["DOTCMS_BACK_END_USER", "CMS Administrator"]
}'
```
Returns the following JSON response -- notice `"languageId":"es_ES"`:
```json
{
  "entity": {
    "user": {
      "active": true,
      "actualCompanyId": "dotcms.org",
      "additionalInfo": null,
      "admin": true,
      "backendUser": true,
      "birthday": null,
      "comments": null,
      "companyId": "dotcms.org",
      "createDate": 1708961542646,
      "deleteDate": null,
      "deleteInProgress": false,
      "emailAddress": "spanish@dotcms.com",
      "emailaddress": "spanish@dotcms.com",
      "failedLoginAttempts": 0,
      "female": false,
      "firstName": "SpanishUser",
      "frontendUser": false,
      "fullName": "SpanishUser S Spanish",
      "gravitar": "74b00ed529df32f0b5b7b47939fb0293",
      "hasConsoleAccess": true,
      "id": "userid-spanish-12345678",
      "languageId": "es_ES",
      "lastLoginDate": null,
      "lastLoginIP": null,
      "lastName": "Spanish",
      "male": true,
      "middleName": "S",
      "modificationDate": 1708961542646,
      "name": "SpanishUser S Spanish",
      "nickname": "Spanish",
      "passwordExpirationDate": null,
      "passwordExpired": false,
      "passwordReset": false,
      "timeZoneId": "UTC",
      "type": "user",
      "userId": "userid-spanish-12345678"
    },
    "userID": "userid-spanish-12345678"
  },
  "errors": [],
  "i18nMessagesMap": {},
  "messages": [],
  "pagination": null,
  "permissions": []
}
```
And passing down the ISO code:
```curl
curl --location 'http://localhost:8080/api/v1/users' \                                                                                                                                                               ‹system: ruby 2.6.10p210›
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
--data-raw '{
    "userId":"userid-french-12345678",
    "active":true,
    "firstName":"FrenchUser",
    "middleName":"S",
    "lastName":"French",
    "nickName":"French",
    "email":"french@dotcms.com",
    "male":true,
    "languageId":"fr_FR",
    "password":["1","2","3","4","5","6","7","8"],
    "roles":["DOTCMS_BACK_END_USER", "CMS Administrator"]
}'
```
Returns the following -- notice `"languageId":"fr_FR"` as well:
```json
{
  "entity": {
    "user": {
      "active": true,
      "actualCompanyId": "dotcms.org",
      "additionalInfo": null,
      "admin": true,
      "backendUser": true,
      "birthday": null,
      "comments": null,
      "companyId": "dotcms.org",
      "createDate": 1708961464872,
      "deleteDate": null,
      "deleteInProgress": false,
      "emailAddress": "french@dotcms.com",
      "emailaddress": "french@dotcms.com",
      "failedLoginAttempts": 0,
      "female": false,
      "firstName": "FrenchUser",
      "frontendUser": false,
      "fullName": "FrenchUser S French",
      "gravitar": "91b66133d66d3e6a49bb87976048a193",
      "hasConsoleAccess": true,
      "id": "userid-french-12345678",
      "languageId": "fr_FR",
      "lastLoginDate": null,
      "lastLoginIP": null,
      "lastName": "French",
      "male": true,
      "middleName": "S",
      "modificationDate": 1708961464872,
      "name": "FrenchUser S French",
      "nickname": "French",
      "passwordExpirationDate": null,
      "passwordExpired": false,
      "passwordReset": false,
      "timeZoneId": "UTC",
      "type": "user",
      "userId": "userid-french-12345678"
    },
    "userID": "userid-french-12345678"
  },
  "errors": [],
  "i18nMessagesMap": {},
  "messages": [],
  "pagination": null,
  "permissions": []
}
```

**Comment by bryanboza** [comment]
We need some work here: 

In case you try to create a new user with an email that is already registered, we are just returning a 400 (bad request) error, which is ok, but we are not returning the proper message in the response,  we are just getting "null". 

We need to indicate the FE part about this problem. 
![image](https://github.com/dotCMS/core/assets/2641437/8b3e2e1e-1dfd-44c1-af28-a05db9523c15)

**Comment by jdotcms** [comment]
> We need some work here:
> 
> In case you try to create a new user with an email that is already registered, we are just returning a 400 (bad request) error, which is ok, but we are not returning the proper message in the response, we are just getting "null".
> 
> We need to indicate the FE part about this problem. ![image](https://private-user-images.githubusercontent.com/2641437/308284967-8b3e2e1e-1dfd-44c1-af28-a05db9523c15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTcxOTUsIm5iZiI6MTcwOTA1Njg5NSwicGF0aCI6Ii8yNjQxNDM3LzMwODI4NDk2Ny04YjNlMmUxZS0xZGZkLTQ0YzEtYWYyOC1hMDVkYjk1MjNjMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTgwMTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFjM2YxZDc4ZjQ2YTRhYzg3ZWZhMDQ2Yjg3YjI4NmQ3MDVjYTc3YzRmOTMwM2MwNjgyOTM5OTM1NTgyZTQ3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E6YJmw4jPikeFscq9t8Djmu9CWC3vjtC2eR79Owxw20)

It is a good improvement, but even if it is related is out of the scope. I will file a new issue to track this

**Comment by jdotcms** [comment]
for tracking: https://github.com/dotCMS/core/issues/27742

@bryanboza if you agree with this approach please proceed to approve this issue

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b5f4512**, Docker, macOS 13.0, FF v121.0.1

Related issue will be addressed in card https://github.com/dotCMS/core/issues/27742
