### ISSUE TITLE
Sort List Experiments by most recent modification 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27324]
### User Story

As an experiments user I want to see the list of experiments sorted by most recent modification

### Acceptance Criteria

The list of experiments should be sorted by most recent modification

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Passed Internal QA: Experiments sorted by most recent modification date. Each individual status grouping sorted like this.

**Comment by josemejias11** [comment]
Blocked by https://github.com/dotCMS/core/issues/27193

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_693a20f**, Docker, macOS 13.0, FF v121.0.1
<img width="1350" alt="Screenshot 2024-01-16 at 2 59 59 PM" src="https://github.com/dotCMS/core/assets/129882031/1fdf1db8-4cb0-4853-9e36-ea93ea5c1d2f">
