### ISSUE TITLE
`Check it out` button in editing a WYSIWYG field has broken styles

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#27341]
### Problem Statement

The styles for the `Check it out` button on the Block Editor information for WYSIWYG are off, The label has an incorrect color.

This just happens when editing a WYSIWYG field, when we create a new one the label has the correct color. 

### Steps to Reproduce

https://github.com/dotCMS/core/assets/63567962/e17fa475-14e4-4ea8-9f7b-37d12f4d27c1

### Acceptance Criteria

As an user I want to see the label with the correct color and the correct contrast.

### dotCMS Version

`master-latest`

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by oidacra** [comment]
close in favor of https://github.com/dotCMS/core/issues/30248

**Comment by bryanboza** [comment]
Fixed, Unable to reproduce after this fix 
![Image](https://github.com/user-attachments/assets/9b89b63c-dc7f-43fc-8cfb-b6f0586ac9a6)
