### ISSUE TITLE
SAML: Create default landing redirect

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27344]
### User Story

As a SAML user, I wan to be able to set a default landing page to avoid to go to dotAdmin as a default.

### Acceptance Criteria

If the redirect.after.login is set for the site, the redirect will be perform to it when the property is empty on the session

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
Just need to set the relative path to the property redirect.after.login, for instance
```
redirect.after.login=/company/index
```

**Comment by bryanboza** [comment]
Fixed, tested on docker // master // FF
