### ISSUE TITLE
Display 'No Notifications' Message for User Clarity

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27368]
### Parent Issue

#25733 

### User Story

As a user, I want to be able to see a "No Notifications" message on the interface when there are no notifications present, so I can quickly and clearly understand that there are currently no new notifications to view.

### Acceptance Criteria

Ensure the display of the following message according to the provided Figma file design. Refer to the file for specific details and layout.

![image](https://github.com/dotCMS/core/assets/3438705/75989063-d9a3-4946-b9ee-e3362f0ce16c)

Figma https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?node-id=631:8405&mode=dev

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dcolina** [comment]
Internal QA: Passed.

As you can see in the following image. 

![Screenshot 2024-02-15 at 18 39 00](https://github.com/dotCMS/core/assets/29883881/fae884a6-ae27-4064-ba1a-e8eb1b709d0b)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
