### ISSUE TITLE
Change Edit EMA config API on Edit EMA guards

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#27372]
### Parent Issue

https://github.com/dotCMS/core/issues/26644

```[tasklist]
### Tasks
- [ ] Change current api (api/{key}/{currentSite} to api/v1/ema
- [ ] Not-admin users (Users without Edit Ema Config in Apps) can access to new edit EMA
```

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `master`

https://github.com/dotCMS/core/assets/72418962/5312dcd1-880c-43dd-98be-ca4b96435954

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
