### ISSUE TITLE
CLI: Limited user problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27386]
### Problem Statement

Users with limited permissions are experiencing issues with the CLI in dotCMS. The problem involves discrepancies in file permissions that result in errors when attempting to pull files. Limited users are unable to access certain files due to permission restrictions, leading to errors during the pull operation.

![image](https://github.com/dotCMS/core/assets/2641437/a0f8be6b-589a-4a19-b0ba-d1a08b427bce)

### Steps to Reproduce

- Log in to the dotCMS CLI with limited user credentials.
- Try to run the follow command `dotcli push --dry-run`
- Observe errors related to file access or permissions during CLI operations.
- Now try to run the general pull 
- You will have the same errors again 

### Acceptance Criteria

**Permission Validation:** Implement a mechanism in the CLI that checks and respects user permissions when performing file-related operations.
**Error Handling:** Provide clear and informative error messages when a limited user attempts to access files without the necessary permissions.
**Pull Operation Enhancement:** Modify the pull operation to consider user permissions, preventing attempts to retrieve files that the user does not have access to.

### dotCMS Version

Tested on master // Docker // dotcms-cli-1.0.0-20231002.205953-1.jar

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Internal QA:** Needs work

If you have multiple folders and for some reason a limited user doesn't have permissions over one of them , the global pull fails. It should ignore that folder and continue.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
We need some work here: 

- if I login via CLI with a limited user, and try to do a global pull we are getting some errors


![Image](https://github.com/dotCMS/core/assets/2641437/32ac4604-fef7-4f60-98fa-433811cb8b41)

- We need be like in site browser, if you don't have permissions to view those files, we should not have errors since you can't access those. We need just ignore and continues just with the files that you have permissions

**Comment by fabrizzio-dotCMS** [comment]
@bryanboza You get the error report but the process does not break. Let's say your missing permission under only one folder 
You'll get the report but the process continues and if you have permissions over the other the pull/push operation succeeds. That's what we talked about.

**Comment by bryanboza** [comment]
ok, basically I'm getting those errors with my instance by default, I have not adding or removing permissions to any folder. My concern here is I don't know why we are getting errors from those folders If I don't have permissions to see in the backend. 

Since the user is "limited", I think we should be able to do a clear pull without errors with all the info that I'm authorized to see. Having this every time you try to pull is very noisy. 

Also, we have another case here: 

- I just added a new folder and add full permissions to some limited user, If I try to upload a file to this folder from backend, I can upload the file without problems, but If I try the same thing via CLI we are getting an error 

Here the video: 
https://drive.google.com/file/d/1iKFUVugNPsuxAE-DtIV2Q4Mby61mcjin/view?usp=sharing

**Comment by fabrizzio-dotCMS** [comment]
I'm following the steps in this video. I think @bryanboza uploads the file logged in as admin. When I try to upload a file logged in as **Chris Publisher** it fails. just like it fails when pushed from the CLI logged in as **Chris Publisher**

**Comment by bryanboza** [comment]
We need to have a clear error when you try to push some content as limited user and you don't have permissions. Right now we are getting a weird error related to a WebApplicationError instead to get a permissions error. Also the response code is 500 instead the 403 error related to permissions. 


![Image](https://github.com/dotCMS/core/assets/2641437/803eef0f-9f6f-473e-9994-390e1a4c527b)

**Comment by nollymar** [comment]
**Internal QA:** Passed

If I try to push a file under a folder where a limited user has View Permissions, now I get a 403 error:

```
[ERROR] ❗  Error pushing asset [/new-limited/image.png] 
 HTTP 403 Unauthorized: Authentication failed or Permission is denied.

```

In case I use the flag `--dry-run` in the push command, I don't get a 403 exception and the new file is not considered as a change to be pushed, which is ok.

**Comment by bryanboza** [comment]
Fixed, now we have a clear error here "

![image](https://github.com/dotCMS/core/assets/2641437/cda9cdc3-9724-45fa-8a05-155c1c21ce0b)

Tested on master // Docker // FF
