### ISSUE TITLE
Update local.dotcms.site SSL cert for 2024

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27384]
Our local.dotcms.site cert that runs on port 8443 is going to expire in 1 week.  We need to update it for the new year.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/27385

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_68f4331**, Docker, macOS 13.0, FF v121.0.1

This certificate is valid from January 19, 2024, until January 26, 2025.

**Comment by erickgonzalez** [comment]
Only applies to 23.10 LTS
