### ISSUE TITLE
 Binary: Autocomplete Issue in Binary Field for File Content Creation

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27389]
### Problem Statement

When adding a new file content in dotCMS, there is an issue with the binary field where the file name and title are not auto-completing as expected. This affects the efficiency of the content creation process and may lead to inconsistencies in file names and titles.

https://github.com/dotCMS/core/assets/2641437/b5dd28c5-eca7-4465-95e2-6b76c2e22647

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Navigate to the section for creating new file content.
- In the binary field, attempt to upload a file.
- Observe that the file name and title are not automatically completed based on the uploaded file. 

### Acceptance Criteria

**Autocomplete Functionality:** Ensure that the binary field autocompletes the file name and title when a new file is added, providing a convenient and accurate way to name files.
**Consistent Autocomplete:** The autocomplete feature should consistently work across various file types and formats.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_c4e5541**, Docker, macOS 13.0, FF v121.0.1
![Screenshot 2024-02-01 at 10 37 52 AM](https://github.com/dotCMS/core/assets/129882031/acb64997-1f7e-419c-a002-ba523ec3c6b0)
