### ISSUE TITLE
Some scroll bars bottom out early

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#27399]
### Problem Statement

Initially noticed this on the Content Type builder: The field list scrollbar doesn’t go down far enough, so when it reaches the "bottom" it looks like we removed the WYSIWYG field.

@jdotcms reports similar behavior when dealing with optional properties while configuring SAML, so it may be something more general than just the Content Type builder. 

### Steps to Reproduce

1. Browse to Content Model -> Content Types
2. Open an existing Content Type or create a new one
3. Try to add a WYSIWYG field
    - By the bottom of the list, it's not there.
4. Grab the last few pixels at the bottom of the list and drag them into a row.
    - You just grabbed the top few pixels of the WYSIWYG field
        - (It still exists and we never stopped believing in it. 🌟)

https://github.com/dotCMS/core/assets/102264829/aea0860f-db70-451f-8ba7-7c8cce10a022

### Acceptance Criteria

Scroll bars should hit the top and bottom at the top and bottom of the display area, respectively.

### dotCMS Version

- 23.12.22
- dotcms-core 1.0.0-SNAPSHOT (January 19, 2024 1:37 PM)

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by rjvelazco** [comment]
### Passed Internal QA

-  Tested on Docker Image: `dotcms:master_4a3fb81`



https://github.com/dotCMS/core/assets/72418962/1141f8ec-03e7-4ef9-a93e-f7f3a7ad4cf1

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a090821**, Docker, macOS 13.0, FF v121.0.1
