### ISSUE TITLE
CLI: Publishing dotcms-cli distributions on NPM registry

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27416]
Publishing `dotcms-cli` distributions on the NPM (Node Package Manager) registry involves making the dotCMS command-line interface (CLI) packages available for installation and use by developers and users within the `Node.js` ecosystem. It is necessary to integrate into the current dotcms-cli release workflow following the steps described in #27089

**Comment by nollymar** [comment]
**Internal QA:** needs work

The publication failed in the [last step ](https://github.com/dotCMS/core/actions/runs/7817910603/job/21327740369#step:9:27)

**Comment by nollymar** [comment]
**Internal QA:** Passed
