### ISSUE TITLE
Edit EMA: Upgrade SDK and nextjs example

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27415]
### Parent Issue

#26644 

### Task

- [x] Publish to npm
- [ ] Upgrade nextjs

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Test this and make sure that offset in layout works.

**Comment by zJaaal** [comment]
## PASSED IQA

The layouts are rendering correctly

## Screenshot

https://github.com/dotCMS/core/assets/63567962/14a535b0-d393-4c4e-ae2f-cecbf99ec8a4

**Comment by fmontes** [comment]
QA will be testing this in #27350
