### ISSUE TITLE
Include UTM Parameters in Announcement URLs

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27424]
### Parent Issue

#25733 

### Task

We should enhance the application by including UTM parameters in the URLs for announcements. The UTM parameters will provide valuable information for tracking the source, medium, and campaign associated with each announcement. The desired format for the UTM parameters is ?utm_source=platform&utm_medium={HOST_NAME}&utm_campaign=announcement. This enhancement will improve analytics and tracking for announcements on the platform.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by dcolina** [comment]
Internal QA: Passed.

**Comment by bryanboza** [comment]
Fixed, we always are adding those values as parameter at the end of the URL
