### ISSUE TITLE
dotCMS Inline Editing Only Applies the Last Change

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#27422]
### Problem Statement

When using the edit page functionality, making changes to the text elements inline (i.e. without clicking on the pencil icon) only applies the last change made when you go back to the preview menu

### Steps to Reproduce

This is reproducible on our demo site, and versions of dotCMS up to [52eaaa9](https://hub.docker.com/layers/dotcms/dotcms/master_52eaaa9/images/sha256-6e0aada45b0821fd8b9e2a56607c2703024e389308d3ef9af62032d4fa139f4c?context=explore)

Navigate to a page that has at least two text fields as part of the contentlets on the page. (On the demo.dotcms.com, the homepage works for this)
Go into edit mode
Click on the text you want to edit.
Make a change to one of the text fields.
Publish the change.
Go to edit mode again.
This time make a change to both of the text fields.
Go back to the preview mode, and notice that only the second text field you changed will have the changes reflected.

Recording here: https://drive.google.com/file/d/1HiMOmBnSiY2rqKF91wtlmsAZTDsduYod/view?usp=sharing

### Acceptance Criteria

Make the inline editing feature capable of editing multiple text fields in a single update

### dotCMS Version

master_52eaaa9 and below

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114934

### Quality Assurance Notes & Workarounds

I noticed that in the most recent master qa versions, there were major changes to the dotCMS UI. It appears that the edit page may no longer be separate from the preview going forward, which would make this issue irrelevant for future releases.

**Comment by wezell** [comment]
We are going to resolve this when we release our new edit content screen - issue #27546

**Comment by erickgonzalez** [comment]
Let's test this in the new UVE.

**Comment by gortiz-dotcms** [comment]
Issue not happening in the new UVE 

https://github.com/user-attachments/assets/bec98f23-cb18-430a-96ce-03ecacffdd16

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the latest trunk // Docker // FF
