### ISSUE TITLE
Modal Closing Enhancement for Announcements

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27434]
### Problem Statement

In dotCMS, there is an issue where the announcements window does not automatically close when users click outside the modal. This behavior deviates from standard modal interactions and can cause inconvenience for users who expect the modal to close when clicking outside its boundaries.

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Access the announcements window or modal.
- Click outside the modal, attempting to close it.
- Observe that the modal does not close, and users need to click again in the announcements logo to dismiss the window.

### Acceptance Criteria

**Modal Closing on External Click:** Implement functionality that allows users to close the announcements window by clicking outside the modal.
**User-Friendly Interaction:** Ensure that the modal closure occurs seamlessly, providing a user-friendly experience.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by damen-dotcms** [comment]
Fixing this brings the Announcement Menu in-line with the prototype.

**Comment by dcolina** [comment]
Internal QA: PASSED.

As we can see in the following video, the functionally works as expected it.

https://github.com/dotCMS/core/assets/29883881/07bf62dc-a607-40ed-be7a-2d32d3d20c5f
