### ISSUE TITLE
Unexpected Error in Sidebar Menu Portlet for DotAI

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#27443]
### Parent Issue

AI

### Problem Statement

An unexpected error is being displayed in the sidebar menu portlet specifically added for the DotAI feature. 

### Steps to Reproduce

1. Launch the application and access the DotAI feature
2. Expand the sidebar menu portlet designated for DotAI
3. Observe the unexpected error message displayed

### Acceptance Criteria

The sidebar menu portlet for DotAI should open without any errors, displaying all relevant options and features.

### dotCMS Version

24.01

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

<img width="1523" alt="Screenshot 2024-01-26 at 8 54 33 AM" src="https://github.com/dotCMS/core/assets/129882031/e31cf8db-3786-4a5d-8a78-aeb4facfc131">

**Comment by dsilvam** [comment]
Not able to reproduce.
