### ISSUE TITLE
CLI: Language.json should only contain isoCode

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27448]
### User Story

As a user, I want to be able to pull a language using a json file that only contains the isoCode and language name. For example: 

```
{
  "dotCMSObjectType" : "Language",
  "isoCode" : "es"
}
```

The other fields should be excluded from the JSON file (it applies for push operations as well). Only language (name) and iso code should be considered. 

{
  "dotCMSObjectType" : "Language",
  ~"id" : 4963328,~
  ~"languageCode" : "es",~
  ~"countryCode" : "",~
  ~"language" : "Spanish",~
  ~"country" : "",~
  ~"defaultLanguage" : false,~
  "isoCode" : "es"
}

Please modify the documentation and adjust the commands parameters accordingly

### Acceptance Criteria

- [ ] Language.json contains only these fields: `isoCode` and `dotCMSObjectType` (internal use only).
- [ ] The only input required by a language command is the isoCode  (when the json file is not provided).
- [ ] The documentation must be updated accordingly
- [ ] Update ITs

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

Now, it is pretty easy to manipulate languages using only the iso code.

**Comment by bryanboza** [comment]
Fixed, now the iso code is only the required parameter in the language.json file, we take this and generate all the other parameters based on that one. 
```
{
  "isoCode" : "es"
}
```

It will generate: 

```
{
  "dotCMSObjectType" : "Language",
  "id" : 4963328,
  "languageCode" : "es",
  "countryCode" : "",
  "language" : "Spanish",
  "country" : "",
  "defaultLanguage" : false,
  "isoCode" : "es"
}

```

Tested on master // Docker // FF

**Comment by jdcmsd** [comment]
I'm curious, how is the `id` property determined on the basis of the `isoCode` alone? Is it just assigned specifically for the case of a new language being added?

The reason I'm wondering: If languages are being pushed between sites during a migration, is it possible they could end up being assigned different `id` values, and could that have the potential to break code referencing language by id?
