### ISSUE TITLE
Change sorting criteria used in the site selector

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27447]
### User Story

As a user, I want to be able to see the most relevant host at the top of the list if I have a list of similar hosts in the system.  For example: 

Because we only show 15 hosts, take this case

You have these hosts :
```
testing1.host.dotcms.com
testing2.host.dotcms.com
testing3.host.dotcms.com
testing4.host.dotcms.com
testing5.host.dotcms.com
testing6.host.dotcms.com
testing7.host.dotcms.com
testing8.host.dotcms.com
testing9.host.dotcms.com
testing11.host.dotcms.com
testing12.host.dotcms.com
testing13.host.dotcms.com
testing14.host.dotcms.com
testing15.host.dotcms.com
testing16.host.dotcms.com
testing17.host.dotcms.com
testing20.host.dotcms.com
host.dotcms.com
```
And search for: `host.dotcms.com`

It is possible to NOT get the `host.dotcms.com` back in your 15 results, pretty much making impossible to ever change to `host.dotcms.com`.

To fix this problem, we should sort by the shortest. Meaning that if you search for `host.dotcms.com` it will come back as the top result.

We need to maintain wildcarding on both sides, e.g. like '%host.dotcms.com%'

dupe issue https://github.com/dotCMS/core/issues/26615
dupe issue: https://github.com/dotCMS/core/issues/26614

### Acceptance Criteria

- [ ] Sort by the shortest hostname
- [ ] Wildcard on both sides when searching, e.g. like '%host.dotcms.com%'

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
We fixed this a while ago https://github.com/dotCMS/core/issues/24921 but seems that the new changes probably broke it. This was a major issue for customers

**Comment by wezell** [comment]
@nollymar this card needs internal QA

**Comment by nollymar** [comment]
**Internal QA:** Needs Work

The sort criteria when I search is not consistent. 
For example: 

if I search for `host`, the site `testing1.host.dotcms.com` is returned after `testing9.host.dotcms.com` 

![Image](https://github.com/dotCMS/core/assets/8741395/b420b2fc-384d-44a0-a96a-b688115dd330)


but if I search for `test`, the site `testing1.host.dotcms.com` is returned before `testing2.host.dotcms.com`

![Image](https://github.com/dotCMS/core/assets/8741395/c7adaa23-8fd2-40f1-b515-475f02b32347)



https://github.com/dotCMS/core/assets/8741395/298c7dd5-61c3-43f1-84d7-f4cf1e3f6995

**Comment by wezell** [comment]
This is what I am seeing

https://github.com/dotCMS/core/assets/934364/9fcdc79c-df13-4917-960e-826e2ec746c0

**Comment by nollymar** [comment]
**Internal QA:** Passed
