### ISSUE TITLE
Apps portlet CSS issues

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27445]
### Problem Statement
App icons are being covered with a blue circle, which is interfering with the visibility and aesthetics of the icons.

Can't scroll thought the apps when the screen is smaller.

Scroll in the SAML app is broken, video

### Steps to Reproduce
1. Open the dotCMS dashboard.
2. Navigate to the Apps section.
3. Make the screen smaller **and see that doesn't scroll**
4. Then active an app
5. See how the icon gets covered.

![image](https://github.com/dotCMS/core/assets/751424/325d053c-a353-4c14-a7f3-06a87840b11a)

### Acceptance Criteria
The app icons should not be covered with a blue circle. Instead, a badge should be used to indicate any notifications or updates related to the app.

### External Links
- N/A

### Assumptions & Initiation Needs
- This bug affects all users of dotCMS.
- The bug is reproducible in the current version of dotCMS.
- The issue is not related to individual user settings or preferences.

### Quality Assurance Notes & Workarounds
- Currently, there is no known workaround for this issue.
- Quality assurance should verify that the app icons are no longer covered with a blue circle and that the new badge design is implemented correctly.

**Comment by zJaaal** [comment]
We have this issue. Although the video shows SAML we should be sure that this doesn't happen in any app.

# STRs

1. Go to apps portlet
2. Select an app (You can try with SAML as in the video)
3. Go to add settings for any site 
4. Add a really long text in a Text Area
5. Try to scroll with the mouse
6. See the error (The scroll is jumping and doesn't let you go to the bottom of the screen)

## Screenshot

https://github.com/dotCMS/core/assets/63567962/15c6ede6-f062-4018-bfab-b48498371f81

**Comment by KevinDavilaDotCMS** [comment]
The scroll jumping error is in stand by, we cannot replicate it yet

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // FF
