### ISSUE TITLE
Move AI Block accept/regenerate/discard options to the popup window

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27456]
Currently, the AI image block uses the following workflow:
1. Pop up a window for the user to enter the prompt
2. Generates the image as a block within the block editor
3. Popup a menu over the image, giving the user the options to Accept, Regenerate, or Discard the AI-generated image.
4. Once the user has accepted the image, it becomes a normal image block in the editor, and can be edited and manipulated exactly the same as any other image.

We need to move steps 2 and 3 of the workflow into the popup window.  So, all image generation and user accept/regen/discard options will be handled in the popup window, and the image won't be written to the block editor until the user has accepted the image (when it will be written to the block editor as a normal image block, the same as the current step 4).

This change will reduce the complexity of the AI image block code in the block editor, and give us a common interface to implement AI image generation in the Binary field.

Figma: https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?type=design&node-id=2083-15349&mode=design&t=1Ll8QNM2lfX6xcFL-0

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27632
- [ ] https://github.com/dotCMS/core/issues/27633
- [ ] https://github.com/dotCMS/core/issues/27640
```

**Comment by oidacra** [comment]
Waiting for the final design.

**Comment by oidacra** [comment]
Passed IQA

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_77989c8**, Docker, macOS 13.0, FF v121.0.1
