### ISSUE TITLE
Final regression to new binary field 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27459]
### Task

Since we are close to release that feature, we need to do a final regression over that functionality, we need make sure nothing is broken and it is working as expected. 

Please create//update a list of BASIC test cases for this binary field and save this in a CSV file. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

### Acceptance Criteria

- Test cases in a CSV file

**Comment by josemejias11** [comment]
**QA Comment**

List of basic Test Cases
[Binary Field.csv](https://github.com/dotCMS/core/files/14168978/Binary.Field.csv)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d201a7c**, Docker, macOS 13.0, FF v121.0.1
