### ISSUE TITLE
Adjust Announcements Menu Icon Size 

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27463]
### Parent Issue

#25733 

### Task

Announcements Menu Icon Size Adjustment:

The size of the Dot Icon in the announcements menu should match the dimensions specified in the corresponding Figma file.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The size of the Dot Icon in the announcements menu should match the dimensions specified in the corresponding Figma file.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_961dfb7**, Docker, macOS 13.0, FF v121.0.1
