### ISSUE TITLE
AI viewtool generateText not working

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27468]
### Parent Issue

https://github.com/dotCMS/core/issues/27440

### Problem Statement

The tool`$ai.generateText` is not working because it is sending the wrong parameters to the inner request to the AI service.

### Steps to Reproduce

1. Install the AI plugin
2. Add a code snippet to a page that includes `$ai.generateText("my prompt")`
3. Render the page
It will fail to generate the text

### Acceptance Criteria

Steps above working as expected.
User should be also able to send a JSON instead of a String to include additional config values. 

### dotCMS Version

AI Plugin / main

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_4a3fb81**, Docker, macOS 13.0, FF v121.0.1
