### ISSUE TITLE
Update Announcement Menu Links

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#27479]
We updated the menu links, updated the design, and switched all the links to use vanity URLs that we can easily change if needed once the feature is in production.

Here are the new designs.

https://www.figma.com/proto/3f17xtGfHmJx3RuC9YhQox/Announcements-Menu?type=design&node-id=1-2007&t=WFcZV2xAww29eM1C-0&scaling=min-zoom&page-id=1%3A3&starting-point-node-id=1%3A2007&show-proto-sidebar=1

<img width="482" alt="image" src="https://github.com/dotCMS/core/assets/114953617/1b403f89-0fdc-4d82-bb76-93195a99f357">

And here are the links.

Just a broad reminder, please make sure all links here have the UTM codes attached. The UTM codes will pass over to dotCMS pages, and they don't matter for non-dotCMS pages. (But if we ever switch the links to point to dotCMS pages the UTM codes will be there.)

## Announcement Menu Link - Documentation

* Menu URL : https://www.dotcms.com/announcement-menu-documentation
* Destination : https://www.dotcms.com/docs/latest/table-of-contents

## Announcement Menu Link - dotCMS Blog

* Menu URL : https://www.dotcms.com/announcement-menu-dotcms-blog
* Destination : https://www.dotcms.com/blog/

## Announcement Menu Link - Online Training

* Menu URL : https://www.dotcms.com/announcement-menu-online-training
* Destination : https://www.dotcms.com/courses/

## Announcement Menu Link - User Forum

* Menu URL : https://www.dotcms.com/announcement-menu-user-forum
* Destination : https://groups.google.com/g/dotcms

## Announcement Menu Link - Customer Support

* Menu URL : https://www.dotcms.com/announcement-menu-customer-support
* Destination : https://helpdesk.dotcms.com/
* Note : At the time this ticket was created, Zendesk is getting hung up on the redirect right now -- I'm sure we'll find a way to fix it.

## Announcement Menu Link - Professional Services

* Menu URL : https://www.dotcms.com/announcement-menu-professional-services
* Destination : https://www.dotcms.com/services/professional-services/

## Announcement Menu Link - GitHub Repository

* Menu URL : https://www.dotcms.com/announcement-menu-github-repository
* Destination : https://github.com/dotCMS/core

## Announcement Menu Link - Report a Bug

* Menu URL : https://www.dotcms.com/announcement-menu-report-a-bug
* Destination : https://docs.google.com/forms/d/e/1FAIpQLSerOflJQDHRAgwApDwPCr856nIQLU_1VQTJj0p8HhjEbzVS3A/viewform
* Note : At the time this ticket was created, this form is not yet complete but the URL is fine.

## Announcement Menu Link - Request a Feature

* Menu URL : https://www.dotcms.com/announcement-menu-request-a-feature
* Destination : https://docs.google.com/forms/d/e/1FAIpQLSdPBPUWwEA2vE5dy_4GaujbMD27pF5oShZy6FRnEK8S1PoCQQ/viewform
* Note : At the time this ticket was created, this form is not yet complete but the URL is fine.

## Announcement Menu Link - Show All

* Menu URL : https://www.dotcms.com/announcement-menu-show-all
* Destination : https://www.dotcms.com/announcements/

**Comment by damen-dotcms** [comment]
<img width="481" alt="image" src="https://github.com/dotCMS/core/assets/114953617/c9735213-4d85-4911-8e12-8f97d09bd80d">

I lost my Figma privs, but this should say "dotCMS Blog" not just "Blog" - thanks! (=

**Comment by damen-dotcms** [comment]
Added "Show All" Vanity URL.

**Comment by nollymar** [comment]
**Note to QA:** Please, test in Firefox that the background page is white even when the default settings are changed

**Comment by dcolina** [comment]
Internal QA: Passed.

As we can see below.



https://github.com/dotCMS/core/assets/29883881/d2d2192e-20f1-43cc-96e9-f6cedb2d0a68

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_b4779ec**, Docker, macOS 13.0, FF v121.0.1
![Screenshot 2024-02-07 at 9 03 21 AM](https://github.com/dotCMS/core/assets/129882031/aa8e82a1-1b08-481c-aca3-aa32dfbf2260)


"Blog" needs to be renamed to "dotCMS Blog"

**Comment by dcolina** [comment]
Internal QA: Passed.

As you can see in the following screenshot.

![Screenshot 2024-02-09 at 18 13 02](https://github.com/dotCMS/core/assets/29883881/87d421cf-0aab-42f9-821f-af4c3b0d83b2)

**Comment by josemejias11** [comment]
**Approved**: Tested on ** master_72a3d00**, Docker, macOS 13.0, FF v121.0.1
