### ISSUE TITLE
Embeddings index not updating correctly.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#27473]
### User Story

Steps to reproduce: 

1. Install the AI plugin. 
2. Create a specific content type
3. Add the subaction `AI Embeddings` in publish and unpublish ( see video ) with the param of the just created content type. 
4. Create and publish new content, the index update token / content . 
5. Unpublish that content, the index do not decrease the tokens / content. 
6. Both `default` and `wf-test2` should decrease. 

https://github.com/dotCMS/core/assets/31667212/a3a9b3be-3aa5-4948-a68f-33231bf5a7c0

Scenario 2: 

1. Install the AI plugin. 
2. In the app - dotAI  portlet add `Auto Index Content Config`
3. publish and unpulbish content. 
4. see how the index `falcon` and `qa` do not decrease when unpublish the content. 

https://github.com/dotCMS/core/assets/31667212/a9b9aa1d-cec4-48b2-8347-286abbedf67e

### Acceptance Criteria

AI Embeddings index should be updated correctly when publish or unpublish. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
Pass internal QA: after following the steps in the video the index is being updated correctly, in the s`ub action` scenario and in the `Auto Index Content Config`

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a090821**, Docker, macOS 13.0, FF v121.0.1
