### ISSUE TITLE
Modal Management Enhancement for Announcements

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27472]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Problem Statement

In dotCMS, there is an issue where the announcements modal does not automatically close when users open another window, leading to overlap between the announcements modal and the new window. This behavior can be confusing and negatively impact the user experience.

![Screenshot 2024-01-30 at 1 31 06 PM](https://github.com/dotCMS/core/assets/2641437/88c9730b-f206-4cd7-9a21-96856dcc1b71)

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Open the announcements modal.
- Without closing the announcements modal, open another window or perform an action that triggers a new window.
- Observe that the announcements modal overlaps with the new window, causing a visual conflict.

### Acceptance Criteria

- **Automatic Modal Closure**: Implement functionality that automatically closes the announcements modal when users open another window, preventing overlap and ensuring a clean user interface.
- **User-Friendly Transition**: Ensure that the modal closure occurs smoothly, providing users with a seamless transition between windows.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by damen-dotcms** [comment]
Yeah, as soon as you click anywhere outside of the menu, it should close the menu.

This way, if one menu is open, and you click on another, the original menu would close.

**Comment by dcolina** [comment]
Internal QA: PASSED.

As we can see in the following video, the functionally works as expected it.


https://github.com/dotCMS/core/assets/29883881/2f3b2ffc-8c81-46b4-80f3-f440c2779ce3

**Comment by bryanboza** [comment]
Fixed, now we are closing this modal when you click outside. Tested on mater // Docker // FF
