### ISSUE TITLE
Checkbox Background Issue

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27486]
### Problem Statement
The checkbox has a transparent background (when checked) which doesn't look good when the page background is different than white.

### Steps to Reproduce
1. Navigate to a page with a non-white background.
2. Add a checkbox element to the page.
3. Check the checkbox.

### Acceptance Criteria
- The checkbox background should be white at all times.
- When the checkbox is checked, the background should remain white.
- Angular and Dojo

### External Links
None

### Assumptions & Initiation Needs
- The problem occurs when the page background is not white.
- The issue is not limited to a specific browser or operating system.

### Quality Assurance Notes & Workarounds
- QA should test the checkbox on different pages with various background colors.
- If the checkbox background is still transparent after applying the fix, the cache should be cleared and the page reloaded.

**Comment by zJaaal** [comment]
# IQA Passed

You can see in the screenshots how when you force backgrounds, checked and unchecked checkboxes remains with white background

docker image: `[dotcms/dotcms:master_a38321e]`

### Screenshots

#### Dojo

<img width="1512" alt="Screenshot 2024-02-06 at 10 25 16 AM" src="https://github.com/dotCMS/core/assets/63567962/d9c6474e-9ce9-468e-af2f-55114c7d4f42">

#### Angular
<img width="1512" alt="Screenshot 2024-02-06 at 10 26 23 AM" src="https://github.com/dotCMS/core/assets/63567962/41831541-42f3-4d07-9bc1-a0339213f392">
<img width="1512" alt="Screenshot 2024-02-06 at 10 26 34 AM" src="https://github.com/dotCMS/core/assets/63567962/0f54cefe-00d5-47f9-bad0-70ff5d03ea25">
