### ISSUE TITLE
Update AI Text and AI Image generation to include all actions in the popup

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27482]
### Define the Problem

Currently, the AI Image block in the block editor pops up a window to allow the user to make selections.  The first selection is whether or not to use the existing content to generate the image, and the second option is to enter a prompt (or for auto-generation, additional text to refine the prompt).  After that, the popup closes, and the generated image is placed into the block editor, where a popup menu appears giving the user the option to Accept, Regenerate, or Discard the image.

We need to make a few changes to the interface:
1. Present both the image and all user choices after the image is generated in the popup, not the editor itself.
2. Add a new option to the prompt entry screen to allow the user to select the image orientation.
3. Display a new field, "Expanded Prompt", when displaying the image.
    * The user must be able to edit this field before hitting "Regenerate".

This means that once the user hits the "Generate" button, instead of closing, the popup window will show a new screen, which will show a "working" icon while the image is being generated, and then display the generated image once it's available.

Once the generated image is displayed, the user will be presented with the following info in the screen:
* User Prompt (editable multi-line text field)
* Expanded Prompt (editable multi-line text field)
* Orientation (editable single-selection field - e.g. radio or drop-down)
    * Options are "Square", "Horizontal", or "Vertical".
* The generated image (read only)
* Action buttons:
    * Accept (adds the image to the block editor)
    * Regenerate (regenerate the image)
    * Discard (close the popup without saving anything)
    * Back (goes back to allow the user to change the initial selection of standard prompt vs. auto-generate)

Once the user has accepted the image, the popup will close, and the image will be inserted as a normal image block in the block editor.  (There will be no menu or other controls in the block editor that aren't part of the existing image block).

### Who's Facing the Problem?

* End users:
    * Most users don't know there's an option to select an image size, so this will add an option for them without the need for them to type in extra text.
    * We aren't displaying the expanded prompt now, but displaying that will make it easier for users to refine their image.
* dotCMS developers:
    * These changes will simplify the AI block code in the block editor.

### Screenshot or Video

![image](https://github.com/dotCMS/core/assets/13456955/c17e30da-1b59-4f94-b80e-a10a3ebc87a2)

![image](https://github.com/dotCMS/core/assets/13456955/321f93d9-97e0-4172-a75e-ab5c791c1252)

### Relevant Links and Resources

We could potentially have all of this in a single screen which doesn't change - and therefore wouldn't need a Back button.

But it might be nice to sort of guide users through the choices in order (standard prompt vs. auto-generate first, image size second, prompt third).  Whether that makes more sense to do in a single screen or with a sequence of screens, I have not opinions on.

**Comment by oidacra** [comment]
Fixed with https://github.com/dotCMS/core/issues/27456 EPIC
