### ISSUE TITLE
Edit Ema: Error on Generate Dynamic Pages in NextJS [Research] 

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27483]
### Parent Issue

#26644

### Task

When generating dynamic pages in NextJS, the `getMetadata` method may throw an error stating that the page title is not available/found.

Take an hour to research the issue. [See NextJS Documentation](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#dynamic-metadata)

<img width="1954" alt="dynamic pages erros" src="https://github.com/dotCMS/core/assets/72418962/908afb8d-9a47-49ba-b737-7863ace07b4e">

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

Take a look at how we retrieve the list of potential values for `[[...slug]]`

**Comment by rjvelazco** [comment]
Unable to reproduce on existing pages. We are going to keep an eye on this `issue`.

**Comment by fmontes** [comment]
Can't repro.
