### ISSUE TITLE
Implement Announcement Menu with "Mark as Read" Feature

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27494]
### Parent Issue

#25733 

### Task

Enhance the announcement menu in our application to feature an unread indicator (dot icon) for unread announcements. When a user clicks on an announcement, mark it as read and remove the unread indicator. Ensure that the read status persists even when the page is refreshed.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

When a user clicks on an announcement:
Remove the dot icon to indicate it is read.
Update the status of the announcement to "read"

**Comment by manuelrojas** [comment]
QA Note, How to test video:



https://github.com/dotCMS/core/assets/3438705/3d53a3e7-3679-4bf7-ab7c-a32021e6b605

**Comment by dcolina** [comment]
Internal QA: Passed.

Only the latest announcements are marked as un read, as we can see in the following video. 


https://github.com/dotCMS/core/assets/29883881/b55f8ea3-f2e3-418d-8365-9922428c59cf

**Comment by bryanboza** [comment]
We need some work here after have the first 5 notifications 

Here the video: 


https://github.com/dotCMS/core/assets/2641437/15fba225-7088-488d-8a2f-229884142864

**Comment by bryanboza** [comment]
Seems this is related to a firefox behavior, we need to take care of this as part of the supported browsers!

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
