### ISSUE TITLE
CLI: Content Type "orderBy" not working

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#27493]
### Problem Statement

When fetching lists of Content Types, it is not possible to select which property they are ordered by. This was discovered through the CLI, but it seems to point to a deeper issue, since the CLI is making use of this more general operation:

https://github.com/dotCMS/core/blob/48df234d80717dc47ad586bee8944d2ba1442ab7/dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResource.java#L719

### Steps to Reproduce

1. Use dotCMS CLI to sign in to Demo with `<dotCLI> login -u admin@dotcms.com -p`
2. Return a list of Content Types ordered by modDate with `<dotCLI> content-type find --name Blo --order modDate`
3. It returns a list like this, with no clear order by modDate:

```
varName: [Blog] modDate:[2024-01-31 07:02:38]
varName: [BlogAuthor] modDate:[2024-01-31 07:02:24]
varName: [BlogComment] modDate:[2024-01-31 07:02:23] 
varName: [BlogCommentor] modDate:[2024-01-31 07:02:24] 
varName: [TestBlockEditor] modDate:[2024-01-31 09:22:25]
```
Attempting with other `--order` properties such as iDate, urlMapPattern, id, siteName, etc., likewise does not change the order of returned Content Types.

### Acceptance Criteria

The `orderBy` / `--order` option should affect the ordering of returned Content Types.

### dotCMS Version

24.01.26

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Needs work

The order is working fine. However, we are not being consistent with the property names with list in the find output with the properties we use in the order criteria. For example: in the image you can notice that we list `varName` but we need to specify `variable` in the order criteria. For an end user it is not intuitive.



![Image](https://github.com/dotCMS/core/assets/8741395/ed7ad3ba-3655-42e4-b520-2e28b6e6773c)

**Comment by nollymar** [comment]
**Internal QA**: Passed

![Image](https://github.com/dotCMS/core/assets/8741395/eb7e517d-8d6c-488f-b27b-8b4f5f5db93c)
