### ISSUE TITLE
Duplicated Index Name in 'Content Index to Search' List

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#27507]
### Parent Issue

AI

### Problem Statement

When attempting to build a new index with a name that matches an existing index, the system incorrectly adds this new index to the 'Content Index to Search' list.

### Steps to Reproduce

1. Navigate to the dotAI Portlet 
2. Go to Manage Embeddings/Indexes
4. Create or identify an existing index with a specific name
5. Attempt to build a new index, using the exact name as the existing one
6. After the index build process, check the 'Content Index to Search' list

### Acceptance Criteria

The system should either prevent the creation of an index with a duplicated name or handle it in a way that does not result in confusing duplicates within the search selection list. Now you need to refresh the page to see the correct list

### dotCMS Version

24.01

### Proposed Objective

Integrations

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2024-02-02 at 3 01 27 PM](https://github.com/dotCMS/core/assets/129882031/00e238db-edbf-4a33-bd49-6bf5c94d097f)

**Comment by dsilvam** [comment]
Passed Internal QA: No more duped indices in the list.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b4779ec**, Docker, macOS 13.0, FF v121.0.1
