### ISSUE TITLE
Sub-Action Parameters Not Displayed for AI Workflow Actions

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#27508]
### Problem Statement

In the AI Workflow configuration interface, parameters for configured sub-actions under AI Workflow actions are not being displayed. 

### Steps to Reproduce

1. Navigate to the Workflows 
2. Go to System Workflows 
3. Select an existing Workflow 
4. Add the AI Workflow Sub-Action
5. Attempt to view or edit the parameters for any of the sub-actions

### Acceptance Criteria

Users should be able to see and edit parameters for sub-actions within an AI Workflow, allowing for detailed configuration of each step in the workflow.

### dotCMS Version

24.01

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

![Screenshot 2024-02-02 at 3 18 00 PM](https://github.com/dotCMS/core/assets/129882031/3a35fe02-023e-409d-93a8-e618ee9546a1)

**Comment by dsilvam** [comment]
Seems to be related to restarting the OSGI framework. Closing it for now. Can reopen it this bugs us again
