### ISSUE TITLE
Content Search: The active state styles are not being displayed for the checkbox

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27503]
### Task

- [ ] Fix the checked styles for the checkbox.

https://github.com/dotCMS/core/assets/72418962/965d1617-004d-4d21-bc7d-b92ea1547628

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master

https://github.com/dotCMS/core/assets/144152756/b52f6db0-ef06-425b-8505-2ecbde922576

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a38321e**, Docker, macOS 13.0, FF v121.0.1
