### ISSUE TITLE
Plugin Requires Multiple Restarts for Full Access to OpenAI Embeddings Workflows

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#27511]
### Parent Issue

AI

### Problem Statement

An issue where the plugin related to OpenAI Embeddings Workflows (Sub-Action) necessitates several restarts before getting access to its functionalities.

### Steps to Reproduce

1. Install or update the plugin associated with OpenAI Embeddings Workflows
2. Attempt to access the full range of features in the OpenAI Embeddings Workflows (Sub-Action) immediately post-installation or update
3. You need to restart the plugin multiple times to achieve full functionality access

### Acceptance Criteria

After the initial installation or update and subsequent restart of the plugin, users should have immediate and full access to all features within the OpenAI Embeddings Workflows (Sub-Action) without additional restarts.

### dotCMS Version

24.11

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

![Screenshot 2024-02-05 at 8 33 23 AM](https://github.com/dotCMS/core/assets/129882031/408a2a68-8cd2-424b-9918-34fe4f201fb7)

**Comment by john-thomas-dotcms** [comment]
Some code changes were made to prevent this behavior.  Need to retest (internally).
