### ISSUE TITLE
Google Maps does not work on the rules page

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#27531]
### Parent Issue

https://github.com/dotCMS/core/issues/14568

### Problem Statement

The Google Maps feature within the visitor location rule on the rules page shows "this page can't load Google Maps correctly"

### Steps to Reproduce

Generate an API key on Google Cloud
Add the API key to the site configuration for dotCMS
Save the configuration
Go to the rules page and add a new rule
Select Visitor's location in the first dropdown
Click +Show Map
The Google Map that is displayed will show the error
![Screenshot 2024-02-06 at 1 28 50 PM](https://github.com/dotCMS/core/assets/136110669/884f4095-8775-4725-90e6-0b39852588a6)

### Acceptance Criteria

Allow the rules page to load the Google Maps API with the API key

API Key should be pulled from the Site definition (there is a Google Map Field in the Site Content Type).

### dotCMS Version

5.3.8.14 +
Also happens in most recent qa branch

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110883
https://dotcms.zendesk.com/agent/tickets/114986
https://dotcms.slack.com/archives/CSHTYUR7H/p1681329439715809

**Comment by erickgonzalez** [comment]
We're not reading from anywhere the key here https://github.com/dotCMS/core/blob/f116137684439500f31e558e7760c8fb71a175ce/core-web/libs/dot-rules/src/lib/services/GoogleMapService.ts#L14 

We need to read the key from the Site Content Type.

**Comment by AndreyDotcms** [comment]
Some tests done in Internal QA

https://github.com/dotCMS/core/assets/127987858/d6a5e134-fc6a-4ac8-ac9d-f5e5fcb67a14

**Comment by erickgonzalez** [comment]
Working as it should, now it shows the map without issues.

![Image](https://github.com/dotCMS/core/assets/5278970/27d77d3a-da10-4dee-bffb-47a5c475a6e8)

**Comment by bryanboza** [comment]
Fixed, now I'm able to open the map without problems 


![Image](https://github.com/dotCMS/core/assets/2641437/561c1fd7-6ad1-4cfb-9931-b1d26dd1cfac)
