### ISSUE TITLE
Issue with Widgets (URL field not being overrided if the content type has a field by name URL)

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#27538]
### Problem Statement

Issue with Widgets (URL field not being override if the content type has a field by name URL)
We have a URL field in the XML/JSON of each contentlet and this has a default URL field mapped similar to 
`<url>/content.6a9bd00a-0862-4755-8161-973f47723193</url>`
![image](https://github.com/dotCMS/core/assets/139247809/0d906c66-0c59-47b2-9099-32fa450deb20)
In normal content types , If we have a field with a same name URL , this is being overriden and actual content is being reflected on the URL field 
![image](https://github.com/dotCMS/core/assets/139247809/6bff83d2-7abf-45b9-a7b0-dab13af4450e)
![image](https://github.com/dotCMS/core/assets/139247809/ab8755ed-7554-4512-98f8-7dfbcd778ecd)

Widgets are not showing similar behaviour
The URL field is not being updated 

### Steps to Reproduce

1. Login to demo
2. Create a sample widget with a text field name URL
![image](https://github.com/dotCMS/core/assets/139247809/b329f0c1-f2aa-450c-a21f-474395df3508)

3.  Access the XML/json of the contentlet after publishing
4. This will have a URL field as below ( This should be reflecting the text added in the URL field of the widget). It is currently having content./inode
![image](https://github.com/dotCMS/core/assets/139247809/113fef9a-6db5-45b3-8729-11b26f3e3468)

### Acceptance Criteria

The URL Field value should reflect the text added in the URL field of the widget. It is currently having content./inode
This is working fine with the other content types

### dotCMS Version

23.10.24.LTS

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115031

**Comment by erickgonzalez** [comment]
Investigate how it behaves with the other base types; let's post the results here.

**Comment by gortiz-dotcms** [comment]
It happens with widgets but also with dotAssets.
File assets also have a default URL field in which the location info will be set and it won't be overridden, so let's keep this behaviour in this case.

**Comment by erickgonzalez** [comment]
Working as it should now, the URL is showing the value set.

![Screenshot 2024-11-13 at 12 26 32 PM](https://github.com/user-attachments/assets/81748a55-2c1f-4477-ae51-800afa8136f3)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after this fix, now we are showing the URL value. 

Tested on the latest trunk // Docker // FF
