### ISSUE TITLE
Create a plugin to get google analytics report

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27559]
### User Story

As an user, I want to be able to install an osgi plugin, in order to get the google analytics reports

### Acceptance Criteria

The plugin can connect with google analytics and provide the reports

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
Code here: [https://github.com/dotCMS/google-analytics](https://github.com/dotCMS/google-analytics)

**Comment by john-thomas-dotcms** [comment]
@jdotcms we already have the Dashboard, which was created to be able to show analytics reports.  But the dashboard doesn't currently work with GA4.

So, do we need a separate plugin, or should we just update the dashboard to work with GA4?

**Comment by fmontes** [comment]
Done for v3.
