### ISSUE TITLE
Edit Page V2: Provide Shortcut to Edit Content

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27561]
### Parent
#27546 

### User Story
As a content editor, I want to be able to easily edit a piece of content that generates a page, so I can make updates efficiently.

https://github.com/dotCMS/core/assets/751424/e960a772-bead-4618-9993-1bb95bac100a

```[tasklist]
### Acceptance Criteria
- [ ] A button is added to the page editor interface. (UI coming soon)
- [ ] Clicking the button opens a dialog to edit the corresponding piece of content.
- [ ] After making changes in the dialog, clicking "Save" closes the dialog and refreshes the page.
```

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
Static content: "N/A"

### Assumptions & Initiation Needs
- The location of the actual content is unknown.
- The button can be added dynamically to the page editor interface.

### Quality Assurance Notes & Workarounds
No additional notes at this time.

**Comment by rjvelazco** [comment]
## Note for QA

If you modify the `URL_CONTENT_MAP` of a page, you may encounter a "NOT_FOUND" error page. There is another ticket for that https://github.com/dotCMS/core/issues/27855

**Comment by fmontes** [comment]
The position of the button is not final, we are working with UX to improve that.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_f3b48ba**, Docker, macOS 13.0, FF v121.0.1

Button is present and it shows the correct page to be edited.

<img width="1546" alt="Screenshot 2024-03-19 at 12 58 14 PM" src="https://github.com/dotCMS/core/assets/129882031/ea9cbe4d-5b27-4005-b581-a08bf48a94fa">
