### ISSUE TITLE
Site or Folder field does not show on the relate content window

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#27563]
### Parent Issue

https://github.com/dotCMS/core/issues/24194
https://github.com/dotCMS/core/issues/24290

### Problem Statement

Site or folder field does not show up on the relate content window. This is believed to stem from when we removed the 'User searchable' option was removed from the Site or Folder field, and instead it was added to Search automatically when the field was added to a content type. This was missed for the relate content window.

### Steps to Reproduce

1. From a demo starter, look at a Blog contentlet.
2. Try to relate a new author, you will see the Site or Folder available for search
3. Go To Content Types and select the Blog Author Content Type
4. Remove the Site or Folder Field.
5. Add the Site or Folder Field.
6. Try to relate a new author again, you will no longer see the Site or Folder field available

### Acceptance Criteria

You should be able to relate to content from other sites when the related content type has a site or folder field.

Let's do this like in the Content Search portlet, which always shows the host or folder field regardless if is user searchable or not.

### dotCMS Version

23.10.24, latest

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115144

**Comment by erickgonzalez** [comment]
Now, we always show the site or folder field regardless if is searchable or not.

![Image](https://github.com/dotCMS/core/assets/5278970/2b32ff77-d09f-43d1-8c5f-cb91222ed602)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_270ac3c**, Docker, macOS 13.0, FF v121.0.1
<img width="569" alt="Screenshot 2024-03-06 at 4 14 46 PM" src="https://github.com/dotCMS/core/assets/129882031/b2374aa1-c8c7-4f80-8050-3d62993ff693">

**Comment by erickgonzalez** [comment]
Only for 23.10 LTS
