### ISSUE TITLE
Add the ability to insert custom URLs in the dotCMS WYSIWYG editor

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#27578]
### User Story

As an edit-mode-anywhere user, I want to be able to add prefixes to links in the editor, so that I can retrieve images and pages based on exactly the string I need from the autofill, rather than needing to add the prefixes manually.

### Acceptance Criteria

Add functionality to the editor such that adding images and URLs allows for users to insert links using relative paths.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114929

**Comment by prestonso** [comment]
Accounted for within Edit Content Enhancements in Airfocus.
