### ISSUE TITLE
CLI: Fix Incorrect Version Display in `dotcli --version` Command

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27593]
### Problem Statement
The `dotcli --version` command does not display the correct version of the CLI. Currently, it shows the same message regardless of the published version of the package, which is incorrect.

### Steps to Reproduce
1. Install the dotCLI package `npm i -g @dotcms/dotcli`.
2. Run the command `dotcli --version`.

### Acceptance Criteria
- When running `dotcli --version`, it should display the accurate version of the CLI corresponding to the installed package.

You can check the `dotcli` current version number  just running the command `npm view @dotcms/dotcli`

### dotCMS Version
N/A

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links
N/A

### Assumptions & Initiation Needs
- This issue assumes that the correct version information is available within the package.
- Initiation requires access to the codebase for the `dotcli` tool.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by nollymar** [comment]
**Internal QA:** Passed



![Image](https://github.com/dotCMS/core/assets/8741395/50c1cc8d-7344-42b7-82d8-522043f0a23f)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
