### ISSUE TITLE
UI: Label overridden by edit Icon 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27599]
### Problem Statement

In dotCMS, there is an issue where the label associated with an item is being overridden by the edit icon, causing confusion and potentially hindering user interactions.
![image](https://github.com/dotCMS/core/assets/2641437/28e54c8e-b9d7-4421-a67c-9402d20415f4)

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Navigate to  the content search portlet 
- Right click any of the items and observe that the edit icon overlaps or obscures the associated label.

### Acceptance Criteria

- **Label Visibility Preservation:** Implement a solution to ensure that the label associated with an item remains visible and unobscured by the edit icon.
- **Clear Visual Distinction:** Ensure that there is a clear visual distinction between the label and the edit icon to prevent confusion for users.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by KevinDavilaDotCMS** [comment]
# Cannot reproduce the issue

Tested in master in Chrome/ Chromium based/ Firefox


https://github.com/user-attachments/assets/8e2ca6ad-116d-4bcd-a68e-d462377e1581

**Comment by bryanboza** [comment]
Fixed, now this looks better 


![Image](https://github.com/user-attachments/assets/bf57ada2-cd2c-4588-8361-9238788e4335)
