### ISSUE TITLE
Unhandled Exception: Failed to Fetch Error Not Caught in Preview with SEO Feature

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27601]
### Problem Statement

![image](https://github.com/dotCMS/core/assets/3438705/9c57e442-e52a-489b-ab0b-753138f443ca)

![image](https://github.com/dotCMS/core/assets/3438705/ad3410e3-73f2-45a8-9c11-30f9c7bc753e)

### Steps to Reproduce

1. Enable the preview mode in the application.
2. Navigate to a page with the SEO feature enabled, triggering a fetch operation within an RxJS observable pipeline.
3. Allow the fetch operation to fail (e.g., by providing an invalid URL).
4. Observe the uncaught exception "Failed to fetch".

### Acceptance Criteria

I expected the fetch error "Failed to fetch" to be caught and handled properly within the RxJS observable pipeline, even in the context of the preview with the SEO feature enabled. This would prevent an uncaught exception and ensure the application behaves as expected in the preview mode.

### dotCMS Version

--

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
I verified in the latest master that the exception is no longer coming up

**Comment by bryanboza** [comment]
Unable to reproduce in the last master...
