### ISSUE TITLE
Create New Designs for Input Field Helper Text

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#27622]
### Task

I want to redesign the helper text icons next to input fields to make them more visible, accessible, and generally usable.

**Default** 

<img width="170" alt="image" src="https://github.com/dotCMS/core/assets/114953617/25cd8954-d612-461c-9723-c2236d2736ac">

**Default mouse-over**

<img width="412" alt="image" src="https://github.com/dotCMS/core/assets/114953617/2d0e7e1e-48ff-44b6-b2ff-81d19e9b78b7">

**Note, customization to make persistent text is still possible. But has to be done with an additional custom field under the input field. Kinda tedious.**

<img width="275" alt="image" src="https://github.com/dotCMS/core/assets/114953617/3c7af677-0060-42c5-9766-c879f5d17c37">

**UX Suggestion**

Feel free to ignore this. (=

<img width="428" alt="image" src="https://github.com/dotCMS/core/assets/114953617/93208921-cbbe-4bae-84c0-0da16eba385d">

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Need designs for the "Helper" text or "Hint" as it's sometimes called in the Content Model.

Should pass WCAG contrast, and also the new "persistent helper text" guideline.

Probably good to cap the default shown around 55 Characters.

Currently "Hint" Text can't be longer than 255 Characters... feels like this is an artificial limitation.

(Should change "Hint" to "Helper Text" in the Demo and Starter -- let's nail down the terms we want to use.)

Would be nice if Helper Text could be longer than 255 Characters, and allow for rich text, and links to external sites to be include in it (with the option to pop the link in a new tab). 

The current error when "Hint" Text is too long is quite ugly. Worse, when you get this error all of the data you entered is lost and you have to re-enter it again. Really junky UX.

<img width="420" alt="image" src="https://github.com/dotCMS/core/assets/114953617/6a5e93f8-68ed-406e-8054-e23bf55b1fb9">

Lastly, some cursor types are misaligned on the Edit Content Model Screen; these would be a separate ticket but likely we need some direction here on what to do when a "Pointer" for a link and "Drag" action overlap. 

https://github.com/dotCMS/core/assets/114953617/8bc07e08-62a0-4679-8cc4-4f296e0cc744

**Comment by melissarojas-dotcms** [comment]
[Link to the Figma file ](https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=967%3A23392&mode=design&t=cPdvO0z1JdlGwI59-1)
