### ISSUE TITLE
CLI: Remove site current command

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27628]
### Task

The command `site current` is not used anymore. We need to remove any related code and update documentation accordingly

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, now we are unable to use this command anymore 


![Image](https://github.com/dotCMS/core/assets/2641437/f68a2bca-542b-46fb-a4f4-3e92548f66b0)
