### ISSUE TITLE
QA: Document the onboarding process for new resources 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27626]
### Task

As part of the department documentation we need to implement a basic guide how to setup the QA env and explain about the tools we use as department. 

This will help the new resources on the onboarding process. We need a basic document with some guide about the things we need to setup in the computer in order to be ready to start with the CMS explanation. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**QA Comment**

Adding documents as drafts
[Technical Guide for Security Testing.docx](https://github.com/dotCMS/core/files/14524890/Technical.Guide.for.Security.Testing.docx)
[Onboarding_20240229_theDot.xlsx](https://github.com/dotCMS/core/files/14524891/Onboarding_20240229_theDot.xlsx)

**Comment by josemejias11** [comment]
**QA Comment**

Update 2024/03/27
https://docs.google.com/document/d/12ZV9L6qb7tBdayWzbBYTJ-IwPeQRwdHK0dmnYnnLYMU/edit?usp=sharing

**Comment by bryanboza** [comment]
Here are the new links to access the docs: https://drive.google.com/drive/folders/1akSGX7nhUlEU31Ry78Tg_zQj_X-Qx8Bo

**Comment by bryanboza** [comment]
We can close this for now... 

The part 1 is done, we will create another one for the part 2
