### ISSUE TITLE
QA: List test cases for AI plugin 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27620]
### Task

We need to document the list of basic test cases to cover the functionality of this plugin 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- Need to list the test cases on a CSV file 
- Need be added to the google repository

**Comment by josemejias11** [comment]
**QA Comment**

Attach the document
[dotAI_TCs.csv](https://github.com/dotCMS/core/files/14285301/dotAI_TCs.csv)
