### ISSUE TITLE
Implement the AI content text generation in a Dialog.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#27633]
### Parent Issue
#27456

### User Story
Migrate AI content generation logic to a popup interface and handle content creation and acceptance within the popup.

### Acceptance Criteria

- All existing functionalities for AI content generation are available within the popup.
- Users can access and modify settings to influence content creation.
- Generated content displays directly within the popup.
- Users can accept or reject generated content within the popup.
- The popup UI is user-friendly and intuitive for content creation and acceptance.

### dotCMS Version
master

### Proposed Objective
Improve user experience and centralize content creation with a dedicated popup interface.

### Proposed Priority
High

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
**Figma:** https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?node-id=2300%3A25370&mode=dev

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27637
- [ ] https://github.com/dotCMS/core/issues/27638
- [ ] https://github.com/dotCMS/core/issues/27639
```

**Comment by oidacra** [comment]
IQA
- Content Generation
<img width="1073" alt="Screenshot 2024-04-16 at 10 27 41 AM" src="https://github.com/dotCMS/core/assets/1909643/080016a3-e63c-4655-927e-9f40f97fb57b">

- Insert to Block Editor as `p`, not block text
<img width="1077" alt="Screenshot 2024-04-16 at 10 27 52 AM" src="https://github.com/dotCMS/core/assets/1909643/cc5914cb-e2dd-4f90-a30b-fe8641fa2e3e">

- Regeneration works
<img width="1122" alt="Screenshot 2024-04-16 at 10 29 26 AM" src="https://github.com/dotCMS/core/assets/1909643/055c643b-2df7-4f62-9819-a28962a1dc77">

- Navegation between regenerations
<img width="345" alt="Screenshot 2024-04-16 at 10 29 54 AM" src="https://github.com/dotCMS/core/assets/1909643/d28b4551-b6b4-45de-98f6-0da1e081595a">

- Cancel warning
<img width="729" alt="Screenshot 2024-04-16 at 10 30 24 AM" src="https://github.com/dotCMS/core/assets/1909643/d7633448-5004-4e7f-bc1b-60838e916499">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a1b916e**, Docker, macOS 13.0, FF v124.0.2
