### ISSUE TITLE
WYSIWYG uses the inode in the /dA/ pathing when inserting an image

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#27649]
### Problem Statement

- when inserting an image into the WYSIWYG, the inode in the /dA/ pathing is referenced
- because this happens, there's no way to know to update the WYSIWYG field
- I got the same result when testing on my local environment

- the customer was affected because they have been going through and updating or adding the description on many of their photos. This has had the unintended consequence of making their photos not link properly where they had been placed into a piece of content.

### Steps to Reproduce

- go to WYSIWYG main text field
- insert image
- check code
- code I obtained after adding an image on https://duncan-dev.dotcms.cloud/dotAdmin/#/edit-page/content?url=%2Fnews%2Findex :

```
<p>Test for image code</p>
<p></p>
<p><a href="/dA/f8741a9841/fileAsset/favicon.ico?language_id=1">favicon.ic <img src="/dA/b4bfd1fac9/gogo-avance-platform.jpg" alt="Gogo AVANCE Platform" data-field-name="fileAsset" data-inode="b4bfd1fa-c956-4ea4-b339-cbbc277ada0b" data-identifier="f734d66a-3551-44a7-bfbe-e262a8fbbcb5" data-saveas="Gogo AVANCE Platform" width="1280" height="385" /></a></p>
```

### Acceptance Criteria

- WYSIWYG should not use the inode in the /dA/ pathing when inserting an image

### dotCMS Version

22.03.13lts

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115193

![image](https://github.com/dotCMS/core/assets/59923449/13546ad7-aa42-4afa-9910-2104b3a57dc7)

**Comment by erickgonzalez** [comment]
@m27iu4 there is a property that allows changing the pathing https://www.dotcms.com/docs/latest/the-wysiwyg-field#Images:~:text=Image%20URL%20Format%20Pattern
