### ISSUE TITLE
Edit Page V2: Return the `onNumberOfPages` property on `/v1/page/json` endpoint

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27658]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Task

We need to retrieve the `onNumberOfPages` property on The `/v1/page/json` endpoint. We already do this in the render version of the endpoint (`/v1/page/render`). [See the example here. ](https://demo.dotcms.com/api/v1/page/render/index?language_id=1&device_inode=&mode=EDIT_MODE&variantName=DEFAULT)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Every `contentlet` present on the page should have its own `onNumberOfPages` property.

**Comment by rjvelazco** [comment]
## Passed Internal QA

- Tested on Docker: [`dotcms:master_1ac696f`]

#### Image

![iqa-issue-27658-return-onNumberOfPages-property-to-json-endpoint](https://github.com/dotCMS/core/assets/72418962/868e3986-20a2-46d8-a682-0354d54c093d)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b295876_SNAPSHOT**, Docker, macOS 13.0, FF v121.0.1
