### ISSUE TITLE
"This URL does not exist"  returned in freshly created SAVED pages in EMA server 

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#27657]
### Problem Statement

- the problem can only be reproduced on a specific instance, please contact Marius for relevant information
- when a fresh page is created it takes some time (about 1 or 2 minutes) before the content can be added to it
- in the 1 - 2 minute timeframe an error pops up: This URL does not exist
- I could not reproduce the problem on my local 

### Steps to Reproduce

Please see Marius for the location to test this
- create a fresh page
- try to add any content
- error should pop up
- retry after about 2 mins - content should be added now

### Acceptance Criteria

- customer expects the error not to be returned and not to wait 1 - 2 minutes before adding content

### dotCMS Version

- image from the master stable code
- Version: 1.0.0-SNAPSHOT (2/14/2024 5:48 AM)

### Proposed Objective

Application Performance

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115206
https://dotcms.slack.com/archives/C06JLA4B2DV/p1708081475568169?thread_ts=1708014706.542969&cid=C06JLA4B2DV
video can be found in the slack archive

**Comment by m27iu4** [comment]
The customer asks for ETA. Can we provide it?

**Comment by damen-dotcms** [comment]
I am not able to reproduce this issue with a test build. 

@m27iu4 - ping me on Slack with some more details? I'd like to know if this is related to the client's configuration somehow, or better understand how to reproduce this issue. Thanks!
