### ISSUE TITLE
Edit Page V2: Research about race conditions

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#27654]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Task

After the move of some information from the client side to the editor. We have encounter a couple of issues due to a race condition that happens after saving the page. 

Right now the response for the page save endpoint `api/v1/page/{pageID}/content` looks like this:

```
{
    "entity": "ok",
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

Our new approach is to use data from the page API instead of the client and this means that everytime we make changes in the page and save we need to hit another endpoint to get the new data.

The consequences of this are double requests and race conditions that are getting out of hands and are kind of unpredictable.

The task is to make more research about getting a solution for this problem either in the BE or FE, but we need to do something about this.

Here is a video showing how weird it can get when this happens.

https://github.com/dotCMS/core/assets/63567962/c4898a99-6610-4720-99d9-64e77723e770

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
No need right now, we'll keep an eye on it.
