### ISSUE TITLE
Enable Experiments Feature by Default in Edit Page

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27671]
### User Story
As a product manager, I want the Experiments feature to be activated by default on the Edit Page, ensuring that users can immediately access and utilize this functionality for A/B testing without needing to enable it manually.

### Acceptance Criteria
- The Experiments feature is enabled by default whenever a user accesses the Edit Page mode.
- Users should see the Experiments option without taking additional steps to activate or configure it initially.
- The default activation should not interfere with the page's performance or the usability of other features within the Edit Page.
- Documentation or tooltips should be updated to reflect this change, informing users that the Experiments feature is now automatically available.

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

**Comment by bryanboza** [comment]
Fixed, tested on the last master code and now this feature is enabled by default.

**Comment by erickgonzalez** [comment]
Experiments issues only for 23.10 LTS
