### ISSUE TITLE
Edit Page V2: Implement Experiment Feature in the New Edit Page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27676]
### Parent
#27546 

### User Story
As a content creator, I want to be able to create experiments and variants within the new edit page, so I can easily manage and track the performance of different content variations.

```[tasklist]
### Acceptance Criteria
- [x] Users should be able to create experiments and variants within the new edit page.
- [x] The feature should reuse code from the Falcon team to ensure consistency and efficiency.
- [x] Users should be able to easily switch between variants and track performance metrics.
- [x] The experiment feature should seamlessly integrate with the new editor interface.
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
@KevinDavilaDotCMS did [the research](https://github.com/dotCMS/core/issues/27565) on how to run this.

### Assumptions & Initiation Needs
- The Falcon team's code for the experiment feature is reusable.
- Users are familiar with creating experiments and variants in dotCMS.

### Quality Assurance Notes & Workarounds
- Ensure that users can create, edit, and delete experiments and variants without any issues.
- Test the performance tracking and reporting functionalities to ensure accuracy.

**Comment by zJaaal** [comment]
Blocked by https://github.com/dotCMS/core/issues/27790

**Comment by rjvelazco** [comment]
### Internal QA

- Tested on Docker image: [`dotcms/dotcms:master_f25a8e3`]


https://github.com/dotCMS/core/assets/72418962/057033af-4e7c-4710-a2eb-fb7d82f75cd2

**Comment by rjvelazco** [comment]
## NOTE QA

Some UI/UX issues need to be fixed in a different PR. This PR ensures that experiments run in the new `edit-ema`.

For example, this button should not be displayed when viewing a variant.

![iqa-test-experiment-inside-ema](https://github.com/dotCMS/core/assets/72418962/e5794b82-c9a8-453f-a05b-02736ea0cee2)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_4278dcc**, Docker, macOS 13.0, FF v121.0.1
