### ISSUE TITLE
Edit Page V2: Allow Users to Move Contentlet Between Containers

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27674]
### Parent
#27546 

### User Story
As a content editor, I want to be able to move contentlets from one container to another on the edit page, so I can easily organize and manage the layout of my content.

https://github.com/dotCMS/core/assets/751424/466aff32-26e8-46c3-ba80-23b5ff754551

> [!IMPORTANT]  
> We need to manually create the drag element because we can just show the button :(

```[tasklist]
### Acceptance Criteria
- [x] Users should be able to click and drag a contentlet from one container to another on the edit page.
- [x] The dragged contentlet should be visually indicated as being moved to the new container.
- [x] Users **should NOT** be able to scroll the page while dragging the contentlet.
- [x] Once dropped in the new container, the contentlet should be placed accordingly without any issues and reload the page
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Users should have clear visual feedback on the dragged contentlet's movement.

**Comment by jcastro-dotcms** [comment]
IQA on hold. We need to publish the latest build of our SDK before testing. I tried to set up my environment with help from @zJaaal but we were not able to.

**Comment by fmontes** [comment]
Drag over not working cross origin.

**Comment by fmontes** [comment]
Tested in master-qa because there was an issue with cross domain

**Comment by bryanboza** [comment]
Fixed testing locally in the last trunk and it is working as expected!
