### ISSUE TITLE
Needs license message needs some styling help 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27672]
### Problem Statement

When you are using the community edition and try to navigate to some portlet that is for EE, we are showing a notification message that requires a license, but we needs some help on that message 
![image](https://github.com/dotCMS/core/assets/2641437/92742605-0a53-484e-a2cd-0f21c66128d4)

### Steps to Reproduce

- Start a fresh environment 
- Login as admin 
- Try to navigate to some EE portlet (Rules, Apps) 

### Acceptance Criteria

We need to show a friendly message here without any issues 

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_84d170e**, Docker, macOS 13.0, FF v121.0.1
