### ISSUE TITLE
EMA: Stiling problem adding new contents 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27684]
### Problem Statement

We have some styling problems adding a new pice of content to the page, we are not loading some of the js files and it looks missaligned and without the same styling of the application. 

![image](https://github.com/dotCMS/core/assets/2641437/9772527e-b48c-4de6-a30c-2c01869991d1)

### Steps to Reproduce

- Login as admin
- Configure your EMA next 
- Edit a page 
- Try to add a new piece of content to that page 

### Acceptance Criteria

We need to keep the same style of the app

### dotCMS Version

Tested on master // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
FIxed here: https://github.com/dotCMS/core/issues/28024
