### ISSUE TITLE
Edit Page V2: Disable "Layout" Button in Editor for Advanced Templates

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27698]
### Parent
#27546 

### User Story
As a content editor using dotCMS, I want the "Layout" button to be disabled when editing a page with an advanced template so that I am not confused by options that do not apply to advanced templates.

```[tasklist]
### Acceptance Criteria
- [ ] When editing a page with an advanced template, the “Layout” button should be grayed out and not clickable.
- [ ] If the button is disabled we need to add a tooltip that reads: "Advanced have no layout"
- [ ] When editing a page with a designer template, the “Layout” button should be enabled and functional.
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
Description: The page API response needs to include a property called `drawed` that flags whether the template is a designer or advanced template.

**Comment by fmontes** [comment]
### Note to QA

The headless pages can't be rendered with an advanced template, we might need to add some warning explaining this into our SDK, right now is just crashing.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
