### ISSUE TITLE
Edit Page V2: Render RRSS Media Cards in New Editor for VTL Pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27699]
### Parent
#27546 

### User Story
As a content editor, I want to be able to render RRSS media cards for Twitter, LinkedIn, and Facebook in the new editor for VTL pages, so I can easily showcase how our page will look like in the RRSS sites.

```[tasklist]
### Acceptance Criteria
- [x] The functionality goes inside the Preview button just like in the old editor
- [x] Only add this for VTL pages
- [x] Headless pages should not show the options (as it is right now)
- [x] The behavior is the sames as the device preview and the button to go back
```

https://github.com/dotCMS/core/assets/751424/300cda8c-a483-4a24-a076-5d71eb6c1536

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The team has access to the codebase of the old editor to replicate the functionality.
- Users are familiar with adding and customizing RRSS media cards in the editor.

**Comment by fmontes** [comment]
### Note to QA:

The social media cards previews are only enabled when you're editing a VTL page, (not headless).

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_f3b48ba**, Docker, macOS 13.0, FF v121.0.1

So, I tried to reproduce this behavior using events pages as vtl's pages but I'm not able to see the RRSS functionality. If I disable the configuration of EMA it works as intended. Please do let me know if theres a more straight forward way to test this. Thanks!

**Comment by fmontes** [comment]
Exactly, that how it works, like I said in the comment is only available for non-headless pages.
