### ISSUE TITLE
Create Upgrade Script to Convert Language Variables to Content Items

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#27703]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

Create Upgrade Script to Convert Language Variables to Content Items

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- We have the Language Variables under Languages, but we also have Language Variables as Content Items. We need to convert all Language Variables to Content Items. 
- We need to convert any legacy Language Variables to Content Items. This should be done as an upgrade task.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Localization Improvements - Phase 1 | dotCMS Internal Documentation - Google Docs || https://docs.google.com/document/d/1bjEM89vkt8TUcKiNgbCY8BPYfpTg_AX3Sb-Brxvy5AA/edit#heading=h.3j55n675gi8u

**Comment by damen-dotcms** [comment]
Copy paste issue in the original description. Fixed now.

**Comment by fabrizzio-dotCMS** [comment]
Not to QA:
The migration script is added as an upgrade task of type DataTask.
DataTasks are registered in a table called `data_version` And these Tasks get applied only on long-running environments being updated. This means you won't see these getting applied on a fresh install. To be able to test this you will need to make some tweaks in the database to simulate the "customer environment" situation. 
To force the task to be executed remove entry 240306 from the `data_version` table. Then restart the server. 

Now the task will look for files present in the folder /assets/messages/
here's an example of what these files might look like 
[messages.zip](https://github.com/dotCMS/core/files/14608296/messages.zip)
It will only import the file if the language already exists in the system and it matches the file name.

**Comment by nollymar** [comment]
**Internal QA:** this change will be tested when [this card](https://github.com/dotCMS/core/issues/27978) is completed.
