### ISSUE TITLE
Edit Page V2: Bring back Shortcut Button for Editing VTL in New Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27700]
### Parent
#27546 

### User Story
As a content editor, I want to have a shortcut button to edit the VTL file (or files) used to render a contentlet in the new editor, so I can easily make changes to the VTL code.

https://github.com/dotCMS/core/assets/751424/b59daae2-6b9c-4b26-a21d-6353e00e96f6

### Acceptance Criteria
- The shortcut button to edit the VTL code is added to the contentlet tools in the Angular component.
- Clicking on the shortcut button opens the edit contentlet dialog to edit the VTL code.
- VTL changes should refresh the page so the user can see the new changes.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The HTML of the rendered page will be used to add the shortcut button to the contentlet tools.
- The VTL editor functionality is already available and just needs to be linked to the shortcut button.

**Comment by zJaaal** [comment]
# IQA Passed

Now we can edit VTL Files from the new Visual Editor

docker image: `dotcms/dotcms:master_latest_SNAPSHOT`


https://github.com/dotCMS/core/assets/63567962/a5c1e660-e2de-4fb1-b54e-8aa943c3ae78

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a0f63f4**, Docker, macOS 13.0, FF v121.0.1
