### ISSUE TITLE
Directive Update: Handling of Nonexistent Feature Flags

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27708]
### Parent Issue

#25733 

### Task

We are turning on the feature flag for announcements, but we are changing the way we activate them. Previously, by default, a feature flag was set to false if the property was not explicitly specified. However, we want to change this so that if the property is not specified, it defaults to true.

This change entails a modification in the front-end behavior that has not yet been implemented. However, I understand that Falcon has made a patch to activate it.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

I made sure that the new edit mode and content edit features are disabled.



![Image](https://github.com/dotCMS/core/assets/8741395/530218f8-9de9-48f3-bf10-088da4d83045)



![Image](https://github.com/dotCMS/core/assets/8741395/1658e131-fb8e-4e64-a570-9c34f49026a0)





Besides, the Announcements Menu is enabled by default.



![Image](https://github.com/dotCMS/core/assets/8741395/4da36617-2751-4f98-899c-f2925928f868)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
