### ISSUE TITLE
Content Types per Site: Associate Content Types with SYSTEM_HOST Upgrade Task

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27728]
### Parent
#27727

### Task description
As a dotCMS administrator, I want to implement an upgrade task that associates all existing content types with the SYSTEM_HOST as their site identifier. This will ensure that all content types are correctly linked to the main site and improve the organization of content within the dotCMS system.

```[tasklist]
### Acceptance Criteria
- [ ] The upgrade task successfully associates all existing content types with the SYSTEM_HOST as their site identifier using `metadata` property.
- [ ] The upgrade task does not affect the content of the existing content types or any other configurations within the dotCMS system.
```

### External Links
N/A

### Assumptions & Initiation Needs
- The dotCMS system is up and running without any issues before initiating the upgrade task.

### Quality Assurance Notes & Workarounds
N/A

**Comment by wezell** [comment]
Wait, @fmontes, I don't think this is right.  Customers are using content types on hosts currently.

**Comment by fmontes** [comment]
@wezell let's talk about it in the PO

**Comment by fmontes** [comment]
This rel alreayd exist in host field
