### ISSUE TITLE
Running the CLI triggers a security warning about "incoming network connections" 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#27738]
### Problem Statement

Running the CLI triggers a security warning about "incoming network connections" warning
The problem is probably related to the Quarkus dev console still attached to the final binary 
And the fact that it opens a server in http://localhost:9000/
The potential fix for this is removing (or changing the scope ) the dependency that pulls in such functionality 

### Steps to Reproduce

https://github.com/dotCMS/core/assets/37148755/7800cd77-e9c0-4919-89e6-3c4410b67edf

### Acceptance Criteria

No server connections should be opened by the CLI

### dotCMS Version

current master

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Note to QA:** Before this fix, the popup only displayed when the OS firewall was on
