### ISSUE TITLE
Render Page on Ended Experiment Variant

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27748]
### Problem Statement

If we try to render a page on a Ended Experiment's Variant it got render on the specific Variant even when the Experiment is Ended

### Steps to Reproduce

- Create a Page.
- Add a Content inside the Page 
- Create an Experiment
- Crete a Variant inside the Experiment, Edit the Content do something visible on the render.
- End the Experiment.
- Try to render the page on the FE using the variantName query parameter, you need to know what if the Variant's name.

The page is render using the Content Variant version.

### Acceptance Criteria

The page must be render on the DEFAULT Variant, because the specific variant is not alive anymore.

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/27877

**Comment by dsilvam** [comment]
Passed Internal QA: Upon trying to render a page on a variant that belongs to an ended experiment it renders the default variant as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_9eae228**, Docker, macOS 13.0, FF v121.0.1
