### ISSUE TITLE
dotcli login should take a token

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27743]
### Parent Issue

`dotcms login -t` should allow the user to set a token to use instead of a username/password.

If no value for -t is given, the token value should be requested interactivity.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, nowIm able to login using the token (-tk)

![Image](https://github.com/dotCMS/core/assets/2641437/60c3edea-d0a4-49ec-935d-11aa0f8b39ac)
