### ISSUE TITLE
Need to improve the response messages in the user API 

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27742]
### Problem Statement
We need to improve some of the messages in case you send the wrong required parameters using the follow endpoint: 
`http://localhost:8080/api/v1/users`.

In case you try to create a new user with an email that is already registered, we are just returning a 400 (bad request) error, which is ok, but we are not returning the proper message in the response,  we are just getting "null". 

We need to indicate the FE part about this problem. 
![image](https://github.com/dotCMS/core/assets/2641437/8b3e2e1e-1dfd-44c1-af28-a05db9523c15)

Also, we need to identify the required parameters for this call and do the same validations. 

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/27319#issuecomment-1967302479_
            

### Steps to Reproduce

Create a new user with repeated email

**Endpoint**: http://localhost:8080/api/v1/users

**Body:**
```
{
    "userId":"userid-spanish-12345678",
    "active":true,
    "firstName":"SpanishUser",
    "middleName":"S",
    "lastName":"Spanish",
    "nickName":"Spanish",
    "email":"spanish2@dotcms.com",
    "male":true,
    "languageId":"es_ES",
    "password":["1","2","3","4","5","6","7","8"],
    "roles":["DOTCMS_BACK_END_USER", "CMS Administrator"]
}
``` 

### Acceptance Criteria
- The error should return a message explaining why is rejected
- Postman test 
- We need to add the proper validation to the test 

### dotCMS Version
Tested on master

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by KevinDavilaDotCMS** [comment]
# Passed Internal QA
Tested in master, in postman and FE
![Screenshot 2024-03-01 at 14 13 15](https://github.com/dotCMS/core/assets/144152756/d0ed1843-f1ce-4732-9919-0183d109ed5f)
<img width="1075" alt="Screenshot 2024-03-01 at 14 18 47" src="https://github.com/dotCMS/core/assets/144152756/cba28f6c-2126-43f3-b2d7-1e02e772bbed">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_9587235**, Docker, macOS 13.0, FF v121.0.1
