### ISSUE TITLE
dotcli login should be interactive

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27741]
Currently,  `dotcli login` says that it requires 2 params - a username and a password.  We should not make any param mandatory.  Instead, if the username/password param is not passed, the `dotcli login` should ask for a username and password interactively.  This is because you do not want to store/record your dotCMS user password in the bash history if you can help it.

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me.

**Comment by bryanboza** [comment]
After play a little bit using this functionality I note that we need some work here: 

Here a video explain the problem: 


https://github.com/dotCMS/core/assets/2641437/24253801-35c6-4049-a37c-b33987c058ca

Also, if I define the user name and token in the yml file, when I do `dotCLI login` we should use those parameters by default, and we are asking again for user name and password instead to use the defined parameters in the file

**Comment by fabrizzio-dotCMS** [comment]
> After play a little bit using this functionality I note that we need some work here:
> 
> Maybe we should be smarter here and use the defined parameters in the file, since we are ignoring it at all when you try to login.
> 
> Here a video explain the problem:
> 
>  Screen.Recording.2024-03-20.at.6.38.29.PM.mov 
> Here two more cases:
> 
> * If I define the user name and token in the `dot-service.yml` file, when I do `dotCLI login` we should use those parameters by default, and we are asking again for user name and password instead to use the defined parameters in the file
> * We don't allow define the password in this file, we have options just for token.

the command was never designed to do that.. I think it is ok. But anyways that's @wezell's call

**Comment by wezell** [comment]
I think that should be another card.

**Comment by bryanboza** [comment]
Moved to a new card #28036. 

We can close this one for now.
