### ISSUE TITLE
Endpoint for Content Reporting

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27755]
### Parent
#27727

As a developer, I want to have an endpoint that provides a list of Content Types and any existing contents of such types that live under a dotCMS entity, so that I can easily get information on them when, for instance, I need to delete them from the database.

Such entities are: Sites and Folders.

```[tasklist]
### Acceptance Criteria
- [x] The endpoint for **folders** should be accessible at `/api/v1/contentReport/folder/{folderId}`.
-  [x] The endpoint for **folders** can take a folder path, but you must pass down the Site ID/Key as well: `/api/v1/contentReport/folder/{folderPath}?site={siteId|siteKey}`.
- [x] The endpoint for **sites** should be accessible at `/api/v1/contentReport/site/{siteId|siteKey}`.
- [x] Sending a GET request to the endpoint should return a JSON response with the content information of the specified entity.
- [x] The response should contain the content type information and the count of contentlets
```

### Proposed Objective
"Core Features"

### Proposed Priority
Priority 3 - Average

### External Links
N/A

### Assumptions & Initiation Needs
- Proper authentication and authorization mechanisms should be in place to access the endpoint.
- Proper permissions mechanisms should be in place to access the endpoint.

### Quality Assurance Notes & Workarounds
In order to test this new feature, please take the following criteria into consideration:

1. You can refer to the tests in the `core/dotCMS/src/curl-test/Content_Report_Resource.postman_collection.json` file, which is a completely brand new test, and work from there.
2. Additionally, you can take the Full Starter and generate reports for both the Demo Site, and any of the folders in it.
3. Finally, keep the following in mind:
3.1. For the Site Report, you can pass down either the Site ID or the Site Key.
3.2. For the Folder you can pass down the Folder ID. You can also pass down the Folder path, but you need to include the `site` parameter via query String, which is the Site ID or Key.

It's very important that you can keep track of what Content Types you add to a Folder or Site and how many contents of such types there are before generating the report. This way, you won't get any false positive results.

**Comment by fmontes** [comment]
We will need to limit the max number.

**Comment by jdotcms** [comment]
working on internal QA

**Comment by jdotcms** [comment]
If the site does not exist, return 200 and empty results, it would be ok if the site exist but does not have anything associated. 
In this particular scenario might return 404 since the site does not exist.

In general works fine: 
- shows the report per site including system_host
- if you add or remove content to the content type report is updated on consequence
- if you send any wrong parameter on the pagination return bad request
- even if the site is archive, works.
- works by site key or site id
- even if the content associated to the content type is archived, it is been part of the report.

Note: there is a small window between the sites state changed (probably b/c the index) where the results are not reachable, but waiting a few seconds the results came again!

**Comment by jdotcms** [comment]
```
curl --location 'http://localhost:8080/api/v1/contentreport/folder/f4b14fa4b86412ff764af014b476f45ddoesnotexist'
```

When running this curl, returns 400 instead of 404, is that right?

**Comment by jdotcms** [comment]
Samething happens here
```
curl --location 'http://localhost:8080/api/v1/contentreport/folder/folder-report/middle-folder/test-folder-35?site=defaultxxxx' 
```

**Comment by jdotcms** [comment]
In general both endpoints work fine, however there are some response responses code that may need some attention

**Comment by jdotcms** [comment]
Fixes for the IQA on https://github.com/dotCMS/core/pull/28080

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_807e03e`

Non0existing Site ID, Folder ID, or Folder Path with Site ID return a Status 404 now.

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk version // Docker // FF... Postman looks ok too
