### ISSUE TITLE
UX: Edit Page Upgrades

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27753]
## Parent
#27546 

## Define the Problem

The new edit page is already in progress and currently in development, we already have a version up and running, but there are some features that we need to include:

### Page is locked by another user
Users can right-click in a page list and lock the page, and then another user with a lower permission level won't be able to unlocked and editing.

We need to figure it out how do we want to show this in the UI.

This is how it looks like right now:

![Image](https://github.com/dotCMS/core/assets/751424/63eafea1-27a4-4860-8be6-6dbd7f92a2e3)

### Edit Variant
When users are creating experiments, they create variants of a page, we need to update the editor to show some UI queue to signal that we are editing a variant a not the “original” page.

In the old version, when you are editing a variant, it looks like this.

<img width="1105" alt="image" src="https://github.com/dotCMS/core/assets/751424/3a89d01a-3d82-4680-ab2c-43d77cf2bcb3">

We need to figure it out how to add this signaling to the new edit page.

### Shortcut to edit the contentlet that generates the page
In dotCMS we can generate pages out of contentlets, for example, you will not create 100 pages for each blog post, you just write the blog posts and the page will be generated automatically.

We have to have a button somewhere in the tooling to edit the piece of content, more info:

https://github.com/dotCMS/core/assets/751424/e960a772-bead-4618-9993-1bb95bac100a

### Disabled sidenav buttons

Either for license or because the page has an advanced layout, we need to disable buttons in the sidenav, we need to design of what that will look like.

Right now in the old version it looks like this:

<img width="325" alt="image" src="https://github.com/dotCMS/core/assets/751424/707f686b-6c74-41eb-8503-d0cedacca2ac">

## Who's Facing the Problem?

All the page editors and creators, even though this is not actually a problem since this is an upgrade of the editor, we need to provide the user with all the same functionality of the previous version.

### Relevant Links and Resources

[New edit mode Figma](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2874%3A14331&mode=design&t=UJnf6IJF9Z9HFri0-1)

**Comment by melissarojas-dotcms** [comment]
The design is ready with the correspondent requirements, there are some **notes in dev mode**, please make sure to read them.

[Link to the Figma File](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2897%3A17391&mode=design&t=zUiiPbEH4G183x24-1)

![image](https://github.com/dotCMS/core/assets/150382008/d0c6e59c-2dba-45d5-90ef-1613e8e105fe)
![image](https://github.com/dotCMS/core/assets/150382008/c6b0852c-e37a-4c88-9b62-b8fce41d3afb)
<img width="272" alt="Screenshot 2024-03-19 at 8 46 44 AM" src="https://github.com/dotCMS/core/assets/150382008/1bd0b8b8-15bc-4e2f-a55b-96402ea21726">
