### ISSUE TITLE
Java 21

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27766]
### Task

Testing to see if we can get an image running with Java 21.

This is not setting code compatibility to Java 21.

dotCMS can run in Java 21 but many of our tests rely on a PowerMock version that uses classes in the`unsafe` package and does not support java 21.

**Comment by fmontes** [comment]
@nollymar do we make this happen in the Java 21 work?

**Comment by nollymar** [comment]
This was already implemented in separate cards
