### ISSUE TITLE
Metric: Set clientCategory from hostName

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#27772]
### User Story

We need a way to categorize the Metric data by:

- Test Data
- dotCMS Data
- Customers

**How we fill the Metric table MetaData right now?**

The hostname for the cloud clients and dotcms server (auth and prod) has the following syntax: dotcms-clientName-env-instance, for example dotcms-corpsites-auth-0.

On the auth and prod case the clientName is equal to corpsites
 
Right now we are using the hostName  to fill the following fields on the metric table: client_name, client_env, client_instance and we are removing the dotcms prefix.

Also we have a client_category in order to fill it  we need to set an environment variable called TELEMETRY_CLIENT_CATEGORY.

We wish use the hostname as a second level to set the client_category field on the follow way:

- If the hostName starts with  dotcms-corpsites then the Category is DOTCMS.
- If the hostName starts with ‘dotcms-’ but not with ‘dotcms-corpsites’ then the category is CLIENT.
-  We are going to take any register with a null category as a TEST_DATA.

Also we are going to include the ability to set the clientName also via environment variables (TELEMETRY_CLIENT_NAME)

### Acceptance Criteria

Set the client_category using the Host name

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/40

**Comment by dsilvam** [comment]
This is working as expected. Checked on the prod db instance receiving data from both `auth` and `prod`.
