### ISSUE TITLE
Page API Returning Content Related to Page Asset 

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#27775]
### User Story

As a developer, I want to be able to use the page api to return content that is related to the page asset itself, so I can easily make performant queries and simplify my calls.

### Acceptance Criteria

The Page API must be able to deliver content related to the page asset

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

This is an issue that was brought to our attention from a customer

**Comment by fmontes** [comment]
### Not working:

1. Edit Page content type
2. Add a relationship field for Blog, I named "Relationship"
3. Edit the page and relate blogs (or not)
4. Then request the API like: `http://localhost:8080/api/v1/page/json/index?depth=2`
5. Got an error:
```
{
  "message": "Contentlet : 9bfaf94e-3852-43da-8cde-2d62f90d6053 is not a FileAsset (through reference chain: com.dotcms.rest.ResponseEntityView[\"entity\"])"
}
```

**Comment by jdotcms** [comment]
I couldnt reproduce
I have done the following steps

1) create the relationship to device 
<img width="1180" alt="Screenshot 2024-03-14 at 10 37 32 PM" src="https://github.com/dotCMS/core/assets/19578350/cb056fd3-5763-4903-bb2d-0b96785df483">
<img width="743" alt="Screenshot 2024-03-14 at 10 37 40 PM" src="https://github.com/dotCMS/core/assets/19578350/d71dca50-d247-429d-a654-5dbe1370695f">

2) add devices to the page
<img width="1197" alt="Screenshot 2024-03-14 at 10 37 54 PM" src="https://github.com/dotCMS/core/assets/19578350/bcc7e092-dd60-4082-b8b6-d12f6778b581">


3) request the API
<img width="794" alt="Screenshot 2024-03-14 at 10 38 11 PM" src="https://github.com/dotCMS/core/assets/19578350/501017ed-ad3b-45b6-bc19-2f30a58085d0">

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master
![image](https://github.com/dotCMS/core/assets/144152756/c2634006-199a-4e09-b26f-8658833204c1)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce following the provided steps. 


![Image](https://github.com/dotCMS/core/assets/2641437/6a0fee21-e005-4fef-9a6b-4bf94e0baee7)
