### ISSUE TITLE
In EDIT Mode, switching the language setting makes the layout go default

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#27771]
### Problem Statement

- when the language is switched (in EDIT mode) for a page that has content, a page is created
-the new page has its layout set to default (so it does not keep the layout of the original page from which it was created as a new language version)
- this functionality was working correctly previously and appears to have been introduced in the recent updates to the customer server
- I reproduced the problem, but only for a page with content added to it
- for a fresh created page, without content, the layout is kept for the new language version page also
- issue is reproducible on https://dotcms-qa-master.dotcms.site/ 1.0.0-SNAPSHOT

### Steps to Reproduce

- go to a page that has content in it (for example a page set up in english)
- create a new language version page (for example the same page with a spanish version)
- check the layout of the new language version page (the spanish version)
- video attached

### Acceptance Criteria

- the layout should be kept on the new page also

### dotCMS Version

- 1.0.0-SNAPSHOT
- customer has master

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115371
[screen-capture-switching-languages-changes-layout-to-default.webm](https://github.com/dotCMS/core/assets/59923449/fd40bd19-eb69-4647-a7b1-df0501a2c623)

**Comment by fmontes** [comment]
A detail explaination of the problem.

https://github.com/dotCMS/core/assets/751424/d1a12b0c-8e16-4a9a-99d1-e429d238a3eb

**Comment by rjvelazco** [comment]
@erickgonzalez This issue is occurring in the old editor, not in the UVE, which is now the default. Do we want to address it for the old editor as well, or focus on the UVE moving forward?

### Video

#### UVE

https://github.com/user-attachments/assets/f84d98c3-2d34-4bfb-886d-70aa0ff3b612

#### Old Editor

https://github.com/user-attachments/assets/b569247b-ca8f-4753-9c99-dc4107c00ffa

**Comment by rjvelazco** [comment]
I'm closing this issue. @erickgonzalez agrees that we should close the ticket since we're fully transitioning to UVE, and the client is on Evergreen.
