### ISSUE TITLE
Handling Large Data Sets with CompletableFuture Instead of CompletionService

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#27770]
### Problem Statement

We encountered a blocking issue when processing large data sets using `CompletionService`. The application was experiencing deadlocks when the number of tasks submitted to the `CompletionService` exceeded the capacity of the underlying thread pool, causing the system to hang.

### Root Cause
The root cause of the problem was identified as the improper handling of concurrent tasks using `CompletionService`. While `CompletionService` facilitates the execution of asynchronous tasks, it does not provide direct control over the number of concurrently executing tasks. This lack of control can lead to a situation where too many tasks are waiting to be executed, exceeding the capacity of the thread pool and resulting in a deadlock.

### Proposed Solution
To address this issue, we propose transitioning from using `CompletionService` to `CompletableFuture` for managing asynchronous tasks. `CompletableFuture` provides a more flexible and powerful way to handle asynchronous computations, allowing for better control over task execution and error handling.

The key changes to be made are:

* Replace `CompletionService` with `CompletableFuture` for executing tasks asynchronously.
* Use `CompletableFuture.supplyAsync` to initiate asynchronous tasks and `CompletableFuture.allOf` to wait for the completion of all tasks.

### Expected Benefits
Switching to `CompletableFuture` is expected to resolve the blocking issue and improve the overall performance and reliability of the system when processing large data sets. It should allow for more efficient task scheduling and provide a clearer and more concise way to handle exceptions.

### Steps to Reproduce

Using integration tests we can reproduce the issue pushing 2000 files living in 1100 folders.

Also, we have a test folder that could be provided if needed for QA with 1200 files on it, resulting, most of the time, with timeouts due to blocked threads. 

### Acceptance Criteria

Pushing and pulling large datasets should work as expected.

**Comment by manuelrojas** [comment]
**Internal QA Approved** 

<img width="1362" alt="image" src="https://github.com/dotCMS/core/assets/3438705/30c3ec03-2e80-4108-8659-f04b009ed398">

**Comment by bryanboza** [comment]
Tested with the internal servers and it works as expected!
