### ISSUE TITLE
 Inclusion of Sub-Categories in Category List Export in dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#27783]
### Parent Issue
Related to #25653 

### Problem Statement

When exporting a category list in dotCMS, sub-categories are not included in the exported file. This omission hinders users who require a comprehensive overview of category structures, impacting their ability to efficiently manage and analyze category hierarchies.

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Navigate to the category management section.
- Export the category list using the available export functionality.
- Open the exported file and observe that sub-categories are not included in the exported data.

### Acceptance Criteria

- **Sub-Category Inclusion:** Enhance the category list export functionality to include all sub-categories within their respective parent categories.
- **Hierarchical Representation**: Ensure that the exported file maintains the hierarchical structure of categories, clearly indicating parent-child relationships.

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
The fix is to correct this on the import such that children are selected; we're closing as works as designed.
