### ISSUE TITLE
Backport AI Plugin Required Changes to LTS 23.10

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27787]
### Problem Statement
The AI Plugin requires specific changes to be fully compatible and functional with the LTS (Long Term Support) version 23.10. These changes need to be identified, adapted, and backported to ensure seamless operation of the AI Plugin within this LTS version.

### Steps to Reproduce
N/A - This task involves proactive development work rather than fixing a specific reproducible bug.

### Acceptance Criteria
- Identify the changes made to the AI Plugin that are not currently present in LTS 23.10.
- Adapt these changes to be compatible with the LTS 23.10 environment.
- Backport the adapted changes to the LTS 23.10 version without affecting the existing functionalities.
- Ensure that the AI Plugin operates as expected in the LTS 23.10 environment, including all its dependencies and integrations.

### dotCMS Version
LTS 23.10

### Proposed Objective
Integrations, Stability Improvement

### Proposed Priority
Priority 2 - Important

### External Links
List of Issues Backported https://docs.google.com/spreadsheets/d/1t6wl2ZrPIHZp_FRFCbkKa_ODqk3KVEgkMvHubo18DRc/edit#gid=0

### Assumptions & Initiation Needs
Assuming that the AI Plugin has undergone significant updates since the release of LTS 23.10, necessitating a careful review of changes to identify those critical for backporting. Access to both the AI Plugin's and LTS 23.10's codebases is essential.

### Quality Assurance Notes & Workarounds
Quality assurance should thoroughly test the backported AI Plugin in the LTS 23.10 environment to identify any compatibility issues or regressions. Workarounds may be necessary for issues that arise specifically from the backporting process.

**Comment by erickgonzalez** [comment]
The plugin was deployed successfully in our 23.10 LTS QA server. This new LTS is expected to be released on March 18th.
