### ISSUE TITLE
dotCLI : Do not require the dot-service.yml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27799]
### Task

If all the commands can take a token (and do not need a user/creds) then we should also add the ability to specify the DOT_API_URL via the command line.  This will save time when someone is trying to use the cli programmatically or just as a one off thing - there wont be a need to make a fake/temp entry into a `$HOME/.dotcms/dot-service.yml` file.

This would allow us to just use something like the following:

```
dotcli push  --token=$token --dotcmsUrl=https://demo.dotcms.com
```

**Comment by fabrizzio-dotCMS** [comment]
We already have a validation in place that prevents every command from being executed unless the cli has been configured (Meaning that the yml has been created). What should be the flow from now on? 
 @wezell

**Comment by wezell** [comment]
We should not need a yml to run the command line.  If all the switches are passed to the cli, it should work.

**Comment by dcolina** [comment]
Internal QA: Passed.

As we can see in the following images. 


![Image](https://github.com/dotCMS/core/assets/29883881/8691f56d-b811-46b0-9067-56d6a0fad53e)
![Image](https://github.com/dotCMS/core/assets/29883881/eef54857-8455-45da-972a-91ca27eb2de7)

**Comment by bryanboza** [comment]
Fixed, now we are able to override the configuration and target an specific server using the `dotcms-url` command 

![Image](https://github.com/dotCMS/core/assets/2641437/ff5fe744-ae60-4561-b5e6-7d935ba397f6)
