### ISSUE TITLE
Update User Rest API

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27794]
### User Story

As an user I want to be able to update an existing user via Rest API

### Acceptance Criteria

The PUT /api/v1/users/{id} should work

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by zJaaal** [comment]
# IQA Passed

Now we can edit users via REST Api.

Docker Image: `[dotcms/dotcms:trunk_63a26cc]`

## Screenshot

https://github.com/dotCMS/core/assets/63567962/ff02adf4-7505-448a-9239-6fc78a635e57

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Postman 

Postman tests changes here: https://github.com/dotCMS/core/pull/28547

**Comment by dsilvam** [comment]
@gortiz-dotcms this is only for 24.04 LTS!
