### ISSUE TITLE
Clickable Links in Announcements Close Menu and Mark as Read

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27795]
### Parent Issue

#25733    

### Task

When users click on any of the links provided in the announcements section, the menu should automatically close, and all announcements should be marked as read. This behavior enhances user experience by reducing clutter and ensuring that users are promptly informed about new updates or announcements.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by dcolina** [comment]
Internal QA: Passed.

As we can see in the following video, the issue has been solved successfully.



https://github.com/dotCMS/core/assets/29883881/28496810-fb85-4caf-a2ff-87b2aa6f3489

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
