### ISSUE TITLE
CLI: Move dotcms-cli.log to .dotcms folder

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27809]
### Task

Currently, the `dotcms-cli.log` is stored in the cli workspace by default. This default path should be changed and the log should be moved to the `~/.dotcms` folder

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
I verified that the login is now written to ${user.home}/.dotcms/dotcms-cli.log
it can also get overriden via environment variables 
like this 
export QUARKUS_LOG_FILE_PATH=/Users/fabrizzioaraya/Coding/dotcms-cli.log

**Comment by bryanboza** [comment]
Fixed, tested in the last trunk version and now we don't have the log in the CLI files anymore, now it is on the .dotCMS hidden folder 

![Image](https://github.com/dotCMS/core/assets/2641437/d7a7fb1b-5d9c-4f6a-9acb-6c2d7c151581)
