### ISSUE TITLE
On Template as File we want to support theme as path

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#27803]
### User Story

As an user i want to use the theme path instead of the folder id, it will give us more facilities to implement the dotcli approach

### Acceptance Criteria

A template such as this works
```
$dotJSON.put("title", "File Template Design Example")
$dotJSON.put("friendly_name", "File Template Design Example")
## This properties only if is a Design Template
$dotJSON.put("theme", "system_theme")
```

and we want this to work as well
```
$dotJSON.put("title", "File Template Design Example")
$dotJSON.put("friendly_name", "File Template Design Example")
## This properties only if is a Design Template
$dotJSON.put("theme", "//dotcms.dev/applications/themes/dotcms")
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Note to QA, while QAing this one we found: https://github.com/dotCMS/core/issues/27916 and https://github.com/dotCMS/core/issues/27914

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to set the theme with a path. As we indicate in the provided example.
