### ISSUE TITLE
Edit Page V2: Fix auto-save layout changes with VTL pages on new edit page

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#27801]
### Problem Statement

Inside the EditPage with a VTL page, we cannot see the changes if we edit the layout.
We must to recharge the page to see these changes

https://github.com/dotCMS/core/assets/144152756/bf544015-939b-4bc8-a68e-1cf3bcf6a353

### Steps to Reproduce

-Enter to new EditPage VTL (Yout must to have FEATURE_FLAG_NEW_EDIT_PAGE in true and dont have Edit EMA Next config).
-Go to edit layout and edit it.
-Go back to content and see the page doesn't change

### Acceptance Criteria

- [ ] When i change the layout, i see that changed in content tab without reload the page

### dotCMS Version

Master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
Fixed with the DSS initiative.

**Comment by fmontes** [comment]
Not happening anymore probably fixed in another ticket.
