### ISSUE TITLE
Content Displacement Bug when Editing Template

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27816]
### Problem Statement
When a user creates a template with the same container in multiple boxes, creates pages using that template, adds different content to those pages, and then updates the template, all the content in the pages gets displaced and appears incorrectly.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/b78d8a5f-a6e7-4c76-80da-e7d8b34f3b80

```[tasklist]
### Acceptance Criteria
- [ ] When a template is edited, ALL pages using that template should maintain their content in the respective containers without displacement.
```

### External Links
N/A

### Assumptions & Initiation Needs
- Assumes that users are creating templates with multiple containers.
- Initiation requires access to create templates and pages in dotCMS.

### Quality Assurance Notes & Workarounds
- QA should test by creating templates with multiple containers and adding content to pages.
- Workaround is to use always the layout editor and not the template

**Comment by freddyDOTCMS** [comment]
**Note to IQA:**  Test also when Update a Layout inside a specific page, try all the cases:

- Add a Container
- Remove Container
- Move Container

Remember If a Page is using a Template and you change the Layout of the Page, the original Template just get updated if the page is the only one using this Template in other case a new Layout is created and the Template is not updated
