### ISSUE TITLE
Changes to sort order of items on the site browser page

### ISSUE THREAD

**Issue by wangweiyi722** [dotCMS/core#27820]
### Problem Statement

When trying to change the sort order of a page on the site browser page, the changes are never saved. After navigating to another page, and navigating back, the changes to the sort order disappear.

### Steps to Reproduce

Go to the site browser
Open a folder with a page in it
Change the value in the menu column
Navigate to another folder
Navigate back to the original folder
Notice that the value of the menu column changed back to the original value

### Acceptance Criteria

Make it possible to save the sort order within the site browser page.

### dotCMS Version

reproduced in the current qa master

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

The sort order feature in the edit modal for contentlets does work as intended.

**Comment by erickgonzalez** [comment]
To change the menu order, you must edit the page, set the **Sort Order** field, and save those changes.

It's misleading that we're able to change the value over there, so we need to remove that behavior.

**Comment by erickgonzalez** [comment]
It's working as it should. Now it's not possible to change the sort order (menu) from the site browser.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_1895cd3**, Docker, macOS 14.5, FF v126.0.1
