### ISSUE TITLE
Return IDP configuration Id instead of site id as part of the ACS URL in the SAML authentication request

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#27832]
### Parent Issue

#25636

### Task

As part of the work done in #25636 to map an old IDP configuration Id to a site identifier, we require to return the IDP configuration id instead of the site id in the ACS URL included in the SAML authentication request.
In #25636 we included a new dotCMS configuration property to enable the mapping by IDP configuration id: `dotcms.saml.use.idp.config.id`. When the property is enabled, this new SAML configuration property can be used to include the IDP configuration id that will mapped to the site: `idp.config.identifier`
In this task, the idea is to use check properties again so when `dotcms.saml.use.idp.config.id` is enabled, we return the id stored in the property `idp.config.identifier` as part of the ACS URL.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The mapped IDP configuration id should be returned in the ACS URL included in the SAML authentication request, for example:
```
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                     AssertionConsumerServiceURL="https://sp-server-name/dotsaml/login/{idp-config-id}">
```
where {idp-config-id} is the IDP configuration id set in the SAML configuration property `idp.config.identifier`.

**Comment by erickgonzalez** [comment]
The customer confirmed that it is working as it should.
