### ISSUE TITLE
Daniel: Drop Everything & Learn Mar 6 - Mar 26

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#27849]

**Comment by dcolina** [comment]
[The Complete GitHub Actions & Workflows Guide [2023 UPDATE]
Automate Code Testing, Deployment & Versioning using CI/CD Workflows. Create & Publish GitHub Actions to the Marketplace](https://dotcms.udemy.com/course/github-actions/) 

25% completed so far.
