### ISSUE TITLE
Extracting a list of unreferenced file assets

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#27856]
### User Story

- the user asked if there's a way to get the list of File Assets that are not referenced in any content
- as we don't have such functionality implemented, I created an enhancement request
- they need this when they want to clean up unused files
- they would like to know if they can get a list of all Files that have no reference in any of the contents

### Acceptance Criteria

- a list of unreferenced File Assets should be extracted when needed

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115172

**Comment by prestonso** [comment]
We're closing this as won't fix — @m27iu4 please let us know if you hear this come up from more customers!
