### ISSUE TITLE
Make sure that the default state for Telemetry is disabled

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27867]
### User Story

As an on-prem customer, I want to ensure that no telemetry data is sent to dotCMS unless I explicitly enable it.

To achieve this, we need to ensure that the default value of the Telemetry feature flag is FALSE (disabled).  This means that the only way a system will send telemetry data is if the telemetry feature flag exists AND is set to TRUE.

### Acceptance Criteria

* Telemetry enabled if the telemetry feature flag exists and is set to TRUE.
* Telemetry DISABLED if the telemetry feature flag exists and is set to FALSE.
* Telemetry DISABLED if the telemetry feature flag does not exist.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Let's change the default in the `Config.getBooleanProperty` and have it `false`

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/44
