### ISSUE TITLE
Spike what is left to do to fully move to Java 21

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#27864]
### Task

A one day spike work, The aim to  create a series of estimated tasks in an epic that cover any remaining work that would be required to fully migrate over to Java 21.   Currently we are able to build but not fully test with Java 21 and particular test features like Mokito and Powermock may be causing issues.  We should outline the minimum required to switch over, and then any follow up work that might be required e.g. changes to make use of new features.
This task follows on from initial work by Will in https://github.com/dotCMS/core/issues/27766 and https://github.com/dotCMS/core/pull/27767

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

1 Day of testing the current migrated branch to find any issues ant confirm if there are problems with upgrading and dependencies that may need to be updated.

**Comment by nollymar** [comment]
Two new epics were created after identifying the remaining work: 
https://github.com/dotCMS/core/issues/27993
https://github.com/dotCMS/core/issues/27996
