### ISSUE TITLE
CLI: Improve error display for files pull failures

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#27869]
### Problem Statement

When pulling files, if errors occur, the error messages displayed on the screen are not clear and do not provide details about the files that failed. This lack of detail makes it difficult for users to understand and address the issues.

Current display:
```
Found [6] errors during the pull process:

[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
[ERROR] ❗  HTTP 404 Not Found: The requested resource was not found or is restricted.
run with -e or --errors for full details on the exception.
```

### Acceptance Criteria

The error display includes more specific information about the files that failed during the pull process, to help users identify and resolve issues more effectively.

**Comment by nollymar** [comment]
**Internal QA:** Passed. Now, I can see more details when an error occurs

![Image](https://github.com/dotCMS/core/assets/8741395/dea4f282-fcc4-450a-af0f-8ddf264a4a2e)

**Comment by bryanboza** [comment]
Fixed, now we are showing more info on those errors 


![Image](https://github.com/dotCMS/core/assets/2641437/5e5606ee-523e-48d2-8366-398fbed40dfc)
