### ISSUE TITLE
refactor pg_dump inclusion in our docker image

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#27871]
### Parent Issue

Our docker image pulls in resources from two other images [java-base](https://github.com/dotCMS/core/tree/master/docker/java-base) and [pg-base](https://github.com/dotCMS/core/tree/master/docker/java-base). Managing multiple images and ensuring their underlying base image versions remain consistent is difficult.

We can move the tasks to include `pg_dump` from the `pg-base` Dockerfile to the `java-base` Dockerfile, thus eliminating the need for the `pg-base` image and  simplify our process.

### User Story

Simplify our docker image build process

### Acceptance Criteria

Steps required:

1. Update the `java-base` Dockerfile to add `pg_dump` to the image
2. Push the updated `java-base` image to Dockerhub with a new tag
3. Update [the main Dockerfile](https://github.com/dotCMS/core/tree/master/dotCMS/src/main/docker/original) to use the new `java-base` image and remove references to `pg-base`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CQQMX585N/p1709745466062889

**Comment by jcastro-dotcms** [comment]
Future code changes will be done/referenced in the original ticket instead: https://github.com/dotCMS/core/issues/27537

W'll close this ticket now.
