### ISSUE TITLE
System Table Blocks on Load

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27878]
### Problem Statement

When a loaded site comes up, the System table blocks all calls to Config, which renders the server inaccessible.  See this thread dump:

https://gist.github.com/wezell/5bb3393d5b1b2cde7ad246a6315f7e6b

The only way to prevent the instances from falling over is to set:
```
          - name: DOT_ENABLE_SYSTEM_TABLE_CONFIG_SOURCE
            value: 'false'
```

### Steps to Reproduce

Maybe load a site with graphql queries and flush cache?

### Acceptance Criteria

We need to not ever block getting a config value.

### dotCMS Version

23.10

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 1 - Show Stopper

**Comment by jdotcms** [comment]
closing b/c dupe https://github.com/dotCMS/core/issues/27020

**Comment by erickgonzalez** [comment]
Only for 23.10 LTS
