### ISSUE TITLE
REST api to all osgi ajax functions

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#27874]
### User Story

Remove the OSGIAjax in favor of the OsgiResource (note: to actually remove the UI has to use the new endpoint instead of the Ajax)

### Acceptance Criteria

All old functionality from OSGIAjax can be called via rest with the OsgiResource
The UI update to actually remove will be part of another issue, so UI will still working with old Ajax, but all functions will be available to called by rest:

1) /api/v1/osgi/dotsystem (will retrieve the dot system framework such as telemery, saml, tika, etc)
2) /api/v1/osgi/ (will get all osgi framework bundles, the ones you see in the portlet)
3) /api/v1/osgi/getInstalledBundles/ (will be deprecated)
4) /api/v1/osgi/_processExports/
5) /api/v1/osgi/bundle/xxx/jar/yyyy. (undeploy)
6) /api/v1/osgi/jar/yyyy (deploy)
7) /api/v1/osgi/stop/bundle/xxx/jar/yyyy (stop)
8) /api/v1/osgi/start/bundle/xxx/jar/yyyy (start)
9) /api/v1/osgi/_extra_packages (get extra packages)
10) /api/v1/osgi/_extra_packages (modify extra packages) 
11) /api/v1/osgi/restart/bundle/xxx/jar/yyyy (restart)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115497

### Quality Assurance Notes & Workarounds

Will add the notes, as soon as all functionality is done

**Comment by jdotcms** [comment]
if you call this:
http://localhost:8080/api/v1/osgi
 Retrieve all bundles installed
```

**Comment by jdotcms** [comment]
if you want to retrieve the available plugins, you can:
http://localhost:8080/api/v1/osgi/available-plugins
will retrieve something such as
```
{
"entity": [
"postman-bootstrap-0.1.jar",
"postman-bootstrap.fragment-0.1.jar"
],
```

**Comment by jdotcms** [comment]
to restart the framework
```
curl --location --request PUT 'http://localhost:8080/api/v1/osgi/_restart'
```

**Comment by jdotcms** [comment]
to get the extra packages:
```
http://localhost:8080/api/v1/osgi/extra-packages
```

**Comment by jdotcms** [comment]
to upd the extra packages:
```
curl --location --request PUT 'http://localhost:8080/api/v1/osgi/extra-packages' \
--header 'Content-Type: application/json' \
--data '{
    "packages": "!com.google.*,\n*;version=0,\ncom.aayushatharva.brotli4j.decoder;version=0,\ncom.aayushatharva.brotli4j.encoder;version=0,\ncom.aayushatharva.brotli4j;version=0,\ncom.beust........
```

**Comment by jdotcms** [comment]
to stops bundle
```
curl --location --request PUT 'http://localhost:8080/api/v1/osgi/_stop/bundle/6/jar/postman-bootstrap-0.1.jar6'
```

**Comment by jdotcms** [comment]
to starts bundle
```
curl --location --request PUT 'http://localhost:8080/api/v1/osgi/_start/bundle/6/jar/postman-bootstrap-0.1.jar6'
```

**Comment by jdotcms** [comment]
to undeploy
```
curl --location --request DELETE 'http://localhost:8080/api/v1/osgi/bundle/6/jar/postman-bootstrap-0.1.jar6'
```

**Comment by jdotcms** [comment]
deploy
```
curl --location --request PUT 'http://localhost:8080/api/v1/osgi/_deploy/jar/postman-bootstrap-0.1.jar' \
```

**Comment by jdotcms** [comment]
working on refactoring from the feedback
in addition need to do the changes on the UI in a separated ticket in order to remove the OSGIAJAX class at all.

**Comment by jdotcms** [comment]
This is the [PR](https://github.com/dotCMS/core/pull/28321) sent to master
