### ISSUE TITLE
Remove feature to copy-paste license

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#27891]
### Task

We've made some changes to the way we distribute licenses. The copy-paste license feature is no longer useful since we provide license packs. It's a simpler and more convenient way to manage your licenses. 

I understand that this option can be confusing for customers, so perhaps it's best to remove it to make the process easier for them.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Failed IQA: 

<img width="1198" alt="Screenshot 2024-04-18 at 5 35 20 PM" src="https://github.com/dotCMS/core/assets/1576794/86c4f743-39be-4427-86fc-b24cbec5fb59">
<img width="1199" alt="Screenshot 2024-04-18 at 5 34 41 PM" src="https://github.com/dotCMS/core/assets/1576794/7b09c6e9-8017-41fe-8ff5-2a9e273d0249">

"Upload License Pack" needs to be the left button.

>Active license already applied:
"Upload License Pack" and "Reset License"
No license applied:
"Upload License Pack" and "Request Trial License"

**Comment by dsilvam** [comment]
Passed Internal QA: Icons in the correct order.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9e49acb**, Docker, macOS 13.0, FF v124.0.2
