### ISSUE TITLE
Edit Page V2: Layout Editor Not Reflecting Template Changes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27899]
### Parent
#27546 

### Problem Statement
When changing the page template while in the layout editor, the changes do not reflect in the layout editor itself.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/043777a6-d6f5-4a18-b519-521fa9366680

```[tasklist]
### Acceptance Criteria
- [ ] The layout editor should update when the template change in the properties
- [ ] Fix this in the old editor as well
```

### External Links
N/A

### Assumptions & Initiation Needs
- Assuming that the page template change should be immediately reflected in the layout editor.
- Development team needs to investigate the codebase to identify the root cause of the issue.

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a0f63f4**, Docker, macOS 13.0, FF v121.0.1
