### ISSUE TITLE
Enhancements to `/api/v1/experiments/isUserIncluded` Endpoint

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27905]
### Parent Issue
#27539

### User Story
As a backend developer, I need to enhance the `/api/v1/experiments/isUserIncluded` endpoint to ensure it returns new experiments if they exist when ExperimentIDs are provided in the request body. Additionally, a property indicating which of these ExperimentIDs are still running should be included in the response in a separate property.

### Acceptance Criteria
- When ExperimentIDs are sent in the data body of a POST request to `/api/v1/experiments/isUserIncluded`, the endpoint must check for and return any new experiments in the response.
- The response should include a new property that clearly indicates which ExperimentIDs are currently running.
- Ensure that the endpoint's performance remains efficient, even with the added logic.
- Update the endpoint documentation to reflect these new features and provide examples of the expected request and response formats.
- If the user send in `excludedExperimentIds` and don't have any experiment retrieve a empty array not a experiment with ExperimentID = `NONE`

### Proposed object
```
export interface AssignedExperiments {
    excludedExperimentIds: string[];
    experiments: Experiment[];
    includedExperimentIds: string[];
    endedExperiments: string[] // <--- new array of string, which one of the sent experiments is now ended.
}
```

### Proposed Objective
API Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Assumptions & Initiation Needs
This change won't break the current Experiment functionality.

### Quality Assurance Notes & Workarounds
Quality assurance should include tests to verify that new and ongoing experiments are accurately returned based on the provided ExperimentIDs. Additionally, testing should ensure backward compatibility for clients not using the new request format.

**Comment by oidacra** [comment]
IQA Passed
`/api/v1/experiments/isUserIncluded` has now a new property `endedExperiments` with the list of the ended experiments sent in `excludedExperimentIds `

**Comment by bryanboza** [comment]
Hey folks, 

I notices some problems here: 

As part of the acceptance criteria we have this here: 
```
When ExperimentIDs are sent in the data body of a POST request to /api/v1/experiments/isUserIncluded, the endpoint must check for and return any new experiments in the response
```

In the set of test we are not validating this specific case in any of the provided test under the file `User_Include_Into_Experiment.postman_collection`

**Comment by freddyDOTCMS** [comment]
> Hey folks,
> 
> I notices some problems here:
> 
> As part of the acceptance criteria we have this here:
> 
> ```
> When ExperimentIDs are sent in the data body of a POST request to /api/v1/experiments/isUserIncluded, the endpoint must check for and return any new experiments in the response 
> ```
> 
> * In the set of test we are not validating this specific case in any of the provided test under the file `User_Include_Into_Experiment.postman_collection` since in all the calls we are not sending any Body in the request.
> 
> Also, please is important to provide us the parameter name that I need to send in the body.
> 
> * Regarding the documentation as best practice is importan to attach it in the documentation notes in the test, at lest we can include the link of the doc page
> 
> ![Image](https://private-user-images.githubusercontent.com/2641437/321796645-c0e87d00-95e8-4a99-a613-ed7ddd2d3959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzMzMzIsIm5iZiI6MTcxMjkzMzAzMiwicGF0aCI6Ii8yNjQxNDM3LzMyMTc5NjY0NS1jMGU4N2QwMC05NWU4LTRhOTktYTYxMy1lZDdkZGQyZDM5NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTQ0MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVmYWU3MWJlNDU0YTYzMTdhODdhZWI0MGI5MWY4ZWRjYmQ3NzM0MWQyZDRhYWVkNzQ4ODA2OTg1OWFjNGJiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.roo3KfB-F_-mXfaTNBDOilDAqEiqdikVuEjsxUKrHns)


- About the this Acceptance Criteria

When ExperimentIDs are sent in the data body of a POST request to /api/v1/experiments/isUserIncluded, the endpoint must check for and return any new experiments in the response.

Really the Endpoint was working like that before I don't need to do any change to fulfill it and it already have a test

https://github.com/dotCMS/core/blob/77989c8bf5dcc773042c8004442bd18fab0fad60/dotCMS/src/curl-test/User_Include_Into_Experiment.postman_collection.json#L414

- and about this one 

Update the endpoint documentation to reflect these new features and provide examples of the expected request and response formats.

Really this Endpoint is not on the Documentation because is not a Endpoint to be use by the dotCMS user directly

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_49f0621**, Docker, macOS 13.0, FF v124.0.2
