### ISSUE TITLE
Edit Page V2: Preserve Scroll Position in Page Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27901]
### Parent
#27546 

### Problem Statement
When users scroll down in the page editor and drag and drop contentlets to rearrange them, the page refreshes and scrolls back to the top, causing inconvenience and disrupting the user's workflow.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/e2357f17-2748-44a1-ab9a-150b4c175ab2

```[tasklist]
### Acceptance Criteria
- [x] When moving a contentlet the scroll position should not change in VTL version
- [x] When moving a contentlet the scroll position should not change in headless version
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker image: [`dotcms/dotcms:master_ca3eb44`]

https://github.com/dotCMS/core/assets/72418962/fcb2db7b-d34d-4bf7-a4b6-8668311f3aef

**Comment by fmontes** [comment]
There is a jump after the reload, and is expected (for now).

**Comment by fmontes** [comment]
Needs to update SDK and Vercel deploy

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected
