### ISSUE TITLE
Content Type link not working in Content Editor via Page Editor

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#27902]
### Problem Statement

The link that takes you to the Content Type editor from a given contentlet works when you arrive at the content editor by Content Search, but not when you use the Page editor.

### Steps to Reproduce

1. Open any contentlet via Content Search, and click the Content Type link on the right bar
    - This will work.
2. Open the Pages tool, then open any Page with an embedded contentlet
3. Edit a contentlet from there
    - The Content Type link will be visually styled as a link, and even has an `<a>` tag, but that **tag has no `href` attribute**

https://github.com/dotCMS/core/assets/102264829/4e579098-11ba-4fec-b43c-290ccd031804

### Acceptance Criteria

Add appropriate `href` attribute to the `<a>` tag on the Content Type link.

### dotCMS Version

Tested on:
dotcms-core 1.0.0-SNAPSHOT (March 07, 2024 3:27 PM)
dotcms-core 24.03.01 (March 01, 2024 4:13 PM)

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by jdcmsd** [comment]
Might not even be the `href` per se; the `href` on the content search version is pointed to `#`, and manually adding that to the broken side doesn't make it work. And both versions of the contentlet editor are reading [the same line of source code](https://github.com/dotCMS/core/blob/d09b03e3da4a0d353686bc8b92a5c3ba80755bea/dotCMS/src/main/webapp/html/portlet/ext/contentlet/contentlet_actions_inc.jsp#L267). So, I suspect it's not getting something it wants somewhere farther up the chain.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_b00ffaf**, Docker, macOS 14.5, FF v126.0.1

Issue is still happening on latest master
https://github.com/user-attachments/assets/f34507b9-4ed0-458c-b013-399ee767226d

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9bee608**, Docker, macOS 14.5, FF v126.0.1
