### ISSUE TITLE
Invalid role check when accessing resource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27909]
### Task

When specifying multiple roles to require for resource access, we use `OR` logic instead of `AND` logic.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- [Slack convo](https://dotcms.slack.com/archives/C5LHLNZ25/p1709920540090929)
- [Report doc](https://docs.google.com/document/d/1U4U1V608f9BsdYoj-mqTLqUdAomrkootmsHhm7fyP-Y/edit)

**Comment by AndreyDotcms** [comment]
Some tests done during internal QA

https://github.com/dotCMS/core/assets/127987858/1d539a21-87f4-42b8-8b99-1f9b91ee75cf

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_ca3eb44**, Docker, macOS 13.0, FF v121.0.1
