### ISSUE TITLE
Edit Page V2: Edit Content Compare versions 

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#27919]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### User Story

As a user, I want to be able to compare versions from the edit content in edit ema, so I can decide which version I want to bring back.

### Acceptance Criteria

* Compare button in History Tab should work as the old edit page

### How it should work

https://github.com/dotCMS/core/assets/63567962/ab89bed7-adf0-4e99-9796-63a27ef53b07

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

* Compare button should trigger an `ng-event` that should open an Angular Component
* This Angular Component already exists.

**Comment by KevinDavilaDotCMS** [comment]
This ticket is on stand-by as it depends on the implementation of this ticket: https://github.com/dotCMS/core/issues/27549

**Comment by zJaaal** [comment]
## IQA Failed 

It works as expected for contentlets inside the editor

## Screenshot
https://github.com/dotCMS/core/assets/63567962/ccd11d03-71e4-4f41-9394-3cdf331e3a7d


But when we try to bring back content for the Page, it looks like is returning an old version of the page, could be a race condition.


https://github.com/dotCMS/core/assets/63567962/475fa578-50bb-4a6c-b68d-2fa1a0c3174e

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_318564e**, Docker, macOS 13.0, FF v124.0.2
