### ISSUE TITLE
Log too verbose in certain situations

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27910]
### Task

When logging command output, dotCMS can be too verbose and write unneeded detail into the log output.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- [Beginning of slack convo](https://dotcms.slack.com/archives/C5LHLNZ25/p1709918805298339)
- [Report doc](https://docs.google.com/document/d/1ZszNUNJ5O0Ru4BfpeLCi20PFlppoDoWEHVsWUCn0mcg/edit#heading=h.3znysh7)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/28006

**Comment by bryanboza** [comment]
Fixed, tested before and after the fix and now we are just printing basic information
