### ISSUE TITLE
Allow users to Create, Delete, Update, List   custom content tool

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#27915]
### Parent Issue

https://github.com/dotCMS/core/issues/22353

### Task

Custom content tool functionality improve
https://github.com/dotCMS/core/issues/22353

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

We added the ability to create custom content tools - we need to also add the ability to EDIT the custom content tools. This would allow an admin to rename the tool or add/remove BASE_TYPES and or Content TYPES to it. Right now, the only option is to delete the tool and recreate it.

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27920
```

**Comment by erickgonzalez** [comment]
Now we're able to EDIT/Update them via REST API.
