### ISSUE TITLE
Investigate why endpoint_ids in the table publishing_pushed_assets are null

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#27928]
### Task

We have a customer with a recurring issue: for some contentlets, the endpoint_ids in the publishing_pushed_assets are being set to null, which breaks editing contentlet.

The customer affirms that no changes to endpoints have been made.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Null over this column shouldn't be an issue to edit the contentlet.

But we need to try to find the reason, why it's being set to null.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115537

**Comment by erickgonzalez** [comment]
I found a case where we inserted null endpoints into the `publishing_pushed_assets` table.

**STR:**

1- Create 2 PP environments: one dynamic and one static
2- Create a content
3- PP the created content for both environments.
4- Check the DB, and you'll see an entry with a null endpoint.
5- Try to edit the created content; you'll get an error.

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now this is working as expected! 

Tested on master // Postgres
