### ISSUE TITLE
CLI keeps requesting keychain Password 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#27926]
### Parent Issue

https://github.com/dotCMS/core/issues/27743

### Problem Statement

Under certain unknown circumstances, the cli keeps asking for the keychain password indefinitely. 
It loops over and over and over.    
![Screenshot 2024-03-08 at 13 10 13](https://github.com/dotCMS/core/assets/37148755/12cc1cc1-af45-436c-8298-439100db9821)

### Steps to Reproduce

The steps to reproduce it are still not very clear. We know it happens with the version installed through npm  
The jar archive version does not have this problem
The problem goes away when logging in with a token
The issue happens when executing for example the command  `status` before having a login 

### Acceptance Criteria

It is acceptable to have the cli to prompt the user for a password but just once. 

### dotCMS Version

current master 

### Proposed Objective

Customer Success

### Proposed Priority

Please Select

**Comment by fabrizzio-dotCMS** [comment]
Note to QA:
You can verify this by having multiple profiles in your dot-services.yml file 
You should have logged in to at least two of them before
Now you run dotcli status and the dialog that requires you to enter you system password should pop up just once.

**Comment by nollymar** [comment]
**Internal QA:** Passed

I only get password requests for the profile I'm logged in, not for all the profiles configured in my dot-service.yml file.
