### ISSUE TITLE
Edit Contentlet: Add TinyMCE V6 WYSIWFY field to the form

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27943]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

Implement the TinyMCE V6 to add the `WYSIWFY` field to the form.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] All plugins available on the old WYSIWYG field should work on the new field.
- [ ] The user should not lose the content when updating it to the new one.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Here is the list of plugins that are supported in the TinyMCE v6: https://github.com/dotCMS/core/issues/27519#issuecomment-1989469647

### Assumptions & Initiation Needs

**Docs:**

1. [Install TinyMCE V6 in Angular](https://www.tiny.cloud/docs/tinymce/latest/angular-pm/ ) (MIT License)
2. [Plugins](https://www.tiny.cloud/docs/tinymce/latest/plugins/)

### Quality Assurance Notes & Workarounds

The custom plugins that were developed in dotCMS for TinyMCE will be migrated to Angular in a separate ticket.

**Comment by fmontes** [comment]
![Image](https://github.com/dotCMS/core/assets/751424/88ea07d0-ea75-40ad-8d3d-3c3febf4b6ce)

**Comment by rjvelazco** [comment]
### QA Note:

Remember that this field belongs to the new `edit content`. In order to see the new field you need to:

1. Enable the following feature flags: 
```
"DOT_CONTENT_EDITOR2_CONTENT_TYPE":"*"
"DOT_CONTENT_EDITOR2_ENABLED": true
```
2. Enable the new edit content for the contentType:

![image](https://github.com/dotCMS/core/assets/72418962/862ba591-bb48-44a3-8e4f-fdfd74f132c3)

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_latest_SNAPSHOT`

The WYSIWYG field is showing up correctly in the new Edit Mode. Just make sure that the new UI in the WYSIWYG looks as specified by Freddy [in his comment above](https://github.com/dotCMS/core/issues/27943#issuecomment-2007257730). 

**IMPORTANT:** Some options from the previous UI, such as the strikethrough, underscore, adding links, anchors, etc. will be included in the new version in the future. They're out of scope for now.

**Comment by josemejias11** [comment]
**Approved**: Tested on **dotcms-qa-master.dotcms**, Docker, macOS 13.0, FF v121.0.1
