### ISSUE TITLE
Implement Error State, Empty State, and Loading State for Dot Table Component

### ISSUE THREAD

**Issue by manuelrojas** [dotCMS/core#27942]
### Parent Issue

#24343

### User Story

As a developer, I need to implement the empty state and error state functionality for the PrimeNG table component. The empty state will provide a clear visual indication when the table has no data to display, guiding users effectively. Conversely, the error state will notify users when an error occurs during data retrieval or processing, ensuring transparency and facilitating error resolution. 

### Acceptance Criteria

Match designs of empty, error and loading state. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

tables: https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?node-id=5521%3A188379&mode=dev

### Sub-Tasks & Estimates

**Comment by nollymar** [comment]
It won't be implemented. Not required, as we'll re use what we already have from other components
