### ISSUE TITLE
Edit Contentlet: Allow WYSIWYG user configuration through tinymceprops  Field Variable

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27944]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

- [x] Support all the field variables for the WYSIWYG field. [docs](https://www.dotcms.com/docs/latest/the-wysiwyg-field#TinyMCEProps)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The variable fields for the WYSIWYG field should work on the new Edit Content.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

All the field variables can be found here in our [docs](https://www.dotcms.com/docs/latest/the-wysiwyg-field#TinyMCEProps).

**Comment by rjvelazco** [comment]
### Note for Documentation




In the **Default Toolbar Buttons** section of our documentation ([here](https://www.dotcms.com/docs/latest/the-wysiwyg-field#PropertiesToolbarDefault)).

![toolbar-buttons](https://github.com/dotCMS/core/assets/72418962/2f134025-28fe-4e63-b586-7959525bf5f1)

In that section, the `dotAddImage` button doc is missing.

- The **`dotAddImage`** button allows you to add `images` from `dotCMS`.

![dotAddImage Dialog](https://github.com/dotCMS/core/assets/72418962/a1d89bf2-f7e7-467b-95d8-a49f379fc0a0)

**Comment by rjvelazco** [comment]
## Note For QA:

The WYSIWYG configuration through a JSON file will be addressed in this ticket: https://github.com/dotCMS/core/issues/28097

**Comment by rjvelazco** [comment]
## QA

### How to test it

1. Go to `Content Types`
2. Rich Text
3. Add Field variables.
4. Make sure the new `Edit Contentlet` is enabled for the `Rich Text` Content-Type

If something is not working, compare the new version with the old version using the same field variables.

### Video

https://github.com/dotCMS/core/assets/72418962/8e3c03c2-33aa-4c4a-b73c-84fb51663f69

**Comment by jcastro-dotcms** [comment]
## Internal QA: FAILED
- Docker Image: `master_latest_SNAPSHOT`

Rafa is going to work on some improvements before going back to IQA. This way, the handling of TinyMCE properties will match our current official documentation.

**Comment by rjvelazco** [comment]
### Note for Documentation

The `theme` property is not available in TinyMCE V6 with the old version options [`simple`, `modern`, and `advanced`]. Do we need to update the docs? @wezell @jdcmsd 

- DotCMS documentation: https://www.dotcms.com/docs/latest/the-wysiwyg-field#PropertiesStyle
- TinyMCE V6 documentation: https://www.tiny.cloud/docs/tinymce/latest/editor-theme/

**Comment by jdcmsd** [comment]
Just scoped it out on Master QA, looks neat! The doc most definitely will need an update, yeah. I'll give it a once-over to see what else needs to be tweaked or qualified.

When do we estimate we'll release the new contentlet editor?

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: FAILED
* Docker Image: `master_485388e`
The following error shows up in the log:
```
dotcms-1      | 13:34:54.449  ERROR vtl.VTLResource - Exception on VTL endpoint. GET method: The vtl: /application/apivtl/tinymceprops/get.vtl does not exists
dotcms-1      | com.dotmarketing.exception.DoesNotExistException: The vtl: /application/apivtl/tinymceprops/get.vtl does not exists
dotcms-1      | 	at com.dotcms.rest.api.v1.vtl.FileVelocityReader.getVelocity(FileVelocityReader.java:57) ~[classes/:?]
dotcms-1      | 	at com.dotcms.rest.api.v1.vtl.VTLResource.processRequest(VTLResource.java:514) ~[classes/:?]
dotcms-1      | 	at com.dotcms.rest.api.v1.vtl.VTLResource.get(VTLResource.java:100) ~[classes/:?]
dotcms-1      | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
dotcms-1      | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
dotcms-1      | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
dotcms-1      | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.22.1.jar:?]
dotcms-1      | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.22.1.jar:?]
...
...
..
```

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: PASSED
* Docker Image: `master_485388e`

After a screen share session with @rjvelazco , he provided the instructions on how to test this correctly. He will be updating the steps to reproduce as the configuration format for changing the WYSIWYG options has changed.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
