### ISSUE TITLE
Edit Contentlet: Allow users to switch between modes in the WYSIWYG field

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27945]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

The WYSIWYG field offers three modes: WYSIWYG, CODE, and PLAIN. Users can select a custom language in CODE mode. We need to keep that behavior.

![WYSIWYG-modes](https://github.com/dotCMS/core/assets/72418962/e9244781-3f8d-401f-8459-d6384b914607)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] Users should be able to switch between modes.
- [ ] Allows users to set a custom language when editing in code mode.

### Assumptions & Initiation Needs

We need this ticket to be merged first: https://github.com/dotCMS/core/issues/27943

**Comment by oidacra** [comment]
Close in favor of https://github.com/dotCMS/core/issues/28186
