### ISSUE TITLE
Edit Contentlet: Make our  dotAddImage custom plugins for TinyMCE work in Angular

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#27969]
### Parent Issue

#25445

### Task

dotCMS has a custom plugin called [dotAddImage](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/tinymce/js/tinymce/plugins/dotCustomButtons/plugin.min.js) which allows user add images coming from dotCMS into their WYSIWYG field. Since we are moving this field from dojo to Angular, we must bring this custom plugin and it should work as expected.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] The [dotAddImage](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/tinymce/js/tinymce/plugins/dotCustomButtons/plugin.min.js) plugin should work as expected in the new WYSIWYG field

### Assumptions & Initiation Needs

- Search how to add custom plugins in tinyMCE v6 Angular integration.
- Check out the `dotAddImage` plugin and see how it works.

**Comment by zJaaal** [comment]
## Failed IQA 

File Asset Images are not getting rendered


https://github.com/dotCMS/core/assets/63567962/0137160f-3c07-4c49-ab8c-61b9eb1b2c69

**Comment by rjvelazco** [comment]
Fixed here:  #28075 @zJaaal

**Comment by zJaaal** [comment]
## IQA Passed 

Now I can add FileAssets as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1fd3428**, Docker, macOS 13.0, FF v121.0.1
<img width="995" alt="Screenshot 2024-04-01 at 12 41 14 PM" src="https://github.com/dotCMS/core/assets/129882031/dfe07268-cb7c-4267-97a9-2266f12fe91a">
