### ISSUE TITLE
Edit Page V2: Unable to Add New Content to Containers in dotCMS Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27964]
### Parent
#27546 

### Problem Statement
Users are currently unable to add new content to any container in the new editor in dotCMS.

### Steps to Reproduce
1. Go to the new editor
2. Click in the +
3. Create a new piece of content (don't reuse)
4. Click Save and Publish
5. Content is not in the page.

### External Links
N/A

### Assumptions & Initiation Needs
1. You can add D&D from palette
2. You can reuse content
3. But you can't add NEW content

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_f68e6f2**, Docker, macOS 13.0, FF v124.0.2
