### ISSUE TITLE
Edit Contentlet: Allow user to configure Image URL Format Pattern in WYSIWYG Field

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28011]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

We need to allow users to configure the URL for WYSIWYG images. [Docs](https://www.dotcms.com/docs/latest/the-wysiwyg-field)

![image](https://github.com/dotCMS/core/assets/72418962/48fabb20-112e-4ee7-927d-0bf08a2e7859)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

1. Users should be able to configure the URL for WYSIWYG Images.

**Comment by jcastro-dotcms** [comment]
## INTERNAL QA: PASSED
- Docker Image: `master_485388e`

I can update the Image URL format as required by setting the expected environment variable: This is the one I used for my tests:
```
DOT_WYSIWYG_IMAGE_URL_PATTERN: '/dA/{shortyInode}/{name}?language_id={languageId}&hostname={hostname}&path={path}'
```

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
