### ISSUE TITLE
Revamping Release Process Workflow to Enhance Security and Stability

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#28014]
### User Story
As a dev-ops engineer, I want to modify the release process workflow to stop pushing commits by overriding branch protection rules. Instead, we will use temporary release branches to create the release tag. Then we will remove any Github account from overriding branch protection rules at corresponding Github UI.

As a security director, I want to have to show branch protection evidence without opening a conversation about why we need an exception for brach protection override on a machine user to our SOC 2 auditors. 

### Acceptance Criteria
1. Create a process to generate temporary release branches for creating release tags.
2. Implement mechanisms to prevent pushing commits by overriding branch protection rules.
3. Remove any Github account from overriding branch protection rules via Github UI.
4. Ensure the release process is smooth and reliable.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 1 - Show Stopper

### External Links
- [Finding in Vanta](https://app.vanta.com/tests/github-ensure-branch-protection-enforced) (our security and compliance management system) 
- [Initial slack conversation in #developers](https://dotcms.slack.com/archives/C028Z3R2D/p1710874755539129)

### Assumptions & Initiation Needs
- Assumption: Development team is familiar with Git and Github workflow.
- Initiation: Discuss with the development team the changes required in the release process.

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates
1. Implement temporary release branch generation: 3 hours
2. Remove Github accounts from overriding branch protection: 1 hours

**Comment by dsilvam** [comment]
Passed IQA: @victoralfaro-dotcms tested it on a test release process. 
Final QA will be performed when the official release process gets executed again.
