### ISSUE TITLE
Edit Page V2: Styling Issue with Dojo Iframes in UVE on Firefox

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28024]
### Parent
#27546 

### Problem Statement
In the UVE running in Firefox, there are styling issues with the dojo iframes, causing them to appear incorrectly.

### Steps to Reproduce
1. In Firefox: Go to new editor
2. Add a content
3. See how the buttons and dropdowns are broken.

<img width="1954" alt="image" src="https://github.com/dotCMS/core/assets/751424/9085dc81-6ab7-40a1-b1c0-40e0ad4b2fb3">

### Acceptance Criteria

1. The dojo widgets and component should load correctly

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
- Only happening in FF

**Comment by rjvelazco** [comment]
### Faild Internal QA

- Tested on Docker image: [`dotcms/dotcms:master_1fd3428`]
- Web Browser: `Firefox`

**Steps to Reproduce**

1. Go to the new Edit Page. [Remember to enable the `FEATURE_FLAG_NEW_EDIT_PAGE` feature flag]
2. Click on a `+` button.
3. Create a new `contentlet`.
4. See the error.

**Video**

https://github.com/dotCMS/core/assets/72418962/0f7f6b37-f05a-4d1a-bc5f-886e2c41569f

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_f68e6f2**, Docker, macOS 13.0, FF v124.0.2
