### ISSUE TITLE
Edit Page V2: Allow Drag and Drop Functionality for Images in dotCMS

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28039]
### Parent
#27546 

### Task description
As a user, I want to be able to drag and drop images from my file system directly into a container within dotCMS, so that I can easily upload and add images to my content without having to go through multiple steps.

### Acceptance Criteria
1. Users can drag and drop images from their file system directly into a container within dotCMS.
2. The dropped images are successfully uploaded and displayed in the container.
3. Users receive a confirmation message upon successful upload.
4. The uploaded images are saved in the correct location within the dotCMS file structure.
5. The drag and drop functionality works across different browsers and operating systems.

### External Links
N/A

### Assumptions & Initiation Needs
- Users have the necessary permissions to upload images within dotCMS.
- The drag and drop functionality is supported by the browser being used.
- The container where images are dropped has been correctly set up to receive image uploads.

### Quality Assurance Notes & Workarounds
- Test the drag and drop functionality on different browsers and operating systems to ensure compatibility.
- Verify that the uploaded images are displayed correctly in the container after the drag and drop action.
- Check for any error

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master
VTL - Chromium Browser

https://github.com/dotCMS/core/assets/144152756/4b9e8f41-df72-4f38-8b1f-99aa9d3618f5

VTL - Firefox

https://github.com/dotCMS/core/assets/144152756/82d1a6fb-be7c-4e26-88c9-f959bc0e0558

Headless - Chromium Browser

https://github.com/dotCMS/core/assets/144152756/3875a4c5-8d12-411c-9268-c373a7161554

Headless - Firefox

https://github.com/dotCMS/core/assets/144152756/731460fa-8ee1-416b-a251-ebbdd254e6d8

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_58d55d2**, Docker, macOS 13.0, FF v124.0.2

When using Firefox and trying to drop he asset and not releasing the mouse click (meaning if a don't want to added anymore) the application freezes and the edit mode doesn't work anymore

https://github.com/dotCMS/core/assets/129882031/1148266d-43ca-4ec1-b169-aee767e9b0a0



Only System containers are showing the thumbnail of the uploaded asset (not sure if this is by desing)

<img width="1280" alt="Screenshot 2024-05-03 at 7 55 14 AM" src="https://github.com/dotCMS/core/assets/129882031/42bfaa24-f457-4486-b489-b77fb3907d52">

**Comment by zJaaal** [comment]
## Note to QA

The images not showing on default container is a known issue, we need to update the starter to change the url that is being used to render the image. Here is the ticket to update the starter https://github.com/dotCMS/core/issues/28269

You can see that the editor is flickering when you drop an image outside of the browser, that's expected at the moment we have to work on a fix. @KevinDavilaDotCMS already have some code that will fix that https://github.com/dotCMS/core/pull/28419

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_5921e6a**, Docker, macOS 13.0, FF v124.0.2
