### ISSUE TITLE
Copy Site with Content Types Inclusion

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28035]
### Parent
#27727

### User Story
As a dotCMS user, I want to be able to include content types when copying a site, so that I can easily replicate the structure of the original site.

### Acceptance Criteria
- Add a checkbox in the dialog of copy site options to include content types.
- When the checkbox is selected, all content types associated with the site should be copied over to the new site.
- The copied content types should retain their configurations and settings in the new site.
- By default, copying Content Types when copying Sites is disabled. In order to enable it, set the `FEATURE_FLAG_ENABLE_CONTENT_TYPE_COPY` to `true`.

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links
Static Content: "N/A"

### Assumptions & Initiation Needs
- The user has permission to copy sites in dotCMS.
- The user understands the relationship between content types and sites in dotCMS.

### Quality Assurance Notes & Workarounds
- QA should verify that the checkbox for including content types works as expected.
- QA should test the copied content types to ensure they retain their configurations.
- QA must test the Relationship field and all of its combinations.

### Sub-Tasks & Estimates
- Develop checkbox in the copy site dialog (2 hours)
- Implement functionality to copy content types (4 hours)
- Test

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker image: [`dotcms:master_a5c816a`]

### Notes
1. I tested the `Copy Site` feature without checking the `contenttype` checkbox and the behavior was as expected.
2. I tested the `Copy Site` feature checking the `contenttype` checkbox, disabling the `All` options, and the behavior was as expected/


### Video

https://github.com/dotCMS/core/assets/72418962/0d376e71-af2c-4a3c-82d3-1498ed526c98

**Comment by bryanboza** [comment]
We need some work here: 

- After this change, when I try to copy a demo site using the full starter data, we are getting some errors related to the relationship field 
Here the complete log: https://gist.github.com/bryanboza/73fcbc7e4da0c99d3b4f6c7d6bc5ad20

**Comment by bryanboza** [comment]
Fixed, we roll back this fix and now is under a feature flag... Some problems around this functionality has been mover to a new card #28339. 

Seems those are old behavior and was present in previous releases. We can pass this one for now.

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master

https://github.com/dotCMS/core/assets/144152756/4f843d52-6ca7-4904-a2c3-99cb5d8c964f

**Comment by bryanboza** [comment]
According to a conversation in the slack channel https://dotcms.slack.com/archives/CQQMX585N/p1717108350306389 , we will need an extra discussion here. 

Maybe the variable should be unique per site. For instance, a client with a large site that includes multiple scripts pulling content from specific content types might encounter issues. When we copy the content type, the page, and the data, the script will continue fetching data from the original content type, not the one that now resides in their site. Manually modifying each instance could be a lot of work on production sites. 

Also, containers won't work either.

**Comment by wezell** [comment]
I wonder if we should append a knowablt key to the end of the new content type variables.  This would allow - in dynamic pulls - to automatically have a shared widget pull the right content types 

Think blog listing widget.  It pulls `+contentType:blogs` with an `order by blogs.publishdate` on the main site.

if the widget gets copied, it will be looking for the wrong content type with an invalid `orderby`.

If we had a knowable key then we could append it and the widget will just work, e.g.
pulls `+contentType:blogsNewsiteCom`
order by `blogsNewsiteCom.publishdate`

which could be represented by `+contentType:blogs${siteKey}` and order by  `blogs${siteKey}.publishdate`
