### ISSUE TITLE
Edit Page V2: Enable Navigation Sorting Feature

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28040]
### Parent
#27546 

### Task description
As a dotCMS user, I want to be able to sort the navigation on my website so that I can easily organize and rearrange the menu items based on my preferences.

Let's create a new macro with HTML and CSS inline so we can control the styling, use this one as base:

```
#macro(orderMenu)
    #if ($EDIT_MODE && $PUBLISH_HTMLPAGE_PERMISSION)
        #set($menuLevel = $VTLSERVLET_URI.split('/').size() - 1)

        <a href="#" onclick="openReorderDialog(event)" class="btn btn-primary btn-xs normaltip" data-original-title="Reorder Menu">
            <i class="fa fa-arrow-up"></i>
            <i class="fa fa-arrow-down"></i>
        </a>
        <script>
            function openReorderDialog(event) {
                event.preventDefault();
                var reorderUrl = "${directorURL}&startLevel=${menuLevel}&depth=2&pagePath=${VTLSERVLET_URI}&hostId=${host.identifier}";
                var customEvent = window.top.document.createEvent("CustomEvent");
                customEvent.initCustomEvent("ng-event", false, false,  {
                    name: "reorder-menu",
                    data: reorderUrl
                });
                window.top.document.dispatchEvent(customEvent);
            }
        </script>
    #end
#end
```

Add the macro to the starter and make it work with the custom event.

```[tasklist]
### Acceptance Criteria
- [ ] User should be able to sort their nav in VTL pages
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

**Comment by fmontes** [comment]
Tested in latest trunk.

Needs to add the new macro `#sortNavigation()` in the `applications/theme/travel/header.vtl` around line 82.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_dda1860**, Docker, macOS 13.0, FF v124.0.2

1. Reordering only works for top menus and not for the submenus
2.Once you open a submenu and try to reorder, then the top menus stop reappearing 

<img width="1294" alt="Screenshot 2024-04-22 at 1 33 59 PM" src="https://github.com/dotCMS/core/assets/129882031/33dc5fb4-2824-4771-a78b-f42515f2f998">

**Comment by rjvelazco** [comment]
### Passed Internal QA
 
 - Tested on Docker image:  [`dotcms/dotcms:trunk_c84abae`]
 
 ### Video

https://github.com/dotCMS/core/assets/72418962/07d474fa-1b06-4939-8f65-7ff9b549052d

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_c1fbb01**, Docker, macOS 13.0, FF v124.0.2

Cancel button is not working
<img width="1280" alt="Screenshot 2024-04-26 at 3 51 51 PM" src="https://github.com/dotCMS/core/assets/129882031/46d1d0f5-87cb-4fd8-9e42-bea6d787ed7a">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_318564e**, Docker, macOS 13.0, FF v124.0.2
