### ISSUE TITLE
Modify Endpoint to Accept Array of Objects for Jitsu Event Data

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28045]
### Parent Issue
#27539

### User Story
As a backend developer, due to the transition from using Jitsu as an HTML snippet to using the direct Jitsu library, I need to modify our event data reception endpoint to accept an array of objects instead of a single object. The structure of the objects within the array remains the same as before, with only the data format changing to an array.

### Acceptance Criteria
- The endpoint that receives Jitsu event data must be updated to process an array of objects rather than a single object.
- The integrity and structure of the individual objects within the array should be validated as before, ensuring they meet the previously established data format.
- Ensure backward compatibility where possible, or provide a clear migration path for services relying on the previous single-object format.
- Implement thorough testing to verify that the endpoint accurately processes arrays of event data and correctly handles each object within the array.

### New Request Payload
```
[
  {
    experiments: [
      {
        experiment: '4ae15021-e085-47fa-904e-408c2f684687',
        runningId: '4aba5d5e-df19-455f-aae2-d9d6360f1641',
        variant: 'DEFAULT',
        lookBackWindow: '5ukTUTAlyj2uQdxadNP1',
        isExperimentPage: false,
        isTargetPage: false,
      },
      {
        experiment: '096efa0d-6ae7-428a-b87d-d958241e73db',
        runningId: '84ba6b26-0a7b-40fa-9ea8-ca1e925d821c',
        variant: 'dotexperiment-096efa0d6a-variant-1',
        lookBackWindow: 'zk4Twz1gaszS2hVVDJs8',
        isExperimentPage: false,
        isTargetPage: false,
      },
    ],
    event_id: '',
    user: { anonymous_id: 'jshqaf3oav' },
    ids: {},
    utc_time: '2024-03-21T17:55:12.352000Z',
    local_tz_offset: 240,
    referer: '',
    url: 'http://localhost:4321/',
    page_title: 'Experiment Demo - Home',
    doc_path: '/',
    doc_host: 'localhost',
    doc_search: '',
    screen_resolution: '1728x1117',
    vp_size: '820x992',
    user_agent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    user_language: 'en-US',
    doc_encoding: 'UTF-8',
    utm: {},
    click_id: {},
    api_key: 'js.cluster1.customer1.81snxx6dvbgne5ptxh',
    src: 'jitsu',
    event_type: 'pageview',
  },
];
```

### Proposed Objective
API Enhancement, Data Handling Improvement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

**Comment by oidacra** [comment]
IQA Passed
The endpoint now accepts an array or object as body content.
![Screenshot 2024-04-04 at 6 00 48 PM (1)](https://github.com/dotCMS/core/assets/1909643/c7ca7ac3-5a5b-4206-abaa-e814c95b48dc)

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_c59b161**, Docker, macOS 13.0, FF v124.0.2
