### ISSUE TITLE
Edit Page V2: Unlocking a Locked Page Feature

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28041]
### Parent
#27546 

### User Story
As a content editor, I want to be able to unlock a page that is locked by another user with proper permissions, so I can make necessary edits.

**PAGE CAN'T BE LOCKED FROM UVE (Universal Visual Editor)**

```[tasklist]
### Acceptance Criteria
- [ ] The user should see a notification bar indicating that the page is locked by another user.
- [ ] There should be a button available to unlock the page (if user has permission to unlock)
- [ ] The user should be able to unlock the page by clicking the button.
- [ ] Once unlocked, the user should have full editing capabilities on the page.
- [ ] While unlock request is happening we should see loading animation to the button
```

### Design

Page is locked and can be unlocked
![image](https://github.com/dotCMS/core/assets/751424/f0113d8a-1816-458b-96df-1a9af9a72c6f)

Page is locked and CAN'T be unlocked
![image](https://github.com/dotCMS/core/assets/751424/16d486d4-b597-4832-ba58-c295a62e82b7)

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
- [Figma locked can unlock](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2901%3A71326&mode=design&t=9SmLxqID2f4Uk5ZB-1)
- [Figma locked can't unlock](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2901%3A71517&mode=design&t=9SmLxqID2f4Uk5ZB-1).
- [Prototype](https://www.figma.com/proto/trbwjLuf5F6KaU1rFucNeg/Edit-Page?page-id=1902%3A6704&type=design&node-id=2901-71326&viewport=1120%2C-7438%2C0.38&t=LhVcv54HwQAXbNJ7-1&scaling=scale-down&starting-point-node-id=2901%3A71326&mode=design)

### Assumptions & Initiation Needs
- There is a property in the page API `canUnlock`
- The locked page is not being actively edited by the user who locked it.

### Quality Assurance Notes & Workarounds
N/A

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `master_836c7db`

In the new UI, the warning message saying `Locked by ${User Name}` is showing up correctly.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a1b916e**, Docker, macOS 13.0, FF v124.0.2
<img width="1269" alt="Screenshot 2024-04-18 at 11 57 34 AM" src="https://github.com/dotCMS/core/assets/129882031/78f3b359-b649-44d3-aae8-e67a0003c3bf">
