### ISSUE TITLE
dotCLI: Add ability to send site variables when sending a host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28059]
### User Story

Customers would like the ability to add site variables via the CLI - this would be helpful to customers when developing new sites.

The variables could simply be contained in a `dot_SiteVariable` property that is included in the Site.json files.    We should follow the pattern we use for setting other collections.  If the `dotSiteVariable` is set, we sync the site variables to match what is being passed in.  If the `dotSiteVariable` exists and is empty, then we delete all the site variables in the target site.  If the `dotSiteVariable` property does not exist, we do not touch the site variables.

### Acceptance Criteria

It should be possible to add or edit site variables using the CLI.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Feedback from customer

> We make heavy use of site variables.  We tested by creating a variable in the admin site and ran a Pull.  The variables never show up in the site descriptor JSON file. Ideally, we’d love to be able to read/write these locally as well.  This would be extremely helpful in the development of Velocity templates that leverage these variables.

**Comment by fabrizzio-dotCMS** [comment]
Some work on this has been done [here](https://github.com/dotCMS/core/pull/28188)

**Comment by fabrizzio-dotCMS** [comment]
we need a small improvement error handling wise I was able to push the following request 
```
{
  "dotCMSObjectType" : "Site",
  "inode" : "b92c1727-772a-4ad1-a18d-10646655ecaf",
  "identifier" : "8a7d5e23-da1e-420a-b4f0-471e7da8ea2d",
  "aliases" : null,
  "systemHost" : false,
  "siteName" : "default",
  "tagStorage" : "8a7d5e23-da1e-420a-b4f0-471e7da8ea2d",
  "siteThumbnail" : "",
  "runDashboard" : false,
  "keywords" : null,
  "description" : null,
  "googleMap" : null,
  "googleAnalytics" : null,
  "addThis" : null,
  "proxyUrlForEditMode" : null,
  "embeddedDashboard" : null,
  "languageId" : 1,
  "variables" : [ {
    "name" : "var1",
    "key" : "var1",
    "value" : "value-1"
  }, {
    "name" : "var3",
    "key" : "var3",
    "value" : "lol"
  }, {
    "name" : "var3",
    "key" : "var3",
    "value" : "lol2"
  } ],
  "modDate" : "2024-04-26T22:25:48.084+00:00",
  "modUser" : "dotcms.org.1",
  "live" : true,
  "default" : true,
  "locked" : true,
  "archived" : false,
  "working" : true
}
```
I can send dups. And the second key is the one that prevails. But since the UI prevents such situation we should do the same. We need to modify the endpoint to report an error and present it in the cli


Additionally I got an error when pushing from within the sites folder whenever I do :

```
fabrizzioaraya@Fabrizzios-MacBook-Pro sites % dot push --dry-run
-
 ──────
 No changes in Languages to push


|
 ──────
 Push Data: [1] Sites to push: (0 New - 1 Modified)

 Sites:
     └── default.json ✎

-
 ──────
 No changes in ContentTypes to push


[ERROR] ❗  Error in command [push] with message:
  Invalid source path. Source path must be inside the files folder or at the root of the workspace
run with -e or --errors for full details on the exception.
fabrizzioaraya@Fabrizzios-MacBook-Pro sites %
```

**Comment by wezell** [comment]
I think this is acceptable Fabro.

**Comment by fabrizzio-dotCMS** [comment]
Per @wezell's comment Im passing it

**Comment by fabrizzio-dotCMS** [comment]
Passing it to QA as I was able to manipulate site vars without any problem
a new issue was found and it is filed [here](https://github.com/dotCMS/core/issues/28473)

**Comment by bryanboza** [comment]
Fixed, able to get site variables after this change: 

```
{
  "dotCMSObjectType" : "Site",
  "inode" : "9a8f37fb-d70b-4f54-a299-a3a0a4e4c011",
  "identifier" : "415ad4ca0aa0fb002e4593537a32c2bf",
  "aliases" : null,
  "systemHost" : false,
  "siteName" : "testSite",
  "tagStorage" : "48190c8c-42c4-46af-8d1a-0cd5db894797",
  "siteThumbnail" : "",
  "runDashboard" : false,
  "keywords" : null,
  "description" : null,
  "googleMap" : null,
  "googleAnalytics" : null,
  "addThis" : null,
  "proxyUrlForEditMode" : null,
  "embeddedDashboard" : null,
  "languageId" : 1,
  "variables" : [ {
    "name" : "test1",
    "key" : "test1",
    "value" : "test1"
  } ],
  "modDate" : "2024-05-08T22:36:28.144+00:00",
  "modUser" : "dotcms.org.1",
  "default" : false,
  "locked" : false,
  "live" : true,
  "archived" : false,
  "working" : true
}

```

**Comment by bryanboza** [comment]
Fixed, new task related to the test improvements created here: https://github.com/dotCMS/core/issues/28543
