### ISSUE TITLE
🐛 Block Editor: Thumbnails Not Showing in Contentlet Block

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28055]
### Problem Statement
Thumbnails in the contentlet block inside the block editor are not showing.

### Steps to Reproduce
<img width="1418" alt="image" src="https://github.com/dotCMS/core/assets/751424/cb0d11ee-edeb-495c-92ad-b9aa45b1a12e">

### Acceptance Criteria
Thumbnails show show

### External Links
N/A

### Assumptions & Initiation Needs
This is happening in demo.dotcms.com

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_99864a2**, Docker, macOS 13.0, FF v121.0.1

![Image](https://github.com/dotCMS/core/assets/129882031/e9875b1d-3cf6-4fb6-9bbc-5d609359751d)
