### ISSUE TITLE
Content Block does not show thumbnail

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28050]
### User Story

When you add content to the block editor, we used to show the content's thumbnail.  We lost this somewhere.

### This is a screenshot from our current demo 2024-03-21 

![Screenshot 2024-03-21 at 4 47 33 PM](https://github.com/dotCMS/core/assets/934364/81c3829d-fc00-48b9-814a-0c434bda3c88)

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 4 - Trivial

**Comment by fmontes** [comment]
Fixed here:

Ticket https://github.com/dotCMS/core/issues/28055
PR: https://github.com/dotCMS/core/pull/28060
