### ISSUE TITLE
REST api to start/stop osgi plugin

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28078]
### User Story

Currently, dotCMS supports [almost all methods](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/OSGIResource.java) for osgi plugin through REST API.

And when a plugin is deployed through REST API, The deployed plugin remains **resolved** and manually **starts** just moves the plugin into **active** state.

For more context, The plugin portlet calls API `baseurl/DotAjaxDirector/com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX?cmd=start&bundleId=id&jar=file.jar` to start/stop

So, It is also a good idea to support the start/stop method through REST API.

### Acceptance Criteria

A REST api that allows the start/stop osgi plugin.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115497

Related issue: https://github.com/dotCMS/core/issues/27874

**Comment by erickgonzalez** [comment]
Closing this one in favor of https://github.com/dotCMS/core/issues/27874
