### ISSUE TITLE
Edit Page V2: Experiments UI/UX Tweaks

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28076]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### User Story

As a content editor, I want to be able to see hints of experiments variants and also the editor should prevent me from making mistakes while running experiments, so I can edit and preview variants in a safe way.

### Acceptance Criteria

* Editor should hint the user when a variant is being edited/previewed
* Editor should prevent the user from executing workflow actions on variants
* Editor should have a button to take the user back to experiments

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

We have some [figma designs](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2897-17391&mode=dev) 
Also some findings from @rjvelazco [IQA](https://github.com/dotCMS/core/issues/27676#issuecomment-2018425211) 

### Assumptions & Initiation Needs

* You should have access to the new Visual Editor
* You have Experiments running in your environment 

### Quality Assurance Notes & Workarounds

No notes at the moment.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
