### ISSUE TITLE
Pound char not decoded when using Rules or Vanity URLs

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28089]
### Problem Statement

It seems that there may be an issue with the decoding of the pound symbol (#) in redirects when utilizing Rules or Vanity URLs.

### Steps to Reproduce

1- Create a new Rich Text content with the following data: 
[RichTextAnchors.txt](https://github.com/dotCMS/core/files/14775519/RichTextAnchors.txt)
2- Create a new page at root level
3- Add the content created in step 1

**Vanity Url:**
1- Create a new Vanity URL with the following data:
- Title: testpound
- Uri: /testpound
- Action: 301
- Forward To: /test#SwissAlps
2- From the Terminal hit the following curl:
```
curl --head https://demo.dotcms.com/testpound
```
3- Check the location response `location: /test%23SwissAlps`

**Rules:**
1- Create a new RuleL with the following data:
- Title: testpoundrule
- Evaluate: Every Page
- Condition: Current Url -> Contains -> testpoundrule
- Action: Redirect requests to -> MOVED_PERM -> /test#SwissAlps
2- From the Terminal hit the following curl:
```
curl --head https://demo.dotcms.com/testpoundrule
```
3- Check the location response `location: /test%23SwissAlps`

### Acceptance Criteria

Special Chars should be decoded.

### dotCMS Version

23.01+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C06QJH22CF8/p1711485642700329

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk

### Vanity Url:
![image](https://github.com/dotCMS/core/assets/2641437/75fa65ef-e4cd-4f22-b91c-f28f3bfc7ad3)

### Rules:
![image](https://github.com/dotCMS/core/assets/2641437/af747e50-a8f0-4c47-8da2-e5ad40cd41fc)
