### ISSUE TITLE
Force HTML highlighting for .vtl files

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28084]
### User Story

When editing a VTL using the new monaco editor in the system, it is important that I should get good syntax highlighting on my files.  As there is no VTL setting for monaco, we should force the HTML syntax onto VTL files.

This is how it looks now:

![Screenshot 2024-03-26 at 4 26 09 PM](https://github.com/dotCMS/core/assets/934364/850641e5-6e12-461c-a15a-e1b36ab9afce)

### Acceptance Criteria

I should see HTML color coded when looking at a VTL file

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF

**Comment by zJaaal** [comment]
## IQA Passed

Docker Image: `[dotcms/dotcms:trunk_430f4c7]`

### Screenshot
https://github.com/user-attachments/assets/45a2c2b5-5de8-48f4-9f36-e7855addd208

**Comment by bryanboza** [comment]
Fixed, tested on trunk and now it is working as expected 

![Image](https://github.com/user-attachments/assets/f168c8c3-1869-48b2-899c-be61065f8f97)

**Comment by erickgonzalez** [comment]
Only for 24.04 LTS
