### ISSUE TITLE
Edit Page V2: Internal Links Navigation Bug

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28096]
### Parent
#27546 

### Problem Statement
When users navigate within a page using internal links, the navigation breaks and the links do not redirect to the correct sections of the page.

### Steps to Reproduce
1. Edit a VTL page
2. Click on any internal link (href)
3. Page broke!

### Acceptance Criteria
User should be able to navigate in the internal links.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
- Currently, there is no workaround for this issue. 
- QA team should thoroughly test all internal links on affected pages to ensure proper navigation.

**Comment by rjvelazco** [comment]
### Fail Internal QA

1. Go to Edit Page [`New Edit Page`]
2. Add a new `contentlet` that has a link
3. Click on that link
4. See the error

### Video

https://github.com/dotCMS/core/assets/72418962/79edc5a5-bd33-4223-bfe4-10309594439b

**Comment by rjvelazco** [comment]
## Passed Internal QA

-  Tested on Docker:  [`dotcms:master_c4932c7`]

### Video 

https://github.com/dotCMS/core/assets/72418962/f0b02013-c723-4770-897b-839fc22e0686

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF. Now links navigation is working as expected
