### ISSUE TITLE
PDF as Binary / upload field doesn't show preview

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28105]
### Problem Statement

When uploaded PDF as binary field. It doesn't show preview for it. However it shows previews for other binary data like PNG, JPEG

https://github.com/dotCMS/core/assets/102758033/ab776eaf-d2db-437f-9b0f-655ffc20994a

Here in video the first of bug has fixed. Now the PDF/file name shows after uploading so only preview is absent

### Steps to Reproduce

Create a content type for binary field
Create a contentlet for it
upload PDF 
There is no preview for it

### Acceptance Criteria

It must show preview for PDFa 

### dotCMS Version

Master [24.03.22]

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

**Comment by dsolistorres** [comment]
Internal QA approved:
Preview for PDF files is workin now for binary fields:
![image](https://github.com/dotCMS/core/assets/2894221/df17e106-0792-43df-a365-8a055aeb3c8f)
