### ISSUE TITLE
UI: We lost any way to download or get the URL of an asset

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28115]
### Task

When we update the binary field, we lost the "information" button that had paths and such that you could copy and paste for using the asset elsewhere.  As it stands now, it is practically impossible to find the right path for an asset and makes them impossible to share or reference.

To test, login to demo and take this asset:

https://demo.dotcms.com/dotAdmin/#/c/site-browser/1cba5ca1-b91d-4bd1-ba91-a078157be85d

Try to get the url to cut and paste any reference this as an `img` tag  in some html.
 

![Screenshot 2024-03-29 at 10 48 42 PM](https://github.com/dotCMS/core/assets/934364/0a3ab6d9-2443-4b9c-9e21-68c0d8253e76)

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by fmontes** [comment]
We need to show this: 

<img width="472" alt="image" src="https://github.com/dotCMS/core/assets/751424/60d1ec18-a8b6-4e7e-832f-eea19de67ee3">

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED
- Docker Image: `trunk_c245efd`

Even though the new Information button is working as expected, the `Edit` button has disappeared.

**Comment by rjvelazco** [comment]
Here: https://github.com/dotCMS/core/pull/28307 @jcastro-dotcms

**Comment by fmontes** [comment]
![Image](https://github.com/dotCMS/core/assets/751424/febe9785-2144-4efb-ae41-f27bfcdc17c9)

Text based files should not have "sizing"

**Comment by rjvelazco** [comment]
**Here:** https://github.com/dotCMS/core/pull/28309 @fmontes

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_06309e2`

The information dialog is back again, as well as the `Edit` button which displays either the Image Editor or the Text Editor. Additionally, as @fmontes stated, text files are not displaying the non-existing dimension data anymore.

**Comment by bryanboza** [comment]
ok, now we got the information button to see all the links, but we have an issue with it: 
Attached a video explaining the problem: 

https://github.com/dotCMS/core/assets/2641437/e4f1d21b-d971-424c-88c9-d07b342990f6

Basically we need to update the generating information every time you click on this button.

**Comment by rjvelazco** [comment]
@bryanboza The old version has the same `issue`.

This `issue` is because the backend not returning the new `contentlet` when publishing. We need to create a way to update the fields once saved (This behavior does not only happens in the binary field)

@fmontes @wezell Do we want it to handle this in this ticket?

### Old Binary Field Behavior

https://github.com/dotCMS/core/assets/72418962/ffa2a764-7c19-4f68-8b6e-b53d55476e99
