### ISSUE TITLE
Spike: Allow Menu Items in Root Folder

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#28131]
## Problem
As a content architect, I want to be able to create a menu item at the top level of the dotCMS navigation tree.

This issue is a spike to estimate effort to implement this enhancement request.

## Related Issue
https://github.com/dotCMS/core/issues/27824

**Comment by erickgonzalez** [comment]
@john-thomas-dotcms is this related to this one https://github.com/dotCMS/core/issues/27824 ??

**Comment by john-thomas-dotcms** [comment]
Yes @erickgonzalez it's related to that one.  This is a spike to estimate how much of a lift that card would be.  Github just hung on me before I could finish typing the description and setting the labels.

**Comment by dsilvam** [comment]
Making this happen without any migration to REST but by modifying the EditLinkAction, PublishFactory and the likes is probably a 5 or 8
