### ISSUE TITLE
Vanity URLs encode question marks

### ISSUE THREAD

**Issue by wangweiyi722** [dotCMS/core#28138]
### Problem Statement

When performing a redirect of a URL containing a query parameter, the "?" gets encoded as "%3F" in the destination URL, which causes the query parameter to get lost

### Steps to Reproduce

Set up a page that with CMS Anonymous removed from accessing it. This means that it is a front-end protected page

Make a vanity URL with the following fields
URI: /dotCMS/login?([A-Za-z0-9]+)
Action: 302
Forward to: /redirect?$1

Set up a page to receive the redirect.

Navigate to the front-end protected page.
This will trigger a first redirect to /dotCMS/login?referrer=_theOriginalUrl_
This will then trigger the second redirect from the vanity URL.
You will notice in the URL bar and in the headers for this request that the ? gets encoded as "%3F", and the redirect to the page will fail.

### Acceptance Criteria

Have dotCMS stop encoding the destination URLs

### dotCMS Version

23.01.13

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115649

**Comment by freddyDOTCMS** [comment]
Unable to reproduce using the latest on master

**Comment by josemejias11** [comment]
**QA Comment**

I was unable to reproduce this issue using the latest snapshot in master **trunk_8348dfb**
