### ISSUE TITLE
CLI: Case Sensitivity Issue with "direction" Parameter in CLI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28143]
### Problem Statement

In the dotCMS Command Line Interface (CLI), there is an issue where the "direction" parameter is case sensitive. This inconsistency causes inconvenience for users, especially when specifying sorting direction, as they may unintentionally use incorrect capitalization and encounter unexpected behavior.
![image](https://github.com/dotCMS/core/assets/2641437/d2ab3042-3d99-4bff-9c93-394c961e6fe4)

![image](https://github.com/dotCMS/core/assets/2641437/40ca72cc-703d-40b6-b7f0-1f2074199c48)

### Steps to Reproduce

- Access the dotCMS Command Line Interface (CLI) using appropriate credentials.
- Execute a command that includes the "direction" parameter with different capitalization (e.g., "asc", "ASC", "desc", "DESC") to specify sorting direction.
- Observe that the CLI does not recognize the parameter if the capitalization does not match the expected format.

### Acceptance Criteria

- **Case Insensitivity:** Enhance the dotCMS CLI to make the "direction" parameter case insensitive, allowing users to specify sorting direction regardless of capitalization (e.g., "asc", "ASC", "desc", "DESC").
- **Consistent Parameter Recognition:** Ensure that the CLI accurately recognizes and interprets the "direction" parameter regardless of capitalization, maintaining consistent behavior across different commands.
- **Documentation Update:** Update the CLI documentation to inform users about the case insensitivity of the "direction" parameter and how to use it effectively.

### dotCMS Version

Tested on master // lastest CLI version 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on `@dotcms/dotcli@rc` `NPM` package: [`dotCLI 1.0.0-SNAPSHOT`]

### Video

https://github.com/dotCMS/core/assets/72418962/5b6a192c-d339-4766-b37b-fc8fb2ee6a8b

**Comment by rjvelazco** [comment]
## Note for QA

The `@dotcms/dotcli` needs to be updated. We use the `@dotcms/dotcli@rc` for `IQA` testing.

P.S.: You can ask @dcolina to update the `@dotcms/dotcli` packaged

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk and now this is working as expected 

![Image](https://github.com/dotCMS/core/assets/2641437/70d9dc9e-7b97-4a85-8dbd-3396b50dd913)
