### ISSUE TITLE
Edit Page V2: Edit Contentlet Button Spacing Issue

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28155]
### Parent
#27546 

### Problem Statement
Users are experiencing an issue where the spacing between the buttons in the edit contentlet interface is inconsistent and off, making it difficult to navigate and use the buttons effectively.

### Steps to Reproduce
<img width="1785" alt="image" src="https://github.com/dotCMS/core/assets/751424/21820fa5-dddd-4b95-b89e-7f44ba33754b">

<img width="322" alt="image" src="https://github.com/dotCMS/core/assets/751424/36b73ce1-7df5-4c35-9c42-c519ce0c8b8b">

```[tasklist]
### Acceptance Criteria
- [ ] The spacing between the buttons in the edit contentlet should be equal and consistent.
- [ ] The add button should align to the left when no spacing.
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
- QA should verify that the spacing between the buttons is consistent across different browsers and screen sizes.
- In the meantime, users can try zooming in or out on the browser to see if it affects the spacing between the buttons.

**Comment by fmontes** [comment]
We still have this issue:

<img width="322" alt="image" src="https://github.com/dotCMS/core/assets/751424/36b73ce1-7df5-4c35-9c42-c519ce0c8b8b">

We're doing a redesign in the next 90.

**Comment by bryanboza** [comment]
Since we will redesign this, we can close this card for now
