### ISSUE TITLE
Edit Contentlet: Expose AChecker Class to an `endpoint`

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28156]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

We have an `ACheckerDWR` Java class that enables us to check the accessibility of content. We must expose the class methods to an endpoint to use it in Angular. [AcheckerDRW.java](https://github.com/dotCMS/core/blob/master/dotCMS/src/enterprise/java/com/dotcms/enterprise/achecker/tinymce/ACheckerDWR.java)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Three methods need to be exposed in the API and should work as they currently do in 'dwr'.

- [getListaGudelines](https://github.com/dotCMS/core/blob/74dd086997bf5fee07a0326e997524906dbd7850/dotCMS/src/enterprise/java/com/dotcms/enterprise/achecker/tinymce/ACheckerDWR.java#L66)
- [getSupportedGudelines](https://github.com/dotCMS/core/blob/74dd086997bf5fee07a0326e997524906dbd7850/dotCMS/src/enterprise/java/com/dotcms/enterprise/achecker/tinymce/ACheckerDWR.java#L81)
- [validate](https://github.com/dotCMS/core/blob/74dd086997bf5fee07a0326e997524906dbd7850/dotCMS/src/enterprise/java/com/dotcms/enterprise/achecker/tinymce/ACheckerDWR.java#L93)

**Comment by dsilvam** [comment]
Passed Internal QA: 
* Endpoints available and working as expected
* Postman reviewed

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_7f140fe**, Docker, macOS 14.5, FF v126.0.1
