### ISSUE TITLE
Refresh content search screen upon AI content generation via workflow actionlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28168]
### Parent Issue

https://github.com/dotCMS/core/issues/27835

### Problem Statement

When the workflow actionlet "AI Content Prompt" is used to autofill fields of a contentlet, there's the need of a manual refresh of the content search screen to reflect the modifications done by the AI actionlet. 

This refresh needs to happen automatically upon modifications of the contentlet by the AI actionlet. 

### Steps to Reproduce

1. Create a a new content type named "AI generated" with a "title" and a "body" fields of types "text" and "textarea" respectively. 
2. Go to Schema->Workflows
3. Click on System Workflow
4. Edit the "Save" action
5. Add the "AI Content Prompt" sub-action and once the popup dialog is shown include the following for the input named "The prompt that will be sent to the AI":
"We need an attractive search result in Google. Return a json object that includes the fields "title" for a meta title of less than 55 characters and "body" for the meta description of less than 300 characters using this content:\n\n$dotContentMap.title\n\n"
6. Click "Save"
7. Go to Content Search and create a new content of type "AI Generated" create in 1, fill the title with "Short but nice text about dotCMS" and hit "Save"
8. Close the dialog.

Issue is that you need to refresh the screen to see the generation made by the AI actionlet. 

https://github.com/dotCMS/core/assets/1576794/bda78e24-ac4d-4b79-b5b9-ddeb7b09e15b

### Acceptance Criteria

Screen refreshing happening automatically upon AI generation

### dotCMS Version

master/24.04.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Passed Internal QA: No page refresh is needed to see the update made to the content with the generation from AI. 

1. Before updating
![Image](https://github.com/dotCMS/core/assets/1576794/3f4e6193-9e78-4103-a7a7-07e8d0742417)

2. After updating without page refresh
![Image](https://github.com/dotCMS/core/assets/1576794/25353741-07c5-4a8e-81c9-a12edf29e553)

Inside the content search editor 
![Image](https://github.com/dotCMS/core/assets/1576794/8c767a52-fef4-42be-9aa8-54a3d6cbafa7)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_c98dafc**, Docker, macOS 14.5, FF v126.0.1
