### ISSUE TITLE
website viewtool doesn't return subfolder for root

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28166]
### Problem Statement

website viewtool to get the first tier sub-folder using root ('/') it always returns an empty list.

### Steps to Reproduce

```
#set($f= $website.getFolder('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))

#set($ff= $website.getSubFolders($f))

$ff // here empty list

#set($f= $website.getSubFolders('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))

$f // here empty list as well
```

### Acceptance Criteria

It should return all first-tier subfolders that live under root.

### dotCMS Version

23.*, 24.* - 24.04.05

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115683

The workaround would be to use REST API to get first-tier subfolders, then use website viewtool.

```
#set($headers = $contents.getEmptyMap())
#set($discard = $headers.put("Content-Type", "application/json"))
#set($discard = $headers.put("Authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOExYjEiLCJlQys7DmmpXsVVGBWHzcVtpaIdvwG5eefQ"))
#set($data = '{
    "path":"//demo.dotcms.com/"
}')
#set($results = $json.post("https://demo.dotcms.com/api/v1/folder/byPath", $headers, $data))

#foreach ($e in $results.entity)

$e.path

#end
```

**Comment by dsolistorres** [comment]
The behavior is expected in the first case:
```
#set($f= $website.getFolder('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))
#set($ff= $website.getSubFolders($f))
$ff // here empty list
```
dotCMS by design doesn't return a different root folder for every site, it only uses one system folder that is the one root folder on the system, and it belong to the System Host. So this line:
```
#set($f= $website.getFolder('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))
```
Returns the system folder, and this other line:
```
#set($ff= $website.getSubFolders($f))
```
Returns an empty list of sub folders for the system folder, as expected.

On the other hand, for the second case, it is a bug because this code should return the sub folder list under the host root path:
```
#set($f= $website.getSubFolders('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))
$f // here empty list as well
```

**Comment by gortiz-dotcms** [comment]
### **Passed internal QA**

The second case that was a bug is returning the correct sub folder list 

<img width="1499" alt="screenshot" src="https://github.com/user-attachments/assets/3e940dde-8187-4b36-8002-da1614cd2333">

<img width="466" alt="screenshot2" src="https://github.com/user-attachments/assets/a805126b-e689-4baa-bca0-4705310134ca">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9af96d6**, Docker, macOS 14.5, FF v126.0.1

```velocity-template-language
#set($f= $website.getFolder('/', '48190c8c-42c4-46af-8d1a-0cd5db894797'))
$f
``` 

```velocity-template-language
com.dotmarketing.portlets.folders.model.Folder@67202dd2[
    identifier=bc9a1d37-dd2d-4d49-a29d-0c9be740bfaf,
    name=system folder,
    sortOrder=0,
    showOnMenu=false,
    hostId=SYSTEM_HOST,
    type=folder,
    title=System folder,
    filesMasks=,
    defaultFileType=33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d,
    modDate=2017-03-07 18:25:58.116,
    owner=system,
    iDate=2009-10-08 20:27:18.0,
    inode=SYSTEM_FOLDER,
    path=/
]
```
