### ISSUE TITLE
System objects should not be push published

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28173]
### Problem Statement

When "push published" the SYSTEM_HOST getting push published along with content. This is causing some headaches regarding dependency chaining. If it's included in a page it chains to every content type on every site, which means every workflow etc. So the "system" object should not be push published ever, as they should exist in any dotCMS environment.

### Steps to Reproduce

Create a bundle Including a folder and some individual vtl files after that review dependencies in Manifest file. The Manifest file will contain that system container of all items from default like (/workflows, etc).

### Acceptance Criteria

System objects should exist by default in any environment and not be push-published.

### dotCMS Version

23.*, 24.04.05

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115819

https://dotcms.slack.com/archives/G01N0AU1NUC/p1712600974664109

**Comment by dsilvam** [comment]
Passed IQA.
Steps:
* Added a new template with an instance of "System Container". Important: remove the existing "System Container" and add it again. 
* Create a page using this new template
* Add the page to a bundle
* Download the bundle 

Checks performed: 
* Open the manifest.csv and check that only the "Page" content type is there 
* Open the manifest.csv and check that the "System Container" is excluded by "Excluded System Folder/Host/Container/Template"

**Comment by freddyDOTCMS** [comment]
PR https://github.com/dotCMS/core/pull/28370

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_318564e**, Docker, macOS 13.0, FF v124.0.2
