### ISSUE TITLE
UVE: Dot Wizard Component is rendering behind PrimeNG Dialog

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28177]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Problem Statement

When opening the `dot-wizard` component inside the edit content while editing a piece of content inside the Visual Editor. The `dot-wizard` is rendered behind the edit content and the user is not able to access the recently opened dialog.

This is related to PrimeNG updating the `z-index` of their `modal` components to maintain them at the top of the screen and the `dot-wizard` using the `dot-dialog` component which is a modal component created by us and therefore works with a fixed `z-index` and is not getting in sync with the primeNG changes.

### Steps to Reproduce

1. Go to the new Visual Editor
2. Hit the edit button in a piece of content
3. Trigger a workflow action that requires the `dot-wizard` (Move, comment and assign or Push Publish)
4. Wait for it complete 
5. Close the edit content
6. Hit again the edit button in a piece of content
7. Try to open the `dot-wizard` as in step 3
8. See the error.

## Screenshot

https://github.com/dotCMS/core/assets/63567962/ca1b2276-e8ce-4beb-878f-5ec25de69e12

### Acceptance Criteria

We should be able to see a dialog that helps us trigger the selected workflow action in a consistent way.

### dotCMS Version

master - latest

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

This issue was found in the solution of this [PR](https://github.com/dotCMS/core/pull/28159), but is not related to the actual implementation.

It's an old bug that none found or reported yet.

### Assumptions & Initiation Needs

- We should be able to enter to the new Visual Editor
- We should be able to trigger Workflow Actions in the new Visual Editor

### Quality Assurance Notes & Workarounds

You can reload the browser to access the `dot-wizard` but is not a good experience for the users to reload after triggering a workflow action.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/dotcms:trunk_ d670af6`]
- Server: [QA Server](https://dotcms-qa-master.dotcms.site/)

### Video

Uploading iqa-28177-uve-dot-wizard-component-is-rendering-behind-primeng-dialog.mov…
