### ISSUE TITLE
Make Workflow Selection Mandatory in Import Content Job

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#28171]
### User Story

Make Workflow Selection Mandatory in the Import Content Job

When the content type has a custom workflow,
It is unsure what action is performed while proceeding without selecting the workflow.

This is an issue with one of the customer
However, this is not being reproducible in the local environment

They don't see a new inode being published while importing content this way.

### Acceptance Criteria

Review the code.
Make the workflow action selection mandate to avoid this scenario

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/115481

**Comment by dsolistorres** [comment]
Internal QA approved:
Now the workflow action selection is mandatory on the import content screen:
![image](https://github.com/dotCMS/core/assets/2894221/0ce493c0-8e21-4f4e-9c68-485a6b482778)
