### ISSUE TITLE
Edit Content: Expose Date and User Information in Content API Response

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28183]
### Parent
#25445 

### User Story
As a developer, I want to be able to access the creation, update, and publish date and user information of a contentlet in the content API response, so I can track the history of the content.

Currently, we have:

- `modUser`: user id
- `modUserName`: Full name
- `owner`: creator user id
- `modDate`: not sure what date this is
- `publishDate`: publish date

### Acceptance Criteria

```[tasklist]
#### We need to add
- [x] `ownerName`: Full name of the user who created the contentlet
- [x] `creationDate`: Date when the content was created
- [x] `publishUser`: ID of the user who published the content last time
- [x] `publishUserName`: full name of the user who published the content last time
- [x] We need this in all the endpoints, es, lucene, graphql, page api, etc.
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - High

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The backend system should be able to capture and store the date and user information for contentlet actions.
- API documentation should be updated to reflect the new properties in the response.

### Quality Assurance Notes & Workarounds
- QA should verify that the date and user information displayed in the API response matches the actual history of

**Comment by jcastro-dotcms** [comment]
Postman Tests are available in the following locations:
* `Content Resource / Checking JSON Attributes`
* `ContentResourceV1 / Checking JSON Attributes`
* `GraphQL / Page API / Checking Content Audit Attributes`
* `Page API - [aapi/v1/page] / Checking JSON Attributes`

**Comment by zJaaal** [comment]
# IQA Passed 

Tested on the Postman tests indicated by @jcastro-dotcms  and also Lucene Query from the Content Search and all cases includes the required properties.

Docker Image: `[dotcms/dotcms:trunk_a481a77]`

**Comment by bryanboza** [comment]
Fixed, refactoring for the postman test in all the related resources applied here: 
- #28647 
- #28667 
- #28675
