### ISSUE TITLE
Remove the map, imap, mapEntries methods from CollectionUtils

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28192]
### Problem Statement

An issue with the CollectionUtils implementation is related to the methods  map, imap, mapEntries, that uses generics.
These methods are already covered native on Java 11, so the idea would be replace them

### Steps to Reproduce

Nothing to reproduce, just refactor/replacement

### Acceptance Criteria

The  map, imap, mapEntries methods can be removed from the CollectionUtils

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

Does not need QA

**Comment by fmontes** [comment]
This required a general smoke tests.

**Comment by bryanboza** [comment]
Fixed, after this huge change, we made a smoke testing over the principal portlets and features and seems this is working as expected. Tested on the last trunk branch //  docker // FF
