### ISSUE TITLE
Edit Page V2: Bring back tinymce inline editing to the new page editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28196]
### Parent
#27546 

### Task description
As a dotCMS user, I want to be able to inline edit the page in the new page editor without changing anything in my code. This feature was available in the previous version, and we need to support our previous API to ensure a seamless transition for users.

```[tasklist]
### Acceptance Criteria
- [ ] Users should be able to inline edit the page without changing anything in their code.
- [ ] The inline editing feature should be consistent with the previous version and should not cause any disruptions in the user's workflow.
```

### External Links
N/A

### Assumptions & Initiation Needs
This task doesn't include block editor inline editing, that will be in another task

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/assets/751424/14b206a7-9897-4cf7-84bd-427e286fc1a9

**Comment by rjvelazco** [comment]
### Falid Internal QA

- Tested on Docker: [`dotcms/dotcms:docker`]

1. Autosave is not working
2. Missing `editpage.content.update.success` & `editpage.content.update.error` messages keys.

### Video

https://github.com/dotCMS/core/assets/72418962/c4220673-bc25-4acd-8880-cbfd957fe67d

**Comment by rjvelazco** [comment]
### Fail Internal QA

- Tested on Docker: [`dotcms/trunk:_6947043`]

### Steps to Reproduce

1. Go to the new Edit Page.
2. Add a Rich Text or any `contenttype` with a WYSIWYG.
3. Edit the WYSIWYG field by inline editing.
4. Click on the `edit` button [The one with the pencil icon].
5. See the error.

The modal is being opened with an old `contentlet version.

### Video

https://github.com/dotCMS/core/assets/72418962/e9dc1d02-9c0d-43c9-8a72-588878cd1691

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_cbce59a**, Docker, macOS 13.0, FF v124.0.2
