### ISSUE TITLE
UVE: Bring back inline editing for block editor fields

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28198]
### Parent
#27546 

### Task description
As a web content editor using dotCMS, I want to have the inline editing feature available in the new editor, so that I can easily make quick edits to content without having to switch to the code view.

Wait for #28196

https://github.com/dotCMS/core/assets/751424/1031f189-37ee-4aba-b2b1-eb8030fd46f0

### Acceptance Criteria
1. The inline editing feature is successfully integrated into the new editor.
2. Users can seamlessly edit content inline without any issues.
3. The functionality works the same as it did in the old editor.
4. Users are not forced to update their code when using the inline editing feature.

### External Links
- Slack conversation: #dotCMS-development
- Support ticket: #12345

### Assumptions & Initiation Needs
- The new editor interface has the capability to support the inline editing feature.
- Users are familiar with how the inline editing feature worked in the old editor.
- A thorough testing phase will be conducted to ensure the feature works as expected.

### Quality Assurance Notes & Workarounds
- QA team should test the feature extensively to ensure it works seamlessly.
- Any issues or bugs encountered during testing should be documented and addressed before release.

### Sub-Tasks & Estimates
1. Research and evaluate the feasibility of bringing back inline editing feature

**Comment by rjvelazco** [comment]
@fmontes Should this work in Headless? Or are we going to handle that in another ticket?

**P.S.:** The `WYSIWYG` is not working in headless [https://github.com/dotCMS/core/issues/28196]

**Comment by rjvelazco** [comment]
This ticket will cover traditional pages. The Block Editor's inline editing implementation for Headless will be covered in this ticket. https://github.com/dotCMS/core/issues/30607

**Comment by zJaaal** [comment]
## IQA Findings 

I want to leave the findings before we determinate if it either passed or not. 

DotCMS Docker Image: `[dotcms/dotcms:trunk_ac4a771]`
Starter: `20230712`


## Failing to edit contentlet via workflow actions

https://github.com/user-attachments/assets/309d76d4-268e-42c0-ae24-6af08fa60a00

## Workaround to make it work

https://github.com/user-attachments/assets/ce2242d9-02fc-4fbd-aab2-509d9dba74fa

Maybe we should pass this and create a ticket for this.

cc: @rjvelazco @nollymar @fmontes

**Comment by rjvelazco** [comment]
I discussed this issue with @nollymar, but she could not reproduce it; we thought it was due to my local environment.

It appears there is an issue with the `/api/v1/workflow/actions/default/fire/{systemAction}` endpoint and its relationships. In my opinion, it should be addressed as a separate ticket. It's more related to the endpoint rather than the Inline Editing

**Comment by bryanboza** [comment]
we can pass this for now since it is working for single contents via the API
