### ISSUE TITLE
Edit Contentlet: Redirect to the correct edit contentlet from the page portlet

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28200]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Problem Statement

Users with the deprecated feature flag `CONTENT_EDITOR2_CONTENT_TYPE="*"` will now be redirected to the new content editor regardless of whether it is enabled for them or not, via the page portlet.

https://github.com/dotCMS/core/assets/72418962/8847c2ee-089d-4240-9b35-cbf349bbd9fc

### Steps to Reproduce

1. Go to the `Page` portlet.
2. Click on the contextual menu [&#8942;].
3. Click on `edit`.
4. See the error.

### Note:

You must have these Feature flags enabled:

- `"CONTENT_EDITOR2_CONTENT_TYPE": "*"` [Deprecated]
- `"CONTENT_EDITOR2_ENABLED": true`

### Acceptance Criteria

Depending on whether a user has the new or old edit content enabled for the `contentType`, they should be directed to the correct edit content page.

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9515870**, Docker, macOS 13.0, FF v124.0.2

Only by enabling the new Edit mode within the CT, the new edit mode shows on the Edit view
<img width="1280" alt="Screenshot 2024-04-24 at 1 31 54 PM" src="https://github.com/dotCMS/core/assets/129882031/c4a185c4-0edc-4432-abe4-83df954ed048">
