### ISSUE TITLE
AI Content Block inserts rich content as a single paragraph

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28201]
### Parent Issue

#27456

### Problem Statement

When you use dotAI to generate content and click insert, it inserts the content as a single paragraph content block.  This means that if you try to style it (say, change a heading to an h1) it styles the whole content block as h1.

This pretty much makes the insert button useless.

The AI tool should instead insert the content block like it would when content is cut an pasted into the block and let the blockeditor parse the incoming content into blocks so it can be edited as normal content.

### Steps to Reproduce

1. Use AI to Generate an article - "Write a blog on the 5 best ways to experience Costa Rica's natural beauty"
2. insert that article into the block editor
3. try to style one of the headers into an H1 - the whole blog gets styled as an h1
4. Save an publish the content and then hit the API - you can see there is only 1 paragraph block in the block editor field rather than the 100's there should be for normal text editing.

You can also generate an article and cut and paste it into the block editor.   This works as expected.  If you save and publish, you will see block editor's json value has properly parsed the text.

# Wrong:

![Screenshot 2024-04-11 at 10 22 18 AM](https://github.com/dotCMS/core/assets/934364/cae39ced-bd5a-4f9d-afdc-3f3f8ab60022)

# Right

![Screenshot 2024-04-11 at 11 28 10 AM](https://github.com/dotCMS/core/assets/934364/5cae24d3-873d-4487-857e-5ab4af844da9)

### Acceptance Criteria

Make sure that when we insert a text block that it gets parsed by the block editor first

### dotCMS Version

24.04.05

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Generated text from AI inserted as a different block per paragraph.


https://github.com/dotCMS/core/assets/1576794/30a7ce52-de12-4641-9bc3-f88b41157c2b

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_c59b161**, Docker, macOS 13.0, FF v124.0.2

**Comment by erickgonzalez** [comment]
23.01 LTS doesn't have AI.

**Comment by erickgonzalez** [comment]
We included this in 23.10 LTS, but it isn't working. Something else is probably missing since a major refactoring of the AI code was done.
