### ISSUE TITLE
Change Open AI Chat classes to make it injectable and add unit tests

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#28209]
### User Story
As a Java developer, I want to refactor OpenAI classes to make their dependencies injectable so that they can be easily tested.

### Acceptance Criteria
1. Identify and refactor classes within the OpenAI codebase to use dependency injection.
2. Ensure that all dependencies required by OpenAI classes are injected via constructor or setter methods.
3. Write unit tests to verify the functionality of the refactored classes.

### dotCMS Version
master

### Proposed Objective
Integration

### Proposed Priority
Priority 2 - Important

### External Links
- Slack Conversations: [Link to relevant Slack channel]
- GitHub Issue: [Link to GitHub issue for tracking progress]

### Assumptions & Initiation Needs
- Access to OpenAI codebase for refactoring.
- Knowledge of dependency injection patterns and practices.
- Necessary permissions and tools to push changes to the OpenAI repository.

### Quality Assurance Notes & Workarounds
- Ensure unit tests cover all refactored classes and verify their behavior.
- Review and validate changes with the development team before merging.

### Sub-Tasks & Estimates
1. Identify classes requiring refactoring - 2 hours
2. Implement dependency injection - 8 hours
3. Write unit tests for refactored classes - 4 hours

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/28267/files

**Comment by john-thomas-dotcms** [comment]
This was completed, it just didn't get closed at the time
