### ISSUE TITLE
Implement Copy to Clipboard Button with Tooltip in Textarea.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#28234]
### User Story

As a user of the Dotcms platform, I want the UI details to adhere closely to Dotcms patterns for a consistent and intuitive user experience. To achieve this, we need to implement a "Copy to Clipboard" feature for text areas. This feature should provide users with a convenient way to copy text from these areas with minimal effort, enhancing usability and productivity.

### Acceptance Criteria

- A copy to the clipboard button must be added to all text areas in the modals of AI image ( revised prompt ) and content generatión ( generated content ).
- The button must use the p-button component of PrimeNG.
- When the user clicks the copy button associated with a text area, the text within that area should be copied to the clipboard.
- Upon successful copying, a PrimeNG tooltip should be displayed for one second with the text "Copied".

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Passed Internal QA: Both AI Content and AI Image have the option to copy either the generated text or the generated image description to the clipboard. This then can be used in different fields of the content, including the block editor itself.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_c3f6242**, Docker, macOS 13.0, FF v124.0.2

Coy to clipboard icon is getting overlap by the generated text, we should reposition the icon or make the text set all scroll down by default (not recommended) so the icon and the text do not overlap
<img width="1097" alt="Screenshot 2024-05-09 at 4 13 44 PM" src="https://github.com/dotCMS/core/assets/129882031/946f02ba-60b0-42d1-9a94-8f904492f59d">

**Comment by dsilvam** [comment]
Passed Internal QA. Copy button doing its function and not overlapping with the text. Tested both for AI Image and AI Content blocks. 



![Image](https://github.com/dotCMS/core/assets/1576794/34beaac2-43ef-42f9-8cd3-ee66bfd0accb)



![Image](https://github.com/dotCMS/core/assets/1576794/20e5c086-0c89-42b2-bebf-f9570c447df0)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_aaa6d05**, Docker, macOS 13.0, FF v124.0.2
