### ISSUE TITLE
spike(performance): test short lived permission cache

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28230]
### Problem

With large content pulls and limited users, this method can consume a lot of CPU time.  The reason for this is that EVERY content pull in dotCMS is filtered through permissions, which are both hierarchical and recursive.  For example, when rendering a front end page in dotCMS

Here is the ticket for reference:
https://dotcms.zendesk.com/agent/tickets/115552

The idea is that a short lived cache on the lookup `doesUserHavePermission` can improve performance.

**Comment by erickgonzalez** [comment]
Not for 23.01 LTS
