### ISSUE TITLE
Orphan running experiments breaking other API calls

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28238]
### Problem Statement

If there's a running orphan experiment, which happens if the parent page is deleted, the api call `api/v1/experiments/isUserIncluded` fails.

### Steps to Reproduce

1. Create a page
2. Create and start an experiment for the page
3. Delete the page
4. Hit the endpoint `{{serverURL}}/api/v1/experiments/isUserIncluded`

It will return a 400 response with the message 
```
{
    "message": "Contentlet is null"
}
```

### Acceptance Criteria

- [ ] Leaving an running experiment orphan should not make the api call to `api/v1/experiments/isUserIncluded` fail. It needs to work as normal but exclude the orphan running experiment.

- [ ] Postman test

### dotCMS Version

23.10 LTS

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a1b916e**, Docker, macOS 13.0, FF v124.0.2
