### ISSUE TITLE
Store file extensions and file names in lowercase in DB and FS

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#2824]
There are issues with resizing here and general retrieving of files

We use to handle this with the older files and we currently handle with folders. 

We have File Name (text3) and Titile (text2)  Title should maintain casing while filename should be a URL friendly name. 

We do NOT need to upgrade people's data here. We need to handle for storing moving forward. We also need to force lowercase on the extension. 

This should happen in JS in the UI and in the ContentletAPI

**Comment by wezell** [comment]
dupe
