### ISSUE TITLE
CLI: Create documentation for testing on fork

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#28255]
As a member of the development team, I need to create detailed documentation on how to run tests on forks of our main repository using GitHub Actions. This documentation should provide clear step-by-step instructions for setting up and running automated tests in a fork environment, ensuring that proposed changes by external contributors are thoroughly evaluated before being merged into the main repository. The documentation should include information on configuring and customizing GitHub Actions workflows specifically designed for testing on forks, as well as any additional setup required to ensure smooth execution of tests in this context. The ultimate goal is to ensure the integrity and quality of the source code even when accepting external contributions to the project.

**Comment by nollymar** [comment]
[ForkDocumentation .pdf](https://github.com/dotCMS/core/files/15241456/ForkDocumentation.pdf)
