### ISSUE TITLE
CLI: Not rely on an id when specifying a CT detail page

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28262]
when specifying a detail page for a url mapped page, a user should be able to specify a path and not rely on an id, e.g. //demo.dotcms.com/blogs/detail-page

**Comment by nollymar** [comment]
**Internal QA:** Needs work 

- [ ] When I set a detail page with an invalid path, it fails with a 500 error 
- [ ] When I set a detail page with an invalid identifier, it doesn't fail and remove the existing detail page if exists

**Comment by nollymar** [comment]
Internal QA: Passed.

The issues reported above were fixed

> * [x]  When I set a detail page with an invalid path, it fails with a 500 error
> * [x]  When I set a detail page with an invalid identifier, it doesn't fail and remove the existing detail page if exists

**Comment by bryanboza** [comment]
Changes needed in the Postman tests:

- Add a validation beyond just returning a 200 status code in the delete and archive requests. It is important to validate that the response JSON is as expected and provides clear feedback.

- Change the authentication to `inherit from parent`

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker // FF
