### ISSUE TITLE
Live View from Edit Page is not possible

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28278]
### Parent Issue

https://github.com/dotCMS/core/issues/25275

### Problem Statement

After the redesign of the Edit Page, the live view tab was removed. As of now, there is no way to access this view. However, the "Open in a new Tab" option opens in Preview Mode.

redesigning

### Steps to Reproduce

STR:
1- Open any page (e.g Index)
2- Click Edit
3- Edit any content but just save (not publish)
4- Click Preview 
5- You can see the changes (Expected)
6- Click over Open in a New Tab
7- You can see the changes (Not Expected)

https://github.com/dotCMS/core/assets/5278970/a515c8f2-5916-4c51-bf22-11c18de6b03e

### Acceptance Criteria

The "Open in a new Tab" option should open in Live Mode.

### dotCMS Version

Agile Releases since 23.08.16.

Not Applies to LTS since Flag was turn on until 

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_9e49acb**, Docker, macOS 13.0, FF v124.0.2

Open in a new tab redirects to the "Welcome" portlet

https://github.com/dotCMS/core/assets/129882031/7c27552f-0d17-4646-9a1c-9ad3d83898e1

**Comment by bryanboza** [comment]
Looking both videos here, the main problem is caused by the new EMA, seems this feature is affecting this functionality and this is not working in the new editor.  In order to reproduce the reported error you need to add your EMA configuration. 
How to configure: 
- Login as admin 
- Go to the apps portlet 
- In the `EMA Next` option add the following configuration 
```
{
  "config": [
    {
      "pattern": ".*",
      "url": "https://nextjs-example-sigma-five.vercel.app"
    }
  ]
}
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_239b434**, Docker, macOS 13.0, FF v124.0.2

Fixed while using the normal edit mode. 
<img width="1294" alt="Screenshot 2024-04-23 at 10 36 29 AM" src="https://github.com/dotCMS/core/assets/129882031/13c1fb9e-6a35-494d-8477-a8c38473ea52">

Issue related while using Edit Mode v2 https://github.com/dotCMS/core/issues/28220
