### ISSUE TITLE
Open in a New Tab in Preview Mode

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28279]
### User Story

As a user, I want to be able to open the Preview Mode in a new tab since it's easier to view the changes applied.

### Acceptance Criteria

Add a link/button to Open in a New Tab in Preview Mode

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
This functionality is in the product as of today; @erickgonzalez which version are you requesting this for and is this still a need?

**Comment by erickgonzalez** [comment]
@prestonso  IIRC, this was a customer request; since it was a new functionality, the customer understands that it won't be backported to their current version. Can you add a video or steps on how this is possible now?

**Comment by prestonso** [comment]
@erickgonzalez Which version, sorry? This is already implemented in the most recent version (Universal Visual Editor).

**Comment by erickgonzalez** [comment]
@prestonso no worries about it, just saw the new preview option. I'll close this request.
