### ISSUE TITLE
Edit Page V2: Unable to Edit Contentlets in Variant

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28281]
### Parent
#27546 

### Problem Statement
Users are unable to edit contentlets in a variant within dotCMS. Clicking the edit button results in an error being thrown in the console.

### Steps to Reproduce
1. Go to https://dotcms-qa-master.dotcms.site
2. Edit the page `/blog/index`
3. Go to the experiment and edit the variant
4. Try to edit a contentlet in the variant
5. See the error.

```[tasklist]
### Acceptance Criteria
- [ ] Contentlets in a variant should be editable
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_6947043**, Docker, macOS 13.0, FF v124.0.2
