### ISSUE TITLE
Reduce Flickering on Page Redirects for Experiment Variants Using PageApi Flags

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28291]
### User Story
As a front-end developer, I need to effectively utilize the flags provided by PageApi to determine if a page is part of an experiment and manage page content before a redirect occurs. This is to eliminate the visual flickering seen when a user lands on a page that requires redirection to an experiment variant.

### Acceptance Criteria
- Utilize the PageApi flags to check if the incoming page has an associated experiment and variant before fully rendering the page.
- Implement pre-fetching or a placeholder mechanism to prevent the initial content from rendering if a redirect to a variant is needed.
- Ensure the solution provides a seamless user experience with no noticeable flicker when navigating to a page involved in an experiment.
- The implemented solution should not adversely affect the page load time or performance.
- Document the approach and any changes made to the handling of page rendering and redirects.

### Proposed Objective
User Experience Improvement, Performance Optimization

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Assumptions & Initiation Needs
Assuming that the current mechanism of handling redirects after the page has begun to load is causing visible flickering, leading to a suboptimal user experience. 

### Quality Assurance Notes & Workarounds
Quality assurance should focus on ensuring that the new mechanism effectively eliminates flickering without introducing new issues such as increased page load times or broken functionality.

**Comment by dsilvam** [comment]
Needs work: A blank page is showing sometimes when a page inside an experiment is assigned to the default/original variant.

**Comment by oidacra** [comment]
Fixed @dsilvam take a look at the Demo Site.

**Comment by dsilvam** [comment]
Note to QA: 

1. Stop any running experiments on the index page on https://dotcms-qa-master.dotcms.site
2. Create a new experiment on index page and add a variant with some changes
3. Set a goal of reaching a certain page that's reachable by clicking from the index page (check menu links on index). Set the goal with "contains" to avoid mismatching. 
4. Start the experiment. 
5. Go to the index page by hitting the url of the SPA https://dotcms-qa-master.dotcms.site on an incognito session
 * When the variant version of the page is shown, register the conversion defined on 3. 
 * When the original version of the page is shown, do not register a conversion
6. Repeat 5 at least 10 times 

- [ ] Make sure it is properly redirecting to the variant by checking the queryParam (?variantName=<variantName>) ~ half of the times
- [ ] Make sure you're getting presented with the original and the variant of the page ~ half of the times
- [ ] Make sure the sessions and conversions are registering by checking the results of the experiment

**Comment by josemejias11** [comment]
**Approved**: Tested on **dotcms-qa-master**, Docker, macOS 13.0, FF v124.0.2
