### ISSUE TITLE
Can't Import Page Assets using the export file

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28306]
### Problem Statement

If you try to use the export tool to export all Page Assets and import it afterward it fails with the following error message `"badType: url"`

### Steps to Reproduce

1- Export Page Asset contentlets using the Export Tool (the one under the 3 dots on the right).
2- Try to import that CSV.
3- Get the error

### Acceptance Criteria

Import should work since it's using the Export file as it is.

Slash should be stripped from the URL when validating.

### dotCMS Version

All LTS versions and Master.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116011

### Assumptions & Initiation Needs

Here is the issue: https://github.com/dotCMS/core/blob/264995dcbab043c0bd01f3fe03c2c4a76724a426/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L8080 it's appending the Slash, and it already comes in the url.

**Comment by gortiz-dotcms** [comment]
Passed Internal QA

No errors

![Image](https://github.com/dotCMS/core/assets/170764530/3a9e3ac1-3aec-40a5-bce8-51001af797cd)

Import made successfully


![Image](https://github.com/dotCMS/core/assets/170764530/20e3fb9f-aa20-4849-8a1a-bdd7f3f4537d)
