### ISSUE TITLE
File Fields Not Showing in EditV2 Mode During New Contentlet Creation

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#28302]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Problem Statement

Users are encountering issues with file fields not functioning correctly when using the EditV2 mode to create new contentlets.

### Steps to Reproduce

1. Switch to EditV2 mode in the application
2. Start the process to create a new contentlet
3. Attempt to upload a file using the designated file field within the contentlet form
4. Observe the file field is not showing as its expected

### Acceptance Criteria

File fields should allow users to upload files seamlessly, and the uploaded files should be displayed appropriately within the contentlet form.

### dotCMS Version

24.3.15

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

<img width="1350" alt="Screenshot 2024-04-19 at 8 52 42 AM" src="https://github.com/dotCMS/core/assets/129882031/dae7510d-97df-4aec-b31a-4e2082aeb00c">
<img width="1350" alt="Screenshot 2024-04-19 at 8 57 34 AM" src="https://github.com/dotCMS/core/assets/129882031/6d44311f-8256-484f-8e49-abc1e988dbab">

**Comment by dsilvam** [comment]
Not yet implemented. Will be implemented in this card https://github.com/dotCMS/core/issues/29691
