### ISSUE TITLE
Updating Osgi UI to remove the OSGIAjax

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28320]
### Task

As an user I want to replace the OSGIAjax calls on the Plugins portlet by the new v1/osgi endpoint

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The OSGIAjax should be removed

**Comment by rjvelazco** [comment]
### Passed Internal QA
 
 - Tested on Docker image:  [`dotcms/dotcms:trunk_c84abae`]
  
### Video


https://github.com/dotCMS/core/assets/72418962/fd9471b9-c858-40e2-a938-be9b9e3d731c

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_98cdf34**, Docker, macOS 13.0, FF v124.0.2
