### ISSUE TITLE
Dependency Update : SnakeYAML for the dotCMS CLI project

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#28325]
### Parent Issue

https://github.com/dotCMS/core/issues/24850

### Task

dotCMS CLI is currently using `org.yaml/snakeyaml 1.30`

Upgrading to version 2.2 will remove all the reported security vulnerabilities.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

SnakeYAML 1.30 is being included as a transitive dependency. As per conversation with @fabrizzio-dotCMS , it's very likely that a major change in the dependency list needs to be done.

**Comment by fabrizzio-dotCMS** [comment]
by upping the quarkus platform version to 2.12.3.Final 

The snakeYML version goes up to 1.32 which is vulnerability-free

However, I was able to upgrade quaks to 2.16.12.Final without any issue.  Beyond this point the build breaks.
