### ISSUE TITLE
NPE error copying sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28339]
### Problem Statement

When you try to make a copy of the demo site, we are getting some NPE errors related to the deterministic IDs API,  this seems that is not affecting the copy of the site, but we need to take care of those. 

LOG: https://gist.github.com/bryanboza/dd64d56cbebd06f33ff33126b5eee49b

### Steps to Reproduce

- Start a fresh instance 
- Login as admin 
- Try to copy the demo site 
- Check your log file 

### Acceptance Criteria

We need to copy the site without any errors. 

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
I think a missing physical asset caused this NPE. 
Looking at the error it comes trying to resolve the asset name of the file titled `template-breadcrumbs.png`

```
 Failed resolving asset name for contentlet with title `template-breadcrumbs.png` and id ``
dotcms-1         | 	at com.dotmarketing.business.DeterministicIdentifierAPIImpl.resolveAssetName(DeterministicIdentifierAPIImpl.java:139) ~[classes/:?]
```
I couldn't reproduce the issue, the file can no longer be found in demo.
However this will always happen if the asset file has been removed. Good thing the NPE does not break the process

**Comment by fabrizzio-dotCMS** [comment]
@bryanboza and @josemejias11 
This starter does not have the file this thing is breaking on `template-breadcrumbs.png`
https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240213/starter-20240213.zip
so my theory stands still. Can you check if that file exists on your installs and if you can open and edit it? 
Cause I believe this NPE is caused because the file exists in the database but isn't part of the starter etc..

**Comment by bryanboza** [comment]
hey @fabrizzio-dotCMS I tested using the same starter (full) and I'm still able to reproduce the issue, I think this is related to some specific file. Not sure if in this case we need to update the starter sites to prevent this...

**Comment by fabrizzio-dotCMS** [comment]
I just tried this using the latest starter that I could find:  20240611 and it seems that any prior reference to the broken file `template-breadcrumbs.png`  has been cleaned.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_45b0c67**, Docker, macOS 14.5, FF v126.0.1
