### ISSUE TITLE
Edit Page V2: Enhance performance in Contentlet Tools

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28331]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Task

Transform `getXYZPosition` functions to optimize DOM Rendening in [Contentlet Tools](https://github.com/dotCMS/core/blob/959776837dd1208e661cf0a1bab5ef43ee0a50c1/core-web/libs/portlets/edit-ema/portlet/src/lib/edit-ema-editor/components/ema-contentlet-tools/ema-contentlet-tools.component.ts)

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

* We should refactor all functions that are triggering in the `HTML`
* Contentlet Tools should work as expected after the refactor

### Assumptions & Initiation Needs

* You understand the impact of triggering functions inside angular templates

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker Image: [`dotcms/trunk_5921e6a`]

### Video

https://github.com/dotCMS/core/assets/72418962/823c32b9-4673-4808-82bb-b1e1d69c8808

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker // FF
