### ISSUE TITLE
Edit Page V2: Page API Depth Parameter Bug

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28332]
### Parent
#27546 

### Problem Statement
When using the Page API in dotCMS, the depth parameter specified in the page contentlet does not match the depth specified in the contentlets added to the page. This inconsistency causes confusion and unexpected results for users trying to retrieve content with specific depth requirements.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/3698c24f-c29f-4b4e-a31a-11cdb7e17e69

```[tasklist]
### Acceptance Criteria
- [ ] The depth parameter specified in the page contentlet should match the depth of all contentlets added to the page.
- [ ] When using the Page API to retrieve content from the page, the depth parameter should be consistent across all contentlets.
```

### External Links
- None

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by jdotcms** [comment]
After a research on it, I think it is working as an expected.

This is the documentation related to the depth:

```
When `depth` param is set to:
     *         0 --> The contentlet object will contain the identifiers of the related contentlets
     *         1 --> The contentlet object will contain the related contentlets
     *         2 --> The contentlet object will contain the related contentlets, which in turn will contain the identifiers of their related contentlets
     *         3 --> The contentlet object will contain the related contentlets, which in turn will contain a list of their related contentlets
```

1. As you can see the depth is a render mode max until 2 levels, but it is not a number for how deeper you want to get the relationships, on the best scenario will get 2 levels of deep. So, there is not something such as deep 4 or so.
2. In the video there is an interesting scenario happening: we have a page with a level1 relationship, and we have also the level1 added as a contentlet on the page layout.

If we see the relationships as a tree we can see something like that for the page relationship
```
page (root node)
    level 1 (child1)
         level 2 (child 2)
              level 3 (child 3)
```

But on the contentlet level 1 added to the page, it is something like
```
    level 1 (root node)
         level 2 (child 1)
              level 3 (child 2)
```

This is the reason the rendering of both levels (one as a content and one as a relationship) will be not equals even using the same depth value parameters. The Page relationship will be always behind the content level1
