### ISSUE TITLE
Binary Field: Information of assets needs be refreshed after any change

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28337]
Related to #28115

We are not refreshing the asset information after you do some change and publish it, you need to close the modal and reopen to see the changes. 
Attached a video explaining the problem: 

https://github.com/dotCMS/core/assets/2641437/e4f1d21b-d971-424c-88c9-d07b342990f6

Basically we need to update the generating information every time you click on this button.

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/28115#issuecomment-2073039999_

**Comment by zJaaal** [comment]
The scope of this ticket covers the JSP side of the Binary Field. We need to make sure this already works on the Angular side otherwise, we should create a ticket for it.

cc: @nollymar @fmontes

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_b535434`]

### Video


https://github.com/user-attachments/assets/2ca618a0-884b-4960-9bed-8f81b62aedd5

**Comment by rjvelazco** [comment]
### Failed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_ c8f8051`]
- Server [dotCMS QA Master](https://dotcms-qa-master.dotcms.site/)

### Steps to Reproduce
1. Go to Content Search
2. Create a new `File` contenttype
3. Add an image
4. Publish
5. See the error. The image disappears

### Video

https://github.com/user-attachments/assets/c2b4d9d9-5058-49aa-a3ec-47695e678b23

**Comment by fmontes** [comment]
This is an edge case difficult to solve with the current implementation of JSP edit content. We don't need to fix this in the old content editor; we can make sure it works in the new content editor. We can close this one, but make sure that @dsilvam and @john-thomas-dotcms know about this so it doesn't happen in the new editor.

**Comment by zJaaal** [comment]
I have sent a revert to leave it as was

**Comment by zJaaal** [comment]
# Note to QA 

After what we decided, just be sure it works as it was before.

**Comment by valentinogiardino** [comment]
### IQA Passed Internal

- Tested on docker image: [dotcms/dotcms:trunk_ 36f72e4]
- After the rollback, it is working as before


https://github.com/user-attachments/assets/7ba7d188-0823-454e-abe7-b73c560aca82

**Comment by bryanboza** [comment]
We don't have a fix here, everything still working in the same way!
