### ISSUE TITLE
Edit Contentlet: Workflow Action Endpoint does not return the `contentlet` metadata

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28338]
### Parent Issue

https://github.com/dotCMS/core/issues/25445
### Task

We must retrieve the binary field `metadata` when executing a workflow action.

- **Endpoint:** `/api/v1/workflow/actions/${workflowActionId}/fire?inode=${contentletInode}&indexPolicy=WAIT_FOR`

#### Current Response

```
{
    "AUTO_ASSIGN_WORKFLOW": false,
    "__icon__": "jpgIcon",
    "archived": false,
    "baseType": "FILEASSET",
    "contentType": "Image",
    "underlyingFileName": "services-2.jpg",
    "url": "/images/pages/12345.jpg",
    "width": 844,
    "working": true
     ...Contentlet
}
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The Workflow Action endpoint should retrieve both the binary field metadata in the `contentlet` information. Our current response is a `contentlet`. We only need to attach the metadata as we do in the Contentlet API.

#### Desire Response

```
{
    "AUTO_ASSIGN_WORKFLOW": false,
    "__icon__": "jpgIcon",
    "archived": false,
    "baseType": "FILEASSET",
    "contentType": "Image",
    "underlyingFileName": "services-2.jpg",
    "url": "/images/pages/12345.jpg",
    "width": 844,
    "working": true
     "Metadata": {
          ...binaryMetadata
     },
     ...Contentlet
}
```

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker image: [`dotcms:trunk_ 3081a8e`]

### Video

https://github.com/dotCMS/core/assets/72418962/9274962f-ef0a-4034-9309-b0f50cb5f351

**Comment by jdotcms** [comment]
PR for postman test: 
https://github.com/dotCMS/core/pull/28778/files

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Postman
