### ISSUE TITLE
Aspect ratio locked on the crop tool

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#28344]
### Problem Statement

- the default values for the crop width and crop height are 150x150, 
- this does not match the aspect ratio for their image
- after one of those 150 values has been changed, then dotCMS is making the other value match the aspect ratio 
- the workaround of manually adjusting the URL is too technical for them; they want a user-oriented solution,  available from the tool
- this was tested in https://dotcms-qa-lts2301.dotcms.site/ and the latest https://dotcms-qa-master.dotcms.site/ and it behaves the same

### Steps to Reproduce

- go to image editing servlet
- use the crop tool and try to change the x and y values 
- video with the demonstration attached

### Acceptance Criteria

- the crop tool should not the aspect ratio
- should be able to set any x and y values as crop values

### dotCMS Version

23.01.13

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116018

**Comment by prestonso** [comment]
@wezell just tested on latest demo version and works. Closing as fixed!
