### ISSUE TITLE
Add Host to the reference tab on Content

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#28365]
### User Story

When content is used on multiple hosts, it would be nice to know not only the pages the content is being referenced by but also the host on which that page lives. 

### Acceptance Criteria

Show the host of the page as a column in the table reference table.
<img width="1429" alt="Screenshot 2024-04-26 at 9 30 41 AM" src="https://github.com/dotCMS/core/assets/1561349/cef3f69a-73b4-44df-8b7c-38a1867372a5">

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by erickgonzalez** [comment]
Passed Internal QA. Now it shows the site

![Image](https://github.com/dotCMS/core/assets/5278970/c78010ff-cf2e-40ab-b9ad-fe399ba98424)

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF 

![Image](https://github.com/dotCMS/core/assets/2641437/ca579b37-dc9c-4445-944b-3d01417c52ee)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_cc8566c**, Docker, macOS 14.5, FF v126.0.1
