### ISSUE TITLE
Uploaded images in another language than the default one do not inherit permissions

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#28366]
### Problem Statement

- when another language than the default one is selected and an image is uploaded from the site browser, it happens two things:
~1. the contentlet that opens has the default language selected~ **Moved to new issue https://github.com/dotCMS/core/issues/28489**
 2. even if the desired language is selected when the image is uploaded, the permissions are not inherited and they have to be set manually
- tests were made on the customer dev environment, prod environment, and on our local instance
- the customer's prod test can be found in the ticket attached to this one

### Steps to Reproduce

- go into the site browser
- change the language to another one than the default
- click on the blue plus sign
- choose _image or file_ 
- choose image -> at this point the contentlet that opens has the language field set to the default language
- change to the desired language (in the contentlet)
- upload an image
- check permissions tab

### Acceptance Criteria

- permissions should be inherited

### dotCMS Version

23.01lts
- the latest version is also affected

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116044

**Comment by erickgonzalez** [comment]
It's working as it should. Now, the permissions tab loads and is inherited. 

![Image](https://github.com/dotCMS/core/assets/5278970/efd23f95-39d9-4fb9-9cca-43f2b821ae9d)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_430f4c7**, Docker, macOS 14.5, FF v126.0.1
