### ISSUE TITLE
Saving a site instead of hitting Save/Activate deactivates the site entirely

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#28362]
### Problem Statement

When you save a currently active Site without hitting Save/Activate, it deactivates the site. This is not clear to the user at all, and the history tab still shows a published version.

### Steps to Reproduce

1. Save a site
2. Try to access the site

### Acceptance Criteria

Either
~1. The Save action should make it clear that the currently published site will be deactivated
2. The history should not show a published version
Or~
The published version should continue to be served and the site must be shown as active.

### dotCMS Version

Master, 23.10, 23.01

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116052
https://dotcms.slack.com/archives/C04UKBYG7SA/p1727116641308499

**Comment by erickgonzalez** [comment]
Working as it should now, when having different live and working versions of a site, the site still renders successfully.

![Screenshot 2024-11-13 at 2 47 46 PM](https://github.com/user-attachments/assets/bb741ab6-0809-4891-bc42-a3b5d9e39013)

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after this fix.
