### ISSUE TITLE
Edit Page V2: UVE Issues

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28372]
### Parent
#27546 

Task for fixing small issues in UVE

- [ ] Unable to drag and drop VTL widgets.  I am getting a message that the container does not accept widgets but widgets are allowed in any container.
![Screenshot 2024-04-29 at 9 58 30 AM](https://github.com/dotCMS/core/assets/934364/2e3984b2-a416-4365-b450-4c9f675e0ece)

**Comment by KevinDavilaDotCMS** [comment]
# PASSED IQA
Tested in Master

Chromiun browser:

https://github.com/dotCMS/core/assets/144152756/0a3f36f6-0e74-4a80-9a38-bf728f34052d

Firefox:


https://github.com/dotCMS/core/assets/144152756/2ca03d72-52b2-4c0a-9ebf-84ffedcfcea2
