### ISSUE TITLE
Edit Page V2: Unable to add content to a container without code in VTL Pages

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28377]
### Parent Issue
TBD

### Problem Statement

When you add a `contentType` to a new container and don't write any code for it and then add the content in the Editor to that container with no code, you will see a blank space and you won't be able to add any content to that container until you add something to the code for that `contentType`. This is only happening in VTL Pages

### Steps to Reproduce

https://github.com/dotCMS/core/assets/63567962/8fcf40a1-9f01-4242-8731-8dc88c421f12

### Acceptance Criteria

* User should be able to add more content to a container even if there is no code for the content inside the container

### dotCMS Version

`trunk-latest`

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

* You understand how the content is created in dotcms
* You understand how the Visual Editor works as a tool

**Comment by zJaaal** [comment]
## IQA Passed 

Now we can add content for containers with no code

Tested on: `[dotcms/dotcms:trunk_b18b2c6]`

## Screenshot

https://github.com/dotCMS/core/assets/63567962/00fc6981-f5e3-440c-8545-ecba20ddfc42

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2ff9668**, Docker, macOS 13.0, FF v124.0.2
