### ISSUE TITLE
Tables do not render correctly when added to containers 

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#28381]
### Problem Statement

When adding a table as part of a container in a template, the table does not render correctly in the edit page of dotCMS. Interacting with the content in the containers of the edit menu also does not work as expected.

### Steps to Reproduce

1. Create a new page for rendering activities
2. Create a container that has an opening <table> tag in the pre loop and a closing </table> tag in the post loop.
3. In the body of the container, add a table row (tr tag) with table data (td tag) to render the title of the activity
4. Add the container to the template for the page
5. Open the page editor and add two activity contentlets into that container, and save the page
6. Go back to the editing page, and you will notice that the title will render outside of the marked area in the editor. There will also be a second striped blue area outside the area of the container. (See attached screenshot)
7. Trying to remove the second contentlet will not remove the content. However removing the first contentlet will end up removing both contentlets.

### Acceptance Criteria

Be able to swap the positions of contentlets added in tables reliably
Be able to delete the contentlets that are added to a table
Render the contentlets within the boundaries of the container in the edit page

### dotCMS Version

24.04.24
5.2.4 <- Customer's version

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CSHTYUR7H/p1714159536805309
https://dotcms.zendesk.com/agent/tickets/115854

**Comment by prestonso** [comment]
@weiyiwang-dotcms is this still an issue? I know this was for a specific customer; are they still facing this even after upgrade?

**Comment by prestonso** [comment]
We've found that tables are closing correctly and we cannot reproduce on latest version. Please reopen if you see this recur in that customer's impl!
