### ISSUE TITLE
Put API usage metrics behind a feature flag

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28386]
### User Story

As a Cloud Engineer / Dev, I want to be able to turn off the API usage metrics by feature flag (env var), so I don't have to keep different versions of the plugin (with and without these metrics) in case of the need of turn the feature off, e.g., errors. 

### Acceptance Criteria

Ability to turn on/off the API usage metrics via feature-flag (env var)

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/48

**Comment by freddyDOTCMS** [comment]
Pass IQA: Work as expected.

Important point if you installed the plugin with the flag disabled.
If you later enabled the flag you need to reinstalled the plugin
