### ISSUE TITLE
Locale Variable Saving Action should publish Content 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28396]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### User Story

Saving should be executed when changes are detected upon leaving the Cell in the Language variables screen table.
This Action should always leave the cotnentlet in published state 

### Acceptance Criteria

This Action should always leave the cotnentlet in published state

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by john-thomas-dotcms** [comment]
We've made the decision to not implement the language variables screen at this time.
