### ISSUE TITLE
Update PP logic to add lang variables as content to bundles

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28395]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### User Story

We need to give users the possibility to add/remove Language Variables to Bundles or Push Publish them. 
The old language keys can be sent for push publishing or passed around in a downloaded bundle therefore we need to support that and remove the current logic that includes Language Keys

### Acceptance Criteria

The user should be able to send Language Variables to Bundles or PP just it can be done on Content-Search 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
Not needed. Already implemented
