### ISSUE TITLE
Locale Variable Delete Action should actually delete the piece of content not archive it. 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28397]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### User Story

Language Variable Delete Action should actually delete the piece of content not archive it.

### Acceptance Criteria

The piece of content should be removed for real.

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by john-thomas-dotcms** [comment]
We've decided not to implement the language variables screen at this time
