### ISSUE TITLE
SDK: Update Next.js example app to handle vanity URLs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28403]
### Parent
#28401

### Task description
As a developer, I need to update the Next.js example app to demonstrate how to handle vanity URLs, allowing for certain URLs to be redirected or forwarded to the appropriate content.

```[tasklist]
### Acceptance Criteria
- [x] The vanity URLs should be redirected or forwarded to the correct content based on the defined logic.
- [x] Add documentation in the README explaining how to vanity URLs worked
```

### External Links
N/A

### Assumptions & Initiation Needs
- I assume that the vanity URLs are defined in the dotCMS starter

### Quality Assurance Notes & Workarounds
- QA should test the functionality of the vanity URLs by trying different URLs and verifying they are redirected correctly.

**Comment by fmontes** [comment]
### IQA:

1. Setup UVE locally and run nextjs locally
2. Create a vanity url
3. Hit the vanity url in localhost:3000/vanity-url
4. Make sure it does the redirect accordingly.

**Comment by bryanboza** [comment]
Fixed, now we are handling vanities without problems 


![Image](https://github.com/dotCMS/core/assets/2641437/52076674-fd63-4bcf-9f0a-36fe70840b85)

Tested on the latest trunk // Docker // FF
