### ISSUE TITLE
Edit Page V2: User cannot move the contentlets when a container is at maximum capacity

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28410]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Problem Statement

When a container is at maximum capacity, the user cannot move any `contentlets` within it.

### Steps to Reproduce

1. Create a new container with `Max Contents` equal to `2`
2. Go to any page
3. Add the container
4. Add 2 `contentlets`
5. Try to move one
7. See the error

### Video

https://github.com/dotCMS/core/assets/72418962/ccaee583-8b3f-46e2-b321-caccf3db9ee9

### Acceptance Criteria

When a container is at maximum capacity, it should allow users to move any `contentlets` within it.

### dotCMS Version

`master`/`trunk`

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by rjvelazco** [comment]
### Fail Internal QA

- Tested on Docker Image: [`dotcms/dotcms:trunk_ b1d9465`]

### Steps to Reproduce:

1. Create a container with a `Max Contents` of `2`
2. Add two of those containers to a page.
3. Fill the first container with 2 `contentlets`
4. Fill the second container with 1 `contentlet`.
5. Move the `contentlet` form the second container to the first one.
6. See the error.

You shouldn't be able to move from one container to another if the container is full.


### Video

https://github.com/dotCMS/core/assets/72418962/ac94d498-0392-468b-afac-6693ffc98777

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_cff69ec**, Docker, macOS 13.0, FF v124.0.2
