### ISSUE TITLE
Can't import Apps from old versions 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28427]
### Problem Statement

Currently when we try to import an App from an old version it throws an error 
```
Caused by: java.io.InvalidClassException: com.dotcms.security.apps.Secret; local class incompatible: stream classdesc serialVersionUID = 7975602366706460873, local class serialVersionUID = 7576154951952060861
```

### Steps to Reproduce

1- Try to import the following app
[googleTranslationApp.export.zip](https://github.com/dotCMS/core/files/15203172/googleTranslationApp.export.zip)

password: testdotcms1234

2- Get the error

### Acceptance Criteria

Apps exported from previous versions should be compatible.

### dotCMS Version

24.04

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by erickgonzalez** [comment]
**WORKAROUND**

This workaround will work when the exported App is coming from dotcms version 24.03.01 or older (works for all LTSs).

Add the following line to the Secret.java file:
```
private static final long serialVersionUID = 7975602366706460873;
```

**Comment by erickgonzalez** [comment]
Only for 24.04 LTS

**Comment by bryanboza** [comment]
Fixed, now we are able to import apps from previous versions, tested on the last trunk and after import apps we are able to use these without any problem.
