### ISSUE TITLE
Split default postman collection into 2

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28423]
### Task

The default postman collection takes an hour to finish while the others take way less than that. 
This task consists in splitting the default postman collection into 2 different ones with similar completion times. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Default postman collection split into two collections with similar completion times.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/29043

**Comment by dsilvam** [comment]
Results of the default collection before and after splitting it:
~68m as one collection 
~38m and ~40m as two separate collections.
