### ISSUE TITLE
Upgrade GraphQL to 17.5

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28420]
### Task

Upgrade GraphQL to 17.5

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Make sure the GraphQL postmans runs ok with the new grapql version

**Comment by fmontes** [comment]
There are some issues with the schema that if I am not mistaken is alreadt reported.

**Comment by bryanboza** [comment]
We can pass this for now, all the test are running without problems, some new cards created to fix related problems
