### ISSUE TITLE
Path traversal in webpack-dev-middleware 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28437]
### Parent Issue

https://github.com/dotCMS/core/issues/28435

### Problem Statement

Path traversal in webpack-dev-middleware 

- [x] https://github.com/dotCMS/core/security/dependabot/353
- [x] https://github.com/dotCMS/core/security/dependabot/351

### Steps to Reproduce

.

### Acceptance Criteria

Vulnerability solved and not listed in the Dependabot alerts.

### dotCMS Version

Master

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by oidacra** [comment]
```
core-web@23.4.0-next.1 /Users/oidacra/Work/core/core-web
├─┬ @angular-devkit/build-angular@17.1.0
│ ├── webpack-dev-middleware@6.1.1
│ └─┬ webpack-dev-server@4.15.1
│   └── webpack-dev-middleware@5.3.4
├─┬ @nx/angular@18.0.4
│ └─┬ @nx/webpack@18.0.4
│   └─┬ webpack-dev-server@4.15.2
│     └── webpack-dev-middleware@5.3.4 deduped
├─┬ @nxext/stencil@17.2.2
│ └─┬ @nx/angular@17.3.2
│   └─┬ @nx/webpack@17.3.2
│     └─┬ webpack-dev-server@4.15.2
│       └── webpack-dev-middleware@5.3.4 deduped
└─┬ @storybook/angular@7.6.19
  └─┬ @storybook/builder-webpack5@7.6.19
    └── webpack-dev-middleware@6.1.3
```
