### ISSUE TITLE
tschaub gh-pages vulnerable to prototype pollution

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28436]
### Parent Issue

https://github.com/dotCMS/core/issues/28435

### Problem Statement

Prototype pollution vulnerability in tschaub gh-pages via the partial variable in util.js.

https://github.com/dotCMS/core/security/dependabot/366

### Steps to Reproduce

.

### Acceptance Criteria

Vulnerability solved and not listed in the Dependabot alerts.

### dotCMS Version

Master

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by oidacra** [comment]
Dependency used for publishing the storybook to Github Pages. Deleted by now until fix the CI/CD for publish again the storybook
