### ISSUE TITLE
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28438]
### Parent Issue

#28435

### Problem Statement

Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem 
https://github.com/dotCMS/core/security/dependabot/333

### Steps to Reproduce

.

### Acceptance Criteria

Vulnerability solved and not listed in the Dependabot alerts.

### dotCMS Version

Master

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

**Comment by oidacra** [comment]
```
core-web@23.4.0-next.1 /Users/oidacra/Work/core/core-web
├─┬ @angular-devkit/build-angular@17.1.0
│ ├─┬ @vitejs/plugin-basic-ssl@1.0.2
│ │ └── vite@5.0.11
│ └── vite@5.0.11
├─┬ @nx/vite@18.0.4
│ └── vite@5.0.13 deduped
├─┬ vite-plugin-dts@2.3.0
│ └── vite@5.0.13 deduped
└── vite@5.0.13
```
