### ISSUE TITLE
Document real world headless experiment pattern

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28443]
### Task

The pattern used for our headless experiment needs to be documented  so it can be used by those looking to implementing it in other JS frameworks.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The pattern used for our headless experiment is documented  and can used by those looking to implementing it in other JS frameworks.

**Comment by oidacra** [comment]
- Explain the pattern used and what steps are necessary to take in consideration for the implementation to VUE( and other frameworks)
- Flow, diagram, or any necessary to explain what I need to implement to the correct use of DotExperiment

**Comment by dsilvam** [comment]
https://docs.google.com/document/d/1wpvlTse-IfLh0F4tlreoQNg-1k1VfH_8_Zp6hX3A5xM/edit

**Comment by oidacra** [comment]
Comment fixed @fmontes
