### ISSUE TITLE
Change "Add New Device" Button to "Edit" Icon

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28455]
### Problem Statement

The "Add New Device" button in the interface currently does not add a new device but rather allows users to edit existing device settings. This misleads users, affecting usability and efficiency. 
![image](https://github.com/dotCMS/core/assets/2641437/05186168-7975-4e83-a06a-00cf1bf13a80)

Then we need to change this icon by a edit pen. 

### Steps to Reproduce

- Login as admin 
- Edit any page 
- Open the preview drop-down
- In the devices list click in the + button on the top of the list 
- Observe that the interface transitions to an edit mode for an existing device rather than adding a new device.

### Acceptance Criteria

The "Add New Device" button should be replaced with an "Edit" icon that accurately reflects its function.
The new icon should be tested across different browsers and devices to ensure it performs consistently.
The tooltip and accessibility labels for the button should be updated to "Edit Device."

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by melissarojas-dotcms** [comment]
[Link to Figma](https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=372%3A9191&mode=design&t=OpsujDbAEROnKkoo-1) with the new icon.

**Comment by zJaaal** [comment]
## IQA Passed

Icon is updated.

Docker Image: `[dotcms/dotcms:trunk_743e6da]`

## Screenshot

https://github.com/dotCMS/core/assets/63567962/3e0e6046-e693-47a9-8606-0fdffddf4f63

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker
