### ISSUE TITLE
Edit Page 2: Allow Users to scroll while dragging 

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#28469]
### Parent Issue

https://github.com/dotCMS/core/issues/26644

### Task

- [ ] Enable the user to scroll inside the iframe page while dragging from palette, outside of browser like dot-asset or move contentlets 

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
IQA Failed

The editor works as expected, but i'm not able to drop anything close to the zone of scroll when im on the edge

## Screenshots

### Headless Chromium Cross Origin

https://github.com/dotCMS/core/assets/63567962/bca94cfe-840c-47c0-9343-ea68d26153d8

**Comment by KevinDavilaDotCMS** [comment]
That will happen when there is a contentlet within the first or last 100 px, it definitely needs to be corrected but perhaps it can be in a different ticket and we add some more cases that we find?
thoughts? cc @fmontes

**Comment by fmontes** [comment]
@zJaaal @KevinDavilaDotCMS let's move on with this, very edge case, Kevin please create a ticket for this case.

**Comment by zJaaal** [comment]
# Note to QA

I didn't find any other issues so we can pass the IQA.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_8b71ba0**, Docker, macOS 13.0, FF v124.0.2
