### ISSUE TITLE
QA: Full regression to edit mode V2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28466]
### Problem Statement

In order to release that feature we need to make sure everything is working as expected and we are not ignoring some important issues. 

### Steps to Reproduce

- Start a fresh instance turning on the following FF: 
```
DOT_CONTENT_EDITOR2_ENABLED: "true"
DOT_FEATURE_FLAG_NEW_EDIT_PAGE: "true"
```

### Acceptance Criteria

We need to make sure not important issues on this transition 

### dotCMS Version

Should be tested on the latest trunk image 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**QA Feedback**

1. 'From' word is getting cut in the alert message
<img width="1280" alt="Screenshot 2024-05-07 at 3 13 36 PM" src="https://github.com/dotCMS/core/assets/129882031/093778ac-35a5-4b09-ba29-ae8c44f16303">

2. PDF thumbnails are not getting rendered 
<img width="1280" alt="Screenshot 2024-05-07 at 3 09 16 PM" src="https://github.com/dotCMS/core/assets/129882031/2b30d67c-e07c-4da8-b8ee-9acea4e8a981">

3. Only at the second try the adds the selected piece of content, it should make it at the first time it opens

https://github.com/dotCMS/core/assets/129882031/3be635f7-4f99-423b-9b5d-a2414f95bdc9

**Comment by bryanboza** [comment]
@josemejias11 steps 3 and 4 are from 'Edit Content' not from 'Edit page', please move those to the edit content epic, here the link: https://github.com/dotCMS/core/issues/25445

**Comment by josemejias11** [comment]
**QA Comment** 

Cards added https://github.com/dotCMS/core/issues/28560 https://github.com/dotCMS/core/issues/28561

**Comment by josemejias11** [comment]
** QA Approved**: Tested using Docker, macOS 14.5 , FF v124.0.2
