### ISSUE TITLE
Binary fields encode some filename characters poorly

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#28462]
### Problem Statement

Certain characters, like one present toward the end of standard Mac screenshots, will show up as a garbled mess in Binary fields after uploading.

### Steps to Reproduce

1. Create screenshot on Mac
2. Upload file to binary field
3. Observe result

![Screenshot 2024-05-07 at 12 22 08 PM](https://github.com/dotCMS/core/assets/102264829/90d85431-9f7a-4e1e-92a1-f5f754508bfd)

Vs the file itself:

![Screenshot 2024-05-08 at 11 35 08 AM](https://github.com/dotCMS/core/assets/102264829/9bf2535b-d084-4ebb-9900-3ce0ebdd1e69)

### Acceptance Criteria

File names should either display identically to their appearance on OS, or should omit problematic characters at the time of upload.

### dotCMS Version

dotcms-core 1.0.0-SNAPSHOT (April 30, 2024 11:38 AM)

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ed06de4**, Docker, macOS 14.5, FF v126.0.1
