### ISSUE TITLE
Creating new content don't respect language selected

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28489]
### Parent Issue

https://github.com/dotCMS/core/issues/28366

### Problem Statement

 When another language than the default one is selected and an image is uploaded from the site browser, the contentlet that opens has the default language selected

### Steps to Reproduce

- go into the site browser
- change the language to another one than the default
- click on the blue plus sign
- choose _image or file_  (or Page)
- choose image -> at this point the contentlet that opens has the language field set to the default language

### Acceptance Criteria

Selected Language should be respected, if ALL was selected default lang should be used.

Let's test against Image or File and Page.

It should behave the same way from Site > Browser and from Content > Search.

### dotCMS Version

23.01 LTS

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116044

**Comment by erickgonzalez** [comment]
Passed Internal QA. Now, it respects the language selected when creating new content.

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
