### ISSUE TITLE
Create a Happy Path Cheat Sheet to build and deploy the project

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28480]
As a developer, I would like to have a cheat that summarizes a Happy Path for BE and FE developers at dotCMS. The document should contain:
- [ ] How to setup the environment
- [ ] Steps to build and deploy (Backend & Frontend developer use different paths)

To complete this card, you would probably need to perform interviews to devs and/or use the data gathered from the Q1 2024 Developer Survey.

The following cards were created to obtain the required inputs: 
https://github.com/dotCMS/core/issues/28482
https://github.com/dotCMS/core/issues/28481

**Comment by dcolina** [comment]
Here is the latest version of the documents.

[dotBackendOnboarding.md](https://github.com/dotCMS/core/files/15482100/dotBackendOnboarding.md)
[dotFrontendOnboarding.md](https://github.com/dotCMS/core/files/15482099/dotFrontendOnboarding.md)
[dotOnboardingCheatSheet.pdf](https://github.com/dotCMS/core/files/15482123/dotOnboardingCheatSheet.pdf)

**Comment by dcolina** [comment]
Last revision `06/03/2024`

[dotBackendOnboarding.md](https://github.com/user-attachments/files/15546342/dotBackendOnboarding.md)
[dotFrontendOnboarding.md](https://github.com/user-attachments/files/15546343/dotFrontendOnboarding.md)
[dotOnboardingCheatSheet.pdf](https://github.com/user-attachments/files/15546358/dotOnboardingCheatSheet.pdf)

Hint: `You can edit the dotOnboardingCheatSheet.pdf with Canva.`
