### ISSUE TITLE
Interview FE stakeholders

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28482]

**Comment by dcolina** [comment]
## Backend Feedback:

### Cons:

- Missing Command for Specific Port:

There is no just command to start the application on a specific port, causing inconvenience when the application starts on a random port and requires an additional step to identify the port.
Live Logs Access:

The new commands complicate accessing live logs of the application running in the local environment.

- Full or Empty Startup:

Lack of a just command to start the application specifying whether to use a Full Started or Empty Started setup.

- Database Dump Initialization:

Missing procedure or command to start the application using a database dump.

- Justfile Organization:

Desire for the justfile to be organized by usage criteria to improve usability.

- Value of Commands:

Some commands, such as running all application tests (Unit, Integration, Postman), are deemed not very valuable for local development.

- Command Categorization:

Importance of categorizing or grouping commands in the justfile for better organization and usability.

### Pros:

- Transition to Maven:
The shift from `Gradle` to `Maven` has been positively received, unifying the process of compilation, building, testing, and deployment.

- Containerized Application Management:
The ability to manage the entire application through containers is highly positive.

- Debugging with IntelliJ:
The recently introduced just command allows step-by-step debugging in IntelliJ, enhancing the development experience.

## Frontend Feedback:

### Cons:

- Lack of Quick Start Procedure:
Absence of an official procedure to configure the local environment (a quick start guide).

- Outdated Documentation:
Existing documentation is outdated and does not align with the current project configuration process.

Pros:
- Unified Configuration Process:
Stakeholders see the potential of creating a unified process for all developers to configure their local environments as highly positive.

- Backend Startup and Testing:
The current process involves starting the backend with a docker-compose file and configuring a proxy in Angular to target the desired backend version, which is seen as effective.

- Local Testing Tricks:
Stakeholders have shared various tricks they use for local testing that help optimize their tasks.
