### ISSUE TITLE
Remove three dots at the end of the Bundle ID

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28509]
### Task

Remove three dots at the end of the Bundle ID

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Three dots at the end of the Bundle ID don't make sense since we're showing the whole Bundle ID.

**Comment by erickgonzalez** [comment]
It's working as it should. Now, the three dots are not showing, and we show the full Bundle ID.

![Image](https://github.com/dotCMS/core/assets/5278970/d6870f05-8265-4019-b84c-6f415bf8325d)

**Comment by bryanboza** [comment]
Fixed, tested on Trunk // Docker // FF
