### ISSUE TITLE
Refresh Running Experiment Cache after abort one Experiment

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28507]
### Problem Statement

After abort an Experiment it is keep on the Running Experiment Cache so it means that a User can be still assigned to the Experiment even after it was aborted

### Steps to Reproduce

1. Create a Page
2. Create a Experiment and Start it
3. Open a Incognito Window and visit any page on the site, check that you was assigned to the Experiment on the Browser LocalStorage, don't close the Window.
4. Cancel the Experiment.
5. Open another tab on the same window from step 3 and visit any page, you should be removed from the Experiment because it is not running anymore.
6. Open a new incognito Window and Visit any pages, you should not be included on any Experiment

### Acceptance Criteria

1. Not keep included on a Experiment after it was aborted.
2. Not be assigned to an Experiment after it was aborted

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/28541

**Comment by dsilvam** [comment]
Passed Internal QA: Running experiments cache properly invalidated upon aborting a running experiment.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_4273db9**, Docker, macOS 13.0, FF v124.0.2

I'm not able to see the **experiment_data** field within the **localStorage** cache 

<img width="1542" alt="Screenshot 2024-05-17 at 11 48 29 AM" src="https://github.com/dotCMS/core/assets/129882031/3e04f941-8f5a-475b-b7fe-a94f412b5824">

**Comment by freddyDOTCMS** [comment]
> **Failed**: Tested on **trunk_4273db9**, Docker, macOS 13.0, FF v124.0.2
> 
> I'm not able to see the **experiment_data** field within the **localStorage** cache
> 
> <img alt="Screenshot 2024-05-17 at 11 48 29 AM" width="1542" src="https://private-user-images.githubusercontent.com/129882031/331688132-3e04f941-8f5a-475b-b7fe-a94f412b5824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTkyOTUsIm5iZiI6MTcxNjMxODk5NSwicGF0aCI6Ii8xMjk4ODIwMzEvMzMxNjg4MTMyLTNlMDRmOTQxLThmNWEtNDc1Yi1iN2ZlLWE5NGY0MTJiNTgyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxOTE2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2Y4ZjZmZTA5NGVmYmViNjcwMjAzMGYyMzA2ZTZkOTVjOGY0YzE4NzQyNGNiNDZiZmFlMWU3Y2U2OTFiNGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MBhuWHa0NF2U3T2dd2_DkbqR9Rqwi2PMD4aPa1qh-qI">

It is working as excepted

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_aaa6d05**, Docker, macOS 13.0, FF v124.0.2
