### ISSUE TITLE
Add Search Box for Bundle ID

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28508]
### Task

Add a search box (similar to the one in the content search) that allows searching for a partial or complete bundle ID.

### Proposed Objective

Customer Support

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

- Bundle ID to search for could be on another page
- Partial Bundle IDs should be allowed
- Placeholder for the search box: `Bundle ID to search for...`

**Comment by erickgonzalez** [comment]
To Test:

Let's create many bundles and try to PP them (it doesn't matter if they fail). After that, try to search for a bundle ID that exists on the second page, but you must be on the first page and the list should be filtered.

Search by a complete bundle ID and also a partial bundle ID.

Clicking on the filtered bundle should open the bundle detail.

**Comment by gortiz-dotcms** [comment]
### **Passed Internal QA**

Tests made:

-  Searching for a bundle placed in second page. The image below shows a bundle that was in the second page and also was searched by complete bundle ID

![image](https://github.com/dotCMS/core/assets/170764530/ca4da31f-548d-42d2-95f2-7ae57fbfe36f)

- Searching by a partial bundle ID and also clicking on the filtered bundle to check detail.

![image](https://github.com/dotCMS/core/assets/170764530/d5976e4a-e31f-4ec8-8408-6ab43b0ce8e2)

**Comment by bryanboza** [comment]
Fxied, tested on trunk // Docker // FF 

![Image](https://github.com/user-attachments/assets/dfc45623-fcda-4968-92d0-1baf0863f86b)
