### ISSUE TITLE
Preview selection displays Height x Width instead of Width x Height

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#28517]
### Problem Statement

On the preview device list in the UVE Preview button, it displays the dimensions as {Height} x {Width} instead of {Width} x {Height}.

All links work correctly, all titles are correct; this is just a simple text issue with the dropdown.

### Steps to Reproduce

1. Open a page in the editor in QA Master
2. Hit the Preview dropdown.
3. See the following:

![image](https://github.com/dotCMS/core/assets/102264829/fae02b8e-0698-4614-8df5-715bd381440b)

The device highlighted in that image illustrates it:

![image](https://github.com/dotCMS/core/assets/102264829/c14949d4-e46c-4644-bbd0-1da343c118ef)

It displays properly in the editor; it's just HxW instead of WxH on the dropdown.

### Acceptance Criteria

The dimensions should display as {Width}x{Height}.

### dotCMS Version

dotcms-core 1.0.0-SNAPSHOT (May 09, 2024 1:25 PM), current on QA Master at the time of writing.

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by jdcmsd** [comment]
https://github.com/dotCMS/core/pull/28520 should fix it! (Tested locally.)

![image](https://github.com/dotCMS/core/assets/102264829/ab5b9d81-79ae-459e-8640-0b56146be88b)

![image](https://github.com/dotCMS/core/assets/102264829/e5f8b930-cf51-43db-8842-be47bb26d496)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d5e1ec1**, Docker, macOS 14.5, FF v126.0.1
