### ISSUE TITLE
Deploy infra for new artifactory

### ISSUE THREAD

**Issue by sfreudenthaler** [dotCMS/core#28516]
## Story
**As A** dotCMS engineer 
**I want** an updated artifactory (infrastructure & version)
**So that** build pipelines are stable and reliable and I can release code 

## Context
We're having issues with artifactory.  The diagnosed cause is lack capacity at the database level.  We're using a very old (~5 years) version of artifactory, running the server and the database in the same container, inside K8s.  Given the criticality of artifactory in our pipelines and release processes it's time that we give it a refresh as part of getting it back up and stable. 

## Acceptance Criteria
- [x] put in the cloud account that is "in-scope" for soc 2 and ISO
- [x] use a new database on an existing shared RDS instance
- [x] host on it's own EC2 instance (us-east region)
- [x] use efs under for filesystem

**Comment by yolabingo** [comment]
An artifactory 7 server is running and ready for configuration

**Comment by yolabingo** [comment]
[Docs and provisioning tools here](https://github.com/dotCMS/internal-infrastructure/tree/main/artifactory).
Closing this as complete.
