### ISSUE TITLE
SDK: Simple Lucene Query Builder for Content API

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28537]
### Parent Issue

https://github.com/dotCMS/core/issues/28415

### User Story

As a developer using the JS client SDK I want to be able to build Lucene Queries in a functional approach, so I can be able to rely all the logic and building process of the query to dotCMS.

> [!WARNING]  
The example is a visual of how it should look like, this ticket will cover simple cases, the ones showed here a more complex ones.
> 

Example: 

```javascript
// title:((hello OR hi) AND (world OR universe))
queryBuilder()
    .field('title')
    .group(queryBuilder().eq('hello').or().eq('hi'))
    .and()
    .group(queryBuilder().eq('world').or().eq('universe'));

// publish_date:[20220101 TO 20221231]
queryBuilder().field('publish_date').dateRange('20220101', '20221231').build()
```

### Acceptance Criteria

- We should should support simple keywords like: `field`, `excludeField`, `term`, `and`, `or` & `not`
- We should have a way to build simple queries like `+title: summer OR winter` or `+summary: cheap AND affordable` or `+colors: white NOT black`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

- You understand the basics of Lucene Query
- You understand the basics of JS Build Pattern approach
- You understand the basics of dotCMS Content API

**Comment by zJaaal** [comment]
Does this needs IQA? 

cc: @fmontes

**Comment by fmontes** [comment]
@zJaaal I would say no.
