### ISSUE TITLE
Telemetry: processing upon API request interception needs to happen asynchronously 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28531]
### Problem Statement

When API interception is enabled, the processing is happening in a synchronous way which makes the requests to take longer and may even fail to respond if an underlying error happens. 

### Steps to Reproduce

* Bring up dotCMS in debug mode
* Install the telemetry plugin
* Enable API tracking with the property TELEMETRY_API_METRICS_ENABLED set to true
* Put a breakpoint in https://github.com/dotCMS/com.dotcms.telemetry/blob/main/src/main/java/com/dotcms/experience/collectors/api/ApiMetricWebInterceptor.java#L38
* Hit the frontend at localhost:8080

Issue: see how the breakpoint gets hit but the page doesn't get rendered until resuming. 

### Acceptance Criteria

The processing that happens on the interception of the API hits needs to happen asynchronously. 

### dotCMS Version

Telemetry plugin 24.05.2

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
To save the Hit on the Database is already async, how we can see here: 

https://github.com/dotCMS/com.dotcms.telemetry/blob/f3eb85d3911ae0f4ea7c6a7c072cf8357119ac88/src/main/java/com/dotcms/experience/collectors/api/ApiMetricFactorySubmitter.java#L48

We hace some code that is not running on the Request Thread, but what it does is select the MetricType for the current request it should not take a lot time, also if any Exception is thrown in this code the Response continue normally.
