### ISSUE TITLE
refactor: delete templateAjax

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28563]
### Task

TemplateAjax is not longer used, lets remove it in favor of TemplateResource

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The template ajax wont exit

### Quality Assurance Notes & Workarounds

Do not need QA

**Comment by jdotcms** [comment]
change the effort to 5, since the issue gets more complicated since the javascript references where not considered on the initial estimation

**Comment by fmontes** [comment]
> change the effort to 5, since the issue gets more complicated since the javascript references where not considered on the initial estimation

@jdotcms please use the actual effort, is important to discuss our stimations that went south.
