### ISSUE TITLE
Replacing EnvironmentAjaxAction by EnvironmentResource

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28578]
### User Story

As an user, I want to be able to create an PP env by using rest

### Acceptance Criteria

UI uses the new endpoint to create a PP env

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

Postman test for create env

**Comment by wezell** [comment]
When adding the "allowed" roles permissions, the api now takes only RoleIds which can be hard to deal with.  What we need to allow on the end point is to be able to pass a List<String> which can be made up of roleIds, roleKeys, userIds and/or user emails, in that order.  We should try to resolve what is passed in as we iterate over the list of strings when building the permissions for the env

**Comment by jearley-captech** [comment]
That would be fantastic to allow the API to take userId/email, role names as well (and let the system resolve these internally).  That would really make it easy for setting up endpoints.

**Comment by jdotcms** [comment]
Noted, working on it

**Comment by jdotcms** [comment]
IQA: we have the crud for env: https://github.com/dotCMS/core/blob/master/dotcms-postman/src/main/resources/postman/EnvironmentResource.postman_collection.json

**Comment by freddyDOTCMS** [comment]
Needs Work:

- When try to create a Environment without set name got a not friendly message:

```
{
    "message": "ERROR: null value in column \"name\" of relation \"publishing_environment\" violates not-null constraint\n  Detail: Failing row contains (4a0facdf-e1e5-4987-995f-6b56a11b272e, null, t).{\n  \"SQL\": [\"INSERT INTO publishing_environment VALUES (?,?,?)\"],\n  \"maxRows\": [-1],\n  \"offest\": [0],\n  \"params\": [\n    \"4a0facdf-e1e5-4987-995f-6b56a11b272e\",\n    null,\n    true\n  ]\n}"
}
```

https://github.com/dotCMS/core/pull/28984/files#diff-2afa388b5d372de717411a8d77cd221d7104df7a9b1824f8f931c475a9dafc86R554

- If we don't set the whoCanSend attribute then got a 500 HTTP Error, it should create the Environment any way


https://github.com/dotCMS/core/pull/28984/files#diff-2afa388b5d372de717411a8d77cd221d7104df7a9b1824f8f931c475a9dafc86R607

I created a new PR with some missis cases, including the 2 mentioned before: https://github.com/dotCMS/core/pull/28984

**Comment by dsilvam** [comment]
Failed IQA: 
The update environment endpoint is not working as expected. 
You can pass a non existing `environmentId` via url but it will ignore it and use the `environmentName` provided in the body to look for the existing environment. 

E.g., 
```
PUT {{serverURL}}/api/environment/does_not_exist
{
    "name":"existing name",
    "pushMode":"PUSH_TO_ONE",
    "whoCanSend":["admin@dotcms.com"]
}
```

It will then return the updated object with the "non existing id" provided as the object id, which is not the real id of the object.  

Acceptance criteria: 
* Use the provided environmentId via url to look up for the environment and use the provided environmentName to update the existing name.
