### ISSUE TITLE
Add a way to bulk Reset Permissions

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28579]
### User Story

The customer has a requirement to reset permissions for over 2500 contentlets. At present, the only method available is to manually click the "RESET PERMISSION" button on each contentlet.

### Acceptance Criteria

Create an endpoint that accepts a Lucene query or a list of contentlets ids to reset permissions.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116065

**Comment by erickgonzalez** [comment]
First, let's work on the BE part before figuring out where to add it to the UI.

For the BE part, let's consider the following:
* A new endpoint to reset permissions in the Permission Resource `_resetPermissions`
* Postman Tests.
* This new endpoint should receive a Lucene query in the body.
* POST 
* Check user permissions

**Comment by jdotcms** [comment]
do you think you can create an actionlet that does this?
if you could you can call the merge which is already batch approach and call this specific reset permissions action

**Comment by dsolistorres** [comment]
**Internal QA approved**
- After applying the Reset Permissions workflow action to multiple contents, the permissions are reset for the selected contentlets. The action is only applied on the contentlets where the user is able to edit/reset permissions.

Content before applying Reset Permissions workflow action on the selected items
<img width="842" alt="before-reset-permissions" src="https://github.com/user-attachments/assets/c949c5bd-a958-4787-8dae-9e966de99f00">

Content after applying Reset Permissions workflow action on the selected items
<img width="842" alt="after-reset-permissions" src="https://github.com/user-attachments/assets/af20ea96-3bd5-46c1-a1aa-86203d2a9df7">

**Comment by bryanboza** [comment]
Fixed, tested on main // Docker // FF
