### ISSUE TITLE
GraphQL __icon__ field violates GraphQL introspection convention prohibiting __ prefixes

### ISSUE THREAD

**Issue by prestonso** [dotCMS/core#28576]
### Problem Statement

The dotCMS GraphQL API currently uses double-underscore prefixes for certain fields in the GraphQL schema (e.g. `__icon__`). This is a validation of the [GraphQL introspection convention](https://graphql.org/learn/introspection/) that reserves this prefix for schema introspection fields (e.g. `__schema`, `__type`). The [`graphql-js`](https://github.com/graphql/graphql-js) library and other commonly used GraphQL implementations honor this convention.

For dotCMS users leveraging headless architectures, this leads to confusing error messaging and prevents a graceful GraphQL API consumption experience. For instance, I encountered this error when attempting to consume dotCMS GraphQL using Gatsby, which uses `graphql-js` in its [`gatsby-source-graphql`](https://www.gatsbyjs.com/plugins/gatsby-source-graphql/) generic GraphQL consumption plugin.

### Steps to Reproduce

The easiest way to reproduce this issue is to consume the dotCMS GraphQL API via a headless app. In these repro steps, [Gatsby is used](https://www.gatsbyjs.com/docs/quick-start/):

1. Generate a new Gatsby site: `npm init gatsby`
2. Change directory to newly created Gatsby root directory and run `npm run develop` to confirm Gatsby site is running locally.
3. Exit local Gatsby server and install `gatsby-source-graphql` dependency: `npm install gatsby-source-graphql`
4. Configure `gatsby-source-graphql` in `./gatsby-config.js` against a dotCMS instance by adding the object to the `plugins` array, supplying the host URL and API access JWT for dotCMS GraphQL as env vars:

```
    {
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "dotcmsGraphql",
        fieldName: "dotcmsGraphql",
        url: `${process.env.DOTCMS_GRAPHQL_HOST}`,
        headers: {
          Authorization: `Bearer ${process.env.DOTCMS_GRAPHQL_ACCESS_TOKEN}`,
        },
      },
    },
```

5. Run `npm run develop`. The command will hang with an error message similar to the following:

```
success building schema - 0.444s

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Name "__icon__" must not begin with "__", which is reserved by GraphQL introspection.

  14 |     const article = path.resolve('./src/templates/article.js')
  15 |     resolve(
> 16 |       graphql(
     |       ^
  17 |         `
  18 |           {
  19 |             allContentfulArticle {

File: gatsby-node.js:16:7



  Error: Name "__icon__" must not begin with "__", which is reserved by GraphQL introspection.

  - graphql-runner.ts:98 GraphQLRunner.validate
    [preston-so]/[gatsby]/src/query/graphql-runner.ts:98:22

  - graphql-runner.ts:162 GraphQLRunner.query
    [preston-so]/[gatsby]/src/query/graphql-runner.ts:162:25

  - create-graphql-runner.ts:59
    [preston-so]/[gatsby]/src/bootstrap/create-graphql-runner.ts:59:8

  - gatsby-node.js:16
    /Users/prestonso/projects/preston-so/gatsby-node.js:16:7

  - debuggability.js:384 Promise._execute
    [preston-so]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [preston-so]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [preston-so]/[bluebird]/js/release/promise.js:103:10

  - gatsby-node.js:13 Object.exports.createPages
    /Users/prestonso/projects/preston-so/gatsby-node.js:13:10

  - api-runner-node.js:485 runAPI
    [preston-so]/[gatsby]/src/utils/api-runner-node.js:485:22

  - api-runner-node.js:636 Promise.catch.decorateEvent.pluginName
    [preston-so]/[gatsby]/src/utils/api-runner-node.js:636:13

  - debuggability.js:384 Promise._execute
    [preston-so]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [preston-so]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [preston-so]/[bluebird]/js/release/promise.js:103:10

  - api-runner-node.js:634
    [preston-so]/[gatsby]/src/utils/api-runner-node.js:634:16


info Total nodes: 568, SitePage nodes: 1 (use --verbose for breakdown)
failed createPages - 0.059s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.072s
success update schema - 0.022s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.088s
success onPostBootstrap - 0.090s
info bootstrap finished - 20.977s
success onPreExtractQueries - 0.001s

 ERROR

Missing onError handler for invocation 'extracting-queries', error was 'Error: Name "__icon__" must not begin with "__", which is reserved by GraphQL introspection.'. Stacktrace was 'Error:
 Name "__icon__" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/prestonso/projects/preston-so/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/prestonso/projects/preston-so/node_modules/graphql/validation/validate.js:54:35)
    at extractOperations (/Users/prestonso/projects/preston-so/node_modules/gatsby/src/query/query-compiler.js:212:20)
    at processQueries (/Users/prestonso/projects/preston-so/node_modules/gatsby/src/query/query-compiler.js:171:45)
    at compile (/Users/prestonso/projects/preston-so/node_modules/gatsby/src/query/query-compiler.js:82:19)
    at updateStateAndRunQueries (/Users/prestonso/projects/preston-so/node_modules/gatsby/src/query/query-watcher.ts:220:40)
    at extractQueries (/Users/prestonso/projects/preston-so/node_modules/gatsby/src/services/extract-queries.ts:18:3)'
```

### Acceptance Criteria

1. When using a GraphQL implementation adhering to GraphQL introspection convention, no reserved word errors should be triggered when consuming data from dotCMS GraphQL.
2. dotCMS GraphQL should use a convention other than `__`-prefixing for fields in order to avoid violating this convention.

### dotCMS Version

Latest nightly build and all preceding versions of dotCMS with GraphQL API support

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by prestonso** [comment]
Proposed resolution: Find and replace [all instances](https://github.com/search?q=repo%3AdotCMS%2Fcore%20__icon&type=code) of `__icon__` and other `__`-prefixed fields destined for GraphQL API exposure to a single-underscore or other prefix convention.

Potential risk: GraphQL API breakage for any headless consumers already using dotCMS as front-end developers.

**Comment by prestonso** [comment]
@jdotcms informs me a fix for this may be in progress already.

**Comment by erickgonzalez** [comment]
I understand that this was QA'd with the following link: https://github.com/dotCMS/core/issues/28420.
