### ISSUE TITLE
AI Viewtools not working

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28571]
### Problem Statement

When attempting to use the AI viewtool $ai the following error is happening: 
https://gist.github.com/dsilvam/b89f70c846e96a9c43990b4387a69d38

This prevents using any of the viewtools available for AI functionality. 

### Steps to Reproduce

1. Set up an API key on the dotAI app. 
2. Add a widget to a page with `$ai.generateText("your prompt")`
3. Render the page

You can see the error in the log https://gist.github.com/dsilvam/b89f70c846e96a9c43990b4387a69d38

### Acceptance Criteria

AI viewtools working without issues. 

### dotCMS Version

master | Agile 24.05.13

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: AI viewtools working again.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected 
![Image](https://github.com/dotCMS/core/assets/2641437/de72c25d-dd2a-4c4d-b877-f0aaddca3ba7)
