### ISSUE TITLE
Make MultiTree Multi variant cache cluster aware

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28588]
### Problem Statement

Currently, we store a Map for each page in the MultiTreeCache. In this Map, the keys represent variantIds, and the values represent the contents of the page for that variant. You can see this implementation at the following link:

https://github.com/dotCMS/core/blob/eb200d27482a557634e0f732ed5f055c0df28450/dotCMS/src/main/java/com/dotmarketing/cache/MultiTreeCache.java#L66-L74

However, this approach is not cluster-aware because we perform a Map Put operation every time new content is added or removed from a page within any variant. Please note that only cache removal operations are cluster-aware.

### Steps to Reproduce

1. Start dotCMS up on a cluster environment
2. Create a Page Add any content on it
3. Crate a Experiment.
4. Add a new Variant on the newly created Experiment and remove the Contentlet added  on the DEFAULT Variant and add another one.
5. Remove the Content on the Variant created on the 4 step, and add another one.
6. Refresh the page and you are going to see that sometime you got the Contentlet added on the 4 step, and sometimes are you going to add the Content on the 5 step

### Acceptance Criteria

The cache need to be cluster aware.
The case describe on "Steps to Reproduce" should not happen

### dotCMS Version

Latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed Internal QA: Unable to reproduce. Tested on master-qa.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_db33b31**, Docker, macOS 13.0, FF v124.0.2
