### ISSUE TITLE
Zappier plugin not compiling 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28589]
### Task

After downloading the Zappier plugin repo, you can't compile it successfully.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Zappier should compile successfully and also be able to upload it.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116237

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/dotcms-zapier-plugin/pull/4

**Comment by bryanboza** [comment]
Fixed, tested on prod and it is working as expected!
