### ISSUE TITLE
drawed_body column on the template table is text column that stores JSON

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#28592]
### User Story

As a support agent I want to be able to easily query the drawed_body column to determine usages of containers, among other things.

Currently it is JSON stored in a text field, which is not easily queriable. 

### Acceptance Criteria

Convert the column from TEXT to JSONB

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
@swicken-dotcms Is this still a clear need?

**Comment by prestonso** [comment]
No response; closing.
