### ISSUE TITLE
Metrics: Count of Active Sites

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28591]
### User Story

As a Product Owner, I want to be able to get the total number of active sites in addition to other usage metrics already gathered so I can get a better understanding of the usage of this feature. 

### Acceptance Criteria

- [ ] "COUNT_OF_ACTIVE_SITES" metric implemented, both available as part of the data captured by the job and via the telemetry endpoint. 

- [ ] Integration test. 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/53

**Comment by freddyDOTCMS** [comment]
Pass IQA: Work as expected
