### ISSUE TITLE
Send Version of CLI along with Header

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#28594]
### Parent Issue

https://github.com/dotCMS/core/issues/28378

### Task

We want to send the version of the CLI along with the Headers when making a call to an instance of dotCMS.

At some point in the future, we'll want the dotCMS instance to be able to look at the headers and respond, "You're using an out of date version of the CLI, time up upgrade!" 

But right now, we just want to include the version in the headers so that we won't get into a spot where we can't add that response improvement to dotCMS in the future.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

**Comment by spbolton** [comment]
Bug introduced in Native build. https://github.com/dotCMS/core/issues/28915

**Comment by fabrizzio-dotCMS** [comment]
you can set a proxy in front of dotCMS to intercept all apis call using Charles for example 
You can also validate that the command dotCLI status prints the cli version

**Comment by bryanboza** [comment]
Fixed, tested on trunk // latest CLI version
