### ISSUE TITLE
Edit Page V2:  the `Editing a variant` message disappears after making a change in the UVE

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28614]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Problem Statement

The `Editing a variant` message disappears after making a change in the UVE

### Steps to Reproduce

1. Enable the new UVE
2. Set up experiments for a Page
3. Create a variant
4. Edit that variant
5. See the error

https://github.com/dotCMS/core/assets/72418962/139e8b9c-5f95-4b55-905d-ac3913ca8227

### Acceptance Criteria

The `Editing a variant` message should not disappear after a change.

### dotCMS Version

`master`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master

https://github.com/dotCMS/core/assets/144152756/0ef9c1f2-a688-40b8-ae20-100cd7542fa1

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_db33b31**, Docker, macOS 13.0, FF v124.0.2
