### ISSUE TITLE
Issue: "Show Preview" Button Does Not Reflect Selected Language

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#28620]
### Problem Statement

When switching the language in Edit Mode, the Preview updates correctly to the selected language. However, clicking the "Show Preview" button opens a new tab with the content in the default language (English) instead of the selected language (Spanish).

### Steps to Reproduce

Steps to Reproduce

1. Open a page in Edit Mode in English.
2. Use the language dropdown on the right to switch to Spanish.
3. Observe that the Preview updates to Spanish.
4. Click the "Show Preview" button.

Expected Behavior
The new tab opened by clicking the "Show Preview" button should display the page content in the selected language (Spanish).

Actual Behavior
The new tab opened by clicking the "Show Preview" button displays the page content in the default language (English), despite the Edit Mode showing the correct language (Spanish).

Technical Details
The URL in Edit Mode updates to language_id=2 when switching to Spanish.
The URL used by the "Show Preview" button remains language_id=1, indicating English.

Uploading Screen Recording 2024-05-21 at 10.56.03 AM.mov…

### Acceptance Criteria

Language Consistency in Preview:

When a user switches the language in Edit Mode using the language dropdown, the Preview section should update to the selected language.
Clicking the "Show Preview" button should open a new tab that reflects the language selected in Edit Mode.

### dotCMS Version

23.10.24 LTS

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116371

**Comment by m27iu4** [comment]
https://dotcms.zendesk.com/agent/tickets/117244

**Comment by erickgonzalez** [comment]
Working as it should now, the language is respected when opening Preview Mode.
`index?language_id=2`

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_8a83f92**, Docker, macOS 14.5, FF v126.0.1
