### ISSUE TITLE
Copy URL Button Not Working Properly in Edit V2 Mode

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#28627]
### Problem Statement

The “Copy URL” button within the Edit V2 mode is not functioning correctly. Users are unable to copy URLs as intended.

### Steps to Reproduce

1. Switch to Edit V2 mode in the application
2. Navigate to any content or page where the “Copy URL” button is available
3. Click the “Copy URL” button
4. Observe whether the URL is successfully copied to the clipboard

### Acceptance Criteria

Clicking the “Copy URL” button should copy the URL to the clipboard, allowing users to paste it elsewhere.

### dotCMS Version

24.05.20

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

<img width="1200" alt="Screenshot 2024-05-21 at 3 39 17 PM" src="https://github.com/dotCMS/core/assets/129882031/b4294871-2809-4c2b-9030-13c1a439b365">

**Comment by zJaaal** [comment]
# IQA Passed

Now we can copy the raw URL of the current page we are editing.

Docker Image: `[dotcms/dotcms:trunk_db33b31]`

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_109e0e7**, Docker, macOS 13.0, FF v124.0.2

**Comment by jdcmsd** [comment]
Closing https://github.com/dotCMS/core/issues/28463 along with this one.
