### ISSUE TITLE
Block editor field relationship contentlet crash

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28626]
### Problem Statement
When using a block editor field in dotCMS and adding the same related content to each other, it crashes the contentlet.

### Steps to Reproduce
1. Create a content type with a block editor field.
2. Create 3 pieces of content 1, 2 and 3
3. In the block editor field of 1, relate 2 and 3
4. In the block editor field of 2, relate 1 and 3
5. In the block editor field of 3, relate 1 and 2
6. Save and publish the content
7. The content should be somehow corrupted.

### Acceptance Criteria
Contentlets with block editor fields should be able to relate to each other without causing any crashes.

### External Links
N/A

### Assumptions & Initiation Needs
Looks like we need to save the contentlets in the block editor without their internal related contentlet.

### Quality Assurance Notes & Workarounds
N/A

**Comment by rjvelazco** [comment]
Closed in favor of: https://github.com/dotCMS/core/issues/28659
