### ISSUE TITLE
Edit Page V2: Content Palette is not querying content for the current variant

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28656]
### Parent Issue

TBD

### Problem Statement

We need to query the content created for an specific variant. Right now if we create content for a variant we cannot use it from the Content Palette.

Actual query: `"+contentType:{contentTypeVar} +deleted: false   +languageId : 1 "`

It should also contain: `+variant: {current variant} OR DEFAULT`

### Steps to Reproduce

1. Configure the UVE to run for VTL Pages
2. Configure Experiments
3. Go to a page
4. Open Experiments and create a new experiment
5. Create a Variant and hit edit 
6. Create a contentlet from the UVE in a variant
7. Search for that contentlet inside the palette 
8. See the error

https://github.com/dotCMS/core/assets/63567962/b701e2c2-45d3-4795-a0af-5472d00ec344

### Acceptance Criteria

- We should be able to see contetlets created for an specific variant inside the palette
- UVE should work as expected for this contentlets

### dotCMS Version

`trunk-latest`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

- You understand how variants work
- You understand how the UVE work

### Quality Assurance Notes & Workarounds

No workarounds at the moment

**Comment by KevinDavilaDotCMS** [comment]
# IQ Failed
The functionality of contentlets inside variants works

https://github.com/dotCMS/core/assets/144152756/118d8629-0d6a-45cf-8744-e9d0af17bd13

But we cannot edit that contentlets in the UVE

https://github.com/dotCMS/core/assets/144152756/342976f5-ca96-48c8-a2a6-d09f74256e72

Maybe this error can be fixed in other ticket

**Comment by zJaaal** [comment]
We will revisit this issue in this ticket https://github.com/dotCMS/core/issues/28799

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_85dce97**, Docker, macOS 14.5, FF v126.0.1


When trying to add the same content to the variant, the contentlets should close and show the message of the content is already added to the contentlets. Currently we need to close the popup window to show the message.


https://github.com/dotCMS/core/assets/129882031/c96575cd-aaa7-41d3-9d8c-02299c7da32a

**Comment by zJaaal** [comment]
@josemejias11 I'm not sure if that issue is related to this one https://github.com/dotCMS/core/issues/28799 but it is not related to the work done in this issue, we only wanted to show the contentlets created in variants on the content palette, the contentlet selector was not modified in this ticket.

We should raise another ticket for it if is not related to the one I mentioned above

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_6d0d4a5**, Docker, macOS 14.5, FF v126.0.1

Feedback will be addressed in card https://github.com/dotCMS/core/issues/28870
