### ISSUE TITLE
Checkbox changes do not reflect in the block editor

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#28664]
### Problem Statement

- a checkbox value in a contentlet (tested with product contentlet from a content type i custom created - see the video) was updated and the same contetlet was assigned in the Block Editor of a Blog
- when the checkbox value is modified in the contentlet, the change is not reflected in the Block Editor JSON
- this issue only occurs with checkboxes; other values update correctly.
- the checkbox value in the contentlet within the Block Editor updates correctly when the content is deleted and reassigned

### Steps to Reproduce

- add a contentlet in a block editor (e.g. add banner to the block editor to a blog / blog content)
- check json of the banner and blog
- go back to the contentlet (banner) and modify the value of the checkbox 
- check json of the contentlet (banner) and json of the block editor (blog)
- only the json of the banner will update
- go to the block editor, delete the banner, re-add the banner
- check both jsons again - they will show correctly
- I have a video for it also (check the ticket link)
- I have a video with the local test instance (contact me and I will share it, since it's too big to attach it)

### Acceptance Criteria

- changes in the checkbox of the added contentlet in block editor should reflect in the json

### dotCMS Version

- tested on local instance (latest version)

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116405

**Comment by jcastro-dotcms** [comment]
Closing in favor of this https://github.com/dotCMS/core/issues/28659

**Comment by jcastro-dotcms** [comment]
Here's the right way of updating the value of a checkbox via REST: https://github.com/dotCMS/core/issues/28800#issuecomment-2159266623
