### ISSUE TITLE
Limited users can't choose System-host in contentlets on 23.1.*

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28672]
### Parent Issue

So basically there are three issues.

~1. Limited user can't create content type on system host https://github.com/dotCMS/core/issues/25296~ This is Done
~2. As a limited user, you cannot edit the host of a content type https://github.com/dotCMS/core/issues/27575~ This is already another issue
3. Limited user, can't select system host in site/host field in contentlet https://dotcms.zendesk.com/agent/tickets/116409 It has been fixed in 24.4.* and 23.10.24_LTS_V10 so does anyone know which commit/issue fixed this issue so we can try to backport it to  23.1.*

### Task

We need to check which changes have fixed the thrid issue to backport to 23.1.* versions.

Here explained all the details about the issue.

https://github.com/dotCMS/core/assets/102758033/f22ae3f0-327b-42d9-8d27-a76ab628195a

STR:

1. create a limitedRole with full permissions over All sites, add the Tool Content > Search
2. create a limitedUser with BE role and the limitedRole
3. login as limitedUser
4. try to create a Content Generic and select System Host

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/G01N0AU1NUC/p1716907280794979

https://dotcms.zendesk.com/agent/tickets/116409

**Comment by waqasakramdot** [comment]
This issue is also resolved on 23.10.24_LTS_V10

**Comment by erickgonzalez** [comment]
After debugging was able to find the issue where we originally fix it https://github.com/dotCMS/core/issues/24908
