### ISSUE TITLE
Our endpoints should support invalid java locales

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28682]
### Parent Issue

#25603 

### Task

We need to make sure that our endpoints in core and the CLI support invalid java locales when performing operations over  languages (add, edit, delete, get). We might send a warning but never throw an exception that prevents the user from finishes their operation.

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by john-thomas-dotcms** [comment]
To clarify, this is for the endpoint that's used to create new locales.  It needs to allow the creation of a custom locale (5 characters, but doesn't conform to any ISO standards).

This is needed for backward compatibility.

**Comment by dsilvam** [comment]
Passed Internal QA: checked postman tests and they cover enough cases with both success and failures.

**Comment by josemejias11** [comment]
**Approved**: Tested on **dotcms-postman/src/main/resources/postman/LanguageResourceTests.json**, Postman
