### ISSUE TITLE
CLI: Cleanup content type descriptor

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28684]
### Task

The CLI content type descriptor contains duplicate information (probably as a consequence of serialization) that should be removed. We should remove any field duplicity and keep anything related to layouts that will be used in the near future.

Besides, when a content type contains relationships, it would be nice to see and edit the relationship cardinality using an enum name instead of a number. For example: MANY_TO_MANY, ONE_TO_ONE.

These changing don't include layouts. A spike [was created](https://github.com/dotCMS/core/issues/28880) to cover this topic.
 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jgambarios** [comment]
**Note to QA:** 

The work done in this ticket includes changes to make the CLI Content Type descriptor more friendly for the end user:
1. **CLI:** Now we display, for Relationship fields, an enum name for the relationship cardinality instead of a number. For example: MANY_TO_MANY, ONE_TO_ONE, etc.

    ```json
    {
      "clazz": "RelationshipField",
      "searchable": true,
      "indexed": true,
      "id": "e4c77c55-f7c8-4919-83bd-2601c2065ed5",
      "modDate": "2024-08-12T18:24:35.000+00:00",
      "name": "Reply",
      "variable": "reply",
      "sortOrder": 9,
      "fieldType": "Relationship",
      "fieldTypeLabel": "Relationships Field",
      "iDate": "2019-04-16T21:40:25.000+00:00",
      "dataType": "SYSTEM",
      "relationships": {
        "velocityVar": "BlogComment",
        "cardinality": "MANY_TO_MANY",
        "isParentField": true
      }
    }
    ```
2. **CLI:** The `systemActionMappings` is simplified by removing unnecessary properties and using the format that it is expected by the Content Type resource, example:

    ```json
      "systemActionMappings" : {
        "NEW" : "b9d89c80-3d88-4311-8365-187323c96436",
        "EDIT": "ceca71a0-deee-4999-bd47-b01baa1bcfc8",
        "UNPUBLISH": "38efc763-d78f-4e4b-b092-59cd8c579b93",
        "UNARCHIVE": "c92f9aa1-9503-4567-ac30-d3242b54d02d"
      }
    ```

Also, during the "cleanup" process the logic in the Content Type Resource related to the system action mappings was improved allowing to properly to add, edit and remove system action mappings.

**Comment by fabrizzio-dotCMS** [comment]
There is a little room for improvement here:
when pushing a content type like this: 

{
  "clazz" : "SimpleContentType",
  "id" : "e855a5dfeaed481dd4afd07b1bdac9d4",
  "name" : "MyTestContentType",
  "variable" : "MyTestContentType",
  "modDate" : "2024-08-27T19:06:04.000+00:00",
  "iDate" : "2024-08-27T18:27:45.000+00:00",
  "host" : "48190c8c-42c4-46af-8d1a-0cd5db894797",
  "folder" : "SYSTEM_FOLDER",
  "siteName" : "demo.dotcms.com",
  "folderPath" : "/",
  "icon" : "event_note",
  "baseType" : "CONTENT",
  "metadata" : {
    "CONTENT_EDITOR2_ENABLED" : false
  },
  "workflows" : [ {
    "id" : "2a4e1d2e-5342-4b46-be3d-80d3a2d9c0dd",
    "variableName" : "Blogs"
  } ],
  "systemActionMappings" : {
    "LOL" : "8d567403-a201-42de-9a48-10cea8a7bdb2"
  },
  "dotCMSObjectType" : "ContentType"
} 

If we send a value outside the range of valid labels "NEW", "EDIT", "UNPUBLISH", "UNARCHIVE" 
That bit of information is lost silently, without even reporting anything in the logs
it simply assumes the **actionMappings** fields is empty and therefore need to be removed

We need to validate that the labels we use are a valid input and wont cause any data loss

**Comment by fabrizzio-dotCMS** [comment]
Another two issues were found while testing this: 
https://github.com/dotCMS/core/issues/29762
https://github.com/dotCMS/core/issues/29765 
They seem to be merely UI

**Comment by bryanboza** [comment]
Fixed, tested in the last trunk // CLI 

New issues referenced on this card, we can close this one for now
