### ISSUE TITLE
Update LTS Telemetry plugin

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28689]
### Task

Update the telemetry plugin to all current LTSs (23.01, 23.10, 24.04) to version `24.05.29`

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
core updated with the Telemetry latest version https://github.com/dotCMS/core/pull/28940/files#diff-00c3714481f3658d556b10ceb2b41b48a545d16aa0d8176dee53516de21d3023R66

**Comment by erickgonzalez** [comment]
Also requires this change: https://github.com/dotCMS/core/pull/28975/files
