### ISSUE TITLE
 Editing Pages in UVE on Community Edition

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28709]
### Problem Statement

Users are unable to edit pages in the UVE (Universal Visual Editor) on the community edition of dotCMS. This issue prevents users from making necessary changes to their pages, impacting their ability to manage and update content effectively.

![image](https://github.com/dotCMS/core/assets/2641437/bfc73980-ec27-4d0e-9861-38e4aa011e59)

### Steps to Reproduce

- Enable the new v2 editor feature flag in a dotCMS instance
- Log into the dotCMS community edition with the necessary credentials.
- Navigate to some page 
- Attempt to edit an existing page.
- Observe that the editor never opens, we are just showing a blank page 

### Acceptance Criteria

We need to be able to edit pages without problems even if you are in the free version. 

### dotCMS Version

Tested on the last trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
# Passed IQA 

Now we can open the UVE without a license 

Docker Image: `[dotcms/dotcms:trunk_db33b31]`

## Screenshot
<img width="1512" alt="Screenshot 2024-06-03 at 2 08 05 PM" src="https://github.com/dotCMS/core/assets/63567962/cbd83ab2-2e24-4f1f-9d50-f7b75de35dac">

**Comment by bryanboza** [comment]
Another case here: 

We need to hide the option to add forms if you don't have license since forms is an EE feature. This is not happening on the legacy editor

![Image](https://github.com/dotCMS/core/assets/2641437/62e8ef0c-20fd-490b-8424-d9030505b7a6)

**Comment by rjvelazco** [comment]
@bryanboza  As you said, that's **Another case**. Shouldn't that be a new ticket?

If not, what are the criteria for knowing when a ticket is ready? This can help us to make a more accurate Internal QA

**Comment by rjvelazco** [comment]
Alright! I'm working on a fix: https://github.com/dotCMS/core/pull/28903
