### ISSUE TITLE
GraphQL: Make titleImage work with dotAssets

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28706]
### Problem Statement

When the `titleImage` of a page is taken from a dotAsset, a GraphQL Page API call to get the page which includes this `titleImage` as a part of the query fails with 500 error. 

Response from the GraphQL API:  https://gist.github.com/dsilvam/6391bf8c48d555537f18d055f6ecff3a
Stacktrace: https://gist.github.com/dsilvam/003ea3fd4d67d8424cc806bdd95d6843

### Steps to Reproduce

1. Bring up dotCMS with full starter
2. Edit the index page and assign a dotAsset to the "ogImage" under the "Social" tab. 
3. Request the page info with GraphQL with the query: 
```
query PageAPI {
  page(url: "/index") {
    title
    url
    seodescription
    titleImage{
      name
    }
    host {
      hostName
    }
    layout {
      header
      footer
      body {
        rows {
          columns {
            containers {
              identifier
              uuid
            }
          }
        }
      }
    }
  }
}
```

It will fail with 500 error. 

### Acceptance Criteria

- [ ] The `titleImage` field needs to resolve properly regardless of being an Image or a DotAsset. 
- [ ] Postman tests. 

### dotCMS Version

Master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Work as expected

**Comment by bryanboza** [comment]
Postman tests are not validating anything...

We are using the same approach in all the Postman tests we have at the moment, which is a significant error.

The GraphQL servlet always returns a 200 status code, so we will never get something different. For the extra validations in all the HTTP requests, we are doing something like this:
```
pm.test("'page' element includes the requested titleImage attributes", function () {
    var jsonData = pm.response.json();
    var page = jsonData.data.page;
    
    if (page && page != undefined) {
    pm.expect(page["titleImage"].name, 'FAILED:[titleImage.name]').equal("dotcms.png");
    pm.expect(page["titleImage"].idPath, 'FAILED:[titleImage.idPath]').include("/asset/dotcms.png");
    pm.expect(page["titleImage"].versionPath, 'FAILED:[titleImage.versionPath]').include("/asset/dotcms.png");
    }
});
``` 

In this validation if **(page && page != undefined)** , if we don't have the page in the response, we simply skip the validation. This means the test is designed to never fail.

**Comment by dsilvam** [comment]
Please remove the needs work. This is complete out of the scope of this card and it's the way we've implemented all the existing graphql tests. The tests have of course failed numerous times because of real bugs or changes in the data, etc, so no, that's not true that they are designed to never fail. 

I do see opportunity for enhancements but definitely not as part of this task, which was fixing a particular bug.

**Comment by bryanboza** [comment]
Agree the scope of this card are just for the test that are under the folder `Test DotAsset as titleImage` for all the other test we need to open a new card.

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker
