### ISSUE TITLE
When A Metric calculation fail should continue with the next Metric

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28702]
### Problem Statement

Right now when a Metric calculation fail all the process is stopped so the other Metrics are not calculated and the MetricSnapshot if not saved, so we need to continue the process even when a Metric fail. 

Right now we have a specific problem with a customer that have a old Postgres version and the API Metric Summary Query is failing for them so the MetricSnapshot is not been saved for this Customer.

### Steps to Reproduce

If is failing right now for a Customer who has a Old Postgres Version, I think it is not to easy to reproduce on a dev environment.

### Acceptance Criteria

The MetricSnapshot must be saved for this customer even if this Customer does not upgrade its Postgres version.

### dotCMS Version

Telemetry plugin lates version

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/58

**Comment by freddyDOTCMS** [comment]
Note to IQA:

what I did to test this was:

- Comment this lines:

https://github.com/dotCMS/core/blob/25dbabae5d58e69eb4f91a576869f644c127f1f9/osgi-base/system-bundles/pom.xml#L63-L76

Now the Telemetry plugins is not going to be a System Plugin anymore

- Build and start dotCMS

- Create a new MetricType SUbClass. with the follow code:
```

public class TestMetricType implements MetricType {
    @Override
    public String getName() {
        return "TEST_METRIC";
    }

    @Override
    public String getDescription() {
        return "This is a test";
    }

    @Override
    public MetricCategory getCategory() {
        return MetricCategory.DIFFERENTIATING_FEATURES;
    }

    @Override
    public MetricFeature getFeature() {
        return MetricFeature.LAYOUT;
    }

    @Override
    public Optional<Object> getValue() {
        throw new RuntimeException("This is a Big error");
    }
}
```

- Add this New class on the MetricStatColelctor class

https://github.com/dotCMS/com.dotcms.telemetry/blob/ffeb53dddd96e83353650d766c113158003c5265/src/main/java/com/dotcms/experience/collectors/MetricStatsCollector.java#L115

Add this line 

`
 metricStatsCollectors.add(new TestMetricType());`

- Build and Install the Plugin again, and Hit the Telemetry End point.
- Check the the TestMetric is included on the errors array

**Comment by dsilvam** [comment]
Passed Internal QA: Forcing an error on a metric does not prevent answering with the results of the other metrics. The error gets included in the "errors" array in the response.
