### ISSUE TITLE
Spike: Define Necessary API Endpoints for Site/Folder Field Integration

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28704]
### User Story

As a backend developer, I need to conduct a spike to identify and define the necessary API endpoints required for the Site/Folder field. This includes determining existing endpoints that can be utilized and identifying new endpoints that need to be created.

### Acceptance Criteria

- Conduct an analysis to determine the API requirements for the Site/Folder field.
- Identify and document existing endpoints that can be used for the Site/Folder field functionality.
- Define any new API endpoints that need to be created to support the Site/Folder field.
- Provide a clear plan for the creation and implementation of any new endpoints.

### Time Cap
- 2 days

### Proposed Objective

Documentation

### Proposed Priority

Priority 2 - Important

**Comment by nicobytes** [comment]
Just to add this endpoint is necessary to implement this field within the new edit content section, the previous version works like this:


Here are my questions: is there an endpoint to get all sites/folders in one request? Or does each folder trigger a request to get the children's?

**Comment by dsilvam** [comment]
Find out if we have endpoints, or need to create new, for:
1. Get site/folder field selected value for a contentlet -> **TBD**
2. List sites -> sites including system_host ->
```
GET {{serverURL}}/api/v1/site?system=true
```
3. List folders of a site (first level) ->
```
POST {{serverURL}}/api/v1/folder/byPath
{
    "path":"//siteName/"
}
```
4.  List folders of a folder (first level) ->
```
POST {{serverURL}}/api/v1/folder/byPath
{
    "path":"//siteName/folderName"
}
```
5.   Save site/folder field value for a contentlet -> **TBD**
