### ISSUE TITLE
Spike: Determine Best Method to Integrate Angular Dialog Component into Binary Field

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28703]
### Parent Issue

https://github.com/dotCMS/core/issues/27458

### User Story

As a front-end developer, I need to conduct a spike to determine the best method to integrate an Angular dialog component within a Binary Field. This will involve evaluating different approaches and identifying the most efficient and maintainable solution.

### Acceptance Criteria

- Conduct research on various methods to integrate an Angular dialog component into a Binary Field.
- Prototype different integration approaches to assess their feasibility.
- Evaluate each approach based on criteria such as performance, maintainability, ease of integration, and user experience.
- Document the findings, including the pros and cons of each approach.
- Provide a recommended solution with a clear implementation plan.
- Create the issue for the implementation

### Time Cap
- 1 Day top

### Binary Field
<img width="627" alt="Screenshot 2024-05-30 at 2 21 14 PM" src="https://github.com/dotCMS/core/assets/1909643/9ff0b62a-8e97-402d-9f82-0e272b529169">

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by nicobytes** [comment]
Checking the code, the plan will be to migrate the dialog component inside BlockEditor to UI lib, as a result we can reuse this component between Block Editor and Binary Field.
