### ISSUE TITLE
Update Nx to Latest Version and Angular to Version 18

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28714]
### User Story

As a front-end developer, I need to update Nx to the latest version and Angular to version 18. This involves ensuring that all builds, lints, tests, application builds, and CI/CD processes function correctly after the update.

### Acceptance Criteria

- Update Nx to the latest version.
- Update Angular to version 18.
- Verify that all build processes complete successfully without errors.
- Ensure all linting tasks run correctly and adhere to project standards.
- Run all tests to confirm they pass without issues.
- Verify that the build processes for all applications function as expected.
- Ensure the CI/CD pipeline runs smoothly and correctly deploys applications.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9f3fb00**, Docker, macOS 14.5, FF v126.0.1

**Comment by josemejias11** [comment]
**QA Comment**

https://docs.google.com/document/d/1oVjDkjTLup9jCAIikhg3RnEdSw7P66HO_Tf5KSlpXrE/edit

**Comment by josemejias11** [comment]
**QA Approved**

Results for the regression testing after the PrimeNG Update can be found here 

https://docs.google.com/document/d/1oVjDkjTLup9jCAIikhg3RnEdSw7P66HO_Tf5KSlpXrE/edit
