### ISSUE TITLE
Write Postman Tests for Generative AI Endpoints

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#28719]
### Parent Issue
https://github.com/dotCMS/core/issues/27973

### User Story
As a Java developer, I want to write Postman tests for the following Generative AI Endpoints:
- /api/v1/ai/text/generate (GET)
- /api/v1/ai/text/generate (POST)
- /api/v1/ai/image/generate (GET)
- /api/v1/ai/image/generate (POST)

### Acceptance Criteria
- Postman test collection includes tests for:
  - /api/v1/ai/text/generate (GET)
  - /api/v1/ai/text/generate (POST)
  - /api/v1/ai/image/generate (GET)
  - /api/v1/ai/image/generate (POST)
- Tests validate successful response status and structure.
- Tests include various valid and invalid input scenarios.
- Test results are documented and shared with the team.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
- Slack Conversation: [link]
- Support Ticket: [link]
- API Documentation: [link]

### Assumptions & Initiation Needs
- Access to the Generative AI endpoints.
- Valid API keys or tokens for authentication.
- Sample input data for text and image generation.

### Quality Assurance Notes & Workarounds
- Ensure that tests cover a wide range of scenarios including edge cases.
- Verify that the API responses match the expected structure and content.
- Perform regression testing to ensure no existing functionality is broken by these tests.

### Sub-Tasks & Estimates
1. Review API documentation for Generative AI endpoints (2 hours)
2. Set up Postman environment and variables (2 hours)
3. Write tests for /api/v1/ai/text/generate (GET) (3 hours)
4. Write tests for /api/v1/ai/text/generate (POST) (3 hours)
5. Write tests for /api/v1/ai/image/generate (GET) (3 hours)
6. Write tests for /api/v1/ai/image/generate (POST) (3 hours)
7. Validate tests with various scenarios and inputs (4 hours)
8. Document test results and share with the team (2 hours)
9. Update documentation to reflect the new tests (1 hour)

Total Estimate: 23 hours

**Comment by dsilvam** [comment]
@victoralfaro-dotcms Let's make sure we follow our Postman Testing Guidelines when writing all these https://docs.google.com/document/d/19DcBaTWXLMF21w8gjxJTV2SxcLZTysxINW2C4MvpIeY/edit#heading=h.sgaylykcd12p

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/28795
