### ISSUE TITLE
Remove systemLoadAverage from JVM report

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28742]
### Task

System Utilization does not make sense in K8 environment -> it is going away because in a containerized/orchestrated environment it reports on the entire k8 host which does not make sense.  It used to make sense when dotCMS was run  in a dedicated environment, but no longer.

![Screenshot 2024-06-03 at 11 40 01 AM](https://github.com/dotCMS/core/assets/934364/5de14642-e950-45c5-a4fe-77945df5f69c)

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED

* Docker Image: `trunk_2585d6d`

The `systemLoadAverage` attribute is no longer present in the `Host` section in the **Settings > Maintenance > System Info** portlet.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e483d1f**, Docker, macOS 14.5, FF v126.0.1
