### ISSUE TITLE
Rename "access_token" cookie as it is confusing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28747]
### Task

When we changed the "Remember Me" to use a jwt, we also changed the name of the remember me cookie to `access-token`. The problem with renaming it that, is that is makes users think that they can/should use it as a JWT Access token, when in fact, all it is doing is allowing for a "remember me" login flow.  This can make users, including experienced users, struggle to understand what the "access-token" cookie is used for and when it should be used (almost never) and how auth against  dotCMS headlessly.

Unlike the AUTH_TOKEN, the "remember me" cookie does a "full login" to dotCMS, and updates the user's "last login" date.  It also does not share the ability to be limited by ip/ip range, can't have custom expirey dates, etc.  And finally, it can't be used as a `Authentication: Bearer TOKEN` header token.

**Comment by erickgonzalez** [comment]
Tested. It's working as it should.

![Image](https://github.com/user-attachments/assets/c0a3c13c-7052-4a63-b73d-21aaacb79193)

**Comment by bryanboza** [comment]
Fixed, before the fix, is was called `access_token` 

![Image](https://github.com/user-attachments/assets/847b342b-eba0-478a-a391-2ade16c8f1ce)

After the fix now we have `rme`

![Image](https://github.com/user-attachments/assets/c421bc56-d317-4726-b65a-3c972070456e)
