### ISSUE TITLE
Preview/edit a page from search opens in New tab

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#28761]
### Problem Statement

It happens when you go to edit a page from the search and then click preview; it opens a new window.
It should open in the same window.

### Steps to Reproduce

Login to demo.dotcms.com

1. Click content ->Search -> Type -> Page
2. Select a page 
3. Click preview  ![image](https://github.com/dotCMS/core/assets/139247809/85af11e8-ab99-4dc4-a78f-3e75b460d15b)
5. Opens a new window

### Acceptance Criteria

It should open in the same window 

### dotCMS Version

23.10.24
24.05.31 (Current demo)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116401
https://dotcms.slack.com/archives/C035XMEDQ4F/p1716901391711789

**Comment by john-thomas-dotcms** [comment]
@fmontes can you comment on this?

It seems to me that opening in a new tab is the right behavior for pages (but not for other types of content), since pages are too big to fit in a modal well.

So, is it working as designed/expected?  And if so, should we change it to open in a modal instead?

**Comment by fmontes** [comment]
@john-thomas-dotcms no, it should definitely don't go in a modal, UVE needs to open in a full window.

@Neehakethi Where is this proposal coming from? is a support or customer requirement?

**Comment by erickgonzalez** [comment]
@fmontes , it looks like a customer complained about this. So if I understand correctly this is the expected behavior, when you click Preview (from the modal when editing a page properties) it should open in a new tab?

**Comment by fmontes** [comment]
@erickgonzalez Ah! I see the issues, is when you are editing the page props because under the hood is the same jsp it shows the Preview but technically is unusable because you are already in the "preview" which for a page is UVE.

If that's the case, I would say the fix is to hide the button when user is editing page props.

**Comment by fmontes** [comment]
@erickgonzalez but the way @Neehakethi is describing is from the content search.

**Comment by erickgonzalez** [comment]
@fmontes I think that we have 2 diff issues here, please take a look at the screen recording:

https://github.com/user-attachments/assets/cf7df0c2-40b5-42f1-af2b-873dbcdadef6

**Comment by fmontes** [comment]
@erickgonzalez 

Issue 1: I don't consider that an issue, that's why I am asking where is that coming from and why we consider it an issue, from my POV is a preference.

Issue 2: Agreed, we should hide the button.

**Comment by erickgonzalez** [comment]
ok, thanks @fmontes for the confirmation. So @gortiz-dotcms, let's only take care of the second issue, which will be hiding the preview button if you're already in edit mode.

**Comment by erickgonzalez** [comment]
Working as it should, now from the edit page, the Preview option is hidden.

![Image](https://github.com/user-attachments/assets/2a578b64-7d1b-4f00-8dab-5cf2d5fab208)
