### ISSUE TITLE
Language Fallback not working.

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#28769]
### Problem Statement

When navigating to a piece of content using a valid languageID different than the default, the content just doesn't load instead of falling back to the default language even when the fallback property is set to true in dotmarketing-config.properties. 

### Steps to Reproduce

- Create a file asset,  (I used an image.) 
- Go to the file's shortyUrl 
- Change language_id=1 to language_id=X (X Being a valid language id) 

### Acceptance Criteria

Should fallback to the default language if the content doesn't have additional languages set up, and the fallback property is set. 

### dotCMS Version

24.04 
Latest Agile 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116573

**Comment by erickgonzalez** [comment]
Not reproducible in 23.01 LTS

**Comment by bryanboza** [comment]
Fixed, tested on Docker [ trunk_635d690 ]
