### ISSUE TITLE
Unified close button in select fields

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#28775]
### Define the Problem

In TreeSelect and MultiSelect, when the filter is enabled, the Close button looks different.

### Who's Facing the Problem?

Content Editors

### Multi Select
![Screenshot 2024-06-05 at 4 58 59 PM](https://github.com/dotCMS/core/assets/7611944/228adb74-8a1e-4e12-9268-ceb0e4f0cf0f)

### TreeSelect
![Screenshot 2024-06-05 at 5 12 33 PM](https://github.com/dotCMS/core/assets/7611944/e645a07f-36e2-4501-9119-e7bab74901b5)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fac6b7a**, Docker, macOS 14.5, FF v126.0.1
