### ISSUE TITLE
dotAI: register EmbeddingContentListener

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28770]
### Problem Statement

The EmbeddingContentListener is not being registered after migrating the dotAI plugin into core. 

It was registered here in the plugin's activator.
https://github.com/dotCMS/com.dotcms.ai/blob/main/src/main/java/com/dotcms/ai/Activator.java#L188

This is important because it keeps the index in sync in push publish environments.

### Steps to Reproduce

1. Configure dotAI in the sender and receiver
2. Create an embeddings index for blogs on both.
3. Create and push a new blog
Error: only the embedding index in the sender will be updated while the one in the receiver should as well. 

### Acceptance Criteria

- [ ] Pushing a piece of content updates the embedding indices in both sender and receiver
- [ ] Push deleting a piece of content updates the embedding indices in both sender and receiver
- [ ] Integration Test

### dotCMS Version

24.04 LTS

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Only for 24.04 LTS

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/28834
