### ISSUE TITLE
Verify the layout editor is only available on Enterprise Edition

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28774]
#### URL:
 https://tuskr.live/project/20c40fe1-2ed8-4b8a-b405-63401ffc4b8f/test-case/472f41ac-b6da-422c-b072-f49f1bc40014

### Name:
 Verify the layout editor is only available on Enterprise Edition

### Pre-conditions
<p>Have a dotCMS instance running</p><p>Make sure your instance is on Enterprise Edition </p>

### Steps:
Create a new page or edit an existing one Try to edit the page layout 
Make sure a warn the license is required is showed 

### Expected Behavior: 
LIcense warning should be displayed

**Comment by prestonso** [comment]
@fmontes will add link to resolution of this.

**Comment by fmontes** [comment]
We fix this here: https://github.com/dotCMS/core/issues/29977
