### ISSUE TITLE
APIs return incorrect information for pages with fields using the variable name "description"

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#28785]
### Problem Statement

When making an API request for data from a page, the "description" field of the page does not get populated with the correct information. This only applies to fields with the specific variable name "description".

This impacts any users who are trying to use APIs to query page information about the "description" field

### Steps to Reproduce

1. Add a field "description" to the page asset content type
2. Create a new page, and populate the "description" field
3. Call the page API for the newly created page
4. The "description" returned in the API response will match the "title" field rather than the "description" field.

### Acceptance Criteria

Have the "description" field resolve to the expected value in API responses.

### dotCMS Version

Master branch, 23.10.24

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116553
https://dotcms.slack.com/archives/CSHTYUR7H/p1717690580891459
https://dotcms.slack.com/archives/C074RCMMQE9/p1717686574484629?thread_ts=1717684361.114839&cid=C074RCMMQE9

**Comment by erickgonzalez** [comment]
<img width="302" alt="Screenshot 2024-06-18 at 4 01 26 PM" src="https://github.com/dotCMS/core/assets/5278970/d910cd78-7482-4996-a339-d85148ff5103">

Working as it should now, the Description shows its value.

**Comment by bryanboza** [comment]
We need some work here:  

- We have double status code validation in almost all the requests. We are validating it at the folder level and again at the HTTP request level. Remember, every request is inheriting everything from the parent.

![Image](https://github.com/dotCMS/core/assets/2641437/9fd8b9c9-eb8c-428c-ba11-c2e90f049e06)

- In the create page request, we need to validate something in the response, not just the 200 status code.

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker //  Postman
