### ISSUE TITLE
QA: Organize and update the test cases listed in TUSKR

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28791]
### Task

Part of our methodology as a QA department is to be a streamlined team and provide all the necessary inputs to the developers to generate releases and be autonomous in QA tasks while ensuring the quality of our features.

The implementation of our new test case management system will help us achieve this goal. We need to have a clear list of test cases to provide the developers with a comprehensive set of tests for every feature in the system, allowing for autonomous QA within teams.

The system is ready to be used, so before start adding new test cases we need to start doing some maintenance and update to the existing test cases following some best practices

TUSKR url: https://tuskr.live/project

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- We need to avoid using abbreviations in our terminology (e.g., CTA).
- We need to avoid providing variable data, such as URLs or similar information, as this will depend on the environment of the person running the tests.
- We need to be clear in our steps so that any person, even without system knowledge, can run the test.
- We need to avoid assumptions; every detail is important in testing.
- We need to be clear on expected behaviors

**Comment by bryanboza** [comment]
@josemejias11 We need to log the status here as a comment, since the milestone for this card was on Monday, June 10. So log the status and pass it. 

Don't forget to add the labels as a regular card. `Next Release`

**Comment by josemejias11** [comment]
**Completed the work on this card.**
