### ISSUE TITLE
UVE: Contentlets created on variants are not saving correctly

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28799]
### Parent Issue

TBD

### Problem Statement

After creating a contentlet inside a variant we have different issues with the contentlet: 

### Image not showing on HTML but is showing on Content Palette:
![Screenshot 2024-06-07 at 11 12 42 AM](https://github.com/dotCMS/core/assets/63567962/1430b93c-c06a-4c1d-a3a2-35c3b744b0c2)

### Unable to open Edit Contentlet:
https://github.com/dotCMS/core/assets/144152756/342976f5-ca96-48c8-a2a6-d09f74256e72

### We can open the edit content in the old edit mode, but the image is not saved:

https://github.com/dotCMS/core/assets/63567962/aa6a38f0-733b-417d-b0b8-55a2afcbe73c

### Steps to Reproduce

1. Configure and run the Analytics app
2. Enable the UVE for your environment
3. Create an experiment for any page
4. Create a variant 
5. Go to that variant 
6. Create a contentlet and use it 
7. Click to edit the recently created contentlet
8. See the error

### Acceptance Criteria

We should be able to create, edit and reuse a contentlet inside a variant

### dotCMS Version

`trunk-latest`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

1. You understand how to use the UVE 
2. You understand how experiments work

### Quality Assurance Notes & Workarounds

No workarounds at the moment.

**Comment by john-thomas-dotcms** [comment]
@freddyDOTCMS can you please put details in this card about your investigation, and let us know if you think this should be handled by the UVE team or not?

**Comment by freddyDOTCMS** [comment]
We are not cleaning up the current Variant when get out of an Experiment, in the image you can see the the Session Storage has the as current Variant the Experiment's Variant, even when I am on the Browser Portlet

![image (6)](https://github.com/user-attachments/assets/6bed862a-ee26-4a8d-b53e-1cf07f2f60a6)

For example I go inside a Variant, the go out and create a Page, the age was created but inside the Experiment's Variant

it can be the root of all the problems that we have with Variant

**Comment by john-thomas-dotcms** [comment]
@fmontes please see Freddy R's comment above.

Summary: The variant id is not being cleaned up when you got to edit a variant, and then stop editing the variant (going back to the experiments config).

We haven't touched this code in quite a while, so we think that probably happened during some UVE changes.  And we'd like to make sure the UVE devs know how to handle experiments and variants since you're in this code quite a bit.  So, can your team take on the fix?

**Comment by fmontes** [comment]
@john-thomas-dotcms make sense, I'll take this back to Scout for further investigation and fix.

**Comment by zJaaal** [comment]
I found out something related to the session storage not being updated. 
I'll be working on this and will notify the details of the fix that I will implement. 

Thanks for the insights @john-thomas-dotcms @freddyDOTCMS @jcastro-dotcms

**Comment by zJaaal** [comment]
# Note to QA 

I recommend to test the edit contentlet in the site browser and the Query Tool.

You can get contentlets by variants in the Query Tool by using `+variant:<your variant id>` when you have results, you will be able to open the edit contentlet by clicking on the title, be sure to create content for variants inside the UVE first

**Comment by zJaaal** [comment]
While investigating I found out that the broken image on variants, could be related to the container/content type code inside the VTL, so we probably need to create a ticket to update the starter or if there is one, make a change in the VTL code to support variants.

cc: @fmontes @nollymar @john-thomas-dotcms

**Comment by valentinogiardino** [comment]
### IQA PASSED
Variant contentlets are working as expected.
Tested on `dotcms/dotcms:trunk_b919bba`.

#### Video

https://github.com/user-attachments/assets/22667198-f911-4fed-8c37-b690f1885fad

https://github.com/user-attachments/assets/582cff7d-2d9d-4657-bd25-8d91554ac171

**Comment by bryanboza** [comment]
We can fixx this for now, but we reported two new issues in this functionality Hola 
https://github.com/dotCMS/core/issues/30726 && 
https://github.com/dotCMS/core/issues/30727
