### ISSUE TITLE
SDK: Add Content API to Examples

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28807]
### Parent Issue

https://github.com/dotCMS/core/issues/28415

### Task

Make use of the footer component in the NextJS and Angular Example to create a design that uses the content API as source of content. 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- NextJS and Angular Example should show a footer with Content retrieved from the Content API using the new `getCollection` method.

**Comment by bryanboza** [comment]
Need to update the SDK, this is blocking the page render 

![image](https://github.com/dotCMS/core/assets/2641437/1fa8eb0d-0b34-4b2c-9f6e-f632ec3d9d9a)

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_1895cd3`]

### Angular Video

https://github.com/dotCMS/core/assets/72418962/b5672ecb-b2cf-49f0-b177-272a1b2d3a23

### NextJS Video

https://github.com/dotCMS/core/assets/72418962/01dd691f-5877-45eb-bcd2-6692a7db2bb6

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
