### ISSUE TITLE
[REST] : Updating the value of a checkbox via REST is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#28800]
### Parent Issue

https://github.com/dotCMS/core/issues/28664

### Problem Statement

If you have a Contentlet that has a checkbox field, uncheck it, and try to save the new data via REST, the change is not being persisted. When you retrieve the Contentlet once more, you'll see that the checked property is still present.

### Steps to Reproduce

- Create a Content Type with a title and a checkbox field.
- Create a Contentlet of such a type via REST where the checkbox is checked.
- Request the Contentlet via REST. You'll see the property in the response.
- Now, via REST, change the request to uncheck the checkbox; i.e., just do not pass it down in the JSON body.
- Request the Contentlet via REST once more. You'll see the property is still in the response, which is not supposed to happen. If you go to the **Content Search** portlet, you'll see that the checkbox is still checked.

### Acceptance Criteria

The REST endpoint should allow you to check/uncheck boxes as required. The saving of the checked/unchecked box works in the back-end because DWR classes are still being used in the current edit mode.

### dotCMS Version

Latest trunk

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

Unlike other fields, if you click a checkbox, that field is part of the Contentlet's data. If you uncheck it, it is removed from the Contentlet's map altogether.

It seems like the back-end is not handling what properties coming in via the JSON body are no longer there. In this case, it means the box was unchecked, and the saving process should reflect that.

**Comment by jcastro-dotcms** [comment]
After my research, I confirmed that **this is NOT a code issue**. Here's the reason why this is working as expected, and how checkboxes can be un-checked:

One of the cool things about our REST Content API is that you can pass down the values of all the fields in a Contentlet, or just a few of them. For instance, you can have a Contentlet with three fields:

1. Title - text
2. Headline - text
3. Checkbox Options - checkbox

And create it like this:

`POST {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH?indexPolicy=WAIT_FOR`
```json
{
    "contentlets": [
        {
            "contentType": "myTestContentType",
            "title": "Test Title",
            "headline": "My headline",
            "checkboxOptions": "option-1",
            "contentHost": "default"
        }
    ]
}
```
Which will create a Contentet with the `Checkbox Option` as checked. Now, if you want to update **ONLY** its title and publish it, just pass down the Contentlet's Identifier and its new title:
`POST {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH?indexPolicy=WAIT_FOR`
```json
{
    "contentlets": [
        {
            "identifier": "{UUID}",
            "title": "Test Title - UPDATED",
        }
    ]
}
```
This allows API users to not have specify all existing properties when updating a Contentlet, and update just a single value or a handful of them. In the case of the checkbox field, in this sample Contentlet, if you want to un-check the `Checkbox Option` checkbox, all you need to do is pass down a blank String as its attribute value, like this:
`POST {{serverURL}}/api/v1/workflow/actions/default/fire/PUBLISH?indexPolicy=WAIT_FOR`
```json
{
    "contentlets": [
        {
            "identifier": "{UUID}",
            "checkboxOptions": ""
        }
    ]
}
```
And that'll do the trick. If you attempt this by NOT passing down the `checkboxOptions` attribute, dotCMS will think that you don't want to update that property -- which is a totally valid and expected scenario -- and unchecking it won't work.

**Comment by rjvelazco** [comment]
Should we update our docs based on the @jcastro-dotcms [comment](https://github.com/dotCMS/core/issues/28800#issuecomment-2159266623), @jdcmsd?

**Comment by jdcmsd** [comment]
@rjvelazco Yeah, this is a really important behavior — one that I've been getting to know in the last couple of weeks while drafting workflow docs. It definitely needs to be stated explicitly.

I'll include it in the new workflow viewtool docs (velocity & JS), I'll add a mention in the workflow REST API Swagger docs. It could probably be high up on [this page](https://www.dotcms.com/docs/latest/save-content-using-workflows), too, which could do with some reorganization and tidying.

If there's anywhere else I've missed, let me know.
