### ISSUE TITLE
SDK: Improved Error Handling in SDK Client Library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28816]
### Parent
[28404](https://github.com/dotCMS/core/issues/28404)

### Task description
As a developer using the dotCMS SDK client library, I want to see informative error messages when there is an issue with a request, so that I can quickly identify and resolve the issue.

### Acceptance Criteria
- The SDK client library should display clear and descriptive error messages when a bad request occurs.
- Error messages should provide relevant information about the issue, such as authentication errors or malformed requests.
- The error messages should be displayed in a user-friendly manner that helps developers understand the nature of the problem.

### External Links
- Slack conversation: [Link to Slack Chat]
- Support ticket: [Link to Support Ticket]

### Assumptions & Initiation Needs
- The developer has basic knowledge of using the dotCMS SDK client library.
- The SDK client library is up to date and compatible with the latest dotCMS version.

### Quality Assurance Notes & Workarounds
- Test various scenarios that could result in errors, such as authentication failure or invalid request parameters.
- Ensure that error messages are displayed consistently and in a readable format.
- Provide documentation on how to troubleshoot common errors and workarounds.

### Sub-Tasks & Estimates
1. Update SDK client library to handle error responses -

**Comment by zJaaal** [comment]
## IQA Failed

The errors are looking great but we have an `[object Object]` error that we should clean up, looks like at some part of the error bubbling the environment is expecting an `string`. We should show error messages effectively in the console and in the environment the code is running. Also in the `404` error maybe we could change the `URL` in the error message for `path` since the parameter is called `path` in the SDK

### [object Object]
<img width="286" alt="Screenshot 2024-06-18 at 4 21 11 PM" src="https://github.com/dotCMS/core/assets/63567962/630ca1d3-9ff9-4dd9-99fa-dd01d172a5e6">

### 404
<img width="612" alt="Screenshot 2024-06-18 at 4 17 07 PM" src="https://github.com/dotCMS/core/assets/63567962/ae33f7ed-666c-41d3-9df8-54305bc28e93">

### 401
<img width="613" alt="Screenshot 2024-06-18 at 4 17 50 PM" src="https://github.com/dotCMS/core/assets/63567962/cb2798b7-fdd7-4907-a4ed-009c1649de22">

### 403
<img width="547" alt="Screenshot 2024-06-18 at 4 20 59 PM" src="https://github.com/dotCMS/core/assets/63567962/f5a4f931-ff99-4226-86c4-603aeeab4b07">

**Comment by KevinDavilaDotCMS** [comment]
I did the test and I can't see that error screen
When an error occurs from the SDK, the NextJS application displays the errors like this

Browser:
![Screenshot 2024-06-19 at 10 49 23 AM](https://github.com/dotCMS/core/assets/144152756/445a400c-fc4f-40ee-a8c3-570ed74e2c72)

Terminal:
![Screenshot 2024-06-19 at 10 49 48 AM](https://github.com/dotCMS/core/assets/144152756/d444cd2d-7b51-4d05-8f15-d0c481f50b83)

**Comment by zJaaal** [comment]
> I did the test and I can't see that error screen When an error occurs from the SDK, the NextJS application displays the errors like this
> 
> Browser: ![Screenshot 2024-06-19 at 10 49 23 AM](https://private-user-images.githubusercontent.com/144152756/341137979-445a400c-fc4f-40ee-a8c3-570ed74e2c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTMwNzUsIm5iZiI6MTcxODgxMjc3NSwicGF0aCI6Ii8xNDQxNTI3NTYvMzQxMTM3OTc5LTQ0NWE0MDBjLWZjNGYtNDBlZS1hOGMzLTU3MGVkNzRlMmM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxNTU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzY3ODBkODUwYWE4NzJiZDYyMGNlODk4NTZjZjQzZWFhNGU5MTBlNjQ0NGIwZjg1MTM5YmFmZTg0NjdmNzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tnKWJ0ZYoZsSCEikuZxqdr7SOZTuIJ2QWwN_7VtWgCE)
> 
> Terminal: ![Screenshot 2024-06-19 at 10 49 48 AM](https://private-user-images.githubusercontent.com/144152756/341138102-d444cd2d-7b51-4d05-8f15-d0c481f50b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTMwNzUsIm5iZiI6MTcxODgxMjc3NSwicGF0aCI6Ii8xNDQxNTI3NTYvMzQxMTM4MTAyLWQ0NDRjZDJkLTdiNTEtNGQwNS04ZjE1LWQwYzQ4MWY1MGI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxNTU5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YThmOTk0Mjc1OTcyNWJmZGYzZWFhMmY4NTllYzZiYTRmYmMxNzY3NWY1NzEwNDRhODM2YWM4MTc2YmMzMGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Ix_4f6hrE1a36JVozP2welvgkLPwVN1sfQcwW0oHDk)

## IQA Passed

I tested it again and you are right! Looks like a cache thing. 
<img width="1512" alt="Screenshot 2024-06-19 at 1 00 33 PM" src="https://github.com/dotCMS/core/assets/63567962/1792b9fd-0e4e-4982-aa46-038b8a373b95">

**Comment by bryanboza** [comment]
Fixed, now we are able to get the corresponding error to every case, we receive the error status code and the correct message. However we are not doing anything at FE level in the provided examples, every one need to take actions in case of every error. 

Tested on trunk [_2181d4a]
