### ISSUE TITLE
SDK: Add Vanity URL Support to Angular Example

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28815]
### Parent
[28401](https://github.com/dotCMS/core/issues/28401)

### Task description 
As a developer working on the dotCMS project, I need to add vanity URL support to the Angular example to showcase the vanity URL capabilities of dotCMS in Angular. Especially because Angular routing is client side, which makes it a little different from our example in next.js.

### Acceptance Criteria
The Angular example must include a feature that demonstrates the use of vanity URLs.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_ a66d047`]

### Video

https://github.com/dotCMS/core/assets/72418962/e4d8597a-376b-49f2-a55d-9119b6d45bff

**Comment by bryanboza** [comment]
Fixed, tested in the latest trunk [ _f036143 ]
