### ISSUE TITLE
UVE: Investigate Read-Only Permission Token for Rendering Pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28818]
### Parent
[28404](https://github.com/dotCMS/core/issues/28404)

### Task description
As a dotCMS developer, I need to research if we can use a read-only permission token to render a page and make content requests. This involves understanding how the token permissions work and identifying any limitations that may affect the rendering of a page in our specific use cases.

```[tasklist]
### Acceptance Criteria
- [ ] Render a page and content with read-only permissions
- [ ] Identify limitations affecting page rendering
```

### External Links
- None

### Assumptions & Initiation Needs
- Access to dotCMS documentation and resources.
- Knowledge of dotCMS user permissions and token functionality.
- Research read-only permission tokens in dotCMS (2 hours)

**Comment by KevinDavilaDotCMS** [comment]
Later on research, we can use a Token for a "Frontend" user to achive the "read-only" purposes (There is not really a "read-only", but works for our needs)
Like this:

![Screenshot 2024-06-19 at 1 51 01 PM](https://github.com/dotCMS/core/assets/144152756/a0b9d82e-d58f-4ab4-a27f-5b543da4eeaf)

More context [here](https://www.dotcms.com/docs/latest/rest-api-authentication#AppSecurity)

**Comment by fmontes** [comment]
@nollymar we can close this one, I'll be adding this findings to the doc.
