### ISSUE TITLE
Rules permission checkbox is not visible

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#28814]
### Problem Statement

- the checkbox is only 1px height visible and thus problematic to check 

### Steps to Reproduce

- go in 23.10lts in any permission tab (for this ticket go to Sites -> Permissions) and try checking Rules checkboxes
- go in the latest version in any permission tab and try to give Rules permissions

### Acceptance Criteria

- checkboxes should be there at the proper size and easy accessible (for example Sites Portlet, and Folder Permssions Tab).

### dotCMS Version

- 23.10 LTS
- latest version

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/CSHTYUR7H/p1717764093411219
https://dotcms.zendesk.com/agent/tickets/116623

![Image](https://github.com/user-attachments/assets/01f99252-ea3d-4661-b9c8-b0cb84a2a8a8)

**Comment by erickgonzalez** [comment]
Workaround:

Set the permissions via the Roles Portlet or the Users Portlet.

**Comment by oidacra** [comment]
@dsilvam @erickgonzalez

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_0a261ce**, Docker, macOS 14.5, FF v126.0.1

Issue is still happening when using FireFox.

![Screenshot 2024-08-05 at 11 11 37 AM](https://github.com/user-attachments/assets/982fb5a5-d88f-48c4-aac6-5c277d8fa28b)

**Comment by erickgonzalez** [comment]
@oidacra I checked this on Master QA `Version: 1.0.0-SNAPSHOT (8/4/2024 2:37 PM)` and am still having issues. The Content/Files or Rules option doesn't show up.
![Screenshot 2024-08-05 at 10 12 49 AM](https://github.com/user-attachments/assets/5954d347-cada-46e4-b7c7-5025a0fd1495)

**Comment by oidacra** [comment]
Changes implemented.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2e54089**, Docker, macOS 14.5, FF v126.0.1
