### ISSUE TITLE
SDK: `getCollection` Method has missing default values 

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28830]
### Parent Issue

https://github.com/dotCMS/core/issues/28415

### Problem Statement

The query for the Content API in `GetCollection` is missing default value for `live` and `languageId` fields

### Steps to Reproduce

Use the new Content API exposed in dotCMS Client and make a fetch with the `getCollection` method, in the network tab you should see that `live` and `languageId` do not have default values.

### Query Example

```javascript
     client.content
            .getCollection("Blog")
            .sortBy([
                {
                    field: "modDate",
                    order: "desc",
                },
            ])
            .limit(3)
            .then((response) => {
                console.log(response);
            })
            .catch((error) => {
                console.error(`Error fetching Blogs`, error);
            });
```

### Query sent by that call ( See that we are not sending live and languageId)

```javascript
{
    "query": "+contentType:Blog",
    "render": false,
    "sort": "modDate desc",
    "limit": 3,
    "offset": 0,
    "depth": 0
}
```

### Acceptance Criteria

The query should contain `+live:true` and `+languageId:1` as default values.

### dotCMS Version

`trunk-latest`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_1895cd3`]

### Video

https://github.com/dotCMS/core/assets/72418962/ca0cb4e2-88c9-40bd-b327-e285bdb750d9

**Comment by bryanboza** [comment]
Fixed tested on Docker [ dotcms/ trunk_635d690 ]
