### ISSUE TITLE
Block Editor: Bubble Menu actions and marks are not working

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#28839]
### Parent Issue

TBD

### Problem Statement

Users cannot set marks/styles from the bubble menu because they are not being applied.

### Steps to Reproduce

1. Go to the [demo site](https://demo.dotcms.com/dotAdmin/#/).
2. Edit a block.
3. Go to the block editor.
4. Select text
5. Try to use the Bubble Menu.

### Video

https://github.com/dotCMS/core/assets/72418962/685804a8-1713-412f-9198-25d6b15859a9

### Acceptance Criteria

Users should be able to set marks/styles using the bubble menu.

### dotCMS Version

master/trunk

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
## IQA Passed

Now the bubble menu and marks are working

Docker Image: `[dotcms/dotcms:trunk_1895cd3]`

### Screenshot

https://github.com/dotCMS/core/assets/63567962/cdd1523c-8dc8-4c4e-9864-7e87a5877961

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected. Tested on the latest trunk // Docker // FF
