### ISSUE TITLE
Category Child Permissions Not Loading

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28838]
### Problem Statement

Category child permission is not loading, and spinner always keeps spinning due to underline exception at [here](https://github.com/dotCMS/core/blob/7b5455093d336fec46849aee5d126f66bb1155a6/dotCMS/src/main/java/com/dotmarketing/business/ajax/PermissionAjax.java#L160)

https://github.com/dotCMS/core/assets/102758033/97531df8-062a-4d4d-a5eb-5806272a1680

### Steps to Reproduce

1. Create a top-level category
2. Within that top-level category, create one or more subcategories
3. Navigate to the permissions tab for the newly created top-level category and assign a role to it. Give the role view permissions and apply the changes.
4. Navigate to the permissions tab for the newly created sub-category. The permissions should be in an infinite state of loading.

### Acceptance Criteria

[here] (https://github.com/dotCMS/core/blob/7b5455093d336fec46849aee5d126f66bb1155a6/dotCMS/src/main/java/com/dotmarketing/business/ajax/PermissionAjax.java#L160) 

Should have a fixed, and category permissions should be viewable if parent category permissions have changed through assigning new roles.

### dotCMS Version

All including the current master

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116583

**Comment by erickgonzalez** [comment]
It's working as it should. Now, child category permissions show up.

![Image](https://github.com/dotCMS/core/assets/5278970/b6d379bf-a2e7-4a4e-95d6-cd7c949fd0f6)

**Comment by bryanboza** [comment]
Fixed, now it is working as expected
![Image](https://github.com/user-attachments/assets/444a7cb0-cf2f-43a7-8388-a63c261fef36)

Tested on trunk // Docker // FF
