### ISSUE TITLE
Pages Portlet Not Displaying Pages in Full Starter Configuration (starter-20240531)

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#28840]
### Problem Statement

The Pages portlet is not displaying any pages when using the full starter configuration (starter-20240531).

### Steps to Reproduce

1. Set up the application using the full starter configuration (starter-20240531)
2. Navigate to the Pages portlet
3. Observe the portlet to check if any pages are displayed

### Acceptance Criteria

The Pages portlet should display a list of all pages available in the application, allowing users to view and manage them.

### dotCMS Version

24.05

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2024-06-10 at 7 35 29 AM](https://github.com/dotCMS/core/assets/129882031/33e43b73-9837-4b03-8dec-7f4099d7f917)

**Comment by prestonso** [comment]
@josemejias11 Is this still happening in the latest starter version?

**Comment by josemejias11** [comment]
Hi @prestonso, 

No, this was fixed already the card just wasn't used for its purpose :D I'm closing it now.

Thanks!
