### ISSUE TITLE
Template Selection Issue on Pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28846]
### Problem Statement

Users are currently unable to select templates when creating or editing pages in the content management system. This issue prevents users from applying the appropriate layout and design to their pages, impacting the overall functionality and appearance of the website.

### Steps to Reproduce

- Log into the content management system with the necessary credentials.
- Navigate to the section for creating or editing pages.
- Note the pages comes without a template selection 
- Attempt to select a template from the available options.
- Apply the changes and try to edit again 
- Notice that the previous template selection is lost.

### Acceptance Criteria

**Template Selection Functionality:** Ensure that users can select templates from the available options when creating or editing pages.
**Consistent Template Application:** The selected template should be applied to the page correctly, reflecting the chosen layout and design.
**User Feedback:** Provide clear feedback or confirmation to users that the template has been successfully selected and applied.

### dotCMS Version

Tested on the last trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_ a66d047`]

### Video


https://github.com/dotCMS/core/assets/72418962/e2c1c9ff-dba3-4217-9d1f-106b37b16c6f

**Comment by bryanboza** [comment]
Fixed, tested in the latest trunk [_888802f] // Docker
