### ISSUE TITLE
[GraphQL] : Error when trying to retrieve a Block Editor field

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#28852]
### Problem Statement

An error is being thrown when trying to retrieve Block Editor fields via GraphQL queries.

### Steps to Reproduce

* Open up one of the Blog Entires in our Demo Site, for instance `French Polynesia Everything You Need to Know` , and copy its Identifier.
* Go to the **Dev Tools > GraphQL** portlet and paste the following query:
```graphql
query  {
  search(
    query: "+identifier:2b100ac7-07b1-48c6-8270-dc01ff958c69", 
    limit: 5, 
    offset:0, 
    sortBy:"title"
  ){
    identifier
    title
    blogContent
  }
}
```
* Run the query. You'll get the following error response:
```json
{
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'blogContent' in type 'DotContentlet' is undefined @ 'search/blogContent'",
      "locations": [
        {
          "line": 10,
          "column": 5
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
  "data": null
}
```

### Acceptance Criteria

We should be able to return information from Block Editor fields correctly.

### dotCMS Version

23.10 LTS up to latest trunk

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

This issue was found when validating the fix for this ticket and trying to retrieve Block Editor values via GraphQL:

- https://github.com/dotCMS/core/issues/28659

**Comment by prestonso** [comment]
This has been fixed, so closing!
