### ISSUE TITLE
UVE: Enhance configuration for clientHost query param support

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28858]
### Parent Issue

https://github.com/dotCMS/core/issues/28404

### Task

We need to make use of a new property inside the UVE App config to whitelist the URLs that can be used in the new `clientHost` queryParam.

```json
{
    "config": [
        {
            "pattern": "/blogs/(.*)",
            "url": "https://myspa.blogs.com:3000/",
            "options": {
                "devURLWhitelist": [
                    "https://myspa.blogs.com:3001/",
                    "https://myspa.blogs.com:3002/",
                    "https://myspa.blogs.com:3003/"
                ]
            }
        },
        {
            "pattern": ".*",
            "url": "https://myspa.com:3000/",
        }
    ]
}
```

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- We should be able to use the `clientHost` queryParam only when we config the dev urls
- If there is no configuration for the url passed through the `clientHost` queryParam, we should clean it from the url 

### Assumptions & Initiation Needs

- You understand how the UVE works in a developer perspective
- You understand how the queryParams and the UVE App config interact with each other
- You understand how to configurate the UVE App

### Quality Assurance Notes & Workarounds

No workarounds.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_1895cd3`]

### App Configuration

```json
{
    "config": [
        {
            "pattern": ".*",
            "url": "http://localhost:3000/",
            "options": {
                "devURLWhitelist": [
                    "http://localhost:3000/",
                    "http://localhost:57832/"
                ]
            }
        }
    ]
}
```

### Video

https://github.com/dotCMS/core/assets/72418962/62ea417c-2d1e-42fa-98d7-29f697103cac

**Comment by zJaaal** [comment]
> ### Passed Internal QA
> * Tested on docker: [`dotcms/trunk_1895cd3`]
> 
> ### App Configuration
> ```json
> {
>     "config": [
>         {
>             "pattern": ".*",
>             "url": "http://localhost:3000/",
>             "options": {
>                 "devURLWhitelist": [
>                     "http://localhost:3000/",
>                     "http://localhost:57832/"
>                 ]
>             }
>         }
>     ]
> }
> ```
> 
> ### Video
>  issue-28858-uve-enhance-configuration-for-clienthost-query-param-support.mov

We currently need the config to not have the last `/` at the end. I think we should fix that so I will send a PR for this fix

**Comment by zJaaal** [comment]
That behavior was fixed in this [PR](https://github.com/dotCMS/core/pull/28895)

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [dotcms/trunk_1895cd3]

### Video


https://github.com/dotCMS/core/assets/72418962/66cf0916-54a0-496d-97a1-d5b01771a934

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2b6105d**, Docker, macOS 14.5, FF v126.0.1
