### ISSUE TITLE
When page is locked, hover text still says "Lock Page" 

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#28855]
### Problem Statement

When editing a page, after locking the page the hover text for the lock icon still says "Lock Page" instead of "Unlock Page" 

### Steps to Reproduce

Go into the browser and open any page. Lock the page for editing, hover mouse over the lock icon. 

### Acceptance Criteria

When the page is locked, hover text should say "Unlock Page" 

### dotCMS Version

24.04.24
24.04.06

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Screenshot 2024-06-12 at 9 40 21 AM](https://github.com/dotCMS/core/assets/157033896/29c26520-6a46-40e8-ac6c-a04174f62ea5)

https://dotcms.zendesk.com/agent/tickets/116750

**Comment by erickgonzalez** [comment]
With the new UVE, there is no lock/unlock when editing a page. Let's fix this directly in 24.04 LTS.
