### ISSUE TITLE
UVE: Update Next.js Example to Latest Version

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28860]
### Parent
#28404 

### Task description
As a dotCMS developer, I want to update the Next.js example to the latest version so that we can showcase the most up-to-date features and best practices.

### Acceptance Criteria
- The Next.js example is updated to the latest version.
- All dependencies are up-to-date and compatible with the latest version of Next.js.
- The example runs without any errors or warnings.
- The updated example includes any new features or improvements that are available in the latest version of Next.js.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
Looks like @KevinDavilaDotCMS took care of this in this [PR](https://github.com/dotCMS/core/pull/28865/files) when working on the VanityURLs

**Comment by zJaaal** [comment]
## IQA Passed 

Looks like everything is working as expected after the update.

#### Screenshot

https://github.com/dotCMS/core/assets/63567962/8ae8a70e-85d4-4ca7-bd9e-80c865b2d001

**Comment by bryanboza** [comment]
Fixed, tested with the latest trunk and everything still working as expected after upgrade
