### ISSUE TITLE
CLI: push cmd for VTL file is getting overwritten in the server in the edit mode of a page

### ISSUE THREAD

**Issue by Millertaker** [dotCMS/core#28861]
### Problem Statement

I’m encountering an unusual behavior when I execute the` dotcli push` command. When I push a modification made in a VTL file and navigate to the page where it’s utilized as a widget, it seems like something is reverting the changes I uploaded to the server, causing an older version to appear. Interestingly, if I delete the rollback version, I’m able to view the changes I just uploaded.

https://github.com/dotCMS/core/assets/2975617/a4c2c40b-04ce-4688-ac7b-8b1824f0f7ce

### Steps to Reproduce

- Using the demo content
- Using a widget that pulls a `#dotParse` a VTL file in a page in edition mode
- upload a change for the VTL using `dotcli push -e`
- go back to the edit page an refresh
- the VTL is taking a roll back for al old version 

### Acceptance Criteria

The uploaded VTL should be updated on the server and not reverted to a previous state

### dotCMS Version

dotCLI 24.06.06
dotcms-core 1.0.0-SNAPSHOT

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
Not sure if the issue is in the CLI. I think the problem is in the Edit Mode

**Comment by Millertaker** [comment]
@nollymar should I change the title ?

**Comment by Millertaker** [comment]
btw, i wasn't experience this behavior when i use the webdav to update the vtl

**Comment by valentinogiardino** [comment]
When making a change to a VTL file in live mode and pushing it using `dotcli push` , the server correctly updates its **live version** and also considers this latest version as the **working version**. On the user's local setup, their live file matches the server's live file, but the local working file becomes desynchronized from the server's working file. If the user then makes a new push, the desynchronized local working file is considered as a new working version by the server.

To avoid this, the user needs to synchronize the working version by performing a `dotcli pull` from the server.
