### ISSUE TITLE
Implement Search Categories in the Sidebar of Category Field

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#28879]
### Parent Issue
#28493 

### User Story
As a user, I need to be able to search for categories by their name within the sidebar, so I can quickly find and select the categories I need.

### Acceptance Criteria
- Implement a search input in the sidebar for category names.
- Allow users to initiate the search by pressing enter or clicking the search (magnifying glass) icon.
- Display a loading (skeleton) animation while the search results are being fetched.
- Use PrimeNG components for the search input and results display (if apply).
- Ensure that search results are accurate and displayed in a user-friendly manner.
- Follow the Final design of the Figma
- Write and pass unit tests for the new search functionality.

<img width="1379" alt="Screenshot 2024-06-13 at 5 30 58 PM" src="https://github.com/dotCMS/core/assets/1909643/cbd6dbfe-4bf9-4766-b8e6-32791dbd2238">
<img width="1373" alt="Screenshot 2024-06-13 at 5 30 51 PM" src="https://github.com/dotCMS/core/assets/1909643/6b5a8cae-dad2-4c49-9452-428bc6d6b313">

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Assumptions & Initiation Needs
Assuming the server provides an API endpoint for searching categories by name. Access to design and translation resources is required.

### Quality Assurance Notes & Workarounds
Quality assurance should ensure that the search functionality works as expected, search results are accurate, and the loading state is handled correctly. Unit tests should cover the new search functionality.

**Comment by oidacra** [comment]
Blocked By https://github.com/dotCMS/core/issues/28881

**Comment by dsilvam** [comment]
Passed IQA. 
* Was able to search categories throughout the entire tree, including up to 5 levels deep.
* Search results can be selected and they properly appear on the right sidebar. 
* The searching takes place once you type at least 3 characters. 
* Upon removing the characters by hitting backspace or clicking on the x, the view rests back to the tree.
* Search results correctly include the Category Path.
