### ISSUE TITLE
Unable to add image via URL to the block editor

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#28874]
### Problem Statement

When adding an image to a block editor field using the Image URL tab, users are unable to publish the contentlet. The publish fails with the following error message.

Unable to populate contentlet from table columns for ID='eb45c4f560bac15da481e4fb55d75067', Inode='241d5864-a00d-4878-b792-0b44302c0c7a', Content-Type '1231478ae5f2ab30ceda688bef87c13a': An error occurred when refreshing Story Block Contentlet references: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
![Screenshot 2024-06-13 at 2 14 09 PM](https://github.com/dotCMS/core/assets/136110669/5a117f39-ca95-42f3-8a3c-c250e1d6f695)

https://github.com/dotCMS/core/assets/136110669/cb252256-cb5d-4b86-93e4-d2e26818e533

### Steps to Reproduce

Create a new content type with a block editor field
Create a new contentlet
Add an image using the Image URL tab (https://plus.unsplash.com/premium_photo-1667860900553-07649c42a314?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
Try to publish the contentlet

### Acceptance Criteria

Allow users to add images using the image URL

### dotCMS Version

24.04.24
Demo (24.06.06)

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116780

**Comment by jcastro-dotcms** [comment]
This issue is NOT reproducible in the latest master branch. It's very likely that the code changes for the following ticket:
* https://github.com/dotCMS/core/issues/28659

Solved this problem. As per discussion with @erickgonzalez , Support will take the fix from #28659 and will backport it to the required LTS to check if that fixes the reported issue.

**Comment by fmontes** [comment]
@weiyiwang-dotcms can you please confirm this?

**Comment by fmontes** [comment]
Closing @erickgonzalez will take care of this.
