### ISSUE TITLE
Deploy Angular Example

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#28887]
### Parent Issue

https://github.com/dotCMS/core/issues/28404

### User Story

As user, i want to see the deployed angular example in some page

### Acceptance Criteria

Users can access to the deployed example

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

- [ ] Deploy Angular example in Vercel

**Comment by fmontes** [comment]
Needs to update the env auth token
