### ISSUE TITLE
QA: Create the list of test cases for the new Locales functionality

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28882]
### Task

As part of the goals for QA team is to be a Enablement Team, that requires to provide all the necessary inputs and stuff to every team could be autonomous and stream-aligned. That's why we need to: 

Develop and document a comprehensive list of test cases to ensure the new Locales functionality as expected. The test cases should cover all possible scenarios, including positive, negative, and edge cases. These test cases will be used to validate the functionality, performance, and reliability of the Locales functionality.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- The list of test cases should be created on TUSKR 
- A detailed list of test cases is created and documented.
- Test cases cover all possible scenarios, including positive, negative, and edge cases.

**Comment by josemejias11** [comment]
**QA Comment**

Add/Edit Locales: 
https://github.com/dotCMS/core/issues/28477
https://docs.google.com/spreadsheets/d/1JhznbKf_j1l4uyI3jNQLIEkbzhiqQmeIMrXQsjRt4GM/edit?usp=sharing

**Comment by josemejias11** [comment]
**QA Comment**

Locales/Variables is currently on hold. Test Cases are saved in the above link.
