### ISSUE TITLE
QA: Create Test Cases for Categories Improvements

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28883]
### Task

Develop and document a comprehensive list of test cases to ensure the new Categories improvements function as expected. The test cases should cover all possible scenarios, including positive, negative, and edge cases. These test cases will be used to validate the functionality, performance, and reliability of the Categories improvements. Don't forget to make sure to validate the communication with the categories portlet as well.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- The test cases needs to be listed in TUSKR, the company's test case management system.
- A detailed list of test cases is created and documented.
- Test cases cover all possible scenarios, including positive, negative, and edge cases.

```[tasklist]
### Tasks
```

**Comment by josemejias11** [comment]
Related to https://github.com/dotCMS/core/issues/28493

**Comment by josemejias11** [comment]
**QA Comment**

Test cases added for categories 
https://docs.google.com/spreadsheets/d/15PS6Xau2BY-tN5FRJ--NonRiwsjZpD5MLYUetqgUwX4/edit?usp=drive_link
