### ISSUE TITLE
LanguageUtil.getLanguageId is always hitting the db 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28890]
### Problem Statement

It looks like this method  LanguageUtil.getLanguageId is always going to the database.
There's a cache but when it doesn't seem to be working as it should
I don't think the language is getting cached either. Therefore whenever we pass something invalid we hit the db
The recent changes introduced for Localization enhancements don't seem to be the cause of this issue

### Steps to Reproduce

I can track this using Integration tests 

### Acceptance Criteria

All languages requested should be cached if an invalid string is passed this should be cached as a 404 entry

### dotCMS Version

current master

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
No te to QA: This can be tracked using Glowroot 
Just make sure that SQL queries are not taking place over and over again
Additionally, if the DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE is on requesting content in a non-existing language should return the content under the default language

**Comment by jgambarios** [comment]
I focused only on the changes made in the PR, the `com/dotcms/rest/api/v1/content/ContentResource`, specifically the methods: `getContent` and `canLockContent` using the `DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE` property enable and disable, and using **glowroot**, I see not extra hits to the language table, looks like the cache is in place for the parts I tested.

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker
