### ISSUE TITLE
Content Resource v1 hits the db 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28897]
### Problem Statement

Every time we call the content resource v1
e.g. 
doing http://localhost:8080/api/v1/content/ed5ca85b87c3585a2be46056346ae091?depth=1
We are calling the db to figure out if the UUID that is getting passed is an identifier or an inode 
We need to use a lighter API that brings back such info using cache e.g. ShortyAPI 

### Steps to Reproduce
Hook up Glowroot on your install and revise the number of Queries over the inode and identifier. It should be stable and not incremental.  

Currently, there is a problem with the languages but it will handled on a this issue https://github.com/dotCMS/core/issues/28890

### Acceptance Criteria

take a snapshot before and after the fix and ensure the numbers in terms of DB access are steady proof that  cache is working

### dotCMS Version

current master 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment]
Note to QA:
This can be tested by hooking up Glowroot to your dotCMS install or using a docker image running already with GloowRoot 
The important thing to verify here is that when hitting the db the number of queries shown does not increment with every hit

for that purpose create a piece of and use the inode/identiier to build a URL as shown below

http://localhost:8080/api/v1/content/e9b53c47d1851b705f126e8d15c4dbda

Then open up Glowroot and verify the executed queries

**Comment by jgambarios** [comment]
Executing multiple times:

```http
GET https://local.dotcms.site:8443/api/v1/content/68456a2b-5e3d-4ebe-8a83-f15dd2a2fa36
Content-Type: application/json
```

Does not generate DB hits, cache looks for this endpoint. This was verified using glowroot.

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
