### ISSUE TITLE
QA: Need to estimate the effort to integrate the e2e project in to CI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28892]
### Task

Evaluate the current e2e project and estimate the effort required to integrate it into the Continuous Integration (CI) pipeline. The estimate should include an analysis of the current e2e setup, identification of required modifications, potential challenges, and a detailed breakdown of the tasks and time required for the integration.

Here the project:  
[dotCMS_e2e.zip](https://github.com/user-attachments/files/15842054/dotCMS_e2e.zip)

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- Review the current e2e project setup and CI pipeline configuration.
- Identify the modifications needed to integrate the e2e tests into the CI pipeline.
- Outline potential challenges and dependencies that may affect the integration.
- Provide a detailed breakdown of tasks required for the integration, including:
- Modifying e2e tests for compatibility with CI
- Updating CI configuration files
- Setting up required environments and dependencies
- Running initial test integrations and troubleshooting
- Estimate the time and effort required for each task.

**Comment by prestonso** [comment]
Closing as stale per @wezell.
