### ISSUE TITLE
Create endpoint that given a list of categories returns them with a list of their parents

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28894]
### Parent Issue

https://github.com/dotCMS/core/issues/28493

### Task

Create an endpoint that does the following takes a list of categories (keys) and return them back with a list of parents for each of them. 

The list of parent cats will be returned as an array. It needs to include key, name, and identifier for each. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The endpoint functioning as stated. 
Include postman test.

**Comment by oidacra** [comment]
IQA: Passed

![Image](https://github.com/user-attachments/assets/a935042e-0084-46ef-b17e-3b941074a5f3)

**Comment by oidacra** [comment]
IQA Passed
POST to `/api/v1/categories/hierarchy`
body: 
```
{
    "keys": ["4100238e544eaf5ca1c944d6180025f3","ae9239ca63071ca1434c9879c57cbbb1"]
}
```

![Image](https://github.com/user-attachments/assets/ead88193-6c0a-4fe2-84f5-6a23256b2c13)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d501a60**, Docker, macOS 14.5, FF v126.0.1
