### ISSUE TITLE
Decrease the amount of data saved to calculate API Metrics

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28893]
### User Story

Right now, we intercept the API requests that we want to track. For each hit, we save a record in the metrics_temp table. Later, we summarize these records to calculate the number of hits happening each hour.

However, this method can produce a lot of data, especially as we add more APIs to track. To avoid storing too much data, we need to refactor our approach.

Currently, we calculate a hash for each request using the query parameters, URL parameters, and the request body. This hash allows us to identify unique requests.

Here are two possible solutions to reduce data storage:

1. Add a count field to the metrics_temp table:

- When a hit occurs, check if the hash already exists with the same metric name, feature, and category.
- If it exists, update the count (count = count + 1).
- If it does not exist, insert a new record with the count set to 1.

2.  Add a JSON field to the metrics_temp table:

- Use this JSON field to count the number of hits for each hash. The JSON structure would look like:
```

{
  "hash_1": 1,
  "hash_2": 5,
  "hash_3": 3,
  ...
  "hash_n": 5
}
```

- When a hit occurs, check the metric type (metric name, feature, and category).
- If it exists, update the JSON field for the request's hash.
- If it does not exist, insert a new record with the count set to 1 for this hash.

### Acceptance Criteria

Decrease the amount of Data storage to calculate the API Metric
Create technique documentation to explain how the API Metric works

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Closing this since we're going to change our approach to Activity metrics, using the Content Analytics infrastructure and methods instead.
