### ISSUE TITLE
QA: Migrate the Workflow Resource postman test to use JWT

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28902]
### Parent Issue
Related to #25581 

### Task

In order to maintain the tests, we need to migrate to the new auth method (JWT) and also try to group all the request in folders, this in the Workflow Resource collection. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

We need to do this migration respecting all the rules and best practices for postman collection

**Comment by prestonso** [comment]
Closing as stale per @wezell.
