### ISSUE TITLE
Create uber-jar "runner" to cli-build-artifacts.yml workflow stage

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#28916]
The new workflows are deploying to the libs-snapshot repo the cli jar, but only the base jar that does not include all the dependencies and is directly runnable.   This is only occurring in the release process by specifying the package type.   We should be publishing the both the regular jar and uber jar ( e.g. ends with -runner.jar ) into the snapshot repository so it can be directly pulled and run using "java -jar" 

MVN_PACKAGE_TYPE: 'uber-jar'
.....
./mvnw package -Dquarkus.package.type=${{ env.MVN_PACKAGE_TYPE }} -DskipTests=true -pl :dotcms-cli

The snapshot artifacts for cli can be found at this path

https://repo.dotcms.com/ui/native/libs-snapshot/com/dotcms/dotcms-cli/1.0.0-SNAPSHOT

Trying to download and run the current jar will not work. e.g. 

```
wget https://repo.dotcms.com/artifactory/libs-snapshot/com/dotcms/dotcms-cli/1.0.0-SNAPSHOT/dotcms-cli-1.0.0-20240618.050632-159.jar

java - jar dotcms-cli-1.0.0-20240618.050632-159.jar
no main manifest attribute, in dotcms-cli-1.0.0-20240618.050632-159.jar

```

When we are uploading correctly we will get a regular jar as before and another one with the -runner.jar extension.  This jar should be downloaded and tested that it runs as expected

**Comment by dcolina** [comment]
**Note to QA:**

You have to use this url [https://repo.dotcms.com/artifactory/libs-snapshot/com/dotcms/dotcms-cli/1.0.0-SNAPSHOT/](https://repo.dotcms.com/artifactory/libs-snapshot/com/dotcms/dotcms-cli/1.0.0-SNAPSHOT/) and pick up the latest version with suffix `-runner`, download it and then run the following java command:

`java -jar <downloaded-jar-file>-runner.jar`

**Comment by fabrizzio-dotCMS** [comment]
It's there:: 
![Screenshot 2024-07-22 at 11 59 46 AM](https://github.com/user-attachments/assets/2a9856f8-5972-467b-9384-e871ac3e7a2b)

**Comment by bryanboza** [comment]
Fixed, tested according the provided steps and this is working as expected.
