### ISSUE TITLE
Rules tab should not be visible to user with restricted access to Rules

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#28919]
### Define the Problem

- the customer wants the Rules tab to be grayed out or not visible to user whom they restricted access to Rules
- when access to Rules is restricted (from Permissions) the Rules menu remains active (not grayed out), and when the user tries to access it, we throw an exception:
```
User thomasa does not have permissions to VIEW Rules
Please contact an administrator...
```
- version: 24.04.24lts
- happens on latest version also
- https://dotcms.zendesk.com/agent/tickets/116746

### Who's Facing the Problem?

- the problem is encountered by the admin of the customer's platform, who's trying to restrict the access to Rules in a visual manner also

### Screenshot or Video

<img width="652" alt="image" src="https://github.com/dotCMS/core/assets/59923449/3b08f1cf-d9c5-4a68-be3f-0f3f422fe266">
<img width="153" alt="image" src="https://github.com/dotCMS/core/assets/59923449/a3031b16-bf22-49b5-b76d-d7e7b0321dec">

### Relevant Links and Resources

https://dotcms.zendesk.com/agent/tickets/116746

**Comment by dsolistorres** [comment]
Internal QA Approved:
- Rules tab is disabled now when the user doesn't have permission to edit rules:

<img width="84" alt="grayed-rules" src="https://github.com/user-attachments/assets/3c14bfe7-8747-4ff1-958b-57aad4247e25" />
