### ISSUE TITLE
feat: Enhancing the SAML by pass

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28910]
### User Story

As an user, I want to be able to add a parameter on the config properties that if set, will be used as a value on the ?native=true, replacing the true.

For instance, if  DOT_SAML_BYPASS_VALUE=Sanchez

it means any SAML request using native=true wont be longer valid, must be now native=sanchez to be by pass

### Acceptance Criteria

When the prop is set, the native=true should not work, will be replaced by native=xxx where xxx is the value set by props.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
I have added an env var such as 
SAML_BY_PASS_VALUE = sanchez

And this is the result (keep in mind the native=true, do not work if the SAML_BY_PASS_VALUE is set)

![Image](https://github.com/dotCMS/core/assets/19578350/1dec39a1-5741-4186-ac5b-40018deae754)

**Comment by dsilvam** [comment]
Passed IQA/QA: Tested on Auth. Set the bypass string to "apply" and it's working as expected. 
* `?native=true` not working - expected
* `?native=apply` working - expected
