### ISSUE TITLE
if a host/folder field is marked as required, then we do not allow/show SYSTEM_HOST

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#28924]
Parent Issue => https://github.com/dotCMS/core/issues/28494

### Screenhosts

if a host/folder field is marked as required, then we do not allow/show SYSTEM_HOST

![Image](https://github.com/dotCMS/core/assets/7611944/af7386d1-a674-425f-a7d9-883d1b8d3951)

if a host/folder field is marked as not required, then we do allow/show SYSTEM_HOST

![Image](https://github.com/dotCMS/core/assets/7611944/c7f0b52a-cd68-4615-bbbd-4a64d234a9ac)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_38272f6**, Docker, macOS 14.5, FF v126.0.1

**Comment by dsilvam** [comment]
Slack thread https://dotcms.slack.com/archives/CQMHM7PNJ/p1718727544373599
