### ISSUE TITLE
UVE: Editing Contentlet Outside Container Element

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28928]
### Parent
[28404](https://github.com/dotCMS/core/issues/28404)

### Problem Statement
When a user adds a contentlet element (div with all the data-attr) outside a container element, the Universal Editing Interface (UVE) crashes on pointer enter.

### Steps to Reproduce
1. In your webapp, fetch some contentlet from dotCMS, render ir inside a `<div>` and add all the data atrributes of a contentlet.
2. Add this outside the layout system, like in the footer.
3. Now edit this page and try to edit that outsider contentlet
4. See how the UVE crash.

```[tasklist]
### Acceptance Criteria
- [x] The user should be able to edit the contentlet even if it is outside a container element.
- [x] The UVE should not crash when the user interacts with the contentlet outside the container.
- [x] Make sure the fix works for both Angular and NextJS Example
```

### External Links
N/A

### Assumptions & Initiation Needs
- Assumption: The UVE crash is caused by the contentlet being outside the container element.
- Initiation Needs: Developers to investigate the code related to UVE interactions with elements outside containers.

**Comment by zJaaal** [comment]
## Note to QA

Right now the contentlets does not get updated after editing. We have a ticket raised for that. https://github.com/dotCMS/core/issues/28996

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/trunk_ c4b5b2f `]

### Video

https://github.com/dotCMS/core/assets/72418962/4eddae5c-55e4-4fee-a252-2b5e14f5be03
