### ISSUE TITLE
Unify API responses for Binary, dotAsset, FileAssets, File and Image fields

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28922]
### Parent Issue

https://github.com/dotCMS/core/issues/28857

### Task

Our current dotContentletTransformer uses Separate Strategies to render different types of files 
We have:

- FileAssetViewStrategy 
- FileViewStrategy 

And We also have a default mechanism that does a simple task including basic binary data in the Default Strategy

A Refactoring here is very desirable so we only have one simple class to centralize the File/Asset rendering logic 

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
I am going to close this because after our meeting we agreed on that I was going to create an EPIC for this.
