### ISSUE TITLE
If no value, we should default to current selected host

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#28925]
Parent Issue => https://github.com/dotCMS/core/issues/28494

### Screenshots

If the siteFolder field is not required, it defaults to system host.

![Screenshot 2024-06-19 at 10 01 36 AM](https://github.com/dotCMS/core/assets/7611944/442e490d-87be-451f-acc8-4d5c8572b084)

 If the siteFolder field is required, it defaults to current host

![Screenshot 2024-06-19 at 10 03 18 AM](https://github.com/dotCMS/core/assets/7611944/9a112eb8-76e3-4200-b527-d59842dd432e)

**Comment by dsilvam** [comment]
Failed IQA: 

1. Marked siteFolder as required
2. Opened new content dialog. It correctly had pre-selected the current site.
3. Hit save

If fails with the following error 

https://gist.github.com/dsilvam/dda940bc803b7b051ca10ee5b2eef116 
![Image](https://github.com/dotCMS/core/assets/1576794/869f1640-547a-4ee1-8d4e-a96082e6cec7)

**Comment by dsilvam** [comment]
Passed Internal QA: 
* Defaulting to System Host when the siteFolder field is not required
* Defaulting to Current Host when the siteFolder field is required. 

Being able to save/publish the content on both cases.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_6d3ea16**, Docker, macOS 14.5, FF v126.0.1
<img width="1350" alt="Screenshot 2024-06-21 at 1 05 05 PM" src="https://github.com/dotCMS/core/assets/129882031/60ff7bee-e6d3-4089-b0d4-6de07e9f61d2">
