### ISSUE TITLE
UVE: Config for `DOTCMS_HOST` should support `/` at the end of the URL

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28932]
### Parent Issue

TBD

### Problem Statement

Using the NextJS project as an example. If we set the var `NEXT_PUBLIC_DOTCMS_HOST` to something like `http://localhost:8080/` with an slash at the end instead of `http://localhost:8080` we get a 404 error or a broken page for every page.

### Steps to Reproduce

1. Make sure you can run the UVE in headless mode
2. Config the UVE App to run the NextJS example
3. Run the NextJS Example with the proper config
4. Go to your `.env.local` file and change the `NEXT_PUBLIC_DOTCMS_HOST` to your dotcms server but add an slash at the end 
5. Try to navigate to a page to enter the UVE inside dotCMS or navigate inside the NextJS Project
6.  See the error

https://github.com/dotCMS/core/assets/63567962/ce14a13b-9a0b-41c0-9808-1d9ad3ef8d60

### Acceptance Criteria

Project should not break if the user adds an slash at the end of the `DOTCMS_HOST` or not

### dotCMS Version

`trunk_latest`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

1. You understand how the UVE works 
2. You understand how the NextJS Example works

**Comment by fmontes** [comment]
Our SDK needs to handle trailing /

**Comment by fmontes** [comment]
@zJaaal https://www.npmjs.com/package/normalize-url

**Comment by zJaaal** [comment]
> @zJaaal https://www.npmjs.com/package/normalize-url

We also need to normalize the `clientHost` queryParam in the UVE. We could use this library in both SDK and core-web

**Comment by zJaaal** [comment]
> @zJaaal https://www.npmjs.com/package/normalize-url

I think we can solve this using the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL)

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in master
NextJS example:

https://github.com/dotCMS/core/assets/144152756/59bcd932-1a92-4f40-b41d-2b7c8b2de678


Angular example:


https://github.com/dotCMS/core/assets/144152756/2118db10-ccab-4463-a4fd-be876408c9be

**Comment by zJaaal** [comment]
We need to update the SDK to test this.

cc: @fmontes

**Comment by bryanboza** [comment]
Getting a 404 when I add the "/" to the url 

![Image](https://github.com/dotCMS/core/assets/2641437/628b6325-4c24-40b2-b4ac-2c74fc109ece)

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker
