### ISSUE TITLE
New Divider Button under Workflows should be under FF

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#28939]
### Task

The new divider button has been created for the new content editor. As the default setting for this feature is currently off, we should consider hiding this button under the new edit content FFs [`DOT_CONTENT_EDITOR2_ENABLED`, `DOT_CONTENT_EDITOR2_CONTENT_TYPE`].

![image](https://github.com/dotCMS/core/assets/5278970/36a00fbc-0ba9-4a6e-8268-3b3b2472d390)

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### Acceptance Criteria

The divider button shouldn't show if FF is off.

### Quality Assurance Notes & Workarounds

24.04 LTS is affected by this.

**Comment by rjvelazco** [comment]
## NOTE QA:

> The `DOT_CONTENT_EDITOR2_CONTENT_TYPE` is deprecated. We don't use it anymore.

To see the `add divider` you need to enable the `DOT_CONTENT_EDITOR2_ENABLED`.

**Comment by erickgonzalez** [comment]
@rjvelazco can I turn off that property in 24.04 LTS?

**Comment by dcolina** [comment]
Internal QA: Passed.

As we can see in the following videos, this feature works as expected.

It tested on macOS using the docker image `dotcms/dotcms:nightly_c6741bd`.

https://github.com/user-attachments/assets/e2f68c50-a6e0-468d-8dab-267cee497303
https://github.com/user-attachments/assets/8d9c2004-2829-4927-8738-6688aa40e39e

**Comment by bryanboza** [comment]
Fixed, now the divider is working under a FF... 

![Image](https://github.com/user-attachments/assets/4c665cac-ba8f-41e3-915f-ac80c90ae79e)
