### ISSUE TITLE
Improve Password Validation Error Message

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28941]
### Problem Statement

When users attempt to change their password and it is caught by the regex as invalid, the current error message is not clear. Users need a clear, two-line error message that explains the issue with their password attempt, improving the user experience and guiding them to create a valid password.

Here some invalid examples: 

`D3l3t3. `
`D3l3t3.th1s!sss `

The current exception is too noisy and have multiple lines 
https://gist.github.com/bryanboza/79c333679c0b6f4e062f05659cf2a2b6

### Steps to Reproduce

- Log into the system with the necessary credentials.
- Navigate to the change password section.
- Attempt to change the password using an invalid password that does not meet the regex criteria.
- Observe the error message that is displayed.

### Acceptance Criteria

**Clear Error Message:** Ensure that the error message for an invalid password is clear and displayed on two lines.
**Detailed Guidance:** The error message should provide specific guidance on why the password is invalid and what the user needs to do to create a valid password.
**User-Friendly:** The error message should be user-friendly, avoiding technical jargon and focusing on actionable feedback.

### dotCMS Version

Tested on `trunk [ _5987d22 ]`

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by erickgonzalez** [comment]
The new message is showing more information as to why the password isn't valid.

![Image](https://github.com/user-attachments/assets/8cb3f6a5-959d-41bf-bb0c-c3108f1b7738)

**Comment by bryanboza** [comment]
Fixed, now we have a clearer error when you type an incorrect password.
