### ISSUE TITLE
UVE: Write Test Cases for Universal Visual Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28942]
### Task description
As a UVE developer, I need to write test cases for the Universal Visual Editor in dotCMS to ensure that all functionalities are working as expected.

### Acceptance Criteria
- Test cases cover all key functionalities of the Universal Visual Editor.
- Each test case includes a clear description, steps to reproduce, expected results, and actual results.
- Test cases are organized in a CSV file for easy reference and execution.

### External Links
- [The spreadsheet to complete](https://docs.google.com/spreadsheets/d/1E5wFboudqLZUO4yEH6905B-0zEyRlFFqf4I-tieEH1Q/edit?usp=sharing)

### Assumptions & Initiation Needs
- Access to the Universal Visual Editor in the dotCMS environment.
- Collaboration with the dev team to understand the expected behavior of each functionality.
- Knowledge of testing tools and techniques for web applications.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by rjvelazco** [comment]
[The spreadsheet [CSV File]](https://docs.google.com/spreadsheets/d/1E5wFboudqLZUO4yEH6905B-0zEyRlFFqf4I-tieEH1Q/edit?usp=sharing)](https://docs.google.com/spreadsheets/d/1E5wFboudqLZUO4yEH6905B-0zEyRlFFqf4I-tieEH1Q/edit?gid=369501277#gid=369501277) updated with 30+ Test cases. Can we consider this ticket `completed` @fmontes @nollymar ?
