### ISSUE TITLE
UVE: Ask user to create page if the language doesn't exist

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28958]
As a user, I want to be notified when selecting a language in the Universal Visual Editor that does not have a page version, so I can decide whether to create a new version in that language.

```[tasklist]
### Acceptance Criteria
- [x] The user should see a dialog box informing them that the selected language does not have a version of the page and giving them the option to create a new version in that language.
- [x] If the users select yes, we show the edit contentlet dialog to fill up
- [x] This should work exactly as it works in the old editor
- [x] We need to catch this in the URL if use try to access the page using que queryParam
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
- This is the PR where @oidacra did it for the old editor: https://github.com/dotCMS/core/pull/27311

### Assumptions & Initiation Needs
The user has access to the Universal Visual Editor and is trying to select a language without an existing page version.

### Quality Assurance Notes & Workarounds
This should work exactly as the old page editor.

**Comment by zJaaal** [comment]
## Note to QA

We have this [ticket](https://github.com/dotCMS/core/issues/29034) present for the templates

We should be sure that the dialog to decide whether or not to translate a page works as expected, any error with the creation of it should be another ticket since this implementation is the same as the old editor and the only thing that changed is that in the UVE we should not be able to open a page without translation before seeing this dialog.

**Comment by rjvelazco** [comment]
### Failed Internal QA

- Tested on docker: [`dotcms/trunk_ e2e9497`]

### Steps to reproduce


1. Create a Page in English.
2. Go to the`edit page` portlet.
3. Add a content.
4. Go to the language dropdown.
5. Click `Español` and create the page.
6. See the error.

**NOTE:**  In the old editor, we create the page and maintain all the content to it

### Video

**Comment by rjvelazco** [comment]
@nollymar @fmontes Should we keep this behavior or do we want the old editor behavior?

I think the correct behavior is "do not copy" the page but I added the label `QA: Failed Internal` because of the requirements (It should work as the old editor).

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [dotcms/trunk_ e2e9497]

The new editor is working as expected [Like the old editor]. `demo` is outdated

### Video - Old Editor Behavior


https://github.com/dotCMS/core/assets/72418962/254eb9f4-0551-443c-8dad-09d0248526ef

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_59c1326**, Docker, macOS 14.5, FF v126.0.1
