### ISSUE TITLE
Create a starter site example implementing a chatbot using dotAI

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#28956]
### Task

Customers are asking for information on how to create a chatbot with dotAI.

While we can document this, the simplest and fastest way to get customers up and running with a dotAI chatbot is with a code example,.  And the proper place to put that is in the starter site.

The example should:
* Update the dotAI App to set the Role, Text prompt, and Image prompt fields with values appropriate for the starter site (e.g. "You are TravelBot, an AI travel agent, helping people decide on what destinations and activities to plan for their vacation").
* Create a new embeddings index on the starter site for TravelBot, which indexes all travel-related content types (Blog, Destinations, Activities).
* Set the default embeddings index config (in the dotAI App config) to automatically update the TravelBot index.
* Create a new top-level (root) folder on the starter site named "TravelBot".
* Crate an index page in the TravelBot folder to allow users to chat with TravelBot.
* Implement a chat with the TravelBot on the new page.
* Add the TravelBot page to the main menu navigation on the demo site, as a new top-level menu item.
    * This should just require checking the "Show in Menu" property on the TravelBot folder.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

1. When dotAI is enabled, a user can navigate to the TravelBot page and have a conversation with the bot.
2. When dotAI is not enabled a user who navigates to the TravelBot page will see a message "TravelBot is build with dotAI, the dotCMS suite of AI features.  Please configure the dotAI App to enable dotAI and TravelBot."
3. When a new blog, Activity, or Destination content item is added, TravelBot should be able to respond to questions about those new content items within a short period of time (long enough for the new content to be added to the embeddings index).

**Comment by hmoreras** [comment]
QA Note: 

The bot is now under https://starter.dotcms.com/TravelBot/ 

**Ai APP configuration:** 

![Image](https://github.com/user-attachments/assets/883ae9b4-8dd0-4f00-8188-7b7ee3fbc86e)

**DotAi Embeddings Configurations:**  A new index named travelBot was created 

![Image](https://github.com/user-attachments/assets/b7f74b23-550c-4267-bf68-736aa7fd668c)

**Site Seach Index:**  A site search index was created, will run all days at 1am. 

![Image](https://github.com/user-attachments/assets/ae5c97a7-3e42-4941-a366-e5f221b24921)

**New Apivtl to get the token:**  https://starter.dotcms.com/api/vtl/ai

**Comment by victoralfaro-dotcms** [comment]
Tested on Docker local instance:
![image](https://github.com/user-attachments/assets/0b45e75c-8c32-4906-86e5-3180d2457259)
App isn't configured
![image](https://github.com/user-attachments/assets/06abef91-9275-48b0-b89f-19076b40bc0a)
TravelBot page message:
![image](https://github.com/user-attachments/assets/813254f5-e1b5-4ebd-8d92-2f1acb240c5c)

**Comment by hmoreras** [comment]
QA Note: use at minimum this startert: https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240724/starter-20240724.zip

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_0663736**, Docker, macOS 14.5, FF v126.0.1

Not able to perform any search using dotCMS AI tool
![Screenshot 2024-07-30 at 10 30 47 AM](https://github.com/user-attachments/assets/76aa9065-2993-4b18-9773-92df4eb38fee)
