### ISSUE TITLE
UVE: Page Preview Top Bar Cut Off

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28959]
### Problem Statement
When previewing a page in RRSS, the top bar is cut off and does not display properly.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/8c8411da-e1de-48c8-bb3a-ab1fa9c0e6f9

### Acceptance Criteria
- The top bar should display properly and not be cut off in the RRSS page preview.

### External Links
- None

### Assumptions & Initiation Needs
- Assumption: The top bar is meant to display fully in the RRSS page preview.
- Initiation Needs: Access to dotCMS RRSS section to replicate the issue.

### Quality Assurance Notes & Workarounds
- QA should verify that the top bar displays correctly in the RRSS page preview after the fix is implemented.
- Workaround: Users can still view the full top bar by checking the page on the device preview option.

**Comment by zJaaal** [comment]
## IQA Passed

Now the top bar shows correctly

Docker Image: `[dotcms/dotcms:trunk_743e6da]`

## Screenshot

https://github.com/dotCMS/core/assets/63567962/7fe1ba29-a2ca-4724-93ff-b45b33b317f0

**Comment by bryanboza** [comment]
Fixed, now this is working as expected 

![Image](https://github.com/dotCMS/core/assets/2641437/11145503-5adc-45a4-a3be-bdebf9e2b48a)
