### ISSUE TITLE
UVE: Clean Page API Response in the SDK `client.page`

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28962]
### Problem Statement
Currently, the response of the SDK page API includes `.entity` before the actual page data, which is unnecessary and causing confusion for developers.

```[tasklist]
### Acceptance Criteria
- [ ] The response of the `page.get` should be without `.entity`
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
# IQA Passed

Now the response is clean.

## Screenshots
<img width="673" alt="Screenshot 2024-07-10 at 5 30 10 PM" src="https://github.com/dotCMS/core/assets/63567962/51d740f8-25b6-4a6e-9306-01eb3ba219d6">

**Comment by zJaaal** [comment]
## Note to QA

If both Angular and NextJS are rendering the page after an `npm i` we should be fine, because we applied this changes to both examples and they should be running with them by now.

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker
