### ISSUE TITLE
UVE: Contentlet Controls Not Showing in Edit Mode When Back from Preview

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28960]
### Problem Statement
In UVE when a user goes to preview and then goes back to edit the contentlets, the controls are not showing, making it difficult for the user to edit the content.

### Steps to Reproduce
https://github.com/dotCMS/core/assets/751424/954a22b6-01f1-4ba0-8063-8c55196126f7

### Acceptance Criteria
- Contentlet controls should be visible in edit mode at all times for easy editing.

### External Links
- None

### Assumptions & Initiation Needs
- The issue is specific to the UVE environment.
- The controls were visible before going to preview mode.

### Quality Assurance Notes & Workarounds
- As a workaround, users can refresh the page to make the controls visible again.
- QA should verify that the controls are consistently visible in edit mode.

**Comment by zJaaal** [comment]
## IQA Passed

Now Contentlet Tools are showing after going to preview and back to edit 

Docker Image: `[dotcms/dotcms:trunk_2181d4a]`

### Screenshot 

https://github.com/dotCMS/core/assets/63567962/c7382a5d-a448-4766-859b-7bc5f80e9530

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes // Trunk // Docker
