### ISSUE TITLE
Option to switch between individual language publish/expiration dates, or use syspublish_date/sysexpire_date

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#28969]
### User Story

As a user, I want to be able to have an option I can change so that when I change a publish or expire date it reflects across all languages instead of how it currently works where each language publishes or expires on its own dates. 

### Acceptance Criteria

Some form of option for users to set so that when they update a publish or expire date, it updates across languages. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Ticket. https://dotcms.zendesk.com/agent/tickets/116822
Git issue of update that switched to individual languages https://github.com/dotCMS/core/issues/21518

**Comment by prestonso** [comment]
@nathan-hildebrandt Which version are you seeing this on?

**Comment by prestonso** [comment]
No response, so closing!
