### ISSUE TITLE
Update Telemetry Plugin use in core to the last version

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28985]
### User Story

We need to Update the core to use the last version of the Telemetry Plugins.

It include fix any error that could bring up and deploy the new Telemetry Version on artifactory

### Acceptance Criteria

The latest evrsion on core master must be using the last version of Telemrtry plugins

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/71

**Comment by dsilvam** [comment]
Passed Internal QA: Telemetry plugin working again as a system plugin.
