### ISSUE TITLE
dotAI throws Text Embedding Error 

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28990]
### Problem Statement

When trying to create Embedded indexes for contenttypes so it can throw error  when the request is invalid ([integer tokens](https://github.com/dotCMS/core/blob/91b81d316f8df2a05437398a0c67d50c9a64253b/dotCMS/src/main/java/com/dotcms/ai/api/EmbeddingsAPIImpl.java#L312)) then API doesn't return data object as JSONArray

### Steps to Reproduce

There are no exact steps to reproduce this issue. However when request is invalid ([integer tokens](https://github.com/dotCMS/core/blob/91b81d316f8df2a05437398a0c67d50c9a64253b/dotCMS/src/main/java/com/dotcms/ai/api/EmbeddingsAPIImpl.java#L312)) then API doesn't return data object as JSONArray and dotCMS logs shows

`api.EmbeddingsRunner: unable to embed content:3b75f5cfb2bc6687f3d6da94d26f86df error:JSONObject["data"] is not a JSONArray.`

Note: Current [master has slightly changed](https://github.com/dotCMS/core/blob/2181d4a4633cd3ca596dcc9d6a73d5fb7786381e/dotCMS/src/main/java/com/dotcms/ai/api/EmbeddingsAPIImpl.java#L413) way to retrieve results, but at the end If API doesn't return DATA object then it will fail with same error.

### Acceptance Criteria

If [OpenAIRequest.doRequest()](https://github.com/dotCMS/core/blob/91b81d316f8df2a05437398a0c67d50c9a64253b/dotCMS/src/main/java/com/dotcms/ai/api/EmbeddingsAPIImpl.java#L312) doesn't return a valid response, it should be handled appropriately and must log the reasons instead of failing because of "JSONObject["data"]" not being a JSONArray.
### dotCMS Version

24.04.24_lts_v2

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116783

**Comment by erickgonzalez** [comment]
23.01 LTS doesn't have AI.

**Comment by dsilvam** [comment]
Passed Internal QA: Tested with a content type with a title and a custom field that saves the value generated. 
Creating embeddings for that type correctly indexes the custom field value. 



![Image](https://github.com/user-attachments/assets/9bb10462-af69-44d7-a3a9-23a16310f6c3)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b1282fe**, Docker, macOS 14.5, FF v126.0.1

**Comment by erickgonzalez** [comment]
After looking the changes, it's required a couple more of PRs https://github.com/dotCMS/core/issues/28770 and https://github.com/dotCMS/core/issues/28721 so waiting on CS/CX to further steps to LTS.

**Comment by erickgonzalez** [comment]
I think all this needs to be backported:
- https://github.com/dotCMS/core/issues/27959
- https://github.com/dotCMS/core/pull/28781/files
- https://github.com/dotCMS/core/issues/28719
- https://github.com/dotCMS/core/pull/28929/files
- https://github.com/dotCMS/core/issues/28770
- https://github.com/dotCMS/core/issues/28721
- https://github.com/dotCMS/core/issues/28720
- https://github.com/dotCMS/core/issues/28990
