### ISSUE TITLE
Locale Variables: Implement the table

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29004]
### Parent Issue
#29003

### User Story

Create a table that displays all Locale Variables by row, and a column for each locale available. The column 'Locale Key' should be static as the start of the table; and the 'Action' column should be static as well and the last in the column.

### Acceptance Criteria

- A table is created that lists all Locale Variables by row.
- Each locale available is represented as a column in the table.
- The 'Locale Key' column is fixed as the first column.
- The 'Action' column is fixed as the last column.
- The table should be fully responsive and functional across all supported browsers and devices.
- Proper styling should be applied to match Dotcms patterns.

### dotCMS Version
master

### Proposed Objective
To enhance localization management by creating an intuitive and accessible table layout for viewing and managing locale variables.

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
Desing: https://www.figma.com/design/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=580-63159&m=dev 

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by john-thomas-dotcms** [comment]
We've decided not to implement this screen at this time.
