### ISSUE TITLE
Locales: Locale Variables screen

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29003]
Figma Demo: https://www.figma.com/proto/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?page-id=0%3A1&type=design&node-id=532-93392&viewport=-1747%2C-4187%2C0.26&t=fx8jP5j5bAGXSHbC-1&scaling=scale-down&starting-point-node-id=591%3A74769&show-proto-sidebar=1

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29004
- [ ] https://github.com/dotCMS/core/issues/29005
`\`\`

**Comment by josemejias11** [comment]
Locales/Variables Test Cases:

https://docs.google.com/spreadsheets/d/1D_f92Tw3f1mNA2RkyTnn3a0RgN7It5SW8AgY8dIB6ek/edit?usp=sharing

**Comment by john-thomas-dotcms** [comment]
It was decided that we won't implement this screen at this time.  Instead, legacy language variables will be automatically converted to content language variables, and will be manageable in the normal Content Search portlet (and custom Content Search portlets).
