### ISSUE TITLE
Fix Checkmark Display for Selected Category in Dialog

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29020]
### Task

As a front-end developer, I need to fix the display of the checkmark for the selected category in the dialog, ensuring that it is correctly aligned and visually consistent with the rest of the UI.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- Correctly display the checkmark for the selected category in the dialog's dropdown menu.
- Ensure the checkmark is visually consistent with the design system.
- Test the checkmark display across different browsers and devices to ensure compatibility.
- Handle any edge cases or errors that may arise during the implementation.
- Update relevant documentation to reflect the changes made.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="795" alt="Screenshot 2024-06-26 at 2 05 41 PM" src="https://github.com/dotCMS/core/assets/1909643/9dfbcfcb-5290-41d7-b640-5211f5d2b7ee">

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Worked as expected

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_8348dfb**, Docker, macOS 14.5, FF v126.0.1
