### ISSUE TITLE
[Layout] : Content disappears from page after Layout is updated

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#29035]
### Problem Statement

When a Contentlet is added to an HTML Page, and a new row is added to the current Layout, such a Contentlet disappears from the page.

If you check the `multi-tree` table in the database, you'll see that the value of the `relation_type` column is off. For instance:

<img width="1146" alt="Screenshot 2024-06-27 at 10 36 46 AM" src="https://github.com/dotCMS/core/assets/8779585/e37e1d04-9c39-49eb-8c8c-ba3d2d50a756">

Such a value should be a consecutive short number, not a number that seems to be a time in milliseconds.

### Steps to Reproduce

1. Create an HTML Page using the `Default Template (demo.dotcms.com)`.
2. Add a new Rich Text content to it.
3. Click the **LAYOUT** button. Add a new row at the top of the page's Layout. Leave it as is, using the `SYSTEM_CONTAINER`.
4. Click the **CONTENT** button. You'll see that the previous Rich Text is missing now.

### Acceptance Criteria

Updating the Layout of a new page must not cause it to drop its Contentlets.

### dotCMS Version

Latest master.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### NOT TO QA:

This issue is NOT reproducible anymore. It's not clear what specific code change could have fixed this, specially since there's been quite a few fixes in the last few months related to the Template Layout code.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9dea667**, Docker, macOS 14.5, FF v126.0.1
Unable to reproduce
![Screenshot 2024-09-09 at 2 15 42 PM](https://github.com/user-attachments/assets/6234e4d9-f122-41eb-974d-ad2c430229b2)
