### ISSUE TITLE
QA: Migrate the Image collection to use JWT and best practices in postman 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29039]
### Task

As part of the security and performance improvements in postman, we need to migrate the Image collection to use all the new quality standards. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- We need to  use JWT authentication 
- Need to group the request into folders
- Add the necessary documentation 
- Push to trunk 

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Collection link: https://github.com/dotCMS/core/blob/master/dotcms-postman/src/main/resources/postman/Image.postman_collection.json

**Comment by josemejias11** [comment]
**QA Comment**

Completed the work. Pending final review. 
[Image Review.postman_collection.json](https://github.com/user-attachments/files/16131588/Image.Review.postman_collection.json)

**Comment by josemejias11** [comment]
**QA Approved**

Completed with the PR https://github.com/dotCMS/core/pull/29488
