### ISSUE TITLE
Automatically notify UX designer of all new Front-end cards

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29032]
## Purpose:
* The design team needs to know when work is planned in different areas of the UX, so they can request design changes to meet broader UX goals and longer-term rocks.
* These requests need to come early in the process, so that point estimates for these cards can take into account any additional work requested by the design team.

## Task:
* Send a slack notification to the design team (currently Melissa R) whenever the Technology field on a Github issue is set to "Front-end".

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

* Melissa R receives a slack message for each card set to Front-end.
* At a minimum, the slack message includes:
    * A link to the github issue
* Ideally, the slack message would also include:
    * Issue title
    * Issue description
    * Assignee
    * Estimated points

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/29068
