### ISSUE TITLE
Swagger Documentation for `/v1/contenttype` Endpoints

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29037]
### Task

Update Content Type REST API resource with Swagger documentation. 

### Proposed Objective

Documentation

### Proposed Priority

Priority 2 - Show Stopper

### Acceptance Criteria

Content Type REST API endpoints on the API Playground should contain all necessary information to comfortably begin to use them, including:

- Tags
- Descriptions
- Parameter details
- Request body explanations
- Sample values where appropriate
- Return schema

![image](https://github.com/dotCMS/core/assets/102264829/cc26bc54-24e9-42dd-9cc6-0ea092dcdece)

![image](https://github.com/dotCMS/core/assets/102264829/ec29c163-cf8a-496f-b10b-74be5250c487)

![image](https://github.com/dotCMS/core/assets/102264829/476ed831-bba7-4a81-8cde-c4fb201f39e3)

![image](https://github.com/dotCMS/core/assets/102264829/127cbd9a-ea5b-4711-8ede-2a05c58a3f26)

**Comment by jdcmsd** [comment]
Redone, new and improved! No refactoring, all swagger!

**Comment by gavriella-dotcms** [comment]
Looks good! All of the documentation is shown on my API playground.

**Comment by bryanboza** [comment]
Hey @jdcmsd , this looks better now. However, I have a question about the responses section. I'm not sure if we should list all the possible response codes handled by the endpoint or if it should just be a basic summary of the happy path. Should we include responses like 400 or 401 as well?

![Image](https://github.com/user-attachments/assets/7311e4fc-ca0c-431c-84f6-db66a72d3d53)



![Image](https://github.com/user-attachments/assets/3b91a71d-ba77-4d9c-8c60-7c831d36d85b)

**Comment by bryanboza** [comment]
We can close this for now, a new discussion opened for the next L10 meeting
