### ISSUE TITLE
UVE: Unable to Edit GraphQL Generated Pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29045]
### Problem Statement
Users are unable to edit GraphQL pages in the Universal Edit mode (UVE) in dotCMS.

### Steps to Reproduce
1. Set headless nextjs pages in UVE
2. Try to edit a page inside the `/campaing/...` folders (those are generated by GQL)
3. Attempt to enter the UVE mode to make edits.
4. 404

### Acceptance Criteria
- All pages should be editable regarding how they were rendered.

### External Links
- Discovered debugging [this](https://dotcms.slack.com/archives/C06QKPWSB60/p1719514603571739)

### Assumptions & Initiation Needs
N/A

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/trunk_8348dfb`]

### Video

https://github.com/dotCMS/core/assets/72418962/bec64312-0755-4b6a-bf0b-e987fa155f6b

**Comment by bryanboza** [comment]
We are missing something here but I'm unable to open this page using the UVE editor: 

Tested on the last trunk // Starter 20240611

**Comment by fmontes** [comment]
@bryanboza we need to update the starter... in the meantime you can point this to starter.dotcms.com

**Comment by bryanboza** [comment]
Still getting the same error using the last starter: 

```
"CUSTOM_STARTER_URL": 'https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240709/starter-20240709.zip'
```

**Comment by rjvelazco** [comment]
@bryanboza Can you check the issue again? I'm not able to reproduce. I try three starters including `20240709`

### Video

https://github.com/user-attachments/assets/627a47fc-7772-4e7f-b2cc-541bb27c5a2c

**Comment by bryanboza** [comment]
This still failing for me: 

I'm using: 
- The last version of the NextJS example
- Trunk [ trunk_da61861 ]
- Starter:  "CUSTOM_STARTER_URL": 'https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240709/starter-20240709.zip'

App config on demo site: 
```
{
  "config": [
    {
      "pattern": ".*",
  "url": "http://localhost:3000"
    }
  ]
}
```

**Comment by bryanboza** [comment]
Fixed, now this is working as expected
![Image](https://github.com/user-attachments/assets/ef71dffd-9145-4b7d-b75f-7a76ab7c64cf)
