### ISSUE TITLE
Locales: Save sorting in the main table.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29040]
### User Story
Preserve the sort order while in the session in the Locale table, so when the user returns to the page, they see the data sorted in the way they defined previously.

### Acceptance Criteria

- The sort order is preserved and applied when the user returns to the page.

### dotCMS Version
master

### Proposed Objective
Enhance user experience by preserving the sort order in the Locale table, allowing users to return to their preferred view without needing to re-sort the data.

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by hmoreras** [comment]
Findings: 

- Keep the sorting by session required attrs in the table: `stateStorage="session" stateKey="state-locales-session"`
- the `sortField` and `sortOrder` in the table, present in other portlets and in the `dot-listing-data-table`, overwrite the `stateStorage`.

**Comment by hmoreras** [comment]
QA Note: 

1. Go to Settings - Roles & Tools, System and add the `Locales` Toot in the menu. 
2. Go to http://localhost:8080/dotAdmin/#/locales
3. Order the table by any column, leave the page and come back, the order should be preserved.

**Comment by nicobytes** [comment]
works fine! @hmoreras 

https://github.com/dotCMS/core/assets/7611944/f84afc05-957b-4a90-995a-dfdf06f195ce

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_54611c0**, Docker, macOS 14.5, FF v126.0.1

Icon for Locale is not changing when the column is selected for sorting
![Screenshot 2024-07-02 at 3 17 13 PM](https://github.com/dotCMS/core/assets/129882031/2cbbe877-d29a-4ce1-b09c-b11e73985237)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_eeca0f8**, Docker, macOS 14.5, FF v126.0.1
