### ISSUE TITLE
Fix translations in the add to bundle dialog.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29064]
### User Story
Fix the translations in the "Add to Bundle" dialog to ensure all text is accurately translated and displayed correctly in all supported languages.

### Acceptance Criteria
All text in the "Add to Bundle" dialog is accurately translated into all supported languages.

### dotCMS Version
master

### Proposed Objective
Enhance user experience by ensuring accurate translations in the "Add to Bundle" dialog, providing clarity and consistency for users in all supported languages.

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Image](https://github.com/dotCMS/core/assets/31667212/3bbb169e-df2f-4c64-a9de-7808d912d8b6)

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Now all the now all the text on the "Add to Bundle" Dialog is shown on the right langueges

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b00ffaf**, Docker, macOS 14.5, FF v126.0.1
