### ISSUE TITLE
dotcli - don't truncate the error messages

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29072]
### Problem Statement

Logging errors is a fine line between too much info and too little.  Using the `dotcli`, I am working through errors and I found that I cannot see the whole helpful error when something goes wrong
```
Found [1] errors during the push process:
[ERROR] ❗  Error pushing file [/Users/will/git/dotcms/websites/dotcms.dev/content-types/DotcmsDocumentation.json] for operation [ADD] - [ Status: (400) With error: {
  "message" : "Missing required informatio...
 HTTP 400 Bad Request: The server encountered an error processing the request.
```
the problem is that this is really the only part I care about:
```
 "Missing required informatio...
```

 I have to send in the `-e` flag to see the whole message.   We should only need the `-e` flag to get the returned json and the stack trace.  The error message should be shown if `-e` is not passed.

### Steps to Reproduce

Use the CLI to do something with an error.

See that the error message is truncated.  

### Acceptance Criteria

We should see less about the request and whole error message to make debugging easier.

### dotCMS Version

24.05

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by jgambarios** [comment]
### Note to QA:

The simple way to test it is to modify an existing Content Type descriptor and remove from it the `id` and `variable` properties, then generate a push.

Before the fix, this was the output:
```json
Found [1] errors during the push process:
[ERROR] ❗  Error pushing file [/Users/myuser/tests/CLI/content-types/Banner.json] for operation [ADD] - [ Status: (400) With error: {
  "message" : "Failed to create Content Type(s): Content type proper...
 HTTP 400 Bad Request: The server encountered an error processing the request.

run with -e or --errors for full details on the exception.
```

Now this is the output:
```json
Found [1] errors during the push process:
[ERROR] ❗  Error pushing file [/Users/myuser/tests/CLI/content-types/Banner.json] for operation [ADD] - [ Status: (400) With error: {
  "message" : "Failed to create Content Type(s): Content type property in fields can not be modified, use [4c441ada-944a-43af-a653-9bb4f3f0cb2b] instead"
} ]
 HTTP 400 Bad Request: The server encountered an error processing the request.

run with -e or --errors for full details on the exception.
```

**Comment by wezell** [comment]
Perfect, thanks @jgambarios

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me.

**Comment by bryanboza** [comment]
Fixed, this looks better now. 

Tested on trunk // Docker // FF
