### ISSUE TITLE
CLI: Apply layout fix logic for fields without structure

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#29087]
### Parent Issue

https://github.com/dotCMS/core/issues/28880

### Task

From the CLI, it is possible to send fields without a layout structure, meaning without rows and columns. In this case, we need to apply the same logic we have when deleting fields, where it “fixes” or actually creates an initial simple layout if no layout fields are provided.

Steps to Reproduce:

1. Send fields from the CLI without a layout structure.
2. Observe the resulting layout.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

The CLI should apply the logic to create an initial simple layout if no layout fields are provided.

**Comment by jgambarios** [comment]
**Note to QA:**

This ticket is part of the spike https://github.com/dotCMS/core/issues/28880, and at the end, all the tickets there can be tested as one.

The idea is to ensure that layout fields (such as rows and columns) can be used without issues when using the content type resource. The changes in the content type resource apply some automatic “fixes” to the fields. For example:

1. If no layout fields are sent, a basic layout is created for the content type.
2. If there are more than the maximum allowed columns under a row, the layout is automatically fixed by removing the extra columns and moving the fields accordingly.

**Comment by dcolina** [comment]
Internal QA: Passed.

This feature works as expected.

We created a new content-type (named ContentWithoutLayout) which has been defined with two columns without any layouts. The sample is attached.

[ContentWithoutLayout.json](https://github.com/user-attachments/files/16509064/ContentWithoutLayout.json)

After pushing the content through `dotCLI` tool, we can notice the new content-type has been created defining a default layout, as is shown below:



![Image](https://github.com/user-attachments/assets/2923e494-5e5c-4ee5-86d2-4bac6933b32e)

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // CLI
