### ISSUE TITLE
CLI: Remove layout attribute from Content Type descriptor 

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#29083]
### Parent Issue

https://github.com/dotCMS/core/issues/28880

### Task

In the CLI, we should remove the `layout` attribute from the content type descriptor. This attribute is used internally, and changes made to it won’t be reflected on the server, as this section is not even read by the `ContentTypeResource`.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

The layout attribute should not be present in the content type descriptor in the CLI to prevent confusion and ensure consistency.

**Comment by dcolina** [comment]
Internal QA: Passed.

As we can notice in the following video, the feature works as expected.

The object `layout` is not shown when we gets the CT through dotCLI. However when we hit the API resource directly the whole CT object is shown including the `layout` key.

https://github.com/user-attachments/assets/25e75413-32c6-4b37-805f-d3a4ca4beed9

**Comment by bryanboza** [comment]
Fixed, tested on the last CLI version
