### ISSUE TITLE
Uploaded file names get mangled

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29093]
### Problem Statement

If you upload OR drag and drop a file onto the content search the file name gets mangled - it looks like an encoding issue. 

The file name goes from:
`Screenshot 2024-07-02 at 3.34.58 PM.png`
to
`Screenshot 2024-07-02 at 3.34.58â¯PM.png`

### Steps to Reproduce

1. take a screenshot in osx
2. drag and drop it on the content search screen
3. See the file name after it uploads

https://github.com/dotCMS/core/assets/934364/6a442cec-f5d8-4c2d-b5dc-109ca21deca4

### Acceptance Criteria

The filename should remain the same as it was on your desktop

### dotCMS Version

24.07.02

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dsolistorres** [comment]
Unable to reproduce in latest master

**Comment by bryanboza** [comment]
Unable to reproduce!



![Image](https://github.com/user-attachments/assets/d5ce066e-a071-43ab-93ae-5fa537d61674)

**Comment by wezell** [comment]
@bryanboza did you test this in docker?

**Comment by jdcmsd** [comment]
Linking another related, resolved issue, just for recordkeeping:
https://github.com/dotCMS/core/issues/28462
