### ISSUE TITLE
Improve Thumbnails in Content Search Screen

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#29098]
### Define the Problem

Poor thumbnail quality for smaller images and SVGs
Smaller images are pixelated in thumbnail view (converted to 500px x 500px).
We shouldn't be converting SVG images to WebP. SVGs should always stay SVG to maintain their vector format.

### Who's Facing the Problem?

Content Contributors

### Screenshot or Video

<img width="1879" alt="Screenshot 2024-07-02 at 5 00 55 PM" src="https://github.com/dotCMS/core/assets/1561349/06b35678-d437-4b16-b4c3-78ff563f254d">

**Comment by fishsmith** [comment]
Also, the thumbnails shouldn't be cut off. The background should have the size set to "background-size: contain;" NOT "background-size: cover;"

**Comment by fishsmith** [comment]
<img width="1754" alt="Screenshot 2024-07-02 at 5 26 37 PM" src="https://github.com/dotCMS/core/assets/1561349/599c0a94-71ff-4876-868c-8e9e18490eb7">

**Comment by zJaaal** [comment]
# Note to QA 

Right now there's no way to know at a contentlet level, the sizes of an image to identify if it is an Icon or a big Image. This means that I didn't find a way to apply the same styles for small images that are not SVGs, right now this fix just work for SVGs which are mostly icons.

**Comment by rjvelazco** [comment]
## Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_ b00ffaf`]

### Video

https://github.com/user-attachments/assets/fdfe4f43-6b37-496c-9a9a-502d3b125d1f

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk and now it is working better regarding small images and SVG.
