### ISSUE TITLE
Implement Color-Coded Slack Notifications for GitHub Actions

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29097]
### Parent Issue

As part of our custom workflows, we generate different notifications every time a GitHub action is run. To improve clarity and ease of association with each workflow, we need to implement color-coded Slack notifications. This will help users quickly identify the type of workflow and its status.

### Task

As part of our custom workflows, we generate different notifications every time a GitHub action is run. To improve clarity and ease of association with each workflow, we need to implement color-coded Slack notifications. This will help users quickly identify the type of workflow and its status.

For now I suggest the following colors: 
- 🟣 : releases
- 🟠: CLI 
- 🔵: docker images 

![image](https://github.com/dotCMS/core/assets/2641437/26fc6072-106f-4f43-a50b-5f1a6f3ee81b)

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- **Color-Coded Notifications**: Implement color-coded Slack notifications for different GitHub actions to help users easily associate notifications with specific workflows.
- **Consistent Color Scheme:** Define a consistent color scheme for each type of workflow (e.g., green for success, red for failure, blue for informational updates).
- **User-Friendly Messages:** Ensure that the notifications include clear and concise messages, along with the color coding.
- **Documentation Update:** Update the documentation to guide users on the color-coding scheme and how to interpret the Slack notifications.

**Comment by wezell** [comment]
Low priority - let the platform team dictate their requirements.
