### ISSUE TITLE
UVE: Edit Contentlet is opening in the default language for any language

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#29095]
### Parent Issue

TBD

### Problem Statement

When we Drag and Drop a Content Type in a Page that is not in the default language, the Edit Content opens in the default language instead of the current language of the page.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/63567962/4c2a83ff-2ef6-465d-b7f6-147fa8457431

### Acceptance Criteria

We should open the Edit Contentlet with the current language of the page.

### dotCMS Version

`trunk-latest`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

- You understand how to use the UVE 
- You know how the languages in the UVE works

### Quality Assurance Notes & Workarounds

A workaround would be to change manually the language in the edit contentlet

**Comment by rjvelazco** [comment]
@nollymar We will need some backend work here. The endpoint we use to build the URL [`/v1/portlet/_actionurl`] does not support `language_id` as a query param.

I already have a [PR](https://github.com/dotCMS/core/pull/30442) with the frontend fix, we can work over that branch

**Comment by dcolina** [comment]
## Internal QA: Passed.

The reported issue could not be reproduced, confirming the functionality now operates as expected.. It was testing using the docker image `dotcms/dotcms:trunk_56e5870`.

A video has been attached for reference, demonstrating the current, correct functionality as proof that the issue has been fully addressed and verified.

https://github.com/user-attachments/assets/029d73b0-33d6-470c-aeba-b95c01022011

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk image and now it is working as expected.
