### ISSUE TITLE
CICD: Evaluate GitHub Webhooks to automate tasks in our GH project

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29100]
### Task

Recently, GH [released a feature](https://github.blog/changelog/2024-06-27-github-issues-projects-graphql-and-webhook-support-for-project-status-updates-and-more/) that might help us get rid of the annoying behavior of getting cards closed automatically when a linked PR gets merged.

We need to do some tests to see if GH webhooks can help us automate some tasks in the future or at least to move linked cards to the Internal QA column and reopen them.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by spbolton** [comment]
Example repo created here

https://github.com/dotCMS/dotcms-github-app

Demo recording : https://drive.google.com/drive/u/0/folders/1c7GPPuBYed8G2NLvXxjEWFnTCJvze-IN

**Comment by spbolton** [comment]
Added follow up task here https://github.com/orgs/dotCMS/projects/7/views/5?pane=issue&itemId=81051585
