### ISSUE TITLE
Metrics: Implement metrics for Content Type Fields 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#29128]
### User Story

As a Product Owner, I want to be able to have data available gathered from metrics related to usage of Content Type, so I can build reports from it and take better informed decisions about the product. 

### Acceptance Criteria

All the metrics included in this Epic must be: 
* Implemented
* Tested
* Available in the persistence layer for reporting. 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Tasks
```

**Comment by dsilvam** [comment]
This query gives us pretty much all the data we need: 
```
select field_type, count(*)
from field group by field_type
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/76/

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED

I can see all the counts for the different fields in dotCMS. For instance:
<img width="487" alt="Screenshot 2024-10-18 at 2 48 52 PM" src="https://github.com/user-attachments/assets/2550231d-734e-4278-8192-db63a8ecb9d8">
