### ISSUE TITLE
Modifying the Template breaks pages on the receiver

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#29148]
### Problem Statement

If you modify a template and PP it, the multi_tree table on the receiver won't be updated so the page will defer from the sender (or if the template originally had timestamp UUIDs, the page will be blank).

### Steps to Reproduce

1- Create a design template like this one:
![Screenshot 2024-07-05 at 1 58 14 PM](https://github.com/dotCMS/core/assets/5278970/154ecef2-d775-42c6-8d41-845e56ba83bc)
3- Create a page with that template
4- Add a few contents
5- PP the created page = Pages look the same on sender and receiver.
![Screenshot 2024-07-05 at 2 11 02 PM](https://github.com/dotCMS/core/assets/5278970/9d5de7b9-f56c-4e8e-af7b-fee3d3168e69)
6- Modify the template: Add a new box before the second row and should use the same container that will be on the second row.
![Screenshot 2024-07-05 at 2 14 36 PM](https://github.com/dotCMS/core/assets/5278970/1bfeb9c5-bdca-4756-bed7-a753188c0e97)
7- PP the template using the filter Everything and Dependencies.
8- Compare the pages; the one of the senders looks different from the one of the receiver.

**Sender**
![Screenshot 2024-07-05 at 2 18 14 PM](https://github.com/dotCMS/core/assets/5278970/a0733570-e334-4f7e-9d39-e829dc2bb3a9)

**Receiver**
![Screenshot 2024-07-05 at 2 17 53 PM](https://github.com/dotCMS/core/assets/5278970/7e468cac-8bf5-4f98-a737-7568d2406d8f)

**NOTE:**
The customer was coming from pretty old versions when template-containers UUIDs weren't sequential; when updating the template, it updated the UUIDs to sequential, so the page in the receiver shows blank due to the relation_type in the multi_tree table still using the old ones.

### Acceptance Criteria

The page should look the same on the sender and on the receiver.

When PP a template, if there were updates in the design, all pages that uses that template should be PP.

### dotCMS Version

Tested on 24.04.24 LTS and demo, but probably all LTS are affected.

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116560

### Quality Assurance Notes & Workarounds

The current workaround is that when PP a template, Force push all impacted pages.

**Comment by john-thomas-dotcms** [comment]
This has been going back and forth for a while (years), and we've taken several shots at this, but we always end up with use cases where things don't work as expected.  So, we're going to have an internal meeting to clearly define the different use cases and expected behavior.

See also: https://github.com/dotCMS/core/issues/27689

**Comment by john-thomas-dotcms** [comment]
See also: https://github.com/dotCMS/core/issues/27816

**Comment by dsilvam** [comment]
Passed Internal QA: 
After going through the steps described the pages are looking the same on both sender and receiver. 


![Image](https://github.com/user-attachments/assets/1176e14b-c0de-4436-bcb2-f05bd51ee288)
![Image](https://github.com/user-attachments/assets/f5ada1b7-cbc1-41a4-9575-87d8e6dccb3a)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e622545**, Docker, macOS 14.5, FF v126.0.1
