### ISSUE TITLE
Moving containers within a layout does not impact the position of the content.

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#29158]
### Problem Statement

When you move Containers in a Page that already have Contents, the Content should be relocated but Sometimes it is not happening 

### Steps to Reproduce

1. Create a Container:

- Name the container C1.
- Add the Generic Content Type to it with the following code: $!{dotContentMap.title}.

2. Create a Template:

- Add 2 rows to the template.
- Add an instance of C1 to each row.
- Name the template T1.

3. Create a Page:

- Name the page P1.
- Use the template T1 for this page.
- Add two Contentlets: A in the first row and B in the second row.
- Fill the Title fields of the Contentlets with the values A and B respectively.

4. Create a Second Page:

- Name this page P2.
- Again, use the template T1.
- Add the Contentlets A and B as before.

5. Modify Page P1:

- Return to page P1.
- Move the layout of the second row to the top.

6. Verify Content Position:

- Check that the positions of the Contentlets have not changed.
- A should still be in the first row, and B in the second row; they should not switch places.

### Acceptance Criteria

The Contentlets must be switched

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `nightly_c6741bd`

After moving the second row in P1's Layout to the top, the Contentlet inside it was moved as well. This is how page `P1` looks like after the layout update:

<img width="1135" alt="Screenshot 2024-07-22 at 2 45 48 PM" src="https://github.com/user-attachments/assets/06e2cfb7-0fa2-48e1-8d8b-f3540b61d310">

Notice how Contentlet `B` is now at the top of the page and `A` is at the bottom. And this is how page `P2` looks now -- same as when it was initially created:

<img width="1143" alt="Screenshot 2024-07-22 at 2 45 57 PM" src="https://github.com/user-attachments/assets/af74727b-447f-4398-95b2-2886cdc71bd0">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2c23184**, Docker, macOS 14.5, FF v126.0.1
