### ISSUE TITLE
UVE: Only Displays Up To 10 Personas

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#29161]
### Problem Statement

The UVE only allows users to select from up to 10 personas. When there are more than 10 personas, only ten will display and there is no pagination for displaying additional options

### Steps to Reproduce

1. Configure UVE App to allow for UVE to edit an Angular app
2. Create 11 personas
<img width="1512" alt="Screenshot 2024-07-08 at 10 28 09 AM" src="https://github.com/dotCMS/core/assets/136110669/59db231b-b10d-4a54-8884-289f87c3e126">

3. Create a page in dotCMS
4. Click on the persona selector in the editor
5. Only 10 personas will be displayed
<img width="1512" alt="Screenshot 2024-07-08 at 10 25 31 AM" src="https://github.com/dotCMS/core/assets/136110669/e5541dfa-5df4-43fa-b2de-1597ac8754a1">

### Acceptance Criteria

Allow users to select from any persona

### dotCMS Version

24.05.20

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
We need to add pagination to this selector.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_ e10a52b`]

### Video

https://github.com/user-attachments/assets/ce6cb03b-a206-4c2d-89a4-39d6bb4af5bd
