### ISSUE TITLE
Slow performance with imports in some cases

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29162]
### Problem Statement

We have seen some cases where importing content can take a long time.  Additionally, when importing content, it spins up a new thread, which does not report to glowroot, making identifying these issues difficult.  We need to optimize for this.

### Steps to Reproduce

Create a content type with 20 fields.  Run a csv import of a large amount of records for that type with glowroot attached to the dotCMS

There will be no glowroot reporting/traces to help identify slow code.

### Acceptance Criteria

We can add some blind fixes here but the real test will be if we can get the import to work nicely in an environment that is sized down.

### dotCMS Version

24.05

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment]
Let's test how this branch `issue-29162-slow-imports` behaves against this Content Type and CSV.

![Image](https://github.com/user-attachments/assets/0b381b8c-5b7f-4ef9-b67e-0702b9832908)


[CSV-Courses.csv](https://github.com/user-attachments/files/16353041/CSV-Courses.csv)



It shouldn't throw java heap

**Comment by erickgonzalez** [comment]
Tested Locally with -Xmx1G.

**Master** threw the following error before throwing the error imported 470 Courses:
```
Caused by: org.postgresql.util.PSQLException: ERROR: out of shared memory
2024-08-29 10:10:51   Hint: You might need to increase max_locks_per_transaction.
```

**Branch** imported 953 contentlets in 7 minutes and 6 seconds. (This is ok since the CSV has dupe courses).
```
16:18:20.442  INFO  action.ImportContentletsAction - -------- Starting Content Import Process --------

16:25:26.874  INFO  util.AdminLogger - UserId : dotcms.org.1 : class com.dotmarketing.portlets.contentlet.action.ImportContentletsAction : processAction : Importing Contentlets
```

**Comment by gortiz-dotcms** [comment]
### **Passed internal QA**

Tested in demo, the import process lasted 7 minutes and 2 seconds

`[12/09/24 12:41:26:783 GMT]  INFO action.ImportContentletsAction: -------- Starting Content Import Process -------- 
[12/09/24 12:48:28:528 GMT]  INFO util.AdminLogger: UserId : dotcms.org.1 : class com.dotmarketing.portlets.contentlet.action.ImportContentletsAction : processAction : Importing Contentlets`

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_5b70657**, Docker, macOS 14.5, FF v126.0.1

Import took less than a minute to complete.
