### ISSUE TITLE
fix jump in image generation for Binary fields

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29173]
### Problem Statement

1. There is a small jump when you open the ai image dialog from the binary field, do not happen from the block editor. 

https://github.com/dotCMS/core/assets/31667212/4d27361e-4ed3-4011-a49f-6b55be97e1bc
 
### Steps to Reproduce

1. enable IA plugin. 
2. display the IA button in the binary field. 
3. Open de AI image pop-up from the binary field. 
4. See the jump when first loads. 

### Acceptance Criteria

Should avoid the jump

### dotCMS Version

latest 

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

**Comment by nicobytes** [comment]
Fixed!

https://github.com/user-attachments/assets/6b393701-15e0-4774-958e-d3d70aafc084

**Comment by dsilvam** [comment]
Passed IQA: No more jumping.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b9d33eb**, Docker, macOS 14.5, FF v126.0.1
