### ISSUE TITLE
Implement Breadcrumb Navigation for Categories

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29184]
### Parent Issue
#28493 

### User Story
As a user, I need breadcrumb navigation for categories in the header of the listing, so that I can easily navigate back to parent categories. This breadcrumb should handle multiple levels by converting them to a menu when there are too many levels to display.

### Acceptance Criteria
- Display breadcrumb navigation in the header of the category listing.
- Show the path of parent categories for the selected category.
- Allow clicking on any breadcrumb to navigate back to the respective parent category.
- Implement a menu to handle and display multiple levels when the breadcrumb path is too long.
- Ensure the breadcrumb navigation is visually consistent with the design system.
- Write unit tests to cover the new breadcrumb functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### References

<img width="675" alt="Screenshot 2024-07-10 at 12 16 04 PM" src="https://github.com/dotCMS/core/assets/1909643/4e7c60f6-91ef-47ec-b8c4-68c96b8e3d01">
<img width="1022" alt="Screenshot 2024-07-10 at 12 16 12 PM" src="https://github.com/dotCMS/core/assets/1909643/dfbd7d37-d2f2-4b26-9ead-27228d6e0795">
<img width="982" alt="Screenshot 2024-07-10 at 12 16 19 PM" src="https://github.com/dotCMS/core/assets/1909643/838c292d-b993-41c1-a7bf-7434abe2707d">

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29360
- [ ] https://github.com/dotCMS/core/issues/29358
```

**Comment by oidacra** [comment]
IQA PAssed:
Works as expected

https://github.com/user-attachments/assets/dec66b9a-cd38-4f1c-a38a-08d5468f414c

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_003b2bb**, Docker, macOS 14.5, FF v126.0.1
