### ISSUE TITLE
Handle Empty Search and Error Message for Categories

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29185]
### Parent Issue
#28493 

### User Story
As a user, I need to see an empty search message when no categories are found during a search, so I know that there are no matching categories.

### Acceptance Criteria
- Display an empty search message component when no categories are found during a search.
- Ensure the empty search message is visually consistent with the design system.
- Implement the empty search component using PrimeNG (if apply).
- Handle different states (e.g., loading, idle, error) gracefully.
- Write unit tests to cover the new empty search functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Visua
<img width="1368" alt="Screenshot 2024-07-10 at 12 26 47 PM" src="https://github.com/dotCMS/core/assets/1909643/99f810f9-194f-4fdf-9194-861e62d3555e">
l
<img width="1365" alt="Screenshot 2024-07-10 at 12 26 54 PM" src="https://github.com/dotCMS/core/assets/1909643/dc94680f-a281-4e29-9c6d-d8cc3d0f92cc">

**Comment by dsilvam** [comment]
Passed IQA: Not found screen in place and showing when expected. 



![Image](https://github.com/user-attachments/assets/43837a67-cc07-4b16-83d2-f95ba80d53a8)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_6343d2b**, Docker, macOS 14.5, FF v126.0.1
