### ISSUE TITLE
Handle Empty Category Message

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29186]
### Parent Issue
#28493 

### User Story
As a user, I need to see an empty category message when there are no categories available, so I know that there are no categories to display.

### Acceptance Criteria
- Display an empty category message component when no categories are available.
- Ensure the empty category message is visually consistent with the design system.
- Implement the empty category component using PrimeNG (If apply).
- Handle different states (e.g., loading, idle, error) gracefully.
- Write unit tests to cover the new empty category functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Visual
<img width="1374" alt="Screenshot 2024-07-10 at 12 27 04 PM" src="https://github.com/dotCMS/core/assets/1909643/3833f592-599c-4e91-8edf-6cdd60a2e649">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d0406c0**, Docker, macOS 14.5, FF v126.0.1
