### ISSUE TITLE
Workflow API swagger doc, Part 1

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29189]
### Parent Issue

https://github.com/dotCMS/core/issues/28600

### Task

There's a lot of exciting work happening in the Workflow API, but it's so big that I've decided to break it up into two tasks.

This task encompasses the first ~20 endpoints in the file.

![image](https://github.com/dotCMS/core/assets/102264829/a11bb08f-67c5-44af-81bd-2cc2d974015c)

![Screenshot 2024-07-10 at 12 54 34 PM](https://github.com/dotCMS/core/assets/102264829/2b5d2b2e-dec2-44fa-9a9d-0af7273ef049)

### Proposed Objective

Documentation

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

If Postman doesn't freak out, we should be golden~

**Comment by gavriella-dotcms** [comment]
All test run successfully aside from firemultipart endpoints related to this [issue](https://github.com/dotCMS/core/issues/29211)

**Comment by bryanboza** [comment]
fixed, tested on master // docker // ff
