### ISSUE TITLE
commit hook does not work in Windows WSL (ubuntu)

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#29180]
@gavriella-dotcms is currently working on a Windows machine. 

We only support Windows currently in its Linux layer WSL a version of Ubuntu.   The commit hook has issues that make it not cross-compatible and only currently works on a Mac.

Using AI we were able to create a version that works, it just needs checking that it still works on Mac also

**Comment by gavriella-dotcms** [comment]
I ran `git commit -m " "` and was given this error "core-web/.husky/pre-commit: 123: Syntax error: "(" unexpected (expecting "fi")
husky - pre-commit hook exited with code 2 (error)"

**Comment by gavriella-dotcms** [comment]
I ran the command `git commit -m " "` on my Windows machine and was able to commit successfully. The command also downloaded the newest versions of Java, Yarn, Node, and Maven, as shown in the pictures below. 
<img width="884" alt="committest1" src="https://github.com/user-attachments/assets/bbbf13e1-e8c0-4aae-b478-df4e4cdd8e45">
<img width="869" alt="committest2" src="https://github.com/user-attachments/assets/11f855ef-42e1-42c9-80a3-fe1a66d7caa1">
