### ISSUE TITLE
Limit the Amount of Selected Categories and Add Show More/Show Less Functionality

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29183]
### Parent Issue
#28493 

### User Story
As a user, I need to see a maximum of two lines of selected categories in the input field, with a text button to show more if there are additional categories. When clicked, the button should display the hidden categories and change to "Show Less" to allow collapsing the view back to two lines.

### Acceptance Criteria
- Display a maximum of two lines of selected categories in the input field.
- If there are more than two lines of categories, add a text button indicating the number of hidden categories (e.g., "9 more").
- When the button is clicked, show all hidden categories and change the button text to "Show Less".
- When the "Show Less" button is clicked, collapse the view back to two lines of categories.
- Ensure the implementation is visually consistent with the design system.
- Use PrimeNG components for displaying categories and managing the show more/less functionality.
- Write unit tests to cover the new functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### External Links
# Collapsed
<img width="749" alt="Screenshot 2024-07-10 at 12 12 05 PM" src="https://github.com/dotCMS/core/assets/1909643/89a1ac2a-7a80-4869-9a1a-a51b0689c2ce">
# Expanded
<img width="742" alt="Screenshot 2024-07-10 at 12 12 17 PM" src="https://github.com/dotCMS/core/assets/1909643/8004509a-b0af-47c8-ad18-f9424fe1cc9c">

**Comment by oidacra** [comment]
IQA Passed

**Comment by bryanboza** [comment]
We need some work here, tested on trunk [ trunk_20af29a ] // Docker // FF

We are getting an error in console here and we are unable to see the changes 


![Image](https://github.com/user-attachments/assets/41ab0cac-97bb-40fe-b242-2905520ae457)

**Comment by oidacra** [comment]
Sorry for not specifying, this is only for the new Edit Contentlet

<img width="1974" alt="Screenshot 2024-07-12 at 5 58 52 PM" src="https://github.com/user-attachments/assets/7925e8f2-d718-4594-8910-9c7207e26bfb">

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_430f4c7**, Docker, macOS 14.5, FF v126.0.1

1. After selecting all of the parent cats and removing them from the list line, the cats remains selected on the column categories selector.

2. Removing the cats one by one should move the text to the far left side of the line and not leave padding.

https://github.com/user-attachments/assets/d6011724-e1af-4a53-8117-2c0781034748

3. Line should be removed after deleting all the cats
![Screenshot 2024-07-15 at 3 47 18 PM](https://github.com/user-attachments/assets/890ee3ce-3141-4e48-b815-86ce3428d465)

**Comment by dsilvam** [comment]
@josemejias11 the remove is out of the scope of this card and actually part of another card. This is about the "Show More / Show Less" based on the number of lines.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d501a60**, Docker, macOS 14.5, FF v126.0.1
