### ISSUE TITLE
Delete Selected Category from Input Tags

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29181]
### Parent Issue
#28493 

### User Story
As a user, I need to be able to delete selected categories from the input tags by clicking the 'X' on each tag, which should remove the category from the store.

### Acceptance Criteria
- Implement functionality to delete a selected category when the 'X' on its tag is clicked.
- Ensure that the category is removed from both the input tags and the store.
- Use PrimeNG components for displaying and managing the tags.
- Update unit tests to cover the new deletion functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement, State Management

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

**Comment by nicobytes** [comment]
QA Steps:

1. Create a content type with a category field
2. Add and remove categories in the side menu and directly delete the chip
3. Save the content

**Comment by oidacra** [comment]
IQA Passed.
Work as expected.
