### ISSUE TITLE
Rafael: Drop Everything and Learn Jul 10 - Jul 30

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29196]

**Comment by rjvelazco** [comment]
I learned about some behaviors/changes in v17/v18 Angular. Here are some interesting articles/videos:

1. [Announcing NgRx Signals v18: State Encapsulation, Private Store Members, Enhanced Entity Management, and more!](https://dev.to/ngrx/announcing-ngrx-signals-v18-state-encapsulation-private-store-members-enhanced-entity-management-and-more-2lo6)
2. [Model Feature](https://youtu.be/oYMm0VzzMYU?si=0enUH22smfYRE5UB)
3. [Zonless upgrade](https://youtu.be/Z9e6MPv4_PI?si=vEWAGgi09yJfPlI4)
