### ISSUE TITLE
Wrong url when exporting file asset

### ISSUE THREAD

**Issue by gortiz-dotcms** [dotCMS/core#29209]
### Problem Statement

When exporting a file asset, the field fileAsset is being exported with an invalid url e.g _/data/shared/assets/e/d/edcd8e9e-f4cf-483c-aa6b-68cc64a02116/fileAsset/test1.txt_

### Steps to Reproduce

1. Go to content search
2. Export file asset 
3. Check in the downloaded CSV the field **fileAsset**

### Acceptance Criteria

The file asset should be exported with the **File Link** value in the fileAsset field

### dotCMS Version

Current master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by dsolistorres** [comment]
Internal QA approved: the fileAsset field exported is the URL that includes the host name and the path for the file in the site.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fc4b777**, Docker, macOS 14.5, FF v126.0.1
