### ISSUE TITLE
SDK: Make @dotcms/client JavaScript library works in nodejs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29202]
### Problem Statement
The @dotcms/client JavaScript library is currently not working with nodejs, causing issues for users who want to use it in their nodejs projects.

### Steps to Reproduce
1. [Download](https://github.com/user-attachments/files/16179855/test-node.zip) this `test-node` app 
2. Go to the folder and `npm install`
3. Run `node index.js`
4. See the error.

```[tasklist]
### Acceptance Criteria
- [ ] SDK client should be useful in nodejs runtime.
```

### External Links
- N/A

### Assumptions & Initiation Needs
- Probably they way we're building needs more work.
- The JavaScript results is not minified or uglified (check the `node_modules`)
- Maybe we need a bundler?

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
Turns out this was a bigger problem, it was not only nodejs but:

1. Nextra (dotcms.dev)
2. Astro (@zJaaal is working on this one)

We needed to build the library `@dotcms/client` in commonjs and esmodule, we only had esmodules.

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested @dotcms/client at `0.0.1-alpha.32` version

#Notes to QA
-You need to [Download](https://github.com/user-attachments/files/16754438/test-node.zip) this folder
- Run npm install
- Then run `node index`
- You should be able to see the information on the page you requested, without any errors.
- You can run any client function without any console errors.



https://github.com/user-attachments/assets/94074ed7-8772-45dc-97df-8138b3f0429e

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and now I'm unable to see the error. 

Passed.
