### ISSUE TITLE
Add the only batch functionality to wf action

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29207]
### User Story

As an user I want to be able to include sub actions that runs only on batch
If an user choice a only batch actionlet, this will the show on edit will be disable and unselected.
and the task will only show on the content search and able to run by using the batch or right click contextual menu

### Acceptance Criteria

If any subaction only batch is part of an action, will perform the UI as mentioned above

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Passed Internal QA: Batch only actionlet added to an action makes the action not possible to check the "Show when editing".
The batch only actionlets by now are the four AI actionlets. 



![Image](https://github.com/user-attachments/assets/7455980f-8a5a-4726-8401-674a51f5c11b)

![Image](https://github.com/user-attachments/assets/f2be2ead-da09-4d6b-8455-6aba7d608207)


![Image](https://github.com/user-attachments/assets/e75da518-5dd5-472f-97c2-60bed6eb2a18)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4a03b35**, Docker, macOS 14.5, FF v126.0.1

**Comment by wezell** [comment]
This broke the drag and drop on the workflow subactionlets.

**Comment by dsilvam** [comment]
Closing in favor of https://github.com/dotCMS/core/issues/30236 not to alter the points of this card.
