### ISSUE TITLE
Intermittent Notify Assignee workflow action error on Task List

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#29214]
### Problem Statement

On occasion when using the Notify Assignee workflow action it provides a Bad Request error. The workflow action still seems to execute just fine but seeing the error message is raising concerns with the customer. 

### Steps to Reproduce

While intermittent, the issue occurs when User A has contentlets that they need to run a "Notify Spanish User" workflow action which

1. Notify Assignee 
2. Unlocks Content

to user B. 

### Acceptance Criteria

No longer displaying the error message when running this workflow action as it seems to be working correctly. 

### dotCMS Version

23.10

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117035
Start of slack conversation https://dotcms.slack.com/archives/C01N0AU1NUC/p1720028558420519

![bad-request-error (1)](https://github.com/user-attachments/assets/b3ddca53-268f-470d-b034-728856306b33)

**Comment by swicken-dotcms** [comment]
Notes: This is a WARN in the logs, we should not display this to the end user.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_98da66b**, Docker, macOS 14.5, FF v126.0.1
