### ISSUE TITLE
Copying a contentlet without having Edit Permissions causes copy to have incorrect permissions.

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#29213]
### Problem Statement

When a user who has full View, Edit and Publish permissions on a content type, but not Edit Permissions goes to copy a contentlet of that content type the copy goes through but does not apply the permissions of the original. This also throws an error in the log saying  "User id: XXXXXX does not have permission to alter permissions on asset XXXXXX"

The customer in question experiencing it does not see the contentlet they have copied as the permissions on the new contentlet do not match the users. 

### Steps to Reproduce

On the demo site I have created a content type called "Permissions Test" which has View, Edit and Publish permissions for the Back-End User Role. 

1. Create a user with the Back-End user role and any other required permissions to allow them to see the demo site. 
2. Create a contentlet of the "Permissions Test" content type. 
3. Open an additional tab to run the logs
4. Create a copy of the contentlet created to see the error. 

### Acceptance Criteria

Proposed by John one of the two following. 
1. When running the Copy Workflow, copy the permissions of the original content regardless of the current user's rights on Editting Permissions is
2. If the user has Edit Permissions rights then copy the original permissions. Otherwise, create new permissions on the new contentlet based on the current user's permissions, as if they have just created a new content item instead of copying one. 

### dotCMS Version

23.10

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117180

**Comment by erickgonzalez** [comment]
![Image](https://github.com/user-attachments/assets/cfe68c82-cdbc-41cd-b8b9-ba7193edc419)


Working as it should now, it copies the permissions.

**Comment by bryanboza** [comment]
Fixed, now we are coping the permissions too
