### ISSUE TITLE
API Playground locks up when opening endpoint with multipart form

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29211]
### Problem Statement

Opening up any Swagger UI endpoint in the API Playground that has a multipart form component causes the browser to hang.

https://github.com/user-attachments/assets/780273df-8cb2-4cc3-8c41-ade7c8d6b420

I'm not sure what could be causing it, though the lockup is clearly caused by an infinite loop fetching `openapi.json` over and over.

### Steps to Reproduce

1. Open API Playground
2. Expand any endpoint
3. Now expand any end point that has "multipart" in its summary or path
    - tab will lock up
    - dev tools network tab will show looping fetches

### Acceptance Criteria

Multipart form endpoints should load the same as any other, without unexpected fetch behaviors.

### dotCMS Version

Trunk, 24.07.05

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

**Comment by gavriella-dotcms** [comment]
I attached another example of my browser infinitely fetching openapi.json.

https://github.com/user-attachments/assets/dadea82b-d43e-4b5f-8df4-0300b49b2026

**Comment by jdcmsd** [comment]
@wezell had suggested that this might be fixed by updating our Swagger js bundle. I've been subjecting this idea to some preliminary tests, though I'm not sure I'm doing so in the correct fashion. My method:

- Clone and build a fresh Swagger UI repo
- Open up my dotCMS core repo and browse to `/core/dotCMS/src/main/webapp/html/portlet/ext/apiplayground`
- Replace `swagger-ui-bundle.js` and `swagger-ui-standalone-preset.js` with the versions in the `swagger-ui/dist/` folder
- Rebuild dotCMS

Unfortunately, this did not solve it. However, it may be that my method is not exhaustive of the various hooks that go into the API Playground, especially considering the use of plugins via Maven/jersey/et al.

I'll try to drum up some feedback on this.

**Comment by jdcmsd** [comment]
I tried again, but this time I also **cleared my whole cache** and it worked! Multipart issue gone. Important note is that the CSS file _also_ needs to be updated in this process, or else the titles end up looking an awful mess.

So, `swagger-ui-bundle.js`, `swagger-ui-standalone-preset.js`, and `swagger-ui.css` all need to be replaced with a newer version in `/core/dotCMS/src/main/webapp/html/portlet/ext/apiplayground`. 

I think we should also add some params to the three paths inside of `index.jsp` to better facilitate cache-busting for our users.

I can wrangle up a PR later today.

**Comment by valentinogiardino** [comment]
### IQA Passed Internal

- Tested on docker image: `[dotcms/dotcms:trunk_ 1c414a1]`
- The API Playground no longer locks up when opening an endpoint with a multipart form.

https://github.com/user-attachments/assets/939c9831-4763-4278-a39c-43945cd981c4

**Comment by bryanboza** [comment]
Fixed, unable to reproduce 

![Image](https://github.com/user-attachments/assets/33cbdb21-4437-40e9-b622-b920a337685f)
