### ISSUE TITLE
Telemetry: not getting data after last release of the plugin

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#29222]
### Problem Statement

Telemetry data gathering stopped after updating environments with the last version of the plugin,[ 24.06.19](https://github.com/dotCMS/com.dotcms.telemetry/releases/tag/v24.06.19).

### Steps to Reproduce

No particular steps, just that data stopped being generated right after updating environments with the lastest version of the plugin. 

### Acceptance Criteria

Have the plugin capturing data as expected. 

### dotCMS Version

All LTSs + Last version of the plugin: https://github.com/dotCMS/com.dotcms.telemetry/releases/tag/v24.06.19

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
PR:

core: https://github.com/dotCMS/core/pull/29504
Telemetry plugin: https://github.com/dotCMS/com.dotcms.telemetry/pull/73

**Comment by dsilvam** [comment]
Passed Internal QA: Working on the latest generated docker image. 
Job is sending the data to the production db and the endpoint is available and display data.
