### ISSUE TITLE
Attaching files feature on tasks is not properly working

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#29238]
### Problem Statement

- the attach file feature in the workflow task is not working properly
- the files get updated but they're unreachable (when you click on it, it won't open)
- tested on the latest 24.04.24v4 and 23.01 (customer's version)

### Steps to Reproduce

- create a new workflow task
- select the task and try to attach a file
- the file will upload but it's not accessible making it unusable

### Acceptance Criteria

- the user should be able to use the attach file

### dotCMS Version

- 24.04.24v4
- 23.01
- 23.10.24

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117200

**Comment by erickgonzalez** [comment]
It's working as it should; now we can attach files.

![Image](https://github.com/user-attachments/assets/edb2129e-2641-4b00-954e-95ca10d45de1)



![Image](https://github.com/user-attachments/assets/98f70d23-0e61-492f-a21e-a0c64290349e)

**Comment by bryanboza** [comment]
We need some work here: 

Tested in the last trunk and now this is working just in case you use assets, but if you try to use a dotAsset file we are getting an error here and broke the piece of content. Here the log: 
https://gist.github.com/bryanboza/8b6fed70c35a8a581a567997bd776232

https://github.com/user-attachments/assets/7473cd95-b927-4bd2-b2fb-3bd1ac785fac

**Comment by erickgonzalez** [comment]
Needs work.

Seems that we can now attach dotAssets successfully but the UI is broken:

![Image](https://github.com/user-attachments/assets/a0138be6-06d2-4f70-b8d0-7ab7d82754d2)

Also we need to change the src of the dotAssets since it's throwing 404: https://demo.dotcms.com/dA/309a1b3a03/content.2870dc34-bf5d-40c6-ac2c-735104d68f19?language_id=1

**Comment by erickgonzalez** [comment]
Working as it should. Now it lists the files ok and can access dotAssets and fileAssets.
![Image](https://github.com/user-attachments/assets/e0004b02-0eb4-4222-ba14-28577d6c0b2c)

https://dotcms-qa-master.dotcms.site/052bf2209b.jpeg

https://dotcms-qa-master.dotcms.site/dA/309a1b3a03/content.2870dc34-bf5d-40c6-ac2c-735104d68f19?language_id=1

**Comment by bryanboza** [comment]
Now this is working, but we’ve broken something else. We're unable to upload new files to attach. We need to address this issue to ensure all functionality is working as it should.


https://github.com/user-attachments/assets/f4899a6d-c25f-435d-95dc-3535633841e7

**Comment by erickgonzalez** [comment]
Working as it should, now you can upload files from the file uploader successfully.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected.
