### ISSUE TITLE
Edit Page: Incorrect handling of legacy relation_type in copyContent method

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#29234]
### Problem Statement

There is an issue with the copyContent method where the relation_type field is not correctly handled for old pages that have the value LEGACY_RELATION_TYPE in the database.

![Screenshot 2024-07-15 at 5 12 20 PM](https://github.com/user-attachments/assets/8a2ae960-9f0d-42e4-97b8-ccd1c93405d1)
![Screenshot 2024-07-15 at 5 12 28 PM](https://github.com/user-attachments/assets/694d270d-1013-4a26-8f2d-c2cebb9cb9f9)

### Steps to Reproduce

Steps to Reproduce

1. Open a page that has an old container with LEGACY_RELATION_TYPE.
2. Click on "This Page" and then "Copy and Edit".
3. Check the network tab and look for a request to copyContent.
4. The copyContent method should correctly handle the LEGACY_RELATION_TYPE by converting it to dotParse_1 for advanced templates or 1 for non-advanced templates.
5. The copyContent method does not convert LEGACY_RELATION_TYPE, resulting in incorrect behavior.

Workaround used : UPDATE multi_tree 
SET relation_type = 'dotParse_1' 
WHERE parent1 = 'Page ID';

### Acceptance Criteria

Conversion Handling: Ensure that the copyContent method correctly converts LEGACY_RELATION_TYPE to dotParse_1 for advanced templates or 1 for non-advanced templates during the copy operation.

### dotCMS Version

24.04

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116938

**Comment by freddyDOTCMS** [comment]
Note to QA: To force this bug, you need to:

- Create a Advanced Template, let called  T1, with the follow code:

#parseContainer('SYSTEM_CONTAINER','LEGACY_RELATION_TYPE')

- Create a Page, let called P1, using T1 Template.
- Create and Add a Contentlet inside the Page.
- Update in the Data Base the relation_type  value of the page with the 'LEGACY_RELATION_TYPE', you can use this Statement: update multi_tree set relation_type =  'LEGACY_RELATION_TYPE' WHERE parent1 = 'Page ID'
- Clean the dotCMS cache.
- Create a second Page and add the same Contentlet inside it.
- Open P1 on the Edit Page Portlet and try to Edit the Contentlet, when you be asked to Edit the Contentlet, select This Page.

After the change it is not going to fail but before the change it is going to failed.
You can do the same test for Advanced or Designer templates.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9bee608**, Docker, macOS 14.5, FF v126.0.1
