### ISSUE TITLE
UVE: Experiment Environment Variables Causing Loop in Next.js Example

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29235]
### Problem Statement
When there are experiment environment variables in a Next.js example, it causes the system to get into a loop while in UVE.

### Steps to Reproduce
1. Add this to your env.local (like the example)

```
NEXT_PUBLIC_EXPERIMENTS_API_KEY=analytic-api-key-from-dotcms-portlet
NEXT_PUBLIC_EXPERIMENTS_DEBUG=true
```

2. Run you next.js
3. Enable UVE
4. Edit a page
5. See the loop. 

```[tasklist]
### Acceptance Criteria
- [ ] No environment variables should cause a loop in the system.
- [ ] The Next.js example should function properly without entering a loop in UVE.
```

### External Links
- This is definitely related with https://github.com/dotCMS/core/pull/28982

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
@dotCMS/frontend @nollymar we need to tests here that the experiments implementation didn't break

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/dotcms:trunk_ 0a261ce`]

### Video 

https://github.com/user-attachments/assets/e518a645-94f0-4adb-89fd-f6931c5a4476

### Local `.env.file`

```.env.local
NEXT_PUBLIC_DOTCMS_AUTH_TOKEN=${YOUR_CUSTOM_API}
NEXT_PUBLIC_DOTCMS_HOST=http://localhost:8080/
NEXT_PUBLIC_EXPERIMENTS_API_KEY=analytic-api-key-from-dotcms-portlet
NEXT_PUBLIC_EXPERIMENTS_DEBUG=true
```

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
