### ISSUE TITLE
UVE: Bring related content of `contentlets` on a page

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#29252]
### Parent Issue

N/A

### Task

Include the param `depth` with value `3` in the page `request` to bring related content of `contentlets` on a page. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The page should come with the related content via the Relationship fields of `contentlets`

**Comment by fmontes** [comment]
Closing in favor of: https://github.com/dotCMS/core/issues/29263
