### ISSUE TITLE
Page API: Image field content gone when request page with depth

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29259]
### User Story
As a developer, I should be able to add content with relationships in the page and request it from the Page API without the values of the image field disappearing.

### Steps to Reproduce
https://github.com/user-attachments/assets/aca74863-66a4-4efa-9810-a61ac957534d

### Acceptance Criteria
- [ ] The page API response of the image field should have all the image information
- [ ] When request the page API with `depth > 1` the image content should not disappear from the content.

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
Static Content: "N/A"

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by wezell** [comment]
Similar to #28857

**Comment by fmontes** [comment]
![Image](https://github.com/user-attachments/assets/af1232c2-fea9-4c64-9c5d-b7319cc8d3fe)

**Comment by fmontes** [comment]
This is a breaking change in the Page API but is a tech debt we need to acknowledge cc: @jdcmsd

**Comment by erickgonzalez** [comment]
Image info populated:

![Image](https://github.com/user-attachments/assets/86bd6b94-3c6b-4f77-a49c-92fad929973d)

The image is still referenced in contentlet: 

![Image](https://github.com/user-attachments/assets/0e9b86f5-0935-461b-b102-d7a3958023fc)

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF

**Comment by erickgonzalez** [comment]
This one was required to backport first: #28857
