### ISSUE TITLE
Push publishing a content type fails if it is on a site that does not exist on target AND NO Error Message

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29255]
### Problem Statement

If you create a content type that lives on host that does not exist on the target site, it will fail to publish and give no error.  See screenshot below with no actionable error:

```
Failed to publish because an error occurred: An error occurred when processing Content Type in '/data/shared/assets/bundles/01J30Y1TQTNFG2MZEBFTQJPWQ9/working/dotcms.com/50e7185be91fea68442ef189e5ac0cb5.contentType.json' with ID 'Documentation Homepage': 50e7185be91fea68442ef189e5ac0cb5
```

<img alt="Screenshot 2024-07-17 at 2 14 32 PM" src="https://github.com/user-attachments/assets/a2b4756c-6f73-4471-b13f-c16b96b6b79b">

### Steps to Reproduce

1. add a new site (name random name)
2. add a content type on this site
3. try to push publish just this content type (without dependencies) to demo.dotcms.com

### Acceptance Criteria

1. A good fix is to include the "hostName" in the content Type definition, rather than just the siteId.  We could do a lookup in the handler to 
- see if the site exists by id, 
- if not, lookup site by hostname
- if not, fall back to system_host

This would prevent failures.

At minimum, we should show a better error message that describes the actual problem.

**Comment by jcastro-dotcms** [comment]
FYI, when the error message is being put together:
https://github.com/dotCMS/core/blob/3870c53ed789384bd63d053bde35db5e4393b3c3/dotCMS/src/enterprise/java/com/dotcms/enterprise/publishing/remote/handler/ContentTypeHandler.java#L210-L212
The `String.format` method is expecting 3 parameters, but it's receiving 4. Therefore, the error message from the original exception is not going to be present in the message displayed in the UI.

**Comment by dsilvam** [comment]
Failed Internal QA: Saving the Content Type under default host instead of system host

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Now the Content Type is saved under the SYSTEN_HOST

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b8fe837**, Docker, macOS 14.5, FF v126.0.1
