### ISSUE TITLE
UVE: Enable Editing Pages with Custom Query

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29263]
### User Story
As a content editor, I need the capability to edit pages generated from various request types or queries to dotCMS data through the Universal Visual Editor (UVE). Some queries could be:

1. GraphQL-specific query or multiples queries
2. Page API with custom parameters like depth, etc.

### The Problem
The problem is that we can't know what request the developer did to generated pages, **we don't know exactly what properties** the user requested to render their page or which GQL query.

When the page loads inside the editor, we send the page data to render that page, and the data we send is coming from the Page API which will often defer from the data that the customer requests in GQL.

The solution is **to receive the GQL query (or `client.page.get` params)** that the customer used to render the page and use that to get the page data we'll be sending down to the client while inside UVE.

We need to update our SDK, libraries and documentation so we can register that “request info”.

### Things to consider
1. User can use any GQL client library
3. User can use complex GQL queries with fragments
4. User can use [inline fragments](https://graphql.org/learn/queries/#inline-fragments), not the same as fragments
5. User can have queries with names
6. User can have multiples queries in one request.

```[tasklist]
### Acceptance Criteria
- [x] UVE should be updated to support editing pages created with GraphQL data.
- [x] Documentation on how to implement GraphQL pages should be updated to include instructions on editing those pages using UVE.
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - High

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by rjvelazco** [comment]
## Notes for IQA

In the example, you should be able to pass an `editor` object with parameters or a query.

### Examples

### Custom Query:

```tsx
export function MyGraphQLPage({ pageAsset, query }) {
    return (
            <main className="container flex flex-col gap-8 m-auto">
                <DotLayoutComponent
                    pageContext={{
                        components: componentsMap,
                        pageAsset: pageAsset,
                    }}
                    config={{
                        pathname,
                        editor: { query }
                    }}
                />
            </main>
    );
}
```

### Custom Params:
#### Only `depth` is available for now

```tsx
export function MyGraphQLPage({ pageAsset, query }) {
    return (
            <main className="container flex flex-col gap-8 m-auto">
                <DotLayoutComponent
                    pageContext={{
                        components: componentsMap,
                        pageAsset: pageAsset,
                    }}
                    config={{
                        pathname,
                        editor: { params: { depth: "1" } }
                    }}
                />
            </main>
    );
}
```

**Comment by fmontes** [comment]
## Notes for IQA (Angular)

**Comment by fmontes** [comment]
Angular example is not working... and looks like is this change.

https://github.com/user-attachments/assets/1927c508-ff6d-4653-b908-36747e3aa5dc

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `master`

NextJS:


https://github.com/user-attachments/assets/6f2d3bf2-18b2-4fc9-bebe-e6ac6cb1bef2


https://github.com/user-attachments/assets/40c0654a-6a11-4624-af17-ec6d4ea3e721



Angular:


https://github.com/user-attachments/assets/0c37eab3-746f-4384-a86d-d2310217e88b

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
