### ISSUE TITLE
Create Postman tests for healthcheck API endpoints

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#29267]
### Task

Include automated Postman(?) tests of 
```
/api/v1/probes/ready
/api/v1/probes/startup
/api/v1/probes/alive
```
These endpoints should
- accept a GET request
- return HTTP 200 with no response body

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Include automated testing of these APIs

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/28163

**Comment by bryanboza** [comment]
Note: 
- Postman test added, important here is this resource does not require authentication, checking the code it is working with an IP-List where you can add//deny IPs. It property is called `SYSTEM_STATUS_API_IP_ACL`  

- Looking at IPUtils and it don't have test at all, need to consider if maybe add integration test to this functionality have an added value...
