### ISSUE TITLE
GraphQL: Collections Query Duplication Issue

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29269]
### Problem Statement
Developers are confused by the duplication of collection queries in the GraphQL schema, which affects their ability to efficiently work with dotCMS.

### Steps to Reproduce
1. Go to GQL playground
2. Write a query for collections
3. See the duped, also you can see the dupe in the docs panel.

![CleanShot 2024-07-18 at 11 20 33@2x](https://github.com/user-attachments/assets/d950bdf5-acbc-4faf-95d0-70a57aa22b46)

```[tasklist]
### Acceptance Criteria
- [ ] The collection queries in the GraphQL schema should not display any duplication.
- [ ] Each collection query should be listed only once in the schema.
```

### External Links
- N/A

### Assumptions & Initiation Needs
- Assumption: The issue is related to how collection queries are fetched and displayed in the GraphQL schema.
- Initiation Needs: Investigation into the root cause of the duplication issue in the schema.

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
# Passed Internal

Now the Autocomplete and Docs don't have dupes on GQL Playground

## Screenshot

https://github.com/user-attachments/assets/88a59b6b-ce33-4caf-96d8-cb10bd0b7a2a

**Comment by bryanboza** [comment]
Fixed, now this is working as expected in the latest trunk...
