### ISSUE TITLE
Add Loading Status to the Column of Category List Component

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29265]
### Parent Issue
#28493 

### User Story
As a user, I need to see a loading status indicator in the column of the category list component while the categories are being fetched, so I know that the data is being loaded.

### Acceptance Criteria
- Implement a loading status indicator in the column of the category list component.
- Use a skeleton for this job.
- Use PrimeNG components for implementing the loading status.
- Handle different states (e.g., loading, idle, error) gracefully.
- Write unit tests to cover the new loading status functionality.
- Ensure the implementation does not introduce any new bugs or regressions.

### Proposed Objective
User Experience Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### External Links
- PrimeNG documentation: [PrimeNG 15-lts](https://www.primefaces.org/primeng-v15-lts/installation)

**Comment by dsilvam** [comment]
Passed IQA: Working as expected

**Comment by bryanboza** [comment]
Fixed, tested in the latest trunk // Docker // FF 

NOTE: This feature is specific for the new editor...
