### ISSUE TITLE
fix(edit-content): error with inputs text

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29275]
### Parent Issue

https://github.com/dotCMS/core/issues/28493

### User Story

As a user, when you create new content with a text field, focus on that field, and then press Enter, the side menu related to the category field appears, and this behavior is a bug.

https://github.com/user-attachments/assets/95efc9de-1aec-4686-9ded-640ee95f3b84

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2c23184**, Docker, macOS 14.5, FF v126.0.1
