### ISSUE TITLE
GraphQL: Improve Error Message for Unauthorized Page Request

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29270]
### Problem Statement
When making a GraphQL request for a working page (edit mode) without authentication, dotCMS returns a 500 error without providing any useful error message.

### Steps to Reproduce
https://github.com/user-attachments/assets/96f3f454-3f24-48aa-ab25-bb1308f265e5

```[tasklist]
### Acceptance Criteria
- [ ] Unauthorized query request should return a correct error message
```

An example error could be:
> Unauthorized: You do not have the necessary permissions to request this page in edit mode. Please contact your administrator for assistance or try again with appropriate writing permissions.

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
Currently, there is no workaround for this issue. QA testing should focus on verifying that the error message is improved when making unauthorized GraphQL requests for working pages.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_2e54089`]


### Video

https://github.com/user-attachments/assets/a09dbf0e-d3ad-4d3c-b313-d1b023ac7783

### Test Case

#### Query:

```graphql
query {
  page( url: "/index", pageMode: "WORKING") {
    title
  }
}
```

#### Response

```json
{
  "errors": [
    {
      "message": "Exception while fetching data (/page) : Unauthorized: You do not have the necessary permissions to request this page in edit mode.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "page"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "page": null
  }
}
```

**Comment by bryanboza** [comment]
Fixed and tested in the latest trunk, and now we have a clearer error message.

![Image](https://github.com/user-attachments/assets/52ef63c5-c127-44ae-a54d-da2171e2d615)
