### ISSUE TITLE
GraphQL: Error Handling for Bad Content Types Data

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29289]
### Problem Statement
When there is bad data in the database related to content types, GraphQL crashes instead of handling the error gracefully and continuing to work with the remaining content types.

### Steps to Reproduce
1. Try to use GQL in https://corpsites-headless.dotcms.cloud/dotAdmin/#/c/maintenance (ping @fmontes for a password)
2. See the 400 error in any GQL client or even dotcms playground
3. The logs show something like this:

```
ERROR business.ContentAPIGraphQLTypesProvider: Unable to generate GraphQL Field for field: videos
com.dotcms.graphql.exception.FieldGenerationException: Unable to find content type with id:c582fe61-6882-43e1-bc2c-5dba20896eaa
	at com.dotcms.graphql.business.RelationshipFieldGenerator.getRelatedContentTypeForField(RelationshipFieldGenerator.java:140) ~[classes/:?]
	at com.dotcms.graphql.business.RelationshipFieldGenerator.createRelationshipField(RelationshipFieldGenerator.java:59) ~[classes/:?]
	at com.dotcms.graphql.business.
```

![Screenshot 2024-07-18 at 2 39 44 PM](https://github.com/user-attachments/assets/45e14122-df79-4fe2-beb4-a51fe0db4e28)

```[tasklist]
### Acceptance Criteria
- [ ] GraphQL should log the error related to bad data in the database for a content type.
- [ ] GraphQL should continue to work with the remaining content types and not crash the entire system.
```

### External Links
- N/A

### Assumptions & Initiation Needs
- Data for content types can get corrupted by push publish
- For test locally, you can download a DB dump from the corp-site server

### Quality Assurance Notes & Workarounds
N/A

**Comment by fmontes** [comment]
@fabrizzio-dotCMS might be related: https://github.com/dotCMS/core/issues/28114

**Comment by fabrizzio-dotCMS** [comment]
So the real error behind this failure was [this](https://github.com/dotCMS/core/issues/28114) 
The exception shown in the screenshot above is handled well

**Comment by fabrizzio-dotCMS** [comment]
A few things need to be taken into consideration:
A few properties will be left out of the GraphQL schema, which is expected with this change.
So when querying a base type only required (fixed) fields will be available. if not we're opening the door for breaking the API quite easily. I wanted to "conciliate" the content-types  
here's a link to a Slack conversation https://dotcms.slack.com/archives/CQNF9PCFQ/p1721754478850189
We need to conciliate what is marked in the database as a required field and what appears on the Immutable Classes that describe the content type. Apparenty @wezell wants that work to happen later

**Comment by bryanboza** [comment]
Fixed, tested on the provided server and now it is working as expected
