### ISSUE TITLE
Restore Info Functionality on Binary Fields

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29283]
### Problem Statement

The info functionality on binary fields has been lost, preventing users from accessing essential information about binary files. This issue impacts the ability to manage and understand file details effectively.

![image](https://github.com/user-attachments/assets/9999d730-8627-4ae7-b8e0-f563df0151e2)

### Steps to Reproduce

- Log into the content management system with the necessary credentials.
- Navigate to a content item that includes binary fields.
- Add a new piece of content including a binary file
- Attempt to access the **info** functionality on a binary field.
- Observe that the info functionality is not available or accessible.

### Acceptance Criteria

- **Restore Info Functionality:** Ensure that the info functionality is restored and accessible on binary fields.
- **Detailed File Information:** Provide detailed information about binary files, including file name, size, type, upload date, and other relevant metadata.
- **User-Friendly Interface:** The info functionality should be easy to use and provide clear, concise information to users.

### dotCMS Version

Tested on trunk // docker 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Info functionality back. 

![Image](https://github.com/user-attachments/assets/cb962da1-4964-46a8-9446-92875d8991a3)

**Comment by bryanboza** [comment]
This is here back, but is affected by the styles, not sure if maybe is related to #

![Image](https://github.com/user-attachments/assets/7a43bed3-e222-4c34-84c7-3b3bf16c3a9b)

**Comment by nicobytes** [comment]
Hello @bryanboza I think is a cache problem I test with **trunk_6417ccd** and works fine.

![Screenshot 2024-07-24 at 10 17 40 AM](https://github.com/user-attachments/assets/aafb006a-f5b4-422c-95a3-317deeb268ba)

Please clean cache because these static files usually have aggressive cache.

1. Open your devtools on localhost:8080
2. Click on Application
3. Click Storage
4. Click Delete Location Data

![Screenshot 2024-07-24 at 10 17 55 AM](https://github.com/user-attachments/assets/20bf61b6-ebdf-4297-9e20-ff813f88584f)

**Comment by bryanboza** [comment]
Hello @nicobytes this is not caused by a cache issue, we usually use private mode to test and avoid cache issues. 

The failure was caused by the issue that we had generating images in our CI/CD, then with the image generated manually from master still failing. Tested again this morning after restore our normal process and now it is working. 

Tested on [ trunk_4980358 ] // Docker
