### ISSUE TITLE
Fail gracefully when OpenAI model stops working

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29284]
### Parent Issue
https://github.com/dotCMS/core/issues/28813

### User Story
As a Java developer, I want to provide a fallback strategy for when our OpenAI client fails. We need to identify the cause of the failure due to three main reasons:
- The current model in use has been decommissioned by OpenAI
- The current model is invalid
- Any other reason like network failure, timeout, etc.

The fallback strategy consists of the following steps:
- When a model in use has been decommissioned or is invalid:
  - Log a multi-line message in the logs
  - Internally mark the issue as unavailable
  - Switch to the next model in the list
- When an attempt to use a model in the list fails for other reasons (timeout, network, etc.):
  - Log a single-line message in the logs
  - Try the next model in the list
- When all models in the list fail:
  - Log a multi-line message in the logs
  - Post a growl
  - Return an error from dotAI

### Acceptance Criteria
- The system can detect if a model has been decommissioned or is invalid.
- The system logs a multi-line message when a model is decommissioned or invalid.
- The system marks the decommissioned or invalid model as unavailable internally.
- The system switches to the next model in the list when a model is decommissioned or invalid.
- The system logs a single-line message when a model fails due to reasons like timeout or network failure.
- The system retries with the next model in the list when a model fails due to timeout or network failure.
- The system logs a multi-line message, posts a growl, and returns an error when all models in the list fail.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- Clear identification of the list of models to be used as fallback.
- Access to logging and error reporting mechanisms.
- Development environment set up to simulate different failure scenarios.

### Quality Assurance Notes & Workarounds
- Test cases to simulate decommissioned models, invalid models, and other failure scenarios (timeout, network issues).
- Verify logging for both multi-line and single-line messages.
- Ensure the system correctly switches to the next model in the list.
- Validate the error handling and reporting when all models fail.

**Comment by victoralfaro-dotcms** [comment]
PRs:
- https://github.com/dotCMS/core/pull/29748
- https://github.com/dotCMS/core/pull/29761
- https://github.com/dotCMS/core/pull/29774

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `trunk_ea541c2`

The expected results and error messages described in Victor's comment are showing up as expected. Now, its **VERY IMPORTANT** that, in some scenarios, you reset the DotAI configuration as Victor said:
```
Repeat the dotAI app configuration process to reset the models once against
```
Otherwise, you may not get the expected result in the scenario.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e622545**, Docker, macOS 14.5, FF v126.0.1
