### ISSUE TITLE
QA: Generate a step by step doc about how to import an existing database in docker 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29285]
### Parent Issue

https://github.com/dotCMS/core/issues/28678

### Problem Statement

Based on these changes, we need to generate a step-by-step guide on how to use this feature. As a stream-aligned team, this will be useful for internal use and also in the onboarding process.

### Steps to Reproduce

- Make sure we are using an existing dataset to test

### Acceptance Criteria

- Need to generate a formal doc file

### dotCMS Version

Trunk. 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
QA Comment

Attached the requested document.

https://docs.google.com/document/d/1vpcFxNcjEMx9Dmw45_JKrn-Ux-jrGlGZr0syGdKNeAQ/edit?usp=sharing

**Comment by bryanboza** [comment]
Please check the feedback provided in the document!

**Comment by josemejias11** [comment]
**QA Comment**

Updated version for revision https://docs.google.com/document/d/1vpcFxNcjEMx9Dmw45_JKrn-Ux-jrGlGZr0syGdKNeAQ/edit?usp=sharing
