### ISSUE TITLE
For binary field + AI: change from DotAI to dotAI

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29291]
### Problem Statement

The label "Generate With DotAI" is wrong and will be "Generate With dotAI"

![Screenshot 2024-07-19 at 12 21 56 PM](https://github.com/user-attachments/assets/e2396505-5c66-409c-a718-d633d7124870)

### Steps to Reproduce

2. Enable DotAi App with an Open AI Key
3. Create a content type with a Binary Field

### Acceptance Criteria

1. Label with "Generate With dotAI"

### dotCMS Version

dotcms:trunk_bd13b61

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ed06de4**, Docker, macOS 14.5, FF v126.0.1
