### ISSUE TITLE
Cannot change folder URL to lowercase

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#29293]
### Problem Statement

When changing the URL of a folder to an upper case or lower case version of the same URL, dotCMS throws an error.

### Steps to Reproduce

1. Create a folder "test"
2. Try changing the name of the folder to "TEST"
3. dotCMS will throw an error

### Acceptance Criteria

Allow renaming folders to the upper or lower case version of the same URL

### dotCMS Version

24.07.12

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117221

### Quality Assurance Notes & Workarounds

Workaround is to change the folder to something else and then change it to the lower/upper case version.

**Comment by erickgonzalez** [comment]
Tested working as it should. Now we can change case of folders.

**Comment by bryanboza** [comment]
Fixed, now we are able to rename without problems, tested on trunk [trunk_78bb755] // Docker // FF
