### ISSUE TITLE
Upgrade the project to Angular 17.3 and Nx 18.3.5.

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29298]
### Task

Upgrade the project to Angular 17.3 and Nx 18.3.5.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- Successfully upgrade the project to Angular 17.3.
- Successfully upgrade the project to Nx 18.3.5.
- Ensure all existing functionalities continue to work correctly after the upgrade.
- Resolve any breaking changes or deprecations introduced by the new versions.
- Test the entire application to ensure compatibility and stability with Angular 17.3 and Nx 18.3.5.
- Verify that all unit tests pass and add new tests for any new functionality introduced by the upgrades.

**Comment by oidacra** [comment]
@dsilvam, This was merged Monday/Tuesday the week after prev. GD

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d5e1ec1**, Docker, macOS 14.5, FF v126.0.1

![Screenshot 2024-08-05 at 12 29 22 PM](https://github.com/user-attachments/assets/70893bac-55a3-4fd7-88cf-10bdc97810cc)
