### ISSUE TITLE
Creating a new page with a name that already exists in the folder fails without message

### ISSUE THREAD

**Issue by mabouza** [dotCMS/core#293]
I'm on the demo site, home folder.

I wanted to create a new page test.dot and didn't see there was already one called that.

On the Add new HTML Page page whenever I tried to create it, the page will load empty again without an error message.

Then I realized the issue was the page already existed.

We should show a message to the user explaining why the page can't be created

**Comment by wezell** [comment]
Will be handled in UI refresh
