### ISSUE TITLE
Image AI Modal on large screens

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29301]
### Problem Statement

2. Pop up do not resize correctly in tall screens. 

<img width="1582" alt="image" src="https://github.com/dotCMS/core/assets/31667212/a1760bda-3e0e-4afb-a23b-1bdf75f047cb">

expected behavior: 

<img width="1517" alt="image" src="https://github.com/dotCMS/core/assets/31667212/d197a9cf-6159-44a8-b86a-c68dfd813da8">

### Steps to Reproduce

1. enable IA plugin. 
2. display the IA button in the binary field. 
3. Open de AI image pop-up from the binary field. 
4. See the jump when first loads. 

### Acceptance Criteria

Should look good on large screens

### dotCMS Version

latest 

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ed06de4**, Docker, macOS 14.5, FF v126.0.1
