### ISSUE TITLE
For siteFolder field: include // at the beginning

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29303]
### Problem Statement

The user should create the site Folder site with // at the beginning

### Steps to Reproduce

1. Create a content type with a site or folder field
2. Select a site or folder
3. The path for user should be // at the beginning

### Acceptance Criteria

The path for user should be // at the beginning

### dotCMS Version

latest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by hmoreras** [comment]
Pass Internal QA:  The field need to be tested in the new edit Content Beta. 

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/512dd377-93c2-4a79-9043-86013a2cf43d">

**Comment by bryanboza** [comment]
Fixed, after select the site/folder, the generated path starts with `//` 

![Image](https://github.com/user-attachments/assets/649ef54a-9769-4fc9-818e-0bb65d07c9c3)
