### ISSUE TITLE
Problems editing and Saving VTL Files

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29309]
### Problem Statement

Users are unable to edit and save changes to VTL files. This issue prevents users from updating templates and other VTL-based configurations, impacting their ability to manage and customize their content management system effectively.

https://github.com/user-attachments/assets/3105e322-0a62-4a7c-9159-76ce26434dfa

### Steps to Reproduce

- Log into the content management system with the necessary credentials.
- Navigate to the section where VTL files are stored.
- Attempt to edit a VTL file by making changes to its content.
- Save the changes and observe that the changes are not saved.

### Acceptance Criteria

- **Edit Functionality:** Ensure that users can edit VTL files and make changes to their content.
- **Save Functionality:** Ensure that changes made to VTL files are correctly saved and persisted.
- **User Feedback:** Provide clear feedback to users when changes are successfully saved or if an error occurs.

### dotCMS Version

Tested on [ trunk_b00ffaf ] // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed IQA: Fixed on latest trunk

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk and this is working as expected.
