### ISSUE TITLE
Enhance /api/v1/categories/children Endpoint to Return Parent List

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29315]
### Parent Issue
#28493 

### User Story
As a developer, I need the `/api/v1/categories/children` endpoint to return the parentList of categories when `showChildrenCount: true` is sent. Alternatively, create a new parameter to handle this. This is necessary to provide the path to the parent category for deeper levels (2-N) to help users navigate back to the selected child category.

### Acceptance Criteria
- Modify the `/api/v1/categories/children` endpoint to include the parentList when `parentList: true` is sent.
- Alternatively, add a new parameter to request the parentList.
- Ensure the parentList provides the complete path to the parent category for deeper levels (2-N).
- Update the API documentation to reflect the changes.
- This is only of 1 Level, only for the children of the inode sent.
- Write unit tests to cover the new functionality.

### Proposed Objective
API Enhancement

### Proposed Priority
Priority 2 - Important

### dotCMS Version
master

### Problem

<img width="1488" alt="Screenshot 2024-07-19 at 5 16 05 PM" src="https://github.com/user-attachments/assets/0f719231-22b5-4607-a58a-4b0605c1b155">

Request don't have parentList
<img width="297" alt="Screenshot 2024-07-19 at 5 18 26 PM" src="https://github.com/user-attachments/assets/cc0acf4f-d94f-4af2-ae6d-390143ded61c">

When we sent filter query param, the endpoint retrieve parentList of the category
<img width="305" alt="Screenshot 2024-07-19 at 5 18 49 PM" src="https://github.com/user-attachments/assets/c62c4ab8-5fba-4358-a72c-80ec2414cf29">

### Assumptions & Initiation Needs
Assuming the current implementation of the `/api/v1/categories/children` endpoint can be enhanced to include the parentList. Access to the current codebase and API documentation is required.

### Quality Assurance Notes & Workarounds
Quality assurance should verify that the parentList is returned correctly when requested and that the API remains stable. Ensure that edge cases, such as categories with no parents, are handled correctly.

**Comment by dsilvam** [comment]
Failed IQA: 
This call is not returning the "parentList" 
http://localhost:8080/api/v1/categories/children?inode=5d72bea551587a8783e88e9145f4e132&per_page=7000&direction=ASC&showChildrenCount=true

**Comment by dsilvam** [comment]
Passed Internal QA: 
This request is properly returning the list of parents

http://localhost:8080/api/v1/categories/children?inode=5d72bea551587a8783e88e9145f4e132&per_page=7000&direction=ASC&showChildrenCount=true


![Image](https://github.com/user-attachments/assets/9bad0891-72f9-46b9-8325-b2e0edc9bbde)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a466b5d**, Docker, macOS 14.5, FF v126.0.1
