### ISSUE TITLE
Error with colors

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29316]
### Problem Statement

Problem primary color

https://github.com/user-attachments/assets/6b4a3958-a616-49ad-a221-cf61bf3dceab

### Steps to Reproduce

1. Create a new content type with old editor version
2. Create a Binary field
3. Check the buttons colors

### Acceptance Criteria

.

### dotCMS Version

latest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by bryanboza** [comment]
Tested on the latest trunk and we still getting same thing here: 

https://github.com/user-attachments/assets/7aac2f91-f1da-457b-b198-37ed55bdfa40

**Comment by nicobytes** [comment]
Hello @bryanboza I think is a cache problem I test with **trunk_6417ccd** and works fine.

![Screenshot 2024-07-24 at 10 17 40 AM](https://github.com/user-attachments/assets/aafb006a-f5b4-422c-95a3-317deeb268ba)

Please clean cache because these static files usually have aggressive cache.

1. Open your devtools on localhost:8080
2. Click on Application
3. Click Storage
4. Press Clear site data

![Screenshot 2024-07-24 at 10 17 55 AM](https://github.com/user-attachments/assets/20bf61b6-ebdf-4297-9e20-ff813f88584f)

**Comment by bryanboza** [comment]
Same thing here, related to the generated image, now it is working as expected
