### ISSUE TITLE
UVE: Inline editing not working with cross-domain 

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#29311]
### Parent Issue

N/A

### Problem Statement

If an Angular page lives on a server outside dotCMS, when attempting inline editing in Angular with a cross-domain we get a `401 Unauthorized`  error

https://github.com/user-attachments/assets/51a7cdda-5cd6-4428-a5ec-ac38a5fc386b

### Steps to Reproduce

1. Configure our Live Angular example in your local
```json
{ "config":[ { "pattern":".*", "url":"https://angular-example-uve.vercel.app/"}]}
```
2. Go to any page.
3. Try to inline editing.
4. See the error/Check the network tab.

### Acceptance Criteria

Users should be able to edit content inline even if an Angular page lives on a server outside dotCMS.

### dotCMS Version

`master`/`trunk`

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![401-unauthorized](https://github.com/user-attachments/assets/e746655d-822c-4ba7-b074-980de3c68145)

![Request](https://github.com/user-attachments/assets/a36c0d91-f2b6-4d3b-b4ce-ddfe72c39c1b)

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `qa-master` with [Angular example](https://angular-example-uve.vercel.app/)


https://github.com/user-attachments/assets/fc8172fd-334d-4fc3-a9a5-75f7ce5ddff7

**Comment by bryanboza** [comment]
Fixed, tested on qa-master.... 

Now we are able to use the in-line editing on cross-domains in angular without problems
