### ISSUE TITLE
An Asset name starts with number and specific alphabets considers as an Image

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#29321]
### Problem Statement

When an asset e.g PDF creates with name starting from **number and alphabets** (list below) consider it as an image.

if any PDF name starts with:
{number}h
{number}w
{number}cw
{number}ch
{number}q
{number}ro
{number}maxw
{number}maxh
{number}minw
{number}minh
it will be treated as an image instead as pdf… this is because our Regex are like this:

https://github.com/dotCMS/core/blob/d1ae95decdc356ef9b7ab16e752ff62944c35d37/dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java#L68-L82

https://github.com/dotCMS/core/blob/d1ae95decdc356ef9b7ab16e752ff62944c35d37/dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java#L319

### Steps to Reproduce

Create a file asset by uploading "1QResults.pdf". Noet **1Q** is important in the file name.

Access that file through asset URL e.g https://demo.dotcms.com/dA/a02d2976-5c56-4460-89f8-31e8ab1c6687/fileAsset/1QResult.pdf

You will receive no response and when check the network tab the response content header would be image/webp.

<img width="856" alt="image" src="https://github.com/user-attachments/assets/dc8db018-9ecb-4c94-8957-dc79c43b9fd2">You will receive nothing, and then you check the network tab, the response content header will be image/web.

### Acceptance Criteria

The asset should return e.g pdf file, without applying a filter on the file name

### dotCMS Version

23.* - 24.* All version

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117235
https://dotcms.slack.com/archives/C028Z3R2D/p1721407542518499?thread_ts=1721400476.590789&cid=C028Z3R2D

**Comment by erickgonzalez** [comment]
Tested working as it should now we get the requested file.

![Image](https://github.com/user-attachments/assets/6497a8dc-ea1f-4b59-acb0-a49d233302ae)

**Comment by bryanboza** [comment]
Fixed, tested on [ trunk_78bb755 ] // Docker // FF 

![Image](https://github.com/user-attachments/assets/3514e996-66e7-465c-96a8-272721de2661)

**Comment by nathan-hildebrandt** [comment]
Crak media encountering this issue on 23.10.24 https://dotcms.freshdesk.com/a/tickets/27549
