### ISSUE TITLE
UVE: Bring back the `onReload` callback in DotcmsLayout

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#29338]
### Parent Issue

N/A

### Task

Clients need the `onReload` callback added to DotcmsLayout to reload the page after any change.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The `onReload` callback should allow developers to handle their page reload after any change in the editor.

**Note:** The callback must be marked as `deprecated` since it is a legacy feature.

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `qa-master` with [Angular example](https://angular-example-uve.vercel.app/)


https://github.com/user-attachments/assets/d7c2d420-b12f-4837-a30e-73eafb8dd83b

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker // NextJS
