### ISSUE TITLE
Correct Background of Calendar Buttons

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29364]
### Task

As a user, I need the background of the calendar buttons to be visually consistent with the design system, ensuring a seamless and polished user interface.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- Correct the background of the calendar buttons to align with the design system.
- Ensure the background change is applied to both the clear (X) button and the calendar icon button.
- Verify the changes across different states (hover, active, disabled) for visual consistency.
- Use PrimeNG components for implementing the background changes if applicable.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

![Screenshot 2024-07-25 at 5 20 09 PM](https://github.com/user-attachments/assets/62dd4144-0df0-43fa-b661-eaedfd7a3b84)

**Comment by oidacra** [comment]
Analytic do not generate the `Analytics Key`

**Comment by nicobytes** [comment]
Duplicated https://github.com/dotCMS/core/issues/29472
