### ISSUE TITLE
CICD: Fix JReleaser path mismatch in dotCLI Release Process

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#29375]
### Problem Statement
During the dotCLI release process, the binaries are missing from the GitHub release. The issue seems to be related to the JReleaser binary selector, which appears to be referencing directories that no longer exist. The current configuration expects directories like `artifacts-osx-aarch_64`, but in the CI/CD build workflow, the directories are being named differently, such as `artifacts-macos-14`.

### Steps to Reproduce
1. Initiate the release process for dotCLI.
2. Observe that the binaries are missing in the GitHub release.

### Acceptance Criteria
- All expected binaries are correctly published to GitHub releases.
- The JReleaser configuration correctly identifies and utilizes the existing directories.

### dotCMS Version
N/A

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links
N/A

### Assumptions & Initiation Needs
- This issue assumes that the paths configured in JReleaser need to match the output directories of the CI/CD build workflow.
- Initiation requires access to both the JReleaser configuration and the CI/CD workflow settings.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by bryanboza** [comment]
We need wait until fire the release process in order to validate if this is working or not...

**Comment by nollymar** [comment]
Working as expected https://github.com/dotCMS/core/releases/tag/dotcms-cli-24.08.20
