### ISSUE TITLE
Remove save and publish functionality from the AI Actionlets

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29387]
### Parent Issue

https://github.com/dotCMS/core/issues/29380

### User Story

As an user I want to be able to decide which is the next sub action after the IA generation

### Acceptance Criteria

Currently the IA WF actionlets does save + publish, the idea would be to leave the ability to the user to decide if wants or not save + publish or something else.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
IQA: Failed. 
After setting the AI Generate Image actionlet + a save actionlet it's giving errors and not saving the image to the content. 
Log: https://gist.github.com/dsilvam/93e9ff2e4a05fe3d5988458dd41a8d26

**Comment by dsilvam** [comment]
Passed IQA: Remaining subaction to work it's now working - Generate AI Image: 


https://github.com/user-attachments/assets/e1441ed5-fb2e-4e32-a23e-e020c0451901

We'll put in a card to capture the lack of feedback to the user right after the action gets executed.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_36f72e4**, Docker, macOS 14.5, FF v126.0.1
