### ISSUE TITLE
AI Refactor

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29380]
### User Story

As an user, I want to be able to refactor the IA code, so I can extend it easily.

### Acceptance Criteria

The IA should not have async calls
Save + Publish
and other enhacements

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29381
```

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29387
```

**Comment by wezell** [comment]
Looks like the tasks are done, closing.
