### ISSUE TITLE
Scroll in Breadcrumb Toolbar on Firefox

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29399]
### Problem Statement

There is a scroll in the toolbar navigation

![Screenshot 2024-07-30 at 3 06 37 PM](https://github.com/user-attachments/assets/faa9eb31-77fc-4a1e-8122-d208845e2347)

### Steps to Reproduce

1. Open Firefox
2. Go to content
3. Select Search
4. See the toolbar

http://localhost:4200/dotAdmin#/c/content

### Acceptance Criteria

Toolbar without scroll

### dotCMS Version

trunk_4a03b35

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed IQA: No scroll in breadcrumb



![Image](https://github.com/user-attachments/assets/7874130d-db03-4b89-a25a-40f311cdd591)




![Image](https://github.com/user-attachments/assets/026bae5c-2a1c-4384-af2c-aca238a8ff0b)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d0406c0**, Docker, macOS 14.5, FF v126.0.1
