### ISSUE TITLE
SDK: Create dotCMS Example for JavaScript Framework Astro

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29393]
### User Story
As a developer, I want an example on how to use Astro with dotCMS pages and dotCMS SDK,

```[tasklist]
### Acceptance Criteria
- [x] Develop a sample dotCMS project using the Astro JavaScript framework.
- [x] Utilize the `@dotcms/react` library for rendering components.
- [x] Implement data fetching using @dotcms/client.
- [x] Ensure the example project demonstrates the integration between dotCMS and Astro effectively.
- [x] Use Astro routing catch all strategy like we did in other examples
- [x] Provide documentation on how to set up and run the example project.
- [x] Astro example should be editable in UVE
- [ ] Deploy to Vercel or AWS
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- Familiarity with dotCMS and the Astro JavaScript framework.
- Access to the @dotcms/react library and @dotcms/client for implementation.

### Quality Assurance Notes & Workarounds
N/A

**Comment by KevinDavilaDotCMS** [comment]
# QA Passed
Tested in `master` with qa-server and [astro deployed example](https://astro-example-uve.vercel.app/)

QA server:

https://github.com/user-attachments/assets/cd711f85-8af8-4c2f-8206-ac1d1bccfc0a

**Comment by bryanboza** [comment]
Fixed, now we have the astro example, we can pass this for now
