### ISSUE TITLE
Saving folder names with special characters leads to incorrect encoding

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#29392]
### Problem Statement

When saving a folder with a name that contains letters with accents, the name will add some additional unexpected characters.

### Steps to Reproduce

Create a docker container for v23.10.24 of dotCMS
Create a folder with name containing an accented character. Example: Ârvore
Save the folder
After the initial save, there will be an additional hyphen after the accented character, and the accent above the A will change to Ã
Subsequent saves will append more unexpected characters
![Screenshot 2024-07-30 at 9 32 25 AM](https://github.com/user-attachments/assets/30002961-36b8-4cb7-b9b9-048dbf0e10a5)

### Acceptance Criteria

Have the accented character in folder names encode correctly

### dotCMS Version

23.10.24
Also reproducible in QA master

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C01N0AU1NUC/p1721766791361909
https://dotcms.zendesk.com/agent/tickets/117346

**Comment by weiyiwang-dotcms** [comment]
May be related to this: https://github.com/dotCMS/core/issues/29093

**Comment by weiyiwang-dotcms** [comment]
In addition to the poor user experience of the incorrect encoding appearing on the front-end page for users, this also appears to be affecting SEO ranking, given that the encoded URLs keep changing.

**Comment by erickgonzalez** [comment]
Working as it should, special chars can be used in folder title/name.

![Image](https://github.com/user-attachments/assets/eeeda5de-7752-4e55-b1b3-18d9656bcff1)

**Comment by bryanboza** [comment]
Unable to reproduce. 

Tested on trunk // Docker // FF 
![Image](https://github.com/user-attachments/assets/1a7ffd0c-f7c6-423c-9dfe-487c8b5df886)
