### ISSUE TITLE
Unable to import the Personas exported file 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29405]
### Problem Statement

Users are unable to import the exported file of personas due to two main issues: the exported file contains an incorrect URL in the photo field (missing the host), and some columns are not recognized during the import process. This issue affects the ability to manage personas efficiently.

![image](https://github.com/user-attachments/assets/8863147c-e8ce-42e9-b255-2972b9e22b7d)

### Steps to Reproduce

- Export a personas file from the content management system.
- Open the exported file and observe the URL in the photo field (missing host).
- Attempt to import the file back into the system.
- Observe that some columns are not recognized during the import process.

### Acceptance Criteria

**Correct URL in Photo Field:** Ensure that the exported file includes the full URL (including host) in the photo field.
**Recognized Columns:** Ensure that all columns in the exported file are correctly recognized during the import process.
**Successful Import:** Users should be able to import the exported file without encountering errors.

### dotCMS Version

Tested on the latest trunk // Docker 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Seems after the fix #29209 now we fixed the URL stuff, but we still getting errors b/c we are not recognizing some of the columns in the file. 
![image](https://github.com/user-attachments/assets/f075ea8c-c62e-4cfa-adc8-e12855fa893e)

**Comment by Neehakethi** [comment]
It seems the columns are now being read as expected
![image](https://github.com/user-attachments/assets/5b0faba4-e14c-47ef-8385-d6cdf3afb61a)

**Comment by erickgonzalez** [comment]
This was fixed in https://github.com/dotCMS/core/issues/29079
