### ISSUE TITLE
Rafael: Drop Everything & Learn Jul 31 - Aug 13

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29428]

**Comment by rjvelazco** [comment]
## Angular v17 Cheat Sheet

- Time spent: ~35 min.

I used this time to read/review this guide: [angularv17-cheat-sheet.pdf](https://github.com/user-attachments/files/16606288/angularv17-cheat-sheet.pdf) (It's in Spanish) to see if there is something useful I didn't know about Angular.

## Findings

### Pipes

- `KeyValuePipe`: Transforms Object or Map into an array of key-value pairs.
- `PercentPipe`: Transforms a number to a percentage string, formatted according to locale rules that determine group sizing and separator, decimal-point character, and other locale-specific configurations.
- `I18nPluralPipe`: Maps a value to a string that pluralizes the value according to locale rules.

### Built-in control flow

#### @empty

- `@empty`: You can optionally include an @empty section immediately after the @for block content. The content of the @empty block displays when there are no items:
- 
```html

```@for (item of items; track item.name) {
     <li> {{ item.name }} </li>
} @empty {
     <li> There are no items. </li>
}
```

####  @defer and @placeholder

- `@defer`: A type of [block](https://angular.dev/api/core/@defer) that can be used to defer load the JavaScript for components, directives and pipes used inside a component template.
- `@placeholder`: The @placeholder block accepts an optional parameter to specify the minimum amount of time that this placeholder should be shown.

```html
@defer {
     <large-component />
} @placeholder (minimum 500ms) {
     <p>Placeholder content</p>
}
````
