### ISSUE TITLE
UVE: Automatic page refresh after saving content changes

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29426]
### Parent Issue

#28947 

### Problem Statement

In the Universal Visual Editor (UVE), users need to manually refresh the page after making changes to a content item and saving it. This manual refresh can disrupt the workflow and lead to confusion, as users might not immediately see the changes they've made. We need an automatic page refresh after saving content changes, that would improve the user experience by ensuring that users always see the latest version of their content.

https://github.com/user-attachments/assets/00eb4b22-7ec3-4d25-ac39-74b78dcc549c

### Steps to Reproduce

- Log in with the necessary credentials.
- Edit a page 
- Navigate to a content item and make changes.
- Click the "Save" button to save the changes.
- Observe that the changes are saved, but the page does not automatically refresh to reflect the updated content.

### Acceptance Criteria

- **Automatic Page Refresh:** Ensure that the page automatically refreshes after a content item is saved in the UVE.
- **User Feedback:** Provide visual or textual feedback indicating that changes have been successfully saved and the page is refreshing.

### dotCMS Version

Tested on the latest trunk `[trunk_8a83f92]`// Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `master 0a261ce`
SDK Lib: `0.0.1-alpha.29`


https://github.com/user-attachments/assets/241a6388-eb48-47ea-ab52-f89d6ea98cbd

**Comment by bryanboza** [comment]
Fixed, now it is working as expected, tested on the latest trunk // Docker // FF
