### ISSUE TITLE
Problem with Side Menu on Category Field on Firefox

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29422]
### Problem Statement

When opening the category field menu, there is a bug with the animation only in Firefox.

https://github.com/user-attachments/assets/9602d01c-b15f-4e22-a6ed-a6b13d28a7a4

### Steps to Reproduce

1. Open Firefox
2. Create a content type with the category field
3. Create a content and open the side menu

### Acceptance Criteria

Open the side menu without this problem.

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by dsilvam** [comment]
Passed Internal QA: No issue with the slide in animation on Firefox anymore.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_5da036f**, Docker, macOS 14.5, FF v126.0.1
