### ISSUE TITLE
Scrolling animation bug in category field

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29423]
### Problem Statement

There is a bug with the scrolling animation when a category is checked and it is already open.

https://github.com/user-attachments/assets/8bc65680-ec31-4ce3-8cbd-fe3a20a4c268

### Steps to Reproduce

1. Create a content type with a category field
2. Create a content and open the side menu
3. Navigate through the categories and try to select a previously opened category.

### Acceptance Criteria

When checking or unchecking a category that is already open, there should not be a scroll animation.

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
QA Note:

#### Prevent loading a category that is already loaded

Before

https://github.com/user-attachments/assets/ec140c30-8f57-4823-b20e-b9094fa0086b

After

https://github.com/user-attachments/assets/58b33419-e447-481c-b5ad-1f08a36ca5ca

#### Separate the checkbox event from the click item to avoid triggering the animation and loading the category when the user checks a category.

Before

https://github.com/user-attachments/assets/352553fd-09d2-4025-8dcf-7855cdb398bb

After

https://github.com/user-attachments/assets/feb9ea1e-db57-42c2-8d91-a8bed5683f18

**Comment by hmoreras** [comment]
Tested in FireFox and Chrome, Categories are not being reloaded and animation fox in Firefox.

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_1d6cebf**, Docker, macOS 14.5, FF v126.0.1
