### ISSUE TITLE
Push Publish Creates a New Folder in the Receiving Server When The Folder Name Changes

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#29447]
### Problem Statement

Push publishing does not properly handle changing folder names. When a folder name is changed, and the folder is push-published, the receiving server will generate a new folder and leave the old folder in place.

### Steps to Reproduce

Create a folder in the sending server
Add a file to the newly created folder
Push publish the folder to the receiving server with the "everything and dependencies" filter applied
Change the name of the folder name on the sending server.
Push publish the folder again with the "everything and dependencies" filter applied
The receiving server will create a new folder matching the new folder name, but the old folder will still be there as well. The contents of the old folder will be moved to the new folder after the push publish.

### Acceptance Criteria

Have the push-publishing of a resource with a name change also remove the resource from the receiving server.

### dotCMS Version

23.10.24

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117366
https://dotcms.slack.com/archives/CSHTYUR7H/p1722444906516579
https://dotcms.slack.com/archives/C035XMEDQ4F/p1729263747833309

**Comment by m27iu4** [comment]
https://dotcms.freshdesk.com/a/tickets/28342
