### ISSUE TITLE
Use the new Angular Syntax in Block Editor

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29448]
### Task

Using the command nx g `@angular/core:control-flow `to migrate to the new Angular syntax

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
QA Note:

1. Create a new content type with a block editor field
2. This field should be working fine on the new or old version

The new Content editor version.

https://github.com/user-attachments/assets/a60e239b-ff6d-494e-8eef-098adf8a9ac1

The old Content editor version.

https://github.com/user-attachments/assets/058d4b33-fbbe-4396-95b3-2aea5da25bc3

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b295876_SNAPSHOT**, Docker, macOS 14.5, FF v126.0.1
