### ISSUE TITLE
Content Analytics: Scope work for MVP

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29475]
### Parent Issue

*No response*

### Task

We need to understand the scope of work required to implement the MVP \(phase 1\) of Content Analytics, using the existing analytics infrastructure to records and query events.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

*No response*

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*
\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29476
- [ ] https://github.com/dotCMS/core/issues/29477
- [ ] https://github.com/dotCMS/core/issues/29481
`\`\`

**Comment by bryanboza** [comment]
New cards reported on: 

https://github.com/dotCMS/core/issues/31165
https://github.com/dotCMS/core/issues/31160
https://github.com/dotCMS/core/issues/31169
