### ISSUE TITLE
Spike: Define specification and scope to configure Content Analytics and perform raw BE queries on the data

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29477]
### Parent Issue

https://github.com/dotCMS/core/issues/29475

### Task

Currently, when any Experiment is running, dotCMS stores an event every time any URL on the site is visited.
* This is less than ideal, but is acceptable for Experiments because on most customer systems, Experiments don't run all the time.
* However, when Content Analytics (CA) is implemented, this will no longer be acceptable, because CA will be running all the time.

So, we need to provide options to limit where and/or how CA data is collected.
* For example, we may want to allow users to enable or disable collection of CA data on specific pages/content, particular paths, or different content types.

In order to enable this kind of configuration, we will need a CA App
* Note: This may need to be separate from the existing Analytics App.

We should (but not must) also provide an interface to allow queries against the CA data from the dotCMS BE UI.

This spike is to:
* Determine whether we should have a separate CA App, or add config to the existing Analytics App.
* Scope the work needed to create or update the App.
* Scope he work would required to provide a basic (bare-bones) CA portlet that enables:
    * Sending a (raw) query to the analytics infrastructure
    * Displaying the results in a readable list

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Cards created for both:
* Creating or updating the App to allow configuring CA parameters.
* Creating a basic CA portlet.

**Comment by freddyDOTCMS** [comment]
Here the Documentation where I explain  what we need to do here

https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/view#heading=h.yow0ow19galg
