### ISSUE TITLE
Color in the Calendar Picker on Experiments

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29472]
### Problem Statement

The date selection buttons are the wrong color.

![Screenshot 2024-07-25 at 5 20 09 PM](https://github.com/user-attachments/assets/5983e238-3ba4-46ff-b524-6497fe79f37e)

### Implement Experiments in Dev mode

First, reproduce this steps to load experiments in dev mode

1. You need to have dotcms running (docker-file with dotcms, elasticsearch and postgresql)
2. Go to `core/docker/docker-compose-examples/analytics/docker-compose.yml` and run that docker-compose.
3. After the docker-compose loads, In dotCMS, go to Settings => Apps => Analytics Integration
4. Fill the fields with this information
`clientId: 	analytics-customer-customer1`
`Secret:	 testsecret`
`Analytics Config URL: 	http://host.docker.internal:8088/c/customer1/cluster1/keys`
`Analytics Write URL use: 	http://host.docker.internal:8081/api/v1/event`
`Analytics Read URL use:	http://host.docker.internal:4001/`
and save it

Second, select a date

1. Go to pages
2. Select a page
3. Go to A/B Testing Option
4. Create a new experiment
5. Go to Scheduling section and click on Setup button
6. Select a date

https://github.com/user-attachments/assets/52b1b11a-1020-488d-afd4-4fd37cb84742

### Acceptance Criteria

Buttons with the proper colors.

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_386274d**, Docker, macOS 14.5, FF v126.0.1
