### ISSUE TITLE
Create BufferedCsvReader to Handle Large CSV Files

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#29487]
### Parent Issue

https://github.com/dotCMS/core/issues/29482

### Task

As a developer, I need to create a new version of the CsvReader component with improved memory management. It can be called BufferedCsvReader 
This new component should be able to read a specified number of rows at a time and indicate if there are more rows to read, preventing the entire file from being loaded into memory at once. Consider creating an interface to swap implementations so the new component can seamlessly replace the old one 

Consider that the actual CvsReader is created using this code:

```java
Reader reader = new InputStreamReader(new ByteArrayInputStream(bytes),Charset.forName("UTF-8")); 
```

Consider replacing it with this: 

```java 
// Save the incoming file into a temp location then.. 
String filePath = "path/to/your/large/file.txt";
int bufferSize = 8192; 
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(filePath), Charset.forName("UTF-8")), bufferSize)) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Process each line as it is read
                System.out.println(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

1. **BufferedCsvReader:** Implement a new BufferedCsvReader component that can read a specified number of rows from a CSV file at a time. 
3. **Memory Efficiency:** Verify that the component does not load the entire file into memory.

**Comment by jgambarios** [comment]
Closed as fixed in https://github.com/dotCMS/core/issues/29162
