### ISSUE TITLE
Spike: Determine if/how to enable Tomcat to accept UTF-8 characters

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29484]
### Task

Tomcat currently only accepts characters using Latin encoding.  This causes problems when customers use UTF-8 characters, as evidenced by this issue: https://github.com/dotCMS/core/issues/28462.

The current solution to the above referenced issue is to delete characters which Tomcat can't handle properly.  But this is a poor solution.

So, we need to identify how to enable Tomcat to handle UTF-8 characters, so customers can use these characters in their file names.

This spike is to answer whether any of the following can resolve this limitation.  We should try these in order, and stop when we find one that offers a solution without significant drawbacks.
1. Change the configuration of the current Tomcat version.
2. Upgrade Tomcat to a newer version (without a config change).
3. Upgrade Tomcat to a newer version AND change the Tomcat configuration.
4. None of the above (it's not possible with any released versions of Tomcat).

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

1. Identify specific changes required to enable Tomcat to properly handle non-Latin characters.
2. If a solution was found, create a card (or Epic) to do the necessary work.

**Comment by jcastro-dotcms** [comment]
As per conversation with @dsolistorres , enabling/disabling UTF-8 character support can be done in our current Tomcat version:

https://github.com/dotCMS/core/blob/683ff1be59c280f497e40e99ce5a941994290657/parent/pom.xml#L64

The required code change was implemented via the following PR:

* https://github.com/dotCMS/core/pull/29766
