### ISSUE TITLE
Spike: Determine changes needed to Clickhouse and CubeJS schemas needed to support Content Analytics

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29481]

**Comment by wezell** [comment]
I would also add - we should question the assumption that we need to use CubeJs at all in the content analytics pipeline?  It is possible to query clickhouse directly and avoid the complexity of cubeJs completely.

**Comment by victoralfaro-dotcms** [comment]
@wezell yes you are correct. I mentioned it because that was my automatic answer when it comes to this kind of infrastructure.

**Comment by freddyDOTCMS** [comment]
Here the Documentation where I explain  what we need to do here

https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/view#heading=h.yow0ow19galg
