### ISSUE TITLE
Show the path in selected items

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29489]
### Parent Issue

https://github.com/dotCMS/core/issues/28493

### User Story

When a user selects an item, the path of each selected item should show the proper path.

![image](https://github.com/user-attachments/assets/5ecede23-20f7-4ac9-8a38-ba005ad2b996)

### Acceptance Criteria

Show the path in selected items

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
![Screenshot 2024-08-08 at 10 12 38 AM](https://github.com/user-attachments/assets/d7718d5c-b1ee-4e15-97f5-dd287be527d7) |  ![Screenshot 2024-08-08 at 10 13 00 AM](https://github.com/user-attachments/assets/adc50f51-7d71-4a97-85f9-9c6cc19ffa8c)

**Comment by hmoreras** [comment]
Pass internal QA: 

Now I see the path of the selected categories under the root or a deeper path. 

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/02096797-854b-4321-922c-4325d74d6e01">

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_78bb755**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-08-16 at 9 58 57 AM](https://github.com/user-attachments/assets/fb3281eb-44e7-4888-816f-2c84c81cdc17)

**Comment by dsilvam** [comment]
Passed IQA: Showing the category path for the recently selected cats (before saving). 



![Image](https://github.com/user-attachments/assets/304557e6-33e4-4977-9a18-e0ea4d48d64f)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_600b4f3**, Docker, macOS 14.5, FF v126.0.1
