### ISSUE TITLE
$host.childrenFolders not getting inode, instead getting identifier

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#29492]
### Problem Statement

Customer has the following set `#foreach($folder in $host.childrenFolders)` and then in their $dotcontent.pull they have  `+conFolder:${folder.inode}...` the folder.inode is returning the idenfitier in the folders table of the db instead of the inode which is causing it to not correctly pull any folder where the inode does not match the identifier. They use this to track the number of launched sites as well as details about the sites, and post upgrade this number has gone from about 690 to 35. 

### Steps to Reproduce

The following code in the Velocity tool will show that identifier and inode are the same instead of being different in the database. 

`#foreach($folder in $host.childrenFolders)
    Title     : $folder.title
    Identifier: $folder.identifier
    iNode     : $folder.inode
    ------------------
#end`

### Acceptance Criteria

Ensure that when going through $host.childrenFolders it's setting .inode to inode and .identifier to identifier

### dotCMS Version

23.10

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117242

**Comment by jdotcms** [comment]
Folders are not versionables, this means the folder inode is the same of a folder identifier since folder do not have inodes/versions
Closing the issue

**Comment by jdotcms** [comment]
One extra note: alternative could do a content search where the "+parentPath:/ +host:{hostId}"

**Comment by josemejias11** [comment]
**QA Comment**

```velocity-template-language
#foreach($folder in $host.childrenFolders)
    #set($inode = $folder.inode)
    #set($identifier = $folder.identifier)

    Title     : $folder.title
    Identifier: $identifier
    iNode     : $inode
    ------------------
#end
```
