### ISSUE TITLE
[Query Tool] : Add the Lucene query in the current session

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#29520]
### User Story

As a dotCMS user/developer, I want to be able to make the `Lucene Query` field in the **Dev Tools > Query Tool** portlet remember the last query I entered.

When troubleshooting or testing new features, we tend to go back and forth between the **Query Tool** portlet and other portlets and test a Lucene query. It'd be a lot easier if dotCMS could remember the last Lucene query that was entered so that you wouldn't need to re-type it, or copy it from another app, specially when dealing with long or complex queries.

### Acceptance Criteria

* Go to the **Dev Tools > Query Tool** portlet, and enter a Lucene query.
* Go to any other portlet.
* Go back to the **Dev Tools > Query Tool** portlet. The Lucene query you enter before should be there.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by victoralfaro-dotcms** [comment]
Query remains after being used in the Query Tool portlet.

https://github.com/user-attachments/assets/5eb304fc-dc4b-49c1-94b1-e809ba195532

**Comment by bryanboza** [comment]
We need some work here: 

Seems we are changing this query after navigate in some of the portlets 
https://github.com/user-attachments/assets/4a22eee6-3bbc-4bad-b90e-cd630701961d

@victoralfaro-dotcms, since the GD issues no longer require QA, we'll need to make a few extra clicks for the IQA work.

**Comment by dsilvam** [comment]
Passed IQA: Tested navigating to a bunch of different portlets and the last lucene query gets remembered in the Query Tool screen.
