### ISSUE TITLE
Login-as popup show's in the incorrect position.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29534]
### Problem Statement

After interact with the Login-as menu, the second time shows in a incorrect position: 

### Steps to Reproduce

https://github.com/user-attachments/assets/c2d56c32-37d8-46eb-b33f-16f6c85dfeda

### Acceptance Criteria

Login-menu should show always in the top left corner, like the first time. 

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_7ad6b2a**, Docker, macOS 14.5, FF v126.0.1
