### ISSUE TITLE
Content Types - copy modal - hidden site/folder dropdown.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29536]
### Problem Statement

In the content type screen, in the copy action of any content type, the Site or folder dropdown don't load / show correctly in Firefox when open then dialog. 

### Steps to Reproduce

https://github.com/user-attachments/assets/95c602d9-813e-46c9-a352-f57d6fc7287c

### Acceptance Criteria

should load and show the dropdown at one. 

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by hmoreras** [comment]
Note to QA: 

Before: 

https://github.com/user-attachments/assets/b2ff59c4-84ac-4fe5-9836-78b0f7c90dc8

After: 

https://github.com/user-attachments/assets/afa6ce2c-6e5a-4796-b8d6-678e5c4ed6d8

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9f3fb00**, Docker, macOS 14.5, FF v126.0.1
