### ISSUE TITLE
SDK: Improve @dotcms/client Documentation 

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#29558]
### Task

As a developer using the`@dotcms/client` library, I want the documentation to be clear, comprehensive, and easy to follow, so that I can effectively utilize the library in my projects.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

1. **Update README**:
    - Provide a clear and concise introduction to the library and its purpose.
    - Clearly state any dependencies or prerequisites needed to use the library.
2. **Enhance JSDoc Comments**:
    - Ensure all functions, methods, and classes have updated and detailed JSDoc comments.

### Assumptions & Initiation Needs

Here is a list of the most important JSDoc annotations:

- `@param` - Documents the parameters of a function.
- `@returns` or `@return` - Documents the return value of a function.
- `@typedef` - Defines custom types.
- `@property` - Documents properties of an object.
- `@example` - Provides example usage of the function or method.
- `@throws` - Documents the exceptions that a function might throw.
- `@deprecated` - Marks a function or method as deprecated.
- `@see` - Provides a reference to related information.
- `@async` - Indicates that a function is asynchronous.
- `@callback` - Documents a callback function.

### Quality Assurance Notes & Workarounds

- Ensure that the documentation is consistent and follows a uniform style.
- Include practical examples and use cases in the README to help developers understand how to implement the library in their projects.
- Review and test the documentation to ensure accuracy and completeness.
- Include practical examples and use cases for exported functions

**Comment by nollymar** [comment]
The readme file looks good to me and the .ts files where verified by the PR reviewers
