### ISSUE TITLE
Legacy Edit Content: Validation on Tags component is not working correctly

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#29559]
### Problem Statement

In the video below we can see how the Persona tags have the correct style, however we have noticed the tag length validation isn't working well. The error message says the maximum length for a tag is 255 character, but the real limit is under 200 characters. We have tested with:

- 150 characters (worked fine)
- 200 characters (failed)
- 199 characters (worked fine)

https://github.com/user-attachments/assets/dd896303-80e3-4fa6-9c42-a124f7c28804

Reported by: @dcolina 

### Steps to Reproduce

1. Open theLegacy Edit Content on a Content Type with a Tags component as Personas Content Type (Showed in video)
2. Add a tag with more than 200 characters 
3. See the error

### Acceptance Criteria

We should be able to save tags with more than 200 characters and 255 as max length

### dotCMS Version

trunk-latest

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by valentinogiardino** [comment]
### Response to Problem Statement

Could not reproduce the issue described. Everything appears to be functioning as expected based on the acceptance criteria. Testing was conducted on the `trunk_0b665e2` branch, and the tag length validation works correctly, allowing tags up to 255 characters.

**Test Results:**

- **Test**: Tag with a single word of 255 characters  
  **Result**: Successfully saved ✅
  
- **Test**: Tag with a single word of 256 characters  
  **Result**: Error message displayed as expected ✅
  
- **Test**: Tag with a string of 255 characters  
  **Result**: Successfully saved ✅
  
- **Test**: Tag with a string of 256 characters  
  **Result**: Error message displayed as expected ✅

https://github.com/user-attachments/assets/6e3e9f0a-3181-4885-a986-75867ef7a0d4

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_14609ff**, Docker, macOS 14.5, FF v126.0.1
