### ISSUE TITLE
Fix blinking effect during category loading

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29564]
### Problem Statement

There is a small visual glitch occurring during the loading of categories. Each category briefly blinks as it's being loaded, which creates a distracting and potentially jarring user experience. This issue affects the overall smoothness and polish of the category display interface.

### Steps to Reproduce

1. Navigate to the page or component where categories are displayed.
2. Observe the loading process of the categories.
3. Notice that each category momentarily blinks or flashes as it appears.

### Acceptance Criteria

1. Categories load smoothly without any visible blinking or flashing effect.
2. The loading process appears seamless and professional to the end-user.
3. No negative impact on the loading speed or performance of the category display.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nicobytes** [comment]
https://github.com/user-attachments/assets/a91e3439-74d3-4546-b297-9955d9fece35

**Comment by dsilvam** [comment]
Passed IQA: No blinking effect when selecting categories with or without children.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_78bb755**, Docker, macOS 14.5, FF v126.0.1
