### ISSUE TITLE
UVE: Page content is deleted after change page properties

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#29569]
### Task

VTL:

https://github.com/user-attachments/assets/a3b0419f-dc24-4147-8019-04aed0d8406f

Headless:

https://github.com/user-attachments/assets/7cf8d081-9b74-4b75-b749-50f3b68e4164

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
We have an small console error. Although it not the fix for this issue. I'm linking the PR to this. We are still working on the main issue.

**Comment by bryanboza** [comment]
Fixed, now I'm unable to reproduce, we are not refreshing the page properties after change something but this was fixed in the new editor here: https://github.com/dotCMS/core/pull/29695
