### ISSUE TITLE
Implement ellipsis for long category names to prevent horizontal scrolling

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29568]
### Problem Statement

Modify the category display component to add ellipsis to category names that are too long, preventing horizontal scrolling and improving the overall user interface.

### Steps to Reproduce

1. Open the category selection interface.
2. Navigate to the 3rd or 4th level of the category hierarchy.
3. Locate a category with a very long name.
4. Observe that the long name pushes the container boundaries.
5. Notice the appearance of a horizontal scrollbar (scroll-x).

### Acceptance Criteria

1. Long category names are truncated with ellipsis (...) when they exceed the available width.
2. No horizontal scrolling occurs due to long category names, even at deep category levels.
3. The full category name is visible on hover (e.g., via tooltip).
4. The layout remains consistent and visually appealing for all category name lengths.
5. The fix is applied consistently across all levels of the category hierarchy.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nicobytes** [comment]
IQA passed with **trunk_cc63b1d**

The categories with long titles will be succesfly truncated.

![Image](https://github.com/user-attachments/assets/703ac57f-80a2-4219-8828-cb403aebb48f)


I suggest this same behavior is the breadcrumbs.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e622545**, Docker, macOS 14.5, FF v126.0.1
