### ISSUE TITLE
Remove Black Border When Expanding Left Navigation Bar using FF to navigate in the dotCMS Backend

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29577]
### Problem Statement

When users expand the left navigation bar in the dotCMS backend, a black border appears, which is inconsistent with the overall design of the interface. This visual inconsistency can detract from the user experience and disrupt the clean and professional appearance of the backend interface.

![image](https://github.com/user-attachments/assets/3b890733-0efb-41df-b866-679985f25967)

### Steps to Reproduce

- Log into the dotCMS backend with the necessary credentials.
- Navigate to any section where the left navigation bar is present.
- Expand the left navigation bar.
- Observe that a black border appears around the expanded navigation bar.

### Acceptance Criteria

- **Remove Black Border:** Ensure that the black border is removed when the left navigation bar is expanded in the dotCMS backend.
- **Consistent Design:** The expanded navigation bar should seamlessly integrate with the rest of the interface, maintaining a consistent design and color scheme in all the supported browsers 

### dotCMS Version

Tested on the latest trunk [ trunk_761ef08 ] // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by valentinogiardino** [comment]
### IQA Passed Internal

- Tested on docker image: `[dotcms/dotcms:trunk_ 1c414a1]`

#### Chrome:

https://github.com/user-attachments/assets/f8a4d954-b050-4b8a-a921-428506cb337b

#### Edge:

https://github.com/user-attachments/assets/bb0509ec-0de4-4ccd-9e97-f5510b70a35d

#### Firefox:

https://github.com/user-attachments/assets/b5609924-a830-40ec-9fbb-2ccd25c4224f

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
