### ISSUE TITLE
UVE: Page content is deleted when change language

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#29572]
### Task

When we change the language we should see an empty page if we create a translation otherwise we should see the translated page. 

VTL:

https://github.com/user-attachments/assets/f7bc7cb3-a6cf-428b-9783-ba116aff75d8

Headless:

https://github.com/user-attachments/assets/3ca37393-ed7c-4255-a8f5-df11b242a2ff

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

We should be able to see the page when we change the language or translate if the page does not exist.

**Comment by rjvelazco** [comment]
There is a edge-case scenario related to the UVE and template that we are going to solve here: https://github.com/dotCMS/core/issues/29671

**Comment by bryanboza** [comment]
We need some work here: 

After test in the latest trunk image generated [trunk_e622545], I'm getting this behavior which is weir and need some work 

https://github.com/user-attachments/assets/2a868e8a-8a3b-48ec-b427-ab4fd25806e5

**Comment by bryanboza** [comment]
**Note to QA again this card:**

We recommend retest the whole functionality in the regular page editor and also using the UVE editor in both technologies 
(NextJS and Angular)

**Comment by dcolina** [comment]
## Internal QA: Failed.

When creating a new version of a page in `Spanish` **from an existing** `English` page, and then attempting to swap back from the new Spanish version to the original English version, an unusual error message appears: "This URL does not exist (The page you are trying to access does not exist)." However, when re-entering the edit mode, the error does not reappear, indicating an inconsistent behavior in the flow.


https://github.com/user-attachments/assets/1f4b99d9-2d84-4c15-8aaa-aed18ffae8d5

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_4a9aadf**, Docker, macOS 14.5, FF v126.0.1
