### ISSUE TITLE
UVE: Copy URL Button doesnt work

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#29570]
### Task

https://github.com/user-attachments/assets/761990a2-1cc7-4478-9173-506e606bdf35

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by valentinogiardino** [comment]
# Passed Internal QA
Now `Copy URL` button works as expected
- Tested on docker image: `[dotcms/dotcms:trunk_52d3299]`
## Video

https://github.com/user-attachments/assets/fe1b9e97-c023-4ebf-b4e5-9c2c099cb576

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_46b0a3d**, Docker, macOS 14.5, FF v126.0.1
