### ISSUE TITLE
Daniel: Drop Everything & Learn Aug 14 - Aug 27

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29598]

**Comment by dcolina** [comment]
I started the full example implementation (full cicd) of this course:

[Icono del autorUdemy Business
The Complete GitHub Actions & Workflows Guide
Automate Code Testing, Deployment &amp; Versioning using CI/CD Workflows. Create &amp; Publish GitHub Actions to the Marketplace

Imagen del curso adjunta
★★★★★ 4.69 (3498 calificaciones)](https://dotcms.udemy.com/course/github-actions/)
