### ISSUE TITLE
Fix Alignment and UI Issues in Settings Configuration Portlet

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29619]
### Problem Statement

The settings configuration portlet currently appears misaligned and has various UI problems, which detracts from the user experience and can lead to confusion or difficulty in managing settings. These issues need to be addressed to ensure a clean, consistent, and user-friendly interface.

![image](https://github.com/user-attachments/assets/aee64cb5-d74e-4bc9-87dc-a99651908338)

### Steps to Reproduce

- Log into the application with the necessary credentials.
- Navigate to the settings configuration portlet.
- Observe the alignment and UI issues, such as misaligned elements, inconsistent spacing, or other visual defects.

### Acceptance Criteria

- **Correct Alignment:** Ensure that all elements within the settings configuration portlet are properly aligned, following the design guidelines used throughout the application.
- **Consistent Spacing:** Apply consistent spacing between elements to enhance readability and visual appeal.
- **Responsive Design:** Ensure that the portlet is responsive and displays correctly on various screen sizes and devices.

### dotCMS Version

Tested on trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed IQA: Shows without alignment issues now. 
Tested on Arc + Chrome + Firefox.

![Image](https://github.com/user-attachments/assets/ed0d3f87-3c41-4687-851d-7ebf2b46fe34)

**Comment by bryanboza** [comment]
Fixed, this looks better now. Tested in trunk // Docker // FF
