### ISSUE TITLE
Create GHA to add Next Release label

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#29618]
### Task

Occasionally, we may overlook adding the "Next Release" label to issues that do not require QA ("QA Not Needed"). This oversight can pose challenges when tracking the inclusion of a fix.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

When the `QA Not Needed` label is added, we should add the label `Next Release`. We should validate the following cases:

- The issue title does not contain `Drop Everything & Learn`
- The label `Type: CI/CD` was not added.

**Comment by dsilvam** [comment]
Passed IQA: working as expected
