### ISSUE TITLE
Be able to hide "Forms" from the Content tab in Edit mode. 

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#29621]
### User Story

As a page designer, I want to be able to hide Forms from the content tab in the Page edit mode, so I can only see the exact content types I want to go into containers. 

I have included the screenshot provided by the customer to show exactly where. 

### Acceptance Criteria

Be able to hide the "Forms" content type 

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117725

<img width="1399" alt="Forms component being shown" src="https://github.com/user-attachments/assets/521746de-22b6-4da4-94e9-dc999c58e623">

**Comment by rjvelazco** [comment]
Hey, @jdcmsd!

I think we need to add this feature to the documentation. We have a configuration variable called `CONTENT_PALETTE_HIDDEN_CONTENT_TYPES` that allows you to prevent certain content types from appearing in the palette. This variable accepts `content types`/`widget` variables separated by commas.

**Example**

```.properties
CONTENT_PALETTE_HIDDEN_CONTENT_TYPES=Activity,Forms
```

**In docker files, users need to add the `DOT_` prefix**

```.yml
environment:
 - DOT_CONTENT_PALETTE_HIDDEN_CONTENT_TYPES==Activity,Forms,VariableId3
```

**Comment by rjvelazco** [comment]
@fmontes @jdcmsd Seems like this configuration variable is already in the `docs`: [Content Palette Displayed Types
](https://www2.dotcms.com/docs/latest/universal-visual-editor#ContentPaletteDisplayedTypes)


![Content Palette Displayed Types](https://github.com/user-attachments/assets/01778bd4-4a2f-4a73-9c66-057bc883d08a)

**Comment by jdcmsd** [comment]
I forgot that I added it months ago 😅

**Comment by dsolistorres** [comment]
Internal QA Approved:
- Adding content type variables to the configuration property `CONTENT_PALETTE_HIDDEN_CONTENT_TYPES` will hide the specified content types from the content palette on the Page edit window.
