### ISSUE TITLE
dotcms/editor-content: Use the new Angular Syntax

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29625]
### Parent Issue
https://github.com/dotCMS/core/issues/29048

### Task

Using the command `nx g @angular/core:control-flow` to migrate to the new Angular syntax

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
Manual test to edit content

https://github.com/user-attachments/assets/0ec5fd6f-81d6-43dc-b50b-df1346ff724e

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_fa74e31**, Docker, macOS 14.5, FF v126.0.1
