### ISSUE TITLE
Update pom file with the latest empty starter

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#29642]
### User Story
As part of the automated process for generating starters, it's necessary to add a step that updates the main project's `pom.xml` file to reference the newly created empty starter and automatically create a pull request for this change. Additionally, it is essential to create and include documentation that details the workflow involved.

### Acceptance Criteria
- The automated process for generating empty starters includes a step to update the main project's `pom.xml` file to reference the new empty starter.
- A pull request is automatically created for the changes made to the `pom.xml` file.
- Documentation is created and included that accurately describes the updated workflow, including the steps for updating the `pom.xml` file and creating the pull request.

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### dotCMS Version
N/A

### External Links
N/A

### Assumptions & Initiation Needs
- Access to modify the main project's `pom.xml` file.
- Ability to automate pull request creation through the CI/CD platform.
- Knowledge of the existing automated starter generation process.
- Familiarity with the documentation standards and requirements for the project.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by sfreudenthaler** [comment]
minted and stored key https://keepersecurity.com/vault/#detail/KaarCDJ13qNX9r4c4xAcng

**Comment by sfreudenthaler** [comment]
Looks like permissions needed are already available as `CI_MACHINE_USER` and `CI_MACHINE_TOKEN`

REF: https://github.com/dotCMS/core/issues/27392
