### ISSUE TITLE
SDK: Unable to use @dotcms/client library in nextra due to import error

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29647]
### Problem Statement
Users are unable to utilize the `@dotcms/client` library in [nextra](https://nextra.site) due to errors with the imports.

### Steps to Reproduce
1. Run this nextra project: [dotcms-nextra-1.0.0.tgz](https://github.com/user-attachments/files/16665464/dotcms-nextra-1.0.0.tgz) (use yarn)
2. Go to page `http://localhost:3000/dotcms`
3. See the error

### Acceptance Criteria
`@dotcms/client` should work in nextra

### External Links
- [Slack conversation](https://dotcms.slack.com/archives/C06QBJS7ZPW/p1724097778974199)

### Assumptions & Initiation Needs
- We need to clean up the way we export the modules.

### Quality Assurance Notes & Workarounds
- Workaround: it works if you import like this:

```
import {DotCmsClient} from '@dotcms/client/src/lib/client/sdk-js-client';
```

**Comment by valentinogiardino** [comment]
### IQA Passed Internal
- Tested with `"@dotcms/client": "0.0.1-alpha.32"`
- Now `import { DotCmsClient } from '@dotcms/client';` works in nextra

https://github.com/user-attachments/assets/46f4a8b7-6115-4655-b664-c11518ac777b

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk and now we are able to compile without problems.
