### ISSUE TITLE
[Logging] : Log less page details when making an unauthorized GraphQL request for a working page (edit mode)

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#29651]
### Problem Statement

We are logging too much information about a page when making a GraphQL request for a working page (edit mode) without authentication.
![image](https://github.com/user-attachments/assets/bb3ea6cd-cadf-45fb-9234-4706563928b7)

### Steps to Reproduce

- Make a GraphQL request for a working page (edit mode) without authentication. For example:
```
query {
  page(url: "/index", pageMode: "WORKING") {
    title
  }
}
```
- Inspect the logs

### Acceptance Criteria

- [ ] The log should show less information about the page

### dotCMS Version

Tested on `trunk_52d3299`

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Slack conversation: https://dotcms.slack.com/archives/CQNF9PCFQ/p1723654751826279

**Comment by bryanboza** [comment]
We still needing some work here: 

- Basically now we are not returning extra information about the piece of content, but now we are returning two errors in the log that is duplicating the failure, and at the end we are printing a WARN with the graphQL schema that we can exclude from the log. 
LOG: https://gist.github.com/bryanboza/9ae75b31303fbe5d6055ae23a544eba9

**Comment by nollymar** [comment]
@bryanboza we will remove the duplicate. 

The warning is logged by a third-party library. Therefore, that logging level can be defined in the log4j configuration.

**Comment by dcolina** [comment]
## Internal QA: Passed.

As we can see in the following image, the error message is now showing the minimal information required to report the error.

**Request:**
![Image](https://github.com/user-attachments/assets/ac17112e-1ba3-4466-a714-cc9c1cdf64a8)

**Log trace:**
![Image](https://github.com/user-attachments/assets/9c56836e-3d5f-40ef-8fdf-7e412b68f894)

It was tested using the docker image `dotcms/dotcms:trunk_042b378`

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
