### ISSUE TITLE
Update `CLEANUP_BUNDLES_OLDER_THAN_DAYS` default value to 4

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#29667]
### Task

We've got your back! We'll update the default value of `CLEANUP_BUNDLES_OLDER_THAN_DAYS` to 4, which will be super helpful for our support team since bundles have a habit of disappearing over the weekend.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### Acceptance Criteria

Update default value to 4

**Comment by bryanboza** [comment]
Fixed, tested by @erickgonzalez in a local env. Now it is working every 4 days.
