### ISSUE TITLE
Import current DNS records into new terraform state

### ISSUE THREAD

**Issue by sfreudenthaler** [dotCMS/core#29683]
### Parent Issue

https://github.com/dotCMS/private-issues/issues/137

### User Story

As a security engineer,
I want to be able to see metadata about dns records (e.g. version history, reason for change, etc)
so that I can more easily prune hanging DNS records that present a security risk 

### Acceptance Criteria

* all human managed DNS records for `dotcms.com` domain should be 
1. codified in the [infrastructure-as-code repo](https://github.com/dotcms/infrastructure-as-code)
2. existing records should be imported to a new terraform state 
* DOES NOT need to be under a managed IaC pipeline (e.g. Atlantis) 

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 3 - Average

**Comment by sfreudenthaler** [comment]
working in branch https://github.com/dotCMS/infrastructure-as-code/tree/terraform-route53-dotcmscom

**Comment by cobbg** [comment]
Now working in branch: https://github.com/dotCMS/infrastructure-as-code/pull/4690

Changed branches to simplify things.
