### ISSUE TITLE
New Content Edit: Remove label for constant field

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29690]
### User Story

The purpose of the constant field is to allow the content architect to define constant values that can be referred to via code (HTML, velocity, etc.).  The values are not intended o be visible to the content editors, so the field, and the value it contains, should not show on the content edit screen.

### Acceptance Criteria

1. The label for a constant field should never show on the content edit screen.
2. The value of a constant field should never show on the content edit screen.
    * This is true no matter what the value is.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by john-thomas-dotcms** [comment]
@hmoreras to summarize our Slack convo, in the existing Content Edit screen, if a Constant field has a Hint set, then although the field itself doesn't show (not even the title), the hint tip does.  This is a bug in the current screen, and we're not going to duplicate that behavior in th new content edit.

Instead, in the new content edit screen, we should:
* Disable the hint property for both the Constant field and Hidden field types.
* Don't show a hint bubble if either of those field types have a hint set (just ignore it).

@jdcmsd I'm putting the "Needs Doc" label on this one for this specific change ^.  It's actually a bug fix, but it mean that if any customers have a Hint set on a custom field now, that Hint won't work when the new content edit screen is released.

The actual number of customers with this specific config is probably zero, so we don't need to list this as a breaking change or anything like that.  But we should doc it in the release notes just in case.

**Comment by dsilvam** [comment]
Passed IQA: 
1. No hint field when adding a constant field 
2. No hint field when adding a hidden field
3. No hint displayed when editing content with either field types even if there's a hint present in the db for them.
4. No label displayed for either constant or hidden fields.

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_c50d421**, Docker, macOS 14.5, FF v126.0.1
