### ISSUE TITLE
New Content Edit: Implement File field

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29691]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### User Story

As a content editor, I want to be able to easily populate a File field, by either selecting a file already in dotCMS, or adding a new file to dotCMS.

### Acceptance Criteria

1. Adhere to the UX design.
    * Designs for both fields are in the design system [here](https://www.figma.com/design/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?node-id=3744-112387).
2. For the File field, provide the following options in the field \(not in the popup\):
    * Main field area:
        * `Drag and Drop of Choose file to upload`
    * Right-side Links:
        * `Select Existing File`
            * When selected, open a popup to select the file.
            * This popup should be the same as other content selection popups \(such as in the Relationships field\).
        * `Import from URL`
            * When selected, open a popup for the user to enter the URL.
            * If the URL doesn't resolve to an appropriate file, the popup should stay open and display the error \(rather than closing\).
        * `Create New File`
            * When selected, open the content edit window for a new file.
            * The "state" of the content edit window needs to be maintained, so that when the new file is saved, the user is returned to the original content item that contains the File field.
3. By default, the content type for any new file should be dotAsset.
    * If the file is imported from a URL, we should choose the dotAsset content type as if the file had been dragged and dropped into dotCMS.
    * If `Create New File` was selected, the default content type should be the generic `dotAsset`.
4. There must be a field variable to allow the content architect to specify a different file content type.
    * If this field variable is set, then the default content type for all new files should be what it specifies.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*
\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29871
- [ ] https://github.com/dotCMS/core/issues/29872
- [ ] https://github.com/dotCMS/core/issues/29874
- [ ] https://github.com/dotCMS/core/issues/29875
- [ ] https://github.com/dotCMS/core/issues/29873
`\`\`

**Comment by hmoreras** [comment]
IQA Note: 

FF needed:    ` DOT_CONTENT_EDITOR2_ENABLED: true`

Test cases: 

- Drag and drop ( working ) 
- Chose file ( working ) 
- Importe for URL ( working ) 
- Create new file txt and vtl ( working )

Once a file is loaded: 

- The information dialog is working and every copy button in th different paths work as expected
- Download button ( working ) 
- remove button (working )


There must be a field variable to allow the content architect to specify a different file content type : checking...
