### ISSUE TITLE
New Content Edit: Implement Image field

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29692]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### User Story

As a content editor, I want to use the new Image field in the new content edit screen, so I can easily select existing images, or upload new images.

### Acceptance Criteria

1. Adhere to the UX design.
    * The design in the design system is [here](https://www.figma.com/design/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?node-id=3744-112387). 
2. Provide the following options in the Image field (not in the popup):
    * Main field area:
        * `Drag and Drop or Choose file`
    * Right-side Links:
        * `Select Existing Image`
            * When selected, open a popup to select the image file.
            * This popup should be the same as other content selection popups (such as in the Relationships field).
        * `Import from URL`
            * When selected, open a popup for the user to enter the URL.
            * If the URL doesn't resolve to an appropriate file, the popup should stay open and display the error (rather than closing).
        * `Generate with dotAI`
            * When selected, open the dotAI image generation popup.
3. By default, the content type for any new image should be dotAsset.
    * If the image is imported from a URL, we should choose the dotAsset content type as if the image had been dragged and dropped into dotCMS.
    * If `Create New Image` was selected, the default content type should be the generic `dotAsset`.
4. There must be a field variable to allow the content architect to specify a different file content type.
    * If this field variable is set, then the default content type for all new images should be what it specifies.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/30059
- [ ] https://github.com/dotCMS/core/issues/30061
- [ ] https://github.com/dotCMS/core/issues/30062
- [ ] https://github.com/dotCMS/core/issues/30060
```

**Comment by oidacra** [comment]
IQA:
### No dotAI active, make disabled the button of AI image generation.
![CleanShot 2024-12-04 at 11 21 18@2x](https://github.com/user-attachments/assets/f894ba4c-4382-454b-bbb1-65da34bbfb7c)
