### ISSUE TITLE
Page Properties Cache TTL label not showing units when creating a new Page Type

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#29708]
### Parent Issue

https://github.com/dotCMS/core/issues/23074

### Task

Both the Full and Empty Starters were updated to have the `Cache TTL` field label in a Page Content Type to display its units, which is `Cache TTL (seconds)` now. However, there's one more case that was missed: When you create a new Content Type of type Page, the label still reads `Cache TTL`.

### Proposed Objective

Core Features

### Proposed Priority

Priority 4 - Trivial

### Acceptance Criteria

* Go to the **Content Model > Content Types** portlet and click the `+` button to create a new Content Type of type `Page`.
* You'll see that the cache TTL field still reads `Cache TTL`, and not `still reads `Cache TTL (seconds)`.

### Assumptions & Initiation Needs

This is the line that must be updated: 

https://github.com/dotCMS/core/blob/0b665e2f4cde82e4c3bfa801ba47de597d6348e2/dotCMS/src/main/java/com/dotcms/contenttype/model/type/PageContentType.java#L138

**Comment by dsilvam** [comment]
Fixed already

**Comment by victoralfaro-dotcms** [comment]
Label shows as expected
![image](https://github.com/user-attachments/assets/eb321587-18d0-46a6-94f5-57e93dbfe302)

**Comment by dsilvam** [comment]
Passed IQA: Showing the proper label for the Cache TTL field, including seconds, for new types of base type "Page".

![Image](https://github.com/user-attachments/assets/0520f561-410f-488e-918b-9e7128a4db42)
