### ISSUE TITLE
Analytics: Encapsulate broadcast and create emitters layer

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29713]
### Parent Issue

[https://github.com/dotCMS/core/issues/29476](https://github.com/dotCMS/core/issues/29476)

### User Story

As part of the Analytics infrastructure; we need to encapsulate the broadcast (local system events)  and create an emitter layer.

The ideas behind this effort will be:
1) if the local system events can not scale very well in the future, we can replace for a more robust solutions such as an queue event bus or so.
2) Avoid the coupling with the Local System Event to be able to switch implementations if needed.

The Emitters layer will use the broadcast to create the event and populate with the collector bean created on the previous step, the emitter will wrap the information into an event type with a payload, this payload could be 1 to 1 with the collector bean, a projection/subset or even a transformation.
The emitter will send the Event built through the event bus.

### Acceptance Criteria

We will have the emitter to fire the events needed to track the analytic kind of information

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by john-thomas-dotcms** [comment]
No longer needed, the existing architecture is working for current needs and loads.
