### ISSUE TITLE
Analytics: Create Collectors Layer

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29712]
### Parent Issue

https://github.com/dotCMS/core/issues/29476

### User Story

As part of the Analytics infrastructure; we need to create a collectors layer
We can think on two kind collectors:
1) syn collectors; which are in charge of collect information from the request, session, app and so on but in the same request thread scope
2) async collectors; which are in charge of collect information from session, app and so on but in a separated thread, the intention behind this is to avoid to delay the current request thread execution by doing cpu times by gathering information
In addition the clients might add collectors programatically by OSGI

### Acceptance Criteria

We need to create a collector to gather information for the following events:

- PAGE_REQUEST: Triggered when a page is accessed.

- FILE_REQUEST: Triggered when any file is accessed. If a page is accessed and requests a file (e.g., an image, JS, CSS, etc.), two events will be triggered: one for the page as a PAGE_REQUEST and another for each file as a FILE_REQUEST. Files can be loaded using the following endpoints:

     - /dA/... Endpoint. More info [here](https://www.dotcms.com/docs/latest/image-resizing-and-processing).
     - /contentAsset Endpoint. More info [here](https://www.dotcms.com/docs/latest/image-resizing-and-processing).
     - /dotAsset Endpoint. More info [here](https://www.dotcms.com/docs/latest/file-assets-and-dotassets).
     - By directly using the file's URI in the URL.

- URL_MAP: Triggered when a URL map is used. In this case, two events are triggered: one for the URL_MAP and another for PAGE_REQUEST (the second one corresponds to the detailed page request).

- VANITY_REQUEST: Triggered when a vanity URL is used. If the vanity URL forwards internally, two events will be triggered: the first one as a VANITY_REQUEST, and the second one could be either a FILE_REQUEST or a PAGE_REQUEST, depending on the forward destination.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by wezell** [comment]
Just to be clear, we have these already.  See:

https://github.com/dotCMS/core/tree/master/dotCMS/src/main/java/com/dotcms/visitor/filter/characteristics

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/29791)

**Comment by freddyDOTCMS** [comment]
**Note to QA**: Steps to test:

- Start dotCMS with the full starter
- Start Analytics to this just: Go to ""/core/docker/docker-compose-examples/analytics"" and run the command "docker-compose up", and wait a couple of minutes, Configure the Analitycs App in dotCMS with the follow parameters:

ClientIId: analytics-customer-customer1
Client Secret: testsecret
Analytics Config URL http://localhost:8088/c/customer1/cluster1/keys
Analytics Write URL http://localhost:8081/api/v1/event
Analytics Read URL http://localhost:4001/

- Navigate by the dotCMS FE.
- Start cubsJS UI in "localhost:4001" and play around with it

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: The CA data for PAGE, FILE, URL MAP and Vanity URL are been collecting as expected

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a12617a**, Docker, macOS 14.5, FF v126.0.1


![Screenshot 2024-10-04 at 8 40 45 AM](https://github.com/user-attachments/assets/7941e21a-cc8e-49f6-b4c3-9a115119063b)
