### ISSUE TITLE
Analytics: Create the Matcher Layer

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29711]
### Parent Issue

[https://github.com/dotCMS/core/issues/29476](https://github.com/dotCMS/core/issues/29476)

### User Story

As part of the Analytics infrastructure; we need to create a matcher layer
The matcher layer will give us the ability to catch functionalities by catching the url, it could be an exact match, or wildcard pattern + one of more verbs (GET, POST, PUT, DELETE, etc)
In addition the clients might add matchers programatically by OSGI

### Acceptance Criteria

We should catch all vanities, urlmaps, apis and all urls we want to track as part of the analytics

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: We are collecting the expected data for Page,File, URL MAP and vanity URL so this mens that the Matcher are working good

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_0028f3c**, Docker, macOS 14.5, FF v126.0.1

Matcher layer Vanity Urls are getting classified as NOTHING in CubeJS
![Screenshot 2024-10-07 at 2 34 01 PM](https://github.com/user-attachments/assets/eded140f-0f38-44ef-96ed-45137550c18b)

**Comment by freddyDOTCMS** [comment]
> **Failed**: Tested on **trunk_0028f3c**, Docker, macOS 14.5, FF v126.0.1
> 
> Matcher layer Vanity Urls are getting classified as NOTHING in CubeJS ![Screenshot 2024-10-07 at 2 34 01 PM](https://private-user-images.githubusercontent.com/129882031/374322042-eded140f-0f38-44ef-96ed-45137550c18b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODc2MDMsIm5iZiI6MTcyODQ4NzMwMywicGF0aCI6Ii8xMjk4ODIwMzEvMzc0MzIyMDQyLWVkZWQxNDBmLTBmMzgtNDRlZi05NmVkLTQ1MTM3NTUwYzE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNTIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDRkNTZjZjFiYzhjYTAwN2E5MmEwYjNhOWYyMTI0ZWQ4ZDFiMGExOGU5Zjc0NWQ5OWJjNjdkYzg1NDI3YmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0DiFwwSwvEgrWsezhaRPkVL6vgIJv5GiS0WmCe1M_DQ)

Really it is not related with this issue so I created a new card for it #30307

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e0e83bd**, Docker, macOS 14.5, FF v126.0.1

Issues added on the comment https://github.com/dotCMS/core/issues/29711#issuecomment-2397843983 will be work on card https://github.com/dotCMS/core/issues/30307
