### ISSUE TITLE
Assess Existing GitHub Actions for Conventional Commits

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#29726]
#### Tasks:
- Research and identify GitHub Actions from the marketplace that enforce conventional commits some examples below
    - [Conventional Commit in Pull Requests](https://github.com/marketplace/actions/conventional-commit-in-pull-requests)
   - [Conventional Commits PR Action](https://github.com/jef/conventional-commits-pr-action)
   - [Conventional Commit](https://github.com/marketplace/actions/conventional-commit)
   - [Conventional PR](https://github.com/marketplace/actions/conventional-pr)
- Test promising actions in our `core-workflow-test` branch
- Document the pros and cons of each tested action

#### Key Considerations:
- Does the action prevent non-compliant PR titles from being committed?
- Is there a clear, actionable notification to the developer on failure?
- Does the action allow for a configurable list of types and scopes?
- Can the list of types and scopes be stored in a separate, script-readable file?
- How are available types and scopes presented to developers? Is selection from options (e.g., labels) possible?
- In case of an error, how quickly and clearly are the correct options provided?

## Testing Guidelines

- Use the `https://github.com/dotCMS/core-workflow-test` branch for all tests
- Create a variety of test PRs to cover different scenarios (valid/invalid titles, different file changes, etc.)
- Document the developer experience for each tested solution, including ease of use and clarity of feedback

## Resources

- [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [GitHub Actions Marketplace](https://github.com/marketplace?type=actions)

## Notes

- This spike is for investigation and documentation. Full implementation will be a separate task.
- Focus on finding solutions that provide the best developer experience while enforcing our commit standards.

**Comment by dcolina** [comment]
## Assessment Results

After thoroughly assessing the available GitHub Actions and comparing their features with the requirements for enforcing conventional commit standards, the **Custom GitHubApp Solution** stands out as the optimal choice. This recommendation is based on its superior flexibility, extensibility, and alignment with scalable DevOps workflows. Below are the key findings and technical reasons supporting this decision.

---

### **1. Configuration Flexibility and Maintainability**
The **Custom GitHubApp Solution** provides advanced configuration options:
- **External configuration support:** Allows the use of JSON or YAML files to define commit types and scopes, enabling centralized control.
  - **Version control-friendly:** Configuration files can be updated independently of the core workflow, ensuring quick adaptability to changes.
  - **Branch-specific customization:** Different configurations can be applied to environments such as development or production.
- **Improved maintainability:** Decouples logic from configuration, reducing the overhead of modifying the GitHubApp code for updates.

---

### **2. Enhanced Developer Experience**
The solution significantly improves the developer experience:
- **In-PR error notifications:** Provides context-specific feedback directly within pull requests, leveraging the GitHub API for detailed guidance.
  - **Customizable messages:** Includes precise error descriptions, suggested fixes, and links to commit message guidelines.
  - **Developer guidance:** Supports prompts for valid commit types and scopes using labels or comments, simplifying compliance.
- **Real-time validation:** Ensures developers receive immediate feedback, reducing time spent troubleshooting errors.

---

### **3. Robust Enforcement and Compliance**
The **Custom GitHubApp Solution** offers superior enforcement capabilities:
- **Blocking mechanism:** Ensures non-compliant pull requests cannot be merged until they meet the commit standards.
- **Granular enforcement:** Can enforce specific rules based on branch requirements or project conventions.

---

### **4. Extensibility and Scalability**
This custom solution is designed for long-term scalability:
- **Extensibility:** Can be enhanced to include additional functionality such as:
  - Mapping commit types to JIRA issues.
  - Enforcing unique scopes or running specific validations based on code changes.
- **Scalability:** Built with a familiar tech stack (e.g., Java), allowing seamless integration with other tools in the CI/CD ecosystem.
- **Adaptability:** Integrates smoothly with complex pipelines and is prepared to adapt to future needs.

---

### **5. Alignment with DevOps Best Practices**
The GitHubApp aligns with modern DevOps principles:
- **Infrastructure as Code (IaC):** Configuration files are managed as code, ensuring consistency and transparency across environments.
- **Continuous improvement:** The solution is easily upgradable, ensuring it can evolve with new requirements or feedback.
- **GitOps alignment:** Fits seamlessly into workflows that prioritize automation and code-driven configurations.

---

## Technical Summary
In summary, the **Custom GitHubApp Solution** provides:
- **Centralized configuration management:** External files ensure maintainability and version control.
- **Enhanced developer experience:** Real-time, actionable guidance directly in pull requests.
- **Strict enforcement:** Blocks non-compliant commits with granular controls.
- **Scalability and extensibility:** Easily integrates into complex workflows and adapts to future needs.
- **DevOps alignment:** Supports IaC, GitOps, and iterative improvement.

This solution is ideal for organizations prioritizing compliance, flexibility, and developer-centric workflows.

---

### **Next Steps**
The detailed assessment, including a full comparison of evaluated actions and the rationale for selecting the Custom GitHubApp Solution, is available here:  
[Assessment Documentation](https://docs.google.com/document/d/1GH91uYlI_MH5s4ED-2ZBemf4x8lUlnddshpArQ3BhQw/edit?usp=sharing)

This solution will be implemented in subsequent tasks, ensuring seamless integration into our CI/CD workflow.
