### ISSUE TITLE
Remove "Permissions" and "Relationships Legacy" fields from the field selections sidebar in the Content Type editor

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29736]
### Problem Statement

The "Permissions" and "Relationships Legacy" fields are now deprecated, and will not be migrated to the new content edit screen.

We need to prevent customers from adding these fields to content types which don't already have them, to reduce the work needed to migrate when the new content edit screen is delivered.

![image](https://github.com/user-attachments/assets/8c771df9-97be-4465-b1cc-1771ebf605b1)

### Steps to Reproduce

1. Create a new content type, or edit an existing content type.
    * Result: The deprecated fields still show in the list of field types you can select.

### Acceptance Criteria

1. The `Permissions` field does not show in the list of field types to select.
2. The `Relationships Legacy` field does not show in the list of field types to select.
3. Both fields still behave normally for any content types which already have one or both of them.  This applies to all of the following places at a minimum:
    * The Content Type edit screen.
    * The content edit screen.
    * Content pulls of legacy content types (`$dotcontent.pullRelated`).
    * Push publish.

### dotCMS Version

All current versions

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by dsilvam** [comment]
Passed IQA: 

* Neither field is available on the content type screen 
* Content whose content type already had those fields still display correctly on the old Content Edit Screen
* Push Publishing content with those old fields work and both are displayed on the receiver.
* When editing content types (content types portlet) which had them already they are still displayed

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_7f140fe**, Docker, macOS 14.5, FF v126.0.1

![Screenshot 2024-09-11 at 11 54 18 AM](https://github.com/user-attachments/assets/011152a0-a27f-450b-9887-795ebf568497)
