### ISSUE TITLE
SDK: Improve error message display for failed angular example authentication

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29738]
### Problem Statement
When the angular example fails for authentication, it currently shows a blank screen, which does not provide any useful information to developers on how to resolve the issue.

### Steps to Reproduce
Run the Angular example without info in the `environtment` file.

### Acceptance Criteria

- [ ] When the angular example fails for authentication or no dotcms host selected, a clear error message should be displayed on the screen to guide developers on how to fix the issue.

### External Links
- N/A

### Assumptions & Initiation Needs
- The error message should be concise and informative, providing guidance on resolving authentication issues.
- Development team needs to implement the logic to display the error message when authentication fails.

### Quality Assurance Notes & Workarounds
N/A

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
Tested in `master`


https://github.com/user-attachments/assets/da73cd9e-9f45-45f2-b240-5ae93e86abea

**Comment by bryanboza** [comment]
We need some work here: 

https://github.com/user-attachments/assets/c43c9e61-cbfa-4c15-918d-755224cce220

We need to check: 
- The error is appearing with a kind of blur and in the background 
- The button just refresh the page the first time

**Comment by dcolina** [comment]
## Internal QA: Passed.

The issue couldn't be reproduced anymore. It was tested using the docker image `dotcms/dotcms:nightly_8040597` through the three different supported browser (`Chrome, Firefox, Edge`).

https://github.com/user-attachments/assets/8251e4f7-5c39-4746-a3c5-aead60607811

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_ea7843a**, Docker, macOS 14.5, FF v126.0.1
