### ISSUE TITLE
Workflow Import endpoint: schema & error messages incorrect

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29730]
### Problem Statement

While working on the API Playground, I noticed the Workflow Import endpoint has a couple of small errors that run a bit deeper than just pure Swagger UI annotations. I figured I'd address these separately from the doc PR itself.

Firstly, the schema includes a duplicated object: Both `workflowObject` (the proper one) and `workflowImportObject` (a bogus one)

![image](https://github.com/user-attachments/assets/a2c8ae3f-f1eb-4748-8e67-6c363be0daca)

Furthermore, if the `workflowObject` is not supplied, even if `workflowImportObject` is supplied, its error message indicates the wrong object is absent:

![image](https://github.com/user-attachments/assets/bf2f98b9-158c-495a-9289-d7eb192b818b)

### Steps to Reproduce

- Open API Playground
- Open `POST /v1/workflow/schemes/import` endpoint
- Click "Schema" to observe the former.
  - Alternately, the default body content will include both redundant objects
- Attempt to submit without the `workflowObject` property to see the mistaken error message.

### Acceptance Criteria

The schema and default body should both not contain duplicate/redundant/unnecessary properties, and errors should point toward the correct concerns.

I'll be pushing a fix shortly.

### dotCMS Version

24.08.20

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by fabrizzio-dotCMS** [comment]
The error now shows accurately the missing property 
![Screenshot 2024-09-30 at 10 13 14 AM](https://github.com/user-attachments/assets/fd88d37b-7bfa-4201-8fcc-4e2371c126e5)

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
