### ISSUE TITLE
WYSIWYG code view styles messed up

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29733]
### Problem Statement

The text styles in the WYSIWYG code view are out of whack, where each character offsets the cursor from the insert point a little more, and the text overruns the edge of the frame. Makes it very hard to use for editing tasks.

https://github.com/user-attachments/assets/84b7236c-ab8a-4004-953e-888fd9378c01

### Steps to Reproduce

- Open Demo
- Create content type with a WYSIWYG field
- Create new contentlet
- Switch over to Code mode
- Type a bunch of dummy text
- Note the cursor gradually falling out of alignment with text insert position

### Acceptance Criteria

Cursor should be the exact same point as text insert; scrolling and wrapping should occur within the expected bounds of the feame.

### dotCMS Version

24.08.20

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
QA Note: This also need to be tested in the Elastic Search screen (Dev Tools -> ES Search ). New and legacy edit content.

**Comment by oidacra** [comment]
Pass IQA.

https://github.com/user-attachments/assets/b3a3e06f-93e6-4d54-b0af-46775410349d

**Comment by bryanboza** [comment]
Fixed, tested on the latest main //  Docker // FF 

![image](https://github.com/user-attachments/assets/ec63d6bc-3b16-4d5a-bd54-5007a9d0bb6b)

**Comment by bryanboza** [comment]
New card to handle specific case switching to plan text here: https://github.com/dotCMS/core/issues/30223

QA card here: https://github.com/dotCMS/core/issues/30224
