### ISSUE TITLE
Update to ZGC ZGenerational garbage collection supported in J21

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#29759]
Update to the latest Garbage collector that is now supported in Java 21. 

Test if there are issues when applied that show in the logs on Docker Startup.  Can review all Java Paramters that are reported when a postman job is startup up to ensure these are being picked up.

Cloud engineering will need to assess any positive impact of these settings on memory utilisation and performance over time.

**Comment by fabrizzio-dotCMS** [comment]
There are no issues in logs whatsoever as far as I can tell
