### ISSUE TITLE
UI Does Not Reflect Saved Default Action in Content Types Update Dialog

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#29765]
### Problem Statement

found while testing https://github.com/dotCMS/core/issues/28684 

In the Content Types Update dialog, after selecting a Default Action and clicking the "Update" button, the dialog closes as expected. However, if you reopen the dialog, it appears unchanged, as if the modifications were not saved. Despite this, a deeper investigation reveals that the changes are indeed saved. When checking the API response from the "API" button on the main Content Types edit screen, the JSON representation of the Content-Type reflects the saved changes. Additionally, if you use the CLI to download the Content Type definition, the JSON correctly shows the updates, including the changes to the Default Action. This behavior suggests that the UI is ignoring the presence of the **systemActionMappings** attribute in the server's response, leading to the false impression that the changes were not applied.

### Steps to Reproduce

1. Open the Content Types Edit dialog.
2. Select a Default Action.
3. Click the "Update" button to save changes.
4. Reopen the Content Types Edit dialog.
5. Observe that the dialog appears as it was before the update, without reflecting the saved changes.
6. Check the API response via the "API" button or use the CLI to download the Content Type definition to see that the changes were actually saved in the JSON.

https://github.com/user-attachments/assets/2b59dd45-d1bf-4bf2-923f-02e60acf72ae

### Acceptance Criteria

The Dialog must show accurate saved data

### dotCMS Version

current Trunk. it can also be reproduced in demo 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_5b70657**, Docker, macOS 14.5, FF v126.0.1
