### ISSUE TITLE
Update the REDIS configuration guide doc 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29764]
### Task

As part of the new changes we need to keep the internal documentation updated!!!

Please validate the follow doc and make sure this still working, if not, we need to update the steps 
https://docs.google.com/document/d/1k2jfYcKF5_e0ph-nk2PQ-1TATfmMFAhchFuvCK6spRo/edit

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**QA Approved**

No necessary changes needed to be made to the current document configurations guide. The fix implemented [here](https://github.com/dotCMS/core/issues/29355) Was only intended to fix a cache issue related to the logged session.
