### ISSUE TITLE
UVE: Next.js Example breaks when adding "Event" content

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#29768]
### Problem Statement

The Next.js headless example encounters an error when an Event content is added to a page container.

![image (5)](https://github.com/user-attachments/assets/81b0b998-db27-4948-bcb5-8a404556c33d)

https://github.com/user-attachments/assets/1d6e01bf-b1e1-4cdd-b33f-2c9837a8e7ab

### Steps to Reproduce

1. Add UVE configuration for Next
3. Edit a page adding an existing Event
4. See the error

### Acceptance Criteria

No response

### dotCMS Version

`dotcms/dotcms:trunk_2f3045b`

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
This is a problem in the example, check also Astro and Angular.

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker image: [`dotcms/dotcms:trunk_ e622545`]
- Server: [QA Master](https://dotcms-qa-master.dotcms.site/dotAdmin/)

### Video

https://github.com/user-attachments/assets/20b8cd7c-2b87-40bc-aa35-04986a2fec1d

**Comment by bryanboza** [comment]
Fixed, now this is working as expected! 

![Image](https://github.com/user-attachments/assets/c10217a8-56bf-47ae-b3d8-b334af8b84e5)
