### ISSUE TITLE
Language Issue for selecting Contentlets/images in Block Editor

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#29781]
### Problem Statement

When creating content other than the default language e.g FR so the BlockEditor doesn't allow to selection of required language images/contentlet. It only allows selecting images/contentlets from the default language e.g EN

### Steps to Reproduce

Create a Test content type with BlockEditor
Create contentlet for other language than default e.g FR
Try to add a contentlet. You will only see contentlet/images from the default language like EN.

https://github.com/user-attachments/assets/b6691652-9a1a-4098-9e19-c0f288a80869

It always calls ES search query for languageId 1

```
curl 'https://rbc-gam-uat.dotcms.cloud/api/content/_search' \
  -H 'authority: rbc-gam-uat.dotcms.cloud' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,ur;q=0.8' \
  -H 'content-type: application/json' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  --data-raw $'{"query":"+catchall:* title:\'\'^15 +languageId:1 +baseType:(4 OR 9) +metadata.contenttype:image/* +deleted:false +working:true","sort":"score,modDate desc","limit":20,"offset":0}' \
  --compressed
```
### Acceptance Criteria

BlockEditor should allow to select contentlet/images for contenlet's language

### dotCMS Version

24.04.24_ltsv6 - above

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117809

**Comment by erickgonzalez** [comment]
![Image](https://github.com/user-attachments/assets/52fe812f-e25e-40b0-8efb-6e64d4f6c746)

Working as it should, we now show the contents in the language selected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_250741a**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-09-13 at 12 38 28 PM](https://github.com/user-attachments/assets/a33bef5c-96ad-4564-b373-196a6f060a1e)
