### ISSUE TITLE
Add New Column: Filter

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#29786]
Add a new column to the PP Portlet named **Filter** that shows the filter used for the bundle.

Let's added before the **Status** column.

**Comment by dsolistorres** [comment]
Note for QA:
* The new column 'Filter' is only shown for bundles sent to another endpoint (not bundles received from another endpoint) because the filter descriptor key is only stored for bundles send to another endpoint.

**Comment by erickgonzalez** [comment]
Working as it should, now we have a column that shows the Filter.![Image](https://github.com/user-attachments/assets/262266ad-950f-4909-9d3c-53d08d81b81e)
