### ISSUE TITLE
Category Field: Empty State not showing

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29801]
### Problem Statement

When the are no categories the empty state is not shown. 

### Steps to Reproduce

1. Create a content type with a category field without categories. 
2. go a create a content. 
3. See there is no empty state. 

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/824c6c59-ed1b-4e15-b95e-35c1c9b729ab">

### Acceptance Criteria

should load empty state correctly. 
### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
IQA passed with **trunk_cc63b1d**

If there are no categories, the appropriate empty space is displayed.

![Image](https://github.com/user-attachments/assets/f4b2b391-322e-4ed4-bf12-4bdca050a33c)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e622545**, Docker, macOS 14.5, FF v126.0.1
