### ISSUE TITLE
Valentino: Drop Everything & Learn Aug 28 - Sep 10

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29814]

**Comment by valentinogiardino** [comment]
Take some time to review the Next.js documentation, focusing on nested layouts and the App Router to deepen understanding of parallel routes, route intercepting, and their benefits in implementing modals, login flows, and optimizing performance.

- [Nesting Layouts](https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#nesting-layouts)
- [Parallel Routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes)
- [Intercepting Routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes)
