### ISSUE TITLE
Actions in listing not working properly

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29826]
### Problem Statement

The action items in the tables that use `dot-action-menu-button` are not working properly. 

### Steps to Reproduce

1. Go to the content type listing. 
2. Use any of the action of each row, for example `Add to Menu`
3. See the error. 

![Image](https://github.com/user-attachments/assets/35b29a09-6fb6-4e99-994e-1115b7cd0214)

### Acceptance Criteria

Menu layover should close and action should be executed correctly. 

### dotCMS Version

lastest

### Proposed Objective

User Experience

**Comment by victoralfaro-dotcms** [comment]
This is working, no menu layover
https://github.com/user-attachments/assets/be9bc943-6317-4cb1-9b6a-7f6008e1ad74

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e622545**, Docker, macOS 14.5, FF v126.0.1
