### ISSUE TITLE
Swaggify Workflow API, part 2

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#29828]
### Parent Issue

https://github.com/dotCMS/core/issues/28600

### Task

The long-awaited second round of Workflow API doc. Unfortunately, there are still five endpoints that need a little work:

- The three `firemultipart` ones still need their multipart form bodies documented, and I'm still trying to understand how that goes:
  - PUT /v1/workflow/actions/{actionId}/firemultipart 
  - PUT /v1/workflow/actions/default/firemultipart/{systemAction}
  - PUT /v1/workflow/actions/firemultipart
- Two others with some kind of API Playground related bug: 
  - POST /v1/workflow/actions/default/fire/{systemAction}
  - PATCH /v1/workflow/actions/default/fire/{systemAction}

On the latter two, I'm able to make successful calls via curl, but when I paste the same data body into the Playground, I get a 406 response. I'm wondering if maybe it has to do with this bit of code present on both of them:

```
//@Produces({MediaType.APPLICATION_JSON, "application/javascript"})
@Produces("application/octet-stream")
```

Either way, I have a lot more material ready to go, and I'll be attaching the PR to illustrate this shortly.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

**Comment by valentinogiardino** [comment]
### IQA FAILED

Tested on `trunk_477606b`

**Great job on this!** 👏  

I've identified a few minor inconsistencies and formatting issues, which are outlined in detail in this [document](https://docs.google.com/document/d/1Q4iSSVtbPVMGjGrKP8MyJ8g2X1Dl0rWZAopKK7Lcq78/edit?usp=sharing)

**Comment by valentinogiardino** [comment]
### IQA PASSED
Tested on `trunk_0028f3c`
All inconsistencies identified in the previous IQA have been resolved.

**Comment by bryanboza** [comment]
Fixed, improvements looks better now
