### ISSUE TITLE
UVE: Dragging a contentlet out of the browser and then dropping it into a container breaks the UVE

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#29837]
### Parent Issue
N/A

### Problem Statement
Dragging a `contentlet` out of the browser and then dropping it back into a container breaks the UVE.

### Steps to Reproduce
1. Select a `contentlet`.
2. Drag it out of the browser window.
3. Return to the browser while still dragging the `contentlet`.
4. Drop the `contentlet` into a container.
5. Observe the error.

### Video

https://github.com/user-attachments/assets/85c95b57-c7bc-464a-a6e3-902073bc99cc

### Expected Behavior
Users should be able to drag a `contentlet` out of the browser and then drop it into a container without breaking the UVE.

### Actual Behavior
Dragging a `contentlet` out of the browser and then dropping it into a container breaks the UVE.

### Acceptance Criteria
If the user left the window/browser with a `contentlet`, we force them to re-do the drag by ignoring the current item.
Defined/Proposed by @fmontes 

- ~~Users can drag a `contentlet` out of the browser and drop it into a container without causing any errors.~~ 
- ~~The UVE remains functional after performing the drag-and-drop action~~ 

### dotCMS Version
`master`/`trunk`

### Proposed Objective
User Experience

### Proposed Priority
Priority 2 - Important

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test case # 9 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by valentinogiardino** [comment]
## [Passed IQA]
- Tested on qa master 
- docker image `dotcms:trunk_8912b16` chrome, firefox, edge

https://github.com/user-attachments/assets/80301afa-7251-434a-9143-dec413f57a08

https://github.com/user-attachments/assets/9565d9ed-88ba-449b-8831-4041d5ad12df

**Comment by bryanboza** [comment]
Fixed, now i'm unable to reproduce, we are preventing this and once you drag outside of the browser it is not working anymore. 

Tested on trunk // Docker // FF
