### ISSUE TITLE
move dev image to java 21

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29830]
### User Story

Now that dotcms is running with java 21, we need to move the dev image to java 21.

Short term, we can leverage the microsoft java-21 docker image. 

For a future development, we should use sdkman and key off the .sdkman file (the dev image does not do a dotcms build and does not have the git repo locally when building).

### Acceptance Criteria

make sure the nightly dev image is running java 21. 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
it is running in java 21

![Image](https://github.com/user-attachments/assets/bc4904a3-3f17-44f0-a3aa-4d2e9d8fa250)

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker
