### ISSUE TITLE
Create E2E section in reusable CI test workflow only for merge (queue) group merges

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29846]
### Parent Issue
https://github.com/dotCMS/core/issues/29350

### User Story
As a dev-ops/CICD engineer, I want to include the necessary GitHub workflow details in the CICD merge-queue file so that the functionality is reusable across existing GitHub workflows and follows best practices and guidelines introduced by the latest changes in CICD.

### Acceptance Criteria
- The GitHub workflow details are included in the CICD merge-queue file.
- The functionality is reusable across existing GitHub workflows.
- Implementation follows best practices and guidelines introduced by recent CICD changes.
- The CICD workflow runs successfully across relevant branches without conflicts.

### dotCMS Version
master

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- The latest CICD guidelines and best practices must be reviewed and adhered to.
- The GitHub workflow should be modular and reusable.

### Quality Assurance Notes & Workarounds
- Verify that the new GitHub workflow details do not conflict with existing workflows.
- Ensure that the workflow follows all established CICD guidelines.

### Sub-Tasks & Estimates
1. Review current CICD guidelines and best practices - 2 hours
2. Implement necessary GitHub workflow details in CICD merge queue file - 4 hours
3. Test reusability across existing workflows - 3 hours
4. Verify CICD functionality and adherence to guidelines - 3 hours

**Comment by victoralfaro-dotcms** [comment]
PRs:
- https://github.com/dotCMS/core/pull/30071/files

**Comment by dsilvam** [comment]
IQA'ed in this one https://github.com/dotCMS/core/issues/29847#issuecomment-2380025985
