### ISSUE TITLE
Create dotCMS child project to host E2E tests

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29845]
### Parent Issue
https://github.com/dotCMS/core/issues/29350

### User Story
As a dev-ops/CICD engineer, I want to create a new Maven module project to be included in the main dotCMS root Maven project file. This file should reference any new dependencies from the application BOM file, so changes in the corresponding POM will be required. Additionally, there should be some sort of output indicating a forked process that needs to be executed by a Maven plugin (probably `Failsafe`) at the same phase of integration and Postman tests.

### Acceptance Criteria
- A new Maven module project is created and integrated into the dotCMS root Maven project file.
- Dependencies are correctly referenced from the application BOM file.
- The corresponding POM file is updated with new dependencies.
- Maven plugin (e.g., `Failsafe`) is configured to execute a forked process during the integration and Postman test phases.
- Output is generated by the forked process to confirm successful execution.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- Maven plugin configuration is required to manage a forked process.
- Dependencies must be updated in the BOM file as part of the new Maven module project.

### Quality Assurance Notes & Workarounds
- Ensure that the Maven plugin runs correctly in the integration and Postman test phases.
- Verify that the forked process generates the expected output without errors.

### Sub-Tasks & Estimates
1. Create new Maven module project and integrate with root POM - 4 hours
2. Update BOM file with new dependencies - 2 hours
3. Configure Maven plugin (`Failsafe`) for forked process - 3 hours
4. Test integration and output generation - 5 hours

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
Since this is merely for developers usage to test this initiative please run:
```
# Java E2E tests
./mvnw -pl :dotcms-e2e-java verify -De2e.test.skip=false
```
and
```
# Node.js E2E tests
./mvnw -pl :dotcms-e2e-node verify -De2e.test.skip=false
```

- Make sure that maven did exit without any errors
- Make sure that 4 Docker container were started: db, ES, WireMock and dotCMS

To kill any remaining containers run:
```
./mvnw -pl :dotcms-e2e -Pdocker-stop -De2e.test.skip=false
```

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
E2E testing for both Java and Node.js work perfectly. This is what I can see in my local:

- The four Docker containers -- DB, ES, WireMock and dotCMS -- going up when tests are running, and going down when they finish.
- The Chromium window testing exactly what the current tests dictate.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ea7843a**, Docker, macOS 14.5, FF v126.0.1
