### ISSUE TITLE
Use existent or create new Playwrigth GH Action to run E2E in parallel

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29847]
### Parent Issue
https://github.com/dotCMS/core/issues/29350

### User Story
As a dev-ops/CICD engineer, I want to, whether it exists, use it; otherwise, create a new Playwright GitHub Action (or workflow call) to invoke E2E tests at the same phase as integration and Postman tests. The job will need to execute in parallel with the other types of tests.

### Acceptance Criteria
- A Playwright GitHub Action (or workflow call) is created or reused to invoke E2E tests.
- E2E tests run in the same phase as integration and Postman tests.
- The Playwright tests are executed in parallel to the other test types.
- The solution works across all branches and environments without conflict.

### dotCMS Version
master

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- If an existing Playwright GitHub Action or workflow exists, it will be reused; if not, a new one will be created.
- The new action/workflow must ensure parallel execution with integration and Postman tests.

### Quality Assurance Notes & Workarounds
- Confirm the E2E tests execute in parallel without impacting the other test workflows.
- Verify that the Playwright tests run successfully on all relevant branches.

### Sub-Tasks & Estimates
1. Investigate existing Playwright GitHub Action or workflow - 2 hours
2. Implement or create new Playwright GitHub Action if needed - 4 hours
3. Configure E2E tests to run in parallel with integration and Postman tests - 3 hours
4. Test and validate the new workflow across environments - 4 hours

**Comment by dsilvam** [comment]
Passed IQA:
E2E running at PR level - https://github.com/dotCMS/core/actions/runs/11076456030/job/30780120771?pr=30181#step:3:2952
For the time being only the LoginTests are running. Need to decide what to include next.
