### ISSUE TITLE
Transform test results to unit test format and include them in test results artifact

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#29848]
### Parent Issue
https://github.com/dotCMS/core/issues/29350

### User Story
As a dev-ops/CICD engineer, I want to ensure the E2E test results are output in the correct unit test results format. Once formatted, bundle all the test results and upload them as a GitHub artifact, following the same process as other test types. This artifact must then be downloaded by subsequent workflows (e.g., `Report` and/or `Finalize` jobs in `cicd_#_...` workflow files) to interpret the results and resolve the overall test results.

### Acceptance Criteria
- E2E test results are output in the correct unit test results format.
- All test results are bundled and uploaded as a GitHub artifact.
- The artifact is successfully downloaded by subsequent workflows (e.g., `Report` and `Finalize`).
- The test results are correctly interpreted and used to resolve the overall test results.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- The correct format for unit test results needs to be confirmed.
- The artifact upload process should follow the same flow as other test types (integration, Postman).

### Quality Assurance Notes & Workarounds
- Verify that the test results are uploaded as an artifact without errors.
- Ensure that subsequent workflows can download and interpret the results correctly.

### Sub-Tasks & Estimates
1. Ensure E2E test results are in the correct unit test format - 3 hours
2. Bundle all test results and configure artifact upload - 4 hours
3. Modify `Report` and/or `Finalize` jobs to download and process the artifact - 3 hours
4. Test and validate the workflow across environments - 4 hours

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
- Verify fro now on that E2E tests are included in de CICD pipeline.
- If you would like to go further you can cut a branch from master and change the change the following test files in order to cause a failure in the tests below and push the branch and create a PR from it to trigger the CICD and finally verify the tests failures details are displayed in the CICD pipeline `Report` phase. Test files:
  - https://github.com/dotCMS/core/blob/main/e2e/dotcms-e2e-java/src/test/java/com/dotcms/e2e/test/LoginTests.java
  - https://github.com/dotCMS/core/blob/main/e2e/dotcms-e2e-node/frontend/tests/welcome.spec.ts

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- **IMPORTANT: No Docker image is used as this is a CI/CD change, not a change in Java code.**

The test report is now including errors from E2E tests. Here's an example of a report I generated based on the instructions provided by @victoralfaro-dotcms : https://github.com/dotCMS/core/pull/30227/checks?check_run_id=30998887410

**Comment by josemejias11** [comment]
**Approved**:
