### ISSUE TITLE
Button in Binary Field is inconsistent

### ISSUE THREAD

**Issue by melissarojas-dotcms** [dotCMS/core#29858]
### Define the Problem

1.	The button labeled “Generate with dotAI” is inconsistent with the rest of the buttons in the Binary Field.
2.	The disabled state of the button has an issue where the icon is shown in blue. Since it is disabled, the icon should be gray. Please check the Design System.

### Who's Facing the Problem?

-

### Screenshot or Video

![Image](https://github.com/user-attachments/assets/afd503d9-0abb-46dd-a5a5-9dba0eed05c5)

![Image](https://github.com/user-attachments/assets/a97b30e3-050c-43e1-99dc-f6ce65d65331)

### Relevant Links and Resources

[Button Figma file](https://www.figma.com/design/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?node-id=810-11507&t=zfUK6z0aRwy1X9db-1)

[Binary Field Link](https://www.figma.com/design/YMTdSO5gKf18rc1pCCv1jN/Edit-Contentlet?node-id=3795-67531&t=6G8uTYEzhyNm6iHo-1)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_477606b**, Docker, macOS 14.5, FF v126.0.1
