### ISSUE TITLE
UVE: Code button not displaying in Headless

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#29854]
### Problem Statement

The `code` icon/button is not displayed in headless mode, preventing users from editing `.vtl` code directly.

https://github.com/user-attachments/assets/c4cdb646-1c24-4940-87b0-d59a62c305bc

### Prerequisites
- Have a page asset with content in it.

1. Edit any page.
2. Hover over a contentlet with `.vtl` code.
3. See that the code button is not displayed

### Acceptance Criteria

1. A `code` button should be displayed when hovering over a contentlet with `.vtl` code.
2. A dialog should open to edit the content for the `.vtl` code.
3. Users should be able to make any changes and save them.
4. After closing the dialog, the `.vtl` code changes should be reflected on the page.

### dotCMS Version

Tested on qa master server. Docker image`[dotcms/dotcms:trunk_fbad538]`

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test case # 5 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by fmontes** [comment]
Code buttons not shows in headless because it links to vtl file and there is not such thing in headless.
