### ISSUE TITLE
Chore: Image Field Localization Issue for Non-Default Language Contentlets

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#29851]
### Parent Issue

No parent issue identified.

### Problem Statement

When creating content in a non-default language that includes an image field, the associated image is not created for the specified language. 
For example, with the "activity" content type in the `20240807` starter, if a user creates Spanish content, the selected image does not appear in the Spanish version. This leads to unexpected behaviors when creating or editing pages that use this contentlet. The issue occurs consistently across Chrome, Firefox, and Edge.

### Steps to Reproduce

1. Open any content with an image field, such as "banner" or "activity."
2. Create a version of this content in a secondary language.
3. Confirm the contentlet is created.
4. Check if the associated image is created in the secondary language.

The issue also occurs when creating new content from scratch in a secondary language.

### Acceptance Criteria

1. When a contentlet is created in a specific language, its associated image should also be available in that language.

### dotCMS Version

Tested with Docker image `dotcms/dotcms:trunk_fbad538`.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- Attached video showing the issue with image field management when creating contentlets for not default languages.

https://github.com/user-attachments/assets/2fe914d0-79a2-4a83-a809-2ca0a33978e0

### Quality Assurance Notes & Workarounds

Manually create a image for version for the specific language.

### Sub-Tasks & Estimates

- [ ] Identify and implement a fix to ensure images fields are managed correctly across all languages and content types.
- [ ] Test the fix across all supported browsers: Chrome, Firefox, and Edge.

**Comment by fmontes** [comment]
Probably something in our example image component, please check in Angular and Astro as well.

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test case # 30 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by valentinogiardino** [comment]
**Note to QA**:  
We have fixed the fallback mechanism to default language if an image or file associated with a contentlet does not exist in the contentlet's current language.  

To test this:
1. Ensure that the `DEFAULT_FILE_TO_DEFAULT_LANGUAGE` property is set to `true` in the environment configuration.
2. Create a Spanish version of a contentlet with an Image Field. Select an image that doesn’t have a Spanish version.
3. Add the contentlet to a Spanish page.
4. Verify that the contentlet-associated image displays properly.

**Comment by zJaaal** [comment]
## IQA Passed

Now the image can be accessed even if we do not have a version for the specified language 

DotCMS Docker Image: `[dotcms/dotcms:trunk_9269649]`

### Screenshot

https://github.com/user-attachments/assets/26942a57-019c-4bc9-a232-fda6f834813f

**Comment by zJaaal** [comment]
# Note to QA 

In the headless version, images may fail even if the language is the same our way to manage images in the examples it's too naive and it's not bulletproof. We are aware of this problem and we will take care of it in this ticket https://github.com/dotCMS/core/issues/30717

**Comment by bryanboza** [comment]
we can pass this one for now, but will need be retested after the fix the #30717
