### ISSUE TITLE
Wrong font size with "Generate With dotAI" in Binary Field

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29859]
### Problem Statement

The button with the text "Generate With dotAI" looks like this with a different font size.

![Screenshot 2024-09-04 at 9 26 20 AM](https://github.com/user-attachments/assets/8470e1ee-2274-44ed-bb99-2261dbb73f86)

### Steps to Reproduce

1. Create a content scheme 
2. Add a binary field to the schema
3. Create content based on the schema

### Acceptance Criteria

Component without different font size.

### dotCMS Version

trunk_e622545

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_8912b16**, Docker, macOS 14.5, FF v126.0.1
