### ISSUE TITLE
 Replace Old Style with New Component for File Asset Upload

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29857]
### Problem Statement

When users attempt to upload a new file asset, the old style interface is displayed instead of the new component. This issue leads to the loss of recently released functionalities, such as the ability to create new content with AI and the option to upload files from a URL. These missing features are critical to the enhanced user experience and functionality of the platform.

![image](https://github.com/user-attachments/assets/710a6a26-4c85-485e-9b5f-d9cddf667dfc)

![image](https://github.com/user-attachments/assets/34353b9b-43b7-4d6e-867c-25a809f9a559)

### Steps to Reproduce

- Log into the content management system with the necessary credentials.
- Navigate to the section where you can upload a new file asset.
- Attempt to upload a file and observe that the old style interface is shown instead of the new component.
- Notice that functionalities like "Create New Content with AI" and "Upload from URL" are missing.

### Acceptance Criteria

- Display New Component: Ensure that the new component is displayed when users upload a new file asset, replacing the old style interface.
- Restore Missing Functionalities: Ensure that all recently released functionalities, such as "Create New Content with AI" and "Upload from URL," are available in the new component.

### dotCMS Version

Tested on trunk // Docker // FF 

### Proposed Objective

Quality Assurance

**Comment by dsilvam** [comment]
This requires changing the defaults for the FF as well

**Comment by nollymar** [comment]
An utility method was created to verify if a feature flag is on/off. However, an additional change should be implemented [here](https://github.com/dotCMS/core/issues/29900)

**Comment by fabrizzio-dotCMS** [comment]
Passed IQA: the new component is now displayed

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d0fcfe0**, Docker, macOS 14.5, FF v126.0.1
