### ISSUE TITLE
The state of the "file select tree" should be remembered between consecutive openings

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#2985]
Structures that have an image or file field use an overlay with a tree to browse through the folder tree of dotCMS. Every time you open the overlay the tree is closed by default forcing you to navigate to the folder that you need to be in. The exception is when you open the overlay for the same field twice. 

We often need to edit many pieces of content one by one. The images for the different pieces of content are often in the same location. It would be very (read: extremely) nice to save the state of the tree in between openings. It would increase the usability.

What I think the logic should be is this:
1) if there is already a file selected open the tree in the location of that file. 
2) if there is no file selected open the tree in the most recent location the tree was opened in.

**Comment by koenpeters** [comment]
This one should not be closed as I think it's still very relevant.
