### ISSUE TITLE
Add loading state for initial category fetch in dialog

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29850]
### Problem Statement

When opening the category dialog, there's a brief moment where the component incorrectly displays a "No categories" message before the parent categories are loaded. This is particularly noticeable on slower connections (e.g., 3G). The component lacks a proper loading state when in the INIT state, which should display a loading indicator instead.

### Steps to Reproduce

1. Slow down the network connection (e.g., throttle to 3G in browser dev tools).
2. Open the category selection dialog.
3. Observe the initial state of the dialog.
4. Notice that a "No categories" message briefly appears.
5. After a moment, the parent categories are displayed.

### Acceptance Criteria

1. When the category dialog is opened and in the INIT state, a loading indicator is displayed.
2. The "No categories" message is not shown during the initial load.
3. The loading indicator persists until the initial category data is fetched.
4. Once data is loaded, the loading indicator is replaced with the list of parent categories.
5. If there are truly no categories after loading, only then should the "No categories" message be displayed.
6. The loading state is visually consistent with other loading states in the application.

### dotCMS Version

master

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/user-attachments/assets/224e0c0f-ac6b-47f0-b1c5-6e64c3af6f3f

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ab4b1df**, Docker, macOS 14.5, FF v126.0.1
