### ISSUE TITLE
The Reference tab don't show pages where contentlets are added in the block editor

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#29860]
### User Story

- When adding a contentlet (like an Activity) to a block editor field on a page (like a Blog), the references tab for the contentlet is not showing that it is being used on that page.
- This is reported to happen only on pages containing block editor fields (which contain a contentlet).

### Acceptance Criteria

- The reference tab should show where the contentlets are used, even for pages where block editor contains these contentlets.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27442

**Comment by wezell** [comment]
The references tab only shows usages on a page, not across various other content objects.

**Comment by wezell** [comment]
This should be added to Airfocus as a BlockEditor improvements epic
