### ISSUE TITLE
Create Endpoint to allow running a query directly into CA data

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#29864]
### Parent Issue

- https://github.com/dotCMS/core/issues/30141
- https://github.com/dotCMS/core/issues/29477

### User Story

We need a Endpoint to run queries directly into the CA Data.

**Possible URL** 

 GET: /api/analitics/data?query='...'

Also We might consider using a POST method to include the query in the request body instead of as a query parameter. Including a long query as a parameter might not be ideal.

**Input** 

I think that the input should be a CubeJS query. If you're unfamiliar with CubeJS queries, you can learn more [here](https://cube.dev/docs/product/apis-integrations/queries). We might consider limiting the available features or slightly modifying the syntax. For instance, we could use "aggregation" instead of "measures" or "fields" instead of "dimensions." However, we should not deviate significantly from the standard CubeJS syntax, as it is both simple and flexible enough for direct use. We can also control what users can do by restricting actions to those defined in the CubeJS schema.

Also we we want to go away from CubeJS in the future we can translate the CubeJS Query into a SQL Query using Java code

**Output** 

We already have a [CubeJSResultSet](https://github.com/dotCMS/core/blob/c16d2c8d9ac68a015868bf972ffd5c3041f217a7/dotCMS/src/main/java/com/dotcms/cube/CubeJSResultSet.java#L10) class that represents the result of a CubeJS query. This class functions as an iterator of maps, where each map entity corresponds to a record returned by the CubeJS query, and each key within the map entity is a field returned by the query. We can simply return a responseView containing this object.

### Acceptance Criteria

- Have the Endpoint Up and running, we can use the Queries [here](https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/edit#bookmark=id.1crzh369qge4) to test
- Ensure that passing the query through the Endpoint does not create a security issue. Although CubeJS likely manages this, we need to confirm it.
- Just authenticated user can use this Endpoint.
- Don't forget swagger

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

#### Steps to Reproduce
1. Follow this doc on how to set up the Analytics Docker instance: https://docs.google.com/document/d/13KFFCX3S7sQWkNOwoZgcE_aPCbvyFLFKBILrm5PZvWQ/edit . Then, set the following env var in your `docker-compose.yml` file: `DOT_FEATURE_FLAG_CONTENT_ANALYTICS: 'true'`
2. Start up dotCMS with the Full Starter and an Enterprise License.
3. Based on the doc mentioned in the first step, set up the `Analytics Integration` App. Make sure that the token is generated correctly and no errors are present.
4. Open up a window in another browser, and start clicking around the Demo Site. This way, Clickhouse will gather all the pages you're accessing so that you can query them via CubeJS.
5. In Postman, create a POST request with the following information -- the endpoint requires authentication:
```
POST {{serverURL}}/api/v1/analytics/content/_query
```
JSON Body:
```json
{
    "query": {
        "measures": [
            "request.count"
        ],
        "orders": "request.count DESC",
        "dimensions": [
            "request.url",
            "request.pageId",
            "request.pageTitle"
        ],
        "filters": "request.whatAmI = ['PAGE']",
        "limit": 100,
        "offset": 1
    }
}

```
6. You should get results similar to the following:
```json
{
    "entity": {
        "results": [
            {
                    "request.count": "4",
                    "request.pageId": "9c5f42da-31b1-4935-9df6-153f5de1bdf2",
                    "request.pageTitle": "Blogs",
                    "request.url": "/blog/"
            },
            {
                    "request.count": "4",
                    "request.pageId": "44a076ad-affa-49d4-97b3-6caa3824e7e8",
                    "request.pageTitle": "Destinations",
                    "request.url": "/destinations/"
            },
            ...
            ...
            ...
        ]
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

**Comment by freddyDOTCMS** [comment]
Blocked by issue #29862

**Comment by jcastro-dotcms** [comment]
### NOTE TO DEVS/QA
This ticket has this temporary code change, which disables the flakey CLI Integration Test:

- https://github.com/dotCMS/core/pull/30044/files#diff-b8a9947f91dca6c78ec1d9ace26d5b02d821ac887439c40bd4cedb920d6a6ca3R204

It was just meant to keep the PR from this ticket from failing and being able to merge the fix. It must be re-enabled in the near future.

**Comment by freddyDOTCMS** [comment]
Needs works: right now our reponse is


```json
{
    "entity": {
        "results": [
            {
                "all": {
                    "request.count": "4",
                    "request.pageId": "9c5f42da-31b1-4935-9df6-153f5de1bdf2",
                    "request.pageTitle": "Blogs",
                    "request.url": "/blog/"
                }
            },
            {
                "all": {
                    "request.count": "4",
                    "request.pageId": "44a076ad-affa-49d4-97b3-6caa3824e7e8",
                    "request.pageTitle": "Destinations",
                    "request.url": "/destinations/"
                }
            },
            ...
            ...
            ...
        ]
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

but we need to remove the all word there and get something like


```json
{
    "entity": {
        "results": [
            {
                    "request.count": "4",
                    "request.pageId": "9c5f42da-31b1-4935-9df6-153f5de1bdf2",
                    "request.pageTitle": "Blogs",
                    "request.url": "/blog/"
            },
            {
                    "request.count": "4",
                    "request.pageId": "44a076ad-affa-49d4-97b3-6caa3824e7e8",
                    "request.pageTitle": "Destinations",
                    "request.url": "/destinations/"
            },
            ...
            ...
            ...
        ]
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

**Comment by jdotcms** [comment]
the output has been solved by this issue: 
https://github.com/dotCMS/core/issues/30148

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker image: `trunk_98f280e`

The REST Endpoint is now returning the response as expected. So, instead of the old JSON structure:
```json
{
    "entity": {
        "results": [
            {
                "all": {
                    "request.count": "4",
                    "request.pageId": "9c5f42da-31b1-4935-9df6-153f5de1bdf2",
                    ...
                    ...
```
We're now getting the new one -- without the `"all"` attribute:
```json
{
    "entity": {
        "results": [
            {
                    "request.count": "4",
                    "request.pageId": "9c5f42da-31b1-4935-9df6-153f5de1bdf2",
                    ...
                    ...
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a12617a**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-10-04 at 2 59 34 PM](https://github.com/user-attachments/assets/261d5c6c-23cd-4f64-a996-81f0a0165e18)
