### ISSUE TITLE
Create Util Method to run a query in the CubeJS Server

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#29865]
### Parent Issue

 - #29477

### User Story

We need to create a method similar to this [one](https://github.com/dotCMS/core/blob/c84abaef84bf98f6e9603900e565e28c53a041f2/dotCMS/src/main/java/com/dotcms/cube/CubeJSClient.java#L79) in this same class, but it should take a JSON string directly as a parameter. I'm not sure if we should call this method directly from the endpoint or if we should create an API-level method for it instead.

### Acceptance Criteria

Have the Util class needed to use in this issue:

- #29864

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
Blocked by issue https://github.com/dotCMS/core/issues/29862

**Comment by freddyDOTCMS** [comment]
Pass IQA: Work as expected even when we have some point to improve in the Query syntax the ViewTool is working well

Improvement we need in the query syntax:

https://github.com/dotCMS/core/issues/30190
https://github.com/dotCMS/core/issues/30191

**Comment by freddyDOTCMS** [comment]
QA Note: this is test with #29866 and #29864

**Comment by freddyDOTCMS** [comment]
QA Note: this is test with #29866 and #29864

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_358e597**, Docker, macOS 14.5, FF v126.0.1
