### ISSUE TITLE
Create REQUEST DataModel in CubeJS Schema 

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#29862]
### Parent Issue

- #29481
- #29477

### User Story

Currently, we have a DataModel that is entirely linked to the Experiment Goal, but for our initial CA version, we will not be supporting the Goal. Therefore, we can leave the existing DataModel as is and create a new one. In this new DataModel, we can group data by request using the new request_id attribute that we need to create and it going to be crated in another issue.

this new DataModel can have a syntax like this one [here](https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/edit#bookmark=id.5su49b8sk1g)

### Acceptance Criteria

We need to be allow to query using this new DataModel using the new attributes describe in this [document](https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/view) .

You can test using the query describe [here](https://docs.google.com/document/d/1g5ta7y7yidlgxh3H88F_TNXnNWpjb-Yp6SfebpHKtCU/edit#bookmark=id.1crzh369qge4), but don't limit for just these you can use and document other ones.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
You need to run this script to make de ClickHouse Database enabled to this changes


ALTER TABLE events ADD COLUMN object_id String;
ALTER TABLE events ADD COLUMN object_title String;
ALTER TABLE events ADD COLUMN object_content_type_id String;
ALTER TABLE events ADD COLUMN object_content_type_name String;
ALTER TABLE events ADD COLUMN object_content_type_var_name String;
ALTER TABLE events ADD COLUMN object_response String;
ALTER TABLE events ADD COLUMN object_forward_to String;
ALTER TABLE events ADD COLUMN object_detail_page_url String;
ALTER TABLE events ADD COLUMN object_url String;
ALTER TABLE events ADD COLUMN comefromvanityurl bool;
ALTER TABLE events ADD COLUMN request_id String;
ALTER TABLE events ADD COLUMN host String;
ALTER TABLE events ADD COLUMN sessionid String;
ALTER TABLE events ADD COLUMN sessionnew bool;

This Script is going to be run automatically after this issue: #29878

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/30039

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: We just have problems retrieving the detail page data, but we already work it on another issue #30069 30179

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0028f3c**, Docker, macOS 14.5, FF v126.0.1
