### ISSUE TITLE
Create a ViewTool to retrieve the CA data

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#29866]
### Parent Issue

#29477

### User Story

We need to create a ViewTool to retrieve CA data. This ViewTool will allow us to run a query directly on the CA data. To do this, we'll create a ViewTool that utilizes the utility method created here #29865

### Acceptance Criteria

New ViewToll be ready to use

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
Pass IQA: Work as expected even when we have some point to improve in the Query syntax the ViewTool is working well

Improvement we need in the query syntax:

#30190
#30191

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0028f3c**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-10-07 at 2 42 06 PM](https://github.com/user-attachments/assets/3c2f7e6b-b984-4b8f-9528-6a24b5cf9cdf)
