### ISSUE TITLE
In UVE, when browsing for content in the content pallet, we show results for all hosts. 

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#29870]
### Problem Statement

In UVE, when browsing for content in the content pallet, we show results for all hosts. We should only show content for the host you are on. If the user wants to add content from another host, they can use the Add button.

We should consider adding filters to the search box in the side panel.

### Steps to Reproduce

1. Have content of the same type on multiple hosts
2. From Edit Mode browse content using the content pallet
3. You will see we are listing content from all hosts

See Video:
https://www.loom.com/share/bbc453261d544341857a87bb0b78c850?sid=dc4132b1-939c-494b-99ce-2b898b2b6e55

### Acceptance Criteria

Only show content for that host.

### dotCMS Version

current

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
Closing as works as designed after discussion.
