### ISSUE TITLE
File field: "Import from URL" functionality

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29874]
## Parent Issue
#29691 

## Task
Implement the "Import from URL" feature for **File Field**, which opens a popup for users to enter a URL and import a file from that location.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. An "Import from URL" option is available in the File field
2. Clicking the option opens a popup with a URL input field
3. The system attempts to download and import the file from the provided URL
4. Error handling if the URL is invalid or the file cannot be imported
5. The popup remains open and displays an error message if the import fails
6. Successfully imported files are treated as if they were uploaded directly

## Assumptions & Initiation Needs
- Backend API for importing files from URLs is available
- Security measures for URL validation and file scanning are in place

**Comment by nicobytes** [comment]
QA Notes:

1. Create a new content type with a file field
![Screenshot 2024-10-07 at 5 09 41 PM](https://github.com/user-attachments/assets/d8b7cec4-5d5e-4067-834e-d402500bab3a)
2. Create a content based on the previously created content type
3. Click the "Import from URL" button
![Screenshot 2024-10-07 at 5 10 59 PM](https://github.com/user-attachments/assets/15a9b93c-2a8d-4658-84a9-a80162e00efb)
3. A popup/dialog should show
![Screenshot 2024-10-07 at 5 13 06 PM](https://github.com/user-attachments/assets/e4044456-fe21-4036-8842-545bb3091032)


### Case 1: Images
1. With a Image URL for example: https://nicobytes.com/og_image.jpg
2. Put the url in the input
![Screenshot 2024-10-07 at 4 57 27 PM](https://github.com/user-attachments/assets/33da272b-2e9e-4a09-8cd2-1a5722f18fc2)
3. Click on the "Import" button.
4. The dialog should close and show the preview.
![Screenshot 2024-10-07 at 4 57 36 PM](https://github.com/user-attachments/assets/b8c20d54-5365-4fe2-b533-b5339ddefd3b)

**Comment by dsilvam** [comment]
Failed IQA: Small case but better to fix: 

https://github.com/user-attachments/assets/7cb2f948-37a0-4488-83f3-0c75dbf5c4a6


We should only import if a valid file is found.  If the URL doesn't return a valid image, or if someone drops an invalid file type on the field, we should display a message saying the file/URL isn't valid, and not update the value of the field.

**Comment by dsilvam** [comment]
Passed IQA: The behavior mentioned above will be captured in a different card since it is old behavior also observable in the binary field.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_298ce7a**, Docker, macOS 14.5, FF v126.0.1
