### ISSUE TITLE
File field: "Create New File" functionality

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29875]
## Parent Issue
#29691 

## Task
Implement the "Create New File" feature for **File Field,** which opens the content edit window for a new file while maintaining the state of the original content item.

![Screenshot 2024-10-16 at 12 52 02 PM](https://github.com/user-attachments/assets/812d31d7-af63-4dfc-ad66-dc52927dcece)

![Screenshot 2024-10-16 at 12 51 31 PM](https://github.com/user-attachments/assets/b1a07e3d-4214-4fbc-ad7b-3116db1c2a1c)

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. A "Create New File" option is available in the File field
2. Clicking the option opens the content edit window for a new file
3. The default content type for the new file is dotAsset
4. The state of the original content item is maintained
5. After saving the new file, the user is returned to the original content item
6. The newly created file is properly linked to the File field

## Assumptions & Initiation Needs
- API for creating new content items (files) is available
- Design specifications for the content edit window are provided

**Comment by nicobytes** [comment]
QA Notes:

Create files from scratch using the Monaco editor for file fields.

https://github.com/user-attachments/assets/123eb3f8-8689-4210-ae03-d31ae18688b1

**Comment by dsilvam** [comment]
Passed Internal QA: Created different type of files and working as expected. 

Formats tested: 
* HTML
* Markdown
* JavaScript
* Velocity

Functionality tested:
* View the different links 
* Download the file 
* dotAssets created for each 
* Removing the files from the content 

![Image](https://github.com/user-attachments/assets/03636366-f16d-4132-8cdd-67e7317e8ecd)
![Image](https://github.com/user-attachments/assets/48ce3aa9-49b3-455a-8bd7-0d2c5d34f2b3)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fe2a36c**, Docker, macOS 14.5, FF v126.0.1
