### ISSUE TITLE
File field: "Select Existing File" functionality

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29873]
## Parent Issue
#29691 

## Task
Implement the "Select Existing File" feature, which opens a popup for users to select a file already existing in dotCMS.

![Screenshot 2024-10-16 at 12 45 58 PM](https://github.com/user-attachments/assets/b6aa2726-2a9c-4353-aa44-121c97571249)

![Screenshot 2024-10-02 at 11 57 00 AM](https://github.com/user-attachments/assets/7d5af93e-e94c-4a2c-a4da-c3b3900f5cf3)

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. A "Select Existing File" option is available in the File field
2. Clicking the option opens a popup similar to other content selection popups
3. The popup allows browsing and searching for existing files in dotCMS
4. Selected file is properly linked to the File field upon confirmation
5. The popup is responsive and works well on different screen sizes

## Assumptions & Initiation Needs
- API for retrieving existing files in dotCMS is available
- Design specifications for the file selection popup are provided
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/30214
- [ ] https://github.com/dotCMS/core/issues/30215
- [ ] https://github.com/dotCMS/core/issues/30216
- [ ] https://github.com/dotCMS/core/issues/30217
- [ ] https://github.com/dotCMS/core/issues/30699
```

**Comment by dsilvam** [comment]
Passed IQA. Working as the current design specifies.
