### ISSUE TITLE
File field: Drag and drop functionality for file upload

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29872]
## Parent Issue
#29691 

## Task
Develop the drag and drop functionality for file uploads in the enhanced **File field**. This should allow users to drag files from their local system and drop them into the field for immediate upload.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. Users can drag files from their local system and drop them into the File field
2. Visual feedback is provided when a file is being dragged over the drop area
3. File upload process begins automatically when a file is dropped
4. Error handling for invalid file types or upload failures
5. Progress indicator for file uploads
6. Support for multiple file uploads if dropped simultaneously

## Assumptions & Initiation Needs
- Backend API for file uploads is available and documented
- File type restrictions and size limits are defined

**Comment by nicobytes** [comment]
QA Notes:

Create a  new content type with File field.

<img width="1010" alt="Screenshot 2024-09-27 at 11 42 25 AM" src="https://github.com/user-attachments/assets/f953881d-8b6a-4755-825c-6a1248fa35bd">


Case 1: Responsive for large screens

<img width="687" alt="Screenshot 2024-09-27 at 11 43 41 AM" src="https://github.com/user-attachments/assets/58f81e33-8ec7-4cdd-acd6-84e5b4cea1de">


Case 2: Responsive for small screens

<img width="428" alt="Screenshot 2024-09-27 at 11 44 12 AM" src="https://github.com/user-attachments/assets/54c4a65e-18a8-4ceb-8e5e-142d20695a9e">

Case 3: Upload files as dotAssets by dragging and dropping or clicking the "Choose File" button


https://github.com/user-attachments/assets/a2c1d685-48ad-49eb-ba72-af10055d51d3

**Comment by dsilvam** [comment]
Passed IQA: 
Tested all the cases from the last comment. 

Created a related issue https://github.com/dotCMS/core/issues/30182

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_324de85**, Docker, macOS 14.5, FF v126.0.1

Unable to drop multiple files at a time

https://github.com/user-attachments/assets/636e80b8-edaf-4a05-933f-70d0824ee54f

**Comment by oidacra** [comment]
Removed 6. Support for multiple file uploads if dropped simultaneously. This field handles files one by one.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_324de85**, Docker, macOS 14.5, FF v126.0.1
