### ISSUE TITLE
Implement UX design for enhanced File field

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#29871]
## Parent Issue
#29691 

## Task
Implement the UX design for the enhanced File field as specified in the design system. This includes the main field area for drag and drop, and the right-side links for additional options.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. The File field UI matches the design provided in the design system
2. The main field area displays "Drag and Drop or Choose file to upload"
3. Right-side links are implemented: "Select Existing File", "Import from URL", and "Create New File"
4. The layout is responsive and works well on different screen sizes

## Assumptions & Initiation Needs
- Access to the design system and detailed UI specifications
- Frontend development environment set up and ready

**Comment by dsilvam** [comment]
Passed IQA: 
File field rendering as designed. No functionality for now. 

![Image](https://github.com/user-attachments/assets/c26e9056-8a4b-4af5-8f5a-d128bd11555d)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b712244**, Docker, macOS 14.5, FF v126.0.1
