### ISSUE TITLE
webdav broken

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#29882]
### Problem Statement

WebDav request returns 5xx, see attached logs

[dotcms.log](https://github.com/user-attachments/files/16881464/dotcms.log)

### Steps to Reproduce

Connect to WebDav on Auth

### Acceptance Criteria

squash bug

### dotCMS Version

`trunk`

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C03PEHAKL6M/p1725484500871529

**Comment by bryanboza** [comment]
Tested on trunk with the following config 
![image](https://github.com/user-attachments/assets/0dcee57d-6ec3-4923-85e8-fa25ca96268f)


And I'm getting a 500 error, here the complete log: https://gist.github.com/bryanboza/5d8e66c56602658ce781978ead9618fd

**Comment by dsilvam** [comment]
Passed IQA. 
Tested browsing, adding, modifying and removing content using cyberduck.

<img width="890" alt="Screenshot 2024-09-05 at 2 56 46 PM" src="https://github.com/user-attachments/assets/512567bc-87fe-4c28-81f3-1e53d10756a0">

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF 

Sanity test on operations like: 
- Login 
- Create/delete folders
- Upload files/images 
- Delete 

New automated test for webdav will be added in the card #29902
