### ISSUE TITLE
UVE: Refresh Page After Closing Page Properties Modal

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29881]
### Problem Statement

After closing the page properties modal, the underlying page remains in a blurred state or is incorrectly displayed in the background. This creates a confusing user experience and can make the page appear unresponsive or partially obscured. To resolve this issue, the page should automatically refresh once the page properties modal is closed, ensuring that the interface is displayed correctly.

https://github.com/user-attachments/assets/d0a67d44-f0ed-4529-b305-825f947e4979

### Steps to Reproduce

- Login as admin
- Try to edit any page 
- Open the page properties modal in the content management system.
- Make any changes or simply close the modal without making changes.
- Observe that the underlying page is left in a blurred state or is not displayed correctly.

### Acceptance Criteria

**- Automatic Page Refresh:** Ensure that the page refreshes automatically after the page properties modal is closed.
**- Remove Blurring/Background Display Issue**: Ensure that the underlying page is displayed correctly and without any visual glitches (e.g., blurring) after the modal is closed.

### dotCMS Version

Tested on trunk // docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment]
## Internal QA: Passed.

The issue couldn't be reproduced anymore. It was tested using the docker image `dotcms/dotcms:nightly_8040597` through the all the three supported browsers (`Chrome, Firefox, Edge`).


Uploading Screen Recording 2024-09-16 at 12.49.45.mov…

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4359825**, Docker, macOS 14.5, FF v126.0.1
