### ISSUE TITLE
UVE: Toolbar Workflow Action Button Not Functioning Correctly

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#29891]
### Problem Statement

The `Move` button under the expanded Workflow Actions in the toolbar does not trigger any action when clicked.

https://github.com/user-attachments/assets/81679dd5-3d4a-450b-be13-8093df816b14

### Steps to Reproduce

1. Edit any page
2. Expand the Workflow Actions button in the toolbar
3. Try click the `Move` button

### Acceptance Criteria

The `Move` button under Workflow Actions triggers the appropriate action.

### dotCMS Version

Tested on qa master server
`dotcms:trunk_e622545`
Chrome

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test case # 22 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by rjvelazco** [comment]
Closed in favor of: https://github.com/dotCMS/core/issues/29920
