### ISSUE TITLE
Issues/invalid characters in the exported packages list causes system bundles to no longer load

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#29899]
### Problem Statement

When there are invalid characters/issues with the exported packages listed in the Plugins portlet, system bundles stop loading as well as any uploaded plugins

### Steps to Reproduce

1. Load up a demo starter
2. Go to the plugins portlet
3. Intentionally add a bunch of invalid characters (commas, slashes, etc) to the exported packages list near the top
4. Save the exported packages
5. Refresh the portlet
6. Click 'Show System Bundles' 

It will look like this:

![image](https://github.com/user-attachments/assets/dc9bf6a2-d36f-44ac-a6d8-0bd329881a1e)

Many of the System bundles are in an 'Installed' state

### Acceptance Criteria

Invalid exported packages should not cause system bundles to stop populating
Invalid exported packages list should be able to self resolve by resetting when encountering an error and reprocessing exported packages on deployed bundles 

### dotCMS Version

Current, all LTS versions

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
I know may be out of the gardening day scope, but will take advance I have a day to concentrate on this

**Comment by dsilvam** [comment]
Passed IQA: 
* Added invalid characters to the exported packages
* Reloaded plugins portlet
* Clicked on show system plugins

They all look active

![Image](https://github.com/user-attachments/assets/1aa48d5a-6334-4db5-bef2-c24e22f7f8cf)
