### ISSUE TITLE
UVE: Incorrect Redirection After Saving or Publishing UrlContentMaps

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#29896]
### Problem Statement

After saving or publishing a UrlContentMap, the system incorrectly redirects to the content type’s detail page.

https://github.com/user-attachments/assets/1b4f74fa-f0b7-46f4-b389-a1bc63f52f7b

### Steps to Reproduce

1. Edit a Blog page
3. Save and publish
3. Observe that you are redirected to `/blog/blog-detail`

### Acceptance Criteria

- The UrlContentMap we are editing should remain visible after save and publish.
- No unexpected redirection should occur.

### dotCMS Version

Tested on qa master server
`dotcms:trunk_e622545`
Chrome

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Note to QA:** Please, additionally test case # 17 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by fmontes** [comment]
This is expected, is not a blocker, this is how it worked normally, now I have an idea: we can look if when we save and publish the contentlet we have the `urlTitle` and if we do have we can use that to do the reload instead of the url. If is harder than that move to Future.

**Comment by dcolina** [comment]
## Internal QA: Passed.

The issue couldn't be reproduced anymore. It was tested using the docker image `dotcms/dotcms:trunk_fd26189`.

https://github.com/user-attachments/assets/5cb92148-b22a-474d-9175-70a2fc4f543d

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF
