### ISSUE TITLE
UVE: Prompt to create page in specific language appears twice

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29906]
### Problem Statement
In the UVE, the prompt to create a page in a specific language is appearing twice, causing confusion for users.

### Steps to Reproduce

https://github.com/user-attachments/assets/b7f544c4-c7dd-4576-a93b-b2135f82ced9

### Acceptance Criteria
- [ ] Modal should not show again when user hits "No"
- [ ] The dropdown options should have highlight the selected options by default

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
- QA should verify that the prompt only appears once when creating a page in a specific language.
- A temporary workaround is to click "no" on the second prompt to proceed with the selected language.

**Comment by zJaaal** [comment]
Closed in favor of https://github.com/dotCMS/core/issues/29572 since it was QA Rejected by this same issue.
