### ISSUE TITLE
Relationship order get changed when adding new content

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#29924]
### Problem Statement

Relationship order get changed when adding new content

### Steps to Reproduce

1. create a relationship to two or more pieces of content
2. save the content
3. choose "relate new content"
4. add the content
5. the previous order of the relationship is mixed up

### Acceptance Criteria

the order should be maintained and the new content should get added last in the order

### dotCMS Version

current

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by prestonso** [comment]
@wezell believes this happens because you can't order parent content from a child. Works as designed. You can only order children.
