### ISSUE TITLE
UVE: Unable to execute sub-actions

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29920]
### Problem Statement

- [x] Users are currently unable to execute sub-actions on pages

Users are currently unable to execute sub-actions on pages within the dotCMS platform. This issue affects the functionality of sub-actions, such as copying, publishing, or archiving pages, which are critical operations for content management workflows. The inability to perform these sub-actions impacts both content creators and administrators, leading to delays in content updates and management. This issue occurs across multiple browsers and operating systems, with no discernible difference in behavior between them.

https://github.com/user-attachments/assets/f7a86c7f-61af-400b-a0e9-26f4ae8d8849

### Acceptance Criteria

- Sub-actions should provide immediate feedback to users, confirming whether the action was successful or failed.

### dotCMS Version

Tested on trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by bryanboza** [comment]
Note: It's important to identify which change broke this, as we don't have any card reported with recent changes related to that functionality.

**Comment by nollymar** [comment]
@dsilvam @nicobytes The PrimeNG upgrade seems to be the root cause

**Comment by nollymar** [comment]
We have scoped the issue. @rjvelazco will fix this specific case and @nicobytes will make sure that everything else is working as expected after the PrimeNG upgrade

**Comment by bryanboza** [comment]
I added another case regarding classes on rows and columns. Please take care of that as well.

**Comment by rjvelazco** [comment]
@bryanboza Create a separate card for that. This was not included in the ticket estimation

**Comment by rjvelazco** [comment]
This ticket also solves:
- https://github.com/dotCMS/core/issues/29920

**Comment by nollymar** [comment]
**Note to QA**: Please, additionally test case # 22 of the [Regression Tests spreadsheet](https://docs.google.com/spreadsheets/d/14pu6MA6QbRumsrj-8hNTkerw4dbWJ_GZru1qfaomlpU/edit?usp=sharing)

**Comment by nollymar** [comment]
@dsilvam @nicobytes [this PR](https://github.com/dotCMS/core/pull/29932) fixes the problem related to the sub-actions. As this issue changed scope, we have linked the PR so you can continue with the remaining issues.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected
