### ISSUE TITLE
Can't add a class to a container or row from the layout editor

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#29923]
### Problem Statement

Can't add a class to a container or row from the layout editor

### Steps to Reproduce

edit a page layout and try to add a class to a container or row

### Acceptance Criteria

it works

### dotCMS Version

current

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by nollymar** [comment]
Dupe of #29935
