### ISSUE TITLE
Layout Builder: Unable to add classes to rows and columns

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29935]
### Problem Statement

[ ] Unable to add classes to rows and columns in the layout builder 

Users are unable to add custom CSS classes to rows and columns in the layout builder within dotCMS. This feature is crucial for content creators and designers who need to apply specific styling or functionality to sections of the layout. Without the ability to add classes, users are forced to apply inline styles or custom solutions, which reduces flexibility and can lead to inconsistencies in the layout. 

https://github.com/user-attachments/assets/c72f5b71-04d5-46fb-8024-9204dcfb8777

### Steps to Reproduce

- Log into the dotCMS backend.
- Navigate to the layout builder.
- Attempt to add a custom CSS class to a row or column within the layout.
- Observe that the field for adding classes is either missing or not functioning, preventing the class from being applied.

### Acceptance Criteria

- We need be able to add classes to rows and columns without problems 

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by hmoreras** [comment]
Pass internal QA, now the user can add a custom class

https://github.com/user-attachments/assets/466dd5d2-6512-4124-8424-5514646ffbf2

**Comment by bryanboza** [comment]
Fixed, now we are able to add classes without problems... New enhancement reported here: https://github.com/dotCMS/core/issues/29983
