### ISSUE TITLE
Many to One Relationship Not Maintained When Copied to New Host

### ISSUE THREAD

**Issue by patrick-schweiger** [dotCMS/core#29938]
### Parent Issue

https://github.com/dotCMS/core/issues/29256

### Problem Statement

When parent and child content exists on another host, a Many to One Relationship is not being maintained when a site is copied to another host. 

This is currently impacting a customer and seems to be an outlier as this does not appear to be an issue with other cardinalities. 

### Steps to Reproduce

To test in the demo site, copy the demo site. 

- Create the many to one relationship field on a content type. ![Screenshot 2024-09-09 at 4 37 56 PM](https://github.com/user-attachments/assets/ff305e92-6ae1-48e0-a667-d8a976355856)
 
- Then create a content item with the parent on Site A and the child (related content, in this case the Activity pictured below) on Site B. 
![Screenshot 2024-09-09 at 4 32 57 PM](https://github.com/user-attachments/assets/bb3aab9d-0b25-4d0b-a683-66d2d5cc90e4)

- Use the site copy tool, copying Site A with all objects checked. When reviewing this new copied site and looking at parent content item that was copied, you will see the relationship is no longer present. 
![Screenshot 2024-09-09 at 4 36 56 PM](https://github.com/user-attachments/assets/8a5238ca-2975-4e62-a6de-2c3053ff694e)

### Acceptance Criteria

When parent and child content exists on another host, a Many to One Relationship should be maintained when a site is copied to another host. 

### dotCMS Version

latest current release, demo, all lts versions

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C035XMEDQ4F/p1725904713408219
Generated from a customer request.

**Comment by dsilvam** [comment]
Passed Internal QA. 

Followed the steps in the description using the same Content Types and after copying the original demo site, the copied version included the Banner Carousel contentlet with the related Activity. 

![Image](https://github.com/user-attachments/assets/21b5198a-79f7-425c-ad81-d489401ad22c)

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_62799e6**, Docker, macOS 14.5, FF v126.0.1
