### ISSUE TITLE
Double preview on binary fields: displaying both old and new editors

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29939]
### Problem Statement

When previewing binary fields in dotCMS, both the old and new versions of the editors are being displayed simultaneously. This creates confusion for users and clutters the interface, making it difficult to determine which editor should be used for file management. The issue impacts all users working with binary fields and affects usability by showing redundant UI elements. This is observed across multiple browsers and operating systems.

![image](https://github.com/user-attachments/assets/86d213c1-a4d4-4e0f-b281-00945524966c)

### Steps to Reproduce

- Log into the dotCMS backend.
- Navigate to a content type or page that includes a binary field (e.g., file upload).
- Attempt to preview or edit the binary field.
- Observe that both the old and new versions of the binary field editors are displayed.

### Acceptance Criteria

- Only the new version of the binary field editor should be displayed when previewing or editing a binary field.
- The old version of the editor should be fully deprecated and removed from the UI.

### dotCMS Version

Tested on trunk // Docker // FF

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by bryanboza** [comment]
FYI: Tested with the last trunk image `trunk_9dea667` and it is happening in any browser 

![image](https://github.com/user-attachments/assets/31371841-3aa1-4530-9845-12f4e664f006)

**Comment by hmoreras** [comment]
Note: 

Related to this update: https://github.com/dotCMS/core/issues/29857 

Note to QA: 

- Test the Binary Field with all supported files to make sure that each case displays correctly. 
- Bryan comment regarding text overlapping the buttons, moved to a gardening day: https://github.com/dotCMS/core/issues/29966

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_c753a0f`

Opening and editing binary files is now displaying only one editor. Tested with existing both Demo Starter files, and uploaded files.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after this fix: 
![Image](https://github.com/user-attachments/assets/d692b379-4bfb-41c9-b4ca-78207ab7d795)
