### ISSUE TITLE
QA for Upgrade PrimeNG from Version 15-LTS to Version 17

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#29949]
### Parent Issue

https://github.com/dotCMS/core/issues/29058

### Task

Manual testing of the different backend screens to ensure they didn't break after the upgrade. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Given list of screen and test cases covered

**Comment by dsilvam** [comment]
https://docs.google.com/document/d/1oVjDkjTLup9jCAIikhg3RnEdSw7P66HO_Tf5KSlpXrE/edit

**Comment by dsilvam** [comment]
This was completed.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master**, Docker
