### ISSUE TITLE
[Localization] : Language Variables in HTML Page are not respecting the Language set in current Session

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#29946]
### Parent Issue

Reported via Enterprise Support. No ticket number available yet.

### Problem Statement

According to our [Multi-Site Language Configuration](https://www.dotcms.com/docs/latest/multi-site-language-configuration) documentation, dotCMS Users/Developers are able to access the current Session via the `$request` object, and update the Language that HTML Pages are being rendered in.

However, it seems that such an update is not working as expected when it comes to the `$text` ViewTool returning Language Variables in the updated Language. If your default language is English, it'll keep returning the value of the Language Variable in English.

### Steps to Reproduce

1. Log into dotCMS, go to the `Site > Templates` portlet.
2. Create an `Advanced Template`, and name it `My Custom Template`. Add the following source code:
```vtl
<html>
    <header>
        <title>My Custom Template</title>
    </header>
    <body>
        <div>
            #if($UtilMethods.isSet($!{request.getParameter("lang")}))
                #set($languages = $text.getLanguages())
                #foreach($language in $languages)
                    ## ========================================================================
                    ## Use the first language that matches if no country code is specified.
                    ## ========================================================================
                    #if($UtilMethods.contains($!{language.getLanguageCode()}, $!{request.getParameter("lang")}))
                        #set($languageId = $!{language.id})
                        #set($flag = "")
                        ## ========================================================================
                        ## Update our session language
                        ## ========================================================================
                        #if(!$UtilMethods.contains($flag, "true"))
                            $request.getSession().setAttribute("com.dotmarketing.htmlpage.language", "$languageId")
                            $request.getSession().setAttribute("flag", "true")
                        #end
                    #end
                #end
            #else
                <h4>No language was specified, using the default one</h4>
            #end
            <p>Current language ID: $request.getSession().getAttribute("com.dotmarketing.htmlpage.language")</p> 
            <p>Language Variable 'customvar': $text.get("customvar")</p>
        </div>
    </body>
</html>
```
3. Go to the `Content > Search` portlet, and create a Language Variable in both English and Spanish:
3.1. Language = `English`, Key = `customvar`, Value = `My website`
3.2. Language = `Spanish`, Key = `customvar`, Value = `Mi sitio web`
4. Create an HTML Page using the `My Custom Template` you created before named `test-page`. Create it in both English and Spanish.
5. Open it in the back-end. You'll see that the Language Variable shows up in both languages depending on the selected page language. This is the expected behavior.
6. Now, open another browser or an Incognito Window with this URL: http://localhost:8080/test-page?lang=es . You'll see that the Language Variable is displayed in English:

<img width="449" alt="Screenshot 2024-09-10 at 10 45 32 AM" src="https://github.com/user-attachments/assets/888879fc-a5c8-4d92-adc5-2a3aa48b1414">

### Acceptance Criteria

Updating the currently selected Language in the Session object must render Language Variables in the specified Language.

### dotCMS Version

Version 24.08.20 and older, and latest master.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1725628920476489

**Comment by wezell** [comment]
This is not the way to set languages in dotCMS.  Use either a rule or a vanityurl.  Doing languages this way will break page cache.

**Comment by wezell** [comment]
We need to fix this in the doc site @jdcmsd

**Comment by jdotcms** [comment]
regarding the issue: the future language is not being retrieve from the session, instead of this is being retrieved from the request, that said if you use 
```
$request.setAttribute("com.dotmarketing.htmlpage.language", "$languageId")
```

Rather than
```
$request.getSession().setAttribute("com.dotmarketing.htmlpage.language", "$languageId")
```

Will work

**Comment by jdotcms** [comment]
btw, it is really bad that the templates only have save on the edit screen, it is kinda annoying to get back to the main page in order to publish

**Comment by wezell** [comment]
Keep in mind that setting the language anywhere in the page render is too late to change the language of the page being rendered.

The page of the language is set before velocity has been rendered:

https://github.com/dotCMS/core/blob/main/dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java#L133

**Comment by jdcmsd** [comment]
Removed all references to setting session attributes via Velocity; instead, recommended adding language param via rule or vanity URL.

Also de-emphasized the use of the word "rule" in the URL filter section, to avoid ambiguity with dotCMS rules.
