### ISSUE TITLE
Spike: How to Update Workflow Actions to support new content edit features

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29952]
### User Story

As a content architect, I want to be able to specify which Workflow actions are primary and secondary, and provide help tips for each workflow action, to make it easier for content editors to know what actions to take.

### Acceptance Criteria

* Workflow Actions contain a new property: `Priority`.
    * The choices are `Primary` and `Secondary`.
    * The default choice is `Primary`.
* Workflow Actions contain a new property: `Hint`.
    * The field where this property is entered behaves the same as the `Hint` field in the content type field properties.
* All Workflow APIs which return information about a Workflow action include the values for `Priority` and `Hint` in the response.
    * This includes `findActionsByStep`, `findAvailableActions`, etc.
* All Workflow viewtool methods which return information about a Workflow action include the values for `Priority` and `Hint` in the response.
    * This includes `findAction`, `findActions`, etc.
* These additional properties are enabled by the feature flag for the new content edit screen.
    * When the feature flag is disabled, the new properties are not displayed in the responses for either the APIs or the viewtool methods.
* The order of actions returned by both APIs and viewtool methods must match the order that those actions are shown in the Workflow portlet.

**Note:** These properties are not currently used outside the new content edit screen.  This card needs to be completed before the new content edit screen can implement the new workflow action menus.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
@jcastro-dotcms note that I added one bullet to the end of the acceptance criteria, about the order of the results.

**Comment by jcastro-dotcms** [comment]
In conclusion, the `metadata` column in the `workflow_action` table can effectively be used to store this new Priority data. The `metadata` column is already displayed and handled by the API so all instances of the Workflow Action class have it, it'd be just a matter of exposing such data to the system.
