### ISSUE TITLE
Spike: determine the effort required to include a Cube playground in Angular

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#29969]
### Task

There's the need to offer querying capabilities to the users of Content Analytics and providing a query builder for CubeJS would provide a better UX.  

This task is to determine the effort required to include a Cube playground as a portlet in the dotCMS backend. 

There this blog where they describe how to implement something like this that we might find useful https://cube.dev/blog/angular-dashboard-tutorial-with-cubejs. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

* Having an estimate of the effort required to include the Cube playground as a portlet in our backend.

**Comment by hmoreras** [comment]
Findings: 

Cube has a playground itself, but as they mention is not recommend to exposed out of dev mode, so they offers the options to expose their data one is via a [SDK for Angular](https://cube.dev/docs/product/apis-integrations/javascript-sdk/angular) that helps for query and visualization of data. 

We will need to implement the playground using the layout and graphics or our choice. 

- [ ] Design of the playground. 
- [ ] Implement the graphics and how to show results.
