### ISSUE TITLE
Bundle name field doesn't get populated on the receiving server 

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#29961]
### Problem Statement

- We're no longer populating the "Bundle Name" field (site -> publishing queue) on the receiving server
- The "Bundle Name" gets populated on the sending server only
- Logs show no error
- Manifest show no error
- I manually created and named a bundle and pp after that, but the Bundle Name (only on the receiving host) remains empty
- Tested locally on 24.04.24
- reported to be happening on 22.03.10 also

### Steps to Reproduce

- Push publish any content from endpoint 1 to endpoint 2
- Check the site -> publishing queue on the receiving server
- The field will be empty

### Acceptance Criteria

- The Bundle Name field should be populated with the bundle name on the receiving server 

### dotCMS Version

24.04.24
22.03.10

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://helpdesk.dotcms.com/a/tickets/27501

**Comment by erickgonzalez** [comment]
Bundle Name Column was removed.
