### ISSUE TITLE
Text overlapping buttons in binary field 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#29966]
FYI: Tested with the last trunk image `trunk_9dea667` and it is happening in any browser 

![image](https://github.com/user-attachments/assets/31371841-3aa1-4530-9845-12f4e664f006)

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/29939#issuecomment-2339228729_

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b712244**, Docker, macOS 14.5, FF v126.0.1
