### ISSUE TITLE
Write to security log when overriding config vars

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29978]
### User Story

When a user overrides a config variable in dotCMS, we need to write to the security log that the change is being made

### Acceptance Criteria

Write to the log when a new config variable is written or deleted

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed IQA:
```
dotcms-1      | 17:32:51.954  INFO  util.SecurityLogger - class com.dotcms.business.SystemTableImpl : Deleting system table key:DOT_CACHE_ CONTENTLETCACHE_SIZE -- ip:192.168.65.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
dotcms-1      | 17:32:57.650  INFO  util.SecurityLogger - class com.dotcms.business.SystemTableImpl : Saving system table value for key:DOT_CACHE_ CONTENTLETCACHE_SIZE=8888 -- ip:192.168.65.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a93b537**, Docker, macOS 14.5, FF v126.0.1


<img width="865" alt="Screenshot 2024-10-03 at 11 19 56 AM" src="https://github.com/user-attachments/assets/bb453d0a-8088-4da8-915c-4e197bd7b578">
