### ISSUE TITLE
UVE: Enterprise features need to be disabled on Community Edition

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29977]
### Problem Statement

In the dotCMS Community Edition, enterprise-only features are currently visible and active, leading to confusion among users who attempt to access these functionalities. Since these features are not available in the Community Edition, they should be clearly marked as disabled or hidden entirely. The current visibility of enterprise features creates a poor user experience by presenting functionalities that are inaccessible, leading to potential frustration and unnecessary support requests. This issue impacts all users of the Community Edition across different browsers and platforms.

https://github.com/user-attachments/assets/d5e973b6-0f29-494e-b6eb-e75c9f425bdd

### Steps to Reproduce

- Log into the dotCMS Community Edition.
- Try to edit some page 
- Observe that enterprise-only features are visible and appear active (e.g., layout, rules, A/B, etc.).
- Attempt to use one of these enterprise features.
- The system restricts access with an error.

### Acceptance Criteria

All enterprise-only features should be visibly disabled or hidden in the Community Edition.

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment]
## Internal QA: Passed.

It was tested through the three supported browsers (Chrome, Firefox and Edge) using the docker image `dotcms/dotcms:trunk_dea1913`.

As we notice on the video below the error can't be reproduced anymore.

https://github.com/user-attachments/assets/3fe3e028-f341-49ee-8e0a-87d652dcad4d

**Comment by bryanboza** [comment]
There is an inconsistent behavior here:

The easier way to reproduce it is to apply an EE license and then remove it. After that, try editing the page. However, I’ve also reproduced it sometimes just by starting up the system.

Attached a video: https://github.com/user-attachments/assets/0fff075a-a395-4a78-a3cd-65d46b480e51

**Comment by valentinogiardino** [comment]
There is a noticeable difference in how the license is detected when performing a full page reload versus not doing so after removing the license. This inconsistency affects various portlets, not just UVE. I've written a document detailing the different scenarios: [Dotcms EE license validation - issues](https://docs.google.com/document/d/1dZOTlCgL2GMs4MdDNzkxg6qYzIUwaHRkBubgvJZ4-RY/edit?usp=sharing).

**Comment by bryanboza** [comment]
Fixed, now we are adding the blank space corresponding to the added content. 

![Screenshot 2024-10-07 at 2 36 04 PM](https://github.com/user-attachments/assets/85b9b0be-d130-423a-9bab-46098d0d876e)

**Comment by nollymar** [comment]
The last issue reported is out of the scope as this is how the application in general behaves, not related to UVE
