### ISSUE TITLE
Valentino: Drop Everything & Learn Oct 23 - Nov 05

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29989]

**Comment by valentinogiardino** [comment]
I spent time learning about microservices design patterns, focusing on the SAGA and CQRS patterns. The SAGA pattern helps manage distributed transactions across microservices to ensure data consistency, while the CQRS pattern separates read and write operations to optimize performance and scalability.

Resources I found helpful:

- Video series on microservices patterns and best practices: [YouTube](https://www.youtube.com/watch?v=aOen1-pQLZg&list=PLVz2XdJiJQxw1H3JVhclHc__WYDaiS1uL)
- In-depth overview of the SAGA pattern: [Microsoft Docs](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/saga/saga)
- Article on the SAGA pattern in microservices: [Medium](https://medium.com/cloud-native-daily/microservices-patterns-part-04-saga-pattern-a7f85d8d4aa3)
- Guide to CQRS and event sourcing in Java: [Baeldung](https://www.baeldung.com/cqrs-event-sourcing-java)
