### ISSUE TITLE
Blocks Not Displaying Correctly in Block Editor After Creating a New Contentlet

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#29999]
### Problem Statement

After creating a new contentlet and selecting a block using the block editor, the blocks are not displaying correctly. The issue appears to distort or misalign the block options, making it difficult for users to select and use the correct block elements. 

### Steps to Reproduce

1. Navigate to the content creation section of the application.
2. Create a new contentlet.
3. Open the block editor to select a block for the content.
4. Observe that the blocks are not displaying correctly (e.g., overlapping text, distorted block elements)

### Acceptance Criteria

The block editor should display all block options clearly and in a well-organized manner, allowing users to select and add blocks without visual issues.

### dotCMS Version

24.09

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2024-09-13 at 12 38 28 PM](https://github.com/user-attachments/assets/4fef8e29-21e7-49a5-83e5-a3579e00eaaa)

**Comment by dsilvam** [comment]
Not related to PrimeNG upgrade

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_ea7843a**, Docker, macOS 14.5, FF v126.0.1

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_ea7843a`

The block dropdown is displaying correctly now:

<img width="851" alt="Screenshot 2024-09-19 at 2 34 23 PM" src="https://github.com/user-attachments/assets/d99fd27c-ba19-4b97-90d6-75a2e5f9e3cb">
