### ISSUE TITLE
Forms portlet not working: redirects to Content Types portlet and unable to add new content types/forms

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29997]
### Problem Statement

Users are experiencing issues with the Forms portlet in dotCMS. When attempting to access the Forms portlet, the system redirects to the Content Types portlet instead of displaying the forms management interface. Additionally, when trying to add a new content type, the system fails to add it and redirects users to the Welcome portlet instead. This problem impacts content administrators and editors who need to create and manage forms and content types. 

https://github.com/user-attachments/assets/d9b6c2ab-6ed5-46fc-a6f0-fadd4a756faa

### Steps to Reproduce

- Login as admin
- Go to marketing --> Forms 
- Attempt to create a new content type / form 

### Acceptance Criteria

- **Correct Navigation:** Accessing the Forms portlet should display the forms management interface without redirecting to other portlets.
- **Functionality to Add Forms:** Users should be able to create and manage forms through the Forms portlet seamlessly.

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by nicobytes** [comment]
IQA Approved with **trunk_8040597**


https://github.com/user-attachments/assets/835cdd14-16da-4ccb-ac23-f9a15cccd109

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_49902f3**, Docker, macOS 14.5, FF v126.0.1
