### ISSUE TITLE
New Category Field: Clearing selection on side panel does not clear the selection on the tree

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30008]
### Problem Statement

When the selected categories are cleared on the right panel on the new category field dialog, those categories are not cleared from the tree.

https://github.com/user-attachments/assets/2236460b-1e2d-44e5-9221-6d7c599bbbc1

### Steps to Reproduce

* Create a content type with a category field
* Make it show the new content editor
* Open the cat field and select some categories from the tree
* Clear the selection on the panel on the right
The selected categories will remain selected on the tree.

### Acceptance Criteria

When clearing the categories by hitting the "Clear" button they need to clear on:
* The right side panel
* The category tree

### dotCMS Version

trunk_250741a

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nicobytes** [comment]
IQA passed with **trunk_477606b**



https://github.com/user-attachments/assets/484eae57-e545-4ceb-83fd-01df6a515593

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_477606b**, Docker, macOS 14.5, FF v126.0.1
