### ISSUE TITLE
Folder Name Validation

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#30003]
### User Story

As a dotCMS backend user, I want to be able to validate the URLs generated when creating a folder in dotCMS, so I can prevent uppercase and special characters from appearing in the URL

### Acceptance Criteria

Add options to the modal for creating folders so that the generated URL will avoid using uppercase and special characters.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27474

**Comment by prestonso** [comment]
Pushing to Airfocus as a feature request. Thanks @weiyiwang-dotcms!
