### ISSUE TITLE
Implement Show/Hide Toggle for Hidden Column

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30015]
## Parent Issue
#30014 

## Task
Implement the show/hide toggle functionality for the hidden column feature.

https://github.com/user-attachments/assets/ff5d7928-47d1-4875-beec-e95a3053e2bd

## Proposed Objective
Same as Parent Issue

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria 
- Create an icon button to toggle the hidden column
- Implement smooth animation for showing/hiding the column
- Ensure the toggle state is preserved across page reloads
- Update any necessary layout components to accommodate the hidden column

## Assumptions & Initiation Needs
- Design assets for the toggle icon are available
- Parent issue is properly set up and accessible

## Quality Assurance Notes & Workarounds
- Verify that the animation is smooth and doesn't cause layout shifts

**Comment by hmoreras** [comment]
QA Note: 

We are showing the close icon and leaving the space for the tabs that will be implemented in other card. The state is preserved ( close/open) and saved in localstorage. 

https://github.com/user-attachments/assets/b05007a0-5316-4a53-94d7-f2f167651129

**Comment by dsilvam** [comment]
Passed IQA: 
* Button present and showing/hiding the sidebar
* Shown/Hidden state preserved when exiting and re-entering on the edit content screen

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_f1b34e9**, Docker, macOS 14.5, FF v126.0.1
