### ISSUE TITLE
Logs not written to dotcms.log (or catalina.log)

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30011]
### Problem Statement

We unified our logging and now both tomcat and dotcms logs get written to console out - which is good.  What we lost was also writing the logs to a file that a user can tail.

This means debugging things like osgi plugins or velocity errors is almost impossible without having access to the log aggregation system.

I think we should be writing to dotcms.out and stdout.

### Steps to Reproduce

1. Tail the logs from the maintenace tab

2. Go to the velocity portlet - run some bad velocity code like:
```
#set($testing = "asdasdasds)
```

3. There is nothing in the logs about the bad velocity.

### Acceptance Criteria

Write logs to both dotcms.out and stdout.

Show osgi errors in both.
Show velocity errors in both.

### dotCMS Version

24.09

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by spbolton** [comment]
@wezell your description talks about dotcms.out file, the file it was logging to before and after this change is dotcms.log.  I can successfully tail dotcms.log from the maintenance screen on demo.dotcms.com as well as master and it does report an error using #set($testing = "asdasdasds) .  So I cannot replicate any issue with the logging here per-se.   Now this does not specifically test logging from external osgi plugins that I was concerned about specifically with the mapping between use of slf4j1 and slf4j2 apis, this would depend upon what logging and dependencies the specific osgi plugin has.   Is there one on top of the missing log file you were seeing that I can test.   Were you testing with a mapped log4j.xml file that is not the default?

<img width="1355" alt="Screenshot 2024-10-08 at 18 04 32" src="https://github.com/user-attachments/assets/4d3ee154-76b0-4e53-b649-4156b40f987f">

**Comment by spbolton** [comment]
@wezell reported that it is no longer reproducible.  We should close and reopen if we see this again.
