### ISSUE TITLE
Content added as the default fileAsset content type regardless of folder settings

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#30023]
### Parent Issue

https://github.com/dotCMS/core/issues/27322

### Problem Statement

Users are able to set the default file asset type on folders
When adding files to dotCMS via the content edit screen, dotCMS will ignore the default file asset setting of the folder and add the file as a fileAsset content type.

### Steps to Reproduce

Create a new content type
Create a new folder
Assign the default file asset type of the folder to the new content type we just created
Create another content type with a file field
Content > Search > Add New Content
When adding the content for the file field, upload a new asset into the folder we created earlier.
Once the content creation is complete, you will see that the file we added is a default "fileAsset" content type.

### Acceptance Criteria

Have the file uploaded through the content creation menu respect the default file type set on the folder

### dotCMS Version

Reproducible on 24.08.27

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/24385

### Quality Assurance Notes & Workarounds

While selecting a workflow action to perform on the file that is uploaded, dotCMS only displays the workflows that are assigned to the default fileAsset content type.

**Comment by erickgonzalez** [comment]
Working as it should, now when you upload a file from the file uploader, it respects the folder default file asset type.

**Comment by bryanboza** [comment]
Fixed, now this is working as expected. 

Once you select some specific content type in a folder any upload file will be of this type. 

Tested on main // Docker // FF
