### ISSUE TITLE
Need to ship with the updated glowroot.jar

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30024]
### Problem Statement

Running glowroot from a centralized folder is no longer possible without box specific config.  It seems like the simplest  solution would be to ship with the glowroot 14 jar in our distribution and point to that  We will still need to configure the central collector address AND the glowroot_id for the rolled up data, though this could be done by just adding the information to java startup, e.g. 
```
-Dglowroot.collector.address=glowrootcentral.com:8181 -Dglowroot.agent.id=k8s.corpsites::auth
```
### Steps to Reproduce

Add glowroot.jar to the `/data/shared` directory.  Start multiple dotCMS instances using the shared jar.  You will see a message in the start of the dotCMS logs that says:
```
2024-09-16 17:20:25.071 ERROR org.glowroot - Glowroot failed to start, directory in use by another jvm process: /data/shared/glowroot (unable to obtain lock on /data/shared/glowroot/tmp/.lock).  If you are trying to monitor multiple JVM processes on one box from the same agent installation, please see instructions for how to do this on the wiki: https://github.com/glowroot/glowroot/wiki/Agent-Installation-(for-Central-Collector)#monitoring-multiple-jvm-processes-on-one-box
```

### Acceptance Criteria

ship with glowroot.jar in the /srv folder.  Make sure that multiple dotCMS instances can start with glowroot enabled without needing new config parameters.

### dotCMS Version

24.08

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment]
## Internal QA: Passed.

The reported issue couldn't reproduced anymore. It was testing using the docker image `trunk_fd26189`.

Here is a video where we can notice how it works running on docker.

https://github.com/user-attachments/assets/52b23515-0df1-4938-aedd-2b8d7fe93e2f

**Comment by nollymar** [comment]
QA notes: Our servers were updated and are now running with the new Glowroot

**Comment by nollymar** [comment]
The details of the doc are found here: 
https://github.com/dotCMS/core/pull/30560
https://github.com/dotCMS/core/pull/30339
