### ISSUE TITLE
Implement Main Tabs for Edit Contentlent

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30022]
## Parent Issue
#30012 

## Task
Implement the main tabs for the Edit Contentlent interface according to the final design specifications.

## Proposed Objective
Technical User Experience

## Proposed Priority
Priority 2 - Important

## Acceptance Criteria 
1. Implement the final design of the tabs in the new Edit Contentlet
<img width="1072" alt="Screenshot 2024-09-16 at 12 20 21 PM" src="https://github.com/user-attachments/assets/e9864fd0-f6c1-4996-9883-420a8b7a4849">

**Comment by oidacra** [comment]
# Internal QA Steps

## 1. Contentlet Operations
- Create a new contentlet and verify it saves properly
- Edit the saved contentlet and confirm changes are maintained
- Check that all fields are saving correctly

## 2. Tab Display Rules
- Single Tab:
  1. Create a content type with only the default Content tab
  2. Verify no tab navigation appears
  3. Check all content is visible and accessible

- Multiple Tabs:
  1. Create a content type with 2+ tabs
  2. Verify both Content tab and custom tab(s) are visible
  3. Check you can switch between tabs normally

## 3. Back Button Navigation
- Work on a content type
- Click back button
- Verify it returns to the correct content type you were working on

## 4. Sidebar Controls
- Click open/close sidebar buttons
- Verify sidebar opens and closes correctly
- Check it works from different sections

**Comment by dsilvam** [comment]
Passed Internal QA. 
I am capturing small style details that can be worked on GD.

Design: blue font for selected
![Image](https://github.com/user-attachments/assets/117789e6-cb16-4248-a170-569eca93579d)

Implementation: black font for selected
![Image](https://github.com/user-attachments/assets/7eb6cc2d-1195-4e43-960b-4b6a0f84ad15)

Design: hover area smaller with radius 
![Image](https://github.com/user-attachments/assets/89559d5c-8d01-4851-b50a-4bd47493a51c)

Implementation: bigger over area without radius 
![Image](https://github.com/user-attachments/assets/e6ed1972-0d58-499b-9530-1a96e1a00522)

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_fe2a36c**, Docker, macOS 14.5, FF v126.0.1

When switching an already existing content like blogs to the new Edit, some of the already existing tabs are not getting throughout the change

**New**
![Screenshot 2024-10-29 at 1 58 35 PM](https://github.com/user-attachments/assets/d2c67922-5000-4a26-aaff-fe10f3415a1b)

**Old**
![Screenshot 2024-10-29 at 2 00 08 PM](https://github.com/user-attachments/assets/74375581-b6bb-4350-9a28-05014dd902ea)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fe2a36c**, Docker, macOS 14.5, FF v126.0.1

Feedback from [above](https://github.com/dotCMS/core/issues/30022#issuecomment-2445225461) will be place in the new sidebar feature.
