### ISSUE TITLE
Make the Changes Required in PageResource for UVE - Future Time Machine

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30027]
### Parent Issue

https://github.com/dotCMS/core/issues/29816

### Task

Makes the changes identified on the Spike https://github.com/dotCMS/core/issues/29816

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

**Comment by fabrizzio-dotCMS** [comment]
Postman test will be covered here https://github.com/dotCMS/core/issues/30186

**Comment by nollymar** [comment]
This change will be tested when we implement the FE integration
