### ISSUE TITLE
Migrate Current Store Service to Signal Store

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30020]
## Parent Issue
#30012 

## Task
Migrate the current store service to Signal Store, maintaining all existing functionalities while preparing for future flexibility and considering component states.

## Proposed Objective
Technical User Experience

## Proposed Priority
Priority 2 - Important

## Acceptance Criteria 
1. Implement Signal Store to replace the current store service
2. Migrate all existing functionalities from the current store to Signal Store
3. Ensure all components currently using the store are updated to use Signal Store
4. Implement state management for component-level states using Signal Store
5. Design the Signal Store structure to be flexible for future additions and modifications
6. Add unit tests to cover all Signal Store functionalities

**Comment by dsilvam** [comment]
Passed IQA: All test cases from the comment working.
