### ISSUE TITLE
Aligment not correct in A/B testing - Edit traffic split

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30045]
### Problem Statement

Alignment is not correct in the Edit traffic split in the Experiments scrren

### Steps to Reproduce

1. Go to any page. 
2. Hit the A/B in the right menu
3. Create an experiment with two variants 
4. Try to edit the traffic split. 
5. See the error. 

https://github.com/user-attachments/assets/b6473a9e-65ab-4b31-af31-c2ac49d8d4f3

### Acceptance Criteria

Should be aligned correctly. 

### dotCMS Version

lastest

### Proposed Objective

User Experience

**Comment by nicobytes** [comment]
IQA passed with **trunk_477606b**

Chrome

![localhost_8080_dotAdmin_ (6)](https://github.com/user-attachments/assets/99f331d1-9e49-486e-b83f-76bd350b39da)

Firefox

![Screen Shot 2024-09-24 at 10 29 54](https://github.com/user-attachments/assets/599f4a7f-2eda-49c2-89f1-1474df22a16a)

Steps to enable Analytics Integration

1. You need to have dotcms running (docker-file with dotcms, elasticsearch and postgresql)
2. Go to `core/docker/docker-compose-examples/analytics/docker-compose.yml` and run that docker-compose.
3. After the docker-compose loads, In dotCMS, go to Settings => Apps => Analytics Integration
4. Fill the fields with this information and save it
```bash
clientId:	analytics-customer-customer1
Secret: testsecret
Analytics Config URL:	http://host.docker.internal:8088/c/customer1/cluster1/keys
Analytics Write URL use:	http://host.docker.internal:8081/api/v1/event
Analytics Read URL use:	http://host.docker.internal:4001/
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b712244**, Docker, macOS 14.5, FF v126.0.1
