### ISSUE TITLE
Create Integration Test for the Analytics "Collectors Layer" 

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30056]
### Parent Issue

- #29712

### User Story

The test are missing for this new layer in the Analytics mechanism, it means create test for these changes: 

- PR: https://github.com/dotCMS/core/pull/29791

### Acceptance Criteria

- Test each of the Collector: AsyncVanitiesCollector, BasicProfileCollector, FilesCollector, PageDetailCollector, PagesCollector, SyncVanitiesCollector

- Test the fireCollectors method

https://github.com/dotCMS/core/pull/29791/files#diff-90a0fa9dfdecdea2c4b6362c0aaea4fdf8a709821647d6f1b3138ede806ecb8dR14

I think we are going to need to get this inner class out for this

https://github.com/dotCMS/core/pull/29791/files#diff-b3262e0c55b89f8f7ebd482593a2c45249e4146e261fd613f72f2ae12a97c0bbR54

- Test this util method

https://github.com/dotCMS/core/pull/29791/files#diff-ae8c16925e0c164cc0aa0342ff2953abb57a46bf69a34437dacf0893521b390eR25

- maybe this this one?

https://github.com/dotCMS/core/pull/29791/files#diff-c6b552720dcdd032d58c9b299fd4c5aba7a5f3b233c6ae1d7a1528e94bfe51c7R75

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by dsilvam** [comment]
Passed IQA: Test executing and passing
