### ISSUE TITLE
Image Field: Drag and drop functionality for image upload

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30059]
### Parent Issue

https://github.com/dotCMS/core/issues/29692

## Task
Develop the drag and drop functionality for file uploads in the enhanced **Image field**. This should allow users to drag files from their local system and drop them into the field for immediate upload.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. Users can drag files from their local system and drop them into the File field
2. Visual feedback is provided when a file is being dragged over the drop area
3. File upload process begins automatically when a file is dropped
4. Error handling for invalid file types or upload failures
5. Progress indicator for file uploads
6. Support for multiple file uploads if dropped simultaneously

## Assumptions & Initiation Needs
- Backend API for file uploads is available and documented
- File type restrictions and size limits are defined

**Comment by nicobytes** [comment]
QA Notes:

Create a new content type with File field.

![Screenshot 2024-09-30 at 1 25 50 PM](https://github.com/user-attachments/assets/cfb19849-0228-42f8-8de6-ba2b232028b0)

Case 1: Upload files as dotAssets by dragging and dropping or clicking the "Choose File" button "ONLY Images"



https://github.com/user-attachments/assets/0145b32e-7416-4426-8743-37fda38f0eac

Case 2: Should display a message when the user tries to drag and drop a non-image.

![Screenshot 2024-09-30 at 1 27 44 PM](https://github.com/user-attachments/assets/b737f3b0-7a10-48e0-bdc5-dddc32d5e576)

Case 3: If the user uses the button, the allowed files should be images.

![Screenshot 2024-09-30 at 1 28 33 PM](https://github.com/user-attachments/assets/c2f97ffc-ae5e-45b1-bdc3-0cd72e0bc4b8)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_324de85**, Docker, macOS 14.5, FF v126.0.1
