### ISSUE TITLE
Overlay Misalignment in Content Type while relating content

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#30053]
### Problem Statement

When clicking the "Relate" button in a content type, the overlay window appears off-center. 
This forces users to manually drag the overlay back to the center. 

In contrast, the overlay is correctly centered in the earlier version (23.01).

### Steps to Reproduce

Steps to Reproduce:

1. Navigate to the "Destination" content type.
2. Click on the "Relate" button at the bottom of the screen.
3. Observe that the overlay window is off-center and needs manual adjustment.
<img width="1701" alt="Screenshot 2024-09-13 at 9 27 54 AM" src="https://github.com/user-attachments/assets/2c671d44-74c2-4fd0-a9b5-ea89118bf243">

https://github.com/user-attachments/assets/6f577977-4e39-4ee0-90fa-3e3fd2dc5e76

### Acceptance Criteria

Expected Behavior: The overlay should be centered on the screen, similar to its behavior in version 23.01.

Actual Behavior: The overlay appears off-center, requiring users to drag it manually.

### dotCMS Version

24.04

24.08.27 (demo)

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://helpdesk.dotcms.com/a/tickets/27542

**Comment by erickgonzalez** [comment]
Working as it should, now the dialog is centered.

![Image](https://github.com/user-attachments/assets/f6fd7959-9362-42f2-bea4-25a025bff02b)

**Comment by bryanboza** [comment]
We need some work here: 

- After this fix, the modal is no longer responsive, causing unnecessary scroll bars and leaving unused blank spaces.

![Image](https://github.com/user-attachments/assets/6dd4a8a7-6178-47fc-afe8-9544a250924d)

**Comment by erickgonzalez** [comment]
We acknowledge that the scrolls and empty spaces have always existed, but their visibility has been compromised since the dialog was repositioned to the right side. We appreciate your understanding as we work to resolve this in the new content editing screen. For this ticket, our primary focus will be on centering the dialog, as this is a matter that impacts our customers significantly. Thank you for your collaboration in addressing these concerns.

**Comment by erickgonzalez** [comment]
Only for 24.04 LTS
