### ISSUE TITLE
Image Field: "Import from URL" functionality

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30061]
## Parent Issue
#29692

## Task
Implement the "Import from URL" feature for **Image Field**, which opens a popup for users to enter a URL and import a file from that location.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
1. An "Import from URL" option is available in the File field
2. Clicking the option opens a popup with a URL input field
3. The system attempts to download and import the file from the provided URL
4. Error handling if the URL is invalid or the file cannot be imported
5. The popup remains open and displays an error message if the import fails
6. Successfully imported files are treated as if they were uploaded directly

## Assumptions & Initiation Needs
- Backend API for importing files from URLs is available
- Security measures for URL validation and file scanning are in place

**Comment by nicobytes** [comment]
QA Notes:

1. Create a new content type with a **Image Field**
2. Create a content based on the previously created content type
3. Click the "Import from URL" button
4. A popup/dialog should show

![Screenshot 2024-10-10 at 10 28 30 AM](https://github.com/user-attachments/assets/2a3b68ea-221a-4f40-93ff-6c78c95e6518)


### Case 1: Upload Images

| Steps   |      Image      |
|----------|:-------------:|
| 1. Put the image URL in the input and import |  ![Screenshot 2024-10-10 at 10 29 34 AM](https://github.com/user-attachments/assets/a67b8954-a12b-424e-a305-4e17eb9365a6) |
| 2. The dialog should close and show the preview. |  ![Screenshot 2024-10-10 at 10 29 41 AM](https://github.com/user-attachments/assets/e20072b1-4b08-4722-86aa-6cba47720a2e) |

### Case 2: Only allow Images

| Steps   |      Image      |
|----------|:-------------:|
| 1. Put the not Image URL in the input and import |   ![Screenshot 2024-10-10 at 10 35 06 AM](https://github.com/user-attachments/assets/496561c9-50cc-46f8-8b4c-4250ae23dc59)  |
 | 2. Should show an error message | ![Screenshot 2024-10-10 at 10 35 55 AM](https://github.com/user-attachments/assets/46a489fe-2755-4746-adaf-e86ad5cee6fb) |

### Case 3: Show error for not valid URLs for Image Fields and File Fields

| Steps   |      Image      |
|----------|:-------------:|
| 1. Put a invalid URL in the input and import |  ![Screenshot 2024-10-10 at 10 39 13 AM](https://github.com/user-attachments/assets/a9bad845-ec35-4996-8e61-1635273160b0) |
 | 2. Should show an error message | ![Screenshot 2024-10-10 at 10 39 21 AM](https://github.com/user-attachments/assets/9c8a254a-c1fe-4cb3-8658-124985eff08f) |

**Comment by dsilvam** [comment]
Passed IQA: All the scenarios above working as expected.
