### ISSUE TITLE
UVE: Improving Template Change Handling to Prevent Page Hangs in Properties Pallet

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#30066]
### Problem Statement

When you change the template in the properties pallet in UVE, the page hangs in the loading state after saving it.

### Steps to Reproduce

1. goto a page in UVE
2. click on the properties tab
3. change the template the page is using
4. save the changes

Results: you are taken back to the edit screen but the loading animation never goes away

### Acceptance Criteria

Page would reload properly

### dotCMS Version

current

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fmontes** [comment]
Here is a repro case:

**Comment by fmontes** [comment]
This could be in the customer code or it could be a wrong abstraction in our SDK, we need to take this as a research issue first. I will give this to either @zJaaal @rjvelazco or @KevinDavilaDotCMS and @valentinogiardino can work with them so he can familiarize with the SDK.

**Comment by fmontes** [comment]
We need to reproduce this in the new dotcms.com, master-qa and local, because it might be something we had wrong in the headless dotcms.com when Jason found it.

**Comment by fmontes** [comment]
As per @fishsmith "Seems to be working"
