### ISSUE TITLE
Image Field: "Select Existing File" functionality

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30060]
### Parent Issue

https://github.com/dotCMS/core/issues/29692

### User Story

As a content editor, I want to select an existing file and have the system display only image files, so that I can quickly find and choose the appropriate image for my content.

### Acceptance Criteria

1. In the File field, there is a "Select Existing File" option.
2. Clicking on this option opens a popup
3. Hosts/Folders should appear on the left side.
4. Navigate through the levels
5. Select a folder/host
6. Only Image Files should be loaded

**Comment by nicobytes** [comment]
QA Notes:

1. Image Field: When the user clicks on the “Select Existing File” option, only image files should be displayed.
2. File Field: When the user clicks on the “Select Existing File” option, all types of content should be displayed.

https://github.com/user-attachments/assets/83c6ce24-015c-4577-af10-5354eb32a11e

**Comment by hmoreras** [comment]
Internal  QA feedback: 
Initial load in image don't filter the files: 

https://github.com/user-attachments/assets/d7e38193-dbcb-4efb-8005-bfe10656ec43

**Comment by hmoreras** [comment]
Pass internal QA:  both fields File and Image, show the files filtered by type.

**Comment by bryanboza** [comment]
Please add to the card the name of the FF that I need to enable in order to see this field..

**Comment by hmoreras** [comment]
> out

  # New Edit Mode
      DOT_CONTENT_EDITOR2_ENABLED: true

**Comment by hmoreras** [comment]
> Please add to the card the name of the feature flag (FF) that needs to be enabled to see this field. It’s important to ensure anyone can take the card and test it without needing to reach out to the developer for additional details.

  ### New Edit Mode
      DOT_CONTENT_EDITOR2_ENABLED: true

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e15f58e**, Docker, macOS 14.5, FF v126.0.1

**Comment by dsilvam** [comment]
Passed IQA:

Showing files living at folder level (not site/host) 
![Image](https://github.com/user-attachments/assets/678b9b01-6acf-4375-94f6-e6cb2170b886)

Showing proper message when no content. 
![Image](https://github.com/user-attachments/assets/ee681164-501c-4296-aaad-82a202b046fc)
