### ISSUE TITLE
Image Field: "Generate with dotAI" functionality

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30062]
### Parent Issue

https://github.com/dotCMS/core/issues/29692

The AI plugin currently supports generative AI in the block editor, including creation of AI-generated images.

We need to duplicate the image generation capabilities of the AI Image block for the standard **Image field** in the content editing screen.

### User Story

As a Content Architect in dotCMS, I want to generate a image with AI in the  Image Field.

![Screenshot 2024-10-14 at 1 56 48 PM](https://github.com/user-attachments/assets/ad69ed1f-0d09-48b1-9f90-3e8eac5f2e47)

![Screenshot 2024-06-17 at 11 19 51 AM](https://github.com/dotCMS/core/assets/7611944/75648ff8-870f-43f8-8b53-3e05095de4f6)

### Acceptance Criteria

- If dotAI is not configured, the options should be disabled, and a mouse-over should have a message something like "Please configure dotAI to enable this feature".
- Like the Block Editor field, once the image is generated and accepted, it just becomes a normal image.  So, dotAI doesn't come into play when the image is edited.

**Comment by nicobytes** [comment]
QA Notes:

This card includes changes in how the AI Prompt dialog for generating images is handled. Therefore, all instances where this dialog is launched should be tested. These cases include:

- Block Editor Field
- Binary Field
- Image Field

Both the Block Editor and Binary Field should function correctly in both the old and new editor content.

### Case 1: New editor content

https://github.com/user-attachments/assets/cbc4bfe5-70c9-45d7-bcc5-9cd65d32491d

### Case 2: Old editor content

https://github.com/user-attachments/assets/f38d9641-4aab-4c58-8b02-f773a3ba2a80

**Comment by hmoreras** [comment]
Pass internal QA

**AI not configured:** 

<img width="765" alt="image" src="https://github.com/user-attachments/assets/4af0f2a6-cb81-422c-8745-e5c3a689e1c6">
<img width="737" alt="image" src="https://github.com/user-attachments/assets/d00cc64c-8b10-485c-8290-4f74e606f12b">

**AI configured:** 

**Block editor in old edit mode working**
<img width="830" alt="image" src="https://github.com/user-attachments/assets/f9637b56-77e2-40dd-96e0-47a289dd65d1">

**Binary old edit mode working**
<img width="834" alt="image" src="https://github.com/user-attachments/assets/b814764f-3c70-491c-b4e9-83da4c080600">


**Block editor new edit mode working**

<img width="719" alt="image" src="https://github.com/user-attachments/assets/d8cdcfba-acd6-4dc1-a22b-c02390f45836">


**Binary new editor working**

<img width="729" alt="image" src="https://github.com/user-attachments/assets/b1941f61-3128-4012-b498-8f1ea289cde3">


**Image new editor working**
<img width="727" alt="image" src="https://github.com/user-attachments/assets/f2b13d25-b403-457c-9295-fbba141c8928">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_11a47ce**, Docker, macOS 14.5, FF v126.0.1
