### ISSUE TITLE
Move telemetry plugin into core

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30079]
### User Story

As a system administrator, I want to be able to access telemetry metrics without having to load a plugin, so I can ensure I have data from new systems without the need for additional work.

### Acceptance Criteria

1. Telemetry metrics are collected and sent on schedule, without the Telemetry plugin loaded.
2. The metrics sent include all those sent via the plugin.
3. No configuration change is required on systems currently sending metrics.
    * The schedule for sending the metrics can be controlled with the same config props as the plugin uses.
4. New metrics can be added as easily in core as in the plugin.
    * Except for unavoidable differences in things like build time.
5. The way to enable the Telemetry feature from core is via the following FF:
```yml
DOT_FEATURE_FLAG_TELEMETRY_CORE_ENABLED: true
```

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### NOTE TO DEVS/AUDITORS
Several classes in the original Telemetry plug-in appeared to contain similar code, but were meant to provide different and expected results. The SonarQube process flagged them as duplicate code, which is not 100% true.

Even though we'll work on refactoring such classes in the near future in order to prevent that, such a task will be carried out in a separate ticket. This is the reason why, this one time only and just for classes under a specific package, the SonarQube analysis on duplicate code will be ignored.

**Comment by jcastro-dotcms** [comment]
# NOTE TO ALL
The default value for the `TELEMETRY_PERSISTENCE_ENDPOINT` configuration parameter has been removed the migrated code altogether. It's very important for the Cloud Engineering Team to take this into consideration when the migrated code is enabled in a given dotCMS instance. They need to set that up for the Telemetry feature to work as expected.

**Comment by dsilvam** [comment]
Passed IQA.

- With feature flag off (default) = using the telemetry system plugin

Endpoint to get the telemetry data working:
![Image](https://github.com/user-attachments/assets/34f34759-054d-4c85-8c12-23fd4db59a3d)

And telemetry job correctly trying to send data to the prod endpoint.

- With feature flag on  (`DOT_FEATURE_FLAG_TELEMETRY_CORE_ENABLED: 'true'`) = using telemetry from core

Endpoint to get the telemetry data working:
![Image](https://github.com/user-attachments/assets/f7226950-0c8b-466d-8c46-0654c975a8b0)

And telemetry job correctly trying to send data to the prod endpoint.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_786c18d**, Docker, macOS 14.5, FF v126.0.1

![Screenshot 2024-11-12 at 9 07 33 AM](https://github.com/user-attachments/assets/3e06b2e8-cec4-49e6-9b37-9cb34edc6c5c)

**Comment by jcastro-dotcms** [comment]
The problem found by @josemejias11 will be addressed in the following ticket:

* #30634
