### ISSUE TITLE
dot-content-types-listing: Use the new Angular Syntax

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30085]
### Parent Issue

https://github.com/dotCMS/core/issues/29797

### Task

Using the `nx g @angular/core:control-flow` command to migrate to the new Angular syntax.

### Why?

The goal is to improve performance and code maintainability.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_477606b**, Docker, macOS 14.5, FF v126.0.1
