### ISSUE TITLE
Analytics: integrate the resource to the new CDI

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#30080]
### User Story

As an user, i want to be able to use CDI into the Analytics

### Acceptance Criteria

CDI should be in place into the analytics stuff

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_839cebb`

The new CDI is working perfectly in the new REST Endpoint and Content Analytics API. Even though this code change cannot be tested visually, you can just set up the Analytics server along with dotCMS and make sure the REST Endpoint described here:

- https://github.com/dotCMS/core/issues/29864

Returns a valid response.
