### ISSUE TITLE
UVE - Make changes to layout you lose container/editable areas

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30116]
### Problem Statement

In edit mode, when you switch the theme, you lose your containers.

### Steps to Reproduce

With the demo site:
1. create new page and use the system template.  Save/Publish.
2. go into edit mode and then click layout.  ~~change the theme to the travel theme.~~ Make any change to the layout.
3. Return to edit mode and you do not see any containers and and unable to edit the page.  It takes a full browser refresh to see the containers.

### Acceptance Criteria

Show container when you switch theme.

### dotCMS Version

24.09.24

**Comment by fmontes** [comment]
I am guessing this is in the traditional mode.

**Comment by bryanboza** [comment]
https://github.com/user-attachments/assets/d930986d-7f1c-4a71-b887-8d63b55ddf42

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last trunk image.
