### ISSUE TITLE
VanityURL redirect applying URL encoding instead of just redirecting.

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#30130]
### Problem Statement

When using 301 or 302 redirects in VanityURLs URL Encoding is being applied. 

For example, when there is a # within the URL, it is changing it to %23 which breaks the redirect. 

### Steps to Reproduce

Create a VanityURL that redirects to a URL with a # within it. In my testing I used the sitemap.xml vanity url on the demo and just set the redirect to a website that contains a # within the URL. 
and this reproduced the issue when trying to go to demo.dotcms.com/sitemap.xml

### Acceptance Criteria

Prevent URL Encoding from being applied to redirects

### dotCMS Version

23.10.24 LTS
24.09.20

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27773

**Comment by erickgonzalez** [comment]
Test this one as well https://github.com/dotCMS/core/issues/28089

**Comment by erickgonzalez** [comment]
It needs work: it's adding a `?` at the end of the redirect, so it isn't working as it should.
![Screenshot 2024-11-13 at 10 39 47 AM](https://github.com/user-attachments/assets/25c319b2-6f6e-4736-b469-9200cbf96382)
![Screenshot 2024-11-13 at 10 40 13 AM](https://github.com/user-attachments/assets/d15b20e2-fe47-402b-83d0-d666abffd06a)

**Comment by gortiz-dotcms** [comment]
**Passed Internal QA**

Works fine now, the redirect doesn't break and the path is correctly shaped


https://github.com/user-attachments/assets/75c08dd2-37be-4ade-a154-0513bc0fd05b

Same with 302

**Comment by bryanboza** [comment]
Fixed, now this is working as expected. Tested on main // docker // FF
