### ISSUE TITLE
SDK: Content API is not returning results when the request have spaces

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#30136]
### Explanation

The `equals` method is using `"` to wrap terms and is not retrieving the expected content due to a wrong parsing on backend side. We should wrap terms in `'` to make it consistent with how the backend works with Lucene Queries

For example: 

```javascript 
client.content.getCollection("Blog").query((qb) => qb.field("title").equals("Universal Visual");
```

That code will send a request with a query that looks like: `+contentType: Blog +live: true +languageId: 1 +Blog.title:\"Universal Visual\"` which will not retrieve the expected content due to the special char `"` we need to use single quotes to avoid this behavior.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- Content API SDK should retrieve the expected content after the changes.

### Assumptions & Initiation Needs

- You understand how the QueryBuilder API works
- You understand how Lucene Query is parsed

**Comment by dcolina** [comment]
## Internal QA: Passed.

It was tested using the docker image `dotcms/dotcms:trunk_324de85` through all the supported browsers (`Chrome, Firefox and Edge`).

The issue couldn't be reproduced anymore.

https://github.com/user-attachments/assets/474a795e-cf91-4d97-8f26-57a2c0d3aa5b
