### ISSUE TITLE
Unable to revoke tokens in dotCMS: API call returning 415 error

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30142]
### Problem Statement

Users are unable to revoke tokens in dotCMS via the API, as the API call to revoke tokens is returning a 415 Unsupported Media Type error. This issue prevents administrators and security teams from effectively managing user sessions and access, leaving tokens potentially active when they should be revoked. This impacts all users and environments where token-based authentication is in use and poses a security risk if tokens cannot be properly revoked.

![image](https://github.com/user-attachments/assets/448e8993-264d-4a8c-86ab-329ec61aabd4)

Log: https://gist.github.com/bryanboza/d820bf57144834122ee9305181999ed9

### Steps to Reproduce

- Log into the dotCMS backend.
- Attempt to revoke a token using the API (e.g., through Postman or a script).
- Observe that the API call fails and returns a 415 Unsupported Media Type error.

### Acceptance Criteria

- Ensure that the token revocation API call works correctly, allowing administrators to revoke tokens without errors.
- The API should handle the request with the correct Content-Type and return a success response (e.g., 200 OK) when a token is revoked.
- Postman Test

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by jdcmsd** [comment]
Seems even after the 415 is solved for revocation, the same problem persists for deleting the inactive tokens. 

Video etc in issue https://github.com/dotCMS/core/issues/30268

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker // FF and now we are able to revoke tokens without problems 
```
dotcms-1         | 20:10:53.342  INFO  util.SecurityLogger - class com.dotcms.auth.providers.jwt.factories.ApiTokenAPI : Revoking token {id:apic16c8c55-2fa3-4559-926c-941304f897d5, userId:dotcms.org.1, issueDate:Mon Oct 07 20:10:48 UTC 2024, expiresDate:Thu Oct 07 06:00:00 UTC 2027, revoked:null, requestingUserId:dotcms.org.1, issuer:93e1a4dc51, allowNetwork:null} -- ip:192.168.65.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
```
