### ISSUE TITLE
Create Notifications for LTS already EOL or upcoming EOL

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#30156]
### Task

We will be implementing a special notification for all users to let them know that 23.01 LTS has reached its EOL. Additionally, we will ensure that our admins receive a 30-day heads-up before EOL, and we will notify all users after EOL when they log in. We hope this helps everyone stay informed and prepared.

Two new properties should be created:
```
##LTS properties to show EOL message
show.lts.eol.message : FF to turn off/on this message
date.lts.eol : date that the LTS is gonna be EOL, expected format MM/dd/yyyy
```

Messages:
```
lts.expired.message = This version of dotCMS already reached EOL. Please contact your CSM to schedule an upgrade.
lts.expires.soon.message = Your dotCMS version will reach EOL in {0} days. Please contact your CSM to schedule an upgrade.
```

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- If EOL date is more than 30 days = don't show any message.
- If EOL date is less than 30 days but more than 0 = show message to Admins.
- If EOL date is less than 0 days = show to everyone the message.
- This feature must be off by default and only activated to LTS versions.

**Comment by erickgonzalez** [comment]
How to test.

Case 1 show to all users, set the following properties:
```
##LTS properties to show EOL message
show.lts.eol.message : true
date.lts.eol : 10/1/2024
```

Login as Admin and also as a limited user, both should get the notification.

Case 2 show to Admins, set the following properties:
```
##LTS properties to show EOL message
show.lts.eol.message : true
date.lts.eol : 11/1/2024
```

Login as Admin and also as a limited user, only Admin user should get the notification.


Case 3 no message since over 30 days to EOL, set the following properties:
```
##LTS properties to show EOL message
show.lts.eol.message : true
date.lts.eol : 12/1/2024
```

Login as Admin and also as a limited user, none should get the notification.

**Comment by gortiz-dotcms** [comment]
**Passed internal QA**

- Case 1 -
Admin and a limited user can see the notification

<img width="981" alt="screenshot1" src="https://github.com/user-attachments/assets/e0c88cef-dd4d-4d5b-87ab-6f6ff87317ce">

- Case 2 -  got notification as Admin 

<img width="438" alt="screenshot" src="https://github.com/user-attachments/assets/5ef59ae8-ff76-45ef-b33b-13c6a6b924bc">

and not as limited user

- Case 3  - didn't get the notification with any of the users

**Comment by josemejias11** [comment]
**Approved**: Tested on **23.01_lts_SNAPSHOT**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-10-23 at 11 02 48 AM](https://github.com/user-attachments/assets/a9708a19-ba56-4b43-bfef-bfd0536965af)
