### ISSUE TITLE
Rafael: Drop Everything & Learn Oct 09 - Oct 22

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30154]

**Comment by rjvelazco** [comment]
### [The Complete Communication Skills Master Class for Life](https://dotcms.udemy.com/course/the-complete-communication-skills-master-class-for-life/)

I’ve continued with the course and completed two activities. One of them was focused on **asking for feedback**.

### 1. Ask for Feedback

Previously, I submitted a video on YouTube as part of this section’s activity. I would appreciate your feedback on the video: [Watch here](https://youtu.be/9w-z0K2-j-I). Specifically, I’m looking for insights on the following:

1. Did you understand the message clearly?
2. Did you grasp the issue I was addressing?
3. How is my body language? Any suggestions for improvement?
4. Did I repeat any gestures or words excessively?

Your feedback would be super helpful—thank you in advance!

### 2. Give feedback to a classmate

I watched this [video](https://www.youtube.com/shorts/wBUe0cXFPko) from another student and gave the following feedback:

> Great video! I really like the tone of your voice and how clearly you express the issue. You did a great job explaining why you took this course and what you hope to gain from it.
> 
> I noticed that you tend to look away for a moment when you’re unsure or change your train of thought. For example, when you said, “does not come naturally to me…”, you looked away briefly before continuing with, “When I started my first job”. Additionally, you can use more connectors to help you to express your ideas

**Comment by nollymar** [comment]
I'll share my feedback in a DM

**Comment by rjvelazco** [comment]
Thank you, @nollymar!
