### ISSUE TITLE
Add a large number of binary image fields to contents

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#30162]
### User Story

As a dotCMS content manager, I want to be able to easily add long lists of embedded objects to my content, so I can relate a large number of contentlets to a piece of content without creating so many separate contentlets in dotCMS.

Here's one hypothetical use case that demonstrates this specific setup:
There's a "person" content type, and we want to track their favorite shirts. This shirt doesn't really belong as a child relationship, each shirt will be specific to a single person and not shared across different people. We want to track a few pieces of data for each shirt, say, shirt name, color, size, and a photo. We would want to be able to add multiple shirts for each user as an embedded content type.

### Acceptance Criteria

Create a new type of field that would allow users to group a set of other fields into an object, and allow users to add an array of these objects as data to the contentlet

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27760

### Quality Assurance Notes & Workarounds

Currently, this can be done with relationships, but this involves creating a separate content type, with a bunch of separate content items.

**Comment by prestonso** [comment]
Thanks @weiyiwang-dotcms! This is accounted for in our coming roadmap item "Multi-Value Binary Fields". @john-thomas-dotcms has more info.
