### ISSUE TITLE
Fixing the two octet-stream Workflow endpoints

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#30167]
### Parent Issue

https://github.com/dotCMS/core/issues/28600

### Task

Five endpoints remained unfinished in the Workflow API doc due to technical hurdles. Two of those five were return octet-stream data, and both would throw 406 errors when called from the API Playground, even with a data payload shown to work in curl. 

This task is to attach a PR that fixes those two.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

`POST /api/v1/workflow/actions/default/fire/{systemAction}` and `PATCH /api/v1/workflow/actions/default/fire/{systemAction}` should both be able to return a 200 response if given a useful payload in the API Playground.

**Comment by valentinogiardino** [comment]
### IQA PASSED

- Tested on latest trunk `trunk_324de85 `- Chrome, Firefox, Edge
- In the API Playground, both endpoints return a 200 response if given a useful payload.

#### Screenshots
`POST /api/v1/workflow/actions/default/fire/{systemAction}`

![image](https://github.com/user-attachments/assets/bad4501a-9822-4115-a01a-343c31159fb2)

`PATCH /api/v1/workflow/actions/default/fire/{systemAction}`

![image](https://github.com/user-attachments/assets/04964e04-8f69-4d63-a58e-8a8727a60360)

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
