### ISSUE TITLE
Fix/Improve some stuff in CA

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30179]
### Parent Issue

#30141

### User Story

We need to fix or improve some point in the Collectors and retrieve data for Content Analytics

- We need to calculate unique page/file request and and total of sessions
- I think we ned some more interesting way to calculate average
- isDetailPage is not working, it tells us that the PAGE_REQUEST is really part of a URL MAP process 
- We need to include  referer and persona fields, we already have the fields in CH but we are sendinf these two in null
- user-agent attribute is not working we are sending the same value all the time no matter witch is the browser used by the user
- We ned to add the pageMode as attribute

### Acceptance Criteria

Fix/improve all

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
Steps to test (both issues together):

- Start dotCMS with the full starter
- Start Analytics to this just: Go to ""/core/docker/docker-compose-examples/analytics"" and run the command "docker-compose up", and wait a couple of minutes, Configure the Analitycs App in dotCMS with the follow parameters:

```
ClientIId: analytics-customer-customer1
Client Secret: testsecret
Analytics Config URL http://localhost:8088/c/customer1/cluster1/keys
Analytics Write URL http://localhost:8081/api/v1/event
Analytics Read URL http://localhost:4001/

```

- Run this script in the CH Database Create 

```
ALTER TABLE events ADD COLUMN object_id String;
ALTER TABLE events ADD COLUMN object_title String;
ALTER TABLE events ADD COLUMN object_content_type_id String;
ALTER TABLE events ADD COLUMN object_content_type_name String;
ALTER TABLE events ADD COLUMN object_content_type_var_name String;
ALTER TABLE events ADD COLUMN object_response String;
ALTER TABLE events ADD COLUMN object_forward_to String;
ALTER TABLE events ADD COLUMN object_detail_page_url String;
ALTER TABLE events ADD COLUMN object_url String;
ALTER TABLE events ADD COLUMN comefromvanityurl bool;
ALTER TABLE events ADD COLUMN request_id String;
ALTER TABLE events ADD COLUMN host String;
ALTER TABLE events ADD COLUMN sessionid String;
ALTER TABLE events ADD COLUMN sessionnew bool;
ALTER TABLE events ADD COLUMN rendermode String;
ALTER TABLE events ADD COLUMN useragent String;

```
- Navigate by the dotCMS FE.
- Start cubsJS UI in "localhost:4001" and play around with it

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: `trunk_54f21fa`

Based on the updated previous comment from @freddyDOTCMS , the following verification criteria were met:

- [X] To retrieve the total number of sessions, you can apply a time filter if needed. Use the 'Total Sessions' measure for this.
- [X] To find how many times a page has been visited (unique visits), use the 'Total Sessions' measure along with the 'pageTitle' and/or 'pageId' dimensions.
- [X] Verify if the isDetailPage attribute is functioning correctly. This attribute should be true when the page being visited is a detail page, which means the URL Map is in use. To test this, visit a URL Map page, then go to CubeJS and retrieve all requests where isDetailPage is true. Ensure you're getting data for the most recently visited page.
- [X] Make a query with referrer as dimensions validate that the values for this field are right, If you don't know witch is the right value check in the Browser network tab and check the referrer header for the request.
- [X] Make a query with persona as dimensions validate that the values for this field are right, make sure that you are making request with different persona. You can change the persona in the index page of the full starter site.
- [X] Make a query with persona as dimensions validate that the values for this field are right. Navigate using different browsers, the value must be different for each Browser, if you don't know which is the right value then check the request user-agent header in the Browser Network tab.
- [X] Visit Pages in the FE and in the BE, then make a query with the count measures and the renderMode dimensions you must get counting for different modes.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e0e83bd**, Docker, macOS 14.5, FF v126.0.1
