### ISSUE TITLE
Weld Container should auto detect any annotated bean 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30187]
### Parent Issue

https://github.com/dotCMS/core/issues/29552

### Task

We have enabled CDI through https://github.com/dotCMS/core/issues/29552 
Currently, we depend on the CDIUtils to create an entry point to instantiate all Annotated Beans 
But we have run into a case that must be supported. Let's say we have a @Inject into a resource 
DotRestApplication must be capable of detecting any annotated bean and taking care of the injection itself 
Therefore we need to iterate over this once again and solve this problem

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Any Resource discovered by DotRestApplication  containing a @Inject must be capable of finding and injecting any Beans annotated with @ApplicationScope

**Comment by fmontes** [comment]
We need to inform #eng on this... maybe the wiki page?
1. Castro will be presenting this
2. It will be in the global demo.
