### ISSUE TITLE
Block editor field is broken when you add more that one in the same content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30197]
### Problem Statement

When using more than one Block Editor field in the same content type in dotCMS, the first instance of the field becomes completely non-functional, while the second instance works as expected. Users are unable to interact with the first Block Editor, and it generates an error in the console. This issue disrupts content creators and developers who rely on multiple Block Editor fields in their content types, limiting their ability to create complex layouts or manage content effectively.

![image](https://github.com/user-attachments/assets/be3ea112-2ed6-47d6-b20a-28d76daaff7b)

### Steps to Reproduce

- Log into the dotCMS backend.
- Create a new content type and add at least two Block Editor fields.
- Save the content type and try to edit it.
- Observe that the first Block Editor field is non-functional, while the second field works normally.
- Check the browser console for errors related to the Block Editor.

### Acceptance Criteria

- Ensure that multiple instances of the Block Editor field in the same content type function correctly.
- Both the first and subsequent Block Editor fields should be fully functional, allowing users to interact with all instances.
- Resolve any console errors related to the Block Editor when multiple instances are used.

### dotCMS Version

Tested on the latest trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
Pass interna QA:  User now can access and modify both editors correctly: 

New editor: 

<img width="862" alt="image" src="https://github.com/user-attachments/assets/48110863-e56f-498c-bbeb-20508481b223">


Legacy editor: 

<img width="983" alt="image" src="https://github.com/user-attachments/assets/08c09c29-662a-4d81-98c6-52a02df689b0">


image: `trunk_8a0ce03`

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_3a6cd47**, Docker, macOS 14.5, FF v126.0.1
