### ISSUE TITLE
Ignore Vector Images in Image API

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30196]
### User Story
As a developer, I want the be able to use the Image API, but occasionally, I need to pass vector images like SVG or EPS, the API should not try to apply transformation to that kind  of images.

### Acceptance Criteria
- The Image API should no longer process vector images like SVG or EPS.
- Only raster images should be processed and returned by the API.
- Image API should log for information purposes

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The development team has the necessary access to update the Image API endpoint.
- Testing will be required to ensure that only raster images are being processed.

### Quality Assurance Notes & Workarounds
- QA team should verify that vector images are indeed being ignored by the Image API.
- If any issues are found during testing, they should be documented and addressed before releasing the feature.

**Comment by zJaaal** [comment]
# IQA Passed 

Now the Image API is Ignoring the Vector images

DotCMS Docker Image: `[dotcms/dotcms:trunk_358e597]`

## Screenshots


https://github.com/user-attachments/assets/eaf40dbc-9e51-44d7-bfe7-47fee2d9fd48

**Comment by nollymar** [comment]
This change only covered changes in the ImageAPI. At UI level, we still need to disable the edition. A new card was created for it https://github.com/dotCMS/core/issues/30271

**Comment by bryanboza** [comment]
Tested on the last trunk // Docker // FF. We are ignoring any kind of image filter on vector images 
https://github.com/user-attachments/assets/d9393384-861f-4f16-9333-b644a925e4b8
