### ISSUE TITLE
Support dateRange in CA queries

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30192]
### Parent Issue

#30141

### Problem Statement

We create a new query sintax for the CA Endpoint and ViewTool, is not really the same CubeJs syntax, let see an example on the filter attribute:

Example to get all the request by day of tis week,

in Cube JS
```

{
  "measures": [
    "request.count"
  ],
  "dimensions": [
    "request.url"
  ],
  "order": {
    "request.count": "desc"
  },
  "timeDimensions": [
    {
      "dimension": "request.createdAt",
      "granularity": "day",
      "dateRange": "This week"
    }
  ]
}
```

In our Syntax is something like:

```

{
  "measures": [
    "request.count"
  ],
  "dimensions": [
    "request.url"
  ],
  "order": {
    "request.count": "desc"
  },
  "timeDimensions": "request.createdAt day This week"
}
```

but right now we are not supporting the third attribute

### Steps to Reproduce

- Start dotCMS with the full starter
- Start Analytics to this just: Go to ""/core/docker/docker-compose-examples/analytics"" and run the command "docker-compose up", and wait a couple of minutes, Configure the Analitycs App in dotCMS with the follow parameters:
-
```
ClientIId: analytics-customer-customer1
Client Secret: testsecret
Analytics Config URL http://localhost:8088/c/customer1/cluster1/keys
Analytics Write URL http://localhost:8081/api/v1/event
Analytics Read URL http://localhost:4001/
```
- Navigate in the dotCMS FE to generate data
- GO to the Velocity playground and run this code

```

#set ($queryMap = {"measures" : ["request.count"], 
                "orders": "request.createdAt desc",
                "dimensions" : ["request.whatAmI"],
                "timeDimensions": "request.createdAt day Today"
                })

#set($collection = $analytics.runReportFromMap($queryMap).getResults())

Requests Per Day

#foreach($item in $collection)
   -> Type: $item.get("request.whatAmI").get()
   -> Create Date: $item.get("request.createdAt").get()
   -> Count: $item.get("request.count").get()
   
#end


```

You are going to get nothing

### Acceptance Criteria

The dateRange parameters in the timeDimensions must work

### dotCMS Version

latest

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed IQA: Simplified syntax for timeDimensions working as described.

![Image](https://github.com/user-attachments/assets/62430329-a0de-4a19-b78b-81169b41f8d2)
![Image](https://github.com/user-attachments/assets/f57350bf-9060-4b50-9e9c-4dcac7e843ad)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_72dacf7**, Docker, macOS 14.5, FF v126.0.1
