### ISSUE TITLE
dotDataException visiting pages from front end

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30195]
### Problem Statement

A dotDataException is being triggered when navigating to pages from the front end of a fresh dotCMS instance. While the exception is currently only generating noise in the logs and does not appear to break any functionality, it should be investigated to prevent potential future issues. This error occurs when navigating to the home page or other pages from the front end. The issue needs to be addressed to ensure a clean and error-free experience when viewing pages from the front end.

LOG: https://gist.github.com/dsilvam/7d65bbdcad433202b0bcda37af0b5de5 

### Steps to Reproduce

- Start a fresh instance of dotCMS.
- Navigate to the front end of the site (e.g., visit the home page).
- Observe the logs for any dotDataException messages.

### Acceptance Criteria

- Investigate and resolve the cause of the dotDataException triggered on the front end.
- Ensure that the error does not appear when navigating pages from the front end.
- Logs should be free of unnecessary errors or noise during normal front-end navigation.

### dotCMS Version

Tested in the last trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
This is already fixed per @wezell.
