### ISSUE TITLE
Allow dotCLI to push very large files

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#30206]
### User Story

As a user, I may need to move files larger than 50 mb from a workstation to an instance. Whereas we're looking for dotCLI to eventually take on all of WebDAV's old duties, that should ultimately include the management of files of arbitrary size.

### Acceptance Criteria

Remove the 50 mb limit on dotCLI file transfers, and allow the command line to move files up to the maximum size the system itself can allow.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

Current errors received when attempting to push large files:

```
[ERROR] ❗  Error pushing asset [/test2g] 
 RESTEASY005081: File limit of 50MB has been reached. The entity cannot be processed. Increase the size with the configuration property dev.resteasy.entity.file.threshold.
[ERROR] ❗  Error pushing asset [/test5g] 
 RESTEASY005081: File limit of 50MB has been reached. The entity cannot be processed. Increase the size with the configuration property dev.resteasy.entity.file.threshold.
[ERROR] ❗  Error pushing asset [/test10g] 
 RESTEASY005081: File limit of 50MB has been reached. The entity cannot be processed. Increase the size with the configuration property dev.resteasy.entity.file.threshold.
```

Quarkus's `dev.resteasy.entity.file.threshold` is at the heart of this, but @fabrizzio-dotCMS and I were not able to find a quick and easy workaround at the level of local variables.

**Comment by wezell** [comment]
Oof, I did not know we had a 50mb limit.  Def needs to change.

**Comment by valentinogiardino** [comment]
@jdcmsd I tested this by setting the `dev.resteasy.entity.file.threshold` property to -1 in `tools/dotcms-cli/api-data-model/src/main/resources/application.properties`, which effectively removes the file size limit for RESTEasy's handling of multipart entities. Here’s the configuration:
```
# Removes the file size limit for RESTEasy multipart data. -1 disables the limit, allowing file uploads of any size.
dev.resteasy.entity.file.threshold=-1
```
Docs [here](https://docs.jboss.org/resteasy/docs/6.2.9.Final/userguide/#_entity_part:~:text=dev.resteasy.entity.file.threshold).

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by bryanboza** [comment]
IQA on this is enough
