### ISSUE TITLE
Select Existing File: Show host/folder on the left

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30215]
## Parent Issue
https://github.com/dotCMS/core/issues/29873

## Task
Show Hosts/Folders on the left panel in the Select Existing File Dialog for File Fields.

## Proposed Objective
User Experience

## Proposed Priority
Same as Parent Issue

## Acceptance Criteria
 
1. In the File field, there is a "Select Existing File" option.
2. Clicking on this option opens a popup
3. Hosts/Folders should appear on the left side.
4. Navigate through the levels

## Screenshot

The UI should be similar to the Dojo dialog.

![Screenshot 2024-10-02 at 12 00 38 PM](https://github.com/user-attachments/assets/ca259d56-e1e4-4c76-9b33-1abe85ebc983)

https://primeng.org/tree

**Comment by nicobytes** [comment]
QA Notes:


https://github.com/user-attachments/assets/56370a81-b204-456e-85c2-7d7dc9f26a57

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `trunk_7a5f044`

The new File Dialog shows up as described in [Nicolas' comment](https://github.com/dotCMS/core/issues/30215#issuecomment-2459945327). Remember to enable the new Edit Mode for your test Content Type.

# IMPORTANT:
This PR is meant to:
1. Display the new File Dialog.
2. Allow the user to list and expand the Sites and their folders.

Displaying the actual contents of such folders was not part of the ticket's scope. It'll be taken care of in another ticket.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4548b16**, Docker, macOS 14.5, FF v126.0.1
