### ISSUE TITLE
Display Toast Message on Contentlet Save 

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30212]
## Parent Issue
#30012

## User Story
As a content editor, I want to see a toast notification when a content let is saved or encounters an error, so I can quickly understand the outcome of my action.

## Acceptance Criteria
- A success toast message is displayed when a content let is successfully saved
- The toast messages use the PrimeNG Toast component
- Success messages should be green and disappear after 3 seconds

![image](https://github.com/user-attachments/assets/127c6bf6-9c16-42f3-85bf-62635a15684b)

## Proposed Objective
- [x] User Experience

## Proposed Priority
- [x] Priority 2 - Important

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

## Assumptions & Initiation Needs
- PrimeNG is already integrated into the project
- The content let saving mechanism is already in place

**Comment by jdotcms** [comment]
I wonder if you do not need also a toast when the content is properly (the workflow) executed in the backend

**Comment by hmoreras** [comment]
Note to QA: 

Add a toast when a workflow is executed. 

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/71165ed7-364b-49e6-8ac1-77bff65c4758">

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED ❌
* Docker Image: `trunk_786c18d`

The toast notification is only showing up when clicking the `Publish` button, but not the `Save` button.

#### Steps to Reproduce:
1. Create a test Content Type with a single `Title` field, and activate the new Edit Mode for it.
2. Create a new Contentlet of such a type, and click `Save`.
3. You will not get the toast.
4. Click the `Publish` button, and you'll see the toast this time.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_396487e**, Docker, macOS 14.5, FF v126.0.1
