### ISSUE TITLE
Can't edit content in variants

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30221]
### Problem Statement

On our authoring server, we can create experiments and create variants, but when editing the variants, we can't add new content to the container.

It also appears that deleting content isn't working properly.  Although my initial attempt to delete existing content appeared to work, when I deleted the second piece of content in the page, both pieces of content reappeared.

### Steps to Reproduce

1. Log into auth.
2. Navigate to the /testing folder
3. Open the "experiments" page
4. In the page editor, open the Experiments screen
5. In the Experiments list, Create a new experiment
6. In the experiment config:
    * Create a new variant
    * Edit the variant
7. In the page editor:
    * Delete the second contentlet on the page (the blog)
    * Attempt to add a new blog to the page
        * You can try this either via the "+" button or via drag-and-drop from the palette
**Result:** The added content does not display in the page.

Note that leaving the editor and re-editing the variant doesn't cause the new blog to show.  BUT if you try to drag the same blog twice, the visual indicator changes, which indicates that the new blog may be added in some way that's just not visible.

### Acceptance Criteria

* Must be able to perform all the following operations on variants, and see the operations work in real time:
    * Delete content from a container
    * Add new content to a container
    * Edit content in a container

### dotCMS Version

Current (latest running on auth)

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Could not reproduce: Imported a bundle that includes the same page (and dependencies) that was used to test on auth to my local environment. Went through the steps described above and was able to add content to the variant.

**Comment by bryanboza** [comment]
According to @dsilvam comment he tested directly in auth server and it works as expected, we can pass this one for now.
