### ISSUE TITLE
Add support for Language Variables in Rich Text (WYSIWYG) Fields

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30222]
### User Story

As a content editor, I want to be able to use Language Variables in Rich Text (WYSIWYG) fields, so I can create dynamic, multilingual content more efficiently.

### Acceptance Criteria

- Rich Text (WYSIWYG) fields support the insertion of Language Variables
- Language Variables are properly rendered when viewing content in different languages
- The WYSIWYG editor provides an intuitive interface for selecting and inserting Language Variables
- Language Variables in Rich Text fields are correctly processed when content is published

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/user-attachments/assets/197005f3-a5d9-4197-9e5d-880428295173

Final Design
![Image](https://github.com/user-attachments/assets/58471ccc-7310-4ceb-854e-4790086d24b3)

Endpoints
```
GET {{serverURL}}/api/v2/languages/variables
```
Response
```
{
    "entity": {
        "total": 1,
        "variables": {
            "title": {
                "en-us": {
                    "identifier": "3b52d52b0b3559c95ed64d61121aaeff",
                    "value": "title"
                },
                "es-es": {
                    "identifier": "3b52d52b0b3559c95ed64d61121aaeff",
                    "value": "título"
                }
            }
        }
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

**Comment by dsilvam** [comment]
IQA: Needs work

We need to be able to see the entire name because under scenarios like this the user can't tell which option is which
![Image](https://github.com/user-attachments/assets/9d7e7f85-0832-440f-975f-6b0cafbc5d82)

**Comment by oidacra** [comment]
Fixed the loading in the autocomplete too.

**Comment by dsilvam** [comment]
Passed IQA: Reported issues working as expected. 

1. Showing the last part of the language variable so we can identify them. 

![Image](https://github.com/user-attachments/assets/7d437d8d-aaa2-4043-851f-9570804952d1)

2. Inserting the variable in the editor as expected

![Image](https://github.com/user-attachments/assets/f6e9a6ab-ae07-4e9c-b4d4-f3f018c43796)

3. Rendering the variable as expected 

![Image](https://github.com/user-attachments/assets/b8adc1a8-e6df-4a34-8642-10a0d9c95f2d)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_56e5870**, Docker, macOS 14.5, FF v126.0.1
