### ISSUE TITLE
Implement Final UI for General and Workflow Components in Edit Contentlet Sidebar

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30220]
## Parent
#30017 

## Task
Apply the final design as defined in the Figma file to the General and Workflow components displayed in the Edit Contentlet sidebar.

## Proposed Objective
- [x] User Experience

## Proposed Priority
- [x] Priority 2 - Important

## Acceptance Criteria
- The General component in the Edit Contentlet sidebar matches the Figma design specifications
- The Workflow component in the Edit Contentlet sidebar matches the Figma design specifications
- The layout and spacing of elements within each component adhere to the Figma specifications
- Any animations or transitions specified in the Figma file are implemented
- The updated UI is consistent with the overall design language of the application

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
**General Component**
![image](https://github.com/user-attachments/assets/50d27f23-a2db-46c5-a768-d64b34e6b40f)

**Workflow Component**
![image](https://github.com/user-attachments/assets/664f1a5f-e7a6-4181-a10d-f6a572831318)

## Assumptions & Initiation Needs
- The Figma design for the General and Workflow components is finalized and approved
- The basic functionality of the General and Workflow components is already implemented
- Access to the necessary design assets (icons, fonts, etc.) is available

## Quality Assurance Notes & Workarounds
- Test the UI implementation on various browsers (Chrome, Firefox, Safari, Edge) to ensure consistency
- Verify that the new UI doesn't break any existing functionality
- Check that the components maintain their design integrity with different amounts of content
- Ensure that all interactive elements (hover states, focus states, etc.) are implemented as per the design

**Comment by oidacra** [comment]
### Notes to IQA/QA

# Acceptance Criteria: Sidebar Information and Workflow Components

## Sidebar Layout and Components
* Final design must be implemented for Information and Workflow components in the sidebar
* Sidebar open/close buttons must be functional

## Information Section
* Implement copy functionality for shortID
* Display content type information
* Include JSON content link (API URL)
* Show dates in human-readable format:
  * Created date
  * Modified date
  * Published date
* Display reference count to pages using this contentlet
* All modified values (dates, names) must show original values in tooltips
* Copy button and JSON link must show tooltips

## Workflow Section
* Display current workflow name
* Show current workflow step
* Display assigned user

## Loading States
* Implement skeleton loading states for all components
* Loading states must work correctly when testing with throttled network speed

## Technical Requirements
* All tooltips must show accurate original values
* Copy functionality must work as expected
* JSON link must be valid and functional
* Dates must use proper time-ago format

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4548b16**, Docker, macOS 14.5, FF v126.0.1
