### ISSUE TITLE
CA search: Display a "wall" if the analytics app is not running

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30233]
### Parent Issue

#30178

### User Story

As a user, I need to see a clear warning message when the Analytics app is not properly configured, so that I understand why analytics data is not being displayed and what actions I need to take.

### Acceptance Criteria

1. Implement a wall message display that appears when, Analytics configuration is missing and Configuration parameters are invalid. 

### Proposed Objective

Error Handling Implementation

### Proposed Priority

Priority 2 - Important

### External Links

- Figma Design: https://www.figma.com/design/FWCtr1mgQwzdvAGVOM9jDc/Content-Analytics?node-id=54-188&t=ON2d5uTJrFC48hnz-1

### Assumptions & Initiation Needs

- The development environment is ready for updating the Content Analytics portlet.

### Quality Assurance Notes & Workarounds

- Ensure no performance degradation due to new styles or components.

### Sub-Tasks & Estimates

*No response*

**Comment by hmoreras** [comment]
QA note: 

Add the Analytics Search portlet: 

<img width="701" alt="image" src="https://github.com/user-attachments/assets/a568fbdf-1821-4893-b0e0-196c91056f41">

See the different walls: example: 

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/122d8186-4848-46a2-8c07-8880f6f2b8aa">

**Comment by dsilvam** [comment]
Wall working as expected under the two scenarios described: 

1. No license: 

![Image](https://github.com/user-attachments/assets/62857d4b-f1bf-4bbd-b9a9-0d168081547b)

2. Analytics app not configured:

![Image](https://github.com/user-attachments/assets/28ab26d1-fc59-4591-bb72-b56b8b643fee)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4271248**, Docker, macOS 14.5, FF v126.0.1
