### ISSUE TITLE
Migrate `plugin-seeds` Repos from Gradle Build Files to Maven POM Files

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#30234]
### User Story
As a dev-ops engineer, I want to migrate the workflow in charge of updating the dotCMS core version in every `plugin-seeds` repo project from Gradle-based build files to Maven POM files. For this, adjust the Python script to set the current dotCMS core Maven dependency in every POM file found in the `plugin-seeds` repo.

### Acceptance Criteria
- A Python script is created or adjusted to handle the replacement of dotCMS core Maven dependencies in every POM file within the `plugin-seeds` repository.
- The script identifies all POM files in the `plugin-seeds` repos and successfully updates the dotCMS core version.
- The migration from Gradle to Maven is documented and tested.
- Ensure no breaking changes are introduced during the migration.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links
_To be defined (Slack conversations, support tickets, etc.)_

### Assumptions & Initiation Needs
- All `plugin-seeds` repositories are available for migration.
- Gradle files can be completely replaced by Maven POM files.
- The dotCMS core dependency version is accessible via a standardized source.

### Quality Assurance Notes & Workarounds
- Test both new and existing plugins to ensure the updated POM files work seamlessly with dotCMS core.
- Validate script accuracy by running it in a test environment before applying changes to all repositories.

### Sub-Tasks & Estimates
- [ ] Adjust the Python script to modify POM files (3 hours)
- [ ] Test the migration on a sample `plugin-seeds` repo (5 hours)

**Comment by bryanboza** [comment]
Fixed, seems now this is working and we are able to fire the job manually without problems. We will work to integrate on the release job in this card: https://github.com/dotCMS/core/issues/30273
