### ISSUE TITLE
Error adding new content when no lang param is send

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#30237]
### Problem Statement

When working in the LTSs, it has been noted that there is an issue when attempting to add new content during page edits if the language_id param is not present.
![Screenshot 2024-10-03 at 10 17 49 AM](https://github.com/user-attachments/assets/a61fcaff-68c9-4437-8aa2-a27179db7c77)

This doesn't happens in main branch since we're always adding the `language_id` param if is not present.

### Steps to Reproduce

1- Go to edit any page
2- Remove the `language_id` param from the url.
3- Try to add a new content (any type of content)
4- Get the error

https://github.com/user-attachments/assets/d12ee113-32da-46d3-a04f-d654c4f5e8e4

### Acceptance Criteria

Always add the language_id param if it is not present.

### dotCMS Version

LTSs: 23.01, 23.10 and 24.04.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27780
https://dotcms.freshdesk.com/a/tickets/27948

**Comment by hmoreras** [comment]
The QA process will be made by the support team due is a LTS issue. 

@erickgonzalez

**Comment by erickgonzalez** [comment]
It's working as it should now in the 24.04 LTS version. Thanks @hmoreras
