### ISSUE TITLE
CA search: Implement Search form and results.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30231]
### Parent Issue

#30178

### User Story
As a user, I want to implement a search form and results display for the Content Analytics portlet, where the input is a Monaco editor that accepts JSON queries, waits for the response, and displays the results in a read-only Monaco editor.

### Acceptance Criteria

- Implement a Monaco editor as the input for users to enter JSON queries.
- Ensure the editor can validate and format JSON correctly.
- Send the JSON query to the backend and wait for the response.
- Display the results in a read-only Monaco editor once the response is received.

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs

- The backend endpoint is available to process JSON queries and return results.
- Analytics infrastructure should be working in the environment.

### Quality Assurance Notes & Workarounds

- Add the portlet to  the menu to have access.

**Comment by hmoreras** [comment]
Note to QA: this is the initial step of the portlet, validations, error handling, loading state, and match the updated design wll be worked in a new card. Eventually the epic will be sent to QA to test the feature complete.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker image: `trunk_b5017f1`

The `Analytics Search` portlet is working fine. You need to manually add it to your main nav menu.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_56e5870**, Docker, macOS 14.5, FF v126.0.1
