### ISSUE TITLE
Drag & Drop workflow subactions broken

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30236]
### Parent Issue

Related to: https://github.com/dotCMS/core/issues/29207

### Problem Statement

The work done in  https://github.com/dotCMS/core/issues/29207 broke the ability to drag and drop workflow actionlets. 

See https://github.com/dotCMS/core/issues/29207#issuecomment-2389632775

https://github.com/user-attachments/assets/5f0939ba-ec43-4025-9f16-fea8780def9b

### Steps to Reproduce

https://github.com/user-attachments/assets/5f0939ba-ec43-4025-9f16-fea8780def9b

### Acceptance Criteria

Drag and drop working as before

### dotCMS Version

trunk_ec4a905

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Ability to drag and drop to sort the actionlets is restored.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a12617a**, Docker, macOS 14.5, FF v126.0.1
