### ISSUE TITLE
Autocomplete doesn't work properly

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30249]
### Problem Statement

Autocomplete doesn't work properly in template section.

https://github.com/user-attachments/assets/8c7a209f-a800-41e4-afd7-51e2ea16aca1

### Steps to Reproduce

1. Go to the Templates section
2. Select a template
3. Click the Edit Classes button
4. Show Suggest Option

### Acceptance Criteria

Working as documented

https://www.dotcms.com/docs/latest/designing-a-template-with-a-theme#ClassSuggestions

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_298ce7a**, Docker, macOS 14.5, FF v126.0.1


![Screenshot 2024-10-14 at 1 00 04 PM](https://github.com/user-attachments/assets/df887921-0d3e-4ecd-8600-ec90e3914cfc)
