### ISSUE TITLE
The button in the WYSIWYG modal field has a problem

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30248]
### Problem Statement

The button in the WYSIWYG modal field has a problem

![image (2)](https://github.com/user-attachments/assets/33e82f61-a473-4f6d-88c0-617d974514e4)

### Steps to Reproduce

1. Create a new content type
2. Add a WYSIWYG field
3. Edit the WYSIWYG field
4. When the modal is open, the button has a wrong color.

### Acceptance Criteria

Show the button with the correct color

### dotCMS Version

lastest

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

**Comment by oidacra** [comment]
Closed in favor of https://github.com/dotCMS/core/issues/27341
