### ISSUE TITLE
Increase the font size of PLAIN view of the WYSIWYG field. 

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30254]
### Problem Statement

With the recent font size changes the code view of the WYSIWYG is too small, put it back as it was before. 

### Steps to Reproduce

1. Go to Content Types
2. Create a content type with a WYSIWYG field. 
3. Create a content - switch the view to `PLAIN`.
4. See the small font size. 
<img width="824" alt="image" src="https://github.com/user-attachments/assets/b8c7e153-9cca-4128-a5cc-db4a06a42529">

### Acceptance Criteria

Should be equivalent to 12px as it was before the font update

### dotCMS Version

lastest

### Proposed Objective

User Experience

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e5e00cb**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-10-10 at 9 58 12 AM](https://github.com/user-attachments/assets/1e959e1c-4814-46ae-91ad-5d4a96f0406a)
