### ISSUE TITLE
Update NgRx Signal Store, Component Store, and Operators versions to match current Angular version

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30255]
### Task

Update the versions of NgRx Signal Store, Component Store, and Operators to ensure compatibility with the current Angular version used in the project (Angular 18). This task is necessary to maintain consistency and leverage the latest features and improvements in the NgRx ecosystem.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
**Warning running yarn**
![CleanShot 2024-10-04 at 15 17 04@2x](https://github.com/user-attachments/assets/c1d6824c-c940-4b64-8c91-0ff35f94765b)

### Quality Assurance Notes & Workarounds

- Go to the branch
- Generate a local docker image
- Test The functionalities of:
- - Pages
- - Templates
- - AI Content Prompt
- - Edit Content (Angular)
- - Binary Field (Angular)
- - Category Field
- - File Field
- - Experiments Configurator/List/Reports
- - Locales
- - Ema Dialog
- - EMA Palette
- - Favorites
- - SEO Tools
- - Dot Asset Search

**Comment by josemejias11** [comment]
**QA Comment**

Tested on branch **issue-30255-upgrade-ngrx** on local Docker 1.0.0-SNAPSHOT
