### ISSUE TITLE
Remove Verdaccio as a dependency of Nx

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30252]
### Task

Remove Verdaccio as a dependency of Nx without affecting other tasks or functionalities. This involves identifying all instances where Verdaccio is used within the Nx setup, removing the dependency, and ensuring that all other tasks and processes continue to function correctly after the removal.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

**Comment by josemejias11** [comment]
**Approved**:
