### ISSUE TITLE
Unable to delete API tokens via UI

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#30268]
### Problem Statement

It is not currently possible to delete an API token through the "delete" link in the user interface. Tokens can be revoked, but the DELETE method call fails with a 415 Unsupported Media Type error. 

This does not seem to be a problem with the endpoint itself, as the same token can be deleted via the API Playground. (See the video for a demonstration.)

### Steps to Reproduce

1. Boot up a dotCMS instance and sign in
2. Create an API token via System -> Users -> {User} -> Api Access Tokens
3. Revoke the token you just created, and note the successful call to the `PUT /api/v1/apitoken/{tokenId}/revoke` endpoint
4. Check the Show Inactive box in the upper-right corner
5. Find the inactive token you just created at the bottom of the list
6. Click the delete link, and note the unsuccessful call to the `DELETE /api/v1/apitoken/{tokenId}` endpoint
    - Expected error: 415 Unsupported Media Type
7. Now copy the token ID from the left column, and paste it into the parameter field of that same endpoint on the API Playground, and click Execute
8. Token deletes successfully.

https://github.com/user-attachments/assets/9a8da8f8-9092-4886-99c3-c8bd02b0d7b0

### Acceptance Criteria

API token deletion should succeed through the user interface.

### dotCMS Version

Latest trunk

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

**Comment by jdcmsd** [comment]
I didn't notice until I was drafting this, but this is probably due to the same problem as this one https://github.com/dotCMS/core/issues/30142

**Comment by jdcmsd** [comment]
After some testing, and one extra commit, the PR for the IQA checks on the API Token API will also fix this problem. Props to @valentinogiardino for identifying the cause!

**Comment by valentinogiardino** [comment]
### IQA PASSED
Tested on `trunk_0028f3c`
Now users can delete API tokens via UI

#### Video
https://github.com/user-attachments/assets/db9a1e4e-f928-4df7-8f9d-8e783f883f7c

**Comment by bryanboza** [comment]
Something is happening here, please retest this since I tried with the same docker images mentioned in the comment above, and I;'m still unable to delete the token. 

https://github.com/user-attachments/assets/a5eab0d6-495e-4281-999c-a22eb1d795b7

**Comment by valentinogiardino** [comment]
> Something is happening here, please retest this since I tried with the same docker images mentioned in the comment above, and I;'m still unable to delete the token.
> 
> Tested with trunk [trunk_0028f3c]
> 
>  Screen.Recording.2024-10-07.at.3.59.29.PM.mov

I am sorry, my bad. I pasted the wrong docker image. Was tested successfully on `dotcms/dotcms:trunk_7d5223d`

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker // FF 

`dotcms-1         | 18:58:31.257  INFO  util.SecurityLogger - class com.dotcms.auth.providers.jwt.factories.ApiTokenAPI : deleting token api0c4bda76-a0de-49e2-affd-3d1fa7fcd8bf -- ip:192.168.65.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]`
