### ISSUE TITLE
dot-toolbar: Use the new Angular Syntax

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30263]
### Parent Issue

https://github.com/dotCMS/core/issues/29797

### Task

Using the `nx g @angular/core:control-flow` command to migrate to the new Angular syntax.

### Why?

The goal is to improve performance and code maintainability.

### Proposed Objective

Application Performance

### Proposed Priority

Priority 4 - Trivial

**Comment by nicobytes** [comment]
QA Notes:

Check the toolbar functions

https://github.com/user-attachments/assets/8fb00ab9-2bca-453f-9d12-df66703eabef

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_72dacf7**, Docker, macOS 14.5, FF v126.0.1
