### ISSUE TITLE
Automate CLI Version Update for Agile Releases

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30276]
### Task

Automatically update the CLI version of the JAR file located in the workflow file [main.yml](https://github.com/dotCMS/core/blob/main/tools/dotcms-cli/action/.github/workflows/main.yml#L18) after each agile release is generated. The update should ensure that the version specified in the file reflects the latest agile release.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The CLI version in the workflow file should be automatically updated to the latest agile release version without manual intervention.

**Comment by nollymar** [comment]
**Internal QA:** passed

The cli runner is now obtained dynamically :)

**Comment by bryanboza** [comment]
Fixed, now this is working as expected.
