### ISSUE TITLE
Clean up the unique_fields table

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30285]
### Parent Issue

* #29459

### User Story

When a Contentlet with a Unique Field, a Unique Field itself, or a Content Type that contains a Unique Field is deleted, we need to clean up the `unique_fields` table. Here's what to do in each case:

* **Case 1: Deleting a Contentlet with a Unique Field**: Look for the record containing this Contentlet by checking the `contentletIds` property in the `supporting_values` JSON field. If the list contains multiple Contentlets, the specific Contentlet must be removed from the list. If it contains the Contentlet you created, the entire record is deleted.
* **Case 2: Deleting a Unique Field**: Using the field variable attribute in the `supporting_values` JSON field, all records containing such a field must be deleted.
* **Case 3: Deleting a Content Type with at least one Unique Field**: All records having that Content Type ID in the `supporting_values` JSON field must be deleted.

We also need to implement several API/Factory methods to handle these cases.

### Acceptance Criteria

Clean up the `unique_fields` table.

### Steps to Reproduce

* In your `docker-compose.yml` file, set the following env var:
```yml
DOT_ FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION: 'true'
```
* Start dotCMS with the Full Starter.
* **THIS IS NOT NECESSARY ANYMORE!** ~At this point, the Upgrade Task that creates the `unique_fields` table is not automatically, so you need to call the class directly. You can use Postman for that:~
```
URL: /v1/upgradetask
Method POST
Body: {
"upgradeTaskClass": "com.dotmarketing.startup.runonce.Task241007CreateUniqueFieldsTable"
}
```
* Log into the PostgreSQL database and verify that (1) the table is there and (2) it has records in it. For the Full Starter, it should be 236 records total.
* Create a Content Type named `My CT` with a single field:
  * Text field `Title`, marked as `Show in List` and  `Unique`.

#### Case 1
* Create a Contentlet of such a type with this value: `my value`.
* Create another Contentlet with the very same value. You must get the following error message:

<img width="328" alt="Screenshot 2024-12-04 at 10 31 39 AM" src="https://github.com/user-attachments/assets/e26b2c19-260b-4312-90e8-1607d492546d">

* Getting the total count of records in the `unique_fields` table must be 237 now, as we just created a Contentlet.
* Delete such a Contentlet and get the table's total count again. It must go down to 236 again.

#### Case 2
* Update the `My CT` to have one more text field named `Description`, required, but NOT unique.
* Create 3 Contentlets of such a type, with different unique values.
* Check the table's total record count. It must be 239.
* Go to the the `My CT` and delete the unique `Title` field. The table's total record count must go down to 236 again.

#### Case 3
* Re-add the `Title` field and, once again, go to the `Content Search` to the unique values for the 3 records again. and set its values for the unique fields again Check the table's total record count. It must be 239 again.
* Go back to the `Content Types` portlet and delete the `My CT`. This will delete all Contentlets from such a type as well.
* After that, the table's total record count must go down to 236 again.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
Note to QA:

Test this again https://github.com/dotCMS/core/issues/30279#issuecomment-2448317463

but now if you delete a Contentlet and try to create aanother one with the same unique value used in the deleted one must works.

Also test all the cases when the extra table should be cleaning up:
- Delete Contentlet
- Unpublish Contentlet
- Delete Content Type with Unique fields
- Delete Unique FIeld
- DO a REMOVE PUSH with a Contentlet

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED ❌
* Docker Image: `trunk_3b866d6`

I found two error scenarios related to the Unique Field validation:

#### Scenario # 1
* Create a test `My CT` just like described in the `Steps to Reproduce` section.
* Go to the `Search` portlet and create a Contentlet with the unique field `111`.
* Open it up again, and change it to `222`.
* Once again, go back and change it to `111`.
* You'll get the error message indicating that the value `111` is being used by more than one Contentlet, which is wrong.

#### Scenario # 2
* Create two more Contentlets with these unique values:
  * `333`
  * `444`
* Go to the `Content Types` portlet, and delete the `My CT` altogether.
* Re-create `My CT` exactly as it was, with the same names for everything.
* Go to the `Search` portlet, and create a Contentlet with unique value `222`.
* You'll get an error indicating that the value `222` is being used by more than one Contentlet, which is wrong.

Both scenarios are happening because the `unique_fields` table is not being cleaned up after:

1. Updating the unique field's value.
2. Deleting the Content Type.

**Comment by freddyDOTCMS** [comment]
Another case to test:

- In your docker-compose.yml file, set the following env var:

DOT_ FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION: 'true'

- Start dotCMS with the Full Starter.
- Create a Content Type named My CT with a couple of fields:

Text field title
Text field unique, mark it as unique

- Create a Contentlet with: Title: A, unique: 111, Save and publish it
- Edit the same Contentlet change the title to 'A2', should save it without error
- Try to create another Contentlet with the unique value equals to '111', must faiil

**Comment by freddyDOTCMS** [comment]
Noto to QA: 

Now you don't need to execute the TaskUpgrade manually, make sure that you don't have the unique_fields table already created from a previous QA

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_b40d2e6`

The error scenarios [described here](https://github.com/dotCMS/core/issues/30285#issuecomment-2518044128) are no longer reproducible. Updating unique values following such steps are not throwing any errors.
