### ISSUE TITLE
graphql endpoint fails pre-flight checks

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30298]
### Problem Statement

When we try to use the graphql endpoint from browser js, it throws a 400 on the OPTIONS method and thus fails the pre-flight checks.  You can see it failing here: https://www.dotcms.com/playgrounds/graphql/

```
Access to fetch at 'https://demo.dotcms.com/api/v1/graphql' from origin 'https://www.dotcms.com/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

### Steps to Reproduce

Open your network tab try this page - it is failing:

https://www.dotcms.com/playgrounds/graphql/

### Acceptance Criteria

head to this site:
https://studio.apollographql.com/sandbox/explorer/?referrer=docs-content

and point the explorer to your local instance, e.g. https://local.dotcms.site:8443/api/v1/graphql

and make sure the graphql calls are working

### dotCMS Version

24.09

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment]
## Internal QA: Passed.

The issue couldn't be reproduced anymore. It was tested using the docker imagen `dotcms/dotcms:trunk_9a1866f`.

https://github.com/user-attachments/assets/26729f9f-98b8-43ec-9bb4-db19867fdce5

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
