### ISSUE TITLE
Upgrade task to include the new Locales portlet in favor of the old Languages one

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30296]
### Task

This task consists in including an upgrade task to do the following: 
1. Insert the new Locales portlet in all the tool groups where the Languages portlet exist. 
2. Remove the Languages portlet from all the tool groups it belong to.

For the implementation of this UT the [Task240530AddDotAIPortletToLayout](https://github.com/dotCMS/core/blob/main/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task240530AddDotAIPortletToLayout.java#L19) is a good one to look at. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

After the Upgrade Tasks runs, the new state of the system needs to be: 
* Locales portlet available on all the tool groups where Languages was available. 
* Languages portlet not present in any tool group. 
* Existing languages shown correctly on the new portlet.

**Comment by john-thomas-dotcms** [comment]
One addition (yes, scope creep):

When we add the new Locales portlet to a tool group, we need to also add a Custom content search portlet named "Language Variables" which shows only the Language Variable content type.
![Image](https://github.com/user-attachments/assets/8b7b3993-29b4-4741-847f-f28040bf9308)

**Comment by jcastro-dotcms** [comment]
The addition of the custom `Language Variables` portlet will be addressed in the following ticket:

* #30351

**Comment by dsilvam** [comment]
Passed Internal QA: The Locales portlet is now available by default and the old Languages one is hidden.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b295876_SNAPSHOT**, Docker, macOS 14.5, FF v126.0.1


![Screenshot 2024-10-18 at 12 06 17 PM](https://github.com/user-attachments/assets/83190bf2-0a23-4ed9-936c-30404745d6e6)
