### ISSUE TITLE
Analytics: System Error - Unknown Clickhouse Default Value for Bool

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#30302]
### Problem Statement

There are repeated occurrences of the following error in the logs

```shell
[ERROR]: System error: Unknown clickhouse default value for Bool
``` 

### Steps to Reproduce

1. Execute a query that interacts with the Clickhouse database using the jitsu component.
2. Observe the logs for the error: [ERROR]: System error: Unknown clickhouse default value for Bool.
3. The error occurs repeatedly, hindering the execution and completion of the query.

### Acceptance Criteria

Queries should execute without errors, and any default boolean values in Clickhouse should be handled correctly.

### dotCMS Version

24.10.08

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### Quality Assurance Notes & Workarounds

<img width="857" alt="Screenshot 2024-10-08 at 4 05 39 PM" src="https://github.com/user-attachments/assets/70587431-8563-40bb-9eea-51a06e2f1779">

**Comment by dsilvam** [comment]
Passed IQA: Not seeing the error anymore when both registering events or fetching data from cube

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e5e00cb**, Docker, macOS 14.5, FF v126.0.1
