### ISSUE TITLE
Enable Unique Field DataBase validation 

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30306]
### Parent Issue

#29459

### User Story

This new validation is going to be disabled until all the issue related are done, so we need to do some stuff:

- Enabled to use this approach as DEFAULT.
- Add the TaskUpgrade created here #30275 to the TaskLocatorUtil and renamed according with the current date.
- Update the postgres.sql file
- Check if we ned to index the supporting_values column.

### Acceptance Criteria

Enabled this approach to be the DEFAULT one.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Let's test this one as part of the IQA https://github.com/dotcms/core/issues/29352

**Comment by freddyDOTCMS** [comment]
We are going to work all this here #30815
