### ISSUE TITLE
Include a Feature Flag for the old Languages portlet

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30300]
### Task

This feature flag will behave like this: 
* If *on* (by default, in code), old Languages portlet gets hidden from the list of portlets you can add to a tool group.
If *off* then the old Languages portlet is available to be added to a tool group - but that's all (The new Locales portlet is neither hidden nor removed from any tool groups).

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

* Go to the `Settings > Roles & Tools` portlet, look up the `CMS Administrator` Role, and click it.
* Click the `TOOLS` tab, and click any of the available `Tool Groups` in the table.
* In the `Tools` dropdown, look for the `Languages` portlet or type in the word. The portlet **MUST NOT BE THERE**.
* Shut down dotCMS, and switch the FF off:
```yml
DOT_FEATURE_FLAG_LOCALES_HIDE-OLD-LANGUAGES-PORTLET: false
```
* Refresh the browser's tab to re-load the portlet, and look for the `Languages` portlet again. The portlet **MUST BE THERE THIS TIME**.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_be08096**, Docker, macOS 14.5, FF v126.0.1

Switching of the Portlets will be work on card https://github.com/dotCMS/core/issues/30296
