### ISSUE TITLE
Cursor Misalignment When Typing in Velocity Dev Tool

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#30310]
### Problem Statement

When typing code into the Velocity Developer Tool, the cursor does not align with the text being typed.

### Steps to Reproduce

1. Open the Velocity Developer Tool.
2. Begin typing any code or script.
3. Observe the cursor’s position in relation to the text being typed.
4. Notice that the cursor does not follow the text correctly and stays misaligned.

### Acceptance Criteria

The cursor should follow the text as you type, maintaining proper alignment and position relative to the code entered.

### dotCMS Version

24.10.08

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

https://github.com/user-attachments/assets/daaa2bcb-2371-40b3-abd7-aac5fdbcd440

**Comment by Neehakethi** [comment]
https://helpdesk.dotcms.com/a/tickets/28379

**Comment by prestonso** [comment]
This has now been fixed per @wezell. Thanks @Neehakethi!
