### ISSUE TITLE
Create upgrade task for the Postgres Job Queue implementation

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#30315]
### Parent Issue

https://github.com/dotCMS/core/issues/29479

### Task

We need to create an upgrade task for thePostgres Job Queue Implementation tables. This task involves the creation of new tables and indexes to manage job queues, job details, and job history in the database.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
It looks good to me.

**Comment by bryanboza** [comment]
Fixed, now. I'm able to use the endpoint after upgrade from previous versions without any problem

Tested upgrading from 23.10_LTS to main
