### ISSUE TITLE
Image properties cannot be edited in Block Editor (Firefox)

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#30327]
### Problem Statement

- properties of images (alt, path, caption) in the block editor cannot be edited in Firefox
- I tested on demo.dotcms.com also and got the same behavior
- Chrome works fine

### Steps to Reproduce

- open dotcms instance in Firefox
- go to a contentlet containing a block editor field (like a Blog - French Polynesia Everything You Need to Know)
- click on the image properties
- try to edit Path, Alt or Caption

### Acceptance Criteria

- the image properties should be editable in Firefox also;

### dotCMS Version

- 24.04.24 LTS
- demo (24.10.09)

### Proposed Objective

Reliability

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- there is a video showing the behavior here https://dotcms.freshdesk.com/a/tickets/28012

**Comment by gortiz-dotcms** [comment]
### **Passed internal QA**

<img width="1281" alt="Captura de pantalla 2025-01-02 a la(s) 9 46 54 a  m" src="https://github.com/user-attachments/assets/9223ca02-c7d2-47a2-a3d3-9213ade1d6e1" />

The properties now are editable in firefox
