### ISSUE TITLE
All requests create a session

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30321]
Regression.

Requests for all assets create a session unnecessarily.  

Run this:

```
curl --head https://demo.dotcms.com/dA/4694d40bd9be/image/320maxh/diving.jpg
```

And you can see the headers include a **JSESSIONID** cookie which means a session has been created.
```
set-cookie: JSESSIONID=745C39F2CACB95B2EC1A01DA4024F0F6; Path=/; Secure; HttpOnly; SameSite=Lax
```
This regression is caused by the variant code. Bottom line, I don't think we need to create a session if there is no specific variable requested, e.g. variable = "DEFAULT".

You can test this by dropping a breakpoint in the `SessionMonitor.sessionCreated` method.

### Acceptance Criteria

This is a regression and it has happened a few times over dotCMS's lifetime.  We need a postman test to make sure we don't create sessions if they are not needed.

Dupe: #7433

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Work as expected now is not creating a Session each time you request a Image

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_be08096**, Docker, macOS 14.5, FF v126.0.1
