### ISSUE TITLE
Job Queue: Negative Timeout Value Causes Error in logs

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#30348]
### Task

The application encountered an error with the message `java.lang.IllegalArgumentException: timeout value is negative.` This error occurs because the code attempts to use a negative value for a timeout, which is not allowed.

The problem is due an overflow issue in the exponential backoff calculation, where the value became too large to handle, causing it to wrap around to a negative number.

### Steps to Reproduce:  

1. Run the job queue manager for a long period of time .
2. Observe the error in the logs.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
After having executed the LargeReadFile Processor for a long time I couldn't reproduce the issue.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the last trunk docker image
