### ISSUE TITLE
[Locales] : Create UT to add a custom Language Variables portlet

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#30351]
### Parent Issue

* #30296

### Task

As part of adding the new `Locales` portlet to the main menu in the dotCMS backend, we need to add a custom `Language Variables` portlet so that Users can perform CRUD operations on them.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The new `Language Variables` portlet must show up under the same menu group that the `Search` portlet lives in.

### Quality Assurance Notes & Workarounds

The following ticket:

- #30296

Must be tested before proceeding with this one.

#### Steps to Reproduce:

* Start dotCMS with a Docker image that **DOES NOT have this fix**, so that you can simulate a real upgrade process.
* Then, start up dotCMS with the appropriate Docker image.
* Look for the menu group that has the `Search` portlet -- usually called `Content`.
* The custom `Language Variables` portlet must be there.

**Comment by dsilvam** [comment]
Passed IQA: Custom language variables portlet shown after upgrading. 

![Image](https://github.com/user-attachments/assets/171b34c3-e38d-44bf-b791-708aa961eda3)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0bae3dc**, Docker, macOS 14.5, FF v126.0.1
