### ISSUE TITLE
Enable users to record user-defined events

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30369]
### User Story

As a developer, I want to be able to track custom-defined events, based on actions users take on the front-end and/or back-end of my site.

### Acceptance Criteria

* Users can trigger the recording of a new analytics event by hitting an API endpoint.
    * At a minimum, the user should be able to specify the type of event and the type of object (e.g. WhatAmI).
* User-defined events can be queried using analytics queries, via both the existing analytics API and the existing analytics viewtool.
    * Ideally, the same methods should work to query both user-defined and pre-defined analytics events.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
TBD if the user needs a role to fire the event
TBD if the user id should be part of the event information

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED
- Image: `trunk_b5017f1`

The event is not making it into the Clickhouse DB.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Image: `trunk_b5017f1`

The new endpoint is working as expected. The reason why the event was not making it into the Clickhouse DB was because of a problem with the Analytics App configuration, which was not being reported at all. This improvement will be reported in another ticket.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_f2fab7c**, Docker, macOS 14.5, FF v126.0.1
