### ISSUE TITLE
[Locales] : Update the portlet Feature Flag in AUTH and PROD instances when code changes are in

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#30363]
### Parent Issue

* #30300

### Task

Once the latest changes made to the Locales feature are in, we need to flip the switch in the AUTH and PROD instances to disable/enable the option to add the old Languages portlet to the main menu bar. The env var is:
```yml
DOT_FEATURE_FLAG_LOCALES_HIDE_OLD_LANGUAGES_PORTLET: true
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Let's make sure the upgrade tasks ran on Auth/Prod
