### ISSUE TITLE
Enhance Stream Chat to Stream Data in Chunks Based on HTTP Status Evaluation

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#30361]
### Problem Statement

`dotAI`'s "Stream Chat" since it currently waits until it gets all the contents instead of sending chunks of data as one would expect in a streaming mode. This happens because, in order to apply an OpenAI model fallback strategy, we wait for the contents to be evaluated to determine what kind of error happened.

### Steps to Reproduce

- Set the dotAI application correctly
- Go to `Dev Tools`->`dotAI`
- Select the `Stream Chat` option
- Type a question
- Response is displayed not chunk by chunk but as a whole

### Acceptance Criteria

- The system streams data as chunks once the HTTP status code is evaluated as 2xx.
- The fallback strategy remains intact and continues to handle error cases as intended.
- Testing covers all potential scenarios of 2xx HTTP status codes and proper streaming of bytes.
- No regression in existing fallback mechanisms.

### dotCMS Version

24.10.09

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/user-attachments/assets/074f5363-986f-4ec2-9b9a-3f84782fc22c

_No response_

**Comment by victoralfaro-dotcms** [comment]
QA Notes:
- Configure dotAI App
- Go to `Dev Tools`->`dotAI` and select the `Manage Embeddings/Indexes` tab
- Set the `Content to Index by Query:` field to something like `+contentType:Blog`, build the index and wait until it finishes 
-Select the `Search and Chat with dotCMS` tab and select the `Streaming Chat         - OpenAI + dotCMS Supporting Content` option
- Provide a prompt like `How is the waves in Tahiti?` and it `Submit` button
- In the results area, response should be displayed in chunk-by-chunk fashion (like it's being typed), not everything at once

**Comment by dsilvam** [comment]
Failed IQA: The dotAI portlet is throwing `java.lang.StackOverflowError` on `trunk_f2fab7c`

**Comment by dsilvam** [comment]
Passed IQA: dotAI Streaming working again

https://www.loom.com/share/b6989ad5acce4e0cb4bc2e8d5c118651?sid=8306cce3-6f81-4cf6-90b5-4b71a0aab3b8

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_cad5532**, Docker, macOS 14.5, FF v126.0.1

https://github.com/user-attachments/assets/c2728057-d94a-4499-9f4b-7889f54f3ae7
