### ISSUE TITLE
Add Activity Creation Functionality to Activities Sidebar Component

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30379]
## Parent Issue
#30017 

## User Story
As a user, I want to be able to add new activities directly from the Activities component in the sidebar, so I can quickly create and track my tasks without navigating away from my current view.

## Acceptance Criteria
- A prominent "Add Activity" button is visible within the Activities sidebar component
- Clicking the "Add Activity" button opens a textarea for creating a new activity (see the video)
- Users can submit the form to create a new activity
- The newly created activity appears immediately in the Activities list without requiring a page refresh
- The form includes proper validation to ensure all required fields are filled before submission
- A success message is displayed after successfully adding an activity
- The UI is consistent with the overall design of the dotCMS interface

## Proposed Objective
- Core Features

## Proposed Priority
- Priority 2 - Important

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/user-attachments/assets/4bf708c0-e457-4236-b38a-23ec21082aae

## Assumptions & Initiation Needs
- The existing Activities component in the sidebar is fully functional
- Backend API endpoints for creating activities are already in place 
- Access to the design system or UI kit to ensure consistency with existing components

## Quality Assurance Notes & Workarounds
- Test the feature across different browsers and devices to ensure compatibility
- Verify that the new functionality doesn't interfere with existing sidebar features
- Check for proper error handling when network issues occur during activity creation

**Comment by jcastro-dotcms** [comment]
This ticket is the duplicate of the official one:
* https://github.com/dotCMS/core/issues/30513

Moving this one to `Done`.
