### ISSUE TITLE
[Locales] : Remove hyphens from Feature Flag name

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#30387]
### Parent Issue

* #30300

### Problem Statement

The hyphens present in the Feature Flag used for showing/hiding the old `Languages` portlet:
```
FEATURE_FLAG_LOCALES_HIDE-OLD-LANGUAGES-PORTLET
```
Are not working correctly when setting this as an env var. The hyphens must be replaced with underscores.

### Steps to Reproduce

* Start dotCMS with the latest Docker image.
* Set the FF in `false`, like this:
```yml
DOT_FEATURE_FLAG_LOCALES_HIDE-OLD-LANGUAGES-PORTLET: 'false'
```
* Go to the `Roles & Tools` portlet. You'll see that the 'Languages` portlet is still not showing up.

### Acceptance Criteria

Setting the FF to `false` must display the `Languages` portlet in the dropdown. The corrected FF name is:
```
DOT_FEATURE_FLAG_LOCALES_HIDE_OLD_LANGUAGES_PORTLET
```

### dotCMS Version

Latest from main

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed IQA: Now the feature flag is working as intended.

Off - Languages portlet present and able to be selected:

![Image](https://github.com/user-attachments/assets/efd9b68a-6ed5-44e9-82f7-233e2ab246b6)

On (default) - Languages portlet not present in the dropdown of tools:

![Image](https://github.com/user-attachments/assets/b074107f-18b0-4f9a-bdaf-75b38865ac01)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0bae3dc**, Docker, macOS 14.5, FF v126.0.1
