### ISSUE TITLE
Dev Tools - Velocity. Cursor has odd behavior when editing.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30393]
# GitHub Issue Template

### Problem Statement
In the dev tool's Velocity section, when editing Velocity code, the cursor is exhibiting odd behavior due to font size differences. This inconsistency in cursor movement and positioning is affecting the user experience and making code editing less efficient and more error-prone.

### Steps to Reproduce
1. Open the dotCMS admin panel
2. Navigate to the dev tools - Velocity  section
5. Start typing or editing the Velocity code
6. Observe the cursor movement as you type.

https://github.com/user-attachments/assets/40288a1b-45e3-4d94-bef2-58381d27bd60

### Acceptance Criteria
- Cursor positioning should be accurate and predictable when moving up, down, left, or right
- The visual feedback of cursor location should align perfectly with where text will be insert

### dotCMS Version
latest

### Proposed Objective
User Experience

### Additional Notes
- This issue may be related to the text rendering or the code editor component used in the Velocity section

**Comment by hmoreras** [comment]
QA note:  cursor editor working correctly: 

https://github.com/user-attachments/assets/bf5d7564-8ea9-479f-9f96-b35afcaf47ca

velocity used. 
`#foreach($con in $dotcontent.pull("+contentType:Activity +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +variant:default",10,"modDate desc"))
$con.title
#end`

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fd26189**, Docker, macOS 14.5, FF v126.0.1
