### ISSUE TITLE
Click on a locale in the new Locales portlet doesn't to anything

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30395]
### Problem Statement

The standard behavior for all portlets in dotCMS is that a single-click on an item in a list takes a default action on that item.  In the Locales portlet, clicking on a Locale in the list currently does nothing; you need to go click on the hamburger menu on the right to edit it.

We need to change it so a single-click on a Locale in the list opens the edit popup for that Locale.

### Steps to Reproduce

1. Open the Locales portlet.
2. Click on any Locale in the list.
Result: Nothing happens.

### Acceptance Criteria

* Click on a Locale in the list opens the edit popup for the clicked Locale.
* Changes made in the edit popup are saved without issues.

### dotCMS Version

Trunk

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by hmoreras** [comment]
video for QA: 

https://github.com/user-attachments/assets/2ef16df8-7fa6-47e8-a04b-139d83567a58

**Comment by dsilvam** [comment]
Passed IQA: Clicking on a locale now shows the edit locale dialog:

![Image](https://github.com/user-attachments/assets/f077acbb-ae94-4544-a808-515c9e282aa5)
