### ISSUE TITLE
Clean Test Errors in Locales Portlet

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30394]
### Problem Statement
There are warnings appearing in the test run for this portlet, which need to be addressed to ensure proper functionality and maintain code quality.

### Steps to Reproduce

For the test warnings:
1. Run the test suite for the Locales portlet, `nx run portlets-dot-locales-portlet:test`
2. Observe the console output or test report
3. Note the warnings that appear during the test run https://gist.github.com/hmoreras/aedfd95812fbd26f901423d5e9048bcb

### Acceptance Criteria
. Test Warnings:
   - All warnings in the test run for the Locales portlet should be resolved

### dotCMS Version
latest

### Proposed Objective
User Experience and Code Quality

**Comment by hmoreras** [comment]
QA note: Errors for this project are gone: 

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/2c016045-7e94-4ef5-b697-6aa6efb26fd5">

**Comment by oidacra** [comment]
IQA, no more warnings when you run the project.
