### ISSUE TITLE
Use new Angular Syntax in DotNavigationComponent

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30401]
### Parent Issue
https://github.com/dotCMS/core/issues/29797

### Task

Use new Angular Syntax in `DotNavigationComponent`. The goal is to improve performance and code maintainability.

![Frame 12](https://github.com/user-attachments/assets/b6ed07d1-fa56-4c7b-b5aa-57afbf8087b4)

### Proposed Objective

Application Performance

### Proposed Priority

Priority 4 - Trivial

### Acceptance Criteria

1. Navigate through the side menu.
2. All routes and links should work properly.

**Comment by nicobytes** [comment]
QA Notes:

1. Navigate through the side menu.
2. All routes and links should work properly.


https://github.com/user-attachments/assets/3258e389-a370-4796-90db-acbad6534fd1

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_fd26189**, Docker, macOS 14.5, FF v126.0.1
