### ISSUE TITLE
We have inconsistency between the 2 Endpoint to retrieve CA data

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30412]
### Problem Statement

Right now we have 2 Endpoint to retrive the CA data:

'/v1/analytics/content/_query': support dotCMS query syntax
'/v1/analytics/content/_query/cube': support raw CubeJS syntax

Both are POSt and receive the query in the body, but :

The first one receive the query wrap like this:

```

{
    "query": {
        "filters": "request.urlMapContentTypeName = ['Blog']",
        "dimensions": ["request.urlMapContentDetailId", "request.urlMapContentDetailTitle"],
        "orders": "request.totalSessions desc",
        "measures": ["request.totalSessions"]
    }
}
```
The second one just receive the query, I mean like this:
```

{
  "filters": [
    {
      "member": "request.urlMapContentTypeName",
      "operator": "equals",
      "values": [
        "Blog"
      ]
    }
  ],
  "dimensions": [
    "request.urlMapContentDetailId",
    "request.urlMapContentDetailTitle"
  ],
  "order": {
    "request.totalSessions": "desc"
  },
  "measures": [
    "request.totalSessions"
  ]
}
```

remenber the second Endpoint receive a raw query

### Steps to Reproduce

Try to use the 2 Endpoint using Postman

### Acceptance Criteria

The Input for the 2 Endpoint must have the same format

### dotCMS Version

latest

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
We will have multiple endpoints with different parameters (query-based vs. parameter-based). As long as the response is identical from all query endpoints, there is no inconsistency to worry about.
