### ISSUE TITLE
Match the CA attribute with the Elaticsearch attribute

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30411]
### Problem Statement

Right now the CA attribute are totally different from what we used in ES, for example, the Contentlet's ID is saved as "identifier" , we used: contentId, also we have others fields that have the same value like : pageId, fileId, vanityId, the only different is that this attribute are NULL when is not the right type on Contentlet, for example pageId is NULL is the COntentlet is a Image.

Also we are not saving some values that we need like the ContentType variable Name, or the Base Content Type, the list of attribute that we want to match with ES are:

**Attribute that already exists in CA but we need to rename:**

- contentId - > identifier
- contenTitle -> title
- urlMapContentTypeVarName -> contentType 
- renderMode -> turn into to boolean live and working
- language -> languageId 
-  host -> conHost
-  vanityForwardTo -> fowardTo
- vanityResponse -> action
- urlMapWasHit and wasVanityHit -> Join in just one attribute that tell if Vanity or URL MAP was used

**We need to removed some attribute too like:**

- isDetailPage
- urlMapContentDetailId
- urlMapContentDetailTitle
- urlMapContentId
- urlMapContentTypeName
- urlMapContentTypeVarName

Also we need to include some attribute that we are not collecting right now:

- baseType
- Path

### Steps to Reproduce

Start Analytics generate some CA data
Go to CubeJS Server and check the field names 

### Acceptance Criteria

We need to rename, removed and create the fields describe before 

### dotCMS Version

latest

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
This is a refactoring of the keys to try to get close of elastic keys.
it wont be testable until get the issue to make the changes on clickhouse and elastic, but we are gonna merge without QA needed

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_e32a4d3`

Existing variable names are now matching what was described in the ticket. As @jdotcms said, another ticket will be created to match the same changes in the ClickHouse schema.
