### ISSUE TITLE
Need support date a specific date range in our Query sintax

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30410]
### Problem Statement

CubeJS Query allow to set a specific range of date like in this query:
```

{
  "measures": [
    "request.count"
  ],
  "dimensions": [
    "request.contentletId",
    "request.contentletTitle",
    "request.whatAmI",
    "request.url"
  ],
  "order": {
    "request.count": "desc"
  },
  "timeDimensions": [
    {
      "dimension": "request.createdAt",
      "granularity": "day",
      "dateRange": [
        "2024-10-07T06:00:00",
        "2024-10-20T05:59:59.999"
      ]
    }
  ]
}

```

right now we are supporting friendly range date like 'last month' but not a specific range date, the reasons is because they are translate to CubeJs in a complete different way, a friendly range is tranlate like:
```

  "timeDimensions": [
    {
      "dimension": "request.createdAt",
      "granularity": "second",
      "dateRange": "This month"
    }
  ],
```

Also the dateRange and granularity are optional we can have just one of them, but in our sintax you need to include both together when you include one you need to include the other one as well so we need to make then optional even when one of then is set.

### Steps to Reproduce

Try to run a query using the '/v1/analytics/content/_query' Endpoint using a specific range of dates

### Acceptance Criteria

Must support this kind of range of date

### dotCMS Version

latest

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
We're not going to support the custom query format long-term, so we don't need to implement this.
