### ISSUE TITLE
CA Search: Apply updated Design

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30427]
### Parent Issue

#30178

### User Story

As a developer, I want to implement the UI updates for the Content Analytics portlet, following the design team's specifications in the provided Figma file, so that the UI is consistent with the new design.

### Acceptance Criteria

1. Update the **layout and styling** of the Content Analytics portlet according to the Figma design.
2. Ensure that the **fonts, colors, and spacing** match the Figma file.
3. Implement any new **UI components or interactions** specified in the design.

### Proposed Objective

UI/UX Improvements

### Proposed Priority

Priority 2 - Important

### External Links

- Figma Design: https://www.figma.com/design/FWCtr1mgQwzdvAGVOM9jDc/Content-Analytics?node-id=54-188&t=ON2d5uTJrFC48hnz-1

### Assumptions & Initiation Needs

- The Figma file contains all required design assets and specifications.
- The development environment is ready for updating the Content Analytics portlet.

### Quality Assurance Notes & Workarounds

- Ensure no performance degradation due to new styles or components.

### Sub-Tasks & Estimates

*No response*

**Comment by hmoreras** [comment]
QA Note: 

The design updates include the use of `p-splitter` and validation of json format before send the request. 

<img width="1301" alt="image" src="https://github.com/user-attachments/assets/c62ce545-4ddb-417e-9643-e4e1434db905">

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/edb41833-aebf-471f-aba9-cea22c9c7d0e">

Details that we are aware: 

- Help button still pending will be worked in other card. 
- Dropdown to support both queries not needed. for now only the `CUBE` query will be supported. 

Example of Cube Query used: 

`{
  "dimensions": [
    "request.whatAmI",
    "request.url"
  ],
  "order": {
    "request.count": "desc"
  },
  "measures": [
    "request.count"
  ],
  "timeDimensions": [
    {
      "dimension": "request.createdAt"
    }
  ],
  "filters": [
    {
      "member": "request.url",
      "operator": "equals",
      "values": [
        "/"
      ]
    },
    {
      "member": "request.whatAmI",
      "operator": "equals",
      "values": [
        "PAGE"
      ]
    }
  ]
}`

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/30487

**Comment by dsilvam** [comment]
IQA: Needs a bit of work.

Main functionality working as expected but found small issues on the Dialog when Analytics is not configured: 

* Change the title for maybe "Analytics App not configured" 
* Fix the word wrapping of the message in the Dialog.

![Image](https://github.com/user-attachments/assets/56325bc0-f9ce-424d-995f-124994f097cf)

**Comment by john-thomas-dotcms** [comment]
Suggested title: `Analytics is Not Configured`

**Comment by hmoreras** [comment]
configration errores are being worked in other card, we wil use a "wall" https://github.com/dotCMS/core/issues/30233

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_7408571**, Docker, macOS 14.5, FF v126.0.1
