### ISSUE TITLE
Retrieve Analytics data in a simple and flexible way

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30439]
### User Story

We need to accomplish two tasks:

- Create a Widget Content Type that allows data retrieval from CA using the following parameters: measure, dimensions, filters, sorting, and time dimensions.

- Create a Custom Field to implement a dropdown menu that offers the following options: "Last week", "Last month", and "Forever". Based on the selected option, dynamically retrieve the number of hits for the chosen time period.

### Acceptance Criteria

Implemented this 2 thing

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by mboutillette-personal** [comment]
Hi Freddy, CS team is asking what release this will be in (after seeing it in the sprint demo), do we know yet what release this will be in?  Thanks
