### ISSUE TITLE
SDK: Unable to Edit Unpublished Page in Angular Example

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30440]
### Problem Statement
When attempting to edit an unpublished page in the Angular example, a 404 error occurs in the UVE. This functionality works in NextJS but needs to be tested in Astro.

### Steps to Reproduce
1. Run the Angular example with a read-only token
2. Set the dotCMS UVE app
3. Create a new page and don't hit "Publish" but just save (or unpublish any exiting page)
4. Try to edit the page in UVE, see the 404

```[tasklist]
### Acceptance Criteria
- [x] All pages, whether published or unpublished, should be editable in the UVE.
- [x] Make sure this works in NextJS
- [x] Make sure this works in Astro
```

### External Links
- Reporter by DSS partner

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
# Note to QA 

You can generate a read only token by giving just access to the front end. Image for reference:

![image](https://github.com/user-attachments/assets/7cc945c2-29d3-421b-b94b-b5f77926aff2)

**Comment by zJaaal** [comment]
## IQA Failed 

DotCMS Docker Image: `[dotcms/dotcms:trunk_c0a01e6]`

We have an issue on the Angular example. we are not showing the Footer and Header for the page:
<img width="1512" alt="Screenshot 2024-10-31 at 6 14 57 PM" src="https://github.com/user-attachments/assets/204578f0-dbe7-4b74-8fe0-8098432d2ac0">

## Astro (Working as expected)

https://github.com/user-attachments/assets/82560240-9b8d-40c0-887e-d509ababa9aa

## NextJS (Working as expected)

https://github.com/user-attachments/assets/e85c5fe6-3d4f-4ec9-9af5-e19a2bbe836a

**Comment by zJaaal** [comment]
## IQA Passed

Now it works as expected 

DotCMS Docker Image: `[dotcms/dotcms:trunk_7408571]`

### Screenshot

https://github.com/user-attachments/assets/dbbec34b-6351-4aab-bb00-df31730b822d

**Comment by bryanboza** [comment]
https://github.com/user-attachments/assets/f95329b3-607f-49bf-b97e-00b6d6b06e65

Fixed, tested on main and now this is working as expected
