### ISSUE TITLE
Content Analytics: Distinguish the source of stored events

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30443]
### User Story

As a developer, I want to be able to distinguish among events fired by the dotCMS code, API calls, workflow actionlets, and Rules actionlets, so I can:
1. Perform queries that distinguish between events generated by dotCMS, headless apps, and user-defined config (workflows and rules).
2. Troubleshoot when events are either being fired or not being fired as expected.

### Acceptance Criteria

* A new Event Source field in each event identifies the source of the event.
    * This field contains one of an enumerated list of values.
    * For example DOTCMS, API, WORKFLOW, and RULE.
* A new Event Source Detail field in each event provides additional details about the source of the event.
    * For example, the collector name (for DOTCMS), the endpoint URL (for API0, the Workflow action ID, or the Rule ID

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
the core part is done, but the changes on clickhouse and so are not, @freddyDOTCMS will take care later

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED ❌
* Docker Image: `trunk_913c82b`

 When debugging the source from both Docker and the source code, the new expected `event_source` attribute is not making it to the Payload object.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_68612b9`

Content Analytics events include what dotCMS system triggered them now. A new column named `event_source` lets you know what feature created the event:

* The `DOT_CMS` event source indicates that the event was created by dotCMS in general; i.e.; accessing the object form the front-end or the back-end.
* The `REST_API` event source indicates that the event was created via the REST Endpoint. You can test it by creating an `/index` page, and calling this CURL command:
```curl
curl -u admin@dotcms.com:admin --location 'http://localhost:8080/api/v1/analytics/content/event' \
--header 'Content-Type: application/json' \
--data '{
    "event_type":"PAGE_REQUEST",
    "url":"/index",
    "screen_resolution":"1280x720"
}'
```
* The `WORKFLOW` event source indicates that the event was created when running a Workflow Action on a Contentlet. You can set the Workflow Action like this:

<img width="1392" alt="Screenshot 2024-11-23 at 12 30 52 PM" src="https://github.com/user-attachments/assets/1be3adc4-d7b0-472d-b7b7-eafe82faba97">

* The `RULE` event source indicates that the event was created by a Rule. You can set it up like this:

<img width="1047" alt="Screenshot 2024-11-23 at 12 30 29 PM" src="https://github.com/user-attachments/assets/e5e2efbe-e508-4009-92fc-95bd7eab3b23">

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_66e3b91**, Docker, macOS 14.5, FF v126.0.1
