### ISSUE TITLE
Demo Starter no longer contains Members Index page

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#30446]
### Problem Statement

For protected pages, our demo no longer provides the login page for the "members" section, meaning this example is not usable. 

### Steps to Reproduce

Go to demo.dotcms.com/dotAdmin
Go to the members folder
See there is no index page

### Acceptance Criteria

Readd the index page to the dotCMS starter. Ensure it works, allowing a login functionality for the intranet role. 

### dotCMS Version

Current, Demo

### Proposed Objective

Sales

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1729776897603819

**Comment by wezell** [comment]
Needs a new starter

**Comment by nollymar** [comment]
Starter generated. Version: 20241031

**Comment by nollymar** [comment]
**Internal QA:** Passed
