### ISSUE TITLE
UVE: Editing Layout Changes Not Showing in UVE (Angular)

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30441]
### Problem Statement
When editing the layout in the Angular example in dotCMS, the changes made do not immediately show in the UVE (Unstructured Content Editor). Users have to perform a hard refresh to see the updated layout.

### Steps to Reproduce
https://github.com/user-attachments/assets/d7168917-4f2d-4ea1-9d2a-2f1604f853db

### Acceptance Criteria
Layout changes should be reflected immediately

### External Links
- Reported by a partner

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by KevinDavilaDotCMS** [comment]
# IQA Instructions

I addition to the fix of the card, this PR have a fix of old issue about UVE with traditional pages.
In Traditional pages, when we go to layout and then go back to the editor (with or without changes in the layout), the UVE show a infinite loading state
So we can include an IQA about this, opening a traditional pages and navigate between editor and layout and we should no see a infinite loading state

**Comment by zJaaal** [comment]
# IQA Passed 

DotCMS Docker Image: `[dotcms/dotcms:trunk_396487e]`


## Angular Layout Update

https://github.com/user-attachments/assets/beee209c-8400-4b53-973f-31a6b336c490

## Traditional case mentioned by @KevinDavilaDotCMS 

https://github.com/user-attachments/assets/c44d1f3e-f850-48e4-b934-c6e1575ecdfc

**Comment by bryanboza** [comment]
Fixed, tested on main // Docker // FF
