### ISSUE TITLE
Persona assigned by City or Province

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#30455]
### User Story

- the user wants to be able to assign personas based on the visitor's location
- although we offer the possibility to trigger a rule based on a radial area, the customer wants something more specific, like the visitor's City or Province

"the end goal for us is to fire the rule based on a specific city or province"

### Acceptance Criteria

- in the Marketing -> Rules there should be an option to trigger the rule by choosing Visitor's city or province

### Proposed Objective

Customer Success

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28184

**Comment by john-thomas-dotcms** [comment]
The default geolocation included in dotCMS is not highly specific.  Customers can upgrade it to a more precise version by paying the vendor, or by implementing their own geolocation with a different vendor.

Since precise geolocation is a paid-for feature, we do not include it in dotCMS.
