### ISSUE TITLE
FTM: Create Feature Flag to enable New Preview Mode

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30459]
### Parent Issue

https://github.com/dotCMS/core/issues/30598

### User Story

As a user, I want to enable or disable the Preview Mode feature through a Feature Flag. If the Feature Flag is not enabled, I want my UVE to remain unchanged, retaining all existing functionality.

### Task
Develop a new Feature Flag to enable the Preview Mode in our application. The new Feature Flag should follow the existing format of the FeatureFlag object, defined within the FeaturedFlags enum

```
export const enum FeaturedFlags {
    LOAD_FRONTEND_EXPERIMENTS = 'FEATURE_FLAG_EXPERIMENTS',
    DOTFAVORITEPAGE_FEATURE_ENABLE = 'DOTFAVORITEPAGE_FEATURE_ENABLE',
    FEATURE_FLAG_TEMPLATE_BUILDER = 'FEATURE_FLAG_TEMPLATE_BUILDER_2',
    FEATURE_FLAG_SEO_IMPROVEMENTS = 'FEATURE_FLAG_SEO_IMPROVEMENTS',
    FEATURE_FLAG_SEO_PAGE_TOOLS = 'FEATURE_FLAG_SEO_PAGE_TOOLS',
    FEATURE_FLAG_EDIT_URL_CONTENT_MAP = 'FEATURE_FLAG_EDIT_URL_CONTENT_MAP',
    FEATURE_FLAG_CONTENT_EDITOR2_ENABLED = 'CONTENT_EDITOR2_ENABLED',
    FEATURE_FLAG_CONTENT_EDITOR2_CONTENT_TYPE = 'CONTENT_EDITOR2_CONTENT_TYPE',
    FEATURE_FLAG_ANNOUNCEMENTS = 'FEATURE_FLAG_ANNOUNCEMENTS',
    FEATURE_FLAG_NEW_EDIT_PAGE = 'FEATURE_FLAG_NEW_EDIT_PAGE',
    //
    FEATURE_FLAG_UVE_PREVIEW_MODE = 'FEATURE_FLAG_NEW_EDIT_PAGE'
}
```

Additionally, this Feature Flag should be accessible through the getFeatureFlags method located in `core/core-web/libs/data-access/src/lib/dot-properties/dot-properties.service.ts`

### Acceptance Criteria

- A new constant for the Preview Mode Feature Flag is added to the FeaturedFlags enum. The new flag follows the naming conventions and structure of existing Feature Flags within this enum.
- The Preview Mode Feature Flag is integrated into the getFeatureFlags method in `dot-properties.service.ts`, allowing it to be fetched and managed centrally.
- Verify that toggling the Feature Flag correctly enables or disables the Preview Mode. Ensure no side effects or regressions on existing Feature Flags

**Comment by zJaaal** [comment]
## Note to QA

The name decided for this FF is `FEATURE_FLAG_UVE_PREVIEW_MODE`

**Comment by oidacra** [comment]
When the FF does not exist return `NOT_FOUND`
And show the empty component
![CleanShot 2024-11-13 at 16 10 39@2x](https://github.com/user-attachments/assets/226be253-1d30-459e-86a3-18364c9f24da)
Using `trunk_b1ba6db` docker image.

**Comment by zJaaal** [comment]
Addressed on https://github.com/dotCMS/core/pull/30653

**Comment by rjvelazco** [comment]
### Passed IQA

- Tested on docker image: [`dotcms/dotcms:trunk_3d77285`]

### `FEATURE_FLAG_UVE_PREVIEW_MODE` disable

https://github.com/user-attachments/assets/b8b6be96-0cac-47d5-8bba-c0532692c961

### `FEATURE_FLAG_UVE_PREVIEW_MODE` enable

https://github.com/user-attachments/assets/acdd5be3-3fb4-4a31-99c1-a374a96e79bc
