### ISSUE TITLE
fileAssetMap with inputStream breaks pageAPI 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30464]
### Problem Statement

When I create new blogs using an uploaded image (FileAsset) then I hit save and publish and hit the URL 
https://demo.dotcms.com/api/v1/page/json/blog?language_id=1&mode=LIVE
it breaks! 

https://github.com/user-attachments/assets/29bae18b-9d00-4d8f-93b8-6644b46ffbbf

### Steps to Reproduce

go to demo upload a new FileAsset using an image
the and create a new blog with the actual day as the posting date and the image you just uploaded as the Blog Image
Then hit the following url
https://demo.dotcms.com/api/v1/page/json/blog?language_id=1&mode=LIVE
See how it breaks with the following exception:

`No serializer found for class java.io.BufferedInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.dotcms.rest.ResponseEntityView["entity"]->com.google.common.collect.RegularImmutableMap["containers"]->java.util.HashMap["//demo.dotcms.com/application/containers/default/"]->com.dotmarketing.portlets.htmlpageasset.business.render.ContainerRaw["contentlets"]->java.util.HashMap["uuid-1"]->java.util.ArrayList[1]->com.dotmarketing.portlets.contentlet.model.Contentlet$ContentletHashMap["widgetCodeJSON"]->java.util.HashMap["posts"]->java.util.ArrayList[0]->java.util.LinkedHashMap["image"]->com.dotcms.rendering.velocity.viewtools.content.FileAssetMap["inputStream"])`

For some reason, this only happens if you use an uploaded image. 
endemic starter images do just fine

### Acceptance Criteria

you should always be able to see the blogs regardless of the image 

### dotCMS Version

current main 

### Proposed Objective

User Experience

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dcolina** [comment]
## Internal QA: Passed.

The task outlined in the problem statement has successfully passed internal QA testing. The testing was conducted using the Docker image `dotcms/dotcms:trunk_7408571`.

Testing confirmed that the issue is resolved, and the blog can be created, saved, published, and accessed without error when using an uploaded image. A screen recording of the successful test has been attached as evidence:

https://github.com/user-attachments/assets/77d8e774-55ea-4c26-84ab-053f0bb260e4

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps and now it is working as expected. 

https://github.com/user-attachments/assets/d29a11a0-97df-4b04-a735-ad72ae0c9f5b
