### ISSUE TITLE
Contentlet listing is not considering postingDate

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30461]
### Parent Issue

https://github.com/user-attachments/assets/1d961683-5652-4ccd-94f5-05288f047739

### Problem Statement

Blog listing is not considering postingDate of contentlets

### Steps to Reproduce

- Create a new Blog
- Put a future posting Date
- Go to/blog and you can see the blog in the listing  

### Acceptance Criteria

- The listing consider postingDate and dont show a Draft content

### dotCMS Version

Latest

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment]
Here's what I have found about this issue : 
it comes from the page API Logic 
it is assumed that we're on PREVIEW or EDIT MODE therefore the query that brings all the contentlets  is built using +working therefore the unpublished bits are included 
![Uploading Screenshot 2024-11-01 at 3.23.06 PM.png…]()

**Comment by fabrizzio-dotCMS** [comment]
This query works just fine excluding the Working content
http://localhost:8080/api/v1/page/json/blog?language_id=1&mode=LIVE
This query also works just fine including the Working content (as it should)
http://localhost:8080/api/v1/page/json/blog?language_id=1&mode=EDIT_MODE
