### ISSUE TITLE
Create a GitHub Action to Automate Labeling for Next Release

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#30488]
### Parent Issue

https://github.com/dotCMS/core/issues/30844

### Task

Create a GitHub Action to automatically add the label Next Release when either the QA Approved or QA Not Needed labels are added to a GitHub issue.

### Proposed Objective

Integrations

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- The GitHub Action should trigger when labels are added to an issue or pull request.

- If either the Passed IQA or QA Not Needed label is added, the action should add the Next Release label to the issue.

- The action should ignore cases where the Next Release label is already present.

- The action should log its activity for auditing purposes.

### Assumptions & Initiation Needs

1. Trigger Event:
- The action is triggered when a label is added to an issue.
	
2. Check for QA Approved or QA Not Needed Label:
- The first step uses the github-script action to inspect the labels on the issue.
- It checks if either the QA Approved or QA Not Needed label is present and verifies that Next Release is not already added.
- If both conditions are met, the result is set to true, allowing the next step to run.
	
3. Add Next Release Label:
- If the previous check passed, this step uses the action-add-labels action to add the Next Release label to the issue.
	
4. Log Action:
- Logs a message indicating that the Next Release label was added due to the presence of QA Approved or QA Not Needed.

### Quality Assurance Notes & Workarounds

- GitHub Token: The ${{ secrets.GITHUB_TOKEN }} is used for authentication, allowing the action to add labels to issues.

- Logging: This workflow logs a message each time it successfully adds the Next Release label, which is useful for tracking and auditing purposes.

**Comment by victoralfaro-dotcms** [comment]
QA Notes
- Add to this issue any of the following labels: `QA : Approved`, `QA : Internal Passed` or `QA : Not Needed`
- Wait for 30 secs and refresh the issue page, you will see the `Next Release` label automatically added to this issue.
- Undo any label adding (manually or automatically)

**Comment by dsilvam** [comment]
Passed IQA: 
Working as expected

![Image](https://github.com/user-attachments/assets/7f528c3d-0333-4cdf-ae8d-76b89b5c570f)
![Image](https://github.com/user-attachments/assets/8e750e5c-99cf-4de1-985b-3fe95d703fea)
![Image](https://github.com/user-attachments/assets/b00eb55e-9e22-4d57-aa19-dc248bf9177d)
