### ISSUE TITLE
QA: Implement a Naming Convention for All New Bug Reports

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30497]
### Task

As part of the department rocks we need to establish a consistent and clear naming convention for all new bug reports across all teams, ensuring clarity and uniformity in bug tracking and reporting.

#### Target: 
- Ensure 100% compliance with the naming convention for all new bug reports within 2 months of implementation.
- Regularly review bug reports for adherence to the standard.

## Acceptance Criteria 

**Naming Convention Development:**

- A standardized naming convention for all bug reports is developed, reviewed, and approved by key stakeholders.

**Communication:**

- The new standard is communicated to all relevant teams through email, chat channels, or meetings.
- A clear guideline document, along with examples, is distributed to help teams adhere to the new convention.

**Training and Documentation:**

- Provide training sessions or materials (e.g., videos, written documentation) that outline the proper bug-naming format.
- Templates or examples are provided for team members to follow.

**Company-Wide Implementation:**

- The naming convention is adopted by all teams, and communication about the new standard is sent organization-wide.

**Feedback Loop:**

- Regular feedback is gathered from teams to improve and refine the naming convention process

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Proposed: 

[Component] : [Brief description]

**Component:** 
- Identify the area of the system where the bug occurs.
- Helps teams quickly locate the affected area and assign the bug to the right team.

**Brief description:**
- A short, clear statement that describes the issue 
- Avoid long texts on title

**Comment by fmontes** [comment]
I already use these:

   - "UVE" for Universal Visual Editor
   - "SDK" for JavaScript SDK or examples
   - "dotCLI" for dotCLI

**Comment by josemejias11** [comment]
**QA Comment**

First draft for the Naming convention proposal
[Bug_Report_Naming_Convention_Guidelines.pptx](https://github.com/user-attachments/files/17737904/Bug_Report_Naming_Convention_Guidelines.pptx)

**Comment by bryanboza** [comment]
We need to create a document outlining the proposed changes to share with the R&D department. This will allow us to open a feedback window and gather input before proceeding. Please ensure the document includes all necessary details for a comprehensive review.

**Comment by josemejias11** [comment]
**QA Comment**

Here you can find the document for everyone to provide feedback to the naming convention proposal 

https://docs.google.com/document/d/1Eb1Xcn9qw150ySCI5j6Y5Mm_fTGSmED5XMcFfquJor8/edit?usp=sharing

**Comment by bryanboza** [comment]
Donde according to the discussion we will use tags for now.
