### ISSUE TITLE
Rafael: Drop Everything & Learn Oct 23 - Nov 05

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30491]

**Comment by rjvelazco** [comment]
## [SEO Tutorial for Beginners](https://dotcms.udemy.com/course/seo-tutorial/)

This time I took a quick SEO Tutorial, here my notes:

### Fundamentals

- Keyword Research
- Optimisation
- Build Authority (Link Building)

#### Keywords Research

- [[Keywordseverywhere.com](http://keywordseverywhere.com/)](http://Keywordseverywhere.com) - Essential tool for everybody to see the market

#### Target body and Long Tail Keywords

- **Head:** 1 word phrases
    - Ex: **Logistics**, **Drone**, **Course**
- **Body:** 2-3 Word phrases
    - Ex: **Logistics Management, Logistics Management Software**
- **Long tail:** More descriptive Phrases
    - Ex: Logistics management software case studies

**Aim for a Portfolio of keywords**

### On Page Optimization

- **Title:** Include the company name and some of the keywords
    - Less than 55 characters
- **Description:** Keywords, engaging
    - Less than 155 characters

### Optimize Any Blog Post

- **URL:** It should include the Keywords we are trying to boost
    - Avoid number
    - Avoid non-alphabet characters

### Off Page Optimization

- **Backlinks:** They are links on websites other than your own that go back to a page on your website
- **Refers audience**
- **Poster Boy Formula:** Find established companies that have your target audience and become their poster boy.
    - You can use Medium and backlink your website

#### How to Protect Yourself from Black Hat SEO

- Do not buy “Backlinks”/”Google Reviews”
- Google Penguin is watching

#### SEO for Local Business

- Google My Business
- Google Reviews

## **FYI:** I also continue the  [The Complete Communication Skills Master Class for Life](https://dotcms.udemy.com/course/the-complete-communication-skills-master-class-for-life/)

Here are some notes:

### Workplace Communication: You Can Speak Up at Meetings!

- Ask questions the right way
    - Ask normal questions - Not need to be brilliant
    - Don’t put pressure on yourself
- **Use Notes**
    - Make/Takes notes
        - Two-three works
        - A little outline for what you wanna say
    - Write your questions before the meeting starts
    - Introduce an idea
- **Risk Assessment**
    - It is possible to ask stupid questions
        - It’s not common to happens
    - The real risk is not being noticed and stagnating by not speaking
- Be conversional
    - Sound like you are thinking and talking at the same time
    - Do not just read and speak
    - It shouldn’t sound memorized
    - It’s a conversation, be natural
- Exude Confidence
    - Be confidence on your style
    - Volume loud enough to be heard
    - Take your time to deliver your idea
    - Look and sound relax
    - Don’t rush
    - Don’t do anything awkward
    - Don’t beat yourself if you made a mistake
    - Don’t doubt the value of your ideas
- Practice speaking in videos
- Try to speak out in every meeting to add value/ask questions
