### ISSUE TITLE
[Spike] SDK: Enhance Error Handling in JavaScript SDKs (Angular and React) 🌵

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30498]
### User Story
As a JavaScript Developer, I want to ensure errors within SDK components do not crash the entire webpage, so I can have a better developer experience and easier debugging.

### Problem Statement
In the current state, if a JavaScript error occurs within SDK components, it causes **the entire webpage to crash**. This fragility leads to a frustrating developer experience by:

1. **Compromising Page Stability**: Errors within any SDK component cause a full-page crash, rather than isolating the failure to the affected component. Developers lose context and control over debugging due to the cascading effect of these errors.

2. **Lack of Actionable Error Messaging**: When crashes occur, error information is vague or non-existent, offering limited insight into the error’s origin and is even worse in production builds. Developers are left with no clear direction on where or how to address the issue in their code, making troubleshooting time-consuming, and is even worse for content authors, they have zero visibility on what happened.

3. **Developer Experience Impact**: The inability to contain errors within specific SDK components disrupts development workflows and decreases confidence in SDK reliability. This lack of resilience is particularly challenging when using frameworks like React and Angular, which have built-in capabilities (e.g., error boundaries in React, Angular's global error handling) that could be leveraged to isolate errors and prevent full-page crashes.

### Objective
To address these issues, we aim to research and implement error-handling strategies that:
- **Isolate Errors**: Contain errors within the affected component, preventing full-page disruption and allowing the rest of the page to function.
- **Improve Debugging Insight**: Provide clear, component-specific error messages, helping developers quickly identify and resolve issues.
- **Enhance SDK Robustness**: Implement framework-specific solutions like React’s error boundaries and Angular’s global error management to make the SDK more resilient and improve developer confidence.

```[tasklist]
### Acceptance Criteria
- [ ] Review and document existing error management techniques in JavaScript, React, and Angular for component-level error handling.
- [ ] Identify best practices for error isolation in component-based SDKs to prevent full-page crashes and ensure errors are contained.
- [ ] Write summary document comparing error-handling techniques across React, Angular, and Next.js frameworks.
- [ ] Documentation on key error-handling methods that enhance reliability in our JavaScript SDK
- [ ] Test results and recommendations for component-specific error handling across SDK components, ensuring isolated recovery mechanisms.
```

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
1. React [ErrorBoundaries](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)
2. Angular [ErrorHandler](https://v17.angular.io/api/core/ErrorHandler)
3. Next.js [error handling](https://nextjs.org/docs/app/building-your-application/routing/error-handling) 
4. Astro [error management](https://dev.to/koyopro/how-to-perform-error-handling-across-pages-in-astro-3dk8)

### Assumptions & Initiation Needs
- Basic understanding of error management in React and Angular is necessary.
- Access to the current SDK sources and development environments for React and Angular.

### Quality Assurance Notes & Workarounds
N/A

### Technical Details
React and Angular latest stable versions should be utilized during the testing and implementation phase.

**Comment by zJaaal** [comment]
Finding are explained in this PR https://github.com/dotCMS/core/pull/30751
