### ISSUE TITLE
ContentEditor: Retrieve Workflow Tasks

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#30519]
### User Story

As an user, I want to be able to retrieve the workflow task by rest, so I can display the ones that the current user can see in the content editor

### Acceptance Criteria

An endpoint that returns the properly workflow tasks

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by oidacra** [comment]
@jdotcms 
Please add the acceptance criteria:
- Endpoint
- Body, GET/POST
- Response expected

**Comment by jdotcms** [comment]
Endpoint:
curl --location 'http://localhost:8080/api/v1/workflow/tasks/history/comments/' \
--header 'Authorization: ••••••' \


Response:
```
{
    "entity": [
        {
            "commentDescription": "Admin User completed action Publish",
            "createdDate": 1730822074734,
            "postedBy": "Admin User",
            "roleId": "dotcms.org.1",
            "taskId": "1dcf5459-b50f-4890-8b49-961911406208",
            "type": "WorkflowHistory"
        }
    ],
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

**Comment by oidacra** [comment]
IQA Passed:
`/api/v1/workflow/tasks/history/comments/{historyIdentifier}`

![CleanShot 2024-11-06 at 10 37 09@2x](https://github.com/user-attachments/assets/6f595c20-3ca9-4f7d-b9d6-e801c14f2abf)

![CleanShot 2024-11-06 at 10 35 55@2x](https://github.com/user-attachments/assets/1fed0eef-0aa2-4c3e-b7b6-5d85d864d7a7)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4271248**, Docker, macOS 14.5, FF v126.0.1
