### ISSUE TITLE
Implement Activities API Endpoints for Edit Contentlet

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30510]
### Parent Issue
#30372 

### User Story
As a developer, I want to create the necessary API endpoints for Activities management in the Edit Contentlet Sidebar, so we can handle all activities-related operations efficiently.

### Acceptance Criteria
1. API Implementation
   - Create GET endpoint for listing activities with pagination
   - Implement POST endpoint for adding new activities
   - Create DELETE endpoint for removing activities
   - Include proper error handling and status codes
   - Add proper validation for inputs

![CleanShot 2024-10-30 at 13 12 01@2x](https://github.com/user-attachments/assets/09932780-a33b-4453-8807-892a5996f4ac)

2. Response Structure
To be defined

3. Documentation
   - OpenAPI/Swagger documentation
   - Example requests and responses

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

**Comment by jdotcms** [comment]
we already implement the get history and comments in a previous issue: https://github.com/dotCMS/core/issues/30519
So this will be only create and delete

**Comment by jdotcms** [comment]
In order to add a comment you can
```
curl --location 'http://localhost:8080/api/v1/workflow/comments/d4dcfcf8-227b-4250-810d-a6999f6c1b0c' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "comment":"This is a postman test"
}'
```

Where the uuid is an contentlet identifier

**Comment by jdotcms** [comment]
We are not going to implement the delete, so this issue is code done

**Comment by oidacra** [comment]
IQA Passed:
# Add comment
POST `/api/v1/workflow/0edfee78-2a75-4f3d-bf20-813aae15d4e9/comments`
```
{
    "comment": "My comment 2"
}
```
![CleanShot 2024-11-13 at 09 59 13@2x](https://github.com/user-attachments/assets/bbe19257-9c7d-49d7-8cd5-abbaf5b90bb8)

# List
GET `/api/v1/workflow/tasks/history/comments/0edfee78-2a75-4f3d-bf20-813aae15d4e9`
![CleanShot 2024-11-13 at 10 00 23@2x](https://github.com/user-attachments/assets/672a8344-dc1b-4171-aa90-812806a8c0b0)

# Error handling and status code
![CleanShot 2024-11-13 at 10 02 23@2x](https://github.com/user-attachments/assets/729112f6-3b0c-423e-a8b4-bedb906492fd)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b1ba6db**, Docker, macOS 14.5, FF v126.0.1
