### ISSUE TITLE
Create Basic Relationship Field Structure for Edit Contentlet

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30515]
### Parent Issue
#30495 

### User Story
As a developer, I need to implement the base structure for the Relationship Field component in Edit Contentlet, so we can build upon it for further functionality.

### Acceptance Criteria
1. Component Structure
   - Create basic Relationship Field component
   - Register component in the Field Type system
   - Handle basic field properties (required, disabled, etc.)
   - Implement basic form field validation
   - Add placeholder for content relationship data

2. Integration Requirements
   - Properly integrate with Edit Contentlet form
   - Handle field initialization
   - Support field configuration
   - Implement basic state management

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External files

[Figma File Component](https://www.figma.com/design/YMTdSO5gKf18rc1pCCv1jN/Edit-Content-Screen?node-id=2900-99314&t=1U40OwH9LLaf5i8b-4)

![CleanShot 2024-10-30 at 14 46 19@2x](https://github.com/user-attachments/assets/c48ebd27-8b3b-4bb4-b2c2-6af37046abe8)

**Comment by oidacra** [comment]
This not will be implemented by now.

**Comment by nicobytes** [comment]
QA Notes:

This card only covers the basic setup and structure with mock data for the new relationship field. So far, there isn't connection with the proper endpoints.

https://github.com/user-attachments/assets/0a0f9f23-1949-44c2-ac06-e4d62f8dbaf3

**Comment by dsilvam** [comment]
Passed IQA: 

Main screen for selection of existing content with all the elements in the design. 
**The only one missing is the "Show selected entries" but will be done in the next PR.** 

![Image](https://github.com/user-attachments/assets/f41fca7b-697b-44bd-90c0-ca08a6c50b63)

Component for showing the included related content in place and looking as the design: 

![Image](https://github.com/user-attachments/assets/270e57e1-bb7f-4c54-a489-d3a2fb978cd0)
