### ISSUE TITLE
Implement Existing Content Selection Dialog for Relationship Field

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30524]
### Parent Issue
#30495 

### User Story
As a content editor, I want to search and select existing content through a dialog interface to relate it to my current content.

### Acceptance Criteria
1. Dialog Implementation
   - Create PrimeNG dialog component
   - Implement content search
   - Add content filtering
   - Enable multi-select functionality
   - Add apply/cancel actions

2. Content Selection Features
   - Search by title functionality
   - Filter by content type
   - Sort options
   - Pagination support
   - Select/deselect all
   - Show selected items count
   - Preview selected content

3. UI/UX Requirements
   - Responsive dialog size
   - Clear selection indicators
   - Loading states
   - Error handling
   - Selection persistence

![CleanShot 2024-10-30 at 14 58 56@2x](https://github.com/user-attachments/assets/071b9774-7d0f-437b-92f1-9b32f0579f4c)

### Proposed Objective
Technical User Experience

### Proposed Priority
Priority 2 - Important

**Comment by nicobytes** [comment]
Cover in https://github.com/dotCMS/core/issues/30515
