### ISSUE TITLE
Implement Relationship Field Data Table with Mock Data

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30523]
### Parent Issue
#30495 

### User Story
As a content editor, I want to see related content in a well-organized, interactive table that allows me to manage and reorder items efficiently.

### Acceptance Criteria
1. Table Implementation
   - Use PrimeNG Table component
   - Implement 5 columns:
     * Drag handle icon
     * Title
     * Language
     * State
     * Delete icon
   - Enable drag-and-drop reordering
   - Support horizontal scrolling for overflow
   - Show 6 items per page with pagination

2. UI/UX Requirements
   - Implement drag handles for reordering
   - Show state indicators with proper styling
   - Right-aligned pagination when hint text exists
   - Responsive table behavior
   - Clear hover states
   - Proper row spacing

3. Mock Data Integration
   - Create realistic mock data set
   - Include various states and languages
   - Support different content types
   - Handle empty states

![CleanShot 2024-10-30 at 14 50 13@2x](https://github.com/user-attachments/assets/71b66e55-5499-4348-ad50-18aac60fb4de)

![CleanShot 2024-10-30 at 14 50 28@2x](https://github.com/user-attachments/assets/953d14d4-bb40-44e2-a721-eb08c886b812)

### Proposed Objective
Technical User Experience

### Proposed Priority
Priority 2 - Important

**Comment by hmoreras** [comment]
iQA Checked agains https://www.figma.com/design/YMTdSO5gKf18rc1pCCv1jN/Edit-Content-Screen?node-id=3744-112387&node-type=canvas&t=QXSQ4XbvC8eoe9NR-0 


- Empty state looks correct. 

### Search Dialog:
-  The title should be "Search" and not "Select existing content". 
- The table should use the new format, where each row has less height. Like we did in the locale portlet with the `dotTable` class https://github.com/dotCMS/core/blob/main/core-web/libs/portlets/dot-locales/portlet/src/lib/dot-locales-list/dot-locales-list.component.html#L27C21-L27C29
-IF the user make a search, close the dialog and open it again the search input and the entries button are not clean, keeps the state. 
- Dialog should not be draggable.  
- following patterns, Dialog should keep the same height. when the user perform a search with a couple of rows the height change 
- Form figma: The selected items will have an active state background.
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/8dbe56e2-c8a0-429b-afa9-10924ba54406">


drag handles, state indicator and responsive behavior looks good.

**Comment by nicobytes** [comment]
QA Notes:

The feedback was solved on this PR https://github.com/dotCMS/core/pull/30901

**Comment by hmoreras** [comment]
Pass internal QA, UI elements looks good, however data integration is missing, a revisit will be needed when done.
