### ISSUE TITLE
Add Reset Workflow Button in Edit Contentlet Sidebar Workflow Section

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30525]
### Parent Issue
#30017 

### User Story
As a content editor, I want to be able to reset the workflow status of a content item directly from the Edit Contentlet sidebar, so I can quickly restart the workflow process when needed.

We need to confirm all the cases available to show this icon.
![Image](https://github.com/user-attachments/assets/67cf0513-961a-4618-bfc4-2aa15dc7f79d)

### Acceptance Criteria
1. Button Implementation
  - Add "Reset" button in the Workflow section
  - Place button next to existing workflow controls
  - Use appropriate PrimeNG button component (Icon like the Design)

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links
N/A

**Comment by oidacra** [comment]
Define all the cases. @dsilvam

**Comment by oidacra** [comment]
Endpoint
`/api/v1/workflow/contentlet/0f306acb-115b-4d04-8a1f-d6b137dc5319/actions`

**Comment by oidacra** [comment]
#30541

**Comment by oidacra** [comment]
### QA Notes
## Requirements
- To be able to reset a workflow needs first add the `sub-action` to the `Reset Workflow` `action` at the step de `Published`
![CleanShot 2024-11-29 at 16 43 31@2x](https://github.com/user-attachments/assets/2dc9257a-657f-4b4e-b65b-67f5f142af67)

## Main Feature Test Case

The Reset button should only appear when content moves to a step where there is at least one possible action that has a Reset Workflow subaction.

## Additional Test Cases from PR Improvements

- For a content type with 2 workflows, if the content is new, a message should appear requiring workflow selection before saving.
- For new content with only 1 workflow available, that workflow should be automatically assigned.
- With 2 workflows available and content not yet saved (still new), the workflow can be changed using the edit (pencil) icon.
- Once the content is saved, the workflow cannot be changed.
- All workflows must display their correct corresponding actions.

**Comment by dsilvam** [comment]
Passed IQA: Reset working as expected. 

If there's an action with a reset actionlet, the reset icon will show and works as intended. 

Reset icon showing
![Image](https://github.com/user-attachments/assets/a4d67bbb-5f02-4971-a429-6a105cc324d9)

Upon clicking on it it's resetting the workflow
![Image](https://github.com/user-attachments/assets/f207c0bc-9e34-48ba-a94c-e88344ff94f8)
