### ISSUE TITLE
Add framebusting headers/js to the dotcms admin console 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#3053]
It is possible to "clickjack" the dotCMS admin console, which works in a frameset.  We need to add the "X-Frame-Options: Deny" / "X-Frame-Options: Sameorigin" header to all requests (both CMS admin and end-user requests). See:

https://www.owasp.org/index.php/ClickjackFilter_for_Java_EE
- For older browsers which do not support the X-Frame-Options header, all CMS admin pages should have the "frame busting" JavaScript applied, for example:

```
<head>
<style> body { display : none;} </style>
</head>
<body>
<script>
if (self == top) {
var theBody = document.getElementsByTagName(’body’)[0];
theBody.style.display = "block";
} else {
top.location = self.location;
}
</script>
```

OWASP Guide to Clickjacking:
https://www.owasp.org/index.php/Clickjacking

This issue is referenced here - if the fix version changes, we need to update the content on our site

http://dotcms.com/security/possible-clickjacking-no-frame-busting-code-in-dotcms-admin

**Comment by mattyarbrough** [comment]
https://my.dotcms.com/tickets/detail.dot?id=53d0cdda-a7f1-407e-b920-34bbf736df26  Support Requested
