### ISSUE TITLE
ContentEditor: Add resetable property to the workflow action

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#30541]
### User Story

As an user I want to be able to reset the workflow, in order to do it we need to provide a way to the UI to know if the action has or not a reset actionlet in any of the actions
So we will return a boolean property called isResetable that will tells if the actionlet can or not be used for reset

### Acceptance Criteria

Actionlet with a reset sub actionlet assign will set the isResetable in true

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
In order to test this you can add the reset workflow action on an action
1) if it is there, the hasResetActionlet property will be in true
2) if iti is not, the hasResetActionlet will be false

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `trunk_7a5f044`

The JSON information for the Workflow Action containing the `Reset Workflow` Actionlet is displaying the `hasResetActionlet` with the value `true`, as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b1b0006**, Docker, macOS 14.5, FF v126.0.1

- [ ] if it is there, the hasResetActionlet property will be in true
- [ ] if iti is not, the hasResetActionlet will be false

![Screenshot 2024-11-11 at 4 03 40 PM](https://github.com/user-attachments/assets/dab07c45-65ae-462f-abc8-ca9da7a2fa2e)
