### ISSUE TITLE
The last role in the Roles list is partially visible

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#30544]
### Problem Statement

- when the list of roles is expanded, the scrolling won't allow you to entirely see the last item in the list (it will only show half of it)

### Steps to Reproduce

- you have to reproduce it on an instance where the count of roles exceeds the space in the area where the roles are shown
- if there are enough roles so that the expanded list has to be scrolled down, then the last role in the list will be only half visible (but accessible)

<img width="194" alt="image" src="https://github.com/user-attachments/assets/86efc929-953c-476c-927b-057d4e3df923">

### Acceptance Criteria

- the last Role in the list should be totally visible

### dotCMS Version

- 24.10.09

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28344

**Comment by gortiz-dotcms** [comment]
**### Passed internal QA**

Now all the items are properly displayed and the scroll works fine.

<img width="339" alt="Captura de pantalla 2024-12-30 a la(s) 1 53 07 p  m" src="https://github.com/user-attachments/assets/76ca2844-17d6-43f5-b9ce-49e158c31498" />
