### ISSUE TITLE
Figure out why the metric_sumamry view is not working

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30563]
### User Story

For some reasons the View is not retrieving any data 

### Acceptance Criteria

The View must work again

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
The problem was not the view it was that some data was saving as String and not like a JSON.

@victoralfaro-dotcms fixed that problem in the Endpoint and now athe data is saved as a JSON again, also the data need to be fixed to make the view works good again

**Comment by victoralfaro-dotcms** [comment]
There were some [internal-infrastructure](https://github.com/dotCMS/internal-infrastructure)'s unmerged (to `main` branch) changes from a year ago that exist only in "orphan" branches. These unmerged changes included:
- Outdated dotcms-configurator URL filter configuration
- Actual transformation from string data to JSON for saving purposes at the telemetry database
We leverage all the CA work to consolidate these changes and merged them back to `main` as they should be.
