### ISSUE TITLE
Create a field that allows for multi-selection of sites and/or groups of sites

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#30569]
### User Story

As a content creator, I want to have a field where I can mark what sites I want my content to show up on, so that I can use that field to query for what content to display and so I can mark groups of sites all at once.

### Acceptance Criteria

Create a field that pre-populates with a multi-select dropdown of the sites, and also allows users to customize the list of sites that gets populated by adding groups of the sites.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28138

### Quality Assurance Notes & Workarounds

One workaround is to use the relationships field with a many to many relationship to relate content to hosts. This would not accomplish the secondary goal of

**Comment by john-thomas-dotcms** [comment]
@weiyiwang-dotcms the standard way of doing this is with a custom field.  We have no plans to create a field just for this specific use case.
