### ISSUE TITLE
Implement Base Language Component and Store Integration

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30579]
## Parent Issue
#30371 

## Task
Implement the base language component in the EditContentLet sidebar with the following:
* Create new component structure
* Implement store slice for language management
* Display current contentlet language
* Setup basic component styling following Figma design

## Acceptance Criteria
* New component is created and integrated into the sidebar
* Store slice is implemented with proper state management
* Current language is correctly displayed
* Basic styling matches Figma design
* loading state

## Proposed Objective
Same as Parent Issue

## Proposed Priority
Same as Parent Issue

**Comment by oidacra** [comment]
IQA Passed
![CleanShot 2024-11-26 at 10 14 57@2x](https://github.com/user-attachments/assets/dcf14061-aef5-4017-98d3-69cd46866617)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e15f58e**, Docker, macOS 14.5, FF v126.0.1
