### ISSUE TITLE
Select Workflow When Content Type Has Multiple Workflows Assigned

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30596]
### Parent Issue
#30017 

## User Story
As a content editor, I want to be presented with a clear workflow selection interface when creating/editing content with multiple workflows assigned, so I can choose the appropriate workflow and see its corresponding actions.

## Acceptance Criteria
- Warning Message Display:
  - Show a warning banner at the top of the content edit page when no workflow is selected
  - Warning message should read "You haven't selected a workflow yet. Please Select Workflow"
  - "Select Workflow" should be a clickable link in the warning message

- Workflow Selection Dialog:
  - Clicking "Select Workflow" link opens a modal dialog
  - Dialog should have the title "Select Workflow"
  - Include descriptive text: "Select the workflow you want to work on"
  - Display a dropdown with all available workflows for the content type
  - Include Cancel and confirmation buttons at the bottom
  - Show loading state on confirmation button when processing
  - Allow closing dialog via 'X' button in top-right corner

- Workflow Panel (Right Sidebar), which will be in implemented in another ticket: #30372
  - Display "No available activities yet" when no workflow is selected
  - After workflow selection:
    - Show selected workflow name
    - Display corresponding workflow step
    - Show assignee information
    - List available workflow actions under "Activities" section

- General Behavior:
  - If content type has no workflows:
    - No warning banner should appear
    - No workflow section should be shown in sidebar
  - Selected workflow should persist during the content editing session
  - Warning banner should disappear after workflow selection

### Proposed Objective
Technical User Experience

### Proposed Priority
Priority 2 - Important

### External Links
![CleanShot 2024-11-07 at 11 40 22@2x](https://github.com/user-attachments/assets/7fe39748-8d95-4b23-8a12-bda2cc8a9655)
![CleanShot 2024-11-07 at 11 40 28@2x](https://github.com/user-attachments/assets/d124e36a-bf96-4cca-9ea8-2de94f50a13c)
![CleanShot 2024-11-07 at 11 40 36@2x](https://github.com/user-attachments/assets/01747f74-c486-4a87-a6bf-01ca7bc56d93)
![CleanShot 2024-11-07 at 11 40 42@2x](https://github.com/user-attachments/assets/bc7ea71f-2b67-49be-973a-403c88982e8d)

## Quality Assurance Notes & Workarounds
Test cases should include:
- Content types with exactly 2 workflows
- Content types with more than 2 workflows
- Verify the selected workflow is correctly applied
- Verify proper error handling if no selection is made
- Test cancel/back functionality in the workflow selection process

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_494076c`

Workflows can be selected as required now by clicking the `Select Workflow` link. Note that the new `Activities` section is going to be implemented in another ticket: #30372

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_4f46e9e**, Docker, macOS 14.5, FF v126.0.1

Reset related issues are being work on the card https://github.com/dotCMS/core/issues/30525
