### ISSUE TITLE
UVE: Bring back inline editing for block editor fields in Headless 

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#30607]
### Parent
#27546 

### Task description
As a web content editor using dotCMS, I want to have the inline editing Block Editor in headless, so that I can easily make quick edits to content without switching to the code view.

**Wait for #28198**

https://github.com/dotCMS/core/assets/751424/1031f189-37ee-4aba-b2b1-eb8030fd46f0

### Acceptance Criteria
1. The inline editing feature is working with headless implementations
2. Users can seamlessly edit content inline without any issues.
3. The functionality works the same as it did in the old editor.
4. Users are not forced to update their code when using the inline editing feature.

### External Links
- Slack conversation: #dotCMS-development
- Support ticket: #12345

### Assumptions & Initiation Needs
- The new editor interface has the capability to support the inline editing feature.
- Users are familiar with how the inline editing feature worked in the old editor.
- A thorough testing phase will be conducted to ensure the feature works as expected.

### Quality Assurance Notes & Workarounds
- QA team should test the feature extensively to ensure it works seamlessly.
- Any issues or bugs encountered during testing should be documented and addressed before release.

**Comment by bryanboza** [comment]
Fixed
