### ISSUE TITLE
SDK: Improve JS Client Readme

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#30614]
### Task

Right now the JS SDK client readme is covering installation of the SDK, configuration and basic use cases. But we need to add examples for basic use cases of the `content` API.

The `content` API just have one method at the moment, which is the `getCollection` but it is a method that uses a builder pattern to create complex queries, so we require basic use cases so the developers can have a simple guide of how it works.

We can see which methods it has and write use cases for them

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- SDK JS Client Readme has all basic cases covered for the `content` API.
- Writing should be clear and easy to understand with basic knowledge on the API.
- Be sure that the methods have no missing docs or examples.

### Assumptions & Initiation Needs

- You understand how the `content` API works in the SDK JS Client

**Comment by zJaaal** [comment]
# IQA Passed

Readme now shows info about the Content API and provides examples for the user.

**Comment by bryanboza** [comment]
Fixed, we can close this after the Jamie's review. Merge is on the queue now!
