### ISSUE TITLE
Content Analytics: Allow all events to be recorded via the API

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30626]
### User Story

As a headless app developer, I want to be able to record the same analytics events that dotCMS records natively, but send them from my headless app.

Right now, dotCMS automatically records certain types of events from within dotCMS.  This includes events such as page URL hits, file URL hits, and URL Map hits.  Future Content Analytics functionality, including reports and back-end displays, will be built to query for these specific, pre-defined events.

So, future queries to be able to report on headless app activity, headless apps need to be able to record the same events that the native dotCMS code records.  We need an API which allows external apps to trigger recording of these pre-defined events.

### Acceptance Criteria

1. The new endpoint may be hit to record any existing analytics event.
    * This includes Page hits, File hits, URL Map hits, and Vanity URL hits.
2. The new endpoint may be hit to record arbitrary event types.
    * So, for example, users may create their own user-defined event types, and record them via the endpoint.
3. Events recorded via the new endpoint are distinguished from native events via a new analytics event property: Event Source.
    * For events recorded from native dotCMS code, this value should automatically be set to the class name of the analytics collector.
    * For events recorded via the new endpoint, this value should automatically be set to the API path (e.g. `/api/v1/analytics/endpointName`).

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
> Ideally, we need to find a way to generate Postman tests for those endpoints, ensuring we provide a structured instance to run the tests.

We do not have CA infrastructure on github, it is not possible to do these tests unfortunately.
we are trying todo the coverage by java test

**Comment by jdotcms** [comment]
In order to test this you can do something such as:
```
curl --location 'http://localhost:8080/api/v1/analytics/content/event' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--header 'Cookie: JSESSIONID=39E83B8A40878772272BA4706AC14296' \
--data '{
    "event_type":"PAGE_REQUEST",
    "url":"/test2",
    "screen_resolution":"1280x720"
}'
```

The event_type is one of the defined, otherwise will be a generic one
url is the page url path, otherwise will use the endpoint url which is not desired
the screen_resolution is property which is not calculated on the backend collectors but may be send, unfortunately the clickhouse in the moment to create this issue does not take in consideration this field, but may be sooner

As soon as you fired, the event will be running in background and collect the missing info base on the event_type and sending to clickhouse

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_e3f2b4f`

Using the CURL command provided by @jdotcms causes the event to be saved to the ClickHouse database, as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d3e2a46**, Docker, macOS 14.5, FF v126.0.1
