### ISSUE TITLE
ContentEditor: Adding first step into the defaultactions content type

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#30629]
### User Story

As an user, I want to be able to receive the first step on the endpoint 
/api/v1/workflows/defaultactions/contenttype/{contentTypeId}

### Acceptance Criteria

the first step of the scheme should be tehre

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
how to test:
Run this curl
curl --location 'http://localhost:8080/api/v1/workflow/defaultactions/contenttype/2a3e91e4-fbbf-4876-8c5b-2233c1739b05' \
--header 'Authorization: ••••••'

check the first step is being returned

**Comment by oidacra** [comment]
IQA Passed:
New property added to know what is the name of the `Step`
![CleanShot 2024-11-13 at 10 11 54@2x](https://github.com/user-attachments/assets/fb2cb782-e61b-498f-8b3d-d9603fa0647c)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_b1ba6db**, Docker, macOS 14.5, FF v126.0.1
