### ISSUE TITLE
Rafael: Drop Everything & Learn Nov 06 - Nov 19

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30641]

**Comment by rjvelazco** [comment]
## I continue the  [The Complete Communication Skills Master Class for Life](https://dotcms.udemy.com/course/the-complete-communication-skills-master-class-for-life/)

Here are some notes:

### Eliminate Verbal Tics, Uh, Um, Er, Ya know

- **You can always simply pause**
- Practice Speaking Slowly
- People do it when they feel uncomfortable
- Saying once in a while is not a problem but doing it every time is an issue
- **Focus on delivering the idea/helping the people that are listening to you**
- Don’t count your verbal tics
- Don’t search for bigger words than usual.
    - Don’t focus on using “utilize”, you can use “use”
    - Simple words can help you
    - Don’t memorize
- Verbal tics come up when you try to remember
- cheat-sheet are cool tools to avoid remembering
    - You can have a single sheet with big fonts
    - Write 3 or 4 words to help you remember/focus on the point
- Video → Record yourself → Help you to improve a lot
- Notice the problem → Be aware of that → Start working on that
- Ask:
    - What do you remember?
    - What do you like?
    - Anything stand up that you think I can improve?
    
I covered all the sections I was interested in. Next time, I will choose another course.
