### ISSUE TITLE
Handle `undefined` experiment ID and error cases in Experiment service endpoint

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30652]
### Problem Statement

The Experiment service endpoint currently doesn't properly handle cases where the experiment ID is undefined or when encountering HTTP errors (400, 500). This can lead to unexpected behavior in the application when these edge cases occur.

### Steps to Reproduce

- Go to Edit Page
- No experiments configured
- Check the Network and see the request 400

![CleanShot 2024-11-13 at 16 01 19@2x](https://github.com/user-attachments/assets/9e90c2ba-21f7-4a3c-93d9-9afbacf3d5e0)

### Acceptance Criteria

- Service returns `undefined` when the experiment ID parameter is `undefined`
- Service returns `undefined` when receiving HTTP 400 errors
- Service returns `undefined` when receiving HTTP 500 errors
- Existing functionality remains intact for valid experiment IDs
- Changes are implemented at the service layer to ensure proper configuration handling

### dotCMS Version

master

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_66d49c2**, Docker, macOS 14.5, FF v126.0.1
