### ISSUE TITLE
Issue: Job Monitoring Stops in All Tabs When One Tab is Closed

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30665]
### Parent Issue

https://github.com/dotCMS/core/issues/29498

### Problem Statement

There is an issue with the job monitoring feature. When multiple browser tabs are opened to monitor the progress of the same job, all tabs display the job progress correctly. However, if one of the tabs is closed, monitoring stops in all remaining tabs. The following error is logged when this occurs:

14:48:34.607 ERROR job.JobQueueResource - Error writing SSE event
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:309) ~[?:?]
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:271) ~[?:?]
	...

### Steps to Reproduce

	1.	Open multiple browser tabs to monitor the progress of a single job.
	2.	Observe that the job progress is displayed correctly in all tabs.
	3.	Close one of the tabs monitoring the same job.
	4.	Notice that all remaining tabs stop monitoring the job, and the above error is logged in the server logs.

### Acceptance Criteria

closing one tab shouldn't stop the other 

### dotCMS Version

current main

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/30665

**Comment by fabrizzio-dotCMS** [comment]
Looks good
