### ISSUE TITLE
Enable Reloadable Config Properties for Analytics and dotAI Apps

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#30673]
### User Story
As a software engineer, I want to identify all the places in the code for Analytics and dotAI Apps where Config properties are being used in a way they cannot be reloaded through the "System Tables" feature. After identifying those, I want to make the necessary changes to ensure those properties are reloadable, avoiding caching them in final variables (instance or static).

### Acceptance Criteria
- A comprehensive list of all instances where Config properties are improperly cached and cannot be reloaded through "System Tables."
- Refactored code to ensure all identified Config properties are reloadable.
- Validation to confirm properties are correctly reloaded using the "System Tables" feature.
- Documentation updated to reflect the changes.

### dotCMS Version
master

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
- Access to the current Analytics and dotAI Apps codebase.
- Understanding of the expected behavior of Config properties when reloaded through "System Tables."
- Knowledge of the impact of caching on Config property reload functionality.

### Quality Assurance Notes & Workarounds
- Ensure thorough testing of all changes to validate Config properties' reload functionality.
- Monitor for any unintended side effects on existing features due to refactoring.

### Sub-Tasks & Estimates
1. **Review Analytics Codebase** – 4 hours  
2. **Review dotAI Apps Codebase** – 4 hours  
3. **Identify Non-Reloadable Config Properties** – 2 hours  
4. **Refactor Code to Avoid Final Variable Caching** – 8 hours  
5. **Validate Changes Using "System Tables" Feature** – 4 hours  
6. **Document Changes and Update Codebase** – 2 hours  
7. **Peer Review and Approval** – 2 hours

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_c0e2992489b8`

Setting up the `Analytics Integration` app fails until the `DOT_ANALYTICS_IDP_URL` property is set via the `Config Overrides` portlet, as expected.

Keep in mind that you must NOT already have the `DOT_ANALYTICS_IDP_URL` set in your `docker-compose.yml` file before starting your tests. Otherwise, you'll never get the expected error message that Victor mentioned.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_396487e**, Docker, macOS 14.5, FF v126.0.1
