### ISSUE TITLE
Allow TimedCacheProvider to take per object TTLs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30670]
### User Story

We have a timed cache provider that allows us to set a group TTL.  When we want to build a cache that uses a per object TTL, we have to write some nasty code to work around this fact - and do things like have wrapper object and cleanup threads to remove stale entries.  This is important for things like the `blockdirectivecache` and the Page cache, where each object has a specific TTL.

### Acceptance Criteria

Allow networked caches to have a specific TTL per object.

### Steps to Reproduce

* Create a test HTML Page: `/set-variable`, and set its Cache TTL to zero.
* Add a Contentlet of type `Code Snippet` to it, with the following code, which will store the `foo` entry to the Dynamic Cache for a period of 10 seconds:
```vtl
<h1>Adding entry to the dot cache</h1>
<p>
    $dotcache.put("foo", "bar", 10)
</p>
```
* Create another test HTML Page: `/get-variable`, and set its Cache TTL to zero as well.
* Add a Contentlet of type `Code Snippet` to it, with the following code, which will read the value of the `foo` entry:
```vtl
<h1>Retrieving cached entry</h1>
<p>
    Entry value = $dotcache.get("foo")
</p>
```
* In the front-end, open up the `/set-variable` page.
* In another tab, open up the `/get-variable` page. It must display the value of the `foo` variable: `bar`.
* Now, wait for more than 10 second, and refresh the `/get-variable` page. You should get the Velocity code now instead of the variables value.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
- Docker Image: `trunk_eaa0f2e`

The `CaffineCache` is now using the `DynamicTTLCache` for providing per object TTL entries now, as expected. This is what the `Settings > Maintenance > CACHE > Cache Stats` looked like before the change -- notice the `Timed Cache Provider Section` there:

<img width="1395" alt="before" src="https://github.com/user-attachments/assets/ba87b907-f566-4f3e-9a04-e4dc6eb68c5c">

And this is what it looks like now:

<img width="1338" alt="after" src="https://github.com/user-attachments/assets/a38583d2-8701-474d-9862-243fe7a50952">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_68612b9**, Docker, macOS 14.5, FF v126.0.1

**Comment by wezell** [comment]
This commit unified  the `TimedCacheProvider` with the `CaffineCache`.  In new installs, you will only see `CaffineCache` in your cache region list and if the region is configured to have an expiry time, it will show there.
