### ISSUE TITLE
Add the folder ID to the endpoint /api/v1/folder/byPath

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30699]
### Parent Issue

https://github.com/dotCMS/core/issues/29873

### User Story

Add the folder ID to the endpoint` /api/v1/folder/byPath`. Currently, this endpoint responds with the following structure:

![Screenshot 2024-11-19 at 10 35 36 AM](https://github.com/user-attachments/assets/5d6eaf83-7669-4878-9d07-0bf0db7fdc2e)

However, users need the folder ID to retrieve more information about a specific folder.

### Acceptance Criteria

Include the folder ID in the response of the endpoint `/api/v1/folder/byPath` for each entity.

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by hmoreras** [comment]
pass internal QA: 

The endpoint now has an id. 

<img width="777" alt="image" src="https://github.com/user-attachments/assets/1fe42112-18c6-4988-b2f6-95a78e1e6377">

**Comment by bryanboza** [comment]
Fixed, passed according to the postman test: 
![Image](https://github.com/user-attachments/assets/6030651d-c518-45f4-9d07-3949ac46fd8f)
