### ISSUE TITLE
Create IIFE Library for PageView Tracking and DotCMS Event Transmission

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30711]
### User Story

As a developer, I want to have a configurable IIFE library for tracking page views and sending events to DotCMS, so I can easily implement analytics tracking across different DotCMS sites with custom authentication tokens and settings.

### Acceptance Criteria

- Create an IIFE library that automatically executes when loaded
- Implement required configuration options:
  - Authentication token
  - Endpoint Sever URL (optional, with default)
  - Event sent to `/api/v1/analytics/content/event`
  - Custom event properties
  - Tracking options (enable/disable specific features)
- Implement pageview tracking functionality (`PAGE_REQUEST`)
- Include event transmission capability to DotCMS
- Provide minified and ~~unminified~~ versions of the library
- Include documentation for implementation and usage
- Support common browser environments
- Handle error cases gracefully
- Provide callback options for success/failure of event transmission

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

- DotCMS API endpoint for event reception must be available and documented
- Browser compatibility requirements need to be defined (IE11+, modern browsers)
- Event structure and payload format should be specified
- Token generation and management process must comes from the Analytics APP

**Comment by oidacra** [comment]
Tested by @jdotcms the issue of auto-inject

**Comment by jdotcms** [comment]
I have tested the injection and it is generating the event
