### ISSUE TITLE
Experiments: Content not listed in variants when adding new content to the same variant

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30727]
### Problem Statement

When users create content for a specific variant in dotCMS, it does not appear in the list when attempting to add a new piece of content to the same variant. This issue disrupts the content creation and management process, making it difficult to verify or reuse existing content within the same variant. This affects content creators who rely on variant-based workflows and need visibility into existing content to ensure consistency and completeness.

https://github.com/user-attachments/assets/2344fc0a-9309-4308-bea8-f02114d3faed

### Steps to Reproduce

- Log into the dotCMS backend.
- Navigate to a variant in the content management interface.
- Create a new piece of content for that variant.
- Attempt to add another piece of content to the same variant.
- Observe that the previously created content is not listed or available for selection.

### Acceptance Criteria

- Ensure that all content created for a specific variant is listed and available when adding new content to the same variant.
- Verify that the listing is updated in real-time or upon refresh after content creation.

### dotCMS Version

Tested on main // Docker // FF

**Comment by bryanboza** [comment]
**Note for IQA:** Make sure the case exist in: https://github.com/dotCMS/core/blob/main/docs/test-cases/Experiments.csv if not please add a new line.

**Comment by zJaaal** [comment]
## IQA Passed

Now we are listing the content correctly

DotCMS Docker Image: `[dotcms/dotcms:trunk_82ddbb0]`

### Screenshot 

https://github.com/user-attachments/assets/47d28b21-b00e-49f5-a87e-72a4968858e2
