### ISSUE TITLE
Error publishing a page from variant editing: "Bad request error"

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#30726]
### Problem Statement

When attempting to publish a page from the variant editing interface, users encounter a Bad request error. The error message indicates that the content is not in a new, live, or working version, and as a result, the page cannot be published. This issue disrupts workflows for content creators and administrators who rely on variant editing for managing and publishing pages. It prevents the successful publication of pages, impacting website updates and user experience.

![image](https://github.com/user-attachments/assets/ffc2cf96-ec5e-4926-a703-beaf39c7d19f)

### Steps to Reproduce

- Log into the dotCMS backend.
- Navigate to the Variant Editing section.
- Edit an existing page variant.
- Attempt to publish the page from the variant editing interface.
- Observe the error message

### Acceptance Criteria

Ensure that pages can be successfully published from the variant editing interface without encountering the error.

### dotCMS Version

Tested on the latest agile release // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by zJaaal** [comment]
## IQA Passed

Now we are hiding the button when editing variants on the old toolbar

For architectural reasons, we couldn't add this fix on the new toolbar, but we will address this behavior in this ticket https://github.com/dotCMS/core/issues/30940 

We are still on development phase and this must be addressed before releasing the new toolbar.

DotCMS Docker Image: `[dotcms/dotcms:trunk_01742fb]`

## Screenshot
https://github.com/user-attachments/assets/b08ddc3f-2b08-414d-9f51-7c1f6dfe1d63
