### ISSUE TITLE
Company information doesn't show in comapny field after the relogin

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#30731]
### Problem Statement

When adding the company information in User Additional details (User > Select User >Additional Info ) so it shows there but when user logout and re-login the company has lost even though the value exists in database.

### Steps to Reproduce

This is easily reproducible when using the wrong starter file, so dotCMS will use the default starter that doesn't have files; however, @erickgonzalez also ran a few tests to verify that.

1. Start a new dotCMS docker image with the wrong starter/empty starter
2. Go to User > Select User >Additional Info and add company information
3. Logout
4. Login and you will not see the company information even though the value exists in database
5. This only happens after logout.

### Acceptance Criteria

The company should show regardless of starter and re-login of user

### dotCMS Version

22.03.15 and above 24.11.14

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28541

**Comment by dsolistorres** [comment]
Internal QA Approved:
- The company information field for the user is shown after logout and login again into dotCMS.
