### ISSUE TITLE
FTM: New Toolbar - Implement Preview Button and Preview Toolbar

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30739]
### Parent Issue

https://github.com/dotCMS/core/issues/30598

### Task

Implement the Preview Button functionality and its associated Preview Toolbar mode in the new UVE Toolbar. This implementation involves creating a distinct preview mode state, managing toolbar transitions, and handling specific UI restrictions for the preview mode.

### Proposed Objective

Create a seamless preview mode experience that allows users to view their content without editing capabilities, while maintaining essential viewing tools (language and persona selectors). The preview mode should be accessible both through the Preview Button and URL parameters.

### Technical Overview

The Preview mode introduces several key changes to the UVE interface:
- Transitions the main toolbar to a simplified Preview Toolbar
- Disables editing capabilities
- Maintains language and persona selection functionality
- Introduces a new "Back to Edit Mode" button
- Handles preview mode state through both UI interaction and URL parameters

#### Preview Button Implementation
- Add Preview Button to the main toolbar following Figma designs
- Implement click handler to transition to preview mode
- Update store to track preview mode state
- Handle preview mode URL parameter (`preview=true`) on page load

#### Preview Toolbar Implementation
- Create new Preview Toolbar component that replaces main toolbar in preview mode
- Maintain Language and Persona selectors in Preview Toolbar
- Implement "Back to Edit Mode" button with proper styling
- Ensure smooth transition between regular and preview toolbars

#### Store Modifications
- Add preview mode state management to `newWithEditorToolbar()`
- Implement actions and reducers for preview mode toggle
- Create selectors to check preview mode status
- Handle persistence of preview mode state

#### Preview Mode Restrictions
- Disable and hide the following features in preview mode:
  - UVE Contentlet Palette
  - Contentlet editing tools
  - Inline editing capabilities
  - Any other editing-related functionality

#### URL Parameter Handling
- Implement logic to check for preview mode URL parameter on page load
- Update URL when entering/exiting preview mode
- Maintain other necessary URL parameters (language, persona, etc.)
- Handle proper state initialization based on URL parameters

#### Testing Requirements
- Verify preview mode activation through button click
- Test preview mode activation through URL parameters
- Ensure proper disabling of all editing features
- Test transitions between edit and preview modes
- Verify URL parameter handling and persistence
- Test across both traditional and headless pages

### Additional Considerations
- Ensure smooth animations during toolbar transitions
- Maintain proper state restoration when exiting preview mode
- Handle edge cases (e.g., invalid URL parameters)
- Consider implementing proper error handling
- Document any new store methods or state changes

### Preview Toolbar Design

In the New UVE Toolbar, this button is the trigger

![Screenshot 2024-11-24 at 9 52 13 PM](https://github.com/user-attachments/assets/136e66fa-c792-40d1-b5fa-42d335149923)

And this is the toolbar to render

![Screenshot 2024-11-21 at 11 06 01 AM](https://github.com/user-attachments/assets/220143fb-99b8-4d21-a0e1-1fc23df257f3)

### Acceptance Criteria
- Clicking the trigger button should render the Preview Mode Toolbar.
- The user can access Preview Mode via a URL that includes the previewMode=true query parameter.
- While in Preview Mode, the contentlet palette and contentlet tools must be hidden, and the page should not be editable in any way.
- There should be a smooth animation when activating Preview Mode (by clicking the trigger button) and when switching between different screen resolutions.

### Resources:

[Figma component link ](https://www.figma.com/design/trbwjLuf5F6KaU1rFucNeg/Edit-Page---UVE?node-id=3488-91193&t=NzkOkm8dmgPRP0Ya-4)

**Comment by zJaaal** [comment]
## IQA Failed 

We forgot to disable editing capabilities 

DotCMS Docker Image: `[dotcms/dotcms:trunk_b40d2e6]`

## Screenshot

https://github.com/user-attachments/assets/a0997f93-b748-41e7-ba1d-12bd355a5515

**Comment by zJaaal** [comment]
# IQA Passed

Now it hides all the tooling when going to preview mode

DotCMS Docker Image: `[dotcms/dotcms:trunk_d67b5fd]`

## Screenshot

https://github.com/user-attachments/assets/28d4ab14-f05a-4f2f-9258-9557bd5c7f4e
