### ISSUE TITLE
FTM: New UVE Toolbar - Implement "Copy URL" button

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30732]
### Parent Issue

https://github.com/dotCMS/core/issues/30598

### Task

Implement the logic for the "Copy URL" button in the new UVE Toolbar component. This task involves modifying (if necessary) store logic for the `newWithEditorToolbar()` feature store, reusing existing copy URL functionality where possible.

### Proposed Objective

Add the "Copy URL" button logic to the new toolbar and ensure it functions correctly under the feature flag, maintaining consistency with the existing copy URL functionality.

### Acceptance Criteria

- Ensure the "Copy URL" button functions correctly and integrates seamlessly with the new toolbar, in traditional and headless pages
- The behaviour of the current "Copy URL" button should not be affected

**Comment by zJaaal** [comment]
## IQA Passed

It's working as expected, the `Cannot GET /index` error is related to the dev proxy we use. So it's not an issue.

DotCMS Docker Image: `[dotcms/dotcms:trunk_a343172]`

### Screenshot

https://github.com/user-attachments/assets/4f69898e-d029-4bce-89bd-94e4f6cbaaf3
