### ISSUE TITLE
FTM: New UVE Toolbar - Implement Language selector

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30735]
### Parent Issue

https://github.com/dotCMS/core/issues/30598

### Task

Adapt the existing Language Selector component for the new UVE Toolbar, maintaining its current functionality and interactions. This task involves adapting the `newWithEditorToolbar()` 

### Proposed Objective

Successfully integrate the Language Selector into the new toolba while preserving all existing functionality across both traditional and headless pages.

### Acceptance Criteria

- Ensure all existing Language Selector functionality remains intact:
  - Language switching
  - Language list display
  - Current language indication
- Verify the component works correctly in both traditional and headless pages.
- Maintain backwards compatibility so the old design continues to work in other parts of the application.

**Comment by KevinDavilaDotCMS** [comment]
### Notes to IQA

For this ticket you need to activate the following Feature Flag: `FEATURE_FLAG_UVE_PREVIEW_MODE`

And test the functionalities from the new toolbar in traditional and headless pages

**Comment by zJaaal** [comment]
# IQA Passed 

Language selector work as expected

DotCMS Docker Image: `[dotcms/dotcms:trunk_632b9af]`

## Screenshot

https://github.com/user-attachments/assets/4df373e2-1672-4352-943b-a8175a775791


https://github.com/user-attachments/assets/8b57be32-99bb-4ca3-b6b8-bbe4591cc38f
