### ISSUE TITLE
pg_dump fails when passwords are complex

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30743]
### Problem Statement

Support is asked once a week to create backups for customers.  We have this functionality in the back end but it can fail in some cases.  

This is because the `pg_dump` functionality under the covers creates a url connection to a postgres database and it fails when there are special characters that need to be encoded to be used in a url - for example when a password contains a special characters like these `:/+%&` .

You can see this breaking in the backend of the new headless site.

This is the same issue as we had with the old pubsub connection #21363

### Steps to Reproduce

Create a database user with a password that contains characters like these `:/+%&` and then try to use the db dump function in  the Maintenance > Tools screen in dotCMS.  These characters need to be escaped.

### Acceptance Criteria

We should be able to dump databases with aplomb!

### Steps to Reproduce

* Start dotCMS with the Empty Starter.
* Go to the `System > Maintenance > TOOLS` portlet, inside the `Export dotCMS Content` section, and click the `Download DB Dump.
* A .GZ file will be downloaded, with a name similar to this one: `default_db_2024-11-22_08-49-29.sql.gz`
* Try to un-compress it, you'll get an error indicating that the file is unable to be expanded.

### dotCMS Version

23.x+

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_eaa0f2e`

The generated dump file can be un-compressed without problem now, exposing the plain .SQL file.

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_4f46e9e**, Docker, macOS 14.5, FF v126.0.1
