### ISSUE TITLE
Rafael: Drop Everything & Learn Dec 04 - Dec 17

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30755]

**Comment by rjvelazco** [comment]
# Smart Time Management (Productivity)

- Smart Time Management (Productivity) [Smart Time Management (Productivity)](https://dotcms.udemy.com/course/timemanagement/learn/lecture/22842595#overview)

## Filter Tasks

- You decide where you spend your time
- It is much more important **WHAT YOU DO**, than **HOW YOU DO IT**

[Temporary+Shopping+Cart.pdf](https://prod-files-secure.s3.us-west-2.amazonaws.com/d82ffd8c-ba53-4f36-be6b-b4d1c0ccdd0f/5cc40d32-7030-4229-bf65-75678b802809/Temporary+Shopping+Cart.pdf)

## **Wheel Life**

- Define your Wheel of Life
- Be very honest
- Define how you want to see yourself in 5 years
- Do it annually

[Wheel+of+life.pdf](https://prod-files-secure.s3.us-west-2.amazonaws.com/d82ffd8c-ba53-4f36-be6b-b4d1c0ccdd0f/aa08a7fd-6dd1-4799-9d10-64208d5efefb/Wheeloflife.pdf)

## **Reflection on time**
Active Minutes per day: **960 min**

- Time is more valuable than money, however we take more care of money than time
- Thinking of time as money helps to better manage time life
[¿En+qué+invierto+mi+tiempo_.pdf](https://github.com/user-attachments/files/18155464/En%2Bque%2Binvierto%2Bmi%2Btiempo_.pdf)

The course is in Spanish - sadly -. In case you want to do the activities, all the PDFs are in Spanish :c

**Comment by rjvelazco** [comment]
Really cool phrase:

> "The brain is for generating ideas, not for remembering tasks"

**Comment by nollymar** [comment]
Pretty interesting course Rafa. I was trying to add it to my Udemy Learning Path but apparently it isn't part of Udemy Business :/
