### ISSUE TITLE
Rule without https scheme redirects to empty location

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#30774]
### Problem Statement

Rules using **Redriect Requests To** redirect matched URLs to an empty location

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/66ae127c-4406-4cdd-b969-9ddc8513ba65)

Check with CURL

curl -l -s --head https://demo.dotcms.com                                                                                                                                        
HTTP/2 302
date: Tue, 26 Nov 2024 14:15:29 GMT
strict-transport-security: max-age=3600;includeSubDomains
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-dot-server: faa692a35a57|ad316e3cdf
x-dot-sendredirectruleaction: true
location:

The page shows blank

![image](https://github.com/user-attachments/assets/4fdb84b0-859d-47ae-9d12-c966946d4c2c)

### Acceptance Criteria

The redirect rule should redirect to https by default if the scheme wasn't provided while creating the rule.weren't

### dotCMS Version

All

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/30078

https://dotcms.freshdesk.com/a/tickets/28636

**Comment by wezell** [comment]
I hadn't looked.  Seems right Erick.

**Comment by prestonso** [comment]
Works as designed. Closing! Thanks @erickgonzalez
