### ISSUE TITLE
UVE: Show "Create New Language Version" Dialog Before Updating Query Params

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#30772]
### Parent Issue

N/A

### Task

Show the "Create New Language Version" dialog when the user clicks on a language where the page does not exist. This will allow us to show the dialog before updating the query parameters, as we do right now, and avoid triggering an unnecessary request if the user chooses not to create the new language version.

### Video

https://github.com/user-attachments/assets/6263d4f5-dda7-4ead-810f-333c1459fdfd

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- Detect when the user clicks on a language where the page does not exist.
- Show the "Create New Language Version" dialog before updating the query parameters.
- Ensure that the dialog allows the user to confirm or cancel the creation of the new language version.
- If the user confirms, proceed with updating the query parameters.
- If the user cancels, do not update the query parameters and avoid triggering the unnecessary request.
- Verify that the application functions correctly after the changes.
- Ensure that all unit tests pass successfully.

**Comment by rjvelazco** [comment]
I think we can implement this in the new toolbar @zJaaal @kevindaviladev

**Comment by KevinDavilaDotCMS** [comment]
This task is closed in the resolution of: https://github.com/dotCMS/core/issues/30735

**Comment by zJaaal** [comment]
# IQA Passed 

It's working as expected. I found an issue while testing this, but I don't think is related to this changes. I created a ticket to work on it https://github.com/dotCMS/core/issues/30878

DotCMS Docker Image: `[dotcms/dotcms:trunk_632b9af]`

## Screenshot

https://github.com/user-attachments/assets/d46b5cd0-2b46-47c5-8720-d0dd7f368ca8
