### ISSUE TITLE
Start up a clustered DotCMS with shared sessions and supporting services on a local development machine using helm

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#30788]
Developers need a way to test the behavior of the DocCMS server when running in a cluster locally without relying on remote shared infrastructure or services.   When developing code to support and fix issues with scaling and upgrade of the server images, quick turnaround is required.   Currently changes cannot be tested easily.   We do have an example docker-compose but this does not match the structure in production that uses k8s and cannot easily be templated with different combinations of features and default configurations.

In this task we will attempt to create a Helm chart that closely replicates the behavior and k8s templates we use in production but uses its own supporting services instead of relying on aws. 

1. Chart can be easily installed with appropriate defaults without needing to understand all the internals
2. Closely replicates the configuration we use in our production environments
3. Can modify the number of replicas
4. Can modify/upgrade the specific docker image versions
5. Developer can easily override and run with different environment variables/feature flags
6. Should be repeatable with the minimum of options a developer needs to start up with the image they want to test.

This should be treated as a prototype initially to demonstrate the benefits of this approach and is focused on providing capabilities to the developer for testing in its first iteration.  Not all parameters need to be templated or for this to work as a production helm chart initially, but it should provide the framework for us to expand upon this into the next phases e.g. creating an init container to upgrade the DB.   

1. Can start up with current realease DotCMS image
2. Can start up with local built 1.0.0-SNAPSHOT image
3. Can update the image and "helm upgrade"
4. Supporting services, db, opensearch, and redis are started and available before DotCMS
5. Same probes for DotCMS are enabled as we use in production.

Finding an issue with the startup or upgrade of DotCMS is a success in this task as it provides a baseline for us to go on and resolve.   This task is not to fix those issues found to end up with a fully working instance,   if we are unable to start up more than one replica because of conflicts or timing, that is important information for us to move forward.

We can use the analytics helm charts as a guide in creation.

**Comment by sfreudenthaler** [comment]
consider gathering feedback coming in in another follow up itteration

**Comment by dcolina** [comment]
The task to create a Helm chart for setting up a local dotCMS environment along with its ecosystem (DB, OpenSearch, Redis) has been completed for the first iteration. A helper script was developed to configure the prerequisites, including tools, a Kubernetes cluster via Docker Desktop, ingress, and TLS certificates.

The progress and results have been recorded, and the video is attached for reference.

https://github.com/user-attachments/assets/10af5185-214a-4a3f-b213-e0e548dc9544
