### ISSUE TITLE
We need to add publishDate param to GraphQL.

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30780]
### Parent Issue

https://github.com/dotCMS/core/issues/30552

### User Story

any change we make in the PageAPI must also be supported in GQL. 
Given that we recently added the publish-date, aka time-machine date to the PageResource 
We need to reflect these new capabilities on Graph QLpublish date

### Acceptance Criteria

Whatever new capability is supported by the introduction of the new publishDate param must also be supported by GraphQL

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by fmontes** [comment]
https://github.com/user-attachments/assets/0253e7cd-f641-41dd-98f2-ac201a3f4ba8

**Comment by fabrizzio-dotCMS** [comment]
Actual effort updated to 5 because of the Karate-test learning curve
