### ISSUE TITLE
[Relationship Field] : Expose REST Endpoint that returns fields that meet specific criteria

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#30796]
### Parent Issue

* #30495

### User Story

As a dotCMS developer, I want to be able to retrieve Fields from a Content Type that meet a specific list of criteria, so I can display the appropriate fields in the UI for Content Authors to deal with them. Such criteria can be related to can be, but not restricted to:

* Required
* User Searchable
* System Indexed
* Show in List
* Unique

### Acceptance Criteria

For this particular case, we need to be able to return all fields from a Content Type that are flagged as `User Searchable`.

However, in order to make this more generic, the new method in the REST Endpoint allows you to filter -- for the time being -- for fields that match the current 5 common attributes in a Field:

* Required.
* User Searchable.
* System Indexed.
* Show in List.
* Unique.

So, a GET request to the Endpoint looking for fields in a given Content Type with all of those options checked would look like this:
```
{{serverURL}}/api/v3/contenttype/{{typeIdOrInode}}/fields/allfields?filter=REQUIRED&filter=USER_SEARCHABLE&filter=SYSTEM_INDEXED&filter=SHOW_IN_LIST&filter=UNIQUE
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by nicobytes** [comment]
QA Notes:

I’ve created a content type with fields using the options to filter.

![Screenshot 2024-12-09 at 10 49 22 AM](https://github.com/user-attachments/assets/f5c111c9-a9d7-4640-8957-60ff472c72f6)

My tests:

REQUIRED: 3 fields ✅

![Screenshot 2024-12-09 at 10 51 38 AM](https://github.com/user-attachments/assets/0aaa71f7-3c23-4d7c-a053-703488da4390)

USER_SEARCHABLE: 2 fields ✅

![Screenshot 2024-12-09 at 10 52 23 AM](https://github.com/user-attachments/assets/db99f81e-de3e-4502-ab94-1538a33b37b2)

SYSTEM_INDEXED: 7 fields ✅

![Screenshot 2024-12-09 at 10 53 00 AM](https://github.com/user-attachments/assets/98aaae30-2cb6-4b1b-8be4-feb7d1994db1)

SHOW_IN_LIST: 2 fields ✅

![Screenshot 2024-12-09 at 10 53 44 AM](https://github.com/user-attachments/assets/c5828dca-e6ee-4cc7-8f4e-2e95a999c92f)

UNIQUE: 1 fields ✅

![Screenshot 2024-12-09 at 10 54 10 AM](https://github.com/user-attachments/assets/1eeef606-a69e-43af-8596-2188842db55f)

As a suggestion, each field should have a `fieldType` attribute.
