### ISSUE TITLE
Populate the unique_fields table when the Database validation is enabled

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30815]
### User Story

Currently, a TaskUpgrade is used to populate the table. However, if validation is disabled and later re-enabled, the TaskUpgrade will need to be executed again. To address this, we should ensure the table is repopulated every time validation is enabled. This requires detecting changes to the validation property and triggering the population logic accordingly.

Additionally, we need to enhance the existing logic (currently in the TaskUpgrade) with the following updates:

- Include the Variant.
- Add a boolean field to indicate whether the version is live. (Currently, only one version is being included.)
- Include a boolean field to store the value of the uniquePerSite field variable.

### Acceptance Criteria

Populate the unique_fields table every time the Data Base Unique Field Validation is enabled
Remove the Task241007CreateUniqueFieldsTable class

### Steps to Reproduce

* In your `docker-compose.yml` file, set the folowing env var:
```yml
DOT_FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION: true
```
* Start up dotCMS with the Full Starter.
  * Once it's up and running, connect to the database instance. In your terminal, you can run `docker ps` to get the name of the database Docker image, and then connect to it like this: `docker exec -it {{DOCKER-IMAGE-NAME}} /bin/bash`
* Get the total record count on the `unique_fields` table. You must get the following result:
```
dotcms=# select count(*) from unique_fields;
 count 
-------
   236
(1 row)
```
* Now, bring dotCMS down and disable the flag:
```yml
DOT_FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION: false
```
* Start dotCMS again and, when it's up and running, connect to the database instance and get the total count on the `unique_fields` table. You must get the following result:
```
dotcms=# select count(*) from unique_fields;
ERROR:  relation "unique_fields" does not exist
LINE 1: select count(*) from unique_fields;
```
* Re-enable the flag, start dotCMS, and make sure that the `unique_fields` table is back again.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_b40d2e6`

The `unique_fields` table is created and deleted appropriately based on the value of the `DOT_FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION` feature flag.

**Comment by bryanboza** [comment]
Fixed, tested on main // Docker // FF
