### ISSUE TITLE
Create Custom Hook for Page View Content Analytics Integration

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30820]
### Parent Issue
https://github.com/dotCMS/core/issues/30711

### Task
Implement a custom React Hook to handle Page View tracking through the Content Analytics system. This hook will use the SDK Dot Analytics library to send page view events to the analytics endpoint.

The hook will be responsible for:
- Capturing page view events
- Formatting the analytics payload according to the established schema
- Sending the event data to the Content Analytics
- Handling the integration with the existing analytics library class

```
{
   "type":"track",
   "key":"...",
   "event_type":"PAGE_REQUEST",
     ...
   "source":"headless",
}
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 2 - Important

### Acceptance Criteria
1. Create a custom React Hook that implements page view tracking
2. Ensure the hook properly formats the event data following the existing schema:
   - Include all required fields (type, key, event_type, timestamps, etc.)
   - Maintain the correct data structure for page-specific information
   - Set the proper source identifier for the headless library
3. Integration with the existing analytics library class
4. Events must be properly distinguished through the Event Source property
5. Implement proper TypeScript types for the hook parameters and return values

### External Links
N/A

### Assumptions & Initiation Needs
- The existing analytics library class is available and functioning
- Access to the analytics endpoint is configured and available
- The event schema is finalized and documented

### QA Notes & Workarounds
Test cases should verify:
- Proper event formatting
- Correct event source identification
- Integration with the existing analytics library
- Event transmission success

**Comment by oidacra** [comment]
QA Steps:
1. Go to the repo folder core-web, build the project of the new library `npx nx build sdk-analytics`
![Image](https://github.com/user-attachments/assets/bf4d28d3-73a7-4a83-968c-d1a38a9852ba)

2. Use link to fake use the library as we install the lib in the normal way
- Go to `core-web/dist/libs/sdk/sdk-analytics/`
- link, `npm link`

3. Go to /examples/nextjs/
- install all the libs. `npm i`
- Link the library, `npm link "@dotcms/analytics"`

With this steps, you can use the library like you install it by npm in the example of nextjs

**Comment by nicobytes** [comment]
Page View Event ✅

<img width="722" alt="Screenshot 2024-12-23 at 12 41 25 PM" src="https://github.com/user-attachments/assets/ef69576b-55e3-4cf3-b870-ba71839a1014" />

Track Click Event ✅

<img width="739" alt="Screenshot 2024-12-23 at 12 42 47 PM" src="https://github.com/user-attachments/assets/0e8d5dd2-ad86-4f17-8733-ac5063d5e34c" />

Page request event ✅

<img width="803" alt="Screenshot 2024-12-23 at 12 43 16 PM" src="https://github.com/user-attachments/assets/fb5a77ae-f15f-4919-9092-4e8105d2c7c7" />
