### ISSUE TITLE
Rest API: Improve error handling for 415 – Unsupported Media Type

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#30828]
### Problem Statement

Currently, when a REST endpoint is annotated with `@Consumes(multipart/form-data)` and a request is made with an incorrect `Content-Type` header, the server returns a `415 – Unsupported Media Type` status. However, the response is in HTML format instead of JSON.

An example of the HTML response is as follows:

```html
<!doctype html><html lang="en"><head><title>HTTP Status 415 – Unsupported Media Type</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 415 – Unsupported Media Type</h1></body></html>
```

This behavior is inconsistent with the error handling across the application, where JSON responses are used to provide meaningful error messages.

The objective is to align this behavior by returning a JSON response with a clear and concise error message.
### Steps to Reproduce

1. Make a request to any REST endpoint annotated with `@Consumes(multipart/form-data).`
2. Set an incorrect `Content-Type` header in the request.
3. Observe the returned `415 – Unsupported Media Type` response in HTML format.

### Acceptance Criteria

- The 415 – Unsupported Media Type error should return a JSON response instead of HTML.
- The JSON response must include a clear and user-friendly error message explaining the issue.
- The error handling should align with the existing standards used across the application.

### dotCMS Version

`dotcms/dotcms:trunk_a343172`

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
### Internal QA: Needs work

We should add the 415 response in the API Playground (only in those endpoints that already have a Swagger Doc)

**Comment by zJaaal** [comment]
## IQA Failed 

Although documentation is appearing in API Playground. We have some issues on the content import API, it is not faling for invalid `Content-Type` values

DotCMS Docker Image: `[dotcms/dotcms:trunk_489be3e]`

### Screenshots

#### `api/v1/content/_import/_validate`

https://github.com/user-attachments/assets/1bb070c1-9f41-4f27-9e6f-f1210a0a18b6

https://github.com/user-attachments/assets/1bcb57e8-6d5b-47ab-a2cc-afcee64f2a17

#### `api/v1/content/_import`

https://github.com/user-attachments/assets/71e33cb9-c88d-4772-a375-979617adf14c

**Comment by zJaaal** [comment]
## IQA Passed

Yes @valentinogiardino you were right after setting off the hidden Header for `Content-Type` and let postman use the wrong one I manually set, we can see the 415 Error in the response.

https://github.com/user-attachments/assets/44ba2dc3-9afe-4c0c-a967-c827625f8f35


cc: @nollymar
