### ISSUE TITLE
Relationship Field: Listing Content with Dynamic Columns 

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30923]
### Parent Issue:

https://github.com/dotCMS/core/issues/30495

## User Story:

As a user, I want to view related content in a dialog when browsing through items, so that I can explore additional resources without leaving my current page.

![Screenshot 2024-12-11 at 3 39 33 PM](https://github.com/user-attachments/assets/cc6dee96-eb71-4f33-9fc3-2b0bdc0aff8c)

### 1. Dynamic Columns

- The mandatory columns are: Type, Title, Step, and Language.
- The columns displayed in the dialog should be fetched dynamically based on the content type.
- Use the `/api/v3/contenttype/<id>/fields/allfields?filter=SHOW_IN_LIST` endpoint to retrieve the fields to be displayed.
- The response should determine which fields (e.g., Title, Type, URL, Publish Date) appear as columns in the dialog.

### 2. Content Display

- Utilize the `/api/content/_search` endpoint to retrieve content dynamically.
- The dialog should display a list of related content items, dynamically binding the retrieved fields to the corresponding columns.
- The display should include thumbnails for items where applicable.
- When there are many columns, implement horizontal scrolling, ensuring the checkbox and button columns are sticky for better usability.

### 3. Error Handling

- If there is no related content, the dialog should display a user-friendly message (e.g., "No related content available.").
- If content fails to load due to a technical error, a retry option should be provided.

**Comment by nicobytes** [comment]
QA Notes:

1. A relationship without any associated content or data.

https://github.com/user-attachments/assets/62661c3b-551b-4d08-924f-b63e77e1a7fd

2. Show related content fields based on “Show in List”

https://github.com/user-attachments/assets/b4c48d9c-e83e-497b-adf5-0a542b34b23d

3. Display the title as the ID when no text field is available.

https://github.com/user-attachments/assets/0b2b2a8f-3037-47f0-a009-26d1c0f44b21

4. Manage multiple fields using horizontal scrolling and sticky columns

https://github.com/user-attachments/assets/9bcd6556-e903-47cc-9e3c-7fe0f149785f


Note: This feature does not include functionalities like pagination, rendering special fields such as ‘step,’ searching, or sorting. It only displays the content with dynamic columns.

**Comment by oidacra** [comment]
IQA Passed:
1. A relationship without any associated content or data. ✅
2. Show related content fields based on “Show in List” ✅
3. Display the title as the ID when no text field is available. ✅
4. Manage multiple fields using horizontal scrolling and sticky columns ✅
