### ISSUE TITLE
Relationship Field: Allow Choosing Content According to the Relationship

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#30928]
### Parent Issue

https://github.com/dotCMS/core/issues/30495

## User Story

As a user, I want to select content based on its relationship to other items, so that I can establish meaningful connections between content pieces without confusion.

![Screenshot 2024-12-11 at 3 53 18 PM](https://github.com/user-attachments/assets/d320b688-1803-4097-95f7-b52c5de7129f)

### 1. Button Behavior Based on Relationship Type

- **For 1-to-1 relationships:**
  - The "Existing Content" button should be disabled if the user has selected exactly one content item.
  - For 1-1  relationships, should the table allow the selection of a single content item using a radio button

- **For 1-to-n or n-to-n relationships:**
  - The "Relate" button should always be enabled, allowing multiple selections.
  - Ensure proper validation and handling for multiple content selections.

**Comment by nicobytes** [comment]
QA Notes:

Behavior

https://github.com/user-attachments/assets/0f99677c-2cf0-424d-a073-9e3c5371397f

Dialog height

<img width="1903" alt="Screenshot 2024-12-27 at 11 24 22 AM" src="https://github.com/user-attachments/assets/d31c9bba-c170-4e35-b2be-304f6cfe4a49" />

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: Work as expected

Note: The "New Content" option is not working but it is going to be work in another issue. also we need to disabled the "New Content" option when the relationship is one to one and you already have a item selected
