### ISSUE TITLE
API: Create a new version of the content on a second language

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#30950]
### Parent Issue

- #30371

### User Story

As a user, I want to create a new content in another language that is related to an existing content, so that I can have content available in multiple languages through the REST API of workflows.

### Acceptance Criteria

1. Develop functionality to create a new content version in a different language.
2. Ensure the new language version is linked to the original content.
3. Implement REST API endpoint to support multilingual content creation.
4. Validate that the relationship between original and translated content is maintained.
5. Provide a mechanism to specify the source language and target language.
6. Ensure that metadata and key attributes are preserved across language versions.
7. Implement proper error handling for language content creation.
8. Verify that the new language version can be retrieved and managed via the REST API.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

- Existing REST API workflow infrastructure is in place.
- Supported languages and their codes are predefined.
- Content model supports multilingual attributes.
- Translation process or mechanism is to be determined.

### Quality Assurance Notes & Workarounds

- Test content creation with various language combinations.
- Verify referential integrity between original and translated content.
- Check API responses for multilingual content operations.
- Validate that all required fields are properly handled during translation.

### Sub-Tasks & Estimates

*No response*

**Comment by jdotcms** [comment]
In order to test this issue, please see postman, the Workflow Resource Test / SavingOnDiffLanguageByActionId
it creates a French language
creates a content in english
and finally creates a content in french, but with the same id of the previous step

**Comment by freddyDOTCMS** [comment]
Needs Work: This case is not working propertly

- Create a ContentType named type_1 with 2 fields: title and secondField, both Text
- Create a couple of locales, French and Italian
- Create a new Contentlet from the Content Type created previously with: title: English; secondField: A
- Now create a new version of the Contentlet but for French, using the new Workflow
```

Method: PUT
URL: {dotcmsEndpoint}/api/v1/workflow/actions/ceca71a0-deee-4999-bd47-b01baa1bcfc8/fire?identifier={content identifier}&lang=1&indexPolicy=WAIT_FOR
body: 
{
    "contentlet":{        
        "identifier":"content Identifier",
        "languageId":"French Id",
        "contentType":"Type1",
        "title":"French",
        "secondField": "B",
        "contentHost":"default"
    }
}
```

- Now create a new version of the Contentlet but for Italian, using the new Workflow
```

Method: PUT
URL: {dotcmsEndpoint}/api/v1/workflow/actions/ceca71a0-deee-4999-bd47-b01baa1bcfc8/fire?identifier={content identifier}&lang={French Language Id}&indexPolicy=WAIT_FOR
body: 
{
    "contentlet":{        
        "identifier":"content Identifier",
        "languageId":"Italian Id",
        "contentType":"Type1",
        "title":"Italian",
        "contentHost":"default"
    }
}
```

The secondField value should be B because the original is the French version but it is A

**Comment by freddyDOTCMS** [comment]
Needs Work: 

- If you set a language that does not exists as target then you got a 500 HTTP response error and the message is not readable at all

```
{
    "message": "ERROR: insert or update on table \"contentlet\" violates foreign key constraint \"fk_contentlet_lang\"\n  Detail: Key (language_id)=(999999) is not present in table \"language\"."
}
```

- If you set the target language Id as "0" or something like "00000", then you got 200 and the Default language version got updated

- If you set a Contentlet that does not exists in the request body or the query parameter, you got a 400 HTTP Response and the not readable message
```

{
    "message": "The content (id da3a57919d33396651637b624a5b80ac, inode 9b4c3e44-5a3c-4ad0-950b-cbc0bbceeb3a, content type type_1) is not a new, live, or working version."
}
```

**Comment by jdotcms** [comment]
Looking at the feedback

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/31020/files) to fix the feedback

Note: on the postmans I have found a mistake, the query string is using lang=1 for setting the language id, it is "language" instead

**Comment by jdotcms** [comment]
Note1: now when trying to create a contentlet with a non existing language, it returns 400 bad request.
In addition the validation has been pushed on the validateContent on the ContentletAPI so any checkin with a non existing language will throw a DotState Exception

**Comment by freddyDOTCMS** [comment]
Need works

- this case is still happening https://github.com/dotCMS/core/issues/30950#issuecomment-2563943564
- Also this is happening too:

"If you set the target language Id as "0" or something like "00000", then you got 200 and the Default language version got updated"

**Comment by jdotcms** [comment]
> Note: on the postmans I have found a mistake, the query string is using lang=1 for setting the language id, it is "language" instead

After a research the feedback may be not valid:
1) the first case you have to use language instead of lang, I have already made a note to this situation on the this thread.
2) the second case happens, however after a lot of research, languageId = 0 is an special case:
any lang id <= 0, will be by default falls back to default language, usually 1, so wont throws an error, just switch to default language.

**Comment by freddyDOTCMS** [comment]
Pass internal QA works as expected according this comment https://github.com/dotCMS/core/issues/30950#issuecomment-2581203713
