### ISSUE TITLE
Files without an extension cannot be edited / saved

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#30982]
### Problem Statement

although a file without an extension can be uploaded, when you try to edit -> save, it will ask for it
this was raised in the context of an upgrade from 5.x -> 24.x; the customer edits their existing files
customer says that they want to be able to edit and save their actual files
I replicated this on the demo site

### Steps to Reproduce

- upload a file without an extension into dotCMS
- try editing the file
- it will return an error asking for an extension to be passed to the file

### Acceptance Criteria

files without extensions should be able to be saved

### dotCMS Version

24.12.10

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28937

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA

https://github.com/user-attachments/assets/e06db16e-5c4c-4204-8dcd-bfcd4b595885

**Comment by erickgonzalez** [comment]
Only for 24.04 and 24.12 LTSs.
