### ISSUE TITLE
UVE: Ensure Window Object Re-Initialization in UVE iframe

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#30981]
### Parent Issue

N/A

### Problem Statement

The window object in the UVE retains its state across page refreshes, resulting in a "dirty" state that preserves previous mutations.

### User Story
The client uses `Stencil` web components, which modify the window object during the registration of custom components. When `Stencil` registers these components, it adds specific HTML elements required for proper functionality.

**However, in the UVE:**

1. A page refresh reuses the same window object reference.
2. Stencil assumes the components are already registered and skips re-registering them.
3. This leads to missing HTML elements, causing the client's application to crash.

### Steps to Reproduce

1. Add the following code to a theme:
```html
<my-component></my-component>
<script>
    var randomKey = `debug_${Math.random().toString(36).substring(2, 15)}`;
    (window)[randomKey] = `Random value: ${Math.random()}`;
    console.log(`Random ${randomKey} property created at window level`);
    console.log("Check how many random properties you have: ", window);
</script>
<script>
    if (!window.customElements.get('my-component')) {
        console.log("Components haven't been registered - Stencil will trigger the register process");
    } else {
        console.log("Components have been registered In Previous Render- Stencil will not trigger the register process");
    }
</script>
<script type="module" src="https://unpkg.com/my-component-stencil-example-123@0.0.1/dist/my-component/my-component.esm.js"></script>
```
2. Add the theme to a page
3. Edit the page within the UVE.
4. Inspect the iframe’s window object.
5. Observe that registered components and random properties persist across refreshes.

### Video

https://github.com/user-attachments/assets/965dd983-c76d-4c78-a3ce-3d08a8553d77

### Acceptance Criteria

- [ ] The window object should be re-initialized each time the UVE refreshes.
- [ ] Stencil web components should be properly registered on every refresh.
- [ ] All necessary HTML elements should be added, avoiding application crashes.
- [ ] Testing should confirm no unwanted mutations persist in the window object across page refreshes.

### Additional Notes

This **issue** only occurs in **UVE** `traditional` mode due to the use of `iframe.write()` to update page content. 
**In headless mode**, this issue **does not happen** because data is sent through `postMessages`

### dotCMS Version

`latest`/`trunk`

### Proposed Objective

Customer Support

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

More information about the Support Ticket: https://dotcms.freshdesk.com/a/tickets/28953

**Comment by rjvelazco** [comment]
### Additional Notes

This **issue** only occurs in **UVE** `traditional` mode due to the use of `iframe.write()` to update page content. 
**In headless mode**, this issue **does not happen** because data is sent through `postMessages`

**Comment by dsolistorres** [comment]
Internal QA Approved:
- When editing the page with the UVE, window properties are reinitialized when the page is refreshed.
