### ISSUE TITLE
Add Support For SAML Relay State

### ISSUE THREAD

**Issue by weiyiwang-dotcms** [dotCMS/core#31016]
### User Story

As a dotCMS administrator, I want to allow users to login to dotCMS on the front-end via SAML without having backend access, so there can be true front-end users managed by SAML.

### Acceptance Criteria

Adjust dotCMS SAML implementation to support SAML relay state. 

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/27790
https://dotcms.slack.com/archives/CU5HDKB24/p1734373208772149?thread_ts=1733336615.859159&cid=CU5HDKB24

### Assumptions & Initiation Needs

https://dotcms.slack.com/archives/CU5HDKB24/p1734395185549759

**Comment by jdotcms** [comment]
[Dupe](https://github.com/dotCMS/core/issues/30969)

**Comment by weiyiwang-dotcms** [comment]
Duplicate of [30969](https://github.com/dotCMS/core/issues/30969)
