### ISSUE TITLE
Improve reindex performance

### ISSUE THREAD

**Issue by dotjorgeu** [dotCMS/core#3149]
It's necessary to refactor the logic of the full reindex in order to process concurrent elastic search requests using a bulk processor. It would improve processing time

**Comment by nollymar** [comment]
A bulk processor has been implemented to perform full reindex tasks only (others ES tasks continue using BulkRequests). It's possible to configure the following settings depending on specific environment requests:
1. `REINDEX_THREAD_ELASTICSEARCH_BULK_ACTIONS`: Set when to flush a new bulk request based on the number of actions currently added. Default value: 2000
2. `REINDEX_THREAD_ELASTICSEARCH_BULK_SIZE`: Set when to flush a new bulk request based on the size of actions currently added. Default value: 20MB
3. `REINDEX_THREAD_CONCURRENT_REQUESTS`: Set the number of concurrent requests allowed to be executed. Default value: 4
4. `REINDEX_RECORDS_TO_FETCH`: Set the number of database records to fetch to be processed by Elastic. Default value: 100

In general, the reindex processing time improved a lot (it takes 1sec or less to process about 2000 requests), however the database is the main bottleneck here. Elastic has to wait between 5s to 10s between bulk processing and takes just a fraction to reindex them.

Using the database as a queue system for very large datasets is not a good approach, so an alternative would be to replace the database queue logic with a messaging system like Apache Kafka or RabbitMQ:

https://kafka.apache.org/intro.html
http://mikehadlow.blogspot.com/2012/04/database-as-queue-anti-pattern.html

**Comment by nollymar** [comment]
My findings using Glowroot instrumentation on a large dataset: 

<img width="1203" alt="2019-04-02_1253" src="https://user-images.githubusercontent.com/8741395/55424859-c1dbf400-5546-11e9-874d-e9859ceb11f0.png">

<img width="1249" alt="2019-04-02_1254" src="https://user-images.githubusercontent.com/8741395/55424866-c4d6e480-5546-11e9-9d28-e8a4ebcc3e95.png">

<img width="1206" alt="2019-04-02_1255" src="https://user-images.githubusercontent.com/8741395/55424879-cf917980-5546-11e9-8ca8-6ed754d0ba12.png">

<img width="1206" alt="2019-04-02_1256" src="https://user-images.githubusercontent.com/8741395/55424887-d4562d80-5546-11e9-92ba-b4b5074c1a1c.png">

**Comment by dsilvam** [comment]
Tested with client's data set: 
```Reindex took        : 11m 11.45s```
