### ISSUE TITLE
Ability to copy a workflow schema

### ISSUE THREAD

**Issue by mabouza** [dotCMS/core#3163]
It would be great to have the ability to copy a workflow schema.

In a multi-host environment where structures are assigned to specific hosts, you may want to have very similar workflows that differ on the roles that can use them and the roles they get assigned to but the rest of the steps / actions are the same.

It's really time consuming to copy a whole schema manually so being able to right click : Copy would be great :)

**Comment by ethode** [comment]
Is this still slated for 3.5?
