### ISSUE TITLE
Add Ability to get an image of a rendered HTMLPage

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#3267]
We need to to work for PDFs, thumbnails etc... We need to provide an API method to do this with a Viewtool and RESTFul interface added as a wrapper. 

In addition we need to show the Thumbnail when viewing a Page 

We can use PhantomJS for this see
http://phantomjs.org/

In addition to this there is a Driver to interface with it here
https://github.com/detro/ghostdriver/
https://github.com/detro/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriverService.java

The actual interface we want to use is this 
https://github.com/ariya/phantomjs
It is a headless version of Webkit

We do NOT want to run PhantomJS as a service but run it embedded. The reason we do not want to run as a service is that we don't want to deal with another service running that could crash

For other research info see
https://groups.google.com/forum/#!topic/phantomjs/MZEegYmxH0Q
Not going to use but interesting https://code.google.com/p/selenium/wiki/ChromeDriver

**Comment by wezell** [comment]
Neat!
