### ISSUE TITLE
Documentation error at http://dotcms.com/docs/latest/javadocs/com/dotmarketing/viewtools/MailerTool.html

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#3627]
In the examples, "sendMail" should be "sendEmail".

**Comment by jkshapiro** [comment]
Got bit by this again today.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9454

**Comment by john-thomas-dotcms** [comment]
Documentation created for this tool: http://dotcms.com/docs/latest/mail-tool
