### ISSUE TITLE
CMS Maintenance > Cash - Should the "Flush All Caches" button read just "Flush" or "Flush Cache"?

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#3765]
It's somehow weird when the user selects one specific option from the drop down (CMS Role, for example), but the button still reads "Flush ALL Caches".

![image](https://f.cloud.github.com/assets/1569509/1012755/2bff9240-0b76-11e3-9a83-7fe81be94229.png)

**Comment by rogelio-blanco** [comment]
Pull Request #7742

**Comment by bryanboza** [comment]
Fixed, tested on Nightly build 2015-05-15 // Postgres // FF

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-15 00:22 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/265
