### ISSUE TITLE
Move edu.emory.mathcs.backport.java.util.concurrent to java.util.concurrent

### ISSUE THREAD

**Issue by dotjorgeu** [dotCMS/core#387]
We can move to java.util.concurrent as our new versions will drop older JVMs.
java.util.concurrent will use a more supported implementation. 

I grep that package and found we have log4j code in our src. Not sure why we don't use log4j jar

**Comment by wezell** [comment]
Get this lib out of our dependencies please.  You can't trust things from Emory.edu

**Comment by wezell** [comment]
```
import com.dotcms.repackage.edu.emory.mathcs.backport.java.util.Arrays;
```

**Comment by wezell** [comment]
![screen shot 2017-06-20 at 3 06 10 pm](https://user-images.githubusercontent.com/934364/27351007-06055f6e-55ca-11e7-9f16-9548032bce00.png)

**Comment by dsilvam** [comment]
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/479

**Comment by john-thomas-dotcms** [comment]
Does this need to be mentioned in the change log for anyone who built their own plugins, or is this just and internal change?

**Comment by danlaguna** [comment]
I believe this should be mentioned, mainly because we dont know if customers have used or repackage packages for their own plugins. If they use standard Java packages this change wont affect them.
