### ISSUE TITLE
Filtering on host when adding widgets to containers 

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#4408]
When adding a widget to a container through the add widget button lists all the widgets. This is nice, but when you have many hosts and they all use the same names for their widgets it's almost impossible to find the correct widget. It would be nice if we could filter the widgets there by host.
![screen shot 2013-10-30 at 17 30 45 pm](https://f.cloud.github.com/assets/2471852/1441411/d46bd776-41aa-11e3-9fe4-8b73e58bfafb.png).

**Comment by jorith88** [comment]
ContentletAjax already has support for this, so only the frontend needs to be changed. I was able to filter on the current host by adding two lines to (`fieldsValues[2]` and `fieldsValues[3]`) to **WEB-INF/velocity/static/preview_mode/preview_mode_controls.vl** in dotCMS 3.2.4:

```javascript
function _dotWidgetSelected(){
    var _dotWidgetSelect = document.getElementById("_dotWidgetSelect");
    var selIndex = _dotWidgetSelect.selectedIndex;
    var woptions = _dotWidgetSelect.options;
    _dotWidgetNameSelected = woptions[selIndex].text;
    _dotWidgetInodeSelected = woptions[selIndex].value;
    _dotStructureTypeName = _dotWidgetNameSelected;
    _dotWidgetSearchString = "";

    if(_dotWidgetInodeSelected == 0){
        _dotWidgetCleanResultsData();
        return;
    }

    var categoriesValues = new Array ();
    var fieldsValues = new Array ();
    fieldsValues[0] = "text1";
    fieldsValues[1] = dijit.byId('_dotWidgetAjaxSearch').attr('value');
    fieldsValues[2] = "conhost";
    fieldsValues[3] = "$host.identifier";

    ContentletAjax.searchContentlet(_dotWidgetInodeSelected, fieldsValues, categoriesValues, false, false, _dotPage, _dotPerPage, "title asc", _dotFillWidgetResults);
}
```

**Comment by Xander-Steinmann** [comment]
Even better would be to have the same display as in the 'reuse content' popup or the content search, where you can select a content type and search for all fields marked 'searchable'.

**Comment by koenpeters** [comment]
+1
