### ISSUE TITLE
Add FTP access as an alternative for webDAV

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#4543]
Many of our clients ask for this for a couple of reasons:
1. It integrates better with their existing tools. Especially for companies that use an external build process htat also updates the JS/CSS/etc in dotCMS this is a win, because these tools have a better support for FTP.  
2. The current webDAV implementation keeps falling over because the OSes and webDAV clients keep changing stuff. FTP is more stable spec wise. 
3. WebDAV clients or even the OSes do more additional calls when saving content then just the files that the users see. This results in a slower process and it is also more error prone. Since FTP is not HTTP based this is likely to be less of an issue.
4. Our clients keep asking us for this feature, so there seems to be a demand for it from the marked. Especially the clients that are more than just a marketing team, but that use dotCMS as a frontend for their backend solution.

**Comment by koenpeters** [comment]
I think this is still relevant
