### ISSUE TITLE
Page refresh sometimes results in a "collapsed tab content"

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#4595]
Pretty often (but not reproducible in a reliable way) I refresh my admin page (using F5 on chrome on windows 7), and the screen shows up collapsed. It happens about 5% of the time on my machine.  The server in the screenshot below is Prime 2.3.2

![closed tab](https://f.cloud.github.com/assets/2471852/1740764/db08d698-63d2-11e3-8267-9371b79356a0.png)

**Comment by wezell** [comment]
4.x
