### ISSUE TITLE
Starting DotCMS from Anywhere

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#466]
Currently things do not work properly if you do not start dotCMS from the dotCMS Root Foler.  For people who use init scripts or restart scripts they hand roll we should be able to start dotcms from any directory as long as you fully path to the correct startup script. 

See for example this ticket:  http://jira.dotmarketing.net/browse/EE-4456

**Comment by wezell** [comment]
This is fixed in 4.1
