### ISSUE TITLE
ResizeImageServlet not working with ?path=

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#474]
I have run into several clients with this issue now.  The issue is that when you have an image like:

/resize_image?path=/path/to/image.jpg&w=80 it ends up in a 403, even if the image has CMS Anon.  Testing in 1.9.5.0 Code, I tracked this down to around Line 210 of the ResizeImageServlet where it is checking permissions.

You do not have the same issue when you use the ?id= instead of ?path=

Here is one example in 1.9.5.0:  http://jira.dotmarketing.net/browse/EE-4307
Does not Work:  https://www.uakron.edu/resize_image?path=/test/bradsslides/images/JellyBeans.jpg&maxw=80&maxh=100
Same Image Works:  https://www.uakron.edu/resize_image?id=c565bf91-6737-4472-85fe-7adce43c933f&maxh=80&maxw=100

Here is a Client in 2.0 having the same issue:  http://jira.dotmarketing.net/browse/EE-4442

I think the common thread is that they are both MySQL clients, but I am not 100% sure and it might be a coincidence.  

I have one client's Database Dump on colo4 to test with.

**Comment by wezell** [comment]
Closing as ResizeImageServlet is no longer used
