### ISSUE TITLE
Limited User Publishing file asset content when you use Multiple files upload

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#4793]
Reproduced on master-2.5

Steps:
1. Go to Roles -> Create a Role -> grant Edit permission to Host and all its child objects (do not give publish permission)
2. Go to File Asset Structure, make sure this role has only Edit Permission.
3. Login as with this role, try to add a file asset content to the host using Multiple Files option
4. You will see that content Published when you upload a file though you don not have Publish Permission.
Please see http://screencast.com/t/kfeUi6QMSyS

Test Info: Win7//MySQL//Chrome.

Test: Role permissions
http://qa.dotcms.com/index.php?/tests/view/67952

**Comment by john-thomas-dotcms** [comment]
Reported by a customer and verified that this still exists on 3.6.0 (tested on demo).  A few more details of the specific permissions that cause the issue:

1. Give the user/role `Edit` permissions on the folder the files will be uploaded into.
2. Give the user/role `Edit` permissions on `Folders`, `Content Types`, and `Content/Files` within the folder the files will be uploaded into.

The problem goes away if you remove the `Edit` permission from _either_ the folder itself (the folder the files will be uploaded into) or `Folders` within the folder where files will be uploaded.
