### ISSUE TITLE
Ability to Export only PUBLISHED Content

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#4858]
(From Jeremiah @HCA)

Hey guys -

Not sure where to put this, but had a request from several individuals in the field that it would be great to be able to export a set of content that does not include unpublished content. The reason is we have users with hundreds of physicians and they only want to export/update/import those that are already published.

I've attached an image of where it would be ideal to add 'Published' to the 'show' menu on the content tab.

![showlist](https://f.cloud.github.com/assets/1823543/2138678/8d2ad73a-9336-11e3-9508-43577a0108c0.png)

**Comment by gabbydotCMS** [comment]
New reference to this github issue:

https://my.dotcms.com/tickets/detail.dot?id=26b87049-2460-4953-a3ab-aa7d5777a0b9

**Comment by gabbydotCMS** [comment]
New reference to this github issue:

https://my.dotcms.com/tickets/detail.dot?id=61a54954-d2da-4e53-a604-17b5ff9acfff

**Comment by Nich0lesj** [comment]
Just adding to this issue... what are the chances that a 3 year old issue will be resolved? Thanks!
