### ISSUE TITLE
Ajax re-ordering of related content not maintain the given order in Parent content

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#5119]
Reproduced in nightly builds 2014-03-13 01:01:00.0//H2DB

Steps: 
1. Create a parent Structure  and a child Structure 
2. Add a Many to Many Relationship between Structures
3. Create a contents for child Structure  and relate to Parent  content.
4. Edit the Parent Content and re-order the related contents then Save and Publish
5. You will see that it should not maintain the given order.
Please see http://screencast.com/t/jYbIZHC0B

TestInfo: Win7//H2DB//Chrome

Test: Check ajax re-ordering of related content
http://qa.dotcms.com/index.php?/tests/view/81625

**Comment by fitzciaran** [comment]
We also have this issue - http://www.youtube.com/watch?v=jVMgttcFlIA 
Relationship Name is SupportVideo-SupportVideoDescriptionBulletPoint

Parent Content Type is Support Video

Child Content Type is Support Video Description Bullet Point 
Cardinality is M-N

Parent Required is No 
and Child Required is No

Running on DotCMS 3.2.3

**Comment by jgambarios** [comment]
Closed this ticket and opened a new related one (https://github.com/dotCMS/core/issues/9196)
