### ISSUE TITLE
(Documentation) ViewTools doc pages need velocity names

### ISSUE THREAD

**Issue by ethode** [dotCMS/core#5154]
In the documentation none of the doc pages for the view tools mention the velocity names I am forced to search github constantly to find the name of viewtool names in the XML configs.  Some have usage examples but many do not like this:

http://dotcms.com/docs/latest/CMSUsersWebAPI

Imagine the frustration from a non technical UI user trying to utilize some of these tools and the docs  :-)

Thanks guys

**Comment by wezell** [comment]
We should stop spitting out the non-helpful java docs for our viewtools and include the toolbox.xml which has all the mappings.
