### ISSUE TITLE
(Enhancement) Form - create from existing

### ISSUE THREAD

**Issue by ethode** [dotCMS/core#5205]
I have some forms that are 40-50 questions, and for different purposes we might change 2 or 3 questions, it's a painstaking task to duplicate these forms by hand.  A nice "Create from" feature would be great

**Comment by jkshapiro** [comment]
What's current status of this please?

**Comment by jtesser** [comment]
nothing right now.  adding more copying of objects like forms, workflows etc.. is something we need but not currently slated for a particular release
