### ISSUE TITLE
Push publishing source identity by IP should be optional

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#5259]
The Push Publishing target server/environment currently authorizes connections via the source server's IP (or hostname) and auth token. There are a number of situations where the source server's connection IP will vary, or may not be known:
-Connection goes through target load balancer (AWS ELB or otherwise)
-Edit (source) environment is internal and NAT'ed
-Edit (source) environment is loose-coupled behind load balancer and doesn't have static IPs
-Target environment is source NAT'ed

In these situations, there is not a clear way to authorize the incoming connection by IP address without adding additional servers/services/complexity. In keeping with cloud build best practices, this source->target connection should not be rigidly coupled by IP address as this connection parameter can be volatile.

**Comment by chrismccracken** [comment]
For some cases, we've found a workaround using a specifically-configured RemoteIpValve with a specifically-configured network topology. However, we've run into https://github.com/dotCMS/core/issues/9067 so its not a slam-dunk yet

**Comment by chrismccracken** [comment]
Consider this architecture, where both the sender IP and load balancer IP addrs may be variable [image]:(https://www.lucidchart.com/publicSegments/view/a4ca37ab-f696-42ac-b85e-37b0ee605b3a/image.png)

**Comment by austindlawless** [comment]
I'm not sure if this is the case for all situations. But for us, our source IPs will be restricted to a small-ish range. It would be great if instead of a list of IPs, the source IP field would take a range of IPs as well.

**Comment by gabbydotCMS** [comment]
Related support ticket: https://my.dotcms.com/tickets/detail.dot?id=78784dd0-a956-47ab-a919-090395c5f991

**Comment by wezell** [comment]
moved here: #11789
