### ISSUE TITLE
Permissions UI Enhancement

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#529]
I'd like propose an enhancement to the way we set permissions (especially on folders and hosts).  What I see happen with clients with large systems and complicated permissions is that when you try to permission individually something or apply permissions to say a folder, it can take a long time (hours).  I know we are improving this as much as we can, but it is understandably a complicated process.  

The issue though is this, most browsers time out the AJAX request we make via the PermissionAjax DWR guy.  So the UI never reports that the operation is finished.  If the user has no idea if the process is still running or finished.  Most of the time they think that it is not finished or that it failed. 

Here is my idea on how to resolve this issue:
1.  Add a table (or maybe not a DB table but some data somewhere) that tracks what is currently being permissioned (or any other permission ajax method).
2.  When I click Permission Individually it inserts into this table that this folder is currently being permissioned.
3.  The process then kicks off a thread to perform the permission changes.
4.  After that it returns to the browser that it is in-progess.
5.  Every few seconds or so another AJAX call goes out to check and see if the current object is being permissioned still.
6.  When it doesn't detect the record in the table anymore it knows to tell the user that the process has completed.  

Not sure if this is feasible or worth the effort to develop, but it would certainly save us in support many hours debugging non-issues.

**Comment by wezell** [comment]
I believe this is resolved in the latest versions.  It deletes permission references when a new permission is saved, which is fast and then rebuilds them lazily, as they are requested.
