### ISSUE TITLE
Relationships view usability improvement

### ISSUE THREAD

**Issue by cmaessen** [dotCMS/core#5300]
There are a couple of odd usability quirks for relationships in Dotcms.

Relationships don't have their own menu option in the Structures menu. You can only view them by clicking on the "view" link in the Relationships column for a structure. But this will show you all relationships, not those linked to that structure. Not very user friendly when you have a lot of relationships and are trying to find one relationship.

The following would make using relationships easier:

1) Add a menu option "Relationships" in the structures tab. This window will display all relationships defined in that Dotcms instance.

2) Add filtering options for the columns "Relationship Name", "Parent Structure", and "Child Structure". This will make it a lot easier to find relationships and maintain/edit them (although this is a would be nice).

3) When clicking on the "view" link in the Relationships column for a structure only the relationships linking to this structure should be shown. This is the expected behaviour for this link (as this is what the "entries" link does in the Entries column). A would be nice could be to add an option on that screen to view all relationships (see point 1).

These changes would give the relationships screens the same feel and usability as you currently have for content of structures.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-24 // Postgres // FF

**Comment by jkshapiro** [comment]
Item 3 is fixed in dotCMS 3.2 but items 1 and 2 are still outstanding
