### ISSUE TITLE
Site search index REST APIs do not support type parameter (no support for JSON or JSONP)

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#5353]
Found while testing this issue:  https://github.com/dotCMS/dotCMS/issues/3573

Used this command to create site search indexes:
curl -i http://localhost:8080/DotAjaxDirector/com.dotmarketing.sitesearch.ajax.SiteSearchAjaxAction/u/admin@dotcms.com/p/admin/cmd/createSiteSearchIndex/shards/1

This command does not return json:
curl -i http://localhost:8080/DotAjaxDirector/com.dotmarketing.sitesearch.ajax.SiteSearchAjaxAction/u/admin@dotcms.com/p/admin/cmd/getNotActiveIndexNames/type/json

Does not seem to handle type parameter at all.  Regardless of what is passed as the type parameter, the Content-Type header value does not change and the returned data does not change.

**Comment by wezell** [comment]
As this api is for scripting and not for use on a cross domain webpage, I think no jsonp is acceptable
