### ISSUE TITLE
Push Pub: Clean up bundles directory upon successfull publishing

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#5541]
As suggested by **a client** a way to avoid the bundle directory from growing continuously (scheduled clean-up or remove bundles upon successful publishing) would avoid running out of space.

**Comment by chrismccracken** [comment]
A number of clients have asked about this lately, let's get this added in Mingle.

**Comment by mattyarbrough** [comment]
This is a problem for clients, particularly those using ext3/4 where inodes aren't scalable and has caused them production problems.

**Comment by oarrietadotcms** [comment]
This one would be cool. On site client request.

**Comment by wezell** [comment]
```
find /path/to/assets/bundles -mtime +5 -exec rm {} \;
```

**Comment by wezell** [comment]
Done here, as part of the tempResource clean up.  It needs doc for 5.2
```
bundles.delete.enabled=true
// delete bundles older than two days
bundles.delete.older.than.milliseconds=1000 * 60 * 60 * 24 * 2
```
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/quartz/job/BinaryCleanupJob.java#L58
