### ISSUE TITLE
When creating files changing the language resets host/folder value

### ISSUE THREAD

**Issue by dotjorgeu** [dotCMS/core#5668]
see video http://screencast.com/t/3TjSmpGzWPWx

**Comment by john-thomas-dotcms** [comment]
So I think what's actually happening here (at least in 4.x) is that all language versions of a content share the same value of the site/folder field.  If you change the site/folder field in one language version

Whether this is a good thing or not is debatable - it means that you can't have different language versions of the same content that live in different folders (and thus you can't control permissions to different language versions of the same content by managing folder permissions).  It also means that if you change the value of the field on one language version, it silently changes it on the other language version of the content, which may be unexpected (and not necessarily intuitive).

Example Case:

1. Open an existing content item that has a site/folder field (such as the News content type on the demo/starter site), which has only one language version of the content.
2. Change the language, and respond to the prompt to copy existing content to the new language version.
3. Remaining in the new language version of the content, change the content title, and change the site/folder field to a different folder.
4. Save the new language version of the content.
5. Close the content and re-open the English version of the content.

**Result:** The folder of the English language version of the content has also been changed.  The Title fields of the two different language versions are different, but the site/folder field value is always the same.

**Comment by wezell** [comment]
This is as designed - for better or worse.  If you need a file or asset in two languages on two different hosts, then I think you should make them 2 files assets.

**Comment by john-thomas-dotcms** [comment]
Note on context: I was looking into this because of a question about how to permission content so that different users could edit different language versions of the content.  Responses on the user forum indicate that more than one user has tried to do this, and we don't currently have a built-in way to do this easily.
