### ISSUE TITLE
Enhancement:  Implement "What's Changed?" functionality at the contentlet level

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#5680]
It's great to be able to see "What's Changed" via the Preview tab of an HTML page.  Let's add the same functionality to contentlets.  This would be especially valuable for organizations that subject content to a workflow:  currently when I access a contentlet from the Workflow Tasks portlet, I have no easy way to see what the changes are.

**Comment by john-thomas-dotcms** [comment]
Adding my +5 for this.  This is the #1 missing feature that would help me manage our doc content.

It's quite challenging to accurately find the differences between 2 versions of content.  For Textarea and WYSIWYG fields, I usually copy and paste the contents into separate text files and run an outside diff program (which takes more effort than I'd like, but at least it works).  But for all other fields, the only way to compare is to manually inspect, or to dump the content as JSON and compare the JSON (again, very messy).

### Possible Solutions

1. (Minimal): Add a `Difference" button on each version listed in the `History` tab.
    * Clicking the button on any version shows the differences between that version and the current version.
2. (Ideal): Add a `Compare` button at the top of the `History` tab (or maybe a separate `Compare` tab).
    * When you click this, you can select 2 versions from the list of versions see a side-by-side comparison.
    * Note: This is what's really needed, but would take more work to implement.

_Note:_
* This could potentially be done via a plugin.
    * (If I was a Java dev, I'd probably have written it already).
* I've been working on a widget to compare the JSON format of 2 content versions and show the differences.
    * This is just a stopgap (and something I can at least offer customers when the question comes up in training) but I haven't gotten it working yet.

### Context

* We have only 2 people that regularly update the content, and I run into this at least a few times a week.  
* I've had questions about comparing versions 3 times (twice in Content Architect and once in the one Content Contributor course I did).
* I suspect this is more of a need for content contributors than architects, and in organizations with more (and more active) content editors than we have.

**Comment by wezell** [comment]
Thoughts:

We need to upgrade/update daisydiff.  There are two competing branches:
- https://github.com/DaisyDiff/DaisyDiff
and the one hippo forked and built on:
-https://code.onehippo.org/cms-community/hippo-htmldiff/tree/master

As a basis for the diff, we should use one of these two.  I was thinking that we could do a diff using similar code from this jsp that shows all the content's fields in html:

http://demo.dotcms.com/html/portlet/ext/contentlet/view_contentlet_popup_inc.jsp?contentletId=dd7cb5f7-057e-46a0-a73e-9620f6bc409b

**Comment by mattyarbrough** [comment]
Another aspect of this would be the ability to compare two versions of a contentlet without having to make one of them live to see its contents.

**Comment by JohnRiv** [comment]
I see this has been closed due to inactivity, but wanted to mention we'd find this useful and I'm sure others would as well
