### ISSUE TITLE
Adding spaces between search terms creating extra words in a Query

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#5833]
Reference #3932

In Content Search page, IF I add spaces between search terms creating extra words in Show Query i.e "+_all:* +".
see http://screencast.com/t/vfSlBVM6OX

Test: "Use Query tests tool to search following: +structureName:webPageContent +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +webPageContent.title:[mac TO mars] Also add spaces between search terms and make sure it still works"
http://qa.dotcms.com/index.php?/tests/view/2918

I am able to reproduce this on master-2.5 // MSSQL // FF

**Comment by jtesser** [comment]
working in master-3.1

**Comment by prasadbhvn** [comment]
Tested in nightly build 07-01-2015 Win7//Chrome//Postgres
