### ISSUE TITLE
Documentation of configuration files

### ISSUE THREAD

**Issue by cmaessen** [dotCMS/core#5988]
Not exactly an issue with the code itself, but it is something that has bugged me on multiple occasions.

I had to look up a configuration option, which led me in this case to the documentation page for DEFAULT_WIDGET_TO_DEFAULT_LANGUAGE:
http://dotcms.com/docs/latest/WidgetsInMultilingualSites

But this page doesn't mention at all in which file this option resides and what the location of said file is. In this case it was easy enough to track it down, but this is a problem with all the documentation for configuring Dotcms.

This is an unnecessary hurdle for checking/changing settings and has slowed me down on several occasions. It forced me to either dig through configuration files and folders or ask a colleague where I could find the files. It would improve Dotcms documentation a lot and would help users with maintaining/configuring their Dotcms instances (especially new users).

**Comment by DeanGonzalez** [comment]
Documented: http://dotcms.com/docs/latest/WidgetsInMultilingualSites
Looking for other examples and will add the same references - thanks!
