### ISSUE TITLE
Push Publishing for Vanity URLs

### ISSUE THREAD

**Issue by thequicksilver** [dotCMS/core#6065]
[Feature Request] Looked around and didn't see any tickets for this. Right now, Vanity URLs are one of the few items that still don't support bundling and push publishing. This is especially problematic when clustering, since you might be making one Vanity URL that ends up needing created multiple times across each individual node.

**Comment by wezell** [comment]
This will be addressed in our refresh of vanity urls

**Comment by monzonj** [comment]
Hi, this is for almost a year old and that "refresh" of vanity URLs never happened. Can we get an update of the status of this feature?

Vanity URLs are a very important marketing tool, however licensed customers like us that user PUSH PUBLISHING are banned from using them as they are not supported for pushing.
