### ISSUE TITLE
Allow search on identifier for Files in the Files Browser

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#61]
We used to allow this in 1.7, it helps admins find images and such that they only have the identifier or inode for.  It is often requested that we allow them to enter the identifier into the search on the files browser.  Right now it is not possible without going to the database to find the actual file referenced by an inode or identifier.

See:  http://jira.dotmarketing.net/browse/EE-4205

**Comment by wezell** [comment]
You can search files, pages content from the content search screen, either by inode or identifier.
