### ISSUE TITLE
Category Import causing multiple duplicate imports at parent and child level

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#6115]
This one may be environment specific, since Bryan tested on his windows box and it did not happen for him, but I retested 3 times and got same results.
Environment: Windows Server 2012 R2 running Postgres 9.3
To re-create:

1) Add a new category called "Genre"
2) Step into the newly created "Genre" parent category
3) Import categories using the moviegenres.csv file we have always used for import testing (QA has the file)

Bug is that duplicate categories are created at both the Child and parent level.  Here are the errors generated in the log:
https://gist.github.com/DeanGonzalez/a8d1c776559be76f2907

Screenshot: http://screencast.com/t/fkd2zmzrC
Here is a screencast of whole import process: http://screencast.com/t/NeuCw4o8

**Comment by jtesser** [comment]
still not getting this in master-3.1

**Comment by prasadbhvn** [comment]
Tested in nightly build 07-01-2015 Win7//Chrome//Postgres
