### ISSUE TITLE
Documentation unusable at narrow widths

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6125]
The Dotcms online documentation at http://dotcms.com/docs/latest/TableOfContents can't be used at screen widths of 971px and below, because the navigation bar on the left disappears.

**Comment by DeanGonzalez** [comment]
Tested - responsive design now creates a menu link in the header

**Comment by jkshapiro** [comment]
Nice to have you back in the game @DeanGonzalez!
