### ISSUE TITLE
Content API doesn't require authentication

### ISSUE THREAD

**Issue by mabouza** [dotCMS/core#618]
I open a new browser where I'm not logged in and try to access the content api
http://localhost:8020/api/content/query/+structureName:Blog%20+Blog.title:jetblue/

and get the content.

shouldn't this be restricted somehow?

it would be easy to take someone's site down by hitting something like this many times?
http://localhost:8020/api/content/query/+live:true/limit/1000000

**Comment by wezell** [comment]
We now limit the limit, which can be configured.
