### ISSUE TITLE
Improve logging in Workflow Bunder

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6185]
When a scheme doesn't exist or a role it points at doesn't exist no good error is shown 

see
https://github.com/dotCMS/enterprise-2.x/commit/2ef850576e0e75b6745c1d0bae3297e357b5a317#diff-2320ae456457ac5398d6ea4e095c76d0

https://github.com/dotCMS/enterprise-2.x/blob/2ef850576e0e75b6745c1d0bae3297e357b5a317/src/com/dotcms/enterprise/publishing/remote/bundler/WorkflowBundler.java#L75

**Comment by jtesser** [comment]
should be working with latest EE commit

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // MySQL // FF
