### ISSUE TITLE
Users password security improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6205]
Actually we only have a regexp expression that you can set in .\bin\system\src-conf\portal.properties with some pattern .... But this system is not working fine.

By default we have "/(?=.{4})(?=._[a-z])(?=._[A-Z])(?=._[0-9])(?!._[^-\w])/", this should be evaluate that must have at least 4 valid characters... but if you try to create a new user and try to set as password= "12", the user was created successfully... Maybe we need implement a new system and set a better handle of password security 

As in other systems, maybe the password should be contain an specific format by default, and should be nice show a password security evaluation... I was tried to change the pattern to multiple formats but does not working neither..

Tested on nightly build 2014-08-25 // MSSQL // FF

**Comment by bryanboza** [comment]
Right now we still having this problem, we are showing the follow message: 

```The password does not meet the system security requirements. It must contain at least 6 valid characters, must contains one digit from 0-9, one lowercase characters, one uppercase characters and one special symbols in the list "@#$%".``` 

But actually we just validate if the password have the 6 valid characters, then we need change the message, or change the regex to have a more complete validation...

What do you think here @wezell ?

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10014

**Comment by jcastro-dotcms** [comment]
Hi @john-thomas-dotcms , the [portal.properties](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/resources/portal.properties) file currently has 3 RegEx patterns for password complexity. The simplest of them is the one we ship with by default. If the selected RegEx is changed by customers, they need to remember to update value of the ``User-Info-Save-Password-Failed`` property in their respective Language.properties files to display the correct error message when password complexity requirements are not met.

Can you add this to the documentation, please? Let me know if you need more information about this.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF.... We need some doc here...

**Comment by john-thomas-dotcms** [comment]
This doc is already there: http://auth.dotcms.com/docs/latest/password-security-configuration#ValidationMessages.  But I added a line in the section where the regex properties are described, to link to the validation messages section.
