### ISSUE TITLE
ActivityLogger needs to be on the versionableapi not just the contentletapi

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6222]
I am seeing content get "unpublished" and even "deleted" and not seeing any logging activity on them.

I do see the new ActivityLogger logging a publish, which is a good thing, but the issue is that really, the VersionableAPIImpl is what controls publishing and unpublishing and is sometimes used without calling the contentletAPI

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6936

**Comment by bryanboza** [comment]
Fixed, now the system is logging all the transactions... Tested on master-3.1 // H2 // FF
