### ISSUE TITLE
Spanish calender events redirects to 404 page in the front end

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6240]
Reproduced in nightly build 2014-08-29//MSSQL

Steps:
1.Create two events in English and Spanish languages from the back end.
2. Go to News & Events , Try to see the details of English and Spanish events.
3.You will get 404 page when you click on Spanish event
Please see http://screencast.com/t/akjpA1iE

**Comment by bryanboza** [comment]
Here we need the fix #6888 to test...
