### ISSUE TITLE
Error trying to archive templates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6297]
Related to #6117 

To recreate: 
1- Create a new template
2- Create a new page and use the created template 
3- Go to the templates portlet and try to unpublish and then archive 

We have the follow error: 

An unexpected system error occurred.
User com.liferay.portal.model.User@cb1c722f does not have permission to read 19e6f18d-76a9-45d3-bd1d-f3151abc9d1e

SC: https://gist.github.com/bryanboza/2124c2cd8cb29bbe355e

Tested on Nightly Build 2014-09-05 // Postgres // FF

**Comment by jtesser** [comment]
this is working properly in master-3.1

**Comment by prasadbhvn** [comment]
Tested in nightly build 07-01-2015 Win7//Chrome//Postgres
