### ISSUE TITLE
Push fails when menu link dependence page in another folder 

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6312]
Reproduced in nightly build 2014-09-05//MSSQL

Steps to reproduce:
1- Create a folder A with a html page
2- Create another folder B with a menu link to the page in the folder A
3- Push the menu link , You will see that push fails due to dependence page in another folder.
Please see http://screencast.com/t/wxJRIAqFd
Error in console: https://gist.github.com/prasadbhvn/f44404f9ade2d488e962

Test Info : Win7//MSSQL DB in both side servers.

**Comment by jgambarios** [comment]
I was unable to reproduce this issue with the latest code, I asked Bryan to help me testing and he was also unable to reproduce the issue.
