### ISSUE TITLE
The "submit" of the "form" saves the data only in "en" language 

### ISSUE THREAD

**Issue by santo-neticon** [dotCMS/core#6333]
My dotCMS is configured as follows: 

LanguageID 1 = en 
LanguageID 2 = it
Defaul Language = it

The current session has "contentLanguageId = 2" and the data is saved in the "en" content.

**Comment by jtesser** [comment]
QA I believe this is working in master-3.1

**Comment by shayngr** [comment]
This functionality is working
Tested on nightly build 3.1 nightly build (2015-01-07 20:52)
H2 // Chrome
