### ISSUE TITLE
JS Error on Host/Folder control 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6431]
this is scenario (on demo host):
a) Insert a new relationship between news-fileasset
b) Upload a new file in "service/market-reseach" folder
c) Select a news content and the switch to relations tab and select "Relate" button ( on news-fileasset relation)
4) search file using host filter, scroll down until "service" folder and try to open "service" folder (click on plus icon).
 
Javascript keep you back to the top.

**Comment by joseorsini** [comment]
This can be reproduced on 3.3.1 and 3.5 (Demo Site). Reported by client here https://my.dotcms.com/tickets/detail.dot?id=8b5f6a23-341f-41ea-bbfa-066dec74f6ba (Support ticket includes video with steps to reproduce it).

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9010

**Comment by jcastro-dotcms** [comment]
PR for master-3.5: https://github.com/dotCMS/core/pull/9011

**Comment by jgambarios** [comment]
PR for master-3.6: https://github.com/dotCMS/core/pull/9066

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // MySQL // FF
