### ISSUE TITLE
When multiple Site Search indexers run at the same time index contents is arbitrary

### ISSUE THREAD

**Issue by bravous** [dotCMS/core#6479]
When two indexers a scheduled to run simultaneously for two different languages it looks like the indexers overwrite each other. Content cannot for either one of the languages cannot be found anymore and other *weird* search behavior on the front end. 

The CMS allows me to create cron jobs that run simultaneously but is not handling this situation correctly when the jobs are executed.

We have two indexers, one indexer for each language on our site, our site has two languages (English and Dutch),

**Comment by wezell** [comment]
#8552 dupe?
