### ISSUE TITLE
Push Publish: contentlet_version_info table on web server not in sync with authoring server

### ISSUE THREAD

**Issue by bravous** [dotCMS/core#6482]
Data in contentlet_version_info is pushed to _Web Server_ in certain cases. For me unclear why it is not .

When I UnArchive the content it is correctly pushed, but when Archived again the new state is not pushed to the _Web Server_.

Look like in certain (edge) cases the data in the contentlet_version_info table is not correctly synced.

**Comment by jtesser** [comment]
So currently we do not push Archived content but can implement this an a future improvement. 

@DeanGonzalez we need to document that Push Publishing doesn't push Archived or Deleted Content
