### ISSUE TITLE
License Manager - Reset License Identity Not Resetting Server ID

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#6525]
I set up a two node cluster with both nodes using licenses from a cluster license pack that I uploaded.  The server ids of both servers changed to match the license they got from the pack.  So far, so good.

![image](https://cloud.githubusercontent.com/assets/3208956/4526519/01cb8e8e-4d60-11e4-9594-40bb5fd0fe42.png)

The problem is that when I click the "Reset License Identity" button, that it leaves the server id the same as it was with the cluster license.  It resets to community correctly but leaves the server id so that it still matches the license it had from the license pack.

![image](https://cloud.githubusercontent.com/assets/3208956/4526527/0fb4bb92-4d60-11e4-87e8-bd0013997cbd.png)

I was then able to go through the support portal and get a license.  I also was able to use the cluster license on another node.  So I was able to have two nodes in my cluster with the same server ID.
![image](https://cloud.githubusercontent.com/assets/3208956/4526612/f857275e-4d60-11e4-8101-a4ae86832dc9.png)

Ubuntu 14.04//Open JDK 1.7.0_65//Postgres//Nightly Build 10/3/2014

**Comment by maurizo** [comment]
Pull request on licence: dotCMS/license#15
Pull request on enterprise: dotCMS/enterprise-2.x#242 
Pull request on core: #6903

**Comment by prasadbhvn** [comment]
Tested in nightly build 07-01-2015 Win7//Chrome//Postgres
