### ISSUE TITLE
Remove permission_reference table

### ISSUE THREAD

**Issue by dotjorgeu** [dotCMS/core#654]
We have permission table for individual permissions and permission_reference for those assets referencing its parent permissions. 

The issue is that we're using it as another level of cache. If we remove all permission_references for an assets then in the next getPermissions on it those rows get regenerated getting getParentPermissionable and then creating references to the permissions on that parent.

We can just remove permission_reference. To get assets permissions we have permissionCache then if not there we can getParentPermissionable and return those permissions. Those permissions will go cache anyway.

This way we can make faster querys (less joins less pain). We can leverage this change to introduce permission cache by URI to make easier to clean children cache on host or folders.

I don't think we can make this soon but I wanted to share the idea :)

**Comment by wezell** [comment]
This is now moot, as we load permission references lazily
