### ISSUE TITLE
Need show the thumbnail of all the templates

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6589]
Right now when you create a new html page, when you select the template, just if you select a Quest Financial template, you will get a thumbnail under the drop down, but if you select other template with a different theme, this is not appearing 

Steps: 
1- Create a new folder 
2- Select a Quest Financial template 
3- Check the thumbnail
4- Change to other template with a different theme 
5- Check the thumbnail 

SC: http://monosnap.com/image/DYh5oOCVFixrZVCH217yhugfkw5Aj4

Tested on a Oct-10-2014 distribution  // Postgres // Linux // FF

**Comment by jtesser** [comment]
@fishsmith do you want to address this on starter.dotcms.com?
