### ISSUE TITLE
Cache problems making a push publishing 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6593]
Related to #6571 

We have an error, in the push process when you follow this steps:

1- Create a new folder and push it
2- Go to the receiver side, and move the folder to other path
3- Form the sender add some asset to the folder and push it 
4- After that delete this folder from the receiver side 
5- Go to sender and push again

You will get an error in the receiver dotcms.log 
https://gist.github.com/bryanboza/e0e106810cf94ba9e036

Tested on a Oct-14-2014 distribution // Postgres // Linux // FF

**Comment by jtesser** [comment]
@bryanboza in this case you need to force push from the sender.

**Comment by shayngr** [comment]
Push is working after using "force push"
Tested on nightly build 3.1 (01/06)
Sender: Linux// H2 // Chrome
Receiver: Mac // H2 // FF
