### ISSUE TITLE
A new session identifier should be issued on login

### ISSUE THREAD

**Issue by hmboonstra** [dotCMS/core#6612]
According to the security audit a new session identifier should be issued on login to prevent Session Fixation.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15896

**Comment by wezell** [comment]
Notes to @john-thomas-dotcms  - this new behavior is the default, but it can be disabled if issues arise by setting `PREVENT_SESSION_FIXATION_ON_LOGIN=false` in the dotmarketing-config.properties

**Comment by bryanboza** [comment]
Fixed, tested on the last master // Oracle // FF... 

Tested injecting an existing session_id in a the autentificationAPI request. We are invalidating the current session and create a new one. 

**FYI**: If you take the session_id from any browser and send this in the API request when you refresh the browser page, the access_token is creating a new session. If you delete the access token and try again   we are redirecting to the login page

**Comment by wezell** [comment]
This is two parts - the first for user login which is in 5.1 and the second for api based logins which is slated for 5.1.1

**Comment by wezell** [comment]
See: #11969
