### ISSUE TITLE
Internal menu links not created as relative

### ISSUE THREAD

**Issue by lonesha** [dotCMS/core#6628]
Related to a very old issue: #1602

When creating a menu link and setting its type to internal, an absolute URL is created that contains the host name.

Version 2.5.6

**Comment by pmooneyarchitech** [comment]
The only resolution I've come across for this, so far, is to use regular expressions in VTL code to find and remove the host from the link to make it relative. It would be good if the internal link simply had an option to make it relative or not and it affects what comes out of the NavResult#getHref. That way I don't need to be concerned about creating relative links in my code, and I'll also be able to mix relative and absolute internal links together in the same code block if needed.

**Comment by jgambarios** [comment]
@pmooneyarchitech what version of dotCMS are you using?

**Comment by pmooneyarchitech** [comment]
@jgambarios  3.5

**Comment by jgambarios** [comment]
@bryanboza please check if this can be reproduce in 3.7
