### ISSUE TITLE
Move ES Content Search Code from plugin to core

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6673]
This plugin (or code that does similar stuff) needs to be baked into the dotCMS core:

https://github.com/dotCMS/plugin-dotcms-elasticsearch-content-3.0

If we do take this code, we need to write a unit test to test the use cases.

**Comment by jtesser** [comment]
SO @brentgriffin @DeanGonzalez 

This is in master-3.1 You currently have to add the Portlet to a tab.  ES Content Search 
There is also a view tool here. 

So Dean I think we need to document this.  I can help you here. 

I need to see about what we will do in starter.

**Comment by prasadbhvn** [comment]
Tested in 12-01-2015 build//Win7//Chrome//H2DB
