### ISSUE TITLE
rewire node bind address does not take Elasticsearch's zen discovery

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6709]
I have a 2 node cluster that is running on an amazon vpc.  They have external ips and internal ips of 10.0.0.100 and 10.0.0.101

When I rewire the node and try to change the bind address to 10.0.0.100, it looks like ES is not respecting that for its discovery.  I am not sure what it is doing.

![screen shot 2014-11-13 at 1 58 42 pm](https://cloud.githubusercontent.com/assets/934364/5034851/5d29fede-6b40-11e4-98d2-a1c37930e5b8.png)

**Comment by dsilvam** [comment]
https://github.com/dotCMS/enterprise-2.x/commit/626f6b321d9aac6c52d0bc96b9ce947aa89a81c3

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // MySQL // FF
