### ISSUE TITLE
Possible JGroups Memory Leak - Upgrade JGroups lib or patch code

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6717]
This was reported by one of our clients.

We believe we have identified the memory leak in our system.  It is related to a bug with the JGroups framework we are currently using (Jgroups 2.12.2).  Under high load, messages are coming in out of order and the messages are put into a map that is never cleaned up.
 
More information can be found here: https://issues.jboss.org/browse/JGRP-1618
 
We ran the patched 2.8.1 code on one of our STAGING servers and the results are below.
 
Staging Server A without the hot fix.

## Before Patching
![unnamed](https://cloud.githubusercontent.com/assets/934364/5071161/745c443c-6e3c-11e4-9c8c-114cb865b16d.png)

## After Patching
![unnamed2](https://cloud.githubusercontent.com/assets/934364/5071171/8cb2d000-6e3c-11e4-8eef-fd02d5605d32.png)

**Comment by jtesser** [comment]
QA I think testing Autoscale is the answer here

**Comment by bryanboza** [comment]
The autoscale is working fine, tested on master-3.1 // H2 // FF
