### ISSUE TITLE
Push Publishing: Push to All Servers is not working properly if one server is not Enabled

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#6725]
Regarding https://groups.google.com/forum/?hl=en-GB#!topic/dotcms/4LiJVFim5s4  and http://jira.dotmarketing.net/browse/EE-7329 

Reproduced in 2.5.6. Steps:

1. Create a Push Publishing scenario that consists in 1 Authoring Environment and 1 Receiver Environment, which it has 2 standalone servers (not clustered): Server A and Server B.
2. Configure Push Publishing between this servers and check they're all communicating fine.
3. In "Send To", for the current Receiver Environment, Enable only the Server A (by checking on its "Enabled" checkbox). Server B must remain "Disabled".
4. Create a folder in the Authoring side and Push it to the Receiver Environment.
5. After the Push is done, log in to both Servers from Receiver Side. Both servers, A and B, will have the pushed folder, despite Server B was disabled from the Push Publishing configuration.

**Comment by joseorsini** [comment]
Update: Reproduced in 3.2.2 version of dotCMS. 

Screenshots:

- Push Pub configuration in Sender Environment. Notice that Browse Node 2 (Standalone) is disabled and it has an IP: 192.168.1.19. The other server (192.168.1.86, also Standalone) is enabled. It's also set to Push to All Servers.

<img width="1286" alt="screen shot 2015-07-16 at 1 44 59 pm" src="https://cloud.githubusercontent.com/assets/1717110/8730799/27fde9cc-2bc1-11e5-9a9f-4bc688bd1bf7.png">

- Folder created in Sender Environment: /test/ and it contains 3 images.

<img width="1285" alt="screen shot 2015-07-16 at 1 45 08 pm" src="https://cloud.githubusercontent.com/assets/1717110/8730805/37ada402-2bc1-11e5-8d73-0370e17e5a05.png">

- Browse Node 1 (192.168.1.86). Folder was pushed

<img width="1284" alt="screen shot 2015-07-16 at 1 45 10 pm" src="https://cloud.githubusercontent.com/assets/1717110/8730836/6b14084a-2bc1-11e5-9097-32d0222d012c.png">

- Browse Node 2 (192.168.1.19). Folder was pushed along with its contents, despite it was disabled in the Push Pub Config:

<img width="1286" alt="screen shot 2015-07-16 at 1 45 12 pm" src="https://cloud.githubusercontent.com/assets/1717110/8730862/93243102-2bc1-11e5-83d9-f22b2482f74a.png">

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7957

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 and now works fine

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/22
