### ISSUE TITLE
Can't fix html conflicts with the integrity checker using H2 in master-3.0

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6772]
We have an error, when you try to fix html conflicts and you are using H2 as your data base.... 

Steps: 
- Configure your push environment 
- Add a folder on both sides with the same name (sender and receiver)
- In to that folder, add a new html page with the same name in both sides too
- Go to push environments, run the integrity checker 
- Try to fix the html conflicts 

Here the error: https://gist.github.com/bryanboza/061af2e2b17da9cd7a40

Tested on a generated distribution of the latest code of master-3.0

Sender: H2 // MacOSX // FF
Receiver: H2 // Win7 // FF

**Comment by jtesser** [comment]
duplicate
