### ISSUE TITLE
Old Form & Form Builder Screen when you don't have a license

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#6773]
If you go to the Forms page and do not have a license other than community, you see this old page:

![image](https://cloud.githubusercontent.com/assets/3208956/5285371/25b1d674-7ae1-11e4-92fc-9cabeca884f3.png)

Notice the reference to 1.9 and the fact that the video no longer exists.

Linux//3.0 Release//Postgres

**Comment by nollymar** [comment]
Tested on 3.6. Still happening.
