### ISSUE TITLE
Error editing host/site permissions with H2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6776]
Steps to reproduced:

-Go to: System - Sites - demo.dotcms.com - Permissions Tab
-Check Publish for Content/Files for Anon User.
-Apply Changes.

The Progress bar hangs for almost a minute. 

Log:
https://gist.github.com/bryanboza/be71ee41e6e4d789c48a

Tested with the latest code of master-3.0 // H2 // FF

**Comment by jtesser** [comment]
probably ok here. Working for us.  Maybe on a real slow machine or slow IO on the disk it could be a problem

**Comment by bryanboza** [comment]
Ok, tested on master-3.1 and if take the manually this process take  3.24 minutes to respond, during this time we have two time the follow warning in the log: 

https://gist.github.com/bryanboza/7f9c6e99fc99de5247cc

I am running dotcms locally in my mac, these are the specs: core i7 // 16 RAM // SSD,  don't think that is my machine.... Taking consideration H2 is only to test and demonstrations, but a lot of time is not normal...
