### ISSUE TITLE
Edit Contentlet lost the left action column on secondary tabs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6799]
This happened in 3.0 - 2.5.6 does not suffer from this.  To reproduce, go to the edit content screen of a "File Asset".  Click on the metadata tab and you will see the left column disappear.

## Here is 3.0

![screen shot 2014-12-05 at 10 41 09 am](https://cloud.githubusercontent.com/assets/934364/5318204/f783c5aa-7c6b-11e4-88f4-10821d5b9962.png)

## Here is 2.5.6

![screen shot 2014-12-05 at 10 40 58 am](https://cloud.githubusercontent.com/assets/934364/5318207/fd8284b4-7c6b-11e4-84ec-199828d50e49.png)

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-16 // H2 // FF
