### ISSUE TITLE
Update internal urls to http://dotcms.com

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6810]
We need to update our internal urls to dotcms.com as this is the canonical domain name.

**Comment by wezell** [comment]
Also, we need to update our favicon from:
```
<link rel="shortcut icon" href="//www.dotcms.com/global/favicon.ico" type="image/x-icon">
```
to
```
<link rel="shortcut icon" href="//dotcms.com/favicon.ico" type="image/x-icon">
```

**Comment by jtesser** [comment]
kist FYI @wezell comments are ferring to places like this in code https://github.com/dotCMS/core/blob/master-3.1/dotCMS/WEB-INF/velocity/preview_mode.vl#L12
