### ISSUE TITLE
VanityURL accepts a bad url

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6817]
If you enter / in the url and hit save, the vainty URL gets saved but does not work.  The form allows you to save a virtual link with any character in it.

This happens on 3.0 and 3.1

## virtual link DB in a bad state with no url, breaks push publishing and the VirtualLinkBundler
![screen shot 2014-12-09 at 2 32 57 pm](https://cloud.githubusercontent.com/assets/934364/5364271/5b0d20fc-7fb0-11e4-95c4-9f903c5eec8e.png)

## Hit Save and it will save, even though it won't show up in the listing
![screen shot 2014-12-09 at 2 28 29 pm](https://cloud.githubusercontent.com/assets/934364/5364272/5b0fef3a-7fb0-11e4-82dd-c6e1208abd00.png)

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF
