### ISSUE TITLE
Bugs in "What's Changed?" feature (com.dotcms.enterprise.HTMLDiffUtilProxy)

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6829]
When you edit an HTML page in dotCMS, in the Preview tab there's a "What's Changed?" tool that identifies content on the page that is different from the live version of that page. This feature makes extensive changes to the source HTML, not all of which are innocuous. Specific bugs include:
- Removes all comments, including the "<!--[if IE 8]>" type of hack that is used for backward compatibility
- Removes classes on the &lt;html> and &lt;body> tags, used for styling
- Removes lines like this one: &lt;link href='http://fonts.googleapis.com/css?family=Roboto%20Condensed%7COpen%20Sans%3A400%2C700' rel='stylesheet'>, therefore breaking Google fonts
- Removes all scripts, including carousels

Because of these bugs, the page can look very different when you use "What's Changed?", and this complicates comparisons.

**Comment by wezell** [comment]
dupe: #5680
