### ISSUE TITLE
Bug: Cannot create/edit Comments contentlets with Community licence

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6837]
Installing a new dotCMS 3.0 server for experimenting. Can't seem to create or edit Comments contentlets though: am receiving the following JavaScript error on page load: "need enterprise license".

**Comment by jtesser** [comment]
@fishsmith thoughts?

**Comment by jtesser** [comment]
I updated this on starter.dotcms.com.  I will take a new starter after I upgrade starter.dotcms.com.  Hopefully by tomorrow or this afternoon .

**Comment by shayngr** [comment]
Working as expected. Tested creating comment in the front end and editing comment on back end
Nightly build master-3.1 - 2015-01-16 16:52
H2 // Chrome & Firefox
