### ISSUE TITLE
Make sure for both Legacy and Content Pages the integrity checker works well

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6840]
Deal with moving, deleting, etc... The cases we currently handle

**Comment by jtesser** [comment]
see https://github.com/dotCMS/core/issues/6958

we need to log out the push case of a folder or other object that has the same name as a htmlpage with no extension or a file or with the same name

**Comment by jtesser** [comment]
see https://github.com/dotCMS/core/issues/6772  make sure working in all DBs

**Comment by jtesser** [comment]
https://github.com/dotCMS/core/issues/6778

**Comment by jcastro-dotcms** [comment]
Pull request in core: https://github.com/dotCMS/core/pull/7010
Pull request in enterprise-2.x: https://github.com/dotCMS/enterprise-2.x/pull/246

**Comment by bryanboza** [comment]
Now we have the basic functionality.... Some others problems was opened in others tasks...

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52855
