### ISSUE TITLE
Re-importing a bundle with categories fails

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#6848]
Reproduced in demo.dotcms.com and locally running 3.0 + Postgres DB.

Steps to reproduce:

1. Select all parent categories from the Categories portlet and add them to a bundle. 
2. Go to Publishing Queue -> Bundles and then Download the Categories bundle.
2. Delete all categories that can be deleted from the Categories portlet (some of them cannot be dropped because of dependencies with structures and contents).
3. Flush all caches in the Maintenance Tab.
4. Import the bundle in the same server, in order to restore the deleted Categories, through the Publishing Queue -> Bundles portlet.

Stacktrace:
https://gist.github.com/joseorsini/082e93a73d02c4753feb

**Comment by jtesser** [comment]
I am not sure this one is an issue anymore but lets look. 

@joseorsini just FYI your step 1 makes no sense.  You cannot select categories to add to a bundle meaning specific ones. You add categories which adds ALL of them

**Comment by maurizo** [comment]
Pull request: #7008

**Comment by jtesser** [comment]
@joseorsini we fixed the empty bundle BUT do keep in mind we prevent you from uploading a bundle into a server with the same serverId and license that generated it
