### ISSUE TITLE
"Unknown error" running SASS compiler on Windows

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#6855]
SASS compiler not working on Windows OS.

Steps to recreate:
1.  Create qa folder
2.  Upload styles.scss (https://gist.github.com/brentgriffin/f2984448f88d1df5d96d) to qa folder (via webdav or create file asset)
3.  Request css file:  http://localhost:8080/DOTSASS/qa/styles.css

See detail error message in log file here:  https://gist.github.com/brentgriffin/32582b33eafd20e0fe58#file-catalina-out-L1492

Windows 7 // Java (build 1.7.0_45-b18) // dotCMS 3.0 Rel // Postgres

**Comment by jtesser** [comment]
Lets try to update the compass gem stuff and see if this just goes away 

I answered on stackoverflow - http://stackoverflow.com/questions/28135801/latest-compass-gems-in-jar-format but I'll answer here as well.  I have no idea if this will solve your issue, but I am interested for you to try it and see if it does.  Let us know.

------------
Question:

I am using dotCMS with Sass and it appears to be using an old compiler compass-gems-0.12.2_1.jar and I'd like to upgrade to the latest. I can't seem to find any newer compass gem in jar format. Any idea how I can obtain this?
Try using the technique like the one found here: http://seanchenxi.com/java/sass-compass-jruby-single-jar it seems that you can update the compass jar yourself


Potential Ansewr
So try this:

Download the jruby jar: http://www.jruby.org/download - jruby-complete-1.7.18.jar then from the command line, run

java -jar jruby-complete-1.7.18.jar -S gem install -i ./compass-gems sass --no-rdoc --no-ri 
java -jar jruby-complete-1.7.18.jar -S gem install -i ./compass-gems compass --no-rdoc --no-ri
java -jar jruby-complete-1.7.18.jar -S gem install -i ./compass-gems less --no-rdoc --no-ri

jar cf compass-gems-latest.jar -C compass-gems .

replace the compass jar (compass-gems-0.12.2_1.jar) that ships with dotCMS with your new compass-gems-latest.jar and give that a try.

**Comment by bryanboza** [comment]
Fixed, tested on mac and is working fine.... Now just need the fix to windows
