### ISSUE TITLE
Default Value On Date/Time Field

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#6856]
When you set the default value 'now' on a date/time field and use the macro submitContent, it doesn't show/set the current date/time, it shows blank on the date and 12:00 AM on the time.

Steps to reproduce:
1- Create a structure with a date/time field.
2- Set the default value now to that field.
3- Create a widget with the submitContent macro and call that structure.
4- Call that widget in a page.

The logs shows a velocity error: https://gist.github.com/erickgonzalez/471d9ef3b3e904b0c715

JIRA Ticket: http://jira.dotmarketing.net/browse/EE-7449

Reproduced on demo and demo2

**Comment by fusion27** [comment]
Any chance you guys have a timeframe on this one?

**Comment by jtesser** [comment]
not right now
