### ISSUE TITLE
IndexRestore logic error results in large memory usage

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6865]
The restful index restore method accidentally reads in the the whole index backup file and builds an ArrayList against it.

Also, in restoring an index, we need to not put empty values back into the index, meaning, we have source json that has values like 

"person.specialty":""
"person.specialty_dotraw":"" 

These empty values blow up the mapping and cause errors in elasticsearch when sorting on person.specialty

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF... tested with a big index file  and works fine
