### ISSUE TITLE
Add html page menu is missing

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6880]
Steps to reproduce:

- Go to Site Browser > Add New drop down > HTML Page

Wrong menu is showing 

Expected behavior:
You should see the right Add/Edit HTML Page menu and be able to save the page

Test Info:
Sender: Linux // H2 // Chrome
Receiver: MacOSX // H2 // FF
dotCMS version: 3.1
Both sender and receiver are new and fresh installs (12/30).
They were built from branch Master 3.1 with the latest changes.

Attachment:
http://screencast.com/t/mJoR7Q1SM6fG

**Comment by jtesser** [comment]
@shayngr you are wrong on the menu you should see. As the flat html pages are the old pages. 

So here is what we need. 

1. In the move the select the page type needed to be the right content types and it seems you are not getting them when clicking the top right drop down button 
2. The HTML Page portlet needs to allow you to see BOTH content pages and legacy pages. When editing you get the right edit screen BUT a new page should ALWAYS be the new Content Page

**Comment by bryanboza** [comment]
Tested on master-3.1 and yes, here the problem is that you don't have options to select in the drop down selecting the type of HTML that you want to create... @shayngr  Now this is different because in 3.1 now the html pages are contents

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6922

**Comment by bryanboza** [comment]
Passed, moved to separates issues....

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52820
