### ISSUE TITLE
Deploy-jsp error

### ISSUE THREAD

**Issue by bocinfor** [dotCMS/core#6881]
There may be an error in the dotCMS\html\portlet\ext\calendar\edit_event.jsp(between 160 to 171).

**Comment by jtesser** [comment]
not sure what you are running or why but everything is compiling properly. 

If you are not sure how to do something or what is happening I would recommend using the mailing list AND/OR IRC

**Comment by bocinfor** [comment]
When running build.xml for deploy-jsp , the error messages show as follows:
jsp:  
    [javac] Compiling 387 source files to dotCMS\build\classes
    [javac] dotCMS\build\jsp\org\apache\jsp\html\portlet\ext\calendar\edit_005fevent_jsp.java:2997: : while
    [javac]           }
    [javac]            ^
    [javac] dotCMS\build\jsp\org\apache\jsp\html\portlet\ext\calendar\edit_005fevent_jsp.java:2998: : ')'
    [javac]           if (_jspx_th_liferay_005fbox_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
    [javac]                                                                                                   ^
    
BUILD FAILED
