### ISSUE TITLE
The CMS allows password change without reathentication

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6882]
dotCMS/Core/ #6614

Reproduced in master-3.1/Win7//Chrome
Please see http://screencast.com/t/Srs6xsWs

**Comment by jtesser** [comment]
looks like we missed this one @jcastro-dotcms

**Comment by jkshapiro** [comment]
There should be an "e" in "Change Password" on the button in the video...

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6899

Also, the following changes in the starter are required:

1. In this velocity file: /application/vtl/pages/user-account/account-detail.vtl:
   1.1 Add the missing "e" to the "Chang Password" label in the submit button.
   1.2 Fix the "name" attribute of the following fields to match the fields in the Struts Form class:
      1.2.1 "Password"           => Set it to "password".
      1.2.2 "New Password"   => Set it to "newPassword".
      1.2.3 "Verify Password" => Set it to "verifyPassword".

**Comment by jtesser** [comment]
I need to take a new starter but you can test QA by manually making the changes above

**Comment by prasadbhvn** [comment]
Tested in nightly build 06-01-2015 Win7//Chrome//H2DB
