### ISSUE TITLE
Dates not working with RestAPI

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6883]
Date filtering is not working when Querying through the Content Rest API.

**Comment by jtesser** [comment]
so as @maurizo has worked on this we realized no changes are needed here

you can query this way 
http://demo.dotcms.com/api/content/render/false/query/+structureName:Blog%20+Blog.sysPublishDate:%5B20110826%20to%202011082616%5D%20+languageId:1%20+deleted:false%20+working:true/orderby/modDate%20desc

See https://groups.google.com/forum/#!topic/dotcms/ptjUubMTuzc

**Comment by prasadbhvn** [comment]
Still unable to get the content from REST API. Tested in nightly build 08-01-2015 Win7//H2DB
Please see http://screencast.com/t/jT1MxuAV

**Comment by jtesser** [comment]
SO I remarked needs QA this works if you change the  URL to what we said it should be in the issue

In addition I created a new issue to handle the modal Show Query Window examples

**Comment by prasadbhvn** [comment]
Tested in nightly build 09-01-2015 Win7//Chrome//H2DB
