### ISSUE TITLE
Security Validation Error in the log when you start a new server 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6886]
After the fix #6611, now we have new validations methods adding users, the problem is that we have some errors with some users in the starter.zip.

Then we have security errors in the log... The main problem is because in the starter, the Jane user have a blank space at the end... and this is not allowed by this validations then is displaying an error ... 

Here the log: https://gist.github.com/anonymous/f50e13dcbd704802a836

Tested on master-3.1 // H2 // FF

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6890

**Comment by prasadbhvn** [comment]
Tested in master-3.1//H2DB//Chrome
