### ISSUE TITLE
Server is not compiling CSS on front end

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6887]
On a fresh dotCMS (master 3.1), server is having issues loading CSS on the front end when compiling

Test info:
Linux // H2 // Chrome
dotCMS version: 3.1

Log:
https://gist.github.com/shayngr/9ebd4703553fa7ec24fb

To reproduce:
System using fresh install (01/05).
Build from branch Master 3.1 with the latest changes.

**Comment by jtesser** [comment]
I think we are ok here. I think there was something in the starter with the template. 

If a specific page is giving you issues shay let me know
