### ISSUE TITLE
We need to trim blank spaces at the end

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6891]
#6886
Reproduced in master-3.1//H2DB//Chrome.

You will see errors in the log when you save user with white spaces at the end
Please see  http://screencast.com/t/BocsWvTt
Error in the log: https://gist.github.com/prasadbhvn/3c5c647b213478ecb069

**Comment by jtesser** [comment]
@jcastro-dotcms lets make sure.  Maybe @prasadbhvn wasn't running the latest

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6895

**Comment by bryanboza** [comment]
Fixed, tested on master 3.1 //H2 // FF
