### ISSUE TITLE
Enhancement: Allow multiple containers of the same type in a template

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6893]
If a template needs four different "Content (Generic)" regions, then we should be able to insert one "Content (Generic)"-containing container four times. It's silly to have identical containers with names like "Default 2 (Page Content)", "Default 3 (Page Content)" etc.

**Comment by jtesser** [comment]
This isn't something we are currently going to be able to do.  While I understand what you are saying it goes against the dotcms thinking. Content lives in a container on a page.  That is how we work.  No matter where you place that container in the template
