### ISSUE TITLE
Error opening hmtl page after cut/paste

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6898]
Message "An unexpected system error occurred" is showing when I try to open an html page that was previously created in one folder then moved to another folder

To reproduce:
1) Go to Site Browser and create an html page inside a folder
2) Cut/paste that page into another location
3) Try to open the page

System will show an error

Test info:
 Master-3.1 // H2 // Chrome
Log: https://gist.github.com/anonymous/afc2cd22bd249c4165eb
Attachment
http://screencast.com/t/Xi7nFC6Jd8k

**Comment by jcastro-dotcms** [comment]
I was not able to reproduce this issue.

These are my test scenarios:

1. In "HTML Pages" page:
1.1 Create a page under any folder.
1.2 Go to "Site Browser" page, select the new page and cut it.
1.3 Paste the page in a different folder, and open it.
1.4 The page is opening up successfully.

1. In "Site Browser" page:
1.1 Create a page under any folder.
1.2 Select the new page and cut it.
1.3 Paste the page in a different folder, and open it.
1.4 The page is opening up successfully.

**Comment by jtesser** [comment]
@shayngr can you test again. You might need to wait for the nightly build tomorrow

**Comment by bryanboza** [comment]
After test with multiple time i am not able to reproduce on master-3.1 // H2 // Chrome

**Comment by shayngr** [comment]
Working as expected.
Tested on branch master-3.1.
H2 // Chrome/FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52882
