### ISSUE TITLE
Error adding new users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6900]
When you try to add a new user we are showing an error message, but the system is saving the user 

To recreate:
- Go to the user portlet 
- Add a new user information 
- Click to save the user

Here the video:
http://monosnap.com/file/G2FnjcTUcOSIRYKlZ8TJAHIpxu54Uk

Tested on master-3.0 // H2 // FF

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6941

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF
