### ISSUE TITLE
The CMS allows password change with out New Password

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6901]
#6882 
After made manual changes , reproduced in nightly build 06-01-2015 Win7//Chrome//H2DB
Please see http://screencast.com/t/GzV9Qa1QI

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6927

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF..... After make the steps of the issue #6882 manually... The validation works fine... Now we need make that in the new starter
