### ISSUE TITLE
XML Site map enhancements  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6902]
Related to #6727 

After the last fix, I am able to reproduce the same problem here, does not make sense if you have a index.html page to enable the show on menu option here, since is a index page must not appear in the menu... 

The problem here is if you don't have this option enabled the system is not adding the page to the site-map file.... Right now only if the page have the show on menu property and the html page is named index works fine....

In the other hand, if you create content in multiple hosts of a Content Type where the Host/Folder is the System Host and is using URL Maps, the site map for each host should generate the url mapping links for that Content Type, right now is only generating those links in just one Host site map. This is working if you test with a new host, but for example if you use some structure with system host the system should create individual links for every host...

Tested on master-3.1 // MySQL // FF

**Comment by jgambarios** [comment]
Fixed in #7457
