### ISSUE TITLE
Can't perform batch actions on content if it has a custom workflow

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#6904]
You can't perform batch actions on content if it has a custom workflow. I think you should be able to do this from the content search screen. For example if my workflow allows me to achieve content I should be able to select all and active it not have to go piece by piece.

**Comment by jtesser** [comment]
@fishsmith this is on purpose as you also lose the context menu items.  Right now we don't have a way to match the batch actions to workflow meaning should this be allowed right now.

**Comment by fishsmith** [comment]
I understand the issue I was adding this as an enhancement to be considered in a future release.

**Comment by wezell** [comment]
The only way currently to execute batch workflows is from the workflow
listing screen itself.  We would need to reproduce some of the logic from
that screen (filter by workflow, then workflow step, then you can execute)
on the content listing screen

On Wed, Jan 7, 2015 at 11:14 AM, Jason Smith <notifications@github.com>
wrote:

> I understand the issue I was adding this as an enhancement to be
> considered in a future release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/6904#issuecomment-69045123>.
>



-- 






3250 Mary Street
Suite 405
Miami, FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jkshapiro** [comment]
This would be most helpful.
