### ISSUE TITLE
Can't add html page in a different languages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6906]
After the new improvement #6201,  when you try to add a new html page to any structure,  this in any language different to english, the system add the page without problems, but when you try to open the page preview, this is generating a NPE....
 
To recreate: 
- Add a new HTML structure 
- Create a new folder 
- Add a new HTML page in any language different to English in to the created structure, and under the created folder
- Go to the folder and try to open the page preview 

SC: http://monosnap.com/image/sGX9DsDhr7xRXeHiT09NiNjrzUDo1o

Here the log: 
https://gist.github.com/bryanboza/98471372bc56477f40aa

Tested in master-3.1 // MySQL // FF

**Comment by jtesser** [comment]
@wezell i would like to discuss this with you when you are back on friday

**Comment by wezell** [comment]
OK, I'll be in tomorrow.  Let's talk then

**Comment by jtesser** [comment]
In addition to the other issues related to this task @dsilvam as we discussed we need to solve the issue when you have pages in languages that are NOT the default language 

Rules are as follows
1. If the system has more then 1 language configured, (We need this cached) then we show the flags like the relationships do on the edit content screen.  The different is there will be no disabled flags.  We only show the flags for versions that actually exist
2. These flags are clickable and should have the context menu on them that the page name does but specific to that language

**Comment by jtesser** [comment]
1. Make description column header go away and on pages change the value from friendly name to title 
2. Add short language name next to page and alter the content search manager to do the same
3. Add the language drop down control next  to ....

**Comment by jtesser** [comment]
@dsilvam while in the site browser fix this also https://github.com/dotCMS/core/issues/7007

**Comment by jtesser** [comment]
@dsilvam make sure this works with the latest fix. https://github.com/dotCMS/core/issues/6987
