### ISSUE TITLE
Missing blank space on HTMLPage content type

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6907]
Refer to #6201

If you navigate to Content Types and click the drop down to select the content, you will see there is a  missing blank space on "HTMLPage". 

It should read "HTML Page" instead of "HTMLPage"

![htmlpage](https://cloud.githubusercontent.com/assets/8741846/5651892/308ce3da-9671-11e4-88f7-8f80a7531ef2.png)

**Comment by maurizo** [comment]
Pull request: #6956

**Comment by bryanboza** [comment]
Passed... tested on master-3.1
