### ISSUE TITLE
Unable to change content in html page

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6909]
Page is not allowing you to change or delete its content.

To reproduce:
1) Create a new folder 
2) Add a new html page inside that folder and choose a template
3) Add Content (Reuse Content) to the page and visualize in the front end
4) Go back to edit the page and change to a different content
5) Visualize in the front end
6) You will see how the page still shows the old content

Test info
Linux // H2 // Chrome

Attachment:
http://screencast.com/t/j6Feifou107

**Comment by jtesser** [comment]
@shayngr you cannot see these changes until you publish the pages.
