### ISSUE TITLE
We need auto select the html page structure if only have one option 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6910]
Maybe should be useful auto-select the structure if you only have one option in the drop down, like when you need select the push publish environment... 

SC: http://monosnap.com/image/yWqL7ooEiNHl5cyVZg7NvVojkQTggc

Tested on master-3.1 // MySQL // FF

**Comment by jkshapiro** [comment]
One is always special. http://www.cooper.com/journal/2015/01/easy-win-citibank
