### ISSUE TITLE
Need validate one html structure is selected when you are creating a new page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6911]
When you try to add a new html page, you need select the html structure, but if you don't select nothing and click to select button, the system is redirecting to add a new simple content page....

Steps: 
- Create a new folder
- Right click and add new page in the menu
- Click in the select button 

SC: http://monosnap.com/image/1Xor5dkiFyNo2HxZGd8s88Z9FF8XYP

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
basically we should validate the input with client side JS

**Comment by jtesser** [comment]
@samuelmortha 2 things

1. We need to default to our default HTMLPage Structur like File Asset does
2. Validate in JS that a structure is selected. Should work like the File Asset Modal does when selecting what file

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-16 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52820
