### ISSUE TITLE
Vanity URLs with parameters do not work in 3.1

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#6913]
Automated test for test case 14101 fails on 3.1 nightly builds. This tests add a vanity URL that is supposed to redirect to "/about-us/locations/index.html?direction=33133&milesR=100". Instead of redirecting to this location, server returns a 404.

1.  Create a vanity URL for demo.dotcms.com that is to redirect to "/about-us/locations/index.html?direction=33133&milesR=100"
![image](https://cloud.githubusercontent.com/assets/3208956/5653510/7149a46c-9680-11e4-93cb-2d21fed8e01e.png)

2.Access vanity URL (i.e. "http://localhost:8080/14101") and receive 404 error page

This test fails on both 3.1 nightly builds but has run correctly on 3.0 builds many times.

Ubuntu 14.04 // Java (build 1.7.0_72-b14) // 3.1 Nightly build 2015-01-06 20:52 // H2 // Firefox & Chrome

**Comment by jtesser** [comment]
yea this and the previous issue are related to CMS Filter I think so only in 3.1

**Comment by wezell** [comment]
There was a unit test committed with the changes to the cmsfilter.  It does a number of checks against vanity urls but it seems this was missed.  We need to make sure to hook up the Unit test and make sure that these cases are checked, fail, then fixed.

**Comment by jtesser** [comment]
@wezell for sure that is the way we will do it .

**Comment by jtesser** [comment]
also the folder is broken here when on page you do something like locations/?test=5555 but if you have no / before the ? it is broke

**Comment by bryanboza** [comment]
Fixed, now this is working fine... tested on master-3.1 // H2 // FF
