### ISSUE TITLE
Need more specific messages adding new html pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6914]
When you try to add a new html page and leave in blank the url field the system is showing the follow error: message.htmlpage.url.required

Maybe here we need a more clear message here

SC: http://monosnap.com/image/wWV9cDrSeC3tjQ6rQ5mWpPvbUu1ODt

Tested on master-3.1 // H2 // FF

**Comment by shayngr** [comment]
Working as expected.
Tested on nightly build master-3.1 (2015-01-08 20:32).
H2 // Chrome

![url message](https://cloud.githubusercontent.com/assets/8741846/5680432/e55e584a-97d2-11e4-89dd-23b60d3ddc54.png)
