### ISSUE TITLE
3.1 Removes the ability to add a folder at the site level from the "Add New" button

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#6915]
1.  Open site browser
2.  Without clicking on any folders, click on the down arrow of the "Add New" button
3.  Notice that you are not able to add a Folder now - used to be able to do this in 3.0 and previous versions
![image](https://cloud.githubusercontent.com/assets/3208956/5654449/ced68f70-9688-11e4-9874-6caac8bad828.png)
4.  If you select a folder on the left hand side, then the add Folder option appears
![image](https://cloud.githubusercontent.com/assets/3208956/5654464/fbadb5b4-9688-11e4-90e3-90433e6ca2cf.png)

This missing functionality is causing the automated test for test case 14105 to fail because it is unable to add a folder.

Ubuntu 14.04 // Java (build 1.7.0_72-b14) // 3.1 Nightly build 2015-01-06 20:52 // H2 // Firefox & Chrome

**Comment by jcastro-dotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/6940

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF
