### ISSUE TITLE
System is not pushing content

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6916]
System is not pushing any content

To reproduce:
1) Set up a push publish configuration (sender/receiver)
2) On the sender navigate to Content > Content Search
3) Click "Add New Content" drop down and select any content (i.e. generic content type, banner, file asset, etc)
4) Fill out the information and save/publish the content
5) Push the content you created

System will show an error message on Publishing Queue > Status/History tab

Test info:
Sender: Linux // H2 // Chrome
Receiver: MacOS // H2 // FF
dotCMS version: 3.1 nightly build 2015-01-07 20:52

Logs on receiver:
https://gist.github.com/shayngr/4e4d4850293ceccde657

**Comment by brentgriffin** [comment]
@shayngr - did you run integrity checker?  If so, does it report everything is good?

This seems to be an issue with different structure inodes

**Comment by jtesser** [comment]
@shayngr also are you sure you got a good install on the receiver end?

**Comment by shayngr** [comment]
Yes I would say the install is good on the receiver end, integrity checker is not showing conflicts. 
Actually I just created and pushed a single folder and it was pushed successfully, so I pushed a new file asset object and basically failed with the same error on the log

**Comment by shayngr** [comment]
Actually push publish is working correctly with contents, I tried this again and it works.
Sender: Linux // H2 // Chrome
Receiver: MacOS // H2 // FF
dotCMS version: 3.1 nightly build 2015-01-07 20:52

**Comment by dsilvam** [comment]
Just to double check, this worked for me also, Postgres and OS X on both sides.
