### ISSUE TITLE
Content Search Filter "All" Not Clear

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#6917]
Under the filters we have "Locked, Unpublished, Archived, All".

Selecting "All" should display all sub-filters, but it does not, it only shows: Unpublished, Locked, not Archived.

We need to find a more intuitive way to present this.

![screen shot 2015-01-08 at 11 47 12 am](https://cloud.githubusercontent.com/assets/1823543/5666314/b2922a0a-972c-11e4-8884-daffc221afcb.png)

**Comment by jkshapiro** [comment]
See also #4858

**Comment by john-thomas-dotcms** [comment]
Suggestions:
* Use the word "Active" (or maybe "Current" or something like that) to show what is currently shown when you select "All".
* Add a new "All" selection that really does show all (including Archived and Unpublished).
* Add a "Published" selection (which just shows Published).
