### ISSUE TITLE
Browser window muddled - this needs to not happen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6919]
This happens periodically - especially when there is a new installation up and running.

I am not sure how to reproduce 100%, but it looks like a race condition between the resize javascript and the rendering

![screen shot 2015-01-08 at 2 22 10 pm](https://cloud.githubusercontent.com/assets/934364/5668990/081626ba-9742-11e4-934d-387d19745aab.png)

**Comment by jtesser** [comment]
We think this is fixed here

https://github.com/dotCMS/core/commit/3f91c60b330e2610ac2d3f3082e57c8130377166#diff-9af0270bb61d58048e2bd997ae23aa0a

**Comment by bryanboza** [comment]
Passed, I am not able to reproduce now...
