### ISSUE TITLE
Unable to add events on calendar

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6920]
Refer to #6240

System is showing an error when you try to add any events from the backend

1) Navigate to Calendar 
2) Click on "Add Event"
3) You will see the error "Ooops, sorry. This has caused a problem"

Test info:
Sender: Linux // H2 // Chrome
Receiver: MacOS // H2 // FF
dotCMS version: 3.1 nightly build (2015-01-07 20:52)

Logs:
https://gist.github.com/shayngr/1fbef5c5788ef43679d9

Video capture: http://screencast.com/t/qO5pX5iI4L

**Comment by bryanboza** [comment]
Duplicated with #6888
