### ISSUE TITLE
Can't assign the redirect URL to the html pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6923]
If you create or edit some page and assign some other page to redirect in the advanced properties, the system is saving the page and the changes, but we are loosing the redirection information... 

To reproduce: 
- Go to create or edit any html page
- Assign some page to redirect 
- Save the changes 
- Enter to edit again and check the redirect field 

Here the video: http://monosnap.com/file/TMmdKAKL8tW5X17x5zGA9NsJ1DyU2d

Tested on master-3.1 // H2 // FF

**Comment by bryanboza** [comment]
FYI: No errors in the log here

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7017

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-20 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52931
