### ISSUE TITLE
Move UrlRewriteFilter up in web.xml

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6926]
We need to move the mapping of the UrlRewriteFilter above the CMSFilter so we can use it to correctly process forwards.

**Comment by jtesser** [comment]
Yes but there are issues both ways.  Need to see how it effects new CMS Filter. But some more control here is for sure needed

**Comment by wezell** [comment]
Notes

Unmapped SalesForceAuthFilter by default - if needed it can be remapped
Unmapped PdfServlet - we would recommend 
Unmapped all servlets used by jasper reports
Unmapped PermalinkServlet - was used for old school ping backs and pathing like /permalink/{id}
Unmapped IconServlet - used by admin tool
Unmapped CampaignReportingServlet - was used for email campaigns
Unmapped AdminControlServlet - not used
Unmapped TitleImage -  (now we reply on web fonts and css)
Unmapped ThumbnailImage - Use restful image url
Unmapped XSPFServlet - (used in old mp3 macro)
Unmapped SlideShowServlet - used in old slide show macro
Unmapped SimpleCaptchaServlet - we recommend implementing this using a 3rd party library
Unmapped ImageServlet - used only by the Configuration Portlet
Unmapped AudioCaptchaServlet - we recommend implementing this using a 3rd party library
Unmapped JMySpellCheckerServlet - enabled browser based spell checking in the wysiwyg

**Comment by wezell** [comment]
We will need to provide the old web.xml for legacy clients who are upgrading.

I can see TitleImage, ThumbnailImage, SimpleCaptchaServlet causing issues for client coming from 1.x

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9154

**Comment by jgambarios** [comment]
@john-thomas-dotcms please help us documenting these changes as Will pointed in: https://github.com/dotCMS/core/pull/9154#issuecomment-222232280
-Thanks

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF, tested with the tuckey plugins and works as expected

**Comment by john-thomas-dotcms** [comment]
Added to 3.6 release notes (not yet published, even on auth, but content is in there).
