### ISSUE TITLE
System does not allow to log back in. Login page gets stuck at 100%

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#6928]
If you change the value of policy auth.simultaneous.logins=true to "false" specified in the portal.properties, the system successfully restricts to have simultaneous logins from different sessions, however when you try log back in, the login page gets stuck at 100%.

To reproduce:
1) Go to the file portal.properties and change the value of policy auth.simultaneous.logins=true to "false"
2) Open a browser and log in to dotCMS (i.e.: log in as Admin)
3) Open another tab in the same browser and log in with the same user as before (Admin). You will see the system shows successfully the restriction
4) Try lo log in again

The login page gets stuck at 100%. Clearing the browser cache does not work.

Test info:
Linux // H2 // Chrome
dotCMS version: master-3.1 nightly build (2015-01-08 20:32)

Log: https://gist.github.com/shayngr/545a13a58212bcf72255

Video capture:
http://screencast.com/t/fS2VYLCv485

**Comment by jtesser** [comment]
this is right. You need to destroy your session before stop 4 in the browser u r logged in as admin with 

/destory.jsp

**Comment by vianneychacon** [comment]
I was able to reproduce this issue on versions **3.5.1** and **3.6.0** using the starter site. After setting ``auth.simultaneous.logins=false`` on ``portal.properties``, admin user can login into the backend without problems the first time. Once logged out (by hitting the logout button or /destroy.jsp), the login process stalls at 100% when trying to login again. Calling /destroy.jsp or hitting logout produces the same behavior.

I’ve also noticed that even if the login process is hanging out at 100%, the backend session is successfully created and access to the backend is granted by hitting another url (e.g. /admin).
