### ISSUE TITLE
Site search is not including the new html pages contents 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6935]
Since now the html pages are contents, when you run a new site search job, the system is not including the content of this pages and neither the pages... 

Steps: 
- Add a new html structure 
- Add a new page to this structure 
- Add a new content to the created page and publish it 
- Go to site search and create a new index and run the complete job 
- Try to search for the page or the content of the page 

Tested on master-3.1 // H2 // FF 

FYI: No errors in the log, and if you try with a old html page the content is showed in the results. The problem is with the new pages

**Comment by dsilvam** [comment]
https://github.com/dotCMS/enterprise-2.x/commit/62666ce4da205e6cd57db62a228d21b90299a336

**Comment by bryanboza** [comment]
Here we need the fix #7050 to test

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-27 // H2 // FF
