### ISSUE TITLE
Unable to see the events details from front-end 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6937]
Related to #6240 

After this fix now we can't see the event details from front-end, we are redirecting to the 404 error page.... 

Also if the event is in spanish you will have the follow error in the log: 

WARN velocity.DotResourceLoader: Error ocurred finding resource 'live/a333f853-2550-4f36-b67a-04e91bb1cb7a_2.content' exception: org.apache.velocity.exception.ResourceNotFoundException: Contentlet is a miss in the cache

FYI: To recreate just need add some events in english and spanish and go to the front-end and try to see the event detail page 

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
@samuelmortha if you give me the change to the starter that is needed here in a comment assuming that is the issue I will make it

**Comment by jtesser** [comment]
this is working on master-3.1

**Comment by bryanboza** [comment]
Fixes, tested on master-3.1 // H2 // FF
