### ISSUE TITLE
Latest TinyMCE upgrade broke plugins that extends TinyMCE

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6949]
Documentation example plugin here is broke.

**Comment by dsilvam** [comment]
Fix consisted in altering the plugin.properties file of the tinymce_extended plugin, by removing the plugins and themes we don't have. (Checked against the plugins and themes folder of tinymce)

In addition, I uncommented the property "ROLE_KEY_SIMPLE=Content_Contributor" in the same file,  which was causing a NullPointerException when commented.

Daniel

**Comment by brentgriffin** [comment]
@dsilvam and @jtesser - wouldn't it be better to take out the line that was commented out rather than uncommenting it?  What is this going to affect?

**Comment by jtesser** [comment]
@brentgriffin it is part of the JSP only in the plugin.  It is an example of what you can do. So I think it is ok

**Comment by bryanboza** [comment]
Ok, now we don't have the NPE, and if the fix is ok, then marked as passed
