### ISSUE TITLE
The tail in the log manager don't show the logs if you change the dynamic_content_path

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6953]
As part of the dotcms options in the file dotmarketing_config.properties, we have the "DYNAMIC_CONTENT_PATH" variable, this is to change the system logs path ... If you change this option, the tail of the log manager tool in our configuration is  not showing the log... This because is not finding the files in the default path

Here the SC: http://screencast.com/t/ogUqNSSdclc

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
this is true.  Once you do this you need to configure manually the logs 

We can try to do some more work here to pick this up in the future

**Comment by jtesser** [comment]
Actually talked to @bryanboza and I think the issue was not changing TAIL_LOG_LOG_FOLDER and the log4.xml to the right location

**Comment by bryanboza** [comment]
The log4j.xml have a  DOTCMS_LOGGING_HOME variable that is taking the value from the dotmatketing-config…. If i change the two prop:
DYNAMIC_CONTENT_PATH and TAIL_LOG_LOG_FOLDER, the tail show all the logs in the drop down list, but have a 403 forbidden error when try to open 
@brentgriffin maybe you can try it... Just to make sure that not is an issue...
