### ISSUE TITLE
HTMLPages as Content and Permission

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6959]
The permissions should work just like the legacy html pages. 

So no new entry but when applying permissions to pages should apply to both kinds of pages

**Comment by jgambarios** [comment]
For this issue we need to execute this queries on the starter site and generate a new one:

```
update permission_reference set permission_type = 'com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage' 
where permission_type = 'com.dotmarketing.portlets.htmlpages.model.HTMLPage';

update permission set permission_type = 'com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage' 
where permission_type = 'com.dotmarketing.portlets.htmlpages.model.HTMLPage';
```

I created an upgrade task for upgraded users.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-22 // H2 // FF
