### ISSUE TITLE
Error trying to add new folder at the site level from the "Add New" button 

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6960]
1) Open site browser
2) On the root (without clicking on any folders), click on the down arrow of the "Add New" button

![html page](https://cloud.githubusercontent.com/assets/8741846/5724236/f6ef90fc-9b0f-11e4-8795-d95938b0b015.png)

![ooops sorry](https://cloud.githubusercontent.com/assets/8741846/5724288/3e209c6e-9b10-11e4-922c-a4047aa98518.png)

You will see the error above, however if you select a folder on the left hand side, this error is not showing. 

Logs:
https://gist.github.com/shayngr/ce398a01f25101af4af3

Tested on
Ubuntu 14.04 // 3.1 Nightly build 2015-01-12 21:51 // Postgres // Firefox & Chrome

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7028

**Comment by shayngr** [comment]
Fix is working
Tested on dotCMS version: 3.1 nightly build (2015-01-20 22:35)
Linux // H2 // Chrome
