### ISSUE TITLE
HTMLPages as Content and Workflow

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6961]
We need to ensure all workflow works from the html pages. 

In addition we need to add the workflow controls to Edit Mode. 
In summary we need a way to get a RESTful/json list of available workflow actions for any given piece of content based upon the user, the step and the locked/unlocked state of the content. In edit mode, we need use this to build the controls/actions for the left hand nav

**Comment by jtesser** [comment]
we can remove the button in edit mode for migrate to content button on edit mode

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-16 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52823
