### ISSUE TITLE
Identifier.java setUri looks broken to me with new Pages as Content

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#6962]
Is expecting page extensions 
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/beans/Identifier.java#L161

**Comment by wezell** [comment]
I looked at that and could not see where it was being used.  It looked like
legacy code to me.

**Comment by jtesser** [comment]
well no it is being used.  But we are not call it in places where it effects the new content. I am inspecting it. 

XMLSiteMap uses it. Creation of new identifies in SOME cases. I actually think it needs to be deprecated or at least doced on what it does.  I am on it.  Some JSPs also use it
