### ISSUE TITLE
The event detail window need styling help if you add big image 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6963]
In the event detail page if you add a big size image, the system is showing some fields over the imge, maybe we need some styling help here

To reproduce
- Create a new event 
- Add to the event description some images of the ./resources/images 
- Go to the event detail page on front-end

SC: http://monosnap.com/image/wyMkgboWgq5MUzmi4wwMOifHBqGyk8

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
not much for us to fix here.  And it is not a bug as this is just starter data
