### ISSUE TITLE
The ES portlet is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6964]
Related to #6951 

If you add a new custom portlet and set the ES Portlet, we have an error when you click on it 

Here the SC: http://monosnap.com/image/7KmOwIgF5t5GeeynX2ytHGEdNLhaiE

And the help window neither works: http://monosnap.com/image/QRmLW3GFuO4Jr3i9fDvUK91QQKRoZE

Tested with the latest changes of master-3.1 // H2 // FF

**Comment by bryanboza** [comment]
FYI: This is the log error: [13/01/15 11:32:32:940 CST] ERROR elasticsearch.ESContentResourcePortlet: javax.servlet.ServletException: File &quot;/WEB-INF/jsp/escontentresourceportlet/render.jsp&quot; not found

**Comment by jtesser** [comment]
this works for me and @brentgriffin can u see why not for you.

**Comment by brentgriffin** [comment]
This is working properly for me running last nights build.

MaxOSX//H2//Chrome

**Comment by brentgriffin** [comment]
Ok, seems to happen only when I put it on its own tab.  When I add to an existing tab, it seems to work fine but when I create a new tab and put it on that tab, it breaks.

**Comment by bryanboza** [comment]
Ok, seems the problem here is when you add to a separated tab, if you add to the system tab, works fine 
Then to recreate: 
- Go to system/ Roles and Tabs
- Add a new custom tab
- Add the ES search portlet tool 
- Enable to see this tab 
- Click to the tab

**Comment by jtesser** [comment]
must be a bug with the rest portlet itself

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF
