### ISSUE TITLE
We need auto-update the vanity URL if you change the page name

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6965]
Since the vanity URL is a reference, maybe we need auto update if you go to the page properties and change the name or the extension of the page... Right now this is now working in the 3.x versions, neither in 2.x... 

To recreate: 
- Create a new folder 
- Add a new html page in to this folder 
- Create a vanity URL redirecting to the new page
- Go to the page properties and modify the page name 
- Check the vanity URL properties 

SC: http://monosnap.com/file/ietNQFQc2EeR9Nivm9y0hrpWYXbviK

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
we've never doe this.  I am not sure we should but can leave open an a possible improvement
