### ISSUE TITLE
ES portlet visual improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6967]
When you add the ES portlet tab, maybe some things need styling help:

- This tool do't have icon: http://screencast.com/t/NaJiMcaU3
-  In the help window the scroll bar is over the close button: http://screencast.com/t/GoqU4QuBdr

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
currently there is another issue on this that @wezell is handling
