### ISSUE TITLE
ElasticSearch 0.90.3 NPE on sort

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#6968]
As found in Dotcms 3.0.1, https://github.com/elasticsearch/elasticsearch/issues/3470. Superseded by ES update in 3.1. https://gist.github.com/chrismccracken/41bdf009d78bf9410059. Fixed w/ ES lib update to 0.90.5

**Comment by chrismccracken** [comment]
Created for hotfix tracking purposes

**Comment by jtesser** [comment]
so this should go away with the update to elastic search but not much more for us to do.  We are updating it in 3.1 

But this is known and as been this way every since we implementing ES in 2.0
