### ISSUE TITLE
Error when saving content with empty relation

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#6969]
Using dotcms 3.0 after migration from 2.5.4.

When we trying to save content with empty relation
![image](https://cloud.githubusercontent.com/assets/2236103/5741940/8f1b0c20-9c1f-11e4-9571-1a28c8de5f45.png)
have an error: These relationships have the following errors: 
One to Many Relation Violated:
Homepageslideshowitem-BannerAdManagement
![image](https://cloud.githubusercontent.com/assets/2236103/5742132/e99c63be-9c20-11e4-8d24-85beb73fe40e.png)

and server.log contains
ERROR com.dotcms.content.elasticsearch.business.ESContentletAPIImpl - com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Contentlet's fields are not valid

Relation is one to many and not required:
![image](https://cloud.githubusercontent.com/assets/2236103/5742029/38bc1e40-9c20-11e4-8471-d6dcb541beb9.png)

Also we've checked out that changes from https://github.com/dotCMS/core/issues/6627 exist in out version of dotcms.

We assume, that migration of relations was with errors.

**Comment by jtesser** [comment]
I am not sure what is happening but I don't see how to reproduce this. Maybe you have an issue with your specific data, DB or implantation.  If you have a support contract I would reach out to them unless you can provide a way fro us to reproduce the issue
