### ISSUE TITLE
Unable to add new categories to bundle

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6973]
When you create a new category and try to add it to a bundle, it doesn't get added.

To reproduce:
1) Navigate to Content Types > Categories
2) Create a new category
3) Add that new category to an existing or new bundle
4) Navigate to Site Browser > Publishing Queue > Bundles

You will see neither the existing nor the new bundle contain the category 

Tested on
Ubuntu 14.04 // 3.1 Nightly build 2015-01-13 20:52 // Postgres // Firefox & Chrome

video capture:
http://screencast.com/t/YeGqwhSCArN

**Comment by brentgriffin** [comment]
@shayngr - categories have to be pushed separately from content and have to be pushed all at one time.
