### ISSUE TITLE
Typo in the MultiselectMap on 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6978]
So the issue is that in the MultiSelectMap class there is a typo....

Instead of .getValues() to return a List<String> of values, the method is singular .getValue()....  Once I changed the method name I started to get them.

We need to add another method for getValues that just calls the legacy getValue for consistency.

See this thread:

http://dotcms.com/forum/?place=msg%2Fdotcms%2F7w92mErcWtQ%2F2_zCWlGYGtgJ

**Comment by ethode** [comment]
@wezell thanks for follow up on this sir
