### ISSUE TITLE
Html pages: URL validation 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6979]
Related to #6803 

When you try to add a new page with some special character in the url field, the system is showing an error message with a list of some examples with not allowed characters... This include characters like: # , {, } and some others and the system is allowing save pages with that... 

SC: http://screencast.com/t/B5GVXxk2fB7

Tested on master-3.1 // H2 // FF

**Comment by jtesser** [comment]
ensure we do not allow any of these characters in the URL

**Comment by shayngr** [comment]
URL still allows to save page with special character "\"

![special character](https://cloud.githubusercontent.com/assets/8741846/5837480/36ccba3e-a145-11e4-9307-443ac107b74b.png)


Tested on dotCMS version: 3.1 nightly build (2015-01-20 22:35)
Linux // H2 // Chrome

**Comment by jtesser** [comment]
@shayngr I updated the code here.  Should be in next nightly build so test again tomorrow

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-20 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52928
