### ISSUE TITLE
(Feature) Select Multiple Files in Site Browser

### ISSUE THREAD

**Issue by ethode** [dotCMS/core#6981]
I have a lot of clients that want to mass archive/unpublish etc files in the site browser but wind up having to do it one by one... This would be a huge feature to save time and aggrivation

**Comment by jtesser** [comment]
you can do it with files as content in the content search manager just FYI

**Comment by ethode** [comment]
@jtesser thanks for the reminder, I did forget about that.  Will definitely work for the situation we ran into today.  Thanks!
