### ISSUE TITLE
Unable to push content in a different language

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#6987]
If you create a new language and try to push a content with that language, it fails.

To reproduce:
1) Create a push publish environment
2) Navigate to System > Languages. Create a new language (french, chinese, etc)
3) Go to Content > Content Search. Select the new language and add a new content (i.e.: Banner)
4) Right click the banner and push publish to the remote server

The system will not push the content if you use a language different that English of Spanish

Tested on
Sender:
Ubuntu 14.04 // 3.1 Nightly build 2015-01-14 20:52 // Postgres // Chrome

Receiver:
MacOS 10.10.1 // 3.1 Nightly build 2015-01-14 20:52 // Postgres // Firefox

Log:
https://gist.github.com/shayngr/243e17fe3accec417d51

![bundle is empty](https://cloud.githubusercontent.com/assets/8741846/5763836/546f33f0-9cb3-11e4-8504-eea70d36a8da.png)

**Comment by jtesser** [comment]
closing as this should be fixed in https://github.com/dotCMS/core/issues/6906
