### ISSUE TITLE
Cluster: We are losing the server ID after you shut down one on the cluster servers

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6989]
If you have 3 or more servers on cluster, and then you try to shut down one of the servers, the system is losing the server ID of the server that you was shut down 

To reproduce 
 - Startup the node1
- Apply the license pack
- Shut down the node1 
- Create the symbolic link of the asset file to the nodes 2 and 3
- Startup the node1 again  
- Configure the node 2 and 3 to use the same data base 
- Start up the node 2 
- Startup the node 3 
- Check the network portlet and make sure all is on green (working fine)
- Shutdown the node 3
- Check again the network tab 

SC: http://screencast.com/t/QAxhCj4g4NOQ

Tested on master-3.1 // Postgres // FF

**Comment by jtesser** [comment]
i think this is right.  We recycle the license after some time and serverId on a disconnected server
