### ISSUE TITLE
Pages as Content Lock Contention UI issues

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6995]
When a page content is locked by one user, and another user tries to view or edit it, the UI either errors or gives no indication that the page cannot be unlocked by the user

From browser, double click to preview a page locked by another user:
![screen shot 2015-01-16 at 9 12 07 am](https://cloud.githubusercontent.com/assets/934364/5777345/c380a286-9d5f-11e4-884a-206a06d907c2.png)
 

From edit mode, viewing a page that is locked by another user:
![screen shot 2015-01-16 at 9 13 02 am](https://cloud.githubusercontent.com/assets/934364/5777359/e3dd5268-9d5f-11e4-8f0c-004780e39d2b.png)

**Comment by jtesser** [comment]
its a feature. True pessimistic locking. One user at a time please hehe.....

**Comment by bryanboza** [comment]
Fixed, now the system show a page locked message and you can't unlock, just view

**Comment by shayngr** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52927
