### ISSUE TITLE
Unexpected error when you try to see the page statics 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6998]
With the new html pages we are having an unexpected error when you try to see the page statics... 

To reproduce: 
- Create a new html structure 
- Create a new html page 
- Right click and go to the view statics in the sub-menu 

SC: http://screencast.com/t/DaES16vjJo

Tested on nightly build 2015-01-16 // H2 // FF

**Comment by jtesser** [comment]
duplicate
