### ISSUE TITLE
The create new page link in the html preview is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6999]
When you go to the html page preview and then click to the create a new page link, the system is redirecting to the site browser tab and you will have an error in the log: 

SC: http://screencast.com/t/wNOEFUlF
Log: https://gist.github.com/bryanboza/f055e50c0c12bf71d846

Tested on nightly build 2015-01-16 // H2 // FF

**Comment by jtesser** [comment]
this should create a new page at the same level

**Comment by shayngr** [comment]
It's not working well because the new page is not created at the same level, all new pages are located in the root (demo.dotcms.com) by default and you have to change the location manually.

**Comment by jtesser** [comment]
@shayngr can you create a new issue outlining and showing the one still broken case
