### ISSUE TITLE
We need improve the error message when you try to create two html pages with the same name 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7000]
When you try to create two html pages with the same name, when you click to save we have the follow error:  Unable to flush Hibernate Session 

SC: http://screencast.com/t/W14ddviqC3B

We need improve this message and show a more clear error 

Tested on nightly build 2015-01-16 // H2 // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7038

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-21 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52926
