### ISSUE TITLE
ContentMap for files is not respecting front end permissions

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7003]
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/viewtools/content/ContentMap.java#L192

**Comment by jtesser** [comment]
test way to test is to use velocity on the front end to get a content's file from a file field 

http://dotcms.com/docs/latest/DisplayingContentWithBinaryAndImageFields

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-23 // H2 // FF
