### ISSUE TITLE
Content Search Manager: Export contents (Forms) is not working if search criteria has a date range

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7004]
Reproduced originally in 2.5.4 and also in demo.dotcms.com (running 3.0.1). 

Steps to reproduce:

1. For "Contact Us" structure (Form-type structure), add a Date Field called "Birth Date" Label it as indexed, required and searchable.

2. Import this CSV file to structure https://gist.github.com/joseorsini/471832132174dd7d27a8

3. Go to Content Search and filter contents according to this search criteria:

First Name: Jose.
Last Name: Mou.
Birth Date: [1/1/1980 TO 1/1/1982]

This will return only one result. The idea is to use a date range field and other field types for filtering results. Then, click on "Export" button.

This will redirect the Content Search to /c and no CSV file is generated.

From the same test above, combination of each text field and date range as search criteria will make the Export to fail. However, having only two text fields as search criteria makes the Export to work properly.

**Comment by jtesser** [comment]
other like issues https://github.com/dotCMS/core/issues/955
https://github.com/dotCMS/core/issues/4969

**Comment by joseorsini** [comment]
Unable to reproduce in 3.6.0. If the Search Criteria is in place, as described on this ticket, while the search is made on Forms portlet (Content Search portlet does not list Forms-type content types), the CSV file is generated according to the selected Search Criteria.
