### ISSUE TITLE
There are a ton of db queries when a page is rendered

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7006]
Obviously turn off the pageCache.  Then hit:

```
ab  -c 25 -n 1000 http://localhost:8080/
```

Did all of the changes in issue #6288 did not make it into 3.1?

Here is my db log.
https://gist.github.com/wezell/39699ecf2ca92dd5268e

**Comment by jtesser** [comment]
yes all the changes from that issue are in but maybe some things got overwritten or something. or some things are not done yet

**Comment by jtesser** [comment]
this is working
