### ISSUE TITLE
MTM Child Ordering 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7013]
When updating one of multiple child contentlets in a many-to-many relationship the order was mixed up. The reason was that the treeOrder of the child was always set to "1". This seems to have broken as a result of the fix for #4370 (commit f83619b).

1. Create a parent Structure A and a child Structure B
2. Add a Many to Many Relationship between Structures
3. Add Relationship field on child Structure B
4. Create a content for parent Structure A and try to relate Structure B contents (4 contents).
5. Observe the order of the child contents
6. Modify the third child (Structure B) and Save&Publish

You will see that the child objects' order has been messed up

**Comment by jtesser** [comment]
fixed here https://github.com/dotCMS/core/pull/7012

**Comment by jtesser** [comment]
QA need to test teh above steps AND issue #4370

**Comment by jtesser** [comment]
committed to master-3.1 now https://github.com/dotCMS/core/commit/2c767d4eb689e9ed989f93f97d5abf328afef37f

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-20 // H2 // FF
