### ISSUE TITLE
Categories not returned from Content Rest API

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7014]
http://demo.dotcms.com/api/content/render/false/query/+structureName:News%20+(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797%20conhost:SYSTEM_HOST)%20+languageId:1%20+deleted:false%20+working:true/orderby/modDate%20desc

**Comment by wezell** [comment]
Are there other objects we are leaving out?  Might as well make sure we get'em everything we can (like we do from the contenttool).

**Comment by jtesser** [comment]
Yea it is the different APIs tags are already there I checked. The files/image links are built.  So I think mists there but yea need to kitchen sink it and see,

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // Postgres // FF

**Comment by wezell** [comment]
@bryanboza and no additional db hits?
