### ISSUE TITLE
LDAP in 3.0 and WebDav

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7015]
https://gist.github.com/jtesser/ab89d16c90442626a8bf

Maybe since the repackage something broke here?

**Comment by jtesser** [comment]
For testing this we can install http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=14683 in our window VMs

**Comment by maurizo** [comment]
Pull request dotcms/dotcms-libs#19
Pull request #19
Artifactory dot.bsh-2.0b4_2.jar

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-12 // H2 // FF
