### ISSUE TITLE
Backend logs viewer can no longer access all logs in 3.0

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7020]
In 3.0, the log4j logs were split off from ~tomcat/logs/ to ~dotsecure/logs, with the catalina.out and http access logs remaining in the tomcat/logs. The backend log viewer is built to only display the logs in the directory defined by TAIL_LOG_LOG_FOLDER which defaults to ./dotsecure/logs so the logs remaining in tomcat/logs are no longer viewable via the backend. This config method does not honor the DYNAMIC_CONTENT_PATH directive for locating dotsecure which adds some confusion also. All logs should probably be centralized into one directory, or the log viewer should provide access to both locations. The ability to zip and download full logs would be a nice enhancement here as well.

This is an issue biting us for our cloud-hosted clients, as they generally do not have shell-level server access and can only view logs through the backend log viewer.

**Comment by jtesser** [comment]
i could solve this with some config or a sym link as a work around. 

Maybe we can provide multiple directories but in general those logs are app server logs and not dotcms logs.

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/143
