### ISSUE TITLE
Server Error 500 when you download for publish or unpublish

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7021]
When you have an unpublished page and want to add it to a bundle in order to “download for publish” or “download for unpublish”, you will get a Server Error 500 message
If the page is already published, "download for publish” or “download for unpublish” does work well.

To reproduce:
1) Create 2 html pages: 1 page unpublished and 1 page published
2) Add each page to a different bundle
3) Go to Publishing Queue > Bundles
4) Select  "download for publish” or “download for unpublish” for the page which status is publish. You will see the file is downloaded fine
5) Now do the same with the page which status is unpublish. You will see a "Server Error 500" after you select "download for publish” or “download for unpublish”

Tested on dotCMS version: 3.1 nightly build (2015-01-16 22:54)
Linux // H2 // Chrome 

Video capture: http://screencast.com/t/IPltcXMtem0X

**Comment by maurizo** [comment]
Pull request: #7034

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-01-21 22:52 // Ubuntu 14.04 // Postgres // Firefox & Chrome

**Comment by shayngr** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52919
