### ISSUE TITLE
Alphabetization of fields in list

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7022]
When you add a field to a content type, the list of field types you can add is mostly alphabetical. The exception is "Site or Folder" which falls in the H's. It should be moved down.
![untitled](https://cloud.githubusercontent.com/assets/3178838/5823975/18b60c3a-a0af-11e4-8d70-7febd01eafa2.png)

**Comment by bryanboza** [comment]
Fixed, now we have the correct order... Tested on nightly build 2015-01-22 // H2 // FF
