### ISSUE TITLE
System is showing an error when clicking on Title column of html page

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7029]
To reproduce:
1) Create a new html page
2) Go to Site Browser> HTML Pages
3) Scroll down and click "Next" button
4) Locate the new page you created and click on its title (on the title column)
The system will throw an error:
******
An unexpected system error occurred.
Contentlets could have working versions for each language
******

![system error](https://cloud.githubusercontent.com/assets/8741846/5826864/d56e08d0-a0bb-11e4-8317-ab3009639442.png)

Test info:
dotCMS version: dotCMS version: 3.1 nightly build (2015-01-16 22:54):
Linux // H2 // Chrome

@jcastro-dotcms said he already has a fix for this issue and will work on it.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7032

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-20 // H2 // FF
