### ISSUE TITLE
Hibernate Session error when you save content in Spanish 

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7030]
Reproduced in 2015-01-16//Postgress//Linux

Steps:
1. Create a content in English and then Edit the content.
2. Try to Save content in Spanish version.
3. You will see Hibernate Session error in console.
Please see http://screencast.com/t/pddPQdZ9gDno
Error in console: https://gist.github.com/anonymous/357bebd1e1b7f89eea27

**Comment by jtesser** [comment]
This is a duplicate and should be fixed today @dsilvam this should be on the issue you are working on #6906
