### ISSUE TITLE
Importing categories from a bundle into remote server is not working

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7036]
Related to #6848

On the receiver server, when you try to import categories that were downloaded for publish on the sender, they are not getting imported.

To reproduce:
1) On the sender, navigate to Content Types> Categories. Add a few new categories
2) Click to select all categories and "Add to Bundle" (you could also skip selecting the categories, it won't change the final result)
3) Go to Site Browser> Publishing Queue> Bundles. "Download for Publish"

4) On the receiver, navigate to Content Types> Categories.
5) Select the option "Add/Edit" and click Import button. Import the bundle that was downloaded for publish.
6) You will see that on the receiver none of the categories were imported.

I compared the bundle file against the postgres db (category table) and it looks like the inode of each category was successfully included in the bundle but the receiver is not importing them.
Flushing all caches or refreshing the page does not work

Test info:
Sender: Linux // Postgres // Chrome
Receiver: MacOS // Postgres // FF
dotCMS version: 3.1 nightly build (2015-01-20 22:35)

Video capture: http://screencast.com/t/TXwwXa76LNQ

**Comment by jtesser** [comment]
@shayngr this isn't how you test bundles. Please get with @brentgriffin on this one. Bundles are uploaded from the Push Publishing Manager. The Import Cats is NOT for bundles but the CSV.  It is a totally separate piece of functionality.
