### ISSUE TITLE
#navigation

### ISSUE THREAD

**Issue by bradrice** [dotCMS/core#7037]
We just discovered if you use double quotes in a page title the #navigation macro will not work for a page or any folder with that page in it.

**Comment by jtesser** [comment]
this is velocity.  You need to escape it or use the $esc tool in the title which accepts velocity

**Comment by wezell** [comment]
also, we would suggest using the more modern $navtool to build your navigation. The #navigation and #crumbtail macros are deprecated

see: http://dotcms.com/docs/latest/NavigationCrumbsAndSitemap for more information.

**Comment by bradrice** [comment]
Thanks Will. I have tried unsuccessfully to get the navtool to work. I've
asked my collegue to help me figure it out. When I copy the code and drop
it on the page, I get nothing.

On Wed, Jan 21, 2015 at 4:35 PM, Will Ezell <notifications@github.com>
wrote:

> also, we would suggest using the more modern $navtool to build your
> navigation. The #navigation and #crumbtail macros are deprecated
>
> see: http://dotcms.com/docs/latest/NavigationCrumbsAndSitemap for more
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7037#issuecomment-70926484>.
>



-- 
Brad Rice
bradrice1@gmail.com
--
Don't wait for the Last Judgement. It takes place every day.
*    - Albert Camus <http://en.wikipedia.org/wiki/Albert_Camus>*
