### ISSUE TITLE
Reorder menu-items not working until you flush all cache

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7039]
Reproduced in 2015-01-16//Postgres//Linux

1.Create a new html page in About-Us.
2 Create a Menu link inside the About-Us.
3.Open preview the HTML page and click on Lock for Editing.
4.Now click on reorder button in the nav column. 
5.Try to reorder and click to save.
6.You will see the reorder not working until Flush all cache.
Please see http://screencast.com/t/LK7gaaDyh

**Comment by jtesser** [comment]
closing as a dup of https://github.com/dotCMS/core/issues/7023
