### ISSUE TITLE
We are duplicating pages after fix conflicts with the integrity checker, and then try to edit the page on receiver side 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7040]
Now the integrity checker is working for the new html pages, but when you make any fix, if you after that try to edit the fixed page, the system is making a duplication.... 

To recreate: 
- Configure your push environment 
- Create a html conflict manually (page with the same name on sender and receiver)
- Fix the conflicts on the sender side 
- On sender side try to edit anything in the page properties and save it 

The system is duplicating the page and save the changes in a new one... 

If you go to the SQL query tool and make the follow search you have two pages on results... 
Query: 
+working:true -deleted:true +conFolder:a1ea5a05-2460-4544-ae6a-f25f37a11db1 +structureType:5

Tested on nightly build 2015-01-21 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7087

**Comment by bryanboza** [comment]
New problem in the #7103
