### ISSUE TITLE
Unpublished HTML page is not showing in site browser

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7041]
When you create a new page in the root and just save without publishing, it does not show in the site browser until you publish it.

To reproduce:
1) In the root (without clicking on any folder) create a new html page and just save it, do not publish it.
You will see it's not showing in the site browser. Activating "Show on Menu" does not fix it.
2) On the other hand, if you create a page and publish, it does show right away

Tested on:  3.1 Nightly build 2015-01-21 22:52 // Ubuntu 14.04 // Postgres // Firefox & Chrome

Video capture: http://screencast.com/t/5PK3rZrE

**Comment by bryanboza** [comment]
fixed, Tested on nightly build 2015-01-27 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52820
