### ISSUE TITLE
We need show the more info when you upload some bundle with html pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7044]
Like in other cases like structures when you upload some bundle to the server, the system show the title, but if you try the same with the new html page the system is not showing nothing here....

SC: http://screencast.com/t/99g3n8plm

Tested on nightly build 2015-01-21 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-28 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52919
