### ISSUE TITLE
The migrate to content action touch ups

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7047]
When you have legacy pages, the system is showing a migrate to content option, we need assign some icon to this fiction

SC: http://screencast.com/t/CSBcY9iyJM

Tested on nightly build 2015-01-21 // H2 // FF

**Comment by jtesser** [comment]
this button actually just needs to go away

**Comment by jtesser** [comment]
Actually we have decided to keep the button. Ensure it is working. 

BUT it should ONLY be available to CMS Admins

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-02 // H2 // FF
