### ISSUE TITLE
The migrate to content function is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7048]
When you have legacy pages, the system shows the option to migrate this to content, if you click to this function the system is showing an error in the log, and this is not working 

Log: https://gist.github.com/bryanboza/710797ac56743557ca67

Tested on nightly build 2015-01-21 // H2 // FF

**Comment by jtesser** [comment]
closing as this button will be going away https://github.com/dotCMS/core/issues/7047
