### ISSUE TITLE
System does not handle messages correctly when you create an account in the Intranet

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7049]
When you try to create and account in the Intranet and the email format is wrong, the system is not giving the right message to the user in order to correct the mistake.

To reproduce:
1) In the frontend click on Login to access the Intranet
2) Click "Create Account" button
3) Fill out the required fields (input the email address using wrong format, for instance type "test1" instead of "test1@dotcms.com"). Hit Next Step
The system is not telling the user what need to be corrected.

In addition, when you successfully create the account, the system does not let the user know about it.

Tested on:  3.1 Nightly build 2015-01-21 22:52 // Ubuntu 14.04 // Postgres // Chrome

Video capture: http://screencast.com/t/2YQrERoq

**Comment by jtesser** [comment]
this is just front end content on starter and is just an example.
