### ISSUE TITLE
Can't make actions selecting multiple html pages in the content tab

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7051]
If you go to the content tab and here try to un-publish multiple html pages at the same time we can have an error here....

Case 1
- Create 5 pages, leave just one unpublished and all the others published... Now select all and try to un-publish... The system show an error and the pages are not changing the status 

SC: http://screencast.com/t/G9MhPu2eLZJ

- Case 2
On the other hand.... Now leave all unpublished and just one published , and make the same step... Select all and click to the un-publish button... The system is showing the same error but is un-publishing the published page 

SC: http://screencast.com/t/DksGzCKUPGra

Tested on nightly build 2015-01-21 // H2 // FF

**Comment by bryanboza** [comment]
fixed, Tested on nightly build 2015-01-27 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52922
