### ISSUE TITLE
Unable to reorder html pages by friendly name 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7052]
If you go to the content tab, if here you click the "Friendly name" column title to reorder by this column, the system is hiding all the contents 

SC: http://screencast.com/t/I0xQng1Hd

Tested on nightly build 2015-01-21 // H2 // FF

**Comment by wezell** [comment]
Actually, that is TMI.  We need "show on listing" only for Title and URL by
default for all HTMLpage content structures.  We should fix in starter and
in the create new HTMLPage code.

**Comment by jtesser** [comment]
@wezell i was wondering about some of that also. BUT still the sort should not behave this way.

**Comment by dsilvam** [comment]
The reason why the order by field friendlyname does not work is because this field is not indexed:
http://screencast.com/t/w9pHBj2h

**Comment by jtesser** [comment]
Need to wait for a new starter to test out of box.  You can upgrade from 3.0 to test now

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-21 // Postgres // FF
