### ISSUE TITLE
dotCMS version 3.1. Content of HTML page is wiped out after fixing conflicts

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7057]
Related to https://github.com/dotCMS/core-2.x/issues/103

Using dotCMS version: 3.1, after fixing conflicts with integrity checker the content of the html is wiped out.

Steps to reproduce:
1) Create a push publish configuration (sender and receiver)
2) On the sender and the receiver, create a folder and html page inside that folder with same name  in order to find conflicts with Integrity Checker
3) Add some Content to it
4) Then go to System > Configuration > Publishing Environments > Check Integrity. Fix the conflicts you will get with the folders and the HTML pages. 
5) If you fixed the conflicts at the local node, open the local page in Preview and will see the content is wiped out, if you fix the conflicts at the remote node, open the remote page in Preview and will see the content is wiped out.

The system should not delete the content of on any of the pages after fixing conflicts

Testing Info:
-Sender: Linux // Postgres // Chrome
-Receiver: MacOSX // Postgres // FF
-dotCMS version: 3.1 Nightly build 2015-01-22 23:09

Video capture: http://screencast.com/t/KKScvTPz

**Comment by jtesser** [comment]
we're not updating the multitree. need to fix.  I think we did this in core-2.x

**Comment by jcastro-dotcms** [comment]
This issue was fixed with this PR: https://github.com/dotCMS/core/pull/7087

As @jtesser mentioned, correctly updating the Multi_Tree table fixed this problem.

**Comment by bryanboza** [comment]
Should be tested with the fix #7103
