### ISSUE TITLE
Edit Mode control on HTML Page as Content doesn't make sense

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7061]
If you have only an english page the spanish is clickable but takes you to edit mode in the old edit mode. 

We need to disable the languages that do not exist meaning you cannot click on it but if it does exist click it and switch the page to the right version meaning the right language of that page

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7120

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-28 // Postgres // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52897
