### ISSUE TITLE
TAIL_LOG_LOG_FOLDER config var should not need a trailing slash

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7062]
TAIL_LOG_LOG_FOLDER=./dotsecure/logs/ conflicts with all other filesystem directory config vars in dotmarketing-config.props that do not expect a trailing slash, which creates an inconsistent experience configuring Dotcms. Code should check the slash situation and not just fail to open files if it is missing.

Code for handling this var and path is here:
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/servlets/taillog/TailLogServlet.java#L76

Line 79 also has the wrong config var name in the error msg:
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/servlets/taillog/TailLogServlet.java#L79

**Comment by joseorsini** [comment]
+1. We would need to implement a similar validation we have for DYNAMIC_CONTENT_PATH property in the ConfigUtils.java https://github.com/dotCMS/core/blob/8bac09f6bd04d7324f39a37b5ce66085331a32d4/src/com/dotmarketing/util/ConfigUtils.java#L27

**Comment by jtesser** [comment]
should work with or without it but yes

**Comment by chrismccracken** [comment]
I actually don't think TAIL_LOG_LOG_FOLDER is working consistently at all. When it is set to a value such as "/opt/dotcms/data/dotsecure/logs/", the tail_log.jsp is generating the fileName param for  TailLogServlet with the full filesystem path (not a path relative to TAIL_LOG_LOG_FOLDER) like this (https://gist.github.com/chrismccracken/49a397de121be25e5d9b). Because https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/servlets/taillog/TailLogServlet.java#L76 is simply appending that param to TAIL_LOG_LOG_FOLDER, the path is invalid and the file can't be found.

I looked at where the jsp is getting the filename array (https://github.com/dotCMS/core/blob/master-3.1/src/com/liferay/util/FileUtil.java#L379), but I'm not sure why its returning the full path when I have TAIL_LOG_LOG_FOLDER defined and why its only returning a relative path when TAIL_LOG_LOG_FOLDER is set to the default "./dotsecure/logs/". 

I'm going to work-around the whole issue now by altering the distro file structure with symlinks (plugin config would be preferred), but something's broken here.

**Comment by jtesser** [comment]
basically 2 issues here

1. The trailing slash as originally slated 
2. The path forces relative and should work absolute bathing

**Comment by oarrietadotcms** [comment]
Pull request: https://github.com/dotCMS/core/pull/7389

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-12 // Postgres // FF
