### ISSUE TITLE
The reorder does not working in the side nav/ menu bar 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7064]
Related to #7023 

After this fix now the top menu bar, works fine when you try to reorder the menu, but if you try to reorder the menu of the side nav, using the theme with side nav, this does not working...

Also if you create some page using the side nav theme, and here you select some special side nav order and save the changes, the reorder is not working, and if you go to the page properties and enable the show on menu option to the html page, and go back to try to reorder again, you will have a "Opsss error message"....

You can see here: http://screencast.com/t/ckehzyTCpr

Tested on nightly build 2015-01-22 // H2 // FF

**Comment by maurizo** [comment]
Pull request #7124

**Comment by jtesser** [comment]
fix as we discussed @maurizo

**Comment by maurizo** [comment]
Pull request #7127

**Comment by bryanboza** [comment]
fixed, Tested on nightly build 2015-01-28 // H2 // FF
