### ISSUE TITLE
Cannot push HTML page inside a bundle

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7065]
When you add a html page to a bundle and push it, it fails

To reproduce:
1) Create a push environment
2) On the sender, create a new html page inside a folder (html structure and folder don't have to be new)
3) Add some content and put the page inside a bundle
4) Push the bundle. You will see it fails

Test info:
Sender: Linux // Postgres // Chrome
Receiver: MacOS // Postgres // FF
dotCMS version: 3.1 nightly build (2015-01-22 23:09)

Log on receiver node: https://gist.github.com/shayngr/ca272bc09c33ca3260d8

**Comment by bryanboza** [comment]
@shayngr, please retest.... Tested on my local with the last nightly build // Postgres  and is working fine....
