### ISSUE TITLE
Problems resizing the nav tool  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7066]
When you enable the show on menu in multiple folders, the system is expanding the nav tool and this is overriding the add content menu bar, and if you have any content too....

Video Capture: http://screencast.com/t/IVEryIDNXxa5

Tested on nightly build 2015-01-22 // H2 // FF

**Comment by jtesser** [comment]
This isn't really an issue as it is the just the starter site CSS.  Should be ok as our example which is all it is
