### ISSUE TITLE
Too many Strings created - merging velocity templates should use streams and not strings

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7069]
We do this all over - in marcos, in #dotParse, in our  *Service classes.  We call `$velutil.mergeTemplate($templatePath)` which builds a large String (whole templates) and returns  to the calling template.

What I think we should be calling (9 times out of ten) is `$velutil.mergeTemplate($templatePath, $response)` which incorporates the current templates' output into the response.getWriter() stream, and avoids building all the intermediary Strings.

Now, I have 0 proof but I think but all this large String generation can't help but cause the heap to grow and potentially the GC to slow down.  

We need to replace our calls to `$velutil.mergeTemplate($templatePath)` to `$velutil.mergeTemplate($templatePath, $response)` for performance, wherever possible.

**Comment by jtesser** [comment]
Makes sense to me
