### ISSUE TITLE
Push publish is not pushing a single HTML page

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7070]
If you have 2 or more HTML pages inside a folder and push only one of those pages, the system is pushing all the pages inside the folder, not only the page you asked to be pushed. 

To reproduce
1) Set up a push environment
2) On the sender, create a new folder and 2 or 3 more new HTML pages inside that folder.
3) Pick only 1 page in that folder and push it
4) On the receiver, you will see the system pushed all the pages inside the folder, not only the page you asked to be pushed.
This happens also if you add 1 single page to a bundle: the system pushes all the pages inside the folder.

Tested on:  3.1 Nightly build 2015-01-22 23:09 // Ubuntu 14.04 // Postgres // Firefox & Chrome

Log on receiver node: 
https://gist.github.com/shayngr/6668901d0e0873dc6129

**Comment by jtesser** [comment]
this is on purpose cause of the dependency manager

**Comment by brentgriffin** [comment]
Please explain the reason for this change.  It does not behave this way in 2.x and 3.0.

**Comment by wezell** [comment]
There is this config property:

#Allow publish tool to export/import all pages in an exported folder
#not only pages linked in the multitree table
PUSH_PUBLISHING_PUSH_ALL_FOLDER_PAGES=true


I don't know if that changes the behavior, but from the default value, it seems like this is expected
