### ISSUE TITLE
Improvement to Forgot Password functionality

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#7074]
Seems like forgot password functionality doesn't check the port or http/https in the URL that sends in recover email. Always send https and no port (80 by default).

https://github.com/dotCMS/core/blob/master-3.1/src/com/liferay/portal/ejb/UserManagerImpl.java#L410

**Comment by jtesser** [comment]
yea not sure what we want to do here. At minimum config but it is a security concern to allow this over http
