### ISSUE TITLE
Server error 500 on new HTML pages

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7076]
After fix on #6906, looks like there's still some functionality missing:

1) In the page, advanced properties tab still shows the value "friendly name" instead of "title"

2) When you create new pages which language **is not** English, in the site browser when you double click on the short language name (or open in Preview), they generate a Server Error 500

![language error 500](https://cloud.githubusercontent.com/assets/8741846/5902876/d796464a-a543-11e4-8ac8-db0d3b62d584.png)

3)  Language drop down control is not appearing above the "Name" column, on the other side of Add New combo box

Tested on:  3.1 Nightly build 2015-01-23 21:52 // Ubuntu 14.04 // Postgres // Firefox & Chrome

**Comment by jtesser** [comment]
@shayngr Your number is correct behavior. That was not what the issue was doing.

**Comment by wezell** [comment]
I am on this right now.

**Comment by bryanboza** [comment]
FYI: when you try to open a page in a different language we have this error in the log: https://gist.github.com/bryanboza/eb064a88db247c07163d
