### ISSUE TITLE
The system is not finding the page after change the language

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7079]
If you have any html page, add some contents in english, and the try to add some contents in spanish, when you come back to english the system is showing an error... 

- Create a new page
- Add some contents in english
- Change the language drop-down to spanish 
- Change again to english

![bug](https://cloud.githubusercontent.com/assets/2641437/5904429/e5eb3ade-a54d-11e4-912a-2d5f2bef5073.png)

Tested on nightly build 2015-01-23 // H2 // FF

**Comment by jtesser** [comment]
this issue is a duplicate https://github.com/dotCMS/core/issues/7061
