### ISSUE TITLE
navtool does not respect language

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7080]
When you change languages and create a page in a default language, the navtool.getChildren  call fails because it just uses the default language

Basically, the drop down menu goes away.

![screen shot 2015-01-26 at 1 00 36 pm](https://cloud.githubusercontent.com/assets/934364/5905096/851c91ae-a55b-11e4-8ccf-884c0063f190.png)

**Comment by jtesser** [comment]
fixed #7128

**Comment by bryanboza** [comment]
Fixed, now this is working as expected.... Tested on nightly build 2015-02-04 // H2 // FF
