### ISSUE TITLE
Unable to bundle html pages in different languages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7082]
The system is only adding the english html pages to the bundles, if you try with a page in any other language the system is not adding it...

Here the video: http://screencast.com/t/ylxqXVW9NNNt

Tested on nightly build 2015-01-23 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-27 // H2 // FF

**Comment by shayngr** [comment]
Added to test rail http://qa.dotcms.com/index.php?/cases/view/52877
