### ISSUE TITLE
 "An unexpected system error occurred" when you see Page Properties

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7083]
To reproduce:

1) Create a new html page (in any language including English) inside a new folder or already existing folder
2) Publish the new page
3) Navigate to Site Browser tab > HTML pages
4) Find the new page you created, do right click > Page Properties
You will see the error:

![page properties](https://cloud.githubusercontent.com/assets/8741846/5904909/c40c0282-a551-11e4-82e6-55c04bfa9f48.png)

Tested on:  3.1 Nightly build 2015-01-23 21:52 // Ubuntu 14.04 // Postgres // Firefox & Chrome

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-04 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55724
