### ISSUE TITLE
Error showing when you filter by template a new page

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7086]
To reproduce:
1) Create a new html page on the root (without clicking on any folder) in a language different than English. Keep in mind what template you chose, this is for future reference
2) Publish the page
3) Navigate to Site Browser tab> HTML pages. Filter the pages by template and choose the template you used when you created the new page 
You will get an error:

![versionable is null](https://cloud.githubusercontent.com/assets/8741846/5908371/708adbf4-a56c-11e4-958f-801a188b3eba.png)

This error will not disappear unless you unpublish the page or archive it

video capture: http://screencast.com/t/d76FmHM4F

Tested on:  3.1 Nightly build 2015-01-23 21:52 // Ubuntu 14.04 // Postgres // Chrome

**Comment by maurizo** [comment]
Pull request: #7168

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-02-03 23:54 // Ubuntu 14.04 // Postgres // Chrome

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55733
