### ISSUE TITLE
Can archieve used containers

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7090]
We can put to archieve container which is used in some templates and don't receive any warning about that. Pages which use these templates become unavailable. We see blank page in browser and uninformative message in log:

```
  ERROR services.PageServices:
  java.lang.NullPointerException at com.dotmarketing.services.PageServices.buildStream(PageServices.java:170)
```

It would be good to disallow deleting container if it is used in some active templates and show list of these templates. It can be very difficult to find reason why some pages are shown empty without any useful information in log.

Can be reproduced on 2.x and 3.x versions.

**Comment by jtesser** [comment]
Right. For now do not archive containers you are using obviously :-p

**Comment by grinev** [comment]
Yes, but if however it happened you wouldn't see any information what causes the error. At least add some information about type of object  and identifier in error message if you won't fix that.

**Comment by jtesser** [comment]
right we don't have that report. We will fix at some point in the future. We didn't close the issue just saying for now you shouldn't archive them
