### ISSUE TITLE
Unable to login on IE11

### ISSUE THREAD

**Issue by PieterHeijman** [dotCMS/core#7091]
I'm having trouble logging in to Dotcms 2.5.2 in IE11 (version 11.0.9600.17501 update version 11.0.15). Logging in using different browsers work, but IE11 doesn't. 

It shows the following behavior : 
- I open Dotcms (http://[sitename]/c)
- Enter my emailadress and password
- Press enter or click login (either one gives the problem)
- The login page reloads with no messages, leaving all fields in login form blank

If at that point I browse to the site itself it opens the page in "edit-mode" but with all the buttons disabled. Pressing "Return to admin" returns you to the loginpage.

**Comment by jtesser** [comment]
You would need to upgrade to a later dotCMS for IE11.  You need google frame in 2.5.2
