### ISSUE TITLE
Friendly name and language drop down functionality 

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7092]
Based on comments in #6906, looks like there's still some functionality missing:

1) In the page, advanced properties tab still shows the value "friendly name" instead of **"title"**

![friendly name](https://cloud.githubusercontent.com/assets/8741846/5919987/7bd7827c-a5fe-11e4-9215-5e74b0dac7d1.png)

2) Language drop down control is not appearing above the "Name" column, on the other side of Add New combo box

![language drop down](https://cloud.githubusercontent.com/assets/8741846/5919998/a0736786-a5fe-11e4-919c-260d3f5ce428.png)

Tested on: 3.1 Nightly build 2015-01-27 04:39 // Ubuntu 14.04 // Postgres // Firefox & Chrome

**Comment by jtesser** [comment]
point 1 is right as I commented yesterday @shayngr 

and yes @fishsmith is going to take a look at point 2.  We need to adjust the css there.  It is problematic
