### ISSUE TITLE
Server error 500 editing HTML pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7093]
After fix #7076 now we don't have the error 500 when you open the page, but if you try to edit have the problem again 
![2015-01-27_0840](https://cloud.githubusercontent.com/assets/2641437/5920194/40f2db6e-a600-11e4-9135-3417c17bca56.png)

Tested on nightly build 2015-01-27 // H2 // FF

**Comment by bryanboza** [comment]
FYI: Here the log: https://gist.github.com/bryanboza/d2b28a57d450a70e69a1

**Comment by jtesser** [comment]
I believe this is now working. One of our other commits fixed it

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-03 // H2 // FF
