### ISSUE TITLE
Bug: XSS filter should not be invoked on form submit

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7094]
We have an HTML form (hand-coded) that POSTs data to a dotCMS page for processing. This seems to invoke an XSS filter, which prevents us from entering many different kinds of legitimate data, e.g. 

- Names with accents, e.g. René Lévesque
- Telephone numbers with area codes, e.g. (416) 492-3833
- Text in other languages, e.g. Chinese

This filter should not be invoked for normal form submissions.

Error message is as follows:

>[27/01/15 14:36:27:671 UTC] WARN IntrusionDetector: [SECURITY FAILURE Anonymous:null@unknown -> /dotcms/IntrusionDetector] Invalid input: context=URLContext, type(HTTPQueryString)=^[a-zA-Z0-9_\-,&. ]{1,45}=[\p{L}\p{N}.\-/+=_ !$*?@\#,&:%âŒ©'"â€™;Ã¯Â¿Â½	d]*$, input=givenName=René&familyName=Lévesque&phoneNumber=(416)+492-3833
>com.dotcms.repackage.org.owasp.esapi.errors.ValidationException: URLContext: Invalid input. Please conform to regex ^[a-zA-Z0-9_\-,&. ]{1,45}=[\p{L}\p{N}.\-/+=_ !$*?@\#,&:%âŒ©'"â€™;Ã¯Â¿Â½	d]*$ with a maximum length of 228
>at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:144)
>at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:160)
>at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.getValid(StringValidationRule.java:284)
>at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:214)
>at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:152)
>at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:143)
>at com.liferay.util.Xss.ParamsHaveXSS(Xss.java:111)
>at com.liferay.util.Xss.ParamsHaveXSS(Xss.java:70)
>at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:106)
>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:331)
>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:162)
>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
>at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
>at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
>at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
>at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
>at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
>at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
>at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
>at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
>at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
>at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
>at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>at java.lang.Thread.run(Thread.java:745)

**Comment by jtesser** [comment]
for sure the XSS filter should fire in this case.  You need to escape your data on post and/or validate it

**Comment by jkshapiro** [comment]
Disagree vehemently. Authors should not have to take any extra steps to submit valid data to the server. And there's nothing invalid about the examples cited.
