### ISSUE TITLE
Prevent edit mode from loading all frames twice

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7096]
When you are browsing a site in edit mode, dotCMS is generally forced to render each frame twice.  This is due to the fact that when you click a link on a edit mode page, it loads the page in the "mainFrame" iframe.  The browser then generally renders the same iframes nested in the "mainFrame" iframe before the frame-busting javascript forces a full page refresh properly reloads the top frame.  This leads to a brief moment (just a flash) where edit mode looks like this before it it is properly rendered and doubles the dotCMS rendering load when working in edit mode.

![screen shot 2015-01-27 at 10 00 21 am](https://cloud.githubusercontent.com/assets/934364/5920547/5e10048c-a60b-11e4-90d3-16f81aa7b0b5.png)

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-27 // H2 // FF
