### ISSUE TITLE
Unable to fix html conflicts in MySQL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7103]
We are having an error when you try to fix conflicts with the integrity checker using MySQL in the receiver side... 

Here the log error: https://gist.github.com/bryanboza/99db804c912d2767ba39

Tested on nightly build 2015-01-27 // MySQL // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7126

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-30 // H2 // FF
