### ISSUE TITLE
We are losing the Host or Folder value when you change the page language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7105]
When you are creating a new page, when you change the language of the page, the system reload the form and lose this value... 

To recreate: 
- Add a new folder 
- Go to this folder, and here try to add a new html page
- The Host or Folder is in the created folder 
- Now change the language 

We lost the value here....

Here the video: http://screencast.com/t/i0nnfElUhoh

Tested on nightly build 2015-01-27 // H2 // FF

**Comment by jtesser** [comment]
good catch @bryanboza 

dev notice this is before saving at all

**Comment by bryanboza** [comment]
FYI: We are having an error in console every time you click or tab to move to this field, it is losing the value too, then if you don't select again any path when you move to another field have this error in console: 
![2015-01-29_1109](https://cloud.githubusercontent.com/assets/2641437/5962162/5a03f43c-a7a7-11e4-9637-4f9095252fad.png)

**Comment by bryanboza** [comment]
Tested on nightly build 2015-02-02 // H2 // FF
