### ISSUE TITLE
Need more specific messages adding new html pages with the same name 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7106]
Related to #6914 

Wen you try to create a new page with the same name that one existing page the system is showing "Unable to flush Hibernate Session".... We need a more clear message here 

![2015-01-27_1102](https://cloud.githubusercontent.com/assets/2641437/5922785/f906ccb6-a613-11e4-88e0-1b07dacea70a.png)

Tested on nightly build 2015-01-27 // H2 // FF

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7134

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-28 // H2 // FF

**Comment by bryanboza** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52891
