### ISSUE TITLE
Can't see the html page preview in oracle

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7110]
When you are using oracle as data base, if you try to create a new html page, the system is creating the page, but you can't see the preview, neither edit....

The license trial was applied, and have this problem...

![2015-01-27_1349](https://cloud.githubusercontent.com/assets/2641437/5925729/4a432446-a62b-11e4-8941-d4fb3f5a8a9a.png)

Tested on nightly build 2015-01-27 // Oracle // FF

**Comment by maurizo** [comment]
Couldn't reproduce it.

**Comment by jtesser** [comment]
@bryanboza 
I wonder if you have page cache on or something.

**Comment by bryanboza** [comment]
Working as expected, the problem here was my license level in the trial.jsp
