### ISSUE TITLE
Retry bundle fails after modify folder properties

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7115]
Reproduced in 2015-01-27//Win7//SQL Server on both sides

Steps:
 1.Upload an image into a folder and then add folder to a bundle.
  2.Push the bundle to remote server. This is fine.
  3.Modify the folder properties in local server and try to Retry the bundle option.
  4.You will see error message and push fails.
Please see http://screencast.com/t/4zpzN2hSVG
Error in console: https://gist.github.com/anonymous/087bda38035249d32989

**Comment by dsilvam** [comment]
This is working on latest master 3.1. Followed exact same steps and bundle gets sent when retrying and modified folder gets pushed successfully.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-04 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55738
