### ISSUE TITLE
Push fails when you Pushing a modified container

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7116]
Reproduced in 2015-01-27//Win7//SQL Server

Steps:
  1. Create a container then Push to remote server.
  2. Modify the Container locally then again push.
  3. You will see that push was failed on remote and getting errors in remote console.      
Please see http://screencast.com/t/1uMsdJBGxuBI     
Errors in console: https://gist.github.com/anonymous/830ad3675c4ed27dada1

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-04 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/560
