### ISSUE TITLE
CategoryComparator is not always transitive

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#7119]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!

I ran into an interesting issue that presented itself because we had a category where the categoryName had some "weird" characters.  it was actually "r�sum�" and the "é"'s were not encoded properly.  

When trying to save any content that used that used that group of categories we were getting the following error:
https://gist.github.com/cfalzone/86914f3cfbf581b1231e#file-gistfile1-txt-L42
(That is from 2.5.6, but the problem is the same in core's master)

The reason for this is the way the CategoryComparator is coded:
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/portlets/categories/business/CategoryFactoryImpl.java#L716-L741

For instance take this case:
CategoryA:  sortOrder=0, name="Something Peachy"
CategoryB:  sortOrder=0, name="Something with weird characters"
CategoryC:  sortOrder=0, name="Something Else"

In this case:
1.  A compared to B would return 0 Because compareTo throws an exception and returnValue is 0.
2.  C compared to B would return 0 Because same reason 
3.  A compared to C would NOT return 0.  Because compareTo works properly 

Which violates the general contract of transitivity that says if A==B and B==C then A must == C

I think the issue is that bad data can be saved, thus presenting this issue.

The can be replicated:
1.  Create a top level category, call it Test Category with children:
  - Test1, Tes2, r�sum�  
2.  Create a structure with a category field referencing the Test Category
3.  Create Contentlet and try to save it, you will see the error.

**Comment by jgambarios** [comment]
On latest master I’m not able to reproduce the issue, I even tried to force an exception:

https://gist.github.com/jgambarios/0c6a6051fd80602370ab
http://screencast.com/t/EqphhnP7q7

In 3.x we addressed some issue related to bad data but what is weird to me is that even forcing the exception I can not reproduce, maybe because 3.x uses java 7 and not java 6 like in the 2.5.x series?.

**Comment by jtesser** [comment]
Agreed i think the latest 3.x will function much better here

**Comment by joseorsini** [comment]
Guys, thank you for the efforts on this ticket. We appreciate it.

Reference to Support tickets: https://my.dotcms.com/ticket/dotcms-10
