### ISSUE TITLE
We need handle languages in the push publish

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7123]
Right now when you are pushing html pages we are pushing complete page with all the language, this on the push is not too bad, but when you try the remove function and you need delete just one language version, the system is deleting all the page in all the languages.... maybe we need handle this different on future....

To recreate: 
- Create a new multi-language page (3 or 4 languages)
- Push it
- Now if you need delete just one language version in the receiver side, and you try with the remove via push publish.  The system delete all the page and all the languages 

Tested on nightly build 2015-01-27 // H2 // FF

**Comment by jtesser** [comment]
yea this is by design. If you remove versions you need to alter the sender so that the version no longer exists.  Then Push it not a Push Delete.  The Delete is a destroy of the identifier

**Comment by bryanboza** [comment]
Yes, i know that is on purpose, but maybe we need keep in opened for future enhancements

**Comment by jtesser** [comment]
For now no.  I don't think we will handle differently
