### ISSUE TITLE
Unable to edit html pages in different languages if you archive the default language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7125]
Right now we can add html page version, but just after create the principal (default language).... After this you can add content, edit, and make anything normally... The problem is if you archive the default language page, and then you try to edit any of the other pages, we have errors in the log and you can't modify the existing contents, neither add nothing.... 

I think we always are working we the default language, then if this does not exist, the system breaks down

Here the log: https://gist.github.com/bryanboza/77c5767161c589c71bde

Video: http://screencast.com/t/9VDyNm263

Tested on nightly build 2015-01-27 // Postgres // FF

**Comment by jtesser** [comment]
we think this was already fixed

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-03 // H2 // FF
