### ISSUE TITLE
The multi-language pages are broken the integrity checker 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7130]
When you create a multi-language page, the system take the language version like a different pages, this because have different inodes... The problem is when you run the integrity checker, the system find a conflicts by every language version... Then when you try to fix conflicts, the system fix the first conflict, but when try to fix the second one, the inode of the page was changes, and this is broken the integrity checker... 

Steps to reproduce: 
- Create manually a integrity conflict 
- On sender: 
                 - Create a new page with multi-language versions (almost two)
![2015-01-28_1511](https://cloud.githubusercontent.com/assets/2641437/5947082/47df254e-a700-11e4-9ab3-cee41cecc083.png)

- On receiver 
                - Create a new page just in the default language 
![2015-01-28_1514](https://cloud.githubusercontent.com/assets/2641437/5947109/714d79e4-a700-11e4-9094-32b0304f36fb.png)

- Now run the integrity checker, look you have two conflicts... One by every language version on sender with the same page on receiver 
![2015-01-28_1517](https://cloud.githubusercontent.com/assets/2641437/5947180/daab75c6-a700-11e4-9818-25d8232753eb.png)
- Now try to fix the conflicts on remote node 

Here the log: https://gist.github.com/bryanboza/c7759f1f411f278057b7

Tested on nightly build 2015-01-27 // H2 // FF

**Comment by jtesser** [comment]
Yea getting close on these but still some issues here

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7169

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-03 // H2 // FF.... nice fix

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55730
