### ISSUE TITLE
Error when you try to reorder in the side nav/ menu bar and no have folders to show in the list

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7138]
Related to #7064 

We are having an error when you add a new page with side nav theme in any path that no have more folders to show in the list... The problem is when you try to reorder the system receive a null values and then the system is showing the follow error... 

![2015-01-29_1017](https://cloud.githubusercontent.com/assets/2641437/5961144/174adaae-a7a0-11e4-974b-819849c570bf.png)

Log error: ERROR portlet.StrutsPortlet: com.dotmarketing.business.DotStateException: identifier is null

Tested on nightly build 2015-01-28 // H2 // FF

**Comment by samuelmortha** [comment]
Tried the below way to reproduce on latest master-3.1 with clean starter : 

http://screencast.com/t/4cYsCmweIU

Can you please help me to reproduce, if i am missing somewhere ?

**Comment by jtesser** [comment]
I guess we fixed this

**Comment by jtesser** [comment]
@bryanboza let us know if we missed something

**Comment by bryanboza** [comment]
I am able to reproduce in the latest nightly build, more easy to recreate, 
- Add a new html page in the root of the site
- Select the template with side nav 
- Try to edit the page and click to reorder the side/ nav

SC: http://screencast.com/t/4YAfdiUgdVI

**Comment by maurizo** [comment]
Fixed. A new starter is need.  The change was on the subnav menu container.

**Comment by jtesser** [comment]
I will take a new starter next week

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-21 // Postgres // FF
