### ISSUE TITLE
Language Control XP issues

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7139]
Related to #7059 

Now we are showing the (en_US)... that's fine, but in the second point we continue showing the language control when you only have one language... 

- When you have only one language we should not show the language control in the Site Browser AND we should not show the language in the column of teh Site Browser or Content Manager

SC: http://screencast.com/t/jte0tWti6A77

Tested on nightly build 2015-01-28 // H2 // FF

**Comment by dsilvam** [comment]
@bryanboza , for second point you need to have only one language in the system, go to languages in the system tab, and erase spanish

**Comment by jtesser** [comment]
i got with @bryanboza this is working as expected
