### ISSUE TITLE
 Push success but page properties can not be updated after fixed conflicts

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7146]
Reproduced in 2015-01-27//Win7//SQL Server

Steps:
1.Create an HTML page on the sender and receiver with the same name and in the same folder location
2. Go to System tab > Configuration > Push publishing tab > Click on "Check Integrity" button
3. Fix the conflicts at the local server
4. Modify HTML page properties in local server.
5. Again push the html page, Now you will see the success message status at both servers but the HTML page properties can not be updated. 
Please see http://screencast.com/t/Ft48LqBLS

**Comment by bryanboza** [comment]
Tested on nightly build 2015-02-02 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-03 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55723
