### ISSUE TITLE
Error when you try to find html conflicts after fix the folder conflicts

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7147]
Reproduced in 2015-01-27//Win7//SQL Server

Steps:
1) Create a folder with the same name and location in the receiver and server side
2) Create an html page inside the folder
3) Go to System tab > Configuration > Push publishing tab
4) Click on "Check Integrity" button and then "View Conflicts". You should see conflicts with both the folder and html page
5) Fix ONLY the conflicts with the folder and check integrity again

Please see http://screencast.com/t/HmlWLbU7HW
Error in console: https://gist.github.com/anonymous/257638ae3ec8bede2849

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7169

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-03 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55720
