### ISSUE TITLE
Migrate from log4j 1.2 to 2.0

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7149]
Log4j 1.2 has not seen any updates in 2 years, and has numerous bugs that are not being patched. We should move to 2.0 which is under active development.

https://logging.apache.org/log4j/2.0/index.html

**Comment by rogelio-blanco** [comment]
Or we can give a try to logback = http://logback.qos.ch

**Comment by ggranum** [comment]
I've done a fair amount with Log4J 2, going as far as to implement (necessarily custom) audit logging of modifications to JPA entities. Far and away better than version 1.2. I can't speak to logback as I barely remember using it :~)

The variety of appenders in Log4J 2 is very nice, as well as the relative ease of configuration thereof. I'd call it the most comparison point - after speed and stability, obviously.

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/60
