### ISSUE TITLE
GetSQL Macro does not work after setting config params

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7151]
I found this on the 3.0.1 version running on Postgres with MacOSX

1) Started up new 3.0.1 instance
2) stopped the instance and put these two properties on the dotmarketing-config-ext.properties

ALLOW_VELOCITY_SQL_ACCESS_TO_DOTCMS_DB=true
ENABLE_SCRIPTING=true

3) Ran this code inside a widget: 
https://gist.github.com/DeanGonzalez/ebdc2cde919d8307b821

*I checked the select statement against my postgres database... returns results, however, my widget on my page simply states: "External scripting is disabled in your dotcms instance."

**Comment by wezell** [comment]
I think you need the role CMS_SCRIPTING or whatever it is called as well.

**Comment by jtesser** [comment]
Yes cause I think this is working. I am sure you are missing the role

**Comment by brentgriffin** [comment]
I believe the role is called "Scripting User" - Marking as "Needs Doc"  - Even if this is working, it should be more straightforward as to what settings and permissions are needed.

**Comment by jtesser** [comment]
Agreed but doesn't have to be opened.  Just labeled needs doc.

**Comment by DeanGonzalez** [comment]
The demo admin user automatically gets the Scripting User - I had already checked that - http://screencast.com/t/7UKEWsAvvSgv

**Comment by DeanGonzalez** [comment]
Chris skyped me thought and let me know that José is working on a safer ViewTool - so maybe the fix to this is just to kill this macro and implement José's Viewtool - maybe put a pin in this guy till the deprecation meeting.
