### ISSUE TITLE
Unable to edit and save some fields when the page is published

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7155]
If you have a published page and try to edit any field different than "URL" or "Host or Folder", the system does not allow you to save the changes unless the page is unpublished first.

To reproduce:
1-Create a new HTML page with all the required fields
2-Hit Save/Publish
3-Now open the "Page Properties" of the page you just created
4-Try to edit Title, Cache TTL, Template, Friendly Name, etc

System message:

![edit save page](https://cloud.githubusercontent.com/assets/8741846/6006083/4277d1ae-aad5-11e4-9784-cd1be0c696e3.png)

Tested on:  3.1 Nightly build 2015-01-30 16:38 // Ubuntu 14.04 // Postgres // Firefox & Chrome

Logs: https://gist.github.com/shayngr/8705d5175528fa918006

**Comment by jtesser** [comment]
we are fixing this here https://github.com/dotCMS/core/issues/7128

Not merged yet but will be soon

**Comment by bryanboza** [comment]
Need wait to fix #7128 to test...

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55728
