### ISSUE TITLE
Unable to create virtual links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7156]
When you try to create virtual links the system is having an error trying to get the html list of any folder.... And is showing a loading message but this never ends....

To recreate: 
- Go to site browser --> Links 
- Try to create a new link 
- When you click to browse to search for a internal page the system show loading message but never ends...

![2015-02-02_1357](https://cloud.githubusercontent.com/assets/2641437/6007934/74e09794-aae3-11e4-8fce-4325c083a272.png)

We have this WARN message in the log: WARN extend.Call: No methods called 'getFolderContent' in NewCreator for com.dotmarketing.portlets.browser.ajax.BrowserAjax are applicable for the passed parameters.

Tested on nightly build 2015-01-30 // Oracle // FF

**Comment by bryanboza** [comment]
FYI: This issue is not related with the new html pages because neither works with the old ones...

**Comment by jtesser** [comment]
So the issue here is we need to display one row of pages per identifier. Must not be archived.  Meaning if you have 4 languages you only display the one page.  Currently virtual links are not multilingual

We broke this with the updates to the browserAjax for the site browser. We need a new method here.

**Comment by jtesser** [comment]
We should get the default language and if that doesn't exist get the next language that does exist

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7188

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-04 // H2 // FF
