### ISSUE TITLE
Unable to push content with bundles 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7163]
Related to #7157

After this fix, now the system make the direct push of content and is working fine, the problem now is when you try with bundles.... If you add contents to a bundle and then try to push, the system is not pushing the content... Also if you try to download the bundle and then try to upload in the receiver side, neither works 

FYI:  If you download the bundle and explore it, the bundle is empty... 
![2015-02-03_1210](https://cloud.githubusercontent.com/assets/2641437/6026153/c1f08bd8-ab9d-11e4-8c4d-a86d1cc76325.png)

Tested on nightly build 2015-02-02 // H2 // FF

**Comment by dsilvam** [comment]
Could not reproduce this one. Either worked for me, adding content to bundle and pushing the bundle, and downloading the bundle and uploading it in the receiver. Success in both and new content appear on receiver node

**Comment by jtesser** [comment]
yea that is what I thought also.  Maybe is a duplicate or something was weird for @bryanboza locally

**Comment by bryanboza** [comment]
Passed, not able to reproduce in the last nightly build...  Maybe something wrong in my local...
