### ISSUE TITLE
Html Page from legacy to content Bulk Converter 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7164]
We need a button in the CMS Maintenance to Bulk convert all HTML Pages. This is in addition to the single button we have in Edit Mode. Ensure we reuse the same code as it works well

**Comment by jtesser** [comment]
this should happen 

1. create a separate thread
2. Use notification system to log details as well as log file 
3. Commit every 100 records in case of crash.  This means deleting the old  data

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-12 // Postgres // FF
