### ISSUE TITLE
Add config for html pages as content to fallthrough 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7165]
1. make the property DEFAULT_PAGE_TO_DEFAULT_LANGUAGE
2. The property will make pages act like legacy pages in multilingual sites. 
3. Basically goto to the page in the default language instead of returning 404. ie... page is in english not spanish; when browsing the front end if the property is true will get he english page and display Spanish content IF DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE is ALSO true just like we do now

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-12 // H2 // FF

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/57315
