### ISSUE TITLE
Recurrent event in other language displays wrong date format

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7166]
#7154

If you have a recurrent event in the calendar in other language different than english, when you go to the front end and open it, that displays a wrong date format
To reproduce:
1-Go to Calendar tab > Add Event
2-Create a recurrent event in Spanish 
3-From the site browser, open any page in Preview
4-Go to News & Events > Events
5-Click on the recurrent event to open it

![spanish event](https://cloud.githubusercontent.com/assets/8741846/6028821/df578ba4-abb1-11e4-9c08-0668c0a29b25.png)

Tested on:  3.1 Nightly build 2015-02-02 21:54 // Ubuntu 14.04 // Postgres // Chrome

**Comment by jtesser** [comment]
@fishsmith are we addressing this?
