### ISSUE TITLE
Page is still not allowing to save changes

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7174]
After fix #7155, the page still shows the same error when you try to make and save changes to Cache TTL, Template and any field of the Advanced Properties. It looks like it allows to save changes made only to page Title, Host or Folder and Url; not to other fields.

Tested on:  3.1 Nightly build 2015-02-03 23:54 // Ubuntu 14.04 // Postgres // Firefox

**Comment by dsilvam** [comment]
This is working for me with lastest master 3.1, made changes on all of those fields and it allows saving without problem

**Comment by jtesser** [comment]
maybe last nights commit is not make it into the build.  @shayngr can u test tomorrow

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-02-04 23:12 // Ubuntu 14.04 // Postgres // Chrome
No test case needed as it will be added for issue #7155
