### ISSUE TITLE
Time machine is not working with multi-language

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7179]
Related to #7128 

Right now the system show the pages individually depend of the language... But we need filter and show only the page in the selected language when you are creating the snap shot.... E.g:

- If you select the time machine in english we should not show the spanish pages in the sub-menu. The same thing in all the languages.... 

![2015-02-04_1119](https://cloud.githubusercontent.com/assets/2641437/6045447/c79f50ce-ac5f-11e4-9b87-b732079835c4.png)

Tested on nightly build 2015-02-03 // H2 // FF

**Comment by jtesser** [comment]
Right but @bryanboza it isn't the TM being broken but the navigation in the TM right?

**Comment by bryanboza** [comment]
@jtesser: Yes, the TM is working fine now... the problem is just navigation through the languages

**Comment by jtesser** [comment]
@dsilvam make sure to test https://github.com/dotCMS/core/issues/7194

**Comment by dsilvam** [comment]
In order to test time machine I had to set this property in the config file:
DEFUALT_DIRECTORY_INDEX_PAGE=index.html

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-09 // H2 // FF

**Comment by shayngr** [comment]
Added test case: http://qa.dotcms.com/index.php?/cases/view/56644
