### ISSUE TITLE
Extra Assets folder showing up inside the /dotsecure/assets directory

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7180]
dotCMS versions affected: 3.0 & 3.1

If this extra assets directory is not a bug, let me know if I need to document what it is for.

Here is a screenshot of the extra assets directory that appears on startup: http://screencast.com/t/5vWzMVm60k

**Comment by dotcmsCodeReview** [comment]
fwiw, I have seen this too.

On Wed, Feb 4, 2015 at 12:24 PM, DeanGonzalez <notifications@github.com>
wrote:

> dotCMS versions affected: 3.0 & 3.1
>
> If this extra assets directory is not a bug, let me know if I need to
> document what it is for.
>
> Here is a screenshot of the extra assets directory that appears on
> startup: http://screencast.com/t/5vWzMVm60k
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7180>.
>



-- 






3250 Mary Street
Suite 405
Miami, FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jtesser** [comment]
this was fixed
