### ISSUE TITLE
Integrity checker is publishing the page by default after fixing conflicts

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7181]
After fixing conflicts between HTML pages, Integrity checker publishes by default the page that was fixed (depending if it was local or remote) 

To reproduce:
1- Create a page in the remote and local sever with the same name so Integrity Checker can recognize the conflict. Do NOT publish the pages, just save them
2- Run Integrity checker and fix the conflict.
3- Now you will see that if you fixed the conflict at local node, the local page is automatically published and if you fixed the page at remote node, the remote page is automatically published.
This happens either if you fix a single HTML page conflict or multi-language pages conflict

Video capture: http://screencast.com/t/Q1Ekzezc

No errors in the log
Test info
Sender: 3.1 Nightly build 2015-02-03 23:54 // Ubuntu 14.04 // Postgres // Chrome
Receiver: 3.1 Nightly build 2015-02-03 23:54 // MacOSX 10.10 // Postgres // Firefox

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7189

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-02-04 23:12 // Ubuntu 14.04 // Postgres // Chrome

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55721
