### ISSUE TITLE
The new html pages forms need Spanish translation 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7182]
When you change your default language to spanish and try to add a new html page, all the forms are displayed in english... 

![2015-02-04_1151](https://cloud.githubusercontent.com/assets/2641437/6046080/9c0a28bc-ac64-11e4-9412-cfaf4467c6b0.png)

Tested on nightly build 2015-02-03 // H2 // FF

**Comment by jtesser** [comment]
this is not a bug. @bryanboza these are maintained as fields in the content types.
