### ISSUE TITLE
Vanity URL Laods a Page but with a different template than that of page

### ISSUE THREAD

**Issue by gtaku89f11** [dotCMS/core#7184]
For a certain page, when a vanity url is used, the page behaves differently when browsed through the vanity url than when browsed through the actual page's url. On investigation, I noticed that the vanity url sometimes loads the page but with the template and containers of another page that's in the the same folder. This to me seem like an issue with dotCMS itself in the engineering behind the scenes. How can the be fixed?

**Comment by jtesser** [comment]
we have never seen this.  Maybe you have something in your local code that is expecting something or a cache you in your implementation or something weird. 

If you have reproducible steps on demo.dotcms.com let us know

**Comment by gtaku89f11** [comment]
Okay. I'll look closer into this later. Thanks.
