### ISSUE TITLE
Integrity checker error when you use the letter "ñ"

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7187]
In spanish is normal use the letter "ñ", in english this does not exist.... But we are having the follow problem when you use that in a folder name...

- If you add a new folder E.g "Español", and add some html pages in to that.... This on both sides manually (sender and receiver)... The system should be detect conflicts, but right now we are not doing that... Seem the integrity checker is excluding that case and is not finding the folder conflict, neither the html conflicts 

Tested on nightly build 2015-02-03 // H2 // FF.... This on both sides

**Comment by wezell** [comment]
How about utf-8 chars?

**Comment by jtesser** [comment]
yes in general should be same fix. I hope :-)

**Comment by oarrietadotcms** [comment]
Fixed: https://github.com/dotCMS/core/pull/7400

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-16 // Postgres // FF
