### ISSUE TITLE
Unable to add new banner in a 3rd language thru edit mode

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7190]
If you have an HTML page in a 3rd language different than english or spanish (french, chinese, etc) and try to add new banner from Edit mode, you will get a "null" message, however if you create it thru Content Search, it does work.

To reproduce:
1- Create a 3rd language (french, chinese, etc)
2- Create an HTML page in that language
3- Open the page in Preview 
4- Lock the page for editing
5- Click "Add Content" > New Content
6- Create a banner using the 3rd language
7- Upload an image and hit Save. You will see the "null" message and if you try to save the page again it will loop in "Saving Content"

Video capture: http://screencast.com/t/uNLKtJAF

Log: https://gist.github.com/shayngr/c88716ae11089f9cd940

Tested on: 3.1 Nightly build 2015-02-03 23:54 // Ubuntu 14.04 & MacOSX 10.10 // Postgres // Firefox & Chrome

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7201

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-09 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55729
