### ISSUE TITLE
Error with Permission field when you add New Contnent

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7192]
Reproduced in 2015//01//30- MSSQL

Steps:
    1.Create a structure with text and Permission fields.
  2. Now try to add a new content to it. 
  3. You will see errors in the console after clicking add new content button.
Please see http://screencast.com/t/iyzVsmqD
Error in console:  https://gist.github.com/anonymous/d652afb652b9fd4c278f

**Comment by maurizo** [comment]
Pull request: #7204

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-06 // H2 // FF
