### ISSUE TITLE
The html pages have the language variable in the URL

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7194]
When you create a new html page, then go to front-end, and try to see the page, the system make the redirection but include the "?language_id=1" in the URL by default.... 

We need use this just to set the session language, but  after this when you navigate over pages should be disappear... 
![2015-02-05_1000](https://cloud.githubusercontent.com/assets/2641437/6063606/2015d764-ad1e-11e4-8ee2-69634dcb1814.png)

Tested on nightly build 2015-02-04 // H2 // FF

**Comment by dsilvam** [comment]
this will be fixed in https://github.com/dotCMS/core/issues/7179

**Comment by jgambarios** [comment]
Images showing the issue:

http://screencast.com/t/W2og1x17ehP
http://screencast.com/t/fziO6dh8yE

**Comment by bryanboza** [comment]
need the #7179 to test...

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-09 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55737
