### ISSUE TITLE
Can't delete structure

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7196]
Trying to delete structure special_suggestion_new_route. Got this error:
![1_trying_to_delete](https://cloud.githubusercontent.com/assets/2236103/6065259/d35b2576-ad74-11e4-8721-bac6af16b8df.png)
Open this container and can't find any mentions of special_suggestion_new_route
![2_structure_is_not_used](https://cloud.githubusercontent.com/assets/2236103/6065291/237e625c-ad75-11e4-94e9-91b24fe9b0a7.png)
Trying to find uses of this structure in whose site and got no results:
![3_can t_find_using_of_structure](https://cloud.githubusercontent.com/assets/2236103/6065300/43bec318-ad75-11e4-8887-70f72e1c328f.png)

We think that this content could be used in previous versions of container it causes this error. But can't search through them and didn't find anythings in huge amount of vesions manually.

**Comment by jtesser** [comment]
yes this is a known issue. It is with previous versions. You need to clean previous version which you can do in the CMS maintenance and then delete
