### ISSUE TITLE
Additional system error with new banners in 3rd language

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7197]
Related to #7190

1- When you create a new banner in a 3rd language **through Content Search** and try to add it to the page you have in the same language, the system shows the message "Ooops, sorry. This has caused a problem", but you can see the banner if you refresh the page
2- On the other hand, when you "Release Lock" in Edit mode, you will not see the new banner

To reproduce:
1- Create a 3rd language (french, chinese, etc)
2- Create an HTML page in that language
3- Create a new banner in that language through the Content Search
4- Open the page in Preview 
5- Lock the page for editing
6- Click "Add Content" > New Content
7- Add the banner you created
You will see the error "Ooops, sorry. This has caused a problem" but if you refresh the page you can see the banner

![ooops sorry](https://cloud.githubusercontent.com/assets/8741846/6065874/441f7632-ad2e-11e4-805b-4e608051c84a.png)

8-When you try to remove the banner clicking on the "X", you will see the same error again

Video capture: http://screencast.com/t/Kva49G7Z

Log: https://gist.github.com/shayngr/3400624782fcc283f821

Tested on:  3.1 Nightly build 2015-02-04 23:12 // Ubuntu 14.04 // Postgres // Chrome

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7201

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-06 // H2 // FF
