### ISSUE TITLE
Error trying to add contents to spanish pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7198]
Right now if you add a new html page in any language different to the default, and then you try to add a new content that no have content version in the page language we are having an error here....

- Need show more specific error
![2015-02-05_1511](https://cloud.githubusercontent.com/assets/2641437/6069363/3b26024c-ad49-11e4-9d65-7c81290d951d.png)
 message....

- And we have a NPE in the log: https://gist.github.com/bryanboza/b95fc1771aa26b27eb4a

Tested on nightly build 2015-02-04 // H2 // FF

**Comment by jcastro-dotcms** [comment]
Related to https://github.com/dotCMS/core/issues/7190

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7201

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55732
