### ISSUE TITLE
Log error adding content to a pages in different languages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7210]
Related to #7198 

Now the system is not showing the null error, but we have a stack trace in the log every time that you try it....

To recereate: 
- Add a new spanish page (without english version)
- Try to reuse content and add a english content to the page 

We have the follow stack trace: https://gist.github.com/bryanboza/f7dc300d29d2a1c4da69

Tested on nightly build 2015-02-06 // H2 // FF

**Comment by jtesser** [comment]
I guess in this case we should not log an error.  We can add to the page and based on the fall through property it may or may not show

**Comment by maurizo** [comment]
Pull request: #7219

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55734
