### ISSUE TITLE
Site search is redirecting to demo.dotcms.com 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7211]
When you add a new site search index, and make any search from front-end, the system is showing all the results with "demo.dotcms.com" URL, and this don't make sense, the system should be take the same URL that you have in the system... Like in the 2.x versions 

![2015-02-09_1507](https://cloud.githubusercontent.com/assets/2641437/6115772/995123f2-b06d-11e4-8bd1-00d18ec690b5.png)

Tested on nightly build 2015-02-06 // H2 // FF

**Comment by jtesser** [comment]
i think the paths use to be relative.

**Comment by dsilvam** [comment]
updated in the starter
