### ISSUE TITLE
Past time machine is not working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7216]
We are having problem when you try to create a past time machine snapshot, the system is showing an error in log and when you try to open we have a error message:
```
WARN velocity.DotResourceLoader: Error ocurred finding resource 'live/9b81a298-9e18-4f83-9197-9abe0fa4bae1_2.content' exception: org.apache.velocity.exception.ResourceNotFoundException: Contentlet is a miss in the cache
```
![2015-02-10_0948](https://cloud.githubusercontent.com/assets/2641437/6130329/11ef9612-b10a-11e4-92a2-d196d8941f71.png)

Tested on nightly build 2015-02-09 // H2 // FF

**Comment by dsilvam** [comment]
This is because DEFUALT_DIRECTORY_INDEX_PAGE is not set to "index.html" and it is unable to find the default index page

**Comment by jtesser** [comment]
@bryanboza if you see the original issue you should notice the needed prop
