### ISSUE TITLE
Content type "Form" is not showing in drop down when you create a new content type

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7220]
If you want to create a new form, you can't select it directly from "Type:" drop down, on the contrary, you have to filter by Form then create the new form.

To reproduce:
1) Login with admin
2) Go to "Content Types" tab
3) Click "Add New Content Type"
4) Click on "Type" drop down

![form option](https://cloud.githubusercontent.com/assets/8741846/6134993/b0fb06e0-b12a-11e4-9df8-48e23fbb85bb.png)

Tested on:  3.1 Nightly build 2015-02-09 23:14 // Ubuntu 14.04 // Postgres // Chrome

**Comment by jtesser** [comment]
You need to add forms from the forms Portlet this is by design
