### ISSUE TITLE
DEFAULT_PAGE_TO_DEFAULT_LANGUAGE prevents you from selecting another language in Edit mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7223]
When you have DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true you should be able to switch back and forth between languages in Edit mode.  It should work exactly as it does now.  If DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=false and there is no version in the other languages, then you should not be able to switch.

![screen shot 2015-02-10 at 3 45 53 pm](https://cloud.githubusercontent.com/assets/934364/6136125/27cfe4dc-b13c-11e4-8502-e9f0111079a2.png)

**Comment by jtesser** [comment]
Need to do the following here

1. Abstract the method at line https://github.com/dotCMS/core/blob/master-3.1/src/com/dotmarketing/velocity/VelocityServlet.java#L438  it is copied and pasted multiple times 
2.

**Comment by brentgriffin** [comment]
To be clear:  If DEFAULT_PAGE_TO_DEFAULT_LANGUAGE is set to false, only the languages that the page exists in should be in the combo box.

If DEFAULT_PAGE_TO_DEFAULT_LANGUAGE is set to true, languages that the page does not exist in will be in the combo box grayed out.  If you select a grayed out language, you are actually viewing the page in the default language but any content on the page that is multilingual should display based on the rules regarding DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE.

**Comment by bryanboza** [comment]
Working as expected.... Tested on nightly build 2015-02-17 // Postgres // FF

**Comment by shayngr** [comment]
Added test case http://qa.dotcms.com/index.php?/cases/edit/56645/1
