### ISSUE TITLE
Incorrect confirmation message if you publish archived link

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7224]
If a link is archived, the system doesn't allow to published it however it tells the user "Links Published"

To reproduce:
1- Login with Admin
2- Go to Site Browser > Links
3- Create a new link or modify an existing one. Do right click and change the state to "Archive"
4- Now click the checkbox and hit "Publish button"
You will see the message "Links Published"

![publish 1](https://cloud.githubusercontent.com/assets/8741846/6136404/ff637a5a-b135-11e4-83b4-d82a742b9df1.png)

![publish 2](https://cloud.githubusercontent.com/assets/8741846/6136411/1115a7d2-b136-11e4-9d3c-6a63c8975d29.png)

Logs: https://gist.github.com/shayngr/b8b03e262c28cf39b7f7

Tested on:  3.1 Nightly build 2015-02-09 23:14 // Ubuntu 14.04 // Postgres // Chrome

**Comment by jtesser** [comment]
I think this might be right. I think you need to be an admin to create these currently.  @shayngr i believe if you look at 2.5 it worked the same.  Let me know

**Comment by brentgriffin** [comment]
Seems to be an issue.  Says "Links Published" but did not published.

**Comment by jtesser** [comment]
Messaging is bad. The issue is that you cannot publish something archived.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-19 // Postgres // FF
