### ISSUE TITLE
Failed to publish link from Site Browser

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7225]
The system allows you to publish a link from Site Browser > Links, however if you try to publish the same link directly from Site Browser, it shows an error with permissions

To reproduce:
1- Log in with Admin
2- Go to Site Browser > Links
3- Create a new link or modify an existing one. The status should be "Unpublish"
4- The system will allow you to publish the link
5- Now go to Site Browser and locate the link 
6- Unpublish and publish back the link. The system shows an error with permissions

Video capture: http://screencast.com/t/RbMu8IudI

No errors in the logs

Tested on:  3.1 Nightly build 2015-02-09 23:14 // Ubuntu 14.04 // Postgres // Chrome

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-12 // H2 // FF
