### ISSUE TITLE
Vanity URLs no longer support URLs without leading slashes

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7233]
In prior releases, dotCMS allows you to specify a url value without the leading slash. (you can verify on demo if desired)  3.1 no longer supports this syntax.

To recreate goto vanity URL page and do the following:
1.  Enter Title of "test"
2.  Leave Applies to as the default of "demo.dotcms.com"
3.  Enter URL of "test"
4.  Enter URL to Redirect To of "http://www.google.com/"
5.  Click Save button
6.  See "Invalid URL" error message display

Ubuntu 14.04 LTS // Java (build 1.7.0_76-b13) // Nightly build - 2015-02-09 23:14 // Postgres // Firefox & Chrome

**Comment by jtesser** [comment]
it should treat without the slash as a slash

**Comment by maurizo** [comment]
Pull request: #7252

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-17 // Postgres // FF
