### ISSUE TITLE
Additional TM fixes

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7238]
1. Need to alter DEFUALT_DIRECTORY_INDEX_PAGE to use CMS_INDEX_PAGE  no need for both settings 
2. Should work with just index or something in case you do not use page extensions 
3. DO a search of all code and ensure we are not referencing DEFUALT_DIRECTORY_INDEX_PAGE in either EE or Core

**Comment by wezell** [comment]
Should we merge this property with the CMS_INDEX_PAGE property?  I don't
think we need both, no?

On Wed, Feb 11, 2015 at 3:09 PM, Jason Tesser <notifications@github.com>
wrote:

>
>    1. Need to alter DEFUALT_DIRECTORY_INDEX_PAGE
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7238>.
>



-- 






3250 Mary Street
Suite 405
Miami, FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jtesser** [comment]
@wezell :-)  that is what point 1 says

**Comment by dsilvam** [comment]
TM tested with muli-language and new starter

**Comment by bryanboza** [comment]
Here we need the new starter to test....
