### ISSUE TITLE
Same error message if you unpublish new page

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7241]
System is showing the same error message as in #7029 if you try to unpublish the new page

To reproduce:
1) Create a new html page in any language and publish it
2) Go to Site Browser> HTML Pages
3) Scroll down and click "Next" button
4) Locate the new page you created and do right click > **Unpublish**
The system will throw an error:

![error occurred](https://cloud.githubusercontent.com/assets/8741846/6156488/54763a08-b200-11e4-90e4-8e18a22b6615.png)

Logs: https://gist.github.com/shayngr/c921d448bb22b16ebb65

Tested on:  3.1 Nightly build 2015-02-09 23:14 // Ubuntu 14.04 // Postgres // Chrome

**Comment by jtesser** [comment]
This is only an issue with the old flat HTML Page portlet and new page as content

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-17 // Postgres // FF
