### ISSUE TITLE
Unable to submit forms when pressing "Enter"

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7243]
Refer to #4759

If you go to Forms portlet, "Enter" key does not work when you try to submit the form.

To reproduce:
1- Login with admin
2- Go to Forms & Polls tab > Forms portlet 
3- Fill out the form and hit "Enter" key. Nothing happens.

As per #4759 notes, this should be working in 2.6 and forward 

Tested on:  3.1 Nightly build 2015-02-09 23:14 // Ubuntu 14.04 // Postgres // Chrome

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-19 // Postgres // FF
