### ISSUE TITLE
Unable to roll back Containers to previous version

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7251]
1.  Edit a container, edit it again.  Make a few versions
2.  Now look in the container history.  Click "Bring back" on the original container
3. When you return to edit it, the history looks right, but you are still looking at the latest container.

**Comment by jtesser** [comment]
OK the issue here is in 3.0 we made container_structures identifier based.  This needs to change

**Comment by jtesser** [comment]
@maurizo as we discussed here is the summary

1. convert the table to use container_inode and FK it to the container table
2. one record in the table for every structure a container version has code for. So at minimum you will have a one to one for the number of rows with the container table
3. Create a upgrade task that deletes all container inodes from container table other then current working live and update the container_structures table to support the new column and data. 
4. Everything can roll back etc.. 
5. Remember transactions

**Comment by oarrietadotcms** [comment]
This is a tricky one to merge.

We will need a new starter BUT first we will need to run the upgrade task (Task03120AddInodeToContainerStructure.java) in the starter in order the import/export logic works in our locals.

Pull Request: https://github.com/dotCMS/core/pull/7384

**Comment by brentgriffin** [comment]
Test both with 3.0 page cache on and off.
