### ISSUE TITLE
Make dotCMS work in Java 8

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7253]
This involves shipping with Tomcat 8 and newer servlet spec

**Comment by jgambarios** [comment]
The committed changes are not forcing the use of the new servlet specs used by the tomcat 8 as it won't allow us to get backward compatibility with tomcat 7.

**Result of my tests:**
 
**Without** the new servlet specs using the one specs used by tomcat 7
- tomcat7 - java8  -> Works
- tomcat7 - java7  -> Works
- tomcat8 - java7  -> Works
- tomcat8 - java8  -> Works

**With** the new servlet specs used by tomcat8
- tomcat8 - java8 -> Works
- tomcat8 - java7 -> Works
- tomcat7 - java7 -> Does NOT work
- tomcat7 - java8 -> Does NOT work

Base on those results on this issue we wont be forcing the use of the new servlet specification.

Also I renamed the task **deploy-war-tomcat7** for **deploy-war-tomcat**

**Comment by bryanboza** [comment]
For now, this is working fine on MacOSX and Windows, need wait the fix #7436

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // Postgres // FF... Java8

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // Postgres // FF... Java8

**Comment by DeanGonzalez** [comment]
Searched all docs for Java 7 and tomcat and made sure to update that we now support Java 8
