### ISSUE TITLE
Events detail page throw ESAPI error

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7255]
See logs:

http://starter.dotcms.com:8080/news-events/events/dotcms-online-training-session?id=e611f5f8-457d-48f2-9c5e-2b72bbd350bb&language_id=1&recurrenceStartDate=07/10/2011%2011:00:00&recurrenceEndDate=07/10/2011%2012:00:00

Reproduce local

http://localhost:8080/news-events/events/dotcms-online-training-session?id=e611f5f8-457d-48f2-9c5e-2b72bbd350bb&language_id=1&recurrenceStartDate=07/10/2011%2011:00:00&recurrenceEndDate=07/10/2011%2012:00:00

**Comment by wezell** [comment]
I think we can just get by urlencoding in the implementation

**Comment by jtesser** [comment]
agreed the fix should be in starter
