### ISSUE TITLE
Logging: WARN messages indicating incomplete requests.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7260]
Related to Suppor Ticket http://jira.dotmarketing.net/browse/EE-7565 Reproduced in demo.dotcms.com and 2.5.7.

Steps to reproduce:
1. Upload a large file through Website Browser. It can be a video file or a bundle of an entire host.
2. On a different browser, try to open the same file. Before the asset is completely loaded, close the browser

```
2015-02-13 17:45:45,537 WARN  com.dotmarketing.servlets.SpeedyAssetServlet - ClientAbortException:  java.net.SocketException: Broken pipe Error for = /dotAsset?path=/3/d/3d815e9e-5ea7-4e8b-ba92-218de6b6c5a5/fileAsset/9c0cadc7-6c84-402c-aa2c-ae233b83dc3c.tar.gz
```

This can also be reproduced if a breakpoint is set in CMSFilter class and when it's hit, close the browser.

As per client's comments, this message can be noisy on logfiles when several hits to a page end in incomplete requests, therefore they suggest to remove them.

**Comment by jtesser** [comment]
This error is actually thrown under the covers from tomcat. It happens as you state when a stream is closed as the file is streamed down. We can try to catch in speedy asset but it isn't a big deal. Maybe for the client turn that classes logging to error

**Comment by joseorsini** [comment]
closing this one.
