### ISSUE TITLE
Unable to add folders with the same name that existing page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7264]
Since the pages don't have extension, then now we can't add folders with the same name of the page. This because have the same path... E.g: If you have a "test" html page, and then try to add a "test" folder the system shows an error: "Folder already exists... Please enter a different name" 

http://monosnap.com/image/tZQU8XBK7NXY7gbMYpDcBdHtSzmoQr

Tested on nightly build 2015-02-12 // H2 // FF

**Comment by jtesser** [comment]
This is correct behavior.  We could change the language to Another Object Exists but this is right

**Comment by bryanboza** [comment]
That issue is only with the new html page as assets, i am not able to reproduce in old versions before 3.1...

**Comment by jtesser** [comment]
because they never had the same name

**Comment by jtesser** [comment]
@samuelmortha simply make the error more descriptive here.  you cannot have a page and folder at the same level with the same URL

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-24 // Postgres // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55731
