### ISSUE TITLE
Lock for editing is not working on legacy pages

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7268]
If you open in Preview a legacy page, "Lock for Editing" is not working.

To reproduce:
1- Login with admin
2- Open in Preview an existing legacy page, i.e.: "about us" folder > index.html or "products" folder > detail.html
You will see that "Lock for Editing" does not change status to "Release Lock"

![lock for editing](https://cloud.githubusercontent.com/assets/8741846/6230275/ed4da432-b683-11e4-9774-d1753d4629e5.png)

Tested on:  3.1 Nightly build 2015-02-13 19:35 // Ubuntu 14.04 // MySQL // Firefox & Chrome

**Comment by brentgriffin** [comment]
From looking at the screenshot, it does not appear to have an edit tab at all.

**Comment by maurizo** [comment]
Pull request: #7295

**Comment by bryanboza** [comment]
Fixed, now we have the 3 tabs as default....
