### ISSUE TITLE
Elastic Search Quests should support +contentType:

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7269]
When we changed the name of Structure to Content Type we left the elastic search queries with +structureName.  Since this language is now inconsistent, we should support the use of +contentType as a way to query Content Types.  

+structureName should continue to be supported if this is possible, but we should not have two names for the same dotCMS object.

This will avoid confusion for the clients in our code and documentation such as this:

http://dotcms.com/docs/latest/ContentSearchSyntax

![structurenameinelasticsearch](https://cloud.githubusercontent.com/assets/1569167/6230700/4f0ef0f6-b687-11e4-805c-7bd2075a083e.png)

**Comment by wezell** [comment]
yup.  We should support both but note that the structureName is deprecated.

**Comment by dsilvam** [comment]
fixed here. https://github.com/dotCMS/core/pull/7370

**Comment by dsilvam** [comment]
new PR sent

**Comment by jtesser** [comment]
@dsilvam need a bit more work. As seen in the screenshot above lets update the messaging to the user

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-24 // Postgres // FF

**Comment by DeanGonzalez** [comment]
Doc was prepared, waiting to publish: http://dotcms.com/docs/latest/content-search-syntax
I also searched for +structureType and +structureName in all docs and replaced

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59166
