### ISSUE TITLE
Replace "Host" with "Site" on Site Portlet

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7271]
Saw this on the 3.0.1 version

There is still some "Host" terminology on the Site Portlet that we need to replace with "Site".  Also when editing a Site, there are still some references to Host on field labels.  See images below:

![host portlet](https://cloud.githubusercontent.com/assets/1569167/6231277/550fd26e-b68b-11e4-9ec9-7fe4ea90ebdd.png)

![editsite](https://cloud.githubusercontent.com/assets/1569167/6231306/8523e8be-b68b-11e4-9432-414a07688fe6.png)

![system site](https://cloud.githubusercontent.com/assets/1569167/6231282/5a6c4292-b68b-11e4-884a-7bef3543aa82.png)

**Comment by jkshapiro** [comment]
See also #6718

**Comment by jkshapiro** [comment]
And #6542

**Comment by rogelio-blanco** [comment]
This issue is related with he starter.   We need to change the host component in the starter this seems to be NOT related with the code.
