### ISSUE TITLE
Permissions - Can't Remove CMS Anonymous from a Site

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7272]
Tested this on multiple 3.0.1 servers, including demo

-To reproduce, edit a Site on the 3.0.1 version
-Remove all permissions for CMS Anonymous role
-Save the permission changes
-Re-edit the Site
*I made sure to clear both the dotCMS cache and the browser cache to make sure this was not a cache ghost

Bug is that CMS Anonymous is still there with no permissions.  This is NOT only on the Demo host, but even on a new clean host with no dependencies.  I also saw that this appeared to affect the inheritance chain - some thing appearing on front end that should not be, had to keep re-editing child objects and permissioning them individually.

Screenshot: http://screencast.com/t/9FpPYfeF

Screencast: http://screencast.com/t/ssy0d5TGnV

**Comment by jtesser** [comment]
yes in this case we always show it. Has been this way in all 2.x and 3.x
