### ISSUE TITLE
Workflow error after fixing conflicts

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7273]
System is showing an error with workflow actions after fixing conflicts

To reproduce:
1- Login with admin
2- Set up a push publish environment
3- Create a test workflow and add a "Step" and "Action" to it, then save it. Do this in both servers (under and receiver) so the system can detect the conflict
4- Run the integrity checker in the sender and select "Fix Conflicts at Local Node"
5- In the sender, go to Content Type > Workflow Schemes and open the "Action" inside the test workflow you created.
You will see the error

![workflow action error](https://cloud.githubusercontent.com/assets/8741846/6231922/54ac5538-b68e-11e4-9e3c-5f192983b0ab.png)

 
Video capture: http://screencast.com/t/vg4lkTYR8V

Logs: https://gist.github.com/shayngr/8409bb19f7dff86b104d

Test info:
Sender: 3.1 Nightly build 2015-02-13 19:35 // Ubuntu 14.04 // MySQL // Chrome
Receiver: 3.1 Nightly build 2015-02-13 19:35 // MacOSX 10.10 // MySQL // Firefox

**Comment by shayngr** [comment]
Currently not working. Waiting on fix #7355

**Comment by dsilvam** [comment]
fix in #7355 does not have anything to do with workflow, this was fixed in the commit in this issue. @shayngr  could you please describe the problem? is it the same? make sure you have that commit in

**Comment by shayngr** [comment]
For this issue #7273, step 4 requires to run integrity checker in order to detect the conflicts with the workflows, however when I run it I'm getting the same error reported in gist https://gist.github.com/bryanboza/42665d9c172db5a83a9f (#7355) so I cannot verify the fix for this one

**Comment by dsilvam** [comment]
@shayngr I understand. Fix for that issue is now merged, will be in the next nightly

**Comment by shayngr** [comment]
Fix is working.
Tested on:  3.1 Nightly build 2015-02-26 20:53 // Ubuntu 14.04 // MySQL // Firefox & Chrome

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55722
