### ISSUE TITLE
Page URL field should strip accented characters that break the HTML Page

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7274]
Tested on version 3.0.1 on a few servers, including demo

Page URL field needs to strip accented characters which are part of an HTML page title.  We need to allow the accented character in the title, but strip them properly in the page url field.

To reproduce:
Create a new HTML page and Title it :"Cédula"
(notice that the accented character gets saved in the page url field automatically)
Then choose a template and save/publish the page
The page does not resolve and requires a re-edit of the page properties, taking the accented character out of the url field so that the page resolves instead of showing a blank screen in the browser.

Screencast: http://screencast.com/t/Nx5mEseMj

**Comment by jkshapiro** [comment]
It would be better to fix the underlying error. If the users wants a page name of cédula.html then they should be allowed to have it. This becomes especially important with non-Latin-based alphabets e.g. Chinese or Arabic, where the proposed solution would end up stripping every character in the page name.

**Comment by jtesser** [comment]
@samuelmortha escape the character so they work. Make sure to test front end and edit mode. I agree with @jkshapiro comments above

**Comment by jtesser** [comment]
For the dev who works on this. I do NOT want to alter the esapi.props as was in the commit above.  I closed the pull request so create a new branch

**Comment by wezell** [comment]
Can we talk about this?  The initial conception was to support UTF-8 in the
url (or however the browser sends utf-8).  I originally tested with a url
like

/about-us/域名交易论坛

I want to make sure we support the spec.

**Comment by jtesser** [comment]
I think that will work @wezell . I understand what you are after.  Should be able to handle with the URL and the spanish one above ie....
