### ISSUE TITLE
Integrity checker is not finding conflicts for other languages

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7276]
Integrity checker is not finding conflicts for languages different than English or Spanish

To reproduce:
1- Login with admin
2- Set up a push publish environment
3- In both servers create a new language different that English and Spanish
4- In both servers create a new page in that language with the same name so Integrity Checker can recognize the conflict.
5- Run Integrity checker, you will see the system is not finding conflicts.
However if you create a page in English or Spanish in both servers with the same name, the system will detect the conflict.

Video capture: http://screencast.com/t/hqxSKPzHU

No errors in the log

Test info:
Sender: 3.1 Nightly build 2015-02-13 19:35 // Ubuntu 14.04 // Mysql // Chrome
Receiver: 3.1 Nightly build 2015-02-13 19:35 // MacOSX 10.10 // Mysql // Firefox

**Comment by dsilvam** [comment]
fixed in #7280

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-02 // Postgres // FF
