### ISSUE TITLE
Non CMS Admin users can't contribute a File Asset without "Legacy File" Permissions

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7279]
Tested on version 3.0.1 local server and on demo.dotcms.com

A non-admin should only need the ability to publish "Content/Files" to be able to publish file assets to the host

To reproduce
1) Create a new role
2) Give the new role "Add To" on the Site and Publish on all children EXCEPT "Legacy Files"

![sitepermissions](https://cloud.githubusercontent.com/assets/1569167/6235175/275e9fd8-b6a6-11e4-94f4-ff17a923026e.png)

3) Give the new role access to the content tab and Publish on the File Asset structure
4) Create a new user and assign the role to the user
5) Login as the new user and try to submit a File Asset

Results in permissions error on submit:

![error](https://cloud.githubusercontent.com/assets/1569167/6235116/98550980-b6a5-11e4-9d1b-edc30f3e8ad7.png)

**Comment by bryanboza** [comment]
I am able to reproduce on 3.1

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-19 // Postgres // FF
