### ISSUE TITLE
Cannot add 3 nested folders 

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7281]
If you try to create 3 nested folders (one inside another) or more, the form used to add new folders stops working

To reproduce:
1- Login with Admin
2- In the root create a new folder (test1)
3- Inside the first folder (test1) create another new folder (test2)
4- Inside the second folder (test2) create another new folder (test3)
At this point the form functionality (buttons, drop down, etc) stops working

http://screencast.com/t/stlXYOb92

No errors in the log

Working as expected.
Tested on:  3.1 Nightly build 2015-02-13 19:35 // Ubuntu 14.04 // MySQL // Firefox

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-18 // Postgres // FF
