### ISSUE TITLE
Assign worflow action" pop-up needs styles help

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#7285]
To Reproduce:
  
  1.Create a content for Content (Generic) structure.
  2.Assign it to a Publisher role.
  3. Go to Workflow Tasks tab and try to re-assign it like as shown in screen cast..
  4.You will see Save and cancel buttons are not showing properly.  
Please see    http://screencast.com/t/Gd86Q5RcB3
Screen cast : http://screencast.com/t/8CiJlaau8nJ

**Comment by bryanboza** [comment]
Reopen in #7324
