### ISSUE TITLE
Unable to fix html conflicts

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7289]
Related to #7244 

When you have a html conflict and run the integrity checker, then you try to solve the conflict the system throws an error in the log and can't solve the problem

To recreate:

- Create a new folder with the same name in both sides (sender and receiver)
- Add one page with the same name in every folder
- Run the integrity checker
- Fix the folder conflicts on local node
- Try to fix the html conflicts in the remote node

Here the SC: https://gist.github.com/bryanboza/3394fecc3f08eca3314e
Log: https://gist.github.com/bryanboza/f31f749b8fe929e342e7

Tested on nightly build 2015-02-17 // Postgres // FF

**Comment by jtesser** [comment]
@bryanboza I think this shouldn't work presay. You should fix both local or both remote. Or you need to run the checker a second time.

**Comment by bryanboza** [comment]
@jtesser I think this should be individually every transaction, for me does not make sense discard the html conflicts every time you fix folder conflicts, this just to update the temporal conflicts table.... You should be able to select where you wanna fix the conflict... If not then maybe we should delete the option to select the local or remote node and fix the conflicts just in one side
