### ISSUE TITLE
ESContentResource does not accept a POST

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7291]
Which means for it to work, you need to do a GET which leaves the whole query string on the access logs.

**Comment by wezell** [comment]
Here are  working examples for our documentation:

jquery:
https://gist.github.com/wezell/df0e5b10e6edb8bdec2a#file-javascript-example

curl:
```
curl -H "Content-Type: application/json" -XPOST http://localhost:8080/api/es -d '{
    "query": {
        "bool": {
            "must": {
                "term": {
                    "_all": "gas"
                }
            }
        }
    }
}'
```

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-23 // Postgres // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59171
