### ISSUE TITLE
Minor Bug -Stopping and restarting server changes name of "CMS Anonymous" role to "Current User"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7294]
Tested on 3.0.1

Each time you stop and start the dotCMS server, the "CMS Anonymous" role switches names in the cache to "Current User" - a cache clear fixes this until you stop and restart the server again, but an annoying cosmetic UI bug.

![current user](https://cloud.githubusercontent.com/assets/1569167/6253151/f2716408-b764-11e4-8d16-56a415325967.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13360

**Comment by bryanboza** [comment]
Unable to reproduce with the last changes. Tested in the last master // Postgres // FF
