### ISSUE TITLE
Cannot republish, unpublish or copy on different Contents

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7297]
To reproduce:
1- Login with admin
2- Navigate to Content > Content Search
3- From Type drop down, select different contents such as News, Banner, Blog, Comments, etc 
4- Right click over any of the content per se and choose Republish, Unpublish or Copy
You will get an error

![error with news](https://cloud.githubusercontent.com/assets/8741846/6256298/9f98e112-b77c-11e4-8725-c7e1c60385ee.png)

Logs: https://gist.github.com/shayngr/53bac5da8516c4a5cc75

Tested on:  3.1 Nightly build 2015-02-17 22:51 // Ubuntu 14.04 // MySQL // Firefox & Chrome

**Comment by maurizo** [comment]
Pull request: #7303

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-02-21 21:54 // Ubuntu 14.04 // MySQL // Firefox & Chrome
