### ISSUE TITLE
Change in behavior when adding a new page

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7302]
System no longer previews HTML Pages when you add them to the system.

1.  Go to site browser
2.  Through dropdown selection in upper right, add a new Page
3.  Fill in fields and select "Save and Publish"
in previous versions this would have previewed the page on the edit tab.  Now it just returns to the site browser without previewing the page.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-21 // H2 // FF
