### ISSUE TITLE
Vanity URLs to folders broken again

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7305]
This issue is broken again:  https://github.com/dotCMS/core/issues/6912

At this point redirects to "/products/" and "products/" are both broken.

Ubuntu 14.04 LTS // Java (build 1.7.0_76-b13) // 3.1 Nightly build 2015-02-17 22:51 // Postgres // Chrome

**Comment by brentgriffin** [comment]
Hold off on this one - think it may be a local configuration issue relating to the default index page setting

**Comment by maurizo** [comment]
Pull request: #7308

**Comment by jtesser** [comment]
not a bug

**Comment by brentgriffin** [comment]
Yeah, this is the CMS_INDEX_PAGE setting.  The current setting is assuming "index" for the default page.  But our current default pages are "index.html".  We need the new starter here.
