### ISSUE TITLE
HTTP client request tools should all have a configurable request timeout

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7307]
This should get passed to URLConnection, and includes $json.fetch and xmltool. Velocity code calling failed external services will hang and eat all Connector threads causing global outage.

**Comment by wezell** [comment]
Also the $import.read as well.

**Comment by jtesser** [comment]
they do it is built into Java 
http://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html

you can set this using a system property on startup

**Comment by jtesser** [comment]
ok so the issue is in some places we hard code the timeout
URLConnection uc = u.openConnection();
               uc.setReadTimeout(15000);

we need to fix this. In these cases pass it in.  If null then take the default meaning do not set and will be picked up by system property or default

**Comment by chrismccracken** [comment]
Re: https://my.dotcms.com/ticket/dotcms-8

**Comment by wezell** [comment]
Here is test vtl code

```
#set($query = "http://localhost:8080/api/content/render/false/type/json/query/-structureName:Host%20-structureType:3%20+(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797%20conhost:SYSTEM_HOST)%20+deleted:false%20+working:true/limit/1/orderby/modDate%20desc")

#set($thisData = $json.fetch($query, 1000))

$thisData
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8017

**Comment by bryanboza** [comment]
Fixed, tested on dotCMS_3.3 // Postgres // FF
