### ISSUE TITLE
Bundling and Push Publishing API

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7309]
[Support Ticket: https://my.dotcms.com/ticket/dotcms-9]

**Objective:** Automate promotion of objects within a push pub environment manually or via automated processes.
###### Push publishing requirements:
- Push a host, bundle, or individual piece of content (including dependencies)
###### Bundles scripting requirements:
- Add content to bundles by id or inode (including dependencies)
- Download a content bundle archive
- Re-create bundles which have already been pushed (in order to have additional content added/removed)
- Ability to retrieve a bundle manifest (exact contents listing) that can be used as a template to create a new bundle

**Comment by chrismccracken** [comment]
This is needed for Content Integration testing workflow. Need public API to read/write existing/new bundle contents and manage bundle deployment for a repeatable process. 

Example:
1) Bundle is created in Dev environment traditionally during dev cycle.
2) At close of dev cycle & time of bundle content promotion, API captures content of bundle prior to deployment.
3) API automates bundle deployment to QA env
4a) If issues are found in bundle post-deployment, API allows re-creation of bundle as baseline for fixes.
4b) If bundle is OK, API allows re-creation of bundle for deployment to Production pipeline.

**Comment by jtesser** [comment]
a lot of this is possible through our jersey classes and receiving servlets already 

https://github.com/dotCMS/core/blob/master-3.1/src/com/dotcms/rest/BundleResource.java
https://github.com/dotCMS/core/blob/master-3.1/src/com/dotcms/rest/BundlePublisherResource.java
