### ISSUE TITLE
NPE trying to add content to legacy pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7312]
We are having a NPE when you try to add a new content to any legacy page, the system is showing a "null" message...
![2015-02-19_1518](https://cloud.githubusercontent.com/assets/2641437/6276188/962989be-b84a-11e4-80f1-80abd2f60bb6.png)

Log: https://gist.github.com/bryanboza/060915e01889257f8b5c

Tested on nightly build 2015-02-18 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-21 // Postgres // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/56641
