### ISSUE TITLE
live and a working cannot be unpublished via right-click

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7315]
If a piece of content or page has a live and a working version that are different, you cannot right click and unpublish.

We do not offer the option in the UI and we should (if workflow is not mandatory)

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-21 // Postgres // FF

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/56656

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/56656
