### ISSUE TITLE
Limited user can select a  Page content they do not have permissions to use

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7318]
From the browser, users should not be able to see types of page content tow which they have no permissions.

1. login as a limited user - joe@dotcms.com / joe - who is only a contributor.
2. go to the browser, right click and hit "add a page".  You will get a popup that shows the default Page Asset - joe has not permissions to this content type.  If you try the same thing with File Assets, the list is filtered correctly.
![screen shot 2015-02-20 at 11 02 56 am](https://cloud.githubusercontent.com/assets/934364/6289813/c7fcc1b2-b8f0-11e4-9c80-0f02fd4abf1a.png)

3. ALSO, while we are at it, we need to change the flyout menu to just say "Page", not "
![screen shot 2015-02-20 at 11 09 00 am](https://cloud.githubusercontent.com/assets/934364/6289843/fbd8dc0a-b8f0-11e4-99d7-29ba72d9d95f.png)
HTML Page"

**Comment by dsilvam** [comment]
Same thing happens for FileAsset type, just choose "FileAsset" as the default type for the folder, then log in as Joe and try to add a new Image or File, you will see type "FileAsset" in the list

**Comment by shayngr** [comment]
Fix is working
Tested on:  3.1 Nightly build 2015-02-21 21:54 // Ubuntu 14.04 // MySQL // Firefox & Chrome

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/56642
