### ISSUE TITLE
Assign worflow action needs styling help

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7324]
To Reproduce:

- Create a content for Content (Generic) structure.
- Assign it to a Publisher role.
- Go to Workflow Tasks tab and try to re-assign it like as shown in screen cast.. 
- You will see Save and cancel buttons are not showing properly until you expand the assignee drop down...

Also the top bar is disappearing... 

SC: http://screencast.com/t/iWWvqrMwaZ

Tested on nightly build 2015-02-19 // Postgres // FF

**Comment by samuelmortha** [comment]
This is fixed here https://github.com/dotCMS/core/issues/7285 

Can you please check this on latest master-3.1.

**Comment by shayngr** [comment]
Fix is working.
Tested on:  3.1 Nightly build 2015-02-21 21:54 // Ubuntu 14.04 // Postgres // Firefox & Chrome
