### ISSUE TITLE
Time machine is showing the archived html pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7336]
Related to #7238 

When you have a multi language page, and archive one of the languages, then go to time machine and create a future snapshot, the system is showing the archived language pages...

To recreate:
- Create a multi language page (English, Spanish), and enable the show on menu property
- Archive the Spanish page 
- Create a future time machine snapshot 
- Select the language Spanish and go to the archived page 

The system is showing the spanish version and this is archived 

SC: http://screencast.com/t/kQ5ggFpT

Tested on nightly build 2015-02-21 // Postgres // FF

**Comment by dsilvam** [comment]
For Testing: you need to set DEFAULT_PAGE_TO_DEFAULT_LANGUAGE to false, cause if you test with the default (true), it won't find the page in the other language (cause it is archived) and will get the page in the default language.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-02 // Postgres // FF

**Comment by bryanboza** [comment]
Tested on nightly build 2015-03-02 // Postgres // FF
