### ISSUE TITLE
Unable to delete languages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7339]
We have a integrity constraint violation when you try to delete any language from the system

Here the log: https://gist.github.com/bryanboza/44a4f3c192c774b25b20

Tested on nightly build 2015-02-21 // Postgres // FF

**Comment by jtesser** [comment]
This is correct for right now.   We ned messaging in the UI but you are using that language for some  content and cannot delete it

**Comment by oarrietadotcms** [comment]
Message added: https://github.com/dotCMS/core/pull/7422
