### ISSUE TITLE
Directory redirects need to be 301, not 302

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7340]
We need to change the redirects we use when a visitor hits a directory without the trailing slash to return a 301 redirect, not a 302.  302s are not seo friendly.

```
cabbage:~ will$ curl --head http://localhost:8080/about-us
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=B1E1AD9DA46A0AC5767B19DD9563F1A9; Path=/; HttpOnly
Location: http://localhost:8080/about-us/
```

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-27 // Postgres // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59167
