### ISSUE TITLE
System allows to create exact same language more than twice

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7342]
System should allow to include the same language with different values (i.e.:Country Code or Country) but restrict the usage of duplicated languages with the exact same information.

To reproduce:
1) Login with admin
2) Create a language in Espanol ( do it two or three times with the exact same values)

![same language 1](https://cloud.githubusercontent.com/assets/8741846/6337017/7a3a78c4-bb6c-11e4-9bfc-e67529e02301.png)

The language is duplicated many times

![same language 2](https://cloud.githubusercontent.com/assets/8741846/6337028/95008fe0-bb6c-11e4-9de9-39dc78c01008.png)

Tested on:  3.1 Nightly build 2015-02-21 21:54 // Ubuntu 14.04 // MySQL // Firefox & Chrome

**Acceptance criteria:** 
- [x] Integration tests
- [x] Postman tests for LanguageResource

**Comment by nollymar** [comment]
**Note to QA:**  LanguageResource should be tested as well

**Comment by jcastro-dotcms** [comment]
This issue is still reproducible in latest master

**Comment by yolabingo** [comment]
We received an additional request for this enhancement from a cloud customer

**Comment by erickgonzalez** [comment]
Tested via UI and Language Resource.

**Comment by bryanboza** [comment]
If you add a new language, try to edit this one, if you don't change anything and just click to save again, we are getting an error that other language with the same value already exist, then we have two options here :

- Have a better handle here and detect that the one that exist is the same one, 
- Disable the save button in case no changes detected.

**Comment by bryanboza** [comment]
Now we fix the error reported above, but when you try to save a language that already exist, we are printing a noisy log and algo we have a hibernate error here: ```DotHibernate: error on rollbackTransaction ```

We need to print just a line error here 

Log: https://gist.github.com/bryanboza/b4394344b91daed80dd036711b02e7e7

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Docker

**Comment by swicken-dotcms** [comment]
Changes too big for 5.3.8.6 LTS
