### ISSUE TITLE
Integrity checker: Unable to fix html conflicts 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7344]
Again we have problems fixing html conflicts with the integrity checker...

To recreate: 
Just the simple use case
- New folder with a new page both with the same name on both sides (local and remote)
- Run the integrity checker 
- Try to fix the html conflicts in the remote side 

Log: https://gist.github.com/bryanboza/67edbc2b0eae0904babf

Tested on nightly build 2015-02-21 // H2 // FF

**Comment by jtesser** [comment]
@dsilvam i think this may have been fixed with yesterday's commits?  Thoughts?

**Comment by dsilvam** [comment]
@jtesser I think so, just going to make sure

**Comment by dsilvam** [comment]
@jtesser right, fixed on #7280
