### ISSUE TITLE
Documentation: Content types still called "Structures" in places

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7346]
Including https://dotcms.com/docs/latest/BuildingYourFirstContentType. This is causing confusion: see, e.g., https://groups.google.com/forum/?fromgroups#!topic/dotcms/dQlSwqey0eA.

The documentation needs to match the product. Incorrect documentation is worse than none at all.

**Comment by jtesser** [comment]
yes we are on them.
