### ISSUE TITLE
Integrity checker: The integrity checker is not working

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7355]
Related to #7347 

We have some errors with the integrity checker:

- The system is showing an error running the HTML Pages Integrity Check.... https://gist.github.com/bryanboza/42665d9c172db5a83a9f

- By this error then the system is not detecting html page conflicts 

- The system detect folders conflicts, but you are unable to fix

To recreate: 
- Create a new folder with a html page in to it (this on both sides)
- Run the integrity checker 
- Check your log (we have the stack trace)
- Try to fix the folder conflict (have another error)

Tested on nightly build 2015-02-24 // H2 // FF

**Comment by bryanboza** [comment]
Tested with MySQL and able to reproduce the same problem

**Comment by dsilvam** [comment]
This was because of multilang pages in the new starter. Multilang page support for IC was added .

**Comment by jtesser** [comment]
@wezell just FYI I manually updated DB for starter so should just be able to update the code without issue

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-26 // Postgres // FF
