### ISSUE TITLE
Enhancement: Allow message customization when a hook fails.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7357]
Currently, when a pre/post-hook returns false, we print on page what's being thrown on 

https://github.com/dotCMS/core/blob/04ce273392f0d7d3d70a2825b9f9501ecc3f91f6/src/com/dotmarketing/portlets/contentlet/business/ContentletAPIInterceptor.java#L164

By deploying a modified version of our OSGI Hooks plugin on 2.5.7 that returns false on its checkin method, we get the following:

![screen shot 2015-02-25 at 12 05 07 pm](https://cloud.githubusercontent.com/assets/1717110/6375666/a3d5d018-bce6-11e4-86ce-6e3d5135b92d.png)

Since hooks are intended for specific client-defined behavior and actions, is there a way to customize the message they're getting from within the plugin itself and not by overriding our ContentletAPIInterceptor.java class? This should help content editors to have more information about why they can't perform certain actions re: Content Editing.

I'd think of creating a specific exception class, like DotContentHookException, so we can specify the exception grabbed by the ContentletAjax instead of what's currently doing here in a more generic manner

https://github.com/dotCMS/core/blob/9e222d9aec24a03d66c5d87d3ff6ad864c8a6bac/src/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java#L1624

so when it's hit, it can retrieve the custom error message set in the same Hook and throw it accordingly. By this, the pre/post hook interfaces should have a "setCustomError" method or something the client can customize on their own.

Let us know your thoughts about this.

**Comment by joseorsini** [comment]
re: https://my.dotcms.com/ticket/dotcms-11

**Comment by jtesser** [comment]
right>  We don't have a mechanism for this.  We have discussed in the past. I think it is a good feature addition but should be built into the framework of the hook. Maybe just a specific exception we throw and has the message. This would probably be best
