### ISSUE TITLE
FolderFactoryImpl.findSubFolders() doesn't work correctrly

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7365]
In method com.dotmarketing.portlets.folders.business.FolderFactoryImpl.findSubFolders parameter showOnMenu is ignored because UtilMethods.isSet(showOnMenu) for boolean always returns true. 

![image](https://cloud.githubusercontent.com/assets/2236103/6392509/5a7128d6-bdd2-11e4-9906-572f32dab3c0.png)

Problem exists in 2.x and 3.x versions.

**Comment by jtesser** [comment]
this is not a bug and is passed from the API based on what is intended. it is querying for folders who are who on menu.  The intention is for the query to be generated based on a passed in parameter.

**Comment by jtesser** [comment]
Sorry was reading this wrong.  yea doesn't make sense
