### ISSUE TITLE
Integrity checker: We are detecting conflicts with the archived pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7373]
Since we don't allow push archived content, we should not detect conflicts if you have archived pages.... Right now the system is detecting this conflicts...

To recreate: 
- Create new html page with the same name in both sides
- Archive both pages 
- Run the integrity checker 

Tested on nightly build 2015-02-26 // Postgres // FF

**Comment by jtesser** [comment]
this is ok as you may unarchive the content and it would be ok.
