### ISSUE TITLE
"Identifier is null" error after fixing page at remote node in another language

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7382]
Related to #7280

Issue is now happening when the pages are in a language **different than English**, for instance Spanish

To reproduce:
1- Login with admin
2- Set up a push publish environment
3- In both servers create a new page in Spanish with the same name so Integrity Checker can recognize the conflict.
4- Add some content to the pages
5- Run Integrity checker and Fix conflicts at the **remote node**
6- Go to the receiver server and try to open the page in Preview
You will see the error

![identifier is null](https://cloud.githubusercontent.com/assets/8741846/6417675/be21cb4a-be74-11e4-93de-309ec78ce0a0.png)

Logs: https://gist.github.com/shayngr/fbb0ba13e61abedaf1d2

Test info:
Sender: 3.1 Nightly build 2015-02-26 20:53 // Ubuntu 14.04 // Mysql // Chrome
Receiver: 3.1 Nightly build 2015-02-26 20:53 // MacOSX 10.10 // Mysql // Firefox

**Comment by dsilvam** [comment]
I think you need to refresh site browser

**Comment by jtesser** [comment]
@dsilvam maybe show a message to the user as we discussed

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-02 // Postgres // FF
