### ISSUE TITLE
Past time machine is not including folder with show on menu property enabled when you set incremental

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7385]
Related to #7358 

When you add a new folder with some pages in to it, then run the time machine job with the incremental property to create a past time machine snapshot... The system is not showing these folders in the menu... 

Here the SC: http://monosnap.com/file/AoHmCOXjWGUC2xvBTM8lTEzPb3wiG5

Tested on nightly build 2015-02-27 // H2 // FF

**Comment by jtesser** [comment]
Not going to solve this as those pages are static pages already generated. The pages which didn't get altered will not be republished

**Comment by jtesser** [comment]
@bryanboza get with @brentgriffin on this for understanding
