### ISSUE TITLE
Cannot fix html page conflict at Local node

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7388]
The system will show an error if you try to fix the conflict at Local node.

To reproduce:
1- Login with admin
2- Set up a push publish environment
3- In both servers create a new page in any language with the same name so Integrity Checker can recognize the conflict.
4- Add some content to the pages
5- Run Integrity checker and Fix conflicts at the Local node
6- The system will show an the error

![error fixing conflict](https://cloud.githubusercontent.com/assets/8741846/6448838/3f4bc896-c0e2-11e4-9417-643d3c097d3c.png)

Logs: https://gist.github.com/shayngr/3ca4af91871ff50e9526

Sender:  3.1 Nightly build 2015-02-27 18:54 // Win7 Pro SP1 // SQLServer 2012 // Chrome
Receiver:  3.1 Nightly build 2015-02-27 18:54 // Ubuntu 14.04 // MySQL // Firefox

**Comment by bryanboza** [comment]
Tested on H2 and works fine, maybe the error is with SQLServer

**Comment by shayngr** [comment]
Working as expected.

Tested on:  3.1 Nightly build 2015-03-03 13:53
