### ISSUE TITLE
Enhancement: Make "delete" parallel to "publish", "unpublish", "archive"

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7393]
When you have a multilingual contentlet, and you take various actions with it, the results are not parallel. Specifically:
- publish, unpublish, and archive all apply only to one language variant
- delete applies to all language variants

They should all work the same way.

**Comment by jtesser** [comment]
this is on purpose as the delete of the language that is parallel is archive. 

The delete is a convent way to destroy a piece of content.

**Comment by jtesser** [comment]
BTW this might change in 3.5 as we are targeting true content variants and content personaes
