### ISSUE TITLE
Bring in 3 Actionlet Plugins

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7394]
https://github.com/dotCMS/plugin-dotcms-actionlet-email
https://github.com/dotCMS/plugin-dotcms-actionlet-setvalue
https://github.com/dotCMS/plugin-dotcms-actionlet-pushnow

**Comment by oarrietadotcms** [comment]
Done, pull request: https://github.com/dotCMS/core/pull/7404

**Comment by DeanGonzalez** [comment]
All three sub actions added here: http://dotcms.com/docs/latest/managing-custom-workflow-schemes  Put the three new actions also on the 3.2 Table of Contents Doc
