### ISSUE TITLE
Workflow Tasks Pagination should only show 10 page results with . . .

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#7401]
Pagination should only show 10 pages of results then a next arrow or . . . for more results
It currently lists all pages. See screen shot
![screen shot 2015-03-04 at 9 49 49 am](https://cloud.githubusercontent.com/assets/1561349/6485806/465a3280-c254-11e4-9458-e3baf657f64e.png)

**Comment by oarrietadotcms** [comment]
Fixed: https://github.com/dotCMS/core/pull/7426
