### ISSUE TITLE
Move workflow action to top of page

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#7402]
Move the workflow controls/actions to the top of the page. See Screenshot
![screen shot 2015-03-04 at 10 03 02 am](https://cloud.githubusercontent.com/assets/1561349/6486017/edd8473a-c255-11e4-9004-070a281414c9.png)

**Comment by jkshapiro** [comment]
Won't this make this portlet inconsistent with other portlets, e.g. Content Search?

**Comment by oarrietadotcms** [comment]
Fixed: https://github.com/dotCMS/core/pull/7429

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-16 // H2 // FF
