### ISSUE TITLE
The integrity checker is not finding conflicts in new sites

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7405]
Right now the integrity checker is only finding conflicts over the demo.docms.com site.... If you create a new site and make a manual conflict, and finally run the integrity, the system is not finding conflicts 

To recreate: 
- Create a new site on both environments 
- Add a folder with a page in to it (this with the same names on both sides too)
- Run the integrity checker  

The system is not finding conflicts... I tested with a copy of demo and with a blank site and neither works....

Tested on nightly build 2015-03-03 // Postgres // FF

**Comment by jtesser** [comment]
@bryanboza but in this case the hosts are different. Are you sure both hosts have the same name? Maybe this is an issue but the hosts are different.

**Comment by bryanboza** [comment]
@jtesser... Yes, both host have the same name, seems the problem is that i was created the host manually in every side.... Maybe i need create the host on sender and push to receiver, this to have the same identifier on both sides... Maybe here we need a hots tab in the integrity checker....

**Comment by bryanboza** [comment]
I tested creating the host on sender and the pushing it... And works fine.... The problem is when you create manually the host on both sides...
