### ISSUE TITLE
Error trying to get the all sites templates list from a new side 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7406]
When you create a new site, and then try to create a new page, when you need select the template we have the option to see the all sites template list.... When you try to get this list, the system is showing a permissions error in the log....

LOG: https://gist.github.com/bryanboza/7b7c6dc323d8a4e3e9a4

To recreate: 
- Create a new host 
- Try to add a new page 
- In the template drop-down try to see all the sites template list 
- Check the log

Tested on nightly build 2015-03-03 // Postgres // FF

**Comment by oarrietadotcms** [comment]
Fixed: https://github.com/dotCMS/core/pull/7408
