### ISSUE TITLE
Site Search: Unable to search content in different languages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7414]
When you create a new site search index, this in a different language (E.g. Spanish), when you try to search for any contenten, the system is not finding consistences.... 

Then the site search is just working in the default language...

To recreate: 
- Create a new folder with a page in Spanish 
- Create a new site search index and run the job in spanish 
- Go to the search tab, in the site search portlet and try to search by name 

![2015-03-05_1159](https://cloud.githubusercontent.com/assets/2641437/6510977/44c20f8e-c32f-11e4-8a25-df0728a4ba30.png)

![2015-03-05_1201](https://cloud.githubusercontent.com/assets/2641437/6510997/5f46796c-c32f-11e4-8da9-d2c0c6864c91.png)

Tested on nightly build 2015-03-03 // Postgres // FF

**Comment by jtesser** [comment]
Is the uri and such magic even in spanish?

**Comment by bryanboza** [comment]
@jtesser Yes, and the index just have spanish content
