### ISSUE TITLE
Site Search: We need support multiple include or exclude commands

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7416]
We have problems when you try to include or exclude files from multiple paths, the system just is taking the first one.... In the documentation page we have examples with multiple transactions.
http://dotcms.com/docs/latest/SiteSearch

Example:  if you try to include the content from: /about-us/*, /services/investment-banking/*... The system only include the files from /about-us/....

**Comment by oarrietadotcms** [comment]
I tested this, several times and it works as the doc says. I noticed that @bryanboza  example is missing the "*" at the end: /about-us/*, /services/investment-banking/*
