### ISSUE TITLE
ElasticSearch not respecting DYNAMIC_CONTENT_PATH configuration

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7417]
In testing a specific configuration, I made this setting in the dotmarketing-config.properties file prior to starting the server:  DYNAMIC_CONTENT_PATH=/Users/brent/dotcms/builds/workplace/dotsecure

After starting the server, the following directories and files were created.
![image](https://cloud.githubusercontent.com/assets/3208956/6525857/7f2b6818-c3d0-11e4-81b5-9c6f01f66616.png)

All other files seem to be honoring the DYNAMIC_CONTENT_PATH setting:
![image](https://cloud.githubusercontent.com/assets/3208956/6525894/f34458f4-c3d0-11e4-8a19-baf4f72eaec4.png)

Issue was originally created on:
&nbsp;&nbsp;Windows 7 // Java (build 1.7.0_45-b18) // 3.0.1 Release // MSSQL 2012

Also reproduced on:
&nbsp;&nbsp;Mac OSX 10.9.5 // Java (build 1.7.0_71-b14) // 3.1 20150306 nightly build // H2

**Comment by jtesser** [comment]
you need to set the esdata properties for this

**Comment by wezell** [comment]
Is this documented anywhere?

**Comment by jtesser** [comment]
yes :-)  maybe not well but the es.data property has been the property forever to alter the location.  WAR doc, cluster doc etc... all refer to it. This is also where that property is mentioned.

**Comment by brentgriffin** [comment]
All fine and good - should consider moving this setting.  I was working with a single server and not looking in the cluster config property file at all.
