### ISSUE TITLE
Data of key/value field gets lost

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#7418]
Found a bug in the key/value field of content types (dotCMS 3.0.1).

To reproduce the bug, follow these steps:
* Add a new content type with
  * a text field
  * a key/value field
* Add a new content of that type
  * Add some key/value pairs to the key/value field
  * Click save/publish
* Edit this content again
  * Enter some text into the text field
  * Do not modify the key/value field
  * Click save/publish
* Edit this content again
  * All key/value data is lost!

**Comment by bryanboza** [comment]
Fixed, Not able to reproduce in the last nightly build
