### ISSUE TITLE
NPE creating html pages via restAPI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7419]
When you try to create a new page with the rest API we are having a NPE in the log.... The page was created, but we are logging the error...

``` ERROR rest.ContentResource: Cannot set COOKIES java.lang.NullPointerException ```

Here the curl command 
```
curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -H "Content-Type:application/json" -d '{
   stInode:"c541abb1-69b3-4bc5-8430-5e09e5239cc8",
   languageId:1,
   title:"Restful API page",
   friendlyname:"Restful API page",
   cachettl:"15",
   sortOrder:0,
   hostFolder:"48190c8c-42c4-46af-8d1a-0cd5db894797",  
   url:"restful-api-page",
   template:"fdb3f906-e9c4-46c4-b7e4-148201271d04"
}'
```

Tested on nightly build 2015-03-03 // Postgres // FF

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7497

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-23 // Postgres // FF
