### ISSUE TITLE
Display user readable message in the front-end when form does not exist anymore

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7420]
If you have a form in the front-end and then delete it from the back-end, the system displays a non-readable message in the front-end

Steps to reproduce:
1- Login with admin
2- Create a new page
2- Add a new form content type in Forms $ Polls > Forms. Add a new "Text" field
3- Go to the Edit mode and add the form you created to the new page. 
4- Now delete the form from the back end and open the page in Edit mode again
You will see the message:

--> $velutil.mergeTemplate('/static/content/content_form_macro.vtl')

Video capture: http://screencast.com/t/xxnwtkZa

No errors on logs.

Tested on:  3.1 Nightly build 2015-03-06 02:11 // Win7 Pro SP1// SQLServer 2012 // Chrome

**Comment by jkshapiro** [comment]
Deleting a form that is on a page should have the same effect as deleting a contentlet that is on a page: it silently disappears.
