### ISSUE TITLE
AceEditor Improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7421]
### Upgrade to latest version (has Velocity Highlighting)

- Add this to ES Search Portlet - It should be ace editor set to highlight JSON
- add to the widget code field
- set highlighting to velocity on: templates, containers, files that end int .vtl, other places that make sense).
- Add dropdown to select how the code wraps (Github Style)

### Make sure we have ACE editor in all this:

- ES Search : JSON
- Content Edit : Velocity 
- Template/Containers : Velocity
- Code Field: Velocity
- Editing Text File - based on file extension

**Comment by wezell** [comment]
I think we need to hide the vertical guide lines for the tabs and the end of line:

![screen shot 2016-04-26 at 11 48 01 am](https://cloud.githubusercontent.com/assets/934364/14824739/0b967b40-0ba5-11e6-9883-9a729a07049a.png)

**Comment by fmontes** [comment]
But but... whyyyyyy? gives more order to the code.

**Comment by fishsmith** [comment]
yes why?

On Tue, Apr 26, 2016 at 12:10 PM, Freddy Montes <notifications@github.com>
wrote:

> But but... whyyyyyy? gives more order to the code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7421#issuecomment-214796943>
>



-- 

3059 Grand Avenue
Suite 410-B
Miami, FL 33133
Main: 305-900-2001 | Direct: 305.209.8104

jason@dotcms.com | dotcms.com <http://www.dotcms.com>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by bryanboza** [comment]
Fixed, tested everyone of the numbered sections and we have the version 1.2.3 in all of those... tested on master-3.5
