### ISSUE TITLE
Time machine not found the files when you try to create a snapshot in spanish

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7423]
When you create a time machine snapshot and set English and Spanish in the language, the system is creating the snapshot without problem, but when you try to load this on Spanish, we are showing an error 

![2015-03-06_1116](https://cloud.githubusercontent.com/assets/2641437/6529929/3a9dd812-c3f2-11e4-980b-f9f8354b9abb.png)

I have the 3 new variables in the dotmarketing-confi.properties file in true...
DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=true
DEFAULT_WIDGET_TO_DEFAULT_LANGUAGE=true
DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true

Tested on nightly build 2015-03-03 // Postgres // FF

**Comment by bryanboza** [comment]
Not sure if this is on purpose because the main page don't have Spanish version, but works different to previous releases...

**Comment by jtesser** [comment]
yes I think this is on purpose but maybe we can readdress this in the future
