### ISSUE TITLE
Allow an ES query to return both hits and facets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7427]
This is important when trying to use the tool to render a page- often, you will need to get both the query hits and the facet results in the same request - otherwise, you need to make one or more requests for data that should only take a single trip.

We are currently limiting this in code and I can't see a reason to do that.
Real world use case: we are running into this very problem on the starter using geolocation.

**Comment by wezell** [comment]
Here is the test query:
```
{
	"sort": [
		{
			"_geo_distance": {
				"news.latlong": {
					"lat": 42.6262237,
					"lon": -71.1571195
				},
				"order": "asc",
				"unit": "km"
			}
		}
	],
	"query": {
		"filtered": {
			"query": {
				"bool": {
					"must": {
						"term": {
							"structureName": "news"
						}
					}
				}
			},
			"filter": {
				"geo_distance": {
					"distance": "1000km",
					"news.latlong": {
						"lat": 42.6262237,
						"lon": -71.1571195
					}
				}
			}
		}
	},
	"size": 999,
	"facets" : {
        "tags" : { "terms" : {"field" : "news.tags"} }
    }
}
```

**Comment by jtesser** [comment]
fixing in https://github.com/dotCMS/core/issues/7397
