### ISSUE TITLE
Data Export causes problems on Oracle when ordering is done only on non-unique fields

### ISSUE THREAD

**Issue by litked** [dotCMS/core#7428]
Data Export causes problems on Oracle when sql query orders entries only by non-unique fields.
The problem occurs by more then 1000 entries in the 'Identifier' table with many entries with identical parent_path:

``` java
int step = 1000;
//...
for(i=0;i < 10000000;i=i+step){
//...
    _dh.setMaxResults(step);
//...
    } else if(Identifier.class.equals(clazz)){
        //THIS ORDERING IS NOT ENOUGHT
        _dh.setQuery("from " + clazz.getName() + " order by parent_path");
//...
```

This works:

``` java
        _dh.setQuery("from " + clazz.getName() + " order by parent_path, id");
```

in classes:
\src\com\dotmarketing\portlets\cmsmaintenance\ajax\CMSMaintenanceAjax.java
and
\src\com\dotmarketing\portlets\cmsmaintenance\action\ViewCMSMaintenanceAction.java

**Comment by jtesser** [comment]
For backup and restore we would recommend is a manual backup/restore http://dotcms.com/docs/latest/BackupAndRestore

In general this tool is for smaller sites. We will address but just trying top help you backup/restore properly
