### ISSUE TITLE
Changing menu order on browser does not change the order

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7431]
This does not seem to work on "Pages as content"

![screen shot 2015-03-09 at 2 36 24 pm](https://cloud.githubusercontent.com/assets/934364/6561727/d4b5551e-c669-11e4-9e6c-6b24a168ea81.png)

**Comment by oarrietadotcms** [comment]
Fixed: https://github.com/dotCMS/core/pull/7432

**Comment by bryanboza** [comment]
Tested on nightly build 2015-03-12 // Postgres // FF
