### ISSUE TITLE
Don't force the use of JSESSIONID for binary/file content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7433]
Recurring issue that seems to come back from time to time.  Having a cookie set on a file/asset can prevent the asset from being cached. 

Whenever we do request.getSession in a filter or servlet, we need to do a request.getSession(false) and test if a session already exists.  If not, we should not use it and instead use the defaults.  Obviously, there are places in code where we need a session and that is ok, but for static files/assets, we do not need them by default.

Below, you can see that curl-ing for a static file sets a session cookie,  It should not.
```
cabbage:dotcms3 will$ curl --head http://127.0.0.1:8080/application/themes/quest/_bower_components/jquery/jquery.min.js
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=D8070A98E9ECBB6E0E15196314360C58; Path=/; HttpOnly
Expires: Tue, 08 Mar 2016 20:52:10 +0000
Cache-Control: public, max-age=31536000
Last-Modified: Fri, 06 Mar 2015 14:05:07 +0000
ETag: dot:f6fa6b13-3a96-4cbf-9a75-19a40137f05a:1425650707000:92629
Content-Type: application/javascript;charset=ISO-8859-1
Content-Length: 92629
Date: Mon, 09 Mar 2015 19:52:10 GMT
```

**Comment by jtesser** [comment]
Yes we have solved the request.getSession(false)  issue in other places.   Like you said creeps up from time to time. :s
