### ISSUE TITLE
Filtering event by tag is not working

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7434]
When you filter an event by tag, it doesn't find it.

To reproduce:
1- Login with admin
2- Navigate to Calendar > Add a single or recurrent Event
3- Add a tag and save/publish it
4- Now filter by tag. System is not showing any result

Video capture: http://screencast.com/t/6NDOcmz5nGjH

Log:
[09/03/15 13:56:02:661 CST] ERROR ajax.TagAjax: identifier is null

Tested on:  3.1 Nightly build 2015-03-06 20:01 // Win7 Pro SP1//  SQLServer 2012 //  Chrome

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13883

**Comment by nollymar** [comment]
It's also filtering by title and description

**Comment by shaydotcms** [comment]
Passed QA

Filter by tag is showing the event properly.
![image](https://user-images.githubusercontent.com/8741846/37546271-a9342a7c-2931-11e8-84c2-eecbb56c90f4.png)

Tested on master branch / Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
