### ISSUE TITLE
Not able to access back-end in 3.2

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#7436]
When you try to access back-end on Linux it throws a 500 error. The front-end loads fine

Catalina.out and localhost.log https://gist.github.com/erickgonzalez/8165a8cb4edd4fc3222a

Reproduced on Ubuntu 14.04//H2 and MySQL

**Comment by oarrietadotcms** [comment]
PR for License: https://github.com/dotCMS/license/pull/17
PR for EE: https://github.com/dotCMS/enterprise-2.x/pull/268
PR for Core: https://github.com/dotCMS/core/pull/7488

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // Postgres // FF
