### ISSUE TITLE
Inserted image is not showing in calendar event

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7438]
Inserted image is not showing in calendar event. This happens for any type of image (png, gif, jpeg, jpg) or size

To reproduce:
1- Login with admin
2- Navigate to Calendar > Add a single or recurrent Event
3- Upload an image in the back-end
4- Add the image you uploaded to "Image" field and save/publish the event
5- In the front-end go to News&Event > Events
6- Locate the date of the event you created and click to open it. The system will not show you the image you added

Logs: https://gist.github.com/anonymous/cb0a54fa4948db1ba7ea

Tested on:  3.1 Nightly build 2015-03-09 20:54 // Win7 Pro SP1//  SQLServer 2012 // Chrome

**Comment by jtesser** [comment]
@fishsmith this is a starter issue with resizing the image

**Comment by fishsmith** [comment]
@jtesser I believe we fixed this awhile ago in the new starter.

Below example has both a image in the field and the WYSIWYG

http://starter.dotcms.com:8080/news-events/events/dotcms-online-training-session-w-image?id=9f303322-a908-4df0-8194-e1323f11b008&language_id=1

**Comment by jtesser** [comment]
@shayngr should be solved when we commit a new starter soon
