### ISSUE TITLE
Symbol вЂ‹ in the end of the file

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7439]
Problem is actual for versions under 3.0

Open any file, for example vtl, for editing in admin screen, copy all content to local file.
Make some changes in local file (optionally).
If you copy this file to the server using webdav you will see white line in the bottom of page where this file is used.
If you are using any tool, for example WinWerge, you will see this 
![image](https://cloud.githubusercontent.com/assets/2236103/6580724/7e1aeaac-c763-11e4-85af-762b58107715.png)

If you open and save this file using admin screen, this strange symbol dissapears.

**Comment by jtesser** [comment]
so this works in 3.x you are saying?

**Comment by grinev** [comment]
Yes, I've tried to reproduce it on version 3.0.1 and it works.
I reproduce it on version 2.5.4

**Comment by jtesser** [comment]
Ya I thought so. I believe in the later 2.5 series this is fixed and is now working.
