### ISSUE TITLE
NavResult isActive is resulting in false positives.

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#7443]
NavResult.isActive is returning true when it shouldn't.

Example: If the requestUri='/loans/personal-loans.html' the paths like '/personal' should not match though '/loans' should. Currently a path of '/personal' would return true though it should not.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-13 // Postgres // FF

**Comment by jorith88** [comment]
isActive still returns false positives in 3.2.3 because of `req.getRequestURI().startsWith(href)`

When the requestURI is '/documentation/sdk/javascript', the method returns true for a page on path '/documentation/sdk/java'.
