### ISSUE TITLE
System only exports top level categories but not subcategories

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7448]
When you export categories, the .csv file only contains the top level categories but not the subcategories so when you import the .csv you don’t get the child categories into the system.

To reproduce:
1- Login with admin
2- Create a top category and subcategories: Content Types > Categories > Add
3- Export the categories
4- Delete all top level categories along with their subcategories.
5- Import the categories again
You will see it only shows the parents categories but not the child categories.
This is broken in previous version too (i.e. demo.dotcms.com)

No errors on logs

Tested on:  3.1 Nightly build 2015-03-10 22:51 // Win7 Pro SP1//  SQLServer 2012 // Chrome

**Comment by bryanboza** [comment]
Here also the replace functionality is not working, because after export the categories and then try to import using the replace option... After import we have a duplicate categories
