### ISSUE TITLE
Unable to create new communications 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7449]
We have an error in console when you try to create a new communication, by this, the portlet never loads.... Then you can't create communications

Here the errors:
- ReferenceError: tinyMCE_GZ is not defined   -======>>   layout?...md=edit (line 1985, col 1)
- TypeError: i is undefined

To recreate: 
- Create a new custom tab
- Add Mailing list, communications, and campaigns 
- Go to communications portlet and try to add a new one 

Tested on nightly build 2015-03-03 // H2 // FF

**Comment by rogelio-blanco** [comment]
Before closing this one, remember to test issue #7632
