### ISSUE TITLE
remove the getSQLResults from DotCMSMacroWebAPI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7451]
This needs to be its own viewtool.

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/viewtools/DotCMSMacroWebAPI.java#L315

**Comment by jtesser** [comment]
so the new view tool was added here for 3.1 https://github.com/dotCMS/core/issues/7453

in 3.5 we want to remove the old method

**Comment by DeanGonzalez** [comment]
http://dotcms.com/docs/latest/executing-a-sql-query - old one deprecated
