### ISSUE TITLE
EE Query fixes

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7452]
2 things

1. Fully remove the post filter
2. Add an attribute to the SearchResult object that has the rewrittenQuery this will help us to debug if there is a problem.

**Comment by jtesser** [comment]
https://github.com/dotCMS/enterprise-2.x/blob/70b690354a6b66be4f3cd1a155c3dfe8ee4d5920/src/com/dotcms/enterprise/priv/ESSearchProxy.java#L99

**Comment by bryanboza** [comment]
fixed, Now the ES Search respect permissions, Tested on nightly build 2015-03-12 // Postgres // FF
