### ISSUE TITLE
New SQLViewtool and depreciate the old one

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7453]
bring the whole viewtool here https://github.com/joseorsini/SQLResultsTool

map to $sql

in code depreciate the old method in DotCMSMacroWebAPI.java

**Comment by jgambarios** [comment]
Notes for QA:

In order to test enable this property in the **dotmarketing-config** file:
```
ALLOW_VELOCITY_SQL_ACCESS_TO_DOTCMS_DB=true
```

And add this velocity code in any content:
```
<h3>Calling getSQLResults Tool from a Content:</h3>
<p>
<br /> Query: select * from identifier <br /><br /> 
  #set($query = "select * from identifier") 
  #set($resultsList = $sql.getSQLResults("default", "$!{query}", 0, 4)) Results: $resultsList
</p>
```

**Comment by jgambarios** [comment]
Also we may want to move the documentation found here https://github.com/joseorsini/SQLResultsTool to our docs.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-13 // Postgres // FF

**Comment by DeanGonzalez** [comment]
http://dotcms.com/docs/latest/executing-a-sql-query - old one deprecated
