### ISSUE TITLE
remove SOLR jar

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#7454]
We are currently in the process of upgrading our SOLR plugin to adapt it to dotCMS 3.1 and also make it compatible with SOLR 5.0.

dotCMS includes the SOLR jar corresponding to their 1.4 implementation. We can still include the new jar in the plugin and force the plugin to use that one instead of the one in dotCMS.

If I'm not wrong, dotCMS doesn't really need the SOLR jar at all. It's only an unnecessary component that was copied over when the SOLR queue manager portlet was reused to implement the Push Publishing queue manager.

This request is related to #2884

**Comment by jtesser** [comment]
right of course with an OSGi plugin you can provide your own solr and in our it is repackaged so you can provide your own even from a static plugin

**Comment by joseorsini** [comment]
FYI

http://mvnrepository.com/artifact/org.apache.solr
