### ISSUE TITLE
Need a better handle on this push exception 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7462]
If you create a new page in english on sender, and create a new one with the same name on receiver, but here in spanish.... The integrity checker is not founding conflicts because are different languages, but when you try to push the english page we have a hibernate exception...

Log: https://gist.github.com/bryanboza/eca7b9132fd0c0523d36 

To recreate: 
- Create a new folder with the same name in both sides (sender and receiver)
- Create a new page in english on sender 
- Create a page with the same name but in spanish on receiver 
- Run the integrity checker 
- Try to push the english page to the sender side 

The integrity is not founding conflicts because are different languages, but we have the error.... Maybe here we can manage this exception or show a better error message 

Tested on nightly build 2015-03-11 // Oracle // FF

**Comment by jtesser** [comment]
We need to make the integrity checker handle this and improve messaging
