### ISSUE TITLE
Can't create html pages using templates from other sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7469]
Related to #7406 

After this fix now we can get the list without errors, but when you set any template to the page, the UI of the page is crashed... Seems we are not loading the CSS 

To recreate:
- Create a new host
- Try to add a new page
- In the template drop-down try to see all the sites templates
- Set anyone and create the page
- Look the IU 

SC: http://screencast.com/t/RjXKLsTqsl

Tested on nightly build 2015-03-12 // Postgres // FF

**Comment by jtesser** [comment]
this might be correct

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // H2 // FF
