### ISSUE TITLE
We have two ROOT folders in to the webapps folder

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7471]
When you start the system, in to the webapps folder, the system is crating a new ROOTdotsecure folder... 

![2015-03-16_1211](https://cloud.githubusercontent.com/assets/2641437/6672995/96dd3a4c-cbd5-11e4-9133-87b9d9a7caa7.png)

Tested on nightly build 2015-03-13 // Postgres // FF

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7492

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // Postgres // FF
