### ISSUE TITLE
The system is not showing special UTF8 Characters in the site browser names

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7473]
Related to #7464 

If you add special UTF8 characters in any page name, when the system redirect the system show fine this in the URL, but when you come back to the site browser, the system remplace the characters by "???" and not show the real name....
SC: http://screencast.com/t/0HkLTS4i

NO have errors in the log, neither console 

Tested on nightly build 2015-03-13 // MySQL // FF

**Comment by bryanboza** [comment]
FYI:  If you try to open the URL manually works fine, the problem is showing the name... The database have the UTF8 default collation....

**Comment by oarrietadotcms** [comment]
I see the characters just fine in my local, also using MySQL:

![screen shot 2015-03-16 at 2 15 11 pm](https://cloud.githubusercontent.com/assets/8225685/6675562/e77ba752-cbe6-11e4-88df-684a1e19acfb.png)
