### ISSUE TITLE
Feature Request: Option to Disable Code Highlighting

### ISSUE THREAD

**Issue by ryan-ethode** [dotCMS/core#7475]
On larger files (like some long CSS files, for example), the editor really bogs down trying to analyze and highlight all of the code. Sometimes my browser will lock up for a few minutes trying to highlight the whole file. I would love to have the ability to disable code highlighting on a user by user basis.

**Comment by wezell** [comment]
is this true on the 3 series?  We switched to the ACE editor.

**Comment by ryan-ethode** [comment]
I've been working through 2.x sites so far, so I'm not sure about the editor on 3.x.

**Comment by jtesser** [comment]
@ryan-ethode check out 3.x as I think it will work much better for you
