### ISSUE TITLE
The value for the Url on Pages as content should ONLY be stored in Identifier

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7476]
@jgambarios as we discussed altering this on a second langauge shows wrong in the BACKEND UI but on the frontend it addresses properly

**Comment by jtesser** [comment]
@jgambarios as we discussed consider the mapping, site browser, XMLSite Map, Time Machine, Site Search make sure all works

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // Postgres // FF
