### ISSUE TITLE
Cleanup the old StructureType

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7477]
Change nomenclature of the old structure "Type" to "Base Type"
1. Need to change the below screenshot
   ![image](https://cloud.githubusercontent.com/assets/1486445/6710085/a8cdd36c-cd54-11e4-94d9-75dc4d0d2fa9.png)
2. Need to add a new mapping the mapping. https://github.com/dotCMS/core/blob/master-3.2/src/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java#L277
3. Update the contentSearch manager to use the name mapping name baseType in the queries we write and use as help

**Comment by wezell** [comment]
![screen shot 2015-03-18 at 9 56 46 am](https://cloud.githubusercontent.com/assets/934364/6710165/374a0e80-cd55-11e4-8ab7-37a8a246ad6f.png)
