### ISSUE TITLE
Use Rulesets to restrict backend access

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7485]
Many clients require custom http proxy or load balancer configuration to manage access restrictions to the Dotcms backend. This is difficult to manage, and non-transparent to the CMS Administrator. The new Rules/Personas framework should provide a much better way to accommodate this need.

Proposed solution example:

Two Rulesets is defined as follows:

> - **Name:** Secure connection from on-site
>   **Rules** (boolean AND'ed):
>   - request.clientaddress ipmatch 10.0.0.0/8
>   - request.scheme equals https
> - **Name:** Secure connection from support
>   **Rules** (boolean AND'ed):
>   - request.clientaddress ipmatch 123.45.67.98/32
>   - request.scheme equals https

On backend "System"->"Configuration"->"Backend Access" tab, something like the following:

> [checkbox] "Enable backend access restrictions" (this can be overridden with a dotmarketing-config.properties value in case you lock yourself out)
> 
> "Require one of the following Rulesets for backend access" ("one of", not AND'ed):
> - [checkbox] "Secure connection from on-site"
> - [checkbox] "Secure connection from support"
> - [checkbox] "Some other ruleset only used for content delivery"

**Comment by chrismccracken** [comment]
When enabled, the Rulesets and access restrictions are checked on every backend page load, same as User/Roles/Permissions.

**Comment by jtesser** [comment]
@dsilvam @ggranum thinking of a possible use case for the Rules Engine.
