### ISSUE TITLE
dotPageContent does not work the same in edit mode and in live mode.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7490]
The $dotPageContent should provide a user a handle on the Content object of their page.  In live mode, this works, and you get back the ContentMap object, which is right:

![screen shot 2015-03-20 at 9 31 49 am](https://cloud.githubusercontent.com/assets/934364/6752335/f884de88-cee3-11e4-96b7-36f47a5576bd.png)

In Edit and Preview Mode, we are only sending in the model.Contentlet object, which does not provide all the richness of the ContentMap.

![screen shot 2015-03-20 at 9 33 22 am](https://cloud.githubusercontent.com/assets/934364/6752360/315c58b2-cee4-11e4-96ae-33c0787034c6.png)

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-20 // H2 // FF
