### ISSUE TITLE
Relationships Not Working As It Should

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#7494]
When you create a relationship and apply it to a content, it saves successfully but once you enter again into the content the relationship disappeared (it's still present on the DB).

Steps to reproduce:
1- Create a Relationship e.g. Blog-Content(Generic)
2- Create a Blog content
3- Create a Content(Generic) contentlet
4- Relate those two and save and publish.
5- Enter once again to that content and go to the Relationships tab.

FWIW: I reverted the changes that were committed here https://github.com/dotCMS/core/issues/7269 and start working again.

Tested on Master-3.2//H2 and MySQL

**Comment by jtesser** [comment]
great catch erick.  Unit tests yay!!!

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7502

The changes in https://github.com/dotCMS/core/pull/7370/files#diff-702c767ceea7d905aade13f8e5058a15L277 tried to change "structureType" to only "type" in ES mapping. But "type" was already in use for other purposes in the code (more than 25 times). 

I used "baseType" instead proposed in https://github.com/dotCMS/core/issues/7477

@DeanGonzalez this will need documentation

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-24 // Postgres // FF

**Comment by DeanGonzalez** [comment]
Added on content search syntax doc and searched for all doc with the old syntax and replaced where appropriate.
