### ISSUE TITLE
Full reindex does not properly set es replicas w/ autowire

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7495]
Tested and reproduced on 3.0.1. 2-node cluster w/ autowire, only cluster config is as follows:

plugins/com.dotcms.config/conf/dotcms-config-cluster-ext.properties:
> es.path.data=/opt/dotcms/data/dotsecure/esdata
> es.path.work=/opt/dotcms/data/dotsecure/esdata/work

plugins/com.dotcms.config/conf/dotmarketing-config-ext.properties
> ASSET_REAL_PATH=/opt/dotcms/shared/assets
> DYNAMIC_CONTENT_PATH=/opt/dotcms/data/dotsecure

Both servers online, and licensed correctly via license pack.  When running a full reindex (content, not sitesearch although it might also be affected?), the index is created but the replicas are not properly updated after reindexing (should be 1 replica for 2-node cluster). It places the live index on one server, and the working index on the other.

> **dotcms-cluster-02-cms1$** du -sh /opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/*
> 14M /opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/live_20150320190714
> 4.0K	 /opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/working_20150320190714

> **dotcms-cluster-02-cms2$** du -sh /opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/*
> 4.0K	/opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/live_20150320190714
> 13M	/opt/dotcms/data/dotsecure/esdata/dotCMSContentIndex_3x/nodes/0/indices/working_20150320190714

Log entries as https://gist.github.com/chrismccracken/73d03a1b67f32a45ce93. 

Cluster status: http://i.imgur.com/5mhLfcL.png
Index status: http://i.imgur.com/xASuQ3n.png

Following a restart of one server node, the replicas are updated properly.
Log: https://gist.github.com/chrismccracken/64c35be0f0b0fa3ad317
Index status: http://i.imgur.com/b3Kmo5U.png

**Comment by oarrietadotcms** [comment]
@chrismccracken the property es.index.number_of_replicas is 0 or 1 in your configuration?

**Comment by chrismccracken** [comment]
@oarrietadotcms  It is unset, using default shipping config & autowire only.

**Comment by oarrietadotcms** [comment]
License PR: https://github.com/dotCMS/license/pull/18
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/269
Core PR: https://github.com/dotCMS/core/pull/7509

**Comment by bryanboza** [comment]
Ficed, tested on nightly build 2015-03-27 // Postgres // FF
