### ISSUE TITLE
Enhancement: Use language names instead of flags on login screen

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7498]
Using flags to represent language is a bad idea (see, e.g., http://flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/). DotCMS has wisely made changes within the back end in recent versions; however, the login screen has not been included in those initiatives. It should be.

I spoke recently with one user who saw the American flag on that screen but had no idea that it represented English--they thought it simply meant "made in the USA".

**Comment by dotcmsCodeReview** [comment]
+1 - good point and good anecdote Kivi.

On Mon, Mar 23, 2015 at 9:35 AM, Kivi Shapiro <notifications@github.com>
wrote:

> Using flags to represent language is a bad idea (see, e.g.,
> http://flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/).
> DotCMS has wisely made changes within the back end in recent versions;
> however, the login screen has not been included in those initiatives. It
> should be.
>
> I spoke recently with one user who saw the American flag on that screen
> but had no idea that it represented English--they thought it simply meant
> "made in the USA".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7498>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>
