### ISSUE TITLE
Legacy Files Permissions problem in version 3.1

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7505]
After migratiion from 2.5.4 to 3.1 we have a problem: some resource files (js, css) returns 403 error if you are not logged in cms. After small research we realized that cms returns 403 for legacy files (not File assets). Is it a normal behavior?

In previous versions it works fine, you don't need to be logged in to see files. We have a lot of legacy files resources. Is there an easy way to convert them to file assets? I didn't find any tool in dotcms.

**Comment by jgambarios** [comment]
@grinev Please submit your questions to our google group (https://groups.google.com/forum/?hl=en#!forum/dotcms), the community is very active in that group and we can help you there.

**Comment by grinev** [comment]
done https://groups.google.com/forum/?hl=en#!topic/dotcms/qzmRsza37eg
