### ISSUE TITLE
Dotcms - Image dimensions distorted when one adds an article image using the image tab

### ISSUE THREAD

**Issue by gtaku89f11** [dotCMS/core#7506]
Article image added using the article image tab in dotCMS article content editor causes the image dimension to not maintain correct aspect ratio, thereby causing the image to appear distorted when view on the live page.

**Comment by jgambarios** [comment]
@gtaku89f11 Can you provide more information and reproducible steps?, this could be a css issue or maybe when requesting the image specifics heights and widths are been set which would affect the aspect ratio of that image.

**Comment by gtaku89f11** [comment]
@jgambarios Sure. 
When in DotCMS admin frontend in 2.2 or 2.5.x, do the following steps
> Click on the "Content" tab
> In the "Type" dropdown, select "Article"
> Click on "Add New Article"
> In the screen that opens, under the "Content" tab, Enter text for "Host Folder", "Headline", and "Body Text"
> Click the "Image" tab and browse and add "Aside Image"
> Save and publish
> Now browse the page for this newly added article and observe the image.

**Comment by jgambarios** [comment]
Unable to reproduce in our latest version, if you are able to reproduce in http://demo.dotcms.com please let us know.

**Comment by gtaku89f11** [comment]
Looking at you demo.dotcms.com, I saw that that there wasn't any article content type. That's when I realized that the article content type is our creation. I was then able to look for the piece of vtl code that was responsibly for the behavior that resized the images disproportionally. I fixed the issue. 
Thanks.
