### ISSUE TITLE
Custom Error Pages not working

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7508]
Follow up of https://groups.google.com/forum/?hl=en#!topic/dotcms/_MxKxPAIzmo

Custom Error pages are not working on latest 3.2, the Vanity URLs are working properly, for what I saw the problem is the jsp (https://github.com/dotCMS/core/tree/master-3.2/dotCMS/portal) error pages are not resolving properly.

**Comment by jgambarios** [comment]
As reference http://dotcms.com/docs/latest/CustomErrorPages

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7515

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-27 // MSSQL // FF
