### ISSUE TITLE
Minor Enhancement: Enforce data integrity between Push Publishing tables

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7510]
As of 3.1 and actual master-3.2, a foreign key between publishing_environment and publishing_end_point is missing. If a Push Publishing Endpoint is created, it refers to a single environment, however, at database level, no foreign key is enforcing this relationship between these columns

publishing_end_point.group_id -> publishing_environment.id

**Comment by levosgien** [comment]
See: https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/307
