### ISSUE TITLE
Error loading legacy files in Site Browser Menu.

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7511]
After migration from 2.5.4 to 3.1 we have a problem: some folders in Site Browser Menu does not loading any files. Ajax to /dwr/call/plaincall/BrowserAjax.openFolderContent.dwr returns NullPointerException. It happens when there are any legacy file in directory. 
Exception is throwed at line 440 of com.dotmarketing.viewtools.BrowserAPI

``` 
if (skip || wfdata.skip) {
``` 

wfdata is null because at line 411 file not instance of Contentlet. File is com.dotmarketing.portlets.files.model.File which mean this is legacy file in dotcms.

I've add one more condition
```
if (skip || (wfdata != null && wfdata.skip)) {
```
and it works fine. Site Browser menu shows list of files with legacy files and they are available for view and edit.

Also there are one more problem with legacy files in dotcms 3.1: https://github.com/dotCMS/core/issues/7505

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-07 // MSSQL // FF
