### ISSUE TITLE
Refactor ContentletAPI.delete methods to destroy

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7512]
Destroy should do what the current delete method does, which is nuke the content in all its language versions.

The new Delete method should only delete only the language of the contentlet passed in, unless it is the last contentlet/lang of its identifier, at which point call the destroy method.

- destroy method does not care if a content is archived or not
- delete will throw an error (DotStateException) if the content that passed in is not in the archived state.

**Comment by jtesser** [comment]
also fix the validateUser Issue

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8986

This issue requires thorough testing to make sure that the contentlet versions are deleted correctly. @bryanboza, @jgambarios please let me know if there are issues or concerns.

**Comment by bryanboza** [comment]
Some new issues opened... This needs work

**Comment by jgambarios** [comment]
Merged in master-3.6 ( https://github.com/dotCMS/core/commit/7577900e64241a4f31bdc3d2f2dee94eefc7bae5 )

**Comment by jgambarios** [comment]
Closed the original issue as the main work is done and new tickets related to these changes were created.
