### ISSUE TITLE
Unable to upgrade from 1.9 to 3.0 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7514]
Related to #5989 

I tested this migration some time ago and was working fine, but making the same process now we have some errors on log and have the error 500 when you try lo login in the server 

Steps to reproduce:
--> In a dotcms 1.9 instance
1- Start up and apply the license to the distribution 
2- Upload some images, create a new structure, add some content to this structure
3- Shut down the server
--> In a 3.0 nightly build 
4- Copy the assets folder from the 1.9 instance 
5- Configure to use the same database that the older version
6-Copy the page.extension.config.zip plugin in your plugin directory
7- Deploy the plugins
8- Start the server
9- Make a full reindex

Here the complete log: https://gist.github.com/bryanboza/671345ced9370ba13ecd

Tested with MySQL and Postgres and is not working for me...

**Comment by jtesser** [comment]
@bryanboza this looks like you are not connecting to the DB properly on the upgrade. Something is wrong with the process. Lets have one of the devs sit with you.  I will talk to @brentgriffin when he is back

**Comment by jtesser** [comment]
@bryanboza you only provided the log for your 1.9 install.   We need the upgrade log
