### ISSUE TITLE
Enhancement: Copy and paste page should copy and paste content

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7517]
To reproduce:
1. In Site Browser, right-click an HTML Page, and copy.
2. Right-click on a different folder, and paste.
3. Open the new page. It does not contain any content.

**Comment by dotcmsCodeReview** [comment]
I am pretty sure copy and pasting has always worked like that.  Cut and
paste will move the page and the content.

**Comment by jkshapiro** [comment]
Hm. If so, let's relabel this as an enhancement. I would expect if I copied and pasted a page that the content would come with it.
