### ISSUE TITLE
Bug: Cannot cut and paste pages into root folder

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7518]
To reproduce:
1 In Site Browser, right-click an HTML Page, and cut.
2. Right-click on the root folder, and paste.
3. The file is not moved.

**Comment by oarrietadotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/7536

**Comment by oarrietadotcms** [comment]
This is not ready yet, I found a bug in the code.

**Comment by oarrietadotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/7538

Ready.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-02 // MSSQL // FF
