### ISSUE TITLE
Permissions issue with the limited users 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7520]
Related to #7447 

We have two possible issues when you try to lock for editing the new html pages... 

To recreate: 
- Add a new folder and add a new page in to it 
- Add new content to the page 
- Add individual permissions to the folder and add edit permissions to "Chris Publisher"
- Login as Chris Publisher and click the folder 
![2015-03-26_0918](https://cloud.githubusercontent.com/assets/2641437/6849503/37f25e4c-d399-11e4-86c3-690072108f1e.png)

1- The first time you login as limited, you can't see the page in to the folder, no errors in log... If you come back to "Admin", lock and unlock the page and login as "Chris" again, now you can see the page 

2- If you as "Chris" try to lock the page for editing, we have the follow error on log.... 
https://gist.github.com/anonymous/628d77841a9df6b16a94

Tested on nightly build 2015-03-24 // Postgres // FF

**Comment by oarrietadotcms** [comment]
I can reproduce the firs error. FWIW is also in 3.1.

Error 2 I can not reproduce in my env (only occurs in Bryan's), I will sit with Bryan tomorrow to see if he can reproduce in my local.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7545

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-02 // MSSQL // FF
