### ISSUE TITLE
Content tab - content items are not clickable links with a single language

### ISSUE THREAD

**Issue by spq2** [dotCMS/core#7522]
DotCMS 3.1

When only one language is used (for example, the default language is overriden in dotmarketing-config.properties), then items in the 'Content' tab do not highlight as blue links and are not clickable.

Secondary context menu still works, so it's possible to edit content by right-clicking and selecting 'Edit'. 

Adding a second language in the CMS 'Languages' area fixes the issue (even without content in that language) and rows become clickable again.

**Comment by oarrietadotcms** [comment]
I think this is duplicated: https://github.com/dotCMS/core/issues/7516
