### ISSUE TITLE
Events content form errors if textarea field is present

### ISSUE THREAD

**Issue by spq2** [dotCMS/core#7523]
DotCMS 3.1 

If the built-in 'Events' content type has a Textarea field added to it (default options for required/indexed), then an error is produced when clicking the 'Add New Content' on the 'Content' tab with the Event content-type selected. 

The same error displays when trying to edit existing content, if the textarea field is present.

If the Textarea field is removed then the form will display and content is editable again.

**Comment by jgambarios** [comment]
QA was unable to reproduce the issue in 3.2 and 3.1 versions, please let us know if you are able to reproduce in our http://demo.dotcms.com

**Comment by spq2** [comment]
Reproduced the error on the demo site. 

1. Add a Textarea field to the Event content-type
2. Click on Content tab
3. Click 'Add new content' button
4. Error displays 'Ooops, sorry. This has caused a problem'

**Comment by shayngr** [comment]
Performed test again and was able to reproduce issue adding Textarea field.
Tested on demo.dotcms.com & 3.2 Nightly build 2015-03-26 14:16

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59162
