### ISSUE TITLE
Unable to create past time machine snapshots

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7525]
When you try to create a past time machine snapshot we have a lot of errors on log.... And the snapshot is not created.. 

Here the log error:
https://gist.github.com/anonymous/bc97455f21c69c8913e7

![2015-03-26_1140](https://cloud.githubusercontent.com/assets/2641437/6852864/fcf79988-d3ac-11e4-948b-5f0945440ddc.png)

Tested on nightly build 2015-03-24 // Postgres // FF // Linux // Java8

**Comment by oarrietadotcms** [comment]
FYI: https://jira.codehaus.org/browse/XSTR-761

**Comment by oarrietadotcms** [comment]
dotcms-libs PR: https://github.com/dotCMS/dotcms-libs/pull/24

**Comment by oarrietadotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/7532
