### ISSUE TITLE
Push publish is not working  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7526]
When you try to push any content we have the follow errors on logs..
https://gist.github.com/bryanboza/41be3b4dd300aa59e121

To recreate:
- Configure your push environment
- Create a new folder and page 
- Try to push the page 

Sender: Linux // Postgres // FF // Java8
Receiver: OSX // Postgres // Chrome // Java8

**Comment by oarrietadotcms** [comment]
FYI: https://jira.codehaus.org/browse/XSTR-761

**Comment by oarrietadotcms** [comment]
dotcms-libs PR: https://github.com/dotCMS/dotcms-libs/pull/24

**Comment by oarrietadotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/7532
