### ISSUE TITLE
Enhancement: Make edit mode for pages similar to edit mode for other contentlets

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7527]
For most contentlets, when you view them in the back end they are shown with textboxes, dropdown lists, etc. If you try to edit them, the screen flashes but then if you try to edit them again you can. However in all cases the changes won't "take" until you lock the contentlet for editing (which also changes the buttons available).

For consistency and predictability, pages should work the same way. Instead of textboxes and dropdown lists, though, there would be "Add content" buttons and such, just like when you're editing them.

**Comment by jkshapiro** [comment]
The alternative would be to make all the other contents work like pages--give a "view only" presentation (e.g. no dropdown lists, just show the selected value) until the user locks them for editing. That would be a more standard approach anyway, but I think it might break custom fields.

**Comment by jkshapiro** [comment]
This has already made someone "feel like an idiot". https://groups.google.com/d/msg/dotcms/8EFovbf35W4/c7Fq5YQZj7YJ

**Comment by jtesser** [comment]
Edit Mode is a very different thing.  You can edit the page properties.  We will be addressing edit mode with a redo in future releases
