### ISSUE TITLE
Upgrade Gradle to Current Version

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7533]
The current version of Gradle is 2.3 and is about 14 releases ahead of the 1.11 gradle wrapper that we currently have in master-3.2.

Having done upgraded locally, here are some things that may help expedite this process:
- Address issue with call to sync - not sure that this guy is right about not calling sync directly but the workaround on this page does work:  http://forums.gradle.org/gradle/topics/_sync_action_does_not_work_after_migration_gradle_1_8_2_0_could_not_find_method_from_error
- Rename targets in build.xml that cause conflicts:
  - javadoc
  - jar
  - clean

**Comment by dsilvam** [comment]
Gradle was updated here in core: https://github.com/dotCMS/core/pull/11317/commits/650084bfa99eadffa935925092c392e2389e3204#diff-39ee156975ba6e77630dc609e3b3f766

Upgrade for ee, lic, and dynamic plugins will be done here: https://github.com/dotCMS/core/issues/11346
