### ISSUE TITLE
Template "bring back this version" rendering issue

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7537]
1. Edit a template, save+publish
2. return to same template, click the version tab and click the old version of the template. 
3. Scroll to the bottom of the template:

![screen shot 2015-03-31 at 10 30 44 am](https://cloud.githubusercontent.com/assets/934364/6921187/3254bc72-d791-11e4-806b-780c9e3a1828.png)

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-01 // MSSQL // FF
