### ISSUE TITLE
String index out of range creating a past time machine snapshot 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7540]
After the fix #7525, we are having this error when you try to create a new past time machine snapshot... 

Here the log: https://gist.github.com/bryanboza/81b3329551eba21a8e7f

Tested on nightly build 2015-03-27 // MSSQL // FF // Win7

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/270 , mistyped the issue number it was 7540, but I typed 7450.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-02 // MSSQL // FF
