### ISSUE TITLE
If you have only 1 host and you stop it in the Host Manager You cannot log in

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7546]

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7549

**Comment by oarrietadotcms** [comment]
New PR: https://github.com/dotCMS/core/pull/7551

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-02 // MSSQL // FF
