### ISSUE TITLE
Enhancement: Add site/folder field to all content types

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7547]
In a multi-tenanted environment, permissioning is very important. In order to support folder-level permissioning, it would be very helpful if every new piece of content, of any type, automatically contained a site/folder field.

We currently add this manually, but had to learn the hard way to do so, and it would be nice not to have to. It would also make permissioning easier for new users to understand.

**Comment by jtesser** [comment]
there are many cases of people who don't want this. We don't force the content into the directory tree.
