### ISSUE TITLE
Enhancement: remove "Admin Screen" button for locked pages

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7550]
The issue:
1) Double-click an HTML page in Site Browser
2) Lock it for editing
3) Make changes and publish
4) Click "Admin Screen" to return to Site Browser

This does not unlock the page. It should not be so easy to leave a page in a locked state. The request is to remove the tempting "Admin Screen" button until the user has unlocked the content.

**Comment by jtesser** [comment]
you can use workflow to control this but yes
