### ISSUE TITLE
Push Publishing: Should not allow push configuration of servers with same IDs

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7552]
Ref Ticket: https://my.dotcms.com/ticket/dotcms-21

If you create a dotCMS instance, apply a license to it, then replicate this dotCMS instance, we allow you to configure these two instances with the same exact server IDs and licenses in a push model (one receives, one sends).

Push pub fails later on when trying to push, but configuration should not be validated in the first place.

**Comment by jtesser** [comment]
We can have the integrity checker ensure that the serverIds are different. If they are not we should report to the user they need a new license on one of the servers.  The integrity checker doesn't need to fix the case just report it. 

We can do the same for version of dotCMS

**Comment by wezell** [comment]
The Integrity Checker should check the licenses of the senders (all of them if license pack) and receivers (all of them if this is a license pack) and show an error if any of them are the same

**Comment by jtesser** [comment]
aded to card#94
