### ISSUE TITLE
Tag Storage field on Sites showing "All Sites" AND "System Host"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7570]
Saw this on latest 3.1 released version

When editing a Site and changing the Tag Storage Repository field, only "System Host" should be visible.  Even when you set "All Sites" it stores as "System Host", so we need to Hide the "All Sites" value.  We should not have two fields that both mean the same thing - confusing to our users.

Additionally, in Content Search section, the label "Hide System Site" should be renamed to "Hide System Host" to keep integrity.

See screenshot: http://screencast.com/t/7GWg4ArYxM

**Comment by john-thomas-dotcms** [comment]
Any chance we can get this fixed before 3.5 is released?  Makes documentation more challenging (both to take screen shots and explain the duplicate entries).

Thx.

**Comment by DeanGonzalez** [comment]
Even worse, this shows up when searching for content if you have a searchable host or folder field.

**Comment by shaydotcms** [comment]
Needs work. 
Searching for content in Content Search still shows "All Sites" and "System Host"

<img width="290" alt="2617f18c-116d-4852-aa7a-29ee23d7f1ea" src="https://cloud.githubusercontent.com/assets/8741846/17602372/a27eed3a-5fc9-11e6-8bc0-dcbde3eb8d86.png">

**Comment by DeanGonzalez** [comment]
I tested this as well and it seems to be working fine on the search/sort.  I did add this task to enhance naming consistency: https://github.com/dotCMS/core/issues/9584

**Comment by nollymar** [comment]
Pull request with last changes agreed with @DeanGonzalez : https://github.com/dotCMS/core/pull/9586

**Comment by nollymar** [comment]
Updated pull request: https://github.com/dotCMS/core/pull/9588
The field Host/Folder in Content Search was not changed

**Comment by DeanGonzalez** [comment]
I tested this again, and working as expected until we have an enhancement task for System Host.
