### ISSUE TITLE
Error indexing content in the Site search

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7577]
This issue is relate to #7499 
In that issue we added the property **ignore_above** to the **es-content-mapping.json** (https://github.com/dotCMS/core/commit/1c299abedda8e0d43fcd034699b4b76ce9242ec4), we need to do the same for the **es-sitesearch-mapping.json** otherwise we will get the same error as #7499 and the content wont be added to the site search index.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-11 // H2 // FF
