### ISSUE TITLE
Push Publishing: Order of Sub-actions in a Workflow Step is not retained after the scheme is pushed

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7581]
Reproduced in 2.5.6 and in 3.1. 

Steps to reproduce:

1. Create a Test Workflow Scheme with only one step and more than 2 Sub-actions.

2. Create a Test Structure and select the recently created Workflow as its Workflow Scheme.

3. Push the Structure.

Order of sub-actions is not the same between sender and the receiver environments. 

Sender:
![screen shot 2015-04-13 at 10 43 46 am](https://cloud.githubusercontent.com/assets/1717110/7117940/07d248dc-e1ca-11e4-9659-b940a09bdd98.png)

Receiver:
![screen shot 2015-04-13 at 10 43 58 am](https://cloud.githubusercontent.com/assets/1717110/7117946/0b82a990-e1ca-11e4-8c93-27d4afb4784b.png)

Re: https://my.dotcms.com/ticket/dotcms-22

**Comment by joseorsini** [comment]
Data in sender side:
 ```
select id, name, my_order from  workflow_Action_class where action_id = '22066ec4-acfd-42ee-89f9-8112ff7f62fb' order by my_order asc;
                  id                  |        name         | my_order 
--------------------------------------+---------------------+----------
 69089ccd-303b-4e8f-90df-b1bad764cec2 | Notify Assignee     |        0
 60c9e4df-1035-43ff-a317-c6bb777e7e23 | Unlock content      |        2
 a1960972-d30c-412f-9e10-f8d1eebe4bfc | Comment on Workflow |        2

```
Notice that, in sender side, the my_order column is not set properly. Sub-actions were not re-ordered after they were created.

Data in receiver side:
```
select id, name, my_order from  workflow_Action_class where action_id = '22066ec4-acfd-42ee-89f9-8112ff7f62fb' order by my_order asc;
                  id                  |        name         | my_order 
--------------------------------------+---------------------+----------
 a1960972-d30c-412f-9e10-f8d1eebe4bfc | Comment on Workflow |        0
 60c9e4df-1035-43ff-a317-c6bb777e7e23 | Unlock content      |        0
 69089ccd-303b-4e8f-90df-b1bad764cec2 | Notify Assignee     |        0
```

**Comment by rogelio-blanco** [comment]
This issue will be solved when #7757 code is merge

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7987

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // Postgres // FF
