### ISSUE TITLE
Push Publishing: Removing a relationship in Sender side does not update Receiver side after contents are pushed

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7582]
Reproduced in 2.5.7 and in 3.1. Steps:

1. Create a test Blog entry.
2. Once it's created, go to the frontend view of this content and add more than 1 comment to this entry. This will create as many related contents as you choose.
3. Push the Blog entry to the Receiver side. The piece Content, all their related contents and proper relationships are pushed as well.
4. Go to Sender side and delete one relationship from this blog Entry. Do not delete the related content through the Content Search Manager.
5. Check in frontend view of Sender side that Blog-Comments relationships is updated. You should see one less comment on the Comments section of that Blog Entry.
6. Push the Blog entry to Receiver side.
7. Check the frontend view of this Blog Entry on the Receiver side. It will reflect the relationship that was deleted in sender side.

Re: https://my.dotcms.com/ticket/dotcms-23

Sender Side:
![screen shot 2015-04-13 at 12 26 07 pm](https://cloud.githubusercontent.com/assets/1717110/7120050/479583f4-e1d8-11e4-9c8c-7464ffcc9236.png)

Receiver Side:
![screen shot 2015-04-13 at 12 26 10 pm](https://cloud.githubusercontent.com/assets/1717110/7120058/4cd2c5c0-e1d8-11e4-98e6-6b4ce06e4ed9.png)

**Comment by rogelio-blanco** [comment]
Pull Request #277

**Comment by joseorsini** [comment]
We would need to test other scenarios, like Many-to-Many relationships and also if a Comment is pushed instead of its parent blog content (for Blog-Comments relationship)

**Comment by jtesser** [comment]
When we test this lets make sure we got this one also. https://github.com/dotCMS/core/issues/6478#issuecomment-103872714

I think we did

**Comment by jtesser** [comment]
Need to merge in this and get new EE jar for 3.3 https://github.com/dotCMS/enterprise-2.x/pull/277

**Comment by rogelio-blanco** [comment]
#6478 (comment) its an related how the values are loaded by the vtl and not with the issue with the push publish

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // Postgres // FF
