### ISSUE TITLE
Enhancement: Implement Java 8 Metaspace in startup scripts

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7583]
In 3.2, we can remove any reference to PermGen from our startup scripts since it's no longer supported by Java 8. We should move to Metaspace

https://blogs.oracle.com/poonam/entry/about_g1_garbage_collector_permanent
http://stackoverflow.com/questions/24074164/what-is-the-use-of-metaspace-in-java-8

**Comment by joseorsini** [comment]
Since 3.2 is also compatible with Java 7, we should ask clients that the PermGem is no longer required only for Java 8. Closing this one. Thanks to @chrismccracken for the heads-up.

**Comment by wezell** [comment]
We should implement this when we drop support for java 7
