### ISSUE TITLE
Can't open context menu for legacy files

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7585]
Can be reproduced on versions 3.1 and 3.2.

When clicking right button on a legacy file at Site Browser menu - nothing happens. And there is a error in browser console:
```
Uncaught TypeError: Cannot read property 'length' of undefined
```

```javascript
function wfActionsMenu(objId, content) {
		contentAdmin = new dotcms.dijit.contentlet.ContentAdmin('','',1);
		var strHTML = "";
		for (var i = 0; i < content.wfActionMapList.length; i++) { //error appears in this line
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/7594

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-15 // postgres // FF
