### ISSUE TITLE
dotCMS/Velocity is inserting whitespace around contentlets

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7587]
Client Ticket Ref: https://my.dotcms.com/ticket/dotcms-24

Reproduced: demo.dotcms.com

dotCMS is inserting whitespace around contentlets, which affects the layout of any dom element displayed inline or inline-block. You can see this behavior in the promotions on the homepage of dotCMS's demo site.
I've attached 2 screenshots:
1. container.png shows that there shouldn't be any white pace around a promo item. (The grey pipe at the end of the pre loop, code, and post loop sections shows the end of the code for each those sections.)
2. markup.png shows that whitespace is being inserted around each promo item in the output.
   The result is that anything displayed inline or inline-block will have a visual space between it.

![container](https://cloud.githubusercontent.com/assets/1823543/7144387/2c856530-e2b3-11e4-885d-71c2fc6bc03e.png)

![markup](https://cloud.githubusercontent.com/assets/1823543/7144381/23a3e36a-e2b3-11e4-9123-ad19d7e60041.png)

**Comment by jtesser** [comment]
this is an old issue. This is how velocity writes code.
