### ISSUE TITLE
Container not clearing from cache

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7588]
1. Create a page with a template with one container
2. Add content to it. Say generic content. 
3. Edit the container from Edit Mode and alter it ie.. add some dummy text . 
4. Save publish the container

Notice your changes are not there until you flush cache.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-14 // Postgres // FF

**Comment by bryanboza** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/56655
