### ISSUE TITLE
No scroll Bar on new "Send an Email" Actionlet

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7590]
Affects the dotCMS 3.2 version where it was introduced
Problem: Users can't see the "save" or "cancel" button and there is no scroll bar.  User needs to tab to get to the bottom fields and buttons

We should figure out a way to incorporate a scroll bar to get to the bottom to be able to see the "save" or "cancel" buttons and the rest of the fields. We need to creatively work around Dojo on this one probably. Not totally broken, but we should make this better in a future version.

screenshot: http://screencast.com/t/TkZ9d44xw6x

**Comment by fishsmith** [comment]
Lets have Freddy take a look at this. Will and I took a shot at it awhile back with little luck.

**Comment by maurizo** [comment]
Pull request: #7689

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-12 01:19 // Ubuntu 14.04 // Postgres // Firefox
