### ISSUE TITLE
Unable to upgrade from 3.1 to 3.2 in MSSQL/Win7

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7592]
When doing an upgrade from 3.1 to 3.2 in MSSQL/Win7 using autoupdater, there's an error 500 when accessing the admin panel

To reproduce:
1) Using win7 and ms sqlserver, try to upgrade from 3.1 to 3.2 using autoupdater.
2) When the upgrade is done, startup the server and try to access the admin panel
You will see the error 500

Logs:
https://gist.github.com/shayngr/967740ff1290fe33fe95

Tested on: 
3.2 build (http://dotcms.com/download/download-now.dot?file=/physical_downloads/dotcms_3.2.tar.gz)
Win7 Pro SP1 // SQLServer 2012 // Chrome

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7593

**Comment by shayngr** [comment]
Working as expected. 
Tested on: 
3.2 build (http://dotcms.com/download/download-now.dot?file=/physical_downloads/dotcms_3.2.zip)
Win7 Pro SP1 // SQLServer 2012 // Chrome
