### ISSUE TITLE
Past time machine is not working after upgrade from 1.9 to 3.2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7599]
The time machine feature is not working after you upgrade from 1.9 to 3.2, we don't have problems when is creating the snapshot, but you can't see that... 

Here the errors in log when you try to open the snapshot: 
https://gist.github.com/bryanboza/9ad861ce9ecdfe5b1a5e

Tested on nightly build 2015-04-15 // postgres // FF

**Comment by jtesser** [comment]
I think the issue here is bad data and missing files. We should deal more gracefully in TM but not a critical issue
