### ISSUE TITLE
Past time machine is not working in 3.2 after upgrade from 1.9

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7600]
We are having a permissions error after try to make a past time machine snapshot in a dotcms 3.2 instance, after make an upgrade from 1.9... Seems the error is related to permissions and the enable_scripting property... 
Here the error: https://gist.github.com/anonymous/1b58a8c9d14f89a4d073

Everything the properties are by default....

To recreate: 
1- Start a dotcms 1.9 instance
2- Create some folders, pages, content, structures etc....
3- Shutdown the instance and copy the asset folder to the new 3.2 instance folder in the ROOT folder 
4- Configure the same database in the dotcms 3.2 instance 
5- Apply the com.dotcms.page.extension.config plugin
6- Start the system 
7- Make a full reindex 
8- Add the time machine portlet in the roles&tabs 
9- Create a past time machine snapshot

Tested on nightly build 2015-04-15 // Postgres // FF

**Comment by jtesser** [comment]
this isn't a bug.  You don't have permissions to execute the macro
