### ISSUE TITLE
Unable to upgrade from 3.1 to 3.2 in oracle

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7601]
We are having errors when you try to upgrade from dotcms 3.1 to the 3.2 version, we have a fatal error running the upgrade tasks 

Log: https://gist.github.com/anonymous/358a68f1ff62d9c7533b

You will have this when you try to login on backend: 

![oracle](https://cloud.githubusercontent.com/assets/2641437/7191696/c6f23fc2-e44c-11e4-829f-7d2c5f22bda7.png)

Tested on nightly build 2015-04-15 // Oracle // FF // Linux

**Comment by jgambarios** [comment]
Look at: http://stackoverflow.com/questions/12980038/ora-00932-inconsistent-datatypes-expected-got-clob

**Comment by jtesser** [comment]
@erickgonzalez @oarrietadotcms lets look at this right away in the morning.

**Comment by oarrietadotcms** [comment]
Fixed, PR: https://github.com/dotCMS/core/pull/7602

Thanks for the link @jgambarios

**Comment by bryanboza** [comment]
Fixed, tested in master-3.2 // Oracle // Linux..
