### ISSUE TITLE
HTML not escaped in Content Search listing

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7604]
To replicate in demo.dotcms.com:

1. Start with a content type that has a field where:
 - "Validation RegEx" is blank
 - "Show in listing" is set
2. Create a new contentlet of that type.
3. In that field, enter HTML e.g. "`<p style="background-color:pink">hi<br>there<br>everyone<img src="http://dotcms.com/application/themes/dotcms/img/logo.png"></p>`"
4. Save and publish.
5. In the Content Search tab, view that contentlet. You will see the HTML rendered. It should be escaped.

![capture](https://cloud.githubusercontent.com/assets/3178838/7207490/cb52ebaa-e507-11e4-9569-647a1b304172.PNG)

This is an example of the general principle mentioned at #6955.

**Comment by jtesser** [comment]
This is actually done on purpose.  If you want to handle this we have view tools and you can handle in your containers etc...

**Comment by jkshapiro** [comment]
Viewtool or custom portlet? Can we modify the existing Content Search portlet or would we have to write our own?
