### ISSUE TITLE
Container Upgrade Task broke in 3.2

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7605]

**Comment by oarrietadotcms** [comment]
Ready, PR: https://github.com/dotCMS/core/pull/7607

**Comment by jtesser** [comment]
QA I think we should upgrade both a 2.5 and a 3.1 to ensure containers work.  I would create a container with multiple version in 2.5 after the install and the same in 3.1  

Then play with the container in 3.2

**Comment by brentgriffin** [comment]
In what way was the container originally broken?  What do we specifically need to look for on the upgraded containers?

**Comment by jtesser** [comment]
couldn't edit it. The dojo button for add variable was not rendering right meaning no DOJO styles. But you will know.  You couldn't save

**Comment by bryanboza** [comment]
Fixed, tested in the last 3.2 // MySQL // FF ....
