### ISSUE TITLE
Enhancement: Improve category selection

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7611]
The selection mechanism for categories needs some attention. For a user to add a category to a contentlet, they should be able to click on the category name--the little green plus sign is too small and too different from the rest of dotCMS to be useful. There should be a different place for people to click if they want to view subcategories. Maybe a treeview would make sense here like the one used in Site or Folder fields.

**Comment by SrKathleenBurns** [comment]
I agree. It is difficult to distinguish the plus sign from the familiar status light and is not an obvious selection mechanism.
