### ISSUE TITLE
Documentation: Single pipe to present null option in a select list

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7614]
Yesterday in training, in response to a question, Dean pointed out that if you want a null option in a select list then you can enter just a pipe symbol ("|") on a line by itself. This is a good trick and should be included in the documentation.

**Comment by jtesser** [comment]
@DeanGonzalez

**Comment by DeanGonzalez** [comment]
Added to the bottom of the standard field type doc: http://dotcms.com/docs/latest/standard-field-types
