### ISSUE TITLE
Enhancement: Synchronize behaviour of Forms and Content Types

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7626]
There is a lot of similarity between a Form and a Content Type, enough that actions that can apply to either one should do so. In the Content Type portlet if you click the name of a content type you are brought to the definition. In the Forms portlet if you click the name of a form you are brought to a list of contentlets ("formlets?") of the appropriate type. Both of these actions are valuable and should be accessed the same way from both portlets.

**Comment by jtesser** [comment]
for now this is on purpose.
