### ISSUE TITLE
Bug: Values from one contentlet are attached to another contentlet when looping within a container

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7627]
To replicate:

1. Create a content type that has an optional field.
2. Create a container that accepts (more than one of) that content type. In the Code area, display the value of the optional field.
3. Create two contentlets of the content type, one where the optional field is set and one where it is left blank.
4. Add the contentlets to the container in order.

For the second contentlet, nothing should be displayed. Instead, the value for the optional field from the first contentlet is displayed.

**Comment by jtesser** [comment]
we are not clearing the velocity context for the $content object in ContentletServices and/or ContentletMap

**Comment by brentgriffin** [comment]
QA - please make sure that you can recreate in the released 3.2 version before testing this issue.  Need to make sure that we have the recreation steps down before testing the fix.

**Comment by bryanboza** [comment]
Tested on the released 3.2 version and i am not able to reproduce this issue... I will close the ticket...
