### ISSUE TITLE
Enhancement: Set "ctInode" as an alias for "stInode" and "ctName" as an alias for "stName" in Content API

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7628]
Now that structures are called content types, it is strange to have fields in the REST Content API called "st[ructure]Inode" and "st[ructure]Name". Users should instead be able to use "c[ontent]t[ype]Inode" and "c[ontent]t[ype]Name". For backward compatibility, these should probably be aliased rather than renamed.

**Comment by jtesser** [comment]
we actually are handling this in 3.2.  As we are continuing to handle the change in nomenclature
