### ISSUE TITLE
Enhancement: Fix the vocabulary around Remote/Push Publishing

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7630]
The terminology used with push publishing is confusing. The terms "push publishing" and "remote publishing" are close enough to "publishing" as to cause confusion, especially because something that's been push published isn't necessarily published. As well, the term "remove" does not clearly refer to the remote server. Until being trained yesterday, I was under the belief that the choice between "remote publish" and "remove" was like the choice between "copy" and "move"--i.e. that if you removed an item as part of push publishing then it would no longer be on the source server.

Not sure of the best alternative. Maybe something like "create remote copy" and "delete remote copy"?

**Comment by jtesser** [comment]
yea there is a lot here.  

For now this is the terminology but we are always looking to improve
