### ISSUE TITLE
Bug: "Insert/Edit Link" tool in TinyMCE editor doesn't work

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7632]
To replicate:

1. Create a contentlet with a WYSIWYG field.
2. Click the "Insert/Edit Link" icon in the TinyMCE editor.
3. Use the camera/search icon next to the "Url" (sic) field, and navigate to a page.

The resulting URL will look something like this: "/contentAsset/raw-data/a7e17f67-4e09-4e51-8275-cddd9f7094b5/fileAsset". This includes the correct page identifier but dotCMS does not recognize it as a valid URL.

**Comment by jtesser** [comment]
what do you mean by "dotCMS does not recognize it as a valid URL"

**Comment by jkshapiro** [comment]
I get a 404 error when I click on it.

**Comment by jtesser** [comment]
assuming it is a file as content file which all ones created since 2.0 should be it should work unless you have something broken on your local system.

**Comment by jkshapiro** [comment]
Replicated on demo.dotcms.com. Try following the link at http://demo.dotcms.com/home/kivi-test

**Comment by rogelio-blanco** [comment]
Pull request #7708

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/59159
