### ISSUE TITLE
Bug: Releasing the lock on a page does not return it to its former status

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7633]
To replicate:

1. Create an HTML page and add content to it. Save and publish.
2. Lock the page for editing.
3. Remove a contentlet from the page.
4. Do not save and publish. Instead, release the lock.

The contentlet is no longer on the page. It should be; the page wasn't even saved let alone published.

**Comment by jtesser** [comment]
no this is by design. The content on a page is not like editing the page properties.  When you move remove contents in Edit Mode you are actually altering the page
