### ISSUE TITLE
Enhancement: Clarify permissioning

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7639]
In order to allow front-end users to fill in and submit forms, we have to grant the CMS Anonymous role "Edit" permissions on Content Types in the appropriate folder. This makes no sense. Creating a new contentlet is not the same as editing that contentlet's Content Type.

**Comment by jtesser** [comment]
this is on purpose.  You'd have to look more into our permissioning but when content has a folder/host its parent permission object is that host/folder and not the structure.  This is true of all content

**Comment by jkshapiro** [comment]
This isn't about the folder, that part does make some sense. It's about needing Edit permission on a content type in order to create new contentlets.
