### ISSUE TITLE
Enhancement: Remove default "All Sites" entry when granting permissions

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7644]
According to the training, it's bad practice to assign permissions on All Sites. Therefore we should not show All Sites by default when the user starts to permission a new role.

**Comment by jtesser** [comment]
best practices vs what is allowed is different.  There are cases for it

**Comment by jkshapiro** [comment]
I'm not saying remove the ability to permission on All Sites. Sometimes you need a stumbling block, like for something to stand on to reach things that are up high. But the stumbling block should not be placed in front of people, it should be off to the side.
