### ISSUE TITLE
Enhancement: Force Unlock when editing a contentlet should also lock for editing

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7649]
When you're editing a piece of content that someone else has a lock on, there's a handy Force Unlock button. This should remove the existing lock and also give a lock to the user. Because why are they unlocking the contentlet unless they want to make changes themselves?

**Comment by jtesser** [comment]
because others need to edit

**Comment by jkshapiro** [comment]
What percentage of the time are people unlocking content so that they can make changes vs. unlocking content so someone else can make changes? And when people are unlocking content so someone else can make changes, what percentage of the time are they going into the contentlet vs. just looking it up in the Content Search portlet?

I only know the answers to those questions in our own organization, but here they're approximately 99%, 1%, 60%, and 40%. Multiplying it out we get:
99% of people go into the contentlet to unlock it for themselves
0.6% of people go into the contentlet to unlock it for someone else
0.4% of people unlock the contentlet for someone else from the Content Search portlet

So who do we want to optimise the interface for? The 0.6% or the 99%?
