### ISSUE TITLE
Enhancement: Provide a version history of what content has been added to a page

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7651]
The version history of a page shows what changes have been made to the page contentlet itself, but not what content has been added or removed. There doesn't seem to be any way to get at that information currently, nor to roll back to a previous state. This should all be made available.

Not sure whether it should be added to the page's version history or whether it should be a different function. Maybe usability testing would help.

**Comment by jtesser** [comment]
we don't currently store this info or handle this kind of rollback or history. Not sure when or if we will moving forward. Plus with widgets and pulls it is only semi useful and can be confusing.  TM should help here for those needing to look at previous renditions of the page
