### ISSUE TITLE
Enhancement: Provide "Host or Folder" search for All content in Content Search portlet

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7652]
In the Content Search portlet, if you select to view "All" content types, you don't have the ability to search by Host or Folder. We would really like to have this ability. Yes we understand that content without a Host or Folder field is stored in System Host.

**Comment by jkshapiro** [comment]
If we can't have #4761 then this would provide a workaround. Currently if we want to see what content is in a folder, we have to look content type by content type.

**Comment by jtesser** [comment]
you can search by location using the query.
