### ISSUE TITLE
Enhancement: Add a "Start with theme folders" option to the Add Site flow

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7655]
When you create a new site, you are presented with two options:
- "Copy an existing site"
- "Start with a blank site"

For the benefit of new users (and really anyone who wants to use themes), it would be valuable to add a third option:
- "Start with theme folders"

This would create a site that was mostly blank except for the following folders:
- application
  - themes
    - default

In the "default" folder would be some very basic VTL files:
- html_head.vtl
- header.vtl
- footer.vtl

These folders and files are prerequisites for using themes, so this option would save repetitive work and the chance for error for everyone, but especially new users,

**Comment by jkshapiro** [comment]
Lower barrier for entry -> more users of dotCMS.

**Comment by jtesser** [comment]
for now you can create a host to copy that has your themes but this is by design
