### ISSUE TITLE
Remove Button "Get License Request Code"

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#7657]
I don't believe the "Get License Request Code" button does anything. Once you select Type & Level the Request code automatically populates. You don't need to click the button.

See Picture.
![screen shot 2015-04-24 at 9 02 49 am](https://cloud.githubusercontent.com/assets/1561349/7327280/e99ff606-ea99-11e4-829e-6cd32cdc8c3f.png)

**Comment by rogelio-blanco** [comment]
Pull request: #7657

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-12 01:19 // Ubuntu 14.04 // Postgres // Firefox
