### ISSUE TITLE
Need show a complete file path uploading multiple files 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7658]
When you have a folder with a large path and try to upload some multiple files or images, the system is showing only part of the folder path, we need use the blank space to show all the path..  

SC: http://screencast.com/t/MDS2gZr6YJ

Tested in the latest 3.2 // H2 // FF

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-12 01:19 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/71
