### ISSUE TITLE
Unable to upload files directly adding content from binary fields

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7659]
If you create a new structure with a binary field, and then you go to content tab and try to add some content to the structure, in the binary field, if you want upload a new file from your computer, the system is showing a console error and you can't make the file upload....

To recreate: 
1- Create a new structure with a binary field 
2- Try to add a content to this structure
3- In the binary field, click to browse, select any folder and try to upload some image from your local 
4- Click on save and publish button 

Here the video: http://screencast.com/t/hXUkCwuMHHP

Tested in the latest 3.2 // H2 // FF

**Comment by rogelio-blanco** [comment]
pull request #7714

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-12 01:19 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59163
