### ISSUE TITLE
Copying Content does not copy its relationships

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7661]
If you copy a piece of content with relationships, the relationships are lost on the copied piece of content.

Tested on demo.dotcms.com running 3.2.

**Comment by rogelio-blanco** [comment]
I did a test, however I was not able to reproduce it.

Could you please include the steps to reproduce the issue?

**Comment by levosgien** [comment]
I can't reproduce anymore, let's resolve this I can't remember what I did last time.

**Comment by oarrietadotcms** [comment]
Closing this one as not reproducible.
