### ISSUE TITLE
Clean-Up "About" Pop-Up

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7662]
Styles for Server ID and bottom of the window need fixing:

![screen shot 2015-04-27 at 4 13 09 pm](https://cloud.githubusercontent.com/assets/1823543/7356792/8cc6b92c-ecf8-11e4-850d-6fc58d8866a9.png)

Tested on demo.dotcms.com running 3.2.

**Comment by fishsmith** [comment]
The serverID div is outside the dojo model content pane. It looks like someone try to absolute position it.

I would suggest moving the serverID div into the dijit.layout.ContentPane and removing the class .serverID from the css

![screen shot 2015-04-28 at 7 27 00 am](https://cloud.githubusercontent.com/assets/1561349/7368705/af3eab38-ed78-11e4-912c-979122ba974d.png)
