### ISSUE TITLE
Can't delete content with multiple language versions

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7663]
Saw this on dotCMS 3.2 release version running on Linux/postgres

Bug: content gets in a state where no version of the content can be deleted at all.

To recreate:
1) Create a piece of generic content in English (save and publish)
2) Create a spanish version of that same contentlet (save and publish)
3) Unpublish, archive and try to delete the spanish version... it does not delete and shows this message on the screen:
http://screencast.com/t/299HaK53E5uV
4) Now go to the English version of the content, unpublish, archive and try to delete the English and spanish version... neither will delete.  Try to delete them individually, neither deletes.

**Comment by jtesser** [comment]
the functionality is right. We don't delete because that destroys the identifier.  The message is wrong but behavior is right

**Comment by DeanGonzalez** [comment]
If you want to delete all versions, all languages, there is no way to do so unless you are an Admin and have access to the Maintenance Tools - Delete Contentlets portlet... that is a bug... I can understand if it does not let you delete a language version when another is published or working... but when EVERY language version is archived it still won't let you delete.

**Comment by DeanGonzalez** [comment]
We allow full delete if the contentlet has only one Language version

**Comment by jtesser** [comment]
@DeanGonzalez no you can delete IF you have permissions meaning Edit Permission permission AND the other versions are unpublished.

**Comment by DeanGonzalez** [comment]
We are in agreement on the way it should work, but the case you just mentioned does not work, that is the bug.  I am logged in as Admin, and all versions of the content are unpublished, and I still can't delete.
http://screencast.com/t/ISQ7gnsyH9Ox

**Comment by DeanGonzalez** [comment]
You have to follow my steps in the original reported bug to make it happen.

**Comment by jtesser** [comment]
@DeanGonzalez no :-p  In your steps at step 3 the English is STILL published. In fact in step 4 you explain that you unpublished it. But step 3 is where your error is

**Comment by jtesser** [comment]
OK so step 4 is the issue you are saying. We'll look

**Comment by DeanGonzalez** [comment]
Yep, I totally agree that step 3 should not allow the delete, if it did, that would be bad - step 4 is where things something gets hung up, even though it should allow the delete then.

**Comment by Xander-Steinmann** [comment]
This is the same as https://github.com/dotCMS/core/issues/8269. It doesn't work yet in 3.2.4.

**Comment by allychan** [comment]
also cant deleted data in 3.2.4
