### ISSUE TITLE
assets are forcing download

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7664]
hit this url - it should display in your browser

http://demo.dotcms.com/images/404.jpg

cabbage:~ will$ curl --head http://demo.dotcms.com/images/404.jpg
HTTP/1.1 200 OK
Date: Tue, 28 Apr 2015 15:32:05 GMT
Content-Type: image/jpeg;charset=ISO-8859-1
Content-Length: 47945
Connection: keep-alive
Server: Apache-Coyote/1.1
dotCacheImages: yes
Expires: Wed, 27 Apr 2016 15:32:05 +0000
Cache-Control: public, max-age=31536000
Content-Disposition: attachment; filename=404.jpg
Last-Modified: Tue, 17 Jun 2014 13:07:06 +0000
ETag: dot:249eeb5c-7002-48e8-9ef3-ea6cd8ea9043:1403010426000:47945

**Comment by wezell** [comment]
Here is an example of why this is a problem:

http://dotcms.com/docs/latest/HighPerformance

**Comment by rogelio-blanco** [comment]
Pull Request #7749

**Comment by bryanboza** [comment]
Fixed, tested in Nightly build 2015-05-19 // H2 // FF... Useful improvement

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59169
