### ISSUE TITLE
no_license.jsp is not displayed in tomcat

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#7665]
After this fix: https://github.com/dotCMS/core/issues/7486

no_license.jsp is not displayed in tomcat

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7666

**Comment by jtesser** [comment]
Lets see if all unit tests can pass now

**Comment by bryanboza** [comment]
Passed
