### ISSUE TITLE
Need update the documentation of WebSphere Server App

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7667]
We need update some details in the dotcms documentation when you are installing WebSphere Server... 
http://dotcms.com/docs/latest/DeployDotCMSAsAWarFileInWebSphere

**Comment by jtesser** [comment]
@bryanboza did you have specific issues?

**Comment by bryanboza** [comment]
1- We have all the config files ready to run in H2, In the step 4 if you copy the jdbc try to run with Postgres, we need indicate this step is optional
2-  In the step 5, the server.xml does not exist, because you only have the unzipped war in this path, you need copy from the $DOTCMS_HOME/docs/examples/websphere/server.xml... Then we need use copy instead modify 
3- The same thing in the step 6, the jvm file does not exist, you need create the folder and copy the file....

Little details can be more easy to follow the guide...
Here the QA installation guide document : https://docs.google.com/a/dotcms.com/document/d/1wa9YxfPHpUr3YDgw-pynwvdmxy-wmEluObc3Co-SLzA/edit?usp=sharing

**Comment by john-thomas-dotcms** [comment]
Websphere is no longer supported, so this is obsolete now
