### ISSUE TITLE
Navtool.nav not working in 3.2 version

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7669]
In previous versions, we have always been able to use the nav tool to create crumbtrails this way:

Look at the documentation link so see how nav.parent and nav.children are used: http://dotcms.com/docs/latest/NavigationTool

https://gist.github.com/DeanGonzalez/aa5a299eac2378354596  (does not work on 3.2)

Here is an example of that exact code working on demo2.dotcms.com:
http://screencast.com/t/hY6Jg6hhv

However, placing the same code, in the same demo resources folder on the 3.2 version, produces null variable results: 
http://screencast.com/t/qaHoVdla

Both pages were tested from the front end

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7754

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-19 19:53// Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/59160
