### ISSUE TITLE
Can't save content by checkbox with similar values

### ISSUE THREAD

**Issue by litked** [dotCMS/core#7670]
1. Create new ContentType 'MyContentType'
2. Create new field 'MyCheckbox' (type Checkbox)
3. Edit field 'MyCheckbox'. Set value
 - canada|Canada
 - canada-new|Canada New

4. Create new contentlet of type 'MyContentType'
5. Edit new contentlet. Check both checkboxes. Save. Result: both checkboxes are 'checked'. OK
6. Edit new contentlet. Check off both checkboxes. Save. Result: both checkboxes are still 'checked'!

Reproduced on http://demo.dotcms.com/

**Comment by bryanboza** [comment]
Tested on the last 3.2 and not able to reproduce...

**Comment by oarrietadotcms** [comment]
Closing this one as it is not reproducible in latest release.

**Comment by litked** [comment]
Sorry, here is correct description:
1. Create new ContentType 'MyContentType'
2. Create new field 'MyCheckbox' (type Checkbox)
3. Edit field 'MyCheckbox'. Set value
 Canada|canada
 Canada New|canada-new
4. Create new contentlet of type 'MyContentType'
5. Edit new contentlet. Check only 'Canada New'. Save. Result: both checkboxes are 'checked'!

Reproduced today on http://demo.dotcms.com/
Screencast: http://screencast.com/t/h7VLq7L1e

**Comment by oarrietadotcms** [comment]
@rogelio-blanco could you please try to reproduce and fix it? Thanks!

**Comment by rogelio-blanco** [comment]
I was able to reproduce it.   I will continue with the fix

**Comment by rogelio-blanco** [comment]
pull request #7728

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-14 04:13 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59161
