### ISSUE TITLE
Make felix caching directory configurable

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7673]
One of our potential clients has requested that we make the felix caching directory configurable.

Excerpt:
"Felix tries to write into its cache directory which is not configurable (in our case to a writable storage).
Is there any possibility to tweak the current release to make this cache directory configurable?"

To get dotCMS to work in their environment, they had to disable felix - less than optimal.

**Comment by jtesser** [comment]
Right now this can only be done via altering this class via a static plugin OR creating a symlink 

Line that needs to be configurable is https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/util/OSGIUtil.java#L84

**Comment by dsilvam** [comment]
Fixed in here https://github.com/dotCMS/core/issues/10370
