### ISSUE TITLE
Upgrade core Spring Libs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7674]
We are on 3.x and need to move to 4.x.  Multiple clients are requesting.

**Comment by jtesser** [comment]
This means we need to also update the OSGi plugin examples

**Comment by ethode** [comment]
Evening gentlemen.  Has this issue been seriously considered for an upcoming release or still just in consideration mode?  Thanks!

**Comment by wezell** [comment]
@ethode feel free to fork, change them and do a pull request and we will review it.
