### ISSUE TITLE
Improve cluster deployment of OSGI plugins

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7675]
Currently, OSGI plugins must be deployed to each server in a cluster independently. This is problematic for the secured SaaS environment where clients often only have access to the load balancer and not have direct access to the individual CMS servers. Some clients are using onerous client lb session cookie manipulation to work around this. This approach also does not work with autoscaling, as any new instances added to the cluster will not have have the same OSGI plugins set as the existing instances. 

Placing the felix/load/ directory on NFS storage has been proposed as a solution to this, but that has not worked well in practice. Cross-server file locking of the deployed jars on the NFS share makes plugin undeployment unreliable (if it works at all).

OSGI deployer should:
- Deploy to all instances in the cluster individually when a new plugin is uploaded
- Maintain a store of active OSGI plugins to deploy to new Dotcms instances when they are added to the cluster

Of course, this behavior should be possible to disable via config as someone will inevitably have a use case that is broken by this.

**Comment by jtesser** [comment]
@chrismccracken there is really no other way to do this.  We have to drop the file on each server. We cn build an interface for this but again not easy.  You can use Push Publishing to accomplish what you want by sending a bundle to cluster
