### ISSUE TITLE
Allow host-based include/exclude patterns on SiteSearch indexer

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7676]
The SiteSearch indexer should allow specifying a host prefix on the include/exclude patterns when you select "Index all sites".

Currently, clients are using multiple SiteSearch indexes (one for each host) as a workaround for this, but this causes performance issues and is not optimal. The number of ES indexes that need to be active should be minimized for resource management considerations (file handles, ES indexing buffer split- http://www.elastic.co/guide/en/elasticsearch/reference/1.4/modules-indices.html#buffer).

A picture is worth 1000 words:
![image](https://cloud.githubusercontent.com/assets/3977301/7416806/c6c85f02-ef16-11e4-8ec0-654e5f7f03bb.png)

**Comment by jtesser** [comment]
this is handled by the select sites to index.  You would need different jobs if this isn't flexible enough.
