### ISSUE TITLE
 Improved password storage security

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7677]
Enhancements to Dotcms password storage

See https://my.dotcms.com/ticket/dotcms-29/

**Comment by dsilvam** [comment]
+1 this this critical. Played a bit with it, got the hash from a 123123 password (we base64 it) and was able to get the value back using https://crackstation.net/ lookup tables

**Comment by jtesser** [comment]
For sure we need this

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/63

**Comment by jkshapiro** [comment]
See also #4403.
