### ISSUE TITLE
Site nav tool is not respecting multi-language pages  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7678]
We are having problems, with the site nav tool, when you change the system language, we should update this tool with the pages and folders in the respective language, and this is not working 

Here the image: http://screencast.com/t/DPf0noFn, here every page have the spanish versions with different page tittle 

FYI: When you try to reorder the site nav menu, you can see the multi language pages versions separately... http://screencast.com/t/PWQygtsjleGn

To recreate: 
-  Create a Spanish version of the "What we do" page with title "What we do (SP)" by switching language in the page properties and filling all fields
-  Flush all caches (just to be sure)
-  Open the homepage and switch to Spanish. In the menu I still see the original About us > "What we do"
-  Open the "What we do" page in Spanish and on the left side I see "What we do"
- When you click the arrows of the top menu I see both the "What we do" and "What we do (SP)" in the menu reordering...

Tested on 3.2 // H2 // FF

**Comment by jtesser** [comment]
@oarrietadotcms can you look into this with @bryanboza See the mailing list from this morning for a reference

**Comment by oarrietadotcms** [comment]
I have a question about this, @jtesser . For the reorder page: http://screencast.com/t/PWQygtsjleGn

Do we want to show Folder/HTML for all languages or just for the language user is currently?

**Comment by jtesser** [comment]
language the user is currently logged in for now as no UI change for 3.2.1.

**Comment by dotcmsCodeReview** [comment]
Is the nav rendering in the language of the site visitor?

On Mon, May 4, 2015 at 9:08 AM, Jason Tesser <notifications@github.com>
wrote:

> language the user is currently logged in for now as no UI change for
> 3.2.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7678#issuecomment-98700810>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jtesser** [comment]
It should be we are addressing it

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7695
