### ISSUE TITLE
Unchecking "Show on Menu" does not remove page from navtool

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7679]
When you uncheck the "show on menu" property in a Page (Page as Content) and save and publish, it does not remove that page from the generated $navtool results.

This bit me on dotcms.com and I just reproduced on demo:
1. Create a new HTML page in the /about-us folder called "testing". check show on menu.  Also make sure to set page cache to 0.
2. View the page /about-us/testing page and you will see your new page, all good.
3. edit page properties and uncheck "show on menu".  Save and Publish
4. Your page will still be in the menu.

**Comment by oarrietadotcms** [comment]
Fixed here: https://github.com/dotCMS/core/issues/7678

**Comment by bryanboza** [comment]
Fixed, tested on dotcms-3.2 // H2 // FF
