### ISSUE TITLE
Unmap com.dotmarketing.viewtools.NavigationWebAPI in distro

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7682]
It is a request scoped viewtool and opens an unneeded file handle every request:

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/viewtools/NavigationWebAPI.java#L533

**Comment by oarrietadotcms** [comment]
@wezell just to be sure, by "unmap" you mean remove from the toolbox? https://github.com/dotCMS/core/blob/master-3.2/dotCMS/WEB-INF/toolbox.xml#L191-L195

**Comment by wezell** [comment]
Actually, I would just create the file once, when the server is first
started.  I dont want to change macros in a minor version

On Tue, May 12, 2015 at 11:16 AM, Oscar Arrieta <notifications@github.com>
wrote:

> @wezell <https://github.com/wezell> just to be sure, by "unmap" you mean
> remove from the toolbox?
> https://github.com/dotCMS/core/blob/master-3.2/dotCMS/WEB-INF/toolbox.xml#L191-L195
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7682#issuecomment-101317525>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7722

**Comment by brentgriffin** [comment]
While the implementation did not accomplish what the title indicates, the code Will refers to has been relocated so that it is only executed at system startup and not for every request.
