### ISSUE TITLE
Unexpected error publishing a page after inline editing 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7684]
We are having an error when you make any modification to any content with the inline editing feature and then try to publish

To recreate: 
- Apply a dotcms license to enable the inline editing feature 
- Try to edit the ./about-us/What we do.html
- Click to edit the text and then click to save button 
- Publish the page 

Note: If you can't reproduce repeat the steps 3 and 4 again 

Here the screencast: http://screencast.com/t/GYDVN9v483az
Log: https://gist.github.com/bryanboza/6de1b3167ccd7753c1a7

Tested on the last 3.2 // H2 // FF

**Comment by bryanboza** [comment]
FYI: Also the save button is not working in Chrome and Safari when you maximize the window

**Comment by rogelio-blanco** [comment]
pull request #7774

**Comment by shayngr** [comment]
"Save" button is still not working in Chrome and Safari. The browser has to be maximized for the button to work.

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59158
