### ISSUE TITLE
Problem with doc site link to Debugging in Eclipse

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7685]
If you search for eclipse on the documentation site (http://dotcms.com/docs/latest/Development-Environment?q=eclipse), you get three hits.  The first link is http://dotcms.com/docs/latest/EclipseDevelopmentEnvironment

This link does not display the content revealed in the search but redirects to the table of contents via a 301.

i.e. using curl on URL 
curl -I http://dotcms.com/docs/latest/EclipseDevelopmentEnvironment
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 04 May 2015 18:08:33 GMT
Content-Type: text/html;charset=UTF-8
Connection: keep-alive
Set-Cookie: JSESSIONID=8E5025E839C2CD2846DF2FBCD6F5535C; Path=/; HttpOnly
Set-Cookie: dmid=152027e5-264a-4deb-82bb-eb8d825ebc9e; Expires=Wed, 18-Mar-2020 18:08:33 GMT; Path=/
Location: /docs/latest/table-of-contents
Vary: Accept-Encoding

**Comment by DeanGonzalez** [comment]
All links now resolve to doc, all  old urlTitle pathing was updated.
