### ISSUE TITLE
When Page Cache is On we should NEVER instantiate Velocity  

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7686]
We do it on lines 
https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/velocity/VelocityServlet.java#L534
https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/velocity/VelocityServlet.java#L469

these lines eventually make calls that setup the engine. 

We could get a lot smarter in this way. In the CMSFIlter we get the iHTMLPage. When if we stick this in the request and use throughout the the request processing.  Much smarter :-p

**Comment by oarrietadotcms** [comment]
Working on this one.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7723

**Comment by bryanboza** [comment]
Fixed, tested as part of the performance testing
