### ISSUE TITLE
Misspelling in properties file

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7690]
The value for the processing key is misspelled.

dotCMS/WEB-INF/messages/Language.properties:Processing=Procesing

This value for this key displays on the site screen when deleting a site.

**Comment by jtesser** [comment]
First bug for @rogelio-blanco

**Comment by rogelio-blanco** [comment]
Pull request: https://github.com/dotCMS/core/pull/7692

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-12 01:19 // Ubuntu 14.04 // Postgres // Firefox
