### ISSUE TITLE
Problems with the bundle encoding in Windows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7691]
We are having problems when you try to download any bundle from a windows server, and then try to upload in another server....  The system is not finding a asset and this generate a NPE 

Here the log error: https://gist.github.com/bryanboza/80ad82ede7fd6ff83779

FYI: The file of the error is in the bundle if you unzip in a folder 

To recreate: 
- Configure your push environment (Only on sender)
- On a windows server generate a bundle and try to push
- Go to Pushing Queue tab --> Status/ History and click the bundle to see details 
- Here click to download bundle button 
- Try to upload this bundle on a mac, or linux server 

Tested in the last 3,2 code // H2 // FF

**Comment by joseorsini** [comment]
Re: https://my.dotcms.com/ticket/dotcms-30

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/96

**Comment by rogelio-blanco** [comment]
I was not able to reproduced it in 3.2.4.

Seems to be fixed

**Comment by levosgien** [comment]
Rogelio, that's great. Can you confirm that this was something you could reproduce on 3.2 (to make sure we're testing the same thing) before we close this? Thanks.
