### ISSUE TITLE
Need to remove es.network.port from dotmarketing-config.properties file and from documenation

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7698]
es.network.port is no longer used and should be removed from properties file and documentation.  This is from email forum:  https://groups.google.com/forum/#!topic/dotcms/exwUzsUzaGA

The affected documentation is here:  http://dotcms.com/docs/latest/cluster-configuration

**Comment by rogelio-blanco** [comment]
Pull Request #7746

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-19 02:05 // Ubuntu 14.04 // Postgres // Firefox

**Comment by john-thomas-dotcms** [comment]
Documented.
