### ISSUE TITLE
Multiple live caches

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7699]
Seems that we are creating two different livecaches rather than one.  One of them seems to be for the html pages and the other for everything else.  Based on my understanding, there should only be one live and one working cache.

To recreate:
1.  Install and start dotCMS 3.2
2.  hit a front end page - i.e. http://localhost:8080/
3.  Login to backend and to to System->Maintenance->Cache tab
4.  Click "Refresh Stats" link at bottom of page
5.  Scroll down to see listings for "livecache_" - you should see two entries here

![image](https://cloud.githubusercontent.com/assets/3208956/7517769/93c5a8ae-f49c-11e4-9394-de2a54941c72.png)

As you can see for the log file, these caches are created within microseconds of each other:
2015-05-07 09:28:18,030 INFO  com.dotmarketing.business.DotGuavaCacheAdministratorImpl - ***	 Building Cache : livecache_48190c8c-42c4-46af-8d1a-0cd5db894797_1, size:1000, toDisk:false,Concurrency:32
2015-05-07 09:28:18,031 INFO  com.dotmarketing.business.DotGuavaCacheAdministratorImpl - ***	 Building Cache : livecache_48190c8c-42c4-46af-8d1a-0cd5db894797, size:1000, toDisk:false,Concurrency:32

I have seen this on multiple operating systems and db engines.  Seems to happen every time from what I can tell.

Ubuntu 14.04.2 LTS // Java Oracle 1.7.0_80 // dotCMS 3.2 Release // H2 & PostgreSQL

**Comment by jtesser** [comment]
this is correct 
A live cache for each host

**Comment by jtesser** [comment]
actually for each host for each language

**Comment by brentgriffin** [comment]
Ok - I did not realize that we made this change.  I added a second language and now I have a third livecache.

But why only one working cache?  I added a spanish page and loaded it on the frontend and locked and edited it on the backend.  Still only have 1 working cache - is this correct behavior?
