### ISSUE TITLE
Can't flush the structure cache 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7701]
We need allow flush the structure cache, and this is not including in the caches drop-down in the maintenance --> cache  portlet 

![2015-05-07_1518](https://cloud.githubusercontent.com/assets/2641437/7526127/60724914-f4cc-11e4-8c78-2a8fd516f0fb.png)

Tested on the last 3.2 // H2 // FF

**Comment by oarrietadotcms** [comment]
@rogelio-blanco now that you are working on this, please fix this one also: https://github.com/dotCMS/core/issues/3765. It should be quick.

**Comment by rogelio-blanco** [comment]
Pull Request #7738

**Comment by rogelio-blanco** [comment]
Pull Request #7744 (refactor)

**Comment by jtesser** [comment]
the fix is done and is here but needs to be merged at some point into a release branch. We didn't want this in 3.2.1 so it is waiting for 3.5 or whatever

**Comment by jgambarios** [comment]
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/282

**Comment by bryanboza** [comment]
Fixed, now we have the content type cache in the list... Tested on 3.3 // Postgres // FF
