### ISSUE TITLE
BinaryExporterServlet not respecting DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE property

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7702]
The BinaryExporterServlet is not respecting the property DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE for file assets:

Working cases (As always the content is delivered regardless the language in session) :
```
http://demo.dotcms.com/contentAsset/raw-data/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043/fileAsset?byInode=true 
http://demo.dotcms.com/contentAsset/raw-data/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043/fileAsset?byInode=true&language_id=1 
http://demo.dotcms.com/contentAsset/raw-data/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043/fileAsset?byInode=true&language_id=2 

http://demo.dotcms.com/images/404.jpg 
http://demo.dotcms.com/images/404.jpg?language_id=1 
http://demo.dotcms.com/images/404.jpg?language_id=2 
```

**Not** working cases (And assuming the default language id is 1):
```
http://demo.dotcms.com/contentAsset/resize-image/4d7daefa-6adb-4b76-896d-c2d9f95b2280/fileAsset/w/373/h/178?language_id=2 
http://demo.dotcms.com/contentAsset/resize-image/4d7daefa-6adb-4b76-896d-c2d9f95b2280/fileAsset/w/373/h/178/v/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043?language_id=2 
```

Basically the content is not delivered when the language is not the default language and the content is requested by Identifier, even if the **DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE** property is set to true.

**Comment by jgambarios** [comment]
R&D I'm working on it as I need a fix for a client in support.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7704

**Comment by bryanboza** [comment]
Fixed, tested on  Nightly build 2015-05-12 // MySQL // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59170

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8001

**Comment by bryanboza** [comment]
Fixed
