### ISSUE TITLE
Workflow EscalationThread needs to be a stateful quartz job

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7703]
It is currently running on all servers and only needs to be run on one in a cluster.

**Comment by jtesser** [comment]
@oarrietadotcms this is easy just alter the interface.  Pretty safe change.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7758

**Comment by oarrietadotcms** [comment]
I replaced property with ESCALATION_CHECK_INTERVAL_SECS  with ESCALATION_CHECK_INTERVAL_CRON, now it uses a cron job, just like the other Quartz Jobs. 

Documentation needs to be updated here: http://dotcms.com/docs/latest/ScheduledEnabledWorkflow

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-19 19:53// Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Test case http://qa.dotcms.com/index.php?/cases/view/429

**Comment by DeanGonzalez** [comment]
documented: http://dotcms.com/docs/latest/scheduled-enabled-workflow
