### ISSUE TITLE
EscalationThread not working consistently

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7705]
This is on dotcms.com

## We have this workflow:
![screen shot 2015-05-08 at 11 17 48 am](https://cloud.githubusercontent.com/assets/934364/7539405/c90a9e7e-f574-11e4-8c44-70506ef9bb43.png)

## We have these contents in this workflow step that are not getting "escalated"
![screen shot 2015-05-08 at 11 19 40 am](https://cloud.githubusercontent.com/assets/934364/7539420/e1f3d072-f574-11e4-85f4-137b957386a9.png)

Here are the results of the SQL that the EscalationThread calls to find out if it needs to run:

```

dotcms=> select workflow_task.id from workflow_task join workflow_step on (workflow_task.status=workflow_step.id) 
dotcms.com_3x-> where workflow_step.resolved=false and workflow_step.escalation_enable=true and now()>workflow_task.mod_date+ 
dotcms.com_3x-> cast(cast(workflow_step.escalation_time as varchar(20))||' seconds' as interval) ;
 id 
----
(0 rows)

dotcms=> 
```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7771

**Comment by shayngr** [comment]
Fix is working.
Tested on:  3.2 Nightly build 2015-05-22 16:41/ Ubuntu 14.04 // Postgres // Firefox
SQL is showing appropriate results when calling EscalationThread

![escalationthread sql](https://cloud.githubusercontent.com/assets/8741846/7823255/77c86d60-03b7-11e5-9f8d-e28a821d3602.png)


It looks like contents in workflow step that are getting escalated according to workflow

![escalationthread_workflow task](https://cloud.githubusercontent.com/assets/8741846/7823406/79aa0c82-03b8-11e5-9fb5-0000adb22110.png)

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59165
