### ISSUE TITLE
Improvement to Date Formatting

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7707]
Right now there is only one backend format for Date & Date/Time fields

Month/Day/Year

However, many countries in Europe, South and Central America, etc., us the following format for dates:

Day/Month/Year 

This leads to Content Publishers constantly putting the wrong dates into content (even for our employees here in the Costa Rica office).  It would be great if the format could change based upon persona, role, or geographical region.  Format based on type of user logging in would be optimal here.

However, if that kind of responsiveness is too challenging, we should at least provide an option under System - Configuration (Maybe in the "Locale" section), that allows a webmaster to choose a default date format for all the back end/front end users.

In addition we need to remove all now()  do not rely on db etc..

**Comment by jkshapiro** [comment]
ISO 8601 FTW
