### ISSUE TITLE
Cannot add a new folder on host root with TRACE logging turned on

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7709]
Adding a new folder to the host via the site browser works fine with normal "INFO" level logging (the default setting).  When you change the logging level to "TRACE", you get the "Oops" screen.  Based on the catalina.out log file the "Ooops" screen is the result of a NullPointerException.

**Steps to recreate**
1. After dotCMS is installed and running, shutdown dotCMS
2. Edit ./dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/log4j/log4j.xml and replace all 15 occurances of "info" with "trace" - save changes
3. Edit ./dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/log4j.properties and replace INFO with TRACE - save changes
4. Restart dotCMS
5. Open site browser in backend
6. Right-click on host/site name and select "Add Folder"
7. Should now see "Ooops" page and see NPE in log file

Log file:  https://gist.github.com/brentgriffin/127efe9e31334fb19eee

Ubuntu 14.04.2 LTS // Java "1.7.0_80" // PostgreSQL 9.3 // dotCMS 3.2 Release

**Comment by maurizo** [comment]
Pull request: #7727

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-14 04:13 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/59164
