### ISSUE TITLE
Push Publishing fails with HTTP gzip compression enabled

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7711]
When using Push Publishing on servers that have gzip compression enabled on their HTTP Connectors or upstream proxies/load balancers, the push fails due to incompatibility. Push should work with http gzip without requiring additional connector workarounds, as this is a very common configuration due to Google PageRank site speed signals.

**Comment by wezell** [comment]
There is another part to this which is to enable gzip by defualt

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/144
