### ISSUE TITLE
Bug: Image uploading in TinyMCE editor

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7720]
To reproduce on demo.dotcms.com:

1. Open some existing news content
2. Click the image icon in TinyMCE and then browse (magnifying glass/folder icon)
2. Navigate to the demo site images folder
3. Click the upload new file button
4. Select a local image to upload
5. Click Save or Save and Publish.

Nothing happens.

The browser's Javascript console shows this error:
> ReferenceError: uploadFiles is not defined

**Comment by oarrietadotcms** [comment]
This dialog is the same used in this bug: https://github.com/dotCMS/core/issues/7659

Already fix in the next release. Duplicated.
