### ISSUE TITLE
XML Sitemap functionality - enterprise only?

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7724]
In 3.0 we incorporated the XML sitemap plugin into the product:  https://github.com/dotCMS/core/issues/4717

Our doc says this is an Enterprise only feature:  http://dotcms.com/content-management-system/enterprise-editions

Currently this functionality is fully functional in the community edition.  Either the doc needs to be updated or the functionality needs to be restricted.

**Comment by jtesser** [comment]
@wezell thoughts?

**Comment by wezell** [comment]
Uhh, yeah, I agree we need to fix the functionality.
