### ISSUE TITLE
Pages return 404 error on upgraded clients if CMS_INDEX_PAGE does not include page extension

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7725]
Reproduced in upgraded client from 2.5.6 to 3.2. 

Steps(for upgraded clients)
1. Upgrade a vanilla install of 2.5.6 to 3.2. It is not needed to apply a license after it's upgraded.
2. Make sure that the home page is still /home/index.html
3. Go to the page in Live mode. It returns a 404 error.

The workaround is to set the CMS_INDEX_PAGE to index.html so all index pages can be available in Live mode. This seems to be a problem with the current configuration since we already have a property for specifying the Page extension, which is VELOCITY_PAGE_EXTENSION. 

Is there any way to check that if the VELOCITY_PAGE_EXTENSION property is set, the CMSFilter concatenates both properties and see if the URI resolves to an existing index page? This would ensure that CMS_INDEX_PAGE deal only with the page name without an extension, which it's something that remains on upgraded pages even after an upgrade from 2.x to 3.x.

**Comment by brentgriffin** [comment]
Please refer to this issue:  https://github.com/dotCMS/core/issues/7598

**Comment by joseorsini** [comment]
@brentgriffin I was talking to @maurizo about that issue in the last few days. The referred issue deals about HTMLPages parsed as file_assets (legacy files) because of the HTMLPage extension configuration which is still required when a partial from 1.9 to 2.x is being done. In this case, the issue is slightly different because the DB objects are not changed to others because of missing configuration, but all index.html pages in an upgraded site (from 2.5.x) cannot be displayed because the CMS_INDEX_PAGE does not consider that pages created in 2.5.x come with a specific extension.

**Comment by dotcmsCodeReview** [comment]
This is on purpose, I believe.  If you have index.dot pages as your index
page, then that should be what you enter for the CMS_INDEX_PAGE value

**Comment by jgambarios** [comment]
It was on purpose but can be improve it using the CMS_INDEX_PAGE along with the VELOCITY_PAGE_EXTENSION (Example: CMS_INDEX_PAGE + "." + VELOCITY_PAGE_EXTENSION) instead of have to specified a extension for the index page when we already have a property for that, doing that would make the upgrade process simpler. 

This can be easily altered after an upgrade, but just saying that can be done as an enhancement.

**Comment by wezell** [comment]
As of 3.2  VELOCITY_PAGE_EXTENSION is not used in the system.  I think the better fix for this is to allow the CMS_INDEX_PAGE variable to take a comma delimited list of index pages that should be tried by the CMSFilter before throwing a 404

**Comment by jkshapiro** [comment]
+1 for the comma delimited list
