### ISSUE TITLE
The system continue trying to get the budle status after the bundle fails

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7726]
When you have a problem sending any bundle the system show fail and try again 3 times, but after that the system continue trying to connect with the other server to try to get the bundle status, and this generate a error in the log every 60 seconds and never finish to try... Maybe we need stop this process 

To recreate: 
- Configure your push publish environment with a non valid receiver server
- Try to push any file 
- After the system show failed in the bundle status remove the bundle from the pending tab in the publish queue
- Check your log... You will have the follow error every 60 seconds 

LOG: https://gist.github.com/bryanboza/6d6a6c5485561f5f40c5

Tested on 3.2 //  Postgres // Linux

**Comment by jtesser** [comment]
agreed after the third failure we should stop checking

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7812

**Comment by brentgriffin** [comment]
After three failed attempts, do we log any special information and/or send something to the notification center?  Just want to know the expected behavior here.

**Comment by oarrietadotcms** [comment]
It will not log anything besides what already was logging. Just that it will stop after the 3rd try. @brentgriffin is right, we should send at least a message to the notification center.

**Comment by shayngr** [comment]
Fix is working. Systems stops trying to get the bundle pushed after it fails 3 times.
Tested on:
Postgres
Ubuntu
Firefox
