### ISSUE TITLE
Insert/Edit Link" tool in TinyMCE editor is not showing a valid URL 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7729]
Related to #7632 

After the fix, now the system works fine if the link is to a html page, show the correct URL, but if you try to add a new link to any image we have the same problem and continue showing an invalid URL 
"/contentAsset/raw-data/a7e17f67-4e09-4e51-8275-cddd9f7094b5/fileAsset"

![2015-05-13_0940](https://cloud.githubusercontent.com/assets/2641437/7614480/3e343c18-f954-11e4-8ec9-e025d04b7819.png)

To recreate: 
- Create a contentlet with a WYSIWYG field.
- Click the "Insert/Edit Link" icon in the TinyMCE editor.
- Use the camera/search icon next to the "Url" (sic) field, and navigate to a image.

Tested on dotcms 3.2 // H2 // FF

**Comment by oarrietadotcms** [comment]
FWIW, this is the way is working on 2.x.

**Comment by bryanboza** [comment]
Maybe can be fixed with the #7664

**Comment by rogelio-blanco** [comment]
Pull Request #7786

**Comment by rogelio-blanco** [comment]
It seems that also solves #7702

**Comment by jgambarios** [comment]
#7702 is a different case.

**Comment by rogelio-blanco** [comment]
You're right :)

**Comment by bryanboza** [comment]
Fixed, tested on Nightly build 2015-06-05 // H2 // FF

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/59159
