### ISSUE TITLE
Site nav tool is not respecting multi-language pages when you reorder 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7730]
Related to #7678 

After the fix, now we are respecting the languages and we are showing just the pages that have versions in the logged in language.... But the problem now is when you try to reorder we continue showing separately the page version in different languages.... 

We have the nav bar to select the language, then we can use that to select in which language you want reorder.... Does not make sense the system show all the languages in the reorder because the system show only the logged language pages 

![2015-05-13_0958](https://cloud.githubusercontent.com/assets/2641437/7614860/de34ac14-f956-11e4-93c8-cc43b0993ef8.png)

To recreate: 
- Create a new folder and add a new page with english and spanish version 
- Create another page with the site nav template 
- Try to reorder the site nav tool 

Tested on dotcms- 3.2 // H2 // FF

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7754

**Comment by shayngr** [comment]
Tested on:  3.2 Nightly build 2015-05-19 19:53// Ubuntu 14.04 // Postgres // Firefox
