### ISSUE TITLE
Make page redirects 301

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#7732]
The page "Redirect Url:" should redirect as a 301 (moved permanently) and not a 300 (moved temporarily)

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7818

**Comment by jgambarios** [comment]
Check Will's comments in the pull request: https://github.com/dotCMS/core/pull/7989

**Comment by wezell** [comment]
We've gone back and forth on this, see:  #4555 I think we will need to do a little more work here
