### ISSUE TITLE
Cache conversion of Contentlet to HTMLPageAsset

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7733]
The conversion of a contentlet to an HTMLPageAsset is somewhat heavy as it has to make a full copy of the contentlet. 

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPIImpl.java#L149

 We do this on every page render and, in menus, for every menu item each time they are displayed, which has a negative impact on performance.  It really only needs to be done once.

We need to cache this conversion and invalidate it every time the page as contentlet is persisted.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7734

**Comment by bryanboza** [comment]
Fixed, tested as part of the performance testing
