### ISSUE TITLE
RoleFactoryImpl.doesUserHaveRole should return immediatly for system user

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7735]
Minor issue but a good performance change.  If we are querying if the system user has a role, return true  immediately rather than build lists and test against them.

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/business/RoleFactoryImpl.java#L553

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7734
