### ISSUE TITLE
Error with the incomplete requests

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7737]
Related to #7260 and #6520

When you are trying to open any html page the first time (from the database), the system is taking a lot of time, but if you try to lock for editing before the page is loaded, we are having not an WARN like in the #7260, now is an error....

To recreate: 
- Create a new html page 
- Before the page is loading the css, click to lock for editing 
- Check your log 

The problem is when the browser close the request without finish... 

LOG: https://gist.github.com/bryanboza/504e057b6ea147c1e049

Tested on dotcms-3.2 // MySQL // FF

**Comment by jtesser** [comment]
not really anything i think we will fix here. more of a training issue
