### ISSUE TITLE
The system never finish to load after clean caches in a cluster environment 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7743]
We are having a problem when you have a cluster environment configured, because if you are logged as Admin in one of the nodes and the other one is logged as limited user, if you clean the caches and then refresh the tab in the limited user the system never finish to reload....

To recreate: 
- In the node A login as Admin
- Create a new folder and set permissions to a limited user (Chris Publisher), create a new html page
- In the node B login as  Chris and lock the created page for edit
- Now from node A go to System --> Maintenance and clean all the caches 
- In node B refresh the tab 

You should have something like that, and never finish to load...
![2015-05-14_1345](https://cloud.githubusercontent.com/assets/2641437/7640275/81cc98d0-fa3f-11e4-8ab7-aeb74fa65443.png)

Tested on Nightly build 2015-05-12 // MySQL // FF

**Comment by bryanboza** [comment]
FYI: Here the log error: https://gist.github.com/bryanboza/53405bc28b09bab35ae3

**Comment by jtesser** [comment]
this sin't a bug i do not believe. I think the permissions do not exist on the host properly. if you click around not using F5 to refresh does it behave better

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/61332

**Comment by dsilvam** [comment]
Wasn't able to reproduce in latest distro (3.5)
