### ISSUE TITLE
Unable to execute scripting query in 3.2 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7745]
I already have enabled the config parameters in the dotmatketing-config.properties, have permissions over Scripting User, but when i try to make any scripting example i am unable to get results 

Config parameters: 
ALLOW_VELOCITY_SQL_ACCESS_TO_DOTCMS_DB=true
ENABLE_SCRIPTING=true 

The role key is Scripting Developer by default 

Tested on Nightly build 2015-05-12 // MySQL // FF

**Comment by jtesser** [comment]
this is working.  @bryanboza we tested.  Maybe your last modified user is missing the permission or you are not doing this in content.
