### ISSUE TITLE
Date problems in the Jenkins server 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7750]
We are generating new builds, but something wrong with the dates, the last Friday  we have the this nightly (Nightly build 2015-05-15) and the last ones have a previous date ( Nightly build 2015-05-14)...

Something wrong here...

http://screencast.com/t/rH3CMXW4l7

**Comment by jtesser** [comment]
not a big deal.  There were no commits but the distro was built at different times. With new commits it is right if you look now
