### ISSUE TITLE
Dashboard not taking pages as content into account

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7751]
For example, dotcms.com is saying we have 5 pages and none of them are the top pages:

![screen shot 2015-05-18 at 1 22 59 pm](https://cloud.githubusercontent.com/assets/934364/7686065/20f301b4-fd61-11e4-951e-02226a828d93.png)

![screen shot 2015-05-18 at 1 22 55 pm](https://cloud.githubusercontent.com/assets/934364/7686068/235bcd00-fd61-11e4-97d9-dbe3708bc122.png)

**Comment by rogelio-blanco** [comment]
PR #7828
PR dotCMS/enterprise-2.x#279

**Comment by shayngr** [comment]
Fix is working. Tested directly thru running dashboard_data_generator.jsp
Tested on dotcms 3.3 build // Win7 Pro SP1 // SQLServer 2012 // Firefox
