### ISSUE TITLE
Unable to reorder workflow sub-actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7757]
Steps to reproduce:

- Create a Test Workflow Scheme with only one step and more than 2 Sub-actions.
- Try to reorder 
- Save the changes 
- Go back and try to edit again 

You can't see the changes, If you make the follow query directly in the database we have a problem in the my_order column....

If you add three actions, then delete one, and add another one you will see that: 
```
select id, name, my_order from  workflow_Action_class where action_id = '$action_id' order by my_order asc;

                  id                  |        name         | my_order 
--------------------------------------+---------------------+----------
 69089ccd-303b-4e8f-90df-b1bad764cec2 | Notify Assignee     |        0
 60c9e4df-1035-43ff-a317-c6bb777e7e23 | Unlock content      |        2
 a1960972-d30c-412f-9e10-f8d1eebe4bfc | Comment on Workflow |        2
 ```

We have two actions with the same order number...

Tested on 3.2 // Postgres // FF

**Comment by rogelio-blanco** [comment]
PR #7799

**Comment by rogelio-blanco** [comment]
I found an issue when the user add a sub-action

**Comment by rogelio-blanco** [comment]
The issue found is also in demo, so we are going to add a new ticket #7801

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7987

**Comment by bryanboza** [comment]
Fixed, now you can reorder sub-actions.... Tested on 3.3 // Postgres // FF
