### ISSUE TITLE
Enhancement: Better handling of Permissions from Cache

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7759]
Reported in client running 2.5.6. 

Contents don't seem to be cached at some point. Our current Cache classes handle getting permissions over assets this way:

1. If nothing is in cache, it returns an empty list. If there's a problem with getting permissions from cache, it returns a null object.
2. Permissions' factory class ask if anything pulled from cache is null, if so, it adds the content to cache.

The problem seems to be if the content has no permissions (for any reason) and therefore it's not added to cache, even if it's a new version of an existing content. This problem goes away with flushing all caches, which is not required every time an user edits contents.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7764

**Comment by bryanboza** [comment]
Fixed, tested on 3.3
