### ISSUE TITLE
Documentation: Clarify licensing

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7760]
The pages http://dotcms.com/products/java-cms/, http://dotcms.com/products/java-cms/licensing/, and http://dotcms.com/pricing/dotcms-server-pricing.dot are missing key information. Specifically, they don't include prices, and they don't discuss (or, in their current form, even mention) the distinction between a development server and a production server.

**Comment by jtesser** [comment]
not an issue Kivi as this is for dotcms product bugs etc...  Also this is a business decision for dotcms.
