### ISSUE TITLE
Search is not working for Youtube widget

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7762]
When you create a new Youtube widget, it does not find the video according to the search criteria.

Steps to reproduce
1- Create a new page
2- Go to Add content and add a Widget
3- Select Youtube > Create New Youtube button
4- Type in any word in the search field and hit "Search" button.
You will see it's not searching on Youtube

Video capture: http://screencast.com/t/fuUjlpLAJb
No errors on logs

Tested on:  3.2 Nightly build 2015-05-19 02:05 // Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
@fishsmith I think this is because of the youtube API update

**Comment by bryanboza** [comment]
Duplicated #7856
