### ISSUE TITLE
Enhancement: Push Language definitions and their associated variables

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7770]
Re: https://my.dotcms.com/ticket/dotcms-35

Steps to reproduce:

1. Set up two servers running 3.2 and configure a Push Publishing environment.

2. Created French-France language in Sender side and added a Language Variable: Hello-World=Bonjour, Monde.

3. Added "Hello-World" language variable to English-US language.

4. Created a Test content in Sender side and pushed it. 

Only English-US Language variable was pushed because French-France Language does not exist in Receiver side. So far, the LanguageHandler does not create new languages upon a Push Pub task. There's a property called

PUSH_PUBLISHING_LANGUAGE_FILE_FLUSH_CACHE

which it's set to false by default, that clears the Language cache and delete all cached Language keys when the LanguageHandler is invoked. However, this does not deal with new Languages and their variables.

**Comment by joseorsini** [comment]
Update, testing 3.2.1.

Language Properties files seem to be added to a bundle only when a Language Property was added to a Language. 

Results from 4 different tests: 

1. Added properties to English - US and Español - España languages, then pushed the demo.dotcms.com.

Bundle generated in Sender side:
{code}
2015-07-13 11:39:08,914 INFO  com.dotcms.publisher.pusher.PushUtils - Compressing 1 to /Users/joseorsini/dotCMS/releases/3.2.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0/../0a4c9ca7-c96b-4248-977e-7fa0fa5882a0.tar.gz
{code}

Language-related files within the bundle:
{code}
MacBook-Pro:3.2.1-dist joseorsini$ find dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0 -name '*.properties'
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0/messages/cms_language_en.properties
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0/messages/cms_language_en_US.properties
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0/messages/cms_language_es.properties
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/0a4c9ca7-c96b-4248-977e-7fa0fa5882a0/messages/cms_language_es_ES.properties
{code}

2. Edited only one language (English - US) and pushed demo.dotcms.com host.

Bundle generated in sender side:
{code}
2015-07-13 11:42:08,713 INFO  com.dotcms.publisher.pusher.PushUtils - Compressing 1 to /Users/joseorsini/dotCMS/releases/3.2.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/d4fba776-8d98-4acd-96d8-c060990fd11b/../d4fba776-8d98-4acd-96d8-c060990fd11b.tar.gz
{code}

Language-related files within the bundle
{code}
MacBook-Pro:3.2.1-dist joseorsini$ find dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/d4fba776-8d98-4acd-96d8-c060990fd11b -name '*.properties'
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/d4fba776-8d98-4acd-96d8-c060990fd11b/messages/cms_language_en.properties
dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/d4fba776-8d98-4acd-96d8-c060990fd11b/messages/cms_language_en_US.properties
{code}

3. Created a test page (/about/test page) and pushed only the page. No Language-related files were added to the bundle. 

4. Created a test page (/about/test-2 page) and pushed the entire demo.dotcms.com host. No Language-related fields were added to the bundle. 

5. Added content to /about/test-2 page and call a Variable from English Language:

{code}
<h2>Test Language Variables Push</h2>
Variable: Test-001
<br>
Value: $text.get("Test-001")
{code}

Language properties were not added to the bundle

--

I think that, in addition to the ability of pushing Languages and their Variables, just like any other asset available in Website Browser, we should include the properties files in each bundle. Chances of clients calling language properties through Velocity Viewtools calls should be considered, just like in the test 5 from above.

**Comment by bravous** [comment]
When we rollout a new bundle the bundle does not always contain the properties with the languages (translations). There are two possible solutions to this problem, making the product more consistent and trustworthy (and give more control to the maintainers).

1. Always add the language properties to the bundle. This wil prevent manaually copying the properties to all servers and garantee what we publish is complete.

2. Allow manually adding the properties to the bundle. This is basically the same as youn already support for plugins.

Hope you can add this in the next minor release.

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/97
