### ISSUE TITLE
Error showing when clicking on What's Changed

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7772]
When you edit a page and then want to see the changes  by clicking on "What's Changed?", it throws an exception.

Steps to reproduce:
1- Login with admin
2- In the site browser, go to folder about-us > what-we-do. Open the page in preview
3- Lock the page for editing and modify the text. Save it
4- Go to Preview tab and click What's Changed? You will see the error in the logs

Logs: https://gist.github.com/shayngr/b17613cd1a95a079b504

Video capture: http://screencast.com/t/q4qvE0MMH69

Tested on:  3.2 Nightly build 2015-05-21 18:42// Ubuntu 14.04 // Postgres // Firefox

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7778

**Comment by bryanboza** [comment]
Fixed, tested on Nightly build 2015-06-05 // H2 // FF
