### ISSUE TITLE
Unable to re-order related content

### ISSUE THREAD

**Issue by hmboonstra** [dotCMS/core#7777]
We have two structures with a 1-N relationship between them (Theme - Category). When I reorder the related categories in the theme content and save the tree_order rows in the tree table gets updates accordingly. But when I re-edit the same theme, the categories appear in a different order and when I pull the related categories using the $dotcontent velocity tool they are returned in the same (but wrong) order. Also when I query the relation index using the Query Tool in the admin the wrong order is returned, e.g:

**query**:
```
+type:content +Theme-Category:83098938-b6e2-4a5b-abcf-54bab498a815 +(conhost:d2b6560f-54e5-4aac-a705-640d2bfc7c1d conhost:SYSTEM_HOST) +languageId:1 +live:true  +deleted:false
```
**sort**:
```
Theme-Category-83098938-b6e2-4a5b-abcf-54bab498a815-order
```

Re-indexing and flushing caches does not help.

**Comment by jtesser** [comment]
what version is this?

**Comment by hmboonstra** [comment]
My bad: dotCMS version 3.2

**Comment by jtesser** [comment]
So I do not think this is a bug.  See my video http://screencast.com/t/1qqe9Bdq8

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/issues/6753 Related

**Comment by jtesser** [comment]
@joseorsini Not really related.  The other is only a push issue

**Comment by joseorsini** [comment]
@jtesser See the ticket I linked. It has nothing to do with Push Pub. This one does https://github.com/dotCMS/core/issues/7582

**Comment by fitzciaran** [comment]
We also have this issue - http://www.youtube.com/watch?v=jVMgttcFlIA 
Relationship Name is SupportVideo-SupportVideoDescriptionBulletPoint 	
Parent Content Type is Support Video 	
Child Content Type is Support Video Description Bullet Point 
Cardinality is 	M-N 	
Parent Required is No 
and Child Required is No

Running on DotCMS 3.2.3

hmboonstra did you get a solution for this?

**Comment by hmboonstra** [comment]
There was corrupt data in the tree table because we changed the relationship type from M-N to 1-N after data was already inserted. We cleaned up the table and our problem was solved.

**Comment by fitzciaran** [comment]
Thanks
