### ISSUE TITLE
Problems with the templates access in WebSphere v8.5.5

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7780]
After the fix #7668, now we can start the server without problems, but i am having an access error after create a new page, I have the error 500, and in the log have a template access error....

Here the log: https://gist.github.com/bryanboza/f73ff2ccb3ef84106356

Tested on master // Web Sphere v8.5.5 // Postgres

**Comment by maurizo** [comment]
The mail.jar file was missing on the "lib" folder.  The mail jar is required by the ServletToolboxManager process, if the jar is missing the toolbox.xml file loading fails.  The documentation on http://dotcms.com/docs/latest/DeployDotCMSAsAWarFileInWebSphere does includes this step, so no change needed.
