### ISSUE TITLE
Usability issues coying and pasting pages

### ISSUE THREAD

**Issue by SteveChalastra** [dotCMS/core#7781]
Let's say your parent folder is "about-us" and child folder is "careers". Child folder contains "index.html" that you now want to rename to "careers" and move to "about-us". Copy action works but Paste action does nothing. Initial assumption is that it's broken in the latest release. So you go into Page Properties and try to select the new host/folder target that way. This time you get a message "Another folder with the same URL exists in this folder". 
1. The message should say "another object" as you're working with a page, not a folder.
2. A similar message should appear on an attempt to paste into the parent folder rather than just leaving the user puzzled.

**Comment by rogelio-blanco** [comment]
Seems to me that this is it also related with #7816

**Comment by jkshapiro** [comment]
And #8153

**Comment by jkshapiro** [comment]
And maybe #8155
