### ISSUE TITLE
Follow on to #7781

### ISSUE THREAD

**Issue by SteveChalastra** [dotCMS/core#7782]
See https://github.com/dotCMS/core/issues/7781. You rename the child folder to "about-us2" and move the page to the parent folder. Forgetting that you now have a page of the same name in the parent folder, you try to rename the child folder back to "about-us" and get the message "You can't delete a Language that is being used by Content", together with an Unexpected System/Hibernate error.

**Comment by rogelio-blanco** [comment]
Seems to me that this is it also related with #7816

**Comment by jkshapiro** [comment]
And maybe #8153 and #8155
