### ISSUE TITLE
Unable to search html pages by URL in 3.2 after upgrade from a previous version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7783]
We are having a problem searching pages by URL when you upgrade from a previous dotcms version to 3.2.... The system is not showing results 

To recreate: 
- Start a dotcms 2.5 version
- Apply the license code  
- Create some assets and create some html pages 
- Shutdown the server 
- Copy the asset folder to the 3.2 instance 
- Configure to use the same database 
- Start the 3.2 version 
- Migrate one of the legacy html pages to content page
- Go to content tab, and try to search this page by url 

Here the SC: http://screencast.com/t/l2MN9gf7Lvs   ///   http://screencast.com/t/o4UfAzomR8X

Tested in a fresh installation of dotCMS and works fine, the problem is in the upgraded version

Tested on nightly build 2015-05-26  // Postgres // FF   -- > Upgraded from 2.5

**Comment by bryanboza** [comment]
FYI: If i create a new content page after the upgrade, neither works, then is not a page migration problem

**Comment by oarrietadotcms** [comment]
This is related to this one: https://github.com/dotCMS/core/issues/7476

The URL is no longer stored under the contentlet, just in the identifier.

**Comment by oarrietadotcms** [comment]
@jtesser As url is not longer part of the contentlet data, I could do a lucene query without that value and then filter it with java. Do you agreed with this solution? Because it is weird to start mixing search methods (lucene + java/cache/db). Let me know what you think

**Comment by oarrietadotcms** [comment]
At the end I added the proper value to the index, using url from identifier and not from contentlet.

PR: https://github.com/dotCMS/core/pull/7825

**Comment by bryanboza** [comment]
Fixed, tested on Nightly build 2015-06-05 // H2 // FF
