### ISSUE TITLE
Integrity conflict with the theme folder after upgrade to 3.2 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7785]
We are having an integrity conflict when you upgrade from a previous version to 3.2, the problem here is when you try to make a push publish, you need fix the conflicts first, if you fix the conflicts in the local node the system is changing the identifier of the theme folder, then when you try to open a page preview, we are having an error: "Identifier is null" 
![2015-05-27_1131](https://cloud.githubusercontent.com/assets/2641437/7843183/2826e77e-0465-11e5-860b-161f20514ff9.png)

Here the log: https://gist.github.com/bryanboza/5ca6782f01f9263c145d
And here the system is showing an error 500, when you open a page preview ....

Sender: Nightly build 2015-05-26  // Postgres // FF --> Upgraded from 2.5 
Receiver: Nightly build 2015-05-26  // Postgres // FF // Linux

**Comment by jtesser** [comment]
I think here @bryanboza you need to fix remote and then push including the template

**Comment by brentgriffin** [comment]
Forcing to fix on remote is problematic - user should be able to chose whether to fix local or remote.  If this is not the case, the documentation needs to outline the caveats.  This is problematic since once they fix it locally, it is broken and not easy for the user to fix.

**Comment by jtesser** [comment]
@brentgriffin it does fix.  We don't hunt template code down. In this case it will update the inode/identifier to the side you are asking. It isn't a bug really. We can talk if you want

**Comment by bryanboza** [comment]
The same situation if the receiver side is the upgraded side and if you fix the conflicts here, you will break the existing pages... because you are changing the identifier

**Comment by jtesser** [comment]
right so you have to push the template. Again we don't search and replace velocity code for replaced identifiers etc...

**Comment by bryanboza** [comment]
Not sure... For me i think we need add some exception here, because if you don't know this and fix the conflicts, you can break the server, because after do that, when you create a new page, have the same problem, after reindex and clean caches the problem continue.... Not sure how to fix that if you make this by error....

**Comment by jtesser** [comment]
You need to push the template or edit the pages template.

**Comment by bryanboza** [comment]
Maybe we need take a look over this case.... 

Talking with @jtesser, then we need fix the conflict on a remote side and then we can fix the problem pushing again the templates.... This just to update the identifiers 

But when you try to push the templates, after fix the conflicts, we are having another error and then you never can fix the error caused by fix the conflicts on remote

Here the error: https://gist.github.com/bryanboza/0d5f03cabbc38eff09c7

The same thing if you try to push any page, content, ect.....

Both servers are running the same nightly build, and both in Postgres

**Comment by brentgriffin** [comment]
I am able to recreate Bryan's scenerio

1.  Setup authoring server using 2.5.7
2.  Upgrade authoring server to 20150528 nightly build of 3.2.1
3.  Apply trial license to authoring server
4.  Setup receiving server with 20150528 nightly build of 3.2.1
5.  Apply trial license to receiving server
6.  Configure push/pub environment on authoring server
7.  Configure push/pub receiving on receiving server
8.  On authoring server run integrity checker and "fix at remote node" the three folder conflicts
![image](https://cloud.githubusercontent.com/assets/3208956/7920065/1617aff4-0862-11e5-901b-c2518b1791ad.png)
9.  On authoring server re-run integrity checker and verify that no conflicts remain
10.  Push demo.dotcms.com host from author server to receiving server - notice error in UI and in the receiving server log
![image](https://cloud.githubusercontent.com/assets/3208956/7920087/32b33926-0862-11e5-89cc-d31a098c09aa.png)

Authoring server log:  https://gist.github.com/brentgriffin/06a36d4d7620cb88dd7e
Receiving server log:  https://gist.github.com/brentgriffin/2b76456a664702d61520

Authoring server:  OSX 10.10.3 //  Java 1.7.0_71 // Postgres 9.3 // Chrome
Receiving server:  Ubuntu 14.04.2 LTS // Java 1.7.0_80 // Postgres 9.3 // Chrome

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/75
