### ISSUE TITLE
Images are not displayed in a Generic Content if it's in a different language than English

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7787]
If an image is added to a generic content and the generic content is in a foreign language (i.e. german), when you add the generic content to a page in the same foreign language (i.e. german), the image is not showing
 
To reproduce:
1- Login with admin
2- Go to Content tab >  Content Search
3- Create a new Generic Content in a language different than English (i.e. german)
4- Add an image to WYSIWYG and save it
5- Create a new page in the same language you have created the generic content (i.e. german)
6- Add the the new generic content you created
You will see that the generic content is not showing the image 

screencast: http://screencast.com/t/cs7EAZYV

Tested on:  3.2 Nightly build 2015-05-26 18:42/ Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
solved with https://github.com/dotCMS/core/issues/7729 both fixed in 3.2.1

**Comment by bryanboza** [comment]
Fixed, tested on Nightly build 2015-06-05 // H2 // FF
