### ISSUE TITLE
Push Publishing: Pushing a host fails when Live and Working versions are different.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7788]
Reproduced in 3.2 and also in client running 2.5.6. 

Steps:

1. Create a Push Publishing environment (two standalone servers) with default 3.2 installs.
2. In Sender side, create a test folder in demo.dotcms.com Site and add a test Page to this folder.
3. Go to Sites portlet and edit the demo.dotcms.com site. Add "demo.dotcms.com" as an alias (at this point you can edit any field) and then click on "Save". This will deactivate the host and it will have different live and working versions. 
4. Go back to the Website Browser and Push the folder created in Step 2. 

Stack trace from Receiver side: https://gist.github.com/joseorsini/00486fd0afaa3f9f5d31

Related to ticket: https://my.dotcms.com/ticket/dotcms-40

**Comment by wezell** [comment]
Thanks for putting this in Jose!

**Comment by jtesser** [comment]
Well wait. @joseorsini can you be more specific.  On step 3 are you on the sender Also on that step why add an alias that was already the host name?

**Comment by wezell** [comment]
The case is when the sender's host contentlet has a live and working
version that are different (there is a edited version of the host content)
and the receiver does not have the working version inode.

**Comment by joseorsini** [comment]
@jtesser: What @wezell said. In Step 3, the host edition is made in the Sender side, and as I said, you can change anything on the Host, like the Tag Storage or the Run Dashboard fields. The thing is to create a new version but not publish it immediately. 

This issue might affect contents tied to Workflows as well.

**Comment by maurizo** [comment]
Core PR: #8064
Enterprise PR: #284

**Comment by bryanboza** [comment]
Nee fix the issue #76 on mingle to test

**Comment by levosgien** [comment]
cards/93
