### ISSUE TITLE
Tomcat 8 org.apache.tomcat.jdbc.pool locks up with too much concurency

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7790]
To reproduce:

1. Start a fresh dotCMS up from the command line.
2. Run: `ab -n 10000 -c 50 http://localhost:8080/`  Do not hit a page via a browser.  This will inevitably lock the server up.  

This cannot be reproduced in dotCMS 3.0.1, which used Tomcat 7 and the apache  commons dbcp.

If you take a threaddump, you see a blocked thread here:
```
"url:GET//demo.dotcms.com/ | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:false | start:05-28-2015 01:21:02 EDT" daemon prio=5 tid=0x00007fa5c52db000 nid=0x14503 waiting on condition [0x000000011ae40000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000074492d898> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at org.apache.tomcat.dbcp.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:582)
	at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:439)
	at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:118)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1412)
	at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:86)
	at com.dotmarketing.db.HibernateUtil.getSession(HibernateUtil.java:630)
	at com.dotmarketing.db.HibernateUtil.setQuery(HibernateUtil.java:186)
	at com.dotmarketing.business.IdentifierFactoryImpl
```

see https://gist.githubusercontent.com/wezell/1a8a3745e511ab5a14b0/raw/gistfile1.txt

**Comment by jtesser** [comment]
In addition while I don't think this is the issue we should add a UtilMethods.isSet to the permissionId here to account for empty string 

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/business/PermissionBitFactoryImpl.java#L1218

**Comment by wezell** [comment]
` ab -n 10000 -c 50  http://localhost:8080/`

**Comment by wezell** [comment]
This behavior can be fixed by changing/reverting tomcat's connection pool to use apache commons dbcp2 again.  This can be done by specifying `factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory" ` in the Context resource

```
    <!-- H2 -->
    <Resource name="jdbc/dotCMSPool" auth="Container"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory" 
              driverClassName="org.h2.Driver"
              url="jdbc:h2:WEB-INF/H2_DATABASE/h2_dotcms_data;MVCC=TRUE;LOCK_TIMEOUT=15000"
              username="sa" password="sa" maxActive="60" maxIdle="10" maxWait="60000"
              removeAbandoned="true" removeAbandonedTimeout="60" logAbandoned="true"
              validationQuery="SELECT 1" testOnBorrow="true" />
```

**Comment by jtesser** [comment]
also here is another case https://my.dotcms.com/ticket/mwu-6

**Comment by brentgriffin** [comment]
FWIW - i have tried this setting locally and does not seem to work for me.  According to this doc:  https://tomcat.apache.org/tomcat-8.0-doc/config/systemprops.html

This value "org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory" seems to be the default value if no factory setting is present.

Locally, I was testing 3.2 official release with postgres on ubuntu 14.04

**Comment by brentgriffin** [comment]
Additional research needed but using this value for the factory setting seems like it is working:  "org.apache.tomcat.jdbc.pool.DataSourceFactory"

Pulled that from here:  https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html

**Comment by jtesser** [comment]
Yes I think @wezell copy/pasted the wrong value we were playing with in this task
