### ISSUE TITLE
Cannot see the option to reorder menu links when you "show on menu" several folders

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7792]
When you have about 5 folders that show on menu, you cannot see the option to reorder menu links in  preview mode.

To reproduce:
1- Login with admin
2- In the site browser, create a folder and create a new page inside that folder. Choose the template -2 column w/ Side Nav- and save/publish it. Both the folder and page should show on menu
3- In addition add at least 2 menu links to the folder and save/publish. They should also show on menu
4- Create 4 more folders in the site browser and show on menu
5- Open the page in Preview.
The issues happen:
1- The menu links are not displaying properly
2- If you click Lock for Editing, you will NOT see the Reorder Links Menu option

![reorder menu option](https://cloud.githubusercontent.com/assets/8741846/7865717/edd925b4-0527-11e5-84ca-16dba3128359.png)

Tested on:  3.2 Nightly build 2015-05-26 18:42/ Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
this is really related to the starter CSS not really a bug by us.  We can do some things possible to prevent  in edit mode but in this case client's css will always be able to mess with it. 

We will be redoing edit mode and making more modal in the future this should address things like this
