### ISSUE TITLE
Unable to edit child folder name

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7793]
To reproduce:
1- Login with Admin
2- In Site Browser, create a parent folder
3- Inside the parent folder, create a child folder
4- Right click on the child folder > Edit Folder. Change the name and save it
The system will not allow you to change the name and will display a message: "Folder already exists. Please enter a different name"

No errors in logs

Tested on:  3.2 Nightly build 2015-05-26 18:42/ Ubuntu 14.04 // Postgres // Firefox

**Comment by rogelio-blanco** [comment]
PR #7804

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // postgres // FF
