### ISSUE TITLE
Java NPE trying to update the audit table in Web Sphere 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7795]
We have the follow error in the log when you try to push any content after fix conflicts 
```
[28/05/15 16:14:19:034 CST] ERROR receiver.BundlePublisher: Unable to update audit table : null
java.lang.NullPointerException
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:197)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
```
 To recreate: 
- Configure your push environment 
- Create manually one folder with a page in to it 
- Run the integrity checker 
- Fix the conflicts in the remote node 
- Now go to sender side and modify the page name and add a new content to the page 
- Try to push the page again 

You will have this error on the receiver log... 

Tested in a single tomcat instance and works fine, and tested with multiple data bases too... I have the problem only with the WS server...

Sender: Tomcat // H2 // Nightly build 2015-05-26
Receiver: WS // postgres // Nightly build 2015-05-26

**Comment by maurizo** [comment]
Could reproduce it on last friday's nightly build but not anymore.

**Comment by bryanboza** [comment]
Fixed, tested on dot_3.3 // WS v8.5 // Postgres
