### ISSUE TITLE
No info message when cut/paste file asset to folder with allowed file restriction

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7797]
If you have a folder with file extension restriction and cut/paste an object from another folder, there is not any info message saying the action is not allowed (as it is when you do copy/paste from another folder)

To reproduce:
1- Login with admin
2- In the site browser, create a new folder and specify in the properties any allowed file extension, i.e.: *.txt
3- Cut/paste a document, video, file asset, etc (which extension is not .txt) from another folder into this new folder you have created. You will see the action is not executed, however is missing the info message "The file does not match the filters specified by the folder". If you do Copy/Paste, that message is showing appropriately

Logs: https://gist.github.com/shayngr/51c6db46ebcbe7c76558

Tested on:  3.2 Nightly build 2015-05-28 10:42/ Ubuntu 14.04 // Postgres // Firefox

**Comment by wezell** [comment]
Can be addressed with site browser redesign
