### ISSUE TITLE
"Copy an existing site" does not place content on pages

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7800]
To replicate in demo.dotcms.com:
1. In the "System" menu, go to Sites.
2. Click the "Add Site" button.
3. Choose to "Copy an existing site".
4. Finish creating the new site.
5. In the "Site Browser" menu, go to "Site Browser".
6. Change the site to the new site.
7. Open any HTML page. It does not contain content.

**Comment by jkshapiro** [comment]
Similar to #7517

**Comment by jtesser** [comment]
I need to look but @jkshapiro are you sure you had all checkboxes checked.

**Comment by jkshapiro** [comment]
I had the "All" checkbox checked.
![capture](https://cloud.githubusercontent.com/assets/3178838/8333497/343a0732-1a61-11e5-809e-44e1b54e5134.PNG)

**Comment by wezell** [comment]
done #8270
