### ISSUE TITLE
Unable to reorder workflow sub actions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7801]
Related to #7757 

We have problems trying to reorder workflow sub actions, after add a new sub action...

To recreate:
- Create a new workflow 
- Add a new action 
- In the sub actions drop-down add almost three
- Reorder the sub actions
- Now add a new one 
- Try to reorder again

The reorder does not working after add the forth sub action 

SC: http://screencast.com/t/Vqvgo3lMX

Tested in the last nightly // Postgres // FF

**Comment by rogelio-blanco** [comment]
Fixed in #7757

**Comment by bryanboza** [comment]
duplicated with #7757.... Fixed
