### ISSUE TITLE
Editing an Event type contentlet throws a null pointer exception

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7803]
1. Go to Content Types
2. Add to the structure **Event** a **Text Area** field
3. Go to content and try to edit any contentlet of type **Event**

An **"Ooops, sorry. This has caused a problem"** is displayed on screen and this is the error on logs: https://gist.github.com/jgambarios/0836327ec5cd418aeb67

The problem is after this line https://github.com/dotCMS/core/blob/master-3.2/dotCMS/html/portlet/ext/contentlet/field/edit_field.jsp#L139 We need to check if **contentletForm != null**.

**Comment by jgambarios** [comment]
I was able to reproduce in demo.dotcms.com and latest 3.2

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7887

**Comment by bryanboza** [comment]
Fixed, tested in master-3.2 and now works fine after add the field....
