### ISSUE TITLE
Relationships: "Relate Content" Window needs some minor adjustments.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7808]
Despite the "Relate Content" only shows 10 paginated results, we have to scroll down in order to find the "Relate" button, and at this moment, this window cannot be resized. 

![screen shot 2015-06-02 at 10 55 30 am 2](https://cloud.githubusercontent.com/assets/1717110/7938923/29576a78-0916-11e5-904e-83ebe4a5b20a.png)

Additionally, once you scroll down, the text overflows and the "Matching Results (x)" can be read in the window's grey header.

![screen shot 2015-06-02 at 10 55 35 am 2](https://cloud.githubusercontent.com/assets/1717110/7938924/2b3eaef0-0916-11e5-9f8e-71a75e20e073.png)

It would be nice to have more controls of the paginated results, just like in the Content Search Manager (showing links to pages 1, 2, 3 and so on...)

**Comment by rogelio-blanco** [comment]
Also, the "Relate" button should has a "disk" icon representing a "save" action

**Comment by wezell** [comment]
Also:
* Language should be defaulted to current language (use the same logic as the content search screen)
* The "all" search box should be there as well

**Comment by wezell** [comment]
@gabbydotCMS where are we with the customer on this?
