### ISSUE TITLE
Relationships: Index is not updated when a related parent content is deleted

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7809]
Reproduced in demo.dotcms.com, running 3.2. Steps:

1. Create a Blog Content.
2. In its frontend View, add 4 comments.
3. Check in Backend that the recently created Blog Entry has its 4 contents related, and check as well that each created Comment is related to this Blog Entry.
4. Go to one of the Comments and delete its parent relationship with the Blog Entry. Save and Publish.
5. Open the comment again and you will see the Relationship is still there. 
6. Open the Blog Entry and the Relationship was deleted. 

Screenshots and Database info:

- Blog Entry with Comments before deleting the Parent relationship.
![screen shot 2015-06-02 at 11 04 13 am 2](https://cloud.githubusercontent.com/assets/1717110/7939351/992b3c2e-0918-11e5-9c3d-540679fa233c.png)

- Comment before deleting the Parent Relationship.
![screen shot 2015-06-02 at 11 04 17 am 2](https://cloud.githubusercontent.com/assets/1717110/7939356/a1b4d940-0918-11e5-8b1e-c3d9b8884205.png)

Database info of Blog-Comment relationship for content which parent relationship is going to be deleted:
```
3.2-dist=# select contentlet.title, contentlet.text1, contentlet.text2, contentlet.text3, tree.parent, tree.tree_order from contentlet, tree, contentlet_version_info where contentlet.identifier = tree.child and tree.child = 'f34e3631-915b-4f3b-b423-0b37c7b88c1c' and contentlet.inode = contentlet_version_info.live_inode;
  title   |  text1   | text2  |        text3        |                parent                | tree_order 
----------+----------+--------+---------------------+--------------------------------------+------------
 Comments | Comments | system | Jonathan Gamba-Rios | d08391e0-d638-43f0-91a1-e49f7699ee88 |          4
```

- Blog Entry Relationships after the relationship was deleted.
![screen shot 2015-06-02 at 11 05 06 am 2](https://cloud.githubusercontent.com/assets/1717110/7939393/dd4bfb82-0918-11e5-9a21-71287a5ab98f.png)

- Comment Relationships after it was deleted, saved and published, and then checked out
![screen shot 2015-06-02 at 11 05 10 am 2](https://cloud.githubusercontent.com/assets/1717110/7939412/f6af39e0-0918-11e5-8449-4f53d8dd6392.png)

Database info after relationship was deleted:
```
select contentlet.title, contentlet.text1, contentlet.text2, contentlet.text3, tree.parent, tree.tree_order from contentlet, tree, contentlet_version_info where contentlet.identifier = tree.child and tree.child = 'f34e3631-915b-4f3b-b423-0b37c7b88c1c' and contentlet.inode = contentlet_version_info.live_inode;
 title | text1 | text2 | text3 | parent | tree_order 
-------+-------+-------+-------+--------+------------
(0 rows)
```

Note: The problem goes away by reindexing, however, Index should be automatically updated once the relationship is dropped and the Comment is saved and published.

**Comment by rogelio-blanco** [comment]
PR: #7961

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // postgres // ff
