### ISSUE TITLE
Invalidate single user does not work properly

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7810]
Logged in as Admin, when you try to invalidate a single user, the system logs out the Admin user instead of the selected single user.

To reproduce:
1-Log in as Admin 
2-Go to System > Maintenance > Logged Users tab
3-Use 3 different browsers (FF, Chrome, Safari) to log in as 3 different users, i.e.: Admin, Bill and Chris
4-As Admin user, click Reload Users button in order to see the users currently logged in
5-Click "Invalidate" button next to a single user
You will see the system logs out the Admin user instead of the selected single user and actually remains  logged in.
"Invalidate All" button does work fine

Video capture: http://screencast.com/t/T1GDoDjoB

Logs: https://gist.github.com/shayngr/9324b3551e04735cd597

Tested on:  3.2 Nightly build 2015-06-01 16:15/ Ubuntu 14.04 // Postgres // Firefox, Chrome and Safari

**Comment by rogelio-blanco** [comment]
PR #7941
