### ISSUE TITLE
"\n" is showing in confirmation message

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7811]
To reproduce:

1- Login as admin
2- Go to System> Maintenance> Tools. Scroll dow to Fix Assets Inconsistencies and select "Execute"
You will see "\n" is showing in confirmation message

![n in confirmation message](https://cloud.githubusercontent.com/assets/8741846/7939784/02aad3a8-090a-11e5-8c29-ea811c2f3a4d.png)

Tested on:  3.2 Nightly build 2015-06-01 16:15/ Ubuntu 14.04 // Postgres // Firefox

**Comment by rogelio-blanco** [comment]
PR #7822

**Comment by bryanboza** [comment]
Fixed, tested on master-3.2 // Postgres // FF
