### ISSUE TITLE
Unable to push a complete host... Copy of demo

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7814]
When you try to push a complete copy of demo, we are having problems pushing the bundle....

To recreate: 
- Apply the dotcms license 
- Create a new copy of demo.dotcms.com
- Try to push 

Here the log error: https://gist.github.com/bryanboza/5ff573869542966acd23

Tested in the last nightly build // Postgres // FF

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/76
