### ISSUE TITLE
Unable to flush hibernate session when you copy/paste page into same folder

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7816]
If you have page A in a folder and want to copy/paste page A into the same folder, logs show the error "Unable to flush hibernate session"

To reproduce
1-Login with admin
2-Create a folder in the root
3-Create a page inside the new folder
4-Copy the new page and try to paste it into the same folder where it's currently located
5-You will get the error message "Unable to flush Hibernate Session" in the logs

Logs: https://gist.github.com/shayngr/29b48d16b2f31daebb15

Tested on:  3.2 Nightly build 2015-06-01 16:15/ Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
Need to rename the page so this doesn't happen

**Comment by rogelio-blanco** [comment]
PR #7932
