### ISSUE TITLE
Error pushing twice the same file but in a different status 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7817]
We are having an error with the identifier, when you try to push twice the same file, but the status is different.... 

To recreate:
- Create a new html page 
- Push it 
- Now go to sender and add a new content to the page and save
- Un-publish the page 
- Push the same page again 

Here the log error: https://gist.github.com/bryanboza/fcc8857fe620b173d7c9

Tested in the last nightly // Postgres // FF... This on both sides

**Comment by maurizo** [comment]
I could not reproduce the error, working as expected.

**Comment by bryanboza** [comment]
Not able to reproduce on 3.3
