### ISSUE TITLE
Improving dotCMS notifications check

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7819]
I wonder if we can improve the notifications code in order to avoid requests every 5 seconds on every open window:

``` javascript
// check for new notifications now and every N seconds
checkNotifications();
window.setInterval(function(){
    checkNotifications();
}, 5000);
```

I can think for now in two options:
- Web sockets
- HTML5 Server-Sent Events

**Comment by dotcmsCodeReview** [comment]
Good thoughts Jonathan. I'd  vote for websockets that can wrap some
lightweight messaging protocol that we can use for multiple purposes, not
just notifications. We've needed a channel open to the users browser
