### ISSUE TITLE
Cannot upload file to folder using webDAV

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7820]
As Admin, I'm trying to upload a ~350 MB file size (nightly build file) to a folder in dotcms backend using webDAV but it fails.

To reproduce:
1- Create a webdav/autopub connection in webdav and login as Admin
2- Try to upload to dotcms backend a big size file, such as a nightly build using webdav
3- Webdav will display an message saying the upload has failed

![webdave failed](https://cloud.githubusercontent.com/assets/8741846/7966633/9354f144-09e2-11e5-86f2-477961667008.png)

Logs: https://gist.github.com/shayngr/2913e325bf638b231294

My Xmx value is 990M
Tested on:  3.2 Nightly build 2015-06-01 16:15/ Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
Are we actually loading the entire file into memory and not using a stream :-s

**Comment by rogelio-blanco** [comment]
PR #7905

**Comment by bryanboza** [comment]
Fixed, tested on master-3.2 // Postgres // FF... I tested with a file of 700 MB and works fine
