### ISSUE TITLE
TinyMCE is not working when you enable the ENABLE_GZIP property 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7821]
We are having problem with the TinyMCE fields when you enable this property in the dotmarketing.config.properties file, when you try to add a new content in this field is not appearing the menu and you can't see the field 

![2015-06-03_1220](https://cloud.githubusercontent.com/assets/2641437/7967978/f17b6f70-09ea-11e5-8f08-e6ee40a09698.png)

Also we have some errors in the java script console: 
![2015-06-03_1221](https://cloud.githubusercontent.com/assets/2641437/7968006/1fc007ec-09eb-11e5-953a-47af4ddf90f0.png)

Tested in the last nightly // Postgres // FF

**Comment by jtesser** [comment]
moving away to a new editor anyways so no need to move here
