### ISSUE TITLE
Recurrent issue: Changing permissions on host Content/Files does not extend user access to pre-existing content inheriting from host

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7823]
After retesting fix #2229 on 3.2 nightly build, same issue still persists. Following the steps/video described lead to same bug.

To reproduce:
1) Edit the demo host permissions, add "Chris Publisher" user and give him "view" and "add to" on host and "edit" on Content Type.
2) Create a new structure with one text field and make sure host is set to demo host
3) Log in as "Chris Publisher" and create a piece of content using the new structure... after save he will not see the content because it saved to the host and he currently does not have permissions to see Content/Files (all good so far)
4) Now login as administrator and change Chris Publishers permissions to also have "Edit" on Content/Files and save (do not cascade)
5) Log in again as Chris Publisher and the bug is that he still can't see the content on the host.  If you log back in as admin and look at the permissions on the content, he has edit permissons.. but he does not see the content until the content is saved again. (that is the bug)

http://screencast.com/t/ZEo1lIvQ1

Tested on:  3.2 Nightly build 2015-06-01 16:15/ Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
@shayngr but I think this is right. I would check with @DeanGonzalez BUT the issue is your object is not inheriting from host.  So changing host doesn't effect it without a cascade
