### ISSUE TITLE
Problem with cache after deleting and add again a file asset throws 404

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#7829]
There is an issue with dotcms cache when you add a file asset, delete it and add it again. For some reason the cache doesn't flush properly.
 
To reproduce it do this:
1) Add a folder 
2) Inside that folder add a file asset and save and publish, for example an image or video 
3) In another frontend tab, look for the file asset http://myhost/myfolder/myfile.jpg (you can see it with no problems)
4) In backend Site Browser, then unpublish, archive and delete the file asset
5) Add again the same image or video file asset (myFile.jsp) in the same folder (/myfolder), save and publish
6) Refresh the other tab showing the file asset and the page throws a 404

But, if you do a flush cache in dotcms cms maintenance portlet and refresh the frontend page, then the file asset is displayed fine

Tested in dotcms 3.1 and 3.2

**Comment by rogelio-blanco** [comment]
PR #7913 and https://github.com/dotCMS/enterprise-2.x/pull/281

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // Postgres // FF
