### ISSUE TITLE
Showing asset name when field is named URL

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#7830]
In a structure, a field is named URL and the option "Show in Listing" when you go to the Content Tab it shows the asset_name instead of the field value. But if you enter the content it shows the right value.

Steps to reproduce:
1- Create a structure
2- Add a field named URL
3- Check value Show in Listing
4- Go to the content tab
5- Add a new content

![screenshot from 2015-06-08 12 21 18](https://cloud.githubusercontent.com/assets/5278970/8041932/ebdb3e64-0dd8-11e5-8c26-c3c9abaa2191.png)
![screenshot from 2015-06-08 12 20 47](https://cloud.githubusercontent.com/assets/5278970/8041931/ebdafb02-0dd8-11e5-91bf-8337789399d1.png)
![screenshot from 2015-06-08 12 21 01](https://cloud.githubusercontent.com/assets/5278970/8041933/ebdbcc58-0dd8-11e5-9a9d-50fd8489ea99.png)

Reproduced in 3.2

**Comment by maurizo** [comment]
Pull Request: #7885

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // Postgres // FF
