### ISSUE TITLE
Page workflow not available on edit mode in 3.2

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7833]
Changes made in this issue #6961 did not make it into 3.2.  I don't know if they made it into 3.1 but they are working in this branch: 7b87d8c58087853a71636910f971d9daeb4ecc35 

Here is a screenshot running branch: 7b87d8c58087853a71636910f971d9daeb4ecc35

![screen shot 2015-06-10 at 8 54 55 am](https://cloud.githubusercontent.com/assets/934364/8083345/e85ce1aa-0f51-11e5-8c0e-c85b7f8b7381.png)

And here is a screenshot from demo.dotcms.com
![screen shot 2015-06-10 at 8 55 15 am](https://cloud.githubusercontent.com/assets/934364/8083350/f1d514d2-0f51-11e5-9fd1-1f48d15ec0df.png)

**Comment by jcastro-dotcms** [comment]
As per conversation with @jtesser, I'll take care of restoring this functionality. I will also change code references from Jettison to Jackson objects.

**Comment by wezell** [comment]
Careful here Jose, we need these changes in a release before the rules
engine comes out, in like a 3.2.2.

On Wed, Jun 10, 2015 at 11:29 AM, Jose Castro <notifications@github.com>
wrote:

> As per conversation with @jtesser <https://github.com/jtesser>, I'll take
> care of restoring this functionality. I will also change code references
> from Jettison to Jackson objects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7833#issuecomment-110796385>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jcastro-dotcms** [comment]
Got it.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7843

The code was not overwritten. The problem was around the Velocity variable called "dotPageContent", which is a ContentMap now, not the plain IHTML object.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
