### ISSUE TITLE
Language selector is displaying page languages that are not available

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#7834]
This issue was addressed in https://github.com/dotCMS/core/issues/7061 but the changes didn't make it into 3.2.

We need to disable the languages that do not exist, meaning you cannot click on it. But if it does exist, click it and switch the page to the right version, meaning the right language of that page.

As you can see in demo, the language selector in the /index page displays 3 options: "English", "Spanish", and "Chinese". However, the page is ONLY available in English, so the selector is not supposed to let users change to another language. It has to display only the languages the page is available on.

![index_page](https://cloud.githubusercontent.com/assets/8779585/8084250/470930d8-0f47-11e5-9cf3-771cb9bddeea.png)

**Comment by wezell** [comment]
@brentgriffin we are seeing a number of regressions between 3.1 and 3.2 (though all seem to have to do with edit mode so far)

**Comment by jcastro-dotcms** [comment]
The fix posted in this issue: https://github.com/dotCMS/core/issues/7686 deals with the available languages and also takes into account the "DEFAULT_PAGE_TO_DEFAULT_LANGUAGE". So it seems the issue described in https://github.com/dotCMS/core/issues/7061 is not valid anymore. We can close this ticket.
