### ISSUE TITLE
Update JASPER jar to its latest version

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#7836]
dotCMS currently ships with version 3.5.0_1.

6.1.0 is the latest available version at this moment.

http://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports

Client Reference: https://my.dotcms.com/ticket/dotcms-49

**Comment by jtesser** [comment]
I wonder if we want to keep this functionality or not.  @wezell

**Comment by dotcmsCodeReview** [comment]
No, we should depreciate and remove it.  It is a perfect candidate for a
plugin.

On Tue, Jun 23, 2015 at 10:29 AM, Jason Tesser <notifications@github.com>
wrote:

> I wonder if we want to keep this functionality or not. @wezell
> <https://github.com/wezell>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7836#issuecomment-114524814>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>
