### ISSUE TITLE
Navtool not returning parent or child results in 3.2

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7838]
The navtool in 3.2 is not producing results when calling navtool.nav, navtool.nav.parent, or navtool.nav.children
Here is the code I am using in the following 3.2 and 2.7 comparison pages:
 https://gist.github.com/DeanGonzalez/080f1d3ccb1c7d419793

3.2 Page: http://demo.dotcms.com/grandparent/parent/current-page (nothing returns)

However, in our navtool documentation and in previous versions, this was the recommended way to build crumbtrails.  Here is a 2.7 page showing returns from the same code and same page at the same navigation level as the 3.2 example:

http://demo2.dotcms.com/grandparent/parent/currentpage.html (parent and child folders return)

In both version tests, show on menu is placed on all pages and folders

**Comment by erickgonzalez** [comment]
Unable to reproduce. Tested in demo and works fine.

**Comment by shayngr** [comment]
Issue still persists with navtool.nav.children. I used the same code https://gist.github.com/DeanGonzalez/080f1d3ccb1c7d419793 and noticed that:
1) navtool.nav.parent is working on both demo.dotcms.com and demo2.dotcms.com
2) navtool.nav.children is only working in demo.dotcms.com

Screencast: http://screencast.com/t/ydC0TiTE2
