### ISSUE TITLE
Adding same content twice to a page changes its display

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7841]
To reproduce
1- Login with admin
2- Create a new page
3- Add some content to the page
4- Add the same content again to the page
You will see the page changes the display. If you delete the content you have added, it goes back to normal.

No logs for this issue

http://screencast.com/t/KIajylfU

Tested on:  3.2 Nightly build 2015-06-08 10:40 // Ubuntu 14.04 // Postgres // Firefox

**Comment by jtesser** [comment]
this is not something we support.  We should not add the same content to the same container
