### ISSUE TITLE
Dependency problem: Unable to delete contents when you have multi language version 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7842]
When you have a version of any content in more that one language, you are unable to delete this content, after you un-publish and then archive the content, when you try to delete we have the follow WARN: 
```
[11/06/15 08:49:52:102 CST]  WARN business.ESContentletAPIImpl: Cannot delete content that has a working copy in another language
```
Tried to delete first the other versions and then the default language version and neither works, the content is not deleted 

If you right click and try to delete the content is disappearing, but after refresh the page appear again... 

Tested in the last nightly // MySQL // FF

**Comment by bryanboza** [comment]
Related to #7521

**Comment by jbjornson** [comment]
Any workaround for this?  Maybe even a database script to manually delete the content?

**Comment by jtesser** [comment]
well no you shouldn't  You need to unpublished and archive each language for the content.   The issue is that a delete is a destroy of all versions including all languages.  This is not a bug.  There is a tool in CMS Maintenance that can destroy identifiers

**Comment by jbjornson** [comment]
But I don't want to delete the whole content, just the specific language version of that content.  We are trying to delete a language from our dotcms website but *cannot* (because this bug is preventing us from deleting the content associated with that language).

I also strongly disagree that this is not a bug.

**Comment by jtesser** [comment]
I understand but in this case you archive the language no longer being used.  The language is still a version of the content.  You can run the Remove old versions which should clean up older non working versions but in general things are versioned and recoverable.

**Comment by jbjornson** [comment]
...but we still can't delete the language (System / Languages / Edit Language / Delete).  We will no longer support one of the languages we had expected, and we would like to remove the temptation for our content providers to add content in that language.

**Comment by jtesser** [comment]
So I put in the related issue above which will address your case in the future.

You can do the following. 
1. Ensure your dotCMS is all backed up. DB, assets, index etc.. 
2. get a CSV using the Content Search export of the content in question. Download it. 
3. Delete the content that is in the other languages using the CMS Admin tool.  This will delete ALL language versions. 
4. Import the content back in without the languages you do not want. 
5. Delete your language
