### ISSUE TITLE
Message is missing in Time Machine if user does not add a site before running the job

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7845]
System is not showing any information message to users if they miss adding a site before running the job.

To reproduce:
1- Login with admin
2- Go to Site Browser> Time Machine. Go to settings to create a snapshot.
3- Don't add any site but fill out the other information
4- Hit "Save & Run Now" button
There should be a message to inform the user about the missing field

![missing message for adding site](https://cloud.githubusercontent.com/assets/8741846/8114481/129c5cee-1032-11e5-9d1a-7b611ed5f9e8.png)

No logs

Tested on:  3.2 Nightly build 2015-06-10 16:45 // Ubuntu 14.04 // Postgres // Firefox

**Comment by rogelio-blanco** [comment]
How about disable the buttons until the user selects a site?

**Comment by rogelio-blanco** [comment]
PR #7935

**Comment by bryanboza** [comment]
Fixed, now we have a message with the error.... Tested on 3.3 // Postgres // FF
