### ISSUE TITLE
Enhancement: Right-Click Edit on a Page should open Page Content in Edit Mode

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#7847]
Improvement based on some current page behavior that is affecting client experience: https://mail.google.com/mail/u/0/#inbox/14de7f4329e26f69

Improvement suggestions to the current 3.2 version behavior
1) When choosing to edit a page from the browse drop down menu, the page should open in Edit Mode and lock automatically. Note: we may want want to change the menu text to "Edit Page" from "Open (Preview)"
2) If browsing away from a locked page a popup should ask the user if they want to "unlock the page before leaving".
3) When they BROWSE to another page in edit mode that page should continue to open in Preview mode (current behavior).

**Comment by fishsmith** [comment]
+1

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/80
