### ISSUE TITLE
htmlpageasset does not return url

### ISSUE THREAD

**Issue by tintami** [dotCMS/core#7848]
When a search returns a page asset you cannot access the url or redirecturl. For example:

#set($pageguid = "bb2659d2-4052-477a-a22f-041d645ca78c")
#set($item = $dotcontent.find($pageguid))
item.title : $item.title
item.url : $item.url
item.template : $item.template
item.friendlyname : $item.friendlyname

...will write out something like this:

item.title : Treating Customers Fairly 
item.url : $item.url 
item.template : 14ed89f1-cd63-4533-92a8-1363abcb928e 
item.friendlyname : Treating Customers Fairly

This can even be seen happening in the dotcms documentation here:

http://dotcms.com/docs/latest/page-content-in-velocity

**Comment by brentgriffin** [comment]
Able to reproduce locally in released 3.2.1 // ubuntu 14.04.2  LTS // H2

**Comment by wezell** [comment]
Be mindful of this issue when fixing: #7830

**Comment by maurizo** [comment]
Pull Request: #7885

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // Posgres // FF
