### ISSUE TITLE
Website Browser: Cannot save folder if DB Provider is Oracle

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7849]
Reproduced in client running upgraded from 2.5.6 to 3.2 and locally in 3.2.1. 

Steps:

1. Make sure the dotCMS Instance has a valid enterprise license.
2. Open any folder from current default site and check that the "Allowed File Extensions" file is empty. 
3. Save.

Stacktrace:

https://gist.github.com/joseorsini/8a40f619eebe51dcb3df

Problem is caused here

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/folders/model/Folder.java#L311

We need to handle null values in this line, since Oracle handles empty varchar/string fields as null.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // Oracle 11g // FF
