### ISSUE TITLE
Upgrades: Post-upgrade issues on clients running 3.2.1

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7851]
Re: https://my.dotcms.com/ticket/dotcms-55/

We need a startup task for the items explained in the referenced ticket.

**Comment by erickgonzalez** [comment]
Missing to test in Oracle DB.

To reproduce point 1:
1- Start an instance of 3.2
2- Create a Content Type with one field indexed.
3- Add some contents.
4- Update page_detail field directly in the DB. e.g set it to 1
5- Flush cache and reindex. Logs will show an error.

To reproduce point 2:
1- Delete the anonymous user from cms_role.
2- Flush cache.
3- Login as Chris Publisher
4- Go to Content Tab.

**Comment by jgambarios** [comment]
Working on Oracle.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7944

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
