### ISSUE TITLE
Need update the youtube API version for demo.dotcms.com... 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7856]
Since April 20th, 2015 google shutdown the old api version and now we need work with the newest (v3 version).... As google maps now we need create a google developers account and request for an api key...

We need update this because the old one is not working in our examples... 

http://stackoverflow.com/questions/30685625/alternative-for-https-gdata-youtube-com-feeds-api-videos-video-idv-2

Tested in the last 3.2.1 version...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7910

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
