### ISSUE TITLE
Some Edit Mode issues

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7858]
What's Changed is broken IF you use inline editing.  So goto a page. Use inline editing and Save. Do not publish. Then click preview and What's Changed. This will throw an error.  I believe it is the same issue we had here. https://github.com/dotCMS/core/commit/83d53de0977a2b207b4b5eb240932f34d8c15e18

**Comment by wezell** [comment]
Also, if you inline edit and hit the save button (the content is now in a drafted state) and then click the edit content button (taking you to the back end/wysiwyg editor), then click cancel (do not unlock the content).  It gives you this oops:


An unexpected system error occurred.

Contentlet : ea2bd8c3-48e5-430f-b7b3-f510a6242c99 is not a pageAsset

**Comment by rogelio-blanco** [comment]
PR #7861

**Comment by shayngr** [comment]
Fix is working on 3.2.1 build // Ubuntu 14.04 // Postgres // Firefox

**Comment by bryanboza** [comment]
More problems in the #7876

**Comment by bryanboza** [comment]
Fixed, tested on 3.2.2 release candidate // Postgres // FF
