### ISSUE TITLE
Manual ES replica config should be honored when CLUSTER_AUTOWIRE=false

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7859]
The following settings are being ignored when using manual clustering:
es.index.auto_expand_replicas=false
es.index.number_of_replicas=1

Index replica counts are being altered automatically on server up/down status instead of using the 2.x manual config. With a large index, this is detrimental due to the large volume of data transferred on full index rebuild and the long sync time.

Reproduced in dotCMS-3.2.1.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7868

**Comment by jgambarios** [comment]
Hot-fix: https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-7859_v3.2.1

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
