### ISSUE TITLE
Add configurable es.index.number_of_replicas decrement grace period with CLUSTER_AUTOWIRE=true

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7860]
When using cluster autowire, we should allow a [config variable] grace period after a server leaves the cluster before lowering the index replica count. For normal brief outages such as scheduled maintenance, this should temporarily drop the index into degraded state and allow for onlining the existing shard upon return instead of full shard rebuild. This is important for clients that have large indexes that can take up to 30 minutes to perform a full replica build.

**Comment by chrismccracken** [comment]
Also https://github.com/dotCMS/core/issues/8038

**Comment by dsilvam** [comment]
We are currently using ElasicSearch auto adjusting of replicas. We need to change this to doing manually and using the new property value specified in the description

**Comment by jtesser** [comment]
30 min default 

replica number will be number of servers -1

**Comment by jtesser** [comment]
need to test autowire and external elastic search together

**Comment by jtesser** [comment]
needs to work both ways up and down

**Comment by wezell** [comment]
set `es.index.auto_expand_replicas=false`

**Comment by jtesser** [comment]
Make sure to read https://github.com/dotCMS/core/issues/8038

**Comment by dsilvam** [comment]
This was fixed in #8038
