### ISSUE TITLE
Menu links permissions issue

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7863]
We have an issue with the permissions in the menu links,  If you add a new role and all full permissions to the host, when you try to edit a existing menu link we have 3 buttons (Save&Publish, Save and Cancel), but if you try to add a new link from any folder you only have (Save and Cancel), and if try from the menu links portlet you only have the cancel button 

From any folder: 
![save - cancel](https://cloud.githubusercontent.com/assets/2641437/8263013/5f926382-1694-11e5-9f50-42a4276267c0.png)
From Menu links portlet: 
![only cancel](https://cloud.githubusercontent.com/assets/2641437/8263019/6ac73188-1694-11e5-86bf-9311d8f247a0.png)

Tested on the last 3.2.1 // Postgres // FF

**Comment by jtesser** [comment]
I think your lacking add children or something like that.  Can u check with @DeanGonzalez  and verify
