### ISSUE TITLE
Thumbnails are not been clean when there is a push publish procedure

### ISSUE THREAD

**Issue by rogelio-blanco** [dotCMS/core#7865]
dotCMS is not cleaning file assets thumbnails when there is a push publish. 

This issue is related with #7806 and #7864 

This issue can be reproduce after #7806 is complete.

**Comment by rogelio-blanco** [comment]
PR core #8037 
PR enterprise #dotCMS/enterprise-2.x/283

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // Postgres // FF
