### ISSUE TITLE
Cant use Vanity Url with Port in Redirect

### ISSUE THREAD

**Issue by cfalzone** [dotCMS/core#787]
Basically you cannot use a Vanity URL to redirect to an external host that using a port other than 80/443.  So for example if you have /test and you want to redirect to http://myexternalhost.com:8080/test/index.php  this does not work.  It looks like we do a search on the hostname to see if it is an internal host or external host and because of the :8080 in the hostname it fails and a default host is returned where we want no host to be returned.

Here is a screencast showing how to reproduce the issue and what happens:  http://screencast.com/t/dq6xeH1jXEz

Here is the error that gets printed in the log:  https://gist.github.com/3097926

**Comment by nkeiter** [comment]
Will this be fixed soon?  I guess I'll have to write a tucky filter plugin to redirect with ports until then.

**Comment by jtesser** [comment]
not currently slated for a fix but that doesn't mean it won't happen.

**Comment by wezell** [comment]
We need to test this case

**Comment by bryanboza** [comment]
Fixed, now this works in the new vanity URL as content
