### ISSUE TITLE
Cookies are not respecting the expire parameter 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7871]
When you create a new cookie and include the expire parameter, the system is sending incomplete and convert this in a session cookie 

- Make sure you don't have browser cookies, and  you don't have a username cookie.
- In JS console execute:
      ```document.cookie="username=JohnDoe; expires=Thu, 18 Dec 2016 12:00:00 UTC; path=/";```
- In browser cookies you have a username cookie expiring in Dec 2016.
- Refresh page
- Now your cookie turned into session cookie because server is sending this:
    ```Set-Cookie: username=JohnDoe;Path=/```

Here the SC: 
Before refresh: 
![2015-06-23_0927](https://cloud.githubusercontent.com/assets/2641437/8309925/3eb89c46-198a-11e5-82fe-89e195f5c77f.png)
After refresh: 
![2015-06-23_0928](https://cloud.githubusercontent.com/assets/2641437/8309933/4729519a-198a-11e5-8b08-778403c1d552.png)

Tested in the last 3.2.1 // Postgres // FF

**Comment by cfalzone** [comment]
I can confirm this behavior on my local 3.2 instance.  The behavior is not unique to the name of the cookie, I also tried it was "test-cookie" instead of "username".

**Comment by shayngr** [comment]
Added TC: http://qa.dotcms.com/index.php?/cases/view/61331

**Comment by maurizo** [comment]
PR: #7969

**Comment by jgambarios** [comment]
QA: Please re-test #6823 #4840

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // MySQL // FF
