### ISSUE TITLE
Pages and get lost when you delete a folder you copied from

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#7872]
After reporting this issue: https://github.com/dotCMS/core/issues/7870

I renamed the index page to a new name to test the copy paste. 
I then copied the renamed file to another folder. 
I then deleted the folder where the page was copied from
----
results: the folder where I copied the stuff to now fails to load. I the need to do a full reindex. The folder now loads but both the page and the original folder are gone.

see video: http://screencast.com/t/VjlfmxVKUCH

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/72
