### ISSUE TITLE
Unable to rename subfolders using webDAV

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7873]
When you create a subfolder and then want to rename it using Cyberduck, it throws the following error:
https://gist.github.com/bryanboza/99ca2f45bc2c6e4938be

This is happening using Cyberduck (and Finder)

Steps to reproduce:
1-Login with admin
2-Create a webdav connection using Cyberduck
3-Create a folder within Cyberduck
4-Now create a subfolder, then try to rename this subfolder
5-You should get an error message

http://screencast.com/t/RpNUremB5C3

Tested on:  3.2.1 build // Ubuntu 14.04 // Postgres // Firefox // Cyberduck 4.5.2 (15055)

**Comment by rogelio-blanco** [comment]
PR #7908

**Comment by bryanboza** [comment]
Fixed, tested on  3.3 // Postgres // FF
