### ISSUE TITLE
The what's changed feature is not detecting changes in the legacy pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7876]
Related to # 7858

After upgrade from 2.5 to 3.2.2, if you take any legacy page and try to edit, and add some contents, we have problems with the what's changed feature...

Steps to reproduce:
- Using a legacy page, add a new content to the page and Save&Publish
- Now try to add a new one, but now just Save
- Go to edit mode and click in wha's changed 

You will see just the new first content and not the last one, you will continue adding more contents but just continue showing the first one 

Here the SC: http://screencast.com/t/MVXC79RMZ0Pf

Tested in the 3.2.2 release // Postgres // FF

**Comment by bryanboza** [comment]
FYI: Tested the same case in the content pages and works fine

**Comment by bryanboza** [comment]
Also, the system is not detecting changes if you modify via in-line editing http://screencast.com/t/UPdcL2k3xi

**Comment by bryanboza** [comment]
The same problem, with the content multi language pages, the system show only the content added, but not the removed.... Testing with @rogelio-blanco, seems that is a cache issue, because after you flush the velocity caches, the system works as expected

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7889 - https://github.com/dotCMS/enterprise-2.x/pull/280

**Comment by bryanboza** [comment]
New problems on #7898

**Comment by bryanboza** [comment]
Fixed, tested on 3.2.2 release candidate // Postgres // FF
