### ISSUE TITLE
Imposible to see the first line when you use in-line editing 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7877]
When you are using the in line editing the save button is replacing  the first text line, and is imposible too see the text..... 

![2015-06-23_1519](https://cloud.githubusercontent.com/assets/2641437/8317502/3edd42c2-19bb-11e5-9b11-cfa4658f60b9.png)

Tested on 3.2.2 release // Postgres // FF

**Comment by wezell** [comment]
fixed
