### ISSUE TITLE
Finder not working well with webDAV in OSX Yosemite

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7879]
Related to #4509

Working with OSX Yosemite 10.10.1 and having some issues using Finder to move files from one folder to another, such as additional entries are being created in the Site Browser and files are left behind (i.e.: files with no extension).

To reproduce:
1-Startup dotcms instance
2-Mount dotcms as a webdav share 
3-Create 2 different folders in the root (test1 & test2) using Finder 
4-Upload different files to test1 folder (including a file with not extension)
5-Try to move those files from test1 folder to test2 folder
6-You will see additional entries created under test2 folder (and the file with no extension will not get moved)

http://screencast.com/t/cP7gGW18

Log: https://gist.github.com/shayngr/ad2036b64183a0c8ca63

Tested on candidate release for 3.2.2 // OSX Yosemite 10.10.1 // MySQL // Firefox

**Comment by jtesser** [comment]
yea FWIW we recommend editing through finder or uploading file. But any bug changes or moves etc... we recommend using cyberduck
