### ISSUE TITLE
Contents: Failed to edit events if Event Content Type has a TextArea field

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7886]
Reproduced in demo.dotcms.com and in upgraded client to 3.2.1.

Steps to reproduce:

1. For Event Content Type, add a Textarea field. It's not necessary to make ir required and indexed. 
2. Try to edit any existing Event content.

Stacktrace: https://gist.github.com/joseorsini/1c8f3df5436f91e1c3e5

Problem is triggered here: https://github.com/dotCMS/core/blob/master-3.2/dotCMS/html/portlet/ext/contentlet/field/edit_field.jsp#L140 The ContentletForm object does not exist in request, but the Contentlet object does exist here https://github.com/dotCMS/core/blob/master-3.2/dotCMS/html/portlet/ext/contentlet/field/edit_field.jsp#L46 so any reference to ContentletForm may be replaced with this.

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/7803
