### ISSUE TITLE
What's Changed not working for url maps

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7888]
The **"What's Changed"** functionality is not showing differences for urls maps, it just shows the **"Nothing Changed"** message.

This problem can be reproduced on any dotCMS version and with any type of HTML Page (legacy and new ones).

**Comment by wezell** [comment]
Does not work in 3.3 either.

**Comment by oswaldogallango** [comment]
the problem was that the changes in the url were detected but not info was displayed. Now the <span> have a title attribute to display what was the change with url links on mouseover

**Comment by brentgriffin** [comment]
isn't the issue here with URL mapped content?  http://dotcms.com/docs/latest/urlmap-seo-friendly-urls

**Comment by jgambarios** [comment]
Yes, for what I remember the original issue is with the URL mapped content.

**Comment by oswaldogallango** [comment]
pull request https://github.com/dotCMS/core/pull/8941

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // Postgres // FF
