### ISSUE TITLE
HTMLPages: Order of containers is not respected in Live Mode

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7890]
Reproduced in upgraded client and in demo site. 

Steps:

1. Create a test page, e.g., /test/overview.html.
2. Add 2 existing contents, e.g, 'A' and 'B'. Check that A is the top content on the container in all 3 backend views (Edit, Preview and Live).
3. In Edit mode, reorder the contents so B is the top content of that page. Edit and Preview mode will reflect the changes, but Live mode will keep the previous version of it. 

If the page is re-published or the cache is flushed, the order is displayed consistently in all 3 views

Preview Mode
![screen shot 2015-06-25 at 12 20 52 pm](https://cloud.githubusercontent.com/assets/1717110/8363962/a39c7426-1b50-11e5-91d5-3fe081c4e5e7.png)

Live Mode
![screen shot 2015-06-25 at 12 20 56 pm](https://cloud.githubusercontent.com/assets/1717110/8363965/a6651ca8-1b50-11e5-8991-6e72be074112.png)

**Comment by wezell** [comment]
This is not a bug.  You need to publish the page before the page cache will refresh.

**Comment by joseorsini** [comment]
Got it. Thanks, @wezell
