### ISSUE TITLE
Dates are not localized when language is changed.

### ISSUE THREAD

**Issue by wolfgang-lausenhammer** [dotCMS/core#7892]
When I change the language to German, the dates in the site browser are not localized to the selected language. See screenshot 
![not_localized_date](https://cloud.githubusercontent.com/assets/1884650/8377983/2c236b5e-1c16-11e5-81d3-107f8ee16777.png)

**Comment by jtesser** [comment]
yes these dates are stored on the content.  We don't convert these yet

**Comment by jkshapiro** [comment]
Stopgap fix: ISO 8601 everywhere (https://en.wikipedia.org/?title=ISO_8601)
Medium-term fix: Date formats configurable by interface language
Long term fix: Date formats configurable by user
