### ISSUE TITLE
Push Pub Integrity Checker - Check Compatibility Between Environments

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7893]
We've seen a growing number of issues stemming from environments within the same push pub environment not running the same stacks/configs.

Any difference between environments not explicitly QA'd and warrantied should be either logged or checked by the integrity checker.

Potential contenders (need to be validated by RnD as not supported and updated to reflect other criteria).

* difference in java versions
* difference in dotCMS versions
* difference in DBs
* difference in OS'
* difference in plugins running (hotfixes for example, could be a warning more than an error)
* other?

**Comment by jtesser** [comment]
We support difference in DBs, OSs and plugins/hotfixes meaning these are not things that we would consider a conflict. Potentially the same with Java version. 

We could message on Java Version and dotCMS Version.  Obviously not fix but message.

**Comment by levosgien** [comment]
Right, messaging would be great, most important would be what we don't support (dotCMS versions, Java versions, ServerIDs, LicenserIDs.....).

For DB differences we'll want to make sure we test it, last we spoke with QA no specific push testing had been done to validate diff. DBs.

**Comment by levosgien** [comment]
/cards/94
