### ISSUE TITLE
Integrity Checker Pop-Up Closes too quickly

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7894]
Version: dotCMS 3.2.1

Can't read the results of the integrity checker, stays up for 1 second and closes itself. Should either stay up a little longer or be closed by user.

See: http://screencast.com/t/Tl59Rrsf

**Comment by brentgriffin** [comment]
another possibility would be to have this message show up in the notification center - it could run awhile and the user may not be able to keep the browser open the whole time.

**Comment by jtesser** [comment]
added to card #93
