### ISSUE TITLE
Integrity Checker Results: Logs/Downloads

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7895]
1) It would be good to include the integrity checker results in the pushpub log. 

2) In addition, it would be helpful for communicating results to have a "Download Results" button somewhere - maybe a with a history of all checks and a download link for each.

**Comment by jtesser** [comment]
So we do not save the history for this and don't think we want to.

**Comment by levosgien** [comment]
The idea here was to get a better understanding of whether issues were new or not, relative to other past results to paint a larger picture. There are probably other/better ways to achieve this so it's up to the business at this point, just a few suggestions.

**Comment by jtesser** [comment]
Yes for now I think we will hold here as not sure what to do with it but the integrity checker runs each time and should/could be different.  There is no infrastructure for history and not sure there should be.  I will leave in github for now
