### ISSUE TITLE
ReindexThread initialization issue - ignores property file setting REINDEX_SLEEP_DURING_INDEX

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7897]
ReindexThread behaves differently based on which static method is called first on the class.  There are three static public methods that can result in the singleton instance being created.

They are:
 * getInstance()
 * startThread()
 * createThread()

The call to getInstance() results in calling createThread() - so far, so good.

The problem is that if startThread() is called first, it does not call createThread(), it runs its own instantiation logic which does not read the dotmarketing-config.properties file and does not set reindexSleepDuringIndex and reindexSleepDuringIndexTime class members.  This causes the code in this if block to never be executed:  https://github.com/dotCMS/core/blob/3.2.1/src/com/dotmarketing/common/reindex/ReindexThread.java#L163-L169

In my local environment, startThread is getting called before createThread which means it is ignoring my REINDEX_SLEEP_DURING_INDEX property file setting.  I verified that both on the initial start of the server and on a restart of the server that startThread is getting called first and initializing the singleton.

OSX 10.10.3 // Java 1.8.0_40 // localbuild of master-3.2 // H2

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7909

**Comment by bryanboza** [comment]
Fixed, tested on nightly build 2015-07-27 // Postgres // FF
