### ISSUE TITLE
Unable to reuse content in a different language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7899]
When you have any  page in a specific language, and you try to reuse any content but in a different language, is having a java script error and can't show the content

 To recreate:
- Create a new content page 
- Try to add a new content, but reuse an existing one, but in a different language 

The system is having a JS error: ReferenceError: showDotCMSSystemMessage is not defined, and can't show the content... 

The expected behavior is validate if exist the page language of the content and add here... 

SC: http://screencast.com/t/Jh9Mh6sgT9

Tested on 3.2.2 // Postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/7901

**Comment by bryanboza** [comment]
Fixed, tested on 3.2.2 release candidate // Postgres // FF
