### ISSUE TITLE
BinaryExporterServlet is not completly respecting FrontEndRoles

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#7903]
Client is complaining about images/css not loading in Edit Mode. The thing is that the user has not READ permission on the folder where the images/css are and the BinaryExporterServlet is returning a Not Authorised error. In 2.x edit mode didn’t go through BinaryExporterServlet but in 3.x it does.

I could reproduced it in demo with BIll Intranet and http://demo.dotcms.com/intranet/index. The logo is not loading because it is under a /themes/intranet/images where Bill doesn’t have READ permission

JT said: in edit mode the servlet is NOT realizing it should respect Front End User Permissions

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7904

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
