### ISSUE TITLE
Documentation: Changelog link for v3.2.2 points to v3.2.1

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7916]
On page http://dotcms.com/docs/latest/change-log, the link under "Issue Tracker" for v3.2.2 is wrong twice. Currently it is

`<a href="https://github.com/dotCMS/core/issues?page=1&amp;q=is%3Aissue+milestone%3A3.2.1+is%3Aclosed">https://github.com/dotCMS/core/issues?q=is%3Aissue+milestone%3A3.2.2+is%3Aclosedlosed</a>`

It should instead be

`<a href="https://github.com/dotCMS/core/issues?page=1&q=is%3Aissue+milestone%3A3.2.2">https://github.com/dotCMS/core/issues?page=1&q=is%3Aissue+milestone%3A3.2.2</a>`

**Comment by DeanGonzalez** [comment]
Thanks, Kivi!

Link has been fixed: http://dotcms.com/docs/latest/change-log

On Thu, Jul 2, 2015 at 6:44 AM, Kivi Shapiro <notifications@github.com>
wrote:

> On page http://dotcms.com/docs/latest/change-log, the link under "Issue
> Tracker" for v3.2.2 is wrong twice. Currently it is
>
> <a href="
> https://github.com/dotCMS/core/issues?page=1&amp;q=is%3Aissue+milestone%3A3.2.1+is%3Aclosed
> ">
> https://github.com/dotCMS/core/issues?q=is%3Aissue+milestone%3A3.2.2+is%3Aclosedlosed
> </a>
>
> It should instead be
>
> <a href="
> https://github.com/dotCMS/core/issues?page=1&q=is%3Aissue+milestone%3A3.2.2
> ">
> https://github.com/dotCMS/core/issues?page=1&q=is%3Aissue+milestone%3A3.2.2
> </a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7916>.
>



-- 
Thank you,

Dean Gonzalez
General Manager, dotCMS Costa Rica
Training Manager



Eurocenter I
Primer Nivel, Oficina dotCMS
Barreal de Heredia, frente a CENADA
Heredia, Costa Rica
Main: 305-900-2001 | Direct: +506.6185.7137

dean@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>
