### ISSUE TITLE
Legacy Files: issue with REST API calls and Permissions

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7919]
Reproduced in 3.2.1 with data from upgraded clients.

When a Legacy File (for example an image) is called through the REST API in a frontend pull and permissions are not set in DB, we check permissions according to its identifier

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/servlets/BinaryExporterServlet.java#L309

However, since we're sending an identifier to the Permission API, we're entering here

 https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/business/PermissionBitFactoryImpl.java#L2489 

and at the end, the permission is saved with the wrong permission_type

Gist: https://gist.github.com/joseorsini/bcfea0c83777a765ad48

Legacy files should have "com.dotmarketing.portlets.files.model.File" as permission_type.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7920

**Comment by bryanboza** [comment]
Fixed, tested on 3.2.4 PR // Postgres
