### ISSUE TITLE
Viewtools: Missing getters in GoogleMiniSearch Entity affects Google CSE Viewtool

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7921]
Reproduced in client running 3.2.1.

For any GoogleMiniSearch object returned by our Google CSE Viewtool, there is no way to return the previousResultPageRelativeURL and nextResultPageRelativeURL, which are required for pagination purposes. 

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/beans/GoogleMiniSearch.java

In the GoogleMiniSearch, though, we do ask if these values are set in the returned object, and the toString() method also includes them, but since it's a StringBuffer returned as a string, we would need to create Get methods for these two values and possibly a JSONArray that would have a better output than the toString() method.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7922

**Comment by shayngr** [comment]
Passed QA. Tested on release candidate for 3.2.4 (http://dotcms.com/physical_downloads/test/dotcms_3.2.4.zip)
Win7 Pro SP1
SQLServer 2012
Firefox
