### ISSUE TITLE
We need use site instead host in the push publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7926]
When you try to push any site and then go to status/history, in this tab you have the "host" word in the title, and we need try to use the same one in all the system... 

<img width="1419" alt="2015-07-08_1411" src="https://cloud.githubusercontent.com/assets/2641437/8581025/478dd97e-257b-11e5-983a-e42305244121.png">

Tested on 3.2.2 release // H2  // FF

**Comment by levosgien** [comment]
/cards/104
