### ISSUE TITLE
Allow single quotes in user first/last names

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7927]
For some reason, we mistakenly chose to disallow users from using single quotes when entering a user's name in order to avoid JS issues.  We should allow single quotes in a users first or last name and  the single quote in JS

**Comment by dotcmsCodeReview** [comment]
Yup I agree.   I do think we handle a lot of the cases now but we need to
reenable the ' and then test

**Comment by jkshapiro** [comment]
Best practice would be to allow any Unicode characters in there that the user chooses to enter. People have all kinds of names.
