### ISSUE TITLE
Enhancement: Implement filtered search of Containers for limited users

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7928]
Reproduced in client and also in demo.dotcms.com running 3.2.1

Currently, we use 

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/containers/ajax/ContainerAjax.java#L73 

For pulling containers in the Add/Edit Template form, specifically in the Add Container dropdown. We are not filtering Containers per host, so this involves a search of all containers in the DB. When the whole list of containers is pulled, then it's filtered according to user's permissions, which involves cache hits or DB (depending if the permissions cache was cleared). The response time may be large in case a multi-host environment has a significant amount of containers. 

A potential solution to this is to implement a search of containers according to user's permissions in the PermissionedWebAssetUtil.java class. This class has working implementation of assets' search for limited users, specifically for Templates and Structures.

**Comment by joseorsini** [comment]
https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/business/PermissionedWebAssetUtil.java

**Comment by jcastro-dotcms** [comment]
As per conversation with @jtesser, improvement in performance can be achieved by using the "PermissionedWebAssetUtil" class. This would allow us to get the final list of permissioned container objects through a single SQL query, instead of retrieving the complete list of containers and then programmatically filtering it to get the permissioned objects.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7942

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // Postgres // FF

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/26/
