### ISSUE TITLE
Cut/Paste Legacy pages is not working properly

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7929]
Reproduced in two clients running 3.2.1. 

If the VELOCITY_PAGE_EXTENSION property in the dotCMS configuration is set to html (default value) but legacy pages have a different page extension, this may cause issues when a user cuts and pastes a Legacy page to a different folder. 

Steps to reproduce:

1. Create a folder.
2. Grab any legacy page, right click on it and then select "Cut".
3. go to the new created folder, right click on it and select "Paste".

Before the cut:
```
dotcms=> select * from identifier where id in (select identifier from htmlpage) and asset_type <>  'htmlpage';
              host_inode              |                  id                  |        parent_path        |          asset_name           | asset_type | syspublish_date | sysexpire_date
--------------------------------------+--------------------------------------+---------------------------+--------------
-----------------+------------+-----------------+----------------
 d8b27542-d5fd-46a5-8ea3-b360bbe91cce | 6409d482-37ba-4100-90d4-6b3ae0012cc2 | /test/ | information-for-travelers.dot | htmlpage |                 |
```

After it's pasted:
```
dotcms=> select * from identifier where id in (select identifier from htmlpage) and asset_type <> 'htmlpage';
              host_inode              |                  id                  |        parent_path        |          asset_name           | asset_type | syspublish_date | sysexpire_date
--------------------------------------+--------------------------------------+---------------------------+--------------
-----------------+------------+-----------------+----------------
 d8b27542-d5fd-46a5-8ea3-b360bbe91cce | 6409d482-37ba-4100-90d4-6b3ae0012cc2 | /test/arnaud-test-folder/ | information-for-travelers.dot | file_asset |                 |
```

The asset type change is done here

https://github.com/dotCMS/core/blob/c4512b35e9e44362b93989be3902f500a948ee12/src/com/dotmarketing/beans/Identifier.java#L148

Where we ask if the page's extension matches with the configuration and, if the property is not even set in the Configuration, it defaults to .dot. When there's no match, it saves it as a legacy file. The only way to rollback this issue is by updating the asset type to 'htmlpage'.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7943

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
