### ISSUE TITLE
Unable to publish from a java8 server to other that use java 7 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7930]
When you try to make any push from a server that is running on java 8, to any server that use java 7, we are having an error and you can't make the push.... 

Here the log: https://gist.github.com/bryanboza/c5447a6389129ac81789

Tested from java7 to java8 and works fine, both cases using the same dotCMS version (last 3.2.2 release)

Since we continue supporting java 7, then we need support that case... 

Testing info: 
Sender:  Java8 // Release 3.2.2 // Postgres // Linux
Receiver: Java7 // Release 3.2.2 // H2 // Linux

**Comment by brentgriffin** [comment]
Personally, I don't think we should try to support this case.  I do think it would be a good idea for the integrity checker to verify that at least the major versions of java match and if they do not display an appropriate warning.

**Comment by levosgien** [comment]
We require customers to be running the same version of dotCMS, Java, and DB to expect Push Pub to work, underlining Brent's point above.
