### ISSUE TITLE
UI: Minor glitches in Languages Portlet 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7939]
Reproduced in 3.2.1. 

Steps: 
1. Go to Language Portlet and select "Edit Variables" for English (US) Language.
2. Add a Language Property. Click on "Save Changes".
3. Go to the Languages Dropdown and select "Español - España". 
4. You'll get a notification of changing languages without saving changes. Click on "Cancel". 
5. The selected language in Languages Dropdown (Español - España) displays the US flag instead of the Spain flag. Additionally, if changes were already saved, the prompt message from step 4 should not be displayed. 

Screencast: http://www.screencast.com/t/feEip34nY1B

**Comment by john-thomas-dotcms** [comment]
This is a minor glitch, but does come up in training when we show adding language variables.  It would be nice to make sure we review this after the UI upgrade to make sure it gets fixed during those changes.
