### ISSUE TITLE
Maintenance: Better logging for "Migrate HTML Pages to Content" tool

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7945]
Re: https://my.dotcms.com/ticket/dotcms-62

Reproduced locally after upgrading a DB from 2.5.7 to 3.2.2.

The Migrate HTML Pages to Content Tool returns "HTML Pages were succesfully migrated to Content" message in the UI, even if it fails. Here are the steps to reproduce it (according to tests done with client's data):

1. Deploy a vanilla install of 2.5.7 version. 

2. Create a /test/index,page.html page (the Add/Edit HTMLPage allows commas in the Page URL field).

3. Stop the 2.5.7 instance. Start a 3.2.2 instance pointing to the 2.5.7 DB and assets. 

4. Once it's fully upgraded, run a Full Reindex. 

5. Hit the "HTML Pages were succesfully migrated to Content" button on Maintenance portlet. 

Stacktrace:
```
2015-07-14 13:50:36,294 ERROR com.dotcms.content.elasticsearch.business.ESContentletAPIImpl -  URL is invalid
2015-07-14 13:50:36,294 ERROR com.dotcms.content.elasticsearch.business.ESContentletAPIImpl - com.dotmarketing.portlets.fileassets.business.FileAssetValidationException:  URL is invalid
List of non valid fields
BADTYPE: url/Url,
```

Exception is thrown here
https://github.com/dotCMS/core/blob/master-3.2/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L3571

Screenshot of Maintenance Portlet after it failed:

![screen-shot-2015-07-14-at-1 51 33-pm](https://cloud.githubusercontent.com/assets/1717110/8680709/15b00890-2a31-11e5-9b77-5445bb8c94e8.png)

**Comment by joseorsini** [comment]
Update: 

The callback for CMSMaintenanceAjax.migrateAllLegacyPages method is triggered before the Thread that converts all pages is run. So the user is getting a false positive over something that hasn't run yet, and additionally does not contain more information about potential issues during its execution.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7946

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
