### ISSUE TITLE
Role listing not alphabetical

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7949]
The roles listed in the roles tab also display in some sort of random order instead of alphabetically.

The only saving grace on this page is the filter, otherwise it would be impossible to find a role in our list of hundreds.

Here the SC: http://screencast.com/t/UCSWKsmX9YI

Tested on the last 3.2.2 release // H2 // FF

**Comment by bryanboza** [comment]
Maybe, we can do the same thing with the folders in the site browser, on backend

**Comment by mattyarbrough** [comment]
This remains an issue in 4.3.3, support requested on this from client.
