### ISSUE TITLE
Handle server failures during reindex

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#7950]
An intermittent failure to connect to the db during reindex can cause the reindex to never complete due to stuck queued records. A server that is failed out of the cluster (such as during an autoscaling action) during reindex could result in the same behavior. There are also fringe cases of heavy GC causing db connection timeout which could trigger this (in theory).

Basic reindex process is:
1) initially the dist_reindex_journal is filled with records with null server id
2) When the bulk selects the records to reindex updates the server id of those records
3) If the records fails to reindex we set back the server id to null for those records so those records will be pick it again
4) If succeeded those records are deleted from the table

If the failure occurs between #2 and #3 (after queuing and before success/fail) the records can be stuck in queue and will not be recovered which will cause the reindex to never complete. We need a cleanup mechanism to return the stuck records to the main (serverid=null) queue for processing by other server in this event.

Concerns are making sure the cleanup/re-queue mechanism is not too aggressive and will not re-queue records that are still in-processing from a server that is actually alive.

**Comment by jgambarios** [comment]
Related to changes made in: https://github.com/dotCMS/core/issues/7911

**Comment by nollymar** [comment]
Fixed on #16277

**Comment by dsilvam** [comment]
Passed Internal QA: 
Tested in Postgres with large dataset. 
The Reindex process is able to successfully resume after stopping the DB service and starting it after a short break (one minute, for example).

**Comment by dsilvam** [comment]
Test in Clustered environment will be tested here: https://github.com/dotCMS/core/issues/16475

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are able to return with the indexing process after stop the service for a while
