### ISSUE TITLE
Website Browser: Styling for assets marked as Show On Menu is broken

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7955]
Reproduced in client and locally running 3.2.2.

Steps:

1. Create a page and mark it as Show On Menu. Assign any random numeric value for "Sort Order" field.
2. Create a Link, mark it as Show On Menu. Assign any random numeric value for "Sort Order" field.

<img width="1266" alt="screen shot 2015-07-16 at 12 19 23 pm copy" src="https://cloud.githubusercontent.com/assets/1717110/8728795/4bb9ba28-2bb5-11e5-9efd-c83cd2dc98a2.png">

On view_browser_js_inc.jsp, validations for assets are not working when it tries to check if they're marked as Show On Menu. For Pages, the Show On Menu value is a string and possible values are true/false, but for Folders, Links and Legacy Pages, it's a boolean value. In code, we ask if it's greater than zero

https://github.com/dotCMS/core/blob/master-3.2/dotCMS/html/portlet/ext/browser/view_browser_js_inc.jsp#L817

https://github.com/dotCMS/core/blob/master-3.2/dotCMS/html/portlet/ext/browser/view_browser_js_inc.jsp#L895

In the screenshot above, we have a Page Asset and a Link, both of them marked as show on menu. They have different styling applied to the Sort Order field.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/7956

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-07-17 // H2 // FF
