### ISSUE TITLE
NPE creating a new file via webdav

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7970]
We are having a null pointer exception when you try to create a new file using the cyber duck client to connect via webdav ... 

Here the error: https://gist.github.com/bryanboza/e66d571118d0a08cea10

To recreate: 
- Connect via webdav 
- Create a new folder 
- In to this folder make a right click on cyber duck and select "create a new file" option 
- Type any name and click on create 

![test](https://cloud.githubusercontent.com/assets/2641437/8856683/873fb696-3129-11e5-9081-d5ecfaf5c0d7.jpg)

Tested on nightly build 2015-07-17 // H2 // FF // Cyberduck Version 4.5.2

**Comment by bryanboza** [comment]
Tested on demo.dotcms.com and works fine...

**Comment by jgambarios** [comment]
Related to changes made in: https://github.com/dotCMS/core/issues/7820

**Comment by rogelio-blanco** [comment]
PR #7974

**Comment by bryanboza** [comment]
Fixed, now you can create files from webdav
