### ISSUE TITLE
Upgrade from 1.9 to 3.2.4 fails on SQL Server 2012

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7976]
Issue seems to be related to #7931 but upgrade task is different: https://gist.github.com/shayngr/9162d6c3b3bec0610f6b

Reproduced while doing manual upgrade from 1.9 to 3.2.4 on 
3.2.4 Nightly build 2015-07-22 22:42 // Win7 Pro SP1 // SQLServer 2012 // Firefox

Steps to reproduce:
--> In dotcms 1.9 instance
1- Start up and apply the license to the distribution 
2- Upload some images, create a new structure, add some content to this structure
3- Shut down the server
--> In 3.2.4 nightly build 
4- Copy the assets folder from the 1.9 instance 
5- Configure to use the same database that the older version
6-Copy the page.extension.config.zip plugin in your plugin directory
7- Deploy the plugins
8- Start the server

Performed query (http://dotcms.com/docs/latest/database-configuration) to test what current settings are set for READ_COMMITTED_SNAPSHOT and ALLOW_SNAPSHOT_ISOLATION and they are set to true in SQL Server 2012 database

Same error is showing when I tried READ_COMMITTED_SNAPSHOT OFF

![read_committed_snapshot off](https://cloud.githubusercontent.com/assets/8741846/8884366/73cfd07e-3213-11e5-8885-0af67502ef37.png)

**Comment by jgambarios** [comment]
I was able to reproduce the issue on 3.2.4. 
This issue is related with the microsoft (**com.microsoft.sqlserver.jdbc.SQLServerDriver**) jdbc driver, using the old jtds (**net.sourceforge.jtds.jdbc.Drive**) driver I got no errors and the upgrade process was successful.

From Microsoft:
> Some DDL operations that are allowed inside snapshot isolation. For example, CREATE TABLE is ok because it did not exist. However, altering/creating index is not allowed. We are aware of this limitation and will look into it....

For reference, this is the original stack trace:
```
 Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
com.microsoft.sqlserver.jdbc.SQLServerException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
```
