### ISSUE TITLE
"Unable to flush hibernate session" when you create a folder and a page with the same name in the root

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7978]
If you create a page and a folder with the same name in the same location different than the root, the fix here #7264 is working properly, but when the page and the folder are created **in the root**, the error message is the following:

<img width="392" alt="unable to flush hibernate session" src="https://cloud.githubusercontent.com/assets/8741846/8880599/3d590a54-31f7-11e5-8064-27081cc5e0ad.png">

Steps to reproduce:
1-Login with admin
2-**In the root**, create a new folder ("Test")
3-**In the root**, create a new page (without extension) with same name as the folder you just created ("Test")
4-You will see the message "Unable to flush Hibernate Session"

https://gist.github.com/shayngr/835af5af62b893bd9e0a

Tested on:
3.2.4 Nightly build 2015-07-22 22:42 
Win7 Pro SP1
SQLServer 2012
Firefox & Chrome

**Comment by dsilvam** [comment]
This is also happening when you try to create two pages in the root with the same name (e.g. index and index). This is not happening when both pages are inside a folder.
