### ISSUE TITLE
Resize filter does not support images with CMYK as Color Space

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7981]
Reproduced in client and locally running 3.2.2. See https://my.dotcms.com/ticket/dotcms-66 for more info.

Steps to reproduce: 
1. Create an image in Adobe Photoshop and set CMYK as its color space. You can use this one for testing purposes https://www.dropbox.com/s/5p1sj5pzqtt1wlk/IMG_4365.jpg?dl=0 
2. Once you save and publish the image, right click on it and edit it. 

<img width="1257" alt="screen shot 2015-07-24 at 4 53 10 pm" src="https://cloud.githubusercontent.com/assets/1717110/8884437/a0c2e2fe-3224-11e5-938a-bb79e8d5a2b2.png">

<img width="1256" alt="screen shot 2015-07-24 at 4 52 55 pm" src="https://cloud.githubusercontent.com/assets/1717110/8884442/a3fc514e-3224-11e5-92bd-694f67db42e9.png">

If you try to pull the image using the REST API, you'll get the following error messages: 

```
sun.awt.image.ImageFormatException: Unsupported color conversion request
    at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
    at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:136)
    at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
    at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
    at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
...
2015-07-24 16:50:01,192 ERROR com.dotmarketing.image.filter.ResizeImageFilter - Unsupported Image Type
```

A suggestion from Will: 

> See:
> http://stackoverflow.com/questions/3123574/how-to-convert-from-cmyk-to-rgb-in-java-correctly
> We need to add something like
> https://github.com/haraldk/TwelveMonkeys

**Comment by joseorsini** [comment]
Update from client running 3.2.4: 

Client provided a logfile after a Reindex was made on their upgraded 3.2.4 instance (running SQL Server) and this error message showed up 

```
[04/11/15 06:35:22:237 EST] ERROR exporter.ImageFilterExporter: Exception in com.dotmarketing.image.filter.JpegImageFilter :Numbers of source Raster bands and source color space components do not match
```

It's still related to a mismatch between the ICC color profile and data from image itself. See http://stackoverflow.com/questions/18351583/illegalargumentexception-numbers-of-source-raster-bands-and-source-color-space/18400559#18400559

**Comment by jtesser** [comment]
Yea fwiw we have never really supported CMYK in our image manipulation tooling nor do we support images with layers like tiffs saved from photoshop. 

We can try to catch some of these cases though in the future

**Comment by lucidmachine** [comment]
Does PR #10423 close this issue? My own testing suggests that CMYK images can be resized in release 3.7.1.

**Comment by wezell** [comment]
It should Eric.
