### ISSUE TITLE
Integrity checker should be case sensitive 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7982]
The URL field is auto generated with the name when you are creating html pages, but if you edit this field manually and write the same name but with a uppercase, the system is not detecting the conflict, and when you try to push you have errors..

To recreate:
- On sender create a new page with the url: "Test"
- On receiver create a new page with the url: "test"
- Run the integrity checker 

Tested on nightly build 2015-07-22 // H2 // FF

**Comment by levosgien** [comment]
cards/103
