### ISSUE TITLE
VirtualLinkFactory should NOT be case-sensitive

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#7985]
If we have a Vanity URL like this one: /Family-Weekend-Reg and the request is /family-weekend-reg, the VirtualLinkFactory will not find the Vanity URL and mis cache the result. The main problem is that the cache is not case sensitive so the next time /Family-Weekend-Reg is requested will find a 404 in the cache.

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/virtuallinks/factories/VirtualLinkFactory.java#L43

**Comment by jtesser** [comment]
@jgambarios lets get this one in

**Comment by brentgriffin** [comment]
QA - note - we need to add to the Virtual Link automated test cases to cover this issue

**Comment by joseorsini** [comment]
Duplicated of https://github.com/dotCMS/core/issues/9258. PR includes fixed proposed on this ticket. https://github.com/dotCMS/core/pull/9525
