### ISSUE TITLE
Issues with plugins deployment and variables with extra white spaces on properties file

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#800]
This has happened on many clients that use plugins to override variables on src-conf/dotmarketing-config.properties.

There are some variables on this file that have some extra white spaces before and after the '=' character, e.g.

VELOCITY_PAGE_EXTENSION = dot

Many of the plugins we have done for clients (specially customized plugins) that should override variables like this one don't work at all because the plugin deployment process can't find the variables on the properties file and override them with the new values. 

After the white spaces are deleted, the variable is overriden as expected, but we shouldn't tell the client to edit the src-conf/dotmarketing-config.properties file directly, that's why we use the plugins.

Is there any chance we can get rid of these extra white spaces?

P.S. This also happens for any *.properties file (like portal.properties).

**Comment by wezell** [comment]
dupe: #11824
