### ISSUE TITLE
Error trying to push two bundles at same time 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8011]
We are having the follow error when you try to push any page and then try to push any bundle, both at same time...

To recreate: 
- Create a new folder with almost 4 pages
- Try to push one of the pages
- At same time add any of the pages to bundle and try to push remove

You will have an error because the table is locked... 

https://gist.github.com/bryanboza/f8bbb0ee6a634336aa8d

Tested on 3.2.4 PR // MySQL // FF

**Comment by levosgien** [comment]
/cards/102
