### ISSUE TITLE
Upgrade from 1.9 to 3.2.4 fails on SQL Server 2012. Task00820CreateNewWorkFlowTables

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#8016]
System is reporting issues when executing upgrade task Task00820CreateNewWorkFlowTables:

https://gist.github.com/shayngr/ff35c9842909a0b5dc02

Reproduced while doing manual upgrade from 1.9 to 3.2.4 on release candidate for 3.2.4 (http://dotcms.com/physical_downloads/test/dotcms_3.2.4.zip)
Win7 Pro SP1
SQLServer 2012
Firefox

Steps to reproduce:
--> In dotcms 1.9 instance
1- Start up and apply the license to the distribution 
2- Upload some images, create a new structure, add some content to this structure
3- Shut down the server
--> In 3.2.4 nightly build 
4- Copy the assets folder from the 1.9 instance 
5- Configure to use the same database that the older version
6-Copy the page.extension.config.zip plugin in your plugin directory
7- Deploy the plugins
8- Start the server

**Comment by jgambarios** [comment]
Related to #7976
