### ISSUE TITLE
Documentation: XssTool example

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#8019]
On the page http://dotcms.com/docs/latest/xsstool there is this text:

> The safe alternative would be &lt;input type="text" value=""/>

Is there some Velocity code there that is being interpreted rather than displayed?

**Comment by jkshapiro** [comment]
Noticed this again today

**Comment by john-thomas-dotcms** [comment]
Thanks for the heads up.  Please take a look again, I just updated the page.
