### ISSUE TITLE
We are generating new files when you edit any file without a extension via webdav

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8020]
Related to #7970 

After the fix, now we can create new files, but when you try to edit any via webdav, cyberduck is editing this files with the text editor, after you save the changes, the system is not saving the changes in the original, is creating a new one with the same name and add the inode at the end...

To recreate: 
- Create a new file without extension
- Select the created file and select the edit button 
- Add some text and save it 
- Refresh cyberduck and check for the new file 

Image here: http://screencast.com/t/5J6nSBDN

FYI: If you add extension to the file is working as expected 

Tested in the 3.2.4 preview release // Postgres // Cyberduck 4.5.2

**Comment by bryanboza** [comment]
Tested on 2.5 and we have the same problem....

**Comment by maurizo** [comment]
Pull Request: #8034

**Comment by bryanboza** [comment]
Fixed, tested on 3.2.4 PR // Postgres // FF.... Now works fine and yo can edit the file and save without problems
