### ISSUE TITLE
We need push the contents of the page when you push a menu link

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8022]
When you create a new page and a new menu link to this page, when you try to push publish this menu link, the system is sending the page by dependency, but we are not sending the contents of this page.... 

To recreate: 
- Create a new folder
-  Add a html page in the folder,  and add some new contents to the page
-  Create another folder and add a menu link in to this one, referencing the new page
-  Push the menu link
- Go to the receiver side and check for the contents of the page 

Tested on 3.2.4 preview release // Postgres // FF

**Comment by levosgien** [comment]
/cards/101
