### ISSUE TITLE
We need show the complete path of the page when you are creating menu links 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8024]
When you are creating a new menu link, we need show the complete path in the binary field.... Right now we are showing just the  name of the page and not the complete path, this can be confused because in a site you can have a lot of pages with the same name.... 

<img width="1058" alt="2015-07-28_1413" src="https://cloud.githubusercontent.com/assets/2641437/8942488/e3af4632-3532-11e5-96a0-8ef8726bd784.png">

SC: http://screencast.com/t/mEq5oVfj

Tested on 3.2.4 PR // Postgres // FF

**Comment by jkshapiro** [comment]
This is one example of a larger problem with that host/folder picker tool. It's used all over the place and it never gives you any information other than the name of the particular folder (which, as Bryan points out, is not guaranteed unique). See also #6807.
