### ISSUE TITLE
Pages disappear when I try to move a folder

### ISSUE THREAD

**Issue by jorith88** [dotCMS/core#8025]
##### Steps to reproduce on demo.dotcms.com:
- Navigate to the Site Browser
- Add a new folder 'testfolder1' to the root of the website
- Add a new folder 'testfolder2' to the root of the website
- Add a new page 'testpage' to 'testfolder1', I chose 'Quest - 1 Column' as template
- Right click on 'testfolder1' and click on 'Cut'
- Right click on 'testfolder2' and click on 'Paste'

##### Expected result:
testfolder1 is a subfolder of testfolder2 and the page in testfolder1 still exists

##### Observed result:
DotCMS shows an error message 'Unable to save/update Object to Hibernate Session'. Both folders are still at the same place, but are now empty

![Screenshot of error message](http://www.jorith.nl/github-images/move-folder-error-message.png)

**Comment by jorith88** [comment]
Also: plain content that is connected to the folder using a 'Site or Folder' field is also gone.

**Comment by oarrietadotcms** [comment]
Hi, this is duplicated https://github.com/dotCMS/core/issues/7872

#7872 is already market for 3.3 and has a developer assigned.
