### ISSUE TITLE
Improve cluster autowire scale-down

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8038]
ClusterFactory.removeNodeFromCluster is never called. HEARTBEAT_TIMEOUT should probably be used from a cluster-stateful job to rewire cache/ES after server loss.

https://www.flowdock.com/app/dotcms/support/threads/EaEahCmdZ2yBN3lCqI4xlJGbggn

**Edit:** Skype chat with Chris, further requirements

I think one job ("A") that does:
- frees the license
- updates the replica count
- rewires

and one ("B") that does:
- cleanup old servers from db

and when a new server comes in ("C"):
- allocates the license
- updates the replica count
- rewires

/////////

Job A should probably run every 5 minutes, maybe even every minute to check for expiration. B could probably run once an hour or even once a day.

The tricky situation is if you have this scenario:
2-node cluster, servers 1 and 2 (replica=1)

1. server 2 goes offline for maintenance (replica=1, yellow status)
2. server 3 joins cluster BEFORE the 2 comes back online or the rewire cron hits
3. server 2 comes back

/////////

The init when server 3 is added needs to not break the "pending" state of server 2 if 2 has not been expired yet
If 2 has expired (> 30 min) then its a 1-node cluster and we just treat 3 as a new addition

Basically, any server has a 30 minute window of downtime before the cluster thinks its gone for good re-arranges accordingly. Within 30 minutes, the server can still come back and nothing has changed
Just make sure that a server 3 init during that 30 minutes won't clean out the missing server
It should rewire WITH the missing server and increment the replicas

The thing is that ES will take the index offline if there are not a majority of shards (primary + replicas) online
So in that case, if we have 2 server and 1 leaves, then we have 1 server and 2 expected shards (50%, 2 shards is a special case that allows 50% to be a majority). If we have a new server added, then we have 1 server and 3 expected shards, 33%, until the replica is built on the new server, so it would go offline during that period

**Comment by jtesser** [comment]
same card as here https://github.com/dotCMS/core/issues/7860

**Comment by jtesser** [comment]
the scale down is not rewiring the cache

**Comment by oarrietadotcms** [comment]
@DeanGonzalez here you can find a [documentation draft for this task](https://docs.google.com/a/dotcms.com/document/d/1kNehS-4TJxKCYleumUlzjDnQg3aR4a-0C0v7vV1GLSA/edit?usp=sharing).

 @dsilvam @maurizo feel free to add/modify the doc in there to be included in our doc site.

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/auto-clustering-configuration

**Comment by dsilvam** [comment]
PR core: https://github.com/dotCMS/core/pull/9136
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/370

**Comment by dsilvam** [comment]
Additional changes core: https://github.com/dotCMS/core/pull/9155
