### ISSUE TITLE
Calendar Events: Events 'Add to Calendar' give incorrect end dates

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8041]
Reported by a client running 2.5.7
Reproducible in http://demo.dotcms.com/ (3.2.3)
Internal ticket: https://my.dotcms.com/ticket/dotcms-71

When clicking the 'Add to Calendar' button on an event detail page to download an ICS file, an incorrect end date is set in that file.

Steps to reproduce:

* Add an event on demo.dotcms.com (dotCMS 3.2.3) for August 3, 12:00 PM - August 4, 11:00 AM.
* When the ICS file is downloaded it has DTSTART:20150803T120000 and DTEND:20150803T110000. DTEND should be 20150804T110000.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8047

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // Potgres // FF
