### ISSUE TITLE
Remove JUnit jar file from released WAR file

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#8043]
JUnit is used for our automated unit tests.  Currently the jar file for JUnit is included with our other production libraries in the .../dotserver/tomcat-x.x.xx/webapps/ROOT/WEB-INF/lib directory.

We need to remove this file:  dot.junit-4.8.1_1.jar

Since the file is not part of the released code, it should not need to be repackaged and we should be able to use the unmodified version of JUnit.

**Comment by rogelio-blanco** [comment]
I think maybe in the future we should consider do something with tika jar because this is a fat jar and seems to me that it includes a lot more than we need.
