### ISSUE TITLE
Starter: Scroll bars in IE 11 when viewing pages in edit mode

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8045]
Reported by a client running dotCMS 2.5.7 and 3.2.3
Internal ticket: https://my.dotcms.com/ticket/dotcms-73

Scroll bars don't appear correctly when viewing large pages via the dotCMS backend in IE11. It's the combination of the 'Edit Mode' menu on the left side and a large page menu. The edit mode menu always extends a bit further than the bottom of the browser viewport, so you get an extra vertical scroll bar for that and a separate one for the page itself. When you have the browser maximized (and sometimes when you resize it) this second scroll bar disappears to the right of the viewport and you have to use a horizontal scroll bar to scroll across and make that second vertical scroll bar visible.

Steps to reproduce:

* Log into http://demo.dotcms.com/admin in IE11.
* Attempt to edit the "/index" page.
* Notice the bar on the right side. The one that actually scrolls down the content does not show up:
<img width="1242" alt="missing_bar" src="https://cloud.githubusercontent.com/assets/8779585/9065573/916a1b2e-3a8f-11e5-98a9-66525c1fda1c.png">

* The user needs to further scroll the horizontal bar to the right to see the second vertical scroll bar:
<img width="1243" alt="second_bar" src="https://cloud.githubusercontent.com/assets/8779585/9065598/db85fba6-3a8f-11e5-8580-c9d0153803d8.png">

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8056

**Comment by bryanboza** [comment]
Fixed, tested on dotcms_3.3 // Postgres // IE 11
