### ISSUE TITLE
Migration from 2.5.4 to 3.2.2 and container history fails

### ISSUE THREAD

**Issue by dim-s** [dotCMS/core#8050]
When I try to migrate from 2.5.4 to 3.2.2, history of the all containers is lost. Also, some of the containers has not the latest version of changes (on 3.2.2 after migration). 
The history of all the other assets is not lost.

**Comment by jtesser** [comment]
Not sure on latest version of changes as this does work for us.  Maybe you had an error upgrading BUT you will loose history here. It is in the changelog FWIW

**Comment by tbomer** [comment]
We are seeing the same issue going from 2.5.6 to 3.2.4.  Not only does the history get removed but the latest version is incorrect and seems to point to the oldest in the history in the 3.2.4.  I am trying to understand why you said "you will loose history here".  Why would the containers loose history on the migration?

**Comment by dim-s** [comment]
@tbomer Yes, we had the same thing. We had to manually restore all of the containers after migration.
