### ISSUE TITLE
We are not updating the content state when you pushing an archived content 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8052]
If you  create a pice of content, and push it, when you change the status on sender node, and try to push again, the system should be update the content status and create the new version with different inode.... this on receiver, that works for publish and unpublished content, but if you try the same for an archive that's not working, then we have two options here:

- Support the push transactions of the archived content  or 
- Delete the option to push archived content 

To recreate:
- Create a new piece of content on sender 
- Push it 
- Go to backend and update the content to unpublish
- Push again 
- Now update the content again but now archived
- Push again 

Tested on 3.2.4 PR // Postgres // FF, both environments with the same configuration

**Comment by levosgien** [comment]
/cards/100
