### ISSUE TITLE
Push Publishing: Integrity Checker fails when there are unpublished/archived assets

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8053]
Reproduced locally in 3.2.3 running with Oracle 11G and Java 7 and with client's data.

Re: https://my.dotcms.com/ticket/dotcms-76

Steps to reproduce: 

1. Deploy two 3.2.3 instances and setup a Push Publishing Environment between them. 
2. Run the Integrity Checker. 

Stacktrace: https://gist.github.com/joseorsini/ef4af2bedf31efda1ff5

Reasons why it's failing: 

- On Starter, we have 5 archived contents across our available sites (including System Host)

```
"ID","PARENT_PATH","ASSET_NAME","HOST_INODE","ASSET_TYPE","SYSPUBLISH_DATE","SYSEXPIRE_DATE"
"54b675be-49b5-4d4c-a8dd-659ff1bdc8c3","/","content.039f3ec5-c063-4077-baba-3aef5db08a38","SYSTEM_HOST","contentlet",,
"5d8814a5-a608-48fe-a0ad-1262aad9b1e6","/","content.e0639b67-98d6-44cb-8e07-2517f9db3e37","SYSTEM_HOST","contentlet",,
"b1521458-5a38-4639-84c2-adb5f3b12153","/","content.230a49a2-63ba-480f-a336-114e1762e228","SYSTEM_HOST","contentlet",,
"ce30838c-70e8-40db-a670-65e895ce12d1","/demos/","angular-comments-components","48190c8c-42c4-46af-8d1a-0cd5db894797","contentlet",,
"ec363a4c-33c4-4b3b-ab18-99ab9a598948","/application/vtl/pages/news/","angular-comments.vtl","48190c8c-42c4-46af-8d1a-0cd5db894797","contentlet",,
```

And our Integrity Checker does not exclude archived contents when it's run. The purpose of it may be related to avoiding pushing assets that may exist on the other end, but archived. It would fail anyways because of the DB Objects set in the Identifier table (triggers, unique indexes, etc...). 

- When the CSV files are generated on each side, again, we do not exclude archived or unpublished contents (see [here](https://github.com/dotCMS/core/blob/1b3905c605bff1fc1c76f9c4de125ba13dfba0b0/src/com/dotcms/rest/IntegrityUtil.java#L139)) for the reasons explained above. As we know, archived/unpublished versionable assets do not have a live_inode value on its versionable_version_info table, however, we're forcing a live_inode not null column [here](https://github.com/dotCMS/core/blob/1b3905c605bff1fc1c76f9c4de125ba13dfba0b0/src/com/dotcms/rest/IntegrityUtil.java#L783), therefore, the exception from the Gist above is thrown right [here](https://github.com/dotCMS/core/blob/1b3905c605bff1fc1c76f9c4de125ba13dfba0b0/src/com/dotcms/rest/IntegrityUtil.java#L827). 

The proposed solution would be to make this live_column as non null, so it would match the info we expect to store from versionable assets that may not be live.

**Comment by dsilvam** [comment]
Sounds good Jose, in addition would need to make sure to handle any potencial NPE from reading that live_column null value

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/98

**Comment by levosgien** [comment]
/cards/98

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/292
