### ISSUE TITLE
The integrity checker should be validate asset conflicts 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8058]
We have a hibernate session error when you try to push any asset and you have another one with the same name on receiver

You can recreate this issue uploading files from backend or using webdav, after upload the same file to both sides and then try to push we have the follow error:

https://gist.github.com/bryanboza/5ba7f8a3c8b4b2c94629

Maybe we need validate this case with a new tab in the integrity checker to the file assets 

Tested on 3.2.3 and 3.2.4  // Postgres // Cyberduck.... and have the same problem

**Comment by wezell** [comment]
I think the sender should overwrite the receiver in this case

**Comment by bryanboza** [comment]
This can be one solution, but here just need take in count that we need a type of confirmation message to avoid override important files by error...

**Comment by levosgien** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/84
