### ISSUE TITLE
High load and deadlock in VelocityServlet

### ISSUE THREAD

**Issue by dim-s** [dotCMS/core#8060]
I use dotcms 3.2.2. When I try to test the dotcms performance, my website freezes forever (after testing), but the admin panel works properly. I've found a place where execution is stopped (via debuging):

In VelocityServlet:
```java
...

	public void doLiveMode(HttpServletRequest request, HttpServletResponse response) throws Exception {
	    LicenseUtil.startLiveMode(); // <---- here execution is stopped, maybe deadlock?
	    try {
    		String uri = URLDecoder.decode(request.getRequestURI(), UtilMethods.getCharsetConfiguration());
    		Host host = (Host)request.getAttribute("host");

...
```

I use the loader.io service for testing performance, 1000 clients per 1 minute.

**Comment by jtesser** [comment]
OK so are you running something like Oracle DB without a license?  This would make sense if so. Or are you running a dev license.  

I don't think this is a bug.  Maybe try contacting support assuming you have a license or the forums

**Comment by dim-s** [comment]
I use a dev license and postgresql.
