### ISSUE TITLE
Make ES treat Empty as Null 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#8062]
So the problem is when ES has a type configured ie... https://github.com/dotCMS/core/blob/master-3.2/src-conf/es-content-mapping.json#L43 and that value is indexed in the content type and it has an empty string NULL in the DB then we store as empty string in ES and this is bad. 

For history https://www.flowdock.com/app/dotcms/developers/threads/XB9dDtlXMHhkfOoN2tL6gaTsU5d

So we should not be indexing empty string in ES but those empty string and NULLs should actually be NULL in ES.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8063

**Comment by shayngr** [comment]
Fix is working. No errors in logs when indexing content type containing "ipaddress" field with empty value.
Tested on dotcms 3.3 build // Win7 Pro SP1 // SQLServer 2012 // Firefox
