### ISSUE TITLE
Remove MaxPermSize from startup script

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#8067]
As 3.5 will support only JDK 8, we can remove MaxPermSize from our startup sh.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8068

Note: I created a new branch (8.0.18-master-3.5) for tomcat repo with the update in dotStartup.sh/bat. Now everybody running the instance from code will have the update also. I created a new branch because we still need to support JDK 7 until 3.5 is released.

**Comment by bryanboza** [comment]
Fixed, tested on 3.3 // Tested with java 7 does not work
