### ISSUE TITLE
Add/Edit Content > Relationship Tab > Relate multiple contents 

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#8071]
Content editors need to be able to relate multiple contents simultaneously so that the operation can be completed in one step.

How to reproduce current behavior:
1. Log into to demo.dotcms.com/c (3.2.3)
2. Go to Content > Content Search
3. Select (content) "Type" = Location
4. Click on the "Office Name" of any of the results so that you can edit that contentlet
5. Go to the "Relationships" tab and click on the "Relate" button so that you can relate existing content
6. On te search pop-up, click on the "Search" button without entering any filters. You should get 15 results displayed (paginated) in two groups: first page = 10 results, second page = 5 results.
7. Select a couple of results from the first page. Click on the "Next" button to go to the second page, and a select a couple of results from the second page.
8. Click on the "Relate" button.
9. Only the results from the second page will be related to the "Location" contentlet being edited.

Expected behavior:
All the results from all the pages selected in step 6 should be related to the "Location" contentlet being edited. The content editor should not be forced to repeat the relate process depending on how many pages the relatable contentlets results are being divided into.

<img width="1396" alt="screen shot 2015-08-12 at 12 31 05 pm" src="https://cloud.githubusercontent.com/assets/1569509/9230050/2b249cf8-40ee-11e5-98d0-b23e8d7f9755.png">
(Step 6)

**Comment by jkshapiro** [comment]
What's "Agile : Moved to Mingle"?

**Comment by jtesser** [comment]
We are going to be using a software called Mingle to manage dotCMS internally moving froward. We will have a what's coming roadmap and changelog soon on dotcms.com which will be available for clients. 

Github is still the place to enter issues and such but acts more as an inbox to us.  We are improving our Agile methodology which is what it driving this.
