### ISSUE TITLE
REST API: Anon User does not need "Add to" permissions to save a content object on a host

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8077]
if you set your `REST_API_CONTENT_ALLOW_FRONT_END_SAVING` configuration variable to `true` and give CMS_ANON role `edit` on a structure, you can still save content to a host, even if the CMS_ANON does not have "Can Add Children" permissions on that host. 

Try adding a different host - CMS_ANON can add content to it as well. This is not great in multi-tenant environments.

**Comment by wezell** [comment]
Here is the curl command to post into the contentlet API
```
curl -XPUT http://localhost:8080/api/content/save/1 -H "Content-Type:application/json" -d "{stName:webPageContent,languageId:1,title:test_content,contentHost:test,body:test_body}"
```

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/83
