### ISSUE TITLE
Tags which name is less than 3 characters are not populating in Suggested Tags window

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#8078]
If you have tags which name is less than 3 characters, the system is not showing it in "Suggested Tags" window. This is important because customer may want to create tags based on 2 char abbreviations (US States, countries, etc) or numbers.

Steps to reproduce:
1- Login with admin
2- Navigate to Content Types> Tag manager
3- Click Show Global Tags and create a few tags containing only 2 characters (LA, NY, Id, 50, etc) and save to All Sites
4- Add/Edit a new content (Blog) and under "Tags", type the name of the new 2 char tags you just created
5- Suggested Tags window will not display those tags. This window will only show tags which names has 3 or more characters

http://screencast.com/t/ekMFIBObqL

Tested on:
Release candidate for 3.2.4
Win7 Pro SP1
SQLServer 2012
Firefox & Chrome

**Comment by jtesser** [comment]
FWIW this is on purpose for performance reasons
