### ISSUE TITLE
Error initializing dotcms_3.3  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8082]
We are having a hibernate session error every time you initialize a fresh instance of this version...

Here the log: 
https://gist.github.com/bryanboza/35fa524272e5287ca624

Testing info: 
OSX  // Postgres  // tomcat8 // Java8 // Generated dist in 14 / 08 /15

**Comment by bryanboza** [comment]
FYI: The system starts, but have this errors

**Comment by rogelio-blanco** [comment]
PR #8085
