### ISSUE TITLE
Listing of versions in Content's History Tab not keeping the order

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8083]
<img width="1390" alt="screen shot 2015-08-14 at 3 50 33 pm" src="https://cloud.githubusercontent.com/assets/1576794/9283297/72142822-429c-11e5-966f-2d385bfefa22.png">

Listing is supposed to be order by mod date desc, but that is only true when all the versions are in cache.
When there are versions not present in the cache, and are retrieved from DB, the resulting list is not in order. 

List returned here is sorted: 
https://github.com/dotCMS/core/blob/master-3.5/src/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L905

But list here is not: 
https://github.com/dotCMS/core/blob/master-3.5/src/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L926

**Comment by jcanup** [comment]
We've noticed this same issue...
![history-sort](https://cloud.githubusercontent.com/assets/1828593/11130701/fddb26f8-894b-11e5-9576-4e8e7d6d2fb8.jpg)

**Comment by levosgien** [comment]
https://my.dotcms.com/tickets/detail.dot?id=c70efb6f-9d83-405d-a38b-e175302c198a

**Comment by oarrietadotcms** [comment]
Dupe: https://github.com/dotCMS/core/issues/13796
