### ISSUE TITLE
[core] Non-existing bundle referenced in contentlet Push History tab

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8084]
Reported by client running dotCMS 3.2.3
Internal ticket: https://my.dotcms.com/ticket/dotcms-83

Opening some contentlets for editing was suddenly displaying errors in the logs. Displaying the information in the front-end was working correctly, but trying to edit the contentlet data was generating this message: "Ooops, sorry. This has caused a problem. Try again". A NullPointerException was being thrown in the following line: https://github.com/dotCMS/core/blob/3.2.3/dotCMS/html/portlet/ext/common/edit_publishing_status_inc.jsp#L83

In line number 82, the BundleAPI is supposed to retrieve the Bundle object, based on the bundle ID that comes from the Push Publish History of the respective contentlet. However, the bundle cannot be found, the object is null, and eventually the "bundle.getOwner()" call throws an NPE.

**Comment by joseorsini** [comment]
Related to https://github.com/dotCMS/core/issues/8195

**Comment by rogelio-blanco** [comment]
In progress - Card#307
