### ISSUE TITLE
Site Search: Unpublished Legacy Pages are not removed from Site Search

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8086]
Reproduced with upgraded starter from 2.5.6 to 3.2.3. 

Steps: 

1. Set up a 2.5.x instance and upgrade it to 3.2.3. Apply an Enterprise License so Site Search feature is available. 

2. In Site Search Portlet, create an index called "sitesearch-default" and mark it as a Default index. 

3. In Website Browser, go to /services/investment-banking/index.html page and edit its content. Add a dummy text which will use as a search criteria in the next steps, like "Omnia sol temperat".

4. Go to //ful-site/vtl/widgets/full-site/site-search.vtl and in line 65, replace the $indexToSearch with the index alias name "sitesearch-test".

5. In Site Search, create a Site Search job that runs every 2 minutes. Add "demo.dotcms.com" site and index all contents. 

6. Upon its first run, go to frontend (/services/investment-banking/index.html) and in Site Search portlet and search for "Omnia Sol Temperat". One occurrence will be returned as a result, pointing to the page edited in step 3.

7. Before the job runs again, unpublish "/services/investment-banking/index.html" page. 

8. After the job runs for the second time, repeat the search in Step 6. Despite the page is unpublished, it will be listed. Clicking on the link returns 404 Error. 

Screencast: 

http://screencast.com/t/FckNe43J

**Comment by joseorsini** [comment]
Related to #6477

**Comment by wezell** [comment]
Outside cases with legacy pages are not going to be fixed moving forward.
