### ISSUE TITLE
Language in session doesn't change immediately anymore

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#8091]
To change the default language_id for a specific site we use the following Velocity code at the top of our template.vtl file:
#if($request.getServerName().toLowerCase().endsWith(".at"))
    $request.getSession().setAttribute("com.dotmarketing.htmlpage.language", "2")
#end

This worked well in dotCMS 3.0.1, but in dotCMS 3.2.3 it doesn't change the language immediatly for the current request, only for the next request.

Is there a new way to change the user's language in dotCMS 3.2?

We have different default languages for different sites. For example on site A we have default language_id 1, but on site B we need default language_id 2.

**Comment by jtesser** [comment]
Maybe what is hurting u is the page is now content.  Not sure if you converting.  I don't think this is a bug. 

I wonder what exactly is not changing for you.  This can be complex.  Is it content? widget? The page? 

Make sure this is set to what you want https://github.com/dotCMS/core/blob/master-3.2/src-conf/dotmarketing-config.properties#L16 

Maybe contact support if you have a license or take to the mailing list
