### ISSUE TITLE
Deploying the starter site removes all existing assets

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#8093]
All configuration properties including the database settings can be stored in the com.dotcms.config plugin, as is recommended. This has a downside, since undeploying the plugins and starting dotCMS will cause the starter site to be deployed. This is OK, but what has proven to be quite dangerous (in our case) is that when the starter site is deployed all existing assets are removed. So when you notice the problem during/after startup you can redeploy the plugins to fix dotCMS but your assets will be gone.

Could you guys think of a way to make this more safe? For instance:
- pause the startup with a warning message
- move/zip the existing assets somewhere
- only deploy the starter site when there is no assets folder or nothing in it
- remove the starter.zip at a certain time

We've had this problem 3 times now therefore we've created this issue. You can easily destroy your PRD environment by running undeploy-plugins + start instead of undeploy-plugins + deploy-plugins + start.

**Comment by wezell** [comment]
There is a configuration variable called STARTERSITE_BUILD that if that is set to false, will prevent the starter from being built.  

Secondly, the starter won't build if the /assets/starter.zip is not there (I think).  Why not just delete it?

**Comment by Xander-Steinmann** [comment]
The STARTERSITE_BUILD is a property that you'd probably set in the com.dotcms.config plugin, so if you undeploy the plugin you're still in trouble. If removing the starter.zip prevents the assets from being deleted then that's something that we'll start to do. Although I still think that a backup of the assets or something would be better.

**Comment by anwarkhadim** [comment]
Hi,

Not sure if this should be another issue. But Setting the STARTERSITE_BUILD=false (followed by a deploy-plugins) and starting the cms through 500 on all pages (even /admin).

This is from a fresh download of 3.2.4. We need a very thin starter pack without the demo site and assets.

Thanks

**Comment by brentgriffin** [comment]
Able to recreate on a clean install of 3.2.4 with no plugins.  
* Untarred release file of 3.2.4 on Ubuntu linux with Java 8 installed
* Set STARTERSITE_BUILD=false in ./dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/dotmarketing-config.properties and saved
* Started server via bin/startup.sh

Full log catalina.out here:  https://gist.github.com/brentgriffin/67d0d3a9fa9cd184f63d

**Comment by brentgriffin** [comment]
As it relates to the initial issue, a workaround would be to make sure that you configure your db and an alternative asset location in your config plugin.  If your ASSET_PATH is configured in your plugin to store the assets in another location then when the plugin is undeployed, assets will be safe.

Since your db and new asset location are only configured when the config plugin is deployed there is no chance they will be overwritten when the plugin is not deployed.

**Comment by anwarkhadim** [comment]
I am doing something different than the original issue. Shall I create a new Issue for just the STARTERSITE_BUILD=false, and 500's?
