### ISSUE TITLE
Website Browser: Cannot move (cut/paste) folders if the selected folder has sub-folders

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8094]
Reproduced in 3.2.4. Steps:

1. Start up a regular 3.2.4 instance. 
2. In Website Browser, go to **/news-events/news** folder. Create two subfolders (for example, 'files' and 'images').
3. Right-click on **/news-events/news** folder and click on 'Cut'.
4. Right-click on **/blogs** folder and click on 'Paste'. 

Exception thrown (only visible if we debug in eclipse)

```
Unable to save/update Object to Hibernate Session 
com.dotcms.repackage.net.sf.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: c0884a17-7699-4693-9049-ce626a8249c3, of class: com.dotmarketing.portlets.folders.model.Folder
```

The Website Browser says the folder was moved but the folder still remains in its original location. 

Proposed fix (tested)

After this [line](https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L697) I added this piece of code and it works.

```
HibernateUtil.getSession().clear();
```

Since this is happening only for folders with sub-folders when they're moved to a different folder, we can place this fix inside this [for loop](https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L687)

**Comment by joseorsini** [comment]
Update: If there is a Menu link in one of the subfolders, it throws a different exception and the folder is not moved. Tested in 3.2.4 and in demo.dotcms.com site. 

Steps: 

1. Create these folders in demo.dotcms.com site: 

/offices
/offices/finances/
/offices/finances/files/

2. Create a test Menu Link under /offices/finances folder.

3. Cut /offices/finances folder and paste it under /bear-mountain folder. 

Exception: 

```
com.dotmarketing.exception.DotSecurityException: User com.liferay.portal.model.User@cb1c722f does not have permission to read null
```

Problem comes [here]https://github.com/dotCMS/core/blob/1b3905c605bff1fc1c76f9c4de125ba13dfba0b0/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L233 despite the query returns a result if it's run directly against the DB, we're getting a null Hibernate object in the dh.load call.

**Comment by joseorsini** [comment]
@jtesser the last test I did was directly against demo.dotcms.com site. I tested locally as well without the fix I suggested on the ticket's description and had the same result.

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/167
