### ISSUE TITLE
Update DB configuration documentation on DBCP configuration properties change

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8095]
After the upgrade of DBCP from 1.x to 2.x, some configuration options in the xml were renamed. 

maxActive -> maxTotal
maxWait -> maxWaitMillis
removeAbandoned -> removeAbandonedOnBorrow, removeAbandonedOnMaintenance.

Also there are a few new configuration options:

timeBetweenEvictionRunsMillis
testWhileIdle 

Please see here: 

https://github.com/dotCMS/core/commit/166272b8b7eb8289d2a966b38af88a4c5b2f5a89

We need to include this renaming in the Documentation

**Comment by john-thomas-dotcms** [comment]
These were all documented a while ago
