### ISSUE TITLE
Problem with documentation search feature

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#8096]
When I am on the doc site (http://dotcms.com/docs/latest/table-of-contents) and search for "REST", I get no results displaying.  Clearly we have doc containing that key word but it is not showing up here.

In the screenshot below, notice the bar on the right shows that there are some entries for certain months and keywords.

If I search for "database" things seem to work correctly.

![image](https://cloud.githubusercontent.com/assets/3208956/9413122/9174f044-47f5-11e5-87b4-08f807f2026a.png)

**Comment by john-thomas-dotcms** [comment]
I've been adding keywords as I'm going through and updating the docs with old Wiki Titles (changing them to use the URL Titles instead). But to fix this for all the docs we either need to spend alot of time going through the rest of the docs (I've gone through maybe a third of them) or write something to automate it, based on a list of keywords to search through the docs.

Note that if we update these manually there's no good way to make sure we didn't miss any, so it will improve things but still might leave some gaps.

**Comment by jkshapiro** [comment]
Also reported as #7953. This is a major usability issue for the docs.

**Comment by john-thomas-dotcms** [comment]
Although updating the tags does help with this problem, I think the long-term solution needs to be to either automatically tag documents based on a pre-defined list of tags (which is still open to gaps in identifying the keywords on that list, and requires significant new functionality or pre-processing) or just allow a full-text search of the docs.

**Comment by wezell** [comment]
Yeah, we have an issue with the sitesearch mapping we are using for our doc site.   I opened an internal ticket on this but have not gotten a chance to get this resolved:

---
the site search on the doc site is not returning properly. Here is the case.

Go to the table of contents. 
http://dotcms.com/docs/latest/table-of-contents

The first bullet says:

dotCMS Now Runs on Java 8!
Search for "Runs"
http://dotcms.com/docs/latest/table-of-contents?q=runs

You get nothing back.

Now, it is probably the stemmer not running on the query (runs != match "run") but our mapping and sitesearch config should do a better job here.

If you search dotCMS Documentation "runs" from the content search screen, it returns the content property.

**Comment by levosgien** [comment]
Yea, try to search for "Plugin" or "plugins" and nothing returns.

**Comment by jtesser** [comment]
FWIW if u search for rest it works. Casing is an issue right now

**Comment by levosgien** [comment]
It actually looks like it completely broke. Nothing returns for anything I try: dotcms, Dotcms, upgrading-dotcms, Upgrade, upgrade, Upgrading, upgrading all

**Comment by john-thomas-dotcms** [comment]
This is a little bigger issue than I thought. I've been adding keywords to the Tags field for the documents as I edit them, to add appropriate search terms. But the search is not finding keywords in the Tags field, even when a Tag matches the specific search term (like "plugins") in the Tag field.

As an example, the "Configuring dotCMS Properties" page (docs/latest/configuring-dotcms-properties) has "plugins" (all lowercase) in the Tags field. But when you search for "plugins" (all lowercase) in the doc search, it doesn't find it.

**Comment by john-thomas-dotcms** [comment]
Is it possible the indexing isn't working right now? We're in the process of setting up a new authoring server, so I wonder if something isn't working there?

**Comment by wezell** [comment]
sitesearch is broke too:

http://dotcms.com/home/search-results.dot?q=performance

**Comment by john-thomas-dotcms** [comment]
This issue appears to have been resolved a while ago.
