### ISSUE TITLE
Add Ids of related content to the ContentMap and to the REST returns

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8099]
We need to add the relationships and their related ids to the ContentMap object and also insure that they are being included in our RESTful returns.

In a perfect world, I think our REST endpoints should be returning the ContentMap object (it would be great if the front end object and what is delivered via REST were identical.  Maybe this is REST API v2?

**Comment by DeanGonzalez** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/141
