### ISSUE TITLE
Feature request: Default language per site

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#8101]
In dotCMS there is only one global default language for all sites configured in the dotmarketing-config.properties file, which is not sufficient for our use case.

Here in Europe we have many different countries with different languages. Our requirements are for example:
- Site A for Germany with default language German (language_id 1)
- Site B for France with default language French (language_id 2)
- Site C for Spain with default language Spanish (language_id 3)
- Site D for Italy with default language Italian (language_id 4)
- And so on…

We cannot offer all languages on all sites, because the content maintenance would be too expensive. So we offer only one language on each site, the main language of each country.

Please try to implement a new (enterprise) feature for the next release of dotCMS, which enables the CMS Admin to define a default language for each site. Maybe a drop down list with all available languages under System -> Sites -> Add/Edit Host would be a good solution.

**Comment by wezell** [comment]
It is possible to do this using the rewriteFilter

http://dotcms.com/codeshare/set-language-by-site-or-folder

**Comment by jkshapiro** [comment]
See also #5556

**Comment by splotzky** [comment]
Great, thanks! This is truly a well-hidden feature in dotCMS. Hard to find.
I believe that my suggested solution would be more obvious for the CMS Admin.
But anyway, thank you. The UrlRewriteFilter works fine for me.
