### ISSUE TITLE
dotCMS Back-end Link to Support Portal Wrong

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8107]
dotCMS links to old support site, need to change "dotcms.org/support" to "https://my.dotcms.com".

* User Menu (top right)
* Support
![screen shot 2015-08-27 at 9 54 22 am](https://cloud.githubusercontent.com/assets/1823543/9522233/ab5e1ab6-4ca1-11e5-986a-383900b4d659.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8437
