### ISSUE TITLE
Add swallowOutput to Context to de-dupe logging

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8116]
From https://tomcat.apache.org/tomcat-8.0-doc/config/context.html#Common_Attributes:

If the value of this flag is true, the bytes output to System.out and System.err by the web application will be redirected to the web application logger (log4j). If not specified, the default value of the flag is false and system logging will be duplicated to catalina.out.

**Comment by chrismccracken** [comment]
This option doesn't seem to actually work. It would be nice to stop duplicating these logs though.

**Comment by chrismccracken** [comment]
We should probably be disabling catalina.out altogether in dotserver/tomcat-8.0.18/bin/catalina.sh.

From https://tomcat.apache.org/tomcat-8.0-doc/logging.html#Console:
> The default logging configuration in Apache Tomcat writes the same messages to the console and to a log file. This is great when using Tomcat for development, but usually is not needed in production.

> Old applications that still use System.out or System.err can be tricked by setting swallowOutput attribute on a Context. If the attribute is set to true, the calls to System.out/err during request processing will be intercepted, and their output will be fed to the logging subsystem using the javax.servlet.ServletContext.log(...) calls.
Note, that the swallowOutput feature is actually a trick, and it has its limitations. It works only with direct calls to System.out/err, and only during request processing cycle. It may not work in other threads that might be created by the application. It cannot be used to intercept logging frameworks that themselves write to the system streams, as those start early and may obtain a direct reference to the streams before the redirection takes place.

Right now, most logging is done in triplicate, geerating 3x i/o load and disk usage.
* catalina.out (stdout)
* catalina.2015-09-01.log (JULI)
* dotcms.log (Log4j)

This could definitely use some cleanup.

**Comment by john-thomas-dotcms** [comment]
I checked this out, and it appears the swallowOutput feature may only be intended to capture output from applications that write to stdout/stderr, not from Tomcat itself.  Instead I found that you can modify the Tomcat logging.properties file (dotserver/tomcat-X.x/conf/logging.properties) to disable Tomcat console output.

I updated the logging configuration doc with specific instructions (http://auth.dotcms.com/docs/latest/logging-configuration#ApplicationServerLogFiles), and added a section on logging configuration to the Performance Tuning doc (http://auth.dotcms.com/docs/latest/performance-tuning#LoggingConfiguration).

Long-term, we might want to consider changing our Tomcat distribution to use Log4j instead of the default Tomcat logging functions (e.g., https://tomcat.apache.org/tomcat-8.0-doc/logging.html#Using_Log4j).  In addition to making the documentation simpler (since we use Log4j for dotCMS already), it would also make one less thing the user needs to learn/understand.

**Comment by wezell** [comment]
I like where this is going but don't we need stdout?  How are we going to get threaddumps, for example?  Does that write somewhere else? Also, stdout is important to debug issues when your dotCMS does not start up - like when you have a bad osgi plugin....

**Comment by brentgriffin** [comment]
I would stop short of recommending they turn of Tomcat console logging.  When things go bad, especially on upgrade or startup, this is where we look.  If there is too much noise to standard out, we should have a separate issue that looks at and fixes the offending code.  I believe with 3.3 the catalina.out logging is much more reasonable.

**Comment by john-thomas-dotcms** [comment]
In 3.3 the default log4j configuration prevents dotCMS messages from writing to the console, so without changing anything the only messages logged to the Tomcat console are Tomcat messages.  For the starter site there aren't any Tomcat messages in the console except during startup and shutdown, but I don't know if there would be other console messages in larger production systems.

Note that when Tomcat console logging is disabled, it only disables console output for Tomcat messages (and writes them all to catalina.out, so they're not lost).  Any output from an app that writes to stdout or stderr still writes to the Tomcat console (including dotCMS when we set up log4j to write to the console); the swallowOutput feature is supposed to be able to capture this output, but swallowOutput isn't mentioned in our docs right now.

So regarding threaddumps, if they're written to stdout or stderr (without going through log4j), then they should still be displayed in the Tomcat console - but we might want to test to verify.

**Comment by chrismccracken** [comment]
Correct me if I'm wrong, but I *think* the date-rotated catalina-....log files should still be capturing everything that catalina.out gets (or can be configured to do so). I strongly favor getting rid of catalina.out if at all possible, its very difficult to manage due to its non-rotating nature (requires app restart to rotate externally).

**Comment by john-thomas-dotcms** [comment]
FWIW, running 3.3 on Windows I get no "catalina.out" file - the only Tomcat logs I have are the ones that roll by date (catalina.2015-12-09.log, catalina.2015-12-10.log, etc.).

And yes, so far the date-rolled Tomcat logs have captured all the Tomcat messages that go to the console and any dotCMS messages that go to the console (when either or both is configured to write to the console).

So I think everything will still be captured, but I'm running a pretty simple case so I'm not sure if there are any types of messages that would be missed.

**Comment by john-thomas-dotcms** [comment]
Chris, at this point I think we've addressed this in the docs: http://auth.dotcms.com/docs/latest/logging-configuration#ApplicationServerLogFiles

Can you review it, and close this if appropriate?  Thanks.
