### ISSUE TITLE
Improve log messages when hardlinks can't be created

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#8117]
When a hard link can't be stablished (e.g. dotsecure and assets directories are in different filesystems), an error message gets logged like this:

```
ERROR com.liferay.util.FileUtil - Can't create hardLink. source:... destination:...
```

Since it falls back to regular copy instead, it should be a WARN message providing some additional info

**Comment by dsilvam** [comment]
Already fixed in this commit: https://github.com/dotCMS/core/commit/ae081bda4c9ec3757cfee68e3b8737d81247e2a7#diff-4f5ae681fcd7777819310cee46a28d71

Current version in master-3.7: https://github.com/dotCMS/core/blob/dde8c0cc718c30a09f0e80d4d64a1568c706fcca/src/com/liferay/util/FileUtil.java#L189

**Comment by dsilvam** [comment]
Fixed in https://github.com/dotCMS/core/issues/9197
