### ISSUE TITLE
Push publishing of unpublished content

### ISSUE THREAD

**Issue by aotearoan** [dotCMS/core#8127]
We would like to propagate the unpublishing of content via push publishing.

The current workaround of publishing and setting the expiration time is clumsy, not very intuitive and is prone to human error.

The ideal solution would be to see "Push Unpublish" in the workflow actions for content that has been unpublished in the local environment.

**Comment by jtesser** [comment]
The solution to this is 

1. Unpublished your content and then push.  It will push the current state 
2. Push a Delete.  This removes the content on the other end

**Comment by aotearoan** [comment]
This doesn't work when using workflow, can you please reopen.

**Comment by jbjornson** [comment]
The "Push to delete" option only shows up on the push dialog in a few very specific situations.  When workflow is enable there is no "Push to delete" option on the push dialog.  There is also no option to push a delete when setting up workflow actions, so there is no way to "push to delete" for us, and the suggested alternative is very unappealing.
