### ISSUE TITLE
CMS reorders workflow actions

### ISSUE THREAD

**Issue by mcenkar** [dotCMS/core#8129]
On demo30.dotcms.com go to `Workflows` -> `Doc Mgmt` -> `Published` -> `Archive`.

Current order:
Unpublish; Unlock; Archive

Now drag `Archive` to 2nd place and `Save`. It gets restored in 3rd place instead.

If this doesn't work then you can recreate bug by reordering other actions. Bug is not really deterministic but we see it on our env, on demo.dotcms and on demo30.dotcms.com. It affects random combinations of sub-actions. Sometimes by adding and straight-away removing another action you can reorder previous actions.

**Comment by john-thomas-dotcms** [comment]
This is still an issue.  The only way to reliably reorder workflow sub-actions is to delete all the sub-actions and re-add them in the order you want them to appear.

**Comment by john-thomas-dotcms** [comment]
Related: https://github.com/dotCMS/core/issues/7757, https://github.com/dotCMS/core/issues/7801
