### ISSUE TITLE
Pages with "Show on Menu" do not show up in root folder

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8151]
If you create a page in the root folder and check "Show on Menu", it should show up in the menu.

It does not because the logic of this code was not changed for "Pages as content"
https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/viewtools/navigation/NavTool.java#L102

**Comment by john-thomas-dotcms** [comment]
Seen by a new customer in training (because they wanted to do this for their site).

Suggested Workaround: Create a top-level folder with the name you want to show in the menu, and then create a Vanity URL to redirect from that folder URL to the appropriate page URL.  Ugly, but it works.
