### ISSUE TITLE
Push Publishing should with case insensitive folders

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8152]
When you create a new folder on sender in upper case and the same folder with the same name on receiver, but this with lower case, the integrity checker is not detecting conflicts, but if you try to push this folder the bundle fail

Steps:
- Create a new folder on sender: TEST
- Create the same folder on receiver: Test 
- Run the integrity checker 
- Add content to the folder and try to push 

Tested on Nightly Build 2015-09-11 // Postgres // FF, this on both sides

**Comment by bryanboza** [comment]
Reported on US#265

**Comment by jkshapiro** [comment]
The bigger change, better for usability, would be to make folders and filenames case-insensitive altogether.

**Comment by wezell** [comment]
This should not fail.  It should just overwrite the existing folders as it should be case insensitive.

**Comment by erickgonzalez** [comment]
After doing the following test:

1- Create a folder in the sender (name with uppercase)
2- Create a folder in the receiver (name with lowercase)
3- Try to PP

The PP fails because there is already another folder with the same name but diff id, went to check the IC and it catches the conflict. 

Here is the error on the log: https://gist.github.com/erickgonzalez/1a58f4fc7c6cf2d8570ccc34fe1fe52a

**Comment by erickgonzalez** [comment]
After fixing the previous error the PP still fails. The IC only updates the inode and the identifier of the folder, not the name.

Log https://gist.github.com/erickgonzalez/dc8173619adb572c98031d7aaa45cb0e

**Comment by erickgonzalez** [comment]
After the changes on https://github.com/dotCMS/core/issues/11762 the name of a folder is saved in lowercase (on the identifier table) so when you try to PP folders with diff case it now succeeds. The only issue you might find is that the Inode of the Folder is diff but as explained above this is caught by the IC and fixed. Do we want to avoid this check and PP even if the Inode of the folder is diff but the name and the parent_path are the same?

**Comment by bryanboza** [comment]
We are having some problems reported in the card #11829.... We need wait this fix to make sure everything works as expected

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres

**Comment by john-thomas-dotcms** [comment]
Doc note added to this section to highlight that folder names are case-insensitive: https://auth.dotcms.com/docs/latest/pushing-hosts-and-folders#Notes
