### ISSUE TITLE
Navtool doesn't expose showOnMenu as a property

### ISSUE THREAD

**Issue by hyperfire4590** [dotCMS/core#8154]
Cannot access showOnMenu property of nav items created through navtool.  Is an issue when using navtool for crumbtrails, as it will show all parents regardless of showOnMenu status, since a nav item still has a parent, even if the parent isn't showOnMenu true.  
http://dotcms.com/docs/latest/crumbtrails

Simplest solution likely to add showOnMenu as a nav item property.
http://dotcms.com/docs/latest/navigation-and-menus

**Comment by joseorsini** [comment]
Tested this as a hotfix in 3.3.1.

1. Added "this-is-a-test" folder under /about-us/our-team. Checked "show On Menu" box.
2. Checked "show on Menu" box for /about-us/ and /about-us/our-team/ folders.
3. Added page under  /about-us/our-team/this-is-a-test folder, called "navigate".
4. Added code to newly created page. 
5. Debugged committed classes as per client's recommendation https://my.dotcms.com/tickets/detail.dot?id=a461941e-e54a-462c-9e28-009389879207 and still show On Menu value is not retrieved properly, despite the NavResult built when NavTool is called IS assigning the right Show On Menu values to Menu Items (Folders).

**Comment by joseorsini** [comment]
Added missing showOnMenu property to NavResult. It was only setting these values to a specific folder/path's children assets. Tested on 3.3.1 + Postgres 9.4.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8789
