### ISSUE TITLE
Integrity checker is not working on Oracle as default 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8161]
We are having some problems when you start a fresh instance of dotcms, using oracle and run the integrity checker... We have one page and one file archived in our starter zip, and Oracle is having problems because the live versions of those files is null 

These are the files: 
=> /demos/angular-comments-components
=> /application/vtl/pages/news/angular-comments.vtl

After run the integrity checker, you will have the follow error: https://gist.github.com/bryanboza/d2ea1cbe192f723bad9d

Also, if you unarchive and publish these files, and try again, everything works fine 

Tested on master-3.3 // Oracle 11g // FF on both sides

**Comment by bryanboza** [comment]
Also we have the same problem when you use H2 as database

**Comment by jtesser** [comment]
So the integrity checker should not fail in the case of an archived asset.  

Push Receiver should handle archived assets by recovering them and saving their state as received in the bundle
