### ISSUE TITLE
Cookies being duplicated on domains

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#8174]
see 
![image](https://cloud.githubusercontent.com/assets/1486445/10075589/87d1b788-62a4-11e5-8fc9-e4c75f14e055.png)

Notice the cookies on .dotcms.com or .demo.dotcms.com duplicated keys

**Comment by levosgien** [comment]
https://my.dotcms.com/ticket/dotcms-102

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/394
