### ISSUE TITLE
Dynamic Plugins' load folder cannot be set outside felix folder

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8181]
Reproduced in 3.2.4. Steps. 
- Add this property to a plugin's dotmarketing-config-ext.properties file

**felix.felix.fileinstall.dir=/home/your_user/dotCMS/felix/load**
- Make sure the "load" folder does not exist under {dotCMS_HOME}/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/felix/ folder.
- Redeploy plugins and start your 3.2.4 instance. 
- Compile the com.dotcms.viewtool OSGi plugin for testing purposes. 
- Once the server is up and running, upload this plugin to the Dynamic Plugins portlet.

Stacktrace: 

https://gist.github.com/joseorsini/dffad746af51cc285d92

Workaround: 

Set a symlink inside {dotCMS_HOME}/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/felix/ folder that would point to the right location of the "load" folder, along with the Felix property on plugins

**Comment by joseorsini** [comment]
Please see https://my.dotcms.com/ticket/dotcms-103

**Comment by chrismccracken** [comment]
Relocating only the felix load/ directory can be done, but will cause problems with the OSGI portlet and plugin start/stop/undeploy unless the undeploy/ directory is also relocated. Currently we do this via symlinks with no config:

>$ ls -l ./dotserver/tomcat-7.0.54/webapps/ROOT/WEB-INF/felix
>drwxr-xr-x  2 dotcms dotcms   4096 May 24 18:09 bundle
>drwxrwxr-x 21 dotcms dotcms   4096 May 29 15:34 felix-cache
>lrwxrwxrwx  1 dotcms dotcms     37 May 29 15:29 load -> /opt/dotcms/shared/assets/felix/load/
>-rw-rw-r--  1 dotcms dotcms 216559 May 24 21:46 osgi-extra.conf
>-rw-rw-r--  1 dotcms dotcms 211597 May 24 21:43 osgi-extra-generated.conf
>lrwxrwxrwx  1 dotcms dotcms     43 May 29 15:29 undeployed -> /opt/dotcms/shared/assets/felix/undeployed/

See also: 
https://github.com/dotCMS/core/issues/7675
https://github.com/dotCMS/core/issues/7673

**Comment by dsilvam** [comment]
Fixed here : https://github.com/dotCMS/core/issues/10370
