### ISSUE TITLE
Cache initial_hosts list is being init'ed incorrectly

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8196]
The initial_hosts list that is being generated to initialize jgroups/guava cache cluster is being generated incorrectly. The list SHOULD contain each member of the cluster with the designated or autoconfigured CACHE_PORT like hostname1[cacheport],hostname2[cacheport], etc...  However, what is actually happening is that for each cluster member, the hostname is being included twice- once with hostname[cacheport] and once with hostname[cacheport + 1]. On a 2-node out-of-the-box cluster with autowire, this looks like "initial_hosts=172.16.141.11[7800],172.16.141.12[7800],172.16.141.11[7801],172.16.141.12[7801]". This is verified happening with both autowire and manual cluster config. This is even happening on a single standalone server ("initial_hosts=172.16.141.11[7800],172.16.141.11[7801]"). The code that is generating the cacheport+1 seems to be here https://github.com/dotCMS/core/blob/3.2.4/src/com/dotmarketing/business/DotGuavaCacheAdministratorImpl.java#L194 but the issue is likely upstream of where ClusterFactory.getNextAvailablePort() is being called as it should not be getting there.

While most of the time this does not cause any actual problems due to nothing running on the cacheport+1 port, in the rare case that the client has something else configured to run on that port then the dotCMS cache service will send cache communication packets to that other destination which can cause problems with that service.

This issue has been observed on several clients, but can generally be worked around with proper configuration.

**Comment by oarrietadotcms** [comment]
Link to flowdock thread: https://www.flowdock.com/app/dotcms/developers/threads/UAiit7AIG_kizFNYZ609xI8yk4N

Important notes from thread: 

From http://www.jgroups.org/manual/html/user-advanced.html#d0e2494
> 5.3.3.1. Using TCP and TCPPING … TCPPING will try to contact both HostA and HostB, starting at port 7800 and ending at port 7800 + port_range, in the above example ports 7800 - 7802. Assuming that at least one of HostA or HostB is up, a response will be received. To be absolutely sure to receive a response, it is recommended to add all the hosts on which members of the cluster will be running to the configuration....

From @chrismccracken:
> …just be sure to verufy that initial hosts is getting set up right when you use ports other than 7800. multi-instances on the same host should do it

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/369
PR core: https://github.com/dotCMS/core/pull/9103
