### ISSUE TITLE
Add a confirmation prompt to workflow actions such as Archive and Delete

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#8209]
It's easy to accidentally hit the wrong button when editing content, such as accidentally hitting the Archive button (I did this recently with Documentation on the dotcms.com site).  If you realize you made a mistake, this is easy to fix, but if you don't realize you hit the wrong button (for example if you thought you hit Publish), this can cause content on the site to go missing without anyone realizing it.

It would be very nice to have an option to require a confirmation for workflow sub-actions such as Archive Content, Delete Content, and Unpublish Content which are, in different ways, destructive to the site.

Notes:
1. This confirmation could be on the individual Subaction parameters, or in the parameters when editing the workflow Action itself.  But adding a confirmation option to the workflow Action would be a more general solution, allowing users to add confirmation to any workflow action (even publishing or saving) if they wish.
2. However this might be implemented, it would be ideal to also allow users to specify the text that will be displayed in the confirmation prompt.

**Comment by jkshapiro** [comment]
Please consider doing usability testing on this feature. Confirmation messages are generally deprecated in the user experience world: see, e.g. http://www.uxdesignedge.com/2010/06/are-you-sure-how-to-write-effective-confirmations/ and the Aza Raskin article linked to therefrom. It's possible that a confirmation message is the best choice here, but that's an assumption that wants testing.

**Comment by john-thomas-dotcms** [comment]
Kivi brings up a good point.  However since the intent is to provide confirmation as an option, it shouldn't change usability as long as the default state of the option is off (e.g. no confirmation, the same behavior as now).

And to a couple points of the referenced article:
- As long as there's only a confirmation on rarely used options a confirmation could add value (but while Archive might be rarely used for most sites, it's also possible that for some relatively static sites a confirmation might make sense on publish or push as well).
- Since accidental actions can cause unwanted content to be published or unpublished, there is a significant potential impact of a mistake.  So a confirmation may be a good UI choice, depending on the nature of the site.
