### ISSUE TITLE
Workflow "Unpublish" does not unpublish the published version of the content when lock required

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8224]
Tested on demo.dotcms.com and dotcms.com

Unpublish actionlet works if you DO NOT require a lock on the content in the workflow action.  However, if you do require the lock, then the "unpublish" actionlet will not unpublish the live/published version of the content... it acts like a save instead.

Here is the screenshot of the settings that fail to unpublish:
![unpublishfail](https://cloud.githubusercontent.com/assets/1569167/10355148/a0eee1ec-6d25-11e5-8f08-b07590af99c1.jpg)

For how to reproduce: see the screencast: http://screencast.com/t/TygUQ5eWf

**Comment by levosgien** [comment]
Reported: https://my.dotcms.com/tickets/detail.dot?id=a76d8e49-f455-4acb-91e4-555ee9236928

**Comment by levosgien** [comment]
https://github.com/dotCMS/core/issues/8130
