### ISSUE TITLE
Enhancement: persistent feedback messages

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#8225]
In several cases, dotCMS provides a response to the user that flashes onscreen and disappears again. One example is when you flush the caches: once the process finishes, an overlay dialog appears and disappears right again. This means that if you're looking somewhere else (because why would you bother watching dotCMS flush its cache?) then you can miss the message.

All feedback messages should be persistent, disappearing only when dismissed by the user.

**Comment by jtesser** [comment]
the solution here is the notification center but yea
