### ISSUE TITLE
Tab Divider in Submit Content form shows variable in form crumbtrail

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#823]
Tested on the 2.1 release version.

Forms with tab dividers work fine because there is a system field called "formTitle" that the crumbtrail on a tab-divided form uses.  

However, the submit content form used with a normal structure that does not have a field called "formTitle" ends up throwing the velocity variable into the form crumbtrail at the top of the form:

http://screencast.com/t/dyUmlUKAoK

We should probably default to display the title on the structure or the first text field on the structure (not sure what should be default), when $formTitle is not set, but we should not be spitting the variable out in the crumbtrail.

**Comment by wezell** [comment]
will fix in 4.x
