### ISSUE TITLE
KEEP_SESSION_ALIVE property is not respected in backend sessions.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8237]
Even if the KEEP_SESSION_ALIVE property is set to false, we're still hitting the Notifications REST API every 5 seconds. This is keeping the session alive even if it has been inactive for the last 15 (if it's set to true) or 30 minutes (if it's set to false).

Internal ticket for 
https://my.dotcms.com/ticket/dotcms-109

**Comment by jtesser** [comment]
This is a duplicate but yes agreed
