### ISSUE TITLE
Deleting related contents is not working properly

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8257]
Reproduced in 3.2.4. Related to https://my.dotcms.com/ticket/dotcms-111 

Steps.

1. Go to http://demo.dotcms.com/blogs/bill-ackman-s-top-stock-picks and add 4 comments to the Blog. 
2. Login to the backend and check out the "Bill Ackman's Top Stock Picks" content. 
3. Check that the 4 comments are displayed in the Relationships Tab. 
4. Remove 2 comments from the Related Contents list and Save/Publish. 
5. Check in frontend page that the contents were removed. It will only show 2 contents. 
6. Go back to backend and remove all related contents for this Blog entry. Save/Publish. 
7. Both backend and frontend views still show the 2 remaining contents. 

Hitting a full reindex will remove them from the Index. 

Screenshots: 

- Content in Frontend, with 4 related comments: 
![screen shot 2015-10-20 at 9 49 41 am 2](https://cloud.githubusercontent.com/assets/1717110/10609272/e6f5bbe4-7710-11e5-814a-d6f72b43fe69.png)

- Content in Backend, showing 4 related comments: 
<img width="1077" alt="screen shot 2015-10-20 at 9 49 47 am" src="https://cloud.githubusercontent.com/assets/1717110/10609276/ee7bdc04-7710-11e5-80f4-0f50332c109f.png">

- Frontend view after removing ALL comments.
![screen shot 2015-10-20 at 9 51 08 am 2](https://cloud.githubusercontent.com/assets/1717110/10609302/094b861a-7711-11e5-999d-2083b79a28d1.png)

- Backend view showing 2 related contents, despite we deleted ALL related contents and saved/published it.
<img width="1086" alt="screen shot 2015-10-20 at 9 51 08 am" src="https://cloud.githubusercontent.com/assets/1717110/10609317/1d44ba56-7711-11e5-9d40-51790af773fc.png">

**Comment by joseorsini** [comment]
From local tests: 

- Relationships in database after all 4 comments were added to the Blog Entry.

```
324dist=# select * from tree where parent = 'a2204140-303f-4402-b22f-b8fad8d30bdf';
                child                 |                parent                | relation_type | tree_order
--------------------------------------+--------------------------------------+---------------+------------
 2712ff7f-4daf-43ec-b40b-4d57d2eaa904 | a2204140-303f-4402-b22f-b8fad8d30bdf | Blog-Comments |          1
 1d1173b4-1d65-4fa8-ad1a-0ce8b65a61de | a2204140-303f-4402-b22f-b8fad8d30bdf | Blog-Comments |          2
 d274592f-b539-48fb-850c-d7c501ed053b | a2204140-303f-4402-b22f-b8fad8d30bdf | Blog-Comments |          3
 b3b6815d-b00a-4f22-a272-cae3746b012d | a2204140-303f-4402-b22f-b8fad8d30bdf | Blog-Comments |          4
(4 rows)
```

- Relationships in Database after all 4 comments are removed from the Relationships Tab. They still show up on index and Frontend/Backend. 

```
324dist=# select * from tree where parent = 'a2204140-303f-4402-b22f-b8fad8d30bdf';
 child | parent | relation_type | tree_order
-------+--------+---------------+------------
(0 rows)
```

**Comment by jtesser** [comment]
@joseorsini I think in 3.3 we fixed this.  Seems to be working.  @bryanboza next week can you confirm
