### ISSUE TITLE
3.x Ignores page dependencies when deleting templates

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8264]
Ref: https://my.dotcms.com/ticket/dotcms-112

in 2.x dotCMS would warn to remove dependencies on pages using a specific template (see below). In 3.x, the template is deleted regardles.

Steps to reproduce:
* Go to demo.dotcms.com AND demo2.dotcms.com
* Try to delete: Quest - 1 Column (No Padding, Detail Page)

![screen shot 2015-10-21 at 7 38 43 am](https://cloud.githubusercontent.com/assets/1823543/10635543/8a6e9d7a-77c7-11e5-88be-32aa1989e3c1.png)

**Comment by wezell** [comment]
We need to test if this breaks PP as well.
