### ISSUE TITLE
Can't see translation in 'reorder menu'

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#8266]
When we use translations for folders this works fine in the menu, but when we reorder the menu you see the titles as velocity and not the calculated actual titles.

![image](https://cloud.githubusercontent.com/assets/2195163/10637966/ce3c0a6a-7808-11e5-9617-bc5e6b1754cc.png)
![image](https://cloud.githubusercontent.com/assets/2195163/10637976/d6a123ac-7808-11e5-8ca9-143309adc193.png)

This is a minor issue, but it would be nice if the title was parsed instead of displayed.

**Comment by jtesser** [comment]
Yes we do not render Velocity there currently

**Comment by wezell** [comment]
Xander, are you all using the navtool or the old navigation macros?  If you are using the old navigation macros, we'd suggest moving to the navtool asap.  Something like this shouldn't show velocity in the reorder menu:

http://dotcms.com/docs/latest/multilingual-navigation

**Comment by Xander-Steinmann** [comment]
Yes, we use the old menu but how would the menu rendering influence the reorder menu page?
And I assume you mean we use this to render the menu: http://dotcms.com/docs/latest/navigation-and-menus
