### ISSUE TITLE
Copy host does not link content to pages

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#8270]
When copying a host, the new host has no content on the pages. The content exists but isn't linked to the right page-container combination. This can be reproduced on the demo site by copying demo.dotcms.com and checking "All".

**Comment by jtesser** [comment]
this has always been this way.  You get the content copied and as suck URL Mapped content would work but not the placed content.  This is actually addressed in 3.3 coming out soon

**Comment by Xander-Steinmann** [comment]
Hi Jason, this used to be possible and I think it's a feature you would expect from the copy host. In the item https://github.com/dotCMS/core/issues/4891 we mentioned that the copy host mixed up the ordering, so the content used to be placed on the pages.

But if this is fixed in 3.3 then that's great, of course.

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/418
