### ISSUE TITLE
URL field displayed incorrectly in content overview

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#8282]
When you have a structure with a field called "URL", the field value is displayed as "content.<uuid>" in the content list. This can be reproduced on the demo website.
1. Create a new structure called "new structure"
2. Add the text field "Title", check everything
3. Add the text field "Url", check everything
4. Create a new English content with title "only EN" and url "/servlets/whatever"
   In the overview you can see the title but the URL is displayed incorrectly:
   ![image](https://cloud.githubusercontent.com/assets/2195163/10727356/77a4223a-7bd9-11e5-81da-bd04ae845599.png)

**Comment by jtesser** [comment]
Yea we can improve at some point but that is a reserved word for that screen>  Its also the URL in the identifier table.  I'll leave here open but I would not use that field in your version

**Comment by Xander-Steinmann** [comment]
OK, thanks.
