### ISSUE TITLE
Set-Cookie: SHARED_SESSION_ID should check for null params

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8286]
On 
https://github.com/dotCMS/core/blob/3.2.4/src/com/liferay/portal/servlet/MainServlet.java#L316
is getting null params, resulting in 
Set-Cookie: SHARED_SESSION_ID=VWTUA3OHGZZ5;;;Path=/;Max-Age=86400

This is invalid cookie syntax due to stacked semicolons.

wget -v http://demo.dotcms.com/c
--2015-10-27 21:06:18--  http://demo.dotcms.com/c
Resolving demo.dotcms.com (demo.dotcms.com)... 54.164.175.175
Connecting to demo.dotcms.com (demo.dotcms.com)|54.164.175.175|:80... connected.
HTTP request sent, awaiting response... 302 Found
**Syntax error in Set-Cookie: SHARED_SESSION_ID=HM1GSR9BZPEI;;;Path=/;Max-Age=86400 at position 31.**
Location: http://demo.dotcms.com/html/portal/login.jsp?r=1445979979695 [following]
--2015-10-27 21:06:18--  http://demo.dotcms.com/html/portal/login.jsp?r=1445979979695
Reusing existing connection to demo.dotcms.com:80.
HTTP request sent, awaiting response... 200 OK

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/394
