### ISSUE TITLE
Edit Template button fails when clicked from open HTMLPageAsset for locked Template

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#8289]
Preview a page that is an HTMLPageAsset under the covers instead of the deprecated HTMLPage and has a locked template. In the left preview menu, click the edit template button. There will be an error when trying to cast Contentlet to an HTMLPage.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8290

I'm still able to reproduce in 3.3 and 3.3.1. Fixed and tested in 3.5.
