### ISSUE TITLE
"Working" yellow dot always lit in UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8295]
In pre 3.3 versions of dotCMS the "working" indicator dot was only lit if there was a "draft" version of a content object that was different than the live version.

In 3.3, the yellow dot is always lit, which basically gives the user no information

## 3.2.4
![screen shot 2015-10-30 at 9 12 56 am](https://cloud.githubusercontent.com/assets/934364/10846598/38a36cc4-7ee7-11e5-80ac-a1ba24872abf.png)

## 3.3
![screen shot 2015-10-30 at 9 13 36 am](https://cloud.githubusercontent.com/assets/934364/10846602/412d0a4e-7ee7-11e5-9684-2b5141b1c8d1.png)

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/392
