### ISSUE TITLE
Uploading Bundle Fails when a Content Type has a New Workflow assigned to it

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8304]
Created on 3.2.4 version

Easy to Reproduce
1) Create a new Content Type
2) Create a new Workflow Scheme
3)Assign the workflow scheme to the Content Type in the Content Type properties
4) Download the Content Type in a bundle
5) Try to upload the bundle to another dotCMS server - this is where it fails

Here is the error in the log:  https://gist.github.com/DeanGonzalez/7afb0d548f1c37500edb

**Comment by DeanGonzalez** [comment]
I think this issue may be the root cause of the bundle failure: https://github.com/dotCMS/core/issues/8368

**Comment by jtesser** [comment]
Yes will leave the other issue open
