### ISSUE TITLE
Unable to turn off sessions in 3.3

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8309]
I am trying to follow this blog 

http://dotcms.com/blog/post/real-world-benchmarking-with-dotcms

And found that turning off sessions did not seem to work in 3.3

This commit - 83d53de0977a2b207b4b5eb240932f34d8c15e18 - broke the ability to turn off sessions - the $null tool does not seem to work as expected and does not short circuit the if condition

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/405
