### ISSUE TITLE
Migrate HTML Pages to Content feedback inconsistency

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#8312]
3.2.4 - When converting pages to content, the feedback first says something along the lines of... "processing..." but then it changes to "HTML Pages could not be migrated to Contents. Please check dotCMS logfiles for more information." But, I believe the migration did in fact work.

<img width="1874" alt="screen shot 2015-11-02 at 5 10 52 pm" src="https://cloud.githubusercontent.com/assets/6390980/10897266/491cc938-8185-11e5-848c-101345106cf7.png">
![screen shot 2015-11-02 at 5 11 06 pm](https://cloud.githubusercontent.com/assets/6390980/10897268/491e7ed6-8185-11e5-8032-b5d62cd7e22a.png)
![screen shot 2015-11-02 at 5 11 17 pm](https://cloud.githubusercontent.com/assets/6390980/10897267/491e48c6-8185-11e5-8035-6f9e7aaa078a.png)

**Comment by jtesser** [comment]
there might have been some orphaned data you had that caused this in the identifier table or something. It tries to recover and deal which obviously it did in this case.
