### ISSUE TITLE
Memory leaks in ElasticSearch 1.4.x, need to upgrade?

### ISSUE THREAD

**Issue by dim-s** [dotCMS/core#8313]
DotCMS 3.2 uses the ES Library 1.4.x. 

We have found a memory leak when using this version of the library, like here:
https://github.com/elastic/elasticsearch/issues/10906
https://github.com/elastic/elasticsearch/issues/9407

The simplest solution for us is upgrading the library to 1.5 or 1.6 or maybe 1.7, but we cannot do it because dotcms uses the repackage version of the es library. 

How to quickly upgrade the library and whether any consequences after the upgrade?

**Comment by jtesser** [comment]
FWIW both of those issues have no code fixes and the ES developers never said there was a leak.  It was a user of the lib.  No telling what was really happening.  

Secondly we do expose our scripts to repackage. https://github.com/dotCMS/dotcms-libs
We don't support you on doing it per say but it is documented. 
BUT no telling what upgrading the lib would do. We do not support or test this
