### ISSUE TITLE
Cannot escape HTML code on Metadata fields when indexing. 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8314]
Reproduced in 3.2.4 and in [client](https://my.dotcms.com/tickets/detail.dot?id=f7cc87f2-4535-46f2-b1fc-0a85ba0e23f5) when a Reindex is executed.

Checkin method handles JSON Metadata for fields with GSon libraries and, after this [fix](https://github.com/dotCMS/core/issues/4870) we escape HTML code since the Metadata generation may include HTML or Velocity code that needs to be parsed so the JSON Object is not saved as broken. However, the Metadata field for File Asset content types is saved on a Key/Field Field, which do not handle HTML/Velocity Escaping (it should be done [here](https://github.com/dotCMS/core/blob/master-3.3/src/com/dotmarketing/portlets/structure/model/KeyValueFieldUtil.java#L47)). 

We have seen other issues like Malformed JSON Objects when the content is indexed, but this may be caused by broken data that was saved in the DB by older bugs and this one. As a workaround, data cleanup may be advised to clients.

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/404
