### ISSUE TITLE
BinaryExporter does not respect old inodes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8319]
For the images on a site, this link should always work no matter how many new versions are published on top of it, as long as there is a live version:

Here is a link to the starter site 404 image - you can hit this on demo too, as it is part of the starter.

http://localhost:8080/contentAsset/image/249eeb5c-7002-48e8-9ef3-ea6cd8ea9043/fileAsset/byInode/1/filter/Resize/resize_w/500

now login to the starter and save and publish a new copy of the /images/404.jpg - if you then hit the image above, it will return a 404.   This was not the case in 3.x before 3.3

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/410
