### ISSUE TITLE
dotCMS User Password: policies enforced but not described

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8321]
If you try to add a symbol (! for example) as part of a password for a dotCMS user in the back-end (go to demo, use contributor user), it'll give you the error below.

The "Portal Security Policies" should be listed somewhere, doc on on the pop-up.

![pass](https://cloud.githubusercontent.com/assets/1823543/10937363/524019ac-82c0-11e5-85bb-a7d3af56ec55.png)

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/526
