### ISSUE TITLE
Templates: select on "Add Page Asset" not default to correct host for non-admins

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8323]
**Ref:** https://goo.gl/CXUmjT
**Tested on:** 3.2.4 Demo
**Screencast:**  [Link](https://www.dropbox.com/s/7tye6i9bck8gv08/Template%20saved%20on%20Non-Default%20Host%20for%20Non-Admins.mov?dl=0)

For non-admins users or user who have access to host(s) that are not default, when a user tries to create a Page Asset, the "Templates" drop-down shows no results. 
The user needs to manually go to the "Change Site" drop-down, and re-select the host he/she is already in (as per the Bread Crumbs) for the "Templates" drop-down to work correctly. Expected behavior was confirmed on the "Templates" tool, where the user does not need to manually re-select the host he/she is already on. Default template listing on the Add Page or Templates page should match.

For more details, follow narrative and see  [This Screencast](https://www.dropbox.com/s/7tye6i9bck8gv08/Template%20saved%20on%20Non-Default%20Host%20for%20Non-Admins.mov?dl=0)

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/523
