### ISSUE TITLE
Dynamic display File Assets is not possible for any language other than default

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8329]
Tested on dotCMS 3.2.4

I think this bug is as old as File Assets themselves, but should still be considered a bug in the original design.

Reasons it is a bug:
1) Behavior is not consistent with any other File Content Type (lack of language version)
2) It is the default File Type, yet it has less multilingual functionality than a custom content type
3) This bug makes our default File Type non-functional in a multi-lingual environment

We should either make the File Assets multi-lingual like every other File Type, or they should show in any language.

Easy to reproduce:
1) Upload a few images to the File Asset Content Type.
2) Pull the images in a widget on a page
3) Switch languages by appending ?language_id=2 at the end of the url - images no longer appear in the widget.

**Comment by jtesser** [comment]
While we need to do work here we have never officially supported multi lingual on files.  You don't get the switch language editing them on purpose. U can save it if you try but our tooling doesn't support it.  Lots of work to do to get it to.  We are moving in that direction but this decision was on purpose currently

**Comment by fishsmith** [comment]
Is this something we can/should handle in documentation then for the time
being? Should we tell people, we do not recommend use the default fileAsset
but rather recommend they create a new fileAsset type.

I assume this issues exists to deal with legacy files? If so we should
explain that and point people in a better direction. Thoughts?

On Thu, Nov 5, 2015 at 10:27 AM, Jason Tesser <notifications@github.com>
wrote:

> While we need to do work here we have never officially supported multi
> lingual on files. You don't get the switch language editing them on
> purpose. U can save it if you try but our tooling doesn't support it. Lots
> of work to do to get it to. We are moving in that direction but this
> decision was on purpose currently
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/8329#issuecomment-154093445>.
>



-- 

3059 Grand Avenue
Suite 410-B
Miami, FL 33133
Main: 305-900-2001 | Direct: 305.209.8104

jason@dotcms.com | dotcms.com <http://www.dotcms.com>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by DeanGonzalez** [comment]
Is there any way to leave file Asset content type there to support legacy files but NOT make it the default file type that is automatically recommended by the UI when right-clicking on a folder and uploading? I just don't want clients to start uploading lots of files to what seems like a logical default, only to find out, way down the road, that the File Content Type they are using can never be multi-lingual.  It is ok that the File Content Type exists, but I don't think it should be the default File Type on folders in the system should be one that is not handicapped.  I will put in a documentation ticket for now on this though to warn clients of the limitation.
