### ISSUE TITLE
Error uploading Bundles in 3.2.4

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8343]
Reproduced on demo.dotcms.com uploading simple bundles.

To reproduce:
1) Create a piece of Generic Content
2) Download the piece of content in a Bundle
3) Delete completely the Generic Content
4) Try to upload the bundle to demo.dotcms.com - Fails

The same goes for folders, pages, etc - simple bundles are not uploading

**Comment by DeanGonzalez** [comment]
I think this occurs specifically when you are running Java 8 - just a theory at this point, asked QA guys to check if they saw same problem.

**Comment by jtesser** [comment]
@DeanGonzalez not sure but in 3.3 in both 7 and 8 we can upload bundles.  So should be ok here moving forward
