### ISSUE TITLE
Clean-Up System Roles and Keys in 3.3+

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8349]
It would be great if we:

1) Cleaned up unneeded system roles (User vs CMS User...do we need both?)
2) Ordered the Roles list alphabetically.
3) Make all the role keys match the names (or vice versa)... [see below]

![screen shot 2015-11-12 at 10 16 47 am](https://cloud.githubusercontent.com/assets/1823543/11121910/86a1c062-8926-11e5-9638-7509c4125a86.png)

**Comment by jtesser** [comment]
Well actually I don't think it is good to alter legacy System Role Keys BUT we should allow them to be visible in the UI.  Right now all Keys are visible but System Roles are not

**Comment by levosgien** [comment]
Makes sense, maybe just make them viewable AND ordered alphabetically, what do you think?

**Comment by jtesser** [comment]
Yea the sort is terrible on the Role Manager

**Comment by jkshapiro** [comment]
See also #6551
