### ISSUE TITLE
HtmlPages screen can be slow if the user has access to a large number of pages across multiple hosts.

### ISSUE THREAD

**Issue by alexmcchesney-bv** [dotCMS/core#8350]
The underlying Lucene query is not filtering by host, resulting in poor performance in some cases.

**Comment by jtesser** [comment]
the HTML Page Flat screen is deprecated. 

You can use the content search screen OR the Web Site browser.

**Comment by alexmcchesney-bv** [comment]
As the code still appears to be in the 3.3 source, do you recommend that view permission to that portlet should just be removed from all users?

**Comment by jtesser** [comment]
the portlet is old and legacy. We have it as people can use it for old school legacy pages so ye sit works but we do not have it on demo.dotcms.com or in a clean install.  I assume this is an upgraded install

**Comment by alexmcchesney-bv** [comment]
It is an upgrade.  We are happy to remove that portlet.  Is dropping the permission from all users the best way to go about it?

**Comment by jtesser** [comment]
Remove from the CMS Tabs on the Role Manager
