### ISSUE TITLE
Incorrect message "Failed to send to all environments" before push succeeds

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#8359]
When pushing a site, the status of the push on the receiving server displays "Failed to send to all environments" for several minutes while the status on the sending server displays "Publishing bundle".  After the site successfully publishes, the status on both sites changes to "Success".

This is a cosmetic issue, since the publish actually succeeds, but it's confusing because it indicates the push failed when it didn't, and may prompt a user to continually re-try a push that was actually successful the first time.

Note: I expect this is reproducible with any large bundle, but I've only verified it when pushing a whole site using the starter site as a base, since that's the simplest to do.

**Steps to Reproduce**:
1. Start a clean starter site.
2. Set up a push publishing environment and verify that content items can be successfully pushed.
3. In **System -> Sites**, create a clone (full copy) of the site.
4. Push Publish the copied site to the receiving server.
5. On both the sending and receiving server, open **Site Browser -> Publishing Queue**, and select the **Status / History** tab.
6. Continue refreshing both servers periodically until the push completes.

**Results**:
- For several minutes the receiving server displays a status of "Failed to send to all environments" while the sending server displays a status of "Publishing bundle".
- Once the push is complete, the status on both the sending and receiving servers changes to "Success".

**Testing Environment**:
- dotCMS 3.2.4 and 3.3
- Windows 7
- Java 8 (1.8.0_65)

**Comment by mattyarbrough** [comment]
This issue continues to be a problem in 4.x, support customers requesting a fix.

**Comment by wezell** [comment]
This has been resolved in later versions
