### ISSUE TITLE
Workflow schemes with Default Actions do not push

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8368]
Just tested on dotCMS 3.3

This bug has probably been around for a while.  Easy to test.
Create a new workflow scheme, give it a mandatory default action, and assign to a content type.  
Then try to push a piece of content using that content type:

This is the error:
Failed to publish because an error occurred: ERROR: insert or update on table "workflow_scheme" violates foreign key constraint "fk_wf_scheme_action" Detail: Key (entry_action_id)=(4fa42503-1c97-4e42-97e5-bdee417c6d1a) is not present in table "workflow_action".

Work around is to remove the default action and then push again, then re-establish the workflow scheme default action on the receiving end.

**Comment by jtesser** [comment]
Yes this has always ben true for push publishing

**Comment by wezell** [comment]
Also broken, workflow steps that use a timed action.

**Comment by wezell** [comment]
fixed here: https://github.com/dotCMS/enterprise-2.x/pull/305

**Comment by wezell** [comment]
[broken-bundle-workflow-defualt-action.gz.txt](https://github.com/dotCMS/core/files/39101/broken-bundle-workflow-defualt-action.gz.txt)
[broken-bundle-workflow-timed-action.gz.txt](https://github.com/dotCMS/core/files/39102/broken-bundle-workflow-timed-action.gz.txt)

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/488
