### ISSUE TITLE
Error Reordering content in not default language Html Page

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8370]
This issue was initially reported by a client: https://my.dotcms.com/tickets/detail.dot?id=8e836ee3-0ec4-405c-9de4-ecfd2f8763db

In order to reproduce the issue:
1. Create two Generic Contents in Spanish
2. Create a Html Page **ONLY** in Spanish
3. Edit the page
4. On Edit mode add the two contents we created
5. On the same edit mode try to reorder those contents
   ![reorder](https://cloud.githubusercontent.com/assets/923947/11283441/64c23f2c-8eca-11e5-8116-8e50b692951b.png)
### Result

```
Ooops, sorry. This has caused a problem
```

---

**dotcms.log**

```
[19/11/15 14:18:51:139 CST]  WARN action.RequestProcessor: Unhandled Exception thrown: class java.lang.NullPointerException
[19/11/15 14:18:51:139 CST] ERROR portlet.StrutsPortlet: java.lang.NullPointerException
```

---

**catalina.out**
https://gist.github.com/jgambarios/e084e99e8ac9b8d748d7

---

**I was able to reproduce locally (dotCMS 3.2.4/postgres) and on demo.dotcms.com**

**Comment by anwarkhadim** [comment]
I have the same issue with English (GB). Tried on both 3.2.4 and 3.3. 

Also when changing the default language via the static plugin stops bundling working (downloading throws a 500, without logging anything). This effectively means dotCMS can only really be used for a single language (US English).
