### ISSUE TITLE
Cannot Delete Default Host

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8371]
When trying to delete a default host, it doesn't let you but doesn't give you any messages. We should message that "Default Sites Cannot be Deleted. Please make another Site default and try again" or something like that.

**Comment by jkshapiro** [comment]
You shouldn't be able even to stop the default host, let alone archive or delete it.

The options just shouldn't be on the menu, in the same way as "Make default" isn't on the menu for that site.
