### ISSUE TITLE
Cannot display image in other language like Chinese language

### ISSUE THREAD

**Issue by allychan** [dotCMS/core#8373]
1. If we first load Chinese language, all images which are selected from content editor cannot show. 
![img1](https://cloud.githubusercontent.com/assets/15936024/11291706/66ef6e14-8f7e-11e5-845b-551e40a71d14.png)

2. If we change to default language (English language) and change back to Chinese language, it can show some images which have the same id with default language’s images. 
![img2](https://cloud.githubusercontent.com/assets/15936024/11291708/692bec3e-8f7e-11e5-995a-c7bef9ff64ee.png)

3. However, if we use different images in different language, the images which do not have same id comparing to each language still cannot show whatever we change the language.

Is there a way to solve above conditions? Thanks.

**Comment by levosgien** [comment]
Currently File Assets do not support multiple languages. We have tagged this issue for review as an enhancement for future releases. Feel free to follow this issue for updates.

Thanks.

**Comment by allychan** [comment]
We changed the Display Type to Binary, users need to upload images for different language version instead of select image from File Asset
