### ISSUE TITLE
Need pre-select one target option when you are creating a new link 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8375]
We should have auto-selected one of the target options when you try to create a new menu-link from backend, because as default we have in blank this field, and since is not required, you can leave this field in blank.

If you leave the field in blank we are opening the link in the "Same Window", then maybe we can use this option as default...

<img width="782" alt="ui" src="https://cloud.githubusercontent.com/assets/2641437/11306911/6d343fd8-8f7a-11e5-9dca-4becbf3669d9.png">

SC: http://screencast.com/t/jDW2ZNdi9b

For now is not an issue, but can be a user experience  improvement...

Tested on master_3.3 // H2 // FF

**Comment by rogelio-blanco** [comment]
PR https://github.com/dotCMS/core/pull/8382

**Comment by jgambarios** [comment]
**master-3.6** PR: https://github.com/dotCMS/core/pull/9007

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF
