### ISSUE TITLE
Push Publish: Missing hosts dependencies

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8384]
This was reported in dotCMS 3.2.4 by a client, I was able to reproduce the issue and I can confirm the same issue in present in dotCMS 3.3

1. Create empty **hostA**
2. Create empty **hostB**
3. Create in **hostA** at the root a page called **index** with a Template from **demo.dotcms.com** and adding it the generic content **About Quest**
4. Create in **hostB** at the root a page called **index** with a Template from **demo.dotcms.com** and **NO content**
5. Switch to host **demo.dotcms.com**
6. Push the generic content **About Quest**

## Result
The dependency manager adds as dependencies the pages from **hostA** and **hostB** BUT NOT the hosts.

**Comment by levosgien** [comment]
Ref: https://my.dotcms.com/tickets/detail.dot?id=e22d0b89-5e82-4050-baad-bad0cfe077e4

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8386
