### ISSUE TITLE
Wrong language_id affects current session

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8388]
It was reported for a client and as I know that's how dotCMS currently works we could as a future **improvement** try to validate the passing **language_id** and fallback maybe to the default language or just ignore it in case of found a wrong language.

> When I request an URL with an invalid Language ID before I have a session (i.e. initial request, no cookies), this ID gets stored in the Session. All following requests result in an 500 exception, until I clear my session cookies. This can be reproduced on the demo server, e.g.: http://demo.dotcms.com/?language_id=dotcms

Note: The workaround is to set back the proper language id: http://demo.dotcms.com/?language_id=1

**Comment by jgambarios** [comment]
**Update:** Actually dotCMS already handles wrong ID's look at: http://demo.dotcms.com/?language_id=45 the problem with the Client is when casting the **dotcms** "id", fails casting that value. Either way nothing new here, old behavior but just to let you know in case we try to improve this logic.

**Comment by rogelio-blanco** [comment]
Seems to be also relate it with #8305

**Comment by levosgien** [comment]
Ref: https://my.dotcms.com/tickets/detail.dot?id=b3c9912b-33d3-422d-a1c1-d6a308e742e4

**Comment by dsilvam** [comment]
hot fixed it here https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-8388_v3.2.4

**Comment by levosgien** [comment]
PR: https://github.com/dotCMS/core/pull/8590
