### ISSUE TITLE
After migrating legacy pages, Redirect URL value is dropped

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8429]
Reproduced in 3.3. 

Steps: 

1. On a 2.5.x instance, create pages with values on Redirect URL field. Doesn't matter if it's an internal or external link. 
2. Stop 2.5.6 and upgrade to 3.3.
3. Once 3.3 is up and running (and with a valid ES index), run the Migrate Pages as Contents tool. 
4. Go to Website Browser and check the pages you created in step 1. The Redirect URL field value is dropped.

**Comment by levosgien** [comment]
PR: https://github.com/dotCMS/core/pull/8430
