### ISSUE TITLE
[core] java.lang.ClassNotFoundException is thrown when adding DEBUG level in log4j for ElasticSearch classes

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8436]
Information | Value
------------ | -------------
Versions | 3.2, 3.2.1, 3.2.4, 3.3, 3.5
Origin | Distro and source code
OS | Any
DB | Any

When setting the debugging level in the "log4j.xml" or "log4j2.xml" for the Elastic classes to "DEBUG", an exception is thrown in the logs during the startup process. However, **this exception DOES NOT seem to have any effect in dotCMS**. It only shows up when setting the debugging level of the Elastic classes to "DEBUG".

This exception was found when working with and testing the configuration of dotCMS to work with an external Elastic server instead of the embedded version. As previously mentioned, the elastic-related features in dotCMS are working correctly, using both the embedded ES and the external ES server.

**Root Cause:** The code in the Elastic library tries to load the class "org.apache.lucene.expressions.Expression", which does not exist in any of the dotCMS .JAR files. It belongs to a .JAR called "lucene-expressions-4.10.2.jar"

**Comment by chrismccracken** [comment]
This is affecting a client, https://my.dotcms.com/tickets/detail.dot?id=0f5c6a22-653f-4e16-b6b1-c9f37bec2f38. The elasticsearch-1.4.2/lib/lucene-expressions-4.10.2.jar was not repackaged and is missing from our build.

**Comment by wezell** [comment]
It seems from the above report that the error can be safely ignored.  The other alternative is to provide the .jar to the classloader, but it seems safer to ignore.

**Comment by wezell** [comment]
Not sure if this is still an issue in 3.6.  We can reopen if needed.
