### ISSUE TITLE
Upgrade to 3.3 - errors relating to obsolete job

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#8442]
Obsolete quartz job causing noise in the logs when upgrading to 3.3.

CleanBlockCacheScheduledTask was removed in 3.3 and displays this message on upgrade:  
https://gist.github.com/vianneychacon/2e7dec2f9712c15fb238

All DBs

**Comment by gabbydotCMS** [comment]
Happened while testing upgrades to 4.1 and also during the upgrade to 3.7.1 of a dEC client.

It's easy to solve by removing data from Quartz tables, but an upgrade task would be great.
