### ISSUE TITLE
Menu Order doesn't stick

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#8451]
Reported by a client: https://my.dotcms.com/tickets/detail.dot?id=1e085aeb-2d1e-4e6f-9dd8-69b70cba154d

I could reproduce in demo and 3.2.4

After updating the Menu Order for a page in the Site Browser, it is updated in the DB but the inode is not removed from ContentletCache so it will display the old Menu Order until you flush that cache.

**Comment by john-thomas-dotcms** [comment]
Related: https://github.com/dotCMS/core/issues/10214

But note that this issue (10214) is not a caching issue - the menu ordering problem persists after flushing all caches and deleting the menu cache.
