### ISSUE TITLE
Problem updating workflow_task table on push publish

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8454]
This is a problem reported by a client, the client have 30,000+ records on the **workflow_task** table and the push publish process on the receiver side tries to update those records making the operation to take a long time to execute or even unresponsive:

Executed query:

```
update workflow_task set status = ? where webasset in (select identifier from contentlet where contentlet.structure_inode = ? group by identifier)
```

https://github.com/dotCMS/core/blob/master-3.3/src/com/dotmarketing/portlets/workflows/business/WorkflowFactoryImpl.java#L976

We need to improve the query above.

**Comment by wezell** [comment]
We do need to improve the query, but the fact is, that unless the workflow has changed, we should not do anything at all (meaning,we can leave this table and this update alone).  This is only if you change a workflow for a structure, remove a step,etc.
