### ISSUE TITLE
Documentation: "04:00 PM EDT", roadmap

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#8470]
On the page http://dotcms.com/company/events/ the time for "Introduction to dotCMS" is shown as "Thu, January 07, 2016 - (04:00 PM EDT)". This time is confusing: the leading zero suggests use of the 24-hour clock, but the "PM" (and knowledge of where your office is) suggest otherwise. As well, since we're now on standard time again, the use of "EDT" is confusing. What about something like "January 7, 2016, 4:00-5:00 PM Eastern"?

On the same page, the listing for "Awesome Upgrades" does not include any indication of time zone.

On another note, the page http://dotcms.com/content-management-system/cms-roadmap suggests that version 3.5 is coming out in "Q3 2015". Since it's now 2016 and we've just released v3.3, this should probably be updated.

**Comment by DeanGonzalez** [comment]
Hey Kivi, thanks for the feedback.  I updated the pages accordingly, thanks again!

**Comment by jkshapiro** [comment]
Thank you Dean!
