### ISSUE TITLE
Change Logging Levels in PluginFileMerger class

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8472]
Reproduced in 3.3. 

If a plugin tries to add custom attributes/nodes to default XML files through static plugins, we're getting ERROR level messages for regular operations. For example, trying to add custom servlets to the main web.xml using a plugin's web-ext.xml throw these error messages, despite there are no errors in the way they're deployed. Same for cleaning up XML files once you try to undeploy plugins. 

Undeploy Output: 
https://gist.github.com/joseorsini/f2d17759802140dde6d8

Deploy Output: 
https://gist.github.com/joseorsini/4fa8fca6fae3f361142c

**Comment by jgambarios** [comment]
Fixed for master-3.5
PR: https://github.com/dotCMS/ant-tooling/pull/6
