### ISSUE TITLE
Delete content by Identifier not working on 3.3 maintenance tab

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8473]
Tested on training server and also on demo.dotcms.com.  On Tools tab under Sytem->Maintenance, the "Delete Contentlets" by identifier is not working to delete contentlets.  Even if the content is unpublished, does not work:

Screencast: http://screencast.com/t/KYFcAHXGGlMN

**Comment by wezell** [comment]
Dupe #8820
