### ISSUE TITLE
PermGen is deprecated in JDK1.8

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#8481]
We are currently shipping with the MaxPermSize option set in the JAVA_OPTS variable, which is deprecated in JDK1.8 so the values are being ignored, letting the max class metadata allocation limited only by the amount of available native memory.

It'll worth to take a look at the implementation changes, however the MaxMetaspaceSize option is analogous to MaxPermSize so it can be used instead.

**Comment by jtesser** [comment]
this is true.   and addressed in 3.5
