### ISSUE TITLE
Form Entries/Content inherit permission from host instead of Content Type or Folder

### ISSUE THREAD

**Issue by allychan** [dotCMS/core#8497]
I have created some forms in dotCMS and need to limit the permission of some CMS users

I created a role "CS" and set following permission as I only allow them to edit the pages under formfolder but not allow them to edit the forms

myhost:/formfolder | View | Add Children | Edit
------------ | ------------- | ------------- | -------------
Folders | ✓ | N/A | N/A
Pages | ✓ | ✓ | ✓
Legacy Files | ✓ | N/A | N/A
Content Types | ✓ | N/A | ✓
Content/Files | ✓ | N/A | ✓

Then I set the forms' Permission Individually in Content Type to only allow CS user to view the form.
The forms' Properties Site or Folder is set to myhost:/formfolder.

However, when customers submit a form in front end, the permissions of all form reply are set to
Getting permissions from parent: myhost

Since I did not grant permission to "CS" to view the content under myhost, they are not available to view customers' reply.

Is there any way to change all form reply's permission to inherit from their Content Type or Folder instead of host?

**Comment by jtesser** [comment]
It will inherit from the closest permission set for the roles the user has.  So in this case maybe the customers roles have no permission on the folder but is crawling up to the host.
