### ISSUE TITLE
Workflow problems for multi-languages content

### ISSUE THREAD

**Issue by allychan** [dotCMS/core#8498]
I have created a workflow in dotCMS that only some roles can publish content, other users need to send the content for review.

However, there are 3 problems we encountered.
1. When users save the content and edit the content in other language
   It will popup a message "Unable to save/update Object to Hibernate Session".
   Then all the users including CMS Administrator are not able to edit/publish that record.
2. When users send the content for review, only one language version can be sent each time.
   Other language version will be locked form editing until that content is publish or returned for editing.
3. When users send the content for review, the reviewer can see the correct language version in the list of My Task. However, when the reviewer click into Edit Content some time it will become other other language version version that are not send for review.

**Comment by wezell** [comment]
Allychan, if you have enterprise support contract, I would suggest entering a support issue on these github for the fastest resolution.
