### ISSUE TITLE
Content Edit: Actions pane for User #2 does not show up when User #1 locks on the same contentlet

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8500]
Reported by a client via the Support Portal: https://my.dotcms.com/tickets/detail.dot?id=9935a502-8a69-48d0-81e9-91a587f14aa0

Reproducible: 3.3 (Demo Site)
DB: Any
OS: Any
Browser: Any

There is a problem with loading the Actions pane when two users are looking at the same contentlet and the first one locks it before the second one.

**Steps to Reproduce:**

* Open up two browsers and log into the back-end with 2 different users (for example, one with "Admin User" and the other with "Joe Contributor").
* Go to the _Content Search_ portlet and open up the same contentlet, in both user sessions.
* In the "Admin User" session, click the "Lock for Editing" button. This will lock the contentlet correctly.
* Now, in the "Joe Contributor" session, click the "Lock for Editing" button as well.
* **RESULT:** The "Joe Contributor" user will get _"Cannot lock content"_ message (which is correct). BUT, the buttons inside the Actions page will not show up. A loading icon displays and never changes.

**Comment by levosgien** [comment]
https://my.dotcms.com/tickets/detail.dot?id=9935a502-8a69-48d0-81e9-91a587f14aa0

**Comment by wezell** [comment]
This will be addressed in our new UI refresh.
