### ISSUE TITLE
Workflow - Lock for editing always visible even when it doesn't make sense.

### ISSUE THREAD

**Issue by mcenkar** [dotCMS/core#8514]
Lock for editing button is always visible even when it doesn't make sense from workflow perspective.

E.g. when only actions from given step don't require locking content you can still lock it which gives you only two possible actions: "Release lock" and "Cancel".

Steps to reproduce: on demo.dotcms.com enable mandatory workflow "Document Management" for content type "Banner".  Publish one piece of content to make it reach Step: Published. Now you have options: Return for Edits, Republish, Archive... and also Lock for Editing which in current state doesn't make sense.

Caused by this jsp https://github.com/dotCMS/core/blob/f5571b0d378cdd87223fd1fdb01ce6bc6eda5a1f/dotCMS/html/portlet/ext/contentlet/contentlet_actions_inc.jsp#L95-L104

which only checks if there are workflow steps available from current state but it doesn't check if any of these requires content lock.

**Comment by levosgien** [comment]
https://my.dotcms.com/tickets/detail.dot?id=9fe1aff3-6548-4527-b237-0eb739834bc5

**Comment by wezell** [comment]
We will be redoing the backend UI in angualr2 and will address the issue then.
