### ISSUE TITLE
Allow languages to be hidden from Language selection list

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#8529]
It would be useful to have some way to remove a language from the drop-down list that content creators see, without admins having to delete the language.
# 

Currently, it's difficult to remove a language once any content has been created in that language, because the language can only be deleted after all content in that language has been (unpublished, archived, and then) deleted.  However the content can only be deleted if _all language versions_ of that content are deleted, which is highly destructive.

This means it's unlikely that users will actually delete a language after it's been used (which is actually probably a good thing).  However if admins wish to remove the language from the language drop-down list (so content creators can no longer select that language to create content), they don't have a good way to do this.
# 

Note: There are a number of potential ways to do this, with the simplest probably being to add something along the lines of a "Display in List" checkbox for each language.  More sophisticated ways might also make sense (such as allowing Languages to be archived without being deleted, controlling language display by Role, etc.), but may not be worth the effort.

**Comment by jkshapiro** [comment]
Another approach:  #5556
