### ISSUE TITLE
NavTool is returning wrong "active" items

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8530]
Reproduced in 3.3. 

Reported by a client: https://my.dotcms.com/tickets/detail.dot?id=c0156dcc-1d3f-4c41-aba9-a042466b22c3

Steps to Reproduce. 

1. Under /home folder, create two pages: /home/test and /home/test-2. Mark them as "Show On Menu" when they're created
2. On both pages, add a Simple Widget with this Velocity code (based on code sent by client) https://gist.github.com/joseorsini/120c429aa2aa2d6e6f67. It's pretty straightforward NavTool call. 
3. Open both pages in Edit Mode and inspect the Menu Items. 
  - If you open /home/test page, this one on the menu is labeled as "Active".
  - If you open /home/test-2 page, this one AND /home-test pages on the menu are labeled as "Active". 

The problem is caused here https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/navigation/NavResult.java#L126 because it checks only a portion of the URI, which can return a wrong result depending on the actual results List for a specific folder.

**Comment by wezell** [comment]
If you are in the code, can you propose a fix via pull request?

**Comment by joseorsini** [comment]
Sure @wezell I'll upload the PR today

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8546

**Comment by joseorsini** [comment]
Disregard last commit from Feb 29. Related to different ticket
