### ISSUE TITLE
URL Field for Page Assets is missing in the ContentMap

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8532]
Reproduced in 3.3 (demo site) and also reported by client: https://my.dotcms.com/tickets/detail.dot?id=b47dbc5e-4ee7-474b-b0ed-f994d6f21d97 

In Content Search Manager, It looks like some Page Assets when they're exported to CSV do not have values in their URL Field 

Partial CSV: https://gist.github.com/joseorsini/164b56383dbc9faaa10c 

Debugging the downloadToExcel Method from our EditContentletAction.java class, this is what we get for "Market Research" Page Asset, which is listed on the CSV without a URL field value 

```
com.dotmarketing.portlets.contentlet.model.Contentlet@1001d9b8[map={template=d30a0347-7473-49ab-b67d-cc7a972f4d59, modDate=2015-06-23 13:45:41.809, cachettl=15, title=Market Research, httpsreq=, showOnMenu=true, inode=15dc1526-b360-4037-a623-4c25493fc18c, __DOTNAME__=Market Research, disabledWYSIWYG=[], seokeywords=, host=48190c8c-42c4-46af-8d1a-0cd5db894797, lastReview=2015-06-23 13:45:41.806, stInode=c541abb1-69b3-4bc5-8430-5e09e5239cc8, owner=dotcms.org.1, identifier=4cd6081f-e93e-4647-9759-3185a8de8807, friendlyname=Market Research, redirecturl=, canonicalUrl=, pagemetadata=, languageId=1, seodescription=, folder=ca1e91b2-6d8c-47fd-a410-462da6fa7ecf, sortOrder=3, modUser=dotcms.org.1},lowIndexPriority=false]
```

If you grab the "Market Research" page identifier and search in in our Query Tool portlet, you'll get the following ContentMap: 

```

1.  Title:  Market Research
    Inode:  15dc1526-b360-4037-a623-4c25493fc18c
    Identifier: 4cd6081f-e93e-4647-9759-3185a8de8807

{template=d30a0347-7473-49ab-b67d-cc7a972f4d59, modDate=2015-06-23 13:45:41.809, cachettl=15, title=Market Research, httpsreq=, showOnMenu=true, inode=15dc1526-b360-4037-a623-4c25493fc18c, __DOTNAME__=Market Research, disabledWYSIWYG=[], seokeywords=, host=48190c8c-42c4-46af-8d1a-0cd5db894797, lastReview=2015-06-23 13:45:41.806, stInode=c541abb1-69b3-4bc5-8430-5e09e5239cc8, owner=dotcms.org.1, identifier=4cd6081f-e93e-4647-9759-3185a8de8807, friendlyname=Market Research, redirecturl=, canonicalUrl=, pagemetadata=, languageId=1, seodescription=, folder=ca1e91b2-6d8c-47fd-a410-462da6fa7ecf, sortOrder=3, modUser=dotcms.org.1}
```

In both cases, the URL field is not added to the ContentMap. This field is required, indexed and searchable, and it should be populated with the content identifier's asset name (where we store the page URL). Running a full reindex does not seem to solve this problem either.

**Comment by wezell** [comment]
So, the URL on a page is not a property of the content object, it is a calculated convenience property that we provide in the elasticsearch index and in the front end content map.  It is made up of a combination of the identifier.getParentPath() + content.uri.    I believe the same is true if you get a csv of fileAssets as well.  If we did export the full URL, that would seem to indicate that they could be importable in csv as well and I am pretty sure that will not work without some further development.

**Comment by joseorsini** [comment]
So for Page Assets, should we exclude URL field? From the CSV we can generate in demo, the Page URL only points to the Asset Name and there is no indication of a parent path or folder.

**Comment by wezell** [comment]
We need to have access to all these fields (which includes the path).  This needs to happen if the page is found through a $dotcontent.pull or as the $dotPageContent variable

http://dotcms.com/docs/latest/page-content-in-velocity

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8969

**Comment by jgambarios** [comment]
We need to finish the discussion about this fix, comments: https://github.com/dotCMS/core/pull/8969#issuecomment-215217352 and https://github.com/dotCMS/core/pull/8969#issuecomment-215228522

-------
I'm not opposed to the answer given for Jose Castro in https://github.com/dotCMS/core/pull/8969#issuecomment-215228522

**Comment by wezell** [comment]
I believe this is resolved.
