### ISSUE TITLE
Limited User cannot add categories 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#8538]
I have a limited user with a role which has access to the categories portlet and where permissions are all set on system host for the user's role for categories and add children. Even with a flush cache the limited user gets a lacking permission message when attempting to add a category

**Comment by john-thomas-dotcms** [comment]
This is still an issue - a prospect just ran into it, and I was able to reproduce on demo (v5.3.6.1).

![image](https://user-images.githubusercontent.com/13456955/90779256-76002b00-e2b2-11ea-910f-873178fd817c.png)

Limited users can create sub-categories, but not top-level categories.  This is true even when the user/Role has full permissions to create Categories:

![image](https://user-images.githubusercontent.com/13456955/90779091-481ae680-e2b2-11ea-8c86-2b227085ca00.png)

**Comment by john-thomas-dotcms** [comment]
### Steps to reproduce:

On demo/starter:

1. Update the permissions for the Publisher/Legal Role under "All Sites":
    * Add "Edit Permissions" rights for Categories.
    * Add "Add Children" rights for All Sites.
2. Login as "Chris Publisher".
3. Open the Categories portlet (Content Model -> Categories).
4. Add a new Category (select "Add" from the top-right drop-down menu).
5. Fill in the name of the new Category and click the "Save" button.
    * **Result:** An error appears, `You cannot edit the Category because you don't have the required permissions.` (see screen shot above).

**Comment by erickgonzalez** [comment]
**Note to Doc:**
Need to update Documentation https://dotcms.com/docs/latest/category-permissions

Now limited users can add Top-Level Categories if they have `Add Children` and `Edit` permissions over Category, all of this under `All Sites`.

To add subCategories, the limited user will need `Edit` permissions under the parent Category.

**Comment by erickgonzalez** [comment]
**Note to QA:**
Possible scenarios to test:

- Create Top-level categories and subcategories as admin.
- Give Permission to one top-level category to a limited user and try to add top-level categories (this should fail), add subcategories to it (should succeed)
- Give `Add Children` permissions to a limited user and try to add a top-level category (should fail).
- Give `Edit` permissions to a limited user and try to add a top-level category (should fail).
- Give `Add Children` and `Edit` permissions to a limited user and try to add a top-level category (should succeed).

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19264

**Comment by bryanboza** [comment]
Need some work here: 
- After the changes we are allowing to create top level categories just adding "Add Children" permissions on the system host, is not necessary the "edit" on the categories 
![image](https://user-images.githubusercontent.com/2641437/94052711-8a928000-fd96-11ea-8605-fb84f164ad23.png)

This should be the permissions:
- Add Top-level Cat = Add Children and Edit over system host
- Add sub cat = Edit over parent cat
- Edit Top-level Cat = Edit over the category itself
- Edit sub cat = Edit over the sub-category itself

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/19326

**Comment by bryanboza** [comment]
To add top level categories we need `Publish` permissions and not just `Edit. This to allow to separate the edit and add rights. Needs some work

**Comment by erickgonzalez** [comment]
**Note to Doc**:

This should be the permissions:

Add Top-level Cat = Add Children and Publish over system host
Add sub cat = Edit over parent cat
Edit Top-level Cat = Edit over the category itself
Edit sub cat = Edit over the sub-category itself

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/19357

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.9 // Postgres // FF. New permissions error related on #19364
