### ISSUE TITLE
Site search overwriting file assets with zero-bytes

### ISSUE THREAD

**Issue by jbjornson** [dotCMS/core#8552]
We have multiple regional sites (ch, de, fr, at, …) that share content that is stored on a common site (“common”). On each site we pull the content from the “common” site so that it does not need to be duplicated on every site (for example news stories, executive committee cvs, pictures of the board of director members, …).

We would like to create a site search index for each of the sites that includes the content specific to that site as well at the the common resources (stored on the “common” site). To do this, I scheduled multiple site search indexing jobs at 5am. Each scheduled job indexes the regional site as well as the “common” site. Unfortunately, when we schedule the indexing jobs at the same time, random file assets in dotcms will lose their content (i.e. they are overwritten with a zero-byte file).

We were able to discover from the logs that each zero-byte file corresponded with an error in the logs like the following:

```
2016-02-01 11:30:03,291 ERROR com.liferay.util.FileUtil - Can't create hardLink. source: /opt/xxxxxxx/dotcms/assets/f/c/fcd2e588-b1a9-422e-9cbb-80d5fc7b6fe7/fileAsset/my-image.jpg, destination: /opt/xxxxxxx/dotcms/assets/bundles/2016-02-01_11-30-00/live/common/1/some/path/images/my-image.jpg
```

When we stagger the site-search indexing jobs so they run at different times, this does not happen.

I was able to reproduce this on the dotcms demo site by scheduling two site-search indexes at the same time. I saw many of the “Can't create hardLink” log entries. For example, the image at the top of the bear mountain page is now missing (zero-byte).

It looks like your implementation uses the same folder for all jobs to generate the site-search index. When multiple jobs are run concurrently for the same site, they block each other and somehow this results in the source file being overwritten.

We consider this a very **severe** and major issue. It should not be possible for the indexing code to delete content under any circumstances! The site-search indexing should be a **read-only** operation.

I would imagine that you should either prevent the jobs from running concurrently or you should use unique directories when generating the site-search indexes.

Steps to reproduce:

Schedule multiple site search jobs for the same site at the same time. I was able to reproduce this on demo.dotcms.com with 2 concurrent jobs.

**Comment by dsilvam** [comment]
https://my.dotcms.com/tickets/detail.dot?id=55c881a6-c3fb-4e54-a003-4e7abeb3f917

**Comment by dsilvam** [comment]
https://my.dotcms.com/tickets/detail.dot?id=eb75834b-85ac-4e63-bc92-573402d8811a

**Comment by dsilvam** [comment]
Another consequence of this error: 
https://my.dotcms.com/tickets/detail.dot?id=5c8d381d-b303-4d97-bf29-7753dd3b6b45

**Comment by wezell** [comment]
The sitesearch job should be a stateful job, and in consequence, only one should run at a given time (even in a cluster, I think).  We should explore why this is not happening

**Comment by wezell** [comment]
Also #6477

**Comment by joseorsini** [comment]
Reported also here: https://my.dotcms.com/tickets/detail.dot?id=9ae77ca8-a4e1-4c4d-aec1-3704b1e96fdc

**Comment by wezell** [comment]
We need to prevent the bundlers from writing a zero byte file

**Comment by joseorsini** [comment]
Related to: 
https://my.dotcms.com/tickets/detail.dot?id=4e622ed5-4cec-44ff-9f50-c079b772117f
https://my.dotcms.com/tickets/detail.dot?id=be5befb1-ed8e-48a8-8d22-601aab164286

**Comment by joseorsini** [comment]
Steps to Reproduce.

1. Start a 4.1.1 instance and apply an Enterprise License.
2. Create two Site Search Indexes.
<img width="1676" alt="screen shot 2017-09-12 at 1 59 15 pm" src="https://user-images.githubusercontent.com/1717110/30345772-9b2118b4-97c3-11e7-8e6e-604769a8c7a2.png">
3. Create two separate Site Search jobs set to index the same Site and contents in English and Spanish. Both of them need to be set to the same cron expression.

    - Job 1, indexing contents to Test 001 Index.
<img width="1656" alt="screen shot 2017-09-12 at 1 59 37 pm" src="https://user-images.githubusercontent.com/1717110/30345794-b966fffa-97c3-11e7-8dbe-969d1f4a8978.png">

    - Job 2, Indexing contents to Test-002 Index.
<img width="1661" alt="screen shot 2017-09-12 at 2 00 14 pm" src="https://user-images.githubusercontent.com/1717110/30345808-cbba873a-97c3-11e7-90c2-d1fd1e1892a4.png">

    - List of all jobs
<img width="1671" alt="screen shot 2017-09-12 at 2 00 16 pm" src="https://user-images.githubusercontent.com/1717110/30345817-d6c406f6-97c3-11e7-8291-6cfeda098b0e.png">

    - Zero Byte files BEFORE jobs were run:
```
./messages/cms_language_en_US.properties
./messages/cms_language_es_ES.properties
./messages/cms_language_zh_TW.properties
```

    - Zero byte files on system AFTER Site Search jobs were run:  https://gist.github.com/joseorsini/cae77dc6311cc5a4c3cc4b0bcc793d6e (around 929 files).

    - File BEFORE site search jobs were executed:
<img width="1402" alt="screen shot 2017-09-12 at 2 12 13 pm" src="https://user-images.githubusercontent.com/1717110/30345988-7c6c9ff0-97c4-11e7-9f67-6fe888bb3754.png">

    - File AFTER site search jobs were executed:
<img width="1414" alt="screen shot 2017-09-12 at 2 11 30 pm" src="https://user-images.githubusercontent.com/1717110/30346037-a18d11ca-97c4-11e7-9e80-1b181376eb46.png">

**Comment by joseorsini** [comment]
Problem seems to be caused [here](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/liferay/util/FileUtil.java#L202-L208). 

- If we have 2 concurrent jobs (running under the same cron expression), first time it comes here for a specific file, it will create a reference on the bundles folder as expected

```
$ ls -lrt /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/6/c/6c71499b-4ebe-4784-b0e3-d4383bd9ac4a/fileAsset/media-listing.less
-rw-r--r--  3 joseorsini  staff   2.9K Jan 26  2016 /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/6/c/6c71499b-4ebe-4784-b0e3-d4383bd9ac4a/fileAsset/media-listing.less
$ ls -lrt /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/2017-09-14_9-26-00/live/demo.dotcms.com/1/application/themes/quest/less/content/media/media-listing.less
-rw-r--r--  3 joseorsini  staff   2.9K Jan 26  2016 /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/2017-09-14_9-26-00/live/demo.dotcms.com/1/application/themes/quest/less/content/media/media-listing.less

```

however, for the second or any concurrent job executed, the code referenced above throws a FileAlreadyExistsException, setting the `hardlinks` boolean to false and then setting both source (
original file in assets folder) and destination (file in bundles folder) to a zero byte file reference

```
$ ls -lrt /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/6/c/6c71499b-4ebe-4784-b0e3-d4383bd9ac4a/fileAsset/media-listing.less
-rw-r--r--  3 joseorsini  staff     0B Jan 26  2016 /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/6/c/6c71499b-4ebe-4784-b0e3-d4383bd9ac4a/fileAsset/media-listing.less
$ ls -lrt /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/2017-09-14_9-26-00/live/demo.dotcms.com/1/application/themes/quest/less/content/media/media-listing.less
-rw-r--r--  3 joseorsini  staff     0B Jan 26  2016 /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/2017-09-14_9-26-00/live/demo.dotcms.com/1/application/themes/quest/less/content/media/media-listing.less
```

Any reason why we have this fallback and set both source and destination as zero bytes if hardlinks is turned off? Despite we attempt to delete the link in case the destination exists, the actual reference in filesystem is never deleted, which explains the exception thrown on this code.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12594 

There's a typo in the Github ticket Id referenced on the commit message and the branch name. Apologies for that.

**Comment by jbjornson** [comment]
This is an extremely disappointing "solution" to this problem.  Your solution is to continue to prepare multiple indexing jobs in the same directory, and simply catch the exception when the indexing jobs collide.  

You have only addressed the symptom of the problem but not the problem itself.  

Does this really fix #6477 that was marked as a duplicate of this?

**Comment by joseorsini** [comment]
@jbjornson,

Would you like to elaborate on a more suitable solution for this issue? The fix that was submitted is meant to avoid the Site Search index to remove references on disk (or converting them to zero-byte files) under certain circumstances:

1. Multiple Site search jobs are executed under the same cron expression.
2. All concurrent Site Search Jobs are attempting to handle the same data on filesystem.

As per your comment on the related Github ticket

I would imagine that you should either prevent the jobs from running concurrently or you should use unique directories when generating the site-search indexes.


Having concurrent jobs should not be an intended limitation of how dotCMS and Site Search work, and indeed, each Site Search index ends up having its own reference in filesystem, specifically under the {DYNAMIC_CONTENT_PATH}/esdata folder, where indexes have their own folder and assets are indexed as ElasticSearch Documents. The temporary resources created for Site Search purposes (like the {ASSET_REAL_PATH}/bundles folder) might be reused under this scenario, however:

1. They are not meant to affect how data is indexed for other Site Search jobs, since each SS Job has its own configuration and handles its own specific set of data/assets.
2. These bundles created for Site Search jobs can be removed altogether once these Jobs are executed.
3. Although it makes sense to have unique folders per concurrent Site Search Jobs under the Bundles folder, the original issue happens once more than one Job tries to access these resources on the Assets folder, which is the centralized repository for every physical asset on your dotCMS instance. Thanks to your input on Github, we were able to demonstrate what happens with concurrent jobs: data corruption, and the exception added on code points to an operation that can be skipped (and logged if Debug is enabled) because the file already exists on the destination folder, and avoid zeroing both source and destination paths at the same time.

The code submitted was also reviewed, tested and approved, and also added on newer versions of dotCMS, just to avoid this from happening to other customers. Initial tests on them, as demonstrated on the Github ticket, indicated the issue was solved and no data corruption occurred afterwards.

If there's a scenario that still presents this issue on your dotCMS instances, please let us know so we can test accordingly and fix if needed.

**Comment by jbjornson** [comment]
Thanks for the details @joseorsini.

I've already made the suggestion and you've even agreed with it: have unique folders per Site Search job (under the bundles folder).  You've done part of the fix for the overall problem, which is handling issues from multiple jobs that are accessing resources in the assets folder.  Take the next logical step and also prevent the jobs from polluting each other if they happen to be running concurrently (via the temporary resources in {ASSET_REAL_PATH}/bundles).

The preference to fix symptoms rather than the underlying problems is also visible with github issue #12242.  This is a bug the type of a field is changed (from type "constant" to type "hidden") when push publishing.  Instead of solving the problem, the fix was to hide the symptom by allowing the now "hidden" fields to be displayed as well as the "constant" ones.  See the commit https://github.com/dotCMS/core/commit/e8e0b755822612f11f18094530b86410a7195066

This kind of focus makes me very concerned about the stability and longevity of the dotCMS platform.  There is also a scary amount of duplicate code in the core codebase.

I'm not trying to start a flame war but lately we've been having more frequent issues with larger and larger consequences.  We are quite frustrated by this because as soon as we begin to gain some confidence with dotCMS, something new fails.  The most recent upgrade was also especially painful.
