### ISSUE TITLE
OSGI Framework tries to deploy bad plugin indefinitely 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8572]
If an OSGI Plugin uses some library that is not properly exported in either:
- the dotCMS/WEB-INF/felix/osgi-extra.conf <br />OR 
- using the dotCMS UI (System -> Dynamic Plugins -> Exported Packages)

it will fail with an error in the log (catalina.out), BUT the framework will try to deploy the plugin indefinitely, so the log file will grow until there is no more disk space available. 

Steps to reproduce: 
- take any of the OSGI examples under https://github.com/dotCMS/core/tree/master-3.5/docs/examples/osgi/. (e.g., 'com.dotcms.tuckey')
- remove any of the required libraries from either osgi-extra.conf or  'Exported Packages' Dialog in the 'Dynamic Plugins' Portlet. (e.g., com.dotcms.repackage.org.tuckey.web.filters.urlrewrite, for the 'com.dotcms.tuckey' plugin) 
- upload the plugin jar through the 'Dynamic Plugins' Portlet

Example of error in the log: https://gist.github.com/dsilvam/e98ebf0aab1329471ca3

Reproduced in master-3.5

**Comment by chrismccracken** [comment]
A felix.fileinstall upgrade should fix this, https://issues.apache.org/jira/browse/FELIX-2702

**Comment by wezell** [comment]
Fixed in 4.0
