### ISSUE TITLE
Update bundled Microsoft SQL driver

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8573]
The current version of the driver we bundle in dotCMS (4.1) is not compatible with Java 8 per Microsoft. We should update to a more recent one (4.2 or later). https://msdn.microsoft.com/en-us/data/ff928484

**Comment by wezell** [comment]
Did we see this issue and do this for a customer and it fixed something?

**Comment by levosgien** [comment]
https://my.dotcms.com/tickets/detail.dot?id=4b68894d-6fcc-4968-a01c-f9682bef751f

**Comment by chrismccracken** [comment]
A drop-in jar replacement from our 4.1 to 4.2 from Microsoft generates failure on startup. https://gist.github.com/chrismccracken/ad1c0dc856445a308ad9
