### ISSUE TITLE
Cluster cache gets corrupted after receiving content

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#8582]
### Environment
Sender: _single instance_
Receiver: _two-node cluster_
dotCMS version: 3.3

### Steps to reproduce
- On the sender side, configure a send_to environment as "push to one server"
- Add both cluster nodes to the environment
- On the receiver side, configure a receive_from endpoint
- Create a new single page
- Push publish the new content

Notice that when pushing the content, in the "push to" combo there are already two environments pre-selected instead of just one.

### Description
The receiver's backend starts to randomly miss backend menu labels and the cache gets corrupted. It was reproduced using both manual and auto-wire configurations.

**Comment by dsilvam** [comment]
https://github.com/dotCMS/core/pull/8644
