### ISSUE TITLE
Limited users cannot add pages even if they have permissions

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8598]
Reproduced in 3.2.4 and 3.3. 

Support Tickets:
https://my.dotcms.com/tickets/detail.dot?id=d0c1f3ff-077d-45fa-a387-b6ee72f5129f
https://my.dotcms.com/tickets/detail.dot?id=385d03d6-4c32-4b90-855a-f07fe1560ff9

Steps to reproduce:

- Create a test role and Assign demo.dotcms.com site and /about-us folder.
- For demo.dotcms.com site, just enable View, Add Children and Edit boxes. Also, in order to replicate client's behavior, assign View Permissions to Containers and Templates.
- For /about-us folder, assign Publish permissions to all Asset Types.
- Assign Website Browser and Content Tabs to this Test Role.
- Create a test user and assign it the new Test Role.
- Login as the newly created user and go to Website Browser. Right click on /about-us and click on New -> Page. Asset Type dropdown is empty.

Screenshots: 

- Test Role Definition
<img width="1328" alt="screen shot 2016-02-10 at 12 49 04 pm" src="https://cloud.githubusercontent.com/assets/1717110/12956219/e14023b4-cff4-11e5-8ebe-32aec966e565.png">

- Add HTML Page view for Limited User
<img width="1325" alt="screen shot 2016-02-10 at 12 49 47 pm" src="https://cloud.githubusercontent.com/assets/1717110/12956225/eb757adc-cff4-11e5-884e-006299056578.png">

Workaround: Setting Permissions at Content Type Level does the trick. However, if we have set granular permissions at role level for Pages, these are not taken into account. 

https://github.com/dotCMS/core/blob/master-3.5/dotCMS/html/portlet/ext/browser/view_browser_js_inc.jsp#L1772

In this line of code, we ask if the user has View Permission over the default Page Asset structure for the current Site (if it's not specified, it defaults to Page Asset Content Type).

**Comment by levosgien** [comment]
Works as designed since pages are now content.
