### ISSUE TITLE
Chrome fails on downloads with a comma in the filename

### ISSUE THREAD

**Issue by hmboonstra** [dotCMS/core#8618]
When trying to download a file with a comma in the filename Chrome shows an error page:

    Duplicate headers received from server

    ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

This is because the filename is not properly escaped, see: https://code.google.com/p/chromium/issues/detail?id=454165

This might be related to an older issue, which is either another part of dotCMS or regressed: #3515

We can confirm this issue in dotCMS 3.2.4 and Chrome Version 48.0.2564.109

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8679

**Comment by joseorsini** [comment]
Related to Support Ticket https://my.dotcms.com/tickets/detail.dot?id=b7ff69eb-f470-483a-b156-d9da415b025f
