### ISSUE TITLE
OSGI plugins logs are being always displayed in catalina.out instead of dotcms.log

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#8653]
Since dotCMS 3.3 any logging from custom code (e.g. example OSGi plugins) is output to catalina.out and not dotcms.log – as it did in dotCMS 3.2.4 and earlier versions. (This coincides with the move in dotCMS to log4j 2).

This can be demonstrated installing dotCMS 3.2.4, 3.3 and 3.5 – and deploying the supplied com.dotcms.hooks OSGi plugin. For 3.2.4 the log messages (on publishing content) appear in dotcms.log – while in 3.3 the same messages appear in catalina.out

This issue is specifically with the OSGi plugin logging. Custom code in static plugins (or JAR files in dotCMS lib/) still log correctly to dotcms.log – but all OSGi logging goes to catalina.out.

For OSGI plugin it seems to take the log log4j2.xml configuration file from the ant-tooling jar instead of the dotCMS/WEB-INF/log4j folder

here is the ticket reference https://my.dotcms.com/tickets/detail.dot?id=426684fa-5d45-492e-9812-324c82490dc8

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8661

**Comment by jgambarios** [comment]
The proper way to initialize the OSGI plugin log4j configuration when the user wants to use the same configuration dotCMS uses is adding this code in the Activator class:

```java

public void start ( BundleContext context ) throws Exception {

        //Initializing log4j...
        LoggerContext dotcmsLoggerContext = Log4jUtil.getLoggerContext();
        //Initialing the log4j context of this plugin based on the dotCMS logger context
        pluginLoggerContext = (LoggerContext) LogManager.getContext(this.getClass().getClassLoader(),
                false,
                dotcmsLoggerContext,
                dotcmsLoggerContext.getConfigLocation());

...
...
...
```

After the initialization of log4j the dotCMS logger can be use anywhere inside the plugin:

```java
com.dotmarketing.util.Logger.Logger.info(this, "Example");
``` 

It is recommended to close the OSGI logger context when the plugin is stopped:
```java
public void stop ( BundleContext context ) throws Exception {

        unregisterServices( context );

        //Shutting down log4j in order to avoid memory leaks
        Log4jUtil.shutdown(pluginLoggerContext);
    }
```
