### ISSUE TITLE
Inefficiency in dotConnect hasOracleDriver() method

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#8655]
Implementation of this method attempts to load the oracle.sql.TIMESTAMP class each time it is called.  This method is called

https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/common/db/DotConnect.java#L896

This method is called from with DotConnect.executeQuery() method.  So, every time we try to execute a query, it is iterating through classloaders attempting to locate this class.

A more efficient implementation would call this method:  https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/db/DbConnectionFactory.java#L275

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10292
