### ISSUE TITLE
Push Publishing: force_true is labeled as false on Publishing Queue, despite it's set to true for a specific bundle

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8683]
Reproduced in 3.3. 
Reported by client: https://my.dotcms.com/tickets/detail.dot?id=512e22ec-4e5d-4976-a5c2-70739251831a

Issue 1: force_true is labeled as false on Publishing Queue, despite it's set to true for a specific bundle.

Steps to Reproduce: 
1. Create a Push Publishing environment with two 3.3 builds running with Enterprise licenses.
2. For Document Management Workflow, add a "Push Publish" Workflow Action under "Editing" Step.
3. Add Push Publish sub-action to this Workflow Action. Also, enable "Save Content (Requires lock)" option. 
4. Go to Website Browser and crete a new Document. 
5. On "Editing" Step, click on your Push Publishing Workflow Step. Set "Force Push" to true and push the file to Receiver side.
6. Go to Publishing Queue portlet BEFORE the file is finally pushed. The bundle for the file aded to Queue shows "force_true" as false. 

Screenshots: 

Workflow Action definition:
<img width="1247" alt="screen shot 2016-03-01 at 9 38 02 am" src="https://cloud.githubusercontent.com/assets/1717110/13430164/e7bc5f30-df91-11e5-8260-4f726f4cc095.png">

Remote Push Action execution. Force Push is set to true
<img width="1249" alt="screen shot 2016-03-01 at 9 39 38 am" src="https://cloud.githubusercontent.com/assets/1717110/13430167/ebdfa6ee-df91-11e5-9937-fcfc93317465.png">

Publishing Queue BEFORE file is pushed. Force Push is labeled as false
<img width="1250" alt="screen shot 2016-03-01 at 9 39 56 am" src="https://cloud.githubusercontent.com/assets/1717110/13430186/025fa626-df92-11e5-830f-835a8f882ad8.png">

**Comment by joseorsini** [comment]
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=baffa244-1fa7-49c3-938b-98e8b14d5a20

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11065

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11204

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF
