### ISSUE TITLE
Enhancement: Force delete build folder of static plugin

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8703]
Reproduced in 3.3 running on Mac OS X El Capitan, Ubuntu Linux 14.04 LTS and Windows Server 2012.

Testing a plugin that includes the following code

```
static org.apache.log4j.Logger log = Logger.getLogger(CustomAuth.class);
```

Which deploys without issues in 2.5.x because of Log4j libraries not repackaged in older versions. If the plugin has been deployed in 2.5.x and then moved to a 3.3 build for testing, Plugins Deployment returns as true despite the Logger class was repackaged in 3.3

Steps to reproduce.

1. Deploy a plugin in 2.5.x which includes call to classes compatible only with 2.5.x.
2. Once the "Build Successful" message is returned, copy the entire plugin to a 3.3 build.
3. Redeploy plugins using the scripts under bin folder. It returns "Build Successful".
4. Remove the plugin's build folder.
5. Redeploy plugins. "Build failed" message is returned.

Plugins deployment output:
https://gist.github.com/joseorsini/60edd745ca79e26d3f10

Potential solution:
Check that build folder is properly removed once bin\undeploy-plugins.bat | bin/undeploy-plugins.sh is executed.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9129

**Comment by oarrietadotcms** [comment]
Tested in OS X, using distro, works just fine.
