### ISSUE TITLE
getContentletVersionInfo() has inconsistent behavior

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#8719]
VersionableFactoryImpl.getContentletVersionInfo(String identifier, long lang) will return a new ContentletVersionInfo with a working inode of 'NOTFOUND' on a cache miss but will return null on a cache hit for an invalid identifier & lang combination. This in conjunction with an empty IdentifierCache will result in unnecessary assets being added to the bundle when Push Publishing when using version 3.2.4.

**Comment by levosgien** [comment]
https://my.dotcms.com/tickets/detail.dot?id=d0a63389-6958-4530-8c63-d77875016c35

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8720
