### ISSUE TITLE
User Accounts: Both Name fields should accept unicode characters

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8750]
Versions: all since 3.x (I believe this worked on 2.x)
Ref Ticket: https://my.dotcms.com/tickets/detail.dot?id=d3d6223f-1c56-493b-acf8-3fe01cfc0fde

For a large part of the world, first and last names will include accents and other unidoce characters.

First and Last name fields of the dotCMS User accounts throws an "invalid" error when trying to insert those.

Try with: Chloé

![asd](http://i.imgur.com/LwKq4nH.gif)

**Comment by nollymar** [comment]
Pull request: [https://github.com/dotCMS/core/pull/9211](url)

**Comment by dsilvam** [comment]
We need to change this doc: https://dotcms.com/docs/latest/add-a-user

**Comment by nollymar** [comment]
Pull request update: [https://github.com/dotCMS/core/pull/9227](url)

**Comment by dsilvam** [comment]
Note to Doc: new regex accepts any char except form-feed, tab, newline, carriage return, >, <

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/add-a-user - marked for 3.6
