### ISSUE TITLE
LoginFactory.doCookieLogin broken

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8771]
The new password encryption methods broke it.

**Comment by wezell** [comment]
@brentgriffin @jtesser Does this affect CAS and LDAP login as well?  We need to test - I am looking at line 195 of the BaseAuthenticator

**Comment by jtesser** [comment]
I don't think so cause we handle that https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/cms/login/factories/LoginFactory.java#L499

**Comment by wezell** [comment]
fail:
```
<%@page import="com.dotmarketing.cms.factories.PublicEncryptionFactory"%>
<%@page import="com.dotmarketing.cms.login.factories.LoginFactory"%>
<%


String fromCookie ="iXKpyu6Bksqb40vMkuRQQw==";


String userId="dotcms.org.1";
String fromCrypt = PublicEncryptionFactory.encryptString(userId);


%>
fromCrypt: <%=fromCrypt %><br>
Works: <%=LoginFactory.doCookieLogin(fromCrypt, request, response)%>
```

**Comment by jtesser** [comment]
i wasn't saying the cookie login was working 
more was commenting on LDAP code

**Comment by jgambarios** [comment]
The problem starts here:

https://github.com/dotCMS/core/blob/1d25de9325c1c8056ff1c54d53b8ab2887ba8d5b/src/com/dotmarketing/cms/login/factories/LoginFactory.java#L68

And ends here:

https://github.com/dotCMS/core/blob/1d25de9325c1c8056ff1c54d53b8ab2887ba8d5b/src/com/dotmarketing/cms/login/factories/LoginFactory.java#L513

The password validation was created to validate the password typed by the user against the password saved in the db, but in the **doCookieLogin** method we are trying to validate the saved password vs the saved password.

```
return doLogin(userName, user.getPassword(), true, request, response);
```

Usually the passed password in the code above is the one typed by the user.
