### ISSUE TITLE
Invalid License:  This server does not have valid license

### ISSUE THREAD

**Issue by lad7** [dotCMS/core#8777]
We have an issue with an invalid server license.  The last known action was a complete full reindex  after the Migrate HTML page tool was complete. (3.3 - Cluster - MSSQL2012)

1.  Cannot login into the admin portal with LDAP or Local Account
2.  Front-end site displays error:  Invalid License:  This server does not have valid license

There should be a better solution to solving licensing issues when you cannot log into the admin portal.

**Comment by jtesser** [comment]
I would recommend you contact support for this. 
You should be able to login with a local account.  This works even with an invalid license.
