### ISSUE TITLE
"Push Publish" nomenclature not standard

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8785]
Sub-action "Push Publish" doesn't actually publish, it just pushes. In addition, we already have a "Publish" sub-action that can be added if needed, so this is confusing users.

![http://i.imgur.com/EAknZtG.png?1](http://i.imgur.com/EAknZtG.png?1)

**Comment by wezell** [comment]
And this:

![screen shot 2016-04-07 at 10 59 54 am](https://cloud.githubusercontent.com/assets/934364/14355740/18d974aa-fcb0-11e5-95a0-04adfb020d56.png)

**Comment by wezell** [comment]
Also see: #8675 #8783
