### ISSUE TITLE
Error deleting field from Structure

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8793]
This issue was reported for a client: https://my.dotcms.com/tickets/detail.dot?id=a3326fb4-36e4-4e89-b099-64b6b726b767

When a field is deleted on a Structure we trigger an update in order to update the field value on each contentlet that uses it (https://github.com/dotCMS/core/blob/master-3.5/src/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L134-L159), in the case of the client that update operation is huge (the update is trying to update **879521** records), as it is a long operation to execute tomcat triggers a timeout (after 60 seconds) even if the execution of the update is still in progress and kills the sql connection.

Stack trace:
https://gist.github.com/jgambarios/32d6b3b33ec42882b55c

**My temporary fix for the client was:**

I created a plugin that improved the update queries in order to update only what needed to be updated (https://github.com/dotCMS/support/commit/783f3b80467eaef5559769f3fbc9d11c29f7c066), meaning instead of doing:

```
update contentlet set text14 = '' where structure_inode = 'f9644a5f-68c7-4051-8862-9b9478405ee5'
```

In the plugin I'm doing:
```
update contentlet set text14 = '' where structure_inode = 'f9644a5f-68c7-4051-8862-9b9478405ee5' and (text14 is not null AND text14 != '');
```

Doing that I was able to lower the records to update from **879521** to **292** and also I suggested the client to change in the **context.xml** file the postgres configuration property **removeAbandonedTimeout** from 60 to 600 in order to increase the time before a timeout.

Like I said is a temporary fix as the fields to remove are not required fields, if the client tries to remove a required field in the same structure **879521** records would be need to be updated.

In the case of deleting a required field to increase the timeout time (**removeAbandonedTimeout**) will help as workaround but not the final fix I think.

We need to make some kind of batch update in order to avoid this kind on timeouts when deleting a field.

**Comment by jgambarios** [comment]
It seems that increasing the **removeAbandonedTimeout** is not a viable solution for this kind of problems as allows to run for long amounts of time a query resulting in a lock of one of the most important tables for minutes.

Still the recommendation is to make some kind of batch update in order to avoid this kind on timeouts when deleting a field.

**Comment by wezell** [comment]
@dsilvam - What are your thoughts here?   I was thinking to do this as a batch this update in a background, 1 time quartz job, 200 records at a time but I'd like to hear other ideas.

**Comment by dsilvam** [comment]
@wezell that is what I was discussing with @jgambarios, doing it as a batch update. Then send a notification to Notification System.

**Comment by brentgriffin** [comment]
The only thing that I would add is that it would be good to send notifications via the notification system both at the start and at the completion of this scheduled process - including details like structure name would be good.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8968

**Comment by jgambarios** [comment]
Tested in master-3.6 with the client database, working as expected.
