### ISSUE TITLE
Edit mode -> publish page should release the lock when page is published

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8806]
**Tested:** 3.3.1
**Ref:** https://goo.gl/W964eX

**Description:** When you unlock and publish a page from the Content page, reopening that page from EITHER edit mode or the content page shows the "Lock for Editing" action as expected. When you publish a page from Edit Mode the lock action doesn't change from "Release Lock".

The workflow for page assets should behave the same way regardless of where they page is edited from.

![lock for editing](https://cloud.githubusercontent.com/assets/1823543/14153348/81e9f14e-f685-11e5-82ce-e678284f5be8.gif)

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9145

**Comment by jgambarios** [comment]
The code in the Pull Request looks good as emulates the behaviour in the Edit Contentlet window ( https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java#L1388-L1389 ), but I think a better solution is to **NOT** force the **unlock** in code after a Publish is done but to modify the default workflow to do it instead.

This solution requires a change in the starter modifying the default workflow and to remove this line: https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java#L1389

**Comment by jgambarios** [comment]
After discussing this with Will and Daniel:

>Will
I am not sure we can make it part of the defualt workflow - the defualt workflow does not have a publish step - it was intended to allow the system to function just as it did before - and allows screens to call whatever they called before.
To your point, if we make this change, it would need to be a rule in the contentapi that if there is no mandatory workflow on the content, when you  publish the content, it will automatically unlock the content.  I don’t know the ramifications of that change
Daniel
yes we need to have only one proper place to do that (contentapi that is), and make sure all clients/callers go through it, which I don’t know if that is the case…
Will
And then we need to decide if this is something we want in the core or not or if it should be written as a post- contenthook
plugin
I don’t have strong feelings.
