### ISSUE TITLE
Plugin deployer does not re-merge properly on deploy-plugins

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8814]
When mergeable configuration is removed from a plugin and deploy-plugins is then run, the plugin override comments from the removed config are not removed from the original file. The results in that original config not be used at all, as it is no longer deployed from the plugin.  This can break things in a fatal way, and it is not intuitive that you must run undeploy-plugins && deploy-plugins just to remove some plugin mergeable config.

**Comment by maurizo** [comment]
Test Passed
Tested on MacOS Java 1.8

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9140
