### ISSUE TITLE
Delete content from CMS Maintenance

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8820]
It says it deletes.  It does not.

Deleting content with this tool should delete the content object in all languages.

![screen shot 2016-04-04 at 11 24 03 am](https://cloud.githubusercontent.com/assets/934364/14253024/db2262d4-fa57-11e5-8454-3278c1a184ab.png)

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/8895

**Comment by jgambarios** [comment]
master-3.6 PR: https://github.com/dotCMS/core/pull/9030

**Comment by shaydotcms** [comment]
Still not working. Tested adding an image in the backend and tried to delete it using identifier but it's not doing it although it says "1 contentlets were succesfully deleted"
Message in logs: 
WARN business.ESContentletAPIImpl: Cannot delete content that has a working copy in another language
Tested on:
master-3.5 // Ubuntu 14.04.1 // Postgres 9.3 // Chrome
master-3.5 // Mac OS 10.10 // MySQL 5.6.23 // FF

**Comment by jgambarios** [comment]
@shaydotcms We need to test this with the master-3.6 branch, it is a 3.6 only functionality.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF... Some new improvements opened
