### ISSUE TITLE
JS error when you try to add rules to bundle 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8823]
The functionality works fine, but if you open the firebug terminal, we have some js errors and the system breaks down... 

Also after add one rule to a bundle the system fail the second time that you try it... 

Here the SC: http://screencast.com/t/4U41pa7jylWQ
Here the complete error: https://gist.github.com/bryanboza/95a2aa9e149aba24e9f11ba28f9620a1

Tested on master-3.1 // H2 // FF

**Comment by fmontes** [comment]
https://github.com/dotCMS/core-web/pull/140

**Comment by bryanboza** [comment]
The first part is fixed, New issue created on #8822
