### ISSUE TITLE
Dependency enhancements adding rules to bundle 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8830]
We are having a dependency issue when you add a page rule on a bundle, and then try to upload to different server

To recreate:
- Add a new folder and a new page into it 
- Create a new rule to this page (rules on pages)
- Add the rule to a bundle 
- Download the bundle to publish 
- Go to receiver side and upload the bundle 

We are not adding the rule dependencies to the bundle, then we are having an error when you try to upload because the dependencies does not exist 

Here the error: https://gist.github.com/bryanboza/c4f6132cfcd4220862dd4d43b315b531

Tested on master-3.5 // Postgres // FF

**Comment by oswaldogallango** [comment]
These are the changes done in core
https://github.com/dotCMS/core/pull/8835

and the changes done in core web
https://github.com/dotCMS/core-web/pull/126
