### ISSUE TITLE
saving content reindexes the content, all dependencies and all the dependencies dependencies multiple times 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8836]
When we call save on a piece of content that has relationships, we end up running a very expensive reindex process on that content and all its dependencies multiple times.  This happens because our commit listeners do not maintain a more global list of what should be included in a reindex and just get run, and this forces multiple reindexes of the same content object and also the content objects related content and the related content to the original related content.

Couple of things:

- Many calls to reindex a content object do not even need to recurse into the related objects.  Things like locking/unlocking content come to mind.  
- We should maintain a list of content inodes that need reindexing in any given thread and reindex those just once.
- We should not be forced to reindex the relationships' relationships

**Comment by jgambarios** [comment]
master-3.6 PRs:
https://github.com/dotCMS/core/pull/9081
https://github.com/dotCMS/enterprise-2.x/pull/365

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF
