### ISSUE TITLE
Issue with foreign characters in url

### ISSUE THREAD

**Issue by kannamraju** [dotCMS/core#8839]
Hi,
We are having issues where by if url has got non english characters like numériques its causing issues in multiple places. To replicate please follow these steps
Steps to reproduce.
Create a folder in root of site with name: Tésting, title: tésting
Add Generic page in that folder: title: Test, Url: index.html
Save and publish.
Navigate to /tésting - results in redirect followed by 404
Navigate to /tésting/ - results in 200.

This is causing a lot of issues for us as even in back end when you edit page and click Admin Section button it will show 404 page.

We are using version 3.2.3. I have tested on 3.3 and even that's having the same issue.
Thanks,
Kumar.

**Comment by scrossley** [comment]
Experiencing same issue. 
Problem seems to be with CMSFilter redirect to UTF-8 encoded incoming Request URI with trailing slash appended. With URI not encoded, this resolves.

**Comment by wezell** [comment]
To clarify - does this happen for site visitors or when editing the page via admin/edit mode?

**Comment by kannamraju** [comment]
Site visitors as well.

**Comment by shaydotcms** [comment]
Passed QA. Tested through site visitors and edit page
Tested locally in:
Ubuntu 14.04.1 // Postgres 9.3 // Chrome
Win7 Pro SP1 // SQLServer 2012 // FF
