### ISSUE TITLE
Non permissioned user can publish content via PublishDate field

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8849]
A user without publish permissions on a piece of content can control the live state of that piece of content via the publish date field. All that user needs to do is set the publish date to now or the past, and upon saving their piece of content it'll publish.

Only current workaround is to either block access to the content type altogether, or not use the publishDate field on the content type.

**Comment by wezell** [comment]
Arnaud, I am looking at the code and I am not sure this is true?  I see it in code that we use the last mod_user to publish or unpublish the content.

**Comment by john-thomas-dotcms** [comment]
Arnaud, I tried to reproduce this on demo and I couldn't.  Here's what I tried, let me know if I missed something:

1. Edit the Document content type, and set the Publish Date property to point at the Publish Date field.
2. Login As Joe Contributor.
3. Add a new Document, and set the Publish Date/Time to a time in the past.
4. Save as Draft (this is the only option in the workflow other than Send for Review).
Result: Document not published.
5. Edit the Document, and set the Publish Date/Time to a time a few minutes in the future.
6. Wait for the specified time.
7. Result: Document not published.

I had another weird issue, where after I did that, and then I refreshed the page, I couldn't view the backend as the "Login As" user any more, but that was something very different.  The document still didn't get published.

Please let me know if I'm missing something here.
Thanks.

**Comment by levosgien** [comment]
No one is able to reproduce at this time.
