### ISSUE TITLE
Unable to add individual rules to bundle 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8852]
When you try to add any rule to bundle, the system is only showing the rule that you select, but if you download the bundle , the bundle contains all the rules... 

Then when you upload in a different server we will remplace all the rules settings if exist and create new ones if not... 

Here the bundle on backend:
![img1](https://cloud.githubusercontent.com/assets/2641437/14396821/04b32920-fd97-11e5-98d0-c1c3c417120a.png)

Here the bundle files:
![img2](https://cloud.githubusercontent.com/assets/2641437/14396827/125f3f1e-fd97-11e5-9b97-f560308818f3.png)

Here the SC: http://screencast.com/t/yNt17OQUbQ

Tested on master-3.5 // Postgres // FF

**Comment by jtesser** [comment]
for now this is right @bryanboza as thge host is a depen and it will add all its rules
