### ISSUE TITLE
User's Permissions not fully cascading from "All Sites"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8853]
Tested on dotcms 3.5 nightly build Linux/Postgres

"1- Login as admin
2- Go to CMS Admin // Users
3- Click on a User's Name
4- Click on Permissions Tab
5- Under ""All Hosts"", give the user Publish access to all objects (Hosts, Folders, Containers, etc.), click the ""Cascade Changes"" checkbox and click the ""Apply Changes"" button. "

**Failures:
Failed to Cascade Containers, Templates, Template-layouts, and Rules**

screenshot of what was cascaded:
http://screencast.com/t/cEmgoOM5y

screenshot of permissions not fully inherited on host:
http://screencast.com/t/N4O0GmbT

No errors in the log - but seems to have completed
https://gist.github.com/DeanGonzalez/61062bfa4db9867fe7801309c643af65

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/8980

**Comment by bryanboza** [comment]
After do some testing over the permissions stuff, we still having some problems here in different databases... 

Postgres: 

- After apply the permissions over any user we the system show a "Permissions Saved" message, but the system show the old configuration, we need refresh the changes after show this message... 

![r1](https://cloud.githubusercontent.com/assets/2641437/15030945/832df156-1212-11e6-90c2-393de67aef04.gif)

FYI: If you refresh the tab, the system shows the changes applied...  

- After you set full permissions and apply changes, when you go to the site permissions tab, we have the "templates-layout" unchecked

![r2](https://cloud.githubusercontent.com/assets/2641437/15031004/04d2bd86-1213-11e6-81d7-1e0f4bf9eeb0.gif)

- After you go to the site properties --> Permissions, and reset the permissions stuff over the site, when you come back to the user permissions and try to apply cascade permissions again, we are loosing one by one every category.... 

![r3](https://cloud.githubusercontent.com/assets/2641437/15031302/da0d3f98-1214-11e6-831c-7d124f401fba.gif)

**Comment by bryanboza** [comment]
In h2: 

- We are having a slow query WARN: https://gist.github.com/bryanboza/65b18d0704fb0e70ad9f1d868f8ccae6, and sometimes the system is appliying the changes and sometimes the job was dying at some point

- Randomly we are having an error message
http://screencast.com/t/fh93GvBvV

And here we have some errors on log: 
catalina.out: https://gist.github.com/bryanboza/7980bc1fc5cf11fb52e3f70987d15550
dotcms.log: https://gist.github.com/bryanboza/e67582292476473aa4398d03a51902e9

**Comment by jtesser** [comment]
@bryanboza if the are only losing the job in H2 this is NOT a problem.  There is a slow query timeout in h2 and h2 is not a production DB. @freddyucv @jgambarios lets not work on this if that is he case

**Comment by freddyucv** [comment]
this:

> Postgres:

After apply the permissions over any user we the system show a "Permissions Saved" message, but the system show the old configuration, we need refresh the changes after show this message...

> 

it is because when you save permission with the cascade option it run in background, and the server response before the all operation is done

**Comment by jtesser** [comment]
OK so u r fixing that @freddyucv ?

**Comment by dsilvam** [comment]
[This](https://github.com/dotCMS/core/issues/8853#issuecomment-217160248) is not a trivial fix @jtesser and it is not part of the original issue reported here. I would create a separate issue for that case.

**Comment by dsilvam** [comment]
To be more specific, Bryan reported two issues:
1. Refresh of the screen needed (separate issue. I recommend open a different one)
2. Template-layouts not being cascade. (this does is part of this issue, but we need to make sure if we are even using those permissions properly)

**Comment by freddyucv** [comment]
> 
OK so u r fixing that @freddyucv ?
> 

No, I am not on this right now, I am working in: 

https://github.com/dotCMS/core/issues/8984

**Comment by jgambarios** [comment]
Following what Daniel and Jason said:

1. I was able to reproduce the refresh of the screen issue without Freddy's changes, so it needs to be a different ticket.
2. About Template-layouts, as Daniel said, it is part of this issue, we just need to make sure how it should work or if it is in use.
3. The h2 problems are not related to the changes made on this ticket
4. And about the third issue I can't confirm that it was broken with this latest changes.: 

> "After you go to the site properties --> Permissions, and reset the permissions stuff over the site, when you come back to the user permissions and try to apply cascade permissions again, we are loosing one by one every category...." 


-------
I will clean up this ticket and we will back to work on it.

**Comment by bryanboza** [comment]
Ok, then i was created a separated issue to take look the h2 stuff: 
https://github.com/dotCMS/core/issues/9014
And create a separated card to the auto refresh problem:
https://github.com/dotCMS/core/issues/9015

**Comment by jgambarios** [comment]
@freddyucv please remember to include the Functional Tests along with the new requested changes, we missed those tests in the previews merge.

**Comment by joseorsini** [comment]
Similar issue was tested in Client running 3.3.1 and locally using Starter Data.

Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=c32027ac-4c8f-410d-a0e7-b17d630e2b9b

1. Create a Literature Content Type with only Two Fields: Title (Text, required, user searchable, listed and indexed) and Description (WYSIWYG).
2. Add German and French Languages to System, via Website Browser.
3. Create a single content for this new Content Type, with Default Language.
4. Open the newly created content and populate all languages with it. Save and Publish. 
5. At this point, 1 Version for Each langauge should be created for the same content. 
6. Go to Sites -> demo.dotcms.com site and add "Nick Reviewer" User to Permissions List. Check all Publish boxes and Cascade all permissions.
7. Login as Nick Reviewer. Go to Content Search Content. 
8. No Literature Contents are listed. 
9. Go back to Backend with Admin user and Import these Literature Contents https://gist.github.com/joseorsini/c02da5420d252ea9224061e737b33d57 as a Multilingual CSV File.
10. Go back to backend with Nick Reviewer user. All contents imported from the CSV are listed. Original one created on previous steps is still missing.  

Please test.
