### ISSUE TITLE
Clicking a tag does not select it in the content search screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8875]
See screenshot.

It works differently on the content edit screen.

![untitled](https://cloud.githubusercontent.com/assets/934364/14530680/058ac61a-0228-11e6-8d45-dd4044549d08.gif)

**Comment by shaydotcms** [comment]
Passed QA. Fix is working on Content Search screen, content edit screen and creating a New Content
Tested locally in:
dotcms-3.5 // Mac OS 10.10 // MySQL 5.6.23 // Chrome & FF v45.0.1
