### ISSUE TITLE
"Update Available" popup still references the Autoupdater

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#8876]
When a new release of dotCMS is available, the **Update Available** notification appears on the banner in the backend.  If you click on this notification, the **Update Available** popup window appears.

In the popup window, below information about the available upgrade, there is a **Learn how to use the Autoupdater** link.

Since Autoupdater is no longer supported in 3.3 and above, it appears this link should be removed (or changed, and then pointed at a different video or the [Installation documentation section](http://dotcms.com/docs/latest/installation)).

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8882

**Comment by bryanboza** [comment]
Unable to test before create dotcms_3.6 in artifactory. This because 3.5 is not showing the update message...

**Comment by jgambarios** [comment]
@bryanboza I think you could change your version manually modifying this file:
https://github.com/dotCMS/core/blob/master-3.5/src/com/liferay/portal/util/build.properties

Changing the **dotcms.release.version** property to for example **3.3.2**

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // H2 // FF
