### ISSUE TITLE
Site Search: Archived contents are indexed if they don't have an expiration date

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8877]
Reproduced in demo.dotcms.com site and reported by client https://my.dotcms.com/tickets/detail.dot?id=0f6455c9-0a79-48b5-ad43-8020b9e89b03 

Steps to Reproduce. 
1. Make sure the News content type has set a Publish and Expire Date on the Content Type properties. 
2. Create a new News content, called "Test News Item". Set the Publish date to current date and check the "Never Expire" box. 
3. Save and publish the content.
4. Create a Site Search Index and a job that runs every 2 minutes, which will index demo.dotcms.com site. 
5. After its first run, check that the News Content you created is listed on the Index. 
6. Unpublish -> Archive the News content. 
7. Wait for the Site Search Job to run again. Once it's done, search for the same News Content.

In backend, the content will be listed. If there are any frontend implementations of Site Search, the content will be listed as well and its link will redirect to 404 page.

Screenshots: 
- News Content: 
  <img width="1226" alt="screen shot 2016-04-14 at 11 49 14 am" src="https://cloud.githubusercontent.com/assets/1717110/14534580/d2eed4f2-0237-11e6-8802-bf06f3f1b1b5.png">
- Site Search Job definition: 
  <img width="1182" alt="screen shot 2016-04-14 at 11 50 22 am" src="https://cloud.githubusercontent.com/assets/1717110/14534592/e2d6fb7e-0237-11e6-8c56-4152d1364f60.png">
- News content is listed after the Job's first run. At this point, the content is still published.
  <img width="1224" alt="screen shot 2016-04-14 at 11 49 51 am" src="https://cloud.githubusercontent.com/assets/1717110/14534679/34223aca-0238-11e6-9eaf-a586157a8dab.png">
- News content is listed after it's archived. 
  <img width="1209" alt="screen shot 2016-04-14 at 11 55 14 am" src="https://cloud.githubusercontent.com/assets/1717110/14534691/443254ae-0238-11e6-837e-ba84c31d8520.png">

**Comment by joseorsini** [comment]
Issue was reproduced with default EE jar in 3.3.1 and with a backported fix of this https://github.com/dotCMS/core/issues/6477 on a 3.2.4 install (on a cloud client). Although this issue is different than #6477, it would be good to have both fixes committed and merged.

**Comment by wezell** [comment]
If you don't have an expire date and you "unpublish" it will just publish the content again, correct?

**Comment by joseorsini** [comment]
Yes @wezell
