### ISSUE TITLE
All delete User in UI

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#8879]
Allow admin to delete users in the dotCMS db  (admin = has access to portlet) 
Allow admin user to select another user to replace where the deleted user’s user id is stored in related tables (mod_user).
See this as a starting point:
	http://dotcms.com/codeshare/deleting-a-user-from-the-database

**Comment by oswaldogallango** [comment]
the following language keys needs to be translated

select-a-user-to-replace-current-user-entries-on-db=Select a User to replace current user entries on the database
+delete-User=Delete User
+delete-and-replace-same-user-error=Sorry, you cannot delete and replace entries with the same user
+replacement-user-required-error=Sorry, you cannot delete without selecting a replacement user for database entries

**Comment by oswaldogallango** [comment]
this is the pull request https://github.com/dotCMS/core/pull/8976

**Comment by jgambarios** [comment]
master-3.5 PR: https://github.com/dotCMS/core/pull/9054
master-3.6 PR: https://github.com/dotCMS/core/pull/9057

**Comment by bryanboza** [comment]
We have an error when you try to delete any user.... 

- When you click to delete user, in the User Detail tab, the system is showing a drop-down with all the user roles, to select one to remplace current user entries on the database... But after delete any user we still showing the deleted user in this list... 

**FYI: If you select a deleted user to remplace the current, we are getting an error on log and the delete process is failing... **
ST: https://gist.github.com/bryanboza/6644955381ce2afb8d68d07671bc1b40

![r1](https://cloud.githubusercontent.com/assets/2641437/15120897/27fb15cc-15d5-11e6-94c0-3be145cc7c7f.gif)


Tested on master-3.5 // MySQL // FF

**Comment by bryanboza** [comment]
Also, maybe we need remplace the message, and be clear that we are not replacing permissions neither roles, just modifying the "mod_user" and "locked_by" columns in the data base...

**Comment by wezell** [comment]
We are deleting the user_role as well, aren't we?

Also, are we doing any reindexing?

**Comment by oswaldogallango** [comment]
@wezell, yes, we are deleting the user_role and the updateUserReferences method for contents is reindexing the contents modified.
