### ISSUE TITLE
Remove unneeded JS files from src

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8881]
We have a ton of old libraries and unneeded js files in our source code.  We need to remove them and remove the references to them.  I have culled the list somewhat successfully with this (though I think we still need the util.js and some others)

![screen shot 2016-04-14 at 11 58 03 am](https://cloud.githubusercontent.com/assets/934364/14536501/ae1e0d92-0240-11e6-8bc7-42a10123a9fc.png)

**Comment by jgambarios** [comment]
Merged in master-3.6 ( https://github.com/dotCMS/core/commit/5cc1efe95010a3da9012e681f1cc22c32f749c56 )

**Comment by bryanboza** [comment]
Fixed with the #8993, tested on master-3.6 // Postgres // FF
