### ISSUE TITLE
Mandatory Workflow: hides Copy, Unpublish, and Republish options for all users

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8884]
Ref: https://my.dotcms.com/ticket/spindex-49
Version: 3.3.1
Tested on: Demo

Description: if a workflow is mandatory, users do not get the COPY, UNPUBLISH, or REPUBLISH option in the right-click menu that shows up on the content search results page for each content item. Only options they see are "Publish, Edit. This works fine if you uncheck "MANDATORY" at the workflow level.

Steps to reproduce:

- Go to "Content" page on demo.dotcms.com, filter by "News"
- Right-click and see the options: Edit, Publish, Unpublish, Republish, Copy (see below "default workflow")
- Now set the workflow "Default Scheme" to be Mandatory
- Go to Content Page, filter by News, right-click any news item and see the option: Edit

Note: does not matter was "default action" is set to, and this is done using a CMS Admin user.

**Default Workflow**
![screen shot 2016-04-14 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/1823543/14544080/4b97f884-0265-11e6-9445-23fd4d4d64da.png)

**Default Workflow - Mandatory**
![screen shot 2016-04-14 at 5 22 04 pm](https://cloud.githubusercontent.com/assets/1823543/14544089/6530fc14-0265-11e6-8dea-4907dc045b92.png)

![copy workflow](https://cloud.githubusercontent.com/assets/1823543/14544242/2ef27f1e-0266-11e6-928d-ac372e21634d.gif)

**Comment by brentgriffin** [comment]
FYI - seems to be broken in 3.5 as well

**Comment by wezell** [comment]
I believe this is correct behavior.

**Comment by sreedharathikam** [comment]
Your comment is applicable for the Publish, Un-publish actions but not for the Copy feature as we dont have a action let which allows us to just copy an existing piece of content. As per my understanding, Copy feature is very similar to creating a new content and workflow comes into play only on an existing content element.

**Comment by wezell** [comment]
Sreed:

We might need to create a CopyContentActionlet but I think the above is right.  If we were to have a copy feature by defualt, we could only show it if the mandatory workflow has a defualt 1st action.  Otherwise, what workflow action would you be firing when the content is copied?  It would throw an error.

**Comment by sreedharathikam** [comment]
I agree, we should have a new actionlet to copy an existing content.

By default, copy feature should be visible for mandatory workflows which have a default action configured.

**Comment by levosgien** [comment]
Closing this one, moved to: https://github.com/dotCMS/core/issues/8891
