### ISSUE TITLE
Language missing on LiveCache when moving file assets

### ISSUE THREAD

**Issue by maurizo** [dotCMS/core#8896]
While moving (cut / paste) a file assets the system creates an entry on the _livecache_ with null values on the language thus creating things like this: https://my.dotcms.com/tickets/detail.dot?id=6b72a347-40eb-42fd-9e5d-a5137d91b558

The problem comes from the use of addToLiveAssetToCache(Versionable) (https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/cache/LiveCache.java#L56) on several parts of the code.

A partial solution might be to add language validation here (https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/cache/LiveCache.java#L124) before adding the value to the map by using

```
if(languageId == null)
   languageId = ((Contentlet) asset).getLanguage();
```

**Comment by wezell** [comment]
@maurizo is this causing any issues or just is sloppy code that needs fixing?

**Comment by maurizo** [comment]
@wezell doesn't seem to be creating mayor problems, at least is not reported by the client as such.  We might be doing an extra hit on the cache after the asset is moved but that is all.
