### ISSUE TITLE
Live and a working content can be Archived without being unpublished first

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8898]
If a piece of content or page has a live and a working version that are different, the system mistakenly allows to Archive it without being unpublished first through Content Search.

This behavior is not consistent with the fix provided in card https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/880

Steps to reproduce:

Create a new page and publish it
Navigate to Content Search and search for the page you just created
Edit any field and hit Save, do NOT publish it, this way you will have a live and working version
If you click the checkbox next to page, you can click the “Archive” button without unpublish the page first. The expected workflow should be unpublish the page first then archive it.

This behavior is not consistent with the fix provided in card https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/880
![live_and_working-c83d65](https://cloud.githubusercontent.com/assets/934364/14610969/04927c9c-055e-11e6-82c5-327d3958425f.gif)

**Comment by oarrietadotcms** [comment]
Oh, I focused on the "right-click" options and forgot the buttons at the end of the page.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8931

**Comment by shaydotcms** [comment]
Passed QA.
Tested locally in:
Win7 Pro SP1 // MySQL 5.7.11 // FF v45.0.1
Ubuntu 14.04.1 // Postgres 9.3 // Chrome
