### ISSUE TITLE
Past time machine not working in foreign language

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8899]
If you create a past time machine in another language different than English or Spanish, the TM is not found

Steps to reproduce:

1- Create a 3rd language: french or german or etc…

2- Create a new folder “test” in the root and 3 index pages inside it: 1 index page in english, spanish and french. Add content to each page
![clip-bfd0-b13d](https://cloud.githubusercontent.com/assets/934364/14611124/b6cbadd4-055e-11e6-802c-1c3f0cf053fd.png)

3- Create the past time machine snapshot

![clip-6cb6-b145](https://cloud.githubusercontent.com/assets/934364/14611151/d54b1614-055e-11e6-9627-80a85057e9d7.png)

4- Verify each index page for each language. 
![clip-0459-6224](https://cloud.githubusercontent.com/assets/934364/14611128/bb994146-055e-11e6-8d14-ddf72da69390.png)

You will see that past time machine in french is not found, even when it’s available.

**Expected Behavior:**

In dotCMS, we have this property: https://github.com/dotCMS/core/blob/master-3.5/src-conf/dotmarketing-config.properties#L22 . If the page does not exist in the selected language, this property will make the page fall back to the default language when set to true. As per Will's input, we need to respect that.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8954

TimeMachine is now respecting the property in https://github.com/dotCMS/core/blob/master-3.5/src-conf/dotmarketing-config.properties#L22

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 with 4 languages and now this is working fine...
