### ISSUE TITLE
ContentResource does not include content tags

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8903]
If you have a piece of content that has been tagged and you are viewing it as JSON or XML, the tag field shows up as empty.  This was not the case in 3.3.  

http://demo.dotcms.com/api/content/id/f23c6b0a-ed11-436b-a350-61c47b388370

## 3.3
![screen shot 2016-04-18 at 3 12 27 pm]
(https://cloud.githubusercontent.com/assets/934364/14617740/6029e4ae-057d-11e6-8e2a-176437f3dd45.png)

## 3.5
![screen shot 2016-04-18 at 3 12 19 pm](https://cloud.githubusercontent.com/assets/934364/14617749/6e3f2752-057d-11e6-854c-419f500e0ca7.png)

**Comment by oarrietadotcms** [comment]
The logic Will submitted was already there and was improved by my changes in #8953 . I double checked the solution still works. 

https://gist.github.com/oarrietadotcms/be2d9ff9105b276568fe1b111363e477

**Comment by dsilvam** [comment]
This is fixed in https://github.com/dotCMS/core/pull/8990/commits/94e0d40c024cd8d1bad1a710dc9f0ca74de7154a. Marking as merged.

**Comment by shaydotcms** [comment]
Passed QA. Content Tags and Categories when there is data
Tested locally in:
master-3.5 // Win7 Pro SP1 // SQLServer 2012 // FF 
master-3.5 // Mac OS 10.10 // MySQL 5.6.23 // Chrome
