### ISSUE TITLE
Issues with dropdowns in some conditionlets

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#8916]
In some conditionlets that allow search in the dropdown but do not allow additions, the dropdown will get stuck and not display its values until the page is refreshed

Steps to reproduce:
1. Go to Rules portlet and create a new rule
2. Choose a conditionlet that allows search in the dropdown but do not allow additions. i.e.: Browser conditionlet
3. Type into the browsers' dropdown a value that is not listed such as "1234" or "test" and hit Enter key
4. You will see the dropdown is not showing the values until the pages is refreshed

![conditionlet dropdown](https://cloud.githubusercontent.com/assets/8741846/14648193/4f0efb86-061e-11e6-9e0e-1f2c88a4ca2b.gif)

**Comment by maurizo** [comment]
I've followed this issue to the semantic minified code.  So far the _onShow()_ and _onHide()_ methods are called on the dropdown and the _onShow()_ is able to see the list of options on the options array.  The _onShow()_ method on our dropdown code is a wrapper for the _show()_ method on semantic, and this is one the one that fails to do the animation to show the content.
