### ISSUE TITLE
Some conditionlets allow to input negative values

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#8917]
Some conditionlets such as "Number of Visits" or "Pages Viewed" allow negative values, which really doesn't make sense.

Steps to reproduce:
1. Go to Rules portlet and create a new rule
2. Choose Number of Visits or Pages Viewed conditionlet
3. Input a negative value and save the changes
4. You will say that changes are successfully saved

**Comment by oarrietadotcms** [comment]
PR for core-web: https://github.com/dotCMS/core-web/pull/141
PR for core: https://github.com/dotCMS/core/pull/9022

Please let me know when you merge this in order to publish core-web to artifactory.

**Comment by oarrietadotcms** [comment]
Note: We need to address this issue to improve the constraints/validations for the Rules Engine: https://github.com/dotCMS/core/issues/9024

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // MySQL // FF

**Comment by bryanboza** [comment]
We still having problems with the negative values, now we have a nice validation, but if you have a rule saved, and you only try to add the (-) symbol to the value, the system is showing an error, but is allowing turn on the rules... 
SC: 
![r72](https://cloud.githubusercontent.com/assets/2641437/15084580/9e1c7278-1391-11e6-933b-25f032c4a380.gif)

Tested on master-3.5 // MySQL // FF

**Comment by oarrietadotcms** [comment]
The error reported by @bryanboza was not created by this change. I created this issue in order to work on the fix in the future. https://github.com/dotCMS/core/issues/9075
