### ISSUE TITLE
Missing tests in AllTestsSuite

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8918]
We need to add the missing Unit/Functional tests to AllTestSuite for them to be run in Jenkins.

Specifically quite few tests under test/com/dotmarketing/portlets/rules package are missing.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8975

**Comment by bryanboza** [comment]
This is a Jenkins change, then don't needs QA
