### ISSUE TITLE
Prototype an 'extended bootstrap' Ng2 app.

### ISSUE THREAD

**Issue by ggranum** [dotCMS/core#8921]
Create a prototype of an app similar to that described by https://www.mediacurrent.com/blog/blog-series-weather-underground-angular-2-introduction.

Goals/Stages: 
- [ ] Load multiple Ng2 components into a root page. 
- [ ] Mix in some content from the existing UI
- [ ] Demonstrate Router navigation in one of the root components Ng2 Component
- [ ] Load a dotCMS 'tab' within an Ng2 app ( to support Ng2 Components living beside Dojo / existing content )

**Comment by wezell** [comment]
While I think the above is good, what I would really like to see is this this inside out- lazily load an Ng2 app/component in a dotcms tab - and prototype replacing the rest portlet.

**Comment by ggranum** [comment]
@wezell I updated the final bullet to more accurately match what I meant. 

When you say replace, do you mean a) 'rewrite such that the admin console doesn't have need of the BaseRestPortlet class any longer (deprecate)' or b) 'Load rest portlets into a Component'? 

Given that we have so few rest portlets, and they aren't visually complicated, I think rewriting them as pure Ng2 components would be the easier option - which is to say, option (a). 

I think it will be possible to create a fairly simple 'ng-iframe-component' that takes a url. If so, we'd *might* be able to bootstrap the app at the post-login page and then not have to reload the entire page on each tab-click navigation; basically route the url of the menu item into the ng-iframe-block. There's probably something small, tedious and annoying that will make this not so easy -- but maybe we'll be lucky. 

If swapping out the jsp+dojo tab menus for an Ng2 driven, sort-of-single-page app isn't possible, then adding an app to the page as tab content is something we've already done, so I'm not imagining we'd have any difficulties with it that we haven't already experienced. Replacing the rest portlet would mean rewriting the existing ones as a set of Ng2 components that consume data from new 'nouvo ReST' endpoints. 

If we can do the first path - Ng2 drives the tab menus - then we can communicate from the 'body' of the tabs\* to the page as a whole. So, side-by-side panels that aren't bound to a particular parent tab, whole-page modal dialogs. And all the advantages of not reloading the Ng2 app and supporting code on each navigation update.

Does that seem like we are aiming in the same direction?


\* the tab bodies that we update as Ng2 Components, not the tab bodies that are still loading in iframes.

**Comment by jtesser** [comment]
excited about this one @ggranum where are we on this?

**Comment by ggranum** [comment]
Wasn't as hard to get nav tabs opening in an iframe as I'd feared it might be. Haven't tested it extensively, of course, but did a global search and replace of uses of 'top' and swapped them with 'window'. I wasn't careful in any way, so I'm sure it breaks in places. But it works well enough that the approach is certainly worth considering - it's obviously going to be a lot of work, and will need a ton of testing.

I'm working on pulling in the menu items from a rest endpoint (this part is already working, but with top level items only), and then using those to create navigable routes (the new bit) -- http://blog.mgechev.com/2015/12/30/angular2-router-dynamic-route-config-definition-creation/  

There's also an issue with some of the pages that are loaded via a JS call, but that's a cross site issue that is due to not proxying correctly yet in the demo/dev environment.
