### ISSUE TITLE
Image not showing up in edit mode 

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#8928]
When you add a contentlet with a image field to a page, the image is not showed in the edit mode, however after the image is publish in any page and after that the image work in any others page
.

![bug](https://cloud.githubusercontent.com/assets/10408015/14723610/c4eb7a82-07db-11e6-895e-c4d11d436031.gif)

![test2](https://cloud.githubusercontent.com/assets/10408015/14723845/d59276be-07dc-11e6-8ba2-6b4417837826.gif)

**Comment by freddyucv** [comment]
maybe fix with this PR: https://github.com/dotCMS/core/pull/8947

**Comment by bryanboza** [comment]
We still having some problems with this type of images... 

- Now we can see the image in preview mode, but we can't see the image thumbnail from the "Select file" window... 

![r2](https://cloud.githubusercontent.com/assets/2641437/15058185/139ceeac-12d8-11e6-9b1c-8a8111294601.gif)

To recreate: 
- Create a new content type with an image filed 
- Create a new container and add the created content type 
- Create a new template and add the created container 
- Create a new page and select the created template 
- Try to add a new content and upload some .svg image 

Also we are having errors on log, when you save the content... https://gist.github.com/bryanboza/facc894f47f4a5e7f0ccc38bf2f04cc2

Tested on master-3.5 // MySQL // FF

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5.1// MySQL // FF
