### ISSUE TITLE
Personas should only be permitted to exist in default language

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8934]
PersonaAPIImp should not permit personas to be created in languages other than the default language.  The validatePersona method should make this check and if it fails, it should throw a DotContentletValidationException

Acceptance Criteria:
* Should still be able to create new personas in the language matching the company default language
* When trying to create a persona in a language other than the default language, you should receive an error message.
* Make sure adding a persona via the content RESTapi only accepts default language

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // Postgres // FF

**Comment by bryanboza** [comment]
Some related issues created: https://github.com/dotCMS/core/issues/8946, https://github.com/dotCMS/core/issues/8945

**Comment by jgambarios** [comment]
Closed the original issue as the main work is done and new tickets related to these changes were created.
