### ISSUE TITLE
Wrong URL name assigned with foreign characters

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#8944]
When you use foreign characters in the page name, the system changes the foreign character with a “-“ in the page url

![image](https://cloud.githubusercontent.com/assets/8741846/14790646/57edc1d2-0acf-11e6-9962-788e8dda31e7.png)

![image](https://cloud.githubusercontent.com/assets/8741846/14790662/6b89a350-0acf-11e6-8bb0-4c39b5240f2d.png)

Steps to reproduce
1. In Site Browser, create a new page using foreign characters such as “pâge1” in the title. Save the page.
2. You will see the URL name is changed to "p-age1”, but the system should be consistent with the title (the URL can be manually update to match the title)

**Comment by brentgriffin** [comment]
I don't believe that this is a bug.  URL is not permitted to contain this character unless it is url encoded.  I believe the current implementation converts the invalid url characters into dashes - i.e. spaces, etc

What is the desired URL here?  dash or URL encoding of the character?
