### ISSUE TITLE
Update Admin bootstrap Style branch with latest master-3.6 so we can see next steps

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8951]
Merge the branch with the bootstrap look and feel with the latest master-3.5 so we can run it and look at it together.

**Comment by fmontes** [comment]
This is done in the branch: new-dijit-theme3.5

**Comment by fmontes** [comment]
Needs to rebase from master-3.6

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9004

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF
