### ISSUE TITLE
Unable to “save” or “save / publish” vtl file

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#8952]
When you try to “save” or “save / publish” a vtl file, they systems displays the message "Unable to set binary file Object" and you're unable to do it.

![vtl error](https://cloud.githubusercontent.com/assets/8741846/14821961/fd3a98b2-0b89-11e6-874e-0ddedcd7629c.gif)

Steps to reproduce:
1. Login to dotcms
2. In Site Browser, navigate to /application/vtl/pages/events/calendar-detail.vtl
3. Right click over the file> Edit
4. Now just click “save” or “save / publish”, you don't even have to edit the vtl file
You should be able to edit and “save” or “save / publish” the vtl file.

Error in the logs: https://gist.github.com/shaydotcms/5208a9dcfacf4df7aa98f79bc28edcb7

Tested on dotcms-3.5

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/8991

**Comment by shaydotcms** [comment]
Passed QA. System does allow to save or save/publish VTL file
Tested locally in:
master-3.5 // Win7 Pro SP1 // SQLServer 2012 // FF
master-3.5 // Mac OS 10.10 // MySQL 5.6.23 // Chrome
Test case: http://qa.dotcms.com/index.php?/cases/view/61939
