### ISSUE TITLE
JS errors in the ES Search portlet 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8955]
We have some JS error on console when you go to the ES Search portlet... 

![r1](https://cloud.githubusercontent.com/assets/2641437/14828097/aa227974-0ba2-11e6-9885-5e8d8b60db2b.gif)

Tested on master-3.5

**Comment by jgambarios** [comment]
master-3.5 PR: https://github.com/dotCMS/core/pull/9048
master-3.6 PR: https://github.com/dotCMS/core/pull/9052

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // MySQL // FF
