### ISSUE TITLE
Needed better cache handling inside PermissionBitFactoryImpl

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#8957]
This issue is related to #7759 and the support ticket: https://my.dotcms.com/tickets/detail.dot?id=88e1b9ca-0568-482a-80f2-2e2cb9ef8dc1

The description of the ticket can be found in: https://my.dotcms.com/tickets/detail.dot?id=88e1b9ca-0568-482a-80f2-2e2cb9ef8dc1#comment-5f7260a2-bc0e-43a9-b209-0006042a9736

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9208

**Comment by jgambarios** [comment]
@bryanboza as this ticket is related to https://github.com/dotCMS/core/issues/7759 please test https://github.com/dotCMS/core/issues/7759 again

**Comment by bryanboza** [comment]
Fixed, tested again the #7759 and works as expected... tested on master-3.6 // MySQL // FF

**Comment by wezell** [comment]
This should have been in 3.6.0 - @dsilvam @jgambarios It looks to me that it is in 3.5.1 and NOT in 3.6.0

**Comment by dsilvam** [comment]
@wezell this is in 3.6.0. https://github.com/dotCMS/core/pull/9208
