### ISSUE TITLE
add markdown viewtool to viewtool list

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8962]
We need to take the code in the osgi markdown plugin and move it to dotcms/core

https://github.com/dotCMS/plugin-viewtool-markdown

**Comment by wezell** [comment]
also, we can't miss this commit which added the ability to specify a class for a code field  

https://github.com/dotCMS/plugin-viewtool-markdown/commit/9e8023aa59d0ef3aa8514cef780454e9347c9b1f


You can see its use here:
http://dotcms.com/docs/latest/managing-rules-via-rest

**Comment by dsilvam** [comment]
@wezell we forked the original repo and committed all custom changes we did https://github.com/dotCMS/txtmark/commit/bd37ca883960070d72cbecde5bb41993bcae793b

**Comment by shaydotcms** [comment]
Passed QA. Markdown viewtool added to viewtool list
Tested locally on master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome & FF v45.0.1

**Comment by DeanGonzalez** [comment]
Documented: http://authoring.dotcms.com/docs/latest/markdown-viewtool

**Comment by wezell** [comment]
I think we need to add some link to this page:

http://authoring.dotcms.com/docs/latest/markdown-syntax
