### ISSUE TITLE
Create Google Analytics Portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8970]
This portlet is intended to replace the Dashboard portlet (though the dashboard portlet will live on for now).
- Provide Site managers a screen that would call google analytics API to render google traffic and analytic data in dotCMS.
- RESTPortlet or new Angular2 replacement
- @fishsmith will be the co-story lead and shall provide wireframes
- Host aware - portlet will show different stats based on the host the user is on (should we show the user a host dropdown to select the host they want to see the reporting on?)
- Hopefully not an iframe
- Key off the Google Analytic Key on the host content type.
### Questions
- Is there any data we can get at a page/url level, to replace or improve upon the "Page Stats" screen?

**Comment by bryanboza** [comment]
UI improvements: 

**_Period field_**
- [ ] When you open this field should be in front of the data warning message
SC: https://screencast.com/t/6St2V7tLqxgk

- [ ] We need auto close this field when you click out of the field 

- [ ] We can remove the apply button, I think we can improve the UX if auto set the value after you click on the specific dates and close the field. 

**_Map section_**
- [ ] We are unable to see the region details on this section 
SC: https://screencast.com/t/iaXUw4bKX9l7

**Comment by bryanboza** [comment]
Fixed

**Comment by bryanboza** [comment]
Fixed, tested on master
