### ISSUE TITLE
PagesViewedConditionlet not working

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#8971]
Since the PagedViewedConditionlet was changed to use Clickstream, it is not working as expected anymore, because the Clickstream.addRequest happens after the rules are evaluated (all fire-ons), so the count won’t match. 
1. PagedViewedConditionlet needs to get the proper count of Pages Viewed when it gets executed.
2. PagesViewedConditionletFTest needs to be revisited to make it work.

**Comment by wezell** [comment]
Believe this is fixed
