### ISSUE TITLE
Adding user verification to method in CMSMaintenanceAjax class

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8973]
The "deleteContentletsFromIdList" method in the **CMSMaintenanceAjax** class needs to check the currently logged-in user. Also, the same user must be the one calling the "delete" of the **ContentletAPI** class.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8974

**Comment by jtesser** [comment]
FOr QA ask @jcastro-dotcms or me for the test case

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // Postgres // FF.... Also a new error reported in the #8820, but was fixed too...
