### ISSUE TITLE
Make sure jquery work for custom fields without no-conflicts mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8983]
We need to allow jquery to work otb in no-conflicts mode for custom fields.  Currently prototype.js is eating the $ symbol and there is no reason to have prototype on any screen except for the browser.

- [ ] Change nav_main_inc.jsp to use css based dropdowns
- [ ] remove our custom /html/js/menu.js file

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/8999

> Files where we kept prototype:

> 1. edit_event
> 2. edit_file_asset_text_inc
> 3. view_contentlets

**Comment by jgambarios** [comment]
Missing changes: PR: https://github.com/dotCMS/core/pull/9003

**Comment by bryanboza** [comment]
Unable to navigate throw the site browser after this changes, please check again...

**Comment by jgambarios** [comment]
Missing changes, PR: https://github.com/dotCMS/core/pull/9017

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // H2 // FF
