### ISSUE TITLE
Debug and fix PP

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8984]
- [x] 

 trying to push publish a site redesign, the process failed on the receiver's side with NPE errors, after which, the site (and its index) was left in a bad state.  Pages and files were in the db but not in the ES index and were basically invisible in the UI which insured that future pushes failed as well.

I would like a team to restore the backup we have from auth on one instance and the backup we have on prod on another.  I would then like the team to try to recreate the push issues we experienced.

- [ ] Push the Host - what is the result?  **fail**
- [ ] Force push the Host - what is the result?
- [ ] Push the /application folder - what is the result?
- [ ] Force Push the /application folder - what is the result?
- [ ] Push the /application/themes folder - what is the result?

We need to understand why the above is failing and prevent it.

Additionally, when pushing a folder, the receiver reported "success" when pushing folders but did not display the received folder's name and push of the folder actually failed.

We have the data from the sender (need as of 2016-05-01) and receiver (need as of 2016-05-2) and we need to recreate the PP environment and insure that the PP works correctly.  

---
### Acceptance Criteria
- [ ] Clean restore from the backup files (no manual sql run) and push the host successfully
- [ ] Identify the bad records in the DB, what are they and what is their data problem?  When were they created?
- [ ] Create a new task to have the "fix asset inconsistencies" fix the bad data.

**Comment by oswaldogallango** [comment]
I've been trying to reproduce the error, but I couldn't get the broken site and/or indexes. I get the failed to push but the only exceptions I found were:

1) trying to push folder with/without force push
Failed to publish because an error occurred: Unable to validate field: fileAsset identifier: f34ea71f-d3df-4778-bf99-341861493f05 inode: 

2) trying to push host with/without force push
ERROR util.DependencyManager: identifier is null
com.dotmarketing.exception.DotDataException: identifier is null
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.find(FolderFactoryImpl.java:108) ~[dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.find(FolderAPIImpl.java:506) ~[dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setTemplateDependencies(DependencyManager.java:787) [dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:329) [dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:62) [ee-784a870-SNAPSHOT.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:73) [dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:17) [dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:140) [dotcms_3.5_3.5-100-gf9e1e7d.jar:?]
	

Those are related to bad data

**Comment by oswaldogallango** [comment]
Also in both sides (authoring and receiver), I got a failed message<img width="1315" alt="screen shot 2016-05-05 at 5 19 48 pm" src="https://cloud.githubusercontent.com/assets/1569280/15057622/b9c9a402-12e5-11e6-8495-df45926f3d52.png">

**Comment by wezell** [comment]
Hey so a couple of things.

1. Bad data is almost never a valid cause in my mind, it is a symptom of another problem that we need to solve.  
2. With bad data, we have a few options from a system perspective
   - When we encounter bad data, self heal.  For example, if we have an identifier without a related record in the version info table, add it on the fly in the db.
   - Find out what is causing the bad data and fix that in such a way to prevent that bad data from happening (this can be hard b/c it is difficult to pin down when bad data is created).
   - When we encounter bad data, make our code robust enough to not fail catastrophically and keep going, with the intent that the user can fix it later and purposefully via something like "Fix asset inconsistencies".  

My preferred approach is a combination of 2 and 3.

What we cannot do is just run some manual sql queries to clean things and get things going and then say, "ok now we can push."   I will add some acceptance criteria above.

For what it is worth, I ran "Fix asset inconsistencies" and the integrity checker before trying to push.

**Comment by jtesser** [comment]
Yes @wezell We are still on this one. 

@wezell the Fix Asset and Integrity was that run the first time meaning for us to exactly reproduce we would have needed to do that?  Meaning on Monday that is what you did?

**Comment by wezell** [comment]
In preparation for the site push, I ran the integrity checker. it found one
error which I fixed on the receiver.  After that, it showed no more
conflicts.  Once the host push failed, I ran "Fix Asset Inconsistencies"
 on sender and tried to push again.  This still failed.  Then I deleted all
the push history (this would be like a force push) and tried to push the
host again and nada.

**Comment by oswaldogallango** [comment]
here is the ee jar change https://github.com/dotCMS/enterprise-2.x/pull/366

**Comment by jgambarios** [comment]
master-3.6 PRs:
https://github.com/dotCMS/enterprise-2.x/pull/366
https://github.com/dotCMS/core/pull/9091

**Comment by wezell** [comment]
So, with this code fix, you can take the backup of auth.dotcms.com as it was and the backup of prod dotcms.com and push the dotcms.com host from auth  --> prod?  With no other db cleanup?

**Comment by jtesser** [comment]
yes i believe that was working but let's see Ozzy comment

**Comment by jtesser** [comment]
Will we also have all the errors in a doc and why it was broke

**Comment by oswaldogallango** [comment]
Hi Will, yes here is the link to the google doc https://docs.google.com/document/d/1oFWFG20DeceP3yGx0hSjW8BlpgtotCdLSLBnCYSVljM/edit

**Comment by jgambarios** [comment]
@wezell Yes, you can take the backup of the two servers and the Push Publish will work without any db cleanup.

**Comment by bryanboza** [comment]
Fixed...
