### ISSUE TITLE
Unable to delete content with the Delete Contentlets tool from CMS Maintenance 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8985]
Related to #8973 

We are unable to delete content using the Delete Contentlets tool in the CMSMaintenance, we are showing a success message, but the content is not deleted, also we have an error on log 

Here the log: https://gist.github.com/bryanboza/241bc4d3a0e3aa68a6768720a3efdd40

![r2](https://cloud.githubusercontent.com/assets/2641437/14967295/d4c543fc-1073-11e6-85b9-59f26afb356f.gif)

Tested on master-3.5 // Postgres // FF

**Comment by oarrietadotcms** [comment]
I think this is already reported: https://github.com/dotCMS/core/issues/8820

**Comment by bryanboza** [comment]
Duplicated...
