### ISSUE TITLE
More descriptive error message when Pushing between nodes with same license ID

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8989]
When both sender and receiver are using the same License any Push fails with the following error message in the Push Detail Dialog: 
```com.dotcms.publishing.DotBundleException: non valid bundle. ```

We need a more descriptive message that can help in quickly identify the issue as a License problem

**Acceptance Criteria:**
New message in Push Detail Dialog should be descriptive enough to determine it was caused because an Invalid License.

**Comment by maurizo** [comment]
PR License: https://github.com/dotCMS/license/pull/26
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/374
PR core: https://github.com/dotCMS/core/pull/9213
