### ISSUE TITLE
Unable to save/publish with a date field in the url map pattern

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#8993]
Steps to reproduce:
1. In the News Content Type, add a new field Date (make it required, indexed and show in listing) e.g Current Date.
2. Add the new field to the URL map pattern. e.g /news/{urlTitle}/{currentDate}
3. Try to save and publish a new content.

Error in the log: https://gist.github.com/erickgonzalez/7fc90aeb854bf208a8a7df8119db43b4

Client Reference: https://my.dotcms.com/tickets/detail.dot?id=dc72c81a-c7b9-4235-a08d-3d1941e3dad7

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9948
