### ISSUE TITLE
Struts error deleting content versions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8997]
Related to #7512 

We are having a Struts error when you try to delete some version of any content... 

To recreate:
- Create a new content
- Edit the same content and save a new version
- Now try to edit the content again and navigate to the history tab
- Try to delete some old version of the content 

The system is deleting the content, but we have an error on log

ERROR struts.PortletRequestProcessor: Forward does not exist

Tested on master-3.5 // Postgres // FF

**Comment by jgambarios** [comment]
We missed the functional tests for https://github.com/dotCMS/core/issues/7512 please along with this ticket work on https://github.com/dotCMS/core/issues/9098
