### ISSUE TITLE
Adding more logging information to authentication process using LDAP

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9013]
Support ticket: https://my.dotcms.com/tickets/detail.dot?id=7d4e75f6-ee27-4a63-84de-45652d2531d0

Setting up the correct configuration of parameters for LDAP authentication for the client took a lot more time because, among other problems throughout the road, the code throwing the exceptions **did not include the complete stack trace of the error**. A debug plugin had to be created just to get it.

**Solution:**
- Below line https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/cms/login/factories/LoginFactory.java#L348 , add the following code: `Logger.error(LoginFactory.class, "User " + userName + " does not exist.", e);`
- Replace line https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/cms/login/factories/LoginFactory.java#L352 with the following code: `Logger.error(LoginFactory.class, "Login Failed: " + e, e);`

These simple changes will save the support engineers a great deal of time when troubleshooting LDAP-related problems.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9050/files
