### ISSUE TITLE
Request.getParameter not working in Edit/Preview/Live Modes

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9020]
Reproduced on dotcms 3.5 released version

Easy to reproduce, just set a variable to request a parameter from the url inside a widget on a page

https://gist.github.com/DeanGonzalez/7379adac2fc0e0b52374e31d37f30b46

Then make sure you are hitting the same page with the parameter set in the URL
Variable is null on backend.  Then look on a front end session, variable is being set - seems to be a backend bug introduced in dotCMS 3.5 version only

Here is a screencast: http://screencast.com/t/UoYTXEHm

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9496
