### ISSUE TITLE
Connection leak in ConsoleLogFactoryImpl class

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9021]
Reported by a client via Support Portal: https://my.dotcms.com/tickets/detail.dot?id=36df9ab8-c1ab-451c-a1ea-4629cbe93733

Their WebLogic logs informed about a connection leak in one of our REST endpoints, which goes all the way to the _ConsoleLogFactoryImpl_ class, specifically the _findLogMapper( )_ method.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9023

**Comment by jgambarios** [comment]
Not merged, see comment for it: https://github.com/dotCMS/core/pull/9023#issuecomment-217908252

**Comment by jtesser** [comment]
I agree with @jgambarios here 
We need to fix it here 
https://github.com/dotCMS/core/blob/master-3.7/src/com/dotmarketing/logConsole/business/ConsoleLogFactoryImpl.java#L60

We should get a new connection from DBConFactory for DOtCOnnection to use and close that.  Right in that code.  That is the proper way to handle

**Comment by nollymar** [comment]
After some tests, I was not able to recreate this bug

**Comment by nollymar** [comment]
A fix was applied, following the suggestion made by @jtesser 
PR: https://github.com/dotCMS/core/pull/10791
