### ISSUE TITLE
Replace thumbnail servlet call to Image REST API call

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9025]
On this file 

https://github.com/dotCMS/core/blob/master-3.6/dotCMS/WEB-INF/velocity/static/htmlpage_assets/template_custom_field.vtl#L26 

We're still hitting the /thumbnail servlet for rendering a thumbnail of the selected Template on the Add/Edit Page form. We should call the Image REST API instead and use the available filters and handlers.

**Comment by shaydotcms** [comment]
Passed QA. Tested locally in:
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3 // Chrome
