### ISSUE TITLE
Link checker shows links with parameters as bad links

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#9026]
The Link checker appears to submit links without any parameters appended, so if a full link (with all the parameters) works fine, but if the URL would fail without the parameters, the link shows as bad in the Link Checker.

A prime example is on the current starter site.  If you run the Link Checker on the starter site (or demo.dotcms.com) the following link shows as bad in the link checker:

```
https://play.google.com/store/apps/details
```

Note that the link is displayed without any parameters.  However the actual link on the page includes parameters.

```
https://play.google.com/store/apps/details?id=com.dotcms.starter&hl=en
```

The full link is a valid working link, and when you click on the link in the page it works fine.  But the truncated link shown in the Link Checker doesn't work.  Link Checker should be submitting the full links to prevent generation of false errors.

Reference issue (old): https://github.com/dotCMS/core/issues/1959

**Comment by wezell** [comment]
Also see #12298

**Comment by john-thomas-dotcms** [comment]
Here's some information which may or may not be related (let me know if a new issue needs to be filed).

I set up the link checker workflow action for the documentation content type on auth.  (Note that the workflow change didn't take effect when I set it up even after I flushed all caches and reindexed the content type - it started working a day or two later - but that's another issue).

When I went to save some content this morning, it flagged a link as bad that isn't bad.  However the link the popup shows as not working doesn't even match the link typed into the content.  I'm guessing the link it's showing me is some redirect from the link in the content, BUT note that the link typed into the content is the link that shows in the browser address bar when you're viewing the actual page - so I'm not sure where the link displayed in the popup is coming from.

Link typed in content: https://docs.oracle.com/cd/E11882_01/server.112/e41573/toc.htm
Link displayed as bad in popup: http://www.oracle.com/technetwork/java/tuning-139912.html

Screen shot - you can see both the original link (at line 78 in the content) and the link in the popup in this image:

![image](https://user-images.githubusercontent.com/13456955/29524038-ad7a6a2e-8643-11e7-8b35-9edce7284864.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/513

**Comment by bryanboza** [comment]
Fixed, tested on the last master, and now we are not showing this cases as truncated link...
