### ISSUE TITLE
Respect UI order when evaluating/executing rules 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9031]
UI currently lists the rules ordered by priority descending so we need to match that when evaluating/executing.

**Comment by john-thomas-dotcms** [comment]
Along with this we need a way to set the priority of each rule in the UI.

(I think there might have been a way to set the priority of each rule in an earlier version of the UI, but if there's still a way to do it I haven't found it).

**Comment by dsilvam** [comment]
@john-thomas-dotcms There is no current way to set this in the UI. This would need to be in a separate issue.
