### ISSUE TITLE
Modernize UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9033]
- Begin developing the Angular2 framework we will use to re build UI
- Begin re-writing core UI functions using Angular 2
- First Candidates : Browser Tree, Edit Mode
- Second Candidates: Content search, Content edit
- Trying to turn dotCMS/admin into a 1 Page app or Angular 2 Portlet Framework?
- Have a base ng2 app in the dotCMS backend to allow us a single app that we can add components/directives - as a framework for future buildout
- Angular 2 Portlet will act like the RestPortlet - in the sense that screens will load, inline
- Dynamically generate the NG2 routes based on the Angular2 portlets in the backend.

**Comment by Xander-Steinmann** [comment]
Try to reduce the number of page refreshes

**Comment by petedegraw** [comment]
Reduce redirects. For instance, redirecting the user on saving the Page Properties is not helpful. Much of the time a user will need to go back and edit it again. Instead please provide a link that allows the user to Preview the page. We have had to create our own Preview Link based on feedback here:
https://groups.google.com/d/embed/topic/dotcms/nBL6_GnFwp0/discussion

**Comment by petedegraw** [comment]
Please add support for visual reference or knowledge somehow of contentlets that are localized when viewing a page in Page Preview.

**Comment by petedegraw** [comment]
Please allow all admin screen links to open a link and not trigger a function. Many users try opening in a new window and can't. Redirecting the user from the page they are on proves to be difficult in keeping track of what you are editing.

**Comment by petedegraw** [comment]
Please add the option for admin fields (widgets/content types) to be horizontal or vertically aligned. Vertical takes quite a bit more space than horizontal layouts.
