### ISSUE TITLE
Allow Files to be Multilingual

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9038]
- Currently, files are not multi-lingual.  We should allow this.
- Unit test, Unit test

**Comment by jtesser** [comment]
This means handling BinaryAsset Servlet and all of the sub classes
Any File Servlet that servers files etc... DO NOT WORRY OLD ThumbNail or ResizeImageServlet 
Tooling in Resize GUI UI tooling/Clipboard

**Comment by Xander-Steinmann** [comment]
Don't forget about WEBDAV :(

**Comment by wezell** [comment]
Completed
