### ISSUE TITLE
Enterprise Support Reporter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9047]
dotCMS needs a way for customers collect and report on the general config and health of their installations.  This can be a maintenance tool that build a folder and report files and zip these up to single bundle of information,  and submit it (securly) to my.dotcms.com support portal.  This bundle will contain support reports like:
- the results of `show processlist` or db specific equiv currently running queries
- the customer's current context.xml (let's parse the xml and not include the username and password). (Tomcat customers only).
- a screenshot of the cache stats screen (we will have to render the html and spit it out)
- The current dotmarketing-config.properties
- A threaddump or a few threaddumps (can use the same Threaddump as is already in the maintenance portlet).
- The last 5000 lines of their current dotcms.log using the java tail class we use in the tail log servlet. (Tomcat customers only).
- The JVM stats and other env info from the system info page
- a list of all scheduled quartz jobs
- a list of all plugins in the osgi folder
- results of a db select from cluster table
- complete ES index list and status.
- How long dotCMS took to start up

These reports should each be generated via single classes that implement an interface and if any of the reports fail, the rest of the reports should still continue.  This will allow us to grow the list of "SupportReports" we can run as we find other areas that we need reporting on.

Business case, when we have any support incident, we need a single way to get information from our customers.

**Comment by chrismccracken** [comment]
I was working with a client on something similar yesterday, and was just thinking that for the cache stats a csv export might be easier to work with (load into Excel).

**Comment by chrismccracken** [comment]
Also, this would be helpful https://github.com/dotCMS/core/issues/7569

**Comment by levosgien** [comment]
For reference, here's the inspector tool: https://github.com/dotCMS/dotcms-inspector
Here's the functional requirements we used: https://goo.gl/i73Qg0

**Comment by fmontes** [comment]
Close as per Will request.
