### ISSUE TITLE
Vanity URL As Content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9055]
We need to update our vanity url impl and move what are currently vanity urls to content
  - host (system_host = global)
  - uri field (can be > 255 char and contain regexes)
 - forward to field (can contain $1, $2 which are the matchers from the uri field)
  - response code - drop down list of standard valid http response codes, 200, 301, 302, 401, 402,403,404,500 
  - redirect, forward, (requestdispatcher) or die (stop)
  - order (int?)

**Comment by john-thomas-dotcms** [comment]
Partial doc (for push publishing, minor):

* https://auth.dotcms.com/docs/latest/what-to-know-before-push-publishing
* https://auth.dotcms.com/docs/latest/pushing-vanity-urls

Additional changes will be needed, both for screen shots and update the main vanity URLs doc to reflect changes in the UI (including potential removal of the Vanity URLs portlet).
