### ISSUE TITLE
Prevent changing index replicas when AUTOWIRE_MANAGE_ES_REPLICAS is set to true 

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9064]

**Comment by chrismccracken** [comment]
This is for use with external ES cluster where the replicas are managed external from dotCMS

**Comment by wezell** [comment]
Prevent changing index replicas in dotCMS at the API level.  This holds true for AUTO_WIRE and for manually changing replices 
  
https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/content/elasticsearch/business/ESIndexAPI.java#L619

**Comment by dsilvam** [comment]
This needs to be done both at UI and REST API level
So, if AUTOWIRE_MANAGE_ES_REPLICAS is true
UI: Don't show the option of updating replica
REST: Return 400 error indicating the method is not supported when the setting is on

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9202

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/auto-clustering-configuration

**Comment by dsilvam** [comment]
The default value for AUTOWIRE_MANAGE_ES_REPLICAS needs to be true instead of false 
See https://github.com/dotCMS/core/pull/9202/files#diff-3799c356cc052dac7dbffb328413195eR215
and https://github.com/dotCMS/core/pull/9202/files#diff-32613d9be063650a286d1f6642f910d6R629

**Comment by maurizo** [comment]
Updated PR: https://github.com/dotCMS/core/pull/9222

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9226
