### ISSUE TITLE
Figure out what version of ES we can move to without needing to refactor stuff

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9065]
Don't do it lets look at the change log and upgrade path 

https://www.elastic.co/support/eol

**Comment by chrismccracken** [comment]
Re: https://github.com/dotCMS/core/issues/9041, an argument could be made to get to a new ES version in order to use native mappings for ipv6 addrs. https://github.com/elastic/elasticsearch/pull/17746

**Comment by maurizo** [comment]
PR on core: https://github.com/dotCMS/core/pull/9288
