### ISSUE TITLE
Add a folder to root level with limited user needs Edit Permissions

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#9076]
To reproduce:
1. Create a Role and add the Site Browser Portlet.
2. Create a User and assign that Role.
3. Add the following Permissions: 
   ![screen shot 2016-05-09 at 3 03 19 pm](https://cloud.githubusercontent.com/assets/5278970/15128115/26360eb4-15f7-11e6-8e12-b193b613baae.png)

With the **View** and **Add** Children to Folders should be enough to add Folders at Root level. But it doesn't show the option:
![screen shot 2016-05-09 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/5278970/15128313/508186f2-15f8-11e6-94d5-cc8d9065adfd.png)

But if you give **Edit Permissions** to Folders, it does allow you to add folders at root level.
![screen shot 2016-05-09 at 2 17 48 pm](https://cloud.githubusercontent.com/assets/5278970/15128334/76a02e6a-15f8-11e6-8717-9cda2fc8e023.png)
![screen shot 2016-05-09 at 3 14 24 pm](https://cloud.githubusercontent.com/assets/5278970/15128373/b370910e-15f8-11e6-9be7-72300f660249.png)

**Comment by erickgonzalez** [comment]
Maybe we need the ADD_CHILDREN Permissions here  https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/user/ajax/UserAjax.java#L441

**Comment by gabbydotCMS** [comment]
The behavior reported by Erick persists. I was able to replicate it on demo.dotcms.com (currently running dotCMS 4.1.1.

Related support ticket (note not supported version 3.3): https://my.dotcms.com/tickets/detail.dot?id=56cecffd-b8b9-4901-96df-60bb5ae192db
