### ISSUE TITLE
Record startup time

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9077]
Benchmarking a dotcms installation is a tough issue.  As a (very rough) proxy, we should record the time it takes dotCMS to startup and init all its subsystems.  We have seen historically a linear relationship between the startup performance of dotCMS and the general performance characteristics of the system.  Obviously, externalized DBs and other resources make this less exact but still, there are worse things to record.

- [ ] Record DB startup time
- [ ] Record osgi startup time
- [ ] Record quartz startup time
- [ ] Record es startup time
- [ ] Record cache startup time

**Comment by DeanGonzalez** [comment]
John-Michael is going to handle this one, since he was working already on a performance doc

**Comment by john-thomas-dotcms** [comment]
Doc'ed: http://auth.dotcms.com/docs/latest/performance-tuning#StartupTime

**Comment by john-thomas-dotcms** [comment]
@wezell, would it make sense to also record this info in the log file?

I'm just thinking that it might be useful for diagnostics to be able to look through old logs to see if/how startup times are changing over time.
