### ISSUE TITLE
Create Wireframes for new Vanity Url replacement

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9079]
![vanity urls](https://cloud.githubusercontent.com/assets/934364/15250147/4f86bce4-18f1-11e6-8f04-72a5d7ab13ae.png)
### Notes
- Search field filters against url and redirect url, with wildcards on the left site
- Types can be 
  - 301
  - 302
  - forward (transparent)
- Redirect URL can redirect to another site and/or can include params, e.g.
  "http://www.nytimes.com/2016/05/10/business/dealbook/as-lending-club-stumbles-its-entire-industry-faces-skepticism.html?ribbon-ad-idx=2&rref=business/dealbook&module=Ribbon"
- Clicking "Add" will add a blank row at the top
- Accept regexes
  `^/world/([a-z]+)/([a-z]+)$      /world.jsp?country=$1&amp;city=$2`

**Comment by cfalzone** [comment]
Hey guys, I know this wireframes is a little old now, but I thought I'd give a little feedback on it and put in my +1 for this. 

One thing that would be really nice is just a comment field associated with each one.  We find we put them in and then forget about them then look a year later and wonder why it was put in.  Having some sort of field that we can look at and say, "oh yeah this was for a 2 month long AdWords campaign that ended last year we can get rid of it now" would be a great plus for us.
