### ISSUE TITLE
Image editor is not working with SVG images

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9080]
The Image Editor is not working with SVG image, it is because a SVG image is not a binary files so the tranformation apply to other images files can't be apply to the svg images.
To fix the error must be implemented all the image editor feature to SVG image

![bug_svg_image_editor](https://cloud.githubusercontent.com/assets/10408015/15151345/8bd6c378-169a-11e6-81e8-6728109f41e2.gif)
.

**Comment by jgambarios** [comment]
As a temporary workaround and just for SGVs images the **Image Editor** functionality won't be available.
