### ISSUE TITLE
Incorrect mandatory error message in Content Type with binary-type fields

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9082]
Reported via Support: https://my.dotcms.com/tickets/detail.dot?id=0d650e0d-b1c2-4d36-b057-a83435ef302d
Reproducible on Demo Site.

**dotCMS:** 3.5
**Browser:** Any
**DB:** Any
**OS:** Any

An invalid error message is displayed on the page when you try to save content data **AFTER** you got an error for not filling in a mandatory field, i.e., the second time you try to save the contentlet.

**Steps to Reproduce:**
* Create a Content Type called "My Content", and add three fields:
 * Title: Text field.
 * Image 1: Binary field.
 * Image 2: Binary field.
* Go to the *Content Search* portlet and add content for the "My Content" content type.
* **DO NOT TYPE ANYTHING IN THE "TITLE" FIELD, LEAVE IT EMPTY.**
* Upload images for both the "Image #1" and "Image #2" fields.
* Click *Save / Publish*. You will get an error saying that the "Title" field is mandatory, which is expected.
* Now, type in content in the "Title" field, and click *Save / Publish*.

**Expected Behavior:**
The contentlet is saved correctly. No error messages are displayed.

**Result:**
An error message shows saying that "Image #1" and "Image #2" fields are mandatory.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9519
