### ISSUE TITLE
Content Edit - Improvements to relate content dialog

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#9084]
As a content editor, I want the search functionality in the relate content dialog to be more similar to the content search functionality so that it facilitates the process of getting multiple contentlets related to a specific piece of content.

Current behavior:
1. No hide/show for simple/advanced search
2. No results are shown when the dialog pops up
3. If specific results are selected in a page, moving to the next/previous page will overwrite that selection
4. Default sort order is "Publish" date
5. Navigation allows moving only to "Next" and "Previous" page
6. Only 10 results are shown per page
7. Sort-by links don't work

![relatecontent-searchresults-currentbehavior](https://cloud.githubusercontent.com/assets/1569509/15158948/2a9deca0-16c0-11e6-9a3c-725da7a14ec4.jpg)

Expected behavior:
1. All "user searchable" fields can be used to filter results. Advanced filters will be hidden when the dialog pops up. "Show" filter will include an option to only show the contentlets that have been selected in the search result list.
2. Default language will be set to the same language of the content being edited (from where the relate action was started), and results matching that language will be shown when the dialog pops up.
3. Selected results will be kept when navigating through pages. Selection does not need to be kept if a new search (filter changes) is started.
4. Default sort order will be "Last Edit Date" (desc)
5. Navigation will include "Next", "Previous", and individual pages.
6. 40 results will be shown per page.
7. All "show on list" fields will be included in the search result list, and sorting results by any of them will be allowed.

![relatecontent-searchresults-expectedbehaviori](https://cloud.githubusercontent.com/assets/1569509/15158989/59d18ea0-16c0-11e6-8e0d-e06d05cf33a4.jpg)

![relatecontent-searchresults-expectedbehaviorii](https://cloud.githubusercontent.com/assets/1569509/15159033/824c48d4-16c0-11e6-96c8-a8c8438cc321.jpg)

**Comment by gabbydotCMS** [comment]
Related to https://github.com/dotCMS/core/issues/7808

**Comment by jkshapiro** [comment]
Also #7954 and #7839

**Comment by gabbydotCMS** [comment]
Also requested by: https://my.dotcms.com/tickets/detail.dot?id=2935e649-f653-4683-98e4-e24170716b6f

**Comment by nkeiter** [comment]
Adding the comments from my ticket here, as my suggestions don't quite seem to be covered on this issue ticket:

When choosing related content, a “select all” shortcut in the search results pane would be very handy.

It would also be nice if the search results excluded content that is already related to the content in question. This would reduce the paging/page navigation of search results.

For example, a search returns 3 pages of results. You could “select all” on page one and relate. Then your next search would only return 2 pages of results, and your final search would only show one page of results.

Another shortcut could also be added to relate content on all 3 results pages of search results.

**Comment by nkeiter** [comment]
Also, Language should default to the default language or the one currently in use.  I'm thinking it should not start blank.  Fortunately I've found that the search works even though it flags the field as required.
