### ISSUE TITLE
Time Machine not snapshotting Personalized Content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9097]
Reproduced on demo.dotcms.com and on local 3.5 release version
It seems that the past time machine snapshot does not play well with personalized content.  No personalized content is displaying on the homepage snapshot, not banners, not the news listing, not the bottom banner image - all pull personalized.

See screenshot: http://screencast.com/t/LGjD5XYH2iHe

**Comment by wezell** [comment]
This is a bigger issue - I think sitesearch does not pick up personalized content either.  The problem is here:

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/util/HttpRequestDataUtil.java#L85

Here is .jsp code to test:
```
<%@page import="com.dotmarketing.business.web.WebAPILocator"%>
<%@page import="com.dotmarketing.beans.Host"%>
<%@page import="com.dotmarketing.business.APILocator"%>
<%
String html = APILocator.getHTMLPageAssetAPI().getHTML("/index", WebAPILocator.getHostWebAPI().getCurrentHost(request), true, null, APILocator.getUserAPI().getSystemUser(),new Long(1), "DOTCMS-SITESEARCH_AGENT");
%>
```

**Comment by shaydotcms** [comment]
Passed QA. Past time machine snapshot is displaying well
Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
