### ISSUE TITLE
Functional Tests for the refactored ContentletAPI.delete methods

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9098]
We need to create the functional tests for https://github.com/dotCMS/core/issues/7512

**Comment by jgambarios** [comment]
Added in the 3.6 Milestone as the https://github.com/dotCMS/core/issues/7512 code is already in master-3.6, this kind of functionallity should be always have functional tests.

**Comment by dsilvam** [comment]
Also destroy method needs to change the call to this deprecated method: https://github.com/dotCMS/core/blob/24faecf4ee1c56de73b890e9dbc6235586a79a3d/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1329-L1329, and call the one passing the language instead

**Comment by dsilvam** [comment]
This test should fail after #7512: https://github.com/dotCMS/core/blob/master-3.6/test/com/dotmarketing/portlets/htmlpages/business/HTMLPageAPITest.java#L290
