### ISSUE TITLE
Allow defualt cache region to create separate regions for non-defined caches

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9104]
When first building out the Guava cache impl in 1.9.5, we took the pattern of a "defualt" region from our old JBoss cache impl.  The way this has worked is that any call for a cache on a region that is not defined in dotmarketing-config.properties uses the same single region called "default".  What this gives us is a number of different object caches with different hit rates and object types all falling into the defualt region and reporting metrics as a single entity.   This makes it very hard to get accurate hit/miss rates and hard to debug any performance issue with objects falling into the defualt region.  

What we need is the ability for defualt to act as the template when creating any cache region based on the "defualt" region definition, instead of just being a single region of all the different objects that fall into it.  Imho, this should be our shipping default.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9105

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // Postgres // FF
