### ISSUE TITLE
Fix Assets Inconsistencies - Wrong table alias is making FixTask00004CheckFileAssetsInconsistencies hang

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#9106]
The alias used for the table identifier in https://github.com/dotCMS/core/blob/5cc1efe95010a3da9012e681f1cc22c32f749c56/src/com/dotmarketing/fixtask/tasks/FixTask00004CheckFileAssetsInconsistencies.java#L58 should be "ident" instead of "id" (similar to the query in https://github.com/dotCMS/core/blob/5cc1efe95010a3da9012e681f1cc22c32f749c56/src/com/dotmarketing/fixtask/tasks/FixTask00004CheckFileAssetsInconsistencies.java#L187)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9108

**Comment by bryanboza** [comment]
Fixed, tested on master-3.6 // Postgres // FF
