### ISSUE TITLE
Relationships: Tree order is not always stored properly

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9109]
Reproduced in 3.3.1 and 3.5. 
Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=53399517-d50d-41de-8037-ac81cdabd04c 

Steps:
1. Go to demo.dotcms.com site and create 4 News Contents (let's call them "News Item 001", "News Item 002", "News Item 003" and "News Item 004") and 1 Media Content. 
2. Open News Item 001 and relate it to the Media Content you created. Save and Publish.
3. Open News Item 002 and relate it to the same Media Content. Save and Publish.
4. Follow the steps 2 and 3 for News Item 003 and News Item 004.

Once all contents are related, open the Media Content and see the Relationships Tabs. Contents are unordered. 

From a local test with 3.3.1 and Starter data

```
Media Content: The Node By Murat Pak

331dist=# select identifier, title, text1 from contentlet where identifier = 'e6689690-786c-457f-a6b1-ee3d44b155e4';
              identifier              | title |         text1
--------------------------------------+-------+-----------------------
 e6689690-786c-457f-a6b1-ee3d44b155e4 | video | The Node by Murat Pak
(1 row)

 Relate "The Node By Murat Pak" Media Content to 
- "The Gas Price Rollercoaster" content (with identifier 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6). 
- "Intranet News: Rethinking Budget: 6 Counterintuitive Tips" content (with identifier 7a3d042f-aae4-4e60-8385-7fc5320f572f) 
- "How to invest in equities and stay sane" News Content (with identifier 5246d270-224d-4f5d-a0d4-aff20584328e)

 Data: 

 331dist=# select identifier, title, text1 from contentlet where identifier in (select parent from tree where child = 'e6689690-786c-457f-a6b1-ee3d44b155e4') and inode in (select working_inode from contentlet_version_info);
              identifier              |                           title                           | text1
--------------------------------------+-----------------------------------------------------------+-------
 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6 | The Gas Price Rollercoaster                               |
 7a3d042f-aae4-4e60-8385-7fc5320f572f | Intranet News: Rethinking Budget: 6 Counterintuitive Tips |
 5246d270-224d-4f5d-a0d4-aff20584328e | How to invest in equities and stay sane                   |
(3 rows)

331dist=# select * from tree where child = 'e6689690-786c-457f-a6b1-ee3d44b155e4';
                child                 |                parent                |      relation_type      | tree_order
--------------------------------------+--------------------------------------+-------------------------+------------
 e6689690-786c-457f-a6b1-ee3d44b155e4 | 2943b5eb-9105-4dcf-a1c7-87a9d4dc92a6 | Parent_News-Child_Media |          1
 e6689690-786c-457f-a6b1-ee3d44b155e4 | 7a3d042f-aae4-4e60-8385-7fc5320f572f | Parent_News-Child_Media |          1
 e6689690-786c-457f-a6b1-ee3d44b155e4 | 5246d270-224d-4f5d-a0d4-aff20584328e | Parent_News-Child_Media |          1
(3 rows)

```

![Image](http://i.imgur.com/bDjyw4l.png)

The order in contents is not properly saved in the DB. The list returned here is ordered by the contents' identifiers. 
## 

The root cause of this issue is that, once a Parent Content gets related to a Child Content, and this Parent Content DOES NOT have children contents related yet, it will store the tree_order value as 1. If we do the same for a different Parent Content (by re-using the Child Content), it will be saved as 1 again. Currently, once a Parent Content is saved, it does not take into account if the Child Content is already related to other Contents under the Same relationship, so the Child Content can keep its own Relationships Order.

**Comment by joseorsini** [comment]
This can be reproduced in Master-3.6 repo. Steps are basically the same. 

1. Grab a single Media content.
2. Relate this Media Content to 5 different News Contents (that don't have other contents related to it yet).
3. The tree_order of the News-Media Relationship entries for the Media content is always "1" for all items. Once a Full Reindex is run, the order of contents in the Relationship tab is always random.

**Comment by joseorsini** [comment]
In the scenario above, there is no way to figure out if the added Child (Media) Content to a Parent (News)  Content was already used for other News, because the getRelatedContent methods in the Content API will always search if the Edited Content (In this case, the News Content) has child contents, which will always return zero in this scenario (And it would explain why the tree_order is set to 1). 

Currently, [this method](https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1115-L1147) searches related content for a Media Content with identifier e6689690-786c-457f-a6b1-ee3d44b155e4.

Query: +type:content +Parent_News-Child_Media:e6689690-786c-457f-a6b1-ee3d44b155e4

Sort: Parent_News-Child_Media-e6689690-786c-457f-a6b1-ee3d44b155e4-order

The intended fix is to make it compliant with the information listed in the Relationships Tab: Headline (content title) and Publish Date. 

<img width="1343" alt="screen shot 2016-05-24 at 3 58 03 pm" src="https://cloud.githubusercontent.com/assets/1717110/15517928/60901190-21c8-11e6-9711-4a2de8dbeed3.png">

As you can see, the list is unordered. It's not sorted by Contents' Titles, Publish Dates, Tree order, or even the Contents' Mod Date. Knowing that the Publish Date, or Mod Date does not necessarily indicate WHEN the Relationship was made, there's a chance to sort Contents according to the following:

1. If we're editing a CHILD content from a Specific Content Relationship, Sort their PARENT contents either by contentType.sysPublishDate asc/desc, or just sort them by modDate asc/desc.
2. If we're editing a PARENT content from a Specific Content Relationship, Sort their CHILD contents either by contentType.sysPublishDate asc/desc, or just sort them by modDate asc/desc. 

In this scenario, if we're looking at a Media Content, the sort can be: 

- News.sysPublishDate asc
- News.sysPublishDate desc
- modDate asc
- modDate desc 

if we're looking at a News Content, sort can be the following: 

- Media.sysPublishDate asc
- Media.sysPublishDate desc
- modDate asc
- modDate desc

**Comment by oarrietadotcms** [comment]
Another client requesting this one: https://dotcms.zendesk.com/agent/tickets/96103
