### ISSUE TITLE
JGroups does not allow to validate incorrect address in CACHE_BINDADDRESS propert

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9119]
#6971 
When you set an invalid ip address in CACHE_BINDADDRESS property, JGroups is showing an error in the logs about the invalid ip address, however the system is ignoring this validation https://github.com/dotCMS/enterprise-2.x/commit/8fefb040439183f601b80adbfdef426a307aac24#diff-ff7cdca8ad16477460068fc7dc9a032bR261 because JGroups error comes up first

Steps to reproduce:
Open the file dotcms-config-cluster.properties located in /dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/
Modify the property CACHE_BINDADDRESS and put an invalid ip address, i.e.: 192.168.1.123
Save the change
Start up a dotcms instance
You will see in the logs an error like:
ERROR jgroups.JGroupsCacheTransport: Error initializing jgroups channel: [TCP] /192.168.1.123 is not a valid address on any local network interface

**Comment by oarrietadotcms** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/371
PR core: https://github.com/dotCMS/core/pull/9144

**Comment by shaydotcms** [comment]
Passed QA.
Tested locally in master-3.6 // Ubuntu 14.04.1 // Postgres 9.3 // Chrome and Firefox

**Comment by wezell** [comment]
@shaydotcms shouldn't this message on startup go away?
```
WARN  2016-05-31 08:23:42,344 com.dotcms.repackage.org.jgroups.stack.Configurator:warn(79): JGRP000014: UNICAST.setTimeout has been deprecated: not used anymore
INFO  2016-05-31 08:23:42,396 com.dotcms.repackage.org.jgroups.protocols.UFC:info(67): UFC is not needed (and can be removed) as we're running on a TCP transport
WARN  2016-05-31 08:23:42,412 com.dotcms.repackage.org.jgroups.protocols.TCP:warn(75): failed to join /224.0.75.75:7500 on awdl0: java.net.SocketException: Can't assign requested address
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-------------------------------------------------------------------
GMS: address=cabbage-25596, cluster=dotCMSCluster, physical address=192.168.86.107:7803
-------------------------------------------------------------------
```

**Comment by jtesser** [comment]
i think it is still set in the system props.  @oscar can u look

**Comment by oarrietadotcms** [comment]
It is not coming from our config, seems like a [bug/config from JGroups](https://issues.jboss.org/browse/JGRP-1535). I am testing [the solution](http://jgroups.1086181.n5.nabble.com/jgroups-users-SocketException-WARN-messages-at-startup-td3634.html) on my local and I will commit it if this works.

**Comment by oarrietadotcms** [comment]
"enable_diagnostics=false" works just fine.

PR: https://github.com/dotCMS/core/pull/9160

**Comment by oarrietadotcms** [comment]
Note: There are some JGroups deprecated configs that should be removed in the future: https://github.com/dotCMS/core/issues/9161

**Comment by jgambarios** [comment]
PR for master-3.7: https://github.com/dotCMS/core/pull/9910
