### ISSUE TITLE
Fix jenkins failing tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9125]
Test Result (2 failures )
com.dotmarketing.portlets.htmlpages.business.HTMLPageAPITest.removeOneLanguageOfHtmlAsset
com.dotcms.publisher.ajax.RemotePublishAjaxActionTest.push_archived_issue5086

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9147/files
