### ISSUE TITLE
In Content Search portlet, the dropdown for All / Locked / Unpublished / Archived does not retain selection

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9126]
Reported by a client via Support: https://my.dotcms.com/tickets/detail.dot?id=ab5b91e3-7681-483b-a0ba-c2ed1c137393
Reproducible in Demo Site.

In the Content Search portlet, when a user filters the contents by the "Show:" option (All / Locked / Unpublished / Archived) and either creates a new content or goes to another portlet and come back, the "Show:" option defaults to "All".

**Expected Result:**
The "Show:" filter must work the same as the "Type:", which does remain selected either after adding new content or moving to another portlet and coming back to the Content Search portlet.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9128

**Comment by maurizo** [comment]
Passed Testing
Tested on FF 46.0.1 and Chrome 51.0.2704.79
