### ISSUE TITLE
Add/Edit Content: Multilingual Files cannot be edited properly in Backend.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9139]
Reproduced in 3.5 release and master-3.6, after an upgrade from 3.3.1

Steps to reproduce:

1. Start a clean 3.3.1 build. 
2. Add a Document under /about-us folder. Once it's saved and published, open the content and populate the same content for a different Language (in this case, Spanish). Since in 3.3.1, the system allows you to handle multilingual files, we will have the same Contentlet object with two different Versions (English and Spanish).
3. Upgrade this 3.3.1 data and assets to master-3.6 repo. Once the upgrade is done, go to Website Browser. Only 1 content version (the English one) will be listed in the /about-us folder, however it should list both Contents' versions. Changing the Language dropdown to "All" or "Spanish" won't bring back the Spanish content version. 
4. If you open this document and see the Versions tab, two versions of the same content will be listed there: English and Spanish. If you click on the Spanish one, there's no indication in the backend of the Content Language. 

Screenshots: 

Uploaded file in 3.3.1 - Versions Tab: 
<img width="1169" alt="331-versions" src="https://cloud.githubusercontent.com/assets/1717110/15548794/fa46e82c-2277-11e6-8a61-21fddc51765a.png">

Uploaded file in 3.3.1 - English Version 
<img width="1294" alt="331-english-version" src="https://cloud.githubusercontent.com/assets/1717110/15548542/ea392144-2276-11e6-8b31-37f77c523423.png">

Uploaded file in 3.3.1 - Spanish Version 
<img width="1293" alt="331-spanish-version" src="https://cloud.githubusercontent.com/assets/1717110/15548552/f6f3a256-2276-11e6-8104-996477057014.png">

File after upgrade to master-3.6 - Versions Tab: 
<img width="1039" alt="master-36-version" src="https://cloud.githubusercontent.com/assets/1717110/15548909/30d42120-2278-11e6-9ee7-2417b9a605d5.png">

File after upgrade to master-3.6 - English Version, No Language Dropdown Available.
<img width="1327" alt="master-36-english-version" src="https://cloud.githubusercontent.com/assets/1717110/15548567/0bc36d92-2277-11e6-8272-754335d89626.png">

File After upgrade to master-3.6 - Spanish Version: **This is only available if we click on the Spanish version, from Versions Tab** 
<img width="1029" alt="master-36-spanish-version" src="https://cloud.githubusercontent.com/assets/1717110/15548779/e3620bdc-2277-11e6-984f-1431bcaeab03.png">

**Comment by brentgriffin** [comment]
Jose has tested this and it is a problem on 3.5 as well.
