### ISSUE TITLE
Upgrade to Velocity 1.7

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#914]
We need to goto latest 1.7

We have changes that we made to Velocity 1.6.3 which is what we currently run.  You can checkout the Velocity Code from SVN https://svn.dotcms.org/thirdparty/velocity163-modified

I suggest running diff between all our commits to see changes but here is the summary

We made changes to the following
1. Made stuff Serializable look at the following
    a. velocity163/src/java/org/apache/velocity/runtime/resource/Resource.java
    b. velocity163/src/java/org/apache/velocity/runtime/parser/node/SimpleNode.java
    c. velocity163/src/java/org/apache/velocity/runtime/parser/Parser.java
    d. velocity163/src/java/org/apache/velocity/runtime/directive/Directive.java
2. Alter the way the parserpool gets inited 
    a. velocity163/src/java/org/apache/velocity/runtime/RuntimeInstance.java
3. Altered Hashmap concurrency 
   a. velocity163/src/java/org/apache/velocity/util/introspection/ClassMap.java
    b. velocity163/src/java/org/apache/velocity/util/MapFactory.java

All these changes need to be moved.

**Comment by wezell** [comment]
done and additional work was done in 4.1
