### ISSUE TITLE
CMS Maintenance: Add more details to contents not being indexed.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9141]
Currently, we allow the Maintenance portlet to download a CSV file of all contents that cannot be indexed for several reasons (mostly caused by broken data). However, the CSV file only includes a dump of the dist_reindex_journal table, with all rows that have a priority level of 40 or greater. 

Despite this information needs to be compared against the logfiles in order to find the root cause of the problem with indexing these contents, the CSV file does not indicate where these files can be located, besides, ident_to_index and inode_to_index columns store the same value in the table, so for troubleshooting purposes, it would be good to have instead: 
- Host Name (or Id).
- Parent Path (for pages or files).
- Page/File Name, or Content Title.
- Language of this content.
- Content identifier and Inode.

**Comment by oarrietadotcms** [comment]
FWIW [this is the piece of code](https://github.com/dotCMS/core/blob/b4c02ce8505a2e19183b79ef8b0132b1f312a355/src/com/dotcms/journal/business/ESDistributedJournalFactoryImpl.java#L68-L68) that is duplicating the identifier value under inode_to_index column. This is creating problems when reading the Reindex fail records CSV report. 

I would suggest to remove that unused column.
