### ISSUE TITLE
JWT Authentication filter

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9163]
Create a JWT Authentication filter where the JWT token will be created and/or read.
- The signing key should be configurable

By default the remember me should work only on https, but if a user wants to use it on insecure connections can enable it using a property as using JWT on insecure connections is not recommended.

**Comment by john-thomas-dotcms** [comment]
Doc finalized: http://auth.dotcms.com/docs/latest/authentication-using-jwt
