### ISSUE TITLE
Upgrade core-web project to the latest Angular version

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9166]
1. Upgrade core-web to latest Angular 2
2. Packaging of the upgraded web-core distribution (Packaging and publish in artifactory)

**Comment by fmontes** [comment]
commit 9fdafec5f0834eeb0305d4c7ab0e7f7e34ebaeee
Author: Freddy Montes <freddy@dotcms.com>
Date:   Thu Jun 16 10:22:47 2016 -0600

    Fix publish snapshot task

**Comment by fmontes** [comment]
commit 09d554cdca5e548c8ccce5938571cfd54fcc737a
Author: Freddy Montes <freddy@dotcms.com>
Date:   Thu Jun 16 19:21:15 2016 -0600

    Fix error when click add rule button

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9233

**Comment by jgambarios** [comment]
We need to revisit this task as we upgraded to **RC1** and now the **RC2** was released: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc2-2016-06-15

**Comment by fmontes** [comment]
+1

On Thu, Jun 23, 2016 at 8:55 AM, Jonathan Gamba <notifications@github.com>
wrote:

> We need to revisit this task as we upgraded to *RC1* and now the *RC2*
> was released:
> https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc2-2016-06-15
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/dotCMS/core/issues/9166#issuecomment-228076385>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAt3QL7NUiuCFdEMUbwYA074ucAlYQPJks5qOp5rgaJpZM4IqyNk>
> .
>



-- 
------------------------------------------------------
Freddy Montes
Diseño y desarrollo Web
(506) 8742.6808
freddymontes@gmail.com
http://fmontes.com
Twitter: http://twitter.com/fmontes
http://about.me/fmontes

**Comment by bryanboza** [comment]
Fixed tested on master-3.6 // MySQL // FF and able to navigate through portlets and features normally

**Comment by jgambarios** [comment]
Upgraded to RC2, another will be created for the upgrade to RC3+
