### ISSUE TITLE
Display of portlets inside Angular components

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9168]
With the new menu (https://github.com/dotCMS/core/issues/9167) and routing create a Component that will be able to display the current dotCMS portlets inside iframes (**using popup=true**).

Some notes made by @oswaldogallango about some initial thoughs and problems we saw:
https://docs.google.com/document/d/1yc5kF8_mwghs8rpGJJvM1d24QzzSYM_sgV30RT9SAOc/edit

**NOTE:** We may need to convert this ticket into a Epic and to break it in multiple tasks.

**Comment by jgambarios** [comment]
Initial pull request: https://github.com/dotCMS/core/pull/9280

**Comment by oswaldogallango** [comment]
there are two issue pending related to these changes they are explained here
https://github.com/dotCMS/core/issues/9299 and https://github.com/dotCMS/core/issues/9300

**Comment by jgambarios** [comment]
Initial work done the task will be continue in https://github.com/dotCMS/core/issues/9299 and https://github.com/dotCMS/core/issues/9300
