### ISSUE TITLE
Change how we handle gradle Snapshots

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9172]
Each time we create a gradle Snapshots for a jar (ee, license, etc) we are creating a new Snapshot instead of append versions of it to an existing Snapshot representing a dotCMS version.

**Example of how it works right now:**
![snapshot1](https://cloud.githubusercontent.com/assets/923947/15721234/433fd7be-27f5-11e6-88f6-d85b2091ab62.png)

**And how it should work:**
  _Enterprise
    |--> ee_
![snapshot2](https://cloud.githubusercontent.com/assets/923947/15721233/433e056a-27f5-11e6-89f5-fa78c7a29a4b.png)

## PROS of changing how we handle Snapshots right now: 
1. Thats how it is supposed to work
2. It is a more organized way to structure versions
3. We still have the option to request specific versions of a Snapshot but if we don't need a specific version we
4. won't need to modify the **dependecies.gradle** file each time a new snapshot is created

## CONS
1. We won't be able to append the github hash to each Snapshot.
-This could sound like a problem as we used to use that hash in order to track the origin of the jar in git but we won't need it if on each release we tagged properly all the involved repositories.

------

Our current implementation made sense at the moment and was created in that way for multiple reasons (mainly for bugs in the gradle core related with the Snapshots handling) but I think this is good moment to change it as we are using the recent versions of gradle.

------
**NOTE:** _Please remember Snapshots are only used or supposed to be only used during the development stage, when the product is released we should also release each jar in Artifactory, a released version should never use a Snapshot version of any library._

**Comment by dsilvam** [comment]
Agree with this. The SNAPSHOT should be one per version.

**Comment by jcastro-dotcms** [comment]
License PR: https://github.com/dotCMS/license/pull/28
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/375
Core PR: https://github.com/dotCMS/core/pull/9214

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9224

**Comment by bryanboza** [comment]
Fixed, master-3.6 is working normally after this changes...
