### ISSUE TITLE
TagCache might use remove on put anit-pattern

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9174]
Not 100% sure, I haven't had enough coffee this morning to unwind what is happening, but it looks to me like the TagInodeCacheImpl is removing on a put:

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/tag/business/TagInodeCacheImpl.java#L55

What this can do in a cluster is cause the servers to ping-pong one putting and sending invalidations to the others, then the other having to put and sending invalidations to the first.

**Comment by dotcmsCodeReview** [comment]
I'll look later but I think this is working

**Comment by wezell** [comment]
Agreed
