### ISSUE TITLE
$request.getParameter not responding when logged in

### ISSUE THREAD

**Issue by schalastra** [dotCMS/core#9175]
In 3.5, you can't see the results of a $request.getParameter in Live mode. You can see it when you're not logged in, and you could see it when logged in in 3.2.4.

Refer to https://groups.google.com/forum/?fromgroups#!topic/dotcms/1Ew3PIJEq1A.

**Comment by dishelt** [comment]
Hi, I have the same problem, is there any solution?

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9496
