### ISSUE TITLE
Unable to on-line editing when you copy any page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9178]
We are having some problems when you copy and paste any page, and then try to in-line editing. The system never finish to save, Also if you reload the page, the changes was applied, but the page loose the URL value in the properties

To recreate: 
- Create a new folder 
- From the about-us folder copy the "what we do" page and paste in the new folder
- Try to edit (on-line editing) the copy of the page and save it 
- Reload the page and check the page properties 

Tested on master-3.5 // Postgres / FF

**Comment by jgambarios** [comment]
This error is related to the **copy/paste** and **Inline Edit** of pages with the **Simple Content Page** Content Type, that content type have a **WYSIWYG field**, so the problem is the Inline Content of content living directly in the HTML page after copying the page.

**Comment by DeanGonzalez** [comment]
I just tested 4.3.2 - this has been fixed.  Closing the issue
