### ISSUE TITLE
Images inside generic contents are not being pushed by dependency

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9182]
When you have an image (jpg, png, svg, etc) inside a generic content and push it, the generic content is pushed but the image is not pushed by dependency.

Steps to reproduce:
1. Setup a Push Publishing environment with 1 node per each Endpoint.
2. Create a generic content and add an image (jpg, png, svg, etc).
3. Push the generic content to the Receiver Side.
4. You will see the generic content has been pushed but not its image
Logs don’t show errors

**Comment by jgambarios** [comment]
I think this ticket is duplicated (https://github.com/dotCMS/core/issues/4154) and not a bug as we don't parse the content inside WYSIWG fields in order to find images to push as a dependency.
