### ISSUE TITLE
Add/Edit Contentlet: Recurrence fields are not displayed for Calendar Event Contents

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9183]
Reproduced in 3.3 and in demo.dotcms.com site, running 3.5. 

Reported by client here:    https://my.dotcms.com/tickets/detail.dot?id=986acbb3-4a42-40ba-8ff8-43205122c676 

Steps to reproduce: 
1. Login to the Backend and go to Content Search Portlet.
2. If "All" option is selected on the Content Type Dropdown, click on "Add New Content" Button. This will display a list of Content Types. 
3. Select Event content type.

The Add/Edit Form will not display the "Repeats" section, where recurrence params can be edited by content editors.

<img width="1171" alt="no-recurrence" src="https://cloud.githubusercontent.com/assets/1717110/15865366/77c19222-2ca8-11e6-8d89-c1ecf400d0e3.png">

However, if "ALL" option is selected on the Content Search Portlet, and you select "Event" Content Type, THEN click on "Add New Content", the "repeats" section and recurrence params will be available 

<img width="1174" alt="with-recurrence" src="https://cloud.githubusercontent.com/assets/1717110/15865402/94c79b5a-2ca8-11e6-9505-cb38dc046978.png">

Same happens if you go to the Calendar Event Portlet and click on "Add Event" button. 

The behavior is inconsistent, and it's caused by [this JS function](https://github.com/dotCMS/core/blob/master-3.6/dotCMS/html/portlet/ext/contentlet/view_contentlets_js_inc.jsp#L707-L738). Once the Event Content Type is selected on the Content Type dialog box on Step 2, there's no way to see if the selected Structure Inode belongs to the Calendar Event.

**Comment by joseorsini** [comment]
This problem is still present on master-4.0. Additionally, if we try to edit the Event through the Calendar portlet, the Description field is never rendered, and some errors in JS console are logged.

<img width="1424" alt="screen shot 2017-03-20 at 10 26 27 am" src="https://cloud.githubusercontent.com/assets/1717110/24104117/bf986270-0d57-11e7-9e97-7faecc2813f7.png">
<img width="1543" alt="screen shot 2017-03-20 at 10 25 00 am" src="https://cloud.githubusercontent.com/assets/1717110/24104118/bf998a6a-0d57-11e7-975e-59153f772146.png">

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11083/

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11202

**Comment by bryanboza** [comment]
Fixed, tested on mater-4.1 // H2 // FF
