### ISSUE TITLE
Add support for multi-language Files to WebDAV 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9186]

**Comment by wezell** [comment]
So if this is configed for legacy webdav pathing
/autopub/dotcms.com/images/my-image.jpg

If this is not configured, the defualt will look like
/live/dotcms.com/1/images/my-image.jpg

**Comment by dsilvam** [comment]
property name: WEBDAV_LEGACY_PATHING, defaults to false

**Comment by wezell** [comment]
Decided to path to these this way
`/live/1/dotcms.com/images/my-image.jpg` 

and the connect endpoint is 

`/webdav/live/1`

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9276

**Comment by erickgonzalez** [comment]
Already tested the following scenarios with cyberduck: 

- **ADMIN/LIVE & ADMIN/NONPUB**: create, download, edit, delete, rename, duplicate, move folder and files.

- **LIMITED USER/WORKING & LIMITED USER/AUTOPUB**: create folder  and create, download, edit, delete, rename, duplicate, move files.

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/editing-with-webdav
Documented: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav

**Comment by dsilvam** [comment]
@DeanGonzalez : Doc looks nice!. We also need to include this property: 
WEBDAV_LEGACY_PATHING, defaults to false, which controls if we use old pathing (autopub/nonpush) or new one

**Comment by shaydotcms** [comment]
Passed QA. Tested actions below:

- Create Folder
- Delete Folder
- Delete File
- Rename Folder
- Rename File
- Move Folder
- Move File
- Duplicate Folder
- Duplicate File
- Upload File and Edit File still need work. Issue created #9334

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
