### ISSUE TITLE
Cannot unlock contentlet.

### ISSUE THREAD

**Issue by austindlawless** [dotCMS/core#9191]
As a non-admin, it is quite the pain to track down an admin or the user that holds the lock on a contentlet to unlock it. Even waiting for the [Timed Unlocking of Contentlet plugin](https://dotcms.com/plugins/timed-unlocking-of-content) to unlock the content is not efficient. It would be great if the ability for non-admins to steal locks was configurable.

**Comment by jtesser** [comment]
as an idea we can create a config of roles or define a role that can do this which can be assigned to a user w/o being an admin

**Comment by austindlawless** [comment]
For non-contentlets (template, containers, links...) anybody that can access it can steal the lock, right? Why have contentlets behave differently?
