### ISSUE TITLE
Ajax re-ordering issue 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9196]
Related to #5119 

We are having some issues after reorder some related content and save it, when you open the content again the system is not saving changes 

**Testing info:**
Relationship Name is SupportVideo-SupportVideoDescriptionBulletPoint

Parent Content Type is Support Video

Child Content Type is Support Video Description Bullet Point 
Cardinality is M-N

Parent Required is No 
and Child Required is No

Here the SC: http://www.youtube.com/watch?v=jVMgttcFlIA 

Tested on master-3.5 // Postgres // FF

**Comment by DeanGonzalez** [comment]
I think this issue was fixed a while ago.
