### ISSUE TITLE
Throw exception if FileUtil.copy fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9197]
Right now, we catch and eat exceptions in the FileUtil that we use to copy files across versions and into bundles etc.  We have seen installations have 0 byte files in bundles and are not sure why that has happened.  I think it would be good to puke this error up the stack and have to deal with it

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9199

**Comment by dsilvam** [comment]
From conversation with product owner and stakeholders:
FileUtils.copyFile method will be modified so: 

- _if_ src file=empty && ALLOW_ EMPTY_FILES=true
_then_ maintain current behavior except with a warn log with the path to the empty file (no stack trace, you can do that in a debug)

- _if_ src file=empty && ALLOW_ EMPTY_FILES=false _then_ log a warn with the path to the file (no stack trace, you can do that in a debug)
if it is not a language file or a metaData/content file then throw exception

Also need to remove the zero-byte files from the starter

**Comment by nollymar** [comment]
Pull Request (enterprise-2.x): [https://github.com/dotCMS/enterprise-2.x/pull/376](url)

**Comment by nollymar** [comment]
PR for tests: https://github.com/dotCMS/core/pull/9259

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/file-configuration
