### ISSUE TITLE
Add automated tests to functionality in #9162

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9198]
- [x] **1. ContentletAPITest - checkin_newFileAsset_languageDifferentThanDefault**: Create (persist) a new content of type FileAsset (See ContentDataGen) in a language different than default language. Verify that the new content was checked in (findContentByIdentifier providing identifier and langId can be used for this check)

- [x] **2. ContentAPITest - checkin_newVersionOfFileAsset_languageDifferentThanDefault**: Create (persist) a new content type of type FileAsset (See ContentDataGen) in default language, then checkout previous created content and checkin in a new language different than default language. Verify that the new version of the content was checked in (findContentByIdentifier providing identifier and langId can be used for this check)

- [x] **3. SpeedyAssetServletITest - service_fileAsset_languageDifferentThanDefault**: Create (persist)  a new content of type FileAsset (See ContentDataGen) in a language different than default language. Send a request to the servlet for the file in the language used  to create it and check the expected data is returned. 

- [x] **4. BinaryExporterServletITest - doGet_fileAsset_languageDifferentThanDefault**: Create (persist)  a new content of type FileAsset (See ContentDataGen) in a language different than default language. Send a _get_ request to the servlet for the file in the language used to create it and check the expected data is returned. 

- [x] **5. FileAssetFTest - request_fileAsset_languageDifferentThanDefault**: Create (persist)  a new content of type FileAsset (See ContentDataGen) in a language different than default language. Request the resource using its resource link (e.g. /application/themes/quest/footer.vtl) providing the language used to create it and check the expected data is returned. 

- [x] **6. FileAssetFTest - request_fileAsset_nonExistingLanguageVersion_defaultFilesToDefaultLanguageFalse**: Create (persist) a new content type of type FileAsset (See ContentDataGen) in default language.
Set property DEFAULT_FILE_TO_DEFAULT_LANGUAGE to _false_ (inside the test code). Request the resource using its resource link (e.g. /application/themes/quest/footer.vtl) providing a language different than the default and check for 404. 

- [x] **7. FileAssetFTest - request_fileAsset_nonExistingLanguageVersion_defaultFilesToDefaultLanguageTrue**: Create (persist) a new content type of type FileAsset (See ContentDataGen) in default language.
Set property DEFAULT_FILE_TO_DEFAULT_LANGUAGE to _true_ (inside the test code). Request the resource using its resource link (e.g. /application/themes/quest/footer.vtl) providing a language different than the default and check that the file in the default language is returned.

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9215
