### ISSUE TITLE
Implement new H2 Disk Cache

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9200]
H2 works well mostly but when it craps out, it brings down the whole system.  It would be nice to have an H2 cache impl that

- Can throttle logging to prevent logs from filling up
- Can self heal in case of errors
- Can provide stats
- Can measure on the size of objects
- Is sharded properly

### Config Params and Defaults

- `cache.h22.number.of.dbs` (defaults 2) the number of separate h2 databases to create
- `cache.h22.number.of.tables.per.db` (defaults 9) the number of tables to shard cache entrys across
- `cache.h22.limit.one.error.log.per.milliseconds` (defaults 5000 or 5 secs) throttle error logs to 1 every x seconds
- `cache.h22.recover.after.errors` (defaults 5000 or recover after 5000 errors) after 5000 db errors, throw away the current db and create a new one
- `cache.h22.recover.if.restarted.in.milliseconds` (defaults 30m in millis) if the dotcms is stopped and restared within this time period, reuse and reconnect to the existing h2 databases 
- `cache.h22.db.poolsize.max` (defaults 500 h2 connections per db) the Hikari connection pool size to each of the databases
- `cache.h22.db.connection.timeout` (defaults 1000 or 1 sec) the connection timeout when trying to retrieve a connection
- `cache.h22.db.leak.detection.timeout` (defaults 0 or off)  This will throw a stack trace if a connection lives longer than the value here.  Anything lower than 10000 will be ignored
- `cache.h22.db.extra.params` (defaults ;DB_CLOSE_ON_EXIT=FALSE) These are passed to H2 when creating the databases.  You can do things like turn on native db compression here.
- `cache.h22.rebuild.on.removeAll` (defaults false)  This configures cache behavior on a flushAll event.  If set to true, new h2 databases will be created, if set to false, then the cache will truncate each table separately.
- `cache.h22.rebuild.on.removeAll.failure.threshhold` (defaults to 1)
This specifies if a flushAll fails this number of times, throw away the current h2 db and recreate them on the next flushAll.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9210

**Comment by john-thomas-dotcms** [comment]
Documented: http://auth.dotcms.com/docs/latest/h22-cache-provider
