### ISSUE TITLE
Errors while creating past snapshot in Time Machine

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9203]
When you create a past snapshot in Time Machine, some errors are showing in catalina.out and dotcms.log files
https://gist.github.com/shaydotcms/da92ac500d7332d5cfeacbc3d3a7c948

Reproduced locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 

Steps to reproduce:
1-Login to dotcms
2-Navigate to Site Browser> Time Machine
3-Select Past Snapshot
4-Click Settings button and configure as below

![image](https://cloud.githubusercontent.com/assets/8741846/15972811/bd3b09d0-2efd-11e6-8151-9ee7e087c535.png)

5-Hit Save and Run Now button
6-Monitor catalina.out and dotcms.log files

**Comment by dsilvam** [comment]
Errors in dotcms.log were fixed in the starter. See https://github.com/dotCMS/core/issues/7559#issuecomment-216880851

**Comment by nollymar** [comment]
This error only occurs when testing Time Machine in a clean environment (recreate database and clean server assets/dotsecure)
 Seems to be a problem with the parsing xml library used for load bundles.

**Comment by wezell** [comment]
FWIW, the time machine is a very good way to test the front end of dotCMS and while some of these errors can be ignored (left side field assignment type stuff) some of the errors are valuable.  Whenever we make changes to velocity or macros or add new view tools, the time machine and its static output should be a goto test tool.
