### ISSUE TITLE
Lock Role: A role can still be added to Folders after the role is locked

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#9205]
After you lock a role, you are (correctly) prevented from adding the locked role to any content, including adding the role to a folder from the `Site Browser` tab.  However you can still add the role to a folder from the `Roles & Tabs` tab.

Steps to Reproduce:
1. Open the `Roles & Tabs` screen.
2. Select a role.
3. Right-click the role and select `Lock Role`.
4. Click `OK` in the confirmation popup.
**Result (_Expected_)**: The lock icon appears next to the role.
5. Select the role again.
6. Select the `Permissions` tab.
7. Select a folder in the `Add Site/Folder` dropdown.
8. Click the `Add` button.
9. Click the `Edit` checkbox on the new folder.
10. Click the `Apply Changes` button.
**Result (_Not Expected_)**: The folder permissions are added to the role.

As a contrast, the following steps correctly prevent adding permissions:
1. Lock a role (steps 1-4 above).
2. Open the Site Browser.
3. Right-click on a folder and select `Edit Folder`.
4. Select the `Permissions` tab.
5. Click the 'Permission Individually` button.
6. Select the locked role in the `Add Role` dropdown.
7. Press the `Add Role` button.

**Result (_Expected_)**: A popup appears with the message "Role cannot be added to permissions because it is locked."

**Comment by bryanboza** [comment]
Able to recreate in the last master-3.6
