### ISSUE TITLE
VersionableFactoryImpl.findLiveVersion always hits db

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9209]
We have 2 methods in our VersionableFactoryImpl that always result in expensive db hits:

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/business/VersionableFactoryImpl.java#L66

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/business/VersionableFactoryImpl.java#L66

These are used in a number of performance sensitive places in our code base and can result in excessive db load when starting from a cold cache.  I noticed this issue flushing cache during a performance test and got a number of DB connection pool exhausted messages in my logs.

This will most probably affect large installations with thousands (hundreds of thousands)  of pages that share templates and containers.

**Comment by dsilvam** [comment]
Initial work here: https://github.com/dotCMS/core/commit/4b779455270b29d787cbd2481e3d5930e308be79

**Comment by wezell** [comment]
This is a critical component. Needs an Integration Test as well.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10099
