### ISSUE TITLE
Error in Log when you create a new version of an existing file in a different language

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9216]
Steps to reproduce:

1. In the root or inside a folder, add a new file asset (image, document, picture, etc). Select English from the language dropdown
2. Click Save/Publish
3. Now right click over the image you just added and hit "Edit"
4. Select another language (ES, FR, etc) from the dropdown 
5. Click Yes on the confirmation pop up
![image](https://cloud.githubusercontent.com/assets/8741846/16083558/a6946590-32d2-11e6-9c99-602a48180db6.png)

6. You will see the error below in the dotcms.log: 

_ERROR model.KeyValueFieldUtil: Trying to parse JSON content for cached Metadata, it is required first to search the data into the cache._

This apparently does not affect the functionality but it is worth checking it out

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox 
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome

**Comment by wezell** [comment]
Non-priority, can reopen if needed
