### ISSUE TITLE
Problem moving a folder with Legacy Files inside

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#9218]
We have a problem with our logic/code when a user tries to Cut/Paste(Move) a folder that has Legacy Files. This is our current logic:
1. Moving a folder also involves [copy legacy files.](https://github.com/dotCMS/core/blob/e7d2c8ff359cdafca9c29d11810237f6833f61da/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L665-L667)
2. When copying a legacy file it tries to [find old/original folder.](https://github.com/dotCMS/core/blob/7c66441fae08e04da36e8aa39a1e9d5c34397920/src/com/dotmarketing/portlets/files/business/FileFactoryImpl.java#L830-L831)
3. [But the identifier's parent path already changed.](https://github.com/dotCMS/core/blob/e7d2c8ff359cdafca9c29d11810237f6833f61da/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L657-L659)
4. [Trying to find the folder with the original path that no longer exists.](https://github.com/dotCMS/core/blob/e7d2c8ff359cdafca9c29d11810237f6833f61da/src/com/dotmarketing/portlets/folders/business/FolderFactoryImpl.java#L231-L237) 
5. [The folder returned from Hibernate Utils is not null, just empty, so we end in this exception all the time.](https://github.com/dotCMS/core/blob/335cf48ed6cb2c98e0e95b050d949e099e2090a8/src/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java#L140-L142)

I checked on the Link's current logic and we tried to implement a fix but we didn't attack the real problem, [we just hide it and move along](https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/links/factories/LinkFactory.java#L441-L447).

**Comment by oarrietadotcms** [comment]
Reported by this Cloud client: https://my.dotcms.com/tickets/detail.dot?id=b6d46829-53d8-4ccf-af62-52b68a05f7c0

**Comment by oarrietadotcms** [comment]
hotfix: https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-9218_v3.3

**Comment by jgambarios** [comment]
@oarrietadotcms this was tested by the client?, should be include that fix to master?

**Comment by oarrietadotcms** [comment]
@jgambarios seems like it worked for the client.

**Comment by wezell** [comment]
Legacy files are no longer supported as of 4.0.0
