### ISSUE TITLE
Opening in Preview a text file asset does not respect language

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9220]
Maybe happening because the file reference is handled by identifier and not by inode.

Steps to reproduce:
1. Go to Site Browser> Add New button> Image or File
2. Select File Asset and add a text file in default language (English)
3. Hit Save / Publish
4. Now right click over the text file you just added and hit "Edit"
5. Select another language (ES) from the dropdown
6. Click Yes on the confirmation pop up
7. Edit the text file in both languages so you can see the difference in both files, e.g.:
**English**: This is a test in English
**Spanish**: Esta es una prueba en Espanol
8. Save the changes
9. Save / Publish
10. Now right click> Open (Preview)
11. You will see that only the text in the default language (EN) is displayed
![open preview](https://cloud.githubusercontent.com/assets/8741846/16097579/b6876022-330b-11e6-985d-f5f6578b2374.gif)

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9350

**Comment by shaydotcms** [comment]
Passed QA. Preview now is showing text file content depending on the language
Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome
