### ISSUE TITLE
Upgrade Tasks - Task03525LowerTagsTagname fails when removing upper case characters generates duplicated tag names

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#9228]
Task03525LowerTagsTagname should handle duplicated tag names generated by removing upper case characters.

Stacktrace:
https://gist.github.com/dsilvam/a33d470505f5a18baad7bc83f24c4953

**Comment by dsilvam** [comment]
Suggested approach is having the task remove duplicate tags; i.e. tags with same lower(name), host_id combination, prior to do the lowering of the tags' names.

So, task would need to:
- Determine the tags to keep
- Determine the tags to delete
- Update the tag_inode entries referencing the inodes of the tags to be removed by replacing then with the inodes of the tags to keep
- Remove the duplicate tags 
- Lowering case tags' names. (what the task currently does) 

For example, given: 

'tag_inode' table

| tag_id | inode 
| ------ | ----------- 
| 2 | a |
| 2 | b |
| 3 | a |
| 4 | b |
| 5 | c |

'tag' table

| tag_id | tag_name | host_id | ''
| ------ | ----------- | ---- | ---- |
| 1   | myTag | 1  | <-- will be kept
| 2 | MYTAG | 1 | <-- will be deleted
| 3    | mytaG | 1 | <-- will be deleted
| 4    | anotherTAG | 1 | <-- will be kept
| 5    | ANOTHERtag | 1 | <-- will be removed


task needs to leave the tables like this (before executing the lowering case on the tagname)

'tag_inode' table

| tag_id | inode 
| ------ | ----------- 
| 1 | a |
| 1 | b |
| 1 | a |
| 4 | b |
| 4 | c |

'tag' table

| tag_id | tag_name | host_id 
| ------ | ----------- | ---- | 
| 1   | myTag | 1  | 
| 4    | anotherTAG | 1

**Comment by wezell** [comment]
It also might make sense from a performance perspective to drop/add any foreign key constraints before doing the work and then added them back after the work is done.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9409

Tested locally with mysql and postgres.

QA could test with MSSQL and Oracle to complete all the DB's

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9435
