### ISSUE TITLE
Timemachine and Multilingual Files

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9232]

**Comment by erickgonzalez** [comment]
Steps Tested:

1. Upload image with English and Spanish versions.
2. Create a widget that shows the images.
3. Create HTML page and add the widget (both languages).
4. Check that the pages show up in both languages and shows the right image.
5. Took a time machine snapshot (both languages).
6. Modify the images from step 1(apply greyscale).
7. Check the changes in the images in front-end.
8. Go to the time machine, select the snapshots created. Should show the images in color.
9. Create a content-type with a date and time field (indexed) and assign it as publish date field.
10. Create a content of that content-type.
11. Check that the content isn't showing in front-end.
12. Go to Time Machine, select the Future option and select a date after than the one set in the content created, should be showing.
