### ISSUE TITLE
Unable to edit text file when it’s created as multilingual file

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9236]
When you have a text file and want to create a multilingual version of it, you cannot edit it until you save it and reopen it again. Maybe related to #4849 

Steps to reproduce:
1. Go to Site Browser> Add New button> Image or File
2. Select File Asset and add a text file in default language (English)
3. Hit "Edit text" button next to Resource Link
4. You will see that you cannot edit it until you save it and reopen it again.

<img width="287" alt="edit text" src="https://cloud.githubusercontent.com/assets/8741846/16156294/cc77caa0-3470-11e6-9f39-6864bef42868.png">

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome

**Comment by dsilvam** [comment]
Neither @shaydotcms nor I could reproduce, closing it.
