### ISSUE TITLE
Vanity URL documentation error

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9238]
The documentation states that “if you set the Redirect To: field of a Vanity URL to a full URL (e.g. http://dotcms.com/docs/latest/table-of-contents), dotCMS will perform a 301 redirect.” This is wrong because dotCMS always do a 302 redirect.

**Comment by Nard-Dog** [comment]
Can the code be updated to do a 301 instead of a 302? 301's are more SEO friendly
