### ISSUE TITLE
Dropdowns in Rules portlet are not collapsed properly

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9244]
When you click exactly on the dropdown arrows, you can have the actionlets, conditionlets, comparators, etc, all displayed at the same time. The normal behavior would be that only one dropdown at a time is displayed.

Steps to reproduce:
1. Login to dotcms
2. Navigate to Marketing> Rules
3. Choose an existing rule or create a new one
4. Click exactly on the dropdown arrow of each actionlets, conditionlets, comparators section

![image](https://cloud.githubusercontent.com/assets/8741846/16233202/c7b008e4-378a-11e6-87c3-b992186f2eb1.png)

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome

**Comment by wezell** [comment]
Good find though non-priority, can reopen if needed.
