### ISSUE TITLE
Workflows: Add list of Content Types a workflow is assigned to

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#9245]
When viewing a workflow, there is currently no way to find out which Content Types have been assigned to the workflow without opening and checking the properties of each Content Type, or performing a query against the dotCMS database.

It would be helpful to have, in the workflow management screen, a list of all workflows which have had the workflow assigned to them (ideally with links so you can click through to each Content Type).

**Comment by wezell** [comment]
fwiw, this information is in Elasticsearch waiting to be used :)

**Comment by john-thomas-dotcms** [comment]
Yeah, agreed.  It takes a bit of work to put a query together for it though (I'm familiar with ES, but I'd have to take some time to work that out).  It would just be nice if getting this info didn't take work and brain space (lazy, I know, but that's the whole idea behind making things easier :-) ).
