### ISSUE TITLE
Error in logs when param defaults to all in Translation Workflow

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9247]
Related to #9037 
When you add the Translate Content sub-action, it is needed to manually type in “all” as a language param to get the translation of all languages, otherwise the system will throw an error:
https://gist.github.com/shaydotcms/3d95ee2a63d2ee8d42ae8e4cc522e5a4
<img width="325" alt="5f00c4d9-3115-4729-b0dc-da8e7fa986f2" src="https://cloud.githubusercontent.com/assets/8741846/16245471/4a1f1562-37be-11e6-9b0d-ab98f62e419f.png">

Steps to reproduce
1. Login to Dotcms
2. Generate and upload the jar "plugin-dotcms-actionlet-google-translate-0.1.jar"
<img width="1144" alt="8cc03584-b89c-4a6c-a19a-f12c0c1dc55a" src="https://cloud.githubusercontent.com/assets/8741846/16245386/d1a27822-37bd-11e6-8a58-5a41a7e12559.png">
3. Now navigate to Content Types> Workflow Schemes
4. Click on Default Scheme
5. Inside Initial State, create a new Workflow Action “Translation_test" and hit Save
6. Now Add the Sub-action “Translate Content" such as below and hit Save
<img width="924" alt="986dc94a-e319-425b-8b79-2ecdfdfb4556" src="https://cloud.githubusercontent.com/assets/8741846/16245395/db60290e-37bd-11e6-9043-6afd68d45177.png">
7. Now add Generic Content and hit “Translation_test”
<img width="595" alt="0a465b18-e72d-46e4-a1ee-c51cd16cc5b1" src="https://cloud.githubusercontent.com/assets/8741846/16245402/e5b0bd9c-37bd-11e6-8342-976f4222153c.png">
8. The expected behavior is that you shouldn’t have to  type in “all” as a language param to get the translation of all languages
<img width="481" alt="6034755d-f483-4b2d-8b06-2b6c85fce4b4" src="https://cloud.githubusercontent.com/assets/8741846/16245406/eae4ca7e-37bd-11e6-8582-d9b8dc94a631.png">

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by dsilvam** [comment]
Removed the "(defaults to all)" from the "Translate to" param, since it brings confusion.

**Comment by dsilvam** [comment]
Fix: https://github.com/dotCMS/plugin-dotcms-actionlet-google-translate/commit/6c74d281cd8e2eb5ee0abaaa3902a7f884d30ec8

**Comment by shaydotcms** [comment]
Passed QA. Fix is working as expected
Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
