### ISSUE TITLE
Change Table Name of Container table 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9251]
This needs to happen because it is a reserved word in the later versions of Oracle 12.1.. c

1. Need to alter hibernate
2. Starter
3. All SQL references Fix and Maintenance Tasks 
4. Junk like this https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/containers/action/ViewContainersAction.java#L75

----
- Rename to "dot_containers"
- We also need an startup task for when moving from prior versions

**Comment by wezell** [comment]
Container.java  : 63
ViewContainerAction.java : 75
WebAssetFactory.java 83   ?
ContainerFactory : all over

**Comment by brentgriffin** [comment]
https://oracle-base.com/articles/12c/multitenant-startup-and-shutdown-cdb-and-pdb-12cr1

**Comment by jtesser** [comment]
https://docs.oracle.com/database/121/NEWFT/chapter12102.htm#NEWFT507

**Comment by nollymar** [comment]
Pull request: https://github.com/dotCMS/core/pull/9339

**Comment by shaydotcms** [comment]
Passed QA.
Upgrade from old dotcms version (dotcms_3.3) to dotcms_3.6 using H2, MySQL, MSSQL Server and Oracle is working properly; and containers table name changed to dot_containers.
