### ISSUE TITLE
JSPs using prototype methods

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9255]
The dashboard portlet does not work in 3.6.  It renders an empty screen.  Seems to be trying to use prototype.

**Comment by wezell** [comment]
![screen shot 2016-06-23 at 9 57 54 am](https://cloud.githubusercontent.com/assets/934364/16305755/2da5a808-3929-11e6-9146-15b73817dd6b.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9256

**Comment by oarrietadotcms** [comment]
Passed QA. Tested in Chrome, Firefox, Safari. Mac OSx
