### ISSUE TITLE
Reindex is not working when you manually update the number of replicas

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9263]
When set the property AUTOWIRE_MANAGE_ES_REPLICAS=false and run a reindex, the reindexation process is not completed and there’s no errors in the logs.

Steps to reproduce:
1. Modify the file dotcms-config-cluster.properties located in .../tomcat8/webapps/ROOT/WEB-INF/classes
2. Uncomment and set AUTOWIRE_MANAGE_ES_REPLICAS=false
3. Save the file
4. Startup dotcms instance
5. Login to dotcms
6. Navigate to System> Maintenance> Index
7. Right Click over the existing indexes and click Update Number of Replicas on each index (i.e.: number of replicas = 2)
<img width="548" alt="f405f1fa-222c-45b3-bbd3-7021c0c539a5" src="https://cloud.githubusercontent.com/assets/8741846/16318617/2bc7a04e-394d-11e6-8576-16bde6b53d9e.png">
8. Click Reindex button
9. Result: the reindexation process is not completed and there’s no errors in the logs

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by dsilvam** [comment]
Check if this works in 3.5 and it is a problem caused by 3.6 changes

**Comment by shaydotcms** [comment]
Passed QA. Reindexation process is completed and number of replicas is now updated accordingly. Transactions are logged in dotcms.log

![image](https://cloud.githubusercontent.com/assets/8741846/17105641/57b489e0-5245-11e6-9bda-a0882738faa1.png)

master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
