### ISSUE TITLE
Include validation for "Translate to" param to avoid incorrect values

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9265]
Related to #9037 
"Translate to” param should only allow values matching language codes already configured in dotcms. Currently it takes any alphanumeric values.

Steps to reproduce:
1. Login to Dotcms
2. Generate and upload the jar "plugin-dotcms-actionlet-google-translate-0.1.jar"
<img width="1144" alt="8cc03584-b89c-4a6c-a19a-f12c0c1dc55a" src="https://cloud.githubusercontent.com/assets/8741846/16341294/a1654ddc-39e9-11e6-8650-27afe558cad7.png">
3. Now navigate to Content Types> Workflow Schemes
4. Click on Default Scheme
5. Inside Initial State, create a new Workflow Action “Translation_test" and hit Save
6. Now Add the Sub-action “Translate Content" such as below and hit Save
<img width="924" alt="986dc94a-e319-425b-8b79-2ecdfdfb4556" src="https://cloud.githubusercontent.com/assets/8741846/16341312/b5db27d2-39e9-11e6-9016-8c2167c2e40a.png">
7. Click Translate Content sub-action and add some incorrect data in Translate to (i.e.: 1234) and hit Save
<img width="475" alt="84445ce8-b2b2-423c-9769-f809f1c4ba2c" src="https://cloud.githubusercontent.com/assets/8741846/16341317/bbbc3150-39e9-11e6-8a34-34ecbb6100f8.png">
8. Expected behavior: "Translate to” param should only allow values matching language codes (es, fr, de, etc.) already configured in dotcms

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by dsilvam** [comment]
This is a deeper issue, it applies to any actionlet that takes parameters. We would need a way to provide and enforce validations to actionlet's parameters
