### ISSUE TITLE
Translation Workflow does not create new page version in other language(s)

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9278]
Related to #9037 
If the Translation Workflow Action is configured to translated text fields, this workflow should create a new page version in other language(s) from the original page.

Steps to reproduce:
1. Generate the jar file "plugin-dotcms-actionlet-google-translate-0.1.jar”
2. Login to Dotcms and upload the jar file in Dynamic Plugins portlet:
<img width="1144" alt="8cc03584-b89c-4a6c-a19a-f12c0c1dc55a" src="https://cloud.githubusercontent.com/assets/8741846/16423719/68d27e7a-3d1a-11e6-8060-2feea2687bc7.png">
3. Now navigate to Content Types> Workflow Schemes
4. Click on Default Scheme
5. Inside Initial State, create a new Workflow Action “Translation_test" and hit Save
6. Now Add the Sub-action “Translate Content" such as below and hit Save:
<img width="924" alt="986dc94a-e319-425b-8b79-2ecdfdfb4556" src="https://cloud.githubusercontent.com/assets/8741846/16423728/7153e1a6-3d1a-11e6-95ec-1d3fd25c662a.png">
7. Click Translate Content to verify it’s set to translate text fields:
<img width="475" alt="5e168ed7-7dc9-43c1-836b-e357ec671440" src="https://cloud.githubusercontent.com/assets/8741846/16423735/76d470be-3d1a-11e6-8d99-e933c0a6eb14.png">
8. Create a new test Page Asset
9. Execute Translation_test workflow:
<img width="261" alt="1f7ac944-822d-41b7-a668-42e0eec7c33c" src="https://cloud.githubusercontent.com/assets/8741846/16423748/81849e58-3d1a-11e6-9ad6-59ee29c36b38.png">
10. Currently you will get a “null” message in the logs:
ERROR ajax.ContentletAjax: null
Complete stacktrace: https://gist.github.com/shaydotcms/8a01eaff98d41ab83d5386ae4cb9a122
<img width="324" alt="4b402fee-c6f5-4b0f-9879-39120479bfe8" src="https://cloud.githubusercontent.com/assets/8741846/16423757/89bf2d5e-3d1a-11e6-9d30-64ad75d307d8.png">

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by dsilvam** [comment]
Fixed here: https://github.com/dotCMS/core/issues/9262

**Comment by shaydotcms** [comment]
Passed QA. Translation Workflow creates new page version in language(s) available in dotcms
Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
