### ISSUE TITLE
Translation Workflow should not translate file names

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9279]
Related to #9037
When you create a File Asset and upload a file such as a txt file, this workflow is translating the **txt file name** to another language(s) which is a wrong behavior, because it should translate only the **file title but not the file name**
This could be happening because the txt file name is a text field as well as the txt title. Perhaps need to create a way to exclude file asset’s name out of the translation.

Steps to reproduce:
1. Generate the jar file "plugin-dotcms-actionlet-google-translate-0.1.jar”
2. Login to Dotcms and upload the jar file in Dynamic Plugins portlet:
<img width="1144" alt="8cc03584-b89c-4a6c-a19a-f12c0c1dc55a" src="https://cloud.githubusercontent.com/assets/8741846/16424699/7cd5f2a4-3d1e-11e6-8b63-c664ea243cb7.png">
3. Now navigate to Content Types> Workflow Schemes
4. Click on Default Scheme
5. Inside Initial State, create a new Workflow Action “Translation_test" and hit Save
6. Now Add the Sub-action “Translate Content" such as below and hit Save:
<img width="924" alt="986dc94a-e319-425b-8b79-2ecdfdfb4556" src="https://cloud.githubusercontent.com/assets/8741846/16424739/a8bd8a1c-3d1e-11e6-8bf7-9cca8bfbcf91.png">
7. Click Translate Content to verify it’s set to translate text fields:
<img width="475" alt="5e168ed7-7dc9-43c1-836b-e357ec671440" src="https://cloud.githubusercontent.com/assets/8741846/16424748/afec6740-3d1e-11e6-811c-656a50502d58.png">
8. Create a new File Asset and upload a txt file
9. Navigate to Content> Content Search.
10. Look for the file asset you just created and execute Translation_test workflow:
<img width="261" alt="1f7ac944-822d-41b7-a668-42e0eec7c33c" src="https://cloud.githubusercontent.com/assets/8741846/16424757/b6428af2-3d1e-11e6-9894-77e8e665eb53.png">
11. You will see the file asset name (as well as the file asset title) is translated to other languages:
<img width="674" alt="1cf9eb90-32b6-436b-824b-c01bdfdba4c1" src="https://cloud.githubusercontent.com/assets/8741846/16424760/bb763f00-3d1e-11e6-9e89-480946ba7531.png">
12. New Resource Links of translated file assets return a 404 error:
http://localhost:8080/archivo+de+prueba+en+diferentes+languages.txt?language_id=2
http://localhost:8080/Fichier+de+test+dans+languages.txt+diff%C3%A9rent?language_id=3

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by dsilvam** [comment]
Fixed here: https://github.com/dotCMS/core/issues/9262

**Comment by shaydotcms** [comment]
Passed QA. Translation Workflow is not translating file names, only fields specified in Translate Field Types (text, texarea, etc).
Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
