### ISSUE TITLE
What's changed feature isn't working 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9281]
We are having problems when you try to use the What's changed feature, this because the system is trowing an exception message when you click in this option... And is not showing the changes on the page... 

```RequestError: Unable to load /html/portlet/ext/htmlpages/view_live_working_diff.jsp?id=acc08d37-a23b-4f2a-9e52-0dd9fd9c68f2 status: 500```

Tested on master-3.6 // MySQL // FF 

FYI: To test this, remember this is a ee feature.

**Comment by nollymar** [comment]
The problem was a broken version of ee-3.6-SNAPSHOT.jar

**Comment by shaydotcms** [comment]
Passed QA. Error in logs has been resolved.
master-3.6 // MySQL // FF
