### ISSUE TITLE
UI: Create new NG2 site selector control

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9283]
This would be for the new ui.  We need to reuse our ContentAPI to provide auto-suggest functionality.

![siteselector](https://cloud.githubusercontent.com/assets/923947/17106540/f9ffd65c-5248-11e6-8e78-7d845ffcd168.png)

Example of the component concept:
```
<md-select ... events class="custom">
  <md-option value="xxx">Host 1</md-option>
  <md-option value="xxx">Host 2</md-option>
</md-select>
```

Related to: https://github.com/dotCMS/core/issues/9431

**Comment by fmontes** [comment]
This component should extend/use the selector component from the task: https://github.com/dotCMS/core/issues/9431

**Comment by bryanboza** [comment]
Pending changes on #9630 and #9716
