### ISSUE TITLE
Backend: Notifications manager using websockets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9284]
We need to rebuild the notifications window in angular 2.

**Comment by jgambarios** [comment]
The new notifications manager will work with websockets (**angular2-websocket**).
Related to https://github.com/dotCMS/core/issues/7819

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9375

**Comment by jcastro-dotcms** [comment]
@bryanboza please let me know when you're testing this issue in order to provide you the test scripts you need.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9379

**Comment by jcastro-dotcms** [comment]
@bryanboza please let me know when you start QA'ing this. I have some test scripts that will let you test this improvement.

**Comment by jcastro-dotcms** [comment]
Replacing the old Notifications logic with new approach will be handled by this ticket: https://github.com/dotCMS/core/issues/9380

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9379
