### ISSUE TITLE
UI: Create "Add" "+" button in NG2 chrome

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9286]
The add button should work as the current "Add New Content" works inside the Content Search.

![image](https://cloud.githubusercontent.com/assets/923947/16585528/90858548-427e-11e6-8aa3-d3e9a07348e1.png)

**Comment by freddyucv** [comment]
![screen shot 2016-09-07 at 1 46 50 pm](https://cloud.githubusercontent.com/assets/10408015/18326161/7a40edba-7512-11e6-951d-da05214a59af.png)

**Comment by wezell** [comment]
@freddyucv need to discuss this

**Comment by fmontes** [comment]
@wezell I just had a meeting with @fishsmith I'm meeting with @freddyucv to explain and I'll be working in the details of the UI asap.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/9778
PR: https://github.com/dotCMS/core-web/pull/188

**Comment by bryanboza** [comment]
New improvements reported on #9798 and #9801
