### ISSUE TITLE
UI: Create Login As functionality in NG2

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9287]

**Comment by jtesser** [comment]
![dotcms-new-ui-edit-content-2](https://cloud.githubusercontent.com/assets/1486445/16492079/7160abee-3eae-11e6-8959-80b03f1cb23e.png)

This is the my account which is the person icon

**Comment by jgambarios** [comment]
As reference this is the current UI:
![admin](https://cloud.githubusercontent.com/assets/923947/17065813/2205f176-5001-11e6-8d51-fd99e0099200.png)

**Comment by fmontes** [comment]
First part: https://github.com/dotCMS/core-web/pull/174

**Comment by jgambarios** [comment]
Backend related PR: https://github.com/dotCMS/core/pull/9696

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/179

**Comment by bryanboza** [comment]
New bug created, needs work
