### ISSUE TITLE
Push Publishing: Bundle sent to multiple environments does not work properly

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9289]
Reproduced locally in 3.5 using Starter Data, Java 8 + Postgres DB. 
Reported by client: https://my.dotcms.com/tickets/detail.dot?id=0880716b-17b7-409e-a759-f7dd025f040f 

Steps to Reproduce: 

1. Set up the following Push Publishing scenario.
  - 1 Authoring/Sender Environment (let's call it AUTH-CMS).
  - 2 Receiver Environments.
    - 1 2-node Cluster Environment (we can call it QA-CLUSTER). Add Two Cluster nodes to the Same Environment and enable "Push to Only One Server.".
    - 1 Standalone Environment (PROD-CMS).

2. First Push: Added to Bundle-001 and Pushed to All Environments (QA-CLUSTER and PROD-CMS)
```
Content in AUTH-CMS:
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: fbae12d3-5655-4c6d-8930-98d8c545d0b9
 - Mod Date: 6/29/2016 - 10:55AM

 Results:

 Content in QA-CLUSTER:
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: fbae12d3-5655-4c6d-8930-98d8c545d0b9
 - Mod Date: 6/29/2016 - 10:55AM

 Content in PROD-CMS:
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: fbae12d3-5655-4c6d-8930-98d8c545d0b9
 - Mod Date: 6/29/2016 - 10:55AM
```
3. Edited same Content, Added to Bundle-002 and Pushed to QA-CLUSTER ONLY

```
Content in Auth:
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: 183860a9-ef39-45d9-b9e4-962feffb75f1
 - Mod Date: 6/29/2016 - 10:59AM

Results:

 Content in QA-CLUSTER  (SUCCESS):
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: 183860a9-ef39-45d9-b9e4-962feffb75f1
 - Mod Date: 6/29/2016 - 10:59AM

 Content in PROD-CMS (NOTHING WAS UPDATED):
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: fbae12d3-5655-4c6d-8930-98d8c545d0b9
 - Mod Date: 6/29/2016 - 10:55AM
``` 

4. Added same content edited in Step 2 to Bundle-003 and Pushed Same Content to ALL ENVIRONMENTS

``` 
Content in Auth:
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: 183860a9-ef39-45d9-b9e4-962feffb75f1
 - Mod Date: 6/29/2016 - 10:59AM

Results:

 Content in QA-CLUSTER  (SUCCESS):
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: 183860a9-ef39-45d9-b9e4-962feffb75f1
 - Mod Date: 6/29/2016 - 10:59AM

 Content in PROD-CMS (NOTHING WAS UPDATED):
 - Identifier: 0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a
 - Inode: fbae12d3-5655-4c6d-8930-98d8c545d0b9
 - Mod Date: 6/29/2016 - 10:55AM
``` 

As you can see, the last step does not update the content in PROD-CMS environment, despite this Environment was selected on the Push Publishing Task. 

We performed the same steps but we individually pushed the content instead of adding it to a bundle (see https://gist.github.com/joseorsini/9670a659508cdc2b6af186fd82875a55#file-tests-3-5-20160629-using-rightclick-push for more details) and results were consistent. In these tests, contents were updated on the selected environments, so it has to be a problem when we generate the bundle for each environment.

**Comment by joseorsini** [comment]
Bundles that were pushed on these tests are located here 
https://drive.google.com/open?id=0B48uh-u7fegRaGVESWFFcFRIbk0

If you uncompress the bundle-001 and bundle-002 files, you'll find an XML file for content with identifier "0c1c174c-0b7f-4a52-8aea-ca2cdbfb913a". Same XML file cannot be found on bundle-003.

**Comment by wezell** [comment]
@joseorsini great job hunting this down!

**Comment by joseorsini** [comment]
Verifying if the Asset has been modified or not against an Environment (as per the Pushed Assets History) might overlap previous checks of the same asset on other environments. As per testings on client and reproducible case:

Asset has been modified in Auth, so it has to be pushed to both Prod-CMS and QA-Cluster, However, pushed assets history will return that it hasn't been modified if it's compared against QA-Cluster's Pushed Assets history, so if it was verified against Prod-CMS before, this new check will overlap the previous validation, therefore the asset is never added to a bundle. 

Proposed fix:
If it's been determined that an asset has been modified, add it to a bundle and broadcast it to the Environments list.

**Comment by joseorsini** [comment]
Discussed fix with @dsilvam. Sent proposed fix and waiting for review.

**Comment by nollymar** [comment]
Pull request: https://github.com/dotCMS/core/pull/9441
