### ISSUE TITLE
Multilang files - WebDAV - Better exception handling and mods

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9290]
As discussed with Erick and Jonathan, 

1. Remove logger.error from stripMapping and add Logger.error to the empty caches in the callers in this form:
Logger.error( this, “Error happened with uri: [” + uri if not null +“]”, e);

2. Add doc to stripMapping indicating that if it finds a languageId in the URI it will set it
3. Change stripMapping to public
4. Remove setLanguage and update callers to use stripMapping instead

**Comment by dsilvam** [comment]
@erickgonzalez also please remove the new property (WEBDAV_LEGACY_PATHING) from the dotmarketing-properties since that is what the default is for, to avoid having the properties file growing

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9301
