### ISSUE TITLE
Need to save file twice to trigger exception

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9292]
Related to #9197
In order to prevent the generation of empty metaData/content file, the system should trigger an exception if CONTENT_ALLOW_ZERO_LENGTH_FILES=false. Currently, the first time the file is saved, there’s not exception in the logs. You need to **save the file twice** to trigger the exception.

Steps to reproduce:
1. Login to dotcms
2. Upload a .txt file which size is than 0
3. Open the .txt file and edit the content. Delete all data so the size now is 0
Before:
![image](https://cloud.githubusercontent.com/assets/8741846/16464875/686ced3c-3df9-11e6-884e-0672cb83dfb0.png)
After:
![image](https://cloud.githubusercontent.com/assets/8741846/16464879/713a5e04-3df9-11e6-93c8-3f0d65c76d8b.png)
4. Hit Save or Save/Publish
5. You will see the file was successfully saved containing 0 bytes
6. You need to hit Save or Save/Publish twice to trigger the exception:
![image](https://cloud.githubusercontent.com/assets/8741846/16464916/91c090bc-3df9-11e6-9d33-62c5bce2304d.png)

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Chrome

**Comment by dsilvam** [comment]
For this to also throw the exception we need to include the validations in #9197 in the moveFile method as well

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9331. Tested with the property set to true, so files with 0 bytes upload without throwing the exception.

**Comment by DeanGonzalez** [comment]
I believe this is already documented here: http://auth.dotcms.com/docs/latest/file-configuration - but let me know if there is something I am missing

**Comment by shaydotcms** [comment]
Passed QA. Exception is being triggered the first time
Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
