### ISSUE TITLE
Create User Authentication End Point

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9297]
Setup for new NG login HTML Page

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9357

**Comment by bryanboza** [comment]
We need keep the language after change it and login, and then logout 
New Login: http://screencast.com/t/dMqsDVOheu
Old Login: http://screencast.com/t/uORYN1bOgU

Tested on master-3.7 // h2 // FF

**Comment by bryanboza** [comment]
Still having the same problems with the language...

**Comment by jgambarios** [comment]
We have new rest services for the login and logout we need to document.

**Comment by bryanboza** [comment]
Some improvements in the #9387....
