### ISSUE TITLE
Create New NG2 HTML Login Page

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9298]

**Comment by fishsmith** [comment]
Layout for the login screen. I will recreate it in Sketch and pass that along to Freddy.

General Idea: 
- Community gets the message about upgrading to Enterrpise and the dotCMS logo. 
- Enterprise customers get the their logo from the configuration screen and background image/color from the configuration screen as well.

![dotcms-new-ui-login](https://cloud.githubusercontent.com/assets/1561349/16495674/7c884df2-3ebc-11e6-8977-90cd132cef76.png)

**Comment by bryanboza** [comment]
FYI: QA will run this test plan to validate this card: http://qa.dotcms.com/index.php?/runs/view/697

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/147

**Comment by jgambarios** [comment]
UI Improvements: https://github.com/dotCMS/core-web/pull/149

**Comment by bryanboza** [comment]
Some pending changes in the #9387
