### ISSUE TITLE
Site Browser javascript issue on NG Iframe Component

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#9299]
In the NG iframe component, the Site Browser portlet have issues when you try to add a page, a file or multiple files.

Issues:
1) if you do right click on a folder and try to add a image/file or multiple files, the javascript is refreshing the whole page not just the iframe

2) if you do right click on a folder and add a page,  then create the page and finally click Admin Screen button. After you are returned to site browser screen, the right click menu options begins to work in an odd way, for example, try to add something and its going to try to open in another browser tab the new folder, page, etc throwing a javascript error

This issue is related to https://github.com/dotCMS/core/issues/9168

**Comment by bryanboza** [comment]
Also we are having a JS error if you try to open any folder with double-click, to expand any folder you need do it from the left panel... 

Here the error: 
``` Uncaught TypeError: Cannot set property 'className' of null```

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/9925

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF

**Comment by bryanboza** [comment]
This is working on FF, but not in chrome ....

**Comment by oswaldogallango** [comment]
Bryan, I tested on Firefox, Safari and Chrome. On all those servers it's working for me. Did you clean your browser cache?

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 / H2 // FF
