### ISSUE TITLE
WebDAV - Multilang files - Create new versions 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9302]
WebDAV User should be able to upload different files with the same path and name on different sessions with different languages. 

For instance:

-Start session in english. Upload file /test/myimage.png
-Start session in spanish. Upload file /test/myimage.png (this would create a new version of the fileasset created in the previous step in the new language. It is currently alerting that the file already exists)

**Comment by wezell** [comment]
@dsilvam this is correct

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9324

**Comment by DeanGonzalez** [comment]
Additional doc added to cover the updating aspect of multilingual folder connections: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav#Multilingual

**Comment by shaydotcms** [comment]
Still needs work. 
Using Cyberduck when you upload first a file in English and then the version in the other language(ES), it does create the 2 versions of the file, but when you upload first the version in the other language (ES) and then the version in English, it seems that it's not finding the identifier:  https://gist.github.com/shaydotcms/82b0dc0ad4fd8ca2cabcf9939c5450d8

**Comment by dsilvam** [comment]
Second PR: https://github.com/dotCMS/core/pull/9337

**Comment by shaydotcms** [comment]
Passed QA. New version of multilingual files are created
Tested locally in:
master-3.6 // Ubuntu 14.04.1 // MySQL 5.5.43 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
