### ISSUE TITLE
Fix webdav tests 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9303]
After merging changes in #9186, the integration tests for webdav broke
https://cb.dotcms.com/view/master-3.6/job/Git_Master_JUnit_Runner_Postgres_3.6_exec/lastCompletedBuild/testReport/

We need to fix either the cause of the issue if real, or update the tests to work with the new changes.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9305
