### ISSUE TITLE
dotCMS rejects valid email addresses for users

### ISSUE THREAD

**Issue by cmaessen** [dotCMS/core#9308]
If you create a user with an email address that looks like this:

> O'Connell@dotcms.com

DotCMS will display the error message that this isn't a valid email address. This is caused by the ' character in the email address. But according to RFCs for email this is a valid character for the local part of an email address.

See the following Wikipedia page for a summary of valid characters:
https://en.wikipedia.org/wiki/Email_address#Local_part

**Comment by cmaessen** [comment]
I now also noticed that the last name field doesn't accept single quotes in names like O'Connell. It then shows the error "Last Name not valid".

**Comment by dsilvam** [comment]
First Name/Last Name accepted characters was addressed here: https://github.com/dotCMS/core/issues/8750

Leaving this one open for the email address validation

**Comment by erickgonzalez** [comment]
Client with the issue of single quote in the email address https://my.dotcms.com/tickets/detail.dot?id=1f5d9efb-728a-40aa-8030-cb0f0db6c85f

There is two places where this needs to be changed: https://github.com/dotCMS/core/blob/master-3.6/dotCMS/html/portlet/ext/useradmin/view_users_js_inc.jsp#L419 and https://github.com/dotCMS/core/blob/master-3.6/src/com/liferay/util/Validator.java#L224

Also as an enhancement create a property, as the one for the username, to validate this.

**Comment by davwil00** [comment]
In 4.1.1, When you use the My Account feature, apostrophes are not allowed in the email address field and the error message that appears shows as "{0} is an invalid E-mail Address."

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core-web/pull/443
