### ISSUE TITLE
Unable to open Ajax portlets on NG Iframe Component

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9310]
Personas portlet is a hidden tab, but if you add this tab to any role, then refresh the page and try to open this portlet, the system is leave the page in blank... The same thing with the ES Search portlet

Tested with the normal UI and works as expected... 

Tested on master-3.7 // Postgres // Chrome

**Comment by jdotcms** [comment]
Note: @maurizo has been touching these services.

**Comment by oswaldogallango** [comment]
PR https://github.com/dotCMS/core-web/pull/202 and https://github.com/dotCMS/core/pull/9875

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/224 fixing issue after routing change

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF... Now these portlets are loading normally...
