### ISSUE TITLE
JS error in the Dynamic Plugins portlet on NG Iframe Component

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9311]
We are having a JS error when you try to open the dynamic plugins using the  NG Iframe Component, the portlet is opening normally but shows this error on console 

Here the error: http://screencast.com/t/G3afKLgY18
FYI: No errors on log...

Tested on master-3.7 // Postgres // Chrome

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10061
