### ISSUE TITLE
com.dotcms.spring is not working on master-3.6

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#9314]
If you install the OSGi plugin for com.dotcms.spring and hit the examples URL in the readme, we got a 500 error page.

Maybe the web.xml changes broke something?

**Comment by nollymar** [comment]
Pull request: https://github.com/dotCMS/core/pull/9352

**Comment by nollymar** [comment]
The issue was related to changes on this task https://github.com/dotCMS/core/issues/8780

When felix init delay was configured, the context bundle for HttpService was never set
