### ISSUE TITLE
Uploading empty file using WebDAV should trigger exception

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9317]
Related to #9197
There should be an exception in the logs when you try to upload a 0 bytes file using WebDAV and the property CONTENT_ALLOW_ZERO_LENGTH_FILES=false. Currently the file is uploaded successfully and you can also edit an empty file without problems from WebDAV.

Steps to reproduce:
1. Connect to dotcms using Webdav(Finder or Cyberduck). Follow this documentation to set up the connection property: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav#MacOS
2. Use Finder to upload an empty file to dotcms
3. You will see there’s no exception in the logs and the file is uploaded successfully

Tested locally with Finder and Cyberduck in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9331. Tested with the property set to true, so files with 0 bytes upload without throwing the exception.

**Comment by DeanGonzalez** [comment]
Added to webdav documentation: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav#EmptyFiles

**Comment by shaydotcms** [comment]
Related to bug #9334
