### ISSUE TITLE
Unzip core-web code to a proper location

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9319]
Right now new Angular shell coming from core-web is being unzipped inside **dotCMS/html/js/_rulesengine**.

We need to move that code into a better location:
**dotCMS/html/ng**

**Comment by jgambarios** [comment]
New path for the angular shell: **http://localhost:8080/html/ng/index.html**

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9327

**Comment by bryanboza** [comment]
Fixed, tested with master-3.7 // MySQL // FF...
