### ISSUE TITLE
UI: Rebuild Notifications window in NG2

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9322]
We need to rebuild the notifications window in angular 2.

The new notifications manager will work with websockets (**angular2-websocket**).
Related to https://github.com/dotCMS/core/issues/9284 and https://github.com/dotCMS/core/issues/7819

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/146

**Comment by bryanboza** [comment]
Some UI improvements on #9397
