### ISSUE TITLE
JWT interaction with CURL and from the backend

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9323]
- [ ] Need to be able to get a token that can be used from CURL.

We don't need to implement it as this example does ( https://github.com/jpadilla/django-jwt-auth#usage ) but could be a good reference of how at least in concept should work.
- [ ] We want to be able to request a web token from the back end and to specify for how long the token should live.

**We need to documents all the previous cases.**

**Comment by bryanboza** [comment]
After talk with @jdotcms... This token always is created, this property is just to make the auto login or not...

**Comment by jgambarios** [comment]
Should we restrict the creation/request of web tokens to the Admin role?.

**Comment by jdotcms** [comment]
This won't affect the AutologinFilter, but will affect the WebResource authentication instead.

Basically will add a new method to do authentication using webtoken on the WebResource.

**Comment by bryanboza** [comment]
Fixed, tested via curl commands... Tested on master-3.7

**Comment by bryanboza** [comment]
Some new issues created
