### ISSUE TITLE
UI: reorder css styles

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#9329]
We have rules-engine css styling that is leaking into angular-material components, we have to encapsulate those to only affect rules-engine component.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/144

**Comment by jgambarios** [comment]
Another PR: https://github.com/dotCMS/core-web/pull/145

**Comment by bryanboza** [comment]
Fixed... Some pending things to define
