### ISSUE TITLE
Captcha can be programmatically reused by passing session id

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9330]
If you use a captcha protected resource like the sendEmailServlet you can pass the same captcha again and again via curl if you use the session id cookie of the original request.

Once the captcha has been checked and validated, we need to remove it from the user's session programmatically.

**Comment by oarrietadotcms** [comment]
Flowdock thread: https://www.flowdock.com/app/dotcms/dev-team-rex/threads/gA5EzBUfoNLLM5y8vOYMxwidTU_

The main problem here is that captcha information will be stored in session even after get/validate the value.

Steps to Reproduce:

* Create a page. ie captcha-page.
* Add a Simple Widget with this code:
```
#set($contentFormReferer = "/path/to/thanks-page")
#set($contentUseCaptcha = true)
#submitContent("webPageContent")
```
* Create another page. ie thanks-page
* Add a widget with this code:
```
$session.getAttribute("simpleCaptcha")
```

Now go to captcha-page in front end, log in and fill the form and captcha. After submit you will no longer see the captcha info in the next page.

After the fix example:
![screen shot 2016-08-09 at 11 09 42 am](https://cloud.githubusercontent.com/assets/8225685/17531259/5bdd4044-5e38-11e6-99e0-e769476b403b.png)
![screen shot 2016-08-09 at 11 10 07 am](https://cloud.githubusercontent.com/assets/8225685/17531266/60797a64-5e38-11e6-92c6-bbc031dfc160.png)

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9532
