### ISSUE TITLE
Replace ngrx with Angular Router 3.0

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#9332]
Next: https://github.com/dotCMS/core/issues/9919

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9835

**Comment by bryanboza** [comment]
Someone can add some info about this change, what should be fix?, how to test?... etc.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
