### ISSUE TITLE
Improvements on the MenuResource

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9333]
The **com.dotcms.rest.menu.MenuResource** needs to be refactored in order to use versions (concept we started with the rules engine and we are planning to continue implementing on new REST services).

Also we need to properly handle authentication and make it to return Response objects instead of just JSON in order to handle along with the content to return (JSON) also response codes.

**Comment by jdotcms** [comment]
On it

**Comment by jgambarios** [comment]
PRs:
https://github.com/dotCMS/core/pull/9376
https://github.com/dotCMS/core-web/pull/148

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // MySQL // FF

**Comment by jgambarios** [comment]
We have a new rest service (**MenuResource**) we need to document.

**Comment by john-thomas-dotcms** [comment]
Doc Updated: http://auth.dotcms.com/docs/latest/rest-api-end-points#MenuResource

Please also see Flow Thread about `{from}` in the API path: https://www.flowdock.com/app/dotcms/dev-team-cody/threads/4q-7dvxVQUEaJPohWdvn5wIAlca
