### ISSUE TITLE
Errors uploading files with WebDAV Finder using legacy and new path

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9334]
When you try to upload a file (png, txt, pdf, etc) using either the legacy (/webdav/autopub or nonpub) or new path (/webdav/live or working/1), the first time you get this error:
<img width="399" alt="ed69e50e-3b1b-473a-a325-e55e4f1ef5ce" src="https://cloud.githubusercontent.com/assets/8741846/16658114/5a646f06-4422-11e6-8e3e-eafa52ef2d25.png">
and the second time you try to upload the same file again, you get this error:
<img width="403" alt="19c12dd8-3416-4282-8e4c-ffdbf585f9d3" src="https://cloud.githubusercontent.com/assets/8741846/16658117/5c6c4800-4422-11e6-8549-ee9d48234e60.png">

The files being uploaded are **not empty files**.

Steps to reproduce
1. Connect to dotcms using Webdav(Finder). Follow this documentation to set up the connection property: http://auth.dotcms.com/docs/latest/upload-and-edit-via-webdav#MacOS
2. Upload a file (png, txt, pdf, etc) to dotcms. The first time you do it, you will get the error code -36 and the second time you try to upload the same file, you will get the error code -43
Stacktrace for both errors: https://gist.github.com/shaydotcms/efdf7d90f5433c213f9885e53c8ea5d0
3. This issue is not happening with **Cyberduck**

Tested locally with Finder in master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9345

**Comment by shaydotcms** [comment]
Passed QA. Result mentioned on https://github.com/dotCMS/core/issues/9343#issuecomment-232501017
