### ISSUE TITLE
SiteSearch - Disable update replicas from UI when is auto managed 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9336]
It is needed to stop showing the "Update Replicas" option from the UI (like it currently happens in the Index portlet) when the system is managing the replicas (default).

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9427

**Comment by shaydotcms** [comment]
Passed QA. "Update Replicas" option is NOT showing in the UI when the system is managing the replicas (default).
![image](https://cloud.githubusercontent.com/assets/8741846/17145628/2c9b1ce6-5318-11e6-9ff7-f2db71d9ef2e.png)

Tested in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
