### ISSUE TITLE
Make H22 cache the shipped default

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9340]
We need to update our config to use the new H22 cache vs. the legacy cache impl.

**Comment by dsilvam** [comment]
https://github.com/dotCMS/core/pull/9360

**Comment by dsilvam** [comment]
Reverting changes since they broke more than half of tests, we need to check what is going on. https://github.com/dotCMS/core/pull/9361

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9420

**Comment by oarrietadotcms** [comment]
I met with @jgambarios @dsilvam and we decided the best approach was to repackage Hikari and make sure it doesn't download slf4j-api as dependency. Instead it should use the repackage dot.slf4j-api-1.7.12_2.jar that we already provide.

Note: our repackage Tika jar still contains some packages without com.dotcms.repackage. At this moment would be dangerous to remove those packages from tika but we will discuss in the next release.

**Comment by wezell** [comment]
Makes sense, thanks Oscar!

**Comment by dotcmsCodeReview** [comment]
Are we going to try to reapply #9340 ?

**Comment by dsilvam** [comment]
yes @dotcmsCodeReview !

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9449
