### ISSUE TITLE
Permissions issues related to latest changes 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9342]
After do some testing over the permissions stuff, are having some issues: 

- After you set full permissions and apply changes, when you go to the site permissions tab, we have the "templates-layout" unchecked

![r2](https://cloud.githubusercontent.com/assets/2641437/15031004/04d2bd86-1213-11e6-81d7-1e0f4bf9eeb0.gif)

- After you go to the site properties --> Permissions, and reset the permissions stuff over the site, when you come back to the user permissions and try to apply cascade permissions again, we are loosing one by one every category.... 

![r3](https://cloud.githubusercontent.com/assets/2641437/15031302/da0d3f98-1214-11e6-831c-7d124f401fba.gif)

**Comment by jgambarios** [comment]
Related to the changes made in: https://github.com/dotCMS/core/issues/8853

**Comment by DeanGonzalez** [comment]
I tested this today and both the role application of the permissions and cascade of permissions from the host seem to be working: http://screencast.com/t/jeaW25SbgP

**Comment by DeanGonzalez** [comment]
ok, Bryan showed me how to reproduce.  If you do not click on ANY child content for the folder in the final step, then the permissions to the folder disappear.  But if you click any children, then it works.  So there is still a bug here that the cascade ends up removing the permissions to the parent object if there are not children in the folder.  Which is a bug.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9507

Upgrade Tested from 3.3 to 3.6 in MySQL and Posgres. QA can test Oracle and MS SQL to complete the DB set.

**Comment by shaydotcms** [comment]
Fix is working.
1st scenario: Templates-layout remains checked after you set full permissions and apply changes
2nd scenario: clicking "cascade changes” doesn’t end up removing the permissions

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3 // Chrome
master-3.6 // Mac OS 10.10 // Oracle 12c // Firefox

**Comment by dsilvam** [comment]
@oarrietadotcms great fix!
