### ISSUE TITLE
fix tests where empty files are created 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9343]
Insert some bytes to the files created in these test to not fail the emptyFile validation: 

* com.dotmarketing.portlets.contentlet.business.ContentletAPITest.newFileAssetLanguageDifferentThanDefault	
* com.dotmarketing.portlets.contentlet.business.ContentletAPITest.newVersionFileAssetLanguageDifferentThanDefault	
* com.dotcms.rest.ContentResourceTest.uriFileImageFields	
 com.dotmarketing.portlets.folder.business.FolderAPITest.copy	
* com.dotmarketing.portlets.contentlet.business.FileAssetTest.fileAssetNonExistingLanguageDefaultFilesFalse	
* com.dotmarketing.portlets.contentlet.business.FileAssetTest.fileAssetLanguageDifferentThanDefault	
* com.dotmarketing.portlets.contentlet.business.FileAssetTest.fileAssetNonExistingLanguageDefaultFilesTrue

**Comment by DeanGonzalez** [comment]
tested uploading empty files in english and spanish, and other assorted files, editing files, creating folders - finder is working

**Comment by shaydotcms** [comment]
This test refers to #9334
