### ISSUE TITLE
UI Styleguide

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#9348]
This should be done after: https://github.com/dotCMS/core/issues/9346 and https://github.com/dotCMS/core/issues/9347

Create a page where developers can go to check all the components, elements and layout.

Every new component should be add it to this page.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/162

**Comment by jgambarios** [comment]
For now the style guide is under: **Home > Pattern Library**

**Comment by bryanboza** [comment]
Fixed, looks good for now

**Comment by bryanboza** [comment]
FYI: We need move to another Path, now is under Home/ Pattern Library

**Comment by john-thomas-dotcms** [comment]
Preliminary doc done for this, but we're not far enough along to really fill this out.

Doc isn't even published on auth yet, but can be found on the auth backend via http://auth.dotcms.com/c/portal/layout?p_l_id=71b8a1ca-37b6-4b6e-a43b-c7482f28db6c&p_p_id=EXT_11&p_p_action=1&p_p_state=maximized&p_p_mode=view&_EXT_11_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_EXT_11_cmd=edit&inode=077badf3-7f8e-431c-88e8-dd066c81f7c3&referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3D71b8a1ca-37b6-4b6e-a43b-c7482f28db6c%26p_p_id%3DEXT_11%26p_p_action%3D1%26p_p_state%3Dmaximized%26_EXT_11_struts_action%3D%2Fext%2Fcontentlet%2Fview_contentlets
