### ISSUE TITLE
Calendar portlet does not respects the workflow schema set to events

### ISSUE THREAD

**Issue by maurizo** [dotCMS/core#9356]
The buttons on the event description window does not comply with a workflow schema assigned to the event content type.  It shows _"copy","edit","publish/re-publish/unpublish","archive/delete"_ actions that are wired to the event API through the CalendarAjax.  The window should follow the same workflow step assigned to the event as in the event edit page.

Reported in https://my.dotcms.com/tickets/detail.dot?id=d0fa36f6-bd33-4bfc-9ca6-62e23983c491.

**Comment by dsilvam** [comment]
@maurizo pointed out this was reproduced in 3.3.2 but that also fails in 3.5
