### ISSUE TITLE
Modify Task03550RenameContainersTable to check if table was already renamed

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9366]
Since we are including this task in 3.5.1, we need to check in the 3.6 version of this task if the table was already renamed (or if table containers does not exist), which would be the case when a client on >=3.5.1 is upgrading to 3.6. This is to determine whether this needs to run or not.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9417

**Comment by shaydotcms** [comment]
Passed QA.
Tested dotcms_3.5.1 using H2,  MySQL, MSSQL Server and Oracle; all is working properly. Added some assets, languages, etc and performed upgrade to dotcms_3.6 without issues
