### ISSUE TITLE
Back end: Create the NG2 forgot password fuctionality

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9367]
As we have in the old login page, we need be able to recover password 

If you go to forgot password you need write your email and the system should be able to send your password via email... 

FYI: Here the the SMTP configuration

```
<Resource name="mail/MailSession"
                  auth="Container"
                  type="javax.mail.Session"
                  mail.debug="true"
                  mail.transport.protocol="smtp"
                  mail.smtp.host="smtp.gmail.com"
                  mail.smtp.auth="true"
                  mail.smtp.port="587"
                  mail.smtp.starttls.enable="true"
                  mail.from=""
                  mail.user=""
                  mail.password=""
                  username=""
              password=""  />
```

Related to: https://github.com/dotCMS/core/issues/9370

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9426

**Comment by jgambarios** [comment]
@john-thomas-dotcms for this ticket we need to document how can the user change the email template used by the email send in the change password functionality.
