### ISSUE TITLE
Log info from the NG2 Login 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9368]
Related to #9298 

Need add info to the log files from this page...

If you try to do a failed login we need add this attempt to the dotcms-security.log file, as we do in the old login page... 

Also if you leave the user or password field in balk, the system is showing a exception in the dotcms.log, maybe we need handle this exception and show a better message 

Here the log: https://gist.github.com/bryanboza/d86ac6e5fdaff20bf08796b7e0a79f68

Tested on master-3.7 // MySQL // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9386

**Comment by bryanboza** [comment]
After the last changes, now we are adding log info in the dotcms.log in case of bad request, but not in the dotcms-security.log, tested with the old UI and works as expected....

**Comment by bryanboza** [comment]
Now we are sending the info to the dotcms-security.log, but when you login this info is going to the dotcms.log.... We need move this to the security log....

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61950
