### ISSUE TITLE
UI: Create the NG2 forgot password fuctionality

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9370]
As we have in the old login page, we need be able to recover password.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core-web/pull/156
https://github.com/dotCMS/core/pull/9497

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // ff... New improvements on the #9529

**Comment by bryanboza** [comment]
Test cases: http://qa.dotcms.com/index.php?/suites/view/1

**Comment by john-thomas-dotcms** [comment]
Translated: PR https://github.com/dotCMS/core/pull/9780
