### ISSUE TITLE
Adding same name file in multiple languages thru webdav is failing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9377]
We must have changed something recently in 3.6 that broke this.  Brokent in finder and Cyberduck

error in finder: http://screencast.com/t/38q4bXCg8

error in Cyberduck: http://screencast.com/t/DnsTSHXyLQjs

To recreate, establish a webdav connection in both english and spanish and then drop the same file in both webdav connections, in the same folder.  Dropping the file the second time will fail, stating that it can't read the file.

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9388

**Comment by DeanGonzalez** [comment]
Shay - I already tested this in Finder - working well now

**Comment by shaydotcms** [comment]
Great. Thanks
