### ISSUE TITLE
UI problems with the login portlet after logout 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9381]
Related to #9298 

We are having UI problems after login in the new NG2 login portlet and then logout, the system is unable to load the login again 

Here the SC: 
![sc1](https://cloud.githubusercontent.com/assets/2641437/16967978/3b46b5e2-4dc9-11e6-8d55-cbfe709f4a33.png)

We are having this error on console:
``` "NetworkError: 500 Internal Server Error - http://localhost:8080/api/v1/loginform" ```

Tested on master-3.7 // H2 // FF

**Comment by oswaldogallango** [comment]
The error is not in the angular component it's in the loginform rest api
<img width="1176" alt="screen shot 2016-07-20 at 9 05 40 am" src="https://cloud.githubusercontent.com/assets/1569280/16987264/493e0dae-4e59-11e6-889f-ab0bbecb800b.png">

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9297

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // MySQL // FF
