### ISSUE TITLE
Integrity Checker: Wrong Data type of IR tables on SQL Server clients 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9382]
Reproduced on upgraded clients from 2.5.x to 3.3

Ticket details: 
https://my.dotcms.com/tickets/detail.dot?id=552be6cd-5756-4f3b-915b-7c8ba67471da
https://my.dotcms.com/tickets/detail.dot?id=83ce5832-ab09-43d0-9670-d0761339d465

Description: 
We have noticed that Integrity Checker does not work properly on upgraded clients running on SQL Server Databases. Even after applying the fixes on https://github.com/dotCMS/core/issues/8559 and https://github.com/dotCMS/core/issues/8586, we're still having ClassCastException messages like the following: 

```
[19/07/16 13:26:50:525 CDT] ERROR rest.IntegrityResource: Error checking integrity
java.lang.Exception: Error running the Folders Integrity Check
    at com.dotcms.integritycheckers.FolderIntegrityChecker.generateIntegrityResults(FolderIntegrityChecker.java:210) ~[dotcms_3.3_1bbd913.jar:?]
    at com.dotcms.integritycheckers.IntegrityUtil.completeCheckIntegrity(IntegrityUtil.java:559) ~[dotcms_3.3_1bbd913.jar:?]
    at com.dotcms.rest.IntegrityResource$2.run(IntegrityResource.java:332) [IntegrityResource$2.class:?]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at com.dotmarketing.common.db.DotConnect.getRecordCount(DotConnect.java:925) ~[dotcms_3.3_1bbd913.jar:?]
    at com.dotcms.integritycheckers.FolderIntegrityChecker.generateIntegrityResults(FolderIntegrityChecker.java:208) ~[dotcms_3.3_1bbd913.jar:?]
    ... 2 more 
```

After inspecting the https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/startup/runonce/Task03065AddHtmlPageIR.java task, it creates a language_id column with a datatype of numeric(19), however, on clean startups of 3.x (see https://github.com/dotCMS/core/blob/master-3.6/src-conf/mssql.sql#L2735)  it creates the same column as bigint. This difference in the datatype is causing issues for these upgraded clients. 

As a workaround, we have provided scripts to clients that will recreate the table with the right data type. An upgrade task must take care of this issue. 
## 

We inspected the https://github.com/dotCMS/core/issues/7806 ticket, where Files were added to the Integrity Checker, and it seems the issue is not affecting the fileassets_ir table.

**Comment by dsilvam** [comment]
@joseorsini it looks like this is a dup of https://github.com/dotCMS/core/issues/8559

**Comment by dsilvam** [comment]
Check this commit out: https://github.com/dotCMS/core/commit/3765057a4f09c6add3f35e9bb10484e837bbbd99

**Comment by joseorsini** [comment]
@dsilvam The issue persists even after applying the fix from that Github issue. The referenced task you mention does not fix the datatype inconsistency between the upgrade task and the startup sql scripts

**Comment by dsilvam** [comment]
@joseorsini if I understand correctly, it looks to me, that the purpose of the fix is to deal with (not to fix) the datatype inconsistency, meaning, to be prepared to successfully process the field in both cases (different data types)

**Comment by dsilvam** [comment]
This one https://my.dotcms.com/tickets/detail.dot?id=57be1aed-05d2-4677-ac28-4af71857b2fb is the original issue that lead to #8559 and it looks like by providing the code in a hotfix and applying it, it was possible to run the integrity checker without issues

**Comment by joseorsini** [comment]
Commit attempts to fix data type for fileassets_ir and htmlpages_ir tables, which are created with numeric data type, however on SQL scripts, create table scripts set language_id column as bigint.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9872
