### ISSUE TITLE
Login Form improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9387]
We still having some errors with the login form: 

- We need show the complete language name, instead the contry-code in the language field
![sc2](https://cloud.githubusercontent.com/assets/2641437/16998235/bec18562-4e75-11e6-81a4-366d0ad3effc.png)

- Now we are remembering the language after refresh the login page, but we are not keeping the value in the language filed: 
To recreate: 
                      - Go to login form
                      - Change the language filed to a Spanish
                      - Refresh the page
The system is showing the information in Spanish, but the language field is in blank
![sc3](https://cloud.githubusercontent.com/assets/2641437/16998333/31108a46-4e76-11e6-907a-17e2c11b46c8.png)

- We are having some encoding problems when you translate the page, specially in French
![sc4](https://cloud.githubusercontent.com/assets/2641437/16998351/49aa9754-4e76-11e6-808c-045dcb374067.png)

- As the old login, we need have the "@dotcms.com" by default in the user field  

- We need validate if the fields are in blank before send parameters, to avoid some fail in the jersey

Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
PRs:
https://github.com/dotCMS/core-web/pull/150
https://github.com/dotCMS/core/pull/9393

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF and Chrome and works fine, new improvements needed on Microsoft Edge...
