### ISSUE TITLE
JWT isn't working in the  NG2 Login

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9390]
If you go to the new Angular login and enable the remember-me option, when you delete all the cookies and leave the access-token, and then refresh the page, the system is redirecting to the login page again, and is not remembering your session 
To recreate: 
- Login in the new angular login (enable the remember me)
- With firebug, delete all the cookies except the access-token 
- Refresh the page 

As the old UI, we need keep the token and redirect to the home page, instead the login page again 

Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9398

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // MySQL // FF
