### ISSUE TITLE
NG2 login component move left side message to language.property

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#9394]
<img width="1364" alt="screen shot 2016-07-21 at 4 13 27 pm" src="https://cloud.githubusercontent.com/assets/1569280/17037320/4bed70e8-4f5e-11e6-8567-c234e0b2033f.png">

1) Move the left side message to the language.property file.
2) Showed only if the server has a community license
3) If the server has a valid license show the server id info

**Comment by oswaldogallango** [comment]
Jus a reminder, the new language.property needs to be translated and included for the other languages

**Comment by jgambarios** [comment]
PRs:
https://github.com/dotCMS/core-web/pull/152
https://github.com/dotCMS/core/pull/9399

**Comment by bryanboza** [comment]
Fixed, Waiting for translations....
