### ISSUE TITLE
UX: Notifications window improvements

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9397]
After the last changes in #9322 we need make some changes: 
- [ ] We need show only the last 10 notifications, this to avoid a large list of notifications 
  http://screencast.com/t/3Ws2nE9c
- [ ] Add pagination to the notification component
- [ ] Need add something to show an alert when you have new notifications, maybe a number or a red point or something like that 
- [x] After open the notification window, we need close it when you click out of the window, right now to close this window need click again to the icon  
- [ ] After you read all the notifications we need put in gray color the icon again, right now the first time appear in gray, but after you have notifications appear in white 
- [ ] Maybe we can add a clear notification button, this to clear manually the notifications
- [ ] We need add a static id to the notification button and the notification window

**Comment by fishsmith** [comment]
![screen shot 2016-07-25 at 12 32 41 pm](https://cloud.githubusercontent.com/assets/1561349/17108977/f38801ee-5263-11e6-92b8-fae0e295a2a8.png)

**Comment by fmontes** [comment]
1. We need show only the last 10 notifications, this to avoid a large list of notifications 
  - Agreed

2. Add pagination to the notification component
  - Need to design the pagination
  - Need to make the backend paginate friendly and see how to handle the new service and the events websocket

3. Need add something to show an alert when you have new notifications, maybe a number or a red point or something like that
  - Needs to design this, also maybe we can show a popup for 10 seconds to the user when he logins for the first time

4. After open the notification window, we need close it when you click out of the window, right now to close this window need click again to the icon
  - Agreed

5. After you read all the notifications we need put in gray color the icon again, right now the first time appear in gray, but after you have notifications appear in white
  - How the user will mark a notification as read? clicking in it? what about if the user read it but not click it?

6. Maybe we can add a clear notification button, this to clear manually the notifications
  - Agreed. But still needs to figure out how to mark one as read.

7. We need add a static id to the notification button and the notification window
  - Not sure what this is about

**Comment by fishsmith** [comment]
1. agree but maybe 10 is too many. 
2. What if we just load the last 5-10 and then when they dismiss/clear them we load more (so this list is always 5-10). I wonder if this would force users to maintain the list
3. In the design there is a small red box maybe this can have the number of alerts not dismissed
5. clicking the dismiss link marks it as read/cleared and removes it from the list
6. I think read and cleared are the same. (This is how Google handles it)

**Comment by fmontes** [comment]
1. agree but maybe 10 is too many.
  - No problem this is a param easy to change whenever we want.
2. What if we just load the last 5-10 and then when they dismiss/clear them we load more (so this list is always 5-10). I wonder if this would force users to maintain the list
  - Sounds good, what about if the user dismiss one, do we show one?
3. In the design there is a small red box maybe this can have the number of alerts not dismissed
  - No problem at all
4. clicking the dismiss link marks it as read/cleared and removes it from the list
  - Good
5. I think read and cleared are the same. (This is how Google handles it)
  - We can add the option

Also in the current version of notification we have notification for all users and for current logged user, are we still having that?

**Comment by fishsmith** [comment]
**original questions:**
2. we show up to X max. If a user dismisses 1 and there are additional not showing we load the 6th one into the 5th spot.

**more questions:**
2. the check was going to be a task successful (like reindex complete). The ! was going to be an alert something failed or warning .... I don't think we are going to have these, so I don't think we need any icon.

**Comment by fmontes** [comment]
<img width="686" alt="screen shot 2016-07-27 at 8 48 48 am" src="https://cloud.githubusercontent.com/assets/751424/17179604/101163c2-53d7-11e6-926a-cc4c21f70f8c.png">

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/158

**Comment by bryanboza** [comment]
Passed

**Comment by bryanboza** [comment]
http://qa.dotcms.com/index.php?/cases/view/61967
http://qa.dotcms.com/index.php?/cases/view/61968
