### ISSUE TITLE
Backend: Create Login As functionality in NG2

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9410]
Create a new rest endpoint to handle the Login As functionality, this new endpoint includes the info to populate the "Login As" component and the logic after an user is selected.

Related to: https://github.com/dotCMS/core/issues/9287

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9554

**Comment by john-thomas-dotcms** [comment]
Doc'ed as part of the REST API Endpoints doc: http://auth.dotcms.com/docs/latest/rest-api-end-points#UserResourceRules

No separate doc for now, though we might want to eventually create a doc that goes into more detail on all the REST API methods related to authentication.
