### ISSUE TITLE
We need to use a token for remember me

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9412]
Am I reading this right?  In moving to JWT, we are still using an encrypted user id as the remember me string?

https://github.com/dotCMS/core/blob/master-3.7/src/com/dotcms/cms/login/LoginServiceFactory.java#L321

I thought we were moving to a token based login.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/issues/9473

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
