### ISSUE TITLE
Backend: Create "Add" "+" button in NG2 chrome

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9413]
Related to: https://github.com/dotCMS/core/issues/9286

> The add button should work as the current "Add New Content" works inside the Content Search.

Create the rest endpoints to return the UI required data (list of Content Types) and to handle the selection of a Content Type in the new component.

# As reference: Current behaviour

![addbutton](https://cloud.githubusercontent.com/assets/923947/17415533/7aa2f13a-5a47-11e6-8a62-2bcaef680c68.png)
![addnewclick](https://cloud.githubusercontent.com/assets/923947/17415532/7a93f6da-5a47-11e6-830e-03964969f35a.png)
![alreadySelected](http://content.screencast.com/users/jgambarios/folders/Snagit/media/8815e426-acc4-498f-8f4b-e8cf15ee1da0/2016-08-04_13-22-04.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9520

**Comment by bryanboza** [comment]
Fixed, tested via postman...
