### ISSUE TITLE
Integrity Checker: Enforce Data Integrity between Integrity and Push Publish tables

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9415]
Reported on 3.3.1. 

Currently, we have the following tables that store data when Integrity Checker is run and found conflicts between environments
- fileassets_ir
- folders_ir
- htmlpages_ir
- schemes_ir
- structures_ir 

These tables have an "endpoint_id" column that should match the info stored on publishing_end_point table. However, no Foreign Key enforces data integrity between these tables, so it's advised to create them. 
## 

In regards to this support Ticket: https://my.dotcms.com/tickets/detail.dot?id=a6be2c43-879e-40be-9b5c-ff4973fe3587 there was a problem with the Integrity Checker. The IR tables had orphan information (pointing to non-existing Endpoints) and the "View Conflicts" button was displayed, despite no conflicts were found by the Integrity Checker between the sender and selected Receiver endpoint. It's worth to double-check: 
1. If IR tables have contents that match the selected Endpoint once the Integrity Checker is executed. 
2. If an Endpoint is deleted, all referenced info on IR tables should be deleted as well.

**Comment by joseorsini** [comment]
Reproduced in 3.5. Steps:

1. Create a Push Publishing scenario with 1 Sender and 1 Receiver endpoints. 
2. Go to Receiver Endpoint (let's call it PROD-CMS1) and drop the  /about-us/index page. Recreate it. 
3. Run the Integrity Checker. One issue is reported. 

```
35dist=# select * from htmlpages_ir;
    html_page    |         local_working_inode          |           local_live_inode           |         remote_working_inode         |          remote_live_inode           |           local_identifier           |          remote_identifier           |             endpoint_id              | language_id
-----------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------------
 /about-us/index | cc2cdf9c-a20d-4862-9454-2a76c1132123 | cc2cdf9c-a20d-4862-9454-2a76c1132123 | 85437fcf-e01a-4a5a-812b-c82160708d77 | 85437fcf-e01a-4a5a-812b-c82160708d77 | c12fe7e6-d338-49d5-973b-2d974d57015b | 74dc85bf-4b6e-4ff1-95b6-ffae87853b4a | 824150b0-049c-4146-b3ab-4ad60596869d |           1
(1 row)

35dist=# select * from publishing_end_point where id = '824150b0-049c-4146-b3ab-4ad60596869d';
                  id                  |               group_id               | server_name |  address  | port | protocol | enabled |   auth_key   | sending
--------------------------------------+--------------------------------------+-------------+-----------+------+----------+---------+--------------+---------
 824150b0-049c-4146-b3ab-4ad60596869d | a00f62e4-de25-4dc6-aa38-a5e4a907abac | PROD-CMS1   | 127.0.0.1 | 8081 | http     | t       | y4Y98iG9aag= | f
(1 row)
```

4. Remove the PROD-CMS1 Environment. 
5. Re-run the same queries from above: 

``` 
35dist=# select * from htmlpages_ir;
    html_page    |         local_working_inode          |           local_live_inode           |         remote_working_inode         |          remote_live_inode           |           local_identifier           |          remote_identifier           |             endpoint_id              | language_id
-----------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------------
 /about-us/index | cc2cdf9c-a20d-4862-9454-2a76c1132123 | cc2cdf9c-a20d-4862-9454-2a76c1132123 | 85437fcf-e01a-4a5a-812b-c82160708d77 | 85437fcf-e01a-4a5a-812b-c82160708d77 | c12fe7e6-d338-49d5-973b-2d974d57015b | 74dc85bf-4b6e-4ff1-95b6-ffae87853b4a | 824150b0-049c-4146-b3ab-4ad60596869d |           1
(1 row)

35dist=# select * from publishing_end_point where id = '824150b0-049c-4146-b3ab-4ad60596869d';
 id | group_id | server_name | address | port | protocol | enabled | auth_key | sending
----+----------+-------------+---------+------+----------+---------+----------+---------
(0 rows)
```

The conflict reported on the htmlpages_ir table was not deleted once the Environment was removed. This causes data consistency issues, because it needs to be dropped because the referenced Endpoint/Environment no longer exists.

**Comment by joseorsini** [comment]
Additional test: 

1. Reproduced all steps from previous test. 
2. Created a new Receiver Environment (different from the ones created previously). 
3. Configured Push Publishing and ran the Integrity Checker. 
4. The "View Conflicts" button is displayed, however, the Conflicts Tabs are empty.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9872

**Comment by joseorsini** [comment]
Committed changes requested here https://github.com/dotCMS/core/issues/9382 Please test

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9872
