### ISSUE TITLE
Wrong behavior with What’s changed feature

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9419]
If you don’t make any changes in the page and click What’s Changed, previously you got a message saying “Nothing was changed” but as of today all the page is marked in red and you get some parse errors. See image below:

![image](https://cloud.githubusercontent.com/assets/8741846/17116870/f5250cb4-5276-11e6-9936-a00e6fa3e29a.png)

Steps to reproduce:
1. Navigate to Site Browser> About-us folder> index page> right click> Open Preview
2. Click Lock for Editing. Don’t do any changes to the page
3. Click What’s Changed feature.
4. You will see all the page is marked in red and you get some parse errors in the page

Tested in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9448

While testing the fix, I found this other bug: https://github.com/dotCMS/core/issues/9447. I would be nice to fix it before 3.6

**Comment by shaydotcms** [comment]
Issue has been fixed.
Estrange behavior is gone when there are changes in the Page and also when no changes were made. Inline editing and content generic editing display the changes when it is saved (does not display the changes when you hit save/publish; this is the way this feature was implemented).
Tested in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
