### ISSUE TITLE
Back end: Events improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9430]
- [ ] Refactor the current url route for the websocket endpoint, currently is **system/events** but must be inside the **api/** path and should be using versions.
- [ ] The events should be able to be delivered to specific users and roles, currently an event is delivered to all the websocket registered clients, to accomplish this we need to be able to identify who is the user related to each registered session with the websocket in order to decide if the event should or not be delivered to that user.
- [ ] Check the current uses of the notification API in order to start using this new **user/role** delivery mechanism (most all the already existing notifications are global notifications and should not, we need to check case by case).
- [ ]  Add internationalization to all the existing notifications and from now all the notifications should be internationalized.

**Comment by jdotcms** [comment]
Refactor the current url route for the websocket endpoint, currently is system/events but must be inside the api/ path and should be using versions.
DONE
The url and package have been changed, after get merged the config resource,  the url should be updated to reflect the new path on the web-core

**Comment by jdotcms** [comment]
The system events are now able to be user or role specific.
In addition the websocket session can be identified as user logged

**Comment by jdotcms** [comment]
The threadpool has been included, in addition the websocket has been fixed to send asyn messages instead of syncr

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9472

**Comment by bryanboza** [comment]
Fixed, tested with the notifications stuff and works as expected...

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61960

**Comment by john-thomas-dotcms** [comment]
Translated: PR https://github.com/dotCMS/core/pull/9780
