### ISSUE TITLE
UI: Login Improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9436]
## Login window:
- [x] On page load the focus should be in the email/user id field
- [x] When the authentication type is email remove from the email input field the @domain - Does not makes sense having multiple sites.
- [x] Add the dotCMS version in the login window (right now is only visible after a license is applied).
- [x] The placeholder should change depending on the email or the user id

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/157

**Comment by bryanboza** [comment]
Fixed, now looks better with this improvements, tested on master-3.7 // postgres

**Comment by bryanboza** [comment]
TC: 
http://qa.dotcms.com/index.php?/cases/view/61951
http://qa.dotcms.com/index.php?/cases/view/61959
