### ISSUE TITLE
Backend: Notifications window improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9438]
We need to add the ability to:

- [ ] Mark notifications as read.
- [ ] Dismiss (Delete) notifications.
- [ ] Make sure the list with notifications returned by the Notifications Resource and the Websocket have the creation date of the Notification in order to be use by the Notifications UI.

Related to: https://github.com/dotCMS/core/issues/9397 and https://github.com/dotCMS/core/issues/9430

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9468

**Comment by jdotcms** [comment]
@bryanboza 

We have to do test for all of these classes:

- DeleteFieldJob 
- ESContentletAPIImpl 
- TimeMachineAjaxAction
- ReindexThread	 
- HostAPIImpl 	 
- HTMLPageAssetAPIImpl
- IdentifierDateJob	

All of these created notifications and have been updated to include a title and i18n messages.
Thanks,
J

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61964
http://qa.dotcms.com/index.php?/cases/view/61965
http://qa.dotcms.com/index.php?/cases/view/61970
http://qa.dotcms.com/index.php?/cases/view/61971
http://qa.dotcms.com/index.php?/cases/view/61972
