### ISSUE TITLE
Problems after the empty files validation 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9442]
We added a new validation to don't allow files < 0 bytes, this validation is generating some functional problems...

- Using Cyberduck as web-dav client, now you can't create a new file from the client, this because the system need create the file and then open to edit, and now we are not allowing create the files because is 0 bytes...
SC: http://screencast.com/t/9O0sP10kVufu
Log: https://gist.github.com/bryanboza/f417ed7413aa14e2e228e1509a2f776e

- After upgrade dotCMS from any version > 3.6, and you try to create a time machine snapshot... We are having a lot of errors on log, this because we have a lot of empty files on our site... (**This is not affecting functionality but it is logging full stacks of errors**) 

Tested on master-3.7 // Oracle // FF

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/9459

**Comment by shaydotcms** [comment]
Issue has been fixed. Files are now able to be created in Cyberduck
Tested in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
