### ISSUE TITLE
Prevent including users marked as deleteInProgress in listing/results

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9462]
This was done already for the User Portlet, so users being deleted won't show in the listing, but we need to check other places where this needs to be prevented also.

**Comment by dsilvam** [comment]
We need to add functional tests to verify the exclusion is working as expected

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9515

**Comment by nollymar** [comment]
All changes were covered by integration tests except those in DashboardFactory.
Please, consider executing a functional test for Workstream Feature in Dashboard functionality.

**Comment by shaydotcms** [comment]
Passed QA.
Removed users are not showing either in the Users portlet nor the Work-Stream in the Dashboard

![delete testuser2](https://cloud.githubusercontent.com/assets/8741846/17760918/6764c73c-64c0-11e6-8727-82b2662e02f5.gif)


Tested locally in:
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome
master-3.6 // Mac OS 10.10 // Oracle 12c // Firefox
