### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerDriver performance degradation due to sendStringParametersAsUnicode=true

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9465]
After switching from the jTDS driver to the Microsoft JDBC driver, we have introduced a significant performance penalty due to the default sendStringParametersAsUnicode=true parameter. This triggers Unicode conversion of the parameters on any prepared statements, which causes significant SQL Server CPU overhead by changing: 

`select * from tree where parent = 'b10d9308-8da5-4e38-8ae3-a35dc724b7ec' or child = 'b10d9308-8da5-4e38-8ae3-a35dc724b7ec' order by tree_order asc;`

to this:

`select * from tree where parent = N'b10d9308-8da5-4e38-8ae3-a35dc724b7ec' or child = N'b10d9308-8da5-4e38-8ae3-a35dc724b7ec' order by tree_order asc;`

which takes almost 10x longer to execute.

I have tested simply changing sendStringParametersAsUnicode=false, but this unfortunately breaks the usage of UTF-8 characters in content (Cyrillic chars are changed to only the '?' character).

**Comment by chrismccracken** [comment]
https://my.dotcms.com/tickets/detail.dot?id=d7a7428b-49a3-4611-acf3-22b72e3cfbca

**Comment by wezell** [comment]
Can you test with the latest jtds driver?  Or has that been eol-ed?

**Comment by wezell** [comment]
If not, you can put a profiler/monitor on the test instance to identify SQL
hotspots and we might be able to improve those (hand build the SQL string)
rather than prepared statements. Thinking of the tree lookup in particular.
