### ISSUE TITLE
Links: Minor Improvements for Links

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9467]
Reproduced in 3.3.2. 

Related to Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=67b4c5a1-e1d2-4f4a-a6da-5a676bf943af 

Steps to Reproduce:
1. on a dotCMS build running over a secure connection (https), create the following objects;
- 1 /test folder, marked as "Show on Menu"
- 1 Index page, Marked as "Show on Menu" and "HTTPS Required". 
- 1 Menu link, pointing to a internal Page with "HTTPS Required" property enabled.
- 1 Menu link, pointing to a internal Page with "HTTPS Required" property disabled.
- 1 simple widget, with the code from this Doc http://dotcms.com/docs/latest/navtool (see Example: Two level navigation)
1. Open the page in Edit and Live Mode. Inspect its code.

<img width="1319" alt="screen shot 2016-08-01 at 5 18 28 pm" src="https://cloud.githubusercontent.com/assets/1717110/17309269/0dc2dbc6-580c-11e6-90d8-487775490eb4.png">

The problem here is that, since we don't know which asset has been selected on the internal link (it can be a file or a page). [We always set http as the link protocol](https://github.com/dotCMS/core/blob/3.5.1/src/com/dotmarketing/portlets/links/action/EditLinkAction.java#L452) when an internal Link is created, regardless if the current connection is set via https. Additionally, in the NavTool code [here](https://github.com/dotCMS/core/blob/3.5.1/src/com/dotmarketing/viewtools/navigation/NavTool.java#L156-L161) we could verify if the internal link references a Page, and if so, get the HTTPS Required Attribute and add it to the HREF attribute we're sending as part of the NavResult Path.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10574

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MysQL // FF
