### ISSUE TITLE
Revert container table renaming in upgrade tasks other tan the renaming itself 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9475]
We need to revert the renaming of the containers table to dot_containers in upgrade tasks prior to Task03550RenameContainersTable, which is pretty much any at this moment. 

Task affected: 
Task00765AddUserForeignKeys
Task00780UUIDTypeChange
Task00782CleanDataInconsistencies
Task00785DataModelChanges
Task00790DataModelChangesForWebAssets
Task00795LiveWorkingToIdentifier
Task00940AlterTemplateTable
Task03000CreateContainertStructures
Task03020PostgresqlIndiciesFK
Task03035FixContainerCheckTrigger
Task03120AddInodeToContainerStructure

We need to test an upgrade from a very old version like 1.9 straight to 3.6

**Comment by dsilvam** [comment]
Tested in the branch doing an upgrade from 2.5.7 (starter database) and from 2.2.0 (client's db)

**Comment by shaydotcms** [comment]
Needs work.
Trying to upgrade from 1.9.5 to 3.6 and we’re still having issues with upgrade tasks Task00795LiveWorkingToIdentifier, Task00780UUIDTypeChange and Task03525LowerTagsTagname
https://gist.github.com/shaydotcms/1af9134a59931aa0f88c49bbf8083e82

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012
master-3.6 // Mac OS 10.10 // MySQL 5.6.23
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5
master-3.6 // Mac OS 10.10 // Oracle 12c

**Comment by jtesser** [comment]
We care more about 2.x up.  We really have very few 1.9.5 people out there. And usually they goto 2.5 and then up

**Comment by shaydotcms** [comment]
Upgraded successfully from dotcms_2.5.7 to master 3.6 using Postgres 9.3.5 and Oracle 12c. 
Upgrade tasks are working properly.

**Comment by shaydotcms** [comment]
Upgrade from 2.2.0 (client's db) is working fine, so moving to Done and passed QA
