### ISSUE TITLE
Problems starting dotCMS with Jboss

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9476]
We are having some problems trying to use Jboss to start dotCMS, 
- The dot-jamm jar file that we have on the docs/jboss/modules folder is the 0.2.5_1 and in the modules .xml we are referencing to the _2...
  SC: http://screencast.com/t/ZYLiK1sW5
- The h2 driver isn't up to date and we are using a different one to start in tomcat... Then we are having this problem starting 
  Log Error: https://gist.github.com/bryanboza/c7ab38d831b8a72391c084ed83b0f685

Tested on Jboss-eap-6.4 // H2

**Comment by wezell** [comment]
We should fix the jamm jar but I think it is ok for h2 not to work as the primary DB with Jboss. If you are running on a big app server, you should not be using h2 as the db anyway.  H2 is just for evaluation purposes.  Does the h22 cache work?

**Comment by bryanboza** [comment]
Also, using postgres we are having some problems loading the old UI... Here the log: https://gist.github.com/bryanboza/c87ac12ed358708eaa6b11668c0ab75e

**Comment by nollymar** [comment]
The problems were solved for JBoss eap 7.
The documentation was updated as well, see: https://docs.google.com/a/dotcms.com/document/d/1dyGtXM1uqocsSxaVbWzPc7WDW6eAnIkjkupuWJ9HfYo/edit?usp=sharing

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/11015

**Comment by DeanGonzalez** [comment]
documented: http://auth.dotcms.com/docs/latest/deploy-as-a-war-in-jboss-eap-7
