### ISSUE TITLE
Error in getRelatedContentlets(), no column identifier.inode

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9482]
In SQL built at https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/structure/factories/RelationshipFactory.java#L524, there is a reference to identifier.inode, which does not exist.

**Comment by chrismccracken** [comment]
Re: https://my.dotcms.com/tickets/detail.dot?id=f5186af8-8ebb-4e06-a05d-139ce5e44b09

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9938
