### ISSUE TITLE
Uploading images via finder/webdav fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9491]
Nightly build 8/4/16
OSX Yosemite

Uploading I get this:
![screen shot 2016-08-04 at 11 44 53 am](https://cloud.githubusercontent.com/assets/934364/17408457/43d3ea6e-5a39-11e6-8214-3dbf0d157c1e.png)

And it results in a 1 byte file:
![screen shot 2016-08-04 at 11 46 15 am](https://cloud.githubusercontent.com/assets/934364/17408470/4d2ba3fe-5a39-11e6-8e67-5dec04790fbd.png)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9495

**Comment by shaydotcms** [comment]
Passed QA. Uploaded image using webdav/finder
Uploaded image into existing folder: no errors in logs, image size is not 1 byte, which is good
Uploaded image into root: no errors in logs, image size is not 1 byte, which is good
Uploaded image into new folder: no errors in logs, image size is not 1 byte, which is good
![image](https://cloud.githubusercontent.com/assets/8741846/17489194/2b8110da-5d5a-11e6-965f-9c0feaaa2b1c.png)

![image](https://cloud.githubusercontent.com/assets/8741846/17489200/31a41bce-5d5a-11e6-9928-526a24ece889.png)

Tested locally in:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3 // Chrome
