### ISSUE TITLE
Recover password issues 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9500]
After the changes in the card #9370 we are having the follow problems... 

- [ ] We are logging in the dotcms.log instead the dotcms-security.log 

- [x] The generated URL have some problems:
- This are not including the running port 
- Is redirecting to an https url and not include the http
- Also if you request the password change from the new UI (NG2), the system send an URL that is redirecting to the old UI, and if you do this from the old one, is redirecting to the new UI 

- [x] After you recover your password, you are unable to login with the new password, neither the old one

- [x] "Forgot Password" is misspelling

- [ ] If you try to recover password and enter a not existing email, the system should show an info message about the error... And this error should be logged in the security.log instead the dotcms.log

- [x] If you try to recover password and enter a not existing email, the system should show an info message about the error... And this error should be logged in the security.log instead the dotcms.log
Also we are showing this error on console: "NetworkError: 400 Bad Request - http://localhost:8080/api/v1/forgotpassword"

Tested on master-3.7 // postgres // ff

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9523

**Comment by bryanboza** [comment]
We still login that process in the dotcms.log, also have the same error on console when you type a no existing email 

Testing on master-3.7 // postgres // ff

**Comment by freddyucv** [comment]
This message: 

"NetworkError: 400 Bad Request - http://localhost:8080/api/v1/forgotpassword"

It is print by the angular2 framework or by the browser, it is not printed by our code

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 //  h2 // FF, now we are logging in the dotcms-security.log, Some improvements created on #9557

**Comment by bryanboza** [comment]
Test cases created here: http://qa.dotcms.com/index.php?/suites/view/1
