### ISSUE TITLE
UX: Notification problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9503]
Related to #9397 

After this changes we are having some problems with the notifications

- [x] We are unable to mark notifications as read using FF

- [x] After you open the notifications window, you can't close this on FF, (works fine on Chrome)

- [x] We need show the title of the element when the mouse is over

- [x] Add date to notification item

Tested on master-3.7 // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/160

**Comment by bryanboza** [comment]
We need some styling improvements to date in the notifications 
http://screencast.com/t/vMhVbdxyxuQG

Tested in the last master-3.7 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // ff... Now is working fine

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61973
