### ISSUE TITLE
Add internationalization to the new Notifications component

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9504]
Currently the new Notifications component does not have internationalization.
We need to add in the **src/api/services/system/app-configuration-service.ts** a method in order to get global i18 values and use it in the Notifications component.

Related to: https://github.com/dotCMS/core/issues/9397

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9526

**Comment by bryanboza** [comment]
Fixed, now we have all the internationalization, but we don't have the translation of the messages, we need retest after create those messages...

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61969

**Comment by john-thomas-dotcms** [comment]
Translated: PR https://github.com/dotCMS/core/pull/9780
