### ISSUE TITLE
Problems with the rememberme functionality after the routing changes 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9505]
When you check the rememberme checkbox, and then try to go to **localhost/html/ng**, the system is trying to remember the session id, but can't  read the property 'userId' and have some problems loading the backend 

Here the SC: 
![r1](https://cloud.githubusercontent.com/assets/2641437/17450004/2996218e-5b1b-11e6-82c7-5c03dc3c2100.gif)

Tested on master-3.7 // postgres // chrome

**Comment by bryanboza** [comment]
After this commit, now the rememberme functionality is not working... 

Tested in the last master-3.7..

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/9537
https://github.com/dotCMS/core-web/pull/163/commits

**Comment by bryanboza** [comment]
Fixed, now the remember-me is working as expected... Tested on  master-3.7 // postgres // ff
