### ISSUE TITLE
Past Time Machine does not respect File Languages

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9511]
Tested on latest 3.6 build as of Aug 6th 2016

The future time machine works fine, and shows all language versions just fine.  However, the past time machine only displays the image from one language version

See screencast: http://screencast.com/t/5OhQDI46z

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9564

**Comment by shaydotcms** [comment]
Passed QA.
Past and future time machine is respecting languages

![past and future time machine multilingual](https://cloud.githubusercontent.com/assets/8741846/17723972/7a97ce32-63fb-11e6-8e92-a4be0b6b19ca.gif)

Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
