### ISSUE TITLE
Multilingual Files do not respect language ID set in session

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9512]
Tested on latest 3.6 version

I used the suggested resize image display code from the container to display a file asset on a page:
https://gist.github.com/DeanGonzalez/6f1a35129ffdb3e3090e46c227d30010

On the backend, I switch between languages just fine and see the title and the image correctly, but on the front end, by changing the language in the session via URL, the image never changes from the default language.

Screencast: http://screencast.com/t/SWINtVke

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9538
