### ISSUE TITLE
Marking notifications as read is not working properly

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9516]
When you mark all your notifications as read, then logout and login again the notifications count shows unread notifications.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9521

**Comment by bryanboza** [comment]
After this PR, we still having the same problem after logout and login again 

Tested in the last master-3.7 // Postgres // ff

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF and now works as expected
