### ISSUE TITLE
Need to add MaxMetaSpaceSize setting for Java 8

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#9527]
Now that we require Java 8, we should include a setting for MaxMetaSpaceSize in the startup.sh  By default the MetaSpace is only limited by the amount of physical memory on a machine.  We should ship with a default value here to prevent a problem here from running servers out of memory.  If there is a problem and the MetaSpace grows too large, the failure will be much easier to diagnose than the server running out of memory, going through continual GCs, or receiving an OOM exception on a memory request from the normal heap.

Doc should mention that if customers have a significant amount of custom or plugin code that they may need to increase the default setting.

**Comment by wezell** [comment]
dupe #11942

**Comment by john-thomas-dotcms** [comment]
Added to startup.sh in this PR: https://github.com/dotCMS/core/pull/11972

Doc'ed for 4.2 here: https://auth.dotcms.com/docs/latest/performance-tuning#JVMMemory
