### ISSUE TITLE
Forgot password internationalization 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9529]
- [ ] We need add the translation to the error that we have in the recover password process
  SC: http://screencast.com/t/kxGpdxA85MU
- [ ] We need make sole styling improvements as we can see in the previous screencast...
- [ ] We need translate the success message http://screencast.com/t/1IkVw21r
- [ ] Also maybe we can show a more clear or specific messages

Tested on master-3.7 // postgres // ff

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/9565
https://github.com/dotCMS/core-web/pull/167

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61961

**Comment by john-thomas-dotcms** [comment]
Translated: PR https://github.com/dotCMS/core/pull/9780
