### ISSUE TITLE
JS error after logout

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9531]
We are having the follow error after logout in the new NG2 UI 

TypeError: document.getElementById(...) is null

SC: http://screencast.com/t/1EwGRtyga8ui

Tested on master-3.7 // postgres // FF 

FYI: This is not affecting the functionality is juts to clean the code...

**Comment by freddyucv** [comment]
This error just is printed in FF.

Also, We are having the follow error after logout in Chrome:
"Uncaught TypeError: Cannot read property 'focus' of null"

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
