### ISSUE TITLE
Restrict/Allow IP by CIDR block in Rules Engine

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#9534]
Currently the Rules Engine doesn't have an IP attribute in the request header or the ability to allow/restrict access to an object or tree by CIDR in the comparison, this would be useful for restricting access to content to in-network IPs.

**Comment by chrismccracken** [comment]
Looks like this was a work-in-progress that needs some resurrecting, https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/rules/conditionlet/UsersIpAddressConditionlet.java
