### ISSUE TITLE
Incorporate ImageIO plugins into core

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9541]
I would like to incorporate this library into dotCMS to greatly expand the # of image types we can thumbnail/resize and handle:

https://github.com/haraldk/TwelveMonkeys

**Comment by wezell** [comment]
This pull adds resize thumbnail support for

- bmp				
- jpeg			
- tiff			
- pnm				
- psd				
- iff				
- pcx				
- pict			
- tiff			
- sgi				
- tga				
- icns			
- pcx				
- thumbsdb			
- clippath

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9900

**Comment by dsilvam** [comment]
Merged into master-3.7: https://github.com/dotCMS/core/pull/10423

**Comment by DeanGonzalez** [comment]
Documented: http://auth.dotcms.com/docs/latest/image-resizing-and-processing
