### ISSUE TITLE
Cascade Changes in permissions tab generates ClassCastException in Oracle 12c

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9547]
Steps to reproduce
1-Navigate to System> Users
2-Go to permissions tab and give full permission to any children (Joe Contributor)
3-Click "Cascade Changes ?” and Apply Changes
<img width="917" alt="7485171c-aaa6-4e3b-add9-50f793d857b4" src="https://cloud.githubusercontent.com/assets/8741846/17590328/a942527a-5f96-11e6-97a3-9668fb3eee4f.png">

4-You will see the error msj in the UI:
"An unexpected system error occurred.:Unable to close Hibernate Session"
and the logs
https://gist.github.com/shaydotcms/98b117df4ee0f88880c212ed568c5c1b

5-The permissions are applied to the user, even though this error.

Tested in master-3.6 // Mac OS 10.10 // Oracle 12c

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9563

**Comment by shaydotcms** [comment]
Passed QA.
Cascade permissions not throwing errors in Oracle
Tested in master-3.6 // Mac OS 10.10 // Oracle 12c
