### ISSUE TITLE
File Type Field for Structures not Multilingual

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9550]
So see this modal

http://screencast.com/t/5VCGFOwxb6ph

The issue is this has not been converted to support multilingual. 

It should function as follows. 

1. It should default to the currently selected language
2. You should be able to select language if you want to change and link from a spanish news to english file image. 

As an internal note this has been vetted through with some of our multilingual clients

**Comment by jtesser** [comment]
Do we not store the image in a way this works?  inode?  or is it only identifier and no language?  Was hoping we could add the language to the storage if ID based. But not sure

If not then we would need to show only images for the specific language of the content and maybe the default if the fallthrough is on AND no file exists for the selected language

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9590

**Comment by dsilvam** [comment]
PR for related fix: https://github.com/dotCMS/core/pull/9599

**Comment by erickgonzalez** [comment]
The button "Upload New File" shown in the modal, uploads the file in the default language. Should be uploaded in the language selected.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9609

**Comment by shaydotcms** [comment]
Fix is working.
New image is uploaded in selected language

master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome
