### ISSUE TITLE
Error when trying to delete a new site

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#9567]
This exception is thrown when trying to delete a host: https://gist.github.com/nollymar/3d36038101a99be42765079dbfafff3d

Steps to reproduce:
* Add a new copy of an existing site (Site to copy: demo.dotcms.com)
* Give it a host name and click on Save/Activate
* Stop site
* Archive site
* Delete site

**Result**: Exception thrown and the deletion process never finish.

Tested on master-3.6/postgreSQL

**Comment by bryanboza** [comment]
I am able to reproduce using master-3.7 // Postgres // FF 
SC: http://screencast.com/t/ZpYtMGvYR

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9616

**Comment by shaydotcms** [comment]
Fix is working.
Copy an existing site from starter: it works, no exception thrown and process finishes completely.
Create a new site: no exception thrown and process finishes completely.
Added files, languages, images to existing site and copied the site: it works, no exception thrown and process finishes completely.

master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome

**Comment by dsilvam** [comment]
Great fix! @oarrietadotcms
