### ISSUE TITLE
UI: Replace alerts/confirms in the new NG2 functionality with a proper NG component

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9568]
Right now in the new forgot password functionality we have one alert and one confirm that does not look good with the new Angular UI, we need to replace those with Angular components.

The confirm is displayed when asking if the user wants to send the forgot password email and the alert is displayed when the password is successfully changed.

**Comment by freddyucv** [comment]
replace one alert that we have in my-account-component too.

**Comment by jgambarios** [comment]
Maybe we should use the growl component for this: http://www.primefaces.org/primeng/#/growl ?

**Comment by wezell** [comment]
@fishsmith thoughts?
