### ISSUE TITLE
UI: Create drop-button component

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9570]
We need to create a drop button component (similar to the Notification toolbar) where we can add inside of it any other component.

Examples of concept:
```
<md-dropdown title="Lorem" or icon="icon_name" events>
  <md-dropdown-content>
    ... ADD CONTENT
    ... NOTIFICATIONS
    ... ANYTHING
  </md-dropdown-content>
</md-dropdown>
```

This new Component will be use for the **Add New Content**, **Login As** and **Edit Profile** components.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF
