### ISSUE TITLE
UI: Create a Modal Component

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9572]
We need to create a Modal Component.

Example of concept:

```
<md-modal title="Lorem" onClose={} onCancel={} onSomething...>
  <md-modal-content>
    ... ANYTHING
  </md-modal-content>
</md-modal>
```

This new Modal Component will be use by the **Edit Profile** and **Login As** component.

**Comment by fmontes** [comment]
Angular Material 2 is working in one:

1. https://github.com/angular/material2/tree/master/src/components/dialog
2. https://github.com/angular/material2/issues/958

**Comment by jgambarios** [comment]
Closed as Prime NG have a dialog component: http://www.primefaces.org/primeng/#/dialog
