### ISSUE TITLE
UI: Create Account button UI functionality in NG2

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9573]
![dotcms-new-ui-edit-content-2](https://cloud.githubusercontent.com/assets/1486445/16492079/7160abee-3eae-11e6-8959-80b03f1cb23e.png)

This is the my account which is the person icon 

------

As reference this is the current UI:

![loginasmyaccount](https://cloud.githubusercontent.com/assets/923947/17069365/7f52653c-5013-11e6-8603-9845e1c9189a.png)

![admin](https://cloud.githubusercontent.com/assets/923947/17065813/2205f176-5001-11e6-8d51-fd99e0099200.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/178

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // ff
