### ISSUE TITLE
Validate the Login As functionality in NG2 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9580]
Component testing of the card #9410

**Comment by bryanboza** [comment]
After test this via http tool, we are having problems:

- [ ] When you login and logout as using this rest, this because we are login transactions in the dotcms.log and not in the dotcms-security.log. If you try from the old backend UI, we log this in the security log...  

- [ ] If you try to login with a wrong credentials we are showing this error on log https://gist.github.com/bryanboza/8785d5233f7c1ac14312fa0d662e6b12
- By security we can't show which field is invalid 
- We need handle this exception and just show a invalid attempt message in the security log 

Tested on master-3.7 // Postgres // HttpTool Plugin for FF

**Comment by oswaldogallango** [comment]
this is the PR https://github.com/dotCMS/core/pull/9826

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
