### ISSUE TITLE
Reindex notification problems 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9582]
We are having some problems with the notifications generated by the reindex process, the system is generating the notification, but if you logout and then login again the system is unable to load this notification, was deleted... 

Tested in multiple browsers and have the same error ...

 Tested on master-3.7 // postgres // FF

**Comment by shaydotcms** [comment]
Passed QA. 
Reindex notifications are still showing after logout and log back in
Master-4.0 / Commit 52f8ea3e3574b9e02548331ddd82b0e61c00badf
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
