### ISSUE TITLE
Enhancement: Change Labels for System Site and Global to "All Sites" for consistency

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9584]
We should improve our labeling to be more consistent with the "All Sites" search term:

1) Change the wording in the tag manager from "Show Global Tags" to "Show "All Sites" Tags"
http://screencast.com/t/gx9p8Pnve

2) Change the wording in the content search manager from "Hide System Site" to "Hide "All Sites" Content"
http://screencast.com/t/OxPIzGyN7

**Comment by nollymar** [comment]
Pull request: https://github.com/dotCMS/core/pull/9585

**Comment by shaydotcms** [comment]
Passed QA. Fix is showing consistency with "All Sites" in Content Search and Tag Manager portlets

**Comment by dsilvam** [comment]
Final work was done here: https://github.com/dotCMS/core/issues/7570. Please check
