### ISSUE TITLE
Switch to ElasticSearch REST API from TCP transport

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9589]
The ES transport protocol is being deprecated for direct client access, and is unavailable from some external ES platforms (AWS). Transport will be used only for intra-cluster sync purposes, and not as a query interface. We need to switch to using the ES REST API for all of our query and index mgmt API calls. On the latest ES code, performance between the two is now on parity (https://gist.github.com/danielmitterdorfer/2de0dfd61092eaad84958319cfc0d61b).

**Comment by wezell** [comment]
dupe: #15942
