### ISSUE TITLE
Contentlet: Binary field required issue

### ISSUE THREAD

**Issue by DannyGloudemans** [dotCMS/core#9598]
Hi,

There is an issue with binary fields that get empty after a required exception on another field. Like in the example below I tried on the demo.dotcms.com website: Create a structure with a required text field and binary field, add a binary but leave the text field empty en click on publish:

![issue1](https://cloud.githubusercontent.com/assets/2641310/17734147/a9b6d1e8-647a-11e6-9e45-ab3fe4d37a86.png)

You will get a notifications that the text field is empty, the binary is still filled. Fill in the text field en click on publish again, now you get an exception that the binary field is required, while on your screen you still see the image.

![issue2](https://cloud.githubusercontent.com/assets/2641310/17734146/a99de8c2-647a-11e6-9c0b-ac8b20b2619e.png)

I think the binary is lost after the first publish, but it's still shown on the admin interface.

Thanks

**Comment by dsilvam** [comment]
Hey @DannyGloudemans, I think this is a dup of https://github.com/dotCMS/core/issues/9082
