### ISSUE TITLE
Reset Password link contains user_id

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9601]
To reset your password please follow the link below:

https://localhost/html/ng?resetPassword=true&userId=dotcms.org.1&token=QGLjJHiyue5bGJmEmHgYtHPq2fFRI61471448634194

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9784

**Comment by bryanboza** [comment]
After you use the token, the token expire, if you try to use again we are showing a "reset_token_expired" message, this need a i18 message, to show in multiple languages... 
http://screencast.com/t/2ULMJK4kf

**Comment by jdotcms** [comment]
@john-thomas-dotcms I have included this new entry on the languages.properties
reset_token_expired=The token has expired. Please restart the "forgot password" process and try again.

Feel free to update with an accurate message.

**Comment by john-thomas-dotcms** [comment]
@jdotcms, there's already an almost identical string (`reset-password-token-expired=Token expired. Please restart the "forgot password" process and try again.`).  Do we really need a second one saying basically the same thing?

**Comment by jdotcms** [comment]
sure I can switch to it instead

**Comment by jdotcms** [comment]
the message has been changed

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9815

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
