### ISSUE TITLE
copy site does not copy files

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9604]
If got so site portlet, select add site, choose copy + templates/containers + folders + files, the files do not copy.

![screen shot 2016-08-17 at 9 13 17 pm](https://cloud.githubusercontent.com/assets/934364/17758683/789a27b4-64bf-11e6-937c-c41accecc890.png)

**Comment by oarrietadotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/9620
ee core: https://github.com/dotCMS/enterprise-2.x/pull/383

**Comment by shaydotcms** [comment]
Passed QA. 
Files are getting copied when you do a copy of an existing site + templates/containers + folders + files
![image](https://cloud.githubusercontent.com/assets/8741846/17916962/2a6ee006-6975-11e6-9711-f74d0a3a91a9.png)

master-3.6 // Mac OS 10.10 // MySQL 5.6.23
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5
