### ISSUE TITLE
csv icon missing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9607]
Now that the /icon servlet is unmapped.  This results in some broken images:

![screen shot 2016-08-18 at 2 41 38 pm](https://cloud.githubusercontent.com/assets/934364/17786408/b0420bda-6552-11e6-8e66-493b7c0a06e7.png)

For example, this does not work:
http://demo.dotcms.com/icon?i=.csv

**Comment by wezell** [comment]
Here too:

![screen shot 2016-08-18 at 2 48 47 pm](https://cloud.githubusercontent.com/assets/934364/17786453/e3f9be82-6552-11e6-9125-457f57e6f5c1.png)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9608
