### ISSUE TITLE
Delay strategy error trying to get the token with wrong credentials  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9613]
Related to card #9323 

When you try to get the token but you are using wrong parameters, the system is showing an error on log about the delay strategy 

ST: https://gist.github.com/bryanboza/f795f9f8cf0057926ca20891f872ea04

Here the token request:
`POST http://localhost:8080/api/v1/authentication/api-token
{ "user":"admin@dotcms.com", "password":"admin123", "expirationDays": 10 }`

Tested on master-3.7 // Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9710

**Comment by bryanboza** [comment]
Tested in the last master and still having the same error... Please retest

**Comment by jdotcms** [comment]
This should be fixed on https://github.com/dotCMS/core/pull/9784

**Comment by bryanboza** [comment]
New issue on #9795
