### ISSUE TITLE
Error when trying to save a News content using inline-editing

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#9619]
Steps to reproduce:

_Pre-condition: Configure one Enterprise License_

* Add a new content to a page  (in this case I reused this content: News - Pay off debt in 5 easy steps and added to about-us --> what-we-do)
* Click on the content and edit it.
* Try to Save. **Error: Content Could Not Be Saved. Please refresh and try again.
java.lang.String cannot be cast to java.io.File**

Environment: master-3.6/postgres/Linux. Note: Not happening on 3.5.1

Server log: https://gist.github.com/nollymar/10870347935bf5c9036f042f667b3b5a
![video-inline-license](https://cloud.githubusercontent.com/assets/8741395/17865112/8d71c35e-6866-11e6-869e-4598af6690c1.gif)

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9628

**Comment by nollymar** [comment]
Functional tests should be made with several content considering different content types.

**Comment by dsilvam** [comment]
Note to QA: please check that https://github.com/dotCMS/core/issues/8953 is still working. @shaydotcms

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9656

**Comment by shaydotcms** [comment]
Passed QA
Inline editing is working fine. Also tested #8953 and verified that tags and category fields are being added to ESSearch results
