### ISSUE TITLE
Delete site fails when content is locked

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#9621]
Steps to reproduce:

1. Create a new site, copy from demo.
2. Go to the new site, in the site browser, /application/vtl/custom-fields/
3. Lock youtube-search.vtl
4. Go to Sites portlet and try to delete the new site.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9623

**Comment by shaydotcms** [comment]
Issue is still happening.
Followed previous steps to reproduce and but this time locked "vimeo-search".vtl and I'm still getting the error: _ERROR business.HostAPIImpl: Contentlet is locked: Unable to archive_

![image](https://cloud.githubusercontent.com/assets/8741846/17934855/afd681a2-69d6-11e6-9f36-4366853f8f3a.png)

When I lock different files suchs as images, txt or videos and try to delete the site, it is successfully deleted but not when I lock vtl files.

I noticed that when I create a copy from an existing site, for instance demo, the new copy already contains locked files coming along with demo and I'm able to delete the recently created site, but if I lock a new vtl file, it fails deleting the new site.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9651

**Comment by shaydotcms** [comment]
Fix is working
Tested locking different contents such as .vtl, .html, images, videos, etc. Everything was properly deleted as long with the site.
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome
