### ISSUE TITLE
Uploading New file thru the file field modal window does not refresh to display the file

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9622]
This is a follow up to QA on this issue: https://github.com/dotCMS/core/issues/9550

When uploading a new file to an image field the modal window is not refreshing to show the new image uploaded.  You have to click on the clear button or the image folder to see the image.

Screencast: http://screencast.com/t/uHVijOeWry

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9645/files

**Comment by DeanGonzalez** [comment]
I tested the refresh in multiple languages - good fix
