### ISSUE TITLE
Other non-default languages are falling thru in the modal window

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9624]
This is a follow up task to #9550 

Only the default language version of the file should fall-thru if any secondary language version of the file is not found when this property is set to true in the dotmarketing config properties:

DEFAULT_FILE_TO_DEFAULT_LANGUAGE = true

The error is that if there is NOT a default language version, is will show the next language as a fall thru... allowing a french version of content to see and choose a spanish version of the file, when spanish is NOT the default language.  It is selectable, but  does not even save to the content.  We need to make sure that only the default language version of the file displays in that modal window when the currently selected language version of the file is not found.

screencast: http://screencast.com/t/kUcDyXCd

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9643

**Comment by shaydotcms** [comment]
Passed QA.
Verified that if there is NOT a default language version (EN) of the file, it doesn’t show in the modal another version of the file that is NOT the default language (ES, FR, etc)
Checked with different file types such as images, txt, video, etc. They work fine
Set up another default language (Italian) in dotmarketing.config and verified that it does fall thru when the file version is Italian and it doesn’t when is not Italian.

Tested on:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome
