### ISSUE TITLE
File field modal window does not respect multilingual file uploads for files with the same name

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9626]
Follow up task to #9550 

Easy to reproduce.
Create a piece of content that has a file field and upload an image to a folder using the file field.
Edit that same piece of content, switch to spanish, remove the file from the file field, and upload a file  using the file field modal that has the same exact file name, but is a different image to create a new spanish "version" of the file on upload and make sure you have selected the same folder to upload to.

After clicking upload, and even after clear to refresh the window, the spanish version of the file with the same name never uploads, and never creates the spanish version of the file with the same name... so only the English version of the file displays.

When adding content in a non-default language, but uploading a file if the same name, to the same folder, using the file field modal, a new version of the same file asset should be uploaded in the currently selected content language version (just like we do with webdav).

screencast: http://screencast.com/t/3qddlFpwC

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9648

**Comment by DeanGonzalez** [comment]
Great job Oscar! works really smooth now. Nice fix!
