### ISSUE TITLE
Toolbar notification doesn't close on iframe component

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9629]
The notification toolbar should be closed when we click anywhere out it, but when you click into a iframe it isn't closed.

![drop-down](https://cloud.githubusercontent.com/assets/10408015/17894371/213fdc50-6917-11e6-9f84-6f59813f5822.gif)

**Comment by bryanboza** [comment]
Still having the same problem...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/282

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // MySQL // FF

**Comment by bryanboza** [comment]
dotSite Selector isn't closing when you click in the iframe...

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/291

**Comment by bryanboza** [comment]
Fixed
