### ISSUE TITLE
Backend: Site selector component is not refresh

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9630]
When you create a new site or delete one the site selector component is not refreshed.

![site-selector-refresh](https://cloud.githubusercontent.com/assets/10408015/17894602/eb1d21cc-6917-11e6-9106-03f22ebcd4ad.gif)

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core-web/pull/196
https://github.com/dotCMS/core/pull/9823

**Comment by bryanboza** [comment]
Fixed
