### ISSUE TITLE
Fix role verification mechanism for the 'Login As' functionality

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9632]
Create a new REST service that returns both the list of users that can be used by the 'Login As' feature, and the role IDs that must be validated when switching to another user. This way, we'll get rid of one REST call to the server.

If the user is assigned to at least one of those roles, a password field will be displayed for the currently logged-in user to re-enter their password.

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/9657

**Comment by bryanboza** [comment]
Fixed, new bug opened in the point #2 of the card: #9735
