### ISSUE TITLE
Session expired error

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9642]
When the Http session or the JWT token expired dotcms is showing the old UI login dialog instead the new one (also it is showed into the new angular UI)

<img width="1229" alt="screen shot 2016-08-23 at 10 40 22 am" src="https://cloud.githubusercontent.com/assets/10408015/17900737/5a116352-692e-11e6-9446-dee0c0eb5ee8.png">
)

**Comment by freddyucv** [comment]
When the JWT token is expired  a 401 HTTP is sent from the backend.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/187

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF

**Comment by bryanboza** [comment]
Some issues on the card #9802
