### ISSUE TITLE
Image field modal window's left pane scroller not using full pane height

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9644]
As show in the image below, expanding the demo.dotcms.com host does not display items below the resources directory... new folders added and other hosts... like system host, are hidden - the scroller area is not using the full height of the pane.. only half.

![heightonscroller](https://cloud.githubusercontent.com/assets/1569167/17910777/972cea54-6947-11e6-877f-e4b0674b4ad8.jpg)

**Comment by maurizo** [comment]
This issue is related to this change https://github.com/dotCMS/core/issues/6431. I would be good to test it as well again.

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9649

**Comment by dsilvam** [comment]
@shaydotcms as Mauricio pointed out, please check [this one]( https://github.com/dotCMS/core/issues/6431) is still working

**Comment by shaydotcms** [comment]
Passed QA.
Tested modal window displayed thru Wysiwyg, file field, image field, etc.

![image](https://cloud.githubusercontent.com/assets/8741846/18016101/c7695558-6b87-11e6-9700-b6cc8671905f.png)

Tested on 
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome
