### ISSUE TITLE
Change SQLServer to store nvarchar and ntexts

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9647]
- [ ] We need to update our start up .sql files to use nvarchar and ntexts to store text fields
- [ ] We need to create a way that we can convert existing MSSQL implementations to nvarchar and ntext

mideas
- Startup task, drop all constraints, change the column storage, re-add constraints

**Comment by chrismccracken** [comment]
ntext() is deprecated, nvarchar(max) should be used instead.

**Comment by wezell** [comment]
Please reach out to @chrismccracken  on this- the importance of this fix is two fold:

1. Currently all parameterized DB queries cannot use the indexes on the text fields because the indexes are for ascii text and SQLServer JDBC Drivers are passing query params as UTF-8 and this forces a whole table scan - true for all tables- inode, tree, identifier tables.  This makes SQL operations slow.

2. In its current state, SQLServer is incapable of serving UTF-8 content.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10350

This ticket **MUST NOT BE CLOSED** until further tests with client datasets be performed.

Note to QA: dotCMS 3.6 upgrades using ALL databases must be tested. For MS SQL Server, you need to manually verify that the upgrade left all the constraints and "NULL"/"NOT NULL" declarations remain as they were before the task was run.

**Comment by jcastro-dotcms** [comment]
PR for fixing NPE: https://github.com/dotCMS/core/pull/10377

**Comment by dsilvam** [comment]
QA was done here: https://github.com/dotCMS/core/issues/9647
