### ISSUE TITLE
Time Machine does not serve pages properly

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9650]
It forces you to download them.  Might have to do with the change in the servlet filter orders

https://gist.github.com/wezell/177d1728e8211b7acef1dd55c471a86f

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9720

**Comment by nollymar** [comment]
Tested following these steps:

1. Install the solution from scratch.
2. Set CMS_INDEX_PAGE to index.dot.
3. Rename index page to index.dot.
4. Execute Time Machine and check past and future snapshots.
