### ISSUE TITLE
Error when publishing file in non default language

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9652]
When you publish an image or file which is NOT in a default language (EN), the system throws an error in the logs; however the file and content are **successfully published** and its functionality is not affected.

Steps to reproduce
1-Navigate to Content Search and choose Event from the dropdown
2-Add New Content and select a different language than default (EN)
3-Fill out required fields and upload an image in “Image” field or “File" field
4-Choose the image or file to upload to the folder and "Save and Publish"
5-Finally Save/Publish content
6-You will get the error message: https://gist.github.com/shaydotcms/01f332355646b1afae967b054576e453

Tested on:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9664

**Comment by shaydotcms** [comment]
Fix is working.
Tested with different non-default languages(FR, DE) and we don't have any more errors.
Tested on:
master-3.6 // Mac OS 10.10 // MySQL 5.6.23
master-3.6 // Ubuntu 14.04.1 // Postgres 9.3.5
