### ISSUE TITLE
Remap the icon servlet to /icon

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9653]
It has broken the file browser and I would rather hold off fixing that.

![screen shot 2016-08-24 at 4 25 36 pm](https://cloud.githubusercontent.com/assets/934364/17946692/6b8649c4-6a17-11e6-92de-70ca97a0b8d7.png)

**Comment by oarrietadotcms** [comment]
FWIW, the file browser in the screenshot was fixed on: https://github.com/dotCMS/core/commit/52429f4d683bb579f8a9dbae665a48b5e60fdf08
