### ISSUE TITLE
Webdav languages will not support languages with id.length > 2

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9654]
Not tested but I don't know how this could work.  We have customers with language_ids > 99.  It is expecting at most a 2 digit number no?

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/webdav/DotWebdavHelper.java#L1559

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9673

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9685

**Comment by shaydotcms** [comment]
Fix is working.
Tested when id.length = 2 (i.e.: language_id = 10) and id.length = 3 (i.e.: language_id = 100) 
Languages support is working thru Cyberduck and Finder.
Tested locally in master-3.6 // Ubuntu 14.04.1 and Postgres 9.3.5 // Mac OS 10.10 and MySQL 5.6.23
