### ISSUE TITLE
Backend: Provide i18n to relative date massages for the Notifications component

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9660]
Related to https://github.com/dotCMS/core/issues/9552

Add a service to provide i18n'ed messages to the Notifications component.

**Comment by jdotcms** [comment]
relativeTime : {
                d : 'un jour',
                dd : '%d jours',
                future : 'dans %s',
                h : 'une heure',
                hh : '%d heures',
                M : 'un mois',
                m : 'une minute',
                mm : '%d minutes',
                MM : '%d mois',
                past : 'il y a %s',
                s : 'quelques secondes',
                y : 'une année',
                yy : '%d années'
            },

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9686

**Comment by bryanboza** [comment]
Some things need be fixed in the #9707

**Comment by bryanboza** [comment]
Waiting for the translation...

**Comment by john-thomas-dotcms** [comment]
Translated, PR: https://github.com/dotCMS/core/pull/9780
