### ISSUE TITLE
Site Search Index not respecting Multilingual language versions

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9663]
Site search is broken in dotCMS 3.6 for multilingual pages & content in a way that was not broken in dotCMS 3.5

To recreate the bug:

1) Create a new page in english, add a generic contentlet with a few words in the WYSIWYG - make the LAST word an English word that you will search for in the site search and Save and Publish the content.
2) Create as spanish version of the page, change the Page Name & Friendly name to "Spanish Page" and publish the page.
3) Switch to the english version of the page, edit the English Content, and add a Spanish version of the content with a few words in the WYSIWYG - make the LAST word a Spanish word that you will search for in the site search and Save and Publish the content.
4) Go to the site search portlet and add a new job to create a new default index on the demo.dotcms.com host that includes all languages and run now.
5) Try to use the site search search tab for the spanish word - reveals no results (bug).  Now search for the English term and it will return both the English and Spanish pages as a result, when it should only return the English page. (bug)

screencast: http://screencast.com/t/uDFqZRYQBc7G

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9699

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9715

**Comment by nollymar** [comment]
Tested on Linux/PostgresSQL. Now, it works perfectly!
