### ISSUE TITLE
QA: Help the Rex team to test upgrades

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9670]
We need test upgrades with the client databases 
- [ ] canisius (mysql) 
- [ ] UTHSC (mssql) 
- [ ] Wawanesa (oracle) 2.5.7
- [ ] Marywood (postgres)

Here the info:  https://docs.google.com/spreadsheets/d/1klarK4Q0EhbTK6o9PLEumPmLq_GEH8aa-EBonrZCnQ4/edit#gid=0

**Comment by dsilvam** [comment]
related to https://github.com/dotCMS/core/issues/9637

**Comment by bryanboza** [comment]
Finished...
