### ISSUE TITLE
File Asset properties do not display in non-default language versions

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9674]
Found in the latest dotCMS 3.6 version

Easy to reproduce:
1) Add an image field to the generic content type
2) Open a page, edit the container and under generic content, choose the "image" property which gives you something similar to the following code in your container where the name of your image field is {yourFieldName) :
```
#if($UtilMethods.isSet(${yourFieldNameImageURI})) 
        <img src="$!{yourFieldNameImageURI}" alt="$!{yourFieldNameImageTitle}"  /> 
    #end 
```
3) Now add a generic contentlet to the page using that container, uploading an image to the image field.
4) Now edit the contentlet again, change the language to spanish, copy, then remove the image and upload a different image to the spanish version of the content.  The bug is that the image properties no longer display, because the file has a different name.

Note: what is strange is that if you upload a spanish language version of the file that is a completely different image, but has the same name as the English file name... then the properties display just fine in spanish... so it seems that somewhere we are doing lookups by filename instead of by identifier and language version.

Screencast: http://screencast.com/t/a442ReaAk3nR

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9682

**Comment by shaydotcms** [comment]
Passed QA. Fix is working in different languages
Tested in master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
