### ISSUE TITLE
Delete site when coming from upgrade fails 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9679]
- Start fresh on 3.5
- Upgrade to 3.6 
- Create new site off demo.dotcms.com
- Try to delete new site 

Error in log: https://gist.github.com/anonymous/d1b8c857f7f778f4df7250be2e5dac73

Reproduced using MySQL

**Comment by nollymar** [comment]
This issue affects all databases. Please, consider it for tests.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9701
