### ISSUE TITLE
Add the Finnish Flag to allow back end login in Finnish

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9681]
We currently have the Finnish backend translation file.  We need to add the Finnish flag to the supported backend login languages.

This is the image that should display for Finnish:

/webapps/ROOT/html/images/languages/fi_FI.gif

**Comment by dsilvam** [comment]
Include it here: https://github.com/dotCMS/core/blob/ba65cc39ff03c795142b47643ddf41d0236748c3/src-conf/portal.properties#L104-L104

**Comment by nollymar** [comment]
Commit: https://github.com/dotCMS/core/commit/a43dfff3fabf1f0a12bc01b36dbaa2efe0530744

**Comment by oarrietadotcms** [comment]
Passed QA, tested on Firefox and Chrome in Mac OSx. 

Note: this is only the language, the translation work should be done here: https://github.com/dotCMS/core/issues/9691
