### ISSUE TITLE
Content Type Field Editor should not permit multiple tag fields for a content type

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#9684]
We only support a single tag field on content.  The Content type editor should limit it so that only one tag field is permitted per content type.  This is how the "Site or Folder" field works.  If you try to add a second "Site of Folder" field, you get an error message saying that only one "Site or Folder" field is permitted per content type.  We should have this same functionality for tag fields.

This changed in 3.5 and existing customers with multiple tag fields are rather surprised by the change:  https://my.dotcms.com/tickets/detail.dot?id=27ba47f8-b1bf-41bb-8e19-2f1cdebfa608  Documentation is being updated to include the restriction:  http://dotcms.com/docs/latest/tag-field but the UI should prevent anyone from adding multiple tag fields going forward.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9915

**Comment by shaydotcms** [comment]
Passed QA.
Tested with different content types (banner, content generic, event, persona, etc) and only 1 tag is allowed per content type.
Tested locally in:
master-3.7 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.7 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome

**Comment by jtesser** [comment]
need to merge into 3.7

**Comment by dsilvam** [comment]
Merged into 3.7: https://github.com/dotCMS/core/pull/10429
