### ISSUE TITLE
Unable to log in when upgrading to 3.6 in MSSQL

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9690]
- Upgrade dotcms from 3.5 to 3.6 using a MSSQL DB and data from starter
- Attempt to log in to backend 

Authentication fail message is displayed

**Comment by dsilvam** [comment]
We need to test in Oracle also since Bryan got the same error on it

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9700

**Comment by shaydotcms** [comment]
Fix is working.
I was able to log in to the backend after upgrade with started data from 3.5 to 3.6 
No error messages in the logs
Tested on Win7 Pro SP1 and SQLServer 2012 // Mac OS 10.10 and MySQL 5.6.23 // Mac OS 10.10 and Oracle 12c
