### ISSUE TITLE
Add Finnish language file and update existing language files

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9691]
Add Finnish language file and update existing language files for new dotCMS 3.6 keys/values

**Comment by dsilvam** [comment]
Fixed here: https://github.com/dotCMS/core/pull/9701

**Comment by DeanGonzalez** [comment]
[Archive.zip](https://github.com/dotCMS/core/files/451022/Archive.zip)  Here are all the language files

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9722
