### ISSUE TITLE
Remove references of JAMM classes from OSGi Url Classloader

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9705]
Reproduced with custom OSGi plugin in dotCMS 3.5.1. 
Related to: https://my.dotcms.com/tickets/detail.dot?id=d53db4b3-3114-4e80-8e7f-7f77d40d2d6d

Stacktrace:
https://gist.github.com/joseorsini/5eab1651c4971c9b80460d696322d894 

If the -javaagent flag is not set in the JAVA_OPTS args upon startup, any deployment of an OSGi plugin will fail because the instrumentation set in the UrlOSGiClassloader will return a NPE because it cannot invoke instrumentation modules for loading the bytecode of plugin's classes into the application. 

Code that's failing: https://github.com/dotCMS/core/blob/master-3.7/src/com/dotmarketing/osgi/UrlOsgiClassLoader.java#L208-L212

**Comment by brentgriffin** [comment]
This was closed because in 4.1, JAMM is no longer used
