### ISSUE TITLE
UI: Integrate i18 relative date massages changes into the notifications UI

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9707]
Related to: https://github.com/dotCMS/core/issues/9660

Integrate the i18 relative date messages sent by the backend (https://github.com/dotCMS/core/issues/9660) into the notifications NG UI.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/184

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
