### ISSUE TITLE
Problems with the host selector using FF 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9716]
If you create a new site and refresh the page, you should be able to change the site, but if change this, and then try to select the old one we are having a js error and never load the resources, this on Site Browser 

To reproduce: 
- Add a new blank site 
- Go to site browser 
- Refresh the page 
- Change the site 
- Come back to the old site 

SC: http://screencast.com/t/UINnKJuzlt31
The system is showing a loading message, but never finish to load... 

Tested on master-3.7 // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/185

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
