### ISSUE TITLE
Hide Default user from Users portlet

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9717]
Reproduced in 3.6.0.

Default user is a system-related user that should not be displayed on Users portlet, nor it cannot be deleted. We should hide it from the Users list.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10842

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11213

**Comment by bryanboza** [comment]
Fixed, tested on master-4.1 // H2 // FF
