### ISSUE TITLE
New UI notifications fails calculating new relative dates 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9719]
We are having an error and the system stop working after you login in the new ui, open the notification window and after a minute try to open again this window, this because the system is trying to change the date massage. 

To recreate: 
- Login in the new Angular UI 
- Generate any notification
- Open the notification window 
- After a minute try to open again 

Here the SC: 
http://screencast.com/t/6PhxI6hB

Tested on master-3.7 // Postgres

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9707

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF
