### ISSUE TITLE
DotConfig, User and i18n

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#9721]
## DotConfig

The dotconfig object it's initialize on app boostrapping, that means this request to `/api/v1/appconfiguration` only happen once, this approach bring issues because if we logout and login (we are not boostrapping again by doing this) we are not updating data like for example i18n messages keys (that if the user login in other language it's an issue).

Also we can't update the dotconfig object because right now it's not save in any service.
## User

Right now, we "kinda" have two User map in core-web, they are store in:
1. LoginService: it's the one we use to display user information in the UI
2. DotConfig: comes from the core.

It's hard to work with because when we modify the user (for example in the "Login as" functionality) we have to do it in both places.

So the idea it's to unify in the same place.

> ## So DotConfig and User are not updating properly in the architecture we have right now.
## i18n

The same problem we need to update this on login and it's not happening.

**Comment by freddyucv** [comment]
Currently dotcmsConfig has the follow data:

1) Websocket Url: 
https://github.com/dotCMS/core-web/blob/master-3.7/src/api/services/dotcms-events-service.ts#L28-L30
2) The current login user and loginAs: 
https://github.com/dotCMS/core-web/blob/master-3.7/src/api/services/login-service.ts#L157 
3) The user's menu: 
https://github.com/dotCMS/core-web/blob/master-3.7/src/view/components/app.ts#L40
4) Message:
https://github.com/dotCMS/core-web/blob/master-3.7/src/view/components/common/notifications/notifications.ts#L37

Some of these thing like (1) never change no matter who is login, but (2), (3) and (4) change with the login user.

So I think that We have to become AppConfigurationService in a Angular Service (maybe change de name to something like AppInitContextService), and inject it in the App component, the AppConfigurationService should has a init method that do the request to get all the data ( this init method should be called just once). (2) is set in LoginService, (3) is set in RoutingService, (1) and (4) are set in two attributes in AppConfigurationService .
The init method should be called in the App Component's ngOnInit method.

The AppConfigurationService has to subscribe to the loginUser$ Subject, and refresh (4) when the login user change, (3) is refreshed by RoutingService, (2) by LoginService, and (1) not need to be refreshed

**Comment by fmontes** [comment]
I like @freddyucv idea of separating this things what I am not so sure about is if we are going to have the AppConfigurationService listening the LoginService or the other way around, also we have to think that if the User change (I mean there is a new Login) the Language can change (or not) too.

**Comment by freddyucv** [comment]
If we get the messages out from AppConfigurationService, it doesn't need listening the LoginService, I think that we must have another service the handler all about the messages

**Comment by fmontes** [comment]
Not only that.... I think that we can remove ```AppConfigurationService``` from the ```boot.ts``` and just bootstrap the app normally (I mean without any previous requests), if we can do this then we should be able to upgrade angular a little more easily.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core-web/pull/186
https://github.com/dotCMS/core/pull/9749

**Comment by bryanboza** [comment]
Here we need do a full regression over the new UI functionality...

**Comment by bryanboza** [comment]
QA pending in the iteration#6 in the card #9840
