### ISSUE TITLE
File Asset Resource Link path needs to be the same for all language versions

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9725]
Known issue on the dotCMS 3.6 version

If the all the multilingual versions of the file have the same name, then there is no issue, but with different file names between language versions the resource link breaks.

Easy to reproduce.  Add a file asset to a directory in the default language, and then edit the file asset again and add a spanish version but upload a different image with a different name.  Then try both of your resource links, making sure to ctrl-R or command-R to clear the browser cache:

http://localhost:8080/services/Lincoln.jpg?language_id=1
http://localhost:8080/services/BigHero6.jpg?language_id=2

The bug is that only one of your resource link image paths will work, the other will 404.

This needs to work like the HTML Page Assets do, in the sense that a multilingual object can have only one URI pointing to it - even in the UI.

The solution to the problem as per conversation with Will
1. URIs for files should be editable, like pages
2. When you upload multiple files in different languages to the same "fileAsset" then they all should respond to the same uri of the original asset.
3. We need to update the resource link to show the path stored in the identifier, this would be right
4. under this we should show the "permalink" /dotAsset link followed by the filename (again, from the identifier)
ala [/dotAsset/4d7daefa-6adb-4b76-896d-c2d9f95b2280/404.jpg](http://demo.dotcms.com/dotAsset/4d7daefa-6adb-4b76-896d-c2d9f95b2280/404.jpg)

Until this is fixed, it is recommended, instead of displaying file assets with the resource link, use the contentAsset link:

**Comment by wezell** [comment]
This is not an issue.  
Either you have a file represented by a single URI that can be shown in different languages or two totally different files, represented by two completely different URIs.  In 3.6.0 we have enabled the first case.

 


We can't have it both ways
