### ISSUE TITLE
Not able to relate content across multiple result pages

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#9732]
We often relate contentlets with many other contentlets. Relating contentlets can be very cumbersome for us if the search result has more than one page. Each time we want to select contentlets on multiple result pages, the page navigation deselects all checkboxes on the previous result pages. so we can only relate contentlets page by page, which is quite annoying when we need to relate a dozen contentlets across many result pages.

To reproduce this behavior in dotCMS 3.6.0 on demo.dotcms.com, you can follow these steps:
- Edit any content of type "Location"
- Go to the Relationships tab and click "Relate" to relate employees
- In the search pop-up select language "English - United States" and click "Search"
- You get 15 results on 2 pages
- Select an employee on the first page and click "Next" to navigate to the second page
- Click "Previous" to navigate back to the first page
  => The checkbox on the first page has been deselected

**Comment by levosgien** [comment]
Ref: https://dotcms.zendesk.com/agent/tickets/95189
