### ISSUE TITLE
Error changing the user password from my account window

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9734]
In the new Ng2 UI we can change the logged user password from my account window, but if you type any password that don't meed the security requirements, we are having an error in the log, but we are not showing nothing in the UI... 

Here the catalina log: https://gist.github.com/bryanboza/02040a178934ef09ca8b03cd143405ad
From the dotcms.log we jut have this message: 
`INFO user.UserResource: Error Updating User : Date: 2016-09-06 15:21:52;  User:dotcms.org.1`

We need show the error in the UI and log something more specific in the dotcms.log

Tested on master-3.7 // postgres // FF

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/9791
https://github.com/dotCMS/core-web/pull/190

**Comment by bryanboza** [comment]
After the last changes, when you have this error message and you change any of the fields we need reset this window and hide the message... This to avoid confusion if you have multiple times the same error.... http://screencast.com/t/DwyQ09pKJy

**Comment by oswaldogallango** [comment]
this pull should fix the last reported issue removing the error message https://github.com/dotCMS/core-web/pull/194

**Comment by bryanboza** [comment]
After the last commit, the system is validating the password just the first time, after you type some password that does not meet with the security requirements, and then try with another wrong password, the system is not validating after the second time time

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
