### ISSUE TITLE
Login As issues in the new Ng2 UI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9735]
Related to card #9287 

After this fix we have some issues: 

_Need to refresh UI elements when a user logins in as (see #9968 #10019)_
- [ ] When you try to login as, the system is showing the admin user as option to login as... Not make sense login as the same user (see #9968)
- [ ] ~~We should be able to scroll in the user list when you try to login as and you have multiple users~~
- [ ] We need show an error message if you try to login as any user that don't have associated layouts. Right now we are not showing nothing in the UI and this is the log: https://gist.github.com/bryanboza/2f6cf767c5d4f3c3e3bc1da0d13ff245
- [ ] ~~When you open MyAccount window we need focus on the first field... Right now we are not focusing this window~~ 

Tested on master-3.7 // postgres // FF

**Comment by jcastro-dotcms** [comment]
Core PR: https://github.com/dotCMS/core/pull/10043
Core-web PR: https://github.com/dotCMS/core-web/pull/221

**Comment by jgambarios** [comment]
**QA Note:** On this ticket we didn't fix the following points as those will be address it when we replace the current components with Prime NG:

- We should be able to scroll in the user list when you try to login as and you have multiple users
- When you open MyAccount window we need focus on the first field... Right now we are not focusing this window

**Comment by bryanboza** [comment]
After this fix we are unable to login as any new user, if you add some user this does not appear in the user list in the drop-down...

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/222

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
