### ISSUE TITLE
Add internationalization to login-as // MyAccount 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9740]
- [ ]  Right now we are hardcoding the labels on this sections, we need add the i18 messages to this features... 
- [ ] Also my account translation needs some improvements: http://screencast.com/t/3zOaG7ENifX

Tested on master 3.7 // Postgres // FF

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotCMS/core/issues/9721

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
