### ISSUE TITLE
Clean up and test language switching

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9741]
Placeholder for cleaning up the logic in the LanguageWebAPIImpl - it is a rats nest

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10042

**Comment by jgambarios** [comment]
**Note to QA:** Please test multilingual functionality.

**Comment by dsilvam** [comment]
**Note to QA (Cont):** In special this one: https://github.com/dotCMS/core/issues/9576. Because that particular class was changed for that issue and now it is all changed so we need to get thru that issue and all the comments on it and check it is working.
