### ISSUE TITLE
Export Contents: Tags are not always included in the Generated CSV file

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9744]
Our Export Contents feature does not include values for Tags Fields in a consistent manner, so upon re-importing the generated CSV file, Tags fields are left empty
## Expected Behavior

Despite we include comma-separated tags for each tag field on the exported Content Type, these values are not always available when Contents are being exported from the backend.
## Known Workarounds

There is no current workaround for this.
## Steps to Reproduce
1. Login to demo.dotcms.com site.
2. Go to Content Search Manager and select "Event" Content Type. 
3. Open one content and add custom tags to it. Save/Publish it.
4. Once you're back on Content Search Manager, click on "Export Contents". The CSV file includes the right tags for the recently edited content.
5. Go to Maintenance portlet and Flush all Caches.
6. Go back to Content Search Manager and Export all Events. CSV File does not include tags this time.
7. Edit the same content from Step 3. Add new tags. Save/Publish.
8. Export all Events again. Tags are still missing. 
## Context

Reported by customer, running dotCMS 3.5.1. 
https://my.dotcms.com/tickets/detail.dot?id=b723b4b4-7218-4656-828e-9c12b17ab606
## Environment Details:
- dotCMS version 3.5.1 and 3.6.0 (demo site).
- Google Chrome Version 52.0.2743.116.
- Mac OS X El Capitan.
- Java 8
- Postgres DB.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9745

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9896

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // MySQL // FF
