### ISSUE TITLE
QA: Test the relative dates internationalization in the notification window 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9746]
Related to card: #9660 

Now we have the i18 messages to the relative dates in notifications, but we need test the internationalization, right now we don't have translation to these messages... 

We need retest after add the language properties... 

Tested on master-3.7 // postgres // FF

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9780

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
