### ISSUE TITLE
Make ContentletAPITest runnable via right click and run as JUnit Test

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9750]
We need to be able to run this test outside the server and without needing it to be up. 

Some of the things preventing this to happen are already addressed here: https://github.com/dotCMS/core/issues/9671

This is a first phase that assumes an already existing tomcat directory with ES indices already created. 

## Expected Behavior
Be able to run this test via right click inside the IDE (Eclipse, IntelliJ)

## Current Behavior
If you try to run this test via right click inside the IDE, it will fail for various reasons. 

## Context
We need all functional tests to be able to run without needed the server up. This is already achievable for testing APIs that don't require ES with the changes in this issue: https://github.com/dotCMS/core/issues/9671.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9809

**Comment by nollymar** [comment]
The following tests are still being ignored: 
* findAllContent
* cleanField
* addFileToContentlet
* addImageToContentlet
* getRelatedContent
* getRelatedContentPullByParent

**Comment by nollymar** [comment]
The class **TestingJndiDatasource.java** was refactored because a new connection pool was being created when a connection was needed, hence, the existing connections were never reused

**Comment by dsilvam** [comment]
Second PR: https://github.com/dotCMS/core/pull/9832
