### ISSUE TITLE
Content Exporter does include tag values on newly created content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9754]
Create a new piece of content with a tag field, then try to export the content.  The tag values are not included in the exported CSV file
## Expected Behavior

The tag field values should export
## Current Behavior

Tag values are not exported until you edit the content again, then click on export, and it shows up in the CSV file
screencast: http://screencast.com/t/WxGXaS45N
## Known Workarounds

There is not really a work around, because editors can't be expected to keep track of which content has been re-opened after initial publish - we just need a fix.
## Steps to Reproduce (for bugs)

1. Create a new content type with a tag field
2. Add new content and a few tags, and Save & Publish
   3.Click the export button - tags values are not present (bug)
3. If you edit the content again and take a lock on it, then click cancel, then the exporter includes the tags in the exported CSV file.
## Your Environment
- dotCMS version used: dotCMS 3.6 (demo.dotcms.com)
- Browser Name and version: Chrome Version 53.0.2785.101 (64-bit)
- Operating System and version:
- Application Server and version:
- Java Brand and version:
- Database and version:
- Application module (if apply):

**Comment by joseorsini** [comment]
@DeanGonzalez this one may be related to https://github.com/dotCMS/core/issues/9744
