### ISSUE TITLE
Migrate TestNG unit tests to JUnit

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9757]
There are a few (to be optimistic) unit tests that need to be migrated from TestNG to JUnit. 
There are known features of TestNG used in some of these tests that have no direct equivalent in JUnit, for example, DataProviders. We need to look if JUnit5 (will upgrade to it) supports it. We can check this out also: https://github.com/TNG/junit-dataprovider

## Expected Behavior
All unit tests need to be in JUnit. 

## Current Behavior
Some unit tests are written in TestNG. Some are in JUnit. 

## Context
We are moving forward having a better way of running tests in dotcms. This is one of the steps to achieve so. This way you would be able to right click in your IDE and run the entire unit test package and get quick feedback, including coverage.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9771
