### ISSUE TITLE
Create new version of PR #9672 for 3.7.0

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9759]
PR needed: https://github.com/dotCMS/core/pull/9672

## Expected Behavior
No conflicts to merge the PR to 3.7.0

## Current Behavior
Unable to merge with no conflicts to 3.7.0 since it is branched off of 3.6

## Possible Solution
checkout the branch, merge 3.7.0 into it and re-send the PR. 

## Context
This commit is needed for all the next work to do related to the changes in testing infrastructure.

**Comment by oarrietadotcms** [comment]
Updated PR: https://github.com/dotCMS/core/pull/9672

**Comment by oarrietadotcms** [comment]
Javadoc included
