### ISSUE TITLE
Delete reindex entries by identifier

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9768]
The reindex queue holds a list of identifiers that need to be reindexed, which is an expensive operation. Currently, the queue can contain redundant entries for the same content object. When processing the reindex queue, and after a content object has been successfully indexed, we need to delete any redundant reindex entries by identifier to prevent the same content object from being reindexed multiple.
## Expected Behavior

A content object in the reindex queue should be indexed once and only once.
## Current Behavior

The same content can be reindexed multiple times unnecessarily by the reindex queue  
## Possible Solution

Delete from the queue by identifier rather than by id
## Known Workarounds

Live with a slow reindex process
## Steps to Reproduce (for bugs)
1. Stop the reindexthread (breakpoint or something)
2. Permission a host a few times and reset child permissions.
3. check these queries  (this is in mysql) : 
   `select count(*) from dist_reindex_journal;`
   `select count(*) as entries,ident_to_index from dist_reindex_journal group by ident_to_index order by entries desc;`
   You can see there are thousands of entries in the dist_reindex_journal and most of them are dupes.  Currently, these will get picked off one by one.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9769

**Comment by wezell** [comment]
done
