### ISSUE TITLE
Multilingual URL Map Behavior should be configurable

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9772]
Right now multilingual URL maps do not work if you copy them and paste them into another browser session.  We require that the language be set first.  Jonathan Gamba made a plugin that has the following solutions: 1) secondary language URL Map patters check for all language versions first, then set the language, then deliver the front end user to the detail page.  2) His code allows language switching from any URL mapped detail page in any language, and there is no 404 error.  Here is a link to his code that Will uploaded to github:

https://github.com/dotCMS/plugin-multilingual-urlmaps

We should add a parameter in dotmarketing configuration properties that sets this behavior by default, but allows webmasters to set it to false if they do not want URLMap patterns to reset the language in the session.

##: allows the URLMap pattern to set the language in the session to match the language version of the matching content
URLMAPPED_CONTENT_SETS_SESSION_LANGUAGE=true
## Expected Behavior

1) URLMapPatterns should be able to find matching content in any language version, then set that language version in the browser session before delivering the user to the detail page (Eliminates 404 errors)
2) Language switching http://somesite/somepattern?language_id=3 should work no matter what language you switch to from any URLMapped page.
## Current Behavior

Current behavior is that only default language URLMap patterns work when copied and pasted between browser sessions... secondary language urlmap patterns 404, unless you set the language at the end of the URL

**Comment by wezell** [comment]
Issue defined here: #15369
