### ISSUE TITLE
Viewtools: Pulling Content's structure/content type does not work as described on Documentation 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9774]
As per our [documentation](https://dotcms.com/docs/latest/display-structure-information-in-a-content-pull), we should be able to pull the Content's parent Content Type/Structure. If our content is stored on a variable called $con, by calling $con.structure or $con.getStructure() should work. 
## Current Behavior

Documentation, however, states that $con.contentType should return the parent Content Type/Structure, but this is not happening.
## Possible Solution

The fix needs to be implemented [here](https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/viewtools/content/ContentMap.java#L135), where we validate if the passed in value is actually a call for retrieving the Content Type/Structure 
## Known Workarounds

By using either $con.structure or $con.getStructure(), users can pull the Parent Content Type/Structure on Frontend Pulls.
## Steps to Reproduce (for bugs)
1. Create a test page on demo.dotcms.com site. 
2. Once the page is created, add a Simple Widget with the following code: 

```
#set($query = "+contentType:calendarEvent")
#set($list = $dotcontent.pull($query,5,"modDate desc"))
<ul>
#foreach($con in $list)
<li>$velocityCount $con.title</li>
<li>$con.contentType</li>
<br>
#end
</ul>
```

This is how the pull looks after the Widget is saved/published

<img width="1285" alt="screen shot 2016-09-12 at 4 46 26 pm" src="https://cloud.githubusercontent.com/assets/1717110/18452358/889ac472-7908-11e6-8ead-0a672187f9a3.png">
## Context

Reported by client on Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=a898de6e-046f-4d34-898b-d8b63aec6882
## Environment
- dotCMS version 3.3.2, 3.5.1 and 3.6.0:
- Google Chrome.
- Mac OS X El Capitan.
- Bundled-in Tomcat Application Version.
- Java 8.
- Postgres 9.4.1.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9777

**Comment by john-thomas-dotcms** [comment]
The documentation has been temporarily updated to reference the `.structure` property instead of the `.contentType` property, so we have a working case documented.  The code sample which uses the `.contentType` has been commented out.

(http://dotcms.com/docs/latest/display-structure-information-in-a-content-pull)

When this issue is integrated into a release, please mark the appropriate card as `Documentation Needed` so we can restore the `.contentType` code sample.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9777

**Comment by john-thomas-dotcms** [comment]
Doc Updated to (re-)use contentType instead of structure: http://auth.dotcms.com/docs/latest/display-structure-information-in-a-content-pull
