### ISSUE TITLE
Never send userId (or password for that matter) as a param once login has occured

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9783]
Our current websocket impl sends the raw userId as a query parameter which means that a user's id gets logged in the access logs the server or of any server/switch that is monitoring/proxying traffic.

We have a JWT implementation, please, we need to ONLY use the tokens to identify users from now on.
## Expected Behavior

Use JWT tokens to resolve the user in dotCMS 
## Current Behavior

passes the userId in the raw
## Possible Solution

Use the token and resolve the user Id
## Known Workarounds

none
## Steps to Reproduce (for bugs)
1. Login to dotcms
2. look at the network tab or access log

See screenshots:
![screen shot 2016-09-13 at 3 53 27 pm](https://cloud.githubusercontent.com/assets/934364/18489276/e4faf67a-79ca-11e6-8759-d9ec0cd25de1.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9933

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // chrome
