### ISSUE TITLE
Identify tests that make real requests and assert using response

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9785]
We need to put together a list of tests that make real requests and assert using the obtained response. 

## Context
Running Integration Tests outside the container.

**Comment by nollymar** [comment]
The following classes make real requests:

* com.dotcms.csspreproc.CSSPreProcessServletTest.java
* com.dotcms.csspreproc.LessCompilerTest.java
* com.dotcms.csspreproc.SassCompilerTest.java
* com.dotcms.publisher.ajax.RemotePublishAjaxActionTest.java
* com.dotcms.rest.ContentResourceTest.java
* com.dotcms.rest.RoleResourceTest.java
* com.dotmarketing.business.UserAPITest.java
* com.dotmarketing.portlets.contentlet.business.FileAssetTest.java
* com.dotmarketing.portlets.rules.ApiRequest.java
* com.dotmarketing.portlets.rules.RulesUnderPageAssetsFTest.java
* com.dotmarketing.portlets.rules.actionlet.PersonaActionletFTest.java
* com.dotmarketing.portlets.rules.actionlet.SetResponseHeaderActionletFTest.java
* com.dotmarketing.portlets.rules.actionlet.SetSessionAttributeActionletFTest.java
* com.dotmarketing.portlets.rules.actionlet.VisitorsTagsActionletFTest.java
* com.dotmarketing.portlets.rules.business.RulesAPIFTest.java
* com.dotmarketing.portlets.structure.business.URLMapTest.java
* com.dotmarketing.portlets.workflows.business.WorkflowAPITest.java
* com.dotmarketing.sitesearch.ajax.SiteSearchAjaxActionTest.java
* com.dotmarketing.webdav.WebDavTest.java
* com.dotcms.rest.WebResourceTest.java
* com.dotcms.rest.api.FunctionalTestConfig.java
* com.dotmarketing.portlets.rules.conditionlet.ConditionletFTest.java

**Comment by nollymar** [comment]
Additional considerations: 
* There are several ways to mock HttpServletRequests and many of them duplicate code already defined in ConfigTestHelper. We should define an standard for integration and unit tests in general.

* The code in ApiRequest.java is duplicated. Even, ApiRequest is defined as a public class, but it exists as private class as well.

* The existing logic in ApiRequest should be moved to ConfigTestHelper.

* Classes ApiRequest and ServletTestRunner might be deleted.

**Comment by dsilvam** [comment]
https://www.flowdock.com/app/dotcms/dev-team-rex/threads/anwlFlghYVcZ0bq3Z3FkezgHs86

**Comment by dsilvam** [comment]
Discussion about these tests: https://www.flowdock.com/app/dotcms/dev-team-rex/threads/anwlFlghYVcZ0bq3Z3FkezgHs86
