### ISSUE TITLE
Tests that require license need to run outside the container

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9786]
There are a number of tests that require to setup a license. 
For example [HostAPITest](https://github.com/dotCMS/core/blob/766f912e254eefc07084bbce20f32627eb2bc057/test/com/dotmarketing/portlets/contentlet/business/HostAPITest.java#L34-L34) . 

This fails since it is unable to find the needed resources. 

## Expected Behavior
Tests that require license need to be able to run outside the container  

## Current Behavior
Tests fail when trying to set up a license

## Context
Running Integration Tests outside the container

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9787

**Comment by nollymar** [comment]
Additional PR: https://github.com/dotCMS/core/pull/9790
