### ISSUE TITLE
Database migration of dotCMS 3.6.0 fails on MySQL with case sensitive table names

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#9788]
The database migration script of dotCMS 3.6.0 cannot find the table "Folder" (with capital "F"). Actually the table name in the database is "folder" (in lower case). This causes an exception in the migration process and the migration fails. Turns out that MySQL can have case sensitive table names depending on the configuration values at database creation.
## Expected Behavior

The database migration should complete successfully.
## Current Behavior

An exception occurs during migration:
FATAL runonce.Task03545FixVarcharSizeInFolderOperations: Unable to execute SQL upgrade
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'Folder' doesn't exist
## Possible Solution

Change the table name in the database migration script to "folder" (in lower case).
## Known Workarounds

Create a new database in MySQL and set the variable "lower_case_table_names" to 1.
## Steps to Reproduce (for bugs)
1. Create a new database in MySQL and set the variable "lower_case_table_names" to 0.
2. Import a starter.zip file with dotCMS 3.5.1.
3. Execute the database migration with dotCMS 3.6.0.
## Context

Unable to upgrade from dotCMS 3.5.1 to dotCMS 3.6.0, because the database migration fails.
## Your Environment
- dotCMS version used: 3.5.1
- Browser Name and version: not applicable
- Operating System and version: Debian GNU/Linux 8.5 (jessie) 
- Application Server and version: Bundled Tomcat 8.0.18
- Java Brand and version: Java 1.8.0_102
- Database and version: MySQL 5.5.50
- Application module (if apply):

**Comment by gabbydotCMS** [comment]
I think this should not be happening if the original database had been created after setting 

lower_case_table_names=1

in the MySQL configuration file as our documentation indicates

http://dotcms.com/docs/latest/database-configuration#MySQL

However, since the name of the table is lowercase in all our DB creation scripts since 3.0, I guess changing the trigger rename_folder_assets_trigger to use "folder" instead of "Folder" should not cause any harm.

**Comment by wezell** [comment]
we should not require lower_case_table_names=1 any longer, at least not on mysql-unix

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9858
