### ISSUE TITLE
Notification language improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9792]
Right now when you generate any notification, the system is saving this in the database, if you are in any language and generate the notification this is saving in this language, if you change the system language, the notification still appearing in the generated language, we need change this to support multi-languages 
## Expected Behavior

The notification should appear in the system language 
## Current Behavior

After change the system language the notifications are not changing 
## Steps to Reproduce
- Change the system language to spanish 
- Generate some notifications 
- Change the language to english and login again 
- Open the notification window 
## Environment

Tested on master-3.7 // FF // Postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9841

**Comment by bryanboza** [comment]
Fixed, tested in the last master-3.7 // Postgres // FF
