### ISSUE TITLE
Need reset the count to calculate the delay strategy every time you login success

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9795]
Related to #9613 

After this commit, now we have an incremental wait avery time you fail the login process, the system is calculating this time (2^X) where X=failed attempts... But if you fail multiple times, then login and after logout you fail again, we are continuing with the same count, we need restart this after login 

 ## Expected Behavior
Need restart the count every time you login success
## Current Behavior

We are continuing with the same wait 
## Steps to Reproduce
- Make 5 failed attempts to login 
- Login success
- Logout 
- Fail 2 logins again 
## Environment

Tested on master-3.7 // H2 // FF

**Comment by wezell** [comment]
How do we check for repeat attempts? By IP?

**Comment by bryanboza** [comment]
That's by user...
