### ISSUE TITLE
Multi-valued X-Forwarded-For header breaking Rules Engine VisitorAPIImpl

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9797]
## Expected Behavior

Client IP address should be properly fetched from X-Forwarded-For request header if XFF contain multiple IPs
## Current Behavior

UnknownHostException is throw due to HttpRequestDataUtil.getIpAddress() returning invalid data. https://gist.github.com/chrismccracken/63677134a9ee0f04c7b2171414a53cd3
## Possible Solution

In https://github.com/dotCMS/core/blob/master-3.7/src/com/dotcms/util/HttpRequestDataUtil.java#L61, 
HttpRequestDataUtil.getIpAddress() should properly handle multi-valued header. The _first_ IP in the list should be the correct real client IP per spec and should be returned (`X-Forwarded-For: client, proxy1, proxy2`). HttpRequestDataUtil.getIpAddress() should also perform output validation that it is returning an IP address to caller at https://github.com/dotCMS/core/blob/master-3.7/src/com/dotcms/util/HttpRequestDataUtil.java#104.
## Known Workarounds

None.

**Comment by chrismccracken** [comment]
Client affected, https://my.dotcms.com/tickets/detail.dot?id=0749e633-2cd6-469d-91e9-6268b539bdc8

**Comment by jcastro-dotcms** [comment]
Another client affected: https://my.dotcms.com/tickets/detail.dot?id=0749e633-2cd6-469d-91e9-6268b539bdc8

It's very important to handle the multi-value situation. Also, the exception handling needs to be considered as the exception is not being handled and it's messing with the complete request.

**Comment by joseorsini** [comment]
Another client affected: https://my.dotcms.com/tickets/detail.dot?id=1b77f1b2-91c5-4eeb-bdc4-77d073328658 

Stacktrace: https://gist.github.com/joseorsini/f658d927fca463a21d276ce2cb40c370

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10653

**Comment by nollymar** [comment]
Tested with a unit test: https://github.com/dotCMS/core/pull/10971
