### ISSUE TITLE
Unable to add content to new structures from the new NG2 "+" button 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9798]
Related to #9286 

As all the new functionality we need send an event every time you add a new content type, this to add the new structures in the menu when you click the "+" button 
## Current Behavior

After you add a new content type, you are unable to see it from the "+" button  menu
## Possible Solution

We need add a notification to refresh the event 
## Steps to Reproduce (for bugs)
- Add a new content type
- Try to see it from the "+" button 
## Your Environment

Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/9871
https://github.com/dotCMS/core-web/pull/201

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF
