### ISSUE TITLE
Clean up of bundles

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#9799]
Push publishing creates bundles which often include a very large number of small files.  This is an issue on ext3/4 filesystems which cannot scale inode allocation and has resulted in production authoring sites crashing due to running out of inodes on the filesystem.

## Expected Behavior
On successful push bundles should be marked for deletion after 7 days and then at that mark should be deleted from the filesystem.

## Current Behavior
Currently the bundles remain on the filesystem, consuming both disk space and inodes

## Possible Solution
Bundles should be deleted after a set period of time

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* dotCMS version used: 3.x
* Browser Name and version: any
* Operating System and version: linux
* Application Server and version: any
* Java Brand and version: any
* Database and version: any
* Application module (if apply):

**Comment by john-thomas-dotcms** [comment]
Suggestion: Config option on time limit for bundles (default to 7 days).

Alternate: Ability to set a max size of saved bundles.  While this would probably be more useful than a time limit, it would also present more potential challenges (so a configurable time limit would be easier to implement and maintain).

**Comment by mattyarbrough** [comment]
This is a duplicate issue of https://github.com/dotCMS/core/issues/5541, it's affecting clients in production now.

**Comment by wezell** [comment]
No known workaround?  This is fatal and unrecoverable issue?  There is no other way to delete these files on a timed basis?  humm.
