### ISSUE TITLE
UI: NG Select component enhancement

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9803]
## Expected Behavior

Our current NG Select component should have a text filter

**Comment by jgambarios** [comment]
We should use: http://www.primefaces.org/primeng/#/autocomplete

**Comment by jgambarios** [comment]
- We need to delete our **dotSelect** component
- Replace all the places that used our **dotSelect** with the Prime NG select component.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/227 and https://github.com/dotCMS/core/pull/10111

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF... Some UI enhancements required
