### ISSUE TITLE
NG My Account enhancements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9804]
## Expected Behavior
- Add a new Field **"Current Password"** to the **My Account** modal
- For any change on the **My Account** modal the Current Password should be required/validated in the back end.
- In the UI the **Current Password** should be a required field.
- In the UI we need to change the labels:

From: "Password" to **"New Password"**
From: "Confirm Password" to **"Confirm New Password"**
- Make sure the rest end point for **My Account** functionality requires authentication.

Related to: https://github.com/dotCMS/core/issues/9573

**Comment by bryanboza** [comment]
Also now we have disabled the save button, then you are unable to edit some of the first 3 fields, "**First Name, Last Name, Email**", you need type the password to enable the button, and if the password don't meet the security requirement need change the password... As in the admin case, the pass is "**admin**"

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/9850
https://github.com/dotCMS/core-web/pull/200

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
