### ISSUE TITLE
JWT should have a max allowed lifetime

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9806]
## Expected Behavior

We should be able to configure the maximum lifetime of Web Tokens and any JWT should NOT live longer than the new lifetime property.
## Current Behavior

Right now you can request a JWT and specify how much time the token will live, but there is not a limit for the lifetime of that token.
---

Related to: https://github.com/dotCMS/core/issues/9323

**Comment by jdotcms** [comment]
We need doc for this Config property

json.web.token.max.allowed.expiration.days

This property basically says how many days are the max allowed for an expiration days, if the property is set and an user tries to create a token using a higher value, the max allowed expiration days value will be assigned instead.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9920

**Comment by jgambarios** [comment]
@jdotcms please change the default of the **json.web.token.max.allowed.expiration.days** to **30** days

**Comment by bryanboza** [comment]
Fixed, tested on 3.7
