### ISSUE TITLE
Backend: Create Recent Content/Widgets for the Add New Content Functionality

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9807]
![screen shot 2016-09-07 at 1 46 50 pm](https://cloud.githubusercontent.com/assets/10408015/18326161/7a40edba-7512-11e6-951d-da05214a59af.png)

We implemented the Add New Content Functionality in the issue https://github.com/dotCMS/core/issues/9286 without the Recent Content / Recent Widget Functionality.

We need to create the Recent Content / Recent Widget functionality.
### Proposed solution:

The Contentlet table have a **mod_user** column, that means that querying the database we can know with which Contentlets an user have interacted, and with that info we should be able to figured it out the recent Content Types for the current user.

On top of the query in order to find the recent Content Types we need to add a cache in order to avoid to hit always the db.
---

Related to: https://github.com/dotCMS/core/issues/9286

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core-web/pull/204
https://github.com/dotCMS/core/pull/9907

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/9838

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // h2 // ff
