### ISSUE TITLE
NG2 Reset Password enhancements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9808]
- [ ]  When you try to reset the password to any user, the system is sending a link to your mail, if you open this link and type a no valid password (security requirements)... The system should add something in logs... Right now we are not logging... 
- [ ] If you are trying to change the password and have the "security requirements" error message, and you type other password that doesn't meet the requirements again, the system is not showing nothing in the UI, neither on logs... 
## Expected Behavior

The system should show an error in the UI
## Current Behavior

Just show an error one time 
## Your Environment

tested on master-3.7 // postgress // FF

**Comment by oswaldogallango** [comment]
these are the pull for this issue https://github.com/dotCMS/core-web/pull/195 and https://github.com/dotCMS/core/pull/9817

**Comment by bryanboza** [comment]
Fixed, some issues pending in the new task...

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // postgres // FF
