### ISSUE TITLE
Pending Content Page editMode javascript errors on NG Iframe Component 

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#9811]
Enter in edit mode on any Page content, add or edit a content or edit the page properties or template and return to the edit mode page, then we are having the following issues:

1) If you click to add, reuse, move, etc a contentlet all those links are open in a new window instead of being opened in the same iframe. Same thing happens with several options of the left menu panel.

2) The back to admin cms button doesn't do anything
## Expected Behavior

1) The page loaded need to be loaded in the same detailFrame 
2) The back to Admin server should work always
## Steps to Reproduce (for bugs)
1. Go to the Site Browser
2. Open a content page, for example: home/index
3. Add a new content in that page
4. Try to add another content or edit the template or edit the content properties
## Context

The issue only happens when you try to use the iframe legacy. this issue is related to https://github.com/dotCMS/core/issues/9300
- dotCMS version used: Master-3.7
- Browser Name and version: Any Browser
- Java Brand and version: Java 8

**Comment by oswaldogallango** [comment]
Only left to fix and issue with the publish page that is reloading the whole page in the old UI and not in the iframe. This is the issue https://github.com/dotCMS/core/issues/9913

**Comment by oswaldogallango** [comment]
This is the PR. https://github.com/dotCMS/core/pull/9914

**Comment by bryanboza** [comment]
Here we still having problems with the point #2:  
After the fix #9299 after create any page, this button works fine, but if you logout and login again, when you open the edit mode of any page the back to admin button is not working... 

FYI: This is in all the browsers

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/9958

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
