### ISSUE TITLE
Import Contents: User can import blank tags to system

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9814]
Follow-up to https://github.com/dotCMS/core/issues/9744
## Expected Behavior

Once the 9744 fix is in place, or a CSV file includes values for Tags fields, we should verify if the values read from the CSV file are valid.
## Current Behavior

We're able to import blank tags for contents, at the moment we import them via CSV file. 
## Known Workarounds

Manually verify the CSV file and see if Tags fields are properly populated.
## Steps to Reproduce
1. Go to Content Search portlet.
2. Select "Event" content type and export all contents to a CSV file.
3. If the 9744 Fix is not merged/deployed in the testing environment, the Tags field are going to be empty on the generated CSV File.
4. Open the CSV File in MS Excel/LibreOffice and for the "dotCMS Online Training Session (w/ Image)" content, add "tag 001,,tag 003" as the Tags field value. Delete the "Identifier", "languageCode" and "countryCode" columns. Save the file.
5. Go to Import Contents portlet and select Event content type.
6. Upload the edited CSV file. Mark "Title" as Key, so existing contents will be overwritten by the ones on the CSV file. 
7. Go to Preview and then Import the contents if no errors are listed on the Preview mode.

Despite the Content, once imported and updated, does not show the blank tag on its Tags field, the blank Tag is listed in the Tag Manager Portlet.

<img width="1290" alt="screen shot 2016-09-20 at 3 14 13 pm" src="https://cloud.githubusercontent.com/assets/1717110/18685433/ff0f522e-7f45-11e6-9401-1f9cfba3847a.png">

<img width="1279" alt="screen shot 2016-09-20 at 3 14 30 pm" src="https://cloud.githubusercontent.com/assets/1717110/18685443/086615ba-7f46-11e6-915f-c6484d745ead.png">
## Context

Related to Support Ticket https://my.dotcms.com/tickets/detail.dot?id=48a62652-66c8-46b6-af04-8043c0fe9d8b Client is running dotCMS version 3.5.1.
## Your Environment
- dotCMS versions 3.5.1 and 3.6.0
- Google Chrome Version 53.0.2785.116 (64-bit)
- Mac OS X El Capitan
- Bundled Tomcat application server.
- Java 8.
- Postgres DB version 9.4.1.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9816

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF
