### ISSUE TITLE
New Content Button is not permission based

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9820]
When a limited user hits the "New Content" button they are still seeing all the content types even though they don't have access to them.
## Expected Behavior

It should only show the base types the user has access to and then only the content type they have edit perms to (this is the current behavior on the edit content screen). 
## Current Behavior

It shows everything for everyone
## Possible Solution

fixing it
## I am logged in as "Joe Contributor"

![screen shot 2016-09-22 at 9 51 35 am](https://cloud.githubusercontent.com/assets/934364/18751758/2de77ab8-80ae-11e6-8112-c7bbeedd0adb.png)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/197

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // Postgres // FF
