### ISSUE TITLE
Make FixAssets an OSGi extension point

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9822]
We are constantly providing customers with raw sql to run to "clean up" their databases. It would be great if we could provide them instead with a java  FixAssetInconsistancy task that could be installed into a running system and run to fix existing db issues.  This would provide automatically provide RnD with prebuilt tasks that could be incorporated into the system on an ongoing basis.
## Expected Behavior

Allow a user to add a fix asset task via osgi
## Current Behavior

Cannot happen now as a the list of tasks are static

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9824
