### ISSUE TITLE
Unable to see the Rules Engine portlet from the old UI 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9825]
After the last changes in master-3.7, we are unable to show the Rules Engine portlet... We need support both user interfaces... 
**FYI: Tested in the new UI adn works fine** 
## Expected Behavior

We should be able to see this portlet without problems 
## Current Behavior

We are having an error 500... 
https://gist.github.com/bryanboza/b1f9a09d9ff14056bc352684d30afd03
## Your Environment

master-3.7 // Postgres // FF

**Comment by oswaldogallango** [comment]
depends on the resolution of issue https://github.com/dotCMS/core/issues/9332 to allow ng to resolve the URLs path related used in the iframe to load the rules engine. Also, need to fix "+" sign that is affecting the springmvc-servlet.xml
