### ISSUE TITLE
Forgot password isn't working from the old UI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9827]
If you try the forgot password from the old UI we are doing all the process without problems, the system shows a success message, but the password never is changed... 
## Expected Behavior

We need support this feature for both UI 
## Current Behavior

We are showing a success message, but the password is not changing 
## Your Environment

Tested in the last master-3.7 // Postgres // FF

**Comment by oswaldogallango** [comment]
PR https://github.com/dotCMS/core/pull/9829

**Comment by shaydotcms** [comment]
Passed QA. Password is reset correctly with the new information and user is able to log in
Tested locally in:
master-3.7 // Win7 Pro SP1 & SQLServer 2012 // Ubuntu 14.04.1 & Postgres 9.3.5
