### ISSUE TITLE
Current tests are failing when run via servlet because of mockContext

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9833]
Because of the new method call to set the mock context and datasource, tests are failing when executed via the test servlet 

## Expected Behavior
Tests not already adapted to run outside the container should run and pass when run either via servlet.
## Current Behavior
Tests fail with this error: https://gist.github.com/nollymar/08c08706f448c69ae88269182f3f1186

## Possible Solution
Have a way to set the mock context only when tests are run outside the container 

## Steps to Reproduce (for bugs)
1. ./gradlew deploy-war-tomcat-test
2. http://localhost:8080/servlet/test?resultType=plain

## Context
We need to have a stabilized set of tests before continue doing the work of adapting them to run outside the container or migrating to JUnit5

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9842
