### ISSUE TITLE
Modifications to dotcms's version of Preconditions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9834]
We need to do a few modifications to our version of Preconditions
1. Rename to DotPreconditions
2. Move to com.dotcms.util
3. Have all methods included in google's Preconditions, keeping the extra functionality in ours.

## Expected Behavior
Being able to use DotPreconditions with all methods in google's version in addition to the existing methods in dotcms's Preconditions

## Current Behavior
DotCMS's Preconditions is inside a 'rest' package and it only has a striped set of methods from google's version. 

## Possible Solution
Either extend from google's or wrap it

## Context
Having a standardized way of checking parameters in APIs or Factories.

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9845
EE PR: https://github.com/dotCMS/enterprise-2.x/pull/386
