### ISSUE TITLE
Upgrade core-web project to the final Angular version

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9835]
1. Upgrade core-web to latest Angular 2
2. Packaging of the upgraded web-core distribution (Packaging and publish in artifactory)

**Comment by fmontes** [comment]
Issues:

- [ ] AccountService error
- [ ] Notification badge count not working

**Comment by bryanboza** [comment]
Also we have a undefined button under the "+" button menu: http://screencast.com/t/ijLmJDGLe This link do a logout...

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
