### ISSUE TITLE
Integrate new components library to the NG project

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9837]
Related to: https://github.com/dotCMS/core/issues/9836

**Comment by jgambarios** [comment]
Initial work PR: https://github.com/dotCMS/core-web/pull/216

We include prime NG just to the login page, we still need to remove Angular material and replace it with prime NG, an epic will be created for this.

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF... Everything works as expected
