### ISSUE TITLE
Unable to load starter site when using NFS

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#9848]
Deploying a fresh dotCMS install using a NFS volume for storing the assets causes a FileSystemException and assets are not copied over to the ASSET_REAL_PATH 
## Expected Behavior

Typically the process tries to create a hard link and in failure it falls to a regular copy
## Current Behavior

The process is failing after not being able to create the hard link over different filesystems (Invalid cross-device link)
## Steps to Reproduce (for bugs)

1. Download dotCMS 3.6.0
2. Create a NFS volume for placing the assets
3. Set ASSET_REAL_PATH to point to a directory inside the NFS volume
4. Start dotCMS
## Context

Versions < 3.6.0 don't have any problems under the same scenario
## Your Environment

- dotCMS version used: 3.6.0
- Browser Name and version: NA
- Operating System and version: CentOS, Amazon Linux
- Application Server and version: NA
- Java Brand and version: OpenJDK 1.8.0_101
- Database and version: NA
- Application module (if apply): NA

**Comment by wezell** [comment]
see: #9997

**Comment by oarrietadotcms** [comment]
I confirmed this is fixed. 

I started 2 Ubuntu VMs and installed NFS, shared a folder where dotsecure and assets will live. Everything started just fine in the proper paths. No errors in the log.
