### ISSUE TITLE
Firefox is not adding .zip extension to downloaded index snapshot file

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9851]
Related to #9127 
When you download the index snapshot using Firefox, the file doesn't contain .zip extension, contrary to Chrome 

Steps to reproduce:
1-Login to dotcms using **Firefox**
2-Navigate to System> Maintenance> Index tab. Right click over any index and select "Download Index Snapshot"
## Current Behavior

Using Firefox, the downloaded file doesn't contain .zip extension
## Expected Behavior

Using Firefox, the downloaded file should contain .zip extension, the same way Chrome does it
## Your Environment

Tested on branch "issue-9127-replace-current-index-backup-restore" // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome and Firefox

**Comment by maurizo** [comment]
Fixed on #9127 by https://github.com/dotCMS/core/commit/0456289666d28201e356c577d1c950d611efab2f

**Comment by shaydotcms** [comment]
Passed QA. 
File is properly downloaded as .zip
Tested on master-3.7 // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome and Firefox
