### ISSUE TITLE
Allow relative path for es.path.repo property

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9852]
Related to #9127
The system should allow a relative path for es.path.repo property, because currently it only allows an absolute path when you try to download an index snapshot.
Error: https://gist.github.com/shaydotcms/935ba97e3409dbbc4b9486f72782984b
## Steps to reproduce:

1-Open file dotcms-config-cluster.properties and add the following property: es.path.repo="some relative path, i.e.: dotsecure/test"
2-Save changes
3-Startup dotcms instance
4-Login to dotcms
5-Navigate to System> Maintenance> Index tab. Right click over any index and select "Download Index Snapshot"
## Current Behavior

If you define a relative path for property es.path.repo such as es.path.repo="some relative path, i.e.: dotsecure/test", you will get an error: https://gist.github.com/shaydotcms/935ba97e3409dbbc4b9486f72782984b
## Expected Behavior

The system should allow a relative path for property es.path.repo
## Your Environment

Tested on branch "issue-9127-replace-current-index-backup-restore" // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome and Firefox

**Comment by maurizo** [comment]
Fixed on #9127 by https://github.com/dotCMS/core/commit/106caa240571eb63b9dd3eb43662ff9392f144e7

**Comment by shaydotcms** [comment]
Passed QA, relative path for es.path.repo property is allowed and not errors are shown in the logs.
System successfully creates folder inside specified in es.path.repo property, i.e.: dotsecure/testqa/snapshots
Tested on master-3.7 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
