### ISSUE TITLE
Create Init Service for Integration Tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9853]
Create a service that deals with all the initialization and setup required for running integration tests outside the container. The initialization should occur only once, regardless of running the whole test suite, a test class or a single test method. 

## Expected Behavior
IntegrationTestInitService.getInstance().init() at the @BeforeClass of an integration test should make it able to run outside the container. 

## Current Behavior
So far there are a couple of calls needed to make the test run properly, but this will probably grow and we need to centralize it. 

## Possible Solution
Create a singleton service that deals with the required initializations and setup.
Suggested Name: IntegrationTestInitService

## Context
Running Integration tests outside the container.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9855
