### ISSUE TITLE
Delete file created when snapshop downloaded via REST

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9856]
We are leaving a timestamped zip of the snapshot when it is created/downloaded via REST.
This needs to be deleted since there is not a way to re-request it or a reason to persist it. See [here](https://github.com/dotCMS/core/issues/9127#issuecomment-250536250). 
## Expected Behavior

Timestamped zip is deleted after response has been fully delivered to the client (or has failed)
## Current Behavior

The file is not cleaned up and persists indefinitely 
## Possible Solution

Delete the file after response has been fully delivered to the client (or has failed)
## Known Workaround

Delete manually
## Steps to Reproduce

Run: curl --user admin@dotcms.com:admin -XGET http://[dotcms-host]:[port]/api/v1/esindex/snapshot/index/[index_name] > snapshot.zip

File will left persisted under dotsecure/backup

**Comment by maurizo** [comment]
Fixed on #9127 by https://github.com/dotCMS/core/commit/21f8011cf27e7a833bf0edae9c419ff0de3bbc9f

**Comment by maurizo** [comment]
Passed QA.
