### ISSUE TITLE
For DataTable View Implement Side Details 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9867]
Need a detailed side component for selected items of the DataTable View see here https://github.com/dotCMS/core/issues/9866
## Expected Behavior

Should work similar to GoogleDrive on the right
![screen shot 2016-10-03 at 8 23 26 am](https://cloud.githubusercontent.com/assets/1486445/19037145/c064b56c-8942-11e6-9a01-f3866ad2c1a8.png)

**Comment by fishsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/1561349/19052764/12de83fc-8986-11e6-939a-1494a511306c.png)

**Comment by jtesser** [comment]
![image](https://cloud.githubusercontent.com/assets/1486445/19052808/3cd05f8c-8986-11e6-99bb-7dd0114804d3.png)
