### ISSUE TITLE
System should let the user know from the UI if there's any error with Index Snapshot

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9873]
Related to #9127 
System should let the user know from the UI if there's any error, as it currently does in the logs. For instance, if you try to restore an index snapshot thru the UI and it already exists, you will get an error message in the logs, but the UI is not showing any info to the user about what is going on, just a static image:
![image](https://cloud.githubusercontent.com/assets/8741846/19040499/8cfc3f8e-8941-11e6-9275-f78afddfc5bf.png)
## Steps to Reproduce (for bugs)

1-Open file dotcms-config-cluster.properties and add the following property: es.path.repo=dotsecure/test
2-Save changes
3-Startup dotcms instance
4-Login to dotcms
5-Navigate to System> Maintenance> Index tab. Right click over any index and select "Download Index Snapshot"
6-After the index has downloaded, click "Add Index" button and select Restore Index Snapshot
7-Upload the same index you have just downloaded
8-You will get an error message in the logs but not in the UI:
_WARN elasticsearch.snapshots: [f21777ca-95fc-4415-9db7-40943cd4d67e] [backup:working_20161003075056] failed to restore snapshot
org.elasticsearch.snapshots.SnapshotRestoreException: [backup:working_20161003075056] cannot restore index [working_20161003075056] because it's open_
## Expected Behavior

System should let the user know from the UI if there's any error, as it currently does in the logs
## Current Behavior

Error message is not showing in the UI
## Your Environment

Tested on branch "issue-9127-replace-current-index-backup-restore" // Ubuntu 14.04.1 // Postgres 9.3.5 // Chrome and Firefox

**Comment by maurizo** [comment]
Fixed on #9127 by https://github.com/dotCMS/core/commit/6138f7f550648990bdc79b87168e2d6fefcdc363
