### ISSUE TITLE
Index Snapshot zip file gets stored in dotsecure folder after it's uploaded from UI

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9874]
Related to #9127 
When you upload an index snapshot, the system keeps the .zip file inside “dotsecure" folder. In addition, it creates the repo folder defined in dotcms-config-cluster.properties (i.e.: es.path.repo=dotsecure/test_snapshots) which contains info about the index:
![image](https://cloud.githubusercontent.com/assets/8741846/19045521/7d5759a0-8956-11e6-8c11-d27a16bc7a21.png)
## Steps to Reproduce (for bugs)

1-Open file dotcms-config-cluster.properties and add the following property: es.path.repo=dotsecure/test_snapshots
2-Save changes
3-Startup dotcms instance
4-Login to dotcms
5-Navigate to System> Maintenance> Index tab. Right click over any index and select "Download Index Snapshot"
6-Delete the index you downloaded
7-Take a look locally to dotsecure folder so you can see what folders/files you currently have
8-Now click "Add Index" button and select Restore Index Snapshot to upload the same index
9-Go back to dotsecure folder, you will see the .zip file that you uploaded is created inside “dotsecure” folder, as long with the repo folder defined in dotcms-config-cluster.properties
## Expected Behavior

System should not keep the .zip file that you uploaded neither keep the repo folder defined in dotcms-config-cluster.properties
## Current Behavior

The index snapshot (.zip file) that you uploaded is created inside “dotsecure” folder, as long with the repo folder defined in dotcms-config-cluster.properties
## Your Environment

Tested on branch "issue-9127-replace-current-index-backup-restore" // Ubuntu 14.04.1 // Postgres 9.3.5 // Firefox

**Comment by maurizo** [comment]
Fixed on #9127  by https://github.com/dotCMS/core/commit/f532ba4c572fa90f05dba6857dbbb04b080cdec8

**Comment by shaydotcms** [comment]
Passed QA, snapshot zip file doesn't get stored in dotsecure folder after it's uploaded from UI
Tested in master-3.7 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
