### ISSUE TITLE
Migrate ant task deploy-war-tomcat-dev to gradle

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9877]
This task needs to be moved from ant to gradle.
## Expected Behavior

Have a pure gradle deploy-war-tomcat-dev task instead of a wrapper to an ant task.
## Current Behavior

Task is currently in ant
## Possible Solution

Migrate to gradle
## Context

Having a pure gradle build

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/9992
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/393
PR License: https://github.com/dotCMS/license/pull/30
