### ISSUE TITLE
Migrate ant task deploy-war-tomcat-tests to gradle

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9878]
This task needs to be moved from ant to gradle.
## Expected Behavior

Have a pure gradle deploy-war-tomcat-tests task instead of a wrapper to an ant task.
## Current Behavior

Task is currently in ant
## Possible Solution

Migrate to gradle
## Context

Having a pure gradle build

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/9981
