### ISSUE TITLE
Move integration test folder one level up 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9881]
Integration folder needs to moved one level up so it lives under src/integration-test instead of src/test/integration
## Expected Behavior

Integration tests living under src/integration-test
## Current Behavior

Integration tests living under src/test/integration
## Possible Solution

Move 'em

**Comment by nollymar** [comment]
Task implemented on this branch: https://github.com/dotCMS/core/tree/issue-9781-new-gradle-layout/
