### ISSUE TITLE
Include IntegrationTestInitService to Integration tests under test.com.dotcms

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9883]
We need to include the call: IntegrationTestInitService.getInstance().init() to the @BeforeClass method of _integration_ tests living under test.com.dotcms.

Please make a list of the ones that are not able to successfully run by adding the mentioned call. 
Also please move the true unit tests found to an equivalent location under unit-test.

**Comment by erickgonzalez** [comment]
https://github.com/dotCMS/core/pull/9929

**Comment by erickgonzalez** [comment]
https://docs.google.com/a/dotcms.com/document/d/1qXIDyg1txsaAYtHGksCMxbxdAP_ae0FkiaqGtQshcME/edit?usp=sharing
