### ISSUE TITLE
Run integration tests via gradle

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9884]
We need to be able to run integration tests via gradle 
## Expected Behavior

./gradlew clean integrationTest
## Current Behavior

Not able to run them via gradle 
## Possible Solution

Have them run by running: 
./gradlew clean integrationTest
## Context

https://github.com/dotCMS/core/issues/9755

**Comment by nollymar** [comment]
Solved in #9878. PR: https://github.com/dotCMS/core/pull/9981
