### ISSUE TITLE
Unique property is not respected between language versions and not at all with whole numbers

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9886]
Two issues with unique not being properly respected on content:

1) Text fields that are unique should not allow duplicates in the same language version or ANY OTHER new contentlet language version.  If it is NOT the same contentlet, the field values should not be able to be replicated... but right now we are allowing the same value for a "unique" text field as long as they are two different language versions.  We need to make sure that the "unique" property is checking all existing language versions of the content for a duplicate value.

2) Text fields that have the "Whole Number" data type do not respect the "unique" property at all.  You can basically add the same number over and over again in the same language version.

## Expected Behavior

unique property should never allow two different contentlets to have the same value for that field - even if the language versions are different

-Text fields marked as whole numbers should respect the unique property.

## Current Behavior

whole numbers do not respect uniqueness at all
Text fields only respect uniqueness with the same language version

![unique](https://user-images.githubusercontent.com/1569167/27930962-bd7fbe86-6255-11e7-8e64-9d4d82a967b6.png)

## Steps to Reproduce (for bugs)

1. Create a new Content Type with a unique text field and a unique text field with the whole number datatype
2. Create two pieces of content in English that have the same number for field number two- bug
3. Create a piece of content in English with simple text for field one.  Then create a second piece of content IN SPANISH and place the same text in the first field.  - bug -uniqueness should be respected, regardless of language version when you are creating two totally different pieces of content.

Here is a screencast of demo.dotcms.com (3.6 version): http://screencast.com/t/KWprUmZBUoE

**Comment by DeanGonzalez** [comment]
Tested on 3.6 - Unique property is not respected by custom fields either :-(

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/12535

**Comment by bryanboza** [comment]
This isn't working if you try via push publish

**Comment by DeanGonzalez** [comment]
Not sure if that even should be checked during push publish.  I think that it should only be checked when you either create or save content locally.  Not sure if we should be checking this on push.  The error would require mismatched content authoring on sender and receiver in order to produce right.  Impossible to create this error if client is using a single point of content authoring.  And even then, when you edited either dupe unique on the receiver, you would be forced to change the value before you could save right?  Let me know if you want to discuss.

**Comment by erickgonzalez** [comment]
Bug:
1- Create a content type with 2 text fields
*Title: Datatype-> Text
*Number: Datatype-> Whole Number and Unique
2- Create a content in English with the values (title: test, number: 1)
3- Create a content in Spanish with the values (title: test2, number: 2)
4- Update the Spanish content with the value (number: 1)

The system allows it, and it shouldn't because only content with the same identifier can have the same unique value.

PR: https://github.com/dotCMS/core/pull/12649

**Comment by dsilvam** [comment]
Note to QA:
Field-Value Uniqueness only applies if contents are in the same Language, so this makes point 1. not valid. This was address on a different ticket.

Please focus only on point 2.

**Comment by shaydotcms** [comment]
Passed QA. Fix covers bullet point #2 as point #1 doesn't apply.
So when text fields have the "Whole Number" data type, "unique" property is respected, meaning same number in the same language version cannot be used again.

![image](https://user-images.githubusercontent.com/8741846/30975352-4ed8940a-a42f-11e7-8ba6-f935317bd81b.png)

![image](https://user-images.githubusercontent.com/8741846/30975308-3f7ca19a-a42f-11e7-9b15-827123269aaf.png)

Tested on master branch
Commit eb534ce3527c2e72c97b4b5c10607a76c85e45e5 on Sep 26, 2017
Mac OS 10.10 / Postgres 9.3.7 / Postgres 9.3.7 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8
