### ISSUE TITLE
Need to change runtime location of dot.jamm*.jar

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#9892]
Need to move the JAMM jar out of the WEB-INF/lib folder.  See comment from author's website (https://github.com/jbellis/jamm):

```
If you would like to use MemoryMeter in a web application, make sure
that you do NOT put this jar in WEB-INF/lib, as that may cause problems
since your code is accessing a MemoryMeter from a different class loader
than the one loaded by the -javaagent and won't see it as initialized.
```
## Expected Behavior

The presence and configuration of using JAMM as a javaagent should not negatively impact the performance and behavior of dotCMS when it is not being used to calculate cache region sizes.
## Current Behavior

Sites with heavy load and a large number of classes are running out of code cache memory which results in the JVM process being terminated.  reference:  https://my.dotcms.com/tickets/detail.dot?id=93963295-f061-4129-9d84-0b9be3573dae

I do not have evidence of this but suspect that the usage of GregorSamsa XML libraries in custom plugins may be what is exposing this problem and causing the extremely quick growth in the code cache utilization the client is seeing.
## Possible Solution

Based on the comment from origin website, seems to be as simple as moving the jar file and changing the startup.sh and startup.bat to point to the new location.  Of course some testing would be needed.
## Known Workarounds

Has not been tested and verified yet but should be able to implement the "Possible Solution" manually.
## Steps to Reproduce (for bugs)

Have not reproduced locally.  Client is having problems where nodes are crashing every couple of days.
## Client Environment
- dotCMS version used: 3.5.1
- Browser Name and version: N/A
- Operating System and version: Linux
- Application Server and version: included tomcat
- Java Brand and version: Azul
- Database and version: postgresql

**Comment by brentgriffin** [comment]
Would probably be good to upgrade JAMM jar version too - we are using a pretty ancient version -  should pick up latest version - there are some changes specifically for Java 8 that we do not currently have

**Comment by jcastro-dotcms** [comment]
PR for core: https://github.com/dotCMS/core/pull/9926
PR for tomcat: https://github.com/dotCMS/tomcat/pull/2

R&D teams, please review and comment on the changes proposed in the pull requests.

**Comment by jgambarios** [comment]
@gabbydotCMS Not sure if we should close this one as the javaagent changed as part of this ticket https://github.com/dotCMS/core/issues/11142

Current agent:
```
-javaagent:$DOTCMS_HOME/WEB-INF/lib/byte-buddy-agent-1.6.12.jar
```
