### ISSUE TITLE
NavTool: Get Parent Permissionable of a Page Asset may throw an Exception

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9893]
Once the NavTool generates a dynamic menu using the code provided [here](https://dotcms.com/docs/latest/navtool) in some cases this may throw a ClassCastException message in dotcms-velocity.log file.
## Expected Behavior

A NavResult object for a page (either legacy or page asset) will have "htmlpage" as type. 
## Current Behavior

Once we're pulling the parent permissionable of the current NavResult object we're evaluating, we can't know if it's a legacy page or a Page Asset, and also we only hit a deprecated API for legacy pages, therefore the ClassCastException message is thrown.
## Known Workarounds

As per customer's feedback (See Context section), re-publishing the page does the trick.
## Steps to Reproduce (provided by customer)
1. Create a page, labeled as Show On Menu and set a Sort Order different to zero.
2. To this page template, add the "Example: Display the Navigation for the Parent Folder" code from [this link](https://dotcms.com/docs/latest/navtool)
3. Check on a different browser that menu is displayed
4. Flush All Caches/Navigation tool cache on Maintenance portlet.
5. Check again the page on a different browser. Menu is lost and the ClassCastException message is thrown

Stacktrace: https://gist.github.com/joseorsini/a291a7f44ea7c18cb922ac2a0dc8c8c0
## Context

Related to Support Ticket https://my.dotcms.com/tickets/detail.dot?id=9011d690-a0b4-48c3-8cd9-efa62d3cb033
## Your Environment
- dotCMS version 3.5.1 and 3.6.0
- Google Chrome Browser, Safari Browser, IE.
- MacOS Sierra, Windows 7/8/10.
- Java 8
- Postgres, MSSQL Databases.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9894
