### ISSUE TITLE
Temporarily ignore tests in the list in #9785

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9899]
To be able to run all integration tests outside the container, we need to temporarily exclude the tests in the list that was put together here #9785. We will work on them later. 
## Expected Behavior

Ignore tests pointed out in the description
## Current Behavior

Those tests won't run outside the container given its nature.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9908
