### ISSUE TITLE
Pending Content Page editMode publish page errors on NG Iframe Component

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#9913]
On the Ng framework using the iframe to watch the edit mode of a content page, after you do some modification on the page and click the publish page link, the whole page is being refreshed and displaying the edit mode on the old browser UI,  not in the angular iframe UI
## Expected Behavior

After publishing the page, the same page should be loaded the iframe
## Current Behavior

After publishing, the page is refreshed completely. Showing itself the old framework instead of the NG one
## Steps to Reproduce (for bugs)
1. Go to Site browser
2. Preview or double click on a content page
3. add some content
4. click the publishing page link
## Your Environment

The issue only happens when you try to use the iframe legacy. this issue is related to https://github.com/dotCMS/core/issues/9811
- dotCMS version used: Master-3.7
- Browser Name and version: Any Browser
- Java Brand and version: Java 8

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10582
https://github.com/dotCMS/core-web/pull/259

**Comment by bryanboza** [comment]
Still having problems after publish the page https://www.screencast.com/t/QTRAFuH1J7B

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/10649
https://github.com/dotCMS/core-web/pull/263

**Comment by bryanboza** [comment]
Fixed, tested on master-4.0 // h2 // FF
