### ISSUE TITLE
Make work direct routes on Angular Router

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#9919]
We need to figure it out why the ngrx don't load direct hits to routes. Angular router does this... not sure if ngrx does it, but we need to check a little more.

More info:

https://github.com/dotCMS/core-web/pull/210#discussion_r82424336
- [ ] Make routes work on dev and prod
- [ ] Show Pattern Library only on dev

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/10017
https://github.com/dotCMS/core-web/pull/218

**Comment by bryanboza** [comment]
We still having problems, this time on FF, if you load any portlet and refresh the complete page, we still having the same url, but the portlet isn't loading...

**Comment by bryanboza** [comment]
Also after this change, we are unable to load the Rules Engine portlet, right now we are showing only a gray window and never loads...

**Comment by jgambarios** [comment]
The gray window in rules is just for the new UI and when there is no licence, will be fix it in: https://github.com/dotCMS/core/issues/9919

**Comment by bryanboza** [comment]
After the last changes and test again, now we are loading the needs license message, but after apply license, the system is showing a gray window and isn't loading the portlet.. 

Here the SC: https://gist.github.com/bryanboza/9a5b94169a85a44f85255a4aadf3bdf0

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/10018

**Comment by bryanboza** [comment]
Fixed, tested in the last master-3.7 // H2 // FF
