### ISSUE TITLE
Reordering items in a Key Value field is broken in 3.x

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#9935]
In the admin console reordering Key/Value items in a content type is broken, José Orsini diff’d the 2.5.6 and 3.3.1 and noticed a script is missing on the edit_field.jsp file for key/value fields. 
- dotCMS version used: 3.3.1
- Browser Name and version:
- Operating System and version:
- Application Server and version:
- Java Brand and version:
- Database and version:
- Application module (if apply):

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9936

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9936

**Comment by erickgonzalez** [comment]
Working as expected. You can reorder Keys/Values in a content.
