### ISSUE TITLE
Change site selector to primenNG

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9937]
In the new NG2 UI, the site selector need show a maximum number of sites, and after this show an scroll bar.

Right now when you create a lot of sites the system is showing the maximum and after this you can't see the other ones.
## Expected Behavior

We need show the scroll bar
## Current Behavior

We are showing the maximum number and after this, we can't see the other sites http://screencast.com/t/ZLp6i62Y
## Steps to Reproduce (for bugs)
- Create a lot of sites 
- Try to expand the site selector drop-down 
## Your Environment

Tested on master-3.7 // H2 // FF

**Comment by freddyucv** [comment]
Really this need fix in the DotSelect component

**Comment by bryanboza** [comment]
Also, we need handle sites with larger names: http://screencast.com/t/GNsRyVVya

**Comment by wezell** [comment]
I believe this should be changed to use a filtering select from primeng

**Comment by jgambarios** [comment]
Will be fixed in: https://github.com/dotCMS/core/issues/9803 using the http://www.primefaces.org/primeng/#/autocomplete

**Comment by jgambarios** [comment]
The initial work was made in https://github.com/dotCMS/core/issues/9803 (replacing the current dotSelect to the prime NG filtering select) but now we need to add ajax support to the text filtering in the component, we need to keep in mind the clients with hundreds of sites where a simple and total load of those sites is not an option. 

We need to do an initial load of maybe 20 records and then the user needs to use the text filter of the component to load the filtered records using ajax.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/10275 and https://github.com/dotCMS/core-web/pull/240

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF, Also we need fix the #10256
