### ISSUE TITLE
Undefined error when you try to change the host and the session has expired 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9943]
We are having an undefined error in the UI, this ehn you try to change the host from the host selector and the session has expired. 
## Expected Behavior

We should redirect to the login portlet 
## Current Behavior

We are showing an error window http://screencast.com/t/XzGO4n31YgI 
## Steps to Reproduce (for bugs)
- Login 
- Open the developer tools and in the cookies tab delete the JSESSIO_ID 
- Refresh the page 
## Your Environment

Tested on master 3.7 // MySQL // FF

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/220

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core-web/pull/225

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // h2 // FF
