### ISSUE TITLE
NPE deleting fields from any content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9954]
Related to #9798 

We are having a NPE with the ContentTypeUtil, this when you try to delete some filed from the content type. 
## Expected Behavior

We need delete the field and send the notifications without problems 
## Current Behavior

NPE on log 
## Your Environment

Tested on master-3.7 // H2 // FF

**Comment by wezell** [comment]
Let's hold on this and any new content type issues until we merge #9272

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9962

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
