### ISSUE TITLE
Contents: usage of delete method on Content API never deletes content

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9956]
We are building an OSGi Plugin that will attempt to delete files, according to https://github.com/dotCMS/core/issues/9341#issuecomment-231794909 and [this support ticket](https://my.dotcms.com/tickets/detail.dot?id=e9a23f13-d47d-4b95-badc-33bfdebb8dd2) but even though [we're calling a Delete Method that will attempt to delete the Content and all its versions](https://github.com/dotCMS/core/blob/master-3.7/src/com/dotmarketing/portlets/contentlet/business/ContentletAPIInterceptor.java#L482), it ends up calling [this one](https://github.com/dotCMS/core/blob/master-3.7/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1322), where versions are not taken into account so the deletion process is not triggered
## Possible Solution

Pre/Post Hooks and final call to Content API must have the same signature, respecting all params.
## Context

Related to Support Ticket https://my.dotcms.com/tickets/detail.dot?id=e9a23f13-d47d-4b95-badc-33bfdebb8dd2
## Your Environment
- dotCMS version 3.3.2
- Google Chrome.
- macOS Sierra 10.12
- Bundled Tomcat App Server
- Java 8
- Postgres 9.x.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9957

**Comment by nollymar** [comment]
Tested with two integration tests. PR: https://github.com/dotCMS/core/pull/10965
