### ISSUE TITLE
Categories are not included in the retrieved Content Maps

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#9961]
Related to #9736 
When you run a Lucene Query, you will see it's not displaying values for Category fields. It does retrieve categories when you run the API 
## Expected Behavior

You should be able to see values for Category fields when you run a Lucene query thru the Query Tool portlet.
## Current Behavior

Category fields are not being displayed when you run a Lucene Query.
## Steps to Reproduce (for bugs)

Follow same steps indicated in #9736 
1.Login to demo.dotcms.com site.
2.Go to Query Tool portlet.
3.Use the following Lucene Query  for searching contents: **+contentType:calendarEvent**

This is an example of a retrieved content map:

```
10.     Title:  dotCMS Online Training Session (w/ Image)
    Inode:  a2bf8b87-b141-4b78-8cda-751e5a2d8044
    Identifier:     9f303322-a908-4df0-8194-e1323f11b008

{modDate=2016-10-12 15:21:37.155, 
endDate=2015-12-25 16:00:00.0, 
link=http://dotcms.com, 
description=<p><img src="/dotAsset/461b2fa3-fb97-442e-b9ca-19e96d683f65.jpg" style="margin: 10px; float: right;" height="334" width="250" />Want to learn how to get the most from your dotCMS installation? This Webinar can help you. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
<p>Morbi in sem quis dui placerat ornare. Pellentesque odio nisi, euismod in, pharetra a, ultricies in, diam. Sed arcu. Cras consequat.</p>
<p>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.</p>,
title=dotCMS Online Training Session (w/ Image), 
recurrenceOccurs=weekly, 
recurrenceDayOfWeek=4, 
inode=a2bf8b87-b141-4b78-8cda-751e5a2d8044, 
file=2896c216-9d15-49b0-9ff9-6bfff113cc4a, 
__DOTNAME__=dotCMS Online Training Session (w/ Image), 
disabledWYSIWYG=[], 
recurrenceEnd=2016-10-12 00:00:00.0, 
recurrenceDayOfMonth=0, 
host=48190c8c-42c4-46af-8d1a-0cd5db894797, 
lastReview=2016-10-12 15:21:37.149, 
recurrenceStart=2015-12-25 15:00:00.0, 
stInode=f6259cc9-5d78-453e-8167-efd7b72b2e96, 
recurrenceWeekOfMonth=3, 
recurs=false, 
owner=dotcms.org.1, 
identifier=9f303322-a908-4df0-8194-e1323f11b008, 
image=9825d1e6-c89f-4110-af92-a242bb42345b, 
noRecurrenceEnd=false, 
urlTitle=dotcms-online-training-session-w-image, 
languageId=1, recurrenceDaysOfWeek=1,2,3,4,5,6,7,, 
tags=meeting,training, 
recurrenceInterval=1, 
folder=SYSTEM_FOLDER, 
recurrenceDatesToIgnore=1318433280000 1352476800000 1356105600000, 
recurrenceMonthOfYear=10, 
sortOrder=0, 
modUser=dotcms.org.1, 
startDate=2015-12-25 15:00:00.0}
```

As you can see, Category's field is not showing but if you open the content, it's there:
![image](https://cloud.githubusercontent.com/assets/8741846/19324984/4c8bb03c-9081-11e6-9e16-f80511496bfc.png)

Retrieving the content thru the API shows the Categories:
http://demo.dotcms.com/api/content/id/9f303322-a908-4df0-8194-e1323f11b008
![image](https://cloud.githubusercontent.com/assets/8741846/19325153/0f1671f0-9082-11e6-8646-a0d9956e80c3.png)
## Your Environment
- dotCMS version used: master-3.7 // demo.dotcms.com
- Browser Name and version: Firefox v45.0.1
- Operating System and version: Mac OS 10.10.5
- Application Server and version: Tomcat 8
- Java Brand and version: Java 8
- Database and version: Postgres 9.3.5

**Comment by maurizo** [comment]
Passed QA.
Tested on MySQL/Oracle/Postgresql/MSSQL, with FF/Chrome.
