### ISSUE TITLE
Snapshot functionality generating dotSecure folder inside tomcat when pointing to external

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9973]
If dotSecure is configured to live outside tomcat, via DYNAMIC_CONTENT_PATH, the snapshot functionality creates it under tomcat instead of using the former. 

## Expected Behavior
Snapshot functionality should use indicated path for dotsecure

## Current Behavior
It creates a dotsecure folder even though there is one outside of tomcat pointed by DYNAMIC_CONTENT_PATH

## Steps to Reproduce (for bugs)
1. Set DYNAMIC_CONTENT_PATH to a path outside tomcat 
2. Snapshot an index (System->Maintenance->Index->Right Click on Index->Download Index Snapshot)

**Comment by maurizo** [comment]
The solution to this is to set the path on **"es.path.repo"** to an absolute path just as it is done with **"es.path.data"** property.
