### ISSUE TITLE
Renaming downloaded snapshot makes it fail when restoring

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9974]
If an snapshot is downloaded and renamed, it then fails when it is tried to restore it
## Expected Behavior

Should be restored regardless of the name
## Current Behavior

Unable to restore
## Possible Solution

Grab the snapshot name from the extracted zip, it starts with "snapshot-". 
## Steps to Reproduce (for bugs)
1.  Snapshot an index (System->Maintenance->Index->Right Click on Index->Download Index Snapshot)
2. Rename downloaded zip
3. Deactivate then Close index
4. Attempt to restore snapshot

**Comment by maurizo** [comment]
Fixed on #9921 by https://github.com/dotCMS/core/commit/85b76c452a01f8a9aede1f58986d186cf1259f5e

**Comment by maurizo** [comment]
Passed QA.
Tested on FF/Chrome.
