### ISSUE TITLE
Recover password isn't working in the new NG2 UI

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9979]
After the changes in the #9835 

Now we are unable to recover password from the new NG2 UI 

**FYI:** This is working normally in the old UI 
## Expected Behavior

we should be able to recover password without problems 
## Current Behavior

We are having the follow error and the mails is not sent
"NetworkError: 500 Internal Server Error - http://localhost:8082/api/v1/forgotpassword"
## Your Environment

Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
Fixed in: https://github.com/dotCMS/core/issues/9919

**Comment by bryanboza** [comment]
After this fix we are unable to resolve the generated URL: http://screencast.com/t/mCmPZWqw

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10068

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7 // H2 // FF
