### ISSUE TITLE
Adapt rest of Integration tests to run outside the container

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9980]
The tests in the following packages need to be properly initialized to run outside the container:
- integration-test.java.com.ettrema
- integration-test.java.com.liferay
- integration-test.java.org.apache.velocity.runtime.parser.node

In addition, some of these test might be true unit tests (unlikely , in which case, they would need to be moved to test package. 
## Expected Behavior

All tests in mentioned packages running outside the container
## Current Behavior

Tests in mentioned packages can run only via the test servlet
## Possible Solution

Include the call: IntegrationTestInitService.getInstance().init() to the @BeforeClass method

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/10006
