### ISSUE TITLE
Workflows: Sub-actions throw NPE if no values were entered on required fields

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9986]
Currently, we are allowed to add Workflow Sub-actions with static values or on-the-fly modifiers, like "Set Value" or "Comment on Workflow" actions. These sub-actions, once added to a Workflow Step, demand a value on their fields so once the Step is triggered, we can modify the current workflow of the added/edited content.
## Expected Behavior

Once we add these values, we should be prompted to edit these Sub-actions fields values, again, required on the UI.
## Current Behavior

We add these Sub-actions to the Workflow step. Once the Step is triggered and the chain of Sub-actions is executed, exceptions are thrown in logfiles: https://gist.github.com/joseorsini/175c5ab25b9032561e54c6defc1cf3fe
## Possible Solution

Once the Set Value, Comment On Workflow or any other Sub-action that require a value on its definition, the Sub-action is added to the list of Actions AFTER it was edited.
## Known Workarounds

Manually edit the sub-action once it was created/added to the Actions list of a Workflow Step. 
## Steps to Reproduce
1. For Document Management Workflow Scheme, go to Editing -> Save for Review Step
2. Remove the "Notify Assignee" sub-action and add "Comment on Workflow".
3. Go to Website Browser and click on Add New -> Image or file -> Document.
4. Upload an image to the File Asset field and click on "Save for Review" button.
5. Comment anything on the pop up window and click on "save" button
6. Null message is displayed on backend and stacktrace from above is displayed on logfiles

<img width="1330" alt="screen shot 2016-10-17 at 4 07 50 pm" src="https://cloud.githubusercontent.com/assets/1717110/19453630/10799896-9484-11e6-9aa4-446b2a1a36a2.png">

Error is thrown [here](https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/CommentOnWorkflowActionlet.java#L45) because the Comment On Workflow Sub-Action does not have a static value on it once it was added to the list of Sub-Actions for this Workflow Step.
## Context

The error message in backend is not descriptive at all (it only shows "null"), and for limited users editing contents tied to a similar Workflow Scheme, they may not have access to the Workflow Scheme definition, so it would require an admin for editing this Sub-action and set a static value. As described early, it's better to ask the user to fill in the required values for this and similar Sub-Actions once the user attempts to add it to the list of sub-actions for a Workflow Step.
## Your Environment

- dotCMS 3.6.0 and master-3.7.
- Google Chrome browser.
- macOS Sierra 10.12.
- Tomcat 8.0.18.
- Java 8.
- Postgres 9.4.1, MySQL 5.6.x.

**Comment by wezell** [comment]
I am not seeing this as a bug - when you add the "Comment on the Workflow" subaction, you need to enter the comment that you want to add.

Likewise, the setValue subaction.  I mean, maybe we need a null check when adding the subaction whose field is required, but this is not a critical issue, unless I am missing something.
