### ISSUE TITLE
TinyMCE: Add support of Legacy Files on FileBrowserDialog Selector

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9994]
The link plugin on TinyMCE Editor allows the user to select a Page or File in order to insert a link on the field body.
## Expected Behavior

All file types should be available for selection, including legacy files
## Current Behavior

Once Multilingual Files was introduced on 3.6.0, Legacy Files cannot be displayed and the File Selector just shows a "Loading" Message. The BrowserAPI class does not add language info to Legacy Files, which is required by the FileBrowserDialog feature (File selector on TinyMCE).
## Possible Solution

Add the default language Id as param for Legacy Files.
## Known Workarounds

No workarounds are available at this point.
## Steps to Reproduce (for bugs)
1. Make sure you have Legacy Files under a folder. 
2. Go to Content Search and create a new Content(Generic) content.
3. On the TinyMCE, click on "Insert/Edit Link" button.
4. For "Url" field, click on the "Search button".
5. In the pop-up window, go to the folder where Legacy Files are stored. Screen will show a "Loading" message and the Javascript console will return a NullPointerException.
## Context

For clients with legacy files, they cannot create links on WYSIWYG fields because of this bug. 
Reported on:    https://my.dotcms.com/tickets/detail.dot?id=90aae4e3-744c-4860-a756-5b0793911e4f
## Your Environment
- dotCMS 3.6.0
- Google Chrome Browser.
- macOS Sierra 10.12.
- Tomcat 8.0.18.
- Java OpenJDK 8.
- Postgres 9.3.x+

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9995

**Comment by wezell** [comment]
Legacy files are no longer in 4.0
