### ISSUE TITLE
Gradle Migration Enhancements

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#9999]
After the Gradle migration some details came up and should be fixed.
## Expected Behavior

- Delete core/dist folder after createDist task is run.
- createDist output should be: dotcms_3.7.0.zip and dotcms_3.7.0.tgz under core/dist-output folder.
- Eclipse does not display errors after dotCMS project is imported.
- test task always logs execution results.
- When ConfigTestHelper._setupFakeTestingContext() is called, properties files are loaded successfully.
- tomcat8/temp folder exists after deployWarTomcatBackup task is run but folders created under it are removed after task execution.
## Current Behavior

- Eclipse errors come up when the IDE validates hibernate.cfg.xml, sampleSavedFormBuilderForm.xml and weblogic.xml.
- When createDist task is run the created folders under core/dist/ are not being removed.
- The compressed files (.zip and .tgz) generated with the distribution version do not keep the standard naming.
- When deployWarTomcatBackup task is run the folder tomcat8/temp is fully deleted. This folder should exist when the server starts to avoid catalina exceptions, but folders created under tomcat8/temp during deployWarTomcatBackup execution should be removed.
- test task is skipped by Gradle if it was run previously and there has not been changes in test sources since then; test task should always run.
- test task is not logging results when all unit tests pass.
- ConfigTestHelper.java is not considering the new Gradle layout to load test resources.
## Context

core repo with Gradle layout.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/10000

**Comment by dsilvam** [comment]
Second PR: https://github.com/dotCMS/core/pull/10025
